### PR TITLE
fix(starknet_api): data gas bounds part of the tx hash

### PR DESCRIPTION
**Pull request by dorimedini-starkware**

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2118)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @Yoni-Starkware)

___
*[`crates/starknet_api/src/transaction_hash.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2118#-OBuYdPACvUi28pmaUFo:-OBuYdPACvUi28pmaUFp:b-4gu3lh) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0872e3ec175828db8cf4cbd7c79976cd4a7fe8d/crates/starknet_api/src/transaction_hash.rs#L36)):*
> ```XML
> mod transaction_hash_test;
> 
> type ResourceName = [u8];
> ```

no longer exactly 7 chars...



_Code quote:_
```XML
type ResourceName = [u8];
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2118)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @nimrod-starkware and @Yoni-Starkware)

___
*[`crates/starknet_api/src/transaction_hash.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2118#-OBuY0BF4raZMcK1lJr5:-OBuhh3w-Rq2EKzFWpD7:be8025n) ([raw file](https://github.com/starkware-libs/sequencer/blob/fda3276be4d819ddf94c9c3e9305132efecff8e1/crates/starknet_api/src/transaction_hash.rs#L40)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@Yoni-Starkware why was there a `\0` prefix on these?
in the OS I don't see this
</blockquote></details>

actually, I think this was the issue:
```
let concat_bytes =
        [[0_u8].as_slice(), resource_name, max_amount.as_slice(), max_price.as_slice()].concat();
```
this assumes `resource_name` is exactly 56 bits, i.e. 7 bytes. `L1_GAS` and `L2_GAS` are 6 bytes, so they needed a preceding `\0`

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2118)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @nimrod-starkware and @Yoni-Starkware)

___
*[`Cargo.lock` line 10531 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2118#-OBuiYG4DfWnoUtj-Eu8:-OBuiYG4DfWnoUtj-Eu9:bmhl666) ([raw file](https://github.com/starkware-libs/sequencer/blob/e97d2d43aec608b3b10368c300021fa0dfef2dc8/Cargo.lock#L10531)):*
> ```TOML
>  "async-trait",
>  "futures",
>  "serde",
> ```

probably from [here](https://reviewable.io/reviews/starkware-libs/sequencer/2072)...



_Code quote:_
```TOML
"serde",
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2118)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/starknet_api/src/transaction_hash.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2118#-OBuY0BF4raZMcK1lJr5:-OBuiT6m0ZLJK-4ispJf:bjfrsi1) ([raw file](https://github.com/starkware-libs/sequencer/blob/fda3276be4d819ddf94c9c3e9305132efecff8e1/crates/starknet_api/src/transaction_hash.rs#L40)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

actually, I think this was the issue:
```
let concat_bytes =
        [[0_u8].as_slice(), resource_name, max_amount.as_slice(), max_price.as_slice()].concat();
```
this assumes `resource_name` is exactly 56 bits, i.e. 7 bytes. `L1_GAS` and `L2_GAS` are 6 bytes, so they needed a preceding `\0`
</blockquote></details>

Is this really needed? we don't need this in the OS (this part is in the msb so it doesn't affect the hash)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2118)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @Yoni-Starkware)

___
*[`crates/starknet_api/src/transaction_hash.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2118#-OBuY0BF4raZMcK1lJr5:-OBujU2E2RX54dhsPKVj:bqtj9vq) ([raw file](https://github.com/starkware-libs/sequencer/blob/fda3276be4d819ddf94c9c3e9305132efecff8e1/crates/starknet_api/src/transaction_hash.rs#L40)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Is this really needed? we don't need this in the OS (this part is in the msb so it doesn't affect the hash)
</blockquote></details>

the way the felt is constructed, yes.
note that `ResourceName` is `[u8; 7]` - i.e. the type itself is exactly 7 bytes.
seems like this was done for safety

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2118#-:-OBv16cF0ZGmPtSr6HNL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by nimrod-starkware — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2118#-:-OBxzeTJ9HNtOPORJnJ-:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2118)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2118#-OByZaVjDg7S-3Nb1DdY:-OByZaVjDg7S-3Nb1DdZ:b-2y5001) (no related file):*
[py side](https://reviewable.io/reviews/starkware-industries/starkware/36274)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2118)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2118#-OByZaVjDg7S-3Nb1DdY:-OC2qfOc9PMMXw19B8ZT:b-m6tfm3) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[py side](https://reviewable.io/reviews/starkware-industries/starkware/36274)
</blockquote></details>

passed

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2118)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
