### PR TITLE
refactor(papyrus_state_reader): code cleanup + caching with sierra only if native flag is on

### PR DESCRIPTION
**Pull request by noaov1**

### CODE REVIEW

**Review by avi-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2926)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2926#-:-OEt47GVEg4BoaKE5r53:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Comment by avi-starkware** [comment]
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2926#-OEt7BL56KMqlZitLNL6:-OEt7BL56KMqlZitLNL7:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/73a191d9752e50d00ac0600475c6355873ac7ab0/crates/papyrus_state_reader/src/papyrus_state.rs#L84)):*
> ```XML
>             #[cfg(feature = "cairo_native")]
>             let cached_casm = if !self.contract_class_manager.run_cairo_native() {
>                 CachedCasm::WithoutSierra(runnable_casm);
> ```





_Suggestion:_
```XML
                CachedCasm::WithoutSierra(runnable_casm)
```

**Review by avi-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2926)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2926)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @avi-starkware)

___
*[`crates/papyrus_state_reader/src/papyrus_state.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2926#-OEt7BL56KMqlZitLNL6:-OEt7YbG1og7xS1cw9xK:bgwqdjn) ([raw file](https://github.com/starkware-libs/sequencer/blob/73a191d9752e50d00ac0600475c6355873ac7ab0/crates/papyrus_state_reader/src/papyrus_state.rs#L84)):*
> ```XML
>             #[cfg(feature = "cairo_native")]
>             let cached_casm = if !self.contract_class_manager.run_cairo_native() {
>                 CachedCasm::WithoutSierra(runnable_casm);
> ```

Nice! I wonder how come the the build with native feature flag was completed successfully. 
Done.

**Pull request merged**
