### PR TITLE
feat(mempool_infra): add configuration to set number of retries of se…

### PR DESCRIPTION
**Pull request by uriel-starkware**
…nding requests

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/245)

### CODE REVIEW

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/245)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`crates/mempool_infra/src/component_client/definitions.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3CKNnU7BrlDccOIuB2:-O3CKNnU7BrlDccOIuB3:b-4r05bi) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/src/component_client/definitions.rs#L21)):*
> ```XML
>     UnexpectedResponse(String),
>     #[error("Retries number is zero.")]
>     ZeroRetries,
> ```

I must add that there is another way to handle 'retries' equal 0. If 'retries' specifies the extra request sending. This way, it can be 0, and this error is unneeded.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/245)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client/definitions.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3CKNnU7BrlDccOIuB2:-O3CQT8JC_6GZx50CUYj:b-acim30) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/src/component_client/definitions.rs#L21)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I must add that there is another way to handle 'retries' equal 0. If 'retries' specifies the extra request sending. This way, it can be 0, and this error is unneeded.
</blockquote></details>

I don't understand the comment.
___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3CQY2K8l0puymHxy9Z:-O3CQY2K8l0puymHxy9_:b3vq9wd) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/src/component_client/remote_component_client.rs#L21)):*
> ```XML
>     uri: Uri,
>     client: Client<hyper::client::HttpConnector>,
>     retries: u16,
> ```

We typically use `usize` for counters, no?



_Code quote:_
```XML
u16
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/245)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3CdaDA4uIcEHLHVxVe:-O3CdaDA4uIcEHLHVxVf:bxn6rgr) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/src/component_client/remote_component_client.rs#L44)):*
> ```XML
> 
>     pub async fn send(&self, component_request: Request) -> ClientResult<Response> {
>         let mut res = Err(ClientError::ZeroRetries);
> ```

Please remove, we prefer to avoid using mut vars if possible. 



_Code quote:_
```XML
let mut res = Err(ClientError::ZeroRetries);
```
___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3Cdq2X0m5L1lR3YiO7:-O3Cdq2X0m5L1lR3YiO8:b-ksncj9) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/src/component_client/remote_component_client.rs#L46)):*
> ```XML
>         let mut res = Err(ClientError::ZeroRetries);
>         for _ in 0..self.retries {
>             res = component_request
> ```

Change to `let res`



_Code quote:_
```XML
res
```
___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3CdlhqDxP308cxAKMZ:-O3CdlhqDxP308cxAKM_:bc76vgy) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/src/component_client/remote_component_client.rs#L54)):*
> ```XML
>             }
>         }
>         res
> ```

Replace with `Err(ClientError::ZeroRetries)`



_Code quote:_
```XML
res
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/245)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3CfYXA61XZsRCagAQt:-O3CfYXA61XZsRCagAQu:b-7hshzv) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/src/component_client/remote_component_client.rs#L66)):*
> ```XML
>                 .expect("Request building should succeed"),
>         )
>     }
> ```

Shouldn't this be part of the `Client` code, and get `request: Request` as an arg instead of `uri: Uri`?
Also, please rename the fn to reflect this is not a "component request" but a "remote/http request".



_Code quote:_
```XML
    fn construct_request(&self, uri: Uri) -> RemoteComponentClientRequest {
        RemoteComponentClientRequest(
            HyperRequest::post(uri)
                .header(CONTENT_TYPE, APPLICATION_OCTET_STREAM)
                .body(Body::from(serialize(self).expect("Request serialization should succeed")))
                .expect("Request building should succeed"),
        )
    }
```
___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3Cg1taCKlXtTk3vH-_:-O3Cg1taCKlXtTk3vH-a:b-rvaiov) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/src/component_client/remote_component_client.rs#L71)):*
> ```XML
> impl<Request: Serialize> ConstructRequest for Request {}
> 
> struct RemoteComponentClientRequest(HyperRequest<Body>);
> ```

Please use named structs.



_Code quote:_
```XML
struct RemoteComponentClientRequest(HyperRequest<Body>);
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/245)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3CgSgZDxx9mdwvOAVA:-O3CgSg_-XIZw1W5EgTD:b19vscp) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/src/component_client/remote_component_client.rs#L48)):*
> ```XML
>             res = component_request
>                 .construct_request(self.uri.clone())
>                 .try_send_request(&self.client)
> ```

I suggest making this a function of the client that takes the request as an arg.



_Code quote:_
```XML
.try_send_request(&self.client)
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/245)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3CgoyM3afjRS0vd7gj:-O3CgoyM3afjRS0vd7gk:bcuvro2) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/tests/component_server_client_http_test.rs#L152)):*
> ```XML
>     ComponentAClient::new(LOCAL_IP, port, RETRIES)
> }
> ```

Please add a suitable test.

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/245)* status: 0 of 3 files reviewed, 10 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3CQY2K8l0puymHxy9Z:-O3D56Ay02oWNFaJSqwT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/src/component_client/remote_component_client.rs#L21)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

We typically use `usize` for counters, no?
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3Cgwvm0pqt7LB_QvPk:-O3D57OM0mcG8AaKHcdF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/src/component_client/remote_component_client.rs#L31)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to `max_retries`
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3CdaDA4uIcEHLHVxVe:-O3D590TALQcvSLpp3LA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/src/component_client/remote_component_client.rs#L44)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please remove, we prefer to avoid using mut vars if possible.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3Cdq2X0m5L1lR3YiO7:-O3D59zgAgLyRn_IY89L:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/src/component_client/remote_component_client.rs#L46)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Change to `let res`
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3CgSgZDxx9mdwvOAVA:-O3D5AiX3wVyChxSUucC:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/src/component_client/remote_component_client.rs#L48)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I suggest making this a function of the client that takes the request as an arg.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3CdlhqDxP308cxAKMZ:-O3Cro_b12554q7IUXhb:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/src/component_client/remote_component_client.rs#L54)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Replace with `Err(ClientError::ZeroRetries)`
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3CfYXA61XZsRCagAQt:-O3Ct09C4pE6elQJmhTr:b-amk3kc) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/src/component_client/remote_component_client.rs#L66)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Shouldn't this be part of the `Client` code, and get `request: Request` as an arg instead of `uri: Uri`?
Also, please rename the fn to reflect this is not a "component request" but a "remote/http request".
</blockquote></details>

Ok, I made it the `Client`s code
___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3Cg1taCKlXtTk3vH-_:-O3CrxLg2m7BJMd0-HGq:bi4j8kv) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/src/component_client/remote_component_client.rs#L71)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please use named structs.
</blockquote></details>

Nevermind as I added its code to the `Client` code and removed this struct entirely
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3CgoyM3afjRS0vd7gj:-O3Cs4ZZ5Z7csJ-4xM3p:b6i8wxz) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/tests/component_server_client_http_test.rs#L152)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add a suitable test.
</blockquote></details>

If you don't mind, will be in a following PR
___
*[`crates/mempool_infra/src/component_client/definitions.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3CKNnU7BrlDccOIuB2:-O3CnCzkEZIcBnfwJFB_:b-rx9g73) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/src/component_client/definitions.rs#L21)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I don't understand the comment.
</blockquote></details>

talked about it on slack

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/245)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3R0Lk13YW1cVGht_Lt:-O3R0Lk13YW1cVGht_Lu:blp3a4r) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f10ed5f2381c3ea5675442f04cc55e49b91bdfe/crates/mempool_infra/src/component_client/remote_component_client.rs#L52)):*
> ```XML
>         }
>         let http_request = self.construct_http_request(&component_request);
>         self.try_send(http_request).await
> ```

Please add comments explaining why the request is constructed both in and out of the loop block.



_Code quote:_
```XML
        for _ in 0..self.max_retries {
            let http_request = self.construct_http_request(&component_request);
            let res = self.try_send(http_request).await;
            if res.is_ok() {
                return res;
            }
        }
        let http_request = self.construct_http_request(&component_request);
        self.try_send(http_request).await
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3CgoyM3afjRS0vd7gj:-O3R-h-MDMgSvX7_e1Rt:bc9q77e) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/tests/component_server_client_http_test.rs#L152)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

If you don't mind, will be in a following PR
</blockquote></details>

Why though? Unless there's some sort of emergency, we prefer adding the code and its tests together.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/245)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3R1RA1E4aoohGbV9hW:-O3R1RA1E4aoohGbV9hX:bjmq658) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f10ed5f2381c3ea5675442f04cc55e49b91bdfe/crates/mempool_infra/src/component_client/remote_component_client.rs#L49)):*
> ```XML
>             if res.is_ok() {
>                 return res;
>             }
> ```

Do all error codes merit a retry? Are there errors in which it makes more sense to abandon the connection?



_Code quote:_
```XML
            if res.is_ok() {
                return res;
            }
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/245)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3CgoyM3afjRS0vd7gj:-O3R2UWUCSmr1Rhp8gpz:b-12nwef) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd98a3551d8ca899cf6df48ebaa3713843f93ddf/crates/mempool_infra/tests/component_server_client_http_test.rs#L152)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Why though? Unless there's some sort of emergency, we prefer adding the code and its tests together.
</blockquote></details>

Rephrasing "Emergency" -- significantly blocking something/someone from making progress

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/245)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 45 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3bkUo36utHKkmlp4v3:-O3bkUo36utHKkmlp4v4:b-okzrhg) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5dde78bfe03a8d0edeb88c8cdd801669f7a133f/crates/mempool_infra/src/component_client/remote_component_client.rs#L45)):*
> ```XML
>     pub async fn send(&self, component_request: Request) -> ClientResult<Response> {
>         // We construct 'http_request' and try sending request 'max_retries' of times,
>         // returning the first successful response.
> ```

Please change to:

Construct and request, and send it up to 'max_retries' times. Return if received a successful response.



_Code quote:_
```XML
        // We construct 'http_request' and try sending request 'max_retries' of times,
        // returning the first successful response.
```
___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 54 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3blQWI-erNMcTeFBSm:-O3blQWI-erNMcTeFBSn:b-dssges) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5dde78bfe03a8d0edeb88c8cdd801669f7a133f/crates/mempool_infra/src/component_client/remote_component_client.rs#L54)):*
> ```XML
>         }
>         // If not successful, do it one last time outside of the loop and returning the result.
>         // 'http_request is not clonable so we construct it here again.
> ```

Please change to:

Construct and send the request, return the received respone regardless whether it successful or not.



_Code quote:_
```XML
        // If not successful, do it one last time outside of the loop and returning the result.
        // 'http_request is not clonable so we construct it here again.
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 259 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3bm0kl10igBXqmfSaK:-O3bm0kl10igBXqmfSaL:bq2xwfx) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5dde78bfe03a8d0edeb88c8cdd801669f7a133f/crates/mempool_infra/tests/component_server_client_http_test.rs#L259)):*
> ```XML
> #[tokio::test]
> async fn test_retry_request() {
>     // spawn a server that responses with OK every other request.
> ```

Capitalize.



_Code quote:_
```XML
s
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 305 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3bnGjh2eGz2EUcbEZm:-O3bnGji0xe-WDzq4U1-:b-tev0nh) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5dde78bfe03a8d0edeb88c8cdd801669f7a133f/crates/mempool_infra/tests/component_server_client_http_test.rs#L305)):*
> ```XML
>     let a_client_no_retry = ComponentAClient::new(LOCAL_IP, RETRY_REQ_PORT, 0);
>     let expected_error_contained_keywords = [DESERIALIZE_RES_ERROR_MESSAGE];
>     verify_error(a_client_no_retry.clone(), &expected_error_contained_keywords).await;
> ```

The current setting requires keeping track of the implicit 'test state' to understand why things happen the way they do (whether the current server state is `true` or `false`, dependent on the number of previous invocations).
This is very implicitly depicted in the test, which IMO is suboptimal.

I'd suggest to either split into two different tests, or to be very explicit throughout.
For example, you could change 
` // Assert success when 'max_retries' is 1.`
To
 // The current server state is initially `false`, hence the first attempt returns an error and sets the server state to `true`. The second attempt (first retry) therefore returns a 'success', while setting the server state to `false` yet again.

And then another similar comment before the `max_retries=0` part.



_Code quote:_
```XML
    // Assert success when 'max_retries' is 1.
    let a_client_retry = ComponentAClient::new(LOCAL_IP, RETRY_REQ_PORT, 1);
    assert_eq!(a_client_retry.a_get_value().await.unwrap(), VALID_VALUE_A);

    // Assert failure when 'max_retries' is 0.
    let a_client_no_retry = ComponentAClient::new(LOCAL_IP, RETRY_REQ_PORT, 0);
    let expected_error_contained_keywords = [DESERIALIZE_RES_ERROR_MESSAGE];
    verify_error(a_client_no_retry.clone(), &expected_error_contained_keywords).await;
```

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/245)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 45 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3bkUo36utHKkmlp4v3:-O3bs9PG8sNS7KUAmI_l:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5dde78bfe03a8d0edeb88c8cdd801669f7a133f/crates/mempool_infra/src/component_client/remote_component_client.rs#L45)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to:

Construct and request, and send it up to 'max_retries' times. Return if received a successful response.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 54 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3blQWI-erNMcTeFBSm:-O3bs9r75o-XJ1SMxDGE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5dde78bfe03a8d0edeb88c8cdd801669f7a133f/crates/mempool_infra/src/component_client/remote_component_client.rs#L54)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to:

Construct and send the request, return the received respone regardless whether it successful or not.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 305 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3bnGjh2eGz2EUcbEZm:-O3bszzs5Y_hF0wkX_yP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5dde78bfe03a8d0edeb88c8cdd801669f7a133f/crates/mempool_infra/tests/component_server_client_http_test.rs#L305)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

The current setting requires keeping track of the implicit 'test state' to understand why things happen the way they do (whether the current server state is `true` or `false`, dependent on the number of previous invocations).
This is very implicitly depicted in the test, which IMO is suboptimal.

I'd suggest to either split into two different tests, or to be very explicit throughout.
For example, you could change 
` // Assert success when 'max_retries' is 1.`
To
 // The current server state is initially `false`, hence the first attempt returns an error and sets the server state to `true`. The second attempt (first retry) therefore returns a 'success', while setting the server state to `false` yet again.

And then another similar comment before the `max_retries=0` part.
</blockquote></details>

Done.

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/245)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 259 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/245#-O3bm0kl10igBXqmfSaK:-O3btDV_-T8p_LlM_0He:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5dde78bfe03a8d0edeb88c8cdd801669f7a133f/crates/mempool_infra/tests/component_server_client_http_test.rs#L259)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Capitalize.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/245#-:-O3bvnOp5FtyZvLQCEqD:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved

**Review by uriel-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/245)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)

**Pull request merged**
