### PR TITLE
test(blockifier): parametrize test_actual_fee_gt_resource_bounds by resource bounds types

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1330)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1330?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1330** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1330?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1322** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1322?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1321** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1321?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1314** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1314?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1313** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1313?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1312** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1312?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1311** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1311?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1310** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1310?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1309** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1309?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1308** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1308?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1307** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1307?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1306** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1306?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yoavGrs — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1330)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1330#-OAlPHO4EqxGbppYx9Ml:-OAlPHO4EqxGbppYx9Mm:b-b52430) (no related file):*
The tests here are quite similar: `test_insufficient_new_resource_bounds`, `test_insufficient_resource_bounds` and `test_actual_fee_gt_resource_bounds`. Do we need them all?

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1330)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1330#-OAlPHO4EqxGbppYx9Ml:-OAlSgw-BLj7Prp8kKvO:bbfqifw) (no related file):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

The tests here are quite similar: `test_insufficient_new_resource_bounds`, `test_insufficient_resource_bounds` and `test_actual_fee_gt_resource_bounds`. Do we need them all?
</blockquote></details>

1. `test_insufficient_new_resource_bounds` checks pre-validation of minimal gas amounts for new resource bounds (I'll rename)
2. `test_insufficient_resource_bounds` checks the same, but for deprecated bounds (max fee / L1 bounds) - also, I'll rename
3. `test_actual_fee_gt_resource_bounds` tests post-execution

___

**Review by yoavGrs — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1330)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
