### PR TITLE
feat(mempool): add pending transaction type

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/439)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/439)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4Z9kxB-fwmaawPd5w2:-O4Z9kxB-fwmaawPd5w3:b-s5rbm4) ([raw file](https://github.com/starkware-libs/sequencer/blob/55308a23d5adbfcfb7f2c830b138467ccb0f31cd/crates/mempool/src/mempool.rs#L238)):*
> ```XML
>         }
>     }
> ```

Aren't there these getters in SN API?
___
*[`crates/mempool/src/transaction_queue.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4ZAXNJCoJpCfwkQUhn:-O4ZAXNJCoJpCfwkQUho:bols8kh) ([raw file](https://github.com/starkware-libs/sequencer/blob/55308a23d5adbfcfb7f2c830b138467ccb0f31cd/crates/mempool/src/transaction_queue.rs#L71)):*
> ```XML
> }
> 
> /// Encapsulates a transaction reference to assess its order (i.e., priority).
> ```

Update comment.



_Code quote:_
```XML
priority
```
___
*[`crates/mempool/src/transaction_queue.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4ZAafg0450NUn5fQCt:-O4ZAafg0450NUn5fQCu:bvbjevz) ([raw file](https://github.com/starkware-libs/sequencer/blob/55308a23d5adbfcfb7f2c830b138467ccb0f31cd/crates/mempool/src/transaction_queue.rs#L72)):*
> ```XML
> 
> /// Encapsulates a transaction reference to assess its order (i.e., priority).
> /// A transaction with gas price below the threshold. Sorted according to the gas price.
> ```

This belongs next to the data structure that will be holding them; it's our of scope for the transaction struct itself.



_Code quote:_
```XML
/// A transaction with gas price below the threshold. Sorted according to the gas price.
```
___
*[`crates/mempool/src/transaction_queue.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4ZB5Li8l2r0Q3fkYYk:-O4ZB5LjCIYXto70cbP-:bn7dpch) ([raw file](https://github.com/starkware-libs/sequencer/blob/55308a23d5adbfcfb7f2c830b138467ccb0f31cd/crates/mempool/src/transaction_queue.rs#L77)):*
> ```XML
> 
> /// Compare transactions based only on their gas price, a uint, using the Eq trait. It ensures that
> /// two gas price are either exactly equal or not.
> ```

But it's the `PartialEq` trait, I'm confused.
Also, this comment isn't clear to me in general. Did you understand it?



_Code quote:_
```XML
/// Compare transactions based only on their gas price, a uint, using the Eq trait. It ensures that
/// two gas price are either exactly equal or not.
```
___
*[`crates/mempool/src/transaction_queue.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4ZBBeKCHGvgHin8f0n:-O4ZBBeKCHGvgHin8f0o:b5hshjn) ([raw file](https://github.com/starkware-libs/sequencer/blob/55308a23d5adbfcfb7f2c830b138467ccb0f31cd/crates/mempool/src/transaction_queue.rs#L101)):*
> ```XML
>         Some(self.cmp(other))
>     }
> }
> ```

I wouldn't repeat all comments for the two structs. Better to refer the reader to `PendingTransaction`'s documentation.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/439)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4Z9kxB-fwmaawPd5w2:-O4j7bQW1E7Vo7eIlTA9:b2nhky0) ([raw file](https://github.com/starkware-libs/sequencer/blob/55308a23d5adbfcfb7f2c830b138467ccb0f31cd/crates/mempool/src/mempool.rs#L238)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Aren't there these getters in SN API?
</blockquote></details>

No.
___
*[`crates/mempool/src/transaction_queue.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4ZBBeKCHGvgHin8f0n:-O4jWrpF6NtZvgRPjuZt:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/55308a23d5adbfcfb7f2c830b138467ccb0f31cd/crates/mempool/src/transaction_queue.rs#L101)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I wouldn't repeat all comments for the two structs. Better to refer the reader to `PendingTransaction`'s documentation.
</blockquote></details>

Done

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/439)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4Z9kxB-fwmaawPd5w2:-O4jYy9A6KmGOjAKzvHI:bbgf11i) ([raw file](https://github.com/starkware-libs/sequencer/blob/55308a23d5adbfcfb7f2c830b138467ccb0f31cd/crates/mempool/src/mempool.rs#L238)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

No.
</blockquote></details>

Don't think they should be `pub`lic though. Note visibility in general; and specifically when the compiler doesn't complain about unused code - means the code is `pub`lic, we should be convinced it needs to be.
___
*[`crates/mempool/src/mempool.rs` line 235 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4jYw6e7Vu1Ia9iQzY_:-O4jYw6e7Vu1Ia9iQzYa:byquu61) ([raw file](https://github.com/starkware-libs/sequencer/blob/c57d7dd36d9945e73c8265922b5e4738c5495e88/crates/mempool/src/mempool.rs#L235)):*
> ```XML
>     }
> 
>     pub fn get_l2_gas_price(&self) -> Option<u128> {
> ```

Do we need this?



_Code quote:_
```XML
get_l2_gas_price
```
___
*[`crates/mempool/src/transaction_queue.rs` line 102 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4jYjDB3sni5oZAMC77:-O4jYjDB3sni5oZAMC78:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c57d7dd36d9945e73c8265922b5e4738c5495e88/crates/mempool/src/transaction_queue.rs#L102)):*
> ```XML
> }
> 
> /// This struct behaves similarly to [`PendingTransaction`], It encapsulates a transaction reference
> ```





_Suggestion:_
```XML
, encapsulating
```
___
*[`crates/mempool/src/transaction_queue.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4jYlHm5W-RqKWZUfC9:-O4jYlHm5W-RqKWZUfCA:b-3sag6l) ([raw file](https://github.com/starkware-libs/sequencer/blob/c57d7dd36d9945e73c8265922b5e4738c5495e88/crates/mempool/src/transaction_queue.rs#L106)):*
> ```XML
> /// # See Also
> ///
> /// - [`PendingTransaction`]: for details.
> ```

How do I see the resulting doc. file from this?



_Code quote:_
```XML
/// # See Also
///
/// - [`PendingTransaction`]: for details.
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/439)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4ZB5Li8l2r0Q3fkYYk:-O4jZ6-H3EBitB0FvsOG:b-8swg99) ([raw file](https://github.com/starkware-libs/sequencer/blob/55308a23d5adbfcfb7f2c830b138467ccb0f31cd/crates/mempool/src/transaction_queue.rs#L77)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

But it's the `PartialEq` trait, I'm confused.
Also, this comment isn't clear to me in general. Did you understand it?
</blockquote></details>

I think Gilad added this comment.
What's unclear exactly?
`PartialEq` implements `eq` method.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/439)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4Z9kxB-fwmaawPd5w2:-O4j_ujP54pZKhMe3far:b-7e44nc) ([raw file](https://github.com/starkware-libs/sequencer/blob/55308a23d5adbfcfb7f2c830b138467ccb0f31cd/crates/mempool/src/mempool.rs#L238)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Don't think they should be `pub`lic though. Note visibility in general; and specifically when the compiler doesn't complain about unused code - means the code is `pub`lic, we should be convinced it needs to be.
</blockquote></details>

It needs to be public so that it can be used in tx queue file.
___
*[`crates/mempool/src/mempool.rs` line 235 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4jYw6e7Vu1Ia9iQzY_:-O4j_Tyb35zKE7ioA02A:b-931zkx) ([raw file](https://github.com/starkware-libs/sequencer/blob/c57d7dd36d9945e73c8265922b5e4738c5495e88/crates/mempool/src/mempool.rs#L235)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we need this?
</blockquote></details>

I assume you mean l1.
Removed; it will be added once mempool considers the l1 price.
___
*[`crates/mempool/src/transaction_queue.rs` line 102 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4jYjDB3sni5oZAMC77:-O4jZzlxEOL5_ime85zy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c57d7dd36d9945e73c8265922b5e4738c5495e88/crates/mempool/src/transaction_queue.rs#L102)):*
> ```XML
> }
> 
> /// This struct behaves similarly to [`PendingTransaction`], It encapsulates a transaction reference
> ```

Done.
___
*[`crates/mempool/src/transaction_queue.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4jYlHm5W-RqKWZUfC9:-O4j_HTf8SsCzVmm4W70:bl7u7pb) ([raw file](https://github.com/starkware-libs/sequencer/blob/c57d7dd36d9945e73c8265922b5e4738c5495e88/crates/mempool/src/transaction_queue.rs#L106)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How do I see the resulting doc. file from this?
</blockquote></details>

Not sure I get it.
What do you mean?

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/439)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4Z9kxB-fwmaawPd5w2:-O4jaU8S7qaQQeCmnKjt:bzeil9n) ([raw file](https://github.com/starkware-libs/sequencer/blob/55308a23d5adbfcfb7f2c830b138467ccb0f31cd/crates/mempool/src/mempool.rs#L238)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It needs to be public so that it can be used in tx queue file.
</blockquote></details>

Okay, cool. I thought it was the other way around.
___
*[`crates/mempool/src/transaction_queue.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4jYlHm5W-RqKWZUfC9:-O4jaoZV3qnpy-066w2K:b-vbnjz2) ([raw file](https://github.com/starkware-libs/sequencer/blob/c57d7dd36d9945e73c8265922b5e4738c5495e88/crates/mempool/src/transaction_queue.rs#L106)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Not sure I get it.
What do you mean?
</blockquote></details>

The HTML doc. that is created from this doc.; I think you should run `cargo build docs` or something similar. Was wondering about this syntax, since I don't recognize it.
___
*[`crates/mempool/src/transaction_queue.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4jale145I0RcOlDgvl:-O4jale145I0RcOlDgvm:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/158d54c1c5a439f50b8c4aee92a040a380366c26/crates/mempool/src/transaction_queue.rs#L75)):*
> ```XML
> struct PendingTransaction(pub TransactionReference);
> 
> /// Compare transactions based only on their gas price, a uint, using the Eq trait. It ensures that
> ```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/439)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/439)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4jYlHm5W-RqKWZUfC9:-O4jzWUN-F-Q6kdgFI6X:b6hhb8b) ([raw file](https://github.com/starkware-libs/sequencer/blob/c57d7dd36d9945e73c8265922b5e4738c5495e88/crates/mempool/src/transaction_queue.rs#L106)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

The HTML doc. that is created from this doc.; I think you should run `cargo build docs` or something similar. Was wondering about this syntax, since I don't recognize it.
</blockquote></details>

It seems that it only generates public code, and transactino_queue is a private module.
See output:
file:///home/lt-mohammadn/workspace/sequencer1/target/doc/starknet_mempool/mempool/struct.Mempool.html

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/439)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue.rs` line 105 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4k-giaAvKv8sbsEbqp:-O4k-giaAvKv8sbsEbqq:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a9895f31f7b119b49d9be4b6379f10a5c5b92/crates/mempool/src/transaction_queue.rs#L105)):*
> ```XML
> /// to assess its order (i.e., tip).
> ///
> /// # See also `PendingTransaction` docstring for details.
> ```





_Suggestion:_
```XML
/// to assess its order (i.e., tip); see its documentation for more details.
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/439)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 219 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4k5xHO37fmnC_DoGNe:-O4k5xHO37fmnC_DoGNf:b-bhbi2v) ([raw file](https://github.com/starkware-libs/sequencer/blob/591f6f64d2053c026f3c0313f3dcef026e8d680a/crates/mempool/src/mempool.rs#L219)):*
> ```XML
>     pub resource_bounds: ResourceBoundsMapping,
> }
> ```

Keep error messages (tip and L2 gas) in same format. 
Also, is this the earliest point of time this can happen in?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/439)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 219 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4k5xHO37fmnC_DoGNe:-O4kCAEC0kW8nszPnv8Q:bz1skrx) ([raw file](https://github.com/starkware-libs/sequencer/blob/591f6f64d2053c026f3c0313f3dcef026e8d680a/crates/mempool/src/mempool.rs#L219)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
As the current Transaction type may be a deprecated version, this is the earliest point.
</blockquote></details>

@ArniStarkware, should be changed.
___
*[`crates/mempool/src/mempool.rs` line 239 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4kBybG5cmtdTaA5HLW:-O4kBybG5cmtdTaA5HLX:baz3zfi) ([raw file](https://github.com/starkware-libs/sequencer/blob/9e88b7d4e22c2236117f3c595725db84a8464ec4/crates/mempool/src/mempool.rs#L239)):*
> ```XML
>             .get(&Resource::L2Gas)
>             .map(|bounds| bounds.max_price_per_unit)
>             .expect("Expected L2Gas resource found")
> ```

Why is it still optional here? This should change in `0.13.3`, right?
Please align the error message here too.



_Code quote:_
```XML
            .map(|bounds| bounds.max_price_per_unit)
            .expect("Expected L2Gas resource found")
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/439)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 239 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4kBybG5cmtdTaA5HLW:-O4kKIte75LEogMW4BCE:b-s6d9wb) ([raw file](https://github.com/starkware-libs/sequencer/blob/9e88b7d4e22c2236117f3c595725db84a8464ec4/crates/mempool/src/mempool.rs#L239)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is it still optional here? This should change in `0.13.3`, right?
Please align the error message here too.
</blockquote></details>

because [resource bounds](https://github.com/starkware-libs/sequencer/blob/6af5e477195984520106ae706e10ed7521d746f6/crates/starknet_api/src/transaction.rs#L919) is a map of resource to resource bound.
So here it is optional since the map keys "may" not include L2Resource.

What do you mean by "align the error message"? Here, I cannot say "expected a valid resource but received none." The resource is not none, the resource is not existed, so I wrote "L2Gas should be found". wdyt?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/439)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 239 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4kBybG5cmtdTaA5HLW:-O4kNR9M2Y1g8KWuOHjg:b3j69k6) ([raw file](https://github.com/starkware-libs/sequencer/blob/9e88b7d4e22c2236117f3c595725db84a8464ec4/crates/mempool/src/mempool.rs#L239)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

because [resource bounds](https://github.com/starkware-libs/sequencer/blob/6af5e477195984520106ae706e10ed7521d746f6/crates/starknet_api/src/transaction.rs#L919) is a map of resource to resource bound.
So here it is optional since the map keys "may" not include L2Resource.

What do you mean by "align the error message"? Here, I cannot say "expected a valid resource but received none." The resource is not none, the resource is not existed, so I wrote "L2Gas should be found". wdyt?
</blockquote></details>

You can say expected a valid X value, without say what you received.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/439)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 239 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4kBybG5cmtdTaA5HLW:-O4l7q876XeZ-akRSm2O:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9e88b7d4e22c2236117f3c595725db84a8464ec4/crates/mempool/src/mempool.rs#L239)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

You can say expected a valid X value, without say what you received.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/439)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 212 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4mzc0q3ALXc71LSb3H:-O4mzc0r4udVAg9bm6bE:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/053ae9abadb782f5f23cfa22f0f4f2cc658d1e90/crates/mempool/src/mempool.rs#L212)):*
> ```XML
>             nonce: tx.nonce(),
>             tx_hash: tx.tx_hash(),
>             tip: tx.tip().expect("Expected a valid tip value, but received None."),
> ```





_Suggestion:_
```XML
"Expected a valid tip value."
```
___
*[`crates/mempool/src/mempool.rs` line 215 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4mynVrEmir19C1lWw7:-O4mynVrEmir19C1lWw8:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/053ae9abadb782f5f23cfa22f0f4f2cc658d1e90/crates/mempool/src/mempool.rs#L215)):*
> ```XML
>             resource_bounds: tx
>                 .resource_bounds()
>                 .expect("Expected a valid resource bounds value, but received None.")
> ```





_Suggestion:_
```XML
"Expected a valid resource bounds value."
```
___
*[`crates/mempool/src/mempool.rs` line 225 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4myqnp7h02pe3_gq5k:-O4myqnp7h02pe3_gq5l:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/053ae9abadb782f5f23cfa22f0f4f2cc658d1e90/crates/mempool/src/mempool.rs#L225)):*
> ```XML
>             .get(&Resource::L2Gas)
>             .map(|bounds| bounds.max_price_per_unit)
>             .expect("Expected a valid L2Gas resource.")
> ```





_Suggestion:_
```XML
"Expected a valid L2 gas resource bounds."
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/439#-:-O4ndrxH-4RxUCjyWDpD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @giladchase)

**Comment by ArniStarkware** [comment]
*[`crates/mempool/src/mempool.rs` line 219 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4k5xHO37fmnC_DoGNe:-O4npg6eARul_BCYBFHI:b-4lascv) ([raw file](https://github.com/starkware-libs/sequencer/blob/591f6f64d2053c026f3c0313f3dcef026e8d680a/crates/mempool/src/mempool.rs#L219)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

@ArniStarkware, should be changed.
</blockquote></details>

I don't follow.

**Comment by ArniStarkware** [comment]
*[`crates/mempool/src/mempool.rs` line 219 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/439#-O4k5xHO37fmnC_DoGNe:-O4nxcQC8_jJw6glkEsI:bi1c5et) ([raw file](https://github.com/starkware-libs/sequencer/blob/591f6f64d2053c026f3c0313f3dcef026e8d680a/crates/mempool/src/mempool.rs#L219)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I don't follow.
</blockquote></details>

I do follow :)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/439)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @giladchase)

**Pull request merged**
