### PR TITLE
feat(tests_integration): one to many network config

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Comment by yair-starkware** [comment]
* **#2253** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2253?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2253?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2253)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5, @eitanm-starkware, and @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2253#-OCX3hGQ-T34Dh6-KSh5:-OCbZKEpC30vOjKa6u6Z:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/14e61a18111378e2d3bef9a1c8116c782411a230/crates/papyrus_network/src/network_manager/test_utils.rs#L151)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to create_connected_network_configs
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2253#-OCX3lyq3CI5yBsM8ZI1:-OCbarz3C9ddunU6-MeN:bfhcvqb) ([raw file](https://github.com/starkware-libs/sequencer/blob/14e61a18111378e2d3bef9a1c8116c782411a230/crates/papyrus_network/src/network_manager/test_utils.rs#L151)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider returning [NetworkConfig; N] instead of vec
</blockquote></details>

It's hard because `NetworkConfig` doesn't implement Copy so you can't initialize an array
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2253#-OCX4REA5ywxsCLvDAzL:-OCbb1-Z-L9qSYcz3wn6:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/14e61a18111378e2d3bef9a1c8116c782411a230/crates/papyrus_network/src/network_manager/test_utils.rs#L151)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Return just a container of network configs instead (decrease N by 1). There's no need to split between the first one and the rest
</blockquote></details>

done
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2253#-OCX44mw2GnARVRnIRmu:-OCbYwix9WbeF3E3Yj73:bjalbkn) ([raw file](https://github.com/starkware-libs/sequencer/blob/14e61a18111378e2d3bef9a1c8116c782411a230/crates/papyrus_network/src/network_manager/test_utils.rs#L180)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Revert the changes to this function. This function is used to check that messages were sent or to send messages, and for that we only need 2 peers
</blockquote></details>

I need to keep this check and also create another sequencer, so I need 3 peers

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2253)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5, @eitanm-starkware, and @yair-starkware)

___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2253#-OCX3lyq3CI5yBsM8ZI1:-OCcchlb9a680obf__O5:b-6w7icf) ([raw file](https://github.com/starkware-libs/sequencer/blob/14e61a18111378e2d3bef9a1c8116c782411a230/crates/papyrus_network/src/network_manager/test_utils.rs#L151)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

It's hard because `NetworkConfig` doesn't implement Copy so you can't initialize an array
</blockquote></details>

You can. With https://doc.rust-lang.org/core/array/fn.from_fn.html
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2253#-OCX44mw2GnARVRnIRmu:-OCcdKRX5isfKhN0f3s8:b-r6cvb9) ([raw file](https://github.com/starkware-libs/sequencer/blob/14e61a18111378e2d3bef9a1c8116c782411a230/crates/papyrus_network/src/network_manager/test_utils.rs#L180)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I need to keep this check and also create another sequencer, so I need 3 peers
</blockquote></details>

I didn't understand. Huddle/zoom?
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2253#-OCcd67YEhHg4LLwoPkk:-OCcd67YEhHg4LLwoPkl:b2nhjd9) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e53a632a4e2ff75c8743a2529d50e4f6803afcd/crates/papyrus_network/src/network_manager/test_utils.rs#L154)):*
> ```XML
>     assert!(N > 0);
>     let port0 = find_n_free_ports::<1>()[0];
>     let ports = find_n_free_ports::<N>();
> ```

N-1
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2253#-OCcd7z3-zqM6XyzAZWY:-OCcd7z3-zqM6XyzAZWZ:b-5qlb2j) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e53a632a4e2ff75c8743a2529d50e4f6803afcd/crates/papyrus_network/src/network_manager/test_utils.rs#L154)):*
> ```XML
>     assert!(N > 0);
>     let port0 = find_n_free_ports::<1>()[0];
>     let ports = find_n_free_ports::<N>();
> ```

calling find_n_free_ports twice doesn't guarantee that the first call and the second call won't give the same port. Unite the calls and then split them off

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2253)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @alonh5, @eitanm-starkware, and @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2253#-OCX3lyq3CI5yBsM8ZI1:-OCcvdMc3yjXPp3cXhLU:b-3p1595) ([raw file](https://github.com/starkware-libs/sequencer/blob/14e61a18111378e2d3bef9a1c8116c782411a230/crates/papyrus_network/src/network_manager/test_utils.rs#L151)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You can. With https://doc.rust-lang.org/core/array/fn.from_fn.html
</blockquote></details>

Changed to vec (talked in slack)
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2253#-OCX44mw2GnARVRnIRmu:-OCcvqan3XlSsigyS4PQ:b-epw0lj) ([raw file](https://github.com/starkware-libs/sequencer/blob/14e61a18111378e2d3bef9a1c8116c782411a230/crates/papyrus_network/src/network_manager/test_utils.rs#L180)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I didn't understand. Huddle/zoom?
</blockquote></details>

huddled
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2253#-OCcd67YEhHg4LLwoPkk:-OCcvkFp0YXdiFYrl0dB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e53a632a4e2ff75c8743a2529d50e4f6803afcd/crates/papyrus_network/src/network_manager/test_utils.rs#L154)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

N-1
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2253#-OCcd7z3-zqM6XyzAZWY:-OCcvlNH-cIkhc3OTyVX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e53a632a4e2ff75c8743a2529d50e4f6803afcd/crates/papyrus_network/src/network_manager/test_utils.rs#L154)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

calling find_n_free_ports twice doesn't guarantee that the first call and the second call won't give the same port. Unite the calls and then split them off
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2253)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @eitanm-starkware, and @yair-starkware)

___
*[`crates/papyrus_common/src/tcp.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2253#-OCgfT3RBNYrZJPk5x2X:-OCgfT3RBNYrZJPk5x2Y:b-uds4px) ([raw file](https://github.com/starkware-libs/sequencer/blob/d273db9e2594f2a5639024accbb0933865817431/crates/papyrus_common/src/tcp.rs#L17)):*
> ```XML
>     let mut ports = Vec::with_capacity(n);
>     for _ in 0..n {
>         let listener = TcpListener::bind("0.0.0.0:0").expect("Failed to bind");
> ```

You should keep all listeners alive until the end of the function. Notice the previous implementation. It defines an array of listeners and then converts it to an array of ports

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2253)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5, @eitanm-starkware, and @ShahakShama)

___
*[`crates/papyrus_common/src/tcp.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2253#-OCgfT3RBNYrZJPk5x2X:-OCgszMU7GFSw2GVC-SZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d273db9e2594f2a5639024accbb0933865817431/crates/papyrus_common/src/tcp.rs#L17)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You should keep all listeners alive until the end of the function. Notice the previous implementation. It defines an array of listeners and then converts it to an array of ports
</blockquote></details>

Done.

**Review by eitanm-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2253)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5, @ShahakShama, and @yair-starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 80 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2253#-OCgwmJV7RYd3z1un23S:-OCgwmJV7RYd3z1un23T:b-v434hd) ([raw file](https://github.com/starkware-libs/sequencer/blob/8fb2748c64293b0202cbbaddfab6c59923066ac0/crates/starknet_integration_tests/src/utils.rs#L80)):*
> ```XML
> }
> 
> fn create_consensus_manager_configs_and_channels(
> ```

create_n_consensus_manager_configs_and_channels



_Code quote:_
```XML
create_consensus_manager_configs_and_channels
```
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 152 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2253#-OCgwYtU6hA2PkEFCPmh:-OCgwYtU6hA2PkEFCPmi:bvdyuu3) ([raw file](https://github.com/starkware-libs/sequencer/blob/8fb2748c64293b0202cbbaddfab6c59923066ac0/crates/papyrus_network/src/network_manager/test_utils.rs#L152)):*
> ```XML
> 
> pub fn create_connected_network_configs(n: usize) -> Vec<NetworkConfig> {
>     let mut ports = find_n_free_ports(n);
> ```

create_n_connected_network_configs
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 180 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2253#-OCgwdKw53nWoBgcgD0B:-OCgwdKw53nWoBgcgD0C:b-wqak9e) ([raw file](https://github.com/starkware-libs/sequencer/blob/8fb2748c64293b0202cbbaddfab6c59923066ac0/crates/papyrus_network/src/network_manager/test_utils.rs#L180)):*
> ```XML
> }
> 
> pub fn create_network_configs_connected_to_broadcast_channels<T>(
> ```

create_n_network_configs_connected_to_broadcast_channels



_Code quote:_
```XML
create_network_configs_connected_to_broadcast_channels
```

**Review by ShahakShama — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2253)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @yair-starkware)

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2253)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by yair-starkware** [comment]
### Merge activity

* **Dec 1, 4:27 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2253).

**Pull request merged**
