### PR TITLE
refactor: drop impl from component names

### PR DESCRIPTION
**Pull request by nadin-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1286)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1286)* status: all files reviewed, 3 unresolved discussions (waiting on @nadin-Starkware)

___
*[`config/mempool/default_config.json` line 173 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1286#-O8pso5661Y8jVQuCr3N:-O8pso5661Y8jVQuCr3O:b-ybshqr) ([raw file](https://github.com/starkware-libs/sequencer/blob/3a787f31a9ae53ff04ea153c8d51cabf56832b1d/config/mempool/default_config.json#L173)):*
> ```JSON
>   },
>   "components.consensus_manager.remote_client_config.socket": {
>     "description": "The remote component socket.",
> ```

Please revert, the component does not have a socket, the server does :pray: (throughout the pr)



_Code quote:_
```JSON
 "The remote component socket.",
```
___
*[`crates/mempool_infra/src/component_definitions.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1286#-O8ptDPg2-sfbG-qeh_C:-O8ptDPhDXNvVisPuvgo:b-8ng0gk) ([raw file](https://github.com/starkware-libs/sequencer/blob/3a787f31a9ae53ff04ea153c8d51cabf56832b1d/crates/mempool_infra/src/component_definitions.rs#L103)):*
> ```XML
>     pub idle_timeout: u64,
> }
> ```

Please add a TODO here to move config definitions to relevant files/modules.
___
*[`crates/mempool_infra/src/component_definitions.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1286#-O8ptQFF-LUqqFCM7CYf:-O8ptQFF-LUqqFCM7CYg:bksp82r) ([raw file](https://github.com/starkware-libs/sequencer/blob/3a787f31a9ae53ff04ea153c8d51cabf56832b1d/crates/mempool_infra/src/component_definitions.rs#L175)):*
> ```XML
>     pub client_config: RemoteClientConfig,
>     pub server_config: RemoteServerConfig,
> }
> ```

Please remove this (I suspect this is a rebasing issue).



_Code quote:_
```XML
// The communication configuration of the remote component.
#[derive(Clone, Default, Debug, Serialize, Deserialize, Validate, PartialEq)]
pub struct RemoteComponentCommunicationConfig {
    pub client_config: RemoteClientConfig,
    pub server_config: RemoteServerConfig,
}
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1286)* status: 6 of 13 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_definitions.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1286#-O8ptDPg2-sfbG-qeh_C:-O8q1lAD3zL2W4Qd1h6I:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3a787f31a9ae53ff04ea153c8d51cabf56832b1d/crates/mempool_infra/src/component_definitions.rs#L103)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add a TODO here to move config definitions to relevant files/modules.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_definitions.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1286#-O8ptQFF-LUqqFCM7CYf:-O8q1nVy5gxsd9I11Ypv:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3a787f31a9ae53ff04ea153c8d51cabf56832b1d/crates/mempool_infra/src/component_definitions.rs#L175)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please remove this (I suspect this is a rebasing issue).
</blockquote></details>

Done.
___
*[`config/mempool/default_config.json` line 173 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1286#-O8pso5661Y8jVQuCr3N:-O8q4MvJ61scGbFW6WR1:bksdvwl) ([raw file](https://github.com/starkware-libs/sequencer/blob/3a787f31a9ae53ff04ea153c8d51cabf56832b1d/config/mempool/default_config.json#L173)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please revert, the component does not have a socket, the server does :pray: (throughout the pr)
</blockquote></details>

To revert the description to "The remote component client socket."?

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1286)* status: 6 of 13 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`config/mempool/default_config.json` line 173 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1286#-O8pso5661Y8jVQuCr3N:-O92oqaZ9-I4QNEDnPiB:bx5385j) ([raw file](https://github.com/starkware-libs/sequencer/blob/3a787f31a9ae53ff04ea153c8d51cabf56832b1d/config/mempool/default_config.json#L173)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

To revert the description to "The remote component client socket."?
</blockquote></details>

I meant server socket. Anyway, I don't think it aligns with this PR commit message, so I fixed it in another PR:
https://reviewable.io/reviews/starkware-libs/sequencer/1343

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1286#-:-O99ZhvD1Ph2Tfdz8BqF:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1286)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Pull request merged**
