### PR TITLE
feat(common): move find_free_port to papyrus_common and add find_n_free_ports

### PR DESCRIPTION
**Pull request by ShahakShama**

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1749)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_common/src/lib.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1749#-OAlUFG7DlqtBeSUqvh_:-OAlUFG85_TQ0neGldOn:b-zigvpe) ([raw file](https://github.com/starkware-libs/sequencer/blob/e8224035d64a35644331fc6f8dcfbbf7c1ac196f/crates/papyrus_common/src/lib.rs#L11)):*
> ```XML
> pub mod state;
> pub mod storage_query;
> pub mod tcp;
> ```

Why create a new module for this? Even if so, maybe don't make it tcp specific? That feels overspecified



_Code quote:_
```XML
pub mod tcp;
```
___
*[`crates/papyrus_common/src/tcp.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1749#-OAlU18TEA697yfG7MfA:-OAlU18TEA697yfG7MfB:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e8224035d64a35644331fc6f8dcfbbf7c1ac196f/crates/papyrus_common/src/tcp.rs#L14)):*
> ```XML
>     // The socket is automatically closed when the function exits.
>     // The port may still be available when accessed, but this is not guaranteed.
>     // TODO(Asmaa): find a reliable way to ensure the port stays free.
> ```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1749)* status: all files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/papyrus_common/src/lib.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1749#-OAlUFG7DlqtBeSUqvh_:-OAlWUGP8K3DdLHepgQh:b-brtw6a) ([raw file](https://github.com/starkware-libs/sequencer/blob/e8224035d64a35644331fc6f8dcfbbf7c1ac196f/crates/papyrus_common/src/lib.rs#L11)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why create a new module for this? Even if so, maybe don't make it tcp specific? That feels overspecified
</blockquote></details>

the common crate contains all kinds of things, so I don't want to put this inside the main module of common
the main module of a crate should be used for things that are the essence of the crate

Regarding naming, we're looking for tcp ports so I think it makes sense
___
*[`crates/papyrus_common/src/tcp.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1749#-OAlU18TEA697yfG7MfA:-OAlWkM-E4ibpSfUspW5:b1u8suh) ([raw file](https://github.com/starkware-libs/sequencer/blob/e8224035d64a35644331fc6f8dcfbbf7c1ac196f/crates/papyrus_common/src/tcp.rs#L14)):*
> ```XML
>     // The socket is automatically closed when the function exits.
>     // The port may still be available when accessed, but this is not guaranteed.
>     // TODO(Asmaa): find a reliable way to ensure the port stays free.
> ```

Why? The comment is still true to this function as well

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1749)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_common/src/lib.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1749#-OAlUFG7DlqtBeSUqvh_:-OAliyP_0LIhpee80Edu:b-okvxjy) ([raw file](https://github.com/starkware-libs/sequencer/blob/e8224035d64a35644331fc6f8dcfbbf7c1ac196f/crates/papyrus_common/src/lib.rs#L11)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

the common crate contains all kinds of things, so I don't want to put this inside the main module of common
the main module of a crate should be used for things that are the essence of the crate

Regarding naming, we're looking for tcp ports so I think it makes sense
</blockquote></details>

WDYT of something like network or net_utils? tcp feels too specific

**Review by matan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1749)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

**Pull request merged**
