### PR TITLE
refactor(blockifier): impl .into() from api executable tx to blockifier AccountTransaction

### PR DESCRIPTION
**Pull request by avivg-starkware**
…tx to account_transaction

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1868)* status: all files reviewed, 2 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1868#-OBKCgHFBDUJeM65XBKd:-OBKCgHFBDUJeM65XBKe:b-1dc4fw) ([raw file](https://github.com/starkware-libs/sequencer/blob/309672f938f5529419c8674ef1bcc44295dccd2f/crates/blockifier/src/test_utils/deploy_account.rs#L28)):*
> ```XML
>         DeployAccountTransaction::new(deploy_account_tx, tx_hash, contract_address);
> 
>     executable_deploy_account_tx.into()
> ```

`use starknet_api::test_utils::deploy_account::executable_deploy_account_tx`

Same for the declare (wow!).
It's not the same for the invoke - add a todo over there...



_Suggestion:_
```XML

    let executable_deploy_account_tx =
        executable_deploy_account_tx(..);

    executable_deploy_account_tx.into()
```
___
*[`crates/blockifier/src/test_utils/declare.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1868#-OBKC2M7CNeGezobnzY1:-OBKC2M7CNeGezobnzY2:b-ul7oqm) ([raw file](https://github.com/starkware-libs/sequencer/blob/309672f938f5529419c8674ef1bcc44295dccd2f/crates/blockifier/src/test_utils/declare.rs#L10)):*
> ```XML
>     let tx_hash = declare_tx_args.tx_hash;
>     let declare_tx = starknet_api::test_utils::declare::declare_tx(declare_tx_args);
>     let executable_declare = DeclareTransaction::new(declare_tx, tx_hash, class_info).unwrap();
> ```

Good job!



_Code quote:_
```XML
let executable_declare = DeclareTransaction::new(declare_tx, tx_hash, class_info).unwrap();
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1868#-OBKAyph8-jZWscjPwyN:-OBKAyph8-jZWscjPwyO:b-sh1f96) ([raw file](https://github.com/starkware-libs/sequencer/blob/35360cd10ebf1e68a87cfe518bcc6ec56280c5f3/crates/blockifier/src/transaction/account_transaction.rs#L80)):*
> ```XML
> 
> /// Represents a paid Starknet transaction.
> #[derive(Clone, Debug, derive_more::From)]
> ```

This did not work? Didn't it do what these `from` methods did?



_Code quote:_
```XML
, derive_more::From
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1868)* status: all files reviewed, 2 unresolved discussions (waiting on @avivg-starkware and @noaov1)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1868)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/declare.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1868#-OBKC2M7CNeGezobnzY1:-OBKc42f5H4cf3yasO5H:b32vhw) ([raw file](https://github.com/starkware-libs/sequencer/blob/309672f938f5529419c8674ef1bcc44295dccd2f/crates/blockifier/src/test_utils/declare.rs#L10)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Good job!
</blockquote></details>

:)
___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1868#-OBKCgHFBDUJeM65XBKd:-OBKfR4862Paqt9fgtVT:b-azxbhx) ([raw file](https://github.com/starkware-libs/sequencer/blob/309672f938f5529419c8674ef1bcc44295dccd2f/crates/blockifier/src/test_utils/deploy_account.rs#L28)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

`use starknet_api::test_utils::deploy_account::executable_deploy_account_tx`

Same for the declare (wow!).
It's not the same for the invoke - add a todo over there...
</blockquote></details>

Will use the code SUGGESTION in #1688. 

What is the change you mean for the invoke? 
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1868#-OBKAyph8-jZWscjPwyN:-OBKhG7h4utj9qYTDzWu:b-u1vfy7) ([raw file](https://github.com/starkware-libs/sequencer/blob/35360cd10ebf1e68a87cfe518bcc6ec56280c5f3/crates/blockifier/src/transaction/account_transaction.rs#L80)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This did not work? Didn't it do what these `from` methods did?
</blockquote></details>

Sorry, works! there is a test that sometimes fails for me after making a change and running for the 1st time- sync_happy_flow(). are you familiar with this perhaps?

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/account_transaction.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1868#-OBKAyph8-jZWscjPwyN:-OBKyrLP640gMq-303S4:bfu2jf) ([raw file](https://github.com/starkware-libs/sequencer/blob/35360cd10ebf1e68a87cfe518bcc6ec56280c5f3/crates/blockifier/src/transaction/account_transaction.rs#L80)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

Sorry, works! there is a test that sometimes fails for me after making a change and running for the 1st time- sync_happy_flow(). are you familiar with this perhaps?
</blockquote></details>

Don't know what you are talking about :o

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1868)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1868#-OBKCgHFBDUJeM65XBKd:-OBL-Xzj2eP2difI3e0Y:b-wpct4w) ([raw file](https://github.com/starkware-libs/sequencer/blob/309672f938f5529419c8674ef1bcc44295dccd2f/crates/blockifier/src/test_utils/deploy_account.rs#L28)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

Will use the code SUGGESTION in #1688. 

What is the change you mean for the invoke?
</blockquote></details>

I don't understand.  

1. Which PR came before which PR?
2. I don't see my suggestion implemented here or there.
3. This PR is small as it is, and this suggestion is small - you can follow through with my suggestion here and close this subject.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1868)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/test_utils/invoke.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1868#-OBL0W3Y5N8W0ToSIFA3:-OBL0W3Y5N8W0ToSIFA4:buogljb) ([raw file](https://github.com/starkware-libs/sequencer/blob/28fcaecef8f4786312cd346b5d4077c956a6b48c/crates/blockifier/src/test_utils/invoke.rs#L22)):*
> ```XML
>             entry_point_selector: selector_from_name(EXECUTE_ENTRY_POINT_NAME),
>         })
>     } else {
> ```

The test util for executable transactions does not support the creation of `TransactionVersion::ZERO` invoke transactions.



_Code quote:_
```XML
    let invoke_tx = if invoke_args.version == TransactionVersion::ZERO {
        starknet_api::transaction::InvokeTransaction::V0(InvokeTransactionV0 {
            max_fee: invoke_args.max_fee,
            calldata: invoke_args.calldata,
            contract_address: invoke_args.sender_address,
            signature: invoke_args.signature,
            // V0 transactions should always select the `__execute__` entry point.
            entry_point_selector: selector_from_name(EXECUTE_ENTRY_POINT_NAME),
        })
    } else {
```

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1868)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware and @noaov1)

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1868)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1868#-OBKCgHFBDUJeM65XBKd:-OBLg9ss0wNm4FQ6J6g8:brnldsl) ([raw file](https://github.com/starkware-libs/sequencer/blob/309672f938f5529419c8674ef1bcc44295dccd2f/crates/blockifier/src/test_utils/deploy_account.rs#L28)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I don't understand.  

1. Which PR came before which PR?
2. I don't see my suggestion implemented here or there.
3. This PR is small as it is, and this suggestion is small - you can follow through with my suggestion here and close this subject.
</blockquote></details>

Ok - I see now fixing this will be much simpler once #1919 (just created) is implemented. 

Please add a todo to use the appropriated executable-transaction-creator-test-util for each of these functions. (For example - for this function - add a todo to use: `starknet_api::test_utils::deploy_account::executable_deploy_account_tx` for it's implementation).

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1868)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1868#-OBKCgHFBDUJeM65XBKd:-OBLeVjy8PplMV4JUlLX:b-ijo4vj) ([raw file](https://github.com/starkware-libs/sequencer/blob/309672f938f5529419c8674ef1bcc44295dccd2f/crates/blockifier/src/test_utils/deploy_account.rs#L28)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I don't understand.  

1. Which PR came before which PR?
2. I don't see my suggestion implemented here or there.
3. This PR is small as it is, and this suggestion is small - you can follow through with my suggestion here and close this subject.
</blockquote></details>

`executable_deploy_account_tx`, returns a DeployAccountTransaction that is api executable,
currently here,  DeployAccountTransaction is a blockifier struct.
 After the PR i mentioned, the DeployAccountTransaction used here, will be the api executable. 
Does it answer? am I missing something? 
___
*[`crates/blockifier/src/test_utils/invoke.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1868#-OBL0W3Y5N8W0ToSIFA3:-OBLi1UO7h9gC8uNsQP2:bmm3lwn) ([raw file](https://github.com/starkware-libs/sequencer/blob/28fcaecef8f4786312cd346b5d4077c956a6b48c/crates/blockifier/src/test_utils/invoke.rs#L22)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The test util for executable transactions does not support the creation of `TransactionVersion::ZERO` invoke transactions.
</blockquote></details>

thanks I see now. Added a TODO. looks clear?

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1868)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1868#-OBKCgHFBDUJeM65XBKd:-OBLl7Bb1XPixultiU1n:b-l4396t) ([raw file](https://github.com/starkware-libs/sequencer/blob/309672f938f5529419c8674ef1bcc44295dccd2f/crates/blockifier/src/test_utils/deploy_account.rs#L28)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

`executable_deploy_account_tx`, returns a DeployAccountTransaction that is api executable,
currently here,  DeployAccountTransaction is a blockifier struct.
 After the PR i mentioned, the DeployAccountTransaction used here, will be the api executable. 
Does it answer? am I missing something?
</blockquote></details>

Added a comment

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1868#-OBM8cdE8gX72T42Pp6i:-OBM8cdE8gX72T42Pp6j:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e700bb8e18156e1fa24939f3b8ee44344d97f90/crates/blockifier/src/test_utils/deploy_account.rs#L28)):*
> ```XML
>     // create executable_deploy_account_tx instead of code above.
>     let executable_deploy_account_tx =
>         DeployAccountTransaction::new(deploy_account_tx, tx_hash, contract_address);
> ```





_Suggestion:_
```XML
    // TODO(AvivG): use starknet_api::test_utils::deploy_account::executable_deploy_account_tx to
    // create executable_deploy_account_tx.
    let executable_deploy_account_tx =
        DeployAccountTransaction::new(deploy_account_tx, tx_hash, contract_address);
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/test_utils/invoke.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1868#-OBL0W3Y5N8W0ToSIFA3:-OBM8y-_7Xn6shGlDNjX:bb77ufg) ([raw file](https://github.com/starkware-libs/sequencer/blob/28fcaecef8f4786312cd346b5d4077c956a6b48c/crates/blockifier/src/test_utils/invoke.rs#L22)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

thanks I see now. Added a TODO. looks clear?
</blockquote></details>

Yes.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1868)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1868#-OBKCgHFBDUJeM65XBKd:-OBM8hVG2SQhRxp2awn-:b-anrldz) ([raw file](https://github.com/starkware-libs/sequencer/blob/309672f938f5529419c8674ef1bcc44295dccd2f/crates/blockifier/src/test_utils/deploy_account.rs#L28)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

Added a comment
</blockquote></details>

I still do not understand what you mean, but following through on the to-do list will solve the issue I mentioned. 
___
*[`crates/blockifier/src/test_utils/declare.rs` line 10 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1868#-OBM9_a5CLySisbcV9m4:-OBM9_a5CLySisbcV9m5:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e700bb8e18156e1fa24939f3b8ee44344d97f90/crates/blockifier/src/test_utils/declare.rs#L10)):*
> ```XML
>     let tx_hash = declare_tx_args.tx_hash;
>     let declare_tx = starknet_api::test_utils::declare::declare_tx(declare_tx_args);
>     let executable_declare = DeclareTransaction::new(declare_tx, tx_hash, class_info).unwrap();
> ```





_Suggestion:_
```XML
// TODO(AvivG): use starknet_api::test_utils::declare::executable_declare_tx to
// create executable_declare.
let executable_declare = DeclareTransaction::new(declare_tx, tx_hash, class_info).unwrap();
```

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1868)* status: all files reviewed, 2 unresolved discussions (waiting on @avivg-starkware and @noaov1)

**Comment by avivg-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1868?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1868** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1868?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1643** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1643?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @avivg-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by meship-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1868)* status: all files reviewed, 2 unresolved discussions (waiting on @avivg-starkware and @noaov1)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1868)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1868#-OBM8cdE8gX72T42Pp6i:-OBPJ2qh1jkIyqo20G6x:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e700bb8e18156e1fa24939f3b8ee44344d97f90/crates/blockifier/src/test_utils/deploy_account.rs#L28)):*
> ```XML
>     // create executable_deploy_account_tx instead of code above.
>     let executable_deploy_account_tx =
>         DeployAccountTransaction::new(deploy_account_tx, tx_hash, contract_address);
> ```

Done.
___
*[`crates/blockifier/src/test_utils/declare.rs` line 10 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1868#-OBM9_a5CLySisbcV9m4:-OBPIsxx1In2LF4L64Cn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e700bb8e18156e1fa24939f3b8ee44344d97f90/crates/blockifier/src/test_utils/declare.rs#L10)):*
> ```XML
>     let tx_hash = declare_tx_args.tx_hash;
>     let declare_tx = starknet_api::test_utils::declare::declare_tx(declare_tx_args);
>     let executable_declare = DeclareTransaction::new(declare_tx, tx_hash, class_info).unwrap();
> ```

Done.

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1868)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
