### PR TITLE
refactor(mempool): call invoke_tx_args macro from StarknetAPI

### PR DESCRIPTION
**Pull request by noam-starkware**
Remove duplicated invoke_tx_args macro from mepool.

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1371)

### CODE REVIEW

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1371)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1 and @noam-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1371#-O9cnCn34unIyfFgYjpP:-O9cnCn34unIyfFgYjpQ:b6gdu3v) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a00d5150a629dd5d2287c8d93361de8975cea3d/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L94)):*
> ```XML
>             signature
>         )),
>         TransactionType::Invoke => rpc_invoke_tx(starknet_api::invoke_tx_args!(
> ```

We can remove it (in all places) since the macro is already deleted in this PR, so there will be no duplication with `starknet_api`'s macro.



_Code quote:_
```XML
starknet_api
```
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 576 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1371#-O9cocrFCE03PCcIq-GJ:-O9cocrFCE03PCcIq-GK:bvdyi2) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e06fe577a7eb29ebcd1146e7eade3854197eecc/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L576)):*
> ```XML
> }
> 
> pub fn rpc_invoke_tx(invoke_args: InvokeTxArgs) -> RpcTransaction {
> ```

can `starknet_api_test_utils`' `InvokeTxArgs` be deleted?



_Code quote:_
```XML
InvokeTxArgs
```

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1371)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @noam-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1371#-O9d6HMXDDTstZmPtrEz:-O9d6HMY5MN-I1qbXaop:b504964) (no related file):*
Congrats on your first PR. Nice!

___
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1371#-O9cnCn34unIyfFgYjpP:-O9d5ZqV5mpp5L9Qn249:b-948m65) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a00d5150a629dd5d2287c8d93361de8975cea3d/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L94)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

We can remove it (in all places) since the macro is already deleted in this PR, so there will be no duplication with `starknet_api`'s macro.
</blockquote></details>

Please remove the struct as well.
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 571 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1371#-O9d5mL-9t7XSoPLvALN:-O9d5mL-9t7XSoPLvALO:b-ppy6g9) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a00d5150a629dd5d2287c8d93361de8975cea3d/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L571)):*
> ```XML
>     let ValidResourceBounds::AllResources(resource_bounds) = invoke_args.resource_bounds else {
>         panic!("Unspported resource bounds type: {:?}.", invoke_args.resource_bounds)
>     };
> ```

Can you use `unwrap` instead? It's a test util, so the error message isn't necessary.
Also the error msg is clear from the context.



_Code quote:_
```XML
    let ValidResourceBounds::AllResources(resource_bounds) = invoke_args.resource_bounds else {
        panic!("Unspported resource bounds type: {:?}.", invoke_args.resource_bounds)
    };
```

**Review by noam-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1371)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1371#-O9cnCn34unIyfFgYjpP:-O9dh1_A8zS7ADOeCpHv:b9bma8o) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a00d5150a629dd5d2287c8d93361de8975cea3d/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L94)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please remove the struct as well.
</blockquote></details>

Locally bound `InvokeTxArgs` and `invoke_tx_args` from Starknet API.
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 571 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1371#-O9d5mL-9t7XSoPLvALN:-O9dhzGV2EXPIqIh9sYw:bok106i) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a00d5150a629dd5d2287c8d93361de8975cea3d/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L571)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can you use `unwrap` instead? It's a test util, so the error message isn't necessary.
Also the error msg is clear from the context.
</blockquote></details>

After discussion with Mohammad and Ayelet: since `invoke_tx_args` uses  the `ValidResourceBounds` enum for the resource bounds but the RPC uses `AllResources` we need to handle the case when the resource bound has type `L1Gas`. This could either be done using an `unreachable` or `panic` macro. 

The use of unreachable makes sense when there is a guarantee that `invoke_args.resource_bounds` will always be of type `AllResources` but when the compiler does not detect it. Since this is not the case we opted to keep this as a `panic` (and adhere to the format of the previous check as well).

Finally, although the error is self-explanatory the use of empty panics in the repo is very rare and we decided to keep the original error message. 
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 576 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1371#-O9cocrFCE03PCcIq-GJ:-O9dhtOdCY4bzTIPpUMG:b9c55xv) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e06fe577a7eb29ebcd1146e7eade3854197eecc/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L576)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

can `starknet_api_test_utils`' `InvokeTxArgs` be deleted?
</blockquote></details>

`InvokeTxArgs` struct and default constructor removed.

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1371#-:-O9dmi2W-mCzbIzriiTe:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1 and @noam-starkware)

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1371)* status: all files reviewed, 1 unresolved discussion (waiting on @noam-starkware)

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1371#-:-O9dzwby4jrownsRXITE:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noam-starkware)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1371#-:-O9hSQz-2cZKgGCQmExq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noam-starkware)

**Pull request merged**
