### PR TITLE
test(storage): regression test for serialization and deserialization

### PR DESCRIPTION
**Pull request by AlonLStarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/239)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
+reviewer:@dan-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/239#-:-O3D1ujRD9kz1T7Bc63u:bu88ic7)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @dan-starkware and @eitanm-starkware)

**Review by ShahakShama — APPROVED** [review]
> Reviewed 6 of 9 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/239)* status: all files reviewed (commit messages unreviewed), 18 unresolved discussions (waiting on @AlonLStarkWare, @dan-starkware, and @eitanm-starkware)

___
*[`crates/papyrus_storage/resources/casm/account.bin` line 0 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D28ZMCR5DF_xnguvG:-O3D28ZN8Z1TKY71AFE6:b9cvtia) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/resources/casm/account.bin#L0)):*
Ask @remollemo which type of account he gave us (send him the class hash I've sent you) and rename this file
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 138 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D3APi31Qfo0nHQLf3:-O3D3APi31Qfo0nHQLf4:b-enj9ro) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L138)):*
> ```XML
>     assert_eq!(input, deserialized);
> }
> const SERIALIZATION_REGRESSION_FILES: [&str; 3] = ["account", "ERC20", "large_contract"];
> ```

Change this to a list of tuples of files where you put ("*.json", "*.bin") in each tuple. No need to add an assumption that the file names are identical
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D2JQv4uRNcOh0DgNS:-O3D2JQw39MymwZfzwCI:bmilkkb) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L141)):*
> ```XML
> 
> #[test]
> fn serialization_regression() {
> ```

casm should be in the name of these 2 tests and in the name of the helper function
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D31152B8WdlaMrqkp:-O3D31152B8WdlaMrqkq:blqeqdn) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L147)):*
> ```XML
>     }
> 
>     let resources_path = Path::new(&env::var("CARGO_MANIFEST_DIR").unwrap()).join("resources");
> ```

We have a utility for this: https://github.com/starkware-libs/papyrus/blob/3bcfcc67c7ca8ec83466090bafe23e591b8636bb/crates/starknet_client/src/test_utils/read_resource.rs#L6
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D3bQo7c_NQNsr8HH_:-O3D3bQo7c_NQNsr8HHa:b-57xofr) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L151)):*
> ```XML
>         let json_str =
>             read_to_string(resources_path.join("casm").join(format!("{}.json", casm_file)))
>                 .unwrap_or_else(|err| panic!("Failed to read casm file: {casm_file}\n {err}"));
> ```

No need to see the error. These errors are very not informative anyway. You can use expect instead which is cleaner
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 153 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D3T-C2lXi0RSVtfh_:-O3D3T-C2lXi0RSVtfha:b-57xofr) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L153)):*
> ```XML
>                 .unwrap_or_else(|err| panic!("Failed to read casm file: {casm_file}\n {err}"));
>         let casm = serde_json::from_str::<CasmContractClass>(&json_str)
>             .unwrap_or_else(|err| panic!("Failed to deserialize casm file: {casm_file}\n {err}"));
> ```

No need to see the error. These errors are very not informative anyway. You can use expect instead which is cleaner
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 156 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D3faT2jBgwKaDy6O8:-O3D3faT2jBgwKaDy6O9:b-57xofr) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L156)):*
> ```XML
>         let mut serialized: Vec<u8> = Vec::new();
>         casm.serialize_into(&mut serialized)
>             .unwrap_or_else(|err| panic!("Failed to serialize casm file: {casm_file}\n {err}"));
> ```

No need to see the error. These errors are very not informative anyway. You can use expect instead which is cleaner
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 165 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D4BlJ4q4Hu2DyCTce:-O3D4BlJ4q4Hu2DyCTcf:b-iz7tzp) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L165)):*
> ```XML
>                     )
>                 });
>         let mut buffer = Vec::new();
> ```

rename buffer to regression_casm or hardcoded_casm or resources_casm
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D2hS3Eoi4wxeHFchj:-O3D2hS3Eoi4wxeHFchk:bossfgz) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L171)):*
> ```XML
>         assert_eq!(
>             buffer, serialized,
>             "Assertion failed duo to serialization mismatch.\n Consider re-generating the binary \
> ```

duo -> do
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D2iu3AgIc3jMwzAK5:-O3D2eMP2HuaW0G0eht2:bbyfm54) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L171)):*
> ```XML
>         assert_eq!(
>             buffer, serialized,
>             "Assertion failed duo to serialization mismatch.\n Consider re-generating the binary \
> ```

Extract this message to a constant to avoid duplication (Unless you end up changing the 2nd one and they end up not the same. Anyway, try to extract the identical parts)
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D5mc_2Dzzsx1y14mF:-O3D5mc_2Dzzsx1y14mG:bu2utto) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L171)):*
> ```XML
>         assert_eq!(
>             buffer, serialized,
>             "Assertion failed duo to serialization mismatch.\n Consider re-generating the binary \
> ```

Consider instead "Serializing the casm gave a result different from the hardcoded serialization.\n Consider ..."
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 172 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D2ZMJ0xdbV3P8NO1I:-O3D2ZMJ0xdbV3P8NO1J:bsaakn0) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L172)):*
> ```XML
>             buffer, serialized,
>             "Assertion failed duo to serialization mismatch.\n Consider re-generating the binary \
>              files by running with FIX=1."
> ```

by re-running the test with the env var FIX=1
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 172 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D5zIo11VQuWjzQk3m:-O3D5zIo11VQuWjzQk3n:b27doow) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L172)):*
> ```XML
>             buffer, serialized,
>             "Assertion failed duo to serialization mismatch.\n Consider re-generating the binary \
>              files by running with FIX=1."
> ```

"re-generating the binary files" -> "re-generating the hardcoded/regression/resource binary files if you're ok with the serialization changing by ... FIX=1 (Note that this should probably increase the major storage version)
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D4JSE4V0VufjBYQ2W:-O3D4JSE4V0VufjBYQ2X:b-25aae9) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L189)):*
> ```XML
>             File::open(resources_path.join("casm").join(format!("{}.bin", casm_file)))
>                 .unwrap_or_else(|err| panic!("Failed to open bin file: {casm_file}\n {err}"));
>         let mut bin = Vec::new();
> ```

Change bin to regression_casm_bytes or the rest of the options I wrote above with the suffix of _bytes
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 196 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D6xtkBgDMAB1B3K7S:-O3D6xtkBgDMAB1B3K7T:btjh6bt) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L196)):*
> ```XML
>             )
>         });
>         let bin_casm = CasmContractClass::deserialize_from(&mut bin.as_slice())
> ```

Change this to regression_casm or the rest of the options I wrote above
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 205 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D2pt-61tP-4h6uB5h:-O3D2pt-61tP-4h6uB5i:bumf2l4) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L205)):*
> ```XML
>         assert_eq!(
>             bin_casm, json_casm,
>             "Assertion failed duo to serialization mismatch.\n Consider re-generating the binary \
> ```

This is not serialization. Consider instead "Deserializing the hardcoded serialization gave a different result"
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 211 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D2TDn65xNezFpomHf:-O3D2TDn65xNezFpomHg:b-td7672) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L211)):*
> ```XML
> }
> 
> fn fix_serialization_regression() {
> ```

This is both serialization and deserialization. Rename to fix_casm_regression_file
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 223 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D7GiC5WjyN54iZFuO:-O3D7GiC5WjyN54iZFuP:b8vuvgc) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L223)):*
> ```XML
>         casm.serialize_into(&mut serialized).unwrap();
>         let bytes = serialized.into_boxed_slice();
>         let mut bin = File::create(resources_path.join("casm").join(format!("{}.bin", casm_file)))
> ```

Rename to bin_file

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/239)* status: 6 of 11 files reviewed, 18 unresolved discussions (waiting on @dan-starkware, @eitanm-starkware, and @ShahakShama)

___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 138 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D3APi31Qfo0nHQLf3:-O3S8FG45mBCKzHzi6Vw:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L138)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change this to a list of tuples of files where you put ("*.json", "*.bin") in each tuple. No need to add an assumption that the file names are identical
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D2JQv4uRNcOh0DgNS:-O3S8Ggv3g5RSGc13aof:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L141)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

casm should be in the name of these 2 tests and in the name of the helper function
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D31152B8WdlaMrqkp:-O3SZSEmBgWeKGF69yxX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L147)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

We have a utility for this: https://github.com/starkware-libs/papyrus/blob/3bcfcc67c7ca8ec83466090bafe23e591b8636bb/crates/starknet_client/src/test_utils/read_resource.rs#L6
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D3bQo7c_NQNsr8HH_:-O3S8IyB1PCtneDdjPsf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L151)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No need to see the error. These errors are very not informative anyway. You can use expect instead which is cleaner
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 153 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D3T-C2lXi0RSVtfh_:-O3S8Jsb3CuaITfNgrwb:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L153)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No need to see the error. These errors are very not informative anyway. You can use expect instead which is cleaner
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 156 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D3faT2jBgwKaDy6O8:-O3SCBOU2bbN7dzJWrDA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L156)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No need to see the error. These errors are very not informative anyway. You can use expect instead which is cleaner
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 165 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D4BlJ4q4Hu2DyCTce:-O3SCCHo3Mydge6cZrfj:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L165)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename buffer to regression_casm or hardcoded_casm or resources_casm
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D2hS3Eoi4wxeHFchj:-O3SGqYY-T7pXKV9ea1F:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L171)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

duo -> do
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D2iu3AgIc3jMwzAK5:-O3SGqkMDMaVbUe7Wm81:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L171)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Extract this message to a constant to avoid duplication (Unless you end up changing the 2nd one and they end up not the same. Anyway, try to extract the identical parts)
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D5mc_2Dzzsx1y14mF:-O3SGs7qEDh1HrvoEj2Z:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L171)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider instead "Serializing the casm gave a result different from the hardcoded serialization.\n Consider ..."
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 172 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D2ZMJ0xdbV3P8NO1I:-O3SGsbF8sfPUOck3I3K:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L172)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

by re-running the test with the env var FIX=1
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 172 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D5zIo11VQuWjzQk3m:-O3SGt-nDqGQ5fYMnWLS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L172)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

"re-generating the binary files" -> "re-generating the hardcoded/regression/resource binary files if you're ok with the serialization changing by ... FIX=1 (Note that this should probably increase the major storage version)
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D4JSE4V0VufjBYQ2W:-O3SGtZI41_ziL_HkDBj:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L189)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change bin to regression_casm_bytes or the rest of the options I wrote above with the suffix of _bytes
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 196 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D6xtkBgDMAB1B3K7S:-O3SGx_v0GBdOEHeKsa8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L196)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change this to regression_casm or the rest of the options I wrote above
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 205 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D2pt-61tP-4h6uB5h:-O3SH37b4vqpyR0-rw30:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L205)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is not serialization. Consider instead "Deserializing the hardcoded serialization gave a different result"
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 211 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D2TDn65xNezFpomHf:-O3SMdgk7QzzDDXfGHf_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L211)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is both serialization and deserialization. Rename to fix_casm_regression_file
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 223 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D7GiC5WjyN54iZFuO:-O3SMl9M4BDqDYJ1_oPW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L223)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to bin_file
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/239)* status: all files reviewed, 5 unresolved discussions (waiting on @AlonLStarkWare, @dan-starkware, and @eitanm-starkware)

___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D2JQv4uRNcOh0DgNS:-O3SlulJ5f0ULieg40XR:b-d9nt5p) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L141)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What about the deserialization test?
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D31152B8WdlaMrqkp:-O3VrEqVE24JfMKyyIxh:b-9ajiux) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L147)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, I meant this one: https://github.com/starkware-libs/sequencer/blob/770e2ed0f6a804762e5425d8ec321918af97af62/crates/papyrus_test_utils/src/lib.rs#L180

The storage should not depend on the client
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 223 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D7GiC5WjyN54iZFuO:-O3VsPdWAV2HUvarjWlf:b-b53kza) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L223)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

On second thought, maybe hardcoded_file is better
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 192 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3VsBmr0WX2l0YOPJKE:-O3VsBmr0WX2l0YOPJKF:b-ehxpjr) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed7cc73e937a6d1d5e4b3e7c6e8b6b31e497302f/crates/papyrus_storage/src/serialization/serializers_test.rs#L192)):*
> ```XML
>     let resources_path = Path::new(&env::var("CARGO_MANIFEST_DIR").unwrap()).join("resources");
>     for (json_file_name, bin_file_name) in SERIALIZATION_REGRESSION_FILES {
>         let mut bin_file = File::open(resources_path.join("casm").join(bin_file_name))
> ```

Change bin_file to regression_casm_file

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/239)* status: 4 of 11 files reviewed, 5 unresolved discussions (waiting on @dan-starkware, @eitanm-starkware, @remollemo, and @ShahakShama)

___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D2JQv4uRNcOh0DgNS:-O3WT09c4RzuSdGq6ynB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L141)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What about the deserialization test?
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D31152B8WdlaMrqkp:-O3WbKRU3sPKkV1W_txz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L147)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Sorry, I meant this one: https://github.com/starkware-libs/sequencer/blob/770e2ed0f6a804762e5425d8ec321918af97af62/crates/papyrus_test_utils/src/lib.rs#L180

The storage should not depend on the client
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 223 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D7GiC5WjyN54iZFuO:-O3bU-T201U90fzR8av-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/src/serialization/serializers_test.rs#L223)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

On second thought, maybe hardcoded_file is better
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/serialization/serializers_test.rs` line 192 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3VsBmr0WX2l0YOPJKE:-O3bTv6IBAdiLfgYNhO5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed7cc73e937a6d1d5e4b3e7c6e8b6b31e497302f/crates/papyrus_storage/src/serialization/serializers_test.rs#L192)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change bin_file to regression_casm_file
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/resources/casm/account.bin` line  at r2](https://reviewable.io/reviews/starkware-libs/sequencer/239#-O3D28ZMCR5DF_xnguvG:-O3WSHbREwgXOVmfvxYL:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d78733782d27274d4f46ad349fd8f16f1cca4080/crates/papyrus_storage/resources/casm/account.bin#L)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Ask @remollemo which type of account he gave us (send him the class hash I've sent you) and rename this file
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/239#-:-O3l0iu306DoJkQqDnfU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @eitanm-starkware)

**Pull request merged**
