### PR TITLE
test(blockifier): update expected_validate_call_info for new sierra g…

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
…as bound

### CODE REVIEW

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1454)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1454)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1577 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1454#-O9nnPerCEFMJCgbIYBg:-O9nnPerCEFMJCgbIYBh:b6rv030) ([raw file](https://github.com/starkware-libs/sequencer/blob/2685763d6333804453d8dea30af1dbef477241cc/crates/blockifier/src/transaction/transactions_test.rs#L1577)):*
> ```XML
>             .get_class()
>             .tracked_resource(&versioned_constants.min_compiler_version_for_sierra_gas),
>         match default_l1_resource_bounds {
> ```

 Put this in a test util function

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1454)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @TzahiTaub and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1577 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1454#-O9nnPerCEFMJCgbIYBg:-O9nsVuM7yUns-yCC7Os:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2685763d6333804453d8dea30af1dbef477241cc/crates/blockifier/src/transaction/transactions_test.rs#L1577)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Put this in a test util function
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1454#-:-O9o0mjI2n7_da4L2a9A:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
