### PR TITLE
refactor: use criterion workspace in committer

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/317)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/317?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#317** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/317?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#316** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/316?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#315** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/315?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#313** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/313?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#311** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/311?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main-v0.13.2`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/317)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`Cargo.toml` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/317#-O3a_oeS2hiAP8g5X01d:-O3a_oeS2hiAP8g5X01e:beu3veg) ([raw file](https://github.com/starkware-libs/sequencer/blob/c2a490ac82603181f6e3cdf2ba3d905da339eaf0/Cargo.toml#L81)):*
> ```TOML
> colored = "2.1.0"
> const_format = "0.2.30"
> criterion = { version = "0.5.1", features = ["html_reports"] }
> ```

no features in root cargo toml (see first PR)
___
*[`crates/committer_cli/Cargo.toml` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/317#-O3a_rDxCPAUJkqzl26y:-O3a_rDxCPAUJkqzl26z:b-n4ac2p) ([raw file](https://github.com/starkware-libs/sequencer/blob/c2a490ac82603181f6e3cdf2ba3d905da339eaf0/crates/committer_cli/Cargo.toml#L13)):*
> ```TOML
> 
> [dev-dependencies]
> criterion.workspace = true
> ```

feature here

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/317)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/317)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/317)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
