### PR TITLE
chore: add impl from rpc tx to snapi tx

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/668)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#517** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/517?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2  dependent PRs ([#518](https://github.com/starkware-libs/sequencer/pull/518) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/518?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#519](https://github.com/starkware-libs/sequencer/pull/519) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/519?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#668** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/668?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ArniStarkware** [comment]
@MohammadNassar1 You suggested we create the `into` methods instead of the `from` methods.

Here is a PR doing that: #679

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/668)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/668#-O5mF8uJ3-T0Pargd50B:-O5qTim5DGrzM0fJVoCM:bmtob6y) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

@MohammadNassar1 You suggested we create the `into` methods instead of the `from` methods.

Here is a PR doing that: #679
</blockquote></details>

Also - in this PR, we now have these implementations in rpc_transaction.rs

___

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/668#-:-O5sBAue5KoE56Kmypj6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
