### PR TITLE
test(blockifier): l1 bounds -> all bounds (or parametrize) in account transaction test

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1312)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1312?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1313** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1313?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1312** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1312?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1311** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1311?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1310** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1310?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1309** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1309?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1308** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1308?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1307** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1307?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1306** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1306?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yoavGrs — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1312)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 372 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1312#-OAI-NqUCvq-CeMn6v4q:-OAI-NqV1Dfa4pqbIsE8:b-qs6nlr) ([raw file](https://github.com/starkware-libs/sequencer/blob/f056a9d7c0a8b906c6f0e9e93c6b6a0f15db9265/crates/blockifier/src/transaction/account_transactions_test.rs#L372)):*
> ```XML
>     #[values(true, false)] normal_recurse: bool,
>     mut block_context: BlockContext,
>     #[values(default_l1_resource_bounds(), default_all_resource_bounds())]
> ```

Why both?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1312)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 372 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1312#-OAI-NqUCvq-CeMn6v4q:-OAI_0y9CBCoGfDGhWbB:big2uqr) ([raw file](https://github.com/starkware-libs/sequencer/blob/f056a9d7c0a8b906c6f0e9e93c6b6a0f15db9265/crates/blockifier/src/transaction/account_transactions_test.rs#L372)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Why both?
</blockquote></details>

so we know runs are limited by resources in both cases

**Review by yoavGrs — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1312)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
