### PR TITLE
test(starknet_integration_tests): add second node

### PR DESCRIPTION
**Pull request by alonh5**

### CODE REVIEW

**Comment by alonh5** [comment]
* **#2727** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2727?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2727?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 13 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2727)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @Itay-Tsabary-Starkware)

___
*[`crates/starknet_mempool/src/mempool.rs` line 204 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET0gBj7C2nhfyB0J3F:-OET0gBj7C2nhfyB0J3G:b2nh4b5) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_mempool/src/mempool.rs#L204)):*
> ```XML
>     pub fn add_tx(&mut self, args: AddTransactionArgs) -> MempoolResult<()> {
>         let AddTransactionArgs { tx, account_state } = args;
>         tracing::debug!("Adding transaction to mempool: {tx:?}.");
> ```

:#?



_Code quote:_
```XML
:?
```
___
*[`crates/starknet_gateway/src/gateway.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OEO-PCQ50CG4sJNi7E1:-OEO-PCQ50CG4sJNi7E2:b-y4dtl8) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b724cd5388967a7b398ac5878d4ef0b9ed665ba/crates/starknet_gateway/src/gateway.rs#L67)):*
> ```XML
>         p2p_message_metadata: Option<BroadcastedMessageMetadata>,
>     ) -> GatewayResult<TransactionHash> {
>         info!("Processing tx: {:?}", tx);
> ```

Consider :#?



_Code quote:_
```XML
:?
```
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OESzjR8-n2fE_uCOTX3:-OESzjR8-n2fE_uCOTX4:b4r9zku) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_integration_tests/src/end_to_end_integration.rs#L103)):*
> ```XML
> 
>     info!("Shutting node 0 down.");
>     node_0_run_task.abort();
> ```

Not in the scope of this PR, but is the node task cancellation safe?
@Itay-Tsabary-Starkware 



_Code quote:_
```XML
node_0_run_task.abort();
```
___
*[`crates/starknet_sequencer_node/src/test_utils/node_runner.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET0xnh2gM4J2QQSDQs:-OET0xnh2gM4J2QQSDQt:b-61gw87) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_sequencer_node/src/test_utils/node_runner.rs#L12)):*
> ```XML
> pub const NODE_EXECUTABLE_PATH: &str = "target/debug/starknet_sequencer_node";
> 
> pub async fn spawn_run_node(node_config_path: PathBuf) -> JoinHandle<()> {
> ```

Consider instrumenting



_Code quote:_
```XML
pub async fn spawn_run_node
```
___
*[`crates/starknet_sequencer_node/src/test_utils/node_runner.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET0sxX-bFCPKLmzJnu:-OET0sxX-bFCPKLmzJnv:b2fgk2v) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_sequencer_node/src/test_utils/node_runner.rs#L13)):*
> ```XML
> 
> pub async fn spawn_run_node(node_config_path: PathBuf) -> JoinHandle<()> {
>     task::spawn(async move {
> ```

Add `.in_current_span()`



_Code quote:_
```XML
task::spawn
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2727)* status: all files reviewed, 6 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OESzjR8-n2fE_uCOTX3:-OET1fc85Dqf3aq_rQNE:be2zd8s) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_integration_tests/src/end_to_end_integration.rs#L103)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Not in the scope of this PR, but is the node task cancellation safe?
@Itay-Tsabary-Starkware
</blockquote></details>

Yes.

Why aren't you shutting down the other node as well?
___
*[`crates/starknet_mempool/src/mempool.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET0MBc-Kzfv0ZRGHwN:-OET0MBd99Io6dt9b4V9:b-zevqyt) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_mempool/src/mempool.rs#L174)):*
> ```XML
>         }
> 
>         tracing::info!(
> ```

Import tracig, use short version.



_Code quote:_
```XML
tracing::info!
```
___
*[`crates/starknet_sequencer_node/src/test_utils/node_runner.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET0FEbDU0IOh-WFa3b:-OET0FEcBI9jxycs1gwI:b2dzjcn) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_sequencer_node/src/test_utils/node_runner.rs#L15)):*
> ```XML
>     task::spawn(async move {
>         info!("Running the node from its spawned task.");
>         let _node_run_result = spawn_node_child_process(node_config_path).
> ```

This is actually a tokio task. Why did you change this?



_Code quote:_
```XML
process
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2727)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OESzjR8-n2fE_uCOTX3:-OET1z7tDN6vkXyP5gxP:b-fuomlb) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_integration_tests/src/end_to_end_integration.rs#L103)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Yes.

Why aren't you shutting down the other node as well?
</blockquote></details>

Ah missed it, sorry.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2727)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET27Oz6bBfpZgjgufk:-OET27Oz6bBfpZgjgufl:bx03y5q) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_integration_tests/src/end_to_end_integration.rs#L115)):*
> ```XML
>         res.expect_err("Node 1 should have been stopped.").is_cancelled(),
>         "Node 1 should have been stopped."
>     );
> ```

You can first abort the tasks, then join their awaits, and then assert the results.



_Code quote:_
```XML
    info!("Shutting node 0 down.");
    node_0_run_task.abort();
    let res = node_0_run_task.await;
    assert!(
        res.expect_err("Node 0 should have been stopped.").is_cancelled(),
        "Node 0 should have been stopped."
    );
    info!("Shutting node 1 down.");
    node_1_run_task.abort();
    let res = node_1_run_task.await;
    assert!(
        res.expect_err("Node 1 should have been stopped.").is_cancelled(),
        "Node 1 should have been stopped."
    );
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2727)* status: all files reviewed, 6 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_gateway/src/gateway.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OEO-PCQ50CG4sJNi7E1:-OET2fqi2kJyOzcNBfB6:b5hgwba) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b724cd5388967a7b398ac5878d4ef0b9ed665ba/crates/starknet_gateway/src/gateway.rs#L67)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider :#?
</blockquote></details>

Does this need to be `info!`, or does `debug` suffice? I suggest the latter.consensus\_proposals\_channels
___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET321K1a1tPBFim169:-OET321L0rX1Xv3O2HKv:b-bq77hn) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_integration_tests/src/integration_test_setup.rs#L38)):*
> ```XML
> 
>     // Channels for consensus proposals, used for asserting the right transactions are proposed.
>     pub consensus_proposals_channels: BroadcastTopicChannels<StreamMessage<ProposalPart>>,
> ```

When is this used?



_Code quote:_
```XML
    // Channels for consensus proposals, used for asserting the right transactions are proposed.
    pub consensus_proposals_channels: BroadcastTopicChannels<StreamMessage<ProposalPart>>,
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2727)* status: 9 of 13 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware and @yair-starkware)

___
*[`crates/starknet_gateway/src/gateway.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OEO-PCQ50CG4sJNi7E1:-OETBIl37Khm8gboN35m:b-n6gae8) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b724cd5388967a7b398ac5878d4ef0b9ed665ba/crates/starknet_gateway/src/gateway.rs#L67)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Does this need to be `info!`, or does `debug` suffice? I suggest the latter.consensus\_proposals\_channels
</blockquote></details>

Maybe the most important functionality of the gateway is receiving txs, and there is no trace of it. I think it should be info. Remeber if we're not interested in the gateway logs we don't have to include them when running the system.
___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET321K1a1tPBFim169:-OETBwj30cUwz1-I2w6x:bu028up) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_integration_tests/src/integration_test_setup.rs#L38)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

In the integration test
</blockquote></details>

Nice catch, it isn't currently used, but will be used when we remove the storage opening and use a listen like the flow test. Do you prefer I remove it? Maybe it's better to leave it, added a TODO.
___
*[`crates/starknet_mempool/src/mempool.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET0MBc-Kzfv0ZRGHwN:-OETCfhB74wfVBmaGJOk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_mempool/src/mempool.rs#L174)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Import tracig, use short version.
</blockquote></details>

Done.
___
*[`crates/starknet_sequencer_node/src/test_utils/node_runner.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET0xnh2gM4J2QQSDQs:-OETB86dE48_Zlx0ncOH:b28db51) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_sequencer_node/src/test_utils/node_runner.rs#L12)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider instrumenting
</blockquote></details>

How will this change the way the logs look?
___
*[`crates/starknet_sequencer_node/src/test_utils/node_runner.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET0sxX-bFCPKLmzJnu:-OETAKYW6EcDjBAhcY_S:b-n4w04m) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_sequencer_node/src/test_utils/node_runner.rs#L13)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add `.in_current_span()`
</blockquote></details>

Same question as above.
___
*[`crates/starknet_sequencer_node/src/test_utils/node_runner.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET0FEbDU0IOh-WFa3b:-OETA_dq7S7ChQxCv0i3:b70exfm) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_sequencer_node/src/test_utils/node_runner.rs#L15)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

This is actually a tokio task. Why did you change this?
</blockquote></details>

The function `Executes the command as a child process`  according to the documentation. This is what we want for the milestone - if it's a tokio async task then we aren't achieving that.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2727)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @Itay-Tsabary-Starkware)

___
*[`crates/starknet_gateway/src/gateway.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OEO-PCQ50CG4sJNi7E1:-OETHOanEb3yYpTQ7_o2:bdshkyx) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b724cd5388967a7b398ac5878d4ef0b9ed665ba/crates/starknet_gateway/src/gateway.rs#L67)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Maybe the most important functionality of the gateway is receiving txs, and there is no trace of it. I think it should be info. Remeber if we're not interested in the gateway logs we don't have to include them when running the system.
</blockquote></details>

Actually we don't need to output the tx itself because it will be in the span's fields.
___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET321K1a1tPBFim169:-OETHrvf4b_Ln_N6JFm-:bojs2kj) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_integration_tests/src/integration_test_setup.rs#L38)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Nice catch, it isn't currently used, but will be used when we remove the storage opening and use a listen like the flow test. Do you prefer I remove it? Maybe it's better to leave it, added a TODO.
</blockquote></details>

We should use monitoring instead
___
*[`crates/starknet_sequencer_node/src/test_utils/node_runner.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET0xnh2gM4J2QQSDQs:-OETHzRJ4-a85sP7dOxj:by6nbgz) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_sequencer_node/src/test_utils/node_runner.rs#L12)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

How will this change the way the logs look?
</blockquote></details>

The node config path will be added as a span field so we can know which sequencer produced the event
___
*[`crates/starknet_sequencer_node/src/test_utils/node_runner.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET0sxX-bFCPKLmzJnu:-OETI9pmCP-HE8Kgg1xN:bx520uf) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_sequencer_node/src/test_utils/node_runner.rs#L13)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Same question as above.
</blockquote></details>

It will make the events produced in the task be child of the current span, so they will have more context
___
*[`crates/starknet_gateway/src/gateway.rs` line 61 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OETGzkr2vJCdr874Kqq:-OETGzkr2vJCdr874Kqr:b-5sy64l) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ca99b5cdb8c883f8c36cf50c90d9ca9ef591606/crates/starknet_gateway/src/gateway.rs#L61)):*
> ```XML
>     }
> 
>     #[instrument(skip(self))]
> ```

Add `ret`



_Code quote:_
```XML
#[instrument(skip(self))]
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2727)* status: 10 of 13 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware and @yair-starkware)

___
*[`crates/starknet_gateway/src/gateway.rs` line 61 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OETGzkr2vJCdr874Kqq:-OETj-9y6XxHAmNsT9Gf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ca99b5cdb8c883f8c36cf50c90d9ca9ef591606/crates/starknet_gateway/src/gateway.rs#L61)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add `ret`
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET321K1a1tPBFim169:-OETjOBHD90ofpCkPqs-:b521e0n) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_integration_tests/src/integration_test_setup.rs#L38)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

We should use monitoring instead
</blockquote></details>

Changed TODO.
___
*[`crates/starknet_sequencer_node/src/test_utils/node_runner.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET0sxX-bFCPKLmzJnu:-OETjjHj4yxeOoeWr6pO:b2f3fel) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_sequencer_node/src/test_utils/node_runner.rs#L13)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

It will make the events produced in the task be child of the current span, so they will have more context
</blockquote></details>

I added the instrument to the function below instead.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-:-OEUOQ3-5kpe_j0xmTp6:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 13 files at r1, 2 of 6 files at r2, 2 of 5 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-:-OEXhZna9xD5scWTH2WS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/starknet_gateway/src/gateway.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OEO-PCQ50CG4sJNi7E1:-OEXcM0B-uHUKEAmV4iB:b7qkcze) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b724cd5388967a7b398ac5878d4ef0b9ed665ba/crates/starknet_gateway/src/gateway.rs#L67)):*
> Maybe the most important functionality of the gateway is receiving txs, and there is no trace of it. I think it should be info. 

The gateway is an internal component to the system. Does the end user that run the node care about this specific part receiving a tx?

I'd expect such messages to be in the http server and in the p2p parts, i.e., in the outward facing ones. The fact a tx made its way to the gateway from whatever endpoint is irrelevant to the user imo in normal flow, hence I suggested it should be in a debug level.

> Remeber if we're not interested in the gateway logs we don't have to include them when running the system.

AFAFIU this only holds when you're using cargo, as it enables setting (through env variables) the tracing level of each component.

However, in production, we will not be using cargo, and such setting will not be available. Additionally, I strongly prefer we do not rely on env variable configurations in production -- the default setting should be of the production env, and we should customize more/less traces when running in other envs (testnet/ci/local tests).


Anyhow, this is not critical at this point, hence I left it as a non-blocking comment. Up to you.
___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET321K1a1tPBFim169:-OEXeehSA4h2_ZQwhr30:b-psfp72) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_integration_tests/src/integration_test_setup.rs#L38)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Changed TODO.
</blockquote></details>

Since the integration test runs the node as a black box, I don't see a way to connect to the node's internal channels as the flow test does.
As such, we need a way to externally query the node state to test it made the correct progress (received txs, created batches, w/e the test is testing).
Originally we resorted to externally checking the storage, and as @yair-starkware mentioned, we can also use metrics for a similar purpose.

I suggest to remove this right now, but not critical (unblocked).
___
*[`crates/starknet_sequencer_node/src/test_utils/node_runner.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET0FEbDU0IOh-WFa3b:-OEXgStLB-kX1VZ-uOAC:b559zn8) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_sequencer_node/src/test_utils/node_runner.rs#L15)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

The function `Executes the command as a child process`  according to the documentation. This is what we want for the milestone - if it's a tokio async task then we aren't achieving that.
</blockquote></details>

1. Right, my mistake.
2. As a מור"ק please know the original code tried using `std::process` instead of `tokio::process` and got dead-locked :-\

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2727)* status: 6 of 13 files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware and @yair-starkware)

___
*[`crates/starknet_gateway/src/gateway.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OEO-PCQ50CG4sJNi7E1:-OEhQMC-4UpEel5DXkz6:b-k53xdn) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b724cd5388967a7b398ac5878d4ef0b9ed665ba/crates/starknet_gateway/src/gateway.rs#L67)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

> Maybe the most important functionality of the gateway is receiving txs, and there is no trace of it. I think it should be info. 

The gateway is an internal component to the system. Does the end user that run the node care about this specific part receiving a tx?

I'd expect such messages to be in the http server and in the p2p parts, i.e., in the outward facing ones. The fact a tx made its way to the gateway from whatever endpoint is irrelevant to the user imo in normal flow, hence I suggested it should be in a debug level.

> Remeber if we're not interested in the gateway logs we don't have to include them when running the system.

AFAFIU this only holds when you're using cargo, as it enables setting (through env variables) the tracing level of each component.

However, in production, we will not be using cargo, and such setting will not be available. Additionally, I strongly prefer we do not rely on env variable configurations in production -- the default setting should be of the production env, and we should customize more/less traces when running in other envs (testnet/ci/local tests).


Anyhow, this is not critical at this point, hence I left it as a non-blocking comment. Up to you.
</blockquote></details>

The logs are for us, info is for the happy flow. I think we'd want to know that txs reached the gateway.
___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2727#-OET321K1a1tPBFim169:-OEhPy8J2_QbhEZFilo2:b-l2s3ch) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89fe97098b580be7cb4fc8e7dc8496ebd6aca5e/crates/starknet_integration_tests/src/integration_test_setup.rs#L38)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Since the integration test runs the node as a black box, I don't see a way to connect to the node's internal channels as the flow test does.
As such, we need a way to externally query the node state to test it made the correct progress (received txs, created batches, w/e the test is testing).
Originally we resorted to externally checking the storage, and as @yair-starkware mentioned, we can also use metrics for a similar purpose.

I suggest to remove this right now, but not critical (unblocked).
</blockquote></details>

We should use monitoring once it's implemented regardless. Both the flow test and the integration test run the nodes as a black box, the listening channel is not an internal channel, it's the channel used to communicate between nodes.

**Review by alonh5 — COMMENTED** [review]
> Reviewed 3 of 6 files at r2, 1 of 5 files at r3, 2 of 5 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2727)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2727)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
