### PR TITLE
feat(batcher): add validate support to build_block

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1872?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1872** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1872?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1867** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1867?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Yael-Starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1872)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1872#-OBKJi2dEsGrqZNhtt2Y:-OBKJi2dEsGrqZNhtt2Z:b-rpi74k) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb50390f2df5c954c469d5b1e635522f11bf867/crates/batcher/src/block_builder.rs#L196)):*
> ```XML
> 
> /// Returns true if the block is full and should be closed, false otherwise.
> async fn collect_execution_results_and_stream_txs(
> ```

Consider passing something like this:
```
enum HandleTxExecution {
  Propose(sender),
  Validate,
}

impl HandleTxExecution {
  pub fn(&mut self, tx_exec_result) -> BlockBuilderResult<()> {
    match (self, result) {
      (Propose(sender), Ok(_) => sender.send(tx),
      (Propose(sender), Err(_) => info!(...),
      (Validate, Ok(_)) => {},
      (Validate, Err(_)) => return Err(...),
    }
}
```

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1872)* status: all files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1872#-OBKgzvR3RgsdQxS_VFL:-OBKgzvS5olkzyY20wH3:bcfbven) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb50390f2df5c954c469d5b1e635522f11bf867/crates/batcher/src/block_builder.rs#L56)):*
> ```XML
>     StreamTransactionsError(#[from] tokio::sync::mpsc::error::SendError<Transaction>),
>     #[error("Build block with fail_on_err mode, failed on error {}.", _0)]
>     FailOnError(BlockifierTransactionExecutorError),
> ```

Why do you need this error wrapper? How about just have it `#[transparent]`?



_Code quote:_
```XML
FailOnError(BlockifierTransactionExecutorError),
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1872)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1872#-OBKgzvR3RgsdQxS_VFL:-OBKvCtiBSnK0mJIZTOJ:b-kexj9z) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb50390f2df5c954c469d5b1e635522f11bf867/crates/batcher/src/block_builder.rs#L56)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why do you need this error wrapper? How about just have it `#[transparent]`?
</blockquote></details>

I think it will make it more clear why the block builder failed on errors that are not expected to fail a block.
Otherwise someone seeing the logs may find it strange that a block building failed for BlockFull for example.
___
*[`crates/batcher/src/block_builder.rs` line 196 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1872#-OBKJi2dEsGrqZNhtt2Y:-OBKv_ep8gKL7ZVQuYeq:b-hupvxa) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb50390f2df5c954c469d5b1e635522f11bf867/crates/batcher/src/block_builder.rs#L196)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider passing something like this:
```
enum HandleTxExecution {
  Propose(sender),
  Validate,
}

impl HandleTxExecution {
  pub fn(&mut self, tx_exec_result) -> BlockBuilderResult<()> {
    match (self, result) {
      (Propose(sender), Ok(_) => sender.send(tx),
      (Propose(sender), Err(_) => info!(...),
      (Validate, Ok(_)) => {},
      (Validate, Err(_)) => return Err(...),
    }
}
```
</blockquote></details>

At the beginning I implemented something similar, but the decision (Lior's) was to make the block builder oblivious to propose/validate.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1872)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1872#-OBKgzvR3RgsdQxS_VFL:-OBLA8ozDE2GoibJg8u6:b-4kiaog) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb50390f2df5c954c469d5b1e635522f11bf867/crates/batcher/src/block_builder.rs#L56)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

There should be logs outside of the block builder saying that the proposal validation failed. The context of validate around it will make it clear, no?
</blockquote></details>

Many times when running tests, I see just the error that failed the assert , without other logs. 
IMO this adds relevant information that can save time.
___
*[`crates/batcher/src/block_builder.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1872#-OBL-fg44e7m4hSSptWb:-OBL9kJX4DAeAaogXOX3:b-tfb9ln) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb50390f2df5c954c469d5b1e635522f11bf867/crates/batcher/src/block_builder.rs#L223)):*
> ```XML
>             Err(err) => {
>                 debug!("Transaction {:?} failed with error: {}.", input_tx, err)
>             }
> ```

I think the previous version was easier to read.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1872)* status: all files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1872#-OBKgzvR3RgsdQxS_VFL:-OBLDvv5DfIBmEcJYj_w:b-6fdp3) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb50390f2df5c954c469d5b1e635522f11bf867/crates/batcher/src/block_builder.rs#L56)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Many times when running tests, I see just the error that failed the assert , without other logs. 
IMO this adds relevant information that can save time.
</blockquote></details>

Okay NP. Do you think we can find a better name? It doesn't match the `Error` suffix convention (unless you mean it a FailOn error lol).
___
*[`crates/batcher/src/block_builder.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1872#-OBL-fg44e7m4hSSptWb:-OBLCUeB-n9rYiuJIxYG:b-dkuyox) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb50390f2df5c954c469d5b1e635522f11bf867/crates/batcher/src/block_builder.rs#L223)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think the previous version was easier to read.
</blockquote></details>

This has one less arm, and also shares code.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1872)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1872#-OBL-fg44e7m4hSSptWb:-OBLjVi75HfTWp4MrIuf:b-epzrn1) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb50390f2df5c954c469d5b1e635522f11bf867/crates/batcher/src/block_builder.rs#L223)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This has one less arm, and also shares code.
</blockquote></details>

but has 2 if statements instead of one.
and one of them includes is "if not ", which is pretty confusing.
:)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1872)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1872#-OBKgzvR3RgsdQxS_VFL:-OBLkczS9UGeEdtIVMOD:b-270qpi) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb50390f2df5c954c469d5b1e635522f11bf867/crates/batcher/src/block_builder.rs#L56)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Okay NP. Do you think we can find a better name? It doesn't match the `Error` suffix convention (unless you mean it a FailOn error lol).
</blockquote></details>

FailOnErrorError? :) probably not.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1872)* status: all files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1872#-OBKgzvR3RgsdQxS_VFL:-OBPNFuC6Pidc9y0McEP:b5uti1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb50390f2df5c954c469d5b1e635522f11bf867/crates/batcher/src/block_builder.rs#L56)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

FailOnErrorError? :) probably not.
</blockquote></details>

Indeed not :) Do you think FailOnError is the best name we can find?
___
*[`crates/batcher/src/block_builder.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1872#-OBL-fg44e7m4hSSptWb:-OBPNwKy1BP__W-LuKsN:b9fxsxp) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb50390f2df5c954c469d5b1e635522f11bf867/crates/batcher/src/block_builder.rs#L223)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

but has 2 if statements instead of one.
and one of them includes is "if not ", which is pretty confusing.
:)
</blockquote></details>

Sharing code is important, even if there's not a lot to share right now. Anyway if you're not convinced we can get a third opinion.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1872#-:-OBPcT7d-ThDPIIsr1J8:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1872)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/batcher/src/block_builder.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1872#-OBKgzvR3RgsdQxS_VFL:-OBPotAt-fkBfU8ITzRJ:bafpgxy) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb50390f2df5c954c469d5b1e635522f11bf867/crates/batcher/src/block_builder.rs#L56)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Indeed not :) Do you think FailOnError is the best name we can find?
</blockquote></details>

I think so
___
*[`crates/batcher/src/block_builder.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1872#-OBL-fg44e7m4hSSptWb:-OBPox7bCDUMNI1IKbg8:b-sr72cg) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb50390f2df5c954c469d5b1e635522f11bf867/crates/batcher/src/block_builder.rs#L223)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Sharing code is important, even if there's not a lot to share right now. Anyway if you're not convinced we can get a third opinion.
</blockquote></details>

ok for the code sharing.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1872#-:-OBPrHMH99B8DYZ6BUha:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1872#-OBL-fg44e7m4hSSptWb:-OBPrDGqCxLBz0s2Uwz9:b-319cx8) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb50390f2df5c954c469d5b1e635522f11bf867/crates/batcher/src/block_builder.rs#L223)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

ok for the code sharing.
</blockquote></details>

Cool, hanks :)

**Pull request merged**
