### PR TITLE
build(fee): sn_resources depend on resource bounds signature

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/454)

### CODE REVIEW

**Comment by nimrod-starkware** [comment]
* **#455** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/455?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#454** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/454?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nimrod-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/454)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4FuMRP1vLUNMJ0BorR:-O4FuMRP1vLUNMJ0BorS:bbu4liz) ([raw file](https://github.com/starkware-libs/sequencer/blob/614086d39fe05da72a1a217ddf6a47368dfd798a/crates/blockifier/src/fee/actual_cost_test.rs#L0)):*
I would prefer the `include_l2_gas` flag be a "parametrized fixture"
TAL at [`rstest_reuse`](https://crates.io/crates/rstest_reuse), so you can define something like:
```
#[template]
#[rstest]
fn include_l2_gas_param(#[values(false)] include_l2_gas: bool) {}
```
and use it in tests like this:
```
#[apply(include_l2_gas_param)]
fn test_calculate_tx_gas_usage_basic<'a>(#[values(false, true)] use_kzg_da: bool, include_l2_gas: bool) {
   ...
```
not sure if it works, but if it does, you'll be able to edit `include_l2_gas_param` by adding `, true` to `#[values]` and get test coverage for free
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4FvBdD3yrxYfy5BU3u:-O4FvBdD3yrxYfy5BU3v:b-5evqwb) ([raw file](https://github.com/starkware-libs/sequencer/blob/614086d39fe05da72a1a217ddf6a47368dfd798a/crates/blockifier/src/fee/gas_usage_test.rs#L0)):*
ditto on the parametrization comment above
___
*[`crates/blockifier/src/transaction/objects.rs` line 320 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4FtgoY9wQL4NoWYAWf:-O4FtgoY9wQL4NoWYAWg:by7v1yv) ([raw file](https://github.com/starkware-libs/sequencer/blob/614086d39fe05da72a1a217ddf6a47368dfd798a/crates/blockifier/src/transaction/objects.rs#L320)):*
> ```XML
>             + self.get_messages_cost()
>             + self.get_events_cost(versioned_constants, include_l2_gas)
>     }
> ```

wouldn't this be cleaner?
then you wouldn't need to propagate this flag everywhere



_Suggestion:_
```XML
        versioned_constants: &VersionedConstants,
        use_kzg_da: bool,
        include_l2_gas: bool,
    ) -> GasVector {
        if include_l2_gas {
            todo!();
        } else {
            self.get_calldata_and_signature_cost(versioned_constants, include_l2_gas)
                + self.get_code_cost(versioned_constants, include_l2_gas)
                + self.get_state_changes_cost(use_kzg_da)
                + self.get_messages_cost()
                + self.get_events_cost(versioned_constants, include_l2_gas)
        }
    }
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/454)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4FuMRP1vLUNMJ0BorR:-O4Jpi16Dtw3VR0L_YON:bu6jd8j) ([raw file](https://github.com/starkware-libs/sequencer/blob/614086d39fe05da72a1a217ddf6a47368dfd798a/crates/blockifier/src/fee/actual_cost_test.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I would prefer the `include_l2_gas` flag be a "parametrized fixture"
TAL at [`rstest_reuse`](https://crates.io/crates/rstest_reuse), so you can define something like:
```
#[template]
#[rstest]
fn include_l2_gas_param(#[values(false)] include_l2_gas: bool) {}
```
and use it in tests like this:
```
#[apply(include_l2_gas_param)]
fn test_calculate_tx_gas_usage_basic<'a>(#[values(false, true)] use_kzg_da: bool, include_l2_gas: bool) {
   ...
```
not sure if it works, but if it does, you'll be able to edit `include_l2_gas_param` by adding `, true` to `#[values]` and get test coverage for free
</blockquote></details>

Nice!
I'll add it to tests that I think are independent of l1/l2 gas calculation (that don't compare hard coded gas vectors for example)
___
*[`crates/blockifier/src/transaction/objects.rs` line 320 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4FtgoY9wQL4NoWYAWf:-O4JqMt78gb1_OCgQhLy:b-u62lr4) ([raw file](https://github.com/starkware-libs/sequencer/blob/614086d39fe05da72a1a217ddf6a47368dfd798a/crates/blockifier/src/transaction/objects.rs#L320)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

wouldn't this be cleaner?
then you wouldn't need to propagate this flag everywhere
</blockquote></details>

it's cleaner but `get_calldata_and_signature_cost` needs to know whether to calculate as l1 or l2... no?

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/454)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4FuMRP1vLUNMJ0BorR:-O4K8ATr1K22iSNg1p_U:b-ajnoij) ([raw file](https://github.com/starkware-libs/sequencer/blob/614086d39fe05da72a1a217ddf6a47368dfd798a/crates/blockifier/src/fee/actual_cost_test.rs#L)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Nice!
I'll add it to tests that I think are independent of l1/l2 gas calculation (that don't compare hard coded gas vectors for example)
</blockquote></details>

added it to `test_calculate_tx_gas_usage`
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4FvBdD3yrxYfy5BU3u:-O4K89FU-6QkalVczYwr:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/614086d39fe05da72a1a217ddf6a47368dfd798a/crates/blockifier/src/fee/gas_usage_test.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto on the parametrization comment above
</blockquote></details>

Done

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/454)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/blockifier/Cargo.toml` line 68 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4K9f9o9w1nTpF-rij2:-O4K9f9o9w1nTpF-rij3:b-zh4dtg) ([raw file](https://github.com/starkware-libs/sequencer/blob/855c361c909abf469f62680a2c8b4c2f91e6d189/crates/blockifier/Cargo.toml#L68)):*
> ```TOML
> regex.workspace = true
> rstest.workspace = true
> test-case.workspace = true
> ```

to pass machete I think you'll need to do this (rstest_reuse isn't used in non-testing code)



_Suggestion:_
```TOML
rand = { workspace = true, optional = true }
rstest = { workspace = true, optional = true }
rstest_reuse = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["arbitrary_precision"] }
sha2.workspace = true
sha3.workspace = true
starknet-types-core.workspace = true
starknet_api = { workspace = true, features = ["testing"] }
strum.workspace = true
strum_macros.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tikv-jemallocator = { workspace = true, optional = true }
toml.workspace = true

[dev-dependencies]
assert_matches.workspace = true
criterion = { workspace = true, features = ["html_reports"] }
glob.workspace = true
pretty_assertions.workspace = true
rand.workspace = true
regex.workspace = true
rstest.workspace = true
rstest_reuse.workspace = true
test-case.workspace = true
```
___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4KA0Lb2sl0hL76nsxJ:-O4KA0Lb2sl0hL76nsxK:bxzv49l) ([raw file](https://github.com/starkware-libs/sequencer/blob/855c361c909abf469f62680a2c8b4c2f91e6d189/crates/blockifier/src/fee/actual_cost_test.rs#L36)):*
> ```XML
> #[rstest]
> // TODO(Nimrod): Add true as a case.
> fn include_l2_gas(#[values(false)] has_l2_gas: bool) {}
> ```

since this is used on other tests, please move it to a test utils module



_Code quote:_
```XML
#[rstest_reuse::template]
#[rstest]
// TODO(Nimrod): Add true as a case.
fn include_l2_gas(#[values(false)] has_l2_gas: bool) {}
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 320 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4FtgoY9wQL4NoWYAWf:-O4KABoL91AsxNgJxjM7:b1o95kd) ([raw file](https://github.com/starkware-libs/sequencer/blob/614086d39fe05da72a1a217ddf6a47368dfd798a/crates/blockifier/src/transaction/objects.rs#L320)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

it's cleaner but `get_calldata_and_signature_cost` needs to know whether to calculate as l1 or l2... no?
</blockquote></details>

won't there be a completely different function to compute L2 gas cost? I guess not... unblocking

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/454)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/Cargo.toml` line 68 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4K9f9o9w1nTpF-rij2:-O4KQqOpBz01JoK6VTDS:b-6k5kdp) ([raw file](https://github.com/starkware-libs/sequencer/blob/855c361c909abf469f62680a2c8b4c2f91e6d189/crates/blockifier/Cargo.toml#L68)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

to pass machete I think you'll need to do this (rstest_reuse isn't used in non-testing code)
</blockquote></details>

machete passed, but added it anyway 
___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4KA0Lb2sl0hL76nsxJ:-O4KW3vj5vLiIqy9VFnr:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/855c361c909abf469f62680a2c8b4c2f91e6d189/crates/blockifier/src/fee/actual_cost_test.rs#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

since this is used on other tests, please move it to a test utils module
</blockquote></details>

Done

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/454#-:-O4Ki3qS4ccuQkwFhHQT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils.rs` line 446 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4KhpP08P_7Zp_UxHpD:-O4KhpP08P_7Zp_UxHpE:b-rfhyac) ([raw file](https://github.com/starkware-libs/sequencer/blob/991209ea9a0808d72b7afefd63f9a5d434d3c64a/crates/blockifier/src/test_utils.rs#L446)):*
> ```XML
> }
> 
> #[cfg(test)]
> ```

why is this needed...? in case `feature = "testing"` causes this module to compile, in non-test mode?



_Code quote:_
```XML
#[cfg(test)]
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/454)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils.rs` line 446 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4KhpP08P_7Zp_UxHpD:-O4Kik_c1dSKRwQ4mEXz:b3fgykz) ([raw file](https://github.com/starkware-libs/sequencer/blob/991209ea9a0808d72b7afefd63f9a5d434d3c64a/crates/blockifier/src/test_utils.rs#L446)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this needed...? in case `feature = "testing"` causes this module to compile, in non-test mode?
</blockquote></details>

without this, i get a clippy warning for unused macros.
I think it's because it's only being used in tests (under `cfg(test)`) but not declared in a test module.
For some weird reason annotating `#[allow(unused_macros)]` didn't solve it...

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/454)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 5 of 8 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/454)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/454)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/454)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/454)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request closed without merging**
