### PR TITLE
refactor(blockifier): add getters for exclusive v3 txs fields

### PR DESCRIPTION
**Pull request by meship-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/698)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
@tdelabro

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/698#-:-O5re3jh3hN_SvCUeSd2:bkvrl3k)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @ArniStarkware and @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/698)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @noaov1)

___
*[`crates/starknet_api/src/transaction.rs` line 545 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/698#-O5s3iuCB9WvemYOA0AP:-O5s3iuCB9WvemYOA0AQ:bwrwx0u) ([raw file](https://github.com/starkware-libs/sequencer/blob/987f8480e29b970146029e403109312bd91734dd/crates/starknet_api/src/transaction.rs#L545)):*
> ```XML
> }
> 
> macro_rules! implement_invoke_tx_v3_getters {
> ```

see discussion https://reviewable.io/reviews/starkware-libs/sequencer/229#-O5qh__jDJPHHcSzgioT
Default is a bit misleading, iMO; I think it should be an error. I am not sure if the user should be able to deal with it.

**Comment by ArniStarkware** [comment]
*[`crates/starknet_api/src/transaction.rs` line 554 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/698#-O5vlM6s3AXMJee6J1bc:-O5vlM6s3AXMJee6J1bd:bz9ivd5) ([raw file](https://github.com/starkware-libs/sequencer/blob/420f02d6269563cd5638a3aaa5d643ba895d7319/crates/starknet_api/src/transaction.rs#L554)):*
> ```XML
>         })*
>     };
> }
> ```

1. you had a typo here. This is invoke tx - the panic message was for declare.
2. Share this code. We need only one macro: `implement_v3_tx_getters`

In another thread, we will talk about the contents of this macro.



_Suggestion:_
```XML
macro_rules! implement_invoke_tx_v3_getters {
    ($(($field:ident, $field_type:ty)),*) => {
        $(pub fn $field(&self) -> $field_type {
            match self {
                Self::V3(tx) => tx.$field.clone(),
                _ => panic!("Field {} is only available for {}.", stringify!($field), $tx_type),
            }
        })*
    };
}
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
I don't think there should be getters for these fields.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/698#-:-O5vpmJI2UBBDQxmux6l:bz7y3s3)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/starknet_api/src/transaction.rs` line 545 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/698#-O5s3iuCB9WvemYOA0AP:-O5vmq4G0tjQWjGEsWmD:byyciev) ([raw file](https://github.com/starkware-libs/sequencer/blob/987f8480e29b970146029e403109312bd91734dd/crates/starknet_api/src/transaction.rs#L545)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

see discussion https://reviewable.io/reviews/starkware-libs/sequencer/229#-O5qh__jDJPHHcSzgioT
Default is a bit misleading, iMO; I think it should be an error. I am not sure if the user should be able to deal with it.
</blockquote></details>

I think these should either not exist ( ask the end user to peal out the field from the transaction they are getting.
Or - these should not be getters but: `try_get_field` which Returns a `Result<$field_type, StarknetApiError>`

**Comment by ArniStarkware** [comment]
I regret that - I wrote a suggestion in one of the threads.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/698)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/starknet_api/src/transaction.rs` line 554 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/698#-O5vlM6s3AXMJee6J1bc:-O7gwdqgAbJIxx807w00:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/420f02d6269563cd5638a3aaa5d643ba895d7319/crates/starknet_api/src/transaction.rs#L554)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

1. you had a typo here. This is invoke tx - the panic message was for declare.
2. Share this code. We need only one macro: `implement_v3_tx_getters`

In another thread, we will talk about the contents of this macro.
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/transaction.rs` line 298 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/698#-O7gvdHd0RB-Y1DoEEQW:-O7gvdHd0RB-Y1DoEEQX:bx1ef55) ([raw file](https://github.com/starkware-libs/sequencer/blob/37dfed5a8621b5ca737400f114d4f74a218d0642/crates/starknet_api/src/transaction.rs#L298)):*
> ```XML
>             DeclareTransaction::V3(tx) => tx.compiled_class_hash,
>         }
>     }
> ```

I am not sure about this getter. I only added it, so it won't be the only non-deprecated field that does not have a getter
see: https://reviewable.io/reviews/starkware-libs/sequencer/699#-O5vrl_Y92H_8WwJfmdU 
I decided to move it to this PR because it involves handling versions.    



_Code quote:_
```XML
    pub fn compiled_class_hash(&self) -> CompiledClassHash {
        match self {
            DeclareTransaction::V0(_) | DeclareTransaction::V1(_) => {
                panic!("Cairo0 DeclareTransaction (V0, V1) doesn't have compiled_class_hash.")
            }
            DeclareTransaction::V2(tx) => tx.compiled_class_hash,
            DeclareTransaction::V3(tx) => tx.compiled_class_hash,
        }
    }
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/698)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/698)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/starknet_api/src/transaction.rs` line 106 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/698#-O7gz3Ka44SIcwz8O9ST:-O7h9roX30L46tYlXkV8:bqtyay2) ([raw file](https://github.com/starkware-libs/sequencer/blob/37dfed5a8621b5ca737400f114d4f74a218d0642/crates/starknet_api/src/transaction.rs#L106)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

How does it look printed?
It seems like it reads:
`Field tip is not available for 1, its only available for V3 transactions.`

Where it should read something like:
`Version 1 transaction does not support the field tip, its only available for V3 transactions.`
Or whatever phrasing Grammarly suggests.
</blockquote></details>

This is how it printed:
TransactionVersion(0x1)  do not support the field tip; they are only available for V3 transactions.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/698)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

___
*[`crates/starknet_api/src/transaction.rs` line 545 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/698#-O5s3iuCB9WvemYOA0AP:-O7hFXSS0UyYnsS4czo5:bjudfui) ([raw file](https://github.com/starkware-libs/sequencer/blob/987f8480e29b970146029e403109312bd91734dd/crates/starknet_api/src/transaction.rs#L545)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I think these should either not exist ( ask the end user to peal out the field from the transaction they are getting.
Or - these should not be getters but: `try_get_field` which Returns a `Result<$field_type, StarknetApiError>`
</blockquote></details>

I prefer optional.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/698)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/starknet_api/src/transaction.rs` line 545 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/698#-O5s3iuCB9WvemYOA0AP:-O7hGnWqAb5Xyfh6qHdj:b790qqr) ([raw file](https://github.com/starkware-libs/sequencer/blob/987f8480e29b970146029e403109312bd91734dd/crates/starknet_api/src/transaction.rs#L545)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I prefer optional.
</blockquote></details>

@noaov1 WDYT? Do you prefer Optional, like we handling the missing tx or do you prefer the panic! solution?

**Review by noaov1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/698)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_api/src/transaction.rs` line 545 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/698#-O5s3iuCB9WvemYOA0AP:-O7iYehkDBIv4XJGb8np:b-sy7nzr) ([raw file](https://github.com/starkware-libs/sequencer/blob/987f8480e29b970146029e403109312bd91734dd/crates/starknet_api/src/transaction.rs#L545)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

@noaov1 WDYT? Do you prefer Optional, like we handling the missing tx or do you prefer the panic! solution?
</blockquote></details>

Panic is great.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/698#-:-O7wiHcmBS2iqAdGAk84:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/698)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Pull request merged**
