### PR TITLE
feat(starknet_api): nonce try_decrement func

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/601)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/601)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/601#-O5DsTui9FIAoNIaYLc1:-O5DsTui9FIAoNIaYLc2:b37wjms) (no related file):*
will be used in mempool's suspended_tx_pool

___

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/601)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/starknet_api/src/core.rs` line 222 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/601#-O5MlIcL5VT6pD_hBH5c:-O5MlIcMD39Mxt4laHw4:b-qhit9q) ([raw file](https://github.com/starkware-libs/sequencer/blob/cada78a0867c56069a6f1da9097062b48a3ab3cb/crates/starknet_api/src/core.rs#L222)):*
> ```XML
>         }
>         Ok(Self(self.0 - Felt::ONE))
>     }
> ```

Can you use Felt logic for this kind of check? what happens in felt when there's an underflow?



_Code quote:_
```XML
    pub fn try_decrement(&self) -> Result<Self, StarknetApiError> {
        // Check if an underflow occurred during decrement.
        if self.0 == Felt::ZERO {
            return Err(StarknetApiError::OutOfRange { string: format!("{:?}", self) });
        }
        Ok(Self(self.0 - Felt::ONE))
    }
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/601)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/starknet_api/src/core.rs` line 222 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/601#-O5MlIcL5VT6pD_hBH5c:-O5N-6Tw-y-aADXrFZyZ:bywrll0) ([raw file](https://github.com/starkware-libs/sequencer/blob/cada78a0867c56069a6f1da9097062b48a3ab3cb/crates/starknet_api/src/core.rs#L222)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can you use Felt logic for this kind of check? what happens in felt when there's an underflow?
</blockquote></details>

When you subtract `1` from `0` in `Felt`, it doesn't cause an error or panic. Instead, it gives the highest possible number in the field.

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/601#-:-O5NIsIH2s6sZ_8uvCaS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Pull request merged**
