### PR TITLE
chore(mempool): derive copy trait for pending and priority structs

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/839)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/839)* status: 0 of 2 files reviewed, 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/839#-O7-2gBz886FjEhw74sv:-O7-2gBz886FjEhw74sw:b-vhm6l3) (no related file):*
`Clone` cannot be removed as`Copy` trait is defined to have `Clone` as supertrait.  
So every structure must also add the implementation.

___
___
*[`crates/mempool/src/transaction_queue.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/839#-O7-2qgr0ztAAXW5MiLA:-O7-2qgr0ztAAXW5MiLB:b-vhm6l3) ([raw file](https://github.com/starkware-libs/sequencer/blob/63bde95686edd54eb95b45cb3395578349f193d7/crates/mempool/src/transaction_queue.rs#L139)):*
> ```XML
> /// Encapsulates a transaction reference to assess its order (i.e., gas price).
> #[derive(Copy, Debug, derive_more::Deref, derive_more::From)]
> struct PendingTransaction(pub TransactionReference);
> ```

`Clone` cannot be removed as`Copy` trait is defined to have `Clone` as supertrait.  
So every structure must also add the implementation.



_Code quote:_
```XML
PendingTransaction
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/839)* status: 0 of 2 files reviewed, 3 unresolved discussions

___
*[`crates/mempool/src/transaction_queue.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/839#-O7-6Zsm7TABESkkkWFF:-O7-6Zsm7TABESkkkWFG:bxla1cb) ([raw file](https://github.com/starkware-libs/sequencer/blob/e47b9bf17095208c5ab3b1ad13e52781a189ca9e/crates/mempool/src/transaction_queue.rs#L120)):*
> ```XML
>             txs_over_threshold
>                 .map(|tx| <TransactionReference as Into<PriorityTransaction>>::into(tx.0)),
>         );
> ```

When a struct implements `Copy`, `extend` can receive by ref and by value. So now, due to ambiguity, I need to tell the compiler which conversion to use.

I choose by value as it is more efficient for small structs.



_Code quote:_
```XML
        self.priority_queue.extend(
            txs_over_threshold
                .map(|tx| <TransactionReference as Into<PriorityTransaction>>::into(tx.0)),
        );
```

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/839)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/839)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/839#-:-O72v-dLBg0HpsGcjtjF:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

**Review by ayeletstarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/839)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/839)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/839#-O736o2WAOzNO1eSjZFq:-O736o2WAOzNO1eSjZFr:bqlfy6w) (no related file):*
Same Q as last PR (please make sure you write this information to the reviewer preemtively): are all redundant `clone()`s gone?

___
___
*[`crates/mempool/src/transaction_queue.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/839#-O7-6Zsm7TABESkkkWFF:-O737D-X7Ggxl4q1zK_N:b7fzwt4) ([raw file](https://github.com/starkware-libs/sequencer/blob/e47b9bf17095208c5ab3b1ad13e52781a189ca9e/crates/mempool/src/transaction_queue.rs#L120)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

When a struct implements `Copy`, `extend` can receive by ref and by value. So now, due to ambiguity, I need to tell the compiler which conversion to use.

I choose by value as it is more efficient for small structs.
</blockquote></details>

Not sure I understand. Please explain differently?
___
*[`crates/mempool/src/transaction_queue.rs` line 133 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/839#-O737-bcD4evKfjAlLkp:-O737-bcD4evKfjAlLkq:bb76mu4) ([raw file](https://github.com/starkware-libs/sequencer/blob/80cef7c1ab6f2d61f2385001afb1e7fdffdc9fac/crates/mempool/src/transaction_queue.rs#L133)):*
> ```XML
>             self.priority_queue.remove(tx);
>         }
>         self.pending_queue.extend(to_remove.into_iter().map(|tx| tx.0.into()));
> ```

Why?



_Code quote:_
```XML
into_iter
```
___
*[`crates/mempool/src/transaction_queue.rs` line 133 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/839#-O7372BH3gebnwBxZX4_:-O7372BH3gebnwBxZX4a:b8lxmk6) ([raw file](https://github.com/starkware-libs/sequencer/blob/832041397d28badb711a31f2da8d04e542aa9eae/crates/mempool/src/transaction_queue.rs#L133)):*
> ```XML
>             self.priority_queue.remove(tx);
>         }
>         self.pending_queue.extend(txs_to_remove.iter().map(|tx| PendingTransaction::from(tx.0)));
> ```

Why not `into()`?



_Code quote:_
```XML
PendingTransaction::from(tx.0)
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/839)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/839#-O736o2WAOzNO1eSjZFq:-O74aO2s6VsvIUdiEEpE:b-4isrll) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

If Clippy is green, so this means that we do not have redundant `clone()`s.
</blockquote></details>

How come? You can still call `clone()` on `Copy` object, can't you?

___
___
*[`crates/mempool/src/transaction_queue.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/839#-O7-6Zsm7TABESkkkWFF:-O74afw916GZc8vd5xU-:bqsxpbb) ([raw file](https://github.com/starkware-libs/sequencer/blob/e47b9bf17095208c5ab3b1ad13e52781a189ca9e/crates/mempool/src/transaction_queue.rs#L120)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

`into()` is used to convert a value into the expected type based on the context. 
In this case, we're using the `extend` method on a `priority_queue` (which is a `BTreeSet`). The `extend` method has two implementations: one that takes a reference and another that takes ownership of the value. 
Therefore, I need to specify which `into()` conversion the compiler should apply.
</blockquote></details>

So it doesn't compile with `into()`?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/839)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/839#-O736o2WAOzNO1eSjZFq:-O74n5sF24cL_6c760kJ:b-2v9ip9) (no related file):*
He means that clippy has a warning against using clone when Copy is implemented.

> If Clippy is green, so this means that we do not have redundant `clone()`s.

Absolutely not. Clippy is primarily static analysis, and as such is never complete, in particular in the presence of code generation, like rust, which has macros, inside which clippy's performance is indeed sketchy at best.

Remove the Clone derive and check if it passes compilation.

___

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/839)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/839#-O7-6Zsm7TABESkkkWFF:-O783vzn9swNG5BHcPIk:boy6u3b) ([raw file](https://github.com/starkware-libs/sequencer/blob/e47b9bf17095208c5ab3b1ad13e52781a189ca9e/crates/mempool/src/transaction_queue.rs#L120)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

So it doesn't compile with `into()`?
</blockquote></details>

Correct.
Error:



_Code snippet:_
```XML
    = note: multiple `impl`s satisfying `BTreeSet<PriorityTransaction>: Extend<_>` found in the `alloc` crate:
            - impl<'a, T, A> Extend<&'a T> for BTreeSet<T, A>
              where T: 'a, T: Ord, T: std::marker::Copy, A: Allocator, A: Clone;
            - impl<T, A> Extend<T> for BTreeSet<T, A>
              where T: Ord, A: Allocator, A: Clone;
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/839)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/839#-O736o2WAOzNO1eSjZFq:-O78Es9h-LYC00rtA8bz:btwll6i) (no related file):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

He means that clippy has a warning against using clone when Copy is implemented.

> If Clippy is green, so this means that we do not have redundant `clone()`s.

Absolutely not. Clippy is primarily static analysis, and as such is never complete, in particular in the presence of code generation, like rust, which has macros, inside which clippy's performance is indeed sketchy at best.

Remove the Clone derive and check if it passes compilation.
</blockquote></details>

Oh wait, you mentioned about the supertrait so it can't be removed, a manual search is necessary then.

___

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/839)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/839#-O736o2WAOzNO1eSjZFq:-O78FMK-4Hi8PFoUcjqS:b-gik2jh) (no related file):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Oh wait, you mentioned about the supertrait so it can't be removed, a manual search is necessary then.
</blockquote></details>

But when I have `Clone`, I get this error in Clippy:



_Code snippet:_
```
error: using `clone` on type `PriorityTransaction` which implements the `Copy` trait
```

___

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/839)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/839#-O736o2WAOzNO1eSjZFq:-O78F_qI2APsv56qh9sR:b-5rtruz) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

But when I have `Clone`, I get this error in Clippy:
</blockquote></details>

Also, both `PriorityTransaction` and `PendingTransaction` are private structs, only used in the `transaction_queue.rs` file. 
I manually searched through the file, and confirmed that there are no remaining clones.

___

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/839)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/839#-O7-6Zsm7TABESkkkWFF:-O78I4yrC-B3UH5UBw7d:blgfyhr) ([raw file](https://github.com/starkware-libs/sequencer/blob/e47b9bf17095208c5ab3b1ad13e52781a189ca9e/crates/mempool/src/transaction_queue.rs#L120)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Correct.
Error:
</blockquote></details>

That's a note, not an error.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/839)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/transaction_queue.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/839#-O7-6Zsm7TABESkkkWFF:-O78J03JDeKTLZo919lS:b-cwrqll) ([raw file](https://github.com/starkware-libs/sequencer/blob/e47b9bf17095208c5ab3b1ad13e52781a189ca9e/crates/mempool/src/transaction_queue.rs#L120)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

That's a note, not an error.
</blockquote></details>

Full error message:



_Code snippet:_
```XML
error[E0283]: type annotations needed
   --> crates/mempool/src/transaction_queue.rs:117:69
    |
117 |         self.priority_queue.extend(txs_over_threshold.map(|tx| tx.0.into()));
    |                             ------ type must be known at this point ^^^^
    |
    = note: multiple `impl`s satisfying `BTreeSet<PriorityTransaction>: Extend<_>` found in the `alloc` crate:
            - impl<'a, T, A> Extend<&'a T> for BTreeSet<T, A>
              where T: 'a, T: Ord, T: std::marker::Copy, A: Allocator, A: Clone;
            - impl<T, A> Extend<T> for BTreeSet<T, A>
              where T: Ord, A: Allocator, A: Clone;
help: try using a fully qualified path to specify the expected types
    |
117 |         self.priority_queue.extend(txs_over_threshold.map(|tx| <TransactionReference as Into<T>>::into(tx.0)));
    |                                                                ++++++++++++++++++++++++++++++++++++++++    ~
```

**Pull request merged**
