### PR TITLE
feat: implement non-published verification

### PR DESCRIPTION
**Pull request by nadin-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/894)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/894)* status: all files reviewed, 5 unresolved discussions (waiting on @nadin-Starkware)

___
*[`scripts/publish_crates.py` line 7 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/894#-O79he1C0wWnCzeslkEF:-O79he1C0wWnCzeslkEG:blwhf60) ([raw file](https://github.com/starkware-libs/sequencer/blob/3eb3dd7e7767da200589991145384a2177e07425/scripts/publish_crates.py#L7)):*
> ```Python
> 
> 
> def check_crate_version_exists(crate_name: str, version: str) -> bool:
> ```

you are returning a boolean, I think this is a better name in that case



_Suggestion:_
```Python
crate_version_exists
```
___
*[`scripts/publish_crates.py` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/894#-O79gtNDDaxi8WLiWlqD:-O79gtNDDaxi8WLiWlqE:b-aryzid) ([raw file](https://github.com/starkware-libs/sequencer/blob/3eb3dd7e7767da200589991145384a2177e07425/scripts/publish_crates.py#L15)):*
> ```Python
>     )
> 
>     if version in response.stdout:
> ```

is this check robust? what is the format of the output of the `api/v1` query?



_Code quote:_
```Python
if version in response.stdout:
```
___
*[`scripts/publish_crates.py` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/894#-O79h0-Y2JrY3dfPkefL:-O79h0-Y2JrY3dfPkefM:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/3eb3dd7e7767da200589991145384a2177e07425/scripts/publish_crates.py#L20)):*
> ```Python
>     else:
>         print(f"Crate {crate_name} version {version} does not exist on crates.io")
>         return False
> ```





_Suggestion:_
```Python
    already_published = version in response.stdout:
    print(f"Crate {crate_name} version {version} {'exists' if already_published else 'does not exist'} on crates.io")
    return already_published
```
___
*[`scripts/publish_crates.py` line 23 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/894#-O79hT3c48hPm_l88-5K:-O79hT3c48hPm_l88-5L:b-hgg1ij) ([raw file](https://github.com/starkware-libs/sequencer/blob/3eb3dd7e7767da200589991145384a2177e07425/scripts/publish_crates.py#L23)):*
> ```Python
> 
> 
> def get_workspace_version(cargo_toml_path) -> str:
> ```

no need for this as input, the point of truth is always the workspace cargo.toml



_Code quote:_
```Python
cargo_toml_path
```
___
*[`scripts/publish_crates.py` line 32 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/894#-O79hKUd9YQlUdJ-LrSB:-O79hKUd9YQlUdJ-LrSC:b8csuaj) ([raw file](https://github.com/starkware-libs/sequencer/blob/3eb3dd7e7767da200589991145384a2177e07425/scripts/publish_crates.py#L32)):*
> ```Python
> 
> 
> def verify_unpublished(crates: List[str], version: Optional[str] = None):
> ```

why is this parameter needed?
 I think you can delete it, we will only ever want to use the workspace-defined version, right?



_Code quote:_
```Python
, version: Optional[str] = None
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/894)* status: all files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

___
*[`scripts/publish_crates.py` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/894#-O79gtNDDaxi8WLiWlqD:-O79pssfAUm9isDwF6bv:b-9wdnf1) ([raw file](https://github.com/starkware-libs/sequencer/blob/3eb3dd7e7767da200589991145384a2177e07425/scripts/publish_crates.py#L15)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

You can see here an example:
https://crates.io/api/v1/crates/starknet_api

I changed it to be more robust :)
</blockquote></details>

Why not JSON deserialize the response, and find the version explicitly in the `versions` list?
___
*[`scripts/publish_crates.py` line 39 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/894#-O79q5tu3nQ_pbwYu9UL:-O79q5tu3nQ_pbwYu9UM:b-x99pkv) ([raw file](https://github.com/starkware-libs/sequencer/blob/6ed66007d58034b27c5ee0865385d3904dfce417/scripts/publish_crates.py#L39)):*
> ```Python
>     version = get_workspace_version()
>     for crate in crates:
>         assert not crate_version_exists(crate_name=crate, version=version)
> ```

please collect the already published crates (probably using `asyncio.gather` is a good idea, these are HTTP calls),
and print all the already-published crates at once



_Code quote:_
```Python
    for crate in crates:
        assert not crate_version_exists(crate_name=crate, version=version)
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/894)* status: all files reviewed, 3 unresolved discussions (waiting on @nadin-Starkware)

___
*[`scripts/publish_crates.py` line 45 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/894#-O7O9EPx4QUjOaIHsauT:-O7O9EPx4QUjOaIHsauU:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/89063e0dfbf6f5c83ea6816fabfc88e0fd8a9caa/scripts/publish_crates.py#L45)):*
> ```Python
>     ]
> 
>     assert not already_published, f"Crates {already_published} have already been published"
> ```





_Suggestion:_
```Python
f"Crates {already_published} have already been published with {version=}."
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/894)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`scripts/publish_crates.py` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/894#-O79gtNDDaxi8WLiWlqD:-O79uULy7j0JVzdTIV87:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3eb3dd7e7767da200589991145384a2177e07425/scripts/publish_crates.py#L15)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Why not JSON deserialize the response, and find the version explicitly in the `versions` list?
</blockquote></details>

Done.
___
*[`scripts/publish_crates.py` line 39 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/894#-O79q5tu3nQ_pbwYu9UL:-O7OBKGL9u-GUCuYxvP3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6ed66007d58034b27c5ee0865385d3904dfce417/scripts/publish_crates.py#L39)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please collect the already published crates (probably using `asyncio.gather` is a good idea, these are HTTP calls),
and print all the already-published crates at once
</blockquote></details>

Done.
___
*[`scripts/publish_crates.py` line 45 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/894#-O7O9EPx4QUjOaIHsauT:-O7OBglJ1mG0VcLaA3Tc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/89063e0dfbf6f5c83ea6816fabfc88e0fd8a9caa/scripts/publish_crates.py#L45)):*
> ```Python
>     ]
> 
>     assert not already_published, f"Crates {already_published} have already been published"
> ```

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/894)* status: all files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`scripts/publish_crates.py` line 39 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/894#-O79q5tu3nQ_pbwYu9UL:-O7OktsK8oeD0VsQIdVu:bpz8vfl) ([raw file](https://github.com/starkware-libs/sequencer/blob/6ed66007d58034b27c5ee0865385d3904dfce417/scripts/publish_crates.py#L39)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

where? the list comprehension is still sequential

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/894)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`scripts/publish_crates.py` line 39 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/894#-O79q5tu3nQ_pbwYu9UL:-O7TCRL6-MHgsfS-5280:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6ed66007d58034b27c5ee0865385d3904dfce417/scripts/publish_crates.py#L39)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where? the list comprehension is still sequential
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/894)* status: all files reviewed, 3 unresolved discussions (waiting on @nadin-Starkware)

___
*[`scripts/publish_crates.py` line 9 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/894#-O7TzGlmAetkcHcA1-7E:-O7TzGlmAetkcHcA1-7F:b-89apy) ([raw file](https://github.com/starkware-libs/sequencer/blob/6e0afa479257ebdc7b951725e4acd9e658956e56/scripts/publish_crates.py#L9)):*
> ```Python
> 
> 
> async def crate_version_exists(crate_name: str, version: str) -> Tuple[str, bool]:
> ```

see below - no need for crate name in return value



_Suggestion:_
```Python
 bool
```
___
*[`scripts/publish_crates.py` line 45 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/894#-O7TzBQm4Bu7bzakHtWn:-O7TzBQm4Bu7bzakHtWo:byr4ffv) ([raw file](https://github.com/starkware-libs/sequencer/blob/6e0afa479257ebdc7b951725e4acd9e658956e56/scripts/publish_crates.py#L45)):*
> ```Python
>     results = await asyncio.gather(*tasks)
> 
>     already_published = [crate for crate, unpublished in results if unpublished]
> ```

see above



_Suggestion:_
```Python
    tasks = [crate_version_exists(crate_name=crate, version=version) for crate in crates]
    results = await asyncio.gather(*tasks)

    already_published = [crate for crate, unpublished in zip(crates, results) if unpublished]
```
___
*[`scripts/publish_crates.py` line 114 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/894#-O7TzS8wDWgx6wrWmHLV:-O7TzS8wDWgx6wrWmHLW:b-3089rc) ([raw file](https://github.com/starkware-libs/sequencer/blob/6e0afa479257ebdc7b951725e4acd9e658956e56/scripts/publish_crates.py#L114)):*
> ```Python
> 
> if __name__ == "__main__":
>     main()
> ```

move the asyncio.run to the main area, and wrap with sys.exit to propagate the return code



_Suggestion:_
```Python
async def publish_crate_and_dependencies(crate: str, dry_run: bool):
    dependencies = get_package_and_dependencies_in_order(crate=crate)
    assert crate == dependencies[-1], f"{crate} should be the last element of '{dependencies}'."

    # Do not attempt to publish anything if even one of the dependencies is already published.
    await verify_unpublished(crates=dependencies)

    base_command_template = "cargo publish -p {crate}" + f"{' --dry-run' if dry_run else ''}"
    # Publish order is important.
    cmd = " && ".join(
        [base_command_template.format(crate=dependency) for dependency in dependencies]
    )

    print(f"Publishing {crate} ({dry_run=}) and its dependencies: {dependencies}...")
    print(cmd, flush=True)
    subprocess.run(cmd, check=True, shell=True)
    print(f"Done.")


async def main():
    parser = argparse.ArgumentParser(
        description="Publish a crate and it's dependencies in the local workspace."
    )
    parser.add_argument(
        "--crate", type=str, help="Crate to publish (dependencies will also be published)."
    )
    parser.add_argument("--dry_run", required=False, action="store_true", help="Dry run.")
    args = parser.parse_args()

    await publish_crate_and_dependencies(crate=args.crate, dry_run=args.dry_run)


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/894)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`scripts/publish_crates.py` line 9 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/894#-O7TzGlmAetkcHcA1-7E:-O7U-1h51MbtRTnja5pq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6e0afa479257ebdc7b951725e4acd9e658956e56/scripts/publish_crates.py#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see below - no need for crate name in return value
</blockquote></details>

Done.
___
*[`scripts/publish_crates.py` line 45 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/894#-O7TzBQm4Bu7bzakHtWn:-O7U-Apb1NWc1e_AGr1T:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6e0afa479257ebdc7b951725e4acd9e658956e56/scripts/publish_crates.py#L45)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.
___
*[`scripts/publish_crates.py` line 114 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/894#-O7TzS8wDWgx6wrWmHLV:-O7U-paO3gOspv-exjgq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6e0afa479257ebdc7b951725e4acd9e658956e56/scripts/publish_crates.py#L114)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move the asyncio.run to the main area, and wrap with sys.exit to propagate the return code
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/894#-:-O7U53qB2NDsxSBI79mC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/894)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Pull request merged**
