### PR TITLE
chore(blockifier): add log for cairo native execution

### PR DESCRIPTION
**Pull request by avivg-starkware**

### CODE REVIEW

**Comment by avivg-starkware** [comment]
* **#2868** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2868?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2868?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2868)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2868#-OEidBqm4BjmX-6E8aUH:-OEidBqn4atgH50L322N:bvxqve4) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c4c2e92031b1cdce67c70a1442de085c0ae204a/crates/blockifier/src/execution/execution_utils.rs#L139)):*
> ```XML
>                 )
>             } else {
>                 log::info!("Using Cairo Native execution.");
> ```

Let's log this at DEBUG level because there will be a lot of these messages and we want to be able to not see them.
+
Let add the block id and transaction hash to the message, so that we know what the message is referring to.



_Suggestion:_
```XML
               log::debug!("Using Cairo Native execution.");
```

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2868)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2868#-OEidBqm4BjmX-6E8aUH:-OEimyW72t3dTLiaK1zj:b-vfdtln) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c4c2e92031b1cdce67c70a1442de085c0ae204a/crates/blockifier/src/execution/execution_utils.rs#L139)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Let's log this at DEBUG level because there will be a lot of these messages and we want to be able to not see them.
+
Let add the block id and transaction hash to the message, so that we know what the message is referring to.
</blockquote></details>

Done. 
Making sure I'm not mistaken- by Block ID, you mean "block_number" ? 



_Code snippet:_
```XML
context.tx_context.block_context.block_info.block_number
```

**Comment by avivg-starkware** [comment]
*[`crates/blockifier/src/execution/execution_utils.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2868#-OEidBqm4BjmX-6E8aUH:-OEivyOnCCVqDHUHmrcI:b-2koddt) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c4c2e92031b1cdce67c70a1442de085c0ae204a/crates/blockifier/src/execution/execution_utils.rs#L139)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Yes. Call it block number in the message instead of block ID to avoid confusion.
</blockquote></details>

Done. thanks!

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2868)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2868#-OEidBqm4BjmX-6E8aUH:-OEk0W7m7lKsun-69ABs:b-7rmg4) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c4c2e92031b1cdce67c70a1442de085c0ae204a/crates/blockifier/src/execution/execution_utils.rs#L139)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

Done. thanks!
</blockquote></details>

Nice. Could you please add the class hash as well? (A transaction can run multiple classes.)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2868)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2868#-OEidBqm4BjmX-6E8aUH:-OEnGkSX7TIe8_agdk_I:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c4c2e92031b1cdce67c70a1442de085c0ae204a/crates/blockifier/src/execution/execution_utils.rs#L139)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Nice. Could you please add the class hash as well? (A transaction can run multiple classes.)
</blockquote></details>

Done.

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2868)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Review by avi-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2868)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2868#-:-OEnRysg3bm-IJHEkW_-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Pull request merged**
