### PR TITLE
feat(blockifier): recompile Cairo1 in the CI

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/197)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/197?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#197** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/197?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#196** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/196?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#195** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/195?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#194** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/194?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#184** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/184?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#183** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/183?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#182** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/182?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#181** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/181?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#180** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/180?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#179** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/179?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by aner-starkware** [comment]
Blocking until a decision is made regarding CI `casm-lang-version` compiler checkout.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/197)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @AvivYossef-starkware, @meship-starkware, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/197#-O3DHR025uYBkJa9s2VC:-O3Dd53I196Y99VTbog2:b-896fix) (no related file):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Blocking until a decision is made regarding CI `casm-lang-version` compiler checkout.
</blockquote></details>

Done.

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/197)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @AvivYossef-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 150 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/197#-O3cAPy792OnwMxlvt7y:-O3cAPy792OnwMxlvt7z:b-g08t2j) ([raw file](https://github.com/starkware-libs/sequencer/blob/60c240b468cd60301d663f64d4167c452037db27/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L150)):*
> ```XML
> 
>     verify_feature_contracts_compatibility(fix_features, contracts_to_test)
> }
> ```

(note to self, blocking):
this entire refactor is redundant. the CI can checkout the legacy tag in the same `cargo test` run as the regular tag, no need for separate runs - 
revert this change + don't run `cargo test` twice in the CI



_Code quote:_
```XML
/// Tests if the env var is set. If a value is provided, also tests that the env var value is equal
/// to the provided value.
fn is_env_var_set(env_var: &str, expected_value: Option<String>) -> bool {
    match std::env::var(env_var) {
        Ok(value) => expected_value.map_or(true, |expected_value| value == expected_value),
        Err(_) => false,
    }
}

#[rstest]
#[ignore]
fn verify_feature_contracts(
    #[values(CairoVersion::Cairo0, CairoVersion::Cairo1)] cairo_version: CairoVersion,
) {
    let fix_features = is_env_var_set("FIX_FEATURE_TEST", None);
    let legacy_mode = is_env_var_set("LEGACY", None);
    let ci_mode = is_env_var_set("CI", Some("true".into()));

    let contracts_to_test = FeatureContract::all_feature_contracts().filter(|contract| {
        // If called with LEGACY environment variable set, only test legacy contracts (from CI
        // or not).
        // If tested from the CI *without* the LEGACY environment variable set, test only
        // non-legacy contracts of the respective cairo version.
        // If not tested from CI, test all contracts of the requested cairo version.
        contract.cairo_version() == cairo_version
            && (if legacy_mode { contract.is_legacy() } else { !ci_mode || !contract.is_legacy() })
    });

    verify_feature_contracts_compatibility(fix_features, contracts_to_test)
}
```

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/197)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware, @AvivYossef-starkware, @dorimedini-starkware, @meship-starkware, and @noaov1)

___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 14 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/197#-O40NTXv-XF1rReK2Tam:-O40NTXv-XF1rReK2Tan:bcvsphs) ([raw file](https://github.com/starkware-libs/sequencer/blob/4993d6cf6707cf3cdcb9bdaecc91ac6c5fbeb6ca/.github/workflows/blockifier_compiled_cairo.yml#L14)):*
> ```YAML
>       - 'crates/blockifier/feature_contracts/**'
>       - 'crates/blockifier/src/test_utils/cairo_compile.rs'
>       - 'crates/blockifier/tests/**'
> ```

Shouldn't this specify the two files currently in the dir instead? (So future files won't trigger this action)



_Code quote:_
```YAML
 'crates/blockifier/tests/**'
```
___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 58 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/197#-O40O2Cr45OmdibgwXt9:-O40O2Cr45OmdibgwXtA:bf4x3d9) ([raw file](https://github.com/starkware-libs/sequencer/blob/4993d6cf6707cf3cdcb9bdaecc91ac6c5fbeb6ca/.github/workflows/blockifier_compiled_cairo.yml#L58)):*
> ```YAML
>         with:
>           repository: 'starkware-libs/cairo'
>           fetch-depth: 0
> ```

By the docs
```
    # Whether to fetch tags, even if fetch-depth > 0.
    # Default: false
    fetch-tags: ''
```
we only need the tags don't we?



_Suggestion:_
```YAML
 fetch-depth: 1
```
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 23 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/197#-O40OWt5AF818XG85VTF:-O40OWt5AF818XG85VTG:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4993d6cf6707cf3cdcb9bdaecc91ac6c5fbeb6ca/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L23)):*
> ```XML
> // Then, run the FIX_COMMAND above.
> 
> // To test Cairo1 feature contracts, first clone the Cairo repo and checkout the required tag.
> ```





_Suggestion:_
```XML
To fix Cairo1
```

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/197#-:-O40e-UP6ObGBiQK9A-_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @AvivYossef-starkware, @meship-starkware, and @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/197)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @AvivYossef-starkware, @meship-starkware, and @noaov1)

___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 58 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/197#-O40O2Cr45OmdibgwXt9:-O40gDRf1H738rRdA3VM:b1wdaqw) ([raw file](https://github.com/starkware-libs/sequencer/blob/4993d6cf6707cf3cdcb9bdaecc91ac6c5fbeb6ca/.github/workflows/blockifier_compiled_cairo.yml#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done. thanks!
</blockquote></details>

[didn't work](https://github.com/starkware-libs/sequencer/actions/runs/10339948162/job/28619937462), reverting

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/197)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @aner-starkware, @AvivYossef-starkware, @meship-starkware, and @noaov1)

___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 58 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/197#-O40O2Cr45OmdibgwXt9:-O40klxp6dbNcdDUjfhk:b-arei5c) ([raw file](https://github.com/starkware-libs/sequencer/blob/4993d6cf6707cf3cdcb9bdaecc91ac6c5fbeb6ca/.github/workflows/blockifier_compiled_cairo.yml#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[didn't work](https://github.com/starkware-libs/sequencer/actions/runs/10339948162/job/28619937462), reverting
</blockquote></details>

OK, [pretty annoying](https://github.com/actions/checkout/issues/1471). Do you wanna try something else or give up?
We can try:
```
- uses: actions/checkout@v4
  with:
    fetch-depth: 0
    filter: object:type=tag
```
(reached to [here](https://github.com/actions/checkout/pull/1396) from the above link)

**Review by TzahiTaub — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/197)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @AvivYossef-starkware, @meship-starkware, and @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/197)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @AvivYossef-starkware, @meship-starkware, @noaov1, and @TzahiTaub)

___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 58 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/197#-O40O2Cr45OmdibgwXt9:-O40yOjW3GHi-S7KEV3e:b-zgcl9g) ([raw file](https://github.com/starkware-libs/sequencer/blob/4993d6cf6707cf3cdcb9bdaecc91ac6c5fbeb6ca/.github/workflows/blockifier_compiled_cairo.yml#L58)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

OK, [pretty annoying](https://github.com/actions/checkout/issues/1471). Do you wanna try something else or give up?
We can try:
```
- uses: actions/checkout@v4
  with:
    fetch-depth: 0
    filter: object:type=tag
```
(reached to [here](https://github.com/actions/checkout/pull/1396) from the above link)
</blockquote></details>

[trying now...](https://github.com/starkware-libs/sequencer/actions/runs/10340717567/job/28621695812)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/197)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @AvivYossef-starkware, @meship-starkware, @noaov1, and @TzahiTaub)

___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 58 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/197#-O40O2Cr45OmdibgwXt9:-O40yxIf048ePFw7mwdP:bxyq9y9) ([raw file](https://github.com/starkware-libs/sequencer/blob/4993d6cf6707cf3cdcb9bdaecc91ac6c5fbeb6ca/.github/workflows/blockifier_compiled_cairo.yml#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[trying now...](https://github.com/starkware-libs/sequencer/actions/runs/10340717567/job/28621695812)
</blockquote></details>

nope
```
filter 'object:type' not supported
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/197)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @AvivYossef-starkware, @meship-starkware, and @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> Dismissed @aner-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/197)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware, @AvivYossef-starkware, @meship-starkware, and @noaov1)

**Pull request merged**
