### PR TITLE
chore(starknet_batcher): remove redundant mutex and sync

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2351)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2351#-OCnPkRv60Aad2b--bFs:-OCnPkRv60Aad2b--bFt:b-gq1vha) (no related file):*
Why was this necessary in the first place? We're sure we don't need it?

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2351)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @dafnamatsry)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2351#-OCnPkRv60Aad2b--bFs:-OD03Uq96TuB4fR0dpw2:b-21f0sm) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why was this necessary in the first place? We're sure we don't need it?
</blockquote></details>

The only copy of the block_builder is being passed to the spawn_build_block_task. There is no other copy. So the only thread that can call the executor is the one running build_block. since there is only one thread - non need for Mutex.

I couldn't reconstruct the steps leading to having this Mutex , but I assume at some point we had BlockBuilderTrait implementing Send+ Sync, and for Sync you need a Mutex. 
Eventually it needs to implement only Send so no need for the Mutex. 
Send is needed when you pass an object to a thread. Sync is needed if you pass a reference to an object to a thread - meaning multiple threads will be able to access it .

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2351#-:-OD0Wqab3tP0djpenVNN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2351#-OCnPkRv60Aad2b--bFs:-OD0WlgOBBecO-OTTrBb:bcr5s2o) (no related file):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

The only copy of the block_builder is being passed to the spawn_build_block_task. There is no other copy. So the only thread that can call the executor is the one running build_block. since there is only one thread - non need for Mutex.

I couldn't reconstruct the steps leading to having this Mutex , but I assume at some point we had BlockBuilderTrait implementing Send+ Sync, and for Sync you need a Mutex. 
Eventually it needs to implement only Send so no need for the Mutex. 
Send is needed when you pass an object to a thread. Sync is needed if you pass a reference to an object to a thread - meaning multiple threads will be able to access it .
</blockquote></details>

Got it, thanks!

**Review by alonh5 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2351)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Pull request merged**
