### PR TITLE
test(blockifier): parametrize more tests in transactions_test by resource bounds types

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1337)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1337?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1337** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1337?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1330** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1330?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1322** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1322?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1321** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1321?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1314** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1314?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1313** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1313?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1312** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1312?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1311** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1311?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1310** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1310?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1309** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1309?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1308** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1308?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1307** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1307?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1306** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1306?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1337)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1543 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1337#-O9-AUKo7PK06XwWyaMJ:-O9-AUKo7PK06XwWyaMK:bt21hvb) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a86d1fbc9d58c84c7c12c8b11c23377cae5904f/crates/blockifier/src/transaction/transactions_test.rs#L1543)):*
> ```XML
>     // Build expected fee transfer call info.
>     let expected_actual_fee =
>         actual_execution_info.receipt.resources.calculate_tx_fee(block_context, fee_type);
> ```

@Yoni-Starkware I see the resources -> fee computation is no longer just a `calculate_tx_fee` call; should I replicate the fee computation logic here instead?
currently I take the `expected` from the `actual`, doesn't really test resources -> fee computation



_Code quote:_
```XML
    let expected_actual_fee =
        actual_execution_info.receipt.resources.calculate_tx_fee(block_context, fee_type);
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1337)* status: 0 of 1 files reviewed, 2 unresolved discussions

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1717 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1337#-O940AW849Qvfpg2Jz8U:-O940AW849Qvfpg2Jz8V:bw30s1h) ([raw file](https://github.com/starkware-libs/sequencer/blob/3650e6c11cf44e5356f402655fa6f967bdffea93/crates/blockifier/src/transaction/transactions_test.rs#L1717)):*
> ```XML
> 
>     // Build expected fee transfer call info.
>     let expected_actual_fee = actual_execution_info.receipt.fee;
> ```

@Yoni-Starkware same question



_Code quote:_
```XML
let expected_actual_fee = actual_execution_info.receipt.fee;
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1337)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1543 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1337#-O9-AUKo7PK06XwWyaMJ:-O997cfm00A8U7YoLTaT:b1muqri) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a86d1fbc9d58c84c7c12c8b11c23377cae5904f/crates/blockifier/src/transaction/transactions_test.rs#L1543)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@Yoni-Starkware I see the resources -> fee computation is no longer just a `calculate_tx_fee` call; should I replicate the fee computation logic here instead?
currently I take the `expected` from the `actual`, doesn't really test resources -> fee computation
</blockquote></details>

It's okay, just make sure the fee is unit-tested somewhere else.
What is the "goal" of this test?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1532 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1337#-O998RHbD-xxG5bO3aCo:-O998RHbD-xxG5bO3aCp:b-9kvorg) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9cf412ce62ac0dc8d10d69ac515ff07ba0c1897/crates/blockifier/src/transaction/transactions_test.rs#L1532)):*
> ```XML
>     let tx_context = &block_context.to_tx_context(&account_tx);
>     let actual_execution_info = account_tx.execute(state, block_context, true, true).unwrap();
>     assert_eq!(actual_execution_info.revert_error, None);
> ```

Is there some `is_reverted` func?



_Code quote:_
```XML
assert_eq!(actual_execution_info.revert_error, None);
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1337)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1543 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1337#-O9-AUKo7PK06XwWyaMJ:-O99ElJ2B2gldh8eHVdY:b-6lykr4) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a86d1fbc9d58c84c7c12c8b11c23377cae5904f/crates/blockifier/src/transaction/transactions_test.rs#L1543)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

It's okay, just make sure the fee is unit-tested somewhere else.
What is the "goal" of this test?
</blockquote></details>

regression test for expected result of a declare (inferring this from the test contents - I didn't write it)
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1532 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1337#-O998RHbD-xxG5bO3aCo:-O99EVE-3dQYVJzUW8YT:b4lq72y) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9cf412ce62ac0dc8d10d69ac515ff07ba0c1897/crates/blockifier/src/transaction/transactions_test.rs#L1532)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Is there some `is_reverted` func?
</blockquote></details>

yes but with `assert_eq`, the error text will be output to console on failure.
I can `assert!(actual_execution_info.is_reverted())` but failures aren't informative

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1337)* status: 0 of 1 files reviewed, all discussions resolved

**Review by yoavGrs — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1337)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2209 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1337#-OAlkIyGE2gjFhn16Ony:-OAlkIyGE2gjFhn16Onz:bcxq8cs) ([raw file](https://github.com/starkware-libs/sequencer/blob/11153e139091cd7835028404762c8ae5fe03d2cd/crates/blockifier/src/transaction/transactions_test.rs#L2209)):*
> ```XML
> 
>     let tx_execution_info = account_tx.execute(state, block_context, true, true).unwrap();
>     assert_eq!(tx_execution_info.revert_error, None);
> ```

I prefer the previous version. Non blocking



_Code quote:_
```XML
 assert_eq!(tx_execution_info.revert_error, None);
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1337)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @yoavGrs)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2209 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1337#-OAlkIyGE2gjFhn16Ony:-OAlkvy8-L3XlPfi4B4X:b-oa681o) ([raw file](https://github.com/starkware-libs/sequencer/blob/11153e139091cd7835028404762c8ae5fe03d2cd/crates/blockifier/src/transaction/transactions_test.rs#L2209)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

I prefer the previous version. Non blocking
</blockquote></details>

this change makes the failure informative (you get the revert error contents printed to console is the tx is reverted)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1337)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
