### PR TITLE
test(mempool): test account nonces removal in get txs

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/759)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/759)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 878 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/759#-O6p9VQw6_NaLTL0qfuy:-O6p9VQx5Q3KVhJqFoTj:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/85c8f6101e61bed3f10fe77e8b7a470b72c9e95b/crates/mempool/src/mempool_test.rs#L878)):*
> ```XML
> 
>     // Assert: account is not added to the mempool.
>     let expected_mempool_content = MempoolContent::with_account_nonces(vec![]);
> ```





_Suggestion:_
```XML
[]
```
___
*[`crates/mempool/src/mempool_test.rs` line 888 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/759#-O6pABSL57zkd6YJIygP:-O6pABSM0e0aJYpquOBX:b-ds0r80) ([raw file](https://github.com/starkware-libs/sequencer/blob/85c8f6101e61bed3f10fe77e8b7a470b72c9e95b/crates/mempool/src/mempool_test.rs#L888)):*
> ```XML
>     let account_nonces = [(input.account.sender_address, input.account.state.nonce)];
>     let queue_txs = [TransactionReference::new(&input.tx)];
>     let pool_txs = [input.tx];
> ```

Do you need to init the pool?



_Code quote:_
```XML
let pool_txs = [input.tx];
```
___
*[`crates/mempool/src/mempool_test.rs` line 897 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/759#-O6pA3sQ5vmq2APP94rL:-O6pA3sQ5vmq2APP94rM:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/85c8f6101e61bed3f10fe77e8b7a470b72c9e95b/crates/mempool/src/mempool_test.rs#L897)):*
> ```XML
> 
>     // Assert: account is removed from account nonces.
>     let expected_mempool_content = MempoolContent::with_account_nonces(vec![]);
> ```





_Suggestion:_
```XML
[]
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/759)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 888 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/759#-O6pABSL57zkd6YJIygP:-O6pNZZtB1xp29hNr09k:by62p11) ([raw file](https://github.com/starkware-libs/sequencer/blob/85c8f6101e61bed3f10fe77e8b7a470b72c9e95b/crates/mempool/src/mempool_test.rs#L888)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Do you need to init the pool?
</blockquote></details>

Yes, in `get_txs`, we remove transactions from the pool, and if an account has no remaining transactions, we also remove it from the account nonces.

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/759#-:-O6uQGvk93BNWMo0L2lp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/759)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/759#-O6yhXcY5MrZ5LwR3WVE:-O6yhXcY5MrZ5LwR3WVF:bcn1hds) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a1c0b548973cc868c2bdfe59ac9caf8068b50bc/crates/mempool/src/mempool_test.rs#L29)):*
> ```XML
> /// Enables customized (and potentially inconsistent) creation for unit testing.
> // TODO(Ayelet): Consider adding a `MempoolContentBuilder` for more flexibility, instead of multiple
> // `with_x_and_y` methods.
> ```

I think now is the time. 

If the test below is indeed necessary and the new `with` constructor is needed, then do the builder first.



_Code quote:_
```XML
// TODO(Ayelet): Consider adding a `MempoolContentBuilder` for more flexibility, instead of multiple
// `with_x_and_y` methods.
```
___
*[`crates/mempool/src/mempool_test.rs` line 883 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/759#-O6yhG_4E1qBrD4uO2b3:-O6yhG_4E1qBrD4uO2b4:b-n6a0gq) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a1c0b548973cc868c2bdfe59ac9caf8068b50bc/crates/mempool/src/mempool_test.rs#L883)):*
> ```XML
> 
> #[rstest]
> fn test_account_nonces_removal_in_get_txs() {
> ```

Not sure we need to test account_nonces directly, it's an auxiliary DS for an auxiliary DS, is there a way of testing its functionality through unit test of the API?
If there isn't then there's no need to test it.



_Code quote:_
```XML
n test_account_nonces_removal_in_get_txs() {
```

**Pull request closed without merging**
