### PR TITLE
test(blockifier): update test_revert_on_resource_overuse to include new resource bounds

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1314)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1314?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1314** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1314?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1313** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1313?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1312** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1312?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1311** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1311?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1310** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1310?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1309** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1309?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1308** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1308?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1307** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1307?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1306** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1306?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1314?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1314** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1314?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1313** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1313?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1312** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1312?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1311** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1311?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1310** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1310?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1309** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1309?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1308** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1308?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1307** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1307?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1306** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1306?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yoavGrs — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1314)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/feature_contracts/cairo0/test_contract.cairo` line 100 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1314#-OANyDi_1B_ryzl05CtQ:-OANyDia8UkJGY_0AGKk:bl7k3ab) ([raw file](https://github.com/starkware-libs/sequencer/blob/3096d35cf9a77189a1d1b3dead1f52c089c633f2/crates/blockifier/feature_contracts/cairo0/test_contract.cairo#L100)):*
> ```Cairo
>         return ();
>     }
>     send_message(7);
> ```

Why do you need it?



_Code quote:_
```Cairo
send_message(7);
```
___
*[`crates/blockifier/src/transaction/post_execution_test.rs` line 339 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1314#-OANqUzNBQgiNPEbYnyA:-OANqUzNBQgiNPEbYnyB:b-sm22a6) ([raw file](https://github.com/starkware-libs/sequencer/blob/3096d35cf9a77189a1d1b3dead1f52c089c633f2/crates/blockifier/src/transaction/post_execution_test.rs#L339)):*
> ```XML
>     // reverted.
>     let low_max_fee = Fee(execution_info_measure.receipt.fee.0 - 1);
>     let low_bounds = if version != TransactionVersion::THREE {
> ```

For future versions.



_Suggestion:_
```XML
if version < TransactionVersion::THREE
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1314)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/blockifier/feature_contracts/cairo0/test_contract.cairo` line 100 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1314#-OANyDi_1B_ryzl05CtQ:-OASN5so17BtZLIHBEl0:bo0k2sy) ([raw file](https://github.com/starkware-libs/sequencer/blob/e72e877f91f1c76b2a176aecf61b27cccb91d613/crates/blockifier/feature_contracts/cairo0/test_contract.cairo#L100)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Why do you need it?
</blockquote></details>

for the `all_bounds_insufficient_l1_gas` case.
we need something that costs L1 gas even when user is paying for L2 stuff with L2 gas

**Review by yoavGrs — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1314)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
