### PR TITLE
feat(consensus): add CentralStateDiff object in the aerospike format

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
* **#2715** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2715?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2715?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2715)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEJf-jZ9SGahqqXq0jL:-OEJf-jZ9SGahqqXq0jM:b-vvukh6) ([raw file](https://github.com/starkware-libs/sequencer/blob/8eac87be4d69a75db000467e9672e662bac5f400/crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs#L5)):*
> ```XML
> //! Implements the consensus context - the interface for consensus to call out to the node.
> 
> mod central_communication;
> ```

move this module to cende when merged
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/central_communication/central_objects_test.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEJgFgT-duYt0not-EF:-OEJgFgUDIFd212GOjva:b-8r078a) ([raw file](https://github.com/starkware-libs/sequencer/blob/8eac87be4d69a75db000467e9672e662bac5f400/crates/sequencing/papyrus_consensus_orchestrator/src/central_communication/central_objects_test.rs#L73)):*
> ```XML
>     let python_json: Value = serde_json::from_str(&python_json_string).unwrap();
> 
>     assert_eq!(rust_json, python_json,);
> ```

we should compare here string representation of the JSON and not the `JsonValue` object

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2715)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/central_communication/central_objects_test.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEJgFgT-duYt0not-EF:-OEPA8SK-Q4Gg5Sif_Sg:b2dsuye) ([raw file](https://github.com/starkware-libs/sequencer/blob/8eac87be4d69a75db000467e9672e662bac5f400/crates/sequencing/papyrus_consensus_orchestrator/src/central_communication/central_objects_test.rs#L73)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

we should compare here string representation of the JSON and not the `JsonValue` object
</blockquote></details>

The strings are not the same due to spaces and \n chars.
what is the problem with comparing jsonValue?

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2715)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/central_communication/central_objects_test.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEJgFgT-duYt0not-EF:-OESu1nf9vVuKCIZ7TkP:b-oin9j3) ([raw file](https://github.com/starkware-libs/sequencer/blob/8eac87be4d69a75db000467e9672e662bac5f400/crates/sequencing/papyrus_consensus_orchestrator/src/central_communication/central_objects_test.rs#L73)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

The strings are not the same due to spaces and \n chars.
what is the problem with comparing jsonValue?
</blockquote></details>

I prefer to compare strings because this is how we will send and write things, but JsonValue is also good.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/central_communication/central_objects_test.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OESuqq88B0dzswAPLNp:-OESuqq88B0dzswAPLNq:b-w1c8nw) ([raw file](https://github.com/starkware-libs/sequencer/blob/8eac87be4d69a75db000467e9672e662bac5f400/crates/sequencing/papyrus_consensus_orchestrator/src/central_communication/central_objects_test.rs#L65)):*
> ```XML
>     let rust_central_state_diff = central_state_diff();
> 
>     let rust_serialized = serde_json::to_string(&rust_central_state_diff).unwrap();
> ```

Try converting the string to `JsonValue` in one call using this:
`let json_value: Value = serde_json::from_str(my_string)?;`

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2715)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/central_communication/central_objects_test.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OESuqq88B0dzswAPLNp:-OESzHNu5Jm8C9FicHe2:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8eac87be4d69a75db000467e9672e662bac5f400/crates/sequencing/papyrus_consensus_orchestrator/src/central_communication/central_objects_test.rs#L65)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Try converting the string to `JsonValue` in one call using this:
`let json_value: Value = serde_json::from_str(my_string)?;`
</blockquote></details>

Done.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2715)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @DvirYo-starkware and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs` line 15 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEhhmFT4K9W7fCQm2cH:-OEhhmFT4K9W7fCQm2cI:bbrankf) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac2a1f7b60cc268f2f09701667e6f997a7b92fe/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs#L15)):*
> ```XML
> use starknet_api::state::StorageKey;
> use starknet_types_core::felt::Felt;
> ```

Please add a short comment explaining what are these "Central" objects.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2715)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEJf-jZ9SGahqqXq0jL:-OEhqIy11Bj5Z9xitYSe:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8eac87be4d69a75db000467e9672e662bac5f400/crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs#L5)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

move this module to cende when merged
</blockquote></details>

Done.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2715)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs` line 15 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEhhmFT4K9W7fCQm2cH:-OEhsLU_8BQsPxF0utW-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac2a1f7b60cc268f2f09701667e6f997a7b92fe/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs#L15)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please add a short comment explaining what are these "Central" objects.
</blockquote></details>

Done.

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2715)* status: 6 of 8 files reviewed, 7 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 8 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEhpsfq-8koo1IOhqrJ:-OEhpsfq-8koo1IOhqrK:by9tprk) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac2a1f7b60cc268f2f09701667e6f997a7b92fe/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L8)):*
> ```XML
> use tokio::task::{self};
> use tracing::debug;
> ```

Move the module declarations before the imports.
Also, make the `central_objects_test` module inside the `central_objects`
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs` line 81 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEhpRP85ltPtHN6BaCD:-OEhpRP95aJPfmGTvTiL:bd1sfz5) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac2a1f7b60cc268f2f09701667e6f997a7b92fe/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs#L81)):*
> ```XML
>             storage_updates: indexmap!(DataAvailabilityMode::L1=> state_diff.storage_updates),
>             declared_classes: state_diff.class_hash_to_compiled_class_hash,
>             block_info: CentralBlockInfo::from((block_info, starknet_version)),
> ```

consider `into()`
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEhsDlkB7jt4FI2LG9c:-OEhsDlkB7jt4FI2LG9d:be7d49g) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac2a1f7b60cc268f2f09701667e6f997a7b92fe/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L21)):*
> ```XML
> pub const CENTRAL_STATE_DIFF_JSON_PATH: &str = "crates/sequencing/papyrus_consensus_orchestrator/\
>                                                 src/cende/resources/\
>                                                 central_state_diff.json";
> ```

Why not a local path? Is there some convention in the repo?



_Code quote:_
```XML
pub const CENTRAL_STATE_DIFF_JSON_PATH: &str = "crates/sequencing/papyrus_consensus_orchestrator/\
                                                src/cende/resources/\
                                                central_state_diff.json";
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEhqRtM1iRwYIqpNNw9:-OEhqRtM1iRwYIqpNNwA:b-l1q4xh) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac2a1f7b60cc268f2f09701667e6f997a7b92fe/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L68)):*
> ```XML
>         fs::read_to_string(resolve_project_relative_path(CENTRAL_STATE_DIFF_JSON_PATH).unwrap())
>             .unwrap();
>     let python_json: Value = serde_json::from_str(&python_json_string).unwrap();
> ```

I think also here you can convert the path directly to value, something like:
`let python_json=serde_json::to_value(resolve_project_relative_path(CENTRAL_STATE_DIFF_JSON_PATH).unwrap())`



_Code quote:_
```XML
    let python_json_string =
        fs::read_to_string(resolve_project_relative_path(CENTRAL_STATE_DIFF_JSON_PATH).unwrap())
            .unwrap();
    let python_json: Value = serde_json::from_str(&python_json_string).unwrap();
```

**Review by dafnamatsry — COMMENTED** [review]
> Reviewed 1 of 8 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2715)* status: all files reviewed, 5 unresolved discussions (waiting on @DvirYo-starkware and @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2715)* status: all files reviewed, 4 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 8 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEhpsfq-8koo1IOhqrJ:-OEiR6UoA-QjBREotEwm:b-ymuu77) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac2a1f7b60cc268f2f09701667e6f997a7b92fe/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L8)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Move the module declarations before the imports.
Also, make the `central_objects_test` module inside the `central_objects`
</blockquote></details>

changed it to your request, but I gotta say that this is done differently in other crates.
I think someone should come up with a convention regarding this.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs` line 81 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEhpRP85ltPtHN6BaCD:-OEi6Y8W7YxJ93TxaTkG:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac2a1f7b60cc268f2f09701667e6f997a7b92fe/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects.rs#L81)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

consider `into()`
</blockquote></details>

done
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEhsDlkB7jt4FI2LG9c:-OEiPE4JC0A1e91lVMVH:b-pw80k4) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac2a1f7b60cc268f2f09701667e6f997a7b92fe/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L21)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Why not a local path? Is there some convention in the repo?
</blockquote></details>

yes, that is what I see in other places.
I think it 's because we son't want to depend on cargo toolchain paths.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEhqRtM1iRwYIqpNNw9:-OEiQdT0Dc3_tD7AUzfv:bfinfl7) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac2a1f7b60cc268f2f09701667e6f997a7b92fe/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L68)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I think also here you can convert the path directly to value, something like:
`let python_json=serde_json::to_value(resolve_project_relative_path(CENTRAL_STATE_DIFF_JSON_PATH).unwrap())`
</blockquote></details>

what you suggested is converting the path to json.
I changed the code , but I don't think it's better, still 2 operations.

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2715)* status: all files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEhqRtM1iRwYIqpNNw9:-OEiV6H5E9KCuud5xzQf:b-ke9v2m) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac2a1f7b60cc268f2f09701667e6f997a7b92fe/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L68)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

what you suggested is converting the path to json.
I changed the code , but I don't think it's better, still 2 operations.
</blockquote></details>

Return this to how it was
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 25 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEnIWL33GjS_fjWkgeK:-OEnIWL33GjS_fjWkgeL:b6nzk0k) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c208a063b07950edcbee9c59fa313453bf2bd4/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L25)):*
> ```XML
> }
> pub const CENTRAL_STATE_DIFF_JSON_PATH: &str =
>     concat!(test_resources_dir!(), "/central_state_diff.json");
> ```

As we talked



_Code quote:_
```XML
macro_rules! test_resources_dir {
    () => {
        "crates/sequencing/papyrus_consensus_orchestrator/src/cende/resources"
    };
}
pub const CENTRAL_STATE_DIFF_JSON_PATH: &str =
    concat!(test_resources_dir!(), "/central_state_diff.json");
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2715)* status: all files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 29 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEnJ-sX434oPT6hkZtb:-OEnJ-sX434oPT6hkZtc:b-buq6hd) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c208a063b07950edcbee9c59fa313453bf2bd4/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L29)):*
> ```XML
> fn central_state_diff() -> CentralStateDiff {
>     CentralStateDiff {
>         address_to_class_hash: indexmap! {
> ```

I also forgot another thing. In this case, it may be simpler to write the object as a JSON string and deserialize it instead of creating the object manually.
Do what you prefer

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2715)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEhqRtM1iRwYIqpNNw9:-OEo7hJw90ns1zBW_exL:buoen30) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac2a1f7b60cc268f2f09701667e6f997a7b92fe/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L68)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Return this to how it was
</blockquote></details>

changing to what we discussed.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 25 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEnIWL33GjS_fjWkgeK:-OEo7fZq-k0L7mLa7Z0o:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c208a063b07950edcbee9c59fa313453bf2bd4/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L25)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

As we talked
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs` line 29 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2715#-OEnJ-sX434oPT6hkZtb:-OEntIkn9gXCuHvq_4yJ:b-4jlkds) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9c208a063b07950edcbee9c59fa313453bf2bd4/crates/sequencing/papyrus_consensus_orchestrator/src/cende/central_objects_test.rs#L29)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I also forgot another thing. In this case, it may be simpler to write the object as a JSON string and deserialize it instead of creating the object manually.
Do what you prefer
</blockquote></details>

as discussed f2f I will convert from the original object using into() and then to json. will do so in a a separate PR.

**Review by DvirYo-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2715)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 3 of 4 files at r7, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2715)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
