### PR TITLE
fix(ci): fix coverage

### PR DESCRIPTION
**Pull request by giladchase**
- nightly isn't a pr, and doesn't need changes-only
- gen coverage of everything.

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2859)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`.github/workflows/main_nightly.yml` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2859#-OEhdBB9EJGKibOJ7ew0:-OEhdBB9EJGKibOJ7ew1:bcmzzen) ([raw file](https://github.com/starkware-libs/sequencer/blob/d1fa34b6ddb3209a7c8b6ce286eaadd5d120c5b3/.github/workflows/main_nightly.yml#L18)):*
> ```YAML
>       - run: npm install -g ganache@7.4.3
>       - name: Install cargo-llvm-cov
>         uses: taiki-e/install-action@cargo-llvm-cov
> ```

shouldn't this be part of the moonrepo action?



_Code quote:_
```YAML
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
```
___
*[`.github/workflows/main_nightly.yml` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2859#-OEhd8Ns-AeSjotKCVNy:-OEhd8Ns-AeSjotKCVNz:b32jlsh) ([raw file](https://github.com/starkware-libs/sequencer/blob/0dd60ea5cee051c070af512f06bda89ce96b4d79/.github/workflows/main_nightly.yml#L55)):*
> ```YAML
>           verbose: true
>           fail_ci_if_error: true
>           version: "v0.1.15"
> ```

wasn't there a reason to fix this version?



_Code quote:_
```YAML
version: "v0.1.15"
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2859)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`.github/workflows/main_nightly.yml` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2859#-OEhdBB9EJGKibOJ7ew0:-OEiKImX9ZyTab8Ng4oW:bvblfbt) ([raw file](https://github.com/starkware-libs/sequencer/blob/d1fa34b6ddb3209a7c8b6ce286eaadd5d120c5b3/.github/workflows/main_nightly.yml#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

shouldn't this be part of the moonrepo action?
</blockquote></details>

Not really, this is only useful for coverage, which runs on a nightly, but if we add it to moonrepo it'll be installed on every PR.
Ya it'll get cached, but still it'll add a few seconds of overhead which won't be beneficial for any PR.
And conversly, this is a nightly job, so cache isn't important for it anyway.
___
*[`.github/workflows/main_nightly.yml` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2859#-OEhd8Ns-AeSjotKCVNy:-OEiKxXb37Wr25sLSMPJ:b3gva30) ([raw file](https://github.com/starkware-libs/sequencer/blob/0dd60ea5cee051c070af512f06bda89ce96b4d79/.github/workflows/main_nightly.yml#L55)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

wasn't there a reason to fix this version?
</blockquote></details>

This was added to papyrus [almost two years ago](https://github.com/starkware-libs/papyrus/commit/fdeeac3e819ec12f1e721e6f058b480587e21c5e/) to (try to) fix the codecov 404 error, which has been solved since then (we stopped getting it in the mempool before the monorepo, which didn't use this version)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2859#-:-OEiSc-qBcsEK9zsDcbT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
Also removed coverage from runtests, it only runs from from nightly and doesn't need changes only

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2859#-:-OEjrO3o5Ee-S_I2-E7S:bsfznf8)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2859)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
