### PR TITLE
refactor(consensus): fix linter warning from the simulation network receiver

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/288)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/288?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#289** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/289?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#288** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/288?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#287** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/287?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/288)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/288#-O3DHc_kDIv_W6GpX0Ok:-O3DHc_kDIv_W6GpX0Ol:bmzr4gx) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf7dfe943a2bfda60f48f32e853c61c7c5fbcbf1/crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs#L54)):*
> ```XML
>     ) -> Self {
>         assert!((0.0..=1.0).contains(&drop_probability));
>         assert!((0.0..=1.0).contains(&invalid_probability));
> ```

what is this syntax? you are iterating over א values??



_Code quote:_
```XML
        assert!((0.0..=1.0).contains(&drop_probability));
        assert!((0.0..=1.0).contains(&invalid_probability));
```

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/288)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @dorimedini-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/288#-O3DHc_kDIv_W6GpX0Ok:-O3DL1iH3d6Hv3drwmwn:b-u5twc6) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf7dfe943a2bfda60f48f32e853c61c7c5fbcbf1/crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs#L54)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what is this syntax? you are iterating over א values??
</blockquote></details>

This syntax is what clippy says I should do. Technically it is an inclusive range

https://doc.rust-lang.org/std/ops/struct.RangeInclusive.html

**Review by dorimedini-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/288#-:-O3DMaM7DIZO5wEiHFBY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/288#-:-O3SJnRX5UzR_GiPqCsR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Comment by matan-starkware** [comment]
### Merge activity

* **Aug 4, 8:19 AM EDT**: @matan-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/288).

**Pull request merged**
