### PR TITLE
refactor(starknet_sequencer_node): refactor run_component_servers

### PR DESCRIPTION
**Pull request by lev-starkware**
commit-id:a5dad3d5

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2792)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/papyrus_proc_macros/src/lib.rs` line 377 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-OEQJzcG4CmLSQzxB3h_:-OEQJzcG4CmLSQzxB3ha:bxcrf7z) ([raw file](https://github.com/starkware-libs/sequencer/blob/6bdeae09245f88f4aaa8c999b16f4c4995276375/crates/papyrus_proc_macros/src/lib.rs#L377)):*
> ```XML
> 
>     TokenStream::from(expanded)
> }
> ```

We're trying to avoid using macros and specifically proc macros unless it is absolutely necessary. We discussed an alternative solution in person, what was wrong with that?



_Code quote:_
```XML
/// This macro generates a code that spawns all the servers and waits in tokio::select! for them.
/// macro gets as input an array of tuples, where each tuple contains the handle to the server and
/// a server name to be logged in case the server stops.
///
/// # Example
///
/// ```rust,ignore
/// use papyrus_proc_macros::run_servers;
/// use tokio;
/// use starknet_sequencer_node::servers::get_server_future;
///
/// pub async fn run_component_servers(servers: SequencerNodeServers) -> anyhow::Result<()> {
///     let result = run_servers!([
///         (servers.local_servers.batcher, "Local Batcher"),
///         (servers.remote_servers.batcher, "Remote Batcher"),
///     ]);
///
///     Ok(result?)
/// }
/// ```
#[proc_macro]
pub fn run_servers(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as ExprArray);
    let handles = input.elems;

    let mut select_cases = quote! {};
    for handle in handles.iter() {
        if let Expr::Tuple(tuple) = handle {
            let handle_expr = &tuple.elems[0];
            let message = &tuple.elems[1];
            if let Expr::Lit(expr_lit) = message {
                if let syn::Lit::Str(lit_str) = &expr_lit.lit {
                    select_cases = quote! {
                        #select_cases
                        res = tokio::spawn(get_server_future(#handle_expr)) => {
                            error!("{} Server stopped.", #lit_str);
                            res?
                        },
                    };
                }
            }
        }
    }

    let expanded = quote! {
        tokio::select! {
            #select_cases
        }
    };

    TokenStream::from(expanded)
}
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2792)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/starknet_sequencer_node/src/servers.rs` line 384 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-OEQKQGh0aFShMH28U2X:-OEQKQGh0aFShMH28U2Y:bzbw1oq) ([raw file](https://github.com/starkware-libs/sequencer/blob/6bdeae09245f88f4aaa8c999b16f4c4995276375/crates/starknet_sequencer_node/src/servers.rs#L384)):*
> ```XML
>         (servers.local_servers.l1_provider, "Local L1 Provider"),
>         (servers.remote_servers.l1_provider, "Remote L1 Provider"),
>     ]);
> ```

Indeed packs a lot of the boiler plate code, but this still suffers from the disadvantage of being a very long list of items that can be easily be left out dated.

I'd argue that if we're going for a proc macro here then we don't even need to provide this list: parse the struct, parse its internal structs, generate the code as such.

However, I don't think we need a macro here.



_Code quote:_
```XML
    // Start servers.
    let result = run_servers!([
        (servers.local_servers.batcher, "Local Batcher"),
        (servers.remote_servers.batcher, "Remote Batcher"),
        (servers.wrapper_servers.consensus_manager, "Consensus Manager"),
        (servers.local_servers.gateway, "Local Gateway"),
        (servers.remote_servers.gateway, "Remote Gateway"),
        (servers.wrapper_servers.http_server, "Http"),
        (servers.local_servers.mempool, "Local Mempool"),
        (servers.remote_servers.mempool, "Remote Mempool"),
        (servers.wrapper_servers.monitoring_endpoint, "Monitoring Endpoint"),
        (servers.local_servers.mempool_p2p_propagator, "Local Mempool P2P Propagator"),
        (servers.remote_servers.mempool_p2p_propagator, "Remote Mempool P2P Propagator"),
        (servers.wrapper_servers.mempool_p2p_runner, "Mempool P2P Runner"),
        (servers.local_servers.state_sync, "Local State Sync"),
        (servers.remote_servers.state_sync, "Remote State Sync"),
        (servers.wrapper_servers.state_sync_runner, "State Sync Runner"),
        (servers.local_servers.l1_provider, "Local L1 Provider"),
        (servers.remote_servers.l1_provider, "Remote L1 Provider"),
    ]);
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2792)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/starknet_sequencer_node/src/servers.rs` line 265 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-OEY-BZh8_5_saC-Ye2h:-OEY-BZh8_5_saC-Ye2i:b-3rg4ea) ([raw file](https://github.com/starkware-libs/sequencer/blob/5d5271a83541d4ccc76d62b55eeb8a323d9cac16/crates/starknet_sequencer_node/src/servers.rs#L265)):*
> ```XML
> 
> impl LocalServers {
>     async fn run(self) -> anyhow::Result<()>  {
> ```

Please change to `!`, for all 3 sub-structs and for the composing struct as well.



_Code quote:_
```XML
anyhow::Result<()>
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2792)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sequencer_node/src/servers.rs` line 265 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-OEY-BZh8_5_saC-Ye2h:-OEnw9Ep5OCMtbFRpJ0U:ba2izq3) ([raw file](https://github.com/starkware-libs/sequencer/blob/5d5271a83541d4ccc76d62b55eeb8a323d9cac16/crates/starknet_sequencer_node/src/servers.rs#L265)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to `!`, for all 3 sub-structs and for the composing struct as well.
</blockquote></details>

I already tried it. It gives nothing and behaves like a virus. Also in case of Errors we do receive results.

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2792)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sequencer_node/src/servers.rs` line 265 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-OEY-BZh8_5_saC-Ye2h:-OErd1XMBfj7S_JigbAV:b-fe1l0) ([raw file](https://github.com/starkware-libs/sequencer/blob/5d5271a83541d4ccc76d62b55eeb8a323d9cac16/crates/starknet_sequencer_node/src/servers.rs#L265)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

I already tried it. It gives nothing and behaves like a virus. Also in case of Errors we do receive results.
</blockquote></details>

I changed the function to return JoinSet
___
*[`crates/papyrus_proc_macros/src/lib.rs` line 377 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-OEQJzcG4CmLSQzxB3h_:-OErdQmF6nU59WYSbybS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6bdeae09245f88f4aaa8c999b16f4c4995276375/crates/papyrus_proc_macros/src/lib.rs#L377)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

We're trying to avoid using macros and specifically proc macros unless it is absolutely necessary. We discussed an alternative solution in person, what was wrong with that?
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2792)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/starknet_sequencer_node/src/servers.rs` line 264 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-OErsci4DrQC6Q61jvOf:-OErsci4DrQC6Q61jvOg:bwhme29) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5dc29925b5a4dd59bc2ac6778ed59605e252482/crates/starknet_sequencer_node/src/servers.rs#L264)):*
> ```XML
> }
> 
> pub async fn create_servers_join_set(
> ```

WDYT about `create_servers`?
In general, fn names should not mention the return types.



_Code quote:_
```XML
create_servers_join_set
```
___
*[`crates/starknet_sequencer_node/src/servers.rs` line 265 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-OErsouDEXStBSdr2ciH:-OErsouDEXStBSdr2ciI:b-o9e7e) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5dc29925b5a4dd59bc2ac6778ed59605e252482/crates/starknet_sequencer_node/src/servers.rs#L265)):*
> ```XML
> 
> pub async fn create_servers_join_set(
>     futures_with_strings: Vec<(
> ```

`labeled_futures` ?



_Code quote:_
```XML
futures_with_strings
```
___
*[`crates/starknet_sequencer_node/src/servers.rs` line 266 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-OErzFWb4QP2VbV6EUtU:-OErzFWb4QP2VbV6EUtV:b-db0yse) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5dc29925b5a4dd59bc2ac6778ed59605e252482/crates/starknet_sequencer_node/src/servers.rs#L266)):*
> ```XML
> pub async fn create_servers_join_set(
>     futures_with_strings: Vec<(
>         impl Future<Output = Result<(), ComponentServerError>> + Send + 'static,
> ```

Use a generic return type here.



_Code quote:_
```XML
Result<(), ComponentServerError>
```
___
*[`crates/starknet_sequencer_node/src/servers.rs` line 269 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-OErzMtzDw92dnpnm2eS:-OErzMtzDw92dnpnm2eT:b-db0yse) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5dc29925b5a4dd59bc2ac6778ed59605e252482/crates/starknet_sequencer_node/src/servers.rs#L269)):*
> ```XML
>         String,
>     )>,
> ) -> JoinSet<(Result<(), ComponentServerError>, String)> {
> ```

Use a generic return type here.



_Code quote:_
```XML
Result<(), ComponentServerError>
```
___
*[`crates/starknet_sequencer_node/src/servers.rs` line 458 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-OEs-0No7W33t4JfwZHE:-OEs-0Np71H7oT9aqj48:b-ut6frl) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5dc29925b5a4dd59bc2ac6778ed59605e252482/crates/starknet_sequencer_node/src/servers.rs#L458)):*
> ```XML
>         }
>     };
>     error!("Servers ended unexpectedly.");
> ```

WDYT about

```
    let mut local_servers_future = servers.local_servers.run();
    let mut remote_servers_future = servers.remote_servers.run();
    let mut wrapper_servers_future = servers.wrapper_servers.run();


        create_servers_join_set(vec![
            server_future_and_label(local_servers_future, "Local Servers"),
            server_future_and_label(remote_servers_future, "Remote Servers"),
            server_future_and_label(wrapper_servers_future, "Wrapper Servers"),
        ])
        .await
```

?



_Code quote:_
```XML
    let mut local_servers = servers.local_servers.run().await;
    let mut remote_servers = servers.remote_servers.run().await;
    let mut wrapper_servers = servers.wrapper_servers.run().await;

    let result = tokio::select! {
        res = local_servers.join_next() => {
            get_server_error(res)
        }
        res = remote_servers.join_next() => {
            get_server_error(res)
        }
        res = wrapper_servers.join_next() => {
            get_server_error(res)
        }
    };
    error!("Servers ended unexpectedly.");
```
___
*[`crates/starknet_sequencer_node/Cargo.toml` line 21 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-OErnAKpBqG4Ycxftu6h:-OErnAKpBqG4Ycxftu6i:b-rm5e8d) ([raw file](https://github.com/starkware-libs/sequencer/blob/332004aa33f7ce60772ae7d73eb651fe0dee4f58/crates/starknet_sequencer_node/Cargo.toml#L21)):*
> ```TOML
> infra_utils.workspace = true
> papyrus_config.workspace = true
> papyrus_proc_macros = { workspace = true, optional = true }
> ```

Please change to the `papyrus_proc_macros.workspace = true` syntax for consistency with the other crates.



_Code quote:_
```TOML
papyrus_proc_macros = { workspace = true, optional = true }
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2792)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sequencer_node/Cargo.toml` line 21 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-OErnAKpBqG4Ycxftu6h:-OEsLu1o4L_WZYQ051Zo:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/332004aa33f7ce60772ae7d73eb651fe0dee4f58/crates/starknet_sequencer_node/Cargo.toml#L21)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to the `papyrus_proc_macros.workspace = true` syntax for consistency with the other crates.
</blockquote></details>

Done.
___
*[`crates/starknet_sequencer_node/src/servers.rs` line 264 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-OErsci4DrQC6Q61jvOf:-OEsMpAU63uxPPhNmArz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5dc29925b5a4dd59bc2ac6778ed59605e252482/crates/starknet_sequencer_node/src/servers.rs#L264)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

WDYT about `create_servers`?
In general, fn names should not mention the return types.
</blockquote></details>

Done.
___
*[`crates/starknet_sequencer_node/src/servers.rs` line 265 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-OErsouDEXStBSdr2ciH:-OEsN51XE9SBqX1uegaW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5dc29925b5a4dd59bc2ac6778ed59605e252482/crates/starknet_sequencer_node/src/servers.rs#L265)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

`labeled_futures` ?
</blockquote></details>

Done.
___
*[`crates/starknet_sequencer_node/src/servers.rs` line 266 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-OErzFWb4QP2VbV6EUtU:-OEsR7aE1LuVBMPvQ7sU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5dc29925b5a4dd59bc2ac6778ed59605e252482/crates/starknet_sequencer_node/src/servers.rs#L266)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Use a generic return type here.
</blockquote></details>

Done.
___
*[`crates/starknet_sequencer_node/src/servers.rs` line 269 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-OErzMtzDw92dnpnm2eS:-OEsR9hr8C-vwBKDSFGj:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5dc29925b5a4dd59bc2ac6778ed59605e252482/crates/starknet_sequencer_node/src/servers.rs#L269)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Use a generic return type here.
</blockquote></details>

Done.
___
*[`crates/starknet_sequencer_node/src/servers.rs` line 458 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-OEs-0No7W33t4JfwZHE:-OEtTKpy52k5A6DaIJTD:biwt1lz) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5dc29925b5a4dd59bc2ac6778ed59605e252482/crates/starknet_sequencer_node/src/servers.rs#L458)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

WDYT about

```
    let mut local_servers_future = servers.local_servers.run();
    let mut remote_servers_future = servers.remote_servers.run();
    let mut wrapper_servers_future = servers.wrapper_servers.run();


        create_servers_join_set(vec![
            server_future_and_label(local_servers_future, "Local Servers"),
            server_future_and_label(remote_servers_future, "Remote Servers"),
            server_future_and_label(wrapper_servers_future, "Wrapper Servers"),
        ])
        .await
```

?
</blockquote></details>

I tried. It can't bring it to work.

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2792)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sequencer_node/src/servers.rs` line 458 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-OEs-0No7W33t4JfwZHE:-OExWndiDkW9RW8o_uwX:b-wtvsj8) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5dc29925b5a4dd59bc2ac6778ed59605e252482/crates/starknet_sequencer_node/src/servers.rs#L458)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

I tried. It can't bring it to work.
</blockquote></details>

Added TODO. Look before tokio::select!

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2792#-:-OExoBiw2WbjNBPiXIoT:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved

**Review by lev-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2792)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Pull request closed without merging**
