### PR TITLE
feat(blockifier): add RunResource to distinguis vm and sierra run

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/787)

### CODE REVIEW

**Comment by TzahiTaub** [comment]
* **#787** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/787?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @TzahiTaub and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/787)* status: 4 of 7 files reviewed, 6 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/versioned_constants.rs` line 94 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/787#-O6tZ0sk-prVenG0EMPh:-O6tZ0sk-prVenG0EMPi:b-hso6jl) ([raw file](https://github.com/starkware-libs/sequencer/blob/23ff0942958387bcba1bedcf8f92808241854dfb/crates/blockifier/src/versioned_constants.rs#L94)):*
> ```XML
>     pub max_recursion_depth: usize,
>     pub validate_max_n_steps: u32,
>     #[serde(default)]
> ```

Remove and fill `"min_compiler_version_for_gas_usage": "2.8.0"` in all version files.
(default is bad here, right?)
___
*[`crates/blockifier/src/versioned_constants.rs` line 95 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/787#-O6tYrDC1C6gDdLZnji5:-O6tYrDC1C6gDdLZnji6:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/23ff0942958387bcba1bedcf8f92808241854dfb/crates/blockifier/src/versioned_constants.rs#L95)):*
> ```XML
>     pub validate_max_n_steps: u32,
>     #[serde(default)]
>     pub min_compiler_version_for_gas_usage: String,
> ```





_Suggestion:_
```XML
    pub min_compiler_version_for_sierra_gas: String,
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 257 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/787#-O6tcN_x767v6pRnuSfg:-O6tcN_x767v6pRnuSfh:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/23ff0942958387bcba1bedcf8f92808241854dfb/crates/blockifier/src/versioned_constants.rs#L257)):*
> ```XML
>     }
> 
>     pub fn get_min_compiler_version_for_gas_usage(&self) -> Version {
> ```





_Suggestion:_
```XML
pub fn get_min_compiler_version_for_sierra_gas(
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 258 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/787#-O6tcJOY7jasSWVtDYDh:-O6tcJOY7jasSWVtDYDi:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/23ff0942958387bcba1bedcf8f92808241854dfb/crates/blockifier/src/versioned_constants.rs#L258)):*
> ```XML
> 
>     pub fn get_min_compiler_version_for_gas_usage(&self) -> Version {
>         Version::parse(&self.min_compiler_version_for_gas_usage).unwrap_or(Version::new(0, 0, 0))
> ```





_Suggestion:_
```XML
.except("..."))
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 248 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/787#-O6tcx1EA1TpGIWWOgKG:-O6tcx1EA1TpGIWWOgKH:b-ah0cr1) ([raw file](https://github.com/starkware-libs/sequencer/blob/23ff0942958387bcba1bedcf8f92808241854dfb/crates/blockifier/src/execution/contract_class.rs#L248)):*
> ```XML
>     /// Returns whether this contract should run using Cairo steps or Sierra gas.
>     pub fn run_resource(&self, min_sierra_version: &Version) -> RunResource {
>         let res = Version::parse(&self.compiler_version);
> ```

Failing to parse the compiler version should result in panic.



_Suggestion:_
```XML
let res = Version::parse(&self.compiler_version).except("...");
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 248 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/787#-O6tfI8eEghaoMuxK2xI:-O6tfI8eEghaoMuxK2xJ:b8mw81f) ([raw file](https://github.com/starkware-libs/sequencer/blob/23ff0942958387bcba1bedcf8f92808241854dfb/crates/blockifier/src/execution/contract_class.rs#L248)):*
> ```XML
>     /// Returns whether this contract should run using Cairo steps or Sierra gas.
>     pub fn run_resource(&self, min_sierra_version: &Version) -> RunResource {
>         let res = Version::parse(&self.compiler_version);
> ```

Also, maybe do the parsing in the construction of the struct?



_Code quote:_
```XML
let res = Version::parse(&self.compiler_version);
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/787)* status: 4 of 7 files reviewed, 7 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 51 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/787#-O6tnFoY91UNX346DtWd:-O6tnFoY91UNX346DtWe:bsxm90f) ([raw file](https://github.com/starkware-libs/sequencer/blob/23ff0942958387bcba1bedcf8f92808241854dfb/crates/blockifier/src/execution/contract_class.rs#L51)):*
> ```XML
> /// The resource used to run a contract function.
> #[derive(Clone, Copy, Default, Debug, Eq, PartialEq, Serialize)]
> pub enum RunResource {
> ```

Too similar to `RunResources`.
How about MeteringMode?



_Code quote:_
```XML
RunResource 
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/787)* status: 3 of 13 files reviewed, 7 unresolved discussions (waiting on @nimrod-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 94 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/787#-O6tZ0sk-prVenG0EMPh:-O6uK5ZIC7vO25Fp6os6:b-b67b98) ([raw file](https://github.com/starkware-libs/sequencer/blob/23ff0942958387bcba1bedcf8f92808241854dfb/crates/blockifier/src/versioned_constants.rs#L94)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Remove and fill `"min_compiler_version_for_gas_usage": "2.8.0"` in all version files.
(default is bad here, right?)
</blockquote></details>

I've used default exactly for this reason, didn't know we can just change previous version_constant files -> removed the default.
___
*[`crates/blockifier/src/versioned_constants.rs` line 95 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/787#-O6tYrDC1C6gDdLZnji5:-O6uIQYr5mm5HfdVOCyV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/23ff0942958387bcba1bedcf8f92808241854dfb/crates/blockifier/src/versioned_constants.rs#L95)):*
> ```XML
>     pub validate_max_n_steps: u32,
>     #[serde(default)]
>     pub min_compiler_version_for_gas_usage: String,
> ```

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 257 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/787#-O6tcN_x767v6pRnuSfg:-O6uIQzjACYDcm2rhxB0:b1cclec) ([raw file](https://github.com/starkware-libs/sequencer/blob/23ff0942958387bcba1bedcf8f92808241854dfb/crates/blockifier/src/versioned_constants.rs#L257)):*
> ```XML
>     }
> 
>     pub fn get_min_compiler_version_for_gas_usage(&self) -> Version {
> ```

Removed this function and moved the string->Version translation to the struct itself. This way we will fail immediately upon deserialization of an invalid version string, and not wait until a call to this removed function.
___
*[`crates/blockifier/src/versioned_constants.rs` line 258 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/787#-O6tcJOY7jasSWVtDYDh:-O6uUt3h2htSKRqlA8wn:bss4a2b) ([raw file](https://github.com/starkware-libs/sequencer/blob/23ff0942958387bcba1bedcf8f92808241854dfb/crates/blockifier/src/versioned_constants.rs#L258)):*
> ```XML
> 
>     pub fn get_min_compiler_version_for_gas_usage(&self) -> Version {
>         Version::parse(&self.min_compiler_version_for_gas_usage).unwrap_or(Version::new(0, 0, 0))
> ```

Removed.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 51 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/787#-O6tnFoY91UNX346DtWd:-O6uIaoT30DiaqSfB7jh:b-jbzc20) ([raw file](https://github.com/starkware-libs/sequencer/blob/23ff0942958387bcba1bedcf8f92808241854dfb/crates/blockifier/src/execution/contract_class.rs#L51)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Too similar to `RunResources`.
How about MeteringMode?
</blockquote></details>

The problem is we have both `RunResources` and `ExecutionResources`. I don't like `MeteringMode` I like have resource in it (I think it's clearer without context).`Metering/TrackingResource`?
___
*[`crates/blockifier/src/execution/contract_class.rs` line 248 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/787#-O6tcx1EA1TpGIWWOgKG:-O6uJcJy5T0iwAQKOQMv:b-3q79ce) ([raw file](https://github.com/starkware-libs/sequencer/blob/23ff0942958387bcba1bedcf8f92808241854dfb/crates/blockifier/src/execution/contract_class.rs#L248)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Failing to parse the compiler version should result in panic.
</blockquote></details>

Done (not here but earlier).
___
*[`crates/blockifier/src/execution/contract_class.rs` line 248 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/787#-O6tfI8eEghaoMuxK2xI:-O6uJw_HADV4eo2DshKQ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/23ff0942958387bcba1bedcf8f92808241854dfb/crates/blockifier/src/execution/contract_class.rs#L248)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Also, maybe do the parsing in the construction of the struct?
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/787#-:-O6vQJMzAtcDu8umfuP8:bnfp4nl)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 257 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/787#-O6tcN_x767v6pRnuSfg:-O6vPoKM1vnC4CqgN9l5:bb6u032) ([raw file](https://github.com/starkware-libs/sequencer/blob/23ff0942958387bcba1bedcf8f92808241854dfb/crates/blockifier/src/versioned_constants.rs#L257)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Removed this function and moved the string->Version translation to the struct itself. This way we will fail immediately upon deserialization of an invalid version string, and not wait until a call to this removed function.
</blockquote></details>

Cool

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/787)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/native_blockifier/src/py_block_executor_test.rs` line 23 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/787#-O6yzXriEKtrwT1LySvg:-O6yzXriEKtrwT1LySvh:b-ves0bo) ([raw file](https://github.com/starkware-libs/sequencer/blob/114e3b9cda4b1e3ecea408d1d8907dc0cb000045/crates/native_blockifier/src/py_block_executor_test.rs#L23)):*
> ```XML
>     // Initialize executor and set a contract class on the state.
>     let mut casm = CasmContractClass::default();
>     // TODO(tzahi): Remove once the default value of compiler version is of a legal value.
> ```

@ilyalesokhin-starkware FYI

**Review by Yoni-Starkware — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/787#-:-O72xobJE92IA1Yo1eR0:bnfp4nl)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

**Review by nimrod-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/787#-:-O73IdweC-M_MMq147US:bnfp4nl)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/787)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
