### PR TITLE
feat(mempool): fee escalation overrides queued transaction

### PR DESCRIPTION
**Pull request by ayeletstarkware**

### CODE REVIEW

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1999)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1999#-OBW9zu2DG-cZV1XRXf8:-OBW9zu2DG-cZV1XRXf9:b-llit0a) ([raw file](https://github.com/starkware-libs/sequencer/blob/7064fa44eab53e272bf6dab7cff5d3d6456bca2a/crates/mempool/src/mempool_test.rs#L142)):*
> ```XML
>         .with_pool([valid_replacement_input.tx.clone()])
>         .with_priority_queue([TransactionReference::new(&valid_replacement_input.tx)])
>         .build();
> ```

This would save the clone.
Or simple define temporal variable: `expected_priotiry_queue`.



_Suggestion:_
```XML
    let expected_mempool_content = MempoolContentBuilder::new()
        .with_priority_queue([TransactionReference::new(&valid_replacement_input.tx)])
        .with_pool([valid_replacement_input.tx])
        .build();
```
___
*[`crates/mempool/src/mempool.rs` line 212 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1999#-OBWAGHy-0v88dNZz2_L:-OBWAGHy-0v88dNZz2_M:b-sk8ckp) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcb2b8e2741bf4782d0418a99f9bebd3fa6aeef7/crates/mempool/src/mempool.rs#L212)):*
> ```XML
> 
>         // Check nonce against the queue.
>         // TODO(Elin): change to < for fee escalation (and add test).
> ```

Do we need to add a test for this case?



_Code quote:_
```XML
(and add test)
```

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1999)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1999#-OB_UZXr6PXRbKVlP2WM:-OB_UZXs0qBmfCLXWRbF:b-ud04gn) ([raw file](https://github.com/starkware-libs/sequencer/blob/7064fa44eab53e272bf6dab7cff5d3d6456bca2a/crates/mempool/src/mempool_test.rs#L141)):*
> ```XML
>     let expected_mempool_content = MempoolContentBuilder::new()
>         .with_pool([valid_replacement_input.tx.clone()])
>         .with_priority_queue([TransactionReference::new(&valid_replacement_input.tx)])
> ```

This way you suggest that the replacement is always done for the queued transactions? Is that a valid assumption?



_Code quote:_
```XML
.with_priority_queue([TransactionReference::new(&valid_replacement_input.tx)])
```
___
*[`crates/mempool/src/mempool_test.rs` line 533 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1999#-OB_Uw0DA_xSmeFLfYcB:-OB_Uw0EAI7S-3MIcTMy:bx028yw) ([raw file](https://github.com/starkware-libs/sequencer/blob/7064fa44eab53e272bf6dab7cff5d3d6456bca2a/crates/mempool/src/mempool_test.rs#L533)):*
> ```XML
>         let tx = tx!(tip: 90, max_l2_gas_price: 90);
>         let mempool = MempoolContentBuilder::new()
>             .with_priority_queue([TransactionReference::new(&tx)])
> ```

Should it be in the queue?



_Code quote:_
```XML
 .with_priority_queue([TransactionReference::new(&tx)])
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1999)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @MohammadNassar1)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1999#-OB_5ZvZ0IwuNFfxAT4R:-OBdpzf80IYQyA4BzSyD:b-896fix) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I see that some tests have failed. Please resolve the issues to proceed with the reviewing.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool.rs` line 212 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1999#-OBWAGHy-0v88dNZz2_L:-OBdq4fU3jeqstn7dyeo:b-yvqhtr) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcb2b8e2741bf4782d0418a99f9bebd3fa6aeef7/crates/mempool/src/mempool.rs#L212)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Do we need to add a test for this case?
</blockquote></details>

That's the PR's purpose. We want to enable fee escalation in queued transactions.
___
*[`crates/mempool/src/mempool_test.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1999#-OB_UZXr6PXRbKVlP2WM:-OBdq_zl4s3tQwO9E56D:b-5ee5p4) ([raw file](https://github.com/starkware-libs/sequencer/blob/7064fa44eab53e272bf6dab7cff5d3d6456bca2a/crates/mempool/src/mempool_test.rs#L141)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

This way you suggest that the replacement is always done for the queued transactions? Is that a valid assumption?
</blockquote></details>

It's a test util. it fits the current tests. perhaps will be changed in the future when more tests are added.
___
*[`crates/mempool/src/mempool_test.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1999#-OBW9zu2DG-cZV1XRXf8:-OBdqjK20pkbSPSKFKXp:b-a4drxi) ([raw file](https://github.com/starkware-libs/sequencer/blob/7064fa44eab53e272bf6dab7cff5d3d6456bca2a/crates/mempool/src/mempool_test.rs#L142)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

This would save the clone.
Or simple define temporal variable: `expected_priotiry_queue`.
</blockquote></details>

I went with the file's convention that `with_pool` is above `with_queue`. The cloning will be move inside the functions soon (noam is working on it).
___
*[`crates/mempool/src/mempool_test.rs` line 533 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1999#-OB_Uw0DA_xSmeFLfYcB:-OBdqz032D-YBzWTGArR:b-3uovvm) ([raw file](https://github.com/starkware-libs/sequencer/blob/7064fa44eab53e272bf6dab7cff5d3d6456bca2a/crates/mempool/src/mempool_test.rs#L533)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Should it be in the queue?
</blockquote></details>

Yep, I want to make sure that fee escalation works in queued transaction

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1999)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/starknet_mempool/src/mempool_test.rs` line 141 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1999#-OBeniVR1jS2VeqUjZeM:-OBeniVS2Djc-RzAxHlF:bykl9c2) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b8145e21cc543ac43810ac8ef20ae31cefd4a4c/crates/starknet_mempool/src/mempool_test.rs#L141)):*
> ```XML
>     let expected_mempool_content = MempoolContentBuilder::new()
>         .with_priority_queue([TransactionReference::new(&valid_replacement_input.tx)])
>         .with_pool([valid_replacement_input.tx.clone()])
> ```

Please remove the clone; it's redundant.



_Code quote:_
```XML
x.clone()
```
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 381 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1999#-OBepUmK3xIrsdEGZSG8:-OBepUmK3xIrsdEGZSG9:b-gakua0) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b8145e21cc543ac43810ac8ef20ae31cefd4a4c/crates/starknet_mempool/src/mempool_test.rs#L381)):*
> ```XML
>     MempoolError::DuplicateNonce { address: contract_address!("0x0"), nonce: nonce!(1) }
> )]
> fn test_add_tx_lower_than_queued_nonce(
> ```

Please remove the use of `#[case]`, and simplify the test.
Simply:



_Code quote (i):_
```XML
fn test_add_tx_lower_than_queued_nonce(
```



_Code snippet (ii):_
```XML
let tx_1 = ...
add_tx_expect_error...

let tx_2 = ...
add_tx_expect_error...
```
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 381 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1999#-OBeqWbT2dZl2ZeqOli_:-OBeqWbT2dZl2ZeqOlia:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b8145e21cc543ac43810ac8ef20ae31cefd4a4c/crates/starknet_mempool/src/mempool_test.rs#L381)):*
> ```XML
>     MempoolError::DuplicateNonce { address: contract_address!("0x0"), nonce: nonce!(1) }
> )]
> fn test_add_tx_lower_than_queued_nonce(
> ```





_Suggestion:_
```XML
test_add_tx_lower_eq_than_queued_nonce
```
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 512 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1999#-OBeqbN8DQZgqiVAIo-S:-OBeqbN8DQZgqiVAIo-T:b-oyqc3c) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b8145e21cc543ac43810ac8ef20ae31cefd4a4c/crates/starknet_mempool/src/mempool_test.rs#L512)):*
> ```XML
> 
> #[rstest]
> fn test_fee_escalation_valid_replacement() {
> ```

What about fee esc. of a tx that is not in queue?



_Code quote:_
```XML
test_fee_escalation_valid_replacement
```
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 540 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1999#-OBeqRSt1kWnwIrlIkrC:-OBeqRSt1kWnwIrlIkrD:byn2cut) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b8145e21cc543ac43810ac8ef20ae31cefd4a4c/crates/starknet_mempool/src/mempool_test.rs#L540)):*
> ```XML
>     let existing_tx = tx!(tx_hash: 1, tip: 100, max_l2_gas_price: 100);
>     let mempool = MempoolContentBuilder::new()
>         .with_pool([existing_tx.clone()])
> ```

please remove



_Code quote:_
```XML
clone()
```
___
*[`crates/starknet_mempool/src/mempool.rs` line 230 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1999#-OBend-OD6Pw32q4Wbbq:-OBend-OD6Pw32q4Wbbr:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b8145e21cc543ac43810ac8ef20ae31cefd4a4c/crates/starknet_mempool/src/mempool.rs#L230)):*
> ```XML
>                 return Err(MempoolError::DuplicateNonce { address, nonce: tx_nonce });
>             }
>         }
> ```





_Suggestion:_
```XML
if let Some(queued_nonce) = self.tx_queue.get_nonce(address) {
    match tx_nonce.cmp(&queued_nonce) {
        std::cmp::Ordering::Less => return Err(MempoolError::NonceTooOld { address, nonce: tx_nonce }),
        std::cmp::Ordering::Equal if !self.config.enable_fee_escalation => {
            return Err(MempoolError::DuplicateNonce { address, nonce: tx_nonce })
        }
        _ => {}
    }
}
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1999)* status: 3 of 5 files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/starknet_mempool/src/mempool.rs` line 219 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1999#-OBtCYFQ-Qtxi6BvyoU5:-OBtCYFR8mCNWrXknlG1:bdrbjei) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b8145e21cc543ac43810ac8ef20ae31cefd4a4c/crates/starknet_mempool/src/mempool.rs#L219)):*
> ```XML
>         {
>             return Err(MempoolError::NonceTooOld { address, nonce: tx_nonce });
>         }
> ```

Let's wait for the code fix for my opened two PRs to be merged; they are mostly reviewed.
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 511 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1999#-OBtBrToEfTkPUf0DtWA:-OBtBrTpBhAYMOzzjILO:b-39w8mw) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b8145e21cc543ac43810ac8ef20ae31cefd4a4c/crates/starknet_mempool/src/mempool_test.rs#L511)):*
> ```XML
> // Fee escalation tests.
> 
> #[rstest]
> ```

I would only like one test to test the (positive and negative) case in which the given transaction is [in]valid for replacement. In addition, come to think of it, I'd like for transaction-only-in-pool to also be tested. So what I have in mind is the following case Cartesian product: `[in]valid x {only P, Q + P}`.

**Pull request closed without merging**
