### PR TITLE
fix(blockifier_reexecution): fix bug in get contract class

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1759?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1759** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1759?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1758** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1758?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1712** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1712?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1698** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1698?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1658** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1658?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1604** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1604?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1759)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 302 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1759#-OAmhMP4CViI4GPEUdo4:-OAmhMP4CViI4GPEUdo5:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/96eeca38b3080d7134bd44dcc57950181d2d07f9/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L302)):*
> ```XML
>             "class_hash": class_hash.0.to_string(),
>         });
>         let contract_value =
> ```





_Suggestion:_
```XML
raw_contract_class
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 311 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1759#-OAmh4QaAmMMtUK2BylA:-OAmh4QaAmMMtUK2BylB:b4qwljs) ([raw file](https://github.com/starkware-libs/sequencer/blob/96eeca38b3080d7134bd44dcc57950181d2d07f9/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L311)):*
> ```XML
>                 }
>                 Ok(contract) => contract,
>             };
> ```

what happens if you try this? (note the `?` at the end - i would expect a natural conversion from the `send_rpc_request` error to a variant of `StateError`)



_Suggestion:_
```XML
        let contract_value =
            match self.rpc_state_reader.send_rpc_request("starknet_getClass", params.clone()) {
                Err(RPCStateReaderError::ClassHashNotFound(_)) => {
                    return Err(StateError::UndeclaredClassHash(*class_hash));
                }
                other_result => other_result,
            }?;
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1759#-:-OArHOytB08DPeiJDhIv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1759)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1759)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
