### PR TITLE
test(blockifier): max gas price for new resource bounds

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/997)

### CODE REVIEW

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/997)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 951 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/997#-O7_bOLADUY7RuMiAJlO:-O7_bOLADUY7RuMiAJlP:b-qtirig) ([raw file](https://github.com/starkware-libs/sequencer/blob/63985ad9fb2a4da58702ef06d4dd9f3b2f31823d/crates/blockifier/src/transaction/transactions_test.rs#L951)):*
> ```XML
>         max_fee: Fee(MAX_FEE)
>     };
>     let tx = &account_invoke_tx(valid_invoke_tx_args.clone());
> ```

I think its better to start with asserting a successful execution of this tx with the default resource bounds defined below.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 979 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/997#-O7_bdol0UlQo7X8NS1d:-O7_bdol0UlQo7X8NS1e:blo6j0c) ([raw file](https://github.com/starkware-libs/sequencer/blob/63985ad9fb2a4da58702ef06d4dd9f3b2f31823d/crates/blockifier/src/transaction/transactions_test.rs#L979)):*
> ```XML
> 
>     // Max gas price too low, new resource bounds.
>     for (_resource, insufficient_price_resource_bounds) in [
> ```

This is a used var



_Suggestion:_
```XML
insufficient_resource
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1016 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/997#-O7_cIQz8xUp3ShgkMHW:-O7_cIQz8xUp3ShgkMHX:b-30oin6) ([raw file](https://github.com/starkware-libs/sequencer/blob/63985ad9fb2a4da58702ef06d4dd9f3b2f31823d/crates/blockifier/src/transaction/transactions_test.rs#L1016)):*
> ```XML
>         });
>         let execution_error = invalid_v3_tx.execute(state, block_context, true, true).unwrap_err();
>         assert_matches!(
> ```

Add a TODO to add a variation of more than 1 insufficient resource, after the error message is updated to return all of them.

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/997)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 951 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/997#-O7_bOLADUY7RuMiAJlO:-O7c9O8K-YWSxD8jrZ2y:b-1m63qc) ([raw file](https://github.com/starkware-libs/sequencer/blob/63985ad9fb2a4da58702ef06d4dd9f3b2f31823d/crates/blockifier/src/transaction/transactions_test.rs#L951)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I think its better to start with asserting a successful execution of this tx with the default resource bounds defined below.
</blockquote></details>

Done. I added this assertion at the end to avoid complicating the test by increasing the nonce.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 979 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/997#-O7_bdol0UlQo7X8NS1d:-O7c6qmP6ZcvVc8_2Bis:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/63985ad9fb2a4da58702ef06d4dd9f3b2f31823d/crates/blockifier/src/transaction/transactions_test.rs#L979)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

This is a used var
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1016 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/997#-O7_cIQz8xUp3ShgkMHW:-O7c6qA55khxOdTT3Qe0:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/63985ad9fb2a4da58702ef06d4dd9f3b2f31823d/crates/blockifier/src/transaction/transactions_test.rs#L1016)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Add a TODO to add a variation of more than 1 insufficient resource, after the error message is updated to return all of them.
</blockquote></details>

Done.

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/997)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 167 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/997#-O7cWzRI34Se9hsjQ-0C:-O7cWzRI34Se9hsjQ-0D:b-wv2drc) ([raw file](https://github.com/starkware-libs/sequencer/blob/8b7f7b0182b7384da41bada2d6a63c573761f377/crates/blockifier/src/test_utils.rs#L167)):*
> ```XML
> 
> // TODO: Default testing bounds should probably be AllResourceBounds variant.
> pub fn default_testing_resource_bounds() -> ValidResourceBounds {
> ```

Why are these defined? Seems they are not used anywhere
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 951 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/997#-O7_bOLADUY7RuMiAJlO:-O7cXelRBheYl1m3G6sr:b-nh69w9) ([raw file](https://github.com/starkware-libs/sequencer/blob/63985ad9fb2a4da58702ef06d4dd9f3b2f31823d/crates/blockifier/src/transaction/transactions_test.rs#L951)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done. I added this assertion at the end to avoid complicating the test by increasing the nonce.
</blockquote></details>

Can you just run it before with a different sender address (`account_contract.get_instance_address(1)`)? The current is problematic, because if for some reason the "valid" tx will fail because of some bug, it will probably mean the invalid txs will earlier, and they will lead the debugger to the wrong direction of where the bug is.

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/997)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 951 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/997#-O7_bOLADUY7RuMiAJlO:-O7c__Qv4aKGXlalDApv:bwlrzyn) ([raw file](https://github.com/starkware-libs/sequencer/blob/63985ad9fb2a4da58702ef06d4dd9f3b2f31823d/crates/blockifier/src/transaction/transactions_test.rs#L951)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Can you just run it before with a different sender address (`account_contract.get_instance_address(1)`)? The current is problematic, because if for some reason the "valid" tx will fail because of some bug, it will probably mean the invalid txs will earlier, and they will lead the debugger to the wrong direction of where the bug is.
</blockquote></details>

OK, never mind, didn't think about it right.

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/997)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1134 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/997#-O7caQU2AixDOFeMZfky:-O7caQU2AixDOFeMZfkz:b-aipn5x) ([raw file](https://github.com/starkware-libs/sequencer/blob/63985ad9fb2a4da58702ef06d4dd9f3b2f31823d/crates/blockifier/src/transaction/transactions_test.rs#L1134)):*
> ```XML
>                 l1_data_gas: ResourceBounds { max_amount: 0, max_price_per_unit: actual_strk_l1_data_gas_price.into() }
>             }),
>         ..valid_invoke_tx_args.clone()
> ```

Isn't this included in the new test you've made?



_Code quote:_
```XML
    // Max L1 gas price too low, new resource bounds.
    // TODO: update l1_data max_amount and l2_data max_amount once minimal estimations are done.
    let insufficient_max_l1_gas_price = u128::from(actual_strk_l1_gas_price) - 1;
    let invalid_v3_tx = account_invoke_tx(invoke_tx_args! {
        resource_bounds: ValidResourceBounds::AllResources(
            AllResourceBounds{
                l1_gas: ResourceBounds{max_amount: minimal_l1_gas, max_price_per_unit: insufficient_max_l1_gas_price },
                l2_gas: ResourceBounds { max_amount: 0, max_price_per_unit: actual_strk_l2_gas_price.into() },
                l1_data_gas: ResourceBounds { max_amount: 0, max_price_per_unit: actual_strk_l1_data_gas_price.into() }
            }),
        ..valid_invoke_tx_args.clone()
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/997)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils.rs` line 167 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/997#-O7cWzRI34Se9hsjQ-0C:-O7chrGZ-7shpRMZQXLl:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8b7f7b0182b7384da41bada2d6a63c573761f377/crates/blockifier/src/test_utils.rs#L167)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Why are these defined? Seems they are not used anywhere
</blockquote></details>

Done.

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/997)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 951 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/997#-O7_bOLADUY7RuMiAJlO:-O7dL5cU8eRK6_rJaL_a:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/63985ad9fb2a4da58702ef06d4dd9f3b2f31823d/crates/blockifier/src/transaction/transactions_test.rs#L951)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

OK, never mind, didn't think about it right.
</blockquote></details>

Done.

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/997#-:-O7dQFT3A-rf3KR_c2LM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
