### PR TITLE
fix(starknet_integration_tests): fix config when creating multiple nodes

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Comment by yair-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2426?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2348** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2348?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2426** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2426?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2426?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2299** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2299?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2242** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2242?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2253** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2253?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2426)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware and @yair-starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2426#-ODaYC55ClBufTi4rGPn:-ODaYC55ClBufTi4rGPo:b-trp6je) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ac2853c905e6f3d8b8969458ba6b7b651b2bb48/crates/starknet_integration_tests/src/utils.rs#L39)):*
> ```XML
> // Currently the orchestrator expects the sequencer addresses in the form of [0..n_sequencers).
> // TODO(yair): Change this offset to be a non-zero value once the orchestrator is updated.
> pub const SEQUENCER_ADDRESS_OFFSET: usize = 0;
> ```

Shouldn't this be 100?



_Suggestion:_
```XML
pub const SEQUENCER_ADDRESS_OFFSET: usize = 100;
```
___
*[`crates/starknet_integration_tests/src/utils.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2426#-ODaXxD937cw-N3uy12n:-ODaXxD937cw-N3uy12o:bt02kuh) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ac2853c905e6f3d8b8969458ba6b7b651b2bb48/crates/starknet_integration_tests/src/utils.rs#L66)):*
> ```XML
>     let mempool_p2p_config = create_mempool_p2p_config(sequencer_id, chain_info.chain_id.clone());
>     let monitoring_endpoint_config = create_monitoring_endpoint_config(sequencer_id);
>     let sequencer_address = create_sequencer_address(sequencer_id);
> ```

Use this to set validator id in config.



_Code quote:_
```XML
let sequencer_address = create_sequencer_address(sequencer_id);
```
___
*[`crates/starknet_integration_tests/src/utils.rs` line 282 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2426#-ODaX4AmC1Tmzogq3HMY:-ODaX4AmC1Tmzogq3HMZ:b-u0yfkd) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ac2853c905e6f3d8b8969458ba6b7b651b2bb48/crates/starknet_integration_tests/src/utils.rs#L282)):*
> ```XML
>     config.port += u16::try_from(sequencer_id).unwrap();
>     config
> }
> ```

@ShahakShama can you ptal at this?



_Code quote:_
```XML
fn create_mempool_p2p_config(sequencer_id: usize, chain_id: ChainId) -> MempoolP2pConfig {
    let mut config = MempoolP2pConfig::default();
    // When running multiple sequencers on the same machine, we need to make sure their ports are
    // different. Use the sequencer_id to differentiate between them.
    config.network_config.tcp_port += u16::try_from(sequencer_id).unwrap();
    config.network_config.quic_port += u16::try_from(sequencer_id).unwrap();
    config.network_config.chain_id = chain_id;
    config
}

fn create_monitoring_endpoint_config(sequencer_id: usize) -> MonitoringEndpointConfig {
    let mut config = MonitoringEndpointConfig::default();
    config.port += u16::try_from(sequencer_id).unwrap();
    config
}
```
___
*[`crates/starknet_sequencer_node/src/config/node_config.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2426#-ODaWD6b-MaMbIlQqK0M:-ODaWD6b-MaMbIlQqK0N:bwr87tb) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ac2853c905e6f3d8b8969458ba6b7b651b2bb48/crates/starknet_sequencer_node/src/config/node_config.rs#L86)):*
> ```XML
>                 "The sequencer address.",
>             ),
>             // TODO(Matan): make validator id of consensus point to the sequencer address.
> ```

We are removing the sequencer address from the block builder config. You can remove the TODO.
___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2426#-ODaYFasEmnKiwkPm-r_:-ODaYFasEmnKiwkPm-ra:bdep13z) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ac2853c905e6f3d8b8969458ba6b7b651b2bb48/crates/starknet_integration_tests/src/integration_test_setup.rs#L61)):*
> ```XML
>         // Derive the configuration for the sequencer node.
>         let (config, required_params) = create_config(
>             SEQUENCER_ID,
> ```

It's confusing that this is an index while validator id is a contract address. Can you change everywhere to differentiate?
use `index` or `number` instead of `id`



_Code quote:_
```XML
SEQUENCER_ID
```

**Review by alonh5 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2426)* status: all files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware and @yair-starkware)

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2426)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @alonh5 and @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2426#-ODaYFasEmnKiwkPm-r_:-ODeYU4lAaFWurEFotbS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ac2853c905e6f3d8b8969458ba6b7b651b2bb48/crates/starknet_integration_tests/src/integration_test_setup.rs#L61)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

It's confusing that this is an index while validator id is a contract address. Can you change everywhere to differentiate?
use `index` or `number` instead of `id`
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/utils.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2426#-ODaYC55ClBufTi4rGPn:-ODeYWonBVfnjngf-UNJ:b-u2ilaz) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ac2853c905e6f3d8b8969458ba6b7b651b2bb48/crates/starknet_integration_tests/src/utils.rs#L39)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Shouldn't this be 100?
</blockquote></details>

Code moved
___
*[`crates/starknet_integration_tests/src/utils.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2426#-ODaXxD937cw-N3uy12n:-ODeYoPB0Qvobs7akdT3:bpneic7) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ac2853c905e6f3d8b8969458ba6b7b651b2bb48/crates/starknet_integration_tests/src/utils.rs#L66)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Use this to set validator id in config.
</blockquote></details>

No need to create sequencer address anymore
___
*[`crates/starknet_sequencer_node/src/config/node_config.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2426#-ODaWD6b-MaMbIlQqK0M:-ODeYxuL5XEau8ZvhC6r:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ac2853c905e6f3d8b8969458ba6b7b651b2bb48/crates/starknet_sequencer_node/src/config/node_config.rs#L86)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

We are removing the sequencer address from the block builder config. You can remove the TODO.
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2426)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware and @yair-starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 256 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2426#-ODfkoKr5R2DwwFJgekR:-ODfkoKs0oRfznYmDBxs:b-v3anhz) ([raw file](https://github.com/starkware-libs/sequencer/blob/04595edc610380e46d7815c830b05427054fe63e/crates/starknet_integration_tests/src/utils.rs#L256)):*
> ```XML
>     // When running multiple sequencers on the same machine, we need to make sure their ports are
>     // different. Use the sequencer_index to differentiate between them.
>     config.network_config.tcp_port += u16::try_from(sequencer_index).unwrap();
> ```

Can we ensure or assert that the ports aren't colliding?

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2426)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 256 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2426#-ODfkoKr5R2DwwFJgekR:-ODjU1NP3y9skgJPWQVs:b-rqukox) ([raw file](https://github.com/starkware-libs/sequencer/blob/04595edc610380e46d7815c830b05427054fe63e/crates/starknet_integration_tests/src/utils.rs#L256)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can we ensure or assert that the ports aren't colliding?
</blockquote></details>

It will be checked at the node's startup.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2426#-:-ODjn7tQ6oxWELl3QTDb:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware and @yair-starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 261 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2426#-ODjm7nL20okjmEequGV:-ODjm7nL20okjmEequGW:b-rh96ml) ([raw file](https://github.com/starkware-libs/sequencer/blob/b1ee8068b836b42f89320a6be5940d0591b3c373/crates/starknet_integration_tests/src/utils.rs#L261)):*
> ```XML
>     // different. Use the sequencer_index to differentiate between them.
>     config.network_config.tcp_port += u16::try_from(sequencer_index).unwrap();
>     config.network_config.quic_port += u16::try_from(sequencer_index).unwrap();
> ```

The quic port is configured to be 1 over the tcp port, so the first node's quic port collides with the second's tcp port.
Shahak told me the quic port isn't currently used, which is why this doesn't fail, and they will remove it. Jusy an FYI

**Pull request merged**
