### PR TITLE
refactor: use serde workspace

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/311)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
* **#311** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/311?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main-v0.13.2`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/311)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`Cargo.toml` line 143 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/311#-O3aZawQC6hiOe3x5KsY:-O3aZawQC6hiOe3x5KsZ:b-irpwwo) ([raw file](https://github.com/starkware-libs/sequencer/blob/5697be7ebb04f687183511a59b854ea7ef6b8cd8/Cargo.toml#L143)):*
> ```TOML
> rustc-hex = "2.1.0"
> schemars = "0.8.12"
> serde = { version = "1.0.197", features = ["derive"] }
> ```

features should only be activated in the package toml; no features on the root toml



_Suggestion:_
```TOML
serde = "1.0.197"
```
___
*[`crates/committer/Cargo.toml` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/311#-O3aZdq85H7Ksa4RgryS:-O3aZdq85H7Ksa4RgryT:byr4ffv) ([raw file](https://github.com/starkware-libs/sequencer/blob/5697be7ebb04f687183511a59b854ea7ef6b8cd8/crates/committer/Cargo.toml#L27)):*
> ```TOML
> log.workspace = true
> rand.workspace = true
> serde.workspace = true
> ```

see above



_Suggestion:_
```TOML
serde = { workspace = true, features = ["derive"] }
```
___
*[`crates/committer_cli/Cargo.toml` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/311#-O3a_7OC0rXIQnDmz4E6:-O3a_7OC0rXIQnDmz4E7:b-3h8osy) ([raw file](https://github.com/starkware-libs/sequencer/blob/5697be7ebb04f687183511a59b854ea7ef6b8cd8/crates/committer_cli/Cargo.toml#L27)):*
> ```TOML
> rand.workspace = true
> rand_distr.workspace = true
> serde.workspace = true
> ```

add the feature here (see above)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/311#-:-O3kj614EqFZrx6MuHiX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/311)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Comment by AvivYossef-starkware** [comment]
### Merge activity

* **Aug 8, 6:40 AM EDT**: @AvivYossef-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/311).

**Pull request merged**
