### PR TITLE
feat(blockifier): rename initial_gas_cost to default_initial_gas_cost

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/958)

### CODE REVIEW

**Comment by TzahiTaub** [comment]
* **#958** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/958?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @TzahiTaub and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/958)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`config/papyrus/default_config.json` line 252 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/958#-O7TuCP61EgXVwlEQPyy:-O7TuCP61EgXVwlEQPyz:b-r34vx1) ([raw file](https://github.com/starkware-libs/sequencer/blob/5975bddecfb9c5bfa41c1348063b61599141ac73/config/papyrus/default_config.json#L252)):*
> ```JSON
>     "privacy": "Public"
>   },
>   "rpc.execution_config.default_initial_gas_cost": {
> ```

@DvirYo-starkware FYI

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/958)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/958)* status: all files reviewed, 1 unresolved discussion

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/958)* status: all files reviewed, 1 unresolved discussion

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/958)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
