### PR TITLE
feat(consensus): add sync_topic to test config

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/412)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/412?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#414** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/414?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#413** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/413?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#412** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/412?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#409** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/409?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#406** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/406?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#404** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/404?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#389** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/389?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#403](https://github.com/starkware-libs/sequencer/pull/403) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/403?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#387** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/387?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#386** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/386?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/412#-:-O4AfxQj04h8VMl5fPb2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @matan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/412#-O4AfqFS0QLVDbdAhSbk:-O4AfqFT-3ntyJEbB_V8:b-atdjt5) (no related file):*
Consider using `&str` as the time instead of `String`

___

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/412)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @DvirYo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/412#-O4AfqFS0QLVDbdAhSbk:-O4AymnZCMJVZ7qbp-U9:bwirv6s) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Consider using `&str` as the time instead of `String`
</blockquote></details>

I assume time should be type? Meaning `sync_topic: &str`? I'm not sure how this would work, since I think the config needs to own the data. This would be ok in `Default` since we have a static `&str`, but if we actually need to use a command line flag then we would need a real lifetime for the `&str`.

I checked all of the papyrus configs and they always use `String` not `&str`.

___

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/412#-:-O4JfGjK926lBvwdALh6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

**Review by asmaastarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/412)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Comment by matan-starkware** [comment]
### Merge activity

* **Aug 15, 9:10 AM EDT**: @matan-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/412).

**Pull request merged**
