### PR TITLE
fix(batcher): treat deadline as error in validate flow

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2148?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2148** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2148?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2148?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2053** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2053?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2126](https://github.com/starkware-libs/sequencer/pull/2126) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2126?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2050** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2050?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2049** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2049?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2042** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2042?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2046** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2046?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1951** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1951?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1996** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1996?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1986** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1986?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1985** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1985?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2148)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2148#-OC2IQNVE1dR0UfXokI2:-OC2IQNVE1dR0UfXokI3:bfclgou) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba483895a5cfa19a9efbcd716cb8a810a03766fb/crates/starknet_batcher/src/block_builder.rs#L52)):*
> ```XML
>     StreamTransactionsError(#[from] tokio::sync::mpsc::error::SendError<Transaction>),
>     #[error("Build block with fail_on_err mode, failed on error {}.", _0)]
>     FailOnError(String),
> ```

do you think an enum would be better than a string here?

#[derive(Debug)]
pub enum FailCause {
    DeadlineReached,
    BlockFull,
    TransactionError(err), 
}



_Code quote:_
```XML
FailOnError(String)
```

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2148)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2148#-OC2IQNVE1dR0UfXokI2:-OC2UEp578kFXw-Hh-2v:b-6uvxsg) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba483895a5cfa19a9efbcd716cb8a810a03766fb/crates/starknet_batcher/src/block_builder.rs#L52)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

do you think an enum would be better than a string here?

#[derive(Debug)]
pub enum FailCause {
    DeadlineReached,
    BlockFull,
    TransactionError(err), 
}
</blockquote></details>

Both are fine, but I think an enum would be better.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2148)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2148#-OC2IQNVE1dR0UfXokI2:-OC2id1I0qDYjm-lvyoU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba483895a5cfa19a9efbcd716cb8a810a03766fb/crates/starknet_batcher/src/block_builder.rs#L52)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Both are fine, but I think an enum would be better.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2148#-:-OC2nIbL9636T7_9HYNv:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2148#-OC2msEV-5yNN1Kq4mE6:-OC2msEV-5yNN1Kq4mE7:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3224ef6200185f3742334edf371114f57319b99/crates/starknet_batcher/src/block_builder.rs#L71)):*
> ```XML
>         match self {
>             FailOnErrorCause::BlockFull => write!(f, "Block is full"),
>             FailOnErrorCause::DeadlineReached => write!(f, "Deadline was reached"),
> ```





_Suggestion:_
```XML
has been reached
```

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2148)* status: all files reviewed, 5 unresolved discussions (waiting on @Yael-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2148#-OC2q42e00_y1A-6rQJb:-OC2q42e00_y1A-6rQJc:b13pc8q) (no related file):*
Can we use test cases in the tests that check `fail_on_error`
___
*[`crates/starknet_batcher/src/block_builder_test.rs` line 154 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2148#-OC2oGHgEbp6Bazm_s9Q:-OC2oGHgEbp6Bazm_s9R:bij8bl1) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3224ef6200185f3742334edf371114f57319b99/crates/starknet_batcher/src/block_builder_test.rs#L154)):*
> ```XML
> 
> fn mock_transaction_executor_with_delay(
>     input_txs: Vec<Transaction>,
> ```

Not blocking, but IIUC this change is not necessary (and it is advised to use slices in arguments)



_Code quote:_
```XML
Vec<T
```
___
*[`crates/starknet_batcher/src/block_builder.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2148#-OC2mbP5C3yWWaRBMrRP:-OC2mbP5C3yWWaRBMrRQ:b-b4kxas) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3224ef6200185f3742334edf371114f57319b99/crates/starknet_batcher/src/block_builder.rs#L52)):*
> ```XML
>     #[error(transparent)]
>     StreamTransactionsError(#[from] tokio::sync::mpsc::error::SendError<Transaction>),
>     #[error("Build block with fail_on_err mode, failed on error {0}.")]
> ```

activated



_Code quote:_
```XML
 mode
```
___
*[`crates/starknet_batcher/src/block_builder.rs` line 61 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2148#-OC2n-780vQAGQLKyzA7:-OC2n-780vQAGQLKyzA8:bw8aie6) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3224ef6200185f3742334edf371114f57319b99/crates/starknet_batcher/src/block_builder.rs#L61)):*
> ```XML
> 
> #[derive(Debug)]
> pub enum FailOnErrorCause {
> ```

You can derive `Error` and use `error(transaparent)` in `BlockBuilderError`



_Code quote:_
```XML
pub enum FailOnErrorCause {
```

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2148)* status: all files reviewed, 5 unresolved discussions (waiting on @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2148)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @yair-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2148#-OC2q42e00_y1A-6rQJb:-OC3YFNK8RecPfSogoZK:b-7rl0jd) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can we use test cases in the tests that check `fail_on_error`
</blockquote></details>

done.
___
*[`crates/starknet_batcher/src/block_builder.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2148#-OC2mbP5C3yWWaRBMrRP:-OC3YLbiEMcO_f69WaIl:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3224ef6200185f3742334edf371114f57319b99/crates/starknet_batcher/src/block_builder.rs#L52)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

activated
</blockquote></details>

done
___
*[`crates/starknet_batcher/src/block_builder.rs` line 61 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2148#-OC2n-780vQAGQLKyzA7:-OC3Yl1E2n0rruBV6NOW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3224ef6200185f3742334edf371114f57319b99/crates/starknet_batcher/src/block_builder.rs#L61)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

You can derive `Error` and use `error(transaparent)` in `BlockBuilderError`
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/block_builder_test.rs` line 154 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2148#-OC2oGHgEbp6Bazm_s9Q:-OC32NET8k1bAFqmsLje:b-7rl0jd) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3224ef6200185f3742334edf371114f57319b99/crates/starknet_batcher/src/block_builder_test.rs#L154)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Not blocking, but IIUC this change is not necessary (and it is advised to use slices in arguments)
</blockquote></details>

done.
___
*[`crates/starknet_batcher/src/block_builder.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2148#-OC2msEV-5yNN1Kq4mE6:-OC3YPf0DNyiH4z57jG9:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3224ef6200185f3742334edf371114f57319b99/crates/starknet_batcher/src/block_builder.rs#L71)):*
> ```XML
>         match self {
>             FailOnErrorCause::BlockFull => write!(f, "Block is full"),
>             FailOnErrorCause::DeadlineReached => write!(f, "Deadline was reached"),
> ```

done

**Review by alonh5 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2148)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2148#-:-OC3gBT4As_98SkCwfbN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
