### PR TITLE
chore(blockifier): a simple code cleanup in signature_length()

### PR DESCRIPTION
**Pull request by avivg-starkware**

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2108)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2108#-OBy7d15--vSKy4Qx3nU:-OBy7d16Dtk5DqfphMvw:b-euctgv) ([raw file](https://github.com/starkware-libs/sequencer/blob/24f580112c99f6ca16599a8c19473ea2cda48799/crates/blockifier/src/transaction/account_transaction.rs#L235)):*
> ```XML
>             Transaction::Declare(tx) => tx.signature(),
>             Transaction::DeployAccount(tx) => tx.signature(),
>             Transaction::Invoke(tx) => tx.signature(),
> ```

Are we cloning the signature here?



_Code quote:_
```XML
        let signature = match &self.tx {
            Transaction::Declare(tx) => tx.signature(),
            Transaction::DeployAccount(tx) => tx.signature(),
            Transaction::Invoke(tx) => tx.signature(),
```

**Comment by avivg-starkware** [comment]
*[`crates/blockifier/src/transaction/account_transaction.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2108#-OBy7d15--vSKy4Qx3nU:-OByVzCu1HLYOuQmLZz2:b7epj7l) ([raw file](https://github.com/starkware-libs/sequencer/blob/24f580112c99f6ca16599a8c19473ea2cda48799/crates/blockifier/src/transaction/account_transaction.rs#L235)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Are we cloning the signature here?
</blockquote></details>

yes,
before the change by using the following macro.
and After with a slight change:
- In #2101, the macro is copied to starknet_api::executable_transaction (implementing other getters)
- and in #2102, the macro is removed from blockifier::account_transaction, and implemented for 'signature' as well 

both through the blockifier and the Api, 'signature' is currently cloned. 

with the current implementation it is actually cloned twice, once by the transaction (tx field) and another by the executable transaction.
I can try and change this but this might mean separating to another macro, as it might not be the case for the other implementations of the macro. Would you like me to try and check? 



_Code snippet (i):_
```XML
implement_account_tx_inner_getters!(
        (signature, TransactionSignature),
        ...
```



_Code snippet (ii):_
```XML
macro_rules! implement_account_tx_inner_getters {
    ($(($field:ident, $field_type:ty)),*) => {
        $(pub fn $field(&self) -> $field_type {
            match &self.tx {
                // TODO(AvivG): Consider moving some of the logic to the Transaction enum.
                Transaction::Declare(tx) => tx.tx.$field().clone(),
                Transaction::DeployAccount(tx) => tx.tx.$field().clone(),
                Transaction::Invoke(tx) => tx.tx.$field().clone(),
            }
        })*
    };
}
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2108)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2108#-OBy7d15--vSKy4Qx3nU:-OC-M-nf8R2iKLvuD23b:b-5n9xq3) ([raw file](https://github.com/starkware-libs/sequencer/blob/24f580112c99f6ca16599a8c19473ea2cda48799/crates/blockifier/src/transaction/account_transaction.rs#L235)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

yes,
before the change by using the following macro.
and After with a slight change:
- In #2101, the macro is copied to starknet_api::executable_transaction (implementing other getters)
- and in #2102, the macro is removed from blockifier::account_transaction, and implemented for 'signature' as well 

both through the blockifier and the Api, 'signature' is currently cloned. 

with the current implementation it is actually cloned twice, once by the transaction (tx field) and another by the executable transaction.
I can try and change this but this might mean separating to another macro, as it might not be the case for the other implementations of the macro. Would you like me to try and check?
</blockquote></details>

Maybe we should have one additional macro that returns a reference.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2108)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2108#-OBy7d15--vSKy4Qx3nU:-OC-MImu8rP6OBqW6LMA:b-t2aquu) ([raw file](https://github.com/starkware-libs/sequencer/blob/24f580112c99f6ca16599a8c19473ea2cda48799/crates/blockifier/src/transaction/account_transaction.rs#L235)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Maybe we should have one additional macro that returns a reference.
</blockquote></details>

Let's talk

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2108)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2108#-OBy7d15--vSKy4Qx3nU:-OC9JEL09wlhtJGDw5Lx:bkd5ega) ([raw file](https://github.com/starkware-libs/sequencer/blob/24f580112c99f6ca16599a8c19473ea2cda48799/crates/blockifier/src/transaction/account_transaction.rs#L235)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Let's talk
</blockquote></details>

Added a TODO

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2108#-:-OC9aDw6-VoDZxlbhcY9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Pull request merged**
