### PR TITLE
fix(blockifier): update stack trace tests to use Native version

### PR DESCRIPTION
**Pull request by varex83**

### CODE REVIEW

**Review by varex83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2164)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 392 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2164#-OC9-eyMBWbyG9HDNoQI:-OC9fmmd6-jAq8ALC-jz:b79svr1) ([raw file](https://github.com/starkware-libs/sequencer/blob/89e54eb87969c4c6cdc6885cf697536aa082f9e7/crates/blockifier/src/test_utils/contracts.rs#L392)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

What is this 10000? Where did it come from?
</blockquote></details>

Just a random number to not panic in case of calling this function

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2164)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @varex83, and @Yoni-Starkware)

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 652 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2164#-OCDii7kEBU7kcZ2MvGu:-OCDii7kEBU7kcZ2MvGv:b-sf8mrp) ([raw file](https://github.com/starkware-libs/sequencer/blob/16038832cc9a13afda5878ffb3d25d2950d5bb9e/crates/blockifier/src/execution/stack_trace_test.rs#L652)):*
> ```XML
> #[rstest]
> /// Tests that hitting an execution error in an account contract constructor outputs the correct
> /// traceback (including correct class hash, contract address and constructor entry point selector).
> ```

Why did you delete the docstring?



_Code quote:_
```XML
/// Tests that hitting an execution error in an account contract constructor outputs the correct
/// traceback (including correct class hash, contract address and constructor entry point selector).
```

**Review by avi-starkware — APPROVED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2164)* status: all files reviewed, 3 unresolved discussions (waiting on @varex83 and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 1002 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2164#-OCDkxC09SFTjhNhurMh:-OCDkxC09SFTjhNhurMi:b-g7amj6) ([raw file](https://github.com/starkware-libs/sequencer/blob/89e54eb87969c4c6cdc6885cf697536aa082f9e7/crates/blockifier/src/execution/stack_trace_test.rs#L1002)):*
> ```XML
>             format!(
>                 "{frame_0}
> {frame_2_native}
> ```

Why is frame 2 different?
If that is expected, please document the reason so it will be easy to understand the test.



_Code quote:_
```XML
{frame_2_native}
```

**Review by avi-starkware — APPROVED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2164)* status: all files reviewed, 3 unresolved discussions (waiting on @varex83 and @Yoni-Starkware)

**Pull request closed without merging**
