### PR TITLE
test(mempool): add more tx!() macro usages

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1091)

### CODE REVIEW

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1091#-:-O80jaXd3xSx4o1b1Pmo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 875 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1091#-O80jNFJB9XWJuYDeDcL:-O80jNFJB9XWJuYDeDcM:b-u684n7) ([raw file](https://github.com/starkware-libs/sequencer/blob/9bbd58c03e42dd787f20ece8a2d92f3b1d6fb133/crates/mempool/src/mempool_test.rs#L875)):*
> ```XML
>     // Assert.
>     let expected_mempool_content =
>         MempoolContentBuilder::new().with_account_nonces([("0x0", 1)]).build();
> ```

The account nonce represents the next eligible nonce, which is the committed nonce + 1. 
Perhaps it would be clearer to add a comment explaining this.



_Code quote:_
```XML
1
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1091)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 875 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1091#-O80jNFJB9XWJuYDeDcL:-O80mTonDkKDVm0Oke2u:b5i2zui) ([raw file](https://github.com/starkware-libs/sequencer/blob/9bbd58c03e42dd787f20ece8a2d92f3b1d6fb133/crates/mempool/src/mempool_test.rs#L875)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

The account nonce represents the next eligible nonce, which is the committed nonce + 1. 
Perhaps it would be clearer to add a comment explaining this.
</blockquote></details>

Come to think of it, where does the account nonce change to `1`?

**Review by ayeletstarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1091)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 875 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1091#-O80jNFJB9XWJuYDeDcL:-O80q9rs-1lLjtKCwkFx:b11qnhz) ([raw file](https://github.com/starkware-libs/sequencer/blob/9bbd58c03e42dd787f20ece8a2d92f3b1d6fb133/crates/mempool/src/mempool_test.rs#L875)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Come to think of it, where does the account nonce change to `1`?
</blockquote></details>

In `commit_block`, we receive a state change with `address` and `nonce`, increment the nonce by one, and pass it to the `align_to_account_state` function, which updates the mempool's data structures, including the account nonce.

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1091)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 875 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1091#-O80jNFJB9XWJuYDeDcL:-O80tKG6ACn36AWb2ClN:blsi64m) ([raw file](https://github.com/starkware-libs/sequencer/blob/9bbd58c03e42dd787f20ece8a2d92f3b1d6fb133/crates/mempool/src/mempool_test.rs#L875)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

In `commit_block`, we receive a state change with `address` and `nonce`, increment the nonce by one, and pass it to the `align_to_account_state` function, which updates the mempool's data structures, including the account nonce.
</blockquote></details>

I see, thanks. Done.

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1091)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1091)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
