### PR TITLE
chore: rename BincodeSerdeWrapper to SerdeWrapper

### PR DESCRIPTION
**Pull request by nadin-Starkware**
commit-id:6fdc6c31

---

**Stack**:
- #2506
- #2463
- #2462
- #2461
- #2460 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2460)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/starknet_sequencer_infra/src/serde_utils.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2460#-ODLy6MaA-ChcIoUuE1f:-ODLy6MaA-ChcIoUuE1g:b-lsn0l6) ([raw file](https://github.com/starkware-libs/sequencer/blob/50db4420a3f9ea90e49326756635f3f0419bc557/crates/starknet_sequencer_infra/src/serde_utils.rs#L31)):*
> ```XML
>     pub fn deserialize(bytes: &[u8]) -> Result<T, bincode::Error> {
>         deserialize(bytes).map(|serde_wrapper: Self| serde_wrapper.data)
>     }
> ```

Can we use different names here, to distinguish from the actual serde operations? E.g., `serialize_inner` and `deserialize_inner`



_Code quote:_
```XML
    pub fn serialize(&self) -> Result<Vec<u8>, bincode::Error> {
        serialize(self)
    }

    pub fn deserialize(bytes: &[u8]) -> Result<T, bincode::Error> {
        deserialize(bytes).map(|serde_wrapper: Self| serde_wrapper.data)
    }
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2460)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sequencer_infra/src/serde_utils.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2460#-ODLy6MaA-ChcIoUuE1f:-ODMCWxVA2Rfw-lPskgN:b-eu7bif) ([raw file](https://github.com/starkware-libs/sequencer/blob/50db4420a3f9ea90e49326756635f3f0419bc557/crates/starknet_sequencer_infra/src/serde_utils.rs#L31)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can we use different names here, to distinguish from the actual serde operations? E.g., `serialize_inner` and `deserialize_inner`
</blockquote></details>

what about `wrapper_serialize` and `wrapper_deserialize`?

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2460)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/starknet_sequencer_infra/src/serde_utils.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2460#-ODLy6MaA-ChcIoUuE1f:-ODMGOxdBs-VhqeBBE-V:bb73djm) ([raw file](https://github.com/starkware-libs/sequencer/blob/50db4420a3f9ea90e49326756635f3f0419bc557/crates/starknet_sequencer_infra/src/serde_utils.rs#L31)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

what about `wrapper_serialize` and `wrapper_deserialize`?
</blockquote></details>

SGTM

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2460)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sequencer_infra/src/serde_utils.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2460#-ODLy6MaA-ChcIoUuE1f:-ODMGa5dAtK9J-vKcUQ3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/50db4420a3f9ea90e49326756635f3f0419bc557/crates/starknet_sequencer_infra/src/serde_utils.rs#L31)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

SGTM
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2460#-:-ODMHWrvCOR7eOPreLdN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2460)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Pull request merged**
