### PR TITLE
refactor: refactor copmonent execution mode enum

### PR DESCRIPTION
**Pull request by nadin-Starkware**

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1520)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/mempool_node/src/communication.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-O9oVfBM3LFx1L6jI6l0:-O9oVfBM3LFx1L6jI6l1:b-fw1dy2) ([raw file](https://github.com/starkware-libs/sequencer/blob/d200f93d676687bef295e819429c33a36ebd06d2/crates/mempool_node/src/communication.rs#L103)):*
> ```XML
>             Some(Arc::new(LocalBatcherClient::new(channels.take_batcher_tx())))
>         }
>         ComponentExecutionMode::LocalExecution { enable_remote_connection: true } => None,
> ```

2nd arm cases should also include the clients. I suggest unifying the 1st and 2nd arm condition to to `ComponentExecutionMode::LocalExecution {_}`.



_Code quote:_
```XML
ComponentExecutionMode::LocalExecution { enable_remote_connection: true } => None,
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1520)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/mempool_node/src/components.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-O9oVwju-vAGUBXM-UqC:-O9oVwjvBwLQmEs_sqAr:b-unsa2j) ([raw file](https://github.com/starkware-libs/sequencer/blob/d200f93d676687bef295e819429c33a36ebd06d2/crates/mempool_node/src/components.rs#L34)):*
> ```XML
>             Some(create_batcher(config.batcher_config.clone(), mempool_client))
>         }
>         ComponentExecutionMode::LocalExecution { enable_remote_connection: true } => None,
> ```

Same :pray: 



_Code quote:_
```XML
ComponentExecutionMode::LocalExecution { enable_remote_connection: true } => None,
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1520)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @nadin-Starkware)

___
*[`config/mempool/default_config.json` line 415 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-O9oX2O57PYE-SUDknki:-O9oX2O57PYE-SUDknkj:b-z8lnl4) ([raw file](https://github.com/starkware-libs/sequencer/blob/d200f93d676687bef295e819429c33a36ebd06d2/config/mempool/default_config.json#L415)):*
> ```JSON
>     "description": "Specifies whether the component, when running locally, allows remote connections.",
>     "privacy": "Public",
>     "value": false
> ```

why has this default value changed?



_Code quote:_
```JSON
false
```
___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-O9oWAseD4T4lD1jGiuQ:-O9oWAseD4T4lD1jGiuR:b514sob) ([raw file](https://github.com/starkware-libs/sequencer/blob/d200f93d676687bef295e819429c33a36ebd06d2/crates/mempool_node/src/config/component_execution_config.rs#L20)):*
> ```XML
> #[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
> pub enum ComponentExecutionMode {
>     SkipComponent,
> ```

WDYT about `Disabled`? 



_Code quote:_
```XML
SkipComponent
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1520)* status: 1 of 7 files reviewed, 8 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-O9oXE4r8FRj5IMrVpkf:-O9oXE4r8FRj5IMrVpkg:b6sqqpp) ([raw file](https://github.com/starkware-libs/sequencer/blob/d200f93d676687bef295e819429c33a36ebd06d2/crates/mempool_node/src/config/component_execution_config.rs#L70)):*
> ```XML
>         .collect()
>     }
> }
> ```

I'm slightly confused regarding the change in code structure; why is this changed required/preferred?



_Code quote:_
```XML
impl SerializeConfig for ComponentExecutionConfig {
    fn dump(&self) -> BTreeMap<ParamPath, SerializedParam> {
        vec![
            append_sub_config_name(self.execution_mode.dump(), "execution_mode"),
            ser_optional_sub_config(&self.local_config, "local_config"),
            ser_optional_sub_config(&self.remote_client_config, "remote_client_config"),
            ser_optional_sub_config(&self.remote_server_config, "remote_server_config"),
        ]
        .into_iter()
        .flatten()
        .collect()
    }
}
```
___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-O9oXP4U3HIzTo9kbzf6:-O9oXP4U3HIzTo9kbzf7:bngm49k) ([raw file](https://github.com/starkware-libs/sequencer/blob/d200f93d676687bef295e819429c33a36ebd06d2/crates/mempool_node/src/config/component_execution_config.rs#L129)):*
> ```XML
>         Self {
>             execution_mode: ComponentExecutionMode::LocalExecution {
>                 enable_remote_connection: false,
> ```

Please set all of these as `true` 
___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-O9oXezK9tp6Q3LISZ2Q:-O9oXezK9tp6Q3LISZ2R:b14gw6d) ([raw file](https://github.com/starkware-libs/sequencer/blob/d200f93d676687bef295e819429c33a36ebd06d2/crates/mempool_node/src/config/component_execution_config.rs#L195)):*
> ```XML
>     let mut error = ValidationError::new("Invalid component configuration.");
>     error.message = Some(error_message.into());
>     Err(error)
> ```

Please change to be in a match-case structure; I believe this will grealy simplify the code.



_Code quote:_
```XML
    let local_execution_mode =
        ComponentExecutionMode::LocalExecution { enable_remote_connection: false };
    let enable_remote_execution_mode =
        ComponentExecutionMode::LocalExecution { enable_remote_connection: true };
    let error_message = if component_config.execution_mode == local_execution_mode
        && component_config.local_config.is_some()
        && (component_config.remote_server_config.is_some()
            || component_config.remote_client_config.is_some())
    {
        "Local config and Remote config are mutually exclusive in Local mode execution, can't be \
         both active."
    } else if component_config.execution_mode == local_execution_mode
        && component_config.local_config.is_none()
    {
        "Local communication config is missing."
    } else if component_config.execution_mode == enable_remote_execution_mode
        && component_config.remote_server_config.is_none()
        && component_config.remote_client_config.is_none()
    {
        "Remote communication config is missing."
    } else if component_config.execution_mode == enable_remote_execution_mode
        && component_config.remote_server_config.is_some()
        && component_config.remote_client_config.is_some()
    {
        "Remote client and Remote server are mutually exclusive in Remote mode execution, can't be \
         both active."
    } else {
        return Ok(());
    };

    let mut error = ValidationError::new("Invalid component configuration.");
    error.message = Some(error_message.into());
    Err(error)
```
___
*[`crates/mempool_node/src/config/config_test.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-O9oXrU_6Qf3TOcJcHQa:-O9oXrU_6Qf3TOcJcHQb:bsnaff4) ([raw file](https://github.com/starkware-libs/sequencer/blob/d200f93d676687bef295e819429c33a36ebd06d2/crates/mempool_node/src/config/config_test.rs#L35)):*
> ```XML
>     use starknet_mempool_infra::component_definitions::LocalComponentCommunicationConfig;
> 
>     use crate::config::ComponentExecutionConfig;
> ```

Move `use` statements to the top of the module



_Code quote:_
```XML
    use starknet_mempool_infra::component_definitions::LocalComponentCommunicationConfig;

    use crate::config::ComponentExecutionConfig;
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1520)* status: 1 of 7 files reviewed, 9 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/mempool_node/src/config/config_test.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-O9oY8jp4SDtS79UTqmv:-O9oY8jp4SDtS79UTqmw:b-q292wj) ([raw file](https://github.com/starkware-libs/sequencer/blob/d200f93d676687bef295e819429c33a36ebd06d2/crates/mempool_node/src/config/config_test.rs#L49)):*
> ```XML
>         local_config,
>         remote_client_config,
>         remote_server_config,
> ```

I think this test would make more sense after we'd have the separated local server and local client configs.



_Code quote:_
```XML
    let component_exe_config = ComponentExecutionConfig {
        execution_mode,
        local_config,
        remote_client_config,
        remote_server_config,
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1520)* status: 0 of 8 files reviewed, 9 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`config/mempool/default_config.json` line 415 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-O9oX2O57PYE-SUDknki:-OABQpRx-LzFVju_hzw0:b-dac58a) ([raw file](https://github.com/starkware-libs/sequencer/blob/d200f93d676687bef295e819429c33a36ebd06d2/config/mempool/default_config.json#L415)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

why has this default value changed?
</blockquote></details>

The field was originally a boolean indicating whether the component was executed or not. Now, it specifies whether, when executed locally, the component allows remote connections. Since this PR is focused solely on refactoring, I've kept the current approach: the component runs locally but does not permit remote connections.
___
*[`crates/mempool_node/src/communication.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-O9oVfBM3LFx1L6jI6l0:-OACS2SECmhOi4bVvQxK:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d200f93d676687bef295e819429c33a36ebd06d2/crates/mempool_node/src/communication.rs#L103)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

2nd arm cases should also include the clients. I suggest unifying the 1st and 2nd arm condition to to `ComponentExecutionMode::LocalExecution {_}`.
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/components.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-O9oVwju-vAGUBXM-UqC:-OACTBO641-rVEPMw9Eg:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d200f93d676687bef295e819429c33a36ebd06d2/crates/mempool_node/src/components.rs#L34)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Same :pray:
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-O9oWAseD4T4lD1jGiuQ:-OABTeFoDXuKhDwJ45Sz:bbr3dvq) ([raw file](https://github.com/starkware-libs/sequencer/blob/d200f93d676687bef295e819429c33a36ebd06d2/crates/mempool_node/src/config/component_execution_config.rs#L20)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

WDYT about `Disabled`?
</blockquote></details>

Sounds good. Done.
___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-O9oXE4r8FRj5IMrVpkf:-OABUEd39vim7bu4_IF4:b6fovfd) ([raw file](https://github.com/starkware-libs/sequencer/blob/d200f93d676687bef295e819429c33a36ebd06d2/crates/mempool_node/src/config/component_execution_config.rs#L70)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I'm slightly confused regarding the change in code structure; why is this changed required/preferred?
</blockquote></details>

Since ComponentExecutionMode can now include a struct (LocalExecution), we need to add it using the append_sub_config_name function.
___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-O9oXP4U3HIzTo9kbzf6:-OABVD0zErrUy9js1iuH:bxxez9o) ([raw file](https://github.com/starkware-libs/sequencer/blob/d200f93d676687bef295e819429c33a36ebd06d2/crates/mempool_node/src/config/component_execution_config.rs#L129)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please set all of these as `true`
</blockquote></details>

Why? the current setup doesn't support remote connection
___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-O9oXezK9tp6Q3LISZ2Q:-OABcDR2BrDU-hF89Vg3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d200f93d676687bef295e819429c33a36ebd06d2/crates/mempool_node/src/config/component_execution_config.rs#L195)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to be in a match-case structure; I believe this will grealy simplify the code.
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/config/config_test.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-O9oXrU_6Qf3TOcJcHQa:-OABcTmzEwcQ-O6_RvfE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d200f93d676687bef295e819429c33a36ebd06d2/crates/mempool_node/src/config/config_test.rs#L35)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Move `use` statements to the top of the module
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/config/config_test.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-O9oY8jp4SDtS79UTqmv:-OABckSI6Ks6DMqZFp6O:b-iwmm5x) ([raw file](https://github.com/starkware-libs/sequencer/blob/d200f93d676687bef295e819429c33a36ebd06d2/crates/mempool_node/src/config/config_test.rs#L49)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I think this test would make more sense after we'd have the separated local server and local client configs.
</blockquote></details>

Added TODO

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1520)* status: all files reviewed, 5 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/mempool_node/src/components.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-OADsJSJ1OCzG8H1DCP_:-OADsJSK5QbjPNnHU8Aw:b-ape1km) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3cbeb9c0da69b9594567e3a29ecc1f181529f8d/crates/mempool_node/src/components.rs#L34)):*
> ```XML
>     let batcher = match config.components.batcher.execution_mode {
>         ComponentExecutionMode::LocalExecution { enable_remote_connection: _ } => {
>             let mempool_client: std::sync::Arc<dyn MempoolClient> =
> ```

Is metioning the type explicitly needed here? If so, why?
If yes, this has a type alias, `SharedMempoolClient` iirc. Please use it if needed.



_Code quote:_
```XML
std::sync::Arc<dyn MempoolClient>
```
___
*[`crates/mempool_node/src/servers.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-OADsnYCAl-MZjFFAc-u:-OADsnYCAl-MZjFFAc-v:bqbihab) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3cbeb9c0da69b9594567e3a29ecc1f181529f8d/crates/mempool_node/src/servers.rs#L56)):*
> ```XML
>             )))
>         }
>         ComponentExecutionMode::LocalExecution { enable_remote_connection: true } => None,
> ```

Unify these as well, not creating a local server if `enable_remote_connection: true` is a bug.



_Code quote:_
```XML
        ComponentExecutionMode::LocalExecution { enable_remote_connection: false } => {
            Some(Box::new(create_local_batcher_server(
                components.batcher.expect("Batcher is not initialized."),
                communication.take_batcher_rx(),
            )))
        }
        ComponentExecutionMode::LocalExecution { enable_remote_connection: true } => None,
```
___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-OADtjNN2l-Or3qrk2pj:-OADtjNN2l-Or3qrk2pk:bm7261p) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3cbeb9c0da69b9594567e3a29ecc1f181529f8d/crates/mempool_node/src/config/component_execution_config.rs#L189)):*
> ```XML
>         }
>         _ => return Ok(()),
>     };
> ```

Please add a todo in this pr to change these conditions. I know you're working on that already in a different pr, but the current state is buggy and this should be noted in the code, even if it will be in this state for a short period of time.



_Code quote:_
```XML
    let error_message = match (
        component_config.execution_mode.clone(),
        component_config.local_config.is_some(),
        component_config.remote_server_config.is_some(),
        component_config.remote_client_config.is_some(),
    ) {
        (mode, true, true, _) | (mode, true, _, true) if mode == local_execution_mode => {
            "Local config and Remote config are mutually exclusive in Local mode execution; both \
             can't be active."
        }
        (mode, false, _, _) if mode == local_execution_mode => {
            "Local communication config is missing."
        }
        (mode, _, false, false) if mode == enable_remote_execution_mode => {
            "Remote communication config is missing."
        }
        (mode, _, true, true) if mode == enable_remote_execution_mode => {
            "Remote client and Remote server are mutually exclusive in Remote mode execution; both \
             can't be active."
        }
        _ => return Ok(()),
    };
```
___
*[`crates/mempool_node/src/config/config_test.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-OADuQQZAePRsZlrrJTo:-OADuQQZAePRsZlrrJTp:b-6i5eqp) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3cbeb9c0da69b9594567e3a29ecc1f181529f8d/crates/mempool_node/src/config/config_test.rs#L30)):*
> ```XML
> #[case::local(ComponentExecutionMode::LocalExecution {enable_remote_connection: false}, None, None)]
> #[case::remote(ComponentExecutionMode::LocalExecution {enable_remote_connection: true}, Some(RemoteClientConfig::default()), None)]
> #[case::remote(ComponentExecutionMode::LocalExecution {enable_remote_connection: true}, None, Some(RemoteServerConfig::default()))]
> ```

Please add a todo to fix this test.



_Code quote:_
```XML
#[case::local(ComponentExecutionMode::LocalExecution {enable_remote_connection: false}, None, None)]
#[case::remote(ComponentExecutionMode::LocalExecution {enable_remote_connection: true}, Some(RemoteClientConfig::default()), None)]
#[case::remote(ComponentExecutionMode::LocalExecution {enable_remote_connection: true}, None, Some(RemoteServerConfig::default()))]
```

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1520#-:-OAHL1uE4L9Oc-bTShVX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Pull request merged**
