### PR TITLE
chore(starknet_batcher): validate batcher input buffer size config

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
* **#2410** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2410?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2410?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2410)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @lev-starkware)

___
*[`crates/starknet_sequencer_node/src/config/node_config.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2410#-OD78CBh-PryzX-gHJUM:-OD78CBh-PryzX-gHJUN:besj5x2) ([raw file](https://github.com/starkware-libs/sequencer/blob/e6832e8e7bb302e254f2c7c31ac14deef11ee634/crates/starknet_sequencer_node/src/config/node_config.rs#L194)):*
> ```XML
>     }
>     Ok(())
> }
> ```

add test

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2410)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @alonh5, @lev-starkware, and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/config.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2410#-ODAcCHZBgyxUYlJlctm:-ODAd1gB1GcKV97pe082:b-w2jm8c) ([raw file](https://github.com/starkware-libs/sequencer/blob/b16db24c62b61c2f624ffc0fa0e02f58e5ff859e/crates/starknet_batcher/src/config.rs#L94)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

We can start noticing these things if we want...
This is a pub function just so that it could be used in tests - right?

Thinking about it more - why is it public at all?
</blockquote></details>

non-blocking.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2410)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5, @ArniStarkware, and @lev-starkware)

___
*[`crates/starknet_batcher/src/config.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2410#-ODAcCHZBgyxUYlJlctm:-ODAryc069A3h0tb0Dgd:bybnttg) ([raw file](https://github.com/starkware-libs/sequencer/blob/b16db24c62b61c2f624ffc0fa0e02f58e5ff859e/crates/starknet_batcher/src/config.rs#L94)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

non-blocking.
</blockquote></details>

you're right, removed it. Thanks!
it was a leftover from previous code that used this function for validations of the struct that contains BatcherConfig.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2410#-:-ODBNcFX6-EY3iAT4CjT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5 and @lev-starkware)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2410)* status: all files reviewed, 1 unresolved discussion (waiting on @lev-starkware and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/config_test.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2410#-ODGi-lM8qNirulwXJJM:-ODGi-lM8qNirulwXJJN:bcl39sa) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d8da6d1fb2e6ec3e6dd128c6ca7eef26c44694c/crates/starknet_batcher/src/config_test.rs#L9)):*
> ```XML
> fn test_validate_batcher_config_success() {
>     let batcher_config = BatcherConfig::default();
>     assert!(batcher_config.validate().is_ok());
> ```

When is the validate called? How is it enforced?

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2410)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @alonh5, @ArniStarkware, and @lev-starkware)

___
*[`crates/starknet_batcher/src/config_test.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2410#-ODGi-lM8qNirulwXJJM:-ODGnme2BctkfM3Rjk5p:bnox5mm) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d8da6d1fb2e6ec3e6dd128c6ca7eef26c44694c/crates/starknet_batcher/src/config_test.rs#L9)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

When is the validate called? How is it enforced?
</blockquote></details>

validate() is called in main of starknet_sequencer_node for the entire node config - batcher included.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2410)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @alonh5, @ArniStarkware, and @lev-starkware)

___
*[`crates/starknet_batcher/src/config_test.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2410#-ODGi-lM8qNirulwXJJM:-ODGo3zZ7_oiGruFD2lb:bdl19dx) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d8da6d1fb2e6ec3e6dd128c6ca7eef26c44694c/crates/starknet_batcher/src/config_test.rs#L9)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

validate() is called in main of starknet_sequencer_node for the entire node config - batcher included.
</blockquote></details>

 changed the tests - now they call the same validate that is called in main.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2410)* status: all files reviewed, 1 unresolved discussion (waiting on @lev-starkware and @Yael-Starkware)

___
*[`crates/starknet_sequencer_node/src/config/config_test.rs` line 152 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2410#-ODGrRNx7_N5iuw5VTjw:-ODGrRNx7_N5iuw5VTjx:bo36xpb) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b8975cd97bf5dde43d7f27e3ef44056df39701e/crates/starknet_sequencer_node/src/config/config_test.rs#L152)):*
> ```XML
>         ..Default::default()
>     };
>     assert!(config.validate().is_err());
> ```

Let's check the specific error



_Code quote:_
```XML
assert!(config.validate().is_err());
```

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2410)* status: all files reviewed, 2 unresolved discussions (waiting on @lev-starkware and @Yael-Starkware)

___
*[`crates/starknet_sequencer_node/src/config/config_test.rs` line 152 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2410#-ODGrRNx7_N5iuw5VTjw:-OD_UNRN-M5PtBKrH9yu:bmxsrdk) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b8975cd97bf5dde43d7f27e3ef44056df39701e/crates/starknet_sequencer_node/src/config/config_test.rs#L152)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

That was more complex than expected.
not sure we want  to keep it .
</blockquote></details>

See suggestion.
___
*[`crates/starknet_sequencer_node/src/config/config_test.rs` line 154 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2410#-OD_UV8q1FmqFUj_9CzS:-OD_UV8q1FmqFUj_9CzT:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/44e2146216f4716e4fe067d76f4a5decd011c062/crates/starknet_sequencer_node/src/config/config_test.rs#L154)):*
> ```XML
> 
>     let error_code = get_batcher_config_error_code(config.validate().unwrap_err());
>     assert_eq!(error_code, "input_stream_content_buffer_size must be at least tx_chunk_size");
> ```





_Suggestion:_
```XML
    let error_code = config.validate().unwrap_err();
    assert!(
        error_code
            .to_string()
            .contains("input_stream_content_buffer_size must be at least tx_chunk_size")
    );
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2410)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @lev-starkware)

___
*[`crates/starknet_sequencer_node/src/config/config_test.rs` line 152 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2410#-ODGrRNx7_N5iuw5VTjw:-OD_eQbuAqVgCmDyn528:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0b8975cd97bf5dde43d7f27e3ef44056df39701e/crates/starknet_sequencer_node/src/config/config_test.rs#L152)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

See suggestion.
</blockquote></details>

Done.
___
*[`crates/starknet_sequencer_node/src/config/config_test.rs` line 154 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2410#-OD_UV8q1FmqFUj_9CzS:-OD_eNzm6FmDQKgydAwN:bakkrnq) ([raw file](https://github.com/starkware-libs/sequencer/blob/44e2146216f4716e4fe067d76f4a5decd011c062/crates/starknet_sequencer_node/src/config/config_test.rs#L154)):*
> ```XML
> 
>     let error_code = get_batcher_config_error_code(config.validate().unwrap_err());
>     assert_eq!(error_code, "input_stream_content_buffer_size must be at least tx_chunk_size");
> ```

much better, thanks!

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2410#-:-ODfxYT_54M5OoAhSX0R:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

___
*[`crates/starknet_sequencer_node/src/config/config_test.rs` line 154 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2410#-OD_UV8q1FmqFUj_9CzS:-ODfxVZTAR2KztcBUQGn:b-7m42hk) ([raw file](https://github.com/starkware-libs/sequencer/blob/44e2146216f4716e4fe067d76f4a5decd011c062/crates/starknet_sequencer_node/src/config/config_test.rs#L154)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

much better, thanks!
</blockquote></details>

np :)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2410)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Pull request merged**
