### PR TITLE
chore: add compilation output as rerun triger

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2182)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sierra_compile/build.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2182#-OC3yenb9NMzMS1FHUmo:-OC3yenb9NMzMS1FHUmp:b-clfk5d) ([raw file](https://github.com/starkware-libs/sequencer/blob/31ca3fba12593f924992c99a8db5c94663d11224/crates/starknet_sierra_compile/build.rs#L10)):*
> ```XML
> 
>     let binary_path = binary_path(CAIRO_LANG_BINARY_NAME);
>     println!("cargo:rerun-if-changed={:?}", binary_path);
> ```

Also, for `CAIRO_NATIVE_BINARY_NAME`



_Code quote:_
```XML
    let binary_path = binary_path(CAIRO_LANG_BINARY_NAME);
    println!("cargo:rerun-if-changed={:?}", binary_path);
```

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2182)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sierra_compile/build.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2182#-OC3yenb9NMzMS1FHUmo:-OC4-e04CQIqqA5OXRR4:b9qlx7p) ([raw file](https://github.com/starkware-libs/sequencer/blob/31ca3fba12593f924992c99a8db5c94663d11224/crates/starknet_sierra_compile/build.rs#L10)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Also, for `CAIRO_NATIVE_BINARY_NAME`
</blockquote></details>

Add a todo.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2182)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by ArniStarkware — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2182#-:-OC4-zGd9fBA-fz2reg4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
