### PR TITLE
refactor(mempool): rename MempoolContent methods to use tx abbreviation

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/966)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/966)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/966#-O7U2TAdAC890F7Pcc6i:-O7U2TAm5QPC_fO3ffwg:b7130w5) (no related file):*
Rename only.

___

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/966)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/966#-O7U7Il34AmXCRkSEXiT:-O7U7Il34AmXCRkSEXiU:b35f57j) ([raw file](https://github.com/starkware-libs/sequencer/blob/d59727abfe52170f05cd345d00463710ea1d4d00/crates/mempool/src/mempool_test.rs#L34)):*
> ```XML
> 
> impl MempoolContent {
>     fn assert_eq_pool_and_queue_content(&self, mempool: &Mempool) {
> ```

Out of context, but I think we should consider deleting this function and calling each assertion separately, now that we have more fields to assert.



_Code quote:_
```XML
assert_eq_pool_and_queue_content
```

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/966#-:-O7U7i682yRYaIOIN9Bm:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/966)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/966#-O7U7Il34AmXCRkSEXiT:-O7U8FS9CQPRI56mGfk8:b-n9j8pr) ([raw file](https://github.com/starkware-libs/sequencer/blob/d59727abfe52170f05cd345d00463710ea1d4d00/crates/mempool/src/mempool_test.rs#L34)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Out of context, but I think we should consider deleting this function and calling each assertion separately, now that we have more fields to assert.
</blockquote></details>

I see it's used quite a lot; what's your alternative suggestion?

**Pull request merged**
