### PR TITLE
refactor(batcher): move block_builder_factory out to the batcher

### PR DESCRIPTION
**Pull request by dafnamatsry**

### CODE REVIEW

**Comment by dafnamatsry** [comment]
* **#2279** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2279?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2279?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2279)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5 and @dafnamatsry)

___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2279#-OChJoLQAQwFcrf1LZVK:-OChJoLQAQwFcrf1LZVL:bqq4u3i) ([raw file](https://github.com/starkware-libs/sequencer/blob/37a269c3e3960a02618bb58b7b0ad74a8dd45324/crates/starknet_batcher/src/proposal_manager_test.rs#L84)):*
> ```XML
>     spawn_proposal(&mut proposal_manager, ProposalId(1), mock_build_block()).await;
>     spawn_proposal(&mut proposal_manager, ProposalId(2), mock_build_block()).await;
>     spawn_proposal(&mut proposal_manager, ProposalId(3), mock_build_block()).await;
> ```

I think 2 repetitions are good enough, now that we are calling only 1 api and not 2 as before.



_Code quote:_
```XML
    spawn_proposal(&mut proposal_manager, ProposalId(0), mock_build_block()).await;
    spawn_proposal(&mut proposal_manager, ProposalId(1), mock_build_block()).await;
    spawn_proposal(&mut proposal_manager, ProposalId(2), mock_build_block()).await;
    spawn_proposal(&mut proposal_manager, ProposalId(3), mock_build_block()).await;
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2279)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5, @dafnamatsry, and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 166 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2279#-OCgWSDm374Gfadt9Wza:-OChKsuJ9z-MWMsL2yQg:b-d1cz7x) ([raw file](https://github.com/starkware-libs/sequencer/blob/37a269c3e3960a02618bb58b7b0ad74a8dd45324/crates/starknet_batcher/src/batcher_test.rs#L166)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I notice we don't have the same function for propose, probably unrelated to its PR, but perhaps someone can tell why?
@Yael-Starkware
</blockquote></details>

because they do not share the same calls to the proposal manager.
validate flow used to call validate_block and get_proposal_status , while propose flow used to call propose_block.

They do share some code in mock_proposal_manager_common_expectations, so now you can add expect_wrap_spawn_proposal to the shared code as well.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2279)* status: all files reviewed, 6 unresolved discussions (waiting on @alonh5, @dafnamatsry, and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2279#-OChOGWK6FEtKQ5LZuen:-OChOGWL45tdUPRz3QU9:b-70eyzj) ([raw file](https://github.com/starkware-libs/sequencer/blob/37a269c3e3960a02618bb58b7b0ad74a8dd45324/crates/starknet_batcher/src/batcher.rs#L145)):*
> ```XML
>         let (abort_signal_sender, abort_signal_receiver) = tokio::sync::oneshot::channel();
> 
>         // A channel to receive the transactions included in the proposed block.
> ```

this comment is the same as the one in validate_block, I think it should emphasize that one channel is the output channel and the other is the input channel.



_Suggestion:_
```XML
// A channel to send the transactions included in the proposed block.
```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2279)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @alonh5, @Yael-Starkware, and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2279#-OChOGWK6FEtKQ5LZuen:-OChUD_I5O7H3zsMnYDE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/37a269c3e3960a02618bb58b7b0ad74a8dd45324/crates/starknet_batcher/src/batcher.rs#L145)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

this comment is the same as the one in validate_block, I think it should emphasize that one channel is the output channel and the other is the input channel.
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2279#-OChNcPd7s8Ie2n9Jfj1:-OChUFquB_4Co0R6vdPq:b1s0gsx) ([raw file](https://github.com/starkware-libs/sequencer/blob/37a269c3e3960a02618bb58b7b0ad74a8dd45324/crates/starknet_batcher/src/batcher.rs#L160)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why clone?
</blockquote></details>

Copy pasted from the proposal_manager. Indeed not necessary.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2279#-OCgTUr_A0qPeAyDFs30:-OChPfo2CEYCC1WrPjmp:b-wh42d6) ([raw file](https://github.com/starkware-libs/sequencer/blob/37a269c3e3960a02618bb58b7b0ad74a8dd45324/crates/starknet_batcher/src/batcher_test.rs#L41)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Is this on purpose?
</blockquote></details>

Fixed.
I was supposed to add `MockBlockBuilderTrait`.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 119 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2279#-OCgVt-O4jVN6XYrf34o:-OChQ-rd3FtlKXxb3QFy:b-3v0vvk) ([raw file](https://github.com/starkware-libs/sequencer/blob/37a269c3e3960a02618bb58b7b0ad74a8dd45324/crates/starknet_batcher/src/batcher_test.rs#L119)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do we have both functions?
</blockquote></details>

The first creates the mock block builder and the second accept it from the outside.
The first existed before this PR, and I kept it so I wouldn't have to touch all the tests that use it.
It is temporary and I will fix it in a following PR.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 166 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2279#-OCgWSDm374Gfadt9Wza:-OChXzck2MHUb066EgcC:b18u5la) ([raw file](https://github.com/starkware-libs/sequencer/blob/37a269c3e3960a02618bb58b7b0ad74a8dd45324/crates/starknet_batcher/src/batcher_test.rs#L166)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

because they do not share the same calls to the proposal manager.
validate flow used to call validate_block and get_proposal_status , while propose flow used to call propose_block.

They do share some code in mock_proposal_manager_common_expectations, so now you can add expect_wrap_spawn_proposal to the shared code as well.
</blockquote></details>

This method will also be deleted once we remove the proposal manager.
___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2279#-OChJoLQAQwFcrf1LZVK:-OChU46R7UmTyzyOFPgp:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/37a269c3e3960a02618bb58b7b0ad74a8dd45324/crates/starknet_batcher/src/proposal_manager_test.rs#L84)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think 2 repetitions are good enough, now that we are calling only 1 api and not 2 as before.
</blockquote></details>

Done.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2279)* status: 2 of 5 files reviewed, 8 unresolved discussions (waiting on @alonh5, @dafnamatsry, and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 228 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2279#-OChPUaM0tOE_zr09RBN:-OChPUaM0tOE_zr09RBO:b-yomekc) ([raw file](https://github.com/starkware-libs/sequencer/blob/37a269c3e3960a02618bb58b7b0ad74a8dd45324/crates/starknet_batcher/src/batcher.rs#L228)):*
> ```XML
>         // TODO(Dafna): this method should return an meaningful error if the given proposal_id
>         // is of a proposed block (and not validated). Currently it panics or returns a
>         // wrong error.
> ```

nice catch!



_Code quote:_
```XML
        // TODO(Dafna): this method should return an meaningful error if the given proposal_id
        // is of a proposed block (and not validated). Currently it panics or returns a
        // wrong error.
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2279#-OChaYCw6nPvgIGDjZrb:-OChaYCw6nPvgIGDjZrc:bcwrd1u) ([raw file](https://github.com/starkware-libs/sequencer/blob/37a269c3e3960a02618bb58b7b0ad74a8dd45324/crates/starknet_batcher/src/batcher_test.rs#L142)):*
> ```XML
>                 while tx_provider.get_txs(0).await.is_ok_and(|v| v == NextTxs::End) {
>                     tokio::task::yield_now().await;
>                 }
> ```

I played with this test a bit, I think there are 2 issues:

1. IIUC there is a missing NOT operator, right? you meant to yield_now() before the End, and not at the End?
2. I think there is a bug in the provider, if the input n_txs is 0, it always returns End.



_Code quote:_
```XML
                while tx_provider.get_txs(0).await.is_ok_and(|v| v == NextTxs::End) {
                    tokio::task::yield_now().await;
                }
```

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2279#-:-OChfin51gAJjK6Z2r31:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5, @dafnamatsry, and @Yael-Starkware)

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2279)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @alonh5, @Yael-Starkware, and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 228 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2279#-OChPUaM0tOE_zr09RBN:-OClZGNOBgF5ju7_zEdY:bvtk9y9) ([raw file](https://github.com/starkware-libs/sequencer/blob/37a269c3e3960a02618bb58b7b0ad74a8dd45324/crates/starknet_batcher/src/batcher.rs#L228)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

nice catch!
</blockquote></details>

Thanks :)
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2279#-OChaYCw6nPvgIGDjZrb:-OClYoDQAgY4qSnr8buJ:bas8ezx) ([raw file](https://github.com/starkware-libs/sequencer/blob/37a269c3e3960a02618bb58b7b0ad74a8dd45324/crates/starknet_batcher/src/batcher_test.rs#L142)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I played with this test a bit, I think there are 2 issues:

1. IIUC there is a missing NOT operator, right? you meant to yield_now() before the End, and not at the End?
2. I think there is a bug in the provider, if the input n_txs is 0, it always returns End.
</blockquote></details>

1. Right! thanks :)
2. I changed to 1 instead of 0, so this test won't rely on any assumption of the return value when n_txs is 0.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2279)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by alonh5 — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2279)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 158 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2279#-OCmcuY_48uz3WWejfna:-OCmcuYa4b2L4Pmzlzfx:b-4f610x) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3c0e523e3cc009f8e8ec1b3e7708b9830aedcea/crates/starknet_batcher/src/batcher_test.rs#L158)):*
> ```XML
>             // Simulate the streaming of the block builder output.
>             for tx in output_txs {
>                 output_content_sender.as_ref().unwrap().send(tx).unwrap();
> ```

You're sending the output txs before the block is created, isn't that a problem? Is there a better way to do it?



_Code quote:_
```XML
output_content_sender.as_ref().unwrap().send(tx).unwrap();
```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2279)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 158 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2279#-OCmcuY_48uz3WWejfna:-OD0Z4UlC9PqDq1b6FS3:bqzdd37) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3c0e523e3cc009f8e8ec1b3e7708b9830aedcea/crates/starknet_batcher/src/batcher_test.rs#L158)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You're sending the output txs before the block is created, isn't that a problem? Is there a better way to do it?
</blockquote></details>

We do this simulation so there will be data in the stream when calling `get_proposal_content`, I don't think it really matters when it happens. It might have make more sense to put it in the expectation to `spawn_proposal`, but I don't have access to the sender there (and keeping it here for later is too complicated I think).

In any case, once we remove the proposal manager, I plan to update the tests to use a fake block builder instead of a mock. This change will specifically make such simulations easier.

**Review by alonh5 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2279)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 158 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2279#-OCmcuY_48uz3WWejfna:-OD0btJl3PwGxN2GTyf3:bdmzvvc) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3c0e523e3cc009f8e8ec1b3e7708b9830aedcea/crates/starknet_batcher/src/batcher_test.rs#L158)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

We do this simulation so there will be data in the stream when calling `get_proposal_content`, I don't think it really matters when it happens. It might have make more sense to put it in the expectation to `spawn_proposal`, but I don't have access to the sender there (and keeping it here for later is too complicated I think).

In any case, once we remove the proposal manager, I plan to update the tests to use a fake block builder instead of a mock. This change will specifically make such simulations easier.
</blockquote></details>

Okay, np. What's the difference between fake and mock?
Also, are we still gonna need the block builder factory?

**Review by alonh5 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2279)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2279)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 158 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2279#-OCmcuY_48uz3WWejfna:-OD0f-IPB7R5EQsJPfyE:b-f2ebot) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3c0e523e3cc009f8e8ec1b3e7708b9830aedcea/crates/starknet_batcher/src/batcher_test.rs#L158)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Okay, np. What's the difference between fake and mock?
Also, are we still gonna need the block builder factory?
</blockquote></details>

Mocks allow you to set expectations and define return values for each call. 
Fake is an actual implementation of the trait, which I believe is more appropriate here because we want to simulate the block building process. Instead of simulating this behaviour through return value expectations, we can create a lightweight block builder that directly simulates the desired functionality.

About the factory - yes. This way we can instantiate Mock/Fake block builders instead of real ones.

**Review by alonh5 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2279)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 158 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2279#-OCmcuY_48uz3WWejfna:-OD0i1jGAD6iz-saIve5:b-8fx2u7) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3c0e523e3cc009f8e8ec1b3e7708b9830aedcea/crates/starknet_batcher/src/batcher_test.rs#L158)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Mocks allow you to set expectations and define return values for each call. 
Fake is an actual implementation of the trait, which I believe is more appropriate here because we want to simulate the block building process. Instead of simulating this behaviour through return value expectations, we can create a lightweight block builder that directly simulates the desired functionality.

About the factory - yes. This way we can instantiate Mock/Fake block builders instead of real ones.
</blockquote></details>

:+1:

**Pull request merged**
