### PR TITLE
feat: enable stateful compression versioned constant

### PR DESCRIPTION
**Pull request by yoavGrs**

### CODE REVIEW

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1836)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1836#-OAwVgJ43ZamNBRT9mJ6:-OAwVgJ43ZamNBRT9mJ7:b4f2ajp) (no related file):*
The python side
https://reviewable.io/reviews/starkware-industries/starkware/36170

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1836)* status: all files reviewed, 2 unresolved discussions (waiting on @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1836#-OAw_mib7mUVGxbdvc67:-OAw_mib7mUVGxbdvc68:b-hxhyj) (no related file):*
please rebase (we now have 0.13.4 VC), and set the flag to `true` in the 0.13.4 VC

___

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1836)* status: all files reviewed, 2 unresolved discussions (waiting on @yoavGrs)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1836)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1836#-OAw_mib7mUVGxbdvc67:-OAwbT__43UysrsRjdvw:b-896fix) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please rebase (we now have 0.13.4 VC), and set the flag to `true` in the 0.13.4 VC
</blockquote></details>

Done.

___

**Review by nimrod-starkware — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1836)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

**Pull request merged**
