### PR TITLE
feat(blockifier): explicit names for versioned constants JSONs

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/998)

### CODE REVIEW

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/998#-:-O7ZhdKA6wTMC3o_Qztf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/998)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/998)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 878 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/998#-O7ifcMa2Tfcwn2uCyCm:-O7ifcMb8JsBt2Hr8mEk:b6o22oz) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0b54aaa2e9c2b17c0773cb889ab7ee3b1b3ae6b/crates/papyrus_execution/src/lib.rs#L878)):*
> ```XML
>             VersionedConstants::get(blockifier_starknet_version)
>         }
>         None => VersionedConstants::latest_constants(),
> ```

Why do they need this arm? they take the latest if there is no match.
So either remove it or check v0_13_3 explicitly

(also, they are missing 0.13.1.1 and 0.13.2.1... a safer way is to assert that the given version is > than the last supported. but non-blocking since it's out of scope)



_Code quote:_
```XML
            } else {
                BlockifierStarknetVersion::V0_13_3
            };
            VersionedConstants::get(blockifier_starknet_version)
        }
        None => VersionedConstants::latest_constants(),
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/998)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @dorimedini-starkware, and @ShahakShama)

___
*[`crates/papyrus_execution/src/lib.rs` line 878 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/998#-O7ifcMa2Tfcwn2uCyCm:-O7isCvJ5c1H1PDgUjCm:b2o1isp) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0b54aaa2e9c2b17c0773cb889ab7ee3b1b3ae6b/crates/papyrus_execution/src/lib.rs#L878)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why do they need this arm? they take the latest if there is no match.
So either remove it or check v0_13_3 explicitly

(also, they are missing 0.13.1.1 and 0.13.2.1... a safer way is to assert that the given version is > than the last supported. but non-blocking since it's out of scope)
</blockquote></details>

main Q is why are there two different structs?
@ShahakShama or @dan-starkware PTAL at this: looks like you should be using the blockifier StarknetVersion enum instead of strings

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/998)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @dorimedini-starkware, and @ShahakShama)

___
*[`crates/papyrus_execution/src/lib.rs` line 878 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/998#-O7ifcMa2Tfcwn2uCyCm:-O7weoQYDChIdasn7lRs:b-qe46hu) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0b54aaa2e9c2b17c0773cb889ab7ee3b1b3ae6b/crates/papyrus_execution/src/lib.rs#L878)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

main Q is why are there two different structs?
@ShahakShama or @dan-starkware PTAL at this: looks like you should be using the blockifier StarknetVersion enum instead of strings
</blockquote></details>

[item](https://starkware.monday.com/boards/6987445459/pulses/7524892471) to track this issue, following [this](https://starkwareindustries.slack.com/archives/C07P3RYQ571/p1727590500832319) conversation

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/998)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/998)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
