### PR TITLE
feat(cairo_native): use contract class manager in papyrus reader

### PR DESCRIPTION
**Pull request by avi-starkware**
- **feat(cairo_native): use contract class manager in papyrus reader**

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2738)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @alonh5, @avi-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-OENXOvX4H77o_cgF4Lg:-OENXOvX4H77o_cgF4Lh:b-qh91af) ([raw file](https://github.com/starkware-libs/sequencer/blob/0edeedd166751ce49bde0b3ac3bfaec505fea1bd/crates/blockifier/src/state/contract_class_manager.rs#L60)):*
> ```XML
>         );
>         #[cfg(feature = "cairo_native")]
>         {
> ```

Consider adding an assert verifying that `config.run_cairo_native` is set to true only if the native feature is on.



_Code quote:_
```XML
        #[cfg(not(feature = "cairo_native"))]
        unimplemented!(
            "Native compilation cannot be enabled when the cairo_native feature is turned off."
        );
        #[cfg(feature = "cairo_native")]
        {
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 368 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-OEO9HO0DwBL9kvwtG8H:-OEO9HO0DwBL9kvwtG8I:b-2pqvs8) ([raw file](https://github.com/starkware-libs/sequencer/blob/0edeedd166751ce49bde0b3ac3bfaec505fea1bd/crates/native_blockifier/src/py_block_executor.rs#L368)):*
> ```XML
>         // Clear global class cache, to properly revert classes declared in the reverted block.
>         // TODO(Avi, 01/01/2025): Consider what exactly to clear in native compilation context.
>         self.contract_class_manager.clear();
> ```

I think that we will want to clear everything, given that we first check the native cache. 



_Code quote:_
```XML
        // TODO(Avi, 01/01/2025): Consider what exactly to clear in native compilation context.
        self.contract_class_manager.clear();
```
___
*[`crates/blockifier/src/state/global_cache.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-OEO8_bGCnJCfnIcnJET:-OEO8_bH7HTtyJ7r2z2s:b-7zi8ni) ([raw file](https://github.com/starkware-libs/sequencer/blob/0edeedd166751ce49bde0b3ac3bfaec505fea1bd/crates/blockifier/src/state/global_cache.rs#L56)):*
> ```XML
> 
> pub struct ContractCaches {
>     pub casm_cache: GlobalContractCache<VersionedRunnableCompiledClass>,
> ```

WDYT?



_Suggestion:_
```XML
pub compiled_class_cache: GlobalContractCache<VersionedRunnableCompiledClass>,
```
___
*[`crates/blockifier/src/state/global_cache.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-OEO8u-w6o0Bq78cfhPp:-OEO8u-w6o0Bq78cfhPq:bxbas8) ([raw file](https://github.com/starkware-libs/sequencer/blob/0edeedd166751ce49bde0b3ac3bfaec505fea1bd/crates/blockifier/src/state/global_cache.rs#L58)):*
> ```XML
>     pub casm_cache: GlobalContractCache<VersionedRunnableCompiledClass>,
>     #[cfg(feature = "cairo_native")]
>     pub native_cache: GlobalContractCache<CachedCairoNative>,
> ```

Consider defining this field last



_Code quote:_
```XML
    #[cfg(feature = "cairo_native")]
    pub native_cache: GlobalContractCache<CachedCairoNative>,
```

**Review by noaov1 — APPROVED** [review]
> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2738)* status: all files reviewed, 6 unresolved discussions (waiting on @alonh5, @avi-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/global_cache.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-OEO8u-w6o0Bq78cfhPp:-OEOhpKk1sYASjngTk3f:b-rag2pl) ([raw file](https://github.com/starkware-libs/sequencer/blob/0edeedd166751ce49bde0b3ac3bfaec505fea1bd/crates/blockifier/src/state/global_cache.rs#L58)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider defining this field last
</blockquote></details>

On second though, as we discussed, we don't need the sierra as well, so you can leave it in this order
___
*[`crates/starknet_batcher/src/batcher.rs` line 449 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-OEOgqfC8hTFLI9AWm7w:-OEOgqfC8hTFLI9AWm7x:b3kre) ([raw file](https://github.com/starkware-libs/sequencer/blob/0edeedd166751ce49bde0b3ac3bfaec505fea1bd/crates/starknet_batcher/src/batcher.rs#L449)):*
> ```XML
>         wait_on_native_compilation: false,
>         contract_cache_size: config.global_contract_cache_size,
>     };
> ```

?



_Suggestion:_
```XML
    let contract_class_manager_config = ContractClassManagerConfig::default();
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 437 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-OEOgN6-9OU1ILNIKQd2:-OEOgN60E36qj6ZZ0FMC:b3kre) ([raw file](https://github.com/starkware-libs/sequencer/blob/0edeedd166751ce49bde0b3ac3bfaec505fea1bd/crates/native_blockifier/src/py_block_executor.rs#L437)):*
> ```XML
>             wait_on_native_compilation: false,
>             contract_cache_size: GLOBAL_CONTRACT_CACHE_SIZE_FOR_TEST,
>         };
> ```

?



_Suggestion:_
```XML
        let contract_class_manager_config = ContractClassManagerConfig::default();
```

**Review by meship-starkware — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2738)* status: all files reviewed, 6 unresolved discussions (waiting on @alonh5, @avi-starkware, and @Yoni-Starkware)

**Comment by avi-starkware** [comment]
*[`crates/native_blockifier/src/py_block_executor.rs` line 368 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-OEO9HO0DwBL9kvwtG8H:-OEOxJvY89iFZ3BFm8nO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0edeedd166751ce49bde0b3ac3bfaec505fea1bd/crates/native_blockifier/src/py_block_executor.rs#L368)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think that we will want to clear everything, given that we first check the native cache.
</blockquote></details>

Done.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2738)* status: 1 of 10 files reviewed, 3 unresolved discussions (waiting on @alonh5, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-OENXOvX4H77o_cgF4Lg:-OEOwhRv-tOBHc43Ld-k:bb8yctb) ([raw file](https://github.com/starkware-libs/sequencer/blob/0edeedd166751ce49bde0b3ac3bfaec505fea1bd/crates/blockifier/src/state/contract_class_manager.rs#L60)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider adding an assert verifying that `config.run_cairo_native` is set to true only if the native feature is on.
</blockquote></details>

I just made it impossible to run the compilation thread if the feature flag is turned off.
That is, `config.run_cairo_native` does nothing in that case.
___
*[`crates/blockifier/src/state/global_cache.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-OEO8_bGCnJCfnIcnJET:-OEOwznM70Yf8b7reEwE:b-zeb5wy) ([raw file](https://github.com/starkware-libs/sequencer/blob/0edeedd166751ce49bde0b3ac3bfaec505fea1bd/crates/blockifier/src/state/global_cache.rs#L56)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

I think this makes it more ambiguous because the native cache also contains compiled classes.
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 437 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-OEOgN6-9OU1ILNIKQd2:-OEOzZDnB2wP-Ph_fHE6:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0edeedd166751ce49bde0b3ac3bfaec505fea1bd/crates/native_blockifier/src/py_block_executor.rs#L437)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r2, 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2738)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 446 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-OEP2W5JBnokX8ZVnBiG:-OEP2W5KEJpXTSo0Kt-m:b-vbxvic) ([raw file](https://github.com/starkware-libs/sequencer/blob/2785713e2ae46e741e781bc17b3d90e9cc04d5ee/crates/starknet_batcher/src/batcher.rs#L446)):*
> ```XML
>         block_builder_config: config.block_builder_config.clone(),
>         storage_reader: storage_reader.clone(),
>         contract_class_manager: ContractClassManager::start(
> ```

Didn't we say it can be configurable and we don't have to run the thread here?



_Code quote:_
```XML
start(
```

**Comment by avi-starkware** [comment]
*[`crates/starknet_batcher/src/batcher.rs` line 446 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-OEP2W5JBnokX8ZVnBiG:-OEP38Og05JGue5UqdQx:b-cdpvyb) ([raw file](https://github.com/starkware-libs/sequencer/blob/2785713e2ae46e741e781bc17b3d90e9cc04d5ee/crates/starknet_batcher/src/batcher.rs#L446)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Didn't we say it can be configurable and we don't have to run the thread here?
</blockquote></details>

Yes. The thread doesn't run if the config `run_cairo_native` is `false` (which is the default).
Moreover, the thread doesn't run without the `cairo_native` feature flag (which you don't even have in the `starknet_batcher` crate)

**Comment by avi-starkware** [comment]
*[`crates/starknet_batcher/src/batcher.rs` line 449 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-OEOgqfC8hTFLI9AWm7w:-OEP3fsYD1pS78tVw0Iq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0edeedd166751ce49bde0b3ac3bfaec505fea1bd/crates/starknet_batcher/src/batcher.rs#L449)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2738)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 446 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-OEP2W5JBnokX8ZVnBiG:-OEP707U84omZ7ojuK_A:b-h8u30q) ([raw file](https://github.com/starkware-libs/sequencer/blob/2785713e2ae46e741e781bc17b3d90e9cc04d5ee/crates/starknet_batcher/src/batcher.rs#L446)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Yes. The thread doesn't run if the config `run_cairo_native` is `false` (which is the default).
Moreover, the thread doesn't run without the `cairo_native` feature flag (which you don't even have in the `starknet_batcher` crate)
</blockquote></details>

Oh okay, the documentation confused me.
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 63 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-OEP6gLm5fRy2PbDRVAC:-OEP6gLm5fRy2PbDRVAD:buo29mt) ([raw file](https://github.com/starkware-libs/sequencer/blob/2785713e2ae46e741e781bc17b3d90e9cc04d5ee/crates/blockifier/src/state/contract_class_manager.rs#L63)):*
> ```XML
>     /// Creates a new contract class manager and spawns a thread that listens for compilation
>     /// requests and processes them (a.k.a. the compilation worker).
>     /// Returns the contract class manager.
> ```

Move docstring over `#[cfg(feature = "cairo_native")]` or edit it to match both.



_Code quote:_
```XML
    /// Creates a new contract class manager and spawns a thread that listens for compilation
    /// requests and processes them (a.k.a. the compilation worker).
    /// Returns the contract class manager.
```

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 9 files at r2, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-:-OEPHuS0AZW6_8Z1MJ8L:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 143 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-OEPHJDc4zfQycbDLlTQ:-OEPHJDd6V0nwtwoAenB:b-pfjv16) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b886a9417365fb6038b3df6867f69f44eaac5f4/crates/blockifier/src/state/contract_class_manager.rs#L143)):*
> ```XML
>         let (class_hash, sierra, casm) = request.clone();
>         let sierra_version = SierraVersion::extract_from_program(&sierra.sierra_program).unwrap();
>         self.contract_caches.set_sierra(class_hash, sierra);
> ```

Do we want to cache the sierra if `config.run_cairo_native = false`?



_Code quote:_
```XML
        self.contract_caches.set_sierra(class_hash, sierra);
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/state/contract_class_manager.rs` line 63 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-OEP6gLm5fRy2PbDRVAC:-OEPMd1k9xLJF7Pdwa72:b-o43ham) ([raw file](https://github.com/starkware-libs/sequencer/blob/2785713e2ae46e741e781bc17b3d90e9cc04d5ee/crates/blockifier/src/state/contract_class_manager.rs#L63)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Move docstring over `#[cfg(feature = "cairo_native")]` or edit it to match both.
</blockquote></details>

Done.
PTAL

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2738)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 143 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2738#-OEPHJDc4zfQycbDLlTQ:-OEPJb-F0BWddSUs0-I9:b-xjs16w) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b886a9417365fb6038b3df6867f69f44eaac5f4/crates/blockifier/src/state/contract_class_manager.rs#L143)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do we want to cache the sierra if `config.run_cairo_native = false`?
</blockquote></details>

Note that this function is called inside `send_compilation_request` after an assert that the `run_cairo_native` config is turned on, so we aren't supposed to reach this line if the flag is off.

If we just consider the `cache_request_contracts` individually, I think we still want to cache the sierra since the function is supposed to cache the entire request. That is, if some other flow would use compilation requests (which include both sierra and casm) and wants to cache the request contracts it makes sense to cache the sierra, since without caching it the sierra would have to be fetched from the state the next time a compilation request would be constructed for that class.

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 6 of 9 files at r2, 3 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2738)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @meship-starkware, @noaov1, and @Yoni-Starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2738)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware and @Yoni-Starkware)

**Pull request merged**
