### PR TITLE
chore(blockifier): add EventSummary to ExecutionSummary

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1024)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1024)* status: all files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/call_info.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1024#-O7hIxwEDoEKaJZ-FJD7:-O7hIxwEDoEKaJZ-FJD8:bon64lw) ([raw file](https://github.com/starkware-libs/sequencer/blob/4267bb2537673c1a1de757a0cd7414bab0111cca/crates/blockifier/src/execution/call_info.rs#L92)):*
> ```XML
> }
> 
> #[cfg_attr(feature = "transaction_serde", derive(Serialize, serde::Deserialize))]
> ```

why is one serde trait imported and the other given with explicit path? please be consistent



_Code quote:_
```XML
derive(Serialize, serde::Deserialize))
```
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1024#-O7hJLZl6u8OKufcPnbF:-O7hJLZl6u8OKufcPnbG:b-ogigkc) ([raw file](https://github.com/starkware-libs/sequencer/blob/4267bb2537673c1a1de757a0cd7414bab0111cca/crates/blockifier/src/transaction/objects_test.rs#L220)):*
> ```XML
>                 + fee_transfer_params.num_of_events,
>             total_event_keys: 0,
>             total_event_data_size: 0,
> ```

why do you expect these to be zero? n_events is taken from the 3 execution phases, shouldn't you check keys and data from them as well?



_Code quote:_
```XML
            total_event_keys: 0,
            total_event_data_size: 0,
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1024)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/call_info.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1024#-O7hIxwEDoEKaJZ-FJD7:-O7hNeJL9Ymx-1-OlRrL:b93roke) ([raw file](https://github.com/starkware-libs/sequencer/blob/4267bb2537673c1a1de757a0cd7414bab0111cca/crates/blockifier/src/execution/call_info.rs#L92)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is one serde trait imported and the other given with explicit path? please be consistent
</blockquote></details>

Copy-paste from other objects.
Apparently, the compiler thinks it is unused. Let's fix all of them in another PR 
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1024#-O7hJLZl6u8OKufcPnbF:-O7hNpofCnp2ZckIkv7w:b-djp2ev) ([raw file](https://github.com/starkware-libs/sequencer/blob/4267bb2537673c1a1de757a0cd7414bab0111cca/crates/blockifier/src/transaction/objects_test.rs#L220)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do you expect these to be zero? n_events is taken from the 3 execution phases, shouldn't you check keys and data from them as well?
</blockquote></details>

This specific test builds the events with no data

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1024)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/call_info.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1024#-O7hIxwEDoEKaJZ-FJD7:-O7hQ4iJ4eDg-FtJBmgO:b-kak4p1) ([raw file](https://github.com/starkware-libs/sequencer/blob/4267bb2537673c1a1de757a0cd7414bab0111cca/crates/blockifier/src/execution/call_info.rs#L92)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Copy-paste from other objects.
Apparently, the compiler thinks it is unused. Let's fix all of them in another PR
</blockquote></details>

this makes sense; in that case please change `Serialize` to `serde::Serialize`,
or, add this at the top:
```
#[cfg(feature = "transaction_serde")]
use serde::Deserialize;
```
(I prefer option 1)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1024)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/call_info.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1024#-O7hIxwEDoEKaJZ-FJD7:-O7hfs_Z7xBsqAInyHkV:b-c4gewl) ([raw file](https://github.com/starkware-libs/sequencer/blob/4267bb2537673c1a1de757a0cd7414bab0111cca/crates/blockifier/src/execution/call_info.rs#L92)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this makes sense; in that case please change `Serialize` to `serde::Serialize`,
or, add this at the top:
```
#[cfg(feature = "transaction_serde")]
use serde::Deserialize;
```
(I prefer option 1)
</blockquote></details>

Done here: https://github.com/starkware-libs/sequencer/pull/1043
(will update that PR once this one is merged)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1024#-:-O7hwNXc7nu7XvrGlMlk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
