### PR TITLE
test(mempool): rename assert mempool content to assert pool and queue

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/560)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/560)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/560#-O4u46wP9xh-W200LV21:-O4u46wP9xh-W200LV22:b4tiab5) (no related file):*
I suddenly wonder if we'd ever need the "full" content object. 
What did you have in mind?

___
___
*[`crates/mempool/src/mempool_test.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/560#-O4u3wca8emxTGgHYY1r:-O4u3wca8emxTGgHYY1s:bsvhi1w) ([raw file](https://github.com/starkware-libs/sequencer/blob/36c18bc8afbd22f794982e77ec26704501bdca5e/crates/mempool/src/mempool_test.rs#L81)):*
> ```XML
> 
>     // Note that this function currently represents a full state. It's a preliminary step;
>     // account nonces will be added to the mempool, making it a partial state.
> ```

Move to be a comment in the PR, instead of in the code.



_Code quote:_
```XML
    // Note that this function currently represents a full state. It's a preliminary step;
    // account nonces will be added to the mempool, making it a partial state.
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/560)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/560#-O4u46wP9xh-W200LV21:-O4uI_jX1AMCZZW2LlEa:b-espub3) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I suddenly wonder if we'd ever need the "full" content object. 
What did you have in mind?
</blockquote></details>

Although we're not using it now, should we consider writing a flow test that checks all fields?

___

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/560)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/560#-O4uKcC61UIes6k2RzPv:-O4uKcC61UIes6k2RzPw:b-mtej0a) (no related file):*
Note that `with_pool_and_queue` function currently represents a full state. 
It's a preliminary step.
account nonces will be added to the mempool, making it a partial state.
#534 

___

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/560)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/560#-O58bWIv8K8iWcTt-xpH:-O58bWIv8K8iWcTt-xpI:b8fpsmy) ([raw file](https://github.com/starkware-libs/sequencer/blob/79a8b457ed652d15253d92ad438448f0e2874ccc/crates/mempool/src/mempool_test.rs#L97)):*
> ```XML
>         self.assert_eq_pool_content(mempool);
>         self.assert_eq_queue_content(mempool);
>     }
> ```

Can you add TODO here? to add the account nonces.



_Code quote:_
```XML
    fn _assert_eq_mempool_content(&self, mempool: &Mempool) {
        self.assert_eq_pool_content(mempool);
        self.assert_eq_queue_content(mempool);
    }
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/560)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/560#-O58bWIv8K8iWcTt-xpH:-O5CNTYaBqdOtWpg-mR1:b-hf7p80) ([raw file](https://github.com/starkware-libs/sequencer/blob/79a8b457ed652d15253d92ad438448f0e2874ccc/crates/mempool/src/mempool_test.rs#L97)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can you add TODO here? to add the account nonces.
</blockquote></details>

I added a comment in the code, but Elin requested that it be included as a comment in this PR instead.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/560)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/560#-O4u46wP9xh-W200LV21:-O5Ci-c8BrbpB9QD6wDN:bpf2wcq) (no related file):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Although we're not using it now, should we consider writing a flow test that checks all fields?
</blockquote></details>

Deleted. Will be re-added in the future if necessary.

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/560#-O5ChV13-kh9y_TT-WXt:-O5ChV14Adt9EznWJV6y:b-9e25hj) (no related file):*
STACK OF PRS:
1. #590 
2. #560 (YOU'RE HERE)
3. #591 
4. #592 
5. #534

___

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/560)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/560#-:-O5HsK430nigjWrgfth5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Pull request merged**
