### PR TITLE
feat: add contract address in range validation

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1799?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1799** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1799?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1798** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1798?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1790** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1790?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1799)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 458 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1799#-OArrar6EZS9bDEUHMHZ:-OArrar6EZS9bDEUHMH_:b-xutpys) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed42197a649abef4bdca147bcc29f5c28fa37160/crates/gateway/src/stateless_transaction_validator_test.rs#L458)):*
> ```XML
> #[case::contract_address_upper_bound(
>     contract_address!("7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00")
> )]
> ```

Let's leave only these two.



_Code quote:_
```XML
#[case::contract_address_1(contract_address!(1_u32))]
#[case::contract_address_upper_bound(
    contract_address!("7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00")
)]
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1799)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 458 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1799#-OArrar6EZS9bDEUHMHZ:-OAsV16a9Lj8TdPfnlPt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed42197a649abef4bdca147bcc29f5c28fa37160/crates/gateway/src/stateless_transaction_validator_test.rs#L458)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Let's leave only these two.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1799#-:-OAvL9EM1ziCpXGS2kqM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Nov 5, 3:13 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1799).

**Pull request merged**
