### PR TITLE
feat(blockifier): add `NativeSyscallHandler`

### PR DESCRIPTION
**Pull request by rodrigo-pino**
Recration of #1157 targeting Main

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1240)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1240)* status: 2 of 5 files reviewed, all discussions resolved

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1240)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/utils.rs` line 22 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1240#-O8kuxaX2c0jD-2MqKJJ:-O8kuxaY6WS5YkyX4hXL:b-kexquv) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9d7c2aeff5eb656dd0dd39c54420f554ed0da9f/crates/blockifier/src/execution/native/utils.rs#L22)):*
> ```XML
>         encoding[i] = Felt::from_bytes_be(&chunk);
>     }
>     encoding
> ```

The `chunks` are of size 31 (as well as `data_chunk`.
`chunk` is of size 32.
We write at indices 1-31 the value of `data_chunk` as the MSB no?
It's different than what we do in the constants messages, right?



_Suggestion:_
```XML
    let data = msg.as_bytes().chunks(CHUNK_SIZE - 1);
    let mut encoding = vec![];
    for data_chunk in data.iter() {
        let mut chunk = [0_u8; CHUNK_SIZE];
        chunk[1..data_chunk.len() + 1].copy_from_slice(data_chunk);
        encoding.push(Felt::from_bytes_be(&chunk));
    }
    encoding
```
___
*[`crates/blockifier/src/execution/native/utils.rs` line 27 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1240#-O8l6wWzC0Q1btlyN_AU:-O8l6wWzC0Q1btlyN_AV:btue4vh) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9d7c2aeff5eb656dd0dd39c54420f554ed0da9f/crates/blockifier/src/execution/native/utils.rs#L27)):*
> ```XML
> // Todo(rodrigo): This is an opinionated way of interpretting error messages. It's ok for now but I
> // think it can be improved; (for example) trying to make the output similar to a Cairo VM panic
> pub fn decode_felts_as_str(encoding: &[Felt]) -> String {
> ```

When will it be used?



_Code quote:_
```XML
pub fn decode_felts_as_str(encoding: &[Felt]) -> String {
```

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1240)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/native/utils.rs` line 22 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1240#-O8kuxaX2c0jD-2MqKJJ:-O8lEDDEBQhM1FP8dkdM:b-dqrpap) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9d7c2aeff5eb656dd0dd39c54420f554ed0da9f/crates/blockifier/src/execution/native/utils.rs#L22)):*
> We write at indices 1-31 the value of `data_chunk` as the MSB no?
> It's different than what we do in the constants messages, right?

I'd have to dive a bit deep in the code to answer a 100% sure but I think is not. Both messages are encoded in the same fashion as your error messages. When they get decoded during execution we don't see any word being reversed :thinking: 
___
*[`crates/blockifier/src/execution/native/utils.rs` line 27 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1240#-O8l6wWzC0Q1btlyN_AU:-O8l9SNk1HM1mmT7Gwhb:b9jzh8o) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9d7c2aeff5eb656dd0dd39c54420f554ed0da9f/crates/blockifier/src/execution/native/utils.rs#L27)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

When will it be used?
</blockquote></details>

When outputting the final error message, after Cairo Native returned control if there was a failure, the message is contained in a `Vec<Felt>`

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1240)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/utils.rs` line 22 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1240#-O8kuxaX2c0jD-2MqKJJ:-O8lEYn73cvDaz00RclQ:byp8x7k) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9d7c2aeff5eb656dd0dd39c54420f554ed0da9f/crates/blockifier/src/execution/native/utils.rs#L22)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

> We write at indices 1-31 the value of `data_chunk` as the MSB no?
> It's different than what we do in the constants messages, right?

I'd have to dive a bit deep in the code to answer a 100% sure but I think is not. Both messages are encoded in the same fashion as your error messages. When they get decoded during execution we don't see any word being reversed :thinking:
</blockquote></details>

I tried to decode it and it seems to result with the same "Out of gas" message. I guess it's because you remove the 0's (in prefix and suffix). Makes sense?
___
*[`crates/blockifier/src/execution/native/utils.rs` line 34 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1240#-O8lHUUc08B9GRqmwIcz:-O8lHUUc08B9GRqmwId-:b-3qejc) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9d7c2aeff5eb656dd0dd39c54420f554ed0da9f/crates/blockifier/src/execution/native/utils.rs#L34)):*
> ```XML
>         // If the string is utf8 make sure it is not prefixed by no null chars. Null chars in
>         // between can still happen
>         Ok(s) => s.trim_matches('\0').to_owned(),
> ```

Can it be problematic? Consider the error message: "Not supporting Cairo 0". It's hex is "4E 6F 74 20 73 75 70 70 6F 72 74 69 6E 67 20 43 61 69 72 6F 20 30", so trimming the last zero can be problematic.



_Code quote:_
```XML
Ok(s) => s.trim_matches('\0').to_owned(),
```

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1240)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @rodrigo-pino)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1240)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @meship-starkware, @PearsonWhite, and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/utils.rs` line 34 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1240#-O8lHUUc08B9GRqmwIcz:-O8ms-Ac56MHYqO0DmP2:b-j37jp7) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9d7c2aeff5eb656dd0dd39c54420f554ed0da9f/crates/blockifier/src/execution/native/utils.rs#L34)):*
<details><summary><i>Previously, PearsonWhite wrote…</i></summary><blockquote>

I don't think this will match unicode 0s. I can't reproduce an error with the test string "Not supporting Cairo 0" in "test_encode_decode_str".
</blockquote></details>

You are right :)

**Review by meship-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1240)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @PearsonWhite and @rodrigo-pino)

**Review by meship-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1240#-:-O8qm8ooD7-lkASERgFB:bnfp4nl)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @PearsonWhite and @rodrigo-pino)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1240)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @PearsonWhite)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1240)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PearsonWhite)

**Pull request merged**
