### PR TITLE
chore(batcher): add next_block_info method to block builder factory

### PR DESCRIPTION
**Pull request by ArniStarkware**
Refactor towards getting block info from consensus.

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2231?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2231** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2231?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2231?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2230** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2230?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2231)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5, @ArniStarkware, and @dafnamatsry)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 319 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2231#-OCRpO1t4k6UtN5L5F4A:-OCRpO1t4k6UtN5L5F4B:bbx73dp) ([raw file](https://github.com/starkware-libs/sequencer/blob/399450373183b221803303f4a1522e94afbbcf85/crates/starknet_batcher/src/block_builder.rs#L319)):*
> ```XML
>     ) -> BlockBuilderResult<TransactionExecutor<PapyrusReader>> {
>         let block_builder_config = self.block_builder_config.clone();
>         // TODO(Arni): Get as a parameter for this function.
> ```

why no take the block number as you did here?



_Code quote:_
```XML
// TODO(Arni): Get as a parameter for this function.
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2231)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 319 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2231#-OCRpO1t4k6UtN5L5F4A:-OCRqCDD-oLn6iT-WBHP:b2pblkr) ([raw file](https://github.com/starkware-libs/sequencer/blob/78e3a013c2b5969e12beedd34c86dd867d8be57f/crates/starknet_batcher/src/block_builder.rs#L319)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why no take the block number as you did here?
</blockquote></details>

This TODO is no longer relevant. I should removed it.
I don't want to pass the `height` separately, as it is a part of the `block_info`.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2231)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 302 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2231#-OCRtXxz12DKo5h23uUD:-OCRubQt5NHsxNkY2rT1:bamqp1n) ([raw file](https://github.com/starkware-libs/sequencer/blob/58aa988ae2a71565bff59b91c75f0f29aa0e3312/crates/starknet_batcher/src/block_builder.rs#L302)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

if you remove this error, you also need to remove it from the error types.
</blockquote></details>

Now not using `unwrap()` in production code.
Done.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2231)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5 and @dafnamatsry)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2231)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2231#-OCTl6ks62lz5IJi61YI:-OCTl6ks62lz5IJi61YJ:b3qm4lr) (no related file):*
Also no need for this intermediate PR. I'm having trouble keeping track. Above PR #2246 there could be one PR passing the block info from the consensus in the input (which is PR #2237 with some additions).

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2231)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5, @dafnamatsry, and @Yael-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2231#-OCTl6ks62lz5IJi61YI:-OCXPnRPCaLqjgGwJ5td:bl4mjeb) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Also no need for this intermediate PR. I'm having trouble keeping track. Above PR #2246 there could be one PR passing the block info from the consensus in the input (which is PR #2237 with some additions).
</blockquote></details>

This PR is indeed no longer relevant.

**Pull request closed without merging**
