### PR TITLE
feat(consensus): add locked_value to sm

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/733)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/733)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/733#-O6p8gnB0T3UWnkIMD6I):*
Split this into 2 separate PRs please. 



_Code quote:_
```
- f0b06ce: feat(consensus): add locked_value to sm and valid_round to proposal
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/733)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 367 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/733#-O6pGY-NBTGY9ZUBKGs2:-O6pGY-NBTGY9ZUBKGs3:b-wvd8ys) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ef6a31e79745e1490899b9118a04caae48f8073/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L367)):*
> ```XML
> 
>     wrapper.send_precommit(None, ROUND);
>     assert_eq!(wrapper.next_event().unwrap(), StateMachineEvent::TimeoutPrecommit(ROUND));
> ```

We don't need to send a pure NIL quorum. A mixed quorum is enough.



_Suggestion:_
```XML
    assert_eq!(wrapper.next_event().unwrap(), StateMachineEvent::TimeoutPrecommit(ROUND));
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/733)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 367 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/733#-O6pGY-NBTGY9ZUBKGs2:-O6pIHXXADizrgaaxGKs:by79zr5) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ef6a31e79745e1490899b9118a04caae48f8073/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L367)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

We don't need to send a pure NIL quorum. A mixed quorum is enough.
</blockquote></details>

we want NIL quorum to advance to the next round

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/733)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/733)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
