### PR TITLE
fix(blockifier_reexecution): remove double error redirect

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1398)

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1398#-:-O9A8O2w-8g3CgnYcIi8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1398)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/serde_utils.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1398#-O9AG-ZU84j7NH914atE:-O9AG-ZU84j7NH914atF:b-4ukffl) ([raw file](https://github.com/starkware-libs/sequencer/blob/638e7b874482c6e9578bf7e36b78593c74dcfec7/crates/blockifier_reexecution/src/state_reader/serde_utils.rs#L11)):*
> ```XML
> };
> 
> use super::test_state_reader::ReexecutionResult;
> ```

don't use `super` imports outside of test modules; use `crate::...`



_Code quote:_
```XML
use super::test_state_reader::ReexecutionResult;
```

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/state_reader/serde_utils.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1398#-O9AG-ZU84j7NH914atE:-O9AGW56-0dP_AO7xoLY:b-nvb14d) ([raw file](https://github.com/starkware-libs/sequencer/blob/638e7b874482c6e9578bf7e36b78593c74dcfec7/crates/blockifier_reexecution/src/state_reader/serde_utils.rs#L11)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't use `super` imports outside of test modules; use `crate::...`
</blockquote></details>

Done. The compiler does this by default. Do you know if there's a way to change this behaviour?

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1398#-:-O9AGyS57iwmrfyMtHW1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/serde_utils.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1398#-O9AG-ZU84j7NH914atE:-O9AGsix8tRmqsHfgBIA:b45ouoe) ([raw file](https://github.com/starkware-libs/sequencer/blob/638e7b874482c6e9578bf7e36b78593c74dcfec7/crates/blockifier_reexecution/src/state_reader/serde_utils.rs#L11)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done. The compiler does this by default. Do you know if there's a way to change this behaviour?
</blockquote></details>

the compiler? or vscode?
either way IDK, you can try searching

**Pull request merged**
