### PR TITLE
feat(batcher): modify the transaction_provider trait to support the validate flow

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1766?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1766** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1766?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1747** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1747?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Yael-Starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1766)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1766#-OAmOFMBB1pvMQQcSuwB:-OAmOFMBB1pvMQQcSuwC:b-643l78) (no related file):*
Please split changes and the renaming to the file into separate PRs. Also let's discuss the naming offline?
BTW I see the changes from the previous PR here also.

___

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1766)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @alonh5)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1766#-OAmOFMBB1pvMQQcSuwB:-OAqHJc2ERzqh0u2fnXh:b-896fix) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Please split changes and the renaming to the file into separate PRs. Also let's discuss the naming offline?
BTW I see the changes from the previous PR here also.
</blockquote></details>

Done.

___

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1766)* status: all files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 154 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1766#-OAqxZQ4DCYiNtfkBrlU:-OAqxZQ4DCYiNtfkBrlV:b-w3jqwm) ([raw file](https://github.com/starkware-libs/sequencer/blob/fda934d284e7947735cf5ba762b4b5d26ef3a72c/crates/batcher/src/block_builder.rs#L154)):*
> ```XML
>         // TODO(yael 6/10/2024): delete the timeout condition once the executor has a timeout
>         while !should_close_block && tokio::time::Instant::now() < deadline {
>             let tx_events_chunk = tx_dispatcher.get_txs(self.tx_chunk_size).await?;
> ```

Match the enum here to either break the loop or execute the txs in the existing flow (see comments below).
___
*[`crates/batcher/src/transaction_dispatcher.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1766#-OAqvMJn9IUMbEvDrlm4:-OAqvMJn9IUMbEvDrlm5:b-3l5szs) ([raw file](https://github.com/starkware-libs/sequencer/blob/fda934d284e7947735cf5ba762b4b5d26ef3a72c/crates/batcher/src/transaction_dispatcher.rs#L17)):*
> ```XML
> 
> #[derive(Debug, PartialEq)]
> pub enum TransactionEvent {
> ```

Let's think of a more inidcative name - Event is very general. Maybe NextTransactions?



_Code quote:_
```XML
TransactionEvent
```
___
*[`crates/batcher/src/transaction_dispatcher.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1766#-OAqv4ok5OUowwjr8o0c:-OAqv4ok5OUowwjr8o0d:bfao47x) ([raw file](https://github.com/starkware-libs/sequencer/blob/fda934d284e7947735cf5ba762b4b5d26ef3a72c/crates/batcher/src/transaction_dispatcher.rs#L18)):*
> ```XML
> #[derive(Debug, PartialEq)]
> pub enum TransactionEvent {
>     Transaction(Transaction),
> ```

This should be either a vector of txs or a finish signal. We don't need each tx wrapped by this enum, nor do we want the option to pass multiple finish signals or even worse - transactions and finish signals mixed together in a vector.



_Suggestion:_
```XML
Transactions(Vec<Transaction>)
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1766)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`crates/batcher/src/block_builder.rs` line 154 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1766#-OAqxZQ4DCYiNtfkBrlU:-OArdUMt2BsUeCXRvdcL:bgchb82) ([raw file](https://github.com/starkware-libs/sequencer/blob/fda934d284e7947735cf5ba762b4b5d26ef3a72c/crates/batcher/src/block_builder.rs#L154)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Match the enum here to either break the loop or execute the txs in the existing flow (see comments below).
</blockquote></details>

good suggestion, it did simplify things.
done,
___
*[`crates/batcher/src/transaction_dispatcher.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1766#-OAqvMJn9IUMbEvDrlm4:-OArdG7A53lKJWTDPd-C:b-7rl0jd) ([raw file](https://github.com/starkware-libs/sequencer/blob/fda934d284e7947735cf5ba762b4b5d26ef3a72c/crates/batcher/src/transaction_dispatcher.rs#L17)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Let's think of a more inidcative name - Event is very general. Maybe NextTransactions?
</blockquote></details>

done.
___
*[`crates/batcher/src/transaction_dispatcher.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1766#-OAqv4ok5OUowwjr8o0c:-OArdLQB1egA-itq4wcb:b3oh8n) ([raw file](https://github.com/starkware-libs/sequencer/blob/fda934d284e7947735cf5ba762b4b5d26ef3a72c/crates/batcher/src/transaction_dispatcher.rs#L18)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This should be either a vector of txs or a finish signal. We don't need each tx wrapped by this enum, nor do we want the option to pass multiple finish signals or even worse - transactions and finish signals mixed together in a vector.
</blockquote></details>


Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1766)* status: all files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 152 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1766#-OAvMOUe2gbrZE5qbK0E:-OAvMOUf8QWJXOGGyadQ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d9692844dca2cd1f9be641698cbbaa900a167db/crates/batcher/src/block_builder.rs#L152)):*
> ```XML
>         // TODO(yael 6/10/2024): delete the timeout condition once the executor has a timeout
>         while !block_is_full && tokio::time::Instant::now() < deadline {
>             let tx_stram = tx_provider.get_txs(self.tx_chunk_size).await?;
> ```





_Suggestion:_
```XML
tx_stream
```
___
*[`crates/batcher/src/transaction_provider.rs` line 13 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1766#-OAvRG116pKVBGIphte2:-OAvRG116pKVBGIphte3:bw5lyp3) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d9692844dca2cd1f9be641698cbbaa900a167db/crates/batcher/src/transaction_provider.rs#L13)):*
> ```XML
>     MempoolError(#[from] MempoolClientError),
>     #[error(transparent)]
>     ChannelSendError(#[from] tokio::sync::mpsc::error::SendError<Transaction>),
> ```

Where can this be returned?



_Code quote:_
```XML
    #[error(transparent)]
    ChannelSendError(#[from] tokio::sync::mpsc::error::SendError<Transaction>),
```
___
*[`crates/batcher/src/transaction_provider.rs` line 38 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1766#-OAvOgGX8j3sftY9TOkU:-OAvOgGX8j3sftY9TOkV:b9i3cpc) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d9692844dca2cd1f9be641698cbbaa900a167db/crates/batcher/src/transaction_provider.rs#L38)):*
> ```XML
>     Txs(Vec<Transaction>),
>     TxStreamDone,
> }
> ```

You don't like the name NextTxs? I think it's very straight forward 
It's not exactly a stream, maybe one element in a stream, but also it's an implementation detail (that isn't used in Propose).



_Suggestion:_
```XML
#[derive(Debug, PartialEq)]
pub enum NextTxs {
    Txs(Vec<Transaction>),
    End,
}
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1766)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`crates/batcher/src/block_builder.rs` line 152 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1766#-OAvMOUe2gbrZE5qbK0E:-OAv_1HNE7QCLc4QVNyA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d9692844dca2cd1f9be641698cbbaa900a167db/crates/batcher/src/block_builder.rs#L152)):*
> ```XML
>         // TODO(yael 6/10/2024): delete the timeout condition once the executor has a timeout
>         while !block_is_full && tokio::time::Instant::now() < deadline {
>             let tx_stram = tx_provider.get_txs(self.tx_chunk_size).await?;
> ```

Done.
___
*[`crates/batcher/src/transaction_provider.rs` line 13 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1766#-OAvRG116pKVBGIphte2:-OAvZx3M0xNWQHW96jTY:b-wdf6mw) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d9692844dca2cd1f9be641698cbbaa900a167db/crates/batcher/src/transaction_provider.rs#L13)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Where can this be returned?
</blockquote></details>

leftovers, deleted now.
done.
___
*[`crates/batcher/src/transaction_provider.rs` line 38 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1766#-OAvOgGX8j3sftY9TOkU:-OAvZwMf0hTIo3y5eGUU:bneli0w) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d9692844dca2cd1f9be641698cbbaa900a167db/crates/batcher/src/transaction_provider.rs#L38)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You don't like the name NextTxs? I think it's very straight forward 
It's not exactly a stream, maybe one element in a stream, but also it's an implementation detail (that isn't used in Propose).
</blockquote></details>

Done.
(also moved it to be before the trait definition)

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1766#-:-OAvfDg96Pu8085ivtNH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
