### PR TITLE
refactor(blockifier): inject VC into CallInfo::summarize

### PR DESCRIPTION
**Pull request by dorimedini-starkware**

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2122?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2123** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2123?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2122** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2122?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2122?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2121** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2121?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
I suggest a cleaner approach - don't pass the VC.
Summarize regularly, and if the flag is on, drop the event summary and calc it again on validate & execute call infos.

Also, this should not affect the bouncer.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2122#-:-OBzKCbd-Mw4Yr7HQ3Q-:b-dy54ss)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
1. why is this cleaner? replacing an already-calculated object with another seems jumbled
2. this will have no effect on the bouncer because this will have no effect on post-0.13.1 blocks; you are saying, it is worth adding code to ensure the 0.13.1 bouncer still gets "correct" event counting, and only the fee computation should be effected?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2122#-:-OBznXYl0eXiJhv-gZVF:b2bl7a)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
2. No, I say, if we don't pass the VC, you don't need to fix the calc for the bouncer, just for the fee calc.
1. It is more local and framed. Doesn't require passing another argument to many places just for this. I prefer not to have this hack in call_info.summarize()

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2122#-:-OC-KXKg5xAlxsy8mrTQ:b-47o6wf)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> No, I say, if we don't pass the VC, you don't need to fix the calc for the bouncer, just for the fee calc.

why would we want to fix this for the bouncer at all? bouncer is irrelevant for reexecution, and we should not support "no inner event charge" mode in latest sequencer version, right?

> It is more local and framed. Doesn't require passing another argument to many places just for this.

where would we get the callinfos from...? (above question)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2122#-:-OC-eLFMB3gyP1wwW5gb:bgs2kvh)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 10 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2122#-:-OC3KuFADTzeFnQkhT0q:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Nov 19, 7:52 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2122).

**Pull request merged**
