### PR TITLE
chore(blockifier): add new constructor to AccountTransaction

### PR DESCRIPTION
**Pull request by avivg-starkware**

### CODE REVIEW

**Comment by avivg-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2431?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2431** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2431?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2431?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2429** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2429?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2428** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2428?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2354](https://github.com/starkware-libs/sequencer/pull/2354) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2354?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2412** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2412?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2377** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2377?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2331** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2331?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2431)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 143 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2431#-ODH742X4FlIA0kIegIW:-ODLBqn44ku2azvsqUrx:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/126a0c7526abbce9fc5cd3f7a66b1121515a771a/crates/blockifier/src/transaction/account_transaction.rs#L143)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

It seems like there is only one place that needs this flag. So better to remove it.

Also, don't use `default` here - for readability.
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 132 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2431#-ODH70570gKF_9020YZ-:-ODLAujLE5vxuzBQS-7J:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/126a0c7526abbce9fc5cd3f7a66b1121515a771a/crates/blockifier/src/transaction/account_transaction.rs#L132)):*
> ```XML
>     );
> 
>     pub fn new(tx: Transaction) -> Self {
> ```

Done

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2431#-:-ODLQUcl9HP6depg7rLW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Review by avivg-starkware — COMMENTED** [review]
> Reviewed 7 of 11 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2431)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Pull request merged**
