### PR TITLE
feat(blockifier): compute allocation cost

### PR DESCRIPTION
**Pull request by yoavGrs**

### CODE REVIEW

**Comment by yoavGrs** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2301?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2301** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2301?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2301?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2300** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2300?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2293** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2293?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2150** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2150?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2175** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2175?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2149** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2149?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2200** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2200?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2301)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/fee/resources.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2301#-OCgyq8ZC2J785nqQRLZ:-OCgyq8ZC2J785nqQRL_:b-qiepw8) ([raw file](https://github.com/starkware-libs/sequencer/blob/1ba2b81bbd7b367e781240149c543907662b2132/crates/blockifier/src/fee/resources.rs#L206)):*
> ```XML
>                  to {da_gas_cost:?}",
>             )
>         })
> ```

Do we want to panic in that case? Isn't it better to return something like `GasVector::MAX`?



_Code quote:_
```XML
    pub fn to_gas_vector(&self, use_kzg_da: bool, allocation_cost: &AllocationCost) -> GasVector {
        let n_allocated_keys = self.state_changes_for_fee.n_allocated_keys;
        let allocation_gas_vector = allocation_cost.get_cost(use_kzg_da);
        let total_allocation_cost =
            allocation_gas_vector.checked_mul(n_allocated_keys).unwrap_or_else(|| {
                panic!(
                    "State resources to gas vector overflowed: tried to multiply \
                     {allocation_gas_vector:?} by {n_allocated_keys:?}",
                )
            });
        let da_gas_cost =
            get_da_gas_cost(&self.state_changes_for_fee.state_changes_count, use_kzg_da);
        total_allocation_cost.checked_add(da_gas_cost).unwrap_or_else(|| {
            panic!(
                "State resources to gas vector overflowed: tried to add {total_allocation_cost:?} \
                 to {da_gas_cost:?}",
            )
        })
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2308 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2301#-OCgybzTEOPnw_3ebkaX:-OCgybzUDbNoAK5gMgS9:b7q2tqo) ([raw file](https://github.com/starkware-libs/sequencer/blob/1ba2b81bbd7b367e781240149c543907662b2132/crates/blockifier/src/transaction/transactions_test.rs#L2308)):*
> ```XML
>         true => GasVector::from_l1_data_gas(160_u32.into()),
>         false => GasVector::from_l1_gas(2203_u32.into()),
>     };
> ```

If you set `block_context.versioned_constants.allocation_cost = AllocationCost::ZERO`, then the values are equal?



_Code quote:_
```XML
    let expected_gas = match use_kzg_da {
        true => GasVector {
            l1_gas: 17988_u32.into(),
            l1_data_gas: 160_u32.into(),
            l2_gas: 0_u32.into(),
        },
        false => GasVector::from_l1_gas(19682_u32.into()),
    };

    let expected_da_gas = match use_kzg_da {
        true => GasVector::from_l1_data_gas(160_u32.into()),
        false => GasVector::from_l1_gas(2203_u32.into()),
    };
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2301)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2301#-OCgyq8ZC2J785nqQRLZ:-OChqkwo-uakFhJDL1tI:b-a0slcd) ([raw file](https://github.com/starkware-libs/sequencer/blob/2ca3609f6a9b952e7ee0d8c27f59b3f41e476b08/crates/blockifier/src/fee/resources.rs#L206)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Do we want to panic in that case? Isn't it better to return something like `GasVector::MAX`?
</blockquote></details>

Yes, I want to panic.
Like in the function `to_gas_vector` of  `StarknetResources` that calls to this function.
We don't want to lose fees.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2308 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2301#-OCgybzTEOPnw_3ebkaX:-OChsR6fA8962iPfGu1P:b-8y13l6) ([raw file](https://github.com/starkware-libs/sequencer/blob/2ca3609f6a9b952e7ee0d8c27f59b3f41e476b08/crates/blockifier/src/transaction/transactions_test.rs#L2308)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

If you set `block_context.versioned_constants.allocation_cost = AllocationCost::ZERO`, then the values are equal?
</blockquote></details>

Yes, with `AllocationCost::ZERO` the test passes without changes.

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2301)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2308 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2301#-OCgybzTEOPnw_3ebkaX:-OCiDLcfAzg7Gb02eoF2:b-fnu8wv) ([raw file](https://github.com/starkware-libs/sequencer/blob/f50f2fa13435c26fa524ec7c9f0ae5c0a0ff0538/crates/blockifier/src/transaction/transactions_test.rs#L2308)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Yes, with `AllocationCost::ZERO` the test passes without changes.
</blockquote></details>

I would prefer to set `block_context.versioned_constants.allocation_cost = AllocationCost::ZERO`, and keep values as they were

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2301)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware and @yoavGrs)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2308 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2301#-OCgybzTEOPnw_3ebkaX:-OClzVLt1ZzhpuyOu-hC:bknvxb3) ([raw file](https://github.com/starkware-libs/sequencer/blob/f50f2fa13435c26fa524ec7c9f0ae5c0a0ff0538/crates/blockifier/src/transaction/transactions_test.rs#L2308)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I would prefer to set `block_context.versioned_constants.allocation_cost = AllocationCost::ZERO`, and keep values as they were
</blockquote></details>

this is wrong: the DA gas in the receipt should not change, regardless of allocation cost
___
*[`crates/blockifier/src/fee/resources.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2301#-OClyjmm1iSL0DQyxvBu:-OClyjmm1iSL0DQyxvBv:bir2621) ([raw file](https://github.com/starkware-libs/sequencer/blob/f50f2fa13435c26fa524ec7c9f0ae5c0a0ff0538/crates/blockifier/src/fee/resources.rs#L207)):*
> ```XML
>             )
>         })
>     }
> ```

where do we compute the da_gas in the TransactionReceipt?
please make sure it is NOT state_resource.to_gas_vector... if it is, please update it (maybe add a `to_da_gas_vector` method in this struct?)



_Suggestion:_
```XML
    pub fn to_gas_vector(&self, use_kzg_da: bool, allocation_cost: &AllocationCost) -> GasVector {
        let n_allocated_keys = self.state_changes_for_fee.n_allocated_keys;
        let allocation_gas_vector = allocation_cost.get_cost(use_kzg_da);
        let total_allocation_cost =
            allocation_gas_vector.checked_mul(n_allocated_keys).unwrap_or_else(|| {
                panic!(
                    "State resources to gas vector overflowed: tried to multiply \
                     {allocation_gas_vector:?} by {n_allocated_keys:?}",
                )
            });
        let da_gas_cost = self.to_da_gas_vector(use_kzg_da);
        total_allocation_cost.checked_add(da_gas_cost).unwrap_or_else(|| {
            panic!(
                "State resources to gas vector overflowed: tried to add {total_allocation_cost:?} \
                 to {da_gas_cost:?}",
            )
        })
    }
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 593 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2301#-OClzF1v0wH6g4FQKl0Q:-OClzF1v0wH6g4FQKl0R:b-dgk3up) ([raw file](https://github.com/starkware-libs/sequencer/blob/f50f2fa13435c26fa524ec7c9f0ae5c0a0ff0538/crates/blockifier/src/transaction/transactions_test.rs#L593)):*
> ```XML
>         receipt: TransactionReceipt {
>             fee: expected_actual_fee,
>             da_gas,
> ```

this is wrong - the da_gas you compute includes allocation costs.
please fix the computation of the TransactionReceipt (maybe many tests will fail... but you will see which ones at least)



_Code quote:_
```XML
da_gas,
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2301#-:-ODAclHa4cGoVZVsnWtt:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

**Review by nimrod-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2301#-:-ODAdEKU9eGdLjTrav6K:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2301)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2301)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
