### PR TITLE
feat(consensus): test receiver to mock network failures during simulations

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/166)

### CODE REVIEW

**Comment by matan-starkware** [comment]
* **#166** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/166?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by asmaastarkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/166)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @matan-starkware, and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 195 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O2yfgIm6VUscreVy2CA:-O2yfgIm6VUscreVy2CB:bfyrkse) ([raw file](https://github.com/starkware-libs/sequencer/blob/2cf7254874b482b67151e14cb51881d9f9fdd5d8/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L195)):*
> ```XML
>         drop(sender);
> 
>         while let Some(_) = receiver.next().await {
> ```

while receiver.next().await.is_some() {



_Code quote:_
```XML
while let Some(_) = receiver.next().await {
```

**Review by asmaastarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/166)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @matan-starkware, and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 70 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37Z9zK9t-7GU77s16N:-O37Z9zL13pLk2nctiny:b-enfzs1) ([raw file](https://github.com/starkware-libs/sequencer/blob/b138c579cedae067b3cb0db1fc8e01b65b14faa8/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L70)):*
> ```XML
>         invalid_probability: u64,
>         drop_probability: u64,
>         cache_size: usize,
> ```

to keep things consistent, let's keep the order of params as in the struct



_Suggestion:_
```XML
    pub fn new(
        receiver: ReceiverT,
        cache_size: usize,
        seed: u64,
        drop_probability: u64,
        invalid_probability: u64,
        
```

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/166)* status: all files reviewed, 14 unresolved discussions (waiting on @asmaastarkware, @dorimedini-starkware, and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 13 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37qPTX2LSVQh9UJfFf:-O37qPTX2LSVQh9UJfFg:b-f4vxwb) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L13)):*
> ```XML
> /// A simple cache used to count the occurrences of a key. It is constant size and simply overwrites
> /// keys when they overlap (resetting their count).
> pub struct Cache {
> ```

What's the goal of this cache? Why not use an existing cache implementation like LruCache (which we use in central sync)
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 14 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37q0YQ9dFhbkiJJZD8:-O37q0YQ9dFhbkiJJZD9:bug7e1o) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L14)):*
> ```XML
> /// keys when they overlap (resetting their count).
> pub struct Cache {
>     data: Vec<Option<(u64, u32)>>,
> ```

It's very not clear what each value stands for here, and what does none mean.
Either document it or define more structs with named fields to pass the meaning (I prefer the latter)
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 18 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37sBgu0G7EGQguXhZG:-O37sBgu0G7EGQguXhZH:b-y2o8td) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L18)):*
> ```XML
> 
> impl Cache {
>     fn new(size: usize) -> Self {
> ```

Why do you limit the size of the cache and not just rename it to counter? Are there too many messages in a test?
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 58 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37rZ7X4QLKsj9cfO2E:-O37rZ7X4QLKsj9cfO2F:b-3g6j4k) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L58)):*
> ```XML
>     pub seed: u64,
>     pub drop_probability: u64,
>     pub invalid_probability: u64,
> ```

Clarify that invalid probability is for the case that the message wasn't dropped (the final invalid probability is (1 - drop_probability) * invalid_probability)
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 72 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37rAJe3-ikApz4pSo0:-O37rAJe3-ikApz4pSo1:b7sx0u3) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L72)):*
> ```XML
>         invalid_probability: u64,
>     ) -> Self {
>         assert!(invalid_probability <= 100);
> ```

It's very unclear that 100 means 1. Why not f64 between 0 and 1?
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 91 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37rPdtEr-lZZ5RhSwY:-O37rPdtEr-lZZ5RhSwZ:b-g7t7qs) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L91)):*
> ```XML
>         }
> 
>         let randint = self.calculate_msg_hash(&msg) % 100;
> ```

Extract this to a helper method that returns a bool
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 153 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37sW8SCn8wE3XHxSWd:-O37sW8SCn8wE3XHxSWe:b-y76la1) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L153)):*
> ```XML
> 
> #[cfg(test)]
> mod test {
> ```

this entire file is only declared as a module if cfg(test), so you can remove this two lines and unindent everything below
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 158 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37sfoT-ZqJkbGjonR2:-O37sfoT-ZqJkbGjonR3:b-e1kjxk) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L158)):*
> ```XML
>     use test_case::test_case;
> 
>     use super::*;
> ```

This is never good. Specify what you need
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 163 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37tqYPAzg3qDBY7x9D:-O37tqYPAzg3qDBY7x9E:bmpy8fi) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L163)):*
> ```XML
>     #[test_case(false; "repeat_messages")]
>     #[tokio::test]
>     async fn test_invalid(distinct_messages: bool) {
> ```

This is a test for the NetworkReceiver, which is a test utility, right?
If yes, mention it explicitly in a comment
Same for the test below
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 165 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37stOp6dGToY3y9puk:-O37stOp6dGToY3y9pul:b-ozp1nx) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L165)):*
> ```XML
>     async fn test_invalid(distinct_messages: bool) {
>         let (mut sender, receiver) = futures::channel::mpsc::unbounded();
>         let mut receiver = NetworkReceiver::new(receiver, 10, 123, 0, 50);
> ```

Extract all these numbers to constants so the reader can understand what they mean (unfortunately rust is not python and we don't have kwargs)
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 166 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37t4iR6150er4MagSu:-O37t4iR6150er4MagSv:b2516qd) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L166)):*
> ```XML
>         let (mut sender, receiver) = futures::channel::mpsc::unbounded();
>         let mut receiver = NetworkReceiver::new(receiver, 10, 123, 0, 50);
>         let mut invalid = 0;
> ```

invalid -> invalid_messages
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 174 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37tDvd43k0KriuGphk:-O37tDvd43k0KriuGphl:bhdiha4) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L174)):*
> ```XML
>             let report_sender = futures::channel::oneshot::channel().0;
>             let msg = ConsensusMessage::Proposal(proposal.clone());
>             sender.send((Ok(msg.clone()), report_sender)).await.unwrap();
> ```

@eitanm-starkware it's worth noting that the network's users also create channels when they "mock the network" in tests
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 179 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37tTSv2J2xWpAD3tyR:-O37tTSv2J2xWpAD3tyS:bwogh0w) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L179)):*
> ```XML
>             }
>         }
>         assert!(40 <= invalid && invalid <= 60, "num_invalid={invalid}");
> ```

That sounds harsh. maybe 30/70? Could you remind me what's the probability this will happen?

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/166)* status: 3 of 6 files reviewed, 14 unresolved discussions (waiting on @asmaastarkware, @dorimedini-starkware, and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 70 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37Z9zK9t-7GU77s16N:-O381UIPARP4P3BuuQXZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b138c579cedae067b3cb0db1fc8e01b65b14faa8/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L70)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

to keep things consistent, let's keep the order of params as in the struct
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 13 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37qPTX2LSVQh9UJfFf:-O386oBO8tI3floPwkYX:b-edk44g) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L13)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What's the goal of this cache? Why not use an existing cache implementation like LruCache (which we use in central sync)
</blockquote></details>

I switched to LruCache. The comments on the struct definition of `NetworkReceiever` should make it clear why I'm using the cache. Can you tell me if that helps or what's missing?
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 14 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37q0YQ9dFhbkiJJZD8:-O386zV2D5Uz-zF8kRX-:bdk5ql2) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L14)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

It's very not clear what each value stands for here, and what does none mean.
Either document it or define more structs with named fields to pass the meaning (I prefer the latter)
</blockquote></details>

LruCache makes this obsolete.
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 18 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37sBgu0G7EGQguXhZG:-O3875iaDII1CIqyllHF:bq2figu) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L18)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why do you limit the size of the cache and not just rename it to counter? Are there too many messages in a test?
</blockquote></details>

Well I want this to be useful even for a longevity test, so I thought I have to cap the size at some point.
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 58 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37rZ7X4QLKsj9cfO2E:-O387HRT3GO-EzDSqbTO:b-srdie6) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L58)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Clarify that invalid probability is for the case that the message wasn't dropped (the final invalid probability is (1 - drop_probability) * invalid_probability)
</blockquote></details>

I put this on `fn filter_msg`
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 72 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37rAJe3-ikApz4pSo0:-O387Kkj6w6X9WzOzmnh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L72)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

It's very unclear that 100 means 1. Why not f64 between 0 and 1?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 91 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37rPdtEr-lZZ5RhSwY:-O387Lz61UVTX14MbTcV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L91)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Extract this to a helper method that returns a bool
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 153 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37sW8SCn8wE3XHxSWd:-O387b436eZ3KoeCs31y:bpm2wov) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L153)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

this entire file is only declared as a module if cfg(test), so you can remove this two lines and unindent everything below
</blockquote></details>

I prefer to keep the tests in their own module.
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 158 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37sfoT-ZqJkbGjonR2:-O387yXyDZCrrAnmockD:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L158)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is never good. Specify what you need
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 163 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37tqYPAzg3qDBY7x9D:-O3886fxEwSv51LQvruc:b3l1zw5) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L163)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is a test for the NetworkReceiver, which is a test utility, right?
If yes, mention it explicitly in a comment
Same for the test below
</blockquote></details>

added at the mod level for tests.
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 165 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37stOp6dGToY3y9puk:-O388XIaCmqVzyKWlaYH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L165)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Extract all these numbers to constants so the reader can understand what they mean (unfortunately rust is not python and we don't have kwargs)
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 166 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37t4iR6150er4MagSu:-O388XjO7Me7egn872U0:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L166)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

invalid -> invalid_messages
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 179 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37tTSv2J2xWpAD3tyR:-O388aFY1sXGwPibbG9D:bgoqq5d) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L179)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

That sounds harsh. maybe 30/70? Could you remind me what's the probability this will happen?
</blockquote></details>

I used a binomial calculator to check and you make a good point. The odds of failure with properly working code (100 msgs, 50% probability):
1. 40-60: 3.5%
2. 30-70: 0.004%

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/166)* status: all files reviewed, 4 unresolved discussions (waiting on @asmaastarkware, @dorimedini-starkware, and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 153 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37sW8SCn8wE3XHxSWd:-O3BjK7Z7ThP6RuWyvFC:b-u2gsqh) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L153)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I prefer to keep the tests in their own module.
</blockquote></details>

Our convention is not to have `mod foo {` inside our code. If you want to keep them separate, please create a separate file
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 179 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37tTSv2J2xWpAD3tyR:-O3BjzjW4QaZZy-zLGrC:bei448c) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L179)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I used a binomial calculator to check and you make a good point. The odds of failure with properly working code (100 msgs, 50% probability):
1. 40-60: 3.5%
2. 30-70: 0.004%
</blockquote></details>

0.004% is still high (2^-14.6)
On the other side, changing it to 20/80 allows the test to pass if there's a bug.
Maybe increase the number of messages? could you send a link to your calculator

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/166)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @asmaastarkware, @dorimedini-starkware, and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 153 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37sW8SCn8wE3XHxSWd:-O3C7FZJ1BmNcsBGk8Pl:bxqrb5r) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L153)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Our convention is not to have `mod foo {` inside our code. If you want to keep them separate, please create a separate file
</blockquote></details>

I/Asmaa actually realized that we want this for simulations, which are tests but we don't compile them with the flag for tests. So I am refactoring this:
1. The file will be `simulation_network_receiver`
2. I will move the tests to their own file.
___
*[`crates/sequencing/papyrus_consensus/src/test_network_receiver.rs` line 179 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/166#-O37tTSv2J2xWpAD3tyR:-O3C6eWE--p6AEoki6Qu:b-jcsc2n) ([raw file](https://github.com/starkware-libs/sequencer/blob/582a44627e48295c77e59c0caa02b60600389b64/crates/sequencing/papyrus_consensus/src/test_network_receiver.rs#L179)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

0.004% is still high (2^-14.6)
On the other side, changing it to 20/80 allows the test to pass if there's a bug.
Maybe increase the number of messages? could you send a link to your calculator
</blockquote></details>

https://stattrek.com/online-calculator/binomial

I'll just switch to 1000 messages. This way, the odds of being outside (400-600) are too low for the calculator to show anything.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/166#-:-O3CAiLRCt2a1WaSxv7u:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @dorimedini-starkware)

**Pull request merged**
