### PR TITLE
chore(sequencer_node): replace run node shell command

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**

### CODE REVIEW

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2266)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by ArniStarkware** [comment]
*[`crates/starknet_sequencer_node/src/test_utils/compilation.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2266#-OCbZOF8AclA_sB694a8:-OCbZOF8AclA_sB694a9:b-ti3nh7) ([raw file](https://github.com/starkware-libs/sequencer/blob/000aaa8f768a2748bb53a5a9a295a6d07ed3d4fc/crates/starknet_sequencer_node/src/test_utils/compilation.rs#L7)):*
> ```XML
> use tracing::info;
> 
> pub const NODE_EXECUTABLE_PATH: &str = "target/debug/starknet_sequencer_node";
> ```

This is always debug as this is a test-util, this will always be called in a debug context. Correct?



_Code quote:_
```XML
pub const NODE_EXECUTABLE_PATH: &str = "target/debug/starknet_sequencer_node";
```

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2266#-:-OCbab54Da_h1eY5Wb9M:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2266)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2266)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2266)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2266#-:-OCcYJZ8E5nlR-Rwq_cN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
