### PR TITLE
chore(ci): use large_runner in committer

### PR DESCRIPTION
**Pull request by alon-dotan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/378)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/378)* status: all files reviewed, 6 unresolved discussions (waiting on @alon-dotan-starkware and @amosStarkware)

___
*[`.github/workflows/blockifier_ci.yml` line 26 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/378#-O40SYunDNTMUVVdjByK:-O40SYunDNTMUVVdjByL:bowafwd) ([raw file](https://github.com/starkware-libs/sequencer/blob/220fba3cfdb75d852e1880eb21210cbc4de1d90d/.github/workflows/blockifier_ci.yml#L26)):*
> ```YAML
>       - 'build_native_in_docker.sh'
>       - 'scripts/build_native_blockifier.sh'
>       - 'scripts/sequancer-ci.Dockerfile'
> ```

typo (above)



_Code quote:_
```YAML
sequancer-ci
```
___
*[`build_native_in_docker.sh` line 0 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/378#-O40SSIM9FRYvyLuKO01:-O40SSIM9FRYvyLuKO02:b-xuo7el) ([raw file](https://github.com/starkware-libs/sequencer/blob/220fba3cfdb75d852e1880eb21210cbc4de1d90d/build_native_in_docker.sh#L0)):*
if this is a general script why is "native" in the filename? committer is not "native", it is a CLI
___
*[`build_native_in_docker.sh` line 4 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/378#-O40SCkXCRetamEV6aUz:-O40SCkXCRetamEV6aV-:bb7phvt) ([raw file](https://github.com/starkware-libs/sequencer/blob/220fba3cfdb75d852e1880eb21210cbc4de1d90d/build_native_in_docker.sh#L4)):*
> ```Shell
> set -e
> 
> docker_image_name=sequancer-ci
> ```

typo



_Code quote:_
```Shell
sequancer
```
___
*[`build_native_in_docker.sh` line 4 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/378#-O40SLwp99-csRt9-nTU:-O40SLwq5tusJxkNZ0tA:b1q5ipj) ([raw file](https://github.com/starkware-libs/sequencer/blob/220fba3cfdb75d852e1880eb21210cbc4de1d90d/build_native_in_docker.sh#L4)):*
> ```Shell
> set -e
> 
> docker_image_name=sequancer-ci
> ```

this is not relevant for papyrus, right?
or are you aligning papyrus as well?



_Code quote:_
```Shell
sequancer-ci
```
___
*[`build_native_in_docker.sh` line 8 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/378#-O40SGVzC-hZCF-d4uwe:-O40SGVzC-hZCF-d4uwf:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/220fba3cfdb75d852e1880eb21210cbc4de1d90d/build_native_in_docker.sh#L8)):*
> ```Shell
> (
>     cd scripts
>     docker build . -t ${docker_image_name} --file sequancer-ci.Dockerfile
> ```





_Suggestion:_
```Shell
${docker_image_name} --file ${docker_image_name}.Dockerfile
```
___
*[`scripts/sequancer-ci.Dockerfile` line 0 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/378#-O40SeZJ3QGC94nizOXl:-O40SeZJ3QGC94nizOXm:b-f4dvlh) ([raw file](https://github.com/starkware-libs/sequencer/blob/220fba3cfdb75d852e1880eb21210cbc4de1d90d/scripts/sequancer-ci.Dockerfile#L0)):*
typo in filename

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/378)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`build_native_in_docker.sh` line 4 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/378#-O40SLwp99-csRt9-nTU:-O458Mqc2pq8Q2JLatyt:bvzy945) ([raw file](https://github.com/starkware-libs/sequencer/blob/220fba3cfdb75d852e1880eb21210cbc4de1d90d/build_native_in_docker.sh#L4)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is not relevant for papyrus, right?
or are you aligning papyrus as well?
</blockquote></details>

currently not related to papyrus, but I think the time will tell
___
*[`build_native_in_docker.sh` line  at r2](https://reviewable.io/reviews/starkware-libs/sequencer/378#-O40SSIM9FRYvyLuKO01:-O458EJ6DpZ9IndDYnUp:b6bxeot) ([raw file](https://github.com/starkware-libs/sequencer/blob/220fba3cfdb75d852e1880eb21210cbc4de1d90d/build_native_in_docker.sh#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if this is a general script why is "native" in the filename? committer is not "native", it is a CLI
</blockquote></details>

native as it sensitive to the os (AKA link issues)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/378)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @amosStarkware)

___
*[`build_native_in_docker.sh` line 8 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/378#-O45MiXRELc1eqXOFxQ3:-O45MiXRELc1eqXOFxQ4:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/87edc04f6559390e21bf1f83294a19f79b341337/build_native_in_docker.sh#L8)):*
> ```Shell
> (
>     cd scripts
>     docker build . -t ${docker_image_name} --file ${docker_image_name}
> ```





_Suggestion:_
```Shell
${docker_image_name}.Dockerfile
```

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/378)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`build_native_in_docker.sh` line 8 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/378#-O45MiXRELc1eqXOFxQ3:-O49gh7S89N-5RjUCB0M:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/87edc04f6559390e21bf1f83294a19f79b341337/build_native_in_docker.sh#L8)):*
> ```Shell
> (
>     cd scripts
>     docker build . -t ${docker_image_name} --file ${docker_image_name}
> ```

Done.

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/378)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`build_native_in_docker.sh` line 8 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/378#-O45MiXRELc1eqXOFxQ3:-O4EpJ2X1ksSuQwzqN-W:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/87edc04f6559390e21bf1f83294a19f79b341337/build_native_in_docker.sh#L8)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where?
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/378)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @amosStarkware)

___
*[`.github/workflows/blockifier_ci.yml` line 35 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/378#-O4F2LJcANVIcJaZvFDL:-O4F2LJd2jtAoRMmsgI6:ba22rjv) ([raw file](https://github.com/starkware-libs/sequencer/blob/1499e40503d14dc868173e44e0581492faf1db07/.github/workflows/blockifier_ci.yml#L35)):*
> ```YAML
>       - 'scripts/build_native_blockifier.sh'
>       - 'scripts/install_build_tools.sh'
>       - 'scripts/sequancer-ci.Dockerfile'
> ```

fix this list... which files exist, which were moved, duplicate, typo



_Code quote:_
```YAML
      - '.github/workflows/blockifier_ci.yml'
      - 'build_native_blockifier_in_docker.sh'
      - 'build_native_in_docker.sh'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'crates/blockifier/**'
      - 'crates/native_blockifier/**'
      - 'scripts/build_native_blockifier.sh'
      - 'scripts/build_native_blockifier.sh'
      - 'scripts/install_build_tools.sh'
      - 'scripts/sequancer-ci.Dockerfile'
```

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/378)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`.github/workflows/blockifier_ci.yml` line 35 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/378#-O4F2LJcANVIcJaZvFDL:-O4KeL4iBhtvptIp53WI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1499e40503d14dc868173e44e0581492faf1db07/.github/workflows/blockifier_ci.yml#L35)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

fix this list... which files exist, which were moved, duplicate, typo
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/378)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @amosStarkware)

___
*[`.github/workflows/blockifier_ci.yml` line 33 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/378#-O4Kgby50T8KBYkJY84Q:-O4Kgby50T8KBYkJY84R:bh65pc1) ([raw file](https://github.com/starkware-libs/sequencer/blob/82a36a697361333cce60d094ef94039a24284dde/.github/workflows/blockifier_ci.yml#L33)):*
> ```YAML
>       - 'scripts/build_native_blockifier.sh'
>       - 'scripts/install_build_tools.sh'
>       - 'scripts/sequancer-ci.Dockerfile'
> ```

still typo



_Code quote:_
```YAML
sequancer-ci
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/378#-:-O4L6q0HDzmwjzDmVkGF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
