### PR TITLE
test(mempool): validate fee escalation replacement

### PR DESCRIPTION
**Pull request by ayeletstarkware**

### CODE REVIEW

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2143)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/starknet_mempool/src/mempool_test.rs` line 146 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2143#-OC-6yOb0QTRX62wiOR6:-OC-6yOc-uy15VRwsiLA:b-4ze0ka) ([raw file](https://github.com/starkware-libs/sequencer/blob/68a7ab8e3c266c909248d6d861c89c2aa9cb162e/crates/starknet_mempool/src/mempool_test.rs#L146)):*
> ```XML
> 
>     // Verify transaction was replaced.
>     let mut builder = MempoolContentBuilder::new().with_pool([valid_replacement_input.tx.clone()]);
> ```

Please re-order this so it'd avoid the clone.



_Code quote:_
```XML
clone()
```
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 534 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2143#-OC-7L4W0ph2nBYFRqKV:-OC-7L4W0ph2nBYFRqKW:bw31ohh) ([raw file](https://github.com/starkware-libs/sequencer/blob/68a7ab8e3c266c909248d6d861c89c2aa9cb162e/crates/starknet_mempool/src/mempool_test.rs#L534)):*
> ```XML
> 
> #[rstest]
> #[case::pool(AdditionalQueueCheck::None)]
> ```

Do we need this case?



_Code quote:_
```XML
#[case::pool(AdditionalQueueCheck::None)]
```
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 547 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2143#-OC-7ExKDOnPehnXqsrU:-OC-7ExL8Lplu3ecf7vb:b-ho0aiu) ([raw file](https://github.com/starkware-libs/sequencer/blob/68a7ab8e3c266c909248d6d861c89c2aa9cb162e/crates/starknet_mempool/src/mempool_test.rs#L547)):*
> ```XML
>         let tx = tx!(tip: 90, max_l2_gas_price: 90);
>         let mut builder =
>             MempoolContentBuilder::new().with_pool([tx.clone()]).with_fee_escalation_percentage(10);
> ```

the same



_Code quote:_
```XML
tx.clone()
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2143)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`crates/starknet_mempool/src/mempool_test.rs` line 534 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2143#-OC-7L4W0ph2nBYFRqKV:-OC2dNFyAck3vkMa3KeQ:buqqain) ([raw file](https://github.com/starkware-libs/sequencer/blob/68a7ab8e3c266c909248d6d861c89c2aa9cb162e/crates/starknet_mempool/src/mempool_test.rs#L534)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Do we need this case?
</blockquote></details>

@elintul asked to test transaction-only-in-pool

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2143)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2143#-OC2ht1s2ktcMarIO_9m:-OC2ht1tDiqCdm3ZoVbx:b4nu75j) (no related file):*
Nice PR! :fire: 
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 534 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2143#-OC-7L4W0ph2nBYFRqKV:-OC2h25Y4f6G-jW0ASx4:b1ty1a5) ([raw file](https://github.com/starkware-libs/sequencer/blob/68a7ab8e3c266c909248d6d861c89c2aa9cb162e/crates/starknet_mempool/src/mempool_test.rs#L534)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

@elintul asked to test transaction-only-in-pool
</blockquote></details>

Oooh, I thought we already have such.
If this is the only case, so please keep it.
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 150 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2143#-OC2hbHP52C9HYgvZLng:-OC2hbHP52C9HYgvZLnh:b-lp793n) ([raw file](https://github.com/starkware-libs/sequencer/blob/547f6e782dd54038a5c88e6cb2046ab2c25e48d2/crates/starknet_mempool/src/mempool_test.rs#L150)):*
> ```XML
>         AdditionalQueueCheck::PriorityQueue => {
>             builder = builder
>                 .with_priority_queue([TransactionReference::new(&valid_replacement_input.tx)]);
> ```

To save the duplication, It can be stored in a variable.



_Code quote:_
```XML
[TransactionReference::new(&valid_replacement_input.tx)]
```
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 159 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2143#-OC2gpdH0ZnaDg2caqiK:-OC2gpdH0ZnaDg2caqiL:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/547f6e782dd54038a5c88e6cb2046ab2c25e48d2/crates/starknet_mempool/src/mempool_test.rs#L159)):*
> ```XML
>     }
>     builder = builder.with_pool([valid_replacement_input.tx]);
>     let expected_mempool_content = builder.build();
> ```





_Suggestion:_
```XML
        let expected_mempool_content = builder.with_pool([valid_replacement_input.tx]).build();
```
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 579 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2143#-OC2hAlnCMwCvN0Urmhw:-OC2hAlnCMwCvN0Urmhx:b-bbqovg) ([raw file](https://github.com/starkware-libs/sequencer/blob/547f6e782dd54038a5c88e6cb2046ab2c25e48d2/crates/starknet_mempool/src/mempool_test.rs#L579)):*
> ```XML
>         };
>         builder = builder.with_pool([tx]);
>         let mempool = builder.build_into_mempool();
> ```

The same like above.



_Code quote:_
```XML
        builder = builder.with_pool([tx]);
        let mempool = builder.build_into_mempool();
```

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2143#-:-OC2pU_07JT6tl_ZofcV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2143)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2143)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/starknet_mempool/src/mempool_test.rs` line 130 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2143#-OC7ztjp-5_cbEqoWnvF:-OC7ztjp-5_cbEqoWnvG:bci6dds) ([raw file](https://github.com/starkware-libs/sequencer/blob/c1214daffc37dfde6f41f128a118c8add89a3c13/crates/starknet_mempool/src/mempool_test.rs#L130)):*
> ```XML
>     }
> }
> ```

I'd lose the enum and pass two booleans (`with_[pending/priority]`); our case is simple enough.

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2143#-:-OC8lldr-tKvElOghDog:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2143)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/starknet_mempool/src/mempool_test.rs` line 130 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2143#-OC7ztjp-5_cbEqoWnvF:-OC8mmnzDnoU8mByBDkE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c1214daffc37dfde6f41f128a118c8add89a3c13/crates/starknet_mempool/src/mempool_test.rs#L130)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'd lose the enum and pass two booleans (`with_[pending/priority]`); our case is simple enough.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2143#-:-OC90SKL1t6u8IE5Imoh:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/starknet_mempool/src/mempool_test.rs` line 559 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2143#-OC8nFUM4tZWrD7BsJZm:-OC9-sJw6aSKvWXao2oE:b-7c3b49) ([raw file](https://github.com/starkware-libs/sequencer/blob/41fac5977e70d6e4ce8f1a7e200909b55a76376c/crates/starknet_mempool/src/mempool_test.rs#L559)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

It causes an extra clone.
</blockquote></details>

Right. :(

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2143)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2143)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
