### PR TITLE
feat(blockifier): add TrackingResource to CallInfo and use to update gas

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/928)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/928)* status: all files reviewed, 8 unresolved discussions (waiting on @TzahiTaub and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P0rx98FY_inFajiFG:-O7P0rx98FY_inFajiFH:bjc2vkq) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/execution/contract_class.rs#L53)):*
> ```XML
> #[cfg_attr(feature = "transaction_serde", derive(serde::Deserialize))]
> #[derive(Clone, Copy, Default, Debug, Eq, PartialEq, Serialize)]
> pub enum TrackingResource {
> ```

should this be named `TrackedResource`? (non-blocking, out of scope)



_Code quote:_
```XML
TrackingResource
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P0eEC6Zew2IcM2RU_:-O7P0eEC6Zew2IcM2RUa:b-cjohil) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/execution/entry_point.rs#L134)):*
> ```XML
>     // The execution mode affects the behavior of the hint processor.
>     pub execution_mode: ExecutionMode,
>     // The stack of tracking resources from the first entry point to the current.
> ```

in the call stack? or in chronological order? please be clear in docstring



_Code quote:_
```XML
// The stack of tracking resources from the first entry point to the current.
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P13V2A2Y7v3XtS_QH:-O7P13V2A2Y7v3XtS_QI:b9mtujn) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/execution/entry_point_execution.rs#L67)):*
> ```XML
> 
>     let tracking_resource =
>         *context.tracking_resource.last().expect("Unexpected empty tracking resource.");
> ```

can't this be empty in the first (top-level) entry point? I see it created above with `vec![]`



_Code quote:_
```XML
    let tracking_resource =
        *context.tracking_resource.last().expect("Unexpected empty tracking resource.");
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P1h1xAqVDxQM0HTBd:-O7P1h1xAqVDxQM0HTBe:b-dtvjfi) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/execution/execution_utils.rs#L82)):*
> ```XML
>     };
> 
>     context.tracking_resource.pop();
> ```

if, in the future, in the code between this line and the `push` above, there is some possibility of an error propagated with `?`, and "caught" in the calling code, we will end up with bugs...
can you track this with some form of scope guard?



_Code quote:_
```XML
context.tracking_resource.pop();
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P1bYX7Ex1gW0HV6NT:-O7P1bYX7Ex1gW0HV6NU:b-uyg16g) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/execution/execution_utils.rs#L89)):*
> ```XML
>     if call_info.tracking_resource == TrackingResource::SierraGas {
>         *remaining_gas -= call_info.execution.gas_consumed;
>     }
> ```

this was previously also done for VM-executed entry points. Why change the behavior?



_Code quote:_
```XML
    if call_info.tracking_resource == TrackingResource::SierraGas {
        *remaining_gas -= call_info.execution.gas_consumed;
    }
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P0ThF0bheCxCoIOfS:-O7P0ThF0bheCxCoIOfT:byy2fss) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L150)):*
> ```XML
>     let tracking_resource = test_contract.get_class().tracking_resource(
>         &VersionedConstants::create_for_testing().min_compiler_version_for_sierra_gas,
>     ); // Fixed version that should be lower than the one in version constants.
> ```

what's this comment referring to?



_Code quote:_
```XML
// Fixed version that should be lower than the one in version constants.
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P0Fk87OU2HXxlz-wX:-O7P0Fk87OU2HXxlz-wY:bpuxcrz) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/transaction/transactions_test.rs#L0)):*
do you test anywhere that the resource value is non zero?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 450 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P0AKS86fBuz4_0r2X:-O7P0AKS86fBuz4_0r2Y:b354p86) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/transaction/transactions_test.rs#L450)):*
> ```XML
>     // } else {
>     //     TrackingResource::CairoSteps
>     // };
> ```

what's this?



_Code quote:_
```XML
    // let account_tracking_resource = account_contract
    //     .get_class()
    //     .tracking_resource(&versioned_constants.min_compiler_version_for_sierra_gas);
    // let test_tracking_resource = test_contract
    //     .get_class()
    //     .tracking_resource(&versioned_constants.min_compiler_version_for_sierra_gas);
    // let expected_tracking_resource = if account_tracking_resource == TrackingResource::SierraGas
    //     && test_tracking_resource == TrackingResource::SierraGas
    // {
    //     TrackingResource::SierraGas
    // } else {
    //     TrackingResource::CairoSteps
    // };
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/928)* status: 0 of 8 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P0rx98FY_inFajiFG:-O7Soix_EogTxwB4YNtW:bb4sabr) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/execution/contract_class.rs#L53)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

should this be named `TrackedResource`? (non-blocking, out of scope)
</blockquote></details>

Sounds better
___
*[`crates/blockifier/src/execution/entry_point.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P0eEC6Zew2IcM2RU_:-O7Syz9FEdBXuzealhV6:b-x9ba83) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/execution/entry_point.rs#L134)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

in the call stack? or in chronological order? please be clear in docstring
</blockquote></details>

Like this?
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P13V2A2Y7v3XtS_QH:-O7T30sG6t_K1vrXlrqE:b-cach5v) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/execution/entry_point_execution.rs#L67)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can't this be empty in the first (top-level) entry point? I see it created above with `vec![]`
</blockquote></details>

No, there is a single caller for this and it pushes to the stack before the call. I can add this req to the docstring of the function, not sure if it's too implementation detail, or required.
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P1h1xAqVDxQM0HTBd:-O7TPE_c4FOYQcZIlP5e:bl0x2qq) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/execution/execution_utils.rs#L82)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if, in the future, in the code between this line and the `push` above, there is some possibility of an error propagated with `?`, and "caught" in the calling code, we will end up with bugs...
can you track this with some form of scope guard?
</blockquote></details>

Asked about it, waiting for a suggestion.
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P1bYX7Ex1gW0HV6NT:-O7TJc9_140iuIFy0Bwn:b-wxgv5k) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/execution/execution_utils.rs#L89)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this was previously also done for VM-executed entry points. Why change the behavior?
</blockquote></details>

Because the VM mode gas consumption is either 0 for Cairo 0 or some blown up value we want to ignore for old Cairo 1 compiler) The def of TrackedResource::CairoSteps is that we ignore the gas consumption and only update the cairo steps usage.
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P0ThF0bheCxCoIOfS:-O7TK4zJC9pUGrOA1KRC:brzb4rd) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L150)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what's this comment referring to?
</blockquote></details>

Old leftovers I think.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 450 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P0AKS86fBuz4_0r2X:-O7TKQwaEIHXFc-LJYGP:b-inoih8) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/transaction/transactions_test.rs#L450)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what's this?
</blockquote></details>

:) 
Leftovers again.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P0Fk87OU2HXxlz-wX:-O7TKVqE3rHykZ1ZEb6m:bvstv0d) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/transaction/transactions_test.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do you test anywhere that the resource value is non zero?
</blockquote></details>

WDYM? The resource bound?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/928)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P1bYX7Ex1gW0HV6NT:-O7U-Q1_-DaL6KOP8BaR:b-td8jlw) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/execution/execution_utils.rs#L89)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Because the VM mode gas consumption is either 0 for Cairo 0 or some blown up value we want to ignore for old Cairo 1 compiler) The def of TrackedResource::CairoSteps is that we ignore the gas consumption and only update the cairo steps usage.
</blockquote></details>

please open a python side PR to make sure no OS test breaks
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P0Fk87OU2HXxlz-wX:-O7U-ZzaADUmIDtB8GE-:b-7gavss) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/transaction/transactions_test.rs#L)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

WDYM? The resource bound?
</blockquote></details>

ah nvm, misunderstood previously what tracked_resource is

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/928)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub and @Yoni-Starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/928)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7Y0HvaDsCA-tXopf33:-O7Y0HvaDsCA-tXopf34:b-36dlmn) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b9c815f84322b1bc8656c0e2bdcf10237855b83/crates/blockifier/src/execution/entry_point_execution.rs#L67)):*
> ```XML
> 
>     let tracked_resource =
>         *context.tracked_resource.last().expect("Unexpected empty tracked resource.");
> ```

You can do this inside `finalize_execution`, right?



_Code quote:_
```XML
    let tracked_resource =
        *context.tracked_resource.last().expect("Unexpected empty tracked resource.");
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P1bYX7Ex1gW0HV6NT:-O7YNt2P1cJkNKU3oDkb:b-6nq3xu) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/execution/execution_utils.rs#L89)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please open a python side PR to make sure no OS test breaks
</blockquote></details>

It will break the OS.
The condition should be:
**Don't** update if my parent is Sierra and I am CairoSteps.

But please do so in a separate PR.

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/928)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7Y0HvaDsCA-tXopf33:-O7i3v2-67V8PMubk0n8:b6s9yak) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b9c815f84322b1bc8656c0e2bdcf10237855b83/crates/blockifier/src/execution/entry_point_execution.rs#L67)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

You can do this inside `finalize_execution`, right?
</blockquote></details>

I don't have the `context` in it
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P1bYX7Ex1gW0HV6NT:-O7i4M4jBFPLUybyVjD4:b3gm4ay) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/execution/execution_utils.rs#L89)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

It will break the OS.
The condition should be:
**Don't** update if my parent is Sierra and I am CairoSteps.

But please do so in a separate PR.
</blockquote></details>

I didn't understand. The OS will break in any case, and you think the current condition is wrong?
You want to update usage of old cairo1 contracts until the point you have to ignore them?

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/928)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/928)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @TzahiTaub and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 470 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7ia1KQCACRjbpsomFy:-O7ia1KQCACRjbpsomFz:b-p21ecv) ([raw file](https://github.com/starkware-libs/sequencer/blob/4547abccee36cc6b507b2952a1e4a50ea05d5efd/crates/blockifier/src/execution/contract_class.rs#L470)):*
> ```XML
>     compiler_version: &str,
> ) -> Result<ContractClassV1, ProgramError> {
>     let data: Vec<MaybeRelocatable> =
> ```

@TzahiTaub are these your changes...? or a rebase issue?



_Code quote:_
```XML
impl TryFrom<&CasmContractClass> for ContractClassV1 {
    type Error = ProgramError;

    fn try_from(class: &CasmContractClass) -> Result<Self, Self::Error> {
        try_from_casm_contrcat_class_internal(
            &class.bytecode,
            &class.hints,
            &class.entry_points_by_type,
            class.bytecode_segment_lengths.clone(),
            &class.compiler_version,
        )
    }
}

// V0 utilities.

/// Converts the program type from SN API into a Cairo VM-compatible type.
pub fn deserialize_program<'de, D: Deserializer<'de>>(
    deserializer: D,
) -> Result<Program, D::Error> {
    let deprecated_program = DeprecatedProgram::deserialize(deserializer)?;
    sn_api_to_cairo_vm_program(deprecated_program)
        .map_err(|err| DeserializationError::custom(err.to_string()))
}

// V1 utilities.

fn try_from_casm_contrcat_class_internal(
    bytecode: &[BigUintAsHex],
    casm_class_hints: &[(usize, Vec<Hint>)],
    casm_class_entry_points_by_type: &CasmContractEntryPoints,
    bytecode_segment_lengths: Option<NestedIntList>,
    compiler_version: &str,
) -> Result<ContractClassV1, ProgramError> {
    let data: Vec<MaybeRelocatable> =
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/928)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P1bYX7Ex1gW0HV6NT:-O7iAEk2D4lZALuCtZN1:bck8qu3) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/execution/execution_utils.rs#L89)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I didn't understand. The OS will break in any case, and you think the current condition is wrong?
You want to update usage of old cairo1 contracts until the point you have to ignore them?
</blockquote></details>

Removed from this PR.

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/928)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7P1bYX7Ex1gW0HV6NT:-O7ib19u9nSVNG7iu6JS:bohyhvw) ([raw file](https://github.com/starkware-libs/sequencer/blob/7297b9ad1d31c4d298b0f0ac1cc92fae11074251/crates/blockifier/src/execution/execution_utils.rs#L89)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Removed from this PR.
</blockquote></details>

Python upate - https://reviewable.io/reviews/starkware-industries/starkware/35976

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/928)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 470 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7ia1KQCACRjbpsomFy:-O7ibEx40R-rvoi6b8x_:byotx49) ([raw file](https://github.com/starkware-libs/sequencer/blob/4547abccee36cc6b507b2952a1e4a50ea05d5efd/crates/blockifier/src/execution/contract_class.rs#L470)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@TzahiTaub are these your changes...? or a rebase issue?
</blockquote></details>

Rebase

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/928)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 470 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7ia1KQCACRjbpsomFy:-O7ibNF35AbbqlI-xutI:b8ae8ow) ([raw file](https://github.com/starkware-libs/sequencer/blob/4547abccee36cc6b507b2952a1e4a50ea05d5efd/crates/blockifier/src/execution/contract_class.rs#L470)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Rebase
</blockquote></details>

Check changes relative to the first version.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/928)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 463 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/928#-O7ibMzaAsFFu_tzBF91:-O7ibMzaAsFFu_tzBF92:b-ljyx40) ([raw file](https://github.com/starkware-libs/sequencer/blob/4547abccee36cc6b507b2952a1e4a50ea05d5efd/crates/blockifier/src/execution/contract_class.rs#L463)):*
> ```XML
> // V1 utilities.
> 
> fn try_from_casm_contrcat_class_internal(
> ```

if you fix this typo in this PR how bad will the rebase look on reviewable...?



_Code quote:_
```XML
contrcat
```

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 4 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/928)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/928)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
