### PR TITLE
chore(starknet_batcher): add height as input

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2339?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2342** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2342?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2341** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2341?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2340** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2340?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2339** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2339?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2339?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2237** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2237?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2238](https://github.com/starkware-libs/sequencer/pull/2238) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2238?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2246** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2246?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2230](https://github.com/starkware-libs/sequencer/pull/2230) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2230?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2245** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2245?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2244** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2244?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2269** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2269?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2243** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2243?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2339#-:-OD0fKl51xkgwuhE0Tx_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2339#-OD0gWhW-adis0Edtj-3:-OD0fLo7Cb0d9O1fs5Hi:bwe44z4) (no related file):*
This should be part of the previous PR IMO.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2339)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Dec 2, 8:47 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2339).

**Pull request merged**
