### PR TITLE
refactor(starknet_gateway): gateway business logic towards bench test

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2948?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2911** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2911?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2948** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2948?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2948?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2404** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2404?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2948)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @alonh5 and @ayeletstarkware)

___
*[`crates/starknet_gateway/src/stateful_transaction_validator.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2948#-OExqqTa2Ir1AlgVPgho:-OExqqTb2zHAJny_h8hr:b-65fbcy) ([raw file](https://github.com/starkware-libs/sequencer/blob/e151662edfb1ba5331f206e35118ec4e32deed9d/crates/starknet_gateway/src/stateful_transaction_validator.rs#L46)):*
> ```XML
>     ) -> BlockifierStatefulValidatorResult<()>;
> 
>     #[allow(dead_code)]
> ```

This PR uncovered a bad practice in the code. At first, I tried removing the dead code in #2951.
But after thinking about it a bit more, I found another issue. It found a slight abuse in the gateway's flow. This issue is outside the scope of this PR.



_Code quote:_
```XML
    #[allow(dead_code)]
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2948)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @alonh5 and @ayeletstarkware)

___
*[`crates/starknet_gateway/src/stateful_transaction_validator.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2948#-OExqqTa2Ir1AlgVPgho:-OF1pgIM-tmJrOGgAAR4:byviwnh) ([raw file](https://github.com/starkware-libs/sequencer/blob/58b1254a3b4a6eca3942a445eee66f051b89dadc/crates/starknet_gateway/src/stateful_transaction_validator.rs#L46)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This PR uncovered a bad practice in the code. At first, I tried removing the dead code in #2951.
But after thinking about it a bit more, I found another issue. It found a slight abuse in the gateway's flow. This issue is outside the scope of this PR.
</blockquote></details>

I deleted this marker because I found the issue.
The method was never called - which was a "bug" (sort of). See: #2982.

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2948)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @ArniStarkware)

___
*[`crates/starknet_gateway/src/gateway.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2948#-OF1qXs4Csvg_ZhJOG9J:-OF1qXs4Csvg_ZhJOG9K:bwzy49k) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a7046eef98cd5fe0317aa3dbf9cc4751ee9b5/crates/starknet_gateway/src/gateway.rs#L33)):*
> ```XML
> 
> pub struct Gateway {
>     pub config: GatewayConfig,
> ```

Is this change relevant to benchmark test prep? 
___
*[`crates/starknet_gateway/src/gateway.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2948#-OF1qNHV0biMF_COhU5L:-OF1qNHV0biMF_COhU5M:b-m1z9ri) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a7046eef98cd5fe0317aa3dbf9cc4751ee9b5/crates/starknet_gateway/src/gateway.rs#L64)):*
> ```XML
>     }
> 
>     #[instrument(skip(self), ret)]
> ```

Can you please explain why you removed it?



_Code quote:_
```XML
#[instrument(skip(self), ret)]
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2948)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/starknet_gateway/src/gateway.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2948#-OF1qXs4Csvg_ZhJOG9J:-OF1sV2H4LapRHmpS71S:b-sj73b1) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a7046eef98cd5fe0317aa3dbf9cc4751ee9b5/crates/starknet_gateway/src/gateway.rs#L33)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Is this change relevant to benchmark test prep?
</blockquote></details>

No, but the compiler yelled at me to remove it, so I did.
(It did not yell before because in the original line, the struct `Gateway` was `pub`.)
___
*[`crates/starknet_gateway/src/gateway.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2948#-OF1qNHV0biMF_COhU5L:-OF1s0OnEsLkCDEnQYk7:bds322r) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a7046eef98cd5fe0317aa3dbf9cc4751ee9b5/crates/starknet_gateway/src/gateway.rs#L64)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Can you please explain why you removed it?
</blockquote></details>

There are two methods called `add_tx`. The function of the `Gateway` kept this marker. This marker is for tracing. It creates a logs subgroup.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2948)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @ayeletstarkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2948#-OF1w8kA1MTYjD5JRo2w:-OF1w8kA1MTYjD5JRo2x:b-gh0u2m) (no related file):*
This is what we talked about f2f? Is this PR still needed?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2948)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @ayeletstarkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2948#-OF1w8kA1MTYjD5JRo2w:-OF2Jmb0DoVqvlrQehNL:b-w3fiwi) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This is what we talked about f2f? Is this PR still needed?
</blockquote></details>

It is not what we talked about F2F. This PR is needed.
I had problems creating a mock mempool (Some issues with dependencies and `cfg`). These issues can be avoided with this PR.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2948)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5, @ArniStarkware, and @ayeletstarkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2948#-OF1w8kA1MTYjD5JRo2w:-OF2RYkmAiWizBa5eJRA:b9pfpa0) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

It is not what we talked about F2F. This PR is needed.
I had problems creating a mock mempool (Some issues with dependencies and `cfg`). These issues can be avoided with this PR.
</blockquote></details>

Can you explain what you are trying to solve here?
___
*[`crates/starknet_gateway/src/gateway.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2948#-OF2ReS6DW0VTlLEM7i1:-OF2ReS6DW0VTlLEM7i2:b-l3kbob) ([raw file](https://github.com/starkware-libs/sequencer/blob/f191cec07c39351f21cd4727d9ba61b7f1f991eb/crates/starknet_gateway/src/gateway.rs#L100)):*
> ```XML
>         p2p_message_metadata: Option<BroadcastedMessageMetadata>,
>     ) -> GatewayResult<TransactionHash> {
>         let add_tx_args = self.business_logic.add_tx(tx, p2p_message_metadata).await?;
> ```

cont. of the previous comment



_Suggestion:_
```XML
let add_tx_args = AddTransactionArgsWrapper { 
    args: self.business_logic.add_tx(tx).await?,
    p2p_message_metadata
};
    
```
___
*[`crates/starknet_gateway/src/gateway.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2948#-OF2RCUo4Xpz71g_xtNF:-OF2RCUpEoz9i7ZfudRg:b-eikfir) ([raw file](https://github.com/starkware-libs/sequencer/blob/416c27745d0cd0ab9a2ab88b93f2cea22fec3144/crates/starknet_gateway/src/gateway.rs#L78)):*
> ```XML
>         Ok(AddTransactionArgsWrapper { args: add_tx_args, p2p_message_metadata })
>     }
> }
> ```

this function is not doing anything with p2p_message_metadata, 
consider removing it from the input.



_Suggestion:_
```XML
    pub async fn add_tx(
        &self,
        tx: RpcTransaction,
    ) -> GatewayResult<AddTransactionArgs> {
        info!("Processing tx");
        let blocking_task = ProcessTxBlockingTask::new(self, tx);
        // Run the blocking task in the current span.
        let curr_span = Span::current();
        let add_tx_args =
            tokio::task::spawn_blocking(move || curr_span.in_scope(|| blocking_task.process_tx()))
                .await
                .map_err(|join_err| {
                    error!("Failed to process tx: {}", join_err);
                    GatewaySpecError::UnexpectedError { data: "Internal server error".to_owned() }
                })??;

        Ok(add_tx_args)
    }
}
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2948)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5, @ArniStarkware, and @ayeletstarkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2948#-OF1w8kA1MTYjD5JRo2w:-OF2SNpk3dGhqlNOVH-0:b3kqx) (no related file):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Can you explain what you are trying to solve here?
</blockquote></details>

.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2948)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5, @ArniStarkware, and @ayeletstarkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2948#-OF1w8kA1MTYjD5JRo2w:-OF2STDY7ptEU4ASFoJ5:b3kqx) (no related file):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

.
</blockquote></details>

.

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2948)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @ayeletstarkware)

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2948#-:-OFHdkqM5pncFBD7l98O:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
