### PR TITLE
feat(blockifier): add get_execution_info_v1 syscall

### PR DESCRIPTION
**Pull request by varex83**

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @varex83)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1735#-OB4UBYP6Qf1EbHI_uNF:-OB4UBYP6Qf1EbHI_uNG:bozlb7s) ([raw file](https://github.com/starkware-libs/sequencer/blob/60e2392722b8f67ae9536726d987f21fd8330338/crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs#L267)):*
> ```XML
>     let word_in_hex: String =
>         s.as_bytes().iter().fold(String::new(), |s, byte| s + (&format!("{:02x}", byte)));
>     [prefix, &padding_zeros, &word_in_hex].into_iter().collect()
> ```

Why did you remove this test?



_Code quote:_
```XML
#[test]
fn test_gas_types_constants() {
    assert_eq!(str_to_32_bytes_in_hex("L1_GAS"), Resource::L1Gas.to_hex());
    assert_eq!(str_to_32_bytes_in_hex("L2_GAS"), Resource::L2Gas.to_hex());
    assert_eq!(str_to_32_bytes_in_hex("L1_DATA"), Resource::L1DataGas.to_hex());
}

fn str_to_32_bytes_in_hex(s: &str) -> String {
    if s.len() > 32 {
        panic!("Unsupported input of length > 32.")
    }
    let prefix = "0x";
    let padding_zeros = "0".repeat(64 - s.len() * 2); // Each string char is 2 chars in hex.
    let word_in_hex: String =
        s.as_bytes().iter().fold(String::new(), |s, byte| s + (&format!("{:02x}", byte)));
    [prefix, &padding_zeros, &word_in_hex].into_iter().collect()
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1735#-OB4VNIl-6aP2ldhscqD:-OB4VNIl-6aP2ldhscqE:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c89a2d62970843125b16da125300be9b259ff19e/crates/blockifier/src/transaction/objects.rs#L92)):*
> ```XML
>     pub fn max_fee(&self) -> TransactionFeeResult<Fee> {
>         match self {
>             Self::Current(_context) => Ok(Fee(0)),
> ```





_Suggestion:_
```XML
Self::Current(_) => Ok(Fee(0)),
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @varex83)

___
*[`crates/blockifier/src/transaction/objects.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1735#-OB4Vp036aZE_aybWpJw:-OB4Vp036aZE_aybWpJx:b5qjggm) ([raw file](https://github.com/starkware-libs/sequencer/blob/c89a2d62970843125b16da125300be9b259ff19e/crates/blockifier/src/transaction/objects.rs#L90)):*
> ```XML
>     }
> 
>     pub fn max_fee(&self) -> TransactionFeeResult<Fee> {
> ```

Why are you returning a result? Where can it fail? 



_Code quote:_
```XML
TransactionFeeResult
```

**Review by varex83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1735#-OB4UBYP6Qf1EbHI_uNF:-OB5Hp_t1l-V5v2bchfJ:bhc36a7) ([raw file](https://github.com/starkware-libs/sequencer/blob/60e2392722b8f67ae9536726d987f21fd8330338/crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs#L267)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why did you remove this test?
</blockquote></details>

Done

Most likely some rebasing problems :eyes: 
___
*[`crates/blockifier/src/transaction/objects.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1735#-OB4Vp036aZE_aybWpJw:-OB5Hm1_Bk93ZXKJ-7nK:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/c89a2d62970843125b16da125300be9b259ff19e/crates/blockifier/src/transaction/objects.rs#L90)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why are you returning a result? Where can it fail?
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/objects.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1735#-OB4VNIl-6aP2ldhscqD:-OB5HoI1CWV1gNn9ha3L:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/c89a2d62970843125b16da125300be9b259ff19e/crates/blockifier/src/transaction/objects.rs#L92)):*
> ```XML
>     pub fn max_fee(&self) -> TransactionFeeResult<Fee> {
>         match self {
>             Self::Current(_context) => Ok(Fee(0)),
> ```

Done

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware and @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735#-:-OBa-K1iCMTB31hQHA5-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @varex83)

___
*[`crates/blockifier/src/transaction/objects.rs` line 101 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1735#-OBanizSEp_Wa7m8g9gb:-OBanizT7-RHZgi2KFpO:ba1prga) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3a504e868e566e8971636f57febfae6d9e7a86a/crates/blockifier/src/transaction/objects.rs#L101)):*
> ```XML
>     }
> 
>     pub fn max_fee(&self) -> Fee {
> ```

Please remove `max_fee_for_execution_info` and use this one



_Suggestion:_
```XML
max_fee_for_execution_info_syscall
```

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1, @varex83, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 118 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1735#-OBapVwS1coOnWxJpAYZ:-OBdMvEc8Mer679CHgIN:byem0qp) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3a504e868e566e8971636f57febfae6d9e7a86a/crates/blockifier/src/test_utils/contracts.rs#L118)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why can't you use the existing contract?
</blockquote></details>

This is how the contract in the test utils is defined. For now, native has its directory for both contracts and compiled contracts. This PR should fix this #1455

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @varex83)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 118 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1735#-OBapVwS1coOnWxJpAYZ:-OBdUXnn1NmTXy8aMGO9:bb6u032) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3a504e868e566e8971636f57febfae6d9e7a86a/crates/blockifier/src/test_utils/contracts.rs#L118)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

This is how the contract in the test utils is defined. For now, native has its directory for both contracts and compiled contracts. This PR should fix this #1455
</blockquote></details>

Cool

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware, @noaov1, and @varex83)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 118 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1735#-OBapVwS1coOnWxJpAYZ:-OBdrWMT-gqtPRRR17lj:bvu7pgo) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3a504e868e566e8971636f57febfae6d9e7a86a/crates/blockifier/src/test_utils/contracts.rs#L118)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Cool
</blockquote></details>

Can we move forward with this PR?

**Review by varex83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 101 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1735#-OBanizSEp_Wa7m8g9gb:-OBeBNssDSOOWubP-nwW:b-bxrx6m) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3a504e868e566e8971636f57febfae6d9e7a86a/crates/blockifier/src/transaction/objects.rs#L101)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Please remove `max_fee_for_execution_info` and use this one
</blockquote></details>

Do you mean to remove this `max_fee` function, and use `max_fee_for_execution_info` instead?

**Review by varex83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 118 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1735#-OBapVwS1coOnWxJpAYZ:-OBeCSgN5NRco-EgoSYL:bifqozc) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3a504e868e566e8971636f57febfae6d9e7a86a/crates/blockifier/src/test_utils/contracts.rs#L118)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can we move forward with this PR?
</blockquote></details>

One main reason we use `SierraExecutionInfoV1Contract` is to test `get_execution_info_v1` using the same tests we use for `get_execution_info_v2`. The difference is in the imports, for v2 we use  `starknet::get_execution_info`, and for v1 - `starknet::syscalls::get_execution_info_syscall`.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 1 of 3 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @varex83)

___
*[`crates/blockifier/src/transaction/objects.rs` line 101 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1735#-OBanizSEp_Wa7m8g9gb:-OBeJHLC5enE5MWDILcG:b3klkjl) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3a504e868e566e8971636f57febfae6d9e7a86a/crates/blockifier/src/transaction/objects.rs#L101)):*
<details><summary><i>Previously, varex83 (Bohdan Ohorodnii) wrote…</i></summary><blockquote>

Do you mean to remove this `max_fee` function, and use `max_fee_for_execution_info` instead?
</blockquote></details>

Rename `max_fee` -> `max_fee_for_execution_info_syscall`, delete `max_fee_for_execution_info`
and use your function instead

**Review by varex83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 101 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1735#-OBanizSEp_Wa7m8g9gb:-OBeSbph0UMAZ0O_f1pb:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3a504e868e566e8971636f57febfae6d9e7a86a/crates/blockifier/src/transaction/objects.rs#L101)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Rename `max_fee` -> `max_fee_for_execution_info_syscall`, delete `max_fee_for_execution_info`
and use your function instead
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r4, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735#-:-OBeTNHG0PukMUKkIjih:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1735)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @noaov1)

**Pull request merged**
