### PR TITLE
chore(blockifier): added gas vector computation mode to StarknetResources::to_gas_vector

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/705)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@TzahiTaub +reviewer:@Yoni-Starkware +reviewer:@nimrod-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/705#-:-O60TUuVBmd98EmgBhno:b-opgrxl)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @nimrod-starkware, @TzahiTaub, and @Yoni-Starkware)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/705)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 340 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/705#-O60fMtp7d-LnQiDfIj3:-O60sF9G5oMocp_QoEmI:b-b0vhc2) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ed38be6dcfea256d5f2e089c1b00fe3b4c1473e/crates/blockifier/src/transaction/objects.rs#L340)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

please make it a docstring (three slashes) and indicate that the result is in l1 gas units
</blockquote></details>

This function isn't really API, so I'm not sure docstring is the right choice, but looks like other functions use docstrings so I'll also use it. Done
___
*[`crates/blockifier/src/transaction/objects.rs` line 395 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/705#-O60fyIq1fnLneaDUPmj:-O60tpvJDjPoH8btCgkC:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ed38be6dcfea256d5f2e089c1b00fe3b4c1473e/crates/blockifier/src/transaction/objects.rs#L395)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

WDYT? 
It might be confusing
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/objects.rs` line 408 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/705#-O60f1Iu0mqCdY0AQR67:-O60uAOA3k_n-hvVTyKW:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ed38be6dcfea256d5f2e089c1b00fe3b4c1473e/crates/blockifier/src/transaction/objects.rs#L408)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

WDYT? 
It might be confusing
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/objects.rs` line 456 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/705#-O60ednIBdGEnrJZhSAI:-O60uuSR0aAkHFUcVBIx:b-5qo1cu) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ed38be6dcfea256d5f2e089c1b00fe3b4c1473e/crates/blockifier/src/transaction/objects.rs#L456)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Please add docstring
</blockquote></details>

Do you have a suggestion?
I think it's self explanatory

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/705)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/objects.rs` line 328 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/705#-O61Il3YA_hOAkJv2M5X:-O61JpRa00Yw5MX8BZOU:b-dkdz75) ([raw file](https://github.com/starkware-libs/sequencer/blob/84e913b7a70ec42069ab763cb9516533b9ef1dff/crates/blockifier/src/transaction/objects.rs#L328)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Consider moving these three to a function the gets the gas mode and returns a gas vector.
We need to thing of a name. Maybe `get_l2_storage_cost`?
</blockquote></details>

No, that's a bad name. Let's think

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/705)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/objects.rs` line 328 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/705#-O61Il3YA_hOAkJv2M5X:-O61LuEt2KWc18nKHMKa:b-7x3y24) ([raw file](https://github.com/starkware-libs/sequencer/blob/84e913b7a70ec42069ab763cb9516533b9ef1dff/crates/blockifier/src/transaction/objects.rs#L328)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

No, that's a bad name. Let's think
</blockquote></details>

`get_l2_archival_data_resources`

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/705)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/objects.rs` line 328 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/705#-O61Il3YA_hOAkJv2M5X:-O61QAT971TmpFHUVeSK:b-pkgvae) ([raw file](https://github.com/starkware-libs/sequencer/blob/84e913b7a70ec42069ab763cb9516533b9ef1dff/crates/blockifier/src/transaction/objects.rs#L328)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

`get_l2_archival_data_resources`
</blockquote></details>

`get_l2_archival_data_cost`

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/705)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 340 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/705#-O60fMtp7d-LnQiDfIj3:-O6BvKMU-hFVyvo4igD_:bp8nyr8) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ed38be6dcfea256d5f2e089c1b00fe3b4c1473e/crates/blockifier/src/transaction/objects.rs#L340)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@nimrod-starkware should refactor this to return L2 gas here, right?
Please add a TODO on him
</blockquote></details>

Done (also in `get_code_cost` & `get_events_cost`)
___
*[`crates/blockifier/src/transaction/objects.rs` line 324 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/705#-O61GwOt33H0-f0S8urk:-O6Br5t20XfNDon5Ex_S:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/84e913b7a70ec42069ab763cb9516533b9ef1dff/crates/blockifier/src/transaction/objects.rs#L324)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

The context is in the function name.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 328 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/705#-O61Il3YA_hOAkJv2M5X:-O6BsFJC5J3RTkzHku_s:bpge4r4) ([raw file](https://github.com/starkware-libs/sequencer/blob/84e913b7a70ec42069ab763cb9516533b9ef1dff/crates/blockifier/src/transaction/objects.rs#L328)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

`get_l2_archival_data_cost`
</blockquote></details>

Done. WYT of the docstring?
`/// Returns the cost of the transaction's calldata, signature, code, and events.`
___
*[`crates/blockifier/src/transaction/objects.rs` line 454 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/705#-O61JLZd8xI27IGd6LJF:-O6BqzNm0N2EXXHtpMpt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/84e913b7a70ec42069ab763cb9516533b9ef1dff/crates/blockifier/src/transaction/objects.rs#L454)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

`All/Full/AllGas/Default`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 491 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/705#-O6C-Tj95-HHJjFFnnR6:-O6C-TjADavv0KMzYRw9:b1rtv6x) ([raw file](https://github.com/starkware-libs/sequencer/blob/fe974f91136194a34dda64916a806c914ffd4645/crates/blockifier/src/transaction/objects.rs#L491)):*
> ```XML
>     }
> 
>     // TODO(Amos: 1/10/2024): Add and use a gas vector computation mode param in this function.
> ```

I noticed I forgot to do this.
it looks non trivial so I think I'll do it in a separate PR



_Code quote:_
```XML
// TODO(Amos: 1/10/2024): Add and use a gas vector computation mode param in this function.
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/705)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/objects.rs` line 328 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/705#-O61Il3YA_hOAkJv2M5X:-O6FAHkaCNa6KNq6a0gX:bhcn0un) ([raw file](https://github.com/starkware-libs/sequencer/blob/84e913b7a70ec42069ab763cb9516533b9ef1dff/crates/blockifier/src/transaction/objects.rs#L328)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Done. WYT of the docstring?
`/// Returns the cost of the transaction's calldata, signature, code, and events.`
</blockquote></details>

```
/// Returns the cost of the transaction's archival data, for example, calldata, signature, code, and events.
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 491 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/705#-O6C-Tj95-HHJjFFnnR6:-O6FBCNN0a6FqRD0NYIw:b-orbfxq) ([raw file](https://github.com/starkware-libs/sequencer/blob/fe974f91136194a34dda64916a806c914ffd4645/crates/blockifier/src/transaction/objects.rs#L491)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I noticed I forgot to do this.
it looks non trivial so I think I'll do it in a separate PR
</blockquote></details>

Note: this function is only used [here](https://github.com/starkware-libs/sequencer/blob/ddc8f516c3befa92ccfbd3382b8d5b718fe9bb98/crates/native_blockifier/src/py_block_executor.rs#L65) - and you have the gas vector in the `receipt` there.
So, you can move this function up to the receipt, and you won't need to pass this argument

**Review by nimrod-starkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/705)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @TzahiTaub)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/705)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 328 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/705#-O61Il3YA_hOAkJv2M5X:-O6Fdg7r9zPE9LuXZ5Rl:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/84e913b7a70ec42069ab763cb9516533b9ef1dff/crates/blockifier/src/transaction/objects.rs#L328)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

```
/// Returns the cost of the transaction's archival data, for example, calldata, signature, code, and events.
```
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/objects.rs` line 491 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/705#-O6C-Tj95-HHJjFFnnR6:-O6FghO3DfIseIGe-U5f:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fe974f91136194a34dda64916a806c914ffd4645/crates/blockifier/src/transaction/objects.rs#L491)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Note: this function is only used [here](https://github.com/starkware-libs/sequencer/blob/ddc8f516c3befa92ccfbd3382b8d5b718fe9bb98/crates/native_blockifier/src/py_block_executor.rs#L65) - and you have the gas vector in the `receipt` there.
So, you can move this function up to the receipt, and you won't need to pass this argument
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
Nice!
:lgtm:

> Reviewed 2 of 4 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/705#-:-O6Ft8F_DOLV6qS7Dw6S:b-ojic6h)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by nimrod-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/705)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
