### PR TITLE
chore: add create wrapper server macro

### PR DESCRIPTION
**Pull request by nadin-Starkware**
**Stack**:
- #1909
- #1878 ⬅
- #1877
- #1876
- #1874

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1878)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/sequencer_node/src/servers.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1878#-OBA-EwmE1dq7BQEdEKy:-OBA-EwmE1dq7BQEdEKz:bdmjm0d) ([raw file](https://github.com/starkware-libs/sequencer/blob/425d716d61889a6c256c03fb8c5e700ed4d31b0f/crates/sequencer_node/src/servers.rs#L141)):*
> ```XML
>         }
>     };
> }
> ```

Same comments for the previous macros :pray: 



_Code quote:_
```XML
/// A macro to create a WrapperServer based on the component's execution mode.
///
/// This macro conditionally creates a WrapperServer instance for a given component based on
/// whether the execution mode is enabled or disabled. It expects execution_mode to be passed
/// as a reference.
///
/// # Arguments
///
/// * $execution_mode - A reference to the execution mode to evaluate, expected to be of type
///   &ComponentExecutionMode.
/// * $component - The optional component that will be taken to initialize the server if the mode is
///   enabled.
///
/// # Returns
///
/// An `Option<Box<WrapperServer<ComponentType>>>` containing the server if the execution mode is
/// enabled, or `None` if the execution mode is `Disabled`.
///
/// # Example
///
/// ```rust, ignore
/// // Assuming ComponentExecutionMode and components are defined, and WrapperServer
/// // has a new method that accepts a component.
/// let consensus_manager_server = create_wrapper_server!(
///     &config.components.consensus_manager.execution_mode,
///     components.consensus_manager
/// );
///
/// match consensus_manager_server {
///     Some(server) => println!("Server created: {:?}", server),
///     None => println!("Server not created because the execution mode is disabled."),
/// }
/// ```
macro_rules! create_wrapper_server {
    ($execution_mode:expr, $component:expr) => {
        match *$execution_mode {
            ComponentExecutionMode::LocalExecutionWithRemoteDisabled
            | ComponentExecutionMode::LocalExecutionWithRemoteEnabled => {
                Some(Box::new(WrapperServer::new(
                    $component
                        .take()
                        .expect(concat!(stringify!($component), " is not initialized.")),
                )))
            }
            ComponentExecutionMode::Disabled => None,
        }
    };
}
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1878)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/sequencer_node/src/servers.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1878#-OBA-EwmE1dq7BQEdEKy:-OBL1Rdq-Gcy9YmKsOFf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b73f76e7e47698c14198562083290314015bda86/crates/sequencer_node/src/servers.rs#L141)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Same comments for the previous macros :pray:
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1878#-:-OBLNEvRCkWP3k2fYhja:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1878)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Comment by nadin-Starkware** [comment]
✓ Commit merged in pull request [#1909](https://github.com/starkware-libs/sequencer/pull/1909)

**Pull request closed without merging**
