### PR TITLE
refactor(batcher): add propose_tx_provider fixture

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
* **#1996** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1996?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Yael-Starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1996)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1996#-OBZYQiw1QcFVrD3PBai:-OBZYQix1tcpSF7u-jDa:b-bzm336) (no related file):*
IIUC, this change means that we can't get txs from the TxProvider in the proposal_manager tests, right?
___
*[`crates/batcher/src/transaction_provider.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1996#-OBZY5P-0qwLqHIf1qWs:-OBZY5P-0qwLqHIf1qWt:bhlqka2) ([raw file](https://github.com/starkware-libs/sequencer/blob/5adc787ca4444ac0bee7b14f8a8041ab978949b5/crates/batcher/src/transaction_provider.rs#L31)):*
> ```XML
> }
> 
> #[cfg_attr(test, derive(Clone))]
> ```

Why not derive Clone anyway?
___
*[`crates/batcher/src/transaction_provider.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1996#-OBZYFLqBdWV73ytuPP7:-OBZYFLqBdWV73ytuPP8:b-jh50bs) ([raw file](https://github.com/starkware-libs/sequencer/blob/5adc787ca4444ac0bee7b14f8a8041ab978949b5/crates/batcher/src/transaction_provider.rs#L41)):*
> ```XML
> 
> // Keeps track of whether we need to fetch L1 handler transactions or mempool transactions.
> #[cfg_attr(test, derive(Clone))]
> ```

Copy instead of Clone

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1996)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/batcher/src/transaction_provider.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1996#-OBZY5P-0qwLqHIf1qWs:-OBZnvmF-YDWsgQMKE-P:b-8b51mp) ([raw file](https://github.com/starkware-libs/sequencer/blob/5adc787ca4444ac0bee7b14f8a8041ab978949b5/crates/batcher/src/transaction_provider.rs#L31)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why not derive Clone anyway?
</blockquote></details>

because we are not using it outside of testing.
Though generally, it is ok to clone it.

I thought we are pretty strict regarding adding derive(Clone) to object.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1996)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1996#-OBZYQiw1QcFVrD3PBai:-OBZoj5o6BBO2Ou23-Ph:bvnrdzd) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

IIUC, this change means that we can't get txs from the TxProvider in the proposal_manager tests, right?
</blockquote></details>

right, which makes sense since the proposal manager does not get txs from the tx_provider.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1996)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/batcher/src/transaction_provider.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1996#-OBZYFLqBdWV73ytuPP7:-OB_EWan4kE9YV8ObMaV:bvsqfti) ([raw file](https://github.com/starkware-libs/sequencer/blob/5adc787ca4444ac0bee7b14f8a8041ab978949b5/crates/batcher/src/transaction_provider.rs#L41)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Copy instead of Clone
</blockquote></details>

doesn't work with the SharedMempoolClient and SharedL1Provider.

I think it's ok derive Clone for testing or even everywhere.
it is a clonable object.

wdyt?

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1996)* status: all files reviewed, 5 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/transaction_provider.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1996#-OBZYFLqBdWV73ytuPP7:-OB_OqdkC3lJlo0dRDAx:b-ntll86) ([raw file](https://github.com/starkware-libs/sequencer/blob/5adc787ca4444ac0bee7b14f8a8041ab978949b5/crates/batcher/src/transaction_provider.rs#L41)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

doesn't work with the SharedMempoolClient and SharedL1Provider.

I think it's ok derive Clone for testing or even everywhere.
it is a clonable object.

wdyt?
</blockquote></details>

Clone is okay, I wouldn't derive Copy, that's for more primitive types.
___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1996#-OB_OCxWBHsXCEYTh8h2:-OB_OCxWBHsXCEYTh8h3:b-6lx13) ([raw file](https://github.com/starkware-libs/sequencer/blob/b065f329ffcd9839f2e9463860df5dce04d51d1b/crates/starknet_batcher/src/proposal_manager_test.rs#L93)):*
> ```XML
> fn propose_tx_provider() -> ProposeTransactionProvider {
>     ProposeTransactionProvider::new(
>         Arc::new(MockMempoolClient::new()),
> ```

Can't we just mock the tx provider instead of mocking its fields?
___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 224 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1996#-OB_MJpMDgfyNWdb22Z3:-OB_MJpMDgfyNWdb22Z4:b-1ut48) ([raw file](https://github.com/starkware-libs/sequencer/blob/b065f329ffcd9839f2e9463860df5dce04d51d1b/crates/starknet_batcher/src/proposal_manager_test.rs#L224)):*
> ```XML
>     // Generate a block builder with a very long build block operation.
>     init_mock_dependencies.expect_long_build_block(1);
>     let mut proposal_manager = init_proposal_manager(init_mock_dependencies);
> ```

I would remove this init here. And in general, do we need the `init` prefix everywhere in this test file? Does it add readbility?



_Suggestion:_
```XML
proposal_manager
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1996)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1996#-OB_OCxWBHsXCEYTh8h2:-OB_hSkz6wGl6VDSB_nt:b-jkm5ss) ([raw file](https://github.com/starkware-libs/sequencer/blob/b065f329ffcd9839f2e9463860df5dce04d51d1b/crates/starknet_batcher/src/proposal_manager_test.rs#L93)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can't we just mock the tx provider instead of mocking its fields?
</blockquote></details>

Thought about it too, but it is not possible since build_proposal gets ProposeTransactionProvider and not the generic trait (same for validate_proposal).

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1996)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 224 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1996#-OB_MJpMDgfyNWdb22Z3:-OB_i8il3aCvs2UIGO0d:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b065f329ffcd9839f2e9463860df5dce04d51d1b/crates/starknet_batcher/src/proposal_manager_test.rs#L224)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I would remove this init here. And in general, do we need the `init` prefix everywhere in this test file? Does it add readbility?
</blockquote></details>

Done.
___
*[`crates/batcher/src/transaction_provider.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1996#-OBZYFLqBdWV73ytuPP7:-OB_iGFN4rVPjFMEAZE1:b9z0mk8) ([raw file](https://github.com/starkware-libs/sequencer/blob/5adc787ca4444ac0bee7b14f8a8041ab978949b5/crates/batcher/src/transaction_provider.rs#L41)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Clone is okay, I wouldn't derive Copy, that's for more primitive types.
</blockquote></details>

so I removed the only for tests part

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1996)* status: all files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 224 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1996#-OB_MJpMDgfyNWdb22Z3:-OB_pUJ72gEeYlBjRrU1:bz2chv) ([raw file](https://github.com/starkware-libs/sequencer/blob/b065f329ffcd9839f2e9463860df5dce04d51d1b/crates/starknet_batcher/src/proposal_manager_test.rs#L224)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant also in mock dependencies and everywhere in the file.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1996)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 224 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1996#-OB_MJpMDgfyNWdb22Z3:-OBdJorc81Pz0wYUPc_V:b276yf0) ([raw file](https://github.com/starkware-libs/sequencer/blob/b065f329ffcd9839f2e9463860df5dce04d51d1b/crates/starknet_batcher/src/proposal_manager_test.rs#L224)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I meant also in mock dependencies and everywhere in the file.
</blockquote></details>

sorry, haven't read through.
Done.

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1996)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Pull request merged**
