### PR TITLE
feat(blockifier): replace the aliases in the state diff

### PR DESCRIPTION
**Pull request by yoavGrs**

### CODE REVIEW

**Comment by yoavGrs** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2766?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2767** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2767?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2766** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2766?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2766?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2765** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2765?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2674** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2674?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2675](https://github.com/starkware-libs/sequencer/pull/2675) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2675?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2535** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2535?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2534** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2534?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2766)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression_test.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2766#-OEPMh484DTx1bcuoH7Y:-OEPMh484DTx1bcuoH7Z:bmk8fvg) ([raw file](https://github.com/starkware-libs/sequencer/blob/af1d7cb36966fd999c0e46624bb10a37c03401cc/crates/blockifier/src/state/stateful_compression_test.rs#L0)):*
can you implement a `decompress` test util and use it to compare original and compressed+decompressed diff?
___
*[`crates/blockifier/src/state/stateful_compression_test.rs` line 271 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2766#-OEPMxnF8oVE0AELqq1n:-OEPMxnG81FsErScZ6cg:b-ihw9d8) ([raw file](https://github.com/starkware-libs/sequencer/blob/af1d7cb36966fd999c0e46624bb10a37c03401cc/crates/blockifier/src/state/stateful_compression_test.rs#L271)):*
> ```XML
>             .into_iter()
>             .collect(),
>         declared_contracts: vec![(ClassHash(Felt::THREE), true)].into_iter().collect(),
> ```

put large values here? to make sure these are not compressed, but for the correct reason



_Code quote:_
```XML
        compiled_class_hashes: vec![(ClassHash(Felt::ONE), CompiledClassHash(Felt::ZERO))]
            .into_iter()
            .collect(),
        declared_contracts: vec![(ClassHash(Felt::THREE), true)].into_iter().collect(),
```
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2766#-OEPLR0g-lzEx9HyLf9O:-OEPLR0g-lzEx9HyLf9P:b-sz2o0p) ([raw file](https://github.com/starkware-libs/sequencer/blob/af1d7cb36966fd999c0e46624bb10a37c03401cc/crates/blockifier/src/state/stateful_compression.rs#L161)):*
> ```XML
>             .class_hashes
>             .insert(alias_compressor.compress_address(address)?, *class_hash);
>     }
> ```

we always compress class hashes? @Yoni-Starkware @nimrod-starkware 



_Code quote:_
```XML
    for (address, class_hash) in state_diff.class_hashes.iter() {
        compressed_state_diff
            .class_hashes
            .insert(alias_compressor.compress_address(address)?, *class_hash);
    }
```
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2766#-OEPLgfr0a3t0ftByTDd:-OEPLgfr0a3t0ftByTDe:b-jpgaf4) ([raw file](https://github.com/starkware-libs/sequencer/blob/af1d7cb36966fd999c0e46624bb10a37c03401cc/crates/blockifier/src/state/stateful_compression.rs#L174)):*
> ```XML
>     compressed_state_diff.declared_contracts.extend(state_diff.declared_contracts.iter());
> 
>     Ok(compressed_state_diff)
> ```

for forward-compatibility (if fields are added to the state diff) better to use `..` notation and explicitly replace specific compressed fields. WDYT?



_Suggestion:_
```XML
    let alias_compressor = AliasCompressor { state, alias_contract_address };

    let nonces: ... = state_diff.nonces.iter().map(|(address, nonce)| {
        (alias_compressor.compress_address(address)?, *nonce)
    }).collect();
    let class_hashes: ... = state_diff.class_hashes.iter().map(|(address, class_hash)| {
        (alias_compressor.compress_address(address)?, *class_hash)
    }).collect();
    let storage: ... = state_diff.storage.iter().map(|((address, key), value)| {
        (
            (
                alias_compressor.compress_address(address)?,
                alias_compressor.compress_storage_key(key, address)?,
            ),
            *value,
        )
    }).collect();

    Ok(StateMaps {
        nonces,
        class_hashes,
        storage,
        ..state_diff
    })
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2766)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2766#-OEPLgfr0a3t0ftByTDd:-OEPVB8CB6kTs5QN2f6e:b-h7a05q) ([raw file](https://github.com/starkware-libs/sequencer/blob/af1d7cb36966fd999c0e46624bb10a37c03401cc/crates/blockifier/src/state/stateful_compression.rs#L174)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

for forward-compatibility (if fields are added to the state diff) better to use `..` notation and explicitly replace specific compressed fields. WDYT?
</blockquote></details>

Done.
(Without `?` in closures)
___
*[`crates/blockifier/src/state/stateful_compression_test.rs` line 271 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2766#-OEPMxnF8oVE0AELqq1n:-OEUKsxX4uqeurvhBM8d:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/af1d7cb36966fd999c0e46624bb10a37c03401cc/crates/blockifier/src/state/stateful_compression_test.rs#L271)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

put large values here? to make sure these are not compressed, but for the correct reason
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/stateful_compression_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2766#-OEPMh484DTx1bcuoH7Y:-OEUK1NQ8dRYQcLnnLxO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/af1d7cb36966fd999c0e46624bb10a37c03401cc/crates/blockifier/src/state/stateful_compression_test.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you implement a `decompress` test util and use it to compare original and compressed+decompressed diff?
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2766)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @yoavGrs)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2766)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2766#-OEPLR0g-lzEx9HyLf9O:-OEUTAla7kH9Zef0uO7o:b-slnj8i) ([raw file](https://github.com/starkware-libs/sequencer/blob/af1d7cb36966fd999c0e46624bb10a37c03401cc/crates/blockifier/src/state/stateful_compression.rs#L161)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we always compress class hashes? @Yoni-Starkware @nimrod-starkware
</blockquote></details>

In this code, we compress only the contract address.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2766)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2766#-OEPLR0g-lzEx9HyLf9O:-OEUVJxO4x1NQ3m53rlt:ba1rox) ([raw file](https://github.com/starkware-libs/sequencer/blob/af1d7cb36966fd999c0e46624bb10a37c03401cc/crates/blockifier/src/state/stateful_compression.rs#L161)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

In this code, we compress only the contract address.
</blockquote></details>

what I meant to ask: if only class hash changed, do we compress the contract address?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2766)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @Yoni-Starkware)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2766)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2766#-OEPLR0g-lzEx9HyLf9O:-OEhPECr5DmbWfRM7bVM:b6ycsi2) ([raw file](https://github.com/starkware-libs/sequencer/blob/af1d7cb36966fd999c0e46624bb10a37c03401cc/crates/blockifier/src/state/stateful_compression.rs#L161)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what I meant to ask: if only class hash changed, do we compress the contract address?
</blockquote></details>

This is what Nimrod wrote to me:
```
for address in address_to_class_hash.keys() | address_to_nonce.keys() | storage_updates.keys():
    if address in storage_updates:
         // allocate aliases for storage keys.
    // allocate alias for address
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2766)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2766#-OEPLgfr0a3t0ftByTDd:-OEh_z5CBi-the075_He:b-k5vtxv) ([raw file](https://github.com/starkware-libs/sequencer/blob/af1d7cb36966fd999c0e46624bb10a37c03401cc/crates/blockifier/src/state/stateful_compression.rs#L174)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Done.
(Without `?` in closures)
</blockquote></details>

@yoavGrs can you please follow Dori's suggestion re `collect` instead of `new` + `for`? (convention)
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 183 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2766#-OEhXidGBapIGPgbhX-Z:-OEhXidGBapIGPgbhX-_:beohux3) ([raw file](https://github.com/starkware-libs/sequencer/blob/1644fd52ff98f9c4cce7b8b6c8499a9450c1ad34/crates/blockifier/src/state/stateful_compression.rs#L183)):*
> ```XML
>     ) -> CompressionResult<ContractAddress> {
>         if contract_address.0 >= MIN_VALUE_FOR_ALIAS_ALLOC {
>             Ok(self.get_alias(StorageKey(contract_address.0))?.try_into()?)
> ```

StorageKey -> AliasKey

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2766)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2766#-OEPLgfr0a3t0ftByTDd:-OEhfRu72VJw_2gzXWtU:bs1dfxc) ([raw file](https://github.com/starkware-libs/sequencer/blob/af1d7cb36966fd999c0e46624bb10a37c03401cc/crates/blockifier/src/state/stateful_compression.rs#L174)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@yoavGrs can you please follow Dori's suggestion re `collect` instead of `new` + `for`? (convention)
</blockquote></details>

@Yoni-Starkware issue is `?` within the iterator closures.
@yoavGrs you can `collect::<Result<_, _>>()?` to solve this though (`collect` is smart enough to collect an `Iterator<Result<_, _>>` into a `Result<_, _>`)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2766)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @yoavGrs)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2766)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2766)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
