### PR TITLE
chore(ci): create security-scan.yml

### PR DESCRIPTION
**Pull request by lotem-starkware**
adding semgrep scans

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/845)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/845)* status: all files reviewed, 7 unresolved discussions (waiting on @lotem-starkware)

___
*[`.github/workflows/security-scan.yml` line 6 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/845#-O78SsaF7m4ddMTIUTDF:-O78SsaF7m4ddMTIUTDG:b-4vig23) ([raw file](https://github.com/starkware-libs/sequencer/blob/c03584b2d45e6589a23a0d388c6c96029e1f8c05/.github/workflows/security-scan.yml#L6)):*
> ```YAML
> on:
>   # Scan changed files in PRs (diff-aware scanning):
>   pull_request: {}
> ```

please specify the explicit events in a pull request that should trigger this job (see other workflows for examples)



_Code quote:_
```YAML
pull_request: {}
```
___
*[`.github/workflows/security-scan.yml` line 8 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/845#-O78SqUi68ZFElF1kPcK:-O78SqUi68ZFElF1kPcL:b-ysbhjs) ([raw file](https://github.com/starkware-libs/sequencer/blob/c03584b2d45e6589a23a0d388c6c96029e1f8c05/.github/workflows/security-scan.yml#L8)):*
> ```YAML
>   pull_request: {}
>   # Scan on-demand through GitHub Actions interface:
>   workflow_dispatch: {}
> ```

what is this event?



_Code quote:_
```YAML
workflow_dispatch: {}
```
___
*[`.github/workflows/security-scan.yml` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/845#-O78T97b0xrkFYsyuonO:-O78T97b0xrkFYsyuonP:b4igqfa) ([raw file](https://github.com/starkware-libs/sequencer/blob/c03584b2d45e6589a23a0d388c6c96029e1f8c05/.github/workflows/security-scan.yml#L10)):*
> ```YAML
>   workflow_dispatch: {}
>   # Scan mainline branches if there are changes to .github/workflows/semgrep.yml:
>   push:
> ```

what about push events to tags? (see other workflows)



_Code quote:_
```YAML
push:
```
___
*[`.github/workflows/security-scan.yml` line 12 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/845#-O78SyNtCuKYwhIfVomS:-O78SyNtCuKYwhIfVomT:b4kmdq9) ([raw file](https://github.com/starkware-libs/sequencer/blob/c03584b2d45e6589a23a0d388c6c96029e1f8c05/.github/workflows/security-scan.yml#L12)):*
> ```YAML
>   push:
>     branches:
>       - main
> ```

`main` is not our only "main" branch, please see other workflows for examples



_Code quote:_
```YAML
    branches:
      - main
```
___
*[`.github/workflows/security-scan.yml` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/845#-O78T3ZT4bcpl2_Ucv2N:-O78T3ZT4bcpl2_Ucv2O:b-w5niob) ([raw file](https://github.com/starkware-libs/sequencer/blob/c03584b2d45e6589a23a0d388c6c96029e1f8c05/.github/workflows/security-scan.yml#L14)):*
> ```YAML
>       - main
>     paths:
>       - .github/workflows/semgrep.yml
> ```

IIUC, this means that `push` events will only trigger this workflow if the semgrep.yml file changed. Is this intended?



_Code quote:_
```YAML
    paths:
      - .github/workflows/semgrep.yml
```
___
*[`.github/workflows/security-scan.yml` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/845#-O78TJ8z1REDqOe_1vKE:-O78TJ8z1REDqOe_1vKF:bch3sk0) ([raw file](https://github.com/starkware-libs/sequencer/blob/c03584b2d45e6589a23a0d388c6c96029e1f8c05/.github/workflows/security-scan.yml#L25)):*
> ```YAML
>     name: semgrep/ci
>     # If you are self-hosting, change the following `runs-on` value:
>     runs-on: ubuntu-latest
> ```

this is not the machine we use in the CI, see other workflows for examples



_Code quote:_
```YAML
runs-on: ubuntu-latest
```
___
*[`.github/workflows/security-scan.yml` line 29 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/845#-O78TObuAeUcoaHrcEow:-O78TObuAeUcoaHrcEox:b-d2v214) ([raw file](https://github.com/starkware-libs/sequencer/blob/c03584b2d45e6589a23a0d388c6c96029e1f8c05/.github/workflows/security-scan.yml#L29)):*
> ```YAML
>     container:
>       # A Docker image with Semgrep installed. Do not change this.
>       image: semgrep/semgrep
> ```

Shouldn't we just add this to the starkware docker used in the CI? @alon-dotan-starkware 



_Code quote:_
```YAML
    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: semgrep/semgrep
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/845)* status: all files reviewed, 4 unresolved discussions (waiting on @lotem-starkware)

___
*[`.github/workflows/security-scan.yml` line 6 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/845#-O78SsaF7m4ddMTIUTDF:-O78tloU8TIpvzC6rxsE:bybprey) ([raw file](https://github.com/starkware-libs/sequencer/blob/c03584b2d45e6589a23a0d388c6c96029e1f8c05/.github/workflows/security-scan.yml#L6)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please specify the explicit events in a pull request that should trigger this job (see other workflows for examples)
</blockquote></details>

are these the only two events you care about?
if I amend a commit and push-force to my PR, will this job trigger? should it?
___
*[`.github/workflows/security-scan.yml` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/845#-O78T97b0xrkFYsyuonO:-O78tuca90ADqbeVTGFx:bnnq58t) ([raw file](https://github.com/starkware-libs/sequencer/blob/c03584b2d45e6589a23a0d388c6c96029e1f8c05/.github/workflows/security-scan.yml#L10)):*
<details><summary><i>Previously, lotem-starkware wrote…</i></summary><blockquote>

why should we limit the run only on specific tags?
</blockquote></details>

no, I mean: without specifying a `tags` trigger, pushing a tag will *never* trigger this workflow

**Review by lotem-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/845)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`.github/workflows/security-scan.yml` line 6 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/845#-O78SsaF7m4ddMTIUTDF:-O796XyN34xrNbPm3fp-:bj8oeoa) ([raw file](https://github.com/starkware-libs/sequencer/blob/c03584b2d45e6589a23a0d388c6c96029e1f8c05/.github/workflows/security-scan.yml#L6)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

are these the only two events you care about?
if I amend a commit and push-force to my PR, will this job trigger? should it?
</blockquote></details>

can i add synchronize and edited?
going over the options i dont find anything other that can be useful
___
*[`.github/workflows/security-scan.yml` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/845#-O78T97b0xrkFYsyuonO:-O796qq3EN9L-0jCTNVH:b-gg85nf) ([raw file](https://github.com/starkware-libs/sequencer/blob/c03584b2d45e6589a23a0d388c6c96029e1f8c05/.github/workflows/security-scan.yml#L10)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no, I mean: without specifying a `tags` trigger, pushing a tag will *never* trigger this workflow
</blockquote></details>

i dont think i understand, tags dont contain code and i dont scan them
___
*[`.github/workflows/security-scan.yml` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/845#-O78T3ZT4bcpl2_Ucv2N:-O793gf-B9SLeRCVBPuK:b-osrrc2) ([raw file](https://github.com/starkware-libs/sequencer/blob/c03584b2d45e6589a23a0d388c6c96029e1f8c05/.github/workflows/security-scan.yml#L14)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

IIUC, this means that `push` events will only trigger this workflow if the semgrep.yml file changed. Is this intended?
</blockquote></details>

changed to the correct path

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/845)* status: all files reviewed, 2 unresolved discussions (waiting on @lotem-starkware)

___
*[`.github/workflows/security-scan.yml` line 6 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/845#-O78SsaF7m4ddMTIUTDF:-O79Fky6A-zL1VaUcrAS:bq0y0e1) ([raw file](https://github.com/starkware-libs/sequencer/blob/c03584b2d45e6589a23a0d388c6c96029e1f8c05/.github/workflows/security-scan.yml#L6)):*
<details><summary><i>Previously, lotem-starkware wrote…</i></summary><blockquote>

can i add synchronize and edited?
going over the options i dont find anything other that can be useful
</blockquote></details>

yes I think that would be good
___
*[`.github/workflows/security-scan.yml` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/845#-O78T97b0xrkFYsyuonO:-O79Fnyk9WHafkxUrQHd:bocc057) ([raw file](https://github.com/starkware-libs/sequencer/blob/c03584b2d45e6589a23a0d388c6c96029e1f8c05/.github/workflows/security-scan.yml#L10)):*
<details><summary><i>Previously, lotem-starkware wrote…</i></summary><blockquote>

i dont think i understand, tags dont contain code and i dont scan them
</blockquote></details>

ah, ok then fine, unblocking
___
*[`.github/workflows/security-scan.yml` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/845#-O78T3ZT4bcpl2_Ucv2N:-O79FuA66ST3ZiPmEruu:b-dijcht) ([raw file](https://github.com/starkware-libs/sequencer/blob/c03584b2d45e6589a23a0d388c6c96029e1f8c05/.github/workflows/security-scan.yml#L14)):*
<details><summary><i>Previously, lotem-starkware wrote…</i></summary><blockquote>

changed to the correct path
</blockquote></details>

still: is this intended? why only run the job on push, when this workflow is changed? because push events are only after PR events, so no point in running again on every push?

**Review by lotem-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/845)* status: all files reviewed, 2 unresolved discussions (waiting on @lotem-starkware)

___
*[`.github/workflows/security-scan.yml` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/845#-O78T3ZT4bcpl2_Ucv2N:-O79HlyS0BySGcHKF7VF:bype8km) ([raw file](https://github.com/starkware-libs/sequencer/blob/c03584b2d45e6589a23a0d388c6c96029e1f8c05/.github/workflows/security-scan.yml#L14)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

still: is this intended? why only run the job on push, when this workflow is changed? because push events are only after PR events, so no point in running again on every push?
</blockquote></details>

you are clearly correct here, i looked at the builds and it shouldnt be there after added the open on pr

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/845)* status: all files reviewed, 1 unresolved discussion (waiting on @lotem-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/845)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lotem-starkware)

___
*[`.github/workflows/security-scan.yml` line 29 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/845#-O78TObuAeUcoaHrcEow:-O79Kyb89shwNfMaPJCN:bdxc775) ([raw file](https://github.com/starkware-libs/sequencer/blob/c03584b2d45e6589a23a0d388c6c96029e1f8c05/.github/workflows/security-scan.yml#L29)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Shouldn't we just add this to the starkware docker used in the CI? @alon-dotan-starkware
</blockquote></details>

nvm, we'll look into it later

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/845#-:-O79LOFTCnj1jgWSoQbx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lotem-starkware)

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/845#-:-O7NRlf815w8bCQ8ch1N:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lotem-starkware)

**Pull request merged**
