### PR TITLE
feat(batcher): abort when resetting the height, and fail if height already in progress

### PR DESCRIPTION
**Pull request by dafnamatsry**

### CODE REVIEW

**Comment by dafnamatsry** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2063?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2063** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2063?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2060** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2060?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dafnamatsry and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2063)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/proposal_manager.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2063#-OBtleFO4EAAC1APFr_S:-OBtleFO4EAAC1APFr_T:b-d3gprj) ([raw file](https://github.com/starkware-libs/sequencer/blob/28698710ac6c3b96712976d414bbab7b0d217b76/crates/starknet_batcher/src/proposal_manager.rs#L187)):*
> ```XML
>         info!("Starting to work on height {}.", height);
>         self.reset_active_height().await;
>         self.active_height = Some(height);
> ```

If this is the only place this is called, you can set the reactive height in `reset_active_height` instead of setting it to none , and then setting a new one outside.



_Code quote:_
```XML
        self.reset_active_height().await;
        self.active_height = Some(height);
```
___
*[`crates/starknet_batcher/src/batcher.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2063#-OBtl5d6D_kh2wIuLKNO:-OBtl5d6D_kh2wIuLKNP:b-2fm02z) ([raw file](https://github.com/starkware-libs/sequencer/blob/28698710ac6c3b96712976d414bbab7b0d217b76/crates/starknet_batcher/src/batcher.rs#L82)):*
> ```XML
>         self.proposal_manager.start_height(input.height).await.map_err(BatcherError::from)
> 
>         // TODO(Dafna): should we reset the mempool?
> ```

Can remove as we talked offline.



_Code quote:_
```XML
// TODO(Dafna): should we reset the mempool?
```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2063)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/proposal_manager.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2063#-OBtleFO4EAAC1APFr_S:-OBtuxqSBlGJPt2laK5C:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/28698710ac6c3b96712976d414bbab7b0d217b76/crates/starknet_batcher/src/proposal_manager.rs#L187)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

If this is the only place this is called, you can set the reactive height in `reset_active_height` instead of setting it to none , and then setting a new one outside.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2063)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by alonh5 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2063#-:-OBu2d93BYRseDRkfMjy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Comment by dafnamatsry** [comment]
### Merge activity

* **Nov 17, 8:01 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2063).

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2063)* status: all files reviewed, 4 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2063#-OBuHhx03iOspaFrloQF:-OBuHhx03iOspaFrloQG:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d1e0d4e6660d6784db2cd3ea7dedb7c1e1e7204/crates/starknet_batcher/src/proposal_manager_test.rs#L86)):*
> ```XML
>     }
> 
>     fn expect_consequtive_storage_heights(&mut self) {
> ```





_Suggestion:_
```XML
consecutive
```
___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2063#-OBuIw6J2k9ZlVaaBDPH:-OBuIw6J2k9ZlVaaBDPI:b-ttmk9z) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d1e0d4e6660d6784db2cd3ea7dedb7c1e1e7204/crates/starknet_batcher/src/proposal_manager_test.rs#L87)):*
> ```XML
> 
>     fn expect_consequtive_storage_heights(&mut self) {
>         self.storage_reader.checkpoint();
> ```

what is this for?



_Code quote:_
```XML
self.storage_reader.checkpoint()
```
___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 391 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2063#-OBuJ5bc9Stp3-_I4aH0:-OBuJ5bc9Stp3-_I4aH1:b-w6yrtz) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d1e0d4e6660d6784db2cd3ea7dedb7c1e1e7204/crates/starknet_batcher/src/proposal_manager_test.rs#L391)):*
> ```XML
>     mock_dependencies.expect_consequtive_storage_heights();
> 
>     mock_dependencies.expect_build_block(1);
> ```

isn't the long_build_block enough?
why do we need the first build block?



_Code quote:_
```XML
mock_dependencies.expect_build_block(1);
```
___
*[`crates/starknet_batcher/src/proposal_manager.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2063#-OBuGRfK80gmKv75o7kC:-OBuGRfK80gmKv75o7kD:b-e40ywf) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d1e0d4e6660d6784db2cd3ea7dedb7c1e1e7204/crates/starknet_batcher/src/proposal_manager.rs#L163)):*
> ```XML
>     #[instrument(skip(self), err)]
>     async fn start_height(&mut self, height: BlockNumber) -> Result<(), StartHeightError> {
>         if self.active_height.is_some_and(|active_height| active_height == height) {
> ```

is is different from:
if self.active_height == Some(height) { 
?



_Suggestion:_
```XML
if self.active_height == Some(height) { 
```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2063)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/proposal_manager.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2063#-OBuGRfK80gmKv75o7kC:-OBy1ZMZ954bMZYgVAva:b-22ucow) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d1e0d4e6660d6784db2cd3ea7dedb7c1e1e7204/crates/starknet_batcher/src/proposal_manager.rs#L163)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

is is different from:
if self.active_height == Some(height) { 
?
</blockquote></details>

The same. Done.
___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2063#-OBuIw6J2k9ZlVaaBDPH:-OBy3Ld1BZX0UgxKFPQz:b3qoa7o) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d1e0d4e6660d6784db2cd3ea7dedb7c1e1e7204/crates/starknet_batcher/src/proposal_manager_test.rs#L87)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

what is this for?
</blockquote></details>

A bit hacky way to clear the expectation set to always return INITIAL_HEIGHT (in `mock_dependencies`).

`checkpoint()` validates all expectations so far, throw them away, and then we can add new ones.
___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 391 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2063#-OBuJ5bc9Stp3-_I4aH0:-OBy4IY_9ylBvy-E57UY:blvjdv9) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d1e0d4e6660d6784db2cd3ea7dedb7c1e1e7204/crates/starknet_batcher/src/proposal_manager_test.rs#L391)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

isn't the long_build_block enough?
why do we need the first build block?
</blockquote></details>

I check 2 things in this test:
* `active_proposal` is cleared (the `long_build_block`)
* `executed_proposals` is cleared (the `build_block`)
___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2063#-OBuHhx03iOspaFrloQF:-OBy3Kun6cOxFAHgsXO5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d1e0d4e6660d6784db2cd3ea7dedb7c1e1e7204/crates/starknet_batcher/src/proposal_manager_test.rs#L86)):*
> ```XML
>     }
> 
>     fn expect_consequtive_storage_heights(&mut self) {
> ```

Done.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2063)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @dafnamatsry)

___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2063#-OBuIw6J2k9ZlVaaBDPH:-OByVbbs6rLFGau_7xSx:bhg27s0) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d1e0d4e6660d6784db2cd3ea7dedb7c1e1e7204/crates/starknet_batcher/src/proposal_manager_test.rs#L87)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

A bit hacky way to clear the expectation set to always return INITIAL_HEIGHT (in `mock_dependencies`).

`checkpoint()` validates all expectations so far, throw them away, and then we can add new ones.
</blockquote></details>

can you add a comment to explain which expectations you are clearing and why.

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2063)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2063#-OBuIw6J2k9ZlVaaBDPH:-OBydUGZ9s5un3MrAG9G:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d1e0d4e6660d6784db2cd3ea7dedb7c1e1e7204/crates/starknet_batcher/src/proposal_manager_test.rs#L87)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

can you add a comment to explain which expectations you are clearing and why.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2063)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2063)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by alonh5 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2063)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Pull request merged**
