### PR TITLE
refactor(blockifier): check gas and fee in pre validate test

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/995)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/995)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 365 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/995#-O7Zb5vF5_bN9cWtnqVo:-O7Zb5vF5_bN9cWtnqVp:b-o5b2qx) ([raw file](https://github.com/starkware-libs/sequencer/blob/b7a0ccfaca74cf979859bbb21f2f7cfe439b887d/crates/blockifier/src/transaction/execution_flavors_test.rs#L365)):*
> ```XML
>     );
> 
>     let mut execute_and_check_gas_and_fee = |(max_fee, resource_bounds)| {
> ```

the downside of this approach is the the test failure won't show you the problematic line; consider making this a macro instead, so you get line numbers



_Code quote:_
```XML
let mut execute_and_check_gas_and_fee = |(max_fee, resource_bounds)| {
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/995)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 365 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/995#-O7Zb5vF5_bN9cWtnqVo:-O7cSLvPDbm1g2Ow32FV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b7a0ccfaca74cf979859bbb21f2f7cfe439b887d/crates/blockifier/src/transaction/execution_flavors_test.rs#L365)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the downside of this approach is the the test failure won't show you the problematic line; consider making this a macro instead, so you get line numbers
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/995#-:-O7d_ZgR8l2_BrPLsbcJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/995)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Comment by yoavGrs** [comment]
### Merge activity

* **Sep 25, 11:35 PM EDT**: @yoavGrs started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/995).

**Pull request merged**
