### PR TITLE
refactor(blockifier): handle common getters with optional fields

### PR DESCRIPTION
**Pull request by meship-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/699)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
@tdelabro

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/699#-:-O5reo4a1aClcX6Cynvi:bkvrl3k)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @ArniStarkware and @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/699)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/699#-O5s1ra29EdoMrovH7-y:-O5s1ra29EdoMrovH7-z:b5o2lt5) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c21da9056e6df58e18ce0a4539f7a4f60fbbb30/crates/blockifier/src/transaction/account_transaction.rs#L145)):*
> ```XML
>         (paymaster_data, PaymasterData)
>     }
> ```

see discussion https://reviewable.io/reviews/starkware-libs/sequencer/229#-O5qgnF8CCzt7EPbPwqe
I don't like this idea because invoke does not have a class hash, so getting the default here could be misleading.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/699)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/699#-O5s2UPR2httTVYiQxfq:-O5s2UPR2httTVYiQxfr:b-puyy1z) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c21da9056e6df58e18ce0a4539f7a4f60fbbb30/crates/starknet_api/src/executable_transaction.rs#L159)):*
> ```XML
>         (nonce_data_availability_mode, DataAvailabilityMode),
>         (fee_data_availability_mode, DataAvailabilityMode),
>         (paymaster_data, PaymasterData),
> ```

see discussion  https://reviewable.io/reviews/starkware-libs/sequencer/229#-O5qqH8FB2mxl1kzVF1Y
I don't have a strong feeling about it. Max fee is deprecated, so I think we don't have to work hard for it to have a getter.
I only added it here just because, otherwise, I could not write a getter for account transaction.

**Comment by ArniStarkware** [comment]
*[`crates/starknet_api/src/transaction.rs` line 307 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/699#-O5vrl_Y92H_8WwJfmdU:-O5vrl_Y92H_8WwJfmdV:b45ctj8) ([raw file](https://github.com/starkware-libs/sequencer/blob/6343fe160963cce4a4ecb3a602b42ecbbe973a90/crates/starknet_api/src/transaction.rs#L307)):*
> ```XML
>             DeclareTransaction::V3(tx) => Some(tx.compiled_class_hash),
>         }
>     }
> ```

Let us be consistent with #698. Whenever the issue is the transaction version, have the getter either return an `Option<..>` or a `Result<..,..>`.



_Code quote:_
```XML
    pub fn compiled_class_hash(&self) -> Option<CompiledClassHash> {
        match self {
            DeclareTransaction::V0(_) => None,
            DeclareTransaction::V1(_) => None,
            DeclareTransaction::V2(tx) => Some(tx.compiled_class_hash),
            DeclareTransaction::V3(tx) => Some(tx.compiled_class_hash),
        }
    }
```

**Review by ArniStarkware — COMMENTED** [review]
There are three issues in this PR IIUC:
1. The getter for `sender_address` looks great. We just need to make sure there is no getter for `contract_address`. This is almost a communication, i.e., a product issue.
2. getters for fields that are only relevant for some transaction types.
3. getters for fields that are only relevant for some transaction versions. 

Am I missing something? Maybe a combination of item 2 and 3?

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/699#-:-O5vstYo8PLXIF9DLMHH:b-mb3z9x)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/699#-O5s1ra29EdoMrovH7-y:-O5vtpPmAOiL2BHwo88R:bb3c0nt) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c21da9056e6df58e18ce0a4539f7a4f60fbbb30/crates/blockifier/src/transaction/account_transaction.rs#L145)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

see discussion https://reviewable.io/reviews/starkware-libs/sequencer/229#-O5qgnF8CCzt7EPbPwqe
I don't like this idea because invoke does not have a class hash, so getting the default here could be misleading.
</blockquote></details>

I am fine with this being an optional (i.e. have the optional when it is a transaction type issue).
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/699#-O5vs9OY-CWszjnC3r1S:-O5vs9OY-CWszjnC3r1T:b-u86kle) ([raw file](https://github.com/starkware-libs/sequencer/blob/6343fe160963cce4a4ecb3a602b42ecbbe973a90/crates/blockifier/src/transaction/account_transaction.rs#L160)):*
> ```XML
>             Self::Invoke(tx) => tx.tx.sender_address(),
>         }
>     }
> ```

Why is this in this PR and not in the "easy solution" PR? If things get complicated - this getter is good to go, in my opinion.



_Code quote:_
```XML
    pub fn sender_address(&self) -> ContractAddress {
        match self {
            Self::Declare(tx) => tx.tx.sender_address(),
            Self::DeployAccount(tx) => tx.tx.contract_address(),
            Self::Invoke(tx) => tx.tx.sender_address(),
        }
    }
```
___
*[`crates/starknet_api/src/executable_transaction.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/699#-O5s2UPR2httTVYiQxfq:-O5vtcGF-nSKsVd-VrtV:b-zf7z4n) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c21da9056e6df58e18ce0a4539f7a4f60fbbb30/crates/starknet_api/src/executable_transaction.rs#L159)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

see discussion  https://reviewable.io/reviews/starkware-libs/sequencer/229#-O5qqH8FB2mxl1kzVF1Y
I don't have a strong feeling about it. Max fee is deprecated, so I think we don't have to work hard for it to have a getter.
I only added it here just because, otherwise, I could not write a getter for account transaction.
</blockquote></details>

Not having a getter for it at all is a satisfactory solution.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/699)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/starknet_api/src/transaction.rs` line 307 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/699#-O5vrl_Y92H_8WwJfmdU:-O5vw0kF0tikwzvN7GYO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6343fe160963cce4a4ecb3a602b42ecbbe973a90/crates/starknet_api/src/transaction.rs#L307)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Let us be consistent with #698. Whenever the issue is the transaction version, have the getter either return an `Option<..>` or a `Result<..,..>`.
</blockquote></details>

Done.

**Comment by ArniStarkware** [comment]
*[`crates/starknet_api/src/transaction.rs` line 307 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/699#-O5vrl_Y92H_8WwJfmdU:-O5w43DgAtFRsc9tmTP8:ba0t9nn) ([raw file](https://github.com/starkware-libs/sequencer/blob/6343fe160963cce4a4ecb3a602b42ecbbe973a90/crates/starknet_api/src/transaction.rs#L307)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Was the fix not pushed?

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/699)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/starknet_api/src/transaction.rs` line 307 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/699#-O5vrl_Y92H_8WwJfmdU:-O5wFpGz3yDuF4Fr2lAu:bcoi2g0) ([raw file](https://github.com/starkware-libs/sequencer/blob/6343fe160963cce4a4ecb3a602b42ecbbe973a90/crates/starknet_api/src/transaction.rs#L307)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Was the fix not pushed?
</blockquote></details>

Oh, I just wrote Done on the wrong comment. This is not done yet sorry.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/699)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @noaov1)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/699#-O5s2UPR2httTVYiQxfq:-O7gsf9o3fSW3E6IFSQB:bs7wumx) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c21da9056e6df58e18ce0a4539f7a4f60fbbb30/crates/starknet_api/src/executable_transaction.rs#L159)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Not having a getter for it at all is a satisfactory solution.
</blockquote></details>

Done. 
___
*[`crates/starknet_api/src/transaction.rs` line 307 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/699#-O5vrl_Y92H_8WwJfmdU:-O7gshdeEfktrF3VG8YA:b-w5gigr) ([raw file](https://github.com/starkware-libs/sequencer/blob/6343fe160963cce4a4ecb3a602b42ecbbe973a90/crates/starknet_api/src/transaction.rs#L307)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Oh, I just wrote Done on the wrong comment. This is not done yet sorry.
</blockquote></details>

in this pr https://github.com/starkware-libs/sequencer/pull/698

**Comment by ArniStarkware** [comment]
*[`crates/starknet_api/src/executable_transaction.rs` line 19 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/699#-O7h0rI1AFibkvCrFiCm:-O7h0rI1AFibkvCrFiCn:ba545ei) ([raw file](https://github.com/starkware-libs/sequencer/blob/eff81495653b275625c6849a25250c9a72f3fa21/crates/starknet_api/src/executable_transaction.rs#L19)):*
> ```XML
>     ContractAddressSalt,
>     DeprecatedResourceBoundsMapping,
>     Fee,
> ```

Delete.
Note it does not pass CI.



_Code quote:_
```XML
    DeprecatedResourceBoundsMapping,
    Fee,
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/699)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/699)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @noaov1)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 19 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/699#-O7h0rI1AFibkvCrFiCm:-O7hEXn8CNhXdip3k23H:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/eff81495653b275625c6849a25250c9a72f3fa21/crates/starknet_api/src/executable_transaction.rs#L19)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Delete.
Note it does not pass CI.
</blockquote></details>

Done.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/699#-:-O7hF1MA7m_lHVftm_yB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/699)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/699)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
