### PR TITLE
chore(infra): move get_absolute_path function to infra_utils

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2074?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2075** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2075?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2074** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2074?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2073** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2073?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2052** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2052?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2026** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2026?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2020** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2020?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2074)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/infra_utils/src/path.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2074#-OC3Qipt0AsAz1pxiGZ3:-OC3Qipt0AsAz1pxiGZ4:b6g66fm) ([raw file](https://github.com/starkware-libs/sequencer/blob/17634f479bcaa1d228d2ba1e2924ad830ed7cb12/crates/infra_utils/src/path.rs#L6)):*
> ```XML
> // TODO(Tsabary/ Arni): consolidate with other get_absolute_path functions.
> /// Returns the absolute path from the project root.
> pub fn get_absolute_path(relative_path: &str) -> PathBuf {
> ```

I think the name and doc should reflect the relative path is from the project directory. Perhaps even state explicitly what is the returned directory.
Also consider (optional) to split into two functions: obtaining the current path, and joining with the relative path.



_Code quote:_
```XML
// TODO(Tsabary/ Arni): consolidate with other get_absolute_path functions.
/// Returns the absolute path from the project root.
pub fn get_absolute_path(relative_path: &str) -> PathBuf {
```
___
*[`crates/infra_utils/src/path.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2074#-OC3S3CiA_ymiHB2kMfo:-OC3S3CiA_ymiHB2kMfp:b-fhi3fc) ([raw file](https://github.com/starkware-libs/sequencer/blob/17634f479bcaa1d228d2ba1e2924ad830ed7cb12/crates/infra_utils/src/path.rs#L12)):*
> ```XML
>         .map(|dir| PathBuf::from(dir).join("../.."))
>         // If `CARGO_MANIFEST_DIR` isn't set, fall back to the current working directory
>         .unwrap_or_else(|_| env::current_dir().expect("Failed to get current directory"));
> ```

For a different pr:

ChatGPT suggested using `env::current_exe()`, are you familiar with it? 

```
use std::env;
use std::path::PathBuf;

fn get_project_path() -> PathBuf {
    if let Ok(manifest_dir) = env::var("CARGO_MANIFEST_DIR") {
        return PathBuf::from(manifest_dir);
    }

    let exe_path = env::current_exe().expect("Failed to get current executable path");
    let exe_dir = exe_path.parent().expect("Failed to get executable directory");

    if exe_dir.ends_with("debug") || exe_dir.ends_with("release") {
        return exe_dir.parent().unwrap().parent().unwrap().to_path_buf();
    }

    env::current_dir().expect("Failed to get current working directory")
}

fn main() {
    let project_path = get_project_path();
    println!("Project path: {}", project_path.display());
}
```



_Code quote:_
```XML
    let base_dir = env::var("CARGO_MANIFEST_DIR")
        // Attempt to get the `CARGO_MANIFEST_DIR` environment variable and convert it to `PathBuf`.
        // Ascend two directories ("../..") to get to the project root.
        .map(|dir| PathBuf::from(dir).join("../.."))
        // If `CARGO_MANIFEST_DIR` isn't set, fall back to the current working directory
        .unwrap_or_else(|_| env::current_dir().expect("Failed to get current directory"));
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2074)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/infra_utils/src/path.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2074#-OC3Qipt0AsAz1pxiGZ3:-OCCW6MJCI2W4ql7EkkP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/17634f479bcaa1d228d2ba1e2924ad830ed7cb12/crates/infra_utils/src/path.rs#L6)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I think the name and doc should reflect the relative path is from the project directory. Perhaps even state explicitly what is the returned directory.
Also consider (optional) to split into two functions: obtaining the current path, and joining with the relative path.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2074)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Nov 21, 2:52 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2074).

**Pull request merged**
