### PR TITLE
feat: add batcher_types communication

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
commit-id:aa33dbd8

---

**Stack**:
- #204
- #201 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/201)* status: all files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/batcher_types/src/batcher_types.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/201#-O3BkCK257MMF1RfqAYZ:-O3BkCK3-cIcJyYvoICF:b-faqwcq) ([raw file](https://github.com/starkware-libs/sequencer/blob/ad45c95ff5bc9a2d6424e8ad845ce56d2bc7ce45/crates/batcher_types/src/batcher_types.rs#L7)):*
> ```XML
> // TODO(Tsabary/Yael/Dafna): Populate the data structure used to invoke the batcher.
> #[derive(Debug, Serialize, Deserialize)]
> pub struct BatcherInput {}
> ```

The batcher will have multiple methods with different input.
I don't mind keeping it like this for now, but it will probably look like `MethodNameInput`.



_Code quote:_
```XML
pub struct BatcherInput {}
```
___
*[`crates/batcher_types/src/communication.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/201#-O3BjYBICY6lFek_GHqO:-O3BjYBICY6lFek_GHqP:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ad45c95ff5bc9a2d6424e8ad845ce56d2bc7ce45/crates/batcher_types/src/communication.rs#L17)):*
> ```XML
> use crate::batcher_types::{BatcherInput, BatcherResult};
> use crate::errors::BatcherError;
> pub type BatcherClientImpl = LocalComponentClient<BatcherRequest, BatcherResponse>;
> ```





_Suggestion:_
```XML
use crate::errors::BatcherError;

pub type BatcherClientImpl = LocalComponentClient<BatcherRequest, BatcherResponse>;
```
___
*[`crates/batcher_types/src/communication.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/201#-O3BlOMI0fmANuSCLJRF:-O3BlOMI0fmANuSCLJRG:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ad45c95ff5bc9a2d6424e8ad845ce56d2bc7ce45/crates/batcher_types/src/communication.rs#L17)):*
> ```XML
> use crate::batcher_types::{BatcherInput, BatcherResult};
> use crate::errors::BatcherError;
> pub type BatcherClientImpl = LocalComponentClient<BatcherRequest, BatcherResponse>;
> ```





_Suggestion:_
```XML
LocalBatcherClientImpl
```
___
*[`crates/batcher_types/src/communication.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/201#-O3BkhKg3jVvQIEbG-LL:-O3BkhKhA797C9856XvQ:bpzw6oa) ([raw file](https://github.com/starkware-libs/sequencer/blob/ad45c95ff5bc9a2d6424e8ad845ce56d2bc7ce45/crates/batcher_types/src/communication.rs#L25)):*
> ```XML
> 
> // TODO(Tsabary/Yael/Dafna): Replace with the actual return type of the batcher function.
> pub type PlaceholderReturnType = ();
> ```

Shouldn't it be in the other `batcher_types.rs` file?



_Code quote:_
```XML
pub type PlaceholderReturnType = ();
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/201)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/batcher_types/src/batcher_types.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/201#-O3BkCK257MMF1RfqAYZ:-O3C8YHFD3wORnPJYSHI:b5ipqwe) ([raw file](https://github.com/starkware-libs/sequencer/blob/5e9993f6bb76474ff5083f3a930840772a319f42/crates/batcher_types/src/batcher_types.rs#L7)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

The batcher will have multiple methods with different input.
I don't mind keeping it like this for now, but it will probably look like `MethodNameInput`.
</blockquote></details>

Right. Added another variant, now we have `BatcherFnOne` and `BatcherFnTwo` (and their respective inputs, outputs, requests, responses, and trait definitions).
___
*[`crates/batcher_types/src/communication.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/201#-O3BjYBICY6lFek_GHqO:-O3C8XiW093tiBiKLb5b:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5e9993f6bb76474ff5083f3a930840772a319f42/crates/batcher_types/src/communication.rs#L17)):*
> ```XML
> use crate::batcher_types::{BatcherInput, BatcherResult};
> use crate::errors::BatcherError;
> pub type BatcherClientImpl = LocalComponentClient<BatcherRequest, BatcherResponse>;
> ```

Done.
___
*[`crates/batcher_types/src/communication.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/201#-O3BlOMI0fmANuSCLJRF:-O3C8iPl84wJxh-EURRq:b-v02g5o) ([raw file](https://github.com/starkware-libs/sequencer/blob/5e9993f6bb76474ff5083f3a930840772a319f42/crates/batcher_types/src/communication.rs#L17)):*
> ```XML
> use crate::batcher_types::{BatcherInput, BatcherResult};
> use crate::errors::BatcherError;
> pub type BatcherClientImpl = LocalComponentClient<BatcherRequest, BatcherResponse>;
> ```

We plan to change these globablly, changed here as well.
___
*[`crates/batcher_types/src/communication.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/201#-O3BkhKg3jVvQIEbG-LL:-O3CBgjK63s7esFEX3na:b-m6f40f) ([raw file](https://github.com/starkware-libs/sequencer/blob/5e9993f6bb76474ff5083f3a930840772a319f42/crates/batcher_types/src/communication.rs#L25)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Shouldn't it be in the other `batcher_types.rs` file?
</blockquote></details>

Yes, moved.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/201#-:-O3SDyRaCr8a8PRpKQMV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/201)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
