### PR TITLE
feat(starknet_state_sync): create state sync components

### PR DESCRIPTION
**Pull request by noamsp-starkware**

### CODE REVIEW

**Comment by noamsp-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2531?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2531** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2531?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2531?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2515** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2515?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2531)* status: 0 of 13 files reviewed, 5 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/starknet_sequencer_node/src/components.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbft6pA1njrnRAkInu:-ODbft6pA1njrnRAkInv:b-40hiqa) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_sequencer_node/src/components.rs#L138)):*
> ```XML
>         mempool_p2p_runner,
>         state_sync,
>         state_sync_runner,
> ```

Are these the formal component names?



_Code quote:_
```XML
        state_sync,
        state_sync_runner,
```
___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbf8hqDa05qYtNGcFq:-ODbf8hqDa05qYtNGcFr:b3emcoq) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_integration_tests/src/state_reader.rs#L59)):*
> ```XML
>     pub batcher_storage_handle: TempDir,
>     pub state_sync_storage_config: StorageConfig,
>     pub state_sync_storage_handle: TempDir,
> ```

I thought the state sync storage is supposed to replace the rpc and batcher storage instances. Will they be deleted in following prs?



_Code quote:_
```XML
    pub state_sync_storage_config: StorageConfig,
    pub state_sync_storage_handle: TempDir,
```
___
*[`crates/starknet_sequencer_node/src/config/config_test.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbg2TFCJHDAq2uzugN:-ODbg2TFCJHDAq2uzugO:bak7b15) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_sequencer_node/src/config/config_test.rs#L79)):*
> ```XML
>     let default_config = SequencerNodeConfig::default();
>     assert_matches!(default_config.validate(), Ok(()));
>     fs::remove_dir("data").unwrap();
> ```

Context for this please :pray: 



_Code quote:_
```XML
    // The validate function will fail if the data directory does not exist. we assert the directory
    // does not exist to prevent deleting a non related folder with the same path.
    assert!(!Path::new("data").exists());
    fs::create_dir_all("data").expect("Should make a temporary `data` directory");

    let default_config = SequencerNodeConfig::default();
    assert_matches!(default_config.validate(), Ok(()));
    fs::remove_dir("data").unwrap();
```
___
*[`crates/starknet_sequencer_node/src/config/config_test.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbg8X7Chm2Ofl8PDm-:-ODbg8X7Chm2Ofl8PDm0:b77rhhq) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_sequencer_node/src/config/config_test.rs#L119)):*
> ```XML
>     // The validate function will fail if the data directory does not exist so we change the path to
>     // point to an existing directory.
>     config.state_sync_config.storage_config.db_config.path_prefix = PathBuf::from(".");
> ```

Context please.



_Code quote:_
```XML
    // The validate function will fail if the data directory does not exist so we change the path to
    // point to an existing directory.
    config.state_sync_config.storage_config.db_config.path_prefix = PathBuf::from(".");
```
___
*[`crates/starknet_integration_tests/src/utils.rs` line 237 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbfS-Z0oVqUoCqL-UP:-ODbfS-Z0oVqUoCqL-UQ:boye6c5) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_integration_tests/src/utils.rs#L237)):*
> ```XML
> 
> pub fn create_state_sync_config(state_sync_storage_config: StorageConfig) -> StateSyncConfig {
>     const STATE_SYNC_NETWORK_CONFIG_TCP_PORT_FOR_TESTING: u16 = 12345;
> ```

Why not `get_available_port`?



_Code quote:_
```XML
const STATE_SYNC_NETWORK_CONFIG_TCP_PORT_FOR_TESTING: u16 = 12345;
```

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2531)* status: 0 of 13 files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbf8hqDa05qYtNGcFq:-ODbmsVz1biDKhMnmDzV:b9m9vne) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_integration_tests/src/state_reader.rs#L59)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I thought the state sync storage is supposed to replace the rpc and batcher storage instances. Will they be deleted in following prs?
</blockquote></details>

I'll check this. If so i'll add a TODO/remove them in a following PR.
___
*[`crates/starknet_integration_tests/src/utils.rs` line 237 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbfS-Z0oVqUoCqL-UP:-ODbnR0F-Bccin4-OqEa:b-bqv9ci) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_integration_tests/src/utils.rs#L237)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Why not `get_available_port`?
</blockquote></details>

What do you mean? I didnt find a func with this name.
___
*[`crates/starknet_sequencer_node/src/components.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbft6pA1njrnRAkInu:-ODbnZIF8XFLwwS_xLrz:b2nhswy) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_sequencer_node/src/components.rs#L138)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Are these the formal component names?
</blockquote></details>

Yes



_Code snippet (i):_
```XML
pub struct StateSync {
    pub request_sender: mpsc::Sender<(StateSyncRequest, oneshot::Sender<StateSyncResponse>)>,
}
```



_Code snippet (ii):_
```XML
pub struct StateSyncRunner {
    #[allow(dead_code)]
    request_receiver: mpsc::Receiver<(StateSyncRequest, oneshot::Sender<StateSyncResponse>)>,
    #[allow(dead_code)]
    storage_reader: StorageReader,
    network_future: BoxFuture<'static, Result<(), NetworkError>>,
    // TODO: change client and server to requester and responder respectively
    p2p_sync_client_future: BoxFuture<'static, Result<(), P2PSyncClientError>>,
    p2p_sync_server_future: BoxFuture<'static, ()>,
}
```
___
*[`crates/starknet_sequencer_node/src/config/config_test.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbg2TFCJHDAq2uzugN:-ODbo5G5DdGH9cui5O_e:bizkme3) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_sequencer_node/src/config/config_test.rs#L79)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Context for this please :pray:
</blockquote></details>

Will add to the comment.
___
*[`crates/starknet_sequencer_node/src/config/config_test.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbg8X7Chm2Ofl8PDm-:-ODbo9DW3wIZxWb-HyGg:bizkme3) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_sequencer_node/src/config/config_test.rs#L119)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Context please.
</blockquote></details>

Will add to the comment.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2531)* status: 0 of 13 files reviewed, 5 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 237 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbfS-Z0oVqUoCqL-UP:-ODe4K2060P8EsSZQzcA:b5uowo2) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_integration_tests/src/utils.rs#L237)):*
<details><summary><i>Previously, noamsp-starkware wrote…</i></summary><blockquote>

What do you mean? I didnt find a func with this name.
</blockquote></details>

`get_available_socket`, apologies.
___
*[`crates/starknet_sequencer_node/src/components.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbft6pA1njrnRAkInu:-ODe4Q8s62aGjuwT_AbB:bkqfo0z) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_sequencer_node/src/components.rs#L138)):*
<details><summary><i>Previously, noamsp-starkware wrote…</i></summary><blockquote>

Yes
</blockquote></details>

The mempool_p2p module also has two components: the propagator and the runner. Can we stick to this convention, i.e., that we have state_sync_X and state_sync_Y. Otherwise this will get too messy to rememeber which component is from which module.
___
*[`crates/starknet_sequencer_node/src/config/config_test.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbg2TFCJHDAq2uzugN:-ODe4gZVA-l1sBamqkfc:b-nhdjou) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_sequencer_node/src/config/config_test.rs#L79)):*
<details><summary><i>Previously, noamsp-starkware wrote…</i></summary><blockquote>

Will add to the comment.
</blockquote></details>

I meant in a broader spec: why does config validation is related to existence of data directories?

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 10 of 13 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2531)* status: 11 of 13 files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware and @noamsp-starkware)

___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbf8hqDa05qYtNGcFq:-ODef1Kg4ugrb1O2YGts:b-aiggxb) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_integration_tests/src/state_reader.rs#L59)):*
<details><summary><i>Previously, noamsp-starkware wrote…</i></summary><blockquote>

I'll check this. If so i'll add a TODO/remove them in a following PR.
</blockquote></details>

Only the rpc one. The batcher one will remain. The rpc one will be deleted within hopefully a week or two
Please add the appropriate TODO
___
*[`crates/starknet_integration_tests/src/utils.rs` line 237 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbfS-Z0oVqUoCqL-UP:-ODefjv_3L6XOOx7HdR3:b-lltm8l) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_integration_tests/src/utils.rs#L237)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

`get_available_socket`, apologies.
</blockquote></details>

This function is used in the dump_config exe. The fact that the port is available in the dump_config exe doesn't mean it will be available when we run the node
___
*[`crates/starknet_sequencer_node/src/components.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbft6pA1njrnRAkInu:-ODf8c6v0p5ZKbMQ3knl:b-lprnhm) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_sequencer_node/src/components.rs#L138)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

The mempool_p2p module also has two components: the propagator and the runner. Can we stick to this convention, i.e., that we have state_sync_X and state_sync_Y. Otherwise this will get too messy to rememeber which component is from which module.
</blockquote></details>

I'd love to discuss this further in huddle or f2f, but it's unrelated to this PR and IMO shouldn't block
___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODefRWf1X1PnJleYPyg:-ODefRWf1X1PnJleYPyh:bb772hf) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ca41628fe841a8eae49773803dab56ecc9f7875/crates/starknet_integration_tests/src/state_reader.rs#L82)):*
> ```XML
>             .chain_id(chain_info.chain_id.clone())
>             .build();
>         create_test_state(&mut state_sync_storage_writer, chain_info, test_defined_accounts);
> ```

@Itay-Tsabary-Starkware is this function deterministic? will it return the same storage for the sync and the batcher?

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2531)* status: 11 of 13 files reviewed, 7 unresolved discussions (waiting on @Itay-Tsabary-Starkware and @noamsp-starkware)

___
*[`config/sequencer/default_config.json` line 1095 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODfLIwJ5TDvSrUM83gz:-ODfLIwJ5TDvSrUM83h-:bu0muga) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ca41628fe841a8eae49773803dab56ecc9f7875/config/sequencer/default_config.json#L1095)):*
> ```JSON
>     "description": "Prefix of the path of the node's storage directory, the storage file path will be <path_prefix>/<chain_id>. The path is not created automatically.",
>     "privacy": "Public",
>     "value": "./data"
> ```

This collides with papyrus. Change to ./sequencer_data

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2531)* status: 11 of 13 files reviewed, 7 unresolved discussions (waiting on @Itay-Tsabary-Starkware and @ShahakShama)

___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbf8hqDa05qYtNGcFq:-ODfCLqJB1_-Br7WopDF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_integration_tests/src/state_reader.rs#L59)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Only the rpc one. The batcher one will remain. The rpc one will be deleted within hopefully a week or two
Please add the appropriate TODO
</blockquote></details>

Done.
___
*[`crates/starknet_sequencer_node/src/config/config_test.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbg2TFCJHDAq2uzugN:-ODfUlJ08d3sDMuQXAyG:b-5g98pn) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_sequencer_node/src/config/config_test.rs#L79)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Is this what they do in batcher?
</blockquote></details>

@Itay-Tsabary-Starkware The validation verifies the paths specified in the config actually exist. ./data is the default and intended path for the state sync storage (this will be refactored to ./sequencer_data).

@ShahakShama In batcher they use a . as the default storage directory, so no need to create this file explicitly.

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2531)* status: 11 of 13 files reviewed, 7 unresolved discussions (waiting on @Itay-Tsabary-Starkware and @ShahakShama)

___
*[`config/sequencer/default_config.json` line 1095 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODfLIwJ5TDvSrUM83gz:-ODfVwC00gvkTE9H3qFt:b32w1t) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ca41628fe841a8eae49773803dab56ecc9f7875/config/sequencer/default_config.json#L1095)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This collides with papyrus. Change to ./sequencer_data
</blockquote></details>

Ok

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2531)* status: 11 of 13 files reviewed, 6 unresolved discussions (waiting on @noamsp-starkware and @ShahakShama)

___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbf8hqDa05qYtNGcFq:-ODfaHNd3-WWNugzmzoK:bkfot3w) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_integration_tests/src/state_reader.rs#L59)):*
<details><summary><i>Previously, noamsp-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Add a name to the todo please :pray: 
___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODefRWf1X1PnJleYPyg:-ODfaY2k-fu6NsXdyGKl:b-qlzwhf) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ca41628fe841a8eae49773803dab56ecc9f7875/crates/starknet_integration_tests/src/state_reader.rs#L82)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

@Itay-Tsabary-Starkware is this function deterministic? will it return the same storage for the sync and the batcher?
</blockquote></details>

Yes. And also for the rpc.
But please note the `StorageScope::FullArchive` parameter that affect the returned storage.
___
*[`crates/starknet_integration_tests/src/utils.rs` line 237 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbfS-Z0oVqUoCqL-UP:-ODfayqz4GeETj4hQ11-:by4813q) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_integration_tests/src/utils.rs#L237)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This function is used in the dump_config exe. The fact that the port is available in the dump_config exe doesn't mean it will be available when we run the node
</blockquote></details>

I don't understand the comment, nor the desired behavior. Could you please elaborate on both?
___
*[`crates/starknet_sequencer_node/src/config/config_test.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbg2TFCJHDAq2uzugN:-ODfbFe-7nWrXp0S6-p6:bst4qju) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_sequencer_node/src/config/config_test.rs#L79)):*
<details><summary><i>Previously, noamsp-starkware wrote…</i></summary><blockquote>

@Itay-Tsabary-Starkware The validation verifies the paths specified in the config actually exist. ./data is the default and intended path for the state sync storage (this will be refactored to ./sequencer_data).

@ShahakShama In batcher they use a . as the default storage directory, so no need to create this file explicitly.
</blockquote></details>

This validation is internal to the component, this does not belong in the globabl config validation scope imo. Please move it to a relevant module. The batcher has/had a similar validation, check it out for inspiration.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2531)* status: 11 of 13 files reviewed, 6 unresolved discussions (waiting on @noamsp-starkware and @ShahakShama)

___
*[`crates/starknet_sequencer_node/src/config/config_test.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbg8X7Chm2Ofl8PDm-:-ODfc44U8bPG1XZWOPcO:b-8fgr9q) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_sequencer_node/src/config/config_test.rs#L119)):*
<details><summary><i>Previously, noamsp-starkware wrote…</i></summary><blockquote>

Will add to the comment.
</blockquote></details>

As per my suggestion/request above, this should be a part of the internal test / setup phase of the state sync component.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2531)* status: 11 of 13 files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware and @noamsp-starkware)

___
*[`config/sequencer/default_config.json` line 1095 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODfLIwJ5TDvSrUM83gz:-ODfsaWN-qy1Glh1uL7-:b-308apy) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ca41628fe841a8eae49773803dab56ecc9f7875/config/sequencer/default_config.json#L1095)):*
<details><summary><i>Previously, noamsp-starkware wrote…</i></summary><blockquote>

Ok
</blockquote></details>

This is not changed. Also, Add `/sequencer_data` to .gitignore

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2531)* status: 11 of 13 files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware, @noamsp-starkware, and @yair-starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 237 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbfS-Z0oVqUoCqL-UP:-ODfsmJhEJUoNT4F13K_:b-xz65vy) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_integration_tests/src/utils.rs#L237)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I don't understand the comment, nor the desired behavior. Could you please elaborate on both?
</blockquote></details>

@yair-starkware also encountered this.
The issue is that what you're suggesting is to call get_available_socket() in every config we have ports in it, but the issue is that we first create the entire config and then run the node so the port isn't taken after we call get_available_socket

I think I have a different solution, we'll create a test utility for get_available_socket that holds a lazy static mutex for a vector/hashset of taken ports and whenever it is called it locks the mutex, gets a port that doesn't appear there and adds it there and returns the port

WDYT

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2531)* status: 11 of 13 files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware, @noamsp-starkware, and @yair-starkware)

___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbf8hqDa05qYtNGcFq:-ODfui96AdPC_xjTOcf4:bwgr2ks) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_integration_tests/src/state_reader.rs#L59)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Add a name to the todo please :pray:
</blockquote></details>

You can put my name if you want
___
*[`crates/starknet_sequencer_node/src/config/config_test.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbg2TFCJHDAq2uzugN:-ODfuREn97GEJW7S9bdg:bd92774) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_sequencer_node/src/config/config_test.rs#L79)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

This validation is internal to the component, this does not belong in the globabl config validation scope imo. Please move it to a relevant module. The batcher has/had a similar validation, check it out for inspiration.
</blockquote></details>

As discussed in slack, IMO we should remove this validation and make it so that if the path doesn't exist, open_storage will create the directory in that path

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2531)* status: 2 of 17 files reviewed, 4 unresolved discussions (waiting on @noamsp-starkware, @ShahakShama, and @yair-starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 237 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbfS-Z0oVqUoCqL-UP:-ODk-WJv8o9AY-XWQGMj:bopzcd2) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_integration_tests/src/utils.rs#L237)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

@yair-starkware also encountered this.
The issue is that what you're suggesting is to call get_available_socket() in every config we have ports in it, but the issue is that we first create the entire config and then run the node so the port isn't taken after we call get_available_socket

I think I have a different solution, we'll create a test utility for get_available_socket that holds a lazy static mutex for a vector/hashset of taken ports and whenever it is called it locks the mutex, gets a port that doesn't appear there and adds it there and returns the port

WDYT
</blockquote></details>

Ack about the problem.
Let's discuss solutions in a different scope.
For the mean time, please put this constant in a visible place (i.e., not within a function body mid-module, but at the top), with a clearly marked todo to get rid of it :pray: (please include "Tsabary" in the todo as well)

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2531)* status: 2 of 17 files reviewed, 2 unresolved discussions (waiting on @ShahakShama and @yair-starkware)

___
*[`config/sequencer/default_config.json` line 1095 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODfLIwJ5TDvSrUM83gz:-ODgCIakAmhN8a9GIRfZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ca41628fe841a8eae49773803dab56ecc9f7875/config/sequencer/default_config.json#L1095)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is not changed. Also, Add `/sequencer_data` to .gitignore
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbf8hqDa05qYtNGcFq:-ODff7T76lhT4Ey3bKNe:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_integration_tests/src/state_reader.rs#L59)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Add a name to the todo please :pray:
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/utils.rs` line 237 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODbfS-Z0oVqUoCqL-UP:-ODk6oHn3SbmkmhCCf_F:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/890bf5df2af3685d33992672f15e186ffaa09f73/crates/starknet_integration_tests/src/utils.rs#L237)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Ack about the problem.
Let's discuss solutions in a different scope.
For the mean time, please put this constant in a visible place (i.e., not within a function body mid-module, but at the top), with a clearly marked todo to get rid of it :pray: (please include "Tsabary" in the todo as well)
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 13 files at r1, 7 of 14 files at r3, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-:-ODkBqjW0NbqavvMglVt:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 3 of 13 files at r1, 7 of 14 files at r3, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2531)* status: all files reviewed, 2 unresolved discussions (waiting on @noamsp-starkware and @ShahakShama)

___
*[`crates/papyrus_storage/src/lib.rs` line 170 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-ODkAXGL0BYUhmF-lbQT:-ODkAXGL0BYUhmF-lbQU:b-odg2lx) ([raw file](https://github.com/starkware-libs/sequencer/blob/b14087cd1c2ab3de58f8e789cbd314bd781ce0f8/crates/papyrus_storage/src/lib.rs#L170)):*
> ```XML
>     {
>         fs::create_dir_all(storage_config.db_config.path_prefix.clone())?;
>         info!("Created storage directory: {:?}", storage_config.db_config.path());
> ```

Please use the display format (`{}` instead of `{:?}` )



_Code quote:_
```XML
:?
```

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 7 of 14 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2531#-:-ODkZQ2z62SFORLFxmtf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)

**Pull request merged**
