### PR TITLE
chore: fix clippy for version 0.1.81

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Review by ArniStarkware — COMMENTED** [review]
This PR is a replica of #2365 except for one difference. This PR does not include a disable of one part of the CI.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2371#-:-OD0tZXP4qNBl5gDGoJA:b9v2n50)* status: 0 of 30 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2371)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2371#-OD0tvJFDWqVAHCW7SOF:-OD0tvJFDWqVAHCW7SOG:b-1f7woc) ([raw file](https://github.com/starkware-libs/sequencer/blob/0c5a30e6a0344a94b90af304f9ef22dca55af213/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L244)):*
> ```XML
>             Some(h) => h < height,
>             None => true,
>         } {
> ```

wonder why clippy thinks this is better



_Code quote:_
```XML
        if match self.current_height {
            Some(h) => h < height,
            None => true,
        } {
```
___
*[`.github/workflows/papyrus_docker-publish.yml.disabled` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2371#-OD0u-o4EDlVEbpTrM_D:-OD0u-o4EDlVEbpTrM_E:bn4189z) ([raw file](https://github.com/starkware-libs/sequencer/blob/0c5a30e6a0344a94b90af304f9ef22dca55af213/.github/workflows/papyrus_docker-publish.yml.disabled#L0)):*
why was this renamed?

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2371#-:-OD0vPfM2qUvlf5z9q9w:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2371#-OD0tvJFDWqVAHCW7SOF:-OD0vNVLA1-zd3ZR3MPV:b8kej34) ([raw file](https://github.com/starkware-libs/sequencer/blob/0c5a30e6a0344a94b90af304f9ef22dca55af213/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L244)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

wonder why clippy thinks this is better
</blockquote></details>

```
error[E0658]: use of unstable library feature 'is_none_or'
   --> crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs:274:32
    |
274 |         if self.current_height.is_none_or(|h| height > h) {
```

https://github.com/rust-lang/rust/issues/126383

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2371)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2371#-OD0vgtO4GZZKJbtXYfq:-OD0vgtO4GZZKJbtXYfr:b-w3g9rb) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab84b238cdba44297180924fffe7072e4a99692f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L244)):*
> ```XML
>             Some(h) => h < height,
>             None => true,
>         } {
> ```

how about this?



_Suggestion:_
```XML
        if self.current_height.map(|h| h < height).unwrap_or(true) {
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2371)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`.github/workflows/papyrus_docker-publish.yml.disabled` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2371#-OD0u-o4EDlVEbpTrM_D:-OD0vjT72woEFUaMec3U:bqf05oh) ([raw file](https://github.com/starkware-libs/sequencer/blob/0c5a30e6a0344a94b90af304f9ef22dca55af213/.github/workflows/papyrus_docker-publish.yml.disabled#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why was this renamed?
</blockquote></details>

In the current revision 2 of this PR, there is no rename. 
Now this PR is actually different than #2365

**Comment by ArniStarkware** [comment]
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2371#-OD0vgtO4GZZKJbtXYfq:-OD0x0LuEsh_DH1j9vRR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab84b238cdba44297180924fffe7072e4a99692f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L244)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

how about this?
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2371)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
