### PR TITLE
feat: log the loaded configuration when the node starts running

### PR DESCRIPTION
**Pull request by nadin-Starkware**
commit-id:17e3b0e2

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2836)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/papyrus_config/src/loading.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2836#-OEYun5KBTpqW0H_cnDc:-OEYun5L6SxlvyrkLl7p:bs7fpg9) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ebee3c683e446fa964892e1be74919d838500a8/crates/papyrus_config/src/loading.rs#L40)):*
> ```XML
>         info!("config_map: {}", pretty_config);
>     } else {
>         info!("Failed to pretty-print config_map");
> ```

1. Please change to `error!`
2. When can this fail?
3. Consider adding a tracing span here (the #instrument macro)



_Code quote:_
```XML
 info
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2836)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/papyrus_config/src/loading.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2836#-OEYun5KBTpqW0H_cnDc:-OEhe27A8B9YXESE8tjh:beauci9) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ebee3c683e446fa964892e1be74919d838500a8/crates/papyrus_config/src/loading.rs#L40)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

1. Please change to `error!`
2. When can this fail?
3. Consider adding a tracing span here (the #instrument macro)
</blockquote></details>

1 + 3 Done.
2:
-   **Serialization Issues:** The `config_map` contains types that don't implement `serde::Serialize` or have invalid structures (e.g., recursive structures).
-   **Unsupported Data:** The `config_map` includes data types that `serde_json` can't handle.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2836)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/papyrus_config/src/loading.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2836#-OEYun5KBTpqW0H_cnDc:-OEiUL9G4_Lq4WIKUW2t:b-3ftkti) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ebee3c683e446fa964892e1be74919d838500a8/crates/papyrus_config/src/loading.rs#L40)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

1 + 3 Done.
2:
-   **Serialization Issues:** The `config_map` contains types that don't implement `serde::Serialize` or have invalid structures (e.g., recursive structures).
-   **Unsupported Data:** The `config_map` includes data types that `serde_json` can't handle.
</blockquote></details>

1. Thanks :pray: 
2. I see, but neither of these should not actually happen, right? If so, please change to `expect`
3. Thanks! Does it make sense to skip the `config_map` arg, i.e., something like `#\[instrument(skip(self))\]` ?

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2836)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/papyrus_config/src/loading.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2836#-OEYun5KBTpqW0H_cnDc:-OEi_uXo03rkgdESObm3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ebee3c683e446fa964892e1be74919d838500a8/crates/papyrus_config/src/loading.rs#L40)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

1. Thanks :pray: 
2. I see, but neither of these should not actually happen, right? If so, please change to `expect`
3. Thanks! Does it make sense to skip the `config_map` arg, i.e., something like `#\[instrument(skip(self))\]` ?
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2836#-:-OEiifZGDi2jT-Bgqqsu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Pull request merged**
