### PR TITLE
feat: use the starknet-sierra-compile downloaded binary to compile

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/598)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/598?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#599** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/599?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#598** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/598?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#597** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/597?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#566** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/566?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#331](https://github.com/starkware-libs/sequencer/pull/331) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/331?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#581](https://github.com/starkware-libs/sequencer/pull/581) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/581?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/598)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/starknet_sierra_compile/src/command_line_compiler.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/598#-O5HVQ7pAxFKGGW0x0wA:-O5HVQ7pAxFKGGW0x0wB:b-ut466q) ([raw file](https://github.com/starkware-libs/sequencer/blob/17e0fd55bb25a07249d290a32649a006d246022a/crates/starknet_sierra_compile/src/command_line_compiler.rs#L37)):*
> ```XML
>         let mut temp_file = NamedTempFile::new()?;
>         temp_file.write_all(serialized_contract_class.as_bytes())?;
>         let temp_file_path = temp_file.path().to_str().ok_or(
> ```

Shouldn't it be before `write_all`?



_Code quote:_
```XML
let temp_file_path = temp_file.path()
```
___
*[`crates/starknet_sierra_compile/src/command_line_compiler.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/598#-O5HVZH0-Ik0lCVVeJET:-O5HVZH0-Ik0lCVVeJEU:b-cca9df) ([raw file](https://github.com/starkware-libs/sequencer/blob/17e0fd55bb25a07249d290a32649a006d246022a/crates/starknet_sierra_compile/src/command_line_compiler.rs#L38)):*
> ```XML
>         temp_file.write_all(serialized_contract_class.as_bytes())?;
>         let temp_file_path = temp_file.path().to_str().ok_or(
>             CompilationUtilError::CompilationError("Failed to get temporary file path".to_owned()),
> ```

UnexpectedError?



_Code quote:_
```XML
CompilationUtilError::CompilationError
```
___
*[`crates/starknet_sierra_compile/src/command_line_compiler.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/598#-O5HXkjHEg9tMTgMsZQv:-O5HXkjI3C8eeRhvIrD0:b-2lr0rf) ([raw file](https://github.com/starkware-libs/sequencer/blob/17e0fd55bb25a07249d290a32649a006d246022a/crates/starknet_sierra_compile/src/command_line_compiler.rs#L74)):*
> ```XML
>             .nth(3)
>             .expect("Failed to navigate up three levels from OUT_DIR")
>             .join("cairo");
> ```

Consider moving to a common location, as it is used in the build.rs as well.



_Code quote:_
```XML
        let out_dir = env::var("OUT_DIR").expect("Failed to get the OUT_DIR environment variable");
        let out_dir = Path::new(&out_dir);

        // Navigate up the directory tree until reaching the 'target' directory
        let target_dir = out_dir
            .ancestors()
            .nth(3)
            .expect("Failed to navigate up three levels from OUT_DIR")
            .join("cairo");
```
___
*[`crates/starknet_sierra_compile/src/compile_test.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/598#-O5HaTwaAclFk4h-e_9s:-O5HaTwaAclFk4h-e_9t:b-wzgv3p) ([raw file](https://github.com/starkware-libs/sequencer/blob/17e0fd55bb25a07249d290a32649a006d246022a/crates/starknet_sierra_compile/src/compile_test.rs#L26)):*
> ```XML
>     COMMAND_LINE_COMPILER
>         .get_or_init(|| CommandLineCompiler::new(SIERRA_TO_CASM_COMPILATION_CONFIG))
> }
> ```

Please make these a simple functions.
Seems to me like an overkill to use OneLock in the test.



_Code quote:_
```XML
const CAIRO_LANG_COMPILER: CairoLangSierraToCasmCompiler =
    CairoLangSierraToCasmCompiler { config: SIERRA_TO_CASM_COMPILATION_CONFIG };

static COMMAND_LINE_COMPILER: OnceLock<CommandLineCompiler> = OnceLock::new();
fn commnad_line_compiler() -> &'static CommandLineCompiler {
    COMMAND_LINE_COMPILER
        .get_or_init(|| CommandLineCompiler::new(SIERRA_TO_CASM_COMPILATION_CONFIG))
}
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/598)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/starknet_sierra_compile/src/command_line_compiler.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/598#-O5HVQ7pAxFKGGW0x0wA:-O5I0a9aAZWbI-8eKfLZ:bp3ed8v) ([raw file](https://github.com/starkware-libs/sequencer/blob/d98265efd0279bff2873a9bf524cc64a1059e802/crates/starknet_sierra_compile/src/command_line_compiler.rs#L37)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Shouldn't it be before `write_all`?
</blockquote></details>

Tried replacing the line: got: 
```
error[E0502]: cannot borrow `temp_file` as mutable because it is also borrowed as immutable
```


Does not seem critical IIUC.
___
*[`crates/starknet_sierra_compile/src/command_line_compiler.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/598#-O5HVZH0-Ik0lCVVeJET:-O5Hvav30Q9IOmDTo-Lm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d98265efd0279bff2873a9bf524cc64a1059e802/crates/starknet_sierra_compile/src/command_line_compiler.rs#L38)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

UnexpectedError?
</blockquote></details>

Done.
___
*[`crates/starknet_sierra_compile/src/command_line_compiler.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/598#-O5HXkjHEg9tMTgMsZQv:-O5Hzsn20fiBhET39pEH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d98265efd0279bff2873a9bf524cc64a1059e802/crates/starknet_sierra_compile/src/command_line_compiler.rs#L74)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Consider moving to a common location, as it is used in the build.rs as well.
</blockquote></details>

Done.
___
*[`crates/starknet_sierra_compile/src/compile_test.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/598#-O5HaTwaAclFk4h-e_9s:-O5I-Bee916FCkh9vuu-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d98265efd0279bff2873a9bf524cc64a1059e802/crates/starknet_sierra_compile/src/compile_test.rs#L26)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please make these a simple functions.
Seems to me like an overkill to use OneLock in the test.
</blockquote></details>

Done.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/598)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/starknet_sierra_compile/src/build_utils.rs` line 3 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/598#-O5IZAxM0M8WM-THn5ZA:-O5IZAxM0M8WM-THn5ZB:b-x9osim) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3e4d611c513404e5e224c0cd0b2834b015eb26a/crates/starknet_sierra_compile/src/build_utils.rs#L3)):*
> ```XML
> /// Get the crate's `OUT_DIR` and navigates up to reach the `target/BUILD_FLAVOR` directory.
> /// This directory is shared accross all crates in this project.
> pub fn get_traget_build_flavor_dir() -> &'static std::path::Path {
> ```

Why static?
I think the caller should be responsible of the lifetime of this.

Is it possible to return std::path::Path, and remove the Box::leak?



_Code quote:_
```XML
&'static std::path::Path {
```
___
*[`crates/starknet_sierra_compile/src/compile_test.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/598#-O5IZUML9bd5fT1yXTKq:-O5IZUML9bd5fT1yXTKr:bh166br) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3e4d611c513404e5e224c0cd0b2834b015eb26a/crates/starknet_sierra_compile/src/compile_test.rs#L19)):*
> ```XML
> 
> const CAIRO_LANG_COMPILER: CairoLangSierraToCasmCompiler =
>     CairoLangSierraToCasmCompiler { config: SIERRA_TO_CASM_COMPILATION_CONFIG };
> ```

Just for consistency, consider changing this to a function as well (like the `command_line_compiler`)



_Code quote:_
```XML
const CAIRO_LANG_COMPILER: CairoLangSierraToCasmCompiler =
    CairoLangSierraToCasmCompiler { config: SIERRA_TO_CASM_COMPILATION_CONFIG };
```

**Comment by ArniStarkware** [comment]
*[`crates/starknet_sierra_compile/src/command_line_compiler.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/598#-O5Is5l48-rO-bKEA1fj:-O5Is5l48-rO-bKEA1fk:b-plbv07) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3e4d611c513404e5e224c0cd0b2834b015eb26a/crates/starknet_sierra_compile/src/command_line_compiler.rs#L47)):*
> ```XML
>             "--max-bytecode-size",
>             &self.config.max_bytecode_size.to_string(),
>         ]);
> ```

add todo - add Ulimits.



_Code quote:_
```XML
        // Set the parameters for the compile process.
        let mut command = Command::new(self.path_to_starknet_sierra_compile_binary);
        command.args([
            temp_file_path,
            "--add-pythonic-hints",
            "--max-bytecode-size",
            &self.config.max_bytecode_size.to_string(),
        ]);
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/598)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/starknet_sierra_compile/src/build_utils.rs` line 3 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/598#-O5IZAxM0M8WM-THn5ZA:-O5J0m-N1Dbvc9JgdK5_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3e4d611c513404e5e224c0cd0b2834b015eb26a/crates/starknet_sierra_compile/src/build_utils.rs#L3)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why static?
I think the caller should be responsible of the lifetime of this.

Is it possible to return std::path::Path, and remove the Box::leak?
</blockquote></details>

Done.
___
*[`crates/starknet_sierra_compile/src/compile_test.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/598#-O5IZUML9bd5fT1yXTKq:-O5J3gvS3zQ0SCuhxwbo:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3e4d611c513404e5e224c0cd0b2834b015eb26a/crates/starknet_sierra_compile/src/compile_test.rs#L19)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Just for consistency, consider changing this to a function as well (like the `command_line_compiler`)
</blockquote></details>

Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/598#-:-O5mT_6KDripEw2lCGLz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/598)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Sep 3, 2:07 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/598).

**Comment by shaharsamocha7** [comment]
This pr stack is for taking the sierra binary instead of compiling it, right?
Why do you want that? whouldn't it be more safe if this code compiles sierra binary by itself?

**Comment by shaharsamocha7** [comment]
*[`crates/starknet_sierra_compile/src/build_utils.rs` line 6 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/598#-O5qdoYa3C2hMmThDbcg:-O5qdoYa3C2hMmThDbch:bnq6ptl) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3ecaa2a7b1541eac96960ab2d1c963624f88ca4/crates/starknet_sierra_compile/src/build_utils.rs#L6)):*
> ```XML
> 
> fn out_dir() -> PathBuf {
>     Path::new(&std::env::var("OUT_DIR").expect("Failed to get the OUT_DIR environment variable"))
> ```

If this library gets compiled into a binary won't this always fail since OUT_DIR is only set in the context of a cargo command? Is this an issue?

**Comment by shaharsamocha7** [comment]
*[`crates/starknet_sierra_compile/src/errors.rs` line 25 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/598#-O5qeaWxAXLLEI7jGk5V:-O5qeaWxAXLLEI7jGk5W:bnyl6y2) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3ecaa2a7b1541eac96960ab2d1c963624f88ca4/crates/starknet_sierra_compile/src/errors.rs#L25)):*
> ```XML
> }
> 
> impl From<serde_json::Error> for CompilationUtilError {
> ```

Why both of these errors are wrapped into the same error?
Wouldn't you want different error types?



_Code quote:_
```XML
impl From<serde_json::Error> for CompilationUtilError {
```

**Comment by ArniStarkware** [comment]
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This pr stack is for taking the sierra binary instead of compiling it, right?
Why do you want that? whouldn't it be more safe if this code compiles sierra binary by itself?
</blockquote></details>

This PR stack uses the `starknet_sierra_compile` binary to compile Sierra -> Casm instead of using the CairoLang crate as a gateway dependency.

Why do we want that:
1. the compiler crate does not intend to be used as a dependency. There is no guarantee that the code will not panic or how much resources the process will take. This is the issue with the previous solution (with `CairoLangSierraToCasmCompiler` replaced in the following PR in this stack (#599).
2. With this solution - we import the binary as a cargo dependency. We then run the binary as a process this way - at some point, we can better control the resources the compilation process takes (see `TODO(Arni): Setup the ulimit for the process.`) and any panic will be handled gracefully.
   a. One more upside of using the `cargo install` command is that it is OS-agnostic. If this code is run on a MAC, the correct binary will be downloaded. 


Did that answer the question? Because I am afraid we do not use the same terminology (What does "sierra binary" mean? 
   - the sierra program to be compiled during the "process tx" flow for a declare transaction?
   - or the binary that compiled sierra to casm?
)

**Comment by ArniStarkware** [comment]
*[`crates/starknet_sierra_compile/src/build_utils.rs` line 6 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/598#-O5qdoYa3C2hMmThDbcg:-O5qmGdlBTAdCmygEi0l:bkb4j2d) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3ecaa2a7b1541eac96960ab2d1c963624f88ca4/crates/starknet_sierra_compile/src/build_utils.rs#L6)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

If this library gets compiled into a binary won't this always fail since OUT_DIR is only set in the context of a cargo command? Is this an issue?
</blockquote></details>

I am not sure.
We want to run this library as a separate microservice at some point. If this indeed requires us to compile this lib into a bin, what you pointed out is indeed a problem.

**Comment by ArniStarkware** [comment]
*[`crates/starknet_sierra_compile/src/errors.rs` line 25 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/598#-O5qeaWxAXLLEI7jGk5V:-O5qnA8q3ijHKgzQMQTW:bp3y8nc) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3ecaa2a7b1541eac96960ab2d1c963624f88ca4/crates/starknet_sierra_compile/src/errors.rs#L25)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why both of these errors are wrapped into the same error?
Wouldn't you want different error types?
</blockquote></details>

These errors should never happen (Thus, they are converted into UnexpectedError). I do not intend to handle these errors differently than other `UnexpectedError`s.

My motivation was "each error type should be mapped to some handle of this error".
and "unexpected error points to a bug in the code - it should be handled gracefully but the bug should be fixed".

**Pull request merged**
