### PR TITLE
chore(blockifier): remove cairo1 syscall_ptr security_check

### PR DESCRIPTION
**Pull request by meship-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1148)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 313 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1148#-O87apBC6RCPjUh5gnau:-O87apBC6RCPjUh5gnav:b-v4jhqo) ([raw file](https://github.com/starkware-libs/sequencer/blob/98d82db7493f9db25ae9c679dd037a1d00f21b10/crates/blockifier/src/execution/syscalls/hint_processor.rs#L313)):*
> ```XML
>                 "Test functions are unsupported on starknet."
>             ))));
>         };
> ```

you removed the check that the hint is starknetHint::SystemCall



_Code quote:_
```XML
        let StarknetHint::SystemCall { system: syscall } = hint else {
            return Err(HintError::Internal(VirtualMachineError::Other(anyhow::anyhow!(
                "Test functions are unsupported on starknet."
            ))));
        };
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1148)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 313 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1148#-O87apBC6RCPjUh5gnau:-O8VLTFzEcp4pHAFeNEI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/98d82db7493f9db25ae9c679dd037a1d00f21b10/crates/blockifier/src/execution/syscalls/hint_processor.rs#L313)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

you removed the check that the hint is starknetHint::SystemCall
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1148#-:-O8VZfAE9qHrp6z6ksyX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1148)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 315 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1148#-O8VuoRi4TMdezQyVihf:-O8VuoRj3SEWKbF-Tobv:b-636mhe) ([raw file](https://github.com/starkware-libs/sequencer/blob/612b2289021f83a9a8702c3ec2f95693a57daefb/crates/blockifier/src/execution/syscalls/hint_processor.rs#L315)):*
> ```XML
>         };
>         let initial_syscall_ptr = get_ptr_from_res_operand_unchecked(vm, syscall);
>         self.verify_syscall_ptr(initial_syscall_ptr)?;
> ```

Can you also delete the `verify_syscall_ptr` method (in thge non-deprecated `hint_processor` file)?



_Code quote:_
```XML
self.verify_syscall_ptr(initial_syscall_ptr)?;
```

**Pull request merged**
