### PR TITLE
test(blockifier): test negative flows of cairo1 revert trace

### PR DESCRIPTION
**Pull request by dorimedini-starkware**

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1469?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1469** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1469?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1468** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1468?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1461** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1461?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1460** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1460?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1459** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1459?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1458** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1458?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1457** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1457?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1469)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 1042 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1469#-OAHOQpn3H932McBKhTM:-OAHOQpn3H932McBKhTN:btaqvx2) ([raw file](https://github.com/starkware-libs/sequencer/blob/9976b8a89ddc1dd429f442c778056db3ede2fe0f/crates/blockifier/src/execution/stack_trace_test.rs#L1042)):*
> ```XML
> 
> /// If extraction function is called with a successful callinfo, it should return an empty stack and
> /// the original retdata.
> ```

This is strange.

Shouldn't it panic in that case?



_Code quote:_
```XML
/// If extraction function is called with a successful callinfo, it should return an empty stack and
/// the original retdata.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1469)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 1042 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1469#-OAHOQpn3H932McBKhTM:-OAHOsJsCYDHpHO94pdn:bk1dy6p) ([raw file](https://github.com/starkware-libs/sequencer/blob/9976b8a89ddc1dd429f442c778056db3ede2fe0f/crates/blockifier/src/execution/stack_trace_test.rs#L1042)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

This is strange.

Shouldn't it panic in that case?
</blockquote></details>

We don't want to panic at all in the stack extraction; if the input is "malformed" we use a fallback by design

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 1042 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1469#-OAHOQpn3H932McBKhTM:-OAHQO-u9fMtZyAzwutq:b-uv1tg7) ([raw file](https://github.com/starkware-libs/sequencer/blob/9976b8a89ddc1dd429f442c778056db3ede2fe0f/crates/blockifier/src/execution/stack_trace_test.rs#L1042)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

We don't want to panic at all in the stack extraction; if the input is "malformed" we use a fallback by design
</blockquote></details>

We shouldn't call that function in that case.
I guess I'm ok with the current behavior but it is a bit strange to test it.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 1042 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1469#-OAHOQpn3H932McBKhTM:-OAHQjujElKcH4VirlMf:bw65cf3) ([raw file](https://github.com/starkware-libs/sequencer/blob/9976b8a89ddc1dd429f442c778056db3ede2fe0f/crates/blockifier/src/execution/stack_trace_test.rs#L1042)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

We shouldn't call that function in that case.
I guess I'm ok with the current behavior but it is a bit strange to test it.
</blockquote></details>

can you just update the comment and say that we don't expect the function to be called in this case?

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1469#-:-OAMOi4WBRxJFsm0ql2K:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1469)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
