### PR TITLE
refactor(mempool): arrange add-tx-input macro

### PR DESCRIPTION
**Pull request by MohammadNassar1**

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1632)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1632#-OAMaJvD0ZryhELm9PsH:-OAMaJvD0ZryhELm9PsI:bejceaf) (no related file):*
This PR:
1. Re-order macros according to inputs.
2. remove unused macros.
3. break long lines.

___

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1632)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/test_utils.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1632#-OAMghsg8-fzFQzm150m:-OAMghsg8-fzFQzm150n:bb7ozpr) ([raw file](https://github.com/starkware-libs/sequencer/blob/436b71e94de590b3bdcac900410bc13313c18c34/crates/mempool/src/test_utils.rs#L96)):*
> ```XML
> 
>         let tx = $crate::tx!(
>             tip: $tip, tx_hash: $tx_hash,
> ```

tab?



_Code quote:_
```XML
, 
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1632)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/test_utils.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1632#-OAMghsg8-fzFQzm150m:-OAMki--AxqCfz3E6MrK:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/436b71e94de590b3bdcac900410bc13313c18c34/crates/mempool/src/test_utils.rs#L96)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

tab?
</blockquote></details>

Done

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1632)* status: all files reviewed, 1 unresolved discussion

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1632#-:-OAMneoKEcgm6bM79io7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1632)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1632#-OAMaJvD0ZryhELm9PsH:-OAMyV4v29BvSvV1zrqT:b-viuk) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

This PR:
1. Re-order macros according to inputs.
2. remove unused macros.
3. break long lines.
</blockquote></details>

Note that
- I have ordered the macros according to the input. E.g. A-B-C-D, A-B-C, A-C, B-C, C-D, C, etc.
- There are unused macros as the `test_utils` is public.

___

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1632)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1632#-:-OANnHss3PCa3fB8qBlF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1632)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1632#-OAMaJvD0ZryhELm9PsH:-OANnsd08bKNrEx9X2MK:bwleuh5) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Note that
- I have ordered the macros according to the input. E.g. A-B-C-D, A-B-C, A-C, B-C, C-D, C, etc.
- There are unused macros as the `test_utils` is public.
</blockquote></details>

- Is it consistent with new `tx!()` order?
- How did you find out which ones are unused?

___

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1632)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1632#-:-OAO5Czb8TGPAL1Y1w9P:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
