### PR TITLE
chore(starknet_integration_tests): dump entire config to a preset file

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2705)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @Itay-Tsabary-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OEJjYMIELQKsWp4KPVA:-OEJjYMJ9exFCVXMbOG9:b-sn7ykq) (no related file):*
Did you try to use this? https://github.com/starkware-libs/sequencer/blob/ca58f5c3a0c4d8d26e82f9260e6383d69c99df59/crates/papyrus_config/src/presentation.rs#L12
___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OEJkDKpCgYYETGsll1G:-OEJkDKpCgYYETGsll1H:bz1epy) (no related file):*
Why do we dump the entire configuration to a preset instead of just the parameters we change?
___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OEJkICREme81bzhx5Co:-OEJkICREme81bzhx5Cp:b-q24ak1) (no related file):*
Why do we automate this instead of manually creating the presets?

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2705)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OEJkDKpCgYYETGsll1G:-OEJmP1o98boXHZoDjDy:bu73d8s) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do we dump the entire configuration to a preset instead of just the parameters we change?
</blockquote></details>

Per @alonh5 's request
___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OEJkICREme81bzhx5Co:-OEJmR6E1-LsqK_2-8My:b-bh2oc7) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do we automate this instead of manually creating the presets?
</blockquote></details>

Auto-generated or manually-crafted preset discussion is not in the scope of this pr.
___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OEJjYMIELQKsWp4KPVA:-OEJoPvx5U_i981dt8MJ:b-2uophi) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Did you try to use this? https://github.com/starkware-libs/sequencer/blob/ca58f5c3a0c4d8d26e82f9260e6383d69c99df59/crates/papyrus_config/src/presentation.rs#L12
</blockquote></details>

Originally, no. Just did now though, didn't work :-\

**Review by yair-starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2705)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @Itay-Tsabary-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OEJjYMIELQKsWp4KPVA:-OEJs8xrEs-sOe8vYFyG:bq83tic) (no related file):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Originally, no. Just did now though, didn't work :-\
</blockquote></details>

WDYM didn't work?

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2705)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2705)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OEKC0Ot2ywRZYAF5sdV:-OEO1OTw2utZk4FrTHeZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2667820312d78c049bf6f58aed040d657082088/crates/starknet_integration_tests/src/config_utils.rs#L80)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why must this be an argument for this function? Is it meant to be used elsewhere with a different string?
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OENqQeoEzXJvY8g_o2H:-OENzmzi-TR4V2pgbT3-:b-p9va6p) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3385dd418907bd5933f77e19d1af2817fd8ccaf/crates/starknet_integration_tests/src/config_utils.rs#L64)):*
> Do we need this now that we dump all of the values regardless if they're required?

Yes, the required parameters are not actual parameters in the config: they are used in the loading process to set certain other values, but you cannot directly access them. As such, they are not in the dumped map, and need to be manually added.
Creating a dumping function that unifies these together is out of scope of this pr, let's discuss offline.

> What makes required params required?

They are listed as such in the config. Specifically, these specific values are required pointer targets: there are other non-required parameters that draw their values from these, e.g., `chain id`.

> `IIUC they should be given by the user, it's not enough to take them from the config because they could be still be the default values.`

Exactly, they are not in the config, and need to be set externally. Please note the test does exactly that by using the test util `RequiredParams` struct. Also, please note that they do not have default values.
___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OENoztpDruZjKZQ2QM7:-OEO2S0c4-EhVjli7pae:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3385dd418907bd5933f77e19d1af2817fd8ccaf/crates/starknet_integration_tests/src/config_utils.rs#L175)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add periods at the end of comments.
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OENq1BM6NpEasn3hsxc:-OEO2SgL2SLbHAptfXXh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3385dd418907bd5933f77e19d1af2817fd8ccaf/crates/starknet_integration_tests/src/config_utils.rs#L175)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Document.
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 193 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OENp62c4RL0NaxHlGuJ:-OEO5eNr-7YeykIL_8iM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3385dd418907bd5933f77e19d1af2817fd8ccaf/crates/starknet_integration_tests/src/config_utils.rs#L193)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

If this is a wrong use of this function, return an error or panic instead of returning an empty object.
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 198 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OENpwOu1iVrF4mXuhks:-OEO5X0P3GCouKlP3vOt:bln6fb2) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3385dd418907bd5933f77e19d1af2817fd8ccaf/crates/starknet_integration_tests/src/config_utils.rs#L198)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Document. Specifically, mention that the required params override the previous values.
</blockquote></details>

Added doc, but, there is no overwriting here. Please see the the response above ^.
___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 199 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OENpOV9--6MQszhV6OI:-OEO5XZH4ZaPPJ-7QJ7p:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3385dd418907bd5933f77e19d1af2817fd8ccaf/crates/starknet_integration_tests/src/config_utils.rs#L199)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Here also, if the values are not objects, you should panic. Imagine someone using this function wrong, it would be very hard to understand why it isn't doing anything.
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2705)* status: all files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OENq1BM6NpEasn3hsxc:-OEO8twa2EFx3ohEHhKd:bi4ow4b) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3385dd418907bd5933f77e19d1af2817fd8ccaf/crates/starknet_integration_tests/src/config_utils.rs#L175)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

That's a bit much, I meant a short documentation of 1-2 sentences. Same for doc below.
___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 198 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OENpwOu1iVrF4mXuhks:-OEO812fAmz1hAoxNIbe:bjnysiu) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3385dd418907bd5933f77e19d1af2817fd8ccaf/crates/starknet_integration_tests/src/config_utils.rs#L198)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Added doc, but, there is no overwriting here. Please see the the response above ^.
</blockquote></details>

Even in the example in the doc `updated_value2` overrides `value2`.
___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OEO9Ug2A9JLBX162StA:-OEO9Ug2A9JLBX162StB:byabaf) ([raw file](https://github.com/starkware-libs/sequencer/blob/7db4a124ebe6df04a6eba8e3d27d0d6f4c814995/crates/starknet_integration_tests/src/config_utils.rs#L79)):*
> ```XML
>     .unwrap();
> 
>     dump_json_data(required_params_json.clone(), "required_params_json", PathBuf::from("."));
> ```

What are all these additions?



_Code quote:_
```XML
dump_json_data
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2705)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OENq1BM6NpEasn3hsxc:-OEOrPf_2ZP_Uxbt7nUc:b-phnatm) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3385dd418907bd5933f77e19d1af2817fd8ccaf/crates/starknet_integration_tests/src/config_utils.rs#L175)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

That's a bit much, I meant a short documentation of 1-2 sentences. Same for doc below.
</blockquote></details>

I shortened the docs, but given they are already there, I'd prefer to keep them at their new lengths rather than making further reductions.
___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 198 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OENpwOu1iVrF4mXuhks:-OEOri3HE_WNhR_W8o3_:b-t0v6jj) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3385dd418907bd5933f77e19d1af2817fd8ccaf/crates/starknet_integration_tests/src/config_utils.rs#L198)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Even in the example in the doc `updated_value2` overrides `value2`.
</blockquote></details>

In the reviewed versions indeed there could have been overwriting, despite the provided json files having no such overlapping keys.
I added an assertion to the code to further amplify that, and deleted the (irrelevant) overwriting example.
___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OEO9Ug2A9JLBX162StA:-OEOrLG9EFZJh-p9W18J:b-qdb2k1) ([raw file](https://github.com/starkware-libs/sequencer/blob/7db4a124ebe6df04a6eba8e3d27d0d6f4c814995/crates/starknet_integration_tests/src/config_utils.rs#L79)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What are all these additions?
</blockquote></details>

Accidental debug leftovers, removed, thanks.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-:-OEOu1cL1rv5aVwtTOhF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 198 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2705#-OENpwOu1iVrF4mXuhks:-OEOtvnZ8Aohy5xHohK2:b-y0vmfd) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3385dd418907bd5933f77e19d1af2817fd8ccaf/crates/starknet_integration_tests/src/config_utils.rs#L198)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

In the reviewed versions indeed there could have been overwriting, despite the provided json files having no such overlapping keys.
I added an assertion to the code to further amplify that, and deleted the (irrelevant) overwriting example.
</blockquote></details>

Oh I see, thanks.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2705)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
