### PR TITLE
build: blockifier regression test add get fee token addresses

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/948)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/948?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#948** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/948?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#946** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/946?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#945** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/945?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by aner-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/948)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/948#-O7TvdTe8JcdOheBz9vV:-O7TvdTe8JcdOheBz9vW:bmiqveu) ([raw file](https://github.com/starkware-libs/sequencer/blob/d56d94859113f692506cec1ad3633aa4f822670b/crates/papyrus_execution/src/lib.rs#L94)):*
> ```XML
> const STARKNET_VERSION_O_13_1: &str = "0.13.1";
> const STARKNET_VERSION_O_13_2: &str = "0.13.2";
> pub const STRK_FEE_CONTRACT_ADDRESS: &str =
> ```

Blocked until approved by @dorimedini-starkware.



_Code quote:_
```XML
pub
```
___
*[`crates/papyrus_execution/src/lib.rs` line 96 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/948#-O7Tvhy17IXTAyJ-tx8y:-O7Tvhy17IXTAyJ-tx8z:bmiqveu) ([raw file](https://github.com/starkware-libs/sequencer/blob/d56d94859113f692506cec1ad3633aa4f822670b/crates/papyrus_execution/src/lib.rs#L96)):*
> ```XML
> pub const STRK_FEE_CONTRACT_ADDRESS: &str =
>     "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d";
> pub const ETH_FEE_CONTRACT_ADDRESS: &str =
> ```

Blocked until approved by @dorimedini-starkware.



_Code quote:_
```XML
pub
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/948)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/948#-O7TvdTe8JcdOheBz9vV:-O7Xv81uBL04EMN5IwYe:bmwtlj0) ([raw file](https://github.com/starkware-libs/sequencer/blob/d56d94859113f692506cec1ad3633aa4f822670b/crates/papyrus_execution/src/lib.rs#L94)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Blocked until approved by @dorimedini-starkware.
</blockquote></details>

fine by me. maybe the const location isn't ideal but that's out of scope
___
*[`crates/papyrus_execution/src/lib.rs` line 96 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/948#-O7Tvhy17IXTAyJ-tx8y:-O7XvAdh11oscpsR2xKC:b-vk1xr4) ([raw file](https://github.com/starkware-libs/sequencer/blob/d56d94859113f692506cec1ad3633aa4f822670b/crates/papyrus_execution/src/lib.rs#L96)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Blocked until approved by @dorimedini-starkware.
</blockquote></details>

fine by me

**Review by aner-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/948)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/948#-:-O7xJJ0B5_XBQAdL0eym:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
