### PR TITLE
feat(batcher): fetch L1Handler txs in propose

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Comment by yair-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1907?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1907** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1907?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1879** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1879?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1870** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1870?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1791** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1791?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1788** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1788?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1787** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1787?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yair-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1907)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/transaction_provider.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBL6TOu4vNr9cwn6hy8:-OBL6TOu4vNr9cwn6hy9:b-2bl4z5) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ccd24b14df332987c32eac3eba05885a897ac7a/crates/batcher/src/transaction_provider.rs#L36)):*
> ```XML
> 
> #[derive(Clone, Debug, Serialize, Deserialize, Validate, PartialEq)]
> pub struct TransactionProviderConfig {
> ```

Can this field be part of the batcher config? I don't think we need a special config for this
___
*[`crates/batcher/src/transaction_provider.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBL6tQ19tx65vGo7UT8:-OBL6tQ19tx65vGo7UT9:bfqyfco) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ccd24b14df332987c32eac3eba05885a897ac7a/crates/batcher/src/transaction_provider.rs#L44)):*
> ```XML
>         Self { max_l1_handler_txs_per_block: 100 }
>     }
> }
> ```

Why implement default as 100? 0 makes more sense IMO.



_Code quote:_
```XML
impl Default for TransactionProviderConfig {
    fn default() -> Self {
        Self { max_l1_handler_txs_per_block: 100 }
    }
}
```
___
*[`crates/batcher/src/transaction_provider.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBL7joM1MKIYyvhHuw8:-OBL7joM1MKIYyvhHuw9:by8lm26) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ccd24b14df332987c32eac3eba05885a897ac7a/crates/batcher/src/transaction_provider.rs#L67)):*
> ```XML
>     L1 { n_txs_so_far: usize },
>     Mempool,
> }
> ```

Document.



_Code quote:_
```XML
enum TxProviderPhase {
    L1 { n_txs_so_far: usize },
    Mempool,
}
```
___
*[`crates/batcher/src/transaction_provider.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBL9sGLDcwlwwUSW8Sy:-OBL9sGLDcwlwwUSW8Sz:b-bs5b2a) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ccd24b14df332987c32eac3eba05885a897ac7a/crates/batcher/src/transaction_provider.rs#L83)):*
> ```XML
>     }
> 
>     fn get_l1_handler_txs(&mut self, n_txs: usize) -> Vec<Transaction> {
> ```

Instead of hiding the `phase` logic inside this function, try handling it in the `get_txs` function, and have this function just return `<=n_txs` txs. I think it will simplify things.
You can extract the mempool get_txs into a helper function as well to make it symmetrical.

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1907)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/batcher/src/transaction_provider.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBL6TOu4vNr9cwn6hy8:-OBLHUeh5MoaGq42GwIh:bujsdak) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ccd24b14df332987c32eac3eba05885a897ac7a/crates/batcher/src/transaction_provider.rs#L36)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can this field be part of the batcher config? I don't think we need a special config for this
</blockquote></details>

I think it is nicer to have a config struct.
IMO, we should also move `n_txs` from being an argument of `get_txs` to being a config member (the block builder always passes the same value).
___
*[`crates/batcher/src/transaction_provider.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBL6tQ19tx65vGo7UT8:-OBLIlKk3Drss7ps4sUq:bis0mre) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ccd24b14df332987c32eac3eba05885a897ac7a/crates/batcher/src/transaction_provider.rs#L44)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why implement default as 100? 0 makes more sense IMO.
</blockquote></details>

How does 0 make sense? By default no l1handler at all?
___
*[`crates/batcher/src/transaction_provider.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBL7joM1MKIYyvhHuw8:-OBLJ4IY-Z1F3_utHHfp:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ccd24b14df332987c32eac3eba05885a897ac7a/crates/batcher/src/transaction_provider.rs#L67)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Document.
</blockquote></details>

Done.
___
*[`crates/batcher/src/transaction_provider.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBL9sGLDcwlwwUSW8Sy:-OBLJlTq6TuMQTz_LlTR:bu6xj8g) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ccd24b14df332987c32eac3eba05885a897ac7a/crates/batcher/src/transaction_provider.rs#L83)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Instead of hiding the `phase` logic inside this function, try handling it in the `get_txs` function, and have this function just return `<=n_txs` txs. I think it will simplify things.
You can extract the mempool get_txs into a helper function as well to make it symmetrical.
</blockquote></details>

Not sure how you can do both things together.
I extracted the mempool logic, seems better than implementing both functions in the same place.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1907)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/transaction_provider.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBL6TOu4vNr9cwn6hy8:-OBLQHOhDNs58K3bGhId:be9g3gy) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ccd24b14df332987c32eac3eba05885a897ac7a/crates/batcher/src/transaction_provider.rs#L36)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think it is nicer to have a config struct.
IMO, we should also move `n_txs` from being an argument of `get_txs` to being a config member (the block builder always passes the same value).
</blockquote></details>

The block builder is a user of the tx provider, it makes sense for him to ask for a number of txs (even if it's always the same number as of now).
Regarding the extra config, I don't see the benefit. The field itself will be stored in the struct (because he needs it), and the batcher is the one "deciding" that limit. I'd rather opt for the simpler option with less code.
___
*[`crates/batcher/src/transaction_provider.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBL6tQ19tx65vGo7UT8:-OBLMCKbDj9-SYDgj8G4:b9sua9n) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ccd24b14df332987c32eac3eba05885a897ac7a/crates/batcher/src/transaction_provider.rs#L44)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

How does 0 make sense? By default no l1handler at all?
</blockquote></details>

By default a node doens't "have to" execute txs from l1. Either way I think ilia said it will be a small amount in each block, likely single digit. We can put a small positive number for now, like 3 or 5.
___
*[`crates/batcher/src/transaction_provider.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBL9sGLDcwlwwUSW8Sy:-OBLNIfSAYNSokPSogpn:b-r4ggbr) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ccd24b14df332987c32eac3eba05885a897ac7a/crates/batcher/src/transaction_provider.rs#L83)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Not sure how you can do both things together.
I extracted the mempool logic, seems better than implementing both functions in the same place.
</blockquote></details>

I meant moving the `phase` logic outside and making this function simpler. something like this:
```
#[async_trait]
impl TransactionProvider for ProposeTransactionProvider {
    async fn get_txs(&mut self, n_txs: usize) -> Result<NextTxs, TransactionProviderError> {
        let mut next_txs = vec![];
        if self.phase == L1 {
            // get_l1_handler_txs.
            // switch to mempool phase if needed.
        }
        if self.phase == Mempool {
            // get_mempool_txs.
        }
        Ok(NextTxs::Txs(next_txs))
    }
}
```

**Review by alonh5 — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 1 files at r3, 4 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1907)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/transaction_provider.rs` line 68 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBPXEet2S9GJb5_khu3:-OBPXEet2S9GJb5_khu4:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/f077e5a511490448ac2bd1fca72497565f8b107a/crates/batcher/src/transaction_provider.rs#L68)):*
> ```XML
>             .map(Transaction::L1Handler)
>             .collect();
>         txs
> ```





_Suggestion:_
```XML
        self
            .l1_provider_client
            .get_txs(n_txs)
            .into_iter()
            .map(Transaction::L1Handler)
            .collect()
```
___
*[`crates/batcher/src/transaction_provider.rs` line 99 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBP_LzQ5m1QDjsec_6q:-OBP_LzQ5m1QDjsec_6r:b-vrflef) ([raw file](https://github.com/starkware-libs/sequencer/blob/f077e5a511490448ac2bd1fca72497565f8b107a/crates/batcher/src/transaction_provider.rs#L99)):*
> ```XML
>             if no_more_l1handler_in_provider || reached_max_l1handler_txs_in_block {
>                 self.phase = TxProviderPhase::Mempool;
>             }
> ```

Nice looks good.
Add blank line above and below, and add a comment for this block.



_Code quote:_
```XML
            let no_more_l1handler_in_provider = l1handler_txs.len() < n_l1handler_txs_to_get;
            let reached_max_l1handler_txs_in_block =
                self.n_l1handler_txs_so_far == self.max_l1_handler_txs_per_block;
            if no_more_l1handler_in_provider || reached_max_l1handler_txs_in_block {
                self.phase = TxProviderPhase::Mempool;
            }
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1907)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/batcher/src/transaction_provider.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBL6TOu4vNr9cwn6hy8:-OBPGpABDkBWNSq1BDqj:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ccd24b14df332987c32eac3eba05885a897ac7a/crates/batcher/src/transaction_provider.rs#L36)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

The block builder is a user of the tx provider, it makes sense for him to ask for a number of txs (even if it's always the same number as of now).
Regarding the extra config, I don't see the benefit. The field itself will be stored in the struct (because he needs it), and the batcher is the one "deciding" that limit. I'd rather opt for the simpler option with less code.
</blockquote></details>

Done.
___
*[`crates/batcher/src/transaction_provider.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBL6tQ19tx65vGo7UT8:-OBPGrBa8_xMlbACCOtt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ccd24b14df332987c32eac3eba05885a897ac7a/crates/batcher/src/transaction_provider.rs#L44)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

By default a node doens't "have to" execute txs from l1. Either way I think ilia said it will be a small amount in each block, likely single digit. We can put a small positive number for now, like 3 or 5.
</blockquote></details>

Done.

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1907)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/batcher/src/transaction_provider.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBL9sGLDcwlwwUSW8Sy:-OBPdyj16wzsjfqbqTW1:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ccd24b14df332987c32eac3eba05885a897ac7a/crates/batcher/src/transaction_provider.rs#L83)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I meant moving the `phase` logic outside and making this function simpler. something like this:
```
#[async_trait]
impl TransactionProvider for ProposeTransactionProvider {
    async fn get_txs(&mut self, n_txs: usize) -> Result<NextTxs, TransactionProviderError> {
        let mut next_txs = vec![];
        if self.phase == L1 {
            // get_l1_handler_txs.
            // switch to mempool phase if needed.
        }
        if self.phase == Mempool {
            // get_mempool_txs.
        }
        Ok(NextTxs::Txs(next_txs))
    }
}
```

</blockquote></details>

done
___
*[`crates/batcher/src/transaction_provider.rs` line 99 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBP_LzQ5m1QDjsec_6q:-OBPeZTc9a-XG8EcvaRp:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/f077e5a511490448ac2bd1fca72497565f8b107a/crates/batcher/src/transaction_provider.rs#L99)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Nice looks good.
Add blank line above and below, and add a comment for this block.
</blockquote></details>

done

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-:-OBPgJS-5Mpy6oxnXlBm:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/transaction_provider_test.rs` line 80 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBPfMsVB9oKqnlfpps2:-OBPfMsVB9oKqnlfpps3:b9dsfht) ([raw file](https://github.com/starkware-libs/sequencer/blob/f077e5a511490448ac2bd1fca72497565f8b107a/crates/batcher/src/transaction_provider_test.rs#L80)):*
> ```XML
> 
>     let txs = tx_provider.get_txs(MAX_TXS_PER_FETCH).await.unwrap();
>     let data = assert_matches!(txs, NextTxs::Txs(txs) if txs.len() == 10 => txs);
> ```

also below.



_Suggestion:_
```XML
MAX_TXS_PER_FETCH
```
___
*[`crates/batcher/src/transaction_provider_test.rs` line 0 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBPgDHP6cBYXJd03w1z:-OBPgDHP6cBYXJd03w2-:b-83sjoh) ([raw file](https://github.com/starkware-libs/sequencer/blob/24179fa81e051cdbbd0f18807881b8b46ef0078f/crates/batcher/src/transaction_provider_test.rs#L0)):*
Nice!

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1907)* status: 3 of 8 files reviewed, all discussions resolved (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/batcher/src/transaction_provider_test.rs` line 80 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBPfMsVB9oKqnlfpps2:-OBQMPkBBYwmpm8sugqx:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/f077e5a511490448ac2bd1fca72497565f8b107a/crates/batcher/src/transaction_provider_test.rs#L80)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

also below.
</blockquote></details>

done

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1907)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/transaction_provider_test.rs` line 80 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBPfMsVB9oKqnlfpps2:-OBUPrir92Ci7jQpGEDd:b-vr4p06) ([raw file](https://github.com/starkware-libs/sequencer/blob/f077e5a511490448ac2bd1fca72497565f8b107a/crates/batcher/src/transaction_provider_test.rs#L80)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

done
</blockquote></details>

I don't see it.

**Review by alonh5 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1907)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

___
*[`crates/batcher/src/transaction_provider_test.rs` line 80 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBPfMsVB9oKqnlfpps2:-OBUS92z-4aLAr8k9CWZ:bvv37l1) ([raw file](https://github.com/starkware-libs/sequencer/blob/f077e5a511490448ac2bd1fca72497565f8b107a/crates/batcher/src/transaction_provider_test.rs#L80)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I don't see it.
</blockquote></details>

It's in the next PR. Unblocking.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1907)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/batcher/src/transaction_provider.rs` line 101 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1907#-OBUjW_q7AgH_J3Zie6n:-OBUjW_q7AgH_J3Zie6o:b-miqaqc) ([raw file](https://github.com/starkware-libs/sequencer/blob/91001af396b9a9c6ef790ac58c8f9a84c7d84d7c/crates/batcher/src/transaction_provider.rs#L101)):*
> ```XML
>                 return Ok(NextTxs::Txs(txs));
>             }
>         }
> ```

Just thinking out loud here:
if the max_l1_handler_txs_per_block is expected to be smaller than the chunk size (I don't know if this is the case but you discussed here numbers < 10), then we could get L1 transactions at the first chunk only.

And check that max_l1_handler_transaction < chunk size at the config. 



_Code quote:_
```XML
        if self.phase == TxProviderPhase::L1 {
            let n_l1handler_txs_to_get =
                min(self.max_l1_handler_txs_per_block - self.n_l1handler_txs_so_far, n_txs);
            let mut l1handler_txs = self.get_l1_handler_txs(n_l1handler_txs_to_get);
            self.n_l1handler_txs_so_far += l1handler_txs.len();

            // Determine whether we need to switch to mempool phase.
            let no_more_l1handler_in_provider = l1handler_txs.len() < n_l1handler_txs_to_get;
            let reached_max_l1handler_txs_in_block =
                self.n_l1handler_txs_so_far == self.max_l1_handler_txs_per_block;
            if no_more_l1handler_in_provider || reached_max_l1handler_txs_in_block {
                self.phase = TxProviderPhase::Mempool;
            }

            txs.append(&mut l1handler_txs);
            if txs.len() == n_txs {
                return Ok(NextTxs::Txs(txs));
            }
        }
```

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1907)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1907)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Comment by yair-starkware** [comment]
### Merge activity

* **Nov 12, 9:02 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1907).

**Pull request merged**
