### PR TITLE
fix(batcher): add block builder chain id field to config pointer

### PR DESCRIPTION
**Pull request by alonh5**

### CODE REVIEW

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1471)

**Comment by alonh5** [comment]
* **#1471** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1471?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1471#-:-O9n5kTRCfyWsrTzHd1W:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/mempool_node/src/config/node_config.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1471#-O9n5mXwDAcQWJFrotzu:-O9n5mXwDAcQWJFrotzv:b-xvmhze) ([raw file](https://github.com/starkware-libs/sequencer/blob/b7a68baaaa94fcc720af3beef3257fd2c9e497cf/crates/mempool_node/src/config/node_config.rs#L36)):*
> ```XML
>             "batcher_config.storage.db_config.chain_id".to_owned(),
>             "gateway_config.chain_info.chain_id".to_owned(),
>             "batcher_config.block_builder_config.chain_info.chain_id".to_owned(),
> ```

Let's keep these sorted, so please move this to be the 2nd element. Leaving as non-blocking.



_Code quote:_
```XML
"batcher_config.block_builder_config.chain_info.chain_id".to_owned(),
```

**Review by alonh5 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1471)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
