### PR TITLE
chore(blockifier_reexecution): complete readme file

### PR DESCRIPTION
**Pull request by aner-starkware**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2232)* status: all files reviewed, 6 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/README.md` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2232#-OCStGFZEbll-E1ws6yg:-OCStGFZEbll-E1ws6yh:b354p86) ([raw file](https://github.com/starkware-libs/sequencer/blob/258f94c94ae5e24dfe1e32685e146fc5d5ad0802/crates/blockifier_reexecution/README.md#L44)):*
> ```Markdown
> ### Uploading Offline Reexecution Files from the GC Bucket
> Uploading files to the GC bucket requires authentication, by typing in the terminal
> `gcloud auth application-default login`
> ```

what's this?



_Code quote:_
```Markdown
application-default
```
___
*[`crates/blockifier_reexecution/README.md` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2232#-OCStJqD6lw737RvHchC:-OCStJqD6lw737RvHchD:byolx9r) ([raw file](https://github.com/starkware-libs/sequencer/blob/258f94c94ae5e24dfe1e32685e146fc5d5ad0802/crates/blockifier_reexecution/README.md#L46)):*
> ```Markdown
> `gcloud auth application-default login`
> 
> Then, to upload the files, in the same terminal run
> ```

i think this is the correct.. *terminology*
... i'll let myself out



_Suggestion:_
```Markdown
shell session
```
___
*[`crates/blockifier_reexecution/README.md` line 85 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2232#-OCSt_dm20bVBWQLGl1k:-OCSt_dm20bVBWQLGl1l:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/258f94c94ae5e24dfe1e32685e146fc5d5ad0802/crates/blockifier_reexecution/README.md#L85)):*
> ```Markdown
> ## Adding/Removing Blocks from the Reexecution Test in the CI
> 
> To add blocks to the reexecution, follow the following steps:
> ```





_Suggestion:_
```Markdown
To add blocks to the reexecution tests, follow the following steps:
```
___
*[`crates/blockifier_reexecution/README.md` line 99 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2232#-OCStj0-4LrQzSjP1Uhg:-OCStj0-4LrQzSjP1Uhh:b-bdfga8) ([raw file](https://github.com/starkware-libs/sequencer/blob/258f94c94ae5e24dfe1e32685e146fc5d5ad0802/crates/blockifier_reexecution/README.md#L99)):*
> ```Markdown
> - 3. Add the block numbers to the file `block_numbers_for_reexecution.json`
> 
> - 4. Add the block numbers to the cases in the test `test_block_reexecution`
> ```

out of scope, but - do you have an idea on how to make a single point of truth from these?
I realize you can't take the contents of a JSON file to create `rstest` cases,
maybe change the `rstest` test to explicitly run (in async) the block numebrs in the JSON, with `case`s?



_Code quote:_
```Markdown
- 3. Add the block numbers to the file `block_numbers_for_reexecution.json`

- 4. Add the block numbers to the cases in the test `test_block_reexecution`
```
___
*[`crates/blockifier_reexecution/README.md` line 105 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2232#-OCSuR7q8ah56kUh4tU5:-OCSuR7q8ah56kUh4tU6:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/258f94c94ae5e24dfe1e32685e146fc5d5ad0802/crates/blockifier_reexecution/README.md#L105)):*
> ```Markdown
> Therefore, when changing the files format, do these 3 steps in order:
> 
> - 1. Change the prefix hash in `offline_reexecution_files_prefix`; it is customary, though not mandatory, to use the current commit hash.
> ```





_Suggestion:_
```Markdown
commit hash (however, it *must* be a unique string that has not been used in the past).
```
___
*[`crates/blockifier_reexecution/README.md` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2232#-OCSum84217S3jD198Vn:-OCSum84217S3jD198Vo:bcf3zn2) ([raw file](https://github.com/starkware-libs/sequencer/blob/258f94c94ae5e24dfe1e32685e146fc5d5ad0802/crates/blockifier_reexecution/README.md#L122)):*
> ```Markdown
> cargo run --bin blockifier_reexecution upload-files
> ```
> **IMPORTANT: DO NOT CHANGE THE HASH IN `offline_reexecution_files_prefix` AFTER UPLOADING THE FILES; IT IS REQUIRED IN ORDER TO PASS THE CI**
> ```

is there any room for human error here?
if they change the hash, the CI will fail, so the PR can't be merged; right?
not sure if this remark is necessary
but at least downgrade it from `**IMPORTANT**: DO NOT...` to `Note: the hash in ... must point to the correct ... otherwise ...`



_Code quote:_
```Markdown
**IMPORTANT: DO NOT CHANGE THE HASH IN `offline_reexecution_files_prefix` AFTER UPLOADING THE FILES; IT IS REQUIRED IN ORDER TO PASS THE CI**
```

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/README.md` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2232#-OCSum84217S3jD198Vn:-OCT48V-4t5FfsL0Zz0i:bfjxee4) ([raw file](https://github.com/starkware-libs/sequencer/blob/258f94c94ae5e24dfe1e32685e146fc5d5ad0802/crates/blockifier_reexecution/README.md#L122)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

There's room for "human error" - people can lose the hash they uploaded the files to, which might be tedious to recover afterwards... Or they can upload different blocks to different hashes due to misunderstanding. I'll change it if you think it's wise (I personally think this is clearer, even if not the most visually appealing).
</blockquote></details>

Also, someone might think that because the commit hash changed, he should change the hash in the file as well... (this will result in a neverending [human] loop :sweat_smile: )

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/README.md` line 99 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2232#-OCStj0-4LrQzSjP1Uhg:-OCT4j1e4qfTItKRW0sP:b-4tvxxb) ([raw file](https://github.com/starkware-libs/sequencer/blob/258f94c94ae5e24dfe1e32685e146fc5d5ad0802/crates/blockifier_reexecution/README.md#L99)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

The problem with this solution (which is possible) is that having a separate test case for each block is in some sense a desired behaviour that you would lose...
</blockquote></details>

Or maybe I didn't completely understand the solution...

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2232#-:-OCTAzVw4nXZ0e0pvqrB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/README.md` line 99 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2232#-OCStj0-4LrQzSjP1Uhg:-OCTACsI1OuhhfqMHjJ-:b-raeh29) ([raw file](https://github.com/starkware-libs/sequencer/blob/258f94c94ae5e24dfe1e32685e146fc5d5ad0802/crates/blockifier_reexecution/README.md#L99)):*
> having a separate test case for each block is in some sense a desired behaviour

it is, but I think it's mainly for (a) easy parallelism and (b) nice output in the `cargo test` console.
I think we can mimic both (a) and (b) in a single `[rstest]` with no cases... we will need to think how to print to console properly but parallelizing a test with tokio is fine IMO
___
*[`crates/blockifier_reexecution/README.md` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2232#-OCSum84217S3jD198Vn:-OCTA_ApBS8EgzsixCYa:b-2smp5r) ([raw file](https://github.com/starkware-libs/sequencer/blob/258f94c94ae5e24dfe1e32685e146fc5d5ad0802/crates/blockifier_reexecution/README.md#L122)):*
> might be tedious to recover afterwards...

hmmmm... we do have this though

1. log the link after running the upload command, so it appears in the console at least temporarily (remark on your other PR)
2. if you browse to the bucket console you can check recent artifacts uploaded to find yours
3. worst case scenario, re-upload

unblocking anyway, I guess losing the hash is annoying..

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2232)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2232)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/README.md` line 99 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2232#-OCStj0-4LrQzSjP1Uhg:-OCTitY9AwUxMmREtgrd:b-3kh8hu) ([raw file](https://github.com/starkware-libs/sequencer/blob/258f94c94ae5e24dfe1e32685e146fc5d5ad0802/crates/blockifier_reexecution/README.md#L99)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

> having a separate test case for each block is in some sense a desired behaviour

it is, but I think it's mainly for (a) easy parallelism and (b) nice output in the `cargo test` console.
I think we can mimic both (a) and (b) in a single `[rstest]` with no cases... we will need to think how to print to console properly but parallelizing a test with tokio is fine IMO
</blockquote></details>

(a) Is similar to what is now in the CLI.
(b) I don't know how to do  - I can print the blocks that failed, but it won't be nice. Also, it's a bit tricky because the `panic!`s will be inside the threads (I think it won't fail on the 1st `panic!`, but I need to test it.

Should I put a TODO?
___
*[`crates/blockifier_reexecution/README.md` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2232#-OCSum84217S3jD198Vn:-OCTjm3sDw5BAi54Ccby:b-67taan) ([raw file](https://github.com/starkware-libs/sequencer/blob/258f94c94ae5e24dfe1e32685e146fc5d5ad0802/crates/blockifier_reexecution/README.md#L122)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

> might be tedious to recover afterwards...

hmmmm... we do have this though

1. log the link after running the upload command, so it appears in the console at least temporarily (remark on your other PR)
2. if you browse to the bucket console you can check recent artifacts uploaded to find yours
3. worst case scenario, re-upload

unblocking anyway, I guess losing the hash is annoying..
</blockquote></details>

Yes, 2-3 is what I meant by tedious... (1) might be work, if they didn't yet close the terminal...

**Pull request merged**
