### PR TITLE
refactor(starknet_api): use general deploy account util

### PR DESCRIPTION
**Pull request by ayeletstarkware**

### CODE REVIEW

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2220#-:-OEOpKxP2lRfOoB8a_Iy:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2220#-OEOex4BB32JoHw4AYdb:-OEOex4BB32JoHw4AYdc:b-aq6jie) ([raw file](https://github.com/starkware-libs/sequencer/blob/61efb021e17c5f07f9b5df9ce67c07db972e8b92/crates/starknet_api/src/rpc_transaction_test.rs#L53)):*
> ```XML
> }
> 
> fn create_deploy_account() -> RpcTransaction {
> ```

Make name consistent

**Review by alonh5 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2220)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2220#-OEOex4BB32JoHw4AYdb:-OEOpTnjBr46lDxPB4lA:b8zg4ml) ([raw file](https://github.com/starkware-libs/sequencer/blob/61efb021e17c5f07f9b5df9ce67c07db972e8b92/crates/starknet_api/src/rpc_transaction_test.rs#L53)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Make name consistent
</blockquote></details>

You can also just change the name of the invoke tx function by removing the `rpc` (it's already in the file name and the test name)

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2220)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2220#-OEOex4BB32JoHw4AYdb:-OEOreJTBjjWyczpCimM:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/61efb021e17c5f07f9b5df9ce67c07db972e8b92/crates/starknet_api/src/rpc_transaction_test.rs#L53)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You can also just change the name of the invoke tx function by removing the `rpc` (it's already in the file name and the test name)
</blockquote></details>

Done

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2220)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2220#-OEOsmFE66NlHGQdfLj0:-OEOsmFE66NlHGQdfLj1:bn82277) ([raw file](https://github.com/starkware-libs/sequencer/blob/134e6e2e89e0b668410a839cea2b04de31dbcc97/crates/starknet_api/src/rpc_transaction_test.rs#L84)):*
> ```XML
> #[case(RpcTransaction::Declare(create_declare_v3()))]
> #[case(create_deploy_account())]
> #[case(create_rpc_invoke_tx())]
> ```

You forgot to remove it here. Remember you can use f2 to rename



_Code quote:_
```XML
#[case(create_rpc_invoke_tx())]
```

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2220)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2220#-OEPBooXBgpDIFEWpXHc:-OEPBooYD_HR3N2_XNYq:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/566412051dc0c4f7822eae012a05e81fda944697/crates/starknet_api/src/rpc_transaction_test.rs#L85)):*
> ```XML
> #[rstest]
> #[case(create_declare_tx())]
> #[case(create_deploy_account())]
> ```





_Suggestion:_
```XML
create_deploy_account_tx
```

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2220)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
