### PR TITLE
refactor(fee): remove more occurnces of resource mapping

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/547)

### CODE REVIEW

**Comment by nimrod-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/547?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#547** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/547?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#538** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/538?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#537** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/537?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#508** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/508?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#509](https://github.com/starkware-libs/sequencer/pull/509) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/509?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#507** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/507?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#506** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/506?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#505** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/505?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#504** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/504?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#503** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/503?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nimrod-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/547)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @ShahakShama)

___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/547#-O4owy1NE_UiA5JMph2K:-O4owy1NE_UiA5JMph2L:b-ecjchu) ([raw file](https://github.com/starkware-libs/sequencer/blob/85cf607600bd58dd94f9f32d183d58a2753d6c81/crates/papyrus_storage/src/serialization/serializers.rs#L369)):*
> ```XML
>         pub max_amount: u64,
>         pub max_price_per_unit: u128,
>     }
> ```

@ShahakShama ?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/547)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @ShahakShama)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/547)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @ShahakShama)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/547)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware and @ShahakShama)

___
*[`crates/starknet_api/Cargo.toml` line 35 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/547#-O5gplQxEeUB_GuIJynd:-O5gplQxEeUB_GuIJyne:b-iwjomh) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ca0d84ccc4dfc77e32e46eeaba7b72bb37898c5/crates/starknet_api/Cargo.toml#L35)):*
> ```TOML
> 
> [package.metadata.cargo-machete]
> ignored = ["strum"]
> ```

why do you need to ignore?
which code uses it?
if it's only test code please make the below change... if it still doesn't work, re-add the `ignored`



_Suggestion:_
```TOML
strum = { workspace = true, optional = true }
strum_macros.workspace = true
thiserror.workspace = true

[dev-dependencies]
assert_matches.workspace = true
rstest.workspace = true
strum.workspace = true
```
___
*[`crates/starknet_api/Cargo.toml` line 35 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/547#-O5gq2k_9pYk9upIE-Nf:-O5gq2k_9pYk9upIE-Ng:b-epcwlz) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ca0d84ccc4dfc77e32e46eeaba7b72bb37898c5/crates/starknet_api/Cargo.toml#L35)):*
> ```TOML
> 
> [package.metadata.cargo-machete]
> ignored = ["strum"]
> ```

single newline please



_Suggestion:_
```TOML
rstest.workspace = true

[package.metadata.cargo-machete]
ignored = ["strum"]
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/547)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @ShahakShama)

___
*[`crates/starknet_api/Cargo.toml` line 35 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/547#-O5gq2k_9pYk9upIE-Nf:-O5hECFJ6ry7PMOXJtJ6:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ca0d84ccc4dfc77e32e46eeaba7b72bb37898c5/crates/starknet_api/Cargo.toml#L35)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

single newline please
</blockquote></details>

Done.
___
*[`crates/starknet_api/Cargo.toml` line 35 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/547#-O5gplQxEeUB_GuIJynd:-O5hEHDVDbv6Q7wMS1pf:b-oundwh) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ca0d84ccc4dfc77e32e46eeaba7b72bb37898c5/crates/starknet_api/Cargo.toml#L35)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do you need to ignore?
which code uses it?
if it's only test code please make the below change... if it still doesn't work, re-add the `ignored`
</blockquote></details>

If I remove `strum.workspace = true` it doesn't compile, i guess `strum_macros` depends on `strum` somehow.
It's also [mentioned](https://github.com/bnjbvr/cargo-machete?tab=readme-ov-file#false-positives) that it might have false positive alarms

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/547)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @ShahakShama)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/547)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @ShahakShama)

**Review by nimrod-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/547)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/547)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/547#-O4owy1NE_UiA5JMph2K:-O60r6mFBCHk8mO3EwRQ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b21d5049a8416b21b69c0a6495e8de500ea50494/crates/papyrus_storage/src/serialization/serializers.rs#L369)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@ShahakShama ?
</blockquote></details>

Done.

**Review by nimrod-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/547)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by nimrod-starkware — COMMENTED** [review]
> Dismissed @dorimedini-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/547)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
