### PR TITLE
chore(ci): workspace version alignment and tests

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/536)

### CODE REVIEW

**Review by nadin-Starkware — COMMENTED** [review]
> Reviewed 1 of 38 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/536)* status: 3 of 38 files reviewed, all discussions resolved (waiting on @dafnamatsry, @dan-starkware, @elintul, @Itay-Tsabary-Starkware, @liorgold2, @noaov1, and @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/536)* status: 5 of 38 files reviewed, all discussions resolved (waiting on @dafnamatsry, @dan-starkware, @elintul, @giladchase, @Itay-Tsabary-Starkware, @liorgold2, @nadin-Starkware, @noaov1, and @Yoni-Starkware)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/536)* status: 5 of 38 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry, @dan-starkware, @dorimedini-starkware, @elintul, @Itay-Tsabary-Starkware, @liorgold2, @nadin-Starkware, @noaov1, and @Yoni-Starkware)

___
*[`.github/workflows/main.yml` line 97 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/536#-O4ss6lbDSkQFsMsbtv8:-O4ss6lbDSkQFsMsbtv9:b-fxfdla) ([raw file](https://github.com/starkware-libs/sequencer/blob/54f88c750ee63935c1f77c46ec4d4bc8753a566f/.github/workflows/main.yml#L97)):*
> ```YAML
>     steps:
>       - uses: actions/checkout@v4
>       - uses: ./.github/actions/install_rust
> ```

Unrelated nonblocking: what does this trigger? we used to use dtolnay/rust-toolchain, why did switch?



_Code quote:_
```YAML
     - uses: ./.github/actions/install_rust
```
___
*[`workspace_tests/version_integrity_test.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/536#-O4su5q18_1J6zzsLh5u:-O4su5q18_1J6zzsLh5v:b-gd28ky) ([raw file](https://github.com/starkware-libs/sequencer/blob/54f88c750ee63935c1f77c46ec4d4bc8753a566f/workspace_tests/version_integrity_test.rs#L3)):*
> ```XML
> use std::collections::HashMap;
> 
> use once_cell::sync::Lazy;
> ```

U can use the recently added `std::sync::OnceLock` and save the extra dep, we already started using it for new lazy static in a bunch of crates.



_Code quote:_
```XML
use once_cell::sync::Lazy;
```
___
*[`workspace_tests/version_integrity_test.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/536#-O4t-CWe1nxPuuggVXvz:-O4t-CWe1nxPuuggVXw-:bpcj6y6) ([raw file](https://github.com/starkware-libs/sequencer/blob/54f88c750ee63935c1f77c46ec4d4bc8753a566f/workspace_tests/version_integrity_test.rs#L37)):*
> ```XML
> 
> static ROOT_TOML: Lazy<CargoToml> = Lazy::new(|| {
>     let root_toml: CargoToml = toml::from_str(include_str!("../Cargo.toml")).unwrap();
> ```

Do we want to use `env::var("CARGO_MANIFEST_DIR")` here instead of `..`?  That is, use absolute path instead of relative



_Code quote:_
```XML
    let root_toml: CargoToml = toml::from_str(include_str!("../Cargo.toml")).unwrap();
```
___
*[`workspace_tests/version_integrity_test.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/536#-O4swh0_2HPMKlWbyr8n:-O4swh0_2HPMKlWbyr8o:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/54f88c750ee63935c1f77c46ec4d4bc8753a566f/workspace_tests/version_integrity_test.rs#L42)):*
> ```XML
> 
> impl<'a> CargoToml {
>     fn local_crates(&'a self) -> impl Iterator<Item = LocalCrate> + 'a {
> ```





_Suggestion:_
```XML
impl CargoToml {
    fn local_crates(&self) -> impl Iterator<Item = LocalCrate> + '_ {
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/536)* status: 5 of 38 files reviewed, all discussions resolved (waiting on @dafnamatsry, @dan-starkware, @elintul, @Itay-Tsabary-Starkware, @liorgold2, @nadin-Starkware, @noaov1, and @Yoni-Starkware)

___
*[`.github/workflows/main.yml` line 97 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/536#-O4ss6lbDSkQFsMsbtv8:-O4t2sq30ol8w1-XAAjO:bml7m8s) ([raw file](https://github.com/starkware-libs/sequencer/blob/54f88c750ee63935c1f77c46ec4d4bc8753a566f/.github/workflows/main.yml#L97)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Unrelated nonblocking: what does this trigger? we used to use dtolnay/rust-toolchain, why did switch?
</blockquote></details>

so we can globally control the rust toolchain we use in the CI; going forward we will probably want to stop using `stable` on release branches, and fix a version (so the occasional bugfix PR won't have to include clippy fixes due to stable rust upgrade)
___
*[`workspace_tests/version_integrity_test.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/536#-O4su5q18_1J6zzsLh5u:-O4t1XF992u34Ql6KDyO:bfn4tp6) ([raw file](https://github.com/starkware-libs/sequencer/blob/54f88c750ee63935c1f77c46ec4d4bc8753a566f/workspace_tests/version_integrity_test.rs#L3)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

U can use the recently added `std::sync::OnceLock` and save the extra dep, we already started using it for new lazy static in a bunch of crates.
</blockquote></details>

with OnceLock don't I have to set the value in each test?
___
*[`workspace_tests/version_integrity_test.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/536#-O4t-CWe1nxPuuggVXvz:-O4t2ZQcBGMuhLa0U2-w:bgey61c) ([raw file](https://github.com/starkware-libs/sequencer/blob/54f88c750ee63935c1f77c46ec4d4bc8753a566f/workspace_tests/version_integrity_test.rs#L37)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Do we want to use `env::var("CARGO_MANIFEST_DIR")` here instead of `..`?  That is, use absolute path instead of relative
</blockquote></details>

Done, though we still need `../Cargo.toml` (`CARGO_MANIFEST_DIR` is `~/workspace/sequencer/workspace_tests`)
___
*[`workspace_tests/version_integrity_test.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/536#-O4swh0_2HPMKlWbyr8n:-O4t2ncfCtdeei8TnmBI:bcpdlaa) ([raw file](https://github.com/starkware-libs/sequencer/blob/54f88c750ee63935c1f77c46ec4d4bc8753a566f/workspace_tests/version_integrity_test.rs#L42)):*
> ```XML
> 
> impl<'a> CargoToml {
>     fn local_crates(&'a self) -> impl Iterator<Item = LocalCrate> + 'a {
> ```

thanks!!
can you explain why this is needed at all?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/536)* status: 5 of 38 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, @dorimedini-starkware, @elintul, @Itay-Tsabary-Starkware, @liorgold2, @nadin-Starkware, @noaov1, and @Yoni-Starkware)

___
*[`workspace_tests/version_integrity_test.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/536#-O4t1eOy7LAT_C6VCDjl:-O4t1eOy7LAT_C6VCDjm:b-6350pk) ([raw file](https://github.com/starkware-libs/sequencer/blob/54f88c750ee63935c1f77c46ec4d4bc8753a566f/workspace_tests/version_integrity_test.rs#L42)):*
> ```XML
> 
> impl<'a> CargoToml {
>     fn local_crates(&'a self) -> impl Iterator<Item = LocalCrate> + 'a {
> ```

Rationale: I found myself a bit confused by `local_crates()` at first glance. 
This makes it clearer that we're picking out dependencies with a `path`, which I missed when going over it.

Maybe workspace_crates() also works, but that could be assuming too much about those deps at this point, considering that you're testing that specifically in this module.



_Suggestion:_
```XML
    fn path_dependencies(&'a self) -> impl Iterator<Item = LocalCrate> + 'a {
```
___
*[`workspace_tests/version_integrity_test.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/536#-O4t09yvDzazxgVmGYp6:-O4t09yvDzazxgVmGYp7:b-id1opn) ([raw file](https://github.com/starkware-libs/sequencer/blob/54f88c750ee63935c1f77c46ec4d4bc8753a566f/workspace_tests/version_integrity_test.rs#L71)):*
> ```XML
>         );
>     }
> }
> ```

Making sure i understand: this goes over all dependencies that have a `path` attributes and ensures they are in fact crates included in the workspace?
So in essence, we're checking that none of our crates what removed from the workspace by mistake? 
(Or maybe also to guard against ppl pushing temporary locally patched external deps?)

If that is the case, maybe we should change `_local_dependencies_` to something like `_local_path_dependencies_` to make it clear, initially I thought it was a mistake because I thought it was checking that all deps are members, which is of course not the intention.



_Code quote:_
```XML
fn test_local_dependencies_are_members() {
    for LocalCrate { path, name, .. } in ROOT_TOML.local_crates() {
        assert!(
            ROOT_TOML.workspace.members.contains(&path),
            "Crate '{name}' at path '{path}' is not a member of the workspace."
        );
    }
}
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/536)* status: 5 of 38 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, @dorimedini-starkware, @elintul, @Itay-Tsabary-Starkware, @liorgold2, @nadin-Starkware, @noaov1, and @Yoni-Starkware)

___
*[`workspace_tests/version_integrity_test.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/536#-O4t-CWe1nxPuuggVXvz:-O4t7Fz-5Dex37mAo4ci:b-51mjpz) ([raw file](https://github.com/starkware-libs/sequencer/blob/54f88c750ee63935c1f77c46ec4d4bc8753a566f/workspace_tests/version_integrity_test.rs#L37)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done, though we still need `../Cargo.toml` (`CARGO_MANIFEST_DIR` is `~/workspace/sequencer/workspace_tests`)
</blockquote></details>

Rightt, shame there isn't a CARGO_WORKSPACE_DIR
___
*[`workspace_tests/version_integrity_test.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/536#-O4swh0_2HPMKlWbyr8n:-O4t7OA99P_kgPLma1Zz:b-f2ovdm) ([raw file](https://github.com/starkware-libs/sequencer/blob/54f88c750ee63935c1f77c46ec4d4bc8753a566f/workspace_tests/version_integrity_test.rs#L42)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

thanks!!
can you explain why this is needed at all?
</blockquote></details>

 No logical reason, just complicated lifetime ellision [that isn't stable yet](https://rust-lang.github.io/rfcs/3498-lifetime-capture-rules-2024.html).

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/536)* status: 5 of 38 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, @elintul, @giladchase, @Itay-Tsabary-Starkware, @liorgold2, @nadin-Starkware, @noaov1, and @Yoni-Starkware)

___
*[`workspace_tests/version_integrity_test.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/536#-O4t09yvDzazxgVmGYp6:-O4teGnZ6K90saDM2Zb7:b-rrdmma) ([raw file](https://github.com/starkware-libs/sequencer/blob/54f88c750ee63935c1f77c46ec4d4bc8753a566f/workspace_tests/version_integrity_test.rs#L71)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Making sure i understand: this goes over all dependencies that have a `path` attributes and ensures they are in fact crates included in the workspace?
So in essence, we're checking that none of our crates what removed from the workspace by mistake? 
(Or maybe also to guard against ppl pushing temporary locally patched external deps?)

If that is the case, maybe we should change `_local_dependencies_` to something like `_local_path_dependencies_` to make it clear, initially I thought it was a mistake because I thought it was checking that all deps are members, which is of course not the intention.
</blockquote></details>

this test checks that all path-deps are members; should we rename this test?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/536)* status: 5 of 38 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, @dorimedini-starkware, @elintul, @Itay-Tsabary-Starkware, @liorgold2, @nadin-Starkware, @noaov1, and @Yoni-Starkware)

___
*[`workspace_tests/version_integrity_test.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/536#-O4su5q18_1J6zzsLh5u:-O4uSluh157v35Dcnrv6:b-cv5xlx) ([raw file](https://github.com/starkware-libs/sequencer/blob/54f88c750ee63935c1f77c46ec4d4bc8753a566f/workspace_tests/version_integrity_test.rs#L3)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

with OnceLock don't I have to set the value in each test?
</blockquote></details>

ya :sweat_smile: buuut looks like LazyLock was merged last month into `stable`, so you can just replace Lazy with `std::sync::LazyLock` without any further changes :grimacing:
___
*[`workspace_tests/version_integrity_test.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/536#-O4t09yvDzazxgVmGYp6:-O4uOZi2-EQK0j8jjZKw:b-z18d8i) ([raw file](https://github.com/starkware-libs/sequencer/blob/54f88c750ee63935c1f77c46ec4d4bc8753a566f/workspace_tests/version_integrity_test.rs#L71)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this test checks that all path-deps are members; should we rename this test?
</blockquote></details>

I think so ya, if you want

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/536)* status: 4 of 40 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry, @dan-starkware, @dorimedini-starkware, @elintul, @Itay-Tsabary-Starkware, @liorgold2, @nadin-Starkware, @noaov1, and @Yoni-Starkware)

___
*[`workspace_tests/version_integrity_test.rs` line 62 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/536#-O579Bea-H6TNWKinfsX:-O579Bea-H6TNWKinfsY:broehxi) ([raw file](https://github.com/starkware-libs/sequencer/blob/07cb498029eaf4a992cce7fc249b69313eb5c525/workspace_tests/version_integrity_test.rs#L62)):*
> ```XML
> 
> #[test]
> fn test_path_dependencies_are_members() {
> ```

According to [this](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-members-and-exclude-fields), path dependencies are automatically members: 
```rust
All path dependencies residing in the workspace directory automatically become members. Additional members can be listed with the members key, which should be an array of strings containing directories with Cargo.toml files.
```

Does that mean that this test cannot fail?

(That's not to say that I like this workspace behavior from cargo, but I just wanna be sure the test isn't a tautology.)



_Code quote:_
```XML
fn test_path_dependencies_are_members() {
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/536)* status: 4 of 40 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry, @dan-starkware, @elintul, @giladchase, @Itay-Tsabary-Starkware, @liorgold2, @nadin-Starkware, @noaov1, and @Yoni-Starkware)

___
*[`workspace_tests/version_integrity_test.rs` line 62 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/536#-O579Bea-H6TNWKinfsX:-O57SZ34D0mi66Jx_tRo:b8o4jc3) ([raw file](https://github.com/starkware-libs/sequencer/blob/07cb498029eaf4a992cce7fc249b69313eb5c525/workspace_tests/version_integrity_test.rs#L62)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

According to [this](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-members-and-exclude-fields), path dependencies are automatically members: 
```rust
All path dependencies residing in the workspace directory automatically become members. Additional members can be listed with the members key, which should be an array of strings containing directories with Cargo.toml files.
```

Does that mean that this test cannot fail?

(That's not to say that I like this workspace behavior from cargo, but I just wanna be sure the test isn't a tautology.)
</blockquote></details>

this tests that the membership is *explicit*, which is worth it IMO

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 34 of 38 files at r1, 6 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/536#-:-O5CJwKsETkCgGVQoNEH:bnfp4nl)* status: 36 of 40 files reviewed, all discussions resolved (waiting on @dafnamatsry, @dan-starkware, @elintul, @Itay-Tsabary-Starkware, @liorgold2, @noaov1, and @Yoni-Starkware)

___
*[`workspace_tests/version_integrity_test.rs` line 62 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/536#-O579Bea-H6TNWKinfsX:-O5CJZ2QCqXmzb-7Z2VA:biro350) ([raw file](https://github.com/starkware-libs/sequencer/blob/07cb498029eaf4a992cce7fc249b69313eb5c525/workspace_tests/version_integrity_test.rs#L62)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this tests that the membership is *explicit*, which is worth it IMO
</blockquote></details>

Got it, as long as the link above doesn't imply that this test can never fail (that is that path deps are dynamically added to `ROOT_TOML.workspace.members` which sounds like an unreasonable thing to do) it's a great test.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/536)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry, @dan-starkware, @elintul, @Itay-Tsabary-Starkware, @liorgold2, @noaov1, and @Yoni-Starkware)

**Pull request merged**
