### PR TITLE
refactor(mempool): split mempool_p2p crate to types and business logic crates

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/820)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
+reviewer:@Itay-Tsabary-Starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/820#-:-O6vItP6CNEtFXSukp5V:b9trd3c)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/820)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`Cargo.toml` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/820#-O6zKPs163hJ35tgdiiW:-O6zKPs163hJ35tgdiiX:braq2y9) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d965e2cfe90490876181eab88fcc6adbdd59bd6/Cargo.toml#L20)):*
> ```TOML
>   "crates/mempool_node",
>   "crates/mempool_p2p",
>   "crates/mempool_p2p_sender_types",
> ```

The convention we use is to have `X_types` for the `X`component.
Is the component called `mempool_p2p` or `mempool_p2p_sender_types` ?



_Code quote:_
```TOML
  "crates/mempool_p2p",
  "crates/mempool_p2p_sender_types",
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/820)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`Cargo.toml` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/820#-O6zKPs163hJ35tgdiiW:-O7-4xmV7XNGhbeXs3QK:bxv8f23) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d965e2cfe90490876181eab88fcc6adbdd59bd6/Cargo.toml#L20)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

The convention we use is to have `X_types` for the `X`component.
Is the component called `mempool_p2p` or `mempool_p2p_sender_types` ?
</blockquote></details>

Discussed in slack

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/820#-:-O7-55-iCjoUpn_vCzYM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
