### PR TITLE
refactor(ci): commitlint scope is mandatory

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/371)

### CODE REVIEW

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/371)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`commitlint.config.js` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/371#-O3mBuwc4IR-WlDgxjXU:-O3mBuwc4IR-WlDgxjXV:bohm2vg) ([raw file](https://github.com/starkware-libs/sequencer/blob/a01e41884fb43bc3c4a80986d8289c2776604dd2/commitlint.config.js#L53)):*
> ```JavaScript
>             'tests-integration',
>             'transaction',
>             'types',
> ```

The list seems quite big for me... 
Maybe it would be better if the scopes would be the previous repositories. (blockifier, committer, mempool ....) and only them.
ATM there are specific features of those repositories for example `skeleton` was under context of the committer



_Code quote:_
```JavaScript
            'base_layer',
            'block_builder',
            'block_hash',
            'blockifier',
            'ci',
            'common',
            'concurrency',
            'config',
            'consensus',
            'execution',
            'fee',
            'gateway',
            'helm',
            'JSON-RPC',
            'load_test',
            'mempool_node',
            'mempool',
            'monitoring',
            'native_blockifier',
            'network',
            'node',
            'protobuf',
            'release',
            'skeleton',
            'starknet_client',
            'state',
            'storage',
            'sync',
            'test_utils',
            'tests-integration',
            'transaction',
            'types',
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/371)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`commitlint.config.js` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/371#-O3mCilN6xi3jm4yYTzW:-O3mCilN6xi3jm4yYTzX:baak67f) ([raw file](https://github.com/starkware-libs/sequencer/blob/a01e41884fb43bc3c4a80986d8289c2776604dd2/commitlint.config.js#L55)):*
> ```JavaScript
>             'types',
>         ]],
>         'scope-empty': [2, 'never']
> ```

This line enforces that scope cannot be empty. (i.e `test: some test` is no longer valid - you need to name at least one scope)



_Code quote:_
```JavaScript
'scope-empty': [2, 'never']
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/371)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

___
*[`commitlint.config.js` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/371#-O3mCilN6xi3jm4yYTzW:-O3mCynKBVP_PEUppqNy:b-yeyud5) ([raw file](https://github.com/starkware-libs/sequencer/blob/a01e41884fb43bc3c4a80986d8289c2776604dd2/commitlint.config.js#L55)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

This line enforces that scope cannot be empty. (i.e `test: some test` is no longer valid - you need to name at least one scope)
</blockquote></details>

is it possible to get more fine-grained enforcement?
we want:
1. at least one of (blockifier, papyrus, mempool, infra, committer), or some specific list
2. possibly more scopes from the long list (useful to be specific, even within a project)

Reasoning:
say we want to generate release notes for a new blockifier version.
We want to first filter by all commits with scopes containing `blockifier`,
and then we can further sort the features/fixes/whatever by "sub scope" (execution, storage, transaction etc.)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/371)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

___
*[`commitlint.config.js` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/371#-O3mBuwc4IR-WlDgxjXU:-O3mEMNo3mKOThNTwIpZ:b-uv18j8) ([raw file](https://github.com/starkware-libs/sequencer/blob/a01e41884fb43bc3c4a80986d8289c2776604dd2/commitlint.config.js#L53)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

The list seems quite big for me... 
Maybe it would be better if the scopes would be the previous repositories. (blockifier, committer, mempool ....) and only them.
ATM there are specific features of those repositories for example `skeleton` was under context of the committer
</blockquote></details>

see below, we want to be able to specify "internal scope" (scope in the project).
maybe prepend `blockifier_` or `papyrus_` etc. to all scopes...? seems cumbersome

**Pull request closed without merging**
