### PR TITLE
chore: add missing deploy_tx to get_sender_address and make run_valid…

### PR DESCRIPTION
**Pull request by Yael-Starkware**
…ate return the mempool_input

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/151)

### CODE REVIEW

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/151)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @dorimedini-starkware)

___
*[`crates/gateway/src/gateway.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/151#-O2t8Of76z9LE9ZvuxXy:-O2t8Of76z9LE9ZvuxXz:b-tktqnc) ([raw file](https://github.com/starkware-libs/sequencer/blob/e5c95538da71484a326d56e02ac8b8d0b25cdee4/crates/gateway/src/gateway.rs#L137)):*
> ```XML
>     let validator = stateful_tx_validator.instantiate_validator(state_reader_factory)?;
>     let mempool_input = stateful_tx_validator.run_validate(&tx, optional_class_info, validator)?;
> ```

link to the discussion in the original PR : https://reviewable.io/reviews/starkware-libs/mempool/527#-O2Zpwku4sEx0ZJtUg3q
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/151#-O2t8W3O95FGe3F_zTC7:-O2t8W3O95FGe3F_zTC8:bhimvxr) ([raw file](https://github.com/starkware-libs/sequencer/blob/e5c95538da71484a326d56e02ac8b8d0b25cdee4/crates/gateway/src/stateful_transaction_validator.rs#L78)):*
> ```XML
>             account: Account { sender_address, state: AccountState { nonce: account_nonce } },
>         })
>     }
> ```

link to the discussion in the original PR:
https://reviewable.io/reviews/starkware-libs/mempool/527#-O2ZpYe04-RVBV7_4A39

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/151#-:-O3BhgO5Ct2OEuX2qlOg:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/stateful_transaction_validator.rs` line 141 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/151#-O3DIeuTDNVo5fje__-r:-O3DIeuTDNVo5fje__-s:b-f88pv9) ([raw file](https://github.com/starkware-libs/sequencer/blob/baa884a24aa8b548af93a8f9f2eec86749d1e202/crates/gateway/src/stateful_transaction_validator.rs#L141)):*
> ```XML
>     pub sender_address: ContractAddress,
>     pub account_nonce: Nonce,
> }
> ```

Add a Doc string about this struct. Write a todo about deleting it once internal transactions are in use.
(Docstring by ChatGPT).



_Suggestion:_
```XML
/// Holds members created by the stateful transaction validator, needed for
/// [`MempoolInput`](starknet_mempool_types::mempool_types::MempoolInput).
#[derive(Debug)]
pub struct ValidateInfo {
    pub tx_hash: TransactionHash,
    pub sender_address: ContractAddress,
    pub account_nonce: Nonce,
}
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/151)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 101 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/151#-O3DUnCB9bP8rsLu-zx8:-O3DUnCB9bP8rsLu-zx9:b6pm621) ([raw file](https://github.com/starkware-libs/sequencer/blob/baa884a24aa8b548af93a8f9f2eec86749d1e202/crates/gateway/src/stateful_transaction_validator_test.rs#L101)):*
> ```XML
>         Ok(expected_result) => assert_eq!(result.unwrap().tx_hash, expected_result),
>         Err(_) => assert_eq!(format!("{:?}", result), format!("{:?}", expected_result)),
>     }
> ```

Should these simply be two tests?

I am not sure.



_Code quote:_
```XML
    match expected_result {
        Ok(expected_result) => assert_eq!(result.unwrap().tx_hash, expected_result),
        Err(_) => assert_eq!(format!("{:?}", result), format!("{:?}", expected_result)),
    }
```
___
*[`crates/starknet_api/src/rpc_transaction.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/151#-O3DTcFR20d8kI89HY5v:-O3DTcFR20d8kI89HY5w:bq7qkuz) ([raw file](https://github.com/starkware-libs/sequencer/blob/baa884a24aa8b548af93a8f9f2eec86749d1e202/crates/starknet_api/src/rpc_transaction.rs#L84)):*
> ```XML
>             RpcTransaction::Invoke(RpcInvokeTransaction::V3(tx)) => tx.sender_address,
>         }
>     }
> ```

This change deserves its own PR. (I love this change).
This change = creating this function and using it when possible.



_Code quote:_
```XML
    pub fn calculate_sender_address(&self) -> ContractAddress {
        match self {
            RpcTransaction::Declare(RpcDeclareTransaction::V3(tx)) => tx.sender_address,
            RpcTransaction::DeployAccount(RpcDeployAccountTransaction::V3(tx)) => {
                calculate_contract_address(
                    tx.contract_address_salt,
                    tx.class_hash,
                    &tx.constructor_calldata,
                    ContractAddress::default(),
                )
                .unwrap()
            }
            RpcTransaction::Invoke(RpcInvokeTransaction::V3(tx)) => tx.sender_address,
        }
    }
```

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/151#-:-O3SJyzy9ArfUVIHC4gY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 141 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/151#-O3DIeuTDNVo5fje__-r:-O3Rv5XD9XTNaPLy5O5v:b-n9dt4d) ([raw file](https://github.com/starkware-libs/sequencer/blob/baa884a24aa8b548af93a8f9f2eec86749d1e202/crates/gateway/src/stateful_transaction_validator.rs#L141)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

done
</blockquote></details>

The todo is on the file `crates/gateway/src/gateway.rs` :)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/151)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/151#-:-O3WRf5TEZkH_YUnscCo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
