### PR TITLE
test(blockifier): update test_insufficient_max_fee_reverts to include new resource bounds

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1313)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1313?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1314** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1314?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1313** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1313?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1312** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1312?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1311** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1311?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1310** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1310?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1309** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1309?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1308** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1308?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1307** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1307?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1306** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1306?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yoavGrs — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1313)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1167 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1313#-OAIIMo47b9lDgG_nea3:-OAIIMo47b9lDgG_nea4:b394hux) ([raw file](https://github.com/starkware-libs/sequencer/blob/a09dcf20ae0ad0ca767b8306fa20b3913e1b5ec9/crates/blockifier/src/transaction/account_transactions_test.rs#L1167)):*
> ```XML
> ) {
>     let gas_mode = resource_bounds.get_gas_vector_computation_mode();
>     let overdraft_resource = match gas_mode {
> ```

Move it next to its use.
It's the overdraft resource only for the second tx.



_Code quote:_
```XML
let overdraft_resource
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1206 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1313#-OAIH2dP9RdCar4nT4Tc:-OAIH2dP9RdCar4nT4Td:b-wsvivy) ([raw file](https://github.com/starkware-libs/sequencer/blob/a09dcf20ae0ad0ca767b8306fa20b3913e1b5ec9/crates/blockifier/src/transaction/account_transactions_test.rs#L1206)):*
> ```XML
>                 }
>                 GasVectorComputationMode::All => {
>                     // We do not expect the exact same fee in the All case.
> ```

Despite the expectation, in practice, we do get equality. Why?



_Code quote:_
```XML
 We do not expect the exact same fee in the All case.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1227 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1313#-OAI6ywO3cwhz0tJ7ANC:-OAI6ywO3cwhz0tJ7AND:b-29e6i9) ([raw file](https://github.com/starkware-libs/sequencer/blob/a09dcf20ae0ad0ca767b8306fa20b3913e1b5ec9/crates/blockifier/src/transaction/account_transactions_test.rs#L1227)):*
> ```XML
>     // This call should fail due to insufficient max fee (steps bound based on max_fee is not so
>     // tight as to stop execution between iterations 1 and 2).
>     let resource_bounds_depth1 = match gas_mode {
> ```

It's not the bounds in `tx_execution_info1`



_Suggestion:_
```XML
resource_used_depth1
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1248 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1313#-OAI7tFM3zUNCwSrYWuW:-OAI7tFM3zUNCwSrYWuX:b1fuoig) ([raw file](https://github.com/starkware-libs/sequencer/blob/a09dcf20ae0ad0ca767b8306fa20b3913e1b5ec9/crates/blockifier/src/transaction/account_transactions_test.rs#L1248)):*
> ```XML
>     )
>     .unwrap();
>     // In the deprecated bounds case, due to resource limit being estimated by steps, the execution
> ```

Is that the case?



_Suggestion:_
```XML
In the l1 gas bounds case
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1267 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1313#-OAIBTtu4tPDed_OCc1t:-OAIBTtu4tPDed_OCc1u:bfacunj) ([raw file](https://github.com/starkware-libs/sequencer/blob/a09dcf20ae0ad0ca767b8306fa20b3913e1b5ec9/crates/blockifier/src/transaction/account_transactions_test.rs#L1267)):*
> ```XML
>             resource_bounds: resource_bounds_depth1,
>             nonce: nonce_manager.next(account_address),
>             calldata: recursive_function_calldata(&contract_address, 824, false),
> ```

Is it tight?
Is it going to change frequently?



_Code quote:_
```XML
824
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1273 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1313#-OAICocP7wJS5MADLBsM:-OAICocP7wJS5MADLBsN:brcy6jg) ([raw file](https://github.com/starkware-libs/sequencer/blob/a09dcf20ae0ad0ca767b8306fa20b3913e1b5ec9/crates/blockifier/src/transaction/account_transactions_test.rs#L1273)):*
> ```XML
>     .unwrap();
>     // In the deprecated bounds case, the entire step limit is derived from 100% of all the
>     // bounds (only L1 gas), so expected revert fee is identical to the original fee.
> ```

This comment should appear above the `NoL2Gas` case in the macro.



_Code quote:_
```XML
    // In the deprecated bounds case, the entire step limit is derived from 100% of all the
    // bounds (only L1 gas), so expected revert fee is identical to the original fee.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1313)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1167 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1313#-OAIIMo47b9lDgG_nea3:-OAI_LBCCPY51Bb3i9ms:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a09dcf20ae0ad0ca767b8306fa20b3913e1b5ec9/crates/blockifier/src/transaction/account_transactions_test.rs#L1167)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Move it next to its use.
It's the overdraft resource only for the second tx.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1206 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1313#-OAIH2dP9RdCar4nT4Tc:-OAI_SFK0jT4MjU_22R7:bz2a804) ([raw file](https://github.com/starkware-libs/sequencer/blob/a09dcf20ae0ad0ca767b8306fa20b3913e1b5ec9/crates/blockifier/src/transaction/account_transactions_test.rs#L1206)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Despite the expectation, in practice, we do get equality. Why?
</blockquote></details>

WDYM in practice we get the same? equality isn't asserted here
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1227 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1313#-OAI6ywO3cwhz0tJ7ANC:-OAI_ann8BTn-Vy5YFKe:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a09dcf20ae0ad0ca767b8306fa20b3913e1b5ec9/crates/blockifier/src/transaction/account_transactions_test.rs#L1227)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

It's not the bounds in `tx_execution_info1`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1248 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1313#-OAI7tFM3zUNCwSrYWuW:-OAI_fK09FS-CllPRW7D:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a09dcf20ae0ad0ca767b8306fa20b3913e1b5ec9/crates/blockifier/src/transaction/account_transactions_test.rs#L1248)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Is that the case?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1267 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1313#-OAIBTtu4tPDed_OCc1t:-OAI_j8V1pBPAFWTrjOd:b-o19cfu) ([raw file](https://github.com/starkware-libs/sequencer/blob/a09dcf20ae0ad0ca767b8306fa20b3913e1b5ec9/crates/blockifier/src/transaction/account_transactions_test.rs#L1267)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Is it tight?
Is it going to change frequently?
</blockquote></details>

this test is old, and it didn't change now, so I guess it's not very sensitive
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1273 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1313#-OAICocP7wJS5MADLBsM:-OAIa24-7FYL_d6TcFQl:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a09dcf20ae0ad0ca767b8306fa20b3913e1b5ec9/crates/blockifier/src/transaction/account_transactions_test.rs#L1273)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

This comment should appear above the `NoL2Gas` case in the macro.
</blockquote></details>

Done.

**Review by yoavGrs — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1313)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1206 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1313#-OAIH2dP9RdCar4nT4Tc:-OAMfwtgABPpAZ1Fwp-n:b-lvb5yt) ([raw file](https://github.com/starkware-libs/sequencer/blob/a09dcf20ae0ad0ca767b8306fa20b3913e1b5ec9/crates/blockifier/src/transaction/account_transactions_test.rs#L1206)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYM in practice we get the same? equality isn't asserted here
</blockquote></details>

In the code, you don't assert inequality.
But the explanations point out that `execution_info.receipt.gas.l2_gas < tx_execution_info1.receipt.gas.l2_gas`, but it's not the case: when I ran the test I got equality.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1313)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1206 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1313#-OAIH2dP9RdCar4nT4Tc:-OANtaw36RCievogGY0X:bcrlxq6) ([raw file](https://github.com/starkware-libs/sequencer/blob/a09dcf20ae0ad0ca767b8306fa20b3913e1b5ec9/crates/blockifier/src/transaction/account_transactions_test.rs#L1206)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

In the code, you don't assert inequality.
But the explanations point out that `execution_info.receipt.gas.l2_gas < tx_execution_info1.receipt.gas.l2_gas`, but it's not the case: when I ran the test I got equality.
</blockquote></details>

Done. You're right, the final fee should be the same (snap to bounds). The final gas vector however need not be the same on revert, so I simplified this a bit (no need for the macro anymore)

**Review by yoavGrs — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1313)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1313)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
