### PR TITLE
refactor(blockifier): rename contract class to runnable contract class

### PR DESCRIPTION
**Pull request by noaov1**

### CODE REVIEW

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1728#-:-OAlIwKE5NpSd1NtaAFP:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1728#-OAlIAOZ8DH0SP41nYx3:-OAlIAOZ8DH0SP41nYx4:bmnnqvx) ([raw file](https://github.com/starkware-libs/sequencer/blob/6797cae0aa1c2e46fea7b4430025239228860b61/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L9)):*
> ```XML
> use blockifier::bouncer::BouncerConfig;
> use blockifier::context::BlockContext;
> use blockifier::execution::contract_class::RunnableContractClass as BlockifierContractClass;
> ```

Can be simplified.
Non-blocking.



_Suggestion:_
```XML
use blockifier::execution::contract_class::RunnableContractClass;
```
___
*[`crates/papyrus_execution/src/execution_utils.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1728#-OAlIUj7DNAt6BRCyvjR:-OAlIUj7DNAt6BRCyvjS:bmnnqvx) ([raw file](https://github.com/starkware-libs/sequencer/blob/6797cae0aa1c2e46fea7b4430025239228860b61/crates/papyrus_execution/src/execution_utils.rs#L10)):*
> ```XML
>     ContractClassV0,
>     ContractClassV1,
>     RunnableContractClass as BlockifierContractClass,
> ```

Can be simplified.
Non-blocking.



_Code quote:_
```XML
    RunnableContractClass as BlockifierContractClass,
```
___
*[`crates/papyrus_execution/src/lib.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1728#-OAlIbYxCigyCN7GanrP:-OAlIbYxCigyCN7GanrQ:bmnnqvx) ([raw file](https://github.com/starkware-libs/sequencer/blob/6797cae0aa1c2e46fea7b4430025239228860b61/crates/papyrus_execution/src/lib.rs#L33)):*
> ```XML
>     ClassInfo,
>     RunnableContractClass as BlockifierContractClass,
> };
> ```

Can be simplified.
Non-blocking.



_Suggestion:_
```XML
use blockifier::execution::contract_class::{
    ClassInfo,
    RunnableContractClass,
};
```
___
*[`crates/papyrus_execution/src/state_reader.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1728#-OAlIeio817QOfji4OHa:-OAlIeio817QOfji4OHb:bmnnqvx) ([raw file](https://github.com/starkware-libs/sequencer/blob/6797cae0aa1c2e46fea7b4430025239228860b61/crates/papyrus_execution/src/state_reader.rs#L11)):*
> ```XML
>     ContractClassV1,
>     RunnableContractClass as BlockifierContractClass,
> };
> ```

Can be simplified.
Non-blocking.



_Suggestion:_
```XML
use blockifier::execution::contract_class::{
    ContractClassV0,
    ContractClassV1,
    RunnableContractClass,
};
```
___
*[`crates/papyrus_execution/src/state_reader_test.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1728#-OAlIi3O4px3Gl4fbM90:-OAlIi3O4px3Gl4fbM91:bmnnqvx) ([raw file](https://github.com/starkware-libs/sequencer/blob/6797cae0aa1c2e46fea7b4430025239228860b61/crates/papyrus_execution/src/state_reader_test.rs#L8)):*
> ```XML
>     ContractClassV1,
>     RunnableContractClass as BlockifierContractClass,
> };
> ```

Can be simplified.
Non-blocking.



_Suggestion:_
```XML
use blockifier::execution::contract_class::{
    ContractClassV0,
    ContractClassV1,
    RunnableContractClass,
};
```

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1728)* status: all files reviewed, 7 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1728#-OAlMjUXDvj6q1MhUUdH:-OAlMjUXDvj6q1MhUUdI:bizhblt) ([raw file](https://github.com/starkware-libs/sequencer/blob/6797cae0aa1c2e46fea7b4430025239228860b61/crates/blockifier/src/execution/contract_class.rs#L86)):*
> ```XML
> 
>         Ok(contract_class)
>     }
> ```

while you're here



_Suggestion:_
```XML
    fn try_from(raw_contract_class: ContractClass) -> Result<Self, Self::Error> {
        let contract_class: Self = match raw_contract_class {
            ContractClass::V0(raw_contract_class) => {
                Self::V0(raw_contract_class.try_into()?)
            }
            ContractClass::V1(raw_contract_class) => {
                Self::V1(raw_contract_class.try_into()?)
            }
        };

        Ok(contract_class)
    }
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1728#-OAlMrl76atFovNVIEr4:-OAlMrl76atFovNVIEr5:b-7ropln) ([raw file](https://github.com/starkware-libs/sequencer/blob/6797cae0aa1c2e46fea7b4430025239228860b61/crates/blockifier/src/execution/contract_class.rs#L147)):*
> ```XML
>             RunnableContractClass::V1Native(_) => TrackedResource::SierraGas,
>         }
>     }
> ```

ditto



_Suggestion:_
```XML
    pub fn constructor_selector(&self) -> Option<EntryPointSelector> {
        match self {
            Self::V0(class) => class.constructor_selector(),
            Self::V1(class) => class.constructor_selector(),
            #[cfg(feature = "cairo_native")]
            Self::V1Native(class) => class.constructor_selector(),
        }
    }

    pub fn estimate_casm_hash_computation_resources(&self) -> ExecutionResources {
        match self {
            Self::V0(class) => class.estimate_casm_hash_computation_resources(),
            Self::V1(class) => class.estimate_casm_hash_computation_resources(),
            #[cfg(feature = "cairo_native")]
            Self::V1Native(_) => {
                todo!("Use casm to estimate casm hash computation resources")
            }
        }
    }

    pub fn get_visited_segments(
        &self,
        visited_pcs: &HashSet<usize>,
    ) -> Result<Vec<usize>, TransactionExecutionError> {
        match self {
            Self::V0(_) => {
                panic!("get_visited_segments is not supported for v0 contracts.")
            }
            Self::V1(class) => class.get_visited_segments(visited_pcs),
            #[cfg(feature = "cairo_native")]
            Self::V1Native(_) => {
                panic!("get_visited_segments is not supported for native contracts.")
            }
        }
    }

    pub fn bytecode_length(&self) -> usize {
        match self {
            Self::V0(class) => class.bytecode_length(),
            Self::V1(class) => class.bytecode_length(),
            #[cfg(feature = "cairo_native")]
            Self::V1Native(_) => {
                todo!("implement bytecode_length for native contracts.")
            }
        }
    }

    /// Returns whether this contract should run using Cairo steps or Sierra gas.
    pub fn tracked_resource(&self, min_sierra_version: &CompilerVersion) -> TrackedResource {
        match self {
            Self::V0(_) => TrackedResource::CairoSteps,
            Self::V1(contract_class) => {
                contract_class.tracked_resource(min_sierra_version)
            }
            #[cfg(feature = "cairo_native")]
            Self::V1Native(_) => TrackedResource::SierraGas,
        }
    }
```

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1728)* status: all files reviewed, 7 unresolved discussions (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1728#-:-OAlYCk527__8OYiexsp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1728)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1728)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
