### PR TITLE
chore(ci): remove unnecessary dep test-with

### PR DESCRIPTION
**Pull request by giladchase**

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1589)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1589#-OAMgi0x7IPvor5haio7:-OAMgi0x7IPvor5haio8:b-j9hgb9) (no related file):*
@giladchase please put someone from papyrus team on this

___

**Review by elintul — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1589)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase)

___
*[`.github/workflows/main.yml` line 95 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1589#-OAMr7mU1OBSQn-150H6:-OAMr7mV-6ndEWfiGOox:bl2co9g) ([raw file](https://github.com/starkware-libs/sequencer/blob/645dfee069a2c14f50c3436c9fe6b117436a55cf/.github/workflows/main.yml#L95)):*
> ```YAML
>           LD_LIBRARY_PATH: ${{ env.Python3_ROOT_DIR }}/bin
>         run: echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}" >> $GITHUB_ENV
>       - run: npm install -g ganache@7.4.3
> ```

Where was this done up until now?
This line: `#[test_with::executable(ganache)]`?



_Code quote:_
```YAML
- run: npm install -g ganache@7.4.3
```
___
*[`.github/workflows/main.yml` line 163 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1589#-OAMrPHTBuq9MfHkte9s:-OAMrPHTBuq9MfHkte9t:b-v95zlx) ([raw file](https://github.com/starkware-libs/sequencer/blob/645dfee069a2c14f50c3436c9fe6b117436a55cf/.github/workflows/main.yml#L163)):*
> ```YAML
>           echo "codecov_output=true" >> $GITHUB_OUTPUT
>         env:
>           CI: 1
> ```

Why only in "Run codecov on push" and "Run tests on push"?
Since these are only two that run on push event?



_Code quote:_
```YAML
CI: 1
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1589)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`.github/workflows/main.yml` line 163 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1589#-OAMrPHTBuq9MfHkte9s:-OAMz0-OCisX83kjJR5s:b7n2nxz) ([raw file](https://github.com/starkware-libs/sequencer/blob/645dfee069a2c14f50c3436c9fe6b117436a55cf/.github/workflows/main.yml#L163)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why only in "Run codecov on push" and "Run tests on push"?
Since these are only two that run on push event?
</blockquote></details>

Tried to put them in the minimal location where they were necessary, that is, the only places where I expect that ganache test to run .
But I can make that env variable global in the CI, maybe other places will also want to use it
WDYT?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1589)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @elintul)

___
*[`.github/workflows/main.yml` line 95 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1589#-OAMr7mU1OBSQn-150H6:-OAN2iHDCt823UlI2END:b-gzw59) ([raw file](https://github.com/starkware-libs/sequencer/blob/645dfee069a2c14f50c3436c9fe6b117436a55cf/.github/workflows/main.yml#L95)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Where was this done up until now?
This line: `#[test_with::executable(ganache)]`?
</blockquote></details>

In an incorrect spot, making this test not run.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1589)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @giladchase)

___
*[`.github/workflows/main.yml` line 163 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1589#-OAMrPHTBuq9MfHkte9s:-OANFkYz4Eu67Qt4w4ci:b-itvwxd) ([raw file](https://github.com/starkware-libs/sequencer/blob/645dfee069a2c14f50c3436c9fe6b117436a55cf/.github/workflows/main.yml#L163)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Tried to put them in the minimal location where they were necessary, that is, the only places where I expect that ganache test to run .
But I can make that env variable global in the CI, maybe other places will also want to use it
WDYT?
</blockquote></details>

Maybe it's better, but not in this PR if it's big.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1589#-:-OANXdVS9qIBvzSm-ctd:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1589)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @elintul)

___
*[`crates/papyrus_base_layer/src/base_layer_test.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1589#-OANaHOtBlRcPTCZuPik:-OANaHOtBlRcPTCZuPil:b-anus25) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2a15654908b4c38ebd30ece007d6976c0dbacb5/crates/papyrus_base_layer/src/base_layer_test.rs#L84)):*
> ```XML
> async fn latest_proved_block_ethereum() {
>     if !in_ci() {
>         panic!("TEST CI IS RUN")
> ```

blocked: checking that this actually runs in the CI.



_Code quote:_
```XML
    panic!("TEST CI IS RUN")
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1589)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1589)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1589)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
