### PR TITLE
fix(protobuf): allow using a local installation of Protoc instead of using protoc_prebuilt

### PR DESCRIPTION
**Pull request by AlonLStarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/884)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/884)* status: all files reviewed, 5 unresolved discussions (waiting on @AlonLStarkWare and @dan-starkware)

___
*[`crates/papyrus_protobuf/build.rs` line 7 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79E3Jy-sB3j9gLfX4q:-O79E3Jy-sB3j9gLfX4r:b-tucshk) ([raw file](https://github.com/starkware-libs/sequencer/blob/bdcfc393efd9c2ac7a069e009f78a920eb492721/crates/papyrus_protobuf/build.rs#L7)):*
> ```XML
> fn parse_protoc_version(protoc_version_str: &str) -> Result<Vec<u32>> {
>     Ok(protoc_version_str.split('.').map(|part| part.parse::<u32>().unwrap()).collect())
> }
> ```

1. you only need major and minor, right?
2. you `unwrap` so no need for a `Result` return type
3. If the minor version does not always exist you will need some extra logic here to return 0 as the minor version (and add it to the docstring)



_Suggestion:_
```XML
/// Returns (major, minor) numbers.
fn parse_protoc_version(protoc_version_str: &str) -> (u32, u32) {
    let version_numbers: Vec<u32> = protoc_version_str.split('.').map(|part| part.parse::<u32>().unwrap()).collect()
    (version_numbers[0], version_numbers[1])
}
```
___
*[`crates/papyrus_protobuf/build.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79EmW76rJXUgHHztDu:-O79EmW76rJXUgHHztDv:bb7phvt) ([raw file](https://github.com/starkware-libs/sequencer/blob/bdcfc393efd9c2ac7a069e009f78a920eb492721/crates/papyrus_protobuf/build.rs#L37)):*
> ```XML
> 
> fn main() -> Result<()> {
>     // If Protoc is installed use it, if not complie using prebuilt protoc.
> ```

typo



_Code quote:_
```XML
complie
```
___
*[`crates/papyrus_protobuf/build.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79Ek67ASrmi_LoWDQc:-O79Ek67ASrmi_LoWDQd:b354p86) ([raw file](https://github.com/starkware-libs/sequencer/blob/bdcfc393efd9c2ac7a069e009f78a920eb492721/crates/papyrus_protobuf/build.rs#L41)):*
> ```XML
>     if validate_preinstalled_protoc().is_err() {
>         println!("Building using prebuilt protoc");
>         let (protoc_bin, _) = protoc_prebuilt::init("27.0").expect(
> ```

what's this?



_Code quote:_
```XML
("27.0")
```
___
*[`docs/papyrus/README.adoc` line 50 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79Ey5M7NSIZNROEyIc:-O79Ey5M7NSIZNROEyId:b-496sog) ([raw file](https://github.com/starkware-libs/sequencer/blob/bdcfc393efd9c2ac7a069e009f78a920eb492721/docs/papyrus/README.adoc#L50)):*
> ```AsciiDoc
> * You must have access to an Ethereum node. For example, you can use a node provider such as Infura.
> * https://grpc.io/docs/protoc-installation[Protoc]
>   - You'll need Protoc only for compiling the link:../crates/papyrus_network/[papyrus_network] crate.
> ```

is this the syntax for path linking? what's the `link:` prefix?



_Code quote:_
```AsciiDoc
link:../crates/papyrus_network/[papyrus_network]
```
___
*[`docs/papyrus/README.adoc` line 73 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79F5lVCUaaxWQQhwQv:-O79F5lVCUaaxWQQhwQw:b9y55y) ([raw file](https://github.com/starkware-libs/sequencer/blob/bdcfc393efd9c2ac7a069e009f78a920eb492721/docs/papyrus/README.adoc#L73)):*
> ```AsciiDoc
> [source,bash]
> ----
> export PATH=$PATH:$DIR/bin
> ```

are these phases needed, even with the changes in build.rs?



_Code quote:_
```AsciiDoc
    2. Install version 15 or higher (replace DIR with your preferred installation directory):
+
[source,bash]
----
DIR="$HOME/.local"
curl -L "https://github.com/protocolbuffers/protobuf/releases/download/v25.1/protoc-25.1-linux-x86_64.zip" -o protoc.zip
unzip ./protoc.zip -d $DIR
rm ./protoc.zip
----

    3. Add DIR to your PATH if it's not already there:
+
[source,bash]
----
export PATH=$PATH:$DIR/bin
```

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/884)* status: all files reviewed, 4 unresolved discussions (waiting on @dan-starkware, @dorimedini-starkware, and @uriel-starkware)

___
*[`crates/papyrus_protobuf/build.rs` line 7 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79E3Jy-sB3j9gLfX4q:-O79KMXX7lzqrUmJ44Fu:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bdcfc393efd9c2ac7a069e009f78a920eb492721/crates/papyrus_protobuf/build.rs#L7)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. you only need major and minor, right?
2. you `unwrap` so no need for a `Result` return type
3. If the minor version does not always exist you will need some extra logic here to return 0 as the minor version (and add it to the docstring)
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/build.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79Ek67ASrmi_LoWDQc:-O79JhiC5vz0FXRYMEVV:bj2mpr0) ([raw file](https://github.com/starkware-libs/sequencer/blob/bdcfc393efd9c2ac7a069e009f78a920eb492721/crates/papyrus_protobuf/build.rs#L41)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what's this?
</blockquote></details>

The protobuf version used by protoc_prebuilt. This specific version was chosen by @uriel-starkware 
___
*[`docs/papyrus/README.adoc` line 50 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79Ey5M7NSIZNROEyIc:-O79JB5N-f8ZOn-YSAJj:b-oj1y1t) ([raw file](https://github.com/starkware-libs/sequencer/blob/bdcfc393efd9c2ac7a069e009f78a920eb492721/docs/papyrus/README.adoc#L50)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this the syntax for path linking? what's the `link:` prefix?
</blockquote></details>

It does not appear in the Readme when viewed on Github
___
*[`docs/papyrus/README.adoc` line 73 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79F5lVCUaaxWQQhwQv:-O79JQAK--61pGml3hh7:b-boiv9j) ([raw file](https://github.com/starkware-libs/sequencer/blob/bdcfc393efd9c2ac7a069e009f78a920eb492721/docs/papyrus/README.adoc#L73)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

are these phases needed, even with the changes in build.rs?
</blockquote></details>

They are required to use a preinstalled version of Protoc. However, this shouldn't appear in the Prerequisites as it is optional.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/884)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @dan-starkware)

___
*[`crates/papyrus_protobuf/build.rs` line 7 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79E3Jy-sB3j9gLfX4q:-O79L48ICtRIPc_xrg_Q:b7d5npl) ([raw file](https://github.com/starkware-libs/sequencer/blob/bdcfc393efd9c2ac7a069e009f78a920eb492721/crates/papyrus_protobuf/build.rs#L7)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

what about (3)?
previously you had `protoc_version_parts.next().unwrap_or(0);`, is it possible the protoc version is a single integer? in which case `version_numbers[1]` will panic?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/884)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @dan-starkware)

___
*[`crates/papyrus_protobuf/build.rs` line 5 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79P1kf4nG8Y2veBOm9:-O79P1kf4nG8Y2veBOmA:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6d036ab03bf4c6cda942b7fc9a8443f75eaabe9/crates/papyrus_protobuf/build.rs#L5)):*
> ```XML
> use std::process::Command;
> 
> fn parse_protoc_version(protoc_version_str: &str) -> (u32, u32) {
> ```





_Suggestion:_
```XML
/// Returns (major, minor) numbers. If the minor doesn't exist, returns 0 as minor.
fn parse_protoc_version(protoc_version_str: &str) -> (u32, u32) {
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/884)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare, @dan-starkware, and @ShahakShama)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/884)* status: all files reviewed, 7 unresolved discussions (waiting on @AlonLStarkWare and @dan-starkware)

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/884)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @dan-starkware, @dorimedini-starkware, and @ShahakShama)

___
*[`crates/papyrus_protobuf/build.rs` line 5 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79YMFIBXqjp-ZvNB-P:-O7DBBGY21xejqDx_vRm:b-uea2k0) ([raw file](https://github.com/starkware-libs/sequencer/blob/52484a66800d5b159c107463ccf4079f82471ce3/crates/papyrus_protobuf/build.rs#L5)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

use io::Result to make it clear what is this Result
Or even better, use Option since it's not really an error, it just means protobuf doesn't exist. You don't use the error anyway

You can print messages if you want along the way
</blockquote></details>

I used Result instead of Option for easier propagation.
___
*[`crates/papyrus_protobuf/build.rs` line 7 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79YpcJA-9e7YyrWDMZ:-O7DBJ2Q3Pg1nB_ChDKG:b-mgo8dy) ([raw file](https://github.com/starkware-libs/sequencer/blob/52484a66800d5b159c107463ccf4079f82471ce3/crates/papyrus_protobuf/build.rs#L7)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think you meant ? instead of unwrap
</blockquote></details>

For some reason ? leads to compilation error, but collect will result in an Err if any of the internal values are Errs so the logic still holds.
___
*[`crates/papyrus_protobuf/build.rs` line 10 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79YzTT2djbXNN_-AbD:-O7DCOCz9NzzHjHogm4F:b-x6zhsk) ([raw file](https://github.com/starkware-libs/sequencer/blob/52484a66800d5b159c107463ccf4079f82471ce3/crates/papyrus_protobuf/build.rs#L10)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Instead of unwrap_or(&0), write `*(version_numbers.get(1)).unwrap_or_default()`
</blockquote></details>

default isn't implemented for u32
___
*[`crates/papyrus_protobuf/build.rs` line 14 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79avHO5Uq6q5kehYcV:-O7NcSF7837EI3GpXkmQ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/52484a66800d5b159c107463ccf4079f82471ce3/crates/papyrus_protobuf/build.rs#L14)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same as before: either change to io::Result, or better, change return type to bool and rename the function to is_protoc_preinstalled
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/build.rs` line 17 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79aQYxDBAGi9hFOwnv:-O7NbfIn0arCpaOFpGjo:bju2ap0) ([raw file](https://github.com/starkware-libs/sequencer/blob/52484a66800d5b159c107463ccf4079f82471ce3/crates/papyrus_protobuf/build.rs#L17)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename to `protoc_version_output`
</blockquote></details>

But this is the Protoc version specified by the user, I think `output` is misleading.
___
*[`crates/papyrus_protobuf/build.rs` line 22 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79aXX0-IonvOpojH15:-O7NbxBQ5BGS1VqwlYLP:bpz0w73) ([raw file](https://github.com/starkware-libs/sequencer/blob/52484a66800d5b159c107463ccf4079f82471ce3/crates/papyrus_protobuf/build.rs#L22)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename to protoc_version_first_word
</blockquote></details>

What do you think about protoc_major_version_str?
___
*[`crates/papyrus_protobuf/build.rs` line 42 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79b6ZFDmaIsELbGswR:-O7Nc4Ev98LwAHA7PR9-:busp1ri) ([raw file](https://github.com/starkware-libs/sequencer/blob/52484a66800d5b159c107463ccf4079f82471ce3/crates/papyrus_protobuf/build.rs#L42)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

prebuilt -> preinstalled

or if you think prebuilt is the correct word, rename the functions to use prebuilt
</blockquote></details>

preinstalled references a case where the user already has Protoc installed on their machine, prebuilt is just the name of the package, they are not the same.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/884)* status: all files reviewed, 7 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_protobuf/build.rs` line 7 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79YpcJA-9e7YyrWDMZ:-O7NiG17E22mt2jDB8aX:b-3nb704) ([raw file](https://github.com/starkware-libs/sequencer/blob/52484a66800d5b159c107463ccf4079f82471ce3/crates/papyrus_protobuf/build.rs#L7)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

For some reason ? leads to compilation error, but collect will result in an Err if any of the internal values are Errs so the logic still holds.
</blockquote></details>

WDYM? you will panic if you fail an inner `unwrap()`

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/884)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @AlonLStarkWare, @dan-starkware, and @ShahakShama)

___
*[`crates/papyrus_protobuf/build.rs` line 40 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O7O4LS77Up2ID-tHGCM:-O7O4LS77Up2ID-tHGCN:b8z2kc2) ([raw file](https://github.com/starkware-libs/sequencer/blob/b15d62b0aac72b0fbdba42aa22a57dc43b37bcba/crates/papyrus_protobuf/build.rs#L40)):*
> ```XML
>     // If Protoc is installed use it, if not compile using prebuilt protoc.
>     println!("Building");
>     if get_preinstalled_protoc_version().is_none() {
> ```

a bit misleading now... even if you have a version, if it's too low you'll get `None`.
I think a rename is enough (if we are going with the `Option` instead of `Result` method)



_Suggestion:_
```XML
if get_valid_preinstalled_protoc_version().is_none() {
```

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/884)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @dan-starkware, @dorimedini-starkware, and @ShahakShama)

___
*[`crates/papyrus_protobuf/build.rs` line 7 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79YpcJA-9e7YyrWDMZ:-O7O3Em8-DWH9uCbbY2y:b-j69dae) ([raw file](https://github.com/starkware-libs/sequencer/blob/52484a66800d5b159c107463ccf4079f82471ce3/crates/papyrus_protobuf/build.rs#L7)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYM? you will panic if you fail an inner `unwrap()`
</blockquote></details>

You're right, my mistake. It shouldn't be a problem now
___
*[`crates/papyrus_protobuf/build.rs` line 10 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79YzTT2djbXNN_-AbD:-O7O3WITC5acTPPVnS87:b6a9u82) ([raw file](https://github.com/starkware-libs/sequencer/blob/52484a66800d5b159c107463ccf4079f82471ce3/crates/papyrus_protobuf/build.rs#L10)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

default isn't implemented for u32
</blockquote></details>

It is implemented. I'm not sure why I got a compilation error for it earlier, it may have something to do with the reference.
___
*[`crates/papyrus_protobuf/build.rs` line 14 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79avHO5Uq6q5kehYcV:-O7O3p377x7xxcGUYIkK:buugx6f) ([raw file](https://github.com/starkware-libs/sequencer/blob/52484a66800d5b159c107463ccf4079f82471ce3/crates/papyrus_protobuf/build.rs#L14)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I've decided to return an Option of the version instead like in the previous function.
___
*[`crates/papyrus_protobuf/build.rs` line 22 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79aXX0-IonvOpojH15:-O7O40wOCQRTOYfNGvF6:b-4g1wxo) ([raw file](https://github.com/starkware-libs/sequencer/blob/52484a66800d5b159c107463ccf4079f82471ce3/crates/papyrus_protobuf/build.rs#L22)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

What do you think about protoc_major_version_str?
</blockquote></details>

Correction: The returned value from `protoc --version` is in the format "libprotoc 25.1", so this fetches the numerical version. I added a comment explaining it.
___
*[`crates/papyrus_protobuf/build.rs` line 40 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O7O4LS77Up2ID-tHGCM:-O7O5bG2C8pjESe9xAL0:b-ov17q6) ([raw file](https://github.com/starkware-libs/sequencer/blob/b15d62b0aac72b0fbdba42aa22a57dc43b37bcba/crates/papyrus_protobuf/build.rs#L40)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

a bit misleading now... even if you have a version, if it's too low you'll get `None`.
I think a rename is enough (if we are going with the `Option` instead of `Result` method)
</blockquote></details>

Done. and added a comment documenting the function

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/884)* status: all files reviewed, 7 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/884)* status: all files reviewed, 7 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

___
*[`crates/papyrus_protobuf/build.rs` line 5 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79YMFIBXqjp-ZvNB-P:-O7O5l2aAyYV3wyKKzVQ:b-iggobb) ([raw file](https://github.com/starkware-libs/sequencer/blob/52484a66800d5b159c107463ccf4079f82471ce3/crates/papyrus_protobuf/build.rs#L5)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

I used Result instead of Option for easier propagation.
</blockquote></details>

Changed to Option

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/884)* status: all files reviewed, 7 unresolved discussions (waiting on @dan-starkware and @ShahakShama)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/884#-:-O7dTXcd9bNr2RMLjCgK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/papyrus_protobuf/build.rs` line 17 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79aQYxDBAGi9hFOwnv:-O7dQz_g3BQjwTZ2j7rb:b5pez1) ([raw file](https://github.com/starkware-libs/sequencer/blob/52484a66800d5b159c107463ccf4079f82471ce3/crates/papyrus_protobuf/build.rs#L17)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

But this is the Protoc version specified by the user, I think `output` is misleading.
</blockquote></details>

no, it comes from a command. Fixed it myself
___
*[`crates/papyrus_protobuf/build.rs` line 42 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O79b6ZFDmaIsELbGswR:-O7dSE4N7_zjAPJJlh2W:b-ozjoum) ([raw file](https://github.com/starkware-libs/sequencer/blob/52484a66800d5b159c107463ccf4079f82471ce3/crates/papyrus_protobuf/build.rs#L42)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

preinstalled references a case where the user already has Protoc installed on their machine, prebuilt is just the name of the package, they are not the same.
</blockquote></details>

I see. The user doesn't care about it though. Fixed it
___
*[`crates/papyrus_protobuf/build.rs` line 4 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O7dRox10Sdn6rsXoL5N:-O7dRox10Sdn6rsXoL5O:b-j66r9w) ([raw file](https://github.com/starkware-libs/sequencer/blob/2346e6cba691acc9819d9a1966df75fb251c5020/crates/papyrus_protobuf/build.rs#L4)):*
> ```XML
> use std::{env, io};
> 
> fn parse_protoc_version(protoc_version_str: &str) -> Option<(u32, u32)> {
> ```

I think that the main helper function should appear first and the helper for the helper should appear after it
___
*[`crates/papyrus_protobuf/build.rs` line 5 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O7dRZvI4jVjSUFRskJM:-O7dRZvI4jVjSUFRskJN:b-bk52e3) ([raw file](https://github.com/starkware-libs/sequencer/blob/2346e6cba691acc9819d9a1966df75fb251c5020/crates/papyrus_protobuf/build.rs#L5)):*
> ```XML
> 
> fn parse_protoc_version(protoc_version_str: &str) -> Option<(u32, u32)> {
>     // Returns Result<(major, minor)> numbers. If the minor doesn't exist, returns 0 as minor. If
> ```

returns -> return. Documentation should be declarative
___
*[`crates/papyrus_protobuf/build.rs` line 6 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/884#-O7Xl2O28L38qjT17EhH:-O7Xl2O28L38qjT17EhI:brt7maj) ([raw file](https://github.com/starkware-libs/sequencer/blob/2346e6cba691acc9819d9a1966df75fb251c5020/crates/papyrus_protobuf/build.rs#L6)):*
> ```XML
> fn parse_protoc_version(protoc_version_str: &str) -> Option<(u32, u32)> {
>     // Returns Result<(major, minor)> numbers. If the minor doesn't exist, returns 0 as minor. If
>     // the major doesn't exist, returns an error.
> ```

returns an error -> returns None

**Pull request merged**
