### PR TITLE
fix(blockifier): get alias from last state diff

### PR DESCRIPTION
**Pull request by yoavGrs**

### CODE REVIEW

**Comment by yoavGrs** [comment]
* **#2767** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2767?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2946** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2946?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2946?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main-v0.13.4`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2946)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2946#-OExgcx85k5Iu_7mBNia:-OExgcx85k5Iu_7mBNib:b-muxv9x) ([raw file](https://github.com/starkware-libs/sequencer/blob/593769421dd7ec3a3639b52a4ce916271c18c2ca/crates/blockifier/src/state/stateful_compression.rs#L183)):*
> ```XML
> struct AliasCompressor<'a, S: StateReader> {
>     state: &'a S,
>     alias_contract_address: ContractAddress,
> ```

Why is this needed? use the constant



_Code quote:_
```XML
    alias_contract_address: ContractAddress,
```
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2946#-OExffI-0-IcF4C6zwuX:-OExffI0EaZ7JF2yJ5DV:b-cbsnp2) ([raw file](https://github.com/starkware-libs/sequencer/blob/593769421dd7ec3a3639b52a4ce916271c18c2ca/crates/blockifier/src/state/stateful_compression.rs#L194)):*
> ```XML
>             new_aliases: state_diff
>                 .storage
>                 .iter()
> ```

Since you need to iterate the entire diff again, how about a more straightforward suggestion (that would be compatible with the execution):

In `state_diff_with_alias_allocation`:
* Compute `state_diff_without_aliases`
* Let the `AliasUpdater` insert the new aliases directly to the `state`.
* Compute the state diff again.

Now the `AliasCompressor` has all the info in `state`.



_Code quote:_
```XML
                .storage
                .iter()
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2946)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2946#-OEy0lb_BrFuqAlx5daB:-OEy0lb_BrFuqAlx5daC:b-2eusjc) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f1025df09b8efc27450a257bc25117028aac9ca/crates/blockifier/src/state/stateful_compression.rs#L84)):*
> ```XML
> /// Updates the alias contract with the new keys.
> struct AliasUpdater<'a, S: StateReader> {
>     state: &'a mut CachedState<S>,
> ```

Try this



_Suggestion:_
```XML
struct AliasUpdater<'a, S: State> {
    state: &'a mut S,
```
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2946#-OEy0L3c7qy_-PLQAtCv:-OEy0L3c7qy_-PLQAtCw:b8b25vt) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f1025df09b8efc27450a257bc25117028aac9ca/crates/blockifier/src/blockifier/transaction_executor.rs#L171)):*
> ```XML
> 
>         log::debug!("Final block weights: {:?}.", self.bouncer.get_accumulated_weights());
>         let mut block_state = self.block_state.take().expect(BLOCK_STATE_ACCESS_ERR);
> ```

Why not?



_Suggestion:_
```XML
self.block_state.as_mut().expect(BLOCK_STATE_ACCESS_ERR);
```

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2946)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2946)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2946#-OEy0L3c7qy_-PLQAtCv:-OEy5F-Y5KsoZLkQBdSw:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f1025df09b8efc27450a257bc25117028aac9ca/crates/blockifier/src/blockifier/transaction_executor.rs#L171)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why not?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2946#-OExgcx85k5Iu_7mBNia:-OExqBFr2PUIzlEzv7ds:bkxgi33) ([raw file](https://github.com/starkware-libs/sequencer/blob/593769421dd7ec3a3639b52a4ce916271c18c2ca/crates/blockifier/src/state/stateful_compression.rs#L183)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why is this needed? use the constant
</blockquote></details>

I removed the constant when I saw it in the versioned_constants
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2946#-OExffI-0-IcF4C6zwuX:-OExqPPH8bHz6JBEIBbj:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/593769421dd7ec3a3639b52a4ce916271c18c2ca/crates/blockifier/src/state/stateful_compression.rs#L194)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Since you need to iterate the entire diff again, how about a more straightforward suggestion (that would be compatible with the execution):

In `state_diff_with_alias_allocation`:
* Compute `state_diff_without_aliases`
* Let the `AliasUpdater` insert the new aliases directly to the `state`.
* Compute the state diff again.

Now the `AliasCompressor` has all the info in `state`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/stateful_compression.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2946#-OEy0lb_BrFuqAlx5daB:-OEy6Vp7-FnVKKy6OVmS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f1025df09b8efc27450a257bc25117028aac9ca/crates/blockifier/src/state/stateful_compression.rs#L84)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Try this
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2946#-:-OEyIua74wTw8kwwSKaR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Comment by yoavGrs** [comment]
### Merge activity

* **Dec 26, 7:50 AM EST**: [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2946) disabled "merge when ready" on this PR due to: a merge conflict with the target branch; resolve the conflict and try again..

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2946#-:-OFGbo-iAfm2s_T962_N:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2946)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 114 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2946#-OFHghU6-mcaLUWdwTus:-OFHghU6-mcaLUWdwTut:b-kkn8jm) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9b79691f984c6dbff3bbb7c260f528e9570c025/crates/blockifier/src/state/stateful_compression.rs#L114)):*
> ```XML
>                 Some(alias) => alias,
>                 None => INITIAL_AVAILABLE_ALIAS,
>             };
> ```

non-blocking; but this should be equivalent



_Suggestion:_
```XML
            let alias_to_allocate = self.next_free_alias.unwrap_or(INITIAL_AVAILABLE_ALIAS);
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2946)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/state/stateful_compression.rs` line 114 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2946#-OFHghU6-mcaLUWdwTus:-OFHlTFg9ggRKhFoAWH-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9b79691f984c6dbff3bbb7c260f528e9570c025/crates/blockifier/src/state/stateful_compression.rs#L114)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

non-blocking; but this should be equivalent
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2946)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
