### PR TITLE
test: use the executable_invoke_tx_creator in mempool test

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/789)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/789?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#789** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/789?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#760** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/760?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#780](https://github.com/starkware-libs/sequencer/pull/780) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/780?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#749** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/749?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#748** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/748?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#747** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/747?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#779** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/779?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/789)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 565 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/789#-O6vfiWOEl3Sv5vwZujb:-O6vfiWOEl3Sv5vwZujc:b-3lzwan) ([raw file](https://github.com/starkware-libs/sequencer/blob/b5a1fd327d85b116d561b211bf6215796a8116c2/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L565)):*
> ```XML
> }
> 
> // TODO(Arni): Delete this function. It is covered by
> ```

Why it cannot be removed now?



_Code quote:_
```XML
TODO(Arni): Delete this function. It is covered by
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/789)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 565 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/789#-O6vfiWOEl3Sv5vwZujb:-O6ygDmw10poZhP6oTr4:bt5syp5) ([raw file](https://github.com/starkware-libs/sequencer/blob/b5a1fd327d85b116d561b211bf6215796a8116c2/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L565)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why it cannot be removed now?
</blockquote></details>

I restacked this PR on top of #519. In this PR the other instance of calling `create_executable_tx` is removed.
No need for the TODO now :)

**Comment by ArniStarkware** [comment]
Already covered in #922.

**Pull request closed without merging**
