### PR TITLE
chore(infra): add error variant for file not found on get path

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2169?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2169** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2169?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2169?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2075** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2075?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2074** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2074?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2073** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2073?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2052** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2052?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2026** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2026?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2020** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2020?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2169)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/infra_utils/src/path.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2169#-OC3iMGA-vyM3D6pkj3h:-OC3iMGA-vyM3D6pkj3i:b-2lozi2) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9f12360184a90968511c00eff3766b5b2aafd43/crates/infra_utils/src/path.rs#L27)):*
> ```XML
>         // If `CARGO_MANIFEST_DIR` isn't set, fall back to the current working directory
>         .unwrap_or(env::current_dir().expect("Failed to get current directory"));
>     let path_buf = base_dir.join(relative_path);
> ```

Please remove this suffix.



_Code quote:_
```XML
_buf
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2169)* status: 1 of 11 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/infra_utils/src/path.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2169#-OCCgl-4Bw6nf9zSrCNo:-OCCgl-4Bw6nf9zSrCNp:b-pf07p2) ([raw file](https://github.com/starkware-libs/sequencer/blob/41012c8f0b0a9a17f313b2c86f216205903dd166/crates/infra_utils/src/path.rs#L8)):*
> ```XML
> 
> #[derive(Debug, Error)]
> pub enum GetPathError {
> ```

Maybe `PathResolutionError`? WDYT?



_Code quote:_
```XML
GetPathError
```
___
*[`crates/infra_utils/src/path.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2169#-OCChQ_p2B9RHacDkw6t:-OCChQ_p2B9RHacDkw6u:bxerbvn) ([raw file](https://github.com/starkware-libs/sequencer/blob/41012c8f0b0a9a17f313b2c86f216205903dd166/crates/infra_utils/src/path.rs#L15)):*
> ```XML
>     IoError(#[from] std::io::Error),
> }
> ```

Please add a todo on me (tsabary): wrap path-related `env::*` invocations in the repo as utility functions here 
___
*[`crates/infra_utils/src/path.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2169#-OCCguo19RlNEXXXVvMo:-OCCguo19RlNEXXXVvMp:byv3tzg) ([raw file](https://github.com/starkware-libs/sequencer/blob/41012c8f0b0a9a17f313b2c86f216205903dd166/crates/infra_utils/src/path.rs#L40)):*
> ```XML
> 
>     Ok(path)
> }
> ```

Please add tests for this: one that successfully resolves a path, one that returns `PathDoesNotExist`, and one that results in `IoError`.



_Code quote:_
```XML
pub fn resolve_project_relative_path(relative_path: &str) -> Result<PathBuf, GetPathError> {
    let base_dir = path_of_project_root();

    let path = base_dir.join(relative_path);
    if !path.try_exists()? {
        return Err(GetPathError::PathDoesNotExist { path });
    }

    Ok(path)
}
```

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 11 files at r1, 7 of 9 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2169#-:-OCCrlteAqfhGTbiupWX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/infra_utils/src/path.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2169#-OCCguo19RlNEXXXVvMo:-OCCri_A24btxToYOxl4:b6g35b3) ([raw file](https://github.com/starkware-libs/sequencer/blob/622ea2275ab25d814f3967f77c2d4a56e2d0c5dc/crates/infra_utils/src/path.rs#L40)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add tests for this: one that successfully resolves a path, one that returns `PathDoesNotExist`, and one that results in `IoError`.
</blockquote></details>

Will be in a different pr.

**Comment by ArniStarkware** [comment]
*[`crates/infra_utils/src/path.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2169#-OCCguo19RlNEXXXVvMo:-OCCzCFi7Di02Zfc-c4R:biqgj6o) ([raw file](https://github.com/starkware-libs/sequencer/blob/622ea2275ab25d814f3967f77c2d4a56e2d0c5dc/crates/infra_utils/src/path.rs#L40)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Will be in a different pr.
</blockquote></details>

See: #2210.

**Pull request merged**
