### PR TITLE
feat: support catching EntryPointNotFound

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1248)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1248)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1248#-O8fJ9DZBvsBcOlOfWdx:-O8fJ9D_8mqJo_TMYA1A:b-x2cmof) ([raw file](https://github.com/starkware-libs/sequencer/blob/eca748ae051e7ba1d31f2baae77ab203850c3586/crates/blockifier/src/execution/entry_point.rs#L170)):*
> ```XML
>                 resources: Default::default(),
>                 inner_calls: vec![],
>                 tracked_resource: TrackedResource::SierraGas,
> ```

what should I put here?



_Code quote:_
```XML
tracked_resource: TrackedResource::SierraGas
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1248)* status: 3 of 9 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1248#-O8fJ9DZBvsBcOlOfWdx:-O8kBgAvD7pvM54WFusj:b-6cp2z) ([raw file](https://github.com/starkware-libs/sequencer/blob/eca748ae051e7ba1d31f2baae77ab203850c3586/crates/blockifier/src/execution/entry_point.rs#L170)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what should I put here?
</blockquote></details>

Move this code inside `execute_entry_point_call_wrapper` and take `context.tracked_resource_stack.last()`
___
*[`crates/blockifier/src/execution/entry_point.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1248#-O8k8Tox3njkyctmkFCP:-O8k8Tox3njkyctmkFCQ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/5aa6bfe08397f7c4c36660601be7c9be61d0f031/crates/blockifier/src/execution/entry_point.rs#L174)):*
> ```XML
>                 accessed_storage_keys: Default::default(),
>             }),
>             res => res,
> ```





_Suggestion:_
```XML
        let orig_call = self.clone();
        match execute_entry_point_call_wrapper(self, contract_class, state, resources, context) {
            Err(EntryPointExecutionError::PreExecutionError(
                PreExecutionError::EntryPointNotFound(_),
            )) if context.versioned_constants().enable_reverts => Ok(CallInfo {
                call: self.clone(),
                execution: CallExecution {
                    retdata: Retdata(vec![Felt::from_hex(ENTRYPOINT_NOT_FOUND_ERROR).unwrap()]),
                    failed: true,
                    ..CallExecution::default()
                },
                tracked_resource: TrackedResource::SierraGas,
                ..CallInfo::default()
            }),
            res => res,
```
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 168 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1248#-O8k3ZLg7NfwkB2skVMP:-O8k3ZLh4ZjXwFe_il6T:bcp0rqu) ([raw file](https://github.com/starkware-libs/sequencer/blob/5aa6bfe08397f7c4c36660601be7c9be61d0f031/crates/blockifier/src/execution/entry_point_test.rs#L168)):*
> ```XML
>         CallEntryPoint { entry_point_selector, ..trivial_external_entry_point_new(test_contract) };
>     let call_info = entry_point_call.execute_directly(&mut state).unwrap();
>     assert!(call_info.execution.failed);
> ```

Can you check the retdata format?



_Code quote:_
```XML
assert!(call_info.execution.failed);
```
___
*[`crates/papyrus_rpc/src/v0_8/execution_test.rs` line 293 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1248#-O8k4y8CA0cH1C9khAh1:-O8k4y8CA0cH1C9khAh2:b-nqbxem) ([raw file](https://github.com/starkware-libs/sequencer/blob/5aa6bfe08397f7c4c36660601be7c9be61d0f031/crates/papyrus_rpc/src/v0_8/execution_test.rs#L293)):*
> ```XML
>     let entry_point_not_found_error =
>         felt!("0x000000000000000000000000454e545259504f494e545f4e4f545f464f554e44");
>     assert_eq!(call, [entry_point_not_found_error]);
> ```

Not sure this is the right behavior here. A reverted call should result in an error.



_Code quote:_
```XML
    // Calling a non-existent entry point.
    let call = module
        .call::<_, Vec<Felt>>(
            "starknet_V0_8_call",
            (
                CallRequest {
                    contract_address: *DEPRECATED_CONTRACT_ADDRESS,
                    entry_point_selector: selector_from_name("aaa"),
                    calldata: calldata![key, value],
                },
                BlockId::HashOrNumber(BlockHashOrNumber::Number(BlockNumber(0))),
            ),
        )
        .await
        .unwrap();

    let entry_point_not_found_error =
        felt!("0x000000000000000000000000454e545259504f494e545f4e4f545f464f554e44");
    assert_eq!(call, [entry_point_not_found_error]);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/entry_point.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1248#-O8k8Tox3njkyctmkFCP:-O93qNa99wIWv4SJ4k7p:b-mml3k7) ([raw file](https://github.com/starkware-libs/sequencer/blob/5aa6bfe08397f7c4c36660601be7c9be61d0f031/crates/blockifier/src/execution/entry_point.rs#L174)):*
> ```
>  gas_consumed: 0,
> ```

this is also the default, is there a reason you left it?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/entry_point.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1248#-O8k8Tox3njkyctmkFCP:-O93vfNTDA7ZmvF6W6YH:b-ofhlf1) ([raw file](https://github.com/starkware-libs/sequencer/blob/5aa6bfe08397f7c4c36660601be7c9be61d0f031/crates/blockifier/src/execution/entry_point.rs#L174)):*
> ```
> self.clone(),
> ```

self was consume by `execute_entry_point_call_wrapper`

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1248)* status: 3 of 9 files reviewed, 3 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 168 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1248#-O8k3ZLg7NfwkB2skVMP:-O93we3f6cFou0hzZz55:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5aa6bfe08397f7c4c36660601be7c9be61d0f031/crates/blockifier/src/execution/entry_point_test.rs#L168)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you check the retdata format?
</blockquote></details>

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1248)* status: 5 of 10 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1248#-O94HrIB2ztyCcQkx5id:-O94HrIB2ztyCcQkx5ie:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/db62294eed9b68a860e1cd29170e4ba65aca2d1e/crates/blockifier/src/execution/execution_utils.rs#L60)):*
> ```XML
>     context: &mut EntryPointExecutionContext,
> ) -> EntryPointExecutionResult<CallInfo> {
>     let tracked_resource = contract_class
> ```





_Suggestion:_
```XML
contract_tracked_resource = contract_class
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 91 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1248#-O94H4f-88EC-7YoeY-D:-O94H4f-88EC-7YoeY-E:boanvha) ([raw file](https://github.com/starkware-libs/sequencer/blob/db62294eed9b68a860e1cd29170e4ba65aca2d1e/crates/blockifier/src/execution/execution_utils.rs#L91)):*
> ```XML
>             res
>         }
>     }
> ```

To be on the safe side - you might add more cases here and forget to pop it.



_Suggestion:_
```XML
    let orig_call = call.clone();
    let res = execute_entry_point_call(call, contract_class, state, resources, context);
    let current_tracked_resource = context.tracked_resource_stack.pop().expect("Unexpected empty tracked resource.")
    match res {
        Err(EntryPointExecutionError::PreExecutionError(
            PreExecutionError::EntryPointNotFound(_),
        )) if context.versioned_constants().enable_reverts => Ok(CallInfo {
            call: orig_call,
            execution: CallExecution {
                retdata: Retdata(vec![Felt::from_hex(ENTRYPOINT_NOT_FOUND_ERROR).unwrap()]),
                failed: true,
                gas_consumed: 0,
                ..CallExecution::default()
            },
            tracked_resource: current_tracked_resource,
            ..CallInfo::default()
        }),
        res => res;
    }
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1248)* status: 5 of 10 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1248#-O8k8Tox3njkyctmkFCP:-O94IaNX1AUr4i-btycY:b-95rdri) ([raw file](https://github.com/starkware-libs/sequencer/blob/5aa6bfe08397f7c4c36660601be7c9be61d0f031/crates/blockifier/src/execution/entry_point.rs#L174)):*
>this is also the default, is there a reason you left it?
I deleted it

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1248)* status: 5 of 14 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1248)* status: 5 of 14 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 7 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1248)* status: 9 of 14 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/papyrus_rpc/src/v0_8/execution_test.rs` line 293 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1248#-O8k4y8CA0cH1C9khAh1:-O9AtWwR-OKtSI0hvf8H:b-7ql1td) ([raw file](https://github.com/starkware-libs/sequencer/blob/5aa6bfe08397f7c4c36660601be7c9be61d0f031/crates/papyrus_rpc/src/v0_8/execution_test.rs#L293)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Not sure this is the right behavior here. A reverted call should result in an error.
</blockquote></details>

fixed

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1248)* status: 7 of 14 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 91 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1248#-O94H4f-88EC-7YoeY-D:-O9AtZPM3GMc64TfqVFo:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/db62294eed9b68a860e1cd29170e4ba65aca2d1e/crates/blockifier/src/execution/execution_utils.rs#L91)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

To be on the safe side - you might add more cases here and forget to pop it.
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r4, 2 of 10 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1248#-:-O9Au5QkDaNss1JuZsA7:bnfp4nl)* status: 13 of 14 files reviewed, all discussions resolved

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1248)* status: 13 of 14 files reviewed, all discussions resolved

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1248)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/execution_utils.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1248#-O94HrIB2ztyCcQkx5id:-O9ddmPMAm-toWBeKMYs:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/db62294eed9b68a860e1cd29170e4ba65aca2d1e/crates/blockifier/src/execution/execution_utils.rs#L60)):*
> ```XML
>     context: &mut EntryPointExecutionContext,
> ) -> EntryPointExecutionResult<CallInfo> {
>     let tracked_resource = contract_class
> ```

done

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1248)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1248)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1248#-:-O9jelzW4VRGtTdQKew1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Pull request merged**
