### PR TITLE
feat(blockifier): cairo1 revert stack now part of ErrorStack

### PR DESCRIPTION
**Pull request by dorimedini-starkware**

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1490?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1491** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1491?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1490** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1490?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1469** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1469?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1468** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1468?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1461** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1461?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1460** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1460?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1459** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1459?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1458** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1458?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1457** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1457?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1490)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 878 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAXL3EiEn288FoNA1vL:-OAXL3EiEn288FoNA1vM:b-bqozq3) ([raw file](https://github.com/starkware-libs/sequencer/blob/339307072376a70769f4a20abe95f6f614662b3a/crates/blockifier/src/execution/stack_trace_test.rs#L878)):*
> ```XML
>     let error_stack_2_frames =
>         extract_trailing_cairo1_revert_trace(&call_info_2_frames, Cairo1RevertHeader::Execution);
>     let diff = error_stack_2_frames.to_string().len() - error_stack_1_frame.to_string().len();
> ```

stringifying a single frame now results in a string with an extra header.
to fix the test, use two errors: 1 frame and 2 frames, and then subtract lengths to get the length of a single frame.



_Code quote:_
```XML
fn test_min_cairo1_frame_length() {
    let failure_hex = "0xdeadbeef";
    let call_info_1_frame = CallInfo {
        call: CallEntryPoint {
            class_hash: Some(ClassHash::default()),
            storage_address: ContractAddress::default(),
            entry_point_selector: EntryPointSelector::default(),
            ..Default::default()
        },
        execution: CallExecution {
            retdata: Retdata(vec![felt!(failure_hex)]),
            failed: true,
            ..Default::default()
        },
        ..Default::default()
    };
    let call_info_2_frames = CallInfo {
        call: CallEntryPoint {
            class_hash: Some(ClassHash::default()),
            storage_address: ContractAddress::default(),
            entry_point_selector: EntryPointSelector::default(),
            ..Default::default()
        },
        execution: CallExecution {
            retdata: Retdata(vec![felt!(failure_hex), felt!(ENTRYPOINT_FAILED_ERROR)]),
            failed: true,
            ..Default::default()
        },
        inner_calls: vec![call_info_1_frame.clone()],
        ..Default::default()
    };
    let error_stack_1_frame =
        extract_trailing_cairo1_revert_trace(&call_info_1_frame, Cairo1RevertHeader::Execution);
    let error_stack_2_frames =
        extract_trailing_cairo1_revert_trace(&call_info_2_frames, Cairo1RevertHeader::Execution);
    let diff = error_stack_2_frames.to_string().len() - error_stack_1_frame.to_string().len();
```
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 964 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAXLGiq7cfnE2dW0eEd:-OAXLGiq7cfnE2dW0eEe:bx936sl) ([raw file](https://github.com/starkware-libs/sequencer/blob/339307072376a70769f4a20abe95f6f614662b3a/crates/blockifier/src/execution/stack_trace_test.rs#L964)):*
> ```XML
>     assert!(error_string.len() <= TRACE_LENGTH_CAP);
>     assert_eq!(error_string[..expected_head.len()], expected_head);
>     assert_eq!(error_string[error_string.len() - expected_tail.len()..], expected_tail);
> ```

explicit comparisons (instead of starts_with and ends_with) makes it easier to debug failures



_Code quote:_
```XML
    assert_eq!(error_string[..expected_head.len()], expected_head);
    assert_eq!(error_string[error_string.len() - expected_tail.len()..], expected_tail);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/stack_trace.rs` line 234 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAX_oXT5JxWQl440Vth:-OAX_oXT5JxWQl440Vti:b-5fpf25) ([raw file](https://github.com/starkware-libs/sequencer/blob/44776206978211acf0c4b2ed5ac11bd17fb7cd08/crates/blockifier/src/execution/stack_trace.rs#L234)):*
> ```XML
> #[derive(Clone, Debug)]
> pub struct Cairo1RevertStack {
>     pub header: Cairo1RevertHeader,
> ```

does not seem to belong here



_Code quote:_
```XML
  pub header: Cairo1RevertHeader,
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/stack_trace.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAXalkd--sPV6mvnIS9:-OAXalkd--sPV6mvnISA:b-hbp9p5) ([raw file](https://github.com/starkware-libs/sequencer/blob/44776206978211acf0c4b2ed5ac11bd17fb7cd08/crates/blockifier/src/execution/stack_trace.rs#L101)):*
> ```XML
> pub enum Frame {
>     EntryPoint(EntryPointErrorFrame),
>     Cairo1Tail(Cairo1RevertStack),
> ```

why is this a tail?



_Code quote:_
```XML
Cairo1Tail
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1490)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAXalkd--sPV6mvnIS9:-OAXe_ET5w8pYqppeXvg:bc8jozx) ([raw file](https://github.com/starkware-libs/sequencer/blob/44776206978211acf0c4b2ed5ac11bd17fb7cd08/crates/blockifier/src/execution/stack_trace.rs#L101)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is this a tail?
</blockquote></details>

because this cairo1 revert stack cannot contain entry point frames or vm frames in it; once we hit a Cairo1 revert stack, it must be by definition the tail of the stack.
since this is a variant of `Frame`, and the cairo1 revert stack contains it's own concept of frames, I thought it wise to be explicit in the variant name
___
*[`crates/blockifier/src/execution/stack_trace.rs` line 234 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAX_oXT5JxWQl440Vth:-OAXesw22LRpX7bWYvij:b4qa0vb) ([raw file](https://github.com/starkware-libs/sequencer/blob/44776206978211acf0c4b2ed5ac11bd17fb7cd08/crates/blockifier/src/execution/stack_trace.rs#L234)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

does not seem to belong here
</blockquote></details>

why not? it is part of the data; the cairo1 revert stack always starts comes from one of two sources (validate/execute)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/stack_trace.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAXalkd--sPV6mvnIS9:-OAXv3MtDwOGaIl5Leqf:bm56lg0) ([raw file](https://github.com/starkware-libs/sequencer/blob/44776206978211acf0c4b2ed5ac11bd17fb7cd08/crates/blockifier/src/execution/stack_trace.rs#L101)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

because this cairo1 revert stack cannot contain entry point frames or vm frames in it; once we hit a Cairo1 revert stack, it must be by definition the tail of the stack.
since this is a variant of `Frame`, and the cairo1 revert stack contains it's own concept of frames, I thought it wise to be explicit in the variant name
</blockquote></details>

What is a frame?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/stack_trace.rs` line 234 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAX_oXT5JxWQl440Vth:-OAXvF3yClFZ-HqkEOZT:b-x6zm1r) ([raw file](https://github.com/starkware-libs/sequencer/blob/44776206978211acf0c4b2ed5ac11bd17fb7cd08/crates/blockifier/src/execution/stack_trace.rs#L234)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not? it is part of the data; the cairo1 revert stack always starts comes from one of two sources (validate/execute)
</blockquote></details>

the stack is the same regardless of if the source is validate or execute

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1490)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAXalkd--sPV6mvnIS9:-OAXxdHJ9lLFK_x2lpbQ:b-igvp6l) ([raw file](https://github.com/starkware-libs/sequencer/blob/44776206978211acf0c4b2ed5ac11bd17fb7cd08/crates/blockifier/src/execution/stack_trace.rs#L101)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What is a frame?
</blockquote></details>

up until now, two frames basically: entry point frame (one per syscall) and VM frame (one per inner call in a contract, one PC location per frame).
I am open to renaming this type if you think it's confusing
___
*[`crates/blockifier/src/execution/stack_trace.rs` line 234 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAX_oXT5JxWQl440Vth:-OAXy3Lw8_UM0k6rqUyF:bd6u4jv) ([raw file](https://github.com/starkware-libs/sequencer/blob/44776206978211acf0c4b2ed5ac11bd17fb7cd08/crates/blockifier/src/execution/stack_trace.rs#L234)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

the stack is the same regardless of if the source is validate or execute
</blockquote></details>

not it's string formatting. we provide a header indicating whether this is from validate or execute.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1490)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 234 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAX_oXT5JxWQl440Vth:-OAY-YihE_fnpo2Nen8Q:b7zhl58) ([raw file](https://github.com/starkware-libs/sequencer/blob/44776206978211acf0c4b2ed5ac11bd17fb7cd08/crates/blockifier/src/execution/stack_trace.rs#L234)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not it's string formatting. we provide a header indicating whether this is from validate or execute.
</blockquote></details>

the TransactionExecutionInfo needs this info, because it will store a non-stringified error stack object.
when converted to a string we need to print the respective header

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/stack_trace.rs` line 234 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAX_oXT5JxWQl440Vth:-OAkyMQX3H4ChJ9nuWxR:b21y6o7) ([raw file](https://github.com/starkware-libs/sequencer/blob/44776206978211acf0c4b2ed5ac11bd17fb7cd08/crates/blockifier/src/execution/stack_trace.rs#L234)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the TransactionExecutionInfo needs this info, because it will store a non-stringified error stack object.
when converted to a string we need to print the respective header
</blockquote></details>

can you store it in the `TansactionExecutionInfo`?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1490)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 234 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAX_oXT5JxWQl440Vth:-OAlCXQWB410mQHRCqIg:b-2qei93) ([raw file](https://github.com/starkware-libs/sequencer/blob/44776206978211acf0c4b2ed5ac11bd17fb7cd08/crates/blockifier/src/execution/stack_trace.rs#L234)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you store it in the `TansactionExecutionInfo`?
</blockquote></details>

why?
this means that `ErrorStack` cannot implement `Display`, because part of the data needed to format the string is not in the struct

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/stack_trace.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAXalkd--sPV6mvnIS9:-OB4Io8c2-nrX4FOJI_f:b-dbcvse) ([raw file](https://github.com/starkware-libs/sequencer/blob/44776206978211acf0c4b2ed5ac11bd17fb7cd08/crates/blockifier/src/execution/stack_trace.rs#L101)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

up until now, two frames basically: entry point frame (one per syscall) and VM frame (one per inner call in a contract, one PC location per frame).
I am open to renaming this type if you think it's confusing
</blockquote></details>

Putting a stack and a frame in stack in the same enum is strange.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/stack_trace.rs` line 234 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAX_oXT5JxWQl440Vth:-OB4Jt_E3tqUCt53AFXR:bfamhrh) ([raw file](https://github.com/starkware-libs/sequencer/blob/44776206978211acf0c4b2ed5ac11bd17fb7cd08/crates/blockifier/src/execution/stack_trace.rs#L234)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why?
this means that `ErrorStack` cannot implement `Display`, because part of the data needed to format the string is not in the struct
</blockquote></details>

If you add it it is no longer a just a revert stack.

Maybe we should rename it to
Cairo1RevertSummery?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1490)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAXalkd--sPV6mvnIS9:-OB55rWu543qPxtqzgdW:b-hff6wv) ([raw file](https://github.com/starkware-libs/sequencer/blob/44776206978211acf0c4b2ed5ac11bd17fb7cd08/crates/blockifier/src/execution/stack_trace.rs#L101)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Putting a stack and a frame in stack in the same enum is strange.
</blockquote></details>

renamed
___
*[`crates/blockifier/src/execution/stack_trace.rs` line 234 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAX_oXT5JxWQl440Vth:-OB55sbI0DcP9Uqs3ybj:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/44776206978211acf0c4b2ed5ac11bd17fb7cd08/crates/blockifier/src/execution/stack_trace.rs#L234)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

If you add it it is no longer a just a revert stack.

Maybe we should rename it to
Cairo1RevertSummery?
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/stack_trace.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAXalkd--sPV6mvnIS9:-OBKZMQ_EfcO8g_8Aotb:b-x64qio) ([raw file](https://github.com/starkware-libs/sequencer/blob/44776206978211acf0c4b2ed5ac11bd17fb7cd08/crates/blockifier/src/execution/stack_trace.rs#L101)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

renamed
</blockquote></details>

What about the variant name?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 4 of 8 files at r2, 3 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1490)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1490)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAXalkd--sPV6mvnIS9:-OBKbdtg3nvaqK9ARt_8:b1jeyey) ([raw file](https://github.com/starkware-libs/sequencer/blob/44776206978211acf0c4b2ed5ac11bd17fb7cd08/crates/blockifier/src/execution/stack_trace.rs#L101)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What about the variant name?
</blockquote></details>

what do you suggest?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1490)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1490#-OAXalkd--sPV6mvnIS9:-OBdTAm2-YWKfOQSCJVP:b-yrrvf1) ([raw file](https://github.com/starkware-libs/sequencer/blob/44776206978211acf0c4b2ed5ac11bd17fb7cd08/crates/blockifier/src/execution/stack_trace.rs#L101)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what do you suggest?
</blockquote></details>

Cairo1RevertSummery
or just
RevertSummery

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1490)* status: 8 of 9 files reviewed, all discussions resolved

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1490)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Nov 17, 5:09 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1490).

**Pull request merged**
