### PR TITLE
feat(mempool_infra): add serde utils

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #904
- #907 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/907)

### CODE REVIEW

**Review by lev-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/907)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/serde_utils.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/907#-O7XnNgt4CWAS0N7De9U:-O7XnNgt4CWAS0N7De9V:b8zopcu) ([raw file](https://github.com/starkware-libs/sequencer/blob/74e443605f44cd31ec4705939d9738dd0cc97cf7/crates/mempool_infra/src/serde_utils.rs#L16)):*
> ```XML
> }
> 
> impl<T> SerdeWrapper<T>
> ```

Change to BincodeSerdeWrapper



_Code quote:_
```XML
SerdeWrapper
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/907)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/mempool_infra/src/serde_utils.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/907#-O7XnNgt4CWAS0N7De9U:-O7Y7kp93xGSdYIVInK5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/74e443605f44cd31ec4705939d9738dd0cc97cf7/crates/mempool_infra/src/serde_utils.rs#L16)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

Change to BincodeSerdeWrapper
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/907)* status: all files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#904](https://github.com/starkware-libs/sequencer/pull/904)

**Pull request closed without merging**
