### PR TITLE
refactor(starknet_integration_tests): separate sequencer setup from test setup

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Comment by yair-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2299?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2299** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2299?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2299?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2242** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2242?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2253** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2253?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2299)* status: 0 of 5 files reviewed, 9 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1oOyV0gu-aifl9X2l:-OD1oOyV0gu-aifl9X2m:b-ono74o) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/integration_test_setup.rs#L55)):*
> ```XML
> 
>         let (mut consensus_manager_configs, _consensus_proposals_channels) =
>             create_consensus_manager_configs_and_channels(1);
> ```

Could you please explain where this values come from?



_Code quote:_
```XML
1
```
___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1oHTt2Dw64dmVU0XO:-OD1oHTt2Dw64dmVU0XP:b-ono74o) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/integration_test_setup.rs#L59)):*
> ```XML
>         // Derive the configuration for the sequencer node.
>         let (config, required_params) = create_config(
>             0,
> ```

Could you please explain where this values come from?



_Code quote:_
```XML
0
```
___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1ocpy6t96k0E3Aw2K:-OD1ocpy6t96k0E3Aw2L:b-gunnc1) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/flow_test_setup.rs#L42)):*
> ```XML
>     pub async fn new_from_tx_generator(tx_generator: &MultiAccountTransactionGenerator) -> Self {
>         let handle = Handle::current();
>         let task_executor = TokioExecutor::new(handle);
> ```

Unrelated to this pr, but you can drop this completely. 



_Code quote:_
```XML
        let handle = Handle::current();
        let task_executor = TokioExecutor::new(handle);
```
___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1oZkdCgYVvXQKUotE:-OD1oZkdCgYVvXQKUotF:bgyegqg) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/flow_test_setup.rs#L47)):*
> ```XML
>         let accounts = tx_generator.accounts();
>         let (mut consensus_manager_configs, consensus_proposals_channels) =
>             create_consensus_manager_configs_and_channels(1);
> ```

Could you please explain where this values come from? 



_Code quote:_
```XML
1
```
___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1oVzD5PwdT1zHpZ5M:-OD1oVzD5PwdT1zHpZ5N:bwlgool) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/flow_test_setup.rs#L49)):*
> ```XML
>             create_consensus_manager_configs_and_channels(1);
> 
>         let proposer_consensus_manager_config = consensus_manager_configs.remove(0);
> ```

Could you please explain where this values come from? Should this be `PROPOSER_ID`?



_Code quote:_
```XML
0
```
___
*[`crates/starknet_integration_tests/src/utils.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1nG1WBpZTii2p9GQi:-OD1nG1WBpZTii2p9GQj:be8oz5u) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/utils.rs#L49)):*
> ```XML
> }
> 
> // TODO(yair, itay): Create config presets for tests.
> ```

Please change to `Tsabary`, otherwise I won't find it :-)



_Code quote:_
```XML
 itay
```
___
*[`crates/starknet_integration_tests/src/utils.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1niu9C_f_CTuBFVnv:-OD1niu9C_f_CTuBFVnw:b5iidi0) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/utils.rs#L57)):*
> ```XML
>     mut consensus_manager_config: ConsensusManagerConfig,
> ) -> (SequencerNodeConfig, RequiredParams) {
>     set_validator_id(&mut consensus_manager_config, sequencer_id);
> ```

Could we please unify the `validator id` and `sequencer address` config parameters, assuming they have the same meaning?
@matan-starkware @alonh5 



_Code quote:_
```XML
set_validator_id(&mut consensus_manager_config, sequencer_id);
```
___
*[`crates/starknet_integration_tests/src/utils.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1nQmbB-cFT0evMdsg:-OD1nQmbB-cFT0evMdsh:b-w0xz3j) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/utils.rs#L63)):*
> ```XML
>     let http_server_config = create_http_server_config().await;
>     let rpc_state_reader_config = test_rpc_state_reader_config(rpc_server_addr);
>     let mempool_p2p_config = create_mempool_p2p_config(sequencer_id, chain_info.chain_id.clone());
> ```

Why do you need to explicitly mention `chain id`? The config pointer mapping should address this, no? 



_Code quote:_
```XML
    let mempool_p2p_config = create_mempool_p2p_config(sequencer_id, chain_info.chain_id.clone());
```
___
*[`crates/starknet_integration_tests/src/utils.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1mn9o-yIoFp8Jen9U:-OD1mn9o-yIoFp8Jen9V:b-awl6px) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/utils.rs#L259)):*
> ```XML
>     )
>     .unwrap();
> }
> ```

Can this be passed as an arg through the preset file?



_Code quote:_
```XML
fn set_validator_id(consensus_manager_config: &mut ConsensusManagerConfig, sequencer_id: usize) {
    consensus_manager_config.consensus_config.validator_id = ValidatorId::try_from(
        Felt::from(consensus_manager_config.consensus_config.validator_id)
            + Felt::from(sequencer_id),
    )
    .unwrap();
}
```
___
*[`crates/starknet_integration_tests/src/utils.rs` line 268 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1mvgu5RgRYyqpHRdO:-OD1mvgu5RgRYyqpHRdP:bs9l813) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/utils.rs#L268)):*
> ```XML
>     let mut config = MempoolP2pConfig::default();
>     config.network_config.tcp_port += u16::try_from(sequencer_id).unwrap();
>     config.network_config.quic_port += u16::try_from(sequencer_id).unwrap();
> ```

Could you please explain what is this part doing?



_Code quote:_
```XML
    config.network_config.tcp_port += u16::try_from(sequencer_id).unwrap();
    config.network_config.quic_port += u16::try_from(sequencer_id).unwrap();
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2299)* status: 0 of 6 files reviewed, 9 unresolved discussions (waiting on @alonh5, @Itay-Tsabary-Starkware, and @matan-starkware)

___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1ocpy6t96k0E3Aw2K:-OD5ECcm1uT9M7stg26X:b-iwmm5x) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/flow_test_setup.rs#L42)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Unrelated to this pr, but you can drop this completely.
</blockquote></details>

Added TODO
___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1oZkdCgYVvXQKUotE:-OD5EeTtBE7UqGBZgcmu:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/flow_test_setup.rs#L47)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Could you please explain where this values come from?
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1oVzD5PwdT1zHpZ5M:-OD5EerV0Qdw2s5KRXZX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/flow_test_setup.rs#L49)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Could you please explain where this values come from? Should this be `PROPOSER_ID`?
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1oOyV0gu-aifl9X2l:-OD5EoCC2xmxnobIhhrm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/integration_test_setup.rs#L55)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Could you please explain where this values come from?
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1oHTt2Dw64dmVU0XO:-OD5F0rSA7wiavuRBnK7:b3owt4l) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/integration_test_setup.rs#L59)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Could you please explain where this values come from?
</blockquote></details>

Replaced with a const
___
*[`crates/starknet_integration_tests/src/utils.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1nG1WBpZTii2p9GQi:-OD5F8L1Dhme9_YOwU-a:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/utils.rs#L49)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to `Tsabary`, otherwise I won't find it :-)
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/utils.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1niu9C_f_CTuBFVnv:-OD5Fa9K9iy18op_ADYL:b-rf0ce7) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/utils.rs#L57)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Could we please unify the `validator id` and `sequencer address` config parameters, assuming they have the same meaning?
@matan-starkware @alonh5
</blockquote></details>

Added a todo on @matan-starkware
___
*[`crates/starknet_integration_tests/src/utils.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1nQmbB-cFT0evMdsg:-OD5GA_f-9WhrJO_dbhc:b-14alv) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/utils.rs#L63)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Why do you need to explicitly mention `chain id`? The config pointer mapping should address this, no?
</blockquote></details>

In the test, we are not loading the configuration using the config crate; we create the instance directly.
There is a TODO to use presets.
___
*[`crates/starknet_integration_tests/src/utils.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1mn9o-yIoFp8Jen9U:-OD5Gcnc3wbA1eHS12Ud:b96gd1) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/utils.rs#L259)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can this be passed as an arg through the preset file?
</blockquote></details>

It will automatically once we have it
___
*[`crates/starknet_integration_tests/src/utils.rs` line 268 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1mvgu5RgRYyqpHRdO:-OD5GmZI-8a-9gMvgYRc:b6ml3g6) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/utils.rs#L268)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Could you please explain what is this part doing?
</blockquote></details>

Added comment.
This will be resolved too when we use presets

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2299)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @alonh5, @matan-starkware, and @yair-starkware)

___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1oZkdCgYVvXQKUotE:-OD5fuvC5d7M0ZkSrGUv:b-rxp4aq) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/flow_test_setup.rs#L47)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Could you please create a `number_of_sequencer_nodes` const/var and use it where relevant?
___
*[`crates/starknet_integration_tests/src/utils.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1niu9C_f_CTuBFVnv:-OD5gGuyE2eA4bpLuEHp:b952y1l) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/utils.rs#L57)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Added a todo on @matan-starkware
</blockquote></details>

Thanks. Please add a todo to drop this function then.
___
*[`crates/starknet_integration_tests/src/utils.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1nQmbB-cFT0evMdsg:-OD5gTHv0Nl12oN_RZPK:br59jnk) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/utils.rs#L63)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

In the test, we are not loading the configuration using the config crate; we create the instance directly.
There is a TODO to use presets.
</blockquote></details>

This is very fragile. How much do you estimate it would take to switch to the robust config loading mechanism a la the integration test?

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2299)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware, @matan-starkware, and @yair-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD6l6WuBiRz5AQqHnMU:-OD6l6Wv3rt3P4GVMiKc:bqewbuh) (no related file):*
Could you please split this PR? Looks like there are a few parts that can and should be reviewed separately.

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2299)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @alonh5, @Itay-Tsabary-Starkware, and @matan-starkware)

___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1oZkdCgYVvXQKUotE:-ODAorsg4F8AIJRSB8np:b-bjpj7a) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/flow_test_setup.rs#L47)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Could you please create a `number_of_sequencer_nodes` const/var and use it where relevant?
</blockquote></details>

Better?
___
*[`crates/starknet_integration_tests/src/utils.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1niu9C_f_CTuBFVnv:-ODAphIj2QzF4shzrdUR:b-urw9y6) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/utils.rs#L57)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Thanks. Please add a todo to drop this function then.
</blockquote></details>

Updated the existing todo
___
*[`crates/starknet_integration_tests/src/utils.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1nQmbB-cFT0evMdsg:-OD5hmBm0gIbns5Rl15R:b-35aqti) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/utils.rs#L63)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

This is very fragile. How much do you estimate it would take to switch to the robust config loading mechanism a la the integration test?
</blockquote></details>

Perhaps a day.
I will know better when the multiple sequencers test succeeds (already in a PR: https://github.com/starkware-libs/sequencer/pull/2348).
I think the sequencer address/validator id issue might cause some problems because IIUC the validator ids must be a range [0, num sequencers)

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2299)* status: 1 of 6 files reviewed, 6 unresolved discussions (waiting on @alonh5, @Itay-Tsabary-Starkware, and @matan-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD6l6WuBiRz5AQqHnMU:-ODBItfr9_81QdwXqtiI:b-j16lgz) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Could you please split this PR? Looks like there are a few parts that can and should be reviewed separately.
</blockquote></details>

Splitted.
Sorry @Itay-Tsabary-Starkware, PTAL again

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2299)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @alonh5, @Itay-Tsabary-Starkware, and @matan-starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1nQmbB-cFT0evMdsg:-ODBkZep9gUNfS5AU2Kh:bkfmohs) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/utils.rs#L63)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I highly suggest to use `RequiredParams` then, its mere purpose is to detail the required parameters that need to be explicitly passed or set n the map. WDYT?
</blockquote></details>

In the config crate, required params are parameters that the user must provide (they don't have a default value).
The ports are not required params in this notion.

Do you want to have a separate concept of required params for the integration tests? The function arguments make it so that the user has to provide them.

Once we have presets everything will be simpler.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2299)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @alonh5, @matan-starkware, and @yair-starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1nQmbB-cFT0evMdsg:-ODBt3bg2sj-XVsf9jL6:b-qprcru) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/utils.rs#L63)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

In the config crate, required params are parameters that the user must provide (they don't have a default value).
The ports are not required params in this notion.

Do you want to have a separate concept of required params for the integration tests? The function arguments make it so that the user has to provide them.

Once we have presets everything will be simpler.
</blockquote></details>

PTAL
https://github.com/starkware-libs/sequencer/blob/main/crates/starknet_sequencer_node/src/config/test_utils.rs#L8-L15
I was suggesting to use this struct to handle the passing of required parameters to the test.

**Comment by yair-starkware** [comment]
*[`crates/starknet_integration_tests/src/utils.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD1nQmbB-cFT0evMdsg:-ODKrLXv1eyqvC4Fn1th:b-mcnnjf) ([raw file](https://github.com/starkware-libs/sequencer/blob/42cab2e37d1ba30762386f2c3509629c6909a2b5/crates/starknet_integration_tests/src/utils.rs#L63)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

PTAL
https://github.com/starkware-libs/sequencer/blob/main/crates/starknet_sequencer_node/src/config/test_utils.rs#L8-L15
I was suggesting to use this struct to handle the passing of required parameters to the test.
</blockquote></details>

I think it is unnecessary once we use the config crate

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 4 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2299)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @matan-starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2299)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @matan-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-OD6l6WuBiRz5AQqHnMU:-ODLBu5V4yShGYm8SLgh:bno4d9u) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Splitted.
Sorry @Itay-Tsabary-Starkware, PTAL again
</blockquote></details>

Unblocked

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3, 4 of 4 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2299)* status: all files reviewed, 4 unresolved discussions (waiting on @matan-starkware and @yair-starkware)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 37 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-ODaVBKN6CPPR4r_kJNX:-ODaVBKN6CPPR4r_kJNY:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d45367460a2c488020f8bb7b5b5982706e2da19/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L37)):*
> ```XML
> #[rstest]
> #[tokio::test]
> async fn end_to_end(mut tx_generator: MultiAccountTransactionGenerator) {
> ```





_Suggestion:_
```XML
end_to_end_flow
```
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 38 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-ODaVQ-O6eQcQGYzOSag:-ODaVQ-O6eQcQGYzOSah:b-3n20rv) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d45367460a2c488020f8bb7b5b5982706e2da19/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L38)):*
> ```XML
> #[tokio::test]
> async fn end_to_end(mut tx_generator: MultiAccountTransactionGenerator) {
>     starknet_sequencer_infra::trace_util::configure_tracing();
> ```

import?



_Suggestion:_
```XML
configure_tracing();
```
___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-ODaUl6JEnUgjupWwK8j:-ODaUl6K2SWf0Ezbb9to:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d45367460a2c488020f8bb7b5b5982706e2da19/crates/starknet_integration_tests/src/flow_test_setup.rs#L74)):*
> ```XML
> }
> 
> pub struct SequencerTestSetup {
> ```





_Suggestion:_
```XML
SequencerSetup
```
___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-ODaUZ3P7XCgFhzNsK4V:-ODaUZ3P7XCgFhzNsK4W:b5v0dm2) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d45367460a2c488020f8bb7b5b5982706e2da19/crates/starknet_integration_tests/src/flow_test_setup.rs#L110)):*
> ```XML
>         .await;
> 
>         debug!("Rpc server spawned at: {}", rpc_server_addr);
> ```

Why do we need the address?



_Code quote:_
```XML
debug!("Rpc server spawned at: {}", rpc_server_addr);
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2299)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @matan-starkware)

___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-ODaUZ3P7XCgFhzNsK4V:-ODalaYp9M79WLP9QmaA:bewywsl) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d45367460a2c488020f8bb7b5b5982706e2da19/crates/starknet_integration_tests/src/flow_test_setup.rs#L110)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why do we need the address?
</blockquote></details>

It goes to the config of RpcStateReader.
It needs to be changed as part of making all of the ports configurable.
___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-ODaUl6JEnUgjupWwK8j:-ODalXBy0t-JvIDTglqh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d45367460a2c488020f8bb7b5b5982706e2da19/crates/starknet_integration_tests/src/flow_test_setup.rs#L74)):*
> ```XML
> }
> 
> pub struct SequencerTestSetup {
> ```

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2299)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware and @yair-starkware)

___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-ODaUZ3P7XCgFhzNsK4V:-ODapDWtEGgj_iEYIJ4O:b-a16yv9) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d45367460a2c488020f8bb7b5b5982706e2da19/crates/starknet_integration_tests/src/flow_test_setup.rs#L110)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

It goes to the config of RpcStateReader.
It needs to be changed as part of making all of the ports configurable.
</blockquote></details>

I meant why do we need to log it?

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2299)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @matan-starkware)

___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-ODaUZ3P7XCgFhzNsK4V:-ODePId-D52i2sZOKXky:ba3dfob) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d45367460a2c488020f8bb7b5b5982706e2da19/crates/starknet_integration_tests/src/flow_test_setup.rs#L110)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I meant why do we need to log it?
</blockquote></details>

Removed

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2299)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by alonh5 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2299#-:-ODfiK5jBMUnqVjPlPRP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Pull request merged**
