### PR TITLE
chore(starknet_l1_provider): use client

### PR DESCRIPTION
**Pull request by giladchase**
- in batcher: replace their dummy l1 provider client with the real thing. The only effective change in behavior is that `validate` now returns an enum instead of a bool.
- changes in sequencer_node are boilerplate, did nothing different from other similar nodes.
- Added a field in the l1 config, currently unused, in order to make the
  config test pass which seems to require at least one field.

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2649)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase and @yair-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2649#-ODu7oC_-WuVGhREhbw_:-ODu7oC_-WuVGhREhbwa:bs56e9) (no related file):*
Can Batcher integration appear in its own PR?
___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2649#-ODu7I0i2SuiTII_hbI7:-ODu7I0i2SuiTII_hbI8:b-2bod8u) ([raw file](https://github.com/starkware-libs/sequencer/blob/028d969383a9384f010df7fe5fb508917572acf9/crates/starknet_integration_tests/src/config_utils.rs#L139)):*
> ```XML
>         mempool_p2p: get_disabled_component_config(),
>         state_sync: get_disabled_component_config(),
>         l1_provider: get_disabled_component_config(),
> ```

Consider alphabetizing.



_Code quote:_
```XML
l1_provider: get_disabled_component_config(),
```
___
*[`crates/starknet_batcher/src/transaction_provider.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2649#-ODu6ynQ7Gv19RrBoWPc:-ODu6ynQ7Gv19RrBoWPd:b9kaxzt) ([raw file](https://github.com/starkware-libs/sequencer/blob/028d969383a9384f010df7fe5fb508917572acf9/crates/starknet_batcher/src/transaction_provider.rs#L70)):*
> ```XML
>         &mut self,
>         n_txs: usize,
>     ) -> Result<Vec<Transaction>, TransactionProviderError> {
> ```

Define `TransactionProviderResult` type?



_Code quote:_
```XML
Result<Vec<Transaction>, TransactionProviderError>
```
___
*[`crates/starknet_sequencer_node/src/clients.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2649#-ODu7PdEA-kTIQbSq9Db:-ODu7PdEA-kTIQbSq9Dc:b-rycuod) ([raw file](https://github.com/starkware-libs/sequencer/blob/028d969383a9384f010df7fe5fb508917572acf9/crates/starknet_sequencer_node/src/clients.rs#L152)):*
> ```XML
>         match &self.l1_provider_client {
>             Some(client) => client.get_local_client(),
>             None => None,
> ```

Is there a more elegant alternative?



_Code quote:_
```XML
None => None,
```

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2649)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @yair-starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2649)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @yair-starkware)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2649)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @yair-starkware)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2649#-:-ODuyuTIAmRLoGy9Fffs:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2649)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 14 files at r1, 4 of 6 files at r2, 5 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2649#-:-OE8kME34N2rs5PI4vKA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2649)* status: 17 of 18 files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> Reviewed 2 of 19 files at r7, 17 of 17 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2649)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 15 of 17 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2649)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/starknet_sequencer_node/src/servers.rs` line 4 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2649#-OEDUknoBPKYKrSm4Hw5:-OEDUknpBBQBr_Ls9j88:bae7f37) ([raw file](https://github.com/starkware-libs/sequencer/blob/d062b7ad8300bfdc70692dfd356e8ddc75abc9e8/crates/starknet_sequencer_node/src/servers.rs#L4)):*
> ```XML
> use std::pin::Pin;
> 
> use futures::{Future, FutureExt};
> ```

Why is state sync deleted?

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2649#-:-OEEAJ977dVWyiVpyMra:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2649)* status: 15 of 19 files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/starknet_sequencer_node/src/servers.rs` line 4 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2649#-OEDUknoBPKYKrSm4Hw5:-OEDjCn2D4dy24NPPyvD:b9q7efr) ([raw file](https://github.com/starkware-libs/sequencer/blob/d062b7ad8300bfdc70692dfd356e8ddc75abc9e8/crates/starknet_sequencer_node/src/servers.rs#L4)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is state sync deleted?
</blockquote></details>

:scream: :scream: :scream: :scream: 
Thanks, bad rebase i guess.
Fixed

**Pull request merged**
