### PR TITLE
refactor(consensus): change StartRound to GetProposal and pass leader…

### PR DESCRIPTION
**Pull request by asmaastarkware**
…_fn to sm from shc

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/63)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/63)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/63#-O2dc6U7CzozcjUqHtZ0:-O2dc6U7CzozcjUqHtZ1:b-vqz38s) ([raw file](https://github.com/starkware-libs/sequencer/blob/e61a835176a662f42502a38b804126a0a27c499b/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L21)):*
> ```XML
> fn events_arrive_in_ideal_order(is_proposer: bool) {
>     let mut state_machine = StateMachine::new(*VALIDATOR_ID, 4);
>     let leader_fn = |_: Round| *VALIDATOR_ID;
> ```

One of these should depend on `is_proposer`. The way you set it up now we are always the leader.



_Code quote:_
```XML
    let mut state_machine = StateMachine::new(*VALIDATOR_ID, 4);
    let leader_fn = |_: Round| *VALIDATOR_ID;
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/63#-O2dcGTq9jDFB5whFesL:-O2dcGTr7AH23jqE5sLf:b-89pfku) ([raw file](https://github.com/starkware-libs/sequencer/blob/e61a835176a662f42502a38b804126a0a27c499b/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L55)):*
> ```XML
>     let mut state_machine = StateMachine::new(*VALIDATOR_ID, 4);
> 
>     let leader_fn = |_: Round| *VALIDATOR_ID;
> ```

Again this means you are the leader. The test is for the validator though, if the name wasn't clear. The validator should not output `GetProposal`



_Code quote:_
```XML
    let mut state_machine = StateMachine::new(*VALIDATOR_ID, 4);

    let leader_fn = |_: Round| *VALIDATOR_ID;
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/63)* status: all files reviewed, 3 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/63#-O2dcyguCo2tpgfidhNs:-O2dcyguCo2tpgfidhNt:b-fabxf9) ([raw file](https://github.com/starkware-libs/sequencer/blob/e61a835176a662f42502a38b804126a0a27c499b/crates/sequencing/papyrus_consensus/src/state_machine.rs#L180)):*
> ```XML
>     fn handle_get_proposal(
>         &mut self,
>         block_hash: Option<BlockHash>,
> ```

I thought we said to assert `None`. This would have prevented you from passing in `GetProposal(None)` in the tests where we are validator.



_Code quote:_
```XML
        block_hash: Option<BlockHash>,
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/63)* status: all files reviewed, 3 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/63#-O2dcyguCo2tpgfidhNs:-O2drtQV7Gj24t4B_Ka6:b-6cvd8y) ([raw file](https://github.com/starkware-libs/sequencer/blob/e61a835176a662f42502a38b804126a0a27c499b/crates/sequencing/papyrus_consensus/src/state_machine.rs#L180)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I thought we said to assert `None`. This would have prevented you from passing in `GetProposal(None)` in the tests where we are validator.
</blockquote></details>

Done. I will replace the panic with an assertion when switching block_hash to optional in all the functions
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/63#-O2dc6U7CzozcjUqHtZ0:-O2dfWCPAalP-vbVMWP-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e61a835176a662f42502a38b804126a0a27c499b/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L21)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

One of these should depend on `is_proposer`. The way you set it up now we are always the leader.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/63#-O2dcGTq9jDFB5whFesL:-O2dfZIt52Vbn1dNPKNG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e61a835176a662f42502a38b804126a0a27c499b/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L55)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Again this means you are the leader. The test is for the validator though, if the name wasn't clear. The validator should not output `GetProposal`
</blockquote></details>

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/63)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
