### PR TITLE
test(consensus): add the ability to run simulations with test receiver

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/285)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/285)* status: all files reviewed, 5 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/papyrus_config/src/converters.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3DGkWX4xsA2y74AuiX:-O3DGkWY33vBbtapBbl5:b-afu46g) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7078ca0f904f9dc87aabd49be37b2161d1e0127/crates/papyrus_config/src/converters.rs#L65)):*
> ```XML
>     let res: f64 = Deserialize::deserialize(de)?;
>     Ok(res / 100.0)
> }
> ```

The user should pass in f64 between [0-1]



_Code quote:_
```XML
/// Deserializes a percentage to f64.
pub fn deserialize_percentage_to_f64<'de, D>(de: D) -> Result<f64, D::Error>
where
    D: Deserializer<'de>,
{
    let res: f64 = Deserialize::deserialize(de)?;
    Ok(res / 100.0)
}
```
___
*[`crates/sequencing/papyrus_consensus/README.md` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3DH0mL8oehSKuqFUOp:-O3DH0mL8oehSKuqFUOq:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7078ca0f904f9dc87aabd49be37b2161d1e0127/crates/sequencing/papyrus_consensus/README.md#L19)):*
> ```Markdown
>          `--consensus.test.random_seed <RANDOM_SEED>`
>          `--consensus.test.drop_probability 0` (set to 0 for now)
>          `--consensus.test.invalid_probability <INVALID_PROBABILITY>` (entered as a percentage)
> ```





_Suggestion:_
```Markdown
(0 to 1)
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 140 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3DHje15w5-WyRMaNsX:-O3DHje15w5-WyRMaNsY:bw6yzop) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7078ca0f904f9dc87aabd49be37b2161d1e0127/crates/sequencing/papyrus_consensus/run_consensus.py#L140)):*
> ```Python
>     )
>     if enable_test_simulation:
>         cache_size, random_seed, drop_probability, invalid_probability = test_params
> ```

I think instead of using a vec we should use a struct. In fact what I suggest is to have 2 structs:
1. PapyrusArgs - all of the arguments passed to papyrus
2. SimulationArgs - all of the arguments that are only for this script
3. If there's anything that somehow doesn't fall into those 2 groups just pass them around explicitly



_Code quote:_
```Python
cache_size, random_seed, drop_probability, invalid_probability = test_params
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 152 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3DH9rDByylNlSGGK63:-O3DH9rE7oaFFDk6yrpu:bmgspqr) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7078ca0f904f9dc87aabd49be37b2161d1e0127/crates/sequencing/papyrus_consensus/run_consensus.py#L152)):*
> ```Python
>         cmd += (
>             f"--network.secret_key {SECRET_KEY} "
>             + f"2>&1 | sed -r 's/\\x1B\\[[0-9;]*[mK]//g' > {logs_dir}/validator{i}.txt"
> ```

This fixes the error which wasn't being sent to logs which you showed me? Did you make sure to test this when there were still failures?



_Code quote:_
```Python
2>&1
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 177 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3DHLYPA9qYD483MBMn:-O3DHLYPA9qYD483MBMo:bpa9u6) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7078ca0f904f9dc87aabd49be37b2161d1e0127/crates/sequencing/papyrus_consensus/run_consensus.py#L177)):*
> ```Python
>     nodes = []
> 
>     nodes.append(build_node(base_layer_node_url, data_dir, logs_dir, num_validators, 1, enable_test_simulation,test_params))  # Bootstrap
> ```

Are these lines (and at the bottom of the file) getting too long? It don't think we have an auto formatted for python in this repo.



_Code quote:_
```Python
    nodes.append(build_node(base_layer_node_url, data_dir, logs_dir, num_validators, 1, enable_test_simulation,test_params))  # Bootstrap
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/285)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/papyrus_config/src/converters.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3DGkWX4xsA2y74AuiX:-O3R-E9o4qaGDLLjN5uP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7078ca0f904f9dc87aabd49be37b2161d1e0127/crates/papyrus_config/src/converters.rs#L65)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

The user should pass in f64 between [0-1]
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/README.md` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3DH0mL8oehSKuqFUOp:-O3R-Ew7DT4UGWSbPxuh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7078ca0f904f9dc87aabd49be37b2161d1e0127/crates/sequencing/papyrus_consensus/README.md#L19)):*
> ```Markdown
>          `--consensus.test.random_seed <RANDOM_SEED>`
>          `--consensus.test.drop_probability 0` (set to 0 for now)
>          `--consensus.test.invalid_probability <INVALID_PROBABILITY>` (entered as a percentage)
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 140 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3DHje15w5-WyRMaNsX:-O3R-FWO33iJOg8rfaqE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7078ca0f904f9dc87aabd49be37b2161d1e0127/crates/sequencing/papyrus_consensus/run_consensus.py#L140)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I think instead of using a vec we should use a struct. In fact what I suggest is to have 2 structs:
1. PapyrusArgs - all of the arguments passed to papyrus
2. SimulationArgs - all of the arguments that are only for this script
3. If there's anything that somehow doesn't fall into those 2 groups just pass them around explicitly
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 152 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3DH9rDByylNlSGGK63:-O3R-HIP0x26735kV-L2:b2nign6) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7078ca0f904f9dc87aabd49be37b2161d1e0127/crates/sequencing/papyrus_consensus/run_consensus.py#L152)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This fixes the error which wasn't being sent to logs which you showed me? Did you make sure to test this when there were still failures?
</blockquote></details>

yes
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 177 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3DHLYPA9qYD483MBMn:-O3R-mPe7VVQtdXBXyJo:b-y2yg1l) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7078ca0f904f9dc87aabd49be37b2161d1e0127/crates/sequencing/papyrus_consensus/run_consensus.py#L177)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Are these lines (and at the bottom of the file) getting too long? It don't think we have an auto formatted for python in this repo.
</blockquote></details>

Done. I am using black python formatter

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/285)* status: all files reviewed, 6 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/papyrus_config/src/converters.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3DGkWX4xsA2y74AuiX:-O3RfrhTA-BwjAvQEW9-:b-htlfai) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7078ca0f904f9dc87aabd49be37b2161d1e0127/crates/papyrus_config/src/converters.rs#L65)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why do you need this function? Does serde not support `f64` out of the box? I don't see a special converter for `u64`.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 140 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3DHje15w5-WyRMaNsX:-O3RfiwcBQWc4U0l__XA:bcni94m) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7078ca0f904f9dc87aabd49be37b2161d1e0127/crates/sequencing/papyrus_consensus/run_consensus.py#L140)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I commented below on the naming. Remember to change the variable names to match whatever new class name we use.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 200 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3Recfs7ua1adphUzb6:-O3Recfs7ua1adphUzb7:bndwcbo) ([raw file](https://github.com/starkware-libs/sequencer/blob/43092ff69b05a5dcf4eb1f04c30423e5086f689d/crates/sequencing/papyrus_consensus/run_consensus.py#L200)):*
> ```Python
> 
> 
> class SimulationArgs:
> ```

These names aren't meaningful to me. I would have thought the opposite
- SimulationArgs configures how we run the simulation
- ConsesusArgs configures how the node runs consensus.

Let's call the arguments that are passed to Papyrus `PapyrusArgs` I think that will be unambiguous. Maybe we can call the args that are just for this script `RunConsensusArgs` since that's the name of the file. Maybe that will be clearer.



_Code quote:_
```Python
class ConsensusArgs:
    def __init__(self, num_validators, db_dir, stagnation_threshold, duration):
        self.num_validators = num_validators
        self.db_dir = db_dir
        self.stagnation_threshold = stagnation_threshold
        self.duration = duration


class SimulationArgs:
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 208 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3Rf1APD70Na0Yncw2V:-O3Rf1APD70Na0Yncw2W:b8zx673) ([raw file](https://github.com/starkware-libs/sequencer/blob/43092ff69b05a5dcf4eb1f04c30423e5086f689d/crates/sequencing/papyrus_consensus/run_consensus.py#L208)):*
> ```Python
> 
> 
> def main(base_layer_node_url, consensus_args, simulation_args):
> ```

Why is this not included in `PapyrusArgs`?



_Code quote:_
```Python
base_layer_node_url
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 277 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3RfNZH-viUq6lDOPtI:-O3RfNZH-viUq6lDOPtJ:b-lphkf9) ([raw file](https://github.com/starkware-libs/sequencer/blob/43092ff69b05a5dcf4eb1f04c30423e5086f689d/crates/sequencing/papyrus_consensus/run_consensus.py#L277)):*
> ```Python
>         required=False,
>         help="Enable test simulation in the consensus configuration.",
>     )
> ```

Do we need this? Meaning if the user doesn't specify a drop/invalid rate they default to 0, which means that the test network receiver acts like the normal network receiver.



_Code quote:_
```Python
    parser.add_argument(
        "--enable_test_simulation",
        type=bool,
        required=False,
        help="Enable test simulation in the consensus configuration.",
    )
```
___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 130 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3RgMPS17IvVbfv4OBb:-O3RgMPS17IvVbfv4OBc:b-t47lr2) ([raw file](https://github.com/starkware-libs/sequencer/blob/43092ff69b05a5dcf4eb1f04c30423e5086f689d/crates/sequencing/papyrus_consensus/src/config.rs#L130)):*
> ```XML
>             ser_param(
>                 "invalid_probability",
>                 &self.invalid_probability.to_string(),
> ```

There's no default way to display a float? I would have thought it to be like `random_seed` above.



_Code quote:_
```XML
&self.invalid_probability.to_string(),
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/285)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 183 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3WH_tV41PU1fq6hcwU:-O3WH_tW0rlUSUq6fief:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/20186068da30e437ee570ad5f22b761dd9bc0345/crates/sequencing/papyrus_consensus/run_consensus.py#L183)):*
> ```Python
> 
> 
> class PapyrusArgs:
> ```





_Suggestion:_
```Python
# Args passed to the test script that are forwarded to the node.
class PapyrusArgs:
```
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 203 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3WHfxYDxN959cQG_tn:-O3WHfxYDxN959cQG_to:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/20186068da30e437ee570ad5f22b761dd9bc0345/crates/sequencing/papyrus_consensus/run_consensus.py#L203)):*
> ```Python
> 
> 
> class RunConsensusArgs:
> ```





_Suggestion:_
```Python
# Args passed to the script that are not forwarded to the node.
class RunConsensusArgs:
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/285)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 183 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3WH_tV41PU1fq6hcwU:-O3Wb_P757UQMC_4q8MN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/20186068da30e437ee570ad5f22b761dd9bc0345/crates/sequencing/papyrus_consensus/run_consensus.py#L183)):*
> ```Python
> 
> 
> class PapyrusArgs:
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/run_consensus.py` line 203 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/285#-O3WHfxYDxN959cQG_tn:-O3Wbb3L6HjD3VVCgYy-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/20186068da30e437ee570ad5f22b761dd9bc0345/crates/sequencing/papyrus_consensus/run_consensus.py#L203)):*
> ```Python
> 
> 
> class RunConsensusArgs:
> ```

Done.

**Review by matan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/285#-:-O3gSHRN5GIIP1v1N0yE:bnfp4nl)* status: 12 of 14 files reviewed, all discussions resolved

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/285)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
