### PR TITLE
refactor(mempool): rename tx queue methods

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/570)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/570)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/570#-O57xtYKAmWpTLFJX4Tx:-O57xtYKAmWpTLFJX4Ty:bobkrsa) ([raw file](https://github.com/starkware-libs/sequencer/blob/28306f077093065b5834acbca904f9fb69ff0936/crates/mempool/src/transaction_queue.rs#L13)):*
> ```XML
> pub struct TransactionQueue {
>     // ready queue of transactions with associated priority.
>     ready_queue: BTreeSet<ReadyTransaction>,
> ```

Revert; I'd only go with "ready" terminology in public API.



_Code quote:_
```XML
    // ready queue of transactions with associated priority.
    ready_queue: BTreeSet<ReadyTransaction>,
```
___
*[`crates/mempool/src/transaction_queue.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/570#-O57y2hkEmwfWay39Wm0:-O57y2hkEmwfWay39Wm1:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/28306f077093065b5834acbca904f9fb69ff0936/crates/mempool/src/transaction_queue.rs#L37)):*
> ```XML
> 
>     // TODO(gilad): remove collect
>     pub fn pop_chunk_by_priority(&mut self, n_txs: usize) -> Vec<TransactionReference> {
> ```





_Suggestion:_
```XML
pop_ready_chunk
```
___
*[`crates/mempool/src/transaction_queue.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/570#-O57yW8_2ZpyCVWm-V2P:-O57yW8_2ZpyCVWm-V2Q:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/28306f077093065b5834acbca904f9fb69ff0936/crates/mempool/src/transaction_queue.rs#L66)):*
> ```XML
>     }
> 
>     pub fn is_ready_txs_exist(&self) -> bool {
> ```





_Suggestion:_
```XML
has_ready_txs
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/570)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/570#-O57xtYKAmWpTLFJX4Tx:-O58-aJY7HF0WQ4KapMs:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/28306f077093065b5834acbca904f9fb69ff0936/crates/mempool/src/transaction_queue.rs#L13)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Revert; I'd only go with "ready" terminology in public API.
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_queue.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/570#-O57y2hkEmwfWay39Wm0:-O57zk2fEISV9Xa3v4Nw:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/28306f077093065b5834acbca904f9fb69ff0936/crates/mempool/src/transaction_queue.rs#L37)):*
> ```XML
> 
>     // TODO(gilad): remove collect
>     pub fn pop_chunk_by_priority(&mut self, n_txs: usize) -> Vec<TransactionReference> {
> ```

Done.
___
*[`crates/mempool/src/transaction_queue.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/570#-O57yW8_2ZpyCVWm-V2P:-O57zrEd8jG6RcMttkY6:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/28306f077093065b5834acbca904f9fb69ff0936/crates/mempool/src/transaction_queue.rs#L66)):*
> ```XML
>     }
> 
>     pub fn is_ready_txs_exist(&self) -> bool {
> ```

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/570)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/570#-O57xtYKAmWpTLFJX4Tx:-O5808ch8G401kFEQVZ_:b-kpv00d) ([raw file](https://github.com/starkware-libs/sequencer/blob/28306f077093065b5834acbca904f9fb69ff0936/crates/mempool/src/transaction_queue.rs#L13)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Capitalise please, note changes from master in your PR.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/570)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/570#-O57xtYKAmWpTLFJX4Tx:-O585qwv-XvB4NA86fU3:b-ljo57k) ([raw file](https://github.com/starkware-libs/sequencer/blob/28306f077093065b5834acbca904f9fb69ff0936/crates/mempool/src/transaction_queue.rs#L13)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Capitalise please, note changes from master in your PR.
</blockquote></details>

Sorry, done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/570#-:-O58f12f3np-8_nUFiM0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @giladchase)

**Pull request merged**
