### PR TITLE
fix(blockifier): move max sierra_gas constants under os_constants

### PR DESCRIPTION
**Pull request by TzahiTaub**

### CODE REVIEW

**Comment by TzahiTaub** [comment]
* **#2908** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2908?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2908?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2908)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @TzahiTaub)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2908#-OErqHQo0sSSyMLqW6CD:-OErqHQp2Vhg0uf4OO5z:b-hpftsn) (no related file):*
don't you need actual code (rust) changes for this to work?
___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2908#-OErqKwvCyjXE9idL-Ho:-OErqKwvCyjXE9idL-Hp:b-6bonui) (no related file):*
py side PR?
___
*[`crates/blockifier/resources/versioned_constants_0_13_2_1.json` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2908#-OErq8Pw3nrHcn_0BCmE:-OErq8Pw3nrHcn_0BCmF:bs0b4c7) ([raw file](https://github.com/starkware-libs/sequencer/blob/4366ef3fe1f60b28d9e88f62169c9a46b7d4af93/crates/blockifier/resources/versioned_constants_0_13_2_1.json#L12)):*
> ```JSON
>     },
>     "invoke_tx_max_n_steps": 10000000,
>     "execute_max_sierra_gas": 10000000000,
> ```

what about this?



_Code quote:_
```JSON
 "execute_max_sierra_gas": 10000000000,
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2908)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @TzahiTaub)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2908#-OEsK0qT0TF8bdcOijJH:-OEsK0qT0TF8bdcOijJI:bpbja99) (no related file):*
rebase over `main-v0.13.4`

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2908)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2908#-OErqHQo0sSSyMLqW6CD:-OEs2z_iCr95jkDZvfVw:bhjirdd) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't you need actual code (rust) changes for this to work?
</blockquote></details>

Yep :)
Nice attempt for changes in the middle of the night
___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2908#-OEsK0qT0TF8bdcOijJH:-OEsQs6KBNomLObua34a:b-896fix) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

rebase over `main-v0.13.4`
</blockquote></details>

Done.
___
*[`crates/blockifier/resources/versioned_constants_0_13_2_1.json` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2908#-OErq8Pw3nrHcn_0BCmE:-OEs0yWK7t_4UmPOgGRq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4366ef3fe1f60b28d9e88f62169c9a46b7d4af93/crates/blockifier/resources/versioned_constants_0_13_2_1.json#L12)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what about this?
</blockquote></details>

Done.

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2908)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2908#-OErqKwvCyjXE9idL-Ho:-OEsiTMJACcx2ePKAk_T:bnqvqy9) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

py side PR?
</blockquote></details>

https://reviewable.io/reviews/starkware-industries/starkware/36532

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2908)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 802 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2908#-OEs_hTW3aiKBdptpXnB:-OEsjtK7DTeydza0Vs39:bf8n0tj) ([raw file](https://github.com/starkware-libs/sequencer/blob/0dfdc6f2cfc1ea90529fcde4d901c066bea2a1c7/crates/blockifier/src/versioned_constants.rs#L802)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

here, and in the other `expect`, I would prefer you just add a variant to the `OsConstantsSerdeError` enum and use `?`
</blockquote></details>

OK, but note we do use `unwrap` for other fields ATM.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2908)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/versioned_constants.rs` line 802 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2908#-OEs_hTW3aiKBdptpXnB:-OEsm9hk4uddwnYZznJh:bmezkb) ([raw file](https://github.com/starkware-libs/sequencer/blob/0dfdc6f2cfc1ea90529fcde4d901c066bea2a1c7/crates/blockifier/src/versioned_constants.rs#L802)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

OK, but note we do use `unwrap` for other fields ATM.
</blockquote></details>

not in this `try_from`

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2908)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 802 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2908#-OEs_hTW3aiKBdptpXnB:-OEvTOBA3rUH6Cq4feTX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0dfdc6f2cfc1ea90529fcde4d901c066bea2a1c7/crates/blockifier/src/versioned_constants.rs#L802)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not in this `try_from`
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2908)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/versioned_constants.rs` line 810 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2908#-OEx-HQS8ghRNwH4Yv4P:-OEx-HQS8ghRNwH4Yv4Q:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c55d2049360d9b141d30dde877ea60bac4ea979f/crates/blockifier/src/versioned_constants.rs#L810)):*
> ```XML
>             raw_json_data
>                 .raw_json_file_as_dict
>                 .get("execute_max_sierra_gas")
> ```





_Suggestion:_
```XML
.get(key)
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2908)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 810 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2908#-OEx-HQS8ghRNwH4Yv4P:-OEx0Cgu0r8VRasbsGfu:b-wqtjmp) ([raw file](https://github.com/starkware-libs/sequencer/blob/c55d2049360d9b141d30dde877ea60bac4ea979f/crates/blockifier/src/versioned_constants.rs#L810)):*
> ```XML
>             raw_json_data
>                 .raw_json_file_as_dict
>                 .get("execute_max_sierra_gas")
> ```

:( Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2908#-:-OEx0snd1m1BwlTJLarN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
