### PR TITLE
fix(mempool): bug fix in mempool input validation

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1231)

### CODE REVIEW

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1231)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 398 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1231#-O8b523BBqyotYEjLRkl:-O8b523BBqyotYEjLRkm:b-k3oa4l) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeab3b6f2c7d0aab2239772cfa86f7cbb7e0055f/crates/mempool/src/mempool_test.rs#L398)):*
> ```XML
>     // Setup.
>     let input = add_tx_input!(tx_hash: 1, tx_nonce: 1, account_nonce: 0);
>     let duplicate_input = input.clone(); // Same hash is possible if signature is different.
> ```

Isn't the signature default here? How is it being generated?



_Code quote:_
```XML
signature
```
___
*[`crates/mempool/tests/flow_test.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1231#-O8b5nOQCB_qVWomKNt6:-O8b5nOQCB_qVWomKNt7:brn0hi0) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeab3b6f2c7d0aab2239772cfa86f7cbb7e0055f/crates/mempool/tests/flow_test.rs#L83)):*
> ```XML
> 
>     let tx_nonce_5_account_nonce_5 =
>         add_tx_input!(tx_hash: 2, sender_address: "0x0", tx_nonce: 5, account_nonce: 5);
> ```

should be 4,4?



_Code quote:_
```XML
tx_nonce: 5, account_nonce: 5);
```
___
*[`crates/mempool/tests/flow_test.rs` line 89 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1231#-O8b5eM47U1CU-dYBS7q:-O8b5eM47U1CU-dYBS7r:b-87xulx) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeab3b6f2c7d0aab2239772cfa86f7cbb7e0055f/crates/mempool/tests/flow_test.rs#L89)):*
> ```XML
>         &mut mempool,
>         2,
>         &[tx_nonce_5_account_nonce_5.tx, tx_nonce_5_account_nonce_3.tx],
> ```

it's the same tx



_Code quote:_
```XML
&[tx_nonce_5_account_nonce_5.tx, tx_nonce_5_account_nonce_3.tx],
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1231)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 398 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1231#-O8b523BBqyotYEjLRkl:-O8b62w3D4iOh3UYDPd_:b-u0b9md) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeab3b6f2c7d0aab2239772cfa86f7cbb7e0055f/crates/mempool/src/mempool_test.rs#L398)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Isn't the signature default here? How is it being generated?
</blockquote></details>

This is a lie here, I don't want to add a cumbersome variant to the macro, so only explaining to the reader.
___
*[`crates/mempool/tests/flow_test.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1231#-O8b5nOQCB_qVWomKNt6:-O8b69Cc0MFg2VWc1li1:bawzdrh) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeab3b6f2c7d0aab2239772cfa86f7cbb7e0055f/crates/mempool/tests/flow_test.rs#L83)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

should be 4,4?
</blockquote></details>

No, commit advances nonce to `nonce_in_diff + 1`.
___
*[`crates/mempool/tests/flow_test.rs` line 89 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1231#-O8b5eM47U1CU-dYBS7q:-O8b6J0P3bO8Sc-T2mdJ:b-83og3x) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeab3b6f2c7d0aab2239772cfa86f7cbb7e0055f/crates/mempool/tests/flow_test.rs#L89)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

it's the same tx
</blockquote></details>

Nope.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1231)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/tests/flow_test.rs` line 89 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1231#-O8b5eM47U1CU-dYBS7q:-O8b6yf53E2CTunK6mA3:b-rst3ay) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeab3b6f2c7d0aab2239772cfa86f7cbb7e0055f/crates/mempool/tests/flow_test.rs#L89)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Nope.
</blockquote></details>

Sorry, fixed.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1231)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/tests/flow_test.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1231#-O8b5nOQCB_qVWomKNt6:-O8b74-PDMBSuXO9sc-I:b-j6uz3i) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeab3b6f2c7d0aab2239772cfa86f7cbb7e0055f/crates/mempool/tests/flow_test.rs#L83)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No, commit advances nonce to `nonce_in_diff + 1`.
</blockquote></details>

Sorry, fixed here too.
Got confused over a rebase.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1231)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/tests/flow_test.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1231#-O8bJymC8KKmNOyP8eHk:-O8eelwZ86q48MS8bL_Z:b-v7c4r5) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6732861b0bb6e23c661a250a45bada89848e496/crates/mempool/tests/flow_test.rs#L79)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Isn't the scenario here that a transaction with nonce 3 is accepted, a transaction with nonce 4 is not included in the block, so it should be sent again, and then transactions with nonces 4 and 5 should be returned?
</blockquote></details>

Reverted, check out the case I added in the appropriate unit test.

**Pull request merged**
