### PR TITLE
chore: fix clippy for version 0.1.81

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Review by dan-starkware — APPROVED** [review]
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2365)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2365#-:-OD0EUyx-QzaJhZrN9_-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2365)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2365)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`.github/workflows/papyrus_docker-publish.yml` line 84 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2365#-OD0PBKE7ZmUSKNEOYSS:-OD0PBKE7ZmUSKNEOYST:bo5bk4r) ([raw file](https://github.com/starkware-libs/sequencer/blob/b5673b652bb061a88cff3441892e8dcfdc414828/.github/workflows/papyrus_docker-publish.yml#L84)):*
> ```YAML
>           labels: ${{ steps.meta.outputs.labels }}
>           cache-from: type=gha
>           cache-to: type=gha,mode=max -->
> ```

blocking until reverted..



_Code quote:_
```YAML
  <!-- docker-build-push:
    runs-on: starkware-ubuntu-latest-large

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Not required but recommended - enables build multi-platform images, export cache, etc
      # Also workaround for: https://github.com/docker/build-push-action/issues/461
      # https://github.com/docker/setup-buildx-action
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.2.1

      # Login to a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Login to registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/papyrus
          tags: |
            type=semver,pattern={{raw}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=pr
            # set `dev` tag for the default branch (`main`).
            type=raw,value=dev,enable={{is_default_branch}}
            type=raw,value={{branch}}{{tag}}-{{sha}},enable=${{ github.event_name == 'workflow_dispatch' }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: deployments/images/papyrus/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max -->
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2365)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2365#-OD0QD5RBLxb6agDhnGT:-OD0QD5RBLxb6agDhnGU:b-66ert4) (no related file):*
this command works locally for me:
```
cargo build --release --package papyrus_node
```
my wild guess would be: need to purge the docker cache to reinstall the rust toolchain
dunno how, or if that even makes... just a guess

**Comment by ArniStarkware** [comment]
This PR is a replica of #2371, except for one difference. This PR includes a disable of one part of the CI.

**Pull request closed without merging**
