### PR TITLE
refactor(papyrus_storage): add an events table and a corresponding file handler

### PR DESCRIPTION
**Pull request by AlonLStarkWare**

### CODE REVIEW

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2896)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @DvirYo-starkware and @ShahakShama)

___
*[`crates/papyrus_storage/src/lib.rs` line 683 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2896#-OEmyAR-3lxbTkT3UM3x:-OEmyAR-3lxbTkT3UM3y:bcwjv8m) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7c9b9f376c653d53ae1bf68c684f80bb7d375c5/crates/papyrus_storage/src/lib.rs#L683)):*
> ```XML
>     transaction_output: FileHandler<VersionZeroWrapper<TransactionOutput>, Mode>,
>     transaction: FileHandler<VersionZeroWrapper<Transaction>, Mode>,
>     events: FileHandler<VersionZeroWrapper<Vec<Event>>, Mode>, /* Should this point to the
> ```

I think the file handler should point to the events of a single transaction, but I think it can be changed to point to an entire block
___
*[`crates/papyrus_storage/src/lib.rs` line 738 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2896#-OEmyfG10W0JZWnGBTky:-OEmyfG10W0JZWnGBTkz:bwhauqh) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7c9b9f376c653d53ae1bf68c684f80bb7d375c5/crates/papyrus_storage/src/lib.rs#L738)):*
> ```XML
>         self.transaction_output.flush();
>         self.transaction.flush();
>         self.events.flush(); // make sure we need this
> ```

Is this needed?
___
*[`crates/papyrus_storage/src/lib.rs` line 752 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2896#-OEmyh9NA-XXJ3WfjGht:-OEmyh9NA-XXJ3WfjGhu:bwhauqh) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7c9b9f376c653d53ae1bf68c684f80bb7d375c5/crates/papyrus_storage/src/lib.rs#L752)):*
> ```XML
>             ("transaction_output".to_string(), self.transaction_output.stats()),
>             ("transaction".to_string(), self.transaction.stats()),
>             ("events".to_string(), self.events.stats()), // make sure we need this
> ```

Is this needed?
___
*[`crates/papyrus_storage/src/lib.rs` line 909 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2896#-OEmyk55-Yrwqx-7aWb5:-OEmyk569MFX9GsxzSdI:b-vn4x54) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7c9b9f376c653d53ae1bf68c684f80bb7d375c5/crates/papyrus_storage/src/lib.rs#L909)):*
> ```XML
>     Transaction,
>     /// An events file.
>     Events,
> ```

Event or Events?
Because the offset kind is used to create the FileHandler, which (currently) addresses the events of a transaction, I think it should be Events.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2896)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @AlonLStarkWare and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 738 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2896#-OEmyfG10W0JZWnGBTky:-OEs3wwBEjz3_-pe9nca:b-cecmla) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7c9b9f376c653d53ae1bf68c684f80bb7d375c5/crates/papyrus_storage/src/lib.rs#L738)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

Is this needed?
</blockquote></details>

yes. Erase the comment
___
*[`crates/papyrus_storage/src/lib.rs` line 752 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2896#-OEmyh9NA-XXJ3WfjGht:-OEs45SN4aLIhloCBj2S:bpydaa) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7c9b9f376c653d53ae1bf68c684f80bb7d375c5/crates/papyrus_storage/src/lib.rs#L752)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

Is this needed?
</blockquote></details>

Yes. Erase the comment
___
*[`crates/papyrus_storage/src/lib.rs` line 909 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2896#-OEmyk55-Yrwqx-7aWb5:-OEs4XIaC7YZ-fb7Hj2s:b-wlo8ps) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7c9b9f376c653d53ae1bf68c684f80bb7d375c5/crates/papyrus_storage/src/lib.rs#L909)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

Event or Events?
Because the offset kind is used to create the FileHandler, which (currently) addresses the events of a transaction, I think it should be Events.
</blockquote></details>

Looks like the convention in file handlers to use non-plural version. Rename this to Event and also rename the member in FileHandlers
___
*[`crates/papyrus_storage/src/lib.rs` line 683 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2896#-OEs3oA3AqQ4wA7h-Isu:-OEs3oA3AqQ4wA7h-Isv:b-kxu7v0) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7c9b9f376c653d53ae1bf68c684f80bb7d375c5/crates/papyrus_storage/src/lib.rs#L683)):*
> ```XML
>     transaction_output: FileHandler<VersionZeroWrapper<TransactionOutput>, Mode>,
>     transaction: FileHandler<VersionZeroWrapper<Transaction>, Mode>,
>     events: FileHandler<VersionZeroWrapper<Vec<Event>>, Mode>, /* Should this point to the
> ```

Remove this comment

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2896)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware and @ShahakShama)

___
*[`crates/papyrus_storage/src/lib.rs` line 683 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2896#-OEs3oA3AqQ4wA7h-Isu:-OExwqV-DERLuInINMFP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7c9b9f376c653d53ae1bf68c684f80bb7d375c5/crates/papyrus_storage/src/lib.rs#L683)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this comment
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/lib.rs` line 909 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2896#-OEmyk55-Yrwqx-7aWb5:-OExwoE7Av-JcZBjubzj:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7c9b9f376c653d53ae1bf68c684f80bb7d375c5/crates/papyrus_storage/src/lib.rs#L909)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Looks like the convention in file handlers to use non-plural version. Rename this to Event and also rename the member in FileHandlers
</blockquote></details>

Done

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2896#-:-OF295qlBbeizr_aErGy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Pull request merged**
