### PR TITLE
test: add build proposal step to end_to_end test

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1386)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1386?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1386** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1386?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1352** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1352?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1386?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1386** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1386?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1352** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1352?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1386)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @ArniStarkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1386#-O99stvC4bKcnWv3jZvm:-O99stvC4bKcnWv3jZvn:ba1niye) ([raw file](https://github.com/starkware-libs/sequencer/blob/87a49477a49b029e689c56420f7093007b4e09d9/crates/tests-integration/tests/end_to_end_test.rs#L66)):*
> ```XML
> 
>     // Set start height.
>     // TODO(Arni): Get the current height from the mock_running_system object.
> ```

Rethinking this - get this from the rpc storage



_Code quote:_
```XML
// TODO(Arni): Get the current height from the mock_running_system object.
```
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1386#-O99sZ7V-V9FA_AXPht7:-O99sZ7V-V9FA_AXPht8:b-eilgcb) ([raw file](https://github.com/starkware-libs/sequencer/blob/87a49477a49b029e689c56420f7093007b4e09d9/crates/tests-integration/tests/end_to_end_test.rs#L79)):*
> ```XML
>         .build_proposal(BuildProposalInput {
>             proposal_id,
>             deadline: chrono::Utc::now() + chrono::TimeDelta::new(1, 0).unwrap(),
> ```

Use const



_Code quote:_
```XML
chrono::TimeDelta::new(1, 0).
```
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1386#-O99siAx83y-Zbrvo7xH:-O99siAx83y-Zbrvo7xI:b-dmhgtu) ([raw file](https://github.com/starkware-libs/sequencer/blob/87a49477a49b029e689c56420f7093007b4e09d9/crates/tests-integration/tests/end_to_end_test.rs#L80)):*
> ```XML
>             proposal_id,
>             deadline: chrono::Utc::now() + chrono::TimeDelta::new(1, 0).unwrap(),
>             retrospective_block_hash: None,
> ```

Get this from the rpc storage



_Code quote:_
```XML
 None
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1386)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1386#-O99stvC4bKcnWv3jZvm:-O99ydBQ4xwEWsdf87na:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/87a49477a49b029e689c56420f7093007b4e09d9/crates/tests-integration/tests/end_to_end_test.rs#L66)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Rethinking this - get this from the rpc storage
</blockquote></details>

Done.
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1386#-O99sZ7V-V9FA_AXPht7:-O9A4han8CuWbsG3rVlp:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/87a49477a49b029e689c56420f7093007b4e09d9/crates/tests-integration/tests/end_to_end_test.rs#L79)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Use const
</blockquote></details>

Done.
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1386#-O99siAx83y-Zbrvo7xH:-O99ybXS4kcRcY3OHg9R:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/87a49477a49b029e689c56420f7093007b4e09d9/crates/tests-integration/tests/end_to_end_test.rs#L80)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Get this from the rpc storage
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1386#-:-O9FICSlATmxe0vAgyar:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
