### PR TITLE
build(blockifier): add l2_gas_price and refactor

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/322)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/322)* status: all files reviewed, 10 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier/src/blockifier/block.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bWPB_0GhBimVll2lV:-O3bWPB_0GhBimVll2lW:b-i5kn9e) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/blockifier/block.rs#L17)):*
> ```XML
> #[path = "block_test.rs"]
> pub mod block_test;
> pub const L2_GAS_FOR_CAIRO_STEP: u128 = 100;
> ```

I think you should take this value from [here](https://github.com/starkware-libs/sequencer/blob/main/crates/blockifier/resources/versioned_constants.json#L156) - it should be part of the versioned constants.



_Code quote:_
```XML
L2_GAS_FOR_CAIRO_STEP: u128 = 100;
```
___
*[`crates/blockifier/src/blockifier/block.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bWefY-6BB_nFtD-sM:-O3bWefY-6BB_nFtD-sN:bjzny1m) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/blockifier/block.rs#L18)):*
> ```XML
> pub mod block_test;
> pub const L2_GAS_FOR_CAIRO_STEP: u128 = 100;
> pub const CAIRO_STEPS_PER_L1_GAS: u128 = 400;
> ```

this value should be taken from `vm_resource_fee_cost`, see [here](https://github.com/starkware-libs/sequencer/blob/main/crates/blockifier/resources/versioned_constants.json#L583-L586)



_Code quote:_
```XML
CAIRO_STEPS_PER_L1_GAS: u128 = 400;
```
___
*[`crates/blockifier/src/blockifier/block.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bXDv8CXRDUZ0qSHTx:-O3bXDv9EMbHqmNNKs_3:b-wpkodj) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/blockifier/block.rs#L19)):*
> ```XML
> pub const L2_GAS_FOR_CAIRO_STEP: u128 = 100;
> pub const CAIRO_STEPS_PER_L1_GAS: u128 = 400;
> pub const L2_TO_L1_GAS_PRICE_RATIO: u128 = L2_GAS_FOR_CAIRO_STEP * CAIRO_STEPS_PER_L1_GAS;
> ```

shouldn't this be a ratio type?



_Code quote:_
```XML
L2_TO_L1_GAS_PRICE_RATIO
```
___
*[`crates/blockifier/src/blockifier/block.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bX4mm5__muDjTjfhu:-O3bX4mn4DDBS9BvLnMS:b6sic15) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/blockifier/block.rs#L21)):*
> ```XML
> pub const L2_TO_L1_GAS_PRICE_RATIO: u128 = L2_GAS_FOR_CAIRO_STEP * CAIRO_STEPS_PER_L1_GAS;
> 
> pub type L2Cost = Ratio<u128>;
> ```

no need to redefine the `ResourceCost` type



_Code quote:_
```XML
pub type L2Cost = Ratio<u128>;
```
___
*[`crates/blockifier/src/blockifier/block.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bX7MoE8hMPEuhmreT:-O3bX7MoE8hMPEuhmreU:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/blockifier/block.rs#L41)):*
> ```XML
>     strk_l1_data_gas_price: NonZeroU128, // In fri.
>     eth_l2_gas_price: L2Cost,            // In wei.
>     strk_l2_gas_price: L2Cost,           // In fri.
> ```





_Suggestion:_
```XML
    eth_l2_gas_price: ResourceCost,            // In wei.
    strk_l2_gas_price: ResourceCost,           // In fri.
```
___
*[`crates/blockifier/src/blockifier/block.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bXKXg1xpcvVSwFRwB:-O3bXKXg1xpcvVSwFRwC:bhja1gi) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/blockifier/block.rs#L62)):*
> ```XML
>         }
>     }
>     pub fn get_gas_price_by_fee_type(&self, fee_type: &FeeType) -> NonZeroU128 {
> ```

newline between function implementations



_Suggestion:_
```XML
    }
    
    pub fn get_gas_price_by_fee_type(&self, fee_type: &FeeType) -> NonZeroU128 {
```
___
*[`crates/blockifier/src/blockifier/block.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bXTw52cRnmgf7dSQZ:-O3bXTw52cRnmgf7dSQ_:b-l4xmum) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/blockifier/block.rs#L69)):*
> ```XML
>     }
> 
>     pub fn get_data_gas_price_by_fee_type(&self, fee_type: &FeeType) -> NonZeroU128 {
> ```

these should be renamed now (in a separate PR)



_Suggestion:_
```XML
    pub fn get_l1_gas_price_by_fee_type(&self, fee_type: &FeeType) -> NonZeroU128 {
        match fee_type {
            FeeType::Strk => self.strk_l1_gas_price,
            FeeType::Eth => self.eth_l1_gas_price,
        }
    }

    pub fn get_l1_data_gas_price_by_fee_type(&self, fee_type: &FeeType) -> NonZeroU128 {
```
___
*[`crates/blockifier/src/fee/fee_test.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bXYcm3PmlJPzhRdil:-O3bXYcm3PmlJPzhRdim:b-gqukf) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/fee/fee_test.rs#L124)):*
> ```XML
>     #[case] expect_failure: bool,
> ) {
>     use crate::blockifier::block::GasPrices;
> ```

move import to top



_Code quote:_
```XML
use crate::blockifier::block::GasPrices;
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bXed-0rZLAjI7k9aa:-O3bXed-0rZLAjI7k9ab:b-omx7jy) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/test_utils/struct_impls.rs#L186)):*
> ```XML
>     }
> 
>     pub fn create_for_testing_w_strk_gas_prices(
> ```

rename this function... not sure to what, but (a) please don't use single-letter abbreviations and (b) what does `strk` have to do with this function? both eth and strk appear in the inputs.

better yet, delete this function completely - instead of passing `None` just use `new` and pass the defaults explicitly



_Code quote:_
```XML
create_for_testing_w_strk_gas_prices
```
___
*[`crates/papyrus_execution/src/objects.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bYWen0W250LpcYOaN:-O3bYWen0W250LpcYOaO:bg01ks7) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/papyrus_execution/src/objects.rs#L164)):*
> ```XML
>         PriceUnit::Wei => FeeType::Eth,
>         PriceUnit::Fri => FeeType::Strk,
>     };
> ```

what is `PriceUnit`?
how about adding `impl From<PriceUnit> for FeeType`? seems natural, and removes the need for this preceding `match` (just do `price_unit.into()`)



_Code quote:_
```XML
    let fee_type = match tx_execution_output.price_unit {
        PriceUnit::Wei => FeeType::Eth,
        PriceUnit::Fri => FeeType::Strk,
    };
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 5 of 14 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/322)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware)

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/322)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/blockifier/block.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bXDv8CXRDUZ0qSHTx:-O3bq_qPCcym75jdiFFt:b4h80iu) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/blockifier/block.rs#L19)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

shouldn't this be a ratio type?
</blockquote></details>

How can I create a `const` ratio type?
___
*[`crates/blockifier/src/blockifier/block.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bX4mm5__muDjTjfhu:-O3bpkDN7rp7IDdDuNSf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/blockifier/block.rs#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no need to redefine the `ResourceCost` type
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/block.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bX7MoE8hMPEuhmreT:-O3bpjBs6KgCZtn1ONq6:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/blockifier/block.rs#L41)):*
> ```XML
>     strk_l1_data_gas_price: NonZeroU128, // In fri.
>     eth_l2_gas_price: L2Cost,            // In wei.
>     strk_l2_gas_price: L2Cost,           // In fri.
> ```

Done.
___
*[`crates/blockifier/src/blockifier/block.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bXKXg1xpcvVSwFRwB:-O3by8uHAWG_7qKknMHQ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/blockifier/block.rs#L62)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

newline between function implementations
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/block.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bXTw52cRnmgf7dSQZ:-O3bxwml6dBwJDEoVDh-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/blockifier/block.rs#L69)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

these should be renamed now (in a separate PR)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/fee_test.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bXYcm3PmlJPzhRdil:-O3bpVVq5vVL3bbyZ_BV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/fee/fee_test.rs#L124)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move import to top
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bXed-0rZLAjI7k9aa:-O3bsapX2fR8xTi19uO4:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/test_utils/struct_impls.rs#L186)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

rename this function... not sure to what, but (a) please don't use single-letter abbreviations and (b) what does `strk` have to do with this function? both eth and strk appear in the inputs.

better yet, delete this function completely - instead of passing `None` just use `new` and pass the defaults explicitly
</blockquote></details>

Done.
___
*[`crates/papyrus_execution/src/objects.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bYWen0W250LpcYOaN:-O3bxufx9RZwAHorDw2s:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/papyrus_execution/src/objects.rs#L164)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what is `PriceUnit`?
how about adding `impl From<PriceUnit> for FeeType`? seems natural, and removes the need for this preceding `match` (just do `price_unit.into()`)
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/322)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier/src/blockifier/block.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bXDv8CXRDUZ0qSHTx:-O3cBDm3CEEK_sLOJhq5:bmkme7d) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/blockifier/block.rs#L19)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

How can I create a `const` ratio type?
</blockquote></details>

hmmm... maybe the type of the `const` should be `[u128; 2]`, and you should convert it to a `Ratio<u128>` at runtime?

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/322)* status: 6 of 15 files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/blockifier/block.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bWPB_0GhBimVll2lV:-O4JXsbGB9bGwMFqpoX1:b-riaacg) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/blockifier/block.rs#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think you should take this value from [here](https://github.com/starkware-libs/sequencer/blob/main/crates/blockifier/resources/versioned_constants.json#L156) - it should be part of the versioned constants.
</blockquote></details>

Done. Now using a function (until next PR, where it's changed to receiving it from python)
___
*[`crates/blockifier/src/blockifier/block.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bWefY-6BB_nFtD-sM:-O4JXt0p3XeK658FETlE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/blockifier/block.rs#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this value should be taken from `vm_resource_fee_cost`, see [here](https://github.com/starkware-libs/sequencer/blob/main/crates/blockifier/resources/versioned_constants.json#L583-L586)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/block.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O3bXDv8CXRDUZ0qSHTx:-O4JXtcL49gO65Q_PEOg:b-r1idmi) ([raw file](https://github.com/starkware-libs/sequencer/blob/6521a07e7bb80d95528f4376a72f1bf2dba7aa6c/crates/blockifier/src/blockifier/block.rs#L19)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

hmmm... maybe the type of the `const` should be `[u128; 2]`, and you should convert it to a `Ratio<u128>` at runtime?
</blockquote></details>

I guess if it's taken from the file, it can't be a `const`.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r6, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/322)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 130 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O4K2igL-h-032VPegSo:-O4K2igL-h-032VPegSp:b-27veyy) ([raw file](https://github.com/starkware-libs/sequencer/blob/e45b885be8042a4e46c18cb01bece5e708584dc7/crates/blockifier/src/versioned_constants.rs#L130)):*
> ```XML
>     pub fn l1_to_l2_gas_price_conversion(l1_gas_price: u128) -> u128 {
>         let versioned_constants = Self::latest_constants();
>         let l1_to_l2_gas_price_ratio: Ratio<u128> = Ratio::new(
> ```

don't get the latest constants: call this as a method please.
the actual versioned constants used at runtime should be configurable



_Suggestion:_
```XML
    /// Converts from l1 gas cost to l2 gas cost with **upward rounding**
    pub fn l1_to_l2_gas_price_conversion(&self, l1_gas_price: u128) -> u128 {
        let l1_to_l2_gas_price_ratio: Ratio<u128> = Ratio::new(
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 134 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O4K2Pq97044ENciwvhk:-O4K2Pq97044ENciwvhl:b1uasme) ([raw file](https://github.com/starkware-libs/sequencer/blob/e45b885be8042a4e46c18cb01bece5e708584dc7/crates/blockifier/src/versioned_constants.rs#L134)):*
> ```XML
>             std::convert::Into::<u128>::into(
>                 versioned_constants.os_constants.gas_costs.step_gas_cost,
>             ),
> ```

isn't this equivalent?
or just `.into()` without the `u128::from(...)`?



_Suggestion:_
```XML
            u128::from(versioned_constants.os_constants.gas_costs.step_gas_cost),
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 138 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O4K31KsCCtmaeacIdIl:-O4K31KsCCtmaeacIdIm:b-cipid9) ([raw file](https://github.com/starkware-libs/sequencer/blob/e45b885be8042a4e46c18cb01bece5e708584dc7/crates/blockifier/src/versioned_constants.rs#L138)):*
> ```XML
>             ["n_steps"];
>         (l1_gas_price * l1_to_l2_gas_price_ratio.numer())
>             .div_ceil(*l1_to_l2_gas_price_ratio.denom())
> ```

doesn't `Ratio` support multiplication by u128? and has it's own "round up" method? I don't think you need to call `numer` and `denom` explicitly here



_Code quote:_
```XML
        (l1_gas_price * l1_to_l2_gas_price_ratio.numer())
            .div_ceil(*l1_to_l2_gas_price_ratio.denom())
```
___
*[`crates/blockifier/src/blockifier/block.rs` line 49 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O4K3dm24CUk8eROZQh5:-O4K3dm24CUk8eROZQh6:b8gpe98) ([raw file](https://github.com/starkware-libs/sequencer/blob/e45b885be8042a4e46c18cb01bece5e708584dc7/crates/blockifier/src/blockifier/block.rs#L49)):*
> ```XML
>             eth_l1_gas_price.into(),
>         ))
>         .unwrap();
> ```

no `unwrap` in business logic; use `expect` if you need to



_Code quote:_
```XML
.unwrap();
```
___
*[`crates/blockifier/src/blockifier/block.rs` line 53 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O4K3PxK2-tAfdjpKYeD:-O4K3PxK2-tAfdjpKYeE:btq6rzh) ([raw file](https://github.com/starkware-libs/sequencer/blob/e45b885be8042a4e46c18cb01bece5e708584dc7/crates/blockifier/src/blockifier/block.rs#L53)):*
> ```XML
>             VersionedConstants::l1_to_l2_gas_price_conversion(strk_l1_gas_price.into()),
>         )
>         .unwrap();
> ```

the problem with this is that you implicitly assume the "latest" versioned constants are used; we shouldn't assume this.
either get the versioned constants as input, or get the L2 gas price(s) as explicit input..



_Code quote:_
```XML
    pub fn new(
        eth_l1_gas_price: NonZeroU128,
        strk_l1_gas_price: NonZeroU128,
        eth_l1_data_gas_price: NonZeroU128,
        strk_l1_data_gas_price: NonZeroU128,
    ) -> Self {
        let eth_l2_gas_price = NonZeroU128::new(VersionedConstants::l1_to_l2_gas_price_conversion(
            eth_l1_gas_price.into(),
        ))
        .unwrap();
        let strk_l2_gas_price = NonZeroU128::new(
            VersionedConstants::l1_to_l2_gas_price_conversion(strk_l1_gas_price.into()),
        )
        .unwrap();
```
___
*[`crates/blockifier/src/blockifier/block.rs` line 53 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O4K3hkj10zEsmS-Y0tl:-O4K3hkj10zEsmS-Y0tm:b8gpe98) ([raw file](https://github.com/starkware-libs/sequencer/blob/e45b885be8042a4e46c18cb01bece5e708584dc7/crates/blockifier/src/blockifier/block.rs#L53)):*
> ```XML
>             VersionedConstants::l1_to_l2_gas_price_conversion(strk_l1_gas_price.into()),
>         )
>         .unwrap();
> ```

no `unwrap` in business logic; use `expect` if you need to



_Code quote:_
```XML
.unwrap();
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/322)* status: 13 of 15 files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 130 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O4K2igL-h-032VPegSo:-O4KZRbk374ENCVRQNIA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e45b885be8042a4e46c18cb01bece5e708584dc7/crates/blockifier/src/versioned_constants.rs#L130)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't get the latest constants: call this as a method please.
the actual versioned constants used at runtime should be configurable
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 134 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O4K2Pq97044ENciwvhk:-O4K_NnK4R44OjTQUhWk:bzgs0vd) ([raw file](https://github.com/starkware-libs/sequencer/blob/e45b885be8042a4e46c18cb01bece5e708584dc7/crates/blockifier/src/versioned_constants.rs#L134)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

isn't this equivalent?
or just `.into()` without the `u128::from(...)`?
</blockquote></details>

`.into()` didn't work for some reason, so I took the compiler's suggestion. `u128::from` does work, thanks
___
*[`crates/blockifier/src/versioned_constants.rs` line 138 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O4K31KsCCtmaeacIdIl:-O4K_MdQ8bajtWyWKGpF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e45b885be8042a4e46c18cb01bece5e708584dc7/crates/blockifier/src/versioned_constants.rs#L138)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

doesn't `Ratio` support multiplication by u128? and has it's own "round up" method? I don't think you need to call `numer` and `denom` explicitly here
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/block.rs` line 49 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O4K3dm24CUk8eROZQh5:-O4KYltC72k-WbQqNmNz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e45b885be8042a4e46c18cb01bece5e708584dc7/crates/blockifier/src/blockifier/block.rs#L49)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no `unwrap` in business logic; use `expect` if you need to
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/block.rs` line 53 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O4K3hkj10zEsmS-Y0tl:-O4KYmXu9MNOIvYw98AM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e45b885be8042a4e46c18cb01bece5e708584dc7/crates/blockifier/src/blockifier/block.rs#L53)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no `unwrap` in business logic; use `expect` if you need to
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/block.rs` line 53 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O4K3PxK2-tAfdjpKYeD:-O4K_acH6gsQDxlCSXEM:bmpl6u) ([raw file](https://github.com/starkware-libs/sequencer/blob/e45b885be8042a4e46c18cb01bece5e708584dc7/crates/blockifier/src/blockifier/block.rs#L53)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the problem with this is that you implicitly assume the "latest" versioned constants are used; we shouldn't assume this.
either get the versioned constants as input, or get the L2 gas price(s) as explicit input..
</blockquote></details>

It's already changed in the next PR; added a TODO and changed how we get versioned constants.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/322)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 132 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O4KjXuaA2feUm3Mvx6m:-O4KjXuaA2feUm3Mvx6n:b-idjm33) ([raw file](https://github.com/starkware-libs/sequencer/blob/61ba5887a1d2ce3ddbacb2a6f69c9d36d13df55e/crates/blockifier/src/versioned_constants.rs#L132)):*
> ```XML
>             Ratio::new(1, u128::from(self.os_constants.gas_costs.step_gas_cost))
>                 * self.vm_resource_fee_cost()["n_steps"];
>         *(l1_to_l2_gas_price_ratio * l1_gas_price).ceil().numer()
> ```

Q: `ceil()` doesn't return an integer? it returns a Ratio? is it guaranteed to have `denom() == 1`?



_Code quote:_
```XML
.ceil().numer()
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/322#-:-O4KjuQc2ZdUbfyFfxKV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @aner-starkware)

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/322)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 132 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/322#-O4KjXuaA2feUm3Mvx6m:-O4LTYLV3JcLFxlksznZ:blmeec9) ([raw file](https://github.com/starkware-libs/sequencer/blob/61ba5887a1d2ce3ddbacb2a6f69c9d36d13df55e/crates/blockifier/src/versioned_constants.rs#L132)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Q: `ceil()` doesn't return an integer? it returns a Ratio? is it guaranteed to have `denom() == 1`?
</blockquote></details>

Seems so - it uses `from_ingteger`, which has the following implementation:
```
/// Creates a `Ratio` representing the integer `t`.
    #[inline]
    pub fn from_integer(t: T) -> Ratio<T> {
        Ratio::new_raw(t, One::one())
    }
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/322#-:-O4ds_yOAdjMDO-oYVUt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 4 of 9 files at r4, 6 of 7 files at r6, 1 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/322)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
