### PR TITLE
chore(blockifier): create func keccak_base to delete code duplication

### PR DESCRIPTION
**Pull request by avivg-starkware**

### CODE REVIEW

**Comment by avivg-starkware** [comment]
* **#2198** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2198?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2198?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2198)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @avivg-starkware, and @meship-starkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 666 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2198#-OC9bdgC9__RuLwkBQyl:-OC9bdgC9__RuLwkBQym:bom09h9) ([raw file](https://github.com/starkware-libs/sequencer/blob/2736adb21776faf589c2767a3026d1893a252cce/crates/blockifier/src/execution/syscalls/mod.rs#L666)):*
> ```XML
>     let gas_cost = n_rounds_as_u64 * syscall_handler.context.gas_costs().keccak_round_cost_gas_cost;
>     if gas_cost > *remaining_gas {
>         let out_of_gas_error =
> ```

Try to share this code as well (in the same base func)



_Code quote:_
```XML
    let mut state = [0u64; 25];
    for chunk in data.chunks(KECCAK_FULL_RATE_IN_WORDS) {
        for (i, val) in chunk.iter().enumerate() {
            state[i] ^= val.to_u64().ok_or_else(|| SyscallExecutionError::InvalidSyscallInput {
                input: **val,
                info: String::from("Invalid input for the keccak syscall."),
            })?;
        }
        keccak::f1600(&mut state)
    }
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2198)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @avivg-starkware, and @meship-starkware)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 578 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2198#-OC9blim2V2hLrarPYHK:-OC9blim2V2hLrarPYHL:b-5eh984) ([raw file](https://github.com/starkware-libs/sequencer/blob/b808867123f497c584ca58d96c8ec476e97689e3/crates/blockifier/src/execution/native/syscall_handler.rs#L578)):*
> ```XML
>         match syscall_base::keccak_base(self.context, input_length, remaining_gas) {
>             Ok(_) => (),
>             Err(e) => return Err(self.handle_error(remaining_gas, e.into())),
> ```

Can be done in one line?



_Code quote:_
```XML
            Ok(_) => (),
            Err(e) => return Err(self.handle_error(remaining_gas, e.into())),
```

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2198)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 578 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2198#-OC9blim2V2hLrarPYHK:-OChGvmuB56l0Qiz8tcs:b-e5nprs) ([raw file](https://github.com/starkware-libs/sequencer/blob/b808867123f497c584ca58d96c8ec476e97689e3/crates/blockifier/src/execution/native/syscall_handler.rs#L578)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can be done in one line?
</blockquote></details>

changed according to other changes. WDYT?
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 666 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2198#-OC9bdgC9__RuLwkBQyl:-OChazF7-HzHISrh4bSt:bqo3p7u) ([raw file](https://github.com/starkware-libs/sequencer/blob/2736adb21776faf589c2767a3026d1893a252cce/crates/blockifier/src/execution/syscalls/mod.rs#L666)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Try to share this code as well (in the same base func)
</blockquote></details>

I moved the conversion logic to be made before hand. please tell me if this implementation looks OK to you. thanks

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2198)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @avivg-starkware, and @meship-starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 217 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2198#-OChjFSBCDcVuSd3U2T8:-OChjFSBCDcVuSd3U2T9:b-65q5ae) ([raw file](https://github.com/starkware-libs/sequencer/blob/b6f7a005872703751636f8d0814a0cfa54aae1c2/crates/blockifier/src/execution/syscalls/syscall_base.rs#L217)):*
> ```XML
>         &mut self,
>         input: &[u64],
>         input_length: usize,
> ```

No need to pass the length - take it from the array.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2198)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @avivg-starkware, and @meship-starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 214 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2198#-OChjMtW8SaCIec0FpM8:-OChjMtX-EM4uN7sbC-3:b-q4g2cv) ([raw file](https://github.com/starkware-libs/sequencer/blob/b6f7a005872703751636f8d0814a0cfa54aae1c2/crates/blockifier/src/execution/syscalls/syscall_base.rs#L214)):*
> ```XML
>     }
> 
>     pub fn keccak_base(
> ```

Rename and move it above `finalize`



_Suggestion:_
```XML
    pub fn finalize(&mut self) {
        self.context
            .revert_infos
            .0
            .last_mut()
            .expect("Missing contract revert info.")
            .original_values = std::mem::take(&mut self.original_values);
    }

    pub fn keccak(
```

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2198)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @avivg-starkware, and @Yoni-Starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2198)* status: all files reviewed, 5 unresolved discussions (waiting on @avi-starkware and @avivg-starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 226 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2198#-OChjXzVE9KBoYj17SFl:-OChjXzVE9KBoYj17SFm:b-lz7d2q) ([raw file](https://github.com/starkware-libs/sequencer/blob/b6f7a005872703751636f8d0814a0cfa54aae1c2/crates/blockifier/src/execution/syscalls/syscall_base.rs#L226)):*
> ```XML
>                 error_data: vec>                     Felt::from_hex(INVALID_INPUT_LENGTH_ERROR)
>                         .map_err(SyscallExecutionError::from)?,
> ```

You can use `.expect("Failed to parse INVALID_INPUT_LENGTH_ERROR hex string")`
___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 237 at r3 ([raw file](https://github.com/starkware-libs/sequencer/blob/b6f7a005872703751636f8d0814a0cfa54aae1c2/crates/blockifier/src/execution/syscalls/syscall_base.rs#L237)):*
> ```XML
>         if gas_cost > *remaining_gas {
>             let out_of_gas_error =
>                 Felt::from_hex(OUT_OF_GAS_ERROR).map_err(SyscallExecutionError::from)?;
> ```

Same



_Code quote:_
```XML
Felt::from_hex(OUT_OF_GAS_ERROR).map_err(SyscallExecutionError::from)?;
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2198#-:-OChoLnV4dGB2OenmMMY:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @avivg-starkware)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 460 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2198#-OChoBU3EGvSqI2pxy8U:-OChoBU3EGvSqI2pxy8V:b-yclhvx) ([raw file](https://github.com/starkware-libs/sequencer/blob/727adf3434ff07ea6a49026307d69baf75a209e3/crates/blockifier/src/execution/native/syscall_handler.rs#L460)):*
> ```XML
>                 lo: u128::from(state[0]) | (u128::from(state[1]) << 64),
>             }),
>             Err(e) => Err(self.handle_error(remaining_gas, e.into())),
> ```

I think the `into` is not necessary



_Suggestion:_
```XML
Err(err) => Err(self.handle_error(remaining_gas, err)),
```

**Review by meship-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2198)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @avivg-starkware)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2198)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 460 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2198#-OChoBU3EGvSqI2pxy8U:-OCiC8nGCmCp8mZM1QEZ:b-r3vrxx) ([raw file](https://github.com/starkware-libs/sequencer/blob/727adf3434ff07ea6a49026307d69baf75a209e3/crates/blockifier/src/execution/native/syscall_handler.rs#L460)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I think the `into` is not necessary
</blockquote></details>

yes indeed, done. 
___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 214 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2198#-OChjMtW8SaCIec0FpM8:-OChl6ii22KXdhW1F339:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b6f7a005872703751636f8d0814a0cfa54aae1c2/crates/blockifier/src/execution/syscalls/syscall_base.rs#L214)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Rename and move it above `finalize`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 217 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2198#-OChjFSBCDcVuSd3U2T8:-OChl7BpDppgwGbb2GhO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b6f7a005872703751636f8d0814a0cfa54aae1c2/crates/blockifier/src/execution/syscalls/syscall_base.rs#L217)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

No need to pass the length - take it from the array.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 226 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2198#-OChjXzVE9KBoYj17SFl:-OCiCO7q83G1mnLETT7N:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/b6f7a005872703751636f8d0814a0cfa54aae1c2/crates/blockifier/src/execution/syscalls/syscall_base.rs#L226)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

You can use `.expect("Failed to parse INVALID_INPUT_LENGTH_ERROR hex string")`
</blockquote></details>

Done
___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 237 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2198#-OChjyGI09ZbbQlGGS0a:-OCiCQ-48M2ZIuFogj5V:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/b6f7a005872703751636f8d0814a0cfa54aae1c2/crates/blockifier/src/execution/syscalls/syscall_base.rs#L237)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2198#-:-OCiF1ZKExJu3h4Jds3r:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Pull request merged**
