### PR TITLE
fix(mempool_node): don't drop component clients when running servers

### PR DESCRIPTION
**Pull request by matan-starkware**
Also minor refactor of get_server_future

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1141)

### CODE REVIEW

**Comment by matan-starkware** [comment]
* **#1141** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1141?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1141#-:-O87I2VzEzu0XDL9xpGc:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Review by matan-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1141)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware and @Itay-Tsabary-Starkware)

**Comment by matan-starkware** [comment]
### Merge activity

* **Oct 6, 6:16 AM EDT**: @matan-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1141).

**Pull request merged**
