### PR TITLE
feat(blockifier): panic or saturate GasAmount arithmetic depending on 'natural' source of values

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1281)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1281?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1281** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1281?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1280** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1280?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1268** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1268?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1255** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1255?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1250** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1250?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1180** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1180?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1179** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1179?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1178** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1178?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1177** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1177?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1176** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1176?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1175** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1175?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1174** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1174?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1173** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1173?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1172** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1172?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1281)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 214 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1281#-O8pmnb_7Aiw8j9xtA7H:-O8pmnb_7Aiw8j9xtA7I:b-plyrm) ([raw file](https://github.com/starkware-libs/sequencer/blob/e372a27297e381137ba83bcbaa14ff551ef0bcc8/crates/blockifier/src/fee/resources.rs#L214)):*
> ```XML
>                 )
>             })
>         });
> ```

I think it's too much here. No need to check addition of natural gas amounts.



_Code quote:_
```XML
        .fold(GasAmount::ZERO, |accumulator, cost| {
            accumulator.checked_add(cost).unwrap_or_else(|| {
                panic!(
                    "Archival data resources to gas vector overflowed: tried to add \
                     {accumulator:?} gas to {cost:?} gas.",
                )
            })
        });
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1281)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 214 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1281#-O8pmnb_7Aiw8j9xtA7H:-O959XRn06kVY-uxGMQh:b-pdc445) ([raw file](https://github.com/starkware-libs/sequencer/blob/60d4781b706ac7e5e185c230097d28baaf765459/crates/blockifier/src/fee/resources.rs#L214)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we have two choices: panic or saturate. the `+` operator panics on overflow. want me to saturate here?
</blockquote></details>

Yes, Just use the regular `+`

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1281)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 214 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1281#-O8pmnb_7Aiw8j9xtA7H:-O95AJmI7F-8FJOIBHbL:b-rdxalc) ([raw file](https://github.com/starkware-libs/sequencer/blob/60d4781b706ac7e5e185c230097d28baaf765459/crates/blockifier/src/fee/resources.rs#L214)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Yes, Just use the regular `+`
</blockquote></details>

I don't understand why use `+` when we can be explicit in the panic.
`GasAmount` shouldn't derive `Add` IMO

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1281#-:-O95BLMC93kGOPqkCseU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 214 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1281#-O8pmnb_7Aiw8j9xtA7H:-O95AtfWDihNwJbaBfP9:bfn2p11) ([raw file](https://github.com/starkware-libs/sequencer/blob/60d4781b706ac7e5e185c230097d28baaf765459/crates/blockifier/src/fee/resources.rs#L214)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't understand why use `+` when we can be explicit in the panic.
`GasAmount` shouldn't derive `Add` IMO
</blockquote></details>

I thought it was too much defensive. We do use regular `+` in our code.
But I agree that it shouldn't impl `Add`, to be on the safe side on other cases.
lgtm.

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Oct 14, 3:01 AM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1281).

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1281)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
