### PR TITLE
refactor(consensus): create start_height function in the manager

### PR DESCRIPTION
**Pull request by matan-starkware**
Handling cached messages is now out of the main select loop.

### CODE REVIEW

**Comment by matan-starkware** [comment]
* **#2498** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2498?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2497** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2497?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2496** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2496?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2496?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2496#-:-OD_kdsY0nxIbYZigaKz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2496#-:-ODaMzsUBi5YRFpJgu-O:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2496#-ODaMCkJAM51rsfnVEhM:-ODaMCkJAM51rsfnVEhN:bhsd4ha) ([raw file](https://github.com/starkware-libs/sequencer/blob/890c09fcc9eb286f522e813b4638164bfc8451c4/crates/sequencing/papyrus_consensus/src/manager.rs#L206)):*
> ```XML
>                 ShcReturn::Tasks(new_tasks) => tasks.extend(new_tasks),
>             }
>         }
> ```

Consider adding documentation explaining each phase



_Code quote:_
```XML
    async fn start_height(
        &mut self,
        context: &mut ContextT,
        height: BlockNumber,
        shc: &mut SingleHeightConsensus,
    ) -> Result<ShcReturn, ConsensusError> {
        let mut tasks = match shc.start(context).await? {
            decision @ ShcReturn::Decision(_) => return Ok(decision),
            ShcReturn::Tasks(tasks) => tasks,
        };

        if let Some((init, content_receiver)) = self.get_current_proposal(height) {
            match shc.handle_proposal(context, init, content_receiver).await? {
                decision @ ShcReturn::Decision(_) => return Ok(decision),
                ShcReturn::Tasks(new_tasks) => tasks.extend(new_tasks),
            }
        };

        for msg in self.get_current_height_messages(height) {
            match shc.handle_message(context, msg).await? {
                decision @ ShcReturn::Decision(_) => return Ok(decision),
                ShcReturn::Tasks(new_tasks) => tasks.extend(new_tasks),
            }
        }
```

**Comment by matan-starkware** [comment]
### Merge activity

* **Dec 9, 6:22 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2496).

**Pull request merged**
