### PR TITLE
chore: do not use executable tx to calculate hash

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/657)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/657?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#517** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/517?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2  dependent PRs ([#518](https://github.com/starkware-libs/sequencer/pull/518) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/518?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#519](https://github.com/starkware-libs/sequencer/pull/519) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/519?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#657** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/657?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#636** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/636?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#611** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/611?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/657)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @yair-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/657#-O5TjGUFDr_E4dCR-syT):*
wdym here?
you use it to calculate the hash



_Code quote:_
```
do not use executable tx to calculate hash
```
___
*[`crates/gateway/src/gateway_test.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/657#-O5Tj9jz8tSKgypciKMz:-O5Tj9jz8tSKgypciKN-:b-m3k8lp) ([raw file](https://github.com/starkware-libs/sequencer/blob/c24efcc2371d22a5f15b015e0f3eb33b0cce2021/crates/gateway/src/gateway_test.rs#L96)):*
> ```XML
> 
> fn calculate_hash(rpc_tx: &RpcTransaction) -> TransactionHash {
>     let tx: Transaction = rpc_tx.clone().into();
> ```

please do not use clone



_Code quote:_
```XML
rpc_tx.clone().
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway_test.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/657#-O5Tj9jz8tSKgypciKMz:-O5Tl4kK7Dqk5ukyguF1:bp9dqag) ([raw file](https://github.com/starkware-libs/sequencer/blob/c24efcc2371d22a5f15b015e0f3eb33b0cce2021/crates/gateway/src/gateway_test.rs#L96)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

please do not use clone
</blockquote></details>

The original code also uses clones (it was just hidden inside `rpc_tx_to_account_tx`). This is only for testing.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/657)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1 and @yair-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/657#-O5TjGUFDr_E4dCR-syT):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

wdym here?
you use it to calculate the hash
</blockquote></details>

Before this PR: the function `calculate_hash` converted `RpcTransaction` into
`starknet_api::transaction::Transaction` wrapped in `starknet_api::executable_transaction::Transaction` then calculates it's hash.

After this PR this function converts `RpcTransaction` into
`starknet_api::transaction::Transaction` then calculates it's hash.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/657)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1 and @yair-starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/657#-O5Tmgnl6Ih5MkhosQI3:-O5Tmgnl6Ih5MkhosQI4:bi1i69x) ([raw file](https://github.com/starkware-libs/sequencer/blob/c24efcc2371d22a5f15b015e0f3eb33b0cce2021/crates/gateway/src/gateway_test.rs#L77)):*
> ```XML
>             ),
>             account: Account { sender_address, state: AccountState { nonce: *tx.nonce() } },
>         }))
> ```

The goal of this stack of PRs is to remove this function 



_Suggestion:_
```XML
    let (tx, sender_address) = create_tx(); // This test util should be repaced to create executable transactions directly.
    let tx_hash = calculate_hash(&tx); // The only call in the codebase to `calculate_hash`.

    let mut mock_mempool_client = MockMempoolClient::new();
    mock_mempool_client
        .expect_add_tx()
        .once()
        .with(eq(MempoolInput {
            Will be replaced here. 
            // TODO(Arni): Use external_to_executable_tx instead of `create_executable_tx`. Consider
            // creating a `convertor for testing` that does not do the compilation.
            tx: create_executable_tx(
                sender_address,
                tx_hash, // Used here.
                *tx.tip(),
                *tx.nonce(),
                tx.resource_bounds().clone().into(),
            ),
            account: Account { sender_address, state: AccountState { nonce: *tx.nonce() } },
        }))
```

**Comment by ArniStarkware** [comment]
This function will be deleted.

**Pull request closed without merging**
