### PR TITLE
chore(blockifier): compute valid retdata directly

### PR DESCRIPTION
**Pull request by ArniStarkware**
Created to address a thought on: #2104.

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#2113** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2113?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2113?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2113)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dorimedini-starkware, and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/constants.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2113#-OBz22YM3fzZa0-Dsgzj:-OBz22YM3fzZa0-Dsgzk:b9mmk71) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0bfc50ef9a10b24430599d45f6205ec5a908586/crates/blockifier/src/transaction/constants.rs#L21)):*
> ```XML
> // Expected return value of a `validate` entry point: `VALID`.
> pub static VALIDATE_RETDATA: LazyLock<Felt> =
>     LazyLock::new(|| ascii_as_felt("VALID").expect("Failed to parse ASCII"));
> ```

why is the lock needed?

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/constants.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2113#-OBz22YM3fzZa0-Dsgzj:-OBz4tRlAre5TuNoPQYp:by9u46) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0bfc50ef9a10b24430599d45f6205ec5a908586/crates/blockifier/src/transaction/constants.rs#L21)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why is the lock needed?
</blockquote></details>

[Here](https://github.com/starkware-libs/sequencer/blob/d6bb45761107546cb99756588b9de51aa392d2b2/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L31) is what I modeled after.

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2113)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @MohammadNassar1)

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2113)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/constants.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2113#-OBz22YM3fzZa0-Dsgzj:-OBzIJ9F4RJKHfFdZw7p:broy9pw) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0bfc50ef9a10b24430599d45f6205ec5a908586/crates/blockifier/src/transaction/constants.rs#L21)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

[Here](https://github.com/starkware-libs/sequencer/blob/d6bb45761107546cb99756588b9de51aa392d2b2/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L31) is what I modeled after.
</blockquote></details>

Don't you want to remove it and use `starknet_api`'s `VALIDATE_RETDATA`?

**Review by ayeletstarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2113)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @MohammadNassar1)

**Pull request merged**
