### PR TITLE
chore: feature activation in crate Cargo.toml files, not workspace

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/647)

### CODE REVIEW

**Review by dan-starkware — COMMENTED** [review]
Papyrus-wise :lgtm: 
Need to make sure with other crate owners. 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/647#-:-O5TCjJq25bjrWji7nB0:b-ho6s41)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @nadin-Starkware)

___
*[`Cargo.toml` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/647#-O5TCF4H7-WucdpnAr32:-O5TCF4H7-WucdpnAr33:b5zjq80) ([raw file](https://github.com/starkware-libs/sequencer/blob/3a6e716cc68fb6cd63071b3136819968759e642a/Cargo.toml#L168)):*
> ```TOML
> regex = "1.10.4"
> replace_with = "0.1.7"
> reqwest = "0.11"
> ```

Is it used? Remove altogether?



_Code quote:_
```TOML
reqwest = "0.11"
```
___
*[`Cargo.toml` line 181 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/647#-O5TCS3HEwNJZ4_zhJq8:-O5TCS3HEwNJZ4_zhJq9:b-dk500c) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f89ecefdd80a8172464f18d244a219b7451f1f7/Cargo.toml#L181)):*
> ```TOML
> starknet-core = "0.6.0"
> starknet-crypto = "0.5.1"
> starknet-types-core = { version = "0.1.5", features = ["hash", "prime-bigint", "std"] }
> ```

Are these used?



_Code quote:_
```TOML
"prime-bigint", "std"] 
```

**Review by dorimedini-starkware — COMMENTED** [review]
what should they check?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/647#-:-O5TDyDB0EQMWssX2q1f:b-t26o3r)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nadin-Starkware)

___
*[`Cargo.toml` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/647#-O5TCF4H7-WucdpnAr32:-O5TDeXWEtFmYmTykZre:b-piaeky) ([raw file](https://github.com/starkware-libs/sequencer/blob/3a6e716cc68fb6cd63071b3136819968759e642a/Cargo.toml#L168)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Is it used? Remove altogether?
</blockquote></details>

used in several crates, why do you say it's unused?
___
*[`Cargo.toml` line 181 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/647#-O5TCS3HEwNJZ4_zhJq8:-O5TDjOR-PPnulvhZrdQ:bxffrlp) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f89ecefdd80a8172464f18d244a219b7451f1f7/Cargo.toml#L181)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Are these used?
</blockquote></details>

doens't look like it.
I ran `cargo test -p X` for every workspace member `X`, all passed...

**Review by uriel-starkware — COMMENTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/647)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry, @dan-starkware, @elintul, @giladchase, @nadin-Starkware, and @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/647)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry, @dan-starkware, @elintul, @giladchase, @nadin-Starkware, and @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/647)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry, @elintul, @giladchase, @nadin-Starkware, and @noaov1)

**Review by uriel-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/647)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry, @elintul, @giladchase, @nadin-Starkware, and @noaov1)

**Pull request merged**
