### PR TITLE
test: add decision reached step to end to end test

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1408)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1408?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1408** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1408?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1407** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1407?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1386** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1386?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1352** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1352?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
+reviewer:@alonh5 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1408#-:-O9DpTMh4YUq08Nie-yG:b-wqqsco)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alonh5)

**Review by alonh5 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1408#-:-O9dkxDB0HwzYdI8Xj8Q:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1408)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 53 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1408#-O9o3zcB3w-k8az-ac-D:-O9o3zcB3w-k8az-ac-E:b-quro43) ([raw file](https://github.com/starkware-libs/sequencer/blob/2484c8935c3796eea66f2f8460df07733eeff663/crates/tests-integration/tests/end_to_end_test.rs#L53)):*
> ```XML
>     expected_batched_tx_hashes: &[TransactionHash],
> ) {
>     // Setup. Holds the state of the consensus manager.
> ```

What does this refer to?
Please remove all redundant comments from this function. (e.g if the code "says" it there's no need for a comment repeating it)



_Code quote:_
```XML
// Setup. Holds the state of the consensus manager.
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1408)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 53 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1408#-O9o3zcB3w-k8az-ac-D:-O9o6TLkBRPHExfGbGHH:b-n1ares) ([raw file](https://github.com/starkware-libs/sequencer/blob/2484c8935c3796eea66f2f8460df07733eeff663/crates/tests-integration/tests/end_to_end_test.rs#L53)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What does this refer to?
Please remove all redundant comments from this function. (e.g if the code "says" it there's no need for a comment repeating it)
</blockquote></details>

This refers to the "Set start height," already covered by a comment.
Removed.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1408)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1408#-O9o8dN32XO9tAj9VFAO:-O9o8dN32XO9tAj9VFAP:b-gdcugw) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb729a5698aeee85d5ebac2c058d548f6b832184/crates/tests-integration/tests/end_to_end_test.rs#L60)):*
> ```XML
> 
>     // Start height.
>     batcher_client.start_height(StartHeightInput { height: current_height }).await.unwrap();
> ```

I would also remove these, they are redundant.

Regarding the TODO, this is something the consensus should do, so if the consensus is added to the test we don't need this right?



_Suggestion:_
```XML
    // TODO(Arni): Get the current height and retrospective_block_hash from the rpc storage
    // Start height.
    let current_height = BlockNumber(1);
    batcher_client.start_height(StartHeightInput { height: current_height }).await.unwrap();
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1408)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @yair-starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1408#-O9o8dN32XO9tAj9VFAO:-OA1kKWG9xBZujaYV73e:bj0ysev) ([raw file](https://github.com/starkware-libs/sequencer/blob/69d8e78f5ecd0e6efc95f62ae2f7f8e18f0208ac/crates/tests-integration/tests/end_to_end_test.rs#L60)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I would also remove these, they are redundant.

Regarding the TODO, this is something the consensus should do, so if the consensus is added to the test we don't need this right?
</blockquote></details>

About the comments. Removed.

About the todo. @yair-starkware suggested we add it. He also questioned the existence of this whole code (it did find a few bug for us already). So I assume we will not mind if we remove this todo. Correct?

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1408#-:-OAByMgN8ccxDGk63Gob:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1408#-O9o8dN32XO9tAj9VFAO:-OABxu5iAEXkEkVT4CrK:b-2a1evm) ([raw file](https://github.com/starkware-libs/sequencer/blob/69d8e78f5ecd0e6efc95f62ae2f7f8e18f0208ac/crates/tests-integration/tests/end_to_end_test.rs#L60)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

About the comments. Removed.

About the todo. @yair-starkware suggested we add it. He also questioned the existence of this whole code (it did find a few bug for us already). So I assume we will not mind if we remove this todo. Correct?
</blockquote></details>

I just think we'll add the consensus before we do this TODO. So either remove it or add an `or use consensus`.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1408)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alonh5 and @yair-starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1408#-O9o8dN32XO9tAj9VFAO:-OAC0-XI9bpI5JkVhtMi:bs7wumb) ([raw file](https://github.com/starkware-libs/sequencer/blob/69d8e78f5ecd0e6efc95f62ae2f7f8e18f0208ac/crates/tests-integration/tests/end_to_end_test.rs#L60)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I just think we'll add the consensus before we do this TODO. So either remove it or add an `or use consensus`.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1408)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
