### PR TITLE
chore(blockifier): implement staknet_api class_info to match blockifier class_info

### PR DESCRIPTION
**Pull request by avivg-starkware**
…er class_info

### CODE REVIEW

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/starknet_api/src/contract_class.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OAvbp7DEDpLM5N6IdEd:-OAvbp7DEDpLM5N6IdEe:bjq67km) ([raw file](https://github.com/starkware-libs/sequencer/blob/011775ddec2d9d8e387dfc4954ffc62aef896b61/crates/starknet_api/src/contract_class.rs#L106)):*
> ```XML
>         }
>     }
> }
> ```

copied from blockifier::execution::contract_class::ClassInfo to be used through staknet_api executable_tx through AccountTransaction in following PR (1688)

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-:-OAwxsJf0QbnFBBDko64:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware and @noaov1)

___
*[`crates/starknet_api/src/contract_class.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OAvbp7DEDpLM5N6IdEd:-OAwtT13CELZDyqDLUKE:b-66s5vi) ([raw file](https://github.com/starkware-libs/sequencer/blob/011775ddec2d9d8e387dfc4954ffc62aef896b61/crates/starknet_api/src/contract_class.rs#L106)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

copied from blockifier::execution::contract_class::ClassInfo to be used through staknet_api executable_tx through AccountTransaction in following PR (1688)
</blockquote></details>

#1688 (add a HashTag for PR number to become a link :) ) 
___
*[`crates/starknet_api/src/contract_class.rs` line 100 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OAwtyFa0Lo27WbiXHEF:-OAwtyFa0Lo27WbiXHEG:bvz1c8x) ([raw file](https://github.com/starkware-libs/sequencer/blob/f6f3de15831fc9bca214e2e8f49076a8dbc521cc/crates/starknet_api/src/contract_class.rs#L100)):*
> ```XML
>             })
>         }
>     }
> ```

Damn, do I hate this `new` method... (This is not a practical comment - just sharing).
It can only return an error if we have an internal error.

Out of scope for this PR - just personal grudges. And the upside is that with the old `new` method deleted - the refactor I planned can take effect.



_Code quote:_
```XML
    pub fn new(
        contract_class: &ContractClass,
        sierra_program_length: usize,
        abi_length: usize,
    ) -> Result<Self, StarknetApiError> {
        let (contract_class_version, condition) = match contract_class {
            ContractClass::V0(_) => (0, sierra_program_length == 0),
            ContractClass::V1(_) => (1, sierra_program_length > 0),
        };

        if condition {
            Ok(Self { contract_class: contract_class.clone(), sierra_program_length, abi_length })
        } else {
            Err(StarknetApiError::ContractClassVersionSierraProgramLengthMismatch {
                contract_class_version,
                sierra_program_length,
            })
        }
    }
```

**Comment by ArniStarkware** [comment]
*[`crates/starknet_api/src/contract_class.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OAx7ybv7Dw62-6tWfpe:-OAx7ybw6cYzSyc5rKLr:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/f6f3de15831fc9bca214e2e8f49076a8dbc521cc/crates/starknet_api/src/contract_class.rs#L48)):*
> ```XML
> /// and other parameters derived from the original declare transaction required for billing.
> #[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
> pub struct ClassInfo {
> ```





_Suggestion:_
```XML
// TODO(Ayelet,10/02/2024): Change to bytes.
pub struct ClassInfo {
```

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware and @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702)* status: all files reviewed, 2 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 28 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OB4Ksk5Ak_NomIqYs6l:-OB4Ksk5Ak_NomIqYs6m:b9pbq3c) ([raw file](https://github.com/starkware-libs/sequencer/blob/c56e01a72a57c6e81fb1cda163bd8eb026d2e137/crates/blockifier/src/test_utils/deploy_account.rs#L28)):*
> ```XML
>         DeployAccountTransaction::new(deploy_account_tx, tx_hash, contract_address);
> 
>     AccountTransaction::DeployAccount(executable_deploy_account_tx)
> ```

Can you revert the empty line? It seems like the only change in this file
___
*[`crates/blockifier/src/test_utils/invoke.rs` line 30 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OB4L13gC-PQT6Hi7nOQ:-OB4L13gC-PQT6Hi7nOR:b-ya81ng) ([raw file](https://github.com/starkware-libs/sequencer/blob/c56e01a72a57c6e81fb1cda163bd8eb026d2e137/crates/blockifier/src/test_utils/invoke.rs#L30)):*
> ```XML
>         false => InvokeTransaction::new(invoke_tx, tx_hash),
>     };
> ```

Same as above

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware and @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware and @noaov1)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 28 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OB4Ksk5Ak_NomIqYs6l:-OB5YLt60ix0ycpR1t2x:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/c56e01a72a57c6e81fb1cda163bd8eb026d2e137/crates/blockifier/src/test_utils/deploy_account.rs#L28)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Can you revert the empty line? It seems like the only change in this file
</blockquote></details>

Done
___
*[`crates/blockifier/src/test_utils/invoke.rs` line 30 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OB4L13gC-PQT6Hi7nOQ:-OB5YOlpE5RySnm2xMrb:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/c56e01a72a57c6e81fb1cda163bd8eb026d2e137/crates/blockifier/src/test_utils/invoke.rs#L30)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware and @noaov1)

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/starknet_api/src/contract_class.rs` line 9 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OBGBHj00lImT1DnkW7u:-OBGBHj00lImT1DnkW7v:bgnvd1y) ([raw file](https://github.com/starkware-libs/sequencer/blob/7f0312927d1ecc9fa3b64559a733f180a9f3a4f9/crates/starknet_api/src/contract_class.rs#L9)):*
> ```XML
> 
> // Calldata.
> pub const WORD_WIDTH: usize = 32;
> ```

Please use this constant in the blockifier crate (and remove it from `eth_gas_constants`. 
Consider defining it in a different file (maybe `core.rs`?)
(can be done in a separate PR)



_Suggestion:_
```XML
// Ethereum constant.
pub const WORD_WIDTH: usize = 32;
```

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

**Comment by ArniStarkware** [comment]
*[`crates/starknet_api/src/contract_class.rs` line 9 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OBKnsD7Bw2Qw5X0GGUa:-OBKnsD7Bw2Qw5X0GGUb:bqiotmd) ([raw file](https://github.com/starkware-libs/sequencer/blob/0228f1620b608b061dda0962b37064e57fed7714/crates/starknet_api/src/contract_class.rs#L9)):*
> ```XML
> 
> // Ethereum constant.
> pub const WORD_WIDTH: usize = 32;
> ```

move to `core.rs`



_Code quote:_
```XML
// Ethereum constant.
pub const WORD_WIDTH: usize = 32;
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r7, 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @avivg-starkware, @meship-starkware, and @noaov1)

___
*[`-- commits` line 5 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OBKo7Y1AFtD4knqIeKH:-OBKo7Y1AFtD4knqIeKI:bkmakw):*
Why is this PR comprised of two commits?
There is no 
> impl .into()
in this PR - or am I missing something?



_Code quote:_
```
New commits in r7 on 10/11/2024 at 13:09:
- 9be723e: refactor(blockifier): impl .into() from api executable tx to blockifier AccountTransaction

New commits in r8 on 10/11/2024 at 13:19, probably rebased from r6:
- 0228f16: chore(blockifier): implement staknet_api class_info to match blockifier class_info
```

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702)* status: 2 of 9 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @meship-starkware, and @noaov1)

___
*[`crates/starknet_api/src/contract_class.rs` line 9 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OBKnsD7Bw2Qw5X0GGUa:-OBKotExBeADysAzZVwd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0228f1620b608b061dda0962b37064e57fed7714/crates/starknet_api/src/contract_class.rs#L9)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

move to `core.rs`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 4 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OBKqHrvD0D0Lu2GpkxR:-OBKqHrvD0D0Lu2GpkxS:b-57nnu7) ([raw file](https://github.com/starkware-libs/sequencer/blob/f1856a287f83201834886d96147a7f5629017030/crates/blockifier/src/fee/eth_gas_constants.rs#L4)):*
> ```XML
> pub const GAS_PER_MEMORY_ZERO_BYTE: usize = 4;
> pub const GAS_PER_MEMORY_BYTE: usize = 16;
> pub const WORD_WIDTH: usize = 32; //TODO(AvivG): use starknet_api::core::WORD_WIDTH instead.aig add -p
> ```

@noaov1  - DO you think this suggested change is wanted (due to the change below)?

**Comment by avivg-starkware** [comment]
*[`crates/starknet_api/src/contract_class.rs` line 9 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OBGBHj00lImT1DnkW7u:-OBKqWTs9Vr9Rq2US3KX:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/7f0312927d1ecc9fa3b64559a733f180a9f3a4f9/crates/starknet_api/src/contract_class.rs#L9)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please use this constant in the blockifier crate (and remove it from `eth_gas_constants`. 
Consider defining it in a different file (maybe `core.rs`?)
(can be done in a separate PR)
</blockquote></details>

Done

**Comment by avivg-starkware** [comment]
*[`-- commits` line 5 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OBKo7Y1AFtD4knqIeKH:-OBKqeJV-ar1lV32R8P2:b-yayxgd):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Why is this PR comprised of two commits?
There is no 
> impl .into()
in this PR - or am I missing something?
</blockquote></details>

fixed. I'm trying Graphite and still learning.. :)

**Comment by ArniStarkware** [comment]
*[`crates/starknet_api/src/core.rs` line 468 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OBKwdZj26GDfTNKblaQ:-OBKwdZj26GDfTNKblaR:bxsf4w6) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ad09b5f44436872b3a6f0cc9ef4cca119900a68/crates/starknet_api/src/core.rs#L468)):*
> ```XML
> 
> // Ethereum constant.
> pub const WORD_WIDTH: usize = 32;
> ```

Constants should be at the start of the file.

Another issue is that the constant `WORD_WIDTH` 's name is non-informative in this context.



_Suggestion:_
```XML
// Ethereum constant. 
/// One Felt fits into 32 bytes.
pub const WORD_WIDTH: usize = 32;
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702)* status: 3 of 9 files reviewed, 3 unresolved discussions (waiting on @avivg-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 4 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OBKqHrvD0D0Lu2GpkxR:-OBKvQAT0luffWK8q2sv:bb77ufg) ([raw file](https://github.com/starkware-libs/sequencer/blob/f1856a287f83201834886d96147a7f5629017030/crates/blockifier/src/fee/eth_gas_constants.rs#L4)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

@noaov1  - DO you think this suggested change is wanted (due to the change below)?
</blockquote></details>

Yes.
___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 4 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OBKvMGn9y8YA7cr5cHB:-OBKvMGn9y8YA7cr5cHC:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ad09b5f44436872b3a6f0cc9ef4cca119900a68/crates/blockifier/src/fee/eth_gas_constants.rs#L4)):*
> ```XML
> pub const GAS_PER_MEMORY_ZERO_BYTE: usize = 4;
> pub const GAS_PER_MEMORY_BYTE: usize = 16;
> pub const WORD_WIDTH: usize = 32; //TODO(AvivG): use starknet_api::core::WORD_WIDTH instead.aig add -p
> ```





_Suggestion:_
```XML
//TODO(AvivG): use starknet_api::core::WORD_WIDTH instead.
pub const WORD_WIDTH: usize = 32; 
```

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r8, 6 of 7 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702)* status: all files reviewed, 3 unresolved discussions (waiting on @avivg-starkware and @noaov1)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @meship-starkware, and @noaov1)

___
*[`crates/starknet_api/src/core.rs` line 468 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OBKwdZj26GDfTNKblaQ:-OBLiaIk1f_bYC6zFGJ0:b-wava7q) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ad09b5f44436872b3a6f0cc9ef4cca119900a68/crates/starknet_api/src/core.rs#L468)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Constants should be at the start of the file.

Another issue is that the constant `WORD_WIDTH` 's name is non-informative in this context.
</blockquote></details>

Would you change the name of the constant or just add the comment as you did?

As there were other constants along this file, I wasn't sure where best to place. I moved it just below the 'use'... should it be elsewhere? 
___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 4 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OBKvMGn9y8YA7cr5cHB:-OBLiSftAnHbL_kHA3FR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ad09b5f44436872b3a6f0cc9ef4cca119900a68/crates/blockifier/src/fee/eth_gas_constants.rs#L4)):*
> ```XML
> pub const GAS_PER_MEMORY_ZERO_BYTE: usize = 4;
> pub const GAS_PER_MEMORY_BYTE: usize = 16;
> pub const WORD_WIDTH: usize = 32; //TODO(AvivG): use starknet_api::core::WORD_WIDTH instead.aig add -p
> ```

Done.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @meship-starkware and @noaov1)

___
*[`crates/starknet_api/src/core.rs` line 468 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OBKwdZj26GDfTNKblaQ:-OBLuiZw2jZWKmNMVXwK:bb529f7) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ad09b5f44436872b3a6f0cc9ef4cca119900a68/crates/starknet_api/src/core.rs#L468)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

Would you change the name of the constant or just add the comment as you did?

As there were other constants along this file, I wasn't sure where best to place. I moved it just below the 'use'... should it be elsewhere?
</blockquote></details>

I think this is fine for now.

Maybe we want a `starknet_api::constants.rs` - but I think this is out of scope.

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 4 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OBKvMGn9y8YA7cr5cHB:-OBM7oaG4fPnJovBn7H1:bkyesf2) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ad09b5f44436872b3a6f0cc9ef4cca119900a68/crates/blockifier/src/fee/eth_gas_constants.rs#L4)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

1. Great.
2. Non-blocking - how hard is it to follow through with this to-do in this PR? How many files are affected?

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 4 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/1702#-OBKvMGn9y8YA7cr5cHB:-OBQ-46X74nTk77ym8b7:bbrbvku) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ad09b5f44436872b3a6f0cc9ef4cca119900a68/crates/blockifier/src/fee/eth_gas_constants.rs#L4)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

1. Great.
2. Non-blocking - how hard is it to follow through with this to-do in this PR? How many files are affected?
</blockquote></details>

there are only 4 files WORD_WIDTH appears in. I still prefer to handle this in a separate PR, will link in this thread when exists

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Comment by avivg-starkware** [comment]
* **#1688** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1688?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1858** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1858?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1702** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1702?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @avivg-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1702)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware and @noaov1)

**Pull request merged**
