### PR TITLE
chore(blockifier_reexecution): refactor cli to reduce code duplication

### PR DESCRIPTION
**Pull request by aner-starkware**

### CODE REVIEW

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1814)* status: 0 of 2 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OAwToayCKB_WaO88Iw9:-OAwToazC-QMU7m6bViT:bg2tbdh) (no related file):*
Some more refactoring is here: https://reviewable.io/reviews/starkware-libs/sequencer/1820

___

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1814)* status: 0 of 2 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OAwToayCKB_WaO88Iw9:-OAx5yWEDjHenCr9UpYS:b-6bl5mf) (no related file):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Some more refactoring is here: https://reviewable.io/reviews/starkware-libs/sequencer/1820
</blockquote></details>

Additional refactoring moved here : https://reviewable.io/reviews/starkware-libs/sequencer/1843

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1814)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB0pv9pCQFzmSzxmDBE:-OB0pv9pCQFzmSzxmDBF:b-ow0l7z) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c083ebd681c2952ffd74474151a113c48917515/crates/blockifier_reexecution/src/main.rs#L51)):*
> ```XML
>         #[clap(flatten)]
>         shared_args: SharedArgs,
>     },
> ```

why do you need an output dir in the rpc test (without dump)?



_Code quote:_
```XML
    RpcTest {
        #[clap(flatten)]
        shared_args: SharedArgs,
    },
```
___
*[`crates/blockifier_reexecution/src/main.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB0qsMp6oQLDB5vC46U:-OB0qsMp6oQLDB5vC46V:b-5e14q5) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c083ebd681c2952ffd74474151a113c48917515/crates/blockifier_reexecution/src/main.rs#L62)):*
> ```XML
>     ReexecuteBlock {
>         #[clap(flatten)]
>         shared_args: SharedArgs,
> ```

you don't need the node url here, right?



_Code quote:_
```XML
 shared_args: SharedArgs,
```

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/main.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB0pv9pCQFzmSzxmDBE:-OB0rhT32bS5zK2TN_Dm:b-92b8b0) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c083ebd681c2952ffd74474151a113c48917515/crates/blockifier_reexecution/src/main.rs#L51)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do you need an output dir in the rpc test (without dump)?
</blockquote></details>

I don't - there are 3 args and 3 commands: the 1st requires the first two args, the second all three, and the last the second two. How do you want me to organize the args?

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/main.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB0qsMp6oQLDB5vC46U:-OB0rxXm4vSMTn2-_W8K:b-81la7d) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c083ebd681c2952ffd74474151a113c48917515/crates/blockifier_reexecution/src/main.rs#L62)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you don't need the node url here, right?
</blockquote></details>

Right

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1814)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB0pv9pCQFzmSzxmDBE:-OB0vS7M5LFNIT0km8DV:b-lrputk) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c083ebd681c2952ffd74474151a113c48917515/crates/blockifier_reexecution/src/main.rs#L51)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I don't - there are 3 args and 3 commands: the 1st requires the first two args, the second all three, and the last the second two. How do you want me to organize the args?
</blockquote></details>

if there is no subset of args that is common to all - just be explicit in each command... unless you have some idea to share code.
but don't require unecessary args for commands that don't need them
___
*[`crates/blockifier_reexecution/src/main.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB0qsMp6oQLDB5vC46U:-OB0ve8PBTQMu_34vjqM:bpumsz2) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c083ebd681c2952ffd74474151a113c48917515/crates/blockifier_reexecution/src/main.rs#L62)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Right
</blockquote></details>

then please don't require it

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/main.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB0pv9pCQFzmSzxmDBE:-OB0vt9ACPdZq120-aHL:b-fdskaj) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c083ebd681c2952ffd74474151a113c48917515/crates/blockifier_reexecution/src/main.rs#L51)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if there is no subset of args that is common to all - just be explicit in each command... unless you have some idea to share code.
but don't require unecessary args for commands that don't need them
</blockquote></details>

There's a natural default, so they don't strictly require them. Being explicit here is simply much more code - what's the disadvantage to using this struct?

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/main.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB0qsMp6oQLDB5vC46U:-OB0x5J78z6KCU7PNxxj:b8iqwii) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c083ebd681c2952ffd74474151a113c48917515/crates/blockifier_reexecution/src/main.rs#L62)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

then please don't require it
</blockquote></details>

Done. Is it better this way?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1814)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB0pv9pCQFzmSzxmDBE:-OB0ytAs9U499Ao6ulic:bctrm7n) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c083ebd681c2952ffd74474151a113c48917515/crates/blockifier_reexecution/src/main.rs#L51)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

There's a natural default, so they don't strictly require them. Being explicit here is simply much more code - what's the disadvantage to using this struct?
</blockquote></details>

in the RPC test you would want the URL to be *required*.
there is no way to run it successfully with a free-tier link
___
*[`crates/blockifier_reexecution/src/main.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB0qsMp6oQLDB5vC46U:-OB0zIVu983LMkMVTTzq:b2nign6) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c083ebd681c2952ffd74474151a113c48917515/crates/blockifier_reexecution/src/main.rs#L62)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done. Is it better this way?
</blockquote></details>

yes
___
*[`crates/blockifier_reexecution/src/main.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB0z09a64MZ_KZlbNBU:-OB0z09a64MZ_KZlbNBV:b-x1untn) ([raw file](https://github.com/starkware-libs/sequencer/blob/3718e55f9f8d0abf6e8ef7a5ba6ce6b955f8c618/crates/blockifier_reexecution/src/main.rs#L35)):*
> ```XML
>         /// Default: https://free-rpc.nethermind.io/mainnet-juno/. Won't work for big tests.
>         #[clap(long, short = 'n', default_value = "https://free-rpc.nethermind.io/mainnet-juno/")]
>         node_url: String,
> ```

default is only useful for the HTTP tests (serde of RPC responses);
no real way to run an entire block in RPC mode with a free link



_Suggestion:_
```XML
        #[clap(long, short = 'n']
        node_url: String,
```
___
*[`crates/blockifier_reexecution/src/main.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB0zDLzD5DJeW_XPXwu:-OB0zDLzD5DJeW_XPXwv:byr4ffv) ([raw file](https://github.com/starkware-libs/sequencer/blob/3718e55f9f8d0abf6e8ef7a5ba6ce6b955f8c618/crates/blockifier_reexecution/src/main.rs#L47)):*
> ```XML
>         /// Default: https://free-rpc.nethermind.io/mainnet-juno/. Won't work for big tests.
>         #[clap(long, short = 'n', default_value = "https://free-rpc.nethermind.io/mainnet-juno/")]
>         node_url: String,
> ```

see above



_Suggestion:_
```XML
        #[clap(long, short = 'n']
        node_url: String,
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1814)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB0pv9pCQFzmSzxmDBE:-OB13vZ_2Tk3y_54hb_B:b-2qzghs) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c083ebd681c2952ffd74474151a113c48917515/crates/blockifier_reexecution/src/main.rs#L51)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

in the RPC test you would want the URL to be *required*.
there is no way to run it successfully with a free-tier link
</blockquote></details>

True, though it was useful for testing it during development.
___
*[`crates/blockifier_reexecution/src/main.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB0z09a64MZ_KZlbNBU:-OB13tjQBjBajK8nqNpF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3718e55f9f8d0abf6e8ef7a5ba6ce6b955f8c618/crates/blockifier_reexecution/src/main.rs#L35)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

default is only useful for the HTTP tests (serde of RPC responses);
no real way to run an entire block in RPC mode with a free link
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/main.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB0zDLzD5DJeW_XPXwu:-OB13t3C2V3il5zI6tE2:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3718e55f9f8d0abf6e8ef7a5ba6ce6b955f8c618/crates/blockifier_reexecution/src/main.rs#L47)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1814)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 193 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB1BLdh27cvl90D4062:-OB1BLdh27cvl90D4063:bxhhd7m) ([raw file](https://github.com/starkware-libs/sequencer/blob/261e2a7d6238979b028b190eba0fb85693421b6b/crates/blockifier_reexecution/src/state_reader/utils.rs#L193)):*
> ```XML
>     // TODO(Aner): compute correct block hash at storage slot 0x1 instead of removing it.
>     expected_state_diff.storage_updates.shift_remove(&ContractAddress(1_u128.into()));
>     assert_eq_state_diff!(expected_state_diff, actual_state_diff);
> ```

aviv merged; please rebase and fix this



_Code quote:_
```XML
    transaction_executor.execute_txs(&all_txs_in_next_block);
    // Finalize block and read actual statediff.
    let (actual_state_diff, _, _) =
        transaction_executor.finalize().expect("Couldn't finalize block");

    // TODO(Aner): compute correct block hash at storage slot 0x1 instead of removing it.
    expected_state_diff.storage_updates.shift_remove(&ContractAddress(1_u128.into()));
    assert_eq_state_diff!(expected_state_diff, actual_state_diff);
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1814)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 193 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB1BLdh27cvl90D4062:-OB1UuEJ3JZ1nmUVB_uR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/261e2a7d6238979b028b190eba0fb85693421b6b/crates/blockifier_reexecution/src/state_reader/utils.rs#L193)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

aviv merged; please rebase and fix this
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1814)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs` line 167 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB4aZPL28XN9fgwyl_Q:-OB4aZPL28XN9fgwyl_R:bwnx82h) ([raw file](https://github.com/starkware-libs/sequencer/blob/b39d90377fa247f7c4e7ddd57ff7a1f93093b041/crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs#L167)):*
> ```XML
> 
> #[rstest]
> // TODO(Aner): Add block for each starknet version and for declare, deploy, replace_class, etc.
> ```

aviv already has block numbers for all of these, no? want to add them?



_Code quote:_
```XML
// TODO(Aner): Add block for each starknet version and for declare, deploy, replace_class, etc.
```
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 193 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB1BLdh27cvl90D4062:-OB4aob_9t12efSRJ_j6:b-d7oxx0) ([raw file](https://github.com/starkware-libs/sequencer/blob/261e2a7d6238979b028b190eba0fb85693421b6b/crates/blockifier_reexecution/src/state_reader/utils.rs#L193)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

where is pre_process_block?
please ask for review from @AvivYossef-starkware

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 193 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB1BLdh27cvl90D4062:-OB4c5exBtAY8VLVeAPU:bxbvo3v) ([raw file](https://github.com/starkware-libs/sequencer/blob/261e2a7d6238979b028b190eba0fb85693421b6b/crates/blockifier_reexecution/src/state_reader/utils.rs#L193)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where is pre_process_block?
please ask for review from @AvivYossef-starkware
</blockquote></details>

That change is already in this PR: https://reviewable.io/reviews/starkware-libs/sequencer/1764

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1814)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs` line 167 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB4aZPL28XN9fgwyl_Q:-OB4dZ0Z6snYOsG0Se7N:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b39d90377fa247f7c4e7ddd57ff7a1f93093b041/crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs#L167)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

aviv already has block numbers for all of these, no? want to add them?
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-:-OB4xtivB5uZv2imsmqw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

**Review by AvivYossef-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1814)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 79 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB56cvgBGtkK8nk_HzD:-OB56cvgBGtkK8nk_HzE:b-lt70n3) ([raw file](https://github.com/starkware-libs/sequencer/blob/7fab368117be7308c4022b3151d8f196dbbd35b1/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L79)):*
> ```XML
>     pub state_maps: ReexecutionStateMaps,
>     pub contract_class_mapping: StarknetContractClassMapping,
>     pub old_block_hash: BlockHash,
> ```

Please add documentation or change the location of `old_block_hash`, as it is confusing since the old block hash does not correspond to the hash of the previous block.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1814)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 79 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-OB56cvgBGtkK8nk_HzD:-OB5MQkp185LqIbuG77m:bohvfg3) ([raw file](https://github.com/starkware-libs/sequencer/blob/94a3fcf7973f0c5ea0ba793af055f978123d9ee7/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L79)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Please add documentation or change the location of `old_block_hash`, as it is confusing since the old block hash does not correspond to the hash of the previous block.
</blockquote></details>

I don't see it, I guess it's already done.

**Review by AvivYossef-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1814#-:-OB5S2iTC8QHGBvm5S7T:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1814)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
