### PR TITLE
test(starknet_integration_tests): match sequencer address with default validator id

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#2486** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2486?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2486?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2486)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 228 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2486#-ODM5J_ODMW4MDJ6jBU_:-ODM5J_ODMW4MDJ6jBUa:b-2fifl8) ([raw file](https://github.com/starkware-libs/sequencer/blob/6cb82b2d5d3c9691b84b866cfbd76a9da402b690/crates/starknet_integration_tests/src/utils.rs#L228)):*
> ```XML
> ) -> BatcherConfig {
>     // TODO(Arni): Create BlockBuilderConfig create for testing method and use here.
>     const SEQUENCER_ADDRESS_FOR_TESTING: u32 = 100;
> ```

You're removing this in the next PR so there's really no need for this change.
I meant changing it in the top PR.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2486)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 228 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2486#-ODM5J_ODMW4MDJ6jBU_:-ODMFEC93igYpiIArJYl:banbwrn) ([raw file](https://github.com/starkware-libs/sequencer/blob/6cb82b2d5d3c9691b84b866cfbd76a9da402b690/crates/starknet_integration_tests/src/utils.rs#L228)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You're removing this in the next PR so there's really no need for this change.
I meant changing it in the top PR.
</blockquote></details>

My goal was to isolate the change of the hashes in the end to end flow test.

Why was this comment blocking?

**Comment by ArniStarkware** [comment]
### Merge activity

* **Dec 5, 9:47 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2486).

**Pull request merged**
