### PR TITLE
refactor(starknet_mempool_p2p): change MempoolP2pRunner to hold future intead of NetworkManager

### PR DESCRIPTION
**Pull request by AlonLStarkWare**

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2692)* status: all files reviewed, 4 unresolved discussions (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2692#-OESv-zj3wgbqQbkGjUb:-OESv-zj3wgbqQbkGjUc:b-a150em) ([raw file](https://github.com/starkware-libs/sequencer/blob/21535eea724b74f960a5342f26890a7ff0e2e567/crates/starknet_mempool_p2p/src/runner/test.rs#L80)):*
> ```XML
> #[tokio::test]
> async fn start_component_receive_tx_happy_flow() {
>     let TestSubscriberChannels { mock_network, subscriber_channels } =
> ```

Add a setup function to reduce code duplication
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 89 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2692#-OESunCRElKVuRTkvVdZ:-OESunCRElKVuRTkvVd_:bbiqb10) ([raw file](https://github.com/starkware-libs/sequencer/blob/21535eea724b74f960a5342f26890a7ff0e2e567/crates/starknet_mempool_p2p/src/runner/test.rs#L89)):*
> ```XML
>     } = mock_network;
>     // Creating a placeholder network manager with default config for init of a mempool receiver
>     let placeholder_network_manager = NetworkManager::new(NetworkConfig::default(), None);
> ```

Remove this and do instead `let network_future = pending();`
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2692#-OESuv0y-qvmo5GMqv4k:-OESuv0y-qvmo5GMqv4l:bsobg3f) ([raw file](https://github.com/starkware-libs/sequencer/blob/21535eea724b74f960a5342f26890a7ff0e2e567/crates/starknet_mempool_p2p/src/runner/test.rs#L94)):*
> ```XML
>     let mock_gateway_client = Arc::new(MockGatewayClient { add_tx_sender });
>     let mut mempool_p2p_runner = MempoolP2pRunner::new(
>         Box::pin(placeholder_network_future),
> ```

use .boxed()
___
*[`crates/starknet_mempool_p2p/src/lib.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2692#-OESs_nE519vmAhldgkJ:-OESs_nE519vmAhldgkK:b-6ysdk3) ([raw file](https://github.com/starkware-libs/sequencer/blob/b8c21bf2a4de109ddec117a7be1f3fcf82a8e821/crates/starknet_mempool_p2p/src/lib.rs#L34)):*
> ```XML
>     let mempool_p2p_propagator = MempoolP2pPropagator::new(broadcast_topic_client.clone());
>     let mempool_p2p_runner = MempoolP2pRunner::new(
>         Box::pin(network_future),
> ```

use .boxed() instead

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2692)* status: all files reviewed, 4 unresolved discussions (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 89 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2692#-OESunCRElKVuRTkvVdZ:-OEiFh4m6bSqFxS4wJJ9:b-ut7np8) ([raw file](https://github.com/starkware-libs/sequencer/blob/21535eea724b74f960a5342f26890a7ff0e2e567/crates/starknet_mempool_p2p/src/runner/test.rs#L89)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2692#-OESuv0y-qvmo5GMqv4k:-OEiFlZH2e4T2YIhoT5p:b-ut7np8) ([raw file](https://github.com/starkware-libs/sequencer/blob/21535eea724b74f960a5342f26890a7ff0e2e567/crates/starknet_mempool_p2p/src/runner/test.rs#L94)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 31 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2692#-OEiG93r1XZgJrZvMmcs:-OEiG93r1XZgJrZvMmct:bda8pk9) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ebf5bcde7d9a7c595ca0389bd815048f547a4c1/crates/starknet_mempool_p2p/src/runner/test.rs#L31)):*
> ```XML
>     network_future: BoxFuture<'static, Result<(), NetworkError>>,
>     gateway_client: Arc<dyn GatewayClient>,
> ) -> MempoolP2pRunner {
> ```

Return the mock_network too and use the setup function in the last test as well

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2692)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @eitanm-starkware and @ShahakShama)

___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 89 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2692#-OESunCRElKVuRTkvVdZ:-OEiTNI481PdZRmYyGv0:b-zg8ama) ([raw file](https://github.com/starkware-libs/sequencer/blob/21535eea724b74f960a5342f26890a7ff0e2e567/crates/starknet_mempool_p2p/src/runner/test.rs#L89)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I don't see it
</blockquote></details>

Take 2
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2692#-OESuv0y-qvmo5GMqv4k:-OEiTP1j2_pkeQaBkrhZ:b9b44u2) ([raw file](https://github.com/starkware-libs/sequencer/blob/21535eea724b74f960a5342f26890a7ff0e2e567/crates/starknet_mempool_p2p/src/runner/test.rs#L94)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I don't see it
</blockquote></details>

runner initialization moved to setup
___
*[`crates/starknet_mempool_p2p/src/runner/test.rs` line 31 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2692#-OEiG93r1XZgJrZvMmcs:-OEiT5UQDwJhJxkZwuWB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ebf5bcde7d9a7c595ca0389bd815048f547a4c1/crates/starknet_mempool_p2p/src/runner/test.rs#L31)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Return the mock_network too and use the setup function in the last test as well
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2692#-:-OEiaALhE5rY98b87ALq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Pull request merged**
