### PR TITLE
fix(ci): move specific versioned deps to root toml

### PR DESCRIPTION
**Pull request by dorimedini-starkware**

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2487)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @aner-starkware)

___
*[`crates/starknet_sierra_compile/build.rs` line 0 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2487#-ODM0vOlEcb1w6LXwvTf:-ODM0vOlEcb1w6LXwvTg:b-k6479k) ([raw file](https://github.com/starkware-libs/sequencer/blob/092b4818b722684087734ac5984dde4bd1bf7ef2/crates/starknet_sierra_compile/build.rs#L0)):*
changes here are unrelated to the scope of this PR but they seem like logical merge conflicts from today

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2487)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/starknet_sierra_compile/build.rs` line 138 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2487#-ODM2gEg46xNxik0D7Ed:-ODM5hqr1vhXupfLGnon:b7ueswc) ([raw file](https://github.com/starkware-libs/sequencer/blob/092b4818b722684087734ac5984dde4bd1bf7ef2/crates/starknet_sierra_compile/build.rs#L138)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Is it not possible to `use` this? Similar question regarding `std::env` and `std::fs`
</blockquote></details>

we can, but not at the top of the module, because it's only used when the `cairo_native` feature is active (building without the feature will result in an `unused import` warning).
I prefer fully-qualifying the import over adding a `use` line right above this one

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2487)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @aner-starkware)

**Review by aner-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2487)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dorimedini-starkware)

**Comment by aner-starkware** [comment]
*[`crates/starknet_sierra_compile/build.rs` line 138 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2487#-ODM2gEg46xNxik0D7Ed:-ODM6D3--pKag8w8YUor:b-qvxuxr) ([raw file](https://github.com/starkware-libs/sequencer/blob/092b4818b722684087734ac5984dde4bd1bf7ef2/crates/starknet_sierra_compile/build.rs#L138)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we can, but not at the top of the module, because it's only used when the `cairo_native` feature is active (building without the feature will result in an `unused import` warning).
I prefer fully-qualifying the import over adding a `use` line right above this one
</blockquote></details>

What about `use` with the feature flag? :grin:

**Review by meship-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2487)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Comment by aner-starkware** [comment]
*[`crates/starknet_sierra_compile/build.rs` line 138 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2487#-ODM2gEg46xNxik0D7Ed:-ODML6qcEAawUpZwfgDw:b7ly67x) ([raw file](https://github.com/starkware-libs/sequencer/blob/092b4818b722684087734ac5984dde4bd1bf7ef2/crates/starknet_sierra_compile/build.rs#L138)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

also possible, we have examples of both absolute imports and gated-`use`s. you have a preference?
</blockquote></details>

I guess I prefer the latter— my reasoning is that if\when the flag goes away, the import is already in the right place. It's not really critical.

**Comment by ArniStarkware** [comment]
*[`crates/starknet_sierra_compile/build.rs` line  at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2487#-ODM0vOlEcb1w6LXwvTf:-ODMMLft7_mVVV3DV-HC:bn3f79b) ([raw file](https://github.com/starkware-libs/sequencer/blob/092b4818b722684087734ac5984dde4bd1bf7ef2/crates/starknet_sierra_compile/build.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

changes here are unrelated to the scope of this PR but they seem like logical merge conflicts from today
</blockquote></details>

Similar to : #2495. which was just approved.

**Pull request merged**
