### PR TITLE
test(blockifier): execute_directly with v3 invoke instead of deprecated

### PR DESCRIPTION
**Pull request by TzahiTaub**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1770)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1770#-OAn27JR1RoyEd-1BEQH:-OAn27JR1RoyEd-1BEQI:bp4mw6a) ([raw file](https://github.com/starkware-libs/sequencer/blob/59b4d31acc83719b4a822b3aa72f79adbafe9d01/crates/blockifier/src/test_utils/struct_impls.rs#L58)):*
> ```XML
>         let default_invoke_tx = account_invoke_tx(InvokeTxArgs::default());
>         let tx_info = default_invoke_tx.create_tx_info();
>         assert!(matches!(tx_info, TransactionInfo::Current(_)));
> ```

this is an awkward way to get the desired default tx context...
maybe add a `&TransactionInfo` input to this method? is it possible?



_Code quote:_
```XML
        let limit_steps_by_resources = false;
        let default_invoke_tx = account_invoke_tx(InvokeTxArgs::default());
        let tx_info = default_invoke_tx.create_tx_info();
        assert!(matches!(tx_info, TransactionInfo::Current(_)));
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1770)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1770#-OAn27JR1RoyEd-1BEQH:-OAqT8QNAEoO4fBSLONZ:b7qzw70) ([raw file](https://github.com/starkware-libs/sequencer/blob/59b4d31acc83719b4a822b3aa72f79adbafe9d01/crates/blockifier/src/test_utils/struct_impls.rs#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is an awkward way to get the desired default tx context...
maybe add a `&TransactionInfo` input to this method? is it possible?
</blockquote></details>

But I want to save the callers this boilerplate code

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1770)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1770#-OAn27JR1RoyEd-1BEQH:-OAr8i6k6g88xuLeRlnA:bq80r9v) ([raw file](https://github.com/starkware-libs/sequencer/blob/59b4d31acc83719b4a822b3aa72f79adbafe9d01/crates/blockifier/src/test_utils/struct_impls.rs#L58)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

But I want to save the callers this boilerplate code
</blockquote></details>

add `CurrentTransactionInfo::default_for_testing`

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1770)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1770#-OAn27JR1RoyEd-1BEQH:-OArFM6G0Cqq9P4WKmXh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/59b4d31acc83719b4a822b3aa72f79adbafe9d01/crates/blockifier/src/test_utils/struct_impls.rs#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add `CurrentTransactionInfo::default_for_testing`
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1770#-:-OArW8ti5Lt2m_P4VJGk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/transaction/objects.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1770#-OArVsEN3Woynm0cSN9L:-OArVsEN3Woynm0cSN9M:b-61g120) ([raw file](https://github.com/starkware-libs/sequencer/blob/b1cd0aa0268a358a09bf2cab786a2c4b4bbf6e8f/crates/blockifier/src/transaction/objects.rs#L126)):*
> ```XML
>         Self {
>             common_fields: CommonAccountFields::default(),
>             resource_bounds: ValidResourceBounds::create_for_testing(),
> ```

this gives AllResources that are nonzero, right?



_Code quote:_
```XML
ValidResourceBounds::create_for_testing()
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1770)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1770#-OArVsEN3Woynm0cSN9L:-OAsHx903ubuUTApW6JC:b28utxe) ([raw file](https://github.com/starkware-libs/sequencer/blob/b1cd0aa0268a358a09bf2cab786a2c4b4bbf6e8f/crates/blockifier/src/transaction/objects.rs#L126)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this gives AllResources that are nonzero, right?
</blockquote></details>

GasAmount for L2 is high, price is 0, and for the other two, amount is 1 and price is 0. This is to keep enforce_fee==False.

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1770)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
