### PR TITLE
feat(batcher): abort proposal in send_proposal_content

### PR DESCRIPTION
**Pull request by dafnamatsry**

### CODE REVIEW

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2099#-:-OBtmjawA7rLRQblZryD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware and @Yael-Starkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2099)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware and @Yael-Starkware)

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2099)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @matan-starkware)

___
*[`crates/starknet_batcher_types/src/batcher_types.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2099#-OBuA8MQ4LCMbrtTxYVH:-OBuA8MQ4LCMbrtTxYVI:bfr4hd8) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3ece972c66e61538f01b5dcbc05f6b095e3c62d/crates/starknet_batcher_types/src/batcher_types.rs#L100)):*
> ```XML
>     // Only sent in response to `Finish`.
>     Finished(ProposalCommitment),
>     // Only sent in response to `Abort`.
> ```

I see in the consensus code that is can also be sent in response to Finish and Txs



_Code quote:_
```XML
// Only sent in response to `Abort`.
```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2099)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware and @Yael-Starkware)

___
*[`crates/starknet_batcher_types/src/batcher_types.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2099#-OBuA8MQ4LCMbrtTxYVH:-OBuBYnS7DJ8Es9MsAyY:b-fin735) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3ece972c66e61538f01b5dcbc05f6b095e3c62d/crates/starknet_batcher_types/src/batcher_types.rs#L100)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I see in the consensus code that is can also be sent in response to Finish and Txs
</blockquote></details>

Where did you see that?
The consensus is the one initiating the abort' so it should send Finish or Txs on aborted proposal.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2099)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @matan-starkware)

___
*[`crates/starknet_batcher_types/src/batcher_types.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2099#-OBuA8MQ4LCMbrtTxYVH:-OBuKZpY8m1oalN_Hc1i:b-aefw9m) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3ece972c66e61538f01b5dcbc05f6b095e3c62d/crates/starknet_batcher_types/src/batcher_types.rs#L100)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Where did you see that?
The consensus is the one initiating the abort' so it should send Finish or Txs on aborted proposal.
</blockquote></details>

here in the PR. :


let input = SendProposalContentInput { proposal_id, content: SendProposalContent::Finish };
    let response = batcher
        .send_proposal_content(input)
        .await
        .unwrap_or_else(|e| panic!("Failed to send Fin to batcher: {proposal_id:?}. {e:?}"));
    let id = match response.response {
        ProposalStatus::Finished(id) => id,
        ProposalStatus::Processing => {
            panic!("Batcher failed to return Fin after all content was sent: {:?}", proposal_id);
        }
        ProposalStatus::Aborted => {
            warn!("Proposal was aborted: {:?}", proposal_id);
            return;
        }
        ProposalStatus::InvalidProposal => {
            warn!("Proposal was invalid: {:?}", proposal_id);

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2099)* status: all files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 371 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2099#-OBxsIIfBvRZA4lCN-Qn:-OBxsIIfBvRZA4lCN-Qo:bb7hf91) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3ece972c66e61538f01b5dcbc05f6b095e3c62d/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L371)):*
> ```XML
>                 panic!("Batcher returned Fin before all content was sent: {proposal_id:?} {fin:?}");
>             }
>             ProposalStatus::Aborted => {
> ```

here



_Code quote:_
```XML
ProposalStatus::Aborted
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 393 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2099#-OBxsFVE4thT7XOueagx:-OBxsFVE4thT7XOueagy:bji28bi) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3ece972c66e61538f01b5dcbc05f6b095e3c62d/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L393)):*
> ```XML
>             panic!("Batcher failed to return Fin after all content was sent: {:?}", proposal_id);
>         }
>         ProposalStatus::Aborted => {
> ```

and here



_Code quote:_
```XML
ProposalStatus::Aborted
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2099)* status: all files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @matan-starkware)

___
*[`crates/starknet_batcher_types/src/batcher_types.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2099#-OBuA8MQ4LCMbrtTxYVH:-OBxsQYQAnSsus63-__o:bclsam0) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3ece972c66e61538f01b5dcbc05f6b095e3c62d/crates/starknet_batcher_types/src/batcher_types.rs#L100)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

here in the PR. :


let input = SendProposalContentInput { proposal_id, content: SendProposalContent::Finish };
    let response = batcher
        .send_proposal_content(input)
        .await
        .unwrap_or_else(|e| panic!("Failed to send Fin to batcher: {proposal_id:?}. {e:?}"));
    let id = match response.response {
        ProposalStatus::Finished(id) => id,
        ProposalStatus::Processing => {
            panic!("Batcher failed to return Fin after all content was sent: {:?}", proposal_id);
        }
        ProposalStatus::Aborted => {
            warn!("Proposal was aborted: {:?}", proposal_id);
            return;
        }
        ProposalStatus::InvalidProposal => {
            warn!("Proposal was invalid: {:?}", proposal_id);
</blockquote></details>

I assume it should panic in that case?

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2099)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @alonh5, @matan-starkware, and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 371 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2099#-OBxsIIfBvRZA4lCN-Qn:-OBy69D_1CADEAqgES4G:b-khxfwi) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3ece972c66e61538f01b5dcbc05f6b095e3c62d/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L371)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

here
</blockquote></details>

I added those lines...
It is not expected to happen. 
I can use `panic!` instead of `warn!`. @matan-starkware ?
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 393 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2099#-OBxsFVE4thT7XOueagx:-OBy6g9k3dj-8EXuAkEL:b-816h6l) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3ece972c66e61538f01b5dcbc05f6b095e3c62d/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L393)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

and here
</blockquote></details>

Same.

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2099)* status: all files reviewed, 3 unresolved discussions (waiting on @matan-starkware and @Yael-Starkware)

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2099)* status: all files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 371 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2099#-OBxsIIfBvRZA4lCN-Qn:-OBz2yhj5kSSxpMWSjwA:beqqvce) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3ece972c66e61538f01b5dcbc05f6b095e3c62d/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L371)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I added those lines...
It is not expected to happen. 
I can use `panic!` instead of `warn!`. @matan-starkware ?
</blockquote></details>

I'm fine with panicing for now, but I reserve the right to change this to an error log in the future. This is an external component failing, so not clear that I really want to panic. On the other hand the Batcher is a critical dependency so IDK what I would do if it fails like this...

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2099)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @dafnamatsry)

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2099)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Comment by dafnamatsry** [comment]
### Merge activity

* **Nov 18, 10:23 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2099).

**Pull request merged**
