### PR TITLE
refactor: use clap workspace in committer cli

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/315)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/315?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#317** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/317?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#316** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/316?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#315** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/315?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#313** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/313?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#311** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/311?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main-v0.13.2`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/315)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`Cargo.toml` line 78 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/315#-O3a_JyWDgF5FCU97V40:-O3a_JyWDgF5FCU97V41:bb8tdxa) ([raw file](https://github.com/starkware-libs/sequencer/blob/08e385d0425bf8c7e82b50cb6084695940a430f6/Cargo.toml#L78)):*
> ```TOML
> camelpaste = "0.1.0"
> chrono = "0.4.26"
> clap = { version = "4.5.4", features = ["cargo", "derive"] }
> ```

no features on root cargo toml (see first PR)



_Code quote:_
```TOML
clap = { version = "4.5.4", features = ["cargo", "derive"] }
```
___
*[`crates/committer_cli/Cargo.toml` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/315#-O3a_Mvm6bTDF56ihzqs:-O3a_Mvm6bTDF56ihzqt:bvtf95a) ([raw file](https://github.com/starkware-libs/sequencer/blob/08e385d0425bf8c7e82b50cb6084695940a430f6/crates/committer_cli/Cargo.toml#L19)):*
> ```TOML
> 
> [dependencies]
> clap.workspace = true
> ```

features here

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/315)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`Cargo.toml` line 78 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/315#-O3a_WJLBeswD31071u9:-O3a_WJLBeswD31071uA:b-4ziemu) ([raw file](https://github.com/starkware-libs/sequencer/blob/08e385d0425bf8c7e82b50cb6084695940a430f6/Cargo.toml#L78)):*
> ```TOML
> camelpaste = "0.1.0"
> chrono = "0.4.26"
> clap = { version = "4.5.4", features = ["cargo", "derive"] }
> ```

what will happen if you keep the `4.3.10` version? semver should allow upgrading to 4.5.4, only the minor version is bumped



_Code quote:_
```TOML
clap = { version = "4.5.4", features = ["cargo", "derive"] }
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/315#-:-O3hK30g9-qmRItou-XT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Comment by AvivYossef-starkware** [comment]
### Merge activity

* **Aug 8, 6:40 AM EDT**: @AvivYossef-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/315).

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/315)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/315)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/315)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/315)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
