### PR TITLE
fix(blockifier_reexecution): bug in rpc get state diff

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1797?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1797** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1797?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1796** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1796?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1765** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1765?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1759** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1759?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1758** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1758?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1712** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1712?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1797#-:-OAwV37i2-vivGfInrHN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1797)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Comment by AvivYossef-starkware** [comment]
### Merge activity

* **Nov 6, 10:20 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1797).

**Pull request merged**
