### PR TITLE
refactor(consensus): get_proposal + propose -> repropose

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1275)

### CODE REVIEW

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1275)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1275#-O8lGq2b3TgiQLR06huY:-O8lGq2b3TgiQLR06huZ:bst6xlm) ([raw file](https://github.com/starkware-libs/sequencer/blob/f30aaa4322dd8c1941cd611b861a784bf542edb5/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs#L204)):*
> ```XML
>             let Some(proposals_at_height) = valid_proposals_lock.get(&init.height) else {
>                 error!("No proposals found for height {}", init.height);
>                 return Err(ConsensusError::InvalidProposal(
> ```

since shc uses .expect(), error handling isn't really a matter. 
wouldn't it be better to use Result instead of using so many .expect() calls? WDYT?

**Review by matan-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1275)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1275#-O8lGq2b3TgiQLR06huY:-O945I1m7rxRhdrVwgd6:bj7n3cv) ([raw file](https://github.com/starkware-libs/sequencer/blob/f30aaa4322dd8c1941cd611b861a784bf542edb5/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs#L204)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

since shc uses .expect(), error handling isn't really a matter. 
wouldn't it be better to use Result instead of using so many .expect() calls? WDYT?
</blockquote></details>

Responded in slack. Conceptually I'm fine with the direction, but this should be a separate milestone. Please remove from this PR.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1275)* status: all files reviewed, 3 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1275#-O94mLvJ08S-ZvZAXOEw:-O94mLvJ08S-ZvZAXOEx:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0507250c858da28e52ea8677d83a6e6553ca2d23/crates/sequencing/papyrus_consensus/src/types.rs#L82)):*
> ```XML
>     /// Params:
>     /// - `id`: The `ProposalContentId` associated with the block's content.
>     /// - `init`: The `ProposalInit` that provides initialization parameters for the proposal.
> ```





_Suggestion:_
```XML
    /// - `init`: The `ProposalInit` that is broadcast to the network.
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs` line 205 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1275#-O94nKDd212zgOnHnvJr:-O94nKDe1wHEdUNjElZR:b-7zi8ni) ([raw file](https://github.com/starkware-libs/sequencer/blob/0507250c858da28e52ea8677d83a6e6553ca2d23/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs#L205)):*
> ```XML
>             });
>             transactions.clone()
>         };
> ```

WDYT?



_Suggestion:_
```XML
        let transactions = valid_proposals
            .lock()
            .expect("valid_proposals lock was poisoned")
            .get(&init.height)
            .unwrap_or_else(|| panic!("No proposals found for height {}", init.height))
            .get(&id)
            .unwrap_or_else(|| panic!("No proposal found for height {} and id {}", init.height, id))
            .clone();
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs` line 218 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1275#-O94nZeE7M-WRX6L5dII:-O94nZeE7M-WRX6L5dIJ:b6zjkou) ([raw file](https://github.com/starkware-libs/sequencer/blob/0507250c858da28e52ea8677d83a6e6553ca2d23/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs#L218)):*
> ```XML
>             .broadcast_message(ConsensusMessage::Proposal(proposal))
>             .await
>             .expect("Failed to send proposal");
> ```

No need to clone since we're not spawning a new task



_Suggestion:_
```XML
        self.network_broadcast_client
            .broadcast_message(ConsensusMessage::Proposal(proposal))
            .await
            .expect("Failed to send proposal");
```

**Review by matan-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1275)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1275)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1275#-O94mLvJ08S-ZvZAXOEw:-O94sWK08MJ63vzGE8yU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0507250c858da28e52ea8677d83a6e6553ca2d23/crates/sequencing/papyrus_consensus/src/types.rs#L82)):*
> ```XML
>     /// Params:
>     /// - `id`: The `ProposalContentId` associated with the block's content.
>     /// - `init`: The `ProposalInit` that provides initialization parameters for the proposal.
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs` line 218 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1275#-O94nZeE7M-WRX6L5dII:-O94sBN08j0oW6YZlSGA:b-w9jex5) ([raw file](https://github.com/starkware-libs/sequencer/blob/0507250c858da28e52ea8677d83a6e6553ca2d23/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs#L218)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

No need to clone since we're not spawning a new task
</blockquote></details>

mutable reference is needed

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1275)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs` line 218 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1275#-O94nZeE7M-WRX6L5dII:-O99IgCaAZKstG3puGpp:b-u1qx79) ([raw file](https://github.com/starkware-libs/sequencer/blob/0507250c858da28e52ea8677d83a6e6553ca2d23/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs#L218)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

mutable reference is needed
</blockquote></details>

Just change the API then to `&mut self` it's what we did for the other functions.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1275)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
