### PR TITLE
feat(network): make StreamHashMap notify when a stream is finished

### PR DESCRIPTION
**Pull request by AlonLStarkWare**

### CODE REVIEW

**Review by guy-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1439)* status: all files reviewed, 3 unresolved discussions (waiting on @AlonLStarkWare)

___
*[`crates/papyrus_network/src/utils.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1439#-O9FIa16BZwS2eH_ItmX:-O9FIa16BZwS2eH_ItmY:b-apto4p) ([raw file](https://github.com/starkware-libs/sequencer/blob/040d5d9db4a4d1b183183a60e7a0eee6a4d94e47/crates/papyrus_network/src/utils.rs#L55)):*
> ```XML
>     fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
>         let unpinned_self = Pin::into_inner(self);
>         let mut finished_stream: Option<K> = None;
> ```

Maybe `finished_stream_key`?

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1439)

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1439)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @guy-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/utils.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1439#-O9FIa16BZwS2eH_ItmX:-O9FN8TCBSxbn0Fpas16:b757pjs) ([raw file](https://github.com/starkware-libs/sequencer/blob/040d5d9db4a4d1b183183a60e7a0eee6a4d94e47/crates/papyrus_network/src/utils.rs#L55)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

Maybe `finished_stream_key`?
</blockquote></details>

I like it
___
*[`crates/papyrus_network/src/utils.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1439#-O9FHVpu8Qvi3BLikt3m:-O9FNJzZ1keBJ5SKpwXD:bcdi0fv) ([raw file](https://github.com/starkware-libs/sequencer/blob/040d5d9db4a4d1b183183a60e7a0eee6a4d94e47/crates/papyrus_network/src/utils.rs#L62)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Try to concise it. Move it just above the break and write: "breaking and removing the finished stream from the map outside of the loop because we can't have two mutable references to the map"
</blockquote></details>

Is the "because" part necessary?
___
*[`crates/papyrus_network/src/utils.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1439#-O9FHvJeA_GiA9cPd-fK:-O9FNbBZ64VXfoAD5zp3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/040d5d9db4a4d1b183183a60e7a0eee6a4d94e47/crates/papyrus_network/src/utils.rs#L71)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

unpinned_self.map.remove(
IDK why the old code was written like that
</blockquote></details>

Done.

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1439)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @AlonLStarkWare and @guy-starkware)

___
*[`crates/papyrus_network/src/utils.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1439#-O9FHVpu8Qvi3BLikt3m:-O9FO1LY626eCLIz9vI3:b2nign6) ([raw file](https://github.com/starkware-libs/sequencer/blob/040d5d9db4a4d1b183183a60e7a0eee6a4d94e47/crates/papyrus_network/src/utils.rs#L62)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

Is the "because" part necessary?
</blockquote></details>

yes

**Review by guy-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1439#-:-O9FOCMC4k8tE5KavMak:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @AlonLStarkWare)

**Review by AlonLStarkWare — COMMENTED** [review]
> Dismissed @ShahakShama from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1439)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1439#-:-OAC0b-G4S2gkn-qdMWt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Pull request merged**
