### PR TITLE
feat(blockifier): implement and test max_steps computation for the L2 gas bound case

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1290)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1290?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1290** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1290?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1289** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1289?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yoavGrs — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1290)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 284 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1290#-O93ysGqAJBq0zCPzt8X:-O93ysGrDQBRrBsrRvNY:bwgl35x) ([raw file](https://github.com/starkware-libs/sequencer/blob/131e4589c603cd7f51a0db2f665112ed64f14147/crates/blockifier/src/execution/entry_point.rs#L284)):*
> ```XML
>         // New transactions with only L1 bounds use the L1 resource bounds directly.
>         // New transactions with L2 bounds use the L2 bounds directly.
>         let l1_gas_per_step = versioned_constants.vm_resource_fee_cost().n_steps;
> ```

It's not the number of steps, right?
Consider renaming it to something like `step_cost`.



_Code quote:_
```XML
n_steps
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1012 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1290#-O94Euc77oYt5TkidsPb:-O94Euc77oYt5TkidsPc:bwzxgmv) ([raw file](https://github.com/starkware-libs/sequencer/blob/131e4589c603cd7f51a0db2f665112ed64f14147/crates/blockifier/src/transaction/account_transactions_test.rs#L1012)):*
> ```XML
>     assert_max_steps_as_expected!(
>         account_tx_max_fee,
>         (block_context.versioned_constants.vm_resource_fee_cost().n_steps.inv()
> ```

It's more readable



_Suggestion:_
```XML
    let steps_per_l1_gas = block_context.versioned_constants.vm_resource_fee_cost().n_steps.inv();
    assert_max_steps_as_expected!(
        account_tx_max_fee,
        (steps_per_l1_gas
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1041 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1290#-O94FIlu31HM4CTEb-_g:-O94FIlvD6moRqf3bcAB:b-4wpg9h) ([raw file](https://github.com/starkware-libs/sequencer/blob/131e4589c603cd7f51a0db2f665112ed64f14147/crates/blockifier/src/transaction/account_transactions_test.rs#L1041)):*
> ```XML
>         resource_bounds: ValidResourceBounds::AllResources(AllResourceBounds {
>             l2_gas: ResourceBounds {
>                 max_amount: l2_gas_bound.into(), max_price_per_unit: 1_u8.into()
> ```

How does it affect the result?



_Code quote:_
```XML
max_price_per_unit: 1_u8.into()
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1290)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 284 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1290#-O93ysGqAJBq0zCPzt8X:-O94a8OjAyvySpNVkAD4:bsgdvfk) ([raw file](https://github.com/starkware-libs/sequencer/blob/131e4589c603cd7f51a0db2f665112ed64f14147/crates/blockifier/src/execution/entry_point.rs#L284)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

It's not the number of steps, right?
Consider renaming it to something like `step_cost`.
</blockquote></details>

this is a field in the versioned constants - it's sensitive to changes. can be done in a separate PR
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1041 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1290#-O94FIlu31HM4CTEb-_g:-O94bAbC54oIucY9FtVB:bkg6czx) ([raw file](https://github.com/starkware-libs/sequencer/blob/131e4589c603cd7f51a0db2f665112ed64f14147/crates/blockifier/src/transaction/account_transactions_test.rs#L1041)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

How does it affect the result?
</blockquote></details>

it doesn't; changed to the default for clarity

**Review by yoavGrs — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1290)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1033 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1290#-O94ogheBPhLZdhiZ5T3:-O94oghf2mMBYrB7dV0D:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/38aab0f1eee379b24a74b66aa951b11e5e14d24c/crates/blockifier/src/transaction/account_transactions_test.rs#L1033)):*
> ```XML
>     assert_max_steps_as_expected!(
>         account_tx_l1_bounds,
>         (block_context.versioned_constants.vm_resource_fee_cost().n_steps.inv() * l1_gas_bound)
> ```





_Suggestion:_
```XML
steps_per_l1_gas
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1290)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1033 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1290#-O94ogheBPhLZdhiZ5T3:-O94tfQq9BkidfxQh6P1:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/38aab0f1eee379b24a74b66aa951b11e5e14d24c/crates/blockifier/src/transaction/account_transactions_test.rs#L1033)):*
> ```XML
>     assert_max_steps_as_expected!(
>         account_tx_l1_bounds,
>         (block_context.versioned_constants.vm_resource_fee_cost().n_steps.inv() * l1_gas_bound)
> ```

Done.

**Review by yoavGrs — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1290)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1290)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
