### PR TITLE
refactor(batcher): block builder test, add case for block full

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1614?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1614** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1614?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1610** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1610?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1562** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1562?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1561** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1561?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1539** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1539?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Yael-Starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1614)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/batcher/src/block_builder_test.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1614#-OANKgqHBdTpXg2z2-sn:-OANKgqHBdTpXg2z2-so:b-hat1nm) ([raw file](https://github.com/starkware-libs/sequencer/blob/c23730fde6c7d0a009f7819f47921c063566e505/crates/batcher/src/block_builder_test.rs#L194)):*
> ```XML
> }
> 
> fn mock_mempool_client(
> ```

Consider having a "base" mock mempool client that can only be queried n_chunks times, and adding the addtional empty expectations in another function, instead of this bool arg that is only used for this one case.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1614)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/batcher/src/block_builder_test.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1614#-OANKgqHBdTpXg2z2-sn:-OARAz_F1RixeV9HrNv5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c23730fde6c7d0a009f7819f47921c063566e505/crates/batcher/src/block_builder_test.rs#L194)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Consider having a "base" mock mempool client that can only be queried n_chunks times, and adding the addtional empty expectations in another function, instead of this bool arg that is only used for this one case.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1614#-:-OAS7IZi-JiWTUQ77Lxc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1614)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Comment by Yael-Starkware** [comment]
### Merge activity

* **Oct 31, 8:18 AM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1614).

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1614)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
