### PR TITLE
chore(blockifier): use infra_utils for fetching manifest dir

### PR DESCRIPTION
**Pull request by dorimedini-starkware**

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2289#-:-OCctOsN4Icsk5HpPI4l:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2289)* status: 6 of 10 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2289#-OCd-GSP5J3B5fvkXWmG:-OCd-GSP5J3B5fvkXWmH:b-2y4go9) (no related file):*
[py side](https://reviewable.io/reviews/starkware-industries/starkware/36326)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 3 of 10 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2289)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2289)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2289#-OCd-GSP5J3B5fvkXWmG:-ODLyRXh3Xcs3g4LRgMy:b-m6tfm3) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[py side](https://reviewable.io/reviews/starkware-industries/starkware/36326)
</blockquote></details>

passed

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 7 files at r7, 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2289)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 8 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2289)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 8 of 8 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2289)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
