### PR TITLE
chore(blockifier): rename BouncerWeights field gas to l1gas

### PR DESCRIPTION
**Pull request by avivg-starkware**

### CODE REVIEW

**Comment by avivg-starkware** [comment]
* **#2527** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2527?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2527?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
Py side? (it should break)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2527#-:-ODb0JE5-fKMiehSmgDW:bkmru68)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2527#-ODb0OpqEQjirptMv-kw:-ODb0OpqEQjirptMv-kx:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c43b6d037c6a4bc313ef8cb6109f0a9268851a3/crates/blockifier/src/bouncer.rs#L106)):*
> ```XML
>     impl_checked_sub!(
>         builtin_count,
>         l1gas,
> ```





_Suggestion:_
```XML
l1_gas
```

**Review by avivg-starkware — COMMENTED** [review]
Still working on it, will put you on the PR as soon as it is ready to check

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2527#-:-ODeo0nAAiwK053qE_u-:b27qtq6)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2527#-ODb0OpqEQjirptMv-kw:-ODeo4GQ3YUaHUkNKiUU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c43b6d037c6a4bc313ef8cb6109f0a9268851a3/crates/blockifier/src/bouncer.rs#L106)):*
> ```XML
>     impl_checked_sub!(
>         builtin_count,
>         l1gas,
> ```

Done.

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2527)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2527)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/abi/constants.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2527#-ODfYpXlAIY-6hbsiMSJ:-ODfZeByBhB_pIVkzRjr:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbd812927cf19528f354910f736df3390585f984/crates/blockifier/src/abi/constants.rs#L28)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Revert, this is not related to your PR
</blockquote></details>

Done.

**Review by avivg-starkware — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2527)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2527#-:-ODgIUVo5iSJ0jdyrwZX:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @avivg-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2527)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Pull request merged**
