### PR TITLE
feat(blockifier): update cairo native to 0.2.2-alpha.0

### PR DESCRIPTION
**Pull request by rodrigo-pino**

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2076)* status: 16 of 18 files reviewed, all discussions resolved

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2076)* status: all files reviewed, 2 unresolved discussions (waiting on @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2076#-OBswRcG4pkIkc_C7JBu:-OBswRcH0KBhUmwowJ-R:b9cgy6e) ([raw file](https://github.com/starkware-libs/sequencer/blob/5769b9ab1c59ffbe72ddb37bbf7c8dea9b40bc52/crates/blockifier/src/execution/native/entry_point_execution.rs#L25)):*
> ```XML
>     context: &mut EntryPointExecutionContext,
> ) -> EntryPointExecutionResult<CallInfo> {
>     let function_selector = call.entry_point_selector.0;
> ```

Please go through `.get_entry_point()` since it returns an error if the entrypoint is not found.
You can change the return type of this function.

Please add a TODO to test entrypoint-not-found in native.



_Code quote:_
```XML
let function_selector = call.entry_point_selector.0;
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2076#-OBsv1sIDfe3_2fmIdb-:-OBsv1sJ0G3t1e3I_uhQ:bi0d7xv) ([raw file](https://github.com/starkware-libs/sequencer/blob/5769b9ab1c59ffbe72ddb37bbf7c8dea9b40bc52/crates/blockifier/src/execution/native/entry_point_execution.rs#L34)):*
> ```XML
>         &syscall_handler.call.calldata.0.clone(),
>         Some(syscall_handler.call.initial_gas.into()),
>         // Todo(rodrigo): What should be the builtin costs?
> ```

Same as in here: https://github.com/starkware-libs/sequencer/blob/48c155deac68322f9bc6cdf109a27321cc3d7176/crates/blockifier/src/execution/entry_point_execution.rs#L205



_Code quote:_
```XML
        // Todo(rodrigo): What should be the builtin costs?
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2076)* status: 16 of 19 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/contract_class.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2076#-OBt9jVzCONNpBPt8eg3:-OBt9jVzCONNpBPt8eg4:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/a16a6200da4d5761142031d1b8d19a4d1467c506/crates/blockifier/src/execution/native/contract_class.rs#L20)):*
> ```XML
> impl NativeContractClassV1 {
>     pub(crate) fn constructor_selector(&self) -> Option<EntryPointSelector> {
>         self.casm.entry_points_by_type.constructor.first().map(|ep| ep.selector)
> ```





_Suggestion:_
```XML
self.casm.constructor_selector()
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 18 files at r6, 1 of 2 files at r7, 1 of 14 files at r10, 3 of 13 files at r13, 2 of 2 files at r14, 10 of 10 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2076#-:-OC--ZOa3e-8FxEBGJKB:bnfp4nl)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/contract_class.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2076#-OBt9jVzCONNpBPt8eg3:-OBzz0Te97xsejUFeyva:b2nhswy) ([raw file](https://github.com/starkware-libs/sequencer/blob/a16a6200da4d5761142031d1b8d19a4d1467c506/crates/blockifier/src/execution/native/contract_class.rs#L20)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

`constructor_selector` is a private class, should I make it public for this instance?
</blockquote></details>

Yes

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2076)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/contract_class.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2076#-OBt9jVzCONNpBPt8eg3:-OC-2GzP4AM9PofxKbWq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a16a6200da4d5761142031d1b8d19a4d1467c506/crates/blockifier/src/execution/native/contract_class.rs#L20)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

Done.

**Review by Yoni-Starkware — COMMENTED** [review]
:lgtm:

> Reviewed 13 of 14 files at r16.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2076#-:-OC-94tdCVkF6ViJXoXc:bnfp4nl)* status: 9 of 22 files reviewed, all discussions resolved (waiting on @meship-starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 14 files at r16, 2 of 2 files at r17, 9 of 10 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2076)* status: 20 of 22 files reviewed, all discussions resolved (waiting on @meship-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 18 files at r6, 1 of 10 files at r18.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2076)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Pull request merged**
