### PR TITLE
refactor(blockifier): format retdata in ExecutionFailed and PanicInValidate errors

### PR DESCRIPTION
**Pull request by dorimedini-starkware**

### CODE REVIEW

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1457)

**Comment by dorimedini-starkware** [comment]
* **#1460** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1460?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1459** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1459?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1458** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1458?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1457** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1457?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1457#-:-O9c_i-R8lrzPMq0pzC1:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1457)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1457#-:-O9cx4sA2WayBT1MNhf2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
