### PR TITLE
refactor(consensus): ignore non-validator vote instead of returning e…

### PR DESCRIPTION
**Pull request by asmaastarkware**
…rror

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/651)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/651)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/651#-O5T2YlJ3TEZaqtSl-Gu:-O5T2YlJ3TEZaqtSl-Gv:b-me98v3) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef179615063921778835022e58871a6b3083138e/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L234)):*
> ```XML
>                 "Ignoring vote from voter not in validators: voter={:?}, validators={:?}",
>                 vote.voter, self.validators
>             );
> ```

Let's avoid printing the entire validator set. This should be printed out once for each height. The reason is that it's a list of variable length, so it could clog up the logs.

Please add a log in `MultiHeightManager::run_height` immediately after we get the validator list `info("running consensus for height X with validator set Y)`



_Suggestion:_
```XML
            debug!(
                "Ignoring vote from voter not in validators: vote={:?}",
                vote
            );
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/651#-O5T2UqZ8WSWrFQX_d-m:-O5T2UqZ8WSWrFQX_d-n:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef179615063921778835022e58871a6b3083138e/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L235)):*
> ```XML
>                 vote.voter, self.validators
>             );
>             return Ok(ShcReturn::Tasks(vec![]));
> ```





_Suggestion:_
```XML
Vec::new()
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/651)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/651#-O5T2YlJ3TEZaqtSl-Gu:-O5gM4lNDJAefv4w2Z_H:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef179615063921778835022e58871a6b3083138e/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L234)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's avoid printing the entire validator set. This should be printed out once for each height. The reason is that it's a list of variable length, so it could clog up the logs.

Please add a log in `MultiHeightManager::run_height` immediately after we get the validator list `info("running consensus for height X with validator set Y)`
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/651#-O5T2UqZ8WSWrFQX_d-m:-O5gM5WQ1fIycgNO-SkX:b-hk8zrm) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef179615063921778835022e58871a6b3083138e/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L235)):*
> ```XML
>                 vote.voter, self.validators
>             );
>             return Ok(ShcReturn::Tasks(vec![]));
> ```

I will replace it when rebasing to the refactor PR #650

**Review by matan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/651#-:-O5gmJT0DeY17yANq-9S:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/651)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
