### PR TITLE
test(consensus): handle repeated proposals and votes

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/187)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/187)* status: all files reviewed, 6 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O31Tdr3B7muqg8u8nMQ:-O31Tdr4EiJMMp7OMKDj:bewo6ji) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3ceddf9a042483687b5b361061f8fc2934073a1/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L191)):*
> ```XML
> 
>     let node_id: ValidatorId = 1_u32.into();
>     let proposer: ValidatorId = 2_u32.into();
> ```

We keep repeating this. Should we define top level statics like you did for the SM tests?



_Code quote:_
```XML
    let node_id: ValidatorId = 1_u32.into();
    let proposer: ValidatorId = 2_u32.into();
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O31UDT3-H-07StBvtLH:-O31UDT3-H-07StBvtLI:b-40fryj) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3ceddf9a042483687b5b361061f8fc2934073a1/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L240)):*
> ```XML
>     context
>         .expect_broadcast()
>         .times(1)
> ```

Also add to the precommit.



_Suggestion:_
```XML
        .times(1)  // Shows the repeat vote is ignored.
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O31UjUTD31LsnkNGaP4:-O31UjUTD31LsnkNGaP5:bv8ic4c) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3ceddf9a042483687b5b361061f8fc2934073a1/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L256)):*
> ```XML
>         .times(1)
>         .withf(move |msg: &ConsensusMessage| msg == &precommit(Some(block_id), 0, 0, node_id))
>         .returning(move |_| Ok(()));
> ```

Move this down so that it's adjacent with the prevote which triggers us sending the recommit. Makes reading the test easier.



_Code quote:_
```XML
    context
        .expect_broadcast()
        .times(1)
        .withf(move |msg: &ConsensusMessage| msg == &precommit(Some(block_id), 0, 0, node_id))
        .returning(move |_| Ok(()));
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 266 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O31UvNsCbyPu80ILce4:-O31UvNsCbyPu80ILce5:b-cw2375) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3ceddf9a042483687b5b361061f8fc2934073a1/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L266)):*
> ```XML
>     let decision =
>         shc.handle_message(&mut context, precommit(Some(block_id), 0, 0, 2_u32.into())).await;
>     assert_eq!(decision, Ok(None));
> ```

You sometimes call the returned value `res` and sometimes `decision`. Be consistent.



_Code quote:_
```XML
    let decision =
        shc.handle_message(&mut context, precommit(Some(block_id), 0, 0, 2_u32.into())).await;
    assert_eq!(decision, Ok(None));
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 274 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O31V40X8YiPOoELGxL4:-O31V40X8YiPOoELGxL5:bpcuszn) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3ceddf9a042483687b5b361061f8fc2934073a1/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L274)):*
> ```XML
>     // Send the same vote again, which should be ignored (already made a decision).
>     let res = shc.handle_message(&mut context, vote.clone()).await;
>     assert_eq!(res, Ok(None));
> ```

I would remove this to have a shorter test. We make no promises about what happens if messages are sent after a decision so I don't think it's important to cover.



_Code quote:_
```XML
    // Send the same vote again, which should be ignored (already made a decision).
    let res = shc.handle_message(&mut context, vote.clone()).await;
    assert_eq!(res, Ok(None));
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O31VWNHDeLePxzwds79:-O31VWNHDeLePxzwds7A:be3i8hb) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3ceddf9a042483687b5b361061f8fc2934073a1/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L278)):*
> ```XML
> 
> #[tokio::test]
> async fn repeat_proposal() {
> ```

This is logically similar to the above and there is a lot of code reuse. WDYT of just testing all 3 cases in a single test?



_Code quote:_
```XML
async fn repeat_proposal()
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/187)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O31Tdr3B7muqg8u8nMQ:-O323Pl10mNzjU7tynNu:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3ceddf9a042483687b5b361061f8fc2934073a1/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L191)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

We keep repeating this. Should we define top level statics like you did for the SM tests?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O31UDT3-H-07StBvtLH:-O323OpvEDODsHr9uAzf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3ceddf9a042483687b5b361061f8fc2934073a1/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L240)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Also add to the precommit.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O31UjUTD31LsnkNGaP4:-O32302y3kTf5NVUsZKs:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3ceddf9a042483687b5b361061f8fc2934073a1/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L256)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Move this down so that it's adjacent with the prevote which triggers us sending the recommit. Makes reading the test easier.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 266 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O31UvNsCbyPu80ILce4:-O323-5n8tA_9EC41F4L:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3ceddf9a042483687b5b361061f8fc2934073a1/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L266)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

You sometimes call the returned value `res` and sometimes `decision`. Be consistent.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 274 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O31V40X8YiPOoELGxL4:-O322ysA7X0aE3q8FCV2:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3ceddf9a042483687b5b361061f8fc2934073a1/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L274)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I would remove this to have a shorter test. We make no promises about what happens if messages are sent after a decision so I don't think it's important to cover.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O31VWNHDeLePxzwds79:-O323SpZEAY7UEFPGrxF:bwzxh8z) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3ceddf9a042483687b5b361061f8fc2934073a1/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L278)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This is logically similar to the above and there is a lot of code reuse. WDYT of just testing all 3 cases in a single test?
</blockquote></details>

I merged voting twice to a single test and proposing twice with validator test

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/187)* status: all files reviewed, 9 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O3373fQ5PeuYrJfpl3P:-O3373fRCe4MCquvI53M:b-52flxm) ([raw file](https://github.com/starkware-libs/sequencer/blob/5087e4b3bbe1dabdd2f618d5cb2b18e71c0a590c/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L137)):*
> ```XML
>         .expect_proposer()
>         .times(if repeat_proposal { 2 } else { 1 })
>         .returning(move |_, _| *PROPOSER_ID);
> ```

I don't really care how many times we check who the proposer is. The call to `validate_proposal` is the interesting one.



_Suggestion:_
```XML
    context
        .expect_proposer()
        .returning(move |_, _| *PROPOSER_ID);
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 144 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O337BAx1-073z1Go0iK:-O337BAx1-073z1Go0iL:b-2ym6d7) ([raw file](https://github.com/starkware-libs/sequencer/blob/5087e4b3bbe1dabdd2f618d5cb2b18e71c0a590c/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L144)):*
> ```XML
>             block_receiver
>         },
>     );
> ```

Ok this test is great because it made me realize that we are not handling repeats properly. We should not call `validate_proposal` twice. We need to change the code in `handle_proposal` to check for conflict/repeat at the beginning (just after we validate the `init` message).

This also means my comment about using `entry` is irrelevant since we currently only insert once we have the BlockHash.



_Suggestion:_
```XML
    context.expect_validate_proposal().times(1).returning(
        move |_, _| {
            let (block_sender, block_receiver) = oneshot::channel();
            block_sender.send(BLOCK.clone()).unwrap();
            block_receiver
        },
    );
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O338F9c66ou8dJIjAwU:-O338F9c66ou8dJIjAwV:b-gkd0vl) ([raw file](https://github.com/starkware-libs/sequencer/blob/5087e4b3bbe1dabdd2f618d5cb2b18e71c0a590c/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L155)):*
> ```XML
>         .handle_proposal(
>             &mut context,
>             ProposalInit { height: BlockNumber(0), round: 0, proposer: *PROPOSER_ID },
> ```

make a variable `proposal_init` so that it's obvious we send the same one and readers don't need to compare fields.



_Code quote:_
```XML
ProposalInit { height: BlockNumber(0), round: 0, proposer: *PROPOSER_ID },
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O338RPY6v7HhipgBL_4:-O338RPY6v7HhipgBL_5:b1wjonq) ([raw file](https://github.com/starkware-libs/sequencer/blob/5087e4b3bbe1dabdd2f618d5cb2b18e71c0a590c/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L175)):*
> ```XML
>             .await;
>         assert_eq!(res, Ok(None));
>         context.expect_broadcast().times(0);
> ```

Does putting an expectation like this after the call to `handle_proposal` add any value? I think this is covered above when we say that we made the expectation for sending 1 prevote.



_Code quote:_
```XML
        context.expect_broadcast().times(0);
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 261 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O339LG6AaRmXGJeX8LF:-O339LG6AaRmXGJeX8LG:b-8j2c96) ([raw file](https://github.com/starkware-libs/sequencer/blob/5087e4b3bbe1dabdd2f618d5cb2b18e71c0a590c/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L261)):*
> ```XML
> 
>     let first_vote = precommit(Some(*BLOCK_ID), 0, 0, *VALIDATOR_ID_2);
>     let decision = shc.handle_message(&mut context, first_vote.clone()).await.unwrap().unwrap();
> ```

The main logic of the test is happening after a decision is reached. A decision is the end, I don't really care how we behave after that. Please make sure to run the test logic before the decision (just do this for the first commit above).



_Code quote:_
```XML
    let decision = shc.handle_message(&mut context, first_vote.clone()).await.unwrap().unwrap();
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/187)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O3373fQ5PeuYrJfpl3P:-O36YHcbBpRRBXQ8Fwud:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5087e4b3bbe1dabdd2f618d5cb2b18e71c0a590c/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L137)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I don't really care how many times we check who the proposer is. The call to `validate_proposal` is the interesting one.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 144 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O337BAx1-073z1Go0iK:-O36YINM0uuH4nkQb-IC:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5087e4b3bbe1dabdd2f618d5cb2b18e71c0a590c/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L144)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Ok this test is great because it made me realize that we are not handling repeats properly. We should not call `validate_proposal` twice. We need to change the code in `handle_proposal` to check for conflict/repeat at the beginning (just after we validate the `init` message).

This also means my comment about using `entry` is irrelevant since we currently only insert once we have the BlockHash.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O338F9c66ou8dJIjAwU:-O36Z7IUDAJXzNs6d4hu:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5087e4b3bbe1dabdd2f618d5cb2b18e71c0a590c/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L155)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

make a variable `proposal_init` so that it's obvious we send the same one and readers don't need to compare fields.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O338RPY6v7HhipgBL_4:-O36YMZb6xE2_2eKXyLi:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5087e4b3bbe1dabdd2f618d5cb2b18e71c0a590c/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L175)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Does putting an expectation like this after the call to `handle_proposal` add any value? I think this is covered above when we say that we made the expectation for sending 1 prevote.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 261 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O339LG6AaRmXGJeX8LF:-O36_lin4dKbtta48Dqv:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5087e4b3bbe1dabdd2f618d5cb2b18e71c0a590c/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L261)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

The main logic of the test is happening after a decision is reached. A decision is the end, I don't really care how we behave after that. Please make sure to run the test logic before the decision (just do this for the first commit above).
</blockquote></details>

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/187)* status: all files reviewed, 3 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 249 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O36rwPb3Qvair3B0C9i:-O36rwPc53ZWseHXp0vU:b-xjrx4l) ([raw file](https://github.com/starkware-libs/sequencer/blob/1ee73ceefaa1f634944b99dbaa7df4b20d23f8d6/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L249)):*
> ```XML
> 
>     let res =
>         shc.handle_message(&mut context, prevote(Some(*BLOCK_ID), 0, 0, *VALIDATOR_ID_2)).await;
> ```

I think it's nice to not leave space between the expectation and the call which triggers it since they are directly connected to each other (one logical block in my mind). Please make this change throughout this test file.



_Suggestion:_
```XML
    context
    .expect_broadcast()
    .times(1) // Shows the repeat vote is ignored.
    .withf(move |msg: &ConsensusMessage| msg == &precommit(Some(*BLOCK_ID), 0, 0, *VALIDATOR_ID_1))
    .returning(move |_| Ok(()));
    let res =
        shc.handle_message(&mut context, prevote(Some(*BLOCK_ID), 0, 0, *VALIDATOR_ID_2)).await;
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 271 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O36rdF_4PgFdZFIK-Qh:-O36rdF_4PgFdZFIK-Qi:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1ee73ceefaa1f634944b99dbaa7df4b20d23f8d6/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L271)):*
> ```XML
>             _ => panic!("Expected Equivocation error"),
>         }
>     }
> ```





_Suggestion:_
```XML
    if same_vote {
        assert_eq!(res, Ok(None));
    } else {
        assert!(matches!(res, Err(ConsensusError::Equivocation(_, _, _))));
    }
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/187)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 249 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O36rwPb3Qvair3B0C9i:-O370rmQ8m47-B2k23Rl:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1ee73ceefaa1f634944b99dbaa7df4b20d23f8d6/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L249)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I think it's nice to not leave space between the expectation and the call which triggers it since they are directly connected to each other (one logical block in my mind). Please make this change throughout this test file.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 271 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O36rdF_4PgFdZFIK-Qh:-O37-i5_75ldkCzazZ9v:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1ee73ceefaa1f634944b99dbaa7df4b20d23f8d6/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L271)):*
> ```XML
>             _ => panic!("Expected Equivocation error"),
>         }
>     }
> ```

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/187)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 238 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/187#-O37HpMQ3KZpts7BZciQ:-O37HpMQ3KZpts7BZciR:bt2t7eg) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd86fe6493bd3627d51cb2ddc1713b67a5863cec/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L238)):*
> ```XML
>     assert_eq!(res, Ok(None));
>     let res = shc.handle_message(&mut context, prevote(Some(*BLOCK_ID), 0, 0, *PROPOSER_ID)).await;
>     assert_eq!(res, Ok(None));
> ```

These can remain separate. They are distinct messages being sent.



_Suggestion:_
```XML
    assert_eq!(res, Ok(None));

    let res = shc.handle_message(&mut context, prevote(Some(*BLOCK_ID), 0, 0, *PROPOSER_ID)).await;
    assert_eq!(res, Ok(None));
```

**Pull request merged**
