### PR TITLE
build: blockifier regression test add block info

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/946)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/946?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#946** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/946?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#945** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/945?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by aner-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/946)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/gateway/src/lib.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/946#-O7Ttl_g7QfxwcIzoRrU:-O7Ttl_g7QfxwcIzoRrV:bchgfxh) ([raw file](https://github.com/starkware-libs/sequencer/blob/5b3d719f4f0c15c2767efcdfabdeba1004ec7081/crates/gateway/src/lib.rs#L11)):*
> ```XML
> #[cfg(test)]
> mod rpc_state_reader_test;
> pub mod state_reader;
> ```

Blocking until approved by @dorimedini-starkware 



_Code quote:_
```XML
pub mod state_reader;
```

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/946)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/946#-O7Xz1Dk8N84hv32IGyH:-O7Xz1Dk8N84hv32IGyI:b-15co5) ([raw file](https://github.com/starkware-libs/sequencer/blob/5b3d719f4f0c15c2767efcdfabdeba1004ec7081/crates/blockifier_regression_test/src/test_state_reader.rs#L47)):*
> ```XML
>     pub fn get_block_info(&self) -> StateResult<BlockInfo> {
>         self.0.get_block_info()
>     }
> ```

consider adding `#[derive(derive_more::Deref)]` to `TestStateReader` - and you may be able to delete this getter. non-blocking



_Code quote:_
```XML
    pub fn get_block_info(&self) -> StateResult<BlockInfo> {
        self.0.get_block_info()
    }
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/946)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @dafnamatsry)

___
*[`crates/gateway/src/lib.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/946#-O7Ttl_g7QfxwcIzoRrU:-O7Z55YDDUdzAhHqk3v3:bd6tos6) ([raw file](https://github.com/starkware-libs/sequencer/blob/435efac4f19f41f1bcf7ab333440d7b93ca5d0f8/crates/gateway/src/lib.rs#L11)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this should be approved by someone from GW team
</blockquote></details>

this is required for the get_block_info functionality?
I think it's fine to make it public but maybe we should rearrange these files as a shared util.
@dafnamatsry wdyt?

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/946)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @dorimedini-starkware)

___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/946#-O7Xz1Dk8N84hv32IGyH:-O7YgcYM1q6TcBPwdv6o:b-8vp8so) ([raw file](https://github.com/starkware-libs/sequencer/blob/435efac4f19f41f1bcf7ab333440d7b93ca5d0f8/crates/blockifier_regression_test/src/test_state_reader.rs#L47)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

consider adding `#[derive(derive_more::Deref)]` to `TestStateReader` - and you may be able to delete this getter. non-blocking
</blockquote></details>

I believe that it might be misleading since I inherited some of the inner methods and changed some of them.
___
*[`crates/gateway/src/lib.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/946#-O7Ttl_g7QfxwcIzoRrU:-O7cDofo6iZT5RGlBA-u:bwb7xp5) ([raw file](https://github.com/starkware-libs/sequencer/blob/435efac4f19f41f1bcf7ab333440d7b93ca5d0f8/crates/gateway/src/lib.rs#L11)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

this is required for the get_block_info functionality?
I think it's fine to make it public but maybe we should rearrange these files as a shared util.
@dafnamatsry wdyt?
</blockquote></details>

Yes, I need to use the MempoolStateReader trait to get this functionality

**Review by aner-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/946)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/946)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
