### PR TITLE
feat(blockifier): add OS constants to VC

### PR DESCRIPTION
**Pull request by nimrod-starkware**

### CODE REVIEW

**Review by nimrod-starkware — COMMENTED** [review]
python side [PR](https://github.com/starkware-industries/starkware/pull/36302)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2281#-:-OCbgmQrCF12R5-iSLUx:b-o9b0w8)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2281)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 651 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2281#-OCc5gqN35DPY6mjLEzI:-OCc5gqN35DPY6mjLEzJ:bbzhpe0) ([raw file](https://github.com/starkware-libs/sequencer/blob/46909f20dbffec259ad50c2a0ec1e95dfc858862/crates/blockifier/src/versioned_constants.rs#L651)):*
> ```XML
> impl OsConstants {
>     // List of additinal os constants, beside the gas cost and validate rounding constants, that are
>     // not used by the blockifier but included for transparency. These constanst will be ignored
> ```

won't you be using these constants? we don't verify deployed addresses are not reserved?



_Code quote:_
```XML
not used by the blockifier
```
___
*[`crates/blockifier/resources/versioned_constants_0_13_4.json` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2281#-OCc5ZIEEV_kGjv1Lt3M:-OCc5ZIEEV_kGjv1Lt3N:b88srkx) ([raw file](https://github.com/starkware-libs/sequencer/blob/46909f20dbffec259ad50c2a0ec1e95dfc858862/crates/blockifier/resources/versioned_constants_0_13_4.json#L0)):*
don't these changes also need to appear on the older VCs...?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2281)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 651 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2281#-OCc5gqN35DPY6mjLEzI:-OCcV_hO5gDFecD3ezTH:b-oedg2a) ([raw file](https://github.com/starkware-libs/sequencer/blob/46909f20dbffec259ad50c2a0ec1e95dfc858862/crates/blockifier/src/versioned_constants.rs#L651)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

won't you be using these constants? we don't verify deployed addresses are not reserved?
</blockquote></details>

No need to check it in the blockifier

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2281)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware)

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2281)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/resources/versioned_constants_0_13_4.json` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2281#-OCc5ZIEEV_kGjv1Lt3M:-OChC9DgBYu2-UPkr7-P:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/46909f20dbffec259ad50c2a0ec1e95dfc858862/crates/blockifier/resources/versioned_constants_0_13_4.json#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't these changes also need to appear on the older VCs...?
</blockquote></details>

Done
___
*[`crates/blockifier/src/versioned_constants.rs` line 713 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2281#-OCckcMe-r4iqUNt85F0:-OChGRMp6M4-wK1csjfe:bpjfdfe) ([raw file](https://github.com/starkware-libs/sequencer/blob/1583dfb74be10b589fe439df8015ca6472520a43/crates/blockifier/src/versioned_constants.rs#L713)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

change types from u8 to ContractAddress, as these are contract addresses... if you want to enforce these are less than 256 via typing, define `struct OsContractAddress(u8)` and `impl From<OsContractAddress> for ContractAddress`, but that seems overkill to me
</blockquote></details>

I did another trick, changing to 
```
pub struct OsContractAddresses {
    block_hash_contract_address: ContractAddress,
    alias_contract_address: ContractAddress,
    reserved_contract_address: ContractAddress,
}
```
Doesn't work because of how `ContractAddress` deserializes.

I changed the fields to be private and added methods return it as a `ContractAddress`
___
*[`crates/blockifier/src/versioned_constants.rs` line 719 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2281#-OCcl3_F36MgcXBSkUHX:-OChDBVS4DUxEblKDEQS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1583dfb74be10b589fe439df8015ca6472520a43/crates/blockifier/src/versioned_constants.rs#L719)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't like how these magic numbers appear here and in the VC jsons; how about like this?
(`latest_constants` returns a `&'static VersionedConstants` so there should very small overhead to loading the entire object)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 709 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2281#-OCckahU7KRfRVDs6y04:-OChCD8k1hf6owBxwxkI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1583dfb74be10b589fe439df8015ca6472520a43/crates/blockifier/src/versioned_constants.rs#L709)):*
> ```XML
>     }
> }
> #[derive(Debug, Deserialize)]
> ```

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2281)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 713 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2281#-OCckcMe-r4iqUNt85F0:-OChmSNG7kZVmVDyTbKU:b-x30gjj) ([raw file](https://github.com/starkware-libs/sequencer/blob/1583dfb74be10b589fe439df8015ca6472520a43/crates/blockifier/src/versioned_constants.rs#L713)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I did another trick, changing to 
```
pub struct OsContractAddresses {
    block_hash_contract_address: ContractAddress,
    alias_contract_address: ContractAddress,
    reserved_contract_address: ContractAddress,
}
```
Doesn't work because of how `ContractAddress` deserializes.

I changed the fields to be private and added methods return it as a `ContractAddress`
</blockquote></details>

did you try `#[serde(deserialize_with = "???")]`? it may be a cleaner solution

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2281)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 713 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2281#-OCckcMe-r4iqUNt85F0:-OCiEp7V2f2nS0c8KQEY:b-ex83g) ([raw file](https://github.com/starkware-libs/sequencer/blob/1583dfb74be10b589fe439df8015ca6472520a43/crates/blockifier/src/versioned_constants.rs#L713)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

did you try `#[serde(deserialize_with = "???")]`? it may be a cleaner solution
</blockquote></details>

It's possible with an intermediate struct that deserializes easily.
However, implementing a `Default` for that becomes more difficult if we want to use `VersionedConstants::latest()` as the fields there of `ContractAddress` type.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2281)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2281)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2281#-OCm-soq-weSeyDIkPNw:-OCm-soq-weSeyDIkPNx:b2j4aux) (no related file):*
waiting for py side PR to pass

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2281)* status: 3 of 15 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2281#-OCm-soq-weSeyDIkPNw:-OCmOKPH2MKGb3scIwdv:b-m6tfm3) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

waiting for py side PR to pass
</blockquote></details>

passed

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 10 of 12 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2281)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2281)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2281)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2281)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 792 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2281#-OD1YjnpAyP52_atU9Hz:-OD1YjnpAyP52_atU9I-:b-oel2p1) ([raw file](https://github.com/starkware-libs/sequencer/blob/bbc0656b9bc024eeffa0dc00c58309d5f9714edd/crates/blockifier/src/versioned_constants.rs#L792)):*
> ```XML
>     #[serde(default)]
>     validate_rounding_consts: ValidateRoundingConsts,
>     #[serde(default)]
> ```

Why default?



_Code quote:_
```XML
#[serde(default)]
```

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2281)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Pull request merged**
