### PR TITLE
refactor(blockifier): split feature contracts to groups based on their…

### PR DESCRIPTION
**Pull request by meship-starkware**
… tags

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2236)* status: all files reviewed, 7 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2236#-OCcgA7y-ssm8-8KPPVX:-OCcgA7y-ssm8-8KPPVY:b62pvdm) ([raw file](https://github.com/starkware-libs/sequencer/blob/3acb443f29e6fb283f189b3824371bce613fe22f/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L46)):*
> ```XML
>             prepare_group_tag_compiler_deps(tag_override.clone());
>         }
>         for contract in feature_contracts
> ```

this loop will be parallelized?



_Code quote:_
```XML
for contract in feature_contracts
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 327 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2236#-OCcezbX3hQMmZxP1-n6:-OCcezbX3hQMmZxP1-n7:b-9zrsk1) ([raw file](https://github.com/starkware-libs/sequencer/blob/3acb443f29e6fb283f189b3824371bce613fe22f/crates/blockifier/src/test_utils/contracts.rs#L327)):*
> ```XML
>         &self,
>         tag_override: Option<String>,
>         cargo_nightly_arg: Option<String>,
> ```

this pair appears often in this PR; please create a `TagAndToolchain` struct containing these, and use it
1. in function signatures,
2. as function return values (where relevant),
2. as the key type on your `TagToContractsMapping` type



_Code quote:_
```XML
        tag_override: Option<String>,
        cargo_nightly_arg: Option<String>,
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 328 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2236#-OCceF-gBiFjneiaXX3c:-OCceF-gBiFjneiaXX3d:b-y65usg) ([raw file](https://github.com/starkware-libs/sequencer/blob/3acb443f29e6fb283f189b3824371bce613fe22f/crates/blockifier/src/test_utils/contracts.rs#L328)):*
> ```XML
>         tag_override: Option<String>,
>         cargo_nightly_arg: Option<String>,
>     ) -> Vec<u8> {
> ```

why do you inject this input now?
tag + nightly arg is still a property of the enum variant; you can still use the `fixed_tag_and_rust_toolchain` to get it.
you can also use `fixed_tag_and_rust_toolchain` in the implementation of `feature_contracts_by_tag`



_Code quote:_
```XML
    pub fn compile(
        &self,
        tag_override: Option<String>,
        cargo_nightly_arg: Option<String>,
    ) -> Vec<u8> {
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 425 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2236#-OCcedJyA0rXSUnnC6mO:-OCcedJyA0rXSUnnC6mP:bngw4yn) ([raw file](https://github.com/starkware-libs/sequencer/blob/3acb443f29e6fb283f189b3824371bce613fe22f/crates/blockifier/src/test_utils/contracts.rs#L425)):*
> ```XML
>             }
>             let tag_and_version = contract.fixed_tag_and_rust_toolchain();
>             let contracts_to_insert = if contract.has_two_versions() {
> ```

what does this function mean, now that there are 3 possible versions (with native)?
this function should indicate cairo1 vs cairo0, and your parallelization feature is for cairo1 only



_Code quote:_
```XML
 if contract.has_two_versions()
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 427 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2236#-OCcfO-FDtvE69QNziu4:-OCcfO-FDtvE69QNziu5:bcqsl7d) ([raw file](https://github.com/starkware-libs/sequencer/blob/3acb443f29e6fb283f189b3824371bce613fe22f/crates/blockifier/src/test_utils/contracts.rs#L427)):*
> ```XML
>             let contracts_to_insert = if contract.has_two_versions() {
>                 let mut other_contract = contract;
>                 other_contract.set_cairo_version(contract.cairo_version().other());
> ```

how is this defined...?



_Code quote:_
```XML
cairo_version().other()
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 435 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2236#-OCceqHT8rBnW_g9qjCK:-OCceqHU6OMk_7vQwQKr:bw5homf) ([raw file](https://github.com/starkware-libs/sequencer/blob/3acb443f29e6fb283f189b3824371bce613fe22f/crates/blockifier/src/test_utils/contracts.rs#L435)):*
> ```XML
>                 .entry(tag_and_version)
>                 .or_insert_with(Vec::new)
>                 .extend(contracts_to_insert);
> ```

why add cairo0 contracts to this list...?



_Code quote:_
```XML
.extend(contracts_to_insert);
```
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2236#-OCcdim4DXaTIHDN4uOJ:-OCcdim4DXaTIHDN4uOK:b-eonud1) ([raw file](https://github.com/starkware-libs/sequencer/blob/3acb443f29e6fb283f189b3824371bce613fe22f/crates/blockifier/src/test_utils/cairo_compile.rs#L232)):*
> ```XML
> }
> 
> fn prepare_cairo1_compiler_deps(git_tag_override: Option<String>) {
> ```

this function makes no changes to the state of the machine it's running on, so I would rename



_Suggestion:_
```XML
fn verify_cairo1_compiler_deps
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2236)* status: all files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 425 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2236#-OCcedJyA0rXSUnnC6mO:-OCcx1ms9mBCvCCeH5N2:b-twxy1r) ([raw file](https://github.com/starkware-libs/sequencer/blob/3acb443f29e6fb283f189b3824371bce613fe22f/crates/blockifier/src/test_utils/contracts.rs#L425)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what does this function mean, now that there are 3 possible versions (with native)?
this function should indicate cairo1 vs cairo0, and your parallelization feature is for cairo1 only
</blockquote></details>

I thought about having two Types: one Cairo version and the second completion type (the names are not set). I also thought about addressing it in a different PR, where I will remove the Cairo Native folder. 
https://reviewable.io/reviews/starkware-libs/sequencer/1301#-O93wpyO6HNmUICVLokU  
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2236#-OCcgA7y-ssm8-8KPPVX:-OCcv7ylDi7beRJdLQHA:b-ds2bca) ([raw file](https://github.com/starkware-libs/sequencer/blob/3acb443f29e6fb283f189b3824371bce613fe22f/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L46)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this loop will be parallelized?
</blockquote></details>

That is the intention. For now, our priority is to save the Sierra files and remove the native folder, so I don't know when it will happen.      
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 416 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2236#-OCcVW6a3UT5qbORAcfm:-OCcVW6bEsvmaq2WW6h7:b-ymciz0) ([raw file](https://github.com/starkware-libs/sequencer/blob/3acb443f29e6fb283f189b3824371bce613fe22f/crates/blockifier/src/test_utils/contracts.rs#L416)):*
> ```XML
>     }
> 
>     pub fn feature_contracts_by_tag() -> TagToContractsMapping {
> ```

I decided to create a new function because all_contracts returns an iterator of all the contracts, and then all feature contracts filter the erc_20 contract, so I didn't know if I could remove the ERC20 in all contracts. Also, there is another use that needs the iterator form 



_Code quote:_
```XML
 fn feature_contracts_by_tag() -> TagToContractsMapping {
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2236)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2236#-OCcdim4DXaTIHDN4uOJ:-OCnh9Jb8GuraoFkmbh6:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3acb443f29e6fb283f189b3824371bce613fe22f/crates/blockifier/src/test_utils/cairo_compile.rs#L232)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this function makes no changes to the state of the machine it's running on, so I would rename
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 327 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2236#-OCcezbX3hQMmZxP1-n6:-OCnhACID8ss1o6tTvcZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3acb443f29e6fb283f189b3824371bce613fe22f/crates/blockifier/src/test_utils/contracts.rs#L327)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this pair appears often in this PR; please create a `TagAndToolchain` struct containing these, and use it
1. in function signatures,
2. as function return values (where relevant),
2. as the key type on your `TagToContractsMapping` type
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 328 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2236#-OCceF-gBiFjneiaXX3c:-OCniXy33cqfEMDrbp3E:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3acb443f29e6fb283f189b3824371bce613fe22f/crates/blockifier/src/test_utils/contracts.rs#L328)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do you inject this input now?
tag + nightly arg is still a property of the enum variant; you can still use the `fixed_tag_and_rust_toolchain` to get it.
you can also use `fixed_tag_and_rust_toolchain` in the implementation of `feature_contracts_by_tag`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 435 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2236#-OCceqHT8rBnW_g9qjCK:-OCcwIrT5UA_QGsd16rT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3acb443f29e6fb283f189b3824371bce613fe22f/crates/blockifier/src/test_utils/contracts.rs#L435)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why add cairo0 contracts to this list...?
</blockquote></details>

Done.
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2236#-OCnicGN8ZJLZ4pMLuzA:-OCnicGN8ZJLZ4pMLuzB:b-6c7rdb) ([raw file](https://github.com/starkware-libs/sequencer/blob/db4eebe932202561bc4396c860753ce0eda000c8/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L48)):*
> ```XML
>             }
>         }
>         _ => {
> ```

I don't like the implicit check here, but doing it explicitly will force me to duplicate the cairo1 behavior because we have the feature flag. It won't be necessary with Doris' changes, so maybe I can keep it and add a TODO. WDYT?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2236)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2236#-OCnicGN8ZJLZ4pMLuzA:-ODBSnpf8MLnNH1KOQ6_:b-2fesb6) ([raw file](https://github.com/starkware-libs/sequencer/blob/db4eebe932202561bc4396c860753ce0eda000c8/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L48)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I don't like the implicit check here, but doing it explicitly will force me to duplicate the cairo1 behavior because we have the feature flag. It won't be necessary with Doris' changes, so maybe I can keep it and add a TODO. WDYT?
</blockquote></details>

keep it and add a TODO sgtm :)
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 439 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2236#-ODBSZOPDppclTB29zJn:-ODBSZOPDppclTB29zJo:bp1z2fi) ([raw file](https://github.com/starkware-libs/sequencer/blob/51c098658e0c276d8a23e053315e36c9c5a2feee/crates/blockifier/src/test_utils/contracts.rs#L439)):*
> ```XML
>     pub fn cairo1_feature_contracts_by_tag() -> TagToContractsMapping {
>         // EnumIter iterates over all variants with Default::default() as the cairo
>         // version.
> ```

delete, not relevant here (you are not using `Self::iter()`)



_Code quote:_
```XML
        // EnumIter iterates over all variants with Default::default() as the cairo
        // version.
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2236)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 439 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2236#-ODBSZOPDppclTB29zJn:-ODFdGU25PqqBTyv54jh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/51c098658e0c276d8a23e053315e36c9c5a2feee/crates/blockifier/src/test_utils/contracts.rs#L439)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete, not relevant here (you are not using `Self::iter()`)
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2236#-:-ODGCEES9qEfq-XOgFIL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
