### PR TITLE
chore(starknet_sequencer_node): avoid redundant client cloning for re…

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
…mote servers

commit-id:d24507fa

---

**Stack**:
- #2743
- #2742 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/starknet_sequencer_node/src/utils.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2742#-OENq5AY6XLoEbYdhlI3:-OENq5AY6XLoEbYdhlI4:b-t8ii3q) ([raw file](https://github.com/starkware-libs/sequencer/blob/3cc6040d079c5ee95a257304e57fe64ad0f9621e/crates/starknet_sequencer_node/src/utils.rs#L15)):*
> ```XML
>     let servers = create_node_servers(config, &mut channels, components, &clients);
> 
>     (clients, servers)
> ```

I like the convention of a new line before the "return statement"



_Code quote:_
```XML
    let servers = create_node_servers(config, &mut channels, components, &clients);

    (clients, servers)
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2742)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2742)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_sequencer_node/src/utils.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2742#-OENq5AY6XLoEbYdhlI3:-OENz0k3-sYDTECv8v2T:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3cc6040d079c5ee95a257304e57fe64ad0f9621e/crates/starknet_sequencer_node/src/utils.rs#L15)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I like the convention of a new line before the "return statement"
</blockquote></details>

Done.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2742#-:-OENz4fmB8TCIODHhYtU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
