### PR TITLE
refactor(network): extract bodies of match arms in network manager

### PR DESCRIPTION
**Pull request by eitanm-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/450)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/450)* status: all files reviewed, 4 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/discovery/mod.rs` line 265 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/450#-O4uJu67AKRvpXlOGaX9:-O4uJu67AKRvpXlOGaXA:b4diemi) ([raw file](https://github.com/starkware-libs/sequencer/blob/90acc598ca395b8571343dd33f3ebee8434c8b0b/crates/papyrus_network/src/discovery/mod.rs#L265)):*
> ```XML
> impl BridgedBehaviour for Behaviour {
>     fn on_other_behaviour_event(&mut self, event: &mixed_behaviour::ToOtherBehaviourEvent) {
>         if let mixed_behaviour::ToOtherBehaviourEvent::Kad(
> ```

Even better, use let ... else { return; };
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 303 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/450#-O4uK5BL6cWr-f1soNXY:-O4uK5BL6cWr-f1soNXZ:b-7dkv19) ([raw file](https://github.com/starkware-libs/sequencer/blob/d05696489bdfb87759254cabb04176b82035ea9f/crates/papyrus_network/src/network_manager/mod.rs#L303)):*
> ```XML
> 
>     fn handle_to_other_behaviour_event(&mut self, event: mixed_behaviour::ToOtherBehaviourEvent) {
>         // TODO(shahak): Move this logic to mixed_behaviour.
> ```

Why did you erase these 2?
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 314 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/450#-O4uKFhUBqbczWbZI6CN:-O4uKFhUBqbczWbZI6CO:b35sdoe) ([raw file](https://github.com/starkware-libs/sequencer/blob/90acc598ca395b8571343dd33f3ebee8434c8b0b/crates/papyrus_network/src/network_manager/mod.rs#L314)):*
> ```XML
>     }
> 
>     fn handle_sqmr_behaviour_event(&mut self, event: sqmr::behaviour::ExternalEvent) {
> ```

sqmr_behaviour_event => sqmr_event
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/450#-O4uKAdB5wDbLynICk6Z:-O4uKAdB5wDbLynICk6_:bck79az) ([raw file](https://github.com/starkware-libs/sequencer/blob/90acc598ca395b8571343dd33f3ebee8434c8b0b/crates/papyrus_network/src/network_manager/mod.rs#L321)):*
> ```XML
>                 peer_id,
>                 protocol_name,
>             } => self.handle_sqmr_behaviour_new_inbound_session(
> ```

behaviour => event. same for the rest of the methods

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/450)* status: all files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 303 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/450#-O4uK5BL6cWr-f1soNXY:-O57HcpZ0MfejU6r4Kww:byq1l5b) ([raw file](https://github.com/starkware-libs/sequencer/blob/d05696489bdfb87759254cabb04176b82035ea9f/crates/papyrus_network/src/network_manager/mod.rs#L303)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why did you erase these 2?
</blockquote></details>

discussed & returned
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 314 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/450#-O4uKFhUBqbczWbZI6CN:-O57JOh98DOFq9mOQ5oa:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/90acc598ca395b8571343dd33f3ebee8434c8b0b/crates/papyrus_network/src/network_manager/mod.rs#L314)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

sqmr_behaviour_event => sqmr_event
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/450#-O4uKAdB5wDbLynICk6Z:-O57JP-71xMDP_GmKzHf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/90acc598ca395b8571343dd33f3ebee8434c8b0b/crates/papyrus_network/src/network_manager/mod.rs#L321)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

behaviour => event. same for the rest of the methods
</blockquote></details>

Done.

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/450)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/discovery/mod.rs` line 265 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/450#-O4uJu67AKRvpXlOGaX9:-O57Lu7yBR1BgrIA672x:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/90acc598ca395b8571343dd33f3ebee8434c8b0b/crates/papyrus_network/src/discovery/mod.rs#L265)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Even better, use let ... else { return; };
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/450)* status: all files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 303 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/450#-O4uK5BL6cWr-f1soNXY:-O57Najr-fy6CVXjRGrl:bl570wv) ([raw file](https://github.com/starkware-libs/sequencer/blob/d05696489bdfb87759254cabb04176b82035ea9f/crates/papyrus_network/src/network_manager/mod.rs#L303)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

discussed & returned
</blockquote></details>

What about the TODO

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/450#-:-O584-rtAhscAchndxMm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Pull request merged**
