### PR TITLE
chore(sequencing): remove ConsensusMessage from context

### PR DESCRIPTION
**Pull request by guy-starkware**
This is the big one. 
I removed the ConsensusMessage from context and single height consensus and a bunch of other places, that were all related to each other. 
I don't think there's a way to chop it up into smaller pieces...

### CODE REVIEW

**Comment by guy-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2533?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2533** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2533?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2533?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2532** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2532?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2528** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2528?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2526** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2526?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2525** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2525?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2524** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2524?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2518** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2518?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2517** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2517?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2512** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2512?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2510** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2510?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by asmaastarkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2533)* status: all files reviewed, 3 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 275 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2533#-OEiTQG_6F7qJVAmWGSN:-OEiTQGa5ZUa6kXpdikW:b-wwnvei) ([raw file](https://github.com/starkware-libs/sequencer/blob/cde4b8d749c4b2664b5e9703e3073651e0bf705b/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L275)):*
> ```XML
>         debug!("Received message: {:?}", message);
> 
>         let ret = self.handle_vote(context, message).await;
> ```

let's remove handle_message fn, and make handle_vote pub (now since it's pub at the end please call `context.set_height_and_round(self.height, self.state_machine.round()).await;` and then return ret
___
*[`crates/papyrus_node/src/bin/run_consensus.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2533#-OEiS4MR2eS23Si1WnpX:-OEiS4MS7nFtFj1c4j7l:b-prnrva) ([raw file](https://github.com/starkware-libs/sequencer/blob/cde4b8d749c4b2664b5e9703e3073651e0bf705b/crates/papyrus_node/src/bin/run_consensus.rs#L94)):*
> ```XML
>         test_config.invalid_probability,
>     );
>     let broadcast_channels = BroadcastVoteChannel {
> ```

change to `broadcast_vote_channels` throughout



_Suggestion:_
```XML
broadcast_vote_channels
```
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2533#-OEiUv1K61YlHYPyFGnG:-OEiUv1K61YlHYPyFGnH:b-twxfa) ([raw file](https://github.com/starkware-libs/sequencer/blob/cde4b8d749c4b2664b5e9703e3073651e0bf705b/crates/sequencing/papyrus_consensus/src/manager.rs#L127)):*
> ```XML
> struct MultiHeightManager<ContextT: ConsensusContext> {
>     validator_id: ValidatorId,
>     cached_messages: BTreeMap<u64, Vec<Vote>>,
> ```

I still think vote would be clearer and more informative than msg for readability WDYT + @matan-starkware WDYT?
cached_vote_messages / cached_votes



_Suggestion:_
```XML
cached_vote_messages: BTreeMap<u64, Vec<Vote>>,
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2533)* status: 8 of 12 files reviewed, 3 unresolved discussions (waiting on @asmaastarkware and @matan-starkware)

___
*[`crates/papyrus_node/src/bin/run_consensus.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2533#-OEiS4MR2eS23Si1WnpX:-OEic7vi3_NhfIhkeZlz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cde4b8d749c4b2664b5e9703e3073651e0bf705b/crates/papyrus_node/src/bin/run_consensus.rs#L94)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

change to `broadcast_vote_channels` throughout
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2533#-OEiUv1K61YlHYPyFGnG:-OEicMJU86FBD75F4zkF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cde4b8d749c4b2664b5e9703e3073651e0bf705b/crates/sequencing/papyrus_consensus/src/manager.rs#L127)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

I still think vote would be clearer and more informative than msg for readability WDYT + @matan-starkware WDYT?
cached_vote_messages / cached_votes
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 275 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2533#-OEiTQG_6F7qJVAmWGSN:-OEigbMi3wdD1g4juPSh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cde4b8d749c4b2664b5e9703e3073651e0bf705b/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L275)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

let's remove handle_message fn, and make handle_vote pub (now since it's pub at the end please call `context.set_height_and_round(self.height, self.state_machine.round()).await;` and then return ret
</blockquote></details>

Done.

**Review by asmaastarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2533)* status: all files reviewed, 5 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 360 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2533#-OEijoXl06TH5OG6bauZ:-OEijoXl06TH5OG6bau_:bowign8) ([raw file](https://github.com/starkware-libs/sequencer/blob/dad001eca09fdbca1346a28b2db316d42ea83c6c/crates/sequencing/papyrus_consensus/src/manager.rs#L360)):*
> ```XML
>     // - drops messages from earlier heights.
>     // - retains future messages in the cache.
>     fn get_current_height_messages(&mut self, height: BlockNumber) -> Vec<Vote> {
> ```

we may create separate refactor PR after merging these PRs



_Suggestion:_
```XML
get_current_height_vote_messages
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 266 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2533#-OEikFoP62iN0t0WkxUP:-OEikFoP62iN0t0WkxUQ:brdne8e) ([raw file](https://github.com/starkware-libs/sequencer/blob/dad001eca09fdbca1346a28b2db316d42ea83c6c/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L266)):*
> ```XML
>     }
> 
>     /// Handle messages from peer nodes.
> ```

delete comment lines
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 280 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2533#-OEik0033ysDDBbrVtjZ:-OEik0033ysDDBbrVtj_:b-qyjabt) ([raw file](https://github.com/starkware-libs/sequencer/blob/dad001eca09fdbca1346a28b2db316d42ea83c6c/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L280)):*
> ```XML
>     // }
> 
>     /// Handle vote messages from peer nodes.
> ```

above handle_vote not handle_event
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 373 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2533#-OEikt_SErfgKTn90Amw:-OEikt_SErfgKTn90Amx:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/dad001eca09fdbca1346a28b2db316d42ea83c6c/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L373)):*
> ```XML
> 
>     #[instrument(skip_all)]
>     pub async fn handle_vote<ContextT: ConsensusContext>(
> ```





_Suggestion:_
```XML
    /// Handle vote messages from peer nodes.
    #[instrument(skip_all)]
    pub(crate) async fn handle_vote<ContextT: ConsensusContext>(
```

**Review by asmaastarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2533)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r2, 4 of 5 files at r3, 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2533)* status: all files reviewed, 2 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2533#-OEiUv1K61YlHYPyFGnG:-OEn0pMT7Q8jdAW75tCQ:b-tfgm4g) ([raw file](https://github.com/starkware-libs/sequencer/blob/cde4b8d749c4b2664b5e9703e3073651e0bf705b/crates/sequencing/papyrus_consensus/src/manager.rs#L127)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I like "future_votes"
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 298 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2533#-OEn1EXZ63O_JV-kcMJf:-OEn1EXZ63O_JV-kcMJg:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1018d1ef3bd695f5d57685e08fa71f0d8086b565/crates/sequencing/papyrus_consensus/src/manager.rs#L298)):*
> ```XML
>         message: Option<(Result<Vote, ProtobufConversionError>, BroadcastedMessageMetadata)>,
>         broadcast_channels: &mut BroadcastVoteChannel,
>     ) -> Result<ShcReturn, ConsensusError> {
> ```





_Suggestion:_
```XML
    async fn handle_vote(
        &mut self,
        context: &mut ContextT,
        height: BlockNumber,
        shc: &mut SingleHeightConsensus,
        vote: Option<(Result<Vote, ProtobufConversionError>, BroadcastedMessageMetadata)>,
        broadcast_channels: &mut BroadcastVoteChannel,
    ) -> Result<ShcReturn, ConsensusError> {
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2533)* status: all files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2533#-OEiUv1K61YlHYPyFGnG:-OErkWsf2F2iB2u7em91:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cde4b8d749c4b2664b5e9703e3073651e0bf705b/crates/sequencing/papyrus_consensus/src/manager.rs#L127)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I like "future_votes"
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 360 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2533#-OEijoXl06TH5OG6bauZ:-OEivDWxBBiodYMhrCtG:bc54id8) ([raw file](https://github.com/starkware-libs/sequencer/blob/dad001eca09fdbca1346a28b2db316d42ea83c6c/crates/sequencing/papyrus_consensus/src/manager.rs#L360)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

we may create separate refactor PR after merging these PRs
</blockquote></details>

yes, a separate PR sounds like a good plan. 
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 266 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2533#-OEikFoP62iN0t0WkxUP:-OEivccWDEEVhQKwjSz_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dad001eca09fdbca1346a28b2db316d42ea83c6c/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L266)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

delete comment lines
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 280 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2533#-OEik0033ysDDBbrVtjZ:-OEivpCF3qKCQIKvwH-m:b-7lj87b) ([raw file](https://github.com/starkware-libs/sequencer/blob/dad001eca09fdbca1346a28b2db316d42ea83c6c/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L280)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

above handle_vote not handle_event
</blockquote></details>

oops!
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 373 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2533#-OEikt_SErfgKTn90Amw:-OEivupY78C0lXEQI7Fo:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dad001eca09fdbca1346a28b2db316d42ea83c6c/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L373)):*
> ```XML
> 
>     #[instrument(skip_all)]
>     pub async fn handle_vote<ContextT: ConsensusContext>(
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 298 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2533#-OEn1EXZ63O_JV-kcMJf:-OErkmhB1w9WUp3cnf_3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1018d1ef3bd695f5d57685e08fa71f0d8086b565/crates/sequencing/papyrus_consensus/src/manager.rs#L298)):*
> ```XML
>         message: Option<(Result<Vote, ProtobufConversionError>, BroadcastedMessageMetadata)>,
>         broadcast_channels: &mut BroadcastVoteChannel,
>     ) -> Result<ShcReturn, ConsensusError> {
> ```

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2533)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Pull request merged**
