### PR TITLE
refactor(execution): put all create for testing methods under testing…

### PR DESCRIPTION
**Pull request by meship-starkware**
… config

refactor(execution): put all create for testing methods under testing config

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/164)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/164)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/164#-O2ymOlg6qJm9AKutS44:-O2ymOlg6qJm9AKutS45:b82qob4) (no related file):*
@tdelabro 

___

**Review by tdelabro — APPROVED** [review]

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/164)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 514 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/164#-O31f9M95RyVTV4ctvsD:-O31f9MA4MUPdra14Sl_:b-8iydic) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f47bedab4599f5797f7fd40a04da4e361a90098/crates/blockifier/src/transaction/transactions.rs#L514)):*
> ```XML
> 
>     #[cfg(any(test, feature = "testing"))]
>     pub fn create_for_testing(l1_fee: Fee, contract_address: ContractAddress) -> Self {
> ```

Please move it to struct_impl



_Code quote:_
```XML
    #[cfg(any(test, feature = "testing"))]
    pub fn create_for_testing(l1_fee: Fee, contract_address: ContractAddress) -> Self {
```
___
*[`crates/gateway/src/config.rs` line 212 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/164#-O31fmAz4Nr47DLpw9vf:-O31fmAz4Nr47DLpw9vg:brejra4) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f47bedab4599f5797f7fd40a04da4e361a90098/crates/gateway/src/config.rs#L212)):*
> ```XML
> #[cfg(any(test, feature = "testing"))]
> impl ChainInfoConfig {
>     pub fn create_for_testing() -> Self {
> ```

Same below



_Suggestion:_
```XML
impl ChainInfoConfig {
    #[cfg(any(test, feature = "testing"))]
    pub fn create_for_testing() -> Self {
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/164)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 514 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/164#-O31f9M95RyVTV4ctvsD:-O32Txb50dvXLY27c0Kb:bax4tq2) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f47bedab4599f5797f7fd40a04da4e361a90098/crates/blockifier/src/transaction/transactions.rs#L514)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please move it to struct_impl
</blockquote></details>

Do we want all `impl L1HandlerTransaction` to only appear in tests binary?
___
*[`crates/gateway/src/config.rs` line 212 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/164#-O31fmAz4Nr47DLpw9vf:-O32UvotERiqMLoUpSNI:bfin1mr) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f47bedab4599f5797f7fd40a04da4e361a90098/crates/gateway/src/config.rs#L212)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Same below
</blockquote></details>

Do you want me to mark the configuration only for the function?

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/164)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 514 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/164#-O31f9M95RyVTV4ctvsD:-O32VjFd3vbHGWLYEPzh:b-usdtm9) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f47bedab4599f5797f7fd40a04da4e361a90098/crates/blockifier/src/transaction/transactions.rs#L514)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Do we want all `impl L1HandlerTransaction` to only appear in tests binary?
</blockquote></details>

No, only the `create_for_testing` method

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/164)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/gateway/src/config.rs` line 212 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/164#-O31fmAz4Nr47DLpw9vf:-O32bD4t9ceuCF-iU4RQ:b46xz5f) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f47bedab4599f5797f7fd40a04da4e361a90098/crates/gateway/src/config.rs#L212)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Do you want me to mark the configuration only for the function?
</blockquote></details>

I can't do this because it is a part of the gateway crate and not the blockifier.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/164)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 514 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/164#-O31f9M95RyVTV4ctvsD:-O32eJ1P2yjaVHp-SF1c:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f47bedab4599f5797f7fd40a04da4e361a90098/crates/blockifier/src/transaction/transactions.rs#L514)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

No, only the `create_for_testing` method
</blockquote></details>

Done.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/164)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/gateway/src/config.rs` line 212 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/164#-O31fmAz4Nr47DLpw9vf:-O32sJbE4fbtY65hK1RT:bjmuulj) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f47bedab4599f5797f7fd40a04da4e361a90098/crates/gateway/src/config.rs#L212)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please elaborate?
</blockquote></details>

Nevermind I did not understand the remark
Done.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/164)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/gateway/src/config.rs` line 210 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/164#-O32xv5EEup42Bq9n9KC:-O32xv5EEup42Bq9n9KD:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d43db280f55e753661350ec70d858f8e3136cc1/crates/gateway/src/config.rs#L210)):*
> ```XML
>     }
> }
> impl ChainInfoConfig {
> ```





_Suggestion:_
```XML
}

impl ChainInfoConfig {
```
___
*[`crates/gateway/src/config.rs` line 290 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/164#-O32xqSbDAZyLlyyB-fi:-O32xqSbDAZyLlyyB-fj:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d43db280f55e753661350ec70d858f8e3136cc1/crates/gateway/src/config.rs#L290)):*
> ```XML
> #[cfg(any(test, feature = "testing"))]
> impl StatefulTransactionValidatorConfig {
>     pub fn create_for_testing() -> Self {
> ```





_Suggestion:_
```XML
impl StatefulTransactionValidatorConfig {
    #[cfg(any(test, feature = "testing"))]
    pub fn create_for_testing() -> Self {
```

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/164#-:-O3338D41iYxkdK--MCA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Pull request merged**
