### PR TITLE
chore(execution): add l2_gas_price to PendingData

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/643)

### CODE REVIEW

**Comment by TzahiTaub** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/643?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#644** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/644?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#643** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/643?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#641** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/641?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @TzahiTaub and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/643)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama and @TzahiTaub)

___
*[`crates/starknet_client/src/reader/objects/pending_data.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/643#-O5hmw6kD7hePENgOV0b:-O5hmw6kD7hePENgOV0c:b-vyc6q4) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8186d0f428ad17d658de11f418d4cbc6e9545e9/crates/starknet_client/src/reader/objects/pending_data.rs#L168)):*
> ```XML
>             PendingBlockOrDeprecated::Current(block) => block.l2_gas_price,
>         }
>     }
> ```

is 0.13.2 an "older version"?
don't we need another enum variant to support the version which has data gas price but doesn't have l2 gas price?



_Code quote:_
```XML
    pub fn l1_data_gas_price(&self) -> GasPricePerToken {
        match self {
            // In older versions, data gas price was 0.
            PendingBlockOrDeprecated::Deprecated(_) => GasPricePerToken::default(),
            PendingBlockOrDeprecated::Current(block) => block.l1_data_gas_price,
        }
    }
    pub fn l2_gas_price(&self) -> GasPricePerToken {
        match self {
            // In older versions, L2 gas price was 0.
            PendingBlockOrDeprecated::Deprecated(_) => GasPricePerToken::default(),
            PendingBlockOrDeprecated::Current(block) => block.l2_gas_price,
        }
    }
```

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/643)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/starknet_client/src/reader/objects/pending_data.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/643#-O5hmw6kD7hePENgOV0b:-O5rxeLY-05eYFHYrulF:b-e86aje) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8186d0f428ad17d658de11f418d4cbc6e9545e9/crates/starknet_client/src/reader/objects/pending_data.rs#L168)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is 0.13.2 an "older version"?
don't we need another enum variant to support the version which has data gas price but doesn't have l2 gas price?
</blockquote></details>

@dorimedini-starkware no, older is either 0.13.0 or 0.13.1, need to check.
It's basically the last version were we decided we need a whole new struct and can't workaround with #[serde(default)] as I suggested below
___
*[`crates/starknet_client/src/reader/objects/pending_data.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/643#-O5rxXka9Z7fIysTDnnd:-O5rxXka9Z7fIysTDnne:b-t790kx) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8186d0f428ad17d658de11f418d4cbc6e9545e9/crates/starknet_client/src/reader/objects/pending_data.rs#L206)):*
> ```XML
>     pub l1_gas_price: GasPricePerToken,
>     pub l1_data_gas_price: GasPricePerToken,
>     pub l2_gas_price: GasPricePerToken,
> ```

Add #[serde(default)] to continue supporting 0.13.2

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/643)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/starknet_client/src/reader/objects/pending_data.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/643#-O5hmw6kD7hePENgOV0b:-O5s-5h3C6W_e7_4qekJ:bjas575) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8186d0f428ad17d658de11f418d4cbc6e9545e9/crates/starknet_client/src/reader/objects/pending_data.rs#L168)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

@dorimedini-starkware no, older is either 0.13.0 or 0.13.1, need to check.
It's basically the last version were we decided we need a whole new struct and can't workaround with #[serde(default)] as I suggested below
</blockquote></details>

so the `l2_gas_price` function will return a dummy value - and not fail! - on 0.13.2 blocks?

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/643)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/starknet_client/src/reader/objects/pending_data.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/643#-O5rxXka9Z7fIysTDnnd:-O5xOm7eCKuIzyQUNRnm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8186d0f428ad17d658de11f418d4cbc6e9545e9/crates/starknet_client/src/reader/objects/pending_data.rs#L206)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add #[serde(default)] to continue supporting 0.13.2
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/643#-:-O6_RjX80xu7sjKiXX6W:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/starknet_client/src/reader/objects/pending_data.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/643#-O5hmw6kD7hePENgOV0b:-O6_RHxiAyr0fCOMGLzf:bb2bhpp) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8186d0f428ad17d658de11f418d4cbc6e9545e9/crates/starknet_client/src/reader/objects/pending_data.rs#L168)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

so the `l2_gas_price` function will return a dummy value - and not fail! - on 0.13.2 blocks?
</blockquote></details>

We defined in this PR that l2_gas_price always exists in 0.13.2+ and its value is default if in the deserialization it's missing, so it will return default value for 0.13.2 blocks

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/643)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 177 files at r3, 175 of 175 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/643)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Comment by yoavGrs** [comment]
### Merge activity

* **Sep 22, 5:01 AM EDT**: @yoavGrs started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/643).

**Pull request merged**
