### PR TITLE
chore: clean http server module

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #1513
- #1512
- #1502
- #1501
- #1499 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by nadin-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1499)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/http_server/src/http_server.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1499#-O9jCHEa7FpeUAblDT45:-O9jCHEb75c1NwW6zMrp:bb76mu4) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f8a0b5a5a3de0d0e89c29bd509db4e92601d8a8/crates/http_server/src/http_server.rs#L67)):*
> ```XML
> async fn is_alive() -> HttpServerResult<String> {
>     unimplemented!("Future handling should be implemented here.");
> }
> ```

Why?



_Code quote:_
```XML
#[instrument]
async fn is_alive() -> HttpServerResult<String> {
    unimplemented!("Future handling should be implemented here.");
}
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1499)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/http_server/src/http_server.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1499#-O9jCHEa7FpeUAblDT45:-O9jmUD15Z-doSaw4RoP:b-4s8h03) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f8a0b5a5a3de0d0e89c29bd509db4e92601d8a8/crates/http_server/src/http_server.rs#L67)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Not going to be implemented in this module
</blockquote></details>

It will be part of the "monitoring endpoint"

**Review by nadin-Starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1499)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1499)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#1502](https://github.com/starkware-libs/sequencer/pull/1502)

**Pull request closed without merging**
