### PR TITLE
chore(sequencer_infra): add component client trait for local client

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #2090
- #2089
- #2088
- #2087
- #2086
- #2085
- #2084 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by nadin-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2084)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sequencer_infra/src/component_server/remote_component_server.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2084#-OBu7lM20dxAM18HPZ7Z:-OBu7lM20dxAM18HPZ7_:b-edod1a) ([raw file](https://github.com/starkware-libs/sequencer/blob/ffca5caeac4a95af709a47e3676e45b4bd28f239/crates/starknet_sequencer_infra/src/component_server/remote_component_server.rs#L111)):*
> ```XML
>     Request: Serialize + DeserializeOwned + Send + Sync + 'static,
>     Response: Serialize + DeserializeOwned + Send + Sync + 'static,
>     LocalComponentClient<Request, Response>: ComponentClient<Request, Response>,
> ```

Why is this necessary? The concrete LocalComponentClient struct already implements the ComponentClient trait.



_Code quote:_
```XML
LocalComponentClient<Request, Response>: ComponentClient<Request, Response>,
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2084)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/starknet_sequencer_infra/src/component_server/remote_component_server.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2084#-OBu7lM20dxAM18HPZ7Z:-OBuA6Dz4am5bMx6AVdZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9bb7bdd342bb4a59e7289142a02d2c75a6b2ac23/crates/starknet_sequencer_infra/src/component_server/remote_component_server.rs#L111)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Why is this necessary? The concrete LocalComponentClient struct already implements the ComponentClient trait.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 8 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2084)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by ShahakShama — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2084)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2084#-:-OBuFrQj3O7Ym5E6AEa4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
