### PR TITLE
feat(starknet_batcher): implement sync_block

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2604?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2604** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2604?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2604?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2603** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2603?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2604)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 353 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2604#-ODkVH--2Zrdmc0ewBIR:-ODkVH--2Zrdmc0ewBIS:b91m12n) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b5c9c3a409e2e4ad4cbfb22cd57a4e83a5cb2ac/crates/starknet_batcher/src/batcher.rs#L353)):*
> ```XML
>     }
> 
>     pub async fn add_sync_block(&mut self, sync_block: SyncBlock) -> BatcherResult<()> {
> ```

We should also abort the active height if there is one, right?
___
*[`crates/starknet_batcher/src/batcher.rs` line 353 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2604#-ODkVh6C1LPNcgjGuXFX:-ODkVh6C1LPNcgjGuXFY:b-80jztk) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b5c9c3a409e2e4ad4cbfb22cd57a4e83a5cb2ac/crates/starknet_batcher/src/batcher.rs#L353)):*
> ```XML
>     }
> 
>     pub async fn add_sync_block(&mut self, sync_block: SyncBlock) -> BatcherResult<()> {
> ```

Test?
___
*[`crates/starknet_batcher/src/batcher.rs` line 377 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2604#-ODkUyGAC0m9gel7J8d7:-ODkUyGAC0m9gel7J8d8:b-87rskb) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b5c9c3a409e2e4ad4cbfb22cd57a4e83a5cb2ac/crates/starknet_batcher/src/batcher.rs#L377)):*
> ```XML
>             proposal_output;
>         // TODO(Arni): Move the height and the `info` level log into the function
>         // `commit_proposal_and_block`.
> ```

Why not do it here?



_Code quote:_
```XML
        // TODO(Arni): Move the height and the `info` level log into the function
        // `commit_proposal_and_block`.
```

**Comment by ArniStarkware** [comment]
*[`crates/starknet_batcher/src/batcher.rs` line 357 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2604#-OE99n0x-sCniZY_MI3q:-OE99n0x-sCniZY_MI3r:b-7mcqzc) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc538a5a82ea0d7f5dbf80ba4112714c3fd74430/crates/starknet_batcher/src/batcher.rs#L357)):*
> ```XML
>         let address_to_nonce = state_diff.nonces.iter().map(|(k, v)| (*k, *v)).collect();
>         let tx_hashes = transaction_hashes.into_iter().collect();
>         // TODO: Keep the height from start_height or get it from the input.
> ```

Is this the correct height to be synced to?
Isn't it supposed to be some other height?
The `height` is read from storage. Is it the intention that the given ` state_diff` be committed to the same `height`?



_Code quote:_
```XML
        // TODO: Keep the height from start_height or get it from the input.
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2604)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_batcher/src/batcher.rs` line 353 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2604#-ODkVH--2Zrdmc0ewBIR:-OE9KuXn-suhOriyazqV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b5c9c3a409e2e4ad4cbfb22cd57a4e83a5cb2ac/crates/starknet_batcher/src/batcher.rs#L353)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

We should also abort the active height if there is one, right?
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher.rs` line 353 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2604#-ODkVh6C1LPNcgjGuXFX:-OED_i9P2RDHccjtaZRV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b5c9c3a409e2e4ad4cbfb22cd57a4e83a5cb2ac/crates/starknet_batcher/src/batcher.rs#L353)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Test?
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher.rs` line 377 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2604#-ODkUyGAC0m9gel7J8d7:-OEDa3iw1yVKKHP8nOnF:b-xiuez9) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b5c9c3a409e2e4ad4cbfb22cd57a4e83a5cb2ac/crates/starknet_batcher/src/batcher.rs#L377)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why not do it here?
</blockquote></details>

Because it is incorrect!
We talked on DMs. The height for `decision_reached` should be the current height.
The height for `add_sync_block` should be current height + 1.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2604)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_batcher/src/batcher.rs` line 377 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2604#-ODkUyGAC0m9gel7J8d7:-OEEMOuV3LVYrqov79Vy:b-lktfsb) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b5c9c3a409e2e4ad4cbfb22cd57a4e83a5cb2ac/crates/starknet_batcher/src/batcher.rs#L377)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Because it is incorrect!
We talked on DMs. The height for `decision_reached` should be the current height.
The height for `add_sync_block` should be current height + 1.
</blockquote></details>

1. Reverted the changes to the height marker.
2. Followed through with the original TODO.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2604)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 369 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2604#-OEENU_I4v3YPA_oQ4Qy:-OEENU_I4v3YPA_oQ4Qz:befs9o2) ([raw file](https://github.com/starkware-libs/sequencer/blob/f9e62f0a8858d592d5ef72d1cdbd17ef1bfb9d49/crates/starknet_batcher/src/batcher.rs#L369)):*
> ```XML
>         let info_callback = |height: BlockNumber| {
>             info!("Syncing block at height {} and notifying mempool of the block.", height);
>         };
> ```

This callback is cool, but can't we just have the same message for both?
Also add `#[instrument(skip(self), err)]` at the top and that way we'll be able to distinct the two.



_Code quote:_
```XML
        let info_callback = |height: BlockNumber| {
            info!("Syncing block at height {} and notifying mempool of the block.", height);
        };
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 499 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2604#-OEEPqxN3jPNwxfYzEU8:-OEEPqxN3jPNwxfYzEU9:b-aniizm) ([raw file](https://github.com/starkware-libs/sequencer/blob/f9e62f0a8858d592d5ef72d1cdbd17ef1bfb9d49/crates/starknet_batcher/src/batcher_test.rs#L499)):*
> ```XML
>             tx_hashes: test_tx_hashes(),
>         }))
>         .returning(|_| Ok(()));
> ```

add times(1) so we know they're called.



_Code quote:_
```XML
    mock_dependencies
        .storage_writer
        .expect_commit_proposal()
        .with(eq(INITIAL_HEIGHT), eq(test_state_diff()))
        .returning(|_, _| Ok(()));

    mock_dependencies
        .mempool_client
        .expect_commit_block()
        .with(eq(CommitBlockArgs {
            address_to_nonce: test_contract_nonces(),
            tx_hashes: test_tx_hashes(),
        }))
        .returning(|_| Ok(()));
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 510 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2604#-OEEOA5KCA5vbipRLQvx:-OEEOA5KCA5vbipRLQvy:b-cv7u9m) ([raw file](https://github.com/starkware-libs/sequencer/blob/f9e62f0a8858d592d5ef72d1cdbd17ef1bfb9d49/crates/starknet_batcher/src/batcher_test.rs#L510)):*
> ```XML
> 
>     let get_height_response = batcher.get_height().await.unwrap();
>     assert_eq!(get_height_response.height, INITIAL_HEIGHT);
> ```

This should be the next height after syncing one block, no?
But the storage reader is mocked anyway, so there's no need for this check.



_Suggestion:_
```XML
INITIAL_HEIGHT.next()
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2604)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_batcher/src/batcher.rs` line 369 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2604#-OEENU_I4v3YPA_oQ4Qy:-OEEY1b25m_3z6CaKSvz:b-j2xoeq) ([raw file](https://github.com/starkware-libs/sequencer/blob/f9e62f0a8858d592d5ef72d1cdbd17ef1bfb9d49/crates/starknet_batcher/src/batcher.rs#L369)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This callback is cool, but can't we just have the same message for both?
Also add `#[instrument(skip(self), err)]` at the top and that way we'll be able to distinct the two.
</blockquote></details>

Done. The log changed slightly. For `decision_reached`, the info will no longer contain the `proposal_id` - we count on the fact that the `proposal_id` appears on the call to `decision_reached`.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 499 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2604#-OEEPqxN3jPNwxfYzEU8:-OEEX6w9ATv8m9w4RwAr:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f9e62f0a8858d592d5ef72d1cdbd17ef1bfb9d49/crates/starknet_batcher/src/batcher_test.rs#L499)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

add times(1) so we know they're called.
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 510 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2604#-OEEOA5KCA5vbipRLQvx:-OEEQeVe9ksUZoCx5fRY:bss4a2b) ([raw file](https://github.com/starkware-libs/sequencer/blob/f9e62f0a8858d592d5ef72d1cdbd17ef1bfb9d49/crates/starknet_batcher/src/batcher_test.rs#L510)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This should be the next height after syncing one block, no?
But the storage reader is mocked anyway, so there's no need for this check.
</blockquote></details>

Removed.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2604#-:-OEEZAnp1acRhflXMHdN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
*[`crates/starknet_batcher/src/batcher.rs` line 369 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2604#-OEENU_I4v3YPA_oQ4Qy:-OEEZjqo-ypxVubp4G-c:b8jfyll) ([raw file](https://github.com/starkware-libs/sequencer/blob/f9e62f0a8858d592d5ef72d1cdbd17ef1bfb9d49/crates/starknet_batcher/src/batcher.rs#L369)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done. The log changed slightly. For `decision_reached`, the info will no longer contain the `proposal_id` - we count on the fact that the `proposal_id` appears on the call to `decision_reached`.
</blockquote></details>

```
2024-12-16T13:04:58.220108Z  INFO decision_reached: starknet_batcher::batcher: Committing block at height 3 and notifying mempool of the block. input=DecisionReachedInput { proposal_id: ProposalId(0) }
```

**Pull request merged**
