### PR TITLE
refactor(starknet_batcher): fee market documentation reshape

### PR DESCRIPTION
**Pull request by ayeletstarkware**

### CODE REVIEW

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2964)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2964)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/starknet_batcher/src/fee_market.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2964#-OF1IEfH-c2E_Wjjmhg_:-OF1IEfH-c2E_Wjjmhga:brqqapn) ([raw file](https://github.com/starkware-libs/sequencer/blob/40ec2b77e8bd2a6b12b49068c2be19c1419252d4/crates/starknet_batcher/src/fee_market.rs#L20)):*
> ```XML
> /// - `price`: Base gas price per unit (in FRI) of the current block.
> /// - `gas_used`: Total gas used by all transactions in the block.
> /// - `gas_target`: Target gas usage per block (usually half of the block's gas limit).
> ```

I like these two additions you made. Other than that, I would leave it as it was.



_Suggestion:_
```XML
/// - `price`: The base gas price per unit (in fri) of the current block.
/// - `gas_used`: The total gas used in the current block.
/// - `gas_target`: The target gas usage per block (usually half of a block's gas limit).
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2964)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @MohammadNassar1)

___
*[`crates/starknet_batcher/src/fee_market.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2964#-OF1IEfH-c2E_Wjjmhg_:-OF1MxqdC1spo71VHCe1:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/40ec2b77e8bd2a6b12b49068c2be19c1419252d4/crates/starknet_batcher/src/fee_market.rs#L20)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I like these two additions you made. Other than that, I would leave it as it was.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2964)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
