### PR TITLE
refactor: wrap executable tx in account/l1handler enum

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Comment by yair-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1788?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1788** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1788?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1787** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1787?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yair-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1788)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1788#-OArj0wm4AJJWOe8zWvh:-OArj0wm4AJJWOe8zWvi:bmy2wff) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0da47a3c2d8642c9a38d7efc045bc2b2584ee43/crates/blockifier/src/transaction/transaction_execution.rs#L50)):*
> ```XML
>             }
>             starknet_api::executable_transaction::Transaction::L1Handler(tx) => {
>                 Ok(Transaction::L1Handler(tx.clone()))
> ```

Shouldn't the `TryFrom` take ownership of the struct?



_Suggestion:_
```XML
Ok(Transaction::L1Handler(tx))
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1788)* status: 18 of 20 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @ArniStarkware)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1788#-OArj0wm4AJJWOe8zWvh:-OB4qUjCES3b51mSHHir:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0da47a3c2d8642c9a38d7efc045bc2b2584ee43/crates/blockifier/src/transaction/transaction_execution.rs#L50)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Shouldn't the `TryFrom` take ownership of the struct?
</blockquote></details>

Done.

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1788#-OArj0wm4AJJWOe8zWvh:-OB4uWGCEYpdosfBG6dN:b-9n0ia0) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0da47a3c2d8642c9a38d7efc045bc2b2584ee43/crates/blockifier/src/transaction/transaction_execution.rs#L50)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove the clone :)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1788)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @yair-starkware)

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1788)* status: 11 of 20 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @ArniStarkware)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1788#-OArj0wm4AJJWOe8zWvh:-OB50gX31iwRcnTV6ZWd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0da47a3c2d8642c9a38d7efc045bc2b2584ee43/crates/blockifier/src/transaction/transaction_execution.rs#L50)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Remove the clone :)
</blockquote></details>

Done.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1788)* status: 12 of 20 files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 11 files at r2, 1 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1788)* status: 13 of 20 files reviewed, all discussions resolved (waiting on @alonh5)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 6 of 20 files at r1, 4 of 11 files at r2, 6 of 8 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1788)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by yair-starkware** [comment]
### Merge activity

* **Nov 7, 6:14 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1788).

**Pull request merged**
