### PR TITLE
fix(tests-integration): reenable e2e test

### PR DESCRIPTION
**Pull request by giladchase**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1067)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1067)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase and @yair-starkware)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1067#-O7rm6wZ1wvw5EmVLSh2:-O7rm6wZ1wvw5EmVLSh3:bmyhg1a) ([raw file](https://github.com/starkware-libs/sequencer/blob/48598943e52eed0b413c99ba578e95b86f54ca7d/crates/tests-integration/src/integration_test_utils.rs#L100)):*
> ```XML
> 
> fn create_batcher_config() -> BatcherConfig {
>     let storage_test_config = papyrus_storage::test_utils::get_test_config(None).0;
> ```

Variable, please. :grimacing: 



_Code quote:_
```XML
None
```
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1067#-O7rmO2N0vkGJV8X2ldN:-O7rmO2N0vkGJV8X2ldO:b-5ubl3d) ([raw file](https://github.com/starkware-libs/sequencer/blob/48598943e52eed0b413c99ba578e95b86f54ca7d/crates/tests-integration/tests/end_to_end_test.rs#L16)):*
> ```XML
> #[rstest]
> #[tokio::test]
> async fn test_end_to_end(mut tx_generator: MultiAccountTransactionGenerator) {
> ```

Where are the deploy account transactions?
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1067#-O7rmWIn5m_HcZbKxEH3:-O7rmWIo6mb3N3-0kXVF:b-4wmnh9) ([raw file](https://github.com/starkware-libs/sequencer/blob/48598943e52eed0b413c99ba578e95b86f54ca7d/crates/tests-integration/tests/end_to_end_test.rs#L30)):*
> ```XML
>     let account0_invoke_nonce1 = tx_generator.account_with_id(0).generate_default_invoke();
>     let account1_invoke_nonce1 = tx_generator.account_with_id(1).generate_default_invoke();
>     let account0_invoke_nonce2 = tx_generator.account_with_id(0).generate_default_invoke();
> ```

Reorder, in hashes below as well (I think transactions from same address should appear sequentially).



_Suggestion:_
```XML
    let account0_invoke_nonce2 = tx_generator.account_with_id(0).generate_default_invoke();
    let account1_invoke_nonce1 = tx_generator.account_with_id(1).generate_default_invoke();
```
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1067#-O7rmn-R1BRYx_7K5Q1D:-O7rmn-R1BRYx_7K5Q1E:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/48598943e52eed0b413c99ba578e95b86f54ca7d/crates/tests-integration/tests/end_to_end_test.rs#L53)):*
> ```XML
>     ];
> 
>     let actual_tx_hashes: Vec<TransactionHash> =
> ```





_Suggestion:_
```XML
    
    let account0_invoke_nonce1_tx_hash =
        mock_running_system.assert_add_tx_success(&account0_invoke_nonce1).await;
    let account1_invoke_nonce1_tx_hash =
        mock_running_system.assert_add_tx_success(&account1_invoke_nonce1).await;
    let account0_invoke_nonce2_tx_hash =
        mock_running_system.assert_add_tx_success(&account0_invoke_nonce2).await;
    
    // Test.
    let mempool_txs = mock_running_system.get_txs(4).await;

    // Assert.
    let expected_tx_hashes_from_get_txs = [
        account1_invoke_nonce1_tx_hash,
        account0_invoke_nonce1_tx_hash,
        account0_invoke_nonce2_tx_hash,
    ];
    let actual_tx_hashes: Vec<TransactionHash> =
```

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1067)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1067#-O7rm6wZ1wvw5EmVLSh2:-O7wh-P3-Fxth6llxRTx:b-6uuh7g) ([raw file](https://github.com/starkware-libs/sequencer/blob/48598943e52eed0b413c99ba578e95b86f54ca7d/crates/tests-integration/src/integration_test_utils.rs#L100)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Variable, please. :grimacing:
</blockquote></details>

Also, make it `Some(StorageScope::StateOnly)`
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1067#-O7wh80TD9OtM3_puwrG:-O7wh80TD9OtM3_puwrH:b-l4yitc) ([raw file](https://github.com/starkware-libs/sequencer/blob/48598943e52eed0b413c99ba578e95b86f54ca7d/crates/tests-integration/src/integration_test_utils.rs#L100)):*
> ```XML
> 
> fn create_batcher_config() -> BatcherConfig {
>     let storage_test_config = papyrus_storage::test_utils::get_test_config(None).0;
> ```

You should keep the temp dir handle for the duration of the test



_Code quote:_
```XML
.0
```

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1067)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul and @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1067)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul and @yair-starkware)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1067#-O7wh80TD9OtM3_puwrG:-O81SqGR8zCyMLUkFwhI:b1qz80x) ([raw file](https://github.com/starkware-libs/sequencer/blob/48598943e52eed0b413c99ba578e95b86f54ca7d/crates/tests-integration/src/integration_test_utils.rs#L100)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

You should keep the temp dir handle for the duration of the test
</blockquote></details>

For context: this is the docstring of the method:
```rust
/// Returns a db config and the temporary directory that holds this db.
/// The TempDir object is returned as a handler for the lifetime of this object (the temp
/// directory), thus make sure the directory won't be destroyed. The caller should propagate the
/// TempDir object until it is no longer needed. When the TempDir object is dropped, the directory
/// is deleted.
pub fn get_test_config(storage_scope: Option<StorageScope>) -> (StorageConfig, TempDir) {
 ```

Question: looks like TempDir is a newtype around a Path, which means it should be possible to create a mocked storage Environment that will own the tempdir (as some path wrapper type, say by some trait that impl's `path()`) and then we won't have to maintain the handle ourselves.
WDYT? 
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1067#-O7rm6wZ1wvw5EmVLSh2:-O81WzNt8XoOUQ3MpMOj:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/48598943e52eed0b413c99ba578e95b86f54ca7d/crates/tests-integration/src/integration_test_utils.rs#L100)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Also, make it `Some(StorageScope::StateOnly)`
</blockquote></details>

Done.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1067)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @elintul and @yair-starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1067#-O7rmO2N0vkGJV8X2ldN:-O81X0xkCJTKC515qNro:b2p3cqi) ([raw file](https://github.com/starkware-libs/sequencer/blob/48598943e52eed0b413c99ba578e95b86f54ca7d/crates/tests-integration/tests/end_to_end_test.rs#L16)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Where are the deploy account transactions?
</blockquote></details>

Unsupported, only invoke are supported for now.
What's happening now is that the accounts defined below are injected directly into the state via `IntegrationTestSetup`
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1067#-O7rmWIn5m_HcZbKxEH3:-O81XS2U7PUzAipHKCnE:bx8luer) ([raw file](https://github.com/starkware-libs/sequencer/blob/48598943e52eed0b413c99ba578e95b86f54ca7d/crates/tests-integration/tests/end_to_end_test.rs#L30)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Reorder, in hashes below as well (I think transactions from same address should appear sequentially).
</blockquote></details>

Reordered this one, but in the add_tx lines I intentionally did them out of order, because in real life there is no reason to assume that txs are sorted by address, they can appear in any order.

As for the expected hashes, their order is determined by the mempool's get_txs ordering.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1067)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase and @yair-starkware)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1067#-O7wh80TD9OtM3_puwrG:-O81p8a04AVQ1i32kM-8:b-98u1b3) ([raw file](https://github.com/starkware-libs/sequencer/blob/48598943e52eed0b413c99ba578e95b86f54ca7d/crates/tests-integration/src/integration_test_utils.rs#L100)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

For context: this is the docstring of the method:
```rust
/// Returns a db config and the temporary directory that holds this db.
/// The TempDir object is returned as a handler for the lifetime of this object (the temp
/// directory), thus make sure the directory won't be destroyed. The caller should propagate the
/// TempDir object until it is no longer needed. When the TempDir object is dropped, the directory
/// is deleted.
pub fn get_test_config(storage_scope: Option<StorageScope>) -> (StorageConfig, TempDir) {
 ```

Question: looks like TempDir is a newtype around a Path, which means it should be possible to create a mocked storage Environment that will own the tempdir (as some path wrapper type, say by some trait that impl's `path()`) and then we won't have to maintain the handle ourselves.
WDYT?
</blockquote></details>

Sounds better than let it leak.
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 51 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1067#-O81l5Je2v_1xc8E4vgj:-O81l5Jf8YnCyBjpBT3a:b-lbpide) ([raw file](https://github.com/starkware-libs/sequencer/blob/4f9fe5cf3112b6e9b2a79865665e770056cc4ccc/crates/tests-integration/src/integration_test_utils.rs#L51)):*
> ```XML
>             rpc_state_reader_config,
>             ..MempoolNodeConfig::default()
>         },
> ```

Please define variable.



_Code quote:_
```XML
        MempoolNodeConfig {
            batcher_config,
            gateway_config,
            http_server_config,
            rpc_state_reader_config,
            ..MempoolNodeConfig::default()
        },
```
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 107 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1067#-O81o59o2YHSJ9ib83-T:-O81o59o2YHSJ9ib83-U:b-kije9p) ([raw file](https://github.com/starkware-libs/sequencer/blob/4f9fe5cf3112b6e9b2a79865665e770056cc4ccc/crates/tests-integration/src/integration_test_utils.rs#L107)):*
> ```XML
>     // Need to keep the file handle alive to prevent the tempdir from being deleted.
>     let (storage_test_config, tempdir_file_handle) =
>         papyrus_storage::test_utils::get_test_config(storage_scope);
> ```

Why fully-qualified?



_Code quote:_
```XML
papyrus_storage::test_utils::get_test_config
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1067)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @yair-starkware)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 107 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1067#-O81o59o2YHSJ9ib83-T:-O81qUat3KWahL_3ZFqT:bgl3slx) ([raw file](https://github.com/starkware-libs/sequencer/blob/4f9fe5cf3112b6e9b2a79865665e770056cc4ccc/crates/tests-integration/src/integration_test_utils.rs#L107)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why fully-qualified?
</blockquote></details>

Srry, fixed

**Review by giladchase — COMMENTED** [review]
Test currently failing due to a new commit merged to main: 6fa9be314825015c263d8f4ff891b8f5284d1adc
Working on adding support, has to do with l2 gas support being added.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1067#-:-O81snST33iY2FOVTjLl:bcmr69)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @elintul and @yair-starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1067)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1067)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1067#-O7wh80TD9OtM3_puwrG:-O82ABIF9oI52WCR_raA:bd5ojst) ([raw file](https://github.com/starkware-libs/sequencer/blob/48598943e52eed0b413c99ba578e95b86f54ca7d/crates/tests-integration/src/integration_test_utils.rs#L100)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Sounds better than let it leak.
</blockquote></details>

There are a lot of places that expect the actual type, will be hard to change everything now

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1067)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 1 of 6 files at r4, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1067)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1067)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1067#-O7wh80TD9OtM3_puwrG:-O82JknB7EtzWd3Wwk57:b-fdbbks) ([raw file](https://github.com/starkware-libs/sequencer/blob/48598943e52eed0b413c99ba578e95b86f54ca7d/crates/tests-integration/src/integration_test_utils.rs#L100)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

There are a lot of places that expect the actual type, will be hard to change everything now
</blockquote></details>

I'll can take care of it, do you like the solution though?

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1067)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1067)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
