### PR TITLE
feat(consensus): add the actual consensus config to the consensus manager crate

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1197)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1197?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1197** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1197?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1196** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1196?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1195** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1195?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1194** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1194?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1193** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1193?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1192** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1192?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1197)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/consensus_manager/src/config.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1197#-O8We0uKD4vZE4r5v184:-O8We0uLEDXuS8IwByxb:b-v1csaw) ([raw file](https://github.com/starkware-libs/sequencer/blob/cfb3da4737ae3684ab410d9cc7b05f5f1c534692/crates/consensus_manager/src/config.rs#L14)):*
> ```XML
> pub struct ConsensusManagerConfig {
>     pub consensus_config: ConsensusConfig,
> }
> ```

Will there be other configs here?



_Code quote:_
```XML
    pub consensus_config: ConsensusConfig,
}
```

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1197)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @Itay-Tsabary-Starkware)

___
*[`crates/consensus_manager/src/config.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1197#-O8We0uKD4vZE4r5v184:-O8Wf8BH4EeyO_3172PQ:b-bb1mur) ([raw file](https://github.com/starkware-libs/sequencer/blob/cfb3da4737ae3684ab410d9cc7b05f5f1c534692/crates/consensus_manager/src/config.rs#L14)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Will there be other configs here?
</blockquote></details>

I don't know. We haven't finished integrating external dependencies yet (e.g. network) and I don't know how that will look, so hard to tell.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1197#-:-O8Wg4uQ29FqOVxKOfz3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/consensus_manager/src/config.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1197#-O8We0uKD4vZE4r5v184:-O8WfsTd64eT_T7Vjhe_:b-cn58df) ([raw file](https://github.com/starkware-libs/sequencer/blob/cfb3da4737ae3684ab410d9cc7b05f5f1c534692/crates/consensus_manager/src/config.rs#L14)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I don't know. We haven't finished integrating external dependencies yet (e.g. network) and I don't know how that will look, so hard to tell.
</blockquote></details>

1. Ack
2. Unblocking
3. Please note that if this ends up the only config then there's a redundant layer of indirection

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1197)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @Itay-Tsabary-Starkware)

___
*[`crates/consensus_manager/src/config.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1197#-O8We0uKD4vZE4r5v184:-O8WgVTg7B1xfOMBgIvD:bd6s1z5) ([raw file](https://github.com/starkware-libs/sequencer/blob/cfb3da4737ae3684ab410d9cc7b05f5f1c534692/crates/consensus_manager/src/config.rs#L14)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

1. Ack
2. Unblocking
3. Please note that if this ends up the only config then there's a redundant layer of indirection
</blockquote></details>

Added TODO to remove this if this remains the case.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1197)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1197)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

**Comment by matan-starkware** [comment]
### Merge activity

* **Oct 13, 5:42 AM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1197).

**Pull request merged**
