### PR TITLE
refactor: share the chain info as a config for the gateway

### PR DESCRIPTION
**Pull request by ArniStarkware**
The `ChainInfo` is a part of the config that is relevant not only to the stateful validator but also to the conversion `RpcTransaction` -> `ExecutableTransaction`. In this PR we move this config to be a part of the `GatewayConfig`. 

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/520)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/520?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#520** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/520?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#519** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/519?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#518** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/518?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#517** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/517?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#516** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/516?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/520)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/520#-O8bOY_z25w9bJ2pRCgt:-O8bOY_z25w9bJ2pRCgu:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7df7bc35a40605a65ca53a75c4cf98bfc69cc718/crates/gateway/src/stateful_transaction_validator_test.rs#L58)):*
> ```XML
>             validate_max_n_steps: block_context.versioned_constants().validate_max_n_steps,
>             max_recursion_depth: block_context.versioned_constants().max_recursion_depth,
>         },
> ```





_Suggestion:_
```XML
        config: StatefulTransactionValidatorConfig::default()
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/520#-O8bObcb2lPCJkVpyRGz:-O8bObcb2lPCJkVpyRH-:bwflfj9) ([raw file](https://github.com/starkware-libs/sequencer/blob/7df7bc35a40605a65ca53a75c4cf98bfc69cc718/crates/gateway/src/stateful_transaction_validator_test.rs#L119)):*
> ```XML
>             validate_max_n_steps: block_context.versioned_constants().validate_max_n_steps,
>             max_recursion_depth: block_context.versioned_constants().max_recursion_depth,
>         },
> ```

check if can use the fixture here



_Suggestion:_
```XML
        config: StatefulTransactionValidatorConfig::default()
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/520)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1 and @Yael-Starkware)

___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/520#-O8bOY_z25w9bJ2pRCgt:-O8feTbf8fjvVOVu-EP7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7df7bc35a40605a65ca53a75c4cf98bfc69cc718/crates/gateway/src/stateful_transaction_validator_test.rs#L58)):*
> ```XML
>             validate_max_n_steps: block_context.versioned_constants().validate_max_n_steps,
>             max_recursion_depth: block_context.versioned_constants().max_recursion_depth,
>         },
> ```

Done.
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/520#-O8bObcb2lPCJkVpyRGz:-O8feTIt9LEVBda264lB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7df7bc35a40605a65ca53a75c4cf98bfc69cc718/crates/gateway/src/stateful_transaction_validator_test.rs#L119)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

check if can use the fixture here
</blockquote></details>

Done.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r2, 1 of 6 files at r3, 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/520)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/520#-O8bObcb2lPCJkVpyRGz:-O8fsTsEB7fslP7hQKpO:b-yb1f8x) ([raw file](https://github.com/starkware-libs/sequencer/blob/7df7bc35a40605a65ca53a75c4cf98bfc69cc718/crates/gateway/src/stateful_transaction_validator_test.rs#L119)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

so the fixture didn't work?

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/520#-O8bObcb2lPCJkVpyRGz:-O8g-UZN2aA3eQehvqIu:b9pymmd) ([raw file](https://github.com/starkware-libs/sequencer/blob/7df7bc35a40605a65ca53a75c4cf98bfc69cc718/crates/gateway/src/stateful_transaction_validator_test.rs#L119)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

so the fixture didn't work?
</blockquote></details>

It did. stateful_validator was removed.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/520#-O8bObcb2lPCJkVpyRGz:-O8jWxEo8Kf3TrysOma8:bxpfes2) ([raw file](https://github.com/starkware-libs/sequencer/blob/7df7bc35a40605a65ca53a75c4cf98bfc69cc718/crates/gateway/src/stateful_transaction_validator_test.rs#L119)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

It did. stateful_validator was removed.
</blockquote></details>

stateful validator is now a fixture of the test.
There is no need for chain_info to be a fixture - as this is the only test where it is used.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/520)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by Yael-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/520#-:-O8jz4Ze5VHXkm4dOQeR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
