### PR TITLE
chore(starknet_consensus_manager): add proposal init into validate proposal input

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Review by matan-starkware — COMMENTED** [review]
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2408)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @ArniStarkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2408#-ODKi1Ag9paPE0tdLXuV:-ODKi1Ag9paPE0tdLXuW:b-96a5z6) ([raw file](https://github.com/starkware-libs/sequencer/blob/875738b54f3ea2e175d0a9ead47f8cebfb4c990a/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs#L75)):*
> ```XML
>                 round: 0,
>                 valid_round: None,
>                 proposer: ValidatorId::default(),
> ```

1. Let's avoid `ValidatorId::default()` since this is 0 which is an illegal address.
2. Don't set valid_round explicitly because: (a) `validate_proposal` doesn't care about the field, (b) we'll add `signature` field soon which also should be ignored and default makes that seamless.

Please do this for all tests



_Suggestion:_
```XML
            ProposalInit {
                height: block_number,
                round: 0,
                proposer: 100.into(),
                ..Default::default(),
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2408)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2408#-ODKi1Ag9paPE0tdLXuV:-ODKm0Jq1YuetgbAPgDh:bnhl6ts) ([raw file](https://github.com/starkware-libs/sequencer/blob/875738b54f3ea2e175d0a9ead47f8cebfb4c990a/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs#L75)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

1. Let's avoid `ValidatorId::default()` since this is 0 which is an illegal address.
2. Don't set valid_round explicitly because: (a) `validate_proposal` doesn't care about the field, (b) we'll add `signature` field soon which also should be ignored and default makes that seamless.

Please do this for all tests
</blockquote></details>

I did that for all the tests I added in this PR.
Done.

**Comment by ArniStarkware** [comment]
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2408#-ODKi1Ag9paPE0tdLXuV:-ODeeLcC5bMjz5Fvdklh:bpfrif3) ([raw file](https://github.com/starkware-libs/sequencer/blob/875738b54f3ea2e175d0a9ead47f8cebfb4c990a/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs#L75)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I did that for all the tests I added in this PR.
Done.
</blockquote></details>

Also, it is based on the change to the validator ID.

**Review by alonh5 — COMMENTED** [review]
> Reviewed 2 of 11 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2408)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs` line 184 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2408#-ODegVEK5f6EM_qZct-p:-ODegVEK5f6EM_qZct-q:b-no149d) ([raw file](https://github.com/starkware-libs/sequencer/blob/514e2e77f3d89728f81c96c22cc5c9e9cee45d86/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs#L184)):*
> ```XML
>                 // the block in storage and to getting the transaction was a revert
>                 // this flow will fail.
>                 wait_for_block(&storage_reader, proposal_init.height)
> ```

Maybe it's worth adding `let height = proposal_init.height`?



_Code quote:_
```XML
proposal_init.height
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2408)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs` line 184 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2408#-ODegVEK5f6EM_qZct-p:-ODf8aU62ZK5XJfNq7CS:b-wyj10o) ([raw file](https://github.com/starkware-libs/sequencer/blob/514e2e77f3d89728f81c96c22cc5c9e9cee45d86/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs#L184)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Maybe it's worth adding `let height = proposal_init.height`?
</blockquote></details>

This is consistent with how this variable is handled in a similar function in this file:`build_proposal`

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2408)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs` line 184 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2408#-ODegVEK5f6EM_qZct-p:-ODkbMmm1erHefXNww9F:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/514e2e77f3d89728f81c96c22cc5c9e9cee45d86/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs#L184)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I didn't understand your response. I'm saying `proposal_init.height` is used like 7 times in this function so it's probably defining a shorter variable name for it. Same goes for `build_proposal` in that case.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2408#-:-OEE8Yv8-nLPGXDarI6H:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

**Review by alonh5 — APPROVED** [review]
> Dismissed @matan-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2408)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by alonh5 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2408)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @matan-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2408#-OEOVS_AEsS-tQg_9svE:-OEOVS_AEsS-tQg_9svF:b48cb1f) (no related file):*
Make sure with @matan-starkware if he wants this or not, and then merge or close accordingly.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r3, 1 of 2 files at r4, 4 of 5 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2408)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2408#-ODKi1Ag9paPE0tdLXuV:-OESu3Wt5KhNXz_lvbzO:b-iuo1uw) ([raw file](https://github.com/starkware-libs/sequencer/blob/875738b54f3ea2e175d0a9ead47f8cebfb4c990a/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs#L75)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Also, it is based on the change to the validator ID.
</blockquote></details>

Can you explicitly define `Default for ProposalInit` and that can have `DEFAULT_VALIDATOR_ID`. I think that will make usage easier.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 205 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2408#-OESvquLABTkokZ8X_PU:-OESvquLABTkokZ8X_PV:b-g7dgev) ([raw file](https://github.com/starkware-libs/sequencer/blob/e460a618f2a9ad0a0d8c70c924ce65500e4eb222/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L205)):*
> ```XML
>                 proposer: ValidatorId::from(DEFAULT_VALIDATOR_ID),
>                 ..Default::default()
>             },
> ```

If you don't care about the field's specifics.



_Suggestion:_
```XML
            ProposalInit::default(),
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 348 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2408#-OESvdrL2OUHj4a9NpA3:-OESvdrL2OUHj4a9NpA4:bghqh9o) ([raw file](https://github.com/starkware-libs/sequencer/blob/e460a618f2a9ad0a0d8c70c924ce65500e4eb222/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L348)):*
> ```XML
>             content_receiver,
>         )
>         .await;
> ```

Let's refactor to highlight the round change.



_Suggestion:_
```XML
    let mut init = ProposalInit {
        round: 0,
        ..Default::default()
    };
    let fin_receiver_past_round =
        context.validate_proposal(init.clone(), TIMEOUT, content_receiver).await;
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 367 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2408#-OESvlVr3E6Mj33l4zkd:-OESvlVr3E6Mj33l4zke:b-u5yhfx) ([raw file](https://github.com/starkware-libs/sequencer/blob/e460a618f2a9ad0a0d8c70c924ce65500e4eb222/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L367)):*
> ```XML
>             content_receiver,
>         )
>         .await;
> ```

and for round 2.



_Suggestion:_
```XML
    init.round = 1;
    let fin_receiver_curr_round =
        context.validate_proposal(init.clone(), TIMEOUT, content_receiver).await;
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2408)* status: 3 of 12 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2408#-ODKi1Ag9paPE0tdLXuV:-OETAnIY-lZxdo6Nx3DQ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/875738b54f3ea2e175d0a9ead47f8cebfb4c990a/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs#L75)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Can you explicitly define `Default for ProposalInit` and that can have `DEFAULT_VALIDATOR_ID`. I think that will make usage easier.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 205 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2408#-OESvquLABTkokZ8X_PU:-OETApqk16JPI3MAiQOE:b-naqrh0) ([raw file](https://github.com/starkware-libs/sequencer/blob/e460a618f2a9ad0a0d8c70c924ce65500e4eb222/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L205)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

If you don't care about the field's specifics.
</blockquote></details>

Done. Throughout the code. 
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 348 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2408#-OESvdrL2OUHj4a9NpA3:-OETBSSf4V4vRAz32Okd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e460a618f2a9ad0a0d8c70c924ce65500e4eb222/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L348)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's refactor to highlight the round change.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 367 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2408#-OESvlVr3E6Mj33l4zkd:-OETBQz3CBbKnm4H4eUG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e460a618f2a9ad0a0d8c70c924ce65500e4eb222/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L367)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

and for round 2.
</blockquote></details>

Done.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2408)* status: 3 of 12 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @matan-starkware)

___
*[`crates/papyrus_protobuf/src/consensus.rs` line 81 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2408#-OETL2g8Ab_49vbWrNAA:-OETL2g8Ab_49vbWrNAB:b-bt0w3) ([raw file](https://github.com/starkware-libs/sequencer/blob/a57aead4777ce087231832976099fbfcb5f7cf46/crates/papyrus_protobuf/src/consensus.rs#L81)):*
> ```XML
>             round: Default::default(),
>             valid_round: Default::default(),
>             // TODO(Arni): Use DEFAULT_VALIDATOR_ID instead of 100.
> ```

Done. #2812.



_Code quote:_
```XML
// TODO(Arni): Use DEFAULT_VALIDATOR_ID instead of 100.
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2408)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @ArniStarkware)

___
*[`crates/papyrus_protobuf/src/consensus.rs` line 83 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2408#-OETM75a5eEM_kLzpVZv:-OETM75a5eEM_kLzpVZw:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/a57aead4777ce087231832976099fbfcb5f7cf46/crates/papyrus_protobuf/src/consensus.rs#L83)):*
> ```XML
>             // TODO(Arni): Use DEFAULT_VALIDATOR_ID instead of 100.
>             proposer: ContractAddress::from(100_u64),
>         }
> ```





_Suggestion:_
```XML
    fn default() -> Self {
        ProposalInit {
            // TODO(Arni): Use DEFAULT_VALIDATOR_ID instead of 100.
            proposer: ContractAddress::from(100_u64),
            ..Default::default(),
        }
```

**Review by matan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2408)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @ArniStarkware)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2408)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/papyrus_protobuf/src/consensus.rs` line 83 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2408#-OETM75a5eEM_kLzpVZv:-OETN4gC7hUMDTvwzy-n:b-hacsl3) ([raw file](https://github.com/starkware-libs/sequencer/blob/a57aead4777ce087231832976099fbfcb5f7cf46/crates/papyrus_protobuf/src/consensus.rs#L83)):*
> ```XML
>             // TODO(Arni): Use DEFAULT_VALIDATOR_ID instead of 100.
>             proposer: ContractAddress::from(100_u64),
>         }
> ```

```warning: function cannot return without recursing```
This is because we are now defining default, so we can not use default to define it.

I suspect your suggestion does not even work.

**Pull request merged**
