### PR TITLE
refactor: split syscalls into separate files

### PR DESCRIPTION
**Pull request by varex83**
This PR is part of the [series](https://excalidraw.com/#json=aT-LWSYR2DZh0v_Mxd5T0,6DOQEMdFUKxD2aBnaBH6dw) of PRs that brings `cairo-native` to the `blockifier`. These changes are need because they create more generic testing approach that could be applied for `NativeSyscallHandler`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/344)

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 17 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/344)* status: 14 of 19 files reviewed, 9 unresolved discussions (waiting on @varex83)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/344#-O3gueSRECQ8QYtYfKWi:-O3gueSRECQ8QYtYfKWj:b-yxvrmx) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef8318be50c2851c3ef05fbb906097cdd3bea3da/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L57)):*
> ```XML
>     );
> 
>     // ensure that the fallback system didn't replace the contract
> ```

Comment convention.



_Suggestion:_
```XML
// Ensure that the fallback system didn't replace the contract.
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/consts.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/344#-O3hE_7w1R2w2blf0ydj:-O3hE_7w1R2w2blf0ydk:bdy438u) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef8318be50c2851c3ef05fbb906097cdd3bea3da/crates/blockifier/src/execution/syscalls/syscall_tests/consts.rs#L1)):*
> ```XML
> pub const REQUIRED_GAS_CALL_CONTRACT_TEST: u64 = 105680;
> ```

Rename this file to `constants.rs` (naming convention)
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/deploy.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/344#-O3hJuy_Cr04Z5km_WvS:-O3hJuy_Cr04Z5km_WvT:b-uh6y1y) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef8318be50c2851c3ef05fbb906097cdd3bea3da/crates/blockifier/src/execution/syscalls/syscall_tests/deploy.rs#L29)):*
> ```XML
>     );
> 
>     assert_consistent_contract_version(deployer_contract, &state);
> ```

We may not need these checks since we ain't going to support fallback to casm
Please add a TODO (can be on me) to share the init code of the tests in this file once `assert_consistent_contract_version` is removed.



_Code quote:_
```XML
assert_consistent_contract_version
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/get_block_hash.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/344#-O3gw_EwEYTYg9c4fiO2:-O3gw_ExEqQm-7mRM0Ol:bnwwd7z) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef8318be50c2851c3ef05fbb906097cdd3bea3da/crates/blockifier/src/execution/syscalls/syscall_tests/get_block_hash.rs#L84)):*
> ```XML
>     assert!(error
>         .to_string()
>         .contains("Unauthorized syscall get_block_hash in execution mode Validate"));
> ```

Seems redundant - remove one of the checks.



_Code quote:_
```XML
    check_entry_point_execution_error_for_custom_hint!(
        &error,
        "Unauthorized syscall get_block_hash in execution mode Validate.",
    );

    assert!(error
        .to_string()
        .contains("Unauthorized syscall get_block_hash in execution mode Validate"));
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/344#-O3h1q7M8pFG8kcnS0yk:-O3h1q7M8pFG8kcnS0yl:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef8318be50c2851c3ef05fbb906097cdd3bea3da/crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs#L141)):*
> ```XML
>     let expected_resource_bounds: Vec<Felt> = match (test_contract, version) {
>         (FeatureContract::LegacyTestContract, _) => vec![],
>         (_, version) if version == TransactionVersion(Felt::from_hex("0x1").unwrap()) => vec![
> ```





_Suggestion:_
```XML
TransactionVersion::ONE
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/344#-O3h2ePCDqEY4MmIFlZd:-O3h2ePCDqEY4MmIFlZe:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef8318be50c2851c3ef05fbb906097cdd3bea3da/crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs#L157)):*
> ```XML
>     let expected_tx_info: Vec<Felt>;
>     let tx_info: TransactionInfo;
>     if version == TransactionVersion(Felt::from_hex("0x1").unwrap()) {
> ```





_Suggestion:_
```XML
TransactionVersion::ONE
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/storage_read_write.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/344#-O3gtogsA2ivNmuDHyUZ:-O3gtogtALqHb0Anad70:b9uozi) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef8318be50c2851c3ef05fbb906097cdd3bea3da/crates/blockifier/src/execution/syscalls/syscall_tests/storage_read_write.rs#L48)):*
> ```XML
>     assert_eq!(value_from_state, value);
> 
>     // ensure that the fallback system didn't replace the contract
> ```

Comment convention (start with a capital letter, end with `.`)



_Suggestion:_
```XML
// Ensure that the fallback system didn't replace the contract.
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/utils.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/344#-O3guNDLA_uH5363qFgI:-O3guNDLA_uH5363qFgJ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef8318be50c2851c3ef05fbb906097cdd3bea3da/crates/blockifier/src/execution/syscalls/syscall_tests/utils.rs#L8)):*
> ```XML
> 
> pub fn assert_consistent_contract_version(contract: FeatureContract, state: &dyn State) {
>     let hash = contract.get_class_hash();
> ```





_Suggestion:_
```XML
class_hash = contract.get_class_hash();
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/utils.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/344#-O3gtxIn7Eyl35VHrvka:-O3gtxIn7Eyl35VHrvkb:b-801f0p) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef8318be50c2851c3ef05fbb906097cdd3bea3da/crates/blockifier/src/execution/syscalls/syscall_tests/utils.rs#L18)):*
> ```XML
>         | FeatureContract::FaultyAccount(_)
>         | FeatureContract::TestContract(_) => {
>             // Assert contract uses VM
> ```

Comment convention



_Suggestion:_
```XML
// Assert contract uses VM.
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/344)* status: 14 of 19 files reviewed, 10 unresolved discussions (waiting on @varex83)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/344#-O3hLL_CBbf7oil2uSCq:-O3hLL_CBbf7oil2uSCr:b-aafqex) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef8318be50c2851c3ef05fbb906097cdd3bea3da/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L28)):*
> ```XML
>     };
>     let error = entry_point_call.execute_directly(&mut state).unwrap_err().to_string();
>     assert!(error.contains("Out of gas"));
> ```

(Non-blocking) why didn't you take this?
```rust
    assert_matches!(error, EntryPointExecutionError::ExecutionFailed{ error_data }
        if error_data == vec![felt!(OUT_OF_GAS_ERROR)]);
```
(It's more specific)



_Code quote:_
```XML
    assert!(error.contains("Out of gas"));
```

**Review by varex83 — COMMENTED** [review]
As far as I understood, we don't need the `assert_consistent_contract_version` at all, correct?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/344#-:-O3hiH34-JdB5LhhySDj:b-lxatzh)* status: 14 of 19 files reviewed, 10 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/344#-O3hLL_CBbf7oil2uSCq:-O3hhpRo0hq43v21Sku5:b-mnz860) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef8318be50c2851c3ef05fbb906097cdd3bea3da/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L28)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

(Non-blocking) why didn't you take this?
```rust
    assert_matches!(error, EntryPointExecutionError::ExecutionFailed{ error_data }
        if error_data == vec![felt!(OUT_OF_GAS_ERROR)]);
```
(It's more specific)
</blockquote></details>

We've done that because native vs VM errors will have different interfaces and the easiest way to implement error checking was using `.contains`

**Review by Yoni-Starkware — APPROVED** [review]
As far as I can tell - right. 
:lgtm: 

> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/344#-:-O3hjRx1DH2ABFYktglu:b-p66lev)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @varex83)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/344#-O3hLL_CBbf7oil2uSCq:-O3hjw9N-_pax7sqtVOl:bb6u032) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef8318be50c2851c3ef05fbb906097cdd3bea3da/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L28)):*
<details><summary><i>Previously, varex83 (Bohdan Ohorodnii) wrote…</i></summary><blockquote>

We've done that because native vs VM errors will have different interfaces and the easiest way to implement error checking was using `.contains`
</blockquote></details>

Cool

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/344#-:-O3lEMi3DFsGmy5G77kU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @varex83)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/344)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @varex83)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/344)* status: all files reviewed, 1 unresolved discussion (waiting on @varex83)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 986 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/344#-O4-6tjW9g1iYGsC5i4n:-O4-6tjW9g1iYGsC5i4o:bufp61o) ([raw file](https://github.com/starkware-libs/sequencer/blob/c2537a95654d67bcadf83181ed5468e5b315aee3/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L986)):*
> ```XML
>     let error = EntryPointExecutionError::ExecutionFailed { error_data };
>     assert_eq!(error.to_string(), "Execution failed. Failure reason: \"Execution failure\".");
> }
> ```

Sorry, missed that - please keep this test



_Code quote:_
```XML
#[test]
fn test_syscall_failure_format() {
    let error_data = vec![
        // Magic to indicate that this is a byte array.
        BYTE_ARRAY_MAGIC,
        // the number of full words in the byte array.
        "0x00",
        // The pending word of the byte array: "Execution failure"
        "0x457865637574696f6e206661696c757265",
        // The length of the pending word.
        "0x11",
    ]
    .into_iter()
    .map(|x| Felt::from_hex(x).unwrap())
    .collect();
    let error = EntryPointExecutionError::ExecutionFailed { error_data };
    assert_eq!(error.to_string(), "Execution failed. Failure reason: \"Execution failure\".");
}
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/344#-:-O4512653mWjmFbv1kbt:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @varex83)

**Review by Yoni-Starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/344#-:-O46wyb968YSO9YzD0_c:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @varex83)

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/344)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @varex83)

**Pull request merged**
