### PR TITLE
chore(mempool_node): rename server struct

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #1111
- #1110
- #1109
- #1103
- #1102
- #1101
- #1100
- #1099
- #1098
- #1097 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1097)

### CODE REVIEW

**Review by lev-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1097)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/servers.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1097#-O81vsFQ0n1nSwCQx2xW:-O81vsFQ0n1nSwCQx2xX:bl9895w) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f5e7768ffa1b3e81575b22c54b748f1d49b5088/crates/mempool_node/src/servers.rs#L39)):*
> ```XML
> pub struct SequencerNodeServers {
>     pub local_servers: LocalServers,
>     pub wrapper_servers: WrapperServers,
> ```

Sorry for not mentioning it in the previous PRs. 
All our servers are wrappers. So it's a bad name.
___
*[`crates/mempool_node/src/servers.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1097#-O81wWm270U5mqJzCjzU:-O81wWm270U5mqJzCjzV:buy4g1s) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f5e7768ffa1b3e81575b22c54b748f1d49b5088/crates/mempool_node/src/servers.rs#L46)):*
> ```XML
>     communication: &mut SequencerNodeCommunication,
>     components: Components,
> ) -> SequencerNodeServers {
> ```

If we are going to change things to 'sequencer...', we also need also rename the folder 'mempool_node' to 'sequencer_node'.

**Review by lev-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1097#-:-O82-lNw3lUwNcNbNu28:bnfp4nl)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

**Review by lev-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1097)* status: all files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1097)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#1098](https://github.com/starkware-libs/sequencer/pull/1098)

**Pull request closed without merging**
