### PR TITLE
feat(batcher): send proposal commitment when proposal is done

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1359)

### CODE REVIEW

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1359)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @alonh5, @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-O9ABT5W2hkkcJtGOKDL:-O9ABT5W2hkkcJtGOKDM:b-2p89re) ([raw file](https://github.com/starkware-libs/sequencer/blob/f873b2373e7f93b5c9c70d941ee9a850083b719e/crates/batcher/src/proposal_manager.rs#L234)):*
> ```XML
>     }
> 
>     async fn get_done_proposal_commitment(
> ```

the name should reflect that this function also removes the item from done_proposals



_Suggestion:_
```XML
take_done_proposal_commitment
```
___
*[`crates/batcher/src/proposal_manager.rs` line 237 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-O9A-gb-9LNN2OIhFHx0:-O9A-gb-9LNN2OIhFHx1:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/f873b2373e7f93b5c9c70d941ee9a850083b719e/crates/batcher/src/proposal_manager.rs#L237)):*
> ```XML
>         &self,
>         proposal_id: ProposalId,
>     ) -> Option<ProposalCommitment> {
> ```





_Suggestion:_
```XML
ProposalManagerResult
```
___
*[`crates/batcher/src/proposal_manager.rs` line 384 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-O9AC2o1DDAQeC9TtNCS:-O9AC2o1DDAQeC9TtNCT:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/f873b2373e7f93b5c9c70d941ee9a850083b719e/crates/batcher/src/proposal_manager.rs#L384)):*
> ```XML
>         active_proposal: Arc<Mutex<Option<ProposalId>>>,
>         result: Result<DoneProposal, BuildProposalError>,
>         done_proposals: Arc<Mutex<HashMap<ProposalId, Result<DoneProposal, BuildProposalError>>>>,
> ```





_Suggestion:_
```XML
BuildProposalResult
```

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1359)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-O9Adfox7VMM-r5xv8Ye:-O9Adfox7VMM-r5xv8Yf:b5c21s4) ([raw file](https://github.com/starkware-libs/sequencer/blob/de299c0fff33cf7239e62989143cefbec45ce5e1/crates/batcher/src/batcher.rs#L131)):*
> ```XML
>             .get_done_proposal_commitment(proposal_id)
>             .await
>             .ok_or(BatcherError::ProposalFailed)?;
> ```

Is there a better way to do this? We are removing the proposal from the batcher but not yet from the proposal manager (only later in decision reached), and also we now have two very similar methods for the proposal manager.



_Code quote:_
```XML
        // Proposal is done.
        self.proposals.remove(&proposal_id);
        let proposal_commitment = self
            .proposal_manager
            .get_done_proposal_commitment(proposal_id)
            .await
            .ok_or(BatcherError::ProposalFailed)?;
```
___
*[`crates/batcher/src/proposal_manager.rs` line 409 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-O9AejzL2sZJKwB3VKcY:-O9AejzMAmUaw8oV91su:b-qztv1e) ([raw file](https://github.com/starkware-libs/sequencer/blob/de299c0fff33cf7239e62989143cefbec45ce5e1/crates/batcher/src/proposal_manager.rs#L409)):*
> ```XML
>         let commitment =
>             ProposalCommitment { state_diff_commitment: calculate_state_diff_hash(&state_diff) };
>         Self { state_diff, commitment }
> ```

Do we need these two in the same struct if you can get one from the other?



_Code quote:_
```XML
Self { state_diff, commitment }
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1359)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-O9ABT5W2hkkcJtGOKDL:-O9BTGtu4O6m-bRr4Yhn:b-31zwv9) ([raw file](https://github.com/starkware-libs/sequencer/blob/f873b2373e7f93b5c9c70d941ee9a850083b719e/crates/batcher/src/proposal_manager.rs#L234)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

the name should reflect that this function also removes the item from done_proposals
</blockquote></details>

This comment was intended for the previous function:
get_done_proposal

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1359)* status: 5 of 8 files reviewed, 7 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-O9BWts1CWkMGszTqMf-:-O9BWts1CWkMGszTqMf0:b4p646y) ([raw file](https://github.com/starkware-libs/sequencer/blob/f873b2373e7f93b5c9c70d941ee9a850083b719e/crates/batcher/src/batcher.rs#L120)):*
> ```XML
>             .get_mut(&proposal_id)
>             .ok_or(BatcherError::ProposalNotFound { proposal_id })?
>             .tx_stream;
> ```

consider extracting into a function



_Suggestion:_
```XML
        let tx_stream = self.tx_stream(proposal_id)?;
```
___
*[`crates/batcher/src/batcher.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-O9BY-om8KW-XfhU9Dln:-O9BY-om8KW-XfhU9Dlo:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/f873b2373e7f93b5c9c70d941ee9a850083b719e/crates/batcher/src/batcher.rs#L132)):*
> ```XML
>         }
> 
>         // Proposal is done.
> ```





_Suggestion:_
```XML
// Proposal stream is done.
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1359)* status: 4 of 8 files reviewed, 7 unresolved discussions (waiting on @alonh5, @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/batcher.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-O9BY-om8KW-XfhU9Dln:-O9E-5mF5Lr6Qi3ajz-7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f873b2373e7f93b5c9c70d941ee9a850083b719e/crates/batcher/src/batcher.rs#L132)):*
> ```XML
>         }
> 
>         // Proposal is done.
> ```

Done.
___
*[`crates/batcher/src/batcher.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-O9Adfox7VMM-r5xv8Ye:-O9E-Lhs3YoYV7woN41g:b-iw1i2d) ([raw file](https://github.com/starkware-libs/sequencer/blob/de299c0fff33cf7239e62989143cefbec45ce5e1/crates/batcher/src/batcher.rs#L131)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Is there a better way to do this? We are removing the proposal from the batcher but not yet from the proposal manager (only later in decision reached), and also we now have two very similar methods for the proposal manager.
</blockquote></details>

Added todo
___
*[`crates/batcher/src/proposal_manager.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-O9ABT5W2hkkcJtGOKDL:-O9E-jyY3GzBkPbUOH0x:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f873b2373e7f93b5c9c70d941ee9a850083b719e/crates/batcher/src/proposal_manager.rs#L234)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

This comment was intended for the previous function:
get_done_proposal
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 237 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-O9A-gb-9LNN2OIhFHx0:-O9E-qiQ3fCv_X5Iu73E:b8lta40) ([raw file](https://github.com/starkware-libs/sequencer/blob/f873b2373e7f93b5c9c70d941ee9a850083b719e/crates/batcher/src/proposal_manager.rs#L237)):*
> ```XML
>         &self,
>         proposal_id: ProposalId,
>     ) -> Option<ProposalCommitment> {
> ```

There is no such type as there are multiple error types
___
*[`crates/batcher/src/proposal_manager.rs` line 384 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-O9AC2o1DDAQeC9TtNCS:-O9E-wmu4CRHUmNqV6X-:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/f873b2373e7f93b5c9c70d941ee9a850083b719e/crates/batcher/src/proposal_manager.rs#L384)):*
> ```XML
>         active_proposal: Arc<Mutex<Option<ProposalId>>>,
>         result: Result<DoneProposal, BuildProposalError>,
>         done_proposals: Arc<Mutex<HashMap<ProposalId, Result<DoneProposal, BuildProposalError>>>>,
> ```

same
___
*[`crates/batcher/src/proposal_manager.rs` line 409 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-O9AejzL2sZJKwB3VKcY:-O9E-zex-Txq6_1Z4O8D:buhp2vf) ([raw file](https://github.com/starkware-libs/sequencer/blob/de299c0fff33cf7239e62989143cefbec45ce5e1/crates/batcher/src/proposal_manager.rs#L409)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Do we need these two in the same struct if you can get one from the other?
</blockquote></details>

The StateDiffCommitment is temporary. In the future it will need to change to a different calculation that is based on the transactions (something like transaction commitment).

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-:-O9EM9z--DCpXrd6nQV2:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1359)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 237 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-O9A-gb-9LNN2OIhFHx0:-O9EgqUX7TeMDGXT4AeL:b-wwvvgd) ([raw file](https://github.com/starkware-libs/sequencer/blob/f873b2373e7f93b5c9c70d941ee9a850083b719e/crates/batcher/src/proposal_manager.rs#L237)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

There is no such type as there are multiple error types
</blockquote></details>

I think it is an important distinction between not having this item in the done_proposals at all (which is probably a bug iiuc), and getting an error for building the proposal.

but we can solve it in a separate PR so as not to delay the milestone.
___
*[`crates/batcher/src/proposal_manager.rs` line 384 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-O9AC2o1DDAQeC9TtNCS:-O9EhbXBBUE1cU3gqml_:b-sewgyr) ([raw file](https://github.com/starkware-libs/sequencer/blob/f873b2373e7f93b5c9c70d941ee9a850083b719e/crates/batcher/src/proposal_manager.rs#L384)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

same
</blockquote></details>

It is not the same comment. I am just suggesting shortening a bit the type definition, which is also not urgent for this PR.
non- blocking

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1359)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @alonh5, @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 237 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-O9A-gb-9LNN2OIhFHx0:-O9EzqmN63RrGxvAoKbZ:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/f873b2373e7f93b5c9c70d941ee9a850083b719e/crates/batcher/src/proposal_manager.rs#L237)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think it is an important distinction between not having this item in the done_proposals at all (which is probably a bug iiuc), and getting an error for building the proposal.

but we can solve it in a separate PR so as not to delay the milestone.
</blockquote></details>

done

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1359)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @alonh5, @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 251 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-O9F1JiQ5HWUv0yJydX0:-O9F1JiQ5HWUv0yJydX1:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a8da8afd418bfc66f9b263d1b3e98f9a376c4a1/crates/batcher/src/proposal_manager.rs#L251)):*
> ```XML
>             Ok(output) => Ok(output.commitment),
>             Err(e) => Err(e.clone()),
>         }
> ```





_Suggestion:_
```XML
        let output = self
            .done_proposals
            .lock()
            .await
            .get(&proposal_id)
            .ok_or(GetProposalResultError::ProposalDoesNotExist { proposal_id })?;
        Ok(output?.map(|output| output.commitment))
```

**Comment by yair-starkware** [comment]
*[`crates/batcher/src/proposal_manager.rs` line 251 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1359#-O9F1JiQ5HWUv0yJydX0:-O9F275Y4aEmYSEEt5qc:b-qvpo9k) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a8da8afd418bfc66f9b263d1b3e98f9a376c4a1/crates/batcher/src/proposal_manager.rs#L251)):*
> ```XML
>             Ok(output) => Ok(output.commitment),
>             Err(e) => Err(e.clone()),
>         }
> ```

Tried this, doesn't compile

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1359)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5, @ArniStarkware, and @dafnamatsry)

**Pull request merged**
