### PR TITLE
test(blockifier): revert storgae changes

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2913?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2913** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2913?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2913?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2889** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2889?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2910** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2910?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2913)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2913#-OEs1bdvDjyRcXcLhurh:-OEs1bdvDjyRcXcLhuri:b-650bn2) ([raw file](https://github.com/starkware-libs/sequencer/blob/6e3a0df829cccbaf2e6bfda9c893fa21fb3b150c/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L213)):*
> ```XML
>     for call in outer_call.iter() {
>         assert_eq!(call.tracked_resource, TrackedResource::SierraGas);
>     }
> ```

what is this for...?
also, just because sierra gas is tracked, doesn't mean native is running



_Code quote:_
```XML
    // Check that the tracked resource is SierraGas to make sure that Native is running.
    for call in outer_call.iter() {
        assert_eq!(call.tracked_resource, TrackedResource::SierraGas);
    }
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2913)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2913#-OEs1bdvDjyRcXcLhurh:-OEs8fDd8RkeVy1eu71a:bpyyulw) ([raw file](https://github.com/starkware-libs/sequencer/blob/6e3a0df829cccbaf2e6bfda9c893fa21fb3b150c/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L213)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what is this for...?
also, just because sierra gas is tracked, doesn't mean native is running
</blockquote></details>

Yeah that's my code. Currently Native is transparent, but it should run (given the test case) only when all calls are of SierraGas mode.

That's the best we can do right now. We should probably add some flag somewhere, for sanity. Out of scope.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2913#-:-OEsB5k8-g5euv-Cmfx8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2913)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2913#-OEsPSKQ3ZAIaSE3SKPy:-OEsPSKR4trS0vcwzzBW:b8lt9qc) (no related file):*
blocking until I'm sure the base branch is correct

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2913)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2913)* status: all files reviewed, 5 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 119 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2913#-OEtFK7Q15bEX8higmhQ:-OEtFK7Q15bEX8higmhR:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/77b510ce5b10f0878afd4203b89f6e858d4874b5/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L119)):*
> ```Cairo
>     /// The function performs the following:
>     /// 1. Calls `write_10_to_my_storage_var` to set the storage variable to 10.
>     /// 2. Calls `test_revert_helper` with `to_panic` = true`.
> ```





_Suggestion:_
```Cairo
`to_panic=true`.
```
___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 121 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2913#-OEtFNja87RGohaUkUBx:-OEtFNja87RGohaUkUBy:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/77b510ce5b10f0878afd4203b89f6e858d4874b5/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L121)):*
> ```Cairo
>     /// 2. Calls `test_revert_helper` with `to_panic` = true`.
>     ///    - `test_revert_helper` is expected to change the storage variable to 17 and then panic.
>     /// 3. Verifies that the `test_revert_helper`` changes are reverted,
> ```





_Suggestion:_
```Cairo
// 3. Verifies that the `test_revert_helper` changes are reverted,
```
___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 127 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2913#-OEtEw7e3exaomo_eGVl:-OEtEw7e3exaomo_eGVm:b-tcay50) ([raw file](https://github.com/starkware-libs/sequencer/blob/77b510ce5b10f0878afd4203b89f6e858d4874b5/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L127)):*
> ```Cairo
>         ref self: ContractState,
>         contract_address: ContractAddress,
>         class_hash: ClassHash,
> ```

Please rename other relevant functions to make it clear



_Suggestion:_
```Cairo
replacement_class_hash
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2913#-OEtE_pM1HlycskRuKXN:-OEtE_pN3RPmuGug0Db3:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/77b510ce5b10f0878afd4203b89f6e858d4874b5/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L174)):*
> ```XML
>     let mut state = test_state(chain_info, BALANCE, &[(test_contract, 1), (empty_contract, 0)]);
> 
>     // Call data of contract A
> ```





_Suggestion:_
```XML
    // Calldata of contract A.
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 179 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2913#-OEtEbHBAMfiBE-5i_dk:-OEtEbHC2HD6-0aSIB9J:boy0h14) ([raw file](https://github.com/starkware-libs/sequencer/blob/77b510ce5b10f0878afd4203b89f6e858d4874b5/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L179)):*
> ```XML
>             FeatureContract::TestContract(CairoVersion::Cairo1(RunnableCairo1::Casm))
>                 .get_instance_address(0)
>                 .into(),
> ```

Please fix other places



_Suggestion:_
```XML
            test_contract.get_instance_address(0).into(),
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2913)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 127 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2913#-OEtEw7e3exaomo_eGVl:-OEwopwm18dqn0yJjrLy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/77b510ce5b10f0878afd4203b89f6e858d4874b5/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L127)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Please rename other relevant functions to make it clear
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 179 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2913#-OEtEbHBAMfiBE-5i_dk:-OEwweyA4hku7Ho5Lh5_:b-73jvyg) ([raw file](https://github.com/starkware-libs/sequencer/blob/77b510ce5b10f0878afd4203b89f6e858d4874b5/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L179)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Please fix other places
</blockquote></details>

in different [PR](https://reviewable.io/reviews/starkware-libs/sequencer/2941)
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2913#-OEtE_pM1HlycskRuKXN:-OEwouo78owoejXL6fyW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/77b510ce5b10f0878afd4203b89f6e858d4874b5/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L174)):*
> ```XML
>     let mut state = test_state(chain_info, BALANCE, &[(test_contract, 1), (empty_contract, 0)]);
> 
>     // Call data of contract A
> ```

Done.
___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 119 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2913#-OEtFK7Q15bEX8higmhQ:-OEwnYgS3Am7Qb5IFK5_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/77b510ce5b10f0878afd4203b89f6e858d4874b5/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L119)):*
> ```Cairo
>     /// The function performs the following:
>     /// 1. Calls `write_10_to_my_storage_var` to set the storage variable to 10.
>     /// 2. Calls `test_revert_helper` with `to_panic` = true`.
> ```

Done.
___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 121 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2913#-OEtFNja87RGohaUkUBx:-OEwnbTJ5YP5H2rtE1Fh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/77b510ce5b10f0878afd4203b89f6e858d4874b5/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L121)):*
> ```Cairo
>     /// 2. Calls `test_revert_helper` with `to_panic` = true`.
>     ///    - `test_revert_helper` is expected to change the storage variable to 17 and then panic.
>     /// 3. Verifies that the `test_revert_helper`` changes are reverted,
> ```

Done.

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2913)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2913)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
