### PR TITLE
chore: remove port consts from remote_component test

### PR DESCRIPTION
**Pull request by nadin-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1045)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1045)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/mempool_infra/src/lib.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1045#-O7i1hyY2Wel4U_0o_lI:-O7i1hyY2Wel4U_0o_lJ:bm7w96g) ([raw file](https://github.com/starkware-libs/sequencer/blob/ecbda3f0619ac9a1b5800ed5f90c17dbf7d9a2e1/crates/mempool_infra/src/lib.rs#L8)):*
> ```XML
> pub mod serde_utils;
> pub mod trace_util;
> pub mod utils;
> ```

Since these are utils for testing, please:
1. rename to `test_utils`
2. add the`#[cfg(test)]` annotation -- this results in the code being compiled only in `test` mod, which is the desired behavior in this case



_Code quote:_
```XML
pub mod utils;
```
___
*[`crates/mempool_infra/tests/remote_component_client_server_test.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1045#-O7i2FzqDun3HbAKZX3k:-O7i2FzqDun3HbAKZX3l:be59ts0) ([raw file](https://github.com/starkware-libs/sequencer/blob/74ec04f82105acc0a89311836dc70c882163710b/crates/mempool_infra/tests/remote_component_client_server_test.rs#L54)):*
> ```XML
> use crate::common::{test_a_b_functionality, ComponentA, ComponentB, ValueB};
> 
> const LOCAL_IP: IpAddr = IpAddr::V6(Ipv6Addr::new(0, 0, 0, 0, 0, 0, 0, 1));
> ```

Can we also remove this const and use the `get_socket` functionality entirely?



_Code quote:_
```XML
const LOCAL_IP: IpAddr = IpAddr::V6(Ipv6Addr::new(0, 0, 0, 0, 0, 0, 0, 1));
```
___
*[`crates/mempool_infra/tests/remote_component_client_server_test.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1045#-O7i2BYK2lT4AMz1v9RF:-O7i2BYK2lT4AMz1v9RG:bb70w76) ([raw file](https://github.com/starkware-libs/sequencer/blob/74ec04f82105acc0a89311836dc70c882163710b/crates/mempool_infra/tests/remote_component_client_server_test.rs#L63)):*
> ```XML
> const FAULTY_SERVER_REQ_DESER_PORT: u16 = 10003;
> const FAULTY_SERVER_RES_DESER_PORT: u16 = 10004;
> const RETRY_REQ_PORT: u16 = 10005;
> ```

Nice



_Code quote:_
```XML
const A_PORT_TEST_SETUP: u16 = 10000;
const B_PORT_TEST_SETUP: u16 = 10001;
const A_PORT_FAULTY_CLIENT: u16 = 10010;
const B_PORT_FAULTY_CLIENT: u16 = 10011;
const UNCONNECTED_SERVER_PORT: u16 = 10002;
const FAULTY_SERVER_REQ_DESER_PORT: u16 = 10003;
const FAULTY_SERVER_RES_DESER_PORT: u16 = 10004;
const RETRY_REQ_PORT: u16 = 10005;
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1045)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/mempool_infra/src/utils.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1045#-O7i2o-mEwyOrQoiGe-o:-O7i2o-n05cfEYzVDH6t:b7yr645) ([raw file](https://github.com/starkware-libs/sequencer/blob/ecbda3f0619ac9a1b5800ed5f90c17dbf7d9a2e1/crates/mempool_infra/src/utils.rs#L5)):*
> ```XML
> use tokio::net::TcpListener;
> 
> // TODO: Merge this get_available_socket function with the one in the test_integration crate and
> ```

Please add your name (or mine, or both) to the TODO.



_Code quote:_
```XML
// TODO: Merge this get_available_socket function with the one in the test_integration crate and
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1045)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/tests/remote_component_client_server_test.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1045#-O7i2FzqDun3HbAKZX3k:-O7i4SLZ1LD9KEa9DoEU:bx9catp) ([raw file](https://github.com/starkware-libs/sequencer/blob/74ec04f82105acc0a89311836dc70c882163710b/crates/mempool_infra/tests/remote_component_client_server_test.rs#L54)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can we also remove this const and use the `get_socket` functionality entirely?
</blockquote></details>

The get_available_socket is an async function, so it cannot be used with const (in the sense that const is being parsed at compilation time). We can remove it from here and use a different local_ip in each function. Do you want me to do so?
___
*[`crates/mempool_infra/tests/remote_component_client_server_test.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1045#-O7i2BYK2lT4AMz1v9RF:-O7i5OZCBGdXOTe0ilDJ:b32vhw) ([raw file](https://github.com/starkware-libs/sequencer/blob/74ec04f82105acc0a89311836dc70c882163710b/crates/mempool_infra/tests/remote_component_client_server_test.rs#L63)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Nice
</blockquote></details>

:)

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1045)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/lib.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1045#-O7i1hyY2Wel4U_0o_lI:-O7i6Q6p8V9242COZgOk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ecbda3f0619ac9a1b5800ed5f90c17dbf7d9a2e1/crates/mempool_infra/src/lib.rs#L8)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Since these are utils for testing, please:
1. rename to `test_utils`
2. add the`#[cfg(test)]` annotation -- this results in the code being compiled only in `test` mod, which is the desired behavior in this case
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/utils.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1045#-O7i2o-mEwyOrQoiGe-o:-O7i6Ya3-fkp3TMMKK7Y:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ecbda3f0619ac9a1b5800ed5f90c17dbf7d9a2e1/crates/mempool_infra/src/utils.rs#L5)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add your name (or mine, or both) to the TODO.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1045)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/mempool_infra/src/lib.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1045#-O7i1hyY2Wel4U_0o_lI:-O7i6tUK5PyHgHu8tQnm:b-75qir6) ([raw file](https://github.com/starkware-libs/sequencer/blob/ecbda3f0619ac9a1b5800ed5f90c17dbf7d9a2e1/crates/mempool_infra/src/lib.rs#L8)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`#[cfg(test)]` should be started in `lib.rs`, see for example `crates/gateway/src/lib.rs`
___
*[`crates/mempool_infra/tests/remote_component_client_server_test.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1045#-O7i2FzqDun3HbAKZX3k:-O7i77zrEpQUKyiPc8hV:blb0u5x) ([raw file](https://github.com/starkware-libs/sequencer/blob/74ec04f82105acc0a89311836dc70c882163710b/crates/mempool_infra/tests/remote_component_client_server_test.rs#L54)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

The get_available_socket is an async function, so it cannot be used with const (in the sense that const is being parsed at compilation time). We can remove it from here and use a different local_ip in each function. Do you want me to do so?
</blockquote></details>

Yes, that was my intention: removing the `IP` const and relying on the returned ip (or more accurately, the returned socket) from the function.

**Pull request closed without merging**
