### PR TITLE
test(mempool): add fee escalation unit test

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1338)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1338)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O9-RZsxAeaNjUT5lsoW:-O9-RZsxAeaNjUT5lsoX:b-xhroy) (no related file):*
Will pass CI once #1304 is merged.

___
___
*[`crates/mempool/src/test_utils.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O9-NS6TBbSiRUBvz5O4:-O9-NS6U4KUqUGnUnvzs:b2rl799) ([raw file](https://github.com/starkware-libs/sequencer/blob/881c4b0635550d091fcbfddc6aa48e2de71a56fc/crates/mempool/src/test_utils.rs#L21)):*
> ```XML
>             let resource_bounds = ValidResourceBounds::AllResources(AllResourceBounds {
>                 l2_gas: ResourceBounds {
>                     max_price_per_unit: $max_l2_gas_price.into(),
> ```

Doesn't work without passing `max_l2_gas_price: 1_u8` (compiler sees `1` as `i32`), and I want to avoid `_u8` suffix if possible. 



_Code quote:_
```XML
$max_l2_gas_price.into()
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1338)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 612 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O9-UQUA7DqHM5XnEST2:-O9-UQUBE_dG2tMOxl3G:b-19c2id) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf86d207832081290f4a5272c83efc4b22202b13/crates/mempool/src/mempool_test.rs#L612)):*
> ```XML
> 
>     // Setup.
>     let input = add_tx_input!(tx_hash: 1, tip: 90, max_l2_gas_price: 90, tx_nonce: 1,
> ```

Had to manually format those lines in order for them to not pass `100` chars line width.
Didn't find a solution online, any suggestions on how fix this? No long research, please; a short hint/instruction will help to continue debugging on my own. :) 



_Code quote:_
```XML
add_tx_input
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1338)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 35 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O9-X9kJ0a3ndGeWbGSA:-O9-X9kJ0a3ndGeWbGSB:bddxt6q) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b89c5cfb188e066c77b45815ec8b0249e7981cb/crates/mempool/src/mempool.rs#L35)):*
> ```XML
>     // The most recent account nonces received, for all account in the pool.
>     account_nonces: AccountToNonce,
>     _fee_escalation_percentage: u8, // E.g., 10 for a 10% increase.
> ```

Used (also, properly added and documented) in #1304; minimal addition here for compilation to pass.



_Code quote:_
```XML
_fee_escalation_percentage: u8, // E.g., 10 for a 10% increase.
```

**Review by giladchase — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1338)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 612 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O9-UQUA7DqHM5XnEST2:-O93ZdKnBiwuWB-Asq6l:b-aju3dg) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf86d207832081290f4a5272c83efc4b22202b13/crates/mempool/src/mempool_test.rs#L612)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Had to manually format those lines in order for them to not pass `100` chars line width.
Didn't find a solution online, any suggestions on how fix this? No long research, please; a short hint/instruction will help to continue debugging on my own. :)
</blockquote></details>

rustfmt doesn't handle macros very well :(
Especially ones with custom syntax.

Happy you managed to get this to work manually, sometimes we need to resort to adding `#[rustfmt::skip]`
___
*[`crates/mempool/src/mempool_test.rs` line 605 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O93aenM7iRq_JEiupqE:-O93aenM7iRq_JEiupqF:bhc526i) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b89c5cfb188e066c77b45815ec8b0249e7981cb/crates/mempool/src/mempool_test.rs#L605)):*
> ```XML
> 
> #[rstest]
> fn test_fee_escalation() {
> ```

Do we want to split into happy-test and depressed-test? This is a bit longish 



_Code quote:_
```XML
fn test_fee_escalation() {
```
___
*[`crates/mempool/src/mempool_test.rs` line 612 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O93a-Gz8lzIh7TxIRqY:-O93a-Gz8lzIh7TxIRqZ:b-cl1wg9) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b89c5cfb188e066c77b45815ec8b0249e7981cb/crates/mempool/src/mempool_test.rs#L612)):*
> ```XML
>         .build_into_mempool();
> 
>     // Valid replacement.
> ```

Should we also check other happy cases? 
The example you used checks ~11% increase, we might want to also test the boundary (exactly 10% increase), and maybe one more very large increase, specifically anything >= 200% increase to make sure we aren't screwing up percentage calc.



_Code quote:_
```XML
    // Valid replacement.
```
___
*[`crates/mempool/src/test_utils.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O9-NS6TBbSiRUBvz5O4:-O93e6ruAIBXHZyVFgNp:b6yks9l) ([raw file](https://github.com/starkware-libs/sequencer/blob/881c4b0635550d091fcbfddc6aa48e2de71a56fc/crates/mempool/src/test_utils.rs#L21)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Doesn't work without passing `max_l2_gas_price: 1_u8` (compiler sees `1` as `i32`), and I want to avoid `_u8` suffix if possible.
</blockquote></details>

Ya, i32 is the default inferred value, barring extra info.
How had this worked thus far?

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1338)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 612 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O9-UQUA7DqHM5XnEST2:-O93i_gyCX8Ir4ju3lie:b-ucfknh) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf86d207832081290f4a5272c83efc4b22202b13/crates/mempool/src/mempool_test.rs#L612)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

rustfmt doesn't handle macros very well :(
Especially ones with custom syntax.

Happy you managed to get this to work manually, sometimes we need to resort to adding `#[rustfmt::skip]`
</blockquote></details>

Thanks!
___
*[`crates/mempool/src/mempool_test.rs` line 605 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O93aenM7iRq_JEiupqE:-O93iIZq2fg5rf3-52rZ:b3zx8qk) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b89c5cfb188e066c77b45815ec8b0249e7981cb/crates/mempool/src/mempool_test.rs#L605)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Do we want to split into happy-test and depressed-test? This is a bit longish
</blockquote></details>

I think it's not too long, but given other happy flows you suggested, I'll split it.
___
*[`crates/mempool/src/test_utils.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O9-NS6TBbSiRUBvz5O4:-O93ihSV7qbXEwNfPEFF:b8d6a37) ([raw file](https://github.com/starkware-libs/sequencer/blob/881c4b0635550d091fcbfddc6aa48e2de71a56fc/crates/mempool/src/test_utils.rs#L21)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Ya, i32 is the default inferred value, barring extra info.
How had this worked thus far?
</blockquote></details>

It hasn't, first use. :)

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-:-O941h5L6Z7Ck97iUfAV:bnfp4nl)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1338)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 605 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O940XDd9Q4ZhtokV1Rk:-O940XDd9Q4ZhtokV1Rl:b-ppd23q) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b89c5cfb188e066c77b45815ec8b0249e7981cb/crates/mempool/src/mempool_test.rs#L605)):*
> ```XML
> 
> #[rstest]
> fn test_fee_escalation() {
> ```

Can a transaction in the queue be replaced? If so, should we add a test for it?
___
*[`crates/mempool/src/mempool_test.rs` line 618 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O941QQ37EkCXILpYeyr:-O941QQ37EkCXILpYeys:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b89c5cfb188e066c77b45815ec8b0249e7981cb/crates/mempool/src/mempool_test.rs#L618)):*
> ```XML
>         tx_nonce: 1, sender_address: "0x0");
> 
>     // Test and assert.
> ```





_Suggestion:_
```XML
// Test.
```
___
*[`crates/mempool/src/mempool_test.rs` line 621 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O941BGa2OL7vzia7OEI:-O941BGa2OL7vzia7OEJ:b-60iqhz) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b89c5cfb188e066c77b45815ec8b0249e7981cb/crates/mempool/src/mempool_test.rs#L621)):*
> ```XML
>     add_tx(&mut mempool, &valid_replacement_input);
> 
>     // Verify transaction was replaced.
> ```

OR above `add_tx` - `// Test and assert: verify transaction was replaced.`



_Suggestion:_
```XML
// Assert: Verify transaction was replaced.
```
___
*[`crates/mempool/src/mempool_test.rs` line 636 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O941bHf9WhYdw8sDtxw:-O941bHg1TG3qZP1jy4b:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b89c5cfb188e066c77b45815ec8b0249e7981cb/crates/mempool/src/mempool_test.rs#L636)):*
> ```XML
>         tx_nonce: 1, sender_address: "0x0");
> 
>     // Test and assert.
> ```

same



_Code quote:_
```XML
// Test and assert.
```

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1338)* status: all files reviewed, 7 unresolved discussions (waiting on @elintul and @MohammadNassar1)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1338)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 605 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O940XDd9Q4ZhtokV1Rk:-O94716n9vo4yRf1CNmQ:b-z24mdc) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b89c5cfb188e066c77b45815ec8b0249e7981cb/crates/mempool/src/mempool_test.rs#L605)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Can a transaction in the queue be replaced? If so, should we add a test for it?
</blockquote></details>

No, it fails in validation.
___
*[`crates/mempool/src/mempool_test.rs` line 618 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O941QQ37EkCXILpYeyr:-O9476k08yEnXWPRa-mL:b-ob3j9o) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b89c5cfb188e066c77b45815ec8b0249e7981cb/crates/mempool/src/mempool_test.rs#L618)):*
> ```XML
>         tx_nonce: 1, sender_address: "0x0");
> 
>     // Test and assert.
> ```

Nope, it also asserts.
___
*[`crates/mempool/src/mempool_test.rs` line 621 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O941BGa2OL7vzia7OEI:-O947A2E5ucds05N89F3:b-dtolz0) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b89c5cfb188e066c77b45815ec8b0249e7981cb/crates/mempool/src/mempool_test.rs#L621)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

OR above `add_tx` - `// Test and assert: verify transaction was replaced.`
</blockquote></details>

I prefer to leave it as-is.

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-:-O94C1DA5h8sWiGetmtk:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @MohammadNassar1)

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1338)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O94Cxsl-69lvxTGq71x:-O94Cxsl-69lvxTGq71y:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b89c5cfb188e066c77b45815ec8b0249e7981cb/crates/mempool/src/mempool_test.rs#L68)):*
> ```XML
>             account_nonces: Default::default(),
>             _fee_escalation_percentage: fee_escalation_percentage,
>         }
> ```





_Suggestion:_
```XML
            _fee_escalation_percentage: fee_escalation_percentage,
            // TODO: Add implementation when needed.
            mempool_state: Default::default(),
            account_nonces: Default::default(),
        }
```
___
*[`crates/mempool/src/mempool_test.rs` line 606 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O94DqXTBVvgtIjBqiYc:-O94DqXTBVvgtIjBqiYd:b3fkpho) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b89c5cfb188e066c77b45815ec8b0249e7981cb/crates/mempool/src/mempool_test.rs#L606)):*
> ```XML
> #[rstest]
> fn test_fee_escalation() {
>     let tx = tx!(tx_hash: 1, tip: 90, max_l2_gas_price: 90, tx_nonce: 1, sender_address: "0x0");
> ```

I’d like to test for equality as well. 
The tip or L2 gas price should be equal to `90 * 1.1 = 99`.



_Code quote:_
```XML
 let tx = tx!(tx_hash: 1, tip: 90, max_l2_gas_price: 90, tx_nonce: 1, sender_address: "0x0");
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1338)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 605 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O93aenM7iRq_JEiupqE:-O94L0RhAc_QAZFGLoNe:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b89c5cfb188e066c77b45815ec8b0249e7981cb/crates/mempool/src/mempool_test.rs#L605)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think it's not too long, but given other happy flows you suggested, I'll split it.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 606 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O94DqXTBVvgtIjBqiYc:-O94L2MsAcJ7prX6qC2b:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b89c5cfb188e066c77b45815ec8b0249e7981cb/crates/mempool/src/mempool_test.rs#L606)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I’d like to test for equality as well. 
The tip or L2 gas price should be equal to `90 * 1.1 = 99`.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 612 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O93a-Gz8lzIh7TxIRqY:-O94L743127i7xriOp1B:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b89c5cfb188e066c77b45815ec8b0249e7981cb/crates/mempool/src/mempool_test.rs#L612)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Should we also check other happy cases? 
The example you used checks ~11% increase, we might want to also test the boundary (exactly 10% increase), and maybe one more very large increase, specifically anything >= 200% increase to make sure we aren't screwing up percentage calc.
</blockquote></details>

Done.

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 3 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1338)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 602 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O94M0TkAQkKUEdMknHw:-O94M0TkAQkKUEdMknHx:b-iworzm) ([raw file](https://github.com/starkware-libs/sequencer/blob/55a20db4e6d95315bb6604f0b603bcb6f9bb8d95/crates/mempool/src/mempool_test.rs#L602)):*
> ```XML
>         99,  // Exactly increase percentage.
>         100, // More than increase percentage,
>         180, // More than 100% increase.
> ```

Out of curiosity, why is it an interesting case?



_Code quote:_
```XML
180, // More than 100% increase.
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1338)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 602 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-O94M0TkAQkKUEdMknHw:-O94MXBe4UZsCg_xC7km:bascgfq) ([raw file](https://github.com/starkware-libs/sequencer/blob/55a20db4e6d95315bb6604f0b603bcb6f9bb8d95/crates/mempool/src/mempool_test.rs#L602)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Out of curiosity, why is it an interesting case?
</blockquote></details>

Gilad suggested it, wanted to make sure we don't screw up percentage calculations.

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1338#-:-O94N6ts19Ht_UDzg_yA:bnfp4nl)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 1 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1338)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @elintul)

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1338)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
