### PR TITLE
chore: implement decode_and_decompress + test

### PR DESCRIPTION
**Pull request by noamsp-starkware**

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1611)* status: all files reviewed, 2 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/papyrus_common/src/compression_utils.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1611#-OAMzhWLE3m1KJDwYCRs:-OAMzhWLE3m1KJDwYCRt:b-6mebyc) ([raw file](https://github.com/starkware-libs/sequencer/blob/18113af5e2befb623b51fc0f0375c3f82dec783c/crates/papyrus_common/src/compression_utils.rs#L18)):*
> ```XML
> 
> // Compress the value using gzip with the default compression level and encode it in base64.
> pub fn compress_and_encode(value: serde_json::Value) -> Result<String, CompressionUtilsError> {
> ```

You can keep this std::io::Error
___
*[`crates/papyrus_protobuf/src/converters/mod.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1611#-OAN-XzF-U6zuWZmhRfm:-OAN-XzF-U6zuWZmhRfn:b-7799u5) ([raw file](https://github.com/starkware-libs/sequencer/blob/18113af5e2befb623b51fc0f0375c3f82dec783c/crates/papyrus_protobuf/src/converters/mod.rs#L27)):*
> ```XML
>     #[error(transparent)]
>     DecodeError(#[from] DecodeError),
>     // The original error does not derive ParitalEq and Clone Traits
> ```

// We put the string of the error instead of the original error because the original error does not ...

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1611)* status: all files reviewed, 3 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/papyrus_storage/src/db/serialization.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1611#-OAN4Ik42AWjX5kChFsU:-OAN4Ik5AZrqYspxhdfF:bxs182e) ([raw file](https://github.com/starkware-libs/sequencer/blob/18113af5e2befb623b51fc0f0375c3f82dec783c/crates/papyrus_storage/src/db/serialization.rs#L168)):*
> ```XML
>     CompressionUtilsError(#[from] papyrus_common::compression_utils::CompressionUtilsError),
>     #[error(transparent)]
>     Io(#[from] std::io::Error),
> ```

Can you erase this variant now?

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1611)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_common/src/compression_utils.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1611#-OAN4AZsA_QWlCpVcruD:-OANIVqj50FZN_D_cjJ7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/18113af5e2befb623b51fc0f0375c3f82dec783c/crates/papyrus_common/src/compression_utils.rs#L8)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to CompressionError
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/mod.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1611#-OAN-XzF-U6zuWZmhRfm:-OANJmaV9l0RRrz_sZeK:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/18113af5e2befb623b51fc0f0375c3f82dec783c/crates/papyrus_protobuf/src/converters/mod.rs#L27)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

// We put the string of the error instead of the original error because the original error does not ...
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/db/serialization.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1611#-OAN4Ik42AWjX5kChFsU:-OANK-UB2lWSZy_gczF7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/18113af5e2befb623b51fc0f0375c3f82dec783c/crates/papyrus_storage/src/db/serialization.rs#L168)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Can you erase this variant now?
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1611#-:-OANWFfL8vqcLbipamsi:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)

**Pull request merged**
