### PR TITLE
docs: running papyrus using p2p sync

### PR DESCRIPTION
**Pull request by AlonLStarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/339)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/339)* status: all files reviewed, 5 unresolved discussions (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`docs/papyrus/README.adoc` line 230 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/339#-O3l2S9V3wgOP1yp2gZi:-O3l2S9V3wgOP1yp2gZj:bcc2nmp) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e891f824e548e780b533c21dc36be0a56dd45e1/docs/papyrus/README.adoc#L230)):*
> ```AsciiDoc
> === Running Papyrus using p2p sync
> 
> .Here are three examples of running p2p nodes with various configurations:
> ```

Try to explain, not just give the examples

Start with listing the various flags (Feel free to improve my english and add titles as you see fit):
--network.#is_none false will turn on the p2p networking component for this node and allow it to serve incoming requests

The flags `--sync.#is_none false` and `--p2p_sync.#is_none true` will change the syncing source of the node from central to p2p, meaning that the node will make sync requests to other nodes it is connected to

The flag --bootstrap_peer_multiaddr is used to let the node know of some other node that exists in the network. Our node will discover the rest of the peers in the network from that node
It is usually custom to have a single or few bootstrap nodes in the network that their address is predetermined and then new nodes join the network through them
You should turn it off if you're the bootstrap node by adding `--network.bootstrap_peer_multiaddr.#is_none true`

And then put the examples
___
*[`docs/papyrus/README.adoc` line 231 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/339#-O3l4_hl-LiZzLRcIMl-:-O3l4_hl-LiZzLRcIMl0:b-idufd1) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e891f824e548e780b533c21dc36be0a56dd45e1/docs/papyrus/README.adoc#L231)):*
> ```AsciiDoc
> 
> .Here are three examples of running p2p nodes with various configurations:
> . No sync - can be used by other nodes for discovery but not for syncing.
> ```

No sync -> Bootstrap node without sync
___
*[`docs/papyrus/README.adoc` line 233 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/339#-O3l4lbh2nzUJu6ulkOo:-O3l4lbh2nzUJu6ulkOp:bbj9v0k) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e891f824e548e780b533c21dc36be0a56dd45e1/docs/papyrus/README.adoc#L233)):*
> ```AsciiDoc
> . No sync - can be used by other nodes for discovery but not for syncing.
> . Syncing from central gateway, and connected to bootstrap peer.
> . Syncing using p2p and connected to bootstrap peer.
> ```

Number these, and then write at the end of 3: "(it will discover 2 and then sync from it)"
___
*[`docs/papyrus/README.adoc` line 267 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/339#-O3l1O0j6egpACd3BYfW:-O3l1O0j6egpACd3BYfX:b-fcrz8c) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e891f824e548e780b533c21dc36be0a56dd45e1/docs/papyrus/README.adoc#L267)):*
> ```AsciiDoc
> ====
> .In case you are running more than one node on the same machine, notice you will have to specify the following fields (to avoid collisions):
> * tcp_port
> ```

network.tcp_port
___
*[`docs/papyrus/README.adoc` line 270 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/339#-O4-vGvlE4yiuQcZunnt:-O4-vGvlE4yiuQcZunnu:bj1k0hk) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e891f824e548e780b533c21dc36be0a56dd45e1/docs/papyrus/README.adoc#L270)):*
> ```AsciiDoc
> * monitoring_gateway.server_address
> * rpc.server_address
> * storage.db_config.path_prefix (if there are multiple syncing nodes they require different storage directories)
> ```

IMO no need for the explanation in parentheses)

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/339)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @eitanm-starkware and @ShahakShama)

___
*[`docs/papyrus/README.adoc` line 230 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/339#-O3l2S9V3wgOP1yp2gZi:-O4_0pjs-T9o13M5W9-F:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e891f824e548e780b533c21dc36be0a56dd45e1/docs/papyrus/README.adoc#L230)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Try to explain, not just give the examples

Start with listing the various flags (Feel free to improve my english and add titles as you see fit):
--network.#is_none false will turn on the p2p networking component for this node and allow it to serve incoming requests

The flags `--sync.#is_none false` and `--p2p_sync.#is_none true` will change the syncing source of the node from central to p2p, meaning that the node will make sync requests to other nodes it is connected to

The flag --bootstrap_peer_multiaddr is used to let the node know of some other node that exists in the network. Our node will discover the rest of the peers in the network from that node
It is usually custom to have a single or few bootstrap nodes in the network that their address is predetermined and then new nodes join the network through them
You should turn it off if you're the bootstrap node by adding `--network.bootstrap_peer_multiaddr.#is_none true`

And then put the examples
</blockquote></details>

Done.
___
*[`docs/papyrus/README.adoc` line 231 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/339#-O3l4_hl-LiZzLRcIMl-:-O4_0VBe0b6b3DrINpU_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e891f824e548e780b533c21dc36be0a56dd45e1/docs/papyrus/README.adoc#L231)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No sync -> Bootstrap node without sync
</blockquote></details>

Done.
___
*[`docs/papyrus/README.adoc` line 233 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/339#-O3l4lbh2nzUJu6ulkOo:-O4_0VgG1qYxuXyk42E4:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e891f824e548e780b533c21dc36be0a56dd45e1/docs/papyrus/README.adoc#L233)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Number these, and then write at the end of 3: "(it will discover 2 and then sync from it)"
</blockquote></details>

Done.
___
*[`docs/papyrus/README.adoc` line 267 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/339#-O3l1O0j6egpACd3BYfW:-O4_0W5M3uTXtXqsvKcI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e891f824e548e780b533c21dc36be0a56dd45e1/docs/papyrus/README.adoc#L267)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

network.tcp_port
</blockquote></details>

Done.
___
*[`docs/papyrus/README.adoc` line 270 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/339#-O4-vGvlE4yiuQcZunnt:-O4_0Wd58NRHV3YQB4r-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e891f824e548e780b533c21dc36be0a56dd45e1/docs/papyrus/README.adoc#L270)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

IMO no need for the explanation in parentheses)
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/339)* status: all files reviewed, 3 unresolved discussions (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`docs/papyrus/README.adoc` line 235 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/339#-O4k6Rn-A7I4QzLlX1Oy:-O4k6Rn-A7I4QzLlX1Oz:b2yl5za) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e07a57ca42c31bc34d316e6ca00f8af7aceb111/docs/papyrus/README.adoc#L235)):*
> ```AsciiDoc
> . `--p2p_sync.#is_none false` will turn on p2p syncing, meaning the node will make sync requests to other connected nodes.
> . `--bootstrap_peer_multiaddr` is used to inform the node of some other node that exists in the network. The new node will discover the rest of the peers in the network from that node.
> * it is usually custom to have a single or few bootstrap nodes in the network with predetermined addresses and have new nodes join the networking using them.
> ```

networking -> network
___
*[`docs/papyrus/README.adoc` line 235 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/339#-O4k6Zt53doY7algjQm_:-O4k6Zt53doY7algjQma:b-xzjpxs) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e07a57ca42c31bc34d316e6ca00f8af7aceb111/docs/papyrus/README.adoc#L235)):*
> ```AsciiDoc
> . `--p2p_sync.#is_none false` will turn on p2p syncing, meaning the node will make sync requests to other connected nodes.
> . `--bootstrap_peer_multiaddr` is used to inform the node of some other node that exists in the network. The new node will discover the rest of the peers in the network from that node.
> * it is usually custom to have a single or few bootstrap nodes in the network with predetermined addresses and have new nodes join the networking using them.
> ```

If you're the bootstrap node, you should not set a value to this flag
___
*[`docs/papyrus/README.adoc` line 235 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/339#-O4k6diw4fotWEIr8gJt:-O4k6diw4fotWEIr8gJu:b9mcuy1) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e07a57ca42c31bc34d316e6ca00f8af7aceb111/docs/papyrus/README.adoc#L235)):*
> ```AsciiDoc
> . `--p2p_sync.#is_none false` will turn on p2p syncing, meaning the node will make sync requests to other connected nodes.
> . `--bootstrap_peer_multiaddr` is used to inform the node of some other node that exists in the network. The new node will discover the rest of the peers in the network from that node.
> * it is usually custom to have a single or few bootstrap nodes in the network with predetermined addresses and have new nodes join the networking using them.
> ```

Note that you need to turn the flag on by adding `network.bootstrap_peer_multiaddr.#is_none false`
Just giving a value to the flag **does not** turn it on

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/339#-:-O4om-xU-mhIeRi7KBTQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Pull request merged**
