### PR TITLE
chore(starknet_sequencer_node): set monitoring as active component

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #2605
- #2601
- #2600
- #2599
- #2578
- #2577
- #2576 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by nadin-Starkware — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2576)* status: 5 of 6 files reviewed, all discussions resolved

**Review by nadin-Starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2576)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by nadin-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2576)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sequencer_node/src/config/component_config.rs` line 33 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2576#-ODjlxNyDYZzX1GUWdvg:-ODjlxNz8kvyI6Q04Wlo:bv3o85l) ([raw file](https://github.com/starkware-libs/sequencer/blob/8342984ad16287d494160519261cd22a3d742ec8/crates/starknet_sequencer_node/src/config/component_config.rs#L33)):*
> ```XML
> 
>     // Reactive component configs.
>     pub monitoring_endpoint: ActiveComponentExecutionConfig,
> ```

What do you think about using two fields here: `active_components`, which would be a struct containing all active components, and `reactive_components`, another struct? This would be similar to the `servers` struct, which has three fields: `local`, `remote`, and `wrapper`.



_Code quote:_
```XML
    // Reactive component configs.
    #[validate]
    pub batcher: ReactiveComponentExecutionConfig,
    #[validate]
    pub consensus_manager: ReactiveComponentExecutionConfig,
    #[validate]
    pub gateway: ReactiveComponentExecutionConfig,
    #[validate]
    pub http_server: ReactiveComponentExecutionConfig,
    #[validate]
    pub mempool: ReactiveComponentExecutionConfig,
    #[validate]
    pub mempool_p2p: ReactiveComponentExecutionConfig,
    #[validate]
    pub state_sync: ReactiveComponentExecutionConfig,

    // Reactive component configs.
    pub monitoring_endpoint: ActiveComponentExecutionConfig,
```

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#2600](https://github.com/starkware-libs/sequencer/pull/2600)

**Pull request closed without merging**
