### PR TITLE
feat(mempool): implement transaction tracker to transaction pool

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/480)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/480)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 821 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/480#-O4d6cTk3wSqLYX_ICIp:-O4d6cTk3wSqLYX_ICIq:b-yg2f5d) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc6e1ffcceeddd9809ba9f3cfde72b63d677766b/crates/mempool/src/mempool_test.rs#L821)):*
> ```XML
>     add_tx(&mut mempool, &tx_1);
>     add_tx(&mut mempool, &tx_2);
>     assert_eq!(mempool._tx_pool()._txs_tracker().txs_counter, 2);
> ```

Not elegant. :(
Perhaps the pool should expose an API of `n_txs`? Please check what's the ergonomic way to test internal data.



_Code quote:_
```XML
mempool._tx_pool()._txs_tracker().txs_counter
```
___
*[`crates/mempool/src/transaction_pool.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/480#-O4d69mN8D5rTbd-PW7w:-O4d69mN8D5rTbd-PW7x:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc6e1ffcceeddd9809ba9f3cfde72b63d677766b/crates/mempool/src/transaction_pool.rs#L23)):*
> ```XML
>     // Transactions organized by account address, sorted by ascending nonce values.
>     txs_by_account: AccountTransactionIndex,
>     // Tracks the number of transactions in the pool.
> ```





_Suggestion:_
```XML
capacity of
```
___
*[`crates/mempool/src/transaction_pool.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/480#-O4d6IPp6gwnqrkR58C5:-O4d6IPp6gwnqrkR58C6:bm3chh5) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc6e1ffcceeddd9809ba9f3cfde72b63d677766b/crates/mempool/src/transaction_pool.rs#L81)):*
> ```XML
>                 );
>             });
>             self.txs_tracker.decrement_tx();
> ```

Called inside `remove`, right?



_Code quote:_
```XML
self.txs_tracker.decrement_tx();
```
___
*[`crates/mempool/src/transaction_pool.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/480#-O4d6MHWChw9YYk4IvZ9:-O4d6MHWChw9YYk4IvZA:bmtoqr3) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc6e1ffcceeddd9809ba9f3cfde72b63d677766b/crates/mempool/src/transaction_pool.rs#L114)):*
> ```XML
>     pub fn _txs_tracker(&self) -> &TransactionTracker {
>         &self.txs_tracker
>     }
> ```

Is this the best practice to test this?



_Code quote:_
```XML
    pub fn _txs_tracker(&self) -> &TransactionTracker {
        &self.txs_tracker
    }
```
___
*[`crates/mempool/src/transaction_pool.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/480#-O4d5Qbv4uif11TZixov:-O4d5Qbv4uif11TZixow:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc6e1ffcceeddd9809ba9f3cfde72b63d677766b/crates/mempool/src/transaction_pool.rs#L166)):*
> ```XML
> 
> #[derive(Debug, Default, Eq, PartialEq)]
> pub struct TransactionTracker {
> ```





_Suggestion:_
```XML
PoolCapacity
```
___
*[`crates/mempool/src/transaction_pool.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/480#-O4d5VKA16XzXmCZRXEx:-O4d5VKA16XzXmCZRXEy:b22qz5p) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc6e1ffcceeddd9809ba9f3cfde72b63d677766b/crates/mempool/src/transaction_pool.rs#L171)):*
> ```XML
> }
> 
> impl TransactionTracker {
> ```

This is not the right API here, you will also be counting the size, and it won't be a +-1 operation. Also, you'll need the transaction for that.
How about: `[add/remove](&mut self, tx: &Transaction)`?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/480)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 821 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/480#-O4d6cTk3wSqLYX_ICIp:-O4eMC887VeqSoLuvD1M:bncptnv) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc6e1ffcceeddd9809ba9f3cfde72b63d677766b/crates/mempool/src/mempool_test.rs#L821)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not elegant. :(
Perhaps the pool should expose an API of `n_txs`? Please check what's the ergonomic way to test internal data.
</blockquote></details>

WDYM by API of n_txs? 
___
*[`crates/mempool/src/transaction_pool.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/480#-O4d6IPp6gwnqrkR58C5:-O4eLO8r9sZu2E78TFr1:b-j29tk2) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc6e1ffcceeddd9809ba9f3cfde72b63d677766b/crates/mempool/src/transaction_pool.rs#L81)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Called inside `remove`, right?
</blockquote></details>

Yes. We’re not calling the `TransactionPool`'s `remove` function here, just using `tx_pool.remove`, which is the HashMap’s `remove` function. (It does feel a bit odd—maybe we should think about that)
___
*[`crates/mempool/src/transaction_pool.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/480#-O4d6MHWChw9YYk4IvZ9:-O4eLHfR7vqjtv_P-bGy:bjh5bbb) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc6e1ffcceeddd9809ba9f3cfde72b63d677766b/crates/mempool/src/transaction_pool.rs#L114)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this the best practice to test this?
</blockquote></details>

tried returning the value itself. wdyt?
___
*[`crates/mempool/src/transaction_pool.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/480#-O4d5VKA16XzXmCZRXEx:-O4eKjph3yIHm__JDTou:b8e1f1h) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc6e1ffcceeddd9809ba9f3cfde72b63d677766b/crates/mempool/src/transaction_pool.rs#L171)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This is not the right API here, you will also be counting the size, and it won't be a +-1 operation. Also, you'll need the transaction for that.
How about: `[add/remove](&mut self, tx: &Transaction)`?
</blockquote></details>

I’ve changed the names, but do I need to add `tx` to the API at this point? maybe it would be better to add it when it’s used?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/480)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/480#-O4eNQzcDzgPRkqba6-C:-O4eNQzcDzgPRkqba6-D:b-qqwtki) (no related file):*
I made a git mistake. please continue review here #512 

___

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/480)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/480#-O4eUO1wCQ9HG74aaMta:-O4eUO1wCQ9HG74aaMtb:b-5os2vx) (no related file):*
Made a git mistake. Continue review in #513

___

**Pull request closed without merging**
