### PR TITLE
feat(starknet_state_sync): implement sync state reader get block info

### PR DESCRIPTION
**Pull request by noamsp-starkware**

### CODE REVIEW

**Comment by noamsp-starkware** [comment]
* **#2887** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2887?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2887?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2887)* status: all files reviewed, 3 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/starknet_state_sync/src/lib.rs` line 200 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2887#-OEoBrkL3HHM27S_FXNE:-OEoBrkL3HHM27S_FXNF:bhu3q83) ([raw file](https://github.com/starkware-libs/sequencer/blob/d52f5b8fd11739d35834332257430aa503c3a0d0/crates/starknet_state_sync/src/lib.rs#L200)):*
> ```XML
>     }
> 
>     fn get_block_header(&self, block_number: BlockNumber) -> StateSyncResult<BlockHeader> {
> ```

Change this to get_block_info and have it return the block info extracted from the header
___
*[`crates/starknet_state_sync/src/lib.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2887#-OEoC3RZCUKIYfbVdY7M:-OEoC3RZCUKIYfbVdY7N:bka77x8) ([raw file](https://github.com/starkware-libs/sequencer/blob/d52f5b8fd11739d35834332257430aa503c3a0d0/crates/starknet_state_sync/src/lib.rs#L203)):*
> ```XML
>         let txn = self.storage_reader.begin_ro_txn()?;
>         let latest_block_number = txn.get_header_marker()?.prev();
>         if latest_block_number.is_none_or(|latest_block_number| latest_block_number < block_number)
> ```

No need for this check. You can just straight up call get_block_header and it will return None if latest_block_number < block_number
___
*[`crates/starknet_gateway/src/sync_state_reader.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2887#-OEoC_lIDwe4b7dgp111:-OEoC_lIDwe4b7dgp112:bxy8p5e) ([raw file](https://github.com/starkware-libs/sequencer/blob/d52f5b8fd11739d35834332257430aa503c3a0d0/crates/starknet_gateway/src/sync_state_reader.rs#L42)):*
> ```XML
>             sequencer_address: block_header_without_hash.sequencer.0,
>             block_timestamp: block_header_without_hash.timestamp,
>             gas_prices: validated_gas_prices(
> ```

What's validated_gas_prices and parse_gas_prices? Could you point me to the code where you've seen this used?

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2887)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/starknet_gateway/src/sync_state_reader.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2887#-OEoC_lIDwe4b7dgp111:-OEoj-CbE-_KqqeQur2s:b41pi7e) ([raw file](https://github.com/starkware-libs/sequencer/blob/d52f5b8fd11739d35834332257430aa503c3a0d0/crates/starknet_gateway/src/sync_state_reader.rs#L42)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What's validated_gas_prices and parse_gas_prices? Could you point me to the code where you've seen this used?
</blockquote></details>

sequencer/crates/starknet_gateway/src/rpc_objects.rs



_Code snippet:_
```XML
impl TryInto<BlockInfo> for BlockHeader {
    type Error = RPCStateReaderError;
    fn try_into(self) -> Result<BlockInfo, Self::Error> {
        Ok(BlockInfo {
            block_number: self.block_number,
            sequencer_address: self.sequencer_address,
            block_timestamp: self.timestamp,
            gas_prices: validated_gas_prices(
                parse_gas_price(self.l1_gas_price.price_in_wei)?,
                parse_gas_price(self.l1_gas_price.price_in_fri)?,
                parse_gas_price(self.l1_data_gas_price.price_in_wei)?,
                parse_gas_price(self.l1_data_gas_price.price_in_fri)?,
                parse_gas_price(self.l2_gas_price.price_in_wei)?,
                parse_gas_price(self.l2_gas_price.price_in_fri)?,
            ),
            use_kzg_da: matches!(self.l1_da_mode, L1DataAvailabilityMode::Blob),
        })
    }
}
```
___
*[`crates/starknet_state_sync/src/lib.rs` line 200 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2887#-OEoBrkL3HHM27S_FXNE:-OEorvE_CZhZCOvACieY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d52f5b8fd11739d35834332257430aa503c3a0d0/crates/starknet_state_sync/src/lib.rs#L200)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change this to get_block_info and have it return the block info extracted from the header
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync/src/lib.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2887#-OEoC3RZCUKIYfbVdY7M:-OEoo2Dk3O5EmdujRwKC:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d52f5b8fd11739d35834332257430aa503c3a0d0/crates/starknet_state_sync/src/lib.rs#L203)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No need for this check. You can just straight up call get_block_header and it will return None if latest_block_number < block_number
</blockquote></details>

Done.

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2887)* status: all files reviewed, 5 unresolved discussions (waiting on @noamsp-starkware and @ShahakShama)

___
*[`crates/starknet_gateway/src/sync_state_reader.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2887#-OEt6X297Ffs_1eMgwSf:-OEt6X297Ffs_1eMgwSg:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/f339fbb89ad7a7b27ef283b62cd984c5c77d8825/crates/starknet_gateway/src/sync_state_reader.rs#L37)):*
> ```XML
>             Some(block_info) => block_info,
>             None => return Err(StateError::StateReadError("Block info not found".to_string())),
>         };
> ```





_Suggestion:_
```XML
        maybe_block_info.ok_or_else(...)
        let block_info = match maybe_block_info {
            Some(block_info) => block_info,
            None => return Err(StateError::StateReadError("Block info not found".to_string())),
        };
```
___
*[`crates/starknet_state_sync/src/lib.rs` line 206 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2887#-OEt71oc8y95haaKLhPb:-OEt71oc8y95haaKLhPc:b-1xtzrp) ([raw file](https://github.com/starkware-libs/sequencer/blob/f339fbb89ad7a7b27ef283b62cd984c5c77d8825/crates/starknet_state_sync/src/lib.rs#L206)):*
> ```XML
>         let txn = self.storage_reader.begin_ro_txn()?;
> 
>         if let Some(block_header) = txn.get_block_header(block_number)? {
> ```

reduce nesting 



_Suggestion:_
```XML
        let Some(block_header) = txn.get_block_header(block_number)? else { return None
        if let Some(block_header) = txn.get_block_header(block_number)? {
```

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2887)* status: all files reviewed, 6 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/starknet_state_sync/src/lib.rs` line 203 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2887#-OEtIgvXDN9lOZ1ZlKw1:-OEtIgvXDN9lOZ1ZlKw2:b-6fjbn4) ([raw file](https://github.com/starkware-libs/sequencer/blob/f339fbb89ad7a7b27ef283b62cd984c5c77d8825/crates/starknet_state_sync/src/lib.rs#L203)):*
> ```XML
>     }
> 
>     fn get_block_info(&self, block_number: BlockNumber) -> StateSyncResult<Option<BlockInfo>> {
> ```

Now that Eitan added block info to get_block, we can erase this method and use get_block in SyncStateReader

**Comment by noamsp-starkware** [comment]
Closing this due to big changes that require a different approach. opened the respective fixed PR at https://github.com/starkware-libs/sequencer/pull/2942

**Pull request closed without merging**
