### PR TITLE
feat(blockifier): add non-recoverable error handling for native syscall handler

### PR DESCRIPTION
**Pull request by rodrigo-pino**

### CODE REVIEW

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/execution/errors.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBQhYC2CYHqmcl46rqZ:-OBQhYC2CYHqmcl46rq_:b226yhm) ([raw file](https://github.com/starkware-libs/sequencer/blob/db041798e6ee5800e688bc97a914e51bbad8175e/crates/blockifier/src/execution/errors.rs#L98)):*
> ```XML
>     #[cfg(feature = "cairo_native")]
>     #[error(transparent)]
>     NativeExecutionError(#[from] Box<SyscallExecutionError>),
> ```

I am not sure if this is the best approach. The Native Syscall Handler will catch non-recoverable `SyscallExecutionError`, nonetheless, the `entry_point_execution` needs to return an `EntryPointExecution` error.

It's not very clear to me in the current context what would be the best and simplest way to map between one to the other.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @meship-starkware, and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBR-hzaAz7pbfPPw4Fg:-OBR-hzaAz7pbfPPw4Fh:bzdbd9q) ([raw file](https://github.com/starkware-libs/sequencer/blob/db041798e6ee5800e688bc97a914e51bbad8175e/crates/blockifier/src/execution/native/syscall_handler.rs#L142)):*
> ```XML
>             SyscallExecutionError::SyscallError { error_data } => error_data,
>             _ => {
>                 self.unrecoverable_error = Some(error);
> ```

I think we can override this, so it may not necessarily contain the original error. Right?
We might need to check this variable at the beginning of each syscall.



_Code quote:_
```XML
self.unrecoverable_error = Some(error);
```

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBR-hzaAz7pbfPPw4Fg:-OBR21-v590HkgN6aLbE:b-fc0ryr) ([raw file](https://github.com/starkware-libs/sequencer/blob/db041798e6ee5800e688bc97a914e51bbad8175e/crates/blockifier/src/execution/native/syscall_handler.rs#L142)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think we can override this, so it may not necessarily contain the original error. Right?
We might need to check this variable at the beginning of each syscall.
</blockquote></details>

Because `remaining_gas` is set to 0 and every syscall pre charges at the beginning this should never happen. 

As a second thought, I think having the sanity check will be also worth it in case of a native bug :thinking:. Not sure what would be your preferred approach in this instance

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @meship-starkware)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBR-hzaAz7pbfPPw4Fg:-OBRAGN_AEvz8XPLZmYe:bcxh1pz) ([raw file](https://github.com/starkware-libs/sequencer/blob/db041798e6ee5800e688bc97a914e51bbad8175e/crates/blockifier/src/execution/native/syscall_handler.rs#L142)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

Because `remaining_gas` is set to 0 and every syscall pre charges at the beginning this should never happen. 

As a second thought, I think having the sanity check will be also worth it in case of a native bug :thinking:. Not sure what would be your preferred approach in this instance
</blockquote></details>

@ilyalesokhin-starkware noted that some syscalls have a cost of 0, so in these cases, setting the remaining gas to 0 will not trigger an abort. You could also make this parameter optional, allowing it to be set only when it is `None`.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware, @meship-starkware, and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBR-hzaAz7pbfPPw4Fg:-OBSYrHm4eEHp3KJxDDC:bs80qi6) ([raw file](https://github.com/starkware-libs/sequencer/blob/db041798e6ee5800e688bc97a914e51bbad8175e/crates/blockifier/src/execution/native/syscall_handler.rs#L142)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

@ilyalesokhin-starkware noted that some syscalls have a cost of 0, so in these cases, setting the remaining gas to 0 will not trigger an abort. You could also make this parameter optional, allowing it to be set only when it is `None`.
</blockquote></details>

I see that it's already optional :)
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBSYB6-6_rOr_RR2Vlh:-OBSYB6-6_rOr_RR2Vli:b-wxrkb5) ([raw file](https://github.com/starkware-libs/sequencer/blob/db041798e6ee5800e688bc97a914e51bbad8175e/crates/blockifier/src/execution/native/entry_point_execution.rs#L41)):*
> ```XML
>     if let Some(error) = syscall_handler.unrecoverable_error {
>         return Err(EntryPointExecutionError::NativeExecutionError(Box::new(error)));
>     }
> ```

You'll need to add a special case for this type of error in `execute_inner_call`. You may want to set `unrecoverable_error` with the specified error.



_Code quote:_
```XML
    if let Some(error) = syscall_handler.unrecoverable_error {
        return Err(EntryPointExecutionError::NativeExecutionError(Box::new(error)));
    }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBUAXtyCBhd0o4JFx-i:-OBUAXtyCBhd0o4JFx-j:b-ecu1vc) ([raw file](https://github.com/starkware-libs/sequencer/blob/db041798e6ee5800e688bc97a914e51bbad8175e/crates/blockifier/src/execution/native/syscall_handler.rs#L142)):*
> ```XML
>             SyscallExecutionError::SyscallError { error_data } => error_data,
>             _ => {
>                 self.unrecoverable_error = Some(error);
> ```

Can we add an assert that we are not overriding the error?



_Suggestion:_
```XML
 assert!(self.unrecoverable_error.is_none())
 self.unrecoverable_error = Some(error);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBUAqp8AICQCM-m8LUa:-OBUAqp8AICQCM-m8LUb:b-e7sbu3) ([raw file](https://github.com/starkware-libs/sequencer/blob/db041798e6ee5800e688bc97a914e51bbad8175e/crates/blockifier/src/execution/native/syscall_handler.rs#L106)):*
> ```XML
>     /// Handles all gas-related logics and additional metadata such as `SyscallCounter`. In native,
>     /// we need to explicitly call this method at the beginning of each syscall.
>     fn pre_execute_syscall(
> ```

Please check self.unrecoverable_error in pre_execute_syscall



_Code quote:_
```XML
 fn pre_execute_syscall(
```

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBSYB6-6_rOr_RR2Vlh:-OBUmkjH9XIrvbCo9jVA:b-ywzyyb) ([raw file](https://github.com/starkware-libs/sequencer/blob/db041798e6ee5800e688bc97a914e51bbad8175e/crates/blockifier/src/execution/native/entry_point_execution.rs#L41)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

You'll need to add a special case for this type of error in `execute_inner_call`. You may want to set `unrecoverable_error` with the specified error.
</blockquote></details>

I don't think the check will ever get executed if we put it on `execute_inner_call`. 

If we get to actually call `execute_inner_call`, it means there were no errors before because they were already checked for it at the beginning (adding a check to `pre_execute_syscall`) or if they appeared during the syscall execution, it would immediately return them.

During `execute_inner_call` execution, if an error occured, it will be handled accordingly, setting the flag and returning immediately. 
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBUAqp8AICQCM-m8LUa:-OBUoKwZ6NvOpaSMN1so:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/db041798e6ee5800e688bc97a914e51bbad8175e/crates/blockifier/src/execution/native/syscall_handler.rs#L106)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Please check self.unrecoverable_error in pre_execute_syscall
</blockquote></details>

Done
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBR-hzaAz7pbfPPw4Fg:-OBUqQ5HCBDwSp-Mn8Wi:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/db041798e6ee5800e688bc97a914e51bbad8175e/crates/blockifier/src/execution/native/syscall_handler.rs#L142)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I see that it's already optional :)
</blockquote></details>

Done
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBUAXtyCBhd0o4JFx-i:-OBUr0Ja1vUXpEwQnRpU:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/db041798e6ee5800e688bc97a914e51bbad8175e/crates/blockifier/src/execution/native/syscall_handler.rs#L142)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Can we add an assert that we are not overriding the error?
</blockquote></details>

Done

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @meship-starkware, @noaov1, and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBSYB6-6_rOr_RR2Vlh:-OB_Y1RGBH-AG5uVYUs7:b35nhqt) ([raw file](https://github.com/starkware-libs/sequencer/blob/db041798e6ee5800e688bc97a914e51bbad8175e/crates/blockifier/src/execution/native/entry_point_execution.rs#L41)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Ok, are you saying that this case will reach the `_ => {` arm in `handle_error`?
</blockquote></details>

Hmmm, the problem is that you are wrapping with `EntryPointExecutionError::NativeExecutionError()` on every level.

How about moving `unrecoverable_error` to `EntryPointExecutionContext`, and doing nothing here?

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @ilyalesokhin-starkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBSYB6-6_rOr_RR2Vlh:-OB_blw2-SvWrOAgKQBk:brmj680) ([raw file](https://github.com/starkware-libs/sequencer/blob/db041798e6ee5800e688bc97a914e51bbad8175e/crates/blockifier/src/execution/native/entry_point_execution.rs#L41)):*
> Hmmm, the problem is that you are wrapping with `EntryPointExecutionError::NativeExecutionError()` on every level.

I am not fully understanding this. I believe the wrapping only happens once, it is not back-propagated in the case of multiple inner calls. We get the error, we store it, once Native finishes we return it. Nothing after the error "counts" execution wise

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @ilyalesokhin-starkware, @meship-starkware, @noaov1, and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBSYB6-6_rOr_RR2Vlh:-OB_difYErR4aMuS4nOn:b9ombnp) ([raw file](https://github.com/starkware-libs/sequencer/blob/db041798e6ee5800e688bc97a914e51bbad8175e/crates/blockifier/src/execution/native/entry_point_execution.rs#L41)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

> Hmmm, the problem is that you are wrapping with `EntryPointExecutionError::NativeExecutionError()` on every level.

I am not fully understanding this. I believe the wrapping only happens once, it is not back-propagated in the case of multiple inner calls. We get the error, we store it, once Native finishes we return it. Nothing after the error "counts" execution wise
</blockquote></details>

I think it is propagated.
If the error happens in the inner most call, with N inner calls, we call `execute_entry_point_call` N times

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @ilyalesokhin-starkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBSYB6-6_rOr_RR2Vlh:-OB_hqvoA6XpALliW8mK:b-qq2eak) ([raw file](https://github.com/starkware-libs/sequencer/blob/db041798e6ee5800e688bc97a914e51bbad8175e/crates/blockifier/src/execution/native/entry_point_execution.rs#L41)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

I understand. It makes sense. Would moving it to `EntryPointExecutionContext` just for Native will be ok?
</blockquote></details>

If we were to modify `EntryPointExecutionContext`, I believe logic changes would be more extensive as well. What do you think of detecting these `NativeExecutionErrors` inside and non-rewrapping them. 

This logic would be defined in `self.handle_error` and it will be less invasive

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @ilyalesokhin-starkware, @meship-starkware, @noaov1, and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBSYB6-6_rOr_RR2Vlh:-OBa-Q4L3uQDbY4QBblp:b-vo0r2) ([raw file](https://github.com/starkware-libs/sequencer/blob/db041798e6ee5800e688bc97a914e51bbad8175e/crates/blockifier/src/execution/native/entry_point_execution.rs#L41)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

If we were to modify `EntryPointExecutionContext`, I believe logic changes would be more extensive as well. What do you think of detecting these `NativeExecutionErrors` inside and non-rewrapping them. 

This logic would be defined in `self.handle_error` and it will be less invasive
</blockquote></details>

Sounds good, let's do this

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @ilyalesokhin-starkware, @noaov1, and @rodrigo-pino)

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @ilyalesokhin-starkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBSYB6-6_rOr_RR2Vlh:-OBeZtOt-KBcBjvs2nCS:bb6ebfb) ([raw file](https://github.com/starkware-libs/sequencer/blob/db041798e6ee5800e688bc97a914e51bbad8175e/crates/blockifier/src/execution/native/entry_point_execution.rs#L41)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Sounds good, let's do this
</blockquote></details>

Done, please re-review

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @ilyalesokhin-starkware, @noaov1, and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @ilyalesokhin-starkware, @noaov1, and @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @ilyalesokhin-starkware, @meship-starkware, @noaov1, and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/errors.rs` line 98 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBecqqN9LlG_ujh-vAH:-OBecqqO1G50DxjybETx:b-7zi8ni) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f7bdd639d3a9be205663113085fba2cb791811d/crates/blockifier/src/execution/errors.rs#L98)):*
> ```XML
>     #[cfg(feature = "cairo_native")]
>     #[error(transparent)]
>     NativeExecutionError(#[from] Box<SyscallExecutionError>),
> ```

WDYT?



_Suggestion:_
```XML
NativeUnrecoverableError
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-:-OBefPoK7s-BOv_aw3vm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @ilyalesokhin-starkware, @meship-starkware, and @noaov1)

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1948)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rodrigo-pino)

___
*[`crates/blockifier/src/execution/errors.rs` line 98 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1948#-OBecqqN9LlG_ujh-vAH:-OBefSR937svOyJBC4MM:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/86aef835fbd674b2061cf486f27b7f27cc46682a/crates/blockifier/src/execution/errors.rs#L98)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

Done

**Pull request merged**
