### PR TITLE
feat(mempool_test_utils): register accounts as deployed or undeployed

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2802)* status: all files reviewed, 4 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 273 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2802#-OFHPiy3492X4NIZ3P6v:-OFHPiy48aO6OYfcLy5n:bdgjlg9) ([raw file](https://github.com/starkware-libs/sequencer/blob/30d83b5603f1c569fa2bf5e47bb197bf5f27466e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L273)):*
> ```XML
>             "Cannot invoke on behalf of an undeployed account: the first transaction of every \
>              account must be a deploy account transaction."
>         );
> ```

Is this assert not enough?



_Code quote:_
```XML
        assert_ne!(
            nonce,
            nonce!(0),
            "Cannot invoke on behalf of an undeployed account: the first transaction of every \
             account must be a deploy account transaction."
        );
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2802)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 265 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2802#-OFHM-Re9VQKRQq2eh_F:-OFHiiGIBbKbbUjC1hGH:b-lesthg) ([raw file](https://github.com/starkware-libs/sequencer/blob/30d83b5603f1c569fa2bf5e47bb197bf5f27466e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L265)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Does this mean all accounts are now deployed with a deploy account tx? Why do we need to register undeployed accounts at all?
</blockquote></details>

No.
You can either register a deployed or undeployed account.
Both are funded in the initial state (once the GW sync flow is implemented we can remove that for the undeployed accounts).
We need to register undeployed accounts to get their expected contract and, in the future, generate TXs from them after their deployment.
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 273 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2802#-OFHPiy3492X4NIZ3P6v:-OFHjyiU2HdCT0BJblyD:b-sqg2m2) ([raw file](https://github.com/starkware-libs/sequencer/blob/30d83b5603f1c569fa2bf5e47bb197bf5f27466e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L273)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Is this assert not enough?
</blockquote></details>

Unfortunately the state is decoupled from the generator, so it is better to check on both systems.
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 314 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2802#-OFHMamd2b6IV1z1b90C:-OFHkVO-9EcWBs92GTaE:brucgwt) ([raw file](https://github.com/starkware-libs/sequencer/blob/56942a28b1d1238d4b500ced6e56f0d25ea304a0/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L314)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Is this not good anymore?
</blockquote></details>

The salt is used in multiple places so it needs to be generated externally.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2802)* status: all files reviewed, 3 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 273 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2802#-OFHPiy3492X4NIZ3P6v:-OFHwA2OAQmTp3isvgjM:b-o3y1k8) ([raw file](https://github.com/starkware-libs/sequencer/blob/30d83b5603f1c569fa2bf5e47bb197bf5f27466e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L273)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Unfortunately the state is decoupled from the generator, so it is better to check on both systems.
</blockquote></details>

But the nonce is not taken from the state, it's also from the generator.
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 314 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2802#-OFHMamd2b6IV1z1b90C:-OFHwO8S5U3rl39iI2vE:b-og37vq) ([raw file](https://github.com/starkware-libs/sequencer/blob/56942a28b1d1238d4b500ced6e56f0d25ea304a0/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L314)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The salt is used in multiple places so it needs to be generated externally.
</blockquote></details>

Where else it is used? In any case, you can always get it from the account id, which you should have anyway, right?

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2802)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 273 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2802#-OFHPiy3492X4NIZ3P6v:-OFMOSwN4QFBT7RH4il9:bf7kw86) ([raw file](https://github.com/starkware-libs/sequencer/blob/30d83b5603f1c569fa2bf5e47bb197bf5f27466e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L273)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

But the nonce is not taken from the state, it's also from the generator.
</blockquote></details>

Didn't realize that.
Made changes that are derived from this.
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 314 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2802#-OFHMamd2b6IV1z1b90C:-OFQjiyyE12A62INTCWJ:bw1joiv) ([raw file](https://github.com/starkware-libs/sequencer/blob/56942a28b1d1238d4b500ced6e56f0d25ea304a0/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L314)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Where else it is used? In any case, you can always get it from the account id, which you should have anyway, right?
</blockquote></details>

It is needed for the deploy account tx args.
I don't like getting it from the account id because it was hard for me to understand how to get the salt for the transaction.
This way is better IMO because it is more explicit.
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2802#-OFHJjP8EXxxjVz3mb8Q:-OFM9oJCEUup9wBP0KnS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/30d83b5603f1c569fa2bf5e47bb197bf5f27466e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L191)):*
> ```XML
> 
>     /// Registers a new account with the given contract, assuming it is already deployed.
>     /// Note: the state should reflect it if the account is already deployed.
> ```

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2802#-:-OFRND50AXtyZjvKzaZW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
