### PR TITLE
test(mempool): refactor test_tip_priority_over_tx_hash to use mempool…

### PR DESCRIPTION
**Pull request by ayeletstarkware**
… state

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/81)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/81)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 367 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/81#-O2dLN7V5BxGgP9_yUp8:-O2dLN7W1FpXJnzphiFR:b-c32aye) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5db2587d98405879507f5ab347a792861cefe1d/crates/mempool/src/mempool_test.rs#L367)):*
> ```XML
>         [&input_big_tip_small_hash.tx, &input_small_tip_big_hash.tx].map(TransactionReference::new);
>     let expected_mempool_state = MempoolState::with_queue(expected_queue_txs);
> ```

Maybe wait for #80 which is LGTM-ed, and use its `assert_eq_queue` method?

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/81)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/81)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 367 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/81#-O2dLN7V5BxGgP9_yUp8:-O2dacKPBMnn5u7YO5r6:b-7buwcm) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5db2587d98405879507f5ab347a792861cefe1d/crates/mempool/src/mempool_test.rs#L367)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Maybe wait for #80 which is LGTM-ed, and use its `assert_eq_queue` method?
</blockquote></details>

i don't understand. that's what i'm using.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/81)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 367 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/81#-O2dLN7V5BxGgP9_yUp8:-O2dbuMx5NYH19l4T1az:b-e03l41) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5db2587d98405879507f5ab347a792861cefe1d/crates/mempool/src/mempool_test.rs#L367)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

i don't understand. that's what i'm using.
</blockquote></details>

How is building `MempoolState` with `with_X` work then? Shoul those c-tors be renamed?
I'm confused as to how come no changes were needed to use the new generic struct...

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/81)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/81)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 368 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/81#-O2dft045mCYjAjx2vt5:-O2dft045mCYjAjx2vt6:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/dfac7a166db89315052e90cd959675f79cfe7808/crates/mempool/src/mempool_test.rs#L368)):*
> ```XML
>     let expected_mempool_state = MempoolState::with_queue(expected_queue_txs);
> 
>     expected_mempool_state.assert_eq_queue_state(&mempool);
> ```





_Suggestion:_
```XML
    let expected_mempool_state = MempoolState::with_queue(expected_queue_txs);
    expected_mempool_state.assert_eq_queue_state(&mempool);
```

**Pull request merged**
