### PR TITLE
chore(starknet_gateway): use the get nonce method of the stateful validator trait

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#2948** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2948?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2  dependent PRs ([#2404](https://github.com/starkware-libs/sequencer/pull/2404) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2404?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#2911](https://github.com/starkware-libs/sequencer/pull/2911) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2911?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2982** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2982?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2982?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ArniStarkware — COMMENTED** [review]
+reviewer:@Yael-Starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2982#-:-OF1suIf4TmSgul77gO1:b835xbr)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2982)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_gateway/src/gateway.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2982#-OF2OWCg4zlqKBZgiWFA:-OF2OWCg4zlqKBZgiWFB:b-wlvd5r) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3a7046eef98cd5fe0317aa3dbf9cc4751ee9b5/crates/starknet_gateway/src/gateway.rs#L141)):*
> ```XML
>         let address = executable_tx.contract_address();
>         let nonce =
>             StatefulTransactionValidatorTrait::get_nonce(&mut validator, address).map_err(|e| {
> ```

please remove get_nonce from the trait if it isn't needed there anymore.



_Code quote:_
```XML
StatefulTransactionValidatorTrait::get_nonce
```

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2982)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2982)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
