### PR TITLE
fix(blockifier): bouncer_weights remove derives of add, addassign, sub. use 'checked' instead

### PR DESCRIPTION
**Pull request by avivg-starkware**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2835)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2835#-OEUbcEl94MPe-ukHp4A:-OEUbcEl94MPe-ukHp4B:b2aqiql) ([raw file](https://github.com/starkware-libs/sequencer/blob/df8829cc0ee8194941b45efd58dc34a3de8f8179/crates/blockifier/src/bouncer.rs#L116)):*
> ```XML
>         *self = self.checked_add(other).expect("Addition overflow");
>     }
> }
> ```

you are making `+` operations behave like "checked_add_or_panic".
is this what we want?
I prefer to be explicit, how painful would it be to replace all?
(if it helps, you can derive the arithmetic traits in testing mode)



_Code quote:_
```XML
impl std::ops::Add for BouncerWeights {
    type Output = BouncerWeights;

    fn add(self, other: BouncerWeights) -> BouncerWeights {
        self.checked_add(other).expect("Addition overflow")
    }
}
impl std::ops::AddAssign for BouncerWeights {
    fn add_assign(&mut self, other: BouncerWeights) {
        *self = self.checked_add(other).expect("Addition overflow");
    }
}
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2835#-:-OEhpr5t4o3rkpdkZq6a:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2835)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 0 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2835#-OEhztpe5gJ6uuFmUT09:-OEhztpe5gJ6uuFmUT0A:btopbh4) ([raw file](https://github.com/starkware-libs/sequencer/blob/7af5968a57a1636c16185430d0767798ab6f2b85/crates/blockifier/src/bouncer.rs#L0)):*
1. do we want checked or saturating?
2. if we want checked, please add more info in the `expect` message: (a) the text in the two cases should be different (easier to identify the source of panic) and (b) maybe also output the weights being added

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2835)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2835#-OEUbcEl94MPe-ukHp4A:-OEiCZoJCI79DQDMKoEn:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/df8829cc0ee8194941b45efd58dc34a3de8f8179/crates/blockifier/src/bouncer.rs#L116)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you are making `+` operations behave like "checked_add_or_panic".
is this what we want?
I prefer to be explicit, how painful would it be to replace all?
(if it helps, you can derive the arithmetic traits in testing mode)
</blockquote></details>

Done
___
*[`crates/blockifier/src/bouncer.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2835#-OEhztpe5gJ6uuFmUT09:-OEmmnt02poZ5SCY7ZiG:btwew2a) ([raw file](https://github.com/starkware-libs/sequencer/blob/7af5968a57a1636c16185430d0767798ab6f2b85/crates/blockifier/src/bouncer.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. do we want checked or saturating?
2. if we want checked, please add more info in the `expect` message: (a) the text in the two cases should be different (easier to identify the source of panic) and (b) maybe also output the weights being added
</blockquote></details>

@Yoni-Starkware  WDYT? i would assume checked, if overflow is something that shouldn't happen. but perhaps saturating is sufficient?

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2835)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/bouncer.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2835#-OEhztpe5gJ6uuFmUT09:-OEmqZdqEcov7otEfGtn:bb7k0qh) ([raw file](https://github.com/starkware-libs/sequencer/blob/7af5968a57a1636c16185430d0767798ab6f2b85/crates/blockifier/src/bouncer.rs#L)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

@Yoni-Starkware  WDYT? i would assume checked, if overflow is something that shouldn't happen. but perhaps saturating is sufficient?
</blockquote></details>

lgtm

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2835)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Comment by avivg-starkware** [comment]
*[`crates/blockifier/src/bouncer.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2835#-OEhztpe5gJ6uuFmUT09:-OEnaqmbE0eeKd7VeOVB:b-9574bl) ([raw file](https://github.com/starkware-libs/sequencer/blob/7af5968a57a1636c16185430d0767798ab6f2b85/crates/blockifier/src/bouncer.rs#L)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

lgtm
</blockquote></details>

@dorimedini-starkware  how does the info I've added looks to you? should I change anything?

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2835)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/bouncer.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2835#-OEhztpe5gJ6uuFmUT09:-OEneJOw-Ui_LHRzwZIS:bb7k0qh) ([raw file](https://github.com/starkware-libs/sequencer/blob/7af5968a57a1636c16185430d0767798ab6f2b85/crates/blockifier/src/bouncer.rs#L)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

@dorimedini-starkware  how does the info I've added looks to you? should I change anything?
</blockquote></details>

lgtm

**Pull request merged**
