### PR TITLE
refactor(consensus): add current_round_upons as in the paper

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1206)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1206)* status: 1 of 3 files reviewed, 11 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8aar6S0EwIo4ReF0KN:-O8aar6S0EwIo4ReF0KO:b-hupk09) ([raw file](https://github.com/starkware-libs/sequencer/blob/a19acd0ba6bc49cff0c83ae238485b2045dc82ae/crates/sequencing/papyrus_consensus/src/state_machine.rs#L69)):*
> ```XML
>     events_queue: VecDeque<StateMachineEvent>,
>     locked_value: Option<(ProposalContentId, Round)>,
>     prevote_quorum: std::collections::HashSet<Round>,
> ```

and other fields



_Suggestion:_
```XML
    use std::collections::HashSet;
    ...
    prevote_quorum: HashSet<Round>,
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 355 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8apGa51nBD5zeLaEuo:-O8apGa51nBD5zeLaEup:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb220e1294f9d13664465676b17518e54fe662b1/crates/sequencing/papyrus_consensus/src/state_machine.rs#L355)):*
> ```XML
>     }
> 
>     fn map_round<LeaderFn>(
> ```





_Suggestion:_
```XML
    fn map_round_to_upons<LeaderFn>(
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 374 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8aqH8IAOOQ90k_LLtk:-O8aqH8J4UGEYp_O2nP7:becu5a3) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb220e1294f9d13664465676b17518e54fe662b1/crates/sequencing/papyrus_consensus/src/state_machine.rs#L374)):*
> ```XML
>         output.append(&mut self.upon_new_proposal());
>         output.append(&mut self.upon_reproposal());
>         output.append(&mut self.maybe_timeout_prevote());
> ```

(and precommit)



_Suggestion:_
```XML
maybe_initiate_timeout_prevote
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 393 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8aqQBr4f3Nw4_os91N:-O8aqQBr4f3Nw4_os91O:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb220e1294f9d13664465676b17518e54fe662b1/crates/sequencing/papyrus_consensus/src/state_machine.rs#L393)):*
> ```XML
>         round: u32,
>         leader_fn: &LeaderFn,
>     ) -> VecDeque<StateMachineEvent>
> ```





_Suggestion:_
```XML
    // LOC 55 in the paper.
    fn future_round_upons<LeaderFn>(
        &mut self,
        round: u32,
        leader_fn: &LeaderFn,
    ) -> VecDeque<StateMachineEvent>
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 408 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8auQx63xOYMlu68rDg:-O8auQx63xOYMlu68rDh:bmozdhj) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb220e1294f9d13664465676b17518e54fe662b1/crates/sequencing/papyrus_consensus/src/state_machine.rs#L408)):*
> ```XML
>     fn upon_new_proposal(&mut self) -> VecDeque<StateMachineEvent> {
>         // StateMachine assumes that the proposer is valid.
>         let Some((proposal_content_id, valid_round)) = self.proposals.get(&self.round) else {
> ```

We can call the local variable `proposal_id` (here and elsewhere in the file). We use the type name `ProposalContentId` since in other contexts there may be other ways of identifying the proposal.



_Suggestion:_
```XML
proposal_id
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 415 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8axmSw9VADax8J3mOR:-O8axmSw9VADax8J3mOS:bor7g9n) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb220e1294f9d13664465676b17518e54fe662b1/crates/sequencing/papyrus_consensus/src/state_machine.rs#L415)):*
> ```XML
>         }
>         let mut output = if self.locked_value.as_ref().map_or(true, |(locked_proposal, _)| {
>             proposal_content_id.map_or(false, |proposal| *locked_proposal == proposal)
> ```

I find this a bid easier to compare with the paper



_Suggestion:_
```XML
        let mut output = if proposal_id
            .is_some_and(|v| self.locked_value.map_or(true, |(locked_value, _)| v == locked_value))
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 425 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8axwLI6dh--v9tlCAG:-O8axwLJ3f1o5lutrUhc:b-ze3ek4) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb220e1294f9d13664465676b17518e54fe662b1/crates/sequencing/papyrus_consensus/src/state_machine.rs#L425)):*
> ```XML
>     }
> 
>     // LOC 36 in the paper.
> ```

Let's keep the order of upon definitions here the same as in the paper. So move 28 & 34 here (and check for other lines)



_Code quote:_
```XML
    }

    // LOC 36 in the paper.
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 433 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8ayK3t6q_5ra08jk0-:-O8ayK3uAsVujtk64vsx:bjvjs3y) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb220e1294f9d13664465676b17518e54fe662b1/crates/sequencing/papyrus_consensus/src/state_machine.rs#L433)):*
> ```XML
>             return VecDeque::new();
>         };
>         let Some((block_hash, count)) = leading_vote(&self.prevotes, self.round) else {
> ```

Same changes as before, look up the specific proposal_id that we already know we are interested in



_Code quote:_
```XML
        let Some((block_hash, count)) = leading_vote(&self.prevotes, self.round) else {
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 447 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8azDqh-mtLOq7DLpUM:-O8azDqh-mtLOq7DLpUN:bh6nc01) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb220e1294f9d13664465676b17518e54fe662b1/crates/sequencing/papyrus_consensus/src/state_machine.rs#L447)):*
> ```XML
>         if !self.prevote_quorum.insert(self.round) {
>             return VecDeque::new();
>         }
> ```

Clarify what this check is for (for the first time). Add it to the other relevant lines also



_Code quote:_
```XML
        if !self.prevote_quorum.insert(self.round) {
            return VecDeque::new();
        }
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 455 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8azqXY3tlr80xEqEzQ:-O8azqXY3tlr80xEqEzR:bt2sr4q) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb220e1294f9d13664465676b17518e54fe662b1/crates/sequencing/papyrus_consensus/src/state_machine.rs#L455)):*
> ```XML
>             VecDeque::from([StateMachineEvent::Precommit(Some(*block_hash), self.round)]);
>         output.append(&mut self.advance_to_step(Step::Precommit));
>         output
> ```

This is incorrect. the paper has 2 fields: locked & valid. valid is always set at this point. The lock though is only updated if we are in the prevote step. You need to add the second field and then check that you are using lock correctly and valid value correctly throughout.



_Code quote:_
```XML
        self.locked_value = Some((*block_hash, self.round));
        if self.step != Step::Prevote {
            return VecDeque::new();
        }
        let mut output =
            VecDeque::from([StateMachineEvent::Precommit(Some(*block_hash), self.round)]);
        output.append(&mut self.advance_to_step(Step::Precommit));
        output
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 471 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8b-Otp9ZyYnkJ7rMR8:-O8b-OtqAC7OMFTILwFK:b-7wis4q) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb220e1294f9d13664465676b17518e54fe662b1/crates/sequencing/papyrus_consensus/src/state_machine.rs#L471)):*
> ```XML
>         if block_hash.is_some() {
>             return VecDeque::new();
>         }
> ```

just check explicitly for none instead of leading vote



_Code quote:_
```XML
        let Some((block_hash, count)) = leading_vote(&self.prevotes, self.round) else {
            return VecDeque::new();
        };
        if count < &self.quorum {
            return VecDeque::new();
        }
        if block_hash.is_some() {
            return VecDeque::new();
        }
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1206)* status: all files reviewed, 14 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 253 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8evYfmBERexBgV2JUC:-O8evYfmBERexBgV2JUD:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/475fc46b2b68787d0dbee32da4fcc03975cf39e0/crates/sequencing/papyrus_consensus/src/state_machine.rs#L253)):*
> ```XML
>     }
> 
>     fn handle_timeout_proposal(&mut self, round: u32) -> VecDeque<StateMachineEvent> {
> ```





_Suggestion:_
```XML
handle_timeout_propose
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 346 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8eyVrFE-SD4VoIoPut:-O8eyVrFE-SD4VoIoPuu:bnwcge9) ([raw file](https://github.com/starkware-libs/sequencer/blob/475fc46b2b68787d0dbee32da4fcc03975cf39e0/crates/sequencing/papyrus_consensus/src/state_machine.rs#L346)):*
> ```XML
>         if !self.proposals.contains_key(&round) {
>             return VecDeque::from([StateMachineEvent::TimeoutPropose(round)]);
>         }
> ```

Why are you checking the list of existing proposals?



_Code quote:_
```XML
        if !self.proposals.contains_key(&round) {
            return VecDeque::from([StateMachineEvent::TimeoutPropose(round)]);
        }
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 347 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8f-Sye81HwDF0-TZAg:-O8f-Sye81HwDF0-TZAh:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/475fc46b2b68787d0dbee32da4fcc03975cf39e0/crates/sequencing/papyrus_consensus/src/state_machine.rs#L347)):*
> ```XML
>             return VecDeque::from([StateMachineEvent::TimeoutPropose(round)]);
>         }
>         self.map_round_to_upons(round, leader_fn)
> ```





_Suggestion:_
```XML
        let mut output = if self.id == leader_fn(self.round) {
            // Leader.
            match self.valid_value_round {
                Some((proposal_id, valid_round)) => {
                    VecDeque::from([StateMachineEvent::Proposal(
                        Some(proposal_id),
                        self.round,
                        Some(valid_round),
                    )])
                }
                None => {
                    self.awaiting_get_proposal = true;
                    // Upon conditions are not checked while awaiting a new proposal.
                    return VecDeque::from([StateMachineEvent::GetProposal(None, self.round)]);
                }
            }
        } else {
            VecDeque::from([StateMachineEvent::TimeoutPropose(self.round)])
        };
        output.append(&mut self.current_round_upons());
        output
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 357 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8f-nNS3YASiqyLaDC6:-O8f-nNS3YASiqyLaDC7:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/475fc46b2b68787d0dbee32da4fcc03975cf39e0/crates/sequencing/papyrus_consensus/src/state_machine.rs#L357)):*
> ```XML
>             Step::Prevote => self.current_round_upons(),
>             Step::Precommit => self.current_round_upons(),
>         }
> ```





_Suggestion:_
```XML
        assert_ne!(step, Step::Propose, "Advancing to Propose is done by advancing rounds");
        self.step = step;
        self.current_round_upons()
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 402 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8f11g_-w5AUPSP5y-T:-O8f11g_-w5AUPSP5y-U:b1uy0e0) ([raw file](https://github.com/starkware-libs/sequencer/blob/475fc46b2b68787d0dbee32da4fcc03975cf39e0/crates/sequencing/papyrus_consensus/src/state_machine.rs#L402)):*
> ```XML
>         if self.step != Step::Propose || valid_round.is_some() {
>             return VecDeque::new();
>         }
> ```

Consider moving the step check to the top for performance reasons.



_Code quote:_
```XML
        let Some((proposal_id, valid_round)) = self.proposals.get(&self.round) else {
            return VecDeque::new();
        };
        if self.step != Step::Propose || valid_round.is_some() {
            return VecDeque::new();
        }
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 440 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8f24Aj2avTXr88njyC:-O8f24Aj2avTXr88njyD:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/475fc46b2b68787d0dbee32da4fcc03975cf39e0/crates/sequencing/papyrus_consensus/src/state_machine.rs#L440)):*
> ```XML
>                     locked_round <= *valid_round || locked_value == v
>                 })
>         }) {
> ```





_Suggestion:_
```XML
        let mut output = if block_hash.is_some_and(|v| {
            self.locked_value_round.map_or(true, |(locked_value, locked_round)| {
                locked_round <= *valid_round || locked_value == v
            })
        }) {
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 457 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8f6Bw1Afp82TwK8fUr:-O8f6Bw1Afp82TwK8fUs:bzehy40) ([raw file](https://github.com/starkware-libs/sequencer/blob/475fc46b2b68787d0dbee32da4fcc03975cf39e0/crates/sequencing/papyrus_consensus/src/state_machine.rs#L457)):*
> ```XML
>         if num_votes < self.quorum {
>             return VecDeque::new();
>         }
> ```

I see this repeating a lot. WDYT of a helper function? It doesn't help with lines but I feel like the fn name documents what's happening to make this easier to read.



_Suggestion:_
```XML
        if !round_has_enough_votes(&self.prevotes, self.round, self.quorum) {
            return VecDeque::new();
        }
        
fn round_has_enough_votes(
    votes: &HashMap<u32, HashMap<Option<BlockHash>, u32>>,
    round: u32,
    threshold: u32,
) -> bool {
    votes.get(&round).map_or(0, |v| v.values().sum()) >= threshold
}
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 479 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8f4kBD0V1pxxFACwM_:-O8f4kBD0V1pxxFACwMa:b243q8l) ([raw file](https://github.com/starkware-libs/sequencer/blob/475fc46b2b68787d0dbee32da4fcc03975cf39e0/crates/sequencing/papyrus_consensus/src/state_machine.rs#L479)):*
> ```XML
>         if count < &self.quorum {
>             return VecDeque::new();
>         }
> ```

I see this pattern repeating a lot. WDYT of adding a helper function, like leading_vote.



_Suggestion:_
```XML
        if !value_has_enough_votes(&self.prevotes, self.round, proposal_id, self.quorum) {
            return VecDeque::new();
        }
        
fn value_has_enough_votes(
    votes: &HashMap<u32, HashMap<Option<BlockHash>, u32>>,
    round: u32,
    value: &Option<BlockHash>,
    threshold: u32,
) -> bool {
    votes.get(&round).map_or(0, |v| *v.get(value).unwrap_or(&0)) >= threshold
}
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 553 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8f0Bf96t8zS21bsIA4:-O8f0Bf96t8zS21bsIA5:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/475fc46b2b68787d0dbee32da4fcc03975cf39e0/crates/sequencing/papyrus_consensus/src/state_machine.rs#L553)):*
> ```XML
> 
>     // LOC 55 in the paper.
>     fn future_round_upons<LeaderFn>(
> ```





_Suggestion:_
```XML
maybe_advance_to_round
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 569 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8fBdF4D0Wt-P_uyOTt:-O8fBdF4D0Wt-P_uyOTu:bwxdfnm) ([raw file](https://github.com/starkware-libs/sequencer/blob/475fc46b2b68787d0dbee32da4fcc03975cf39e0/crates/sequencing/papyrus_consensus/src/state_machine.rs#L569)):*
> ```XML
>             VecDeque::new()
>         }
>     }
> ```

This is actually nice here from a performance perspective, since if prevotes has enough then we don't even bother trying to calculate this over the precommits.



_Suggestion:_
```XML
        if round_has_enough_votes(&self.prevotes, round, self.round_skip_threshold)
            || round_has_enough_votes(&self.precommits, round, self.round_skip_threshold)
        {
            self.advance_to_round(round, leader_fn)
        } else {
            VecDeque::new()
        }
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 347 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8fBV2f1wXBTV9zZRpf:-O8fBV2f1wXBTV9zZRpg:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/475fc46b2b68787d0dbee32da4fcc03975cf39e0/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L347)):*
> ```XML
>         StateMachineEvent::Proposal(BLOCK_HASH, ROUND + 1, None)
>     );
>     assert_eq!(wrapper.next_event().unwrap(), StateMachineEvent::TimeoutPrecommit(ROUND + 1));
> ```





_Suggestion:_
```XML
    // It now receives the proposal.
    wrapper.send_get_proposal(BLOCK_HASH, ROUND);
    assert_eq!(wrapper.next_event().unwrap(), StateMachineEvent::Proposal(BLOCK_HASH, ROUND, None));
    assert_eq!(wrapper.next_event().unwrap(), StateMachineEvent::TimeoutPrecommit(ROUND));
    
    // Timeout and move on to the next round.
    wrapper.send_timeout_precommit(ROUND);
    assert_eq!(wrapper.next_event().unwrap(), StateMachineEvent::GetProposal(None, ROUND + 1));
    assert!(wrapper.next_event().is_none());

    // The other votes are only handled after the next GetProposal is received.
    wrapper.send_get_proposal(BLOCK_HASH, ROUND + 1);
    assert_eq!(
        wrapper.next_event().unwrap(),
        StateMachineEvent::Proposal(BLOCK_HASH, ROUND + 1, None)
    );
    assert_eq!(wrapper.next_event().unwrap(), StateMachineEvent::TimeoutPrecommit(ROUND + 1));
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1206)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 433 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8gctnm1P6k3LyQWjQW:-O8gctnm1P6k3LyQWjQX:b-cztimr) ([raw file](https://github.com/starkware-libs/sequencer/blob/83fd5d8d3a001a588c5d884094830487308de5b3/crates/sequencing/papyrus_consensus/src/state_machine.rs#L433)):*
> ```XML
>         if count < &self.quorum {
>             return VecDeque::new();
>         }
> ```

value_has_enough_votes?



_Code quote:_
```XML
        let Some(round_prevotes) = self.prevotes.get(valid_round) else {
            return VecDeque::new();
        };
        let Some(count) = round_prevotes.get(proposal_id) else { return VecDeque::new() };
        if count < &self.quorum {
            return VecDeque::new();
        }
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 518 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8ge16k95D66HNdd78Y:-O8ge16l2eh8ckptx5uz:bbmr6b1) ([raw file](https://github.com/starkware-libs/sequencer/blob/83fd5d8d3a001a588c5d884094830487308de5b3/crates/sequencing/papyrus_consensus/src/state_machine.rs#L518)):*
> ```XML
>     // LOC 49 in the paper.
>     fn upon_decision(&mut self, round: u32) -> VecDeque<StateMachineEvent> {
>         let Some((block_hash, count)) = leading_vote(&self.precommits, round) else {
> ```

This seems now to be the only use. consider removing the helper function and just inlining it.



_Code quote:_
```XML
        let Some((block_hash, count)) = leading_vote(&self.precommits, round) else {
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1206)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 433 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8gctnm1P6k3LyQWjQW:-O8h5vsL4PPBF2YixYhR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/83fd5d8d3a001a588c5d884094830487308de5b3/crates/sequencing/papyrus_consensus/src/state_machine.rs#L433)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

value_has_enough_votes?
</blockquote></details>

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1206)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 471 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8kON4EAV4zK_guCCoz:-O8kON4EAV4zK_guCCp-:b-y04czf) ([raw file](https://github.com/starkware-libs/sequencer/blob/f7a7a9e9670064443fa1826c89a1005a8386050e/crates/sequencing/papyrus_consensus/src/state_machine.rs#L471)):*
> ```XML
>         let Some(proposal_id) = proposal_id else {
>             return VecDeque::new();
>         };
> ```

I am compounding the get proposal and proposal is valid into a single line `Some(Some(v))`. WDYT?



_Suggestion:_
```XML
        let Some((Some(proposal_id), _)) = self.proposals.get(&self.round) else {
            return VecDeque::new();
        };
        if !value_has_enough_votes(
            &self.prevotes,
            self.round,
            &Some(proposal_id.clone()),
            self.quorum,
        ) {
            return VecDeque::new();
        }
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 534 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1206#-O8kKPTZ2IGHHm7tvpU_:-O8kKPTZ2IGHHm7tvpUa:b466svv) ([raw file](https://github.com/starkware-libs/sequencer/blob/f7a7a9e9670064443fa1826c89a1005a8386050e/crates/sequencing/papyrus_consensus/src/state_machine.rs#L534)):*
> ```XML
>             error!("Proposal does not match quorum.");
>             return VecDeque::new();
>         }
> ```

Let's start with the proposal lookup



_Suggestion:_
```XML
        let Some((Some(proposal_id), _)) = self.proposals.get(&round) else {
            return VecDeque::new();
        };
        if !value_has_enough_votes(&self.precommits, round, &Some(proposal_id.clone()), self.quorum)
        {
            return VecDeque::new();
        }
```

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1206)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1206)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
