### PR TITLE
chore: split transaction file part one fields dedicated file

### PR DESCRIPTION
**Pull request by ArniStarkware**
chore: split transaction file part one fields dedicated file

chore: remove public imports from starknet api transaction

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#1732** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1732?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1732)* status: 0 of 116 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @dorimedini-starkware)

___
*[`crates/starknet_api/src/transaction.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OAqcapK9mHQtT7POziu:-OAqcapK9mHQtT7POziv:b3o6d15) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca40e429c12bd04c81a7f66756013c7a877b13b6/crates/starknet_api/src/transaction.rs#L118)):*
> ```XML
>     }
> }
> ```

Please move this struct as well.
___
*[`crates/starknet_api/src/transaction.rs` line 716 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OAqclj1-efEmU_P9ypC:-OAqclj1-efEmU_P9ypD:b-ligi68) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca40e429c12bd04c81a7f66756013c7a877b13b6/crates/starknet_api/src/transaction.rs#L716)):*
> ```XML
>     #[serde(flatten)]
>     pub output: TransactionOutput,
> }
> ```

This as well?



_Code quote:_
```XML
/// A transaction receipt.
#[derive(Debug, Clone, Eq, PartialEq, Deserialize, Serialize)]
pub struct TransactionReceipt {
    pub transaction_hash: TransactionHash,
    pub block_hash: BlockHash,
    pub block_number: BlockNumber,
    #[serde(flatten)]
    pub output: TransactionOutput,
}
```
___
*[`crates/starknet_api/src/transaction.rs` line 843 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OAqcunS4meN6G0uL6kg:-OAqcunS4meN6G0uL6kh:bdn3zet) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca40e429c12bd04c81a7f66756013c7a877b13b6/crates/starknet_api/src/transaction.rs#L843)):*
> ```XML
> #[derive(
>     Debug, Default, Copy, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord,
> )]
> ```

these as well?



_Code quote:_
```XML
#[derive(Debug, Default, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
pub struct MessageToL2 {
    pub from_address: EthAddress,
    pub payload: L1ToL2Payload,
}

/// An L2 to L1 message.
#[derive(Debug, Default, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
pub struct MessageToL1 {
    pub from_address: ContractAddress,
    pub to_address: EthAddress,
    pub payload: L2ToL1Payload,
}

/// The payload of [`MessageToL2`].
#[derive(Debug, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
pub struct L1ToL2Payload(pub Vec<Felt>);

/// The payload of [`MessageToL1`].
#[derive(Debug, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
pub struct L2ToL1Payload(pub Vec<Felt>);

/// An event.
#[derive(Debug, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
pub struct Event {
    // TODO: Add a TransactionHash element to this struct, and then remove EventLeafElements.
    pub from_address: ContractAddress,
    #[serde(flatten)]
    pub content: EventContent,
}

/// An event content.
#[derive(Debug, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
pub struct EventContent {
    pub keys: Vec<EventKey>,
    pub data: EventData,
}

/// An event key.
#[derive(Debug, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
pub struct EventKey(pub Felt);

/// An event data.
#[derive(Debug, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
pub struct EventData(pub Vec<Felt>);

/// The index of a transaction in [BlockBody](`crate::block::BlockBody`).
#[derive(
    Debug, Default, Copy, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord,
)]
pub struct TransactionOffsetInBlock(pub usize);

/// The index of an event in [TransactionOutput](`crate::transaction::TransactionOutput`).
#[derive(
    Debug, Default, Copy, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord,
)]
```
___
*[`crates/starknet_api/src/transaction/fields.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OAqZck86ujtBiQ1Hy9f:-OAqZck86ujtBiQ1Hy9g:bkn55lp) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca40e429c12bd04c81a7f66756013c7a877b13b6/crates/starknet_api/src/transaction/fields.rs#L1)):*
> ```XML
> use std::collections::BTreeMap;
> ```

What do you think about these names? Are they better names?
`transaction_components.rs`
`transaction_structs.rs`
`transaction_inner.rs`



_Code quote:_
```XML
use std::collections::BTreeMap;
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1732)* status: 0 of 116 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @MohammadNassar1)

___
*[`crates/starknet_api/src/transaction.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OAqcapK9mHQtT7POziu:-OAqmNCp9Kj6Y9p5QJj1:b7rtr96) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca40e429c12bd04c81a7f66756013c7a877b13b6/crates/starknet_api/src/transaction.rs#L118)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please move this struct as well.
</blockquote></details>

I thought about it!

1. Let us not deal with this in this PR - it is big enough as it is.
2. This struct is used only for transaction hash calculation - as an add on to transaction version. I think this one should be in a different file related to transaction hash.
___
*[`crates/starknet_api/src/transaction.rs` line 716 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OAqclj1-efEmU_P9ypC:-OAqmuYX9Ienlg6OID6V:b-pl1l2h) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca40e429c12bd04c81a7f66756013c7a877b13b6/crates/starknet_api/src/transaction.rs#L716)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

This as well?
</blockquote></details>

This is not a field related to transactions. This is used as an output of the execution.
___
*[`crates/starknet_api/src/transaction.rs` line 843 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OAqcunS4meN6G0uL6kg:-OAqnBCl93AQ_GidEvle:b-lspkc6) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca40e429c12bd04c81a7f66756013c7a877b13b6/crates/starknet_api/src/transaction.rs#L843)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

these as well?
</blockquote></details>

About almost all structs mentioned - I suggest creating a file for L1<-> L2 messages in a different PR.

About `TransactionOffsetInBlock` - I suspect it is closer related to `TransactionReceipt` - as they are both related to execution output (I think... I am not sure - I am sure these are not fields of a transaction).
___
*[`crates/starknet_api/src/transaction/fields.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OAqZck86ujtBiQ1Hy9f:-OAqnsYAB7EJfyqlzr-3:b-hei50y) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca40e429c12bd04c81a7f66756013c7a877b13b6/crates/starknet_api/src/transaction/fields.rs#L1)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

What do you think about these names? Are they better names?
`transaction_components.rs`
`transaction_structs.rs`
`transaction_inner.rs`
</blockquote></details>

`transaction_components.rs` is my favorite so far.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1732)* status: 0 of 116 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @MohammadNassar1)

___
*[`crates/starknet_api/src/transaction/fields.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OAqqmLI8GCT3ykifm6c:-OAqqmLI8GCT3ykifm6d:b-r5uwt6) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca40e429c12bd04c81a7f66756013c7a877b13b6/crates/starknet_api/src/transaction/fields.rs#L16)):*
> ```XML
> // TODO(Noa, 14/11/2023): Replace QUERY_VERSION_BASE_BIT with a lazy calculation.
> //      pub static QUERY_VERSION_BASE: Lazy<Felt> = ...
> pub const QUERY_VERSION_BASE_BIT: u32 = 128;
> ```

Related to tx version and tx hash...



_Code quote:_
```XML
// TODO(Noa, 14/11/2023): Replace QUERY_VERSION_BASE_BIT with a lazy calculation.
//      pub static QUERY_VERSION_BASE: Lazy<Felt> = ...
pub const QUERY_VERSION_BASE_BIT: u32 = 128;
```
___
*[`crates/starknet_api/src/transaction/fields.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OAqqy4CARrGRHj0n4BB:-OAqqy4CARrGRHj0n4BC:b-r5uwt6) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca40e429c12bd04c81a7f66756013c7a877b13b6/crates/starknet_api/src/transaction/fields.rs#L129)):*
> ```XML
>     /// [TransactionVersion] constant that's equal to 3.
>     pub const THREE: Self = { Self(Felt::THREE) };
> }
> ```

Related to tx version and tx hash...



_Code quote:_
```XML
/// A transaction version.
#[derive(
    Debug,
    Copy,
    Clone,
    Default,
    Eq,
    PartialEq,
    Hash,
    Deserialize,
    Serialize,
    PartialOrd,
    Ord,
    derive_more::Deref,
)]
pub struct TransactionVersion(pub Felt);

impl TransactionVersion {
    /// [TransactionVersion] constant that's equal to 0.
    pub const ZERO: Self = { Self(Felt::ZERO) };

    /// [TransactionVersion] constant that's equal to 1.
    pub const ONE: Self = { Self(Felt::ONE) };

    /// [TransactionVersion] constant that's equal to 2.
    pub const TWO: Self = { Self(Felt::TWO) };

    /// [TransactionVersion] constant that's equal to 3.
    pub const THREE: Self = { Self(Felt::THREE) };
}
```

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1732)* status: 0 of 116 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware and @dorimedini-starkware)

___
*[`crates/starknet_api/src/transaction.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OAqcapK9mHQtT7POziu:-OAqsjFx4bLZdlNH32-t:brxp9sq) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca40e429c12bd04c81a7f66756013c7a877b13b6/crates/starknet_api/src/transaction.rs#L118)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I thought about it!

1. Let us not deal with this in this PR - it is big enough as it is.
2. This struct is used only for transaction hash calculation - as an add on to transaction version. I think this one should be in a different file related to transaction hash.
</blockquote></details>

Sounds good.
___
*[`crates/starknet_api/src/transaction.rs` line 716 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OAqclj1-efEmU_P9ypC:-OAqslfUDdWOdqFrrHpn:bqog7zb) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca40e429c12bd04c81a7f66756013c7a877b13b6/crates/starknet_api/src/transaction.rs#L716)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This is not a field related to transactions. This is used as an output of the execution.
</blockquote></details>

Agree.
___
*[`crates/starknet_api/src/transaction.rs` line 843 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OAqcunS4meN6G0uL6kg:-OAqrmb6AXl0F6AtpSc7:b-91r395) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca40e429c12bd04c81a7f66756013c7a877b13b6/crates/starknet_api/src/transaction.rs#L843)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

About almost all structs mentioned - I suggest creating a file for L1<-> L2 messages in a different PR.

About `TransactionOffsetInBlock` - I suspect it is closer related to `TransactionReceipt` - as they are both related to execution output (I think... I am not sure - I am sure these are not fields of a transaction).
</blockquote></details>

Why do we need a new file for `l1 messages`?
Why it's different from other fields (e.g. fee).

I agree that `TxOffset..` is unrelated.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1732)* status: 0 of 116 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @MohammadNassar1)

___
*[`crates/starknet_api/src/transaction.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OAqcapK9mHQtT7POziu:-OArlR9d9yIbfszyTzyv:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca40e429c12bd04c81a7f66756013c7a877b13b6/crates/starknet_api/src/transaction.rs#L118)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Sounds good.
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/transaction.rs` line 716 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OAqclj1-efEmU_P9ypC:-OAr1_tmCJDJvBeb0p1Z:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca40e429c12bd04c81a7f66756013c7a877b13b6/crates/starknet_api/src/transaction.rs#L716)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Agree.
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/transaction.rs` line 843 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OAqcunS4meN6G0uL6kg:-OAr1ewe7I_KcJwIwh9B:b8hdv4u) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca40e429c12bd04c81a7f66756013c7a877b13b6/crates/starknet_api/src/transaction.rs#L843)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why do we need a new file for `l1 messages`?
Why it's different from other fields (e.g. fee).

I agree that `TxOffset..` is unrelated.
</blockquote></details>

About something like `l1 messages`:
I am not an expert about these type of fields which is why:
1. I did not want to move them to this file if I was not sure they belonged there.
2. Again - this PR is big enough as it is - let us deal with them in a different PR.

Added a TODO.
___
*[`crates/starknet_api/src/transaction/fields.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OAqZck86ujtBiQ1Hy9f:-OAvS3qbCFA6vRqIZICV:b-7cu8rd) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca40e429c12bd04c81a7f66756013c7a877b13b6/crates/starknet_api/src/transaction/fields.rs#L1)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

`transaction_components.rs` is my favorite so far.
</blockquote></details>

In rust - members of a struct [are called fields](https://doc.rust-lang.org/book/ch05-01-defining-structs.html#defining-and-instantiating-structs).
@ShahakShama seems to prefer this name. Other people I asked don't have any input.

**Comment by ArniStarkware** [comment]
*[`crates/starknet_api/src/transaction/fields.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OAqqmLI8GCT3ykifm6c:-OB5SOusBoHdvdCT4b6s:b-3kt8fv) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca40e429c12bd04c81a7f66756013c7a877b13b6/crates/starknet_api/src/transaction/fields.rs#L16)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Related to tx version and tx hash...
</blockquote></details>

Now not a part of this PR. In a Future PR we will handle:
1. TransactionVersion
2. TransactionHash

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1732)* status: 0 of 117 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @MohammadNassar1)

___
*[`crates/starknet_api/src/transaction/fields.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OAqqy4CARrGRHj0n4BB:-OB5S_So0mq0tzTMDBHK:b-edsopp) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca40e429c12bd04c81a7f66756013c7a877b13b6/crates/starknet_api/src/transaction/fields.rs#L129)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Related to tx version and tx hash...
</blockquote></details>

Now not a part of this PR. In a future PR we will have a file dedicated to tx version.

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 116 files at r3, 117 of 117 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1732)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dorimedini-starkware)

___
*[`crates/l1-provider/src/lib.rs` line 45 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OB6cb820VL79tet328K:-OB6cb820VL79tet328L:bfw1wxk) ([raw file](https://github.com/starkware-libs/sequencer/blob/20845272bcb2c7c7bf9caa0347859febbecb2da1/crates/l1-provider/src/lib.rs#L45)):*
> ```XML
>         todo!(
>             "Purges txs from internal buffers, if was proposer clear staging buffer, 
>             reset state to Pending until we get proposing/validating notice from consensus."
> ```

What's this change?



_Code quote:_
```XML
            "Purges txs from internal buffers, if was proposer clear staging buffer,
            reset state to Pending until we get proposing/validating notice from consensus."
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1732)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/l1-provider/src/lib.rs` line 45 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1732#-OB6cb820VL79tet328K:-OB6jPz1AH0DyIZCL769:bhcu5en) ([raw file](https://github.com/starkware-libs/sequencer/blob/20845272bcb2c7c7bf9caa0347859febbecb2da1/crates/l1-provider/src/lib.rs#L45)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

What's this change?
</blockquote></details>

The autoformatter added this change. Reverting. 
Out of scope for this PR.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1732)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 4 of 114 files at r6, 113 of 113 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1732)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @MohammadNassar1)

**Pull request merged**
