### PR TITLE
chore(mempool): add gas price threshold to transaction queue content

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1432)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1432)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1432#-O9F2DoTCf5z2lVeT4vC:-O9F2DoU7AyTyMTb36SG:b2ati14) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea0df1ecb9119900383322480708f4df7a3dc5c0/crates/mempool/src/transaction_queue_test_utils.rs#L20)):*
> ```XML
> 
> impl TransactionQueueContent {
>     pub fn assert_eq(&self, tx_queue: &TransactionQueue) {
> ```

Why don't we need to add an assertion for the gas_price_threshold?



_Code quote:_
```XML
assert_eq
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1432)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1432#-O9F2DoTCf5z2lVeT4vC:-O9F6rqj4tMv3WW7R4RG:bgacgk9) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea0df1ecb9119900383322480708f4df7a3dc5c0/crates/mempool/src/transaction_queue_test_utils.rs#L20)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Why don't we need to add an assertion for the gas_price_threshold?
</blockquote></details>

Good question!

The gas price threshold isn't changed within the mempool code—it only updates through the `update_gas_price_threshold` API, which is tested separately (still in a PR). Since no logic updates it, there's no need to assert its value.

I have added a docstr about that:



_Code snippet:_
```XML
/// Note: gas price threshold is only used for building the (non-test) queue struct.
```

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1432#-:-O9FBgZ3CBn8NykX9Yxp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1432)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1432#-O9FCItt7tArP_rQj56a:-O9FCItt7tArP_rQj56b:b-vylicl) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea0df1ecb9119900383322480708f4df7a3dc5c0/crates/mempool/src/transaction_queue_test_utils.rs#L97)):*
> ```XML
>         self.priority_queue.is_none()
>             && self.pending_queue.is_none()
>             && self.gas_price_threshold.is_none()
> ```

Is there a more idiomatic way? Some similar to Python's `any(...)`.



_Code quote:_
```XML
        self.priority_queue.is_none()
            && self.pending_queue.is_none()
            && self.gas_price_threshold.is_none()
```

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1432)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1432)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1432#-O9FCItt7tArP_rQj56a:-O9FEAVs-8vI2Swc0irp:b-mumaxu) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea0df1ecb9119900383322480708f4df7a3dc5c0/crates/mempool/src/transaction_queue_test_utils.rs#L97)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is there a more idiomatic way? Some similar to Python's `any(...)`.
</blockquote></details>

In Rust, there is `all`, which iterates over the elements and verifies that they satisfy the condition. See the below example, and please let me know if you think it's more natural than the original code.

I can't use `[self.priority_queue, self.pending_queue, self.gas_price_threshold]` directly because the elements are of different types.



_Code snippet:_
```XML
fn is_default(&self) -> bool {
    [self.priority_queue.is_none(), self.pending_queue.is_none(), self.gas_price_threshold.is_none()]
        .iter()
        .all(|&x| x)
}
```

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1432#-:-O9FHF2WETuH7G9yagD0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
