### PR TITLE
test(mempool): commit_block removes transaction from tx queues

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/583)

### CODE REVIEW

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/583)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 699 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/583#-O5Hq1r-BYBIQvfe5wvT:-O5Hq1r-BYBIQvfe5wvU:bsbqb3y) ([raw file](https://github.com/starkware-libs/sequencer/blob/027bef42afcee63f1169304cabc58d1849e7c9cb/crates/mempool/src/mempool_test.rs#L699)):*
> ```XML
> 
> #[rstest]
> #[case::test_commit_block_with_low_gas_price_thr(100)]
> ```

why not threshold?



_Code quote:_
```XML
thr
```
___
*[`crates/mempool/src/mempool_test.rs` line 706 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/583#-O5HqJNa6ogdyHr6jK9q:-O5HqJNa6ogdyHr6jK9r:byqg52c) ([raw file](https://github.com/starkware-libs/sequencer/blob/027bef42afcee63f1169304cabc58d1849e7c9cb/crates/mempool/src/mempool_test.rs#L706)):*
> ```XML
> 
>     let pool_txs = [input_tx.tx.clone()];
>     let queue_txs = [TransactionReference::new(&input_tx.tx)];
> ```

switch order to avoid clone



_Code quote (i):_
```XML
    let pool_txs = [input_tx.tx.clone()];
    let queue_txs = [TransactionReference::new(&input_tx.tx)];
```



_Code snippet (ii):_
```XML
    let queue_txs = [TransactionReference::new(&input_tx.tx)];
    let pool_txs = [input_tx.tx];
```
___
*[`crates/mempool/src/mempool_test.rs` line 707 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/583#-O5HqdzKEknbQhL19azE:-O5HqdzL1lPIcglP8V59:b-ha2efw) ([raw file](https://github.com/starkware-libs/sequencer/blob/027bef42afcee63f1169304cabc58d1849e7c9cb/crates/mempool/src/mempool_test.rs#L707)):*
> ```XML
>     let pool_txs = [input_tx.tx.clone()];
>     let queue_txs = [TransactionReference::new(&input_tx.tx)];
>     let mut mempool: Mempool = MempoolContent::new(pool_txs, queue_txs).into();
> ```

why using `new` when we only check the queue?



_Code quote:_
```XML
new
```
___
*[`crates/mempool/src/mempool_test.rs` line 715 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/583#-O5Hpuv7B4epDrh8i3rN:-O5Hpuv7B4epDrh8i3rO:b-3qgzjn) ([raw file](https://github.com/starkware-libs/sequencer/blob/027bef42afcee63f1169304cabc58d1849e7c9cb/crates/mempool/src/mempool_test.rs#L715)):*
> ```XML
>         HashMap::from([(contract_address!("0x0"), AccountState { nonce: Nonce(felt!(0_u16)) })]);
>     assert!(mempool.commit_block(state_changes).is_ok());
> ```

// Assert.

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/583)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/583#-:-O5S6c2p5bwosiPXyRMz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/583)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 699 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/583#-O5Hq1r-BYBIQvfe5wvT:-O5SOljU0_WSD3nTwgxK:b-j8g73c) ([raw file](https://github.com/starkware-libs/sequencer/blob/027bef42afcee63f1169304cabc58d1849e7c9cb/crates/mempool/src/mempool_test.rs#L699)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why not threshold?
</blockquote></details>

seconded
___
*[`crates/mempool/src/mempool_test.rs` line 713 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/583#-O5SQ2B85adK-3zXeyp3:-O5SQ2B938WfQLNNoDkd:b-xgfbcc) ([raw file](https://github.com/starkware-libs/sequencer/blob/91723c274c4bb7f1d5ec8c1c38def26cef862a18/crates/mempool/src/mempool_test.rs#L713)):*
> ```XML
>     let state_changes =
>         HashMap::from([(contract_address!("0x0"), AccountState { nonce: Nonce(felt!(0_u16)) })]);
>     assert!(mempool.commit_block(state_changes).is_ok());
> ```

What is this assert testing? Does this depend on the threshold value?



_Code quote:_
```XML
    assert!(mempool.commit_block(state_changes).is_ok());
```
___
*[`crates/mempool/src/mempool_test.rs` line 718 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/583#-O5SQlda2f6Y_pj7zKfM:-O5SQlda2f6Y_pj7zKfN:b-y2sd4l) ([raw file](https://github.com/starkware-libs/sequencer/blob/91723c274c4bb7f1d5ec8c1c38def26cef862a18/crates/mempool/src/mempool_test.rs#L718)):*
> ```XML
>     mempool._update_gas_price_threshold(0);
>     let expected_mempool_content = MempoolContent::with_queue([]);
>     expected_mempool_content.assert_eq_queue_content(&mempool);
> ```

The mempool queue is empty for both cases?

Why do we need to reset the price threshold? i saw the TODO, but I'm not sure I get it



_Code quote:_
```XML
    mempool._update_gas_price_threshold(0);
    let expected_mempool_content = MempoolContent::with_queue([]);
    expected_mempool_content.assert_eq_queue_content(&mempool);
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/583)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 699 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/583#-O5SS27w85TXD4N8_WiV:-O5SS27xA8Sd2q-Ex4i6:biv473j) ([raw file](https://github.com/starkware-libs/sequencer/blob/91723c274c4bb7f1d5ec8c1c38def26cef862a18/crates/mempool/src/mempool_test.rs#L699)):*
> ```XML
> #[rstest]
> #[case::test_commit_block_with_low_gas_price_thr(100)]
> #[case::test_commit_block_with_high_gas_price_thr(1000000000000)]
> ```

Do these correspond with the bounds that Noam mentioned? 
I'm really starting to think that these bounds need to be consts somewhere, lets decide after the meeting with Elin, I prefer not having magic numbers for these values, especially if they might be out of bounds.



_Code quote:_
```XML
#[case::test_commit_block_with_low_gas_price_thr(100)]
#[case::test_commit_block_with_high_gas_price_thr(1000000000000)]
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/583)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 713 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/583#-O5STftn0epIUlnkefEM:-O5STftoAFUXRCYDgkNw:b3zs96v) ([raw file](https://github.com/starkware-libs/sequencer/blob/91723c274c4bb7f1d5ec8c1c38def26cef862a18/crates/mempool/src/mempool_test.rs#L713)):*
> ```XML
>     let state_changes =
>         HashMap::from([(contract_address!("0x0"), AccountState { nonce: Nonce(felt!(0_u16)) })]);
>     assert!(mempool.commit_block(state_changes).is_ok());
> ```

assert is_ok is hard to debug, only shows `false` in the trace instead of the error.
I used to use assert+is_ok myself until Arni told me about that issue



_Suggestion:_
```XML
    assert_eq!(mempool.commit_block(state_changes), Ok(()));
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/583)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 699 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/583#-O5SS27w85TXD4N8_WiV:-O5gXqs2BpkgOY2cLeei:b7oxnp3) ([raw file](https://github.com/starkware-libs/sequencer/blob/91723c274c4bb7f1d5ec8c1c38def26cef862a18/crates/mempool/src/mempool_test.rs#L699)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

used the max_price values.
A legal value that is above the min defined by Noam.
</blockquote></details>

I'm confused a bit by this change, the difference between low and high is 2? Also the minimum gas threshold is called `VALID_...`? why not MIN?
___
*[`crates/mempool/src/mempool_test.rs` line 713 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/583#-O5SQ2B85adK-3zXeyp3:-O5gWZOi0izV3wTGspzS:b-wndytb) ([raw file](https://github.com/starkware-libs/sequencer/blob/91723c274c4bb7f1d5ec8c1c38def26cef862a18/crates/mempool/src/mempool_test.rs#L713)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Here the test checks that commit_blocks, updates the correct queue.
In the first case, it removes from the first queue, in the second case, it removes from the second queue.
</blockquote></details>

I still don't understand how this assert checks the things you mentioned.

The assert is testing that commit_block returns OK, which implies that the errors given from commit_block are significant to what you're trying to test. If the assert is checking that the correct value is in the queue, does that mean that the errors will tell us how the correct value isn't being updated in the queue?
___
*[`crates/mempool/src/mempool_test.rs` line 718 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/583#-O5SQlda2f6Y_pj7zKfM:-O5gX4SV68Z9WVyFPR05:b-wkoh0n) ([raw file](https://github.com/starkware-libs/sequencer/blob/91723c274c4bb7f1d5ec8c1c38def26cef862a18/crates/mempool/src/mempool_test.rs#L718)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Since `MempoolContent` doesn't support `gas_price_threshold` yet (that's what I meant in the TODO).
</blockquote></details>

Can we add support to gas_price_threshold? of is it waiting on something.

If we can then that should have been introduced before this test was.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/583)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 699 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/583#-O5SS27w85TXD4N8_WiV:-O5hGDz98Lr4yLO6oMrY:bidru5m) ([raw file](https://github.com/starkware-libs/sequencer/blob/91723c274c4bb7f1d5ec8c1c38def26cef862a18/crates/mempool/src/mempool_test.rs#L699)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I'm confused a bit by this change, the difference between low and high is 2? Also the minimum gas threshold is called `VALID_...`? why not MIN?
</blockquote></details>

`VALID_...` represents the gas price of the transaction (not the minimum threshold). In this test, I've covered two scenarios: one where the threshold is above the transaction's gas price (`VALID... + 1`), and another where the threshold is below it (`VALID... - 1`).

I do not thin that the difference between low and high has any meaning.
___
*[`crates/mempool/src/mempool_test.rs` line 713 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/583#-O5SQ2B85adK-3zXeyp3:-O5hHpaO3ZDuN-K2zQZA:b-280kyk) ([raw file](https://github.com/starkware-libs/sequencer/blob/91723c274c4bb7f1d5ec8c1c38def26cef862a18/crates/mempool/src/mempool_test.rs#L713)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I still don't understand how this assert checks the things you mentioned.

The assert is testing that commit_block returns OK, which implies that the errors given from commit_block are significant to what you're trying to test. If the assert is checking that the correct value is in the queue, does that mean that the errors will tell us how the correct value isn't being updated in the queue?
</blockquote></details>

Sorry, I wasn't clear.

This assert is just verifying that `commit_block` completed successfully. The assert with the mempool content ensures that the queues were updated as expected.
___
*[`crates/mempool/src/mempool_test.rs` line 718 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/583#-O5SQlda2f6Y_pj7zKfM:-O5hIfty8xN3ffGNGtbK:bkym7qg) ([raw file](https://github.com/starkware-libs/sequencer/blob/91723c274c4bb7f1d5ec8c1c38def26cef862a18/crates/mempool/src/mempool_test.rs#L718)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can we add support to gas_price_threshold? of is it waiting on something.

If we can then that should have been introduced before this test was.
</blockquote></details>

It's actually not that straightforward. The current `mempoolContent` uses an iterator over transaction references. I need to discuss this change with the team before proceeding.

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/583)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @elintul and @giladchase)

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/583)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

**Comment by MohammadNassar1** [comment]
I am closing these PRs until MempoolContent supports two queues and gas price threshold.

**Pull request closed without merging**
