### PR TITLE
chore(starknet_consensus_manager): set proposer address in propose block input

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2346?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2346** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2346?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2346?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2345** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2345?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2342** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2342?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2238](https://github.com/starkware-libs/sequencer/pull/2238) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2238?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2341** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2341?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2340** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2340?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2339** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2339?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2237** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2237?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2246** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2246?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2230](https://github.com/starkware-libs/sequencer/pull/2230) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2230?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2245** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2245?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2244** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2244?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2269** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2269?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2243** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2243?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ArniStarkware** [comment]
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 293 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2346#-OCnRL8rBW4xA4F8_WKW:-OCnRL8s329Cry_GuL6y:b99mvmr) ([raw file](https://github.com/starkware-libs/sequencer/blob/8049c6489556748190466b0c302f0c3ce54ec895/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L293)):*
> ```XML
>             None => true,
>         };
>         if condition {
> ```

remove, this is not a part of this PR.



_Code quote:_
```XML
    ) {
        let condition = match self.current_height {
            Some(h) => h < height,
            None => true,
        };
        if condition {
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2346)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @alonh5, @ArniStarkware, and @dan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 122 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2346#-ODBWVIqEPfvifmxu4HU:-ODBWVIqEPfvifmxu4HV:bahqg41) ([raw file](https://github.com/starkware-libs/sequencer/blob/b6a3940ab3a7fe2966a3ccfc4f1bc2e6645a1683/crates/sequencing/papyrus_consensus/src/types.rs#L122)):*
> ```XML
>         round: Round,
>         proposer: ValidatorId,
>     );
> ```

Why would I pass this here? The node's ID is set on startup, not every round.



_Code quote:_
```XML
    async fn set_height_and_round(
        &mut self,
        height: BlockNumber,
        round: Round,
        proposer: ValidatorId,
    );
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2346)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @alonh5, @ArniStarkware, and @dan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 122 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2346#-ODBWVIqEPfvifmxu4HU:-ODBWy-N01NLYixrQlDR:bxqv8za) ([raw file](https://github.com/starkware-libs/sequencer/blob/b6a3940ab3a7fe2966a3ccfc4f1bc2e6645a1683/crates/sequencing/papyrus_consensus/src/types.rs#L122)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why would I pass this here? The node's ID is set on startup, not every round.
</blockquote></details>

I think what you want is to add the proposer to `self.queued_proposals`

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2346)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @alonh5, @dan-starkware, and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 122 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2346#-ODBWVIqEPfvifmxu4HU:-ODBvQNPESY3jw2qGDNW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/38d7da875c89b34afc04c6ffa27f53e314146ec8/crates/sequencing/papyrus_consensus/src/types.rs#L122)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I think what you want is to add the proposer to `self.queued_proposals`
</blockquote></details>

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 9 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2346)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5 and @dan-starkware)

**Pull request merged**
