### PR TITLE
chore(blockifier): add gas cost to bultin price array

### PR DESCRIPTION
**Pull request by meship-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/514)

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/514)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4iDmrNA9hqb8NceCQS:-O4iDmrO-XJzAFaXKPwZ:bxjndc0) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3d2d512355e7764973c73de22609106deadc7e/crates/blockifier/src/execution/entry_point_execution.rs#L204)):*
> ```XML
>         MaybeRelocatable::from(500),  // Posidon
>         MaybeRelocatable::from(234),  // AddMod
>         MaybeRelocatable::from(616),  // MulMod
> ```

Please define those constants in the versioned constant file and use it here



_Code quote:_
```XML
        MaybeRelocatable::from(4130), // Pesetsen
        MaybeRelocatable::from(594),  // Bitwise
        MaybeRelocatable::from(4166), // EcOp
        MaybeRelocatable::from(500),  // Posidon
        MaybeRelocatable::from(234),  // AddMod
        MaybeRelocatable::from(616),  // MulMod
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 210 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4iDwjC9v3zcQtadjve:-O4iDwjC9v3zcQtadjvf:b38eaer) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3d2d512355e7764973c73de22609106deadc7e/crates/blockifier/src/execution/entry_point_execution.rs#L210)):*
> ```XML
>     // for _i in 0..20 {
>     //     data.push(MaybeRelocatable::from(0));
>     // }
> ```

Please delete :)



_Code quote:_
```XML
    // // TODO(spapini): Put real costs here.
    // for _i in 0..20 {
    //     data.push(MaybeRelocatable::from(0));
    // }
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4iE2eqDAm3SvHTzcuK:-O4iE2eqDAm3SvHTzcuL:b-dmeyn1) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3d2d512355e7764973c73de22609106deadc7e/crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs#L12)):*
> ```XML
> use crate::test_utils::{trivial_external_entry_point_new, CairoVersion, BALANCE};
> 
> #[test_case(FeatureContract::TestContract(CairoVersion::Cairo1), 17051678; "VM")]
> ```

Why is that the only test with a gas consumption change? :thinking: 



_Code quote:_
```XML
#[test_case(FeatureContract::TestContract(CairoVersion::Cairo1), 17051678; "VM")]
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/514)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 210 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4iDwjC9v3zcQtadjve:-O4iaI-66X61s3W7siaA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3d2d512355e7764973c73de22609106deadc7e/crates/blockifier/src/execution/entry_point_execution.rs#L210)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please delete :)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4iE2eqDAm3SvHTzcuK:-O4iMN622N8uk8QxwJQG:b-bdfzev) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3d2d512355e7764973c73de22609106deadc7e/crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs#L12)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is that the only test with a gas consumption change? :thinking:
</blockquote></details>

I think it is because this is the only syscalls aside from deploy that uses a builtin other than range check, and because I rebased it over main, we have not tested deploy yet. I'll try to rebase over the test deploy gas cost and see what will happen.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/514)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4iE2eqDAm3SvHTzcuK:-O4iaLqN4G0hg1wvr1Ux:b-2c20er) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3d2d512355e7764973c73de22609106deadc7e/crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs#L12)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I think it is because this is the only syscalls aside from deploy that uses a builtin other than range check, and because I rebased it over main, we have not tested deploy yet. I'll try to rebase over the test deploy gas cost and see what will happen.
</blockquote></details>

it looks like that is not the solution, as deploy gas cost has not changed

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/514)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4iDmrNA9hqb8NceCQS:-O4jOq6VE_w_vf6GQ40M:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3d2d512355e7764973c73de22609106deadc7e/crates/blockifier/src/execution/entry_point_execution.rs#L204)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please define those constants in the versioned constant file and use it here
</blockquote></details>

Done.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/514)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4iE2eqDAm3SvHTzcuK:-O4oqzyx1kjRZyvmEcLk:bbb1ubo) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3d2d512355e7764973c73de22609106deadc7e/crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs#L12)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

it looks like that is not the solution, as deploy gas cost has not changed
</blockquote></details>

@ilyalesokhin-starkware  Do you have any idea why the cost of the secp might change as a result of updating the builtins price array?  
Also, the price from r1 is the price after updating the builtins array and before updating the syscall gas_cost
and the price in r2 is after updating both the gas cost and builtin array prices.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4iE2eqDAm3SvHTzcuK:-O4paMhNAyj_gxer_TiG:b-rl0xxu) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3d2d512355e7764973c73de22609106deadc7e/crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs#L12)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

@ilyalesokhin-starkware  Do you have any idea why the cost of the secp might change as a result of updating the builtins price array?  
Also, the price from r1 is the price after updating the builtins array and before updating the syscall gas_cost
and the price in r2 is after updating both the gas cost and builtin array prices.
</blockquote></details>

Yes, contracts use that array when updating the gas counter.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4iE2eqDAm3SvHTzcuK:-O4suT1ZCCSrt3mLtTs-:bqdwloo) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3d2d512355e7764973c73de22609106deadc7e/crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs#L12)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Is there a resone Only sekpk1 was affected? It sounds like the call contract syscalls should have been affected as well.
</blockquote></details>

Do the other tests use builtins?

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/514)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4iE2eqDAm3SvHTzcuK:-O4sxfr0-kuNlaTuhgrm:bugmax1) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3d2d512355e7764973c73de22609106deadc7e/crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs#L12)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Do the other tests use builtins?
</blockquote></details>

I am not sure what you mean by asking if the test uses builtins, but from the os resources, the only syscalls that use builtins that are not rangecheck are deployed sha256 and keccak; as for the code in the test contract, I don't see much difference between secpk1 and secpr1.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4iE2eqDAm3SvHTzcuK:-O4t0enF-6GkeVBu9paI:bnc2zdc) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3d2d512355e7764973c73de22609106deadc7e/crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs#L12)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I am not sure what you mean by asking if the test uses builtins, but from the os resources, the only syscalls that use builtins that are not rangecheck are deployed sha256 and keccak; as for the code in the test contract, I don't see much difference between secpk1 and secpr1.
</blockquote></details>

The secp256k1 test calls verify\_eth\_signature which does keccak.
the secpr1 test does not do that.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/514)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4iE2eqDAm3SvHTzcuK:-O4tB1HL7FIGGKz8cH9f:b-lj8v57) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e3d2d512355e7764973c73de22609106deadc7e/crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs#L12)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The secp256k1 test calls verify\_eth\_signature which does keccak.
the secpr1 test does not do that.
</blockquote></details>

Cool that would explain it thanks.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 7 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/514)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @meship-starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 201 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4tIpa2DKSYelEGwMjx:-O4tIpa2DKSYelEGwMjy:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/340623ea75e637ddfd04bbcb4e48c806346e3da6/crates/blockifier/src/execution/entry_point_execution.rs#L201)):*
> ```XML
>     contract_class: &ContractClassV1,
>     read_only_segments: &mut ReadOnlySegments,
>     versioned_constants: &VersionedConstants,
> ```





_Suggestion:_
```XML
    gas_costs: &GasCosts,
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 203 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4tJQ-j3jAYyxmsOysO:-O4tJQ-j3jAYyxmsOysP:bgtxthy) ([raw file](https://github.com/starkware-libs/sequencer/blob/340623ea75e637ddfd04bbcb4e48c806346e3da6/crates/blockifier/src/execution/entry_point_execution.rs#L203)):*
> ```XML
>     versioned_constants: &VersionedConstants,
> ) -> Result<usize, PreExecutionError> {
>     // Create the builtin cost segment, with dummy values.
> ```

Can you please refer to a source that determines the correct order of the builtins?



_Code quote:_
```XML
    // Create the builtin cost segment, with dummy values.
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/514)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 203 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4tJQ-j3jAYyxmsOysO:-O4tcU7v8LCfJy9lwb9L:bjcxyef) ([raw file](https://github.com/starkware-libs/sequencer/blob/340623ea75e637ddfd04bbcb4e48c806346e3da6/crates/blockifier/src/execution/entry_point_execution.rs#L203)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please refer to a source that determines the correct order of the builtins?
</blockquote></details>

I am unsure about adding the function name to the comment, but I think it would be the easiest way to find it.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/514)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @meship-starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 203 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4tJQ-j3jAYyxmsOysO:-O4uYUBU97eG3gYuiNfd:b2m2o8n) ([raw file](https://github.com/starkware-libs/sequencer/blob/340623ea75e637ddfd04bbcb4e48c806346e3da6/crates/blockifier/src/execution/entry_point_execution.rs#L203)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I am unsure about adding the function name to the comment, but I think it would be the easiest way to find it.
</blockquote></details>

I wonder if this method is the what counts (and in that case, consider using it), or the OS itself.
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 211 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4u_nNLEt9TwwFhbw9G:-O4u_nNMA4NKKnA9EmWG:b2msusi) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a2ada114aff030be501a0391c673ed9b36daa4b/crates/blockifier/src/execution/entry_point_execution.rs#L211)):*
> ```XML
>         gas_costs.poseidon_gas_cost,
>         gas_costs.add_mod_gas_cost,
>         gas_costs.mul_mod_gas_cost,
> ```

Those prices are defined in the compiler as well ([here](https://github.com/starkware-libs/cairo/blob/4c43ba3bf0cfc5debc6e63939fa24992846197ca/crates/cairo-lang-runner/src/lib.rs#L136)). 
Why is it needed in the complier? 
Do we need to use the same costs? I suspect that no
@ilyalesokhin-starkware 



_Code quote:_
```XML
        gas_costs.pedersen_gas_cost,
        gas_costs.bitwise_builtin_gas_cost,
        gas_costs.ecop_gas_cost,
        gas_costs.poseidon_gas_cost,
        gas_costs.add_mod_gas_cost,
        gas_costs.mul_mod_gas_cost,
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 211 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4u_nNLEt9TwwFhbw9G:-O5CC-FW9cukhmVxa1lf:bszzmww) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a2ada114aff030be501a0391c673ed9b36daa4b/crates/blockifier/src/execution/entry_point_execution.rs#L211)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Those prices are defined in the compiler as well ([here](https://github.com/starkware-libs/cairo/blob/4c43ba3bf0cfc5debc6e63939fa24992846197ca/crates/cairo-lang-runner/src/lib.rs#L136)). 
Why is it needed in the complier? 
Do we need to use the same costs? I suspect that no
@ilyalesokhin-starkware
</blockquote></details>

The compiler has a framework to run Cairo code without relying on the sequencer, so it needs those prices.
The prices should be the same, but nothing will break if they are different.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 7 of 9 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/514)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/514)* status: 0 of 19 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 203 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4tJQ-j3jAYyxmsOysO:-O5HNSVD5-6QkBCVQD2i:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/340623ea75e637ddfd04bbcb4e48c806346e3da6/crates/blockifier/src/execution/entry_point_execution.rs#L203)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I wonder if this method is the what counts (and in that case, consider using it), or the OS itself.
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
> Reviewed 9 of 10 files at r6, 1 of 10 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/514)* status: 10 of 19 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 211 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4u_nNLEt9TwwFhbw9G:-O5I-Qsr6_Dw4IXRlNSI:b6y3swo) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a2ada114aff030be501a0391c673ed9b36daa4b/crates/blockifier/src/execution/entry_point_execution.rs#L211)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The compiler has a framework to run Cairo code without relying on the sequencer, so it needs those prices.
The prices should be the same, but nothing will break if they are different.
</blockquote></details>

Why should they be the same?
Is the compiler uses it for testing?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 211 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/514#-O4u_nNLEt9TwwFhbw9G:-O5T-Z2K4OLcvGXY0FKy:bbjhhdk) ([raw file](https://github.com/starkware-libs/sequencer/blob/5a2ada114aff030be501a0391c673ed9b36daa4b/crates/blockifier/src/execution/entry_point_execution.rs#L211)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why should they be the same?
Is the compiler uses it for testing?
</blockquote></details>

If the prices are different, then the testing framework would give different gas costs than Starknet.

Yes, The compiler uses it for testing.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 9 of 10 files at r6, 8 of 10 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/514#-:-O5T03S7-qDe3TiOiPqA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Pull request merged**
