### PR TITLE
chore(deployment): cdk8s refactor (#2468)

### PR DESCRIPTION
**Pull request by idan-starkware**
* chore(deployment): get values from sequencer config

* chore(deployment): removed set functions

* chore(deployment): preparation to remove objects.py

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3025)* status: 2 of 16 files reviewed, 1 unresolved discussion (waiting on @idan-starkware)

___
*[`deployments/sequencer/app/service.py` line 117 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3025#-OFN6mEN3paCKDhu3r2I:-OFN6mEN3paCKDhu3r2J:b-gzkv6r) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0af94381b65d102cd1d846a451463d8d6437795/deployments/sequencer/app/service.py#L117)):*
> ```Python
>         config_attr = self.node_config.get(attribute).get('value')
>         if config_attr is None:
>             assert f'Config attribute "{attribute}" is missing.'
> ```

this assert does nothing ATM



_Suggestion:_
```Python
        assert config_attr is not None, f'Config attribute "{attribute}" is missing.'
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3025)* status: 2 of 16 files reviewed, 2 unresolved discussions (waiting on @idan-starkware)

___
*[`deployments/sequencer/services/objects.py` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3025#-OFN76Yl2TFrFFD4DLFo:-OFN76Yl2TFrFFD4DLFp:b-aznopi) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0af94381b65d102cd1d846a451463d8d6437795/deployments/sequencer/services/objects.py#L56)):*
> ```Python
> 
>     def get_config(self):
>         return self.config
> ```

return type annotation



_Code quote:_
```Python
    def get_merged_config(self):
        return self._merged_config()

    def get_config(self):
        return self.config
```

**Review by alon-dotan-starkware — APPROVED** [review]

**Review by idan-starkware — COMMENTED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3025)* status: 14 of 16 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`deployments/sequencer/app/service.py` line 117 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3025#-OFN6mEN3paCKDhu3r2I:-OFS05Yx6oIg5_1Miz6y:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0af94381b65d102cd1d846a451463d8d6437795/deployments/sequencer/app/service.py#L117)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this assert does nothing ATM
</blockquote></details>

Done.
___
*[`deployments/sequencer/services/objects.py` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3025#-OFN76Yl2TFrFFD4DLFo:-OFS053G8dzj_4n9AEMx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0af94381b65d102cd1d846a451463d8d6437795/deployments/sequencer/services/objects.py#L56)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

return type annotation
</blockquote></details>

Done.

**Review by idan-starkware — COMMENTED** [review]
> Reviewed 1 of 16 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3025)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @dorimedini-starkware)

**Review by idan-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3025)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3025#-:-OFS7d_rE8UOfnyf74U7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @idan-starkware)

**Pull request merged**
