### PR TITLE
feat: post artifacts upload run link as a comment

### PR DESCRIPTION
**Pull request by nadin-Starkware**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1519)* status: all files reviewed, 5 unresolved discussions (waiting on @nadin-Starkware)

___
*[`.github/workflows/upload_artifacts_workflow.yml` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9nBkUTAcDZt0HZs8-U:-O9nBkUTAcDZt0HZs8-V:bw600x1) ([raw file](https://github.com/starkware-libs/sequencer/blob/0962f755ed314119835fd5e418819d40a8b82b34/.github/workflows/upload_artifacts_workflow.yml#L34)):*
> ```YAML
>       - name: Set environment variable
>         run: |
>           pr_number=$(gh pr list --head "${{ github.event.workflow_run.head_branch }}" --json number --jq '.[0].number')
> ```

isn't there some nicer context variable you can access here to get the PR number?



_Code quote:_
```YAML
pr_number=$(gh pr list --head "${{ github.event.workflow_run.head_branch }}" --json number --jq '.[0].number')
```
___
*[`.github/workflows/upload_artifacts_workflow.yml` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9nBxw4AFOlAtdRCmNA:-O9nBxw55bmQr6LcHyCv:bi74pzw) ([raw file](https://github.com/starkware-libs/sequencer/blob/0962f755ed314119835fd5e418819d40a8b82b34/.github/workflows/upload_artifacts_workflow.yml#L40)):*
> ```YAML
> 
>       - name: Add a comment to the PR
>         if: env.PR_NUMBER != '' && env.WORKFLOW_LINK != ''
> ```

please add a step with a fallback comment in case the `Set environment variable` phase fails for some reason; i.e. "upload artifacts started, failed to generate link"



_Code quote:_
```YAML
 if: env.PR_NUMBER != '' && env.WORKFLOW_LINK != ''
```
___
*[`.github/workflows/upload_artifacts_workflow.yml` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9nCEVX5-Fj-hEc1Cru:-O9nCEVX5-Fj-hEc1Crv:b-ks6qcm) ([raw file](https://github.com/starkware-libs/sequencer/blob/0962f755ed314119835fd5e418819d40a8b82b34/.github/workflows/upload_artifacts_workflow.yml#L50)):*
> ```YAML
>               owner: context.repo.owner,
>               repo: context.repo.repo,
>               body: `Artifacts upload triggered. View details here: ${workflowLink}`
> ```

why with backticks? non-blocking, in the example I see it's formatted as regular text



_Code quote:_
```YAML
`Artifacts upload triggered. View details here: ${workflowLink}`
```
___
*[`.github/workflows/upload_artifacts_workflow.yml` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9nCNG91u7Jc4YY0sp8:-O9nCNG91u7Jc4YY0sp9:b-x6amsj) ([raw file](https://github.com/starkware-libs/sequencer/blob/0962f755ed314119835fd5e418819d40a8b82b34/.github/workflows/upload_artifacts_workflow.yml#L50)):*
> ```YAML
>               owner: context.repo.owner,
>               repo: context.repo.repo,
>               body: `Artifacts upload triggered. View details here: ${workflowLink}`
> ```

use markdown link please



_Suggestion:_
```YAML
Artifacts upload triggered, view details [here](${workflowLink}).
```
___
*[`.github/workflows/upload_artifacts_workflow.yml` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9nBT12CTYRds4J0CU4:-O9nBT12CTYRds4J0CU5:b-4x59ly) ([raw file](https://github.com/starkware-libs/sequencer/blob/0962f755ed314119835fd5e418819d40a8b82b34/.github/workflows/upload_artifacts_workflow.yml#L51)):*
> ```YAML
>               repo: context.repo.repo,
>               body: `Artifacts upload triggered. View details here: ${workflowLink}`
>             })
> ```

please move these to be the first two steps of the job; I'd like to see the link before `build_native_in_docker` starts (or ends)



_Code quote:_
```YAML
      # Set environment variable for commenting the uploaded file URL.
      - name: Set environment variable
        run: |
          pr_number=$(gh pr list --head "${{ github.event.workflow_run.head_branch }}" --json number --jq '.[0].number')
          echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV
          echo "WORKFLOW_LINK=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Add a comment to the PR
        if: env.PR_NUMBER != '' && env.WORKFLOW_LINK != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const workflowLink = process.env.WORKFLOW_LINK;
            github.rest.issues.createComment({
              issue_number: process.env.PR_NUMBER,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Artifacts upload triggered. View details here: ${workflowLink}`
            })
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1519)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`.github/workflows/upload_artifacts_workflow.yml` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9nBkUTAcDZt0HZs8-U:-O9nCgxu-PDy1dprvcuj:brbdyh0) ([raw file](https://github.com/starkware-libs/sequencer/blob/0962f755ed314119835fd5e418819d40a8b82b34/.github/workflows/upload_artifacts_workflow.yml#L34)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

isn't there some nicer context variable you can access here to get the PR number?
</blockquote></details>

Not that I found
___
*[`.github/workflows/upload_artifacts_workflow.yml` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9nBxw4AFOlAtdRCmNA:-O9nEIlm6mW0zUncb8Xl:b5xgvjv) ([raw file](https://github.com/starkware-libs/sequencer/blob/0962f755ed314119835fd5e418819d40a8b82b34/.github/workflows/upload_artifacts_workflow.yml#L40)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a step with a fallback comment in case the `Set environment variable` phase fails for some reason; i.e. "upload artifacts started, failed to generate link"
</blockquote></details>

The condition && env.WORKFLOW_LINK != '' is unnecessary, as the variable will always be present. If it's not, the comment will simply not include the URL, and users will understand that something went wrong. Additionally, if the step to set environment variables fails, we won't be able to create the comment at all since those variables are required for posting the comment in the first place.
___
*[`.github/workflows/upload_artifacts_workflow.yml` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9nCEVX5-Fj-hEc1Cru:-O9nEW7K7RUbl-0yqU4k:b-2szx2b) ([raw file](https://github.com/starkware-libs/sequencer/blob/0962f755ed314119835fd5e418819d40a8b82b34/.github/workflows/upload_artifacts_workflow.yml#L50)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why with backticks? non-blocking, in the example I see it's formatted as regular text
</blockquote></details>

Because of the JSON format, we need to access the variable with backticks.
___
*[`.github/workflows/upload_artifacts_workflow.yml` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9nCNG91u7Jc4YY0sp8:-O9naP15CdGLNw9AWzB5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0962f755ed314119835fd5e418819d40a8b82b34/.github/workflows/upload_artifacts_workflow.yml#L50)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use markdown link please
</blockquote></details>

Done.
___
*[`.github/workflows/upload_artifacts_workflow.yml` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9nBT12CTYRds4J0CU4:-O9nauzX0SUmZbVMXWax:b-s8m2n2) ([raw file](https://github.com/starkware-libs/sequencer/blob/0962f755ed314119835fd5e418819d40a8b82b34/.github/workflows/upload_artifacts_workflow.yml#L51)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please move these to be the first two steps of the job; I'd like to see the link before `build_native_in_docker` starts (or ends)
</blockquote></details>

Need to checkout first, Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1519)* status: all files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

___
*[`.github/workflows/upload_artifacts_workflow.yml` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9nBxw4AFOlAtdRCmNA:-O9nbZuu6aUrranrizTI:b-7k2kqo) ([raw file](https://github.com/starkware-libs/sequencer/blob/0962f755ed314119835fd5e418819d40a8b82b34/.github/workflows/upload_artifacts_workflow.yml#L40)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

The condition && env.WORKFLOW_LINK != '' is unnecessary, as the variable will always be present. If it's not, the comment will simply not include the URL, and users will understand that something went wrong. Additionally, if the step to set environment variables fails, we won't be able to create the comment at all since those variables are required for posting the comment in the first place.
</blockquote></details>

the comment won't appear at all if the `if` is false; it applies to the entire step
___
*[`.github/workflows/upload_artifacts_workflow.yml` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9nbMQ28-w17BHDn0sr:-O9nbMQ28-w17BHDn0ss:b57qeum) ([raw file](https://github.com/starkware-libs/sequencer/blob/ccf3ae255a9095f1ab1652694286368172321422/.github/workflows/upload_artifacts_workflow.yml#L16)):*
> ```YAML
>       - uses: actions/checkout@v4
>         with:
>           ref: ${{ env.COMMIT_SHA }}
> ```

delete (oops)



_Code quote:_
```YAML
      # This workflow is always triggered in `main` branch context, so need to checkout the commit.
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMIT_SHA }}
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1519)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`.github/workflows/upload_artifacts_workflow.yml` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9nBxw4AFOlAtdRCmNA:-O9ncM0pBsF-yE4UJQC3:b-2feo7c) ([raw file](https://github.com/starkware-libs/sequencer/blob/0962f755ed314119835fd5e418819d40a8b82b34/.github/workflows/upload_artifacts_workflow.yml#L40)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the comment won't appear at all if the `if` is false; it applies to the entire step
</blockquote></details>

Exactly. If there is no PR number, there is no pr to comment on
___
*[`.github/workflows/upload_artifacts_workflow.yml` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9nbMQ28-w17BHDn0sr:-O9ncK8MEJk_z-pNxBK4:bwo2e59) ([raw file](https://github.com/starkware-libs/sequencer/blob/ccf3ae255a9095f1ab1652694286368172321422/.github/workflows/upload_artifacts_workflow.yml#L16)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete (oops)
</blockquote></details>

Oops indeed

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1519)* status: all files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`.github/workflows/upload_artifacts_workflow.yml` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9nBxw4AFOlAtdRCmNA:-O9ncszw-dJYvPe2G4na:bii76vk) ([raw file](https://github.com/starkware-libs/sequencer/blob/0962f755ed314119835fd5e418819d40a8b82b34/.github/workflows/upload_artifacts_workflow.yml#L40)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Exactly. If there is no PR number, there is no pr to comment on
</blockquote></details>

ahhh ok
___
*[`.github/workflows/upload_artifacts_workflow.yml` line 49 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9ncvmv92azjckndVbS:-O9ncvmv92azjckndVbT:b-s64gkb) ([raw file](https://github.com/starkware-libs/sequencer/blob/fea51eb764ab7fd788bb67c803c67c56c85dfd11/.github/workflows/upload_artifacts_workflow.yml#L49)):*
> ```YAML
>       - uses: actions/checkout@v4
>         with:
>           ref: ${{ env.COMMIT_SHA }}
> ```

why do you need to checkout again?



_Code quote:_
```YAML
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMIT_SHA }}
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1519)* status: all files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`.github/workflows/upload_artifacts_workflow.yml` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9nBxw4AFOlAtdRCmNA:-O9nd_6v-pDdr6XCd9-r:b1y9rbq) ([raw file](https://github.com/starkware-libs/sequencer/blob/0962f755ed314119835fd5e418819d40a8b82b34/.github/workflows/upload_artifacts_workflow.yml#L40)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ahhh ok
</blockquote></details>

When it's running on post-merge for example

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1519)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`.github/workflows/upload_artifacts_workflow.yml` line 49 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9ncvmv92azjckndVbS:-O9neEyJB1M4-yEEOWUW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fea51eb764ab7fd788bb67c803c67c56c85dfd11/.github/workflows/upload_artifacts_workflow.yml#L49)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do you need to checkout again?
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1519)* status: all files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`.github/workflows/upload_artifacts_workflow.yml` line 52 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9neMpNCKcJcqIBZVWy:-O9neMpNCKcJcqIBZVWz:b-c09min) ([raw file](https://github.com/starkware-libs/sequencer/blob/fea51eb764ab7fd788bb67c803c67c56c85dfd11/.github/workflows/upload_artifacts_workflow.yml#L52)):*
> ```YAML
>       - uses: ./.github/actions/bootstrap
>       - name: Build native blockifier
>         run: ./build_native_in_docker.sh scripts/build_native_blockifier.sh
> ```

done too much :)
revert this deletion..



_Code quote:_
```YAML
      - uses: ./.github/actions/bootstrap
      - name: Build native blockifier
        run: ./build_native_in_docker.sh scripts/build_native_blockifier.sh
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1519)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`.github/workflows/upload_artifacts_workflow.yml` line 52 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-O9neMpNCKcJcqIBZVWy:-O9nejCJ5Pt4R3uZJOIt:b-toe5iz) ([raw file](https://github.com/starkware-libs/sequencer/blob/fea51eb764ab7fd788bb67c803c67c56c85dfd11/.github/workflows/upload_artifacts_workflow.yml#L52)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

done too much :)
revert this deletion..
</blockquote></details>

aaaaaaaa

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1519#-:-O9nfDvz1UYVLIZdwZrs:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Pull request merged**
