### PR TITLE
chore(consensus): remove irrelevant TODO items

### PR DESCRIPTION
**Pull request by guy-starkware**
A few TODOs that I found that are no longer relevant and are removed.

### CODE REVIEW

**Comment by guy-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2671?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2671** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2671?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2671?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2559** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2559?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2533** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2533?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2532** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2532?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2528** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2528?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2526** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2526?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2525** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2525?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2524** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2524?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2518** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2518?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2517** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2517?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2512** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2512?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2510** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2510?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by asmaastarkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2671)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2671)* status: all files reviewed, 3 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/papyrus_protobuf/Cargo.toml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2671#-OErj8oJ0R0vTLSQIcWG:-OErj8oK-J8UnRBr8buG:b-jrx4s8) ([raw file](https://github.com/starkware-libs/sequencer/blob/ddd8259c902801cff6351e909623afc483809e70/crates/papyrus_protobuf/Cargo.toml#L12)):*
> ```TOML
> 
> [dependencies]
> # TODO(Guy): Remove after implementing broadcast streams.
> ```

what were you supposed to remove?



_Code quote:_
```TOML
# TODO(Guy): Remove after implementing broadcast streams.
```
___
*[`crates/papyrus_protobuf/src/consensus.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2671#-OErjJeA7JBgsP-cp0Yp:-OErjJeBEk-ktXTNCzAi:b3kre) ([raw file](https://github.com/starkware-libs/sequencer/blob/ddd8259c902801cff6351e909623afc483809e70/crates/papyrus_protobuf/src/consensus.rs#L116)):*
> ```XML
> {
>     fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
>         // TODO(guyn): add option to display when message is Fin and doesn't have content (PR #1048)
> ```

?



_Code quote:_
```XML
        // TODO(guyn): add option to display when message is Fin and doesn't have content (PR #1048)
```
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2671#-OErjNqwD2SLwptkpzeh:-OErjNqwD2SLwptkpzei:bp4vh2g) ([raw file](https://github.com/starkware-libs/sequencer/blob/ddd8259c902801cff6351e909623afc483809e70/crates/sequencing/papyrus_consensus/src/manager_test.rs#L86)):*
> ```XML
>     let mut sender = mock_network.broadcasted_messages_sender;
> 
>     // TODO(guyn): refactor this test to pass proposals through the correct channels.
> ```

Already done but you didn't delete the TODO?



_Code quote:_
```XML
    // TODO(guyn): refactor this test to pass proposals through the correct channels.
```

**Review by matan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2671)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Review by guy-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2671)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Pull request merged**
