### PR TITLE
refactor(starknet_api): test that changing any field changes the hash

### PR DESCRIPTION
**Pull request by yoavGrs**
[Context](https://reviewable.io/reviews/starkware-libs/sequencer/814#-O6v65yHCuMIIWUWr48W)

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/844)

### CODE REVIEW

**Review by AvivYossef-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/844#-:-O6zyj1g8x7eIiuAjsk1:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/844)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/844#-O72zg8yCpy6Cct3WpLY:-O72zg8yCpy6Cct3WpLZ:b5t6nhp) ([raw file](https://github.com/starkware-libs/sequencer/blob/300eb78e7b4fe079fe61787f8c0bb7118af50cac/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L41)):*
> ```XML
> /// and asserts that the block hash changes as a result.
> macro_rules! test_hash_changes {
>     (header_fields => { $($header_field:ident: $header_value:expr),* }, commitments_fields => { $($commitments_field:ident: $commitments_value:expr),* }) => {
> ```

the advantage of this is that the macro invocation looks more like rust syntax



_Suggestion:_
```XML
(BlockHeaderWithoutHash { $($header_field:ident: $header_value:expr),* }, BlockHeaderCommitments { $
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/844)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/844#-O72zg8yCpy6Cct3WpLY:-O731Lw81z8kklGAoOSB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/300eb78e7b4fe079fe61787f8c0bb7118af50cac/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L41)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the advantage of this is that the macro invocation looks more like rust syntax
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/844)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/844#-O72zg8yCpy6Cct3WpLY:-O737u0WAlCzlw7AohRp:bmz6sy7) ([raw file](https://github.com/starkware-libs/sequencer/blob/300eb78e7b4fe079fe61787f8c0bb7118af50cac/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L41)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you don't need the `=>`; remove it so that the invocation looks like constructing two struct instances and passing them as arguments.

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/844)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/844#-O72zg8yCpy6Cct3WpLY:-O739jc40N1dtRs7JXDX:bjikkn3) ([raw file](https://github.com/starkware-libs/sequencer/blob/300eb78e7b4fe079fe61787f8c0bb7118af50cac/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L41)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you don't need the `=>`; remove it so that the invocation looks like constructing two struct instances and passing them as arguments.
</blockquote></details>

Note that the field `l1_da_mode` of the header doesn't pass into the invocation.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/844#-:-O73LQHlDUtzP-0KRNvh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/844#-O72zg8yCpy6Cct3WpLY:-O73KCVh9XJ5dt6ZGyVI:b-plsxa5) ([raw file](https://github.com/starkware-libs/sequencer/blob/300eb78e7b4fe079fe61787f8c0bb7118af50cac/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L41)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Note that the field `l1_da_mode` of the header doesn't pass into the invocation.
</blockquote></details>

if you pass it explicitly, I think it does:
```
            let header = BlockHeaderWithoutHash {
                l1_da_mode: L1DataAvailabilityMode::Blob,
                $($header_field: $header_value),*
            };
```
if you have `l1_da_mode: L1DataAvailabilityMode::Calldata` as one of the `$header_field: $header_value` pairs, it will overwrite the `Blob`, I think

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/844)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/844#-O72zg8yCpy6Cct3WpLY:-O73OLOK6027Qy6dc0cK:b-nu2oa8) ([raw file](https://github.com/starkware-libs/sequencer/blob/300eb78e7b4fe079fe61787f8c0bb7118af50cac/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L41)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you pass it explicitly, I think it does:
```
            let header = BlockHeaderWithoutHash {
                l1_da_mode: L1DataAvailabilityMode::Blob,
                $($header_field: $header_value),*
            };
```
if you have `l1_da_mode: L1DataAvailabilityMode::Calldata` as one of the `$header_field: $header_value` pairs, it will overwrite the `Blob`, I think
</blockquote></details>

It doesn't overwrites:
```field `l1_da_mode` specified more than once```

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/844)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/844#-O72zg8yCpy6Cct3WpLY:-O73PnR_AOkknc_wC3Sm:b-9uk9nm) ([raw file](https://github.com/starkware-libs/sequencer/blob/300eb78e7b4fe079fe61787f8c0bb7118af50cac/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L41)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

It doesn't overwrites:
```field `l1_da_mode` specified more than once```
</blockquote></details>

even better :)

**Pull request merged**
