### PR TITLE
feat(consensus): send Proposal(None) to the SM instead of InvalidProposal error

### PR DESCRIPTION
**Pull request by asmaastarkware**
- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/147)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/147)* status: all files reviewed, 3 unresolved discussions (waiting on @asmaastarkware and @dorimedini-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/147#-O2tENVg3TRV3-WCu38A:-O2tENVg3TRV3-WCu38B:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/05ab48efcb7802507ec1c65c3fb917437bbe79a9/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L98)):*
> ```XML
>             Ok(block) => block,
>             Err(_) => return self.process_proposal(context, &init, None).await,
>         };
> ```





_Suggestion:_
```XML
x        let block = match block_receiver.await {
           Ok(block) => block,
           // ProposalFin never received from peer.
           Err(_) => return self.process_proposal(context, &init, None).await,
        };
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/147#-O2tET81-YTfU7LO8Dkl:-O2tET820xQuj3WWwFIB:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/05ab48efcb7802507ec1c65c3fb917437bbe79a9/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L103)):*
> ```XML
>             Ok(fin) => fin,
>             Err(_) => return self.process_proposal(context, &init, None).await,
>         };
> ```





_Suggestion:_
```XML
        let fin = match fin_receiver.await {
            Ok(fin) => fin,
            // ProposalFin never received from peer.
            Err(_) => return self.process_proposal(context, &init, None).await,
        };
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/147#-O2tF43UEIX8aCXo63Pj:-O2tF43VBMItSbCbs0Nw:b-n6q1se) ([raw file](https://github.com/starkware-libs/sequencer/blob/05ab48efcb7802507ec1c65c3fb917437bbe79a9/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L125)):*
> ```XML
>             }
>             None => {
>                 // TODO(Asmaa): handle re-proposing
> ```

When I say "re-proposing" I typically mean a node sends out a proposal which was already received (and received a prevote quorum) from another round. Are you referring to that? If so, that should only be relevant when sending a proposal, where this function is for receiving one, right? Maybe the fn name should imply that:
- receive_proposal
- process_inbound_proposal
- etc?



_Code quote:_
```XML
                // TODO(Asmaa): handle re-proposing
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/147)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/147#-O2tENVg3TRV3-WCu38A:-O2tJn5JAGig23qkPgKQ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/05ab48efcb7802507ec1c65c3fb917437bbe79a9/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L98)):*
> ```XML
>             Ok(block) => block,
>             Err(_) => return self.process_proposal(context, &init, None).await,
>         };
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/147#-O2tET81-YTfU7LO8Dkl:-O2tJsLA7caGwzEg8nEx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/05ab48efcb7802507ec1c65c3fb917437bbe79a9/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L103)):*
> ```XML
>             Ok(fin) => fin,
>             Err(_) => return self.process_proposal(context, &init, None).await,
>         };
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/147#-O2tF43UEIX8aCXo63Pj:-O2xKaz7D9cpmID8avhs:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/05ab48efcb7802507ec1c65c3fb917437bbe79a9/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L125)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

When I say "re-proposing" I typically mean a node sends out a proposal which was already received (and received a prevote quorum) from another round. Are you referring to that? If so, that should only be relevant when sending a proposal, where this function is for receiving one, right? Maybe the fn name should imply that:
- receive_proposal
- process_inbound_proposal
- etc?
</blockquote></details>

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/147)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/147)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/147)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
