### PR TITLE
feat(block_hash): starknet version for block hash

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/814)

### CODE REVIEW

**Review by aner-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/814)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/814#-O6vgKoD8MCECBzJ-FaX:-O6vgKoD8MCECBzJ-FaY:b5yw05d) ([raw file](https://github.com/starkware-libs/sequencer/blob/e38bf528b248888e8ee581f0b4762113489fd8c0/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L100)):*
> ```XML
>             felt!("0x151e476191e08eb205e879d4fc5bce4b48d039a2dc18b94af52b37da749f770")
>         }
>     };
> ```

Possibly an overkill, but is it possible to rerun the hash computation with different `l2_gas_price` and check that it changes for `V0_13_3`, but remains the same for `V0_13_2`?



_Code quote:_
```XML
    let expected_hash = match block_hash_version {
        BlockHashVersion::VO_13_2 => {
            felt!("0xe248d6ce583f8fa48d1d401d4beb9ceced3733e38d8eacb0d8d3669a7d901c")
        }
        BlockHashVersion::VO_13_3 => {
            felt!("0x151e476191e08eb205e879d4fc5bce4b48d039a2dc18b94af52b37da749f770")
        }
    };
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/814)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/814#-O6vgKoD8MCECBzJ-FaX:-O6z1d9Y6w8tFeplLEHD:b5p3611) ([raw file](https://github.com/starkware-libs/sequencer/blob/e38bf528b248888e8ee581f0b4762113489fd8c0/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L100)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Possibly an overkill, but is it possible to rerun the hash computation with different `l2_gas_price` and check that it changes for `V0_13_3`, but remains the same for `V0_13_2`?
</blockquote></details>

Here we test changing the version with the same `l2_gas price`.
In `test_hash_changes` we test changing the `l2_gas price` under v0_13_3.
Do you ask to test changing the `l2_gas price` under v0_13_2 as well?

**Comment by aner-starkware** [comment]
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/814#-O6vgKoD8MCECBzJ-FaX:-O6z55mp8xkrKVshIrxo:b-7hrzib) ([raw file](https://github.com/starkware-libs/sequencer/blob/e38bf528b248888e8ee581f0b4762113489fd8c0/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L100)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Here we test changing the version with the same `l2_gas price`.
In `test_hash_changes` we test changing the `l2_gas price` under v0_13_3.
Do you ask to test changing the `l2_gas price` under v0_13_2 as well?
</blockquote></details>

Yes, I want a sanity check to ensure it doesn't affect the hash in `v0_13_2`.

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/814)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/814#-O6vgKoD8MCECBzJ-FaX:-O6zBhWRB0cT7nZJjUf1:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e38bf528b248888e8ee581f0b4762113489fd8c0/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L100)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Yes, I want a sanity check to ensure it doesn't affect the hash in `v0_13_2`.
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/814)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @yoavGrs)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/814#-O6v5ipf0IUH8sxA8eDT:-O6v5ipf0IUH8sxA8eDU:bazd9d6) ([raw file](https://github.com/starkware-libs/sequencer/blob/e38bf528b248888e8ee581f0b4762113489fd8c0/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L48)):*
> ```XML
>         }
>     }
> }
> ```

seems more natural



_Suggestion:_
```XML
impl From<BlockHashVersion> for StarknetVersion {
    pub fn from(value: BlockHashVersion) -> Self {
        match value {
            BlockHashVersion::VO_13_2 => Self("0.13.2".to_owned()),
            BlockHashVersion::VO_13_3 => Self("0.13.3".to_owned()),
        }
    }
}
```
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/814#-O6v6Yo86o1lE_XRHmas:-O6v6Yo86o1lE_XRHmat:brua0by) ([raw file](https://github.com/starkware-libs/sequencer/blob/e38bf528b248888e8ee581f0b4762113489fd8c0/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L67)):*
> ```XML
> #[case::v0_13_2(BlockHashVersion::VO_13_2)]
> #[case::v0_13_3(BlockHashVersion::VO_13_3)]
> fn test_block_hash_regression(#[case] block_hash_version: BlockHashVersion) {
> ```

I always prefer using `values` when possible (only impossible when you have coupled parameters). non-blocking



_Suggestion:_
```XML
#[rstest]
fn test_block_hash_regression(
    #[values(BlockHashVersion::VO_13_2, BlockHashVersion::VO_13_3)]
    block_hash_version: BlockHashVersion
) {
```
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/814#-O6v65yHCuMIIWUWr48W:-O6v65yHCuMIIWUWr48X:b-du6wtk) ([raw file](https://github.com/starkware-libs/sequencer/blob/e38bf528b248888e8ee581f0b4762113489fd8c0/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L140)):*
> ```XML
> 
>     // Test that changing any of the fields in the header or the commitments changes the hash.
>     test_hash_changes!(
> ```

please edit the `test_hash_changes` macro to *also create the above structs*. that way, you add the field values in a single location, and you won't need to remember to add a field somewhere else.
can (and should) be done in a separate PR..



_Code quote:_
```XML
test_hash_changes!(
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/814)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/814#-O6v5ipf0IUH8sxA8eDT:-O6zbSXm7zE-fPTZmJ0B:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e38bf528b248888e8ee581f0b4762113489fd8c0/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

seems more natural
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/814#-O6v6Yo86o1lE_XRHmas:-O6zbmkmEL5iDgUPUnzt:bu47lik) ([raw file](https://github.com/starkware-libs/sequencer/blob/e38bf528b248888e8ee581f0b4762113489fd8c0/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L67)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I always prefer using `values` when possible (only impossible when you have coupled parameters). non-blocking
</blockquote></details>

Right, it's better. Done.
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/814#-O6v65yHCuMIIWUWr48W:-O6zcddgBvXpa3rF-OLj:bmr01d3) ([raw file](https://github.com/starkware-libs/sequencer/blob/e38bf528b248888e8ee581f0b4762113489fd8c0/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L140)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please edit the `test_hash_changes` macro to *also create the above structs*. that way, you add the field values in a single location, and you won't need to remember to add a field somewhere else.
can (and should) be done in a separate PR..
</blockquote></details>

I'll look into it

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/814#-:-O6zlJWp1e1GaaauQKj0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/814)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 109 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/814#-O6zww8qCutOAwv3hvEp:-O6zww8qCutOAwv3hvEq:br3mqiv) ([raw file](https://github.com/starkware-libs/sequencer/blob/740170106fed6cff95098393f9188587f931f85b/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L109)):*
> ```XML
> fn l2_gas_price_pre_v0_13_3() {
>     let block_header = {
>         |l2_gas_price: u128| BlockHeaderWithoutHash {
> ```

I think you don't need this; non-blocking.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/814)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/814)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 109 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/814#-O6zww8qCutOAwv3hvEp:-O73-UJW1PaC0fLsoZJC:ba3dfob) ([raw file](https://github.com/starkware-libs/sequencer/blob/740170106fed6cff95098393f9188587f931f85b/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L109)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I think you don't need this; non-blocking.
</blockquote></details>

Removed

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/814)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/814)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 109 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/814#-O6zww8qCutOAwv3hvEp:-O733Pq15rd34s3_9z66:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/740170106fed6cff95098393f9188587f931f85b/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L109)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Removed
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/814)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by aner-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/814)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
