### PR TITLE
build(fee): add l2_gas field to gas vector

### PR DESCRIPTION
**Pull request by nimrod-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/113)

### CODE REVIEW

**Review by nimrod-starkware — COMMENTED** [review]
python side [PR](https://reviewable.io/reviews/starkware-industries/starkware/35624)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/113#-:-O2e09H9933ZQcotwDfR:bn40ji2)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/113)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 276 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/113#-O2xgNd03aQhQmfmlsia:-O2xgNd03aQhQmfmlsib:b-pb9bm7) ([raw file](https://github.com/starkware-libs/sequencer/blob/932bdcebfd28ecef8084daba6db58e28bec530e3/crates/blockifier/src/fee/actual_cost_test.rs#L276)):*
> ```XML
>             .get_state_changes_cost(use_kzg_da)
>             .l1_data_gas,
>         ..Default::default()
> ```

indent



_Suggestion:_
```XML
    ..Default::default()
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1869 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/113#-O2xgXQQ7xwXmlP1RNhz:-O2xgXQQ7xwXmlP1RNi-:be2utnb) ([raw file](https://github.com/starkware-libs/sequencer/blob/932bdcebfd28ecef8084daba6db58e28bec530e3/crates/blockifier/src/transaction/transactions_test.rs#L1869)):*
> ```XML
>     // (currently matches only starknet resources).
>     let expected_gas = match use_kzg_da {
>         true => GasVector { l1_gas: 16023, l1_data_gas: 128, ..Default::default() },
> ```

being explicit makes more sense here IMO



_Suggestion:_
```XML
, l2_gas: 0
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/113)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 276 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/113#-O2xgNd03aQhQmfmlsia:-O2xjCpJ8oorY7egtM1D:b-ojgy7y) ([raw file](https://github.com/starkware-libs/sequencer/blob/932bdcebfd28ecef8084daba6db58e28bec530e3/crates/blockifier/src/fee/actual_cost_test.rs#L276)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

indent
</blockquote></details>

The auto formatter keeps it that way; the `.,Default::default()` refers to `l2_gas` which is at the indentation level as the other fields in `GasVector`
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1869 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/113#-O2xgXQQ7xwXmlP1RNhz:-O2xiieACQ5-IkWZZMaK:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/932bdcebfd28ecef8084daba6db58e28bec530e3/crates/blockifier/src/transaction/transactions_test.rs#L1869)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

being explicit makes more sense here IMO
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/113)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/113#-O2yLPFV3tmVWFI4H2UX:-O2yLPFV3tmVWFI4H2UY:b-365zp0) (no related file):*
blocking until python side passes..

___
___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 276 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/113#-O2xgNd03aQhQmfmlsia:-O2yLVNz2PT0iLEYNDN6:bjp0lgk) ([raw file](https://github.com/starkware-libs/sequencer/blob/932bdcebfd28ecef8084daba6db58e28bec530e3/crates/blockifier/src/fee/actual_cost_test.rs#L276)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

The auto formatter keeps it that way; the `.,Default::default()` refers to `l2_gas` which is at the indentation level as the other fields in `GasVector`
</blockquote></details>

ah! right you are

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/113)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/113#-O2yLPFV3tmVWFI4H2UX:-O3aOPaO-hN7cBUAtVsT:bvhsfn9) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

blocking until python side passes..
</blockquote></details>

hodor passed

___

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/113#-:-O3bZTtv8py1NvCiJLev:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
