### PR TITLE
refactor(blockifier_reexecution): compare sorted jsons instead of structs

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1758?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1758** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1758?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1712** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1712?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1698** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1698?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1658** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1658?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1604** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1604?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1758)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-OAwQdzt4eju1E_J8xmR:-OAwQdzuCyqIMuRPbFxD:b-wx1nef) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ceac3b0e0fd46d7b9d5a42af41b9fabd8aceb46/crates/blockifier/src/state/cached_state.rs#L8)):*
> ```XML
> use indexmap::IndexMap;
> #[cfg(feature = "transaction_serde")]
> use serde::{Serialize, Serializer};
> ```

I prefer you use fully-qualified inline imports below, instead of adding "gated" `use`es.
for example, we already have lines like this:
```
#[cfg_attr(feature = "transaction_serde", derive(serde::Serialize, serde::Deserialize))]
```
we don't do `use serde::{Deserialize, Serialize}` behind `#[cfg(feature = "transaction_serde")]`



_Code quote:_
```XML
#[cfg(feature = "transaction_serde")]
use std::collections::BTreeMap;
use std::collections::{HashMap, HashSet};

use indexmap::IndexMap;
#[cfg(feature = "transaction_serde")]
use serde::{Serialize, Serializer};
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 578 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-OAwQzBuBD--GcxZtTLt:-OAwQzBuBD--GcxZtTLu:biv2fb8) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ceac3b0e0fd46d7b9d5a42af41b9fabd8aceb46/crates/blockifier/src/state/cached_state.rs#L578)):*
> ```XML
> 
> // Custom serializer for nested `IndexMap` with different key types.
> #[cfg(feature = "transaction_serde")]
> ```

not just `transaction_serde`: also require the `reexecution` feature (Aner [is adding it](https://reviewable.io/reviews/starkware-libs/sequencer/1762)).
we don't want to sort always... only when both features are active.
since the `reexecution` feature [will depend on `transaction_serde`](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OAwRZ123JfIOwYoeZ5Y), enough to replace the `transaction_serde` requirements here with `reexecution`



_Code quote:_
```XML
    #[cfg_attr(feature = "transaction_serde", serde(serialize_with = "serialize_sorted"))]
    pub address_to_class_hash: IndexMap<ContractAddress, ClassHash>,
    #[cfg_attr(feature = "transaction_serde", serde(serialize_with = "serialize_sorted"))]
    pub address_to_nonce: IndexMap<ContractAddress, Nonce>,
    #[cfg_attr(feature = "transaction_serde", serde(serialize_with = "serialize_nested_sorted"))]
    pub storage_updates: IndexMap<ContractAddress, IndexMap<StorageKey, Felt>>,

    // Global attributes.
    #[cfg_attr(feature = "transaction_serde", serde(serialize_with = "serialize_sorted"))]
    pub class_hash_to_compiled_class_hash: IndexMap<ClassHash, CompiledClassHash>,
}

// Define custom serializer to sort by keys.
#[cfg(feature = "transaction_serde")]
fn serialize_sorted<S, K, V>(map: &IndexMap<K, V>, serializer: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
    K: Ord + Serialize,
    V: Serialize,
{
    // Convert the IndexMap to BTreeMap, which automatically sorts keys.
    let sorted_map: BTreeMap<_, _> = map.iter().collect();
    sorted_map.serialize(serializer)
}

// Custom serializer for nested `IndexMap` with different key types.
#[cfg(feature = "transaction_serde")]
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 599 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-OAwRwrt7yxO5CMoixPI:-OAwRwrt7yxO5CMoixPJ:b1bsacg) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ceac3b0e0fd46d7b9d5a42af41b9fabd8aceb46/crates/blockifier/src/state/cached_state.rs#L599)):*
> ```XML
> 
>     sorted_map.serialize(serializer)
> }
> ```

please put this in a separate `reexecution_serde.rs` module and declare it at the top of this module:
```
#[cfg(feature = "reexecution")]`
pub mod reexecution_serde;
```



_Code quote:_
```XML
// Define custom serializer to sort by keys.
#[cfg(feature = "transaction_serde")]
fn serialize_sorted<S, K, V>(map: &IndexMap<K, V>, serializer: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
    K: Ord + Serialize,
    V: Serialize,
{
    // Convert the IndexMap to BTreeMap, which automatically sorts keys.
    let sorted_map: BTreeMap<_, _> = map.iter().collect();
    sorted_map.serialize(serializer)
}

// Custom serializer for nested `IndexMap` with different key types.
#[cfg(feature = "transaction_serde")]
fn serialize_nested_sorted<S, OuterK, InnerK, V>(
    map: &IndexMap<OuterK, IndexMap<InnerK, V>>,
    serializer: S,
) -> Result<S::Ok, S::Error>
where
    S: Serializer,
    OuterK: Ord + Serialize,
    InnerK: Ord + Serialize,
    V: Serialize,
{
    // Sort each inner `IndexMap` and store in a `BTreeMap` for serialization.
    let sorted_map: BTreeMap<_, BTreeMap<_, _>> = map
        .iter()
        .map(|(outer_key, inner_map)| {
            let sorted_inner_map: BTreeMap<_, _> = inner_map.iter().collect();
            (outer_key, sorted_inner_map)
        })
        .collect();

    sorted_map.serialize(serializer)
}
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 599 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-OAwS8gz65wj86D3YNMH:-OAwS8gz65wj86D3YNMI:b-epavo6) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ceac3b0e0fd46d7b9d5a42af41b9fabd8aceb46/crates/blockifier/src/state/cached_state.rs#L599)):*
> ```XML
> 
>     sorted_map.serialize(serializer)
> }
> ```

are these custom serializers needed?
don't serde have utility methods for dumping indexmaps sorted by the value of the keys instead of insertion order?



_Code quote:_
```XML
#[cfg(feature = "transaction_serde")]
fn serialize_sorted<S, K, V>(map: &IndexMap<K, V>, serializer: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
    K: Ord + Serialize,
    V: Serialize,
{
    // Convert the IndexMap to BTreeMap, which automatically sorts keys.
    let sorted_map: BTreeMap<_, _> = map.iter().collect();
    sorted_map.serialize(serializer)
}

// Custom serializer for nested `IndexMap` with different key types.
#[cfg(feature = "transaction_serde")]
fn serialize_nested_sorted<S, OuterK, InnerK, V>(
    map: &IndexMap<OuterK, IndexMap<InnerK, V>>,
    serializer: S,
) -> Result<S::Ok, S::Error>
where
    S: Serializer,
    OuterK: Ord + Serialize,
    InnerK: Ord + Serialize,
    V: Serialize,
{
    // Sort each inner `IndexMap` and store in a `BTreeMap` for serialization.
    let sorted_map: BTreeMap<_, BTreeMap<_, _>> = map
        .iter()
        .map(|(outer_key, inner_map)| {
            let sorted_inner_map: BTreeMap<_, _> = inner_map.iter().collect();
            (outer_key, sorted_inner_map)
        })
        .collect();

    sorted_map.serialize(serializer)
}
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1758)* status: all files reviewed, 5 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-OAwTOeL95GzNUbOuZYw:-OAwTOeL95GzNUbOuZYx:bup62m2) (no related file):*
now that I think about it: I would like this done differently.
I don't want these code changes in the blockifier - if someone activates the feature unintentionally they will get unexpected serde behavior!
please add custom "compare_state_diffs" function in the reexecution crate, that does this custom serialization excplitily.
even better: just define a new SortedStateDiff struct, with `From` conversions in both directions, that just changes the `IndexMap` type to a `HashMap`. then, `assert_eq` should just work out of the box

___

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1758)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1758)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-OAwTOeL95GzNUbOuZYw:-OAwlK306Pu9dsr4K9ia:b-3zo8ty) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

now that I think about it: I would like this done differently.
I don't want these code changes in the blockifier - if someone activates the feature unintentionally they will get unexpected serde behavior!
please add custom "compare_state_diffs" function in the reexecution crate, that does this custom serialization excplitily.
even better: just define a new SortedStateDiff struct, with `From` conversions in both directions, that just changes the `IndexMap` type to a `HashMap`. then, `assert_eq` should just work out of the box
</blockquote></details>

HashMap is not performing well; there is still significant noise in the diff when comparing two different objects. In contrast, BTreeMap provides a clearer diff.

___
___
*[`crates/blockifier/src/state/cached_state.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-OAwQdzt4eju1E_J8xmR:-OAwylYe5TBnm-UILn-n:b-1k4x3t) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ceac3b0e0fd46d7b9d5a42af41b9fabd8aceb46/crates/blockifier/src/state/cached_state.rs#L8)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I prefer you use fully-qualified inline imports below, instead of adding "gated" `use`es.
for example, we already have lines like this:
```
#[cfg_attr(feature = "transaction_serde", derive(serde::Serialize, serde::Deserialize))]
```
we don't do `use serde::{Deserialize, Serialize}` behind `#[cfg(feature = "transaction_serde")]`
</blockquote></details>

Doesnt relevant 
___
*[`crates/blockifier/src/state/cached_state.rs` line 578 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-OAwQzBuBD--GcxZtTLt:-OAwyset-aiLkEZe_387:b-1k4x3t) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ceac3b0e0fd46d7b9d5a42af41b9fabd8aceb46/crates/blockifier/src/state/cached_state.rs#L578)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not just `transaction_serde`: also require the `reexecution` feature (Aner [is adding it](https://reviewable.io/reviews/starkware-libs/sequencer/1762)).
we don't want to sort always... only when both features are active.
since the `reexecution` feature [will depend on `transaction_serde`](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OAwRZ123JfIOwYoeZ5Y), enough to replace the `transaction_serde` requirements here with `reexecution`
</blockquote></details>

Doesnt relevant 
___
*[`crates/blockifier/src/state/cached_state.rs` line 599 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-OAwRwrt7yxO5CMoixPI:-OAw_3U24mrBfs82R6Hc:b-1k4x3t) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ceac3b0e0fd46d7b9d5a42af41b9fabd8aceb46/crates/blockifier/src/state/cached_state.rs#L599)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please put this in a separate `reexecution_serde.rs` module and declare it at the top of this module:
```
#[cfg(feature = "reexecution")]`
pub mod reexecution_serde;
```
</blockquote></details>

Doesnt relevant 
___
*[`crates/blockifier/src/state/cached_state.rs` line 599 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-OAwS8gz65wj86D3YNMH:-OAw_Hfe8EdvYSvK1gHC:b-1k4x3t) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ceac3b0e0fd46d7b9d5a42af41b9fabd8aceb46/crates/blockifier/src/state/cached_state.rs#L599)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

are these custom serializers needed?
don't serde have utility methods for dumping indexmaps sorted by the value of the keys instead of insertion order?
</blockquote></details>

Doesnt relevant

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1758)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-OAwTOeL95GzNUbOuZYw:-OAx-pWP9WYI1hbJtMDv:bmv089u) (no related file):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

HashMap is not performing well; there is still significant noise in the diff when comparing two different objects. In contrast, BTreeMap provides a clearer diff.
</blockquote></details>

ok, BTreeMap then.

___
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 133 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-OAx-xA4BJemQ2poMkjU:-OAx-xA4BJemQ2poMkjV:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0a1f2b4548f3b8a0481a7a4a1796581d6cbfab42/crates/blockifier_reexecution/src/state_reader/utils.rs#L133)):*
> ```XML
> }
> 
> // A struct for comparing `CommitmentStateDiff` instances, disregarding insertion order.
> ```





_Suggestion:_
```XML
/// A 
```
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 174 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-OAx0KVE25pwUCnDeZ_L:-OAx0KVE25pwUCnDeZ_M:b-n7080c) ([raw file](https://github.com/starkware-libs/sequencer/blob/0a1f2b4548f3b8a0481a7a4a1796581d6cbfab42/crates/blockifier_reexecution/src/state_reader/utils.rs#L174)):*
> ```XML
>     let comparable_expected_state_diff = ComparableStateDiff::from(expected_state_diff);
>     let comparable_actual_state_diff = ComparableStateDiff::from(actual_state_diff);
>     assert_eq!(comparable_expected_state_diff, comparable_actual_state_diff);
> ```

I would remove the intermediate vars; when this is a macro you wouldn't want to define new variable names



_Code quote:_
```XML
    let comparable_expected_state_diff = ComparableStateDiff::from(expected_state_diff);
    let comparable_actual_state_diff = ComparableStateDiff::from(actual_state_diff);
    assert_eq!(comparable_expected_state_diff, comparable_actual_state_diff);
```
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 175 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-OAx04xGAk1LTfTNhkQX:-OAx04xGAk1LTfTNhkQY:b-5u33pw) ([raw file](https://github.com/starkware-libs/sequencer/blob/0a1f2b4548f3b8a0481a7a4a1796581d6cbfab42/crates/blockifier_reexecution/src/state_reader/utils.rs#L175)):*
> ```XML
>     let comparable_actual_state_diff = ComparableStateDiff::from(actual_state_diff);
>     assert_eq!(comparable_expected_state_diff, comparable_actual_state_diff);
> }
> ```

please make this a macro, like `assert_eq`.
useful to see the line number in the console on failure (in case this function is also used elsewhere)



_Code quote:_
```XML
pub fn assert_eq_state_diff(
    expected_state_diff: CommitmentStateDiff,
    actual_state_diff: CommitmentStateDiff,
) {
    let comparable_expected_state_diff = ComparableStateDiff::from(expected_state_diff);
    let comparable_actual_state_diff = ComparableStateDiff::from(actual_state_diff);
    assert_eq!(comparable_expected_state_diff, comparable_actual_state_diff);
}
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1758)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 133 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-OAx-xA4BJemQ2poMkjU:-OB-PH7MArDUtJapxS4l:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0a1f2b4548f3b8a0481a7a4a1796581d6cbfab42/crates/blockifier_reexecution/src/state_reader/utils.rs#L133)):*
> ```XML
> }
> 
> // A struct for comparing `CommitmentStateDiff` instances, disregarding insertion order.
> ```

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 174 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-OAx0KVE25pwUCnDeZ_L:-OB-PMVU8DjK6REGUNAF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0a1f2b4548f3b8a0481a7a4a1796581d6cbfab42/crates/blockifier_reexecution/src/state_reader/utils.rs#L174)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I would remove the intermediate vars; when this is a macro you wouldn't want to define new variable names
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 175 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-OAx04xGAk1LTfTNhkQX:-OB-PN0O-kWOBRmvnlSn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0a1f2b4548f3b8a0481a7a4a1796581d6cbfab42/crates/blockifier_reexecution/src/state_reader/utils.rs#L175)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please make this a macro, like `assert_eq`.
useful to see the line number in the console on failure (in case this function is also used elsewhere)
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1758)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 178 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-OB-r3Ix2zg5lnQfpziA:-OB-r3Ix2zg5lnQfpziB:b-7etu9f) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b5af656df457045e2f785bfa32d3ab8b28f85c9/crates/blockifier_reexecution/src/state_reader/utils.rs#L178)):*
> ```XML
>             ComparableStateDiff::from($actual_state_diff),
>             "Expected and actual state diffs do not match."
>         );
> ```

inline the paths?
otherwise, if you call `assert_eq_state_diff` twice in a row you will `use` twice



_Suggestion:_
```XML
        pretty_assertions::assert_eq!(
            blockifier_reexecution::state_reader::utils::ComparableStateDiff::from($expected_state_diff),
            blockifier_reexecution::state_reader::utils::ComparableStateDiff::from($actual_state_diff),
            "Expected and actual state diffs do not match."
        );
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1758)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 178 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-OB-r3Ix2zg5lnQfpziA:-OB0DOhiBL-IGa5P7mhA:b-zcjvte) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b5af656df457045e2f785bfa32d3ab8b28f85c9/crates/blockifier_reexecution/src/state_reader/utils.rs#L178)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

inline the paths?
otherwise, if you call `assert_eq_state_diff` twice in a row you will `use` twice
</blockquote></details>

Thanks

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1758#-:-OB0Klil5XBlfdCMnRW8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Comment by AvivYossef-starkware** [comment]
### Merge activity

* **Nov 6, 6:59 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1758).

**Pull request merged**
