### PR TITLE
refactor(batcher): start_height tests refactor

### PR DESCRIPTION
**Pull request by dafnamatsry**

### CODE REVIEW

**Comment by dafnamatsry** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2205?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2205** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2205?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2205?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2192** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2192?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2205#-:-OCD0xNl5Sb2ducyueAY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2205)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2205#-OCD-qym4keq1Ff56GgA:-OCD-qym4keq1Ff56GgB:b-rhboei) ([raw file](https://github.com/starkware-libs/sequencer/blob/029d9e9c9d8ccd69a98fb6fb667b57c605fbacc9/crates/starknet_batcher/src/batcher_test.rs#L154)):*
> ```XML
> #[rstest]
> #[case::height_already_passed(
>     StartHeightInput {height: INITIAL_HEIGHT.prev().unwrap()},
> ```

Isn't it actually less duplication to wrap it when calling as it was previously? 



_Code quote:_
```XML
StartHeightInput {height:
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2205#-OCD1MBK52zpNZV2jW_j:-OCD1MBK52zpNZV2jW_k:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/029d9e9c9d8ccd69a98fb6fb667b57c605fbacc9/crates/starknet_batcher/src/batcher_test.rs#L195)):*
> ```XML
>     let mut batcher = batcher(proposal_manager);
> 
>     // Calling `build_proposal` and `validate_proposal` without starting a height should fail.
> ```





_Suggestion:_
```XML
// Calling `build_block` and `validate_block` without starting a height should fail.
```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2205)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2205#-OCD-qym4keq1Ff56GgA:-OCD4QK51GsL7k96dCOc:b-tuomwa) ([raw file](https://github.com/starkware-libs/sequencer/blob/029d9e9c9d8ccd69a98fb6fb667b57c605fbacc9/crates/starknet_batcher/src/batcher_test.rs#L154)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Isn't it actually less duplication to wrap it when calling as it was previously?
</blockquote></details>

Right! Done.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2205#-OCD1MBK52zpNZV2jW_j:-OCD4_z67X8e9cG8aKfJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/029d9e9c9d8ccd69a98fb6fb667b57c605fbacc9/crates/starknet_batcher/src/batcher_test.rs#L195)):*
> ```XML
>     let mut batcher = batcher(proposal_manager);
> 
>     // Calling `build_proposal` and `validate_proposal` without starting a height should fail.
> ```

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2205#-:-OCD5qZX-FwJf1ZEXJb1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Comment by dafnamatsry** [comment]
### Merge activity

* **Nov 21, 6:20 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2205).

**Pull request merged**
