### PR TITLE
refactor(blockifier): share get_block_hash syscall code between native and casm

### PR DESCRIPTION
**Pull request by meship-starkware**

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2107)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBtz4vEAdCV7Irh5XLI:-OBtz4vEAdCV7Irh5XLJ:bnqq7xs) ([raw file](https://github.com/starkware-libs/sequencer/blob/7120aabaf7ac9826afc182a3834265e5db390c82/crates/blockifier/src/execution/syscalls/syscall_base.rs#L21)):*
> ```XML
>     {
>         let out_of_range_error =
>             Felt::from_hex(BLOCK_NUMBER_OUT_OF_RANGE_ERROR).map_err(SyscallExecutionError::from)?;
> ```

I am not sure this is the right way to handle the error here because, in the native implementation, we panicked. 



_Code quote:_
```XML
        let out_of_range_error =
            Felt::from_hex(BLOCK_NUMBER_OUT_OF_RANGE_ERROR).map_err(SyscallExecutionError::from)?;
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBtzR0J6K_FMzBdtS8q:-OBtzR0J6K_FMzBdtS8r:b-5x87s6) ([raw file](https://github.com/starkware-libs/sequencer/blob/7120aabaf7ac9826afc182a3834265e5db390c82/crates/blockifier/src/execution/native/syscall_handler.rs#L285)):*
> ```XML
>         let (key, block_hash_contract_address) =
>             get_block_hash_base(current_block_number, block_number)
>                 .map_err(|e| self.handle_error(remaining_gas, e.into()))?;
> ```

I am not sure this is the right way to handle the error here. 



_Code quote:_
```XML
.map_err(|e| self.handle_error(remaining_gas, e.into()))?;
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2107)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/cairo_native` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBu0LkCDjBNK--lWW9n:-OBu0LkCDjBNK--lWW9o:b-g8qpnp) ([raw file](https://github.com/starkware-libs/sequencer/blob/913d48489d0e6716601ad76c58060f364fc9a84b/crates/blockifier/cairo_native#L1)):*
> ```
> Subproject commit 0bc6f408884370e4fbbf421c4e8e109911c3d73e
> ```

This is a mistake. Working on it 



_Code quote:_
```
Subproject commit 0bc6f408884370e4fbbf421c4e8e109911c3d73e
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2107)* status: 1 of 5 files reviewed, 8 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBtzR0J6K_FMzBdtS8q:-OBuA22r60QVIpmpXkrZ:b8b25vt) ([raw file](https://github.com/starkware-libs/sequencer/blob/913d48489d0e6716601ad76c58060f364fc9a84b/crates/blockifier/src/execution/native/syscall_handler.rs#L285)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I am not sure this is the right way to handle the error here.
</blockquote></details>

Why not?
___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBtz4vEAdCV7Irh5XLI:-OBuANk17UHvXO5fzXKe:b-7mzodi) ([raw file](https://github.com/starkware-libs/sequencer/blob/913d48489d0e6716601ad76c58060f364fc9a84b/crates/blockifier/src/execution/syscalls/syscall_base.rs#L21)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I am not sure this is the right way to handle the error here because, in the native implementation, we panicked.
</blockquote></details>

Panic here as well. It is safe
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/get_block_hash.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBuAWCo7FiFZKA0kmyR:-OBuAWCo7FiFZKA0kmyS:bvtk9y9) ([raw file](https://github.com/starkware-libs/sequencer/blob/600f313e49fe82fc6d1eebb3731b6bcb2cb89ddc/crates/blockifier/src/execution/syscalls/syscall_tests/get_block_hash.rs#L120)):*
> ```XML
>     };
> 
>     let call_info = entry_point_call.execute_directly(&mut state).unwrap();
> ```

Thanks :)
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBu9qJL9PzeZdcrBNoc:-OBu9qJL9PzeZdcrBNod:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/600f313e49fe82fc6d1eebb3731b6bcb2cb89ddc/crates/blockifier/src/execution/native/syscall_handler.rs#L55)):*
> ```XML
>     OUT_OF_GAS_ERROR,
> };
> use crate::execution::syscalls::syscall_base::get_block_hash_base;
> ```





_Suggestion:_
```XML
ase;
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 281 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBuA6354LJxLgu2lqCe:-OBuA6365_2DGKQli_fk:b-27ocsb) ([raw file](https://github.com/starkware-libs/sequencer/blob/600f313e49fe82fc6d1eebb3731b6bcb2cb89ddc/crates/blockifier/src/execution/native/syscall_handler.rs#L281)):*
> ```XML
> 
>         let current_block_number =
>             self.context.tx_context.block_context.block_info().block_number.0;
> ```

Share this code as well



_Code quote:_
```XML
        if self.context.execution_mode == ExecutionMode::Validate {
            let err = SyscallExecutionError::InvalidSyscallInExecutionMode {
                syscall_name: "get_block_hash".to_string(),
                execution_mode: ExecutionMode::Validate,
            };
            return Err(self.handle_error(remaining_gas, err));
        }

        let current_block_number =
            self.context.tx_context.block_context.block_info().block_number.0;
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 284 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBu9muOCCL0wWN_5xh3:-OBu9muOCCL0wWN_5xh4:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/600f313e49fe82fc6d1eebb3731b6bcb2cb89ddc/crates/blockifier/src/execution/native/syscall_handler.rs#L284)):*
> ```XML
> 
>         let (key, block_hash_contract_address) =
>             get_block_hash_base(current_block_number, block_number)
> ```





_Suggestion:_
```XML
syscall_base::get_block_hash(
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 287 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBuAHLI27ppQCGhZ0jT:-OBuAHLI27ppQCGhZ0jU:by8fchs) ([raw file](https://github.com/starkware-libs/sequencer/blob/600f313e49fe82fc6d1eebb3731b6bcb2cb89ddc/crates/blockifier/src/execution/native/syscall_handler.rs#L287)):*
> ```XML
>                 .map_err(|e| self.handle_error(remaining_gas, e.into()))?;
> 
>         match self.state.get_storage_at(block_hash_contract_address, key) {
> ```

Share this as well



_Code quote:_
```XML
self.state.get_storage_at(block_hash_contract_address, key) {
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBuARYbCguzNkPK0vgw:-OBuARYbCguzNkPK0vgx:b-ktgkvt) ([raw file](https://github.com/starkware-libs/sequencer/blob/600f313e49fe82fc6d1eebb3731b6bcb2cb89ddc/crates/blockifier/src/execution/syscalls/syscall_base.rs#L10)):*
> ```XML
>     BLOCK_NUMBER_OUT_OF_RANGE_ERROR,
> };
> ```

Document this file shortly.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2107)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @avi-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 281 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBuA6354LJxLgu2lqCe:-OBuRVo8Etcp4WdL36dU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/600f313e49fe82fc6d1eebb3731b6bcb2cb89ddc/crates/blockifier/src/execution/native/syscall_handler.rs#L281)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Share this code as well
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 287 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBuAHLI27ppQCGhZ0jT:-OBuRYfI6vQXN1ZNIbHs:boxiria) ([raw file](https://github.com/starkware-libs/sequencer/blob/600f313e49fe82fc6d1eebb3731b6bcb2cb89ddc/crates/blockifier/src/execution/native/syscall_handler.rs#L287)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Share this as well
</blockquote></details>

Seems like it fails the native tests. I'll look into it. 
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBu9qJL9PzeZdcrBNoc:-OBuRND81BHYIiVPI3s2:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/600f313e49fe82fc6d1eebb3731b6bcb2cb89ddc/crates/blockifier/src/execution/native/syscall_handler.rs#L55)):*
> ```XML
>     OUT_OF_GAS_ERROR,
> };
> use crate::execution::syscalls::syscall_base::get_block_hash_base;
> ```

Done.
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 284 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBu9muOCCL0wWN_5xh3:-OBuRWs50wsHncsadPgB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/600f313e49fe82fc6d1eebb3731b6bcb2cb89ddc/crates/blockifier/src/execution/native/syscall_handler.rs#L284)):*
> ```XML
> 
>         let (key, block_hash_contract_address) =
>             get_block_hash_base(current_block_number, block_number)
> ```

Done.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2107)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @avi-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 287 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBuAHLI27ppQCGhZ0jT:-OBuUgFwAMxiTXdKkdYB:b-5pe4bn) ([raw file](https://github.com/starkware-libs/sequencer/blob/600f313e49fe82fc6d1eebb3731b6bcb2cb89ddc/crates/blockifier/src/execution/native/syscall_handler.rs#L287)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Seems like it fails the native tests. I'll look into it.
</blockquote></details>

NM seems OK in the CI, although it fails locally. 
Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2107)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 400 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OButiEy510ckcrcBw2P:-OButiEy510ckcrcBw2Q:b-p91c3u) ([raw file](https://github.com/starkware-libs/sequencer/blob/e94d3b05b3cf6f78598d318a363041acab2e227e/crates/blockifier/src/execution/syscalls/mod.rs#L400)):*
> ```XML
>     let block_hash = BlockHash(syscall_base::get_block_hash_base(
>         syscall_handler.execution_mode(),
>         current_block_number,
> ```

Pass the context instead.



_Suggestion:_
```XML
    let block_hash = BlockHash(syscall_base::get_block_hash_base(
        self.context,
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2107)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @avi-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBtzR0J6K_FMzBdtS8q:-OByAxGpBEo4aG5KILu6:b-7wso34) ([raw file](https://github.com/starkware-libs/sequencer/blob/913d48489d0e6716601ad76c58060f364fc9a84b/crates/blockifier/src/execution/native/syscall_handler.rs#L285)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why not?
</blockquote></details>

Not relevant anymore
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 400 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OButiEy510ckcrcBw2P:-OByBmg945ifnv_VuhHn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e94d3b05b3cf6f78598d318a363041acab2e227e/crates/blockifier/src/execution/syscalls/mod.rs#L400)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Pass the context instead.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBuARYbCguzNkPK0vgw:-OByBu_614imNV8xbkWY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/600f313e49fe82fc6d1eebb3731b6bcb2cb89ddc/crates/blockifier/src/execution/syscalls/syscall_base.rs#L10)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Document this file shortly.
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-:-OByGIbD5iPET9jY_rsR:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @avi-starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBuARYbCguzNkPK0vgw:-OByFgC1DoHACDaj_Q5l:b-eed7d1) ([raw file](https://github.com/starkware-libs/sequencer/blob/600f313e49fe82fc6d1eebb3731b6bcb2cb89ddc/crates/blockifier/src/execution/syscalls/syscall_base.rs#L10)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet :) but non-blocking

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2107)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 1 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-OBy_FtW-UHbRUqbdTPf:-OBy_FtW-UHbRUqbdTPg:b-4ih2ph) ([raw file](https://github.com/starkware-libs/sequencer/blob/fadd3b110bcf465f5846f2d58d33008380067077/crates/blockifier/src/execution/syscalls/syscall_base.rs#L1)):*
> ```XML
> /// This file is for sharing common logic between Native and Casm syscalls implementations.
> ```

Is this not enough documentation, or is it in the wrong place? 



_Code quote:_
```XML
/// This file is for sharing common logic between Native and Casm syscalls implementations.
```

**Review by Yoni-Starkware — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2107#-:-OByi5h83dP_PCBTJ4La:bnfp4nl)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @avi-starkware)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2107)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Pull request merged**
