### PR TITLE
chore(blockifier): create 'from' Transaction to BlockifierTransaction

### PR DESCRIPTION
**Pull request by avivg-starkware**

### CODE REVIEW

**Comment by avivg-starkware** [comment]
* **#2522** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2522?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2522?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2522)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2522#-ODaD1oy2UH4wFFvCZ6S:-ODaD1oy2UH4wFFvCZ6T:btdeupd) ([raw file](https://github.com/starkware-libs/sequencer/blob/38c81a7ec3532641f90f4f75ec3df833007d615e/crates/blockifier/src/transaction/transaction_execution.rs#L54)):*
> ```XML
>             }
>         }
>     }
> ```

not sure about 'fn from_with_default_flags' as currently there is no use to it. @Yoni-Starkware WDYT? should I leave only 'from_for_sequencing' ?

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2522)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2522#-ODaD1oy2UH4wFFvCZ6S:-ODaIwcCCsc4PM1UQ5yt:bt30blm) ([raw file](https://github.com/starkware-libs/sequencer/blob/38c81a7ec3532641f90f4f75ec3df833007d615e/crates/blockifier/src/transaction/transaction_execution.rs#L54)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

not sure about 'fn from_with_default_flags' as currently there is no use to it. @Yoni-Starkware WDYT? should I leave only 'from_for_sequencing' ?
</blockquote></details>

1. If it's not used - remove
2. Rename `from_for_sequencing` -> `new_for_sequencing`.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2522#-:-ODacs_J8PV-eRMlOgDi:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2522)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2522)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2522#-ODaD1oy2UH4wFFvCZ6S:-ODerWE1AA7VIbbkXwlf:b-896fjb) ([raw file](https://github.com/starkware-libs/sequencer/blob/38c81a7ec3532641f90f4f75ec3df833007d615e/crates/blockifier/src/transaction/transaction_execution.rs#L54)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

1. If it's not used - remove
2. Rename `from_for_sequencing` -> `new_for_sequencing`.
</blockquote></details>

Done

**Review by avivg-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2522)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Pull request merged**
