### PR TITLE
feat(blockifier): add Secp256r1 cairo native syscalls

### PR DESCRIPTION
**Pull request by PearsonWhite**
Currently waiting for other changes before proceeding with this.

This is currently a Draft. It requires some other Secp logic that will come in another issue. Then, this branch will be rebased on top of it and the overlapping logic will be removed.

### CODE REVIEW

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1675)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @meship-starkware, @PearsonWhite, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 740 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1675#-OBzuudl3wSuXm1u7pXO:-OBzuudl3wSuXm1u7pXP:bqrikqe) ([raw file](https://github.com/starkware-libs/sequencer/blob/3854b86f39027ee94f190addc2b7ef861aa6aadb/crates/blockifier/src/execution/native/syscall_handler.rs#L740)):*
> ```XML
>         Secp256k1Point {
>             x: big4int_to_u256(x.into()),
>             y: big4int_to_u256(y.into()),
> ```

Why not have the type be `U256` in `Secp256Point` to avoid the double conversion?
Why is the type`BigInt<4>` when converting `Secp256Point` to `Sec256k1Point`, and `BigUint` when converting in the other direction?



_Code quote:_
```XML
            x: big4int_to_u256(x.into()),
            y: big4int_to_u256(y.into()),
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 652 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1675#-OBzxZrQ-OtpMhO1od9r:-OBzxZrQ-OtpMhO1od9s:b1we0a5) ([raw file](https://github.com/starkware-libs/sequencer/blob/3854b86f39027ee94f190addc2b7ef861aa6aadb/crates/blockifier/src/execution/native/syscall_handler.rs#L652)):*
> ```XML
>         Secp256Point::new(x, y)
>             .map(|op| op.map(|p| p.into()))
>             .map_err(|err| self.handle_error(remaining_gas, err))
> ```

I think `option` is clearer than `op`



_Suggestion:_
```XML
        Secp256Point::new(x, y)
            .map(|option| option.map(|p| p.into()))
            .map_err(|err| self.handle_error(remaining_gas, err))
```

**Review by PearsonWhite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1675)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 740 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1675#-OBzuudl3wSuXm1u7pXO:-OC-cMrXBBLdR5v_Qpk3:bg42nk8) ([raw file](https://github.com/starkware-libs/sequencer/blob/3854b86f39027ee94f190addc2b7ef861aa6aadb/crates/blockifier/src/execution/native/syscall_handler.rs#L740)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Why not have the type be `U256` in `Secp256Point` to avoid the double conversion?
Why is the type`BigInt<4>` when converting `Secp256Point` to `Sec256k1Point`, and `BigUint` when converting in the other direction?
</blockquote></details>

I think `Secp256Point`, as an `ark_ec::...::Affine<Curve>` has to hold whatever the config determines, which is `BigInt<4>` to be generic (in `ark_ec`). We're essentially just converting `Affine`s with configs to their cairo_native::starknet structs, which use u256s. As for the BigInt<4> vs BigUint conversion, I'm pretty sure that's just convenience. Since we're not actually handling any signed/unsigned conversions, `big4int_to_u256` and `u256_to_biguint` are used simply because they're in `cairo_native::starknet_stub.rs`.

So I think this boils down to not adding our own helpers/structs on top of ark_ec and cairo_native.

**Comment by xrvdg** [comment]
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 740 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1675#-OBzuudl3wSuXm1u7pXO:-OC1p3cn4Jyov7dpU7R1:b-45b0rp) ([raw file](https://github.com/starkware-libs/sequencer/blob/3854b86f39027ee94f190addc2b7ef861aa6aadb/crates/blockifier/src/execution/native/syscall_handler.rs#L740)):*
<details><summary><i>Previously, PearsonWhite wrote…</i></summary><blockquote>

I think `Secp256Point`, as an `ark_ec::...::Affine<Curve>` has to hold whatever the config determines, which is `BigInt<4>` to be generic (in `ark_ec`). We're essentially just converting `Affine`s with configs to their cairo_native::starknet structs, which use u256s. As for the BigInt<4> vs BigUint conversion, I'm pretty sure that's just convenience. Since we're not actually handling any signed/unsigned conversions, `big4int_to_u256` and `u256_to_biguint` are used simply because they're in `cairo_native::starknet_stub.rs`.

So I think this boils down to not adding our own helpers/structs on top of ark_ec and cairo_native.
</blockquote></details>

Which part do you view as the double conversion? `Secp256k1Point` - convert > `Secp256Point<Curve>` - newtype > `Affine<Curve>` is a single conversion with a newtype wrapper.  The Affine<Curve> is what the operations are done on and Secp256k1Point is set by the interface, putting U256 in Secp256Point wouldn't prevent a conversion, it would only move it to somewhere else.

**Comment by xrvdg** [comment]
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 740 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1675#-OBzuudl3wSuXm1u7pXO:-OC1vg3RBHkUPgBgNHn6:b-jtogrn) ([raw file](https://github.com/starkware-libs/sequencer/blob/3854b86f39027ee94f190addc2b7ef861aa6aadb/crates/blockifier/src/execution/native/syscall_handler.rs#L740)):*
<details><summary><i>Previously, xrvdg (Xander van der Goot) wrote…</i></summary><blockquote>

Which part do you view as the double conversion? `Secp256k1Point` - convert > `Secp256Point<Curve>` - newtype > `Affine<Curve>` is a single conversion with a newtype wrapper.  The Affine<Curve> is what the operations are done on and Secp256k1Point is set by the interface, putting U256 in Secp256Point wouldn't prevent a conversion, it would only move it to somewhere else.
</blockquote></details>

Based on a quick scan the conversion don't do any signed/unsigned conversion, just like Pearson said. Still I would be in favour of changing `u256_to_biguint` to `u256_to_bigint`, that should only require using bigint's constructor. There was no reason to use the biguint over the bigint, I overlooked this.

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1675)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @PearsonWhite, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1675#-OC2BZMf0EBcWwWAIVwV:-OC2BZMg1E04eEGVtWH6:bfqxf79) ([raw file](https://github.com/starkware-libs/sequencer/blob/e79c663bc448be3bd3428a658c65f80ea8355d2b/crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs#L32)):*
> ```XML
> #[cfg_attr(
>   feature = "cairo_native",
>   test_case(FeatureContract::TestContract(CairoVersion::Native), 27573600; "Native")
> ```

Note to self: this is the only syscalls that is affected by the builtins gas cost, meaning that the fact that this gas cost is right means that the builtins costs are right  :) 



_Code quote:_
```XML
test_case(FeatureContract::TestContract(CairoVersion::Native), 27573600; "Native")
```

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1675)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 740 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1675#-OBzuudl3wSuXm1u7pXO:-OC2PWJ48J3mVcKPuXZe:bbxwq0o) ([raw file](https://github.com/starkware-libs/sequencer/blob/3854b86f39027ee94f190addc2b7ef861aa6aadb/crates/blockifier/src/execution/native/syscall_handler.rs#L740)):*
<details><summary><i>Previously, xrvdg (Xander van der Goot) wrote…</i></summary><blockquote>

Based on a quick scan the conversion don't do any signed/unsigned conversion, just like Pearson said. Still I would be in favour of changing `u256_to_biguint` to `u256_to_bigint`, that should only require using bigint's constructor. There was no reason to use the biguint over the bigint, I overlooked this.
</blockquote></details>

Okay, I understand. So the type for `Secp256Point` coordinates is supposed to be `BigInt<4>` according to the definition of the curve.
Two further comments:
1. I think we shouldn't go through `BigUint`. To get `Secp256r1Point` from `Secp256Point`, our current conversion is `U256` -> `BigUint` -> `BigInt<4>`. We should do a direct conversion, as Xander suggested.
2. Is it good practice to use functions from `starknet_stub.rs`? It is a module containing a mock syscall handler for tests. It might not be the most well-maintained module. These helper functions are very short. Why not have a version of them in our repo? WDYT @Yoni-Starkware  @meship-starkware ?
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1675#-OC2BZMf0EBcWwWAIVwV:-OC2LgkE-wXXHtg-G1dX:b-p2tmxj) ([raw file](https://github.com/starkware-libs/sequencer/blob/e79c663bc448be3bd3428a658c65f80ea8355d2b/crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs#L32)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Note to self: this is the only syscalls that is affected by the builtins gas cost, meaning that the fact that this gas cost is right means that the builtins costs are right  :)
</blockquote></details>

Note that they are not the same though. Native costs 10,000 more.
Even if they were the same, the fact that this gas cost is correct doesn't necessarily mean that the builtin costs are correct. It just means that our current tests don't catch any mistakes.

**Review by PearsonWhite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1675)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 740 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1675#-OBzuudl3wSuXm1u7pXO:-OC3vr-M8Bx4YDI44tHQ:b-i2xhli) ([raw file](https://github.com/starkware-libs/sequencer/blob/3854b86f39027ee94f190addc2b7ef861aa6aadb/crates/blockifier/src/execution/native/syscall_handler.rs#L740)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Okay, I understand. So the type for `Secp256Point` coordinates is supposed to be `BigInt<4>` according to the definition of the curve.
Two further comments:
1. I think we shouldn't go through `BigUint`. To get `Secp256r1Point` from `Secp256Point`, our current conversion is `U256` -> `BigUint` -> `BigInt<4>`. We should do a direct conversion, as Xander suggested.
2. Is it good practice to use functions from `starknet_stub.rs`? It is a module containing a mock syscall handler for tests. It might not be the most well-maintained module. These helper functions are very short. Why not have a version of them in our repo? WDYT @Yoni-Starkware  @meship-starkware ?
</blockquote></details>

Added `u256_to_big4int` and used that.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1675)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @PearsonWhite)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 867 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1675#-OC5DodhCsx_fgZkAX8a:-OC5DodhCsx_fgZkAX8b:b4s59rz) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5c6ab09e4344e43d93a6de3f04ffa857a3d87f8/crates/blockifier/src/execution/native/syscall_handler.rs#L867)):*
> ```XML
> 
>     (hi << 128) + lo
> }
> ```

Not needed anymore, right?

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1675)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @PearsonWhite, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1675#-OC2BZMf0EBcWwWAIVwV:-OC7_MZ074sFfONH9_MB:bm8xr2n) ([raw file](https://github.com/starkware-libs/sequencer/blob/e79c663bc448be3bd3428a658c65f80ea8355d2b/crates/blockifier/src/execution/syscalls/syscall_tests/secp.rs#L32)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Note that they are not the same though. Native costs 10,000 more.
Even if they were the same, the fact that this gas cost is correct doesn't necessarily mean that the builtin costs are correct. It just means that our current tests don't catch any mistakes.
</blockquote></details>

The 10K is a known issue. We double charge on entry point

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1675)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @PearsonWhite)

**Review by PearsonWhite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1675)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 867 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1675#-OC5DodhCsx_fgZkAX8a:-OC9KRSpALctkfWNpplz:b5he6s) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5c6ab09e4344e43d93a6de3f04ffa857a3d87f8/crates/blockifier/src/execution/native/syscall_handler.rs#L867)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Not needed anymore, right?
</blockquote></details>

`ark_ff` uses `BigUint` in places like `PrimeField`, so I think we're better off keeping it in. Otherwise we will have a Uint in the form of BigInt<4>, which would be confusing and only exist for the purposes of avoiding the conversion.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1675#-:-OC9Q4yB1QzW940Ykyax:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware)

**Review by meship-starkware — APPROVED** [review]
> Dismissed @avi-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1675)* status: all files reviewed, 1 unresolved discussion (waiting on @PearsonWhite)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1675)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PearsonWhite)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1675#-OCCUWBT7Wo2gP1CfbeJ:-OCCUWBT7Wo2gP1CfbeK:b-r1ggd8) (no related file):*
Please rebase and resolve the conflicts.

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1675)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PearsonWhite)

**Review by avi-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1675)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PearsonWhite)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1675)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PearsonWhite)

**Pull request merged**
