### PR TITLE
chore(mempool): add transaction queue content

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/770)

### CODE REVIEW

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/770)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/770#-O6p2S9c8KnQl3nYcgDo:-O6p2S9c8KnQl3nYcgDp:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/f4eb52a40e035fc37a5ce2e0b6ad72dcba516784/crates/mempool/src/transaction_queue_test_utils.rs#L14)):*
> ```XML
> /// Enables customized (and potentially inconsistent) creation for unit testing.
> #[derive(Debug, Default)]
> pub struct TransactionQueueContent {
> ```





_Suggestion:_
```XML
TransactionQueuePartialContent
```
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/770#-O6p7cF_2_o-Qr9WA5RY:-O6p7cF_2_o-Qr9WA5RZ:behhrk2) ([raw file](https://github.com/starkware-libs/sequencer/blob/f4eb52a40e035fc37a5ce2e0b6ad72dcba516784/crates/mempool/src/transaction_queue_test_utils.rs#L37)):*
> ```XML
>             .chain(pending_queue.iter().map(|tx| tx.clone().0))
>             .map(|tx| (tx.sender_address, tx))
>             .collect();
> ```

does this work? avoiding one clone



_Suggestion:_
```XML
        let address_to_tx: HashMap<ContractAddress, TransactionReference> = priority_queue
            .iter()
            .map(|tx| &tx.0)
            .chain(pending_queue.iter().map(|tx| &tx.0))
            .map(|tx| (tx.sender_address, tx.clone()))  
            .collect();
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/770)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/770#-O6p2S9c8KnQl3nYcgDo:-O6phR183PjFpjdMVUxo:b797wxr) ([raw file](https://github.com/starkware-libs/sequencer/blob/f4eb52a40e035fc37a5ce2e0b6ad72dcba516784/crates/mempool/src/transaction_queue_test_utils.rs#L14)):*
> ```XML
> /// Enables customized (and potentially inconsistent) creation for unit testing.
> #[derive(Debug, Default)]
> pub struct TransactionQueueContent {
> ```

But it's not partial.
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/770#-O6p7cF_2_o-Qr9WA5RY:-O6piLjr-nkJOeuK5edq:b-7zv58k) ([raw file](https://github.com/starkware-libs/sequencer/blob/f4eb52a40e035fc37a5ce2e0b6ad72dcba516784/crates/mempool/src/transaction_queue_test_utils.rs#L37)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

does this work? avoiding one clone
</blockquote></details>

It works, but it doesn't save the clones. 
Actually, I prefer your suggestion, having a single clone in one place is better.

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/770)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/770#-O6p2S9c8KnQl3nYcgDo:-O6tnPjg-DKkJaIRzR3N:b-3sy8hx) ([raw file](https://github.com/starkware-libs/sequencer/blob/f4eb52a40e035fc37a5ce2e0b6ad72dcba516784/crates/mempool/src/transaction_queue_test_utils.rs#L14)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

But it's not partial.
</blockquote></details>

It is partial because `gas_price_threshold` is not included here, but it was discussed offline, and the decision was made to keep the original name as it is in `MempoolContent`.
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/770#-O6toBGP6d3YgImgoymw:-O6toBGP6d3YgImgoymx:b-yht6dz) ([raw file](https://github.com/starkware-libs/sequencer/blob/7810e6b83c6d2895b0c6de9725fb9260adc541a9/crates/mempool/src/transaction_queue_test_utils.rs#L49)):*
> ```XML
> }
> 
> impl From<TransactionQueueContent> for TransactionQueue {
> ```

are you using both from functions?

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/770)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/770#-O6yi_9F8O0mnLq5zUPW:-O6yi_9GBLEl58Rrwa-K:bwoto4i) ([raw file](https://github.com/starkware-libs/sequencer/blob/7810e6b83c6d2895b0c6de9725fb9260adc541a9/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
> ```XML
>     priority_queue: BTreeSet<PriorityTransaction>,
>     pending_queue: BTreeSet<PendingTransaction>,
>     address_to_tx: HashMap<ContractAddress, TransactionReference>,
> ```

Should this be part of this mock as a field?
Do we need to assert its contents in tests?



_Code quote:_
```XML
    address_to_tx: HashMap<ContractAddress, TransactionReference>,
```
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 37 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/770#-O6yiexG5AXevK2o5bEe:-O6yiexG5AXevK2o5bEf:bxat334) ([raw file](https://github.com/starkware-libs/sequencer/blob/7810e6b83c6d2895b0c6de9725fb9260adc541a9/crates/mempool/src/transaction_queue_test_utils.rs#L37)):*
> ```XML
>             .chain(pending_queue.iter().map(|tx| &tx.0))
>             .map(|tx| (tx.sender_address, tx.clone()))
>             .collect();
> ```

Are the 3 `collect`s all necessary? (each one is an allocation)



_Code quote:_
```XML
        let priority_queue: BTreeSet<PriorityTransaction> =
            priority_txs.into_iter().map(Into::into).collect();

        let pending_queue: BTreeSet<PendingTransaction> =
            pending_txs.into_iter().map(Into::into).collect();

        let address_to_tx: HashMap<ContractAddress, TransactionReference> = priority_queue
            .iter()
            .map(|tx| &tx.0)
            .chain(pending_queue.iter().map(|tx| &tx.0))
            .map(|tx| (tx.sender_address, tx.clone()))
            .collect();
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/770)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/770#-O6yi_9F8O0mnLq5zUPW:-O748bwc-EfEqT6sV7z5:b-zdpo5a) ([raw file](https://github.com/starkware-libs/sequencer/blob/7810e6b83c6d2895b0c6de9725fb9260adc541a9/crates/mempool/src/transaction_queue_test_utils.rs#L17)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Should this be part of this mock as a field?
Do we need to assert its contents in tests?
</blockquote></details>

Good question.
The `TransactionQueueContent` is used to test the `TransactinoQueue` functionality.
I think we need to check this field as well, as it can cover a potential bug. For example, when the pending/priority transaction queues are aligned, but for some reason, the `tx_to_address` is not.
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 37 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/770#-O6yiexG5AXevK2o5bEe:-O73sZ6q6TNnFMt16Hqf:b-vom35s) ([raw file](https://github.com/starkware-libs/sequencer/blob/7810e6b83c6d2895b0c6de9725fb9260adc541a9/crates/mempool/src/transaction_queue_test_utils.rs#L37)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Are the 3 `collect`s all necessary? (each one is an allocation)
</blockquote></details>

Stale,
I've used Builder, and there is no collect `anymore`.

**Comment by MohammadNassar1** [comment]
Will reopen this PR once `MempoolContentBuilder` is merged.

**Pull request closed without merging**
