### PR TITLE
test(mempool): test get_txs while updating gas price

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/563)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/563)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 364 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/563#-O4u7wlm5AgasQQNyD_L:-O4u7wlm5AgasQQNyD_M:b-9dsgdv) ([raw file](https://github.com/starkware-libs/sequencer/blob/9428a36d7214d2efce67e34f39d6adb7ad755540/crates/mempool/src/mempool_test.rs#L364)):*
> ```XML
> 
> #[rstest]
> fn test_get_txs_with_different_gas_price_threshold() {
> ```

This flow would never happen, right?



_Code quote:_
```XML
test_get_txs_with_different_gas_price_threshold
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/563)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 364 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/563#-O4u7wlm5AgasQQNyD_L:-O4uUIft7kMQYOKuTNNI:bgwn0kj) ([raw file](https://github.com/starkware-libs/sequencer/blob/9428a36d7214d2efce67e34f39d6adb7ad755540/crates/mempool/src/mempool_test.rs#L364)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This flow would never happen, right?
</blockquote></details>

Why?
This flow tests the case where the gas price decreases, and ofc it can happen.

**Review by giladchase — COMMENTED** [review]
rebase

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/563#-:-O57po2z9kIpQo4FQDlj:b-l6u88n)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

**Review by MohammadNassar1 — COMMENTED** [review]
done.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/563#-:-O57yB-e1eiIPd9-Ig_D:b-7rl0jd)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 364 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/563#-O4u7wlm5AgasQQNyD_L:-O588DXkBIp9_t_9XQAR:b-ftiold) ([raw file](https://github.com/starkware-libs/sequencer/blob/768e2484f99b7f72f68673fd4c95119284b2c409/crates/mempool/src/mempool_test.rs#L364)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why?
This flow tests the case where the gas price decreases, and ofc it can happen.
</blockquote></details>

Called commit block.
Now it simulates a valid flow.

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/563)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/563#-O5NGwomCFr8iBnXa9x7):*
get_txs



_Code quote:_
```
get_ttxs
```
___
*[`crates/mempool/src/mempool_test.rs` line 380 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/563#-O5NIer4A_9XfA-YWVeY:-O5NIer4A_9XfA-YWVeZ:brwfydt) ([raw file](https://github.com/starkware-libs/sequencer/blob/2964f5677728ac9fc118b8321c8726f60cf7de65/crates/mempool/src/mempool_test.rs#L380)):*
> ```XML
>     // Test.
>     // High gas price threshold, no transactions should be returned.
>     mempool.update_gas_price_threshold(1000000000000);
> ```

Does this represent an initial threshold? If so, it should be moved to the setup.
___
*[`crates/mempool/src/mempool_test.rs` line 385 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/563#-O5NJUb90KE014ZtJznm:-O5NJUb90KE014ZtJznn:bz5qjkq) ([raw file](https://github.com/starkware-libs/sequencer/blob/2964f5677728ac9fc118b8321c8726f60cf7de65/crates/mempool/src/mempool_test.rs#L385)):*
> ```XML
> 
>     // Updating the gas price threshold should happen in a new block creation.
>     assert!(mempool.commit_block(HashMap::default()).is_ok());
> ```

Isn't the comment enough? Does the function update the gas threshold?
___
*[`crates/mempool/src/transaction_queue.rs` line 104 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/563#-O5NJmDy5mSGP7fQXRzM:-O5NJmDy5mSGP7fQXRzN:b-drtv04) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb59b7917010c617729f19b150810864feeddd13/crates/mempool/src/transaction_queue.rs#L104)):*
> ```XML
> 
>         // Split off the pending queue at the given transaction higher than the threshold.
>         let txs_over_threshold = self.pending_queue.split_off(&tmp_split_tx).into_iter().skip(1);
> ```

can you explain this change?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/563)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/563#-O5NGwomCFr8iBnXa9x7):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

get_txs
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 380 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/563#-O5NIer4A_9XfA-YWVeY:-O5NmTfM1bTZ-A12G5fF:bfgp3cm) ([raw file](https://github.com/starkware-libs/sequencer/blob/2964f5677728ac9fc118b8321c8726f60cf7de65/crates/mempool/src/mempool_test.rs#L380)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Does this represent an initial threshold? If so, it should be moved to the setup.
</blockquote></details>

It's some high gas price, that is updated once the consensus round starts.
___
*[`crates/mempool/src/mempool_test.rs` line 385 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/563#-O5NJUb90KE014ZtJznm:-O5NoGp08L0oSNNZ-8kz:b-sk0uub) ([raw file](https://github.com/starkware-libs/sequencer/blob/2964f5677728ac9fc118b8321c8726f60cf7de65/crates/mempool/src/mempool_test.rs#L385)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Isn't the comment enough? Does the function update the gas threshold?
</blockquote></details>

`commit_block` doesn't update the gas price.
Here I meant that calling `update_gas_price_threshold` should be by the start of the consensus round, and cannot be done immediately after the `get_txs`.
___
*[`crates/mempool/src/transaction_queue.rs` line 104 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/563#-O5NJmDy5mSGP7fQXRzM:-O5Nou5n-qWYsE8p89Of:b-rsqy8v) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb59b7917010c617729f19b150810864feeddd13/crates/mempool/src/transaction_queue.rs#L104)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

can you explain this change?
</blockquote></details>

This is not part of ht the PR.
Rebased

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/563)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

**Review by ayeletstarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/563)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/563#-:-O5S6KKH61WbaCyRqoHY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/563)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
