### PR TITLE
chore(blockifier_reexecution): add readme file

### PR DESCRIPTION
**Pull request by aner-starkware**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2212)* status: all files reviewed, 13 unresolved discussions (waiting on @aner-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD2m0GBHLsPB5sMVPr:-OCD2m0GBHLsPB5sMVPs:b-xz83q9) (no related file):*
can you add a section for developers, describing how to add a new block to the offline tests suite? e.g. the list of commands needed to generate the data and then upload it, and how to add a test case for the new block 
___
*[`crates/blockifier_reexecution/README.md` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD0xKO6lQxsV3S_Dw9:-OCD0xKO6lQxsV3S_DwA:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L5)):*
> ```Markdown
> ## Description
> 
> The blockier reexecution crate is intended to verify blockifier changes do not break backwards compatibility when executing old blocks. Reexecution of old blocks with the blockifier should return the same expected state-diff as when originally run.
> ```





_Suggestion:_
```Markdown
output
```
___
*[`crates/blockifier_reexecution/README.md` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD10yv12FDZr8sh2E3:-OCD10yv12FDZr8sh2E4:b-gsod8f) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L9)):*
> ```Markdown
> ## Running modes via CLI
> 
> Reexecution tests should be run in release mode, as otherwise these tests can be very long. Reexecution can be run via CLI in the following modes: 
> ```

not necessarily true for RPC mode - the bottleneck in this case would be network usage. I would move this remark to the offline section



_Code quote:_
```Markdown
Reexecution tests should be run in release mode, as otherwise these tests can be very long.
```
___
*[`crates/blockifier_reexecution/README.md` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD1Bid92jAzp2VCwKr:-OCD1Bid92jAzp2VCwKs:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L12)):*
> ```Markdown
> 
> - **RPC test:**
> Reexecution test where the data required for reexecuting the block, as well as the expected resulting state diff, are received using RPC calls. It is necessary to supply a node url for these RPC calls. Note that free urls (as, e.g., used in the tests) will most likely Err due to the large amount of RPC calls. 
> ```





_Suggestion:_
```Markdown
retrieved
```
___
*[`crates/blockifier_reexecution/README.md` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD1Ip-1TUxjuNHNHiQ:-OCD1Ip-1TUxjuNHNHiR:b-r6qy3e) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L12)):*
> ```Markdown
> 
> - **RPC test:**
> Reexecution test where the data required for reexecuting the block, as well as the expected resulting state diff, are received using RPC calls. It is necessary to supply a node url for these RPC calls. Note that free urls (as, e.g., used in the tests) will most likely Err due to the large amount of RPC calls. 
> ```

I think this is the terminology



_Suggestion:_
```Markdown
RPC provider
```
___
*[`crates/blockifier_reexecution/README.md` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD1OOQ3aWSDoqSZM-3:-OCD1OOR7rLrw-ct454E:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L12)):*
> ```Markdown
> 
> - **RPC test:**
> Reexecution test where the data required for reexecuting the block, as well as the expected resulting state diff, are received using RPC calls. It is necessary to supply a node url for these RPC calls. Note that free urls (as, e.g., used in the tests) will most likely Err due to the large amount of RPC calls. 
> ```





_Suggestion:_
```Markdown
hit rate limit errors
```
___
*[`crates/blockifier_reexecution/README.md` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD1Zm69ITI0DPiuztg:-OCD1Zm69ITI0DPiuzth:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L17)):*
> ```Markdown
> ```
> 
> - **RPC test with Writing to JSON file:**
> ```





_Suggestion:_
```Markdown
**RPC test with preparation for offline reexecution:**
```
___
*[`crates/blockifier_reexecution/README.md` line 30 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD1pAG9ZDy2IToH8J3:-OCD1pAH467hiZYS_msH:bbzky63) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L30)):*
> ```Markdown
> ```
> 
> Additionally, uploading\downloading the offline reexecution files can be done via CLI.
> ```

separate between upload and download: upload will be a permissioned operation, whereas download should be open



_Code quote:_
```Markdown
Additionally, uploading\downloading the offline reexecution files can be done via CLI.
```
___
*[`crates/blockifier_reexecution/README.md` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD20v1EO-NPO9ROyVy:-OCD20v1EO-NPO9ROyVz:b3shvo4) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L49)):*
> ```Markdown
> - **Full block reexecution tests:** These tests take a long time unless run in release mode, hence they are under #[ignore]. These tests can be run by the command
> ```
> cargo test --release -p blockifier_reexecution -- --ignored
> ```

you sure this is the command? doesn't the CI do something else?



_Code quote:_
```Markdown
cargo test --release -p blockifier_reexecution -- --ignored
```
___
*[`crates/blockifier_reexecution/README.md` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD254j0qu55E5s9yB1:-OCD254j0qu55E5s9yB2:bq7rkq3) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L52)):*
> ```Markdown
> ```
> 
> - **RPC tests:** These tests require sending RPC requests to an RPC url; As these tests use a free node url, they sometimes Err due to RPC Errors. These tests are under the `blockifier_regression_https_testing` flag and are compiled, but not run, in the CI.
> ```

please mention what these tests check (that RPC responses can be properly deserialized)



_Code quote:_
```Markdown
**RPC tests:** 
```
___
*[`crates/blockifier_reexecution/README.md` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD2Bvi6fEdeft7mPjZ:-OCD2Bvi6fEdeft7mPj_:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L52)):*
> ```Markdown
> ```
> 
> - **RPC tests:** These tests require sending RPC requests to an RPC url; As these tests use a free node url, they sometimes Err due to RPC Errors. These tests are under the `blockifier_regression_https_testing` flag and are compiled, but not run, in the CI.
> ```





_Suggestion:_
```Markdown
hit rate limit errors
```
___
*[`crates/blockifier_reexecution/README.md` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD2NgV1wWkSm5XVyNU:-OCD2NgV1wWkSm5XVyNV:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L56)):*
> ```Markdown
> ```
> cargo test -p blockifier_reexecution --features blockifier_regression_https_testing
> ```
> ```





_Suggestion:_
```Markdown
To run these tests locally, it is recommended to use your own RPC provider (set in the `TEST_URL` environment variable):
```
TEST_URL=<node_url> cargo test -p blockifier_reexecution --features blockifier_regression_https_testing
```
```
___
*[`crates/blockifier_reexecution/README.md` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD2hAA0qDeeCUmLHHz:-OCD2hAA0qDeeCUmLHI-:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L66)):*
> ```Markdown
> In order to run all the above tests in a single command:
> ```
> cargo test --release -p blockifier_reexecution --features blockifier_regression_https_testing -- --include-ignored
> ```





_Suggestion:_
```Markdown
TEST_URL=<node_url> cargo test --release -p blockifier_reexecution --features blockifier_regression_https_testing -- --include-ignored
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2212)* status: all files reviewed, 13 unresolved discussions (waiting on @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD2m0GBHLsPB5sMVPr:-OCDF1XP4-jX61gWTvXe:b-tw5nm4) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you add a section for developers, describing how to add a new block to the offline tests suite? e.g. the list of commands needed to generate the data and then upload it, and how to add a test case for the new block
</blockquote></details>

Added a TODO. This should be in a different PR, after upload/download is integrated.
___
*[`crates/blockifier_reexecution/README.md` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD10yv12FDZr8sh2E3:-OCDFP5eBXA90XzdK8VM:burs6a3) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not necessarily true for RPC mode - the bottleneck in this case would be network usage. I would move this remark to the offline section
</blockquote></details>

Done. However, I think it will be true for the RPC case once we add concurrency to the RPC.
___
*[`crates/blockifier_reexecution/README.md` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD1Ip-1TUxjuNHNHiQ:-OCDG3gc3vfMTyHW1HYH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L12)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think this is the terminology
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/README.md` line 30 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD1pAG9ZDy2IToH8J3:-OCDGGPYCAawqK2tJVUj:btqdov7) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L30)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

separate between upload and download: upload will be a permissioned operation, whereas download should be open
</blockquote></details>

Added a TODO; will do it in the PR where upload&download are explained.
___
*[`crates/blockifier_reexecution/README.md` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD20v1EO-NPO9ROyVy:-OCDGNPP-VEC7JNkm6s7:b5yuksm) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L49)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you sure this is the command? doesn't the CI do something else?
</blockquote></details>

In the CI it's `--include-ignored`, same as in the run all tests in a single command below.
___
*[`crates/blockifier_reexecution/README.md` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD254j0qu55E5s9yB1:-OCDI6JbBQvfk75sC8XY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L52)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please mention what these tests check (that RPC responses can be properly deserialized)
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/README.md` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD0xKO6lQxsV3S_Dw9:-OCDFC_D15VdSWI_6AAB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L5)):*
> ```Markdown
> ## Description
> 
> The blockier reexecution crate is intended to verify blockifier changes do not break backwards compatibility when executing old blocks. Reexecution of old blocks with the blockifier should return the same expected state-diff as when originally run.
> ```

Done.
___
*[`crates/blockifier_reexecution/README.md` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD1Bid92jAzp2VCwKr:-OCDFp5d2VmNT_Wk_bcs:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L12)):*
> ```Markdown
> 
> - **RPC test:**
> Reexecution test where the data required for reexecuting the block, as well as the expected resulting state diff, are received using RPC calls. It is necessary to supply a node url for these RPC calls. Note that free urls (as, e.g., used in the tests) will most likely Err due to the large amount of RPC calls. 
> ```

Done.
___
*[`crates/blockifier_reexecution/README.md` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD1OOQ3aWSDoqSZM-3:-OCDG486AS0pB_NTxNSK:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L12)):*
> ```Markdown
> 
> - **RPC test:**
> Reexecution test where the data required for reexecuting the block, as well as the expected resulting state diff, are received using RPC calls. It is necessary to supply a node url for these RPC calls. Note that free urls (as, e.g., used in the tests) will most likely Err due to the large amount of RPC calls. 
> ```

Done.
___
*[`crates/blockifier_reexecution/README.md` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD1Zm69ITI0DPiuztg:-OCDI3cX9vDDWFAGQ6YA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L17)):*
> ```Markdown
> ```
> 
> - **RPC test with Writing to JSON file:**
> ```

Done.
___
*[`crates/blockifier_reexecution/README.md` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD2Bvi6fEdeft7mPjZ:-OCDI83327nb44mGT5si:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L52)):*
> ```Markdown
> ```
> 
> - **RPC tests:** These tests require sending RPC requests to an RPC url; As these tests use a free node url, they sometimes Err due to RPC Errors. These tests are under the `blockifier_regression_https_testing` flag and are compiled, but not run, in the CI.
> ```

Done.
___
*[`crates/blockifier_reexecution/README.md` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD2NgV1wWkSm5XVyNU:-OCDI8Vt585zKtSzOmpS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L56)):*
> ```Markdown
> ```
> cargo test -p blockifier_reexecution --features blockifier_regression_https_testing
> ```
> ```

Done.
___
*[`crates/blockifier_reexecution/README.md` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD2hAA0qDeeCUmLHHz:-OCDI9UBDWJEmd-9c-2K:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L66)):*
> ```Markdown
> In order to run all the above tests in a single command:
> ```
> cargo test --release -p blockifier_reexecution --features blockifier_regression_https_testing -- --include-ignored
> ```

Done.

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2212)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/README.md` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD10yv12FDZr8sh2E3:-OCEFe-x5C166XhyQkS5:b-splo3p) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

per tx, read requests from RPC will stay sequential anyway - execution depends on the result.
activating *blockifier* "optimistic concurrency" will speed up *computation* (CPU) but not RPC requests;
am i missing something? how will RPC tests be sped up?
</blockquote></details>

Since the blocks themselves will be run in parallel, I'm quite sure that there will still be a significant speedup when using release, even though, yes, the main bottleneck will remain unaffected.
___
*[`crates/blockifier_reexecution/README.md` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD20v1EO-NPO9ROyVy:-OCEGAjKAzkYsgIoYZ2X:b-1ahm3n) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L49)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

so why `--ignored` and not `--include-ignored`?
</blockquote></details>

Because here I separated to the three different test types. If one wants to only run the reexecution tests, this is the way to go. If one wants to run all the tests, then he uses the single command below. 
___
*[`crates/blockifier_reexecution/README.md` line 54 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCDM6QxCvkLG4mdIVMW:-OCESuYf8KfzKymBRpTt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b6bdc85fa8162a6960a4b4a3aff26ae81df1992e/crates/blockifier_reexecution/README.md#L54)):*
> ```Markdown
> 
> - **RPC tests:** These tests check that RPC responses can be properly deserialized. They require sending RPC requests to an RPC provider; These tests are under the `blockifier_regression_https_testing` flag and are compiled, but not run, in the CI.
> These tests use a free node url by default, so they sometimes Err due to RPC Errors; hence, it is recommended to use your own RPC provider (set in the `TEST_URL` environment variable).
> ```

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2212)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

___
*[`crates/blockifier_reexecution/README.md` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD10yv12FDZr8sh2E3:-OCEWX-s2lRyxCGwCNvi:bjnf67h) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L9)):*
> Since the blocks themselves will be run in parallel

blocks will be run in parallel in debug mode as well

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/README.md` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2212#-OCD10yv12FDZr8sh2E3:-OCICuHEErXMXrtBxpUn:bns3w60) ([raw file](https://github.com/starkware-libs/sequencer/blob/d54311f4d33d2be878a946c43c94d8fa70a28a13/crates/blockifier_reexecution/README.md#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

> Since the blocks themselves will be run in parallel

blocks will be run in parallel in debug mode as well
</blockquote></details>

The thing is that in release mode there is only one bottleneck, while when running without there are two bottlenecks. So, I'm not sure there won't be a significant runtime difference, but it's hard to predict without testing.

**Pull request merged**
