### PR TITLE
refactor(starknet_batcher): validate flow refactor

### PR DESCRIPTION
**Pull request by dafnamatsry**

### CODE REVIEW

**Comment by dafnamatsry** [comment]
* **#2441** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2441?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2441?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yael-Starkware — COMMENTED** [review]
This is a bit overwhelming,  can you split to smaller PRs?
if not, can you please give an overview of the changes introduced here?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-:-ODL5J6Y-SfEnO9KemAD:bh6qpnp)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @alonh5)

**Review by dafnamatsry — COMMENTED** [review]
Done (see additional 2 PRs in the stack).
This is still a big PR, but it's a bit harder to split it (mostly because of how it affects the tests).
What is done here:
* Delete the `get_proposal_status` and `await_proposal_commitment` from the proposal_manager.
* Refactor `send_proposal_content` accordingly.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-:-ODLo8dH6THuQYuu6MtA:b-8xlm0u)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @alonh5)

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2441)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @alonh5 and @dafnamatsry)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 70 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-OD__dlWCs6AI-J1orRV:-OD__dlWCs6AI-J1orRW:behima3) ([raw file](https://github.com/starkware-libs/sequencer/blob/a9f68cbdc1858a107e8ca7208175592e53536f47/crates/starknet_batcher/src/batcher_test.rs#L70)):*
> ```XML
> 
> fn proposal_commitment() -> ProposalCommitment {
>     ProposalOutput::from(BlockExecutionArtifacts::create_for_testing()).commitment
> ```

The intention was not to give the ProposalCommitment a default value in order to verify that the batcher indeed passed the correct value from the block_builder to the consensus.



_Code quote:_
```XML
ProposalOutput::from(BlockExecutionArtifacts::create_for_testing()).commitment
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 208 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-OD_b6XBBodtUlggyqvv:-OD_b6XBBodtUlggyqvw:b-t8kvve) ([raw file](https://github.com/starkware-libs/sequencer/blob/a9f68cbdc1858a107e8ca7208175592e53536f47/crates/starknet_batcher/src/batcher_test.rs#L208)):*
> ```XML
>         &mut proposal_manager,
>         PROPOSAL_ID,
>         Ok(ProposalOutput::from(BlockExecutionArtifacts::create_for_testing())),
> ```

same comment for the default value,
in other tests as well



_Code quote:_
```XML
ProposalOutput::from(BlockExecutionArtifacts::create_for_testing())
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 413 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-OD_bHYJ1bX5bg4TXKK2:-OD_bHYJ1bX5bg4TXKK3:b5cjihi) ([raw file](https://github.com/starkware-libs/sequencer/blob/a9f68cbdc1858a107e8ca7208175592e53536f47/crates/starknet_batcher/src/batcher_test.rs#L413)):*
> ```XML
>         &mut proposal_manager,
>         PROPOSAL_ID,
>         Ok(ProposalOutput::from(BlockExecutionArtifacts::create_for_testing())),
> ```

same comment for the default value



_Code quote:_
```XML
ProposalOutput::from(BlockExecutionArtifacts::create_for_testing()
```
___
*[`crates/starknet_batcher/src/batcher.rs` line 322 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-OD_Y-p4AWstSC13HHKe:-OD_Y-p4AWstSC13HHKf:b-1diru5) ([raw file](https://github.com/starkware-libs/sequencer/blob/a9f68cbdc1858a107e8ca7208175592e53536f47/crates/starknet_batcher/src/batcher.rs#L322)):*
> ```XML
>         // TODO: Consider removing the proposal from the proposal manager and keep it in the batcher
>         // for decision reached.
>         self.propose_tx_streams.remove(&proposal_id);
> ```

what happens if there are no new transactions in the block - so the stream is empty , but the block is not closed yet
(no timeout and no block full)?



_Code quote:_
```XML
self.propose_tx_streams.remove(&proposal_id);
```
___
*[`crates/starknet_batcher/src/batcher.rs` line 374 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-OD_YqIS9S6NMXkJ8rI8:-OD_YqIS9S6NMXkJ8rI9:b-nrxodl) ([raw file](https://github.com/starkware-libs/sequencer/blob/a9f68cbdc1858a107e8ca7208175592e53536f47/crates/starknet_batcher/src/batcher.rs#L374)):*
> ```XML
>         let completed_proposals = self.proposal_manager.get_completed_proposals().await;
>         let guard = completed_proposals.lock().await;
>         let proposal_result = guard.get(&proposal_id).expect("Proposal should exist");
> ```

Doesn't seem right to get a field from the proposal manager and change it here in the batcher.
I assume this is just a step towards the refactor and eventually completed_proposals will be a part of the batcher. right?



_Code quote:_
```XML
        let completed_proposals = self.proposal_manager.get_completed_proposals().await;
        let guard = completed_proposals.lock().await;
        let proposal_result = guard.get(&proposal_id).expect("Proposal should exist");
```
___
*[`crates/starknet_batcher/src/batcher.rs` line 374 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-OD_Za1V4xbe4jxKaxhw:-OD_Za1W3Mac2WIei-0m:b-z8mil0) ([raw file](https://github.com/starkware-libs/sequencer/blob/a9f68cbdc1858a107e8ca7208175592e53536f47/crates/starknet_batcher/src/batcher.rs#L374)):*
> ```XML
>         let completed_proposals = self.proposal_manager.get_completed_proposals().await;
>         let guard = completed_proposals.lock().await;
>         let proposal_result = guard.get(&proposal_id).expect("Proposal should exist");
> ```

I'm not sure it's ideal to hide the panic inside the function (even though it is well-documented). It might be more straightforward and easier to understand if it were part of the calling function instead.



_Code quote:_
```XML
.expect("Proposal should exist");
```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2441)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 322 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-OD_Y-p4AWstSC13HHKe:-OD_dNLx-qjUYrhTqdPO:b-ds2044) ([raw file](https://github.com/starkware-libs/sequencer/blob/a9f68cbdc1858a107e8ca7208175592e53536f47/crates/starknet_batcher/src/batcher.rs#L322)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

what happens if there are no new transactions in the block - so the stream is empty , but the block is not closed yet
(no timeout and no block full)?
</blockquote></details>

It wouldn't reach this point.
`recv_many` will block until either there are some txs in the channel or if the channel is closed (in which case the block is closed).
___
*[`crates/starknet_batcher/src/batcher.rs` line 374 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-OD_YqIS9S6NMXkJ8rI8:-OD_eOwYE7OdDe_d8W0D:bwfsxux) ([raw file](https://github.com/starkware-libs/sequencer/blob/a9f68cbdc1858a107e8ca7208175592e53536f47/crates/starknet_batcher/src/batcher.rs#L374)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Doesn't seem right to get a field from the proposal manager and change it here in the batcher.
I assume this is just a step towards the refactor and eventually completed_proposals will be a part of the batcher. right?
</blockquote></details>

Yes, the proposal manger will be deleted in a following PR.
Note that the batcher only reads the field, and doesn't change it.
___
*[`crates/starknet_batcher/src/batcher.rs` line 374 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-OD_Za1V4xbe4jxKaxhw:-OD_gGMB5hfe13N0QBpS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a9f68cbdc1858a107e8ca7208175592e53536f47/crates/starknet_batcher/src/batcher.rs#L374)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I'm not sure it's ideal to hide the panic inside the function (even though it is well-documented). It might be more straightforward and easier to understand if it were part of the calling function instead.
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 70 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-OD__dlWCs6AI-J1orRV:-OD_iUYH5j82dkFsP1Rc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a9f68cbdc1858a107e8ca7208175592e53536f47/crates/starknet_batcher/src/batcher_test.rs#L70)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

The intention was not to give the ProposalCommitment a default value in order to verify that the batcher indeed passed the correct value from the block_builder to the consensus.
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 208 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-OD_b6XBBodtUlggyqvv:-OD_iWP7EzbxaPcPpQR8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a9f68cbdc1858a107e8ca7208175592e53536f47/crates/starknet_batcher/src/batcher_test.rs#L208)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

same comment for the default value,
in other tests as well
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 413 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-OD_bHYJ1bX5bg4TXKK2:-OD_iX__87fg0zbO3DOG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a9f68cbdc1858a107e8ca7208175592e53536f47/crates/starknet_batcher/src/batcher_test.rs#L413)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

same comment for the default value
</blockquote></details>

Done.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2441)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @alonh5 and @dafnamatsry)

___
*[`crates/starknet_batcher/src/batcher.rs` line 322 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-OD_Y-p4AWstSC13HHKe:-ODe2DWv6Kz7OC3xxxAE:b-t0pe4z) ([raw file](https://github.com/starkware-libs/sequencer/blob/a9f68cbdc1858a107e8ca7208175592e53536f47/crates/starknet_batcher/src/batcher.rs#L322)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

It wouldn't reach this point.
`recv_many` will block until either there are some txs in the channel or if the channel is closed (in which case the block is closed).
</blockquote></details>

right, thanks!
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 71 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODe5WBtAPbcwxqbzpfv:-ODe5WBtAPbcwxqbzpfw:bp2nd0a) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher_test.rs#L71)):*
> ```XML
> fn proposal_commitment() -> ProposalCommitment {
>     ProposalCommitment {
>         state_diff_commitment: StateDiffCommitment(PoseidonHash(felt!(u128::try_from(7).unwrap()))),
> ```

wdyt about having the BlockExecutionArtifacts::create_for_testing() return a non-zero value?
Then we won't need this messy line.



_Code quote:_
```XML
state_diff_commitment: StateDiffCommitment(PoseidonHash(felt!(u128::try_from(7).unwrap()))),
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 154 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODe9yaN7DJAtLapvkp2:-ODe9yaN7DJAtLapvkp3:b-lq283x) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher_test.rs#L154)):*
> ```XML
> }
> 
> fn mock_validate_block(proposal_manager: &mut MockProposalManagerTraitWrapper) {
> ```

rename to fit both validate and propose



_Code quote:_
```XML
mock_validate_block
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 169 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODeAFzp4JZdQ-6Av3mf:-ODeAFzp4JZdQ-6Av3mg:bo0q7tb) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher_test.rs#L169)):*
> ```XML
> ) {
>     proposal_manager.expect_wrap_get_completed_proposals().times(1).return_once(move || {
>         async move { Arc::new(tokio::sync::Mutex::new(HashMap::from([(proposal_id, proposal_result)]))) }.boxed()
> ```

use tokio::sync::Mutex;



_Suggestion:_
```XML
Mutex
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 194 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODeBrY60xJbTzNHwS8y:-ODeBrY60xJbTzNHwS8z:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher_test.rs#L194)):*
> ```XML
>         deadline: deadline(),
>         retrospective_block_hash: None,
>         block_info: BlockInfo { block_number: INITIAL_HEIGHT, ..Default::default() },
> ```





_Suggestion:_
```XML
initial_block_info()
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 388 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODe8IucBctdGYIJVZ1N:-ODe8IucBctdGYIJVZ1O:bo7wo8p) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher_test.rs#L388)):*
> ```XML
>     let invalid_proposal_result = Err(ProposalError::BlockBuilderError(Arc::new(
>         BlockBuilderError::FailOnError(FailOnErrorCause::BlockFull),
>     )));
> ```

I think this can be a const, already being used by two functions.



_Code quote:_
```XML
    let invalid_proposal_result = Err(ProposalError::BlockBuilderError(Arc::new(
        BlockBuilderError::FailOnError(FailOnErrorCause::BlockFull),
    )));
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 410 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODe9g0b-AV7mfHc2r9c:-ODe9g0b-AV7mfHc2r9d:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher_test.rs#L410)):*
> ```XML
>         .expect_wrap_spawn_proposal()
>         .times(1)
>         .return_once(|_, _, _| { async move { Ok(()) } }.boxed());
> ```





_Suggestion:_
```XML
mock_validate_block(&mut proposal_manager);
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2441)* status: 1 of 4 files reviewed, 8 unresolved discussions (waiting on @alonh5 and @dafnamatsry)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 310 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODeD0Q5BQlSqVyk4Hqo:-ODeD0Q66EM6uq11zaZo:b-y0q7cg) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher_test.rs#L310)):*
> ```XML
>         block_info: initial_block_info(),
>     };
>     batcher.validate_block(validate_block_input).await.unwrap();
> ```

I think this code can be shared with batcher_with_validated_proposal() funciton



_Code quote:_
```XML
    let mut batcher = create_batcher(MockDependencies {
        proposal_manager,
        block_builder_factory,
        ..Default::default()
    });

    batcher.start_height(StartHeightInput { height: INITIAL_HEIGHT }).await.unwrap();

    let validate_block_input = ValidateBlockInput {
        proposal_id: PROPOSAL_ID,
        deadline: deadline(),
        retrospective_block_hash: None,
        block_info: initial_block_info(),
    };
    batcher.validate_block(validate_block_input).await.unwrap();
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2441)* status: 1 of 4 files reviewed, 9 unresolved discussions (waiting on @alonh5 and @dafnamatsry)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 169 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODeDnUL7xwiqMxEyj31:-ODeDnUL7xwiqMxEyj32:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher_test.rs#L169)):*
> ```XML
> ) {
>     proposal_manager.expect_wrap_get_completed_proposals().times(1).return_once(move || {
>         async move { Arc::new(tokio::sync::Mutex::new(HashMap::from([(proposal_id, proposal_result)]))) }.boxed()
> ```





_Suggestion:_
```XML
    proposal_result: ProposalResult<ProposalOutput>,
) {
    proposal_manager.expect_wrap_get_completed_proposals().times(1).return_once(move || {
        async move { Arc::new(tokio::sync::Mutex::new(HashMap::from([(PROPOSAL_ID, proposal_result)]))) }.boxed()
```

**Review by Yael-Starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2441)* status: 2 of 4 files reviewed, 9 unresolved discussions (waiting on @alonh5 and @dafnamatsry)

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2441)* status: 2 of 4 files reviewed, 10 unresolved discussions (waiting on @alonh5 and @dafnamatsry)

___
*[`crates/starknet_batcher/src/batcher.rs` line 372 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODeGmiH7JMEg2Ua8Y5U:-ODeGmiH7JMEg2Ua8Y5V:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher.rs#L372)):*
> ```XML
>     // Returns a completed proposal result, either its commitment or an error if the proposal
>     // failed.
>     // Panics if the proposal doesn't exist.
> ```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2441)* status: 1 of 4 files reviewed, 10 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 71 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODe5WBtAPbcwxqbzpfv:-ODeFjL23Fs9_2HesH5V:bockmfu) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher_test.rs#L71)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

wdyt about having the BlockExecutionArtifacts::create_for_testing() return a non-zero value?
Then we won't need this messy line.
</blockquote></details>

I reverted my change, so this is the line that was before.
But, what you suggested is exactly what I'm working on now as part of completely deleting the proposal manager.
So it will be in following PRs.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 154 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODe9yaN7DJAtLapvkp2:-ODeJS1BC_Ymlwwi6NVZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher_test.rs#L154)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

rename to fit both validate and propose
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 169 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODeAFzp4JZdQ-6Av3mf:-ODeHL6rBclQwLNkKuHq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher_test.rs#L169)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

use tokio::sync::Mutex;
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 310 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODeD0Q5BQlSqVyk4Hqo:-ODeIzK6-ifrO9llQk7p:b-t5uh4r) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher_test.rs#L310)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think this code can be shared with batcher_with_validated_proposal() funciton
</blockquote></details>

Could be. I prefer to do this kind of refactoring as a last step.
Note that all of the proposal manger mock code here will be deleted.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 388 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODe8IucBctdGYIJVZ1N:-ODeMs7N-4QcsLGOqVdu:b-sj2itq) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher_test.rs#L388)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think this can be a const, already being used by two functions.
</blockquote></details>

A bit problematic because of the `Arc`.
I can put only the `BlockBuilderError::FailOnError(FailOnErrorCause::BlockFull)` behind a const but IMO it won't make the test more readable.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 169 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODeDnUL7xwiqMxEyj31:-ODeH_GqAx0l0bRJSHgy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher_test.rs#L169)):*
> ```XML
> ) {
>     proposal_manager.expect_wrap_get_completed_proposals().times(1).return_once(move || {
>         async move { Arc::new(tokio::sync::Mutex::new(HashMap::from([(proposal_id, proposal_result)]))) }.boxed()
> ```

Done.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 194 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODeBrY60xJbTzNHwS8y:-ODeIjHb4xT_bUt9Q2Oz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher_test.rs#L194)):*
> ```XML
>         deadline: deadline(),
>         retrospective_block_hash: None,
>         block_info: BlockInfo { block_number: INITIAL_HEIGHT, ..Default::default() },
> ```

Done.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 410 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODe9g0b-AV7mfHc2r9c:-ODeLNEk4RnAHdWw4CFM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher_test.rs#L410)):*
> ```XML
>         .expect_wrap_spawn_proposal()
>         .times(1)
>         .return_once(|_, _, _| { async move { Ok(()) } }.boxed());
> ```

Done.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2441)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @dafnamatsry)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 388 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODe8IucBctdGYIJVZ1N:-ODehYKy28rS5NIQvt3Q:bb6sue7) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher_test.rs#L388)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

A bit problematic because of the `Arc`.
I can put only the `BlockBuilderError::FailOnError(FailOnErrorCause::BlockFull)` behind a const but IMO it won't make the test more readable.
</blockquote></details>

maybe lazy_static?
or a separate function?

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2441)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 388 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODe8IucBctdGYIJVZ1N:-ODfMaQv-ah6oOqsyHE2:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher_test.rs#L388)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

maybe lazy_static?
or a separate function?
</blockquote></details>

Done.

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2441)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 372 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODeGmiH7JMEg2Ua8Y5U:-ODg0D0U5KI8zgRNADcI:b9t84ze) ([raw file](https://github.com/starkware-libs/sequencer/blob/844ed9bafe397927c56ed1834989bdfb36b99f6d/crates/starknet_batcher/src/batcher.rs#L372)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

in case this wasn't clear, I was asking to remove the comment about the panic.
</blockquote></details>

Oops. Missed it.
Done.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2441)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r5, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2441)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 202 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODkNxIk30b2tJcnl6Cx:-ODkNxIk30b2tJcnl6Cy:b-fpkw0y) ([raw file](https://github.com/starkware-libs/sequencer/blob/fe25e297e6907ed887c66f1d89a1e3eacd63de39/crates/starknet_batcher/src/batcher_test.rs#L202)):*
> ```XML
>         block_info: initial_block_info(),
>     };
>     batcher.validate_block(validate_block_input).await.unwrap();
> ```

(After rebase)



_Suggestion:_
```XML
    batcher.validate_block(validate_block_input()).await.unwrap();
```
___
*[`crates/starknet_batcher/src/batcher.rs` line 238 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODkLlyfDHRRQDorC40X:-ODkLlyfDHRRQDorC40Y:b-wa7gz7) ([raw file](https://github.com/starkware-libs/sequencer/blob/fe25e297e6907ed887c66f1d89a1e3eacd63de39/crates/starknet_batcher/src/batcher.rs#L238)):*
> ```XML
>                 self.proposal_manager.abort_proposal(proposal_id).await;
>                 self.close_input_transaction_stream(proposal_id)?;
>                 Ok(SendProposalContentResponse { response: ProposalStatus::Aborted })
> ```

Extract to function? For symmetry



_Code quote:_
```XML
                self.proposal_manager.abort_proposal(proposal_id).await;
                self.close_input_transaction_stream(proposal_id)?;
                Ok(SendProposalContentResponse { response: ProposalStatus::Aborted })
```

**Review by alonh5 — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2441)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry)

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2441)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 238 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODkLlyfDHRRQDorC40X:-ODu62VL3YVzthHE1Na-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fe25e297e6907ed887c66f1d89a1e3eacd63de39/crates/starknet_batcher/src/batcher.rs#L238)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Extract to function? For symmetry
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 202 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-ODkNxIk30b2tJcnl6Cx:-ODu7z5379Pb3h0cvvct:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fe25e297e6907ed887c66f1d89a1e3eacd63de39/crates/starknet_batcher/src/batcher_test.rs#L202)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

(After rebase)
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2441#-:-OE97GQJ2PxMyyZvKhj4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Pull request merged**
