### PR TITLE
refactor(blockifier): move event and message summary to ExecutionSummary

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1005)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1005)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1005#-O7hKGqDDINFeLd3CxTK:-O7hKGqDDINFeLd3CxTL:b-csixtg) (no related file):*
please open py-side PR

___
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1005#-O7hJZxn8orrd1yGNyNU:-O7hJZxn8orrd1yGNyNV:bwa9yno) ([raw file](https://github.com/starkware-libs/sequencer/blob/46ad70592a4a868b07345f3928db4979399616a9/crates/blockifier/src/fee/gas_usage_test.rs#L46)):*
> ```XML
>             .into_iter()
>             .map(|call_info| call_info.with_some_class_hash())
>             .collect();
> ```

consider defining a function to `Some`ify class hashes in a vector of call infos (non-blocking... duplication, but in test code)



_Code quote:_
```XML
    let call_infos: Vec<CallInfo> =
        vec![CallInfo::default(), CallInfo::default(), CallInfo::default()]
            .into_iter()
            .map(|call_info| call_info.with_some_class_hash())
            .collect();
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1005#-O7hK4Pc-OWsvAvtVKms:-O7hK4Pc-OWsvAvtVKmt:b-infwhx) ([raw file](https://github.com/starkware-libs/sequencer/blob/46ad70592a4a868b07345f3928db4979399616a9/crates/blockifier/src/test_utils/struct_impls.rs#L111)):*
> ```XML
>         self
>     }
> }
> ```

can you explain why this is needed?
why not remove the `Option` entirely? when is `None` needed?



_Code quote:_
```XML
impl CallInfo {
    pub fn with_some_class_hash(mut self) -> Self {
        self.call.class_hash = Some(ClassHash::default());
        self
    }
}
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1005)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1005#-O7hJZxn8orrd1yGNyNU:-O7hQ0EvDOJ5WZBgO4Aw:byq4gun) ([raw file](https://github.com/starkware-libs/sequencer/blob/46ad70592a4a868b07345f3928db4979399616a9/crates/blockifier/src/fee/gas_usage_test.rs#L46)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

consider defining a function to `Some`ify class hashes in a vector of call infos (non-blocking... duplication, but in test code)
</blockquote></details>

Sure, I will do that in the following PR (or in this one if I have to fix some real issue in this stack)
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1005#-O7hK4Pc-OWsvAvtVKms:-O7hPasQ4hQ4UBpbc7oZ:b-nw49zy) ([raw file](https://github.com/starkware-libs/sequencer/blob/46ad70592a4a868b07345f3928db4979399616a9/crates/blockifier/src/test_utils/struct_impls.rs#L111)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you explain why this is needed?
why not remove the `Option` entirely? when is `None` needed?
</blockquote></details>

I tried to set the default value to Some(...), but many tests failed, and it makes sense to keep it None:
Currently, if the class hash is None, it indicates that the entry point should run with the contract's class hash

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1005)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1005#-O7hKGqDDINFeLd3CxTK:-O7hQrCi-4ws0jbJ-xRj:b-ndjq0o) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please open py-side PR
</blockquote></details>

https://github.com/starkware-industries/starkware/compare/yoni/blockifier/rm-event-and-msg?expand=1

___

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1005)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
