### PR TITLE
feat(blockifier): keep revert error structure in TransactionExecutionInfo

### PR DESCRIPTION
**Pull request by dorimedini-starkware**

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1491?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1491** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1491?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1490** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1490?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1469** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1469?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1468** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1468?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1461** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1461?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1460** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1460?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1459** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1459?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1458** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1458?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1457** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1457?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1491)* status: 0 of 15 files reviewed, all discussions resolved

___
*[`crates/blockifier/src/transaction/objects.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1491#-O9iCiQo22yualqNFZly:-O9iCiQo22yualqNFZlz:b-supby4) ([raw file](https://github.com/starkware-libs/sequencer/blob/3116a9f0fade6f5070a305b17446ad4071e7be62/crates/blockifier/src/transaction/objects.rs#L166)):*
> ```XML
>         Self::Execution(ErrorStack::default())
>     }
> }
> ```

required, since `TransactionExecutionInfo` must implement `Default`.
This won't really be used (Option<T> default is None)



_Code quote:_
```XML
impl Default for RevertError {
    fn default() -> Self {
        Self::Execution(ErrorStack::default())
    }
}
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1491)* status: 0 of 15 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1491#-OAXMGrW0Xp5Asr2uwF3:-OAXMGrW0Xp5Asr2uwF4:bo5w5z7) ([raw file](https://github.com/starkware-libs/sequencer/blob/76e20334d3126d669cf0a7ae1c4a9bc310fdf187/crates/blockifier/src/transaction/objects.rs#L147)):*
> ```XML
>     Execution(ErrorStack),
>     PostExecution(FeeCheckError),
> }
> ```

this is the object that will be in `TransactionExecutionInfo`, instead of a string



_Code quote:_
```XML
pub enum RevertError {
    Execution(ErrorStack),
    PostExecution(FeeCheckError),
}
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 614 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1491#-OAXbZ15727qoLnHZZVB:-OAXbZ15727qoLnHZZVC:b7ion0c) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1e6ad6fb40640e0e79635ed2092fded3750de79/crates/blockifier/src/concurrency/worker_logic_test.rs#L614)):*
> ```XML
>     let tx_execution_info = execution_output.as_ref().unwrap().result.as_ref().unwrap();
>     assert!(tx_execution_info.is_reverted());
>     assert!(tx_execution_info.revert_error.clone().unwrap().to_string().contains("not declared."));
> ```

why is it cloned?



_Code quote:_
```XML
.clone()
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1491)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 614 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1491#-OAXbZ15727qoLnHZZVB:-OAXfp6aEwI-e3jq7zq7:bd8spf1) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1e6ad6fb40640e0e79635ed2092fded3750de79/crates/blockifier/src/concurrency/worker_logic_test.rs#L614)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is it cloned?
</blockquote></details>

`std::option::Option::<T>::unwrap takes ownership of the receiver self, which moves tx_execution_info.revert_error`

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/transaction/objects.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1491#-O9iCiQo22yualqNFZly:-OB4VPBg7F_PQD78Hewr:bfxdsko) ([raw file](https://github.com/starkware-libs/sequencer/blob/3116a9f0fade6f5070a305b17446ad4071e7be62/crates/blockifier/src/transaction/objects.rs#L166)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

required, since `TransactionExecutionInfo` must implement `Default`.
This won't really be used (Option<T> default is None)
</blockquote></details>

you could make it optional

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r1, 1 of 11 files at r2, 1 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1491)* status: 3 of 15 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1491#-O9iCiQo22yualqNFZly:-OB4VUOF4GwjeUwwi_kp:b-duaeo9) ([raw file](https://github.com/starkware-libs/sequencer/blob/3116a9f0fade6f5070a305b17446ad4071e7be62/crates/blockifier/src/transaction/objects.rs#L166)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

you could make it optional
</blockquote></details>

Actually, I see that it is optional, so why do you need a default?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1491)* status: 2 of 15 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1491#-O9iCiQo22yualqNFZly:-OB56XVn2a6g0LNKNM35:b-oefp1f) ([raw file](https://github.com/starkware-libs/sequencer/blob/3116a9f0fade6f5070a305b17446ad4071e7be62/crates/blockifier/src/transaction/objects.rs#L166)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Actually, I see that it is optional, so why do you need a default?
</blockquote></details>

I thought I did, I was wrong :) fixed

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1491#-:-OBtH8a-BrQn8h06IHrA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1491)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Nov 17, 5:09 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1491).

**Pull request merged**
