### PR TITLE
chore(blockifier): derive serde for transaction_execution_info

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/379)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/379)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @meship-starkware, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/379#-O4K1nsd8gbHdiCAcZ6t:-O4K1nsd8gbHdiCAcZ6u:b-tdjh3v) (no related file):*
why?
what's the use case?

___

**Comment by aner-starkware** [comment]
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why?
what's the use case?
</blockquote></details>

:shrug:, it's the assignment from github issues...

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/379)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @meship-starkware, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/379#-O4K1nsd8gbHdiCAcZ6t:-O4KdgDJ4moDgQ9e4IGK:b-uiinp6) (no related file):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

:shrug:, it's the assignment from github issues...
</blockquote></details>

ah
ok then, please gate it behind a feature, so we verify we don't use this internally

___

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/379)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/379#-O4KtULX9uy9xlfMKOkc:-O4KtULX9uy9xlfMKOkd:b-mfvyga) (no related file):*
In all open issues PRs, Ariel asked us to add @tdelabro 

___

**Comment by aner-starkware** [comment]
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah
ok then, please gate it behind a feature, so we verify we don't use this internally
</blockquote></details>

What does that mean?

**Comment by aner-starkware** [comment]
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

In all open issues PRs, Ariel asked us to add @tdelabro
</blockquote></details>

Thanks.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/379)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @noaov1, and @tdelabro)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/379#-O4K1nsd8gbHdiCAcZ6t:-O4dVfx06ENWV5WPMY7m:b-bxfq2l) (no related file):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

What does that mean?
</blockquote></details>

1. add a feature (call it, say, `transaction_serde` in the `features` section of the blockifier's cargo.toml
2. use `cfg_attr` to conditionally derive (De)Serialize if the feature is active (see `cfg_attr` examples in the repo)

___

**Comment by tdelabro** [comment]
@aner-starkware you can take a look to widely used crate like: https://github.com/rust-num/num-bigint/blob/master/Cargo.toml

The Cargo.toml has a `serde` feature, and the `serde` crate is flaged as an optional dependency. Read carefully this section in order to understand how to specify those things correctly: https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies

Then instead of having `#[derive(Serialize, Deserialize)]` in your code you have instead
```rust
#[derive(Copy, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serizalize, serde::Deserialize)]
pub struct MyStruct {}
```

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/379)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, @noaov1, and @tdelabro)

___
*[`crates/blockifier/Cargo.toml` line 15 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/379#-O4q3bppAkGR7JW_S0dD:-O4q3bpq14ClOLRrWAGO:b-dlzwp5) ([raw file](https://github.com/starkware-libs/sequencer/blob/67b490b1afcdaed7c12308f4b0121e9aeec9cd17/crates/blockifier/Cargo.toml#L15)):*
> ```TOML
> concurrency = []
> jemalloc = ["dep:tikv-jemallocator"]
> transaction_serde = []
> ```

AFAIU, no need for explicit dependencies as serde is a non-optional dependency already.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/379)* status: all files reviewed, 8 unresolved discussions (waiting on @aner-starkware, @noaov1, and @tdelabro)

___
*[`crates/blockifier/src/execution/call_info.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/379#-O4qFipS6AAcmCVFbgbD:-O4qFipS6AAcmCVFbgbE:b5u3hjo) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c2652a361c82138c14c2bd76fe2b0decdcbc3a9/crates/blockifier/src/execution/call_info.rs#L32)):*
> ```XML
> #[cfg_attr(test, derive(Clone))]
> #[cfg_attr(feature = "transaction_serde", derive(Deserialize))]
> #[derive(Debug, Default, Eq, PartialEq, Serialize)]
> ```

this is cleaner IMO; WDYT?
this way you only need to name the feature once



_Suggestion:_
```XML
use cairo_vm::vm::runners::cairo_runner::ExecutionResources;
use serde::Serialize;
use starknet_api::core::{ClassHash, ContractAddress, EthAddress, PatriciaKey};
use starknet_api::state::StorageKey;
use starknet_api::transaction::{EventContent, L2ToL1Payload};
use starknet_api::{felt, patricia_key};
use starknet_types_core::felt::Felt;

use crate::execution::entry_point::CallEntryPoint;
use crate::fee::gas_usage::get_message_segment_length;
use crate::state::cached_state::StorageEntry;

#[cfg_attr(feature = "transaction_serde", derive(serde::Deserialize))]
#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize)]
pub struct Retdata(pub Vec<Felt>);

#[macro_export]
macro_rules! retdata {
    ( $( $x:expr ),* ) => {
        Retdata(vec![$($x),*])
    };
}

#[cfg_attr(test, derive(Clone))]
#[cfg_attr(feature = "transaction_serde", derive(Deserialize))]
#[derive(Debug, Default, Eq, PartialEq, Serialize)]
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/379#-O4qFvWr8suwU-w4mya2:-O4qFvWr8suwU-w4mya3:byr4ffv) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c2652a361c82138c14c2bd76fe2b0decdcbc3a9/crates/blockifier/src/execution/entry_point.rs#L8)):*
> ```XML
> use num_traits::{Inv, Zero};
> #[cfg(feature = "transaction_serde")]
> use serde::Deserialize;
> ```

see above



_Code quote:_
```XML
#[cfg(feature = "transaction_serde")]
use serde::Deserialize;
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/379#-O4qG2DW-UZJYO0R0hlh:-O4qG2DW-UZJYO0R0hli:byr4ffv) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c2652a361c82138c14c2bd76fe2b0decdcbc3a9/crates/blockifier/src/fee/actual_cost.rs#L3)):*
> ```XML
> use cairo_vm::vm::runners::cairo_runner::ExecutionResources;
> #[cfg(feature = "transaction_serde")]
> use serde::{Deserialize, Serialize};
> ```

see above



_Code quote:_
```XML
#[cfg(feature = "transaction_serde")]
use serde::{Deserialize, Serialize};
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 7 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/379#-O4qG4el6_Ao9b3kwaXp:-O4qG4el6_Ao9b3kwaXq:byr4ffv) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c2652a361c82138c14c2bd76fe2b0decdcbc3a9/crates/blockifier/src/state/cached_state.rs#L7)):*
> ```XML
> use indexmap::IndexMap;
> #[cfg(feature = "transaction_serde")]
> use serde::{Deserialize, Serialize};
> ```

see above



_Code quote:_
```XML
#[cfg(feature = "transaction_serde")]
use serde::{Deserialize, Serialize};
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 7 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/379#-O4qG82kDFjCH4SkFmlh:-O4qG82kDFjCH4SkFmli:byr4ffv) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c2652a361c82138c14c2bd76fe2b0decdcbc3a9/crates/blockifier/src/transaction/objects.rs#L7)):*
> ```XML
> use num_traits::Pow;
> #[cfg(feature = "transaction_serde")]
> use serde::Deserialize;
> ```

see above



_Code quote:_
```XML
#[cfg(feature = "transaction_serde")]
use serde::Deserialize;
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/379)* status: 2 of 7 files reviewed, 8 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, @noaov1, and @tdelabro)

___
*[`crates/blockifier/src/execution/call_info.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/379#-O4qFipS6AAcmCVFbgbD:-O4t4CoG6zRSuY8zje9K:b-8ayu6x) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c2652a361c82138c14c2bd76fe2b0decdcbc3a9/crates/blockifier/src/execution/call_info.rs#L32)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is cleaner IMO; WDYT?
this way you only need to name the feature once
</blockquote></details>

Agree

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/379#-:-O4t4sda6orwvMB7JT5F:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/379)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/379)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @noaov1)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/379)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/379)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
