### PR TITLE
test(blockifier): test initial_gas for consecutive call_contract calls

### PR DESCRIPTION
**Pull request by TzahiTaub**

### CODE REVIEW

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1453)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1453)* status: all files reviewed, 10 unresolved discussions (waiting on @TzahiTaub and @yoavGrs)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1534 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9OvwXU38jxT8oGrcW2:-O9OvwXU38jxT8oGrcW3:b3ltllf) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1534)):*
> ```XML
>     CompilerBasedVersion::CairoVersion(CairoVersion::Cairo0),
>     CompilerBasedVersion::CairoVersion(CairoVersion::Cairo1)
> ])]
> ```

which other scenarios are you planning?
strange to have a single `#[case]`



_Code quote:_
```XML
#[case(&[
    CompilerBasedVersion::CairoVersion(CairoVersion::Cairo1),
    CompilerBasedVersion::CairoVersion(CairoVersion::Cairo1),
    CompilerBasedVersion::CairoVersion(CairoVersion::Cairo0),
    CompilerBasedVersion::CairoVersion(CairoVersion::Cairo1)
])]
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1536 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9Ow0-595Uz5mU8zipK:-O9Ow0-595Uz5mU8zipL:b-fxzv0m) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1536)):*
> ```XML
> ])]
> fn test_initial_gas(#[case] versions: &[CompilerBasedVersion]) {
>     use crate::execution::call_info::CallInfo;
> ```

move to top



_Code quote:_
```XML
use crate::execution::call_info::CallInfo;
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1565 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9OwCY07U7S0tug5_JX:-O9OwCY07U7S0tug5_JY:bv2xn4t) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1565)):*
> ```XML
>             max_price_per_unit: DEFAULT_STRK_L1_DATA_GAS_PRICE.into(),
>         },
>     });
> ```

there's a `default_all_resource_bounds` fixture; use it, it provides exactly the same numbers IIRC



_Suggestion:_
```XML
fn test_initial_gas(
    default_all_resource_bounds: ValidResourceBounds,
    #[case] versions: &[CompilerBasedVersion]
) {
    use crate::execution::call_info::CallInfo;

    let block_context = BlockContext::create_for_account_testing();
    let account = FeatureContract::AccountWithoutValidations(CairoVersion::Cairo1);
    let account_address = account.get_instance_address(0_u16);
    let used_test_contracts: HashSet<FeatureContract> =
        HashSet::from_iter(versions.iter().map(|x| x.get_test_contract()));
    let mut contracts: Vec<FeatureContract> = used_test_contracts.into_iter().collect();
    contracts.push(account);
    let sender_balance = BALANCE;
    let chain_info = &block_context.chain_info;
    let state = &mut test_state(
        chain_info,
        sender_balance,
        &contracts.into_iter().map(|contract| (contract, 1u16)).collect::<Vec<_>>(),
    );
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1571 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9OwSku6drBIQhGfNR8:-O9OwSku6drBIQhGfNR9:blfsn7q) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1571)):*
> ```XML
>     resource_bounds:  unlimited_resource_bounds,
>         version: TransactionVersion::THREE
>     });
> ```

fix formatting (not automatic in macros)



_Code quote:_
```XML
    let account_tx = account_invoke_tx(invoke_tx_args! {
    sender_address: account_address,
    calldata: build_recurse_calldata(versions),
    resource_bounds:  unlimited_resource_bounds,
        version: TransactionVersion::THREE
    });
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1573 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9OxnOA3qzw31ZFWC_P:-O9OxnOA3qzw31ZFWC_Q:bmbeguh) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1573)):*
> ```XML
>     });
> 
>     let mut transactional_state = TransactionalState::create_transactional(state);
> ```

you need this because you're calling `execute_raw` instead of `execute`? why not call `execute`?



_Code quote:_
```XML
let mut transactional_state = TransactionalState::create_transactional(state);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1580 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9Owdz127hw0ItY6hY_:-O9Owdz127hw0ItY6hYa:b6tkuu8) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1580)):*
> ```XML
> 
>     let val_call_info = &transaction_ex_info.validate_call_info.unwrap();
>     let val_initial_gas = val_call_info.call.initial_gas;
> ```

(a) consistency (you have `validate_gas_consumed`), (b) `val` can mean `value`, better write it out



_Suggestion:_
```XML
    let validate_call_info = &transaction_ex_info.validate_call_info.unwrap();
    let validate_initial_gas = val_call_info.call.initial_gas;
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1591 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9OwvnC-Rj0sWQvGN3h:-O9OwvnC-Rj0sWQvGN3i:b-nznc9y) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1591)):*
> ```XML
>     let mut started_vm_mode = false;
>     // The __validate__ call of a the account contract.
>     let mut prev_version = &CompilerBasedVersion::CairoVersion(CairoVersion::Cairo1);
> ```

in case we add a test case where the account is cairo0 - better to name this (you use this value twice)



_Suggestion:_
```XML
    let account_version = CairoVersion::Cairo1;
    let account = FeatureContract::AccountWithoutValidations(account_version);
    let account_address = account.get_instance_address(0_u16);
    let used_test_contracts: HashSet<FeatureContract> =
        HashSet::from_iter(versions.iter().map(|x| x.get_test_contract()));
    let mut contracts: Vec<FeatureContract> = used_test_contracts.into_iter().collect();
    contracts.push(account);
    let sender_balance = BALANCE;
    let chain_info = &block_context.chain_info;
    let state = &mut test_state(
        chain_info,
        sender_balance,
        &contracts.into_iter().map(|contract| (contract, 1u16)).collect::<Vec<_>>(),
    );
    let unlimited_resource_bounds = ValidResourceBounds::AllResources(AllResourceBounds {
        l1_gas: ResourceBounds {
            max_amount: DEFAULT_L1_GAS_AMOUNT,
            max_price_per_unit: DEFAULT_STRK_L1_GAS_PRICE.into(),
        },
        l2_gas: ResourceBounds {
            max_amount: DEFAULT_L2_GAS_MAX_AMOUNT.into(),
            max_price_per_unit: DEFAULT_STRK_L2_GAS_PRICE.into(),
        },
        l1_data_gas: ResourceBounds {
            max_amount: DEFAULT_L1_DATA_GAS_MAX_AMOUNT,
            max_price_per_unit: DEFAULT_STRK_L1_DATA_GAS_PRICE.into(),
        },
    });
    let account_tx = account_invoke_tx(invoke_tx_args! {
    sender_address: account_address,
    calldata: build_recurse_calldata(versions),
    resource_bounds:  unlimited_resource_bounds,
        version: TransactionVersion::THREE
    });

    let mut transactional_state = TransactionalState::create_transactional(state);
    let execution_flags =
        ExecutionFlags { charge_fee: true, validate: true, concurrency_mode: false };
    let transaction_ex_info =
        account_tx.execute_raw(&mut transactional_state, &block_context, execution_flags).unwrap();

    let val_call_info = &transaction_ex_info.validate_call_info.unwrap();
    let val_initial_gas = val_call_info.call.initial_gas;
    assert_eq!(val_initial_gas, DEFAULT_L2_GAS_MAX_AMOUNT.0);
    let validate_gas_consumed = val_call_info.execution.gas_consumed;
    assert!(validate_gas_consumed > 0, "New Cairo1 contract should consume gas.");

    let default_call_info = CallInfo::default();
    let mut prev_initial_gas = val_initial_gas;
    let mut ex_call_info = &transaction_ex_info.execute_call_info.unwrap();
    let mut curr_initial_gas;
    let mut started_vm_mode = false;
    // The __validate__ call of a the account contract.
    let mut prev_version = &CompilerBasedVersion::CairoVersion(account_version);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1593 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9OxIwF4fzLtYOgT9HQ:-O9OxIwF4fzLtYOgT9HR:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1593)):*
> ```XML
>     let mut prev_version = &CompilerBasedVersion::CairoVersion(CairoVersion::Cairo1);
>     // Insert the __execute__ call in the beginning of versions.
>     for version in [CompilerBasedVersion::CairoVersion(CairoVersion::Cairo1)].iter().chain(versions)
> ```





_Suggestion:_
```XML
(account_version)
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1617 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9OxRNw1daGVuxIw3eG:-O9OxRNw1daGVuxIw3eH:btxwe0z) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1617)):*
> ```XML
>         } else {
>             assert!(ex_call_info.execution.gas_consumed == 0);
>         }
> ```

will this logic look better if you `match (prev_version, version, started_vm_mode)`? I have a feeling it will



_Code quote:_
```XML
        if version == &CompilerBasedVersion::CairoVersion(CairoVersion::Cairo0) && !started_vm_mode
        {
            // First time we are in VM mode.
            assert_eq!(
                curr_initial_gas,
                block_context.versioned_constants.default_initial_gas_cost()
            );
            started_vm_mode = true;
        } else {
            if prev_version != &CompilerBasedVersion::CairoVersion(CairoVersion::Cairo0) {
                // Non Cairo0 contract consumes gas from the initial gas.
                assert!(curr_initial_gas < prev_initial_gas);
            } else {
                assert_eq!(curr_initial_gas, prev_initial_gas);
            }
        }

        if version == &CompilerBasedVersion::CairoVersion(CairoVersion::Cairo1) {
            assert!(ex_call_info.execution.gas_consumed > 0);
        } else {
            assert!(ex_call_info.execution.gas_consumed == 0);
        }
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1620 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9OyD_CEzAXmDOBVhEq:-O9OyD_CEzAXmDOBVhEr:b-njua4q) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1620)):*
> ```XML
>         // If inner_calls is empty, this SHOULD be the last call and thus last loop iteration.
>         // Assigning the default call info, will cause an error if the loop continues.
>         ex_call_info = &ex_call_info.inner_calls.first().unwrap_or(&default_call_info);
> ```

you expect there to be exactly zero or one inner call infos, right? please assert this



_Code quote:_
```XML
.first()
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1453)* status: all files reviewed, 10 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1534 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9OvwXU38jxT8oGrcW2:-OADKEkA1xEyTp5cVmo3:bywz91a) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1534)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

which other scenarios are you planning?
strange to have a single `#[case]`
</blockquote></details>

Would like to use `OldCairo1` instead of `Cairo0` later on. Two variants in total.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1536 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9Ow0-595Uz5mU8zipK:-OADH-vD9qyd0PdpLYvS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1536)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move to top
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1565 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9OwCY07U7S0tug5_JX:-OADKm8R2UiL7OKN6I0B:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1565)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there's a `default_all_resource_bounds` fixture; use it, it provides exactly the same numbers IIRC
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1571 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9OwSku6drBIQhGfNR8:-OADKw698r-xouYIctch:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1571)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

fix formatting (not automatic in macros)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1573 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9OxnOA3qzw31ZFWC_P:-OADRrFj8VuReyLUTHyr:bkv5p4g) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1573)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you need this because you're calling `execute_raw` instead of `execute`? why not call `execute`?
</blockquote></details>

Copied from other tests on the file.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1580 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9Owdz127hw0ItY6hY_:-OADS7Qh8JVy8gFvq04E:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1580)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

(a) consistency (you have `validate_gas_consumed`), (b) `val` can mean `value`, better write it out
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1591 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9OwvnC-Rj0sWQvGN3h:-OADSyf18fPC7NfLMiXI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1591)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

in case we add a test case where the account is cairo0 - better to name this (you use this value twice)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1593 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9OxIwF4fzLtYOgT9HQ:-OADT7Kk3z9qI9bqi5S3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1593)):*
> ```XML
>     let mut prev_version = &CompilerBasedVersion::CairoVersion(CairoVersion::Cairo1);
>     // Insert the __execute__ call in the beginning of versions.
>     for version in [CompilerBasedVersion::CairoVersion(CairoVersion::Cairo1)].iter().chain(versions)
> ```

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1617 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9OxRNw1daGVuxIw3eG:-OADq8KLErOfSHOBUo1R:b6726n1) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1617)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

will this logic look better if you `match (prev_version, version, started_vm_mode)`? I have a feeling it will
</blockquote></details>

Not sure if it's clearer, but here it is
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1620 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9OyD_CEzAXmDOBVhEq:-OADqqzz6NxwpqUMgUyM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1620)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you expect there to be exactly zero or one inner call infos, right? please assert this
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1453)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub and @yoavGrs)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1534 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9OvwXU38jxT8oGrcW2:-OAEfUnhEPyEfpqh5DlK:bgrjl8l) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1534)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Would like to use `OldCairo1` instead of `Cairo0` later on. Two variants in total.
</blockquote></details>

can you add a TODO with the cases you still want to check?
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1596 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-OAEek5q40rZbAEaXLbj:-OAEek5r67rd_LHXCnO0:b-jgr5ge) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f4988434c4a6caf6634848ca37b091d9e4d2b09/crates/blockifier/src/transaction/account_transactions_test.rs#L1596)):*
> ```XML
>                 started_vm_mode = true;
>             }
>             _ => {
> ```

IIUC - there is currently no scenario where the first contract is old cairo1; however this is what you must assume in this match arm, right?
you can add a final `_` arm that panics with `test case not implemented` or something



_Suggestion:_
```XML
(CompilerBasedVersion::CairoVersion(CairoVersion::Cairo1), _, _)
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1453)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1534 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-O9OvwXU38jxT8oGrcW2:-OAEmZpH0u2B9o3jMPvk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ada9a823c4bc903dbbac9e6ece7c20a58b837c9/crates/blockifier/src/transaction/account_transactions_test.rs#L1534)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you add a TODO with the cases you still want to check?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1596 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-OAEek5q40rZbAEaXLbj:-OAEnCB6AX_xwQ-dXTlZ:bnhnd79) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f4988434c4a6caf6634848ca37b091d9e4d2b09/crates/blockifier/src/transaction/account_transactions_test.rs#L1596)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

IIUC - there is currently no scenario where the first contract is old cairo1; however this is what you must assume in this match arm, right?
you can add a final `_` arm that panics with `test case not implemented` or something
</blockquote></details>

I don't understand - what do I assume in this match arm? We match this arm if prev is Cairo1 or OldCairo1 (and not the first time in VM mode).

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1453)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub and @yoavGrs)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1596 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-OAEek5q40rZbAEaXLbj:-OAHMo1YAlvihGgIseft:b-wzcq07) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f4988434c4a6caf6634848ca37b091d9e4d2b09/crates/blockifier/src/transaction/account_transactions_test.rs#L1596)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I don't understand - what do I assume in this match arm? We match this arm if prev is Cairo1 or OldCairo1 (and not the first time in VM mode).
</blockquote></details>

I'm confused, why is this true?
```
// prev_version is a non Cairo0 contract, thus it consumes gas from the initial
// gas.
```
if prev version is OldCairo1, why does it consume gas from the initial gas?

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1453#-:-OAIbAIn8PCyKaOmzGam:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1453)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
