### PR TITLE
chore: create executable tx creator for testing

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/672)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/672?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#672** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/672?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#666** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/666?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#661** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/661?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#660** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/660?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/672)* status: 0 of 3 files reviewed, all discussions resolved

___
*[`crates/starknet_api/src/test_utils/deploy_account.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/672#-O6GncAY3gdCrcu2si-z:-O6GncAY3gdCrcu2si0-:b-3p6vx4) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d23a92a09efcd70ef4677bfde93d2d4a93f9dbe/crates/starknet_api/src/test_utils/deploy_account.rs#L109)):*
> ```XML
> ) -> ExecutableDeployAccountTransaction {
>     let tx = deploy_account_tx(deploy_tx_args, nonce);
>     ExecutableDeployAccountTransaction::create(tx, &ChainId::create_for_testing()).unwrap()
> ```

The `create` class method calculates the tx_hash. 



_Code quote:_
```XML
 ExecutableDeployAccountTransaction::create(tx, &ChainId::create_for_testing()).unwrap()
```

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/672)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_api/src/test_utils/declare.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/672#-O6GsNHc-uTs1zlXx8vx:-O6GsNHdDSazy2rEK-fw:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d23a92a09efcd70ef4677bfde93d2d4a93f9dbe/crates/starknet_api/src/test_utils/declare.rs#L124)):*
> ```XML
> }
> 
> pub fn executable_declare_tx(
> ```





_Suggestion:_
```XML
executable_declare_tx_for_testing
```
___
*[`crates/starknet_api/src/test_utils/deploy_account.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/672#-O6GncAY3gdCrcu2si-z:-O6GscEN0fPzuu4e794s:bk4v2ib) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d23a92a09efcd70ef4677bfde93d2d4a93f9dbe/crates/starknet_api/src/test_utils/deploy_account.rs#L109)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The `create` class method calculates the tx_hash.
</blockquote></details>

Why it's different for `declare`?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/672)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @MohammadNassar1)

___
*[`crates/starknet_api/src/test_utils/deploy_account.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/672#-O6GncAY3gdCrcu2si-z:-O6KipR42GjrY_qJB1fv:b-2tcda7) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d23a92a09efcd70ef4677bfde93d2d4a93f9dbe/crates/starknet_api/src/test_utils/deploy_account.rs#L109)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why it's different for `declare`?
</blockquote></details>

Now, it is streamlined with the blockifier test utils.
I will soon publish a PR where the blockifier test utils will use the Starknet API test utils. The code suggested in this PR wi compatible with this change.


I did not check why the declare case is different. I noticed it could theoretically be aligned with the solution for deploy accounts and invoke.

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/672)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/starknet_api/src/test_utils/deploy_account.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/672#-O6GncAY3gdCrcu2si-z:-O6L7T8R1OXSIbvL8T_9:b-h054bq) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d23a92a09efcd70ef4677bfde93d2d4a93f9dbe/crates/starknet_api/src/test_utils/deploy_account.rs#L109)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Now, it is streamlined with the blockifier test utils.
I will soon publish a PR where the blockifier test utils will use the Starknet API test utils. The code suggested in this PR wi compatible with this change.


I did not check why the declare case is different. I noticed it could theoretically be aligned with the solution for deploy accounts and invoke.
</blockquote></details>

I believe that if we intend to use this util in Mempool, it might be problematic to use the default for the transaction hash.
This is because the DSs of Mempool rely on the transaction hash as a key variable, so each transaction should have a unique hash.

**Pull request merged**
