### PR TITLE
feat(starknet_batcher): save BlockExecutionArtifacts in ProposalManager

### PR DESCRIPTION
**Pull request by DvirYo-starkware**

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2725)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @alonh5, @dafnamatsry, @noaov1, @Yael-Starkware, and @yair-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2725#-OEJbL6z-F3dd7DFmxG-:-OEJbL7-0aLF4ViWQ6Gu:bm8ol89) (no related file):*
I assume that was some discussion about all the optional cloning. If important it can be prevented in two ways:
- add another flag in addition to the `testing` flag and import `blockier` in the `batcher` with this flag
- save in the `ProposalManager` only the `BlockExecutionArtifacts` and only when writing the block to the storage make a conversion. This will increase the latency of the transaction to accept on layer 2 in version14.0

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2725#-:-OEO-1ti7qHdgtSJQ5Ku:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @dafnamatsry, @noaov1, and @Yael-Starkware)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2725)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @DvirYo-starkware, @noaov1, and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 372 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2725#-OEO00oW8wZblBkTtqit:-OEO00oW8wZblBkTtqiu:bb76mu4) ([raw file](https://github.com/starkware-libs/sequencer/blob/a74f90c7b5d9ea2777090f442f9acffc868f7945/crates/starknet_batcher/src/batcher.rs#L372)):*
> ```XML
>     }
> 
>     // TODO(dvir): return `BlockExecutionArtifacts`
> ```

Why?



_Code quote:_
```XML
// TODO(dvir): return `BlockExecutionArtifacts`
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2725)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5, @dafnamatsry, @noaov1, and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 372 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2725#-OEO00oW8wZblBkTtqit:-OEO82di8LYgvEDQzIs6:byohfup) ([raw file](https://github.com/starkware-libs/sequencer/blob/a74f90c7b5d9ea2777090f442f9acffc868f7945/crates/starknet_batcher/src/batcher.rs#L372)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

This information is needed for writing to Aerospike

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2725)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @DvirYo-starkware, @noaov1, and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/utils.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2725#-OEOLVBD9cj2w97fmaSi:-OEOLVBD9cj2w97fmaSj:b-8iq1ta) ([raw file](https://github.com/starkware-libs/sequencer/blob/a74f90c7b5d9ea2777090f442f9acffc868f7945/crates/starknet_batcher/src/utils.rs#L69)):*
> ```XML
>             tx_hashes,
>             nonces,
>             block_execution_artifacts: cloned_artifacts,
> ```

In this case, consider deleting the `ProposalOutput` type and storing only the `BlockExecutionArtifacts`. Fields used from `ProposalOutput` can be calculated when needed (they are used only once, IIRC).

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2725)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5, @dafnamatsry, @noaov1, and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/utils.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2725#-OEOLVBD9cj2w97fmaSi:-OEOPwi23Tdf25sH2qiw:boxwuev) ([raw file](https://github.com/starkware-libs/sequencer/blob/a74f90c7b5d9ea2777090f442f9acffc868f7945/crates/starknet_batcher/src/utils.rs#L69)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

In this case, consider deleting the `ProposalOutput` type and storing only the `BlockExecutionArtifacts`. Fields used from `ProposalOutput` can be calculated when needed (they are used only once, IIRC).
</blockquote></details>

See here:
https://reviewable.io/reviews/starkware-libs/sequencer/2725#:~:text=save%20in%20the%20ProposalManager%20only%20the%20BlockExecutionArtifacts%20and%20only%20when%20writing%20the%20block%20to%20the%20storage%20make%20a%20conversion.%20This%20will%20increase%20the%20latency%20of%20the%20transaction%20to%20accept%20on%20layer%202%20in%20version14.0

In addition, it requires more significant changes in the batcher for something that will be deleted after version 14.0, and I try to avoid it.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2725)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @DvirYo-starkware, @noaov1, @Yael-Starkware, and @yair-starkware)

___
*[`crates/starknet_batcher/src/utils.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2725#-OEOLVBD9cj2w97fmaSi:-OEOyvJ12XfzhHgxIJ5n:bahn1or) ([raw file](https://github.com/starkware-libs/sequencer/blob/a74f90c7b5d9ea2777090f442f9acffc868f7945/crates/starknet_batcher/src/utils.rs#L69)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

See here:
https://reviewable.io/reviews/starkware-libs/sequencer/2725#:~:text=save%20in%20the%20ProposalManager%20only%20the%20BlockExecutionArtifacts%20and%20only%20when%20writing%20the%20block%20to%20the%20storage%20make%20a%20conversion.%20This%20will%20increase%20the%20latency%20of%20the%20transaction%20to%20accept%20on%20layer%202%20in%20version14.0

In addition, it requires more significant changes in the batcher for something that will be deleted after version 14.0, and I try to avoid it.
</blockquote></details>

On the other hand, we're now doing these calculations for every proposal even though we only need them for the one we decided on.
We recently did a refactor to the batcher (deleting the proposal manager), and I think the `ProposalOutput` is redundant anyway, this won't be deleted after 0.14.0. Could you try to do this and see if it makes sense? I think it would be better

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2725)* status: 7 of 10 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry, @DvirYo-starkware, @noaov1, and @yair-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2725#-OExSu8B3g0R-nWfJ2Wv:-OExSu8B3g0R-nWfJ2Ww:bx98j4i) (no related file):*
@ayeletstarkware merged a PR removing `ProposalOutput` completely and replacing it with `BlockExecutionArtifacts`
Rebase and see if your PR is still needed.

**Pull request closed without merging**
