### PR TITLE
chore(blockifier, native_blockifier): update versioned constants

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/559)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware +reviewer:@Yonatan-Starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/559#-:-O58VL9j1FkUjifd4kSa:b8blj49)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @Yonatan-Starkware)

**Review by amosStarkware — COMMENTED** [review]
-reviewer:@Yonatan-Starkware +reviewer:@Yoni-Starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/559#-:-O58VzcTBuuuwYyo7Yvd:bo31y3m)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @Yoni-Starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/559)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 746 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/559#-O58xMnb9dvUusRQ6Xfb:-O58xMnc2gI8MMOWl0ur:bqazt17) ([raw file](https://github.com/starkware-libs/sequencer/blob/0d617f442e078701fda403e2f8d77e5d76020a97/crates/blockifier/src/versioned_constants.rs#L746)):*
> ```XML
>     pub max_recursion_depth: usize,
>     pub invoke_tx_max_n_steps: Option<u32>,
> }
> ```

why is only one field optional here?

I would expect either:
1. make all three optional (and override only what is `Some`, as you do above)
2. make none optional, and force the caller to override all three (if the caller needs only one override, the caller can explicitly put the defaults in the other two fields)

I personally prefer (2)



_Code quote:_
```XML
pub struct VersionedConstantsOverrides {
    pub validate_max_n_steps: u32,
    pub max_recursion_depth: usize,
    pub invoke_tx_max_n_steps: Option<u32>,
}
```
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/559#-O590UJA69bn5Qk-gf9e:-O590UJA69bn5Qk-gf9f:b5kp0ja) ([raw file](https://github.com/starkware-libs/sequencer/blob/0d617f442e078701fda403e2f8d77e5d76020a97/crates/blockifier/src/versioned_constants_test.rs#L97)):*
> ```XML
> /// Assert versioned constants overrides are used when provided.
> #[test]
> fn test_versioned_constants_overrides() {
> ```

parametrize all three fields with `#[values]` in this test? or is it redundant?



_Code quote:_
```XML
#[test]
fn test_versioned_constants_overrides() {
```
___
*[`crates/native_blockifier/src/py_objects.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/559#-O590c9t1GlCq5EslVTM:-O590c9t1GlCq5EslVTN:b-mihfo9) ([raw file](https://github.com/starkware-libs/sequencer/blob/0d617f442e078701fda403e2f8d77e5d76020a97/crates/native_blockifier/src/py_objects.rs#L53)):*
> ```XML
>     pub max_recursion_depth: usize,
>     pub invoke_tx_max_n_steps: Option<u32>,
> }
> ```

see above: I think either all optional or none optional



_Code quote:_
```XML
pub struct PyVersionedConstantsOverrides {
    pub validate_max_n_steps: u32,
    pub max_recursion_depth: usize,
    pub invoke_tx_max_n_steps: Option<u32>,
}
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/559)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 746 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/559#-O58xMnb9dvUusRQ6Xfb:-O5Cb3JO32gjurLF7kxQ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0d617f442e078701fda403e2f8d77e5d76020a97/crates/blockifier/src/versioned_constants.rs#L746)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is only one field optional here?

I would expect either:
1. make all three optional (and override only what is `Some`, as you do above)
2. make none optional, and force the caller to override all three (if the caller needs only one override, the caller can explicitly put the defaults in the other two fields)

I personally prefer (2)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/559#-O590UJA69bn5Qk-gf9e:-O5CcL9JCsQbNPq5vzIx:b2yvuq4) ([raw file](https://github.com/starkware-libs/sequencer/blob/0d617f442e078701fda403e2f8d77e5d76020a97/crates/blockifier/src/versioned_constants_test.rs#L97)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

parametrize all three fields with `#[values]` in this test? or is it redundant?
</blockquote></details>

I added the other values to the test - no need for parameterising IMO
___
*[`crates/native_blockifier/src/py_objects.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/559#-O590c9t1GlCq5EslVTM:-O5CcXIE68yg7cu0PxUI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0d617f442e078701fda403e2f8d77e5d76020a97/crates/native_blockifier/src/py_objects.rs#L53)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above: I think either all optional or none optional
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/559#-:-O5D3QVW1UDyrkWaay7t:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/559)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
