### PR TITLE
papyrus_storage: fix README in papyrus_storage

### PR DESCRIPTION
**Pull request by thunggis**
Hi team the original path seems incorrect. Fixed now.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/765)

### CODE REVIEW

**Comment by thunggis** [comment]
@MohammadNassar1 @elintul  @dorimedini-starkware  PLZ have a check

**Review by elintul — APPROVED** [review]
:lgtm:

 Thanks!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/765#-:-O7SSpyR8M_HO22mlX0F:b-8r73zr)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @thunggis)

**Comment by thunggis** [comment]
@elintul Hi there it's good to go?

**Review by elintul — APPROVED** [review]
Yes, please rebase and merge; it's open for too long.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/765#-:-O9su0mRAiJDQL-gjtGE:bo6clwq)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @thunggis)

**Comment by thunggis** [comment]
Done, PLZ check again. @elintul

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/765#-:-OA3CtoZEVJX8YrzB_DT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @thunggis)

**Pull request closed without merging**
