### PR TITLE
feat(batcher): executor trait for mocking the blockifier

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/157)

### CODE REVIEW

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/157)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @yair-starkware)

___
*[`crates/batcher/src/executer.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/157#-O31N01U7wB5Z_42Bgbm:-O31N01U7wB5Z_42Bgbn:bkwefe) ([raw file](https://github.com/starkware-libs/sequencer/blob/80634183010d656312b9f2cfdf0f270b30a79538/crates/batcher/src/executer.rs#L19)):*
> ```XML
>     use starknet_gateway::rpc_state_reader::RpcStateReader;
> 
>     pub type TxExecutionResult = TransactionExecutorResult<TransactionExecutionInfo>;
> ```

Necessary? 
I would have prefer `TransactionExecutionInfo` to not be hidden.



_Code quote:_
```XML
pub type TxExecutionResult = TransactionExecutorResult<TransactionExecutionInfo>;
```
___
*[`crates/batcher/src/executer.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/157#-O31PnHM9yJi8xzhS598:-O31PnHM9yJi8xzhS599:b-4dqvzd) ([raw file](https://github.com/starkware-libs/sequencer/blob/80634183010d656312b9f2cfdf0f270b30a79538/crates/batcher/src/executer.rs#L20)):*
> ```XML
> 
>     pub type TxExecutionResult = TransactionExecutorResult<TransactionExecutionInfo>;
>     pub type TransactionExecutor = GenericBlockifierTransactionExecutor<RpcStateReader>;
> ```

The plan is to use a local storage (and not RPC).

I think the actual Executor we implement should be generic.



_Suggestion:_
```XML
pub type TransactionExecutor<S> = GenericBlockifierTransactionExecutor<S>;
```
___
*[`crates/batcher/src/lib.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/157#-O31Ox1EAsIv-Ndq1FIQ:-O31Ox1EAsIv-Ndq1FIR:b-v2h7pe) ([raw file](https://github.com/starkware-libs/sequencer/blob/80634183010d656312b9f2cfdf0f270b30a79538/crates/batcher/src/lib.rs#L1)):*
> ```XML
> mod executer;
> ```

I think `executor` is more appropriate, although I'm not sure.
But that's what we use in the rest of the code.



_Suggestion:_
```XML
mod executor;
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/157)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry, @dorimedini-starkware, and @Yael-Starkware)

___
*[`crates/batcher/src/executer.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/157#-O31N01U7wB5Z_42Bgbm:-O31dZ0E1XmU373jawhq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/80634183010d656312b9f2cfdf0f270b30a79538/crates/batcher/src/executer.rs#L19)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Necessary? 
I would have prefer `TransactionExecutionInfo` to not be hidden.
</blockquote></details>

Done.
___
*[`crates/batcher/src/executer.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/157#-O31PnHM9yJi8xzhS598:-O31bo175XMthTcBszoA:b-qefbzv) ([raw file](https://github.com/starkware-libs/sequencer/blob/80634183010d656312b9f2cfdf0f270b30a79538/crates/batcher/src/executer.rs#L20)):*
>The plan is to use a local storage (and not RPC).

Will we have a papyrus storage_reader instance then?

> I think the actual Executor we implement should be generic.

Why? Will there be multiple modes in production?
___
*[`crates/batcher/src/lib.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/157#-O31Ox1EAsIv-Ndq1FIQ:-O31be_sCLEcnJZPitDZ:b-x3mlpp) ([raw file](https://github.com/starkware-libs/sequencer/blob/80634183010d656312b9f2cfdf0f270b30a79538/crates/batcher/src/lib.rs#L1)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think `executor` is more appropriate, although I'm not sure.
But that's what we use in the rest of the code.
</blockquote></details>

I took it from the design doc: https://docs.google.com/document/d/18mQg95cefHSVzVE7V85et18OhNHhv4aWCgBUEtYpync/edit
@Yael-Starkware wdyt?

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/157)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/executer.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/157#-O31PnHM9yJi8xzhS598:-O320TCC2nGnZXh_LXwz:b83hq8d) ([raw file](https://github.com/starkware-libs/sequencer/blob/80634183010d656312b9f2cfdf0f270b30a79538/crates/batcher/src/executer.rs#L20)):*
> Will we have a papyrus storage\_reader instance then?

Still not decided.

> Why? Will there be multiple modes in production?

No. But we should be able to create executor with different StateReader if desired (also for testing).
___
*[`crates/batcher/src/lib.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/157#-O31Ox1EAsIv-Ndq1FIQ:-O321Skk5bA9sRQaCw4e:b-fr1hd9) ([raw file](https://github.com/starkware-libs/sequencer/blob/80634183010d656312b9f2cfdf0f270b30a79538/crates/batcher/src/lib.rs#L1)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I took it from the design doc: https://docs.google.com/document/d/18mQg95cefHSVzVE7V85et18OhNHhv4aWCgBUEtYpync/edit
@Yael-Starkware wdyt?
</blockquote></details>

Still think executor is the right term. And especially when we already use it, it's confusing to have both `executer` and `executor`

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/157)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @dorimedini-starkware, and @Yael-Starkware)

___
*[`crates/batcher/src/lib.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/157#-O31Ox1EAsIv-Ndq1FIQ:-O329WCREqz3PHoN8VJ3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/80634183010d656312b9f2cfdf0f270b30a79538/crates/batcher/src/lib.rs#L1)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Still think executor is the right term. And especially when we already use it, it's confusing to have both `executer` and `executor`
</blockquote></details>

Done.
___
*[`crates/batcher/src/executer.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/157#-O31PnHM9yJi8xzhS598:-O325WZD-i9AMI4ZEH_3:b-ym82ud) ([raw file](https://github.com/starkware-libs/sequencer/blob/80634183010d656312b9f2cfdf0f270b30a79538/crates/batcher/src/executer.rs#L20)):*
> Still not decided.

So what implementation of `StateReader` should I use? Should I leave it as is with a TODO?

> No. But we should be able to create executor with different StateReader if desired (also for testing).


I think we should use the generic type in the tests for dependency injection and non-generic alias for convenience in the production code.

If there will be more modes of getting the state we should create more aliases or use a crate feature to decide which type the alias will use (as I don't think we will need more than a single mode in an executable)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/157)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @dorimedini-starkware)

___
*[`crates/batcher/src/lib.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/157#-O31Ox1EAsIv-Ndq1FIQ:-O32odLq3Ki9ibCHw4pm:b8cddn) ([raw file](https://github.com/starkware-libs/sequencer/blob/80634183010d656312b9f2cfdf0f270b30a79538/crates/batcher/src/lib.rs#L1)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

yes in the blockifier they call it executor, so I agree

**Comment by yair-starkware** [comment]
*[`crates/batcher/src/executer.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/157#-O31PnHM9yJi8xzhS598:-O3CRMkx8_whneLIYLPq:b-caz8r0) ([raw file](https://github.com/starkware-libs/sequencer/blob/80634183010d656312b9f2cfdf0f270b30a79538/crates/batcher/src/executer.rs#L20)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

> Still not decided.

So what implementation of `StateReader` should I use? Should I leave it as is with a TODO?

> No. But we should be able to create executor with different StateReader if desired (also for testing).


I think we should use the generic type in the tests for dependency injection and non-generic alias for convenience in the production code.

If there will be more modes of getting the state we should create more aliases or use a crate feature to decide which type the alias will use (as I don't think we will need more than a single mode in an executable)
</blockquote></details>

After talking with @Yael-Starkware  - changed from Rpc state reader to Papyrus state reader (the batcher will hold a local Papyrus storage instance).

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/157)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yael-Starkware)

___
*[`crates/batcher/src/executer.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/157#-O31PnHM9yJi8xzhS598:-O3XBg8K2MUR366qmRGS:b-5mw4jr) ([raw file](https://github.com/starkware-libs/sequencer/blob/80634183010d656312b9f2cfdf0f270b30a79538/crates/batcher/src/executer.rs#L20)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

After talking with @Yael-Starkware  - changed from Rpc state reader to Papyrus state reader (the batcher will hold a local Papyrus storage instance).
</blockquote></details>

Still there's something here that I don't quite understand...
Why do we need the `GenericExecutor`? doesn't just having the trait enough for dependency injection?
The batcher can hold `impl Trait` or `dyn Trait`.

**Pull request closed without merging**
