### PR TITLE
chore(blockifier_reexecution): add contract class dumper to test_state_reader

### PR DESCRIPTION
**Pull request by aner-starkware**
…e_reader

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1724)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1724#-OAXjxiZ6Mpwob2HRDnd:-OAXjxiZ6Mpwob2HRDne:b44hnxz) ([raw file](https://github.com/starkware-libs/sequencer/blob/17bde6a3d80d6117036e526ebab19aa2e53fc2ea/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L44)):*
> ```XML
> pub type ReexecutionResult<T> = Result<T, ReexecutionError>;
> 
> pub type StarknetContractClassMapping = HashMap<ClassHash, StarknetContractClass>;
> ```

this is defined in a different PR, no?



_Code quote:_
```XML
pub type StarknetContractClassMapping = HashMap<ClassHash, StarknetContractClass>;
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1724#-OAXk4YgAVu6yTAl4ODm:-OAXk4YgAVu6yTAl4ODn:b-k1pjyq) ([raw file](https://github.com/starkware-libs/sequencer/blob/17bde6a3d80d6117036e526ebab19aa2e53fc2ea/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L90)):*
> ```XML
>         config: &RpcStateReaderConfig,
>         block_number: BlockNumber,
>         contract_class_mapping_dumper: Arc<Mutex<Option<StarknetContractClassMapping>>>,
> ```

I think you can just create this mapping dumper in here and not accept the arg externally, no?
or at least: pass a boolean `dump_mode` instead of this complex type, and if it's true, create a new mapping



_Code quote:_
```XML
contract_class_mapping_dumper: Arc<Mutex<Option<StarknetContractClassMapping>>>,
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1724#-OAXkGQyAX6tcgMqnJQi:-OAXkGQzARsg8P7QLUkw:bpxqq35) ([raw file](https://github.com/starkware-libs/sequencer/blob/17bde6a3d80d6117036e526ebab19aa2e53fc2ea/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L90)):*
> ```XML
>         config: &RpcStateReaderConfig,
>         block_number: BlockNumber,
>         contract_class_mapping_dumper: Arc<Mutex<Option<StarknetContractClassMapping>>>,
> ```

why is this `Option`?
the RPC reader will not need this if dump mode is off?



_Code quote:_
```XML
Option<StarknetContractClassMapping>
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 290 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1724#-OAXkgxb8-ycIkx0I4y9:-OAXkgxb8-ycIkx0I4yA:b-p0w93w) ([raw file](https://github.com/starkware-libs/sequencer/blob/17bde6a3d80d6117036e526ebab19aa2e53fc2ea/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L290)):*
> ```XML
>         last_constructed_block_number: BlockNumber,
>         config: Option<RpcStateReaderConfig>,
>         contract_class_mapping_dumper: Option<StarknetContractClassMapping>,
> ```

see above: prefer a boolean `dump_mode` input, to abstract this dumping mechanism away from the user of the TestStateReader



_Code quote:_
```XML
contract_class_mapping_dumper: Option<StarknetContractClassMapping>,
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1724)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1724#-OAXjxiZ6Mpwob2HRDnd:-OAXlzaa8craM5pMudST:bqgggb8) ([raw file](https://github.com/starkware-libs/sequencer/blob/17bde6a3d80d6117036e526ebab19aa2e53fc2ea/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L44)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is defined in a different PR, no?
</blockquote></details>

Yeah, because it's needed in both PRs, but other than that, they're independent.
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1724#-OAXkGQyAX6tcgMqnJQi:-OAXmKxF6t3LirBZwboO:b5msn01) ([raw file](https://github.com/starkware-libs/sequencer/blob/17bde6a3d80d6117036e526ebab19aa2e53fc2ea/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L90)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this `Option`?
the RPC reader will not need this if dump mode is off?
</blockquote></details>

Yes, that's the idea.
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1724#-OAXk4YgAVu6yTAl4ODm:-OAXoff_7vIgsg-twNa_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/17bde6a3d80d6117036e526ebab19aa2e53fc2ea/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L90)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think you can just create this mapping dumper in here and not accept the arg externally, no?
or at least: pass a boolean `dump_mode` instead of this complex type, and if it's true, create a new mapping
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 290 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1724#-OAXkgxb8-ycIkx0I4y9:-OAXogQlAShuu1Or85bn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/17bde6a3d80d6117036e526ebab19aa2e53fc2ea/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L290)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above: prefer a boolean `dump_mode` input, to abstract this dumping mechanism away from the user of the TestStateReader
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1724)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1724#-OAXpMlf5X2wYSbgYCCn:-OAXpMlf5X2wYSbgYCCo:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/5de6dc494b2bfca871ba84a30bd5de7ab8c3f858/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L91)):*
> ```XML
>             true => Arc::new(Mutex::new(Some(HashMap::new()))),
>             false => Arc::new(Mutex::new(None)),
>         };
> ```





_Suggestion:_
```XML
        let contract_class_mapping_dumper = Arc::new(Mutex::new(match dump_mode {
            true => Some(HashMap::new()),
            false => None,
        }));
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1724)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1724#-OAXpMlf5X2wYSbgYCCn:-OAXr22k4xV4aJIlt4ns:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5de6dc494b2bfca871ba84a30bd5de7ab8c3f858/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L91)):*
> ```XML
>             true => Arc::new(Mutex::new(Some(HashMap::new()))),
>             false => Arc::new(Mutex::new(None)),
>         };
> ```

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1724#-:-OAXtV-l34R0aH5GCrEk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
