### PR TITLE
chore(starknet_gateway): create bench file for benchmark test

### PR DESCRIPTION
**Pull request by ArniStarkware**
We can later discuss the details of the test cases we want to benchmark exactly.

Running the benchmarking action:
`cargo bench --bench gateway_bench`

Prints:
```
declares                time:   [0.0000 ps 0.0000 ps 0.0000 ps]
                        change: [-62.446% -29.235% +34.904%] (p = 0.33 > 0.05)
                        No change in performance detected.
Found 13 outliers among 100 measurements (13.00%)
  4 (4.00%) high mild
  9 (9.00%) high severe

deploy_accounts         time:   [0.0000 ps 0.0000 ps 0.0000 ps]
                        change: [-54.552% -11.417% +70.199%] (p = 0.73 > 0.05)
                        No change in performance detected.
Found 12 outliers among 100 measurements (12.00%)
  4 (4.00%) high mild
  8 (8.00%) high severe

invokes                 time:   [0.0000 ps 0.0000 ps 0.0000 ps]
                        change: [-46.424% -0.1889% +83.908%] (p = 1.00 > 0.05)
                        No change in performance detected.
Found 12 outliers among 100 measurements (12.00%)
  4 (4.00%) high mild
  8 (8.00%) high severe

all_transaction_types   time:   [0.0000 ps 0.0000 ps 0.0000 ps]
Found 12 outliers among 100 measurements (12.00%)
  4 (4.00%) high mild
  8 (8.00%) high severe
```

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#2404** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2404?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2404?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ArniStarkware** [comment]
The insparation is `blockifier_bench`.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2404)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_gateway/bench/gateway_bench.rs` line 14 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2404#-OF1vY7r2r9Iem0xoruc:-OF1vY7r2r9Iem0xorud:b-iwp4x7) ([raw file](https://github.com/starkware-libs/sequencer/blob/7cdfc96502d0f9434813c54cd6dd2d4e2702e5ed/crates/starknet_gateway/bench/gateway_bench.rs#L14)):*
> ```XML
> use criterion::{criterion_group, criterion_main, Criterion};
> 
> pub fn declare_benchmark(c: &mut Criterion) {
> ```

Can you explain these? What are they running?

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2404)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/starknet_gateway/Cargo.toml` line 42 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2404#-OF1vh0G5SgjvCt21eGi:-OF1vh0G5SgjvCt21eGj:bpotxgj) ([raw file](https://github.com/starkware-libs/sequencer/blob/7cdfc96502d0f9434813c54cd6dd2d4e2702e5ed/crates/starknet_gateway/Cargo.toml#L42)):*
> ```TOML
> assert_matches.workspace = true
> cairo-lang-sierra-to-casm.workspace = true
> criterion = { workspace = true, features = ["html_reports"] }
> ```

What is this feature for?



_Code quote:_
```TOML
"html_reports"
```

**Review by alonh5 — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2404)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2404)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_gateway/bench/gateway_bench.rs` line 14 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2404#-OF1vY7r2r9Iem0xoruc:-OF2KRd-Ap6uHOgX1wVE:b-nxk6mh) ([raw file](https://github.com/starkware-libs/sequencer/blob/7cdfc96502d0f9434813c54cd6dd2d4e2702e5ed/crates/starknet_gateway/bench/gateway_bench.rs#L14)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you explain these? What are they running?
</blockquote></details>

These = `declare_benchmark` etc?
These are the tests that are going to be run.

Should I have just one function for now? (just `invoke_benchmark` - which is being filled in the next PR: #2911)?


I wrote a comment on this PR demonstrating how the printed report of the test looks like.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2404)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_gateway/Cargo.toml` line 42 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2404#-OF1vh0G5SgjvCt21eGi:-OF2PMsDEP1X6CpByY3w:bvpeo2n) ([raw file](https://github.com/starkware-libs/sequencer/blob/7cdfc96502d0f9434813c54cd6dd2d4e2702e5ed/crates/starknet_gateway/Cargo.toml#L42)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What is this feature for?
</blockquote></details>

Removed. Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2404)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_gateway/bench/gateway_bench.rs` line 14 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2404#-OF1vY7r2r9Iem0xoruc:-OFHcKN_-oG5vWoMsBmG:b-m47er8) ([raw file](https://github.com/starkware-libs/sequencer/blob/7cdfc96502d0f9434813c54cd6dd2d4e2702e5ed/crates/starknet_gateway/bench/gateway_bench.rs#L14)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

These = `declare_benchmark` etc?
These are the tests that are going to be run.

Should I have just one function for now? (just `invoke_benchmark` - which is being filled in the next PR: #2911)?


I wrote a comment on this PR demonstrating how the printed report of the test looks like.
</blockquote></details>

Yes, let's just have one. We can add more later easily.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2404)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/starknet_gateway/bench/gateway_bench.rs` line 14 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2404#-OF1vY7r2r9Iem0xoruc:-OFHcsFQ4XbrMcb3omyD:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7cdfc96502d0f9434813c54cd6dd2d4e2702e5ed/crates/starknet_gateway/bench/gateway_bench.rs#L14)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Yes, let's just have one. We can add more later easily.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2404#-:-OFHff4f-sqcELKefNAc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
