### PR TITLE
chore: add flamegraph generation script for committer

### PR DESCRIPTION
**Pull request by aner-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Other (please describe):

## What is the new behavior?

script for generating a flame-graph for the committer

## Does this introduce a breaking change?

- [ ] No

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/89)

### CODE REVIEW

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/89)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/89#-O2dsPFA8lPStytvUXcl:-O2dsPFA8lPStytvUXcm:bxtd12y) (no related file):*
1. This file shouldn't be in the root dir of the project. In scripts, or IMO under `scripts/committer`
2. Should this script run in github actions? Do you know how sudo commands behave in there if it does?

___
___
*[`generate_committer_flamegraph.sh` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/89#-O2drhko-iRBFjeK88be:-O2drhko-iRBFjeK88bf:buw0nea) ([raw file](https://github.com/starkware-libs/sequencer/blob/73087da59b5c2d8070111775e116ad4b59146bc9/generate_committer_flamegraph.sh#L1)):*
> ```Shell
> trap 'echo 4 | sudo tee /proc/sys/kernel/perf_event_paranoid ' EXIT SIGINT SIGTERM
> ```

What's this? Doesn't it write 4 to the file and prints 4 to the screen?



_Code quote:_
```Shell
'echo 4 | sudo tee /proc/sys/kernel/perf_event_paranoid '
```
___
*[`generate_committer_flamegraph.sh` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/89#-O2dlqkC6qzmdHzmGYb4:-O2dlqkC6qzmdHzmGYb5:b-1mxn9w) ([raw file](https://github.com/starkware-libs/sequencer/blob/73087da59b5c2d8070111775e116ad4b59146bc9/generate_committer_flamegraph.sh#L14)):*
> ```Shell
> echo 2 | sudo tee /proc/sys/kernel/perf_event_paranoid
> 
> gcloud storage cat gs://committer-testing-artifacts/23ffcf5/committer_flow_inputs.json | jq -r .committer_input | CARGO_PROFILE_RELEASE_DEBUG=true cargo flamegraph -p committer_cli -- commit
> ```

Shouldn't this be read from the flow_test_files_prefix file?



_Code quote:_
```Shell
23ffcf5
```
___
*[`generate_committer_flamegraph.sh` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/89#-O2dssnJEGeaelbU5jMc:-O2dssnJEGeaelbU5jMd:bkwo544) ([raw file](https://github.com/starkware-libs/sequencer/blob/73087da59b5c2d8070111775e116ad4b59146bc9/generate_committer_flamegraph.sh#L16)):*
> ```Shell
> gcloud storage cat gs://committer-testing-artifacts/23ffcf5/committer_flow_inputs.json | jq -r .committer_input | CARGO_PROFILE_RELEASE_DEBUG=true cargo flamegraph -p committer_cli -- commit
> 
> echo 4 | sudo tee /proc/sys/kernel/perf_event_paranoid
> ```

What's this again, and why is defined here as well?



_Code quote:_
```Shell
cho 4 | sudo tee /proc/sys/kernel/perf_event_paranoid
```

**Comment by aner-starkware** [comment]
*[`generate_committer_flamegraph.sh` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/89#-O2drhko-iRBFjeK88be:-O2dydy-2Dmtw7rDO4Tp:b2nhswy) ([raw file](https://github.com/starkware-libs/sequencer/blob/73087da59b5c2d8070111775e116ad4b59146bc9/generate_committer_flamegraph.sh#L1)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

What's this? Doesn't it write 4 to the file and prints 4 to the screen?
</blockquote></details>

Yes

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/89)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`generate_committer_flamegraph.sh` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/89#-O2dlqkC6qzmdHzmGYb4:-O2dyjTx-HfBw8rPmMym:b-kubekd) ([raw file](https://github.com/starkware-libs/sequencer/blob/73087da59b5c2d8070111775e116ad4b59146bc9/generate_committer_flamegraph.sh#L14)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Shouldn't this be read from the flow_test_files_prefix file?
</blockquote></details>

You're right of course!
Done.
___
*[`generate_committer_flamegraph.sh` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/89#-O2dssnJEGeaelbU5jMc:-O2dynDt9PDoLW0WyeD5:bem2i3c) ([raw file](https://github.com/starkware-libs/sequencer/blob/73087da59b5c2d8070111775e116ad4b59146bc9/generate_committer_flamegraph.sh#L16)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

What's this again, and why is defined here as well?
</blockquote></details>

It's defined twice for paranoidal reasons :grin: (once in standard EXIT and once using trap to make sure it's executed anyway, even in case of error)

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/89)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/89#-O2dsPFA8lPStytvUXcl:-O2e0KPz3YLGYdWzDed5:blf9bbv) (no related file):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

1. This file shouldn't be in the root dir of the project. In scripts, or IMO under `scripts/committer`
2. Should this script run in github actions? Do you know how sudo commands behave in there if it does?
</blockquote></details>

1. Done.
2. I don't think it's supposed to run in github actions for now, right @dorimedini-starkware ?

___

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/89)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`generate_committer_flamegraph.sh` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/89#-O2drhko-iRBFjeK88be:-O2e08aw47Bfeu9Ea8P1:b-wg1n4q) ([raw file](https://github.com/starkware-libs/sequencer/blob/73087da59b5c2d8070111775e116ad4b59146bc9/generate_committer_flamegraph.sh#L1)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Yes
</blockquote></details>

OK, and why do you do it? Need some comments here to explain why this is needed.
___
*[`generate_committer_flamegraph.sh` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/89#-O2dssnJEGeaelbU5jMc:-O2s__bGCG_8WjvDfYCP:b-1yxk9o) ([raw file](https://github.com/starkware-libs/sequencer/blob/73087da59b5c2d8070111775e116ad4b59146bc9/generate_committer_flamegraph.sh#L16)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

It's defined twice for paranoidal reasons :grin: (once in standard EXIT and once using trap to make sure it's executed anyway, even in case of error)
</blockquote></details>

I think the trap, works in an standard exit (as defined in the EXIT op) as well so this seems redundant (please verify).

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/89)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`generate_committer_flamegraph.sh` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/89#-O2drhko-iRBFjeK88be:-O2tQeD_49XjMJTfMKVN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/73087da59b5c2d8070111775e116ad4b59146bc9/generate_committer_flamegraph.sh#L1)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

OK, and why do you do it? Need some comments here to explain why this is needed.
</blockquote></details>

Done.
___
*[`generate_committer_flamegraph.sh` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/89#-O2dssnJEGeaelbU5jMc:-O2tQfDy1nPRKM-fJxnS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/73087da59b5c2d8070111775e116ad4b59146bc9/generate_committer_flamegraph.sh#L16)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I think the trap, works in an standard exit (as defined in the EXIT op) as well so this seems redundant (please verify).
</blockquote></details>

Done.

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/89)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`scripts/committer/generate_committer_flamegraph.sh` line 1 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/89#-O2yTindA1JxdAsIP-cm:-O2yTindA1JxdAsIP-cn:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea6be75e5717430596e26666c779a209a69e877f/scripts/committer/generate_committer_flamegraph.sh#L1)):*
> ```Shell
> # Restore security level in perf_event_paranoid to 4.
> ```





_Suggestion:_
```Shell
set -e

# Restore security level in perf_event_paranoid to 4.
```
___
*[`scripts/committer/generate_committer_flamegraph.sh` line 2 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/89#-O2yQ4iY2oFm05TleRtA:-O2yQ4iY2oFm05TleRtB:bqbyqad) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea6be75e5717430596e26666c779a209a69e877f/scripts/committer/generate_committer_flamegraph.sh#L2)):*
> ```Shell
> # Restore security level in perf_event_paranoid to 4.
> trap 'echo 4 | sudo tee /proc/sys/kernel/perf_event_paranoid ' EXIT SIGINT SIGTERM
> ```

There is a custom command for this, which is better than manually overriding system files.



_Suggestion:_
```Shell
ORIGINAL_PARANOID=$(echo $(sysctl kernel.perf_event_paranoid) | grep -o '[0-9]$')
trap 'sudo sysctl kernel.perf_event_paranoid=$ORIGINAL_PARANOID`
```
___
*[`scripts/committer/generate_committer_flamegraph.sh` line 17 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/89#-O2yTLJ2DhIqZKRe2U8P:-O2yTLJ2DhIqZKRe2U8Q:bd89los) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea6be75e5717430596e26666c779a209a69e877f/scripts/committer/generate_committer_flamegraph.sh#L17)):*
> ```Shell
> BENCH_INPUT_FILES_PREFIX=$(cat ${ROOT_DIR}/crates/committer_cli/src/tests/flow_test_files_prefix)
> # Lower security level in perf_event_paranoid to 2 to allow cargo to use perf without running on root.
> echo 2 | sudo tee /proc/sys/kernel/perf_event_paranoid
> ```

@dorimedini-starkware



_Suggestion:_
```Shell
sudo sysctl kernel.perf_event_paranoid=2
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/89)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`scripts/committer/generate_committer_flamegraph.sh` line 2 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/89#-O2yQ4iY2oFm05TleRtA:-O31_6JmA3ZLLRXcDgEC:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea6be75e5717430596e26666c779a209a69e877f/scripts/committer/generate_committer_flamegraph.sh#L2)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

There is a custom command for this, which is better than manually overriding system files.
</blockquote></details>

Done.
___
*[`scripts/committer/generate_committer_flamegraph.sh` line 17 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/89#-O2yTLJ2DhIqZKRe2U8P:-O31_6pc3DY2r2lqIWpm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ea6be75e5717430596e26666c779a209a69e877f/scripts/committer/generate_committer_flamegraph.sh#L17)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

@dorimedini-starkware
</blockquote></details>

Done.

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/89)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`scripts/committer/generate_committer_flamegraph.sh` line 3 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/89#-O32t9cZ1C9qYoDvO_rN:-O32t9cZ1C9qYoDvO_rO:b-s6wsjs) ([raw file](https://github.com/starkware-libs/sequencer/blob/1484558a2a7e17b9aab1fa03a9eaa312f68ac203/scripts/committer/generate_committer_flamegraph.sh#L3)):*
> ```Shell
> set -e
> 
> if GITHUB_ACTIONS; then
> ```

`if $VAR;` evaluates to true for undefined vars.



_Suggestion:_
```Shell
if [ "$GITHUB_ACTIONS" = true ];
```

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/89)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/89)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`scripts/committer/generate_committer_flamegraph.sh` line 3 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/89#-O32t9cZ1C9qYoDvO_rN:-O32xf-xAL60zfnOYHjA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1484558a2a7e17b9aab1fa03a9eaa312f68ac203/scripts/committer/generate_committer_flamegraph.sh#L3)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

`if $VAR;` evaluates to true for undefined vars.
</blockquote></details>

Done.

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/89#-:-O36_Zkk8zMzVitL0qES:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
