### PR TITLE
refactor(batcher): create the tx provider in the batcher

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Comment by yair-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1879?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1879** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1879?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1870** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1870?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1791** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1791?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1788** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1788?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1787** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1787?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yair-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1879)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager_test.rs` line 218 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBK2ULO9RVflJrlr3XX:-OBK2ULO9RVflJrlr3XY:b-w2naby) ([raw file](https://github.com/starkware-libs/sequencer/blob/038c2e502828c1e8bd8c8043de920885c57338ff/crates/batcher/src/proposal_manager_test.rs#L218)):*
> ```XML
>     mock_dependencies.expect_long_build_block(1);
> 
>     let tx_provider_0 = propose_tx_provider(&mock_dependencies);
> ```

This line is repeated across all tests.

I suggest the create a function that does the following:
1. create the tx_provider
2. create the output channel
3. run proposal_manager.build_block_proposal

(can be in a separate PR).



_Code quote:_
```XML
let tx_provider_0 = propose_tx_provider(&mock_dependencies);
```
___
*[`crates/batcher/src/batcher.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBJzd5X0j6d3baS-RI8:-OBJzd5X0j6d3baS-RI9:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/038c2e502828c1e8bd8c8043de920885c57338ff/crates/batcher/src/batcher.rs#L104)):*
> ```XML
>             )
>             .await
>             .map_err(BatcherError::from)?;
> ```





_Suggestion:_
```XML
        let tx_provider =  ProposeTransactionProvider {
                mempool_client: self.mempool_client.clone(),
                // TODO: use a real L1 provider client.
                l1_provider_client: Arc::new(DummyL1ProviderClient),
            };
        self.proposal_manager
            .build_block_proposal(
                build_proposal_input.proposal_id,
                build_proposal_input.retrospective_block_hash,
                deadline,
                tx_sender,
                tx_provider,
            )
            .await
            .map_err(BatcherError::from)?;
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1879)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @alonh5, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/proposal_manager_test.rs` line 218 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBK2ULO9RVflJrlr3XX:-OBKa7el6KUwi0Ei_48w:bissmhr) ([raw file](https://github.com/starkware-libs/sequencer/blob/038c2e502828c1e8bd8c8043de920885c57338ff/crates/batcher/src/proposal_manager_test.rs#L218)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

This line is repeated across all tests.

I suggest the create a function that does the following:
1. create the tx_provider
2. create the output channel
3. run proposal_manager.build_block_proposal

(can be in a separate PR).
</blockquote></details>

`init_proposal_manager` consumes `mock_dependencies` and needs to be called before starting the block proposal
___
*[`crates/batcher/src/batcher.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBJzd5X0j6d3baS-RI8:-OBK_qJ26TL1Kn_7Xrd5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/038c2e502828c1e8bd8c8043de920885c57338ff/crates/batcher/src/batcher.rs#L104)):*
> ```XML
>             )
>             .await
>             .map_err(BatcherError::from)?;
> ```

Done.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1879)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @alonh5, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager_test.rs` line 218 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBK2ULO9RVflJrlr3XX:-OBL0GxUDJ-1FYrOQ_U5:b9lrpvo) ([raw file](https://github.com/starkware-libs/sequencer/blob/038c2e502828c1e8bd8c8043de920885c57338ff/crates/batcher/src/proposal_manager_test.rs#L218)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

`init_proposal_manager` consumes `mock_dependencies` and needs to be called before starting the block proposal
</blockquote></details>

right, but it actually needs to consume different fields than the tx_provider fields. Indeed requires a small refactor.
___
*[`crates/batcher/src/proposal_manager_test.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBL-4K11AtMDJIuHtWm:-OBL-4K11AtMDJIuHtWn:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f04b9a60de99e32c83cd609c1fa4876e8ed34b4/crates/batcher/src/proposal_manager_test.rs#L45)):*
> ```XML
>     mempool_client: Arc<MockMempoolClient>,
>     storage_reader: MockBatcherStorageReaderTrait,
> }
> ```





_Suggestion:_
```XML
struct MockDependencies {
    block_builder_factory: MockBlockBuilderFactoryTrait,
    tx_provider: Arc<MockTransactionProvider>,
    storage_reader: MockBatcherStorageReaderTrait,
}
```
___
*[`crates/batcher/src/proposal_manager_test.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBL-EYK2vHKQC3Ndr-L:-OBL-EYK2vHKQC3Ndr-M:b-1li2i1) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f04b9a60de99e32c83cd609c1fa4876e8ed34b4/crates/batcher/src/proposal_manager_test.rs#L90)):*
> ```XML
>         block_builder_factory: MockBlockBuilderFactoryTrait::new(),
>         mempool_client: Arc::new(MockMempoolClient::new()),
>         storage_reader,
> ```

and then you don't need the function propose_tx_provider()



_Suggestion:_
```XML
        l1_provider_client: Arc::new(MockL1ProviderClientTrait::new()),
        mock_transaction_provider: Arc:new(ProposeTransactionProvider {
            mempool_client: MockL1ProviderClientTrait::new(),
            l1_provider_client: MockL1ProviderClientTrait::new(),
        )}
        storage_reader,
```

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1879)* status: 5 of 7 files reviewed, 6 unresolved discussions (waiting on @alonh5, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBL0XM8824keaHIknS8:-OBL0XM8824keaHIknS9:b-6kctpv) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f04b9a60de99e32c83cd609c1fa4876e8ed34b4/crates/batcher/src/block_builder.rs#L105)):*
> ```XML
> impl BlockBuilderTrait for BlockBuilder {
>     async fn build_block(
>         &mut self,
> ```

Why mut?
`tx_provider.get_txs` is expecting `&self `.



_Code quote:_
```XML
&mut self,
```
___
*[`crates/batcher/src/proposal_manager.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBL47NqA0jEorjkdSnz:-OBL47NqA0jEorjkdSo-:b-ff0z5t) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f04b9a60de99e32c83cd609c1fa4876e8ed34b4/crates/batcher/src/proposal_manager.rs#L75)):*
> ```XML
>         deadline: tokio::time::Instant,
>         tx_sender: tokio::sync::mpsc::UnboundedSender<Transaction>,
>         tx_provider: ProposeTransactionProvider,
> ```

Does the proposal manager needs to know that this is a `ProposeTransactionProvider`?
Consider using `dyn TransactionProvider` and than you can also use `MockTransactionProvider` in the tests.



_Code quote:_
```XML
ProposeTransactionProvider
```
___
*[`crates/batcher/src/transaction_provider.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBL4d_Y7OMOrwTF_rlm:-OBL4d_Y7OMOrwTF_rln:bb7r2f0) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f04b9a60de99e32c83cd609c1fa4876e8ed34b4/crates/batcher/src/transaction_provider.rs#L74)):*
> ```XML
> pub trait L1ProviderClientTrait: Send + Sync {
>     #[allow(dead_code)]
>     fn get_txs(&mut self, n_txs: usize) -> Vec<L1HandlerTransaction>;
> ```

why?



_Code quote:_
```XML
&mut 
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1879)* status: 5 of 7 files reviewed, 6 unresolved discussions (waiting on @alonh5, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBL0XM8824keaHIknS8:-OBL4w-L0Nvs3e4JfHF9:b-3s57xl) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f04b9a60de99e32c83cd609c1fa4876e8ed34b4/crates/batcher/src/block_builder.rs#L105)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why mut?
`tx_provider.get_txs` is expecting `&self `.
</blockquote></details>

The tx provider needs to remember how many l1handler txs were already fetched
___
*[`crates/batcher/src/proposal_manager.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBL47NqA0jEorjkdSnz:-OBL5FZE9gnMPzy_6ll7:bxeby9i) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f04b9a60de99e32c83cd609c1fa4876e8ed34b4/crates/batcher/src/proposal_manager.rs#L75)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Does the proposal manager needs to know that this is a `ProposeTransactionProvider`?
Consider using `dyn TransactionProvider` and than you can also use `MockTransactionProvider` in the tests.
</blockquote></details>

I want to force the user to provide the correct TX provider. 
___
*[`crates/batcher/src/proposal_manager_test.rs` line 218 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBK2ULO9RVflJrlr3XX:-OBL6taP9_YNhNHdRpCk:byx5lah) ([raw file](https://github.com/starkware-libs/sequencer/blob/038c2e502828c1e8bd8c8043de920885c57338ff/crates/batcher/src/proposal_manager_test.rs#L218)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

right, but it actually needs to consume different fields than the tx_provider fields. Indeed requires a small refactor.
</blockquote></details>

Let's discuss and implement in a separate PR
___
*[`crates/batcher/src/proposal_manager_test.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBL-EYK2vHKQC3Ndr-L:-OBL6f6922MJhObGT7t2:b7wks2o) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f04b9a60de99e32c83cd609c1fa4876e8ed34b4/crates/batcher/src/proposal_manager_test.rs#L90)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

and then you don't need the function propose_tx_provider()
</blockquote></details>

Answered in previous comments
___
*[`crates/batcher/src/transaction_provider.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBL4d_Y7OMOrwTF_rlm:-OBL834n1H3J-meSAq4l:bc90zu8) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f04b9a60de99e32c83cd609c1fa4876e8ed34b4/crates/batcher/src/transaction_provider.rs#L74)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

why?
</blockquote></details>

mistake, reverted
___
*[`crates/batcher/src/proposal_manager_test.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBL-4K11AtMDJIuHtWm:-OBL6O9E1Bpw8zI7_uQF:b-bqmbpa) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f04b9a60de99e32c83cd609c1fa4876e8ed34b4/crates/batcher/src/proposal_manager_test.rs#L45)):*
> ```XML
>     mempool_client: Arc<MockMempoolClient>,
>     storage_reader: MockBatcherStorageReaderTrait,
> }
> ```

I need to create specifically `ProposeTransactionProvider`, not a mock

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1879)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager_test.rs` line 218 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBK2ULO9RVflJrlr3XX:-OBLBxS1Bl7E70nJ7Nus:basgj2o) ([raw file](https://github.com/starkware-libs/sequencer/blob/038c2e502828c1e8bd8c8043de920885c57338ff/crates/batcher/src/proposal_manager_test.rs#L218)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Let's discuss and implement in a separate PR
</blockquote></details>

Sure, marked as non blocking
___
*[`crates/batcher/src/proposal_manager_test.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBL-4K11AtMDJIuHtWm:-OBLC1Db5oWe8UUUKL-p:b-msz9no) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f04b9a60de99e32c83cd609c1fa4876e8ed34b4/crates/batcher/src/proposal_manager_test.rs#L45)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I need to create specifically `ProposeTransactionProvider`, not a mock
</blockquote></details>

Ok, but still this can be computed in advance and not for every test separately. 
again, can be refactored later,  non-blocking.
___
*[`crates/batcher/src/proposal_manager_test.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBL-EYK2vHKQC3Ndr-L:-OBLCP1v6mTc1k4r2uDq:b2nhysk) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f04b9a60de99e32c83cd609c1fa4876e8ed34b4/crates/batcher/src/proposal_manager_test.rs#L90)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Answered in previous comments
</blockquote></details>

ack

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1879)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @alonh5, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/proposal_manager_test.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBL-4K11AtMDJIuHtWm:-OBLGbJg8nhylNi4pEUN:bgrwxim) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f04b9a60de99e32c83cd609c1fa4876e8ed34b4/crates/batcher/src/proposal_manager_test.rs#L45)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Ok, but still this can be computed in advance and not for every test separately. 
again, can be refactored later,  non-blocking.
</blockquote></details>

We need a new provider for each call to `build_block_proposal` so I don't see how you can escape it

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1879)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBL47NqA0jEorjkdSnz:-OBOtUIfCVmbWfu2gSoo:brvfj7q) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f04b9a60de99e32c83cd609c1fa4876e8ed34b4/crates/batcher/src/proposal_manager.rs#L75)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I want to force the user to provide the correct TX provider.
</blockquote></details>

Not sure there is a justification for distinguishing between propose and validate in the proposal manager anymore, now that we moved the tx_provider responsibility to the batcher.

This is non-blocking, but worth consideration IMO.
___
*[`crates/batcher/src/proposal_manager_test.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1879#-OBL-4K11AtMDJIuHtWm:-OBOsyqv939VCpC7ZUTg:byydmuo) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f04b9a60de99e32c83cd609c1fa4876e8ed34b4/crates/batcher/src/proposal_manager_test.rs#L45)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

We need a new provider for each call to `build_block_proposal` so I don't see how you can escape it
</blockquote></details>

Maybe you can create them inside `build_and_await_block_proposal`

**Review by alonh5 — APPROVED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1879)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1879)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Comment by yair-starkware** [comment]
### Merge activity

* **Nov 12, 5:54 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1879).

**Pull request merged**
