### PR TITLE
chore(blockifier,starknet_api): move l1handler to executable tx

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Comment by yair-starkware** [comment]
* **#1723** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1723?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yair-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1723)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @giladchase, @noaov1, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1723#-OAXy-3bCJ1DWjO51d8O:-OAXy-3bCJ1DWjO51d8P:b75ejq4) (no related file):*
After looking into it again, I think we might have to add L1HandlerTransaction to the executable_transaction enum, because the transactin providers get_txs return type has to be consistent. I'm fine with adding it, even if the mempool can't return it. WDYT? @yair-starkware @noaov1 @giladchase 

___
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 227 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1723#-OAXnI_t8eJ1cMNTRHfO:-OAXnI_t8eJ1cMNTRHfP:bm81jd) ([raw file](https://github.com/starkware-libs/sequencer/blob/2cae216e94f2f1f86ecae8a5a6bc337c26c4a2ab/crates/blockifier/src/test_utils/struct_impls.rs#L227)):*
> ```XML
> }
> 
> pub trait CreateForTesting {
> ```

How about moving this impl also? Creating a trait just for a single impl block seems weird

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1723)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @giladchase and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1723#-OAXy-3bCJ1DWjO51d8O:-OAYCzRdDfxpMdGlFFss:bdq9mbo) (no related file):*
> get\_txs return type has to be consistent

I see that it is currently divided into two providers (one for [Transaction](https://github.com/starkware-libs/sequencer/blob/b908324b13a9fd26a66b46ed4b3fd22576e6fd1c/crates/starknet_api/src/executable_transaction.rs#L45) and one for [L1HandlerTransaction](https://github.com/starkware-libs/sequencer/blob/891a68c4e486f4a7c5481871bea3aab2bf362236/crates/starknet_api/src/transaction.rs#L622). Anyway, it can be consistent by defining a Transaction enum that contains an account transaction and an L1 handler. I think the separation is required (the execution flows are different).
WDYT?

___

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1723)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @alonh5, @giladchase, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1723#-OAXy-3bCJ1DWjO51d8O:-OAl-SFbDQqUy4N0L5I6:bi0m21p) (no related file):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

> get\_txs return type has to be consistent

I see that it is currently divided into two providers (one for [Transaction](https://github.com/starkware-libs/sequencer/blob/b908324b13a9fd26a66b46ed4b3fd22576e6fd1c/crates/starknet_api/src/executable_transaction.rs#L45) and one for [L1HandlerTransaction](https://github.com/starkware-libs/sequencer/blob/891a68c4e486f4a7c5481871bea3aab2bf362236/crates/starknet_api/src/transaction.rs#L622). Anyway, it can be consistent by defining a Transaction enum that contains an account transaction and an L1 handler. I think the separation is required (the execution flows are different).
WDYT?
</blockquote></details>

We talked about it in the meeting.
Each provider can return its own type and the blockifier adds another type which is an enum of both of them.
We convert `executable_transaction` into the blockifier type anyways.

___
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 227 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1723#-OAXnI_t8eJ1cMNTRHfO:-OAl-var6ppRaL3EvJ0_:b-3j3wyj) ([raw file](https://github.com/starkware-libs/sequencer/blob/2cae216e94f2f1f86ecae8a5a6bc337c26c4a2ab/crates/blockifier/src/test_utils/struct_impls.rs#L227)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

How about moving this impl also? Creating a trait just for a single impl block seems weird
</blockquote></details>

We don't have testing instances for the other types in SN_API so I don't want to introduce a new module just for that

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1723)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase, @noaov1, and @yair-starkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 227 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1723#-OAXnI_t8eJ1cMNTRHfO:-OAl1-Tc7-MVC08AeEsf:b35alw6) ([raw file](https://github.com/starkware-libs/sequencer/blob/2cae216e94f2f1f86ecae8a5a6bc337c26c4a2ab/crates/blockifier/src/test_utils/struct_impls.rs#L227)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

We don't have testing instances for the other types in SN_API so I don't want to introduce a new module just for that
</blockquote></details>

You can add a cfg(test) over it

**Comment by yair-starkware** [comment]
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 227 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1723#-OAXnI_t8eJ1cMNTRHfO:-OAlE9EaE1WuCCQKtUkJ:b6fo9s1) ([raw file](https://github.com/starkware-libs/sequencer/blob/2cae216e94f2f1f86ecae8a5a6bc337c26c4a2ab/crates/blockifier/src/test_utils/struct_impls.rs#L227)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You can add a cfg(test) over it
</blockquote></details>

It uses `selector_from_name`which is defined in blockifier

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1723)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase, @noaov1, and @yair-starkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 227 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1723#-OAXnI_t8eJ1cMNTRHfO:-OAlXKqD5ufiw0l8iwpm:b-j56nlz) ([raw file](https://github.com/starkware-libs/sequencer/blob/2cae216e94f2f1f86ecae8a5a6bc337c26c4a2ab/crates/blockifier/src/test_utils/struct_impls.rs#L227)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

It uses `selector_from_name`which is defined in blockifier
</blockquote></details>

Okay so leave it here. Can you turn it into a regular function please?
`l1_handler_tx()` in a separate file like the other 3 txs

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1723)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @alonh5, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 227 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1723#-OAXnI_t8eJ1cMNTRHfO:-OAmBg-Z2eJBCoAAT_eR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2cae216e94f2f1f86ecae8a5a6bc337c26c4a2ab/crates/blockifier/src/test_utils/struct_impls.rs#L227)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Okay so leave it here. Can you turn it into a regular function please?
`l1_handler_tx()` in a separate file like the other 3 txs
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1723#-:-OAmCH325S0rn8Uh37JY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)

**Pull request merged**
