### PR TITLE
feat(blockifier): only All resource bounds txs can run in SierraGas mode

### PR DESCRIPTION
**Pull request by TzahiTaub**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1771)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1 and @TzahiTaub)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1771#-OAn2ZJHAhhP0DTGjdQi:-OAn2ZJHAhhP0DTGjdQj:b9gyvq5) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb9b8c1f44f51fc247b5de6010fe6439db2d5966/crates/blockifier/src/execution/contract_class.rs#L139)):*
> ```XML
>         &self,
>         min_sierra_version: &CompilerVersion,
>         is_all_resources_bound: bool,
> ```

... and then `match` instead of `if-else`ing it



_Suggestion:_
```XML
gas_mode: GasVectorComputationMode
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1771#-OAn2qrJ98E6NS65D92B:-OAn2qrKEQSNkLAIJMt2:b-8nvuh1) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb9b8c1f44f51fc247b5de6010fe6439db2d5966/crates/blockifier/src/execution/contract_class.rs#L148)):*
> ```XML
>                 }
>                 #[cfg(feature = "cairo_native")]
>                 RunnableContractClass::V1Native(_) => TrackedResource::SierraGas,
> ```

revert this change



_Suggestion:_
```XML
                Self::V0(_) => TrackedResource::CairoSteps,
                Self::V1(contract_class) => {
                    contract_class.tracked_resource(min_sierra_version)
                }
                #[cfg(feature = "cairo_native")]
                Self::V1Native(_) => TrackedResource::SierraGas,
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1771#-OAn37eTC7p1sRMNLwOD:-OAn37eTC7p1sRMNLwOE:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb9b8c1f44f51fc247b5de6010fe6439db2d5966/crates/blockifier/src/transaction/objects.rs#L89)):*
> ```XML
>     }
> 
>     pub fn is_all_resources_bound(&self) -> bool {
> ```





_Suggestion:_
```XML
pub fn gas_mode(&self) -> GasVectorComputationMode
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 482 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1771#-OAn3ONXDA6CABSXuU28:-OAn3ONXDA6CABSXuU29:b7nqewg) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb9b8c1f44f51fc247b5de6010fe6439db2d5966/crates/blockifier/src/transaction/transactions_test.rs#L482)):*
> ```XML
>         // In CairoSteps mode, the initial gas is set to the default once before the validate call.
>         expected_arguments.inner_call_initial_gas -=
>             expected_arguments.validate_gas_consumed + expected_arguments.execute_gas_consumed
> ```

why is this so hard...
... explain to me please why, in cairo steps mode, we need to deduct from the expected initial gas in the inner call...?



_Code quote:_
```XML
        expected_arguments.inner_call_initial_gas -=
            expected_arguments.validate_gas_consumed + expected_arguments.execute_gas_consumed
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1771)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1771#-OAn2ZJHAhhP0DTGjdQi:-OAqVYtH7ey1nY5qXsXq:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb9b8c1f44f51fc247b5de6010fe6439db2d5966/crates/blockifier/src/execution/contract_class.rs#L139)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

... and then `match` instead of `if-else`ing it
</blockquote></details>

Done
___
*[`crates/blockifier/src/execution/contract_class.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1771#-OAn2qrJ98E6NS65D92B:-OAqUV1g-yHgYD40TRF-:b-834n6i) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb9b8c1f44f51fc247b5de6010fe6439db2d5966/crates/blockifier/src/execution/contract_class.rs#L148)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

revert this change
</blockquote></details>

Oops.
___
*[`crates/blockifier/src/transaction/objects.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1771#-OAn37eTC7p1sRMNLwOD:-OAqWM8IDajrwzbeu1Gp:b-133p8i) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb9b8c1f44f51fc247b5de6010fe6439db2d5966/crates/blockifier/src/transaction/objects.rs#L89)):*
> ```XML
>     }
> 
>     pub fn is_all_resources_bound(&self) -> bool {
> ```

Does "NoL2Gas" mean L1Gas, or (either L1Gas or fee)?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 482 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1771#-OAn3ONXDA6CABSXuU28:-OAqUnVTCm42WOyyHgXf:b-5y2w5v) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb9b8c1f44f51fc247b5de6010fe6439db2d5966/crates/blockifier/src/transaction/transactions_test.rs#L482)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this so hard...
... explain to me please why, in cairo steps mode, we need to deduct from the expected initial gas in the inner call...?
</blockquote></details>

I sort of wrote in the comment - in every tx that doesn't run entirely in Gas mode, you have a single location (the switch from Gas mode to VM mode) where you assign `default_initial_gas` to the call's initial gas. If the entire tx runs in VM mode like here, this is done at the start, and then after validate is done you have initial_gas = prev_initial_gas - validate_gas_consumed for the initial of execute, and similarly you have that minus the execute cost before getting to the first inner call as the inner call initial gas.

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1771)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 482 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1771#-OAn3ONXDA6CABSXuU28:-OAqZcrq8v4M0YzYPwsl:brpmupy) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb9b8c1f44f51fc247b5de6010fe6439db2d5966/crates/blockifier/src/transaction/transactions_test.rs#L482)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I sort of wrote in the comment - in every tx that doesn't run entirely in Gas mode, you have a single location (the switch from Gas mode to VM mode) where you assign `default_initial_gas` to the call's initial gas. If the entire tx runs in VM mode like here, this is done at the start, and then after validate is done you have initial_gas = prev_initial_gas - validate_gas_consumed for the initial of execute, and similarly you have that minus the execute cost before getting to the first inner call as the inner call initial gas.
</blockquote></details>

Remember that the initial gas and gas consumed are updated even in CairoSteps mode calls.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1771)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/objects.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1771#-OAn37eTC7p1sRMNLwOD:-OArF_pM5PQ0ClQ1JsAT:byamh9k) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb9b8c1f44f51fc247b5de6010fe6439db2d5966/crates/blockifier/src/transaction/objects.rs#L89)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Does "NoL2Gas" mean L1Gas, or (either L1Gas or fee)?
</blockquote></details>

when computing a gas vector (for the receipt), we either include L2 gas or not.
for v3 txs without L2 gas and for v1 txs, we always show L1 gas and L1 data gas consumed;
so the only difference is whether or not we show L2 gas
___
*[`crates/blockifier/src/transaction/objects.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1771#-OArG2JCCoyhUzpII_O9:-OArG2JCCoyhUzpII_OA:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/75c5a81b23e74ae2f7c6eb3f1ae18598cfd2bd09/crates/blockifier/src/transaction/objects.rs#L95)):*
> ```XML
>                 ValidResourceBounds::L1Gas(_) => GasVectorComputationMode::NoL2Gas,
>                 ValidResourceBounds::AllResources(_) => GasVectorComputationMode::All,
>             },
> ```





_Suggestion:_
```XML
            TransactionInfo::Current(info) => info.resource_bounds.get_gas_vector_computation_mode(),
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1771)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/objects.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1771#-OAn37eTC7p1sRMNLwOD:-OAsIU1f3C1GePqiJ2MO:b-8ev2km) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb9b8c1f44f51fc247b5de6010fe6439db2d5966/crates/blockifier/src/transaction/objects.rs#L89)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

when computing a gas vector (for the receipt), we either include L2 gas or not.
for v3 txs without L2 gas and for v1 txs, we always show L1 gas and L1 data gas consumed;
so the only difference is whether or not we show L2 gas
</blockquote></details>

OK, not sure how it answer my question. I want to know that NoL2Gas is used to represent a V1 tx with fee field instead of the newer resource bounds. Because this `gas_mode` function will return `NoL2Gas` for such txs, and I want to verify it won't be misleading.
___
*[`crates/blockifier/src/transaction/objects.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1771#-OArG2JCCoyhUzpII_O9:-OAsIyxC43C0t9uJUQT3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/75c5a81b23e74ae2f7c6eb3f1ae18598cfd2bd09/crates/blockifier/src/transaction/objects.rs#L95)):*
> ```XML
>                 ValidResourceBounds::L1Gas(_) => GasVectorComputationMode::NoL2Gas,
>                 ValidResourceBounds::AllResources(_) => GasVectorComputationMode::All,
>             },
> ```

Done.

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1771)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/objects.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1771#-OAn37eTC7p1sRMNLwOD:-OAvXXfWAbyLE0u2Ilir:b6kr68m) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb9b8c1f44f51fc247b5de6010fe6439db2d5966/crates/blockifier/src/transaction/objects.rs#L89)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

OK, not sure how it answer my question. I want to know that NoL2Gas is used to represent a V1 tx with fee field instead of the newer resource bounds. Because this `gas_mode` function will return `NoL2Gas` for such txs, and I want to verify it won't be misleading.
</blockquote></details>

\* is **also** used to represent

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1771)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/objects.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1771#-OAn37eTC7p1sRMNLwOD:-OAwOTIP1qNDG7FDSIEv:br5je4x) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb9b8c1f44f51fc247b5de6010fe6439db2d5966/crates/blockifier/src/transaction/objects.rs#L89)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

\* is **also** used to represent
</blockquote></details>

yes, see [here](https://github.com/starkware-libs/sequencer/blob/main/crates/blockifier/src/context.rs#L34-L41).
now that I see it -
please fix this function too!
no need for `match &self.tx_info`, just call `self.tx_info.gas_mode()`

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1771)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/objects.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1771#-OAn37eTC7p1sRMNLwOD:-OB-9Lse-Y5QDRpZqqOT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb9b8c1f44f51fc247b5de6010fe6439db2d5966/crates/blockifier/src/transaction/objects.rs#L89)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes, see [here](https://github.com/starkware-libs/sequencer/blob/main/crates/blockifier/src/context.rs#L34-L41).
now that I see it -
please fix this function too!
no need for `match &self.tx_info`, just call `self.tx_info.gas_mode()`
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1771#-:-OB-qBQuAy0mggbYAZE0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 2 of 5 files at r2, 1 of 1 files at r3, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1771)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
