### PR TITLE
chore(blockifier): share syscall handler's fields

### PR DESCRIPTION
**Pull request by Yoni-Starkware**

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
Prep for syscall code sharing

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2251#-:-OCXDHOl0LDH5g0TJfI2:bymb4w3)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @meship-starkware)

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2251)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2251#-OCXgqJK4SITxAs7jvlH:-OCXgqJK4SITxAs7jvlI:b-sna47t):*
even though this is a refactor, it would have been better to split this PR. I should have asked you to split before I started reviewing



_Code quote:_
```
- b0ee29f: chore(blockifier): share syscall handler's fields
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2251#-OCXeHsZ6Ll2iUbASk1N:-OCXeHsZ6Ll2iUbASk1O:bqfrbtv) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0ee29f63b589782d565634874b8a8e3ee6414f6/crates/blockifier/src/execution/syscalls/syscall_base.rs#L36)):*
> ```XML
>     // Additional information gathered during execution.
>     pub read_values: Vec<Felt>,
>     pub accessed_keys: HashSet<StorageKey, RandomState>,
> ```

why does this have a different type than in `SyscallHintProcessor`?



_Code quote:_
```XML
pub accessed_keys: HashSet<StorageKey, RandomState>,
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2251#-OCXZ-TlBtNbP-BL8KBe:-OCXZ-TlBtNbP-BL8KBf:bhyag9e) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0ee29f63b589782d565634874b8a8e3ee6414f6/crates/blockifier/src/execution/syscalls/syscall_base.rs#L43)):*
> ```XML
>     // The original storage value of the executed contract.
>     // Should be moved back `context.revert_info` before executing an inner call.
>     pub original_values: HashMap<StorageKey, Felt>,
> ```

`NativeSyscallHandler` didn't have this, right, as far as I can see - is this because revert in native is only implemented now?



_Code quote:_
```XML
pub original_values: HashMap<StorageKey, Felt>,
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2251#-OCXZiaO0fS3udhBTere:-OCXZiaO0fS3udhBTerf:b-qpm56q) ([raw file](https://github.com/starkware-libs/sequencer/blob/29f5d16a68c73a2bc9e4bcf819893c4e65ed3447/crates/blockifier/src/execution/native/syscall_handler.rs#L60)):*
> ```XML
> };
> use crate::execution::syscalls::{exceeds_event_size_limit, syscall_base};
> use crate::state::state_api::State;
> ```

why does this have to stay here instead of moving to base?



_Code quote:_
```XML
pub unrecoverable_error: Option<SyscallExecutionError>,
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2251#-OCX_0-g5jpV8KeQ1j23:-OCX_0-g5jpV8KeQ1j24:b-hzp0wa) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0ee29f63b589782d565634874b8a8e3ee6414f6/crates/blockifier/src/execution/native/syscall_handler.rs#L70)):*
> ```XML
>     ) -> NativeSyscallHandler<'state> {
>         NativeSyscallHandler {
>             base: syscall_base::SyscallHandlerBase::new(call, state, context),
> ```

why not import `SyscallHandlerBase` instead of using `syscall_base::`?
non blocking



_Code quote:_
```XML
base: syscall_base::SyscallHandlerBase::new(call, state, context),
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2251)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @meship-starkware)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2251#-OCXZiaO0fS3udhBTere:-OCXlDuO2GtWJDDtC5Bo:b-ie7je4) ([raw file](https://github.com/starkware-libs/sequencer/blob/29f5d16a68c73a2bc9e4bcf819893c4e65ed3447/crates/blockifier/src/execution/native/syscall_handler.rs#L60)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

why does this have to stay here instead of moving to base?
</blockquote></details>

Native cannot return rust errors. The VM can. 
We are handling this by keeping this field. It might be a good idea to share this behaviour with the VM, but not now - it is still under dev (in particular, we need to make the stack traces compatible with the VM's)
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2251#-OCX_0-g5jpV8KeQ1j23:-OCXlcrRBhEdO2MxjRUh:bopkugr) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0ee29f63b589782d565634874b8a8e3ee6414f6/crates/blockifier/src/execution/native/syscall_handler.rs#L70)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

why not import `SyscallHandlerBase` instead of using `syscall_base::`?
non blocking
</blockquote></details>

Leftovers of the prev design (bundle of functions instead of a shared impl)
I'm removing this in a future PR in the stack
___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2251#-OCXkBpC9fYvLHqXMt46:-OCXkGEo-K1pLpmFta-N:bv3anm) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0ee29f63b589782d565634874b8a8e3ee6414f6/crates/blockifier/src/execution/syscalls/syscall_base.rs#L23)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Are there any methods which can move here?
</blockquote></details>

Sure, next PRs
___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2251#-OCXeHsZ6Ll2iUbASk1N:-OCXkw0t77B6hnwt976E:b-mrdsfq) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0ee29f63b589782d565634874b8a8e3ee6414f6/crates/blockifier/src/execution/syscalls/syscall_base.rs#L36)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

why does this have a different type than in `SyscallHintProcessor`?
</blockquote></details>

IDK why native did that explicitly. Maybe for safety. You can see that this is the default state for hash sets:
```
pub struct HashSet<T, S = RandomState>
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2251#-OCXZ-TlBtNbP-BL8KBe:-OCXl5xMARItOGdm-I3L:b-81la7d) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0ee29f63b589782d565634874b8a8e3ee6414f6/crates/blockifier/src/execution/syscalls/syscall_base.rs#L43)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

`NativeSyscallHandler` didn't have this, right, as far as I can see - is this because revert in native is only implemented now?
</blockquote></details>

Right

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2251)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2251#-OCXeHsZ6Ll2iUbASk1N:-OCXpc7_6_fk2OZMLAiZ:b-yh9hm) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0ee29f63b589782d565634874b8a8e3ee6414f6/crates/blockifier/src/execution/syscalls/syscall_base.rs#L36)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

IDK why native did that explicitly. Maybe for safety. You can see that this is the default state for hash sets:
```
pub struct HashSet<T, S = RandomState>
```
</blockquote></details>

The default `RandomState` is different:
https://doc.rust-lang.org/std/collections/hash_map/struct.RandomState.html
please check why it needs it be different / if it's ok that `SyscallHintProcessor` will now also use this type.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2251)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @meship-starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2251#-OCXeHsZ6Ll2iUbASk1N:-OCXx7OSCcUL57ltqBk1:bilxlx5) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0ee29f63b589782d565634874b8a8e3ee6414f6/crates/blockifier/src/execution/syscalls/syscall_base.rs#L36)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

The default `RandomState` is different:
https://doc.rust-lang.org/std/collections/hash_map/struct.RandomState.html
please check why it needs it be different / if it's ok that `SyscallHintProcessor` will now also use this type.
</blockquote></details>

It's the same struct - I checked

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2251)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @meship-starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_base.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2251#-OCXeHsZ6Ll2iUbASk1N:-OCXxj1UB9RDcZnGioi9:b-nlpooo) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0ee29f63b589782d565634874b8a8e3ee6414f6/crates/blockifier/src/execution/syscalls/syscall_base.rs#L36)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

It's the same struct - I checked
</blockquote></details>

It's not needed. I'll remove it in the next PR

**Review by amosStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2251)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @meship-starkware, and @Yoni-Starkware)

**Pull request merged**
