### PR TITLE
feat(blockifier): add replace_class cairo native syscall

### PR DESCRIPTION
**Pull request by PearsonWhite**
Implements the`replace_class` syscall for native cairo syscall handler.

### CODE REVIEW

**Review by varex83 — CHANGES_REQUESTED** [review]
Please, rebase / change target branch to https://github.com/starkware-libs/sequencer/pull/1305

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1551#-:-OAHwBQyEirRhw0kImou:bpi6ygz)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @PearsonWhite)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 180 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1551#-OAHwMa54gL9UWOByPLu:-OAHwMa6DpqG97WdzqYD:b-8ovpps) ([raw file](https://github.com/starkware-libs/sequencer/blob/74a67fe29834de5b8aed02d6963ce3dc435a9b9b/crates/blockifier/src/execution/native/syscall_handler.rs#L180)):*
> ```XML
>             .state
>             .get_compiled_contract_class(class_hash)
>             .expect("Failed to get ContractClass from class hash: {class_hash}.");
> ```

Please, be consistent with VM implementation, return the runtime error here, not panic
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 186 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1551#-OAHwZ1x8DlSwAPBU8ni:-OAHwZ1x8DlSwAPBU8nj:b-gm8kah) ([raw file](https://github.com/starkware-libs/sequencer/blob/74a67fe29834de5b8aed02d6963ce3dc435a9b9b/crates/blockifier/src/execution/native/syscall_handler.rs#L186)):*
> ```XML
>                 let err =
>                     &SyscallExecutionError::ForbiddenClassReplacement { class_hash }.to_string();
>                 panic!("{err:?}");
> ```

Don't use panic here
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 191 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1551#-OAHwaBr7LIKq58bPDPB:-OAHwaBr7LIKq58bPDPC:bkkjs1q) ([raw file](https://github.com/starkware-libs/sequencer/blob/74a67fe29834de5b8aed02d6963ce3dc435a9b9b/crates/blockifier/src/execution/native/syscall_handler.rs#L191)):*
> ```XML
>                 self.state
>                     .set_class_hash_at(self.contract_address, class_hash)
>                     .expect("Failed to set class hash for class hash: {class_hash}.");
> ```

And here

**Review by PearsonWhite — COMMENTED** [review]
I rebased it onto `rdr/add-syscall-counting` because it doesn't depend on `rdr/native-storage-read`.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1551#-:-OAJRe9d6cGglDg6NiIA:bph9k3k)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @varex83)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 180 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1551#-OAHwMa54gL9UWOByPLu:-OAJmbn_7tDWBvHENhuJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/74a67fe29834de5b8aed02d6963ce3dc435a9b9b/crates/blockifier/src/execution/native/syscall_handler.rs#L180)):*
<details><summary><i>Previously, varex83 (Bohdan Ohorodnii) wrote…</i></summary><blockquote>

Please, be consistent with VM implementation, return the runtime error here, not panic
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 186 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1551#-OAHwZ1x8DlSwAPBU8ni:-OAJmeVK4QRDME6oEgy9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/74a67fe29834de5b8aed02d6963ce3dc435a9b9b/crates/blockifier/src/execution/native/syscall_handler.rs#L186)):*
<details><summary><i>Previously, varex83 (Bohdan Ohorodnii) wrote…</i></summary><blockquote>

Don't use panic here
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 191 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1551#-OAHwaBr7LIKq58bPDPB:-OAJmesF-NN7Sr9xqVQG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/74a67fe29834de5b8aed02d6963ce3dc435a9b9b/crates/blockifier/src/execution/native/syscall_handler.rs#L191)):*
<details><summary><i>Previously, varex83 (Bohdan Ohorodnii) wrote…</i></summary><blockquote>

And here
</blockquote></details>

Done.

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r4, 5 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1551)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @varex83)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1551)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @varex83)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1551)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @varex83)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1551)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by avi-starkware — APPROVED** [review]
> Reviewed 2 of 6 files at r5, 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1551)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1551)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1551)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 4 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1551)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1551)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @noaov1, @PearsonWhite, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/replace_class.rs` line 60 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/1551#-OBt00O5AJgiuEOHEBby:-OBt00O5AJgiuEOHEBbz:bru638j) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a2e74288ac48a05aa855bd8c0352bc3f8ecedcc/crates/blockifier/src/execution/syscalls/syscall_tests/replace_class.rs#L60)):*
> ```XML
> #[cfg_attr(
>     feature = "cairo_native",
>     test_case(FeatureContract::TestContract(CairoVersion::Native), 13850; "Native")
> ```

The previous gas price was the right price. I believe it will be fixed after the update.



_Code quote:_
```XML
test_case(FeatureContract::TestContract(CairoVersion::Native), 13850; "Native")
```

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1551)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1, @PearsonWhite, and @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1551#-:-OBt5qEdBqo8HRvX1XZQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @PearsonWhite)

**Pull request merged**
