### PR TITLE
feat(native_blockifier): make cairo_native a feature of native blockifier

### PR DESCRIPTION
**Pull request by dorimedini-starkware**

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2625?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2625** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2625?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2625?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2624** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2624?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2625)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`scripts/build_native_blockifier.sh` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2625#-ODkalzDAnobyfQnkdIM:-ODkalzEBi0YeMveqZS4:bvqhq4q) ([raw file](https://github.com/starkware-libs/sequencer/blob/90901bb7ea14be53665c8335df5922372cfdce74/scripts/build_native_blockifier.sh#L19)):*
> ```Shell
>     pypy3.9 -m venv /tmp/venv
>     source /tmp/venv/bin/activate
>     cargo build --release -p native_blockifier --features "cairo_native" || clean
> ```

Do we also want to add it to the ci? I.e., building native blockifier with the cairo_native feature? 



_Code quote:_
```Shell
cargo build --release -p native_blockifier --features "cairo_native" 
```
___
*[`crates/native_blockifier/Cargo.toml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2625#-ODkb86e3AK8o_qZquYC:-ODkb86e3AK8o_qZquYD:b-531i0d) ([raw file](https://github.com/starkware-libs/sequencer/blob/90901bb7ea14be53665c8335df5922372cfdce74/crates/native_blockifier/Cargo.toml#L10)):*
> ```TOML
> 
> [features]
> cairo_native = ["blockifier/cairo_native"]
> ```

Like :)



_Code quote:_
```TOML
cairo_native = ["blockifier/cairo_native"]
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2625)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`scripts/build_native_blockifier.sh` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2625#-ODkalzDAnobyfQnkdIM:-ODkwRbm-agPQB-vBvDZ:b-gdejys) ([raw file](https://github.com/starkware-libs/sequencer/blob/90901bb7ea14be53665c8335df5922372cfdce74/scripts/build_native_blockifier.sh#L19)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do we also want to add it to the ci? I.e., building native blockifier with the cairo_native feature?
</blockquote></details>

this is the script the CI runs for the native blockifier build :)

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2625)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`scripts/build_native_blockifier.sh` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2625#-ODkalzDAnobyfQnkdIM:-ODlIZBWAdlKKj6yAIZt:b-65eirf) ([raw file](https://github.com/starkware-libs/sequencer/blob/301d7977eb43b569e92c0b64d37157e76cfe0bb6/scripts/build_native_blockifier.sh#L19)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is the script the CI runs for the native blockifier build :)
</blockquote></details>

Got it :) What about `cargo test`?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2625)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

___
*[`scripts/build_native_blockifier.sh` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2625#-ODkalzDAnobyfQnkdIM:-OEEe9HS4W32FBqozWRU:bn7hwa7) ([raw file](https://github.com/starkware-libs/sequencer/blob/40d927ecadb60126eb2375e46f58b6f8a1181f61/scripts/build_native_blockifier.sh#L19)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Got it :) What about `cargo test`?
</blockquote></details>

native blockifier test doesn't run with the cairo-native feature but I think that's ok

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2625)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
