### PR TITLE
chore(mempool): add assert_eq_two_queues for mempool content

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/709)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/709)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/transaction_queue.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/709#-O5xejEBBsst1IwHdNps:-O5xejEBBsst1IwHdNpt:bp72dky) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c82cd3d7bc677af411f38dce3c4a7bb6bfb059b/crates/mempool/src/transaction_queue.rs#L20)):*
> ```XML
> #[derive(Debug, Default, Eq, PartialEq)]
> pub struct TransactionQueue {
>     gas_price_threshold: u128,
> ```

Shall I add a TODO to consider updating the mempool content in case of moving the threshold variable to mempool?



_Code quote:_
```XML
gas_price_threshold: u128,
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/709)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/709#-O60CIdHD0sSeGJZUQ6i:-O60CIdIBJAFWnY50Haf:b5jxh4p) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c82cd3d7bc677af411f38dce3c4a7bb6bfb059b/crates/mempool/src/mempool_test.rs#L95)):*
> ```XML
>     }
> 
>     fn _assert_eq_two_queues_content(&self, mempool: &Mempool) {
> ```

WDYT (change across the board)?
 
I'm thinking that the "two" part is an implementation detail, and the emphasis on the number might be puzzling, perhaps all that matters is the fact that these are queues (perhaps tx_queues but that might be obvious)



_Suggestion:_
```XML
    fn _assert_eq_queues_content(&self, mempool: &Mempool) {
```
___
*[`crates/mempool/src/transaction_queue.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/709#-O5xejEBBsst1IwHdNps:-O60DCLE3xIZUyJSEVD8:bpvkkzn) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c82cd3d7bc677af411f38dce3c4a7bb6bfb059b/crates/mempool/src/transaction_queue.rs#L20)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Shall I add a TODO to consider updating the mempool content in case of moving the threshold variable to mempool?
</blockquote></details>

Nah its fin
___
*[`crates/mempool/src/transaction_queue.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/709#-O60D-Pr-A_0v9VsnDpW:-O60D-Pr-A_0v9VsnDpX:b-e3owx) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c82cd3d7bc677af411f38dce3c4a7bb6bfb059b/crates/mempool/src/transaction_queue.rs#L103)):*
> ```XML
>             && self.pending_queue == other.pending_queue
>             && self.address_to_tx == other.address_to_tx
>     }
> ```

Lets add cfg(test) getters for each field, this is a bit too specific.

The assert should be inside the test infra (inside mempoolContent maybe?)



_Code quote:_
```XML
    #[cfg(test)]
    pub fn _compare_two_queues(&self, other: &Self) -> bool {
        self.priority_queue == other.priority_queue
            && self.pending_queue == other.pending_queue
            && self.address_to_tx == other.address_to_tx
    }
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/709)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/709#-O60CIdHD0sSeGJZUQ6i:-O60t5sp7qq7tDtHI_-D:b-s4jr5f) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c82cd3d7bc677af411f38dce3c4a7bb6bfb059b/crates/mempool/src/mempool_test.rs#L95)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

WDYT (change across the board)?
 
I'm thinking that the "two" part is an implementation detail, and the emphasis on the number might be puzzling, perhaps all that matters is the fact that these are queues (perhaps tx_queues but that might be obvious)
</blockquote></details>

According to our offline discussion, we have decided to merge these two asserts. Now we have one assert method that verifies that all the tx queue elements are the same apart from the gas threshold.
Updated.
___
*[`crates/mempool/src/transaction_queue.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/709#-O60D-Pr-A_0v9VsnDpW:-O60t4906UN6-l6Z9Vku:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c82cd3d7bc677af411f38dce3c4a7bb6bfb059b/crates/mempool/src/transaction_queue.rs#L103)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Lets add cfg(test) getters for each field, this is a bit too specific.

The assert should be inside the test infra (inside mempoolContent maybe?)
</blockquote></details>

Done

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/709)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/709#-O6GCvPJ1Gy6C-y_ZQ4J):*
fix commemt
something with `adjust _assert... `

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/709)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/709#-O6GCvPJ1Gy6C-y_ZQ4J):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

fix commemt
something with `adjust _assert... `
</blockquote></details>

Done.

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/709)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

**Review by ayeletstarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/709)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/709)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue.rs` line 150 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/709#-O6LPPiKEbNj67H1vyX_:-O6LPPiKEbNj67H1vyXa:b-taybtu) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a156341262ffecec9bd6d8094e3fe41fbd8fdd5/crates/mempool/src/transaction_queue.rs#L150)):*
> ```XML
>         &self.address_to_tx
>     }
> }
> ```

do these need to have `_` prefix?



_Code quote:_
```XML
    #[cfg(test)]
    pub fn _get_priority_txs(&self) -> Vec<&TransactionReference> {
        self.priority_queue.iter().map(|tx| &tx.0).collect()
    }

    #[cfg(test)]
    pub fn _get_pending_txs(&self) -> Vec<&TransactionReference> {
        self.pending_queue.iter().map(|tx| &tx.0).collect()
    }

    #[cfg(test)]
    pub fn _get_address_to_tx_mapping(&self) -> &HashMap<ContractAddress, TransactionReference> {
        &self.address_to_tx
    }
}
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/709)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue.rs` line 150 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/709#-O6LPPiKEbNj67H1vyX_:-O6LXeuC0ISMfBQSFB6G:b-k0kus9) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a156341262ffecec9bd6d8094e3fe41fbd8fdd5/crates/mempool/src/transaction_queue.rs#L150)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

do these need to have `_` prefix?
</blockquote></details>

You're correct!
It's not needed anymore when I moved the implementation to `assert_eq_transaction_queue_content`.

**Comment by MohammadNassar1** [comment]
Will implement the assert as part of `TransactionQueueContent`.

**Pull request closed without merging**
