### PR TITLE
chore(starknet_api): create a new method for l1 handler using version 0

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2702?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2702** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2702?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2702?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2699** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2699?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2698** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2698?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2702)* status: 0 of 9 files reviewed, all discussions resolved

___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2702#-OETj7ym5KsCcNJmrfFo:-OETj7ynAZq70un_CZ6X:b46huod) ([raw file](https://github.com/starkware-libs/sequencer/blob/83fe5bfcebb6380b6c457f13c34ae448c1701b6d/crates/starknet_client/src/reader/objects/transaction.rs#L163)):*
> ```XML
>         //     l1_handler_tx.entry_point_selector,
>         //     l1_handler_tx.calldata,
>         // )
> ```

intentional?



_Code quote:_
```XML
        // starknet_api::transaction::L1HandlerTransaction::new(
        //     l1_handler_tx.nonce,
        //     l1_handler_tx.contract_address,
        //     l1_handler_tx.entry_point_selector,
        //     l1_handler_tx.calldata,
        // )
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2702)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/starknet_client/src/reader/objects/transaction.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2702#-OETj7ym5KsCcNJmrfFo:-OETmiME4yxTSn198Kq1:b-n4fb1i) ([raw file](https://github.com/starkware-libs/sequencer/blob/83fe5bfcebb6380b6c457f13c34ae448c1701b6d/crates/starknet_client/src/reader/objects/transaction.rs#L163)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

intentional?
</blockquote></details>

No.
Removed.

**Comment by ArniStarkware** [comment]
This PR is odd. The idea is not good. Closing for now.

**Pull request closed without merging**
