### PR TITLE
chore: import in macro body for improved readablity

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1462)

**Comment by ArniStarkware** [comment]
* **#1465** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1465?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1464** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1464?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1463** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1462** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1462?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1462)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dorimedini-starkware, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1462#-O9cWC5JCLKSJuN1Bvlb:-O9cWC5JCLKSJuN1Bvlc:bg51liq) (no related file):*
How come no imports are removed from files that use these macros?

___

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1462)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @elintul, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1462#-O9cWC5JCLKSJuN1Bvlb:-O9cdidi1TiuE_mWB476:b-68omxf) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How come no imports are removed from files that use these macros?
</blockquote></details>

In this PR we do not remove any "imports". In this set of macros the path to the structs was already used in the macro.
The goal of this PR is to make these macros more readable (by using the `use` inside the macro technology).

The goal was to make this less readable lines like this one:
```
 if let cairo_vm::vm::errors::vm_errors::VirtualMachineError::Hint(hint) = $inner_exc {
            if let cairo_vm::vm::errors::hint_errors::HintError::Internal(
                cairo_vm::vm::errors::vm_errors::VirtualMachineError::Other(error),
            ) = &hint.1

```

into 
```
if let VirtualMachineError::Hint(hint) = $inner_exc {
            if let HintError::Internal(VirtualMachineError::Other(error)) = &hint.1

```

___

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1462)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dorimedini-starkware, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1462#-O9cWC5JCLKSJuN1Bvlb:-O9cfAa678zEinZga2c5:bcjhaqo) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

In this PR we do not remove any "imports". In this set of macros the path to the structs was already used in the macro.
The goal of this PR is to make these macros more readable (by using the `use` inside the macro technology).

The goal was to make this less readable lines like this one:
```
 if let cairo_vm::vm::errors::vm_errors::VirtualMachineError::Hint(hint) = $inner_exc {
            if let cairo_vm::vm::errors::hint_errors::HintError::Internal(
                cairo_vm::vm::errors::vm_errors::VirtualMachineError::Other(error),
            ) = &hint.1

```

into 
```
if let VirtualMachineError::Hint(hint) = $inner_exc {
            if let HintError::Internal(VirtualMachineError::Other(error)) = &hint.1

```
</blockquote></details>

Not sure I understand.

___

**Comment by ArniStarkware** [comment]
This PR may cause longer compilation times.

**Pull request closed without merging**
