### PR TITLE
feat: report error when a call is reverted

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1358)

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1358)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/papyrus_rpc/src/v0_8/api/api_impl.rs` line 910 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1358#-O96QLD86zKUQOKJcFBb:-O96QLD946V4hy0vS_A5:bonn69l) ([raw file](https://github.com/starkware-libs/sequencer/blob/70b5782926cff062b2fccc960e9f8febfcb508ce/crates/papyrus_rpc/src/v0_8/api/api_impl.rs#L910)):*
> ```XML
>             return Err(execution_error_to_error_object_owned(ExecutionError::ContractError(
>                 BlockifierError::new(EntryPointExecutionError::ExecutionFailed {
>                     error_data: res.retdata.0,
> ```

Didn't you want to use the nice panic format?



_Code quote:_
```XML
res.retdata.0,
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/papyrus_rpc/src/v0_8/api/api_impl.rs` line 910 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1358#-O96QLD86zKUQOKJcFBb:-O98YxwzCOipmKbuhlzI:bpejge) ([raw file](https://github.com/starkware-libs/sequencer/blob/70b5782926cff062b2fccc960e9f8febfcb508ce/crates/papyrus_rpc/src/v0_8/api/api_impl.rs#L910)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Didn't you want to use the nice panic format?
</blockquote></details>

it is used in the formatting of `EntryPointExecutionError::ExecutionFailed`

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/papyrus_rpc/Cargo.toml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1358#-O98Z2cT8DG4cxWUGnMH:-O98Z2cT8DG4cxWUGnMI:b95v8hb) ([raw file](https://github.com/starkware-libs/sequencer/blob/70b5782926cff062b2fccc960e9f8febfcb508ce/crates/papyrus_rpc/Cargo.toml#L12)):*
> ```TOML
> async-trait.workspace = true
> base64.workspace = true
> blockifier.workspace = true
> ```

not sure this is a good idea, but this was the simplest solution.



_Code quote:_
```TOML
blockifier.workspace = true
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/papyrus_rpc/Cargo.toml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1358#-O98Z2cT8DG4cxWUGnMH:-O98udB7Cl6PS-MQAQr1:b-di0sf9) ([raw file](https://github.com/starkware-libs/sequencer/blob/70b5782926cff062b2fccc960e9f8febfcb508ce/crates/papyrus_rpc/Cargo.toml#L12)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

not sure this is a good idea, but this was the simplest solution.
</blockquote></details>

@dan-starkware Is this dependency ok?

**Comment by dan-starkware** [comment]
*[`crates/papyrus_rpc/Cargo.toml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1358#-O98Z2cT8DG4cxWUGnMH:-O9902bT3pWUKYI8YME-:b-8fh7aw) ([raw file](https://github.com/starkware-libs/sequencer/blob/70b5782926cff062b2fccc960e9f8febfcb508ce/crates/papyrus_rpc/Cargo.toml#L12)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

@dan-starkware Is this dependency ok?
</blockquote></details>

We tried to decouple these by having an execution crate that depends on the blockifier.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1358)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @Yoni-Starkware)

___
*[`crates/papyrus_rpc/Cargo.toml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1358#-O98Z2cT8DG4cxWUGnMH:-O9A7IvR2O45CIH9ugU4:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/70b5782926cff062b2fccc960e9f8febfcb508ce/crates/papyrus_rpc/Cargo.toml#L12)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

We tried to decouple these by having an execution crate that depends on the blockifier.
</blockquote></details>

done

**Pull request merged**
