### PR TITLE
refactor(consensus): add past_round_upons as in the paper

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1204)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1204)* status: all files reviewed, 8 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1204#-O8_mffz0b8rnMsMas7x:-O8_mfg-60moPIITjKZo:b-skvr0c) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e6236d5dbd5d8330448b42700bb1a494a4c4c82/crates/sequencing/papyrus_consensus/src/state_machine.rs#L68)):*
> ```XML
>     awaiting_get_proposal: bool,
>     events_queue: VecDeque<StateMachineEvent>,
>     locked_value: Option<(ProposalContentId, Round)>,
> ```

Please switch the other BlockHash's in this struct to also be ProposalContentId.



_Code quote:_
```XML
    locked_value: Option<(ProposalContentId, Round)>,
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 237 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1204#-O8_WGE34zm-U6CQWNXp:-O8_WGE34zm-U6CQWNXq:b-x5lmlr) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e6236d5dbd5d8330448b42700bb1a494a4c4c82/crates/sequencing/papyrus_consensus/src/state_machine.rs#L237)):*
> ```XML
>         LeaderFn: Fn(Round) -> ValidatorId,
>     {
>         let old = self.proposals.insert(round, (block_hash, None));
> ```

didn't you already add valid_round to Proposal? Why is that not being used here?



_Code quote:_
```XML
None));
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 406 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1204#-O8_WZo6ENzU7MPNCxRI:-O8_WZo78wEH3n7U7y9D:bq268pk) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e6236d5dbd5d8330448b42700bb1a494a4c4c82/crates/sequencing/papyrus_consensus/src/state_machine.rs#L406)):*
> ```XML
>         if round < self.round {
>             return self.past_round_upons(round);
>         }
> ```

I don't think this makes sense here. The call to `past_round_upons` is meant to come as a direct response to an old message. It is a general category of checks. Once we reach `check_precommit_quorum` we are already targeting a  specific check in a specific round.



_Code quote:_
```XML
        if round < self.round {
            return self.past_round_upons(round);
        }
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 495 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1204#-O8_WzKr4-U-uNOJlTkk:-O8_WzKr4-U-uNOJlTkl:bbfpp7j) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e6236d5dbd5d8330448b42700bb1a494a4c4c82/crates/sequencing/papyrus_consensus/src/state_machine.rs#L495)):*
> ```XML
>     }
> 
>     fn upon_reproposal(&mut self) -> VecDeque<StateMachineEvent> {
> ```

add a comment for all the conditions which line it is in the paper. 



_Suggestion:_
```XML
    // LOC 28 in the paper.
    fn upon_reproposal(&mut self) -> VecDeque<StateMachineEvent> {
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 496 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1204#-O8_oqDs1K2Clg27cWM1:-O8_oqDs1K2Clg27cWM2:b-l6ujek) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e6236d5dbd5d8330448b42700bb1a494a4c4c82/crates/sequencing/papyrus_consensus/src/state_machine.rs#L496)):*
> ```XML
> 
>     fn upon_reproposal(&mut self) -> VecDeque<StateMachineEvent> {
>         let mut output = VecDeque::new();
> ```

All the conditions below are just return empty. So let's just make that explicit and only initialize this when we are ready to actually insert something.



_Code quote:_
```XML
        let mut output = VecDeque::new();
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 518 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1204#-O8_l-Z-70WxxK3iYoPJ:-O8_l-Z-70WxxK3iYoPK:bgqrvrl) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e6236d5dbd5d8330448b42700bb1a494a4c4c82/crates/sequencing/papyrus_consensus/src/state_machine.rs#L518)):*
> ```XML
>         if count < &self.quorum {
>             return output;
>         }
> ```

At a theoretical level `leading_vote`, since it is only valid for a single proposal to receive `2f+1` prevotes. I would prefer if we changed this function to use a lookup which is to get the number of prevotes in support of this (v, r). This should be easy, since we designed the maps for this. Something like this.



_Suggestion:_
```XML
        let Some(round_prevotes) = self.prevotes.get(&self.round) else {
            return output;
        };
        let Some(vote_count) = round_prevotes.get(Some(block_hash)) else { return output };
        if count < &self.quorum {
            return output;
        }
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 532 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1204#-O8_loeADAEUuisUTX0P:-O8_loeADAEUuisUTX0Q:b-x0sn5x) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e6236d5dbd5d8330448b42700bb1a494a4c4c82/crates/sequencing/papyrus_consensus/src/state_machine.rs#L532)):*
> ```XML
>         }
>         self.step = Step::Prevote;
>         output
> ```

This is not correct. If `locked_value` is not set in the paper (`lockedRoundp ≤ vr`) they prevote in favor where you (`None`) prevote NIL. 

I suggest the following. I understand that it is a somewhat complex condition, but I believe this makes it very clear how we conform to the paper.



_Suggestion:_
```XML
        let output;
        if block_hash.is_some_and(|v| {
            self.locked_value.is_none()
                || self.locked_value.is_some_and(|(locked_value, locked_round)| {
                    locked_round <= valid_round || locked_value == v
                })
        }) {
            output = VecDeque::from([StateMachineEvent::Prevote(*block_hash, self.round)]);
        } else {
            output = VecDeque::from([StateMachineEvent::Prevote(None, self.round)]);
        }
        
        self.step = Step::Prevote;
        output
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 554 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1204#-O8a788k5hQRzh8A3HwT:-O8a788k5hQRzh8A3HwU:bojo64j) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e6236d5dbd5d8330448b42700bb1a494a4c4c82/crates/sequencing/papyrus_consensus/src/state_machine.rs#L554)):*
> ```XML
>         }
>         output.append(&mut VecDeque::from([StateMachineEvent::Decision(*block_hash, round)]));
>         output
> ```

I prefer to explicitly return empty.



_Suggestion:_
```XML
        let Some((block_hash, count)) = leading_vote(&self.precommits, round) else {
            return VecDeque::new();
        };
        if *count < self.quorum {
            return VecDeque::new();
        }
        let Some(block_hash) = block_hash else {
            return VecDeque::new();
        };
        let Some((proposed_value, _)) = self.proposals.get(&round) else {
            return VecDeque::new();
        };
        if *proposed_value != Some(*block_hash) {
            // If the proposal is None this could be due to an honest error (crash or network). If
            // the proposal is valid, this can be caused by a malicious leader double proposing. We
            // will rely on the sync protocol to catch us up if such a decision is reached.
            error!("Proposal does not match quorum.");
            return VecDeque::new();
        }
        VecDeque::from([StateMachineEvent::Decision(*block_hash, round)])
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1204)* status: all files reviewed, 8 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 237 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1204#-O8_WGE34zm-U6CQWNXp:-O8aBOkS1oBzw7eXWryG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e6236d5dbd5d8330448b42700bb1a494a4c4c82/crates/sequencing/papyrus_consensus/src/state_machine.rs#L237)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

didn't you already add valid_round to Proposal? Why is that not being used here?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 406 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1204#-O8_WZo6ENzU7MPNCxRI:-O8aBcviB_kV0tFpdidY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e6236d5dbd5d8330448b42700bb1a494a4c4c82/crates/sequencing/papyrus_consensus/src/state_machine.rs#L406)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I don't think this makes sense here. The call to `past_round_upons` is meant to come as a direct response to an old message. It is a general category of checks. Once we reach `check_precommit_quorum` we are already targeting a  specific check in a specific round.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 518 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1204#-O8_l-Z-70WxxK3iYoPJ:-O8aT9hg6Q1wBn9j5lrj:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e6236d5dbd5d8330448b42700bb1a494a4c4c82/crates/sequencing/papyrus_consensus/src/state_machine.rs#L518)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

At a theoretical level `leading_vote`, since it is only valid for a single proposal to receive `2f+1` prevotes. I would prefer if we changed this function to use a lookup which is to get the number of prevotes in support of this (v, r). This should be easy, since we designed the maps for this. Something like this.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 532 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1204#-O8_loeADAEUuisUTX0P:-O8aVldP2evFkMoNBtQf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e6236d5dbd5d8330448b42700bb1a494a4c4c82/crates/sequencing/papyrus_consensus/src/state_machine.rs#L532)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This is not correct. If `locked_value` is not set in the paper (`lockedRoundp ≤ vr`) they prevote in favor where you (`None`) prevote NIL. 

I suggest the following. I understand that it is a somewhat complex condition, but I believe this makes it very clear how we conform to the paper.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 554 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1204#-O8a788k5hQRzh8A3HwT:-O8aGm2v9SDI7iD4UYWe:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e6236d5dbd5d8330448b42700bb1a494a4c4c82/crates/sequencing/papyrus_consensus/src/state_machine.rs#L554)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I prefer to explicitly return empty.
</blockquote></details>

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1204)* status: all files reviewed, 4 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 495 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1204#-O8_WzKr4-U-uNOJlTkk:-O8acsBM6fRa-htcshVN:byv661a) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e6236d5dbd5d8330448b42700bb1a494a4c4c82/crates/sequencing/papyrus_consensus/src/state_machine.rs#L495)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

add a comment for all the conditions which line it is in the paper.
</blockquote></details>

above the function not inside of it
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 526 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1204#-O8abdn42HmkRdwqJFab:-O8abdn42HmkRdwqJFac:b3o4z8o) ([raw file](https://github.com/starkware-libs/sequencer/blob/266f32d97b7e9a7b2ed2ee6e2a9144f0e5808067/crates/sequencing/papyrus_consensus/src/state_machine.rs#L526)):*
> ```XML
>         };
> 
>         self.step = Step::Prevote;
> ```

This calls to advance to step which itself will call to check the conditions (which are now checked based on the new step)



_Suggestion:_
```XML
        self.advance_to_step(Step::Prevote);
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 531 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1204#-O8adaas1psm1OdMmiwz:-O8adaas1psm1OdMmix-:big5fih) ([raw file](https://github.com/starkware-libs/sequencer/blob/266f32d97b7e9a7b2ed2ee6e2a9144f0e5808067/crates/sequencing/papyrus_consensus/src/state_machine.rs#L531)):*
> ```XML
> 
>     fn upon_decision(&mut self, round: u32) -> VecDeque<StateMachineEvent> {
>         // LOC 49 in the paper.
> ```

above the fn (make sure to update the other PRs)



_Code quote:_
```XML
        // LOC 49 in the paper.
```

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1204)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1204#-O8_mffz0b8rnMsMas7x:-O8aoj3QCdqQKHRaUl4m:b-bx6azq) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e6236d5dbd5d8330448b42700bb1a494a4c4c82/crates/sequencing/papyrus_consensus/src/state_machine.rs#L68)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Please switch the other BlockHash's in this struct to also be ProposalContentId.
</blockquote></details>

Separate PR

**Pull request merged**
