### PR TITLE
refactor(blockifier): split pre validate test by charge fee

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/994)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/994)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/994#-O7Zanus7Hg54LWb8tln:-O7Zanus7Hg54LWb8tlo:bw27ez4) (no related file):*
why split? lots of code duplication now, no?

___

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/994)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/994#-O7Zanus7Hg54LWb8tln:-O7cKwgN-aVdr1GVY7oJ:b-9peq58) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why split? lots of code duplication now, no?
</blockquote></details>

In the last PR, there is some code duplication in the second scenario. I can move this duplication to a shared source, but it's not too bad IMO to leave it like that.
I don't like long tests, in which the state at the beginning is not necessary for the validations at the end.
It's also possible to split it another way (test for each case?).

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/994)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 385 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/994#-O7d_qsXAmS69M8GE1nQ:-O7d_qsXAmS69M8GE1nR:b-dqu1z7) ([raw file](https://github.com/starkware-libs/sequencer/blob/7531510ab7685cfbc9709628252b259f2df8270c/crates/blockifier/src/transaction/execution_flavors_test.rs#L385)):*
> ```XML
>     // Second scenario: resource bounds greater than balance.
> 
>     // TODO(Ori, 1/2/2024): Write an indicative expect message explaining why the conversion works.
> ```

you can delete this



_Code quote:_
```XML
// TODO(Ori, 1/2/2024): Write an indicative expect message explaining why the conversion works.
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/994#-:-O7deI1_1_9I5j4s6SxF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Comment by yoavGrs** [comment]
### Merge activity

* **Sep 25, 11:35 PM EDT**: @yoavGrs started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/994).

**Pull request merged**
