### PR TITLE
refactor(batcher): change BuildProposalError to GenerateProposalError

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1986?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1951** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1951?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1986** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1986?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1985** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1985?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Yael-Starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1986)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1986#-OBVS-LB2JjvfLb5_8Qy:-OBVS-LB2JjvfLb5_8Qz:bowfv5i) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd634816231c62edcd7a44fb18d5636374a6a736/crates/batcher/src/proposal_manager.rs#L44)):*
> ```XML
> 
> #[derive(Debug, Error)]
> pub enum GenerateProposalError {
> ```

Would you consider validating a proposal as generating a proposal? I would say it's a another word for build.
Maybe Proposal or ProposalManager Error (After the refactor there will hopefully not be a proposal manager, so maybe the first is better).



_Code quote:_
```XML
GenerateProposalError
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1986)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/batcher/src/proposal_manager.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1986#-OBVS-LB2JjvfLb5_8Qy:-OBVUKfmD_DECgXeEYmZ:byl00hd) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd634816231c62edcd7a44fb18d5636374a6a736/crates/batcher/src/proposal_manager.rs#L44)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Would you consider validating a proposal as generating a proposal? I would say it's a another word for build.
Maybe Proposal or ProposalManager Error (After the refactor there will hopefully not be a proposal manager, so maybe the first is better).
</blockquote></details>

I wrote a pretty long comment about it in the next PR let me copy it here :

I think ProposalError is too general since we have GetProposalResultError and StartHeightError.

changed to GenerateProposalError, which is not perfect because it is similar to Build.

I think that the problem with the terminology comes from the api, we have build or validate proposal, while it should have been propose and validate. And then we could have used the word build to describe both.  
wdyt?

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1986)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/batcher/src/proposal_manager.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1986#-OBVS-LB2JjvfLb5_8Qy:-OBW2ceW7El6F83G8LxI:b-hfghm4) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd634816231c62edcd7a44fb18d5636374a6a736/crates/batcher/src/proposal_manager.rs#L44)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Oh, sorry, I hadn't looked at that PR yet.
I agree 100%, I think it should be propose_block and validate_block.
In that case, let's change the error name to Generate for now, and can you please add this renaming task to Monday? Let's also get the team's opinion (first) and then the group on the API name change. Sound good?
</blockquote></details>

Sounds good

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1986#-:-OBZZJUn9wpzJ7iENwvV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1986)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
