### PR TITLE
refactor(node): split run from main, as it will be used by many binaries

### PR DESCRIPTION
**Pull request by matan-starkware**
Also moved build_network_manager function.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/873)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/873?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#874** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/874?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#873** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/873?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#872** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/872?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#871** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/871?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#870** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/870?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#867** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/867?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#865** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/865?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#863** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/863?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#862** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/862?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#861** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/861?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#860** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/860?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/873)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/papyrus_node/src/main.rs` line 523 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/873#-O78xFS04c3oVgnZFazb:-O78xFS04c3oVgnZFazc:bovbqqm) ([raw file](https://github.com/starkware-libs/sequencer/blob/0fbc2729a1f965660a3a5734178786a222fdf3d9/crates/papyrus_node/src/main.rs#L523)):*
> ```XML
> }
> 
> pub async fn run(
> ```

Where is the call to run?



_Code quote:_
```XML
pub async fn run(
```

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/873)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/papyrus_node/src/main.rs` line 523 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/873#-O78xFS04c3oVgnZFazb:-O78xmDj5m46obm97OCm:bdzz0ke) ([raw file](https://github.com/starkware-libs/sequencer/blob/0fbc2729a1f965660a3a5734178786a222fdf3d9/crates/papyrus_node/src/main.rs#L523)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Where is the call to run?
</blockquote></details>

Whoops, that was supposed to be in `fn main`. It's correct in the next PR so must have messed up when splitting the diffs.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/873)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Pull request merged**
