### PR TITLE
feat(blockifier): add get_block_hash cairo native syscall

### PR DESCRIPTION
**Pull request by PearsonWhite**
Implements the `get_block_hash` syscall for native cairo syscall handler.

### CODE REVIEW

**Review by PearsonWhite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: 0 of 6 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-OA4JqeH08mUUurM_k68:-OA4JqeH08mUUurM_k69:bdlwtj7) (no related file):*
I'm looking for more clarification on the expected error return behavior. For errors that are not of the type `SyscallExecutionError::SyscallError`, I'm currently using `.expect(...)`, which causes tests to fail in some syscall PRs. This can be handled in several ways. There is currently a discussion on this topic here: https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96F70GASwm5B06IRKL

___

**Review by varex83 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @PearsonWhite)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 184 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-OAHvGFv8D4cZVd_64EQ:-OAHvGFv8D4cZVd_64ER:b3jnv9c) ([raw file](https://github.com/starkware-libs/sequencer/blob/0c73ea9c63aee212eef530b2cc33e3e36a987040/crates/blockifier/src/execution/native/syscall_handler.rs#L184)):*
> ```XML
>         let block_hash_address =
>             ContractAddress::try_from(Felt::from(constants::BLOCK_HASH_CONTRACT_ADDRESS))
>                 .expect("Failed to convert BLOCK_HASH_ADDRESS to Felt.");
> ```

Don't use expect here, in VM implementation all of that is returned as a runtime error



_Code quote:_
```XML
        let key = StorageKey::try_from(Felt::from(block_number))
            .expect("Failed to get storage key for block: {block_number}.");
        let block_hash_address =
            ContractAddress::try_from(Felt::from(constants::BLOCK_HASH_CONTRACT_ADDRESS))
                .expect("Failed to convert BLOCK_HASH_ADDRESS to Felt.");
```

**Review by varex83 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @PearsonWhite)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 186 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-OAHvPfXCYIjFZI3IQ-i:-OAHvPfY-Fokt0Uhljzj:brmhs4a) ([raw file](https://github.com/starkware-libs/sequencer/blob/0c73ea9c63aee212eef530b2cc33e3e36a987040/crates/blockifier/src/execution/native/syscall_handler.rs#L186)):*
> ```XML
>                 .expect("Failed to convert BLOCK_HASH_ADDRESS to Felt.");
> 
>         let block_hash = self.state.get_storage_at(block_hash_address, key).expect(
> ```

And here as well

**Review by PearsonWhite — COMMENTED** [review]
I rebased it onto `rdr/add-syscall-counting` because it doesn't depend on `rdr/native-storage-read`.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-:-OAJmOEq1XiXSvcFnqbE:bph9k3k)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @varex83)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-OA4JqeH08mUUurM_k68:-OAJmx2AB3nt3JxRpte3:b-k0qj24) (no related file):*
<details><summary><i>Previously, PearsonWhite wrote…</i></summary><blockquote>

I'm looking for more clarification on the expected error return behavior. For errors that are not of the type `SyscallExecutionError::SyscallError`, I'm currently using `.expect(...)`, which causes tests to fail in some syscall PRs. This can be handled in several ways. There is currently a discussion on this topic here: https://reviewable.io/reviews/starkware-libs/sequencer/1305#-O96F70GASwm5B06IRKL
</blockquote></details>

Changed this to return the Errs instead of panicking.

___
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 184 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-OAHvGFv8D4cZVd_64EQ:-OAJmtHt7HbVb_zmUJE7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0c73ea9c63aee212eef530b2cc33e3e36a987040/crates/blockifier/src/execution/native/syscall_handler.rs#L184)):*
<details><summary><i>Previously, varex83 (Bohdan Ohorodnii) wrote…</i></summary><blockquote>

Don't use expect here, in VM implementation all of that is returned as a runtime error
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 186 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-OAHvPfXCYIjFZI3IQ-i:-OAJmtdY0h0JpovBQeFB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0c73ea9c63aee212eef530b2cc33e3e36a987040/crates/blockifier/src/execution/native/syscall_handler.rs#L186)):*
<details><summary><i>Previously, varex83 (Bohdan Ohorodnii) wrote…</i></summary><blockquote>

And here as well
</blockquote></details>

Done.

**Review by PearsonWhite — COMMENTED** [review]
> Dismissed @varex83 from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @meship-starkware and @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 2 of 7 files at r5, 3 of 5 files at r8, 1 of 1 files at r12, 1 of 1 files at r13, 2 of 4 files at r14, 2 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @PearsonWhite)

___
*[`crates/blockifier/src/execution/native/utils.rs` line 31 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-OAr05aD1rxqSrcv3C0S:-OAr05aD1rxqSrcv3C0T:b4omcio) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e0b4faeb4b6fe51b678a18fdbaa9763055e03fa/crates/blockifier/src/execution/native/utils.rs#L31)):*
> ```XML
>     match String::from_utf8(bytes_err) {
>         Ok(s) => s.trim_matches('\0').to_owned(),
>         Err(_) => {
> ```

This shouldn't be part of this PR 
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/get_block_hash.rs` line 143 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-OArDnPiEUErgJE4oXw2:-OArDnPiEUErgJE4oXw3:b-a9pr13) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e0b4faeb4b6fe51b678a18fdbaa9763055e03fa/crates/blockifier/src/execution/syscalls/syscall_tests/get_block_hash.rs#L143)):*
> ```XML
>             "0x426c6f636b206e756d626572206f7574206f662072616e6765 ('Block number out of range')"
>         );
>     };
> ```

I think this looks better, but I don't have a strong opinion about it, so it's not blocking. 



_Suggestion:_
```XML
    
    #[cfg(feature = "cairo_native")]
    let (actual_error_msg, expected_error_msg) =
        if matches!(test_contract, FeatureContract::TestContract(CairoVersion::Native)) {
            (
                call_result.unwrap_err().to_string(),
                "Native execution error: Block number out of range",
            );
        } else {
            (
                format_panic_data(&call_result.unwrap().execution.retdata.0),
                "0x426c6f636b206e756d626572206f7574206f662072616e6765 ('Block number out of \
                 range')",
            )
        };

    #[cfg(not(feature = "cairo_native"))]
    let (actual_error_msg, expected_error_msg) = (
        format_panic_data(&call_result.unwrap().execution.retdata.0),
        "0x426c6f636b206e756d626572206f7574206f662072616e6765 ('Block number out of range')",
    );

    assert_eq!(actual_error_msg, expected_error_msg);
   
```

**Review by PearsonWhite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/get_block_hash.rs` line 143 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-OArDnPiEUErgJE4oXw2:-OAt015M0TNxazAZ-Zz6:b50tlde) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e0b4faeb4b6fe51b678a18fdbaa9763055e03fa/crates/blockifier/src/execution/syscalls/syscall_tests/get_block_hash.rs#L143)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I think this looks better, but I don't have a strong opinion about it, so it's not blocking.
</blockquote></details>

I've done your suggestion. Thanks.
___
*[`crates/blockifier/src/execution/native/utils.rs` line 31 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-OAr05aD1rxqSrcv3C0S:-OAt-vhq6uXMJoNkAp38:bss4a2b) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e0b4faeb4b6fe51b678a18fdbaa9763055e03fa/crates/blockifier/src/execution/native/utils.rs#L31)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

This shouldn't be part of this PR
</blockquote></details>

Removed.

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @noaov1)

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r8, 1 of 3 files at r15, 3 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @PearsonWhite)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 167 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-OB28_aRCpbQTwHfwSxp:-OB28_aRCpbQTwHfwSxq:b-ikeqs4) ([raw file](https://github.com/starkware-libs/sequencer/blob/e786639a78ea0db3aca1a0107080a26447793de4/crates/blockifier/src/execution/native/syscall_handler.rs#L167)):*
> ```XML
>             // `panic` is unreachable in this case, also this is covered by tests so we can safely
>             // unwrap
>             let out_of_range_felt = Felt::from_hex(BLOCK_NUMBER_OUT_OF_RANGE_ERROR).unwrap();
> ```

What do you think?



_Suggestion:_
```XML
            let out_of_range_felt = Felt::from_hex(BLOCK_NUMBER_OUT_OF_RANGE_ERROR)
                .expect("Converting BLOCK_NUMBER_OUT_OF_RANGE_ERROR to Felt should not fail.")
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 178 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-OB28RN0BGz-CCkJo9hd:-OB28RN0BGz-CCkJo9he:b-q6rtka) ([raw file](https://github.com/starkware-libs/sequencer/blob/e786639a78ea0db3aca1a0107080a26447793de4/crates/blockifier/src/execution/native/syscall_handler.rs#L178)):*
> ```XML
>         let key = StorageKey::try_from(Felt::from(block_number))
>             .expect("Failed to get storage key for block: {block_number}.");
>         let block_hash_address =
> ```

same as the name of the const.



_Suggestion:_
```XML
       let block_hash_contract_address =
```

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @PearsonWhite)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @PearsonWhite)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @PearsonWhite)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @PearsonWhite)

**Review by PearsonWhite — COMMENTED** [review]
Changed error mapping from `encode_str_as_felts` to `self.handle_error`.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-:-OBR6w2EChGeW4Rfa9MD:b-czza7f)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 167 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-OB28_aRCpbQTwHfwSxp:-OBR4bYs29oUW4hT-qwb:b6hb71v) ([raw file](https://github.com/starkware-libs/sequencer/blob/e786639a78ea0db3aca1a0107080a26447793de4/crates/blockifier/src/execution/native/syscall_handler.rs#L167)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

What do you think?
</blockquote></details>

Changed to `expect`.
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 178 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-OB28RN0BGz-CCkJo9hd:-OBR4v69E2sRnXYnbHpW:b-a2ujfl) ([raw file](https://github.com/starkware-libs/sequencer/blob/e786639a78ea0db3aca1a0107080a26447793de4/crates/blockifier/src/execution/native/syscall_handler.rs#L178)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

same as the name of the const.
</blockquote></details>

Changed.

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @noaov1, and @PearsonWhite)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 167 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-OB28_aRCpbQTwHfwSxp:-OBVCpNu6iTTm5glP3Cv:bcw91qg) ([raw file](https://github.com/starkware-libs/sequencer/blob/e786639a78ea0db3aca1a0107080a26447793de4/crates/blockifier/src/execution/native/syscall_handler.rs#L167)):*
<details><summary><i>Previously, PearsonWhite wrote…</i></summary><blockquote>

Changed to `expect`.
</blockquote></details>

It changed back to be unwarp. 
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/get_block_hash.rs` line 136 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-OBVnN2u20W6577hcbNu:-OBVnN2v4P6kCho3CsBB:b-lo0hii) ([raw file](https://github.com/starkware-libs/sequencer/blob/c8158596d8d9ea73199224d6dee34b5237fdb814/crates/blockifier/src/execution/syscalls/syscall_tests/get_block_hash.rs#L136)):*
> ```XML
>         };
> 
>     #[cfg(not(feature = "cairo_native"))]
> ```

Why is it no longer needed?



_Code quote:_
```XML
    #[cfg(feature = "cairo_native")]
    let (actual_error_msg, expected_error_msg) =
        if matches!(test_contract, FeatureContract::TestContract(CairoVersion::Native)) {
            (
                call_result.unwrap_err().to_string(),
                "Native execution error: Block number out of range",
            )
        } else {
            (
                format_panic_data(&call_result.unwrap().execution.retdata.0),
                "0x426c6f636b206e756d626572206f7574206f662072616e6765 ('Block number out of \
                 range')",
            )
        };

    #[cfg(not(feature = "cairo_native"))]
```

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @noaov1, and @PearsonWhite)

**Review by meship-starkware — COMMENTED** [review]
> Dismissed @graphite-app[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @noaov1, and @PearsonWhite)

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @noaov1, @PearsonWhite, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/get_block_hash.rs` line 136 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-OBVnN2u20W6577hcbNu:-OB_2vJC-MIdnn5jb_q3:b-4e2sbn) ([raw file](https://github.com/starkware-libs/sequencer/blob/c8158596d8d9ea73199224d6dee34b5237fdb814/crates/blockifier/src/execution/syscalls/syscall_tests/get_block_hash.rs#L136)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why is it no longer needed?
</blockquote></details>

Because with the addition of the non-recoverable error handling, the Native Handler throws the same errors as the VM (it was not the case previously) where everything was encoded to felts

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @noaov1, @PearsonWhite, and @Yoni-Starkware)

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 4 files at r21, 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1, @PearsonWhite, and @Yoni-Starkware)

**Review by avi-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1, @PearsonWhite, and @Yoni-Starkware)

**Review by avi-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1, @PearsonWhite, and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1, @PearsonWhite, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/get_block_hash.rs` line 45 at r24](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-OBszvnf8n1Ceh2E8Hkz:-OBszvnf8n1Ceh2E8Hl-:b-qaw999) ([raw file](https://github.com/starkware-libs/sequencer/blob/6804fb510de3acd3dc1c3cb8dc4c09663518b8ef/crates/blockifier/src/execution/syscalls/syscall_tests/get_block_hash.rs#L45)):*
> ```XML
> #[cfg_attr(
>     feature = "cairo_native",
>     test_case(FeatureContract::TestContract(CairoVersion::Native), 13850; "Native")
> ```

The previous gas price was the right price. I believe it will be fixed after the update.  



_Code quote:_
```XML
test_case(FeatureContract::TestContract(CairoVersion::Native), 13850; "Native")
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r24.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @PearsonWhite)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/get_block_hash.rs` line 124 at r24](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-OBt4MSqELHnJioRen1E:-OBt4MSqELHnJioRen1F:b-pn15pf) ([raw file](https://github.com/starkware-libs/sequencer/blob/6804fb510de3acd3dc1c3cb8dc4c09663518b8ef/crates/blockifier/src/execution/syscalls/syscall_tests/get_block_hash.rs#L124)):*
> ```XML
>         format_panic_data(&call_result.unwrap().execution.retdata.0),
>         "0x426c6f636b206e756d626572206f7574206f662072616e6765 ('Block number out of range')",
>     );
> ```

Please restore the `failed` check



_Suggestion:_
```XML
    let call_info = entry_point_call.execute_directly(&mut state).unwrap();
    assert!(call_info.execution.failed);
    assert_eq!(
        format_panic_data(&call_info.execution.retdata.0),
        "0x426c6f636b206e756d626572206f7574206f662072616e6765 ('Block number out of range')"
    );
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1556#-:-OBtVvFM6hC7NdYXKRyJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
