### PR TITLE
fix: replace impl From<&Path> with an ad-hoc method

### PR DESCRIPTION
**Pull request by tdelabro**
fixes: https://github.com/starkware-libs/blockifier/issues/1756

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/219)

### CODE REVIEW

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/219)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @tdelabro)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/219#-O4dQhnF3RehwTIYZhTi:-O4dQhnF3RehwTIYZhTj:b-hold65) (no related file):*
Please change all the places that use the try from trait of versioned constants to use that new function   

___

**Comment by tdelabro** [comment]
@meship-starkware done

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/219)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tdelabro)

**Review by meship-starkware — APPROVED** [review]
Already done.  

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/219#-:-O7Y09c--3XH4CKS-rcv:b3xnqe7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tdelabro)

**Comment by meship-starkware** [comment]
see: https://reviewable.io/reviews/starkware-libs/sequencer/973

**Pull request closed without merging**
