### PR TITLE
chore: add calculate_sender_address to RPCTransaction

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/295)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/starknet_api/src/rpc_transaction.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/295#-O3SETLjCk6yLfBcHIcQ:-O3SETLjCk6yLfBcHIcR:bhemn9p) ([raw file](https://github.com/starkware-libs/sequencer/blob/e83f397a383b8f3349b4763f31b66a3c996d655a/crates/starknet_api/src/rpc_transaction.rs#L80)):*
> ```XML
>                     ContractAddress::default(),
>                 )
>                 .unwrap()
> ```

Why unwrap? Is it something that can be expected?



_Suggestion:_
```XML
                calculate_contract_address(
                    tx.contract_address_salt,
                    tx.class_hash,
                    &tx.constructor_calldata,
                    ContractAddress::default(),
                )
                .expect("This should not fail. It probably failed because...")
```

**Comment by ArniStarkware** [comment]
*[`crates/starknet_api/src/rpc_transaction.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/295#-O3SETLjCk6yLfBcHIcQ:-O3SEmwO15lmI5Dxwc1q:b-369i04) ([raw file](https://github.com/starkware-libs/sequencer/blob/e83f397a383b8f3349b4763f31b66a3c996d655a/crates/starknet_api/src/rpc_transaction.rs#L80)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Why unwrap? Is it something that can be expected?
</blockquote></details>

Or is it a test util? In that case, it should be marked appropriately.

**Comment by ArniStarkware** [comment]
*[`crates/starknet_api/src/rpc_transaction.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/295#-O3SETLjCk6yLfBcHIcQ:-O3SFDy7Aiy73NmY7QLl:b-rng62a) ([raw file](https://github.com/starkware-libs/sequencer/blob/e83f397a383b8f3349b4763f31b66a3c996d655a/crates/starknet_api/src/rpc_transaction.rs#L80)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Or is it a test util? In that case, it should be marked appropriately.
</blockquote></details>

It seems like it is no longer a test util, as it is used in `crates/gateway/src/utils.rs`.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/295)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry, @giladchase, and @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/295)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)

___
*[`crates/starknet_api/src/rpc_transaction.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/295#-O3SETLjCk6yLfBcHIcQ:-O3SKEOw0Ot7wGPcEDjM:b1x819a) ([raw file](https://github.com/starkware-libs/sequencer/blob/e83f397a383b8f3349b4763f31b66a3c996d655a/crates/starknet_api/src/rpc_transaction.rs#L80)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

It seems like it is no longer a test util, as it is used in `crates/gateway/src/utils.rs`.
</blockquote></details>

you are absolutely right. fixed.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/295)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry, @giladchase, and @Yael-Starkware)

___
*[`crates/gateway/src/errors.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/295#-O3SMJve9f5ySDdC6HD9:-O3SMJvf7jnBXyYEtXhF:b-t8sukf) ([raw file](https://github.com/starkware-libs/sequencer/blob/891e72176bc8bb87bbb3e3194611af6a1df4bb44/crates/gateway/src/errors.rs#L59)):*
> ```XML
>     #[error(transparent)]
>     StarknetApiError(#[from] StarknetApiError),
>     #[error(transparent)]
> ```

This is getting complicated. This is probably the correct solution, but this line does not tell me that we "failed to calculate contract address". 

non-blocking.



_Code quote:_
```XML
    StarknetApiError(#[from] StarknetApiError),
    #[error(transparent)]
```
___
*[`crates/gateway/src/gateway.rs` line 144 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/295#-O3SN3ip1Vwo_52gVyjG:-O3SN3ip1Vwo_52gVyjH:b212jca) ([raw file](https://github.com/starkware-libs/sequencer/blob/891e72176bc8bb87bbb3e3194611af6a1df4bb44/crates/gateway/src/gateway.rs#L144)):*
> ```XML
>         tx: external_tx_to_thin_tx(&tx, tx_hash, sender_address),
>         account: Account { sender_address, ..Default::default() },
>     })
> ```

This PR is out of scope. Can we remove the `sender_address` member of `Account`? It is contained in the `tx`...



_Code quote:_
```XML
    Ok(MempoolInput {
        tx: external_tx_to_thin_tx(&tx, tx_hash, sender_address),
        account: Account { sender_address, ..Default::default() },
    })
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/utils.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/295#-O3SO-8V5C3Ka1_W8Pq3:-O3SO-8V5C3Ka1_W8Pq4:b-pcez4f) ([raw file](https://github.com/starkware-libs/sequencer/blob/891e72176bc8bb87bbb3e3194611af6a1df4bb44/crates/gateway/src/utils.rs#L40)):*
> ```XML
>         tx_hash,
>     }
> }
> ```

I liked it better when the calculation of sender address was inside this function.



_Code quote:_
```XML
pub fn external_tx_to_thin_tx(
    external_tx: &RpcTransaction,
    tx_hash: TransactionHash,
    sender_address: ContractAddress,
) -> ThinTransaction {
    ThinTransaction {
        tip: *external_tx.tip(),
        nonce: *external_tx.nonce(),
        sender_address,
        tx_hash,
    }
}
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/295)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry, @giladchase, and @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 144 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/295#-O3SQ2gm-iX088wfrDKD:-O3SQ2gn2W9Cb_snkapB:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/891e72176bc8bb87bbb3e3194611af6a1df4bb44/crates/gateway/src/gateway.rs#L144)):*
> ```XML
>         tx: external_tx_to_thin_tx(&tx, tx_hash, sender_address),
>         account: Account { sender_address, ..Default::default() },
>     })
> ```





_Suggestion:_
```XML
    let thin_tx = external_tx_to_thin_tx(&tx, tx_hash)?;
    Ok(MempoolInput {
        tx: thin_tx,
        account: Account { sender_address: thin_tx.sender_address, ..Default::default() },
    })
```
___
*[`crates/gateway/src/utils.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/295#-O3SPOet95uVDbWpNEdE:-O3SPOet95uVDbWpNEdF:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/891e72176bc8bb87bbb3e3194611af6a1df4bb44/crates/gateway/src/utils.rs#L40)):*
> ```XML
>         tx_hash,
>     }
> }
> ```





_Suggestion:_
```XML
pub fn external_tx_to_thin_tx(
    external_tx: &RpcTransaction,
    tx_hash: TransactionHash,
) -> Result<ThinTransaction, GatewayError> {
    Ok(ThinTransaction {
        tip: *external_tx.tip(),
        nonce: *external_tx.nonce(),
        sender_address: tx.calculate_sender_address()?,
        tx_hash,
    })
}
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/295)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)

___
*[`crates/gateway/src/errors.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/295#-O3SMJve9f5ySDdC6HD9:-O3SWjpc3ad8K9Mluay9:b-vww1nh) ([raw file](https://github.com/starkware-libs/sequencer/blob/891e72176bc8bb87bbb3e3194611af6a1df4bb44/crates/gateway/src/errors.rs#L59)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This is getting complicated. This is probably the correct solution, but this line does not tell me that we "failed to calculate contract address". 

non-blocking.
</blockquote></details>

This error is only required now for compilation and will be deleted in the following PR since run_validate will return the sender_address.

I think that this is a classic case where separating PRs creates some complications (see also the following responses().
___
*[`crates/gateway/src/gateway.rs` line 144 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/295#-O3SQ2gm-iX088wfrDKD:-O3SWZJ1B6j_dcXQ8hlV:b-juk8f3) ([raw file](https://github.com/starkware-libs/sequencer/blob/891e72176bc8bb87bbb3e3194611af6a1df4bb44/crates/gateway/src/gateway.rs#L144)):*
> ```XML
>         tx: external_tx_to_thin_tx(&tx, tx_hash, sender_address),
>         account: Account { sender_address, ..Default::default() },
>     })
> ```

The sender address will be returned from run_validate anyway, so there is no point in changing this here now.
___
*[`crates/gateway/src/utils.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/295#-O3SO-8V5C3Ka1_W8Pq3:-O3SW8Az80mXsPx9VHJU:b-blv89h) ([raw file](https://github.com/starkware-libs/sequencer/blob/891e72176bc8bb87bbb3e3194611af6a1df4bb44/crates/gateway/src/utils.rs#L40)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I liked it better when the calculation of sender address was inside this function.
</blockquote></details>

The whole point of these 2 PRs is not to compute the contract address multiple times. 
since this is already computed in the run_validate function, this function will return it and give it as input here.
There is no point in adding an error type return value that will be deleted later.
___
*[`crates/gateway/src/utils.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/295#-O3SPOet95uVDbWpNEdE:-O3SX2mvB7i01FFnzKRE:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/891e72176bc8bb87bbb3e3194611af6a1df4bb44/crates/gateway/src/utils.rs#L40)):*
> ```XML
>         tx_hash,
>     }
> }
> ```

same

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 4 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/295)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry and @giladchase)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/295)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry and @giladchase)

**Pull request merged**
