### PR TITLE
fix(consensus): dont fail when stream handler inbound receiver drops

### PR DESCRIPTION
**Pull request by guy-starkware**
In the StreamHandler inbound case (listening to the network and sending internal messages into Consensus) there's a case where the Consensus drops the receiver. 
This is a receiver that the StreamHandler sends whenever it sees a new stream, and the receiver should stay open for as long as that stream is not done. 

However, the Consensus may choose to drop it (e.g., when moving to a new height) and that leaves the StreamHandler with a broken pipe, and also some messages that should go into that pipe. 

As a first step, I'm making this no longer a panic, but if the receiver is dropped, then the sender inside StreamHandler is dropped, too (along with the remaining StreamData, which includes the message id, cached messages, etc). 

This still doesn't address what happens to all the other messages that should come into StreamHandler. I'll handle that in the next PR.

### CODE REVIEW

**Comment by guy-starkware** [comment]
* **#2730** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2730?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2730?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2730)* status: all files reviewed, 5 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 412 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2730#-OEKsxKl3SloWZMVj4Ep:-OEKsxKl3SloWZMVj4Eq:btmygbz) ([raw file](https://github.com/starkware-libs/sequencer/blob/75eaa43f8feb5fc2cc8d7bcc1947d609a9e3fce3/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L412)):*
> ```XML
>         // Allow the StreamHandler to process the messages.
>         let join_handle = tokio::spawn(async move {
>             let _ = tokio::time::timeout(TIMEOUT, stream_handler.run()).await;
> ```

I think often it's better not to have timeouts like this in a test. Normally tests are run with a timeout on the whole test, and so this explicit timeout is just adding complexity to your test code.



_Code quote:_
```XML
            let _ = tokio::time::timeout(TIMEOUT, stream_handler.run()).await;
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 433 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2730#-OEKtKFQ5iasmVHXtIrK:-OEKtKFQ5iasmVHXtIrL:b-cdb4ef) ([raw file](https://github.com/starkware-libs/sequencer/blob/75eaa43f8feb5fc2cc8d7bcc1947d609a9e3fce3/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L433)):*
> ```XML
> 
>         // Send more messages.
>         // TODO(guyn): if we set this to 2..4 it fails... the last message opens a new StreamData!
> ```

this is the follow up "ignore late messages"?



_Code quote:_
```XML
        // TODO(guyn): if we set this to 2..4 it fails... the last message opens a new StreamData!
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2730#-OEKs1G48fg6atRTi4UJ:-OEKs1G48fg6atRTi4UK:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/75eaa43f8feb5fc2cc8d7bcc1947d609a9e3fce3/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L185)):*
> ```XML
>     }
> 
>     fn inbound_send(data: &mut StreamData<T>, message: StreamMessage<T>) -> bool {
> ```





_Suggestion:_
```XML
    // Returns false if the receiver is no longer subscribed to this stream.
    fn inbound_send(data: &mut StreamData<T>, message: StreamMessage<T>) -> bool {
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2730#-OEKsCBe2zjX8sEdqNUc:-OEKsCBfBpsokbNieO4I:bqgmmg7) ([raw file](https://github.com/starkware-libs/sequencer/blob/75eaa43f8feb5fc2cc8d7bcc1947d609a9e3fce3/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L204)):*
> ```XML
>                             "Sender is full, dropping the message. StreamId: {}, MessageId: {}",
>                             message.stream_id, message.message_id
>                         );
> ```

Good catch. I would want this to just stay in the internal buffer for this stream_id (where we keep the out of order messages). I don't see this as an error. That buffer though must be limited in size to prevent OOM



_Code quote:_
```XML
                    } else if e.is_full() {
                        // TODO(guyn): replace panic with more graceful error handling
                        panic!(
                            "Sender is full, dropping the message. StreamId: {}, MessageId: {}",
                            message.stream_id, message.message_id
                        );
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 313 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2730#-OEKsdur6ObQwastQSBX:-OEKsdur6ObQwastQSBY:b-7zi8ni) ([raw file](https://github.com/starkware-libs/sequencer/blob/75eaa43f8feb5fc2cc8d7bcc1947d609a9e3fce3/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L313)):*
> ```XML
>             Ordering::Equal => {
>                 // success will be false if the receiver is closed.
>                 let mut success = Self::inbound_send(data, message);
> ```

WDYT?



_Suggestion:_
```XML
                let mut receiver_unsubscribed = Self::inbound_send(data, message);
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2730)* status: all files reviewed, 5 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2730#-OEKsCBe2zjX8sEdqNUc:-OEL3Iy47ofkMOB9snca:bksmzzn) ([raw file](https://github.com/starkware-libs/sequencer/blob/75eaa43f8feb5fc2cc8d7bcc1947d609a9e3fce3/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L204)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Good catch. I would want this to just stay in the internal buffer for this stream_id (where we keep the out of order messages). I don't see this as an error. That buffer though must be limited in size to prevent OOM
</blockquote></details>

Good idea! 
It looks like this may be a little more complicated because of the way the code is written right now. Could require a bit of a refactor to make this work. 
Also, I'm not sure what happens after we buffer that message. If no other messages come in, that buffer will never get triggered and you may end up with all messages buffered forever. 
I'm putting a TODO on this option and we'll do it on the next PR. 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 313 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2730#-OEKsdur6ObQwastQSBX:-OEL4cva46EHwmfhQM7j:bwwec88) ([raw file](https://github.com/starkware-libs/sequencer/blob/75eaa43f8feb5fc2cc8d7bcc1947d609a9e3fce3/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L313)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

yeah, I was feeling a bit uneasy about "success". I'll take your idea. Maybe "receiver_dropped" is more obvious? Because as far as I can tell, the only way to close the channel from that end is to drop it. 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 412 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2730#-OEKsxKl3SloWZMVj4Ep:-OEL5IEH6GdISGA-7yCA:b-iq7gae) ([raw file](https://github.com/starkware-libs/sequencer/blob/75eaa43f8feb5fc2cc8d7bcc1947d609a9e3fce3/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L412)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I think often it's better not to have timeouts like this in a test. Normally tests are run with a timeout on the whole test, and so this explicit timeout is just adding complexity to your test code.
</blockquote></details>

I don't know how to make the stream handler's `run()` function quit gracefully, so instead I'm using a timeout. This is not "in case things run too long" this is "after messages are consumed, quit the run". 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 433 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2730#-OEKtKFQ5iasmVHXtIrK:-OEL5Wtc5S6RhEMfwdeC:bcw54vt) ([raw file](https://github.com/starkware-libs/sequencer/blob/75eaa43f8feb5fc2cc8d7bcc1947d609a9e3fce3/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L433)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

this is the follow up "ignore late messages"?
</blockquote></details>

Exactly. 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2730#-OEKs1G48fg6atRTi4UJ:-OEL3B_m9z1z4QSurFet:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/75eaa43f8feb5fc2cc8d7bcc1947d609a9e3fce3/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L185)):*
> ```XML
>     }
> 
>     fn inbound_send(data: &mut StreamData<T>, message: StreamMessage<T>) -> bool {
> ```

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2730)* status: all files reviewed, 2 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2730#-OEKsCBe2zjX8sEdqNUc:-OEPFmE0B28FB8isCxwX:b-sr8zia) ([raw file](https://github.com/starkware-libs/sequencer/blob/75eaa43f8feb5fc2cc8d7bcc1947d609a9e3fce3/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L204)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

Good idea! 
It looks like this may be a little more complicated because of the way the code is written right now. Could require a bit of a refactor to make this work. 
Also, I'm not sure what happens after we buffer that message. If no other messages come in, that buffer will never get triggered and you may end up with all messages buffered forever. 
I'm putting a TODO on this option and we'll do it on the next PR.
</blockquote></details>

Yeah I more just mean the TODO should be updated to this instead of triggering an error. We can discuss design later.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 314 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2730#-OEPG1pG0TGnEB_ZG6TJ:-OEPG1pG0TGnEB_ZG6TK:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/691a239cb2900d74b4fe13a98cfe2914caf87ee2/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L314)):*
> ```XML
>             Ordering::Equal => {
>                 // receiver_dropped will be true if the receiver for this stream is dropped.
>                 let mut receiver_dropped = Self::inbound_send(data, message);
> ```





_Suggestion:_
```XML
                let mut receiver_dropped = Self::inbound_send(data, message);
```

**Review by guy-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2730)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Pull request merged**
