### PR TITLE
Dori/Merge main-v0.13.2 into main

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/117)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
[Src](https://github.com/starkware-libs/blockifier/compare/cd3107459a81e77b5888718cc8d82ea9b1a068b7..main-v0.13.2#diff-2b1ae4316086c0ebb213227790133a792300e1cef03b0afc067b23d3399ea5ca) [Dst](https://github.com/starkware-libs/blockifier/compare/cd3107459a81e77b5888718cc8d82ea9b1a068b7..main#diff-2b1ae4316086c0ebb213227790133a792300e1cef03b0afc067b23d3399ea5ca) commitlint.config.js

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 4 of 5 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/117)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/117#-:-O2eGu143TPnFYRLJ9xh:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @dorimedini-starkware)

___
*[`commitlint.config.js` line 38 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/117#-O2eH1SX2qBKVWRa7AXU:-O2eH1SY7SHpfzCpPY8N:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef9cfc0b0e7f10beedfe2e1ea7fd5134cd8d1bc7/commitlint.config.js#L38)):*
> ```JavaScript
>             'mempool_infra',
>             'mempool_node',
>             'mempool',
> ```





_Suggestion:_
```JavaScript
            'mempool',
            'mempool_infra',
            'mempool_node',
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/117)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/117)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
