### PR TITLE
fix(consensus): pass streamed proposal channels when building consensus

### PR DESCRIPTION
**Pull request by asmaastarkware**

### CODE REVIEW

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2829)* status: all files reviewed, 1 unresolved discussion (waiting on @guy-starkware and @matan-starkware)

___
*[`crates/papyrus_node/src/bin/run_consensus.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2829#-OEUMNB63w9FBCxlkFlm:-OEUNT5i4HIDe4hQtPFs:bcbh4x2) ([raw file](https://github.com/starkware-libs/sequencer/blob/d29edd24dc04e2f5db1330a37a5de49bb609a677/crates/papyrus_node/src/bin/run_consensus.rs#L66)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

Please check if the NETWORK_TOPIC is for votes or for proposals. They should be different.
</blockquote></details>

it's for proposals

**Review by guy-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2829)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2829)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/papyrus_node/src/bin/run_consensus.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2829#-OEV6gpS3qaTC6AC6C6Z:-OEV6gpTDrXM9PChNEXM:bfohbb9) ([raw file](https://github.com/starkware-libs/sequencer/blob/d29edd24dc04e2f5db1330a37a5de49bb609a677/crates/papyrus_node/src/bin/run_consensus.rs#L71)):*
> ```XML
>         broadcast_topic_client: outbound_network_sender,
>     } = proposal_network_channels;
>     let (outbound_internal_sender, inbound_internal_receiver, _) =
> ```

You are dropping the handle to the stream handler's task. I don't want that in case there is an error. Please hold onto this and inside of the task that you return from here run this concurrently with `run_consensus` (I guess inside of a select). The cancel safety is a non issue since if either of these return we want the node to abort.



_Code quote:_
```XML
_
```

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2829)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
