### PR TITLE
feat: dependencies.sh script for dev onboarding

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1116)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1116)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alon-dotan-starkware and @noaov1)

___
*[`scripts/dependencies.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1116#-O82h4tj1g3SSdZ7z4j9:-O82h4tkClnOpq8vT-WG:b50k81x) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d100407dca5c56d23c187a2549cd92070bd8bfa/scripts/dependencies.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> sudo -s
> ```

when running this script, sudo context is entered but the apt commands aren't run until I `exit`.
Why?
should every command in this script be prepended with `sudo` explicitly?



_Code quote:_
```Shell
sudo -s
```
___
*[`scripts/dependencies.sh` line 4 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1116#-O82hGIm1n9NaPYlnkZN:-O82hGIm1n9NaPYlnkZO:bc5i7wk) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d100407dca5c56d23c187a2549cd92070bd8bfa/scripts/dependencies.sh#L4)):*
> ```Shell
> 
> sudo -s
> pushd /tmp
> ```

instead of `cd`, + `popd` added at the end



_Code quote:_
```Shell
pushd /tmp
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1116)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alon-dotan-starkware and @noaov1)

___
*[`scripts/dependencies.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1116#-O82h4tj1g3SSdZ7z4j9:-O82iW6s169I8x2VWqaK:b-pp7guh) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d100407dca5c56d23c187a2549cd92070bd8bfa/scripts/dependencies.sh#L3)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

when running this script, sudo context is entered but the apt commands aren't run until I `exit`.
Why?
should every command in this script be prepended with `sudo` explicitly?
</blockquote></details>

explicit `sudo`s seem to work

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1116)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`scripts/dependencies.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1116#-O82h4tj1g3SSdZ7z4j9:-O82mHvc3SZcP_oZw6xp:b-ngq6qp) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d100407dca5c56d23c187a2549cd92070bd8bfa/scripts/dependencies.sh#L3)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

explicit `sudo`s seem to work
</blockquote></details>

Its duplicate code... Just import the function

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1116)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`scripts/dependencies.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1116#-O82h4tj1g3SSdZ7z4j9:-O82u-xn0BtUN23UiAqB:bfns4b4) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d100407dca5c56d23c187a2549cd92070bd8bfa/scripts/dependencies.sh#L3)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

Its duplicate code... Just import the function
</blockquote></details>

hmmm... what would be the difference between this script and setup_native_deps.sh?
should we just rename setup_native_deps to dependencies, or should we decouple these scripts?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1116)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`scripts/dependencies.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1116#-O82h4tj1g3SSdZ7z4j9:-O82uqpo0vE8W9t6Rxna:bbmt0d9) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d100407dca5c56d23c187a2549cd92070bd8bfa/scripts/dependencies.sh#L3)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

hmmm... what would be the difference between this script and setup_native_deps.sh?
should we just rename setup_native_deps to dependencies, or should we decouple these scripts?
</blockquote></details>

if we want to keep the scripts separate... which invocations of `setup_native_deps` should actually invoke `dependencies`?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1116)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`scripts/dependencies.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1116#-O82h4tj1g3SSdZ7z4j9:-O83uDhO-PRskGFLbvhU:b-n44paf) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d100407dca5c56d23c187a2549cd92070bd8bfa/scripts/dependencies.sh#L3)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if we want to keep the scripts separate... which invocations of `setup_native_deps` should actually invoke `dependencies`?
</blockquote></details>

We can add the protobuf deps in here

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1116)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`scripts/dependencies.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1116#-O82h4tj1g3SSdZ7z4j9:-O85ePGt3fXyJ2Z-31MP:b-1d04yw) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d100407dca5c56d23c187a2549cd92070bd8bfa/scripts/dependencies.sh#L3)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

We can add the protobuf deps in here
</blockquote></details>

@Yoni-Starkware will do that in a future PR after this is merged

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1116)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`scripts/dependencies.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1116#-O82h4tj1g3SSdZ7z4j9:-O85wR064TNXs3pqHGsr:bdm3mmh) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d100407dca5c56d23c187a2549cd92070bd8bfa/scripts/dependencies.sh#L3)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

*I will
</blockquote></details>

when someone LGTMs I'll merge :)

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1116)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`scripts/dependencies.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1116#-O82h4tj1g3SSdZ7z4j9:-O85x3ke-GCbEIhYlTq9:bne12ss) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d100407dca5c56d23c187a2549cd92070bd8bfa/scripts/dependencies.sh#L3)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

when someone LGTMs I'll merge :)
</blockquote></details>

can we NOT!! pust protobuf here and add it to the build.rs?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1116)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`Dockerfile` line 14 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1116#-O860tb88GdE8Z7Y31fB:-O860tb88GdE8Z7Y31fC:bhaeyub) ([raw file](https://github.com/starkware-libs/sequencer/blob/d8b79c6fb0d3be3d09c5ac6d68bc427b4ce834b1/Dockerfile#L14)):*
> ```Dockerfile
> 
> COPY scripts/install_build_tools.sh .
> COPY scripts/dependencies.sh .
> ```

you will still need `setup_native_deps`, this script is just a wrapper



_Code quote:_
```Dockerfile
COPY scripts/dependencies.sh .
```
___
*[`.github/workflows/blockifier_ci.yml` line 32 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1116#-O860yfe5shymD3Vu6bA:-O860yfe5shymD3Vu6bB:b-r4uplb) ([raw file](https://github.com/starkware-libs/sequencer/blob/d8b79c6fb0d3be3d09c5ac6d68bc427b4ce834b1/.github/workflows/blockifier_ci.yml#L32)):*
> ```YAML
>       - 'crates/native_blockifier/**'
>       - 'scripts/build_native_blockifier.sh'
>       - 'scripts/dependencies.sh'
> ```

if this job needs triggering on change to dev setup script, then it needs triggering when setup_native_deps is edited, right?

same comment for all CI workflows in this PR where you added dependencies.sh to the triggers



_Code quote:_
```YAML
'scripts/dependencies.sh'
```

**Review by dorimedini-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1116#-:-O8632ajDDOdcnvbVRcg:bnfp4nl)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @noaov1)

**Review by alon-dotan-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1116)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @noaov1)

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1116#-:-O86378Q2NLKLj_N1hut:bnfp4nl)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @noaov1)

**Review by alon-dotan-starkware — APPROVED** [review]
> Reviewed 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1116)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
