### PR TITLE
chore(mempool): add two queues option for mempool content

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/708)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/708)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/708#-O60B6QT38zeuJ-rRkz4:-O60B6QT38zeuJ-rRkz5:b-koyz4t) ([raw file](https://github.com/starkware-libs/sequencer/blob/51cec71d75a209808fe47b11b02531ff873f431e/crates/mempool/src/transaction_queue.rs#L25)):*
> ```XML
> impl TransactionQueue {
>     #[cfg(test)]
>     pub fn _new_with_transactions(
> ```

Move to the end of the impl block.
Order of items is by importance: pub, then private, and finally conditionally compiled stuff (internally ordered by pub/private).



_Code quote:_
```XML
    #[cfg(test)]
    pub fn _new_with_transactions(
```
___
*[`crates/mempool/src/transaction_queue.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/708#-O60BWjzCYPZnSZO_EKv:-O60BWjzCYPZnSZO_EKw:brbec8b) ([raw file](https://github.com/starkware-libs/sequencer/blob/51cec71d75a209808fe47b11b02531ff873f431e/crates/mempool/src/transaction_queue.rs#L27)):*
> ```XML
>     pub fn _new_with_transactions(
>         priority_queue: Vec<TransactionReference>,
>         pending_queue: Vec<TransactionReference>,
> ```

Looks like both of these can be IntoIterators, unless you have other usages in mind.



_Code quote:_
```XML
        priority_queue: Vec<TransactionReference>,
        pending_queue: Vec<TransactionReference>,
```
___
*[`crates/mempool/src/transaction_queue.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/708#-O60BpQZ3uaSwgM4W9UW:-O60BpQZ3uaSwgM4W9UX:bwafyrr) ([raw file](https://github.com/starkware-libs/sequencer/blob/51cec71d75a209808fe47b11b02531ff873f431e/crates/mempool/src/transaction_queue.rs#L27)):*
> ```XML
>     pub fn _new_with_transactions(
>         priority_queue: Vec<TransactionReference>,
>         pending_queue: Vec<TransactionReference>,
> ```

Names need to be changed, vector != queue



_Code quote:_
```XML
        priority_queue: Vec<TransactionReference>,
        pending_queue: Vec<TransactionReference>,
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/708)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/transaction_queue.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/708#-O60B6QT38zeuJ-rRkz4:-O60uWzVEwQtmOTYVxsG:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/51cec71d75a209808fe47b11b02531ff873f431e/crates/mempool/src/transaction_queue.rs#L25)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Move to the end of the impl block.
Order of items is by importance: pub, then private, and finally conditionally compiled stuff (internally ordered by pub/private).
</blockquote></details>

Done
___
*[`crates/mempool/src/transaction_queue.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/708#-O60BpQZ3uaSwgM4W9UW:-O611IoaE5_TS5EDP-vB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/51cec71d75a209808fe47b11b02531ff873f431e/crates/mempool/src/transaction_queue.rs#L27)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Names need to be changed, vector != queue
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_queue.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/708#-O60BWjzCYPZnSZO_EKv:-O616fijAPS14Nld2C4C:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/51cec71d75a209808fe47b11b02531ff873f431e/crates/mempool/src/transaction_queue.rs#L27)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Looks like both of these can be IntoIterators, unless you have other usages in mind.
</blockquote></details>

Done.

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/708)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/708#-O6GIrGxEUTY6xUOoFV2:-O6GIrGxEUTY6xUOoFV3:bgygxwl) ([raw file](https://github.com/starkware-libs/sequencer/blob/5da12583cd557ca4888f7f60fc728d73b62354e2/crates/mempool/src/mempool_test.rs#L75)):*
> ```XML
>     }
> 
>     fn _with_inner_transaction_queues<Q>(priority_txs: Q, pending_txs: Q) -> Self
> ```

How does that differ from using `with_queue` combined with `impl FromIterator<TransactionReference> for TransactionQueue`? Also, why do we need two implementations for asserting queues?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/708)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/708#-O6GIrGxEUTY6xUOoFV2:-O6Go5GG-u1-UORTuzdr:b-cbp0qr) ([raw file](https://github.com/starkware-libs/sequencer/blob/5da12583cd557ca4888f7f60fc728d73b62354e2/crates/mempool/src/mempool_test.rs#L75)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

How does that differ from using `with_queue` combined with `impl FromIterator<TransactionReference> for TransactionQueue`? Also, why do we need two implementations for asserting queues?
</blockquote></details>

Good question!
The `with_queue` function does not distinguish between the two inner queues. It initializes the mempool with transactions from the transaction queue, but doesn't account for which specific inner queue they belong to.

In contrast, the `with_inner_transaction_queue` function initializes the mempool with transactions from the inner queues without using the `insert` method.

This method is intended for use in tests involving two queues, where it's important to verify which inner queue the transactions are located in.

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/708)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/708#-O6GIrGxEUTY6xUOoFV2:-O6GvEN35wZZ_iIJEA5y:bghvb55) ([raw file](https://github.com/starkware-libs/sequencer/blob/5da12583cd557ca4888f7f60fc728d73b62354e2/crates/mempool/src/mempool_test.rs#L75)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Good question!
The `with_queue` function does not distinguish between the two inner queues. It initializes the mempool with transactions from the transaction queue, but doesn't account for which specific inner queue they belong to.

In contrast, the `with_inner_transaction_queue` function initializes the mempool with transactions from the inner queues without using the `insert` method.

This method is intended for use in tests involving two queues, where it's important to verify which inner queue the transactions are located in.
</blockquote></details>

what would happen if you use this function in all tests using `with_queue`?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/708)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/708#-O6GIrGxEUTY6xUOoFV2:-O6Gxqx5ERiIljFJ0f9O:b-y5mkmo) ([raw file](https://github.com/starkware-libs/sequencer/blob/5da12583cd557ca4888f7f60fc728d73b62354e2/crates/mempool/src/mempool_test.rs#L75)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

what would happen if you use this function in all tests using `with_queue`?
</blockquote></details>

We couldn't verify which inner queue a specific tx is located in.

For example, in "add tx test," we aim to include a transaction with a gas price lower than the threshold. In this test, our goal is to confirm that the transaction is in the pending queue.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/708)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/708#-O6GIrGxEUTY6xUOoFV2:-O6H46H99BYwrUJ7akt2:b-xpugew) ([raw file](https://github.com/starkware-libs/sequencer/blob/5da12583cd557ca4888f7f60fc728d73b62354e2/crates/mempool/src/mempool_test.rs#L75)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

We couldn't verify which inner queue a specific tx is located in.

For example, in "add tx test," we aim to include a transaction with a gas price lower than the threshold. In this test, our goal is to confirm that the transaction is in the pending queue.
</blockquote></details>

I think having both `with_queue` and `_with_inner_transaction_queues` could be confusing. 
Tests currently using `with_queue` wouldn’t be affected if the inner queues were checked as well. 
It think it would be better to create a single `with` function that handles all queue scenarios and update all relevant tests accordingly (in a separate PR).

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/708)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/708#-O6GIrGxEUTY6xUOoFV2:-O6H5-Tf0HP4MCxH2WP1:b-dmj92a) ([raw file](https://github.com/starkware-libs/sequencer/blob/5da12583cd557ca4888f7f60fc728d73b62354e2/crates/mempool/src/mempool_test.rs#L75)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I think having both `with_queue` and `_with_inner_transaction_queues` could be confusing. 
Tests currently using `with_queue` wouldn’t be affected if the inner queues were checked as well. 
It think it would be better to create a single `with` function that handles all queue scenarios and update all relevant tests accordingly (in a separate PR).
</blockquote></details>

Got your point.
You mean that all the tests should be aware of the inner queues.
@giladchase and @elintul, what do you think of Ayelet's suggestion?

Anyway, this can be done in a separate PR.

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/708)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/708#-O6HAiig2aAn9CMlG_-6:-O6HAiig2aAn9CMlG_-7:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/5da12583cd557ca4888f7f60fc728d73b62354e2/crates/mempool/src/transaction_queue.rs#L137)):*
> ```XML
> 
>     #[cfg(test)]
>     pub fn _new_with_transactions<Q>(priority_txs: Q, pending_txs: Q) -> Self
> ```





_Suggestion:_
```XML
_new_with_priority_and_pending_transactions
```

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/708)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/708)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/708#-O6GIrGxEUTY6xUOoFV2:-O6LL184-t3_TNfu5j-N:b53ocu9) ([raw file](https://github.com/starkware-libs/sequencer/blob/5da12583cd557ca4888f7f60fc728d73b62354e2/crates/mempool/src/mempool_test.rs#L75)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Got your point.
You mean that all the tests should be aware of the inner queues.
@giladchase and @elintul, what do you think of Ayelet's suggestion?

Anyway, this can be done in a separate PR.
</blockquote></details>

I agree with ayelet, `with_queue` is too ambiguous.
IIUC it should be something like "with priority_queue" depending on how we call that queue.

This is getting a bit messy now, in the future we'll use a full builder pattern which will allow us to chain`with_X` and `with_Y` instead of having `with_X_and_Y`combinations, which is messy.
___
*[`crates/mempool/src/transaction_queue.rs` line 155 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/708#-O6LOCQW3IIVsdJ2hIpP:-O6LOCQW3IIVsdJ2hIpQ:b-79uoja) ([raw file](https://github.com/starkware-libs/sequencer/blob/10029a726568badb7889e5ecc89caaaccfe9f64c/crates/mempool/src/transaction_queue.rs#L155)):*
> ```XML
> 
>         Self { priority_queue, pending_queue, address_to_tx, ..Default::default() }
>     }
> ```

Didn't we decide on using getters here and moving this to the test util?



_Code quote:_
```XML
    #[cfg(test)]
    pub fn _new_with_priority_and_pending_transactions<Q>(priority_txs: Q, pending_txs: Q) -> Self
    where
        Q: IntoIterator<Item = TransactionReference>,
    {
        let priority_queue: BTreeSet<PriorityTransaction> =
            priority_txs.into_iter().map(Into::into).collect();

        let pending_queue: BTreeSet<PendingTransaction> =
            pending_txs.into_iter().map(Into::into).collect();

        let address_to_tx: HashMap<ContractAddress, TransactionReference> = priority_queue
            .iter()
            .map(|tx| tx.clone().0)
            .chain(pending_queue.iter().map(|tx| tx.clone().0))
            .map(|tx| (tx.sender_address, tx))
            .collect();

        Self { priority_queue, pending_queue, address_to_tx, ..Default::default() }
    }
```

**Comment by MohammadNassar1** [comment]
Create `TrasnactionQueueContent` instead of new for testing method.

**Pull request closed without merging**
