### PR TITLE
chore: wrap cairo lang version id for code dedup

### PR DESCRIPTION
**Pull request by ArniStarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

There is code duplication between Cairo-Lang's version ID and the gateway's version ID.

## What is the new behavior?

- Refactor the Gateway's version ID as a wrapper.

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/83)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#84** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/84?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#83** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/83?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by yair-starkware** [comment]
Why don't we use the type directly from Cairo?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/83)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/83#-O2sLztQDqQsiNuAJ1EU:-O36_aTE8eLi4BWVwlQ0:baazqqn) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why don't we use the type directly from Cairo?
</blockquote></details>

The issue is that Cairo-lang does not implement `Serialize` and `Deserialize.`
We define a wrapper that will have the required functionality.

___
___
*[`crates/gateway/src/compiler_version.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/83#-O36_1X4COV3QJ_Ojgth:-O36_1X4COV3QJ_Ojgti:b-96r9k5) ([raw file](https://github.com/starkware-libs/sequencer/blob/6513dc1b544a5434387ba78f7be6383cd65e5c96/crates/gateway/src/compiler_version.rs#L22)):*
> ```XML
> 
> #[derive(Clone, Copy, Debug, PartialEq)]
> pub struct VersionId(pub CairoLangVersionId);
> ```

@yair-starkware Your question is about this line.

The issue is that Cairo-lang does not implement `Serialize` and `Deserialize.`
We define a wrapper that will have the required functionality.



_Code quote:_
```XML
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct VersionId(pub CairoLangVersionId);
```

**Review by yair-starkware — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/83)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/compiler_version.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/83#-O36_1X4COV3QJ_Ojgth:-O37OcXq4CP5_K-egUl6:bktvhsi) ([raw file](https://github.com/starkware-libs/sequencer/blob/6513dc1b544a5434387ba78f7be6383cd65e5c96/crates/gateway/src/compiler_version.rs#L22)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

@yair-starkware Your question is about this line.

The issue is that Cairo-lang does not implement `Serialize` and `Deserialize.`
We define a wrapper that will have the required functionality.
</blockquote></details>

+reviewer:@elintul

**Comment by ArniStarkware** [comment]
I reordered the PRs.
This PR deals with wrapping the `CairoLangVersionId` with our `VersionId`.

This struct offers additional functionality for serialization as this object is used for configuration.

**Comment by ArniStarkware** [comment]
Open a PR in compilers for them to implement serialization/deserialization on Version Id.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/83)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @elintul, @Yael-Starkware, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/83#-O45sD0KCKGHXhbo8i3b:-O49g7IW3l2htrY_u_0T:b-896fix) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Open a PR in compilers for them to implement serialization/deserialization on Version Id.
</blockquote></details>

Done.

___

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/compiler_version.rs` line 44 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/83#-O4A2zr8-F6WTIN0F5kR:-O4A2zr9Dm-jpogKaU6I:bj81bwt) ([raw file](https://github.com/starkware-libs/sequencer/blob/71fd7274963e9812a6cb6e6f6100ed9339875b56/crates/gateway/src/compiler_version.rs#L44)):*
> ```XML
>         let sierra_program_for_compiler = sierra_program_as_felts_to_big_uint_as_hex(
>             safe_slice(&sierra_program, 0..6).map_err(|_| VersionIdError::InvalidVersion {
>                 message: format!("Sierra program is too short."),
> ```

@yair-starkware - You already said - we should remove the `message` from `InvalidVersion`.



_Code quote:_
```XML
            safe_slice(&sierra_program, 0..6).map_err(|_| VersionIdError::InvalidVersion {
                message: format!("Sierra program is too short."),
```

**Comment by yair-starkware** [comment]
*[`crates/gateway/src/compiler_version.rs` line 44 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/83#-O4A2zr8-F6WTIN0F5kR:-O4K40qn4TP7bybqdw-s:br6t1fw) ([raw file](https://github.com/starkware-libs/sequencer/blob/71fd7274963e9812a6cb6e6f6100ed9339875b56/crates/gateway/src/compiler_version.rs#L44)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

@yair-starkware - You already said - we should remove the `message` from `InvalidVersion`.
</blockquote></details>

Not sure what you mean, but maybe the error should be: "Couldn't get version from the program - program too short (expecting at least 6 felts, got {}."

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r4, 1 of 2 files at r5, 1 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/83)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @elintul, and @Yael-Starkware)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 34 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/83#-O4K4x9l0WFXj8TmxIC8:-O4K4x9l0WFXj8TmxIC9:b-z2qi9g) ([raw file](https://github.com/starkware-libs/sequencer/blob/97f3e510ceee3d628cb8be71f51d3497e8f2e1c5/crates/gateway/src/stateless_transaction_validator_test.rs#L34)):*
> ```XML
>     static MIN_SIERRA_VERSION: OnceLock<VersionId> = OnceLock::new();
>     MIN_SIERRA_VERSION.get_or_init(|| VersionId::new(1, 1, 0))
> }
> ```

Can you use LazyLock instead of OnceLock?
https://doc.rust-lang.org/stable/std/sync/struct.LazyLock.html



_Code quote:_
```XML
fn min_sierra_version() -> &'static VersionId {
    static MIN_SIERRA_VERSION: OnceLock<VersionId> = OnceLock::new();
    MIN_SIERRA_VERSION.get_or_init(|| VersionId::new(1, 1, 0))
}
```
___
*[`crates/gateway/src/utils.rs` line 168 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/83#-O4K6fJTBkbCLgUkF0-R:-O4K6fJTBkbCLgUkF0-S:b-txgzn2) ([raw file](https://github.com/starkware-libs/sequencer/blob/97f3e510ceee3d628cb8be71f51d3497e8f2e1c5/crates/gateway/src/utils.rs#L168)):*
> ```XML
> 
> // TODO(Arni): Move this to a more general location.
> pub fn safe_slice<T, R>(slice: &[T], range: R) -> Result<&[T], ()>
> ```

Why not to use get?
https://doc.rust-lang.org/stable/std/primitive.slice.html#method.get

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/83)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @elintul, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/compiler_version.rs` line 44 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/83#-O4A2zr8-F6WTIN0F5kR:-O4KWcPT42aoxbDebdSw:bglvcb9) ([raw file](https://github.com/starkware-libs/sequencer/blob/71fd7274963e9812a6cb6e6f6100ed9339875b56/crates/gateway/src/compiler_version.rs#L44)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Not sure what you mean, but maybe the error should be: "Couldn't get version from the program - program too short (expecting at least 6 felts, got {}."
</blockquote></details>

I used ChatGPT for phrasing. 
Done.
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 34 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/83#-O4K4x9l0WFXj8TmxIC8:-O4KMuuN7F92HWNIY_c4:bn5i9r9) ([raw file](https://github.com/starkware-libs/sequencer/blob/97f3e510ceee3d628cb8be71f51d3497e8f2e1c5/crates/gateway/src/stateless_transaction_validator_test.rs#L34)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can you use LazyLock instead of OnceLock?
https://doc.rust-lang.org/stable/std/sync/struct.LazyLock.html
</blockquote></details>

The compiler tells me: `error[E0658]: use of unstable library feature 'lazy_cell'`.
___
*[`crates/gateway/src/utils.rs` line 168 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/83#-O4K6fJTBkbCLgUkF0-R:-O4KUp_p3PyZNGbj_2Af:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/97f3e510ceee3d628cb8be71f51d3497e8f2e1c5/crates/gateway/src/utils.rs#L168)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why not to use get?
https://doc.rust-lang.org/stable/std/primitive.slice.html#method.get
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/83#-:-O4Zezwd6s8B4Hg2a8l1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
