### PR TITLE
chore: use BlockHashAndNumber from SN_API

### PR DESCRIPTION
**Pull request by dan-starkware**

### CODE REVIEW

**Comment by dan-starkware** [comment]
* **#1560** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1560?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1599** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1599?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1599)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/papyrus_rpc/src/v0_8/api/api_impl.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1599#-OAHv29vBUS0C-9KgaJn:-OAHv29vBUS0C-9KgaJo:bqzs0rk) ([raw file](https://github.com/starkware-libs/sequencer/blob/ad092d3d3f809f7225c1d53bc784506980eca4c3/crates/papyrus_rpc/src/v0_8/api/api_impl.rs#L185)):*
> ```XML
>         let header: BlockHeader = get_block_header_by_number(&txn, block_number)?.into();
> 
>         Ok(BlockHashAndNumber { hash: header.block_hash, number: block_number })
> ```

This should fail the schema tests. My guess is that we didn't test this method. Please:
1. add a test for this method (and for syncing, where this issue should exist as well)
2. change our local copy of the schema to have hash/number instead of block_hash/block_number

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1599)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_rpc/src/v0_8/api/api_impl.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1599#-OAHv29vBUS0C-9KgaJn:-OAIGm-s6t2W831AgSOT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ad092d3d3f809f7225c1d53bc784506980eca4c3/crates/papyrus_rpc/src/v0_8/api/api_impl.rs#L185)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This should fail the schema tests. My guess is that we didn't test this method. Please:
1. add a test for this method (and for syncing, where this issue should exist as well)
2. change our local copy of the schema to have hash/number instead of block_hash/block_number
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1599#-:-OAIHNRYCIaqVdVteE5k:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
