### PR TITLE
refactor(blockifier): change return type of invoke_tx deploy_account_tx to account_transaction

### PR DESCRIPTION
**Pull request by avivg-starkware**
…tx to account_transaction

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OAS8PJoCCufnt4wb5Va:-OAS8PJoCCufnt4wb5Vb:bui0flb) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e13fb4282ab5b38e7ec9574b42eb61dfc21bf6e/crates/blockifier/src/concurrency/versioned_state_test.rs#L238)):*
> ```XML
> 
>     // Prepare transactions
>     let account_tx_1 = deploy_account_tx(
> ```

Please revert (more informative)
(in the entire file)



_Code quote:_
```XML
 let account_tx_1 = deploy_account_tx(
```
___
*[`crates/blockifier/src/test_utils/invoke.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OAXCzuN-jnawl90kkXZ:-OAXCzuN-jnawl90kkX_:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e13fb4282ab5b38e7ec9574b42eb61dfc21bf6e/crates/blockifier/src/test_utils/invoke.rs#L30)):*
> ```XML
>         false => AccountTransaction::Invoke(InvokeTransaction::new(invoke_tx, tx_hash)),
>     }
> }
> ```





_Suggestion:_
```XML
    let invoke_tx = match only_query {
        true => InvokeTransaction::new_for_query(invoke_tx, tx_hash),
        false => InvokeTransaction::new(invoke_tx, tx_hash),
    };
    AccountTransaction::Invoke(invoke_tx
}
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 239 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OAXJt0Y7LOIULRwhr9x:-OAXJt0Y7LOIULRwhr9y:bdr3x3y) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e13fb4282ab5b38e7ec9574b42eb61dfc21bf6e/crates/blockifier/src/transaction/account_transaction.rs#L239)):*
> ```XML
>             Self::DeployAccount(tx) => tx.constructor_calldata(),
>             Self::Invoke(tx) => tx.calldata(),
>         }
> ```

Please revert. See my comment below.



_Code quote:_
```XML
    pub fn calldata_length(&self) -> usize {
        self.calldata().0.len()
    }

    pub fn calldata(&self) -> Calldata {
        match self {
            Self::Declare(_tx) => calldata![],
            Self::DeployAccount(tx) => tx.constructor_calldata(),
            Self::Invoke(tx) => tx.calldata(),
        }
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OAXDcR88im1gsbFHZpb:-OAXDcR88im1gsbFHZpc:bqzv5xh) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e13fb4282ab5b38e7ec9574b42eb61dfc21bf6e/crates/blockifier/src/transaction/test_utils.rs#L141)):*
> ```XML
> ) -> (AccountTransaction, ContractAddress) {
>     // Deploy an account contract.
>     let account_tx = deploy_account_tx(deploy_tx_args, nonce_manager);
> ```

Please revert the name



_Code quote:_
```XML
 let account_tx = deploy_account_tx(deploy_tx_args, nonce_manager);
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 442 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OAXJc-cCDkxv3fpD4ha:-OAXJc-cCDkxv3fpD4hb:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e13fb4282ab5b38e7ec9574b42eb61dfc21bf6e/crates/blockifier/src/transaction/transactions_test.rs#L442)):*
> ```XML
>     // transaction.
>     let calldata = Calldata(Arc::clone(&account_tx.calldata().0)); //Aviv how to access?
>     let calldata_length = account_tx.calldata_length();
> ```





_Suggestion:_
```XML
    let calldata = create_trivial_calldata(test_contract_address);
    let account_tx = invoke_tx(invoke_tx_args! {
        sender_address: account_contract_address,
        calldata
        resource_bounds: default_l1_resource_bounds,
    });

    // Extract invoke transaction fields for testing, as it is consumed when creating an account
    // transaction.
    let calldata_length = account_tx.calldata_length();
```

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OAS8PJoCCufnt4wb5Va:-OArm05y7oSScsDA6Mlu:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e13fb4282ab5b38e7ec9574b42eb61dfc21bf6e/crates/blockifier/src/concurrency/versioned_state_test.rs#L238)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please revert (more informative)
(in the entire file)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/invoke.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OAXCzuN-jnawl90kkXZ:-OArm_tq6mmITdi3-LD0:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e13fb4282ab5b38e7ec9574b42eb61dfc21bf6e/crates/blockifier/src/test_utils/invoke.rs#L30)):*
> ```XML
>         false => AccountTransaction::Invoke(InvokeTransaction::new(invoke_tx, tx_hash)),
>     }
> }
> ```

Done
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 239 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OAXJt0Y7LOIULRwhr9x:-OAronAA6mIGjrgP2VyR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e13fb4282ab5b38e7ec9574b42eb61dfc21bf6e/crates/blockifier/src/transaction/account_transaction.rs#L239)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please revert. See my comment below.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OAXDcR88im1gsbFHZpb:-OArn768-LsWY3QrOlZV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e13fb4282ab5b38e7ec9574b42eb61dfc21bf6e/crates/blockifier/src/transaction/test_utils.rs#L141)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please revert the name
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 442 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OAXJc-cCDkxv3fpD4ha:-OAroOMX44Cr21tX_to4:bocmw1v) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e13fb4282ab5b38e7ec9574b42eb61dfc21bf6e/crates/blockifier/src/transaction/transactions_test.rs#L442)):*
> ```XML
>     // transaction.
>     let calldata = Calldata(Arc::clone(&account_tx.calldata().0)); //Aviv how to access?
>     let calldata_length = account_tx.calldata_length();
> ```

Partially done, please see my fix; As 'calldata' is used twice, it doesn't work without a clone.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: 3 of 8 files reviewed, 6 unresolved discussions (waiting on @avivg-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 235 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OAwqNJK-E3IYPcQhPNB:-OAwqNJK-E3IYPcQhPNC:b-a4r6a2) ([raw file](https://github.com/starkware-libs/sequencer/blob/9bdbcaef4c4aa0a0ab91989bd94adcbecc6796f7/crates/blockifier/src/transaction/account_transaction.rs#L235)):*
> ```XML
>             Self::DeployAccount(tx) => tx.constructor_calldata(),
>             Self::Invoke(tx) => tx.calldata(),
>         };
> ```

If we are already here...



_Suggestion:_
```XML
        let calldata = match self {
            Self::Declare(_tx) => return 0,
            Self::DeployAccount(tx) => tx.constructor_calldata(),
            Self::Invoke(tx) => tx.calldata(),
        };
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 212 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OAwqpkV7px1vMYpK50x:-OAwqpkV7px1vMYpK50y:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/9bdbcaef4c4aa0a0ab91989bd94adcbecc6796f7/crates/blockifier/src/transaction/account_transactions_test.rs#L212)):*
> ```XML
>     let result = account_tx.execute(state, &block_context, enforce_fee, true);
>     // Execution should fail if the fee is enforced because the account doesn't have sufficient
>     // balance.
> ```





_Suggestion:_
```XML
    let deploy_account_tx = deploy_account_tx(
        deploy_account_tx_args! {
            class_hash: account.get_class_hash(),
            max_fee: Fee(if zero_bounds { 0 } else { MAX_FEE.0 }),
            resource_bounds: match gas_bounds_mode {
                GasVectorComputationMode::NoL2Gas => l1_resource_bounds(
                    (if zero_bounds { 0 } else { DEFAULT_L1_GAS_AMOUNT.0 }).into(),
                    DEFAULT_STRK_L1_GAS_PRICE.into()
                ),
                GasVectorComputationMode::All => create_all_resource_bounds(
                    (if zero_bounds { 0 } else { DEFAULT_L1_GAS_AMOUNT.0 }).into(),
                    DEFAULT_STRK_L1_GAS_PRICE.into(),
                    (if zero_bounds { 0 } else { DEFAULT_L2_GAS_MAX_AMOUNT.0 }).into(),
                    DEFAULT_STRK_L2_GAS_PRICE.into(),
                    (if zero_bounds { 0 } else { DEFAULT_L1_DATA_GAS_MAX_AMOUNT.0 }).into(),
                    DEFAULT_STRK_L1_DATA_GAS_PRICE.into(),
                ),
            },
            version,
        },
        &mut NonceManager::default(),
    );

    let enforce_fee = deploy_account_tx.create_tx_info().enforce_fee();
    assert_ne!(zero_bounds, enforce_fee);
    let result = deploy_account_tx.execute(state, &block_context, enforce_fee, true);
    // Execution should fail if the fee is enforced because the account doesn't have sufficient
    // balance.
```

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r2, 2 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-:-OAwsu_29p1w40eEiSdF:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @avivg-starkware, @meship-starkware, and @noaov1)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 235 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OAwqNJK-E3IYPcQhPNB:-OAxBBu_0LqIyXcTI4KR:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/9bdbcaef4c4aa0a0ab91989bd94adcbecc6796f7/crates/blockifier/src/transaction/account_transaction.rs#L235)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

If we are already here...
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 212 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OAwqpkV7px1vMYpK50x:-OAxC5CS3DmNcJsBZ-i2:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/9bdbcaef4c4aa0a0ab91989bd94adcbecc6796f7/crates/blockifier/src/transaction/account_transactions_test.rs#L212)):*
> ```XML
>     let result = account_tx.execute(state, &block_context, enforce_fee, true);
>     // Execution should fail if the fee is enforced because the account doesn't have sufficient
>     // balance.
> ```

Done

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 3 of 5 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
> Reviewed 3 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: all files reviewed, 3 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 214 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OBGACMt9z89UdT74xJi:-OBGACMt9z89UdT74xJj:b-67uvg3) ([raw file](https://github.com/starkware-libs/sequencer/blob/35360cd10ebf1e68a87cfe518bcc6ec56280c5f3/crates/blockifier/src/transaction/account_transaction.rs#L214)):*
> ```XML
>     // Calldata for validation contains transaction fields that cannot be obtained by calling
>     // `et_tx_info()`.
>     pub fn validate_entrypoint_calldata(&self) -> Calldata {
> ```

I'm not sure we want to externelize it. Anyway, better to use `pub (crate)`.



_Code quote:_
```XML
pub fn validate_entrypoint_calldata(&self) -> Calldata {
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 253 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OBG7I_u-HzAP5t-Uxiw:-OBG7I_v43i1NpJwrrZr:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/35360cd10ebf1e68a87cfe518bcc6ec56280c5f3/crates/blockifier/src/concurrency/versioned_state_test.rs#L253)):*
> ```XML
>     };
>     let nonce_manager = &mut NonceManager::default();
>     let account_tx_2 = deploy_account_tx(deploy_tx_args, nonce_manager);
> ```





_Suggestion:_
```XML
let deploy_account_tx_2 = deploy_account_tx(deploy_tx_args, nonce_manager
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1719 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OBGASJyAR9JlvoBUkAI:-OBGASJyAR9JlvoBUkAJ:bejmnrd) ([raw file](https://github.com/starkware-libs/sequencer/blob/71daa83c0a113864a3027269e68749e4782476e0/crates/blockifier/src/transaction/transactions_test.rs#L1719)):*
> ```XML
>     // Build expected validate call info.
>     let validate_calldata =
>         [vec![class_hash.0, salt.0], (*constructor_calldata.0).clone()].concat();
> ```

I'm wondering if it's part of what we are testing, the validity of the `validate_entrypoint_calldata` method. 



_Code quote:_
```XML
    let validate_calldata =
        [vec![class_hash.0, salt.0], (*constructor_calldata.0).clone()].concat();
```

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: all files reviewed, 3 unresolved discussions (waiting on @avivg-starkware)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 214 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OBGACMt9z89UdT74xJi:-OBKFSge1fraL0n4XvhC:b6xmk7c) ([raw file](https://github.com/starkware-libs/sequencer/blob/35360cd10ebf1e68a87cfe518bcc6ec56280c5f3/crates/blockifier/src/transaction/account_transaction.rs#L214)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I'm not sure we want to externelize it. Anyway, better to use `pub (crate)`.
</blockquote></details>

I reverted back to not pub, the implementation in "transactions_test.rs" (in fn validate_entry_point_selector), in which I used this PR, is now almost a copy of this func. 
In #1688, after refactoring AccountTransaction, I'll be able to revert to the prev implementation. 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1719 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OBGASJyAR9JlvoBUkAI:-OBKKxVR0pCRPd9k8fvB:bu8brso) ([raw file](https://github.com/starkware-libs/sequencer/blob/71daa83c0a113864a3027269e68749e4782476e0/crates/blockifier/src/transaction/transactions_test.rs#L1719)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I'm wondering if it's part of what we are testing, the validity of the `validate_entrypoint_calldata` method.
</blockquote></details>

see comment above. 
It look like the content of the code is pretty much the same, only that the test func uses more declarations . 
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 253 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OBG7I_u-HzAP5t-Uxiw:-OBKFGsE7fiRsRcYRe0k:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/35360cd10ebf1e68a87cfe518bcc6ec56280c5f3/crates/blockifier/src/concurrency/versioned_state_test.rs#L253)):*
> ```XML
>     };
>     let nonce_manager = &mut NonceManager::default();
>     let account_tx_2 = deploy_account_tx(deploy_tx_args, nonce_manager);
> ```

Done

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1721 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OBKrgoa41gauIVoiJil:-OBKrgoa41gauIVoiJim:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/5f06479d58d3fd532f8e64607b625fcdf305cac1/crates/blockifier/src/transaction/transactions_test.rs#L1721)):*
> ```XML
> 
>     // Build expected validate call info.
>     // TODO (AvivG) Temp implementation until AccountTransaction refactor PR.
> ```





_Suggestion:_
```XML
    // TODO(AvivG): When the AccountTransaction refactor is complete, simplify the creation of `validate_calldata` by doing 1.2.3...
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @avivg-starkware, @meship-starkware, and @noaov1)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1721 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OBKrgoa41gauIVoiJil:-OBKuCsa8r07c5f77ZXP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5f06479d58d3fd532f8e64607b625fcdf305cac1/crates/blockifier/src/transaction/transactions_test.rs#L1721)):*
> ```XML
> 
>     // Build expected validate call info.
>     // TODO (AvivG) Temp implementation until AccountTransaction refactor PR.
> ```

Done.

**Review by meship-starkware — APPROVED** [review]
> Reviewed 3 of 4 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 4 files at r6, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware and @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Comment by avivg-starkware** [comment]
* **#1868** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1868?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1643** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1643?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @avivg-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 16 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OBPryEvAl8CxcXMdvvx:-OBPryEvAl8CxcXMdvvy:b-w3a07x) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca4a66d11ebfe050df171ce9a3070f6562cc268b/crates/blockifier/src/test_utils/deploy_account.rs#L16)):*
> ```XML
>     );
> 
>     // TODO(AvivG): use the "new" method.
> ```

Delete the todo. It will be addressed in future PR.
Please link in this thread which PR addresses this issue.

(Non-blocking, this todo can be deleted later).



_Code quote:_
```XML
    // TODO(AvivG): use the "new" method.
```

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1643)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 16 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/1643#-OBPryEvAl8CxcXMdvvx:-OBPvJcy2P9XuoZ5qSwn:b-bgahgn) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca4a66d11ebfe050df171ce9a3070f6562cc268b/crates/blockifier/src/test_utils/deploy_account.rs#L16)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Delete the todo. It will be addressed in future PR.
Please link in this thread which PR addresses this issue.

(Non-blocking, this todo can be deleted later).
</blockquote></details>

Thanks! the PR is #1688   
A short explanation: after this PR, using "new" is longer needed here as we're no longer manually setting only_query to false, but rather this is done in ".into()"

**Pull request merged**
