### PR TITLE
feat(blockifier): gas_for_fee computation

### PR DESCRIPTION
**Pull request by TzahiTaub**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1804)* status: all files reviewed, 6 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 370 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1804#-OAwNBIV-ryjUHiK4RQ8:-OAwNBIV-ryjUHiK4RQ9:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/97f71d507fd05f675b3d8ac03537e8ad62a64384/crates/blockifier/src/execution/entry_point_execution.rs#L370)):*
> ```XML
> }
> 
> /// Calculates the gas for fee consumed in the current call.
> ```





_Suggestion:_
```XML
/// Calculates the total gas for fee consumed in the current call + subtree.
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 387 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1804#-OAwLW2qEnjQXN4xH072:-OAwLW2rAjaLzFuv4ytW:b-16c233) ([raw file](https://github.com/starkware-libs/sequencer/blob/97f71d507fd05f675b3d8ac03537e8ad62a64384/crates/blockifier/src/execution/entry_point_execution.rs#L387)):*
> ```XML
>     // is 2 (upper branch) + 4 (lower branch).
>     // For every branch, the first child embeds its branch "VM mode calls gas_consumed" in the
>     // difference between its gas_consumed and gas_for_fee.
> ```

How about this? Clearer, IMO
```
// The total sierra gas consumed in this specific call is `gas_consumed` (total gas including self + subtree),
// minus the sum of all inner calls total sierra gas consumed.
// To compute the total sierra gas to charge (if the sierra gas resource is the tracked resource), we add this
// amount to the total gas to charge for in the subtree:
// total_gas_to_charge = gas_consumed - total_subtree_gas_consumed + total_subtree_gas_to_charge.
```



_Code quote:_
```XML
    // For CairoSteps the gas_for_fee is 0.
    // For SierraGas it is the gas_consumed of the call minus the gas_consumed of CairoSteps (VM)
    // mode inner calls.
    // E.g., for the following call topology (marked as TrackedResource(gas_consumed, gas_for_fee)):
    //       Gas(8,2) -> Gas(3,1) -> VM(2,0) -> VM(1,0)
    //          \
    //           --> VM(4,0)
    // The fee_for_gas for the first call is 8-2-4 = 2. As the gas_consumed of derived VM mode calls
    // is 2 (upper branch) + 4 (lower branch).
    // For every branch, the first child embeds its branch "VM mode calls gas_consumed" in the
    // difference between its gas_consumed and gas_for_fee.
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 389 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1804#-OAwM0dc8z5zpDDuaXiZ:-OAwM0dc8z5zpDDuaXi_:bgm1e8b) ([raw file](https://github.com/starkware-libs/sequencer/blob/97f71d507fd05f675b3d8ac03537e8ad62a64384/crates/blockifier/src/execution/entry_point_execution.rs#L389)):*
> ```XML
>     // difference between its gas_consumed and gas_for_fee.
>     GasAmount(match tracked_resource {
>         TrackedResource::CairoSteps => 0,
> ```

is my comment correct?
if so, please add it; if not, why not?



_Suggestion:_
```XML
// If the tracked resource is steps, then all tracked resources of all calls in
// the subtree are also steps. Thus, the total gas to charge in this subtree is zero. 
TrackedResource::CairoSteps => 0,
```
___
*[`crates/blockifier/src/execution/entry_point_execution_test.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1804#-OAwNHfr5yvYayyynuUE:-OAwNHfr5yvYayyynuUF:b-n5gyck) ([raw file](https://github.com/starkware-libs/sequencer/blob/97f71d507fd05f675b3d8ac03537e8ad62a64384/crates/blockifier/src/execution/entry_point_execution_test.rs#L5)):*
> ```XML
> use super::to_gas_for_fee;
> use crate::execution::call_info::{CallExecution, CallInfo, ChargedResources};
> use crate::execution::contract_class::TrackedResource;
> ```

be consistent: `super` or `crate::execution`?
i prefer `crate` but this is a test module so super is also ok



_Code quote:_
```XML
use super::to_gas_for_fee;
use crate::execution::call_info::{CallExecution, CallInfo, ChargedResources};
use crate::execution::contract_class::TrackedResource;
```
___
*[`crates/blockifier/src/execution/entry_point_execution_test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1804#-OAwNrsz9GxR4wwJRtrR:-OAwNrsz9GxR4wwJRtrS:b-9gd33v) ([raw file](https://github.com/starkware-libs/sequencer/blob/97f71d507fd05f675b3d8ac03537e8ad62a64384/crates/blockifier/src/execution/entry_point_execution_test.rs#L51)):*
> ```XML
>         },
>         ..Default::default()
>     });
> ```

can you merge this with the `for` loop above? adding a fourth boolean argument so you know how to construct the `CallInfo`, and whether you want to push or reassign to `inner_calls`?



_Code quote:_
```XML
    // Second branch - 1 call.
    let (tracked_resource, gas_consumed, expected_gas_for_fee) =
        (TrackedResource::CairoSteps, 4, 0);
    assert_eq!(to_gas_for_fee(&tracked_resource, gas_consumed, &[]).0, expected_gas_for_fee);

    inner_calls.push(CallInfo {
        execution: CallExecution { gas_consumed, ..Default::default() },
        tracked_resource,
        charged_resources: ChargedResources {
            gas_for_fee: GasAmount(expected_gas_for_fee),
            ..Default::default()
        },
        ..Default::default()
    });
```
___
*[`crates/blockifier/src/execution/entry_point_execution_test.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1804#-OAwOBswE4SXiD5zMxBc:-OAwOBsxEhUqHxP8jdm_:b5gc5w0) ([raw file](https://github.com/starkware-libs/sequencer/blob/97f71d507fd05f675b3d8ac03537e8ad62a64384/crates/blockifier/src/execution/entry_point_execution_test.rs#L58)):*
> ```XML
>         to_gas_for_fee(&tracked_resource, gas_consumed, &inner_calls).0,
>         expected_gas_for_fee
>     );
> ```

no point in intermediate vars here IMO... your docstring is clear



_Suggestion:_
```XML
    assert_eq!(to_gas_for_fee(&TrackedResource::SierraGas, 8, &inner_calls).0, 2);
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1804)* status: all files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 370 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1804#-OAwNBIV-ryjUHiK4RQ8:-OB0QaghDotOUurD-ySC:b-hm0q8s) ([raw file](https://github.com/starkware-libs/sequencer/blob/97f71d507fd05f675b3d8ac03537e8ad62a64384/crates/blockifier/src/execution/entry_point_execution.rs#L370)):*
> ```XML
> }
> 
> /// Calculates the gas for fee consumed in the current call.
> ```

Done. Removed the consumed as it's not clear what it means.
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 387 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1804#-OAwLW2qEnjQXN4xH072:-OB65qiXC8n1DrgiHg4M:b-ox7y94) ([raw file](https://github.com/starkware-libs/sequencer/blob/97f71d507fd05f675b3d8ac03537e8ad62a64384/crates/blockifier/src/execution/entry_point_execution.rs#L387)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

How about this? Clearer, IMO
```
// The total sierra gas consumed in this specific call is `gas_consumed` (total gas including self + subtree),
// minus the sum of all inner calls total sierra gas consumed.
// To compute the total sierra gas to charge (if the sierra gas resource is the tracked resource), we add this
// amount to the total gas to charge for in the subtree:
// total_gas_to_charge = gas_consumed - total_subtree_gas_consumed + total_subtree_gas_to_charge.
```
</blockquote></details>

Changed it a little (specifically removed most of the `total` as I think it should only be when talking about `self + subtree`). Thanks.
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 389 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1804#-OAwM0dc8z5zpDDuaXiZ:-OB0QsBw4oui_DGhupYV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/97f71d507fd05f675b3d8ac03537e8ad62a64384/crates/blockifier/src/execution/entry_point_execution.rs#L389)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is my comment correct?
if so, please add it; if not, why not?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/entry_point_execution_test.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1804#-OAwNHfr5yvYayyynuUE:-OB0RCk_CxJlDoUC5uPP:b-xziu26) ([raw file](https://github.com/starkware-libs/sequencer/blob/97f71d507fd05f675b3d8ac03537e8ad62a64384/crates/blockifier/src/execution/entry_point_execution_test.rs#L5)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

be consistent: `super` or `crate::execution`?
i prefer `crate` but this is a test module so super is also ok
</blockquote></details>

Do you mean to change everything to super::super?
___
*[`crates/blockifier/src/execution/entry_point_execution_test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1804#-OAwNrsz9GxR4wwJRtrR:-OB6DTum7Fq4SA3UrhDi:buqk0yl) ([raw file](https://github.com/starkware-libs/sequencer/blob/97f71d507fd05f675b3d8ac03537e8ad62a64384/crates/blockifier/src/execution/entry_point_execution_test.rs#L51)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you merge this with the `for` loop above? adding a fourth boolean argument so you know how to construct the `CallInfo`, and whether you want to push or reassign to `inner_calls`?
</blockquote></details>

No :)
Became too ugly.
___
*[`crates/blockifier/src/execution/entry_point_execution_test.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1804#-OAwOBswE4SXiD5zMxBc:-OB668XW462vVWtOUhJW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/97f71d507fd05f675b3d8ac03537e8ad62a64384/crates/blockifier/src/execution/entry_point_execution_test.rs#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no point in intermediate vars here IMO... your docstring is clear
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1804#-:-OB6KWBj3xpBE7C9lSs0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/execution/entry_point_execution_test.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1804#-OAwNHfr5yvYayyynuUE:-OB6KKq2738yOc_GxPlr:bawnfza) ([raw file](https://github.com/starkware-libs/sequencer/blob/97f71d507fd05f675b3d8ac03537e8ad62a64384/crates/blockifier/src/execution/entry_point_execution_test.rs#L5)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Do you mean to change everything to super::super?
</blockquote></details>

`super` and `crate::execution` are interchangeable in this module.
I mean: pick one :)
I prefer `crate::..` always

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1804)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/execution/entry_point_execution_test.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1804#-OAwNHfr5yvYayyynuUE:-OB7zZZ-BKbaIqPGqDoL:b-n8mg2h) ([raw file](https://github.com/starkware-libs/sequencer/blob/97f71d507fd05f675b3d8ac03537e8ad62a64384/crates/blockifier/src/execution/entry_point_execution_test.rs#L5)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`super` and `crate::execution` are interchangeable in this module.
I mean: pick one :)
I prefer `crate::..` always
</blockquote></details>

Not exactly - `super == crate::execution::entry_point_execution` and `super::super == crate::execution`

**Pull request merged**
