### PR TITLE
chore: switch to tracing crate

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/291)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware 
I answered your comment in the PR which was over the `committer` crate

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/291#-:-O3Npi7E1-iBrjPD8qnT:b-9lzg6s)* status: 0 of 16 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/291)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer_cli/src/commands.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/291#-O3NupPG9Yki0VAoHT1N:-O3NupPG9Yki0VAoHT1O:b-yda26i) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e4bb52038e19a8e2d4193cc23645eb80c9907ce/crates/committer_cli/src/commands.rs#L21)):*
> ```XML
>             .modify(|filter| *filter = input.config.logger_level())
>             .expect("Failed to set the log level.");
>     }
> ```

Option here is bad, blocking myself



_Code quote:_
```XML
    if let Some(log_filter_handle) = log_filter_handle {
        log_filter_handle
            .modify(|filter| *filter = input.config.logger_level())
            .expect("Failed to set the log level.");
    }
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/291)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/291#-O3WeAODA1_LBZA6Z3AS:-O3WeAODA1_LBZA6Z3AT:br3ffbx) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e4bb52038e19a8e2d4193cc23645eb80c9907ce/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L26)):*
> ```XML
> use crate::storage::errors::StorageError;
> use crate::storage::storage_trait::{create_db_key, StarknetPrefix, Storage, StorageKey};
> #[cfg(test)]
> ```

restore newline



_Code quote:_
```XML
use crate::storage::storage_trait::{create_db_key, StarknetPrefix, Storage, StorageKey};
#[cfg(test)]
```
___
*[`crates/committer_cli/benches/committer_bench.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/291#-O3WesoN5cfD5tqi46KK:-O3WesoN5cfD5tqi46KL:bjnpvtb) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e4bb52038e19a8e2d4193cc23645eb80c9907ce/crates/committer_cli/benches/committer_bench.rs#L69)):*
> ```XML
>                 committer_input_string,
>                 OUTPUT_PATH.to_owned(),
>                 None,
> ```

why not be explicit? (related to removing the `Option` below)



_Code quote:_
```XML
None,
```
___
*[`crates/committer_cli/src/tracing_utils.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/291#-O3WegCDAzLtyJLM3dpk:-O3WegCDAzLtyJLM3dpl:b-nhjk6l) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e4bb52038e19a8e2d4193cc23645eb80c9907ce/crates/committer_cli/src/tracing_utils.rs#L6)):*
> ```XML
> use tracing_subscriber::{filter, fmt, reload, Registry};
> 
> // TODO(Amos, 1/8/2024) Move all tracing instantiations in the monorepo to a common location.
> ```

monorepo is an internal term. non-blocking



_Suggestion:_
```XML
sequencer
```

**Review by amosStarkware — COMMENTED** [review]
Python side:
https://reviewable.io/reviews/starkware-industries/starkware/35694

@dorimedini-starkware it may be better to pass the log level via an env variable instead of through the committer input. that way the log level may be configured when running command types other than `commit`

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/291#-:-O3bvLPKCXkCmqyYN1Wq:borgrku)* status: 4 of 16 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/291#-O3WeAODA1_LBZA6Z3AS:-O3btrq-3jSjnWTvyBsE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e4bb52038e19a8e2d4193cc23645eb80c9907ce/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L26)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

restore newline
</blockquote></details>

Done.
___
*[`crates/committer_cli/benches/committer_bench.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/291#-O3WesoN5cfD5tqi46KK:-O3bttrOEwzkoCaEBAKT:b-avrnqz) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e4bb52038e19a8e2d4193cc23645eb80c9907ce/crates/committer_cli/benches/committer_bench.rs#L69)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not be explicit? (related to removing the `Option` below)
</blockquote></details>

I'm not sure what you mean?
___
*[`crates/committer_cli/src/commands.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/291#-O3NupPG9Yki0VAoHT1N:-O3bu2zs1yqnlSNYOohS:b-plunl2) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e4bb52038e19a8e2d4193cc23645eb80c9907ce/crates/committer_cli/src/commands.rs#L21)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Option here is bad, blocking myself
</blockquote></details>

I changed `log_filter_handle` to be non-optional.
___
*[`crates/committer_cli/src/tracing_utils.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/291#-O3WegCDAzLtyJLM3dpk:-O3bti9H-ig2AtOZ-qlg:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e4bb52038e19a8e2d4193cc23645eb80c9907ce/crates/committer_cli/src/tracing_utils.rs#L6)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

monorepo is an internal term. non-blocking
</blockquote></details>

Done

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/291)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
