### PR TITLE
refactor(blockifier): update get class hash at resources

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
* **#2130** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2130?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2130?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2130)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/resources/versioned_constants_0_13_4.json` line 190 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2130#-OByhqFK7451h47EOgPl:-OByhqFK7451h47EOgPm:bhqflwp) ([raw file](https://github.com/starkware-libs/sequencer/blob/3af0799f5101ebab42fd85a089d40375d8a5287c/crates/blockifier/resources/versioned_constants_0_13_4.json#L190)):*
> ```JSON
>         },
>         "get_class_hash_at_gas_cost": {
>             "step_gas_cost": 89,
> ```

The minimum here is 100.



_Code quote:_
```JSON
"step_gas_cost": 89,
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2130)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_0_13_4.json` line 190 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2130#-OByhqFK7451h47EOgPl:-OBz-3zyAl5OSJ07Alki:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3af0799f5101ebab42fd85a089d40375d8a5287c/crates/blockifier/resources/versioned_constants_0_13_4.json#L190)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

The minimum here is 100.
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2130#-:-OC-La9tENqnYdsWwicZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2130)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2130#-:-OCCL8nV9A1gTUZ-UmLP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
