### PR TITLE
feat(consensus): resend last vote

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/602)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/602)* status: all files reviewed, 8 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E8U1-2f8i9Zp3p18l:-O5E8U1-2f8i9Zp3p18m:b-5ubobs) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L183)):*
> ```XML
>         context: &mut ContextT,
>         task: ShcTask,
>     ) -> Result<ShcReturn<BlockT>, ConsensusError> {
> ```

If we never use the timeout field let's change this to event. Separate PR



_Suggestion:_
```XML
    pub async fn handle_task<ContextT: ConsensusContext<Block = BlockT>>(
        &mut self,
        context: &mut ContextT,
        event: ..,
    ) -> Result<ShcReturn<BlockT>, ConsensusError> {
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E3GPu487NC-SeXgW4:-O5E3GPu487NC-SeXgW5:bgs41hn) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L195)):*
> ```XML
>             }
>             StateMachineEvent::Prevote(block_hash, round) => {
>                 let mut ret_val = vec![];
> ```

Let's make this change throughout the crate for all empty vecs (incl tests). I prefer fewer macros. This can be a separate PR.



_Suggestion:_
```XML
                let mut ret_val = Vec::new();
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E4VBmE8pHl1d5pFyX:-O5E4VBmE8pHl1d5pFyY:b-7f6zit) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L206)):*
> ```XML
>                     });
>                 }
>                 Ok(ShcReturn::Tasks(ret_val))
> ```

Let's reorganize like this to avoid nesting. (This will require some cleanup).
And for precommit



_Suggestion:_
```XML
                let Some(vote) = &self.last_prevote {
                    return Err(...)
                };
                if vote.round > round {
                    return Task(Vec::new());
                }
                context.broadcast(ConsensusMessage::Vote(vote.clone())).await?;
                Ok(ShcReturn::Tasks(vec![ShcTask {
                    duration: self.timeouts.prevote_timeout,
                    event: StateMachineEvent::Prevote(block_hash, round),                
                ]))
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 401 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E6cD-6nqTALwYPJp0:-O5E6cD-6nqTALwYPJp1:baosbsh) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L401)):*
> ```XML
>         }
>         context.broadcast(ConsensusMessage::Vote(vote)).await?;
>         Ok(ret_val)
> ```

I find this easier to read



_Suggestion:_
```XML
        context.broadcast(ConsensusMessage::Vote(vote)).await?;
        if last_vote.as_ref().map_or(true, |last| round < last.round) {
            return Ok(Vec::new());
        }
        *last_vote = Some(vote.clone());
        Ok(vec![ShcTask { duration, event }])
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 338 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E8tt01qMjD9bC0-rQ:-O5E8tt01qMjD9bC0-rR:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L338)):*
> ```XML
> 
> #[tokio::test]
> async fn broadcast_votes() {
> ```





_Suggestion:_
```XML
async fn rebroadcast_votes() {
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 348 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E7nch3ZKYOtBxfKcv:-O5E7nch3ZKYOtBxfKcw:b3kre) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L348)):*
> ```XML
>     );
> 
>     context.expect_proposer().times(1).returning(move |_, _| *VALIDATOR_ID_1);
> ```

?



_Suggestion:_
```XML
    context.expect_proposer().times(1).returning(move |_, _| *PROPOSER_ID);
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 405 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E9BrH7YJNSwxMpY5Y:-O5E9BrH7YJNSwxMpY5Z:bb3u83o) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L405)):*
> ```XML
>             }
>         ]))
>     );
> ```

This adds a lot of lines to the tests, and we don't really care to check duration all the time). Can we do something like this for all of the tests?



_Suggestion:_
```XML
    assert_matches!(
        shc.handle_message(&mut context, prevote(Some(BLOCK.id().0), 0, 0, *VALIDATOR_ID_2)).await,
        Ok(ShcReturn::Tasks(vec![
            ShcTask {event: StateMachineEvent::TimeoutPrevote(0), .. },
            ShcTask {event: StateMachineEvent::Precommit(Some(BLOCK.id()), 0), .. },
        ]))
    );
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 419 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E8osB4RDj65arDKGB:-O5E8osB4RDj65arDKGC:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L419)):*
> ```XML
>             event: StateMachineEvent::Precommit(Some(BLOCK.id()), 0)
>         }]))
>     );
> ```





_Suggestion:_
```XML
    // Re-broadcast vote.
    assert_eq!(
        shc.handle_task(
            &mut context,
            ShcTask {
                duration: TIMEOUTS.precommit_timeout,
                event: StateMachineEvent::Precommit(Some(BLOCK.id()), 0),
            },
        )
        .await,
        Ok(ShcReturn::Tasks(vec![ShcTask {
            duration: TIMEOUTS.precommit_timeout,
            event: StateMachineEvent::Precommit(Some(BLOCK.id()), 0)
        }]))
    );
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/602)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E8U1-2f8i9Zp3p18l:-O5ELxTC5v0-tsLLe_rU:b32wtd) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L183)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

If we never use the timeout field let's change this to event. Separate PR
</blockquote></details>

ok
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E3GPu487NC-SeXgW4:-O5ELwEX0dzmLLwRg1W2:b32wtd) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L195)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's make this change throughout the crate for all empty vecs (incl tests). I prefer fewer macros. This can be a separate PR.
</blockquote></details>

ok
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E4VBmE8pHl1d5pFyX:-O5EEUsz7QpP8VcMAbVT:bauvcvs) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L206)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's reorganize like this to avoid nesting. (This will require some cleanup).
And for precommit
</blockquote></details>

Done. LMK if u have another suggestion the error name
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 401 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E6cD-6nqTALwYPJp0:-O5EHTRsCi5JYog91I1B:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L401)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I find this easier to read
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 338 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E8tt01qMjD9bC0-rQ:-O5EB6wDD9Ch0Y0WdV8X:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L338)):*
> ```XML
> 
> #[tokio::test]
> async fn broadcast_votes() {
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 348 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E7nch3ZKYOtBxfKcv:-O5EJ3vWApPyDcPX7nUZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L348)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 405 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E9BrH7YJNSwxMpY5Y:-O5ELKsw-op-D7vNyPlr:b-5969zk) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L405)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This adds a lot of lines to the tests, and we don't really care to check duration all the time). Can we do something like this for all of the tests?
</blockquote></details>

`..` cannot be used directly with vec in assert_matches!
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 419 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E8osB4RDj65arDKGB:-O5EBP_rDmFODr9v2u1c:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L419)):*
> ```XML
>             event: StateMachineEvent::Precommit(Some(BLOCK.id()), 0)
>         }]))
>     );
> ```

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/602)* status: all files reviewed, 4 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 212 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5SkzAl66sCNVFJsLv3:-O5SkzAl66sCNVFJsLv4:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2b0fc87e3d2290a849887e737ab60a111fa42d2/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L212)):*
> ```XML
>                 };
>                 if last_vote.round > round {
>                     return Ok(ShcReturn::Tasks(vec![]));
> ```





_Suggestion:_
```XML
Vec::new
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 395 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5Skwv4BoMzJ-vkP6yi:-O5Skwv4BoMzJ-vkP6yj:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2b0fc87e3d2290a849887e737ab60a111fa42d2/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L395)):*
> ```XML
>         context.broadcast(ConsensusMessage::Vote(vote.clone())).await?;
>         if last_vote.as_ref().map_or(false, |last| round < last.round) {
>             return Ok(vec![]);
> ```





_Suggestion:_
```XML
Vec::new
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 405 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E9BrH7YJNSwxMpY5Y:-O5SlGfi9-U-4Z7UUeNP:b-ndxm5n) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L405)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

`..` cannot be used directly with vec in assert_matches!
</blockquote></details>

What if instead we create a util fn in this file then (for each task).

Example:



_Code snippet:_
```XML
fn precommit_task(content_id: Option<BlockHash>, round: Round) -> ShcTask {
    ShcTask {
        duration: TIMEOUTS.precommit_timeout,
        event: StateMachineEvent::Precommit(content_id, round),
    }
}


    assert_eq!(
        shc.handle_message(&mut context, prevote(Some(BLOCK.id().0), 0, 0, *VALIDATOR_ID_2)).await,
        Ok(ShcReturn::Tasks(vec![timeout_prevote_task(0), precommit_task(Some(BLOCK.id()), 0)]))
    );
```
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5SsVoO-KvL04faNzXM:-O5SsVoO-KvL04faNzXN:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2b0fc87e3d2290a849887e737ab60a111fa42d2/crates/sequencing/papyrus_consensus/src/types.rs#L179)):*
> ```XML
>     ProtobufConversionError(#[from] ProtobufConversionError),
>     #[error("Invalid event: {0}")]
>     InvalidEvent(String),
> ```





_Suggestion:_
```XML
    /// This should never occur, since events are internally generated.
    #[error("Invalid event: {0}")]
    InvalidEvent(String),
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/602)* status: all files reviewed, 4 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 212 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5SkzAl66sCNVFJsLv3:-O5Stj4ECC_YR9P5gFbK:b-cvdslz) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2b0fc87e3d2290a849887e737ab60a111fa42d2/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L212)):*
> ```XML
>                 };
>                 if last_vote.round > round {
>                     return Ok(ShcReturn::Tasks(vec![]));
> ```

I opened refactor PR #650    
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 395 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5Skwv4BoMzJ-vkP6yi:-O5StzkDEBHi23vPJ6pk:b-8sd8wj) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2b0fc87e3d2290a849887e737ab60a111fa42d2/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L395)):*
> ```XML
>         context.broadcast(ConsensusMessage::Vote(vote.clone())).await?;
>         if last_vote.as_ref().map_or(false, |last| round < last.round) {
>             return Ok(vec![]);
> ```

#650 
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 405 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E9BrH7YJNSwxMpY5Y:-O5T5MPP7jZdeLRnUNfi:b-32b0wo) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L405)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

What if instead we create a util fn in this file then (for each task).

Example:
</blockquote></details>

I did some refactoring, LMK if u prefer putting them in separate PR
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5SsVoO-KvL04faNzXM:-O5StgBG7msEehqkbauF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2b0fc87e3d2290a849887e737ab60a111fa42d2/crates/sequencing/papyrus_consensus/src/types.rs#L179)):*
> ```XML
>     ProtobufConversionError(#[from] ProtobufConversionError),
>     #[error("Invalid event: {0}")]
>     InvalidEvent(String),
> ```

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/602)* status: all files reviewed, 5 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5TAiWc234NUb-37u-a:-O5TAiWc234NUb-37u-b:b61wpyj) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2bcd735d4c37517a05b58f98f81a4d587ee3cf6/crates/sequencing/papyrus_consensus/src/manager_test.rs#L35)):*
> ```XML
>     static ref VALIDATOR_ID_3: ValidatorId = 3_u32.into();
>     static ref TIMEOUTS: TimeoutsConfig = TimeoutsConfig::default();
> }
> ```

I prefer this to putting it in test_utils.

These are basically arbitrary constant just used throughout these tests. Not significant logic that we only want to implement once.



_Code quote:_
```XML
lazy_static! {
    static ref PROPOSER_ID: ValidatorId = 0_u32.into();
    static ref VALIDATOR_ID: ValidatorId = 1_u32.into();
    static ref VALIDATOR_ID_2: ValidatorId = 2_u32.into();
    static ref VALIDATOR_ID_3: ValidatorId = 3_u32.into();
    static ref TIMEOUTS: TimeoutsConfig = TimeoutsConfig::default();
}
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5TAzrb05Ej9QXbRloN:-O5TAzrb05Ej9QXbRloO:b-5cvhig) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2b0fc87e3d2290a849887e737ab60a111fa42d2/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L29)):*
> ```XML
>         ProposalInit { height: BlockNumber(0), round: 0, proposer: *PROPOSER_ID };
>     static ref TIMEOUTS: TimeoutsConfig = TimeoutsConfig::default();
> }
> ```

Prefer these constants in the test file

I presume you wanted to do this for `prevote_task` etc.? We only need those helper functions in this file though.



_Code quote:_
```XML
lazy_static! {
    static ref PROPOSER_ID: ValidatorId = 0_u32.into();
    static ref VALIDATOR_ID_1: ValidatorId = 1_u32.into();
    static ref VALIDATOR_ID_2: ValidatorId = 2_u32.into();
    static ref VALIDATOR_ID_3: ValidatorId = 3_u32.into();
    static ref VALIDATORS: Vec<ValidatorId> =
        vec![*PROPOSER_ID, *VALIDATOR_ID_1, *VALIDATOR_ID_2, *VALIDATOR_ID_3];
    static ref BLOCK: TestBlock = TestBlock { content: vec![1, 2, 3], id: BlockHash(Felt::ONE) };
    static ref PROPOSAL_INIT: ProposalInit =
        ProposalInit { height: BlockNumber(0), round: 0, proposer: *PROPOSER_ID };
    static ref TIMEOUTS: TimeoutsConfig = TimeoutsConfig::default();
}
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 15 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5TBgFP8WbVkl29HPyX:-O5TBgFP8WbVkl29HPyY:b-b8gx5m) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2bcd735d4c37517a05b58f98f81a4d587ee3cf6/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L15)):*
> ```XML
>     static ref PROPOSER_ID: ValidatorId = 0_u32.into();
>     static ref VALIDATOR_ID: ValidatorId = 1_u32.into();
> }
> ```

Keep here



_Code quote:_
```XML
lazy_static! {
    static ref PROPOSER_ID: ValidatorId = 0_u32.into();
    static ref VALIDATOR_ID: ValidatorId = 1_u32.into();
}
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/602)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 405 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E9BrH7YJNSwxMpY5Y:-O5gfQgLB1m6bdv8rXx-:btq52p7) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L405)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

I did some refactoring, LMK if u prefer putting them in separate PR
</blockquote></details>

I think these fns should go at the top of the file and no need to be `pub`
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 362 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5gf5q0BAeRqJCpf-jP:-O5gf5q1CLNqWHFSrL7A:b-aqre5w) ([raw file](https://github.com/starkware-libs/sequencer/blob/e62ab6497cf55bcd30da344628045f443f405224/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L362)):*
> ```XML
>         event: StateMachineEvent::Prevote(block_hash, round),
>     }
> }
> ```

And precommit



_Suggestion:_
```XML
pub fn prevote_task(block_felt: Option<Felt>, round: u32) -> ShcTask {
    ShcTask {
        duration: TIMEOUTS.prevote_timeout,
        event: StateMachineEvent::Prevote(block_felt.map(BlockHash), round),
    }
}
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/602)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 405 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/602#-O5E9BrH7YJNSwxMpY5Y:-O5glBlPAwK1rCNHSl2t:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4aefe7d350a7dcb69f6c3ee761049164a282c42/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L405)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I think these fns should go at the top of the file and no need to be `pub`
</blockquote></details>

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/602)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
