### PR TITLE
feat(mempool): commit block acts as account nonce source of truth

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1214)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1214)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1214#-O8_qRDDCGNFsT8ZXFDj:-O8_qRDDCGNFsT8ZXFDk:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/49b8fcd2adcc95e58e16ef605d92e2a54b8bdc95/crates/mempool/src/mempool.rs#L87)):*
> ```XML
>         self.validate_input(&args)?;
> 
>         let AddTransactionArgs { tx, account_state } = args;
> ```





_Suggestion:_
```XML
let AddTransactionArgs { tx, account_state } = args;
let AccountState { address, nonce } = account_state;
```
___
*[`crates/mempool/src/mempool.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1214#-O8_sMpd6bPL-6fPdUp9:-O8_sMpd6bPL-6fPdUpA:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/49b8fcd2adcc95e58e16ef605d92e2a54b8bdc95/crates/mempool/src/mempool.rs#L90)):*
> ```XML
>         self.tx_pool.insert(tx)?;
> 
>         // Align to account nonce, only if it is at least the one stored.
> ```





_Suggestion:_
```XML
// Align to account nonce, only if it is at least the one stored; skip if lower.
```
___
*[`crates/mempool/src/mempool_test.rs` line 758 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1214#-O8_tjzl8cvYQHTzbwwJ:-O8_tjzl8cvYQHTzbwwK:bbnnqby) ([raw file](https://github.com/starkware-libs/sequencer/blob/49b8fcd2adcc95e58e16ef605d92e2a54b8bdc95/crates/mempool/src/mempool_test.rs#L758)):*
> ```XML
> 
> #[rstest]
> fn test_account_nonce_might_decrease_in_commit_block() {
> ```

Consider testing both incrementing and decrementing the nonce in `test_account_nonces_update_in_commit_block`



_Code quote:_
```XML
test_account_nonce_might_decrease_in_commit_block
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1214)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1214#-O8_qRDDCGNFsT8ZXFDj:-O8_uw0K9-1uV0QgDBPm:b-nb3m6j) ([raw file](https://github.com/starkware-libs/sequencer/blob/49b8fcd2adcc95e58e16ef605d92e2a54b8bdc95/crates/mempool/src/mempool.rs#L87)):*
> ```XML
>         self.validate_input(&args)?;
> 
>         let AddTransactionArgs { tx, account_state } = args;
> ```

Can't consume, need it later.
___
*[`crates/mempool/src/mempool.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1214#-O8_sMpd6bPL-6fPdUp9:-O8_uzJp12S0-g56ZPC-:b-fkebz0) ([raw file](https://github.com/starkware-libs/sequencer/blob/49b8fcd2adcc95e58e16ef605d92e2a54b8bdc95/crates/mempool/src/mempool.rs#L90)):*
> ```XML
>         self.tx_pool.insert(tx)?;
> 
>         // Align to account nonce, only if it is at least the one stored.
> ```

I think it's clear from "only" + code.
___
*[`crates/mempool/src/mempool_test.rs` line 758 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1214#-O8_tjzl8cvYQHTzbwwJ:-O8_v2Db1q3jgSChrJKZ:b-wega3a) ([raw file](https://github.com/starkware-libs/sequencer/blob/49b8fcd2adcc95e58e16ef605d92e2a54b8bdc95/crates/mempool/src/mempool_test.rs#L758)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Consider testing both incrementing and decrementing the nonce in `test_account_nonces_update_in_commit_block`
</blockquote></details>

Increasing is tested in the test above.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1214)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1214#-O8_qRDDCGNFsT8ZXFDj:-O8a54md-a5Rg1lA0BNt:b-ayh646) ([raw file](https://github.com/starkware-libs/sequencer/blob/49b8fcd2adcc95e58e16ef605d92e2a54b8bdc95/crates/mempool/src/mempool.rs#L87)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can't consume, need it later.
</blockquote></details>

I think it doesn’t consume it
___
*[`crates/mempool/src/mempool_test.rs` line 758 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1214#-O8_tjzl8cvYQHTzbwwJ:-O8a4QwT1CZ_qJG17yhT:bfbhn1n) ([raw file](https://github.com/starkware-libs/sequencer/blob/49b8fcd2adcc95e58e16ef605d92e2a54b8bdc95/crates/mempool/src/mempool_test.rs#L758)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Increasing is tested in the test above.
</blockquote></details>

why not check both updates in one test?

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1214)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1214#-O8_qRDDCGNFsT8ZXFDj:-O8a7oK_6waCGqjnPgD6:bhrmej) ([raw file](https://github.com/starkware-libs/sequencer/blob/49b8fcd2adcc95e58e16ef605d92e2a54b8bdc95/crates/mempool/src/mempool.rs#L87)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I think it doesn’t consume it
</blockquote></details>

It does, but something else is happening here; maybe it's possible since there's a single use of `account_state` later on, and its fields are used only behind a reference. Will dig into it.
___
*[`crates/mempool/src/mempool_test.rs` line 758 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1214#-O8_tjzl8cvYQHTzbwwJ:-O8a5bp0-c0IgqYO69f0:bispvjl) ([raw file](https://github.com/starkware-libs/sequencer/blob/49b8fcd2adcc95e58e16ef605d92e2a54b8bdc95/crates/mempool/src/mempool_test.rs#L758)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why not check both updates in one test?
</blockquote></details>

That's the way those tests were initially written, I'd rather not go into refactoring them given that they are about to be converted to flow tests.

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1214#-:-O8a9jsNAqqdUM84B7C4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1214#-O8_qRDDCGNFsT8ZXFDj:-O8a9Z4w6M8UikfJcfak:b-89q77x) ([raw file](https://github.com/starkware-libs/sequencer/blob/49b8fcd2adcc95e58e16ef605d92e2a54b8bdc95/crates/mempool/src/mempool.rs#L87)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It does, but something else is happening here; maybe it's possible since there's a single use of `account_state` later on, and its fields are used only behind a reference. Will dig into it.
</blockquote></details>

Cool!

**Pull request merged**
