### PR TITLE
chore(infra): re-enable cairo native build

### PR DESCRIPTION
**Pull request by alon-dotan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/989)

### CODE REVIEW

**Review by rodrigo-pino — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/989)* status: 0 of 26 files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware and @noaov1)

___
*[`.cargo/config.toml` line 1 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7dyiFlDI_Hyil2roxP:-O7dyiFlDI_Hyil2roxQ:b-1vxxne) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/.cargo/config.toml#L1)):*
> ```TOML
> [env]
> ```

The expected behaviour for MacOS users would be different. Perhaps leaving comments how to config this correctly for other systems.
___
*[`scripts/setup_native_deps.sh` line 36 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7dzbzS1cX1Yr8KTAX6:-O7dzbzS1cX1Yr8KTAX7:b45rsbc) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/scripts/setup_native_deps.sh#L36)):*
> ```Shell
>         TABLEGEN_180_PREFIX="$MLIR_SYS_180_PREFIX"
> 
>         export LIBRARY_PATH
> ```

I find myself unable to select multiple lines, I think this variables declarations are redundant (defined on top and exported below this comment)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/989)* status: 0 of 26 files reviewed, 14 unresolved discussions (waiting on @alon-dotan-starkware and @rodrigo-pino)

___
*[`Dockerfile` line 1 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gpuxBA9BhVAzsoyNi:-O7gpuxBA9BhVAzsoyNj:bz7du5d) ([raw file](https://github.com/starkware-libs/sequencer/blob/6643538ef6c45c0e2a2e0079787aeffc984313e5/Dockerfile#L1)):*
> ```Dockerfile
> # Dockerfile with multi-stage builds for efficient dependency caching and lightweight final image.
> ```

@dan-starkware 
___
*[`Dockerfile` line 62 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gqR8R1HsYyHdNvgwP:-O7gqR8R1HsYyHdNvgwQ:bf4fnki) ([raw file](https://github.com/starkware-libs/sequencer/blob/6643538ef6c45c0e2a2e0079787aeffc984313e5/Dockerfile#L62)):*
> ```Dockerfile
> ###########################
> # Uses Alpine Linux to run a lightweight and secure container.
> FROM alpine:3.17.0 AS papyrus_node
> ```

Is this change okay? @dan-starkware 



_Code quote:_
```Dockerfile
# Uses Alpine Linux to run a lightweight and secure container.
FROM alpine:3.17.0 AS papyrus_node
```
___
*[`Dockerfile` line 73 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gq__G1CMFycycjnos:-O7gq__G1CMFycycjnot:b-dctmmi) ([raw file](https://github.com/starkware-libs/sequencer/blob/6643538ef6c45c0e2a2e0079787aeffc984313e5/Dockerfile#L73)):*
> ```Dockerfile
> RUN set -ex; \
>     apk update; \
>     apk add --no-cache tini; \
> ```

was this flag here for a reason? [@dan-starkware](https://github.com/dan-starkware)



_Code quote:_
```Dockerfile
--no-cache
```
___
*[`.github/workflows/blockifier_ci.yml` line 50 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7grGFT8zyPpPb2_1h8:-O7grGFT8zyPpPb2_1h9:b-g35er2) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/.github/workflows/blockifier_ci.yml#L50)):*
> ```YAML
> 
>   native-blockifier-artifacts-push:
>     runs-on: starkware-ubuntu-latest-large
> ```

This machine change needs to be python-side tested (I'll do it).
@dorimedini-starkware don't expect this to work, and if it does, [@alon-dotan-starkware](https://github.com/alon-dotan-starkware) please advise why...? He though we needed to build the SO on ubuntu 20.04



_Code quote:_
```YAML
runs-on: starkware-ubuntu-latest-large
```
___
*[`.github/workflows/committer_ci.yml` line 120 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7grup52lp--P71hfEg:-O7grup52lp--P71hfEh:bjv6cte) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/.github/workflows/committer_ci.yml#L120)):*
> ```YAML
>               repo: context.repo.repo,
>               body: fs.readFileSync('bench_new.txt', 'utf8'),
>               path: 'Commits'
> ```

@aner-starkware 



_Code quote:_
```YAML
              path: 'Commits'
```
___
*[`.github/workflows/main.yml` line 98 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gs54Z11GrKXdgm9gO:-O7gs54Z11GrKXdgm9gP:blcey8z) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/.github/workflows/main.yml#L98)):*
> ```YAML
> 
>   run-tests:
>     runs-on: starkware-ubuntu-latest-large
> ```

why ubuntu 22?



_Code quote:_
```YAML
runs-on: starkware-ubuntu-latest-large
```
___
*[`.github/workflows/papyrus_benchmark.yaml` line 7 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gsBkjD5YwuHJHlCIO:-O7gsBkjD5YwuHJHlCIP:b-35byhk) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/.github/workflows/papyrus_benchmark.yaml#L7)):*
> ```YAML
>   # TODO: Uncomment and run this automatically when the storage benchmark is fixed.
>   # push:
>   # branches: [main]
> ```

indentation would matter here



_Suggestion:_
```YAML
  #   branches: [main]
```
___
*[`.github/workflows/papyrus_ci.yml` line 5 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gsKAL3Zq8GxJIwyn_:-O7gsKAL3Zq8GxJIwyna:b-vokul7) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/.github/workflows/papyrus_ci.yml#L5)):*
> ```YAML
> on:
>   push:
>     branches: [ main ]
> ```

Why was the extra whitespace added?
(same below)



_Code quote:_
```YAML
   branches: [ main ]
```
___
*[`.github/workflows/papyrus_docker-publish.yml` line 7 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gsYBM01suRMbt8zuy:-O7gsYBM01suRMbt8zuz:b-prdn0x) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/.github/workflows/papyrus_docker-publish.yml#L7)):*
> ```YAML
>   push:
>     branches: [ main ]
>     tags: [ "v*.*.*" ]
> ```

Why was the extra whitespace added?



_Code quote:_
```YAML
    branches: [ main ]
    tags: [ "v*.*.*" ]
```
___
*[`.github/workflows/papyrus_docker-publish.yml` line 28 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gsapu3fbLs4FaK4BQ:-O7gsapu3fbLs4FaK4BR:bbknkx0) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/.github/workflows/papyrus_docker-publish.yml#L28)):*
> ```YAML
> jobs:
>   docker-build-push:
>     runs-on: starkware-ubuntu-latest-large
> ```

Why is this change related to this PR?



_Code quote:_
```YAML
runs-on: starkware-ubuntu-latest-large
```
___
*[`.github/workflows/papyrus_nightly-tests.yml` line 45 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gshX23U8ye5XD6eA4:-O7gshX3E_--EjO1rofG:b-ldxh29) ([raw file](https://github.com/starkware-libs/sequencer/blob/6643538ef6c45c0e2a2e0079787aeffc984313e5/.github/workflows/papyrus_nightly-tests.yml#L45)):*
> ```YAML
> 
>       - run: brew install protobuf@$PROTOC_VERSION
> ```

Is the new kine needed?
___
*[`crates/blockifier/src/execution/contract_class.rs` line 15 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gt5Nc02I-sICvNYkN:-O7gt5Nc02I-sICvNYkO:b-yycl7i) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/crates/blockifier/src/execution/contract_class.rs#L15)):*
> ```XML
> use cairo_lang_utils::bigint::BigUintAsHex;
> #[allow(unused_imports)]
> use cairo_native::executor::AotNativeExecutor;
> ```

Why is this needed?
@varex83 



_Code quote:_
```XML
#[allow(unused_imports)]
use cairo_native::executor::AotNativeExecutor;
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/989)* status: 0 of 26 files reviewed, 15 unresolved discussions (waiting on @alon-dotan-starkware and @rodrigo-pino)

___
*[`scripts/setup_native_deps.sh` line 60 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gvzAt3xbuCCmPS9Lw:-O7gvzAu6JYQLvfgLTcJ:bqcciv9) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/scripts/setup_native_deps.sh#L60)):*
> ```Shell
> function main() {
>     [ "$(uname)" = "Linux" ] && install_essential_deps_linux
>     setup_llvm_deps
> ```

Need to add:
`sudo apt-get install libzstd-dev`

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/989)* status: 0 of 26 files reviewed, 17 unresolved discussions (waiting on @alon-dotan-starkware and @rodrigo-pino)

___
*[`Cargo.toml` line 91 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7h5Qq6B1v-BJUqRnO4:-O7h5Qq6B1v-BJUqRnO5:b-4p177g) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/Cargo.toml#L91)):*
> ```TOML
> cached = "0.44.0"
> cairo-felt = "0.9.1"
> cairo-lang-casm = "2.8.2"
> ```

I updated the compiler version in a separate PR. Please rebase.



_Code quote:_
```TOML
cairo-lang-casm = "2.8.2"
```
___
*[`scripts/setup_native_deps.sh` line 90 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gyub23yEvvSHLvmbA:-O7gyub23yEvvSHLvmbB:b-yrakqt) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ab65e4c792bb756557a84512dad8699279d0191/scripts/setup_native_deps.sh#L90)):*
> ```Shell
> }
> 
> install_cairo_native_runtime() {
> ```

What did that method do and why isn't it needed anymore?



_Code quote:_
```Shell
install_cairo_native_runtime() {
```

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/989)* status: 0 of 26 files reviewed, 17 unresolved discussions (waiting on @alon-dotan-starkware, @noaov1, and @varex83)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 15 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gt5Nc02I-sICvNYkN:-O7hbCUzDJr7ZPBzMaOB:bkviyn9) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/crates/blockifier/src/execution/contract_class.rs#L15)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is this needed?
@varex83
</blockquote></details>

It is not, we can remove

**Comment by aner-starkware** [comment]
*[`.github/workflows/committer_ci.yml` line 120 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7grup52lp--P71hfEg:-O7xNCyzBZoHzVWYmB8J:b-7l8r60) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/.github/workflows/committer_ci.yml#L120)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

@aner-starkware
</blockquote></details>

This is just where to post the comment. AFAIK, this line doesn't work, so it doesn't matter, but if it does work, it's better to include it.

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/989)* status: 0 of 26 files reviewed, 17 unresolved discussions (waiting on @aner-starkware, @dan-starkware, @noaov1, @rodrigo-pino, and @varex83)

___
*[`Dockerfile` line 1 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gpuxBA9BhVAzsoyNi:-O7xSnG178t-qz5J_T4s:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6643538ef6c45c0e2a2e0079787aeffc984313e5/Dockerfile#L1)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

@dan-starkware
</blockquote></details>

Done.
___
*[`Dockerfile` line 62 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gqR8R1HsYyHdNvgwP:-O7xSoGY1bbUru87H5hE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6643538ef6c45c0e2a2e0079787aeffc984313e5/Dockerfile#L62)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is this change okay? @dan-starkware
</blockquote></details>

Done.
___
*[`Dockerfile` line 73 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gq__G1CMFycycjnos:-O7xSrgK3B4J6CHLG3ok:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6643538ef6c45c0e2a2e0079787aeffc984313e5/Dockerfile#L73)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

was this flag here for a reason? [@dan-starkware](https://github.com/dan-starkware)
</blockquote></details>

Done.
___
*[`.github/workflows/blockifier_ci.yml` line 50 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7grGFT8zyPpPb2_1h8:-O7xSz8z2E2znElVMGnp:bj7icye) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/.github/workflows/blockifier_ci.yml#L50)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

This machine change needs to be python-side tested (I'll do it).
@dorimedini-starkware don't expect this to work, and if it does, [@alon-dotan-starkware](https://github.com/alon-dotan-starkware) please advise why...? He though we needed to build the SO on ubuntu 20.04
</blockquote></details>

its only the push... the build itself executed in the docker itself which is ubuntu 20.04
___
*[`.github/workflows/committer_ci.yml` line 120 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7grup52lp--P71hfEg:-O7xTCi5CfQoL1qayh1Q:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/.github/workflows/committer_ci.yml#L120)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

This is just where to post the comment. AFAIK, this line doesn't work, so it doesn't matter, but if it does work, it's better to include it.
</blockquote></details>

Done.
___
*[`.github/workflows/main.yml` line 98 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gs54Z11GrKXdgm9gO:-O7xTNMP-dftiRHLo7uj:b-w1i1u7) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/.github/workflows/main.yml#L98)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

why ubuntu 22?
</blockquote></details>

it makes no difference
___
*[`.github/workflows/papyrus_benchmark.yaml` line 7 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gsBkjD5YwuHJHlCIO:-O7xTVW54Mgz-hOv9axj:b-bo5fkm) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/.github/workflows/papyrus_benchmark.yaml#L7)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

indentation would matter here
</blockquote></details>

nope... its comment, when uncomment the indentation need to be fixed

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/989)* status: 0 of 26 files reviewed, 17 unresolved discussions (waiting on @aner-starkware, @dan-starkware, @noaov1, @rodrigo-pino, and @varex83)

___
*[`.github/workflows/papyrus_ci.yml` line 5 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gsKAL3Zq8GxJIwyn_:-O7xTchACfpp7G4Y1pTv:bt4zg5c) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/.github/workflows/papyrus_ci.yml#L5)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why was the extra whitespace added?
(same below)
</blockquote></details>

code styling
___
*[`.github/workflows/papyrus_docker-publish.yml` line 28 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gsapu3fbLs4FaK4BQ:-O7xTgcI5_pwYBhhd34f:b-3ojodg) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/.github/workflows/papyrus_docker-publish.yml#L28)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is this change related to this PR?
</blockquote></details>

its needed for tests to pass....
need more disk space
___
*[`.github/workflows/papyrus_nightly-tests.yml` line 45 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gshX23U8ye5XD6eA4:-O7xTsQMEr53IZ2EIwSL:b-7hb85j) ([raw file](https://github.com/starkware-libs/sequencer/blob/6643538ef6c45c0e2a2e0079787aeffc984313e5/.github/workflows/papyrus_nightly-tests.yml#L45)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is the new kine needed?
</blockquote></details>

were?
___
*[`crates/blockifier/src/execution/contract_class.rs` line 15 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gt5Nc02I-sICvNYkN:-O7xU3Qe900HP9JWSqD0:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/crates/blockifier/src/execution/contract_class.rs#L15)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

It is not, we can remove
</blockquote></details>

Done.
___
*[`scripts/setup_native_deps.sh` line 90 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gyub23yEvvSHLvmbA:-O7xUOAk4KQJqQgYbtDc:b-33epwy) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ab65e4c792bb756557a84512dad8699279d0191/scripts/setup_native_deps.sh#L90)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What did that method do and why isn't it needed anymore?
</blockquote></details>

dont really know I consulted with @rodrigo-pino  and he mentioned its not needed
___
*[`scripts/setup_native_deps.sh` line 36 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7dzbzS1cX1Yr8KTAX6:-O7xULif2CcuUWF0OUzE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/scripts/setup_native_deps.sh#L36)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

I find myself unable to select multiple lines, I think this variables declarations are redundant (defined on top and exported below this comment)
</blockquote></details>

Done.
___
*[`scripts/setup_native_deps.sh` line 60 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gvzAt3xbuCCmPS9Lw:-O7xUamX-ELNOgd6u-RA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/scripts/setup_native_deps.sh#L60)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Need to add:
`sudo apt-get install libzstd-dev`
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/989)* status: 0 of 26 files reviewed, 17 unresolved discussions (waiting on @alon-dotan-starkware, @aner-starkware, @dan-starkware, @noaov1, @rodrigo-pino, and @varex83)

___
*[`.github/workflows/papyrus_benchmark.yaml` line 7 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gsBkjD5YwuHJHlCIO:-O7xZtds7ugIubZneGwt:b-wltvme) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4d586381fb760623704e5c11c358f3b40770fb/.github/workflows/papyrus_benchmark.yaml#L7)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

nope... its comment, when uncomment the indentation need to be fixed
</blockquote></details>

yes, so indent now, so when it's uncommented no thought will be required.
GH is not good at notifying devs that an action is malformed - the action is simply skipped

**Review by noaov1 — COMMENTED** [review]
> Reviewed 5 of 23 files at r1, 6 of 10 files at r4, 1 of 6 files at r5, 3 of 4 files at r6, 2 of 7 files at r7, 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/989)* status: 18 of 26 files reviewed, 7 unresolved discussions (waiting on @alon-dotan-starkware, @aner-starkware, @dan-starkware, @rodrigo-pino, and @varex83)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/989)* status: 18 of 26 files reviewed, 8 unresolved discussions (waiting on @alon-dotan-starkware, @aner-starkware, @dan-starkware, @rodrigo-pino, and @varex83)

___
*[`Dockerfile` line 36 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7xn2w_030vjeg695VJ:-O7xn2w_030vjeg695VK:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d089336a76249b5574543e8e4939bd1e1499a93b/Dockerfile#L36)):*
> ```Dockerfile
> # # This enables the creation of fully self-contained binaries that do not depend on the system's dynamic libraries,
> # # resulting in more portable executables that can run on any Linux distribution.
> # RUN rustup target add x86_64-unknown-linux-musl
> ```





_Suggestion:_
```Dockerfile
# Reinstalling the stable Rust toolchain to ensure a clean environment
# RUN rustup toolchain uninstall stable-x86_64-unknown-linux-gnu && rustup toolchain install stable-x86_64-unknown-linux-gnu

# Add the x86_64-unknown-linux-musl target to rustup for compiling statically linked binaries.
# This enables the creation of fully self-contained binaries that do not depend on the system's dynamic libraries,
# resulting in more portable executables that can run on any Linux distribution.
# RUN rustup target add x86_64-unknown-linux-musl
```

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/989)* status: 18 of 26 files reviewed, 8 unresolved discussions (waiting on @alon-dotan-starkware, @aner-starkware, @dan-starkware, @noaov1, and @varex83)

___
*[`scripts/setup_native_deps.sh` line 90 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/989#-O7gyub23yEvvSHLvmbA:-O7zgurACcFWjM2A3faO:b-35qfte) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ab65e4c792bb756557a84512dad8699279d0191/scripts/setup_native_deps.sh#L90)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

dont really know I consulted with @rodrigo-pino  and he mentioned its not needed
</blockquote></details>

It's needed for native runtime, but it is not needed now. Better to add it when actually using it.

**Review by noaov1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/989)* status: 18 of 26 files reviewed, 7 unresolved discussions (waiting on @alon-dotan-starkware, @aner-starkware, @dan-starkware, @rodrigo-pino, and @varex83)

**Review by noaov1 — APPROVED** [review]
> Reviewed 5 of 7 files at r7, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/989)* status: 24 of 26 files reviewed, 6 unresolved discussions (waiting on @alon-dotan-starkware, @aner-starkware, @dan-starkware, @rodrigo-pino, and @varex83)

**Review by rodrigo-pino — APPROVED** [review]
> Reviewed 5 of 23 files at r1, 6 of 10 files at r4, 1 of 6 files at r5, 3 of 4 files at r6, 2 of 7 files at r7, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/989)* status: 24 of 26 files reviewed, 6 unresolved discussions (waiting on @alon-dotan-starkware, @aner-starkware, @dan-starkware, and @varex83)

**Review by rodrigo-pino — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/989)* status: 24 of 26 files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware, @aner-starkware, @dan-starkware, @noaov1, and @varex83)

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/989)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/989)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware)

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/989)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Pull request merged**
