### PR TITLE
chore(starknet_monitoring_endpoint): revert app changes

### PR DESCRIPTION
**Pull request by dan-starkware**

### CODE REVIEW

**Comment by dan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2504?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2504** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2504?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2504?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2472** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2472?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2469** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2469?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2504#-:-ODQzZEPEmpHG0xebWrc:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2504)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2504)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Comment by dan-starkware** [comment]
### Merge activity

* **Dec 9, 7:28 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2504).

**Pull request merged**
