### PR TITLE
chore(sequencer_node): add fee token addresses as required target params

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
commit-id:4bb4e626

---

**Stack**:
- #1725 ⬅
- #1710

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by nadin-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1725)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/config/node_config.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1725#-OAhAN3_2kMHl0rKUHYa:-OAhAN3_2kMHl0rKUHYb:bbolpa8) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc8655496e4018fcbf84d1f43bf9f746397aa8e5/crates/mempool_node/src/config/node_config.rs#L37)):*
> ```XML
> 
> // Required target parameters.
> pub static REQUIRED_PARAM_CONFIG_POINTERS: LazyLock<Vec<(ParamPath, SerializedParam)>> =
> ```

Perhaps we should add this as a function within the RequiredParams struct, wdyt?



_Code quote:_
```XML
REQUIRED_PARAM_CONFIG_POINTERS
```
___
*[`crates/mempool_node/src/config/node_config.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1725#-OAhB5n4A1XgPNvmg64g:-OAhB5n4A1XgPNvmg64h:b4r683n) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc8655496e4018fcbf84d1f43bf9f746397aa8e5/crates/mempool_node/src/config/node_config.rs#L59)):*
> ```XML
> 
> // Optional target parameters, i.e., target parameters with default values.
> pub static DEFAULT_PARAM_CONFIG_POINTERS: LazyLock<Vec<(ParamPath, SerializedParam)>> =
> ```

suggestion (not for this PR): Add a ConfigPointerParams struct with two fields: RequiredParams and DefaultParams. Then add to the SequencerNodeConfig config_pointers as a field.



_Code quote:_
```XML
DEFAULT_PARAM_CONFIG_POINTERS
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1725)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/mempool_node/src/config/node_config.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1725#-OAhAN3_2kMHl0rKUHYa:-OAkxG9gEcJenCYNBSG0:b-hy34ge) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc8655496e4018fcbf84d1f43bf9f746397aa8e5/crates/mempool_node/src/config/node_config.rs#L37)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Perhaps we should add this as a function within the RequiredParams struct, wdyt?
</blockquote></details>

Note this is a static variable that describes the structure of the node config, whereas the `RequiredParams` is for generating data of a single invocation/test. 
___
*[`crates/mempool_node/src/config/node_config.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1725#-OAhB5n4A1XgPNvmg64g:-OAkxbb198hY6QvK1FqF:b-lrnr66) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc8655496e4018fcbf84d1f43bf9f746397aa8e5/crates/mempool_node/src/config/node_config.rs#L59)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

suggestion (not for this PR): Add a ConfigPointerParams struct with two fields: RequiredParams and DefaultParams. Then add to the SequencerNodeConfig config_pointers as a field.
</blockquote></details>

I have some thoughts about this, let's discuss in person.

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1725)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/mempool_node/src/config/node_config.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1725#-OAhAN3_2kMHl0rKUHYa:-OAl1thF9_NBP0lP91eF:b-tnkqx) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc8655496e4018fcbf84d1f43bf9f746397aa8e5/crates/mempool_node/src/config/node_config.rs#L37)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Note this is a static variable that describes the structure of the node config, whereas the `RequiredParams` is for generating data of a single invocation/test.
</blockquote></details>

Required is when you want to force the user to provide a value (no default value).
Generated param is when the value can be created from a function (the user can still provide a value and then the function won't be called).

**Review by nadin-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1725#-:-OAlPoyTDIot15y1SJHo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
