### PR TITLE
refactor(network): move BroadcastedMessageManager to separate crate and add OpaquePeerId

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1032)

### CODE REVIEW

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1032)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware and @ShahakShama)

___
*[`crates/papyrus_network_types/src/network_types.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1032#-O7hVeKo-nUURNXaZRZN:-O7hVeKo-nUURNXaZRZO:b-xj5ec9) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d4263c8dbf1ca255069fa07e2eba7d0c7f19971/crates/papyrus_network_types/src/network_types.rs#L24)):*
> ```XML
>         self.0
>     }
> }
> ```

maybe make this impl a trait and impl it in NM?



_Code quote:_
```XML
impl OpaquePeerId {
    /// This function shouldn't be used by anyone except for the papyrus_network crate
    pub fn private_new(peer_id: PeerId) -> Self {
        Self(peer_id)
    }

    /// This function shouldn't be used by anyone except for the papyrus_network crate
    pub fn private_get_peer_id(&self) -> PeerId {
        self.0
    }
}
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1032)* status: all files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware and @Itay-Tsabary-Starkware)

___
*[`crates/papyrus_network_types/src/network_types.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1032#-O7hVeKo-nUURNXaZRZN:-O7htJpoAMZfGSPoDqni:bchtaju) ([raw file](https://github.com/starkware-libs/sequencer/blob/2d4263c8dbf1ca255069fa07e2eba7d0c7f19971/crates/papyrus_network_types/src/network_types.rs#L24)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

maybe make this impl a trait and impl it in NM?
</blockquote></details>

If I impl it in NM it complains that self.0 is private
```
error[E0603]: tuple struct constructor `OpaquePeerId` is private
   --> crates/papyrus_network/src/lib.rs:137:9
    |
137 |         Self(peer_id)
    |         ^^^^^^^^^^^^^

error[E0616]: field `0` of struct `OpaquePeerId` is private
   --> crates/papyrus_network/src/lib.rs:141:14
    |
141 |         self.0
    |              ^ private field
```

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1032#-:-O7xG6HT4nOUhkiuWje-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1032#-:-O7xSBvt2RM1Boq3Hn1o:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
