### PR TITLE
chore(mempool_infra): move verify_test function to common

### PR DESCRIPTION
**Pull request by uriel-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/159)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/159)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/common/mod.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/159#-O2xMPAuDHOiOC4lvPK_:-O2xMPAuDHOiOC4lvPKa:b-c7gawq) ([raw file](https://github.com/starkware-libs/sequencer/blob/5eb5d23a251dbb98c1adeb92b8b56f4620961f37/crates/mempool_infra/tests/common/mod.rs#L93)):*
> ```XML
> ) {
>     assert_eq!(a_client.a_get_value().await.unwrap(), expected_value);
>     let new_expected_value: ValueB = 222;
> ```

Where does 222 come from?
Please change it to be an arg to the function.



_Code quote:_
```XML
 let new_expected_value: ValueB = 222;
```

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/159)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/tests/common/mod.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/159#-O2xMPAuDHOiOC4lvPK_:-O32PN3T7yvl6HufN7ZH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5eb5d23a251dbb98c1adeb92b8b56f4620961f37/crates/mempool_infra/tests/common/mod.rs#L93)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Where does 222 come from?
Please change it to be an arg to the function.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/159)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/common/mod.rs` line 87 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/159#-O32WnPW-Gz9eMi_S3uf:-O32WnPW-Gz9eMi_S3ug:bk7mg4j) ([raw file](https://github.com/starkware-libs/sequencer/blob/622579b643a358e56ee4f36c8c77e05d8e2e38bc/crates/mempool_infra/tests/common/mod.rs#L87)):*
> ```XML
> impl ComponentStarter for ComponentB {}
> 
> pub(crate) async fn verify_response(
> ```

Could you please rename this? With the addition of testing the `set` it is no longer just `verify_response`, but more like `test_body` (or whatever name you see fit).

Also please add a comment before the first assert that states this check the setup value, and one before the two last asserts that these check setting a new value



_Code quote:_
```XML
verify_response
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/159)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/common/mod.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/159#-O2xMPAuDHOiOC4lvPK_:-O32XGLL0USMQW5KWRgj:bb6sh2i) ([raw file](https://github.com/starkware-libs/sequencer/blob/5eb5d23a251dbb98c1adeb92b8b56f4620961f37/crates/mempool_infra/tests/common/mod.rs#L93)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ack.

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/159)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/tests/common/mod.rs` line 87 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/159#-O32WnPW-Gz9eMi_S3uf:-O32ZYoa-3xGVWOqgS0w:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/622579b643a358e56ee4f36c8c77e05d8e2e38bc/crates/mempool_infra/tests/common/mod.rs#L87)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Could you please rename this? With the addition of testing the `set` it is no longer just `verify_response`, but more like `test_body` (or whatever name you see fit).

Also please add a comment before the first assert that states this check the setup value, and one before the two last asserts that these check setting a new value
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/159#-:-O32_6jn9pbGJK9UyyMG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)

**Review by uriel-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/159)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)

**Pull request merged**
