### PR TITLE
build(blockifier, fee): translate resources to l2 gas

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/384)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/384)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/fee/fee_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/384#-O4-mqAeBmHBd-XEFNxX:-O4-mqAeBmHBd-XEFNxY:b7j9w8t) ([raw file](https://github.com/starkware-libs/sequencer/blob/c203584cb80d2c24c1234dff441fe19f5976d0c6/crates/blockifier/src/fee/fee_test.rs#L38)):*
> ```XML
> 
> #[test]
> fn test_simple_calculate_l1_gas_by_vm_usage() {
> ```

for backwards-compatibility we need the L1 gas computation to (a) still exist and (b) be consistent with the (new) L2 gas computation, right?
you are changing the old tests to no longer test L1 gas computation...?
please parametrize the tests instead

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/384)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 177 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/384#-O40P_ZG8KLPO8-UOHIO:-O40P_ZG8KLPO8-UOHIP:bctwlo2) ([raw file](https://github.com/starkware-libs/sequencer/blob/c203584cb80d2c24c1234dff441fe19f5976d0c6/crates/blockifier/src/transaction/objects.rs#L177)):*
> ```XML
>             l1_gas: gas_vector.l1_gas + gas_vector.l2_gas,
>             l1_data_gas: gas_vector.l1_data_gas,
>             l2_gas: 0,
> ```

How does this work if the struct doesn't have it?



_Code quote:_
```XML
       l2_gas: 0,
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/384)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/transaction/objects.rs` line 177 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/384#-O40P_ZG8KLPO8-UOHIO:-O40levH9nIfMMJ15Sla:btej5c7) ([raw file](https://github.com/starkware-libs/sequencer/blob/c203584cb80d2c24c1234dff441fe19f5976d0c6/crates/blockifier/src/transaction/objects.rs#L177)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

How does this work if the struct doesn't have it?
</blockquote></details>

it does have it. always 0, unused

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/384)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 177 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/384#-O40P_ZG8KLPO8-UOHIO:-O40rm1z7gXTsRV5k-it:b-rfoaqt) ([raw file](https://github.com/starkware-libs/sequencer/blob/c203584cb80d2c24c1234dff441fe19f5976d0c6/crates/blockifier/src/transaction/objects.rs#L177)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

it does have it. always 0, unused
</blockquote></details>

I think I have some reviewable bug

**Pull request closed without merging**
