### PR TITLE
test: add batcher client to sequencer end_to_end_test

### PR DESCRIPTION
**Pull request by ArniStarkware**
This PR conflicts with #1296.

In this PR we do not create a mock consensus manager but add the least amount of code to allow us to add the batcher to the flow test.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1352)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#1352** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1352?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1352)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @giladchase)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1352#-O94j8pIDbkcSEDhgCdN:-O94j8pIDbkcSEDhgCdO:b1ovjt) ([raw file](https://github.com/starkware-libs/sequencer/blob/9afeaca52528f427bf637224bcb049baa9474207/crates/tests-integration/tests/end_to_end_test.rs#L66)):*
> ```XML
> 
>     // Set start height.
>     let current_height = BlockNumber(1);
> ```

Consider asserting that the storages are synced by checking the markers



_Code quote:_
```XML
let current_height = BlockNumber(1);
```
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1352#-O94jLM620WahYZGnPzo:-O94jLM620WahYZGnPzp:bh29wk) ([raw file](https://github.com/starkware-libs/sequencer/blob/9afeaca52528f427bf637224bcb049baa9474207/crates/tests-integration/tests/end_to_end_test.rs#L69)):*
> ```XML
> 
>     // Test.
>     batcher_client.start_height(StartHeightInput { height: current_height }).await.unwrap();
> ```

What about build_proposal & get_proposal_content? both are already in main

**Comment by ArniStarkware** [comment]
*[`crates/tests-integration/tests/end_to_end_test.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1352#-O94jLM620WahYZGnPzo:-O99Cadv4DJBEfng5DM9:bru6pdd) ([raw file](https://github.com/starkware-libs/sequencer/blob/9afeaca52528f427bf637224bcb049baa9474207/crates/tests-integration/tests/end_to_end_test.rs#L69)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

What about build_proposal & get_proposal_content? both are already in main
</blockquote></details>

`build_proposal` is covered in the next PR: #1386. (Was not possible before: #1384).
`get_proposal_contexnt` can not be added to the test yet as the `BlockBuilderTrait` is not completely implemented.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1352)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @giladchase)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1352#-O94j8pIDbkcSEDhgCdN:-O99TSd31jXNAv0rRqYn:b5ulnv1) ([raw file](https://github.com/starkware-libs/sequencer/blob/9afeaca52528f427bf637224bcb049baa9474207/crates/tests-integration/tests/end_to_end_test.rs#L66)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider asserting that the storages are synced by checking the markers
</blockquote></details>

I thought this was in the context of the setup.
Please add a todo to get the height from the `mock_running_system` object.

**Comment by ArniStarkware** [comment]
*[`crates/tests-integration/tests/end_to_end_test.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1352#-O94j8pIDbkcSEDhgCdN:-O99Wa9P5BI2dXVDJsoS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9afeaca52528f427bf637224bcb049baa9474207/crates/tests-integration/tests/end_to_end_test.rs#L66)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I thought this was in the context of the setup.
Please add a todo to get the height from the `mock_running_system` object.
</blockquote></details>

Done.

**Pull request merged**
