### PR TITLE
refactor: move test files to dedicated directory

### PR DESCRIPTION
**Pull request by aner-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Refactoring (no functional changes, no API changes)

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/105)

### CODE REVIEW

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/105)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/committer_cli/test_inputs/tree_flow_inputs.json` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/105#-O2sbSftDSdqo0YR8g9h:-O2sbSfu2N6kssz-ES7A:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4bcedb1b7536b0b272b4a4b7af1abc4abd8c5ade/crates/committer_cli/test_inputs/tree_flow_inputs.json#L1)):*
> ```JSON
> This file is a placeholder for inputs to single_tree_flow regression test and benchmark.
> ```





_Suggestion:_
```JSON
committer_flow
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/105)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer_cli/test_inputs/tree_flow_inputs.json` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/105#-O2sbSftDSdqo0YR8g9h:-O2t8QlkCWqNwWUTHf_J:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4bcedb1b7536b0b272b4a4b7af1abc4abd8c5ade/crates/committer_cli/test_inputs/tree_flow_inputs.json#L1)):*
> ```JSON
> This file is a placeholder for inputs to single_tree_flow regression test and benchmark.
> ```

Done.

**Comment by aner-starkware** [comment]
*[`crates/committer_cli/test_inputs/tree_flow_inputs.json` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/105#-O2sbSftDSdqo0YR8g9h:-O2t8VWY1VReIyhiyfmo:b-pcn7xm) ([raw file](https://github.com/starkware-libs/sequencer/blob/4bcedb1b7536b0b272b4a4b7af1abc4abd8c5ade/crates/committer_cli/test_inputs/tree_flow_inputs.json#L1)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

(In the other file)

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/105#-:-O2tBbfhBdlXi0u9OQ6I:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
