### PR TITLE
chore: move transaction creator test util to starknet api

### PR DESCRIPTION
**Pull request by ArniStarkware**
This is a step towards addressing the issue in: #519.

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/661)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/661?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#661** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/661?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#660** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/660?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 24 files at r1, 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/661)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/blockifier/src/test_utils/declare.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/661#-O61BPU0-R1CJUsb-hVo:-O61BPU0-R1CJUsb-hVp:b-p49ut5) ([raw file](https://github.com/starkware-libs/sequencer/blob/53ca21d2863d77826829689359bbb456d90fc66e/crates/blockifier/src/test_utils/declare.rs#L23)):*
> ```XML
> 
> #[derive(Clone)]
> pub struct DeclareTxArgs {
> ```

I assume no code changes.
You're only moving the code, right?



_Code quote:_
```XML
pub struct DeclareTxArgs {
```
___
*[`crates/blockifier/src/test_utils/invoke.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/661#-O61CUBs8nlS4YtvSJXJ:-O61CUBs8nlS4YtvSJXK:b-a3xt4m) ([raw file](https://github.com/starkware-libs/sequencer/blob/2230b5b94c6c7850ba81452288200830659c4c79/crates/blockifier/src/test_utils/invoke.rs#L11)):*
> ```XML
>     let only_query = invoke_args.only_query;
>     // TODO: Make TransactionVersion an enum and use match here.
>     let invoke_tx = if invoke_args.version == TransactionVersion::ZERO {
> ```

Could you please explain why you kept this code here instead of moving it to `sn-api` and simply calling the `create` function from there?
___
*[`crates/starknet_api/src/test_utils.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/661#-O61D3gGAlcA-TSMpVm1:-O61D3gGAlcA-TSMpVm2:b-j0ihsh) ([raw file](https://github.com/starkware-libs/sequencer/blob/2230b5b94c6c7850ba81452288200830659c4c79/crates/starknet_api/src/test_utils.rs#L8)):*
> ```XML
> 
> // TODO: Default testing bounds should probably be AllResourceBounds variant.
> pub fn default_testing_resource_bounds() -> ValidResourceBounds {
> ```

Maybe it can be in the same file of `ValidResourceBound` struct.



_Code quote:_
```XML
default_testing_resource_bounds(
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/661)* status: 15 of 25 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @MohammadNassar1)

___
*[`crates/blockifier/src/test_utils/declare.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/661#-O61BPU0-R1CJUsb-hVo:-O61QFzdBxgHigaRDeN6:bo6apac) ([raw file](https://github.com/starkware-libs/sequencer/blob/53ca21d2863d77826829689359bbb456d90fc66e/crates/blockifier/src/test_utils/declare.rs#L23)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I assume no code changes.
You're only moving the code, right?
</blockquote></details>

Indeed.
___
*[`crates/blockifier/src/test_utils/invoke.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/661#-O61CUBs8nlS4YtvSJXJ:-O61QTeR4suhBqqoK50h:b4gnt47) ([raw file](https://github.com/starkware-libs/sequencer/blob/2230b5b94c6c7850ba81452288200830659c4c79/crates/blockifier/src/test_utils/invoke.rs#L11)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Could you please explain why you kept this code here instead of moving it to `sn-api` and simply calling the `create` function from there?
</blockquote></details>

Explanation: The function `selector_from_name` is from the `blockifier` crate.
I did not look much into moving it into the shared test util.
(note - `selector_from_name(EXECUTE_ENTRY_POINT_NAME)` is just a constant number).

On the other hand, v0 will be deleted anyway - so I did not want to work hard to support it.
___
*[`crates/starknet_api/src/test_utils.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/661#-O61D3gGAlcA-TSMpVm1:-O61UNVD4MT9avc7OiLr:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2230b5b94c6c7850ba81452288200830659c4c79/crates/starknet_api/src/test_utils.rs#L8)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Maybe it can be in the same file of `ValidResourceBound` struct.
</blockquote></details>

Done.

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/661)* status: 24 of 25 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/starknet_api/src/test_utils.rs` line 3 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/661#-O61ezG934TI43vr28uu:-O61ezG934TI43vr28uv:bq7txjq) ([raw file](https://github.com/starkware-libs/sequencer/blob/24a0fc81c3934423dc495a0f38361e27ac7330ba/crates/starknet_api/src/test_utils.rs#L3)):*
> ```XML
> pub mod declare;
> pub mod deploy_account;
> pub mod invoke;
> ```

Why you define the modules here, and not in lib file?



_Code quote:_
```XML
pub mod declare;
pub mod deploy_account;
pub mod invoke;
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/661)* status: 24 of 25 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @MohammadNassar1)

___
*[`crates/starknet_api/src/test_utils.rs` line 3 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/661#-O61ezG934TI43vr28uu:-O66ZYYo4mB4Kqj8SFnq:bkgqzes) ([raw file](https://github.com/starkware-libs/sequencer/blob/24a0fc81c3934423dc495a0f38361e27ac7330ba/crates/starknet_api/src/test_utils.rs#L3)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why you define the modules here, and not in lib file?
</blockquote></details>

I copied the folder/file structure from blockifier's test utils.

It is nice that the lib file points to the public-facing `test_utils.rs`, and here - it points to the inner workings of the util. also we don't have to decorate everything with: `#[cfg(any(feature = "testing", test))]` - but only once.

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 10 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/661#-:-O6FMJ7i2AMQ1NjEej2n:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Sep 8, 3:01 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/661).

**Pull request merged**
