### PR TITLE
feat(consensus): use protobuf/SMEvent round

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/146)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/146)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @dorimedini-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/146#-O2tDbRB5wdMVzCiHRRT:-O2tDbRB5wdMVzCiHRRU:b-n70h56) ([raw file](https://github.com/starkware-libs/sequencer/blob/6b3fb49ba52c9162464f1df3929080f897c7bcc3/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L119)):*
> ```XML
>         }
>         let sm_proposal = StateMachineEvent::Proposal(Some(block.id()), init.round);
>         self.proposals.insert(init.round, block);
> ```

We should check that there is no proposal already stored. If there is let's produce a warning log and then ignore.



_Code quote:_
```XML
        self.proposals.insert(init.round, block);
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/146)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware and @dorimedini-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/146#-O2tDbRB5wdMVzCiHRRT:-O2tE3kw2qUmrgZ_D5JF:b-3s9am7) ([raw file](https://github.com/starkware-libs/sequencer/blob/6b3fb49ba52c9162464f1df3929080f897c7bcc3/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L119)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

We should check that there is no proposal already stored. If there is let's produce a warning log and then ignore.
</blockquote></details>

Also please add a test for this case.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/146#-O2tE8Hy4VTSlzUuPuT_:-O2tE8Hy4VTSlzUuPuTa:b-jiyggg) ([raw file](https://github.com/starkware-libs/sequencer/blob/6b3fb49ba52c9162464f1df3929080f897c7bcc3/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L167)):*
> ```XML
>                 return Ok(None);
>             }
>         }
> ```

Please add (if missing) tests for these cases.



_Code quote:_
```XML
        if let Some(old) = votes.get(&(vote.round, vote.voter)) {
            if old.block_hash != vote.block_hash {
                return Err(ConsensusError::Equivocation(
                    self.height,
                    ConsensusMessage::Vote(old.clone()),
                    ConsensusMessage::Vote(vote),
                ));
            } else {
                // Replay, ignore.
                return Ok(None);
            }
        }
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/146)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/146#-O2tDbRB5wdMVzCiHRRT:-O2xK3qADlabCtzSizdS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6b3fb49ba52c9162464f1df3929080f897c7bcc3/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L119)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Also please add a test for this case.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/146#-O2tE8Hy4VTSlzUuPuT_:-O2xK4dhBSPqNN5qQihN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6b3fb49ba52c9162464f1df3929080f897c7bcc3/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L167)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Please add (if missing) tests for these cases.
</blockquote></details>

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r2, 1 of 1 files at r3, 3 of 7 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/146)* status: all files reviewed, 5 unresolved discussions (waiting on @asmaastarkware and @dorimedini-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 173 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/146#-O2y1XG839WpHnsL_jOb:-O2y1XG9DJ6MJUqh3SJN:b-iwvo86) ([raw file](https://github.com/starkware-libs/sequencer/blob/519bc42bb08921246143afbc8b08d62da43fd450/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L173)):*
> ```XML
>         }
> 
>         votes.insert((vote.round, vote.voter), vote);
> ```

Above we have `votes.get` and here we have `votes.insert`, that requires 2 hashmap lookups. I'd like to reduce that to 1 for performance. Can you look into using the `entry` interface to do that?



_Code quote:_
```XML
        votes.insert((vote.round, vote.voter), vote);
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 17 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/146#-O2y2Ej20depkT4eNL89:-O2y2Ej20depkT4eNL8A:b-p03u55) ([raw file](https://github.com/starkware-libs/sequencer/blob/519bc42bb08921246143afbc8b08d62da43fd450/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L17)):*
> ```XML
>         vote_type: VoteType::Prevote,
>         height,
>         round: 0,
> ```

Pass round to the function (and for precommit)



_Code quote:_
```XML
        round: 0,
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 148 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/146#-O2y2mUWEfyij9I9F29b:-O2y2mUWEfyij9I9F29c:b-x2oq1t) ([raw file](https://github.com/starkware-libs/sequencer/blob/519bc42bb08921246143afbc8b08d62da43fd450/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L148)):*
> ```XML
>     assert_eq!(res, Ok(None));
> 
>     // Sending the same proposal again - should be ignored.
> ```

Can you please double check that the expectations fail if called multiple times. Specifically I think we need to be explicit above with `context.expect_broadcast().time(1)` or something like that. Look at the `mockall` documentation and make sure to check for the failure before making the change I suggested.

Also it's helpful to keep tests focused. Let's create a separate test where we just check for the ignored proposal.



_Suggestion:_
```XML
    // Send the same proposal again, which is be ignored (no expectations).
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 209 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/146#-O2y3t0a2gYsdKSahN7b:-O2y3t0a2gYsdKSahN7c:bvlcukq) ([raw file](https://github.com/starkware-libs/sequencer/blob/519bc42bb08921246143afbc8b08d62da43fd450/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L209)):*
> ```XML
>     // Sending the same vote again should be fine - ignored.
>     let res = shc.handle_message(&mut context, first_vote.clone()).await;
>     assert_eq!(res, Ok(None));
> ```

We need to prove that this is ignored. The line above also returns `Ok(None)`. Probably the easiest way is to show that we reach a decision in line with the first vote.



_Code quote:_
```XML
    // Sending the same vote again should be fine - ignored.
    let res = shc.handle_message(&mut context, first_vote.clone()).await;
    assert_eq!(res, Ok(None));
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 221 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/146#-O2y4oquEngxavmzoqQO:-O2y4oquEngxavmzoqQP:b7u4c4k) ([raw file](https://github.com/starkware-libs/sequencer/blob/519bc42bb08921246143afbc8b08d62da43fd450/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L221)):*
> ```XML
>         }
>         _ => panic!("Expected Equivocation error"),
>     }
> ```

Let's create a separate test for equivocation from repeats.



_Code quote:_
```XML
    match res {
        Err(ConsensusError::Equivocation(height, old_vote, new_vote)) => {
            assert_eq!(height, BlockNumber(0));
            assert_eq!(old_vote, first_vote);
            assert_eq!(new_vote, second_vote);
        }
        _ => panic!("Expected Equivocation error"),
    }
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/146)* status: 3 of 10 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 173 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/146#-O2y1XG839WpHnsL_jOb:-O2yPzKG6S67tneYmxzO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/519bc42bb08921246143afbc8b08d62da43fd450/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L173)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Above we have `votes.get` and here we have `votes.insert`, that requires 2 hashmap lookups. I'd like to reduce that to 1 for performance. Can you look into using the `entry` interface to do that?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 17 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/146#-O2y2Ej20depkT4eNL89:-O2yQuL2Eddxs-C4S6sA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/519bc42bb08921246143afbc8b08d62da43fd450/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L17)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Pass round to the function (and for precommit)
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 148 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/146#-O2y2mUWEfyij9I9F29b:-O2ynyzv-5bqhV5W6aCB:b-xhzs5q) ([raw file](https://github.com/starkware-libs/sequencer/blob/519bc42bb08921246143afbc8b08d62da43fd450/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L148)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Can you please double check that the expectations fail if called multiple times. Specifically I think we need to be explicit above with `context.expect_broadcast().time(1)` or something like that. Look at the `mockall` documentation and make sure to check for the failure before making the change I suggested.

Also it's helpful to keep tests focused. Let's create a separate test where we just check for the ignored proposal.
</blockquote></details>

Done. I will open a separate PR for tests

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/146)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @dorimedini-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 173 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/146#-O2y1XG839WpHnsL_jOb:-O333nrt3x1veWTltiR8:beyv5db) ([raw file](https://github.com/starkware-libs/sequencer/blob/519bc42bb08921246143afbc8b08d62da43fd450/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L173)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is incorrect because you always `insert`. Notice how we have the check for conflicts first. That is why I asked about using the `entry` interface, so that we only insert after confirming that there is no conflict.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/146)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @dorimedini-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 173 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/146#-O2y1XG839WpHnsL_jOb:-O337ZW1DmSfh3y1Ibj1:bds2uki) ([raw file](https://github.com/starkware-libs/sequencer/blob/519bc42bb08921246143afbc8b08d62da43fd450/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L173)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This is incorrect because you always `insert`. Notice how we have the check for conflicts first. That is why I asked about using the `entry` interface, so that we only insert after confirming that there is no conflict.
</blockquote></details>

Also see my comment on https://reviewable.io/reviews/starkware-libs/sequencer/187 for why this is no longer relevant since we are splitting the check and insert.

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/146)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 173 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/146#-O2y1XG839WpHnsL_jOb:-O36fyES0x_rAwF-KnSi:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/519bc42bb08921246143afbc8b08d62da43fd450/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L173)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Also see my comment on https://reviewable.io/reviews/starkware-libs/sequencer/187 for why this is no longer relevant since we are splitting the check and insert.
</blockquote></details>

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/146)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @dorimedini-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 94 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/146#-O36oUKk0LBR8FvxO5YB:-O36oUKk0LBR8FvxO5YC:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/97df998aaee60bceb7ca531627af97c89cd79d4d/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L94)):*
> ```XML
>         }
>         let Entry::Vacant(proposal_entry) = self.proposals.entry(init.round) else {
>             info!("Round {} already has a proposal, ignoring", init.round);
> ```





_Suggestion:_
```XML
 warn!
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/146)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 94 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/146#-O36oUKk0LBR8FvxO5YB:-O36s1Zx7b5ZyCXpGfMp:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/97df998aaee60bceb7ca531627af97c89cd79d4d/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L94)):*
> ```XML
>         }
>         let Entry::Vacant(proposal_entry) = self.proposals.entry(init.round) else {
>             info!("Round {} already has a proposal, ignoring", init.round);
> ```

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/146)* status: 7 of 12 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
