### PR TITLE
chore(blockifier): separate create and validate logic on gas prices

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#2246** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2246?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2245** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2245?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2244** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2244?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2243** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2243?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2243?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2243)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @ArniStarkware, and @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2243#-OCTIb4dDr5xE4PcN7wk:-OCTIb4eCr75gJIhxuxq:b-yukule) (no related file):*
Why do we need this change? Specifically if `new()` is now a private method, what's the difference between `safe_new()` and the previous `new()`?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2243)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @alonh5, @aner-starkware, and @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2243#-OCTIb4dDr5xE4PcN7wk:-OCTJeUb4lMrMdYzOL8Q:b-bwmr9n) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why do we need this change? Specifically if `new()` is now a private method, what's the difference between `safe_new()` and the previous `new()`?
</blockquote></details>

The goal is to move `new()` into starknet API.
You do have a point - it will be public at that point. Should I change the visibility of `new` in this PR?

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2243)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @ArniStarkware, and @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2243#-OCTIb4dDr5xE4PcN7wk:-OCTMpR768ZXxxx8OnmT:b-lmau89) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The goal is to move `new()` into starknet API.
You do have a point - it will be public at that point. Should I change the visibility of `new` in this PR?
</blockquote></details>

I think the reason there is a `new()` function is for that validation. So in that case I would remove the `new()` function and the getters completely and make the fields public. WDYT?
___
*[`crates/blockifier/src/blockifier/block.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2243#-OCTMe8CCxnC7BzDklGP:-OCTMe8CCxnC7BzDklGQ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec2b2fe01e89545868f4ca5f4fb4e693c3b55671/crates/blockifier/src/blockifier/block.rs#L88)):*
> ```XML
>     }
> 
>     pub fn safe_new(
> ```





_Suggestion:_
```XML
validated_new
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2243)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @alonh5, @aner-starkware, and @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2243#-OCTIb4dDr5xE4PcN7wk:-OCTaGrS4ROHyVnaYjQU:b-896fix) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I think the reason there is a `new()` function is for that validation. So in that case I would remove the `new()` function and the getters completely and make the fields public. WDYT?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/block.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2243#-OCTMe8CCxnC7BzDklGP:-OCT_oXV2gdG4MeGnM70:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec2b2fe01e89545868f4ca5f4fb4e693c3b55671/crates/blockifier/src/blockifier/block.rs#L88)):*
> ```XML
>     }
> 
>     pub fn safe_new(
> ```

Done.

**Review by alonh5 — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2243)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware and @dorimedini-starkware)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2243)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @ArniStarkware, and @dorimedini-starkware)

___
*[`crates/blockifier/src/blockifier/block.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2243#-OCTj9C-7BAllY2H3aRA:-OCTj9C-7BAllY2H3aRB:bqdctm6) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab1a5046a4d07308646baa0bbd770005d045be0c/crates/blockifier/src/blockifier/block.rs#L108)):*
> ```XML
>             FeeType::Eth => &self.eth_gas_prices,
>         }
>     }
> ```

You can also remove these now.



_Code quote:_
```XML
    pub fn get_l1_gas_price_by_fee_type(&self, fee_type: &FeeType) -> NonzeroGasPrice {
        self.get_gas_prices_by_fee_type(fee_type).l1_gas_price
    }

    pub fn get_l1_data_gas_price_by_fee_type(&self, fee_type: &FeeType) -> NonzeroGasPrice {
        self.get_gas_prices_by_fee_type(fee_type).l1_data_gas_price
    }

    pub fn get_l2_gas_price_by_fee_type(&self, fee_type: &FeeType) -> NonzeroGasPrice {
        self.get_gas_prices_by_fee_type(fee_type).l2_gas_price
    }

    pub fn get_gas_prices_by_fee_type(&self, fee_type: &FeeType) -> &GasPriceVector {
        match fee_type {
            FeeType::Strk => &self.strk_gas_prices,
            FeeType::Eth => &self.eth_gas_prices,
        }
    }
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2243)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @aner-starkware, and @dorimedini-starkware)

___
*[`crates/blockifier/src/blockifier/block.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2243#-OCTj9C-7BAllY2H3aRA:-OCTtx869CDbuGISUe1m:bvho1fz) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab1a5046a4d07308646baa0bbd770005d045be0c/crates/blockifier/src/blockifier/block.rs#L108)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You can also remove these now.
</blockquote></details>

No - I can not. I looked into it.
It is used in many locations, non-trivially.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2243)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @ArniStarkware, and @dorimedini-starkware)

___
*[`crates/blockifier/src/blockifier/block.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2243#-OCTj9C-7BAllY2H3aRA:-OCXjoqX1Euo1Be3A5ei:b-4aq0ok) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab1a5046a4d07308646baa0bbd770005d045be0c/crates/blockifier/src/blockifier/block.rs#L108)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

No - I can not. I looked into it.
It is used in many locations, non-trivially.
</blockquote></details>

Oh I see. Let's leave them then.
Can you remove the `get_` prefix and the `_by_fee_type` suffix?
The [Rust style guide](https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter) says you shouldn't use `get_` and the `_by_fee_type` is also redundant because the fee type argument signifies that.

**Review by alonh5 — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2243)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware and @dorimedini-starkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Nov 28, 4:15 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2243).

**Pull request merged**
