### PR TITLE
feat(blockifier): define ChargedResources in CallInfo

### PR DESCRIPTION
**Pull request by TzahiTaub**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1722)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/execution/call_info.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAXVlYo-atGqzcjxTZg:-OAXVlYo-atGqzcjxTZh:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/eafa139c61ab02a4fac201ba75386446263c4fc4/crates/blockifier/src/execution/call_info.rs#L111)):*
> ```XML
> impl ChargedResources {
>     pub fn from_execution_resources(resources: ExecutionResources) -> Self {
>         Self { vm_resources: resources, gas_for_fee: GasAmount::default() }
> ```





_Suggestion:_
```XML
..Default::default()
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 363 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAXVw8j7kLvkNQB78iX:-OAXVw8j7kLvkNQB78iY:bvyb82y) ([raw file](https://github.com/starkware-libs/sequencer/blob/eafa139c61ab02a4fac201ba75386446263c4fc4/crates/blockifier/src/execution/entry_point.rs#L363)):*
> ```XML
> 
>     /// From the total amount of steps available for execution, deduct the steps consumed during
>     /// validation and the overhead steps required, among the rest, for fee transfer.
> ```

better?



_Suggestion:_
```XML
charged resources required 
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAXW8uk7a1gJlxJRxeg:-OAXW8uk7a1gJlxJRxeh:bmt1fjr) ([raw file](https://github.com/starkware-libs/sequencer/blob/eafa139c61ab02a4fac201ba75386446263c4fc4/crates/blockifier/src/execution/native/entry_point_execution.rs#L79)):*
> ```XML
>             vm_resources: ExecutionResources::default(),
>             gas_for_fee: GasAmount(gas_consumed),
>         },
> ```

this is already an implementation, right?
please add @noaov1 as reviewer



_Code quote:_
```XML
        charged_resources: ChargedResources {
            vm_resources: ExecutionResources::default(),
            gas_for_fee: GasAmount(gas_consumed),
        },
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1722)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/call_info.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAXVlYo-atGqzcjxTZg:-OAXuiKI5pbkAxaDDVkE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/eafa139c61ab02a4fac201ba75386446263c4fc4/crates/blockifier/src/execution/call_info.rs#L111)):*
> ```XML
> impl ChargedResources {
>     pub fn from_execution_resources(resources: ExecutionResources) -> Self {
>         Self { vm_resources: resources, gas_for_fee: GasAmount::default() }
> ```

Done.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 363 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAXVw8j7kLvkNQB78iX:-OAXxGl1AX8Hs73ERaGW:bl0g2pk) ([raw file](https://github.com/starkware-libs/sequencer/blob/eafa139c61ab02a4fac201ba75386446263c4fc4/crates/blockifier/src/execution/entry_point.rs#L363)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

better?
</blockquote></details>

Nope. I didn't change this comment because of this PR change, it's a by the way change - the "overhead steps" mentioned in the comment aren't only fee transfer related (e.g., every call have some constant steps from VC we charge here) so I just wanted to make it clearer. Actually from looking at the code, I don't really understand the connection to the fee transfer - do you know if the execute_txs_inner mapping has the fee transfer cost embedded in it?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1722)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 363 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAXVw8j7kLvkNQB78iX:-OAY3d9H21e-Lz2Wkd5L:b-dotjis) ([raw file](https://github.com/starkware-libs/sequencer/blob/eafa139c61ab02a4fac201ba75386446263c4fc4/crates/blockifier/src/execution/entry_point.rs#L363)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Nope. I didn't change this comment because of this PR change, it's a by the way change - the "overhead steps" mentioned in the comment aren't only fee transfer related (e.g., every call have some constant steps from VC we charge here) so I just wanted to make it clearer. Actually from looking at the code, I don't really understand the connection to the fee transfer - do you know if the execute_txs_inner mapping has the fee transfer cost embedded in it?
</blockquote></details>

IDK, question for Noa or Meshi I think

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1722)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 363 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAXVw8j7kLvkNQB78iX:-OAY7NY-Dyw_kdDd-EgF:b-q6rzms) ([raw file](https://github.com/starkware-libs/sequencer/blob/eafa139c61ab02a4fac201ba75386446263c4fc4/crates/blockifier/src/execution/entry_point.rs#L363)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

IDK, question for Noa or Meshi I think
</blockquote></details>

@noaov1 if you may

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1722)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAmDg2F-O_7o8Qr4JIl:-OAmDg2F-O_7o8Qr4JIm:b-ktfwku) (no related file):*
How do you plan to be backward compatible? Is that an issue?

___
___
*[`crates/blockifier/src/execution/entry_point.rs` line 363 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAXVw8j7kLvkNQB78iX:-OAm4ROO7QYE7WEakasy:bvwhomz) ([raw file](https://github.com/starkware-libs/sequencer/blob/eafa139c61ab02a4fac201ba75386446263c4fc4/crates/blockifier/src/execution/entry_point.rs#L363)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

@noaov1 if you may
</blockquote></details>

It does. 
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 413 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAm6CWJDxs6odAiWX7y:-OAm6CWJDxs6odAiWX7z:b-6np1ij) ([raw file](https://github.com/starkware-libs/sequencer/blob/4320ba8d7c6fa9e5157e98273002d5c9a4b71a41/crates/blockifier/src/execution/entry_point_execution.rs#L413)):*
> ```XML
>     let full_call_resources = &*syscall_handler.resources - &previous_resources;
>     let charged_resources = ChargedResources {
>         vm_resources: full_call_resources.filter_unused_builtins(),
> ```

I'm a bit confused.
Do we always charge for the vm resources? What about when the tracked resource is a sierra gas?  



_Code quote:_
```XML
 vm_resources: full_call_resources.filter_unused_builtins()
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAXW8uk7a1gJlxJRxeg:-OAm5XXeE5z_lQaYhat3:b-aboaf4) ([raw file](https://github.com/starkware-libs/sequencer/blob/eafa139c61ab02a4fac201ba75386446263c4fc4/crates/blockifier/src/execution/native/entry_point_execution.rs#L79)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is already an implementation, right?
please add @noaov1 as reviewer
</blockquote></details>

@TzahiTaub - why do you set here the ` gas_for_fee` as the `gas_consumed`

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1722)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAXW8uk7a1gJlxJRxeg:-OAmDmdh26J26h8wYWSK:bis00z) ([raw file](https://github.com/starkware-libs/sequencer/blob/eafa139c61ab02a4fac201ba75386446263c4fc4/crates/blockifier/src/execution/native/entry_point_execution.rs#L79)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

@TzahiTaub - why do you set here the ` gas_for_fee` as the `gas_consumed`
</blockquote></details>

Opps, please ignore.

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1722)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAmDg2F-O_7o8Qr4JIl:-OAmVOszExnKpLhhT7qP:bw4ilwu) (no related file):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

How do you plan to be backward compatible? Is that an issue?
</blockquote></details>

With what? txs with L2 gas are new for this version. The gas_consumed stays and before and is compatible with the OS. And VM mode txs will stay unchanged.

___
___
*[`crates/blockifier/src/execution/entry_point.rs` line 363 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAXVw8j7kLvkNQB78iX:-OAmURKOC2YhYucKUycG:bqgm5pv) ([raw file](https://github.com/starkware-libs/sequencer/blob/eafa139c61ab02a4fac201ba75386446263c4fc4/crates/blockifier/src/execution/entry_point.rs#L363)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It does.
</blockquote></details>

This is not related to the PR (but the comment) but does the fee_transfer resources cost change between transactions? Assuming it doesn't, why not have a separate resource constant for the fee transfer, instead of embedding it in every tx resources?
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 413 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAm6CWJDxs6odAiWX7y:-OAmUwf00mlLRe0WuEv7:b9fda81) ([raw file](https://github.com/starkware-libs/sequencer/blob/4320ba8d7c6fa9e5157e98273002d5c9a4b71a41/crates/blockifier/src/execution/entry_point_execution.rs#L413)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I'm a bit confused.
Do we always charge for the vm resources? What about when the tracked resource is a sierra gas?
</blockquote></details>

This is temporary, We'll have either vm_resources update or gas_for_fee update per call (gas_consumed will always be updated).

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1722)* status: 7 of 11 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAXW8uk7a1gJlxJRxeg:-OAmgaPj8PkSYvYrwnSI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/eafa139c61ab02a4fac201ba75386446263c4fc4/crates/blockifier/src/execution/native/entry_point_execution.rs#L79)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Opps, please ignore.
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1722)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 4 of 11 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1722)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAmDg2F-O_7o8Qr4JIl:-OAmtNH_7AwQlfdHnsTD:bu3049r) (no related file):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

With what? txs with L2 gas are new for this version. The gas_consumed stays and before and is compatible with the OS. And VM mode txs will stay unchanged.
</blockquote></details>

Oh, I see. Will only transactions that have signed non-trivial L2 gas bounds run in Sierra gas mode?  
Where is this indicated [here](https://github.com/starkware-libs/sequencer/blob/148bc1e268b781c3a509167c99e92f3f54edd139/crates/blockifier/src/execution/execution_utils.rs#L63-L64)?

___
___
*[`crates/blockifier/src/execution/entry_point.rs` line 363 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAXVw8j7kLvkNQB78iX:-OApwirV9_377ef0Gjoa:bdkt8ni) ([raw file](https://github.com/starkware-libs/sequencer/blob/eafa139c61ab02a4fac201ba75386446263c4fc4/crates/blockifier/src/execution/entry_point.rs#L363)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

This is not related to the PR (but the comment) but does the fee_transfer resources cost change between transactions? Assuming it doesn't, why not have a separate resource constant for the fee transfer, instead of embedding it in every tx resources?
</blockquote></details>

I am not sure. It should not.
What will we benefit from the separation? 
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 413 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAm6CWJDxs6odAiWX7y:-OApzmpz1PyHhsDykoN5:b8id9fq) ([raw file](https://github.com/starkware-libs/sequencer/blob/4320ba8d7c6fa9e5157e98273002d5c9a4b71a41/crates/blockifier/src/execution/entry_point_execution.rs#L413)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

This is temporary, We'll have either vm_resources update or gas_for_fee update per call (gas_consumed will always be updated).
</blockquote></details>

According to the tracked resources mode?

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1722)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAmDg2F-O_7o8Qr4JIl:-OAqOnon6xRr7nWZhBnt:b5aiwqc) (no related file):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Oh, I see. Will only transactions that have signed non-trivial L2 gas bounds run in Sierra gas mode?  
Where is this indicated [here](https://github.com/starkware-libs/sequencer/blob/148bc1e268b781c3a509167c99e92f3f54edd139/crates/blockifier/src/execution/execution_utils.rs#L63-L64)?
</blockquote></details>

It in a future PR (you're on it) - https://reviewable.io/reviews/starkware-libs/sequencer/1771#-

___
___
*[`crates/blockifier/src/execution/entry_point.rs` line 363 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAXVw8j7kLvkNQB78iX:-OAqOvXi-wWnL2oW7t44:bw57x9e) ([raw file](https://github.com/starkware-libs/sequencer/blob/eafa139c61ab02a4fac201ba75386446263c4fc4/crates/blockifier/src/execution/entry_point.rs#L363)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I am not sure. It should not.
What will we benefit from the separation?
</blockquote></details>

One point of truth for the fee transfer cost, it will also be clear from the file what part is of the fee transfer and what cost comes directly from the tx "behavior".
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 413 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1722#-OAm6CWJDxs6odAiWX7y:-OAqRe7v6yzZfznorpgn:bnz0y93) ([raw file](https://github.com/starkware-libs/sequencer/blob/4320ba8d7c6fa9e5157e98273002d5c9a4b71a41/crates/blockifier/src/execution/entry_point_execution.rs#L413)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

According to the tracked resources mode?
</blockquote></details>

Yes, according to the tracked resource either the VM resource will be updated, or the fee_for_gas.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1722)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1722)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
