### PR TITLE
refactor(blockifier,starknet_api): gas amount is now a u64, not a u128

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1175)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1175?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1175** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1175?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1174** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1174?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1173** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1173?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1172** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1172?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1175)* status: 0 of 20 files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_test.rs` line 346 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1175#-O8aSJ3zCujqS0ND0rhf:-O8aSJ3zCujqS0ND0rhg:b-jn1mb4) ([raw file](https://github.com/starkware-libs/sequencer/blob/6804f67f345833cb7e928730e28673b8295c3480/crates/blockifier/src/fee/fee_test.rs#L346)):*
> ```XML
> #[case::l1_data_saturates(0, u64::MAX, 0)]
> // TODO: Add L2 saturation case once `get_fee_by_gas_vector` implements L2 collection.
> fn test_get_fee_by_gas_vector_saturation(
> ```

this new test is easier than generalizing the above test:
now that gas amount is u64, it is more difficult to create a "saturating" scenario (amount * price > u128::MAX) by only controlling gas amount.



_Code quote:_
```XML
fn test_get_fee_by_gas_vector_saturation(
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 20 files at r1, 2 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1175)* status: 5 of 20 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 277 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1175#-O8cHTnU6tgq6Djo3py3:-O8cHTnU6tgq6Djo3py4:byfh83t) ([raw file](https://github.com/starkware-libs/sequencer/blob/743a1c65facfdae51b6bb246b2b8bb5ce27e8c33/crates/blockifier/src/execution/entry_point.rs#L277)):*
> ```XML
>                     block_info.gas_prices.get_l1_gas_price_by_fee_type(&tx_info.fee_type()),
>                 )
>                 .unwrap_or(GasAmount::MAX),
> ```

Why? what might go wrong?



_Code quote:_
```XML
.unwrap_or(GasAmount::MAX),
```
___
*[`crates/blockifier/src/fee/resources.rs` line 238 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1175#-O8cIrP16e294qIHI10c:-O8cIrP16e294qIHI10d:bkphrbc) ([raw file](https://github.com/starkware-libs/sequencer/blob/743a1c65facfdae51b6bb246b2b8bb5ce27e8c33/crates/blockifier/src/fee/resources.rs#L238)):*
> ```XML
>                 archival_gas_costs.gas_per_data_felt
>             );
>             u64::MAX
> ```

Please panic instead



_Code quote:_
```XML
        .unwrap_or_else(|_| {
            log::warn!(
                "Events gas cost overflowed: {} event keys (factor: {}), data length {} (at {} \
                 gas per felt).",
                self.event_summary.total_event_keys,
                archival_gas_costs.event_key_factor,
                self.event_summary.total_event_data_size,
                archival_gas_costs.gas_per_data_felt
            );
            u64::MAX
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1175)* status: 5 of 20 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 226 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1175#-O8cKR6_0Ewi57mYoMpg:-O8cKR6_0Ewi57mYoMph:b-kfgw4y) ([raw file](https://github.com/starkware-libs/sequencer/blob/743a1c65facfdae51b6bb246b2b8bb5ce27e8c33/crates/blockifier/src/fee/resources.rs#L226)):*
> ```XML
>                 * (resource_cost_to_u128_ratio(archival_gas_costs.event_key_factor)
>                     * self.event_summary.total_event_keys
>                     + self.event_summary.total_event_data_size))
> ```

Why not changing all of them to u64?



_Code quote:_
```XML
            (resource_cost_to_u128_ratio(archival_gas_costs.gas_per_data_felt)
                * (resource_cost_to_u128_ratio(archival_gas_costs.event_key_factor)
                    * self.event_summary.total_event_keys
                    + self.event_summary.total_event_data_size))
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1175)* status: 4 of 20 files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 277 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1175#-O8cHTnU6tgq6Djo3py3:-O8f37N77xQFdYb5TqPd:b-16ueyz) ([raw file](https://github.com/starkware-libs/sequencer/blob/743a1c65facfdae51b6bb246b2b8bb5ce27e8c33/crates/blockifier/src/execution/entry_point.rs#L277)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why? what might go wrong?
</blockquote></details>

if fee is u128::MAX and the gas price is 1 (or less than 2^64) then the result is larger than u64::MAX - which is now the inner type of GasAmount.
I'll implement and use a `saturating_div` function instead of the `unwrap_or`
___
*[`crates/blockifier/src/fee/resources.rs` line 226 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1175#-O8cKR6_0Ewi57mYoMpg:-O8f4DyoE-Y2ONA-C4uK:b5nx38j) ([raw file](https://github.com/starkware-libs/sequencer/blob/743a1c65facfdae51b6bb246b2b8bb5ce27e8c33/crates/blockifier/src/fee/resources.rs#L226)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why not changing all of them to u64?
</blockquote></details>

a worthy endeavor, but out of scope... I'll add a TODO to delete the ratio-converter function if and when possible
___
*[`crates/blockifier/src/fee/resources.rs` line 238 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1175#-O8cIrP16e294qIHI10c:-O8f4mULDhLEeGyAwT7R:b-7ybq5w) ([raw file](https://github.com/starkware-libs/sequencer/blob/743a1c65facfdae51b6bb246b2b8bb5ce27e8c33/crates/blockifier/src/fee/resources.rs#L238)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Please panic instead
</blockquote></details>

why...?
this flow is triggered after tx execution is complete, if we panic here when we can instead charge the maximal gas amount instead?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1175)* status: 4 of 20 files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 226 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1175#-O8cKR6_0Ewi57mYoMpg:-O8fV1E8AaM-Q1bzppCH:b-78yd5w) ([raw file](https://github.com/starkware-libs/sequencer/blob/743a1c65facfdae51b6bb246b2b8bb5ce27e8c33/crates/blockifier/src/fee/resources.rs#L226)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

a worthy endeavor, but out of scope... I'll add a TODO to delete the ratio-converter function if and when possible
</blockquote></details>

[opened a PR at the top of the stack](https://reviewable.io/reviews/starkware-libs/sequencer/1250) for this

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1175)* status: 4 of 20 files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 238 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1175#-O8cIrP16e294qIHI10c:-O8fsLjNAUvl8iF2BxaL:bo7yvtg) ([raw file](https://github.com/starkware-libs/sequencer/blob/743a1c65facfdae51b6bb246b2b8bb5ce27e8c33/crates/blockifier/src/fee/resources.rs#L238)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why...?
this flow is triggered after tx execution is complete, if we panic here when we can instead charge the maximal gas amount instead?
</blockquote></details>

in this context, I [opened a PR](https://reviewable.io/reviews/starkware-libs/sequencer/1255) (top of this stack... no point in reviewing now) to implement similar behavior when computing the max possible fee from given resource bounds

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 20 files at r1, 1 of 11 files at r2, 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1175)* status: 8 of 20 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 238 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1175#-O8cIrP16e294qIHI10c:-O8fwMQfEgdXNe23uggz:b-swtg4i) ([raw file](https://github.com/starkware-libs/sequencer/blob/743a1c65facfdae51b6bb246b2b8bb5ce27e8c33/crates/blockifier/src/fee/resources.rs#L238)):*
> why...?

It's a bug and should never happen. Warn hides bugs
___
*[`crates/starknet_api/src/transaction.rs` line 765 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1175#-O8fy9A0E_IksDqHEzIm:-O8fy9A13WtjEWBWeLQc:b-wf5xl8) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9e4553a4b1c778b1d989da6b170f3e55f099238/crates/starknet_api/src/transaction.rs#L765)):*
> ```XML
>     pub fn saturating_div(self, rhs: NonzeroGasPrice) -> GasAmount {
>         u64::try_from(self.0 / rhs.get().0).unwrap_or(u64::MAX).into()
>     }
> ```

Can you use `saturating_div` in more places?



_Suggestion:_
```XML
    pub fn saturating_div(self, rhs: NonzeroGasPrice) -> GasAmount {
        self.checked_div(rhs).unwrap_or(GasAmount::max)
    }
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1175)* status: 8 of 20 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 238 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1175#-O8cIrP16e294qIHI10c:-O8gGil7638CCdV248PW:bnktitm) ([raw file](https://github.com/starkware-libs/sequencer/blob/743a1c65facfdae51b6bb246b2b8bb5ce27e8c33/crates/blockifier/src/fee/resources.rs#L238)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

> why...?

It's a bug and should never happen. Warn hides bugs
</blockquote></details>

fixed [here](https://reviewable.io/reviews/starkware-libs/sequencer/1250) anyway, added the panic for now
___
*[`crates/starknet_api/src/transaction.rs` line 765 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1175#-O8fy9A0E_IksDqHEzIm:-O8g8ACnCcS-bAo3jpuQ:bcxkxas) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9e4553a4b1c778b1d989da6b170f3e55f099238/crates/starknet_api/src/transaction.rs#L765)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you use `saturating_div` in more places?
</blockquote></details>

I understand the requested diff, but I don't understand the comment

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1175)* status: 9 of 20 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 389 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1175#-O8kN1kC9m98Lelm2vZq:-O8kN1kC9m98Lelm2vZr:b8pqlmi) ([raw file](https://github.com/starkware-libs/sequencer/blob/1ff6bd447b61d662ad1a68fc58da53a54db6ea29/crates/blockifier/src/fee/resources.rs#L389)):*
> ```XML
>                     );
>                     GasAmount::MAX
>                 })
> ```

More readable:

```rust
        let data_gas_fee = self.l1_data_gas.nonzero_saturating_mul(data_gas_price);
        let data_gas_in_l1_gas_units = data_gas_fee.checked_div_ceil(l1_gas_price)
            .unwrap_or_else(|| {
                        log::warn!(
                            "Discounted L1 gas cost overflowed: division of L1 data fee {:?} by regular L1 gas price ({:?}) resulted in overflow.",
                            data_gas_fee,
                            l1_gas_price
                        );
                        GasAmount::MAX
                    })
        self.l1_gas.saturated_add(data_gas_in_l1_gas_units)
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1175)* status: 16 of 20 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 389 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1175#-O8kN1kC9m98Lelm2vZq:-O8kS1-w1iccNLhK1ufT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1ff6bd447b61d662ad1a68fc58da53a54db6ea29/crates/blockifier/src/fee/resources.rs#L389)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

More readable:

```rust
        let data_gas_fee = self.l1_data_gas.nonzero_saturating_mul(data_gas_price);
        let data_gas_in_l1_gas_units = data_gas_fee.checked_div_ceil(l1_gas_price)
            .unwrap_or_else(|| {
                        log::warn!(
                            "Discounted L1 gas cost overflowed: division of L1 data fee {:?} by regular L1 gas price ({:?}) resulted in overflow.",
                            data_gas_fee,
                            l1_gas_price
                        );
                        GasAmount::MAX
                    })
        self.l1_gas.saturated_add(data_gas_in_l1_gas_units)
```
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/block.rs` line 269 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1175#-O8kP8_gEQRgva7urKgm:-O8kQvt07fOzOkK4tS-C:b-7jzv7t) ([raw file](https://github.com/starkware-libs/sequencer/blob/1ff6bd447b61d662ad1a68fc58da53a54db6ea29/crates/starknet_api/src/block.rs#L269)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I guess that `u128::from` is not const, right?
</blockquote></details>

right

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 20 files at r1, 1 of 9 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1175#-:-O8kUER-9p0g8EyWc3yn:bnfp4nl)* status: 19 of 20 files reviewed, all discussions resolved

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1175)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
