### PR TITLE
test(mempool): flow test a commit block closes a nonce gap

### PR DESCRIPTION
**Pull request by MohammadNassar1**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/87)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/87)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/87#-O2dPFR_-W3Si9OH7N-O:-O2dPFR_-W3Si9OH7N-P:bcbkqi2) (no related file):*
Mempool PR:
https://reviewable.io/reviews/starkware-libs/mempool/518

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/87)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/87#-O2dQ8D_-sxDzPEBPaq9:-O2dQ8Da3JyuRS3Xkx57:b-lx82wr) (no related file):*
Should we add the case in which a hole is closed without the mempool ever seeing this transaction?

___
___
*[`crates/mempool/src/mempool_test.rs` line 542 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/87#-O2dQR7sANF0VKhlu-fz:-O2dQR7sANF0VKhlu-g-:b-81vqzr) ([raw file](https://github.com/starkware-libs/sequencer/blob/a357e3ca48920ac5a302a17e66373eb2d303f4d3/crates/mempool/src/mempool_test.rs#L542)):*
> ```XML
>         })
>     );
>     assert_eq_mempool_queue(&mempool, &[tx_nonce5]);
> ```

Do we want to check the mempool state after committing the block?
Also, we have [this](https://github.com/starkware-libs/mempool/blob/44e4e3509cd8f6bfb51102b0f997c1f0fbdffe57/crates/mempool/src/mempool_test.rs#L72) util, maybe we should add an error version of it?



_Suggestion:_
```XML
    // Assert: hole was indeed closed.
    assert_eq_mempool_queue(&mempool, &[tx_nonce5]);
    
    let res = mempool.add_tx(tx_input_nonce4);
    assert_eq!(
        res,
        Err(MempoolError::DuplicateNonce {
            address: ContractAddress::default(),
            nonce: Nonce(Felt::from(4))
        })
    );
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/87)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 542 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/87#-O2dQR7sANF0VKhlu-fz:-O2dX9zV5ptCTAh033Xb:buj5dao) ([raw file](https://github.com/starkware-libs/sequencer/blob/a357e3ca48920ac5a302a17e66373eb2d303f4d3/crates/mempool/src/mempool_test.rs#L542)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we want to check the mempool state after committing the block?
Also, we have [this](https://github.com/starkware-libs/mempool/blob/44e4e3509cd8f6bfb51102b0f997c1f0fbdffe57/crates/mempool/src/mempool_test.rs#L72) util, maybe we should add an error version of it?
</blockquote></details>

Done.
yeah, the util can be useful.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/87)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 542 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/87#-O2dQR7sANF0VKhlu-fz:-O2dXqviCfBYvDQp4UmN:bps2z6b) ([raw file](https://github.com/starkware-libs/sequencer/blob/a357e3ca48920ac5a302a17e66373eb2d303f4d3/crates/mempool/src/mempool_test.rs#L542)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
yeah, the util can be useful.
</blockquote></details>

Please add it.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/87)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 542 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/87#-O2dQR7sANF0VKhlu-fz:-O2doP6B2ZbyGjXooSNt:b-hchs7d) ([raw file](https://github.com/starkware-libs/sequencer/blob/a357e3ca48920ac5a302a17e66373eb2d303f4d3/crates/mempool/src/mempool_test.rs#L542)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please add it.
</blockquote></details>

Added [here](https://reviewable.io/reviews/starkware-libs/sequencer/108)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/87)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 540 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/87#-O2sJa8m-r3Ng_rjtiW7:-O2sJa8n5FIxbTyL63Qu:b-zdhd1o) ([raw file](https://github.com/starkware-libs/sequencer/blob/447a5f0f9541a7325b54a1079a45327e6bdd4a2e/crates/mempool/src/mempool_test.rs#L540)):*
> ```XML
>         res,
>         Err(MempoolError::DuplicateNonce {
>             address: ContractAddress::default(),
> ```

Let's use "0x0" somehow, so it's clear it's the same address (maybe a variable?). Same for nonce.



_Code quote:_
```XML
ContractAddress::default()
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/87)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 540 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/87#-O2sJa8m-r3Ng_rjtiW7:-O2yXpte7YHXfb2Csd6m:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/447a5f0f9541a7325b54a1079a45327e6bdd4a2e/crates/mempool/src/mempool_test.rs#L540)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's use "0x0" somehow, so it's clear it's the same address (maybe a variable?). Same for nonce.
</blockquote></details>

Done.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/87)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 540 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/87#-O2sJa8m-r3Ng_rjtiW7:-O3CxYhH0t_elku7iHKy:b-75i932) ([raw file](https://github.com/starkware-libs/sequencer/blob/447a5f0f9541a7325b54a1079a45327e6bdd4a2e/crates/mempool/src/mempool_test.rs#L540)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we define two variables and use them both for input and expected value creation?
</blockquote></details>

They use different types.
I still can do some `&str` type. But not sure if that what you mean.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/87)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 728 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/87#-O3D4XE74Tm-VoiJNecL:-O3D4XE74Tm-VoiJNecM:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ab3d0253b4ae83242c4a50a5a7e6bf618ec8b4e/crates/mempool/src/mempool_test.rs#L728)):*
> ```XML
>     // Test.
>     let state_changes =
>         HashMap::from([(contract_address!("0x0"), AccountState { nonce: Nonce(felt!(4_u16)) })]);
> ```





_Suggestion:_
```XML
4_u8
```
___
*[`crates/mempool/src/mempool_test.rs` line 741 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/87#-O3D4Zks9G90Y-qc_9ZU:-O3D4Zks9G90Y-qc_9ZV:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ab3d0253b4ae83242c4a50a5a7e6bf618ec8b4e/crates/mempool/src/mempool_test.rs#L741)):*
> ```XML
>         Err(MempoolError::DuplicateNonce {
>             address: contract_address!("0x0"),
>             nonce: Nonce(felt!("0x4")),
> ```





_Suggestion:_
```XML
4_u8
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/87)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 728 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/87#-O3D4XE74Tm-VoiJNecL:-O3D9UD57Ry9A4sLWYV9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ab3d0253b4ae83242c4a50a5a7e6bf618ec8b4e/crates/mempool/src/mempool_test.rs#L728)):*
> ```XML
>     // Test.
>     let state_changes =
>         HashMap::from([(contract_address!("0x0"), AccountState { nonce: Nonce(felt!(4_u16)) })]);
> ```

Done.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/87)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 741 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/87#-O3D4Zks9G90Y-qc_9ZU:-O3DAdSS20KnLrbROWwV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ab3d0253b4ae83242c4a50a5a7e6bf618ec8b4e/crates/mempool/src/mempool_test.rs#L741)):*
> ```XML
>         Err(MempoolError::DuplicateNonce {
>             address: contract_address!("0x0"),
>             nonce: Nonce(felt!("0x4")),
> ```

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/87)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
