### PR TITLE
fix(blockifier): enforce fee for allresourcebounds when l1 gas is 0

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/846)

### CODE REVIEW

**Review by nimrod-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/846#-:-O73LC8_3WDTzgq6-ccQ:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/846)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/objects.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/846#-O73j9g7Ci2UnI36WOLV:-O73j9g7Ci2UnI36WOLW:b-9yzglo) ([raw file](https://github.com/starkware-libs/sequencer/blob/9710f0e2f299b0c569a64f128ece178e9cada8a6/crates/blockifier/src/transaction/objects.rs#L120)):*
> ```XML
>                         + u128::from(l1_data_gas.max_amount) * l1_data_gas.max_price_per_unit
>                         > 0
>                 }
> ```

I think `ValidResourceBounds` should have a `max_possible_fee` method that returns the scalar product of the amounts and the prices; this will replace the two `match` arms here



_Code quote:_
```XML
                ValidResourceBounds::L1Gas(l1_bounds) => {
                    let max_amount: u128 = l1_bounds.max_amount.into();
                    max_amount * l1_bounds.max_price_per_unit > 0
                }
                ValidResourceBounds::AllResources(AllResourceBounds {
                    l1_gas,
                    l2_gas,
                    l1_data_gas,
                }) => {
                    u128::from(l1_gas.max_amount) * l1_gas.max_price_per_unit
                        + u128::from(l2_gas.max_amount) * l2_gas.max_price_per_unit
                        + u128::from(l1_data_gas.max_amount) * l1_data_gas.max_price_per_unit
                        > 0
                }
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/846#-O73irxe0k21gWeQ-aFc:-O73irxe0k21gWeQ-aFd:b-v6whpk) ([raw file](https://github.com/starkware-libs/sequencer/blob/9710f0e2f299b0c569a64f128ece178e9cada8a6/crates/blockifier/src/transaction/objects.rs#L121)):*
> ```XML
>                         > 0
>                 }
>             },
> ```

flatten the `match` please (or, see comment above)



_Suggestion:_
```XML
            TransactionInfo::Current(ValidResourceBounds::L1Gas(l1_bounds)) =>  {
                let max_amount: u128 = l1_bounds.max_amount.into();
                max_amount * l1_bounds.max_price_per_unit > 0
            }
            TransactionInfo::Current(ValidResourceBounds::AllResources(AllResourceBounds {
                    l1_gas,
                    l2_gas,
                    l1_data_gas,
            })) => {
                u128::from(l1_gas.max_amount) * l1_gas.max_price_per_unit
                    + u128::from(l2_gas.max_amount) * l2_gas.max_price_per_unit
                    + u128::from(l1_data_gas.max_amount) * l1_data_gas.max_price_per_unit
                    > 0
            },
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/846)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/objects.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/846#-O73j9g7Ci2UnI36WOLV:-O73w-hR5QSZdYnF78oq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9710f0e2f299b0c569a64f128ece178e9cada8a6/crates/blockifier/src/transaction/objects.rs#L120)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think `ValidResourceBounds` should have a `max_possible_fee` method that returns the scalar product of the amounts and the prices; this will replace the two `match` arms here
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/846#-O73irxe0k21gWeQ-aFc:-O73w2Y6BdrCZhTa_SgF:b-qaqd8d) ([raw file](https://github.com/starkware-libs/sequencer/blob/9710f0e2f299b0c569a64f128ece178e9cada8a6/crates/blockifier/src/transaction/objects.rs#L121)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

flatten the `match` please (or, see comment above)
</blockquote></details>

Took the above option.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/846)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/starknet_api/src/transaction.rs` line 998 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/846#-O7XvhcxDoHz8yY9uTGz:-O7XvhcxDoHz8yY9uTH-:b-tglii1) ([raw file](https://github.com/starkware-libs/sequencer/blob/e6feb76cb4e4fecf01fb4912a36bc0640201950d/crates/starknet_api/src/transaction.rs#L998)):*
> ```XML
>             }
>         }
>     }
> ```

wrap in this type, for clarity



_Suggestion:_
```XML
    pub fn max_possible_fee(&self) -> Fee {
        Fee(match self {
            ValidResourceBounds::L1Gas(l1_bounds) => {
                let max_amount: u128 = l1_bounds.max_amount.into();
                max_amount * l1_bounds.max_price_per_unit
            }
            ValidResourceBounds::AllResources(AllResourceBounds {
                l1_gas,
                l2_gas,
                l1_data_gas,
            }) => {
                u128::from(l1_gas.max_amount) * l1_gas.max_price_per_unit
                    + u128::from(l2_gas.max_amount) * l2_gas.max_price_per_unit
                    + u128::from(l1_data_gas.max_amount) * l1_data_gas.max_price_per_unit
            }
        })
    }
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/846)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/starknet_api/src/transaction.rs` line 998 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/846#-O7XvhcxDoHz8yY9uTGz:-O7YAQM_695pDF74erNK:b-v8vfir) ([raw file](https://github.com/starkware-libs/sequencer/blob/e6feb76cb4e4fecf01fb4912a36bc0640201950d/crates/starknet_api/src/transaction.rs#L998)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

wrap in this type, for clarity
</blockquote></details>

Done. Though the name fn name is probably clear enough ;)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/846#-:-O7YFJ-l2CPnRYLv41A4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/starknet_api/src/transaction.rs` line 998 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/846#-O7XvhcxDoHz8yY9uTGz:-O7YF0_jAfTtxisyUHHV:b-wefcxd) ([raw file](https://github.com/starkware-libs/sequencer/blob/e6feb76cb4e4fecf01fb4912a36bc0640201950d/crates/starknet_api/src/transaction.rs#L998)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done. Though the name fn name is probably clear enough ;)
</blockquote></details>

it's clear, but type enforcement is better.
it enforces that we don't perform addition/subtraction on different numeric types, for example (basic physics, can't add meters to seconds :) )

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/846)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware and @TzahiTaub)

**Pull request merged**
