### PR TITLE
fix(blockifier): update fee check error message

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/881)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
* **#881** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/881?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/881#-:-O78Grw32LVB14QIGBTO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/881#-:-O78P6Bb85oNAx2xPOjj:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @AvivYossef-starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/881#-:-O78Q5m8CH8DuytcxnQY:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @AvivYossef-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/881)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
