### PR TITLE
chore(tests-integration): rename flow test setup

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #1915
- #1914
- #1913
- #1912
- #1911 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
@giladchase - what do you think? I like this rename. 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1911#-:-OBLc4ol-FfmAw9jZKDA:b9rwwua)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1911#-OBLcEg09MaRqgAaldwN:-OBLcEg09MaRqgAaldwO:bm0pzr1) ([raw file](https://github.com/starkware-libs/sequencer/blob/03039b8bbdbf9564542f3f407bfc9aaa51dcd80d/crates/tests-integration/tests/end_to_end_test.rs#L0)):*
Should we rename this file as well?

**Comment by ArniStarkware** [comment]
*[`crates/tests-integration/tests/end_to_end_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1911#-OBLcEg09MaRqgAaldwN:-OBLeCvA4ZQoYnyDgujl:b-s0eb17) ([raw file](https://github.com/starkware-libs/sequencer/blob/03039b8bbdbf9564542f3f407bfc9aaa51dcd80d/crates/tests-integration/tests/end_to_end_test.rs#L)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Should we rename this file as well?
</blockquote></details>

addressed in #1914

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1911#-:-OBPphPy--SH2wGsYqix:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1911)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#1915](https://github.com/starkware-libs/sequencer/pull/1915)

**Pull request closed without merging**
