### PR TITLE
feat(blockifier): more informative 'tx too large' error in the bouncer

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1249)

### CODE REVIEW

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1249)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/bouncer.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1249#-O8fxUNx7HCGsL3xcGY-:-O8fxUNx7HCGsL3xcGY0:b77sitt) ([raw file](https://github.com/starkware-libs/sequencer/blob/a730305c63a98d292294d0a75d32a3ce9d602f25/crates/blockifier/src/bouncer.rs#L105)):*
> ```XML
>         } else {
>             Err(TransactionExecutionError::TransactionTooLarge {
>                 max_capacity: Box::new(*self),
> ```

why Box?



_Code quote:_
```XML
Box
```
___
*[`crates/blockifier/src/bouncer_test.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1249#-O8fwaY7BY-PRx8VwdbT:-O8fwaY7BY-PRx8VwdbU:b-m5q4p1) ([raw file](https://github.com/starkware-libs/sequencer/blob/f8d9ce181157f56ed04c5dfcfe6d45bce89f128b/crates/blockifier/src/bouncer_test.rs#L278)):*
> ```XML
>         "too_large" => assert_matches!(result, Err(
>                 TransactionExecutorError::TransactionExecutionError(
>                     TransactionExecutionError::TransactionTooLarge { max_capacity, .. }
> ```

can you also handle this value?



_Code quote:_
```XML
..
```
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 323 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1249#-O8fwzNbA2JLjlXGdDA0:-O8fwzNc0rJ6Bz684FQP:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/f8d9ce181157f56ed04c5dfcfe6d45bce89f128b/crates/blockifier/src/blockifier/transaction_executor_test.rs#L323)):*
> ```XML
>         results[1].as_ref().unwrap_err(),
>         TransactionExecutorError::TransactionExecutionError(
>             TransactionExecutionError::TransactionTooLarge { .. }
> ```

same



_Code quote:_
```XML
..
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1249)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1249#-O8fxUNx7HCGsL3xcGY-:-O8fxw7uDedUn3BC-qk5:b-tpjfbd) ([raw file](https://github.com/starkware-libs/sequencer/blob/a730305c63a98d292294d0a75d32a3ce9d602f25/crates/blockifier/src/bouncer.rs#L105)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why Box?
</blockquote></details>

otherwise clippy complains that the size of the error struct is too large
___
*[`crates/blockifier/src/bouncer_test.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1249#-O8fwaY7BY-PRx8VwdbT:-O8fzOcx3JpTHI45Jjaj:b-kh4hg4) ([raw file](https://github.com/starkware-libs/sequencer/blob/f8d9ce181157f56ed04c5dfcfe6d45bce89f128b/crates/blockifier/src/bouncer_test.rs#L278)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

can you also handle this value?
</blockquote></details>

yes, but now `verify_tx_weights_in_bounds` isn't actually tested (it's inlined in the test). better?
___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 323 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1249#-O8fwzNbA2JLjlXGdDA0:-O8g--Sj0sE8Y3XgBpzu:b22as9) ([raw file](https://github.com/starkware-libs/sequencer/blob/f8d9ce181157f56ed04c5dfcfe6d45bce89f128b/crates/blockifier/src/blockifier/transaction_executor_test.rs#L323)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

same
</blockquote></details>

this is harder - need to refactor the test to keep track of which tx is too large, and compute it's resources separately.
i think the coverage in the other error is enough, no? just check the variant in this test

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1249)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/bouncer_test.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1249#-O8fwaY7BY-PRx8VwdbT:-O8gKqjS06NbzX_WDn1e:bchtv7z) ([raw file](https://github.com/starkware-libs/sequencer/blob/f8d9ce181157f56ed04c5dfcfe6d45bce89f128b/crates/blockifier/src/bouncer_test.rs#L278)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes, but now `verify_tx_weights_in_bounds` isn't actually tested (it's inlined in the test). better?
</blockquote></details>

no, I don't think we should verify like this; I think it is just the same function running from both sides of the equation.
IIUC, builtin_counter, marked above, should be equal to the tx_weights.
___
*[`crates/blockifier/src/bouncer_test.rs` line 236 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1249#-O8gKklHCj0V0_ORtdW4:-O8gKklHCj0V0_ORtdW5:bvocdl0) ([raw file](https://github.com/starkware-libs/sequencer/blob/e33101fcb09194e9103871748e5445b87bafdcb1/crates/blockifier/src/bouncer_test.rs#L236)):*
> ```XML
>         (BuiltinName::poseidon, 1),
>         (BuiltinName::range_check, 1),
>     ]);
> ```

isn't this the tx_weight that should be eventually computed?



_Code quote:_
```XML
    let builtin_counter = HashMap::from([
        (BuiltinName::bitwise, 1),
        (BuiltinName::ecdsa, added_ecdsa),
        (BuiltinName::ec_op, 1),
        (BuiltinName::keccak, 1),
        (BuiltinName::pedersen, 1),
        (BuiltinName::poseidon, 1),
        (BuiltinName::range_check, 1),
    ]);
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1249)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer_test.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1249#-O8fwaY7BY-PRx8VwdbT:-O8gMdxp0PeO7lJh77wz:bn9luvk) ([raw file](https://github.com/starkware-libs/sequencer/blob/f8d9ce181157f56ed04c5dfcfe6d45bce89f128b/crates/blockifier/src/bouncer_test.rs#L278)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

no, I don't think we should verify like this; I think it is just the same function running from both sides of the equation.
IIUC, builtin_counter, marked above, should be equal to the tx_weights.
</blockquote></details>

they are not the same types... do you want me to do `*tx_size.builtin_weights == builtin_weights` and ignore the other bouncer weights?
___
*[`crates/blockifier/src/bouncer_test.rs` line 236 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1249#-O8gKklHCj0V0_ORtdW4:-O8gMXPk12wY5p2oCRLQ:b-onehkj) ([raw file](https://github.com/starkware-libs/sequencer/blob/e33101fcb09194e9103871748e5445b87bafdcb1/crates/blockifier/src/bouncer_test.rs#L236)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

isn't this the tx_weight that should be eventually computed?
</blockquote></details>

no, these are just the builtin weights; bouncer weights contains more things

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1249)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/bouncer_test.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1249#-O8fwaY7BY-PRx8VwdbT:-O8gND-v4fokFUdEhe0A:b173ip0) ([raw file](https://github.com/starkware-libs/sequencer/blob/f8d9ce181157f56ed04c5dfcfe6d45bce89f128b/crates/blockifier/src/bouncer_test.rs#L278)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

~builtin weights~ builtin counter
</blockquote></details>

I believer the other weights are zero, I don't see any code that adds them.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1249)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/bouncer.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1249#-O8gO8EC2Ak4w61q-TMg:-O8gO8EC2Ak4w61q-TMh:bg3syg0) ([raw file](https://github.com/starkware-libs/sequencer/blob/e33101fcb09194e9103871748e5445b87bafdcb1/crates/blockifier/src/bouncer.rs#L109)):*
> ```XML
>             })
>         }
>     }
> ```

thinking about it again, this is wrong because not every has_room == false implies the TransactionTooLargeError, is can also be BlockFull.



_Code quote:_
```XML
    pub fn has_room_or_err(&self, other: Self) -> TransactionExecutionResult<()> {
        if self.has_room(other) {
            Ok(())
        } else {
            Err(TransactionExecutionError::TransactionTooLarge {
                max_capacity: Box::new(*self),
                tx_size: Box::new(other),
            })
        }
    }
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1249)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1249#-O8gO8EC2Ak4w61q-TMg:-O8gPm-P3ISxmL9a_0eM:b7zpjoo) ([raw file](https://github.com/starkware-libs/sequencer/blob/e33101fcb09194e9103871748e5445b87bafdcb1/crates/blockifier/src/bouncer.rs#L109)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

thinking about it again, this is wrong because not every has_room == false implies the TransactionTooLargeError, is can also be BlockFull.
</blockquote></details>

ok, refactored a bit and renamed functions for clarity (the `verify_...` function was only used to check max capacity AFAICT)
___
*[`crates/blockifier/src/bouncer_test.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1249#-O8fwaY7BY-PRx8VwdbT:-O8gOzXR6mYaDybt68k5:bjl4r2w) ([raw file](https://github.com/starkware-libs/sequencer/blob/f8d9ce181157f56ed04c5dfcfe6d45bce89f128b/crates/blockifier/src/bouncer_test.rs#L278)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I believer the other weights are zero, I don't see any code that adds them.
</blockquote></details>

right! done

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1249)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by Yael-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1249#-:-O8k8rVg-toby6QUfQ95:bnfp4nl)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1249)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
