### PR TITLE
feat(consensus): add ProposalParts and related objects

### PR DESCRIPTION
**Pull request by guy-starkware**
This PR adds ProposalParts which is an enum that can be ProposalInit, Transactions, or ProposalFin.
This will be the content that we stream whenever Consensus wants to make a new proposal.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/916)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/916)* status: 4 of 5 files reviewed, 9 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/papyrus_protobuf/src/consensus.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7OgGkS0rxFnrI6-kS4:-O7OgGkS0rxFnrI6-kS5:b-mflpae) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c8eae937ac3f4ee2d03c3a053b02ebae0419462/crates/papyrus_protobuf/src/consensus.rs#L75)):*
> ```XML
>     pub round: u32,
>     /// The last round that was valid.
>     pub valid_round: u32, // TODO(guyn): should this be optional?
> ```

option



_Code quote:_
```XML
    pub valid_round: u32, // TODO(guyn): should this be optional?
```
___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7OhUlXBJhz_64yB8T6:-O7OhUlXBJhz_64yB8T7:b-ooje39) ([raw file](https://github.com/starkware-libs/sequencer/blob/583280c5ecd42818966930fda9522abf5031eba1/crates/papyrus_protobuf/src/converters/consensus_test.rs#L68)):*
> ```XML
> 
> auto_impl_get_test_instance!(
>     pub struct ProposalInit {
> ```

Is there nowhere convenient we can put this for reuse?



_Code quote:_
```XML
auto_impl_get_test_instance!(
    pub struct ProposalInit {
```
___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 219 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7OhpOsCoOX9G_i3eOD:-O7OhpOsCoOX9G_i3eOE:bb3jsox) ([raw file](https://github.com/starkware-libs/sequencer/blob/583280c5ecd42818966930fda9522abf5031eba1/crates/papyrus_protobuf/src/converters/consensus_test.rs#L219)):*
> ```XML
>         }
>         _ => {}
>     }
> ```

Let's either fix the real thing or use a helper function. We're repeating something that adds a lot of mess to the test.



_Code quote:_
```XML
    // Below is a hack: The problem is that when we deserialize a Transaction, if it has an
    // AllResources variant, it will turn into a L1Gas variant if all the gas prices are zero.
    // So I will intentionally make them non-zero, but the real solution is to make the randomly
    // generated structs contain random values instead of zero.
    // TODO(guyn): add random values to the structs generated by get_test_instance
    let transaction = &mut transaction_batch.transactions[0];
    match transaction {
        Transaction::Declare(DeclareTransaction::V3(DeclareTransactionV3 {
            resource_bounds,
            ..
        }))
        | Transaction::Invoke(InvokeTransaction::V3(InvokeTransactionV3 {
            resource_bounds, ..
        }))
        | Transaction::DeployAccount(DeployAccountTransaction::V3(DeployAccountTransactionV3 {
            resource_bounds,
            ..
        })) => {
            if let ValidResourceBounds::AllResources(ref mut bounds) = resource_bounds {
                bounds.l2_gas.max_amount = 1;
            }
        }
        _ => {}
    }
```
___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 227 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7OiGmQ8mZArfb1ZXy-:-O7OiGmRCaV8d7uOtaTT:b80b4t6) ([raw file](https://github.com/starkware-libs/sequencer/blob/583280c5ecd42818966930fda9522abf5031eba1/crates/papyrus_protobuf/src/converters/consensus_test.rs#L227)):*
> ```XML
> #[test]
> fn convert_proposal_fin_to_vec_u8_and_back() {
>     let mut rng = get_rng();
> ```

We should expose what the RNG seed was in the case of failure to make debug easier. Maybe just print it out at the beginning of the test?



_Code quote:_
```XML
    let mut rng = get_rng();
```
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7Ofrdn--BJeBxG-7qa:-O7Ofrdn--BJeBxG-7qb:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c8eae937ac3f4ee2d03c3a053b02ebae0419462/crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto#L26)):*
> ```proto
>     uint32        round      = 4;
>     // This is optional since a vote can be NIL.
>     optional Hash block_hash = 5;
> ```





_Suggestion:_
```proto
    // This is optional since a vote can be NIL.
    optional Hash proposal_content_id = 5;
```
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7Of4sf1xjD4R5yz4kG:-O7Of4sf1xjD4R5yz4kH:b-gwemlm) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c8eae937ac3f4ee2d03c3a053b02ebae0419462/crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto#L48)):*
> ```proto
>     uint64 height = 1;
>     uint32 round = 2;
>     uint32 valid_round = 3;  // TODO(guyn): should this be optional? 
> ```

yes, optional



_Code quote:_
```proto
    uint32 valid_round = 3;  // TODO(guyn): should this be optional?
```
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7OfPAg9GFmoOYUBBkf:-O7OfPAg9GFmoOYUBBkg:b-xly9gv) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c8eae937ac3f4ee2d03c3a053b02ebae0419462/crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto#L58)):*
> ```proto
> message ProposalFin {
>     Hash block_hash = 1;
> }
> ```

This will eventually get replaced when we have signatures.



_Suggestion:_
```proto
message ProposalFin {
    // Identifies all of the content streamed in the proposal.
    Hash proposal_content_id = 1;
}
```
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto` line 70 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7Og4AmEOM0khfBC-Ec:-O7Og4AmEOM0khfBC-Ed:bqb4twm) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c8eae937ac3f4ee2d03c3a053b02ebae0419462/crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto#L70)):*
> ```proto
>         ProposalFin fin = 3;
>     }
> }
> ```

Let's switch the order to fin is after init.
This is because those are the 2 fixed messages for consensus. The other messages can be changed without much impact on consensus.



_Suggestion:_
```proto
message ProposalPart {
    oneof message {
        ProposalInit init = 1;
        ProposalFin fin = 2;
        TransactionBatch transactions = 3;
    }
}
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 0 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7OiaWz5XECNdbW_faD:-O7OiaWz5XECNdbW_faE:b3s7r1b) ([raw file](https://github.com/starkware-libs/sequencer/blob/583280c5ecd42818966930fda9522abf5031eba1/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L0)):*
Should this be in a different PR?

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/916)* status: 4 of 5 files reviewed, 9 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/papyrus_protobuf/src/consensus.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7OgGkS0rxFnrI6-kS4:-O7Onb-f5BMkhWNI7W8j:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c8eae937ac3f4ee2d03c3a053b02ebae0419462/crates/papyrus_protobuf/src/consensus.rs#L75)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

option
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7OhUlXBJhz_64yB8T6:-O7Om6L-1z5nUJ2bJ1Lz:bbtwltm) ([raw file](https://github.com/starkware-libs/sequencer/blob/583280c5ecd42818966930fda9522abf5031eba1/crates/papyrus_protobuf/src/converters/consensus_test.rs#L68)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Is there nowhere convenient we can put this for reuse?
</blockquote></details>

I don't know. What do you think? 
___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 219 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7OhpOsCoOX9G_i3eOD:-O7Op3QtCyFnncIZsYm-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/583280c5ecd42818966930fda9522abf5031eba1/crates/papyrus_protobuf/src/converters/consensus_test.rs#L219)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's either fix the real thing or use a helper function. We're repeating something that adds a lot of mess to the test.
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 227 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7OiGmQ8mZArfb1ZXy-:-O7OmgnREvrnNZbJYjzu:biqseqb) ([raw file](https://github.com/starkware-libs/sequencer/blob/583280c5ecd42818966930fda9522abf5031eba1/crates/papyrus_protobuf/src/converters/consensus_test.rs#L227)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

We should expose what the RNG seed was in the case of failure to make debug easier. Maybe just print it out at the beginning of the test?
</blockquote></details>

I think that already happens (I don't remember if it is the `get_rng` or one of the other test utilities that does it. 
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7Ofrdn--BJeBxG-7qa:-O7OpBrE4g69-rG8-XYo:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c8eae937ac3f4ee2d03c3a053b02ebae0419462/crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto#L26)):*
> ```proto
>     uint32        round      = 4;
>     // This is optional since a vote can be NIL.
>     optional Hash block_hash = 5;
> ```

Done.
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7Of4sf1xjD4R5yz4kG:-O7OpIQQ1cr6RPlX8Qj0:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c8eae937ac3f4ee2d03c3a053b02ebae0419462/crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto#L48)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

yes, optional
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7OfPAg9GFmoOYUBBkf:-O7OpOzJCQTMXCz-TwUH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c8eae937ac3f4ee2d03c3a053b02ebae0419462/crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto#L58)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This will eventually get replaced when we have signatures.
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto` line 70 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7Og4AmEOM0khfBC-Ec:-O7OpPYH54zd3-zx2Tu8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c8eae937ac3f4ee2d03c3a053b02ebae0419462/crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto#L70)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's switch the order to fin is after init.
This is because those are the 2 fixed messages for consensus. The other messages can be changed without much impact on consensus.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line  at r4](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7OiaWz5XECNdbW_faD:-O7On24P02tGOCdykLc0:b-7g7nvj) ([raw file](https://github.com/starkware-libs/sequencer/blob/583280c5ecd42818966930fda9522abf5031eba1/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Should this be in a different PR?
</blockquote></details>

yes!

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/916)* status: all files reviewed, 3 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7OhUlXBJhz_64yB8T6:-O7P0YFc2DdeKXGTyC-3:bz9b98q) ([raw file](https://github.com/starkware-libs/sequencer/blob/583280c5ecd42818966930fda9522abf5031eba1/crates/papyrus_protobuf/src/converters/consensus_test.rs#L68)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

I don't know. What do you think?
</blockquote></details>

Look for other examples in the protobuf crate.
___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 38 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7P0GxYDGVlSOgt7ESa:-O7P0GxYDGVlSOgt7ESb:b-y517eo) ([raw file](https://github.com/starkware-libs/sequencer/blob/f2cd2f00b3d6dac86795bd9e157fbcb2fad56d52/crates/papyrus_protobuf/src/converters/consensus_test.rs#L38)):*
> ```XML
> // generated structs contain random values instead of zero.
> // TODO(guyn): add random values to the structs generated by get_test_instance
> fn add_gas_values_to_transaction_temporary_hack(transactions: &mut Vec<Transaction>) {
> ```

The TODO is enough



_Suggestion:_
```XML
add_gas_values_to_transaction
```
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7OfPAg9GFmoOYUBBkf:-O7P0r5m-E3wkd9gmuYr:bz13za1) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c8eae937ac3f4ee2d03c3a053b02ebae0419462/crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto#L58)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What about the comment?

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/916)* status: all files reviewed, 3 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7OhUlXBJhz_64yB8T6:-O7P2FMX56ECzC0En6fl:b4uc6l2) ([raw file](https://github.com/starkware-libs/sequencer/blob/583280c5ecd42818966930fda9522abf5031eba1/crates/papyrus_protobuf/src/converters/consensus_test.rs#L68)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Look for other examples in the protobuf crate.
</blockquote></details>

So there's `papyrus_test_utils` and indeed there are a lot of such implementations. But I thought it would be easier to have the specific objects needed for the specific tests in the same place. But I will go with whatever you think is best... 
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7OfPAg9GFmoOYUBBkf:-O7P1pW_EJjdjhJRgIQY:bvkywa3) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c8eae937ac3f4ee2d03c3a053b02ebae0419462/crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto#L58)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

What about the comment?
</blockquote></details>

Sorry, misread that suggestion! Added now.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/916)* status: all files reviewed, 3 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O7OhUlXBJhz_64yB8T6:-O7P5h6u7FVdbDmIxq08:b97cian) ([raw file](https://github.com/starkware-libs/sequencer/blob/583280c5ecd42818966930fda9522abf5031eba1/crates/papyrus_protobuf/src/converters/consensus_test.rs#L68)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

So there's `papyrus_test_utils` and indeed there are a lot of such implementations. But I thought it would be easier to have the specific objects needed for the specific tests in the same place. But I will go with whatever you think is best...
</blockquote></details>

What about the example in `sync.rs`?

**Review by matan-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/916)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/916)* status: all files reviewed, 1 unresolved discussion (waiting on @guy-starkware)

___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto` line 71 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O81fkWC9BseZ8mkC4bl:-O81fkWC9BseZ8mkC4bm:b2ni2nk) ([raw file](https://github.com/starkware-libs/sequencer/blob/815a3de90c905c4063f1172ce7ac271785035267/crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto#L71)):*
> ```proto
>         ProposalFin fin = 2;
>         TransactionBatch transactions = 3;
>         
> ```

fix



_Code quote:_
```proto
·······
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/916)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto` line 71 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O81fkWC9BseZ8mkC4bl:-O81gE4R7SRMrKyhelwL:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/815a3de90c905c4063f1172ce7ac271785035267/crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto#L71)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

fix
</blockquote></details>

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/916)* status: all files reviewed, 1 unresolved discussion (waiting on @guy-starkware)

___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto` line 71 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O81fkWC9BseZ8mkC4bl:-O81sRpO2LGshpFGbJeH:blg659d) ([raw file](https://github.com/starkware-libs/sequencer/blob/815a3de90c905c4063f1172ce7ac271785035267/crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto#L71)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Reviewable is showing the trailing whitespace on the line above now

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/916)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 3 of 7 files at r9, 4 of 4 files at r14.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/916)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @guy-starkware)

___
*[`crates/papyrus_protobuf/src/consensus.rs` line 86 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O9cUryI4xMcOILByAIC:-O9cUryI4xMcOILByAID:b-30si2r) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f81da57211f3581580323eefddb24848eadcc92/crates/papyrus_protobuf/src/consensus.rs#L86)):*
> ```XML
> }
> 
> /// The propsal is done when receiving this fin message, which contains the block hash.
> ```

Please add a TODO to consider changing the content ID type 



_Code quote:_
```XML
/// The propsal is done when receiving this fin message, which contains the block hash.
```
___
*[`crates/papyrus_protobuf/src/consensus.rs` line 105 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O9cY0Qa9xMIEzsRlS_9:-O9cY0Qa9xMIEzsRlS_A:b-6spn74) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f81da57211f3581580323eefddb24848eadcc92/crates/papyrus_protobuf/src/consensus.rs#L105)):*
> ```XML
> 
> #[cfg(any(feature = "testing", test))]
> auto_impl_get_test_instance! {
> ```

Why did you move this here?
How about adding a test_instances module instead?



_Code quote:_
```XML
#[cfg(any(feature = "testing", test))]
auto_impl_get_test_instance! {
```
___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 28 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O9cYTYs5gI9Cj2O507O:-O9cYTYs5gI9Cj2O507P:brv6pjy) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f81da57211f3581580323eefddb24848eadcc92/crates/papyrus_protobuf/src/converters/consensus_test.rs#L28)):*
> ```XML
> // So I will intentionally make them non-zero, but the real solution is to make the randomly
> // generated structs contain random values instead of zero.
> // TODO(guyn): add random values to the structs generated by get_test_instance
> ```

Consider



_Suggestion:_
```XML
// Hack: intentionally make gas prices non-zero since when we deserialize a Transaction, if it has an
// AllResources variant, it will turn into a L1Gas variant if all the gas prices are zero.
// TODO(guyn): add random values to the structs generated by get_test_instance
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/916)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/papyrus_protobuf/src/consensus.rs` line 86 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O9cUryI4xMcOILByAIC:-O9ceCbKAugtEaDX0ecQ:b-q9xha7) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f81da57211f3581580323eefddb24848eadcc92/crates/papyrus_protobuf/src/consensus.rs#L86)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please add a TODO to consider changing the content ID type
</blockquote></details>

OK, but I'm not sure why. 
___
*[`crates/papyrus_protobuf/src/consensus.rs` line 105 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O9cY0Qa9xMIEzsRlS_9:-O9ceJl19GZu2mJjtpw9:b-meyb5o) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f81da57211f3581580323eefddb24848eadcc92/crates/papyrus_protobuf/src/consensus.rs#L105)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why did you move this here?
How about adding a test_instances module instead?
</blockquote></details>

I think this was the same style that was done in other places. But I think moving it to a separate file is better.

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 6 files at r15, 4 of 4 files at r18.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/916)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @guy-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 27 at r18](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O9cyI7qEQvv48IaURV6:-O9cyI7qEQvv48IaURV7:bk7rhya) ([raw file](https://github.com/starkware-libs/sequencer/blob/8be4b7ee663e568269a5d8cf27824559b13ba917/crates/papyrus_protobuf/src/converters/consensus_test.rs#L27)):*
> ```XML
> 
> #[path = "test_instances.rs"]
> mod test_instances;
> ```

Consider moving to `converters/mod.rs`



_Code quote:_
```XML
#[path = "test_instances.rs"]
mod test_instances;
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/916)* status: 5 of 9 files reviewed, all discussions resolved (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 27 at r18](https://reviewable.io/reviews/starkware-libs/sequencer/916#-O9cyI7qEQvv48IaURV6:-O9dTO9k22iUTbP5uKa5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8be4b7ee663e568269a5d8cf27824559b13ba917/crates/papyrus_protobuf/src/converters/consensus_test.rs#L27)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider moving to `converters/mod.rs`
</blockquote></details>

Done.

**Review by guy-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r14, 1 of 6 files at r15, 1 of 4 files at r18, 3 of 4 files at r19, 2 of 2 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/916)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Pull request merged**
