### PR TITLE
chore(blockifier): add is_legacy method

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/196)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/196?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#197** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/197?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#196** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/196?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#195** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/195?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#194** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/194?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#184** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/184?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#183** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/183?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#182** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/182?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#181** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/181?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#180** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/180?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#179** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/179?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by TzahiTaub — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/196)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware, @meship-starkware, and @nimrod-starkware)

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/196#-:-O40dpV03DIB-HtBaJlX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware, @meship-starkware, and @nimrod-starkware)

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Aug 11, 11:28 AM EDT**: @dorimedini-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/196).

**Pull request merged**
