### PR TITLE
feat(network): impl network server channel struct

### PR DESCRIPTION
**Pull request by eitanm-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/388)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/388)* status: all files reviewed, 11 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 642 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40ExTwCkRBDHIlVp_F:-O40ExTwCkRBDHIlVp_G:b-8z62n1) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_network/src/network_manager/mod.rs#L642)):*
> ```XML
> 
> pub type ReportSender = oneshot::Sender<()>;
> type ReportReceiver = oneshot::Receiver<()>;
> ```

Try to move private types and structs below the public ones
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 709 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40F3BE7DdWGusa-Yxe:-O40F3BE7DdWGusa-Yxf:b9r1uzd) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_network/src/network_manager/mod.rs#L709)):*
> ```XML
> impl<Response: TryFrom<Bytes>> ClientResponsesManager<Response> {
>     pub fn report_peer(self) {
>         error!("Reporting peer");
> ```

Consider using warn instead of error
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 743 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40FKPMEnxBFPNEk-if:-O40FKPMEnxBFPNEk-ig:b-ckzp4h) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_network/src/network_manager/mod.rs#L743)):*
> ```XML
>     <Query as TryFrom<Bytes>>::Error: Clone,
> {
>     #[cfg(feature = "testing")]
> ```

Add TODO to add a test utility for creating channels for tests and removing this function
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 749 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40FVf-EZVMgICzsM93:-O40FVf-EZVMgICzsM94:bdo2rkc) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_network/src/network_manager/mod.rs#L749)):*
> ```XML
> }
> 
> impl<Query: TryFrom<Bytes> + Clone, Response> Stream for SqmrServerReceiver<Query, Response>
> ```

Remove the bound here, as you've put it already below
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 781 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40FmVV3H1zxPCSExyq:-O40FmVW61zBkKgnF6-b:b-9vtb5z) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_network/src/network_manager/mod.rs#L781)):*
> ```XML
> {
>     pub fn query(&self) -> Result<Query, <Query as TryFrom<Bytes>>::Error> {
>         self.query.clone()
> ```

Do not clone here, and remove all the bounds for clone
The return type should be &Result<...>

You can clone in p2p_sync_server instead if needed
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 782 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40FtuI3AdOoadmXX66:-O40FtuI3AdOoadmXX67:b-r55pjr) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_network/src/network_manager/mod.rs#L782)):*
> ```XML
>     pub fn query(&self) -> Result<Query, <Query as TryFrom<Bytes>>::Error> {
>         self.query.clone()
>     }
> ```

newline between methods
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 853 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40GGITB7_vO1bqZb0n:-O40GGITB7_vO1bqZb0o:b-qdwagc) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_network/src/network_manager/mod.rs#L853)):*
> ```XML
>     <Query as TryFrom<Bytes>>::Error: Clone,
> {
>     fn from(payload: SqmrServerPayloadForNetwork) -> Self {
> ```

Rename this to SqmrServerPayload, or add a TODO to rename it and rename SqmrClientPayloadForNetwork to SqmrClientPayload once you erase SqmrClientPayload
___
*[`crates/papyrus_p2p_sync/src/server/mod.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40HMzMCh0OEeIf7Km2:-O40HMzMCh0OEeIf7Km3:b-toplph) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_p2p_sync/src/server/mod.rs#L119)):*
> ```XML
>         loop {
>             tokio::select! {
>                 result = header_receiver.next() => {
> ```

Unrelated to this PR, but let's fix this
result implies this is a `Result<...>`, but this is an `Option<...>`. Rename these to maybe_server_query_manager
___
*[`crates/papyrus_p2p_sync/src/server/mod.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40ICdq-m9445v-HsLN:-O40ICdq-m9445v-HsLO:b9ovfcn) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_p2p_sync/src/server/mod.rs#L165)):*
> ```XML
>     Query: From<TQuery>,
> {
>     let query = server_query_manager.query();
> ```

Erase this line
___
*[`crates/papyrus_p2p_sync/src/server/mod.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40I1xk98tcBcYbNA9-:-O40I1xk98tcBcYbNA90:b9ovfcn) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_p2p_sync/src/server/mod.rs#L168)):*
> ```XML
>     match query {
>         Ok(query) => {
>             let query = Query::from(query);
> ```

Erase this line
___
*[`crates/papyrus_p2p_sync/src/server/mod.rs` line 384 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40IIdY7xHbX7nbYX1w:-O40IIdY7xHbX7nbYX1x:b-krbxvq) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_p2p_sync/src/server/mod.rs#L384)):*
> ```XML
>     Query: From<TQuery>,
> {
>     let query = server_query_manager.query().expect("Failed to parse inbound query.");
> ```

use ? instead of expect and add a TODO to report the query

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/388)* status: all files reviewed, 10 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 642 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40ExTwCkRBDHIlVp_F:-O40M5Yy7yvXMvrZOQp_:b-d8nmz8) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_network/src/network_manager/mod.rs#L642)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Try to move private types and structs below the public ones
</blockquote></details>

Done. Left Broadcast below because it's context doesn't belong here imo
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 743 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40FKPMEnxBFPNEk-if:-O40MU3J5euIgzzlB75e:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_network/src/network_manager/mod.rs#L743)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to add a test utility for creating channels for tests and removing this function
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 749 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40FVf-EZVMgICzsM93:-O40MZKzA8RCkFtnyBI_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_network/src/network_manager/mod.rs#L749)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove the bound here, as you've put it already below
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 781 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40FmVV3H1zxPCSExyq:-O40jzvq5azsn8eQo3S3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_network/src/network_manager/mod.rs#L781)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Do not clone here, and remove all the bounds for clone
The return type should be &Result<...>

You can clone in p2p_sync_server instead if needed
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 782 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40FtuI3AdOoadmXX66:-O40NIqM1hEDIF8uFNxM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_network/src/network_manager/mod.rs#L782)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

newline between methods
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 853 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40GGITB7_vO1bqZb0n:-O40Ne7p8bD-telVbW_g:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_network/src/network_manager/mod.rs#L853)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename this to SqmrServerPayload, or add a TODO to rename it and rename SqmrClientPayloadForNetwork to SqmrClientPayload once you erase SqmrClientPayload
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/server/mod.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40HMzMCh0OEeIf7Km2:-O40O7l177iSvoDC0vNX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_p2p_sync/src/server/mod.rs#L119)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Unrelated to this PR, but let's fix this
result implies this is a `Result<...>`, but this is an `Option<...>`. Rename these to maybe_server_query_manager
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/server/mod.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40ICdq-m9445v-HsLN:-O40ik6-3Yu85gvDtAII:b-ouifq9) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_p2p_sync/src/server/mod.rs#L165)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Erase this line
</blockquote></details>

cloned it
___
*[`crates/papyrus_p2p_sync/src/server/mod.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40I1xk98tcBcYbNA9-:-O40iiG95d38uCmj0X6d:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_p2p_sync/src/server/mod.rs#L168)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Erase this line
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/server/mod.rs` line 384 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40IIdY7xHbX7nbYX1w:-O40k1Pf0gacxBgPeYFN:bjkis91) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_p2p_sync/src/server/mod.rs#L384)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

use ? instead of expect and add a TODO to report the query
</blockquote></details>

cant use ? because different errors. query validity is checked before it gets to this function regardless. do you think we should still make changes?

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/388)* status: all files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware)

___
*[`crates/papyrus_p2p_sync/src/server/mod.rs` line 384 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40IIdY7xHbX7nbYX1w:-O40mN5Q3eAxRTHCfL9Y:b-gl96fc) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_p2p_sync/src/server/mod.rs#L384)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

cant use ? because different errors. query validity is checked before it gets to this function regardless. do you think we should still make changes?
</blockquote></details>

Change the message to "query result contains error even though it was previously checked to have no errors")

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/388)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/server/mod.rs` line 384 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/388#-O40IIdY7xHbX7nbYX1w:-O40mf6t6K9uq2EpT1j4:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aba34ae03a060f0209283731bf5bf0f9214deb5a/crates/papyrus_p2p_sync/src/server/mod.rs#L384)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change the message to "query result contains error even though it was previously checked to have no errors")
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/388#-:-O40myjg6cuIKdyxzrLy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Pull request merged**
