### PR TITLE
feat(batcher): add validate flow to proposal manager

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
* **#1951** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1951?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Yael-Starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1951)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1951#-OBV5ie_5iJ0NhBaOQ2j:-OBVPnGU2zXtfYfjME80:b-gamqun) ([raw file](https://github.com/starkware-libs/sequencer/blob/f9fdf7cc69f21d77eff9f49da0ede7e7173a1906/crates/batcher/src/proposal_manager.rs#L96)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

If we want to use the same error we should change it's name.
</blockquote></details>

I think ProposalError is too general since we have GetProposalResultError and StartHeightError.

changed to GenerateProposalError, which is not perfect because it is similar to Build.

I think the the problem with the terminology comes from the api, we have build or validate proposal, while it should have been propose and validate. And then we could have used the word build as describing both.
wdyt?

btw , opened a separate PR for this name change.
___
*[`crates/batcher/src/proposal_manager.rs` line 200 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1951#-OBV6JFb4cGZAC3cl8FD:-OBVPle1E-YL8h-5wBt4:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f9fdf7cc69f21d77eff9f49da0ede7e7173a1906/crates/batcher/src/proposal_manager.rs#L200)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Extracting into a function would be a great preliminary PR :)
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1951#-OBV624GDrmueHisxrNe:-OBVPgnTA8F1N77AEiLK:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/f9fdf7cc69f21d77eff9f49da0ede7e7173a1906/crates/batcher/src/proposal_manager.rs#L88)):*
> ```XML
>     ) -> Result<(), BuildProposalError>;
> 
>     // TODO delete allow dead code once the batcher uses this code.
> ```

done

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1951#-:-OBVphsX9zt4EDc4TCKt:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager_test.rs` line 233 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1951#-OBVpO-D5VA6JM9UIYB7:-OBVpO-E0-jyuEWLbsLD:b-29medh) ([raw file](https://github.com/starkware-libs/sequencer/blob/687d0d489d20fcb512a804526e379329333e06f1/crates/batcher/src/proposal_manager_test.rs#L233)):*
> ```XML
>     // Build and validate multiple proposal consecutively (awaiting on them to
>     // make sure they finished successfully).
>     build_proposal_and_await_completion(&mut proposal_manager, ProposalId(0)).await;
> ```

Maybe interleave them?

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1951)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @alonh5 and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager_test.rs` line 233 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1951#-OBVpO-D5VA6JM9UIYB7:-OBWBXgjCTdyGE7Sz3DN:b-r6a6e7) ([raw file](https://github.com/starkware-libs/sequencer/blob/687d0d489d20fcb512a804526e379329333e06f1/crates/batcher/src/proposal_manager_test.rs#L233)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Maybe interleave them?
</blockquote></details>

done,  unfortunately lines are too long now to see it aligned nicely together.
Do you think it's worth shortening names for this?

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1951)* status: all files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/batcher/src/proposal_manager_test.rs` line 202 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1951#-OBZ_p0WC76E5liEptgW:-OBZ_p0WC76E5liEptgX:b-x1evap) ([raw file](https://github.com/starkware-libs/sequencer/blob/00b5e9bf6b21b19553ddaa76962e965bea7e1a34/crates/batcher/src/proposal_manager_test.rs#L202)):*
> ```XML
> #[rstest]
> #[tokio::test]
> async fn validate_proposal_fails_without_start_height(
> ```

Consider using a test case in a single test
___
*[`crates/batcher/src/proposal_manager_test.rs` line 230 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1951#-OBZaP_G1UmJFLjGFcud:-OBZaP_H29qtNohUfgO9:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/00b5e9bf6b21b19553ddaa76962e965bea7e1a34/crates/batcher/src/proposal_manager_test.rs#L230)):*
> ```XML
> #[rstest]
> #[tokio::test]
> async fn validate_proposal_success(
> ```

same

**Review by alonh5 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1951)* status: all files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/batcher/src/proposal_manager_test.rs` line 233 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1951#-OBVpO-D5VA6JM9UIYB7:-OB_9qY21tLM1vW123pw:b-uor86j) ([raw file](https://github.com/starkware-libs/sequencer/blob/687d0d489d20fcb512a804526e379329333e06f1/crates/batcher/src/proposal_manager_test.rs#L233)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

done,  unfortunately lines are too long now to see it aligned nicely together.
Do you think it's worth shortening names for this?
</blockquote></details>

Maybe remove the `_and_await_completion` suffix to the function names. I don't think it's important to the test reader in this case.

**Review by alonh5 — APPROVED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1951)* status: all files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 119 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1951#-OB_GmhkDAZvZABvwJzp:-OB_GmhkDAZvZABvwJzq:b6fdsfn) ([raw file](https://github.com/starkware-libs/sequencer/blob/233986fe767ac16427e36a1666e646d017c2abd9/crates/starknet_batcher/src/proposal_manager_test.rs#L119)):*
> ```XML
> }
> 
> async fn build_proposal_and_await_completion(
> ```

Remove these?



_Code quote:_
```XML
_and_await_completion
```
___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 39 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1951#-OB_FekR1RbI-tH7XeyB:-OB_FekR1RbI-tH7XeyC:b-zfueax) ([raw file](https://github.com/starkware-libs/sequencer/blob/b065f329ffcd9839f2e9463860df5dce04d51d1b/crates/starknet_batcher/src/proposal_manager_test.rs#L39)):*
> ```XML
>     tokio::sync::mpsc::unbounded_channel()
> }
> ```

Restore blank line.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1951)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 39 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1951#-OB_FekR1RbI-tH7XeyB:-OBeCeDDDJKZKoMdLqVk:b-7rl0jd) ([raw file](https://github.com/starkware-libs/sequencer/blob/b065f329ffcd9839f2e9463860df5dce04d51d1b/crates/starknet_batcher/src/proposal_manager_test.rs#L39)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Restore blank line.
</blockquote></details>

done.
___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 119 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1951#-OB_GmhkDAZvZABvwJzp:-OBeCQah9bfmHuJKbhRB:b-7rl0jd) ([raw file](https://github.com/starkware-libs/sequencer/blob/233986fe767ac16427e36a1666e646d017c2abd9/crates/starknet_batcher/src/proposal_manager_test.rs#L119)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Remove these?
</blockquote></details>

done.
___
*[`crates/batcher/src/proposal_manager_test.rs` line 233 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1951#-OBVpO-D5VA6JM9UIYB7:-OBeCSAY0fRq_tmUkDc4:b-7rl0jd) ([raw file](https://github.com/starkware-libs/sequencer/blob/687d0d489d20fcb512a804526e379329333e06f1/crates/batcher/src/proposal_manager_test.rs#L233)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Maybe remove the `_and_await_completion` suffix to the function names. I don't think it's important to the test reader in this case.
</blockquote></details>

done.
___
*[`crates/batcher/src/proposal_manager_test.rs` line 202 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1951#-OBZ_p0WC76E5liEptgW:-OBeCXWB9XyNwowwvalW:bftfqyq) ([raw file](https://github.com/starkware-libs/sequencer/blob/00b5e9bf6b21b19553ddaa76962e965bea7e1a34/crates/batcher/src/proposal_manager_test.rs#L202)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider using a test case in a single test
</blockquote></details>

couldn't find a simple solution
___
*[`crates/batcher/src/proposal_manager_test.rs` line 230 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1951#-OBZaP_G1UmJFLjGFcud:-OBeCcy3-h3Ow6nfVdM_:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/00b5e9bf6b21b19553ddaa76962e965bea7e1a34/crates/batcher/src/proposal_manager_test.rs#L230)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

same
</blockquote></details>

same

**Pull request merged**
