### PR TITLE
chore(infra): share get_absolute_path infra util with snapi test utils

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2075?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2075** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2075?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2074** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2074?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2073** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2073?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2052** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2052?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2026** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2026?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2020** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2020?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2075)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/infra_utils/src/path.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2075#-OC3hkr59VnAoGH9PDBq:-OC3hkr59VnAoGH9PDBr:b-uynq7i) ([raw file](https://github.com/starkware-libs/sequencer/blob/f154aa3988eddbabaf30956205f00a806f85b8b7/crates/infra_utils/src/path.rs#L6)):*
> ```XML
> 
> pub static PATH_TO_CARGO_MANIFEST_DIR: LazyLock<Option<PathBuf>> =
>     LazyLock::new(|| env::var("CARGO_MANIFEST_DIR").ok().map(|dir| Path::new(&dir).into()));
> ```

Please make this a private function, and create a function that returns the cloned path. The benefit of that would be that
1. users wouldn't have to clone the path whenever they use it
2. we can later add code that returns this path even when running not through cargo



_Code quote:_
```XML
pub static PATH_TO_CARGO_MANIFEST_DIR: LazyLock<Option<PathBuf>> =
    LazyLock::new(|| env::var("CARGO_MANIFEST_DIR").ok().map(|dir| Path::new(&dir).into()));
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2075)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/infra_utils/src/path.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2075#-OC3hkr59VnAoGH9PDBq:-OC3tJrAAt-TosAOcPkz:b-amnbx0) ([raw file](https://github.com/starkware-libs/sequencer/blob/f154aa3988eddbabaf30956205f00a806f85b8b7/crates/infra_utils/src/path.rs#L6)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please make this a private function, and create a function that returns the cloned path. The benefit of that would be that
1. users wouldn't have to clone the path whenever they use it
2. we can later add code that returns this path even when running not through cargo
</blockquote></details>

Done.
We can move functionality from `get_absolute_path` into a function called: `manifest_dir`, in another PR.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 14 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2075#-:-OCCgHJwC87Ko3_S9bD3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Nov 21, 2:52 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2075).

**Pull request merged**
