### PR TITLE
Merge main-v0.13.2 into main

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/169)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
[Src](https://github.com/starkware-libs/blockifier/compare/a9dc431be4445b8963c5d46f81023aaaa2b662bd..main-v0.13.2#diff-cc008c341d769f5978bc4948b7978b31ad46bdffd4f0a312ef6da15164a369e6) [Dst](https://github.com/starkware-libs/blockifier/compare/a9dc431be4445b8963c5d46f81023aaaa2b662bd..main#diff-cc008c341d769f5978bc4948b7978b31ad46bdffd4f0a312ef6da15164a369e6) .github/workflows/committer_ci.yml
[Src](https://github.com/starkware-libs/blockifier/compare/a9dc431be4445b8963c5d46f81023aaaa2b662bd..main-v0.13.2#diff-ed087b73aa98a868bd0fa5a5c491edcd4aab43953ef127dd5d92b7f7dc13bb09) [Dst](https://github.com/starkware-libs/blockifier/compare/a9dc431be4445b8963c5d46f81023aaaa2b662bd..main#diff-ed087b73aa98a868bd0fa5a5c491edcd4aab43953ef127dd5d92b7f7dc13bb09) crates/sequencing/papyrus_consensus/src/state_machine.rs

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r11, 15 of 15 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/169)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by asmaastarkware — APPROVED** [review]
:lgtm: from consensus review

> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/169#-:-O2y6z_73pwQ804Kdi8n:b-hl6j3s)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware and @TzahiTaub)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/169)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware and @TzahiTaub)

**Pull request merged**
