### PR TITLE
chore(ci): tune boostraping cache

### PR DESCRIPTION
**Pull request by alon-dotan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/949)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/949)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware)

___
*[`.github/actions/install_rust/action.yml` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/949#-O7TMcn1Byx3Ia65mXTb:-O7TMcn1Byx3Ia65mXTc:b-eu1ftn) ([raw file](https://github.com/starkware-libs/sequencer/blob/4da1f566cff0f18adbfdd6c61d8e2e6491943cad/.github/actions/install_rust/action.yml#L3)):*
> ```YAML
> name: Bootsrap rust installation
> description: Bootsrap rust installation
> runs:
> ```

1. newline
2. it's not just rust installation, right? If you're adding a docstring please make it descriptive



_Suggestion:_
```YAML
name: Bootsrap rust installation
description: Bootsrap rust installation

runs:
```
___
*[`.github/actions/install_rust/action.yml` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/949#-O7TMRMg-GL6DP9_YHJt:-O7TMRMg-GL6DP9_YHJu:bx2j96o) ([raw file](https://github.com/starkware-libs/sequencer/blob/4da1f566cff0f18adbfdd6c61d8e2e6491943cad/.github/actions/install_rust/action.yml#L8)):*
> ```YAML
>     - uses: moonrepo/setup-rust@v1
>       with:
>         cache-base: (main|main-v0.13.2)
> ```

if regex has full support let's catch all future release branches as well



_Suggestion:_
```YAML
main-v[0-9].*
```

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/949)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`.github/actions/install_rust/action.yml` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/949#-O7TMcn1Byx3Ia65mXTb:-O7TPU378LJwscSMpYvc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4da1f566cff0f18adbfdd6c61d8e2e6491943cad/.github/actions/install_rust/action.yml#L3)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. newline
2. it's not just rust installation, right? If you're adding a docstring please make it descriptive
</blockquote></details>

Done.
___
*[`.github/actions/install_rust/action.yml` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/949#-O7TMRMg-GL6DP9_YHJt:-O7TPoEu0dp8TubNOPTU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4da1f566cff0f18adbfdd6c61d8e2e6491943cad/.github/actions/install_rust/action.yml#L8)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if regex has full support let's catch all future release branches as well
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/949)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware)

___
*[`.github/actions/install_rust/action.yml` line 9 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/949#-O7Tzw_o8NFJuLMO_M7s:-O7Tzw_o8NFJuLMO_M7t:b-21yn2r) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b81414930a6ccca92dafc1296a91ff4d07741b1/.github/actions/install_rust/action.yml#L9)):*
> ```YAML
>     - uses: moonrepo/setup-rust@v1
>       with:
>         cache-base: (main-v[0-9].*)
> ```

currently doesn't cover `main`



_Suggestion:_
```YAML
(main|main-v[0-9].*)
```

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/949)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`.github/actions/install_rust/action.yml` line 9 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/949#-O7Tzw_o8NFJuLMO_M7s:-O7Xnpmk4m12HIQ4d3ko:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b81414930a6ccca92dafc1296a91ff4d07741b1/.github/actions/install_rust/action.yml#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

currently doesn't cover `main`
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/949)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware)

___
*[`.github/actions/install_rust/action.yml` line 9 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/949#-O7Tzw_o8NFJuLMO_M7s:-O7XwVEpAZLXFEY_cNxt:bb7mv1b) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b81414930a6ccca92dafc1296a91ff4d07741b1/.github/actions/install_rust/action.yml#L9)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

push

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/949)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware)

___
*[`.github/actions/install_rust/action.yml` line 9 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/949#-O7Tzw_o8NFJuLMO_M7s:-O7XwZmaBgcbOAzIX1BE:bwdkx5y) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b81414930a6ccca92dafc1296a91ff4d07741b1/.github/actions/install_rust/action.yml#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

push
</blockquote></details>

or just `main(-v[0-9].*)?`

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/949)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`.github/actions/install_rust/action.yml` line 9 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/949#-O7Tzw_o8NFJuLMO_M7s:-O7Y93LB0Xw8vAser495:b-el339i) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b81414930a6ccca92dafc1296a91ff4d07741b1/.github/actions/install_rust/action.yml#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

or just `main(-v[0-9].*)?`
</blockquote></details>

Done.!!!

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/949#-:-O7YEtreDRIFBu5rx8t6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/949)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Pull request merged**
