### PR TITLE
chore(starknet_sequencer_infra): add dynamic logging util fn

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #2424
- #2385
- #2384
- #2329
- #2332
- #2328 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by lev-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2328)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/infra_utils/src/tracing.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2328#-OD6Ueoe9_GywedQhkxW:-OD6Ueoe9_GywedQhkxX:b-kyby49) ([raw file](https://github.com/starkware-libs/sequencer/blob/f6705a7e838f928fa00a1094b8490f9dc05a6439/crates/infra_utils/src/tracing.rs#L4)):*
> ```XML
> 
> /// Dynamically set tracing level of a message.
> pub struct DynamicLogger {
> ```

Why this is DynamicLogger?
Your previous version, As I remember, could log every message with a different TraceLevel
___
*[`crates/infra_utils/src/tracing.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2328#-OD6V5BC7CzOsMUBzG1C:-OD6V5BC7CzOsMUBzG1D:bgt47rx) ([raw file](https://github.com/starkware-libs/sequencer/blob/f6705a7e838f928fa00a1094b8490f9dc05a6439/crates/infra_utils/src/tracing.rs#L23)):*
> ```XML
>         };
> 
>         match self.level {
> ```

I understand that 'match' is quite effective, but it doesn't seem pretty.

I would suggest another solution but its up to you



_Code snippet:_
```XML
use tracing::{debug, error, info, trace, warn}; 

pub struct DynamicLogger {
    base_msg: Option<String>,
    log_message_fn: Box<dyn Fn(&str)>,
}

impl DynamicLogger {
    fn new(base_msg: Option<String>, log_message_fn: Box<dyn Fn(&str)>) -> Self {
        Self { base_msg, log_message_fn }
    }

    fn log_message(&self, msg: &str) {
        let message = match &self.base_msg {
            Some(base_msg) => format!("{}: {}", base_msg, msg),
            None => msg.to_string(),
        };
        (self.log_message_fn)(&message);
    }
}

pub enum TraceLevel {
    Trace,
    Debug,
    Info,
    Warn,
    Error,
}

pub fn create_logger(base_msg: Option<String>, level: TraceLevel) -> DynamicLogger {
    let log_fn: Box<dyn Fn(&str)> = match level {
        TraceLevel::Trace => Box::new(|msg| trace!("{}", msg)),
        TraceLevel::Debug => Box::new(|msg| debug!("{}", msg)),
        TraceLevel::Info => Box::new(|msg| info!("{}", msg)),
        TraceLevel::Warn => Box::new(|msg| warn!("{}", msg)),
        TraceLevel::Error => Box::new(|msg| error!("{}", msg)),
    };

    DynamicLogger::new(base_msg, log_fn)
}
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2328)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/infra_utils/src/tracing.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2328#-OD6Ueoe9_GywedQhkxW:-OD6fIWr9khEeeHJQ0Be:b-hsxir8) ([raw file](https://github.com/starkware-libs/sequencer/blob/f6705a7e838f928fa00a1094b8490f9dc05a6439/crates/infra_utils/src/tracing.rs#L4)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

Why this is DynamicLogger?
Your previous version, As I remember, could log every message with a different TraceLevel
</blockquote></details>

It determines the logging level at runtime and not at compile time.
Happy to take name suggestions.

**Review by lev-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2328)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/infra_utils/src/tracing.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2328#-OD6Ueoe9_GywedQhkxW:-ODAtRio6JGqyoHEvvO9:bll2lh3) ([raw file](https://github.com/starkware-libs/sequencer/blob/f6705a7e838f928fa00a1094b8490f9dc05a6439/crates/infra_utils/src/tracing.rs#L4)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

It determines the logging level at runtime and not at compile time.
Happy to take name suggestions.
</blockquote></details>

AdaptiveLogger, FlexibleLogger, and my favorite CustomLogger?

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2328)* status: all files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/infra_utils/src/tracing.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2328#-OD6Ueoe9_GywedQhkxW:-ODB-8yDEnEqtecEfk9T:b-d2ze6p) ([raw file](https://github.com/starkware-libs/sequencer/blob/f6705a7e838f928fa00a1094b8490f9dc05a6439/crates/infra_utils/src/tracing.rs#L4)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

AdaptiveLogger, FlexibleLogger, and my favorite CustomLogger?
</blockquote></details>

Added a refactor in https://github.com/starkware-libs/sequencer/pull/2424

**Review by lev-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2328#-:-ODBEBGk1MDHQWXUAOZG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#2424](https://github.com/starkware-libs/sequencer/pull/2424)

**Pull request closed without merging**
