### PR TITLE
chore(batcher): simplify class info convertion

### PR DESCRIPTION
**Pull request by alonh5**

### CODE REVIEW

**Comment by alonh5** [comment]
* **#1916** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1916?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

See this PR: #1858 .

@avivg-starkware  - note this might conflict with you.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1916#-:-OBLUWVf-z3_fbmwVikX:b-h8rpa0)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by alonh5 — COMMENTED** [review]
Oh that's even better. Is it going to merge soon? If so I'll delete this PR

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1916#-:-OBLW-Lq5z6ucQJCtqwi:b-i153ef)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
It might take a while, I assume about a week.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1916#-:-OBLeufQ-LyIPgFpjzfx:bz8rt4h)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
This PR is no longer relevant. It was covered by the PR discussed above.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1916#-:-OBUgckF5MeNQqgzBCF9:bgccj4i)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request closed without merging**
