### PR TITLE
refactor(starknet_api): add l2 gas to gas vector

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/786)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
* **#786** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/786?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 5 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/786)* status: 7 of 10 files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware, @nimrod-starkware, and @ShahakShama)

___
*[`crates/papyrus_execution/src/objects.rs` line 392 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/786#-O6zF_qF0m9NE5pMb_29:-O6zF_qF0m9NE5pMb_2A:b-1q9ty) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec907490007862ccdbf38ff72ecd250a61468254/crates/papyrus_execution/src/objects.rs#L392)):*
> ```XML
>         da_gas_consumed: StarknetApiGasVector {
>             l1_gas: l1_gas.try_into().map_err(|_| ExecutionError::GasConsumedOutOfRange)?,
>             l2_gas: l1_gas.try_into().map_err(|_| ExecutionError::GasConsumedOutOfRange)?,
> ```

what's this...?



_Code quote:_
```XML
 l2_gas: l1_gas
```
___
*[`crates/starknet_api/src/execution_resources.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/786#-O6zFhEF0T34xos_kp2y:-O6zFhEF0T34xos_kp2z:bj6kmfh) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec907490007862ccdbf38ff72ecd250a61468254/crates/starknet_api/src/execution_resources.rs#L10)):*
> ```XML
>     pub l1_gas: u64,
>     pub l1_data_gas: u64,
>     #[serde(default)]
> ```

is this the desired behavior? when deserializing an old object, set l2 gas to zero? @ShahakShama 



_Code quote:_
```XML
#[serde(default)]
```
___
*[`crates/starknet_api/src/block_hash/test_utils.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/786#-O6zFrYQAca_xv374Qdr:-O6zFrYQAca_xv374Qds:btc09zh) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec907490007862ccdbf38ff72ecd250a61468254/crates/starknet_api/src/block_hash/test_utils.rs#L27)):*
> ```XML
>         events: vec![],
>         execution_status,
>         gas_consumed: GasVector { l1_gas: 16580, l2_gas: 0, l1_data_gas: 32 },
> ```

the l1 gas amounts seem oddly specific; why is the l2 value zero?



_Code quote:_
```XML
l1_gas: 16580, l2_gas: 0, l1_data_gas: 32
```
___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/786#-O6zFvWlA_juSFNQkwKy:-O6zFvWlA_juSFNQkwKz:b-rtagwg) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec907490007862ccdbf38ff72ecd250a61468254/crates/starknet_client/src/reader/objects/block_test.rs#L162)):*
> ```XML
> async fn to_starknet_api_block_and_version_0_13_1() {
>     let raw_block = read_resource_file("reader/block_post_0_13_1.json");
>     println!("{}", raw_block);
> ```

delete



_Code quote:_
```XML
println!("{}", raw_block);
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/786)* status: 5 of 10 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @ShahakShama)

___
*[`crates/papyrus_execution/src/objects.rs` line 392 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/786#-O6zF_qF0m9NE5pMb_29:-O6z_4HM3dos_UVSBsIY:b2nhlrh) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec907490007862ccdbf38ff72ecd250a61468254/crates/papyrus_execution/src/objects.rs#L392)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what's this...?
</blockquote></details>

Ops
___
*[`crates/starknet_api/src/block_hash/test_utils.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/786#-O6zFrYQAca_xv374Qdr:-O6z_LMgA_hu8UAKHt38:b-xc4xhq) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec907490007862ccdbf38ff72ecd250a61468254/crates/starknet_api/src/block_hash/test_utils.rs#L27)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the l1 gas amounts seem oddly specific; why is the l2 value zero?
</blockquote></details>

It's some test utils for the block hash . I haven't thought it's important, so I just put 0 there.
___
*[`crates/starknet_client/src/reader/objects/block_test.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/786#-O6zFvWlA_juSFNQkwKy:-O6zagjg1kARu2sDD3xu:b2ng590) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec907490007862ccdbf38ff72ecd250a61468254/crates/starknet_client/src/reader/objects/block_test.rs#L162)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>


:)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/786)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware, @nimrod-starkware, @ShahakShama, and @yoavGrs)

___
*[`crates/starknet_api/src/block_hash/test_utils.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/786#-O6zFrYQAca_xv374Qdr:-O6zjEzjA7bVqjcCyjkn:b-v21qu) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec907490007862ccdbf38ff72ecd250a61468254/crates/starknet_api/src/block_hash/test_utils.rs#L27)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

It's some test utils for the block hash . I haven't thought it's important, so I just put 0 there.
</blockquote></details>

@yoavGrs is this value ok?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/786)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @nimrod-starkware, and @ShahakShama)

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 2 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/786)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/starknet_api/src/execution_resources.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/786#-O6zFhEF0T34xos_kp2y:-O787iPT4LQxTo5KXqa8:b-vmmkcj) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec907490007862ccdbf38ff72ecd250a61468254/crates/starknet_api/src/execution_resources.rs#L10)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this the desired behavior? when deserializing an old object, set l2 gas to zero? @ShahakShama
</blockquote></details>

I think yes

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/786)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
