### PR TITLE
refactor(mempool): add tx! macro

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/889)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/889)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/889#-O79JjzJAonPIpk2tl5e:-O79JjzJAonPIpk2tl5f:b-pkhk8h) ([raw file](https://github.com/starkware-libs/sequencer/blob/0069df022767f9bb7ec3c8b300a4ffeb7c9baa5e/crates/mempool/src/mempool_test.rs#L155)):*
> ```XML
> 
> /// Creates a valid input for mempool's `add_tx` with optional default values.
> /// Usage:
> ```

Comments became outdated; usages can be seen in tests.



_Code quote:_
```XML
Usage:
```
___
*[`crates/mempool/src/mempool_test.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/889#-O79Jpa7D0dMt3ab43Du:-O79Jpa803Db5tog4Q1h:bxabplx) ([raw file](https://github.com/starkware-libs/sequencer/blob/0069df022767f9bb7ec3c8b300a4ffeb7c9baa5e/crates/mempool/src/mempool_test.rs#L175)):*
> ```XML
>         let account = Account { sender_address, state: AccountState {nonce: account_nonce}};
> 
>         let tx = create_executable_tx(
> ```

Using `tx!(...)` macro instead.



_Code quote:_
```XML
create_executable_tx
```
___
*[`crates/mempool/src/mempool_test.rs` line 193 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/889#-O79Jt0i76gP6UPAlQ_h:-O79Jt0i76gP6UPAlQ_i:b-x3xp2h) ([raw file](https://github.com/starkware-libs/sequencer/blob/0069df022767f9bb7ec3c8b300a4ffeb7c9baa5e/crates/mempool/src/mempool_test.rs#L193)):*
> ```XML
>     (tip: $tip:expr, tx_hash: $tx_hash:expr, sender_address: $sender_address:expr) => {
>         add_tx_input!(tip: $tip, tx_hash: $tx_hash, sender_address: $sender_address, tx_nonce: 0_u8, account_nonce: 0_u8)
>     };
> ```

Deleted rules are unused.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/889)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 193 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/889#-O79Jt0i76gP6UPAlQ_h:-O79NZPXB8Ey6MHXFlil:bfavshn) ([raw file](https://github.com/starkware-libs/sequencer/blob/0069df022767f9bb7ec3c8b300a4ffeb7c9baa5e/crates/mempool/src/mempool_test.rs#L193)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Deleted rules are unused.
</blockquote></details>

is it possible to split to another PR?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/889)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/889#-O79Jpa7D0dMt3ab43Du:-O79PR3e-KL2UsZJ12R3:bguycpe) ([raw file](https://github.com/starkware-libs/sequencer/blob/0069df022767f9bb7ec3c8b300a4ffeb7c9baa5e/crates/mempool/src/mempool_test.rs#L175)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Using `tx!(...)` macro instead.
</blockquote></details>

Is this function still being used anywhere, or can it be removed?

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/889)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/889#-O79Jpa7D0dMt3ab43Du:-O79Pbnr74BehuXRKlCq:bd6z79x) ([raw file](https://github.com/starkware-libs/sequencer/blob/0069df022767f9bb7ec3c8b300a4ffeb7c9baa5e/crates/mempool/src/mempool_test.rs#L175)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Is this function still being used anywhere, or can it be removed?
</blockquote></details>

In the `tx!(...)` macro (+ probably gateway tests).
___
*[`crates/mempool/src/mempool_test.rs` line 193 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/889#-O79Jt0i76gP6UPAlQ_h:-O79P5-9Eo5BT36wTMJN:bp6ero7) ([raw file](https://github.com/starkware-libs/sequencer/blob/0069df022767f9bb7ec3c8b300a4ffeb7c9baa5e/crates/mempool/src/mempool_test.rs#L193)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

is it possible to split to another PR?
</blockquote></details>

Done, [PTAL](https://reviewable.io/reviews/starkware-libs/sequencer/891).

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/889)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 182 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/889#-O79T4M46X9Rij5OVhnT:-O79T4M46X9Rij5OVhnU:b-7hbpla) ([raw file](https://github.com/starkware-libs/sequencer/blob/37ff471258265ce08662448c41dcf3c4ae1b8a54/crates/mempool/src/mempool_test.rs#L182)):*
> ```XML
> 
> /// Creates an input for `add_tx` with the given field subset (the rest receive default values).
> macro_rules! add_tx_input {
> ```

wdyt?



_Suggestion:_
```XML
mempool_input
```
___
*[`crates/mempool/src/mempool_test.rs` line 799 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/889#-O79TaM86DVnhQOUzDZ1:-O79TaM86DVnhQOUzDZ2:bsaunmx) ([raw file](https://github.com/starkware-libs/sequencer/blob/37ff471258265ce08662448c41dcf3c4ae1b8a54/crates/mempool/src/mempool_test.rs#L799)):*
> ```XML
> fn test_commit_block_from_different_leader() {
>     // Setup.
>     let tx_address0_nonce3 = tx!(tip: 1, tx_hash: 1, sender_address: "0x0", tx_nonce: 3_u8);
> ```

Now it's not clear that this transaction is not ready.



_Code quote:_
```XML
let tx_address0_nonce3 = tx!(tip: 1, tx_hash: 1, sender_address: "0x0", tx_nonce: 3_u8);
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/889)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 182 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/889#-O79T4M46X9Rij5OVhnT:-O79VUC-6t4D9C68oPYB:b-lhl4sh) ([raw file](https://github.com/starkware-libs/sequencer/blob/37ff471258265ce08662448c41dcf3c4ae1b8a54/crates/mempool/src/mempool_test.rs#L182)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

wdyt?
</blockquote></details>

Maybe later.
___
*[`crates/mempool/src/mempool_test.rs` line 799 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/889#-O79TaM86DVnhQOUzDZ1:-O79VPea0OYGfg6jH-K-:b-oq0ean) ([raw file](https://github.com/starkware-libs/sequencer/blob/37ff471258265ce08662448c41dcf3c4ae1b8a54/crates/mempool/src/mempool_test.rs#L799)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Now it's not clear that this transaction is not ready.
</blockquote></details>

It's clear from how mempool content is built.

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/889)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 799 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/889#-O79TaM86DVnhQOUzDZ1:-O79k33bA727Rdxa7SGM:b-tsuo7h) ([raw file](https://github.com/starkware-libs/sequencer/blob/37ff471258265ce08662448c41dcf3c4ae1b8a54/crates/mempool/src/mempool_test.rs#L799)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It's clear from how mempool content is built.
</blockquote></details>

means that if someone needs to debug it, they will have to scroll down to see what is being passed to `MempoolContent`. 

The decision is yours - approving this PR.

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/889)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/889)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/889#-O79JjzJAonPIpk2tl5e:-O79r_TO0nSka5TH5yfb:blakimw) ([raw file](https://github.com/starkware-libs/sequencer/blob/0069df022767f9bb7ec3c8b300a4ffeb7c9baa5e/crates/mempool/src/mempool_test.rs#L155)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Comments became outdated; usages can be seen in tests.
</blockquote></details>

The comments are really helpful when writing the code. When hovering over the macro call, they show all the available options. Why do you think they should be deleted?
___
*[`crates/mempool/src/mempool_test.rs` line 799 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/889#-O79TaM86DVnhQOUzDZ1:-O79tiZZB-Zja3SDKQ58:b9ixb5l) ([raw file](https://github.com/starkware-libs/sequencer/blob/37ff471258265ce08662448c41dcf3c4ae1b8a54/crates/mempool/src/mempool_test.rs#L799)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

means that if someone needs to debug it, they will have to scroll down to see what is being passed to `MempoolContent`. 

The decision is yours - approving this PR.
</blockquote></details>

I think it might be confusing in some tests.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/889)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/889#-O79JjzJAonPIpk2tl5e:-O7K2qLGC8G4TT739ZL1:b-rqmqk7) ([raw file](https://github.com/starkware-libs/sequencer/blob/0069df022767f9bb7ec3c8b300a4ffeb7c9baa5e/crates/mempool/src/mempool_test.rs#L155)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

The comments are really helpful when writing the code. When hovering over the macro call, they show all the available options. Why do you think they should be deleted?
</blockquote></details>

Why is a comment better than code usage?
___
*[`crates/mempool/src/mempool_test.rs` line 799 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/889#-O79TaM86DVnhQOUzDZ1:-O7K35pd-TBQnSco2rEe:b-trhk0c) ([raw file](https://github.com/starkware-libs/sequencer/blob/37ff471258265ce08662448c41dcf3c4ae1b8a54/crates/mempool/src/mempool_test.rs#L799)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I think it might be confusing in some tests.
</blockquote></details>

What is more confusing, is that the test writer needs to think about account nonce for non-`add_tx` tests. We're creating `Account` object, just to throw it away in the same line, so it's not actually needed, and might be inconsistent since it isn't used. There _must_ be a better way. 
To debug a failed test, one would have to read it regardless.
The queue represents the account nonces.

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/889)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Pull request merged**
