### PR TITLE
chore(starknet_batcher): extract propose/validate block inputs into function

### PR DESCRIPTION
**Pull request by alonh5**

### CODE REVIEW

**Review by Yael-Starkware — APPROVED** [review]
beautiful! 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2306#-:-OCiDYOb4Ymmdl-006iS:bvtzoej)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2306)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @ArniStarkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2306#-OD_IiXW6XlyQguXId4d:-OD_IiXW6XlyQguXId4e:brvrvza) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c35d9cccff9dad724fc583d6540b8507bc04e3d/crates/starknet_batcher/src/batcher_test.rs#L85)):*
> ```XML
>         deadline: deadline(),
>         retrospective_block_hash: None,
>         block_info: Default::default(),
> ```

why not use the initial_block_info() for all tests?



_Code quote:_
```XML
Default::default()
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2306#-OD_InnS4dG0ql61TgGQ:-OD_InnS4dG0ql61TgGR:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c35d9cccff9dad724fc583d6540b8507bc04e3d/crates/starknet_batcher/src/batcher_test.rs#L94)):*
> ```XML
>         deadline: deadline(),
>         retrospective_block_hash: None,
>         block_info: Default::default(),
> ```

same



_Code quote:_
```XML
block_info: Default::default(),
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2306)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2306#-OD_IiXW6XlyQguXId4d:-ODfvyZ654i0LH_NqXbV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c35d9cccff9dad724fc583d6540b8507bc04e3d/crates/starknet_batcher/src/batcher_test.rs#L85)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why not use the initial_block_info() for all tests?
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2306#-OD_InnS4dG0ql61TgGQ:-ODfvywaE3IQ6Ud4yo5l:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3c35d9cccff9dad724fc583d6540b8507bc04e3d/crates/starknet_batcher/src/batcher_test.rs#L94)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

**Comment by alonh5** [comment]
* **#2306** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2306?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2306?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2306)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by alonh5 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2306)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
