### PR TITLE
feat: add config functions for remote flow test

### PR DESCRIPTION
**Pull request by nadin-Starkware**
commit-id:e9855990

---

**Stack**:
- #2506 ⬅
- #2463
- #2462
- #2461

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2506)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2506#-ODaba9eBIuVDSle22N0:-ODaba9eBIuVDSle22N1:b-djpe71) ([raw file](https://github.com/starkware-libs/sequencer/blob/183c942e58ca4be264dc8c448881c0eafb98a372/crates/starknet_integration_tests/src/config_utils.rs#L123)):*
> ```XML
>         remote_server_config: Some(RemoteServerConfig { socket }),
>     }
> }
> ```

Please add a todo to change these 3 generator functions to be "static" functions of `ComponentExecutionConfig`, a la `new`.



_Code quote:_
```XML
pub fn get_disabled_component_config() -> ComponentExecutionConfig {
    ComponentExecutionConfig {
        execution_mode: ComponentExecutionMode::Disabled,
        local_server_config: None,
        remote_client_config: None,
        remote_server_config: None,
    }
}

pub fn get_remote_component_config(socket: SocketAddr) -> ComponentExecutionConfig {
    ComponentExecutionConfig {
        execution_mode: ComponentExecutionMode::Remote,
        local_server_config: None,
        remote_client_config: Some(RemoteClientConfig { socket, ..RemoteClientConfig::default() }),
        remote_server_config: None,
    }
}

pub fn get_local_with_remote_enabled_component_config(
    socket: SocketAddr,
) -> ComponentExecutionConfig {
    ComponentExecutionConfig {
        execution_mode: ComponentExecutionMode::LocalExecutionWithRemoteEnabled,
        local_server_config: Some(LocalServerConfig::default()),
        remote_client_config: None,
        remote_server_config: Some(RemoteServerConfig { socket }),
    }
}
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2506)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2506#-ODaba9eBIuVDSle22N0:-ODaeViu21U0IlF8m2I4:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/183c942e58ca4be264dc8c448881c0eafb98a372/crates/starknet_integration_tests/src/config_utils.rs#L123)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add a todo to change these 3 generator functions to be "static" functions of `ComponentExecutionConfig`, a la `new`.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2506#-:-ODaenCV9cUqVRZvjvsl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Review by nadin-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2506)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Pull request merged**
