### PR TITLE
test(mempool): refactor add-tx util

### PR DESCRIPTION
**Pull request by MohammadNassar1**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/108)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/108)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/108#-O2eTTTP7nFDYF7xOeLZ:-O2eTTTP7nFDYF7xOeL_:bcbq1gr) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b8fbc413d191a71e98c699f54979d33b9eaa9a3/crates/mempool/src/mempool_test.rs#L122)):*
> ```XML
> }
> 
> #[track_caller]
> ```

Makes us pass `None` everywhere. :(
Maybe a different util? What would be the best solution here?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/108)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/108#-O2eTTTP7nFDYF7xOeLZ:-O2z3qyb5pTmieVh64w0:b4zeu1n) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b8fbc413d191a71e98c699f54979d33b9eaa9a3/crates/mempool/src/mempool_test.rs#L122)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Makes us pass `None` everywhere. :(
Maybe a different util? What would be the best solution here?
</blockquote></details>

Create a new function that expects error.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/108)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 132 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/108#-O3WusOyEJC9sTNOw9m7:-O3WusOyEJC9sTNOw9m8:bpl3ti3) ([raw file](https://github.com/starkware-libs/sequencer/blob/c08e5c2d241d9d4ad2fa01f22d73126c365b0b39/crates/mempool/src/mempool_test.rs#L132)):*
> ```XML
> 
> #[track_caller]
> fn add_tx_expect_success(mempool: &mut Mempool, input: &MempoolInput) {
> ```

Maybe we shouldn't rename, since 99% of the usages are positive flow.



_Code quote:_
```XML
add_tx_expect_success
```
___
*[`crates/mempool/src/mempool_test.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/108#-O3WuoxiAnrRGgL8eWBs:-O3Wuoxj-toaPd220-BL:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c08e5c2d241d9d4ad2fa01f22d73126c365b0b39/crates/mempool/src/mempool_test.rs#L137)):*
> ```XML
> 
> #[track_caller]
> fn _add_tx_expect_error(mempool: &mut Mempool, input: &MempoolInput, expected_err: MempoolError) {
> ```





_Suggestion:_
```XML
expected_error
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/108)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 132 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/108#-O3WusOyEJC9sTNOw9m7:-O3Y4X8NCb3JWn3lxAUZ:b-hay66z) ([raw file](https://github.com/starkware-libs/sequencer/blob/c08e5c2d241d9d4ad2fa01f22d73126c365b0b39/crates/mempool/src/mempool_test.rs#L132)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Maybe we shouldn't rename, since 99% of the usages are positive flow.
</blockquote></details>

revert.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/108#-:-O3b0ZAA2WD6yrLcPd-u:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/108#-O3b0ZSYCZuWsscSrGad:-O3b0ZSYCZuWsscSrGae:b-i029ke) (no related file):*
Use in negative `add_tx` tests?

___

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/108)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/108#-O3b0ZSYCZuWsscSrGad:-O3bC6uI0hTktHKZhnKr:bjsbnr6) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Use in negative `add_tx` tests?
</blockquote></details>

I'll open a new PR that replaces the negative `add_tx`.

___

**Pull request merged**
