### PR TITLE
refactor(tests-integration): simplify accounts

### PR DESCRIPTION
**Pull request by giladchase**
Final design didn't need all of these states, it's basically just a
protection wrapper around `FeatureContract`, which will be ensure that
the tx generator's internal account abstraction has a consistent
address.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1051)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1051)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 356 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1051#-O7rf9zLDe1OfRysZquA:-O7rf9zLDe1OfRysZquB:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/62fa5ac8c03b983de7f4a24e31c9c0cb0d83449c/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L356)):*
> ```XML
> }
> 
> /// Extends FeatureContract account variants with a fixed sender address.
> ```





_Suggestion:_
```XML
(account) feature contract
```
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 360 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1051#-O7rfIiC61e3sVcQ3AtG:-O7rfIiC61e3sVcQ3AtH:byoyx85) ([raw file](https://github.com/starkware-libs/sequencer/blob/62fa5ac8c03b983de7f4a24e31c9c0cb0d83449c/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L360)):*
> ```XML
> // Note: feature contracts have their own address generating method, but it a mocked address and is
> // not related to an actual deploy account transaction, which is the way real account addresses are
> // calculated.
> ```

Thank you for this written clarification!



_Code quote:_
```XML
// Note: feature contracts have their own address generating method, but it a mocked address and is
// not related to an actual deploy account transaction, which is the way real account addresses are
// calculated.
```
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 361 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1051#-O7rf5bK7ScfZSECw5fg:-O7rf5bK7ScfZSECw5fh:ba9ta7u) ([raw file](https://github.com/starkware-libs/sequencer/blob/62fa5ac8c03b983de7f4a24e31c9c0cb0d83449c/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L361)):*
> ```XML
> // not related to an actual deploy account transaction, which is the way real account addresses are
> // calculated.
> #[derive(Debug, Clone)]
> ```

Alphabetize? :grimacing: 



_Code quote:_
```XML
#[derive(Debug, Clone)]
```
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 372 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1051#-O7rfUyI1yZYED92bTSP:-O7rfUyI1yZYED92bTSQ:b4yj7uh) ([raw file](https://github.com/starkware-libs/sequencer/blob/62fa5ac8c03b983de7f4a24e31c9c0cb0d83449c/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L372)):*
> ```XML
>     }
> 
>     fn _new(account: FeatureContract, deploy_account_tx: &RpcTransaction) -> Self {
> ```

Move first?



_Suggestion:_
```XML
pub fn _new
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1051)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 372 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1051#-O7rfUyI1yZYED92bTSP:-O7wuGb758Fg46Flfsdu:b-1snlp7) ([raw file](https://github.com/starkware-libs/sequencer/blob/62fa5ac8c03b983de7f4a24e31c9c0cb0d83449c/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L372)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move first?
</blockquote></details>

I plan on keeping it private (which is why I put it after the pub methods) , i don't want anyone to initialize this struct except for the tx_generator.

This is because it is an implementation detail, and is basically just meant to fix the issue with FeatureContract addresses.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1051#-:-O7wv6nt9tWFu7fzKmcl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1051)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Comment by ArniStarkware** [comment]
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 364 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1051#-O9Ev2NX9WKFEf43oBlD:-O9Ev2NX9WKFEf43oBlE:brwayfq) ([raw file](https://github.com/starkware-libs/sequencer/blob/a7cacf1e0f29dd758be3d2d091c6f08220f56f57/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L364)):*
> ```XML
> pub struct FeatureAccount {
>     pub account: FeatureContract,
>     pub sender_address: ContractAddress,
> ```

This should be something like - post `deploy instance address`.
And it should be an optional.



_Code quote:_
```XML
    pub sender_address: ContractAddress,
```

**Pull request merged**
