### PR TITLE
chore(blockifier): added tests for get_vm_resources_cost

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/927)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/927)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/927#-O7P3MGhApoYgiCKS-_K):*
should I add L2 gas test cases to any more tests?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/927)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/927#-O7yBFMi8KK0pFOT9Gqs:-O7yIbiJB9a6B4nfiIqj:bb7f2mf) (no related file):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Blocking until approved by @dorimedini-starkware
</blockquote></details>

done

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/927#-O7P3MGhApoYgiCKS-_K):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

should I add L2 gas test cases to any more tests?
</blockquote></details>

we will extend existing tests when we do [this](https://starkware.monday.com/boards/6987445459/pulses/7524892471)
___
*[`crates/blockifier/src/fee/fee_test.rs` line 149 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/927#-O7yIPzd9-NdXe7DejKa:-O7yIPzd9-NdXe7DejKb:bj037zz) ([raw file](https://github.com/starkware-libs/sequencer/blob/84253248cdc6b8cb08496c47407edc4c6d08b7b0/crates/blockifier/src/fee/fee_test.rs#L149)):*
> ```XML
>             versioned_constants.convert_l1_to_l2_gas_amount_round_up(l1_gas_by_vm_usage),
>         ),
>     };
> ```

these lines are duplicated 4 times, please add a tiny test util and use it



_Code quote:_
```XML
    let expected_gas_vector = match gas_vector_computation_mode {
        GasVectorComputationMode::NoL2Gas => GasVector::from_l1_gas(l1_gas_by_vm_usage),
        GasVectorComputationMode::All => GasVector::from_l2_gas(
            versioned_constants.convert_l1_to_l2_gas_amount_round_up(l1_gas_by_vm_usage),
        ),
    };
```

**Review by aner-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/927)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/927#-:-O818mjV4sV3yjzmkpve:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
