### PR TITLE
chore(blockifier): unify get entry point for V1 and Native

### PR DESCRIPTION
**Pull request by meship-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1243)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1243)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/starknet_client/src/writer/objects/transaction.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1243#-O8pyzip6REDvoOqHZCG:-O8pyzip6REDvoOqHZCH:bi2eweo) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcfc20155756bb952ce1699d56f92ddc34729db0/crates/starknet_client/src/writer/objects/transaction.rs#L27)):*
> ```XML
>     ContractClassAbiEntry as DeprecatedContractClassAbiEntry,
>     EntryPointType as DeprecatedEntryPointType,
>     EntryPointV0 as DeprecatedEntryPoint,
> ```

I'm not sure if it needs to be part of this PR or if we should change the name. I can revert it if you'd like 



_Code quote:_
```XML
EntryPointV0
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1243)* status: all files reviewed, 5 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1243#-O8rGBJR0-WYjmaIfTFY:-O8rGBJR0-WYjmaIfTFZ:bf6q41d) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcfc20155756bb952ce1699d56f92ddc34729db0/crates/blockifier/src/execution/contract_class.rs#L72)):*
> ```XML
>     V1(EntryPointV1),
>     Native(NativeEntryPoint),
> }
> ```

I would even consider renaming `EntryPointV1 -> CasmEntryPoint` (separate PR)



_Suggestion:_
```XML
pub enum Cairo1EntryPoint {
    Casm(EntryPointV1),
    Native(NativeEntryPoint),
}
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1243#-O8rEhJ5A2pmEhwhrTWR:-O8rEhJ66VZwEpvHm2Va:b-a4nbd3) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcfc20155756bb952ce1699d56f92ddc34729db0/crates/blockifier/src/execution/entry_point_execution.rs#L156)):*
> ```XML
> }
> 
> pub fn get_entry_point(
> ```

Can you please move it to the contract_class.rs file?



_Code quote:_
```XML
pub fn get_entry_point(
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1243#-O8rFTCg22d4gmBamGny:-O8rFTCg22d4gmBamGnz:badc10o) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcfc20155756bb952ce1699d56f92ddc34729db0/crates/blockifier/src/execution/entry_point_execution.rs#L163)):*
> ```XML
> 
>     let entry_points_of_same_type =
>         &contract_class.entry_points_of_same_type(call.entry_point_type);
> ```

Is this working? If so, you can remove some of th `*` in the following lines.



_Suggestion:_
```XML
    let entry_points_of_same_type =
        contract_class.entry_points_of_same_type(call.entry_point_type);
```
___
*[`crates/starknet_client/src/reader/starknet_feeder_gateway_client_test.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1243#-O8rHppx25sxnGP1A53T:-O8rHppx25sxnGP1A53U:blhfowg) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcfc20155756bb952ce1699d56f92ddc34729db0/crates/starknet_client/src/reader/starknet_feeder_gateway_client_test.rs#L26)):*
> ```XML
>     ContractClassAbiEntry,
>     EntryPointOffset,
>     EntryPointType as DeprecatedEntryPointType,
> ```

Why is it deprecated?



_Code quote:_
```XML
    EntryPointType as DeprecatedEntryPointType,
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1243)* status: 10 of 12 files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1243#-O8rGBJR0-WYjmaIfTFY:-O93M_Op5653VOvtfYp9:b-njs2kd) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcfc20155756bb952ce1699d56f92ddc34729db0/crates/blockifier/src/execution/contract_class.rs#L72)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I would even consider renaming `EntryPointV1 -> CasmEntryPoint` (separate PR)
</blockquote></details>

Done. Added a Monday task for the refactor.
___
*[`crates/starknet_client/src/reader/starknet_feeder_gateway_client_test.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1243#-O8rHppx25sxnGP1A53T:-O93NPqL71_Js9frSTOt:b-p7ryvo) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcfc20155756bb952ce1699d56f92ddc34729db0/crates/starknet_client/src/reader/starknet_feeder_gateway_client_test.rs#L26)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it deprecated?
</blockquote></details>

Because the EntryPointType appears in the deprecated_contract_class. I guess the reason is that the deprecated_contract_class file is in starknet_api, and the EntryPointType also appears in the state in starknet_api. So as I see it, we can unify both entry point enum and change the name from deprecated in the imports. Anyway I don't think it should be part of this PR.  
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1243#-O8rEhJ5A2pmEhwhrTWR:-O93K44PCakeuv9hbgKm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcfc20155756bb952ce1699d56f92ddc34729db0/crates/blockifier/src/execution/entry_point_execution.rs#L156)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please move it to the contract_class.rs file?
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1243#-:-O94RbKME49GgAeLhQ5P:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1243)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Pull request merged**
