### PR TITLE
feat(batcher): stream transactions outside while generating proposal

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/548)

### CODE REVIEW

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/548)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/548#-O5K2V658XN9ut8XMONz:-O5K2V658XN9ut8XMOO-:b-idl56r) ([raw file](https://github.com/starkware-libs/sequencer/blob/f292b900882718b6359d1f680f0a7b2966792aab/crates/batcher/src/proposals_manager.rs#L21)):*
> ```XML
> pub struct ProposalsManagerConfig {
>     pub max_txs_per_mempool_request: usize,
>     pub outstream_tx_stream_buffer_size: usize,
> ```

We will probably stream other data as well (not only Transaction). e.g. block info necessary to start the building of a block.

Also please add documentation.



_Suggestion:_
```XML
outstream_content_buffer_size
```
___
*[`crates/batcher/src/proposals_manager.rs` line 210 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/548#-O5K6nXz1KYOa5e8EhEb:-O5K6nY-EzPejkBBsOpZ:bivugt0) ([raw file](https://github.com/starkware-libs/sequencer/blob/f292b900882718b6359d1f680f0a7b2966792aab/crates/batcher/src/proposals_manager.rs#L210)):*
> ```XML
>                     return Err(ProposalsManagerError::InternalError);
>                 }
>             }
> ```

Only txs that were successfully executed and entered the block should be streamed.
I think the sender should be passed to the block builder.



_Code quote:_
```XML
            for tx in mempool_txs {
                debug!("Sending tx {}.", tx.tx_hash());
                if self.sender.send(tx).await.is_err() {
                    error!("Failed to send tx to the receiver.");
                    return Err(ProposalsManagerError::InternalError);
                }
            }
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/548)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/batcher/src/proposals_manager.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/548#-O5K2V658XN9ut8XMONz:-O5NS8xtCeWqwwu2nkC7:bmzojjp) ([raw file](https://github.com/starkware-libs/sequencer/blob/f292b900882718b6359d1f680f0a7b2966792aab/crates/batcher/src/proposals_manager.rs#L21)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

We will probably stream other data as well (not only Transaction). e.g. block info necessary to start the building of a block.

Also please add documentation.
</blockquote></details>

Done.
it is self-documented by the dump function
___
*[`crates/batcher/src/proposals_manager.rs` line 210 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/548#-O5K6nXz1KYOa5e8EhEb:-O5NRv8_-vYWP9BODHaa:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f292b900882718b6359d1f680f0a7b2966792aab/crates/batcher/src/proposals_manager.rs#L210)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Only txs that were successfully executed and entered the block should be streamed.
I think the sender should be passed to the block builder.
</blockquote></details>

Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/548#-:-O5h8ALRDrdjmlyrypra:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware and @Yael-Starkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/548)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
