### PR TITLE
chore: use cairo lang util to extract sierra program version id

### PR DESCRIPTION
**Pull request by ArniStarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

The validation for version ID is currently only validating the version is in range. It does not validate the compiler version is included in the contract.

## What is the new behavior?

- Use the Cairo lang deserializer to deserialize the version ID.
- The gateway now validates the compiler version is included in the program.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/84)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/84?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#84** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/84?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#83** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/83?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/84)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/compiler_version.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/84#-O31eYIu9KxDI7ZpKuh-:-O31eYIu9KxDI7ZpKuh0:b-knilj9) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c1d96d599fde465f9418bd590af6bbc96220786/crates/gateway/src/compiler_version.rs#L126)):*
> ```XML
>             });
>         }
>         if sierra_program_length < 6 {
> ```

use `get` method of String: https://doc.rust-lang.org/std/string/struct.String.html#method.get:~:text=Returns%20a%20subslice%20of%20str.



_Code quote:_
```XML
if sierra_program_length < 6
```
___
*[`crates/gateway/src/compiler_version.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/84#-O31eJ8BBjN1aEgOhWYx:-O31eJ8CB0YoIUNHb9Vb:bxgzeoj) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c1d96d599fde465f9418bd590af6bbc96220786/crates/gateway/src/compiler_version.rs#L132)):*
> ```XML
>                      enough to Sierra program's headers.",
>                     sierra_program_length
>                 ),
> ```

log this message instead of passing it in the error



_Code quote:_
```XML
                message: format!(
                    "Sierra program is too short. got program of length {} which is not long \
                     enough to Sierra program's headers.",
                    sierra_program_length
                ),
```

**Comment by yair-starkware** [comment]
*[`crates/gateway/src/compiler_version.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/84#-O31eYIu9KxDI7ZpKuh-:-O36heqBCVgr3y_o2IIy:bjwoseu) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c1d96d599fde465f9418bd590af6bbc96220786/crates/gateway/src/compiler_version.rs#L126)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

use `get` method of String: https://doc.rust-lang.org/std/string/struct.String.html#method.get:~:text=Returns%20a%20subslice%20of%20str.
</blockquote></details>

nvm, had a mistake

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/84)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/gateway/src/compiler_version.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/84#-O31eJ8BBjN1aEgOhWYx:-O36YlyRC3MnK7A9bJ4Q:b-cmmr4j) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c1d96d599fde465f9418bd590af6bbc96220786/crates/gateway/src/compiler_version.rs#L132)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

log this message instead of passing it in the error
</blockquote></details>

We discussed on DMs.
A TODO was added.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/84)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @yair-starkware)

___
*[`crates/gateway/src/compiler_version.rs` line 134 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/84#-O371VlR-Z0imj57Y2Un:-O371VlR-Z0imj57Y2Uo:b-4ohm7l) ([raw file](https://github.com/starkware-libs/sequencer/blob/275f0e43354d1baeebe02ecfca5f74aa79b218dc/crates/gateway/src/compiler_version.rs#L134)):*
> ```XML
>                      enough to Sierra program's headers.",
>                     sierra_program_length
>                 ),
> ```

maybe one error type is enough



_Code quote:_
```XML
        if sierra_program_length < 3 {
            return Err(VersionIdError::InvalidVersion {
                message: format!(
                    "Sierra program is too short. got program of length {} which is not long \
                     enough to hold the version field.",
                    sierra_program_length
                ),
            });
        }
        if sierra_program_length < 6 {
            return Err(VersionIdError::InvalidVersion {
                message: format!(
                    "Sierra program is too short. got program of length {} which is not long \
                     enough to Sierra program's headers.",
                    sierra_program_length
                ),
```
___
*[`crates/gateway/src/compiler_version.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/84#-O370QGj3kDA8GcO1YSQ:-O370QGj3kDA8GcO1YSR:b-ju9wfa) ([raw file](https://github.com/starkware-libs/sequencer/blob/275f0e43354d1baeebe02ecfca5f74aa79b218dc/crates/gateway/src/compiler_version.rs#L140)):*
> ```XML
>             sierra_program_as_felts_to_big_uint_as_hex(&sierra_program[..6]);
> 
>         // TODO(Arni): Handle unwrap. map error to VersionIdError.
> ```

this is done . right?



_Code quote:_
```XML
// TODO(Arni): Handle unwrap. map error to VersionIdError.
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/84)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/gateway/src/compiler_version.rs` line 134 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/84#-O371VlR-Z0imj57Y2Un:-O37DNUJ8TVTqe8i9uE5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/275f0e43354d1baeebe02ecfca5f74aa79b218dc/crates/gateway/src/compiler_version.rs#L134)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

maybe one error type is enough
</blockquote></details>

Done.
___
*[`crates/gateway/src/compiler_version.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/84#-O370QGj3kDA8GcO1YSQ:-O37EehWA1soKXcGwXIO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/275f0e43354d1baeebe02ecfca5f74aa79b218dc/crates/gateway/src/compiler_version.rs#L140)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

this is done . right?
</blockquote></details>

Done.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/84)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/compiler_version.rs` line 133 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/84#-O3bIyp545xPzAxGCRsr:-O3bIyp545xPzAxGCRss:byztc7p) ([raw file](https://github.com/starkware-libs/sequencer/blob/d20162bb9e85f018351e543a5b010e3aabf357c3/crates/gateway/src/compiler_version.rs#L133)):*
> ```XML
>         let (version_id, _compiler_version_id) = version_id_from_serialized_sierra_program(
>             &sierra_program_for_compiler,
>         )
> ```

This is the main benefit of PR. 



_Code quote:_
```XML
        let (version_id, _compiler_version_id) = version_id_from_serialized_sierra_program(
            &sierra_program_for_compiler,
        )
```

**Review by ArniStarkware — COMMENTED** [review]
I reordered the PRs.
This PR focuses on using new functionality the CarioLang crate offers for reading the serialized Sierra program.

The changes are in the file `compiler_version.rs`. Other changes are minor/ affect the tests.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/84#-:-O3fiEWJ5ao2IbybWABb:b-c0rgag)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware and @yair-starkware)

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/compiler_version.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/84#-O31eJ8BBjN1aEgOhWYx:-O3frS2ECBIFjVirozRY:b-8aiez6) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c1d96d599fde465f9418bd590af6bbc96220786/crates/gateway/src/compiler_version.rs#L132)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

We discussed on DMs.
A TODO was added.
</blockquote></details>

See: 
```
pub enum VersionIdError {
    // TODO(Arni): Consider removing the error message from VersionIdError::InvalidVersion.
    // Error messages should be handled or cause a painc. Talk to product.
    #[error("{message}")]
    InvalidVersion { message: String },
}
```

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 4 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/84)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/compiler_version.rs` line 41 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/84#-O44_6ls6tozteNKvQH0:-O44_6ls6tozteNKvQH1:bxu3sii) ([raw file](https://github.com/starkware-libs/sequencer/blob/8b715c0b1da584a248809a90e31112c19dd658c2/crates/gateway/src/compiler_version.rs#L41)):*
> ```XML
> }
> 
> impl From<&CairoLangVersionId> for VersionId {
> ```

Why from a borrow and not consuming? Seems like it makes the copying implicit 



_Code quote:_
```XML
&
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/84)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/gateway/src/compiler_version.rs` line 41 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/84#-O44_6ls6tozteNKvQH0:-O44g8kr9hnFNDWRjwSw:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8b715c0b1da584a248809a90e31112c19dd658c2/crates/gateway/src/compiler_version.rs#L41)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why from a borrow and not consuming? Seems like it makes the copying implicit
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/84#-:-O455LKt4Ky6JQQIr0ks:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
