### PR TITLE
feat: update cairo to 2.8.4 and native to 0.2.0-alpha.4

### PR DESCRIPTION
**Pull request by rodrigo-pino**

### CODE REVIEW

**Review by noaov1 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 5 of 7 files at r2, 1 of 1 files at r3, 3 of 8 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1704)* status: all files reviewed, 1 unresolved discussion (waiting on @rodrigo-pino)

___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 11 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1704#-OAXm7-30BWz6HdoGusA:-OAXm7-30BWz6HdoGusB:bhjqkge) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd77a64f612d05795d8db88cf41c5670d56b4a03/.github/workflows/blockifier_compiled_cairo.yml#L11)):*
> ```YAML
>     paths:
>       - '.github/workflows/blockifier_compiled_cairo.yml'
>       - 'crates/Cargo.toml'
> ```

Why is it needed?



_Code quote:_
```YAML
- 'crates/Cargo.toml'
```

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1704)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 11 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1704#-OAXm7-30BWz6HdoGusA:-OAXn_zv4V1C_Z1Oimlj:bsq4uv4) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd77a64f612d05795d8db88cf41c5670d56b4a03/.github/workflows/blockifier_compiled_cairo.yml#L11)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it needed?
</blockquote></details>

Added them to trigger test verification on a Cairo version update. Otherwise there is no check for it, like small PRs like this which are only a version update

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1704)* status: all files reviewed, 1 unresolved discussion (waiting on @rodrigo-pino)

___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 11 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1704#-OAXm7-30BWz6HdoGusA:-OAXphw37KYVbbJYyaBL:b-6zerq4) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd77a64f612d05795d8db88cf41c5670d56b4a03/.github/workflows/blockifier_compiled_cairo.yml#L11)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

But if you think the check is too much of a hassle, I'll just remove it
</blockquote></details>

t's better to remove it. It will trigger on every change to the `Cargo.toml` file, and I'm fine with recompiling only when needed.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1704#-:-OAXu6q_3F6KssmjIqLA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rodrigo-pino)

**Pull request merged**
