### PR TITLE
build(ci): add rust version file

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/612)

### CODE REVIEW

**Comment by nimrod-starkware** [comment]
* **#612** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/612?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nimrod-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/612)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/612#-O5IT9dQ3dojtJKZi8pp:-O5IT9dRAJvBgN1_yDFA:b-1887zc) (no related file):*
merge to `main-v0.13.2` please

___

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/612)* status: 3 of 9 files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/612#-:-O5IecYf-LlAYaBoyFM6:bnfp4nl)* status: 3 of 9 files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/612)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
