### PR TITLE
chore(blockifier): add with_attr error message

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/624)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/624)* status: all files reviewed, 5 unresolved discussions (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/624#-O5J-y3yC2Vk1i8BYSqp:-O5J-y3yC2Vk1i8BYSqq:b-aw64mg) ([raw file](https://github.com/starkware-libs/sequencer/blob/caebe1c35cde78ccdc98d3cf5e8e398bc4487a2f/crates/blockifier/src/execution/stack_trace.rs#L86)):*
> ```XML
>         };
>         // TODO(Aner): add test for error message in intermediate call"
>         format!("{error_msg}{vm_exception_preamble}{vm_exception_traceback}")
> ```

if the error message exists you should add a newline, no?
or is the newline already in the error attr?



_Code quote:_
```XML
{error_msg}{
```
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/624#-O5J0Cz69U9ere_f93Pp:-O5J0Cz69U9ere_f93Pq:b-v4nmt) ([raw file](https://github.com/starkware-libs/sequencer/blob/caebe1c35cde78ccdc98d3cf5e8e398bc4487a2f/crates/blockifier/src/execution/stack_trace_test.rs#L173)):*
> ```XML
>         }
>         CairoVersion::Cairo1 => String::new(),
>     };
> ```

simpler



_Suggestion:_
```XML
    let expected_with_attr_error_msg = match (cairo_version, last_func_name) {
        (CairoVersion::Cairo0, "fail") => "Error message: You shall not pass!\n".to_string(),
        _ => String::new(),
    };
```
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 248 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/624#-O5J0Oe4DH7-m6TP2gjn:-O5J0Oe4DH7-m6TP2gjo:b-xm2y3i) ([raw file](https://github.com/starkware-libs/sequencer/blob/caebe1c35cde78ccdc98d3cf5e8e398bc4487a2f/crates/blockifier/src/execution/stack_trace_test.rs#L248)):*
> ```XML
> 2: Error in the called contract (contract address: {contract_address_felt:#064x}, class hash: \
>                  {test_contract_hash:#064x}, selector: {invoke_call_chain_selector_felt:#064x}):
> {expected_with_attr_error_msg}Error at pc=0:{expected_pc0}:
> ```

need a newline after this line



_Code quote:_
```XML
{expected_with_attr_error_msg}
```
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 308 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/624#-O5J0R4C78E5frqPsKSy:-O5J0R4C78E5frqPsKSz:b-aslc7d) ([raw file](https://github.com/starkware-libs/sequencer/blob/caebe1c35cde78ccdc98d3cf5e8e398bc4487a2f/crates/blockifier/src/execution/stack_trace_test.rs#L308)):*
> ```XML
>         }
>         CairoVersion::Cairo1 => String::new(),
>     };
> ```

see above for simplification



_Code quote:_
```XML
    let expected_with_attr_error_msg = match cairo_version {
        CairoVersion::Cairo0 => {
            if last_func_name == "fail" {
                "Error message: You shall not pass!\n".to_string()
            } else {
                String::new()
            }
        }
        CairoVersion::Cairo1 => String::new(),
    };
```
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 411 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/624#-O5J0TrF8JXwxBvsXwy_:-O5J0TrF8JXwxBvsXwya:b-4yr6dt) ([raw file](https://github.com/starkware-libs/sequencer/blob/caebe1c35cde78ccdc98d3cf5e8e398bc4487a2f/crates/blockifier/src/execution/stack_trace_test.rs#L411)):*
> ```XML
> 
> 3: {last_call_preamble}:
> {expected_with_attr_error_msg}Error at pc=0:{expected_pc2}:
> ```

newline



_Code quote:_
```XML
{expected_with_attr_error_msg}
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/624)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/624#-O5J-y3yC2Vk1i8BYSqp:-O5MvA8q-biIEh2luMJP:b-flc09e) ([raw file](https://github.com/starkware-libs/sequencer/blob/caebe1c35cde78ccdc98d3cf5e8e398bc4487a2f/crates/blockifier/src/execution/stack_trace.rs#L86)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if the error message exists you should add a newline, no?
or is the newline already in the error attr?
</blockquote></details>

I wrote it so that it passes the test, so I guess this is the correct way. While there might of course be other correct ways, just adding something, e.g., a newline, will cause it to fail the test. 
So the other logical option seems to be that when there is no error message, there will just be a blank line - would it be a better option? (IMO, the current solution is better)
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/624#-O5J0Cz69U9ere_f93Pp:-O5MwToR2xpcwLpAGqmx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/caebe1c35cde78ccdc98d3cf5e8e398bc4487a2f/crates/blockifier/src/execution/stack_trace_test.rs#L173)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

simpler
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 248 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/624#-O5J0Oe4DH7-m6TP2gjn:-O5MvgIR1cIMa_Fcpypo:b-q64pkt) ([raw file](https://github.com/starkware-libs/sequencer/blob/caebe1c35cde78ccdc98d3cf5e8e398bc4487a2f/crates/blockifier/src/execution/stack_trace_test.rs#L248)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

need a newline after this line
</blockquote></details>

See above.
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 308 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/624#-O5J0R4C78E5frqPsKSy:-O5MwWOD0WHm5_OGtaeN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/caebe1c35cde78ccdc98d3cf5e8e398bc4487a2f/crates/blockifier/src/execution/stack_trace_test.rs#L308)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above for simplification
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 411 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/624#-O5J0TrF8JXwxBvsXwy_:-O5MvhoJC0EXmerP3Bo9:b-q64pkt) ([raw file](https://github.com/starkware-libs/sequencer/blob/caebe1c35cde78ccdc98d3cf5e8e398bc4487a2f/crates/blockifier/src/execution/stack_trace_test.rs#L411)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

newline
</blockquote></details>

See above.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/624)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/624#-O5J-y3yC2Vk1i8BYSqp:-O5N0ryP0SozSjArieWj:b-f9h2ta) ([raw file](https://github.com/starkware-libs/sequencer/blob/caebe1c35cde78ccdc98d3cf5e8e398bc4487a2f/crates/blockifier/src/execution/stack_trace.rs#L86)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I wrote it so that it passes the test, so I guess this is the correct way. While there might of course be other correct ways, just adding something, e.g., a newline, will cause it to fail the test. 
So the other logical option seems to be that when there is no error message, there will just be a blank line - would it be a better option? (IMO, the current solution is better)
</blockquote></details>

OK, the below comments I had about newlines (in tests) - you are right, your way is better.
here, though, I don't understand how you get the newline for free?
in the `with_attr`, the string doesn't include a newline,
but somehow in tests you get a newline in the formatted frame.
how does this happen?
does the `with_attr` automatically append a newline?

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/execution/stack_trace.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/624#-O5J-y3yC2Vk1i8BYSqp:-O5NV0OE0JoDS0C26I-H:bkkcj6w) ([raw file](https://github.com/starkware-libs/sequencer/blob/caebe1c35cde78ccdc98d3cf5e8e398bc4487a2f/crates/blockifier/src/execution/stack_trace.rs#L86)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

OK, the below comments I had about newlines (in tests) - you are right, your way is better.
here, though, I don't understand how you get the newline for free?
in the `with_attr`, the string doesn't include a newline,
but somehow in tests you get a newline in the formatted frame.
how does this happen?
does the `with_attr` automatically append a newline?
</blockquote></details>

Apparently it's automatically appended, as I didn't specifically add a newline in the Cairo code. Should I investigate it further? I guess it's worth verifying this is the intended behaviour.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/624)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/624#-O5J-y3yC2Vk1i8BYSqp:-O5N_LQmATnRD9prYBSx:bbpzh88) ([raw file](https://github.com/starkware-libs/sequencer/blob/caebe1c35cde78ccdc98d3cf5e8e398bc4487a2f/crates/blockifier/src/execution/stack_trace.rs#L86)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Apparently it's automatically appended, as I didn't specifically add a newline in the Cairo code. Should I investigate it further? I guess it's worth verifying this is the intended behaviour.
</blockquote></details>

if you can, please do; it looks like this is the behavior but we should verify so we don't start seeing mangled error messages on public endpoints

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/624)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/624#-O5J-y3yC2Vk1i8BYSqp:-O5ODsJD9XzOnyqPD2YQ:bae3r2q) ([raw file](https://github.com/starkware-libs/sequencer/blob/caebe1c35cde78ccdc98d3cf5e8e398bc4487a2f/crates/blockifier/src/execution/stack_trace.rs#L86)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

OK, will do. Who should I ask?
</blockquote></details>

[in the python VM](https://github.com/starkware-industries/starkware/blob/dori/merge-cairo-v0.13.2-into-dev/src/starkware/cairo/lang/vm/virtual_machine_base.py#L425) it looks like that's what's happening;
for the rust VM - you will have to read to verify :)
I would clone the VM repo locally and search for `with_attr` handling, i.e. search for `with_attr` or the `Error message: ` prefix

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/execution/stack_trace.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/624#-O5J-y3yC2Vk1i8BYSqp:-O5S3rb242eMWZ3jRblJ:b-e0hbhl) ([raw file](https://github.com/starkware-libs/sequencer/blob/caebe1c35cde78ccdc98d3cf5e8e398bc4487a2f/crates/blockifier/src/execution/stack_trace.rs#L86)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[in the python VM](https://github.com/starkware-industries/starkware/blob/dori/merge-cairo-v0.13.2-into-dev/src/starkware/cairo/lang/vm/virtual_machine_base.py#L425) it looks like that's what's happening;
for the rust VM - you will have to read to verify :)
I would clone the VM repo locally and search for `with_attr` handling, i.e. search for `with_attr` or the `Error message: ` prefix
</blockquote></details>

Wouldn't that just be verifying the *actual* behaviour (which seems to be adding a newline). I meant how do I check this is the *intended* behaviour?

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/624#-:-O5SLK-jA-EEgX40mSB1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/624#-O5J-y3yC2Vk1i8BYSqp:-O5SLEKQ09M7j0fIbmZQ:b-iae2g4) ([raw file](https://github.com/starkware-libs/sequencer/blob/caebe1c35cde78ccdc98d3cf5e8e398bc4487a2f/crates/blockifier/src/execution/stack_trace.rs#L86)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Wouldn't that just be verifying the *actual* behaviour (which seems to be adding a newline). I meant how do I check this is the *intended* behaviour?
</blockquote></details>

it is intended :) (request from product team)
unblocking

**Pull request merged**
