### PR TITLE
chore(mempool): move account nonces update check to add tx test

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/878)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/878)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`crates/mempool/src/mempool_test.rs` line 490 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/878#-O7Ox-w85TDZgXht9G7l:-O7Ox-w85TDZgXht9G7m:b-hy1pan) ([raw file](https://github.com/starkware-libs/sequencer/blob/602ec6fec7c605b696780cff756e2653b0f4acd9/crates/mempool/src/mempool_test.rs#L490)):*
> ```XML
>         .with_queue(expected_queue_txs)
>         .build();
>     expected_mempool_content.assert_eq_pool_and_queue_content(&mempool);
> ```

I think it would be better to delete this function since we now have more fields to assert, and we can check each one separately as needed.



_Code quote:_
```XML
assert_eq_pool_and_queue_content
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/878)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`Cargo.lock` line 9793 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/878#-O7Xuehd5OqrNhkEXPnJ:-O7Xuehd5OqrNhkEXPnK:b-lhot9o) ([raw file](https://github.com/starkware-libs/sequencer/blob/e349c541ebd11f216b73efdf3e4de664159d419a/Cargo.lock#L9793)):*
> ```TOML
> dependencies = [
>  "async-trait",
>  "derive_more 0.99.17",
> ```

The lock was updated, but no toml files were updated. This seems odd...



_Code quote:_
```TOML
 "derive_more 0.99.17"
```
___
*[`crates/mempool/src/mempool_test.rs` line 490 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/878#-O7Ox-w85TDZgXht9G7l:-O7XvV066XowhncYJ8z5:b-f20scc) ([raw file](https://github.com/starkware-libs/sequencer/blob/602ec6fec7c605b696780cff756e2653b0f4acd9/crates/mempool/src/mempool_test.rs#L490)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I think it would be better to delete this function since we now have more fields to assert, and we can check each one separately as needed.
</blockquote></details>

Delete it from this test - and not in general, I see.
Is this the intended behavior?
___
*[`crates/mempool/src/mempool_test.rs` line 497 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/878#-O7XzHkIBCs5pWspnKxa:-O7XzHkIBCs5pWspnKxb:bo51bdt) ([raw file](https://github.com/starkware-libs/sequencer/blob/e349c541ebd11f216b73efdf3e4de664159d419a/crates/mempool/src/mempool_test.rs#L497)):*
> ```XML
>         .with_queue(expected_queue_txs)
>         .with_account_nonces(expected_account_nonces)
>         .build();
> ```

For the record, this suggested code does not require `.collect`. I am not sure it is a value we should aspire to, though. This suggestion is less readable.



_Suggestion:_
```XML
    // Assert: transactions are ordered by priority.
    let expected_mempool_content = MempoolContentBuilder::new()
        .with_account_nonces(add_tx_inputs.iter().map(|input| {
            let Account { sender_address, state: AccountState { nonce } } = input.account;
            (sender_address, nonce)
        }))
        .with_queue(add_tx_inputs.iter().map(|input| TransactionReference::new(&input.tx)))
        .with_pool(add_tx_inputs.into_iter().map(|input| input.tx))
        .build();
```
___
*[`crates/mempool/src/mempool_test.rs` line 497 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/878#-O7Y09f68pZtg1UH05H8:-O7Y09f68pZtg1UH05H9:b-2r5axy) ([raw file](https://github.com/starkware-libs/sequencer/blob/e349c541ebd11f216b73efdf3e4de664159d419a/crates/mempool/src/mempool_test.rs#L497)):*
> ```XML
>         .with_queue(expected_queue_txs)
>         .with_account_nonces(expected_account_nonces)
>         .build();
> ```

Please align the order of the itereables and the order of the `with_` methods (If it is possible). (Not necessarily in the suggested order - but in a readable way).



_Suggestion:_
```XML
    // Assert: transactions are ordered by priority.
    let expected_account_nonces: Vec<(ContractAddress, Nonce)> = add_tx_inputs
        .iter()
        .map(|input| {
            let Account { sender_address, state: AccountState { nonce } } = input.account;
            (sender_address, nonce)
        })
        .collect();
    let expected_queue_txs: Vec<TransactionReference> =
        add_tx_inputs.iter().map(|input| TransactionReference::new(&input.tx)).collect();
    let expected_pool_txs = add_tx_inputs.into_iter().map(|input| input.tx);
    let expected_mempool_content = MempoolContentBuilder::new()
        .with_account_nonces(expected_account_nonces)
        .with_queue(expected_queue_txs)
        .with_pool(expected_pool_txs)
        .build();
```

**Comment by ArniStarkware** [comment]
*[`crates/mempool/src/mempool_test.rs` line 497 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/878#-O7XzHkIBCs5pWspnKxa:-O7YCov_AVWVP1hcPQSc:b-h7qdk2) ([raw file](https://github.com/starkware-libs/sequencer/blob/e349c541ebd11f216b73efdf3e4de664159d419a/crates/mempool/src/mempool_test.rs#L497)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

For the record, this suggested code does not require `.collect`. I am not sure it is a value we should aspire to, though. This suggestion is less readable.
</blockquote></details>

Collect is happening inside anyway.

**Comment by ArniStarkware** [comment]
*[`crates/mempool/src/mempool_test.rs` line 497 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/878#-O7XzHkIBCs5pWspnKxa:-O7YDXAv9ydHi2x78UYK:b-f68kv5) ([raw file](https://github.com/starkware-libs/sequencer/blob/e349c541ebd11f216b73efdf3e4de664159d419a/crates/mempool/src/mempool_test.rs#L497)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Collect is happening inside anyway.
</blockquote></details>

So, I regret that comment.

**Comment by ArniStarkware** [comment]
*[`crates/mempool/src/mempool_test.rs` line 497 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/878#-O7Y09f68pZtg1UH05H8:-O7YEJvOBmu3zdkyj7at:b-6vh36x) ([raw file](https://github.com/starkware-libs/sequencer/blob/e349c541ebd11f216b73efdf3e4de664159d419a/crates/mempool/src/mempool_test.rs#L497)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Please align the order of the itereables and the order of the `with_` methods (If it is possible). (Not necessarily in the suggested order - but in a readable way).
</blockquote></details>

Please also extend this order to the `assert` lines.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/878)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`Cargo.lock` line 9793 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/878#-O7Xuehd5OqrNhkEXPnJ:-O7Y1-YdDcHEonXiKZeh:b-hfpv0l) ([raw file](https://github.com/starkware-libs/sequencer/blob/e349c541ebd11f216b73efdf3e4de664159d419a/Cargo.lock#L9793)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The lock was updated, but no toml files were updated. This seems odd...
</blockquote></details>

removed
___
*[`crates/mempool/src/mempool_test.rs` line 490 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/878#-O7Ox-w85TDZgXht9G7l:-O7Y3-83BBSqtXlXOJeM:b-10zre5) ([raw file](https://github.com/starkware-libs/sequencer/blob/602ec6fec7c605b696780cff756e2653b0f4acd9/crates/mempool/src/mempool_test.rs#L490)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Delete it from this test - and not in general, I see.
Is this the intended behavior?
</blockquote></details>

I considered deleting this function, but it was decided to keep it, so I’m returning to using it.
___
*[`crates/mempool/src/mempool_test.rs` line 497 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/878#-O7Y09f68pZtg1UH05H8:-O7YevPvDkJTauUX4RTb:b-u8qmfz) ([raw file](https://github.com/starkware-libs/sequencer/blob/e349c541ebd11f216b73efdf3e4de664159d419a/crates/mempool/src/mempool_test.rs#L497)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Please also extend this order to the `assert` lines.
</blockquote></details>

Due to borrowing constraints, the iterators are in this order. I’ve arranged the following flow as optimally as possible.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/878#-:-O7YgeJE8Ms_FsDVQiSq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/878)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 473 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/878#-O7_I8Z0AiwQcqrOBb13:-O7_I8Z0AiwQcqrOBb14:bgkjwcq) ([raw file](https://github.com/starkware-libs/sequencer/blob/73a83065aa12c50e2f1ef25bd15e036edadfe2eb/crates/mempool/src/mempool_test.rs#L473)):*
> ```XML
>     ];
> 
>     // Test.
> ```

Is this the simplest test this can be checked in?
I want a single account, single input; this is what the specific test checked, no need to complicate more than this.
___
*[`crates/mempool/src/mempool_test.rs` line 489 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/878#-O7_HxmT4e4UzKei1Hzb:-O7_HxmT4e4UzKei1Hzc:b-efy17s) ([raw file](https://github.com/starkware-libs/sequencer/blob/73a83065aa12c50e2f1ef25bd15e036edadfe2eb/crates/mempool/src/mempool_test.rs#L489)):*
> ```XML
>             (sender_address, nonce)
>         })
>         .collect();
> ```

This is complex; after the refactor below, please define them using literals for easy read.



_Code quote:_
```XML
    // Assert: transactions are ordered by priority.
    let expected_account_nonces: Vec<(ContractAddress, Nonce)> = add_tx_inputs
        .iter()
        .map(|input| {
            let Account { sender_address, state: AccountState { nonce } } = input.account;
            (sender_address, nonce)
        })
        .collect();
```
___
*[`crates/mempool/src/mempool_test.rs` line 494 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/878#-O7_Hc_K9c2_TDM6VE_d:-O7_Hc_K9c2_TDM6VE_e:bk684wn) ([raw file](https://github.com/starkware-libs/sequencer/blob/73a83065aa12c50e2f1ef25bd15e036edadfe2eb/crates/mempool/src/mempool_test.rs#L494)):*
> ```XML
>     let expected_pool_txs = add_tx_inputs.into_iter().map(|input| input.tx);
>     let expected_mempool_content = MempoolContentBuilder::new()
>         .with_account_nonces(expected_account_nonces)
> ```

Please refactor `with_account_nonces` to receive `IntoIterator<Item = (&str, u8)>`; no need for full types, it makes tests cumbersome.



_Code quote:_
```XML
with_account_nonces
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/878)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 473 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/878#-O7_I8Z0AiwQcqrOBb13:-O80kjB4AdLXYANw0X51:brjiix6) ([raw file](https://github.com/starkware-libs/sequencer/blob/73a83065aa12c50e2f1ef25bd15e036edadfe2eb/crates/mempool/src/mempool_test.rs#L473)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this the simplest test this can be checked in?
I want a single account, single input; this is what the specific test checked, no need to complicate more than this.
</blockquote></details>

There's an option to add it to `test_add_tx_with_duplicate_tx`, which makes it a bit shorter since we only check one tx there. However, `test_add_tx` is the most basic test for adding transactions to the Mempool, so it seems better suited here. WDYT?
___
*[`crates/mempool/src/mempool_test.rs` line 489 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/878#-O7_HxmT4e4UzKei1Hzb:-O7y8whH-T-VzFYk9oNS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/73a83065aa12c50e2f1ef25bd15e036edadfe2eb/crates/mempool/src/mempool_test.rs#L489)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This is complex; after the refactor below, please define them using literals for easy read.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 494 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/878#-O7_Hc_K9c2_TDM6VE_d:-O7y8rsu1oW1yb602oyt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/73a83065aa12c50e2f1ef25bd15e036edadfe2eb/crates/mempool/src/mempool_test.rs#L494)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please refactor `with_account_nonces` to receive `IntoIterator<Item = (&str, u8)>`; no need for full types, it makes tests cumbersome.
</blockquote></details>

Done.

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/878)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @giladchase)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/878)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 448 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/878#-O813a94-Or1krwSY18Q:-O813a94-Or1krwSY18R:b-fcjs14) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef3815c7f03214682532a9dc68677fa9232c6df8/crates/mempool/src/mempool_test.rs#L448)):*
> ```XML
> fn test_add_tx(mut mempool: Mempool) {
>     // Setup.
>     let mut add_tx_inputs = [
> ```

Pass nonces explicitly if you're mentioning them bellow.



_Code quote:_
```XML
add_tx_inputs
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/878)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 448 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/878#-O813a94-Or1krwSY18Q:-O81mrr3B9CDV2kvNg1p:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef3815c7f03214682532a9dc68677fa9232c6df8/crates/mempool/src/mempool_test.rs#L448)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Pass nonces explicitly if you're mentioning them bellow.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/878#-:-O81pSba9AG7ipp1l8oV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
