### PR TITLE
test(batcher): refactor block builder test

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
* **#2171** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2171?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2191** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2191?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2191?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yael-Starkware — COMMENTED** [review]
this refactor allows me to add a case of transaction_failed 
and also looks nice

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2191#-:-OC7HmyW9nVlYKSZYAEf:bz5awo8)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alonh5 and @yair-starkware)

**Review by alonh5 — APPROVED** [review]
Great PR!
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2191#-:-OC8rm892nkBhqsWnmaC:bq25x7z)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by Yael-Starkware — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2191#-:-OC94Lg023v-N6FmALNh:b-ucfknh)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Comment by Yael-Starkware** [comment]
### Merge activity

* **Nov 20, 9:59 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2191).

**Pull request merged**
