### PR TITLE
feat(starknet_api): backward compatibility for empty signatures

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1201)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1201)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @yoavGrs and @Yoni-Starkware)

___
*[`crates/committer_cli/src/block_hash.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1201#-O8WqrYw2-rFsyLuIlfB:-O8WqrYw2-rFsyLuIlfC:b-lsqn7i) ([raw file](https://github.com/starkware-libs/sequencer/blob/0a5b16967bf2298683dc1e4f333ad380eb5da2c4/crates/committer_cli/src/block_hash.rs#L2)):*
> ```XML
> use serde::Deserialize;
> use starknet_api::block::{BlockHeaderWithoutHash, StarknetVersion};
> ```

any specific reason you use the StarknetVersion from starknet_api and not blockifier?
I prefer we use the enum, not the struct; we will try to migrate the starknet_api type to be an enum and combine the types in the near future



_Code quote:_
```XML
use starknet_api::block::{BlockHeaderWithoutHash, StarknetVersion};
```
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1201#-O8Wr7O72vG0iNVngHrL:-O8Wr7O72vG0iNVngHrM:bwwucl0) ([raw file](https://github.com/starkware-libs/sequencer/blob/0a5b16967bf2298683dc1e4f333ad380eb5da2c4/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L140)):*
> ```XML
>     if starknet_version < &BlockHashVersion::VO_13_3.into() {
>         fill_empty_signatures(&mut transaction_leaf_elements);
>     }
> ```

put the logic inside the `map` (non-blocking)



_Suggestion:_
```XML
    let transaction_leaf_elements: Vec<TransactionLeafElement> =
        transactions_data.iter().map(|tx_leaf| {
            if starknet_version < &BlockHashVersion::VO_13_3.into() && tx_leaf.transaction_signature.0.is_empty() {
                tx_leaf.transaction_signature.0.push(Felt::ZERO);
            }
            TransactionLeafElement::from(tx_leaf)
        ).collect();
```
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1201#-O8WsNpq3OByFelkOaK1:-O8WsNpq3OByFelkOaK2:bkoec3t) ([raw file](https://github.com/starkware-libs/sequencer/blob/0a5b16967bf2298683dc1e4f333ad380eb5da2c4/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L140)):*
> ```XML
>     if starknet_version < &BlockHashVersion::VO_13_3.into() {
>         fill_empty_signatures(&mut transaction_leaf_elements);
>     }
> ```

is this the desired behavior...?



_Code quote:_
```XML
    if starknet_version < &BlockHashVersion::VO_13_3.into() {
        fill_empty_signatures(&mut transaction_leaf_elements);
    }
```
___
*[`crates/starknet_api/src/block_hash/transaction_commitment.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1201#-O8Wrhk931rqL_Dpd2q2:-O8Wrhk931rqL_Dpd2q3:b-knu6d) ([raw file](https://github.com/starkware-libs/sequencer/blob/0a5b16967bf2298683dc1e4f333ad380eb5da2c4/crates/starknet_api/src/block_hash/transaction_commitment.rs#L55)):*
> ```XML
>         }
>     });
> }
> ```

if this is used only once, please inline it (and meld the logic into the `map` above)



_Code quote:_
```XML
// Replaces empty signatures with a single zero.
pub(crate) fn fill_empty_signatures(transaction_leaf_elements: &mut Vec<TransactionLeafElement>) {
    transaction_leaf_elements.iter_mut().for_each(|transaction_leaf_element| {
        if transaction_leaf_element.transaction_signature.0.is_empty() {
            transaction_leaf_element.transaction_signature.0.push(Felt::ZERO);
        }
    });
}
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1201)* status: all files reviewed, 4 unresolved discussions (waiting on @yoavGrs and @Yoni-Starkware)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1201)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/committer_cli/src/block_hash.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1201#-O8WqrYw2-rFsyLuIlfB:-O8XE-Bu1UhL_nIzm1zS:b-zhwo3y) ([raw file](https://github.com/starkware-libs/sequencer/blob/0a5b16967bf2298683dc1e4f333ad380eb5da2c4/crates/committer_cli/src/block_hash.rs#L2)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

any specific reason you use the StarknetVersion from starknet_api and not blockifier?
I prefer we use the enum, not the struct; we will try to migrate the starknet_api type to be an enum and combine the types in the near future
</blockquote></details>

It's the input of a function in starknet_api, that uses this type.
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1201#-O8Wr7O72vG0iNVngHrL:-O8ertBKAHMkug_w7Tpl:bvhas4) ([raw file](https://github.com/starkware-libs/sequencer/blob/0a5b16967bf2298683dc1e4f333ad380eb5da2c4/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L140)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

put the logic inside the `map` (non-blocking)
</blockquote></details>

Done a little differently
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1201#-O8WsNpq3OByFelkOaK1:-O8es8mz6LHt7CqlVDej:bgr3brl) ([raw file](https://github.com/starkware-libs/sequencer/blob/0a5b16967bf2298683dc1e4f333ad380eb5da2c4/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L140)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this the desired behavior...?
</blockquote></details>

Where the version < 0.13.3 `None` and `[]` becomes `[0]`.
(Now the input is `[]` for both cases; in the past, the input was only `None`.)
___
*[`crates/starknet_api/src/block_hash/transaction_commitment.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1201#-O8Wrhk931rqL_Dpd2q2:-O8ernhK9HSwkSkLjZCV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0a5b16967bf2298683dc1e4f333ad380eb5da2c4/crates/starknet_api/src/block_hash/transaction_commitment.rs#L55)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if this is used only once, please inline it (and meld the logic into the `map` above)
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1201)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs and @Yoni-Starkware)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 135 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1201#-O8f64mCCj7aggB_RK6Q:-O8f64mD5JB-LOW6s0oU:b-4069ph) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca08ad2a15608987abb570de8ef6ecc18977a41d/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L135)):*
> ```XML
>         .iter()
>         .map(|tx_leaf| {
>             let mut tx_leaf_element = TransactionLeafElement::from(tx_leaf);
> ```

why is the `let mut` needed? isn't there some variation of `iter` that gives you ownership and mutability of the input collection?



_Code quote:_
```XML
        .iter()
        .map(|tx_leaf| {
            let mut tx_leaf_element = TransactionLeafElement::from(tx_leaf);
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1201)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 135 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1201#-O8f64mCCj7aggB_RK6Q:-O8f78oa5XvEWz_dRmPp:b-f4ukrw) ([raw file](https://github.com/starkware-libs/sequencer/blob/ca08ad2a15608987abb570de8ef6ecc18977a41d/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L135)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is the `let mut` needed? isn't there some variation of `iter` that gives you ownership and mutability of the input collection?
</blockquote></details>

For pushing ZERO if needed

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1201#-:-O8fPKWpEE853KF2XNSl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
