### PR TITLE
chore(infra): use rust-toolchain.toml to align rust toolchains locally and in ci

### PR DESCRIPTION
**Pull request by alon-dotan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/656)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/656)* status: all files reviewed, 4 unresolved discussions (waiting on @alon-dotan-starkware and @nadin-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5T4SZS2Ydxlg3Nqg6Y:-O5T4SZS2Ydxlg3Nqg6Z:brlqn95) (no related file):*
1. delete rust_version.txt
2. update merge_branches.py to reflect your changes (see where rust_version.txt was used)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5T58AJ6OUIROdii6TU:-O5T58AJ6OUIROdii6TV:bsdwhfe) (no related file):*
please add @nimrod-starkware and @giladchase as reviewers

___
___
*[`rust-toolchain.toml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5T4b3E1ex8d1zSxIjh:-O5T4b3F0fOeSlr_gMCX:bx81ngr) ([raw file](https://github.com/starkware-libs/sequencer/blob/a61b3aabd34c64a9b7ac088b788c88d18e8b868d/rust-toolchain.toml#L5)):*
> ```TOML
> components = [ "rustfmt", "rustc-dev", "clippy" ]
> targets = [ "x86_64-unknown-linux-gnu" ]
> profile = "default"
> ```

this file defines the toolchain, so it should not be merged forward (i.e. once it exists on main, the merge script should checkout this file).
this means that any changes to this file will need to be cherry-picked to all relevant branches, right?



_Code quote:_
```TOML
[toolchain]
channel = "stable"
components = [ "rustfmt", "rustc-dev", "clippy" ]
targets = [ "x86_64-unknown-linux-gnu" ]
profile = "default"
```
___
*[`.github/actions/install_rust/action.yml` line 7 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5T5-zo15DdjfNMcjqc:-O5T5-zo15DdjfNMcjqd:bmbnfzb) ([raw file](https://github.com/starkware-libs/sequencer/blob/a61b3aabd34c64a9b7ac088b788c88d18e8b868d/.github/actions/install_rust/action.yml#L7)):*
> ```YAML
>     required: false
>     type: string
>     default: ''
> ```

no longer used...? how do we control component installation now?



_Code quote:_
```YAML
  components:
    description: "Optional: which additional components to install."
    required: false
    type: string
    default: ''
```

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/656)* status: 11 of 13 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, @nadin-Starkware, and @nimrod-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5T4SZS2Ydxlg3Nqg6Y:-O5T6HyRDrR4Gp2Nj3Q_:b-896fix) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. delete rust_version.txt
2. update merge_branches.py to reflect your changes (see where rust_version.txt was used)
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5T58AJ6OUIROdii6TU:-O5T6IFm44xD44pUErGk:b-896fix) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add @nimrod-starkware and @giladchase as reviewers
</blockquote></details>

Done.

___

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/656)* status: 11 of 13 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, @nadin-Starkware, and @nimrod-starkware)

___
*[`.github/actions/install_rust/action.yml` line 7 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5T5-zo15DdjfNMcjqc:-O5T6QeS7gFM1EZ4WV0P:bgwu6s9) ([raw file](https://github.com/starkware-libs/sequencer/blob/a61b3aabd34c64a9b7ac088b788c88d18e8b868d/.github/actions/install_rust/action.yml#L7)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no longer used...? how do we control component installation now?
</blockquote></details>

in the rust-toolchain.toml file

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/656)* status: 11 of 13 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, @nadin-Starkware, and @nimrod-starkware)

___
*[`rust-toolchain.toml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5T4b3E1ex8d1zSxIjh:-O5T6WRC8lsqoNtlAMw6:bw37mb5) ([raw file](https://github.com/starkware-libs/sequencer/blob/a61b3aabd34c64a9b7ac088b788c88d18e8b868d/rust-toolchain.toml#L5)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this file defines the toolchain, so it should not be merged forward (i.e. once it exists on main, the merge script should checkout this file).
this means that any changes to this file will need to be cherry-picked to all relevant branches, right?
</blockquote></details>

this will be like the bazel WORKSPACE file... it will define the exact toolchain to use for each commit

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/656)* status: all files reviewed, 3 unresolved discussions (waiting on @alon-dotan-starkware, @giladchase, @nadin-Starkware, and @nimrod-starkware)

___
*[`rust-toolchain.toml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5T4b3E1ex8d1zSxIjh:-O5T76y_3WwQwsUI6vGU:bwgbdhv) ([raw file](https://github.com/starkware-libs/sequencer/blob/a61b3aabd34c64a9b7ac088b788c88d18e8b868d/rust-toolchain.toml#L5)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

this will be like the bazel WORKSPACE file... it will define the exact toolchain to use for each commit
</blockquote></details>

yes, but we decided we want
1. stable version on `main`
2. fixed version on release branches
3. each release branch should have it's own (unchanging!) version
so, we need merge guards somehow.
load_blockifier and load_committer bzl files allow forward merging by splitting lines and writing each release branches "version" (of the crate) explicitly on separate lines.
how will this work with the `rust-toolchain.toml` file?
___
*[`.github/actions/install_rust/action.yml` line 7 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5T5-zo15DdjfNMcjqc:-O5T7TJK2rDM9oC3fw5G:b-odxo6b) ([raw file](https://github.com/starkware-libs/sequencer/blob/a61b3aabd34c64a9b7ac088b788c88d18e8b868d/.github/actions/install_rust/action.yml#L7)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

in the rust-toolchain.toml file
</blockquote></details>

so delete the inputs key please
___
*[`scripts/merge_branches.py` line 19 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5T6z1G36skKWGBnhQI:-O5T6z1G36skKWGBnhQJ:b-8ndlxp) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5167b98da57a9e553a3dfa99d7d1ab1012437da/scripts/merge_branches.py#L19)):*
> ```Python
> FINAL_BRANCH = "main"
> MERGE_PATHS_FILE = "scripts/merge_paths.json"
> FILES_TO_PRESERVE = {}
> ```

what about the toolchain file?



_Code quote:_
```Python
FILES_TO_PRESERVE = {}
```

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/656)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, @nadin-Starkware, and @nimrod-starkware)

___
*[`.github/actions/install_rust/action.yml` line 7 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5T5-zo15DdjfNMcjqc:-O5T8WWC658Z4jyfKI4u:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a61b3aabd34c64a9b7ac088b788c88d18e8b868d/.github/actions/install_rust/action.yml#L7)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

so delete the inputs key please
</blockquote></details>

Done.
___
*[`scripts/merge_branches.py` line 19 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5T6z1G36skKWGBnhQI:-O5T9c7R6QxmbmLKT5NZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5167b98da57a9e553a3dfa99d7d1ab1012437da/scripts/merge_branches.py#L19)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what about the toolchain file?
</blockquote></details>

Done.

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/656)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, @nadin-Starkware, and @nimrod-starkware)

___
*[`rust-toolchain.toml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5T4b3E1ex8d1zSxIjh:-O5T9jDe91ps-0eq3lBv:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a61b3aabd34c64a9b7ac088b788c88d18e8b868d/rust-toolchain.toml#L5)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes, but we decided we want
1. stable version on `main`
2. fixed version on release branches
3. each release branch should have it's own (unchanging!) version
so, we need merge guards somehow.
load_blockifier and load_committer bzl files allow forward merging by splitting lines and writing each release branches "version" (of the crate) explicitly on separate lines.
how will this work with the `rust-toolchain.toml` file?
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/656)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware, @giladchase, @nadin-Starkware, and @nimrod-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5T9oLIDwqBw2g55Qhv:-O5T9oLIDwqBw2g55Qhw:b-edkt8o) (no related file):*
pending python side PR success

___

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/656)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware, @giladchase, and @nadin-Starkware)

___
*[`scripts/merge_branches.py` line 19 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5TAuNt88Zx3mtBXuDi:-O5TAuNt88Zx3mtBXuDj:b-7i7p1z) ([raw file](https://github.com/starkware-libs/sequencer/blob/59239d8333376d3433b5a3ea2e90815de4303cce/scripts/merge_branches.py#L19)):*
> ```Python
> FINAL_BRANCH = "main"
> MERGE_PATHS_FILE = "scripts/merge_paths.json"
> FILES_TO_PRESERVE = {"rust-toolchain.toml"}
> ```

What if we have changes in that file that we want to keep in the source branch? (Changes that are unrelated to the rust version)
Do we expect that this file will change?



_Code quote:_
```Python
FILES_TO_PRESERVE = {"rust-toolchain.toml"}
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/656)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware, @giladchase, @nadin-Starkware, and @nimrod-starkware)

___
*[`scripts/merge_branches.py` line 19 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5TAuNt88Zx3mtBXuDi:-O5TCKa14froRj-Gug0i:b-hvg5ar) ([raw file](https://github.com/starkware-libs/sequencer/blob/59239d8333376d3433b5a3ea2e90815de4303cce/scripts/merge_branches.py#L19)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

What if we have changes in that file that we want to keep in the source branch? (Changes that are unrelated to the rust version)
Do we expect that this file will change?
</blockquote></details>

this is indeed a problem... but the advantages of using a rust-toolchain.toml file is worth it.
with this file, if you run `cargo build` locally, cargo will auto-install the specific toolchain required and build the workspace with it.
we should probably make the merge_branches script smarter: check that, if there is a diff in this file, that it is only in the toolchain version and nothing else - otherwise report a conflict or something

**Review by giladchase — COMMENTED** [review]
> Reviewed 9 of 11 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/656)* status: all files reviewed, 3 unresolved discussions (waiting on @alon-dotan-starkware and @nadin-Starkware)

___
*[`.github/actions/install_rust/action.yml` line 4 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5TMj859e7dIgGjYLyn:-O5TMj859e7dIgGjYLyo:bwosvih) ([raw file](https://github.com/starkware-libs/sequencer/blob/59239d8333376d3433b5a3ea2e90815de4303cce/.github/actions/install_rust/action.yml#L4)):*
> ```YAML
>   using: "composite"
>   steps:
>     - uses: moonrepo/setup-rust@v1
> ```

is this better than dtolnay/rust-toolchain?



_Code quote:_
```YAML
  - uses: moonrepo/setup-rust@v1
```
___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 35 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5TMqAU1heeMshydcsi:-O5TMqAU1heeMshydcsj:b-ikbtks) ([raw file](https://github.com/starkware-libs/sequencer/blob/00b348daecc03e490b263bd1bade8ddeb0744439/.github/workflows/blockifier_compiled_cairo.yml#L35)):*
> ```YAML
>       - uses: actions/checkout@v4
>       - uses: ./.github/actions/install_rust
>       - uses: Swatinem/rust-cache@v2
> ```

Curious, what issues has this causes? how do we caching without it?



_Code quote:_
```YAML
      - uses: Swatinem/rust-cache@v2
```

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/656)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @nadin-Starkware)

___
*[`.github/actions/install_rust/action.yml` line 4 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5TMj859e7dIgGjYLyn:-O5mc3W5DxlEs9ZVAAd_:b2z5pzq) ([raw file](https://github.com/starkware-libs/sequencer/blob/59239d8333376d3433b5a3ea2e90815de4303cce/.github/actions/install_rust/action.yml#L4)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[according to them, yes](https://github.com/moonrepo/setup-rust?tab=readme-ov-file#dtolnayrust-toolchain)
</blockquote></details>

yes looks like dtonlay's is basic by design.
In particular, dtolnay [refuses to support rust-toolchain.toml](https://github.com/dtolnay/rust-toolchain/issues/77) which might make it irrelevant for us.
However, maybe there might be a better way of doing this if dtolnay isn't supporting it, I couldn't find it.

Also note that we're switching from a 1K-star action to a 100 star one, but I have no better alternative :sweat_smile:  
___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 35 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5TMqAU1heeMshydcsi:-O5qFD0r5gSks2Elt-Ul:b-zgkru4) ([raw file](https://github.com/starkware-libs/sequencer/blob/00b348daecc03e490b263bd1bade8ddeb0744439/.github/workflows/blockifier_compiled_cairo.yml#L35)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Curious, what issues has this causes? how do we caching without it?
</blockquote></details>

looks like setup-rust handles caching [out of the box,](https://github.com/moonrepo/setup-rust?tab=readme-ov-file#swatinemrust-cache)

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/656)* status: 12 of 16 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @giladchase, and @nadin-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/656#-O5T9oLIDwqBw2g55Qhv:-O6KKv3e4eLrcRVrOxNG:bnqv6uw) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

pending python side PR success
</blockquote></details>

https://reviewable.io/reviews/starkware-industries/starkware/35901

___

**Review by alon-dotan-starkware — COMMENTED** [review]
> Reviewed 8 of 11 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/656)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @giladchase, and @nadin-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/656)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
