### PR TITLE
chore: add remote servers struct

### PR DESCRIPTION
**Pull request by nadin-Starkware**
**Stack**:
- #2047
- #2041
- #2040 ⬅
- #2035
- #2034
- #2033
- #2032
- #2030
- #2029
- #2028

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2040)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/starknet_sequencer_node/src/servers.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2040#-OBgSDTh2PKmXFo7R-wp:-OBgSDTh2PKmXFo7R-wq:bafrsom) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4f55c8c0f66ef2fd19ec8ed6579b41295c4c79f/crates/starknet_sequencer_node/src/servers.rs#L47)):*
> ```XML
> // Component servers that can run remotely.
> pub struct RemoteServers {
>     pub batcher: Option<Box<RemoteBatcherServer>>,
> ```

Will `pub(crate) ` work?



_Code quote:_
```XML
pub 
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2040)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sequencer_node/src/servers.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2040#-OBgSDTh2PKmXFo7R-wp:-OBtaBdj5fr6ZMmOaiuu:byzy34y) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4f55c8c0f66ef2fd19ec8ed6579b41295c4c79f/crates/starknet_sequencer_node/src/servers.rs#L47)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Will `pub(crate) ` work?
</blockquote></details>

Yes, I’ll replace it in a later PR—dropping it now would cause a compilation error due to unused code. Adding TODO.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2040#-:-OBu7F5aA81LqaLc41Rc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Comment by nadin-Starkware** [comment]
✓ Commit merged in pull request [#2041](https://github.com/starkware-libs/sequencer/pull/2041)

**Pull request closed without merging**
