### PR TITLE
feat(consensus): add metric for sync in consensus and update the simulation script

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/490)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/490?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#490** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/490?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#465** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/465?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#414** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/414?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#413** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/413?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#412** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/412?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#409** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/409?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#406** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/406?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#404** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/404?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#389** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/389?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#403](https://github.com/starkware-libs/sequencer/pull/403) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/403?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#387** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/387?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#386** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/386?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/490)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/490#-O4ZvkYh34TIkkl0as9P:-O4ZvkYh34TIkkl0as9Q:b-e386kz) ([raw file](https://github.com/starkware-libs/sequencer/blob/9edafbe99d4b8d4a2aa12c8bc973ab490cbd24ae/crates/sequencing/papyrus_consensus/src/manager.rs#L71)):*
> ```XML
>                 current_height = current_height.unchecked_next();
>             },
>             sync_height = sync_height(current_height, &mut sync_receiver) => {
> ```

I think this will set the count to 1, not increment it by one, is it your intention?

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/490)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/490#-O4ZvkYh34TIkkl0as9P:-O4_-Rie0fIlXnpN_PEH:b-s0t4j0) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9e1a5eb4a781126599fcc4fbfb92b9d17186fb3/crates/sequencing/papyrus_consensus/src/manager.rs#L71)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I think this will set the count to 1, not increment it by one, is it your intention?
</blockquote></details>

Not my intention. I ran simulations where the counter seems to increase as expected (it definitely was above 1).

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/490#-:-O4_04OcEwfwrpCTAmX0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

**Comment by DvirYo-starkware** [comment]
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/490#-O4ZvkYh34TIkkl0as9P:-O4_0jsT8dx0qWrDafWb:bszaf4b) ([raw file](https://github.com/starkware-libs/sequencer/blob/b9e1a5eb4a781126599fcc4fbfb92b9d17186fb3/crates/sequencing/papyrus_consensus/src/manager.rs#L71)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Not my intention. I ran simulations where the counter seems to increase as expected (it definitely was above 1).
</blockquote></details>

consider using `increment_counter!` instead

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/490)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/490#-O4ZvkYh34TIkkl0as9P:-O4_4TBw0PPqm3g44JR_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0c2254fbc4e1cd93d7ddf76022721794456e0dca/crates/sequencing/papyrus_consensus/src/manager.rs#L71)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

consider using `increment_counter!` instead
</blockquote></details>

Done.

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/490#-:-O4_5Kah1qFSP7ug9n0k:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Comment by matan-starkware** [comment]
### Merge activity

* **Aug 18, 6:54 AM EDT**: @matan-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/490).

**Pull request merged**
