### PR TITLE
refactor(blockifier): clean runnable contract class code

### PR DESCRIPTION
**Pull request by noaov1**

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1745)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1745#-OB-sE061hkkRDRcZItt:-OB0E3vNEhwluaDEP7OV:bb71op5) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you sure the deleted blockifier public API is unused externally?
</blockquote></details>

Opps

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1745)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1745#-OB-sE061hkkRDRcZItt:-OB0LNQUEUC5l2cAiUPj:bicqjmj) (no related file):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Opps
</blockquote></details>

I meant the two from_file functions...
also, please open a py side PR if you touch the native blockifier

___

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1745)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1745#-OB-sE061hkkRDRcZItt:-OB0MDIS5DLNDEbbx6dD:b-uacjdl) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I meant the two from_file functions...
also, please open a py side PR if you touch the native blockifier
</blockquote></details>

The two `from_file` are test utils which are no linger used in the repo. 
I don't know if they are used but given the recent change they can be exchanged by the new `from_file` methods.

___

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1745#-:-OB0pNKG-Ajr2rBztKA9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
