### PR TITLE
chore(blockifier): update cairo version to 2.9.0

### PR DESCRIPTION
**Pull request by PearsonWhite**

### CODE REVIEW

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1854)* status: 17 of 24 files reviewed, 1 unresolved discussion (waiting on @meship-starkware, @noaov1, and @PearsonWhite)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2298 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1854#-OB5TPOO41lh5JENpGlx:-OB5TPOO41lh5JENpGly:b-nj5l8h) ([raw file](https://github.com/starkware-libs/sequencer/blob/2285a95b3d8b7a0e990d2631b0d8a06189b4efe6/crates/blockifier/src/transaction/transactions_test.rs#L2298)):*
> ```XML
>                     + 6,
>             ),
>             (BuiltinName::pedersen, 11 + payload_size),
> ```

Is there a reason for this reordering? Or is it just the formatter?



_Code quote:_
```XML
            (
                BuiltinName::range_check,
                get_tx_resources(TransactionType::L1Handler).builtin_instance_counter
                    [&BuiltinName::range_check]
                    + 6,
            ),
            (BuiltinName::pedersen, 11 + payload_size),
```

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 4 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1854)* status: 17 of 24 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @PearsonWhite)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 11 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1854)* status: 17 of 24 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @PearsonWhite)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 2 of 17 files at r1, 3 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1854)* status: 20 of 24 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @PearsonWhite)

___
*[`crates/gateway/src/rpc_state_reader_test.rs` line 167 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1854#-OB5cqL61tbVAMQObgF8:-OB5cqL7-RW_RRt574eN:b-m91b38) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac7de69d522bebec18ceb5e27e8080ffa9ed4d1/crates/gateway/src/rpc_state_reader_test.rs#L167)):*
> ```XML
>         hints: Default::default(),
>         pythonic_hints: Default::default(),
>         entry_points_by_type: Default::default(),
> ```

Why can't you use ..Default::default()? 



_Code quote:_
```XML
        compiler_version: "0.0.0".to_string(),
        prime: Default::default(),
        bytecode: Default::default(),
        bytecode_segment_lengths: Default::default(),
        hints: Default::default(),
        pythonic_hints: Default::default(),
        entry_points_by_type: Default::default(),
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1854)* status: all files reviewed, 5 unresolved discussions (waiting on @PearsonWhite)

___
*[`Cargo.toml` line 99 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1854#-OB5cTMlBTplGE8RZEgh:-OB5cTMlBTplGE8RZEgi:b-3earr2) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac7de69d522bebec18ceb5e27e8080ffa9ed4d1/Cargo.toml#L99)):*
> ```TOML
> cairo-lang-starknet-classes = "2.9.0-dev.0"
> cairo-lang-utils = "2.9.0-dev.0"
> # Important: when updated, make sure to update the cairo-native submodule as well.
> ```

Can you please update the git submodel?



_Code quote:_
```TOML
# Important: when updated, make sure to update the cairo-native submodule as well.
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/sha256.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1854#-OB5ZPLJ8SgB-OWZrhZM:-OB5ZPLK4x3HGJOaKWWy:b483wyg) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac7de69d522bebec18ceb5e27e8080ffa9ed4d1/crates/blockifier/src/execution/syscalls/syscall_tests/sha256.rs#L1)):*
> ```XML
> use pretty_assertions::assert_eq;
> ```

Why is it needed now?



_Code quote:_
```XML
use pretty_assertions::assert_eq;
```
___
*[`crates/gateway/src/rpc_state_reader_test.rs` line 168 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1854#-OB5cwgkEimDupRH-7PP:-OB5cwgkEimDupRH-7PQ:bravb6a) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac7de69d522bebec18ceb5e27e8080ffa9ed4d1/crates/gateway/src/rpc_state_reader_test.rs#L168)):*
> ```XML
>         pythonic_hints: Default::default(),
>         entry_points_by_type: Default::default(),
>     };
> ```

What is the reason for this change?



_Code quote:_
```XML
        prime: Default::default(),
        bytecode: Default::default(),
        bytecode_segment_lengths: Default::default(),
        hints: Default::default(),
        pythonic_hints: Default::default(),
        entry_points_by_type: Default::default(),
    };
```

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1854)* status: 18 of 25 files reviewed, 4 unresolved discussions (waiting on @meship-starkware and @PearsonWhite)

**Review by PearsonWhite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1854)* status: 17 of 25 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`Cargo.toml` line 99 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1854#-OB5cTMlBTplGE8RZEgh:-OB7K_wt9ZYEhIAsWY3B:b-bw8e14) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac7de69d522bebec18ceb5e27e8080ffa9ed4d1/Cargo.toml#L99)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please update the git submodel?
</blockquote></details>

Updated.
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/sha256.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1854#-OB5ZPLJ8SgB-OWZrhZM:-OB7KXj96H_Pfy285xig:bss4a2b) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac7de69d522bebec18ceb5e27e8080ffa9ed4d1/crates/blockifier/src/execution/syscalls/syscall_tests/sha256.rs#L1)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it needed now?
</blockquote></details>

Removed.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2298 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1854#-OB5TPOO41lh5JENpGlx:-OB7Y5Nl2O0uiN6ZQdmG:b-cnr9wb) ([raw file](https://github.com/starkware-libs/sequencer/blob/2285a95b3d8b7a0e990d2631b0d8a06189b4efe6/crates/blockifier/src/transaction/transactions_test.rs#L2298)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Is there a reason for this reordering? Or is it just the formatter?
</blockquote></details>

I thought this was causing a test failure, but it wasn't. Reverted back.
___
*[`crates/gateway/src/rpc_state_reader_test.rs` line 167 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1854#-OB5cqL61tbVAMQObgF8:-OB7YzL--Ee2BD2JzZAJ:b-ymgjkt) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac7de69d522bebec18ceb5e27e8080ffa9ed4d1/crates/gateway/src/rpc_state_reader_test.rs#L167)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why can't you use ..Default::default()?
</blockquote></details>

`CasmContractClass::Default` was removed from cairo in this PR: https://github.com/starkware-libs/cairo/pull/6383
___
*[`crates/gateway/src/rpc_state_reader_test.rs` line 168 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1854#-OB5cwgkEimDupRH-7PP:-OB7ZKS0AdLYGnYrGoJi:b-ymgjkt) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac7de69d522bebec18ceb5e27e8080ffa9ed4d1/crates/gateway/src/rpc_state_reader_test.rs#L168)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What is the reason for this change?
</blockquote></details>

`CasmContractClass::Default` was removed from cairo in this PR: https://github.com/starkware-libs/cairo/pull/6383

**Review by meship-starkware — APPROVED** [review]
> Reviewed 9 of 9 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1854)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware and @noaov1)

**Review by avi-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1854)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
> Reviewed 6 of 9 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1854)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PearsonWhite)

**Pull request merged**
