### PR TITLE
feat(blockifier): add support for secp256k1 syscall for native

### PR DESCRIPTION
**Pull request by varex83**
Should go after #1675 , #1813 , #1546 , #1545 

Commit history will be changed in the future, so "feat: add support for keccak syscall" will be removed

### CODE REVIEW

**Review by meship-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1940)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware and @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1940#-:-OC2LLgV-zf2OfWXq1hE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1940)* status: all files reviewed, 2 unresolved discussions (waiting on @varex83)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 642 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1940#-OC2SZo63bCa7MqUYKAX:-OC2SZo63bCa7MqUYKAY:b-jdru3b) ([raw file](https://github.com/starkware-libs/sequencer/blob/318e8f1b673a62ec13e522095cb3a86d0c8e1e14/crates/blockifier/src/execution/native/syscall_handler.rs#L642)):*
> ```XML
>         Secp256Point::new(x, y)
>             .map(|op| op.map(|p| p.into()))
>             .map_err(|e| self.handle_error(remaining_gas, e))
> ```

Let's be consistent with #1675 .



_Suggestion:_
```XML
        Secp256Point::new(x, y)
            .map(|option| option.map(|p| p.into()))
            .map_err(|err| self.handle_error(remaining_gas, err))
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 680 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1940#-OC2SrSE5SeFqPitLL1T:-OC2SrSE5SeFqPitLL1U:b-jdru3b) ([raw file](https://github.com/starkware-libs/sequencer/blob/318e8f1b673a62ec13e522095cb3a86d0c8e1e14/crates/blockifier/src/execution/native/syscall_handler.rs#L680)):*
> ```XML
>         Secp256Point::get_point_from_x(x, y_parity)
>             .map(|op| op.map(|p| p.into()))
>             .map_err(|e| self.handle_error(remaining_gas, e))
> ```

Let's be consistent with #1675 .



_Suggestion:_
```XML
        Secp256Point::get_point_from_x(x, y_parity)
            .map(|option| option.map(|p| p.into()))
            .map_err(|err| self.handle_error(remaining_gas, err))
```

**Review by avi-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1940)* status: all files reviewed, 2 unresolved discussions (waiting on @varex83)

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1940)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @varex83)

**Review by Yoni-Starkware — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1940#-:-OCDiB7dCpVyUXJ5GMZ0:bnfp4nl)* status: 3 of 81 files reviewed, all discussions resolved (waiting on @avi-starkware and @meship-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1940#-:-OCDihx60oNaYIbhKmlz:bnfp4nl)* status: 3 of 81 files reviewed, all discussions resolved (waiting on @avi-starkware and @meship-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 77 of 80 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1940)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @varex83)

**Pull request merged**
