### PR TITLE
refactor(starknet_api): represent starknet version as vec of ints

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/838)

### CODE REVIEW

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/838)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/papyrus_protobuf/src/converters/header.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/838#-O6zrsA62L5W6Pad2iwE:-O6zrsA62L5W6Pad2iwF:b-i0q2gq) ([raw file](https://github.com/starkware-libs/sequencer/blob/07739f4baabfcf2a17e21373627e0015af1424ab/crates/papyrus_protobuf/src/converters/header.rs#L147)):*
> ```XML
>                 });
>             }
>         };
> ```

@ShahakShama
Does that make sense?



_Code quote:_
```XML
        let starknet_version = match StarknetVersion::try_from(value.protocol_version.to_owned()) {
            Ok(version) => version,
            Err(_) => {
                return Err(ProtobufConversionError::OutOfRangeValue {
                    type_description: "starknet version",
                    value_as_str: value.protocol_version,
                });
            }
        };
```

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/838#-:-O7-8yvm2wI85x1UbXCu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @yoavGrs)

___
*[`crates/papyrus_protobuf/src/converters/header.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/838#-O6zrsA62L5W6Pad2iwE:-O7-2F7T0s1TVLAZ_uLT:b2nign6) ([raw file](https://github.com/starkware-libs/sequencer/blob/07739f4baabfcf2a17e21373627e0015af1424ab/crates/papyrus_protobuf/src/converters/header.rs#L147)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

@ShahakShama
Does that make sense?
</blockquote></details>

yes

**Review by nimrod-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/838)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/838)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/838)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
