### PR TITLE
feat: use the build script to download the cairo crate from the starkware release page

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/597)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/597?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#599** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/599?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#598** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/598?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#597** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/597?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#566** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/566?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#331](https://github.com/starkware-libs/sequencer/pull/331) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/331?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#581](https://github.com/starkware-libs/sequencer/pull/581) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/581?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/597)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/starknet_sierra_compile/build.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5HO7Wg0zYsL9kppm4U:-O5HO7Wg0zYsL9kppm4V:b-umvh4q) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b34427d1000546a149ea410b6d18dcd47bb86f3/crates/starknet_sierra_compile/build.rs#L12)):*
> ```XML
> }
> 
> /// Downloads the cairo crate from the StarkWare release page and extracts it into the target.
> ```

Please add a comment explaining why we are doing this.
___
*[`crates/starknet_sierra_compile/build.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5HNzv_CyaHQOap-BYD:-O5HNzv_CyaHQOap-BYE:bnkp3rh) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b34427d1000546a149ea410b6d18dcd47bb86f3/crates/starknet_sierra_compile/build.rs#L17)):*
> ```XML
>     let out_dir = Path::new(&out_dir);
>     let target_dir =
>         out_dir.ancestors().nth(3).expect("Failed to navigate up three levels from OUT_DIR");
> ```

Why are we going up 3 levels?



_Code quote:_
```XML
    let target_dir =
        out_dir.ancestors().nth(3).expect("Failed to navigate up three levels from OUT_DIR");
```
___
*[`crates/starknet_sierra_compile/build.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5HSLMI7wO5UQrfFNVH:-O5HSLMI7wO5UQrfFNVI:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b34427d1000546a149ea410b6d18dcd47bb86f3/crates/starknet_sierra_compile/build.rs#L29)):*
> ```XML
> 
>     let url = "https://github.com/starkware-libs/cairo/releases/download/v2.7.0-rc.1/release-x86_64-unknown-linux-musl.tar.gz";
>     let file_path = target_dir.join("release-x86_64-unknown-linux-musl.tar.gz");
> ```





_Suggestion:_
```XML
download_path
```
___
*[`crates/starknet_sierra_compile/build.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5HOpr51KGu7fsU5vWO:-O5HOpr51KGu7fsU5vWP:bgsmlh8) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b34427d1000546a149ea410b6d18dcd47bb86f3/crates/starknet_sierra_compile/build.rs#L43)):*
> ```XML
>     if !status.success() {
>         panic!("Failed to download the cairo tar");
>     }
> ```

Can it happen? 
You called `expect()` in the previous line.



_Code quote:_
```XML
    if !status.success() {
        panic!("Failed to download the cairo tar");
    }
```
___
*[`crates/starknet_sierra_compile/build.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5HP-uB7cBcB79zP3mG:-O5HP-uB7cBcB79zP3mH:brhumzt) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b34427d1000546a149ea410b6d18dcd47bb86f3/crates/starknet_sierra_compile/build.rs#L54)):*
> ```XML
>         .expect("Failed to execute tar command");
> 
>     if !status.success() {
> ```

Same here.



_Code quote:_
```XML
if !status.success() {
```
___
*[`crates/starknet_sierra_compile/build.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5HRmC-34ZtgKjjeJ3m:-O5HRmC-34ZtgKjjeJ3n:b9jsrwc) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b34427d1000546a149ea410b6d18dcd47bb86f3/crates/starknet_sierra_compile/build.rs#L57)):*
> ```XML
>         panic!("Failed to extract the cairo crate from zip");
>     }
> ```

Please add an assertion that `cairo_folder_dir` now exist.

**Review by dafnamatsry — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/597)* status: all files reviewed, 6 unresolved discussions (waiting on @ArniStarkware)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/597)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/starknet_sierra_compile/build.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5HO7Wg0zYsL9kppm4U:-O5Hko1jCy9aDwzu6mfX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b34427d1000546a149ea410b6d18dcd47bb86f3/crates/starknet_sierra_compile/build.rs#L12)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please add a comment explaining why we are doing this.
</blockquote></details>

Done.
___
*[`crates/starknet_sierra_compile/build.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5HNzv_CyaHQOap-BYD:-O5HlCGkDh11SgE0HPzV:b-iabvo2) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b34427d1000546a149ea410b6d18dcd47bb86f3/crates/starknet_sierra_compile/build.rs#L17)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why are we going up 3 levels?
</blockquote></details>

Added a comment.

For tests, `out_dir` is: ```/home/arni/workspace/sequencer/target/debug/build/starknet_sierra_compile-5f5ad2b0ae546c28/out``` (`starknet_sierra_compile-5f5ad2b0ae546c28` = `starknet_sierra_compile-BuildNumber`)

We want to go down at least two levels as we want the `starknet-sierra-compile` binary to be available outside the specific build folder. We encounter a problem where one crate must have the binary available for other crates (for example: `gateway`). This solves this issue as for every crate - if we navigate two levels up - they share the path.

We navigate a third level up just for consistency. The `build` folder contains only built crates. The build flavor folder (`debug` in this case - other things in production),  contains such run artifacts.
___
*[`crates/starknet_sierra_compile/build.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5HSLMI7wO5UQrfFNVH:-O5HoRqQ3_npkgbXkpa2:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b34427d1000546a149ea410b6d18dcd47bb86f3/crates/starknet_sierra_compile/build.rs#L29)):*
> ```XML
> 
>     let url = "https://github.com/starkware-libs/cairo/releases/download/v2.7.0-rc.1/release-x86_64-unknown-linux-musl.tar.gz";
>     let file_path = target_dir.join("release-x86_64-unknown-linux-musl.tar.gz");
> ```

Done.
___
*[`crates/starknet_sierra_compile/build.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5HOpr51KGu7fsU5vWO:-O5HpGzNE_F7sZHPUMb6:b-mwmv12) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b34427d1000546a149ea410b6d18dcd47bb86f3/crates/starknet_sierra_compile/build.rs#L43)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can it happen? 
You called `expect()` in the previous line.
</blockquote></details>

`.expect` handles the case where the `Command` fails to execute (e.g., if the `wget` command is not found). The `if` statement checks if the `wget` command was executed but failed (e.g., due to a network error or the file not existing at the specified URL).
___
*[`crates/starknet_sierra_compile/build.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5HP-uB7cBcB79zP3mG:-O5Hq351C2AvR7bn3ZVu:b-5h08c7) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b34427d1000546a149ea410b6d18dcd47bb86f3/crates/starknet_sierra_compile/build.rs#L54)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

same here.
___
*[`crates/starknet_sierra_compile/build.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5HRmC-34ZtgKjjeJ3m:-O5Hr2OX0P8seYe3uGGK:b-xejklb) ([raw file](https://github.com/starkware-libs/sequencer/blob/4b34427d1000546a149ea410b6d18dcd47bb86f3/crates/starknet_sierra_compile/build.rs#L57)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please add an assertion that `cairo_folder_dir` now exist.
</blockquote></details>

Done.
I also reordered the lines so the .tar file would be removed before we panic.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/597)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_sierra_compile/build.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5IWL4HEpycm9uD2_tq:-O5IWL4HEpycm9uD2_tr:b-b3ognk) ([raw file](https://github.com/starkware-libs/sequencer/blob/3635605c6c5f3da7f7a6e4f113197b3ae98e6270/crates/starknet_sierra_compile/build.rs#L57)):*
> ```XML
>         .current_dir(target_dir)
>         .status()
>         .expect("Failed to execute tar command");
> ```

If it fails here, you won't clean up the downloaded file.
Maybe only the download dir can be `out_dir`?



_Code quote:_
```XML
.expect("Failed to execute tar command");
```

**Review by dafnamatsry — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/597)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/597)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

___
*[`crates/starknet_sierra_compile/build.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5IWL4HEpycm9uD2_tq:-O5IjdXTDGTaLa0duo1L:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3635605c6c5f3da7f7a6e4f113197b3ae98e6270/crates/starknet_sierra_compile/build.rs#L57)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

If it fails here, you won't clean up the downloaded file.
Maybe only the download dir can be `out_dir`?
</blockquote></details>

Done.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/597)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/starknet_sierra_compile/build.rs` line 23 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5mM6j2BQre87G4OMce:-O5mM6j2BQre87G4OMcf:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/68b8010f3eccfad956235a06a55b0832a881289a/crates/starknet_sierra_compile/build.rs#L23)):*
> ```XML
>     )
>     .to_path_buf();
>     // Get the crate's `OUT_DIR` and navigates up to reach the `target/BUILD_FLAVOR` directory.
> ```





_Suggestion:_
```XML
Get the crate's `OUT_DIR` and navigate up to reach the `target/BUILD_FLAVOR` directory.
```
___
*[`crates/starknet_sierra_compile/build.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5mQtXC5W5vnZVG3e10:-O5mQtXC5W5vnZVG3e11:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/68b8010f3eccfad956235a06a55b0832a881289a/crates/starknet_sierra_compile/build.rs#L48)):*
> ```XML
>         }
>         Err(_) => {
>             println!("The starknet-sierra-compile binary is not installed.");
> ```





_Suggestion:_
```XML
"The starknet-sierra-compile binary is not installed. Installing the required version."
```
___
*[`crates/starknet_sierra_compile/build.rs` line 62 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5mSGdX0yU6EcbN94qg:-O5mSGdX0yU6EcbN94qh:bv2e0jg) ([raw file](https://github.com/starkware-libs/sequencer/blob/68b8010f3eccfad956235a06a55b0832a881289a/crates/starknet_sierra_compile/build.rs#L62)):*
> ```XML
>             BINARY_NAME,
>             "--root",
>             temp_cargo_path.to_str().expect("Failed to convert cargo_path to str"),
> ```

Why not install it directly in the shared folder?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/597)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/starknet_sierra_compile/build.rs` line 23 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5mM6j2BQre87G4OMce:-O5mSxR-89QZrpEyFegA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/68b8010f3eccfad956235a06a55b0832a881289a/crates/starknet_sierra_compile/build.rs#L23)):*
> ```XML
>     )
>     .to_path_buf();
>     // Get the crate's `OUT_DIR` and navigates up to reach the `target/BUILD_FLAVOR` directory.
> ```

Done.
___
*[`crates/starknet_sierra_compile/build.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5mQtXC5W5vnZVG3e10:-O5mTAq_DEtCaybi6dqP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/68b8010f3eccfad956235a06a55b0832a881289a/crates/starknet_sierra_compile/build.rs#L48)):*
> ```XML
>         }
>         Err(_) => {
>             println!("The starknet-sierra-compile binary is not installed.");
> ```

Done.
___
*[`crates/starknet_sierra_compile/build.rs` line 62 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5mSGdX0yU6EcbN94qg:-O5mU0OG-qU9WFLicfSt:b4xkvb1) ([raw file](https://github.com/starkware-libs/sequencer/blob/68b8010f3eccfad956235a06a55b0832a881289a/crates/starknet_sierra_compile/build.rs#L62)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why not install it directly in the shared folder?
</blockquote></details>

Before the `remove_dir_all` command, the following files are created:

```
-- out
 |
 -- cargo
  |
   -- bin // folder
   -- .crates.toml
   -- .crates2.json
```

My goal was to hide all of this garbage in the crates' build / out dir where it belongs.

I do agree that we can do less. We can either:
1. Install the binary in a shared location directly and remove the garbage (mentioned above).
2. Install as in this PR. Move the file to the shared dir. Don't bother deleting the garbage (i.e., delete the `std::fs::remove_dir_all` command).

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/597#-:-O5qRmZ_6RJJiY5cYFP_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/starknet_sierra_compile/build.rs` line 62 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/597#-O5mSGdX0yU6EcbN94qg:-O5qR_Ee6PSTZAw-HmQH:brsv2z4) ([raw file](https://github.com/starkware-libs/sequencer/blob/68b8010f3eccfad956235a06a55b0832a881289a/crates/starknet_sierra_compile/build.rs#L62)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Before the `remove_dir_all` command, the following files are created:

```
-- out
 |
 -- cargo
  |
   -- bin // folder
   -- .crates.toml
   -- .crates2.json
```

My goal was to hide all of this garbage in the crates' build / out dir where it belongs.

I do agree that we can do less. We can either:
1. Install the binary in a shared location directly and remove the garbage (mentioned above).
2. Install as in this PR. Move the file to the shared dir. Don't bother deleting the garbage (i.e., delete the `std::fs::remove_dir_all` command).
</blockquote></details>

Let's keep it as it is now :)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Sep 3, 2:07 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/597).

**Pull request merged**
