### PR TITLE
chore(sequencer_node): rename sequencer node package

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #1516
- #1513 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1513)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/task_executor/src/commitlint.config.js` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1513#-O9n-TMt0zQ26MFB1hTw:-O9n-TMt0zQ26MFB1hTx:b4aph0b) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a2e48d59c71a9c3ced53fd49366fa5ed81e6ea6/crates/task_executor/src/commitlint.config.js#L1)):*
> ```JavaScript
> const Configuration = {
> ```

What is this file addition? Is it related to the PR?

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1513)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/task_executor/src/commitlint.config.js` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1513#-O9n-TMt0zQ26MFB1hTw:-O9oVCu28TkzzZ4Ggw71:bwbxgb) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a2e48d59c71a9c3ced53fd49366fa5ed81e6ea6/crates/task_executor/src/commitlint.config.js#L1)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What is this file addition? Is it related to the PR?
</blockquote></details>

No, mistake, deleted :pray:

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 5 of 12 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1513)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#1516](https://github.com/starkware-libs/sequencer/pull/1516)

**Pull request closed without merging**
