### PR TITLE
refactor(network): rename BroadcastedMessageManager to BroadcastedMessageMetadata

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1144)

### CODE REVIEW

**Review by matan-starkware — APPROVED** [review]
> Reviewed 2 of 6 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1144)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by AlonLStarkWare — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1144)* status: 15 of 16 files reviewed, 11 unresolved discussions (waiting on @matan-starkware and @ShahakShama)

___
*[`crates/mempool_p2p/src/sender/test.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1144#-O98xoX73hC0oStE2ugE:-O98xoX73hC0oStE2ugF:b-lqou7z) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bea22ce66d6698d0dc873ef1f1f20dc1c87c4d2/crates/mempool_p2p/src/sender/test.rs#L43)):*
> ```XML
>         subscriber_channels;
>     let BroadcastNetworkMock { mut continue_propagation_receiver, .. } = mock_network;
>     let propagation_manager = BroadcastedMessageMetadata::get_test_instance(&mut get_rng());
> ```

missed manager to metadata
___
*[`crates/mempool_p2p/src/sender/test.rs` line 46 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1144#-O98xp74ApQHKqChMmOm:-O98xp74ApQHKqChMmOn:b-lqou7z) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bea22ce66d6698d0dc873ef1f1f20dc1c87c4d2/crates/mempool_p2p/src/sender/test.rs#L46)):*
> ```XML
>     let mut mempool_sender = MempoolP2pSender::new(broadcast_topic_client);
>     mempool_sender
>         .handle_request(MempoolP2pSenderRequest::ContinuePropagation(propagation_manager.clone()))
> ```

missed manager to metadata
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 237 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1144#-O98xdwn-o_OGLubLz3k:-O98xdwo91hOrvwg2cKh:b-hj6gms) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bea22ce66d6698d0dc873ef1f1f20dc1c87c4d2/crates/papyrus_network/src/network_manager/mod.rs#L237)):*
> ```XML
>         let reported_messages_fn: fn(
>             BroadcastedMessageMetadata,
>         ) -> Ready<Result<PeerId, SendError>> = |broadcasted_message_manager| {
> ```

missed manager to metadata (also in the following line)
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 885 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1144#-O98xz7m97KeC4TAj6Xd:-O98xz7m97KeC4TAj6Xe:b-lqou7z) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bea22ce66d6698d0dc873ef1f1f20dc1c87c4d2/crates/papyrus_network/src/network_manager/mod.rs#L885)):*
> ```XML
>     async fn report_peer(
>         &mut self,
>         broadcasted_message_manager: BroadcastedMessageMetadata,
> ```

missed manager to metadata
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 892 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1144#-O98y1Gg-qPiQ0z9cXdF:-O98y1Gg-qPiQ0z9cXdG:b-lqou7z) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bea22ce66d6698d0dc873ef1f1f20dc1c87c4d2/crates/papyrus_network/src/network_manager/mod.rs#L892)):*
> ```XML
>     async fn continue_propagation(
>         &mut self,
>         broadcasted_message_manager: &BroadcastedMessageMetadata,
> ```

missed manager to metadata
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 207 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1144#-O98y3YS8mBWgSw803pm:-O98y3YS8mBWgSw803pn:b-lqou7z) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bea22ce66d6698d0dc873ef1f1f20dc1c87c4d2/crates/papyrus_network/src/network_manager/test.rs#L207)):*
> ```XML
> 
>     // TODO (shahak): Add test for continue propagation.
>     fn continue_propagation(&mut self, _message_manager: super::BroadcastedMessageMetadata) {
> ```

missed manager to metadata
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 101 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1144#-O98y4my0t3qgMXfj-it:-O98y4my0t3qgMXfj-iu:b-lqou7z) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bea22ce66d6698d0dc873ef1f1f20dc1c87c4d2/crates/papyrus_network/src/network_manager/test_utils.rs#L101)):*
> ```XML
>         futures::channel::mpsc::channel(CHANNEL_BUFFER_SIZE);
>     let reported_messages_fn: fn(BroadcastedMessageMetadata) -> Ready<Result<PeerId, SendError>> =
>         |broadcasted_message_manager| {
> ```

missed manager to metadata
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1144#-O98y6Y74dxDnkvkgwWY:-O98y6Y74dxDnkvkgwWZ:b-lqou7z) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bea22ce66d6698d0dc873ef1f1f20dc1c87c4d2/crates/sequencing/papyrus_consensus/src/manager_test.rs#L89)):*
> ```XML
> 
> async fn send(sender: &mut MockBroadcastedMessagesSender<ConsensusMessage>, msg: ConsensusMessage) {
>     let broadcasted_message_manager = BroadcastedMessageMetadata::get_test_instance(&mut get_rng());
> ```

missed manager to metadata
___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs` line 37 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1144#-O98y8bu-Z8ssxTCKlpv:-O98y8bu-Z8ssxTCKlpw:b-lqou7z) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bea22ce66d6698d0dc873ef1f1f20dc1c87c4d2/crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs#L37)):*
> ```XML
>     for height in 0..1000 {
>         let msg = create_consensus_msg(if distinct_messages { height } else { 0 }, is_vote);
>         let broadcasted_message_manager =
> ```

missed manager to metadata
___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs` line 70 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1144#-O98y9Vk3F8J9S7bq_ut:-O98y9Vk3F8J9S7bq_uu:b-lqou7z) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bea22ce66d6698d0dc873ef1f1f20dc1c87c4d2/crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs#L70)):*
> ```XML
>     for height in 0..1000 {
>         let msg = create_consensus_msg(if distinct_messages { height } else { 0 }, is_vote);
>         let broadcasted_message_manager =
> ```

missed manager to metadata
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1144#-O98yB1x4Sf0P13SHuLQ:-O98yB1x4Sf0P13SHuLR:b-lqou7z) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bea22ce66d6698d0dc873ef1f1f20dc1c87c4d2/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L47)):*
> ```XML
>         msg: StreamMessage<ConsensusMessage>,
>     ) {
>         let broadcasted_message_manager =
> ```

missed manager to metadata

**Review by AlonLStarkWare — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1144#-:-O992zZ0ABS1tz2yqP0I:bnfp4nl)* status: 9 of 16 files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1144)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 9 files at r6, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1144)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
