### PR TITLE
feat(mempool): reject tx of lower nonce in add_tx

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/172)

### CODE REVIEW

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
Nice!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/172#-:-O31EQZv8b25bXMoYtcZ:b-83sjoh)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/172#-O31DXem47uDLEYzeWYw:-O31DXem47uDLEYzeWYx:b-58q578) ([raw file](https://github.com/starkware-libs/sequencer/blob/982dcfbfce79c047316a73a7557301e8c332d649/crates/mempool/src/mempool.rs#L171)):*
> ```XML
>         }
> 
>         // Check nonce against the tx queue.
> ```

Since it's a trivial behavior, do you want to document our assumption?



_Code quote:_
```XML
// Check nonce against the tx queue.
```
___
*[`crates/mempool/src/mempool.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/172#-O31CytF1scFWF5r1_kl:-O31CytF1scFWF5r1_km:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/982dcfbfce79c047316a73a7557301e8c332d649/crates/mempool/src/mempool.rs#L172)):*
> ```XML
> 
>         // Check nonce against the tx queue.
>         if let Some(existing_nonce) = self.tx_queue.get_nonce(tx.sender_address) {
> ```





_Suggestion:_
```XML
queued_nonce
```
___
*[`crates/mempool/src/mempool.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/172#-O31D9Rz3kaQUrArPq0D:-O31D9Rz3kaQUrArPq0E:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/982dcfbfce79c047316a73a7557301e8c332d649/crates/mempool/src/mempool.rs#L178)):*
> ```XML
>                     nonce: tx.nonce,
>                 });
>             }
> ```





_Suggestion:_
```XML
        if self.tx_queue.get_nonce(tx.sender_address).is_some_and(|queued_nonce| queued_nonce >= tx.nonce)) {
                return Err(MempoolError::DuplicateNonce {
                    address: tx.sender_address,
                    nonce: tx.nonce,
                });
            }
```
___
*[`crates/mempool/src/mempool_test.rs` line 376 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/172#-O31EEtw7bYM7Wb-1BtO:-O31EEtw7bYM7Wb-1BtP:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/982dcfbfce79c047316a73a7557301e8c332d649/crates/mempool/src/mempool_test.rs#L376)):*
> ```XML
> 
> #[rstest]
> fn test_add_tx_with_tx_of_lower_nonce(mut mempool: Mempool) {
> ```





_Suggestion:_
```XML
test_add_tx_lower_than_queued_nonce
```
___
*[`crates/mempool/src/mempool_test.rs` line 387 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/172#-O31DzHY-WvAq6e9bxZA:-O31DzHY-WvAq6e9bxZB:b-atlgji) ([raw file](https://github.com/starkware-libs/sequencer/blob/982dcfbfce79c047316a73a7557301e8c332d649/crates/mempool/src/mempool_test.rs#L387)):*
> ```XML
> 
>     // Test and assert the original transaction remains.
>     add_tx(&mut mempool, &valid_input);
> ```

you can initialize the mempool with a single tx in the queue.



_Code quote:_
```XML
add_tx(&mut mempool, &valid_input);
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/172)* status: all files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/172#-O31O75p9n9NzfPK9V4-:-O31O75p9n9NzfPK9V40:b6cbuvg) ([raw file](https://github.com/starkware-libs/sequencer/blob/982dcfbfce79c047316a73a7557301e8c332d649/crates/mempool/src/mempool.rs#L158)):*
> ```XML
>                     address: tx.sender_address,
>                     nonce: tx.nonce,
>                 });
> ```

Can we define once instead of repeating?



_Code quote:_
```XML
                return Err(MempoolError::DuplicateNonce {
                    address: tx.sender_address,
                    nonce: tx.nonce,
                });
```
___
*[`crates/mempool/src/mempool_test.rs` line 381 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/172#-O31Od_mBZy6hd1Db0F7:-O31Od_mBZy6hd1Db0F8:b4xz0st) ([raw file](https://github.com/starkware-libs/sequencer/blob/982dcfbfce79c047316a73a7557301e8c332d649/crates/mempool/src/mempool_test.rs#L381)):*
> ```XML
>         add_tx_input!(tx_hash: 1, sender_address: "0x0", tx_nonce: 1_u8, account_nonce: 1_u8);
>     let lower_nonce_input =
>         add_tx_input!(tx_hash: 2, sender_address: "0x0", tx_nonce: 0_u8, account_nonce: 0_u8);
> ```

Do we also need this to be different?



_Code quote:_
```XML
account_nonce: 0_u8
```
___
*[`crates/mempool/src/mempool_test.rs` line 383 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/172#-O31OhWW149kGH8gFe6V:-O31OhWW149kGH8gFe6W:b-l74ot3) ([raw file](https://github.com/starkware-libs/sequencer/blob/982dcfbfce79c047316a73a7557301e8c332d649/crates/mempool/src/mempool_test.rs#L383)):*
> ```XML
>         add_tx_input!(tx_hash: 2, sender_address: "0x0", tx_nonce: 0_u8, account_nonce: 0_u8);
> 
>     let queue_txs = [&valid_input.tx].map(TransactionReference::new);
> ```

`map` on one element is more confusing than the alternative, IMO.



_Code quote:_
```XML
[&valid_input.tx].map(TransactionReference::new);
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/172)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/172#-O31D9Rz3kaQUrArPq0D:-O31e-Dk1Rl9eyCsiLS7:b-gw4hib) ([raw file](https://github.com/starkware-libs/sequencer/blob/982dcfbfce79c047316a73a7557301e8c332d649/crates/mempool/src/mempool.rs#L178)):*
> ```XML
>                     nonce: tx.nonce,
>                 });
>             }
> ```

I find it less readable. Don't you think?
___
*[`crates/mempool/src/mempool_test.rs` line 381 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/172#-O31Od_mBZy6hd1Db0F7:-O31_g8S4MVYO4p2EaCb:b-y3io10) ([raw file](https://github.com/starkware-libs/sequencer/blob/982dcfbfce79c047316a73a7557301e8c332d649/crates/mempool/src/mempool_test.rs#L381)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we also need this to be different?
</blockquote></details>

Yes, if we set `account_nonce` to 1, the `validate_input` method will fail the nonce check against the given account state before it even checks the nonce against the transaction queue.

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/172)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/172#-O31D9Rz3kaQUrArPq0D:-O31hXh97RkxXRDYEf44:bbf1z3o) ([raw file](https://github.com/starkware-libs/sequencer/blob/982dcfbfce79c047316a73a7557301e8c332d649/crates/mempool/src/mempool.rs#L178)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I find it less readable. Don't you think?
</blockquote></details>

This is duplicated from another flow, isn't it? If so, please share.
___
*[`crates/mempool/src/mempool.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/172#-O31hMAC0Ixuyj1dDUu-:-O31hMADBv_kHG0KRuRU:b6nmrm5) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa5898d040e130131047f1a26d1ac7ad6aeca14a/crates/mempool/src/mempool.rs#L151)):*
> ```XML
> 
>     fn validate_input(&self, input: &MempoolInput) -> MempoolResult<()> {
>         let MempoolInput { tx, account } = input;
> ```


Consider also unpacking the transaction (the subset of field you need from it).



_Code quote:_
```XML
tx
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/172)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/172#-O31DXem47uDLEYzeWYw:-O31k3Mc2dp27ic27p9l:b70cx1s) ([raw file](https://github.com/starkware-libs/sequencer/blob/982dcfbfce79c047316a73a7557301e8c332d649/crates/mempool/src/mempool.rs#L171)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Since it's a trivial behavior, do you want to document our assumption?
</blockquote></details>

I think we should add it for structural consistency of the method (each check has a header).
___
*[`crates/mempool/src/mempool.rs` line 150 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/172#-O31kKHh6zrdGXYiq646:-O31kKHh6zrdGXYiq647:b-qrguqu) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa5898d040e130131047f1a26d1ac7ad6aeca14a/crates/mempool/src/mempool.rs#L150)):*
> ```XML
>     }
> 
>     fn validate_input(&self, input: &MempoolInput) -> MempoolResult<()> {
> ```

Perhaps this struct should have its own `validate` method?



_Code quote:_
```XML
MempoolInput
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/172)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/172#-O31D9Rz3kaQUrArPq0D:-O31lXvR1yVuG4AcO0Uo:btmfk5q) ([raw file](https://github.com/starkware-libs/sequencer/blob/982dcfbfce79c047316a73a7557301e8c332d649/crates/mempool/src/mempool.rs#L178)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This is duplicated from another flow, isn't it? If so, please share.
</blockquote></details>

it's not exactly the same. in `commit_block` we check this: `queued_nonce != next_nonce`

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/172#-:-O32rgaG50X4dbERALNR:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/172#-O31DXem47uDLEYzeWYw:-O32bhjL-nMAZM7wQ1pN:b-niapv) ([raw file](https://github.com/starkware-libs/sequencer/blob/982dcfbfce79c047316a73a7557301e8c332d649/crates/mempool/src/mempool.rs#L171)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we should add it for structural consistency of the method (each check has a header).
</blockquote></details>

Sorry, I meant "it's not a trivial behavior".
NVM, it's up to you.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/172)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/172#-O31D9Rz3kaQUrArPq0D:-O36_-8L230xlLC95iZE:b-7kvbdm) ([raw file](https://github.com/starkware-libs/sequencer/blob/982dcfbfce79c047316a73a7557301e8c332d649/crates/mempool/src/mempool.rs#L178)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

it's not exactly the same. in `commit_block` we check this: `queued_nonce != next_nonce`
</blockquote></details>

We should at least have a writing convention.
___
*[`crates/mempool/src/mempool.rs` line 168 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/172#-O36Zrs4DV5ThcA0PdVZ:-O36Zrs4DV5ThcA0PdV_:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e38a84a0a97c271fce01f55fe2acc5c460286009/crates/mempool/src/mempool.rs#L168)):*
> ```XML
> 
>         // Check nonce against mempool state.
>         if let Some(AccountState { nonce: state_nonce }) = self.mempool_state.get(sender_address) {
> ```





_Suggestion:_
```XML
mempool_state_nonce
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/172)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool.rs` line 168 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/172#-O36Zrs4DV5ThcA0PdVZ:-O36e7cxAP-RSf7BCFBV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e38a84a0a97c271fce01f55fe2acc5c460286009/crates/mempool/src/mempool.rs#L168)):*
> ```XML
> 
>         // Check nonce against mempool state.
>         if let Some(AccountState { nonce: state_nonce }) = self.mempool_state.get(sender_address) {
> ```

Done.

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/172)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/172#-:-O3CdRt77vxEOW-hAtxF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
