### PR TITLE
chore(mempool_types): unify client implementations

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #2119
- #2115
- #2090 ⬅
- #2089
- #2088
- #2087
- #2086
- #2085

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by nadin-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2090)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_mempool_types/src/communication.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2090#-OBuHXLI-RC3B9mrOZvM:-OBuHXLI-RC3B9mrOZvN:b-wadyng) ([raw file](https://github.com/starkware-libs/sequencer/blob/6fff27999687c31e4de3edab0d8b3364b0ddc08e/crates/starknet_mempool_types/src/communication.rs#L73)):*
> ```XML
> 
> #[async_trait]
> impl<T> MempoolClient for T
> ```

Please replace T with a more descriptive name.



_Code quote:_
```XML
T
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2090)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/starknet_mempool_types/src/communication.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2090#-OBuHXLI-RC3B9mrOZvM:-OBuT3LSAruyAzIkgPBM:b-d3xf9y) ([raw file](https://github.com/starkware-libs/sequencer/blob/34608328474d81e9316b26c232951f01df0df102/crates/starknet_mempool_types/src/communication.rs#L73)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Please replace T with a more descriptive name.
</blockquote></details>

Single pr at the end

**Review by nadin-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2090)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2090)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#2119](https://github.com/starkware-libs/sequencer/pull/2119)

**Pull request closed without merging**
