### PR TITLE
feat(consensus): filter votes

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/603)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/603)* status: all files reviewed, 3 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/603#-O5EBojlCzn-9XLJbZ80:-O5EBojlCzn-9XLJbZ81:b-qr21p1) ([raw file](https://github.com/starkware-libs/sequencer/blob/11e4ae32e259e8365c7c7857366368d2f0628196/crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs#L121)):*
> ```XML
>             }
>             ConsensusMessage::Vote(ref mut vote) => {
>                 vote.voter = random_contract_address();
> ```

Your implementation creates a new `thread_rng` each time, which makes the tests unrepeatable. We should create an rng based on the msg hash calculated.

We may need to rearrange how the functions are structured to enable this.



_Code quote:_
```XML
                vote.voter = random_contract_address();
```
___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/603#-O5ECOiH-DX6qOkdYsMH:-O5ECOiI0grre4NTvN6k:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/11e4ae32e259e8365c7c7857366368d2f0628196/crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs#L161)):*
> ```XML
>     let felt = arbitrary_felt(&mut rand::thread_rng());
>     ContractAddress(PatriciaKey::try_from(felt).expect("Failed to convert Felt to PatriciaKey"))
> }
> ```





_Suggestion:_
```XML
pub fn random_contract_address(seed) -> ContractAddress {
    let felt = arbitrary_felt(&mut rand::StdRng(seed));
    ContractAddress(PatriciaKey::try_from(felt).expect("Failed to convert Felt to PatriciaKey"))
}
```
___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/603#-O5ECkeB3XMnbW1jsfzS:-O5ECkeC1x-slTUrXscM:b-f3z73o) ([raw file](https://github.com/starkware-libs/sequencer/blob/11e4ae32e259e8365c7c7857366368d2f0628196/crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs#L35)):*
> ```XML
>             }
>             ConsensusMessage::Proposal(proposal.clone())
>         };
> ```

Let's move this into a helper fn



_Code quote:_
```XML
        let msg = if is_vote {
            let mut vote = papyrus_protobuf::consensus::Vote::default();
            if distinct_messages {
                vote.height = height;
            }
            ConsensusMessage::Vote(vote.clone())
        } else {
            let mut proposal = papyrus_protobuf::consensus::Proposal::default();
            if distinct_messages {
                proposal.height = height;
            }
            ConsensusMessage::Proposal(proposal.clone())
        };
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/603)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/603#-O5EBojlCzn-9XLJbZ80:-O5HhTy32yCQFmIkCOdh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/11e4ae32e259e8365c7c7857366368d2f0628196/crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs#L121)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Your implementation creates a new `thread_rng` each time, which makes the tests unrepeatable. We should create an rng based on the msg hash calculated.

We may need to rearrange how the functions are structured to enable this.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/603#-O5ECOiH-DX6qOkdYsMH:-O5HhV1FBn0oNuH9dqO_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/11e4ae32e259e8365c7c7857366368d2f0628196/crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs#L161)):*
> ```XML
>     let felt = arbitrary_felt(&mut rand::thread_rng());
>     ContractAddress(PatriciaKey::try_from(felt).expect("Failed to convert Felt to PatriciaKey"))
> }
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/603#-O5ECkeB3XMnbW1jsfzS:-O5Hj_LdCoKQTR2a5D-4:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/11e4ae32e259e8365c7c7857366368d2f0628196/crates/sequencing/papyrus_consensus/src/simulation_network_receiver_test.rs#L35)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let's move this into a helper fn
</blockquote></details>

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/603)* status: all files reviewed, 3 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/603#-O5EBojlCzn-9XLJbZ80:-O5SzKgb-r9BKZH71bUi:bfn5tuo) ([raw file](https://github.com/starkware-libs/sequencer/blob/11e4ae32e259e8365c7c7857366368d2f0628196/crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs#L121)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We may have overthought this. Why not just use `msg_hash` as the new ContractAddress? It is random enough for our needs and repeatable across runs.
___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs` line 87 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/603#-O5SyX3dCkonsX660NtX:-O5SyX3e9OZZuns_zvtu:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e4cae3748c7742e5682523d8b11d13f15384dea/crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs#L87)):*
> ```XML
>             self.invalidate_msg(&mut msg, msg_hash);
>         }
>         Some(msg)
> ```





_Suggestion:_
```XML
        Some(self.maybe_invalidate_msg(&mut msg, msg_hash));
```
___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs` line 116 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/603#-O5SyivZAqhN_odB_s_z:-O5SyivZAqhN_odB_sa-:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e4cae3748c7742e5682523d8b11d13f15384dea/crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs#L116)):*
> ```XML
>     }
> 
>     fn invalidate_msg(&mut self, msg: &mut ConsensusMessage, msg_hash: u64) {
> ```





_Suggestion:_
```XML
     fn maybe_invalidate_msg(&mut self, msg: ConsensusMessage, msg_hash: u64) -> ConsensusMessage {
        if (msg_hash as f64) / (u64::MAX as f64) > self.invalid_probability {
            return msg;
        }
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/603)* status: all files reviewed, 3 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/603#-O5EBojlCzn-9XLJbZ80:-O5TEWsX-QQ_RK2SdyUZ:b23olzf) ([raw file](https://github.com/starkware-libs/sequencer/blob/11e4ae32e259e8365c7c7857366368d2f0628196/crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs#L121)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

We may have overthought this. Why not just use `msg_hash` as the new ContractAddress? It is random enough for our needs and repeatable across runs.
</blockquote></details>

Oh! it's ok, learned something new in Rust. :)
done
___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs` line 87 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/603#-O5SyX3dCkonsX660NtX:-O5TBkmQ7WjkhOfKSDvG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e4cae3748c7742e5682523d8b11d13f15384dea/crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs#L87)):*
> ```XML
>             self.invalidate_msg(&mut msg, msg_hash);
>         }
>         Some(msg)
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs` line 116 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/603#-O5SyivZAqhN_odB_s_z:-O5TBl4S3O50h2H6oyJk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2e4cae3748c7742e5682523d8b11d13f15384dea/crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs#L116)):*
> ```XML
>     }
> 
>     fn invalidate_msg(&mut self, msg: &mut ConsensusMessage, msg_hash: u64) {
> ```

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 3 of 7 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/603)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/603)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
