### PR TITLE
chore(batcher): remove block metadata member from block builder factory

### PR DESCRIPTION
**Pull request by ArniStarkware**
Refactor towards getting block info from consensus.

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#2231** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2231?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2230** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2230?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2230?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2230)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5 and @dafnamatsry)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2230)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Comment by ArniStarkware** [comment]
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Is this PR still relevant? Instead of removing this here and then adding the block info (which contains these fields), you can just replace it in the same PR.
</blockquote></details>

This Pr is indeed no longer relevant.

**Pull request closed without merging**
