### PR TITLE
chore(blockifier_reexecution): add test cases

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1796?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1796** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1796?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1765** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1765?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1759** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1759?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1758** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1758?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1712** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1712?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1796)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1796#-OAwUmo7-O-2HWITTnvG:-OAwUmo7-O-2HWITTnvH:b-w1xylb) (no related file):*
where is the usage of these changes? cannot review unused code, need context

___

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1796)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1796#-OAwUmo7-O-2HWITTnvG:-OAwgjLT9XtW3zceaWy_:bx3hjq4) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where is the usage of these changes? cannot review unused code, need context
</blockquote></details>

This is an example of all the cases that interest us. I ran the RPC test command with them,
 and we might use them as examples in the CI.

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1796)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1796#-OAwUmo7-O-2HWITTnvG:-OAwqQwE3PeNIcxgw51r:b-kqlxb3) (no related file):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

This is an example of all the cases that interest us. I ran the RPC test command with them,
 and we might use them as examples in the CI.
</blockquote></details>

maybe add a `block_numbers_for_reexecution` function that
1. reads the JSON, one per version of starknet after and including 0.13.0
2. appends the specific block numbers with extra examples
?
that way you'll only need `#[allow(unused)]` once, right?

___

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1796)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1796#-OAwUmo7-O-2HWITTnvG:-OB-RPuE1UWSoKoZNckI:b-sr96ga) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe add a `block_numbers_for_reexecution` function that
1. reads the JSON, one per version of starknet after and including 0.13.0
2. appends the specific block numbers with extra examples
?
that way you'll only need `#[allow(unused)]` once, right?
</blockquote></details>

Do we want to add all possible examples for blocks with different tx types? ( total 12 blocks including the blocks per version )

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1796)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1796#-OAwUmo7-O-2HWITTnvG:-OB-rO0hAcFuho0PoiEC:b2nign6) (no related file):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Do we want to add all possible examples for blocks with different tx types? ( total 12 blocks including the blocks per version )
</blockquote></details>

yes

___

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1796)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1796)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1796#-OAwUmo7-O-2HWITTnvG:-OB0kKzA8FwM2aPzdaD_:b-896fix) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes
</blockquote></details>

Done.

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1796)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1796#-OAwUmo7-O-2HWITTnvG:-OB0xUZ56yDCC_dBLsrq:b-q24fr) (no related file):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

can you delete the constants with the special block numbers? if not, why are they still needed?

___

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1796)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1796#-OAwUmo7-O-2HWITTnvG:-OB0yAvc44GUMMYdB9Be:bexgyd6) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you delete the constants with the special block numbers? if not, why are they still needed?
</blockquote></details>

We use them in the test file, I can fetch the JSON and extract them instead of using constants

___

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1796#-:-OB0zXBD08Oopan156mb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1796#-OAwUmo7-O-2HWITTnvG:-OB0zQSL0R-xBckGspFI:beh0hk7) (no related file):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

We use them in the test file, I can fetch the JSON and extract them instead of using constants
</blockquote></details>

can be in a separate PR... maybe we want something smarter, that can also be used to parametrize Aner's offline test

___

**Comment by AvivYossef-starkware** [comment]
### Merge activity

* **Nov 6, 10:02 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1796).

**Pull request merged**
