### PR TITLE
feat(consensus): add advance_to_round

### PR DESCRIPTION
**Pull request by asmaastarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/70)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/70)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/70#-O2e2VB_-0YqdkxoIf1I:-O2e2VB_-0YqdkxoIf1J:b-2h6dzi) ([raw file](https://github.com/starkware-libs/sequencer/blob/e80cd8e8e629e008153f461a34f5c0a9241450e4/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L125)):*
> ```XML
>         self.proposals.insert(ROUND_ZERO, block);
>         let leader_fn = |_round: Round| -> ValidatorId {
>             context.proposer(&self.validators.clone(), self.height)
> ```

Are you sure we need to clone this? I thought we'd be able to pass this by reference. If we don't need to, change in all locations.



_Code quote:_
```XML
self.validators.clone()
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/70#-O2e2wTi2RdcFMDHIkHF:-O2e2wTj340GLkLgBCI1:b-frgtbt) ([raw file](https://github.com/starkware-libs/sequencer/blob/e80cd8e8e629e008153f461a34f5c0a9241450e4/crates/sequencing/papyrus_consensus/src/state_machine.rs#L106)):*
> ```XML
>         event: StateMachineEvent,
>         leader_fn: &impl Fn(Round) -> ValidatorId,
>     ) -> VecDeque<StateMachineEvent> {
> ```

Shahak suggested that if we use the same `impl` all over the place it's better to use generics (here and below)



_Suggestion:_
```XML
    pub fn handle_event<LeaderFn>(
        &mut self,
        event: StateMachineEvent,
        leader_fn: &LeaderFn,
    ) -> VecDeque<StateMachineEvent> 
    where:
        LeaderFn: Fn(Round) -> ValidatorId,
    {
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 266 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/70#-O2e3nEVBOfpm1i4opo5:-O2e3nEVBOfpm1i4opo6:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e80cd8e8e629e008153f461a34f5c0a9241450e4/crates/sequencing/papyrus_consensus/src/state_machine.rs#L266)):*
> ```XML
>         // Check for an existing quorum in case messages arrived out of order.
>         match self.step {
>             Step::Propose => unreachable!(),
> ```





_Suggestion:_
```XML
unreachable!("Advancing to Propose is done by advancing rounds")
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 292 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/70#-O2e6H-V82CQuVpImd0D:-O2e6H-V82CQuVpImd0E:b-tm1yap) ([raw file](https://github.com/starkware-libs/sequencer/blob/e80cd8e8e629e008153f461a34f5c0a9241450e4/crates/sequencing/papyrus_consensus/src/state_machine.rs#L292)):*
> ```XML
>         }
>         self.send_precommit(*block_hash, round, leader_fn)
>     }
> ```

We need to change our logic. First of all we only need to check the value if there is a quorum. Secondly, if the quorum is None then we should always send Precommit None. The question is if there is a quorum for Some.
1. If we have no proposal: do nothing
2. If we have an invalid proposal: panic
3. If we have a valid proposal which does not match the quorum: panic
4. If Proposal.hash == Quorum.hash: send Precommit in favor

We want similar logic for the precommits with 2 changes:
1. If the quorum is None advance round
2. If Proposal.hash == Quorum.hash: Decision



_Suggestion:_
```XML
        let Some((block_hash, count)) = leading_vote(&self.prevotes, round) else {
            return VecDeque::new();
        };
        if *count < self.quorum {
            return VecDeque::new();
        }
        let Some(proposed_value) = self.proposals.get(&round) else {
            return VecDeque::new();
        };
        if proposed_value != block_hash {
            error!("Proposal does not match quorum.");
            return VecDeque::new();
        }


        self.send_precommit(*block_hash, round, leader_fn)
    }
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/70)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/70#-O2e2VB_-0YqdkxoIf1I:-O2e7wQBCT6x6zNmQOHc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e80cd8e8e629e008153f461a34f5c0a9241450e4/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L125)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Are you sure we need to clone this? I thought we'd be able to pass this by reference. If we don't need to, change in all locations.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/70#-O2e2wTi2RdcFMDHIkHF:-O2eA9jq2sesjAcKW1dM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e80cd8e8e629e008153f461a34f5c0a9241450e4/crates/sequencing/papyrus_consensus/src/state_machine.rs#L106)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Shahak suggested that if we use the same `impl` all over the place it's better to use generics (here and below)
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 266 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/70#-O2e3nEVBOfpm1i4opo5:-O2e8Wn52r-yqbG_dxR4:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e80cd8e8e629e008153f461a34f5c0a9241450e4/crates/sequencing/papyrus_consensus/src/state_machine.rs#L266)):*
> ```XML
>         // Check for an existing quorum in case messages arrived out of order.
>         match self.step {
>             Step::Propose => unreachable!(),
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 292 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/70#-O2e6H-V82CQuVpImd0D:-O2eFnkK5VnHtNmUY28F:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e80cd8e8e629e008153f461a34f5c0a9241450e4/crates/sequencing/papyrus_consensus/src/state_machine.rs#L292)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

We need to change our logic. First of all we only need to check the value if there is a quorum. Secondly, if the quorum is None then we should always send Precommit None. The question is if there is a quorum for Some.
1. If we have no proposal: do nothing
2. If we have an invalid proposal: panic
3. If we have a valid proposal which does not match the quorum: panic
4. If Proposal.hash == Quorum.hash: send Precommit in favor

We want similar logic for the precommits with 2 changes:
1. If the quorum is None advance round
2. If Proposal.hash == Quorum.hash: Decision
</blockquote></details>

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r7, 1 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/70)* status: 3 of 8 files reviewed, 9 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 346 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/70#-O2sXeAR8A4BKPCdAWCa:-O2sXeAS48RAWrJ-or39:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f9e8b2dea2f8ac6ac1ef1fe4775150befa6de56/crates/sequencing/papyrus_consensus/src/state_machine.rs#L346)):*
> ```XML
>             VecDeque::from([StateMachineEvent::Decision(*block_hash, round)])
>         } else {
>             VecDeque::new()
> ```





_Suggestion:_
```XML
            // NIL quorum reached on a different round.
            VecDeque::new()
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 303 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/70#-O2sZApJ6xu3Oj2AEGd2:-O2sZApJ6xu3Oj2AEGd3:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/97127d7d42f11fdeb846ef3e094901c908bf5039/crates/sequencing/papyrus_consensus/src/state_machine.rs#L303)):*
> ```XML
>         let Some((block_hash, count)) = leading_vote(&self.prevotes, round) else {
>             return VecDeque::new();
>         };
> ```





_Suggestion:_
```XML
    fn check_prevote_quorum<LeaderFn>(
        &mut self,
        round: u32,
        leader_fn: &LeaderFn,
    ) -> VecDeque<StateMachineEvent>
    where
        LeaderFn: Fn(Round) -> ValidatorId,
    {
        assert_eq(round, self.round, "check_prevote_quorum is only called for the current round");
        let Some((block_hash, count)) = leading_vote(&self.prevotes, round) else {
            return VecDeque::new();
        };
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine.rs` line 315 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/70#-O2sZwCJCA4UWhz8Nx-f:-O2sZwCJCA4UWhz8Nx-g:b30fs9z) ([raw file](https://github.com/starkware-libs/sequencer/blob/97127d7d42f11fdeb846ef3e094901c908bf5039/crates/sequencing/papyrus_consensus/src/state_machine.rs#L315)):*
> ```XML
>         if proposed_value != block_hash {
>             panic!("Proposal does not match quorum.");
>         }
> ```

Also add this in the precommit check



_Suggestion:_
```XML
        if proposed_value != block_hash {
            // TODO(matan): This can be caused by a malicious leader double proposing.
            panic!("Proposal does not match quorum.");
        }
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 155 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/70#-O2scPRX9V_D2J9iNsOg:-O2scPRX9V_D2J9iNsOh:b-kehl6n) ([raw file](https://github.com/starkware-libs/sequencer/blob/97127d7d42f11fdeb846ef3e094901c908bf5039/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L155)):*
> ```XML
>     assert_eq!(events.pop_front().unwrap(), StateMachineEvent::Precommit(None, ROUND));
>     assert!(events.is_empty(), "{:?}", events);
> }
> ```

Please combine into a single test and use `test_case` to have both variants as they are almost identical



_Code quote:_
```XML
#[test]
fn buffer_events_during_get_proposal() {
    let mut state_machine = StateMachine::new(*PROPOSER_ID, 4);
    let leader_fn = |_: Round| *PROPOSER_ID;
    let mut events = state_machine.start(&leader_fn);
    assert_eq!(events.pop_front().unwrap(), StateMachineEvent::GetProposal(None, 0));
    assert!(events.is_empty(), "{:?}", events);

    events.append(
        &mut state_machine.handle_event(StateMachineEvent::Prevote(BLOCK_HASH, ROUND), &leader_fn),
    );
    events.append(
        &mut state_machine.handle_event(StateMachineEvent::Prevote(BLOCK_HASH, ROUND), &leader_fn),
    );
    events.append(
        &mut state_machine.handle_event(StateMachineEvent::Prevote(BLOCK_HASH, ROUND), &leader_fn),
    );
    assert!(events.is_empty(), "{:?}", events);

    // Node finishes building the proposal.
    events =
        state_machine.handle_event(StateMachineEvent::GetProposal(BLOCK_HASH, ROUND), &leader_fn);
    assert_eq!(events.pop_front().unwrap(), StateMachineEvent::Proposal(BLOCK_HASH, ROUND));
    assert_eq!(events.pop_front().unwrap(), StateMachineEvent::Prevote(BLOCK_HASH, ROUND));
    assert_eq!(events.pop_front().unwrap(), StateMachineEvent::Precommit(BLOCK_HASH, ROUND));
    assert!(events.is_empty(), "{:?}", events);
}

#[test]
fn buffer_nil_votes_during_get_proposal() {
    let mut state_machine = StateMachine::new(*PROPOSER_ID, 4);
    let leader_fn = |_: Round| *PROPOSER_ID;
    let mut events = state_machine.start(&leader_fn);
    assert_eq!(events.pop_front().unwrap(), StateMachineEvent::GetProposal(None, 0));
    assert!(events.is_empty(), "{:?}", events);

    events.append(
        &mut state_machine.handle_event(StateMachineEvent::Prevote(None, ROUND), &leader_fn),
    );
    events.append(
        &mut state_machine.handle_event(StateMachineEvent::Prevote(None, ROUND), &leader_fn),
    );
    events.append(
        &mut state_machine.handle_event(StateMachineEvent::Prevote(None, ROUND), &leader_fn),
    );
    assert!(events.is_empty(), "{:?}", events);

    // Node finishes building the proposal.
    events =
        state_machine.handle_event(StateMachineEvent::GetProposal(BLOCK_HASH, ROUND), &leader_fn);
    assert_eq!(events.pop_front().unwrap(), StateMachineEvent::Proposal(BLOCK_HASH, ROUND));
    assert_eq!(events.pop_front().unwrap(), StateMachineEvent::Prevote(BLOCK_HASH, ROUND));
    assert_eq!(events.pop_front().unwrap(), StateMachineEvent::Precommit(None, ROUND));
    assert!(events.is_empty(), "{:?}", events);
}
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 158 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/70#-O2sc_8h28awXtcu8lPq:-O2sc_8h28awXtcu8lPr:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/97127d7d42f11fdeb846ef3e094901c908bf5039/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L158)):*
> ```XML
> 
> #[test]
> fn no_precommit_without_proposal_even_with_prevote_quorum() {
> ```





_Suggestion:_
```XML
fn only_send_precommit_with_prevote_quorum_and_proposal() {
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 181 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/70#-O2sdrWO5BRJ8lQysM5C:-O2sdrWO5BRJ8lQysM5D:b-el78gg) ([raw file](https://github.com/starkware-libs/sequencer/blob/97127d7d42f11fdeb846ef3e094901c908bf5039/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L181)):*
> ```XML
>             .handle_event(StateMachineEvent::Precommit(BLOCK_HASH, ROUND), &leader_fn),
>     );
>     assert!(events.is_empty(), "{:?}", events);
> ```

I don't see the value in sending this precommit .
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 191 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/70#-O2se4Pe3tP3GZTtBdUA:-O2se4Pe3tP3GZTtBdUB:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/97127d7d42f11fdeb846ef3e094901c908bf5039/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L191)):*
> ```XML
> 
> #[test]
> fn no_decision_without_proposal_even_with_precommit_quorum() {
> ```





_Suggestion:_
```XML
only_decide_with_prcommit_quorum_and_proposal(
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 233 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/70#-O2se_cO85sPi4MJYGvO:-O2se_cPCONjaA0SMcNu:b-trtstx) ([raw file](https://github.com/starkware-libs/sequencer/blob/97127d7d42f11fdeb846ef3e094901c908bf5039/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L233)):*
> ```XML
>     );
>     assert!(events.is_empty(), "{:?}", events);
> }
> ```

Where are the tests for multiple rounds? The main point of this PR is `advance_to_round`



_Code quote:_
```XML
    assert!(events.is_empty(), "{:?}", events);
}
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/70)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 102 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/70#-O2t8QO09jP31XnUIjXV:-O2t8QO16Ad7QydTz4_d:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/571fe5b7b5f375390435fc49b1f9b7dda3b46b18/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L102)):*
> ```XML
> 
> #[test_case(BLOCK_HASH ; "with valid block hash votes")]
> #[test_case(None ; "with nil votes")]
> ```





_Suggestion:_
```XML
#[test_case(BLOCK_HASH ; "valid_proposal")]
#[test_case(None ; "invalid_proposal")]
```
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 236 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/70#-O2tAlXg0W1CoU6v5umZ:-O2tAlXg0W1CoU6v5um_:b7hn22a) ([raw file](https://github.com/starkware-libs/sequencer/blob/571fe5b7b5f375390435fc49b1f9b7dda3b46b18/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L236)):*
> ```XML
>         events.pop_front().unwrap(),
>         StateMachineEvent::Decision(BLOCK_HASH.unwrap(), ROUND + 1)
>     );
> ```

I don't mind the first check since it's a negative one "we have not progressed rounds". For the second check I would like to see this in the public interface though.



_Suggestion:_
```XML
    assert_eq!(state_machine.round, 0);
    // Send valid Proposal for round 1 and see that no Prevote is sent.
    events.append(
        &mut state_machine.handle_event(StateMachineEvent::Precommit(None, ROUND), &leader_fn),
    );
    // Check that a Prevote for round 1 is now sent since we were able to progress after the NIL quorum.
```

**Review by matan-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/70)* status: 3 of 8 files reviewed, all discussions resolved

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/70)* status: 3 of 8 files reviewed, all discussions resolved

**Pull request merged**
