### PR TITLE
fix: take care of edge cases in consensus message conversion

### PR DESCRIPTION
**Pull request by guy-starkware**
This adds a non-zero value to the gas price in the Consensus Proposal message, so it will be deserialized to the exact same value it was before serialization.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1300)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1300)* status: all files reviewed, 2 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1300#-O8qVQm40IYNmPaBmdC9:-O8qVQm40IYNmPaBmdCA:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/557d06682bdb299c967eb93c259d7b59a74d988a/crates/papyrus_protobuf/src/converters/consensus_test.rs#L35)):*
> ```XML
> // So I will intentionally make them non-zero, but the real solution is to make the randomly
> // generated structs contain random values instead of zero.
> // TODO(guyn): add random values to the structs generated by get_test_instance
> ```





_Suggestion:_
```XML
// If all the fields of `AllResources` are 0 upon serialization, then the deserialized value will interpreted as the `L1Gas` variant.
// TODO(guyn): add random values to the structs generated by get_test_instance
```
___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1300#-O8qWqEd44KxuYBuUEyz:-O8qWqEd44KxuYBuUEz-:bz2ub07) ([raw file](https://github.com/starkware-libs/sequencer/blob/557d06682bdb299c967eb93c259d7b59a74d988a/crates/papyrus_protobuf/src/converters/consensus_test.rs#L119)):*
> ```XML
>         }
>         _ => {}
>     }
> ```

I'm surprised clippy didn't suggest this. I thought it usually does when only matching a single variant.

do the same below with Proposal.



_Suggestion:_
```XML
    if let StreamMessageBody::Content(ConsensusMessage::Proposal(proposal)) =
        &mut stream_message.message
    {
        add_gas_values_to_transaction(&mut proposal.transactions);
    }
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1300)* status: all files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1300#-O8qWqEd44KxuYBuUEyz:-O8qYiTlCgQHdC330Gqf:b-y0b0fh) ([raw file](https://github.com/starkware-libs/sequencer/blob/557d06682bdb299c967eb93c259d7b59a74d988a/crates/papyrus_protobuf/src/converters/consensus_test.rs#L119)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I'm surprised clippy didn't suggest this. I thought it usually does when only matching a single variant.

do the same below with Proposal.
</blockquote></details>

Right! I forgot about this...

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1300)* status: all files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1300#-O8qVQm40IYNmPaBmdC9:-O8qZes49YWB4fMY8fp0:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/557d06682bdb299c967eb93c259d7b59a74d988a/crates/papyrus_protobuf/src/converters/consensus_test.rs#L35)):*
> ```XML
> // So I will intentionally make them non-zero, but the real solution is to make the randomly
> // generated structs contain random values instead of zero.
> // TODO(guyn): add random values to the structs generated by get_test_instance
> ```

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1300)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1300)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Pull request merged**
