### PR TITLE
chore(blockifier): remove unnecessary message utils

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1011)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1011)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/receipt_test.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1011#-O7dfk2W0gQPj38D0hR1:-O7dfk2XDJ7gHdMTazg0:b48w6no) ([raw file](https://github.com/starkware-libs/sequencer/blob/3af2f46bc74069abe181a9f8fc2bc1e775980c58/crates/blockifier/src/fee/receipt_test.rs#L169)):*
> ```XML
>     for i in 0..4 {
>         let payload_vec = vec![Felt::ZERO; i];
>         l2_to_l1_payload_lengths.push(payload_vec.len());
> ```

this doesn't look equivalent to the deleted `get_l2_to_l1_payload_lengths()`



_Code quote:_
```XML
payload_vec.len()
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1011)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/fee/receipt_test.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1011#-O7dfk2W0gQPj38D0hR1:-O7dmPWL56B1PVa8Am66:ba7euyi) ([raw file](https://github.com/starkware-libs/sequencer/blob/3af2f46bc74069abe181a9f8fc2bc1e775980c58/crates/blockifier/src/fee/receipt_test.rs#L169)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this doesn't look equivalent to the deleted `get_l2_to_l1_payload_lengths()`
</blockquote></details>

It's enough for this test to create the expected result.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1011)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/receipt_test.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1011#-O7dfk2W0gQPj38D0hR1:-O7hKX3Q6kSvkKm9W7mJ:b-3rbfry) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a1d0cb28433e6a4ac0d8fbbf627a9f0d431d892/crates/blockifier/src/fee/receipt_test.rs#L169)):*
> Note that each call info contains a single message

this will stay true in the future of this test?
why not test the "correct" computation? will allow changing this (already long) test easier

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1011#-:-O7hQhRkDjt98HtdcolA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1011)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
