### PR TITLE
feat(blockifier, starknet_api): add explcit typing and arithmetic to gas amount/price, and fee

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1173)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1173?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1174** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1174?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1173** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1173?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1172** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1172?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1173)* status: 0 of 42 files reviewed, all discussions resolved

___
*[`crates/blockifier/src/utils.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1173#-O8VozdN93v1d5MrTMcq:-O8VozdN93v1d5MrTMcr:b-lo2avu) ([raw file](https://github.com/starkware-libs/sequencer/blob/160c32ba1479e53183a9bbc8fa7cdbdb57b50798/crates/blockifier/src/utils.rs#L71)):*
> ```XML
>     }
>     result
> }
> ```

was only used for nonzero- gas price; implementation moved



_Code quote:_
```XML
/// Returns the ceiling of the division of two u128 numbers.
pub fn u128_div_ceil(a: u128, b: NonZeroU128) -> u128 {
    let mut result = a / b;
    if result * b.get() < a {
        result += 1;
    }
    result
}
```
___
*[`crates/blockifier/src/utils_test.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1173#-O8Vp40o-jfT7W9YXl8w:-O8Vp40o-jfT7W9YXl8x:bvfnkoc) ([raw file](https://github.com/starkware-libs/sequencer/blob/160c32ba1479e53183a9bbc8fa7cdbdb57b50798/crates/blockifier/src/utils_test.rs#L77)):*
> ```XML
>     assert_eq!(9, u128_div_ceil(27, NonZeroU128::new(3).unwrap()));
>     assert_eq!(10, u128_div_ceil(28, NonZeroU128::new(3).unwrap()));
> }
> ```

this test was moved (see above)



_Code quote:_
```XML
#[test]
fn test_u128_div_ceil() {
    assert_eq!(1, u128_div_ceil(1, NonZeroU128::new(1).unwrap()));
    assert_eq!(0, u128_div_ceil(0, NonZeroU128::new(1).unwrap()));
    assert_eq!(1, u128_div_ceil(1, NonZeroU128::new(2).unwrap()));
    assert_eq!(9, u128_div_ceil(27, NonZeroU128::new(3).unwrap()));
    assert_eq!(10, u128_div_ceil(28, NonZeroU128::new(3).unwrap()));
}
```
___
*[`crates/starknet_api/src/transaction.rs` line 752 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1173#-O8VpHXWClQ-NX4D2GjR:-O8VpHXWClQ-NX4D2GjS:b35csfq) ([raw file](https://github.com/starkware-libs/sequencer/blob/d32a194970cef0f43c64feb82e735f47e74a28af/crates/starknet_api/src/transaction.rs#L752)):*
> ```XML
>         }
>         result
>     }
> ```

logic was moved (see above)



_Code quote:_
```XML
    pub fn div_ceil(self, rhs: NonzeroGasPrice) -> GasAmount {
        let mut result: GasAmount = self / rhs;
        if result.0 * rhs.get().0 < self.0 {
            result = GasAmount(result.0 + 1);
        }
        result
    }
```
___
*[`crates/starknet_api/src/transaction_test.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1173#-O8VpE7o2pGY1RCgdl7q:-O8VpE7o2pGY1RCgdl7r:bvfnkoc) ([raw file](https://github.com/starkware-libs/sequencer/blob/d32a194970cef0f43c64feb82e735f47e74a28af/crates/starknet_api/src/transaction_test.rs#L12)):*
> ```XML
>     assert_eq!(GasAmount(9), Fee(27).div_ceil(NonzeroGasPrice::new(GasPrice(3)).unwrap()));
>     assert_eq!(GasAmount(10), Fee(28).div_ceil(NonzeroGasPrice::new(GasPrice(3)).unwrap()));
> }
> ```

this test was moved (see above)



_Code quote:_
```XML
#[test]
fn test_fee_div_ceil() {
    assert_eq!(GasAmount(1), Fee(1).div_ceil(NonzeroGasPrice::new(GasPrice(1)).unwrap()));
    assert_eq!(GasAmount(0), Fee(0).div_ceil(NonzeroGasPrice::new(GasPrice(1)).unwrap()));
    assert_eq!(GasAmount(1), Fee(1).div_ceil(NonzeroGasPrice::new(GasPrice(2)).unwrap()));
    assert_eq!(GasAmount(9), Fee(27).div_ceil(NonzeroGasPrice::new(GasPrice(3)).unwrap()));
    assert_eq!(GasAmount(10), Fee(28).div_ceil(NonzeroGasPrice::new(GasPrice(3)).unwrap()));
}
```

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 2 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1173)* status: 2 of 42 files reviewed, all discussions resolved

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 42 files at r1, 2 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1173)* status: 10 of 42 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 205 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1173#-O8XTzHh56pfjpYQ07Cp:-O8XTzHh56pfjpYQ07Cq:b-87woqa) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f1a5fb338b7a27478cdc15d9e3a5b877fd1f57b/crates/blockifier/src/execution/entry_point.rs#L205)):*
> ```XML
>             }
>             TransactionInfo::Current(context) => {
>                 GasAmount(u128::from(context.l1_resource_bounds().max_amount))
> ```

Throughout this PR as well



_Suggestion:_
```XML
  context.l1_resource_bounds().max_amount.into()
```

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 4 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1173)* status: 14 of 42 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 42 files at r1, 1 of 13 files at r2, 3 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1173)* status: 21 of 42 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/errors.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1173#-O8XXrbe9lc69Db72BVC:-O8XXrbe9lc69Db72BVD:b22d3jm) ([raw file](https://github.com/starkware-libs/sequencer/blob/455529c6f236b2861397d1b9d7c8b939394c8fb9/crates/blockifier/src/transaction/errors.rs#L60)):*
> ```XML
>     #[error(
>         "Max {resource} price ({max_gas_price:?}) is lower than the actual gas price: \
>          {actual_gas_price:?}."
> ```

Remove `:?`



_Code quote:_
```XML
        "Max {resource} price ({max_gas_price:?}) is lower than the actual gas price: \
         {actual_gas_price:?}."
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1173)* status: 22 of 42 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/starknet_api/src/block.rs` line 242 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1173#-O8X_38J3-gqtQnEwmsP:-O8X_38J3-gqtQnEwmsQ:b6jd7nr) ([raw file](https://github.com/starkware-libs/sequencer/blob/455529c6f236b2861397d1b9d7c8b939394c8fb9/crates/starknet_api/src/block.rs#L242)):*
> ```XML
> 
> #[derive(Copy, Clone, Debug)]
> pub struct NonzeroGasPrice(GasPrice);
> ```

Please document why this struct is needed (since we also have GasPrice in this file)
Also, I guess that the nonzero variant is not part of the block header, so maybe it's not the right file for it (this part is not blocking)



_Code quote:_
```XML
pub struct NonzeroGasPrice(GasPrice);
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1173)* status: 24 of 42 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/starknet_api/src/transaction.rs` line 812 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1173#-O8XcYFx6KmpuITyKQPv:-O8XcYFx6KmpuITyKQPw:b-r87d1b) ([raw file](https://github.com/starkware-libs/sequencer/blob/455529c6f236b2861397d1b9d7c8b939394c8fb9/crates/starknet_api/src/transaction.rs#L812)):*
> ```XML
>     pub fn checked_mul(self, rhs: GasPrice) -> Option<Fee> {
>         rhs.checked_mul(self)
>     }
> ```

Why here? I think the convention is having a single impl block next to the struct definition.

Also, consider gathering all gas/price/fee structs in a separate file (non blocking)



_Code quote:_
```XML
impl Div<NonzeroGasPrice> for Fee {
    type Output = GasAmount;

    fn div(self, rhs: NonzeroGasPrice) -> Self::Output {
        GasAmount(self.0 / GasPrice::from(rhs).0)
    }
}

impl GasPrice {
    pub const fn saturating_mul(self, rhs: GasAmount) -> Fee {
        Fee(self.0.saturating_mul(rhs.0))
    }

    pub fn checked_mul(self, rhs: GasAmount) -> Option<Fee> {
        self.0.checked_mul(rhs.0).map(Fee)
    }
}

impl NonzeroGasPrice {
    pub const fn saturating_mul(self, rhs: GasAmount) -> Fee {
        self.get().saturating_mul(rhs)
    }

    pub fn checked_mul(self, rhs: GasAmount) -> Option<Fee> {
        self.get().checked_mul(rhs)
    }
}

impl GasAmount {
    pub const fn saturating_mul(self, rhs: GasPrice) -> Fee {
        rhs.saturating_mul(self)
    }

    pub const fn nonzero_saturating_mul(self, rhs: NonzeroGasPrice) -> Fee {
        rhs.saturating_mul(self)
    }

    pub fn checked_mul(self, rhs: GasPrice) -> Option<Fee> {
        rhs.checked_mul(self)
    }
```

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1173)* status: 25 of 42 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1173)* status: 17 of 50 files reviewed, 4 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 205 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1173#-O8XTzHh56pfjpYQ07Cp:-O8aDqFW-pPs87_2C0xU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/455529c6f236b2861397d1b9d7c8b939394c8fb9/crates/blockifier/src/execution/entry_point.rs#L205)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Throughout this PR as well
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/errors.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1173#-O8XXrbe9lc69Db72BVC:-O8aBRMg8a-ylHJX921r:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/455529c6f236b2861397d1b9d7c8b939394c8fb9/crates/blockifier/src/transaction/errors.rs#L60)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Remove `:?`
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/block.rs` line 242 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1173#-O8X_38J3-gqtQnEwmsP:-O8aCOvWD57iYq-AcDvT:b-gn8fup) ([raw file](https://github.com/starkware-libs/sequencer/blob/455529c6f236b2861397d1b9d7c8b939394c8fb9/crates/starknet_api/src/block.rs#L242)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Please document why this struct is needed (since we also have GasPrice in this file)
Also, I guess that the nonzero variant is not part of the block header, so maybe it's not the right file for it (this part is not blocking)
</blockquote></details>

1. It should be in starknet-api so we can have `impl Fee { fn div_ceil(self, rhs: NonzeroGasPrice) -> GasAmount; }`
2. I put it in this module so it's next to `GasPrice`

documented
___
*[`crates/starknet_api/src/transaction.rs` line 812 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1173#-O8XcYFx6KmpuITyKQPv:-O8aDotCCtPlWzDM3hU0:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/455529c6f236b2861397d1b9d7c8b939394c8fb9/crates/starknet_api/src/transaction.rs#L812)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why here? I think the convention is having a single impl block next to the struct definition.

Also, consider gathering all gas/price/fee structs in a separate file (non blocking)
</blockquote></details>

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 42 files at r1, 1 of 13 files at r2, 1 of 11 files at r3, 7 of 23 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1173)* status: 27 of 50 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 205 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1173#-O8XTzHh56pfjpYQ07Cp:-O8aq1ii8dx38BJfK2CU:b-rxusqu) ([raw file](https://github.com/starkware-libs/sequencer/blob/455529c6f236b2861397d1b9d7c8b939394c8fb9/crates/blockifier/src/execution/entry_point.rs#L205)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done :(

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 13 files at r2, 3 of 23 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1173)* status: 31 of 50 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 361 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1173#-O8avfiT5llDvoM3uI5n:-O8avfiT5llDvoM3uI5o:b-2kwag8) ([raw file](https://github.com/starkware-libs/sequencer/blob/f28fdce7237169c9a4b7cd4f14388e96b43abb53/crates/blockifier/src/transaction/test_utils.rs#L361)):*
> ```XML
> ) -> ValidResourceBounds {
>     ValidResourceBounds::AllResources(AllResourceBounds {
>         l1_gas: ResourceBounds {
> ```

Are you going to change its types in a future PR?



_Code quote:_
```XML
ResourceBounds {
```

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 3 of 42 files at r1, 6 of 23 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1173)* status: 40 of 50 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/gateway/src/rpc_objects.rs` line 102 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1173#-O8aw-t8CFW6mNDIrb_X:-O8aw-t8CFW6mNDIrb_Y:b-jhvde0) ([raw file](https://github.com/starkware-libs/sequencer/blob/f28fdce7237169c9a4b7cd4f14388e96b43abb53/crates/gateway/src/rpc_objects.rs#L102)):*
> ```XML
> fn parse_gas_price(gas_price: GasPrice) -> Result<NonzeroGasPrice, RPCStateReaderError> {
>     NonzeroGasPrice::new(gas_price)
>         .map_err(|_| RPCStateReaderError::GasPriceParsingFailure(gas_price))
> ```

What's the difference? 



_Code quote:_
```XML
.map_err(|_|
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1173)* status: 31 of 51 files reviewed, 3 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 205 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1173#-O8XTzHh56pfjpYQ07Cp:-O8bCqqdBQ3-O8KqfUWK:bb5lnyl) ([raw file](https://github.com/starkware-libs/sequencer/blob/455529c6f236b2861397d1b9d7c8b939394c8fb9/crates/blockifier/src/execution/entry_point.rs#L205)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Not done :(
</blockquote></details>

oops... now done, I hope
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 361 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1173#-O8avfiT5llDvoM3uI5n:-O8b7FL_2Gsx71iT855s:b-ayzsq3) ([raw file](https://github.com/starkware-libs/sequencer/blob/f28fdce7237169c9a4b7cd4f14388e96b43abb53/crates/blockifier/src/transaction/test_utils.rs#L361)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Are you going to change its types in a future PR?
</blockquote></details>

[yes](https://reviewable.io/reviews/starkware-libs/sequencer/1180)
___
*[`crates/gateway/src/rpc_objects.rs` line 102 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1173#-O8aw-t8CFW6mNDIrb_X:-O8b7S7OEtUC2P2UvLcu:b5w4pm4) ([raw file](https://github.com/starkware-libs/sequencer/blob/f28fdce7237169c9a4b7cd4f14388e96b43abb53/crates/gateway/src/rpc_objects.rs#L102)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

What's the difference?
</blockquote></details>

`NonZeroU128::new` returns `Option`, while `NonzeroGasPrice::new` returns `Result`

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 42 files at r1, 2 of 13 files at r2, 5 of 23 files at r4, 12 of 12 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1173#-:-O8bg7tX2dSjeWMoy9th:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
