### PR TITLE
chore(sequencing): remove ConsensusMessage and Proposal from proto

### PR DESCRIPTION
**Pull request by guy-starkware**

### CODE REVIEW

**Comment by guy-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2559?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2559** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2559?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2559?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2533** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2533?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2532** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2532?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2528** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2528?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2526** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2526?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2525** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2525?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2524** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2524?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2518** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2518?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2517** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2517?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2512** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2512?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2510** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2510?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2559#-:-OEidyfn72AHdj2KM45w:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2559)* status: all files reviewed, 1 unresolved discussion (waiting on @guy-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2559#-OEriuKjE7LHnRIwvb09:-OEriuKjE7LHnRIwvb0A:b-n3tmrb) ([raw file](https://github.com/starkware-libs/sequencer/blob/1018d1ef3bd695f5d57685e08fa71f0d8086b565/crates/papyrus_protobuf/src/converters/consensus_test.rs#L18)):*
> ```XML
>     Proposal,         // TODO: remove this
>     ProposalFin,
>     ProposalInit,
> ```

Why did you remove the init test?



_Code quote:_
```XML
    ProposalInit,
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2559)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2559#-OEriuKjE7LHnRIwvb09:-OErlmE95PULjLpQyF49:brmk0te) ([raw file](https://github.com/starkware-libs/sequencer/blob/1018d1ef3bd695f5d57685e08fa71f0d8086b565/crates/papyrus_protobuf/src/converters/consensus_test.rs#L18)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why did you remove the init test?
</blockquote></details>

That is a really good question! Reinstating test.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2559)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Pull request merged**
