### PR TITLE
chore: derive serialize and deserialize for chain info

### PR DESCRIPTION
**Pull request by ArniStarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- Derive Serialize/Deserialize towards Papyrus config on these structs.

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/97)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#97** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/97?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/97)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/blockifier/src/context.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/97#-O2e3sDK7vk7XQa6mCPn:-O2e3sDL2bf5wBBmBQEX:b6y287y) ([raw file](https://github.com/starkware-libs/sequencer/blob/b5440216c52e62f50575d708b81996d615078b38/crates/blockifier/src/context.rs#L72)):*
> ```XML
> }
> 
> #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
> ```

Why it's needed?



_Code quote:_
```XML
 PartialEq,
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/97)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

___
*[`crates/blockifier/src/context.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/97#-O2e3sDK7vk7XQa6mCPn:-O36Xz1U8Z47sjJvO1Wg:b-ic9088) ([raw file](https://github.com/starkware-libs/sequencer/blob/b5440216c52e62f50575d708b81996d615078b38/crates/blockifier/src/context.rs#L72)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why it's needed?
</blockquote></details>

The struct `StatefulTransactionValidatorConfig` in the blockifier will use this struct in #99.
It is used for testing. This derive is not heavy, so there is no need to limit it for testing only.

**Comment by ArniStarkware** [comment]
### Merge activity

* **Jul 31, 4:24 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/97).

**Pull request merged**
