### PR TITLE
chore(tests-integration): change rpc state reader visibility, sort module

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #1383
- #1364
- #1363
- #1361
- #1360 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1360)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1360)* status: all files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1360#-O992WVzAsb4wzAX1GVW:-O992WVzAsb4wzAX1GVX:bga64le) ([raw file](https://github.com/starkware-libs/sequencer/blob/739c23a085077f741b844715a5dbaedfd9a236d7/crates/tests-integration/src/integration_test_utils.rs#L40)):*
> ```XML
> 
> pub fn test_rpc_state_reader_config(rpc_server_addr: SocketAddr) -> RpcStateReaderConfig {
>     const RPC_SPEC_VERION: &str = "V0_8";
> ```

Add a todo to get the latest version from the RPC crate (otherwise we will forget to update this in future versions)



_Code quote:_
```XML
const RPC_SPEC_VERION: &str = "V0_8";
```
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1360#-O993ySR1k7sPFnZO9iK:-O993ySR1k7sPFnZO9iL:b-pqhs99) ([raw file](https://github.com/starkware-libs/sequencer/blob/739c23a085077f741b844715a5dbaedfd9a236d7/crates/tests-integration/src/integration_test_utils.rs#L117)):*
> ```XML
>     let socket = get_available_socket().await;
>     HttpServerConfig { ip: socket.ip(), port: socket.port() }
> }
> ```

In a separate PR you can change the config to use generated params: 
https://github.com/starkware-libs/sequencer/blob/985a2578cc539cb7506ee26dfc606e5241fa17ec/crates/papyrus_config/src/dumping.rs#L169-L172



_Code quote:_
```XML
async fn create_http_server_config() -> HttpServerConfig {
    let socket = get_available_socket().await;
    HttpServerConfig { ip: socket.ip(), port: socket.port() }
}
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1360)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1360#-O992WVzAsb4wzAX1GVW:-O999EkR34nDvggm_vSv:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/739c23a085077f741b844715a5dbaedfd9a236d7/crates/tests-integration/src/integration_test_utils.rs#L40)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add a todo to get the latest version from the RPC crate (otherwise we will forget to update this in future versions)
</blockquote></details>

Done.
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1360#-O993ySR1k7sPFnZO9iK:-O999F8F2g5Z9TK76kw8:b4clok5) ([raw file](https://github.com/starkware-libs/sequencer/blob/739c23a085077f741b844715a5dbaedfd9a236d7/crates/tests-integration/src/integration_test_utils.rs#L117)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

In a separate PR you can change the config to use generated params: 
https://github.com/starkware-libs/sequencer/blob/985a2578cc539cb7506ee26dfc606e5241fa17ec/crates/papyrus_config/src/dumping.rs#L169-L172
</blockquote></details>

Added a todo, but I'd need an explanation.

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1360)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#1361](https://github.com/starkware-libs/sequencer/pull/1361)

**Pull request closed without merging**
