### PR TITLE
feat(consensus): run network manager in consensus

### PR DESCRIPTION
**Pull request by dan-starkware**

### CODE REVIEW

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1809#-:-OAv8LaD7u9vn4YYixsE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware and @matan-starkware)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1809)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/papyrus_node/src/run.rs` line 181 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1809#-OAvErHF4vZY1RpSL74Y:-OAvErHF4vZY1RpSL74Z:bizbmzn) ([raw file](https://github.com/starkware-libs/sequencer/blob/898a552f5878c28b90eb225cd9c3907794535b0d/crates/papyrus_node/src/run.rs#L181)):*
> ```XML
>     let (Some(config), Some(network_manager)) = (config, network_manager) else {
>         info!("Consensus is disabled.");
>         return Ok(tokio::spawn(future::pending()));
> ```

Consider wrapping with a function that indicates this purpose, e.g., `run_void_network`.



_Code quote:_
```XML
tokio::spawn(future::pending())
```
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1809#-OAvDkJ980s0nJs-YyhZ:-OAvDkJ980s0nJs-Yyh_:b-m23t7u) ([raw file](https://github.com/starkware-libs/sequencer/blob/898a552f5878c28b90eb225cd9c3907794535b0d/crates/sequencing/papyrus_consensus/src/manager.rs#L88)):*
> ```XML
>                 metrics::increment_counter!(PAPYRUS_CONSENSUS_SYNC_COUNT);
>                 current_height = sync_height?.unchecked_next();
>             }
> ```

Unrelated to this pr, but IIUC this code pattern results in the one of select branches being dropped at possiblely different locations, which might cause undesired results. We had a similar issue in the batcher with the `get_txs` branch being dropped mid-run. IIRC we decided to avoid this.



_Code quote:_
```XML
            decision = run_height => {
                let decision = decision?;
                context.decision_reached(decision.block, decision.precommits).await?;
                current_height = current_height.unchecked_next();
            },
            sync_height = sync_height(current_height, &mut sync_receiver) => {
                metrics::increment_counter!(PAPYRUS_CONSENSUS_SYNC_COUNT);
                current_height = sync_height?.unchecked_next();
            }
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1809)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @Itay-Tsabary-Starkware)

___
*[`crates/consensus_manager/src/consensus_manager.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1809#-OAw8FBDD3n3FJ3dy6V4:-OAw8FBDD3n3FJ3dy6V5:b3rjt5e) ([raw file](https://github.com/starkware-libs/sequencer/blob/98f96a63e7917e279f12fb0c0a30680c81d46528/crates/consensus_manager/src/consensus_manager.rs#L55)):*
> ```XML
>             futures::stream::pending(),
>         )
>         .await
> ```

This is the only example I find for adding `network_handle` to consensus. From the perspective of consensus I don't see how this makes sense as an input, and I think that it's a solvable problem to hold the network outside of consensus. You could then await both with select if you care about the result.

If you don't care to see the result (error) you don't need to await a tokio spawn at all for it to run: "The provided future will start running in the background immediately when `spawn` is called, even if you don’t await the returned `JoinHandle`."



_Suggestion:_
```XML
        let network_handle = tokio::task::spawn(network_manager.run());

        papyrus_consensus::run_consensus(
            context,
            self.config.consensus_config.start_height,
            self.config.consensus_config.validator_id,
            self.config.consensus_config.consensus_delay,
            self.config.consensus_config.timeouts.clone(),
            create_fake_network_channels(),
            futures::stream::pending(),
        )
        .await
```
___
*[`crates/papyrus_node/src/run.rs` line 181 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1809#-OAvErHF4vZY1RpSL74Y:-OAw7SYM0bHDdinuaJy5:b-pl0157) ([raw file](https://github.com/starkware-libs/sequencer/blob/98f96a63e7917e279f12fb0c0a30680c81d46528/crates/papyrus_node/src/run.rs#L181)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Consider wrapping with a function that indicates this purpose, e.g., `run_void_network`.
</blockquote></details>

There is a log above "Consensus is disabled", I think wrapping this would just be an added layer of indirection for a 1 liner.
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1809#-OAw7t7i5lb0xNTMjlL8:-OAw7t7i5lb0xNTMjlL9:b-7zsv7z) ([raw file](https://github.com/starkware-libs/sequencer/blob/98f96a63e7917e279f12fb0c0a30680c81d46528/crates/sequencing/papyrus_consensus/src/manager.rs#L36)):*
> ```XML
> #[allow(clippy::too_many_arguments)]
> pub async fn run_consensus<ContextT, SyncReceiverT>(
>     mut network_handle: JoinHandle<Result<(), NetworkError>>,
> ```

Why? The network is meant to be something external to consensus, not something that we have some "ownership" of.



_Code quote:_
```XML
    mut network_handle: JoinHandle<Result<(), NetworkError>>,
```

**Comment by dan-starkware** [comment]
### Merge activity

* **Nov 7, 8:22 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1809).

**Pull request merged**
