### PR TITLE
test(starknet_gateway): handle todo in test_get_block_info

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2267?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2267** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2267?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2267?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2238** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2238?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2237** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2237?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2246** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2246?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2230](https://github.com/starkware-libs/sequencer/pull/2230) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2230?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2245** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2245?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2244** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2244?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2243** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2243?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ArniStarkware** [comment]
*[`crates/starknet_gateway/src/rpc_state_reader_test.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2267#-OCnRuw_6cPVvtQHy5Pb:-OD1N0_r9sxjdBRGs0ow:b-5zeugc) ([raw file](https://github.com/starkware-libs/sequencer/blob/3134674e176989516ea7e09c0000fa36751330f9/crates/starknet_gateway/src/rpc_state_reader_test.rs#L74)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why not expect the default value?
</blockquote></details>

The function `get_block_info()` will return `use_kzg_da == false` becasue the default value here is: https://github.com/starkware-libs/sequencer/blob/df433f1b888dc73b3c5c122cdc7006779aaa45d5/crates/starknet_api/src/data_availability.rs#L81

On the other hand, in a previous PR: (#2238), we set the use_kzg flag as `true` - to match the (to be deprecated) block builder config.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2267)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/starknet_gateway/src/rpc_state_reader_test.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2267#-OCnRuw_6cPVvtQHy5Pb:-OD1PVjv24fPX5aCaXAH:b-51i7r6) ([raw file](https://github.com/starkware-libs/sequencer/blob/3134674e176989516ea7e09c0000fa36751330f9/crates/starknet_gateway/src/rpc_state_reader_test.rs#L74)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The function `get_block_info()` will return `use_kzg_da == false` becasue the default value here is: https://github.com/starkware-libs/sequencer/blob/df433f1b888dc73b3c5c122cdc7006779aaa45d5/crates/starknet_api/src/data_availability.rs#L81

On the other hand, in a previous PR: (#2238), we set the use_kzg flag as `true` - to match the (to be deprecated) block builder config.
</blockquote></details>

Sorry - the relevant PR is: #2345.

**Comment by yair-starkware** [comment]
*[`crates/starknet_gateway/src/rpc_state_reader_test.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2267#-OCnRuw_6cPVvtQHy5Pb:-OD1UC3W8KiWo_HID7E5:b1itf6y) ([raw file](https://github.com/starkware-libs/sequencer/blob/3134674e176989516ea7e09c0000fa36751330f9/crates/starknet_gateway/src/rpc_state_reader_test.rs#L74)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Sorry - the relevant PR is: #2345.
</blockquote></details>

So the default `BlockInfo` doesn't match the default `L1DataAvailabilityMode`?
Is this going to be resolved by removing the default implementation of `BlockInfo`?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2267)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/starknet_gateway/src/rpc_state_reader_test.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2267#-OCnRuw_6cPVvtQHy5Pb:-OD1VPvUBwVlSx8G_p1S:b-qpbnhe) ([raw file](https://github.com/starkware-libs/sequencer/blob/3134674e176989516ea7e09c0000fa36751330f9/crates/starknet_gateway/src/rpc_state_reader_test.rs#L74)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

So the default `BlockInfo` doesn't match the default `L1DataAvailabilityMode`?
Is this going to be resolved by removing the default implementation of `BlockInfo`?
</blockquote></details>

Now they are aligned.
I just modified #2345.

Also - yes - `BlockInfo` should not have a default value.

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2267)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Dec 5, 4:36 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2267).

**Pull request merged**
