### PR TITLE
chore(infra): add bootstrap flow to the ci

### PR DESCRIPTION
**Pull request by alon-dotan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/941)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/941)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @noaov1)

___
*[`.github/actions/bootstrap/action.yml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/941#-O7Sg2eXEz0JdxDtINNr:-O7Sg2eXEz0JdxDtINNs:b7iueic) ([raw file](https://github.com/starkware-libs/sequencer/blob/ddf1240fe4802c9dd061e478c3827c12a51a5442/.github/actions/bootstrap/action.yml#L5)):*
> ```YAML
>   steps:
>     - name: Install rust.
>       uses: ./.github/actions/bootstrap
> ```

this is recursive... this file *is* `actions/bootstrap`
did you mean to call `install_rust`?



_Code quote:_
```YAML
uses: ./.github/actions/bootstrap
```

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/941)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`.github/actions/bootstrap/action.yml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/941#-O7Sg2eXEz0JdxDtINNr:-O7ShMfO5X5gEzsS0Dnn:byr8bc3) ([raw file](https://github.com/starkware-libs/sequencer/blob/ddf1240fe4802c9dd061e478c3827c12a51a5442/.github/actions/bootstrap/action.yml#L5)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is recursive... this file *is* `actions/bootstrap`
did you mean to call `install_rust`?
</blockquote></details>

yes...
Thanks

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/941#-:-O7SiLVbCk17d6HUcBuf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/941)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @noaov1)

___
*[`.github/actions/install_rust/action.yml` line 9 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/941#-O7XxfDFDVIgXy3UM8iM:-O7XxfDFDVIgXy3UM8iN:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0495d0e4d653d7be9581765308c0e2406df9b7a2/.github/actions/install_rust/action.yml#L9)):*
> ```YAML
>     - uses: moonrepo/setup-rust@v1
>       with:
>         cache-base: (main-v[0-9].*)
> ```





_Suggestion:_
```YAML
main(-v[0-9].*)?
```

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/941)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`.github/actions/install_rust/action.yml` line 9 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/941#-O7XxfDFDVIgXy3UM8iM:-O7Y_OF2AzjZexpZx-Lx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0495d0e4d653d7be9581765308c0e2406df9b7a2/.github/actions/install_rust/action.yml#L9)):*
> ```YAML
>     - uses: moonrepo/setup-rust@v1
>       with:
>         cache-base: (main-v[0-9].*)
> ```

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/941)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
