### PR TITLE
chore: add create client macro

### PR DESCRIPTION
**Pull request by nadin-Starkware**
**Stack**:
- #1909
- #1878
- #1877
- #1876
- #1874 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1874)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/sequencer_node/src/clients.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1874#-OB9vZpuEH6l5IYx83gq:-OB9vZpuEH6l5IYx83gr:b-wikrbr) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f06ee012323d860a7e097ad8337504141eb0edf/crates/sequencer_node/src/clients.rs#L44)):*
> ```XML
> /// This macro simplifies the creation of a client by evaluating the execution mode
> /// and conditionally constructing the client only if the mode is enabled (either
> /// LocalExecutionWithRemoteDisabled or LocalExecutionWithRemoteEnabled).
> ```

Let's make this more concise: wydt about

```
A macro for creating a component client, determined by the component's execution mode. Returns a local client if the component is run locally, otherwise `None`.
```

Later when adding the remote client we can modify this doc to detail the remote client option as well.



_Code quote:_
```XML
/// A macro to create a shared client based on the component's execution mode.
///
/// This macro simplifies the creation of a client by evaluating the execution mode
/// and conditionally constructing the client only if the mode is enabled (either
/// LocalExecutionWithRemoteDisabled or LocalExecutionWithRemoteEnabled).
```
___
*[`crates/sequencer_node/src/clients.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1874#-OB9wMV23lGju_6a9y1M:-OB9wMV23lGju_6a9y1N:b-ivx9hz) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f06ee012323d860a7e097ad8337504141eb0edf/crates/sequencer_node/src/clients.rs#L49)):*
> ```XML
> ///
> /// * $execution_mode - A reference to the execution mode to evaluate, expected to be of type
> ///   ComponentExecutionMode.
> ```

A reference to the component's execution mode, i.e., type `&ComponentExecutionMode`



_Code quote:_
```XML
/// * $execution_mode - A reference to the execution mode to evaluate, expected to be of type
///   ComponentExecutionMode.
```
___
*[`crates/sequencer_node/src/clients.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1874#-OB9x5VTAuisXOvi8sYM:-OB9x5VTAuisXOvi8sYN:b1bwqnv) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f06ee012323d860a7e097ad8337504141eb0edf/crates/sequencer_node/src/clients.rs#L50)):*
> ```XML
> /// * $execution_mode - A reference to the execution mode to evaluate, expected to be of type
> ///   ComponentExecutionMode.
> /// * $client_type - The type of the client to create, such as LocalBatcherClient.
> ```

The client type to create, e.g., LocalBatcherClient. The client type should have a function $client_type::new(tx : $channel_expr).



_Code quote:_
```XML
The type of the client to create, such as LocalBatcherClient.
```
___
*[`crates/sequencer_node/src/clients.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1874#-OB9xljK8mxqgOgIfGRP:-OB9xljK8mxqgOgIfGRQ:b-nj82x2) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f06ee012323d860a7e097ad8337504141eb0edf/crates/sequencer_node/src/clients.rs#L51)):*
> ```XML
> ///   ComponentExecutionMode.
> /// * $client_type - The type of the client to create, such as LocalBatcherClient.
> /// * $channel_expr - An expression to retrieve the channel required for the client, e.g.,
> ```

Sender side for the client.



_Code quote:_
```XML
An expression to retrieve the channel required for the client
```
___
*[`crates/sequencer_node/src/clients.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1874#-OB9xWZZEc09Z96Bm-q5:-OB9xWZZEc09Z96Bm-q6:b-xx162s) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f06ee012323d860a7e097ad8337504141eb0edf/crates/sequencer_node/src/clients.rs#L52)):*
> ```XML
> /// * $client_type - The type of the client to create, such as LocalBatcherClient.
> /// * $channel_expr - An expression to retrieve the channel required for the client, e.g.,
> ///   channels.take_batcher_tx().
> ```

Let's make this the 2nd arguement (i.e., replace the order with client type), so we can better describe what client type is.



_Code quote:_
```XML
/// * $channel_expr - An expression to retrieve the channel required for the client, e.g.,
///   channels.take_batcher_tx().
```
___
*[`crates/sequencer_node/src/clients.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1874#-OB9y36N6RfDceYq8MH1:-OB9y36N6RfDceYq8MH2:b-dqbeop) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f06ee012323d860a7e097ad8337504141eb0edf/crates/sequencer_node/src/clients.rs#L57)):*
> ```XML
> ///
> /// An `Option<Arc<dyn ClientType>>` containing the client if the execution mode is enabled,
> /// or None if the execution mode is Disabled.
> ```

Be more explicit regarding the `enabled` option, as `Disabled` is an actual enum variant whereas `enabled` isn't.



_Code quote:_
```XML
/// An `Option<Arc<dyn ClientType>>` containing the client if the execution mode is enabled,
/// or None if the execution mode is Disabled.
```
___
*[`crates/sequencer_node/src/clients.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1874#-OB9yCsF2rxFv0m1B4xP:-OB9yCsF2rxFv0m1B4xQ:b-squua0) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f06ee012323d860a7e097ad8337504141eb0edf/crates/sequencer_node/src/clients.rs#L74)):*
> ```XML
> ///     None => println!("Client not created because the execution mode is disabled."),
> /// }
> /// ```
> ```

Can you make this example compile/pass?
I.e., drop the `ignore`



_Code quote:_
```XML
/// ```rust,ignore
/// // Assuming ComponentExecutionMode and channels are defined, and LocalBatcherClient
/// // has a new method that accepts a channel.
/// let batcher_client: Option<SharedBatcherClient> = create_client!(
///     &config.components.batcher.execution_mode,
///     LocalBatcherClient,
///     channels.take_batcher_tx()
/// );
///
/// match batcher_client {
///     Some(client) => println!("Client created: {:?}", client),
///     None => println!("Client not created because the execution mode is disabled."),
/// }
/// ```
```
___
*[`crates/sequencer_node/src/clients.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1874#-OB9yPoI5UmGe_-lQTII:-OB9yPoI5UmGe_-lQTIJ:b-gutwdw) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f06ee012323d860a7e097ad8337504141eb0edf/crates/sequencer_node/src/clients.rs#L91)):*
> ```XML
>     channels: &mut SequencerNodeCommunication,
> ) -> SequencerNodeClients {
>     let batcher_client: Option<SharedBatcherClient> = create_client!(
> ```

Are these type annotations required?



_Code quote:_
```XML
Option<SharedBatcherClient>
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1874)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/sequencer_node/src/clients.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1874#-OB9vZpuEH6l5IYx83gq:-OBKSlOj2NU4Rch27Wxl:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f06ee012323d860a7e097ad8337504141eb0edf/crates/sequencer_node/src/clients.rs#L44)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Let's make this more concise: wydt about

```
A macro for creating a component client, determined by the component's execution mode. Returns a local client if the component is run locally, otherwise `None`.
```

Later when adding the remote client we can modify this doc to detail the remote client option as well.
</blockquote></details>

Done.
___
*[`crates/sequencer_node/src/clients.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1874#-OB9wMV23lGju_6a9y1M:-OBKSuIf1mLplVssseWk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f06ee012323d860a7e097ad8337504141eb0edf/crates/sequencer_node/src/clients.rs#L49)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

A reference to the component's execution mode, i.e., type `&ComponentExecutionMode`
</blockquote></details>

Done.
___
*[`crates/sequencer_node/src/clients.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1874#-OB9x5VTAuisXOvi8sYM:-OBKT-iF3iGAphrifSAc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f06ee012323d860a7e097ad8337504141eb0edf/crates/sequencer_node/src/clients.rs#L50)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

The client type to create, e.g., LocalBatcherClient. The client type should have a function $client_type::new(tx : $channel_expr).
</blockquote></details>

Done.
___
*[`crates/sequencer_node/src/clients.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1874#-OB9xljK8mxqgOgIfGRP:-OBKT3WZCq-NQEweaKDW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f06ee012323d860a7e097ad8337504141eb0edf/crates/sequencer_node/src/clients.rs#L51)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Sender side for the client.
</blockquote></details>

Done.
___
*[`crates/sequencer_node/src/clients.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1874#-OB9xWZZEc09Z96Bm-q5:-OBKTOF8BUJHLgsJ8cB-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f06ee012323d860a7e097ad8337504141eb0edf/crates/sequencer_node/src/clients.rs#L52)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Let's make this the 2nd arguement (i.e., replace the order with client type), so we can better describe what client type is.
</blockquote></details>

Done.
___
*[`crates/sequencer_node/src/clients.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1874#-OB9y36N6RfDceYq8MH1:-OBKT_bA8fTNpubIrqqH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f06ee012323d860a7e097ad8337504141eb0edf/crates/sequencer_node/src/clients.rs#L57)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Be more explicit regarding the `enabled` option, as `Disabled` is an actual enum variant whereas `enabled` isn't.
</blockquote></details>

Done.
___
*[`crates/sequencer_node/src/clients.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1874#-OB9yCsF2rxFv0m1B4xP:-OBKThKy-4lXuPByMRys:b52p03d) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f06ee012323d860a7e097ad8337504141eb0edf/crates/sequencer_node/src/clients.rs#L74)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can you make this example compile/pass?
I.e., drop the `ignore`
</blockquote></details>

No, I get not found in this scope on the macro.
___
*[`crates/sequencer_node/src/clients.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1874#-OB9yPoI5UmGe_-lQTII:-OBF35FECVoEyIuznnnC:bhvq5lj) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f06ee012323d860a7e097ad8337504141eb0edf/crates/sequencer_node/src/clients.rs#L91)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Are these type annotations required?
</blockquote></details>

The type annotation is necessary because it tells Rust to treat LocalComponentClient<BatcherRequest, BatcherResponse> as the trait object BatcherClient. This annotation triggers a coercion from Arc<LocalComponentClient> to Arc<dyn BatcherClient>, which Rust wouldn’t do automatically without the annotation, resulting in a type mismatch.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1874#-:-OBLMp_314KII4temVR1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Comment by nadin-Starkware** [comment]
✓ Commit merged in pull request [#1909](https://github.com/starkware-libs/sequencer/pull/1909)

**Pull request closed without merging**
