### PR TITLE
chore(batcher): unify client implementations

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #2119
- #2115
- #2090
- #2089
- #2088
- #2087
- #2086 ⬅
- #2085

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by nadin-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2086)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_batcher_types/src/communication.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2086#-OBuEMva5EcSyu98TmV5:-OBuEMva5EcSyu98TmV6:b6853n2) ([raw file](https://github.com/starkware-libs/sequencer/blob/812d81f5988081e54f9fac7d9719c732e76ef8e7/crates/starknet_batcher_types/src/communication.rs#L103)):*
> ```XML
> 
> #[async_trait]
> impl<T> BatcherClient for T
> ```

Please replace T with a more descriptive name, such as ClientType or something similar.



_Code quote:_
```XML
T
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2086)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/starknet_batcher_types/src/communication.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2086#-OBuEMva5EcSyu98TmV5:-OBuSlPG65rU5RlvGxdn:b-wz03i1) ([raw file](https://github.com/starkware-libs/sequencer/blob/2ed99b85b8abe27e5e3d101e9eb7e5b82e13955d/crates/starknet_batcher_types/src/communication.rs#L103)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Please replace T with a more descriptive name, such as ClientType or something similar.
</blockquote></details>

As a single pr at the end :pray:

**Review by nadin-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2086)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2086)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#2119](https://github.com/starkware-libs/sequencer/pull/2119)

**Pull request closed without merging**
