### PR TITLE
fix(blockifier): bouncer_weights::sierra_gas change from gas_amount to u64

### PR DESCRIPTION
**Pull request by avivg-starkware**

### CODE REVIEW

**Comment by avivg-starkware** [comment]
* **#2772** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2772?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2772?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2772#-:-OET1EGEAtaz0ud0KAJA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @noaov1)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2772)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware and @noaov1)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2772#-OETFUj707ry2EZoX1AN:-OETFUj707ry2EZoX1AO:b-nmpj9y) (no related file):*
why not implement saturating_add and use everywhere...?

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2772)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request closed without merging**
