### PR TITLE
chore(sequencing): remove ConsensusMessage from stream_handler_test

### PR DESCRIPTION
**Pull request by guy-starkware**

### CODE REVIEW

**Comment by guy-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2526?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2526** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2526?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2526?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2525** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2525?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2524** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2524?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2518** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2518?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2517** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2517?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2512** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2512?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2510** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2510?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2526#-:-OEEiMZyE7o4QZ22d7gy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2526)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Review by guy-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2526)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Comment by guy-starkware** [comment]
### Merge activity

* **Dec 20, 2:30 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2526).

**Pull request merged**
