### PR TITLE
feat(mempool): add account nonces field and adjust mempool content ac…

### PR DESCRIPTION
**Pull request by ayeletstarkware**
…crodingly

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/592)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/592)* status: 0 of 2 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5Chj3gAdC80lcE9RuJ:-O5Chj3gAdC80lcE9RuK:bh2c88t) (no related file):*
STACK OF PRS:
1. #590 
2. #560 
3. #591 
4. #592 (YOU'RE HERE)
5. #534

___

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/592)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5ED8Io5N02NIdRFaCS:-O5ED8Ip8nGK-7oHMyKE:bt7qfjd) ([raw file](https://github.com/starkware-libs/sequencer/blob/b6120041b810f67ecd1efad5422151ad5b7a444c/crates/mempool/src/mempool.rs#L27)):*
> ```XML
>     // Represents the current state of the mempool during block creation.
>     mempool_state: HashMap<ContractAddress, AccountState>,
>     // The most recent account nonces received (might change right after), for all account in the
> ```

wdym by that?



_Code quote:_
```XML
might change right after
```
___
*[`crates/mempool/src/mempool_test.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5EDCla4olj6AVBjZsw:-O5EDClb6w4fjbQlwCez:bcqnidh) ([raw file](https://github.com/starkware-libs/sequencer/blob/b6120041b810f67ecd1efad5422151ad5b7a444c/crates/mempool/src/mempool_test.rs#L20)):*
> ```XML
> use starknet_types_core::felt::Felt;
> 
> use super::AccountToNonce;
> ```

do not use super



_Code quote:_
```XML
super
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/592)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5ED8Io5N02NIdRFaCS:-O5HggSM9wK3RC2IgtUy:bzzra7) ([raw file](https://github.com/starkware-libs/sequencer/blob/b6120041b810f67ecd1efad5422151ad5b7a444c/crates/mempool/src/mempool.rs#L27)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

wdym by that?
</blockquote></details>

I have no idea. deleted. 
___
*[`crates/mempool/src/mempool_test.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5EDCla4olj6AVBjZsw:-O5HgX2fEE8mFnBJJgp6:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b6120041b810f67ecd1efad5422151ad5b7a444c/crates/mempool/src/mempool_test.rs#L20)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

do not use super
</blockquote></details>

Done.

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/592#-:-O5N7FDr9k-ud5Z-V-aP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/592)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5NKD7a724ZCA4zbA8X:-O5NKD7a724ZCA4zbA8Y:b-slwd4j) ([raw file](https://github.com/starkware-libs/sequencer/blob/90ac2de1f84f0c920e5ec7b683c9ed7499a21185/crates/mempool/src/mempool.rs#L29)):*
> ```XML
>     // The most recent account nonces received, for all account in the pool.
>     #[allow(dead_code)]
>     account_nonces: AccountToNonce,
> ```

Easy to forget about the dead_code thing



_Suggestion:_
```XML
    _account_nonces: AccountToNonce,
```
___
*[`crates/mempool/src/mempool_test.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5NUDaNBKfyAkPVooym:-O5NUDaNBKfyAkPVooyn:buf66l0) ([raw file](https://github.com/starkware-libs/sequencer/blob/90ac2de1f84f0c920e5ec7b683c9ed7499a21185/crates/mempool/src/mempool_test.rs#L38)):*
> ```XML
> 
> #[derive(Debug)]
> struct PartialContent;
> ```

Is this the only possible value for T? 



_Code quote:_
```XML
#[derive(Debug)]
struct PartialContent;
```
___
*[`crates/mempool/src/mempool_test.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5NTguZ86yJrFlDG5O0:-O5NTguZ86yJrFlDG5O1:b88f7cm) ([raw file](https://github.com/starkware-libs/sequencer/blob/90ac2de1f84f0c920e5ec7b683c9ed7499a21185/crates/mempool/src/mempool_test.rs#L63)):*
> ```XML
>             tx_queue: None,
>             account_nonces: None,
>             _phantom: std::marker::PhantomData,
> ```

also in the other ones,  on a separate PR.



_Suggestion:_
```XML
Self::default()
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/592)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5NKD7a724ZCA4zbA8X:-O5NWGdP-gHSL9dA9h4G:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/90ac2de1f84f0c920e5ec7b683c9ed7499a21185/crates/mempool/src/mempool.rs#L29)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Easy to forget about the dead_code thing
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5NUDaNBKfyAkPVooym:-O5NWIT3CJ8Uc_WrclDo:b-urlh17) ([raw file](https://github.com/starkware-libs/sequencer/blob/90ac2de1f84f0c920e5ec7b683c9ed7499a21185/crates/mempool/src/mempool_test.rs#L38)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Is this the only possible value for T?
</blockquote></details>

For now, yes. There was a full state, but it is no longer in use, so it was deleted. It might be needed in the future and will be added if necessary.
___
*[`crates/mempool/src/mempool_test.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5NTguZ86yJrFlDG5O0:-O5NWlbm8u52_2NK7f2g:bbglzwr) ([raw file](https://github.com/starkware-libs/sequencer/blob/90ac2de1f84f0c920e5ec7b683c9ed7499a21185/crates/mempool/src/mempool_test.rs#L63)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

also in the other ones,  on a separate PR.
</blockquote></details>

Why? The default for these structs is not `None`.

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/592)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5NUDaNBKfyAkPVooym:-O5NaKDx-c6LcQK1D3Uo:br2efpa) ([raw file](https://github.com/starkware-libs/sequencer/blob/90ac2de1f84f0c920e5ec7b683c9ed7499a21185/crates/mempool/src/mempool_test.rs#L38)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

For now, yes. There was a full state, but it is no longer in use, so it was deleted. It might be needed in the future and will be added if necessary.
</blockquote></details>

Do we have any concrete plans for reintroducing FullState? 

If there's nothing concrete then the generic and PartialState should both be removed, it is very confusing to new readers otherwise.
___
*[`crates/mempool/src/mempool_test.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5NTguZ86yJrFlDG5O0:-O5NaqbA0cdf0NLK6ZKJ:bqitcv3) ([raw file](https://github.com/starkware-libs/sequencer/blob/90ac2de1f84f0c920e5ec7b683c9ed7499a21185/crates/mempool/src/mempool_test.rs#L63)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Why? The default for these structs is not `None`.
</blockquote></details>

I think there's a disconnect. Note that I only removed the last three fields; the tx_pool field, which was Some, was not removed.

```rust
    fn with_pool<P>(pool_txs: P) -> Self
    where
        P: IntoIterator<Item = Transaction>,
    {
        Self {
            tx_pool: Some(pool_txs.into_iter().collect()),
            ..Self::default()
        }
    }
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/592)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5NUDaNBKfyAkPVooym:-O5NhRj2-t5kMlr7XfpY:b-hby1ph) ([raw file](https://github.com/starkware-libs/sequencer/blob/90ac2de1f84f0c920e5ec7b683c9ed7499a21185/crates/mempool/src/mempool_test.rs#L38)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Do we have any concrete plans for reintroducing FullState? 

If there's nothing concrete then the generic and PartialState should both be removed, it is very confusing to new readers otherwise.
</blockquote></details>

added a todo, will do it in a different PR.
___
*[`crates/mempool/src/mempool_test.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5NTguZ86yJrFlDG5O0:-O5OAKeUBGzzTjsS1Z0L:b-bz2nn1) ([raw file](https://github.com/starkware-libs/sequencer/blob/90ac2de1f84f0c920e5ec7b683c9ed7499a21185/crates/mempool/src/mempool_test.rs#L63)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think there's a disconnect. Note that I only removed the last three fields; the tx_pool field, which was Some, was not removed.

```rust
    fn with_pool<P>(pool_txs: P) -> Self
    where
        P: IntoIterator<Item = Transaction>,
    {
        Self {
            tx_pool: Some(pool_txs.into_iter().collect()),
            ..Self::default()
        }
    }
```
</blockquote></details>

I still don't understand. You removed fields that should have `None` values. If I use `Default`, I get empty values, but not `None` for them.

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/592)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5NUDaNBKfyAkPVooym:-O5OdLs93m-rFuMMa9XW:bwa4x01) ([raw file](https://github.com/starkware-libs/sequencer/blob/90ac2de1f84f0c920e5ec7b683c9ed7499a21185/crates/mempool/src/mempool_test.rs#L38)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

added a todo, will do it in a different PR.
</blockquote></details>

No need for a TODO, you can open the other PR in parallel to this one
___
*[`crates/mempool/src/mempool_test.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5NTguZ86yJrFlDG5O0:-O5Oct2G1jxGU5O_r0x8:bgnbfw8) ([raw file](https://github.com/starkware-libs/sequencer/blob/90ac2de1f84f0c920e5ec7b683c9ed7499a21185/crates/mempool/src/mempool_test.rs#L63)):*
>I get empty values

WDYM?

Default of `Option<T>` is `None` AFAIK, please check.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/592)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5NUDaNBKfyAkPVooym:-O5Rc-wF-MY2aR3SuxdY:b9yypt9) ([raw file](https://github.com/starkware-libs/sequencer/blob/90ac2de1f84f0c920e5ec7b683c9ed7499a21185/crates/mempool/src/mempool_test.rs#L38)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

No need for a TODO, you can open the other PR in parallel to this one
</blockquote></details>

Ok, i'm leaving this TODO so I won't forget. 
___
*[`crates/mempool/src/mempool_test.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5NTguZ86yJrFlDG5O0:-O5Rbefl0i4z6ceMur11:bt7va2) ([raw file](https://github.com/starkware-libs/sequencer/blob/90ac2de1f84f0c920e5ec7b683c9ed7499a21185/crates/mempool/src/mempool_test.rs#L63)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

>I get empty values

WDYM?

Default of `Option<T>` is `None` AFAIK, please check.
</blockquote></details>

okay, opening another PR.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/592)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5NUDaNBKfyAkPVooym:-O5ReuTH26li6CCC1i_U:b-cfosod) ([raw file](https://github.com/starkware-libs/sequencer/blob/90ac2de1f84f0c920e5ec7b683c9ed7499a21185/crates/mempool/src/mempool_test.rs#L38)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Ok, i'm leaving this TODO so I won't forget.
</blockquote></details>

removed the TODO, opened a PR. #648

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/592)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/592)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/592#-O5NTguZ86yJrFlDG5O0:-O5SCmYT2aWDQBEHNOwM:bb68ct2) ([raw file](https://github.com/starkware-libs/sequencer/blob/90ac2de1f84f0c920e5ec7b683c9ed7499a21185/crates/mempool/src/mempool_test.rs#L63)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

okay, opening another PR.
</blockquote></details>

#653

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/592#-:-O5SHKV43SP2kXKBcCH4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Pull request merged**
