### PR TITLE
chore: create rpc transaction args struct for tests

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1798?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1799** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1799?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1798** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1798?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1790** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1790?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1798#-:-OArphHNCkBMBK_pr9Sj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @noam-starkware)

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1798)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @noam-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1798#-OArq1xU06JjKVPxQ-i_:-OArq1xVDgKlZ_GsD2Qg:b-e0cw6r) ([raw file](https://github.com/starkware-libs/sequencer/blob/a03a28d12134be46c36007e139bab491ffbb1d7d/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L68)):*
> ```XML
> 
> #[derive(Clone)]
> pub struct RpcTransactionArgs {
> ```

why do we need this truct? how these fields are related to each other?



_Code quote:_
```XML
RpcTransactionArgs
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1798)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noam-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1798#-OArq1xU06JjKVPxQ-i_:-OArreP046pkfVFyznL5:bjzccx3) ([raw file](https://github.com/starkware-libs/sequencer/blob/a03a28d12134be46c36007e139bab491ffbb1d7d/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L68)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why do we need this truct? how these fields are related to each other?
</blockquote></details>

They are the arguments for the following function - wrapped in a struct.

This PR (and the one after it) shows how it reduces boilerplate code.

```
rpc_tx_for_testing(tx_type, resource_bounds, calldata![], TransactionSignature::default());
```
Becomes:
```
let tx = rpc_tx_for_testing(RpcTransactionArgs {
        tx_type,
        resource_bounds,
        ..DEFAULT_RPC_TRANSACTION_ARGS.clone()
    });
```
i.e. deletes the empty `calldata` and `signature`.



If I had created a macro that does that even more simply - it would read even cleaner... hum

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1798)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @alonh5, @ayeletstarkware, and @noam-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1798#-OArq1xU06JjKVPxQ-i_:-OAsVAIB7lhCuAL7rLcS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a03a28d12134be46c36007e139bab491ffbb1d7d/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L68)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

They are the arguments for the following function - wrapped in a struct.

This PR (and the one after it) shows how it reduces boilerplate code.

```
rpc_tx_for_testing(tx_type, resource_bounds, calldata![], TransactionSignature::default());
```
Becomes:
```
let tx = rpc_tx_for_testing(RpcTransactionArgs {
        tx_type,
        resource_bounds,
        ..DEFAULT_RPC_TRANSACTION_ARGS.clone()
    });
```
i.e. deletes the empty `calldata` and `signature`.



If I had created a macro that does that even more simply - it would read even cleaner... hum
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1798)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @noam-starkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Nov 5, 3:13 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1798).

**Pull request merged**
