### PR TITLE
fix(mempool): in add_tx, delete queue transaction with lower nonce t…

### PR DESCRIPTION
**Pull request by ayeletstarkware**
…hat account nonce

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/452)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/452)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4J9ak1AzEeaStZwEVQ:-O4J9ak1AzEeaStZwEVR:b-lgjjwl) ([raw file](https://github.com/starkware-libs/sequencer/blob/299153fbd814e0289672ae9672f840989046cc67/crates/mempool/src/mempool.rs#L139)):*
> ```XML
>         // Remove transactions with lower nonce than the account nonce.
>         self.tx_pool.remove_up_to_nonce(sender_address, nonce);
>         if self.tx_queue.get_nonce(sender_address).is_some_and(|queued_nonce| queued_nonce != nonce)
> ```

i think, because it can't be larger? Can it be larger?

If it can, then the comment here should be fixed to reflect that.



_Suggestion:_
```XML
        // Remove transactions with lower nonce than the account nonce.
        self.tx_pool.remove_up_to_nonce(sender_address, nonce);
        if self.tx_queue.get_nonce(sender_address).is_some_and(|queued_nonce| queued_nonce < nonce)
```
___
*[`crates/mempool/src/mempool.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4JC2SM6wc1RHhGJkaq:-O4JC2SM6wc1RHhGJkar:btn53w4) ([raw file](https://github.com/starkware-libs/sequencer/blob/299153fbd814e0289672ae9672f840989046cc67/crates/mempool/src/mempool.rs#L147)):*
> ```XML
> 
>         // Maybe close nonce gap.
>         if self.tx_queue.get_nonce(sender_address).is_none() {
> ```

The answer to this check can be inferred from the previous lines, this adds complexity unnecessarily.

BTW I think this happened in a previous PR as well, I don't remember which, but in general when you add code to a function you should consider the whole function cohesively, sometimes the whole flow if it warrents it.

BTW, In this situation, can we forgo the removal/check entirely and just insert into the queue (if we want to know if something was there or not we can return the old value from the insert)



_Code quote:_
```XML
        if self.tx_queue.get_nonce(sender_address).is_none() {
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/452)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4J9ak1AzEeaStZwEVQ:-O4KI9gbBJmWBPSv4yKW:b-xcs8tm) ([raw file](https://github.com/starkware-libs/sequencer/blob/299153fbd814e0289672ae9672f840989046cc67/crates/mempool/src/mempool.rs#L139)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

i think, because it can't be larger? Can it be larger?

If it can, then the comment here should be fixed to reflect that.
</blockquote></details>

I want to align with the commit block logic, so I'll keep the `!=` comparison, which fits here as well, and remove the comment.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/452)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4Z84_UDN6vFz-HJR8E:-O4Z84_UDN6vFz-HJR8F:blsy622) (no related file):*
Not sure I understand the motivation for this PR.

___
___
*[`crates/mempool/src/mempool.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4Z8AAm69IJgXrFGuFw:-O4Z7zIPBjY4d8qESsKc:b9r4mj7) ([raw file](https://github.com/starkware-libs/sequencer/blob/b6af979b93bac2e6b6e8c87365f51362b401389b/crates/mempool/src/mempool.rs#L136)):*
> ```XML
>         let MempoolInput { tx, account: Account { sender_address, state: AccountState { nonce } } } =
>             input;
> ```

I think it's better to remove from queue (which depends on the account state and is "less stable"  than the pool) first, then from the pool.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/452)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4Z84_UDN6vFz-HJR8E:-O4ZJfXd-nR6wKTJ_ZaZ:b-9zuit3) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure I understand the motivation for this PR.
</blockquote></details>

The `add_tx` function passes the current account nonce to `insert_tx`. The purpose of this PR is to remove the queued transaction if its nonce differs from the current account nonce, ensuring that a valid transaction remains in the queue.

___
___
*[`crates/mempool/src/mempool.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4JC2SM6wc1RHhGJkaq:-O4ZHugTBMzv-HLDgV8K:b-xu7wny) ([raw file](https://github.com/starkware-libs/sequencer/blob/299153fbd814e0289672ae9672f840989046cc67/crates/mempool/src/mempool.rs#L147)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

The answer to this check can be inferred from the previous lines, this adds complexity unnecessarily.

BTW I think this happened in a previous PR as well, I don't remember which, but in general when you add code to a function you should consider the whole function cohesively, sometimes the whole flow if it warrents it.

BTW, In this situation, can we forgo the removal/check entirely and just insert into the queue (if we want to know if something was there or not we can return the old value from the insert)
</blockquote></details>

how can the answer to this check be inferred from the previous lines? the queue could be empty before the check/removal above.
___
*[`crates/mempool/src/mempool.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4Z8AAm69IJgXrFGuFw:-O4ZHlfF9GAfLnS5shr2:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b6af979b93bac2e6b6e8c87365f51362b401389b/crates/mempool/src/mempool.rs#L136)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think it's better to remove from queue (which depends on the account state and is "less stable"  than the pool) first, then from the pool.
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/452)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4Z84_UDN6vFz-HJR8E:-O4ZMyxr3Qrtz31S64GY:b-eb82l5) (no related file):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

The `add_tx` function passes the current account nonce to `insert_tx`. The purpose of this PR is to remove the queued transaction if its nonce differs from the current account nonce, ensuring that a valid transaction remains in the queue.
</blockquote></details>

Sounds like a bug, right? Please add a test that fails without this corretion.

___
___
*[`crates/mempool/src/mempool.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4J9ak1AzEeaStZwEVQ:-O4ZNAn3DN5K7Xiqk9Wu:b-xut6m1) ([raw file](https://github.com/starkware-libs/sequencer/blob/299153fbd814e0289672ae9672f840989046cc67/crates/mempool/src/mempool.rs#L139)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I want to align with the commit block logic, so I'll keep the `!=` comparison, which fits here as well, and remove the comment.
</blockquote></details>

I think it can't be larger thanks to `validate_input`; Ayelet, can you doublecheck?
___
*[`crates/mempool/src/mempool.rs` line 137 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4ZNLr_0E9-c3inkVi-:-O4ZNLr_0E9-c3inkVi0:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/5fe625358d9770aa6e77351d1e9e843c5336e323/crates/mempool/src/mempool.rs#L137)):*
> ```XML
>             input;
> 
>         if self.tx_queue.get_nonce(sender_address).is_some_and(|queued_nonce| queued_nonce != nonce)
> ```





_Suggestion:_
```XML
// Align mempool to given account state.

// First, maybe remove old nonces.
if self.tx_queue.get_nonce(sender_address).is_some_and(|queued_nonce| queued_nonce != nonce)
```
___
*[`crates/mempool/src/mempool.rs` line 143 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4ZNVEa7ziqTTflGCYX:-O4ZNVEa7ziqTTflGCYY:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/5fe625358d9770aa6e77351d1e9e843c5336e323/crates/mempool/src/mempool.rs#L143)):*
> ```XML
>         self.tx_pool.remove_up_to_nonce(sender_address, nonce);
> 
>         self.tx_pool.insert(tx)?;
> ```





_Suggestion:_
```XML
// Then, insert new transaction.
self.tx_pool.insert(tx)?;
```

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/452)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4JC2SM6wc1RHhGJkaq:-O4ZPX-T-6s6QDL3FodQ:bk6jlul) ([raw file](https://github.com/starkware-libs/sequencer/blob/299153fbd814e0289672ae9672f840989046cc67/crates/mempool/src/mempool.rs#L147)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

how can the answer to this check be inferred from the previous lines? the queue could be empty before the check/removal above.
</blockquote></details>

I think I also got confused here, maybe a sign for low code readability.
There might be accounts that weren't in the queue to begin with.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/452)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4Z84_UDN6vFz-HJR8E:-O4ZaGFf4jFVdJe86Bty:b-o3fbx1) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Sounds like a bug, right? Please add a test that fails without this corretion.
</blockquote></details>

added a test. It fails without this PR code. 

___
___
*[`crates/mempool/src/mempool.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4J9ak1AzEeaStZwEVQ:-O4ZbY6yD4XxQCD3s4he:b-vf1v52) ([raw file](https://github.com/starkware-libs/sequencer/blob/299153fbd814e0289672ae9672f840989046cc67/crates/mempool/src/mempool.rs#L139)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think it can't be larger thanks to `validate_input`; Ayelet, can you doublecheck?
</blockquote></details>

I will discuss this with @MohammadNassar1 
added a todo. 
___
*[`crates/mempool/src/mempool.rs` line 137 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4ZNLr_0E9-c3inkVi-:-O4Zakbs8wRxTia8rCwM:b-bcgw0g) ([raw file](https://github.com/starkware-libs/sequencer/blob/5fe625358d9770aa6e77351d1e9e843c5336e323/crates/mempool/src/mempool.rs#L137)):*
> ```XML
>             input;
> 
>         if self.tx_queue.get_nonce(sender_address).is_some_and(|queued_nonce| queued_nonce != nonce)
> ```

I'll add the comments in the next PR since the order is being changed.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/452)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4J9ak1AzEeaStZwEVQ:-O4_9u9iDa_Ss9jNxb1e:br9rihq) ([raw file](https://github.com/starkware-libs/sequencer/blob/299153fbd814e0289672ae9672f840989046cc67/crates/mempool/src/mempool.rs#L139)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I will discuss this with @MohammadNassar1 
added a todo.
</blockquote></details>

changed to a comment.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/452)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 138 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4_FUQMBHr93vTmbAKA:-O4_FUQMBHr93vTmbAKB:b-uxedts) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f3245417aea017ad0c96a5154804f40e54b26a5/crates/mempool/src/mempool.rs#L138)):*
> ```XML
>             input;
> 
>         // Note: != is actually equivalent to > here, as lower nonces are rejected in validation.
> ```

`insert_tx` is only used in `add_tx` now, as the `new` function is removed in #475. I suggest moving this function’s logic directly into `add_tx` to make the code and comment easier to understand. wdyt? @elintul

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/452)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 138 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4_FUQMBHr93vTmbAKA:-O4_LxQ1Cu8cvzz5kkNu:be5160n) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f3245417aea017ad0c96a5154804f40e54b26a5/crates/mempool/src/mempool.rs#L138)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

`insert_tx` is only used in `add_tx` now, as the `new` function is removed in #475. I suggest moving this function’s logic directly into `add_tx` to make the code and comment easier to understand. wdyt? @elintul
</blockquote></details>

will be easier to change after the code share

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/452)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 138 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4_FUQMBHr93vTmbAKA:-O4d54Oc0yHBhvvN-nHv:b8q1hug) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f3245417aea017ad0c96a5154804f40e54b26a5/crates/mempool/src/mempool.rs#L138)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

will be easier to change after the code share
</blockquote></details>

Let's first merge the PRs we have open, and then revisit.
___
*[`crates/mempool/src/mempool_test.rs` line 456 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4d4tP91blmv-5CwTse:-O4d4tP91blmv-5CwTsf:b-xtzk40) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f3245417aea017ad0c96a5154804f40e54b26a5/crates/mempool/src/mempool_test.rs#L456)):*
> ```XML
>     expected_mempool_content.assert_eq_queue_content(&mempool);
> }
> ```

Do we check the case where the account was not in the queue to begin with?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/452)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4JC2SM6wc1RHhGJkaq:-O4dOhehEuC2XJWClb7V:bprgoro) ([raw file](https://github.com/starkware-libs/sequencer/blob/299153fbd814e0289672ae9672f840989046cc67/crates/mempool/src/mempool.rs#L147)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think I also got confused here, maybe a sign for low code readability.
There might be accounts that weren't in the queue to begin with.
</blockquote></details>

Is there anything you would suggest I do?
___
*[`crates/mempool/src/mempool_test.rs` line 456 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4d4tP91blmv-5CwTse:-O4dOb2J6TtSjCQrI0xH:b7phi92) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f3245417aea017ad0c96a5154804f40e54b26a5/crates/mempool/src/mempool_test.rs#L456)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we check the case where the account was not in the queue to begin with?
</blockquote></details>

yes, in `test_add_tx_account_state_fills_hole`

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/452)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4JC2SM6wc1RHhGJkaq:-O4dQPx12WbH965UnHTG:b6s9of3) ([raw file](https://github.com/starkware-libs/sequencer/blob/299153fbd814e0289672ae9672f840989046cc67/crates/mempool/src/mempool.rs#L147)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Is there anything you would suggest I do?
</blockquote></details>

Please revisit a possible refactor after these PRs are merged.
___
*[`crates/mempool/src/mempool_test.rs` line 456 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4d4tP91blmv-5CwTse:-O4dQYs02duqfDsXwNyO:b1dpozq) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f3245417aea017ad0c96a5154804f40e54b26a5/crates/mempool/src/mempool_test.rs#L456)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

yes, in `test_add_tx_account_state_fills_hole`
</blockquote></details>

Thanks. Better to add a line to the code.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/452#-:-O4dQd_49Qk70UjVOSig:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/452)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/452#-O4JC2SM6wc1RHhGJkaq:-O4dSlmLEv69TZjyi1xO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/299153fbd814e0289672ae9672f840989046cc67/crates/mempool/src/mempool.rs#L147)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please revisit a possible refactor after these PRs are merged.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/452)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

**Review by ayeletstarkware — COMMENTED** [review]
> Dismissed @giladchase from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/452)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Pull request merged**
