### PR TITLE
chore(mempool_infra): rename empty server

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #1111
- #1110
- #1109
- #1103
- #1102
- #1101 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1101)

### CODE REVIEW

**Review by lev-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1101)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/consensus_manager/src/communication.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1101#-O81njT9Dz1r_44pXNxK:-O81njTADZsapI0ZsNUF:bbozcfy) ([raw file](https://github.com/starkware-libs/sequencer/blob/f81323e653c25154299790d1fe7c22bfc3ce1e67/crates/consensus_manager/src/communication.rs#L7)):*
> ```XML
> };
> use starknet_mempool_infra::component_definitions::ComponentRequestHandler;
> use starknet_mempool_infra::component_server::WrapperServer;
> ```

Local server is also a wrapper server. So, it's not a good name.



_Code quote:_
```XML
WrapperServer
```

**Review by lev-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1101#-:-O820TtP5ECuVd_Bd9t1:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1101)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#1110](https://github.com/starkware-libs/sequencer/pull/1110)

**Pull request closed without merging**
