### PR TITLE
feat(blockifier): add syscall counting for native syscall handler

### PR DESCRIPTION
**Pull request by rodrigo-pino**

### CODE REVIEW

**Review by meship-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1555)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-OATXVGH49uubLtplgYA:-OATXVGIC9rPDgF9dcAg:b5bekru) ([raw file](https://github.com/starkware-libs/sequencer/blob/ded98cfadbccbaf7eda3dc3d6a3d67bf42246bac/crates/blockifier/src/execution/native/entry_point_execution.rs#L79)):*
> ```XML
>             gas_consumed,
>         },
>         resources: syscall_handler.resources.clone(),
> ```

Why are we no longer using default resources? 



_Code quote:_
```XML
resources: syscall_handler.resources.clone(),
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-OATYj5X042tHOK7lK1-:-OATYj5X042tHOK7lK10:b-9p0btg) ([raw file](https://github.com/starkware-libs/sequencer/blob/ded98cfadbccbaf7eda3dc3d6a3d67bf42246bac/crates/blockifier/src/execution/native/syscall_handler.rs#L68)):*
> ```XML
>         let syscall_count = self.syscall_counter.entry(*selector).or_default();
>         *syscall_count += n
>     }
> ```

Why are we increasing by n and not by 1? Are there cases where we want to increase it with a different number? 



_Code quote:_
```XML
    fn increment_syscall_count_by(&mut self, selector: &SyscallSelector, n: usize) {
        let syscall_count = self.syscall_counter.entry(*selector).or_default();
        *syscall_count += n
    }
```

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1555)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @rodrigo-pino)

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1555)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @rodrigo-pino)

___
*[`a.xadfas` line 0 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-OAqzGOkDql_pGnnfFNI:-OAqzGOl5sRThhDV2u7p:b-y9u91l) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/a.xadfas#L0)):*
What is this file? Can you remove it?

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1555)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @rodrigo-pino)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1555)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1 and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-OAvj4ew3KC1CuvN0kgP:-OAvj4ew3KC1CuvN0kgQ:b-7zi8tj) ([raw file](https://github.com/starkware-libs/sequencer/blob/60e2392722b8f67ae9536726d987f21fd8330338/crates/blockifier/src/execution/native/entry_point_execution.rs#L65)):*
> ```XML
> 
>     // todo(rodrigo): execution resources for native execution are still wip until future
>     // development on both Cairo lang and the Native compiler
> ```

WDYM?



_Code quote:_
```XML
    // todo(rodrigo): execution resources for native execution are still wip until future
    // development on both Cairo lang and the Native compiler
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1555)* status: all files reviewed, 6 unresolved discussions (waiting on @meship-starkware and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-OATXVGH49uubLtplgYA:-OAw3sLp2AabnWV_TT7S:bhfy6cr) ([raw file](https://github.com/starkware-libs/sequencer/blob/ded98cfadbccbaf7eda3dc3d6a3d67bf42246bac/crates/blockifier/src/execution/native/entry_point_execution.rs#L79)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why are we no longer using default resources?
</blockquote></details>

When running cairo native, the only resource that matters is the gas counter. Please revert.
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-OAw4QuO4B1dRd95xkpq:-OAw4QuO4B1dRd95xkpr:b-7zi8tj) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/execution/native/entry_point_execution.rs#L74)):*
> ```XML
>         },
>         // todo(rodrigo): execution resources rely heavily on how the VM work, therefore
>         // the dummy values
> ```

WDYM?



_Code quote:_
```XML
        // todo(rodrigo): execution resources rely heavily on how the VM work, therefore
        // the dummy values
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-OATYj5X042tHOK7lK1-:-OAwBdMUExCeGV5U-1Ih:bmv92f) ([raw file](https://github.com/starkware-libs/sequencer/blob/ded98cfadbccbaf7eda3dc3d6a3d67bf42246bac/crates/blockifier/src/execution/native/syscall_handler.rs#L68)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why are we increasing by n and not by 1? Are there cases where we want to increase it with a different number?
</blockquote></details>

Currently, we need `n` that is potentially greater for one in the keccak syscall. 
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-OAwCaze1EUUMt8CGHhb:-OAwCaze1EUUMt8CGHhc:b-8t17mc) ([raw file](https://github.com/starkware-libs/sequencer/blob/60e2392722b8f67ae9536726d987f21fd8330338/crates/blockifier/src/execution/native/syscall_handler.rs#L110)):*
> ```XML
>         if syscall_selector != SyscallSelector::Keccak {
>             self.increment_syscall_count_by(&syscall_selector, 1);
>         }
> ```

With this change the method can no linger be called `substract_syscall_gas_cost`. Consider renaming it or, alternatively, removing this functionality. 



_Code quote:_
```XML
        // Syscall count for Keccak is done differently
        if syscall_selector != SyscallSelector::Keccak {
            self.increment_syscall_count_by(&syscall_selector, 1);
        }
```

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1555)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @rodrigo-pino)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1555)* status: all files reviewed, 4 unresolved discussions (waiting on @rodrigo-pino)

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1555)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-OATXVGH49uubLtplgYA:-OBKT8bl4-gR-II7Ex6T:bce20r8) ([raw file](https://github.com/starkware-libs/sequencer/blob/ded98cfadbccbaf7eda3dc3d6a3d67bf42246bac/crates/blockifier/src/execution/native/entry_point_execution.rs#L79)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

When running cairo native, the only resource that matters is the gas counter. Please revert.
</blockquote></details>

Done, i've change it default to `ChargedResources`
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-OAvj4ew3KC1CuvN0kgP:-OBKTTAq4MlnXHSezESW:btdbqyi) ([raw file](https://github.com/starkware-libs/sequencer/blob/60e2392722b8f67ae9536726d987f21fd8330338/crates/blockifier/src/execution/native/entry_point_execution.rs#L65)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

No longer relevant
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-OAw4QuO4B1dRd95xkpq:-OBKT4o_1xQYntiz2tn7:b-621oy) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/crates/blockifier/src/execution/native/entry_point_execution.rs#L74)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

I think doesn't show up in the code anymore
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-OATYj5X042tHOK7lK1-:-OBKRH0d0iKTLkKW5i7U:bqi9wzi) ([raw file](https://github.com/starkware-libs/sequencer/blob/ded98cfadbccbaf7eda3dc3d6a3d67bf42246bac/crates/blockifier/src/execution/native/syscall_handler.rs#L68)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Currently, we need `n` that is potentially greater for one in the keccak syscall.
</blockquote></details>

Yes, that's it. Didn't want to add an `increment_syscall_count_by_one`, but if you prefer it that way we can add a specialized function
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-OAwCaze1EUUMt8CGHhb:-OBKR2SO1iP_-YOcatwC:b-4rddvs) ([raw file](https://github.com/starkware-libs/sequencer/blob/60e2392722b8f67ae9536726d987f21fd8330338/crates/blockifier/src/execution/native/syscall_handler.rs#L110)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

With this change the method can no linger be called `substract_syscall_gas_cost`. Consider renaming it or, alternatively, removing this functionality.
</blockquote></details>

Done, tell me what you think!
___
*[`a.xadfas` line  at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-OAqzGOkDql_pGnnfFNI:-OBKPSJY2x6pAZ82TgU-:b-5sbuwo) ([raw file](https://github.com/starkware-libs/sequencer/blob/099970f8bfeb9cdbe1976de06acc0112b4ea2db7/a.xadfas#L)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

What is this file? Can you remove it?
</blockquote></details>

Oooooops! Removed!

**Review by noaov1 — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-:-OBKaQz14YRE1LvvKwIQ:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 100 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-OBKbAjA9W2squXWKdDw:-OBKbAjB7o5oJkcBX6mf:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/139d79dc2118866672721503c781009d22e16ab0/crates/blockifier/src/execution/native/syscall_handler.rs#L100)):*
> ```XML
>     /// handling all gas-related logics and additional metadata such as `SyscallCounter`). The
>     /// difference for native execution is that we need to explicitly call this method at the
>     /// beginning of each syscall.
> ```





_Suggestion:_
```XML
    /// Handles all gas-related logics and additional metadata such as `SyscallCounter`. In native,
    /// we need to explicitly call this method at the
    /// beginning of each syscall.
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 73 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-OBKag0c3m4dAOI8IdH-:-OBKag0c3m4dAOI8IdH0:b-jhoazy) ([raw file](https://github.com/starkware-libs/sequencer/blob/139d79dc2118866672721503c781009d22e16ab0/crates/blockifier/src/execution/native/entry_point_execution.rs#L73)):*
> ```XML
>             gas_consumed,
>         },
>         charged_resources: ChargedResources::default(),
> ```

We charge according to the gas consumed in the native run



_Suggestion:_
```XML
charged_resources: ChargedResources {
            vm_resources: ExecutionResources::default(),
            gas_for_fee: GasAmount(gas_consumed),
        },
,
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1555)* status: all files reviewed, 2 unresolved discussions (waiting on @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-OATYj5X042tHOK7lK1-:-OBKk2dK0TsmrL1P_IkK:bm21hrs) ([raw file](https://github.com/starkware-libs/sequencer/blob/ded98cfadbccbaf7eda3dc3d6a3d67bf42246bac/crates/blockifier/src/execution/native/syscall_handler.rs#L68)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

Yes, that's it. Didn't want to add an `increment_syscall_count_by_one`, but if you prefer it that way we can add a specialized function
</blockquote></details>

No, that's ok. I think it is better this way.

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1555)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 73 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-OBKag0c3m4dAOI8IdH-:-OBKt9ac80LMiT1Ply4W:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/139d79dc2118866672721503c781009d22e16ab0/crates/blockifier/src/execution/native/entry_point_execution.rs#L73)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We charge according to the gas consumed in the native run
</blockquote></details>

Done
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 100 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1555#-OBKbAjA9W2squXWKdDw:-OBKtROI6i7gzrOF0-Iz:bx7xv1r) ([raw file](https://github.com/starkware-libs/sequencer/blob/139d79dc2118866672721503c781009d22e16ab0/crates/blockifier/src/execution/native/syscall_handler.rs#L100)):*
> ```XML
>     /// handling all gas-related logics and additional metadata such as `SyscallCounter`). The
>     /// difference for native execution is that we need to explicitly call this method at the
>     /// beginning of each syscall.
> ```

Done Love the writing tips :)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1555)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1555)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1555)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rodrigo-pino)

**Pull request merged**
