### PR TITLE
refactor(batcher): add input channel size config

### PR DESCRIPTION
**Pull request by Yael-Starkware**
refactor(batcher): add batcher creation func to test

feat(batcher): add input channel size config for validate flow

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2042?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2042** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2042?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1951** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1951?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1996** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1996?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1986** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1986?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1985** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1985?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Yael-Starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2042)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @Yael-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2042#-OBe5y1Z0tcaEgqx8CUO:-OBe5y1Z0tcaEgqx8CUP:b6t00pk) (no related file):*
I think this should be a constant instead of config

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2042)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`config/sequencer/default_config.json` line 142 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2042#-OBe5zSRBDfXn6AAQEA0:-OBe7KMrCtfsGTpdGYXh:b-vt5hpm) ([raw file](https://github.com/starkware-libs/sequencer/blob/372c808e5388bbea5ed6a6d8fa4910700b8d34bb/config/sequencer/default_config.json#L142)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why do we need this config? Can't we use the `tx_chunk_size` from the block builders config?
</blockquote></details>

In that case, every time a chunk is taken from the channel, it will be emptied, and it will take some time to fill it up. Probably the time to fill it up is much shorter than the time to process the chunk by the executor. 
So it makes sense, but maybe we want keep some extra capacity?

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2042)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`config/sequencer/default_config.json` line 142 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2042#-OBe5zSRBDfXn6AAQEA0:-OBeDFMe97zvELFebCD7:bwolvts) ([raw file](https://github.com/starkware-libs/sequencer/blob/372c808e5388bbea5ed6a6d8fa4910700b8d34bb/config/sequencer/default_config.json#L142)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

In that case, every time a chunk is taken from the channel, it will be emptied, and it will take some time to fill it up. Probably the time to fill it up is much shorter than the time to process the chunk by the executor. 
So it makes sense, but maybe we want keep some extra capacity?
</blockquote></details>

Hmm, it's a good question. We should also consider having it as a constant, as Yair suggested.
Do you know why, for example, the outstream_content_buffer_size below needs to be configurable? @yair-starkware

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2042)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`config/sequencer/default_config.json` line 153 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2042#-OBe2wxJ54jNsSkvl7hn:-OBeLGD_DhCGso7BhSwf:bf83zmg) ([raw file](https://github.com/starkware-libs/sequencer/blob/372c808e5388bbea5ed6a6d8fa4910700b8d34bb/config/sequencer/default_config.json#L153)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Forgot to push?

**Comment by yair-starkware** [comment]
*[`config/sequencer/default_config.json` line 142 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2042#-OBe5zSRBDfXn6AAQEA0:-OBexfV42D7FKMVP_Won:b-6sbk9i) ([raw file](https://github.com/starkware-libs/sequencer/blob/372c808e5388bbea5ed6a6d8fa4910700b8d34bb/config/sequencer/default_config.json#L142)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Hmm, it's a good question. We should also consider having it as a constant, as Yair suggested.
Do you know why, for example, the outstream_content_buffer_size below needs to be configurable? @yair-starkware
</blockquote></details>

Thinking about it again, I think the sum input + output buffer size should be derived from the pods memory size.
Maybe @Itay-Tsabary-Starkware should be involved here/

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2042)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @Itay-Tsabary-Starkware)

___
*[`config/sequencer/default_config.json` line 153 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2042#-OBe2wxJ54jNsSkvl7hn:-OBsxN6c-rAYRAKVCtle:b-gv1i0s) ([raw file](https://github.com/starkware-libs/sequencer/blob/372c808e5388bbea5ed6a6d8fa4910700b8d34bb/config/sequencer/default_config.json#L153)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Forgot to push?
</blockquote></details>

seems that way.
now done.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2042)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @Itay-Tsabary-Starkware)

___
*[`config/sequencer/default_config.json` line 142 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2042#-OBe5zSRBDfXn6AAQEA0:-OBsyxD-5gaAUKWanM51:b-9ti9n0) ([raw file](https://github.com/starkware-libs/sequencer/blob/372c808e5388bbea5ed6a6d8fa4910700b8d34bb/config/sequencer/default_config.json#L142)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Thinking about it again, I think the sum input + output buffer size should be derived from the pods memory size.
Maybe @Itay-Tsabary-Starkware should be involved here/
</blockquote></details>

scheduled a meeting tomorrow to discuss.

**Review by alonh5 — APPROVED** [review]
:lgtm:
Unblocking for now. We still need to check if we want this as a separate configuration or if we can infer it from other values (e.g., tx_chunk_size) or have it as a constant.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2042#-:-OBzHRvQ9zE8sIX_VdiP:b-cm439d)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2042#-:-OBzJ81vBeO8ury9qqeb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
