### PR TITLE
chore(deployment): add cdk8s deployment tool for sequencer

### PR DESCRIPTION
**Pull request by idan-starkware**

### CODE REVIEW

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 12 files at r1, 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2250)* status: 1 of 19 files reviewed, 1 unresolved discussion (waiting on @idan-starkware)

___
*[`deployments/sequencer/config/sequencer.py` line 13 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2250#-OCTkk1k0oL4aFPdxX4V:-OCTkk1k0oL4aFPdxX4W:bi0vk84) ([raw file](https://github.com/starkware-libs/sequencer/blob/d29bf837f9520178157e88eaeb24119f32d83f19/deployments/sequencer/config/sequencer.py#L13)):*
> ```Python
> 
> class SequencerDevConfig(Config):
>     def __init__(self, mount_path: str, config_file_path: str = ""):
> ```

never set empty string
never set default value to func sig if its not used 99.9% of the times



_Code quote:_
```Python
 config_file_path: str = ""
```

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2250)* status: 1 of 19 files reviewed, 2 unresolved discussions (waiting on @idan-starkware)

___
*[`deployments/sequencer/config/sequencer.py` line 16 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2250#-OCTkzyu4IJ44qxOxDLx:-OCTkzyu4IJ44qxOxDLy:b-umufob) ([raw file](https://github.com/starkware-libs/sequencer/blob/d29bf837f9520178157e88eaeb24119f32d83f19/deployments/sequencer/config/sequencer.py#L16)):*
> ```Python
>         super().__init__(
>             schema=json.loads(open(os.path.join(CONFIG_DIR, 'default_config.json'), 'r').read()),
>             config=json.loads(open(os.path.join(CONFIG_DIR, 'presets', 'config.json'), 'r').read()) if not config_file_path else json.loads(open(os.path.abspath(config_file_path)).read()),
> ```

func it,
`load_config`



_Code quote:_
```Python
json.loads(open(os.path.join(CONFIG_DIR, 'presets', 'config.json'), 'r').read()) if not config_file_path else json.loads(open(os.path.abspath(config_file_path)).read())
```

**Review by idan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2250)* status: 1 of 19 files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware and @idan-starkware)

___
*[`deployments/sequencer/config/sequencer.py` line 13 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2250#-OCTkk1k0oL4aFPdxX4V:-OCTqucm1fnJRZ3-jNvJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d29bf837f9520178157e88eaeb24119f32d83f19/deployments/sequencer/config/sequencer.py#L13)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

never set empty string
never set default value to func sig if its not used 99.9% of the times
</blockquote></details>

Done.
___
*[`deployments/sequencer/config/sequencer.py` line 16 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2250#-OCTkzyu4IJ44qxOxDLx:-OCTqv0dB-MaO2R0yXsj:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d29bf837f9520178157e88eaeb24119f32d83f19/deployments/sequencer/config/sequencer.py#L16)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

func it,
`load_config`
</blockquote></details>

Done.

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2250#-:-OCXJ5ei3xp8s-gEDmro:bnfp4nl)* status: 1 of 19 files reviewed, all discussions resolved (waiting on @idan-starkware)

**Review by idan-starkware — COMMENTED** [review]
> Reviewed 3 of 12 files at r1, 7 of 8 files at r2, 4 of 6 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2250)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @idan-starkware)

**Review by idan-starkware — COMMENTED** [review]
> Reviewed 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2250)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @idan-starkware)

**Pull request merged**
