### PR TITLE
chore(blockifier): rename fn account_invoke_tx to invoke_tx_with_default_flags

### PR DESCRIPTION
**Pull request by avivg-starkware**

### CODE REVIEW

**Comment by avivg-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2479?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2479** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2479?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2479?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2478** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2478?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2470** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2470?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2437** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2437?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2431** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2431?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2429** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2429?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2428** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2428?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2354](https://github.com/starkware-libs/sequencer/pull/2354) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2354?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2412** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2412?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2377** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2377?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2331** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2331?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2479#-:-ODLgKYp0tuek_SrLVeu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Review by avivg-starkware — COMMENTED** [review]
> Reviewed 10 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2479)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Comment by avivg-starkware** [comment]
### Merge activity

* **Dec 6, 4:37 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2479).

**Pull request merged**
