### PR TITLE
refactor(storage,tests_integration): set chain_info correctly

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2181)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/test_utils.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2181#-OC3yAaS4HwwbisD_2MK:-OC3yAaS4HwwbisD_2ML:budm3gf) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a90b836d15e153935b7207f5b4cb2ae4b0388d7/crates/papyrus_storage/src/test_utils.rs#L77)):*
> ```XML
> }
> 
> // TODO: Make all previous functions work with the builder.
> ```

Do you mean to deprecate `get_test_storage()`?
Also, please use named todos.



_Code quote:_
```XML
// TODO: Make all previous functions work with the builder.
```
___
*[`crates/papyrus_storage/src/test_utils.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2181#-OC3xN8L41K1W9-FjYPe:-OC3xN8M44pQ33ZmPgPt:b-p90sah) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a90b836d15e153935b7207f5b4cb2ae4b0388d7/crates/papyrus_storage/src/test_utils.rs#L99)):*
> ```XML
>     /// Finishes the building and returns [`StorageReader`], [`StorageWriter`] and [`StorageConfig`]
>     /// that were built, and the temporary directory that holds a db for testing purposes. The
>     /// Returned [`StorageConfig`] can be used to open the exact same storage again (same DB
> ```

Please use lowercase.



_Code quote:_
```XML
R
```
___
*[`crates/papyrus_storage/src/test_utils.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2181#-OC3zPwI1lGYWZL4ftSm:-OC3zPwI1lGYWZL4ftSn:b-r770fc) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a90b836d15e153935b7207f5b4cb2ae4b0388d7/crates/papyrus_storage/src/test_utils.rs#L104)):*
> ```XML
>         let (reader, writer) = open_storage(self.config.clone()).unwrap();
>         ((reader, writer), self.config, self.handle)
>     }
> ```

What happens in case of two consencutive `build` invocations?



_Code quote:_
```XML
    pub fn build(self) -> ((StorageReader, StorageWriter), StorageConfig, TempDir) {
        let (reader, writer) = open_storage(self.config.clone()).unwrap();
        ((reader, writer), self.config, self.handle)
    }
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2181)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/papyrus_storage/src/test_utils.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2181#-OC3zPwI1lGYWZL4ftSm:-OC44xBZ8VvpO3h81ndq:b8ipde5) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a90b836d15e153935b7207f5b4cb2ae4b0388d7/crates/papyrus_storage/src/test_utils.rs#L104)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

```
            TestStorageBuilder::default()
                .scope(StorageScope::StateOnly)
                .chain_id(chain_id.clone())
                .build().build()
```

What will happen if you run the above?

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2181)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @Itay-Tsabary-Starkware)

___
*[`crates/papyrus_storage/src/test_utils.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2181#-OC3zPwI1lGYWZL4ftSm:-OC7Tx0J8LInOxXXc3Fp:b-sltn6x) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a90b836d15e153935b7207f5b4cb2ae4b0388d7/crates/papyrus_storage/src/test_utils.rs#L104)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

```
            TestStorageBuilder::default()
                .scope(StorageScope::StateOnly)
                .chain_id(chain_id.clone())
                .build().build()
```

What will happen if you run the above?
</blockquote></details>

`build` consumes the builder instance so it won't compile
See builder pattern: https://rust-unofficial.github.io/patterns/patterns/creational/builder.html

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2181#-:-OC7XMRV83QV476W0jkf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2181)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2181#-OCCoim12z4Z-km7a1D4:-OCCq2S-DSDqN-CJ75Se:ba3dfob) ([raw file](https://github.com/starkware-libs/sequencer/blob/d4e5a34b189452eadd5d02242ce4a9e66a8862f4/crates/starknet_integration_tests/src/state_reader.rs#L65)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why state default value explicitly in a builder?
</blockquote></details>

Removed
___
*[`crates/starknet_integration_tests/src/utils.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2181#-OCCoyNB8ER6YZvFGgFc:-OCCqL_305VK1eZFevnU:bc69j5l) ([raw file](https://github.com/starkware-libs/sequencer/blob/d4e5a34b189452eadd5d02242ce4a9e66a8862f4/crates/starknet_integration_tests/src/utils.rs#L42)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Is this used somewhere else?
Please use const
</blockquote></details>

It affects the tx hashes, added a const

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2181)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2181)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by yair-starkware** [comment]
### Merge activity

* **Nov 21, 4:32 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2181).

**Pull request merged**
