### PR TITLE
test(blockifier): parametrize test_max_fee_exceeds_balance by resource bounds types

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1322)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1322?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1322** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1322?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1321** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1321?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1314** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1314?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1313** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1313?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1312** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1312?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1311** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1311?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1310** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1310?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1309** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1309?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1308** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1308?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1307** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1307?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1306** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1306?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yoavGrs — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1322)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 841 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1322#-OAWkjzG4uqZ7z1pPRA4:-OAWkjzG4uqZ7z1pPRA5:bpyqkl9) ([raw file](https://github.com/starkware-libs/sequencer/blob/b789d5c4d63aeca10d2d65d7b8bb8f9f0736bd5e/crates/blockifier/src/transaction/transactions_test.rs#L841)):*
> ```XML
> }
> 
> fn assert_failure_if_resource_bounds_exceed_balance(
> ```

No `if`



_Suggestion:_
```XML
assert_resource_bounds_exceed_balance_failure
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 881 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1322#-OAWjRzu9m2xKpR9yLxP:-OAWjRzu9m2xKpR9yLxQ:buq1jxx) ([raw file](https://github.com/starkware-libs/sequencer/blob/b789d5c4d63aeca10d2d65d7b8bb8f9f0736bd5e/crates/blockifier/src/transaction/transactions_test.rs#L881)):*
> ```XML
>                     TransactionExecutionError::TransactionPreValidationError(
>                         TransactionPreValidationError::TransactionFeeError(
>                             TransactionFeeError::ResourcesBoundsExceedBalance {
> ```

It is better if this error object contains an `AllResourceBounds` object.
Non blocking.



_Code quote:_
```XML
ResourcesBoundsExceedBalance
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 955 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1322#-OAWm90i14rpu8WTeZ6c:-OAWm90i14rpu8WTeZ6d:b-hbz6or) ([raw file](https://github.com/starkware-libs/sequencer/blob/b789d5c4d63aeca10d2d65d7b8bb8f9f0736bd5e/crates/blockifier/src/transaction/transactions_test.rs#L955)):*
> ```XML
>         &[(account_contract, 1), (test_contract, 1)],
>     );
>     let account_contract_address = account_contract.get_instance_address(0);
> ```

Suggestion.



_Suggestion:_
```XML
sender_address
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 956 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1322#-OAWlmTI0coJnj1Zt5ls:-OAWlmTI0coJnj1Zt5lt:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/b789d5c4d63aeca10d2d65d7b8bb8f9f0736bd5e/crates/blockifier/src/transaction/transactions_test.rs#L956)):*
> ```XML
>     );
>     let account_contract_address = account_contract.get_instance_address(0);
>     let default_args = invoke_tx_args! {
> ```





_Suggestion:_
```XML
default_invoke_args
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 960 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1322#-OAWl8VM53CGvMMURIUh:-OAWl8VM53CGvMMURIUi:b-sh5a2l) ([raw file](https://github.com/starkware-libs/sequencer/blob/b789d5c4d63aeca10d2d65d7b8bb8f9f0736bd5e/crates/blockifier/src/transaction/transactions_test.rs#L960)):*
> ```XML
>         calldata: create_trivial_calldata(test_contract.get_instance_address(0)
>     )};
>     let invalid_max_fee = Fee(BALANCE.0 + 1);
> ```

Move under V1 Invoke.



_Code quote:_
```XML
let invalid_max_fee = Fee(BALANCE.0 + 1);
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1047 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1322#-OAWp_PSBQ9nFaZVCeoZ:-OAWp_PSBQ9nFaZVCeo_:b-b0saz9) ([raw file](https://github.com/starkware-libs/sequencer/blob/b789d5c4d63aeca10d2d65d7b8bb8f9f0736bd5e/crates/blockifier/src/transaction/transactions_test.rs#L1047)):*
> ```XML
>                 base_resource_bounds
>             ));
>             base_resource_bounds.l1_gas.max_amount.0 -= 10;
> ```

Code duplication.
Move te logic into a macro



_Suggestion:_
```XML
            macro_rules! resource_overdraft {
                ($max_amount:expr) => {
                    $max_amount.0 += 10;
                    v3_txs_invalid_bounds_invoke_case!(ValidResourceBounds::AllResources(
                        base_resource_bounds
                    ));
                    v3_txs_invalid_bounds_declare_case!(ValidResourceBounds::AllResources(
                        base_resource_bounds
                    ));
                    $max_amount.0 -= 10;
                };
            }

            resource_overdraft!(base_resource_bounds.l1_gas.max_amount);
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1322)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 841 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1322#-OAWkjzG4uqZ7z1pPRA4:-OAXDBlWAnfS69LJSkvR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b789d5c4d63aeca10d2d65d7b8bb8f9f0736bd5e/crates/blockifier/src/transaction/transactions_test.rs#L841)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

No `if`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 956 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1322#-OAWlmTI0coJnj1Zt5ls:-OAXDY8pDeuAyn187JM_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b789d5c4d63aeca10d2d65d7b8bb8f9f0736bd5e/crates/blockifier/src/transaction/transactions_test.rs#L956)):*
> ```XML
>     );
>     let account_contract_address = account_contract.get_instance_address(0);
>     let default_args = invoke_tx_args! {
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 960 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1322#-OAWl8VM53CGvMMURIUh:-OAXBsD4EaMcIuhJD8wP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b789d5c4d63aeca10d2d65d7b8bb8f9f0736bd5e/crates/blockifier/src/transaction/transactions_test.rs#L960)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Move under V1 Invoke.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1047 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1322#-OAWp_PSBQ9nFaZVCeoZ:-OAXCqWp2sIHxBu6O6Sg:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b789d5c4d63aeca10d2d65d7b8bb8f9f0736bd5e/crates/blockifier/src/transaction/transactions_test.rs#L1047)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Code duplication.
Move te logic into a macro
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1322)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1322#-OAXFAoQ01GAxt9cOQPT:-OAXFAoQ01GAxt9cOQPU:b-k6om58) (no related file):*
[py side pr](https://reviewable.io/reviews/starkware-industries/starkware/36148) (change in error formatting, need to check nothing breaks)

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1322)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 904 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1322#-OAXbWUUBU1t3eZ40GcM:-OAXlfJCDS3HYAubbJWz:b-12g02j) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3543e21d73f073c725ecf16484c59c4952f1a55/crates/blockifier/src/transaction/transactions_test.rs#L904)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Compare `AllResourceBounds` objects
</blockquote></details>

yes!! much better

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1322)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1322#-OAXFAoQ01GAxt9cOQPT:-OAXn-Yo2AE-vgG3T2bb:b-m6tflo) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[py side pr](https://reviewable.io/reviews/starkware-industries/starkware/36148) (change in error formatting, need to check nothing breaks)
</blockquote></details>

passes

___

**Review by yoavGrs — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1322)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
