### PR TITLE
feat(blockifier): charge for inner events by VC check

### PR DESCRIPTION
**Pull request by dorimedini-starkware**

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2123?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2123** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2123?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2123?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2122** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2122?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2121** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2121?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2123)* status: 0 of 9 files reviewed, all discussions resolved

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2123#-OBybPgz-zDrC7F_qoSS:-OBybPgz-zDrC7F_qoST:b-2y4zyb) (no related file):*
[py side](https://reviewable.io/reviews/starkware-industries/starkware/36276)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2123)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/resources/versioned_constants_0_13_0.json` line 11 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2123#-OC3W-xxC7rU-m7i3Bnn:-OC3W-xxC7rU-m7i3Bno:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/91fc715394932c003faf99d3e8362f3bb1e0f04c/crates/blockifier/resources/versioned_constants_0_13_0.json#L11)):*
> ```JSON
>     "disable_cairo0_redeclaration": false,
>     "enable_stateful_compression": false,
>     "ignore_inner_events_resources": false,
> ```





_Suggestion:_
```JSON
"ignore_inner_event_resources"
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2123#-:-OC3WBT78a-6ioLwUReh:bnfp4nl)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 8 of 9 files at r3, 8 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2123)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
