### PR TITLE
feat: add configuration for idle timeout and max idle connections

### PR DESCRIPTION
**Pull request by nadin-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1121)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1121)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1121#-O87HYm71kKOrwYiYAql:-O87HYm88wLTxcbuFbyA:b-cghliz) ([raw file](https://github.com/starkware-libs/sequencer/blob/f1db2b7024bb88a045362b34773f3131b5b4c1dc/crates/mempool_infra/src/component_client/remote_component_client.rs#L103)):*
> ```XML
>         let client =
>             Client::builder().http2_only(true).pool_max_idle_per_host(usize::MAX).build_http();
>         Self { uri, client, communication_config, _req: PhantomData, _res: PhantomData }
> ```

Please use the config values here.



_Code quote:_
```XML
        // TODO(Tsabary): Add a configuration for the maximum number of idle connections.
        // TODO(Tsabary): Add a configuration for "keep-alive" time of idle connections.
        let client =
            Client::builder().http2_only(true).pool_max_idle_per_host(usize::MAX).build_http();
        Self { uri, client, communication_config, _req: PhantomData, _res: PhantomData }
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1121)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1121#-O87HYm71kKOrwYiYAql:-O8Qb5P02o1W-tiy1YaD:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f1db2b7024bb88a045362b34773f3131b5b4c1dc/crates/mempool_infra/src/component_client/remote_component_client.rs#L103)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please use the config values here.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1121)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/mempool_infra/src/tests/remote_component_client_server_test.rs` line 166 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1121#-O8VWpa0Dbp_qBWR6i6W:-O8VWpa0Dbp_qBWR6i6X:b-dowg9g) ([raw file](https://github.com/starkware-libs/sequencer/blob/9cc7c7701638d7d58efe7b8d7e27cbd99c4d97be/crates/mempool_infra/src/tests/remote_component_client_server_test.rs#L166)):*
> ```XML
>         retries: MAX_RETRIES,
>         idle_connections: MAX_IDLE_CONNECTION,
>         idle_timeout: IDLE_TIMEOUT,
> ```

Please instantiate the default values using the `..Default::default()` syntax, see here an example: https://stackoverflow.com/a/19653453

(there are also various examples in our code base)



_Code quote:_
```XML
        retries: MAX_RETRIES,
        idle_connections: MAX_IDLE_CONNECTION,
        idle_timeout: IDLE_TIMEOUT,
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1121)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/tests/remote_component_client_server_test.rs` line 166 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1121#-O8VWpa0Dbp_qBWR6i6W:-O8Wqsss3UX83PTCqWzW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9cc7c7701638d7d58efe7b8d7e27cbd99c4d97be/crates/mempool_infra/src/tests/remote_component_client_server_test.rs#L166)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please instantiate the default values using the `..Default::default()` syntax, see here an example: https://stackoverflow.com/a/19653453

(there are also various examples in our code base)
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1121#-:-O8WrjbN1ry9YfNGKbNG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Pull request merged**
