### PR TITLE
chore(ci): reduce jobs to reduce API / bootstrap load

### PR DESCRIPTION
**Pull request by alon-dotan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/402)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/402)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @nadin-Starkware)

___
*[`.github/actions/install_rust/action.yml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/402#-O5STJla42eW9FbCb4wE:-O5STJla42eW9FbCb4wF:b-jfwgkc) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e32da1fe0849bf649e0e0c38e15ece6b72d7256/.github/actions/install_rust/action.yml#L12)):*
> ```YAML
>     required: false
>     type: string
>     default: stable
> ```

no:
we used a text file on purpose: for merges
main-v0.13.2 rust version should be decoupled from the one on main.
when merging mainX -> mainY, the merge script will checkout the `rust_version.txt` file to make sure we don't change the toolchain on the target branch.

why would you need this as an input?



_Code quote:_
```YAML
default: stable
```

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/402)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @nadin-Starkware)

___
*[`.github/actions/install_rust/action.yml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/402#-O5STJla42eW9FbCb4wE:-O5SWtzfCMmyfZZhe-vc:b-358kr2) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e32da1fe0849bf649e0e0c38e15ece6b72d7256/.github/actions/install_rust/action.yml#L12)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no:
we used a text file on purpose: for merges
main-v0.13.2 rust version should be decoupled from the one on main.
when merging mainX -> mainY, the merge script will checkout the `rust_version.txt` file to make sure we don't change the toolchain on the target branch.

why would you need this as an input?
</blockquote></details>

This is the right way to use actions....
If something is changeable it's via inputs... I will try to set the default value of the param the content of the file

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/402)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @nadin-Starkware)

___
*[`.github/actions/install_rust/action.yml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/402#-O5STJla42eW9FbCb4wE:-O5SZeXd6u7G3JM69nJ9:bxw4g9c) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e32da1fe0849bf649e0e0c38e15ece6b72d7256/.github/actions/install_rust/action.yml#L12)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why should it be changeable?
it should only depend on the release branch, no?
</blockquote></details>

No, its a reusable action... so any one can use it and decide which params to use

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/402)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @nadin-Starkware)

___
*[`.github/actions/install_rust/action.yml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/402#-O5STJla42eW9FbCb4wE:-O5S_9O-8T8oIz7RPsNU:b-trpjuv) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e32da1fe0849bf649e0e0c38e15ece6b72d7256/.github/actions/install_rust/action.yml#L12)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

No, its a reusable action... so any one can use it and decide which params to use
</blockquote></details>

this action is intended to unify the CI workflows to use the same toolchain though...
or am i missing the point?
anyway if you can get the default from the txt file (or think of another way to protect from forward-merges changing the toolchain), I'll unblock

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/402)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @nadin-Starkware)

___
*[`.github/actions/install_rust/action.yml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/402#-O5STJla42eW9FbCb4wE:-O5S_ybh2AlntKdPnKlZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e32da1fe0849bf649e0e0c38e15ece6b72d7256/.github/actions/install_rust/action.yml#L12)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this action is intended to unify the CI workflows to use the same toolchain though...
or am i missing the point?
anyway if you can get the default from the txt file (or think of another way to protect from forward-merges changing the toolchain), I'll unblock
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/402#-:-O5SbikT-zV-jJ3MgS3V:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Pull request merged**
