### PR TITLE
refactor(consensus): add a test wrapper to avoid boilerplate with response events

### PR DESCRIPTION
**Pull request by matan-starkware**
Kept the assertions as is since it is nice for errors to show the exact line in the test.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/347)

### CODE REVIEW

**Comment by matan-starkware** [comment]
* **#347** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/347?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/347#-:-O3gzv9m-VOOlHBcqSQ2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/347)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware, @DvirYo-starkware, and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/347#-O3lT0fL9aASHgn_yL87:-O3lT0fL9aASHgn_yL88:b779h3c) ([raw file](https://github.com/starkware-libs/sequencer/blob/a693b69b09501954942812d87d81fb1e8a9a3178/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L23)):*
> ```XML
>     state_machine: StateMachine,
>     leader_fn: LeaderFn,
>     pub events: VecDeque<StateMachineEvent>,
> ```

make this private and add func to the wrapper to access `next_event`

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/347)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware, @DvirYo-starkware, and @eitanm-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/347#-O3lT0fL9aASHgn_yL87:-O3lUer66Iaik0Ys4WKN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a693b69b09501954942812d87d81fb1e8a9a3178/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L23)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

make this private and add func to the wrapper to access `next_event`
</blockquote></details>

Done.

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/347)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @asmaastarkware, @DvirYo-starkware, and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/347#-O3lUr-J6X73EjSFxSiH:-O3lUr-J6X73EjSFxSiI:bdtkdg5) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5885956006d66bcb4007840b10bd1b9fb616b7a/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L76)):*
> ```XML
>         assert_eq!(wrapper.next_event().unwrap(), StateMachineEvent::Proposal(BLOCK_HASH, ROUND));
>     } else {
>         assert!(wrapper.events.is_empty());
> ```

this is private. access by checking next_event is none.
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/347#-O3lUt0q2GHie4bFzvPj:-O3lUt0q2GHie4bFzvPk:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5885956006d66bcb4007840b10bd1b9fb616b7a/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L80)):*
> ```XML
>     }
>     assert_eq!(wrapper.next_event().unwrap(), StateMachineEvent::Prevote(BLOCK_HASH, ROUND));
>     assert!(wrapper.events.is_empty());
> ```

same
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/347#-O3lUuKJ3NMQWj96ATB2:-O3lUuKJ3NMQWj96ATB3:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5885956006d66bcb4007840b10bd1b9fb616b7a/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L83)):*
> ```XML
> 
>     wrapper.send_prevote(BLOCK_HASH, ROUND);
>     assert!(wrapper.events.is_empty());
> ```

same
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/347#-O3lUvtjEkWnCHFv3Ipw:-O3lUvtjEkWnCHFv3Ipx:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5885956006d66bcb4007840b10bd1b9fb616b7a/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L87)):*
> ```XML
>     wrapper.send_prevote(BLOCK_HASH, ROUND);
>     assert_eq!(wrapper.next_event().unwrap(), StateMachineEvent::Precommit(BLOCK_HASH, ROUND));
>     assert!(wrapper.events.is_empty());
> ```

same
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/347#-O3lUvBi5tau6cTWpUET:-O3lUvBi5tau6cTWpUEU:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5885956006d66bcb4007840b10bd1b9fb616b7a/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L90)):*
> ```XML
> 
>     wrapper.send_precommit(BLOCK_HASH, ROUND);
>     assert!(wrapper.events.is_empty());
> ```

same
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/347#-O3lUxHM-sp6vH8f6WUo:-O3lUxHM-sp6vH8f6WUp:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5885956006d66bcb4007840b10bd1b9fb616b7a/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L97)):*
> ```XML
>         StateMachineEvent::Decision(BLOCK_HASH.unwrap(), ROUND)
>     );
>     assert!(wrapper.events.is_empty());
> ```

same
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/347#-O3lUyeAB2qrk-e8Uc3a:-O3lUyeAB2qrk-e8Uc3b:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5885956006d66bcb4007840b10bd1b9fb616b7a/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L105)):*
> ```XML
> 
>     wrapper.start();
>     assert!(wrapper.events.is_empty());
> ```

same
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/347#-O3lUzoT5FEviObl1V5Z:-O3lUzoT5FEviObl1V5_:b-xe26ux) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5885956006d66bcb4007840b10bd1b9fb616b7a/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L114)):*
> ```XML
>     wrapper.send_precommit(BLOCK_HASH, ROUND);
>     wrapper.send_precommit(BLOCK_HASH, ROUND);
>     assert!(wrapper.events.is_empty());
> ```

same.. there is more below as well

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/347)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @asmaastarkware, @DvirYo-starkware, and @eitanm-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/347#-O3lUr-J6X73EjSFxSiH:-O3lVKWp-_f1TLTHAI-H:b4z0yi1) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5885956006d66bcb4007840b10bd1b9fb616b7a/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L76)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

this is private. access by checking next_event is none.
</blockquote></details>

Interesting that this passes tests. I think rust allows accessing private fields within the same module (at least from tests).
___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/347#-O3lUt0q2GHie4bFzvPj:-O3lVqqnD4n6_bgreiuS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5885956006d66bcb4007840b10bd1b9fb616b7a/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L80)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/347#-:-O3lWZIR0JvVe-0FUO3Y:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @asmaastarkware, @DvirYo-starkware, and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/347#-O3lUr-J6X73EjSFxSiH:-O3lVvqM9aFLKeBgRaE3:b-bdpuix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d5885956006d66bcb4007840b10bd1b9fb616b7a/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L76)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Interesting that this passes tests. I think rust allows accessing private fields within the same module (at least from tests).
</blockquote></details>

yeah - i think your right . resolving for now, your choice if you want to change. in the event that you move the struct to a utils it will need to be fixed.

**Review by matan-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/347)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware and @DvirYo-starkware)

**Review by asmaastarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/347)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Comment by matan-starkware** [comment]
### Merge activity

* **Aug 8, 6:37 AM EDT**: @matan-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/347).

**Pull request merged**
