### PR TITLE
feat(blockifier): limit characters in cairo1 revert trace

### PR DESCRIPTION
**Pull request by dorimedini-starkware**

### CODE REVIEW

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1468)

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1468?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1469** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1469?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1468** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1468?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1461** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1461?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1460** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1460?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1459** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1459?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1458** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1458?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1457** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1457?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1468)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1468)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 205 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1468#-O9oQbpxD3I-D8brrMsW:-O9oQbpy4PUy9uD-PucR:b67dolw) ([raw file](https://github.com/starkware-libs/sequencer/blob/61fb90c7f9a90cbcf0563cdd108ed9b1d35e93f0/crates/blockifier/src/execution/stack_trace.rs#L205)):*
> ```XML
>                 .iter()
>                 .map(|frame| frame.to_string())
>                 .chain([format_panic_data(&self.last_retdata.0)])
> ```

Isn't it important to include this in the message?

you probably want something like:
Error in contract (contract address: {:#064x}, class hash: {}, selector: {:#064x}):
Error in contract (contract address: {:#064x}, class hash: {}, selector: {:#064x}):
...
{inner_most_error}



_Code quote:_
```XML
format_panic_data(&self.last_retdata.0)
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1468)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 205 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1468#-O9oQbpxD3I-D8brrMsW:-O9oa5al3ZDb7afUIQPc:bzbehlo) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2c7dc7533bf4e62dc20d9e0208ca05279cf2372/crates/blockifier/src/execution/stack_trace.rs#L205)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Isn't it important to include this in the message?

you probably want something like:
Error in contract (contract address: {:#064x}, class hash: {}, selector: {:#064x}):
Error in contract (contract address: {:#064x}, class hash: {}, selector: {:#064x}):
...
{inner_most_error}
</blockquote></details>

this is getting a bit ugly... both the stack and the failure reason can hit this limit, we may need to truncate them both.
when would we realistically have a trace longer than 15K chars?
anyway, modified, LMK what you think

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1468)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @ilyalesokhin-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 278 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1468#-O9t3wZV-htTSHcSSZyM:-O9t3wZV-htTSHcSSZyN:b-u4pxu6) ([raw file](https://github.com/starkware-libs/sequencer/blob/054bd31eca8d2e8f0d3b18b04f40d0263943886a/crates/blockifier/src/execution/stack_trace.rs#L278)):*
> ```XML
>             .chars()
>             .take(TRACE_LENGTH_CAP)
>             .collect::<String>()
> ```

I really don't like the fact that we need this logic to support an edge-case character limitation...
a frame is 264 characters, so 56 frames fit in the cap bound, not including the innermost retdata which should be short (unless there are use cases for many felts in the failure reason?)...
@ilyalesokhin-starkware if it's worth the extra code, do you have any ideas for improvements / helpful assumptions that will simplify the logic?



_Code quote:_
```XML
        // Total string length is limited by TRACE_LENGTH_CAP.

        // Prioritize the failure reason felts over the frames.
        // If the failure reason is too long to include a minimal frame trace, display only the
        // failure reason (truncated if necessary).
        let failure_reason = format_panic_data(&self.last_retdata.0);
        if failure_reason.len() >= TRACE_LENGTH_CAP - *MIN_CAIRO1_FRAMES_STACK_LENGTH {
            let output = if failure_reason.len() <= TRACE_LENGTH_CAP {
                failure_reason
            } else {
                failure_reason
                    .chars()
                    .take(TRACE_LENGTH_CAP - Self::TRUNCATION_SEPARATOR.len())
                    .collect::<String>()
                    + &format!("{}", Self::TRUNCATION_SEPARATOR)
            };
            return write!(f, "{}", output);
        }

        let untruncated_string = self
            .stack
            .iter()
            .map(|frame| frame.to_string())
            .chain([failure_reason.clone()])
            .join("\n");
        if untruncated_string.len() <= TRACE_LENGTH_CAP {
            return write!(f, "{}", untruncated_string);
        }

        // If the number of frames is too large, drop frames above the last frame (two frames are
        // not too many, as checked above with MIN_CAIRO1_FRAMES_STACK_LENGTH).
        let n_frames_to_drop = (untruncated_string.len() - TRACE_LENGTH_CAP
            + Self::TRUNCATION_SEPARATOR.len())
        .div_ceil(*MIN_CAIRO1_FRAME_LENGTH);

        // Expect the number of frames to be at least the number of frames to drop + 2. If not,
        // fall back to the failure reason.
        if self.stack.len() < n_frames_to_drop + 2 {
            return write!(f, "{}", failure_reason);
        }

        write!(
            f,
            "{}",
            self.stack[..self.stack.len() - n_frames_to_drop - 1]
            .iter()
            .map(|frame| frame.to_string())
            .chain([
                String::from(Self::TRUNCATION_SEPARATOR),
                self.stack
                    .last()
                    .expect("Stack has at least two frames at this point.")
                    .to_string(),
                failure_reason,
            ])
            .join("\n")
            // Truncate again as a failsafe.
            .chars()
            .take(TRACE_LENGTH_CAP)
            .collect::<String>()
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/stack_trace.rs` line 278 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1468#-O9t3wZV-htTSHcSSZyM:-OABmciv0tZmMJlHAzal:b-n1cavu) ([raw file](https://github.com/starkware-libs/sequencer/blob/054bd31eca8d2e8f0d3b18b04f40d0263943886a/crates/blockifier/src/execution/stack_trace.rs#L278)):*
> ```
>  .expect("Stack has at least two frames at this point.")
> ```

I'd rather not use expect her.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/stack_trace.rs` line 205 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1468#-O9oQbpxD3I-D8brrMsW:-OABmvw60bZCetadDe4d:b9nqcft) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2c7dc7533bf4e62dc20d9e0208ca05279cf2372/crates/blockifier/src/execution/stack_trace.rs#L205)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is getting a bit ugly... both the stack and the failure reason can hit this limit, we may need to truncate them both.
when would we realistically have a trace longer than 15K chars?
anyway, modified, LMK what you think
</blockquote></details>

I guess I didn't think it was going to be that complicated.

but if you already wrote it lets keep it.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1468)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1468)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/stack_trace.rs` line 278 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1468#-O9t3wZV-htTSHcSSZyM:-OAC8ZMQ-dgFjYIAmFfI:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/054bd31eca8d2e8f0d3b18b04f40d0263943886a/crates/blockifier/src/execution/stack_trace.rs#L278)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

> ```
>  .expect("Stack has at least two frames at this point.")
> ```

I'd rather not use expect her.
</blockquote></details>

done

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 851 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1468#-OADdpHfAEKPMwNa-azA:-OADdpHfAEKPMwNa-azB:b-sgxp94) ([raw file](https://github.com/starkware-libs/sequencer/blob/c0953acad2fe5534d83009092f2c9c8acf1284bc/crates/blockifier/src/execution/stack_trace_test.rs#L851)):*
> ```XML
>     assert!(
>         format!("{}", extract_trailing_cairo1_revert_trace(&next_call_info)).len()
>             <= TRACE_LENGTH_CAP
> ```

Is putting the actual string here bad?


as it is written the length is the only thing being tested.



_Code quote:_
```XML
        format!("{}", extract_trailing_cairo1_revert_trace(&next_call_info)).len()
            <= TRACE_LENGTH_CAP
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1468)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 851 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1468#-OADdpHfAEKPMwNa-azA:-OAEb6D_4s0Wuf780bVf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c0953acad2fe5534d83009092f2c9c8acf1284bc/crates/blockifier/src/execution/stack_trace_test.rs#L851)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Is putting the actual string here bad?


as it is written the length is the only thing being tested.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1468#-:-OAGvWpc6zwzYBj12SD2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
