### PR TITLE
refactor(consensus): change proposer function signature

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/533)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/533)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/533#-O4jXC3t912kf1bs-C5D:-O4jXC3u1l0gdIbrbNLk:b-vo4h6j) ([raw file](https://github.com/starkware-libs/sequencer/blob/3858409e44be5f246c4273c92ee0934de035fc2b/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L59)):*
> ```XML
>     ) -> Result<Option<Decision<BlockT>>, ConsensusError> {
>         info!("Starting consensus with validators {:?}", self.validators);
>         let leader_fn = |_round: Round| -> ValidatorId { context.proposer(self.height, 0) };
> ```

Why are you not passing the round? It is the state machine's responsibility to send `0` as needed. 

Also, everywhere else, you do similar things, where you ignore the closures input round and capture some other round. Why? Remember, the state machine can advance round during handling of an event.



_Code quote:_
```XML
0
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/533)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/533#-O4jXC3t912kf1bs-C5D:-O4jZa4-DXoU8WqRsM0m:b-3s4d61) ([raw file](https://github.com/starkware-libs/sequencer/blob/3858409e44be5f246c4273c92ee0934de035fc2b/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L59)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why are you not passing the round? It is the state machine's responsibility to send `0` as needed. 

Also, everywhere else, you do similar things, where you ignore the closures input round and capture some other round. Why? Remember, the state machine can advance round during handling of an event.
</blockquote></details>

oops, my bad
fixed

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/533)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/533)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
