### PR TITLE
fix(batcher): check that retrospective_block_hash value is not none

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
* **#2199** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2199?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2199?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by dorimedini-starkware — COMMENTED** [review]
whoops
my bad
my [ci comment updating experiments](https://reviewable.io/reviews/starkware-libs/sequencer/2054) commented on the wrong PR (see `Create comment` phase [here](https://github.com/starkware-libs/sequencer/actions/runs/11935966537/job/33268512598))... wonder why

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2199#-:-OC94oqo8Dq4uR3rk0X1:b-l374ld)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @alonh5 and @yair-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
I am only referring to the `Artifacts upload workflows:` comment above mine
it shouldn't be here, it should be on my PR, but the PR number I injected was 2199 by mistake (probably latest PR over `main` was taken for some reason)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2199#-:-OC97WTjEbXqCamPg4z2:bxe8fr9)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @alonh5 and @yair-starkware)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2199)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/starknet_batcher/src/proposal_manager.rs` line 202 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2199#-OC99HEf88zaT_Ewpi-y:-OC99HEf88zaT_Ewpi-z:b-2yp3od) ([raw file](https://github.com/starkware-libs/sequencer/blob/88271a39fc20fcdbf9b6a58290d97a181726e3fd/crates/starknet_batcher/src/proposal_manager.rs#L202)):*
> ```XML
>         tx_provider: ProposeTransactionProvider,
>     ) -> Result<(), GenerateProposalError> {
>         self.set_active_proposal(proposal_id, retrospective_block_hash).await?;
> ```

Can you open this PR over @dafnamatsry's [PR](https://reviewable.io/reviews/starkware-libs/sequencer/2192)?
It will make more sense anyway to check it in the batcher and not have to pass it as an arg to this unrelated function.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2199)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/starknet_batcher/src/proposal_manager.rs` line 202 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2199#-OC99HEf88zaT_Ewpi-y:-OCD7w_h7B0DSWyvd6ts:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a71a281b7096311e032ee60dc74c32f61b361a5/crates/starknet_batcher/src/proposal_manager.rs#L202)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you open this PR over @dafnamatsry's [PR](https://reviewable.io/reviews/starkware-libs/sequencer/2192)?
It will make more sense anyway to check it in the batcher and not have to pass it as an arg to this unrelated function.
</blockquote></details>

Done.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2199)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/starknet_batcher/src/proposal_manager.rs` line 202 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2199#-OC99HEf88zaT_Ewpi-y:-OCD8BV0CSL-axEWXWva:b-ps4cco) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a71a281b7096311e032ee60dc74c32f61b361a5/crates/starknet_batcher/src/proposal_manager.rs#L202)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

fully agree btw.

**Review by Yael-Starkware — COMMENTED** [review]
actually, to avoid this , I added her code to my stack and rebased on top of it.  It was not a great idea (CI fails). Anyway I'll wait for her to merge and then it'll be alright.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2199#-:-OCDAY3KB0eRDCewZ5ey:bypqod2)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Review by alonh5 — APPROVED** [review]
Cool

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2199#-:-OCDPOmP6Jn4SMVnA2dQ:bb6u032)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2199)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 126 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2199#-OCD7VDt3xfk1GktjoUw:-OCDgSOq1NUXmR1w6Nfx:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa5500cd40b4b870793f4511e29eb3a512db7416/crates/starknet_batcher/src/batcher.rs#L126)):*
> ```XML
>     ) -> BatcherResult<()> {
>         let active_height = self.active_height.ok_or(BatcherError::NoActiveHeight)?;
>         check_block_input(active_height, propose_block_input.retrospective_block_hash)?;
> ```

done

**Review by alonh5 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2199)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
