### PR TITLE
refactor(helm): update config_file path add service yaml files

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/299)

### CODE REVIEW

**Review by idan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/299)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @asmaastarkware)

___
*[`deployments/papyrus/helm/values.yaml` line 76 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/299#-O3XLx6UC9MEfdy7POFk:-O3XLx6UC9MEfdy7POFl:b-lvn959) ([raw file](https://github.com/starkware-libs/sequencer/blob/52a03948605c911d0384025131709d5fcd6b11a4/deployments/papyrus/helm/values.yaml#L76)):*
> ```YAML
>   ## Optionally specify extra environment variables to add to papyrus container
>   env:
>     []
> ```

The brackets should be same line with env. 
env: []
___
*[`deployments/papyrus/helm/values.yaml` line 80 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/299#-O3XM5KJCYWaveKbWZRM:-O3XM5KJCYWaveKbWZRN:b2xvy8s) ([raw file](https://github.com/starkware-libs/sequencer/blob/52a03948605c911d0384025131709d5fcd6b11a4/deployments/papyrus/helm/values.yaml#L80)):*
> ```YAML
>     #   value: BAR
>   extraArgs:
>     {} # Optional additional deployment args
> ```

Same here, extraArgs: {}

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/299)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @idan-starkware)

___
*[`deployments/papyrus/helm/values.yaml` line 76 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/299#-O3XLx6UC9MEfdy7POFk:-O3XTQRM0aubi6QfG6QF:bu6kfds) ([raw file](https://github.com/starkware-libs/sequencer/blob/52a03948605c911d0384025131709d5fcd6b11a4/deployments/papyrus/helm/values.yaml#L76)):*
<details><summary><i>Previously, idan-starkware (Idan Shamam) wrote…</i></summary><blockquote>

The brackets should be same line with env. 
env: []
</blockquote></details>

Done. rustfmt automatically reformats the file when saving :)
___
*[`deployments/papyrus/helm/values.yaml` line 80 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/299#-O3XM5KJCYWaveKbWZRM:-O3XTV44D4BY3mqMU7K7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/52a03948605c911d0384025131709d5fcd6b11a4/deployments/papyrus/helm/values.yaml#L80)):*
<details><summary><i>Previously, idan-starkware (Idan Shamam) wrote…</i></summary><blockquote>

Same here, extraArgs: {}
</blockquote></details>

Done.

**Review by idan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/299#-:-O3XlHFKDWAappjyjKWf:bnfp4nl)* status: 0 of 5 files reviewed, 2 unresolved discussions

**Review by idan-starkware — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/299)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
