### PR TITLE
chore: fix versioned constants

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/853)

### CODE REVIEW

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/853#-:-O73pOja0x_SqNLmNe7J:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/853)* status: 0 of 74 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`-- commits` line 69 at r18](https://reviewable.io/reviews/starkware-libs/sequencer/853#-O74RLV4-1e1wRkKGLYJ):*
Rebase?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/853)* status: 0 of 74 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`-- commits` line 69 at r18](https://reviewable.io/reviews/starkware-libs/sequencer/853#-O74RLV4-1e1wRkKGLYJ):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Rebase?
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/853)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 496 at r19](https://reviewable.io/reviews/starkware-libs/sequencer/853#-O74xPCVEyJGtfgFgs6g:-O74xPCVEyJGtfgFgs6h:b-uufstt) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbf8d83d71534625eb18d709b1cdbd7979ea2b4f/crates/blockifier/src/transaction/execution_flavors_test.rs#L496)):*
> ```XML
>     // If `charge_fee` is true, execution is limited by sender bounds, so less resources will be
>     // used. Otherwise, execution is limited by block bounds, so more resources will be used.
>     let (limited_gas_used, limited_fee) = gas_and_fee(7752, validate, &fee_type);
> ```

this passes for me. please apply the change and delete the `if true` above



_Suggestion:_
```XML
    let (gas_bound, fee_bound) = gas_and_fee(6107, validate, &fee_type);
    // If `charge_fee` is true, execution is limited by sender bounds, so less resources will be
    // used. Otherwise, execution is limited by block bounds, so more resources will be used.
    let (limited_gas_used, limited_fee) = gas_and_fee(7759, validate, &fee_type);
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/853)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 427 at r19](https://reviewable.io/reviews/starkware-libs/sequencer/853#-O74dUq07As-eTIAtKI5:-O74x_ML6tr_USgYSgnx:biwe5di) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbf8d83d71534625eb18d709b1cdbd7979ea2b4f/crates/blockifier/src/transaction/execution_flavors_test.rs#L427)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@dorimedini-starkware
</blockquote></details>

blocking, see below

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/853)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 496 at r19](https://reviewable.io/reviews/starkware-libs/sequencer/853#-O74xPCVEyJGtfgFgs6g:-O77oQuo8LVJbLNneZ63:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbf8d83d71534625eb18d709b1cdbd7979ea2b4f/crates/blockifier/src/transaction/execution_flavors_test.rs#L496)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this passes for me. please apply the change and delete the `if true` above
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/853)* status: 65 of 74 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 427 at r19](https://reviewable.io/reviews/starkware-libs/sequencer/853#-O74dUq07As-eTIAtKI5:-O77oTsD0R55gSkLZDQ_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbf8d83d71534625eb18d709b1cdbd7979ea2b4f/crates/blockifier/src/transaction/execution_flavors_test.rs#L427)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

blocking, see below
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 9 of 9 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/853)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Pull request merged**
