### PR TITLE
build(blockifier_reexecution): command for writing rpc replies to files

### PR DESCRIPTION
**Pull request by aner-starkware**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1661)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1661#-OARht-72KPQFIPKCs0F:-OARht-72KPQFIPKCs0G:bvfa2et) ([raw file](https://github.com/starkware-libs/sequencer/blob/dbb6eff70beef049a385847542f355cb619fb4ba/crates/blockifier_reexecution/src/main.rs#L43)):*
> ```XML
>         /// Block number.
>         #[clap(long, short = 'b')]
>         block_number: u64,
> ```

these are common args, please put them in a struct and put them here  (and in `RpcTest`) as a single field with `flatten`



_Code quote:_
```XML
        /// Node url.
        /// Default: https://free-rpc.nethermind.io/mainnet-juno/. Won't work for big tests.
        #[clap(long, short = 'n', default_value = "https://free-rpc.nethermind.io/mainnet-juno/")]
        node_url: String,

        /// Block number.
        #[clap(long, short = 'b')]
        block_number: u64,
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1661)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1661#-OARht-72KPQFIPKCs0F:-OASyrSj8pH2HUm-YAYS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dbb6eff70beef049a385847542f355cb619fb4ba/crates/blockifier_reexecution/src/main.rs#L43)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

these are common args, please put them in a struct and put them here  (and in `RpcTest`) as a single field with `flatten`
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1661)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1661#-OAT5uZb4LQzYIA7D98a:-OAT5uZb4LQzYIA7D98b:byvy57e) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3b524a4e27b0f5953a55580ed458d769c404db0/crates/blockifier_reexecution/src/main.rs#L60)):*
> ```XML
> 
>     match args.command {
>         Command::RpcTest { url_and_block_number } => {
> ```

destructure fully in the `match`



_Suggestion:_
```XML
Command::RpcTest { url_and_block_number: SharedArgs { node_url, block_number } }
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1661)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1661#-OAT5uZb4LQzYIA7D98a:-OATEKep70-FQm9Opany:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3b524a4e27b0f5953a55580ed458d769c404db0/crates/blockifier_reexecution/src/main.rs#L60)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

destructure fully in the `match`
</blockquote></details>

Done.

**Pull request merged**
