### PR TITLE
chore(blockifier): dedup test util l1 handler creator

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2131)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @giladchase and @yair-starkware)

___
*[`crates/starknet_api/src/test_utils/l1_handler.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2131#-OByeVZ492Ug3AXQOtAH:-OByeVZ5BrVdQlCm4-02:b-4l7gjn) ([raw file](https://github.com/starkware-libs/sequencer/blob/0681378a42dd7737f128767dd910e12361aae736/crates/starknet_api/src/test_utils/l1_handler.rs#L55)):*
> ```XML
>     // if tx_version != TransactionVersion::THREE {
>     //     panic!("Unsupported transaction version: {:?}.", l1_handler_tx_args.version);
>     // }
> ```

@giladchase - How critical is this validation? The test `crates/blockifier/src/transaction/transactions_test.rs` --- `test_l1_handler` fails with `TransactionVersion::THREE`.

This implies both Versions should be accounted for and tested for... I am working on this PR. 



_Code quote:_
```XML
    // TODO(Arni): Re-enable this validation.
    // if tx_version != TransactionVersion::THREE {
    //     panic!("Unsupported transaction version: {:?}.", l1_handler_tx_args.version);
    // }
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2131)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`crates/starknet_api/src/test_utils/l1_handler.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2131#-OByeVZ492Ug3AXQOtAH:-OBzsZIu7ZoJ6MJMMhRN:b-v4nsnf) ([raw file](https://github.com/starkware-libs/sequencer/blob/0681378a42dd7737f128767dd910e12361aae736/crates/starknet_api/src/test_utils/l1_handler.rs#L55)):*
>How critical is this validation

AFAIK we don't intend to support version < 3, if you heard differently then remove the validation, otherwise it's probably better to keep it and fix the source.

>`crates/blockifier/src/transaction/transactions_test.rs` --- `test_l1_handler` fails with `TransactionVersion::THREE`.

Is this a typo? I don't understand how this can happen, the conditional raises only if transactionVersion is _not_ THREE :thinking: .

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2131)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`crates/starknet_api/src/test_utils/l1_handler.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2131#-OByeVZ492Ug3AXQOtAH:-OBzvS0c2v5qj2Z4Iz77:bak4rnj) ([raw file](https://github.com/starkware-libs/sequencer/blob/0681378a42dd7737f128767dd910e12361aae736/crates/starknet_api/src/test_utils/l1_handler.rs#L55)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

>How critical is this validation

AFAIK we don't intend to support version < 3, if you heard differently then remove the validation, otherwise it's probably better to keep it and fix the source.

>`crates/blockifier/src/transaction/transactions_test.rs` --- `test_l1_handler` fails with `TransactionVersion::THREE`.

Is this a typo? I don't understand how this can happen, the conditional raises only if transactionVersion is _not_ THREE :thinking: .
</blockquote></details>

I will remove this assertion. This test util can be shared with the blockifier test utils, that uses - and assumes the version is 0.
You can see it in this PR.

This is not a typo: In #2146, there is one test case that fails. The test case is of Version::THREE, with USE kzg.
___
*[`crates/blockifier/src/test_utils/l1_handler.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2131#-OBzw8Kx5WHlRwmPtqbK:-OBzw8Kx5WHlRwmPtqbL:b4ndln1) ([raw file](https://github.com/starkware-libs/sequencer/blob/3f82a9f7352cd031dac20e45931f7cbf54ebb5b3/crates/blockifier/src/test_utils/l1_handler.rs#L24)):*
> ```XML
>         paid_fee_on_l1: l1_fee,
>         ..Default::default()
>     })
> ```

@giladchase see code dedup. (using the snapi's test util).
See the version zero. 



_Code quote:_
```XML
    executable_l1_handler_tx(L1HandlerTxArgs {
        version: TransactionVersion::ZERO,
        contract_address,
        entry_point_selector: selector_from_name("l1_handler_set_value"),
        calldata,
        paid_fee_on_l1: l1_fee,
        ..Default::default()
    })
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2131)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`crates/starknet_api/src/test_utils/l1_handler.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2131#-OByeVZ492Ug3AXQOtAH:-OC-bAgO2vVFWEIhwJIs:btocvj8) ([raw file](https://github.com/starkware-libs/sequencer/blob/0681378a42dd7737f128767dd910e12361aae736/crates/starknet_api/src/test_utils/l1_handler.rs#L55)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I will remove this assertion. This test util can be shared with the blockifier test utils, that uses - and assumes the version is 0.
You can see it in this PR.

This is not a typo: In #2146, there is one test case that fails. The test case is of Version::THREE, with USE kzg.
</blockquote></details>

Oh right, ya kill it with fire , tnx!

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2131#-:-OC2LWfM9NPGtHFbc9qE:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`crates/starknet_api/src/test_utils/l1_handler.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2131#-OByeVZ492Ug3AXQOtAH:-OC2L5Ng7-KtoIjV_OBN:b4eyjfb) ([raw file](https://github.com/starkware-libs/sequencer/blob/0681378a42dd7737f128767dd910e12361aae736/crates/starknet_api/src/test_utils/l1_handler.rs#L55)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Oh right, ya kill it with fire , tnx!
</blockquote></details>

I mean delete it altogether, no need to reenable if it if the version3 assumption is incorrect

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2131)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
