### PR TITLE
refactor(batcher): refactor proposal manager

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/790)

### CODE REVIEW

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/790)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 203 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/790#-O6zENaHCGknBZMt68z4:-O6zENaHCGknBZMt68z5:b91hqft) ([raw file](https://github.com/starkware-libs/sequencer/blob/62a74a1b6de9e1bdca8365d4ec507fc2077bfe60/crates/batcher/src/proposals_manager.rs#L203)):*
> ```XML
>                         self.max_txs_per_mempool_request,
>                         &mempool_tx_sender,
>                     ) => {
> ```

wdyt about defining a streaming_future in advance?
same as you did for the building_future.
I think it will be more readable



_Code quote:_
```XML
                    fetch_result = Self::feed_more_mempool_txs(
                        &self.mempool_client,
                        self.max_txs_per_mempool_request,
                        &mempool_tx_sender,
                    ) => {
```
___
*[`crates/batcher/src/proposals_manager.rs` line 232 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/790#-O6zEarq79wry37JTGXy:-O6zEarq79wry37JTGXz:b-gduive) ([raw file](https://github.com/starkware-libs/sequencer/blob/62a74a1b6de9e1bdca8365d4ec507fc2077bfe60/crates/batcher/src/proposals_manager.rs#L232)):*
> ```XML
>         for tx in mempool_txs {
>             mempool_tx_sender.send(tx).await.map_err(|err| {
>                 // TODO: should we return the rest of the txs to the mempool?
> ```

yes, but I think it should be one flow together with cleaning up aborted proposals. 
I wonder if this is the batcher responsibility or the orchestrator's. In this case the orchestrator may not have gotten all the transactions yet. we should probably discuss this in the broader context of how to return txs to the mempool.



_Code quote:_
```XML
// TODO: should we return the rest of the txs to the mempool?
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/790)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 196 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/790#-O6zSLJjDQSjBpNM50J2:-O6zSLJk-HM9dib2mCit:b-7p9pkp) ([raw file](https://github.com/starkware-libs/sequencer/blob/62a74a1b6de9e1bdca8365d4ec507fc2077bfe60/crates/batcher/src/proposals_manager.rs#L196)):*
> ```XML
>             );
>             pin!(building_future);
>             loop {
> ```

I think the loop should be inside feed_more_mempool_txs.



_Code quote:_
```XML
loop {
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/790)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 196 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/790#-O6zSLJjDQSjBpNM50J2:-O7O3DgzBlNLJzzrM6K4:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/62a74a1b6de9e1bdca8365d4ec507fc2077bfe60/crates/batcher/src/proposals_manager.rs#L196)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think the loop should be inside feed_more_mempool_txs.
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposals_manager.rs` line 203 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/790#-O6zENaHCGknBZMt68z4:-O7O3E_c0YRAUpenJU3K:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/62a74a1b6de9e1bdca8365d4ec507fc2077bfe60/crates/batcher/src/proposals_manager.rs#L203)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

wdyt about defining a streaming_future in advance?
same as you did for the building_future.
I think it will be more readable
</blockquote></details>

Done.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/790)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 210 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/790#-O7Sy8jh6RuqmOKfCZGn:-O7Sy8jh6RuqmOKfCZGo:b-5gq0gb) ([raw file](https://github.com/starkware-libs/sequencer/blob/64cfda8087a1f62ed635ce596a35c4427b8838fc/crates/batcher/src/proposals_manager.rs#L210)):*
> ```XML
>             },
>             builder_done = building_future => {
>                 info!("Block builder finished.");
> ```

The building future can also return with an error.

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/790)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 232 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/790#-O6zEarq79wry37JTGXy:-O7TGqLlCyCTMD4I_ton:bgrr8d8) ([raw file](https://github.com/starkware-libs/sequencer/blob/62a74a1b6de9e1bdca8365d4ec507fc2077bfe60/crates/batcher/src/proposals_manager.rs#L232)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

yes, but I think it should be one flow together with cleaning up aborted proposals. 
I wonder if this is the batcher responsibility or the orchestrator's. In this case the orchestrator may not have gotten all the transactions yet. we should probably discuss this in the broader context of how to return txs to the mempool.
</blockquote></details>

For now I think the todo is ok.
___
*[`crates/batcher/src/proposals_manager.rs` line 210 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/790#-O7Sy8jh6RuqmOKfCZGn:-O7TGQS_84gpHXMS_cUc:b-3jlvqy) ([raw file](https://github.com/starkware-libs/sequencer/blob/64cfda8087a1f62ed635ce596a35c4427b8838fc/crates/batcher/src/proposals_manager.rs#L210)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

The building future can also return with an error.
</blockquote></details>

I will handle it in another PR after we have more final API for the block builder

**Comment by yair-starkware** [comment]
*[`crates/batcher/src/proposals_manager.rs` line 232 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/790#-O6zEarq79wry37JTGXy:-O7TXxpZA4akNu_QqSJJ:b-kjn7he) ([raw file](https://github.com/starkware-libs/sequencer/blob/62a74a1b6de9e1bdca8365d4ec507fc2077bfe60/crates/batcher/src/proposals_manager.rs#L232)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

For now I think the todo is ok.
</blockquote></details>

Resolved in https://github.com/starkware-libs/sequencer/pull/541

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/790)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @ArniStarkware and @dafnamatsry)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/790#-:-O7TivK65ar1AIGyVE0Z:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/batcher/src/proposals_manager.rs` line 181 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/790#-O7TggwNChCZ7ZxQ_e_1:-O7TggwNChCZ7ZxQ_e_2:b-dr2su2) ([raw file](https://github.com/starkware-libs/sequencer/blob/64cfda8087a1f62ed635ce596a35c4427b8838fc/crates/batcher/src/proposals_manager.rs#L181)):*
> ```XML
> impl BuildProposalTask {
>     async fn run(mut self) -> ProposalsManagerResult<()> {
>         // TODO: Should we use a different config for the stream buffer size?
> ```

Note:
You defined a different config in https://reviewable.io/reviews/starkware-libs/sequencer/541#-



_Code quote:_
```XML
// TODO: Should we use a different config for the stream buffer size?
```
___
*[`crates/batcher/src/proposals_manager.rs` line 227 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/790#-O7Ti_ff-I3O8gZMvRn0:-O7Ti_ff-I3O8gZMvRn1:bjfujwb) ([raw file](https://github.com/starkware-libs/sequencer/blob/64cfda8087a1f62ed635ce596a35c4427b8838fc/crates/batcher/src/proposals_manager.rs#L227)):*
> ```XML
>         loop {
>             // TODO: Get L1 transactions.
>             let mempool_txs = match mempool_client.get_txs(max_txs_per_mempool_request).await {
> ```

Note:
handle the case of empty `mempool_txs`.

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/790)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
