### PR TITLE
feat(blockifier): compute fee from new gas vector

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)

### CODE REVIEW

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O86t_W17OFvKIBA1t_s:-O86t_W17OFvKIBA1t_t:b-m8mlo0) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee87ab8c0e265d853dcd097eb3aa4be3fc5b596e/crates/blockifier/src/fee/fee_utils.rs#L82)):*
> ```XML
>     fee_type: &FeeType,
> ) -> Fee {
>     gas_vector.saturated_cost(&block_info.gas_prices.get_gas_prices_by_fee_type(fee_type))
> ```

are you sure saturation is the correct behaviour?
(It probably is, but since this seems sensitive I want to make sure)



_Code quote:_
```XML
gas_vector.saturated_cost(&block_info.gas_prices.get_gas_prices_by_fee_type(fee_type))
```
___
*[`crates/blockifier/src/fee/resources.rs` line 318 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O86sh-Y7-iZdb1bMJXT:-O86sh-Z8ygRirfdGu6I:bfvqu1u) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee87ab8c0e265d853dcd097eb3aa4be3fc5b596e/crates/blockifier/src/fee/resources.rs#L318)):*
> ```XML
>             let cost = gas.checked_mul(price.get()).unwrap_or_else(|| {
>                 log::warn!(
>                     "{} cost overflowed: multiplication of {} by {} resulted in overflow.",
> ```

please state which is cost and which is amount



_Code quote:_
```XML
cost overflowed: multiplication of {} by {} resulted in overflow.
```
___
*[`crates/blockifier/src/fee/resources.rs` line 327 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O86t5WHA4LMEVeAcB1Z:-O86t5WHA4LMEVeAcB1_:bdz5yca) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee87ab8c0e265d853dcd097eb3aa4be3fc5b596e/crates/blockifier/src/fee/resources.rs#L327)):*
> ```XML
>             sum = sum.checked_add(cost).unwrap_or_else(|| {
>                 log::warn!(
>                     "Total cost overflowed: addition of {} and {} resulted in overflow.",
> ```

please state which is total and which is added resource (and what resource it is)



_Code quote:_
```XML
"Total cost overflowed: addition of {} and {} resulted in overflow.",
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O86t_W17OFvKIBA1t_s:-O86z3YR5S4aDP9gZ1OA:b-1lqp9t) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee87ab8c0e265d853dcd097eb3aa4be3fc5b596e/crates/blockifier/src/fee/fee_utils.rs#L82)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

are you sure saturation is the correct behaviour?
(It probably is, but since this seems sensitive I want to make sure)
</blockquote></details>

yes - when charging fee, if something costs too much, we don't want to fail to collect (possible, though probably infeasible, attack vector)
___
*[`crates/blockifier/src/fee/resources.rs` line 318 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O86sh-Y7-iZdb1bMJXT:-O87-sIp61Mts4w1F6Hm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee87ab8c0e265d853dcd097eb3aa4be3fc5b596e/crates/blockifier/src/fee/resources.rs#L318)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

please state which is cost and which is amount
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/resources.rs` line 327 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O86t5WHA4LMEVeAcB1Z:-O87-snE9QGBH2VBgojd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee87ab8c0e265d853dcd097eb3aa4be3fc5b596e/crates/blockifier/src/fee/resources.rs#L327)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

please state which is total and which is added resource (and what resource it is)
</blockquote></details>

Done.

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O8738Uc9SckAAt-FcYj:-O8738Uc9SckAAt-FcYk:b-c2mnk7) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee87ab8c0e265d853dcd097eb3aa4be3fc5b596e/crates/blockifier/src/fee/fee_utils.rs#L77)):*
> ```XML
> 
> /// Converts the gas vector to a fee.
> pub fn get_fee_by_gas_vector(
> ```

please find where this is tested and add L2 gas to the test



_Code quote:_
```XML
pub fn get_fee_by_gas_vector(
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O8738Uc9SckAAt-FcYj:-O879Lv_6F-szMMQkg7m:b-47vb9n) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee87ab8c0e265d853dcd097eb3aa4be3fc5b596e/crates/blockifier/src/fee/fee_utils.rs#L77)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

please find where this is tested and add L2 gas to the test
</blockquote></details>

this is coupled with the task of deleting the `max_l1_resource_bounds` fixture; I'll parametrize one test as an example (`test_max_fee_limit_validate`)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 479 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O87QWLC9ivt5NIOl2ro:-O87QWLC9ivt5NIOl2rp:bbkjsss) ([raw file](https://github.com/starkware-libs/sequencer/blob/f85ca573f06dd7f0d9bb9ae831743b31fe0971bf/crates/blockifier/src/transaction/account_transactions_test.rs#L479)):*
> ```XML
>         &GasVectorComputationMode::NoL2Gas,
>     );
>     let estimated_min_l1_gas = estimated_min_gas_usage_vector.l1_gas;
> ```

used only once, so i inlined below



_Code quote:_
```XML
estimated_min_l1_gas = estimated_min_gas_usage_vector.l1_gas
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O8738Uc9SckAAt-FcYj:-O87iVyXANRiNKSklKxv:bmsnbvy) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee87ab8c0e265d853dcd097eb3aa4be3fc5b596e/crates/blockifier/src/fee/fee_utils.rs#L77)):*
> we should add new features together with tests, no?

agree 100%.

> IMO `get_fee_by_gas_vector` warrants a test - can you add one / add a TODO to add one?

not exactly true IMO - a unit test for this function is basically a unit test for a dot product between vectors.
we also really don't want (a) hard-coded fee values in regression tests (too sensitive) and (b) we don't want to enforce a relation between fee computed with and without L2 gas;
what test would you like to see for this function?

the fact that both gas modes are used in some test that uses `get_fee_by_gas_vector` more than nothing
___
*[`crates/blockifier/src/fee/resources.rs` line 371 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O87K7iu7eoC4u-Ag90Q:-O87k9CZ-T-WbYldeGSe:bt2s8o5) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9aed511098c65af4f9b85b9027a3b305330df8e/crates/blockifier/src/fee/resources.rs#L371)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

@Yoni-Starkware told me, and I agree, that `from` should consume the object (or use all of it's fields).
can you add a method similar to [this](https://github.com/starkware-libs/sequencer/blob/23f9f8118b047436f21d05dc868b28efb4c10fcd/crates/blockifier/src/context.rs#L33),
and also use it in the above method?
</blockquote></details>

ok, but this will involve moving `GasVectorComputationMode` into starknet api... will open a preemptive PR for this, [here you go](https://reviewable.io/reviews/starkware-libs/sequencer/1152)
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 439 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O87X_3z5kHIHBz--_TW:-O87maN9-JqD1trChSQ2:b-lnx21u) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9aed511098c65af4f9b85b9027a3b305330df8e/crates/blockifier/src/transaction/account_transactions_test.rs#L439)):*
> what? this fails even on max L1 resource bounds? isn't that crazy high?

yes; it should hit the "global" limit, even if user signs on `u128::MAX` amount and price, we still limit to 1 million steps in validation or something like that.
the grindy phase is very long:
```
const GRIND_DEPTH: felt252 = 10000000;
```

> should the All-resources case also pass max resources?

ah, right.. but looking at the code, the problem is with the names, not the values... even the "defaults" are good enough, pretty much equivalent to the "max" bounds
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 474 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O87Y2hR3-PRKt80MXm7:-O87mJAJ43KqUb-QIrO4:b47ocxg) ([raw file](https://github.com/starkware-libs/sequencer/blob/f85ca573f06dd7f0d9bb9ae831743b31fe0971bf/crates/blockifier/src/transaction/account_transactions_test.rs#L474)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

why is this sent in addition to `resource_bounds`?
</blockquote></details>

invoke_tx_args is designed to accept all parameters for all tx versions, and ignores/uses specific fields based on the `version` parameter.
`max_fee` will be ignored always, except for the `version == TransactionVersion::ONE` case.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 497 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O87_Jh_6bjFskJZyntD:-O87nm526_s_ZfreaiTZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9aed511098c65af4f9b85b9027a3b305330df8e/crates/blockifier/src/transaction/account_transactions_test.rs#L497)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

please use `create_all_resource_bounds`, this is a fixture
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 100 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O87N1v31V0ipP221puZ:-O87nztiDdW0oavUgjap:b-7pfpl4) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9aed511098c65af4f9b85b9027a3b305330df8e/crates/blockifier/src/transaction/test_utils.rs#L100)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

why not use `all_resource_bounds`? note the default args
</blockquote></details>

Doesn't work: when calling it explicitly you need to provide the values.
the `#[default]` works when it's used like a fixture

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O8738Uc9SckAAt-FcYj:-O8ViBfj78O7e1kGTQZo:b-pbv0oy) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee87ab8c0e265d853dcd097eb3aa4be3fc5b596e/crates/blockifier/src/fee/fee_utils.rs#L77)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

> we should add new features together with tests, no?

agree 100%.

> IMO `get_fee_by_gas_vector` warrants a test - can you add one / add a TODO to add one?

not exactly true IMO - a unit test for this function is basically a unit test for a dot product between vectors.
we also really don't want (a) hard-coded fee values in regression tests (too sensitive) and (b) we don't want to enforce a relation between fee computed with and without L2 gas;
what test would you like to see for this function?

the fact that both gas modes are used in some test that uses `get_fee_by_gas_vector` more than nothing
</blockquote></details>

I would add a regression test for `get_fee_by_gas_vector` - why is that sensitive? it wouldn't reflect real gas amounts / costs
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 439 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O87X_3z5kHIHBz--_TW:-O8VqLOD9GFSDyILymPs:b-mwe5zf) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9aed511098c65af4f9b85b9027a3b305330df8e/crates/blockifier/src/transaction/account_transactions_test.rs#L439)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

> what? this fails even on max L1 resource bounds? isn't that crazy high?

yes; it should hit the "global" limit, even if user signs on `u128::MAX` amount and price, we still limit to 1 million steps in validation or something like that.
the grindy phase is very long:
```
const GRIND_DEPTH: felt252 = 10000000;
```

> should the All-resources case also pass max resources?

ah, right.. but looking at the code, the problem is with the names, not the values... even the "defaults" are good enough, pretty much equivalent to the "max" bounds
</blockquote></details>

I'm not sure I understand what this test tests - 
is it supposed to assert that the `validate` phase is bound by the resource bounds?
or is it supposed to test the global limit you mention above?

for the first option the current resource bounds seem fine, but for the second option we should use max values for the resource bounds (and the current bounds are far from that, also for L2)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O8738Uc9SckAAt-FcYj:-O8W7Axl6YBYGooUmRc8:b-kxqfuu) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee87ab8c0e265d853dcd097eb3aa4be3fc5b596e/crates/blockifier/src/fee/fee_utils.rs#L77)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I would add a regression test for `get_fee_by_gas_vector` - why is that sensitive? it wouldn't reflect real gas amounts / costs
</blockquote></details>

added pre-PR [here](https://reviewable.io/reviews/starkware-libs/sequencer/1186), and added more test cases for current PR, PTAL
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 439 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O87X_3z5kHIHBz--_TW:-O8W7y8hCpyJMNKRVGw7:b-1ojusj) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9aed511098c65af4f9b85b9027a3b305330df8e/crates/blockifier/src/transaction/account_transactions_test.rs#L439)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I'm not sure I understand what this test tests - 
is it supposed to assert that the `validate` phase is bound by the resource bounds?
or is it supposed to test the global limit you mention above?

for the first option the current resource bounds seem fine, but for the second option we should use max values for the resource bounds (and the current bounds are far from that, also for L2)
</blockquote></details>

first option. the global limits are only applied when testing that `__validate_deploy__` is limited by the global bound - we test `__validate__` limits only after deploying successfully (second deploy attempt in the test)

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O8738Uc9SckAAt-FcYj:-O8X8VTv6xbCSuEkkste:b7txyqu) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee87ab8c0e265d853dcd097eb3aa4be3fc5b596e/crates/blockifier/src/fee/fee_utils.rs#L77)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

added pre-PR [here](https://reviewable.io/reviews/starkware-libs/sequencer/1186), and added more test cases for current PR, PTAL
</blockquote></details>

LGTM on pre-PR
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 439 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O87X_3z5kHIHBz--_TW:-O8XM_w943PWbmoJLGnN:b-3m41n5) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9aed511098c65af4f9b85b9027a3b305330df8e/crates/blockifier/src/transaction/account_transactions_test.rs#L439)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

first option. the global limits are only applied when testing that `__validate_deploy__` is limited by the global bound - we test `__validate__` limits only after deploying successfully (second deploy attempt in the test)
</blockquote></details>

after talking F2F:
the test steps -
1.  deploy, using max bounds, with grind; global limit reached
2.  deploy, using max bounds, no grind; success
3.  create a temporary invoke tx (do not run!) with max bounds, just to estimate minimal fee
4.  invoke, using minimal bounds, with grind; regular limit reached

fix for step 1: resource bounds should have max values, so that the global limit is reached.
fix for step 4: the grind should be lower than the global limit, so that if the resource bounds don't limit validate, the tx will succeed.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 439 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O87X_3z5kHIHBz--_TW:-O8a-Cbp6TfVCIgjitoY:bj5f328) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9aed511098c65af4f9b85b9027a3b305330df8e/crates/blockifier/src/transaction/account_transactions_test.rs#L439)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

after talking F2F:
the test steps -
1.  deploy, using max bounds, with grind; global limit reached
2.  deploy, using max bounds, no grind; success
3.  create a temporary invoke tx (do not run!) with max bounds, just to estimate minimal fee
4.  invoke, using minimal bounds, with grind; regular limit reached

fix for step 1: resource bounds should have max values, so that the global limit is reached.
fix for step 4: the grind should be lower than the global limit, so that if the resource bounds don't limit validate, the tx will succeed.
</blockquote></details>

1. global limit is now tested by lowering the limit, instead of increasing the bounds (easier, + makes the test faster)
4. done [here](https://reviewable.io/reviews/starkware-libs/sequencer/1212)

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 439 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O87X_3z5kHIHBz--_TW:-O8bC3cw8tBUkYzVUI_4:bfo5ryt) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9aed511098c65af4f9b85b9027a3b305330df8e/crates/blockifier/src/transaction/account_transactions_test.rs#L439)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. global limit is now tested by lowering the limit, instead of increasing the bounds (easier, + makes the test faster)
4. done [here](https://reviewable.io/reviews/starkware-libs/sequencer/1212)
</blockquote></details>

it's not possible to understand from the error if the execution failed because of the resource bounds or the global limit, right?
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 403 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O8bBfTW5Vjhc3UqFQ5F:-O8bBfTW5Vjhc3UqFQ5G:b-p7tl9n) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bc79ae1fafd953a3d47e0c0459d68300c3ba69d/crates/blockifier/src/transaction/account_transactions_test.rs#L403)):*
> ```XML
> #[case::v3_all_bounds(TransactionVersion::THREE, default_all_resource_bounds())]
> fn test_max_fee_limit_validate(
>     mut block_context: BlockContext,
> ```

can you clone instead?
this can be very confusing



_Code quote:_
```XML
mut block_context: BlockContext,
```

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 397 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O8bDFeSCf0OVsKPxods:-O8bDFeSCf0OVsKPxodt:bbbgp1m) ([raw file](https://github.com/starkware-libs/sequencer/blob/a49f672df208f8494c7946f9d1daa883eff1466c/crates/blockifier/src/transaction/account_transactions_test.rs#L397)):*
> ```XML
>     }
> }
> ```

I think you fulfilled this



_Code quote:_
```XML
// TODO(Aner, 21/01/24) modify test for 4844.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 439 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O87X_3z5kHIHBz--_TW:-O8bL2JlDYM3iA_bxzXq:bj3qp38) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9aed511098c65af4f9b85b9027a3b305330df8e/crates/blockifier/src/transaction/account_transactions_test.rs#L439)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

it's not possible to understand from the error if the execution failed because of the resource bounds or the global limit, right?
</blockquote></details>

right, the answer to this question is not part of the tx execution context
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 397 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O8bDFeSCf0OVsKPxods:-O8bKvmW-WxUCHnVsdND:b-taie3l) ([raw file](https://github.com/starkware-libs/sequencer/blob/a49f672df208f8494c7946f9d1daa883eff1466c/crates/blockifier/src/transaction/account_transactions_test.rs#L397)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I think you fulfilled this
</blockquote></details>

nope, but now I did :)
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 403 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O8bBfTW5Vjhc3UqFQ5F:-O8bKyd3BJHGl8_ScSip:b4i9j3v) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bc79ae1fafd953a3d47e0c0459d68300c3ba69d/crates/blockifier/src/transaction/account_transactions_test.rs#L403)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

can you clone instead?
this can be very confusing
</blockquote></details>

why? would still need to mutate the clone, what is the benefit?

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 403 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O8bBfTW5Vjhc3UqFQ5F:-O8g6Kun4ANf0DofMJQb:b-y4arpu) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bc79ae1fafd953a3d47e0c0459d68300c3ba69d/crates/blockifier/src/transaction/account_transactions_test.rs#L403)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why? would still need to mutate the clone, what is the benefit?
</blockquote></details>

if mutate block_context, won't it change it for other tests which use this fixture?
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 505 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O8gB8Ht04mtSzUIfQ_Y:-O8gB8Hu6JQS2WnDpyp7:b-ku9prc) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f93d637090d2afe94c1260e505c270a43453180/crates/blockifier/src/transaction/account_transactions_test.rs#L505)):*
> ```XML
>                         block_info.gas_prices
>                             .get_l1_gas_price_by_fee_type(&account_tx.fee_type()).into()
>                     )
> ```

won't it be better to pass resource bounds that include L1 data gas? or is that not possible?



_Code quote:_
```XML
                    l1_resource_bounds(
                        estimated_min_gas_usage_vector.to_discounted_l1_gas(&tx_context),
                        block_info.gas_prices
                            .get_l1_gas_price_by_fee_type(&account_tx.fee_type()).into()
                    )
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 509 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O8g99xu6V5-1iYDpKsN:-O8g99xu6V5-1iYDpKsO:b-ep0247) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f93d637090d2afe94c1260e505c270a43453180/crates/blockifier/src/transaction/account_transactions_test.rs#L509)):*
> ```XML
>                 GasVectorComputationMode::All => create_all_resource_bounds(
>                     // TODO(Ori, 1/2/2024): Write an indicative expect message explaining why the
>                     // conversion works.
> ```

you think this is about converting u128 to u64?



_Code quote:_
```XML
                    // TODO(Ori, 1/2/2024): Write an indicative expect message explaining why the
                    // conversion works.
```

**Review by amosStarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 496 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O8gC8Q-9sm5IXG2lcoT:-O8gC8Q-9sm5IXG2lcoU:bbhdb94) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f93d637090d2afe94c1260e505c270a43453180/crates/blockifier/src/transaction/account_transactions_test.rs#L496)):*
> ```XML
>                     // If KZG DA mode is active, the L1 gas amount in the minimal fee estimate does
>                     // not include DA. To cover minimal cost with only an L1 gas bound, need to
>                     // convert the L1 data gas to L1 gas.
> ```

none blocking



_Suggestion:_
```XML
                    // If KZG DA mode is active, the L1 data gas amount is greater than zero,
                    // and it needs to be converted into L1 gas.
```

**Review by amosStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 496 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O8gC8Q-9sm5IXG2lcoT:-O8gID_O0lIFBAhgu7vJ:b-wcwlhj) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f93d637090d2afe94c1260e505c270a43453180/crates/blockifier/src/transaction/account_transactions_test.rs#L496)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

hmm... this is true if there is a state change, I prefer the current phrasing.. you find it confusing?
</blockquote></details>

a bit, but not important

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 0 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/1114#-O8gKgDc-K-8GqykRvjJ:-O8gKgDc-K-8GqykRvjK:b85dgob) ([raw file](https://github.com/starkware-libs/sequencer/blob/7eeb7a3d71eadfe2dd318fbb3d2133a92d9c39f6/crates/blockifier/src/fee/resources.rs#L0)):*
@Yoni-Starkware FYI

**Review by amosStarkware — APPROVED** [review]
> Reviewed 5 of 6 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1114)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Pull request merged**
