### PR TITLE
chore(sequencer_node): separate config pointers to required and optional

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #1725
- #1710
- #1709
- #1708
- #1707
- #1706
- #1701 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by nadin-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1701)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/config/node_config.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1701#-OAXhCJd5H_F5CJRFs80:-OAXhCJd5H_F5CJRFs81:b-s8l51e) ([raw file](https://github.com/starkware-libs/sequencer/blob/c8054edfdb8a66f68d29de6b87742b511bbf73f6/crates/mempool_node/src/config/node_config.rs#L60)):*
> ```XML
> pub static CONFIG_POINTERS: LazyLock<Vec<(ParamPath, SerializedParam)>> = LazyLock::new(|| {
>     let mut combined = REQUIRED_PARAM_CONFIG_POINTERS.clone();
>     combined.extend(DEFAULT_PARAM_CONFIG_POINTERS.iter().cloned());
> ```

Why not use just .clone()?



_Code quote:_
```XML
.iter().cloned()
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1701)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/mempool_node/src/config/node_config.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1701#-OAXhCJd5H_F5CJRFs80:-OAXtaHiAZzfCkPIdItS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c8054edfdb8a66f68d29de6b87742b511bbf73f6/crates/mempool_node/src/config/node_config.rs#L60)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Why not use just .clone()?
</blockquote></details>

Done.

**Review by nadin-Starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1701)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1701)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#1706](https://github.com/starkware-libs/sequencer/pull/1706)

**Pull request closed without merging**
