### PR TITLE
feat(ci): add native dependencies to the CI (dynamic docker)

### PR DESCRIPTION
**Pull request by varex83**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/726)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/726)* status: 0 of 25 files reviewed, 1 unresolved discussion (waiting on @varex83)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/726#-O6KOb8j4d2UACBHR9AM:-O6KOb8j4d2UACBHR9AN:b2k1iot) (no related file):*
Please fetch and rebase under main. The papyrus_protobuf error you are facing in the ci has already been fixed.  

___

**Comment by avi-starkware** [comment]
*[`.github/workflows/blockifier_ci.yml` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/726#-O6LP0TDBhiF2y70Izlk:-O6LP0TDBhiF2y70Izll:b-sy3otq) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf1edddc709a21ed10447de7743c0e7085b9c001/.github/workflows/blockifier_ci.yml#L56)):*
> ```YAML
> 
>   native-blockifier-artifacts-push:
>     runs-on: starkware-ubuntu-latest-large
> ```

Why not use `starkware-ubuntu-latest-small`?



_Code quote:_
```YAML
starkware-ubuntu-latest-large
```

**Review by varex83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/726)* status: 0 of 25 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

___
*[`.github/workflows/blockifier_ci.yml` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/726#-O6LP0TDBhiF2y70Izlk:-O6LXwt_4jLqFJV5TeBI:b-kehqx0) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf1edddc709a21ed10447de7743c0e7085b9c001/.github/workflows/blockifier_ci.yml#L56)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Why not use `starkware-ubuntu-latest-small`?
</blockquote></details>

we've tried to use as least resources as we could, but the size of the artifacts produced is quite big, so it didn't work even with medium-sized image

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/726)* status: 1 of 26 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @meship-starkware, and @varex83)

___
*[`.github/actions/setup-native-deps/action.yml` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/726#-O6tmJe180mPMAUIlpVb:-O6tmJe180mPMAUIlpVc:brndqip) ([raw file](https://github.com/starkware-libs/sequencer/blob/cf1edddc709a21ed10447de7743c0e7085b9c001/.github/actions/setup-native-deps/action.yml#L25)):*
> ```YAML
>         sudo apt-get install -y zstd
>         sudo apt-get install llvm-18 llvm-18-dev llvm-18-runtime clang-18 clang-tools-18 lld-18 libpolly-18-dev libmlir-18-dev mlir-18-tools
>         sudo apt-get install -y libgmp3-dev
> ```

script it and use it in the docker build and in the action



_Code quote:_
```YAML
    - name: Add llvm deb repository
      uses: myci-actions/add-deb-repo@11
      with:
        repo: deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main
        repo-name: llvm-repo
        keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key

    - name: Install LLVM and gmplib
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get upgrade -y
        sudo apt-get install -y zstd
        sudo apt-get install llvm-18 llvm-18-dev llvm-18-runtime clang-18 clang-tools-18 lld-18 libpolly-18-dev libmlir-18-dev mlir-18-tools
        sudo apt-get install -y libgmp3-dev
```

**Review by alon-dotan-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/726)* status: 3 of 26 files reviewed, all discussions resolved (waiting on @avi-starkware and @meship-starkware)

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/726#-:-O6tu4SmE-lSdyQMwnHD:bnfp4nl)* status: 3 of 26 files reviewed, all discussions resolved (waiting on @avi-starkware and @meship-starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 12 of 25 files at r1, 2 of 4 files at r2, 2 of 2 files at r18, 1 of 1 files at r19, 1 of 3 files at r20, 1 of 2 files at r21, 6 of 6 files at r22, 1 of 1 files at r23, 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/726)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware and @meship-starkware)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/726)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @meship-starkware, and @varex83)

___
*[`crates/blockifier/feature_contracts/cairo1/compiled/account_faulty.casm.json` line 3 at r24](https://reviewable.io/reviews/starkware-libs/sequencer/726#-O6yixkk0qQz9_UkqCU1:-O6yixkk0qQz9_UkqCU2:b-122m6g) ([raw file](https://github.com/starkware-libs/sequencer/blob/1848b1ebdd7b32d376737b8c3ccf9ed86b1f8316/crates/blockifier/feature_contracts/cairo1/compiled/account_faulty.casm.json#L3)):*
> ```JSON
> {
>   "prime": "0x800000000000011000000000000000000000000000000000000000000000001",
>   "compiler_version": "2.8.2",
> ```

Did you recompile those contracts with 2.8.2 version? 



_Code quote:_
```JSON
"compiler_version": "2.8.2",
```

**Review by varex83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/726)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/compiled/account_faulty.casm.json` line 3 at r24](https://reviewable.io/reviews/starkware-libs/sequencer/726#-O6yixkk0qQz9_UkqCU1:-O6ylx8v65-RA4RBaATj:b-qhg3xu) ([raw file](https://github.com/starkware-libs/sequencer/blob/1848b1ebdd7b32d376737b8c3ccf9ed86b1f8316/crates/blockifier/feature_contracts/cairo1/compiled/account_faulty.casm.json#L3)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Did you recompile those contracts with 2.8.2 version?
</blockquote></details>

yes, since the feature contracts test was arguing

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/726)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware and @meship-starkware)

**Comment by rodrigo-pino** [comment]
Solution given in #726

**Pull request merged**
