### PR TITLE
refactor: use fully-qualified std::fmt::Display trait

### PR DESCRIPTION
**Pull request by elintul**
To disambiguate from derive_more::Display.

### CODE REVIEW

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1451)

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1451)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1451#-O9cw8OSA5DT07Fztfgt:-O9cw8OSA5DT07Fztfgu:b-rbqcdq) (no related file):*
There are additional uses in `crates/starknet_client/src/starknet_error.rs` and`crates/papyrus_rpc/src/version_config.rs`

___

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1451)* status: 7 of 12 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1451#-O9cw8OSA5DT07Fztfgt:-O9d4pzg8DnyPVcRt-Ja:b-ymvj5m) (no related file):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

There are additional uses in `crates/starknet_client/src/starknet_error.rs` and`crates/papyrus_rpc/src/version_config.rs`
</blockquote></details>

Good catch!
Done.

___

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1451#-:-O9d6mPA2DwLylES00xp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1451)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by ayeletstarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1451)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1451)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
