### PR TITLE
chore(blockifier_reexecution): add blockifier reexecution test to ci

### PR DESCRIPTION
**Pull request by aner-starkware**

### CODE REVIEW

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC3xWAzDhEfRoEUV1O5:-OC3xWB-Air7e0fCrXp9:bdsrzk5) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs#L170)):*
> ```XML
> #[case::v_0_13_0(600001)]
> // Commented out until fix integrated.
> // #[case::v_0_13_1(620978)]
> ```

Blocking myself until rebased and can be uncommented



_Code quote:_
```XML
// Commented out until fix integrated.
// #[case::v_0_13_1(620978)]
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1857)* status: all files reviewed, 11 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC41U-Z6OosUWouLVi5:-OC41U-Z6OosUWouLVi6:b-xkv0sc) (no related file):*
we now need a README.md file for this crate. Can you write one?
(it can be a separate PR)
the readme should cover:
1. All CLI commands and their meaning
2. How to run the RPC tests (using `TEST_URL=<ENDPOINT>`)
___
*[`crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC3xWAzDhEfRoEUV1O5:-OC40PS44xZzQtXpE-a2:b-dijz5c) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs#L170)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Blocking myself until rebased and can be uncommented
</blockquote></details>

also blocking because blocking self sometimes doesn't actually work
___
*[`crates/blockifier_reexecution/resources/offline_reexecution_files_prefix` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC40Ji88PcRBVbw97wr:-OC40Ji88PcRBVbw97ws:b-z1y1cl) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/crates/blockifier_reexecution/resources/offline_reexecution_files_prefix#L1)):*
> ```
> 4f7def520
> ```

not that it matters much, but... where is this value from?



_Code quote:_
```
4f7def520
```
___
*[`.github/workflows/blockifier_ci.yml` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC4-QBaDoS4tMenyqOz:-OC4-QBaDoS4tMenyqP-:bhpb7a4) ([raw file](https://github.com/starkware-libs/sequencer/blob/846e4ea7b8a9281a639673b250eaeea38e657fee/.github/workflows/blockifier_ci.yml#L57)):*
> ```YAML
>       # transaction_serde is not activated by any workspace crate; test the build.
>       - run: cargo build -p blockifier --features transaction_serde
>       - run: cargo test -p blockifier --features transaction_serde
> ```

I think this is still worth keeping. I know reexecution feature always activates this serde feature but we shouldn't assume this will be true forever IMO.



_Code quote:_
```YAML
      # transaction_serde is not activated by any workspace crate; test the build.
      - run: cargo build -p blockifier --features transaction_serde
      - run: cargo test -p blockifier --features transaction_serde
```
___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC4-4_E1Udjs6RsoYok:-OC4-4_E1Udjs6RsoYol:bhjd3qu) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L9)):*
> ```YAML
>       - main-v[0-9].**
>     tags:
>       - v[0-9].**
> ```

do we want to run this CI on post-merge? I doubt it; it should only block PRs



_Code quote:_
```YAML
  push:
    branches:
      - main
      - main-v[0-9].**
    tags:
      - v[0-9].**
```
___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC4-2-O0pAPXaBuwczI:-OC4-2-P9-baOYQ-86TB:byb7mpc) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L11)):*
> ```YAML
>       - v[0-9].**
>     # TODO(Dori, 1/9/2024): Decide when exactly native-blockifier artifacts will be built. Until
>     #   then, keep the 'paths' key empty and build on every push to a release branch / tag.
> ```

irrelevant (copied from somewhere?)



_Code quote:_
```YAML
    # TODO(Dori, 1/9/2024): Decide when exactly native-blockifier artifacts will be built. Until
    #   then, keep the 'paths' key empty and build on every push to a release branch / tag.
```
___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC3zxyu4NlySrZVDq2B:-OC3zxyu4NlySrZVDq2C:b-1zh60b) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L26)):*
> ```YAML
>       - '.github/workflows/blockifier_ci.yml'
>       - '.github/workflows/upload_artifacts_workflow.yml'
>       - 'build_native_in_docker.sh'
> ```

why should these three trigger this workflow?



_Code quote:_
```YAML
      - '.github/workflows/blockifier_ci.yml'
      - '.github/workflows/upload_artifacts_workflow.yml'
      - 'build_native_in_docker.sh'
```
___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC4-DhT94MI3LrwPsuF:-OC4-DhT94MI3LrwPsuG:b-is6xzp) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L31)):*
> ```YAML
>       - 'crates/blockifier/**'
>       - 'crates/native_blockifier/**'
>       - 'scripts/build_native_blockifier.sh'
> ```

why? reexecution doesn't depend on native blockifier



_Code quote:_
```YAML
      - 'crates/native_blockifier/**'
      - 'scripts/build_native_blockifier.sh'
```
___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC4-l9u0B3ntOtV2Aaq:-OC4-l9u0B3ntOtV2Aar:b-fhc8ec) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L44)):*
> ```YAML
>   blockifier_reexecution:
>     runs-on: starkware-ubuntu-latest-medium
>     if: ${{ github.event_name == 'pull_request' }}
> ```

see above - don't run this workflow on `push` events at all, and remove this `if`



_Code quote:_
```YAML
if: ${{ github.event_name == 'pull_request' }}
```
___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC4-tUO1dx0P3whDIIT:-OC4-tUO1dx0P3whDIIU:b-o5x3pe) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L52)):*
> ```YAML
>         uses: "google-github-actions/auth@v2"
>         with:
>           credentials_json: ${{ secrets.SA_REEXECUTION_ARTIFACTS_READ_ACCESS_KEY }}
> ```

the point with public access was to allow running this CI without secrets.
otherwise, external PRs from external devs cannot run the CI.
why do you need this for read access?



_Code quote:_
```YAML
${{ secrets.SA_REEXECUTION_ARTIFACTS_READ_ACCESS_KEY }}
```
___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC40dzO55rK4VYlY_by:-OC40dzO55rK4VYlY_bz:bk764mj) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L57)):*
> ```YAML
>       - run: gcloud storage cp -r gs://reexecution_artifacts/$REEXECUTION_INPUT_FILES_PREFIX/resources/* ./crates/blockifier_reexecution/resources/
>       # Run blockifier re-execution tests.
>       - run: cargo test --release -p blockifier_reexecution -- --ignored
> ```

I [can see](https://github.com/starkware-libs/sequencer/actions/runs/11915409096/job/33205604267) that the reexecution itself *did not run*. the raw json tests ran, but that's it.

once you fix this, please check which is faster: with or without `--release`.
1. how much time required for compilation in both cases?
2. how much time required for running the test in both cases?



_Code quote:_
```YAML
- run: cargo test --release -p blockifier_reexecution -- --ignored
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1857)* status: 1 of 4 files reviewed, 12 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC4-4_E1Udjs6RsoYok:-OC4MSxIB2T-vCMvzqrm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do we want to run this CI on post-merge? I doubt it; it should only block PRs
</blockquote></details>

Done.
___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC4-2-O0pAPXaBuwczI:-OC4MS_fBoaksA9P6l8U:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L11)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

irrelevant (copied from somewhere?)
</blockquote></details>

Done.
___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 22 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC43VbDAwjCKyCxo5P9:-OC4MWFG5N64BErzRfT7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L22)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move this down (sort this list)
</blockquote></details>

Done.
___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC3zxyu4NlySrZVDq2B:-OC4B7ls35yPubqbjOG9:b-gfreok) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L26)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why should these three trigger this workflow?
</blockquote></details>

I basically copied everything from the blockifier CI, reasoning that if there's a reason to run the blockifier checks, then reexecution checks should also be run
___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC4-l9u0B3ntOtV2Aaq:-OC4MZ4G86tLW5Dp2piw:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L44)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above - don't run this workflow on `push` events at all, and remove this `if`
</blockquote></details>

Done.
___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC4-tUO1dx0P3whDIIT:-OC4M_tc-ox3TPxVFH7P:bbojpb3) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L52)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the point with public access was to allow running this CI without secrets.
otherwise, external PRs from external devs cannot run the CI.
why do you need this for read access?
</blockquote></details>

That's not what I recall; look at your request in the conversation.
___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC40dzO55rK4VYlY_by:-OC4Mq5B3ZvFwPxGCw8h:blqyx4v) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L57)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I [can see](https://github.com/starkware-libs/sequencer/actions/runs/11915409096/job/33205604267) that the reexecution itself *did not run*. the raw json tests ran, but that's it.

once you fix this, please check which is faster: with or without `--release`.
1. how much time required for compilation in both cases?
2. how much time required for running the test in both cases?
</blockquote></details>

OK, will check.

**Comment by aner-starkware** [comment]
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we now need a README.md file for this crate. Can you write one?
(it can be a separate PR)
the readme should cover:
1. All CLI commands and their meaning
2. How to run the RPC tests (using `TEST_URL=<ENDPOINT>`)
</blockquote></details>

OK, will do it in a separate PR.

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1857)* status: 0 of 4 files reviewed, 12 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/resources/offline_reexecution_files_prefix` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC40Ji88PcRBVbw97wr:-OC4O26P7VANLRtPSI7V:b9nim63) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/crates/blockifier_reexecution/resources/offline_reexecution_files_prefix#L1)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not that it matters much, but... where is this value from?
</blockquote></details>

Hash of some commit; probably already amended that commit or rebased, but the hash doesn't change (since it's the folder - need to change it manually)
___
*[`crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC3xWAzDhEfRoEUV1O5:-OC4OPfE2CI70nWnq-wr:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs#L170)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

also blocking because blocking self sometimes doesn't actually work
</blockquote></details>

Done.

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1857)* status: 0 of 4 files reviewed, 12 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`.github/workflows/blockifier_ci.yml` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC4-QBaDoS4tMenyqOz:-OC4OUBf2rG4atNjqIDn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/846e4ea7b8a9281a639673b250eaeea38e657fee/.github/workflows/blockifier_ci.yml#L57)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think this is still worth keeping. I know reexecution feature always activates this serde feature but we shouldn't assume this will be true forever IMO.
</blockquote></details>

Done.

**Comment by aner-starkware** [comment]
*[`.github/workflows/blockifier_reexecution_ci.yml` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC40dzO55rK4VYlY_by:-OC4PR9YEkHqQv87_WpD:b-5b7idu) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L57)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

OK, will check.
</blockquote></details>

Actually, I think it was reversed - the reexecution tests ran, but all other tests did not. Now all tests run... But I'll split the tests file (in a separate PR), so that it will make more sense.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1857)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC3zxyu4NlySrZVDq2B:-OC4TEzADBTxApjbd-67:b-eye5yi) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L26)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I basically copied everything from the blockifier CI, reasoning that if there's a reason to run the blockifier checks, then reexecution checks should also be run
</blockquote></details>

If there's a reason to run blockifier checks, then yes,
but 
1. changes in the blockifier CI are changes in the checks, not changes in the crate, so no reason to trigger reexecution checks
2. native blockifier is not a dependency of reexecution, so changes in the native blockifier shouldn't trigger reexecution - the blockifier CI also runs native blockifier stuff (actually, only the upload_artifacts workflow should really be triggered on changes to native blockifier, we can probably update the blockifier CI triggers to reflect this).

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1857)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC40dzO55rK4VYlY_by:-OC4VeYe3-yGpOn884hV:b-m2dnwv) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L57)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Actually, I think it was reversed - the reexecution tests ran, but all other tests did not. Now all tests run... But I'll split the tests file (in a separate PR), so that it will make more sense.
</blockquote></details>

without `--release`, compilation takes 3:20 and reexecution seems to take ~15 minutes.
also, [I don't see that the 0_13_1_1 case finished, but the tests seem to have passed](https://github.com/starkware-libs/sequencer/actions/runs/11918373327/job/33215653933)... why?
also, 15 minutes is a bit much, please try again with `--release`... hopefully it should decrease the runtime dramatically

**Comment by aner-starkware** [comment]
*[`.github/workflows/blockifier_reexecution_ci.yml` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC40dzO55rK4VYlY_by:-OC4Rdkp6zc8QyvEAQRt:b-v0erxk) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L57)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

without `--release`, compilation takes 3:20 and reexecution seems to take ~15 minutes.
also, [I don't see that the 0_13_1_1 case finished, but the tests seem to have passed](https://github.com/starkware-libs/sequencer/actions/runs/11918373327/job/33215653933)... why?
also, 15 minutes is a bit much, please try again with `--release`... hopefully it should decrease the runtime dramatically
</blockquote></details>

Without `--release`: compilation 4 minutes, tests 14 minutes (total: 18 minutes); this solution isn't scalable, if you test reexecution on more blocks then it will grow significantly...

With `--release`: compilation 10 minutes, tests 1 minute (total 11 minutes); this solution is more scalable since you can add many tests and it won't dramatically increase the time

**Comment by aner-starkware** [comment]
*[`.github/workflows/blockifier_reexecution_ci.yml` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC40dzO55rK4VYlY_by:-OC4YIJ68fqW8vlN2MSi:bqdur67) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L57)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

cool! let's go with --release then
</blockquote></details>

`test state_reader::raw_rpc_json_test::test_block_reexecution::case_03_v_0_13_1_1 ... ok`
Seems to have finished...

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1857)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC40dzO55rK4VYlY_by:-OC4YVfG1DnZiJ7PKEtJ:b-zectqs) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L57)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

`test state_reader::raw_rpc_json_test::test_block_reexecution::case_03_v_0_13_1_1 ... ok`
Seems to have finished...
</blockquote></details>

ah, missed that..

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1857)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC4-tUO1dx0P3whDIIT:-OC4p4ZR1mlAmoAt2q4B:b1qqoj5) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L52)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

That's not what I recall; look at your request in the conversation.
</blockquote></details>

discussed offline, we want a secret-less solution..

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1857)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1857)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC4-tUO1dx0P3whDIIT:-OCT0RzRBJ1egZuOdVA3:bnweif9) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L52)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

discussed offline, we want a secret-less solution..
</blockquote></details>

In the end continuing with secrets for now?

**Review by dorimedini-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-:-OCT1Mzj08MSxJH-Xq0S:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

___
*[`.github/workflows/blockifier_reexecution_ci.yml` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-OC4-tUO1dx0P3whDIIT:-OCT1GmF-G-wCCHBtyYT:b2nign6) ([raw file](https://github.com/starkware-libs/sequencer/blob/6261b647920dd6df5d7cbc91948473ddb581e0b6/.github/workflows/blockifier_reexecution_ci.yml#L52)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

In the end continuing with secrets for now?
</blockquote></details>

yes

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1857#-:-OCTBKc79h9tJ1ZWSxUB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
