### PR TITLE
Merge main-v0.13.2 into main

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/589)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
[Src](https://github.com/starkware-libs/blockifier/compare/df672bc5a755e00cf30232464de6268082e78904..main-v0.13.2#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542) [Dst](https://github.com/starkware-libs/blockifier/compare/df672bc5a755e00cf30232464de6268082e78904..main#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542) Cargo.toml

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 3 of 7 files at r3, 15 of 40 files at r4, 28 of 28 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/589)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/589#-:-O5FExPHBUBhwi9AwgKX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware, @Yael-Starkware, and @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/589)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware, @Yael-Starkware, and @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 6 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/589)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware, @Yael-Starkware, and @Yoni-Starkware)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/589)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @Itay-Tsabary-Starkware, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/starknet_sierra_compile/Cargo.toml` line 3 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/589#-O5HzxUd7-zLs0WsZ56S:-O5HzxUe5-_UuIgbueJU:b-z2ksv4) ([raw file](https://github.com/starkware-libs/sequencer/blob/41c19186724685074850f40928631bcce0b47cee/crates/starknet_sierra_compile/Cargo.toml#L3)):*
> ```TOML
> [package]
> <<<<<<< HEAD
> name = "starknet_sierra_compile"
> ```

Why was it removed?



_Code quote:_
```TOML
name = "starknet_sierra_compile"
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/589)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware, @noaov1, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/starknet_sierra_compile/Cargo.toml` line 3 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/589#-O5HzxUd7-zLs0WsZ56S:-O5I-ncxD4KsyNAEifmW:b-sy6uze) ([raw file](https://github.com/starkware-libs/sequencer/blob/41c19186724685074850f40928631bcce0b47cee/crates/starknet_sierra_compile/Cargo.toml#L3)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why was it removed?
</blockquote></details>

it wasn't, it's sorted now

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/589)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware, @Yael-Starkware, and @Yoni-Starkware)

**Pull request merged**
