### PR TITLE
chore(starknet_gateway): create sync state reader infra with todos

### PR DESCRIPTION
**Pull request by noamsp-starkware**

### CODE REVIEW

**Comment by noamsp-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2754?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2755** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2755?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2754** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2754?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2754?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2662** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2662?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2537** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2537?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2538](https://github.com/starkware-libs/sequencer/pull/2538) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2538?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2531** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2531?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2515** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2515?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2754)* status: all files reviewed, 4 unresolved discussions (waiting on @noamsp-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2754#-OESp7U_5elgSgQEkmIB:-OESp7U_5elgSgQEkmIC:b3l97w0) (no related file):*
@alonh5 should review this as well. Please send it to him in slack
___
*[`crates/starknet_state_sync_types/src/communication.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2754#-OESqXFO6cHdDTgw-XWc:-OESqXFO6cHdDTgw-XWd:b-hfavu7) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f4bcbd995b30bf2a4d41d695b6190e474aa84a0/crates/starknet_state_sync_types/src/communication.rs#L37)):*
> ```XML
>     ) -> StateSyncClientResult<()>;
> 
>     // TODO: add get_storage_at for BlockifierStateReader trait
> ```

This sounds like you want to add this method to the BlockifierStateReader trait. Rephrase it "for SyncStateReader"
___
*[`crates/starknet_gateway/src/sync_state_reader.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2754#-OESpZFc0q_BkPSh23wR:-OESpZFc0q_BkPSh23wS:b9q9r6m) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f4bcbd995b30bf2a4d41d695b6190e474aa84a0/crates/starknet_gateway/src/sync_state_reader.rs#L14)):*
> ```XML
> struct SyncStateReader {
>     block_number: BlockNumber,
>     shared_state_sync_client: SharedStateSyncClient,
> ```

You can name this state_sync_client
___
*[`crates/starknet_gateway/src/sync_state_reader.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2754#-OESpdA9-TR8dqkXaKwh:-OESpdA9-TR8dqkXaKwi:boytvse) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f4bcbd995b30bf2a4d41d695b6190e474aa84a0/crates/starknet_gateway/src/sync_state_reader.rs#L19)):*
> ```XML
> impl SyncStateReader {
>     pub fn from_number(
>         shared_state_sync_client: &SharedStateSyncClient,
> ```

In rust we usually don't take by reference what we then clone, we consume it. This allows the caller to maybe pass to us an object that they don't need anymore and save the clone

@alonh5 FYI since it is copied from the RpcStateReader

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2754)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @ShahakShama)

___
*[`crates/starknet_gateway/src/sync_state_reader.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2754#-OESpZFc0q_BkPSh23wR:-OETMdek-qqFCd2gh488:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f4bcbd995b30bf2a4d41d695b6190e474aa84a0/crates/starknet_gateway/src/sync_state_reader.rs#L14)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You can name this state_sync_client
</blockquote></details>

Done.
___
*[`crates/starknet_gateway/src/sync_state_reader.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2754#-OESpdA9-TR8dqkXaKwh:-OETMiPN2XPhqHUepiXM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f4bcbd995b30bf2a4d41d695b6190e474aa84a0/crates/starknet_gateway/src/sync_state_reader.rs#L19)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

In rust we usually don't take by reference what we then clone, we consume it. This allows the caller to maybe pass to us an object that they don't need anymore and save the clone

@alonh5 FYI since it is copied from the RpcStateReader
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync_types/src/communication.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2754#-OESqXFO6cHdDTgw-XWc:-OETMjwiB-YGMv4abCLz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f4bcbd995b30bf2a4d41d695b6190e474aa84a0/crates/starknet_state_sync_types/src/communication.rs#L37)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This sounds like you want to add this method to the BlockifierStateReader trait. Rephrase it "for SyncStateReader"
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2754#-:-OETNooM9EOzSx9vWRKQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noamsp-starkware)

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2754)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2754#-OESp7U_5elgSgQEkmIB:-OETqwanBPrCDLWubKMk:bir1gre) (no related file):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

@alonh5 should review this as well. Please send it to him in slack
</blockquote></details>

I spoke with @alonh5; his team's review will be required for the PRs that actually integrate the sync state reader into gateway. resolving this.

**Comment by noamsp-starkware** [comment]
### Merge activity

* **Dec 22, 3:18 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2754).

**Pull request merged**
