### PR TITLE
build(fee): define valid resources bounds enum

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/503)

### CODE REVIEW

**Comment by nimrod-starkware** [comment]
* **#506** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/506?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#505** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/505?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#504** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/504?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#503** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/503?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nimrod-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/503)* status: all files reviewed, 8 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/503#-O4jA9DtEVWVGsCUCCjg:-O4jA9DtEVWVGsCUCCjh:b784wkz) (no related file):*
you added `todo!`s here, so please open a python side PR (I am concerned about the OS test mainly)

___
___
*[`crates/starknet_api/src/transaction.rs` line 870 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/503#-O4j8aUw257Ta8f9Bh8C:-O4j8aUw257Ta8f9Bh8D:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6c1477fbbbfc501e5c23c9e3b12896cd678c6f3/crates/starknet_api/src/transaction.rs#L870)):*
> ```XML
>     #[serde(rename = "L2_GAS")]
>     L2Gas,
>     L1DataGas,
> ```





_Suggestion:_
```XML
    #[serde(rename = "L2_GAS")]
    L2Gas,
    #[serde(rename = "L1_DATA_GAS")]
    L1DataGas,
```
___
*[`crates/starknet_api/src/transaction.rs` line 891 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/503#-O4j8hOVA7NOT4WkJTjK:-O4j8hOVA7NOT4WkJTjL:b1zlm3q) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6c1477fbbbfc501e5c23c9e3b12896cd678c6f3/crates/starknet_api/src/transaction.rs#L891)):*
> ```XML
>     pub fn is_zero(&self) -> bool {
>         self.max_amount == 0 && self.max_price_per_unit == 0
>     }
> ```

name is a bit ambiguous - if *one* of the two fields is zero, the effective bound is zero.
consider another name / a docstring?



_Code quote:_
```XML
    pub fn is_zero(&self) -> bool {
        self.max_amount == 0 && self.max_price_per_unit == 0
    }
```
___
*[`crates/starknet_api/src/transaction.rs` line 953 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/503#-O4j96mlDK6lkm_sOjBj:-O4j96mlDK6lkm_sOjBk:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6c1477fbbbfc501e5c23c9e3b12896cd678c6f3/crates/starknet_api/src/transaction.rs#L953)):*
> ```XML
> 
> pub enum ValidResourceBounds {
>     L1Gas(ResourceBounds), // Pre 0.13.3. L2 bounds are signed but never used.
> ```





_Suggestion:_
```XML
L1Gas(ResourceBounds), // Pre 0.13.3. Only L1 gas. L2 bounds are signed but never used.
```
___
*[`crates/starknet_api/src/transaction.rs` line 961 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/503#-O4j99EZ0VCa-R5QjxrY:-O4j99EZ0VCa-R5QjxrZ:bb26myb) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6c1477fbbbfc501e5c23c9e3b12896cd678c6f3/crates/starknet_api/src/transaction.rs#L961)):*
> ```XML
>     pub l2_gas: ResourceBounds,
>     pub l1_data_gas: ResourceBounds,
> }
> ```

define and implement this, to enforce the connection between `AllResourceBounds` and the `Resource` enum



_Suggestion:_
```XML
pub struct AllResourceBounds {
    pub l1_gas: ResourceBounds,
    pub l2_gas: ResourceBounds,
    pub l1_data_gas: ResourceBounds,
}

impl AllResourceBounds {
    fn get_bound(&self, resource: Resource) -> ResourceBounds { ... }
}
```
___
*[`crates/starknet_api/src/transaction.rs` line 967 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/503#-O4j9SnU-AloZ3jo86vl:-O4j9SnU-AloZ3jo86vm:b-oynrmb) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6c1477fbbbfc501e5c23c9e3b12896cd678c6f3/crates/starknet_api/src/transaction.rs#L967)):*
> ```XML
>     fn try_from(
>         raw_resource_bounds: HashMap<Resource, ResourceBounds>,
>     ) -> Result<Self, Self::Error> {
> ```

suggestion: while the `ResourceBoundsMapping` is still alive, make it clear that it converts to the new type.
may be useful in refactoring.
WDYT? (non-blocking, you may have other design plans)



_Suggestion:_
```XML
impl TryFrom<ResourceBoundsMapping> for ValidResourceBounds {
    type Error = StarknetApiError;
    fn try_from(
        raw_resource_bounds: ResourceBoundsMapping,
    ) -> Result<Self, Self::Error> {
```
___
*[`crates/starknet_api/src/transaction.rs` line 984 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/503#-O4j9isE49u1Pth2Jiyc:-O4j9isE49u1Pth2Jiyd:b-d8sazg) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6c1477fbbbfc501e5c23c9e3b12896cd678c6f3/crates/starknet_api/src/transaction.rs#L984)):*
> ```XML
>                             "{:?}",
>                             raw_resource_bounds
>                         )))
> ```

more information please



_Suggestion:_
```XML
                        Err(StarknetApiError::InvalidResourceMappingInitializer(format!(
                            "Missing DA gas bound, but L2 gas bound is not zero: {:?}",
                            raw_resource_bounds
                        )))
```
___
*[`crates/starknet_api/src/transaction.rs` line 984 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/503#-O4j9p4f9TZoKDju5rug:-O4j9p4f9TZoKDju5ruh:b-9igqll) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6c1477fbbbfc501e5c23c9e3b12896cd678c6f3/crates/starknet_api/src/transaction.rs#L984)):*
> ```XML
>                             "{:?}",
>                             raw_resource_bounds
>                         )))
> ```

I prefer inlining the variable in the formatted string (non-blocking), it is more readable when you have several variables in the string



_Suggestion:_
```XML
                        Err(StarknetApiError::InvalidResourceMappingInitializer(format!(
                            "{raw_resource_bounds:?}"
                        )))
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/503)* status: all files reviewed, 8 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/503#-O4jA9DtEVWVGsCUCCjg:-O4jBKB7BABMz-Rb_9Lo:b-rol3vn) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you added `todo!`s here, so please open a python side PR (I am concerned about the OS test mainly)
</blockquote></details>

you can open such a PR for the top of your stack if you want, maybe better

___

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/503)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/starknet_api/src/transaction.rs` line 870 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/503#-O4j8aUw257Ta8f9Bh8C:-O4jGwkb3nYtrqbjyPP5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6c1477fbbbfc501e5c23c9e3b12896cd678c6f3/crates/starknet_api/src/transaction.rs#L870)):*
> ```XML
>     #[serde(rename = "L2_GAS")]
>     L2Gas,
>     L1DataGas,
> ```

Done.
___
*[`crates/starknet_api/src/transaction.rs` line 891 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/503#-O4j8hOVA7NOT4WkJTjK:-O4jHBPV-LB9NQ7ur7BM:b-zuwjf) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6c1477fbbbfc501e5c23c9e3b12896cd678c6f3/crates/starknet_api/src/transaction.rs#L891)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

name is a bit ambiguous - if *one* of the two fields is zero, the effective bound is zero.
consider another name / a docstring?
</blockquote></details>

added a docstring
___
*[`crates/starknet_api/src/transaction.rs` line 953 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/503#-O4j96mlDK6lkm_sOjBj:-O4jHlNE4QYwcFbde1xT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6c1477fbbbfc501e5c23c9e3b12896cd678c6f3/crates/starknet_api/src/transaction.rs#L953)):*
> ```XML
> 
> pub enum ValidResourceBounds {
>     L1Gas(ResourceBounds), // Pre 0.13.3. L2 bounds are signed but never used.
> ```

Done.
___
*[`crates/starknet_api/src/transaction.rs` line 961 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/503#-O4j99EZ0VCa-R5QjxrY:-O4jIBD10rId5-A9R-v5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6c1477fbbbfc501e5c23c9e3b12896cd678c6f3/crates/starknet_api/src/transaction.rs#L961)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

define and implement this, to enforce the connection between `AllResourceBounds` and the `Resource` enum
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/transaction.rs` line 967 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/503#-O4j9SnU-AloZ3jo86vl:-O4jIIib31mFF3XWdzao:b-oyylq2) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6c1477fbbbfc501e5c23c9e3b12896cd678c6f3/crates/starknet_api/src/transaction.rs#L967)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

suggestion: while the `ResourceBoundsMapping` is still alive, make it clear that it converts to the new type.
may be useful in refactoring.
WDYT? (non-blocking, you may have other design plans)
</blockquote></details>

I want to use `ResourceBoundsMapping` as little as possible (it will be easier to remove it later)...
___
*[`crates/starknet_api/src/transaction.rs` line 984 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/503#-O4j9p4f9TZoKDju5rug:-O4jIdpICer8JIykKx0C:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6c1477fbbbfc501e5c23c9e3b12896cd678c6f3/crates/starknet_api/src/transaction.rs#L984)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I prefer inlining the variable in the formatted string (non-blocking), it is more readable when you have several variables in the string
</blockquote></details>

Done
___
*[`crates/starknet_api/src/transaction.rs` line 984 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/503#-O4j9isE49u1Pth2Jiyc:-O4jIu7nAqoYN54vznAE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6c1477fbbbfc501e5c23c9e3b12896cd678c6f3/crates/starknet_api/src/transaction.rs#L984)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

more information please
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/503)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/starknet_api/src/transaction.rs` line 967 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/503#-O4j9SnU-AloZ3jo86vl:-O4jTNxm-_h9Jzbm8yZT:bx748wl) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6c1477fbbbfc501e5c23c9e3b12896cd678c6f3/crates/starknet_api/src/transaction.rs#L967)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I want to use `ResourceBoundsMapping` as little as possible (it will be easier to remove it later)...
</blockquote></details>

but this `TryFrom` is coupled to this type. enforcing this coupling will keep code stable in intermediate phases, and the final search for usages will remind you to update this to the relevant input type / move the logic to the general tx deserialization code / delete this `TryFrom` entirely

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/503)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

___
*[`crates/starknet_api/src/transaction.rs` line 967 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/503#-O4j9SnU-AloZ3jo86vl:-O4jk8VB23dLDD_YIdhq:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6c1477fbbbfc501e5c23c9e3b12896cd678c6f3/crates/starknet_api/src/transaction.rs#L967)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

but this `TryFrom` is coupled to this type. enforcing this coupling will keep code stable in intermediate phases, and the final search for usages will remind you to update this to the relevant input type / move the logic to the general tx deserialization code / delete this `TryFrom` entirely
</blockquote></details>

Done

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/503)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/starknet_api/src/transaction.rs` line 967 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/503#-O4j9SnU-AloZ3jo86vl:-O4jleKg7lyvyEC2kO0o:bvwhitd) ([raw file](https://github.com/starkware-libs/sequencer/blob/d6c1477fbbbfc501e5c23c9e3b12896cd678c6f3/crates/starknet_api/src/transaction.rs#L967)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done
</blockquote></details>

pushed?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/503)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/503)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/503#-:-O57QV7x2Nz3Jq9_Z5ux:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Comment by nimrod-starkware** [comment]
### Merge activity

* **Aug 25, 3:32 AM EDT**: @nimrod-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/503).

**Pull request merged**
