### PR TITLE
feat(starknet_gateway_types,starknet_http_server): move spec error conversion to the http server

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Comment by yair-starkware** [comment]
* **#2904** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2904?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2904?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2904)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_http_server/src/errors.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2904#-OEs7g6n4y5xni_cQ2m0:-OEs7g6n4y5xni_cQ2m1:b-1wn7md) ([raw file](https://github.com/starkware-libs/sequencer/blob/25a2089aa552679e215ce726b085764e5bdfbd47/crates/starknet_http_server/src/errors.rs#L33)):*
> ```XML
>     let general_rpc_error = match err {
>         GatewayClientError::ClientError(e) => {
>             error!("Got a gateway client: {}", e);
> ```

`Encountered a ClientError`



_Code quote:_
```XML
Got a gateway client
```
___
*[`crates/starknet_http_server/src/errors.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2904#-OEs7zzg-pXfJ1WnWqz7:-OEs7zzg-pXfJ1WnWqz8:bjsja1p) ([raw file](https://github.com/starkware-libs/sequencer/blob/25a2089aa552679e215ce726b085764e5bdfbd47/crates/starknet_http_server/src/errors.rs#L43)):*
> ```XML
>             source,
>             p2p_message_metadata: _,
>         }) => {
> ```

Please add a todo to `into_rpc()` on the entirety of `GatewayError`, not just the `source` member.



_Code quote:_
```XML
        GatewayClientError::GatewayError(GatewayError::GatewaySpecError {
            source,
            p2p_message_metadata: _,
        }) => {
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2904)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @Itay-Tsabary-Starkware)

___
*[`crates/starknet_http_server/src/errors.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2904#-OEs7g6n4y5xni_cQ2m0:-OEsAxCTDHRaO4uENXTr:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/557330fdfd82a1ea000e8ca1e7365fee2f38c4d3/crates/starknet_http_server/src/errors.rs#L33)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

`Encountered a ClientError`
</blockquote></details>

Done.
___
*[`crates/starknet_http_server/src/errors.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2904#-OEs7zzg-pXfJ1WnWqz7:-OEsBCOl8DSwyb4MOxqP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/557330fdfd82a1ea000e8ca1e7365fee2f38c4d3/crates/starknet_http_server/src/errors.rs#L43)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add a todo to `into_rpc()` on the entirety of `GatewayError`, not just the `source` member.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2904#-:-OEsTAhv9xT2Xz3rmwyt:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_http_server/src/errors.rs` line 44 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2904#-OEsSg2e6--G8tq4cVbt:-OEsSg2e6--G8tq4cVbu:bcx38th) ([raw file](https://github.com/starkware-libs/sequencer/blob/872a99ecdcc79d3b0f11c1f3676e313fcf5d6577/crates/starknet_http_server/src/errors.rs#L44)):*
> ```XML
>             p2p_message_metadata: _,
>         }) => {
>             // TODO(Itay): Add the p2p_message_metadata to the error response.
> ```

1. I go by `Tsabary` :-)
2. The todo is for you :-)

Non-blocking, but please change :thumbsup: 



_Code quote:_
```XML
// TODO(Itay): Add the p2p_message_metadata to the error response.
```

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2904)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @yair-starkware)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2904#-:-OExDcoK39evEBaLoUT2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
