### PR TITLE
refactor(mempool): delete thin tx struct

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/377)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/377)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool_types/src/mempool_types.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/377#-O40hl7E2oGgLanPl2V-:-O40hl7E2oGgLanPl2V0:bjewstl) ([raw file](https://github.com/starkware-libs/sequencer/blob/58e44145c4e02a5aab1969a875c40dd233452c03/crates/mempool_types/src/mempool_types.rs#L38)):*
> ```XML
> pub type MempoolResult<T> = Result<T, MempoolError>;
> 
> pub fn create_internal_tx(
> ```

Move to test utils? Also, it's weird it's only invoke.



_Code quote:_
```XML
create_internal_tx
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/377)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/377#-O40k4qpE1ziEgQx8NOS:-O40k4qpE1ziEgQx8NOT:b-mrbdki) (no related file):*
Deletes `ThinTx`.

___

**Review by giladchase — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/377)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/377#-O40k4qpE1ziEgQx8NOS:-O4Jqdbp9o-xPalkEfJt:b-w3svd8) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Deletes `ThinTx`.
</blockquote></details>

Renaming TransactionReference -> ThinTransaction is the next step?

___

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/377)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/377#-O40k4qpE1ziEgQx8NOS:-O4K9lWN2EjEnb0fp-ki:b2nhswy) (no related file):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Renaming TransactionReference -> ThinTransaction is the next step?
</blockquote></details>

Yes

___
___
*[`crates/mempool_types/src/mempool_types.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/377#-O40hl7E2oGgLanPl2V-:-O4KD03jAn5swp6vNh95:b-8r9cmv) ([raw file](https://github.com/starkware-libs/sequencer/blob/58e44145c4e02a5aab1969a875c40dd233452c03/crates/mempool_types/src/mempool_types.rs#L38)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move to test utils? Also, it's weird it's only invoke.
</blockquote></details>

Done.

@ArniStarkware will add a converter from rpcTx to executable tx.

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/377)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/Cargo.toml` line 22 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/377#-O4KQrNp7x9nD1hgkqUB:-O4KQrNp7x9nD1hgkqUC:b6dnmcn) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0f12d5fc55f716c9f1dd83f90fbb13f0e31662e/crates/mempool/Cargo.toml#L22)):*
> ```TOML
> assert_matches.workspace = true
> itertools.workspace = true
> mempool_test_utils.workspace = true
> ```

what makes it needed?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/377)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @giladchase)

___
*[`crates/mempool/Cargo.toml` line 22 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/377#-O4KQrNp7x9nD1hgkqUB:-O4KSvOo3HuqOEIcuZFr:b1gcszj) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0f12d5fc55f716c9f1dd83f90fbb13f0e31662e/crates/mempool/Cargo.toml#L22)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

what makes it needed?
</blockquote></details>

I moved the create_executable_tx to mempool_test_utils, following Elin's request.

**Review by elintul — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/377)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/377#-:-O4f7SBp4K442UR7QV__:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway_test.rs` line 68 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/377#-O4i_QLh5HPEux6abh2w:-O4i_QLh5HPEux6abh2x:b-o5dhxj) ([raw file](https://github.com/starkware-libs/sequencer/blob/67cec253691072fb302cf11f17f6cb425985a7f9/crates/gateway/src/gateway_test.rs#L68)):*
> ```XML
>         .once()
>         .with(eq(MempoolInput {
>             tx: create_executable_tx(sender_address, tx_hash, *tx.tip(), *tx.nonce()),
> ```

Add a todo on my name.



_Suggestion:_
```XML
// TODO(Arni): Use external_to_executable_tx instead of `create_executable_tx`. Consider creating a `convertor for testing` that does not do the compilation.
tx: create_executable_tx(sender_address, tx_hash, *tx.tip(), *tx.nonce()),
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/377)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @giladchase)

___
*[`crates/gateway/src/gateway_test.rs` line 68 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/377#-O4i_QLh5HPEux6abh2w:-O4ild7X8geUGCmd59iH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/67cec253691072fb302cf11f17f6cb425985a7f9/crates/gateway/src/gateway_test.rs#L68)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Add a todo on my name.
</blockquote></details>

Done.

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/377)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

**Pull request merged**
