### PR TITLE
chore(committer): renamed committer to starknet_patricia

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/405)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/405)* status: 0 of 72 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @aner-starkware, and @TzahiTaub)

___
*[`Cargo.toml` line 171 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/405#-O44qvpI-HU_Jv2-YpR-:-O44qvpI-HU_Jv2-YpR0:b2e2io6) ([raw file](https://github.com/starkware-libs/sequencer/blob/17bec500602c65e249e78c3c337a4e0fe36c1a3e/Cargo.toml#L171)):*
> ```TOML
> starknet_api = { path = "crates/starknet_api", version = "0.13.0-rc.0" }
> starknet_client = { path = "crates/starknet_client", version = "0.4.0-rc.0" }
> starknet_committer = { path = "crates/starknet_committer", version = "0.1.0-rc.0" }
> ```

this was missing before... see other Cargo.tomls that used `path = "../starknet_committer"` instead of `workspace = true`



_Code quote:_
```TOML
starknet_committer = { path = "crates/starknet_committer", version = "0.1.0-rc.0" }
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/405)* status: 0 of 73 files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @TzahiTaub)

___
*[`commitlint.config.js` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/405#-O44rK_K0hGcuYyy4IWM:-O44rK_K0hGcuYyy4IWN:b-56psk7) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a4529c6ac03eb336789aebb6de42534a85dcb6b/commitlint.config.js#L27)):*
> ```JavaScript
>             'blockifier',
>             'ci',
>             'committer',
> ```

unrelated, but required to scope this commit



_Code quote:_
```JavaScript
'committer'
```

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> Reviewed 72 of 72 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/405)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/405#-O44sihi0bcHvU-hELGe:-O451zI96TKuMCiGPCgh:b-oecw1h) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[py side](https://reviewable.io/reviews/starkware-industries/starkware/35732)
</blockquote></details>

more instances of `committer` which probably need to be changed to `starknet_patricia`:
https://github.com/starkware-libs/sequencer/blob/9a4529c6ac03eb336789aebb6de42534a85dcb6b/commitlint.config.js#L27
https://github.com/starkware-libs/sequencer/blob/abf106eb1eca71f975cf7dee0ed81822f7cc30be/.github/workflows/committer_ci.yml#L14
https://github.com/starkware-libs/sequencer/blob/abf106eb1eca71f975cf7dee0ed81822f7cc30be/.github/workflows/committer_ci.yml#L29

___
___
*[`commitlint.config.js` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/405#-O44rK_K0hGcuYyy4IWM:-O45-js65k56ndIT8eYW:b-8zdsmt) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a4529c6ac03eb336789aebb6de42534a85dcb6b/commitlint.config.js#L27)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

unrelated, but required to scope this commit
</blockquote></details>

don't you need to add `starknet_patricia`?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/405)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/405#-O44sihi0bcHvU-hELGe:-O45ML0U86AREG104nOD:bd5l6mr) (no related file):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

more instances of `committer` which probably need to be changed to `starknet_patricia`:
https://github.com/starkware-libs/sequencer/blob/9a4529c6ac03eb336789aebb6de42534a85dcb6b/commitlint.config.js#L27
https://github.com/starkware-libs/sequencer/blob/abf106eb1eca71f975cf7dee0ed81822f7cc30be/.github/workflows/committer_ci.yml#L14
https://github.com/starkware-libs/sequencer/blob/abf106eb1eca71f975cf7dee0ed81822f7cc30be/.github/workflows/committer_ci.yml#L29
</blockquote></details>

thanks!

___
___
*[`commitlint.config.js` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/405#-O44rK_K0hGcuYyy4IWM:-O45LlQO46RkfhKjaGLF:bbge762) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a4529c6ac03eb336789aebb6de42534a85dcb6b/commitlint.config.js#L27)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

don't you need to add `starknet_patricia`?
</blockquote></details>

there is a difference between "project name" and "crate name".
starknet_patricia, starknet_committer and committer_cli are all crates in the committer project.
I think it's informative to keep a simple `committer` scope here

**Review by TzahiTaub — APPROVED** [review]
> Reviewed 72 of 72 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/405)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @dorimedini-starkware)

___
*[`Cargo.lock` line 1948 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/405#-O45Po8y0ZwaDj8mlnSb:-O45Po8zBxbn0G6jkkAf:btvwexa) ([raw file](https://github.com/starkware-libs/sequencer/blob/a18b1ba1943fdcf8cc3aa2619006e4bb77d745a1/Cargo.lock#L1948)):*
> ```TOML
> 
> [[package]]
> name = "committer_cli"
> ```

seems like this should be changed to be consistent with the other packages (not here and not in this PR).



_Suggestion:_
```TOML
starknet_committer_cli
```
___
*[`commitlint.config.js` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/405#-O44rK_K0hGcuYyy4IWM:-O45R-uOBVOmT1U3M16H:b-8fx2u7) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a4529c6ac03eb336789aebb6de42534a85dcb6b/commitlint.config.js#L27)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there is a difference between "project name" and "crate name".
starknet_patricia, starknet_committer and committer_cli are all crates in the committer project.
I think it's informative to keep a simple `committer` scope here
</blockquote></details>

:+1:

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/405#-:-O45X9Gc9CaPKBoCXBvt:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @aner-starkware)

**Review by amosStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/405)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
