### PR TITLE
test(blockifier_reexecution): add support for declare and deploy account tx with rpc

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
test: blockifier reececution test getting deploy account tx with rpc

build: blockifier reexecution add support for declare tx

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
* **#1604** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1604?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 132 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1604#-OAIhosY247ICXDbnLQ5:-OAIhosY247ICXDbnLQ6:b-fxzv0m) ([raw file](https://github.com/starkware-libs/sequencer/blob/df80f6ed4f9c7b7e86b4a3b89db4657056c05444/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L132)):*
> ```XML
> pub fn test_get_deploy_account_tx_by_hash(block_number: u64, tx_hash: &str, version: u64) {
>     // Create StateReader with block number that contain the deploy account tx.
>     use starknet_api::transaction::DeployAccountTransaction;
> ```

move to top



_Code quote:_
```XML
 use starknet_api::transaction::DeployAccountTransaction;
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1604)* status: all files reviewed, 6 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1604#-OAIdLKJ3tp2OW0RA77m:-OAIdLKJ3tp2OW0RA77n:bkjjwbo) ([raw file](https://github.com/starkware-libs/sequencer/blob/df80f6ed4f9c7b7e86b4a3b89db4657056c05444/crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs#L113)):*
> ```XML
> 
>     assert_matches!(declare_tx_v3, Transaction::Declare(DeclareTransaction::V3(..)));
> }
> ```

suggestion (non-blocking).
you can do something similar in the deploy_account txs test



_Suggestion:_
```XML
#[rstest]
fn deserialize_declare_txs(#[values("declare_v1", "declare_v2", "declare_v3")] key: &str) {
    let declare_tx = deserialize_transaction_json_to_starknet_api_tx(
        read_json_file("raw_rpc_json_objects/transactions.json")[key].clone(),
    )
    .expect(format!("Failed to deserialize {key} tx"));

    match key {
        "declare_v1" => assert_matches!(declare_tx, Transaction::Declare(DeclareTransaction::V1(..))),
        "declare_v2" => assert_matches!(declare_tx, Transaction::Declare(DeclareTransaction::V2(..))),
        "declare_v3" => assert_matches!(declare_tx, Transaction::Declare(DeclareTransaction::V3(..))),
        _ => panic!("Unknown scenario '{key}'"),
    }
}
```
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1604#-OAIh6mmBD6BfU7LGQVB:-OAIh6mmBD6BfU7LGQVC:b-rse9e9) ([raw file](https://github.com/starkware-libs/sequencer/blob/df80f6ed4f9c7b7e86b4a3b89db4657056c05444/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L130)):*
> ```XML
>     case(EXAMPLE_DEPLOY_ACCOUNT_V3_BLOCK_NUMBER, EXAMPLE_DEPLOY_ACCOUNT_V3_TX_HASH, 3)
> )]
> pub fn test_get_deploy_account_tx_by_hash(block_number: u64, tx_hash: &str, version: u64) {
> ```

this is the standard syntax for test cases in our repo



_Suggestion:_
```XML
#[rstest]
#[case(EXAMPLE_DEPLOY_ACCOUNT_V1_BLOCK_NUMBER, EXAMPLE_DEPLOY_ACCOUNT_V1_TX_HASH, 1)]
#[case(EXAMPLE_DEPLOY_ACCOUNT_V3_BLOCK_NUMBER, EXAMPLE_DEPLOY_ACCOUNT_V3_TX_HASH, 3)]
pub fn test_get_deploy_account_tx_by_hash(#[case] block_number: u64, #[case] tx_hash: &str, #[case] version: u64) {
```
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1604#-OAIj7me9jIZbqLnpzq3:-OAIj7me9jIZbqLnpzq4:b9iqwap) ([raw file](https://github.com/starkware-libs/sequencer/blob/df80f6ed4f9c7b7e86b4a3b89db4657056c05444/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L130)):*
> ```XML
>     case(EXAMPLE_DEPLOY_ACCOUNT_V3_BLOCK_NUMBER, EXAMPLE_DEPLOY_ACCOUNT_V3_TX_HASH, 3)
> )]
> pub fn test_get_deploy_account_tx_by_hash(block_number: u64, tx_hash: &str, version: u64) {
> ```

we have a type for this.
you will not be able to `match` (working on a fix) but use if-else for now



_Suggestion:_
```XML
version: TransactionVersion
```
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 153 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1604#-OAIjf238Jr5fQRD_fuF:-OAIjf238Jr5fQRD_fuG:byr4ffv) ([raw file](https://github.com/starkware-libs/sequencer/blob/df80f6ed4f9c7b7e86b4a3b89db4657056c05444/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L153)):*
> ```XML
>     case(EXAMPLE_DECLARE_V2_BLOCK_NUMBER, EXAMPLE_DECLARE_V2_TX_HASH, 2),
>     case(EXAMPLE_DECLARE_V3_BLOCK_NUMBER, EXAMPLE_DECLARE_V3_TX_HASH, 3)
> )]
> ```

see above



_Code quote:_
```XML
#[rstest(
    block_number,
    tx_hash,
    expected_version,
    case(EXAMPLE_DECLARE_V1_BLOCK_NUMBER, EXAMPLE_DECLARE_V1_TX_HASH, 1),
    case(EXAMPLE_DECLARE_V2_BLOCK_NUMBER, EXAMPLE_DECLARE_V2_TX_HASH, 2),
    case(EXAMPLE_DECLARE_V3_BLOCK_NUMBER, EXAMPLE_DECLARE_V3_TX_HASH, 3)
)]
```
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1604#-OAIjgWe6Qmr3Tp66gH_:-OAIjgWe6Qmr3Tp66gHa:byr4ffv) ([raw file](https://github.com/starkware-libs/sequencer/blob/df80f6ed4f9c7b7e86b4a3b89db4657056c05444/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L154)):*
> ```XML
>     case(EXAMPLE_DECLARE_V3_BLOCK_NUMBER, EXAMPLE_DECLARE_V3_TX_HASH, 3)
> )]
> pub fn test_get_declare_tx_by_hash(block_number: u64, tx_hash: &str, expected_version: u64) {
> ```

see above



_Suggestion:_
```XML
expected_version: TransactionVersion)
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1604)* status: all files reviewed, 7 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1604#-OAJIjzU4Rs5xBIGW5qJ:-OAJIjzV2INQdFt_g5yD:bhmmoq9) (no related file):*
please amend the commit message to start with `test(blockifier_reexecution): ...`

___

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1604)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1604#-OAJIjzU4Rs5xBIGW5qJ:-OAMSO_T4liQOfUvo50I:b-896fix) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please amend the commit message to start with `test(blockifier_reexecution): ...`
</blockquote></details>

Done.

___
___
*[`crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1604#-OAIdLKJ3tp2OW0RA77m:-OAMSdCB6a6qcwrDmAK9:bb7lbs2) ([raw file](https://github.com/starkware-libs/sequencer/blob/df80f6ed4f9c7b7e86b4a3b89db4657056c05444/crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs#L113)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

suggestion (non-blocking).
you can do something similar in the deploy_account txs test
</blockquote></details>

nice
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1604#-OAIh6mmBD6BfU7LGQVB:-OAMYGNT-VJUM6BHo8Px:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/df80f6ed4f9c7b7e86b4a3b89db4657056c05444/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L130)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is the standard syntax for test cases in our repo
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1604#-OAIj7me9jIZbqLnpzq3:-OAMZkQN3oQLyfnjQjV5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/df80f6ed4f9c7b7e86b4a3b89db4657056c05444/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L130)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we have a type for this.
you will not be able to `match` (working on a fix) but use if-else for now
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 132 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1604#-OAIhosY247ICXDbnLQ5:-OAMZsHh4m661R6feT70:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/df80f6ed4f9c7b7e86b4a3b89db4657056c05444/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L132)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

move to top
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 153 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1604#-OAIjf238Jr5fQRD_fuF:-OAMZt075zIwG7aLkCwk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/df80f6ed4f9c7b7e86b4a3b89db4657056c05444/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L153)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1604#-OAIjgWe6Qmr3Tp66gH_:-OAMZtLv52hHz3LBhtr-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/df80f6ed4f9c7b7e86b4a3b89db4657056c05444/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L154)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1604)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs` line 78 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1604#-OAMixrN527Q1720u_ze:-OAMixrN527Q1720u_zf:bvva7hx) ([raw file](https://github.com/starkware-libs/sequencer/blob/148ad69a714f035ed8018c934e6a145cd31ea8a1/crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs#L78)):*
> ```XML
>     #[values("deploy_account_v1", "deploy_account_v3")] deploy_account_version: &str,
> ) {
>     let deploy_account_tx_v1 = deserialize_transaction_json_to_starknet_api_tx(
> ```

rename (not always v1)



_Suggestion:_
```XML
 deploy_account
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1604#-:-OAO3ZGW209hyUiH13uL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)

**Review by aner-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1604)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
