### PR TITLE
refactor(blockifier): define ArchivalDataResources struct

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1018)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1018)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 355 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1018#-O7dg77q1HUgAukV0B13:-O7dg77q1HUgAukV0B14:b-3ztgsp) ([raw file](https://github.com/starkware-libs/sequencer/blob/9087472423a5c79510b0b8e1ff6f1c2248049ce3/crates/blockifier/src/transaction/objects.rs#L355)):*
> ```XML
>                 + self.event_summary.total_event_data_size))
>             .to_integer()
>     }
> ```

these are just cut-pasted, right? any changes?



_Code quote:_
```XML
    pub fn to_gas_vector(
        &self,
        versioned_constants: &VersionedConstants,
        mode: &GasVectorComputationMode,
    ) -> GasVector {
        let archival_gas_costs = match mode {
            // Computation is in L2 gas units.
            GasVectorComputationMode::All => &versioned_constants.archival_data_gas_costs,
            // Computation is in L1 gas units.
            GasVectorComputationMode::NoL2Gas => {
                &versioned_constants.deprecated_l2_resource_gas_costs
            }
        };
        let gas_amount = [
            self.get_calldata_and_signature_gas_cost(archival_gas_costs),
            self.get_code_gas_cost(archival_gas_costs),
            self.get_events_gas_cost(archival_gas_costs),
        ]
        .into_iter()
        .sum();
        match mode {
            GasVectorComputationMode::All => GasVector::from_l2_gas(gas_amount),
            GasVectorComputationMode::NoL2Gas => GasVector::from_l1_gas(gas_amount),
        }
    }

    /// Returns the cost for transaction calldata and transaction signature. Each felt costs a
    /// fixed and configurable amount of gas. This cost represents the cost of storing the
    /// calldata and the signature on L2.  The result is given in L1/L2 gas units, depending on the
    /// mode.
    fn get_calldata_and_signature_gas_cost(
        &self,
        archival_gas_costs: &ArchivalDataGasCosts,
    ) -> u128 {
        // TODO(Avi, 20/2/2024): Calculate the number of bytes instead of the number of felts.
        let total_data_size = u128_from_usize(self.calldata_length + self.signature_length);
        (archival_gas_costs.gas_per_data_felt * total_data_size).to_integer()
    }

    /// Returns the cost of declared class codes in L1/L2 gas units, depending on the mode.
    fn get_code_gas_cost(&self, archival_gas_costs: &ArchivalDataGasCosts) -> u128 {
        (archival_gas_costs.gas_per_code_byte * u128_from_usize(self.code_size)).to_integer()
    }

    /// Returns the cost of the transaction's emmited events in L1/L2 gas units, depending on the
    /// mode.
    fn get_events_gas_cost(&self, archival_gas_costs: &ArchivalDataGasCosts) -> u128 {
        (archival_gas_costs.gas_per_data_felt
            * (archival_gas_costs.event_key_factor * self.event_summary.total_event_keys
                + self.event_summary.total_event_data_size))
            .to_integer()
    }
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1018)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/objects.rs` line 355 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1018#-O7dg77q1HUgAukV0B13:-O7dlf9LB8LX35CXXwBc:b-26fyy0) ([raw file](https://github.com/starkware-libs/sequencer/blob/9087472423a5c79510b0b8e1ff6f1c2248049ce3/crates/blockifier/src/transaction/objects.rs#L355)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

these are just cut-pasted, right? any changes?
</blockquote></details>

Right. Changed some funcs to be private since no one is using them

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1018#-:-O7hI7jS0bPYvvUwoC4P:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1018)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
