### PR TITLE
test(mempool): convert partial commit block test into a proper flow test

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1161)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1161)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1161#-O8VolVv-dmTBaC-0kBS:-O8VolVw-boGAVVHoVIy:b-olpuz9) ([raw file](https://github.com/starkware-libs/sequencer/blob/e5fdfef4595d052ae1c513237f7eb96b0667ac1d/crates/mempool/src/mempool_test.rs#L180)):*
> ```XML
> }
> 
> // TODO(Elin): consider comparing sets (makes tests more robust, no need to think of the order);
> ```

Don't we want to check the order of the transactions returned by `get_txs` function?



_Code quote:_
```XML
no need to think of the order
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1161)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1161#-O8VolVv-dmTBaC-0kBS:-O8VrxX04irPBHf772Hv:b-aplc6n) ([raw file](https://github.com/starkware-libs/sequencer/blob/e5fdfef4595d052ae1c513237f7eb96b0667ac1d/crates/mempool/src/mempool_test.rs#L180)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Don't we want to check the order of the transactions returned by `get_txs` function?
</blockquote></details>

Yeah , maybe we do. Done.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1161)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 963 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1161#-O8VvMSiB7ePf3ZOINs4:-O8VvMSiB7ePf3ZOINs5:bu9sglz) ([raw file](https://github.com/starkware-libs/sequencer/blob/6b79744820d942ed2bd3f922d5a5d4936f6ec474/crates/mempool/src/mempool_test.rs#L963)):*
> ```XML
>     );
> 
>     // Not included in block: address "0x2" nonce 2, address "0x1" nonce 1.
> ```

This is a bit confusing, you are mentioning addr 1 and 2 but not addr 0, even though there are still addr 0 txs in the poo.
The only diff between addr 1 and 0 is that 1 is also queued, but that's hard to tell in a glance, needs documentation I think



_Code quote:_
```XML
    // Not included in block: address "0x2" nonce 2, address "0x1" nonce 1.
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1161)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 955 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1161#-O8VutzMAKQFOUVPDHVM:-O8VutzMAKQFOUVPDHVN:b-7w4mzu) ([raw file](https://github.com/starkware-libs/sequencer/blob/6b79744820d942ed2bd3f922d5a5d4936f6ec474/crates/mempool/src/mempool_test.rs#L955)):*
> ```XML
>         &mut mempool,
>         2,
>         &[tx_address_2_nonce_2.tx, tx_address_1_nonce_0.tx],
> ```

Consider adding a comment explaining why `tx_address_0_nonce_3` is less prioritized



_Code quote:_
```XML
&[tx_address_2_nonce_2.tx, tx_address_1_nonce_0.tx]
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1161)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 955 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1161#-O8VutzMAKQFOUVPDHVM:-O8W-gTXCNw9W8Idlqa5:b-t1rcp1) ([raw file](https://github.com/starkware-libs/sequencer/blob/6b79744820d942ed2bd3f922d5a5d4936f6ec474/crates/mempool/src/mempool_test.rs#L955)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Consider adding a comment explaining why `tx_address_0_nonce_3` is less prioritized
</blockquote></details>

Might become outdated.
___
*[`crates/mempool/src/mempool_test.rs` line 963 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1161#-O8VvMSiB7ePf3ZOINs4:-O8W0TYX9sEBZlN6hjjj:bwafr45) ([raw file](https://github.com/starkware-libs/sequencer/blob/6b79744820d942ed2bd3f922d5a5d4936f6ec474/crates/mempool/src/mempool_test.rs#L963)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This is a bit confusing, you are mentioning addr 1 and 2 but not addr 0, even though there are still addr 0 txs in the poo.
The only diff between addr 1 and 0 is that 1 is also queued, but that's hard to tell in a glance, needs documentation I think
</blockquote></details>

The (only proposed) transaction from address 0 _was_ included in the block.

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1161)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1161#-:-O8W6yJEEpVnHhWaX6vg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
