### PR TITLE
refactor(mempool): use tx!() in additional locations

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/914)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/914)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/914#-O7NxvX32qbzhKu5TDoO:-O7NxvX44Gr1P2RMVHc8:blnilko) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4d27498e1020242e6cf54cf795d10d8b90a1bbe/crates/mempool/src/mempool_test.rs#L321)):*
> ```XML
> fn test_get_txs_replenishes_queue_multi_account_between_chunks() {
>     // Setup.
>     let tx_address_0_nonce_0 = tx!(tip: 30, tx_hash: 1, sender_address: "0x0", tx_nonce: 0_u8);
> ```

Only reordering.
___
*[`crates/mempool/src/mempool_test.rs` line 491 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/914#-O7Ny0HI56k-NdNUKiwr:-O7Ny0HI56k-NdNUKiws:blnilko) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4d27498e1020242e6cf54cf795d10d8b90a1bbe/crates/mempool/src/mempool_test.rs#L491)):*
> ```XML
> fn test_add_tx_multi_nonce_success(mut mempool: Mempool) {
>     // Setup.
>     let input_address_0_nonce_0 =
> ```

Only reordering.
___
*[`crates/mempool/src/mempool_test.rs` line 576 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/914#-O7Ny4HB4pZNAZ4-Udyq:-O7Ny4HB4pZNAZ4-Udyr:b3qma5w) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4d27498e1020242e6cf54cf795d10d8b90a1bbe/crates/mempool/src/mempool_test.rs#L576)):*
> ```XML
> fn test_add_tx_with_identical_tip_succeeds(mut mempool: Mempool) {
>     // Setup.
>     let input1 = add_tx_input!(tip: 1, tx_hash: 2, sender_address: "0x0");
> ```

I think we should be explicit here, same for `tX_hash: 0` addition below.
General case is when we have different values for the same field, which means its value is important for the test; default values are implicit and make the test harder to read.



_Code quote:_
```XML
sender_address: "0x0"
```

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/914#-:-O7OIqVO5BcUaEYZR-Rr:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/914#-O7OHtH3-cWN1mMn2hcY:-O7OHtH3-cWN1mMn2hcZ:bhjxljr) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4d27498e1020242e6cf54cf795d10d8b90a1bbe/crates/mempool/src/mempool_test.rs#L233)):*
> ```XML
> fn test_get_txs_returns_by_priority_order(#[case] requested_txs: usize) {
>     // Setup.
>     let mut txs = vec![
> ```

does this work? its stack instead of heap.
Might be separate PR though, since this is out of scope for this PR.



_Suggestion:_
```XML
    let mut txs = [
```
___
*[`crates/mempool/src/mempool_test.rs` line 439 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/914#-O7OIN092vDpROJHbpbj:-O7OIN0A38kI9k5nvE-m:b-32icjm) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4d27498e1020242e6cf54cf795d10d8b90a1bbe/crates/mempool/src/mempool_test.rs#L439)):*
> ```XML
>         .with_queue(queue_txs)
>         .build()
>         .into();
> ```

Out of scope thought, maybe we need a build_into_mempool or something like that, since this pattern appears alot



_Code quote:_
```XML
        .build()
        .into();
```
___
*[`crates/mempool/src/mempool_test.rs` line 576 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/914#-O7Ny4HB4pZNAZ4-Udyq:-O7OI_rSDE4Vq21uskRv:b-7q817d) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4d27498e1020242e6cf54cf795d10d8b90a1bbe/crates/mempool/src/mempool_test.rs#L576)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we should be explicit here, same for `tX_hash: 0` addition below.
General case is when we have different values for the same field, which means its value is important for the test; default values are implicit and make the test harder to read.
</blockquote></details>

Agreed, if there is more than one tx this is indeed hard to read, maybe I was the one who asked for this change previously to remove the explicit 0.
However for tests with only one tx I think it's fine

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/914#-:-O7OPh7a90qqFYZn8kIo:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 403 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/914#-O7OOK0HECTmcngtQejD:-O7OOK0I4bTQ_LcXrXod:b-vd87yn) ([raw file](https://github.com/starkware-libs/sequencer/blob/d70e589b874d98ccf29795faa96145e3cb224347/crates/mempool/src/mempool_test.rs#L403)):*
> ```XML
>     let input_tx = add_tx_input!(tx_nonce: 0_u8, account_nonce: 0_u8);
> 
>     let pool_txs = [input_tx.tx.clone()];
> ```

Why was it removed? In most tests, we use a named variable like `pool_txs` for clarity. Do you find it unnecessary now?



_Code quote:_
```XML
let pool_txs
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/914)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/914#-O7OHtH3-cWN1mMn2hcY:-O7OQ2h3Eh1BOTmnmsd9:bu7gfku) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4d27498e1020242e6cf54cf795d10d8b90a1bbe/crates/mempool/src/mempool_test.rs#L233)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

does this work? its stack instead of heap.
Might be separate PR though, since this is out of scope for this PR.
</blockquote></details>

Yup, done. Thanks for pointing it out.
___
*[`crates/mempool/src/mempool_test.rs` line 403 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/914#-O7OOK0HECTmcngtQejD:-O7OQBB31wZH_6xvepRq:b-3k1mba) ([raw file](https://github.com/starkware-libs/sequencer/blob/d70e589b874d98ccf29795faa96145e3cb224347/crates/mempool/src/mempool_test.rs#L403)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Why was it removed? In most tests, we use a named variable like `pool_txs` for clarity. Do you find it unnecessary now?
</blockquote></details>

Single use, so no need IMO.
___
*[`crates/mempool/src/mempool_test.rs` line 439 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/914#-O7OIN092vDpROJHbpbj:-O7ON7nb-AWcsibToE24:b-rw2r0f) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4d27498e1020242e6cf54cf795d10d8b90a1bbe/crates/mempool/src/mempool_test.rs#L439)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Out of scope thought, maybe we need a build_into_mempool or something like that, since this pattern appears alot
</blockquote></details>

Thanks, it's been bugging me too.
Done, [PTAL](https://reviewable.io/reviews/starkware-libs/sequencer/924).
___
*[`crates/mempool/src/mempool_test.rs` line 576 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/914#-O7Ny4HB4pZNAZ4-Udyq:-O7ONSfEBziOJF4tfgtR:bb7867z) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4d27498e1020242e6cf54cf795d10d8b90a1bbe/crates/mempool/src/mempool_test.rs#L576)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Agreed, if there is more than one tx this is indeed hard to read, maybe I was the one who asked for this change previously to remove the explicit 0.
However for tests with only one tx I think it's fine
</blockquote></details>

Yup.

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/914)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/914)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
