### PR TITLE
feat(mempool): add PartitionManager file

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/752)

### CODE REVIEW

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/752)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/partition_manager.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O6pAWHR5hKpsZuwa0qI:-O6pAWHR5hKpsZuwa0qJ:b-1sdczr) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dcdf6f54eefc67879cbd335f428c9ea65cac24e/crates/mempool/src/partition_manager.rs#L6)):*
> ```XML
> use crate::mempool::TransactionReference;
> 
> pub struct _PartitionManager {}
> ```

Please add docstr for the methods.



_Code quote:_
```XML
pub struct _PartitionManager {}
```
___
*[`crates/mempool/src/partition_manager.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O6pB4Jb1BeSCZnu5SoY:-O6pB4Jb1BeSCZnu5SoZ:bqiinnx) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dcdf6f54eefc67879cbd335f428c9ea65cac24e/crates/mempool/src/partition_manager.rs#L13)):*
> ```XML
>         _tx: TransactionReference,
>         _account_nonce: Nonce,
>     ) -> MempoolResult<()> {
> ```

Why did you choose to return a result, instead of assert/boolean as we did in TxQ?



_Code quote:_
```XML
MempoolResult<()>
```
___
*[`crates/mempool/src/partition_manager.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O6pBKEe-uatNURmL8-L:-O6pBKEfC7qUgMLgyHHk:b-kgne5x) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dcdf6f54eefc67879cbd335f428c9ea65cac24e/crates/mempool/src/partition_manager.rs#L19)):*
> ```XML
>     pub fn _align_with_current_state(&mut self, _address: ContractAddress, _nonce: Nonce) {}
> 
>     pub fn _remove(&mut self, _tx: &TransactionReference) {
> ```

Return a boolean; Please align with the TxQ struct.



_Code quote:_
```XML
_remove(&mut self, _tx: &TransactionReference) 
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/752)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/partition_manager.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O6pB4Jb1BeSCZnu5SoY:-O6pSCxe56leL5J1ZQJB:br5yb9g) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dcdf6f54eefc67879cbd335f428c9ea65cac24e/crates/mempool/src/partition_manager.rs#L13)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why did you choose to return a result, instead of assert/boolean as we did in TxQ?
</blockquote></details>

This `insert` func will be used after `tx_pool.insert` in `add_tx`, so I aligned the function header with`TransactionPool`
___
*[`crates/mempool/src/partition_manager.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O6pBKEe-uatNURmL8-L:-O6pRTGB-9nHp13iEel3:b-ogs45t) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dcdf6f54eefc67879cbd335f428c9ea65cac24e/crates/mempool/src/partition_manager.rs#L19)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Return a boolean; Please align with the TxQ struct.
</blockquote></details>

Why align specifically with the transaction queue struct? In the transaction pool, the return type is `MempoolResult<Transaction>`. This function will be used in `get_txs`, after removing from transaction pool

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/752)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/partition_manager.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O6pAWHR5hKpsZuwa0qI:-O6vBO0N2rpG_TvoKwD4:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dcdf6f54eefc67879cbd335f428c9ea65cac24e/crates/mempool/src/partition_manager.rs#L6)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please add docstr for the methods.
</blockquote></details>

Done.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/752)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/partition_manager.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O6pB4Jb1BeSCZnu5SoY:-O6zDhm53DLN9uTVRlpr:b-af2275) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dcdf6f54eefc67879cbd335f428c9ea65cac24e/crates/mempool/src/partition_manager.rs#L13)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

This `insert` func will be used after `tx_pool.insert` in `add_tx`, so I aligned the function header with`TransactionPool`
</blockquote></details>

the function usage is here #753

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/752)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/partition_manager.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O6pB4Jb1BeSCZnu5SoY:-O6zVp4GDh4R3ZBK-8Rs:b-iouy0a) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dcdf6f54eefc67879cbd335f428c9ea65cac24e/crates/mempool/src/partition_manager.rs#L13)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

the function usage is here #753
</blockquote></details>

But you'll call this method after you have already checked for duplication. 
Are there any other errors you expect to occur in this method that have not been checked beforehand?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/752)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/partition_manager.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O6pB4Jb1BeSCZnu5SoY:-O6zj9SbBeUTDbVtuWPX:b-pcqp7r) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dcdf6f54eefc67879cbd335f428c9ea65cac24e/crates/mempool/src/partition_manager.rs#L13)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

But you'll call this method after you have already checked for duplication. 
Are there any other errors you expect to occur in this method that have not been checked beforehand?
</blockquote></details>

In this function, I'll attempt to decrement the nonce to check if it's suspended. Since this may result in an error, I need the function to return a mempool result.
___
*[`crates/mempool/src/partition_manager.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O6pBKEe-uatNURmL8-L:-O6ziK1V7S5NT8CKbaF7:b-ruutax) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dcdf6f54eefc67879cbd335f428c9ea65cac24e/crates/mempool/src/partition_manager.rs#L19)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Are you planning to add assert here?
Do you assume that the remove always succeeds?
</blockquote></details>

Yes, since the PartitionManager contains all transactions, any given transaction must be removed from one of its fields (suspended or ready transactions).

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/752)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/partition_manager.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O6pBKEe-uatNURmL8-L:-O6zmX7r9rrWU3rB6HHD:b3w4e80) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dcdf6f54eefc67879cbd335f428c9ea65cac24e/crates/mempool/src/partition_manager.rs#L19)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Yes, since the PartitionManager contains all transactions, any given transaction must be removed from one of its fields (suspended or ready transactions).
</blockquote></details>

Just to make sure I get it, if `tx` wasn't in the partition manager it'd assert, right?

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/752)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/partition_manager.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O6znJOXC14ZuWfGg8LZ:-O6znJOXC14ZuWfGg8L_:b-hei6ur) ([raw file](https://github.com/starkware-libs/sequencer/blob/58758b3767f72fd28cfea20b2eafd866cf3d648b/crates/mempool/src/partition_manager.rs#L19)):*
> ```XML
>     /// Aligns the struct with the current state of a specific address and nonce updated in the
>     /// Mempool flow, e.g., during a commit block.
>     pub fn _align_with_current_state(&mut self, _address: ContractAddress, _nonce: Nonce) {}
> ```

Can it be replaced by `AccountState`?



_Code quote:_
```XML
 _address: ContractAddress, _nonce: Nonce
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/752)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/partition_manager.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O6pBKEe-uatNURmL8-L:-O6zuijZ34mj-Yzfm1jz:b-op21qh) ([raw file](https://github.com/starkware-libs/sequencer/blob/2dcdf6f54eefc67879cbd335f428c9ea65cac24e/crates/mempool/src/partition_manager.rs#L19)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Just to make sure I get it, if `tx` wasn't in the partition manager it'd assert, right?
</blockquote></details>

I'll add an assertion when implementing the function
___
*[`crates/mempool/src/partition_manager.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O6znJOXC14ZuWfGg8LZ:-O6zuwny3tSIoDBFAWrj:b-b5jkp5) ([raw file](https://github.com/starkware-libs/sequencer/blob/58758b3767f72fd28cfea20b2eafd866cf3d648b/crates/mempool/src/partition_manager.rs#L19)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can it be replaced by `AccountState`?
</blockquote></details>

No. `AccountState` contains only nonce now. It might be refactored in the future.

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/752#-:-O7--m8t9RaRFNg0flTG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/partition_manager.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O6znJOXC14ZuWfGg8LZ:-O6zzdM402bQPkCTLQPo:b-69mhl8) ([raw file](https://github.com/starkware-libs/sequencer/blob/58758b3767f72fd28cfea20b2eafd866cf3d648b/crates/mempool/src/partition_manager.rs#L19)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

No. `AccountState` contains only nonce now. It might be refactored in the future.
</blockquote></details>

the function name is called `_state`, so I think it's better to receive `AccountState`.
Non-blocking - it's up to you.

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/752)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/partition_manager.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O6znJOXC14ZuWfGg8LZ:-O78COItBxyH-MeMtltM:b-nnwb61) ([raw file](https://github.com/starkware-libs/sequencer/blob/58758b3767f72fd28cfea20b2eafd866cf3d648b/crates/mempool/src/partition_manager.rs#L19)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

the function name is called `_state`, so I think it's better to receive `AccountState`.
Non-blocking - it's up to you.
</blockquote></details>

This is linked to the longstanding issue of the missing address+nonce abstraction. Out of scope for this one, we'll do the refactor soon
___
*[`crates/mempool/src/partition_manager.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O78DLfE7l_s4D2RKJQk:-O78DLfE7l_s4D2RKJQl:b-os1xwb) ([raw file](https://github.com/starkware-libs/sequencer/blob/58758b3767f72fd28cfea20b2eafd866cf3d648b/crates/mempool/src/partition_manager.rs#L27)):*
> ```XML
>     pub fn _update_gas_price_threshold(&mut self, _gas_price_threshold: u128) {
>         todo!()
>     }
> ```

Remove plz.
Mempool is the one managing this value, both here and in the txQ the value has to be synced, so neither has permission to change it.



_Code quote:_
```XML
    pub fn _update_gas_price_threshold(&mut self, _gas_price_threshold: u128) {
        todo!()
    }
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/752)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/partition_manager.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O78J3imBmv1qDI16u1d:-O78J3inCA_AlvrxSQN-:bk5dn6n) ([raw file](https://github.com/starkware-libs/sequencer/blob/58758b3767f72fd28cfea20b2eafd866cf3d648b/crates/mempool/src/partition_manager.rs#L18)):*
> ```XML
> 
>     /// Aligns the struct with the current state of a specific address and nonce updated in the
>     /// Mempool flow, e.g., during a commit block.
> ```

This is repeating the signature in words.
The commit block part is the only addition, and it isn't necessary in order to understand what this does.



_Code quote:_
```XML
    /// Aligns the struct with the current state of a specific address and nonce updated in the
    /// Mempool flow, e.g., during a commit block.
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/752)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/partition_manager.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O78J3imBmv1qDI16u1d:-O78JGq36rG329dXSK6f:b-929bro) ([raw file](https://github.com/starkware-libs/sequencer/blob/58758b3767f72fd28cfea20b2eafd866cf3d648b/crates/mempool/src/partition_manager.rs#L18)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This is repeating the signature in words.
The commit block part is the only addition, and it isn't necessary in order to understand what this does.
</blockquote></details>

Can be removed altogether for now

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/752)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/partition_manager.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O78J3imBmv1qDI16u1d:-O792mlF-Vmyq-W4YrQ9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/58758b3767f72fd28cfea20b2eafd866cf3d648b/crates/mempool/src/partition_manager.rs#L18)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can be removed altogether for now
</blockquote></details>

Done.
___
*[`crates/mempool/src/partition_manager.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O78DLfE7l_s4D2RKJQk:-O792Mj11Vs4wVs8PVzX:bzgmvg8) ([raw file](https://github.com/starkware-libs/sequencer/blob/58758b3767f72fd28cfea20b2eafd866cf3d648b/crates/mempool/src/partition_manager.rs#L27)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Remove plz.
Mempool is the one managing this value, both here and in the txQ the value has to be synced, so neither has permission to change it.
</blockquote></details>

`PartitionManager` will have a `gas_threshold` field, updated by mempool's `update_gas_price_threshold` calling this function. It can be removed for now until gas partitioning is implemented.

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/752)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/partition_manager.rs` line 6 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O79a7ExBd2SUZYoVuuf:-O79a7ExBd2SUZYoVuug:bfush3d) ([raw file](https://github.com/starkware-libs/sequencer/blob/0778fe241d54a5c93b869049436307cefb4dd045/crates/mempool/src/partition_manager.rs#L6)):*
> ```XML
> use crate::mempool::TransactionReference;
> 
> pub struct _PartitionManager {}
> ```

What part of the API will be called for the main flow? That is, when the mempool wants a tx to remove and asks the manager for one?



_Code quote:_
```XML
pub struct _PartitionManager {}
```
___
*[`crates/mempool/src/partition_manager.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O79_xHiAnUnaMBze-jt:-O79_xHiAnUnaMBze-ju:bfyrwy0) ([raw file](https://github.com/starkware-libs/sequencer/blob/0778fe241d54a5c93b869049436307cefb4dd045/crates/mempool/src/partition_manager.rs#L19)):*
> ```XML
>     pub fn _align_with_current_state(&mut self, _address: ContractAddress, _nonce: Nonce) {}
> 
>     pub fn _remove(&mut self, _tx: &TransactionReference) {
> ```

What flow uses this?



_Code quote:_
```XML
    pub fn _remove(&mut self, _tx: &TransactionReference) {
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/752)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/partition_manager.rs` line 6 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O79a7ExBd2SUZYoVuuf:-O7O-u6k62U7tTL54aY3:b560qif) ([raw file](https://github.com/starkware-libs/sequencer/blob/0778fe241d54a5c93b869049436307cefb4dd045/crates/mempool/src/partition_manager.rs#L6)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

What part of the API will be called for the main flow? That is, when the mempool wants a tx to remove and asks the manager for one?
</blockquote></details>

The `PartitionManager` contains all transactions currently in the mempool. Therefore, the mempool flow calls the _PartitionManager API when transactions are received or removed: `insert`, `remove`, and `_align_with_current_state`, with `align` calling `remove` when account nonce updates require deletion.
___
*[`crates/mempool/src/partition_manager.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O79_xHiAnUnaMBze-jt:-O7NxNnm7q_ZCYnxjKEN:broxfzq) ([raw file](https://github.com/starkware-libs/sequencer/blob/0778fe241d54a5c93b869049436307cefb4dd045/crates/mempool/src/partition_manager.rs#L19)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

What flow uses this?
</blockquote></details>

This function is used when a transaction is no longer in the mempool's tx pool:
-   In `get_txs`, when popping a transaction from the pool.
-   When receiving a higher nonce, requiring deletion of older transactions from the pool, used in `add_tx` and `commit_block`.

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/752)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/partition_manager.rs` line 6 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O79a7ExBd2SUZYoVuuf:-O7UKsOe4tKWprsKDfiH:bwgcyfz) ([raw file](https://github.com/starkware-libs/sequencer/blob/0778fe241d54a5c93b869049436307cefb4dd045/crates/mempool/src/partition_manager.rs#L6)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

The `PartitionManager` contains all transactions currently in the mempool. Therefore, the mempool flow calls the _PartitionManager API when transactions are received or removed: `insert`, `remove`, and `_align_with_current_state`, with `align` calling `remove` when account nonce updates require deletion.
</blockquote></details>

That doesn't answer my question: when the mempool is full and it wants to ask the manager for a tx to purge, how does it do that through this API?

Also, I'm not sure if align can call remove on its own accord, isn't this the mempool's responsibility?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/752)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/partition_manager.rs` line 6 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/752#-O79a7ExBd2SUZYoVuuf:-O7XwPtB96mnADASocMK:b-ibiohh) ([raw file](https://github.com/starkware-libs/sequencer/blob/0778fe241d54a5c93b869049436307cefb4dd045/crates/mempool/src/partition_manager.rs#L6)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

That doesn't answer my question: when the mempool is full and it wants to ask the manager for a tx to purge, how does it do that through this API?

Also, I'm not sure if align can call remove on its own accord, isn't this the mempool's responsibility?
</blockquote></details>

I haven’t added the eviction API yet. So far, I’ve only added the API for maintaining all transactions in `PartitionManager`, which handles partitioning them into groups in preparation for eviction.

Regarding `align`, I plan to call it from the mempool's `align` function. When an account's nonce is updated, we may need to delete or move transactions in PartitionManager. The mempool isn’t aware of PartitionManager's internal partitioning.

**Pull request closed without merging**
