### PR TITLE
chore(consensus): remove the tx_hash from transactionBatch

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2459?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2459** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2459?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2459?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2458** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2458?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2457** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2457?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by guy-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 5 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2459)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @matan-starkware, and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 468 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2459#-ODM9ibbBb1jjOkiv1gc:-ODM9ibbBb1jjOkiv1gd:b-dbojx) ([raw file](https://github.com/starkware-libs/sequencer/blob/2eb8a6e809f12070195ae94f908de2a0d39fad21/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L468)):*
> ```XML
>                     transactions.push(tx.into());
>                 }
>                 debug!("Broadcasting proposal content: {transaction_hashes:?}");
> ```

I think this debug (and the extraction of the hashes right above it) was here before I added the hashes to the transaction batch. It may be better to leave it here.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2459)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @guy-starkware, and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 468 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2459#-ODM9ibbBb1jjOkiv1gc:-OD_G4b1BMmV7j51Tuxu:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2eb8a6e809f12070195ae94f908de2a0d39fad21/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L468)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

I think this debug (and the extraction of the hashes right above it) was here before I added the hashes to the transaction batch. It may be better to leave it here.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 5 of 7 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2459#-:-ODgMPHe-R-kcork3X_p:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @guy-starkware and @matan-starkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2459)* status: all files reviewed, 1 unresolved discussion (waiting on @guy-starkware and @matan-starkware)

**Review by guy-starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2459#-:-OEJuITGCgvw_9zHI-vY:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @matan-starkware)

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r7, 7 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2459)* status: all files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 61 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2459#-OEKjg3B1wcC4V2ozzwr:-OEKjg3B1wcC4V2ozzws:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f37611487ab8dc9066ea2a8a1b09d692a7e1290/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L61)):*
> ```XML
>     static ref EXECUTABLE_TX_BATCH: Vec<ExecutableTransaction> =
>         TX_BATCH.iter().map(|tx| (tx.clone(), &CHAIN_ID).try_into().unwrap()).collect();
> }
> ```





_Suggestion:_
```XML
lazy_static! {
    static ref TX_BATCH: Vec<Transaction> = (0..3).map(generate_invoke_tx).collect();
    static ref EXECUTABLE_TX_BATCH: Vec<ExecutableTransaction> =
        TX_BATCH.iter().map(|tx| (tx.clone(), &CHAIN_ID).try_into().unwrap()).collect();
}
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 401 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2459#-OEKi_iiBWDonh6o9df6:-OEKi_ij8YPjB28fE9Ia:bagu6h0) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f37611487ab8dc9066ea2a8a1b09d692a7e1290/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L401)):*
> ```XML
>         let chain_id = self.chain_id.clone();
> 
>         let handle = tokio::spawn({
> ```

Why add another scope?



_Code quote:_
```XML
        let handle = tokio::spawn({
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2459)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @guy-starkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 401 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2459#-OEKi_iiBWDonh6o9df6:-OENsWix9i2xubFHcewT:b-fbqmri) ([raw file](https://github.com/starkware-libs/sequencer/blob/60f2f252cbb5464b9b749cec992e16c0db681e6f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L401)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why add another scope?
</blockquote></details>

was just left here by accident form the previous PR on stack.
anyway, deleted now.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 8 files at r7, 1 of 8 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2459)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2459)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 61 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/2459#-OEKjg3B1wcC4V2ozzwr:-OEht4qN7eAEK8w2x6Xw:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/60f2f252cbb5464b9b749cec992e16c0db681e6f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L61)):*
> ```XML
>     static ref EXECUTABLE_TX_BATCH: Vec<ExecutableTransaction> =
>         TX_BATCH.iter().map(|tx| (tx.clone(), &CHAIN_ID).try_into().unwrap()).collect();
> }
> ```

done

**Review by guy-starkware — APPROVED** [review]
> Reviewed 7 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2459)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by guy-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2459)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Comment by Yael-Starkware** [comment]
### Merge activity

* **Dec 22, 6:37 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2459).

**Pull request merged**
