### PR TITLE
chore(gateway): move compiler config to gateway component

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/374)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/374?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#374** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/374?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#373** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/373?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/374)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/gateway.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/374#-O44MOKx5xsOtB1sN7Zd:-O44MOKx5xsOtB1sN7Ze:bltl9tv) ([raw file](https://github.com/starkware-libs/sequencer/blob/a071e2e5eb999180c8bdb8bb0f0047d65a07bf6e/crates/gateway/src/gateway.rs#L155)):*
> ```XML
>     config: GatewayConfig,
>     rpc_state_reader_config: RpcStateReaderConfig,
>     compiler_config: SierraToCasmCompilationConfig,
> ```

This can be the actual compiler, instead of just the config.
That way you will be able to easily inject a mock compiler.



_Code quote:_
```XML
compiler_config: SierraToCasmCompilationConfig,
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/374)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/gateway.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/374#-O44MOKx5xsOtB1sN7Zd:-O44US641062qB5KUigo:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a071e2e5eb999180c8bdb8bb0f0047d65a07bf6e/crates/gateway/src/gateway.rs#L155)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

This can be the actual compiler, instead of just the config.
That way you will be able to easily inject a mock compiler.
</blockquote></details>

Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/374#-:-O4C2DU63EHfYTfakZZQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware and @yair-starkware)

**Pull request merged**
