### PR TITLE
feat(mempool): add skip validate checks

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
* **#2227** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2227?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2227?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2227)* status: all files reviewed, 6 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/starknet_mempool/tests/flow_test.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCSdGlwBiHlflN45wJk:-OCSdGlwBiHlflN45wJl:b-c0aj7v) ([raw file](https://github.com/starkware-libs/sequencer/blob/74269094f66920a8a9c88e4e3b0b97797a85af03/crates/starknet_mempool/tests/flow_test.rs#L31)):*
> ```XML
>         add_tx_input!(tx_hash: 2, address: "0x0", tx_nonce: 2, account_nonce: 1);
>     let input_address_1_nonce_0 =
>         add_tx_input!(tx_hash: 3, address: "0x1", tx_nonce: 0, account_nonce: 0);
> ```

Can you please explain why this is not problematic?



_Code quote:_
```XML
    let input_address_1_nonce_0 =
        add_tx_input!(tx_hash: 3, address: "0x1", tx_nonce: 0, account_nonce: 0);
```
___
*[`crates/starknet_api/src/core.rs` line 254 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCSa0ON6r4o6E8oXmfl:-OCSa0ON6r4o6E8oXmfm:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/74269094f66920a8a9c88e4e3b0b97797a85af03/crates/starknet_api/src/core.rs#L254)):*
> ```XML
> 
>     pub fn is_first_invoke_for_undeployed_account(self, account_nonce: Nonce) -> bool {
>         self == Nonce(Felt::ONE) && account_nonce == Nonce(Felt::ZERO)
> ```





_Suggestion:_
```XML
nonce!(1_u32)
```
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 743 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCScQED5rGkJqOg51z0:-OCScQED5rGkJqOg51z1:bfyyc74) ([raw file](https://github.com/starkware-libs/sequencer/blob/74269094f66920a8a9c88e4e3b0b97797a85af03/crates/starknet_mempool/src/mempool_test.rs#L743)):*
> ```XML
> #[case::empty_mempool(vec![])]
> #[case::mempool_contains_another_address(vec![tx!(tx_hash: 2, address: "0x1", tx_nonce: 2)])]
> fn test_rejects_nonce_1_for_undeployed_account(#[case] pool_txs: Vec<AccountTransaction>) {
> ```

Please move it to the addTx tests section.



_Suggestion:_
```XML
test_add_tx_rejects_nonce_1_for_undeployed_account
```
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 750 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCSca0DAUAhqGqX44Ps:-OCSca0DAUAhqGqX44Pt:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/74269094f66920a8a9c88e4e3b0b97797a85af03/crates/starknet_mempool/src/mempool_test.rs#L750)):*
> ```XML
>         result,
>         Err(MempoolError::UndeployedAccount { sender_address: ContractAddress::default() })
>     );
> ```





_Suggestion:_
```XML
    // Setup.
    let mut mempool: Mempool = MempoolContentBuilder::new().with_pool(pool_txs).build().into();
    let tx = add_tx_input!(tx_hash: 1, address: "0x0", tx_nonce: 1, account_nonce: 0);
    
    //Test and Assert.
    let result = mempool.add_tx(tx);
    assert_eq!(
        result,
        Err(MempoolError::UndeployedAccount { sender_address: ContractAddress::default() })
    );
```
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 750 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCScgoCEJJPT29Zz0gr:-OCScgoCEJJPT29Zz0gs:b-98d2h5) ([raw file](https://github.com/starkware-libs/sequencer/blob/74269094f66920a8a9c88e4e3b0b97797a85af03/crates/starknet_mempool/src/mempool_test.rs#L750)):*
> ```XML
>         result,
>         Err(MempoolError::UndeployedAccount { sender_address: ContractAddress::default() })
>     );
> ```

please use `add_tx_expect_error`



_Code quote:_
```XML
    let result = mempool.add_tx(tx);
    assert_eq!(
        result,
        Err(MempoolError::UndeployedAccount { sender_address: ContractAddress::default() })
    );
```
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 760 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCScrjf0UtVAopCCTnr:-OCScrjf0UtVAopCCTns:b-3nourn) ([raw file](https://github.com/starkware-libs/sequencer/blob/74269094f66920a8a9c88e4e3b0b97797a85af03/crates/starknet_mempool/src/mempool_test.rs#L760)):*
> ```XML
>     let result = mempool.add_tx(tx);
>     assert_eq!(result, Ok(()));
> }
> ```

Please apply the same changes here as well.



_Code quote:_
```XML
#[test]
fn test_accepts_nonce_1_with_deploy_account_in_pool() {
    let tx = tx!(tx_hash: 0, address: "0x0", tx_nonce: 0);
    let mut mempool: Mempool = MempoolContentBuilder::new().with_pool([tx]).build().into();
    let tx = add_tx_input!(tx_hash: 1, address: "0x0", tx_nonce: 1, account_nonce: 0);
    let result = mempool.add_tx(tx);
    assert_eq!(result, Ok(()));
}
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2227)* status: all files reviewed, 5 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/starknet_mempool/src/mempool_test.rs` line 743 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCScQED5rGkJqOg51z0:-OCTBn5P6y_x_PEhyPXk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/74269094f66920a8a9c88e4e3b0b97797a85af03/crates/starknet_mempool/src/mempool_test.rs#L743)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please move it to the addTx tests section.
</blockquote></details>

Done.
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 750 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCScgoCEJJPT29Zz0gr:-OCTBngyCVePLKNp66d_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/74269094f66920a8a9c88e4e3b0b97797a85af03/crates/starknet_mempool/src/mempool_test.rs#L750)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

please use `add_tx_expect_error`
</blockquote></details>

Done.
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 760 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCScrjf0UtVAopCCTnr:-OCTCw2L4jUUXadjMXNV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/74269094f66920a8a9c88e4e3b0b97797a85af03/crates/starknet_mempool/src/mempool_test.rs#L760)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please apply the same changes here as well.
</blockquote></details>

Done.
___
*[`crates/starknet_mempool/tests/flow_test.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCSdGlwBiHlflN45wJk:-OCTCxrS4VT3DO7eXzwl:b-ufil83) ([raw file](https://github.com/starkware-libs/sequencer/blob/74269094f66920a8a9c88e4e3b0b97797a85af03/crates/starknet_mempool/tests/flow_test.rs#L31)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can you please explain why this is not problematic?
</blockquote></details>

if the tx_nonce is 1 and the account nonce is 0, then the gateway skips validations.

here tx_nonce is 0 (not 1).
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 750 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCSca0DAUAhqGqX44Ps:-OCTBmlxBi9BVHQ2djue:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/74269094f66920a8a9c88e4e3b0b97797a85af03/crates/starknet_mempool/src/mempool_test.rs#L750)):*
> ```XML
>         result,
>         Err(MempoolError::UndeployedAccount { sender_address: ContractAddress::default() })
>     );
> ```

Done.
___
*[`crates/starknet_api/src/core.rs` line 254 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCSa0ON6r4o6E8oXmfl:-OCTBHH2AwTBg01AA18L:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/74269094f66920a8a9c88e4e3b0b97797a85af03/crates/starknet_api/src/core.rs#L254)):*
> ```XML
> 
>     pub fn is_first_invoke_for_undeployed_account(self, account_nonce: Nonce) -> bool {
>         self == Nonce(Felt::ONE) && account_nonce == Nonce(Felt::ZERO)
> ```

done

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2227)* status: all files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/starknet_api/src/core.rs` line 254 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCSa0ON6r4o6E8oXmfl:-OCTNLNY6RYQGFc6NgD8:b6itz4q) ([raw file](https://github.com/starkware-libs/sequencer/blob/74269094f66920a8a9c88e4e3b0b97797a85af03/crates/starknet_api/src/core.rs#L254)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

done
</blockquote></details>

Why this change was reverted?
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 743 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCScQED5rGkJqOg51z0:-OCTHKZQ8tBEaIJ-eE4D:b-zihlt9) ([raw file](https://github.com/starkware-libs/sequencer/blob/74269094f66920a8a9c88e4e3b0b97797a85af03/crates/starknet_mempool/src/mempool_test.rs#L743)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, also please move it to the addTx section.
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 746 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCTMDyl-XWJjT-Nn3JN:-OCTMDym9kTb2iEJ1_g9:b-sg3jv) ([raw file](https://github.com/starkware-libs/sequencer/blob/96d703e28eea8940a607c4f0936989cd8bb48157/crates/starknet_mempool/src/mempool_test.rs#L746)):*
> ```XML
>     // Setup.
>     let mut mempool: Mempool = MempoolContentBuilder::new().with_pool(pool_txs).build().into();
>     let tx = add_tx_input!(tx_hash: 1, address: "0x0", tx_nonce: 1, account_nonce: 0);
> ```

Usually we use `input` for `add_tx_input`.



_Suggestion:_
```XML
input
```
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 761 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCTMeIMAw3iq2jYP5lS:-OCTMeIMAw3iq2jYP5lT:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/96d703e28eea8940a607c4f0936989cd8bb48157/crates/starknet_mempool/src/mempool_test.rs#L761)):*
> ```XML
>     let tx = tx!(tx_hash: 0, address: "0x0", tx_nonce: 0);
>     let mut mempool: Mempool = MempoolContentBuilder::new().with_pool([tx]).build().into();
>     let tx = add_tx_input!(tx_hash: 1, address: "0x0", tx_nonce: 1, account_nonce: 0);
> ```





_Suggestion:_
```XML
input
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2227)* status: all files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/starknet_api/src/core.rs` line 254 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCSa0ON6r4o6E8oXmfl:-OCTOKDs7mY1QYwbLQVo:b-jye265) ([raw file](https://github.com/starkware-libs/sequencer/blob/74269094f66920a8a9c88e4e3b0b97797a85af03/crates/starknet_api/src/core.rs#L254)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why this change was reverted?
</blockquote></details>

turns out nonce!() is only  for testing

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2227)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/starknet_mempool/src/mempool_test.rs` line 743 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCScQED5rGkJqOg51z0:-OCTPvPRATkoSVq2Or5e:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/74269094f66920a8a9c88e4e3b0b97797a85af03/crates/starknet_mempool/src/mempool_test.rs#L743)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Thanks, also please move it to the addTx section.
</blockquote></details>

Done.
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 746 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCTMDyl-XWJjT-Nn3JN:-OCTPvxO2K7XfwKGny3i:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/96d703e28eea8940a607c4f0936989cd8bb48157/crates/starknet_mempool/src/mempool_test.rs#L746)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Usually we use `input` for `add_tx_input`.
</blockquote></details>

done
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 761 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCTMeIMAw3iq2jYP5lS:-OCTPxqU7zH0J1y_3-DF:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/96d703e28eea8940a607c4f0936989cd8bb48157/crates/starknet_mempool/src/mempool_test.rs#L761)):*
> ```XML
>     let tx = tx!(tx_hash: 0, address: "0x0", tx_nonce: 0);
>     let mut mempool: Mempool = MempoolContentBuilder::new().with_pool([tx]).build().into();
>     let tx = add_tx_input!(tx_hash: 1, address: "0x0", tx_nonce: 1, account_nonce: 0);
> ```

done

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2227)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-:-OCTW4ASEpz-MN1RqtUF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5 and @elintul)

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2227)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @elintul, and @Yael-Starkware)

___
*[`crates/starknet_api/src/core.rs` line 255 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCTkskMCmkC5TENse8-:-OCTkskMCmkC5TENse80:b-o18xck) ([raw file](https://github.com/starkware-libs/sequencer/blob/426ace3e0238f716c5c1f77a46fb1014dec3042d/crates/starknet_api/src/core.rs#L255)):*
> ```XML
>     pub fn is_first_invoke_for_undeployed_account(self, account_nonce: Nonce) -> bool {
>         self == Nonce(Felt::ONE) && account_nonce == Nonce(Felt::ZERO)
>     }
> ```

(Non-blocking)
I wonder if this is the correct place to locate this function, maybe it should be in a `test_util`, as it is not relevant for starknet api.
wdyt?



_Code quote:_
```XML
    pub fn is_first_invoke_for_undeployed_account(self, account_nonce: Nonce) -> bool {
        self == Nonce(Felt::ONE) && account_nonce == Nonce(Felt::ZERO)
    }
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2227)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @elintul, and @MohammadNassar1)

___
*[`crates/starknet_api/src/core.rs` line 255 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCTkskMCmkC5TENse8-:-OCTvzX0436oze72dWG6:b-25iojz) ([raw file](https://github.com/starkware-libs/sequencer/blob/426ace3e0238f716c5c1f77a46fb1014dec3042d/crates/starknet_api/src/core.rs#L255)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

(Non-blocking)
I wonder if this is the correct place to locate this function, maybe it should be in a `test_util`, as it is not relevant for starknet api.
wdyt?
</blockquote></details>

but it is not a test util. and it needs to be shared between the gateway and the mempool

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2227)* status: all files reviewed, 7 unresolved discussions (waiting on @alonh5, @elintul, and @giladchase)

___
*[`crates/starknet_api/src/core.rs` line 255 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCTkskMCmkC5TENse8-:-OCce4P66PS8u4HzBeBr:b-9ivmuo) ([raw file](https://github.com/starkware-libs/sequencer/blob/426ace3e0238f716c5c1f77a46fb1014dec3042d/crates/starknet_api/src/core.rs#L255)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Yr both correct.

I think a dedicated `skip_validation` function for both the mempool and gateway with each one's required logic is fine.
This is because the logic doesn't really match anyway since the mempool does an additional state check (inclusion-check) that the gateway does not.
</blockquote></details>

not sure I understand your suggestion :)
___
*[`crates/starknet_gateway/src/stateful_transaction_validator.rs` line 120 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCbwQvd8wFwS64QYgks:-OCcgj0T6dfENssymrgM:b5hcn3c) ([raw file](https://github.com/starkware-libs/sequencer/blob/cec10c41a9af6b15376385908bb55f6545707cc5/crates/starknet_gateway/src/stateful_transaction_validator.rs#L120)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

IIUC this is not the case, the mempool checks inclusion of an address only?
</blockquote></details>

inclusion of the address in this case indicates that the account was deployed. (explanation in the next comment).
___
*[`crates/starknet_mempool/src/mempool.rs` line 295 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCbo5LK8JqbGbiOjnuo:-OCcfYvc17CSYY9zK_pI:b-1o94s4) ([raw file](https://github.com/starkware-libs/sequencer/blob/426ace3e0238f716c5c1f77a46fb1014dec3042d/crates/starknet_mempool/src/mempool.rs#L295)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can you plz explain the future nonces thing? 
Does this mean that if I send txs with tx nonce 2 then 1 to the mempool, then tx 1 will pass this test?
</blockquote></details>

if you send a transaction with nonce 2 to the gateway, the gateway doesn't skip validations, so it will pass the validations only if the account was already deployed.
In this case nonce 2 will get to the mempool. 

it was just an attempt to explain why checking the inclusion of the address is enough and there is no need to check that this is a deploy_account tx.
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 515 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCbvWp37by1X4CcXWf3:-OCcjAx49XKJZN07SXJM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/426ace3e0238f716c5c1f77a46fb1014dec3042d/crates/starknet_mempool/src/mempool_test.rs#L515)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

allocations weren't necessary
</blockquote></details>

Done.
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 517 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCbrFhE1dSmZyhC-D1b:-OCcjFID6-97yo84lO73:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/426ace3e0238f716c5c1f77a46fb1014dec3042d/crates/starknet_mempool/src/mempool_test.rs#L517)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Also in the other test
</blockquote></details>

Done.
___
*[`crates/starknet_mempool_types/src/errors.rs` line 21 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCbpAvA86NL5_1eWlcR:-OCcjRPJCzOZLzsBKLWf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/426ace3e0238f716c5c1f77a46fb1014dec3042d/crates/starknet_mempool_types/src/errors.rs#L21)):*
> ```XML
>     TransactionNotFound { tx_hash: TransactionHash },
>     #[error("Undeployed account {:?}", sender_address)]
>     UndeployedAccount { sender_address: ContractAddress },
> ```

Done.
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 469 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCbvxQZAakJgHTitgSn:-OCciypuAtUcfW0tB87x:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/426ace3e0238f716c5c1f77a46fb1014dec3042d/crates/starknet_mempool/src/mempool_test.rs#L469)):*
> ```XML
>     // Setup.
>     let input_nonce_0 = add_tx_input!(tx_hash: 1, tx_nonce: 1, account_nonce: 1);
>     let input_nonce_1 = add_tx_input!(tx_hash: 2, tx_nonce: 2, account_nonce: 1);
> ```

Done.

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2227)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @alonh5, @elintul, @MohammadNassar1, and @Yael-Starkware)

___
*[`crates/starknet_api/src/core.rs` line 255 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCTkskMCmkC5TENse8-:-OD06oZFA8ECvTBhZxEV:b-pz5vp3) ([raw file](https://github.com/starkware-libs/sequencer/blob/426ace3e0238f716c5c1f77a46fb1014dec3042d/crates/starknet_api/src/core.rs#L255)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

not sure I understand your suggestion :)
</blockquote></details>

I suggest not trying to share this logic between the gateway and the mempool, have each one inline this condition or define it's own private function that encapsulates this logic.

In any case, I don't think it belongs in SNAPI since it isn't meaningful enough to non mempool/gateway users.
___
*[`crates/starknet_gateway/src/stateful_transaction_validator.rs` line 120 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCbwQvd8wFwS64QYgks:-OD08uGNEO5b-uxcWZ3T:bqbbw3r) ([raw file](https://github.com/starkware-libs/sequencer/blob/cec10c41a9af6b15376385908bb55f6545707cc5/crates/starknet_gateway/src/stateful_transaction_validator.rs#L120)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

inclusion of the address in this case indicates that the account was deployed. (explanation in the next comment).
</blockquote></details>

I see, but still i don't think we can say that `The mempool also verifies that the deploy_account transaction exists`,  I think the comment might be misleading, since the mempool can't really verify this definitively, at least not without trusting the GW to some extent, which makes the verification circular (the gw trusts that the mempool verified, but the mempool verifies based on trusting that the gw verified)
___
*[`crates/starknet_mempool/src/mempool.rs` line 295 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCbo5LK8JqbGbiOjnuo:-OD0D7ASCUlUdZqEbR7G:b-caoi7f) ([raw file](https://github.com/starkware-libs/sequencer/blob/426ace3e0238f716c5c1f77a46fb1014dec3042d/crates/starknet_mempool/src/mempool.rs#L295)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

if you send a transaction with nonce 2 to the gateway, the gateway doesn't skip validations, so it will pass the validations only if the account was already deployed.
In this case nonce 2 will get to the mempool. 

it was just an attempt to explain why checking the inclusion of the address is enough and there is no need to check that this is a deploy_account tx.
</blockquote></details>

I undestand, there are a few issues here though:

1. This won't always work. For example, if the deploy tx is added to a block, a commit_block is sent, which removes the tx from the mempool, including the address. If at the same time the GW sends a tx with tx-nonce=1 and account-nonce=0 (the GW didn't get the commit_block). This will fail this check. This might happen a non-negligable amount of times in real-life, since a block is closed every few seconds. Checking the mempool_state instead of the pool might help out with this to an extent.
2. This is too complicated, even if (1) is solved. In order to understand this code the prerequisites are: know how gateway validations work, know how gateway validation skipping logic is performed, know when and how the mempool evicts addresses from its storage works. Can this be written in a way that that reduces some of these prerequisites?

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2227)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @alonh5, @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/starknet_api/src/core.rs` line 255 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2227#-OCTkskMCmkC5TENse8-:-OD0JR7b2vV3o9-dKJFo:b-d2nqod) ([raw file](https://github.com/starkware-libs/sequencer/blob/426ace3e0238f716c5c1f77a46fb1014dec3042d/crates/starknet_api/src/core.rs#L255)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I suggest not trying to share this logic between the gateway and the mempool, have each one inline this condition or define it's own private function that encapsulates this logic.

In any case, I don't think it belongs in SNAPI since it isn't meaningful enough to non mempool/gateway users.
</blockquote></details>

I think it is important to couple the two , since if someone tries to change the condition in one place, he should be aware that it affects the behaviour of the other service.

regarding the location, I'm not sure about SNAPI, but this is the only shared location I could think of, do you have other suggestions?

**Pull request closed without merging**
