### PR TITLE
feat(blockifier): add `NativeSyscallHandler`

### PR DESCRIPTION
**Pull request by rodrigo-pino**
Third time of the PR for the same feature. I am not rebasing from the previous one because git history has been a bit messy and resolving conflicts for 70+ commits is not fun.

This PR comes as a new version for #621 (which in itself was a copy version for #551) but it has been trimmed down a bit.

After this one is merged we can subsequently close the others.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1157)

### CODE REVIEW

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1157)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8Wqix4BYYDrwZEtDW0:-O8Wqix4BYYDrwZEtDW1:bybhan0) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d8ec18fa974520c62552a8b89b67f3f45abd3ed/crates/blockifier/src/execution/native/syscall_handler.rs#L110)):*
> ```XML
>     pub fn substract_syscall_gas_cost(
>         &mut self,
>         remaining_gas: &mut u128,
> ```

https://reviewable.io/reviews/starkware-libs/sequencer/621#-O7AR9rr3iLF7ozeCslU 
see discussion above



_Suggestion:_
```XML
remaining_gas: &mut u128,
remaining_gas: &mut u64,
```
___
*[`crates/blockifier/src/execution/native/utils.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8WrUtm8ycrSRb7e_jh:-O8WrUtm8ycrSRb7e_ji:b-ohuij4) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d8ec18fa974520c62552a8b89b67f3f45abd3ed/crates/blockifier/src/execution/native/utils.rs#L13)):*
> ```XML
> 
> pub fn encode_str_as_felts(msg: &str) -> Vec<Felt> {
>     const CHUNK_SIZE: usize = 32;
> ```

Can you please explain? Why 32?



_Code quote:_
```XML
const CHUNK_SIZE: usize = 32;
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1157)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @noaov1 and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/utils.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8WuIUvAN4ooiNHqIL8:-O8WuIUvAN4ooiNHqIL9:bgplwzh) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d8ec18fa974520c62552a8b89b67f3f45abd3ed/crates/blockifier/src/execution/native/utils.rs#L12)):*
> ```XML
> }
> 
> pub fn encode_str_as_felts(msg: &str) -> Vec<Felt> {
> ```

See discussion
https://reviewable.io/reviews/starkware-libs/sequencer/621#-O5wl5XLBruyQJwstLkp

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1157)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @noaov1 and @rodrigo-pino)

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1157)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8Wdk8M4iLtb3R0hmvz:-O8XQxJn6KnQI2G70try:b-8fx2u7) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d8ec18fa974520c62552a8b89b67f3f45abd3ed/crates/blockifier/src/execution/native/syscall_handler.rs#L87)):*
> ```XML
>         self.update_remaining_gas(remaining_gas, &call_info);
> 
>         let retdata = call_info.execution.retdata.clone();
> ```

:+1: 
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8WeWprBG5gqXNGtW6P:-O8XR_Eq2Vk3CbDwVj6l:b-5vb6nz) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d8ec18fa974520c62552a8b89b67f3f45abd3ed/crates/blockifier/src/execution/native/syscall_handler.rs#L103)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please move this method outside the `Imp`
</blockquote></details>

I don't know why this were public `execute_inner_call`, `update_remaining_gas` and `substract_syscall_gas_cost`. I've reverted them back to private and used `#[allow(dead_code)]` for the time being. 

I can also removed them but almost all syscalls will be using them in the future which means a bit slowness when starting those.

Is in the impl because it was meant as an internal part of `NativeSyscallHandler` private to everyone else. If you still think is best out I'll move it out
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8Wqix4BYYDrwZEtDW0:-O8XTr2N6fkRyEkMS3aj:b-sce9go) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d8ec18fa974520c62552a8b89b67f3f45abd3ed/crates/blockifier/src/execution/native/syscall_handler.rs#L110)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

https://reviewable.io/reviews/starkware-libs/sequencer/621#-O7AR9rr3iLF7ozeCslU 
see discussion above
</blockquote></details>

Native treats gas as a `u128` hence we have to build our wrappers around it to communicate with blockifiers `u64`. We can ask for a `u64` change on their part and re-update this part.
___
*[`crates/blockifier/src/execution/native/utils.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8WuIUvAN4ooiNHqIL8:-O8XUuyC0h-RCOBoEB1P:b-g44foc) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d8ec18fa974520c62552a8b89b67f3f45abd3ed/crates/blockifier/src/execution/native/utils.rs#L12)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

See discussion
https://reviewable.io/reviews/starkware-libs/sequencer/621#-O5wl5XLBruyQJwstLkp
</blockquote></details>

This functions are required to handle user created errors (either panics! or Err results) or inner-call error propagation.

If we get an error message which fits in a `Felt` then it behavesthe same as the VM. 

If the error is bigger, meaning it spans several `Felt`, we take the bytes of each felt, join them and decode them as utf8 if possible. If not utf8-decodable, then we just try to decode individual Felts.

This method is only used after Native returned control and there was an error. The error returned by Native won't be in String form but in a `Vec<Felt>` hence the need to decode it.
___
*[`crates/blockifier/src/execution/native/utils.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8WrUtm8ycrSRb7e_jh:-O8XUp3TEAdMoMnZzizS:b-3gz1j1) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d8ec18fa974520c62552a8b89b67f3f45abd3ed/crates/blockifier/src/execution/native/utils.rs#L13)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Can you please explain? Why 32?
</blockquote></details>

We are converting a string back into a Felt. We then created small arrays of 32 bytes, fill the first 31 bytes with the string encoding information and make them Felts.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 17 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1157)* status: 4 of 17 files reviewed, 7 unresolved discussions (waiting on @meship-starkware and @rodrigo-pino)

___
*[`.github/workflows/blockifier_ci.yml` line 44 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8XjqvG6j5UYGlYAYh_:-O8XjqvG6j5UYGlYAYha:bwxq1fq) ([raw file](https://github.com/starkware-libs/sequencer/blob/68e2ecbb4928cd50c81e070a42794f7b8a70801b/.github/workflows/blockifier_ci.yml#L44)):*
> ```YAML
> jobs:
>   featureless-build:
>     runs-on: ubuntu-22.04
> ```

Why was this change needed?
@alon-dotan-starkware 



_Code quote:_
```YAML
    runs-on: ubuntu-22.04
```
___
*[`.github/workflows/main.yml` line 22 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8Xk95t45_zb11Oxsck:-O8Xk95t45_zb11Oxscl:b-hyoy0j) ([raw file](https://github.com/starkware-libs/sequencer/blob/9fd6c3f9d2567dd77d61d94aae8c2ef3518e1c4d/.github/workflows/main.yml#L22)):*
> ```YAML
> concurrency:
>   group: ${{ github.workflow }}-${{ github.ref }}
>   cancel-in-progress: ${{ github.event_name == 'pull_request' }}
> ```

Why was this removed?



_Code quote:_
```YAML
# On PR events, cancel existing CI runs on this same PR for this workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8WeWprBG5gqXNGtW6P:-O8XmUUT3WF0cVyAkzS8:bqep644) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d8ec18fa974520c62552a8b89b67f3f45abd3ed/crates/blockifier/src/execution/native/syscall_handler.rs#L103)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

I don't know why this were public `execute_inner_call`, `update_remaining_gas` and `substract_syscall_gas_cost`. I've reverted them back to private and used `#[allow(dead_code)]` for the time being. 

I can also removed them but almost all syscalls will be using them in the future which means a bit slowness when starting those.

Is in the impl because it was meant as an internal part of `NativeSyscallHandler` private to everyone else. If you still think is best out I'll move it out
</blockquote></details>

RE the private: great!
I thought that as it does not use `self` it is better to move it out of the `impl` block.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r9, 1 of 1 files at r11, 1 of 1 files at r13, 1 of 1 files at r14, 1 of 1 files at r16, 10 of 10 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1157)* status: 15 of 17 files reviewed, 8 unresolved discussions (waiting on @meship-starkware and @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 112 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8_bqIKCBSCJsVKjYAx:-O8_bqIKCBSCJsVKjYAy:b4ihzz2) ([raw file](https://github.com/starkware-libs/sequencer/blob/425acc7770dd3490afde725a029fed84bb47e6be/crates/blockifier/src/execution/native/syscall_handler.rs#L112)):*
> ```XML
>                     .expect("Failed to parse OUT_OF_GAS_ERROR hex string"),
>             ]);
>         }
> ```

Where do we set the failure flag to `1` in this case? (and in any case of an error returned from a syscall)



_Code quote:_
```XML
            return Err(vec![
                Felt::from_hex(OUT_OF_GAS_ERROR)
                    .expect("Failed to parse OUT_OF_GAS_ERROR hex string"),
            ]);
        }
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 320 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8_Q-1X9Eoh49YDaoZW:-O8_Q-1X9Eoh49YDaoZX:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/425acc7770dd3490afde725a029fed84bb47e6be/crates/blockifier/src/execution/native/syscall_handler.rs#L320)):*
> ```XML
> fn native_update_remaining_gas(remaining_gas: &mut u128, call_info: &CallInfo) {
>     // Create a new variable with converted type.
>     let mut remaining_gas_u64 = u64::try_from(*remaining_gas).unwrap();
> ```





_Suggestion:_
```XML
let mut remaining_gas_u64 = u64::try_from(*remaining_gas).expect("Failed to convert gas to u64.");
```
___
*[`crates/blockifier/src/execution/native/utils.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8WrUtm8ycrSRb7e_jh:-O8_UdaiBSUB-QXtcxnU:b-jwm2kp) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d8ec18fa974520c62552a8b89b67f3f45abd3ed/crates/blockifier/src/execution/native/utils.rs#L13)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

We are converting a string back into a Felt. We then created small arrays of 32 bytes, fill the first 31 bytes with the string encoding information and make them Felts.
</blockquote></details>

Why 32 exactly?

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1157)* status: 14 of 17 files reviewed, 8 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8WeWprBG5gqXNGtW6P:-O8Y-fMF-d44wkYvbNKk:bazii8d) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d8ec18fa974520c62552a8b89b67f3f45abd3ed/crates/blockifier/src/execution/native/syscall_handler.rs#L103)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

RE the private: great!
I thought that as it does not use `self` it is better to move it out of the `impl` block.
</blockquote></details>

yes, it makes sense!
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 112 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8_bqIKCBSCJsVKjYAx:-O8adnEb5Sw0WZ-vDoXV:brl9swx) ([raw file](https://github.com/starkware-libs/sequencer/blob/425acc7770dd3490afde725a029fed84bb47e6be/crates/blockifier/src/execution/native/syscall_handler.rs#L112)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Where do we set the failure flag to `1` in this case? (and in any case of an error returned from a syscall)
</blockquote></details>

When Native invokes a syscall and passes control to us, it expects a a result a `SyscallResult<OkType, ErrType>`.  If we return an Err in the syscall, in this specific context by calling this function, it will propagate back to Native. The Native Contract should then propagate the error back and return it as well as setting the failure flag to 1
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 320 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8_Q-1X9Eoh49YDaoZW:-O8agTvRAFspsur9LpCE:b-8fx2u7) ([raw file](https://github.com/starkware-libs/sequencer/blob/425acc7770dd3490afde725a029fed84bb47e6be/crates/blockifier/src/execution/native/syscall_handler.rs#L320)):*
> ```XML
> fn native_update_remaining_gas(remaining_gas: &mut u128, call_info: &CallInfo) {
>     // Create a new variable with converted type.
>     let mut remaining_gas_u64 = u64::try_from(*remaining_gas).unwrap();
> ```

:+1: 
___
*[`crates/blockifier/src/execution/native/utils.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8WrUtm8ycrSRb7e_jh:-O8adI557t34zvd2vIuO:b5tq7tj) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d8ec18fa974520c62552a8b89b67f3f45abd3ed/crates/blockifier/src/execution/native/utils.rs#L13)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why 32 exactly?
</blockquote></details>

Ok, so the issue to solve is we have a long string we want to encode as Felts. We know how much info fits in a Felt (31 Bytes). 

The function splits the string in chunks of 31 Bytes, copies them to a static array of size 32 Bytes which is then used to create the new felt with `Felt::from_bytes_be(...)`. This function requires the static array size to be 32 (maybe this is what you were asking)

During the code we are either dealing with `CHUNK_SIZE - 1` or `CHUNK_SIZE`. 
___
*[`.github/workflows/main.yml` line 22 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8Xk95t45_zb11Oxsck:-O8Y1blc8WUD7W2vkrAX:b-1qbhi1) ([raw file](https://github.com/starkware-libs/sequencer/blob/9fd6c3f9d2567dd77d61d94aae8c2ef3518e1c4d/.github/workflows/main.yml#L22)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why was this removed?
</blockquote></details>

Unintentional deletion.

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 1 of 1 files at r13, 1 of 1 files at r14, 1 of 1 files at r16, 10 of 10 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1157)* status: all files reviewed, 5 unresolved discussions (waiting on @noaov1 and @rodrigo-pino)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1157)* status: all files reviewed, 1 unresolved discussion (waiting on @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/utils.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8WrUtm8ycrSRb7e_jh:-O8bQLji6CCDh2oobNNR:b-6p9qqf) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d8ec18fa974520c62552a8b89b67f3f45abd3ed/crates/blockifier/src/execution/native/utils.rs#L13)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

Ok, so the issue to solve is we have a long string we want to encode as Felts. We know how much info fits in a Felt (31 Bytes). 

The function splits the string in chunks of 31 Bytes, copies them to a static array of size 32 Bytes which is then used to create the new felt with `Felt::from_bytes_be(...)`. This function requires the static array size to be 32 (maybe this is what you were asking)

During the code we are either dealing with `CHUNK_SIZE - 1` or `CHUNK_SIZE`.
</blockquote></details>

Got it. Thanks!
Why not do it as we encode the constants error (e.g. `OUT_OF_GAS_ERROR`): 



_Code snippet:_
```XML
let bytes = msg.as_bytes();
let error_felt = BigUint::from_bytes_be(bytes)
let error_hex = format!("0x{:x}", error_felt)
 Felt::from_hex(error_hex)
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1157)* status: all files reviewed, 2 unresolved discussions (waiting on @rodrigo-pino)

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1157)* status: 16 of 18 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/native/utils.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1157#-O8WrUtm8ycrSRb7e_jh:-O8bsoib9WhithOxuFOj:buaor1l) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d8ec18fa974520c62552a8b89b67f3f45abd3ed/crates/blockifier/src/execution/native/utils.rs#L13)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Got it. Thanks!
Why not do it as we encode the constants error (e.g. `OUT_OF_GAS_ERROR`):
</blockquote></details>

In this case we are just handling case where `msg` cannot have more than 31 bytes of information, otherwise it might not fit in a felt. 

I remember we took that decision because there are errors given by the blockifier which exceed the 31 byte size, and there was no way of propagating all the information back through Native the same way you do in the VM with the Blockifier. 

For example, the following error, there is no way to propagate back with Native without encoding it as Felts: https://github.com/starkware-libs/sequencer/blob/7df7a302ac4f54ea3e0e98ad4fd134c24b1a9a6c/crates/blockifier/src/execution/syscalls/hint_processor.rs#L113-L114

**Pull request closed without merging**
