### PR TITLE
refactor(blockifier,starknet_api): add GasAmount (u128) type and use in blockifier's GasVector

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1172)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
* **#1174** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1174?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1173** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1173?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1172** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1172?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1172)* status: 4 of 22 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 242 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1172#-O8WinuwA5q-Psdn-Tyx:-O8WinuwA5q-Psdn-Tyy:br2y3p4) ([raw file](https://github.com/starkware-libs/sequencer/blob/eccb0e4bd650656553e495f9a8ec19c00227d7f8/crates/blockifier/src/concurrency/versioned_state_test.rs#L242)):*
> ```XML
>         deploy_account_tx_args! {
>             class_hash: account_without_validation.get_class_hash(),
>             resource_bounds: l1_resource_bounds(GasAmount(u128::from(!zero_bounds)), DEFAULT_STRK_L1_GAS_PRICE),
> ```

Consider impl `from` and `into` GasAmount` (for u64 and u128)



_Code quote:_
```XML
(GasAmount(u128::from(!zero_bounds))
```
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1172#-O8Wiyq84-JAjP6yhlZl:-O8Wiyq84-JAjP6yhlZm:b-cky5b2) ([raw file](https://github.com/starkware-libs/sequencer/blob/eccb0e4bd650656553e495f9a8ec19c00227d7f8/crates/blockifier/src/fee/fee_checks.rs#L20)):*
> ```XML
>         "Insufficient max {resource}: max amount: {max_amount:?}, actual used: {actual_amount:?}."
>     )]
>     MaxGasAmountExceeded { resource: Resource, max_amount: GasAmount, actual_amount: GasAmount },
> ```

Remember - we want numbers without wrappers in error messages.



_Code quote:_
```XML
        "Insufficient max {resource}: max amount: {max_amount:?}, actual used: {actual_amount:?}."
    )]
    MaxGasAmountExceeded { resource: Resource, max_amount: GasAmount, actual_amount: GasAmount },
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1172)* status: 4 of 22 files reviewed, 3 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1172#-O8Wiyq84-JAjP6yhlZl:-O8WzE5c7cmqhi97Dvp8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/eccb0e4bd650656553e495f9a8ec19c00227d7f8/crates/blockifier/src/fee/fee_checks.rs#L20)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Remember - we want numbers without wrappers in error messages.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/fee_test.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1172#-O8WmUpKCUbvWmJSa5JL:-O8WzHTq7gzq4JTImdHV:b-xzazpz) ([raw file](https://github.com/starkware-libs/sequencer/blob/eccb0e4bd650656553e495f9a8ec19c00227d7f8/crates/blockifier/src/fee/fee_test.rs#L84)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Impl `into` for GasAmount?
</blockquote></details>

when going to/from `usize` we want to be explicit
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 364 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1172#-O8WmH_n2gZ_msZHh8R4:-O8Wy_FY6ZZSL59u_Tp_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/eccb0e4bd650656553e495f9a8ec19c00227d7f8/crates/blockifier/src/transaction/account_transaction.rs#L364)):*
> ```XML
>                     // TODO(Aner): refactor to return all amounts that are too low.
>                     // TODO(Ori, 1/2/2024): Write an indicative expect message explaining why the
>                     // conversion works.
> ```

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 22 files at r1, 1 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1172)* status: 6 of 22 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1172#-O8X8G3K408QONPQbqmD:-O8X8G3L3YsP1-UD6Ahy:b3c8f1i) ([raw file](https://github.com/starkware-libs/sequencer/blob/594c451a702bf37f9784ff981415aa6fc33482d0/crates/blockifier/src/fee/fee_checks.rs#L80)):*
> ```XML
>                         &tx_context.block_context.block_info,
>                         GasVector::from_l1_gas(GasAmount(
>                             info.l1_resource_bounds().max_amount.into(),
> ```

Works?
if so, please do so everywhere



_Suggestion:_
```XML
                        GasVector::from_l1_gas(
                            info.l1_resource_bounds().max_amount.into(),
```
___
*[`crates/starknet_api/src/execution_resources.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1172#-O8X7MaSDEvnWooCgSwa:-O8X7MaT5TKi7zErIwVV:b-uhskxe) ([raw file](https://github.com/starkware-libs/sequencer/blob/594c451a702bf37f9784ff981415aa6fc33482d0/crates/starknet_api/src/execution_resources.rs#L41)):*
> ```XML
>         write!(f, "{}", self.0)
>     }
> }
> ```

chatGPT says that `derive_more::Display` does this work



_Code quote:_
```XML
impl Display for GasAmount {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1172)* status: 6 of 22 files reviewed, 4 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1172#-O8X8G3K408QONPQbqmD:-O8XC2mf6rGk5fYgY13K:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/594c451a702bf37f9784ff981415aa6fc33482d0/crates/blockifier/src/fee/fee_checks.rs#L80)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Works?
if so, please do so everywhere
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/execution_resources.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1172#-O8X7MaSDEvnWooCgSwa:-O8XC3Rm4iLRJ7oYNDzM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/594c451a702bf37f9784ff981415aa6fc33482d0/crates/starknet_api/src/execution_resources.rs#L41)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

chatGPT says that `derive_more::Display` does this work
</blockquote></details>

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r1, 5 of 14 files at r2, 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1172)* status: 14 of 22 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 364 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1172#-O8WmH_n2gZ_msZHh8R4:-O8XERwK6TdxcGZgKxtp:b-vtpqbo) ([raw file](https://github.com/starkware-libs/sequencer/blob/eccb0e4bd650656553e495f9a8ec19c00227d7f8/crates/blockifier/src/transaction/account_transaction.rs#L364)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, but you can delete this in the next PR
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 367 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1172#-O8XEeNc4qNA7Q1Ha5qR:-O8XEeNc4qNA7Q1Ha5qS:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/f10a3f264e4d616052770601069c2a22261af2a5/crates/blockifier/src/transaction/account_transaction.rs#L367)):*
> ```XML
>                         return Err(TransactionFeeError::MaxGasAmountTooLow {
>                             resource,
>                             max_gas_amount: u128::from(resource_bounds.max_amount).into(),
> ```





_Suggestion:_
```XML
                    if minimal_gas_amount > resource_bounds.max_amount.into() {
                        return Err(TransactionFeeError::MaxGasAmountTooLow {
                            resource,
                            max_gas_amount: resource_bounds.max_amount.into(),
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 188 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1172#-O8XFDHn6-oL51ef0feA:-O8XFDHo6jKVs1-iTLa7:b-tud054) ([raw file](https://github.com/starkware-libs/sequencer/blob/f10a3f264e4d616052770601069c2a22261af2a5/crates/blockifier/src/transaction/execution_flavors_test.rs#L188)):*
> ```XML
>     // maximum number of arguments.
>     let resource_bounds =
>         l1_resource_bounds(u128::from(MAX_L1_GAS_AMOUNT).into(), MAX_L1_GAS_PRICE);
> ```

Go over `u128::from` and remove most of them



_Suggestion:_
```XML
(MAX_L1_GAS_AMOUNT.into()
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1172)* status: 12 of 22 files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 364 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1172#-O8WmH_n2gZ_msZHh8R4:-O8XK_Rp9CCvVFcq8SJa:bv1dxad) ([raw file](https://github.com/starkware-libs/sequencer/blob/eccb0e4bd650656553e495f9a8ec19c00227d7f8/crates/blockifier/src/transaction/account_transaction.rs#L364)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

No, but you can delete this in the next PR
</blockquote></details>

ah, gotcha - done
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 367 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1172#-O8XEeNc4qNA7Q1Ha5qR:-O8XKIXyBnXjyYWuneWt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f10a3f264e4d616052770601069c2a22261af2a5/crates/blockifier/src/transaction/account_transaction.rs#L367)):*
> ```XML
>                         return Err(TransactionFeeError::MaxGasAmountTooLow {
>                             resource,
>                             max_gas_amount: u128::from(resource_bounds.max_amount).into(),
> ```

Done.
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 188 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1172#-O8XFDHn6-oL51ef0feA:-O8XKWmqDtEYJ-rSzJSz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f10a3f264e4d616052770601069c2a22261af2a5/crates/blockifier/src/transaction/execution_flavors_test.rs#L188)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Go over `u128::from` and remove most of them
</blockquote></details>

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r2, 3 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1172)* status: 16 of 22 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/errors.rs` line 64 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1172#-O8XNp-s2XyMYURdb3y5:-O8XNp-s2XyMYURdb3y6:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac2e90c60de9b512720be93b0c9c14dc5ce9dd4/crates/blockifier/src/transaction/errors.rs#L64)):*
> ```XML
>     #[error(
>         "Max {resource} amount ({max_gas_amount:?}) is lower than the minimal gas amount: \
>          {minimal_gas_amount:?}."
> ```





_Suggestion:_
```XML
        "Max {resource} amount ({max_gas_amount}) is lower than the minimal gas amount: \
         {minimal_gas_amount}."
```

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 22 files at r1, 2 of 4 files at r3, 2 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1172)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1172)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/errors.rs` line 64 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1172#-O8XNp-s2XyMYURdb3y5:-O8XRPKkALMEMAicL9Ap:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ac2e90c60de9b512720be93b0c9c14dc5ce9dd4/crates/blockifier/src/transaction/errors.rs#L64)):*
> ```XML
>     #[error(
>         "Max {resource} amount ({max_gas_amount:?}) is lower than the minimal gas amount: \
>          {minimal_gas_amount:?}."
> ```

Done.

**Pull request merged**
