### PR TITLE
feat(blockifier): add deploy syscall implementation

### PR DESCRIPTION
**Pull request by varex83**

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 3 of 8 files at r6, 1 of 3 files at r7, 2 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @varex83)

___
*[`crates/blockifier/feature_contracts/cairo_native/test_contract.cairo` line 79 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1554#-OATKqdo969eexunclR8:-OATKqdo969eexunclR9:b4omcio) ([raw file](https://github.com/starkware-libs/sequencer/blob/55e0f857c3a85dcce78efcda0966d4323a5865a6/crates/blockifier/feature_contracts/cairo_native/test_contract.cairo#L79)):*
> ```Cairo
>         contract_address_0: ContractAddress,
>         entry_point_selector_0: felt252,
>         calldata_0: Array::<felt252>,
> ```

This shouldn't be part of this PR

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 8 files at r6, 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @varex83)

___
*[`crates/blockifier/src/execution/native/utils.rs` line 31 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1554#-OATP_kz5aeLFyrKr7D7:-OATP_l-61z8cULRi_E1:b-fzmbrc) ([raw file](https://github.com/starkware-libs/sequencer/blob/55e0f857c3a85dcce78efcda0966d4323a5865a6/crates/blockifier/src/execution/native/utils.rs#L31)):*
> ```XML
>     match String::from_utf8(bytes_err) {
>         Ok(s) => s.trim_matches('\0').to_owned(),
>         Err(_) => {
> ```

Shouldn't be part of this PR

**Review by PearsonWhite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: 3 of 35 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo_native/test_contract.cairo` line 79 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1554#-OATKqdo969eexunclR8:-OAhIMxN-Mm60CtpGR3x:by5vxcq) ([raw file](https://github.com/starkware-libs/sequencer/blob/55e0f857c3a85dcce78efcda0966d4323a5865a6/crates/blockifier/feature_contracts/cairo_native/test_contract.cairo#L79)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

This shouldn't be part of this PR
</blockquote></details>

`decode_felts_as_str` is in `cairo_native/src/starknet_stub.rs` now, so I changed this to `use cairo_native::starknet_stub::decode_felts_as_str;` instead of adding the function.
___
*[`crates/blockifier/src/execution/native/utils.rs` line 31 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1554#-OATP_kz5aeLFyrKr7D7:-OAhIxqvEv0ESEThasPK:bioua9q) ([raw file](https://github.com/starkware-libs/sequencer/blob/55e0f857c3a85dcce78efcda0966d4323a5865a6/crates/blockifier/src/execution/native/utils.rs#L31)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Shouldn't be part of this PR
</blockquote></details>

I think this comment was in reference to something that was showing as part of the PR due to an old base branch. Rebased, so this isn't (and shouldn't be) show up as part of the diff anymore.

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 30 files at r10, 1 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: 26 of 35 files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r6, 1 of 4 files at r8, 1 of 30 files at r10, 1 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: 26 of 35 files reviewed, 1 unresolved discussion (waiting on @meship-starkware, @PearsonWhite, and @varex83)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 45 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/1554#-OB16lz9BjFuX69QzvWA:-OB16lz9BjFuX69QzvWB:bbwxp0h) ([raw file](https://github.com/starkware-libs/sequencer/blob/730c4c06c989ccbd08b643500b455dffcf5654ba/crates/blockifier/src/execution/native/entry_point_execution.rs#L45)):*
> ```XML
>         Err(runner_err) => Err(EntryPointExecutionError::NativeUnexpectedError(runner_err)),
>         Ok(res) => Ok(res),
>     }?;
> ```

Why was this change?



_Code quote:_
```XML
        Ok(res) if res.failure_flag => Err(EntryPointExecutionError::NativeExecutionError {
            info: if !res.return_values.is_empty() {
                decode_felts_as_str(&res.return_values)
            } else {
                String::from("Unknown error")
            },
        }),
        Err(runner_err) => Err(EntryPointExecutionError::NativeUnexpectedError(runner_err)),
        Ok(res) => Ok(res),
    }?;
```

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: 26 of 35 files reviewed, 3 unresolved discussions (waiting on @meship-starkware, @noaov1, @PearsonWhite, and @varex83)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 45 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/1554#-OB1CymFCFhudpLaurlF:-OB1CymFCFhudpLaurlG:bblni8h) ([raw file](https://github.com/starkware-libs/sequencer/blob/730c4c06c989ccbd08b643500b455dffcf5654ba/crates/blockifier/src/execution/native/entry_point_execution.rs#L45)):*
> ```XML
>         Err(runner_err) => Err(EntryPointExecutionError::NativeUnexpectedError(runner_err)),
>         Ok(res) => Ok(res),
>     }?;
> ```

I think this is easier to parse



_Suggestion:_
```XML
    ) {
        Ok(res) if res.failure_flag => Err(EntryPointExecutionError::NativeExecutionError {
            info: match res.return_values.is_empty() {
                false => decode_felts_as_str(&res.return_values),
                true => String::from("Unknown error"),
            },
        }),
        Err(runner_err) => Err(EntryPointExecutionError::NativeUnexpectedError(runner_err)),
        Ok(res) => Ok(res),
    }?;
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 221 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/1554#-OB1CYrd6_t_DsTOeTdl:-OB1CYrd6_t_DsTOeTdm:bsoosv4) ([raw file](https://github.com/starkware-libs/sequencer/blob/730c4c06c989ccbd08b643500b455dffcf5654ba/crates/blockifier/src/execution/native/syscall_handler.rs#L221)):*
> ```XML
>         *remaining_gas = u128::from(remaining_gas_u64);
> 
>         let return_data = call_info.execution.retdata.0[..].to_vec();
> ```

(to be consistent with our current syscall)



_Suggestion:_
```XML
        let constructor_retdata = call_info.execution.retdata.0[..].to_vec();
```

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 1 of 8 files at r6, 1 of 4 files at r8, 1 of 30 files at r10, 1 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: 26 of 35 files reviewed, 3 unresolved discussions (waiting on @meship-starkware, @noaov1, @PearsonWhite, and @varex83)

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: 26 of 35 files reviewed, 3 unresolved discussions (waiting on @meship-starkware, @noaov1, @PearsonWhite, and @varex83)

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: 26 of 35 files reviewed, 4 unresolved discussions (waiting on @meship-starkware, @noaov1, @PearsonWhite, and @varex83)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 176 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/1554#-OB1DmbaB1omGPDH_5ZY:-OB1DmbaB1omGPDH_5ZZ:b-ikeqs4) ([raw file](https://github.com/starkware-libs/sequencer/blob/730c4c06c989ccbd08b643500b455dffcf5654ba/crates/blockifier/src/execution/native/syscall_handler.rs#L176)):*
> ```XML
> 
>         let class_hash = ClassHash(class_hash);
>         let wrapper_calldata = Calldata(Arc::new(calldata.to_vec()));
> ```

What do you think?



_Suggestion:_
```XML
        let calldata = Calldata(Arc::new(calldata.to_vec()));
```

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 8 of 30 files at r10, 1 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: all files reviewed, 4 unresolved discussions (waiting on @varex83)

**Review by avi-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r16, 3 of 3 files at r19, all commit messages.
> Dismissed @noaov1 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by avi-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r7, 26 of 30 files at r10, 3 of 3 files at r11, 1 of 2 files at r12, 1 of 2 files at r16, 3 of 3 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554#-:-OBeNTkTDi6hdrhUBPLc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @varex83)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @varex83)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: all files reviewed, 1 unresolved discussion (waiting on @varex83)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1554#-OBe_CHEC55nZ5Gr5wlq:-OATMBkL-2-sj7r_ifJA:b-z0gwj) (no related file):*
Please rebase to resolve conflicts

**Review by meship-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: all files reviewed, 1 unresolved discussion (waiting on @varex83)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: all files reviewed, 1 unresolved discussion (waiting on @varex83)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: all files reviewed, 1 unresolved discussion (waiting on @varex83)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1554)* status: all files reviewed, 1 unresolved discussion (waiting on @varex83)

**Pull request merged**
