### PR TITLE
fix(mempool): fix order bug in transaction queue content

### PR DESCRIPTION
**Pull request by MohammadNassar1**

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAMml2d3Xb8B4yMjYAj:-OAMml2eEtCQnm0uhIom:b-nrsq4p) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ca97c33e9c24ad52ad408288de33f20f36f8f76/crates/mempool/src/transaction_queue_test_utils.rs#L24)):*
> ```XML
>     pub fn assert_eq(&self, tx_queue: &TransactionQueue) {
>         if let Some(priority_queue) = &self.priority_queue {
>             let expected_priority_txs: Vec<_> = priority_queue.iter().map(|tx| &tx.0).collect();
> ```

is it possible to use `zip` instead of `collect` for direct comparison?



_Code quote:_
```XML
collect()
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAMml2d3Xb8B4yMjYAj:-OANqBOj-S6CCyLorRUE:bq98o6u) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ca97c33e9c24ad52ad408288de33f20f36f8f76/crates/mempool/src/transaction_queue_test_utils.rs#L24)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

is it possible to use `zip` instead of `collect` for direct comparison?
</blockquote></details>

If I understand you correctly, you mean somethin like:
`expected_priority_txs.zip(actual_priority_txs)` and then assert_eq on them?

If yes, I think the assertion error message would be less informative than the current code.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAMml2d3Xb8B4yMjYAj:-OARpkiJC1vt5nuLM_-G:b-ofu1a) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ca97c33e9c24ad52ad408288de33f20f36f8f76/crates/mempool/src/transaction_queue_test_utils.rs#L24)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

If I understand you correctly, you mean somethin like:
`expected_priority_txs.zip(actual_priority_txs)` and then assert_eq on them?

If yes, I think the assertion error message would be less informative than the current code.
</blockquote></details>

I agree that comparing iters is better performance-wise, but I'd prefer readability and a more informative error message.

Especially in our tests, we have < 8 txs.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAMml2d3Xb8B4yMjYAj:-OAS8IK7DG98WVj7_zW4:bdi186b) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ca97c33e9c24ad52ad408288de33f20f36f8f76/crates/mempool/src/transaction_queue_test_utils.rs#L24)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I agree that comparing iters is better performance-wise, but I'd prefer readability and a more informative error message.

Especially in our tests, we have < 8 txs.
</blockquote></details>

Ok. @elintul PTAL 
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAS94Id2Zeiqi9e63WR:-OAS94Id2Zeiqi9e63WS:b-ik13w) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ca97c33e9c24ad52ad408288de33f20f36f8f76/crates/mempool/src/transaction_queue_test_utils.rs#L24)):*
> ```XML
>     pub fn assert_eq(&self, tx_queue: &TransactionQueue) {
>         if let Some(priority_queue) = &self.priority_queue {
>             let expected_priority_txs: Vec<_> = priority_queue.iter().map(|tx| &tx.0).collect();
> ```

Not a must, but I think it's better for clarity



_Suggestion:_
```XML
Vec<&TransactionReference>
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAS94Id2Zeiqi9e63WR:-OASZ7JmCN-YDNTwZ8ly:byjyph3) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ca97c33e9c24ad52ad408288de33f20f36f8f76/crates/mempool/src/transaction_queue_test_utils.rs#L24)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Not a must, but I think it's better for clarity
</blockquote></details>

I'd keep it as is, to avoid updating the type if it changes.

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAMml2d3Xb8B4yMjYAj:-OAWXhf0ExvhSgDYPwiX:btd48oj) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ca97c33e9c24ad52ad408288de33f20f36f8f76/crates/mempool/src/transaction_queue_test_utils.rs#L24)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Ok. @elintul PTAL
</blockquote></details>

@MohammadNassar1, please mention to the reviewer what you tried and work or didn't.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAMml2d3Xb8B4yMjYAj:-OAWYo4_4B3Fdjc88igD:b-3o8tmv) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ca97c33e9c24ad52ad408288de33f20f36f8f76/crates/mempool/src/transaction_queue_test_utils.rs#L24)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

@MohammadNassar1, please mention to the reviewer what you tried and work or didn't.
</blockquote></details>

I tried to compare iterators using `a.eq(b)` in the comparison, which is more efficient but less readable and provides less informative error messages.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAMml2d3Xb8B4yMjYAj:-OAWz4q6-APO34_JHdIv:bj9y71y) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ca97c33e9c24ad52ad408288de33f20f36f8f76/crates/mempool/src/transaction_queue_test_utils.rs#L24)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I tried to compare iterators using `a.eq(b)` in the comparison, which is more efficient but less readable and provides less informative error messages.
</blockquote></details>

What about some kind of `zip`, as Ayelet suggested?

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAWzt_46aFaMKC7GP7x:-OAWzt_46aFaMKC7GP7y:bib7abg) ([raw file](https://github.com/starkware-libs/sequencer/blob/5b28318fc69e6e34370e8cd23a36b533dfc6788b/crates/mempool/src/transaction_queue_test_utils.rs#L26)):*
> ```XML
>             let expected_priority_txs: Vec<_> = priority_queue.iter().map(|tx| &tx.0).collect();
>             let actual_priority_txs: Vec<_> = tx_queue.iter_over_ready_txs().collect();
>             assert_eq!(expected_priority_txs, actual_priority_txs);
> ```

Please make sure this is the direction of comparison throughout our tests.



_Code quote:_
```XML
assert_eq!(expected_priority_txs, actual_priority_txs);
```
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAX79x62VFYtF4wboyK:-OAX79x62VFYtF4wboyL:b-qh3n3c) ([raw file](https://github.com/starkware-libs/sequencer/blob/5b28318fc69e6e34370e8cd23a36b533dfc6788b/crates/mempool/src/transaction_queue_test_utils.rs#L32)):*
> ```XML
>             let expected_pending_txs: Vec<_> = pending_queue.iter().map(|tx| &tx.0).collect();
>             let actual_pending_txs: Vec<_> =
>                 tx_queue.pending_queue.iter().rev().map(|tx| &tx.0).collect();
> ```

Is this currently the only usage?



_Code quote:_
```XML
 tx_queue.pending_queue.iter().rev()
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAMml2d3Xb8B4yMjYAj:-OAX4h4E0cMERU5CeUGT:b-nrx9qe) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ca97c33e9c24ad52ad408288de33f20f36f8f76/crates/mempool/src/transaction_queue_test_utils.rs#L24)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What about some kind of `zip`, as Ayelet suggested?
</blockquote></details>

As I wrote above, the suggestion with zip (attached below) is more efficient (it saves the allocations), but on the other side, it's less readable and less helpful in debugging.

Once there is a mismatch it only shows the first mismatch, which may be less helpful if you troubleshoot differences across multiple transactions.

what do you think?



_Code snippet:_
```XML
        if let Some(priority_queue) = &self.priority_queue {
            let expected_priority_txs = priority_queue.iter().map(|tx| &tx.0);
            let actual_priority_txs = tx_queue.iter_over_ready_txs();

            for (expected, actual) in expected_priority_txs.zip(actual_priority_txs) {
                assert_eq!(expected, actual);
            }
        }
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAX79x62VFYtF4wboyK:-OAXACVq4NDdJ0ebAUWg:btwxzb8) ([raw file](https://github.com/starkware-libs/sequencer/blob/5b28318fc69e6e34370e8cd23a36b533dfc6788b/crates/mempool/src/transaction_queue_test_utils.rs#L32)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this currently the only usage?
</blockquote></details>

Correct, that's why I did not add a dedicated function for it.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAWzt_46aFaMKC7GP7x:-OAXBQxRAy_wKMzoNEZk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5b28318fc69e6e34370e8cd23a36b533dfc6788b/crates/mempool/src/transaction_queue_test_utils.rs#L26)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please make sure this is the direction of comparison throughout our tests.
</blockquote></details>

Done.

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by elintul — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAMml2d3Xb8B4yMjYAj:-OAY31wA4nt3z97Fy9ma:bhd3csd) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ca97c33e9c24ad52ad408288de33f20f36f8f76/crates/mempool/src/transaction_queue_test_utils.rs#L24)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`zip` is still comparing iterators, right? Then no.
</blockquote></details>

Correct, the suggestion with `zip` uses iterators.

Do you mean that there is no need to use it?
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAWzt_46aFaMKC7GP7x:-OAY3d_0-VGIZ4iTO88f:bl4j580) ([raw file](https://github.com/starkware-libs/sequencer/blob/5b28318fc69e6e34370e8cd23a36b533dfc6788b/crates/mempool/src/transaction_queue_test_utils.rs#L26)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What about rest of our tests (and utils)? Can be done in another PR.
</blockquote></details>

They are aligned. Note that the tests use `MempoolContent` assertions, not `assert_eq`. 

I'll review the assertion, and if I find a matching one, I'll fix it in a separate PR.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAMml2d3Xb8B4yMjYAj:-OAY4oXl9iBIEfgJoDqq:b9pij7i) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ca97c33e9c24ad52ad408288de33f20f36f8f76/crates/mempool/src/transaction_queue_test_utils.rs#L24)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Correct, the suggestion with `zip` uses iterators.

Do you mean that there is no need to use it?
</blockquote></details>

Yup, as I wrote in Slack last week.
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAWzt_46aFaMKC7GP7x:-OAY4uV7ED29L4mjwAzj:b-v8ru5i) ([raw file](https://github.com/starkware-libs/sequencer/blob/5b28318fc69e6e34370e8cd23a36b533dfc6788b/crates/mempool/src/transaction_queue_test_utils.rs#L26)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

They are aligned. Note that the tests use `MempoolContent` assertions, not `assert_eq`. 

I'll review the assertion, and if I find a matching one, I'll fix it in a separate PR.
</blockquote></details>

WDYM? There's a `MempoolContent::assert_eq` method.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAWzt_46aFaMKC7GP7x:-OAlGW5V5Zcbs8EWAaP2:b-7ehsxv) ([raw file](https://github.com/starkware-libs/sequencer/blob/5b28318fc69e6e34370e8cd23a36b533dfc6788b/crates/mempool/src/transaction_queue_test_utils.rs#L26)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How is this different from what I wrote?
So asking again: do we always compare in this order: "actual" on LHS and "expected" on RHS?
Consistency will make it easier to debug.
</blockquote></details>

I see now what you mean. 
The `assert_eq!()` in the `MempoolContent` has the same order.
So, it's consistent with the rest of the tests & the utils.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-:-OAlI9mG9Ect-gW8M9hN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1544)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1544#-OAWzt_46aFaMKC7GP7x:-OAlCm7k-iGBP3xG6Zmx:b96aub8) ([raw file](https://github.com/starkware-libs/sequencer/blob/5b28318fc69e6e34370e8cd23a36b533dfc6788b/crates/mempool/src/transaction_queue_test_utils.rs#L26)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

[Example](https://github.com/starkware-libs/sequencer/blob/5d977d2b493cba3c0584bde2d37fae8f7ac0ef49/crates/mempool/src/mempool_test.rs#L154).

In the tests, we use `expected_mempool_content.assert_eq(mempool)` instead of `assert_eq!(mempool, expected_mempool)`
</blockquote></details>

How is this different from what I wrote?
So asking again: do we always compare in this order: "actual" on LHS and "expected" on RHS?
Consistency will make it easier to debug.

**Pull request merged**
