### PR TITLE
feat(network): blacklist peers after a threshold of malicious activities has been reached

### PR DESCRIPTION
**Pull request by AlonLStarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/991)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/991)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @AlonLStarkWare)

___
*[`crates/papyrus_network/src/network_manager/swarm_trait.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O87Lo3o6Tgb8IQH2w_K:-O87Lo3o6Tgb8IQH2w_L:b4ynx80) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e595fd5ddf8068e1a8f4851ae077055e3483a3/crates/papyrus_network/src/network_manager/swarm_trait.rs#L132)):*
> ```XML
>             .behaviour_mut()
>             .peer_manager
>             .report_peer(peer_id, ReputationModifier::Malicious { maliciousness: 1.0 });
> ```

I don't like the name maliciousness. How about score? penalty?
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O86EWEI9TuytB1fMVMf:-O86EWEI9TuytB1fMVMg:b-429q4m) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e595fd5ddf8068e1a8f4851ae077055e3483a3/crates/papyrus_network/src/peer_manager/mod.rs#L27)):*
> ```XML
> #[derive(Clone, Copy)]
> pub enum ReputationModifier {
>     Malicious { maliciousness: f64 },
> ```

Add documentation that maliciousness should be between 0 and 1 and if the sum of malicious activity is above 1 then the node is considered malicious
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O86F3O-61QD_XW9sgs2:-O86F3O-61QD_XW9sgs3:b-7p6od2) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e595fd5ddf8068e1a8f4851ae077055e3483a3/crates/papyrus_network/src/peer_manager/peer.rs#L27)):*
> ```XML
>     fn remove_connection_id(&mut self, connection_id: ConnectionId);
> 
>     fn get_maliciousness(&self) -> f64;
> ```

Instead of these two functions, define the following functions:

1. report(&mut self, maliciousness: f64)
2. is_malicious(&self) -> bool
3. reset_maliciousness(&mut self)

The main idea is that the functions should contain as much "implementation details" inside them rather than exposing the implementation in the API
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O87LhF_4_a154Ut2ORY:-O87LhF_4_a154Ut2ORZ:b-i0moxu) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e595fd5ddf8068e1a8f4851ae077055e3483a3/crates/papyrus_network/src/peer_manager/test.rs#L289)):*
> ```XML
> 
>     peer_manager
>         .report_session(outbound_session_id, ReputationModifier::Malicious { maliciousness: 1.0 })
> ```

Add 1.0 as a constant called MALICIOUS in peer_manager/mod.rs. Name the constant according to the name you chose for the rename of maliciousness (e.g MALICIOUS_SCORE)

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/991)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/swarm_trait.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O87Lo3o6Tgb8IQH2w_K:-O8pUF3W67IRaRyu5LFh:bl0jgey) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e595fd5ddf8068e1a8f4851ae077055e3483a3/crates/papyrus_network/src/network_manager/swarm_trait.rs#L132)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I don't like the name maliciousness. How about score? penalty?
</blockquote></details>

Of course, it was a placeholder name. How about misconduct_score?
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O86F3O-61QD_XW9sgs2:-O8qQelY4XJHscpy8MWO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e595fd5ddf8068e1a8f4851ae077055e3483a3/crates/papyrus_network/src/peer_manager/peer.rs#L27)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Instead of these two functions, define the following functions:

1. report(&mut self, maliciousness: f64)
2. is_malicious(&self) -> bool
3. reset_maliciousness(&mut self)

The main idea is that the functions should contain as much "implementation details" inside them rather than exposing the implementation in the API
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O87LhF_4_a154Ut2ORY:-O8qQdj447H-CEEItryC:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e595fd5ddf8068e1a8f4851ae077055e3483a3/crates/papyrus_network/src/peer_manager/test.rs#L289)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add 1.0 as a constant called MALICIOUS in peer_manager/mod.rs. Name the constant according to the name you chose for the rename of maliciousness (e.g MALICIOUS_SCORE)
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/991)* status: all files reviewed, 7 unresolved discussions (waiting on @AlonLStarkWare)

___
*[`crates/papyrus_network/src/network_manager/swarm_trait.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O87M9e_5FlgIynLE9l3:-O87M9e_5FlgIynLE9l4:baqe184) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e595fd5ddf8068e1a8f4851ae077055e3483a3/crates/papyrus_network/src/network_manager/swarm_trait.rs#L128)):*
> ```XML
>     }
> 
>     fn report_peer_as_malicious(&mut self, peer_id: PeerId) {
> ```

Add TODO to change this to report_peer, receive a score here as an argument and receive a score from the user when they report peer with BroadcastedMessageMetadata
___
*[`crates/papyrus_network/src/network_manager/swarm_trait.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O87Lo3o6Tgb8IQH2w_K:-O94qej870u_GbJ-HQT-:b-4xdfyh) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e595fd5ddf8068e1a8f4851ae077055e3483a3/crates/papyrus_network/src/network_manager/swarm_trait.rs#L132)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

Of course, it was a placeholder name. How about misconduct_score?
</blockquote></details>

Great! now rename ReputationModifier::Malicious to ReputationModifier::Misconduct
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O94qo425n7oYKnQbBMu:-O94qo425n7oYKnQbBMv:b-qpnyy) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e33d95cdd9c0216a020484e820a16fb5323810/crates/papyrus_network/src/peer_manager/mod.rs#L29)):*
> ```XML
> #[derive(Clone, Copy)]
> pub enum ReputationModifier {
>     Malicious { misconduct_score: f64 }, /* misconduct_score is in the range [0, 1]. When a
> ```

Change the comment into a `///` on top of the variant
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O94r3m47nLDYX4aEBQf:-O94r3m47nLDYX4aEBQg:b-6ujpca) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e33d95cdd9c0216a020484e820a16fb5323810/crates/papyrus_network/src/peer_manager/mod.rs#L30)):*
> ```XML
> pub enum ReputationModifier {
>     Malicious { misconduct_score: f64 }, /* misconduct_score is in the range [0, 1]. When a
>                                           * peer's misconduct_score reaches 1, it is
> ```

when a peer's total/sum misconduct_score reaches 1, ...
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O94rJqE24Yf6RQwz4X-:-O94rJqE24Yf6RQwz4X0:b-xfuhqt) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e33d95cdd9c0216a020484e820a16fb5323810/crates/papyrus_network/src/peer_manager/peer.rs#L50)):*
> ```XML
>             timed_out_until: get_instant_now(),
>             connection_ids: Vec::new(),
>             misconduct_score: 0 as f64,
> ```

write 0f64 instead of 0 as f64
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O94rN3MDoaZjaybM2ql:-O94rN3MDoaZjaybM2qm:b-xfuhqt) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e33d95cdd9c0216a020484e820a16fb5323810/crates/papyrus_network/src/peer_manager/peer.rs#L96)):*
> ```XML
> 
>     fn reset_misconduct_score(&mut self) {
>         self.misconduct_score = 0 as f64;
> ```

write 0f64 instead of 0 as f64
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O94rSiG9Qy6rRe6IsK1:-O94rSiG9Qy6rRe6IsK2:b-k8i4pl) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e33d95cdd9c0216a020484e820a16fb5323810/crates/papyrus_network/src/peer_manager/peer.rs#L104)):*
> ```XML
> 
>     fn is_malicious(&self) -> bool {
>         1.0 <= self.misconduct_score
> ```

write 1.0f64 just to be sure that rust doesn't auto cast misconduct_score to f32

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/991)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/swarm_trait.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O87M9e_5FlgIynLE9l3:-O9E9xpO1i-8wYQEI_OB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e595fd5ddf8068e1a8f4851ae077055e3483a3/crates/papyrus_network/src/network_manager/swarm_trait.rs#L128)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to change this to report_peer, receive a score here as an argument and receive a score from the user when they report peer with BroadcastedMessageMetadata
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O94qo425n7oYKnQbBMu:-O9EAzgK9IqmWKO2NUjo:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e33d95cdd9c0216a020484e820a16fb5323810/crates/papyrus_network/src/peer_manager/mod.rs#L29)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change the comment into a `///` on top of the variant
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O94r3m47nLDYX4aEBQf:-O9EAzSL2Psn8PaeJDVP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e33d95cdd9c0216a020484e820a16fb5323810/crates/papyrus_network/src/peer_manager/mod.rs#L30)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

when a peer's total/sum misconduct_score reaches 1, ...
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O94rJqE24Yf6RQwz4X-:-O9EB6acCZY2srLSPscg:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e33d95cdd9c0216a020484e820a16fb5323810/crates/papyrus_network/src/peer_manager/peer.rs#L50)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

write 0f64 instead of 0 as f64
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O94rN3MDoaZjaybM2ql:-O9EB9x6B3BcPZRzz4tA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e33d95cdd9c0216a020484e820a16fb5323810/crates/papyrus_network/src/peer_manager/peer.rs#L96)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

write 0f64 instead of 0 as f64
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O94rSiG9Qy6rRe6IsK1:-O9EBDHm2o6oqrymbc3H:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e33d95cdd9c0216a020484e820a16fb5323810/crates/papyrus_network/src/peer_manager/peer.rs#L104)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

write 1.0f64 just to be sure that rust doesn't auto cast misconduct_score to f32
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/991)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare)

___
*[`crates/papyrus_network/src/network_manager/swarm_trait.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O87M9e_5FlgIynLE9l3:-O9EfSK-4nzGuIWjLwZw:bg78lpj) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e595fd5ddf8068e1a8f4851ae077055e3483a3/crates/papyrus_network/src/network_manager/swarm_trait.rs#L128)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Where's the TODO

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/991)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/swarm_trait.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/991#-O87M9e_5FlgIynLE9l3:-O9Eol3k3N-x5l8uxG1y:bd2sb55) ([raw file](https://github.com/starkware-libs/sequencer/blob/07e595fd5ddf8068e1a8f4851ae077055e3483a3/crates/papyrus_network/src/network_manager/swarm_trait.rs#L128)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Where's the TODO
</blockquote></details>

Added in the trait

**Review by ShahakShama — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/991)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/991#-:-O9EpWRH-x3LvckPZD8x:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Pull request merged**
