### PR TITLE
refactor(gateway): send internal tx instead of thin tx

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O40jxrPA5O_3onqAMJB:-O40jxrQCz8o2jVfFrMA:bw4wfx9) (no related file):*
Add default external to internal conversion in GW.

___

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/utils.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O44OpYpCPFUU66WMN9U:-O44OpYpCPFUU66WMN9V:b80p687) ([raw file](https://github.com/starkware-libs/sequencer/blob/b403e16374bbefacf6ef5ac0c401213da053a2da/crates/gateway/src/utils.rs#L34)):*
> ```XML
> use crate::errors::StatefulTransactionValidatorResult;
> 
> pub fn external_tx_to_internal_tx(
> ```

I find the `Transaction' / 'internal_tx` mismatch very confusing.



_Code quote:_
```XML
external_tx_to_internal_tx
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/gateway/src/utils.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O44OpYpCPFUU66WMN9U:-O4AU6QA7hQpb4wBOoey:bki0cr) ([raw file](https://github.com/starkware-libs/sequencer/blob/b403e16374bbefacf6ef5ac0c401213da053a2da/crates/gateway/src/utils.rs#L34)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I find the `Transaction' / 'internal_tx` mismatch very confusing.
</blockquote></details>

Let's discuss it F2F.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/utils.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O44OpYpCPFUU66WMN9U:-O4AdwGoDdPEjcq2vHNe:b-uy8p67) ([raw file](https://github.com/starkware-libs/sequencer/blob/b403e16374bbefacf6ef5ac0c401213da053a2da/crates/gateway/src/utils.rs#L34)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Let's discuss it F2F.
</blockquote></details>

Why not `external_tx_to_executable_tx`?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/gateway/src/utils.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O44OpYpCPFUU66WMN9U:-O4K8zc5BV5kVCazLIx9:bo8fhjk) ([raw file](https://github.com/starkware-libs/sequencer/blob/b403e16374bbefacf6ef5ac0c401213da053a2da/crates/gateway/src/utils.rs#L34)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Why not `external_tx_to_executable_tx`?
</blockquote></details>

I Like it. Updated!

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, and @MohammadNassar1)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4KOJDc-FG5n-xUz4e1):*
fix



_Code quote:_
```
internal tx
```
___
*[`crates/gateway/src/utils.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O44OpYpCPFUU66WMN9U:-O4KO-4c13PFboWGP_UU:b-5q9x1d) ([raw file](https://github.com/starkware-libs/sequencer/blob/b403e16374bbefacf6ef5ac0c401213da053a2da/crates/gateway/src/utils.rs#L34)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I Like it. Updated!
</blockquote></details>

are you going to change 'Transaction` to `ExecutabkleTransaction`?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/gateway/src/utils.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O44OpYpCPFUU66WMN9U:-O4KSHXe-Zt1_iLrtxnV:b-x28rsp) ([raw file](https://github.com/starkware-libs/sequencer/blob/b403e16374bbefacf6ef5ac0c401213da053a2da/crates/gateway/src/utils.rs#L34)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

are you going to change 'Transaction` to `ExecutabkleTransaction`?
</blockquote></details>

changed already

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: all files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4ZLXk_2fddPuR5biqx:-O4ZLXk_2fddPuR5biqy:bj6opre) (no related file):*
Please update commit message.

___
___
*[`crates/gateway/src/gateway.rs` line 146 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4ZLAGN7tU-oC96jSq3:-O4ZLAGO7CGnF1qxJanz:b-vcbm1e) ([raw file](https://github.com/starkware-libs/sequencer/blob/f466382c9a732cde6f40c2264c7e22e8df251537/crates/gateway/src/gateway.rs#L146)):*
> ```XML
>     // TODO(Arni): Add the Sierra and the Casm to the mempool input.
>     Ok(MempoolInput {
>         tx: external_tx_to_executable_tx(&tx, validate_info.tx_hash, validate_info.sender_address),
> ```

Add `new_from_rpc_tx` to `ExecutableTransaction`; better than a floating function.



_Code quote:_
```XML
external_tx_to_executable_tx
```
___
*[`crates/gateway/src/utils.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4ZLUFrDtGz9nnqTiSl:-O4ZLUFs4kPdXvAjdnvU:b-umahpp) ([raw file](https://github.com/starkware-libs/sequencer/blob/f466382c9a732cde6f40c2264c7e22e8df251537/crates/gateway/src/utils.rs#L40)):*
> ```XML
>     tx_hash: TransactionHash,
>     sender_address: ContractAddress,
> ) -> Transaction {
> ```

Why is this repeating? I saw this in other PRs.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4ZLXk_2fddPuR5biqx:-O4_pi-v3o2tFA0DgJvI:b-cypxrc) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please update commit message.
</blockquote></details>

updated.

___
___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4KOJDc-FG5n-xUz4e1):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

fix
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 146 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4ZLAGN7tU-oC96jSq3:-O4_ohXjC8ekuKVHMKuO:b7puugh) ([raw file](https://github.com/starkware-libs/sequencer/blob/f466382c9a732cde6f40c2264c7e22e8df251537/crates/gateway/src/gateway.rs#L146)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add `new_from_rpc_tx` to `ExecutableTransaction`; better than a floating function.
</blockquote></details>

What do you mean to rename the function?
Or to use a method instead?
___
*[`crates/gateway/src/utils.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4ZLUFrDtGz9nnqTiSl:-O4_pPuRB8NgmFcm_f_2:b-45y3f6) ([raw file](https://github.com/starkware-libs/sequencer/blob/f466382c9a732cde6f40c2264c7e22e8df251537/crates/gateway/src/utils.rs#L40)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is this repeating? I saw this in other PRs.
</blockquote></details>

This one converts from external to full transaction.
The other one converts from thin tx to full tx, and it's temporal, removed [here](https://reviewable.io/reviews/starkware-libs/sequencer/377).

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 146 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4ZLAGN7tU-oC96jSq3:-O4d8TwO-esDya4GBqzZ:b-8a9w6w) ([raw file](https://github.com/starkware-libs/sequencer/blob/f466382c9a732cde6f40c2264c7e22e8df251537/crates/gateway/src/gateway.rs#L146)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

What do you mean to rename the function?
Or to use a method instead?
</blockquote></details>

Both.
___
*[`crates/gateway/src/utils.rs` line 51 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4d8_u76Z2dOtBC-dDL:-O4d8_u76Z2dOtBC-dDM:bhfvc6p) ([raw file](https://github.com/starkware-libs/sequencer/blob/4cda367d64493fadb9f1b7e082c6b0347b6e4e35/crates/gateway/src/utils.rs#L51)):*
> ```XML
>                 calldata: Calldata::default(),
>                 nonce_data_availability_mode: DataAvailabilityMode::L1,
>                 fee_data_availability_mode: DataAvailabilityMode::L2,
> ```

Please be minded.



_Suggestion:_
```XML
L1
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/starknet_api/src/rpc_transaction.rs` line 89 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4domjIBINvNIXHDlw4:-O4domjIBINvNIXHDlw5:b6oh3lw) ([raw file](https://github.com/starkware-libs/sequencer/blob/588350dae2759d7d85beb13b493cb54d8babd9b2/crates/starknet_api/src/rpc_transaction.rs#L89)):*
> ```XML
>     // TODO(Arni): Update the function to support all transaction types.
>     pub fn new_from_rpc_tx(
>         &self,
> ```

How come `&self` is passed? This should be a c-tor.



_Suggestion:_
```XML
    }
    
    // TODO(Arni): Update the function to support all transaction types.
    pub fn new_from_rpc_tx(
        &self,
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/starknet_api/src/rpc_transaction.rs` line 89 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4domjIBINvNIXHDlw4:-O4dpH7VAu1JyFz2VdyE:b-pnvmw2) ([raw file](https://github.com/starkware-libs/sequencer/blob/588350dae2759d7d85beb13b493cb54d8babd9b2/crates/starknet_api/src/rpc_transaction.rs#L89)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How come `&self` is passed? This should be a c-tor.
</blockquote></details>

A c-tor of `Transaction`.

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @giladchase, and @MohammadNassar1)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: all files reviewed, 7 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 67 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4drrJ0DYBfFD4q-YhG:-O4drrJ12dZ_IzdM0mjT:b-kije9p) ([raw file](https://github.com/starkware-libs/sequencer/blob/1550b813c32d9a38117f8ef5923e3d6a0881b1bb/crates/starknet_api/src/executable_transaction.rs#L67)):*
> ```XML
>     // TODO(Arni): Update the function to support all transaction types.
>     pub fn new_from_rpc_tx(
>         rpc_tx: crate::rpc_transaction::RpcTransaction,
> ```

Why fully-qualified?



_Code quote:_
```XML
crate::rpc_transaction::RpcTransaction
```
___
*[`crates/starknet_api/src/executable_transaction.rs` line 74 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4dsGLL7rmoyiBFCWwj:-O4dsGLL7rmoyiBFCWwk:b-5d6m81) ([raw file](https://github.com/starkware-libs/sequencer/blob/1550b813c32d9a38117f8ef5923e3d6a0881b1bb/crates/starknet_api/src/executable_transaction.rs#L74)):*
> ```XML
>             tx: crate::transaction::InvokeTransaction::V3(
>                 crate::transaction::InvokeTransactionV3 {
>                     sender_address,
> ```

For invoke, take the address from the input transaction.



_Code quote:_
```XML
sender_address,
```
___
*[`crates/starknet_api/src/executable_transaction.rs` line 76 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4dsCUJ78dyv8kVg8bj:-O4dsCUJ78dyv8kVg8bk:b-h27bku) ([raw file](https://github.com/starkware-libs/sequencer/blob/1550b813c32d9a38117f8ef5923e3d6a0881b1bb/crates/starknet_api/src/executable_transaction.rs#L76)):*
> ```XML
>                     sender_address,
>                     tip: *rpc_tx.tip(),
>                     nonce: *rpc_tx.nonce(),
> ```

Why cloning?



_Code quote:_
```XML
                    tip: *rpc_tx.tip(),
                    nonce: *rpc_tx.nonce(),
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 146 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4ZLAGN7tU-oC96jSq3:-O4dom2C5yCBJ7JoOUFX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f466382c9a732cde6f40c2264c7e22e8df251537/crates/gateway/src/gateway.rs#L146)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Both.
</blockquote></details>

Done.
___
*[`crates/gateway/src/utils.rs` line 51 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4d8_u76Z2dOtBC-dDL:-O4dEWqE1aocPMkWI6Jk:bhuf6yg) ([raw file](https://github.com/starkware-libs/sequencer/blob/4cda367d64493fadb9f1b7e082c6b0347b6e4e35/crates/gateway/src/utils.rs#L51)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please be minded.
</blockquote></details>

Sorry :(.
___
*[`crates/starknet_api/src/executable_transaction.rs` line 67 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4drrJ0DYBfFD4q-YhG:-O4dspDs0xD5GXuci32_:b-hfpv0l) ([raw file](https://github.com/starkware-libs/sequencer/blob/1550b813c32d9a38117f8ef5923e3d6a0881b1bb/crates/starknet_api/src/executable_transaction.rs#L67)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why fully-qualified?
</blockquote></details>

removed
___
*[`crates/starknet_api/src/rpc_transaction.rs` line 89 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4domjIBINvNIXHDlw4:-O4dsoEEEGXdTGzRpOry:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/588350dae2759d7d85beb13b493cb54d8babd9b2/crates/starknet_api/src/rpc_transaction.rs#L89)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

A c-tor of `Transaction`.
</blockquote></details>

Done.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @Arni, @ArniStarkware, @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 74 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4dsGLL7rmoyiBFCWwj:-O4dt9uJ1dJKG-Pu4ufR:b6i42wx) ([raw file](https://github.com/starkware-libs/sequencer/blob/1550b813c32d9a38117f8ef5923e3d6a0881b1bb/crates/starknet_api/src/executable_transaction.rs#L74)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

For invoke, take the address from the input transaction.
</blockquote></details>

The sender address is calculated during the stateful validation.
and the method should be generic (@arni will update it). 
___
*[`crates/starknet_api/src/executable_transaction.rs` line 76 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4dsCUJ78dyv8kVg8bj:-O4dtYaY6Re5YC9XBXcH:b-wt0kqi) ([raw file](https://github.com/starkware-libs/sequencer/blob/1550b813c32d9a38117f8ef5923e3d6a0881b1bb/crates/starknet_api/src/executable_transaction.rs#L76)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why cloning?
</blockquote></details>

It returns &Nonce, and &Tip.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: all files reviewed, 5 unresolved discussions (waiting on @Arni, @ArniStarkware, @ayeletstarkware, and @giladchase)

___
*[`crates/gateway/src/utils.rs` line 51 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4d8_u76Z2dOtBC-dDL:-O4e0Vc9BmGQgcrxYY-U:b-vqkjuf) ([raw file](https://github.com/starkware-libs/sequencer/blob/4cda367d64493fadb9f1b7e082c6b0347b6e4e35/crates/gateway/src/utils.rs#L51)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Sorry :(.
</blockquote></details>

No worries.
___
*[`crates/starknet_api/src/executable_transaction.rs` line 67 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4drrJ0DYBfFD4q-YhG:-O4dyChF6TFgO_93xXrH:b-51m43j) ([raw file](https://github.com/starkware-libs/sequencer/blob/1550b813c32d9a38117f8ef5923e3d6a0881b1bb/crates/starknet_api/src/executable_transaction.rs#L67)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

removed
</blockquote></details>

Can it receive it by value? The `RpcTransaction` isn't used after this.
___
*[`crates/starknet_api/src/executable_transaction.rs` line 74 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4dsGLL7rmoyiBFCWwj:-O4dyHUBA009zMF4cnxM:b-c105zt) ([raw file](https://github.com/starkware-libs/sequencer/blob/1550b813c32d9a38117f8ef5923e3d6a0881b1bb/crates/starknet_api/src/executable_transaction.rs#L74)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

The sender address is calculated during the stateful validation.
and the method should be generic (@arni will update it).
</blockquote></details>

For invoke, it shouldn't be used.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: all files reviewed, 5 unresolved discussions (waiting on @Arni, @ArniStarkware, @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 67 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4drrJ0DYBfFD4q-YhG:-O4egQ_u7boNtUWmT5AX:bylxa4l) ([raw file](https://github.com/starkware-libs/sequencer/blob/1550b813c32d9a38117f8ef5923e3d6a0881b1bb/crates/starknet_api/src/executable_transaction.rs#L67)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can it receive it by value? The `RpcTransaction` isn't used after this.
</blockquote></details>

Can you explain, please, why we need to pass by value and not by ref?
What if we'll use it after this?

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: all files reviewed, 5 unresolved discussions (waiting on @Arni, @ArniStarkware, @ayeletstarkware, and @giladchase)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 67 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4drrJ0DYBfFD4q-YhG:-O4emjiCBxy9vdEnEdsN:bpzb2vi) ([raw file](https://github.com/starkware-libs/sequencer/blob/1550b813c32d9a38117f8ef5923e3d6a0881b1bb/crates/starknet_api/src/executable_transaction.rs#L67)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can you explain, please, why we need to pass by value and not by ref?
What if we'll use it after this?
</blockquote></details>

But we don't, it's the return value of `process_tx`; i.e., the last line of the function.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @giladchase)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 74 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4dsGLL7rmoyiBFCWwj:-O4eqQsHCnz5dOjuQfws:bszvhi8) ([raw file](https://github.com/starkware-libs/sequencer/blob/1550b813c32d9a38117f8ef5923e3d6a0881b1bb/crates/starknet_api/src/executable_transaction.rs#L74)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

For invoke, it shouldn't be used.
</blockquote></details>

Add a TODO with your suggestion.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360#-:-O4eslv0CE8BsPnkmAgM:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @giladchase)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 67 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4drrJ0DYBfFD4q-YhG:-O4exxDa1NCym585tU1j:bfn4kj6) ([raw file](https://github.com/starkware-libs/sequencer/blob/1550b813c32d9a38117f8ef5923e3d6a0881b1bb/crates/starknet_api/src/executable_transaction.rs#L67)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

But we don't, it's the return value of `process_tx`; i.e., the last line of the function.
</blockquote></details>

Changed to by value.
___
*[`crates/starknet_api/src/executable_transaction.rs` line 74 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4dsGLL7rmoyiBFCWwj:-O4ez3SR8Mmu2oGGtzfQ:bqmjwcz) ([raw file](https://github.com/starkware-libs/sequencer/blob/1550b813c32d9a38117f8ef5923e3d6a0881b1bb/crates/starknet_api/src/executable_transaction.rs#L74)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a TODO with your suggestion.
</blockquote></details>

Added.

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @giladchase)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 67 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/360#-O4drrJ0DYBfFD4q-YhG:-O4f7_UKEBWWWmu-tBaL:bdec8p9) ([raw file](https://github.com/starkware-libs/sequencer/blob/1550b813c32d9a38117f8ef5923e3d6a0881b1bb/crates/starknet_api/src/executable_transaction.rs#L67)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Changed to by value.
</blockquote></details>

For the record: this is temporary, until Sierra class is sent to mempool, to be propagated by P2P.

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, 1 of 3 files at r9, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @giladchase)

**Review by ayeletstarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/360)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @giladchase)

**Pull request merged**
