### PR TITLE
chore(blockifier): add runnable cairo version to the cairo version enum

### PR DESCRIPTION
**Pull request by meship-starkware**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 33 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2503)* status: all files reviewed, 5 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2503#-OD_ZZR49JKQL5mvjnnR:-OD_ZZR49JKQL5mvjnnS:bg1k475) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b28f4a5cf7b0d245fcbe3bb75f2c0ad31f9f8fc/crates/blockifier/src/test_utils/contracts.rs#L131)):*
> ```XML
>             Self::SierraExecutionInfoV1Contract => {
>                 CairoVersion::Cairo1(RunnableCairoVersion::Native)
>             }
> ```

this will change in the next PR to return the inner runnable cairo1 version?
or will this contract stay "only native"?



_Code quote:_
```XML
            Self::SierraExecutionInfoV1Contract => {
                CairoVersion::Cairo1(RunnableCairoVersion::Native)
            }
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 310 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2503#-OD_Zm7o6HuDEz1z33MD:-OD_Zm7o6HuDEz1z33ME:bbxkbx1) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b28f4a5cf7b0d245fcbe3bb75f2c0ad31f9f8fc/crates/blockifier/src/test_utils/contracts.rs#L310)):*
> ```XML
>     pub fn get_sierra_path(&self) -> String {
>         assert_ne!(self.cairo_version(), CairoVersion::Cairo0);
>         assert_ne!(self, &Self::ERC20(CairoVersion::Cairo1(RunnableCairoVersion::Casm)));
> ```

what if the ERC20 is native? this can be constructed, compiler won't protect us



_Code quote:_
```XML
assert_ne!(self, &Self::ERC20(CairoVersion::Cairo1(RunnableCairoVersion::Casm)));
```
___
*[`crates/blockifier/src/test_utils.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2503#-OD_XTil41E5z3em6HBL:-OD_XTil41E5z3em6HBM:bal7ov5) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b28f4a5cf7b0d245fcbe3bb75f2c0ad31f9f8fc/crates/blockifier/src/test_utils.rs#L63)):*
> ```XML
> 
> #[derive(Clone, Hash, PartialEq, Eq, Copy, Debug)]
> pub enum RunnableCairoVersion {
> ```

please add the `1` for clarity.
I would also drop the `Version` - it's not a difference in versions, actually, just the execution framework



_Suggestion:_
```XML
RunnableCairo1
```
___
*[`crates/blockifier/src/test_utils.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2503#-OD_XkON4aGPg5J0WITg:-OD_XkON4aGPg5J0WITh:bj9awcv) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b28f4a5cf7b0d245fcbe3bb75f2c0ad31f9f8fc/crates/blockifier/src/test_utils.rs#L106)):*
> ```XML
>             }
>         }
>     }
> ```

is this deleted in PR 2464? because it should be...
if native feature is active, calling this function should always panic imo, `Cairo0.other_version()` is not well defined if native exists



_Code quote:_
```XML
    pub fn other(&self) -> Self {
        match self {
            Self::Cairo0 => CairoVersion::Cairo1(RunnableCairoVersion::Casm),
            CairoVersion::Cairo1(RunnableCairoVersion::Casm) => Self::Cairo0,
            #[cfg(feature = "cairo_native")]
            CairoVersion::Cairo1(RunnableCairoVersion::Native) => {
                panic!("There is no other version for native")
            }
        }
    }
```
___
*[`crates/blockifier/src/test_utils.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2503#-OD_Y3Tp-ohIiqUeMc1M:-OD_Y3TqDa2yzT3BSzjT:b-ru0x2g) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b28f4a5cf7b0d245fcbe3bb75f2c0ad31f9f8fc/crates/blockifier/src/test_utils.rs#L136)):*
> ```XML
>             Self::CairoVersion(CairoVersion::Cairo1(RunnableCairoVersion::Native)) => {
>                 TrackedResource::SierraGas
>             }
> ```

less boilerplate :)



_Suggestion:_
```XML
            Self::CairoVersion(CairoVersion::Cairo1(_)) => TrackedResource::SierraGas,
```
___
*[`crates/blockifier/src/test_utils.rs` line 370 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2503#-OD_YRXO55HeVKpcCFmk:-OD_YRXO55HeVKpcCFml:b-s7utk5) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b28f4a5cf7b0d245fcbe3bb75f2c0ad31f9f8fc/crates/blockifier/src/test_utils.rs#L370)):*
> ```XML
>                     )
>                 }
>             }
> ```

this macro should behave the same for all cairo1 contracts regardless of running framework, right? 



_Suggestion:_
```XML
            CairoVersion::Cairo1(_) => {
                if let $crate::transaction::errors::TransactionExecutionError::ValidateTransactionError {
                    error, ..
                } = $error {
                    assert_eq!(
                        error.to_string(),
                        "Execution failed. Failure reason: 0x496e76616c6964207363656e6172696f \
                         ('Invalid scenario')."
                    )
                }
            }
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2503)* status: all files reviewed, 5 unresolved discussions (waiting on @meship-starkware)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2503)* status: 0 of 33 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2503#-OD_XTil41E5z3em6HBL:-ODa89pN0PMRPNICh2Kz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b28f4a5cf7b0d245fcbe3bb75f2c0ad31f9f8fc/crates/blockifier/src/test_utils.rs#L63)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add the `1` for clarity.
I would also drop the `Version` - it's not a difference in versions, actually, just the execution framework
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2503#-OD_XkON4aGPg5J0WITg:-ODa4IbcB7z4O-1J5x0d:biea2sy) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b28f4a5cf7b0d245fcbe3bb75f2c0ad31f9f8fc/crates/blockifier/src/test_utils.rs#L106)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this deleted in PR 2464? because it should be...
if native feature is active, calling this function should always panic imo, `Cairo0.other_version()` is not well defined if native exists
</blockquote></details>

It is deleted in the next PR
___
*[`crates/blockifier/src/test_utils.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2503#-OD_Y3Tp-ohIiqUeMc1M:-ODaBVApBp8sbc3AkBgc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b28f4a5cf7b0d245fcbe3bb75f2c0ad31f9f8fc/crates/blockifier/src/test_utils.rs#L136)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

less boilerplate :)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils.rs` line 370 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2503#-OD_YRXO55HeVKpcCFmk:-ODaBVpK8jNQnAoCcGS-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b28f4a5cf7b0d245fcbe3bb75f2c0ad31f9f8fc/crates/blockifier/src/test_utils.rs#L370)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this macro should behave the same for all cairo1 contracts regardless of running framework, right?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2503#-OD_ZZR49JKQL5mvjnnR:-ODa4U3rEv8dVHgX_OYF:byz8pa9) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b28f4a5cf7b0d245fcbe3bb75f2c0ad31f9f8fc/crates/blockifier/src/test_utils/contracts.rs#L131)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this will change in the next PR to return the inner runnable cairo1 version?
or will this contract stay "only native"?
</blockquote></details>

I am changing it in the next PR 
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 310 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2503#-OD_Zm7o6HuDEz1z33MD:-ODa4kjlBif8CtqgrqsW:bm4thu2) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b28f4a5cf7b0d245fcbe3bb75f2c0ad31f9f8fc/crates/blockifier/src/test_utils/contracts.rs#L310)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what if the ERC20 is native? this can be constructed, compiler won't protect us
</blockquote></details>

Will fix it, but for now ERC20 cannot be native will be fixed in the near future,

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 33 of 33 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2503#-:-ODaIQM8CWsg5CLtfQIA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2503)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2503)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2503)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
