### PR TITLE
fix(network): discovery performs kad queries even if not connected to bootstrap

### PR DESCRIPTION
**Pull request by ShahakShama**

### CODE REVIEW

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2142)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @ShahakShama)

___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 237 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2142#-OCDF43j5tkvbf5MF5gb:-OCDF43j5tkvbf5MF5gc:bauqf70) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f361a8f50ad1d3e34f3cb649c424e9ac83d5894/crates/papyrus_network/src/discovery/discovery_test.rs#L237)):*
> ```XML
> }
> 
> #[tokio::test]
> ```

add test to check positive flow of added code. ie check that kad queries without bootstrap connected

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2142)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`crates/papyrus_network/src/discovery/discovery_test.rs` line 237 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2142#-OCDF43j5tkvbf5MF5gb:-OCDK8E5AZg6DD2L1MGx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f361a8f50ad1d3e34f3cb649c424e9ac83d5894/crates/papyrus_network/src/discovery/discovery_test.rs#L237)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

add test to check positive flow of added code. ie check that kad queries without bootstrap connected
</blockquote></details>

Done.

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2142#-:-OCDNJz35EJgOBZiHDhw:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @AlonLStarkWare)

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2142#-:-OCDTVxvDePn9LJjos4G:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Pull request merged**
