### PR TITLE
feat(blockifier): count the number of charged storage keys

### PR DESCRIPTION
**Pull request by yoavGrs**

### CODE REVIEW

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1927)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/execution/alias_keys.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBQdTQl494HkMn-yVA_:-OBQrIEuBvuOir_6v0T6:b-5ljuc) ([raw file](https://github.com/starkware-libs/sequencer/blob/9c95aa7681c6e577cc2f049e90f9efd40512527d/crates/blockifier/src/execution/alias_keys.rs#L21)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Which state is that?
</blockquote></details>

In each call to `execute` the state is updated.
So, this is the state the transaction applies to.

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1927)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/blockifier/src/execution/alias_keys.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBQdTQl494HkMn-yVA_:-OBZVauv0q7V3WhpOJ4O:b-nptshk) ([raw file](https://github.com/starkware-libs/sequencer/blob/9c95aa7681c6e577cc2f049e90f9efd40512527d/crates/blockifier/src/execution/alias_keys.rs#L21)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

In each call to `execute` the state is updated.
So, this is the state the transaction applies to.
</blockquote></details>

I don't understand, is that the state before the tx's changes or after? 
When does the state get updated? If a storage cell is updated during execution then when we read it again it will be the same value... (we won't be able to tell if it was zero or not)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1927)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/execution/alias_keys.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBQdTQl494HkMn-yVA_:-OBfHgCBErYUEDv3TlCb:bq75vv1) ([raw file](https://github.com/starkware-libs/sequencer/blob/9c95aa7681c6e577cc2f049e90f9efd40512527d/crates/blockifier/src/execution/alias_keys.rs#L21)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I don't understand, is that the state before the tx's changes or after? 
When does the state get updated? If a storage cell is updated during execution then when we read it again it will be the same value... (we won't be able to tell if it was zero or not)
</blockquote></details>

Good point. Now it's the state before the execution.

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
What does the field `StateMaps.compiled_class_hashes` mean? Maybe it should also be taken into account?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-:-OBtH2m-7qhGUpHTxurU:b-dmtnch)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/execution/alias_keys.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBQdTQl494HkMn-yVA_:-OBtFUCN5sTzMZR10reD:b-1jkb4j) ([raw file](https://github.com/starkware-libs/sequencer/blob/9c95aa7681c6e577cc2f049e90f9efd40512527d/crates/blockifier/src/execution/alias_keys.rs#L21)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Good point. Now it's the state before the execution.
</blockquote></details>

I don't think this is the right way because the `base_state` is getting updated by other tx's running in parallel.
I looked into `StateCache`. It has two fields `initial_reads`, `writes`.
I think the way to read the previous value should be with respect to `initial_reads`.
I suggest that the function will take `initial_reads: StateMaps` instead of base state, we also need to make sure that the keys of `initial_reads` will match the keys of `state_changes`.
PTAL at `fn update_initial_values_of_write_only_access`.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1927)* status: all files reviewed, 18 unresolved discussions (waiting on @nimrod-starkware and @yoavGrs)

___
*[`crates/blockifier/src/execution/alias_keys.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBQdTQl494HkMn-yVA_:-OBtGPld5Ui7AmPa-oyI:b-v0f8ib) ([raw file](https://github.com/starkware-libs/sequencer/blob/9c95aa7681c6e577cc2f049e90f9efd40512527d/crates/blockifier/src/execution/alias_keys.rs#L21)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I don't think this is the right way because the `base_state` is getting updated by other tx's running in parallel.
I looked into `StateCache`. It has two fields `initial_reads`, `writes`.
I think the way to read the previous value should be with respect to `initial_reads`.
I suggest that the function will take `initial_reads: StateMaps` instead of base state, we also need to make sure that the keys of `initial_reads` will match the keys of `state_changes`.
PTAL at `fn update_initial_values_of_write_only_access`.
</blockquote></details>

1. what if the storage cell is created during the validate phase? the user should still be charged for it, but it will appear nonzero in this current state.
is this function also called after the validate phase, with the "base state" being the state before this tx?
both validate and execute phase changes must be accounted for.

2. what about the fee transfer phase? we need to count the first time the account's balance cell is modified; how will this be done?

3. @nimrod-starkware it's ok if other txs change the same cells queried here, because the tx touches them anyway - any invalidation that can happen, would have happened anyway. contract 0x2 is not accessed here, so not extra invalidation can happen (right?)
___
*[`crates/blockifier/src/execution/alias_keys.rs` line 12 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtFQow2cRpcqbFP9x-:-OBtFQow2cRpcqbFP9x0:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/execution/alias_keys.rs#L12)):*
> ```XML
> 
> /// Keys in contract addresses up to this address don't get aliases.
> pub const N_SAVED_CONTRACT_ADDRESSES: u8 = 16;
> ```





_Suggestion:_
```XML
N_RESERVED_CONTRACT_ADDRESSES
```
___
*[`crates/blockifier/src/execution/alias_keys.rs` line 14 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtFWl71eIpzh7k6Tce:-OBtFWl71eIpzh7k6Tcf:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/execution/alias_keys.rs#L14)):*
> ```XML
> pub const N_SAVED_CONTRACT_ADDRESSES: u8 = 16;
> /// The alias of a felt X up to this number is X.
> /// This trivial mappings don't write to the alias contract.
> ```





_Suggestion:_
```XML
isn't written
```
___
*[`crates/blockifier/src/execution/alias_keys.rs` line 15 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtIs5t3VhbPontRBHh:-OBtIs5u6U7s9TbYQumw:b-ex86va) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/execution/alias_keys.rs#L15)):*
> ```XML
> /// The alias of a felt X up to this number is X.
> /// This trivial mappings don't write to the alias contract.
> pub const N_TRIVIAL_SELF_ALIASES: u8 = 128;
> ```

general question @nimrod-starkware @Yoni-Starkware @yoavGrs , related to comment below:
we charge by number of cells changed from zero to nonzero.
we use this count to fund aliases *but we are not counting new aliases* for fee charge.
should we charge for zero->nonzero modification, on "small" addresses/keys?



_Code quote:_
```XML
/// Keys in contract addresses up to this address don't get aliases.
pub const N_SAVED_CONTRACT_ADDRESSES: u8 = 16;
/// The alias of a felt X up to this number is X.
/// This trivial mappings don't write to the alias contract.
pub const N_TRIVIAL_SELF_ALIASES: u8 = 128;
```
___
*[`crates/blockifier/src/execution/alias_keys.rs` line 20 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtG2Vs1UMSfts3qRu8:-OBtG2Vs1UMSfts3qRu9:bo4ognm) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/execution/alias_keys.rs#L20)):*
> ```XML
> /// Counts declared classes, deployed contracts, and storage keys that were previously empty and
> /// are now filled.
> pub fn n_charged_invoke_aliases<S: StateReader>(
> ```

this function has no relation to the concept of aliases; contract 0x2 is not accessed. please rephrase + rename the function



_Suggestion:_
```XML
/// Returns the number of storage cells changed from zero to non-zero, for fee charge.
/// Counts declared classes, deployed contracts, and storage keys that were previously empty and
/// are now filled.
pub fn n_newly_allocated_cells<S: StateReader>(
```
___
*[`crates/blockifier/src/execution/alias_keys.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtGqpBAHKUpsnwBz_b:-OBtGqpC8uJuJJ4BdiGJ:bb3fupb) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/execution/alias_keys.rs#L29)):*
> ```XML
>         .iter()
>         .filter(|(class_hash, is_declared)| {
>             **is_declared && (class_hash.0 >= N_TRIVIAL_SELF_ALIASES.into())
> ```

I'm missing something: we charge for zero->nonzero, regardless of the storage cell changed, no?
this function is related to, but not equivalent to, alias allocation



_Code quote:_
```XML
&& (class_hash.0 >= N_TRIVIAL_SELF_ALIASES.into())
```
___
*[`crates/blockifier/src/execution/alias_keys.rs` line 35 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtH5uV4D4aeKOsB5HU:-OBtH5uV4D4aeKOsB5HV:b-rznxdx) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/execution/alias_keys.rs#L35)):*
> ```XML
>     let mut n_deployed_contracts = 0;
>     for contract_address in state_changes.0.class_hashes.keys() {
>         if contract_address.0 >= N_TRIVIAL_SELF_ALIASES.into()
> ```

ditto (zero->nonzero, not aliases)



_Code quote:_
```XML
if contract_address.0 >= N_TRIVIAL_SELF_ALIASES.into()
```
___
*[`crates/blockifier/src/execution/alias_keys.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtHdtj9EgJzTRDLz77:-OBtHdtj9EgJzTRDLz78:b-rznxdx) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/execution/alias_keys.rs#L47)):*
> ```XML
>     for ((contract_address, storage_key), new_value) in storage_changes {
>         if contract_address.0.0 >= N_SAVED_CONTRACT_ADDRESSES.into()
>             && storage_key.0.0 >= N_TRIVIAL_SELF_ALIASES.into()
> ```

ditto (zero->nonzero, not aliases)



_Code quote:_
```XML
        if contract_address.0.0 >= N_SAVED_CONTRACT_ADDRESSES.into()
            && storage_key.0.0 >= N_TRIVIAL_SELF_ALIASES.into()
```
___
*[`crates/blockifier/src/execution/alias_keys.rs` line 50 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtHjVb1nP-XxOdoD4-:-OBtHjVc-BFq1oY7kaS9:bkhcfhs) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/execution/alias_keys.rs#L50)):*
> ```XML
>             // Zero to non-zero.
>             && base_state.get_storage_at(*contract_address, *storage_key)? == Felt::ZERO
>             && new_value != &Felt::ZERO
> ```

this check should be redundant - it shouldn't appear in the state changes if it went from zero to zero.
however, if this base state is from the end of validate and this function is called after execution... not sure the diff is squashed yet



_Code quote:_
```XML
&& new_value != &Felt::ZERO
```
___
*[`crates/blockifier/src/execution/alias_keys.rs` line 54 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtHUaqBVhjJTkta97V:-OBtHUarEn8-eboPqy25:bmhkj34) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/execution/alias_keys.rs#L54)):*
> ```XML
>             n_storage_keys += 1;
>         }
>     }
> ```

you use `iter()...count()` once, and then `let mut... for...` twice. why not `iter()...count()` in all 3 cases?



_Code quote:_
```XML
    let n_declared_classes = state_changes
        .0
        .declared_contracts
        .iter()
        .filter(|(class_hash, is_declared)| {
            **is_declared && (class_hash.0 >= N_TRIVIAL_SELF_ALIASES.into())
        })
        .count();

    let mut n_deployed_contracts = 0;
    for contract_address in state_changes.0.class_hashes.keys() {
        if contract_address.0 >= N_TRIVIAL_SELF_ALIASES.into()
            // The contract is deployed, not replaced class.
            && base_state.get_class_hash_at(*contract_address)? == ClassHash(Felt::ZERO)
        {
            n_deployed_contracts += 1;
        }
    }

    let storage_changes = &state_changes.0.storage;
    let mut n_storage_keys = 0;
    for ((contract_address, storage_key), new_value) in storage_changes {
        if contract_address.0.0 >= N_SAVED_CONTRACT_ADDRESSES.into()
            && storage_key.0.0 >= N_TRIVIAL_SELF_ALIASES.into()
            // Zero to non-zero.
            && base_state.get_storage_at(*contract_address, *storage_key)? == Felt::ZERO
            && new_value != &Felt::ZERO
        {
            n_storage_keys += 1;
        }
    }
```
___
*[`crates/starknet_api/src/core.rs` line 350 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtFIaA5FZpEAtFZHbW:-OBtFIaA5FZpEAtFZHbX:b-q9ocik) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/starknet_api/src/core.rs#L350)):*
> ```XML
> )]
> #[display(fmt = "{}", "_0.to_fixed_hex_string()")]
> pub struct PatriciaKey(pub StarkHash);
> ```

remove the `pub`, use the `key()` getter



_Code quote:_
```XML
pub StarkHash
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 688 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtK_o-8g2tuDcHK6Yu:-OBtK_o-8g2tuDcHK6Yv:b-c6pkid) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/transaction/account_transaction.rs#L688)):*
> ```XML
>                     &execution_state.state,
>                     &execution_state_changes,
>                 )?;
> ```

the `execution_state` is a transactional state over the *end of the validate phase*; you will not see changes incurred in the validate phase here.
I suggest you also call `n_charged_aliases` after validation, before creation of the `execution_state`, so you can add the count...
but even with this addition, if validate changes 0->7 and execute changes 7->0, we should NOT charge for an allocation, but you WILL charge... not sure what can be done here, need to compute this before the fee transfer phase but the states aren't squashed yet.
consider, instead of computing post-validate, calling `StateChanges::merge` (see below) *before* `n_charged_aliases`



_Code quote:_
```XML
                let n_allocated_leaves_for_fee = self.n_charged_aliases(
                    tx_context.clone(),
                    &execution_state.state,
                    &execution_state_changes,
                )?;
```
___
*[`crates/blockifier/src/execution/alias_keys_test.rs` line 0 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtF3cA2z55j5g1hcm7:-OBtF3cBEfghmf6hM4LX:bjdsgi6) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/execution/alias_keys_test.rs#L0)):*
please use `felt!`, `contract_address!`, `class_hash!` and `storage_key!` macros instead of the `from`s, this is a test file
___
*[`crates/blockifier/src/execution/alias_keys_test.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtJRcpErqYrrvcJauS:-OBtJRcpErqYrrvcJauT:b-tb6g17) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/execution/alias_keys_test.rs#L21)):*
> ```XML
>             ContractAddress::from(2000_u32),
>             ClassHash(Felt::from(2001)),
>         )]),
> ```

what about declared classes?



_Code quote:_
```XML
        storage_view: HashMap::from([(
            (ContractAddress::from(1000_u32), StorageKey::from(1001_u32)),
            Felt::from(1002),
        )]),
        address_to_class_hash: HashMap::from([(
            ContractAddress::from(2000_u32),
            ClassHash(Felt::from(2001)),
        )]),
```
___
*[`crates/blockifier/src/execution/alias_keys_test.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtJoKt0SBOLIWf8ESG:-OBtJoKu6xNk-Yz6Piy3:bf4ezxy) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/execution/alias_keys_test.rs#L26)):*
> ```XML
> }
> 
> fn assert_number_of_charged_changes(state_changes: StateChanges, charged_change: bool) {
> ```

to allow for more general test cases later



_Suggestion:_
```XML
expected_charged_allocations: u8
```
___
*[`crates/blockifier/src/execution/alias_keys_test.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtJeU8DsTAnRvMyoU-:-OBtJeU8DsTAnRvMyoU0:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/execution/alias_keys_test.rs#L28)):*
> ```XML
> fn assert_number_of_charged_changes(state_changes: StateChanges, charged_change: bool) {
>     let state = initial_state();
>     let n_charged_aliases = n_charged_invoke_aliases(&state, &state_changes).unwrap();
> ```





_Suggestion:_
```XML
n_charged_allocations
```
___
*[`crates/blockifier/src/execution/alias_keys_test.rs` line 30 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtJVocEcB65wfMB9Y9:-OBtJVodBN1BqLknzG_W:blbb8f8) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/execution/alias_keys_test.rs#L30)):*
> ```XML
>     let n_charged_aliases = n_charged_invoke_aliases(&state, &state_changes).unwrap();
>     assert_eq!(n_charged_aliases, if charged_change { 1 } else { 0 });
> }
> ```

consider making this a macro, so you see the relevant line number on failure (non-blocking)



_Code quote:_
```XML
fn assert_number_of_charged_changes(state_changes: StateChanges, charged_change: bool) {
    let state = initial_state();
    let n_charged_aliases = n_charged_invoke_aliases(&state, &state_changes).unwrap();
    assert_eq!(n_charged_aliases, if charged_change { 1 } else { 0 });
}
```
___
*[`crates/blockifier/src/execution/alias_keys_test.rs` line 52 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtK1vREE5iDa9Lvop4:-OBtK1vS0jEN2Yr7ykOj:b-bpnk4j) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/execution/alias_keys_test.rs#L52)):*
> ```XML
> #[case::empty(HashMap::new(), false)]
> #[case::add_class_hash(HashMap::from([(ClassHash(3000.into()), true)]), true)]
> #[case::remove_class_hash(HashMap::from([(ClassHash(3000.into()), false)]), false)]
> ```

what does it mean when `declared_contracts` value is `false`?



_Code quote:_
```XML
ClassHash(3000.into()), false
```
___
*[`crates/blockifier/src/execution/alias_keys_test.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtKKOX4qRjFqXn91aU:-OBtKKOYCUBdREhKsDdP:bvqhqyx) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/execution/alias_keys_test.rs#L67)):*
> ```XML
> #[case::empty(HashMap::new(), false)]
> #[case::new_contract(HashMap::from([(ContractAddress::from(3000_u32), ClassHash(3001.into()))]), true)]
> #[case::replace_class(HashMap::from([(ContractAddress::from(2000_u32), ClassHash(2002.into()))]), false)]
> ```

this isn't charged because 2000 is already in the initial state, right?
please give names to these magic numbers and use them, so it's clear what a test case is testing



_Code quote:_
```XML
(ContractAddress::from(2000_u32), ClassHash(2002.into()))]), false
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1927)* status: all files reviewed, 18 unresolved discussions (waiting on @nimrod-starkware and @yoavGrs)

___
*[`crates/blockifier/src/execution/alias_keys.rs` line 15 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtIs5t3VhbPontRBHh:-OBtZVzd0CzzkQX6Y1Ga:b75pzor) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/execution/alias_keys.rs#L15)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

general question @nimrod-starkware @Yoni-Starkware @yoavGrs , related to comment below:
we charge by number of cells changed from zero to nonzero.
we use this count to fund aliases *but we are not counting new aliases* for fee charge.
should we charge for zero->nonzero modification, on "small" addresses/keys?
</blockquote></details>

Yes, for consistency

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1927)* status: all files reviewed, 18 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @yoavGrs)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 688 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtK_o-8g2tuDcHK6Yu:-OBt_HkY5RJ4gijUD_Gc:bcps90e) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/transaction/account_transaction.rs#L688)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the `execution_state` is a transactional state over the *end of the validate phase*; you will not see changes incurred in the validate phase here.
I suggest you also call `n_charged_aliases` after validation, before creation of the `execution_state`, so you can add the count...
but even with this addition, if validate changes 0->7 and execute changes 7->0, we should NOT charge for an allocation, but you WILL charge... not sure what can be done here, need to compute this before the fee transfer phase but the states aren't squashed yet.
consider, instead of computing post-validate, calling `StateChanges::merge` (see below) *before* `n_charged_aliases`
</blockquote></details>

@dorimedini-starkware isn't it a private case of fee charging?
what are we doing for not charging for trivial changes in general?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1927)* status: all files reviewed, 18 unresolved discussions (waiting on @nimrod-starkware, @yoavGrs, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 688 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtK_o-8g2tuDcHK6Yu:-OBt_q_T9IuN5L0ZSyGZ:b673i9z) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/transaction/account_transaction.rs#L688)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@dorimedini-starkware isn't it a private case of fee charging?
what are we doing for not charging for trivial changes in general?
</blockquote></details>

we do `StateChanges::merge` in `TransactionReceipt::from_account_tx`; is that what you mean?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1927)* status: all files reviewed, 18 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @yoavGrs)

___
*[`crates/blockifier/src/execution/alias_keys.rs` line 20 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtG2Vs1UMSfts3qRu8:-OBtaBDxCT4sHKe3KNhV:b-kwn0pa) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/execution/alias_keys.rs#L20)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this function has no relation to the concept of aliases; contract 0x2 is not accessed. please rephrase + rename the function
</blockquote></details>

And the file name

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1927)* status: all files reviewed, 18 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @yoavGrs)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 688 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtK_o-8g2tuDcHK6Yu:-OBtapiV4ZjGyUXX2VcW:b-rdeovy) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/transaction/account_transaction.rs#L688)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we do `StateChanges::merge` in `TransactionReceipt::from_account_tx`; is that what you mean?
</blockquote></details>

So we're not doing this (remove trivial updates across validate<>execute) also in the general case.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1927)* status: all files reviewed, 18 unresolved discussions (waiting on @nimrod-starkware, @yoavGrs, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 688 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtK_o-8g2tuDcHK6Yu:-OBtdwjl7NNBZqYKJ3AY:b17mahu) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/transaction/account_transaction.rs#L688)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

So we're not doing this (remove trivial updates across validate<>execute) also in the general case.
</blockquote></details>

right; state changes do not include initial reads in the data, so we can't, with the current design

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1927)* status: all files reviewed, 18 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @yoavGrs)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 688 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtK_o-8g2tuDcHK6Yu:-OBtwVpD4FoVvfwN8tzI:bb0grvp) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/transaction/account_transaction.rs#L688)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

right; state changes do not include initial reads in the data, so we can't, with the current design
</blockquote></details>

Can we access &execution_state.state.**cache**?

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1927)* status: all files reviewed, 18 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/execution/alias_keys.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBQdTQl494HkMn-yVA_:-OBu4WWA0934Pjb0S0E0:bv7pcfe) ([raw file](https://github.com/starkware-libs/sequencer/blob/9c95aa7681c6e577cc2f049e90f9efd40512527d/crates/blockifier/src/execution/alias_keys.rs#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. what if the storage cell is created during the validate phase? the user should still be charged for it, but it will appear nonzero in this current state.
is this function also called after the validate phase, with the "base state" being the state before this tx?
both validate and execute phase changes must be accounted for.

2. what about the fee transfer phase? we need to count the first time the account's balance cell is modified; how will this be done?

3. @nimrod-starkware it's ok if other txs change the same cells queried here, because the tx touches them anyway - any invalidation that can happen, would have happened anyway. contract 0x2 is not accessed here, so not extra invalidation can happen (right?)
</blockquote></details>

3. you are right, but the state can be incorrect.
If my tx does this: `if x == 1: x ++`.
In the short period of time if another tx changed x to zero, when we read it we will charge for that, although it has been non-zero. The charging should be with respect to what this tx has read, that's my point
___
*[`crates/blockifier/src/execution/alias_keys.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBtGqpBAHKUpsnwBz_b:-OBtwFre3gzxTE35pJEj:b1jbpr8) ([raw file](https://github.com/starkware-libs/sequencer/blob/452a948557b6264bfc4c78707fb606b73bb19d8a/crates/blockifier/src/execution/alias_keys.rs#L29)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I'm missing something: we charge for zero->nonzero, regardless of the storage cell changed, no?
this function is related to, but not equivalent to, alias allocation
</blockquote></details>

@yoavGrs I think the constants `N_TRIVIAL_SELF_ALIASES` & `N_SAVED_CONTRACT_ADDRESSES` shouldn't be taken into account when calculating fees, only when allocating aliases

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1927)* status: all files reviewed, 18 unresolved discussions (waiting on @nimrod-starkware and @yoavGrs)

___
*[`crates/blockifier/src/execution/alias_keys.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1927#-OBQdTQl494HkMn-yVA_:-OBufnZD8Xq5iVeHPnl3:be5u9k0) ([raw file](https://github.com/starkware-libs/sequencer/blob/9c95aa7681c6e577cc2f049e90f9efd40512527d/crates/blockifier/src/execution/alias_keys.rs#L21)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

3. you are right, but the state can be incorrect.
If my tx does this: `if x == 1: x ++`.
In the short period of time if another tx changed x to zero, when we read it we will charge for that, although it has been non-zero. The charging should be with respect to what this tx has read, that's my point
</blockquote></details>

concurrency doesn't mean different txs operate on the same state.
the way it works is: we "guess" sets of txs that don't conflict,
and run each set in sequence (different sets in parallel),
starting from the same state, but different copies.
later, when combining the sets, we check for invalidation (i.e. same tx read/wrote the same cell)

**Pull request closed without merging**
