### PR TITLE
Merge main-v0.13.2 into main

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/361)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
[Src](https://github.com/starkware-libs/blockifier/compare/439a24ceffab883c5b4b9cded576ed975b1d3a01..main-v0.13.2#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87e) [Dst](https://github.com/starkware-libs/blockifier/compare/439a24ceffab883c5b4b9cded576ed975b1d3a01..main#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87e) Cargo.lock

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 16 files at r1, 1 of 4 files at r2, 60 of 62 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/361)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by amosStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/361)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/361)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
