### PR TITLE
feat(blockifier): support Cairo1 local recompilation

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/184)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/184?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#184** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/184?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#183** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/183?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#182** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/182?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#181** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/181?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#180** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/180?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#179** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/179?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 102 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O39Jl001EM6ryYmWFv3:-O39Jl001EM6ryYmWFv4:b2s2ria) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ae0de0333e1e37bc7e1a0f0453504d849b3187c/crates/blockifier/src/test_utils/cairo_compile.rs#L102)):*
> ```XML
>     path: String,
>     git_tag_override: Option<String>,
>     additional_cargo_arg: Option<String>,
> ```

What is this?



_Code quote:_
```XML
additional_cargo_arg: Option<String>,
```

**Review by aner-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/184)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O39NRJa1s4JMIaDwJjv:-O39NRJa1s4JMIaDwJjw:b-ruwg4l) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ae0de0333e1e37bc7e1a0f0453504d849b3187c/crates/blockifier/src/test_utils/cairo_compile.rs#L115)):*
> ```XML
>     base_compile_args
>         .push(format!("--manifest-path={}/Cargo.toml", cairo1_compiler_path.to_string_lossy()));
>     base_compile_args.push("--bin".into());
> ```

Isn't it better to use the macro as intended? If the order is important, you can use `insert(0, cargo_arg)`



_Suggestion:_
```XML
   let mut base_compile_args = vec![
        "run".into(),
        format!("--manifest-path={}/Cargo.toml", cairo1_compiler_path.to_string_lossy()),
        "--bin".into(),
    ];
    if let Some(cargo_arg) = additional_cargo_arg {
        base_compile_args.push(cargo_arg);
    }
```
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 129 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O39KmSqAvvwsQGuoKdj:-O39KmSrD6sJTklU7ZOB:b-7lq735) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ae0de0333e1e37bc7e1a0f0453504d849b3187c/crates/blockifier/src/test_utils/cairo_compile.rs#L129)):*
> ```XML
>     // Sierra -> CASM.
>     let mut sierra_compile_command = Command::new("cargo");
>     sierra_compile_command.args(base_compile_args.clone());
> ```

Why are you cloning here?



_Code quote:_
```XML
.clone()
```
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 133 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O39Q-_e0G6lp1wUol2s:-O39Q-_e0G6lp1wUol2t:bopiud9) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ae0de0333e1e37bc7e1a0f0453504d849b3187c/crates/blockifier/src/test_utils/cairo_compile.rs#L133)):*
> ```XML
>     let casm_output = run_and_verify_output(&mut sierra_compile_command);
> 
>     casm_output.stdout
> ```

What happens if there's an error?



_Code quote:_
```XML
 casm_output.stdout
```

**Comment by aner-starkware** [comment]
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 134 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O3BjIp3DmXNa60x94O_:-O3BjIp3DmXNa60x94Oa:b-gm0vq9) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ae0de0333e1e37bc7e1a0f0453504d849b3187c/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L134)):*
> ```XML
> ) {
>     // TODO(Dori, 1/9/2024): Support Cairo1 contracts in the CI and remove this `if` statement.
>     if std::env::var("CI").is_ok() && matches!(cairo_version, CairoVersion::Cairo1) {
> ```

Since this part will be removed, I'm not sure how important it is, but:
1. I'm not sure this is the correct variable to check, it should probably be `GITHUB_ACTIONS` (the `CI` var can be changed)
2. It's probably a good idea to also check that it has the expected `true` value, not only that the variable exists.



_Code quote:_
```XML
std::env::var("CI").is_ok()
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/184)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @aner-starkware, @AvivYossef-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 102 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O39Jl001EM6ryYmWFv3:-O3C7ePIEkTBvH3a1lx0:b-u1zwgg) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ae0de0333e1e37bc7e1a0f0453504d849b3187c/crates/blockifier/src/test_utils/cairo_compile.rs#L102)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

What is this?
</blockquote></details>

goes with `git_tag_override`, for the legacy contract.
legacy contract requires an old compiler tag (hence `git_tag_override`),
and that tag of the compiler doesn't build (`cargo run` fails) with stable rust so we need to pass a nightly version to cargo (hence `additional_cargo_arg`).
Maybe better to pass an `is_legacy_contract` flag? I thought to make this `cairo1_compile` function generic (unaware of actual existing contracts)
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O39NRJa1s4JMIaDwJjv:-O3C8hNG1hXvebNpB9w-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ae0de0333e1e37bc7e1a0f0453504d849b3187c/crates/blockifier/src/test_utils/cairo_compile.rs#L115)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Isn't it better to use the macro as intended? If the order is important, you can use `insert(0, cargo_arg)`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 129 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O39KmSqAvvwsQGuoKdj:-O3C8vQkDHKFpdqSnmxn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ae0de0333e1e37bc7e1a0f0453504d849b3187c/crates/blockifier/src/test_utils/cairo_compile.rs#L129)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Why are you cloning here?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 133 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O39Q-_e0G6lp1wUol2s:-O3C8zuu6NHDv3Cfsa-T:b-epjluo) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ae0de0333e1e37bc7e1a0f0453504d849b3187c/crates/blockifier/src/test_utils/cairo_compile.rs#L133)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

What happens if there's an error?
</blockquote></details>

see impl of `run_and_verify_output` in [the previous PR](https://reviewable.io/reviews/starkware-libs/sequencer/183) (answer: panic, with the stderr output as the message)
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 134 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O3BjIp3DmXNa60x94O_:-O3CBorYCwFqv7DRCdzt:b-fkovdr) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ae0de0333e1e37bc7e1a0f0453504d849b3187c/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L134)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Since this part will be removed, I'm not sure how important it is, but:
1. I'm not sure this is the correct variable to check, it should probably be `GITHUB_ACTIONS` (the `CI` var can be changed)
2. It's probably a good idea to also check that it has the expected `true` value, not only that the variable exists.
</blockquote></details>

it won't be removed; just editted. see [here](https://reviewable.io/reviews/starkware-libs/sequencer/197) (final PR in stack).
1. [this](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/variables#default-environment-variables) indicates the `CI` env var can be sometimes changed; but what should I check with `GITHUB_ACTIONS`? that it's set?
2. better?

**Comment by aner-starkware** [comment]
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 134 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O3BjIp3DmXNa60x94O_:-O3D2QXzA37kSsCxEnPw:b-26z5ab) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ae0de0333e1e37bc7e1a0f0453504d849b3187c/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L134)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

it won't be removed; just editted. see [here](https://reviewable.io/reviews/starkware-libs/sequencer/197) (final PR in stack).
1. [this](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/variables#default-environment-variables) indicates the `CI` env var can be sometimes changed; but what should I check with `GITHUB_ACTIONS`? that it's set?
2. better?
</blockquote></details>

`GITHUB_ACTIONS` is a always set to `true` when running in the CI, so you can check that. 
I'm woriied the current method might not make sense in some future scenrio - If for some reason `CI` is set to `false` in a local run (who knows, there might need to be a reason to do so in the future), then the local run would run as if it's in the CI. This would create a very hard-to-spot bug.

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 102 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O39Jl001EM6ryYmWFv3:-O3D4bP7EcFpOZT3NT01:bqs356a) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ae0de0333e1e37bc7e1a0f0453504d849b3187c/crates/blockifier/src/test_utils/cairo_compile.rs#L102)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

goes with `git_tag_override`, for the legacy contract.
legacy contract requires an old compiler tag (hence `git_tag_override`),
and that tag of the compiler doesn't build (`cargo run` fails) with stable rust so we need to pass a nightly version to cargo (hence `additional_cargo_arg`).
Maybe better to pass an `is_legacy_contract` flag? I thought to make this `cairo1_compile` function generic (unaware of actual existing contracts)
</blockquote></details>

Not sure I understand. If it's "+nightly", maybe rename to `nightly_arg` or smthng?

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 133 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O39Q-_e0G6lp1wUol2s:-O3D56iU1SfV2i9LcJXf:balv7b3) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ae0de0333e1e37bc7e1a0f0453504d849b3187c/crates/blockifier/src/test_utils/cairo_compile.rs#L133)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see impl of `run_and_verify_output` in [the previous PR](https://reviewable.io/reviews/starkware-libs/sequencer/183) (answer: panic, with the stderr output as the message)
</blockquote></details>

Is panic what we want?

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/184)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 282 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O3RBytdCcCInDMuLRvU:-O3RBytdCcCInDMuLRvV:bpqdsmw) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ae0de0333e1e37bc7e1a0f0453504d849b3187c/crates/blockifier/src/test_utils/contracts.rs#L282)):*
> ```XML
>             }
>             CairoVersion::Cairo1 => {
>                 let (tag_override, cargo_arg) = match self {
> ```

How about



_Suggestion:_
```XML
cargo_nightly_arg
```

**Review by aner-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/184)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @dorimedini-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 134 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O3BjIp3DmXNa60x94O_:-O3X7OZWEEo3o9uGkzpI:b-gebzyc) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ae0de0333e1e37bc7e1a0f0453504d849b3187c/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L134)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you set it to `false` locally now, this shouldn't run; I check that the value is `true`
</blockquote></details>

OK, I'll resolve it, though I think `GITHUB_ACTIONS` is the safer option here.

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/184)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 174 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O40Fb9p3XV_59Qei27Z:-O40Fb9p3XV_59Qei27_:b-pvpu31) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa4a115c2e098f096cfd96ad8a4c99e542bc1552/crates/blockifier/src/test_utils/cairo_compile.rs#L174)):*
> ```XML
> }
> 
> fn verify_cairo1_compiler_deps(git_tag_override: Option<String>) {
> ```

`verify` sounds like a no-side-effect action.



_Suggestion:_
```XML
prepare_cairo1_compiler_deps
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 279 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O40HrI6635YAIAoohBF:-O40HrI6635YAIAoohBG:bb580ep) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa4a115c2e098f096cfd96ad8a4c99e542bc1552/crates/blockifier/src/test_utils/contracts.rs#L279)):*
> ```XML
>                     Self::LegacyTestContract => (
>                         // Legacy contract requires specific compiler tag (which is the point of
>                         // the test contract), + to build the compiler an
> ```

I don't understand the sentence (== this is why the test contract exists?)



_Suggestion:_
```XML
which is the point of the test contract
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 282 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O40HaAKDIvwtU7dCMZ7:-O40HaAKDIvwtU7dCMZ8:b5l1vzx) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa4a115c2e098f096cfd96ad8a4c99e542bc1552/crates/blockifier/src/test_utils/contracts.rs#L282)):*
> ```XML
>                         // older rust version is required.
>                         Some(LEGACY_CONTRACT_COMPILER_TAG.into()),
>                         Some(String::from("2023-07-05")),
> ```

Why 1 is const and the other isn't?



_Code quote:_
```XML
                        Some(LEGACY_CONTRACT_COMPILER_TAG.into()),
                        Some(String::from("2023-07-05")),
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/184)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @meship-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 279 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O40HrI6635YAIAoohBF:-O40UOmjE6cNysiJ0cyF:bvyb82y) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa4a115c2e098f096cfd96ad8a4c99e542bc1552/crates/blockifier/src/test_utils/contracts.rs#L279)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I don't understand the sentence (== this is why the test contract exists?)
</blockquote></details>

better?

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/184#-:-O40cMP24JEulIRm_krd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 279 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/184#-O40HrI6635YAIAoohBF:-O40cK0nBUNCYwPVGDCB:bb70i42) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa4a115c2e098f096cfd96ad8a4c99e542bc1552/crates/blockifier/src/test_utils/contracts.rs#L279)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

better?
</blockquote></details>

Much

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Aug 11, 11:28 AM EDT**: @dorimedini-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/184).

**Pull request merged**
