### PR TITLE
refactor(papyrus_p2p_sync): run_test supports all data types

### PR DESCRIPTION
**Pull request by ShahakShama**
- **refactor(papyrus_p2p_sync): add_test receives query size instead of constant**
- **refactor(papyrus_p2p_sync): run_test supports all data types**

### CODE REVIEW

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2415)* status: all files reviewed, 1 unresolved discussion (waiting on @noamsp-starkware and @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/client/test_utils.rs` line 376 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2415#-ODahKSZAfyFZ-cXTmu0:-ODahKSZAfyFZ-cXTmu1:b-vyc3x5) ([raw file](https://github.com/starkware-libs/sequencer/blob/63cba885aedc06fe439e01615bc4c5eb2860ee37/crates/papyrus_p2p_sync/src/client/test_utils.rs#L376)):*
> ```XML
>     mock_network: &mut GenericReceiver<MockClientResponsesManager<Query, Response>>,
>     current_query_responses_manager: &mut Option<MockClientResponsesManager<Query, Response>>,
> ) -> Query
> ```

I think this function does too much - it should just get the query, response. the main test should handle in/out of the MockClientResponseManager for clear encapsulation



_Suggestion:_
```XML
(Query, MockClientResponseManager)
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2415)* status: all files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware and @noamsp-starkware)

___
*[`crates/papyrus_p2p_sync/src/client/test_utils.rs` line 376 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2415#-ODahKSZAfyFZ-cXTmu0:-ODaoEjs2t91T6UDZ4IG:b19dsc2) ([raw file](https://github.com/starkware-libs/sequencer/blob/63cba885aedc06fe439e01615bc4c5eb2860ee37/crates/papyrus_p2p_sync/src/client/test_utils.rs#L376)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

I think this function does too much - it should just get the query, response. the main test should handle in/out of the MockClientResponseManager for clear encapsulation
</blockquote></details>

IIUC, what you're suggesting will imply to delete this function. This will cause code duplication
This is a helper function so I don't think it's problematic that it does too much. If you want we can huddle on it

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2415)* status: all files reviewed, 1 unresolved discussion (waiting on @noamsp-starkware and @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/client/test_utils.rs` line 376 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2415#-ODahKSZAfyFZ-cXTmu0:-ODarStHBCfQTL5D7Lv3:b-sys7la) ([raw file](https://github.com/starkware-libs/sequencer/blob/63cba885aedc06fe439e01615bc4c5eb2860ee37/crates/papyrus_p2p_sync/src/client/test_utils.rs#L376)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

IIUC, what you're suggesting will imply to delete this function. This will cause code duplication
This is a helper function so I don't think it's problematic that it does too much. If you want we can huddle on it
</blockquote></details>

I was suggesting that it doesn't take the current _query_responses_manager as an input, and leaves the logic for the main func. Alternatively can rename the helper func so that it include '_and_set_response_manager. Wdyt?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2415)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware and @noamsp-starkware)

___
*[`crates/papyrus_p2p_sync/src/client/test_utils.rs` line 376 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2415#-ODahKSZAfyFZ-cXTmu0:-ODjiSZTEHKjY1FzWomg:b5t3gb6) ([raw file](https://github.com/starkware-libs/sequencer/blob/63cba885aedc06fe439e01615bc4c5eb2860ee37/crates/papyrus_p2p_sync/src/client/test_utils.rs#L376)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

I was suggesting that it doesn't take the current _query_responses_manager as an input, and leaves the logic for the main func. Alternatively can rename the helper func so that it include '_and_set_response_manager. Wdyt?
</blockquote></details>

Renamed :)

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2415#-:-ODjoRDW80i8J4qfSYng:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)

**Pull request merged**
