### PR TITLE
refactor(node): convert storage metrics handle to the desired task type

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/860)

### CODE REVIEW

**Comment by matan-starkware** [comment]
* **#861** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/861?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#860** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/860?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/860)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/860)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Comment by matan-starkware** [comment]
### Merge activity

* **Sep 18, 9:38 AM EDT**: @matan-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/860).

**Pull request merged**
