### PR TITLE
chore(batcher): impl default to ExecutionConfig for addition to Batch…

### PR DESCRIPTION
**Pull request by ayeletstarkware**
…erConfig

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
Can you please give more context? :)
Are we planning to use the default values in the regular flow?
Can we add a config to allow an easy modification to the values? (eliminates the need to re-publish)

> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-:-O8r-pFN585zhXegKbd_:biw8z4o)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware and @noaov1)

___
*[`crates/blockifier/src/bouncer.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O93M7oiBqB6PHUXszeU:-O93M7ojEtxexWwvH2DT:bunivwp) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/blockifier/src/bouncer.rs#L136)):*
> ```XML
>         Self {
>             gas: 4950000,
>             n_steps: 20000000,
> ```

I see 40000000 in some starknet config files.
lets verify all numbers with @noaov1



_Code quote:_
```XML
20000000
```
___
*[`crates/blockifier/src/bouncer.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O93Kl1DAp-6QdSVvp1N:-O93Kl1DAp-6QdSVvp1O:btbdhs) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/blockifier/src/bouncer.rs#L137)):*
> ```XML
>             gas: 4950000,
>             n_steps: 20000000,
>             message_segment_length: 3700,
> ```

I see the @Yoni-Starkware recently changed it from 3750 to 3700, did you check with him?



_Code quote:_
```XML
3700
```
___
*[`crates/blockifier/src/bouncer.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O93MKnW4CvJRuzJyWnZ:-O93MKnW4CvJRuzJyWn_:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/blockifier/src/bouncer.rs#L139)):*
> ```XML
>             message_segment_length: 3700,
>             n_events: 5000,
>             state_diff_size: 20000,
> ```





_Suggestion:_
```XML
//TODO: override this value when using kzg_da
state_diff_size: 20000,
```
___
*[`crates/blockifier/src/bouncer.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O93K3hh--B2WMnTsUnM:-O93K3hh--B2WMnTsUnN:b33esat) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/blockifier/src/bouncer.rs#L140)):*
> ```XML
>             n_events: 5000,
>             state_diff_size: 20000,
>             builtin_count: BuiltinCount::default(),
> ```

please implement this default as well.



_Code quote:_
```XML
builtin_count: BuiltinCount::default()
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 868 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O93Jhu69diwXWf5NE5g:-O93Jhu69diwXWf5NE5h:b-vrtns2) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/blockifier/src/versioned_constants.rs#L868)):*
> ```XML
>             validate_max_n_steps: 1000000,
>             max_recursion_depth: 50,
>             invoke_tx_max_n_steps: 4000000,
> ```

I think it should be 10000000 according to starknet version 0_13_3
did you ask @noaov1 ?



_Suggestion:_
```XML
10000000
```
___
*[`crates/blockifier/src/blockifier/config.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O93JEdQ7EuKyq2z6Bvx:-O93JEdQ7EuKyq2z6Bvy:b-ovtyrb) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/blockifier/src/blockifier/config.rs#L32)):*
> ```XML
> impl Default for ConcurrencyConfig {
>     fn default() -> Self {
>         Self { enabled: true, n_workers: 28, chunk_size: 100 }
> ```

this was the number provided by @noaov1 ?



_Code quote:_
```XML
28
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @noaov1, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O93Kl1DAp-6QdSVvp1N:-O93Ui034Us_fvX5kAl5:b-lxg25x) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/blockifier/src/bouncer.rs#L137)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I see the @Yoni-Starkware recently changed it from 3750 to 3700, did you check with him?
</blockquote></details>

3700 if fine (very high)
___
*[`crates/blockifier/src/bouncer.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O93MKnW4CvJRuzJyWnZ:-O93Umk99gMoNAQqNJpr:bqtmzrz) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/blockifier/src/bouncer.rs#L139)):*
> ```XML
>             message_segment_length: 3700,
>             n_events: 5000,
>             state_diff_size: 20000,
> ```

Let it be 4000 in any case. 
___
*[`crates/blockifier/src/versioned_constants.rs` line 868 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O93Jhu69diwXWf5NE5g:-O93V0411d5k8FxlXOtR:b-a266d2) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/blockifier/src/versioned_constants.rs#L868)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think it should be 10000000 according to starknet version 0_13_3
did you ask @noaov1 ?
</blockquote></details>

Why do you need to put concrete values here?
The override is for overriding the VC values, primarily for appchains or for bugfixes.
I.e., it should be passed as Option

**Review by Yael-Starkware — COMMENTED** [review]
yes we plan to use these in the regular flow.
These are the default values and can be overridden by a config file.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-:-O93u_YU4pGnLDye4Ep6:bny80p9)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @noaov1)

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 868 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O93Jhu69diwXWf5NE5g:-O93yiJ64TtRu0KLgBnl:bz6abv6) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/blockifier/src/versioned_constants.rs#L868)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why do you need to put concrete values here?
The override is for overriding the VC values, primarily for appchains or for bugfixes.
I.e., it should be passed as Option
</blockquote></details>

I fully agree, but this is the existing blockifier code.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 868 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O93Jhu69diwXWf5NE5g:-O93zdWP2kcNJLL-0Qs4:b-26rbam) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/blockifier/src/versioned_constants.rs#L868)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I fully agree, but this is the existing blockifier code.
</blockquote></details>

we can do this as a separate PR.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @noaov1)

___
*[`crates/batcher/src/block_builder.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O94CSnmDVFPoXq9TQTE:-O94CSnmDVFPoXq9TQTF:b-9h9iz5) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/batcher/src/block_builder.rs#L65)):*
> ```XML
>             chain_info: ChainInfo::default(),
>             execute_config: TransactionExecutorConfig::default(),
>             bouncer_config: BouncerConfig::empty(),
> ```

why empty?



_Code quote:_
```XML
bouncer_config: BouncerConfig::empty()
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O94CSnmDVFPoXq9TQTE:-O94QD4PE2VaM0_XmuWW:bd9chs0) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/batcher/src/block_builder.rs#L65)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why empty?
</blockquote></details>

A mistake. Done.
___
*[`crates/blockifier/src/bouncer.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O93M7oiBqB6PHUXszeU:-O999dNqD6d83OYJKwSo:blv8vrw) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/blockifier/src/bouncer.rs#L136)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I see 40000000 in some starknet config files.
lets verify all numbers with @noaov1
</blockquote></details>

used 20000000
___
*[`crates/blockifier/src/bouncer.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O93Kl1DAp-6QdSVvp1N:-O94CsDr38Lux2bf8t-b:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/blockifier/src/bouncer.rs#L137)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

3700 if fine (very high)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O93MKnW4CvJRuzJyWnZ:-O94REpI-BJRXPJCoJC5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/blockifier/src/bouncer.rs#L139)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Let it be 4000 in any case.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O93K3hh--B2WMnTsUnM:-O998oOP8qI-JP9BjgU0:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/blockifier/src/bouncer.rs#L140)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

please implement this default as well.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 868 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O93Jhu69diwXWf5NE5g:-O94ROO7-VD9OTgMb4Sk:bvxwxuz) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/blockifier/src/versioned_constants.rs#L868)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

we can do this as a separate PR.
</blockquote></details>

changed to 10000000. I will create a separate PR for passing VersionedConstantsOverrides as an option.
___
*[`crates/blockifier/src/blockifier/config.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O93JEdQ7EuKyq2z6Bvx:-O94D3292_5C2rryfdh5:b-7j964s) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/blockifier/src/blockifier/config.rs#L32)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

this was the number provided by @noaov1 ?
</blockquote></details>

stale

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @noaov1, and @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O99HEss-53_VCPU2DvY:-O99HEst3mhj5V0SIcHG:b6d0ln5) ([raw file](https://github.com/starkware-libs/sequencer/blob/460a98da079cfc87fdd3d03c5f3867fc918f7b8a/crates/batcher/src/block_builder.rs#L49)):*
> ```XML
> 
> #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
> pub struct ExecutionConfig {
> ```

I suggest a more specific name. `Execution` is used too much in our code



_Suggestion:_
```XML
BlockBuilderConfig
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)* status: 0 of 5 files reviewed, 10 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 135 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O99HqSO6gxouRbdBUfk:-O99HqSP65nPVZ3QZ-Zl:bb76mu4) ([raw file](https://github.com/starkware-libs/sequencer/blob/460a98da079cfc87fdd3d03c5f3867fc918f7b8a/crates/blockifier/src/bouncer.rs#L135)):*
> ```XML
>     fn default() -> Self {
>         Self {
>             gas: 2500000,
> ```

Why?



_Code quote:_
```XML
gas: 2500000,
```
___
*[`crates/blockifier/src/bouncer.rs` line 303 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O99HglRB6rf9n7_uhsz:-O99HglS3VNHN2OXubeM:blnfnd) ([raw file](https://github.com/starkware-libs/sequencer/blob/460a98da079cfc87fdd3d03c5f3867fc918f7b8a/crates/blockifier/src/bouncer.rs#L303)):*
> ```XML
>             poseidon: 78125,
>             range_check: 156250,
>             range_check96: 0,
> ```

There should not be zeros here. Where did it come from?



_Code quote:_
```XML
            add_mod: 0,
            bitwise: 39062,
            ecdsa: 1220,
            ec_op: 2441,
            keccak: 0,
            mul_mod: 0,
            pedersen: 78125,
            poseidon: 78125,
            range_check: 156250,
            range_check96: 0,
```

**Comment by ArniStarkware** [comment]
Non-blocking. If you have more comments for address in this PR, please fix the creation of `execution_config` in `batcher.rs`:
https://github.com/starkware-libs/sequencer/blob/033ec459613252d2a087e98d91dd481672dabe0f/crates/batcher/src/batcher.rs#L126

Should turn into: 
```
let execution_config = ExecutionConfig::default();
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)* status: 0 of 5 files reviewed, 11 unresolved discussions (waiting on @ArniStarkware, @noaov1, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 135 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O99HqSO6gxouRbdBUfk:-O99Tyx47AtPpZjonbNq:bbr7k36) ([raw file](https://github.com/starkware-libs/sequencer/blob/460a98da079cfc87fdd3d03c5f3867fc918f7b8a/crates/blockifier/src/bouncer.rs#L135)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

All values, except `state_diff_size: 4000` (as you requested), were taken from `starkware/starknet/services/batcher/config.yml` as Lior suggested. These are placeholder values to get the program running and will be updated later.
___
*[`crates/blockifier/src/bouncer.rs` line 303 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O99HglRB6rf9n7_uhsz:-O99UplM2G03TPRNc9kp:be0b68s) ([raw file](https://github.com/starkware-libs/sequencer/blob/460a98da079cfc87fdd3d03c5f3867fc918f7b8a/crates/blockifier/src/bouncer.rs#L303)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

There should not be zeros here. Where did it come from?
</blockquote></details>

The builtins were calculated as `n_steps (2500000) / ratio` from `src/starkware/cairo/lang/instances_external.py`. I set unlisted builtins to zero, which I think won’t stop the program from running, right?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)* status: 0 of 5 files reviewed, 10 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 135 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O99HqSO6gxouRbdBUfk:-O99YjWy6AnLmKFWIrm7:b32w1t) ([raw file](https://github.com/starkware-libs/sequencer/blob/460a98da079cfc87fdd3d03c5f3867fc918f7b8a/crates/blockifier/src/bouncer.rs#L135)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

All values, except `state_diff_size: 4000` (as you requested), were taken from `starkware/starknet/services/batcher/config.yml` as Lior suggested. These are placeholder values to get the program running and will be updated later.
</blockquote></details>

Ok

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)* status: 0 of 5 files reviewed, 10 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 303 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O99HglRB6rf9n7_uhsz:-O99YtE2A3zOngeFAtRN:bxp0uf0) ([raw file](https://github.com/starkware-libs/sequencer/blob/460a98da079cfc87fdd3d03c5f3867fc918f7b8a/crates/blockifier/src/bouncer.rs#L303)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

The builtins were calculated as `n_steps (2500000) / ratio` from `src/starkware/cairo/lang/instances_external.py`. I set unlisted builtins to zero, which I think won’t stop the program from running, right?
</blockquote></details>

It would fail txs the use these builtins (even in tests it's not good)
use `starknet_with_keccak_instance` ratios and use the ratio of range_check for
`"add_mod_builtin", "mul_mod_builtin", "range_check96_builtin"`

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)* status: 0 of 6 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware, @noaov1, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 303 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O99HglRB6rf9n7_uhsz:-O99ab3M-viUNkkLUDrM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/460a98da079cfc87fdd3d03c5f3867fc918f7b8a/crates/blockifier/src/bouncer.rs#L303)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

It would fail txs the use these builtins (even in tests it's not good)
use `starknet_with_keccak_instance` ratios and use the ratio of range_check for
`"add_mod_builtin", "mul_mod_builtin", "range_check96_builtin"`
</blockquote></details>

Done.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)* status: 1 of 6 files reviewed, 9 unresolved discussions (waiting on @noaov1, @Yael-Starkware, and @Yoni-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 4 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O93Kl1DAp-6QdSVvp1N:-O99gHBd2iiexGrvTMh2:br35qzk) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/blockifier/src/bouncer.rs#L137)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see 3750

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 291 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O99oXwbA_tCC00iyPW5:-O99oXwbA_tCC00iyPW6:bqknzs3) ([raw file](https://github.com/starkware-libs/sequencer/blob/c573f0bcd6b9350ed4806db8378d0ef24fb28fc6/crates/blockifier/src/bouncer.rs#L291)):*
> ```XML
> }
> 
> impl Default for BuiltinCount {
> ```

please add a todo for each struct that doesn't represent the real production values, so we won't forget to fix it in the future.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O93Kl1DAp-6QdSVvp1N:-O99sXIL0nh39cuDSkl5:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0600ce781549d96c67db786e44bd0d0467735f6/crates/blockifier/src/bouncer.rs#L137)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I still see 3750
</blockquote></details>

Done
___
*[`crates/blockifier/src/bouncer.rs` line 291 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O99oXwbA_tCC00iyPW5:-O99tgZM5pjaTu4bZDqJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c573f0bcd6b9350ed4806db8378d0ef24fb28fc6/crates/blockifier/src/bouncer.rs#L291)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

please add a todo for each struct that doesn't represent the real production values, so we won't forget to fix it in the future.
</blockquote></details>

Done.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1277)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Comment by ArniStarkware** [comment]
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1277#-O9DVS0w06uOESGjk60E):*
Extremely non-blocking. (you  can fix the merge massage)



_Suggestion:_
```
impl default to BlockBuilderConfig towards implementation of BatcherConfig
```

**Pull request merged**
