### PR TITLE
chore(gateway): rename cairo_lang_compiler file

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/330)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/330?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#331** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/331?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#330** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/330?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#319** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/319?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#318** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/318?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#283** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/283?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#284](https://github.com/starkware-libs/sequencer/pull/284) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/284?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#250** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/250?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/330)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/330)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Aug 8, 5:47 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/330).

**Pull request merged**
