### PR TITLE
feat(network): add dns transport

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/704)

### CODE REVIEW

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/704)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare, @idan-starkware, and @ShahakShama)

___
*[`crates/papyrus_network/src/bin_utils/mod.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/704#-O5wRC-6Azihf4NAhIN-:-O5wRC-6Azihf4NAhIN0:b-7rn6f3) ([raw file](https://github.com/starkware-libs/sequencer/blob/916339410eccf5cb927cbeb51b8f37ae88ee14a9/crates/papyrus_network/src/bin_utils/mod.rs#L34)):*
> ```XML
>         .expect("Error building TCP transport")
>         .with_dns()
>         .expect("Error building DNS transport")
> ```

were you able to somehow test this? does it work with and without providing DNS?

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/704)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare, @idan-starkware, and @ShahakShama)

___
*[`crates/papyrus_network/src/bin_utils/mod.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/704#-O5wRC-6Azihf4NAhIN-:-O5wxkPVE6cR7h1B3oHZ:bm7jqre) ([raw file](https://github.com/starkware-libs/sequencer/blob/916339410eccf5cb927cbeb51b8f37ae88ee14a9/crates/papyrus_network/src/bin_utils/mod.rs#L34)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Yes, I tested it. Managed connecting to another node via dns and without this PR it failed
</blockquote></details>

but can we still connect to another node without DNS with pr?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/704)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare, @eitanm-starkware, and @idan-starkware)

___
*[`crates/papyrus_network/src/bin_utils/mod.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/704#-O5wRC-6Azihf4NAhIN-:-O5wynmL9Ltf3J2ht-GF:bjx6nwt) ([raw file](https://github.com/starkware-libs/sequencer/blob/916339410eccf5cb927cbeb51b8f37ae88ee14a9/crates/papyrus_network/src/bin_utils/mod.rs#L34)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

yes, just checked now
</blockquote></details>

Besides, the CI passes so the e2e test checked that as well

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/704#-:-O5x02oHBUUMt_j5TIEE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare and @idan-starkware)

**Review by idan-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/704)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Pull request merged**
