### PR TITLE
chore: use create wrapper server macro with p2p runner

### PR DESCRIPTION
**Pull request by nadin-Starkware**
**Stack**:
- #1961
- #1960
- #1959
- #1958
- #1957
- #1956
- #1933
- #1924 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
Please remove 
```
pub fn create_mempool_p2p_runner_server(
    mempool_p2p_runner: MempoolP2pRunner,
) -> MempoolP2pRunnerServer {
    WrapperServer::new(mempool_p2p_runner)
}
```

From `crates/mempool_p2p/src/runner/mod.rs`

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1924#-:-OBV3hBmBOzuJZiUUkch:b42rjbt)* status: 0 of 1 files reviewed, all discussions resolved

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1924#-:-OBV3qJHAS9HLyksBRZv:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by nadin-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1924)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Comment by nadin-Starkware** [comment]
✓ Commit merged in pull request [#1956](https://github.com/starkware-libs/sequencer/pull/1956)

**Pull request closed without merging**
