### PR TITLE
build(ci): preserve rust version when merging

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/613)

### CODE REVIEW

**Comment by nimrod-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/613?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#613** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/613?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#612** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/612?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nimrod-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/613#-:-O5IUG8kA051M7Vw_dcw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`scripts/merge_branches.py` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/613#-O5ITLZN1mvv93tLzMlD:-O5ITLZN1mvv93tLzMlE:b443r7g) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb7ce726b70ae89af239e500ddb44276f0d427dc/scripts/merge_branches.py#L19)):*
> ```Python
> FINAL_BRANCH = "main"
> MERGE_PATHS_FILE = "scripts/merge_paths.json"
> FILES_TO_PRESERVE = [".github/actions/install_rust/rust_version.txt"]
> ```

consider making this a `set` (non-blocking)



_Suggestion:_
```Python
FILES_TO_PRESERVE = {".github/actions/install_rust/rust_version.txt"}
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/613)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

___
*[`scripts/merge_branches.py` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/613#-O5ITLZN1mvv93tLzMlD:-O5IcB1F3Op4FhO5ObF3:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb7ce726b70ae89af239e500ddb44276f0d427dc/scripts/merge_branches.py#L19)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

consider making this a `set` (non-blocking)
</blockquote></details>

Done

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/613)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request closed without merging**
