### PR TITLE
feat(network): add peer manager and discovery config to network config

### PR DESCRIPTION
**Pull request by AlonLStarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1397)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1397)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare)

___
*[`crates/papyrus_network/src/lib.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1397#-O9A3l9_AN0PcpxX9898:-O9A3l9_AN0PcpxX9899:b-lca1fx) ([raw file](https://github.com/starkware-libs/sequencer/blob/e8b67269c6a6e642ccb831f250b7d372114e89f4/crates/papyrus_network/src/lib.rs#L89)):*
> ```XML
>                 ParamPrivacyInput::Public,
>             ),
>             ser_param(
> ```

You should use append_sub_config_name instead and implement SerializeConfig on DiscoveryConfig and PeerManagerConfig

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1397)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/lib.rs` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1397#-O9A3l9_AN0PcpxX9898:-O9iG2s0BTebld0yZqc7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e8b67269c6a6e642ccb831f250b7d372114e89f4/crates/papyrus_network/src/lib.rs#L89)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You should use append_sub_config_name instead and implement SerializeConfig on DiscoveryConfig and PeerManagerConfig
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1397)* status: all files reviewed, 4 unresolved discussions (waiting on @AlonLStarkWare)

___
*[`crates/papyrus_network/src/discovery/mod.rs` line 210 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1397#-OACN5azE9GHUl5VdE9P:-OACN5azE9GHUl5VdE9Q:byxugl3) ([raw file](https://github.com/starkware-libs/sequencer/blob/a71bb754d7a0964988ddd11619768179439aa389/crates/papyrus_network/src/discovery/mod.rs#L210)):*
> ```XML
>             "bootstrap_dial_retry_config",
>         ));
>         dump.append(&mut BTreeMap::from([ser_param(
> ```

Keep the same style as the other places: First create the map with heartbeat_interval and then extend with sub config
https://github.com/starkware-libs/sequencer/blob/b7f8ed7bfd7f7c3ce3919bc64eba686e9388fa1e/crates/papyrus_storage/src/lib.rs#L624
___
*[`crates/papyrus_network/src/discovery/mod.rs` line 212 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1397#-OACNbymEr8-KNbcm40U:-OACNbymEr8-KNbcm40V:bbigciv) ([raw file](https://github.com/starkware-libs/sequencer/blob/a71bb754d7a0964988ddd11619768179439aa389/crates/papyrus_network/src/discovery/mod.rs#L212)):*
> ```XML
>         dump.append(&mut BTreeMap::from([ser_param(
>             "heartbeat_interval",
>             &self.heartbeat_interval,
> ```

use .as_millis(), add `#[serde(deserialize_with = "deserialize_millis_to_duration")]` on top of the field in the struct, and add in the description the fact that it's in milliseconds
___
*[`crates/papyrus_network/src/discovery/mod.rs` line 213 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1397#-OACNw_M2mhsxir9nrdC:-OACNw_M2mhsxir9nrdD:b-f0g596) ([raw file](https://github.com/starkware-libs/sequencer/blob/a71bb754d7a0964988ddd11619768179439aa389/crates/papyrus_network/src/discovery/mod.rs#L213)):*
> ```XML
>             "heartbeat_interval",
>             &self.heartbeat_interval,
>             "The interval between each Kademlia (discovery) query.",
> ```

Swap between kademlia and discovery: kademlia should be in parentheses

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1397)* status: 2 of 10 files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/discovery/mod.rs` line 210 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1397#-OACN5azE9GHUl5VdE9P:-OACkYhoCZvYCel8NFXg:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/a71bb754d7a0964988ddd11619768179439aa389/crates/papyrus_network/src/discovery/mod.rs#L210)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Keep the same style as the other places: First create the map with heartbeat_interval and then extend with sub config
https://github.com/starkware-libs/sequencer/blob/b7f8ed7bfd7f7c3ce3919bc64eba686e9388fa1e/crates/papyrus_storage/src/lib.rs#L624
</blockquote></details>

Done
___
*[`crates/papyrus_network/src/discovery/mod.rs` line 212 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1397#-OACNbymEr8-KNbcm40U:-OACl1OXDSsBN2kJMo1h:b24hqse) ([raw file](https://github.com/starkware-libs/sequencer/blob/a71bb754d7a0964988ddd11619768179439aa389/crates/papyrus_network/src/discovery/mod.rs#L212)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

use .as_millis(), add `#[serde(deserialize_with = "deserialize_millis_to_duration")]` on top of the field in the struct, and add in the description the fact that it's in milliseconds
</blockquote></details>

Done.
Added the function in utils, should it be in the same file?
___
*[`crates/papyrus_network/src/discovery/mod.rs` line 213 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1397#-OACNw_M2mhsxir9nrdC:-OACl1hk9bpeSZ3mJ1wn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a71bb754d7a0964988ddd11619768179439aa389/crates/papyrus_network/src/discovery/mod.rs#L213)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Swap between kademlia and discovery: kademlia should be in parentheses
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r3, 2 of 5 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1397)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare)

___
*[`crates/papyrus_network/src/utils.rs` line 93 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1397#-OAICQxk9oO8KE_Sta_N:-OAICQxk9oO8KE_Sta_O:b4lcom8) ([raw file](https://github.com/starkware-libs/sequencer/blob/5ad338a62a23739251b7f9e58bc0ccde9789d060/crates/papyrus_network/src/utils.rs#L93)):*
> ```XML
> 
> // Function to deserialize milliseconds to Duration
> pub(crate) fn deserialize_millis_to_duration<'de, D>(deserializer: D) -> Result<Duration, D::Error>
> ```

Put this where we define deserialize_seconds_to_duration
___
*[`crates/papyrus_network/src/discovery/mod.rs` line 212 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1397#-OACNbymEr8-KNbcm40U:-OAICbmV7CxKhVdvdsuS:bljnti8) ([raw file](https://github.com/starkware-libs/sequencer/blob/a71bb754d7a0964988ddd11619768179439aa389/crates/papyrus_network/src/discovery/mod.rs#L212)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

Done.
Added the function in utils, should it be in the same file?
</blockquote></details>

answered in a comment above

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1397)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/utils.rs` line 93 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1397#-OAICQxk9oO8KE_Sta_N:-OAIJ8Y64NmlFnI7DQs9:b-ana6mn) ([raw file](https://github.com/starkware-libs/sequencer/blob/10071029ce38ae344e948d62e5df34ae01f95751/crates/papyrus_network/src/utils.rs#L93)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Put this where we define deserialize_seconds_to_duration
</blockquote></details>

Apparently we have this function but with a different name (milliseconds instead of millis) so I switched to it

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1397#-:-OAIQhKp6edcNBkJ27vO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Pull request merged**
