### PR TITLE
refactor: committer node index

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/160)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/160?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#154** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/154?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#160** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/160?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#156** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/156?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#140** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/140?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#133** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/133?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main-v0.13.2`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/160?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#154** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/154?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#160** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/160?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#156** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/156?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#140** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/140?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#133** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/133?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main-v0.13.2`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/160)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/160#-O2yIMT-3N0K2PratBuL:-O2yIMT-3N0K2PratBuM:bqbp41p) ([raw file](https://github.com/starkware-libs/sequencer/blob/b3dc633cfe1a07cc1a8d4813f537425dfb5bda53/crates/committer/src/patricia_merkle_tree/types.rs#L285)):*
> ```XML
> pub(crate) fn node_index_from_class_hash(class_hash: &ClassHash) -> NodeIndex {
>     NodeIndex::from_leaf_felt(&class_hash.0)
> }
> ```

I prefer these won't be standalone functions... can you implement a `to_node_index` method on the specific types (`ContractAddress`, `StarknetStorageKey`, `ClassHash`)?



_Code quote:_
```XML
pub(crate) fn node_index_from_contract_address(address: &ContractAddress) -> NodeIndex {
    NodeIndex::from_leaf_felt(&address.0)
}

pub(crate) fn node_index_from_starknet_storage_key(key: &StarknetStorageKey) -> NodeIndex {
    NodeIndex::from_leaf_felt(&key.0)
}

pub(crate) fn node_index_from_class_hash(class_hash: &ClassHash) -> NodeIndex {
    NodeIndex::from_leaf_felt(&class_hash.0)
}
```
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/160#-O2yIc4U20dNfmbmTHNI:-O2yIc4U20dNfmbmTHNJ:b-vz5kue) ([raw file](https://github.com/starkware-libs/sequencer/blob/b3dc633cfe1a07cc1a8d4813f537425dfb5bda53/crates/committer/src/patricia_merkle_tree/types_test.rs#L40)):*
> ```XML
>         node_index_from_contract_address,
>         node_index_from_starknet_storage_key,
>     };
> ```

`use`s at the top



_Code quote:_
```XML
    use crate::patricia_merkle_tree::types::{
        node_index_from_contract_address,
        node_index_from_starknet_storage_key,
    };
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/160)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 285 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/160#-O2yIMT-3N0K2PratBuL:-O36j4pXD94173fXfDQw:b2nhswy) ([raw file](https://github.com/starkware-libs/sequencer/blob/b3dc633cfe1a07cc1a8d4813f537425dfb5bda53/crates/committer/src/patricia_merkle_tree/types.rs#L285)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I prefer these won't be standalone functions... can you implement a `to_node_index` method on the specific types (`ContractAddress`, `StarknetStorageKey`, `ClassHash`)?
</blockquote></details>

Yes
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/160#-O2yIc4U20dNfmbmTHNI:-O36vTTc5C5YeGel0Cmd:bcp9w4w) ([raw file](https://github.com/starkware-libs/sequencer/blob/b3dc633cfe1a07cc1a8d4813f537425dfb5bda53/crates/committer/src/patricia_merkle_tree/types_test.rs#L40)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`use`s at the top
</blockquote></details>

Deleted.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/160)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware and @nimrod-starkware)

___
*[`crates/committer/src/block_committer/commit.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/160#-O38JIp4Cavp9Nc6rLJC:-O38JIp5CuyIOJxpiUq4:b7tyje6) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bfb89e7697da545816b9421543924cfecad6a55/crates/committer/src/block_committer/commit.rs#L107)):*
> ```XML
>     let accessed_addresses = state_diff.accessed_addresses();
>     let contracts_trie_indices: Vec<NodeIndex> =
>         accessed_addresses.iter().map(|address| (*address).into()).collect();
> ```

does this work?



_Suggestion:_
```XML
NodeIndex::from
```
___
*[`crates/committer/src/block_committer/commit.rs` line 111 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/160#-O38JOK0-hi-eeYCinTn:-O38JOK0-hi-eeYCinTo:b-7ropln) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bfb89e7697da545816b9421543924cfecad6a55/crates/committer/src/block_committer/commit.rs#L111)):*
> ```XML
>         .class_hash_to_compiled_class_hash
>         .keys()
>         .map(|class_hash| class_hash.into())
> ```

ditto



_Suggestion:_
```XML
NodeIndex::from
```
___
*[`crates/committer/src/block_committer/commit.rs` line 117 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/160#-O38JQYf4Premi0Y3aHQ:-O38JQYf4Premi0Y3aHR:b-7ropln) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bfb89e7697da545816b9421543924cfecad6a55/crates/committer/src/block_committer/commit.rs#L117)):*
> ```XML
>         .map(|address| {
>             let indices: Vec<NodeIndex> = match state_diff.storage_updates.get(address) {
>                 Some(updates) => updates.keys().map(|key| key.into()).collect(),
> ```

ditto



_Suggestion:_
```XML
NodeIndex::from
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/160)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/committer/src/block_committer/commit.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/160#-O38JIp4Cavp9Nc6rLJC:-O3RFBNQ2OwHncwG54PZ:b5z0fol) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bfb89e7697da545816b9421543924cfecad6a55/crates/committer/src/block_committer/commit.rs#L107)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does this work?
</blockquote></details>

Not here since 'into' called on *address rather than address.
___
*[`crates/committer/src/block_committer/commit.rs` line 111 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/160#-O38JOK0-hi-eeYCinTn:-O3RGKpk9L4pX4eGjwnO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bfb89e7697da545816b9421543924cfecad6a55/crates/committer/src/block_committer/commit.rs#L111)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`crates/committer/src/block_committer/commit.rs` line 117 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/160#-O38JQYf4Premi0Y3aHQ:-O3RGQ96Cs0935Fh7cxr:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bfb89e7697da545816b9421543924cfecad6a55/crates/committer/src/block_committer/commit.rs#L117)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/160#-:-O3WieDV6dKwxEQv5PfY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Comment by AvivYossef-starkware** [comment]
### Merge activity

* **Aug 5, 6:34 AM EDT**: @AvivYossef-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/160).

**Pull request merged**
