### PR TITLE
refactor(starknet_gateway): hide the whole business logic struct behind an arc

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2879?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2879** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2879?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2879?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2877** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2877?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ArniStarkware** [comment]
This PR, should be squashed into the previous PR if we like it.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2879)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_gateway/src/gateway.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2879#-OEmi3Uy-shYVoKaRcAd:-OEmi3Uy-shYVoKaRcAe:bdpfw95) ([raw file](https://github.com/starkware-libs/sequencer/blob/a276aef0f8a24cf3430d12083449d5eaa29aea64/crates/starknet_gateway/src/gateway.rs#L61)):*
> ```XML
>             chain_info: config.chain_info.clone(),
>         };
>         Self { config: config.clone(), business_logic: Arc::new(business_logic), mempool_client }
> ```

why do you need to Arc both the internal fields and the outer struct? isn't one of them enough for this?



_Code quote:_
```XML
Arc::new(business_logic)
```

**Comment by ArniStarkware** [comment]
*[`crates/starknet_gateway/src/gateway.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2879#-OEmi3Uy-shYVoKaRcAd:-OEmjosrBDQz7LElEIdq:b-in6i71) ([raw file](https://github.com/starkware-libs/sequencer/blob/a276aef0f8a24cf3430d12083449d5eaa29aea64/crates/starknet_gateway/src/gateway.rs#L61)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why do you need to Arc both the internal fields and the outer struct? isn't one of them enough for this?
</blockquote></details>

This PR is just about that issue. 
Before this PR: `GatewayBusinessLogic` had five members - four of which were `Arc`.
After this PR: `GatewayBusinessLogic` has just one `Arc` inside of it for the `StateReaderFactory` (if we can even remove it, it would be lovely. I failed using ChatGPT). In return - this struct is now hidden inside `Arc`.

Or maybe I do not understand the question.

**Comment by ArniStarkware** [comment]
No need.

**Pull request closed without merging**
