### PR TITLE
chore(blockifier_reexecution): serialize reexecution data to file

### PR DESCRIPTION
**Pull request by aner-starkware**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1762)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 302 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OAmzuKW0j4CKBLnMzug:-OAmzuKW0j4CKBLnMzuh:b-wtg8ey) ([raw file](https://github.com/starkware-libs/sequencer/blob/57fced1590e6b1c881ee0e9207b6a5d6ddce7a31/crates/blockifier/src/state/cached_state.rs#L302)):*
> ```XML
>         Ok(self.cache.borrow().initial_reads.clone())
>     }
> }
> ```

can you solve this by injecting more code into the test state reader?
i.e. every `get_X` should check if this key was read before, and if not, populate self? like you do with compiled classes?

I do not want to touch blockifier code; this is only useful for reexecution



_Code quote:_
```XML
#[cfg(any(feature = "testing", test))]
impl<S: StateReader> CachedState<S> {
    pub fn get_initial_reads(&self) -> StateResult<StateMaps> {
        Ok(self.cache.borrow().initial_reads.clone())
    }
}
```
___
*[`crates/blockifier_reexecution/src/main.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OAn-Ezs1atlwq_ZM7b0:-OAn-Ezt97_SOzWL416z:b-enhzvj) ([raw file](https://github.com/starkware-libs/sequencer/blob/57fced1590e6b1c881ee0e9207b6a5d6ddce7a31/crates/blockifier_reexecution/src/main.rs#L104)):*
> ```XML
>         } => {
>             let directory_path = directory_path
>                 .unwrap_or(format!("./crates/blockifier_reexecution/tmp/block_{block_number}/"));
> ```

1. why give a temporary name?
2. I suggest putting this in a `resources` dir; like the `read_from_json` function expects. blockifier has such a directory for artifacts



_Code quote:_
```XML
tmp
```
___
*[`crates/blockifier_reexecution/src/main.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OAn04mv7pJxPFZkQ500:-OAn04mv7pJxPFZkQ501:b-7jz43c) ([raw file](https://github.com/starkware-libs/sequencer/blob/57fced1590e6b1c881ee0e9207b6a5d6ddce7a31/crates/blockifier_reexecution/src/main.rs#L121)):*
> ```XML
>             let transactions_next_block = next_block_state_reader.get_all_txs_in_block().unwrap();
> 
>             let blockifier_transactions_next_block = &last_block_state_reader
> ```

why are the `next` txs taken from the `last` block?



_Code quote:_
```XML
let blockifier_transactions_next_block = &last_block_state_reader
```
___
*[`crates/blockifier_reexecution/src/main.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OAn-guLCZ4HVbP1WAb2:-OAn-guLCZ4HVbP1WAb3:b-3n7zz8) ([raw file](https://github.com/starkware-libs/sequencer/blob/57fced1590e6b1c881ee0e9207b6a5d6ddce7a31/crates/blockifier_reexecution/src/main.rs#L156)):*
> ```XML
>                 "RPC replies required for reexecuting block {block_number} written to json file."
>             );
>         }
> ```

code duplication with the non-dump command... please extract to a function that accepts the input data + boolean named `dump_mode`



_Code quote:_
```XML
        } => {
            let directory_path = directory_path
                .unwrap_or(format!("./crates/blockifier_reexecution/tmp/block_{block_number}/"));
            let config = RpcStateReaderConfig {
                url: node_url,
                json_rpc_version: JSON_RPC_VERSION.to_string(),
            };

            let ConsecutiveTestStateReaders { last_block_state_reader, next_block_state_reader } =
                ConsecutiveTestStateReaders::new(BlockNumber(block_number - 1), Some(config), true);

            let block_info_next_block = next_block_state_reader.get_block_info().unwrap();

            let starknet_version = next_block_state_reader.get_starknet_version().unwrap();

            let state_diff_next_block = next_block_state_reader.get_state_diff().unwrap();

            let transactions_next_block = next_block_state_reader.get_all_txs_in_block().unwrap();

            let blockifier_transactions_next_block = &last_block_state_reader
                .api_txs_to_blockifier_txs(transactions_next_block.clone())
                .unwrap();

            let mut transaction_executor = last_block_state_reader
                .get_transaction_executor(
                    next_block_state_reader.get_block_context().unwrap(),
                    None,
                )
                .unwrap();

            transaction_executor.execute_txs(blockifier_transactions_next_block);

            let block_state = transaction_executor.block_state.unwrap();
            let initial_reads = block_state.get_initial_reads().unwrap();

            let contract_class_mapping =
                block_state.state.get_contract_class_mapping_dumper().unwrap();

            let serializable_offline_reexecution_data = SerializableOfflineReexecutionData {
                state_maps: initial_reads.into(),
                block_info_next_block,
                starknet_version,
                transactions_next_block,
                contract_class_mapping,
                state_diff_next_block,
            };

            serializable_offline_reexecution_data
                .write_to_file(&directory_path, "reexecution_data.json")
                .unwrap();

            println!(
                "RPC replies required for reexecuting block {block_number} written to json file."
            );
        }
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1762)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OAn-Ezs1atlwq_ZM7b0:-OAppXvN-qoC_n1OFLUM:b3hynkv) ([raw file](https://github.com/starkware-libs/sequencer/blob/57fced1590e6b1c881ee0e9207b6a5d6ddce7a31/crates/blockifier_reexecution/src/main.rs#L104)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. why give a temporary name?
2. I suggest putting this in a `resources` dir; like the `read_from_json` function expects. blockifier has such a directory for artifacts
</blockquote></details>

Done. It's just a question of the behavior for the default path - should it ben written in a "real" location or a temporary one?
___
*[`crates/blockifier_reexecution/src/main.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OAn04mv7pJxPFZkQ500:-OAppzNF9hPFiCCCbmO-:bix24m6) ([raw file](https://github.com/starkware-libs/sequencer/blob/57fced1590e6b1c881ee0e9207b6a5d6ddce7a31/crates/blockifier_reexecution/src/main.rs#L121)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why are the `next` txs taken from the `last` block?
</blockquote></details>

See my answer in previous PR.
___
*[`crates/blockifier_reexecution/src/main.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OAn-guLCZ4HVbP1WAb2:-OAprf0A4vh9wxkMs5NO:b-cpknyd) ([raw file](https://github.com/starkware-libs/sequencer/blob/57fced1590e6b1c881ee0e9207b6a5d6ddce7a31/crates/blockifier_reexecution/src/main.rs#L156)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

code duplication with the non-dump command... please extract to a function that accepts the input data + boolean named `dump_mode`
</blockquote></details>

I added a TODO. I think it's better to delay this refactoring until this PR (when it's ready): https://reviewable.io/reviews/starkware-libs/sequencer/1764.
The reason is that the command there has even more similar code, so this would avoid double refactoring. Also, this is not exactly code duplication, so I think it's better that the function corresponds to the other two commands, which are much more similar.

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/state/cached_state.rs` line 302 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OAmzuKW0j4CKBLnMzug:-OAqo9XQ89LIj6czNCpE:b-s99l2d) ([raw file](https://github.com/starkware-libs/sequencer/blob/57fced1590e6b1c881ee0e9207b6a5d6ddce7a31/crates/blockifier/src/state/cached_state.rs#L302)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you solve this by injecting more code into the test state reader?
i.e. every `get_X` should check if this key was read before, and if not, populate self? like you do with compiled classes?

I do not want to touch blockifier code; this is only useful for reexecution
</blockquote></details>

Switched the flag, as we agreed.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1762)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier/Cargo.toml` line 13 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OArLGPMCqvk3Pm-2LGD:-OArLGPMCqvk3Pm-2LGE:b-vrm4q9) ([raw file](https://github.com/starkware-libs/sequencer/blob/95680cba950fe7d5a20dcc871b7c2515c4f4f2ab/crates/blockifier/Cargo.toml#L13)):*
> ```TOML
> 
> [features]
> blockifier_reexecution = []
> ```

you are in the blockifier crate: no need for this prefix in the feature name imo



_Suggestion:_
```TOML
reexecution
```
___
*[`crates/blockifier_reexecution/src/main.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OAn04mv7pJxPFZkQ500:-OArLUyM76A3K78A8C1u:b4bhvic) ([raw file](https://github.com/starkware-libs/sequencer/blob/57fced1590e6b1c881ee0e9207b6a5d6ddce7a31/crates/blockifier_reexecution/src/main.rs#L121)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

See my answer in previous PR.
</blockquote></details>

still relevant (right?)
___
*[`crates/blockifier_reexecution/src/main.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OAn-guLCZ4HVbP1WAb2:-OArUo2-1_u5poMK5hAs:btff8e6) ([raw file](https://github.com/starkware-libs/sequencer/blob/57fced1590e6b1c881ee0e9207b6a5d6ddce7a31/crates/blockifier_reexecution/src/main.rs#L156)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I added a TODO. I think it's better to delay this refactoring until this PR (when it's ready): https://reviewable.io/reviews/starkware-libs/sequencer/1764.
The reason is that the command there has even more similar code, so this would avoid double refactoring. Also, this is not exactly code duplication, so I think it's better that the function corresponds to the other two commands, which are much more similar.
</blockquote></details>

I think the other way around:
1. open a PR to extract common logic to a separate function (replacing most of the `Command::RpcTest` implementation)
2. change this current PR to use the shared code
3. in PR 1764 also use common code

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/main.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OAn-guLCZ4HVbP1WAb2:-OArhm5XBnadRy_fBTl-:bjbojjg) ([raw file](https://github.com/starkware-libs/sequencer/blob/57fced1590e6b1c881ee0e9207b6a5d6ddce7a31/crates/blockifier_reexecution/src/main.rs#L156)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

The issue is that it's not exactly common logic—if I do it in this PR, it won't match the code in 1764. If it matches, it won't be clear why that code should be separated and not be a different code part. It's better to wait with this until 1764, which will probably be tomorrow.
</blockquote></details>

Anyway, I'll fix this in 1764; you can block this PR for now

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/main.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OAn-guLCZ4HVbP1WAb2:-OAvZXrE6ZdVdrZKnrMI:b-azjgkj) ([raw file](https://github.com/starkware-libs/sequencer/blob/57fced1590e6b1c881ee0e9207b6a5d6ddce7a31/crates/blockifier_reexecution/src/main.rs#L156)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Anyway, I'll fix this in 1764; you can block this PR for now
</blockquote></details>

Refactoring in the this PR: https://reviewable.io/reviews/starkware-libs/sequencer/1814

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1762)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier/Cargo.toml` line 17 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OAwRZ123JfIOwYoeZ5Y:-OAwRZ123JfIOwYoeZ5Z:b-roc8w1) ([raw file](https://github.com/starkware-libs/sequencer/blob/baaf5847e5eebcb1cfefe68f60c8ecd0f23a0e2a/crates/blockifier/Cargo.toml#L17)):*
> ```TOML
> reexecution = []
> testing = ["rand", "rstest", "starknet_api/testing"]
> transaction_serde = []
> ```

reexecution [should activate the transaction_serde feature](https://doc.rust-lang.org/cargo/reference/features.html#the-features-section), right? we need serialization in reexecution



_Suggestion:_
```TOML
reexecution = ["transaction_serde"]
testing = ["rand", "rstest", "starknet_api/testing"]
transaction_serde = []
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1762)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/Cargo.toml` line 17 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OAwRZ123JfIOwYoeZ5Y:-OAwTPtv5xnNRtQSIbAt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/baaf5847e5eebcb1cfefe68f60c8ecd0f23a0e2a/crates/blockifier/Cargo.toml#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

reexecution [should activate the transaction_serde feature](https://doc.rust-lang.org/cargo/reference/features.html#the-features-section), right? we need serialization in reexecution
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1762)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1762)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1762)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OB4cBdP6TBn4-WKaTLy:-OB4cBdP6TBn4-WKaTLz:bk2p0t0) (no related file):*
why do I see diffs from [here](https://reviewable.io/reviews/starkware-libs/sequencer/1859)

___

**Comment by aner-starkware** [comment]
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do I see diffs from [here](https://reviewable.io/reviews/starkware-libs/sequencer/1859)
</blockquote></details>

Is it fixed?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 5 files at r9, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1762)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OB4cBdP6TBn4-WKaTLy:-OB4uBfF5BNy01jsAvp4:bogsb27) (no related file):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Is it fixed?
</blockquote></details>

yes, thanks

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1762)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OB5SSyHB53boNvt43Vo:-OB5SSyHB53boNvt43Vp:bymv1jp) (no related file):*
please rebase

___

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1762)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OB5SSyHB53boNvt43Vo:-OB5VY7f9RS0xw18ZG4v:b-896fix) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please rebase
</blockquote></details>

Done.

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1762)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 64 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OB5gyeH8A2YeWIuI17I:-OB5gyeH8A2YeWIuI17J:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7439c15e6ae25ec03fdc4409456054c5e2f5d61e/crates/blockifier_reexecution/src/main.rs#L64)):*
> ```XML
>         // "./crates/blockifier_reexecution/resources/block_{block_number}".
>         #[clap(long, short = 'd', default_value = None)]
>         directory_path: Option<String>,
> ```





_Suggestion:_
```XML
        // Directory path to json files. Default:
        // "./crates/blockifier_reexecution/resources/block_{block_number}".
        // TODO: None should indicate using the bucket. Maybe need a commit_id arg.
        #[clap(long, short = 'd', default_value = None)]
        directory_path: Option<String>,
    },

    // Reexecutes the block from JSON files.
    ReexecuteBlock {
        /// Block number.
        #[clap(long, short = 'b')]
        block_number: u64,

        // Directory path to json files. Default:
        // "./crates/blockifier_reexecution/resources/block_{block_number}".
        // TODO: None should indicate using the bucket. Maybe need a commit_id arg.
        #[clap(long, short = 'd', default_value = None)]
        directory_path: Option<String>,
```
___
*[`crates/blockifier_reexecution/src/main.rs` line 141 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OB5hKDP7s0bwipry4Ms:-OB5hKDP7s0bwipry4Mt:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7439c15e6ae25ec03fdc4409456054c5e2f5d61e/crates/blockifier_reexecution/src/main.rs#L141)):*
> ```XML
>             let full_file_path = directory_path.unwrap_or(format!(
>                 "./crates/blockifier_reexecution/resources/block_{block_number}"
>             )) + "/reexecution_data.json";
> ```





_Suggestion:_
```XML
            let full_file_path = directory_path.unwrap_or(format!(
                "./crates/blockifier_reexecution/resources/block_{block_number}/reexecution_data.json"
            ));
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1762)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 64 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OB5gyeH8A2YeWIuI17I:-OB5yoY94eP_x_5UwgtI:b-uhoktg) ([raw file](https://github.com/starkware-libs/sequencer/blob/7439c15e6ae25ec03fdc4409456054c5e2f5d61e/crates/blockifier_reexecution/src/main.rs#L64)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Why? `None` just indicates using the default directory; The bucket will be downloaded to this directory using the script.
</blockquote></details>

what if I have the files already, and I want to point to that location?
I was thinking there would be two (mutually exclusive) options:
1. provide an explicit path, and the CLI will assume the relevant file already exists there
2. provide a git commit, and the CLI will fetch the files from the bucket (to `/tmp` or something)

wdyt?
___
*[`crates/blockifier_reexecution/src/main.rs` line 141 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OB5hKDP7s0bwipry4Ms:-OB5zGNL7yBwCb4KvvdY:bcy60mp) ([raw file](https://github.com/starkware-libs/sequencer/blob/7439c15e6ae25ec03fdc4409456054c5e2f5d61e/crates/blockifier_reexecution/src/main.rs#L141)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

It's different functionality - the first way you only need to specify the directory, this way you need to also need to specify the file name
</blockquote></details>

wdym? `reexecution_data.json` is still part of the string

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1762)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 64 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OB5gyeH8A2YeWIuI17I:-OB604vSAlWyvzm8O6UW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7439c15e6ae25ec03fdc4409456054c5e2f5d61e/crates/blockifier_reexecution/src/main.rs#L64)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what if I have the files already, and I want to point to that location?
I was thinking there would be two (mutually exclusive) options:
1. provide an explicit path, and the CLI will assume the relevant file already exists there
2. provide a git commit, and the CLI will fetch the files from the bucket (to `/tmp` or something)

wdyt?
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/main.rs` line 141 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OB5hKDP7s0bwipry4Ms:-OB6-R4b5ZPZLNUeUoMZ:b-l8hjh8) ([raw file](https://github.com/starkware-libs/sequencer/blob/7439c15e6ae25ec03fdc4409456054c5e2f5d61e/crates/blockifier_reexecution/src/main.rs#L141)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

wdym? `reexecution_data.json` is still part of the string
</blockquote></details>

In the second option, if you specify the location yourself, you also need to specify the file name.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1762)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 141 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OB5hKDP7s0bwipry4Ms:-OB60YvUESiX_GDfpYdH:b-1wwsky) ([raw file](https://github.com/starkware-libs/sequencer/blob/7439c15e6ae25ec03fdc4409456054c5e2f5d61e/crates/blockifier_reexecution/src/main.rs#L141)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

In the second option, if you specify the location yourself, you also need to specify the file name.
</blockquote></details>

ah, yes
if you specify a path, I'm assuming you're not downloading a file - the user can (and should) supply the full path in this case

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-:-OB6IU3y7y0Uvlwa0ew7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 90 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OB6IMB1-SBlmWBIRz92:-OB6IMB1-SBlmWBIRz93:brc3ros) ([raw file](https://github.com/starkware-libs/sequencer/blob/50ad0f4b430ed58c0c128b7f5843ae6008d3f667/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L90)):*
> ```XML
> impl SerializableOfflineReexecutionData {
>     pub fn write_to_file(&self, full_file_path: &str) -> ReexecutionResult<()> {
>         let file_path = full_file_path.rsplit_once('/').expect("Invalid file path.").0;
> ```

consider using `Path` and `PathBuf` objects, we have examples in code - abstracts this kind of logic (non-blocking)



_Code quote:_
```XML
 let file_path = full_file_path.rsplit_once('/').expect("Invalid file path.").0;
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1762)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 90 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/1762#-OB6IMB1-SBlmWBIRz92:-OB6NhGK7DgV_3dLgjNv:b-v7ktt8) ([raw file](https://github.com/starkware-libs/sequencer/blob/50ad0f4b430ed58c0c128b7f5843ae6008d3f667/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L90)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

consider using `Path` and `PathBuf` objects, we have examples in code - abstracts this kind of logic (non-blocking)
</blockquote></details>

I tried - it's longer and not really any clearer.

**Pull request merged**
