### PR TITLE
chore(blockifier): have limit_steps_by_resources flag rep charge_fee flag and enforce_fee ret val

### PR DESCRIPTION
**Pull request by avivg-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 11 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: 11 of 14 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 3 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs` line 244 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O7ScqQ73iWolRBtK-jl:-O7ScqQ73iWolRBtK-jm:bthmwxx) ([raw file](https://github.com/starkware-libs/sequencer/blob/7dd6541636f1a1a6cd0604c05d8d96122a031806/crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs#L244)):*
> ```XML
>         ..trivial_external_entry_point_with_address(test_contract_address)
>     };
> ```

Revert this space

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: 1 of 14 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 118 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O6zuJViEZrmjw64CqYM:-O79L68h4zpitegC8QiB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8cbac7314b7da593f6569974c0228a333f4a34ec/crates/blockifier/src/blockifier/stateful_validator.rs#L118)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Remove all aviv comments.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs` line 244 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O7ScqQ73iWolRBtK-jl:-O80w89wE_ADooWM3mvI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7dd6541636f1a1a6cd0604c05d8d96122a031806/crates/blockifier/src/execution/syscalls/syscall_tests/get_execution_info.rs#L244)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Revert this space
</blockquote></details>

Done.

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: 1 of 14 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware and @noaov1)

___
*[`-- commits` line 4 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O81oqQa2xG_DI7ZoZWn):*
Rebase this PR under  avivg/blockifier/combine_charge_fee_w_enforce_fee

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 14 files at r4, 4 of 13 files at r5, 1 of 1 files at r6, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware and @noaov1)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r4, 4 of 13 files at r5, 1 of 1 files at r6, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: all files reviewed, 5 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 493 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O8LDcjy1AlmBmNrncS9:-O8LDcjy1AlmBmNrncSA:b-d33qn2) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b55ea491e9bcb44b13124d9704d9b5971d2efc0/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L493)):*
> ```XML
>     let limit_steps_by_resources = tx_info.enforce_fee();
>     let result = entry_point_call
>         .execute_directly_given_tx_info(&mut state, tx_info, limit_steps_by_resources)
> ```

Can this change be reverted?



_Code quote:_
```XML
    let limit_steps_by_resources = tx_info.enforce_fee();
    let result = entry_point_call
        .execute_directly_given_tx_info(&mut state, tx_info, limit_steps_by_resources)
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 54 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O8LVFvGA3sBt5UrfzbE:-O8LVFvGA3sBt5UrfzbF:btniarl) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b55ea491e9bcb44b13124d9704d9b5971d2efc0/crates/blockifier/src/test_utils/struct_impls.rs#L54)):*
> ```XML
>     pub fn execute_directly(self, state: &mut dyn State) -> EntryPointExecutionResult<CallInfo> {
>         let tx_info = TransactionInfo::Deprecated(DeprecatedTransactionInfo::default());
>         let limit_steps_by_resources = tx_info.enforce_fee();
> ```

Is this flag needed? Do we want to be able to avoid limiting steps when we run entry points in tests?



_Code quote:_
```XML
 let limit_steps_by_resources = tx_info.enforce_fee();
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 554 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O8LEidTEKMaadquYQr_:-O8LEidTEKMaadquYQra:bapak4v) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b55ea491e9bcb44b13124d9704d9b5971d2efc0/crates/blockifier/src/transaction/account_transaction.rs#L554)):*
> ```XML
>         let limit_steps_by_resources = tx_info.enforce_fee();
>         let mut context =
>             EntryPointExecutionContext::new_invoke(tx_context, limit_steps_by_resources);
> ```

I think that this change can be reverted. We will not get to this method if we do not enforce fee.



_Code quote:_
```XML
        let limit_steps_by_resources = tx_info.enforce_fee();
        let mut context =
            EntryPointExecutionContext::new_invoke(tx_context, limit_steps_by_resources);
```
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 144 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O8LTFG99bQYCwaAUbvT:-O8LTFGA47cyCWlr5cgu:b-rw1bl4) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b55ea491e9bcb44b13124d9704d9b5971d2efc0/crates/blockifier/src/transaction/transaction_execution.rs#L144)):*
> ```XML
>         let mut execution_resources = ExecutionResources::default();
>         let mut context =
>             EntryPointExecutionContext::new_invoke(tx_context.clone(), limit_steps_by_resources);
> ```

Few things to notice here:
We set the max fee of an L1 handler to 0.
What does it mean:
every `enforce_fee` check resulted in false. Hence, we are not limiting steps by resources and do not perform pre validations checks (regardless of the charge fee flag).
Do you preserve this behaviour? 



_Code quote:_
```XML
        let limit_steps_by_resources = execution_flags.charge_fee;
        let mut execution_resources = ExecutionResources::default();
        let mut context =
            EntryPointExecutionContext::new_invoke(tx_context.clone(), limit_steps_by_resources);
```
___
*[`crates/papyrus_execution/src/lib.rs` line 254 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O8LVdiV1dyivZ6HqJ1U:-O8LVdiWDtRP65OleQRC:bejx6gm) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b55ea491e9bcb44b13124d9704d9b5971d2efc0/crates/papyrus_execution/src/lib.rs#L254)):*
> ```XML
>     // TODO(yair): fix when supporting v3 transactions
>     let tx_info = TransactionInfo::Deprecated(DeprecatedTransactionInfo::default());
>     let limit_steps_by_resources = tx_info.enforce_fee();
> ```

Can you please explain this change?



_Code quote:_
```XML
    let limit_steps_by_resources = tx_info.enforce_fee();
```

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: 10 of 14 files reviewed, 6 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`-- commits` line 6 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O8VSwh2BSChFUCnZN0Z):*
Something happened in this PR commit. See if you can rebase and remove the two commits with the same name or if you need to squash one of them. Fell free to ask for help if you need

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: 9 of 16 files reviewed, 6 unresolved discussions (waiting on @avivg-starkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O8bFPgx9u7ix3GE4187:-O8bFPgx9u7ix3GE4188:b-hu81xk) (no related file):*
make sure to check this changes in the python repo as well 

___

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: 15 of 16 files reviewed, 9 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 947 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O8bFj5T9bmb04mIypM1:-O8bFj5T9bmb04mIypM2:b-ogwcjz) ([raw file](https://github.com/starkware-libs/sequencer/blob/96b1e95028f40cb5554d4b7559abb16d06444a5c/crates/blockifier/src/transaction/account_transactions_test.rs#L947)):*
> ```XML
>     let tx_context1 = Arc::new(block_context.to_tx_context(&account_tx1));
>     let charge_fee1 = account_tx1.create_tx_info().enforce_fee();
>     let execution_context1 = EntryPointExecutionContext::new_invoke(tx_context1, charge_fee1);
> ```

Why is this part of this PR? Is this due to a rebase? 



_Code quote:_
```XML
    let charge_fee1 = account_tx1.create_tx_info().enforce_fee();
    let execution_context1 = EntryPointExecutionContext::new_invoke(tx_context1, charge_fee1);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 969 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O8bFulWD4ueZboyB0uC:-O8bFulWD4ueZboyB0uD:b-33b6k6) ([raw file](https://github.com/starkware-libs/sequencer/blob/96b1e95028f40cb5554d4b7559abb16d06444a5c/crates/blockifier/src/transaction/account_transactions_test.rs#L969)):*
> ```XML
>     let tx_context2 = Arc::new(block_context.to_tx_context(&account_tx2));
>     let charge_fee2 = account_tx2.create_tx_info().enforce_fee();
>     let execution_context2 = EntryPointExecutionContext::new_invoke(tx_context2, charge_fee2);
> ```

See comment above



_Code quote:_
```XML
    let charge_fee2 = account_tx2.create_tx_info().enforce_fee();
    let execution_context2 = EntryPointExecutionContext::new_invoke(tx_context2, charge_fee2);
```
___
*[`crates/blockifier/src/transaction/post_execution_test.rs` line 123 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O8bFzIh1DnT4Pz5TXkN:-O8bFzIh1DnT4Pz5TXkO:b-xz7t2u) ([raw file](https://github.com/starkware-libs/sequencer/blob/e984e79d3ce23b57de7127441987d5423de461b5/crates/blockifier/src/transaction/post_execution_test.rs#L123)):*
> ```XML
>     });
>     let tx_info = approve_tx.create_tx_info();
> ```

Please revert this file changes

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: 7 of 16 files reviewed, 8 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 947 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O8bFj5T9bmb04mIypM1:-O8fA8Pf-ERmzKTQlxbP:b-dsym1r) ([raw file](https://github.com/starkware-libs/sequencer/blob/96b1e95028f40cb5554d4b7559abb16d06444a5c/crates/blockifier/src/transaction/account_transactions_test.rs#L947)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why is this part of this PR? Is this due to a rebase?
</blockquote></details>

yes, thank you. I reverted 
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 969 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O8bFulWD4ueZboyB0uC:-O8fAKyf0kO2cbL2p_q_:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/96b1e95028f40cb5554d4b7559abb16d06444a5c/crates/blockifier/src/transaction/account_transactions_test.rs#L969)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

See comment above
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/post_execution_test.rs` line 123 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O8bFzIh1DnT4Pz5TXkN:-O8fAmtC7w4NA5J8PfE2:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/e984e79d3ce23b57de7127441987d5423de461b5/crates/blockifier/src/transaction/post_execution_test.rs#L123)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Please revert this file changes
</blockquote></details>

Done

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 8 of 9 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: all files reviewed, 6 unresolved discussions (waiting on @avivg-starkware and @noaov1)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: all files reviewed, 6 unresolved discussions (waiting on @noaov1)

___
*[`-- commits` line 6 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O8VSwh2BSChFUCnZN0Z):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Something happened in this PR commit. See if you can rebase and remove the two commits with the same name or if you need to squash one of them. Fell free to ask for help if you need
</blockquote></details>

Done

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: 9 of 16 files reviewed, 6 unresolved discussions (waiting on @meship-starkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O8bFPgx9u7ix3GE4187:-O8qvkfKAn7vz-IpIdXf:b3cq44i) (no related file):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

make sure to check this changes in the python repo as well
</blockquote></details>

python PR:

https://github.com/starkware-industries/starkware/pull/36061

___

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 7 of 7 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: all files reviewed, 5 unresolved discussions (waiting on @noaov1)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r9, 2 of 9 files at r10, 7 of 7 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: all files reviewed, 5 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 494 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O94A1uJBSOeR23-230l:-O94A1uJBSOeR23-230m:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/18f62c775c039f75cd33c67c27006a4bc2be5c00/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L494)):*
> ```XML
>         max_fee,
>     });
>     let limit_steps_by_resources = false; // Do not limit steps by resources as account is not funded.
> ```





_Suggestion:_
```XML
    let limit_steps_by_resources = false; // Do not limit steps by resources as we use default reasources..
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 59 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O94AYiW6T61128EU0O7:-O94AYiW6T61128EU0O8:bfknfe6) ([raw file](https://github.com/starkware-libs/sequencer/blob/18f62c775c039f75cd33c67c27006a4bc2be5c00/crates/blockifier/src/test_utils/struct_impls.rs#L59)):*
> ```XML
>     /// bounds.
>     pub fn execute_directly(self, state: &mut dyn State) -> EntryPointExecutionResult<CallInfo> {
>         let tx_info = TransactionInfo::Deprecated(DeprecatedTransactionInfo::default());
> ```

We will always get `max_fee = 0`, so you can simply set it to false :)
Same below.



_Code quote:_
```XML
        let tx_info = TransactionInfo::Deprecated(DeprecatedTransactionInfo::default());
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 649 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O94BBpi42zVa5S6tq3x:-O94BBpi42zVa5S6tq3y:b-eirayb) ([raw file](https://github.com/starkware-libs/sequencer/blob/18f62c775c039f75cd33c67c27006a4bc2be5c00/crates/blockifier/src/transaction/account_transactions_test.rs#L649)):*
> ```XML
>     let initial_balance = state.get_fee_token_balance(deploy_address, fee_token_address).unwrap();
> 
>     let charge_fee = deploy_account_tx.create_tx_info().enforce_fee();
> ```

Why?
It is always true, no? (as we have non-trivial resources)



_Code quote:_
```XML
    let charge_fee = deploy_account_tx.create_tx_info().enforce_fee();
```
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 144 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O8LTFG99bQYCwaAUbvT:-O94BgBp9sSoBQb6Uyt9:bl4jy3q) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b55ea491e9bcb44b13124d9704d9b5971d2efc0/crates/blockifier/src/transaction/transaction_execution.rs#L144)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

It seems that limit_steps_by_resources is inputted to:
    EntryPointExecutionContext::max_steps 
which then is inputted to:
    EntryPointExecutionContext::vm_run_resources

Simultaneously, the overall 'resources' that are being passed are from the second code line you sent
(execution_resources = ExecutionResources::default() )

it leaves me a bit confused as to whether this is actually necessary. on the other hand, removing "limit_steps_by_resources" or setting it to "true" results in changing the func signature (as much as i understand).
</blockquote></details>

We can leave it as is. However, we need to add a special treatment for the L1 handler case.
___
*[`crates/papyrus_execution/src/lib.rs` line 253 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O94LxqC9GRkxWsn1Qt3:-O94LxqC9GRkxWsn1Qt4:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/18f62c775c039f75cd33c67c27006a4bc2be5c00/crates/papyrus_execution/src/lib.rs#L253)):*
> ```XML
>     // TODO(yair): fix when supporting v3 transactions
>     let tx_info = TransactionInfo::Deprecated(DeprecatedTransactionInfo::default());
>     let limit_steps_by_resources = false; // Default resource bounds, thus account is not funded.
> ```





_Suggestion:_
```XML
    let limit_steps_by_resources = false; // Default resource bounds.
```

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: all files reviewed, 5 unresolved discussions (waiting on @avivg-starkware)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 59 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O94AYiW6T61128EU0O7:-O94TE4F9ohENbfxA643:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/18f62c775c039f75cd33c67c27006a4bc2be5c00/crates/blockifier/src/test_utils/struct_impls.rs#L59)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We will always get `max_fee = 0`, so you can simply set it to false :)
Same below.
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 649 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O94BBpi42zVa5S6tq3x:-O94T1lpD-pXKP0feuA7:b-1mzw25) ([raw file](https://github.com/starkware-libs/sequencer/blob/18f62c775c039f75cd33c67c27006a4bc2be5c00/crates/blockifier/src/transaction/account_transactions_test.rs#L649)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why?
It is always true, no? (as we have non-trivial resources)
</blockquote></details>

you're completely right, thank you

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: 10 of 16 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 144 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O8LTFG99bQYCwaAUbvT:-O95YEY9CZfWLEqd0TY8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b55ea491e9bcb44b13124d9704d9b5971d2efc0/crates/blockifier/src/transaction/transaction_execution.rs#L144)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We can leave it as is. However, we need to add a special treatment for the L1 handler case.
</blockquote></details>

Done.

**Review by meship-starkware — APPROVED** [review]
> Reviewed 6 of 6 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: all files reviewed, 4 unresolved discussions (waiting on @avivg-starkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O98_VASAG4bZ20j7qiC:-O98_VASAG4bZ20j7qiD:b-4hfhh6) (no related file):*
Please rebase over main 

___

**Review by meship-starkware — APPROVED** [review]
> Reviewed 12 of 12 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r13, 1 of 12 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833#-:-O9A8IFX-ler0IQkWTy7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 9 files at r10, 4 of 6 files at r13, 9 of 12 files at r15, 3 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 144 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O8LTFG99bQYCwaAUbvT:-O9Ap_tD-zKcqWfgdKtg:bmip9pp) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b55ea491e9bcb44b13124d9704d9b5971d2efc0/crates/blockifier/src/transaction/transaction_execution.rs#L144)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Changed my mind- please set it to `false`.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 144 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O8LTFG99bQYCwaAUbvT:-O9EHbDA-n72VtcR76ui:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b55ea491e9bcb44b13124d9704d9b5971d2efc0/crates/blockifier/src/transaction/transaction_execution.rs#L144)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Changed my mind- please set it to `false`.
</blockquote></details>

Done.

**Review by avivg-starkware — COMMENTED** [review]
> Reviewed 1 of 14 files at r4, 1 of 9 files at r9, 1 of 9 files at r10, 2 of 7 files at r12, 4 of 6 files at r13, 10 of 12 files at r15, 3 of 3 files at r16.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: 13 of 22 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

**Review by noaov1 — APPROVED** [review]
> Reviewed 9 of 9 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 89 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O9EQ1wI9Aj156UlY21d:-O9EQ1wI9Aj156UlY21e:b3kre) ([raw file](https://github.com/starkware-libs/sequencer/blob/ac8ac5ef9fe1e08984181e8a2fe13aa206b4cf67/crates/blockifier/src/test_utils/struct_impls.rs#L89)):*
> ```XML
>         self.execute_directly_given_tx_info(
>             state,
>             TransactionInfo::Deprecated(DeprecatedTransactionInfo::default()),
> ```

?



_Suggestion:_
```XML
             // TODO(Yoni, 1/12/2024): change the default to V3.
            TransactionInfo::Deprecated(DeprecatedTransactionInfo::default()),
```

**Review by avivg-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 89 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/833#-O9EQ1wI9Aj156UlY21d:-O9EfveYByCjLNDcvMYE:biqrejr) ([raw file](https://github.com/starkware-libs/sequencer/blob/ad894891949cce91001e5c2b1d4065e2e6d6bed6/crates/blockifier/src/test_utils/struct_impls.rs#L89)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

?
</blockquote></details>

there's only one comment such as this  I see in this file on origin/main ( line 54 ). perhaps it was recently changed?

**Review by avivg-starkware — COMMENTED** [review]
> Reviewed 9 of 9 files at r17.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
> Reviewed 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Review by avivg-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/833)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Pull request merged**
