### PR TITLE
chore(sequencer_node): stop returning clients from create_node_servers

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Comment by yair-starkware** [comment]
* **#2137** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2137?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2137?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2137#-:-OBzGaxk0xxYfSb5WP7g:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2137)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2137)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/starknet_sequencer_node/src/utils.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2137#-OC-dzQwCY8DnRdymOiC:-OC-dzQwCY8DnRdymOiD:bmjfo79) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef8f923e4340462750f5daafbdf93b4fe037d6ab/crates/starknet_sequencer_node/src/utils.rs#L19)):*
> ```XML
> 
>     (clients, servers)
> }
> ```

Please revert this.



_Code quote:_
```XML
pub fn create_node_modules(
    config: &SequencerNodeConfig,
) -> (SequencerNodeClients, SequencerNodeServers) {
    let mut channels = create_node_channels();
    let clients = create_node_clients(config, &mut channels);
    let components = create_node_components(config, &clients);
    let servers = create_node_servers(config, &mut channels, components);

    (clients, servers)
}
```
___
*[`crates/starknet_sequencer_node/src/main.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2137#-OC-djDU-vmJmX278y9g:-OC-djDVBt--ecqgbY3H:bpfz8f8) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef8f923e4340462750f5daafbdf93b4fe037d6ab/crates/starknet_sequencer_node/src/main.rs#L31)):*
> ```XML
> 
>     // Clients are currently unused, but should not be dropped.
>     let (_clients, servers) = create_node_modules(&config);
> ```

The commet here is written in (my) blood.



_Code quote:_
```XML
    // Clients are currently unused, but should not be dropped.
    let (_clients, servers) = create_node_modules(&config);
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2137)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/starknet_sequencer_node/src/main.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2137#-OC-djDU-vmJmX278y9g:-OC-e3UH2LPgeujdiCfD:b7ljnlk) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef8f923e4340462750f5daafbdf93b4fe037d6ab/crates/starknet_sequencer_node/src/main.rs#L31)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

The commet here is written in (my) blood.
</blockquote></details>

(please revert)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2137)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2137#-OC-e9tW6dHxN28QlN9y:-OC-e9tX2s_ieoNakkSC:b9znlne) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef8f923e4340462750f5daafbdf93b4fe037d6ab/crates/starknet_integration_tests/src/flow_test_setup.rs#L33)):*
> ```XML
> 
>     // TODO(Arni): Remove batcher client once the consensus manager is integrated into the test.
>     pub batcher_client: SharedBatcherClient,
> ```

This is great.



_Code quote:_
```XML
    // TODO(Arni): Remove batcher client once the consensus manager is integrated into the test.
    pub batcher_client: SharedBatcherClient,
```

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2137)* status: all files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2137#-:-OC31D9G-OKsXZryqGj9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
