### PR TITLE
chore(sequencing): remove mock context from manager_test.rs

### PR DESCRIPTION
**Pull request by guy-starkware**
I've removed the MockTestContext from manager_test.rs and instead mved it to depend on the mock context in test_utils.rs.

### CODE REVIEW

**Comment by guy-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2524?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2524** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2524?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2524?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2518** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2518?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2517** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2517?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2512** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2512?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2510** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2510?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2524#-:-OEDcb-w1YccS_Z5x7Ln:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2524)* status: all files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/test_utils.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2524#-OEEgcHl72dhQ6N3TYoE:-OEKx9Qt4vkDqtPRwFLJ:b-2cn87o) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a0bbd7b82a91fb6d3e4aad7a3db036c72325346/crates/sequencing/papyrus_consensus/src/test_utils.rs#L24)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Do we actually need Fin to be part of this enum?
</blockquote></details>

I guess we don't :)
___
*[`crates/sequencing/papyrus_consensus/src/test_utils.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2524#-OEEgoJq7oOvNkuogLso:-OEKxT2a6SCf3aYArJ0b:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4a0bbd7b82a91fb6d3e4aad7a3db036c72325346/crates/sequencing/papyrus_consensus/src/test_utils.rs#L52)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2524)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Review by guy-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2524)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
