### PR TITLE
refactor: tree hash function impl

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/156)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/156?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#154** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/154?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#156** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/156?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#140** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/140?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#133** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/133?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main-v0.13.2`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/156)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/156#-O2xzimuBcXUoMmQ7M6N:-O2y-LXu8EMtn-EX2lBn:bkg070o) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I would rather you revert this change.
Why is it needed for crate separation? The starknet crate can implement the patricia crate's hash function, no?
</blockquote></details>

the problem is that the Leafs implement 
` TreeHashFunction<L> for TreeHashFunctionImpl `
but I can't impl TreeHashFunctionImpl directly outside the crate.
I can just put it as a const in hash.rs outside TreeHashFunctionImpl if you want 

___

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/156)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/156#-O2xzimuBcXUoMmQ7M6N:-O36i6pGBGyyk1qT2c95:bz0yhr3) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`TreeHashFunctionImpl` itself shouldn't be in the patricia crate, it should be defined in the starknet crate, no?
</blockquote></details>

We use it in tests, but I think that we can keep it in the Patricia create and use diff struct for starknet crate. is that ok?

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/156)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs` line 498 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/156#-O38Ikid2I7NZPBjSh83:-O38Ikid2I7NZPBjSh84:bn8c1wk) ([raw file](https://github.com/starkware-libs/sequencer/blob/0a992024da433ffad440f4f5aafa10f56ee9932f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs#L498)):*
> ```XML
> #[tokio::test]
> async fn test_update_non_modified_storage_tree(#[case] root_hash: HashOutput) {
>     use crate::patricia_merkle_tree::internal_test_utils::TestTreeHashFunction;
> ```

move to top (why does this keep happening?)



_Code quote:_
```XML
use crate::patricia_merkle_tree::internal_test_utils::TestTreeHashFunction;
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/156)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs` line 498 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/156#-O38Ikid2I7NZPBjSh83:-O3RCSx03vlc6e3EQc9X:b-xgr0lp) ([raw file](https://github.com/starkware-libs/sequencer/blob/0a992024da433ffad440f4f5aafa10f56ee9932f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs#L498)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move to top (why does this keep happening?)
</blockquote></details>

It's happening because I'm using the quick fix to solve the missing imports. I pay more attention to it.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/156#-O2xzXWhCXuvVEpetrc-:-O37oS8x1Bm35H9t9Bcc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0dc9be4bd09d2950a0665155c30a970e0241a036/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L74)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

IMO these two constants should be defined in the hasher context - it is not really part of the implementation of any leaf, it is a property of our hashing scheme.
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/156#-:-O3WiXglDL4Nkx7FCE03:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Comment by AvivYossef-starkware** [comment]
### Merge activity

* **Aug 5, 6:34 AM EDT**: @AvivYossef-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/156).

**Pull request merged**
