### PR TITLE
chore(starknet_batcher): in block builder use the consensus suplied sequncer address

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2409?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2409** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2409?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2409?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2238** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2238?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#2267](https://github.com/starkware-libs/sequencer/pull/2267) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2267?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#2302](https://github.com/starkware-libs/sequencer/pull/2302) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2302?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2346** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2346?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2408](https://github.com/starkware-libs/sequencer/pull/2408) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2408?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2345** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2345?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2341** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2341?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2342** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2342?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2409)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 297 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2409#-ODBOCAS7Ag1kAOb0y3z:-ODBOCAS7Ag1kAOb0y4-:b-m2d9zx) ([raw file](https://github.com/starkware-libs/sequencer/blob/da661e5b9e4c350f044cba493fab7c614ae25019/crates/starknet_batcher/src/block_builder.rs#L297)):*
> ```XML
>             versioned_constants,
>             block_builder_config.bouncer_config,
>         );
> ```

This is the innovation of this PR. Thanks to this change, the block info is supplied to the batcher entirely externally. 



_Code quote:_
```XML
        let block_context = BlockContext::new(
            block_metadata.block_info,
            block_builder_config.chain_info,
            versioned_constants,
            block_builder_config.bouncer_config,
        );
```

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 7 files at r1, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2409#-:-ODGvKyREM_icaLgapWg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 297 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2409#-ODBOCAS7Ag1kAOb0y3z:-ODGv6ib3_v_m4yteon8:btojbfd) ([raw file](https://github.com/starkware-libs/sequencer/blob/da661e5b9e4c350f044cba493fab7c614ae25019/crates/starknet_batcher/src/block_builder.rs#L297)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This is the innovation of this PR. Thanks to this change, the block info is supplied to the batcher entirely externally.
</blockquote></details>

Great!

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2409)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 177 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2409#-ODKTJ7iBEjRnYyPEyhL:-ODKTJ7iBEjRnYyPEyhM:bdpie4c) ([raw file](https://github.com/starkware-libs/sequencer/blob/58e291042523fbae7b3fa41210248a6a935663d3/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L177)):*
> ```XML
>                 ),
>                 use_kzg_da: true,
>                 sequencer_address: ValidatorId::from(TEMPORARY_SEQUENCER_ADDRESS),
> ```

Blocking, until we talk with someone to make to make flow tests pass.



_Code quote:_
```XML
sequencer_address: ValidatorId::from(TEMPORARY_SEQUENCER_ADDRESS),
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2409)* status: 4 of 8 files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/starknet_sequencer_node/src/config/node_config.rs` line 87 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2409#-ODM3JoQEQCSy2JlzOcr:-ODM3JoQEQCSy2JlzOcs:b-7rl8f5) ([raw file](https://github.com/starkware-libs/sequencer/blob/6cb82b2d5d3c9691b84b866cfbd76a9da402b690/crates/starknet_sequencer_node/src/config/node_config.rs#L87)):*
> ```XML
>             ),
>             set_pointing_param_paths(&["batcher_config.block_builder_config.sequencer_address"]),
>         ),
> ```

TODO(Arni):  set a validator id as pointer.



_Code quote:_
```XML
        // TODO(tsabary): set as a regular required parameter.
        (
            ser_pointer_target_required_param(
                "sequencer_address",
                SerializationType::String,
                "The sequencer address.",
            ),
            set_pointing_param_paths(&["batcher_config.block_builder_config.sequencer_address"]),
        ),
```

**Review by alonh5 — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2409)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Dec 5, 9:47 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2409).

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2409)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
