### PR TITLE
feat(blockifier): add native entry point execution

### PR DESCRIPTION
**Pull request by varex83**
Note, that this PR is a copy of https://github.com/starkware-libs/sequencer/pull/551 but with changed "from" branch

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/622)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/622)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @varex83)

___
*[`crates/blockifier/src/execution/native/utils.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/622#-O5gl5Eo7X6cGbfOK7Dh:-O5gl5Eo7X6cGbfOK7Di:b-30ls4d) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa1af67543538d1b6d705f8bf5eadd59218687e6/crates/blockifier/src/execution/native/utils.rs#L54)):*
> ```XML
>     );
> 
>     let run_result = match execution_result {
> ```

When are we expecting the result failure flag to be false? If there is a clear difference between the case of failure flag is true and an error was returned, could you document it (for example, Cairo failure vs. program failure)   
___
*[`crates/blockifier/src/execution/native/utils.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/622#-O5ghzauDim31f5gzilM:-O5ghzauDim31f5gzilN:b-zi83p8) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa1af67543538d1b6d705f8bf5eadd59218687e6/crates/blockifier/src/execution/native/utils.rs#L66)):*
> ```XML
>         }
>         Ok(res) => Ok(res),
>     }?;
> ```

Just to be consistent with the other, I also find the Ok, Err, Ok pattern a bit confusing WDYT?



_Suggestion:_
```XML
    let run_result = match execution_result {
        Err(runner_err) =>
            Err(EntryPointExecutionError::NativeUnexpectedError { source: runner_err }),
        Ok(res) if res.failure_flag => Err(EntryPointExecutionError::NativeExecutionError {
            info: if !res.return_values.is_empty() {
                decode_felts_as_str(&res.return_values)
            } else {
                String::from("Unknown error")
            },
        }),
        Ok(res) => Ok(res),
    }?;
```

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/622)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @varex83)

___
*[`crates/blockifier/src/execution/native/utils.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/622#-O5wfQaGCaVGgsdZfIad:-O5wfQaGCaVGgsdZfIae:bl4ygqo) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa1af67543538d1b6d705f8bf5eadd59218687e6/crates/blockifier/src/execution/native/utils.rs#L87)):*
> ```XML
>     storage_read_values: Vec<Felt>,
>     accessed_storage_keys: HashSet<StorageKey, RandomState>,
> ) -> Result<CallInfo, EntryPointExecutionError> {
> ```

Please change this function to return CallInfo. 
see discussion: https://reviewable.io/reviews/starkware-libs/sequencer/551#-O5HvHgF9ef4_sc5aZh6

**Review by varex83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/622)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @varex83)

___
*[`crates/blockifier/src/execution/native/utils.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/622#-O5gl5Eo7X6cGbfOK7Dh:-O6Lagn_3FqK90-YSG_m:b-5hbjc1) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa1af67543538d1b6d705f8bf5eadd59218687e6/crates/blockifier/src/execution/native/utils.rs#L54)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

When are we expecting the result failure flag to be false? If there is a clear difference between the case of failure flag is true and an error was returned, could you document it (for example, Cairo failure vs. program failure)
</blockquote></details>

As far as I remember, when compilation is successful and we get this error from the runtime as output, we get it together with `failure_flag` set to `true` 
___
*[`crates/blockifier/src/execution/native/utils.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/622#-O5ghzauDim31f5gzilM:-O6Lb5gNEF-HWeCMCRl2:b-1njoch) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa1af67543538d1b6d705f8bf5eadd59218687e6/crates/blockifier/src/execution/native/utils.rs#L66)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Just to be consistent with the other, I also find the Ok, Err, Ok pattern a bit confusing WDYT?
</blockquote></details>

Will do, good catch! 
___
*[`crates/blockifier/src/execution/native/utils.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/622#-O5wfQaGCaVGgsdZfIad:-O6LbA1eDbk6omCdnVvt:bhy9ost) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa1af67543538d1b6d705f8bf5eadd59218687e6/crates/blockifier/src/execution/native/utils.rs#L87)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Please change this function to return CallInfo. 
see discussion: https://reviewable.io/reviews/starkware-libs/sequencer/551#-O5HvHgF9ef4_sc5aZh6
</blockquote></details>

Will do!

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/622)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @varex83)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/622)* status: all files reviewed, 1 unresolved discussion (waiting on @varex83)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/622)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @varex83)

**Review by rodrigo-pino — CHANGES_REQUESTED** [review]
@varex83 this PR doesn't match the latest updates that we have in the Blockifier. There has been a refactor specially targeting this part of the code. Please, update before proceeding. Or did you have something else in mind?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/622#-:-O73fSrR1SmDoJrz0l6F:b-7qxhbw)* status: all files reviewed, 2 unresolved discussions (waiting on @varex83)

___
*[`crates/blockifier/src/execution/native/utils.rs` line 31 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/622#-O73f1nKATEPx3x0zgVe:-O73f1nKATEPx3x0zgVf:b-1enxos) ([raw file](https://github.com/starkware-libs/sequencer/blob/b73d315da96e299c25b0c01be2fffbca7c783bef/crates/blockifier/src/execution/native/utils.rs#L31)):*
> ```XML
> // An arbitrary number, chosen to avoid accidentally aligning with actually calculated gas
> // To be deleted once cairo native gas handling can be used.
> pub const NATIVE_GAS_PLACEHOLDER: u64 = 12;
> ```

I believe there is no need for this constant anymore. Is there a reason for it to be still part of the PR?
___
*[`crates/blockifier/src/execution/native/utils.rs` line 77 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/622#-O73fNF651PjOwmJRGPt:-O73fNF651PjOwmJRGPu:byuf8k8) ([raw file](https://github.com/starkware-libs/sequencer/blob/b73d315da96e299c25b0c01be2fffbca7c783bef/crates/blockifier/src/execution/native/utils.rs#L77)):*
> ```XML
> }
> 
> pub fn create_callinfo(
> ```

Please update to use the latest version of the Call Info

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/622)* status: all files reviewed, 4 unresolved discussions (waiting on @varex83)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 4 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/622#-O73vnDQE3Xh7V9_zZEP:-O73vnDQE3Xh7V9_zZEQ:bpdjh3x) ([raw file](https://github.com/starkware-libs/sequencer/blob/b73d315da96e299c25b0c01be2fffbca7c783bef/crates/blockifier/src/execution/native/entry_point_execution.rs#L4)):*
> ```XML
> 
> use super::syscall_handler::NativeSyscallHandler;
> use super::utils::run_native_executor;
> ```

Please avoid using super 



_Code quote:_
```XML
use super::syscall_handler::NativeSyscallHandler;
use super::utils::run_native_executor;
```
___
*[`crates/blockifier/src/execution/native/utils.rs` line 55 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/622#-O73xlYlCueOXOz6CWz2:-O73xlYm41hzpNRVp-lM:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/b73d315da96e299c25b0c01be2fffbca7c783bef/crates/blockifier/src/execution/native/utils.rs#L55)):*
> ```XML
>         Err(runner_err) => {
>             Err(EntryPointExecutionError::NativeUnexpectedError { source: runner_err })
>         }
> ```





_Suggestion:_
```XML
        Err(runner_err) => 
            Err(EntryPointExecutionError::NativeUnexpectedError { source: runner_err })
        
```

**Comment by rodrigo-pino** [comment]
Solved in #1158

**Pull request closed without merging**
