### PR TITLE
feat(consensus): shc handle sm proposal

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/926)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/926)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 328 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/926#-O7P3llHAyYb53Rq_c4Q:-O7P3llHAyYb53Rq_c4R:b6oi2f9) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ccb9998cb67f9e7527795392fb8f67afedca0c4/crates/sequencing/papyrus_consensus/src/manager_test.rs#L328)):*
> ```XML
> 
> #[tokio::test]
> async fn test_valid_proposal() {
> ```

Why is this test not in `single_height_consensus_test.rs`, that's where you are updating the code?



_Code quote:_
```XML
#[tokio::test]
async fn test_valid_proposal() {
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 373 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/926#-O7P42uAB0VheNYvqmfn:-O7P42uB2zNNxuhNEAZJ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ccb9998cb67f9e7527795392fb8f67afedca0c4/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L373)):*
> ```XML
>         let Some(valid_round) = valid_round else {
>             return;
>         };
> ```





_Suggestion:_
```XML
        let Some(valid_round) = valid_round else {
            // newly built so just streamed
            return;
        };
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 376 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/926#-O7P4AhN4cexIPjhlqIL:-O7P4AhN4cexIPjhlqIM:bc2fr0l) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ccb9998cb67f9e7527795392fb8f67afedca0c4/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L376)):*
> ```XML
>         let Some(block_hash) = block_hash else {
>             return;
>         };
> ```

This is an error, the SM should never output an empty proposal. In fact move this check above the valid round check



_Code quote:_
```XML
        let Some(block_hash) = block_hash else {
            return;
        };
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 395 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/926#-O7P57xi-VtP0yf6RqZq:-O7P57xi-VtP0yf6RqZr:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ccb9998cb67f9e7527795392fb8f67afedca0c4/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L395)):*
> ```XML
>             .propose(init, content_receiver, fin_receiver)
>             .await
>             .expect("Failed sending Proposal to Peering");
> ```





_Suggestion:_
```XML
Failed broadcasting Proposal
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/926)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 328 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/926#-O7P3llHAyYb53Rq_c4Q:-O7StumKDsC2JsCX0JVb:bjp11ak) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ccb9998cb67f9e7527795392fb8f67afedca0c4/crates/sequencing/papyrus_consensus/src/manager_test.rs#L328)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why is this test not in `single_height_consensus_test.rs`, that's where you are updating the code?
</blockquote></details>

"moved"

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/926)* status: all files reviewed, 4 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 374 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/926#-O7TBMggAIQhb561EMDv:-O7TBMggAIQhb561EMDw:b-avjqez) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf063fbade487da95d16a06249126c01cee22e00/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L374)):*
> ```XML
>             error!("StateMachine should not propose a None block_hash");
>             return;
>         };
> ```

Oh I meant this should either actually return an error or assert.



_Code quote:_
```XML
        let Some(block_hash) = block_hash else {
            error!("StateMachine should not propose a None block_hash");
            return;
        };
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 382 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/926#-O7TBWyYEFfL84wmFgIn:-O7TBWyYEFfL84wmFgIo:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf063fbade487da95d16a06249126c01cee22e00/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L382)):*
> ```XML
> #[tokio::test]
> async fn valid_proposal() {
>     let mut context = MockTestContext::new();
> ```





_Suggestion:_
```XML
#[tokio::test]
async fn repropose() {
    let mut context = MockTestContext::new();
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 391 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/926#-O7TBhzb-E9QDB9rO5Gu:-O7TBhzb-E9QDB9rO5Gv:b-3redri) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf063fbade487da95d16a06249126c01cee22e00/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L391)):*
> ```XML
>     );
> 
>     context.expect_proposer().times(2).returning(move |_, _| *PROPOSER_ID);
> ```

I don't really care how many times SHC tries to see who the leader is.



_Suggestion:_
```XML
    context.expect_proposer().returning(move |_, _| *PROPOSER_ID);
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 444 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/926#-O7TC_wEEFXCfqlUKj9D:-O7TC_wEEFXCfqlUKj9E:b4lp21b) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf063fbade487da95d16a06249126c01cee22e00/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L444)):*
> ```XML
>         let (_content_sender, content_receiver) = mpsc::channel(1);
>         content_receiver
>     });
> ```

We should check that the get_proposal is for the expected block ID



_Code quote:_
```XML
    context.expect_get_proposal().returning(move |_, _| {
        let (_content_sender, content_receiver) = mpsc::channel(1);
        content_receiver
    });
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/926)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 373 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/926#-O7YD83P2Wh2DWF6DJ03:-O7YD83Q-2PWIlCQtBaQ:bmej8i3) ([raw file](https://github.com/starkware-libs/sequencer/blob/2afc775268c3fd21812932dd8ba30e76451eb677/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L373)):*
> ```XML
>         let Some(block_hash) = block_hash else {
>             panic!("StateMachine should not propose a None block_hash");
>         };
> ```

let's just use an `expect`



_Code quote:_
```XML
        let Some(block_hash) = block_hash else {
            panic!("StateMachine should not propose a None block_hash");
        };
```

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/926)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
