### PR TITLE
chore(cairo_native): add native to stack trace test

### PR DESCRIPTION
**Pull request by meship-starkware**

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2633)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 404 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2633#-ODkov24CIRU2IaPABCb:-ODkov24CIRU2IaPABCc:bv7efjg) ([raw file](https://github.com/starkware-libs/sequencer/blob/a305ccaa1fad2a1b76b7277cb7881f0f8316e199/crates/blockifier/src/test_utils/contracts.rs#L404)):*
> ```XML
>                     panic!("Not implemented for cairo native contracts")
>                 }
>             }
> ```

This is waiting for LC to add the entry_point_by_type to the AotContractExacutor.



_Code quote:_
```XML
            RunnableCompiledClass::V1Native(_) => {
                #[cfg(test)]
                {
                    EntryPointOffset(10000)
                }
                #[cfg(not(test))]
                {
                    panic!("Not implemented for cairo native contracts")
                }
            }
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2633)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 404 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2633#-ODkov24CIRU2IaPABCb:-OE8AqLX2rhvzYJ7Wkf2:b7qsa1d) ([raw file](https://github.com/starkware-libs/sequencer/blob/a305ccaa1fad2a1b76b7277cb7881f0f8316e199/crates/blockifier/src/test_utils/contracts.rs#L404)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider using the casm field
</blockquote></details>

Do we still need the entry_point_by_type for the V1Native class, or can we assume that the casm would be enough?

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2633)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 344 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2633#-OEFExyvDbKHZKf7z3rV:-OEFExyw7NoaFLv0BG11:b-wx94m3) ([raw file](https://github.com/starkware-libs/sequencer/blob/b703dee9c67080ee9dd28b8e427e84d0906cb3ab/crates/blockifier/src/execution/native/syscall_handler.rs#L344)):*
> ```XML
>             .map_err(|error| self.handle_error(remaining_gas, error.into()))?;
> 
>         let class_hash = self.base.get_class_hash_at(contract_address).unwrap_or_default();
> ```

This shouldn't be unwrap_or_default. Should this be expect if we can't get the  class_hash error?
At the VM, we return the error in the function. I can add handle error flow here. 



_Code quote:_
```XML
    let class_hash = self.base.get_class_hash_at(contract_address).unwrap_or_default();
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2633)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 348 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2633#-OEFOJYM4549IZHdoXXh:-OEFOJYM4549IZHdoXXi:b-kzz6e9) ([raw file](https://github.com/starkware-libs/sequencer/blob/f6869ad3aa5a96563e59341a9175c7b7cac3daca/crates/blockifier/src/execution/native/syscall_handler.rs#L348)):*
> ```XML
>             .base
>             .get_class_hash_at(contract_address)
>             .map_err(|e| self.handle_error(remaining_gas, e))?;
> ```

It's the same as the VM, but I am not entirely sure why it should be like this. 



_Code quote:_
```XML
        let class_hash = self
            .base
            .get_class_hash_at(contract_address)
            .map_err(|e| self.handle_error(remaining_gas, e))?;
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2633)* status: all files reviewed, 6 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 348 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2633#-OEFOJYM4549IZHdoXXh:-OEU0c_t3tCbCFnBMoCS:b-7zi8tj) ([raw file](https://github.com/starkware-libs/sequencer/blob/f6869ad3aa5a96563e59341a9175c7b7cac3daca/crates/blockifier/src/execution/native/syscall_handler.rs#L348)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

It's the same as the VM, but I am not entirely sure why it should be like this.
</blockquote></details>

WDYM?
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 404 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2633#-ODkov24CIRU2IaPABCb:-OEf8h2E4X1Zb-P01H7o:b-339w2k) ([raw file](https://github.com/starkware-libs/sequencer/blob/a305ccaa1fad2a1b76b7277cb7881f0f8316e199/crates/blockifier/src/test_utils/contracts.rs#L404)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Do we still need the entry_point_by_type for the V1Native class, or can we assume that the casm would be enough?
</blockquote></details>

Wait- why is it needed? You don't need the pc in the native expected case, no? Please revert.
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 321 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2633#-OEfFIHB3iB19MprYNEh:-OEfFIHC2YzNPjpbC0AQ:b2nhkyh) ([raw file](https://github.com/starkware-libs/sequencer/blob/f6869ad3aa5a96563e59341a9175c7b7cac3daca/crates/blockifier/src/execution/native/syscall_handler.rs#L321)):*
> ```XML
>                     match e {
>                         SyscallExecutionError::SyscallError { .. } => e,
>                         _ => e.as_call_contract_execution_error(
> ```

No?



_Suggestion:_
```XML
                        _ => e.as_lib_call_execution_error(
```
___
*[`crates/blockifier/src/execution/stack_trace.rs` line 715 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2633#-OEf4KljCCN2840xtozs:-OEf4KljCCN2840xtozt:b-la5y2o) ([raw file](https://github.com/starkware-libs/sequencer/blob/f6869ad3aa5a96563e59341a9175c7b7cac3daca/crates/blockifier/src/execution/stack_trace.rs#L715)):*
> ```XML
>         EntryPointExecutionError::NativeUnrecoverableError(error) => {
>             extract_syscall_execution_error_into_stack_trace(error_stack, depth, error)
>         }
> ```

Nice!
In the VM, we needed to extract it from ` CairoRunError::VmException(VirtualMachineError::Hint(Box(HintError::Internal(VirtualMachineError::Other(error.into()))))`.



_Code quote:_
```XML
        #[cfg(feature = "cairo_native")]
        EntryPointExecutionError::NativeUnrecoverableError(error) => {
            extract_syscall_execution_error_into_stack_trace(error_stack, depth, error)
        }
```
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 648 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2633#-OEfBD8T7FzVnOSiUKig:-OEfBD8T7FzVnOSiUKih:b-35iw4v) ([raw file](https://github.com/starkware-libs/sequencer/blob/f6869ad3aa5a96563e59341a9175c7b7cac3daca/crates/blockifier/src/execution/stack_trace_test.rs#L648)):*
> ```XML
>         CairoVersion::Cairo1(RunnableCairo1::Casm),
>         CairoVersion::Cairo1(RunnableCairo1::Native)
>     )]
> ```

Consider defining a `const CAIRO_VERSIONS` with two different values (condition on the cairo native feature flag), to avoid code duplication. 



_Code quote:_
```XML
    #[values(
        CairoVersion::Cairo0,
        CairoVersion::Cairo1(RunnableCairo1::Casm),
        CairoVersion::Cairo1(RunnableCairo1::Native)
    )]
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2633#-OEU18qm3c7tVm2EuwXs:-OEU18qm3c7tVm2EuwXt:b64opyp) ([raw file](https://github.com/starkware-libs/sequencer/blob/8fbf8027356f22f368dc01b5f516b386d9b32af2/crates/blockifier/src/execution/native/syscall_handler.rs#L58)):*
> ```XML
>     }
> 
>     fn execute_inner_call(
> ```

I think that using this function makes the code more readable. Can you leave it with the needed modification? (non-blocking)



_Code quote:_
```XML
fn execute_inner_call(
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2633)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 648 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2633#-OEfBD8T7FzVnOSiUKig:-OEhj_r50eCC4RoG4CB7:b-411ail) ([raw file](https://github.com/starkware-libs/sequencer/blob/f6869ad3aa5a96563e59341a9175c7b7cac3daca/crates/blockifier/src/execution/stack_trace_test.rs#L648)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider defining a `const CAIRO_VERSIONS` with two different values (condition on the cairo native feature flag), to avoid code duplication.
</blockquote></details>

It does not work. Lets stay with this for now. 
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 321 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2633#-OEfFIHB3iB19MprYNEh:-OEhP8ih-E3mc-SkZAA6:b-rpqap4) ([raw file](https://github.com/starkware-libs/sequencer/blob/f6869ad3aa5a96563e59341a9175c7b7cac3daca/crates/blockifier/src/execution/native/syscall_handler.rs#L321)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

No?
</blockquote></details>

You are right 
Done.
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 348 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2633#-OEFOJYM4549IZHdoXXh:-OEhr5gd-psDssdBiRpa:b-pywgvv) ([raw file](https://github.com/starkware-libs/sequencer/blob/f6869ad3aa5a96563e59341a9175c7b7cac3daca/crates/blockifier/src/execution/native/syscall_handler.rs#L348)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

I though we might want to wrap it as well but it is not an inner call error so I think its ok.
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 404 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2633#-ODkov24CIRU2IaPABCb:-OEhqgOn4XABv9lqkUB_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a305ccaa1fad2a1b76b7277cb7881f0f8316e199/crates/blockifier/src/test_utils/contracts.rs#L404)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Wait- why is it needed? You don't need the pc in the native expected case, no? Please revert.
</blockquote></details>

Done.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2633)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 250 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2633#-OEiD6KN3e87qtnE87GR:-OEiD6KN3e87qtnE87GS:b483wyg) ([raw file](https://github.com/starkware-libs/sequencer/blob/803c6742abdf950d5618d8e6cb7f80b6a2921b65/crates/blockifier/src/execution/stack_trace_test.rs#L250)):*
> ```XML
> "
>         )
>         .to_string(),
> ```

Why is it needed now?



_Code quote:_
```XML
        .to_string(),
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 127 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2633#-OEiDX6v02xcKSFp3Dw2:-OEiDX6w3QPhdvZYl9at:b-7zi8ni) ([raw file](https://github.com/starkware-libs/sequencer/blob/803c6742abdf950d5618d8e6cb7f80b6a2921b65/crates/blockifier/src/execution/native/syscall_handler.rs#L127)):*
> ```XML
>         remaining_gas: &mut u64,
>         class_hash: ClassHash,
>     ) -> SyscallResult<Retdata> {
> ```

WDYT?



_Suggestion:_
```XML
    fn execute_inner_call(
        &mut self,
        entry_point: CallEntryPoint,
        remaining_gas: &mut u64,
        class_hash: ClassHash,
        format_error: F
    ) -> SyscallResult<Retdata> 
    where
    F: FnOnce(SyscallExecutionError, ClassHash, ContractAddress, EntryPointSelector) -> SyscallExecutionError,
{
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2633)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 250 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2633#-OEiD6KN3e87qtnE87GR:-OExqjF_CKnY8SOd1YhM:bvue451) ([raw file](https://github.com/starkware-libs/sequencer/blob/803c6742abdf950d5618d8e6cb7f80b6a2921b65/crates/blockifier/src/execution/stack_trace_test.rs#L250)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it needed now?
</blockquote></details>

I think its becuse we return this now and not saving this as an argument

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2633#-:-OEyCYo6-fXL2cDhxNKo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
