### PR TITLE
feat(blockifier): add `get_execution_info_v2` syscall

### PR DESCRIPTION
**Pull request by varex83**

### CODE REVIEW

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1812)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @varex83)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1812#-OAv4-lh2Bx69Tskw5GN:-OAv4-liEzCdJmRfLS0W:be0ihrr) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9e5adeb6e5e5190c57d276f7e0b72efceffe0e4/crates/blockifier/src/execution/native/syscall_handler.rs#L203)):*
> ```XML
>                 paymaster_data: context.paymaster_data.0.clone(),
>                 nonce_data_availability_mode: context.nonce_data_availability_mode as u32,
>                 fee_data_availability_mode: context.fee_data_availability_mode as u32,
> ```

Please use into or try_ino and not as 



_Suggestion:_
```XML
                nonce_data_availability_mode: context.nonce_data_availability_mode.into(),
                fee_data_availability_mode: context.fee_data_availability_mode.into(),
```

**Review by varex83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1812)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1812#-OAv4-lh2Bx69Tskw5GN:-OAw-3lu3r11rfAxoGAH:bodnkkf) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9e5adeb6e5e5190c57d276f7e0b72efceffe0e4/crates/blockifier/src/execution/native/syscall_handler.rs#L203)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Please use into or try_ino and not as
</blockquote></details>

`TryInto` is not implemented in this case for the enum, but corresponding integers are defined in the enum itself, so converting with `as` is a pretty idiomatic way to do

**Review by varex83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1812)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1812#-OAv4-lh2Bx69Tskw5GN:-OAw2Ge83i82Re4OAgvd:b4lnjof) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9e5adeb6e5e5190c57d276f7e0b72efceffe0e4/crates/blockifier/src/execution/native/syscall_handler.rs#L203)):*
<details><summary><i>Previously, varex83 (Bohdan Ohorodnii) wrote…</i></summary><blockquote>

`TryInto` is not implemented in this case for the enum, but corresponding integers are defined in the enum itself, so converting with `as` is a pretty idiomatic way to do
</blockquote></details>

Oh, just noticed that clippy failed (I was checking it a few times, but only now it appeared). I will push fix ASAP

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1812)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @varex83)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1812#-OB4X5uf6K5sP01DV-l4:-OB4X5uf6K5sP01DV-l5:b-hnitap) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9e5adeb6e5e5190c57d276f7e0b72efceffe0e4/crates/blockifier/src/execution/native/syscall_handler.rs#L20)):*
> ```XML
> use starknet_types_core::felt::Felt;
> 
> use super::utils::{calculate_resource_bounds, default_tx_v2_info};
> ```

Avoid using super



_Code quote:_
```XML
use super::utils::{calculate_resource_bounds, default_tx_v2_info};
```

**Review by varex83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1812)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1812#-OB4X5uf6K5sP01DV-l4:-OB5Jd1w-dqWWe-5P3BL:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9e5adeb6e5e5190c57d276f7e0b72efceffe0e4/crates/blockifier/src/execution/native/syscall_handler.rs#L20)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Avoid using super
</blockquote></details>

Done

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1812)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1812)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1812)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1812)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1812)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1812)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1812)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1812)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 2 of 4 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1812#-:-OBa4_wFCDv06AvKhd5s:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1812)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @meship-starkware, @noaov1, and @varex83)

___
*[`crates/blockifier/src/execution/native/utils.rs` line 72 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/1812#-OBf4l3H0_MSV75UBRGp:-OBf4l3H0_MSV75UBRGq:bn6hoa5) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd49a8be5dfc9c1c89455a04397db70b27af05b4/crates/blockifier/src/execution/native/utils.rs#L72)):*
> ```XML
>                 },
>                 ResourceBounds {
>                     resource: Felt::from_hex(Resource::L1DataGas.to_hex()).unwrap(),
> ```

I think this is the wrong order. Please check against the vm impl

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 4 files at r6, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1812#-:-OBf6bmEBxaKH7DPY69E:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1812)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1812)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
