### PR TITLE
feat(execution): add l2_gas_price to FeeEstimation

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/644)

### CODE REVIEW

**Comment by TzahiTaub** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/644?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#644** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/644?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#643** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/643?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#641** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/641?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @TzahiTaub and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/644)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama and @TzahiTaub)

___
*[`crates/papyrus_execution/src/testing_instances.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/644#-O5hnBKZ0JX5AqqaRIdd:-O5hnBKZ0JX5AqqaRIde:b-2wusmo) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a4cab681c4017c8744578ff6ac3d146adf7b46d/crates/papyrus_execution/src/testing_instances.rs#L69)):*
> ```XML
>     pub struct FeeEstimation {
>         pub gas_consumed: Felt,
>         pub gas_price: GasPrice,
> ```

can this be renamed to l1_gas_price...? confusing as it is now
or is this some object that needs to be BC?



_Code quote:_
```XML
pub gas_price: GasPrice,
```
___
*[`crates/papyrus_rpc/src/v0_7/execution_test.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/644#-O5hnLpn6yqN5EUvnKpZ:-O5hnLpn6yqN5EUvnKp_:bo4gj99) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a4cab681c4017c8744578ff6ac3d146adf7b46d/crates/papyrus_rpc/src/v0_7/execution_test.rs#L163)):*
> ```XML
>         price_in_wei: GasPrice(1),
>         price_in_fri: GasPrice(0),
>     };
> ```

the first two prices are "sane" (pretty close to actual prices), should L2_GAS_PRICE be the same? @ShahakShama 



_Code quote:_
```XML
    pub static ref GAS_PRICE: GasPricePerToken = GasPricePerToken{
        price_in_wei: GasPrice(100 * u128::pow(10, 9)),
        price_in_fri: GasPrice(0),
    };
    pub static ref DATA_GAS_PRICE: GasPricePerToken = GasPricePerToken{
        price_in_wei: GasPrice(1),
        price_in_fri: GasPrice(0),
    };
    pub static ref L2_GAS_PRICE: GasPricePerToken = GasPricePerToken{
        price_in_wei: GasPrice(1),
        price_in_fri: GasPrice(0),
    };
```

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/644)* status: all files reviewed, 4 unresolved discussions (waiting on @ArielElp, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/papyrus_execution/src/objects.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/644#-O5qa8mt1eB-oGaIAfDM:-O5qa8mt1eB-oGaIAfDN:b-z2bm4n) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a4cab681c4017c8744578ff6ac3d146adf7b46d/crates/papyrus_execution/src/objects.rs#L100)):*
> ```XML
>     /// The gas price for DA blob.
>     pub data_gas_price: GasPrice,
>     // TODO(Tzahi): Add l2_gas_consumed + verify estimation is close enough to l1 gas fee if user
> ```

This TODO is very unclear. Try to rephrase it. The + is the confusing part IMO
___
*[`crates/papyrus_execution/src/objects.rs` line 160 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/644#-O5qaEn611P1Tl7yXt4s:-O5qaEn611P1Tl7yXt4t:b9r2uwr) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a4cab681c4017c8744578ff6ac3d146adf7b46d/crates/papyrus_execution/src/objects.rs#L160)):*
> ```XML
> ) -> ExecutionResult<FeeEstimation> {
>     let gas_prices = &block_context.block_info().gas_prices;
>     let (gas_price, data_gas_price, l2_gas_price) = (
> ```

As Dori said, change gas_price to l1_gas_price (and if it's nahoog to write l1_data_gas instead of data_gas write l1_data_gas_price as well)
___
*[`crates/papyrus_execution/src/testing_instances.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/644#-O5hnBKZ0JX5AqqaRIdd:-O5qa2nq4XGIGU6M_s_Z:bbmej5i) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a4cab681c4017c8744578ff6ac3d146adf7b46d/crates/papyrus_execution/src/testing_instances.rs#L69)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can this be renamed to l1_gas_price...? confusing as it is now
or is this some object that needs to be BC?
</blockquote></details>

Dan recently said that in the RPC we support only the latest version, so no need for BC
We should verify with @ArielElp what are the names of fields of FeeEstimation in rpc v0.8
___
*[`crates/papyrus_rpc/src/v0_7/execution_test.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/644#-O5hnLpn6yqN5EUvnKpZ:-O5qcMeTC5VobQioykRz:bpe0c7w) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a4cab681c4017c8744578ff6ac3d146adf7b46d/crates/papyrus_rpc/src/v0_7/execution_test.rs#L163)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the first two prices are "sane" (pretty close to actual prices), should L2_GAS_PRICE be the same? @ShahakShama
</blockquote></details>

the DATA_GAS_PRICE isn't tested yet, that's why we put 1. For now, you can keep the l2 gas price as you did. Just add a TODO to add tests for data gas and l2 gas

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/644)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @ArielElp, @dorimedini-starkware, and @ShahakShama)

___
*[`crates/papyrus_execution/src/objects.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/644#-O5qa8mt1eB-oGaIAfDM:-O60OSCZDRYlhChO2Dtu:b-vx3ao5) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a4cab681c4017c8744578ff6ac3d146adf7b46d/crates/papyrus_execution/src/objects.rs#L100)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This TODO is very unclear. Try to rephrase it. The + is the confusing part IMO
</blockquote></details>

I think I meant (:) ) - we have an automatic translation of l1_gas_price to  l2_gas_price in the version constants (`l1\_to\_l2\_gas\_price\_conversion`). I think we would like to verify that running txs with l1_gas_price only, and running them using l1_gas_price and the l2_gas_price as computed automatically, will give close `overall_fee` results (otherwise, we have some inconsistency).  "close" and not exact equality as we use rounding.
Makes sense?

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/644)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @ArielElp, @dorimedini-starkware, and @ShahakShama)

___
*[`crates/papyrus_execution/src/testing_instances.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/644#-O5hnBKZ0JX5AqqaRIdd:-O60Q83WDrIK-3rZl34B:b-cd417e) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a4cab681c4017c8744578ff6ac3d146adf7b46d/crates/papyrus_execution/src/testing_instances.rs#L69)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Dan recently said that in the RPC we support only the latest version, so no need for BC
We should verify with @ArielElp what are the names of fields of FeeEstimation in rpc v0.8
</blockquote></details>

Is `rpc` considered the only user interface with theoretically BC issues, and in any other crate we can do whatever we want?

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/644)* status: all files reviewed, 4 unresolved discussions (waiting on @ArielElp, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/papyrus_execution/src/objects.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/644#-O5qa8mt1eB-oGaIAfDM:-O6_PfgJ8syAYHafMzLE:bc7nsyq) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a4cab681c4017c8744578ff6ac3d146adf7b46d/crates/papyrus_execution/src/objects.rs#L100)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I think I meant (:) ) - we have an automatic translation of l1_gas_price to  l2_gas_price in the version constants (`l1\_to\_l2\_gas\_price\_conversion`). I think we would like to verify that running txs with l1_gas_price only, and running them using l1_gas_price and the l2_gas_price as computed automatically, will give close `overall_fee` results (otherwise, we have some inconsistency).  "close" and not exact equality as we use rounding.
Makes sense?
</blockquote></details>

Yes. Now write it inside the comment
___
*[`crates/papyrus_execution/src/objects.rs` line 160 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/644#-O5qaEn611P1Tl7yXt4s:-O6_QEvy2-kRAzGknkkJ:b-pb71bd) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a4cab681c4017c8744578ff6ac3d146adf7b46d/crates/papyrus_execution/src/objects.rs#L160)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

As Dori said, change gas_price to l1_gas_price (and if it's nahoog to write l1_data_gas instead of data_gas write l1_data_gas_price as well)
</blockquote></details>

Checking with @ArielElp on slack if it's l1_data_gas or data_gas
___
*[`crates/papyrus_execution/src/testing_instances.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/644#-O5hnBKZ0JX5AqqaRIdd:-O6_PsAT612pYiVW5Hq7:b-qmiogd) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a4cab681c4017c8744578ff6ac3d146adf7b46d/crates/papyrus_execution/src/testing_instances.rs#L69)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

And I see this truct (FeeEstimation) is returned in rpc calls - we would like to keep the same names for v7 and v6 if possible AFAIU, I think we don't want to runover those names for existing API. (I mean, making v7 return `l1_gas_price` is not exactly BC issue, its making the V7 route in our rpc server diverge from the V7 spec).
</blockquote></details>

We only need to support the latest version. Change the jsonschema file to have l1_gas_price instead of gas_price and I'm checking with Ariel whether data_gas needs renaming or not

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/644)* status: all files reviewed, 4 unresolved discussions (waiting on @ArielElp and @TzahiTaub)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 18 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/644)* status: 4 of 19 files reviewed, 4 unresolved discussions (waiting on @ArielElp, @ShahakShama, and @TzahiTaub)

___
*[`bin/protoc` line 0 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/644#-O7NtqhxBy83jcnaYWCu:-O7NtqhxBy83jcnaYWCv:b-ctajjx) ([raw file](https://github.com/starkware-libs/sequencer/blob/cd41b84feb8c426f66685f44170d4e0bd6f6aa41/bin/protoc#L0)):*
should this file be tracked by git...?
where does it come from?
@ShahakShama maybe related to AlonL's changes?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 18 files at r3, 14 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/644)* status: all files reviewed, 4 unresolved discussions (waiting on @ArielElp, @TzahiTaub, and @yoavGrs)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/644)* status: 18 of 19 files reviewed, 4 unresolved discussions (waiting on @ArielElp, @dorimedini-starkware, @ShahakShama, and @TzahiTaub)

___
*[`bin/protoc` line  at r5](https://reviewable.io/reviews/starkware-libs/sequencer/644#-O7NtqhxBy83jcnaYWCu:-O7OBk6B6YcTGyrxPKj8:bwvyox4) ([raw file](https://github.com/starkware-libs/sequencer/blob/3d7c1a0387a2e45ae924e2d96ddd2f2028ad4543/bin/protoc#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

should this file be tracked by git...?
where does it come from?
@ShahakShama maybe related to AlonL's changes?
</blockquote></details>

Reverted

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/644)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp and @TzahiTaub)

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/644)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

___
*[`crates/papyrus_execution/src/testing_instances.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/644#-O5hnBKZ0JX5AqqaRIdd:-O7ZQIK39qD6YvRUN832:b-gp70su) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a4cab681c4017c8744578ff6ac3d146adf7b46d/crates/papyrus_execution/src/testing_instances.rs#L69)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

We only need to support the latest version. Change the jsonschema file to have l1_gas_price instead of gas_price and I'm checking with Ariel whether data_gas needs renaming or not
</blockquote></details>

Change gas_price to l1_gas_price and data_gas_price to l1_data_gas_price

**Review by ShahakShama — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/644)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/644)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

___
*[`crates/papyrus_execution/src/testing_instances.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/644#-O5hnBKZ0JX5AqqaRIdd:-O7ZWGbUEYMeZ27xlxMg:b-o9cdre) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a4cab681c4017c8744578ff6ac3d146adf7b46d/crates/papyrus_execution/src/testing_instances.rs#L69)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change gas_price to l1_gas_price and data_gas_price to l1_data_gas_price
</blockquote></details>

I'm opening a new PR for this

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/644#-:-O7h-rcVAeEBxFrI8VwK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/644)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/644)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

___
*[`crates/papyrus_execution/src/testing_instances.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/644#-O5hnBKZ0JX5AqqaRIdd:-O7hLQJp2Bq8tVjnt1Mm:bwbzinf) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a4cab681c4017c8744578ff6ac3d146adf7b46d/crates/papyrus_execution/src/testing_instances.rs#L69)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

I'm opening a new PR for this
</blockquote></details>

@yoavGrs can you link to it when it's open?

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/644)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

___
*[`crates/papyrus_execution/src/testing_instances.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/644#-O5hnBKZ0JX5AqqaRIdd:-O7wXQkp56qSVwF4TjP2:b-mewenb) ([raw file](https://github.com/starkware-libs/sequencer/blob/9a4cab681c4017c8744578ff6ac3d146adf7b46d/crates/papyrus_execution/src/testing_instances.rs#L69)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@yoavGrs can you link to it when it's open?
</blockquote></details>

https://reviewable.io/reviews/starkware-libs/sequencer/1007

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/644#-:-O7weGAQ58fC0bLjG5SR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
