### PR TITLE
chore(mempool_p2p_types): unify client implementations

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #2119
- #2115
- #2090
- #2089 ⬅
- #2088
- #2087
- #2086
- #2085

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by nadin-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2089)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_mempool_p2p_types/src/communication.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2089#-OBuHVldCHzUQmCdsdGb:-OBuHVle4oQ1Q8QM2moB:b-wadyng) ([raw file](https://github.com/starkware-libs/sequencer/blob/d674f5c72061fbc669225b01203349cac40c1187/crates/starknet_mempool_p2p_types/src/communication.rs#L69)):*
> ```XML
> 
> #[async_trait]
> impl<T> MempoolP2pPropagatorClient for T
> ```

Please replace T with a more descriptive name.



_Code quote:_
```XML
T
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2089)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/starknet_mempool_p2p_types/src/communication.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2089#-OBuHVldCHzUQmCdsdGb:-OBuSzRs4HF2y-IAvClV:b-d3xf9y) ([raw file](https://github.com/starkware-libs/sequencer/blob/f93fe0472089edfb4efea1674043bb4d54040458/crates/starknet_mempool_p2p_types/src/communication.rs#L69)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Please replace T with a more descriptive name.
</blockquote></details>

Single pr at the end

**Review by nadin-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2089)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2089)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#2119](https://github.com/starkware-libs/sequencer/pull/2119)

**Pull request closed without merging**
