### PR TITLE
fix(mempool): mempool will not propagate declare transactions

### PR DESCRIPTION
**Pull request by AlonLStarkWare**
- refactor(mempool): add mempool p2p sender client to mempool wrapper
- fix(mempool): mempool will not propagate declare transactions

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/932)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/932)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare)

___
*[`crates/mempool/src/communication.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/932#-O86E91d7s7_Ie10caJr:-O86E91d7s7_Ie10caJs:bk65u9a) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa531f6b93941604205d4d2294a0918f5df04fda/crates/mempool/src/communication.rs#L65)):*
> ```XML
>     async fn add_tx(&mut self, mempool_wrapper_input: MempoolWrapperInput) -> MempoolResult<()> {
>         let result = self.mempool.add_tx(mempool_wrapper_input.mempool_input.clone());
>         match mempool_wrapper_input.mempool_input.tx {
> ```

Add TODO to handle declare correctly and remove this match

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/932)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/mempool/src/communication.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/932#-O86E91d7s7_Ie10caJr:-O94SbFOCuCCz_-R1i4M:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa531f6b93941604205d4d2294a0918f5df04fda/crates/mempool/src/communication.rs#L65)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to handle declare correctly and remove this match
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 7 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/932#-:-O94rxXP0p0maR0dF77T:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/932#-:-OACHAhSCYueoFMvq1eZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Pull request merged**
