### PR TITLE
refactor(blockifier):  refactor transaction fee error

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/670)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
* **#670** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/670?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/670)* status: all files reviewed, 12 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 281 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hgMW8CAktHbr9cLrv:-O5hgMW8CAktHbr9cLrw:b2rkma2) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/account_transaction.rs#L281)):*
> ```XML
>                         min_fee,
>                         max_fee,
>                     })?;
> ```

no, this is a *deprecated* tx, i.e. V2 tx or below.
these txs don't have resource bounds, only a `max_fee` field.
no `Resource` field required in this error



_Code quote:_
```XML
                    return Err(TransactionFeeError::MaxFeeTooLow {
                        resource: Resource::L1Gas,
                        min_fee,
                        max_fee,
                    })?;
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hgXq14lCDtVV2DYgG:-O5hgXq14lCDtVV2DYgH:b64r3oa) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/errors.rs#L25)):*
> ```XML
>     FeeTransferError { max_fee: Fee, actual_fee: Fee },
>     #[error("Actual fee ({}) exceeded paid fee on L1 ({}).", actual_fee.0, paid_fee.0)]
>     InsufficientFee { resource: Resource, paid_fee: Fee, actual_fee: Fee },
> ```

where is this error used...? I get the feeling it shouldn't have a `resource` field



_Code quote:_
```XML
InsufficientFee { resource: Resource, paid_fee: Fee, actual_fee: Fee },
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hgfOGAgiVlc-AiOGj:-O5hgfOGAgiVlc-AiOGk:bbcwabu) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/errors.rs#L37)):*
> ```XML
>     },
>     #[error("{resource} GasBounds: Max fee ({}) exceeds balance ({balance}).", max_fee.0, )]
>     MaxFeeExceedsBalance { resource: Resource, max_fee: Fee, balance: BigUint },
> ```

revert (see above)



_Code quote:_
```XML
    #[error("{resource} GasBounds: Max fee ({}) exceeds balance ({balance}).", max_fee.0, )]
    MaxFeeExceedsBalance { resource: Resource, max_fee: Fee, balance: BigUint },
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hghb7EhImtd-nBViy:-O5hghb7EhImtd-nBViz:bkl2mbz) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/errors.rs#L39)):*
> ```XML
>     MaxFeeExceedsBalance { resource: Resource, max_fee: Fee, balance: BigUint },
>     #[error("Max fee ({}) is too low. Minimum fee: {}.", max_fee.0, min_fee.0)]
>     MaxFeeTooLow { resource: Resource, min_fee: Fee, max_fee: Fee },
> ```

revert (should only be relevant for pre-V3 txs without resource bounds)



_Code quote:_
```XML
    #[error("Max fee ({}) is too low. Minimum fee: {}.", max_fee.0, min_fee.0)]
    MaxFeeTooLow { resource: Resource, min_fee: Fee, max_fee: Fee },
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 260 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hgwpn9B45_kFB1vXB:-O5hgwpn9B45_kFB1vXC:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/execution_flavors_test.rs#L260)):*
> ```XML
>                         TransactionFeeError::MaxGasAmountTooLow { .. }
>                     )
>                 )
> ```





_Suggestion:_
```XML
                TransactionExecutionError::TransactionPreValidationError(
                    TransactionPreValidationError::TransactionFeeError(
                        TransactionFeeError::MaxGasAmountTooLow { resource, .. }
                    )
                )
                if resource == Resource::L1Gas
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 304 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hh2mV2n_aUP7tAxo0:-O5hh2mV2n_aUP7tAxo1:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/execution_flavors_test.rs#L304)):*
> ```XML
>                         TransactionFeeError::GasBoundsExceedBalance { .. }
>                     )
>                 )
> ```





_Suggestion:_
```XML
                TransactionExecutionError::TransactionPreValidationError(
                    TransactionPreValidationError::TransactionFeeError(
                        TransactionFeeError::GasBoundsExceedBalance { resource, .. }
                    )
                )
                if resource == Resource::L1Gas
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 334 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hh5ICD0qNFxFW6dI4:-O5hh5ICD0qNFxFW6dI5:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/execution_flavors_test.rs#L334)):*
> ```XML
>                         TransactionFeeError::MaxGasPriceTooLow { .. }
>                     )
>                 )
> ```





_Suggestion:_
```XML
                TransactionExecutionError::TransactionPreValidationError(
                    TransactionPreValidationError::TransactionFeeError(
                        TransactionFeeError::MaxGasPriceTooLow { resource, .. }
                    )
                )
                if resource == Resource::L1Gas
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 813 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hhEIzCievzHcBPas-:-O5hhEIzCievzHcBPas0:b75tnlp) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/transactions_test.rs#L813)):*
> ```XML
>                     TransactionPreValidationError::TransactionFeeError(
>                         TransactionFeeError::GasBoundsExceedBalance{resource: Resource::L1Gas, max_amount, max_price, .. }))
>                 if max_amount == l1_bounds.max_amount && max_price == l1_bounds.max_price_per_unit
> ```

I think this is the correct `assert_matches!` syntax, no?



_Suggestion:_
```XML
                        TransactionFeeError::GasBoundsExceedBalance{resource, max_amount, max_price, .. }))
                if resource == Resource:: L1Gas && max_amount == l1_bounds.max_amount && max_price == l1_bounds.max_price_per_unit
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 928 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hhKqa2j8g1Z96DCxw:-O5hhKqa2j8g1Z96DCxx:b-7ropln) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/transactions_test.rs#L928)):*
> ```XML
>             TransactionPreValidationError::TransactionFeeError(
>                 TransactionFeeError::MaxFeeTooLow { resource: Resource::L1Gas, min_fee, max_fee }))
>         if max_fee == invalid_max_fee && min_fee == minimal_fee
> ```

ditto



_Code quote:_
```XML
                TransactionFeeError::MaxFeeTooLow { resource: Resource::L1Gas, min_fee, max_fee }))
        if max_fee == invalid_max_fee && min_fee == minimal_fee
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 953 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hhOSdDPgpqaTMKRN7:-O5hhOSdDPgpqaTMKRN8:b-tlnm62) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/transactions_test.rs#L953)):*
> ```XML
>                     resource: Resource::L1Gas,
>                     max_gas_amount: max_l1_gas_amount,
>                     minimal_gas_amount: minimal_l1_gas_amount }))
> ```

1. ditto on above
2. no need to rename amount and price fields, it is clear by the `if` statement below what you are comparing to



_Code quote:_
```XML
                    resource: Resource::L1Gas,
                    max_gas_amount: max_l1_gas_amount,
                    minimal_gas_amount: minimal_l1_gas_amount }))
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 974 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hhXIS539qPuZDinjT:-O5hhXIU-j_ZegqqfppQ:b-gv3v6k) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/transactions_test.rs#L974)):*
> ```XML
>                     resource: Resource::L1Gas,
>                     max_gas_price: max_l1_gas_price,
>                     actual_gas_price: actual_l1_gas_price }))
> ```

1. ditto
2. ditto



_Code quote:_
```XML
                    resource: Resource::L1Gas,
                    max_gas_price: max_l1_gas_price,
                    actual_gas_price: actual_l1_gas_price }))
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1970 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hhZ_pBXrayE744K0L:-O5hhZ_pBXrayE744K0M:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/transactions_test.rs#L1970)):*
> ```XML
>         TransactionExecutionError::TransactionFeeError(
>             TransactionFeeError::InsufficientFee {resource: Resource::L1Gas, paid_fee, actual_fee, })
>             if paid_fee == Fee(0) && actual_fee == expected_actual_fee
> ```





_Suggestion:_
```XML
            TransactionFeeError::InsufficientFee {resource, paid_fee, actual_fee, })
            if resource == Resource::L1Gas && paid_fee == Fee(0) && actual_fee == expected_actual_fee
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/670)* status: 1 of 8 files reviewed, 12 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 281 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hgMW8CAktHbr9cLrv:-O5mE6lc3gj2yqY66xvs:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/account_transaction.rs#L281)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no, this is a *deprecated* tx, i.e. V2 tx or below.
these txs don't have resource bounds, only a `max_fee` field.
no `Resource` field required in this error
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/errors.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hgXq14lCDtVV2DYgG:-O5luNzC3LBvXuSxHVzn:bvo1u1x) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/errors.rs#L25)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where is this error used...? I get the feeling it shouldn't have a `resource` field
</blockquote></details>

Yes, I think that it is used only for deprecated tx.
Reverted.
___
*[`crates/blockifier/src/transaction/errors.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hgfOGAgiVlc-AiOGj:-O5lsXXm8MfYsVfnEjNY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/errors.rs#L37)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

revert (see above)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/errors.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hghb7EhImtd-nBViy:-O5lse2p6gN_BO4aU_D9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/errors.rs#L39)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

revert (should only be relevant for pre-V3 txs without resource bounds)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 260 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hgwpn9B45_kFB1vXB:-O5lwm-G2OUIywdHV5c2:bu7c8x) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/execution_flavors_test.rs#L260)):*
> ```XML
>                         TransactionFeeError::MaxGasAmountTooLow { .. }
>                     )
>                 )
> ```

Nice syntax
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 304 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hh2mV2n_aUP7tAxo0:-O5lx7OZ4_WLxrA5F0OL:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/execution_flavors_test.rs#L304)):*
> ```XML
>                         TransactionFeeError::GasBoundsExceedBalance { .. }
>                     )
>                 )
> ```

Done.
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 334 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hh5ICD0qNFxFW6dI4:-O5lxRblEAfb7LmDsmF9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/execution_flavors_test.rs#L334)):*
> ```XML
>                         TransactionFeeError::MaxGasPriceTooLow { .. }
>                     )
>                 )
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 813 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hhEIzCievzHcBPas-:-O5lzTH90Z2x3ca8Es88:b-ekd2on) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/transactions_test.rs#L813)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think this is the correct `assert_matches!` syntax, no?
</blockquote></details>

I think it is the same since your code matches the expression returned  from
```
invalid_tx.execute(state, block_context, true, true).unwrap_err()
```
to the error (with any resource),
and then checked that 
```resource == Resource::L1Gas```

and in my code, the match itself doesn't succeed if the resource is not  
``` Resource::L1Gas```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 928 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hhKqa2j8g1Z96DCxw:-O5mCu8-1_8GaJfK0dUw:b6gv43p) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/transactions_test.rs#L928)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

not needed because of the revert.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 953 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hhOSdDPgpqaTMKRN7:-O5mDTmt4KZbmx8e3Cf7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/transactions_test.rs#L953)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. ditto on above
2. no need to rename amount and price fields, it is clear by the `if` statement below what you are comparing to
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 974 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hhXIS539qPuZDinjT:-O5mDj-U8WQ3_zWGRFvQ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/transactions_test.rs#L974)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. ditto
2. ditto
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1970 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hhZ_pBXrayE744K0L:-O5mDqPeEqZwP--dLvFv:bpmf1b9) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/transactions_test.rs#L1970)):*
> ```XML
>         TransactionExecutionError::TransactionFeeError(
>             TransactionFeeError::InsufficientFee {resource: Resource::L1Gas, paid_fee, actual_fee, })
>             if paid_fee == Fee(0) && actual_fee == expected_actual_fee
> ```

Not needed because of the revert.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/670)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/transaction/errors.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5mpDNGENNzDHMt4fBF:-O5mpDNGENNzDHMt4fBG:b4oxd6f) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc704deef7dd18a33ba82c1a82a116e0d15a250d/crates/blockifier/src/transaction/errors.rs#L28)):*
> ```XML
>     #[error(
>         "Gas bounds (max amount: {max_amount}, max price: {max_price}) exceed balance ({balance})."
>     )]
> ```

why not output the resource type?



_Code quote:_
```XML
    #[error(
        "Gas bounds (max amount: {max_amount}, max price: {max_price}) exceed balance ({balance})."
    )]
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5mpJHW6j2p5FPzHuXm:-O5mpJHW6j2p5FPzHuXn:b-1cglql) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc704deef7dd18a33ba82c1a82a116e0d15a250d/crates/blockifier/src/transaction/errors.rs#L35)):*
> ```XML
>         balance: BigUint,
>     },
>     #[error("GasBounds: Max fee ({}) exceeds balance ({balance}).", max_fee.0, )]
> ```

no gas bounds in deprecated txs



_Suggestion:_
```XML
Max fee ({})
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5mpPV28ss2ijZScCOe:-O5mpPV35RVZqQK-_u6Z:b-tc5117) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc704deef7dd18a33ba82c1a82a116e0d15a250d/crates/blockifier/src/transaction/errors.rs#L40)):*
> ```XML
>     MaxFeeTooLow { min_fee: Fee, max_fee: Fee },
>     #[error(
>         "Max gas price ({max_gas_price}) is lower than the actual gas price: {actual_gas_price}."
> ```

why not print the resource?



_Code quote:_
```XML
"Max gas price 
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 813 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5hhEIzCievzHcBPas-:-O5mptzm4iW6OhABPlJG:bxlikgl) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d4a4c8daacb7aa55918475514ff223139d114db/crates/blockifier/src/transaction/transactions_test.rs#L813)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

I think it is the same since your code matches the expression returned  from
```
invalid_tx.execute(state, block_context, true, true).unwrap_err()
```
to the error (with any resource),
and then checked that 
```resource == Resource::L1Gas```

and in my code, the match itself doesn't succeed if the resource is not  
``` Resource::L1Gas```
</blockquote></details>

cool, didn't know this syntax is allowed in assert_matches

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/670)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/errors.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5mpDNGENNzDHMt4fBF:-O5vv8RnD8mjs5hQITwz:bdh0iu5) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc704deef7dd18a33ba82c1a82a116e0d15a250d/crates/blockifier/src/transaction/errors.rs#L28)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not output the resource type?
</blockquote></details>

Just got confused about whether the string related to the error under or above it :)
___
*[`crates/blockifier/src/transaction/errors.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5mpJHW6j2p5FPzHuXm:-O5w3zc0EE_ut95Vwwbn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc704deef7dd18a33ba82c1a82a116e0d15a250d/crates/blockifier/src/transaction/errors.rs#L35)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no gas bounds in deprecated txs
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/errors.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/670#-O5mpPV28ss2ijZScCOe:-O5w49exD7DrX_UZgN-a:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc704deef7dd18a33ba82c1a82a116e0d15a250d/crates/blockifier/src/transaction/errors.rs#L40)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not print the resource?
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/670#-:-O6pESwJ8o6jnZuXa7Es:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @Yoni-Starkware)

**Pull request merged**
