### PR TITLE
chore(blockifier_reexecution): write all blocks to file

### PR DESCRIPTION
**Pull request by aner-starkware**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1908)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1908#-OBL6np40wPFQN3QiExb:-OBL6np40wPFQN3QiExc:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/bbc84353261156bbadfed0d34cf52a72f46835d9/crates/blockifier_reexecution/src/state_reader/utils.rs#L213)):*
> ```XML
> 
> pub fn write_block_reexecution_data_to_file(
>     block_number: u64,
> ```





_Suggestion:_
```XML
block_number: BlockNumber,
```
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1908#-OBL6j3zBwvWHCed-c5M:-OBL6j4-1WkNpo7qgbmJ:bu1fn0y) ([raw file](https://github.com/starkware-libs/sequencer/blob/bbc84353261156bbadfed0d34cf52a72f46835d9/crates/blockifier_reexecution/src/state_reader/utils.rs#L262)):*
> ```XML
> /// There is block number for each Starknet Version (starting v0.13)
> /// And some additional block with specific transactions.
> pub fn get_block_numbers_for_reexecution() -> Vec<u64> {
> ```

revert this type change; convert the user input to BlockNumber instead



_Code quote:_
```XML
Vec<u64>
```
___
*[`crates/blockifier_reexecution/src/main.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1908#-OBL6WzsBYog9bp4_J93:-OBL6WzsBYog9bp4_J94:b-u7ue4o) ([raw file](https://github.com/starkware-libs/sequencer/blob/bbc84353261156bbadfed0d34cf52a72f46835d9/crates/blockifier_reexecution/src/main.rs#L141)):*
> ```XML
>                     node_url.clone(),
>                 );
>             }
> ```

can you parallelize this?



_Code quote:_
```XML
            for block_number in block_numbers {
                let full_file_path =
                    format!("{directory_path}/block_{block_number}/reexecution_data.json");

                write_block_reexecution_data_to_file(
                    block_number,
                    &full_file_path,
                    node_url.clone(),
                );
            }
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1908)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1908#-OBL6WzsBYog9bp4_J93:-OBPDO2m725hHdblGq0R:bdlacgv) ([raw file](https://github.com/starkware-libs/sequencer/blob/bbc84353261156bbadfed0d34cf52a72f46835d9/crates/blockifier_reexecution/src/main.rs#L141)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you parallelize this?
</blockquote></details>

You mean using Tokio? (Since it's IO, Rayon is probably not a good idea) 
It's possible, I guess (though might possibly be problematic due to the amount of RPC calls), but in any case, it's a big refactor. Should I add a TODO?
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1908#-OBL6j3zBwvWHCed-c5M:-OBPvy199M9RkOKWqY3i:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bbc84353261156bbadfed0d34cf52a72f46835d9/crates/blockifier_reexecution/src/state_reader/utils.rs#L262)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

revert this type change; convert the user input to BlockNumber instead
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1908#-OBL6np40wPFQN3QiExb:-OBPvyNUCb8t02JkiHMS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bbc84353261156bbadfed0d34cf52a72f46835d9/crates/blockifier_reexecution/src/state_reader/utils.rs#L213)):*
> ```XML
> 
> pub fn write_block_reexecution_data_to_file(
>     block_number: u64,
> ```

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1908)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1908#-OBL6WzsBYog9bp4_J93:-OBQCMCc55sU3mvgb6T1:b-78nacc) ([raw file](https://github.com/starkware-libs/sequencer/blob/bbc84353261156bbadfed0d34cf52a72f46835d9/crates/blockifier_reexecution/src/main.rs#L141)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

You mean using Tokio? (Since it's IO, Rayon is probably not a good idea) 
It's possible, I guess (though might possibly be problematic due to the amount of RPC calls), but in any case, it's a big refactor. Should I add a TODO?
</blockquote></details>

yes please
when we're close to integrating into the CI we should go over all TODOs in this crate...
Also, maybe we will decide to run the offline reexecution via CLI instead of `cargo test`, in which case we won't get parallelization for free anymore
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 271 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1908#-OBQCuLd2Auh0J4b51jg:-OBQCuLd2Auh0J4b51jh:baf6zlm) ([raw file](https://github.com/starkware-libs/sequencer/blob/62fd53a3c672505f13106f9ab849ad2325c530aa/crates/blockifier_reexecution/src/state_reader/utils.rs#L271)):*
> ```XML
>         serde_json::from_value(read_json_file("block_numbers_for_reexecution.json"))
>             .expect("Failed to deserialize block header");
>     block_numbers_examples.values().map(|block_number| BlockNumber(*block_number)).collect()
> ```

non-blocking



_Suggestion:_
```XML
.values().cloned().map(BlockNumber).collect()
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1908)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1908#-OBL6WzsBYog9bp4_J93:-OBQEbnlAPOpJgoFHMR9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bbc84353261156bbadfed0d34cf52a72f46835d9/crates/blockifier_reexecution/src/main.rs#L141)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes please
when we're close to integrating into the CI we should go over all TODOs in this crate...
Also, maybe we will decide to run the offline reexecution via CLI instead of `cargo test`, in which case we won't get parallelization for free anymore
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1908#-:-OBQF-QM3qFOKMVFCuC_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1908)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
