### PR TITLE
feat(sync): implement DataStreamBuilder for classes

### PR DESCRIPTION
**Pull request by noamsp-starkware**

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1829)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/papyrus_p2p_sync/src/client/class.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1829#-OB4x4OI2E0-sBElEGMN:-OB4x4OI2E0-sBElEGMO:b-2vaobc) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f4362d7a475db628246b10e80a49ec28a39f873/crates/papyrus_p2p_sync/src/client/class.rs#L130)):*
> ```XML
> 
>     fn get_start_block_number(storage_reader: &StorageReader) -> Result<BlockNumber, StorageError> {
>         storage_reader.begin_ro_txn()?.get_state_marker()
> ```

Should be class marker. Note that the test you're writing will probably fail if you don't fix this
___
*[`crates/papyrus_p2p_sync/src/client/mod.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1829#-OB4ubMm4fVomBnyoI4q:-OB4ubMm4fVomBnyoI4r:b-64q772) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f4362d7a475db628246b10e80a49ec28a39f873/crates/papyrus_p2p_sync/src/client/mod.rs#L54)):*
> ```XML
>     pub num_block_state_diffs_per_query: u64,
>     pub num_transactions_per_query: u64,
>     pub num_classes_per_query: u64,
> ```

Please rename this to num_block_classes_per_query. If you can, fix num_transactions too on the way

**Comment by noamsp-starkware** [comment]
* **#1829** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1829?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @noamsp-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by noamsp-starkware — COMMENTED** [review]
r2 - rebase revision

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1829#-:-OBL0mVP4wjBW_KPDjCD:br98r0h)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1829)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/client/class.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1829#-OB4x4OI2E0-sBElEGMN:-OBL5CUN2Oex9Tm0mK7I:bb6sh2i) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f4362d7a475db628246b10e80a49ec28a39f873/crates/papyrus_p2p_sync/src/client/class.rs#L130)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Should be class marker. Note that the test you're writing will probably fail if you don't fix this
</blockquote></details>

Ack.
___
*[`crates/papyrus_p2p_sync/src/client/mod.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1829#-OB4ubMm4fVomBnyoI4q:-OBL5C9N69t1UbiTzfW0:bb6sh2i) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f4362d7a475db628246b10e80a49ec28a39f873/crates/papyrus_p2p_sync/src/client/mod.rs#L54)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Please rename this to num_block_classes_per_query. If you can, fix num_transactions too on the way
</blockquote></details>

Ack.

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 3 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1829)* status: all files reviewed, 2 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 72 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1829#-OBLAmG_5wEkGqwNCbfP:-OBLAmG_5wEkGqwNCbfQ:b8ecjez) ([raw file](https://github.com/starkware-libs/sequencer/blob/770f3e848b74f3cce802d9b6b63a9e613e7db37c/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L72)):*
> ```XML
>                     BlockNumberLimit::Unlimited => num_blocks_per_query,
>                     BlockNumberLimit::HeaderMarker | BlockNumberLimit::StateDiffMarker => {
>                         let last_block_number = if let BlockNumberLimit::HeaderMarker = Self::BLOCK_NUMBER_LIMIT {
> ```

Use match instead, it will look cleaner
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 198 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1829#-OBLAwp70lFTB5W_R75S:-OBLAwp70lFTB5W_R75T:b-9b4olk) ([raw file](https://github.com/starkware-libs/sequencer/blob/770f3e848b74f3cce802d9b6b63a9e613e7db37c/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L198)):*
> ```XML
>     #[error("The class with hash {class_hash} was not found in the state diff.")]
>     ClassNotInStateDiff { class_hash: ClassHash },
>     #[error("Two classes with the same hash are conflicting.")]
> ```

Change the message to: Received two classes with the same hash

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1829)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 79 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1829#-OBOzqIp5mlzh3kES4b2:-OBP39Ld4AxBE5gP921X:bb6sh1i) ([raw file](https://github.com/starkware-libs/sequencer/blob/50996f4ce1006fa1e76eb538ef676139c1d613a6/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L79)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

unite these two:
```
let (last_block_number, description) = match ...
```
</blockquote></details>

Ack

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1829#-:-OBP3NdF22B9r6tmntYe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)

**Pull request merged**
