### PR TITLE
Merge main-v0.13.2 into main

### PR DESCRIPTION
**Pull request by meship-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/691)

### CODE REVIEW

**Comment by meship-starkware** [comment]
[Src](https://github.com/starkware-libs/blockifier/compare/e9fef0f80c614a6f0a2db565f732383ff88fd6e3..main-v0.13.2#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3) [Dst](https://github.com/starkware-libs/blockifier/compare/e9fef0f80c614a6f0a2db565f732383ff88fd6e3..main#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3) .github/workflows/main.yml

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, 2 of 3 files at r3, 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/691)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 9 files at r7, 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/691)* status: 12 of 15 files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

___
*[`.github/workflows/main.yml` line 88 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/691#-O5rJvBD0TcqbLbMXhxU:-O5rJvBD0TcqbLbMXhxV:b-ie8kub) ([raw file](https://github.com/starkware-libs/sequencer/blob/fea10114dc1c38b4d74642aebdc205f59bf3e5fe/.github/workflows/main.yml#L88)):*
> ```YAML
>     steps:
>       - uses: actions/checkout@v4
> =======
> ```

@dorimedini-starkware can you PTAL?



_Code quote:_
```YAML
      - run: scripts/clippy.sh

  doc:
    runs-on: starkware-ubuntu-latest-small
    env:
      RUSTDOCFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
||||||| e9fef0f80
      - run: scripts/clippy.sh

  doc:
    runs-on: starkware-ubuntu-latest-small
    # env:
    #   RUSTDOCFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
=======
```

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/691)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/691)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r2, 3 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/691#-:-O5rRzdvBi9Nxlv1Gzsc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/691)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/691)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Pull request closed without merging**
