### PR TITLE
chore(blockifier): add struct ExecutionFlags to AccTx & use instead of transaction::ExecutionFlags

### PR DESCRIPTION
**Pull request by avivg-starkware**

### CODE REVIEW

**Comment by avivg-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2429?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2429** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2429?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2429?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2428** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2428?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2354](https://github.com/starkware-libs/sequencer/pull/2354) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2354?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2412** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2412?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2377** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2377?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2331** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2331?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2429)* status: 1 of 22 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2429#-ODC44l39LM2ia4u2qQ7:-ODC44l39LM2ia4u2qQ8:b-vl77i2) ([raw file](https://github.com/starkware-libs/sequencer/blob/43209f7adc62a26b6925ae08cfd6476c73d35dde/crates/native_blockifier/src/py_transaction.rs#L149)):*
> ```XML
>                 ..ExecutionFlags::default()
>             };
>             AccountTransaction { tx, execution_flags }.into()
> ```

Save this code duplication - add a constructor that gets the tx.
`new_for_sequencing` or something like this



_Code quote:_
```XML
            let execution_flags = ExecutionFlags {
                only_query,
                charge_fee: enforce_fee(&tx, only_query),
                ..ExecutionFlags::default()
            };
            AccountTransaction { tx, execution_flags }.into()
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2429)* status: 2 of 22 files reviewed, 4 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2429#-ODC5M-Y8DGqsyD1fnvu:-ODC5M-Y8DGqsyD1fnvv:b-k6votm) ([raw file](https://github.com/starkware-libs/sequencer/blob/43209f7adc62a26b6925ae08cfd6476c73d35dde/crates/blockifier/src/blockifier/transaction_executor_test.rs#L136)):*
> ```XML
>     );
>     let only_query = false;
>     let charge_fee = enforce_fee(&declare_tx, only_query);
> ```

What is this func? are you sure it is necessary?
Seems like you can use the `new_for_sequencing` c-tor everywhere here



_Code quote:_
```XML
enforce_fee
```

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2429)* status: 1 of 22 files reviewed, 4 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor_test.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2429#-ODC5M-Y8DGqsyD1fnvu:-ODGuZ942M_cGQi3CI5j:b-2o6xbh) ([raw file](https://github.com/starkware-libs/sequencer/blob/43209f7adc62a26b6925ae08cfd6476c73d35dde/crates/blockifier/src/blockifier/transaction_executor_test.rs#L136)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

What is this func? are you sure it is necessary?
Seems like you can use the `new_for_sequencing` c-tor everywhere here
</blockquote></details>

enforce_fee is the func created in the prev PR to allow computing 'charge_fee' before creating AccountTransaction #2377

and defiantly for using 'new_for_sequencing', in the following PR: #2431 
___
*[`crates/native_blockifier/src/py_transaction.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2429#-ODC44l39LM2ia4u2qQ7:-ODGryRLAe68uhLKcfsl:bi6k5do) ([raw file](https://github.com/starkware-libs/sequencer/blob/43209f7adc62a26b6925ae08cfd6476c73d35dde/crates/native_blockifier/src/py_transaction.rs#L149)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Save this code duplication - add a constructor that gets the tx.
`new_for_sequencing` or something like this
</blockquote></details>

Defiantly! added in the next PR as I'm anyway creating a constructor there.  #2431
___
*[`crates/starknet_batcher/src/block_builder.rs` line 177 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2429#-ODC4kn3EJZU3mid133f:-ODGwOt838qzu5-wwYgB:b-i76k2n) ([raw file](https://github.com/starkware-libs/sequencer/blob/43209f7adc62a26b6925ae08cfd6476c73d35dde/crates/starknet_batcher/src/block_builder.rs#L177)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Use the `new_for_sequencing` c-tor
</blockquote></details>

Done in #2431
___
*[`crates/starknet_gateway/src/stateful_transaction_validator.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2429#-ODC4zH36LGluh3Nbsb3:-ODGxfYhBiLf-twyQNCT:b-pl6vuv) ([raw file](https://github.com/starkware-libs/sequencer/blob/43209f7adc62a26b6925ae08cfd6476c73d35dde/crates/starknet_gateway/src/stateful_transaction_validator.rs#L81)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Should it be `!skip_validate`?
</blockquote></details>

Seems right. thank you.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 20 files at r1, 10 of 13 files at r2, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2429#-:-ODH2CJwEyLr9Awf_T1k:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1976 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2429#-ODH1scD4bfPrg7-3AZm:-ODH1scD4bfPrg7-3AZn:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c75942ee182df423d795a829864920df712eb4f5/crates/blockifier/src/transaction/transactions_test.rs#L1976)):*
> ```XML
>         validate_constructor,
>         validate: true,
>         charge_fee: false, // We test `__validate__`, and don't care about the cahrge fee flow.
> ```





_Suggestion:_
```XML
charge fee flow
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 724 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2429#-ODH1Q8J2XHDVucgqyQ0:-ODH1Q8J2XHDVucgqyQ1:bwvhwwj) ([raw file](https://github.com/starkware-libs/sequencer/blob/c75942ee182df423d795a829864920df712eb4f5/crates/blockifier/src/transaction/account_transaction.rs#L724)):*
> ```XML
>         state: &mut TransactionalState<'_, U>,
>         block_context: &BlockContext,
>         execution_flags_: TransactionExecutionFlags,
> ```

Consider passing `concurrecy_mode` without this struct



_Code quote:_
```XML
execution_flags_: TransactionExecutionFlags,
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 756 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2429#-ODH1HvjEqW1aybsncRa:-ODH1HvjEqW1aybsncRb:b-s4e7y9) ([raw file](https://github.com/starkware-libs/sequencer/blob/c75942ee182df423d795a829864920df712eb4f5/crates/blockifier/src/transaction/account_transaction.rs#L756)):*
> ```XML
>             tx_context.clone(),
>             self.execution_flags.validate,
>             self.execution_flags.charge_fee,
> ```

Be sure to push these inside instead of passing them as arguments (now that they are part of self)



_Code quote:_
```XML
            self.execution_flags.validate,
            self.execution_flags.charge_fee,
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2429#-:-ODLQ49jExpM0awGPgNa:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2429)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 756 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2429#-ODH1HvjEqW1aybsncRa:-ODMCPCq9OCFU4cgcple:bbmtxmw) ([raw file](https://github.com/starkware-libs/sequencer/blob/c75942ee182df423d795a829864920df712eb4f5/crates/blockifier/src/transaction/account_transaction.rs#L756)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

WOW, yes. will do
</blockquote></details>

#2491

**Review by avivg-starkware — COMMENTED** [review]
> Reviewed 6 of 20 files at r1, 8 of 13 files at r2, 2 of 5 files at r5, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2429)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Review by avivg-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2429)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Pull request merged**
