### PR TITLE
test(starknet_api): set l1 handler tx version to default zero

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#2698** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2698?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2698?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2698)* status: 0 of 9 files reviewed, all discussions resolved

___
*[`crates/starknet_api/src/test_utils/l1_handler.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2698#-OEJ25fmAgSnlv_ZR0Rl:-OEJ25fmAgSnlv_ZR0Rm:b2wvsqh) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa71cff70384d70ccc21c3c9e28662f2749f382b/crates/starknet_api/src/test_utils/l1_handler.rs#L20)):*
> ```XML
>     fn default() -> Self {
>         L1HandlerTxArgs {
>             version: TransactionVersion::THREE,
> ```

This number has changed in this PR.



_Code quote:_
```XML
TransactionVersion::THREE,
```
___
*[`crates/papyrus_rpc/src/v0_8/transaction.rs` line 1284 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2698#-OEJ1ZwI2t28j7CgyToH:-OEJ1ZwI2t28j7CgyToI:b2wvsqh) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa71cff70384d70ccc21c3c9e28662f2749f382b/crates/papyrus_rpc/src/v0_8/transaction.rs#L1284)):*
> ```XML
>         let calldata = Calldata(Arc::new(calldata));
>         Self {
>             version: TransactionVersion::ONE,
> ```

This number has changed in this PR.



_Code quote:_
```XML
version: TransactionVersion::ONE,
```

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2698#-:-OEhVLwxDIrWKdER2PcI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Dec 22, 3:39 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2698).

**Pull request merged**
