### PR TITLE
refactor(blockifier_reexecution): use retry request macro in more cases

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1905?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1905** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1905?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1902** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1902?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1905)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 299 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1905#-OBKsrZJ7zC4CBIKH2ZA:-OBKsrZJ7zC4CBIKH2ZB:b-nvnnkl) ([raw file](https://github.com/starkware-libs/sequencer/blob/503da9524a443f74ec82bbbd90e1149eedc80007/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L299)):*
> ```XML
>                 let params = json!({
>                     "transaction_hash": tx_hash,
>                 });
> ```

isn't there some object like `GetBlockWithTxHashesParams` for this?



_Code quote:_
```XML
                let params = json!({
                    "transaction_hash": tx_hash,
                });
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 302 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1905#-OBKsn_T3qEV9PsKuRm_:-OBKsn_T3qEV9PsKuRma:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/503da9524a443f74ec82bbbd90e1149eedc80007/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L302)):*
> ```XML
>                 self.rpc_state_reader.send_rpc_request(method, params)
>             }
>         )?)?)
> ```





_Suggestion:_
```XML
        Ok(deserialize_transaction_json_to_starknet_api_tx(retry_request!(
            self.retry_config,
            || {
                let params = json!({
                    "transaction_hash": tx_hash,
                });
                self.rpc_state_reader.send_rpc_request("starknet_getTransactionByHash", params)
            }
        )?)?)
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1905)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1905)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 299 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1905#-OBKsrZJ7zC4CBIKH2ZA:-OBL6jY7AqltWdB0SyMM:b-s1kepk) ([raw file](https://github.com/starkware-libs/sequencer/blob/503da9524a443f74ec82bbbd90e1149eedc80007/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L299)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

isn't there some object like `GetBlockWithTxHashesParams` for this?
</blockquote></details>

No, I dont think so
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 302 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1905#-OBKsn_T3qEV9PsKuRm_:-OBL9hj--ii92UYqiIaR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/503da9524a443f74ec82bbbd90e1149eedc80007/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L302)):*
> ```XML
>                 self.rpc_state_reader.send_rpc_request(method, params)
>             }
>         )?)?)
> ```

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1905)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 299 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1905#-OBKsrZJ7zC4CBIKH2ZA:-OBLB1kX1vLfW5HGNor9:b-x26z7o) ([raw file](https://github.com/starkware-libs/sequencer/blob/503da9524a443f74ec82bbbd90e1149eedc80007/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L299)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

No, I dont think so
</blockquote></details>

please add such a struct in the gateway crate and ask someone from the gateway team to review,
+ use it here

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1905)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 299 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1905#-OBKsrZJ7zC4CBIKH2ZA:-OBLCjL14dZulJZ-Auyg:b-fbpwa9) ([raw file](https://github.com/starkware-libs/sequencer/blob/503da9524a443f74ec82bbbd90e1149eedc80007/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L299)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add such a struct in the gateway crate and ask someone from the gateway team to review,
+ use it here
</blockquote></details>

But the gateway state reader doesn't impl the request `starknet_getTransactionByHash`, so I don't think it should be there

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1905)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 299 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1905#-OBKsrZJ7zC4CBIKH2ZA:-OBLFFe_B2vHJZ-H00lm:bro8feh) ([raw file](https://github.com/starkware-libs/sequencer/blob/503da9524a443f74ec82bbbd90e1149eedc80007/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L299)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

But the gateway state reader doesn't impl the request `starknet_getTransactionByHash`, so I don't think it should be there
</blockquote></details>

ah...
hmm...
maybe add a struct here above, in this crate, with a comment that it may need to migrate to the gateway crate in the future?
I prefer we stay consistent with using structs instead of JSON data

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1905)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 299 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1905#-OBKsrZJ7zC4CBIKH2ZA:-OBLQFnv7S2lSvQapNd7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/503da9524a443f74ec82bbbd90e1149eedc80007/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L299)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah...
hmm...
maybe add a struct here above, in this crate, with a comment that it may need to migrate to the gateway crate in the future?
I prefer we stay consistent with using structs instead of JSON data
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1905#-:-OBLYyopAmU05sAzhkfw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
