### PR TITLE
feat(tests-integration): add functionality for dumping config change …

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
…files

commit-id:e3bafafd

---

**Stack**:
- #1383
- #1364
- #1363
- #1361 ⬅
- #1360

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by yair-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1361)* status: all files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/tests-integration/src/integration_test_config_utils.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1361#-O98vb2H9IFo-OmpZB-m:-O98vb2I1ymNoQJIzvhX:b-rukqfs) ([raw file](https://github.com/starkware-libs/sequencer/blob/13157905922d729b7745ff66674c38d5888cb72d/crates/tests-integration/src/integration_test_config_utils.rs#L16)):*
> ```XML
> 
> /// A utility macro that takes a list of config fields and returns a json dictionary with "field
> /// name : field value" entries, where prefixed "config." name is removed from the entry key.
> ```

Consider adding an example, also move down in the file.



_Code quote:_
```XML
/// A utility macro that takes a list of config fields and returns a json dictionary with "field
/// name : field value" entries, where prefixed "config." name is removed from the entry key.
```
___
*[`crates/tests-integration/src/integration_test_config_utils.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1361#-O98xlME1gqW2kuckYlg:-O98xlME1gqW2kuckYlh:b-uxz0ep) ([raw file](https://github.com/starkware-libs/sequencer/blob/13157905922d729b7745ff66674c38d5888cb72d/crates/tests-integration/src/integration_test_config_utils.rs#L33)):*
> ```XML
> /// Transaction generator:
> /// cargo run --bin run_test_tx_generator -- --config_file TX_GEN_CONFIG_CHANGES_FILE_PATH
> pub fn dump_config_file_changes(config: SequencerNodeConfig) -> anyhow::Result<()> {
> ```

Who calls this?



_Code quote:_
```XML
dump_config_file_changes
```
___
*[`crates/tests-integration/src/integration_test_config_utils.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1361#-O98ykvZE7Q8ugFsEg-F:-O98ykvZE7Q8ugFsEg-G:b-f1ola3) ([raw file](https://github.com/starkware-libs/sequencer/blob/13157905922d729b7745ff66674c38d5888cb72d/crates/tests-integration/src/integration_test_config_utils.rs#L57)):*
> ```XML
> 
>     // Write the JSON string to a file
>     let mut file = File::create(path)?;
> ```

This will create a persistent file. I think it makes the todo not be a "consider."



_Code quote:_
```XML
File::create(path)?
```
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1361#-O9907XiADZg5SCCzi9P:-O9907XiADZg5SCCzi9Q:b-gm0ii4) ([raw file](https://github.com/starkware-libs/sequencer/blob/13157905922d729b7745ff66674c38d5888cb72d/crates/tests-integration/src/integration_test_utils.rs#L26)):*
> ```XML
>     batcher_storage_config: StorageConfig,
> ) -> SequencerNodeConfig {
>     let chain_id = batcher_storage_config.db_config.chain_id.clone();
> ```

Consider modifying `StorageTestSetup` to keep the chain_id as a member and pass it forward from there (more explicit I think)



_Code quote:_
```XML
batcher_storage_config.db_config.chain_id.clone()
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1361)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/tests-integration/src/integration_test_config_utils.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1361#-O98vb2H9IFo-OmpZB-m:-O99BS4P0dY-W_EU7Vf1:bs7b15) ([raw file](https://github.com/starkware-libs/sequencer/blob/13157905922d729b7745ff66674c38d5888cb72d/crates/tests-integration/src/integration_test_config_utils.rs#L16)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider adding an example, also move down in the file.
</blockquote></details>

Added an example, but unlike functions, macros cannot be defined after their usage.
___
*[`crates/tests-integration/src/integration_test_config_utils.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1361#-O98xlME1gqW2kuckYlg:-O99BWKf1xK2oa5P51iX:b-1lbcac) ([raw file](https://github.com/starkware-libs/sequencer/blob/13157905922d729b7745ff66674c38d5888cb72d/crates/tests-integration/src/integration_test_config_utils.rs#L33)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Who calls this?
</blockquote></details>

The code in the next pr, I split it as it was getting too long.
___
*[`crates/tests-integration/src/integration_test_config_utils.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1361#-O98ykvZE7Q8ugFsEg-F:-O99Baq79lHXAY_LMcWq:b97rudk) ([raw file](https://github.com/starkware-libs/sequencer/blob/13157905922d729b7745ff66674c38d5888cb72d/crates/tests-integration/src/integration_test_config_utils.rs#L57)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

This will create a persistent file. I think it makes the todo not be a "consider."
</blockquote></details>

Yea, I already considered this positively :-)
Editted the todo anyway.
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1361#-O9907XiADZg5SCCzi9P:-O99DKMs0NDAeZvFrTJk:bny6q0) ([raw file](https://github.com/starkware-libs/sequencer/blob/13157905922d729b7745ff66674c38d5888cb72d/crates/tests-integration/src/integration_test_utils.rs#L26)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider modifying `StorageTestSetup` to keep the chain_id as a member and pass it forward from there (more explicit I think)
</blockquote></details>


It is already addressed in a later, but added the todo anyway :pray:

**Review by yair-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1361)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1361)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
