### PR TITLE
test(starknet_api): use const for l1 handler tx version

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2763)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_api/src/transaction.rs` line 692 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2763#-OEhHRiL-mUVsVLr9ApC:-OEhHRiL-mUVsVLr9ApD:b-nv045b) ([raw file](https://github.com/starkware-libs/sequencer/blob/343785514a68ebd38dac305b1bd1f1dd30a7c773/crates/starknet_api/src/transaction.rs#L692)):*
> ```XML
>     /// purposes.
>     pub const VERSION: TransactionVersion = TransactionVersion::ZERO;
> }
> ```

WDYT?
This will 
a) make its api consistent with the rest of the tx types which all use a getter
b) make it impossible to instantiate an l1 tx with an incorrect field (and communicate that fact better maybe)



_Suggestion:_
```XML
#[derive(Debug, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
pub struct L1HandlerTransaction {
    pub nonce: Nonce,
    pub contract_address: ContractAddress,
    pub entry_point_selector: EntryPointSelector,
    pub calldata: Calldata,
}

impl L1HandlerTransaction {
    /// The transaction version is considered 0 for L1-Handler transaction for hash calculation
    /// purposes.
    pub const VERSION: TransactionVersion = TransactionVersion::ZERO;
    
    pub fn version(&self) -> TransactionVersion {
        Self::VERSION
    }
}
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2763)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/starknet_api/src/transaction.rs` line 692 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2763#-OEhHRiL-mUVsVLr9ApC:-OEhJqBS5DODJG-MtfxQ:bj8wjwc) ([raw file](https://github.com/starkware-libs/sequencer/blob/343785514a68ebd38dac305b1bd1f1dd30a7c773/crates/starknet_api/src/transaction.rs#L692)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

WDYT?
This will 
a) make its api consistent with the rest of the tx types which all use a getter
b) make it impossible to instantiate an l1 tx with an incorrect field (and communicate that fact better maybe)
</blockquote></details>

On a later PR. 

I tried something similar. There is an issue with the serialization, etc.

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2763#-:-OEhVCRM6bLur0oLOrE7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/starknet_api/src/transaction.rs` line 692 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2763#-OEhHRiL-mUVsVLr9ApC:-OEhV8Ku6ADQ2EMq3bsN:b-i598y3) ([raw file](https://github.com/starkware-libs/sequencer/blob/343785514a68ebd38dac305b1bd1f1dd30a7c773/crates/starknet_api/src/transaction.rs#L692)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

On a later PR. 

I tried something similar. There is an issue with the serialization, etc.
</blockquote></details>

:melting_face:

**Comment by ArniStarkware** [comment]
### Merge activity

* **Dec 22, 3:39 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2763).

**Pull request merged**
