### PR TITLE
refactor(blockifier): fix some u128 gas cost remainings

### PR DESCRIPTION
**Pull request by meship-starkware**

### CODE REVIEW

**Review by avi-starkware — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2204)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/receipt_test.rs` line 435 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2204#-OCCtFW27sl_oHCR2TTf:-OCCtFW27sl_oHCR2TTg:b-7ejprq) ([raw file](https://github.com/starkware-libs/sequencer/blob/34323a1af0ee432d7a6b1feab6eb97d23a8f571c/crates/blockifier/src/fee/receipt_test.rs#L435)):*
> ```XML
>         &tx_execution_info.execute_call_info.expect("Execution call info should exist.");
>     let execution_summary =
>         CallInfo::summarize_many(vec![execution_call_info].into_iter(), &versioned_constants);
> ```

This line conflicts with dori's PR #2122



_Code quote:_
```XML
       CallInfo::summarize_many(vec![execution_call_info].into_iter(), &versioned_constants);
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2204#-:-OCCwBm-Cqx1FDvO1a_d:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2204)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2204)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2204)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2204)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Pull request merged**
