### PR TITLE
chore(tests_integration): return tx sender address

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #2071
- #2070
- #2056 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2056)* status: all files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2056#-OBuUWAG7oktBleyZXTG:-OBuUWAG7oktBleyZXTH:b81lznl) ([raw file](https://github.com/starkware-libs/sequencer/blob/d4e1db2b39fef1d6b2ac49407f6af64a7b6f3c0a/crates/starknet_integration_tests/src/utils.rs#L186)):*
> ```XML
> }
> 
> fn create_txs_for_tx_generator_test_scenario(
> ```

Consider passing the account ID as an arg, and then you can get the contract address outside of this function.
Also can you please rename this function? It's not clear what it does.
___
*[`crates/starknet_integration_tests/src/utils.rs` line 241 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2056#-OBuWcrwCbqdV71Syl2z:-OBuWcrwCbqdV71Syl3-:b-mblm8w) ([raw file](https://github.com/starkware-libs/sequencer/blob/d4e1db2b39fef1d6b2ac49407f6af64a7b6f3c0a/crates/starknet_integration_tests/src/utils.rs#L241)):*
> ```XML
> /// Creates and runs the many txs test scenario for the sequencer integration test. Returns
> /// a list of transaction hashes, in the order they are expected to be in the mempool.
> pub async fn run_transaction_generator_test_scenario<'a, Fut>(
> ```

Also rename to match.



_Code quote:_
```XML
run_transaction_generator_test_scenario
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2056)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2056#-OBuUWAG7oktBleyZXTG:-OBvLj9b5CQvV0YF4u4l:bojqhtt) ([raw file](https://github.com/starkware-libs/sequencer/blob/d4e1db2b39fef1d6b2ac49407f6af64a7b6f3c0a/crates/starknet_integration_tests/src/utils.rs#L186)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Consider passing the account ID as an arg, and then you can get the contract address outside of this function.
Also can you please rename this function? It's not clear what it does.
</blockquote></details>

Added a todo to address that, this will require a few changes elsewhere.
___
*[`crates/starknet_integration_tests/src/utils.rs` line 241 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2056#-OBuWcrwCbqdV71Syl2z:-OBvLs3s2w8gmm26EAK_:bkqwoq9) ([raw file](https://github.com/starkware-libs/sequencer/blob/d4e1db2b39fef1d6b2ac49407f6af64a7b6f3c0a/crates/starknet_integration_tests/src/utils.rs#L241)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Also rename to match.
</blockquote></details>

The todo above includes renaming this function as well.

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2056)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2056#-OBuUWAG7oktBleyZXTG:-OBz3ssJEVw8CiihVmVg:bjamh4k) ([raw file](https://github.com/starkware-libs/sequencer/blob/d4e1db2b39fef1d6b2ac49407f6af64a7b6f3c0a/crates/starknet_integration_tests/src/utils.rs#L186)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Added a todo to address that, this will require a few changes elsewhere.
</blockquote></details>

It's a small change, I opened a [PR](https://reviewable.io/reviews/starkware-libs/sequencer/2134) over your stack to show you what I meant.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2056)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
