### PR TITLE
refactor(mempool_test_utils): add non mut account_with_id, rename previous implementation

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Comment by yair-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2801?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2805** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2805?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2804** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2804?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2803** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2803?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2802** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2802?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2801** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2801?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2801?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2724** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2724?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2801)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2801#-OFHIr-2-ybty23jcAmA:-OFHIr-3EjSxa1heHvx5:b-37wm2b) ([raw file](https://github.com/starkware-libs/sequencer/blob/56942a28b1d1238d4b500ced6e56f0d25ea304a0/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L209)):*
> ```XML
>     }
> 
>     pub fn account_with_id(&self, account_id: AccountId) -> &AccountTransactionGenerator {
> ```

Why do you need both?

**Comment by yair-starkware** [comment]
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2801#-OFHIr-2-ybty23jcAmA:-OFHhxid-lPRI8Z8qB4o:b4arh5) ([raw file](https://github.com/starkware-libs/sequencer/blob/56942a28b1d1238d4b500ced6e56f0d25ea304a0/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L209)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why do you need both?
</blockquote></details>

We need to hold the funding account and the account to be deployed simultaneously. It is not possible if they require a mutable ref of `self`

**Review by alonh5 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2801#-:-OFHvdt1B0jaM5MDyBjb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2801#-OFHIr-2-ybty23jcAmA:-OFHvVqJ3Qxi60W8lhzZ:bcr5s2o) ([raw file](https://github.com/starkware-libs/sequencer/blob/56942a28b1d1238d4b500ced6e56f0d25ea304a0/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L209)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

We need to hold the funding account and the account to be deployed simultaneously. It is not possible if they require a mutable ref of `self`
</blockquote></details>

Got it, thanks!

**Pull request merged**
