### PR TITLE
chore(tests_integration): add nonce verification

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
commit-id:ab21c59b

---

**Stack**:
- #2071 ⬅
- #2070

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2071)* status: all files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/tests/end_to_end_integration_test.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2071#-OBuZoOj3cQHca-oUnCZ:-OBuZoOj3cQHca-oUnC_:buqvyw3) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4734f6690db58e29b661fcc75e80b1e58393a7d/crates/starknet_integration_tests/tests/end_to_end_integration_test.rs#L69)):*
> ```XML
> fn get_latest_block_number(storage_reader: &StorageReader) -> BlockNumber {
>     let txn = storage_reader.begin_ro_txn().unwrap();
>     txn.get_state_marker().unwrap().prev().unwrap()
> ```

This will panic if no blocks have been written yet, right? Is that what we want?
Same below at get nonce



_Code quote:_
```XML
txn.get_state_marker().unwrap().prev().unwrap()
```
___
*[`crates/starknet_integration_tests/tests/end_to_end_integration_test.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2071#-OBuZXDA9T505cPGmvpy:-OBuZXDA9T505cPGmvpz:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4734f6690db58e29b661fcc75e80b1e58393a7d/crates/starknet_integration_tests/tests/end_to_end_integration_test.rs#L80)):*
> ```XML
>     let txn = storage_reader.begin_ro_txn().unwrap();
>     let state_number = StateNumber::unchecked_right_after_block(block_number);
>     get_nonce_at(&txn, state_number, None.as_ref(), contract_address).unwrap().unwrap()
> ```





_Suggestion:_
```XML
&None
```
___
*[`crates/starknet_integration_tests/tests/end_to_end_integration_test.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2071#-OBu_GlMCVwXHUd8Om_d:-OBu_GlMCVwXHUd8Om_e:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4734f6690db58e29b661fcc75e80b1e58393a7d/crates/starknet_integration_tests/tests/end_to_end_integration_test.rs#L83)):*
> ```XML
> }
> 
> /// Sample a storage until sufficiently many blocks have been stored. Returns an error if the after
> ```





_Suggestion:_
```XML
if after
```
___
*[`crates/starknet_integration_tests/tests/end_to_end_integration_test.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2071#-OBu_Q7YCxecXzihkdwx:-OBu_Q7Z1GrYATZf-xYe:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4734f6690db58e29b661fcc75e80b1e58393a7d/crates/starknet_integration_tests/tests/end_to_end_integration_test.rs#L84)):*
> ```XML
> 
> /// Sample a storage until sufficiently many blocks have been stored. Returns an error if the after
> /// a certain number of attempts the target block number has not been reached.
> ```





_Suggestion:_
```XML
the given
```
___
*[`crates/starknet_integration_tests/tests/end_to_end_integration_test.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2071#-OBubXkkDqcUjeAFDOax:-OBubXkkDqcUjeAFDOay:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4734f6690db58e29b661fcc75e80b1e58393a7d/crates/starknet_integration_tests/tests/end_to_end_integration_test.rs#L85)):*
> ```XML
> /// Sample a storage until sufficiently many blocks have been stored. Returns an error if the after
> /// a certain number of attempts the target block number has not been reached.
> async fn await_until_storage_contains_block(
> ```





_Suggestion:_
```XML
await_block
```
___
*[`crates/starknet_integration_tests/tests/end_to_end_integration_test.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2071#-OBuXRaeC6oAsbIJbwdb:-OBuXRaeC6oAsbIJbwdc:b3kqj) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4734f6690db58e29b661fcc75e80b1e58393a7d/crates/starknet_integration_tests/tests/end_to_end_integration_test.rs#L176)):*
> ```XML
>     );
> 
>     info!("Verify tx sender account nonce.");
> ```

 



_Suggestion:_
```XML
info!("Verifying tx sender account nonce.");
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2071)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/tests/end_to_end_integration_test.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2071#-OBuZoOj3cQHca-oUnCZ:-OBvMF8s6LGICBkwy8y9:b-3c5jwz) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4734f6690db58e29b661fcc75e80b1e58393a7d/crates/starknet_integration_tests/tests/end_to_end_integration_test.rs#L69)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This will panic if no blocks have been written yet, right? Is that what we want?
Same below at get nonce
</blockquote></details>

The setup function that creates the db ensures it is not empty. I prefer not to add error handling here.
___
*[`crates/starknet_integration_tests/tests/end_to_end_integration_test.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2071#-OBu_GlMCVwXHUd8Om_d:-OBvMwKp4cT2_GR7MBz3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4734f6690db58e29b661fcc75e80b1e58393a7d/crates/starknet_integration_tests/tests/end_to_end_integration_test.rs#L83)):*
> ```XML
> }
> 
> /// Sample a storage until sufficiently many blocks have been stored. Returns an error if the after
> ```

Done.
___
*[`crates/starknet_integration_tests/tests/end_to_end_integration_test.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2071#-OBu_Q7YCxecXzihkdwx:-OBvN-BBA-PbQeSLmLqV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4734f6690db58e29b661fcc75e80b1e58393a7d/crates/starknet_integration_tests/tests/end_to_end_integration_test.rs#L84)):*
> ```XML
> 
> /// Sample a storage until sufficiently many blocks have been stored. Returns an error if the after
> /// a certain number of attempts the target block number has not been reached.
> ```

Done.
___
*[`crates/starknet_integration_tests/tests/end_to_end_integration_test.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2071#-OBubXkkDqcUjeAFDOax:-OBvN4Zx4rhW0abvoBi3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4734f6690db58e29b661fcc75e80b1e58393a7d/crates/starknet_integration_tests/tests/end_to_end_integration_test.rs#L85)):*
> ```XML
> /// Sample a storage until sufficiently many blocks have been stored. Returns an error if the after
> /// a certain number of attempts the target block number has not been reached.
> async fn await_until_storage_contains_block(
> ```

Done.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2071)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/tests/end_to_end_integration_test.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2071#-OBuXRaeC6oAsbIJbwdb:-OByOMEp63ZDeE7BxLPG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4734f6690db58e29b661fcc75e80b1e58393a7d/crates/starknet_integration_tests/tests/end_to_end_integration_test.rs#L176)):*
> ```XML
>     );
> 
>     info!("Verify tx sender account nonce.");
> ```

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2071)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/tests/end_to_end_integration_test.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2071#-OBuZoOj3cQHca-oUnCZ:-OBz3ZRsDC7phXS63OWG:bj7odgj) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4734f6690db58e29b661fcc75e80b1e58393a7d/crates/starknet_integration_tests/tests/end_to_end_integration_test.rs#L69)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

The setup function that creates the db ensures it is not empty. I prefer not to add error handling here.
</blockquote></details>

No need for error handling. Could you add documentation and also use `expect` instead of the respective `unwrap`?

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2071)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/tests/end_to_end_integration_test.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2071#-OBuZoOj3cQHca-oUnCZ:-OC-iUJ5AK-IZZUK06Yp:b2120bc) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4734f6690db58e29b661fcc75e80b1e58393a7d/crates/starknet_integration_tests/tests/end_to_end_integration_test.rs#L69)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

No need for error handling. Could you add documentation and also use `expect` instead of the respective `unwrap`?
</blockquote></details>

Changed to `expect`s, in both location. IMO thier message suffices as documentation, if you think otherwise please lmk what you'd like to be added :pray:

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2071)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/tests/end_to_end_integration_test.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2071#-OBuZoOj3cQHca-oUnCZ:-OC-ilc1BVojRoYindPL:b-ak1gl5) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4734f6690db58e29b661fcc75e80b1e58393a7d/crates/starknet_integration_tests/tests/end_to_end_integration_test.rs#L69)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Changed to `expect`s, in both location. IMO thier message suffices as documentation, if you think otherwise please lmk what you'd like to be added :pray:
</blockquote></details>

location*s*

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2071#-:-OC2RmhTBMcGF0N1njSu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2071)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2071)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
