### PR TITLE
fix(config): limit concurrency to prevent 'cargo test/build' crash due to excessive memory use

### PR DESCRIPTION
**Pull request by avivg-starkware**
- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1259)

### CODE REVIEW

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1259#-:-O8gU-Be2eHQJd4DksdV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1259)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1259)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1259)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware, @giladchase, and @noaov1)

___
*[`.cargo/config.toml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1259#-O8hGhpd8k-fjrEQ_ncY:-O8hGhpd8k-fjrEQ_ncZ:b-gc9dg0) ([raw file](https://github.com/starkware-libs/sequencer/blob/3fc8fef9f8e08779599e5e49518dbffd2013ff6c/.cargo/config.toml#L12)):*
> ```TOML
> # Limit concurrency to prevent crash during "cargo test" due to excessive memory usage. Should be removed in the future. Slows down performance.
> [test]
> jobs = 8
> ```

What about `cargo run`?



_Code quote:_
```TOML
# Limit concurrency to prevent crash during "cargo test" due to excessive memory usage. Should be removed in the future. Slows down performance.
[test]
jobs = 8
```

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1259)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase, @Itay-Tsabary-Starkware, and @noaov1)

___
*[`.cargo/config.toml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1259#-O8hGhpd8k-fjrEQ_ncY:-O8kAgS85BLBxDS-uoQq:byxxll9) ([raw file](https://github.com/starkware-libs/sequencer/blob/3fc8fef9f8e08779599e5e49518dbffd2013ff6c/.cargo/config.toml#L12)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

What about `cargo run`?
</blockquote></details>

You sure we want this..? won't adding a `[run]` section also limit the number of processes when actually running the built binary? this is not something we want

**Review by alon-dotan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1259)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @giladchase, @Itay-Tsabary-Starkware, and @noaov1)

___
*[`.cargo/config.toml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1259#-O8hGhpd8k-fjrEQ_ncY:-O8kKtOcEVhsv5_TqiKN:b-64trul) ([raw file](https://github.com/starkware-libs/sequencer/blob/3fc8fef9f8e08779599e5e49518dbffd2013ff6c/.cargo/config.toml#L12)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

You sure we want this..? won't adding a `[run]` section also limit the number of processes when actually running the built binary? this is not something we want
</blockquote></details>

Its limiting the number of jobs... not processes, as far as I know cargo run ends up running a single job....

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1259#-:-O8pWBpU79US5IfraVBR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware, @dorimedini-starkware, @Itay-Tsabary-Starkware, and @noaov1)

___
*[`.cargo/config.toml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1259#-O8hGhpd8k-fjrEQ_ncY:-O8pW0hoDEi1NfmVpZcg:b-la2v0c) ([raw file](https://github.com/starkware-libs/sequencer/blob/3fc8fef9f8e08779599e5e49518dbffd2013ff6c/.cargo/config.toml#L12)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

Its limiting the number of jobs... not processes, as far as I know cargo run ends up running a single job....
</blockquote></details>

Yep, the out of memory error occures during linking stage, so has no affect on runtime.

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1259)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware, @dorimedini-starkware, @Itay-Tsabary-Starkware, and @noaov1)

**Pull request merged**
