### PR TITLE
chore(ci): move codecov to main ci

### PR DESCRIPTION
**Pull request by dan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/124)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/124)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`.github/workflows/main.yml` line 161 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/124#-O2sfkh0-G5B55IRql2f:-O2sfkh0-G5B55IRql2g:bzdygh8) ([raw file](https://github.com/starkware-libs/sequencer/blob/1e4819cc882fb5e29c451f9a128754af5453bbf6/.github/workflows/main.yml#L161)):*
> ```YAML
>       - run: npm install -g ganache@7.4.3
>       - name: Coverage
>         run: cargo llvm-cov --codecov -r --output-path codecov.json
> ```

just making sure: this does not trigger `cargo test` right?
it's a workspace compilation + static analysis?
(non-blocking)



_Code quote:_
```YAML
run: cargo llvm-cov --codecov -r --output-path codecov.json
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/124)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/124)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/124)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/124#-O3353FjAOzrxCfdu8pZ:-O3353FjAOzrxCfdu8p_:b-9aff91) (no related file):*
please delete the codecov phase from blockifier_ci (it's commented out ATM I think)

___

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/124)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/124)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/124)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`.github/workflows/blockifier_coverage.yml` line  at r3](https://reviewable.io/reviews/starkware-libs/sequencer/124#-O45MV6e5I2dJr8cD3mQ:-O45gabTCbrAo37_T3a3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f815faa8077044d05b4fa519c067012ad9e43635/.github/workflows/blockifier_coverage.yml#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can't you delete this now after rebase?
</blockquote></details>

Done.

**Pull request merged**
