### PR TITLE
chore: improve blockifier CI trigger and scope

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/76)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/76)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`.github/workflows/blockifier_coverage.yml` line 0 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O328wZj4KCguhzneWBV:-O328wZj4KCguhzneWBW:b-eyegh8) ([raw file](https://github.com/starkware-libs/sequencer/blob/ffba6849137906f9971e25bd441af4ac225a5037/.github/workflows/blockifier_coverage.yml#L0)):*
note to self:
is this CI phase even needed?
don't we have a codecov phase in the main CI?

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/76)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`.github/workflows/blockifier_ci.yml` line 19 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O339LuT2QbSAGV4Zrga:-O339LuT2QbSAGV4Zrgb:bp955x3) ([raw file](https://github.com/starkware-libs/sequencer/blob/ffba6849137906f9971e25bd441af4ac225a5037/.github/workflows/blockifier_ci.yml#L19)):*
> ```YAML
>       - 'crates/native_blockifier/**'
>       - 'scripts/install_build_tools.sh'
>       - 'scripts/requirements.txt'
> ```

Do we want this requirement file or the one under `crates/blockifier/tests`?



_Code quote:_
```YAML
      - 'scripts/requirements.txt'
```
___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O338GdI4LzGG6_0tGws:-O338GdI4LzGG6_0tGwt:bs05cud) ([raw file](https://github.com/starkware-libs/sequencer/blob/ffba6849137906f9971e25bd441af4ac225a5037/.github/workflows/blockifier_compiled_cairo.yml#L10)):*
> ```YAML
>     - v[0-9].**
>     paths:
>     - '.github/workflows/blockifier_compiled_cairo.yml'
> ```

What does it mean to have the file name in the file itself?



_Code quote:_
```YAML
    - '.github/workflows/blockifier_compiled_cairo.yml'
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/76)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`.github/workflows/blockifier_ci.yml` line 19 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O339LuT2QbSAGV4Zrga:-O33B-7F9kFBiOWIyULW:b-tx5jz8) ([raw file](https://github.com/starkware-libs/sequencer/blob/ffba6849137906f9971e25bd441af4ac225a5037/.github/workflows/blockifier_ci.yml#L19)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do we want this requirement file or the one under `crates/blockifier/tests`?
</blockquote></details>

good catch.. this is actually only needed in the `blockifier_compiled_cairo` job below
___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O338GdI4LzGG6_0tGws:-O33Ap0QC9qmNNHwfUl2:b-tlyjan) ([raw file](https://github.com/starkware-libs/sequencer/blob/ffba6849137906f9971e25bd441af4ac225a5037/.github/workflows/blockifier_compiled_cairo.yml#L10)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What does it mean to have the file name in the file itself?
</blockquote></details>

so this job triggers when it changes (I think this is what it does, at least)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/76)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`.github/workflows/blockifier_coverage.yml` line  at r2](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O328wZj4KCguhzneWBV:-O33M1Ga15Pt-BDiFhy_:b1vrcc6) ([raw file](https://github.com/starkware-libs/sequencer/blob/ffba6849137906f9971e25bd441af4ac225a5037/.github/workflows/blockifier_coverage.yml#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

note to self:
is this CI phase even needed?
don't we have a codecov phase in the main CI?
</blockquote></details>

[related PR](https://reviewable.io/reviews/starkware-libs/sequencer/124)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/76)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`.github/workflows/blockifier_ci.yml` line 11 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EW5Nc6yf1wPvkHQDg:-O3EW5Nc6yf1wPvkHQDh:bfxqp3n) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_ci.yml#L11)):*
> ```YAML
>       - main-v[0-9].**
>     tags:
>       - v[0-9].**
> ```

Why is there no paths here?



_Code quote:_
```YAML
  push:
    branches:
      - main
      - main-v[0-9].**
    tags:
      - v[0-9].**
```
___
*[`.github/workflows/blockifier_ci.yml` line 27 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EWyGc3oG2tQ9Vo2tK:-O3EWyGc3oG2tQ9Vo2tL:bgfrpzp) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_ci.yml#L27)):*
> ```YAML
>       - 'build_native_blockifier_in_docker.sh'
>       - 'crates/blockifier/**'
>       - 'crates/native_blockifier/**'
> ```

Why is the native blockifier trigger this ci job?



_Code quote:_
```YAML
      - 'crates/native_blockifier/**'
```
___
*[`.github/workflows/blockifier_ci.yml` line 29 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EXAdS0GVDzC9U6m3-:-O3EXAdS0GVDzC9U6m30:btcc0ao) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_ci.yml#L29)):*
> ```YAML
>       - 'crates/native_blockifier/**'
>       - 'scripts/build_native_blockifier.sh'
>       - 'scripts/install_build_tools.sh'
> ```

What is this file?



_Code quote:_
```YAML
      - 'scripts/install_build_tools.sh'
```
___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 6 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EXJOFD5TxiN4Mx1SB:-O3EXJOFD5TxiN4Mx1SC:b-6jgssp) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_compiled_cairo.yml#L6)):*
> ```YAML
>   push:
>     branches:
>     - main
> ```

Why here we don't also have: `main-v[0-9].**`?
Do we want to add this branch to the papyrus ci?



_Code quote:_
```YAML
    branches:
    - main
```
___
*[`.github/workflows/blockifier_coverage.yml` line 9 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EXcf69LhflO_LXErI:-O3EXcf69LhflO_LXErJ:bl5r8fj) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_coverage.yml#L9)):*
> ```YAML
>       - 'crates/blockifier/**'
>       - 'crates/native_blockifier/**'
>   push:
> ```

Why here we don't need to mention branches?



_Code quote:_
```YAML
  push:
```
___
*[`.github/workflows/blockifier_post-merge.yml` line 11 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EVH8w2Pt-P8I-AMNP:-O3EVH8x1rXwd3rqP05x:bb76mu4) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_post-merge.yml#L11)):*
> ```YAML
>       - 'crates/blockifier/**'
>       - 'crates/native_blockifier/**'
>       - 'scripts/requirements.txt'
> ```

Why?



_Code quote:_
```YAML
      - 'scripts/requirements.txt'
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/76)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`.github/workflows/blockifier_ci.yml` line 11 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EW5Nc6yf1wPvkHQDg:-O3EgtS08chPZBZcY11b:b-uu49qv) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_ci.yml#L11)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is there no paths here?
</blockquote></details>

until we decide how we fix the brokefier and not create many redundant artifacts, we will temporarily build a native blockifier artifact on every merge to a release branch (on `push` to `branches: main, main-v[0-9].**`).
so, no paths: *always* trigger this job
___
*[`.github/workflows/blockifier_ci.yml` line 27 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EWyGc3oG2tQ9Vo2tK:-O3EhKAuBzL4745awJNV:b-h9jc1g) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_ci.yml#L27)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is the native blockifier trigger this ci job?
</blockquote></details>

for the `native-blockifier-artifacts-push` job in this file
___
*[`.github/workflows/blockifier_ci.yml` line 29 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EXAdS0GVDzC9U6m3-:-O3EhPZHBEHAbZYhOtGt:b51smde) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_ci.yml#L29)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What is this file?
</blockquote></details>

part of the build-native-blockifier process.
script runs docker -> docker calls script to install deps -> script is install_build_tools
___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 6 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EXJOFD5TxiN4Mx1SB:-O3EhkN3-cuw_V-0GAcb:b-26pekh) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_compiled_cairo.yml#L6)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why here we don't also have: `main-v[0-9].**`?
Do we want to add this branch to the papyrus ci?
</blockquote></details>

1. good catch, thanks! added
2. yes, which papyrus CIs don't have it?
___
*[`.github/workflows/blockifier_coverage.yml` line 9 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EXcf69LhflO_LXErI:-O3EhskA1nH-7sXct1IN:blrapwl) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_coverage.yml#L9)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why here we don't need to mention branches?
</blockquote></details>

I think code coverage report is really only useful during review; "post-merge coverage report" sounds redundant, WDYT?
___
*[`.github/workflows/blockifier_post-merge.yml` line 11 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EVH8w2Pt-P8I-AMNP:-O3EiC8FA4awiN5nrLi9:bhs22fc) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_post-merge.yml#L11)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

my mistake
need the requirements.txt in the blockifier crate (blockifier/** covers it)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/76)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`.github/workflows/blockifier_ci.yml` line 11 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EW5Nc6yf1wPvkHQDg:-O3SY3e35Oup-9uH83-q:b-lsjgb0) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_ci.yml#L11)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

until we decide how we fix the brokefier and not create many redundant artifacts, we will temporarily build a native blockifier artifact on every merge to a release branch (on `push` to `branches: main, main-v[0-9].**`).
so, no paths: *always* trigger this job
</blockquote></details>

Got it. Document?
Why not have this job in a `native_blockifier_ci.yml` file?
___
*[`.github/workflows/blockifier_ci.yml` line 29 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EXAdS0GVDzC9U6m3-:-O3SYmRiDb9SKeX54bdQ:by8lm2n) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_ci.yml#L29)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

part of the build-native-blockifier process.
script runs docker -> docker calls script to install deps -> script is install_build_tools
</blockquote></details>

Document?
___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 6 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EXJOFD5TxiN4Mx1SB:-O3SZMoG85Z5E8u03SWE:b-8zztr6) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_compiled_cairo.yml#L6)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. good catch, thanks! added
2. yes, which papyrus CIs don't have it?
</blockquote></details>

I see it's missing in:
`papyrus_ci.yml`, `papyrus_docker-publish.yml` and `helm-install.yml`
___
*[`.github/workflows/blockifier_coverage.yml` line 9 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EXcf69LhflO_LXErI:-O3SZq7ICuHnmOlheLdG:bwdai1s) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_coverage.yml#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think code coverage report is really only useful during review; "post-merge coverage report" sounds redundant, WDYT?
</blockquote></details>

I agree. What will adding branches do? Trigger this job post merge to the mentioned branches?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/76)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`.github/workflows/blockifier_ci.yml` line 11 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EW5Nc6yf1wPvkHQDg:-O3WlrVB1ve5OLk_2TUh:b-mpd5cr) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_ci.yml#L11)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Got it. Document?
Why not have this job in a `native_blockifier_ci.yml` file?
</blockquote></details>

1. done
2. already have a TODO for that at the top of the file :)
___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 6 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EXJOFD5TxiN4Mx1SB:-O3WmCWjEVAvOTODTaZD:bvoi6gg) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_compiled_cairo.yml#L6)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I see it's missing in:
`papyrus_ci.yml`, `papyrus_docker-publish.yml` and `helm-install.yml`
</blockquote></details>

out of scope of this PR, but we should fix this

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/76)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dorimedini-starkware)

___
*[`.github/workflows/blockifier_coverage.yml` line 9 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EXcf69LhflO_LXErI:-O3hXd_l2U2RRq9zCD3j:b-bo9el7) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_coverage.yml#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

oops... this was run on every push to any branch...
deleted the `push` event
</blockquote></details>

Why don't we want it to run on every push to the (native ) blockifier branch?

**Review by noaov1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/76)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/76)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`.github/workflows/blockifier_coverage.yml` line 9 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/76#-O3EXcf69LhflO_LXErI:-O3hdGfdEN16LtQ8mbCW:b-18vhmk) ([raw file](https://github.com/starkware-libs/sequencer/blob/f77c5c445e50d0c5ad7c9474a5ab62a79bfd4535/.github/workflows/blockifier_coverage.yml#L9)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why don't we want it to run on every push to the (native ) blockifier branch?
</blockquote></details>

what is the native blockifier branch?
if you are asking why not run on every push to main/main-v0.13.2 - why run on every push? all you get is a post-merge report in your inbox; IMO running jobs on push events is only useful (if even) when the failure indicates an error in the code, like test failure or artifact build failure. WDYT?

In any case I think this particular discussion is a bit redundant since [codecov should be moving to the main CI anyway](https://reviewable.io/reviews/starkware-libs/sequencer/124#-O3353FjAOzrxCfdu8pZ)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/76)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
