### PR TITLE
refactor(mempool): change thin tx to internal tx

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/356)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/356)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O40hw4-AEIkyKPyK8v0:-O40hw4-AEIkyKPyK8v1:bq2vmjl) (no related file):*
Changing Mempool's API.
`AddTx` and `GetTxs` uses `InternalTx`.

___

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 1 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/356)* status: 1 of 12 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O40qZZ9D7kBwwSsDjvM:-O40qZZA6hl7W4ipJSyk:bkwueyc) ([raw file](https://github.com/starkware-libs/sequencer/blob/a75ba936478f194278b48353101d52e8bd1f806a/crates/gateway/src/gateway.rs#L144)):*
> ```XML
>     Ok(MempoolInput {
>         tx: (&external_tx_to_thin_tx(&tx, validate_info.tx_hash, validate_info.sender_address))
>             .into(),
> ```

i don't know if it's a good idea, but consider creating `external_tx_to_tx` instead of `into`?



_Code quote:_
```XML
.into()
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/356)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O40qZZ9D7kBwwSsDjvM:-O44Miiu2OtZsbMOjLuD:b-y3m7zi) ([raw file](https://github.com/starkware-libs/sequencer/blob/a75ba936478f194278b48353101d52e8bd1f806a/crates/gateway/src/gateway.rs#L144)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

i don't know if it's a good idea, but consider creating `external_tx_to_tx` instead of `into`?
</blockquote></details>

Sound good, raising to "why doesn't `RpcTransaction` have a `into_transaction` method?".
Seems like something an external transaction should know how to do.
___
*[`crates/mempool/src/mempool.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O44NSI3Eq55uhOt8UOO:-O44NSI3Eq55uhOt8UOP:bjvgrdo) ([raw file](https://github.com/starkware-libs/sequencer/blob/a75ba936478f194278b48353101d52e8bd1f806a/crates/mempool/src/mempool.rs#L151)):*
> ```XML
>         } = input;
>         let sender_address = input.tx.contract_address();
>         let tx_nonce = input.tx.nonce();
> ```

this seems longer than the previos notation, what's the motivation for not using the former anymore?



_Code quote:_
```XML
            account: Account { state: AccountState { nonce: account_nonce }, .. },
            ..
        } = input;
        let sender_address = input.tx.contract_address();
        let tx_nonce = input.tx.nonce();
```
___
*[`crates/mempool/src/mempool.rs` line 239 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O44Nhkf8QVFrCtbqvq6:-O44Nhkf8QVFrCtbqvq7:b55793b) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce7ec4c4e8f622ca9c5dbd4fc975c3b5711aa4d1/crates/mempool/src/mempool.rs#L239)):*
> ```XML
>             tx_hash: tx.tx_hash(),
>             tip: tx.tip().unwrap(),
>         }
> ```

remove in separate PR, this PR is too long for this.

If you have a mass-action in a PR, like changing ThinTransaction to Transaction, there shouldn't be any other operations in the PR if possible



_Code quote:_
```XML
    pub fn new(tx: &ThinTransaction) -> Self {
        TransactionReference {
            sender_address: tx.sender_address,
            nonce: tx.nonce,
            tx_hash: tx.tx_hash,
            tip: tx.tip,
        }
    }
    pub fn new_from_transaction(tx: &Transaction) -> Self {
        TransactionReference {
            sender_address: tx.contract_address(),
            nonce: tx.nonce(),
            tx_hash: tx.tx_hash(),
            tip: tx.tip().unwrap(),
        }
```
___
*[`crates/starknet_api/src/executable_transaction.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O44MF339foMJL6nMpuF:-O44MF339foMJL6nMpuG:b-noadmy) ([raw file](https://github.com/starkware-libs/sequencer/blob/a75ba936478f194278b48353101d52e8bd1f806a/crates/starknet_api/src/executable_transaction.rs#L0)):*
These should be added on a separate PR before this one

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/356)* status: 6 of 12 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O40qZZ9D7kBwwSsDjvM:-O4A4j8J6l9yBmbtCbtw:b21p1z2) ([raw file](https://github.com/starkware-libs/sequencer/blob/a75ba936478f194278b48353101d52e8bd1f806a/crates/gateway/src/gateway.rs#L144)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Sound good, raising to "why doesn't `RpcTransaction` have a `into_transaction` method?".
Seems like something an external transaction should know how to do.
</blockquote></details>

Good points!
In the next pull request (PR), I have implemented `external_tx_to_tx`. I decided to split it into smaller PRs. 

Re the `from` method: we have a method that converts `RPCTransaction` to `AccountTransaction`. @ArniStarkware will update it to convert from `RPC` to `Internal`.
___
*[`crates/mempool/src/mempool.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O44NSI3Eq55uhOt8UOO:-O4A6-rS4r1Lmla6O1OX:blha6rh) ([raw file](https://github.com/starkware-libs/sequencer/blob/a75ba936478f194278b48353101d52e8bd1f806a/crates/mempool/src/mempool.rs#L151)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

this seems longer than the previos notation, what's the motivation for not using the former anymore?
</blockquote></details>

At this stage, input_tx contains ThinTx and not internal transactions.
___
*[`crates/mempool/src/mempool.rs` line 239 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O44Nhkf8QVFrCtbqvq6:-O4A6Ps96pvuQ24euY2b:b-kat5q5) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce7ec4c4e8f622ca9c5dbd4fc975c3b5711aa4d1/crates/mempool/src/mempool.rs#L239)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

remove in separate PR, this PR is too long for this.

If you have a mass-action in a PR, like changing ThinTransaction to Transaction, there shouldn't be any other operations in the PR if possible
</blockquote></details>

Note, here I didn't simply remove the code.
Now, the new expects `Transaction` instead of `ThinTransaction`.
___
*[`crates/starknet_api/src/executable_transaction.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O44MF339foMJL6nMpuF:-O4ALfef8KnlDUdM3vt6:b-sf1sid) ([raw file](https://github.com/starkware-libs/sequencer/blob/a75ba936478f194278b48353101d52e8bd1f806a/crates/starknet_api/src/executable_transaction.rs#L)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

These should be added on a separate PR before this one
</blockquote></details>

Added:
https://reviewable.io/reviews/starkware-libs/sequencer/426

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2, 8 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/356)* status: 9 of 12 files reviewed, 11 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4ZJv1IEb6VT0VQGZwS:-O4ZJv1IEb6VT0VQGZwT:bj6opre) (no related file):*
Please update commit message.

___
___
*[`crates/gateway/src/gateway.rs` line 147 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4ZKJUjAeLMTBlPb25m:-O4ZKJUjAeLMTBlPb25n:b-5u8rtw) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e3d0a605f86ffa98d662538d13c2149508f40d0/crates/gateway/src/gateway.rs#L147)):*
> ```XML
>     Ok(MempoolInput {
>         tx: (&external_tx_to_thin_tx(&tx, validate_info.tx_hash, validate_info.sender_address))
>             .into(),
> ```

What's the status here? This isn't elegant.
___
*[`crates/mempool/src/mempool.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O44NSI3Eq55uhOt8UOO:-O4ZKXCe-4R4P-ESnXkY:bcjhaqo) ([raw file](https://github.com/starkware-libs/sequencer/blob/a75ba936478f194278b48353101d52e8bd1f806a/crates/mempool/src/mempool.rs#L151)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

At this stage, input_tx contains ThinTx and not internal transactions.
</blockquote></details>

Not sure I understand.
___
*[`crates/mempool/src/mempool_test.rs` line 163 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4ZKgXc7Gju5so2TtUR:-O4ZKgXc7Gju5so2TtUS:b-gc46lh) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e3d0a605f86ffa98d662538d13c2149508f40d0/crates/mempool/src/mempool_test.rs#L163)):*
> ```XML
>             nonce: Nonce(felt!($tx_nonce)),
>         };
>         MempoolInput { tx: (&tx).into(), account }
> ```

Can this be avoided?



_Code quote:_
```XML
(&tx).into()
```
___
*[`crates/mempool/src/mempool_test.rs` line 384 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4ZKnkX50DraOQjC6CA:-O4ZKnkX50DraOQjC6CB:b-5ii5a2) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e3d0a605f86ffa98d662538d13c2149508f40d0/crates/mempool/src/mempool_test.rs#L384)):*
> ```XML
>     // TODO(Ayelet): Consider share this code.
>     // Sort in an ascending priority order.
>     add_tx_inputs.sort_by_key(|input| std::cmp::Reverse(input.tx.tip().unwrap()));
> ```

I would add a util for this, we can't `unwrap` every time; we only support `>= V3`.



_Code quote:_
```XML
unwrap()
```
___
*[`crates/mempool/src/transaction_pool.rs` line 4 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4ZJziN5UbzpLs8HWHB:-O4ZJziN5UbzpLs8HWHC:b-qpchet) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e3d0a605f86ffa98d662538d13c2149508f40d0/crates/mempool/src/transaction_pool.rs#L4)):*
> ```XML
> 
> use starknet_api::core::{ContractAddress, Nonce};
> use starknet_api::executable_transaction::Transaction;
> ```

I see #341's changes here. Was that your intention?
___
*[`crates/mempool_types/src/mempool_types.rs` line 45 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4ZKuxf9iBfAJCUCfWw:-O4ZKuxg1mz0U-oaDJ9g:bhnjqcg) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e3d0a605f86ffa98d662538d13c2149508f40d0/crates/mempool_types/src/mempool_types.rs#L45)):*
> ```XML
> 
> pub type MempoolResult<T> = Result<T, MempoolError>;
> ```

Doesn't belong here.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/356)* status: 5 of 12 files reviewed, 11 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4ZJv1IEb6VT0VQGZwS:-O4_k1Z87oToDuEHUEkp:b-cypxrc) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please update commit message.
</blockquote></details>

updated.

___
___
*[`crates/gateway/src/gateway.rs` line 147 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4ZKJUjAeLMTBlPb25m:-O4_eCW7Dz6AbfujCi0x:bo956tp) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e3d0a605f86ffa98d662538d13c2149508f40d0/crates/gateway/src/gateway.rs#L147)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What's the status here? This isn't elegant.
</blockquote></details>

It's temporal.
changed in this [PR](https://reviewable.io/reviews/starkware-libs/sequencer/360).
___
*[`crates/mempool/src/mempool.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O44NSI3Eq55uhOt8UOO:-O4_eOwu1vQKetK99Zai:b-8sb96y) ([raw file](https://github.com/starkware-libs/sequencer/blob/a75ba936478f194278b48353101d52e8bd1f806a/crates/mempool/src/mempool.rs#L151)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure I understand.
</blockquote></details>

Note that in this PR, `MempoolInput` includes Tx and not ThinTx.
It's not an elegant code to extract the fields from full transaction struct.
___
*[`crates/mempool/src/mempool_test.rs` line 163 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4ZKgXc7Gju5so2TtUR:-O4_gurm-S-ZUbAZEmBE:b-rym0dr) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e3d0a605f86ffa98d662538d13c2149508f40d0/crates/mempool/src/mempool_test.rs#L163)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can this be avoided?
</blockquote></details>

Removed [here](https://reviewable.io/reviews/starkware-libs/sequencer/377).
___
*[`crates/mempool/src/mempool_test.rs` line 384 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4ZKnkX50DraOQjC6CA:-O4_gyNvDE5kVXafCl7L:bgt5dmr) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e3d0a605f86ffa98d662538d13c2149508f40d0/crates/mempool/src/mempool_test.rs#L384)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I would add a util for this, we can't `unwrap` every time; we only support `>= V3`.
</blockquote></details>

I'll add it in another PR.
added to https://starkware.monday.com/boards/6678575467/pulses/7246894443.
___
*[`crates/mempool_types/src/mempool_types.rs` line 45 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4ZKuxf9iBfAJCUCfWw:-O4_keaa18mfcdAEGYcM:brpmqc3) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e3d0a605f86ffa98d662538d13c2149508f40d0/crates/mempool_types/src/mempool_types.rs#L45)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Doesn't belong here.
</blockquote></details>

removed.
___
*[`crates/mempool/src/transaction_pool.rs` line 4 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4ZJziN5UbzpLs8HWHB:-O4_hoSP0jpkCfPfFYrD:b-ydbvzp) ([raw file](https://github.com/starkware-libs/sequencer/blob/0e3d0a605f86ffa98d662538d13c2149508f40d0/crates/mempool/src/transaction_pool.rs#L4)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I see #341's changes here. Was that your intention?
</blockquote></details>

Not sure I get it.
In this PR I updated the API (get_txs and add_tx).

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 11 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/356)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O44NSI3Eq55uhOt8UOO:-O4d87XD05CWejAWtH8i:bncyvww) ([raw file](https://github.com/starkware-libs/sequencer/blob/a75ba936478f194278b48353101d52e8bd1f806a/crates/mempool/src/mempool.rs#L151)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Note that in this PR, `MempoolInput` includes Tx and not ThinTx.
It's not an elegant code to extract the fields from full transaction struct.
</blockquote></details>

Because of the getters?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/356)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O44NSI3Eq55uhOt8UOO:-O4dCbubBvOIxJ0Ia1Pc:b76z51o) ([raw file](https://github.com/starkware-libs/sequencer/blob/a75ba936478f194278b48353101d52e8bd1f806a/crates/mempool/src/mempool.rs#L151)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Because of the getters?
</blockquote></details>

No, the similar code looks like the following.
Which i think it's less elegant.



_Code snippet:_
```XML
        let MempoolInput {
            tx: Transaction { tx: Transaction::Invoke(InvokeTransaction::V3{sender_address, nonce: tx_nonce}, .. },
            account: Account { state: AccountState { nonce: account_nonce }, .. },
```

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/356)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O44NSI3Eq55uhOt8UOO:-O4dGZsK6ej8m-uW_cig:b-nrnkes) ([raw file](https://github.com/starkware-libs/sequencer/blob/a75ba936478f194278b48353101d52e8bd1f806a/crates/mempool/src/mempool.rs#L151)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

No, the similar code looks like the following.
Which i think it's less elegant.
</blockquote></details>

This doesn't look so bad, but it isn't compiling, right? Due to different transaction types.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/356)* status: all files reviewed, 7 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 144 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4dZ9G194jIblGNf-jv:-O4dZ9G194jIblGNf-jw:bg9k32v) ([raw file](https://github.com/starkware-libs/sequencer/blob/33b52527c08e75ee37a36c66ac77dc05520fd0a5/crates/mempool/src/mempool.rs#L144)):*
> ```XML
>             ..
>         } = input;
>         let sender_address = input.tx.contract_address();
> ```

Used once, remove.



_Code quote:_
```XML
let sender_address = input.tx.contract_address();
```
___
*[`crates/mempool/src/mempool.rs` line 152 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4dZ5PH2_vHH95VMZpa:-O4dZ5PH2_vHH95VMZpb:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/33b52527c08e75ee37a36c66ac77dc05520fd0a5/crates/mempool/src/mempool.rs#L152)):*
> ```XML
> 
>         // Check the input: transaction nonce against given account state.
>         if account_nonce > &tx_nonce {
> ```





_Suggestion:_
```XML
let account_nonce = ...
let tx_nonce = ...
if account_nonce > &tx_nonce {
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/356)* status: 10 of 12 files reviewed, 7 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O44NSI3Eq55uhOt8UOO:-O4dvIPE6vdsI5bGH0O8:b7xo04v) ([raw file](https://github.com/starkware-libs/sequencer/blob/a75ba936478f194278b48353101d52e8bd1f806a/crates/mempool/src/mempool.rs#L151)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This doesn't look so bad, but it isn't compiling, right? Due to different transaction types.
</blockquote></details>

It fails during compilation.
___
*[`crates/mempool/src/mempool.rs` line 144 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4dZ9G194jIblGNf-jv:-O4dtvVy3lniOBn1G-jT:bc5jua1) ([raw file](https://github.com/starkware-libs/sequencer/blob/33b52527c08e75ee37a36c66ac77dc05520fd0a5/crates/mempool/src/mempool.rs#L144)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Used once, remove.
</blockquote></details>

It's used three times.
___
*[`crates/mempool/src/mempool.rs` line 152 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4dZ5PH2_vHH95VMZpa:-O4dvF8B8CdghpZw5VTo:b-g43xx3) ([raw file](https://github.com/starkware-libs/sequencer/blob/33b52527c08e75ee37a36c66ac77dc05520fd0a5/crates/mempool/src/mempool.rs#L152)):*
> ```XML
> 
>         // Check the input: transaction nonce against given account state.
>         if account_nonce > &tx_nonce {
> ```

tx_nonce is used 3 times.

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 6 files at r2, 7 of 11 files at r4, 2 of 4 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/356)* status: all files reviewed, 7 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool_types/src/mempool_types.rs` line 38 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4eDyL08B1AIwFz6Kwy:-O4eDyL08B1AIwFz6Kwz:b9anqvr) ([raw file](https://github.com/starkware-libs/sequencer/blob/b6955bbd59635d37a12f9070a3f0b8a8db74f7c1/crates/mempool_types/src/mempool_types.rs#L38)):*
> ```XML
> }
> 
> #[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
> ```

why did you remove it?



_Code quote:_
```XML
Default,
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/356)* status: all files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 144 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4dZ9G194jIblGNf-jv:-O4e_HDIEVf-S_XKw6Z-:bx9s3zz) ([raw file](https://github.com/starkware-libs/sequencer/blob/33b52527c08e75ee37a36c66ac77dc05520fd0a5/crates/mempool/src/mempool.rs#L144)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please define right before usage.
</blockquote></details>

It's already right before usage.
note, it's used immediately in `duplicate_nonce_error`.
___
*[`crates/mempool/src/mempool.rs` line 152 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4dZ5PH2_vHH95VMZpa:-O4e_U3DBiKW8633Rsi3:bx9s3zz) ([raw file](https://github.com/starkware-libs/sequencer/blob/33b52527c08e75ee37a36c66ac77dc05520fd0a5/crates/mempool/src/mempool.rs#L152)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Define it here, right before first usage.
</blockquote></details>

It's already right before usage.
note, it's used immediately in `duplicate_nonce_error`.
___
*[`crates/mempool_types/src/mempool_types.rs` line 38 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/356#-O4eDyL08B1AIwFz6Kwy:-O4eYx2z2OglIf96ADVz:bausyli) ([raw file](https://github.com/starkware-libs/sequencer/blob/b6955bbd59635d37a12f9070a3f0b8a8db74f7c1/crates/mempool_types/src/mempool_types.rs#L38)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why did you remove it?
</blockquote></details>

Cause transaction doesn't implement Default.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/356#-:-O4etlL61gAIl1beiDYH:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

**Pull request merged**
