### PR TITLE
refactor(starknet_api): gas vector to contain fields of type GasAmount

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1176)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1176?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1177** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1177?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1176** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1176?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1175** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1175?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1174** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1174?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1173** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1173?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1172** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1172?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1176)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1176#-O8WKE2PD_rFyVNET1Sy:-O8WKE2Q2PxStRdPB2mf:bd65yp4) ([raw file](https://github.com/starkware-libs/sequencer/blob/0a43e86bcf3104b6e7b592be0a2f4683abc36299/crates/papyrus_storage/src/serialization/serializers.rs#L0)):*
@ShahakShama would this change break backwards-compatibility?
@Yoni-Starkware do we care?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1176)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @ShahakShama and @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 295 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1176#-O8h6Gj05G1Cw2uAYBoN:-O8hDT7qEuJhVxGhuqTF:bjbomhb) ([raw file](https://github.com/starkware-libs/sequencer/blob/7819527fe90b9bfce946b19426006259ed3744c6/crates/papyrus_storage/src/serialization/serializers.rs#L295)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why this is duplicated?
</blockquote></details>

one in `auto_impl_get_test_instance!` macro and one in `auto_storage_serde!` macro

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1176)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1176#-:-O8kbc_e0JT6AEURzkXx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Oct 9, 6:06 AM EDT**: @dorimedini-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1176).

**Pull request merged**
