### PR TITLE
refactor(batcher): make versioned_constants_overrides field optional in BlockBuilderConfig

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#1832** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1832?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ArniStarkware** [comment]
Replaces #1414.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1832)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 328 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1832#-OAwRHbZDW08iFyKbe2A:-OAwRHbZDW08iFyKbe2B:b-4355ug) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1c02ec1eb652020d70361aaf9acebc2ca77c137/crates/blockifier/src/versioned_constants.rs#L328)):*
> ```XML
> 
>     /// Returns the latest versioned constants, applying the given overrides if provided.
>     pub fn latest_with_overrides(
> ```

do you think this function will be used in other places? why not use if,else in `BlockBuilderFactory`



_Code quote:_
```XML
latest_with_overrides
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1832)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @Yael-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 328 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1832#-OAwRHbZDW08iFyKbe2A:-OAw_jug5gs9rS7Z-R7q:bljnimt) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1c02ec1eb652020d70361aaf9acebc2ca77c137/crates/blockifier/src/versioned_constants.rs#L328)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

do you think this function will be used in other places? why not use if,else in `BlockBuilderFactory`
</blockquote></details>

Yes. It seems very useful to me.
(My master plan is to squash `latest_with_overrides`, `get_versioned_constants`, `latest_constants_with_overrides` together - if this is the case - I want them all to be close to each other).

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1832#-:-OAwsFOX4isI_6sUL_5-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1832)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/batcher/src/block_builder.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1832#-OB4YW0V8LnLxUS8aEdg:-OB4YW0V8LnLxUS8aEdh:b-f5jly8) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1c02ec1eb652020d70361aaf9acebc2ca77c137/crates/batcher/src/block_builder.rs#L143)):*
> ```XML
>         dump
>     }
> }
> ```

lets move this to be under the BlockBuilderConfig struct



_Code quote:_
```XML
impl Default for BlockBuilderConfig {
    fn default() -> Self {
        Self {
            // TODO: update the default values once the actual values are known.
            chain_info: ChainInfo::default(),
            execute_config: TransactionExecutorConfig::default(),
            bouncer_config: BouncerConfig::default(),
            sequencer_address: ContractAddress::default(),
            use_kzg_da: true,
            tx_chunk_size: 100,
            versioned_constants_overrides: None,
        }
    }
}

impl SerializeConfig for BlockBuilderConfig {
    fn dump(&self) -> BTreeMap<ParamPath, SerializedParam> {
        let mut dump = append_sub_config_name(self.chain_info.dump(), "chain_info");
        dump.append(&mut append_sub_config_name(self.execute_config.dump(), "execute_config"));
        dump.append(&mut append_sub_config_name(self.bouncer_config.dump(), "bouncer_config"));
        dump.append(&mut BTreeMap::from([ser_param(
            "sequencer_address",
            &self.sequencer_address,
            "The address of the sequencer.",
            ParamPrivacyInput::Public,
        )]));
        dump.append(&mut BTreeMap::from([ser_param(
            "use_kzg_da",
            &self.use_kzg_da,
            "Indicates whether the kzg mechanism is used for data availability.",
            ParamPrivacyInput::Public,
        )]));
        dump.append(&mut BTreeMap::from([ser_param(
            "tx_chunk_size",
            &self.tx_chunk_size,
            "The size of the transaction chunk.",
            ParamPrivacyInput::Public,
        )]));
        dump.append(&mut ser_optional_sub_config(
            &self.versioned_constants_overrides,
            "versioned_constants_overrides",
        ));
        dump
    }
}
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 313 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1832#-OB4ZPZf2qjmeDyzlSgJ:-OB4ZPZf2qjmeDyzlSgK:bketh44) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1c02ec1eb652020d70361aaf9acebc2ca77c137/crates/blockifier/src/versioned_constants.rs#L313)):*
> ```XML
>     pub fn get_versioned_constants(
>         versioned_constants_overrides: VersionedConstantsOverrides,
>     ) -> Self {
> ```

why nor make this function get an option directly instead of having another function to wrap it?



_Code quote:_
```XML
    pub fn get_versioned_constants(
        versioned_constants_overrides: VersionedConstantsOverrides,
    ) -> Self {
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1832)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1832#-OB4YW0V8LnLxUS8aEdg:-OB5DYJ68TaN6En1ql4Z:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1c02ec1eb652020d70361aaf9acebc2ca77c137/crates/batcher/src/block_builder.rs#L143)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

lets move this to be under the BlockBuilderConfig struct
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 313 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1832#-OB4ZPZf2qjmeDyzlSgJ:-OB4whG498OVllUa1b5L:b6my3d1) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1c02ec1eb652020d70361aaf9acebc2ca77c137/crates/blockifier/src/versioned_constants.rs#L313)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why nor make this function get an option directly instead of having another function to wrap it?
</blockquote></details>

This is a topic for another PR.
I claim these other instances (of `get_versioned_constants`) should be examined further and potentially refactored. I do not want to complicate this PR any further.
Added a TODO.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1832)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
