### PR TITLE
fix: ascii art spacing

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/119)

### CODE REVIEW

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/119)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/119#-O2eL6uF6OZjCDxSzSxv:-O2eL6uGE4Hwqbc9keuR:bccjf9m) ([raw file](https://github.com/starkware-libs/sequencer/blob/b7cfa6bdc288edec012c53a8f64428310aebe179/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L140)):*
> ```XML
> ///                         26       90
> ///                        /      /     \
> ///                       ?      25      65
> ```

i think it's clearer than `?`. since it represents an edge node, and not some unknown value



_Suggestion:_
```XML
/
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/119#-O2eLOF83ZDVVW79Sma7:-O2eLOF99I59LvSzIOFE:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/b7cfa6bdc288edec012c53a8f64428310aebe179/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L142)):*
> ```XML
> ///                       ?      25      65
> ///                      /        \     /  \
> ///                     24         ?   6   59
> ```





_Suggestion:_
```XML
\
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/119#-O2eLQml071b9CT0CPAE:-O2eLQml071b9CT0CPAF:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/b7cfa6bdc288edec012c53a8f64428310aebe179/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L154)):*
> ```XML
> ///                          E       B
> ///                         /     /     \
> ///                        ?     E       B
> ```





_Suggestion:_
```XML
/
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/119#-O2eLSrR69U7y96i9u6W:-O2eLSrR69U7y96i9u6X:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/b7cfa6bdc288edec012c53a8f64428310aebe179/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L156)):*
> ```XML
> ///                        ?     E       B
> ///                       /       \     /  \
> ///                      24        ?   E    B
> ```





_Suggestion:_
```XML
\
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/119)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 298 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/119#-O2eSyzY5dJOAGHzYka9:-O2eUPDc4F6wJ85jZg1m:bptnd28) ([raw file](https://github.com/starkware-libs/sequencer/blob/9423952d05e43c23017848059eb03b67627a5fc3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L298)):*
> ```XML
> ///            1
> ///         /     \
> ///        ?       ?
> ```

went with `^`, ok?
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 298 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/119#-O2eT-T2-siJ-eAcxXZi:-O2eURX54nJK91H2qSp0:b-v28i2q) ([raw file](https://github.com/starkware-libs/sequencer/blob/9423952d05e43c23017848059eb03b67627a5fc3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L298)):*
> ```XML
> ///            1
> ///         /     \
> ///        ?       ?
> ```

went with `|`, ok?
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/119#-O2eT5O3E9ns5zLEbnmx:-O2eUZbq1ZRnYumJ5m3P:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9423952d05e43c23017848059eb03b67627a5fc3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L95)):*
> ```XML
> ///                 E     E                            B
> ///                /       \                         /   \
> ///               ?         B                       B     E
> ```

Done.

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/119)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 298 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/119#-O2eSyzY5dJOAGHzYka9:-O2ryfTV0NIRkI8YPUmo:b9eyaoi) ([raw file](https://github.com/starkware-libs/sequencer/blob/9423952d05e43c23017848059eb03b67627a5fc3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L298)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

went with `^`, ok?
</blockquote></details>

why? let's be consistent
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 298 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/119#-O2eT-T2-siJ-eAcxXZi:-O2ryode8VLXVVJfEJq_:b9eyaoi) ([raw file](https://github.com/starkware-libs/sequencer/blob/9423952d05e43c23017848059eb03b67627a5fc3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L298)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

went with `|`, ok?
</blockquote></details>

why? let's be consistent

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/119)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/119#-O2eL6uF6OZjCDxSzSxv:-O2saNM6AtbcLRNN_VA6:b-58rrs4) ([raw file](https://github.com/starkware-libs/sequencer/blob/b7cfa6bdc288edec012c53a8f64428310aebe179/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L140)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm not sure if we prefer to mark the edge node like we did before or not, but if we do, I assume that the asterisk sign is specifically the issue, and using pawn `#` will work.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/119)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 298 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/119#-O2eSyzY5dJOAGHzYka9:-O2xfUAWDLWMqN-Uehr-:btq8uj6) ([raw file](https://github.com/starkware-libs/sequencer/blob/9423952d05e43c23017848059eb03b67627a5fc3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L298)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

why? let's be consistent
</blockquote></details>

because `^` is a split and `\` is one direction
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 298 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/119#-O2eT-T2-siJ-eAcxXZi:-O2xfwTF20uQQFBCn9f-:b-7jzu7g) ([raw file](https://github.com/starkware-libs/sequencer/blob/9423952d05e43c23017848059eb03b67627a5fc3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L298)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

why? let's be consistent
</blockquote></details>

looks weird IMO but ok

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/119)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 298 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/119#-O2eSyzY5dJOAGHzYka9:-O2xhIxwEbBfAmxCqKkZ:b-w694yg) ([raw file](https://github.com/starkware-libs/sequencer/blob/9423952d05e43c23017848059eb03b67627a5fc3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L298)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

because `^` is a split and `\` is one direction
</blockquote></details>

can you please explain?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/119)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 298 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/119#-O2eSyzY5dJOAGHzYka9:-O2yIyQ1C2xmCQWsdXR4:b-kd32ac) ([raw file](https://github.com/starkware-libs/sequencer/blob/9423952d05e43c23017848059eb03b67627a5fc3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L298)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

can you please explain?
</blockquote></details>

this:
```
    /
   ?
 /   \
```
is not a long edge, the tree *splits* at the `?` point.
a `\` character is weird, no? indicates a single direction instead of a binary node

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/119)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

**Review by nimrod-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/119)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 298 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/119#-O2eSyzY5dJOAGHzYka9:-O2yWbS84Npot7VZjhc1:b-pmoxcx) ([raw file](https://github.com/starkware-libs/sequencer/blob/9423952d05e43c23017848059eb03b67627a5fc3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L298)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this:
```
    /
   ?
 /   \
```
is not a long edge, the tree *splits* at the `?` point.
a `\` character is weird, no? indicates a single direction instead of a binary node
</blockquote></details>

Oh, sorry, I thought it represented an edge node.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/119)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 298 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/119#-O2eSyzY5dJOAGHzYka9:-O2yenhFBhUHAQBNGRkO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9423952d05e43c23017848059eb03b67627a5fc3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L298)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Oh, sorry, I thought it represented an edge node.
</blockquote></details>

Done.

**Review by TzahiTaub — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/119)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

**Pull request merged**
