### PR TITLE
refactor(blockifier): replace BouncerConfig default by create_for_tes…

### PR DESCRIPTION
**Pull request by ayeletstarkware**
…ting.  This prepares for implementing a manual Default function for BouncerConfig, a field in ExecutionConfig, which will be added to BatcherConfig.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1283)

### CODE REVIEW

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1283)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @yair-starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1283#-O8p8E9OCYQ7YKxtMylG:-O8p8E9P9ReJKD7kUWGx:bgdkgkk) ([raw file](https://github.com/starkware-libs/sequencer/blob/64d981ba58b4a3578dcb22c7e1ead063c6d6d4f5/crates/blockifier/src/bouncer.rs#L52)):*
> ```XML
> 
>     pub fn empty() -> Self {
>         Self::default()
> ```

When I edited the code,  there was no empty function, 
seems that someone wanted to stress that it was empty. 
lets ask them if they want to name it empty instead of create_for_testing.



_Code quote:_
```XML
    pub fn empty() -> Self {
        Self::default()
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1283)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @yair-starkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 283 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1283#-O8pDXznE-v3EQgG9bvD:-O8pDXznE-v3EQgG9bvE:b-i9ew9d) ([raw file](https://github.com/starkware-libs/sequencer/blob/8988235b0a609fb57aae3eb8c23942d5efbe63ec/crates/blockifier/src/test_utils/struct_impls.rs#L283)):*
> ```XML
> 
> impl BouncerConfig {
>     pub fn create_for_testing() -> Self {
> ```

maybe it's clearer to stick to the existing terminology



_Suggestion:_
```XML
empty
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1283#-O8pDiDgBZTcODS8vtf0:-O8pDiDgBZTcODS8vtf1:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8988235b0a609fb57aae3eb8c23942d5efbe63ec/crates/blockifier/src/test_utils/struct_impls.rs#L289)):*
> ```XML
> 
> impl BouncerWeights {
>     pub fn create_for_testing() -> Self {
> ```





_Suggestion:_
```XML
empty
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1283)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1283#-O8p8E9OCYQ7YKxtMylG:-O8pH5BLC7qkchGTuwVh:bedr5ry) ([raw file](https://github.com/starkware-libs/sequencer/blob/64d981ba58b4a3578dcb22c7e1ead063c6d6d4f5/crates/blockifier/src/bouncer.rs#L52)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

When I edited the code,  there was no empty function, 
seems that someone wanted to stress that it was empty. 
lets ask them if they want to name it empty instead of create_for_testing.
</blockquote></details>

talked offline, decided to rename the func name to `empty`
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 283 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1283#-O8pDXznE-v3EQgG9bvD:-O8pFvky7Z8-awZDCLv4:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8988235b0a609fb57aae3eb8c23942d5efbe63ec/crates/blockifier/src/test_utils/struct_impls.rs#L283)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

maybe it's clearer to stick to the existing terminology
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1283#-O8pDiDgBZTcODS8vtf0:-O8pFwFp6ertEsyFBePD:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8988235b0a609fb57aae3eb8c23942d5efbe63ec/crates/blockifier/src/test_utils/struct_impls.rs#L289)):*
> ```XML
> 
> impl BouncerWeights {
>     pub fn create_for_testing() -> Self {
> ```

Done.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1283)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
