### PR TITLE
test(starknet_state_sync): add unit tests for state sync read methods

### PR DESCRIPTION
**Pull request by noamsp-starkware**

### CODE REVIEW

**Comment by noamsp-starkware** [comment]
* **#2886** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2886?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2886?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2886)* status: all files reviewed, 8 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/starknet_state_sync/src/test.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEo8eEh1JCOp9OfyHeA:-OEo8eEh1JCOp9OfyHeB:b3oho37) ([raw file](https://github.com/starkware-libs/sequencer/blob/d80a21467b827f5313ce354bdb951702f1b6c79f/crates/starknet_state_sync/src/test.rs#L23)):*
> ```XML
> use crate::StateSync;
> 
> fn get_mock_state_sync_and_storage_writer() -> (StateSync, StorageWriter) {
> ```

Why is this mock? It's the real thing just without the new_block_sender
I'd rename this function to `setup`
___
*[`crates/starknet_state_sync/src/test.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEo9An20LuRG4Y-0wM2:-OEo9An20LuRG4Y-0wM3:b-twec14) ([raw file](https://github.com/starkware-libs/sequencer/blob/d80a21467b827f5313ce354bdb951702f1b6c79f/crates/starknet_state_sync/src/test.rs#L40)):*
> ```XML
>         .append_header(header.block_header_without_hash.block_number, &header)
>         .unwrap()
>         .append_state_diff(header.block_header_without_hash.block_number, ThinStateDiff::default())
> ```

Put a non default ThinStateDiff. You can use get_test_instance. It makes for a more interesting test
___
*[`crates/starknet_state_sync/src/test.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEo8rjsCqicO3tgLIoz:-OEo8rjt4eMV4gFK-h5u:b74nucw) ([raw file](https://github.com/starkware-libs/sequencer/blob/d80a21467b827f5313ce354bdb951702f1b6c79f/crates/starknet_state_sync/src/test.rs#L49)):*
> ```XML
>     // Verify that the block that was written is returned correctly.
>     let value =
>         state_sync.get_block(header.block_header_without_hash.block_number).unwrap().unwrap();
> ```

I prefer using the external API: `state_sync.handle_request(StateSyncRequest::GetBlock(...))`
Same across the entire PR
___
*[`crates/starknet_state_sync/src/test.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEoAn2vEJPlfa7dyp3O:-OEoAn2vEJPlfa7dyp3P:b-8vygbm) ([raw file](https://github.com/starkware-libs/sequencer/blob/d80a21467b827f5313ce354bdb951702f1b6c79f/crates/starknet_state_sync/src/test.rs#L56)):*
> ```XML
> 
>     // Verify we get Ok(None) when trying to call get_block with an unknown block number.
>     let result = state_sync
> ```

I usually prefer doing separate test cases in separate tests. This way you put these comments in the test title
In most cases here you don't need any setup for the special case. You can just use an empty storage with any block number to test this case

Same across this PR
___
*[`crates/starknet_state_sync/src/test.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEoAUVuBwCkQ8DrCoN5:-OEoAUVuBwCkQ8DrCoN6:bd06eim) ([raw file](https://github.com/starkware-libs/sequencer/blob/d80a21467b827f5313ce354bdb951702f1b6c79f/crates/starknet_state_sync/src/test.rs#L68)):*
> ```XML
>     let mut rng = get_rng();
>     let expected_address_u64 = rng.next_u64();
>     let expected_address = ContractAddress::from(expected_address_u64);
> ```

expected_* is usually used for the expected return value. address is an argument and not a return value. You can just call it address

Same across this PR
___
*[`crates/starknet_state_sync/src/test.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEoADxHAMCsQtN0Z1k2:-OEoADxHAMCsQtN0Z1k3:b-ymebnt) ([raw file](https://github.com/starkware-libs/sequencer/blob/d80a21467b827f5313ce354bdb951702f1b6c79f/crates/starknet_state_sync/src/test.rs#L94)):*
> ```XML
>     // number.
>     let result = state_sync.get_storage_at(
>         header.block_header_without_hash.block_number.unchecked_next(),
> ```

Consider keeping this in a var called wrong_block_number or non_existing_block_number or other_block_number and use it here and in the assert
___
*[`crates/starknet_state_sync/src/test.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEoBV0sCowmDDnfxWXr:-OEoBV0sCowmDDnfxWXs:b-hghw6k) ([raw file](https://github.com/starkware-libs/sequencer/blob/d80a21467b827f5313ce354bdb951702f1b6c79f/crates/starknet_state_sync/src/test.rs#L123)):*
> ```XML
>     let expected_address_u64 = rng.next_u64();
>     let expected_address = ContractAddress::from(expected_address_u64);
>     let expected_value = Nonce::get_test_instance(&mut rng);
> ```

value -> nonce
___
*[`crates/starknet_state_sync/src/test.rs` line 172 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEoBSAp6xYEXdopK8Kj:-OEoBSAq8J2ubhMmFOJF:bfoau9c) ([raw file](https://github.com/starkware-libs/sequencer/blob/d80a21467b827f5313ce354bdb951702f1b6c79f/crates/starknet_state_sync/src/test.rs#L172)):*
> ```XML
>     let expected_address_u64 = rng.next_u64();
>     let expected_address = ContractAddress::from(expected_address_u64);
>     let expected_value = ClassHash::get_test_instance(&mut rng);
> ```

value -> class_hash
___
*[`crates/starknet_state_sync/src/test.rs` line 215 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEoB_poDGoe5lDU9cGL:-OEoB_poDGoe5lDU9cGM:b-gjmuo7) ([raw file](https://github.com/starkware-libs/sequencer/blob/d80a21467b827f5313ce354bdb951702f1b6c79f/crates/starknet_state_sync/src/test.rs#L215)):*
> ```XML
> 
> #[tokio::test]
> async fn test_get_compiled_class_deprecated() {
> ```

You can avoid updating this test according to my comments since it will be erased soon

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2886)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/starknet_state_sync/src/test.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEo8eEh1JCOp9OfyHeA:-OEoCizl2XkVEnxfp7Ik:bh6r8y6) ([raw file](https://github.com/starkware-libs/sequencer/blob/d80a21467b827f5313ce354bdb951702f1b6c79f/crates/starknet_state_sync/src/test.rs#L23)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why is this mock? It's the real thing just without the new_block_sender
I'd rename this function to `setup`
</blockquote></details>

Missed this, its from previous trials when writing the file. fixing
___
*[`crates/starknet_state_sync/src/test.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEo9An20LuRG4Y-0wM2:-OEoV0Yd7mi9BCXF6jbA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d80a21467b827f5313ce354bdb951702f1b6c79f/crates/starknet_state_sync/src/test.rs#L40)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Put a non default ThinStateDiff. You can use get_test_instance. It makes for a more interesting test
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync/src/test.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEo8rjsCqicO3tgLIoz:-OEob-5yCnheOmRQgKkE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d80a21467b827f5313ce354bdb951702f1b6c79f/crates/starknet_state_sync/src/test.rs#L49)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I prefer using the external API: `state_sync.handle_request(StateSyncRequest::GetBlock(...))`
Same across the entire PR
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync/src/test.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEoAn2vEJPlfa7dyp3O:-OEogu5d7H6uEE_aBIg5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d80a21467b827f5313ce354bdb951702f1b6c79f/crates/starknet_state_sync/src/test.rs#L56)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I usually prefer doing separate test cases in separate tests. This way you put these comments in the test title
In most cases here you don't need any setup for the special case. You can just use an empty storage with any block number to test this case

Same across this PR
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync/src/test.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEoAUVuBwCkQ8DrCoN5:-OEoYecBEDQAPBkXn1E-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d80a21467b827f5313ce354bdb951702f1b6c79f/crates/starknet_state_sync/src/test.rs#L68)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

expected_* is usually used for the expected return value. address is an argument and not a return value. You can just call it address

Same across this PR
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync/src/test.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEoBV0sCowmDDnfxWXr:-OEoZT145tjrat6B_j4F:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d80a21467b827f5313ce354bdb951702f1b6c79f/crates/starknet_state_sync/src/test.rs#L123)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

value -> nonce
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync/src/test.rs` line 172 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEoBSAp6xYEXdopK8Kj:-OEoZSkl2pDQipqSZlAG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d80a21467b827f5313ce354bdb951702f1b6c79f/crates/starknet_state_sync/src/test.rs#L172)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

value -> class_hash
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2886)* status: all files reviewed (commit messages unreviewed), 7 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/starknet_state_sync/src/test.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEraEIHAgpbpBiu13zM:-OEraEIIEA_gKyNvZ1Tb:b-1u4duq) ([raw file](https://github.com/starkware-libs/sequencer/blob/514b33a967d69771f687cba71cef0a9cf13d0ddb/crates/starknet_state_sync/src/test.rs#L65)):*
> ```XML
>         }
>         StateSyncResponse::GetBlock(Ok(None)) => {
>             panic!("No block returned");
> ```

No need to differentiate this case if you accept my suggestions below.
Same across the entire PR
___
*[`crates/starknet_state_sync/src/test.rs` line 68 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEra6XT3f_bsEzFXO5k:-OEra6XT3f_bsEzFXO5l:b-msng7) ([raw file](https://github.com/starkware-libs/sequencer/blob/514b33a967d69771f687cba71cef0a9cf13d0ddb/crates/starknet_state_sync/src/test.rs#L68)):*
> ```XML
>         }
>         _ => {
>             panic!("Expected StateSyncResponse::GetBlock::Ok");
> ```

display the response you actually got inside the panic message.
Same across the entire PR
___
*[`crates/starknet_state_sync/src/test.rs` line 68 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEraNer0-V8nQ-YXWmY:-OEraNer0-V8nQ-YXWmZ:bjwckiz) ([raw file](https://github.com/starkware-libs/sequencer/blob/514b33a967d69771f687cba71cef0a9cf13d0ddb/crates/starknet_state_sync/src/test.rs#L68)):*
> ```XML
>         }
>         _ => {
>             panic!("Expected StateSyncResponse::GetBlock::Ok");
> ```

If you apply the 2 suggestions above, change StateSyncResponse::GetBlock::Ok to StateSyncResponse::GetBlock::Ok(Some(_))
Same across the entire PR
___
*[`crates/starknet_state_sync/src/test.rs` line 252 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OErd2FHBS_m-q216hrO:-OErd2FHBS_m-q216hrP:b3gnvyz) ([raw file](https://github.com/starkware-libs/sequencer/blob/514b33a967d69771f687cba71cef0a9cf13d0ddb/crates/starknet_state_sync/src/test.rs#L252)):*
> ```XML
> async fn test_block_not_found() {
>     let (mut state_sync, _) = setup();
>     let wrong_block_number = BlockNumber(0);
> ```

consider non_existing_block_number
___
*[`crates/starknet_state_sync/src/test.rs` line 325 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OErdBm680ou7Yh-Q_sF:-OErdBm680ou7Yh-Q_sG:be94m40) ([raw file](https://github.com/starkware-libs/sequencer/blob/514b33a967d69771f687cba71cef0a9cf13d0ddb/crates/starknet_state_sync/src/test.rs#L325)):*
> ```XML
>     let address = ContractAddress::from(1u64);
>     let mut diff = ThinStateDiff::default();
>     diff.storage_diffs.insert(address, IndexMap::from([(Default::default(), Default::default())]));
> ```

Shouldn't you do the same for nonces?
___
*[`crates/starknet_state_sync/src/test.rs` line 325 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OErdIK7-v4DDO3JtVza:-OErdIK7-v4DDO3JtVzb:bnhzb2w) ([raw file](https://github.com/starkware-libs/sequencer/blob/514b33a967d69771f687cba71cef0a9cf13d0ddb/crates/starknet_state_sync/src/test.rs#L325)):*
> ```XML
>     let address = ContractAddress::from(1u64);
>     let mut diff = ThinStateDiff::default();
>     diff.storage_diffs.insert(address, IndexMap::from([(Default::default(), Default::default())]));
> ```

Add a comment that you're creating a corrupted state diff (storage diffs for a contract that wasn't deployed) and you're checking that even if the state diff is corrupted the function will work as expected
___
*[`crates/starknet_state_sync/src/test.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OErVyMRDJIcQtZCeUQp:-OErVyMRDJIcQtZCeUQq:b-yc0sjg) ([raw file](https://github.com/starkware-libs/sequencer/blob/d80a21467b827f5313ce354bdb951702f1b6c79f/crates/starknet_state_sync/src/test.rs#L48)):*
> ```XML
> 
>     // Verify that the block that was written is returned correctly.
>     let value =
> ```

use let else instead of match for a more compact syntax
Same across the entire PR

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2886)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/starknet_state_sync/src/test.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OErVyMRDJIcQtZCeUQp:-OErw3pS0SzimiaGk1W0:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d80a21467b827f5313ce354bdb951702f1b6c79f/crates/starknet_state_sync/src/test.rs#L48)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

use let else instead of match for a more compact syntax
Same across the entire PR
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync/src/test.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEraEIHAgpbpBiu13zM:-OErjzmT2lsZTF1CG0Ld:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/514b33a967d69771f687cba71cef0a9cf13d0ddb/crates/starknet_state_sync/src/test.rs#L65)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No need to differentiate this case if you accept my suggestions below.
Same across the entire PR
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync/src/test.rs` line 68 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEra6XT3f_bsEzFXO5k:-OErk-Wk8pQzvT-as6tu:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/514b33a967d69771f687cba71cef0a9cf13d0ddb/crates/starknet_state_sync/src/test.rs#L68)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

display the response you actually got inside the panic message.
Same across the entire PR
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync/src/test.rs` line 68 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEraNer0-V8nQ-YXWmY:-OErk0E-7QnkGtJraRTA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/514b33a967d69771f687cba71cef0a9cf13d0ddb/crates/starknet_state_sync/src/test.rs#L68)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

If you apply the 2 suggestions above, change StateSyncResponse::GetBlock::Ok to StateSyncResponse::GetBlock::Ok(Some(_))
Same across the entire PR
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync/src/test.rs` line 325 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OErdBm680ou7Yh-Q_sF:-OEs34Jd45bUMN0T1sat:bq2ikyk) ([raw file](https://github.com/starkware-libs/sequencer/blob/514b33a967d69771f687cba71cef0a9cf13d0ddb/crates/starknet_state_sync/src/test.rs#L325)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Shouldn't you do the same for nonces?
</blockquote></details>

Ill add it just for consistency, but to be honest, we don't really need this since we are just looking for an address that doesn't exist (therefore empty state_diff also does the job)
___
*[`crates/starknet_state_sync/src/test.rs` line 325 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OErdIK7-v4DDO3JtVza:-OEsPOl6BL7-CCKSUeNa:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/514b33a967d69771f687cba71cef0a9cf13d0ddb/crates/starknet_state_sync/src/test.rs#L325)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add a comment that you're creating a corrupted state diff (storage diffs for a contract that wasn't deployed) and you're checking that even if the state diff is corrupted the function will work as expected
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2886)* status: all files reviewed, 2 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/starknet_state_sync/src/test.rs` line 327 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEwoMb39UxB0t8zSuzn:-OEwoMb39UxB0t8zSuzo:buuw0mw) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae10b186b33694666e036b3f106270de32a13b2c/crates/starknet_state_sync/src/test.rs#L327)):*
> ```XML
>         .unwrap();
> 
>     // Check that get_storage_at verifies the contract was not deployed and therefore returns
> ```

Add to the end of the sentence ", even though the state diff is corrupt and contains this storage"
___
*[`crates/starknet_state_sync/src/test.rs` line 342 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEwoJQJ4cvguy7MJ5gC:-OEwoJQJ4cvguy7MJ5gD:b-qqctpt) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae10b186b33694666e036b3f106270de32a13b2c/crates/starknet_state_sync/src/test.rs#L342)):*
> ```XML
>     assert_eq!(get_storage_at_result, Err(StateSyncError::ContractNotFound(address)));
> 
>     // Check that calling the functions below with a non existing adress returns contract not found
> ```

Put the same comment you did in get_storage_at plus my suggestion

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2886)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/starknet_state_sync/src/test.rs` line 327 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEwoMb39UxB0t8zSuzn:-OEyIFII6mtzPTwoo26X:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae10b186b33694666e036b3f106270de32a13b2c/crates/starknet_state_sync/src/test.rs#L327)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add to the end of the sentence ", even though the state diff is corrupt and contains this storage"
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync/src/test.rs` line 342 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-OEwoJQJ4cvguy7MJ5gC:-OEyIFZ_B5RsJfdfJQpb:b-z4dsrn) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae10b186b33694666e036b3f106270de32a13b2c/crates/starknet_state_sync/src/test.rs#L342)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Put the same comment you did in get_storage_at plus my suggestion
</blockquote></details>

Added this to the comment above, thought it looked better

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-:-OFMC8r24Fb4TXHrpzzq:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

**Review by noamsp-starkware — COMMENTED** [review]
> Dismissed @ShahakShama from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2886)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2886#-:-OFMm3TrCcifB1p9iXeS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)

**Pull request merged**
