### PR TITLE
build: regression test crate

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/945)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
* **#945** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/945?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by aner-starkware** [comment]
*[`crates/gateway/src/lib.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/945#-O7Tpgk_4w4QmhHkePdi:-O7Tpgka2sBYm2xB6yAb:b-foggtz) ([raw file](https://github.com/starkware-libs/sequencer/blob/63df357b3559313295b1311c5b7dbb7916c25706/crates/gateway/src/lib.rs#L8)):*
> ```XML
> pub mod gateway;
> mod rpc_objects;
> pub mod rpc_state_reader;
> ```

I'm not sure it's desirable to change to `pub` just for testing purposes.



_Code quote:_
```XML
pub mod rpc_state_reader;
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/945)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)

___
*[`crates/gateway/src/lib.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/945#-O7Tpgk_4w4QmhHkePdi:-O7Ybo8TCTjyPe7wl13u:b-qetxqa) ([raw file](https://github.com/starkware-libs/sequencer/blob/63df357b3559313295b1311c5b7dbb7916c25706/crates/gateway/src/lib.rs#L8)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

@dorimedini-starkware 
what do you think?
</blockquote></details>

if the GW team is fine with including this module as part of "public API", then I have no issue with it.
changing to `pub` just means that the devs "commit to maintaining API".
if the GW crate won't be published; then it's only a question of "commit to fixing issues in other workspace crates if we change something in the RPC state reader"

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/945)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)

___
*[`crates/gateway/src/lib.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/945#-O7Tpgk_4w4QmhHkePdi:-O7Z3qPaBgMk0jEZeQoY:b-a9zksr) ([raw file](https://github.com/starkware-libs/sequencer/blob/63df357b3559313295b1311c5b7dbb7916c25706/crates/gateway/src/lib.rs#L8)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if the GW team is fine with including this module as part of "public API", then I have no issue with it.
changing to `pub` just means that the devs "commit to maintaining API".
if the GW crate won't be published; then it's only a question of "commit to fixing issues in other workspace crates if we change something in the RPC state reader"
</blockquote></details>

I think it's ok to share this state reader.
maybe in the future, we should move all state reader implementations to some utils crate.

**Review by aner-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/945)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/945)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier_regression_test/Cargo.toml` line 13 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/945#-O7ciVG_CKi7sV6mzETD:-O7ciVG_CKi7sV6mzETE:b-rekjp0) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c434513fe50d9c54ea6ddd6e3a70d7253f8f15d/crates/blockifier_regression_test/Cargo.toml#L13)):*
> ```TOML
> starknet-types-core.workspace = true
> starknet_api = { workspace = true }
> starknet_gateway = { workspace = true }
> ```

why object-notation?



_Suggestion:_
```TOML
blockifier.workspace = true
starknet-types-core.workspace = true
starknet_api.workspace = true
starknet_gateway.workspace = true
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/945)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_regression_test/Cargo.toml` line 13 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/945#-O7ciVG_CKi7sV6mzETD:-O7clQfk7bA5Lq6c-_10:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c434513fe50d9c54ea6ddd6e3a70d7253f8f15d/crates/blockifier_regression_test/Cargo.toml#L13)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why object-notation?
</blockquote></details>

Done.

**Pull request merged**
