### PR TITLE
chore(mempool_node): add component replacer for servers

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #1111
- #1110
- #1109
- #1103
- #1102
- #1101
- #1100
- #1099
- #1098
- #1097
- #1096
- #1090
- #1089
- #1088
- #1058 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1058)

### CODE REVIEW

**Review by lev-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1058)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_server/definitions.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1058#-O7y14-iEGgxoHAkqCSf:-O7y14-iEGgxoHAkqCSg:bcj32q0) ([raw file](https://github.com/starkware-libs/sequencer/blob/dacc2d5c9c1fe9d51bcf5471076adf696e245959/crates/mempool_infra/src/component_server/definitions.rs#L36)):*
> ```XML
>     InternalError,
> }
> ```

Try to define only in test compilation.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1058)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/mempool_infra/src/component_server/definitions.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1058#-O7y14-iEGgxoHAkqCSf:-O81e-Ut26BDdyd66Hxz:bayvoar) ([raw file](https://github.com/starkware-libs/sequencer/blob/dda842d7bf734b456c06da7b64e3d834d9bd2c5a/crates/mempool_infra/src/component_server/definitions.rs#L36)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

Try to define only in test compilation.
</blockquote></details>

Added a todo (in a later pr).

**Review by lev-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1058)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by lev-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1058#-:-O81gBTh5LAyArwk0fmW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#1096](https://github.com/starkware-libs/sequencer/pull/1096)

**Pull request closed without merging**
