### PR TITLE
test(blockifier): intermediate with_attr error message

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/630)

### CODE REVIEW

**Comment by aner-starkware** [comment]
*[`crates/blockifier/feature_contracts/cairo0/test_contract.cairo` line 170 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/630#-O5NqC9C3zlJiyCt_bXx:-O5NqC9C3zlJiyCt_bXy:brvkomv) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d5adef8e88abb4fc16256bda9ebbe3c19dbe214/crates/blockifier/feature_contracts/cairo0/test_contract.cairo#L170)):*
> ```Cairo
> @external
> func test_call_contract_with_attr_error_msg{syscall_ptr: felt*}(
>     contract_address: felt, function_selector: felt, calldata_len: felt, calldata: felt*
> ```

@dorimedini-starkware is there a way to hardcode the variables here? I want to call `call_contract` with the current contract and the function `fail`.



_Code quote:_
```Cairo
contract_address: felt, function_selector: felt, calldata_len: felt, calldata: felt*
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/630)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/blockifier/feature_contracts/cairo0/test_contract.cairo` line 170 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/630#-O5NqC9C3zlJiyCt_bXx:-O5Nqy03AK0q6KDhg2Xg:b5ps5c8) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d5adef8e88abb4fc16256bda9ebbe3c19dbe214/crates/blockifier/feature_contracts/cairo0/test_contract.cairo#L170)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

@dorimedini-starkware is there a way to hardcode the variables here? I want to call `call_contract` with the current contract and the function `fail`.
</blockquote></details>

1. you shouldn't hard-code the address, it depends on the executing code (to which address is it deployed?)
2. selector and calldata - you can probably hard-code, yes
___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/630#-O5Nqndu3g9e0ym2cz03:-O5Nqndu3g9e0ym2cz04:b-nasdui) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d5adef8e88abb4fc16256bda9ebbe3c19dbe214/crates/blockifier/src/execution/stack_trace_test.rs#L116)):*
> ```XML
> Unknown location (pc=0:{call_location})
> Error message: Be aware of failure ahead...
> Unknown location (pc=0:{entry_point_location})
> ```

shouldn't it be here...?



_Suggestion:_
```XML
Error message: Be aware of failure ahead...
Error at pc=0:37:
Cairo traceback (most recent call last):
Unknown location (pc=0:{call_location})
Unknown location (pc=0:{entry_point_location})
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/630#-:-O5SMZPb2mdRI6B4nOlg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/630)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
