### PR TITLE
feat(sequencing): allow a streamed proposal channel on top of existing

### PR DESCRIPTION
**Pull request by guy-starkware**
This is part of a series of PRs to integrate streaming of consensus proposals. 
It adds the streaming channels but does not connect them to block building or validation, yet.

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 23 files at r1, 1 of 1 files at r2, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2262)* status: all files reviewed, 9 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCmJMTV--Mtrc_DvrNU:-OCmJMTV--Mtrc_DvrNV:bs76nhs) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs#L42)):*
> ```XML
>     storage_reader: StorageReader,
>     network_broadcast_client: BroadcastTopicClient<ConsensusMessage>,
>     _network_proposal_sender: mpsc::Sender<(u64, mpsc::Receiver<ProposalPart>)>,
> ```

Why pass it in if you don't use it. I think this is the same as above. Better to start with actual support which can be tested.



_Code quote:_
```XML
    _network_proposal_sender: mpsc::Sender<(u64, mpsc::Receiver<ProposalPart>)>,
```
___
*[`crates/papyrus_node/src/run.rs` line 54 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCm2Zc46zi7ZZNwQTwh:-OCm2Zc5DuHbfdZ5wjO6:bhz415m) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/papyrus_node/src/run.rs#L54)):*
> ```XML
> // TODO: Consider moving to a more general place.
> const GENESIS_HASH: &str = "0x0";
> pub const NETWORK_TOPIC: &str = "consensus_proposals";
> ```

Are you going to move this to the config in a later PR?

https://github.com/starkware-libs/sequencer/blob/f5304b7a26d9c3005948e642d39b29fc225631e9/crates/sequencing/papyrus_consensus/src/config.rs#L25



_Suggestion:_
```XML
pub const CONSENSUS_PROPOSALS_TOPIC: &str = "consensus_proposals";
```
___
*[`crates/papyrus_node/src/run.rs` line 198 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCm3afECJbeE5kdfaVP:-OCm3afECJbeE5kdfaVQ:b-rcg70a) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/papyrus_node/src/run.rs#L198)):*
> ```XML
>     } = proposal_network_channels;
> 
>     let (outbound_internal_sender, inbound_internal_receiver, _) =
> ```

In another PR I'd like us to hold onto this handle. That way if there's an error it will shut down the node with an error message like the other handles. Options I see:
1. separate fn to spawn stream handle
2. return 2 handles from this fn
3. have the handle here contain both the consensus and stream futures

https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/papyrus_node/src/run.rs#L427



_Code quote:_
```XML
_
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCmJjuLC-I6CwPfPQM0:-OCmJjuM6zccJ5c2xoU5:b-ublz99) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L67)):*
> ```XML
>     current_height: Option<BlockNumber>,
>     network_broadcast_client: BroadcastTopicClient<ProposalPart>,
>     _outbound_proposal_sender: mpsc::Sender<(u64, mpsc::Receiver<ProposalPart>)>,
> ```

Same comment about no usage.



_Code quote:_
```XML
    _outbound_proposal_sender: mpsc::Sender<(u64, mpsc::Receiver<ProposalPart>)>,
```
___
*[`crates/papyrus_protobuf/src/consensus.rs` line 117 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCmIdLRDLNwLRqXYzuc:-OCmIdLRDLNwLRqXYzud:b-1x0lwr) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/papyrus_protobuf/src/consensus.rs#L117)):*
> ```XML
>                 expected: "Init",
>                 got: "Transactions or Fin",
>             }),
> ```

I feel like `value_as_str` covers `got` but with more detail. Maybe put `expected` first though, since it'll be easier to read if the long one is last in the line.



_Suggestion:_
```XML
            ProposalPart::Init(init) => Ok(init),
            _ => Err(ProtobufConversionError::WrongEnumVariant {
                type_description: "ProposalPart",
                value_as_str: format!("{:?}", self),
                expected: "Init",
            }),
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 96 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCmJsf4DrQ-WqMbwXtz:-OCmJsf4DrQ-WqMbwXu-:b-olf9nb) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L96)):*
> ```XML
>     } = subscriber_channels;
>     let (outbound_internal_sender, _inbound_internal_receiver, _) =
>         StreamHandler::get_channels(inbound_network_receiver, outbound_network_sender);
> ```

Seems to repeat a bunch, can we move to a fn?



_Code quote:_
```XML
    let TestSubscriberChannels { mock_network: _mock_network, subscriber_channels } =
        mock_register_broadcast_topic().expect("Failed to create mock network");
    let BroadcastTopicChannels {
        broadcasted_messages_receiver: inbound_network_receiver,
        broadcast_topic_client: outbound_network_sender,
    } = subscriber_channels;
    let (outbound_internal_sender, _inbound_internal_receiver, _) =
        StreamHandler::get_channels(inbound_network_receiver, outbound_network_sender);
```
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 117 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCmIlXi4Ka02UhdwJLj:-OCmIlXi4Ka02UhdwJLk:b5v2in8) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/sequencing/papyrus_consensus/src/manager.rs#L117)):*
> ```XML
>         proposal_receiver: &mut mpsc::Receiver<mpsc::Receiver<ContextT::ProposalPart>>,
>     ) -> Result<Decision, ConsensusError>
>     where
> ```

so this is not used anywhere?

I tend to prefer an inside-out approach. Where the usage of this streaming is implemented and then in `run_consensus` we pass `pending` or whatever. This allows us to actually have usage for this before we start adding this "piping".
1. Add usage in manager and callers can pass an "empty" value
2. Add piping like here
3. Remove old Proposal support



_Code quote:_
```XML
        broadcast_channels: &mut BroadcastConsensusMessageChannel,
        proposal_receiver: &mut mpsc::Receiver<mpsc::Receiver<ContextT::ProposalPart>>,
    ) -> Result<Decision, ConsensusError>
    where
```
___
*[`crates/starknet_consensus_manager/src/consensus_manager.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCmKP8Q4EaOsBMx96EL:-OCmKP8Q4EaOsBMx96EM:bt09cn3) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/starknet_consensus_manager/src/consensus_manager.rs#L67)):*
> ```XML
>         } = proposals_broadcast_channels;
> 
>         let (outbound_internal_sender, inbound_internal_receiver, _) =
> ```

please add this to the select below.



_Code quote:_
```XML
_
```
___
*[`crates/starknet_api/src/transaction.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCmK0fY61ljhSloypOv:-OCmK0fY61ljhSloypOw:bb76mu4) ([raw file](https://github.com/starkware-libs/sequencer/blob/e5576a45817ff938f1cc659d168422bd155d63cd/crates/starknet_api/src/transaction.rs#L165)):*
> ```XML
> 
> macro_rules! implement_v3_tx_getters {
>     ($(($field:ident, $field_type:ty)),*) => {
> ```

Why?



_Code quote:_
```XML
pub struct TransactionOptions {
    /// Transaction that shouldn't be broadcasted to StarkNet. For example, users that want to
    /// test the execution result of a transaction without the risk of it being rebroadcasted (the
    /// signature will be different while the execution remain the same). Using this flag will
    /// modify the transaction version by setting the 128-th bit to 1.
    pub only_query: bool,
}

macro_rules! implement_v3_tx_getters {
    ($(($field:ident, $field_type:ty)),*) => {
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2262)* status: all files reviewed, 9 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/papyrus_node/src/run.rs` line 54 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCm2Zc46zi7ZZNwQTwh:-OCmWa506hTqlqzjvcR-:b-jzog1q) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/papyrus_node/src/run.rs#L54)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Are you going to move this to the config in a later PR?

https://github.com/starkware-libs/sequencer/blob/f5304b7a26d9c3005948e642d39b29fc225631e9/crates/sequencing/papyrus_consensus/src/config.rs#L25
</blockquote></details>

Yes. I added a TODO. 
___
*[`crates/papyrus_node/src/run.rs` line 198 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCm3afECJbeE5kdfaVP:-OCmWku20bdcMFSUT1DK:b7szzm4) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/papyrus_node/src/run.rs#L198)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

In another PR I'd like us to hold onto this handle. That way if there's an error it will shut down the node with an error message like the other handles. Options I see:
1. separate fn to spawn stream handle
2. return 2 handles from this fn
3. have the handle here contain both the consensus and stream futures

https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/papyrus_node/src/run.rs#L427
</blockquote></details>

I'm not sure exactly how you would like to propagate the errors, but we can talk about it offline. In the meantime I put a TODO on it. 
___
*[`crates/papyrus_protobuf/src/consensus.rs` line 117 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCmIdLRDLNwLRqXYzuc:-OCmXaYeDhGrUvYy1uz7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/papyrus_protobuf/src/consensus.rs#L117)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I feel like `value_as_str` covers `got` but with more detail. Maybe put `expected` first though, since it'll be easier to read if the long one is last in the line.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 117 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCmIlXi4Ka02UhdwJLj:-OCmXdN43U_uZ_ejFH8L:b-da48yh) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/sequencing/papyrus_consensus/src/manager.rs#L117)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

so this is not used anywhere?

I tend to prefer an inside-out approach. Where the usage of this streaming is implemented and then in `run_consensus` we pass `pending` or whatever. This allows us to actually have usage for this before we start adding this "piping".
1. Add usage in manager and callers can pass an "empty" value
2. Add piping like here
3. Remove old Proposal support
</blockquote></details>

Let's discuss with Dan. 
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCmJMTV--Mtrc_DvrNU:-OCmXhgrBQivD7C7Ajg_:b-da48yh) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs#L42)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why pass it in if you don't use it. I think this is the same as above. Better to start with actual support which can be tested.
</blockquote></details>

Let's discuss with Dan. 
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCmJjuLC-I6CwPfPQM0:-OCmXjwKDsCgvKNxaebv:bbfhety) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L67)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Same comment about no usage.
</blockquote></details>

Same as above. 
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 96 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCmJsf4DrQ-WqMbwXtz:-OCm_GGZ-cW80isx4qHT:b9vf7pw) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L96)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Seems to repeat a bunch, can we move to a fn?
</blockquote></details>

Good idea! 
___
*[`crates/starknet_api/src/transaction.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCmK0fY61ljhSloypOv:-OCm_Jzh5_Mu9rqp-c77:b-5s1hfr) ([raw file](https://github.com/starkware-libs/sequencer/blob/e5576a45817ff938f1cc659d168422bd155d63cd/crates/starknet_api/src/transaction.rs#L165)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why?
</blockquote></details>

I think there was something weird going on with the auto merging, I thought I fixed it, probably missed the comments.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2262)* status: all files reviewed, 5 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/papyrus_node/src/run.rs` line 198 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCm3afECJbeE5kdfaVP:-OCn71xU8D6ayyUzBV0U:b-f0t49r) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/papyrus_node/src/run.rs#L198)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

I'm not sure exactly how you would like to propagate the errors, but we can talk about it offline. In the meantime I put a TODO on it.
</blockquote></details>

Ok, remind me next week to look into this
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 96 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCmJsf4DrQ-WqMbwXtz:-OCn78SD-oqYf1SITtzj:botgt4q) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L96)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

Good idea!
</blockquote></details>

please remove commented code

**Review by matan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2262)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Comment by dan-starkware** [comment]
*[`crates/papyrus_node/src/run.rs` line 206 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCtewZeAdzwCoo4MdC8:-OCtewZeAdzwCoo4MdC9:b30wgf5) ([raw file](https://github.com/starkware-libs/sequencer/blob/5f06879176395cc6cfeb68979c588763b8cef4a0/crates/papyrus_node/src/run.rs#L206)):*
> ```XML
>         storage_reader.clone(),
>         network_channels.broadcast_topic_client.clone(),
>         // outbound_network_sender.clone(),
> ```

Please remove later



_Code quote:_
```XML
 // outbound_network_sender.clone(),
```

**Review by matan-starkware — COMMENTED** [review]
> Reviewed 9 of 10 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2262)* status: 24 of 25 files reviewed, all discussions resolved (waiting on @guy-starkware)

**Review by matan-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2262)* status: 24 of 25 files reviewed, all discussions resolved (waiting on @guy-starkware)

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2262)* status: 24 of 25 files reviewed, all discussions resolved (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 96 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2262#-OCmJsf4DrQ-WqMbwXtz:-OCnVP4a3S3M2x0WeE4f:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fd11f327fba57134313e39c185960e7140a552/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L96)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

please remove commented code
</blockquote></details>

Done.

**Review by guy-starkware — COMMENTED** [review]
> Reviewed 2 of 23 files at r1, 7 of 13 files at r3, 3 of 7 files at r4, 1 of 2 files at r5, 9 of 10 files at r6, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2262)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Review by guy-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2262)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Pull request merged**
