### PR TITLE
feat(batcher): add trait for getting txs

### PR DESCRIPTION
**Pull request by alonh5**

### CODE REVIEW

**Comment by alonh5** [comment]
* **#1697** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1697?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1697)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @alonh5, @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWCBN_5BFgIRXMCNW_:-OAWCBN_5BFgIRXMCNWa:bh30zim) ([raw file](https://github.com/starkware-libs/sequencer/blob/e91083d4eda84f203dd55a6bf85854a73adfb727/crates/batcher/src/proposal_manager.rs#L66)):*
> ```XML
> 
> #[derive(Clone, Debug, Error)]
> pub enum GetTransactionError {
> ```

I think that the convention is usually to call the error by the name of the object.



_Suggestion:_
```XML
pub enum TransactionGetterError
```
___
*[`crates/batcher/src/proposal_manager.rs` line 311 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWDRs72FqfbvTmp__m:-OAWDRs72FqfbvTmp__n:b9ib8dl) ([raw file](https://github.com/starkware-libs/sequencer/blob/e91083d4eda84f203dd55a6bf85854a73adfb727/crates/batcher/src/proposal_manager.rs#L311)):*
> ```XML
> }
> 
> pub struct BuildTransactionGetter {
> ```

I think the naming should be Propose and Validate, since Build is actually a common functionality between the two.



_Suggestion:_
```XML
ProposeBlockTransactionGetter
```
___
*[`crates/batcher/src/proposal_manager.rs` line 320 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWBlfW82ILnpZslqmz:-OAWBlfW82ILnpZslqn-:b-k8a55h) ([raw file](https://github.com/starkware-libs/sequencer/blob/e91083d4eda84f203dd55a6bf85854a73adfb727/crates/batcher/src/proposal_manager.rs#L320)):*
> ```XML
>         Ok(self.mempool_client.get_txs(n_txs).await?)
>     }
> }
> ```

move this to a new file transaction_getter.rs



_Code quote:_
```XML
#[async_trait]
pub trait TransactionGetter: Send + Sync {
    async fn get_txs(&self, n_txs: usize) -> Result<Vec<Transaction>, GetTransactionError>;
}

pub struct BuildTransactionGetter {
    pub mempool_client: SharedMempoolClient,
}

#[async_trait]
impl TransactionGetter for BuildTransactionGetter {
    async fn get_txs(&self, n_txs: usize) -> Result<Vec<Transaction>, GetTransactionError> {
        Ok(self.mempool_client.get_txs(n_txs).await?)
    }
}
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1697)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWCBN_5BFgIRXMCNW_:-OAWYK7ZE81XIP8kBHfj:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e91083d4eda84f203dd55a6bf85854a73adfb727/crates/batcher/src/proposal_manager.rs#L66)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think that the convention is usually to call the error by the name of the object.
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 311 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWDRs72FqfbvTmp__m:-OAWYN051Yt57-XWV0vF:b-xvohb6) ([raw file](https://github.com/starkware-libs/sequencer/blob/e91083d4eda84f203dd55a6bf85854a73adfb727/crates/batcher/src/proposal_manager.rs#L311)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think the naming should be Propose and Validate, since Build is actually a common functionality between the two.
</blockquote></details>

You're right. Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 320 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWBlfW82ILnpZslqmz:-OAWZnSR9PqBcwlxh_P2:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e91083d4eda84f203dd55a6bf85854a73adfb727/crates/batcher/src/proposal_manager.rs#L320)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

move this to a new file transaction_getter.rs
</blockquote></details>

Done.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1697)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @alonh5, @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 307 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWWpUB-awyNIJrD_TH:-OAWWpUB-awyNIJrD_TI:b-ct1noz) ([raw file](https://github.com/starkware-libs/sequencer/blob/e91083d4eda84f203dd55a6bf85854a73adfb727/crates/batcher/src/proposal_manager.rs#L307)):*
> ```XML
> 
> #[async_trait]
> pub trait TransactionGetter: Send + Sync {
> ```

Consider: `TransactionProvider`



_Code quote:_
```XML
TransactionGetter
```
___
*[`crates/batcher/src/proposal_manager.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWauoD8eHwuZuh33K2:-OAWauoE2q583VTe63jg:bc8bf9o) ([raw file](https://github.com/starkware-libs/sequencer/blob/e91083d4eda84f203dd55a6bf85854a73adfb727/crates/batcher/src/proposal_manager.rs#L308)):*
> ```XML
> #[async_trait]
> pub trait TransactionGetter: Send + Sync {
>     async fn get_txs(&self, n_txs: usize) -> Result<Vec<Transaction>, GetTransactionError>;
> ```

Note that the 2 implementations will have very different errors.
Maybe there should be some kind of abstraction to allow us define 2 different error types, on for each getter implementation.



_Code quote:_
```XML
GetTransactionError
```
___
*[`crates/batcher/src/proposal_manager.rs` line 311 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWDRs72FqfbvTmp__m:-OAWXMwu-2l4-mYLJXQI:brwtrm3) ([raw file](https://github.com/starkware-libs/sequencer/blob/e91083d4eda84f203dd55a6bf85854a73adfb727/crates/batcher/src/proposal_manager.rs#L311)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think the naming should be Propose and Validate, since Build is actually a common functionality between the two.
</blockquote></details>

I actually think the name should indicate the source of transactions and not the use case in which it it used.
Maybe `MempoolTransactionGetter` and `ConsensusTransactionGetter`.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1697)* status: all files reviewed, 10 unresolved discussions (waiting on @alonh5, @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWf5dA7cq0AqXKlDIv:-OAWf5dBDO2VtZsFVkmj:bq2hhr8) ([raw file](https://github.com/starkware-libs/sequencer/blob/fce03f20f8a4c61d2b8816023913ccd05c9f0ad8/crates/batcher/src/block_builder.rs#L69)):*
> ```XML
> 
> /// The BlockBuilderTrait is responsible for building a new block from transactions provided in
> /// tx_stream. The block building will stop at time deadline.
> ```

Please update the comment.



_Code quote:_
```XML
/// The BlockBuilderTrait is responsible for building a new block from transactions provided in
/// tx_stream. The block building will stop at time deadline.
```
___
*[`crates/batcher/src/block_builder.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWfCCa5m1jVKJCOgX7:-OAWfCCa5m1jVKJCOgX8:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/fce03f20f8a4c61d2b8816023913ccd05c9f0ad8/crates/batcher/src/block_builder.rs#L77)):*
> ```XML
>         &self,
>         deadline: tokio::time::Instant,
>         tx_getter: Box<dyn TransactionProvider>,
> ```





_Suggestion:_
```XML
tx_provider
```
___
*[`crates/batcher/src/block_builder_test.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWfLEh-hOsOSO8Tl76:-OAWfLEh-hOsOSO8Tl77:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/fce03f20f8a4c61d2b8816023913ccd05c9f0ad8/crates/batcher/src/block_builder_test.rs#L54)):*
> ```XML
> 
>     // Create the mock transaction executor, mock mempool client and the expected block artifacts.
>     let (mock_transaction_executor, tx_getter, expected_block_artifacts) =
> ```





_Suggestion:_
```XML
tx_provider
```
___
*[`crates/batcher/src/block_builder_test.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWfOTI8Op5wNv46t3c:-OAWfOTI8Op5wNv46t3d:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/fce03f20f8a4c61d2b8816023913ccd05c9f0ad8/crates/batcher/src/block_builder_test.rs#L115)):*
> ```XML
>     );
> 
>     let tx_getter = ProposeTransactionProvider { mempool_client: Arc::new(mock_mempool_client) };
> ```





_Suggestion:_
```XML
tx_provider
```
___
*[`crates/batcher/src/proposal_manager.rs` line 169 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWfjcNAq7iHSlpRE1w:-OAWfjcNAq7iHSlpRE1x:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/fce03f20f8a4c61d2b8816023913ccd05c9f0ad8/crates/batcher/src/proposal_manager.rs#L169)):*
> ```XML
>             self.block_builder_factory.create_block_builder(height, retrospective_block_hash)?;
> 
>         let tx_getter = ProposeTransactionProvider { mempool_client: self.mempool_client.clone() };
> ```





_Suggestion:_
```XML
tx_provider
```

**Review by yair-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1697)* status: all files reviewed, 12 unresolved discussions (waiting on @alonh5, @ArniStarkware, and @Yael-Starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 169 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWfDG_0j8abjr4PGcY:-OAWfDG_0j8abjr4PGcZ:b5segg6) ([raw file](https://github.com/starkware-libs/sequencer/blob/fce03f20f8a4c61d2b8816023913ccd05c9f0ad8/crates/batcher/src/proposal_manager.rs#L169)):*
> ```XML
>             self.block_builder_factory.create_block_builder(height, retrospective_block_hash)?;
> 
>         let tx_getter = ProposeTransactionProvider { mempool_client: self.mempool_client.clone() };
> ```

Consider moving the creation of the tx_getter to the batcher (I think it will look better when implementing the `validate_proposal`)



_Code quote:_
```XML
let tx_getter = ProposeTransactionProvider { mempool_client: self.mempool_client.clone() };
```
___
*[`crates/batcher/src/transaction_provider.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWg14Y1IQcFmhQAERR:-OAWg14Y1IQcFmhQAERS:b-f6e5mw) ([raw file](https://github.com/starkware-libs/sequencer/blob/fce03f20f8a4c61d2b8816023913ccd05c9f0ad8/crates/batcher/src/transaction_provider.rs#L14)):*
> ```XML
> #[async_trait]
> pub trait TransactionProvider: Send + Sync {
>     async fn get_txs(&self, n_txs: usize) -> Result<Vec<Transaction>, TransactionProviderError>;
> ```

Consider making this a member of the struct instead of passing it every time



_Code quote:_
```XML
n_txs: usize
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1697)* status: all files reviewed, 12 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWf5dA7cq0AqXKlDIv:-OAWhMB31eE_ClcwRt55:bnputky) ([raw file](https://github.com/starkware-libs/sequencer/blob/fce03f20f8a4c61d2b8816023913ccd05c9f0ad8/crates/batcher/src/block_builder.rs#L69)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please update the comment.
</blockquote></details>

Done. Thanks
___
*[`crates/batcher/src/block_builder.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWfCCa5m1jVKJCOgX7:-OAWhAph1Juj0-Td-ioN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fce03f20f8a4c61d2b8816023913ccd05c9f0ad8/crates/batcher/src/block_builder.rs#L77)):*
> ```XML
>         &self,
>         deadline: tokio::time::Instant,
>         tx_getter: Box<dyn TransactionProvider>,
> ```

Done.
___
*[`crates/batcher/src/block_builder_test.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWfLEh-hOsOSO8Tl76:-OAWhPsB2uXtHumsvGM9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fce03f20f8a4c61d2b8816023913ccd05c9f0ad8/crates/batcher/src/block_builder_test.rs#L54)):*
> ```XML
> 
>     // Create the mock transaction executor, mock mempool client and the expected block artifacts.
>     let (mock_transaction_executor, tx_getter, expected_block_artifacts) =
> ```

Done.
___
*[`crates/batcher/src/block_builder_test.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWfOTI8Op5wNv46t3c:-OAWhQWF1pbPdORrB_2B:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fce03f20f8a4c61d2b8816023913ccd05c9f0ad8/crates/batcher/src/block_builder_test.rs#L115)):*
> ```XML
>     );
> 
>     let tx_getter = ProposeTransactionProvider { mempool_client: Arc::new(mock_mempool_client) };
> ```

Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWauoD8eHwuZuh33K2:-OAWhW6L0C91flQ24wmT:b-hl050n) ([raw file](https://github.com/starkware-libs/sequencer/blob/e91083d4eda84f203dd55a6bf85854a73adfb727/crates/batcher/src/proposal_manager.rs#L308)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Note that the 2 implementations will have very different errors.
Maybe there should be some kind of abstraction to allow us define 2 different error types, on for each getter implementation.
</blockquote></details>

I thought TransactionProviderError would wrap any error it could get (MempoolClientError, L1Provider Error, ConsensusSomethingError, etc.) and also have other "local" errors if we need any. Why do we need another error type?
___
*[`crates/batcher/src/proposal_manager.rs` line 311 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWDRs72FqfbvTmp__m:-OAWiJG2-CmrVMoY5Vdx:b-6cbmuz) ([raw file](https://github.com/starkware-libs/sequencer/blob/e91083d4eda84f203dd55a6bf85854a73adfb727/crates/batcher/src/proposal_manager.rs#L311)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I actually think the name should indicate the source of transactions and not the use case in which it it used.
Maybe `MempoolTransactionGetter` and `ConsensusTransactionGetter`.
</blockquote></details>

The former will also get txs from the L1 provider. Generally what defines them for users is what they are used for (proposing or validating). The naming is part of the "containing" of that logic. wdyt?
___
*[`crates/batcher/src/transaction_provider.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWg14Y1IQcFmhQAERR:-OAWjrjJ6aVzBl7RNzaP:b-oyg0d) ([raw file](https://github.com/starkware-libs/sequencer/blob/fce03f20f8a4c61d2b8816023913ccd05c9f0ad8/crates/batcher/src/transaction_provider.rs#L14)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider making this a member of the struct instead of passing it every time
</blockquote></details>

Might we want to change the number between calls?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1697)* status: 2 of 5 files reviewed, 12 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 307 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWWpUB-awyNIJrD_TH:-OAWkgoP8qd7JlDyXdfZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e91083d4eda84f203dd55a6bf85854a73adfb727/crates/batcher/src/proposal_manager.rs#L307)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Consider: `TransactionProvider`
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 169 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWfjcNAq7iHSlpRE1w:-OAWkOTgCLzA-Ux7qd3D:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fce03f20f8a4c61d2b8816023913ccd05c9f0ad8/crates/batcher/src/proposal_manager.rs#L169)):*
> ```XML
>             self.block_builder_factory.create_block_builder(height, retrospective_block_hash)?;
> 
>         let tx_getter = ProposeTransactionProvider { mempool_client: self.mempool_client.clone() };
> ```

Done.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1697)* status: 2 of 5 files reviewed, 12 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 169 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWfDG_0j8abjr4PGcY:-OAWlM0uA1BdCmsLY_aT:b-ogt64m) ([raw file](https://github.com/starkware-libs/sequencer/blob/fce03f20f8a4c61d2b8816023913ccd05c9f0ad8/crates/batcher/src/proposal_manager.rs#L169)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider moving the creation of the tx_getter to the batcher (I think it will look better when implementing the `validate_proposal`)
</blockquote></details>

Good idea, this requires a small refactor (removing the mempool client from the proposal manager etc.).
I'll do it in another PR.

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1697)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5, @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWauoD8eHwuZuh33K2:-OAWrNXp146IRjsZzNA2:btwwh66) ([raw file](https://github.com/starkware-libs/sequencer/blob/e91083d4eda84f203dd55a6bf85854a73adfb727/crates/batcher/src/proposal_manager.rs#L308)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I thought TransactionProviderError would wrap any error it could get (MempoolClientError, L1Provider Error, ConsensusSomethingError, etc.) and also have other "local" errors if we need any. Why do we need another error type?
</blockquote></details>

Not critical, I'm ok with also one error type that includes all.
I just think it's a bit weird that part of the trait definition is specific to the different trait implementations.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1697)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWauoD8eHwuZuh33K2:-OAWtBa4DTD4qOC9Z_Oe:bs3gwo5) ([raw file](https://github.com/starkware-libs/sequencer/blob/e91083d4eda84f203dd55a6bf85854a73adfb727/crates/batcher/src/proposal_manager.rs#L308)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Not critical, I'm ok with also one error type that includes all.
I just think it's a bit weird that part of the trait definition is specific to the different trait implementations.
</blockquote></details>

Okay, let's leave it like this then. It's simpler
___
*[`crates/batcher/src/transaction_provider.rs` line 24 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWrxEFA5UtmeJtn5zc:-OAWsoHfCwvahOIcarcO:b-hzmksr) ([raw file](https://github.com/starkware-libs/sequencer/blob/08e5958228027f24b37958e85c20068077416c95/crates/batcher/src/transaction_provider.rs#L24)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

we want to limit the number of L1 transactions per block.
how would we know how many L1 transactions to ask for here?
</blockquote></details>

This struct will have to have more information, it's part of the TODO :)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1697)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/batcher/src/transaction_provider.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1697#-OAWg14Y1IQcFmhQAERR:-OAX7nhP620e0fY0IUO0:b-jbbby1) ([raw file](https://github.com/starkware-libs/sequencer/blob/fce03f20f8a4c61d2b8816023913ccd05c9f0ad8/crates/batcher/src/transaction_provider.rs#L14)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Might we want to change the number between calls?
</blockquote></details>

Can't see when, but it doesn't matter too much.

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1697)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1697)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
