### PR TITLE
feat(l1_provider): add validate action

### PR DESCRIPTION
**Pull request by giladchase**

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2211)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase)

___
*[`crates/starknet_l1_provider/src/l1_provider_tests.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2211#-OCDILlOBHfDlG219fVb:-OCDILlOBHfDlG219fVc:bqjuw7q) ([raw file](https://github.com/starkware-libs/sequencer/blob/b70390cd730057d3b4ee8276cbfcf60916a3ff33/crates/starknet_l1_provider/src/l1_provider_tests.rs#L26)):*
> ```XML
>     ($tx_hash:expr) => {
>         TransactionHash(StarkHash::from($tx_hash))
>     };
> ```

Nothing similar exists in the repo.?



_Code quote:_
```XML
macro_rules! tx_hash {
    ($tx_hash:expr) => {
        TransactionHash(StarkHash::from($tx_hash))
    };
```
___
*[`crates/starknet_l1_provider/src/lib.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2211#-OCDJFAv1dZ86k66vxJc:-OCDJFAv1dZ86k66vxJd:bbkcitv) ([raw file](https://github.com/starkware-libs/sequencer/blob/b70390cd730057d3b4ee8276cbfcf60916a3ff33/crates/starknet_l1_provider/src/lib.rs#L51)):*
> ```XML
>             ProviderState::Validate => Ok(self.tx_manager.tx_status(tx_hash)),
>             ProviderState::Propose => Err(L1ProviderError::ValidateTransactionConsensusBug),
>             ProviderState::Pending => Err(L1ProviderError::ValidateInPendingState),
> ```

Isn't this also a consensus bug? Who's telling the provider to move from "pending" to "proposer/validator", the consensus?



_Code quote:_
```XML
ProviderState::Pending => Err(L1ProviderError::ValidateInPendingState),
```
___
*[`crates/starknet_l1_provider/src/lib.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2211#-OCDIqTT6z6pNA7kPJAX:-OCDIqTT6z6pNA7kPJAY:bxgyohi) ([raw file](https://github.com/starkware-libs/sequencer/blob/b70390cd730057d3b4ee8276cbfcf60916a3ff33/crates/starknet_l1_provider/src/lib.rs#L127)):*
> ```XML
>             ValidationStatus::AlreadyIncludedOnL2
>         } else {
>             ValidationStatus::ConsumedOnL1OrUnknown
> ```

Do we need (or: can we) differentiate between the two?



_Code quote:_
```XML
ValidationStatus::ConsumedOnL1OrUnknown
```
___
*[`crates/starknet_l1_provider/src/errors.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2211#-OCDJtX20UUMJb2FcNio:-OCDJtX20UUMJb2FcNip:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/b70390cd730057d3b4ee8276cbfcf60916a3ff33/crates/starknet_l1_provider/src/errors.rs#L22)):*
> ```XML
>     )]
>     ValidateInPendingState,
>     #[error("`validate_tx` called while in proposal state")]
> ```





_Suggestion:_
```XML
`validate` called while in `Propose`
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2211)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/starknet_l1_provider/src/l1_provider_tests.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2211#-OCDILlOBHfDlG219fVb:-OCDQWYR0bzCoGOy55VL:b-z9l0gc) ([raw file](https://github.com/starkware-libs/sequencer/blob/b70390cd730057d3b4ee8276cbfcf60916a3ff33/crates/starknet_l1_provider/src/l1_provider_tests.rs#L26)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Nothing similar exists in the repo.?
</blockquote></details>

Nope, but there are plenty of applicable cases: search (case-insensitive) for`TransactionHash(felt`.
We can add a task of moving to SNAPI and use everywhere.
___
*[`crates/starknet_l1_provider/src/lib.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2211#-OCDJFAv1dZ86k66vxJc:-OCDQw5m51BKWVEcdAfE:blb6ane) ([raw file](https://github.com/starkware-libs/sequencer/blob/b70390cd730057d3b4ee8276cbfcf60916a3ff33/crates/starknet_l1_provider/src/lib.rs#L51)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Isn't this also a consensus bug? Who's telling the provider to move from "pending" to "proposer/validator", the consensus?
</blockquote></details>

It _could_ be a consensus bug, but it is more likely due to an unhandled crash (which again could be considered a consensus bug because it didn't unregister the node that crashed?).

But I see yr point, `ValidateTransactionConsensusBug` implies dichotomy, perhaps I'll remove the `ConsensusBug` from the variant name and into the error string ("... likely a consensus bug")?
___
*[`crates/starknet_l1_provider/src/lib.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2211#-OCDIqTT6z6pNA7kPJAX:-OCDRQ8iCkGvVSwYCOIe:b-a96vwj) ([raw file](https://github.com/starkware-libs/sequencer/blob/b70390cd730057d3b4ee8276cbfcf60916a3ff33/crates/starknet_l1_provider/src/lib.rs#L127)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we need (or: can we) differentiate between the two?
</blockquote></details>

Ya thought about it while writing this, here's what came up:
 
Need: not sure, i couldn't find a reason why a validator would care, only for debugging purposes this might help. 

Can: Yes, but in practice only on a best-effort basis. We can either use a cache of consumed txs (which is incomplete since it'll have to be a bounded cache, otherwise we'll run out of memory) ,or synchronesly query the last N L1 blocks, but again, we can't query the whole chain so this is incomplete.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2211)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/starknet_l1_provider/src/lib.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2211#-OCDJFAv1dZ86k66vxJc:-OCDdngZCFtyGNJaq_2C:b-a10lw3) ([raw file](https://github.com/starkware-libs/sequencer/blob/b70390cd730057d3b4ee8276cbfcf60916a3ff33/crates/starknet_l1_provider/src/lib.rs#L51)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

It _could_ be a consensus bug, but it is more likely due to an unhandled crash (which again could be considered a consensus bug because it didn't unregister the node that crashed?).

But I see yr point, `ValidateTransactionConsensusBug` implies dichotomy, perhaps I'll remove the `ConsensusBug` from the variant name and into the error string ("... likely a consensus bug")?
</blockquote></details>

WDYM by "implies dichotomy"?
___
*[`crates/starknet_l1_provider/src/lib.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2211#-OCDIqTT6z6pNA7kPJAX:-OCDeuzaBvLzxZO_KGKz:bmy82rj) ([raw file](https://github.com/starkware-libs/sequencer/blob/b70390cd730057d3b4ee8276cbfcf60916a3ff33/crates/starknet_l1_provider/src/lib.rs#L127)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Ya thought about it while writing this, here's what came up:
 
Need: not sure, i couldn't find a reason why a validator would care, only for debugging purposes this might help. 

Can: Yes, but in practice only on a best-effort basis. We can either use a cache of consumed txs (which is incomplete since it'll have to be a bounded cache, otherwise we'll run out of memory) ,or synchronesly query the last N L1 blocks, but again, we can't query the whole chain so this is incomplete.
</blockquote></details>

Thanks! And by "consumed" you mean, "the L2 block it was included in, got to L1", right?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2211)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/starknet_l1_provider/src/lib.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2211#-OCDJFAv1dZ86k66vxJc:-OCE0PJrEpdqS5QzEBL2:b-115os8) ([raw file](https://github.com/starkware-libs/sequencer/blob/b70390cd730057d3b4ee8276cbfcf60916a3ff33/crates/starknet_l1_provider/src/lib.rs#L51)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYM by "implies dichotomy"?
</blockquote></details>

That a consensus bug is only possible in the `Propose` branch of the match, but technically it's also possible in the `Pending` branch, so maybe the error name is misleading.
___
*[`crates/starknet_l1_provider/src/lib.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2211#-OCDIqTT6z6pNA7kPJAX:-OCE0aVqCaBQ45Mn98P6:b2nhc8k) ([raw file](https://github.com/starkware-libs/sequencer/blob/b70390cd730057d3b4ee8276cbfcf60916a3ff33/crates/starknet_l1_provider/src/lib.rs#L127)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Thanks! And by "consumed" you mean, "the L2 block it was included in, got to L1", right?
</blockquote></details>

Bul

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2211)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/starknet_l1_provider/src/lib.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2211#-OCDJFAv1dZ86k66vxJc:-OCEHSwu2hjezNj2_EDi:bjh1dm3) ([raw file](https://github.com/starkware-libs/sequencer/blob/b70390cd730057d3b4ee8276cbfcf60916a3ff33/crates/starknet_l1_provider/src/lib.rs#L51)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

That a consensus bug is only possible in the `Propose` branch of the match, but technically it's also possible in the `Pending` branch, so maybe the error name is misleading.
</blockquote></details>

Okay, can be revisited later.
___
*[`crates/starknet_l1_provider/src/lib.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2211#-OCDIqTT6z6pNA7kPJAX:-OCEHPeT5aK8S7YPBU3g:bcbtl2y) ([raw file](https://github.com/starkware-libs/sequencer/blob/b70390cd730057d3b4ee8276cbfcf60916a3ff33/crates/starknet_l1_provider/src/lib.rs#L127)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Bul
</blockquote></details>

:dart:

**Pull request merged**
