### PR TITLE
feat(starknet_api): checked mul for gas vector

### PR DESCRIPTION
**Pull request by yoavGrs**

### CODE REVIEW

**Review by nimrod-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2300#-:-OCgvlsd-TtRKIzn57vu:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2300)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/starknet_api/src/execution_resources.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2300#-OCly6xTASZL7L86xlu_:-OCly6xTASZL7L86xlua:b-hii0ou) ([raw file](https://github.com/starkware-libs/sequencer/blob/3faf3f51abeb735544ce8dbe9c9929fa28842809/crates/starknet_api/src/execution_resources.rs#L116)):*
> ```XML
>     }
> 
>     pub fn checked_mul(self, factor: usize) -> Option<Self> {
> ```

convert usize->u64 at the caller location - comply with GasAmount's checked_factor_mul API



_Suggestion:_
```XML
factor: u64
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2300)* status: all files reviewed, 2 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/starknet_api/src/execution_resources.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2300#-OCly_vm4k8DM4KGX32r:-OCly_vm4k8DM4KGX32s:bcmhguw) ([raw file](https://github.com/starkware-libs/sequencer/blob/3faf3f51abeb735544ce8dbe9c9929fa28842809/crates/starknet_api/src/execution_resources.rs#L116)):*
> ```XML
>     }
> 
>     pub fn checked_mul(self, factor: usize) -> Option<Self> {
> ```

for clarity



_Suggestion:_
```XML
checked_scalar_mul
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2300)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/starknet_api/src/execution_resources.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2300#-OCly6xTASZL7L86xlu_:-OD5OgKsDehEXlDckr_h:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3faf3f51abeb735544ce8dbe9c9929fa28842809/crates/starknet_api/src/execution_resources.rs#L116)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

convert usize->u64 at the caller location - comply with GasAmount's checked_factor_mul API
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/execution_resources.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2300#-OCly_vm4k8DM4KGX32r:-OD5OS028CnGofvEzZsT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3faf3f51abeb735544ce8dbe9c9929fa28842809/crates/starknet_api/src/execution_resources.rs#L116)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

for clarity
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2300#-:-ODAcCIP09GmNgPIKvNQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
