### PR TITLE
chore(consensus): add missing tests for consesus messages conversions

### PR DESCRIPTION
**Pull request by guy-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/731)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r4, 1 of 5 files at r5, 1 of 3 files at r7, 5 of 6 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/731)* status: all files reviewed, 1 unresolved discussion (waiting on @guy-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 78 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/731#-O6K_5-K0XYWV27HjPzU:-O6K_5-K0XYWV27HjPzV:b-d59vp4) ([raw file](https://github.com/starkware-libs/sequencer/blob/08ebbf19bf8d277c9f71c6eb49efa27caf80ce57/crates/papyrus_protobuf/src/converters/consensus_test.rs#L78)):*
> ```XML
> 
> #[test]
> fn convert_vote_to_vec_u8_and_back() {
> ```

Why not test Proposal explicitly? Are you assuming the ConsensusMessage test covers this?



_Code quote:_
```XML
fn convert_vote_to_vec_u8_and_back()
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/731)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 78 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/731#-O6K_5-K0XYWV27HjPzU:-O6_BF3N6kfCfcW_jeyg:b-wkdkil) ([raw file](https://github.com/starkware-libs/sequencer/blob/08ebbf19bf8d277c9f71c6eb49efa27caf80ce57/crates/papyrus_protobuf/src/converters/consensus_test.rs#L78)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why not test Proposal explicitly? Are you assuming the ConsensusMessage test covers this?
</blockquote></details>

I wanted to write the same test for all the data types in `papyrus_protobuf/src/converters/consensus.rs`, but not all types implement a conversion into `Vec<u8>`. 
I assume they only convert into protobuf objects (and not into raw bytes) because they are nested inside other structs, so I guess it is less critical to test if they can convert by themselves. 

I could add a test to see the convertion into/from a protobuf message but I am not sure if that's overkill.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/731)* status: all files reviewed, 1 unresolved discussion (waiting on @guy-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 78 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/731#-O6K_5-K0XYWV27HjPzU:-O6oqvQ9AY9qUc_geA__:bf6vl78) ([raw file](https://github.com/starkware-libs/sequencer/blob/08ebbf19bf8d277c9f71c6eb49efa27caf80ce57/crates/papyrus_protobuf/src/converters/consensus_test.rs#L78)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

I wanted to write the same test for all the data types in `papyrus_protobuf/src/converters/consensus.rs`, but not all types implement a conversion into `Vec<u8>`. 
I assume they only convert into protobuf objects (and not into raw bytes) because they are nested inside other structs, so I guess it is less critical to test if they can convert by themselves. 

I could add a test to see the convertion into/from a protobuf message but I am not sure if that's overkill.
</blockquote></details>

So add the convertion to/from `Vec<u8>`

auto_impl_into_and_try_from_vec_u8

**Review by matan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/731)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/731)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @guy-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 128 at r18](https://reviewable.io/reviews/starkware-libs/sequencer/731#-O6pxbca3w0AI45LI-hU:-O6pxbca3w0AI45LI-hV:bhbiqm) ([raw file](https://github.com/starkware-libs/sequencer/blob/f8753327c5cf6bf76265d4a4503f608b0f527271/crates/papyrus_protobuf/src/converters/consensus_test.rs#L128)):*
> ```XML
>             bounds.l2_gas.max_amount = 1;
>         }
>     }
> ```

If there are multiple variants of interest use a match statement. Below is one way to do it. you could also have 3 separate arms like you have here if you prefer.



_Suggestion:_
```XML
    match &mut proposal.transactions[0] {
        Transaction::Declare(DeclareTransaction::V3(DeclareTransactionV3 {
            resource_bounds,
            ..
        }))
        | Transaction::Invoke(InvokeTransaction::V3(InvokeTransactionV3 {
            resource_bounds, ..
        }))
        | Transaction::DeployAccount(DeployAccountTransaction::V3(DeployAccountTransactionV3 {
            resource_bounds,
            ..
        })) => {
            if let ValidResourceBounds::AllResources(ref mut bounds) = resource_bounds {
                bounds.l2_gas.max_amount = 1;
            }
        }
        _ => {}
    }
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r19, 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/731)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @guy-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 117 at r19](https://reviewable.io/reviews/starkware-libs/sequencer/731#-O6tpmJV-E6p4Rf6KwTz:-O6tpmJV-E6p4Rf6KwU-:bpazdxm) ([raw file](https://github.com/starkware-libs/sequencer/blob/f9b72073831e892b43d29d686e8eea7e3ed0485e/crates/papyrus_protobuf/src/converters/consensus_test.rs#L117)):*
> ```XML
>     match transaction {
>         Transaction::Declare(DeclareTransaction::V3(data)) => {
>             data.resource_bounds = ValidResourceBounds::AllResources(Default::default());
> ```

I'm confused, I thought we didn't want to use the default value, but rather to manually set to 1?



_Code quote:_
```XML
            data.resource_bounds = ValidResourceBounds::AllResources(Default::default());
```

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/731)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
