### PR TITLE
chore(blockifier, native_blockifier, starknet_batcher): remove visite…

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
…d PCS

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
Python: https://reviewable.io/reviews/starkware-industries/starkware/36551

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2974#-:-OEz8S8cDAhW8PqRgV9p:bsg7768)* status: 0 of 16 files reviewed, all discussions resolved (waiting on @meship-starkware and @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2974)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2974#-OF0npp05EFvTnQUlL_Z:-OF0npp05EFvTnQUlL__:bdyekmc) ([raw file](https://github.com/starkware-libs/sequencer/blob/2bb9dd745ed23059b3f789e8f3ee7d5e3ae16cb4/crates/blockifier/src/execution/entry_point_execution.rs#L105)):*
> ```XML
>     // Instantiate Cairo runner.
>     let proof_mode = false;
>     let trace_enabled = false;
> ```

Why do we change the trace enable to false?



_Code quote:_
```XML
 let trace_enabled = false;
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2974)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2974#-OF0npp05EFvTnQUlL_Z:-OF0pTm-DWB7zAwrPFee:b-wcahb4) ([raw file](https://github.com/starkware-libs/sequencer/blob/2bb9dd745ed23059b3f789e8f3ee7d5e3ae16cb4/crates/blockifier/src/execution/entry_point_execution.rs#L105)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why do we change the trace enable to false?
</blockquote></details>

@liorgold2 changed it to true just for the visited pcs collection.
I'm reverting his change.

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2974)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
