### PR TITLE
build(fee): tx_resources depend on resource bounds signature

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/455)

### CODE REVIEW

**Comment by nimrod-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/455?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#455** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/455?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#454** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/454?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nimrod-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/455)* status: all files reviewed, 7 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O4FvmZwCTTS819kKwqL:-O4FvmZwCTTS819kKwqM:b-k08jbn) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e23dfffab58008b5c7714e59f1c4b4204057cf3/crates/blockifier/src/fee/actual_cost.rs#L92)):*
> ```XML
>             tx_context.block_context.block_info.use_kzg_da,
>             tx_context.tx_info.has_l2_gas_bounds(),
>         )?;
> ```

maybe `to_gas_vector` should simply borrow the `tx_context`? seems weird, passing three of it's fields explicitly



_Code quote:_
```XML
        let gas = tx_resources.to_gas_vector(
            &tx_context.block_context.versioned_constants,
            tx_context.block_context.block_info.use_kzg_da,
            tx_context.tx_info.has_l2_gas_bounds(),
        )?;
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O4FvP4bCrL_V_NrVd6a:-O4FvP4bCrL_V_NrVd6b:b-p39qx8) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e23dfffab58008b5c7714e59f1c4b4204057cf3/crates/blockifier/src/test_utils/struct_impls.rs#L123)):*
> ```XML
>             &block_context.versioned_constants,
>             block_context.block_info.use_kzg_da,
>             false,
> ```

this should be injected somehow; it's a test util, and we should be able to test both cases



_Code quote:_
```XML
false,
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O4FvVjc1YQdo5-OUBy5:-O4FvVjc1YQdo5-OUBy6:b-ql5eh1) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e23dfffab58008b5c7714e59f1c4b4204057cf3/crates/blockifier/src/transaction/account_transactions_test.rs#L0)):*
see [here](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4FuMRP1vLUNMJ0BorR)
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O4FvYMOE8Dy70YSyLqt:-O4FvYMOE8Dy70YSyLqu:b-ql5eh1) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e23dfffab58008b5c7714e59f1c4b4204057cf3/crates/blockifier/src/transaction/execution_flavors_test.rs#L135)):*
> ```XML
>                 &block_context.versioned_constants,
>                 block_context.block_info.use_kzg_da,
>                 false
> ```

see [here](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4FuMRP1vLUNMJ0BorR)



_Code quote:_
```XML
 false
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O4Fv_aFCAc3igJfqryJ:-O4Fv_aFCAc3igJfqryK:b-pl7040) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e23dfffab58008b5c7714e59f1c4b4204057cf3/crates/blockifier/src/transaction/objects.rs#L116)):*
> ```XML
>     pub fn has_l2_gas_bounds(&self) -> bool {
>         match self {
>             TransactionInfo::Current(context) => context.resource_bounds.0.len() == 3,
> ```

didn't we want to first look into changing this type to an enum?



_Code quote:_
```XML
context.resource_bounds
```
___
*[`crates/blockifier/src/transaction/post_execution_test.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O4FvgCrBNNFxPNgzhzv:-O4FvgCrBNNFxPNgzhzw:b-ql5eh1) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e23dfffab58008b5c7714e59f1c4b4204057cf3/crates/blockifier/src/transaction/post_execution_test.rs#L262)):*
> ```XML
>             &block_context.versioned_constants,
>             block_context.block_info.use_kzg_da,
>             false,
> ```

see [here](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4FuMRP1vLUNMJ0BorR)



_Code quote:_
```XML
false,
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O4Fvh_O7L7Y_OXgDo2O:-O4Fvh_O7L7Y_OXgDo2P:b-ql5eh1) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e23dfffab58008b5c7714e59f1c4b4204057cf3/crates/blockifier/src/transaction/transactions_test.rs#L0)):*
see [here](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4FuMRP1vLUNMJ0BorR)

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/455)* status: all files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O4FvmZwCTTS819kKwqL:-O4K9yKF0JYY2_x74u6I:bihjtat) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e23dfffab58008b5c7714e59f1c4b4204057cf3/crates/blockifier/src/fee/actual_cost.rs#L92)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe `to_gas_vector` should simply borrow the `tx_context`? seems weird, passing three of it's fields explicitly
</blockquote></details>

I agree it looks weird but I think passing more information than needed might be more confusing, no?
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O4FvP4bCrL_V_NrVd6a:-O4KIrNr3n8J82Q5xJyI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e23dfffab58008b5c7714e59f1c4b4204057cf3/crates/blockifier/src/test_utils/struct_impls.rs#L123)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this should be injected somehow; it's a test util, and we should be able to test both cases
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O4FvVjc1YQdo5-OUBy5:-O4KJhcd2mBSpbRQPm5e:b4rwu97) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e23dfffab58008b5c7714e59f1c4b4204057cf3/crates/blockifier/src/transaction/account_transactions_test.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see [here](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4FuMRP1vLUNMJ0BorR)
</blockquote></details>

Changed it to be dependent on the user's bounds signature.
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O4FvYMOE8Dy70YSyLqt:-O4KJxjz-svAxt84_OJ3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e23dfffab58008b5c7714e59f1c4b4204057cf3/crates/blockifier/src/transaction/execution_flavors_test.rs#L135)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see [here](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4FuMRP1vLUNMJ0BorR)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O4Fv_aFCAc3igJfqryJ:-O4KK0DoDFS5wOnlYcw5:b7laspr) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e23dfffab58008b5c7714e59f1c4b4204057cf3/crates/blockifier/src/transaction/objects.rs#L116)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

didn't we want to first look into changing this type to an enum?
</blockquote></details>

I will do it separately. I haven't figured out yet how and where to do it.
___
*[`crates/blockifier/src/transaction/post_execution_test.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O4FvgCrBNNFxPNgzhzv:-O4KOJOj96ajBBOYVpQY:bh9rbro) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e23dfffab58008b5c7714e59f1c4b4204057cf3/crates/blockifier/src/transaction/post_execution_test.rs#L262)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see [here](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4FuMRP1vLUNMJ0BorR)
</blockquote></details>

Added TODO to derive it from user's bounds
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1918 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O4KPO3_56XqQe-gApsK:-O4KPO3aCQQTcDdYsgxy:bugugua) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e23dfffab58008b5c7714e59f1c4b4204057cf3/crates/blockifier/src/transaction/transactions_test.rs#L1918)):*
> ```XML
> 
>     let total_gas = expected_tx_resources
>         .to_gas_vector(versioned_constants, block_context.block_info.use_kzg_da, false)
> ```

here it's false since it tests l1 handler



_Code quote:_
```XML
 false)
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O4Fvh_O7L7Y_OXgDo2O:-O4KPRjnDF6tPWPjmXzK:b4rwu97) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e23dfffab58008b5c7714e59f1c4b4204057cf3/crates/blockifier/src/transaction/transactions_test.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see [here](https://reviewable.io/reviews/starkware-libs/sequencer/454#-O4FuMRP1vLUNMJ0BorR)
</blockquote></details>

Changed it to be dependent on the user's bounds signature.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/455)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O4FvmZwCTTS819kKwqL:-O4KigqVACfgFeY3KzqD:bsfoxza) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e23dfffab58008b5c7714e59f1c4b4204057cf3/crates/blockifier/src/fee/actual_cost.rs#L92)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I agree it looks weird but I think passing more information than needed might be more confusing, no?
</blockquote></details>

add a TODO to consider this... maybe adding a `to_gas_vector_with_context` wrapper to `to_gas_vector`
___
*[`crates/blockifier/src/transaction/objects.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O4Fv_aFCAc3igJfqryJ:-O4Ki_J10RaFb86cTgbx:bur06b7) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e23dfffab58008b5c7714e59f1c4b4204057cf3/crates/blockifier/src/transaction/objects.rs#L116)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I will do it separately. I haven't figured out yet how and where to do it.
</blockquote></details>

add a TODO then for now

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/455)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O4FvmZwCTTS819kKwqL:-O4Kpp5k0AFvL9obrMX1:b61l827) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e23dfffab58008b5c7714e59f1c4b4204057cf3/crates/blockifier/src/fee/actual_cost.rs#L92)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add a TODO to consider this... maybe adding a `to_gas_vector_with_context` wrapper to `to_gas_vector`
</blockquote></details>

added a wrapper
___
*[`crates/blockifier/src/transaction/objects.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O4Fv_aFCAc3igJfqryJ:-O4KmXZ94ctl0vNUC33p:b-fulrbc) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e23dfffab58008b5c7714e59f1c4b4204057cf3/crates/blockifier/src/transaction/objects.rs#L116)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add a TODO then for now
</blockquote></details>

WDYT about how i did it now?
added a method for `ResourceBoundsMapping`

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/455)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/455)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/starknet_api/src/transaction.rs` line 974 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/455#-O5gN8NSE9I4sG9dmIWG:-O5gN8NSE9I4sG9dmIWH:bukbe26) ([raw file](https://github.com/starkware-libs/sequencer/blob/3545a13f4f45cdd7a22933b852c4560c3e24aae6/crates/starknet_api/src/transaction.rs#L974)):*
> ```XML
>     }
> 
>     pub fn has_l2_gas(&self) -> bool {
> ```

this is confusing, why not "has data gas bounds"?
l2 gas exists (and is zero) on old V3 txs as well.
also, where is this used?



_Code quote:_
```XML
has_l2_gas
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/455)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/455)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

**Pull request closed without merging**
