### PR TITLE
feat(sync): implement get_block in StateSync

### PR DESCRIPTION
**Pull request by noamsp-starkware**

### CODE REVIEW

**Comment by noamsp-starkware** [comment]
* **#2285** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2285?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2285?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2285)* status: all files reviewed, 3 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/starknet_state_sync/src/runner/mod.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2285#-OCcc13u3nJWJ4JtqlxK:-OCcc13u3nJWJ4JtqlxL:bd08ktm) ([raw file](https://github.com/starkware-libs/sequencer/blob/1af5f6979116c1fdeb6aebbfe8cb647532a85aec/crates/starknet_state_sync/src/runner/mod.rs#L52)):*
> ```XML
>         tokio::select! {
>             result = &mut self.sync_future => result.map_err(|_| ComponentError::InternalComponentError),
>             Some((request, sender)) = self.request_receiver.next() => {
> ```

Run this inside an async block that loops for requests. Right now it will only handle one request and stop
___
*[`crates/starknet_state_sync/src/runner/mod.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2285#-OCcbrbi2BRnVyZyqRXk:-OCcbrbi2BRnVyZyqRXl:b-2a7r9s) ([raw file](https://github.com/starkware-libs/sequencer/blob/1af5f6979116c1fdeb6aebbfe8cb647532a85aec/crates/starknet_state_sync/src/runner/mod.rs#L55)):*
> ```XML
>                 let response = match request {
>                     StateSyncRequest::GetBlock(block_number) => {
>                         StateSyncResponse::GetBlock(self.get_block(block_number))
> ```

See comment below, and then change this to Ok(self.get_block....map_err(|_| ComponentError::Int...)?
___
*[`crates/starknet_state_sync/src/runner/mod.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2285#-OCcbUIG46hMxgTofvlf:-OCcbUIG46hMxgTofvlg:bga6mn) ([raw file](https://github.com/starkware-libs/sequencer/blob/1af5f6979116c1fdeb6aebbfe8cb647532a85aec/crates/starknet_state_sync/src/runner/mod.rs#L110)):*
> ```XML
>     }
> 
>     fn get_block(&self, block_number: BlockNumber) -> StateSyncResult<Option<SyncBlock>> {
> ```

This wasn't the last thing we said today. We said it should be Result<Option<SyncBlock>, StorageError>, and all the unwraps should be ? instead

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2285)* status: all files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/starknet_state_sync/src/runner/mod.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2285#-OCcc13u3nJWJ4JtqlxK:-OCchcI-AKRHx67p8Lli:b2nhb2c) ([raw file](https://github.com/starkware-libs/sequencer/blob/1af5f6979116c1fdeb6aebbfe8cb647532a85aec/crates/starknet_state_sync/src/runner/mod.rs#L52)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Run this inside an async block that loops for requests. Right now it will only handle one request and stop
</blockquote></details>

Ack
___
*[`crates/starknet_state_sync/src/runner/mod.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2285#-OCcbrbi2BRnVyZyqRXk:-OCchbVy3yrJbVsQqhxd:b2nhb2c) ([raw file](https://github.com/starkware-libs/sequencer/blob/1af5f6979116c1fdeb6aebbfe8cb647532a85aec/crates/starknet_state_sync/src/runner/mod.rs#L55)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

See comment below, and then change this to Ok(self.get_block....map_err(|_| ComponentError::Int...)?
</blockquote></details>

Ack
___
*[`crates/starknet_state_sync/src/runner/mod.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2285#-OCcbUIG46hMxgTofvlf:-OCcdj4z5vwQfYaaeW51:bbip1ai) ([raw file](https://github.com/starkware-libs/sequencer/blob/1af5f6979116c1fdeb6aebbfe8cb647532a85aec/crates/starknet_state_sync/src/runner/mod.rs#L110)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This wasn't the last thing we said today. We said it should be Result<Option<SyncBlock>, StorageError>, and all the unwraps should be ? instead
</blockquote></details>

We also said that we should panic if encountered an error, so I thought it was more readable this way.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2285)* status: all files reviewed, 1 unresolved discussion (waiting on @noamsp-starkware)

___
*[`crates/starknet_state_sync/src/runner/mod.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2285#-OCcc13u3nJWJ4JtqlxK:-OCgZjWF6MxKraEWY01p:b-e5xm5l) ([raw file](https://github.com/starkware-libs/sequencer/blob/1af5f6979116c1fdeb6aebbfe8cb647532a85aec/crates/starknet_state_sync/src/runner/mod.rs#L52)):*
<details><summary><i>Previously, noamsp-starkware wrote…</i></summary><blockquote>

Ack
</blockquote></details>

This also works :) 
___
*[`crates/starknet_state_sync/src/runner/mod.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2285#-OCgZslIDhqu5pR0D86v:-OCgZslIDhqu5pR0D86w:bj5mhom) ([raw file](https://github.com/starkware-libs/sequencer/blob/3481d54c46dfccbff15aa060de0595cf58b642eb/crates/starknet_state_sync/src/runner/mod.rs#L108)):*
> ```XML
>     }
> 
>     fn get_block(&self, block_number: BlockNumber) -> Result<Option<SyncBlock>, StorageError> {
> ```

I thought about it this morning, and I think that we should return the error to the user instead of crashing. This means that you should return this back to StateSyncResult and add a StorageError variant to StateSyncError

sorry for the mess

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2285)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/starknet_state_sync/src/runner/mod.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2285#-OCcc13u3nJWJ4JtqlxK:-OCgzGD28eW2Wz_9wTWM:biyqtw) ([raw file](https://github.com/starkware-libs/sequencer/blob/1af5f6979116c1fdeb6aebbfe8cb647532a85aec/crates/starknet_state_sync/src/runner/mod.rs#L52)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This also works :)
</blockquote></details>

It was really problematic (ownership-wise) to put the loop in the select. I figured this would have the same effect and be much less of a hassle.
___
*[`crates/starknet_state_sync/src/runner/mod.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2285#-OCgZslIDhqu5pR0D86v:-OCgzfeT6j6zfZrJ-vG0:b-836xo9) ([raw file](https://github.com/starkware-libs/sequencer/blob/3481d54c46dfccbff15aa060de0595cf58b642eb/crates/starknet_state_sync/src/runner/mod.rs#L108)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I thought about it this morning, and I think that we should return the error to the user instead of crashing. This means that you should return this back to StateSyncResult and add a StorageError variant to StateSyncError

sorry for the mess
</blockquote></details>

On it

**Pull request merged**
