### PR TITLE
refactor(batcher): extract common logic into a function for validate flow

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
* **#1951** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1951?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1986** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1986?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1985** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1985?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Yael-Starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1985)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1985#-OBVRTrH5QdERMpsvyJN:-OBVT3rf35EmM57Rm66e:b-kle917) ([raw file](https://github.com/starkware-libs/sequencer/blob/5bd1781dc1e40f0d90d8a807f601bbf7611822be/crates/batcher/src/proposal_manager.rs#L253)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This can't return an error, can it?
</blockquote></details>

right, fixed.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1985#-:-OBVUKVdB4LuSxrklZkB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1985#-:-OBVedui-L0oUkCZOrOB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
