### PR TITLE
refactor(fee): use valid resource bounds in blockifier

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/537)

### CODE REVIEW

**Comment by nimrod-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/537?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#538** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/538?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#537** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/537?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#508** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/508?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#509](https://github.com/starkware-libs/sequencer/pull/509) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/509?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#507** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/507?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#506** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/506?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#505** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/505?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#504** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/504?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#503** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/503?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nimrod-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 14 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/537)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 217 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/537#-O5NZ5iJ3s7vfTobC-4X:-O5NZ5iJ3s7vfTobC-4Y:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c960e691cf1bf74dd472f5fcdf44ed22c5a3f747/crates/blockifier/src/test_utils.rs#L217)):*
> ```XML
>     //   L2 gas.
>     ValidResourceBounds::L1Gas(ResourceBounds { max_amount: 0, max_price_per_unit: 1 })
> }
> ```





_Suggestion:_
```XML
// TODO: Default testing bounds should probably be AllResourceBounds variant.
pub fn default_testing_resource_bounds() -> ValidResourceBounds {
    ValidResourceBounds::L1Gas(ResourceBounds { max_amount: 0, max_price_per_unit: 1 })
}
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/537)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 217 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/537#-O5NZ5iJ3s7vfTobC-4X:-O5O8RnoBPwThQ5sifMu:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c960e691cf1bf74dd472f5fcdf44ed22c5a3f747/crates/blockifier/src/test_utils.rs#L217)):*
> ```XML
>     //   L2 gas.
>     ValidResourceBounds::L1Gas(ResourceBounds { max_amount: 0, max_price_per_unit: 1 })
> }
> ```

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/537)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/537#-:-O5OFTZy-flf54uAIPoe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/537)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Comment by nimrod-starkware** [comment]
### Merge activity

* **Sep 4, 9:01 AM EDT**: @nimrod-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/537).

**Pull request merged**
