### PR TITLE
chore: add get selected server future

### PR DESCRIPTION
**Pull request by nadin-Starkware**
**Stack**:
- #2047
- #2044 ⬅
- #2041
- #2040
- #2035
- #2034
- #2033
- #2032
- #2030
- #2029
- #2028

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2044)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/starknet_sequencer_node/src/servers.rs` line 337 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2044#-OBgStSm-j2cuZtt4isY:-OBgStSm-j2cuZtt4isZ:b-3yvzy1) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae3a146d509f5242bddca32abcbd4d16c5e4c095/crates/starknet_sequencer_node/src/servers.rs#L337)):*
> ```XML
>         ComponentExecutionMode::Disabled => pending().boxed(),
>     }
> }
> ```

Need to see this in context in order to review.



_Code quote:_
```XML
pub fn get_selected_server_future(
    execution_mode: &ComponentExecutionMode,
    local_server: Option<Box<impl ComponentServerStarter + Send + 'static>>,
    remote_server: Option<Box<impl ComponentServerStarter + Send + 'static>>,
) -> Pin<Box<dyn Future<Output = Result<(), ComponentServerError>> + Send>> {
    match execution_mode {
        ComponentExecutionMode::Remote => get_server_future(remote_server),
        ComponentExecutionMode::LocalExecutionWithRemoteDisabled
        | ComponentExecutionMode::LocalExecutionWithRemoteEnabled => {
            get_server_future(local_server)
        }
        ComponentExecutionMode::Disabled => pending().boxed(),
    }
}
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2044)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/starknet_sequencer_node/src/servers.rs` line 337 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2044#-OBgStSm-j2cuZtt4isY:-OBgTJ0Q2kP9XOwdZi11:b-s6xvf7) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae3a146d509f5242bddca32abcbd4d16c5e4c095/crates/starknet_sequencer_node/src/servers.rs#L337)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Need to see this in context in order to review.
</blockquote></details>

After looking at https://reviewable.io/reviews/starkware-libs/sequencer/2047

The code afaiu does something different than needed:
1.  In `LocalExecutionWithRemoteEnabled` you'd want both the local and remote servers to run.
2. In `Remote` you don't run any server.

I think this should be also further simplified: no need to pass the config and match its values once again -- once there is a server, then run it.

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2044)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sequencer_node/src/servers.rs` line 337 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2044#-OBgStSm-j2cuZtt4isY:-OBtiSPl7CQ95hz_oD_7:b6wdi1t) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae3a146d509f5242bddca32abcbd4d16c5e4c095/crates/starknet_sequencer_node/src/servers.rs#L337)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

After looking at https://reviewable.io/reviews/starkware-libs/sequencer/2047

The code afaiu does something different than needed:
1.  In `LocalExecutionWithRemoteEnabled` you'd want both the local and remote servers to run.
2. In `Remote` you don't run any server.

I think this should be also further simplified: no need to pass the config and match its values once again -- once there is a server, then run it.
</blockquote></details>

Agreed, I’ve added a TODO to remove it.

**Comment by nadin-Starkware** [comment]
Closing pull request: commit has gone away

**Pull request closed without merging**
