### PR TITLE
refactor(fee): remove resource mapping usage in rpc and adjust to use all resources

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/580)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/580)* status: all files reviewed, 5 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, and @ShahakShama)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58A0-8AN2RQ11NPxP9:-O58A0-8AN2RQ11NPxPA:bwz4uro) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/gateway/src/stateless_transaction_validator_test.rs#L0)):*
who will update these tests for nonzero data gas bounds?
@dafnamatsry ?
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58A7cm3nTw0QdpN6kY:-O58A7cm3nTw0QdpN6kZ:b2lgtm3) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L52)):*
> ```XML
> pub const VALID_L2_GAS_MAX_PRICE_PER_UNIT: u128 = 100000000000;
> pub const VALID_L1_DATA_GAS_MAX_AMOUNT: u64 = 203484;
> pub const VALID_L1_DATA_GAS_MAX_PRICE_PER_UNIT: u128 = 100000000000;
> ```

where did these numbers come from?



_Code quote:_
```XML
pub const VALID_L1_DATA_GAS_MAX_AMOUNT: u64 = 203484;
pub const VALID_L1_DATA_GAS_MAX_PRICE_PER_UNIT: u128 = 100000000000;
```
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58AD-e39ya8ixIhbDm:-O58AD-f5-aA9ySDcKWO:b-z0h70z) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L110)):*
> ```XML
>         l1_data_gas: l1_data_resource_bounds,
>     }
> }
> ```

please add a TODO to delete this function... looks redundant.
if not redundant, then the fields of AllResourceBounds should be private, and this "logic" should be moved to `AllResourceBounds::new`



_Code quote:_
```XML
pub fn create_resource_bounds_mapping(
    l1_resource_bounds: ResourceBounds,
    l2_resource_bounds: ResourceBounds,
    l1_data_resource_bounds: ResourceBounds,
) -> AllResourceBounds {
    AllResourceBounds {
        l1_gas: l1_resource_bounds,
        l2_gas: l2_resource_bounds,
        l1_data_gas: l1_data_resource_bounds,
    }
}
```
___
*[`crates/starknet_api/src/rpc_transaction.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58AX_643puoOIAxKMe:-O58AX_643puoOIAxKMf:b9dxh04) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/starknet_api/src/rpc_transaction.rs#L203)):*
> ```XML
>             (Resource::L1Gas, all_resource_bounds.l1_gas),
>             (Resource::L2Gas, all_resource_bounds.l2_gas),
>         ]);
> ```

no assert that L2 gas bounds are zero?
when will this conversion be required...?
or, did you forget to add the data gas?



_Code quote:_
```XML
        let map = BTreeMap::from([
            (Resource::L1Gas, all_resource_bounds.l1_gas),
            (Resource::L2Gas, all_resource_bounds.l2_gas),
        ]);
```
___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58AjKQBhjNGFiyNtuf:-O58AjKQBhjNGFiyNtug:b-j1su88) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/starknet_api/src/rpc_transaction_test.rs#L35)):*
> ```XML
>         l2_gas: ResourceBounds { max_amount: 58, max_price_per_unit: 31 },
>         l1_data_gas: ResourceBounds { max_amount: 66, max_price_per_unit: 25 },
>     }
> ```

are these numbers random...?



_Code quote:_
```XML
    AllResourceBounds {
        l1_gas: ResourceBounds { max_amount: 100, max_price_per_unit: 12 },
        l2_gas: ResourceBounds { max_amount: 58, max_price_per_unit: 31 },
        l1_data_gas: ResourceBounds { max_amount: 66, max_price_per_unit: 25 },
    }
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/580)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware, @MohammadNassar1, and @ShahakShama)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58A7cm3nTw0QdpN6kY:-O58RxdS2EpP48bLNshw:b-k3vxj2) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L52)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where did these numbers come from?
</blockquote></details>

it's a copy paste...
@MohammadNassar1 , is that ok?
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58AD-e39ya8ixIhbDm:-O58SyWO8outpCQIrANP:bhnwk7e) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L110)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a TODO to delete this function... looks redundant.
if not redundant, then the fields of AllResourceBounds should be private, and this "logic" should be moved to `AllResourceBounds::new`
</blockquote></details>

added a todo
___
*[`crates/starknet_api/src/rpc_transaction.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58AX_643puoOIAxKMe:-O58RrPRE_AZyghC3hB9:bv2soo3) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/starknet_api/src/rpc_transaction.rs#L203)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no assert that L2 gas bounds are zero?
when will this conversion be required...?
or, did you forget to add the data gas?
</blockquote></details>

forgot the data gas. added that
___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58AjKQBhjNGFiyNtuf:-O58RlbtBg2r4tjq0wbH:b-icpuhs) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/starknet_api/src/rpc_transaction_test.rs#L35)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

are these numbers random...?
</blockquote></details>

yes, the numbers i added are random... do they mean anything?
@MohammadNassar1 ?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/580)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1, @nimrod-starkware, and @ShahakShama)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58A7cm3nTw0QdpN6kY:-O58hI-R0DjZJ0Flh4pC:bauqz8h) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L52)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

it's a copy paste...
@MohammadNassar1 , is that ok?
</blockquote></details>

I don't think L2 gas units and L1 data gas units are related...
and neither are related to L1 gas.
you shouldn't be copy-pasting here, need new (sane) values.
this is a test util so maybe it isn't critical but @MohammadNassar1 please advise

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/580)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @ShahakShama)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58A7cm3nTw0QdpN6kY:-O59BISt1i1Z7D2L4H-y:bw4kvh1) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L52)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't think L2 gas units and L1 data gas units are related...
and neither are related to L1 gas.
you shouldn't be copy-pasting here, need new (sane) values.
this is a test util so maybe it isn't critical but @MohammadNassar1 please advise
</blockquote></details>

Currently, `VALID_L2_GAS_MAX_AMOUNT` and `VALID_L2_GAS_MAX_PRICE_PER_UNIT` are used as default values for testing.
I'm not sure if we should use specific values.
___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58AjKQBhjNGFiyNtuf:-O59B7827EI6C7EFRl3n:b-7oqi81) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/starknet_api/src/rpc_transaction_test.rs#L35)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

yes, the numbers i added are random... do they mean anything?
@MohammadNassar1 ?
</blockquote></details>

Correct, these are random numbers.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/580)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @ShahakShama)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58A0-8AN2RQ11NPxP9:-O5CozJH2qD8Mg7g6EGz:b-md231t) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/gateway/src/stateless_transaction_validator_test.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

who will update these tests for nonzero data gas bounds?
@dafnamatsry ?
</blockquote></details>

What should be validated in the new flow? what bounds must not be zero?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/580)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @ShahakShama)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58A0-8AN2RQ11NPxP9:-O5D3ef57EsFo1eVuNOz:b-881tnx) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/gateway/src/stateless_transaction_validator_test.rs#L)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What should be validated in the new flow? what bounds must not be zero?
</blockquote></details>

I see `create_resource_bounds_mapping` called 3 times to test different L1/L2 gas scenarios; but data gas is always trivial in tests.
If it doesn't matter ( @dafnamatsry ?) I'll unblock

**Review by dafnamatsry — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/580)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @ShahakShama)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58A0-8AN2RQ11NPxP9:-O5D6H7g9L2lXRtTlIeA:b-r34rx8) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/gateway/src/stateless_transaction_validator_test.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I see `create_resource_bounds_mapping` called 3 times to test different L1/L2 gas scenarios; but data gas is always trivial in tests.
If it doesn't matter ( @dafnamatsry ?) I'll unblock
</blockquote></details>

We need to update the GW to check that the bounds are valid. Do you know what are the valid scenarios?

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/580)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry, @dorimedini-starkware, and @ShahakShama)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58A0-8AN2RQ11NPxP9:-O5D8BVV8S-d4uAcEImy:b4usqt0) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/gateway/src/stateless_transaction_validator_test.rs#L)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

We need to update the GW to check that the bounds are valid. Do you know what are the valid scenarios?
</blockquote></details>

There are two valid scenarios:
1. All three bounds are given (l1, l1_data, l2)
2. only l1 and l2 are given and `l2.max_amount == l2.max_price_per_unit == 0`

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/580)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry, @dorimedini-starkware, and @ShahakShama)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58A0-8AN2RQ11NPxP9:-O5D8g3P7eU33uHv3Hpi:b-s4lmz6) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/gateway/src/stateless_transaction_validator_test.rs#L)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

There are two valid scenarios:
1. All three bounds are given (l1, l1_data, l2)
2. only l1 and l2 are given and `l2.max_amount == l2.max_price_per_unit == 0`
</blockquote></details>

But IIUC, since the rpc transaction is not something we have in production then maybe only the first scenario is valid, no? @dorimedini-starkware

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/580)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @ShahakShama)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58A0-8AN2RQ11NPxP9:-O5DKlu6CgmOXJ5OOia1:bs8khzz) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/gateway/src/stateless_transaction_validator_test.rs#L)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

But IIUC, since the rpc transaction is not something we have in production then maybe only the first scenario is valid, no? @dorimedini-starkware
</blockquote></details>

Yes, the RPC should only support the "all three bounds" case

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/580)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @ShahakShama)

**Review by dafnamatsry — COMMENTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/580)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/580)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58A0-8AN2RQ11NPxP9:-O5N8OhcDfuaExJ7VZH9:b-4vvv9s) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/gateway/src/stateless_transaction_validator_test.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Yes, the RPC should only support the "all three bounds" case
</blockquote></details>

however, the issue is that there is no coverage for *positive* data gas limits

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/580)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/580#-O58A0-8AN2RQ11NPxP9:-O5N8ckX2nVv4KtFiPCx:b-enl8eq) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a41f5fcc731f068c78eae38592d85aca4e08399/crates/gateway/src/stateless_transaction_validator_test.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

however, the issue is that there is no coverage for *positive* data gas limits
</blockquote></details>

Before we update the test, we first need to add the appropriate validations to the data gas limit.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/580#-:-O5NB-6o6LoPskm4Auf8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/580#-:-O5O5tVH1O0-MU8RNGfA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Comment by nimrod-starkware** [comment]
### Merge activity

* **Aug 28, 9:25 AM EDT**: @nimrod-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/580).

**Pull request merged**
