### PR TITLE
refactor(blockifier): min compiler version for sierra gas type

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2752?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2752** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2752?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2752?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2680** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2680?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2681](https://github.com/starkware-libs/sequencer/pull/2681) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2681?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2679** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2679?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2678** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2678?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2668** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2668?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2641](https://github.com/starkware-libs/sequencer/pull/2641) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2641?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2614** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2614?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2493** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2493?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2438** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2438?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2420** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2420?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2421](https://github.com/starkware-libs/sequencer/pull/2421) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2421?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2467** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2467?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2466** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2466?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2752)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 312 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2752#-OEPDWfP4_Lfa4Xr71Mw:-OEPDWfP4_Lfa4Xr71Mx:b-nyj77e) ([raw file](https://github.com/starkware-libs/sequencer/blob/5e89fc04c77a53a7a1a480b6056084d76a90d80a/crates/blockifier/src/execution/contract_class.rs#L312)):*
> ```XML
>     pub fn try_from_json_string(raw_contract_class: &str) -> Result<CompiledClassV1, ProgramError> {
>         let casm_contract_class: CasmContractClass = serde_json::from_str(raw_contract_class)?;
>         let sierra_version = SierraVersion::default();
> ```

is this ok...? where is `try_from_json_string` used?



_Code quote:_
```XML
let sierra_version = SierraVersion::default();
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2752)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @noaov1, and @TzahiTaub)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2752)* status: 22 of 28 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 312 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2752#-OEPDWfP4_Lfa4Xr71Mw:-OEPIioh-7LAV8a-fUpA:b4l6pna) ([raw file](https://github.com/starkware-libs/sequencer/blob/5e89fc04c77a53a7a1a480b6056084d76a90d80a/crates/blockifier/src/execution/contract_class.rs#L312)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this ok...? where is `try_from_json_string` used?
</blockquote></details>

No, it's not okay. It is used here [Here](https://github.com/starkware-libs/sequencer/blob/eb9b1abc5cf05e03cd046d9b6432190ddde2183a/crates/native_blockifier/src/state_readers/py_state_reader.rs#L128). I'll open another [PR](https://reviewable.io/reviews/starkware-libs/sequencer/2809) for it, and in the meantime, I'll use `SierraVersion::deprecated` to avoid activating the feature on the Python gateway.

**Review by AvivYossef-starkware — COMMENTED** [review]
Should add python PR

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2752#-:-OETBFl0D0K5LKEdr9NE:b-ggcj5t)* status: 22 of 28 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @noaov1, and @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2752#-:-OETNOooAV0Lq6krZzVH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2752)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2752)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2752)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2752)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @TzahiTaub)

**Pull request merged**
