### PR TITLE
chore(batcher): remove the duplicated papyrus_reader from native_blockifier

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
* **#1640** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1640?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Yael-Starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — COMMENTED** [review]
changes this PRS contains:
1. papyrus_reader was deleted from native_blockifier (since it was previously duplicated to the batcher).
2. native_blockifier now uses papyrus_reader from the batcher.
3. papyrus_reader_test was split. It had 2 tests: one of them went to the batcher , and the other to py_block_executor_test - since it only used py_block_executor functionality.
4. large_compiled_contract.json moved to a new native_blockifier/resources directory.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1640#-:-OAMSEPUEsv4lJKqeLpm:b2fyot4)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @alonh5 and @noaov1)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1640#-:-OAXM1n--3VULvxx33I_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5 and @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 10 files at r1, 8 of 12 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1640#-:-OBPa-DKB-aOrvSbmBY1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
