### PR TITLE
chore(ci): enforce crate directory name match + version from workspace

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
…kspace

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2014)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`workspace_tests/toml_utils.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2014#-OB_DR1_EBW1XNkS06R3:-OB_DR1_EBW1XNkS06R4:bgqac53) ([raw file](https://github.com/starkware-libs/sequencer/blob/b1e7777505eeff38fec2124bbbdd133f895a63df/workspace_tests/toml_utils.rs#L40)):*
> ```XML
> #[derive(Clone, Debug, Serialize, Deserialize)]
> pub(crate) struct CrateCargoTomlPackage {
>     version: HashMap<String, bool>, // Expect `version.workspace = true`.
> ```

Please do this check explicitly

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2014)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`workspace_tests/toml_utils.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2014#-OB_DR1_EBW1XNkS06R3:-OB_DkSc0mzc6XhIyjiC:b-ohvou8) ([raw file](https://github.com/starkware-libs/sequencer/blob/b1e7777505eeff38fec2124bbbdd133f895a63df/workspace_tests/toml_utils.rs#L40)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Please do this check explicitly
</blockquote></details>

With a good error message

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2014)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @ShahakShama)

___
*[`workspace_tests/toml_utils.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2014#-OB_DR1_EBW1XNkS06R3:-OBa0GoeEO1PseeNemvC:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b1e7777505eeff38fec2124bbbdd133f895a63df/workspace_tests/toml_utils.rs#L40)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

With a good error message
</blockquote></details>

Done.

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2014)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`workspace_tests/toml_utils.rs` line 43 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2014#-OBeUdrA7qiZgOAJC21r:-OBeUdrA7qiZgOAJC21s:b-1k6o43) ([raw file](https://github.com/starkware-libs/sequencer/blob/577435d5992071928b113495113b42571b97b092/workspace_tests/toml_utils.rs#L43)):*
> ```XML
>     String(String),
>     Object { workspace: bool },
>     Other(toml::Value),
> ```

Does serde(untagged) has a guarantee inside the docs that it will choose the first variant that matches? If not, find a different method to do this (e.g receive a toml::Value and in the test run match on it)
___
*[`workspace_tests/package_integrity_test.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2014#-OBeUJahEREbHFGvVgak:-OBeUJaiD_E6EB1uffNJ:b-20lmvd) ([raw file](https://github.com/starkware-libs/sequencer/blob/577435d5992071928b113495113b42571b97b092/workspace_tests/package_integrity_test.rs#L16)):*
> ```XML
>                 match toml.package.get("name") {
>                     // No package name.
>                     None => Some(path_str),
> ```

You can unite this with the Some(_) below to just _
Even better, just use `let ... else { return Some(path_str); }`

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2014)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @ShahakShama)

___
*[`workspace_tests/package_integrity_test.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2014#-OBeUJahEREbHFGvVgak:-OBebbH37Aj1Jt79hp-j:b6mft5s) ([raw file](https://github.com/starkware-libs/sequencer/blob/577435d5992071928b113495113b42571b97b092/workspace_tests/package_integrity_test.rs#L16)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You can unite this with the Some(_) below to just _
Even better, just use `let ... else { return Some(path_str); }`
</blockquote></details>

better? i still need the `if` in the match arm
___
*[`workspace_tests/toml_utils.rs` line 43 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2014#-OBeUdrA7qiZgOAJC21r:-OBeaq7W4ze_XCIvrFSm:b-uiduuo) ([raw file](https://github.com/starkware-libs/sequencer/blob/577435d5992071928b113495113b42571b97b092/workspace_tests/toml_utils.rs#L43)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Does serde(untagged) has a guarantee inside the docs that it will choose the first variant that matches? If not, find a different method to do this (e.g receive a toml::Value and in the test run match on it)
</blockquote></details>

from [here](https://serde.rs/enum-representations.html#untagged):
```
Serde will try to match the data against each variant in order and
the first one that deserializes successfully is the one returned.
```

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2014#-:-OBt08Mi6McRCZo5Azk1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
