### PR TITLE
feat(consensus): sequencer context broadcasts votes

### PR DESCRIPTION
**Pull request by matan-starkware**

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2393?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2393** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2393?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2393?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2392** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2392?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2393#-:-OD5gdnAB6lDXzXaNxKp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2393)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

___
*[`crates/starknet_consensus_manager/src/consensus_manager.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2393#-OD6-em-0mQv9KAeWtVI:-OD6-em-0mQv9KAeWtVJ:b-weo8c3) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3e0a208e21bdbbf32feb10e088472ed0a18a701/crates/starknet_consensus_manager/src/consensus_manager.rs#L20)):*
> ```XML
> pub const BROADCAST_BUFFER_SIZE: usize = 100;
> pub const CONSENSUS_PROPOSALS_TOPIC: &str = "consensus_proposals";
> pub const CONSENSUS_TOPIC: &str = "consensus";
> ```

Consider `consensus_votes` to be aligned with the other topic



_Code quote:_
```XML
consensus
```

**Review by asmaastarkware — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2393)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Pull request closed without merging**
