### PR TITLE
feat(config): handle positive, negative, and float in SerializationType

### PR DESCRIPTION
**Pull request by asmaastarkware**
- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/301)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/301)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_config/src/config_test.rs` line 312 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/301#-O3S_CN9DMFV5UJ3bWGJ:-O3S_CN9DMFV5UJ3bWGK:bq5i3hn) ([raw file](https://github.com/starkware-libs/sequencer/blob/a271788d5967332a66e225508ea54b3921e7b90a/crates/papyrus_config/src/config_test.rs#L312)):*
> ```XML
>                 "A dummy seed with generated default = 0.",
>                 ParamPrivacyInput::Public,
>             ),
> ```

Should we also include a test for Float? Maybe not this style, but anywhere in this file.



_Code quote:_
```XML
            ser_generated_param(
                "seed",
                SerializationType::Integer,
                "A dummy seed with generated default = 0.",
                ParamPrivacyInput::Public,
            ),
```

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/301)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/301)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_config/src/command.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/301#-O3bYsNg72YO71Nw-Oxm:-O3bYsNg72YO71Nw-Oxn:bzfmh0g) ([raw file](https://github.com/starkware-libs/sequencer/blob/f83514bf5b4f9c8b292003908d578314d5305c17/crates/papyrus_config/src/command.rs#L55)):*
> ```XML
>             SerializationType::Boolean => clap::value_parser!(bool),
>             SerializationType::String => clap::value_parser!(String),
>             SerializationType::Float => clap::value_parser!(f64).into(),
> ```

Do we have a convention on ordering the match cases? E.g., to match the enum (alphabetical) variant order?
I noticed these are indeed sorted for `SerializationType` below.



_Code quote:_
```XML
            SerializationType::Integer => clap::value_parser!(usize).into(),
            SerializationType::Boolean => clap::value_parser!(bool),
            SerializationType::String => clap::value_parser!(String),
            SerializationType::Float => clap::value_parser!(f64).into(),
```
___
*[`crates/papyrus_config/src/lib.rs` line 124 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/301#-O3b_klI55MFmVK0X8-r:-O3b_klJ9voYq0fiJhVz:b-4orvja) ([raw file](https://github.com/starkware-libs/sequencer/blob/f83514bf5b4f9c8b292003908d578314d5305c17/crates/papyrus_config/src/lib.rs#L124)):*
> ```XML
>                     } else {
>                         Some(SerializationType::Integer)
>                     }
> ```

Maybe worth adding a comment that JSON "Number"s are double-precision floating-point values, i.e., are accurately captured by using f64.



_Code quote:_
```XML
                    if num.is_f64() {
                        Some(SerializationType::Float)
                    } else {
                        Some(SerializationType::Integer)
                    }
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/301)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @dan-starkware)

___
*[`crates/papyrus_config/src/command.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/301#-O3batt89F1gtprpGaT3:-O3batt9ClblUAI1EGZF:bsbfyna) ([raw file](https://github.com/starkware-libs/sequencer/blob/f83514bf5b4f9c8b292003908d578314d5305c17/crates/papyrus_config/src/command.rs#L52)):*
> ```XML
>         };
>         let clap_parser = match serialization_type {
>             SerializationType::Integer => clap::value_parser!(usize).into(),
> ```

JSON supports up to u64, no? 
I realize this is not the scope of this pr, but why not u64?



_Code quote:_
```XML
usize
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/301)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @Itay-Tsabary-Starkware, and @matan-starkware)

___
*[`crates/papyrus_config/src/command.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/301#-O3batt89F1gtprpGaT3:-O3f8CZE-r-78CFVq1jk:b-iywffo) ([raw file](https://github.com/starkware-libs/sequencer/blob/f83514bf5b4f9c8b292003908d578314d5305c17/crates/papyrus_config/src/command.rs#L52)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

JSON supports up to u64, no? 
I realize this is not the scope of this pr, but why not u64?
</blockquote></details>

JSON "Number" is handled as u64, i64 and f64
I guess handling all three types ensures better compatibility. WDYT?
___
*[`crates/papyrus_config/src/command.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/301#-O3bYsNg72YO71Nw-Oxm:-O3f8wOP4CMaJhPd_DoR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f83514bf5b4f9c8b292003908d578314d5305c17/crates/papyrus_config/src/command.rs#L55)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Do we have a convention on ordering the match cases? E.g., to match the enum (alphabetical) variant order?
I noticed these are indeed sorted for `SerializationType` below.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/301#-:-O3febQtE5e77y1vJvsw:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/papyrus_config/src/command.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/301#-O3batt89F1gtprpGaT3:-O3fatKc5id07PvE3She:b2qhap2) ([raw file](https://github.com/starkware-libs/sequencer/blob/f83514bf5b4f9c8b292003908d578314d5305c17/crates/papyrus_config/src/command.rs#L52)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

JSON "Number" is handled as u64, i64 and f64
I guess handling all three types ensures better compatibility. WDYT?
</blockquote></details>

Makes sense. My previous comment was regarding the usage of `usize`, which can also be `u32`.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/301)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
