### PR TITLE
refactor(starknet_api): use general invoke rpc transaction test util

### PR DESCRIPTION
**Pull request by ayeletstarkware**

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1932)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1932#-OBQM_J83h-YbYjTLdj3:-OBQN_Hn6wuec-o5rQ7e:b-j8au7j) ([raw file](https://github.com/starkware-libs/sequencer/blob/d028027fab2b44627b56cd751d198cf4414a80fe/crates/starknet_api/src/rpc_transaction_test.rs#L83)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Do these values mean anything? or can this use `invoke_tx() -> RpcTransaction` instead?
</blockquote></details>

If not, and `create_invoke_v3` is a special dummy invoke only relevant here then we can leave it

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1932)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1932#-OBQM_J83h-YbYjTLdj3:-OBQNzIVBNKXpCYNknoc:b-vxgirw) ([raw file](https://github.com/starkware-libs/sequencer/blob/d028027fab2b44627b56cd751d198cf4414a80fe/crates/starknet_api/src/rpc_transaction_test.rs#L83)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

If not, and `create_invoke_v3` is a special dummy invoke only relevant here then we can leave it
</blockquote></details>

Actually, what does this test even test?
Do we have custom serialize/deserizlie in RpcTransaction?
If we don't then all this does is test serde_json, which is not our responsibility, in that case double-check with the author and if they didn't notice delete the test.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1932)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1932#-OBQM_J83h-YbYjTLdj3:-OBUV6sy68hcUk1CFEmy:b-fwms9s) ([raw file](https://github.com/starkware-libs/sequencer/blob/d028027fab2b44627b56cd751d198cf4414a80fe/crates/starknet_api/src/rpc_transaction_test.rs#L83)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Actually, what does this test even test?
Do we have custom serialize/deserizlie in RpcTransaction?
If we don't then all this does is test serde_json, which is not our responsibility, in that case double-check with the author and if they didn't notice delete the test.
</blockquote></details>

1 - RpcTransaction doesn't have custom serialization. 
2 - The comment above suggests these values are just non-defaults without meaning.
3 - Attaching the original PR; this test might need to be deleted. https://reviewable.io/reviews/starkware-libs/starknet-api/226
@MohammadNassar1 PTAL

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1932)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1932#-OBQM_J83h-YbYjTLdj3:-OBVQxpd0p_U_t7SdUsf:b-czwg8f) ([raw file](https://github.com/starkware-libs/sequencer/blob/d028027fab2b44627b56cd751d198cf4414a80fe/crates/starknet_api/src/rpc_transaction_test.rs#L83)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

1 - RpcTransaction doesn't have custom serialization. 
2 - The comment above suggests these values are just non-defaults without meaning.
3 - Attaching the original PR; this test might need to be deleted. https://reviewable.io/reviews/starkware-libs/starknet-api/226
@MohammadNassar1 PTAL
</blockquote></details>

Lets delete the whole file, maybe there was justification for this when it was merged, but I don't see any now

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1932)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1932#-OBQM_J83h-YbYjTLdj3:-OBVSCp6-MVgYLmqtLG7:b5gnwyj) ([raw file](https://github.com/starkware-libs/sequencer/blob/d028027fab2b44627b56cd751d198cf4414a80fe/crates/starknet_api/src/rpc_transaction_test.rs#L83)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Lets delete the whole file, maybe there was justification for this when it was merged, but I don't see any now
</blockquote></details>

The test was added because the primary function of `RPCTransaction` is to handle serialization and deserialization (sending transaction requests with JSON). This test ensures that the serialization and deserialization processes are functioning correctly.

Note that in RPC structs we use `serde` attributes to customize serialization and deserialization behavior.

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1932#-:-OBZoZC923st1JFf641B:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1932#-OBZoDUxBENCEAo66fkd:-OBZoDUxBENCEAo66fke:b-zex1a0) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed2929cae232d7a91a29e8908b0eadba6a246353/crates/starknet_api/src/rpc_transaction_test.rs#L76)):*
> ```XML
> #[case(RpcTransaction::DeployAccount(create_deploy_account_v3()))]
> #[case(rpc_invoke_tx(InvokeTxArgs {
>     resource_bounds: ValidResourceBounds::AllResources(create_resource_bounds_for_testing()),
> ```

we have `creare_resource_bounds_for_testing` that returns `Valid..` type, rigth?
Can it be used here?



_Code quote:_
```XML
ValidResourceBounds::AllResources(create_resource_bounds_for_testing())
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1932)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1932#-OBZoDUxBENCEAo66fkd:-OB_M59n4C_oZOr_p7ro:b-xec83g) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed2929cae232d7a91a29e8908b0eadba6a246353/crates/starknet_api/src/rpc_transaction_test.rs#L76)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

we have `creare_resource_bounds_for_testing` that returns `Valid..` type, rigth?
Can it be used here?
</blockquote></details>

It will be moved to `starknet_api` and used here once `declare_tx` is also relocated here.

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1932)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1932)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1932#-OBQM_J83h-YbYjTLdj3:-OBeNkOT6QdzqKwWF4Tu:b1foz6i) ([raw file](https://github.com/starkware-libs/sequencer/blob/d028027fab2b44627b56cd751d198cf4414a80fe/crates/starknet_api/src/rpc_transaction_test.rs#L83)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

an example: https://github.com/starkware-libs/sequencer/blob/c4b36db0a4043a88b90db2b4f27bfc91e86c4484/crates/starknet_api/src/rpc_transaction.rs#L44
</blockquote></details>

So it does have custom deserde, in that case the test is valid, retracting.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1932)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1932#-OBQM_J83h-YbYjTLdj3:-OBul_KgCmims5Jb-TEn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d028027fab2b44627b56cd751d198cf4414a80fe/crates/starknet_api/src/rpc_transaction_test.rs#L83)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

There is still the issue of the values and adding boilerplate to the parameterization.

- Keep using a function inside the parametrization instead of inline constructor.
- RE this specific function, if there is some other dummy constructor for rpc invokes use it instead of this one, and if there isn't, replace the values here to smaller non-trivial values (for example, nonce(1) instead of nonce(32))
</blockquote></details>

Done.

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1932#-:-OByKJg4DuK8XM1DTZPl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1932)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 86 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1932#-OByKNX62a8McLa3IHte:-OByKNX62a8McLa3IHtf:b-uz76mb) ([raw file](https://github.com/starkware-libs/sequencer/blob/e97d2d43aec608b3b10368c300021fa0dfef2dc8/crates/starknet_api/src/rpc_transaction_test.rs#L86)):*
> ```XML
> }
> 
> // We are testing the `RpcTransaction` serialization. Passing non-default values.
> ```

Nonblocking



_Suggestion:_
```XML
// Test the custom serde/deserde of RPC transactions.
```

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1932)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1932#-OByKSl768MAHDpBb7r0:-OByKSl88u5fSnKfW2RV:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/4ef2fa909ab8a538f2ec54ea0d3d87850f336a96/crates/starknet_api/src/rpc_transaction_test.rs#L75)):*
> ```XML
>     rpc_invoke_tx(InvokeTxArgs {
>         resource_bounds: ValidResourceBounds::AllResources(create_resource_bounds_for_testing()),
>         calldata: Calldata(Arc::new(vec![felt!("0x1"), felt!("0x2")])),
> ```





_Suggestion:_
```XML
calldata![felt!("0x1"), felt!("0x2")]
```

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1932)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
