### PR TITLE
feat(blockifier): panic on GasVector arithmetic overflow

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1280)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1280?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1280** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1280?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1268** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1268?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1255** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1255?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1250** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1250?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1180** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1180?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1179** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1179?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1178** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1178?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1177** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1177?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1176** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1176?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1175** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1175?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1174** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1174?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1173** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1173?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1172** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1172?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1280)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 310 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1280#-O95CkvUBkZgNLIcrlMi:-O95CkvUBkZgNLIcrlMj:b-9s391l) ([raw file](https://github.com/starkware-libs/sequencer/blob/f2914323b9f0bd51710473862a76dd1aa5197d52/crates/blockifier/src/fee/resources.rs#L310)):*
> ```XML
>                     "Message resources to starknet gas cost overflowed: tried to add \
>                      {accumulator:?} to {cost:?}"
>                 )
> ```

Does rust have something like `checked_sum`?



_Code quote:_
```XML
        .iter()
        .fold(GasVector::ZERO, |accumulator, cost| {
            accumulator.checked_add(*cost).unwrap_or_else(|| {
                panic!(
                    "Message resources to starknet gas cost overflowed: tried to add \
                     {accumulator:?} to {cost:?}"
                )
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1280)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 310 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1280#-O95CkvUBkZgNLIcrlMi:-O96X5Cx-YLIeHFiBUkU:b-htg95e) ([raw file](https://github.com/starkware-libs/sequencer/blob/f2914323b9f0bd51710473862a76dd1aa5197d52/crates/blockifier/src/fee/resources.rs#L310)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Does rust have something like `checked_sum`?
</blockquote></details>

1. I didn't find something I liked; there is nothing built in
2. what would the panic message look like?

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1280#-:-O98ZXjmBKFeOTcxUfMJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 310 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1280#-O95CkvUBkZgNLIcrlMi:-O98ZLrv7N9uXVEkzFew:b-5w88bu) ([raw file](https://github.com/starkware-libs/sequencer/blob/f2914323b9f0bd51710473862a76dd1aa5197d52/crates/blockifier/src/fee/resources.rs#L310)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. I didn't find something I liked; there is nothing built in
2. what would the panic message look like?
</blockquote></details>

I want to save some code duplication with all those panics. Not in this PR though

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Oct 14, 3:01 AM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1280).

**Pull request merged**
