### PR TITLE
feat(batcher): add validate flow request handlers

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
* **#1747** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1747?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Yael-Starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1747)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @yair-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 147 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1747#-OAlU3as9VT-gFIPvd9C:-OAlU3as9VT-gFIPvd9D:b2i3f8b) ([raw file](https://github.com/starkware-libs/sequencer/blob/f7ca9efe61d1c91a878c89f50d78f810f2e08801/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L147)):*
> ```XML
>             deadline: chrono::Utc::now() + chrono_timeout,
>             //TODO(Matan 3/11/2024): Add the real value of the retrospective block hash.
>             retrospective_block_hash: None,
> ```

@matan-starkware  FYI



_Code quote:_
```XML
            //TODO(Matan 3/11/2024): Add the real value of the retrospective block hash.
            retrospective_block_hash: None,
```

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1747)* status: all files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1747#-OAlUeH3E4T9C1MxLsH2:-OAlUeH3E4T9C1MxLsH3:b-34igyk) ([raw file](https://github.com/starkware-libs/sequencer/blob/b70cf82c058d4a3e256e168510bfe85c741db83e/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L147)):*
> ```XML
>             deadline: chrono::Utc::now() + chrono_timeout,
>             //TODO(yael 3/11/2024): Add the real value of the retrospective block hash.
>             retrospective_block_hash: None,
> ```

Similar to build_proposal - this way we won't error after 10 blocks.



_Suggestion:_
```XML
            retrospective_block_hash: Some(BlockHashAndNumber {
                number: BlockNumber::default(),
                hash: BlockHash::default(),
            }),
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1747)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1747#-OAlUeH3E4T9C1MxLsH2:-OAmKh_D5H7JrwXnue_O:b-bvbg3t) ([raw file](https://github.com/starkware-libs/sequencer/blob/b70cf82c058d4a3e256e168510bfe85c741db83e/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L147)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Similar to build_proposal - this way we won't error after 10 blocks.
</blockquote></details>

right , good catch
done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1747#-:-OAmNC9ADdwp0cZSz8zc:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Pull request merged**
