### PR TITLE
feat(starknet_api): the StarknetVersion type is now an enum

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1376)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
* **#1376** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1376?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 8 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1376#-:-O9FuLPZ53diwGDKKRKa:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/starknet_api/src/block.rs` line 135 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1376#-O9FttkFEItN_68mKK-X:-O9FttkFEItN_68mKK-Y:b-csqkgu) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a06947f14747619c7c74872a89b09a0074de60d/crates/starknet_api/src/block.rs#L135)):*
> ```XML
>     type Error = StarknetApiError;
>     fn try_from(starknet_version: &str) -> Result<Self, StarknetApiError> {
>         Self::try_from(starknet_version.to_string())
> ```

Does this return `Vec<u8>`?



_Code quote:_
```XML
to_string()
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1376)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/starknet_api/src/block.rs` line 135 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1376#-O9FttkFEItN_68mKK-X:-O9GE3wWBj0tFEa_A0mj:b-ucawya) ([raw file](https://github.com/starkware-libs/sequencer/blob/2a06947f14747619c7c74872a89b09a0074de60d/crates/starknet_api/src/block.rs#L135)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Does this return `Vec<u8>`?
</blockquote></details>

no, it returns the string-serialized version, e.g. `"0.13.1"`

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Oct 15, 1:32 PM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1376).

**Pull request merged**
