### PR TITLE
fix: flatten duration serialization

### PR DESCRIPTION
**Pull request by AlonLStarkWare**
- Revert "fix: fix dump to config (#1637)"
- fix: flatten duration serialization to seconds

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 5 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1647)* status: all files reviewed, 2 unresolved discussions (waiting on @AlonLStarkWare)

___
*[`crates/papyrus_network/src/discovery/mod.rs` line 228 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1647#-OASSO-19v6CRgSihMbB:-OASSO-19v6CRgSihMbC:bd8jtmw) ([raw file](https://github.com/starkware-libs/sequencer/blob/1285ac6dbe6c4e0808fa65a6a35a15cfc3074057/crates/papyrus_network/src/discovery/mod.rs#L228)):*
> ```XML
>     pub base_delay_millis: u64,
>     #[serde(deserialize_with = "deserialize_seconds_to_duration")]
>     pub max_delay: Duration,
> ```

Rename this to max_delay_seconds
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 80 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1647#-OASSSNMBlHbbs0Up0z9:-OASSSNMBlHbbs0Up0zA:b-2863u7) ([raw file](https://github.com/starkware-libs/sequencer/blob/1285ac6dbe6c4e0808fa65a6a35a15cfc3074057/crates/papyrus_network/src/peer_manager/mod.rs#L80)):*
> ```XML
>             // 1 year.
>             malicious_timeout_seconds: Duration::from_secs(3600 * 24 * 365),
>             unstable_timeout_millis: Duration::from_secs(1),
> ```

Please change this to Duration::from_millis(1000). It's confusing how it is right now

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1647)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/discovery/mod.rs` line 228 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1647#-OASSO-19v6CRgSihMbB:-OAvTNCv1uGh3nNbNyoe:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1285ac6dbe6c4e0808fa65a6a35a15cfc3074057/crates/papyrus_network/src/discovery/mod.rs#L228)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename this to max_delay_seconds
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 80 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1647#-OASSSNMBlHbbs0Up0z9:-OAvTJn-5AG9ytBPN8Eb:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1285ac6dbe6c4e0808fa65a6a35a15cfc3074057/crates/papyrus_network/src/peer_manager/mod.rs#L80)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Please change this to Duration::from_millis(1000). It's confusing how it is right now
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1647#-:-OAwBQpM5uHklleilkWO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Review by AlonLStarkWare — COMMENTED** [review]
> Reviewed 1 of 5 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1647)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Pull request merged**
