### PR TITLE
test: add get proposal content loop to end to end test

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1407)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1407?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1408** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1408?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1407** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1407?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1386** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1386?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1352** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1352?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ArniStarkware** [comment]
+reviewer:@alonh5

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1407)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9DpcVz2IeUXZz4ble5:-O9DpcVz2IeUXZz4ble6:b-an9jpa) ([raw file](https://github.com/starkware-libs/sequencer/blob/efec6bdca4e864b1b95432f67ba777a59917d568/crates/tests-integration/tests/end_to_end_test.rs#L102)):*
> ```XML
>             GetProposalContent::Txs(batched_txs) => {
>                 actual_tx_hashes.append(&mut batched_txs.iter().map(|tx| tx.tx_hash()).collect());
>             }
> ```

This revision has a bug where this match arm is never reached.
We would probably solve it in this or in one pre-pr.



_Code quote:_
```XML
            GetProposalContent::Txs(batched_txs) => {
                actual_tx_hashes.append(&mut batched_txs.iter().map(|tx| tx.tx_hash()).collect());
            }
```

**Comment by ArniStarkware** [comment]
+reviewer:@Yael-Starkware

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-:-O9d5tCLAk7K3DI0dr6p:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9DpcVz2IeUXZz4ble5:-O9d5W2U4KWAfXrSt4P5:bakncgz) ([raw file](https://github.com/starkware-libs/sequencer/blob/efec6bdca4e864b1b95432f67ba777a59917d568/crates/tests-integration/tests/end_to_end_test.rs#L102)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This revision has a bug where this match arm is never reached.
We would probably solve it in this or in one pre-pr.
</blockquote></details>

Is the test currently failing?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1407)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9DpcVz2IeUXZz4ble5:-O9dPca69EH5RrbcWDTB:bwwyhpw) ([raw file](https://github.com/starkware-libs/sequencer/blob/efec6bdca4e864b1b95432f67ba777a59917d568/crates/tests-integration/tests/end_to_end_test.rs#L102)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Is the test currently failing?
</blockquote></details>

No! :)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1407)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5 and @dafnamatsry)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1407)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @ArniStarkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 45 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9dUkxE9J4ZNNUpCW3o:-O9dUkxE9J4ZNNUpCW3p:b31x37n) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7feb5b1bff2d92292983b0d79a89df6d882bd82/crates/tests-integration/tests/end_to_end_test.rs#L45)):*
> ```XML
>     // offers a higher tip, regardless of the nonce. Hence the expected tx order, regardless of
>     // tx hashes, is: account1_invoke_nonce1, account0_invoke_nonce1, and account0_invoke_nonce2.
>     let expected_tx_hashes_from_get_txs = [
> ```

Consider renaming to `expected_block_content`/`expected_batched_txs`.



_Code quote:_
```XML
expected_tx_hashes_from_get_txs
```
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 64 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9dUAkKD2qxAhDv8Oe0:-O9dUAkL4lETrXBkXCz-:b-nma6q9) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7feb5b1bff2d92292983b0d79a89df6d882bd82/crates/tests-integration/tests/end_to_end_test.rs#L64)):*
> ```XML
> pub async fn run_consensus_for_end_to_end_test(
>     batcher_client: &SharedBatcherClient,
>     expected_tx_hashes_from_get_proposal_content: [TransactionHash; 3],
> ```

Why not `Vec<TransactionHash>`?



_Code quote:_
```XML
[TransactionHash; 3]
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1407)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @alonh5, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 45 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9dUkxE9J4ZNNUpCW3o:-O9dhSblBvUdrrX_W4BG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7feb5b1bff2d92292983b0d79a89df6d882bd82/crates/tests-integration/tests/end_to_end_test.rs#L45)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Consider renaming to `expected_block_content`/`expected_batched_txs`.
</blockquote></details>

Done.
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 64 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9dUAkKD2qxAhDv8Oe0:-O9dhT5S366ap2cg8qhv:b-blnik0) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7feb5b1bff2d92292983b0d79a89df6d882bd82/crates/tests-integration/tests/end_to_end_test.rs#L64)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why not `Vec<TransactionHash>`?
</blockquote></details>

Done. (I made sure the test is non-trivial in this case).

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-:-O9dmek6BS7Bl2n8BrLb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5, @Yael-Starkware, and @yair-starkware)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 4 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1407)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 92 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9dmhjFDnAk-0LNF5SW:-O9dmhjFDnAk-0LNF5SX:bco1vef) ([raw file](https://github.com/starkware-libs/sequencer/blob/5ef1f5cb184cd6e4a7743e5b770b2ec56b648d48/crates/tests-integration/tests/end_to_end_test.rs#L92)):*
> ```XML
> 
>     // Get proposal content.
> ```

Remove blank line.
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 110 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9dn5TQDWLG5c4RZf8n:-O9dn5TQDWLG5c4RZf8o:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/5ef1f5cb184cd6e4a7743e5b770b2ec56b648d48/crates/tests-integration/tests/end_to_end_test.rs#L110)):*
> ```XML
> 
>     // Assert.
>     assert_eq!(expected_batched_tx_hashes, actual_tx_hashes);
> ```





_Suggestion:_
```XML
    assert_eq!(expected_batched_tx_hashes, executed_tx_hashes);
```
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9dnSgD-Sw1-UiaL0hX:-O9dnSgD-Sw1-UiaL0hY:b59pxda) ([raw file](https://github.com/starkware-libs/sequencer/blob/5ef1f5cb184cd6e4a7743e5b770b2ec56b648d48/crates/tests-integration/tests/end_to_end_test.rs#L111)):*
> ```XML
>     // Assert.
>     assert_eq!(expected_batched_tx_hashes, actual_tx_hashes);
>     // TODO(Arni): Consider assert_eq(_proposal_commitment, ..);
> ```

Let's consider now, is there anything to compare to? Will it add to the test?



_Code quote:_
```XML
// TODO(Arni): Consider assert_eq(_proposal_commitment, ..);
```

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1407)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9DpcVz2IeUXZz4ble5:-O9e1SCL1sLSeotGOatY:b-h4d02a) ([raw file](https://github.com/starkware-libs/sequencer/blob/efec6bdca4e864b1b95432f67ba777a59917d568/crates/tests-integration/tests/end_to_end_test.rs#L102)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

No! :)
</blockquote></details>

So I don't understand your comment

**Comment by ArniStarkware** [comment]
*[`crates/tests-integration/tests/end_to_end_test.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9DpcVz2IeUXZz4ble5:-O9eAJjR8fXhZUbJHTX6:b-wvoiul) ([raw file](https://github.com/starkware-libs/sequencer/blob/efec6bdca4e864b1b95432f67ba777a59917d568/crates/tests-integration/tests/end_to_end_test.rs#L102)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

So I don't understand your comment
</blockquote></details>

It is no longer relevant.

**Comment by ArniStarkware** [comment]
*[`crates/tests-integration/tests/end_to_end_test.rs` line 110 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9dn5TQDWLG5c4RZf8n:-O9eAfGX3Oq8bTQ61Qr_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/49d58ca12d8a1df9748404c4377d3a73970ca388/crates/tests-integration/tests/end_to_end_test.rs#L110)):*
> ```XML
> 
>     // Assert.
>     assert_eq!(expected_batched_tx_hashes, actual_tx_hashes);
> ```

Done.

**Comment by ArniStarkware** [comment]
*[`crates/tests-integration/tests/end_to_end_test.rs` line 92 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9dmhjFDnAk-0LNF5SW:-O9hgkwlE6lHcXtzkA3m:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/49d58ca12d8a1df9748404c4377d3a73970ca388/crates/tests-integration/tests/end_to_end_test.rs#L92)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Remove blank line.
</blockquote></details>

Done.

**Comment by ArniStarkware** [comment]
*[`crates/tests-integration/tests/end_to_end_test.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9dnSgD-Sw1-UiaL0hX:-O9hgmGE2aCC_AOjr1L-:bir9ljb) ([raw file](https://github.com/starkware-libs/sequencer/blob/49d58ca12d8a1df9748404c4377d3a73970ca388/crates/tests-integration/tests/end_to_end_test.rs#L111)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Let's consider now, is there anything to compare to? Will it add to the test?
</blockquote></details>

I started thinking about it. We need to create a state diff manually - and calculate the commitment from that.

Should it block this PR?
This should also be compatible with the way we integrate the consensus into the test once we do that.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-:-O9hoxsz6Zru4i_t2DKJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 110 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9dn5TQDWLG5c4RZf8n:-O9hoZXkEtQ6gqYNGHQL:bgey1ym) ([raw file](https://github.com/starkware-libs/sequencer/blob/49d58ca12d8a1df9748404c4377d3a73970ca388/crates/tests-integration/tests/end_to_end_test.rs#L110)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Also remove the `Assert.` comment, it doesn't add anything new.
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9dnSgD-Sw1-UiaL0hX:-O9ho6ib38T97MoER7Ig:b-otjm1x) ([raw file](https://github.com/starkware-libs/sequencer/blob/49d58ca12d8a1df9748404c4377d3a73970ca388/crates/tests-integration/tests/end_to_end_test.rs#L111)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I started thinking about it. We need to create a state diff manually - and calculate the commitment from that.

Should it block this PR?
This should also be compatible with the way we integrate the consensus into the test once we do that.
</blockquote></details>

I don't think we need this in the e2e test. This check is something that should be (and probably is) done in a unit test for the blockifier. Here it's enough to see the expected txs have been executed. You can remove the todo :)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1407)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @alonh5, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 110 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9dn5TQDWLG5c4RZf8n:-O9i6UDuAtabbfiNcweW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/49d58ca12d8a1df9748404c4377d3a73970ca388/crates/tests-integration/tests/end_to_end_test.rs#L110)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Also remove the `Assert.` comment, it doesn't add anything new.
</blockquote></details>

Done.
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9dnSgD-Sw1-UiaL0hX:-O9i6Qgp7_Xz1_5V-V1a:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/49d58ca12d8a1df9748404c4377d3a73970ca388/crates/tests-integration/tests/end_to_end_test.rs#L111)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I don't think we need this in the e2e test. This check is something that should be (and probably is) done in a unit test for the blockifier. Here it's enough to see the expected txs have been executed. You can remove the todo :)
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1407)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1407)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9ijDpb8hr8ET2K7z8g:-O9ijDpb8hr8ET2K7z8h:bcw9lot) (no related file):*
Is this test stable or still flakey? If falkey, don't merge yet please

___

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1407)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @alonh5, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9ijDpb8hr8ET2K7z8g:-O9nKx9VADp47ACA67EX:b-zdfv6b) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Is this test stable or still flakey? If falkey, don't merge yet please
</blockquote></details>

The test is now stable.

___

**Review by alonh5 — APPROVED** [review]
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1407)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9ijDpb8hr8ET2K7z8g:-O9o3J3n9qo4OqNVH1k1:btojbfd) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The test is now stable.
</blockquote></details>

Great!

___

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1407)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9oAZt_8QA4PcmnvUAK:-O9oAZt_8QA4PcmnvUAL:b-ha5ofs) (no related file):*
I see the test failed in the PR over this one. Please reabse over main and make sure it's stable again (I merged a fix).

___

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1407)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @alonh5, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-O9oAZt_8QA4PcmnvUAK:-OA1jSe274l8EN8gQI3r:b-896fix) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I see the test failed in the PR over this one. Please reabse over main and make sure it's stable again (I merged a fix).
</blockquote></details>

Done.

___

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1407#-:-OABxMLi0QbfQxrUKN3r:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

**Pull request merged**
