### PR TITLE
feat(blockifier): don't count Sierra gas in CairoSteps mode

### PR DESCRIPTION
**Pull request by Yoni-Starkware**

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
Py side: https://github.com/starkware-industries/starkware/pull/36379

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2440#-:-ODCmjBR5wS4ZkKMcB4A:b-k1nvge)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2440)* status: all files reviewed, 6 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2440#-ODFrOgj4feD7WDLQ93a:-ODFrOgj4feD7WDLQ93b:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ec45d8ffaebee61444f4e10887b7ce49faab811/crates/blockifier/src/execution/contract_class.rs#L149)):*
> ```XML
>             Some(TrackedResource::CairoSteps) => TrackedResource::CairoSteps,
>             Some(TrackedResource::SierraGas) => contract_tracked_resource,
>             None => contract_tracked_resource,
> ```





_Suggestion:_
```XML
            Some(TrackedResource::SierraGas) | None => contract_tracked_resource,
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2440#-ODFrDHzCXlqG4hjRTAw:-ODFrDI-2EaQOhyEHU-E:b-sb14gp) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ec45d8ffaebee61444f4e10887b7ce49faab811/crates/blockifier/src/execution/contract_class.rs#L150)):*
> ```XML
>             Some(TrackedResource::SierraGas) => contract_tracked_resource,
>             None => contract_tracked_resource,
>         }
> ```

I think we are not ready yet to make this change.
we currently assume sierra gas consumption is zero if the user didn't sign on L1 data gas,
so you cna't run in gas tracking mode without changing this assumption first



_Code quote:_
```XML
    ) -> TrackedResource {
        let contract_tracked_resource = match self {
            Self::V0(_) => TrackedResource::CairoSteps,
            Self::V1(contract_class) => contract_class.tracked_resource(min_sierra_version),
            #[cfg(feature = "cairo_native")]
            Self::V1Native(contract_class) => {
                contract_class.casm().tracked_resource(min_sierra_version)
            }
        };
        match last_tracked_resource {
            // Once we ran with CairoSteps, we will continue to run using it for all nested calls.
            Some(TrackedResource::CairoSteps) => TrackedResource::CairoSteps,
            Some(TrackedResource::SierraGas) => contract_tracked_resource,
            None => contract_tracked_resource,
        }
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2440#-ODFtMjE2LN60Su-XRae:-ODFtMjE2LN60Su-XRaf:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ec45d8ffaebee61444f4e10887b7ce49faab811/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L227)):*
> ```XML
> 
>     assert_eq!(main_call_info.tracked_resource, TrackedResource::SierraGas);
>     assert!(main_call_info.execution.gas_consumed != 0);
> ```





_Suggestion:_
```XML
assert_ne!(main_call_info.execution.gas_consumed, 0);
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2440#-ODFtRF044D5yHGYsvQo:-ODFtRF044D5yHGYsvQp:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ec45d8ffaebee61444f4e10887b7ce49faab811/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L238)):*
> ```XML
>     let second_inner_call = main_call_info.inner_calls.get(1).unwrap();
>     assert_eq!(second_inner_call.tracked_resource, TrackedResource::SierraGas);
>     assert!(second_inner_call.execution.gas_consumed != 0);
> ```





_Suggestion:_
```XML
assert_ne!(second_inner_call.execution.gas_consumed, 0);
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 504 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2440#-ODFrbyaDGEUUEIoU6zu:-ODFrbyaDGEUUEIoU6zv:b-bseymf) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ec45d8ffaebee61444f4e10887b7ce49faab811/crates/blockifier/src/execution/entry_point_execution.rs#L504)):*
> ```XML
>         TrackedResource::CairoSteps => 0,
>         TrackedResource::SierraGas => syscall_handler.base.call.initial_gas - gas,
>     };
> ```

I have a suggestion: since gas_for_fee already exists and is implemented, why not have 2 PRs:
1. First, delete gas_consumed. when needed, use gas_for_fee (logically should be the same, but easier to review)
2. If you want, delete gas_for_fee (rename it to gas_consumed) as a second PR

WDYT?



_Code quote:_
```XML
    let gas_consumed = match tracked_resource {
        // Do not count Sierra gas in CairoSteps mode.
        TrackedResource::CairoSteps => 0,
        TrackedResource::SierraGas => syscall_handler.base.call.initial_gas - gas,
    };
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2440#-ODFselO2WjV05-Eooxk:-ODFselO2WjV05-Eooxl:b-68sz3b) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ec45d8ffaebee61444f4e10887b7ce49faab811/crates/blockifier/src/transaction/transactions_test.rs#L0)):*
when you set `None` as the last tracked resource in these tests - is it accurate? are you only calling the tracked_resource method on outermost calls (validate/execute)?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2440)* status: all files reviewed, 3 unresolved discussions (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2440)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 504 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2440#-ODFrbyaDGEUUEIoU6zu:-ODGNP2q-_Zo8G3Hik91:b-qrdbaj) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ec45d8ffaebee61444f4e10887b7ce49faab811/crates/blockifier/src/execution/entry_point_execution.rs#L504)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I have a suggestion: since gas_for_fee already exists and is implemented, why not have 2 PRs:
1. First, delete gas_consumed. when needed, use gas_for_fee (logically should be the same, but easier to review)
2. If you want, delete gas_for_fee (rename it to gas_consumed) as a second PR

WDYT?
</blockquote></details>

I don't want to mess with `gas_for_fee` for now. I aim to align the blockifier and the OS regarding `gas_consumed` (the OS needs this field).

I'll let Tzahi handle gas_for_fee once he is back (can be removed)
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2440#-ODFselO2WjV05-Eooxk:-ODGNKV98AQ-OHKFOO9A:byr4flj) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ec45d8ffaebee61444f4e10887b7ce49faab811/crates/blockifier/src/transaction/transactions_test.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

when you set `None` as the last tracked resource in these tests - is it accurate? are you only calling the tracked_resource method on outermost calls (validate/execute)?
</blockquote></details>

Right.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2440#-ODFrOgj4feD7WDLQ93a:-ODGObIn94jAHws_qmIA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ec45d8ffaebee61444f4e10887b7ce49faab811/crates/blockifier/src/execution/contract_class.rs#L149)):*
> ```XML
>             Some(TrackedResource::CairoSteps) => TrackedResource::CairoSteps,
>             Some(TrackedResource::SierraGas) => contract_tracked_resource,
>             None => contract_tracked_resource,
> ```

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2440#-ODFtMjE2LN60Su-XRae:-ODGNFwTCdNBOStRZaoc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ec45d8ffaebee61444f4e10887b7ce49faab811/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L227)):*
> ```XML
> 
>     assert_eq!(main_call_info.tracked_resource, TrackedResource::SierraGas);
>     assert!(main_call_info.execution.gas_consumed != 0);
> ```

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2440#-ODFtRF044D5yHGYsvQo:-ODGNGiZ4xTxMkuuf8Jv:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ec45d8ffaebee61444f4e10887b7ce49faab811/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L238)):*
> ```XML
>     let second_inner_call = main_call_info.inner_calls.get(1).unwrap();
>     assert_eq!(second_inner_call.tracked_resource, TrackedResource::SierraGas);
>     assert!(second_inner_call.execution.gas_consumed != 0);
> ```

Done.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2440)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2440#-ODFrDHzCXlqG4hjRTAw:-ODGRnvD7vKBPDowHYTF:br8od01) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ec45d8ffaebee61444f4e10887b7ce49faab811/crates/blockifier/src/execution/contract_class.rs#L150)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think we are not ready yet to make this change.
we currently assume sierra gas consumption is zero if the user didn't sign on L1 data gas,
so you cna't run in gas tracking mode without changing this assumption first
</blockquote></details>

Hey, I think we should keep it as-is. Let's talk F2F

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2440)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2440#-ODFrDHzCXlqG4hjRTAw:-ODGRz8O-foaOiIF5jF-:b-83arh9) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ec45d8ffaebee61444f4e10887b7ce49faab811/crates/blockifier/src/execution/contract_class.rs#L150)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Hey, I think we should keep it as-is. Let's talk F2F
</blockquote></details>

Oh no

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2440)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2440#-ODFrDHzCXlqG4hjRTAw:-ODGxSOAC7WoVoJyaEXU:b-dviq6a) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ec45d8ffaebee61444f4e10887b7ce49faab811/crates/blockifier/src/execution/contract_class.rs#L150)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Oh no
</blockquote></details>

Done in a separate PR

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2440)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
