### PR TITLE
feat(sequencing): add cetral deploy account transaction written object

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2872?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2872** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2872?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2872?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2861** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2861?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2715** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2715?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by DvirYo-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2872)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @dafnamatsry)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2872#-OF1ipMw0q5fSU8p-PaZ:-OF1ipMw0q5fSU8p-Pa_:b5nqd4t):*
cooooooooooooooooooooooooooooooooooooooonesnsus.
The subject in general, should be sequencing and not consensus



_Code quote:_
```
coonsensus
```

**Review by DvirYo-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2872)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2872)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dafnamatsry)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2872#-OF1ipMw0q5fSU8p-PaZ:-OFHJMJMCsf7kZt3mUgj:b-7rl0jf):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

cooooooooooooooooooooooooooooooooooooooonesnsus.
The subject in general, should be sequencing and not consensus
</blockquote></details>

done,

**Review by DvirYo-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2872)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Pull request merged**
