### PR TITLE
test: streamline the v0 version tx for invoke tx towards code dedup in test utils

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/747)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/747?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#749** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/749?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#748** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/748?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#747** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/747?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#672** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/672?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#519](https://github.com/starkware-libs/sequencer/pull/519) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/519?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#666** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/666?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#694](https://github.com/starkware-libs/sequencer/pull/694) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/694?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#701](https://github.com/starkware-libs/sequencer/pull/701) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/701?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#661** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/661?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#660** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/660?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/747)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/747#-O6py784CxuMVTtgTzdd:-O6py784CxuMVTtgTzde:bald4f4) (no related file):*
Can you please explain the change here?
Why does V0 have a special treatment, and why is it no longer necessary?

___

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/747)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/747#-O6py784CxuMVTtgTzdd:-O6q7RCN-EUP8nu5i8to:b-v0ig6t) (no related file):*
For version 0 transactions, the field `entry_point_selector` must always be a specific thing: 
> /// V0 transactions should always select the `__execute__` entry point.
> /// The original code from the blockifier crate was:

To compute the entry point selector value, you must use functions specifically from `blockifier::abi::abi_utils`, namely: `selector_from_name`.  In this PR, we compute the value manually, offline,  and hard code it in SNAPI.


The question becomes do we want to avoid this hard coding of a value.
The other thing we can do is move the `abi` utils into snapi.
Stuff like moving the function `starknet_keccak` into snapi - which might be fair game....

___

**Comment by ArniStarkware** [comment]
*[`crates/starknet_api/src/test_utils/invoke.rs` line 79 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/747#-OA8hWJiCAPpjalHKt6d:-OA8hWJiCAPpjalHKt6e:bx6ti2l) ([raw file](https://github.com/starkware-libs/sequencer/blob/0c39a59deca6e8c551719520ce834c2a7c782f44/crates/starknet_api/src/test_utils/invoke.rs#L79)):*
> ```XML
> }
> 
> static EXECUTE_ENTRY_POINT_SELECTOR: OnceLock<EntryPointSelector> = OnceLock::new();
> ```

Use lazylock



_Code quote:_
```XML
static EXECUTE_ENTRY_POINT_SELECTOR: OnceLock<EntryPointSelector> = OnceLock::new();
```

**Pull request closed without merging**
