### PR TITLE
feat(blockifier): add struct StateChangesCountForFee

### PR DESCRIPTION
**Pull request by yoavGrs**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2175)* status: all files reviewed, 8 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3Ry8_6oJoCtFoT-Lm:-OC3Ry8_6oJoCtFoT-Ln:b-pb0szn) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/transaction/transactions_test.rs#L0)):*
same as above: does it make sense to have nonzero values for n_allocations in this test?
___
*[`crates/blockifier/src/state/cached_state.rs` line 731 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3RGajBEMK-wZueCQO:-OC3RGajBEMK-wZueCQP:b9q2paa) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/state/cached_state.rs#L731)):*
> ```XML
>                 n_modified_contracts: modified_contracts.len(),
>             },
>             n_allocated_keys: if enable_stateful_compression {
> ```

hmmm... maybe this flag is a bit confusing...
I would expect `enable_stateful_compression` to indicate whether or not contract `0x2` appears in the state diff,
*not* whether or not we charge for allocations (which is what is happening here).
should we have two separate flags for this? @Yoni-Starkware 



_Code quote:_
```XML
n_allocated_keys: if enable_stateful_compression {
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 755 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3RAmt1vQl2AaGWufi:-OC3RAmt1vQl2AaGWufj:b-ud6wkg) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/state/cached_state.rs#L755)):*
> ```XML
> pub struct StateChangesCountForFee {
>     pub state_changes_count: StateChangesCount,
>     pub n_allocated_keys: usize,
> ```

just to be clear: this field will be computed, regardless of the `enable_stateful_compression` flag, correct?



_Code quote:_
```XML
 pub n_allocated_keys: usize,
```
___
*[`crates/blockifier/src/fee/resources.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3RcQs8iBuBo62CY6-:-OC3RcQs8iBuBo62CY60:boe0ks6) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/fee/resources.rs#L153)):*
> ```XML
>         sender_address: Option<ContractAddress>,
>         fee_token_address: ContractAddress,
>         enable_stateful_compression: bool,
> ```

consider this rename, everywhere (see below - maybe a separate flag for stateful compression?)



_Suggestion:_
```XML
charge_for_allocations: bool,
```
___
*[`crates/blockifier/src/fee/resources.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3QD3c43plaMZBszh0:-OC3QD3c43plaMZBszh1:bwg3knt) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/fee/resources.rs#L181)):*
> ```XML
>         // TODO(Nimrod, 29/3/2024): delete `get_da_gas_cost` and move it's logic here.
>         // TODO(Yoav): Add the cost of allocating keys.
>         get_da_gas_cost(&self.state_changes_for_fee.state_changes_count, use_kzg_da)
> ```

did we decide the allocation should be part of DA gas?
we show DA gas separately in the receipt, we want to charge for allocation but not necessarily make it show up as part of the DA gas vector
@Yoni-Starkware WDYT?



_Code quote:_
```XML
        // TODO(Yoav): Add the cost of allocating keys.
        get_da_gas_cost(&self.state_changes_for_fee.state_changes_count, use_kzg_da)
```
___
*[`crates/blockifier/src/fee/receipt_test.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3QSWSBKkGWuYNa_WA:-OC3QSWSBKkGWuYNa_WB:bcfyupr) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/fee/receipt_test.rs#L0)):*
any coverage benefit from making some of these values non-zero?
if so, please make some non-zero
(if tests fail: why?)
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1385 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3Rr8bBpa6U7_oVfIB:-OC3Rr8bBpa6U7_oVfIC:b71x2l9) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/transaction/account_transactions_test.rs#L1385)):*
> ```XML
>             block_context.versioned_constants.enable_stateful_compression,
>         )
>         .state_changes_count;
> ```

why take this field, and not compare the entire object?

X3 (same Q twice below)



_Code quote:_
```XML
.state_changes_count
```
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 351 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3Qxx03kroIy6plP8-:-OC3Qxx11noo76urIWIr:b-t3mhay) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/state/cached_state_test.rs#L351)):*
> ```XML
>             n_modified_contracts: 2,
>         },
>         n_allocated_keys: 0,
> ```

can you update `create_state_changes_for_test` to create some allocations and use some nonzero `X` here?



_Suggestion:_
```XML
n_allocated_keys: if enable_stateful_compression { X } else { 0 },
```

**Comment by yoavGrs** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2175?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2175** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2175?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2175?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2174** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2174?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2173** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2173?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2172** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2172?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2175)* status: 5 of 8 files reviewed, 9 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/receipt_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3QSWSBKkGWuYNa_WA:-OC3dyI72La26mAC46eh:bano9nr) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/fee/receipt_test.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

any coverage benefit from making some of these values non-zero?
if so, please make some non-zero
(if tests fail: why?)
</blockquote></details>

Done, where it makes sense.
Some tests will fail when we include the allocations in the gas computation.
___
*[`crates/blockifier/src/state/cached_state.rs` line 755 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3RAmt1vQl2AaGWufi:-OC3eZmuENu3RA1aRoyu:b1vuomh) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/state/cached_state.rs#L755)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

just to be clear: this field will be computed, regardless of the `enable_stateful_compression` flag, correct?
</blockquote></details>

No.
Under a `ForFee` struct, this field will be 0 if `not enable_stateful_compression`.
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 351 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3Qxx03kroIy6plP8-:-OC3hkFlCqRnfDusNZHb:bbs7k0v) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/state/cached_state_test.rs#L351)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you update `create_state_changes_for_test` to create some allocations and use some nonzero `X` here?
</blockquote></details>

It will create allocations when we implement the allocation logic. Look at this test here:
https://reviewable.io/reviews/starkware-libs/sequencer/2150
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1385 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3Rr8bBpa6U7_oVfIB:-OC3ivWq6Hsn4CPI2lZX:b-5bv26s) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/transaction/account_transactions_test.rs#L1385)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why take this field, and not compare the entire object?

X3 (same Q twice below)
</blockquote></details>

Changing it.
I'll set the correct number of allocations when we implement the allocation logic (2150).
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3Ry8_6oJoCtFoT-Lm:-OC3kYN69hL8xXpDLnKR:b-hpbk05) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/transaction/transactions_test.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

same as above: does it make sense to have nonzero values for n_allocations in this test?
</blockquote></details>

No allocations in invoke `return_result` / declare tx.
This is the expected value.
___
*[`crates/blockifier/src/state/cached_state.rs` line 732 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3iX7f6WuQQLZYXJf9:-OC3iX7f6WuQQLZYXJfA:b-1ohs15) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/state/cached_state.rs#L732)):*
> ```XML
>             },
>             n_allocated_keys: if enable_stateful_compression {
>                 self.allocated_keys.count()
> ```

Sorry, moving this to the next PR.



_Code quote:_
```XML
self.allocated_keys.count()
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2175)* status: all files reviewed, 3 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/state/cached_state.rs` line 755 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3RAmt1vQl2AaGWufi:-OC46RoLCZ54AbhmPtIj:bmotq9q) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/state/cached_state.rs#L755)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

No.
Under a `ForFee` struct, this field will be 0 if `not enable_stateful_compression`.
</blockquote></details>

ah, right.
but the StateChanges will count this? just not the `ForFee` flavor?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2175)* status: 1 of 8 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/cached_state.rs` line 731 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3RGajBEMK-wZueCQO:-OC7NiLR5jWnSusjQ-hT:bb0u9wy) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/state/cached_state.rs#L731)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

hmmm... maybe this flag is a bit confusing...
I would expect `enable_stateful_compression` to indicate whether or not contract `0x2` appears in the state diff,
*not* whether or not we charge for allocations (which is what is happening here).
should we have two separate flags for this? @Yoni-Starkware
</blockquote></details>

We should count the allocated keys here regardless of this flag - only charge according to it.
And yes, more readable to have two flags.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2175)* status: 1 of 8 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/cached_state.rs` line 731 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3RGajBEMK-wZueCQO:-OC7O1AhCqwTKAoAyKce:b-v780k8) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/state/cached_state.rs#L731)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

We should count the allocated keys here regardless of this flag - only charge according to it.
And yes, more readable to have two flags.
</blockquote></details>

Even better - let the second config be the cost of an allocated key, and set it to 0 for old VCs. That way we save a flag.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2175)* status: all files reviewed, 4 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC8x-Os1rb4SuQ8SQX6:-OC8x-Os1rb4SuQ8SQX7:bb7m3jc) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7d90ca7ff762dce9316d0a6dfc92c660e6547ca/crates/blockifier/src/fee/gas_usage_test.rs#L82)):*
> ```XML
>         },
>         19,
> >>>>>>> 868b6b68c (feat(blockifier): add struct StateChangesCountForFee)
> ```

oops



_Code quote:_
```XML
>>>>>>> 868b6b68c (feat(blockifier): add struct StateChangesCountForFee)
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2175)* status: all files reviewed, 3 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/fee/resources.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3QD3c43plaMZBszh0:-OC98CWGALbu1GFcqzVe:b-qeuh1h) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/fee/resources.rs#L181)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Hmmm yes but I don't want to split this part into another struct. And soon we will have L2 cost for state changes, so I think putting this under StateResources makes sense.
</blockquote></details>

unblocking here, but I'm saying that `get_da_gas_cost` should ignore allocations even in future PRs.
this function should return `get_da_gas_cost(...).checked_add(get_allocations_gas_cost(...)).expect(...)`, so we can still use `get_da_gas_cost` to represent the cost of data availability (and not starknet state allocation costs)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2175)* status: 1 of 9 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/cached_state.rs` line 731 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OCZ1c0u0QahdOYhA6TW:-OCZ1c0v-q64t86rkh7S:btnxd4s) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb121bae8c127c503b6582792b9f35ef9eeadb08/crates/blockifier/src/state/cached_state.rs#L731)):*
> ```XML
>             },
>             // TODO: Set number of allocated keys.
>             n_allocated_keys: { 0 },
> ```

What's the plan?



_Code quote:_
```XML
            // TODO: Set number of allocated keys.
            n_allocated_keys: { 0 },
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2175)* status: 1 of 9 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC8x-Os1rb4SuQ8SQX6:-OC96j886SRPJXRva8vQ:b32vhv) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7d90ca7ff762dce9316d0a6dfc92c660e6547ca/crates/blockifier/src/fee/gas_usage_test.rs#L82)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

oops
</blockquote></details>

:(
___
*[`crates/blockifier/src/fee/resources.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3RcQs8iBuBo62CY6-:-OCZ3R-pEYwjnHXjjmyv:brpmqc3) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/fee/resources.rs#L153)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

consider this rename, everywhere (see below - maybe a separate flag for stateful compression?)
</blockquote></details>

removed.
___
*[`crates/blockifier/src/fee/resources.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3QD3c43plaMZBszh0:-OC9DD0F-bGanh7Pgpy8:b-8fx2u7) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/fee/resources.rs#L181)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

unblocking here, but I'm saying that `get_da_gas_cost` should ignore allocations even in future PRs.
this function should return `get_da_gas_cost(...).checked_add(get_allocations_gas_cost(...)).expect(...)`, so we can still use `get_da_gas_cost` to represent the cost of data availability (and not starknet state allocation costs)
</blockquote></details>

:+1: 
___
*[`crates/blockifier/src/state/cached_state.rs` line 731 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3RGajBEMK-wZueCQO:-OC9CuG90NAKl-0bDro2:b-mevq6l) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/state/cached_state.rs#L731)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Even better - let the second config be the cost of an allocated key, and set it to 0 for old VCs. That way we save a flag.
</blockquote></details>

https://reviewable.io/reviews/starkware-libs/sequencer/2200
___
*[`crates/blockifier/src/state/cached_state.rs` line 755 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OC3RAmt1vQl2AaGWufi:-OC95Hyf2ziSwFJxF44B:b-30romi) ([raw file](https://github.com/starkware-libs/sequencer/blob/46a6da209c954267bbac02510fcde551e53a7c18/crates/blockifier/src/state/cached_state.rs#L755)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah, right.
but the StateChanges will count this? just not the `ForFee` flavor?
</blockquote></details>

Sorry, even in the`ForFee` struct, the real amount will appear.

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2175)* status: 1 of 9 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 731 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OCZ1c0u0QahdOYhA6TW:-OCbjoAP7Cxlw55QFtUt:b930rb1) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb121bae8c127c503b6582792b9f35ef9eeadb08/crates/blockifier/src/state/cached_state.rs#L731)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

What's the plan?
</blockquote></details>

I changed the order of the branches, and removed the TODO.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r4, 1 of 6 files at r5, 4 of 5 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-:-OCbumWwBNb5mSaMC_b1:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 17 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OCbuK5i4xSC8kZrVD8N:-OCbuK5i4xSC8kZrVD8O:baayub4) ([raw file](https://github.com/starkware-libs/sequencer/blob/2c198004d4bd7cb8482ceb12a69903aab8d00946/crates/blockifier/src/fee/resources.rs#L17)):*
> ```XML
> };
> #[cfg(any(test, feature = "testing"))]
> use crate::state::cached_state::StateChangesCount;
> ```

delete (see below)
non-blocking, it's a question of style



_Code quote:_
```XML
#[cfg(any(test, feature = "testing"))]
use crate::state::cached_state::StateChangesCount;
```
___
*[`crates/blockifier/src/fee/resources.rs` line 183 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2175#-OCbuApcEJZ-CEVwh1BK:-OCbuApcEJZ-CEVwh1BL:b-8s6iq0) ([raw file](https://github.com/starkware-libs/sequencer/blob/2c198004d4bd7cb8482ceb12a69903aab8d00946/crates/blockifier/src/fee/resources.rs#L183)):*
> ```XML
>     ) -> Self {
>         Self {
>             state_changes_for_fee: StateChangesCountForFee {
> ```

I suggest this, looks better than gating the `use` (see above)



_Suggestion:_
```XML
state_changes_for_fee: crate::state::cached_state::StateChangesCountForFee
```

**Comment by yoavGrs** [comment]
### Merge activity

* **Nov 26, 5:53 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2175).

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2175)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
