### PR TITLE
refactor(blockifier): refactor default testing resource bounds

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1306)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
* **#1308** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1308?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1307** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1307?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1306** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1306?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by dorimedini-starkware** [comment]
* **#1309** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1309?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1308** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1308?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1307** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1307?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1306** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1306?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yoavGrs — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1306)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1306#-O9DqFJn630yZxJIrtMR:-O9DqFJo9prNqzDatRgo:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/42b94c93da7a0884afe28912d82a356c882f1525/crates/blockifier/src/test_utils.rs#L100)):*
> ```XML
> // The max_fee / resource bounds used for txs in this test.
> // V3 transactions:
> pub const DEFAULT_L1_GAS_AMOUNT: GasAmount = GasAmount(1000000);
> ```





_Suggestion:_
```XML
u64::pow(10, 6)
```
___
*[`crates/blockifier/src/test_utils.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1306#-O9DtrBLDdxtkzRhD0zU:-O9DtrBLDdxtkzRhD0zV:be74u90) ([raw file](https://github.com/starkware-libs/sequencer/blob/42b94c93da7a0884afe28912d82a356c882f1525/crates/blockifier/src/test_utils.rs#L120)):*
> ```XML
> // The amount of test-token allocated to the account in this test, set to a multiple of the max
> // amount deprecated / non-deprecated transactions commit to paying.
> pub const BALANCE: Fee = Fee(10
> ```

Move this definition after `DEFAULT_ALL_BOUNDS_COMMITTED_FEE`



_Code quote:_
```XML
BALANCE
```
___
*[`crates/blockifier/src/test_utils.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1306#-O9Du70xDusHYlnFg9U5:-O9Du70xDusHYlnFg9U6:b-z5icb6) ([raw file](https://github.com/starkware-libs/sequencer/blob/42b94c93da7a0884afe28912d82a356c882f1525/crates/blockifier/src/test_utils.rs#L122)):*
> ```XML
> pub const BALANCE: Fee = Fee(10
>     * const_max(
>         const_max(DEFAULT_ALL_BOUNDS_COMMITTED_FEE.0, DEFAULT_L1_BOUNDS_COMMITTED_FEE.0),
> ```

Is there a case where`DEFAULT_ALL_BOUNDS_COMMITTED_FEE.0` < `DEFAULT_L1_BOUNDS_COMMITTED_FEE.0`?



_Code quote:_
```XML
const_max(DEFAULT_ALL_BOUNDS_COMMITTED_FEE.0, DEFAULT_L1_BOUNDS_COMMITTED_FEE.0),
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1306)* status: 9 of 13 files reviewed, 3 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/test_utils.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1306#-O9DqFJn630yZxJIrtMR:-O9E9P7B8jUy2bTrT_SO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/42b94c93da7a0884afe28912d82a356c882f1525/crates/blockifier/src/test_utils.rs#L100)):*
> ```XML
> // The max_fee / resource bounds used for txs in this test.
> // V3 transactions:
> pub const DEFAULT_L1_GAS_AMOUNT: GasAmount = GasAmount(1000000);
> ```

Done.
___
*[`crates/blockifier/src/test_utils.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1306#-O9DtrBLDdxtkzRhD0zU:-O9E9OQg7jkzkJlO13Zp:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/42b94c93da7a0884afe28912d82a356c882f1525/crates/blockifier/src/test_utils.rs#L120)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Move this definition after `DEFAULT_ALL_BOUNDS_COMMITTED_FEE`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1306#-O9Du70xDusHYlnFg9U5:-O9E7CmW2gq7hveAxxQs:b7yzo5n) ([raw file](https://github.com/starkware-libs/sequencer/blob/42b94c93da7a0884afe28912d82a356c882f1525/crates/blockifier/src/test_utils.rs#L122)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Is there a case where`DEFAULT_ALL_BOUNDS_COMMITTED_FEE.0` < `DEFAULT_L1_BOUNDS_COMMITTED_FEE.0`?
</blockquote></details>

in AllResourceBounds mode, it makes sense if the L1 gas bound is very low - even zero.
so, yes

**Review by yoavGrs — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1306#-:-O9EAmIf4HR-VnSPbkNg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
