### PR TITLE
chore(blockifier): add pre_process_and_create c-tor for TransactionEx…

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
…ecutor

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1030)

### CODE REVIEW

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1030)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1030#-O7hS0Ko4Y2TEvIVK3TW:-O7hS0Ko4Y2TEvIVK3TX:b-ltw1se) ([raw file](https://github.com/starkware-libs/sequencer/blob/d62a03bcb5e8d44bf135322c135b42283557f9e5/crates/blockifier/src/test_utils/struct_impls.rs#L145)):*
> ```XML
> 
> impl BlockNumberHashPair {
>     pub fn create_given_current(block_number: BlockNumber) -> Option<Self> {
> ```

I think that the name is misleading 



_Suggestion:_
```XML
create_dummy_given_current
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1030#-O7hSOGj0-jlFbGckWRd:-O7hSOGj0-jlFbGckWRe:b-4bjnu) ([raw file](https://github.com/starkware-libs/sequencer/blob/d62a03bcb5e8d44bf135322c135b42283557f9e5/crates/native_blockifier/src/py_block_executor.rs#L143)):*
> ```XML
>         Ok(())
>     }
> ```

I would expect papyrus_execution to use pre_process_and_create as well, but I see that they are using a completely different object there for execution.  why?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1030)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1030#-O7hS0Ko4Y2TEvIVK3TW:-O7hukSR7HBiiBcS1DZp:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d62a03bcb5e8d44bf135322c135b42283557f9e5/crates/blockifier/src/test_utils/struct_impls.rs#L145)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think that the name is misleading
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1030#-O7hSOGj0-jlFbGckWRd:-O7hukxG9ua6PM_Wkvco:bwy7ygj) ([raw file](https://github.com/starkware-libs/sequencer/blob/d62a03bcb5e8d44bf135322c135b42283557f9e5/crates/native_blockifier/src/py_block_executor.rs#L143)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I would expect papyrus_execution to use pre_process_and_create as well, but I see that they are using a completely different object there for execution.  why?
</blockquote></details>

Hmmm, I think that they need more things (e.g. state diff per tx) which is not supported atm.
Added a TODO

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1030)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @noaov1)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1030)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
