### PR TITLE
feat(mempool): add contains function to transaction pool

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/562)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/562)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/562#-O4tPD6cBSAd6Et8dXS3:-O4tPD6cBSAd6Et8dXS4:bc6tqa6) (no related file):*
will be in use in #534

___

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/562)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_pool.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/562#-O4u7WUiB1SmpLTOn6rW:-O4u7WUjEIekw-f__osD:b-lmlxp0) ([raw file](https://github.com/starkware-libs/sequencer/blob/1ca2ffe347f636313ab5f676f716b6d1d1ad6e5a/crates/mempool/src/transaction_pool.rs#L101)):*
> ```XML
> 
>     #[allow(dead_code)]
>     pub fn contains_address(&self, address: ContractAddress) -> bool {
> ```

WDYT is better?



_Suggestion:_
```XML
contains_account
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/562)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_pool.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/562#-O4u7WUiB1SmpLTOn6rW:-O4uEXC-5deIzXt1ShE9:b-vqh29w) ([raw file](https://github.com/starkware-libs/sequencer/blob/1ca2ffe347f636313ab5f676f716b6d1d1ad6e5a/crates/mempool/src/transaction_pool.rs#L101)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYT is better?
</blockquote></details>

i like account better. fixed.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/562#-:-O4uIfSxC7lX4QVGUxUS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Pull request merged**
