### PR TITLE
feat: add consensus_manager_types communication

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #326
- #325
- #324 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/324)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/324)* status: all files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/consensus_manager_types/src/communication.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/324#-O3cgnqCB1YkhwiNrd6o:-O3cgnqD8fykzxD4R5Ye:b-fk39k2) ([raw file](https://github.com/starkware-libs/sequencer/blob/4faf143e08abf1098e6e44c114f6421e55029ac1/crates/consensus_manager_types/src/communication.rs#L31)):*
> ```XML
> pub type ConsensusManagerClientResult<T> = Result<T, ConsensusManagerClientError>;
> pub type ConsensusManagerRequestAndResponseSender =
>     ComponentRequestAndResponseSender<ConsensusManagerRequest, ConsensusManagerResponse>;
> ```

What is this type? Is it the server or something else? I don't see it being used in this file.



_Code quote:_
```XML
pub type ConsensusManagerRequestAndResponseSender =
    ComponentRequestAndResponseSender<ConsensusManagerRequest, ConsensusManagerResponse>;
```
___
*[`crates/consensus_manager_types/src/communication.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/324#-O3cj74W4Y7vrZ4-UNWS:-O3cj74W4Y7vrZ4-UNWT:bcjol2h) ([raw file](https://github.com/starkware-libs/sequencer/blob/4faf143e08abf1098e6e44c114f6421e55029ac1/crates/consensus_manager_types/src/communication.rs#L84)):*
> ```XML
>             ConsensusManagerClientError,
>             ConsensusManagerError
>         )
> ```

So this macro is basically to avoid putting the 3 branch match statement in each function?

I know this PR probably isn't the right place to argue on a decision I am guessing others were involved in, but I want to state my reticence around macros. I think just putting that content directly here would be a reasonable thing to do as opposed to:
1. Adding complexity - users need to go somewhere else to see the logic and be able to read macro code.
2. Slows compilation
3. Often IDEs/LSPs have trouble with macros.



_Code quote:_
```XML
        handle_response_variants!(
            ConsensusManagerResponse,
            ConsensusManagerFnOne,
            ConsensusManagerClientError,
            ConsensusManagerError
        )
```
___
*[`crates/consensus_manager_types/src/consensus_manager_types.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/324#-O3cfcJo-qyUSNVLWJaC:-O3cfcJo-qyUSNVLWJaD:blk5p69) ([raw file](https://github.com/starkware-libs/sequencer/blob/4faf143e08abf1098e6e44c114f6421e55029ac1/crates/consensus_manager_types/src/consensus_manager_types.rs#L15)):*
> ```XML
> // TODO(Tsabary/Matan): Replace with the actual return type of the consensus manager function.
> #[derive(Debug, Serialize, Deserialize)]
> pub struct ConsensusManagerFnOneReturnValue {}
> ```

Should we make Return adjacent to its matching Input?



_Code quote:_
```XML
// TODO(Tsabary/Matan): Replace with the actual return type of the consensus manager function.
#[derive(Debug, Serialize, Deserialize)]
pub struct ConsensusManagerFnOneReturnValue {}
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/324)* status: all files reviewed, 3 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/consensus_manager_types/src/communication.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/324#-O3cgnqCB1YkhwiNrd6o:-O3fh7YV1M7ACAdK2-4s:bt9jro5) ([raw file](https://github.com/starkware-libs/sequencer/blob/4faf143e08abf1098e6e44c114f6421e55029ac1/crates/consensus_manager_types/src/communication.rs#L31)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

What is this type? Is it the server or something else? I don't see it being used in this file.
</blockquote></details>

Its usage is added in #326 

The purpose is to create the response channel for the local communication: 

The client sends the request to the server along the tx-side of a channel (of the respone type) for the server to send the response to. Then the client awaits on the rx-side of that channel for the response. 

Therefore, the "main" channel the server awaits on expects two values: the request, and the response-tx-channel. This is the type definition of that tuple.
___
*[`crates/consensus_manager_types/src/communication.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/324#-O3cj74W4Y7vrZ4-UNWS:-O3fhyvQBPqwdy54uE6G:bokpms2) ([raw file](https://github.com/starkware-libs/sequencer/blob/4faf143e08abf1098e6e44c114f6421e55029ac1/crates/consensus_manager_types/src/communication.rs#L84)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

So this macro is basically to avoid putting the 3 branch match statement in each function?

I know this PR probably isn't the right place to argue on a decision I am guessing others were involved in, but I want to state my reticence around macros. I think just putting that content directly here would be a reasonable thing to do as opposed to:
1. Adding complexity - users need to go somewhere else to see the logic and be able to read macro code.
2. Slows compilation
3. Often IDEs/LSPs have trouble with macros.
</blockquote></details>

Understandable. Please note that for each trait function (currently there are 2 for the consensus, 2 for the batcher, and 2 for the mempool, and we expect these to grow quite rapidly in the near future) we need to retype the `match` code twice -- once for the local and once for the remote impls.

So, the code duplication is already quite significant, and is expected to be much more significant, hence the justification for the macro usage.
___
*[`crates/consensus_manager_types/src/consensus_manager_types.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/324#-O3cfcJo-qyUSNVLWJaC:-O3fiZdd0hPO4-2XryFm:b-7zi8tj) ([raw file](https://github.com/starkware-libs/sequencer/blob/4faf143e08abf1098e6e44c114f6421e55029ac1/crates/consensus_manager_types/src/consensus_manager_types.rs#L15)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Should we make Return adjacent to its matching Input?
</blockquote></details>

WDYM?

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/324)* status: all files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/consensus_manager_types/src/communication.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/324#-O3cgnqCB1YkhwiNrd6o:-O3g3BuxEDR2gieX6UJF:b-sgqq7o) ([raw file](https://github.com/starkware-libs/sequencer/blob/4faf143e08abf1098e6e44c114f6421e55029ac1/crates/consensus_manager_types/src/communication.rs#L31)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Its usage is added in #326 

The purpose is to create the response channel for the local communication: 

The client sends the request to the server along the tx-side of a channel (of the respone type) for the server to send the response to. Then the client awaits on the rx-side of that channel for the response. 

Therefore, the "main" channel the server awaits on expects two values: the request, and the response-tx-channel. This is the type definition of that tuple.
</blockquote></details>

Oh. I was reading this as (Request and Response)Sender. It is (Request)and(ResponseSender)
___
*[`crates/consensus_manager_types/src/communication.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/324#-O3cj74W4Y7vrZ4-UNWS:-O3g0ibVDnXHJTQEG7jv:bn2t1hk) ([raw file](https://github.com/starkware-libs/sequencer/blob/4faf143e08abf1098e6e44c114f6421e55029ac1/crates/consensus_manager_types/src/communication.rs#L84)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Understandable. Please note that for each trait function (currently there are 2 for the consensus, 2 for the batcher, and 2 for the mempool, and we expect these to grow quite rapidly in the near future) we need to retype the `match` code twice -- once for the local and once for the remote impls.

So, the code duplication is already quite significant, and is expected to be much more significant, hence the justification for the macro usage.
</blockquote></details>

IIUC you are saying that this macro is used in many place: `num_fn_in_trait * 2` (2 = local + remote)?

Therefore even if it provides a small benefit in a given location, this is multiplied by the number of usage sites. Is that the gist?
___
*[`crates/consensus_manager_types/src/consensus_manager_types.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/324#-O3cfcJo-qyUSNVLWJaC:-O3g0UbgCqtCq-JCnH4j:b-u4g0nv) ([raw file](https://github.com/starkware-libs/sequencer/blob/4faf143e08abf1098e6e44c114f6421e55029ac1/crates/consensus_manager_types/src/consensus_manager_types.rs#L15)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

```
// TODO(Tsabary/Matan): Populate the data structure used to invoke the consensus manager.
#[derive(Debug, Serialize, Deserialize)]
pub struct ConsensusManagerFnOneInput {}

// TODO(Tsabary/Matan): Replace with the actual return type of the consensus manager function.
#[derive(Debug, Serialize, Deserialize)]
pub struct ConsensusManagerFnOneReturnValue {}

// TODO(Tsabary/Matan): Populate the data structure used to invoke the consensus manager.
#[derive(Debug, Serialize, Deserialize)]
pub struct ConsensusManagerFnTwoInput {}

// TODO(Tsabary/Matan): Replace with the actual return type of the consensus manager function.
#[derive(Debug, Serialize, Deserialize)]
pub struct ConsensusManagerFnTwoReturnValue {}

```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/324)* status: all files reviewed, 3 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/consensus_manager_types/src/communication.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/324#-O3cgnqCB1YkhwiNrd6o:-O3g4gGt2vd8e34CApFW:bqgq1fx) ([raw file](https://github.com/starkware-libs/sequencer/blob/4faf143e08abf1098e6e44c114f6421e55029ac1/crates/consensus_manager_types/src/communication.rs#L31)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Oh. I was reading this as (Request and Response)Sender. It is (Request)and(ResponseSender)
</blockquote></details>

Yes. I hate this name as well. Suggestions are more than welcome.
___
*[`crates/consensus_manager_types/src/communication.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/324#-O3cj74W4Y7vrZ4-UNWS:-O3g4lHW858sgpk3_L1V:btierea) ([raw file](https://github.com/starkware-libs/sequencer/blob/4faf143e08abf1098e6e44c114f6421e55029ac1/crates/consensus_manager_types/src/communication.rs#L84)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

IIUC you are saying that this macro is used in many place: `num_fn_in_trait * 2` (2 = local + remote)?

Therefore even if it provides a small benefit in a given location, this is multiplied by the number of usage sites. Is that the gist?
</blockquote></details>

Yes, precisely: `(num_fn_in_consensus_trait + num_fn_in_batcher_trait + num_fn_in_mempool_trait + ...) * 2`
___
*[`crates/consensus_manager_types/src/consensus_manager_types.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/324#-O3cfcJo-qyUSNVLWJaC:-O3g55e50Gu3ucZGCme3:b-owqa9d) ([raw file](https://github.com/starkware-libs/sequencer/blob/4faf143e08abf1098e6e44c114f6421e55029ac1/crates/consensus_manager_types/src/consensus_manager_types.rs#L15)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

```
// TODO(Tsabary/Matan): Populate the data structure used to invoke the consensus manager.
#[derive(Debug, Serialize, Deserialize)]
pub struct ConsensusManagerFnOneInput {}

// TODO(Tsabary/Matan): Replace with the actual return type of the consensus manager function.
#[derive(Debug, Serialize, Deserialize)]
pub struct ConsensusManagerFnOneReturnValue {}

// TODO(Tsabary/Matan): Populate the data structure used to invoke the consensus manager.
#[derive(Debug, Serialize, Deserialize)]
pub struct ConsensusManagerFnTwoInput {}

// TODO(Tsabary/Matan): Replace with the actual return type of the consensus manager function.
#[derive(Debug, Serialize, Deserialize)]
pub struct ConsensusManagerFnTwoReturnValue {}

```
</blockquote></details>

I probably do not understan your question, so here is a general explanation of my intent that hopefully addresses the issue:

The trait defines a function that takes a parameter and has a return type. 
The quoted definitions define these types.
Change them accordingly to your desired types.
I suggest encapsulating the actual content in these structs, such

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/324)* status: all files reviewed, 3 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/consensus_manager_types/src/consensus_manager_types.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/324#-O3cfcJo-qyUSNVLWJaC:-O3gVijDA7Gh4E8o2fWu:b-7s092a) ([raw file](https://github.com/starkware-libs/sequencer/blob/4faf143e08abf1098e6e44c114f6421e55029ac1/crates/consensus_manager_types/src/consensus_manager_types.rs#L15)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I probably do not understan your question, so here is a general explanation of my intent that hopefully addresses the issue:

The trait defines a function that takes a parameter and has a return type. 
The quoted definitions define these types.
Change them accordingly to your desired types.
I suggest encapsulating the actual content in these structs, such
</blockquote></details>

* that future changes do not require changing the infra code, only the inner struct definitions.

**Review by matan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/324)* status: all files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/consensus_manager_types/src/communication.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/324#-O3cgnqCB1YkhwiNrd6o:-O3gvwgZ1d9qF9xT0Xd8:b-5sa6s4) ([raw file](https://github.com/starkware-libs/sequencer/blob/4faf143e08abf1098e6e44c114f6421e55029ac1/crates/consensus_manager_types/src/communication.rs#L31)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Yes. I hate this name as well. Suggestions are more than welcome.
</blockquote></details>

Not in love with any of these, just throwing out ideas.
- ConsensusManagerRequestAndResponder
- ConsensusManagerRequestEnvelope
- ConsensusManagerRequestPackage
___
*[`crates/consensus_manager_types/src/communication.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/324#-O3cj74W4Y7vrZ4-UNWS:-O3gwIiM9SDq-RBxt-Js:b-oq2atx) ([raw file](https://github.com/starkware-libs/sequencer/blob/4faf143e08abf1098e6e44c114f6421e55029ac1/crates/consensus_manager_types/src/communication.rs#L84)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Yes, precisely: `(num_fn_in_consensus_trait + num_fn_in_batcher_trait + num_fn_in_mempool_trait + ...) * 2`
</blockquote></details>

I will accept my biases and not block. Harumph
___
*[`crates/consensus_manager_types/src/consensus_manager_types.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/324#-O3cfcJo-qyUSNVLWJaC:-O3gwdzh0btEGdM8-g1I:bymq3s9) ([raw file](https://github.com/starkware-libs/sequencer/blob/4faf143e08abf1098e6e44c114f6421e55029ac1/crates/consensus_manager_types/src/consensus_manager_types.rs#L15)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

* that future changes do not require changing the infra code, only the inner struct definitions.
</blockquote></details>

I was just asking about the order that we listed the structs in this file. 
- Why: Input1, Input2, Return1, Return2
- Instead of: Input1, Return1, Input2, Return2

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/324)* status: all files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/consensus_manager_types/src/consensus_manager_types.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/324#-O3cfcJo-qyUSNVLWJaC:-O3h-gnc0OnP_XRXfFB-:by63hds) ([raw file](https://github.com/starkware-libs/sequencer/blob/4faf143e08abf1098e6e44c114f6421e55029ac1/crates/consensus_manager_types/src/consensus_manager_types.rs#L15)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I was just asking about the order that we listed the structs in this file. 
- Why: Input1, Input2, Return1, Return2
- Instead of: Input1, Return1, Input2, Return2
</blockquote></details>

No particular reason, change as you see fit when filling in the actual types.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/324)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/consensus_manager_types/src/communication.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/324#-O3cgnqCB1YkhwiNrd6o:-O3h0-7S4HePE4aYC14I:b-ft2ago) ([raw file](https://github.com/starkware-libs/sequencer/blob/4faf143e08abf1098e6e44c114f6421e55029ac1/crates/consensus_manager_types/src/communication.rs#L31)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Not in love with any of these, just throwing out ideas.
- ConsensusManagerRequestAndResponder
- ConsensusManagerRequestEnvelope
- ConsensusManagerRequestPackage
</blockquote></details>

Thanks, will consult with the team.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/324)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#326](https://github.com/starkware-libs/sequencer/pull/326)

**Pull request closed without merging**
