### PR TITLE
fix: add missing features to dependencies serde and hyper

### PR DESCRIPTION
**Pull request by uriel-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?
mempool_infra crate does not compile because it is missing dependencies features.

Issue Number: N/A

## What is the new behavior?
mempool_infra crate is now compiling successfully

-

## Does this introduce a breaking change?

- [ ] Yes
-[x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/71)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/71)* status: all files reviewed, 1 unresolved discussion (waiting on @uriel-starkware)

___
*[`Cargo.toml` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/71#-O2d5RDACX9znJ2oRFGb:-O2d7XBV3CMqUx_n_3yK:bu4gtlk) ([raw file](https://github.com/starkware-libs/sequencer/blob/57857f5d973b9c0ed4647e96d0ec9bb2cb73224a/Cargo.toml#L89)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I'm in favour. Who is to decide this?
</blockquote></details>

Common sense? :)
Please move this constraint to `mempool_infra/Cargo.toml`.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/71)* status: all files reviewed, 1 unresolved discussion (waiting on @uriel-starkware)

___
*[`Cargo.toml` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/71#-O2d5RDACX9znJ2oRFGb:-O2d7gK9EfgryGk0ctOK:b-i56ill) ([raw file](https://github.com/starkware-libs/sequencer/blob/57857f5d973b9c0ed4647e96d0ec9bb2cb73224a/Cargo.toml#L89)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Common sense? :)
Please move this constraint to `mempool_infra/Cargo.toml`.
</blockquote></details>

Unless I'm missing something and CI won't pass.

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/71)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`Cargo.toml` line 89 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/71#-O2d5RDACX9znJ2oRFGb:-O2d8j7rB3mZJ2WTMSRq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/57857f5d973b9c0ed4647e96d0ec9bb2cb73224a/Cargo.toml#L89)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Unless I'm missing something and CI won't pass.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/71#-:-O2dBGjvAUh24VUgGCET:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
