### PR TITLE
refactor(base_layer): remove unnecessary option + dep

### PR DESCRIPTION
**Pull request by giladchase**
commit-id:19ed8b4a

---

**Stack**:
- #869
- #856
- #855
- #849 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/849)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @elintul)

___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/849#-O73KxMX1GME4JZ-LDKY:-O73KxMX1GME4JZ-LDKZ:b-rve7kd) ([raw file](https://github.com/starkware-libs/sequencer/blob/76027f0792070798fff7d5065caffa9dbcc3caf1/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L94)):*
> ```XML
>     async fn latest_proved_block(
>         &self,
>         min_confirmations: Option<u64>,
> ```

Rename ok?

Also since most usages will likely require `finality` (?) I suggest adding a separate `latest_proved_block_no_finality` and keep finality non-optional here, WDYT?



_Suggestion:_
```XML
    async fn latest_proved_block(
        &self,
        finality: Option<u64>,
```

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/849)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @giladchase)

___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/849#-O73KxMX1GME4JZ-LDKY:-O73_MAr1tgs5pO0bnFr:b-qzovck) ([raw file](https://github.com/starkware-libs/sequencer/blob/76027f0792070798fff7d5065caffa9dbcc3caf1/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L94)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Rename ok?

Also since most usages will likely require `finality` (?) I suggest adding a separate `latest_proved_block_no_finality` and keep finality non-optional here, WDYT?
</blockquote></details>

Rename's good; not sure I understand the following suggestion.
___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/849#-O73_9PL4TZ4b0bm-d_i:-O73_9PL4TZ4b0bm-d_j:b-6j7mct) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0d9b76a99d7a76c18819e38b694d3ff26959a10/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L84)):*
> ```XML
> 
>         // The solidity contract was pre-compiled, and only the relevant functions were kept.
>         let abi = serde_json::from_str(include_str!("core_contract_latest_block.abi"))?;
> ```

How come neither annotation nor turbofish is needed? :grimacing:

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/849)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @giladchase)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/849)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @elintul)

___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/849#-O73KxMX1GME4JZ-LDKY:-O73bM5TCmvTV48LMq1G:b-5pf1xe) ([raw file](https://github.com/starkware-libs/sequencer/blob/76027f0792070798fff7d5065caffa9dbcc3caf1/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L94)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Rename's good; not sure I understand the following suggestion.
</blockquote></details>

i'm wondering if `Option` is faithfully representing common usage.

If vast majority of use cases need finality, then it is misleading and unnecessarily cumbersome, and we can just do `fn latest_proved_block(&self, finality: u64)`, and add an additional function for the few edge cases that need 0 finality:
```rust
fn latest_proved_block_no_finality(&self) {
   let finality = 0;
   self.latest_proved_block(finality)
}
```
___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/849#-O73_9PL4TZ4b0bm-d_i:-O73agBW6FS5FLodyF9-:b-ypg2v3) ([raw file](https://github.com/starkware-libs/sequencer/blob/e0d9b76a99d7a76c18819e38b694d3ff26959a10/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L84)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How come neither annotation nor turbofish is needed? :grimacing:
</blockquote></details>

So two things, first of all adding both is unnecessary, only one of them suffices when type can't be inferred.
However (and that is the second thing) here type can be inferred, from the type of the field in `ContractInstance`.

I went back and forth on this one for a bit, but since I need a whole new dependency (`alloy-json-abi`) just for this annotation, I felt that going without annotation is worth it.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/849)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @giladchase)

___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/849#-O73KxMX1GME4JZ-LDKY:-O74_NnS6LjwC5LxgZa4:b-d1mavx) ([raw file](https://github.com/starkware-libs/sequencer/blob/76027f0792070798fff7d5065caffa9dbcc3caf1/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L94)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

i'm wondering if `Option` is faithfully representing common usage.

If vast majority of use cases need finality, then it is misleading and unnecessarily cumbersome, and we can just do `fn latest_proved_block(&self, finality: u64)`, and add an additional function for the few edge cases that need 0 finality:
```rust
fn latest_proved_block_no_finality(&self) {
   let finality = 0;
   self.latest_proved_block(finality)
}
```
</blockquote></details>

I think `0` can represent no finality, no reason for `None`; unless I'm missing something.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/849)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @elintul)

___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/849#-O73KxMX1GME4JZ-LDKY:-O74k-8-6W4AODrj8qrZ:boqejpb) ([raw file](https://github.com/starkware-libs/sequencer/blob/76027f0792070798fff7d5065caffa9dbcc3caf1/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L94)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think `0` can represent no finality, no reason for `None`; unless I'm missing something.
</blockquote></details>

yr right, added at the top of the stack, diff is big'ish

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/849#-:-O78IjJs3jmHsA9dNJcQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/849)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @giladchase)

___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 97 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/849#-O78Iz0a-qCoFwSB-9eL:-O78Iz0b5KVIoHdexT8m:bhyk8yn) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0ce810412feb4347b5960f268847ca9a750f834/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L97)):*
> ```XML
>     async fn latest_proved_block(
>         &self,
>         finality: Option<u64>,
> ```

Planning to remove `Option`?



_Code quote:_
```XML
finality: Option<u64>,
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/849)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 97 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/849#-O78Iz0a-qCoFwSB-9eL:-O78PvbR9ftlGd-aRgg3:b-wdqzol) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0ce810412feb4347b5960f268847ca9a750f834/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L97)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Planning to remove `Option`?
</blockquote></details>

Done at the[ end of the stack](https://reviewable.io/reviews/starkware-libs/sequencer/869), diff is too distinct

**Pull request merged**
