### PR TITLE
chore(blockifier): add gas cost for ecdsa

### PR DESCRIPTION
**Pull request by Yonatan-Starkware**

### CODE REVIEW

**Comment by Yonatan-Starkware** [comment]
* **#2502** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2502?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2502?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by meship-starkware — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2502)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware and @Yoni-Starkware)

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2502)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @Yonatan-Starkware, and @Yoni-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2502#-ODMwxrZE6UYKIRHFYAq:-ODMwxrZE6UYKIRHFYAr:bca3ozv) (no related file):*
Open a Python side

**Review by Yonatan-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2502)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2502#-ODMwxrZE6UYKIRHFYAq:-OD_CtGI0in02o8-3xA5:b-896fix) (no related file):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Open a Python side
</blockquote></details>

Done.

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2502)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware and @Yoni-Starkware)

**Pull request merged**
