### PR TITLE
refactor(starknet_api): add contract class version to sierra contract

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2277)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 986 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCbZVyTEcvfnjveIACC:-OCbZVyTEcvfnjveIACD:bpr7vyr) ([raw file](https://github.com/starkware-libs/sequencer/blob/851feacd4d273f82bfefe1cc7b196d3cf5be06a4/crates/papyrus_storage/src/serialization/serializers.rs#L986)):*
> ```XML
>             )?,
>             abi: String::deserialize_from(&mut decompress_from_reader(bytes)?.as_slice())?,
>             contract_class_version: String::deserialize_from(bytes)?,
> ```

Seems like you need to keep the order here



_Code quote:_
```XML
    fn deserialize_from(bytes: &mut impl std::io::Read) -> Option<Self> {
        Some(Self {
            sierra_program: Vec::<Felt>::deserialize_from(
                &mut decompress_from_reader(bytes)?.as_slice(),
            )?,
            entry_points_by_type: HashMap::<EntryPointType, Vec<EntryPoint>>::deserialize_from(
                bytes,
            )?,
            abi: String::deserialize_from(&mut decompress_from_reader(bytes)?.as_slice())?,
            contract_class_version: String::deserialize_from(bytes)?,
```
___
*[`crates/starknet_api/src/state.rs` line 218 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCb_BypCiPVNIJLqp1I:-OCb_BypCiPVNIJLqp1J:bngvc8i) ([raw file](https://github.com/starkware-libs/sequencer/blob/851feacd4d273f82bfefe1cc7b196d3cf5be06a4/crates/starknet_api/src/state.rs#L218)):*
> ```XML
>     pub entry_points_by_type: HashMap<EntryPointType, Vec<EntryPoint>>,
>     pub abi: String,
>     pub contract_class_version: String,
> ```

To be consistent with the compiler's struct



_Suggestion:_
```XML
    pub sierra_program: Vec<Felt>,
    pub contract_class_version: String,
    pub entry_points_by_type: HashMap<EntryPointType, Vec<EntryPoint>>,
    pub abi: String,
```
___
*[`crates/papyrus_storage/src/utils_test.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCbZFw08nWoaKDIrYjD:-OCbZFw13LepYXRzI99G:b-1qrzfn) ([raw file](https://github.com/starkware-libs/sequencer/blob/851feacd4d273f82bfefe1cc7b196d3cf5be06a4/crates/papyrus_storage/src/utils_test.rs#L34)):*
> ```XML
>             ClassHash(i_felt),
>             SierraContractClass {
>                 contract_class_version: "".to_string(),
> ```

Let it be "0.1.0"



_Code quote:_
```XML
"".to_string(),
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2277)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 986 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCbZVyTEcvfnjveIACC:-OCb_ZjMB5mYxwOIn97M:b-hoh7cc) ([raw file](https://github.com/starkware-libs/sequencer/blob/851feacd4d273f82bfefe1cc7b196d3cf5be06a4/crates/papyrus_storage/src/serialization/serializers.rs#L986)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Seems like you need to keep the order here
</blockquote></details>

the order of the fields?

**Review by Yoni-Starkware — COMMENTED** [review]
Are you removing the duplicated object in a separate PR?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-:-OCbbLxy56m8VV88IBIE:bci6fhg)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2277)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 986 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCbZVyTEcvfnjveIACC:-OCbebWx2F5Kfe2Cznsf:b2nhswy) ([raw file](https://github.com/starkware-libs/sequencer/blob/851feacd4d273f82bfefe1cc7b196d3cf5be06a4/crates/papyrus_storage/src/serialization/serializers.rs#L986)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

the order of the fields?
</blockquote></details>

Yes
___
*[`crates/starknet_client/src/reader/objects/state.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCbelCd17m6h-_1hLwG:-OCbelCeEr85wLP-kDmI:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/2295fe7ae770d5c178819c31b732af5b36bd9811/crates/starknet_client/src/reader/objects/state.rs#L71)):*
> ```XML
>             contract_class_version: class.contract_class_version,
>             sierra_program: class.sierra_program,
>             entry_points_by_type: class.entry_points_by_type,
> ```





_Suggestion:_
```XML
        Self {
            sierra_program: class.sierra_program,
            contract_class_version: class.contract_class_version,
            entry_points_by_type: class.entry_points_by_type,
```
___
*[`crates/papyrus_test_utils/src/lib.rs` line 503 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCbehI_5ObD61WkFQa6:-OCbehI_5ObD61WkFQa7:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/2295fe7ae770d5c178819c31b732af5b36bd9811/crates/papyrus_test_utils/src/lib.rs#L503)):*
> ```XML
>         pub entry_points_by_type: HashMap<EntryPointType, Vec<EntryPoint>>,
>         pub abi: String,
>         pub contract_class_version: String,
> ```





_Suggestion:_
```XML
    pub struct SierraContractClass {
        pub sierra_program: Vec<Felt>,
        pub contract_class_version: String,
        pub entry_points_by_type: HashMap<EntryPointType, Vec<EntryPoint>>,
        pub abi: String,
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2277)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/utils.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCbeAIxBoDpqyfjnIxR:-OCbhBXKDL5U_elgrP40:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2295fe7ae770d5c178819c31b732af5b36bd9811/crates/papyrus_storage/src/utils.rs#L31)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Keep the order consistent
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/utils.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCbeIYV04I_mPoK4H0h:-OCbhIQ6CHSul6imLpZq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2295fe7ae770d5c178819c31b732af5b36bd9811/crates/papyrus_storage/src/utils.rs#L82)):*
> ```XML
>                             compiled_class_hash: *compiled_class_hash,
>                             sierra_program: contract_class.sierra_program.clone(),
>                             entry_points_by_type: contract_class.entry_points_by_type.clone(),
> ```

Done.
___
*[`crates/papyrus_test_utils/src/lib.rs` line 503 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCbehI_5ObD61WkFQa6:-OCbgVtEAMq27iBTfYQO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2295fe7ae770d5c178819c31b732af5b36bd9811/crates/papyrus_test_utils/src/lib.rs#L503)):*
> ```XML
>         pub entry_points_by_type: HashMap<EntryPointType, Vec<EntryPoint>>,
>         pub abi: String,
>         pub contract_class_version: String,
> ```

Done.
___
*[`crates/starknet_client/src/reader/objects/state.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCbelCd17m6h-_1hLwG:-OCbhkiU8-s6S1x4rnmr:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2295fe7ae770d5c178819c31b732af5b36bd9811/crates/starknet_client/src/reader/objects/state.rs#L71)):*
> ```XML
>             contract_class_version: class.contract_class_version,
>             sierra_program: class.sierra_program,
>             entry_points_by_type: class.entry_points_by_type,
> ```

Done.

**Review by Yoni-Starkware — APPROVED** [review]
Don't forget to delete RpcContractClass :lgtm: 

> Reviewed 1 of 6 files at r1, 2 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-:-OCbooAo4P9gjHxYEQ2T:bwf45oj)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 3 of 4 files at r2, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2277)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/papyrus_storage/src/utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCbeQkHBCBj4WLoSXmc:-OCbpGc38IzSBmV-ID4Z:b-uy0htp) ([raw file](https://github.com/starkware-libs/sequencer/blob/2295fe7ae770d5c178819c31b732af5b36bd9811/crates/papyrus_storage/src/utils.rs#L26)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Non blocking
</blockquote></details>

The struct `DumpDeclaredClass` can be deleted. I will delete it in a different PR.
___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 972 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCbphbVAau0pqzCHY-J:-OCbphbVAau0pqzCHY-K:b9lu800) ([raw file](https://github.com/starkware-libs/sequencer/blob/3893a2712337a404ad44775cb05e0f85daf40c95/crates/papyrus_storage/src/serialization/serializers.rs#L972)):*
> ```XML
>     fn serialize_into(&self, res: &mut impl std::io::Write) -> Result<(), StorageSerdeError> {
>         serialize_and_compress(&self.sierra_program)?.serialize_into(res)?;
>         self.contract_class_version.serialize_into(res)?;
> ```

This is a breaking change to the storage. We should discuss this.
A few months ago, we decided to break the storage in version 13.3. I don't know what was agreed upon about the storage in 13.3 and 13.4, but it is fine if we break the storage in 13.4.
___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 209 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCboqHV7oIex3qK284D:-OCboqHV7oIex3qK284E:b3g5y6f) ([raw file](https://github.com/starkware-libs/sequencer/blob/3893a2712337a404ad44775cb05e0f85daf40c95/crates/papyrus_protobuf/src/converters/class.rs#L209)):*
> ```XML
>         let sierra_program =
>             value.program.into_iter().map(Felt::try_from).collect::<Result<Vec<_>, _>>()?;
> ```

Make sure with @ShahakShama it is fine (I don't think should be a problem here)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2277)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 972 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCbphbVAau0pqzCHY-J:-OCbrYGI4TetLHrsd_65:bpf288j) ([raw file](https://github.com/starkware-libs/sequencer/blob/3893a2712337a404ad44775cb05e0f85daf40c95/crates/papyrus_storage/src/serialization/serializers.rs#L972)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

This is a breaking change to the storage. We should discuss this.
A few months ago, we decided to break the storage in version 13.3. I don't know what was agreed upon about the storage in 13.3 and 13.4, but it is fine if we break the storage in 13.4.
</blockquote></details>

I think that we initialize papyrus with each new version, right? @Yoni-Starkware

**Review by AvivYossef-starkware — COMMENTED** [review]
Just two more PRS to reach it.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-:-OCbrtgT32Pub4ojF-od:b-pgflmg)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2277)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/serialization/serializers.rs` line 972 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCbphbVAau0pqzCHY-J:-OCbunRW8hVvVOSdISeH:b-jm49b1) ([raw file](https://github.com/starkware-libs/sequencer/blob/3893a2712337a404ad44775cb05e0f85daf40c95/crates/papyrus_storage/src/serialization/serializers.rs#L972)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

I think that we initialize papyrus with each new version, right? @Yoni-Starkware
</blockquote></details>

@AvivYossef-starkware not necessarily but we would have to do this for this version since we need all the Sierra classes. So LGTM

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2277)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @DvirYo-starkware)

___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 209 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCboqHV7oIex3qK284D:-OCce6ju0J_18Y2ymZQO:b-8leyts) ([raw file](https://github.com/starkware-libs/sequencer/blob/3893a2712337a404ad44775cb05e0f85daf40c95/crates/papyrus_protobuf/src/converters/class.rs#L209)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Make sure with @ShahakShama it is fine (I don't think should be a problem here)
</blockquote></details>

Now the conversion to protobuf isn't the inverse of the conversion from protobuf. Fix the other conversion (I'll put a comment there
___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 292 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCcecMp5PBZweOoD7ap:-OCcecMp5PBZweOoD7aq:brj1kc9) ([raw file](https://github.com/starkware-libs/sequencer/blob/3893a2712337a404ad44775cb05e0f85daf40c95/crates/papyrus_protobuf/src/converters/class.rs#L292)):*
> ```XML
>         });
> 
>         let contract_class_version = format!(
> ```

Remove this, and extract the contract_class_version from value instead

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2277)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware, @ShahakShama, and @Yoni-Starkware)

___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 292 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCcecMp5PBZweOoD7ap:-OCclAr41sUUopfBFF19:b9xgf36) ([raw file](https://github.com/starkware-libs/sequencer/blob/3893a2712337a404ad44775cb05e0f85daf40c95/crates/papyrus_protobuf/src/converters/class.rs#L292)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this, and extract the contract_class_version from value instead
</blockquote></details>

Thanks, consider adding a test to enforce this.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-:-OCg_mxvE-hKZNrk2-lm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 292 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2277#-OCcecMp5PBZweOoD7ap:-OCg_hCtESn2wLI5IgLc:b-np09lv) ([raw file](https://github.com/starkware-libs/sequencer/blob/3893a2712337a404ad44775cb05e0f85daf40c95/crates/papyrus_protobuf/src/converters/class.rs#L292)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Thanks, consider adding a test to enforce this.
</blockquote></details>

There's a TODO to add that test (FYI @noamsp-starkware )

**Pull request merged**
