### PR TITLE
feat: use the command line compiler in gateway

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/599)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/599?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#599** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/599?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#598** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/598?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#597** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/597?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#566** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/566?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#331](https://github.com/starkware-libs/sequencer/pull/331) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/331?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#581](https://github.com/starkware-libs/sequencer/pull/581) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/581?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/599)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/gateway/build.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/599#-O5HcBjz8Vc-fm7OsEhh:-O5HcBjz8Vc-fm7OsEhi:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/efe83f3a818fc1c91270720a83452ddbcd477f49/crates/gateway/build.rs#L1)):*
> ```XML
> // Sets up the environment variable OUT_DIR.
> ```





_Suggestion:_
```XML
// Sets up the environment variable OUT_DIR, which holds the cairo compiler binary.
// The binary is dowloaded to OUT_DIR by the starknet_sierra_compile crate.
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/599#-O5Hf13FDveVh4g8g4Wr:-O5Hf13FDveVh4g8g4Ws:b-6zr2e6) ([raw file](https://github.com/starkware-libs/sequencer/blob/efe83f3a818fc1c91270720a83452ddbcd477f49/crates/gateway/src/stateful_transaction_validator_test.rs#L85)):*
> ```XML
>     stateful_validator: StatefulTransactionValidator,
> ) {
>     let optional_class_info =
> ```

Can you add the optional_class_info as a case argument and set it to None?
i.e.:



_Suggestion:_
```XML
#[case::invalid_tx(invoke_tx(CairoVersion::Cairo1), Err(STATEFUL_VALIDATOR_FEE_ERROR)), None]
fn test_stateful_tx_validator(
    #[case] external_tx: RpcTransaction,
    #[case] expected_result: BlockifierStatefulValidatorResult<ValidateInfo>,
    #[case] class_info: Option<ClassInfo>,
    stateful_validator: StatefulTransactionValidator,
) {
```
___
*[`crates/tests-integration/build.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/599#-O5HfQn32H97EVGRIkfk:-O5HfQn32H97EVGRIkfl:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/efe83f3a818fc1c91270720a83452ddbcd477f49/crates/tests-integration/build.rs#L2)):*
> ```XML
> // Sets up the environment variable OUT_DIR. This is necessary for for the crate
> // starknet_sierra_compile.
> ```





_Suggestion:_
```XML
// Sets up the environment variable OUT_DIR. This is necessary for for the crate
// starknet_sierra_compile to download the cairo compiler binary.
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/599)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/gateway/build.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/599#-O5HcBjz8Vc-fm7OsEhh:-O5I2r-XEBSSd5NB2y0K:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/efe83f3a818fc1c91270720a83452ddbcd477f49/crates/gateway/build.rs#L1)):*
> ```XML
> // Sets up the environment variable OUT_DIR.
> ```

Done.
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/599#-O5Hf13FDveVh4g8g4Wr:-O5I60Au-NKQFWZdDD2A:bda5ty3) ([raw file](https://github.com/starkware-libs/sequencer/blob/efe83f3a818fc1c91270720a83452ddbcd477f49/crates/gateway/src/stateful_transaction_validator_test.rs#L85)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can you add the optional_class_info as a case argument and set it to None?
i.e.:
</blockquote></details>

Done.
Even better.
___
*[`crates/tests-integration/build.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/599#-O5HfQn32H97EVGRIkfk:-O5I35QM2xwR3z0cG20k:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/efe83f3a818fc1c91270720a83452ddbcd477f49/crates/tests-integration/build.rs#L2)):*
> ```XML
> // Sets up the environment variable OUT_DIR. This is necessary for for the crate
> // starknet_sierra_compile.
> ```

Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/599#-:-O5I_2FY3qnYE97orqs7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/599)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Sep 3, 2:07 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/599).

**Pull request merged**
