### PR TITLE
feat(mempool): add resource bounds to transaction reference type

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/437)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/437)* status: 0 of 3 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/437#-O4FJvWCD0lDX07DfPLz:-O4FJvWCD0lDX07DfPM-:b3da800) (no related file):*
This PR adds resource_bounds to the transaction reference; this field will be used to check the gas price.
As resource_bounds doesn't implement `Copy`, I removed `Copy` from `TransactionReference`.

___

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/437)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/437#-O4FJvWCD0lDX07DfPLz:-O4Jj2f_Em5xBvnqtN46:b-qyd9ix) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

This PR adds resource_bounds to the transaction reference; this field will be used to check the gas price.
As resource_bounds doesn't implement `Copy`, I removed `Copy` from `TransactionReference`.
</blockquote></details>

Can you ping Dori about the Copy thing? i think Meshi started implementing Copy on ResourceBoundsMapping, and she told me the task was passed to Dori's team

___

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/437)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/437#-O4FJvWCD0lDX07DfPLz:-O4KQcUG5zeE5uxeM06V:b-gpjpty) (no related file):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can you ping Dori about the Copy thing? i think Meshi started implementing Copy on ResourceBoundsMapping, and she told me the task was passed to Dori's team
</blockquote></details>

Asked him, till then I think I can merge this PR.
Do you prefer deref on clone?

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/437)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/437#-O4d9UmE0AlnYWDfhomD:-O4d9UmE0AlnYWDfhomE:bgb8xtb) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcb733dc9048a7584ffa5e08eadb49484cacaf05/crates/mempool/src/mempool.rs#L113)):*
> ```XML
> 
>             if self.tx_queue.get_nonce(address).is_none() {
>                 if let Some(tx) = self.tx_pool.get_by_address_and_nonce(address, next_nonce) {
> ```

Throughout the code (also in `transaction_queue.rs` below); `tx.clone()` should not appear.



_Suggestion:_
```XML
tx_reference
```
___
*[`crates/mempool/src/mempool.rs` line 218 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/437#-O4d9ICXD4aIyzeQDLPN:-O4d9ICYCosrb0RdkGWY:b2sskhj) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcb733dc9048a7584ffa5e08eadb49484cacaf05/crates/mempool/src/mempool.rs#L218)):*
> ```XML
> /// TODO(Mohammad): rename this struct to `ThinTransaction` once that name
> /// becomes available, to better reflect its purpose and usage.
> #[derive(Clone, Debug, Default, Eq, PartialEq)]
> ```

Add a TODO to restore the `Copy` once `ResourceBoundsMapping` implements it.
___
*[`crates/mempool/src/mempool_test.rs` line 352 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/437#-O4d9YMb-9kaSIFyPS9K:-O4d9YMb-9kaSIFyPS9L:b-uk784b) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcb733dc9048a7584ffa5e08eadb49484cacaf05/crates/mempool/src/mempool_test.rs#L352)):*
> ```XML
> 
>     let pool_txs = [input_nonce_1.tx];
>     let queue_txs = [];
> ```

Why are these changes suddenly needed?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/437)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/437#-O4d9UmE0AlnYWDfhomD:-O4ejU5y3OOPwsnX-2Vv:bwqaqqp) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcb733dc9048a7584ffa5e08eadb49484cacaf05/crates/mempool/src/mempool.rs#L113)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Throughout the code (also in `transaction_queue.rs` below); `tx.clone()` should not appear.
</blockquote></details>

Why clone should not appear?
We cannot use deref as it doesn't imply copy.
___
*[`crates/mempool/src/mempool.rs` line 218 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/437#-O4d9ICXD4aIyzeQDLPN:-O4eilXu8mWj3uc3HtAq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcb733dc9048a7584ffa5e08eadb49484cacaf05/crates/mempool/src/mempool.rs#L218)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a TODO to restore the `Copy` once `ResourceBoundsMapping` implements it.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 352 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/437#-O4d9YMb-9kaSIFyPS9K:-O4eioFBEkv12dp5NzZE:b35cgti) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcb733dc9048a7584ffa5e08eadb49484cacaf05/crates/mempool/src/mempool_test.rs#L352)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why are these changes suddenly needed?
</blockquote></details>

queue_txs is from the `TransactionReference` type, and since it doesn't implement Copy, so I had to add a clone.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/437)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/437#-O4d9UmE0AlnYWDfhomD:-O4emywk6PnhuGBuDUvo:b-uaf6yf) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcb733dc9048a7584ffa5e08eadb49484cacaf05/crates/mempool/src/mempool.rs#L113)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why clone should not appear?
We cannot use deref as it doesn't imply copy.
</blockquote></details>

I meant `.clone()` should not be invoked on a variable named `tx` if it's a transaction reference. It makes the reader think there's heavy-lifting being done.
___
*[`crates/mempool/src/mempool_test.rs` line 352 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/437#-O4d9YMb-9kaSIFyPS9K:-O4enJjH648BZ6mL2EMS:b-wevam2) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcb733dc9048a7584ffa5e08eadb49484cacaf05/crates/mempool/src/mempool_test.rs#L352)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

queue_txs is from the `TransactionReference` type, and since it doesn't implement Copy, so I had to add a clone.
</blockquote></details>

What happened before? It was `Copy`ied implicitly?
___
*[`crates/mempool/src/transaction_queue.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/437#-O4enD9T0QXELZeAm3XP:-O4enD9T0QXELZeAm3XQ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/09556f89db8961588a7545403c188e0fe9159c61/crates/mempool/src/transaction_queue.rs#L25)):*
> ```XML
>     pub fn insert(&mut self, tx: TransactionReference) {
>         assert_eq!(
>             self.address_to_tx.insert(tx.sender_address, tx.clone()),
> ```





_Suggestion:_
```XML
tx_reference
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/437)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/437#-O4d9UmE0AlnYWDfhomD:-O4ibuJJ2QcBkfwjZslr:b-i54lf1) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcb733dc9048a7584ffa5e08eadb49484cacaf05/crates/mempool/src/mempool.rs#L113)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I meant `.clone()` should not be invoked on a variable named `tx` if it's a transaction reference. It makes the reader think there's heavy-lifting being done.
</blockquote></details>

I see.
I think we don't have `tx.clone()` anymore.
___
*[`crates/mempool/src/mempool_test.rs` line 352 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/437#-O4d9YMb-9kaSIFyPS9K:-O4idH1s3i1pariCLu_z:b-1vijnd) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcb733dc9048a7584ffa5e08eadb49484cacaf05/crates/mempool/src/mempool_test.rs#L352)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What happened before? It was `Copy`ied implicitly?
</blockquote></details>

Exactly.
___
*[`crates/mempool/src/transaction_queue.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/437#-O4enD9T0QXELZeAm3XP:-O4ibjVl0mtlud9E-wUR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/09556f89db8961588a7545403c188e0fe9159c61/crates/mempool/src/transaction_queue.rs#L25)):*
> ```XML
>     pub fn insert(&mut self, tx: TransactionReference) {
>         assert_eq!(
>             self.address_to_tx.insert(tx.sender_address, tx.clone()),
> ```

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/437#-:-O4jIgA2-dEp1Bjmqzhr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Pull request merged**
