### PR TITLE
refactor(mempool): add test utils for fee escalation tests

### PR DESCRIPTION
**Pull request by elintul**
Will be used in additional tests, in a subsequent PR.

### CODE REVIEW

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1445)

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1445)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1445#-O9FZCgCE9pvjl9qnsL5:-O9FZCgD6bktRrnN1_Aw:b-zcsrtl) ([raw file](https://github.com/starkware-libs/sequencer/blob/c9a505caffee011fc639da1d7779514eb86eb387/crates/mempool/src/mempool_test.rs#L135)):*
> ```XML
> }
> 
> fn add_tx_and_verify_replacement(
> ```

Why it's not part of `test_utils.rs` file?



_Code quote:_
```XML
fn add_tx_and_verify_replacement
```
___
*[`crates/mempool/src/mempool_test.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1445#-O9FZPA14hgec7rAH8mp:-O9FZPA14hgec7rAH8mq:b4c5o69) ([raw file](https://github.com/starkware-libs/sequencer/blob/c9a505caffee011fc639da1d7779514eb86eb387/crates/mempool/src/mempool_test.rs#L135)):*
> ```XML
> }
> 
> fn add_tx_and_verify_replacement(
> ```

Do we need to add `#[track_caller]`?



_Code quote:_
```XML
fn add_tx_and_verify_replacemen
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1445)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1445#-O9FZCgCE9pvjl9qnsL5:-O9FZjFaD1RQw0pooZyb:bdrz6bs) ([raw file](https://github.com/starkware-libs/sequencer/blob/c9a505caffee011fc639da1d7779514eb86eb387/crates/mempool/src/mempool_test.rs#L135)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why it's not part of `test_utils.rs` file?
</blockquote></details>

Uses unit test utils (`MempoolContent`); only used in unit test, no need for it to compile outside `[#cfg(test)]`, which I mentioned compiles outside.
___
*[`crates/mempool/src/mempool_test.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1445#-O9FZPA14hgec7rAH8mp:-O9FZvF1EEPeEkQZKfoR:bvzfohb) ([raw file](https://github.com/starkware-libs/sequencer/blob/c9a505caffee011fc639da1d7779514eb86eb387/crates/mempool/src/mempool_test.rs#L135)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Do we need to add `#[track_caller]`?
</blockquote></details>

I'll add it next PR, #1447.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1445)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1445#-O9FZPA14hgec7rAH8mp:-O9FctXMEmW2Z1ddLoMH:bi0b0wv) ([raw file](https://github.com/starkware-libs/sequencer/blob/c9a505caffee011fc639da1d7779514eb86eb387/crates/mempool/src/mempool_test.rs#L135)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'll add it next PR, #1447.
</blockquote></details>

Hmm, why not in this PR?
Is there a technical problem?

BTW, I didn't see that you've added it in the above PR.
___
*[`crates/mempool/src/mempool_test.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1445#-O9FZCgCE9pvjl9qnsL5:-O9Fd5coDseyYiLVCAhI:b-pqov82) ([raw file](https://github.com/starkware-libs/sequencer/blob/c9a505caffee011fc639da1d7779514eb86eb387/crates/mempool/src/mempool_test.rs#L135)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Uses unit test utils (`MempoolContent`); only used in unit test, no need for it to compile outside `[#cfg(test)]`, which I mentioned compiles outside.
</blockquote></details>

makes sense

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1445)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1445#-O9FZPA14hgec7rAH8mp:-O9FdcceAhrLGJhEAQGf:b9ia14w) ([raw file](https://github.com/starkware-libs/sequencer/blob/c9a505caffee011fc639da1d7779514eb86eb387/crates/mempool/src/mempool_test.rs#L135)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Hmm, why not in this PR?
Is there a technical problem?

BTW, I didn't see that you've added it in the above PR.
</blockquote></details>

Later today, for all debts.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1445)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1445#-O9FddYY4yoiyOVsfTwv:-O9FddYY4yoiyOVsfTww:b-q923ue) ([raw file](https://github.com/starkware-libs/sequencer/blob/c9a505caffee011fc639da1d7779514eb86eb387/crates/mempool/src/mempool_test.rs#L150)):*
> ```XML
>     mut mempool: Mempool,
>     existing_tx: Transaction,
>     invalid_replacement_inputs: impl IntoIterator<Item = AddTransactionArgs>,
> ```

Could you explain why the function accepts iterators instead of a single tax value?

Another option could be to add the for-loop within the test itself. I would prefer if both functions were more consistent. What do you think?



_Code quote:_
```XML
 invalid_replacement_inputs: impl IntoIterator<Item = AddTransactionArgs>,
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1445)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1445#-O9FddYY4yoiyOVsfTwv:-O9FeZtF08G4ogqJaHjt:b-rn340u) ([raw file](https://github.com/starkware-libs/sequencer/blob/c9a505caffee011fc639da1d7779514eb86eb387/crates/mempool/src/mempool_test.rs#L150)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Could you explain why the function accepts iterators instead of a single tax value?

Another option could be to add the for-loop within the test itself. I would prefer if both functions were more consistent. What do you think?
</blockquote></details>

I want to the check of no replacement to be done once, less runtime.

**Review by elintul — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1445#-:-O9GXXPl5Ku062JttsFY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1445)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1445#-O9FddYY4yoiyOVsfTwv:-O9cesJp7vQcjwbu8UM4:b8kbfbk) ([raw file](https://github.com/starkware-libs/sequencer/blob/c9a505caffee011fc639da1d7779514eb86eb387/crates/mempool/src/mempool_test.rs#L150)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I want to the check of no replacement to be done once, less runtime.
</blockquote></details>

I would still prefer a consistent implementation with similar functions for both valid and invalid transactions. Could you modify the `valid` function to accept a list of transactions? wdyt?

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1445)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1445#-O9FddYY4yoiyOVsfTwv:-O9chfDY-0RiVRsw8MA9:bc8kqua) ([raw file](https://github.com/starkware-libs/sequencer/blob/c9a505caffee011fc639da1d7779514eb86eb387/crates/mempool/src/mempool_test.rs#L150)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I would still prefer a consistent implementation with similar functions for both valid and invalid transactions. Could you modify the `valid` function to accept a list of transactions? wdyt?
</blockquote></details>

They are not symmetric: when a transaction is replaced, I want to check it's replaced; when there isn't a replacement, I can check once.

**Pull request merged**
