### PR TITLE
test(mempool): add max_l2_gas_price to [add_]tx[_input] macros

### PR DESCRIPTION
**Pull request by elintul**
To be used in fee escalation tests.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1303)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1303)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1303#-O8qlTiEB-r71lHIDHHN:-O8qlTiEB-r71lHIDHHO:bst5yky) (no related file):*
As for now, mempool only cares about max L2 gas price value for multiple flows (fee escalation, queues' ordering).
No need to pass the cumbersome three resources struct in our macros.

___

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1303)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/Cargo.toml` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1303#-O8qn1ig5khBjsP_nXnx:-O8qn1ig5khBjsP_nXny:b-340gwl) ([raw file](https://github.com/starkware-libs/sequencer/blob/1dfe86d164288557cdf526d8602708765c9ce54a/crates/mempool/Cargo.toml#L14)):*
> ```TOML
> async-trait.workspace = true
> derive_more.workspace = true
> mempool_test_utils = { workspace = true, optional = true }
> ```

Inelegant, but required as long as we're using `starknet_api_test_utils`.
To be refactored.



_Code quote:_
```TOML
mempool_test_utils = { workspace = true, optional = true }
```

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1303)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/test_utils.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1303#-O8qo-IIBkVlUEjWvZuS:-O8quDmt-CjMg-KVID6v:b5785h5) ([raw file](https://github.com/starkware-libs/sequencer/blob/1dfe86d164288557cdf526d8602708765c9ce54a/crates/mempool/src/test_utils.rs#L21)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Sorry, I misunderstood your Q; I thought you meant the _value_ of this constant. 
Please review this line again: I pass the amount constant to the amount field.
</blockquote></details>

I'm asking why you're passing `VALID_L2_GAS_MAX_AMOUNT` (which, I agree, is a bad name) instead of using the default value, especially since `max_amount` isn't used in the mempool code.

The alternative I suggest is:



_Code snippet:_
```XML
max_amount: Default::default(),
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1303)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/test_utils.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1303#-O8qo-IIBkVlUEjWvZuS:-O8quyUk6gYukgSe2s-v:bdsskrv) ([raw file](https://github.com/starkware-libs/sequencer/blob/1dfe86d164288557cdf526d8602708765c9ce54a/crates/mempool/src/test_utils.rs#L21)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I'm asking why you're passing `VALID_L2_GAS_MAX_AMOUNT` (which, I agree, is a bad name) instead of using the default value, especially since `max_amount` isn't used in the mempool code.

The alternative I suggest is:
</blockquote></details>

Okay, let's go with default.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1303)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/Cargo.toml` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1303#-O8qn1ig5khBjsP_nXnx:-O8qvLcl9g-KotgtOdrW:b8zv981) ([raw file](https://github.com/starkware-libs/sequencer/blob/1dfe86d164288557cdf526d8602708765c9ce54a/crates/mempool/Cargo.toml#L14)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No need for TODOs, that might become outdated. If changes in code will require changes in dependencies, it's better and more robust than a TODO.

You can see usages in the imports.
</blockquote></details>

The reason that we have non-tests dependencies in `[dependencies]` section is since `mempool/src/test_utils.rs` is compiled in "testing" feature for integration tests. This is unrelated to this PR.

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1303)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/test_utils.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1303#-O8qvgLoADHy6YOTA-xh:-O8qvgLoADHy6YOTA-xi:b-nidoc0) ([raw file](https://github.com/starkware-libs/sequencer/blob/057e381974a135d94e63964d6e3100afada4a38d/crates/mempool/src/test_utils.rs#L21)):*
> ```XML
>             let resource_bounds = ValidResourceBounds::AllResources(AllResourceBounds {
>                 l2_gas: ResourceBounds {
>                     max_amount: GasAmount(VALID_L2_GAS_MAX_AMOUNT),
> ```

Please note that you have removed  `max_price_per_unit` instead



_Code quote:_
```XML
 max_amount: GasAmount(VALID_L2_GAS_MAX_AMOUNT),
```
___
*[`crates/mempool/tests/flow_test.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1303#-O8qv_Ft4dN8ekiz_vjS:-O8qv_Ft4dN8ekiz_vjT:bfany4m) ([raw file](https://github.com/starkware-libs/sequencer/blob/057e381974a135d94e63964d6e3100afada4a38d/crates/mempool/tests/flow_test.rs#L9)):*
> ```XML
> use starknet_api::core::{ContractAddress, PatriciaKey};
> use starknet_api::executable_transaction::Transaction;
> use starknet_api::execution_resources::GasAmount;
> ```

why it's still needed?



_Code quote:_
```XML
use starknet_api::execution_resources::GasAmount;
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1303)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/test_utils.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1303#-O8qvgLoADHy6YOTA-xh:-O8qw25C9iwtC5eZzbdC:b-o7vuhc) ([raw file](https://github.com/starkware-libs/sequencer/blob/057e381974a135d94e63964d6e3100afada4a38d/crates/mempool/src/test_utils.rs#L21)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please note that you have removed  `max_price_per_unit` instead
</blockquote></details>

Good catch! Done.
___
*[`crates/mempool/tests/flow_test.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1303#-O8qv_Ft4dN8ekiz_vjS:-O8qwr7B6Y41TKv74IB7:b-pwkcwu) ([raw file](https://github.com/starkware-libs/sequencer/blob/057e381974a135d94e63964d6e3100afada4a38d/crates/mempool/tests/flow_test.rs#L9)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

why it's still needed?
</blockquote></details>

My mistake above.

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1303)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/test_utils.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1303#-O8qz-X10kTrPfxRbFMB:-O8qz-X10kTrPfxRbFMC:b-mcwaqc) ([raw file](https://github.com/starkware-libs/sequencer/blob/42179cf8c27043a0001ef2a3b523c31628ca7d2d/crates/mempool/src/test_utils.rs#L21)):*
> ```XML
>             let resource_bounds = ValidResourceBounds::AllResources(AllResourceBounds {
>                 l2_gas: ResourceBounds {
>                     max_price_per_unit: GasPrice(VALID_L2_GAS_MAX_PRICE_PER_UNIT),
> ```

I noticed you could use `into()` here, which would eliminate the need to import `GasPrice` in all the files.

It's not critical—just a suggestion, up to you



_Code quote:_
```XML
GasPrice(VALID_L2_GAS_MAX_PRICE_PER_UNIT)
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1303)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/test_utils.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1303#-O8qz-X10kTrPfxRbFMB:-O8qzqj1Bcy7k9xNnbZX:bcte6lk) ([raw file](https://github.com/starkware-libs/sequencer/blob/42179cf8c27043a0001ef2a3b523c31628ca7d2d/crates/mempool/src/test_utils.rs#L21)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I noticed you could use `into()` here, which would eliminate the need to import `GasPrice` in all the files.

It's not critical—just a suggestion, up to you
</blockquote></details>

Maybe next PR, I want to rebase over this one.

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1303)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/test_utils.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1303#-O8qz-X10kTrPfxRbFMB:-O8r-G4k17WyK13VFYtI:bb74ce2) ([raw file](https://github.com/starkware-libs/sequencer/blob/42179cf8c27043a0001ef2a3b523c31628ca7d2d/crates/mempool/src/test_utils.rs#L21)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Maybe next PR, I want to rebase over this one.
</blockquote></details>

Sure

**Pull request merged**
