### PR TITLE
build(blockifier_reexecution): consecutive test state readers struct and fixtures

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1344)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1344)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1344#-O9588ueAB5Dprml77wo:-O9588ueAB5Dprml77wp:b2g7jkq) ([raw file](https://github.com/starkware-libs/sequencer/blob/3715affa025d589768683ea215673ecd2d1a7364/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L39)):*
> ```XML
> 
> impl ConsecutiveTestStateReaders {
>     pub fn new_for_testing(last_constructed_block_number: BlockNumber) -> Self {
> ```

do you mean: for testing the reexecution crate? or for running "actual" reexecution?
if it's only for internal crate testing, move this to a separate `impl` block in a test util module;
if not, rename to just `new`



_Code quote:_
```XML
new_for_testing
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1344#-O95834F1Q_DvWaxIMmJ:-O95834F1Q_DvWaxIMmK:b-3kp6az) ([raw file](https://github.com/starkware-libs/sequencer/blob/3715affa025d589768683ea215673ecd2d1a7364/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L60)):*
> ```XML
>         ))
>     }
> }
> ```

should be below definition and implementation of TestStateReader



_Code quote:_
```XML
pub struct ConsecutiveTestStateReaders {
    pub last_block_state_reader: TestStateReader,
    pub next_block_state_reader: TestStateReader,
}

impl ConsecutiveTestStateReaders {
    pub fn new_for_testing(last_constructed_block_number: BlockNumber) -> Self {
        let config = &get_rpc_state_reader_config();
        ConsecutiveTestStateReaders {
            last_block_state_reader: TestStateReader::new(config, last_constructed_block_number),
            next_block_state_reader: TestStateReader::new(
                config,
                last_constructed_block_number.next().expect("Overflow in block number"),
            ),
        }
    }

    pub fn get_transaction_executor(
        self,
        transaction_executor_config: Option<TransactionExecutorConfig>,
    ) -> ReexecutionResult<TransactionExecutor<TestStateReader>> {
        Ok(TransactionExecutor::<TestStateReader>::new(
            CachedState::new(self.last_block_state_reader),
            self.next_block_state_reader.get_block_context()?,
            transaction_executor_config.unwrap_or_default(),
        ))
    }
}
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 210 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1344#-O958fqm-Zf1WBLSAOIC:-O958fqm-Zf1WBLSAOID:bnip323) ([raw file](https://github.com/starkware-libs/sequencer/blob/3715affa025d589768683ea215673ecd2d1a7364/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L210)):*
> ```XML
>             transaction_executor_config.unwrap_or_default(),
>         ))
>     }
> ```

Why do you need this function on `TestStateReader`?
to define an executor you need current block context and previous state;
so it's more natural if this is implemented *only* on the `Consecutive` type



_Code quote:_
```XML
    pub fn get_transaction_executor(
        test_state_reader: TestStateReader,
        block_context_next_block: BlockContext,
        transaction_executor_config: Option<TransactionExecutorConfig>,
    ) -> ReexecutionResult<TransactionExecutor<TestStateReader>> {
        Ok(TransactionExecutor::<TestStateReader>::new(
            CachedState::new(test_state_reader),
            block_context_next_block,
            transaction_executor_config.unwrap_or_default(),
        ))
    }
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1344)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @A, @AvivYossef-starkware, and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1344#-O9588ueAB5Dprml77wo:-O992ij1D3I28M--bKQs:by9qjf5) ([raw file](https://github.com/starkware-libs/sequencer/blob/3715affa025d589768683ea215673ecd2d1a7364/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L39)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do you mean: for testing the reexecution crate? or for running "actual" reexecution?
if it's only for internal crate testing, move this to a separate `impl` block in a test util module;
if not, rename to just `new`
</blockquote></details>

Done. The question is if I should create both a `new` function and a `new_for_testing` function, as @AvivYossef-starkware did for the `TestStateReader`
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1344#-O95834F1Q_DvWaxIMmJ:-O998nEM5c6RbDj1B8zy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3715affa025d589768683ea215673ecd2d1a7364/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L60)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

should be below definition and implementation of TestStateReader
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 210 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1344#-O958fqm-Zf1WBLSAOIC:-O99303o7jdrtE6aWkDB:b-4qmxuh) ([raw file](https://github.com/starkware-libs/sequencer/blob/3715affa025d589768683ea215673ecd2d1a7364/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L210)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Why do you need this function on `TestStateReader`?
to define an executor you need current block context and previous state;
so it's more natural if this is implemented *only* on the `Consecutive` type
</blockquote></details>

I slightly disagree here - more than one StateReader is not strictly required, so I think this way is more natural and possibly more useful in the future. (But, of course, if you insist).

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1344)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1344#-O9588ueAB5Dprml77wo:-O99E70771n_UeK2Uc17:bz204m5) ([raw file](https://github.com/starkware-libs/sequencer/blob/3715affa025d589768683ea215673ecd2d1a7364/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L39)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done. The question is if I should create both a `new` function and a `new_for_testing` function, as @AvivYossef-starkware did for the `TestStateReader`
</blockquote></details>

we implement `new_for_testing` usually when the actual field values of the object don't really matter, and we just want a usable object for other test scenarios. this is not the case here IIUC
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 210 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1344#-O958fqm-Zf1WBLSAOIC:-O99DxGk3XAkn5c8rpwO:b-ovsb8f) ([raw file](https://github.com/starkware-libs/sequencer/blob/3715affa025d589768683ea215673ecd2d1a7364/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L210)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I slightly disagree here - more than one StateReader is not strictly required, so I think this way is more natural and possibly more useful in the future. (But, of course, if you insist).
</blockquote></details>

if it's used, or will be used, keep it :)
otherwise, I would delete it - worse case scenario we re-implement it

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1344)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 210 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1344#-O958fqm-Zf1WBLSAOIC:-O99L9ku-buAbwj3dWUu:ba3iudz) ([raw file](https://github.com/starkware-libs/sequencer/blob/3715affa025d589768683ea215673ecd2d1a7364/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L210)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if it's used, or will be used, keep it :)
otherwise, I would delete it - worse case scenario we re-implement it
</blockquote></details>

Fixed, now it's used :grin:

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1344)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
