### PR TITLE
feat(starknet_state_sync_types): add BlockInfo to SyncBlock

### PR DESCRIPTION
**Pull request by eitanm-starkware**

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2927)* status: all files reviewed, 3 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/starknet_state_sync_types/src/state_sync_types.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2927#-OEt7H209x18e1XkGaiM:-OEt7H209x18e1XkGaiN:bdm3keh) ([raw file](https://github.com/starkware-libs/sequencer/blob/f14d7fe70f767f86f998ddaec270cdd1811cf989/crates/starknet_state_sync_types/src/state_sync_types.rs#L19)):*
> ```XML
> #[derive(Debug, Default, Clone, Serialize, Deserialize)]
> pub struct SyncBlock {
>     pub state_diff: ThinStateDiff,
> ```

Put this at the bottom, or put transaction_hashes at the top right below state_diff
___
*[`crates/papyrus_p2p_sync/src/client/header.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2927#-OEt6KB00dwEYm1OvXe4:-OEt6KB1Cs1DoCmTMPNT:bude35t) ([raw file](https://github.com/starkware-libs/sequencer/blob/f14d7fe70f767f86f998ddaec270cdd1811cf989/crates/papyrus_p2p_sync/src/client/header.rs#L136)):*
> ```XML
>                     timestamp: sync_block.block_timestamp,
>                     l1_da_mode: sync_block.l1_da_mode,
>                     sequencer: sync_block.sequencer_address,
> ```

Call this sequencer if in starknet api it's called sequencer
___
*[`crates/starknet_state_sync/src/lib.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2927#-OEt71e2D0jRzhvdNK6F:-OEt71e2D0jRzhvdNK6G:b-koe7ws) ([raw file](https://github.com/starkware-libs/sequencer/blob/f14d7fe70f767f86f998ddaec270cdd1811cf989/crates/starknet_state_sync/src/lib.rs#L84)):*
> ```XML
>     fn get_block(&self, block_number: BlockNumber) -> StateSyncResult<Option<SyncBlock>> {
>         let txn = self.storage_reader.begin_ro_txn()?;
>         let block_header = txn.get_block_header(block_number)?;
> ```

Nice. I see you looked at the video I sent this morning :)
___
*[`crates/starknet_batcher/src/batcher.rs` line 388 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2927#-OEt6jz8Anal9v6lkez4:-OEt6jz9--4cuMfEv9zr:b-6d80a4) ([raw file](https://github.com/starkware-libs/sequencer/blob/f14d7fe70f767f86f998ddaec270cdd1811cf989/crates/starknet_batcher/src/batcher.rs#L388)):*
> ```XML
>         }
> 
>         let SyncBlock { state_diff, transaction_hashes, block_number, .. } = sync_block;
> ```

Add a TODO on @alonh5 to use the extra data

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2927)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @alon and @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/client/header.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2927#-OEt6KB00dwEYm1OvXe4:-OEt9O9C-WsgOJGHa74s:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f14d7fe70f767f86f998ddaec270cdd1811cf989/crates/papyrus_p2p_sync/src/client/header.rs#L136)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Call this sequencer if in starknet api it's called sequencer
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher.rs` line 388 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2927#-OEt6jz8Anal9v6lkez4:-OEt9fJv7baQY6H8AaKI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f14d7fe70f767f86f998ddaec270cdd1811cf989/crates/starknet_batcher/src/batcher.rs#L388)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add a TODO on @alonh5 to use the extra data
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync/src/lib.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2927#-OEt71e2D0jRzhvdNK6F:-OEt8f7a7ijort-SVpx2:b32vir) ([raw file](https://github.com/starkware-libs/sequencer/blob/f14d7fe70f767f86f998ddaec270cdd1811cf989/crates/starknet_state_sync/src/lib.rs#L84)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Nice. I see you looked at the video I sent this morning :)
</blockquote></details>

;)

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2927)* status: all files reviewed, 2 unresolved discussions (waiting on @alon and @eitanm-starkware)

___
*[`crates/papyrus_p2p_sync/src/client/header.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2927#-OEt6KB00dwEYm1OvXe4:-OEtBlYz2I2lqC06cqGG:b-d9j7y1) ([raw file](https://github.com/starkware-libs/sequencer/blob/f14d7fe70f767f86f998ddaec270cdd1811cf989/crates/papyrus_p2p_sync/src/client/header.rs#L136)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it. Forgot to push?
___
*[`crates/starknet_batcher/src/batcher.rs` line 388 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2927#-OEt6jz8Anal9v6lkez4:-OEtBj03DTSsBaDkb1SB:b-d9j7y1) ([raw file](https://github.com/starkware-libs/sequencer/blob/f14d7fe70f767f86f998ddaec270cdd1811cf989/crates/starknet_batcher/src/batcher.rs#L388)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it. Forgot to push?

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2927#-:-OEtGyuB6ZHtpInARoYN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2927)* status: all files reviewed, 2 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 529 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2927#-OEtNO-r9KO3BN5YWw3R:-OEtNO-r9KO3BN5YWw3S:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/f14d7fe70f767f86f998ddaec270cdd1811cf989/crates/starknet_batcher/src/batcher_test.rs#L529)):*
> ```XML
>         block_number: INITIAL_HEIGHT.unchecked_next(),
>         state_diff: Default::default(),
>         transaction_hashes: Default::default(),
> ```


___
*[`crates/starknet_state_sync_types/src/state_sync_types.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2927#-OEtNwZiCpCDPGgtlNZW:-OEtNwZiCpCDPGgtlNZX:b-4bc8qe) ([raw file](https://github.com/starkware-libs/sequencer/blob/b056c479f1214ebfcd0079fd7cbf78dd57790a70/crates/starknet_state_sync_types/src/state_sync_types.rs#L23)):*
> ```XML
>     pub transaction_hashes: Vec<TransactionHash>,
> 
>     pub block_number: BlockNumber,
> ```

Why not use the BlockInfo struct that contains all of these?

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2927)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @ShahakShama)

___
*[`crates/starknet_state_sync_types/src/state_sync_types.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2927#-OEtNwZiCpCDPGgtlNZW:-OEtP3YZ72SqXO6x7WKF:b7qkzee) ([raw file](https://github.com/starkware-libs/sequencer/blob/b056c479f1214ebfcd0079fd7cbf78dd57790a70/crates/starknet_state_sync_types/src/state_sync_types.rs#L23)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why not use the BlockInfo struct that contains all of these?
</blockquote></details>

Currently, because of the nonzerogasprice - blockinfo uses it while storage and sync dont. @ShahakShama  had some longer term reasons as well from what i gathered.

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2927)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/starknet_state_sync_types/src/state_sync_types.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2927#-OEtNwZiCpCDPGgtlNZW:-OEwiSCD9EoM0NJdcZ3Z:b-rmsh79) ([raw file](https://github.com/starkware-libs/sequencer/blob/b056c479f1214ebfcd0079fd7cbf78dd57790a70/crates/starknet_state_sync_types/src/state_sync_types.rs#L23)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Currently, because of the nonzerogasprice - blockinfo uses it while storage and sync dont. @ShahakShama  had some longer term reasons as well from what i gathered.
</blockquote></details>

Yes. We want to be able to return zero gas prices if the header has zero gas prices
long term - SyncBlock should contain the entire header

**Review by ShahakShama — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2927)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2927)* status: all files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware)

___
*[`crates/starknet_state_sync_types/src/state_sync_types.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2927#-OEtNwZiCpCDPGgtlNZW:-OExljLv48IPG3rjwuhe:b-6i22ze) ([raw file](https://github.com/starkware-libs/sequencer/blob/b056c479f1214ebfcd0079fd7cbf78dd57790a70/crates/starknet_state_sync_types/src/state_sync_types.rs#L23)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Yes. We want to be able to return zero gas prices if the header has zero gas prices
long term - SyncBlock should contain the entire header
</blockquote></details>

After talking f2f, please check if we can use gas price 1.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2927#-:-OEyKnmD3Rn8VQXB1-uG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2927)* status: all files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware)

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2927#-:-OF1AuX_E8lyVU-N3zo6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Pull request merged**
