### PR TITLE
feat(consensus): cache proposals based on height and round

### PR DESCRIPTION
**Pull request by guy-starkware**

### CODE REVIEW

**Comment by guy-starkware** [comment]
* **#2586** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2586?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2586?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2586)* status: all files reviewed, 3 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2586#-ODfXeHO2QZe1KBiUAca:-ODfXeHO2QZe1KBiUAcb:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/a48eeee8d366ac4477f32ac68ed9b598faa7bdc6/crates/sequencing/papyrus_consensus/src/manager.rs#L103)):*
> ```XML
>     cached_messages: BTreeMap<u64, Vec<ConsensusMessage>>,
>     // The external map is keyed on the height
>     // The internal map is keyed on round of the proposal
> ```





_Suggestion:_
```XML
    // { Height : { Round : (Init, Receiver)}}
```
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2586#-ODfY2PA5ooV7wy276vf:-ODfY2PA5ooV7wy276vg:bio3qgf) ([raw file](https://github.com/starkware-libs/sequencer/blob/a48eeee8d366ac4477f32ac68ed9b598faa7bdc6/crates/sequencing/papyrus_consensus/src/manager.rs#L232)):*
> ```XML
>                     .entry(proposal_init.height.0)
>                     .or_default()
>                     .insert(proposal_init.round, (proposal_init, content_receiver));
> ```

I thought insert would overwrite the existing entry?



_Code quote:_
```XML
                // Note: ignores new proposals with the same height/round that were already cached.
                self.cached_proposals
                    .entry(proposal_init.height.0)
                    .or_default()
                    .insert(proposal_init.round, (proposal_init, content_receiver));
```
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2586#-ODfYGiG2DvvTN4L8Wv9:-ODfYGiG2DvvTN4L8WvA:bjjeuj3) ([raw file](https://github.com/starkware-libs/sequencer/blob/a48eeee8d366ac4477f32ac68ed9b598faa7bdc6/crates/sequencing/papyrus_consensus/src/manager.rs#L291)):*
> ```XML
>         &mut self,
>         height: BlockNumber,
>     ) -> Option<(ProposalInit, mpsc::Receiver<ContextT::ProposalPart>)> {
> ```

Return all of them. I can iterate them like I do with messages. Look in `start_height`



_Code quote:_
```XML
    // Checks if a cached proposal already exists (with correct height)
    // - returns the proposal if it exists and removes it from the cache.
    // - returns None if no proposal exists.
    // - cleans up any proposals from earlier heights.
    // - for a given height, returns the proposal with the lowest round (and removes it).
    fn get_current_proposal(
        &mut self,
        height: BlockNumber,
    ) -> Option<(ProposalInit, mpsc::Receiver<ContextT::ProposalPart>)> {
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2586)* status: all files reviewed, 3 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2586#-ODfY2PA5ooV7wy276vf:-ODg2wL98jIbkhRMxGZQ:bdpjzu5) ([raw file](https://github.com/starkware-libs/sequencer/blob/a48eeee8d366ac4477f32ac68ed9b598faa7bdc6/crates/sequencing/papyrus_consensus/src/manager.rs#L232)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I thought insert would overwrite the existing entry?
</blockquote></details>

I thought we wanted to ignore? I was hoping to change the code, not the comment.

I prefer to ignore both for conceptual simplicity (first come first serve) and also since I don't want a network repeat to cause us to repeat the whole stream.
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 307 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2586#-ODg3SjMBl5riXZLE29D:-ODg3SjMBl5riXZLE29E:b84dol4) ([raw file](https://github.com/starkware-libs/sequencer/blob/9cfebe827e68bb56d6200f934321dca0b18806a3/crates/sequencing/papyrus_consensus/src/manager.rs#L307)):*
> ```XML
>                 },
>             }
>         }
> ```

I'm a never nester :P 



_Suggestion:_
```XML
            let Some(entry) = self.cached_proposals.first_entry() else {
                return Vec::new()
            };
 match entry.key().cmp(&height.0) {
                    std::cmp::Ordering::Greater => return vec![],
                    std::cmp::Ordering::Equal => {
                        let submap = entry.remove();
                        return submap.into_values().collect();
                    }
                    std::cmp::Ordering::Less => {
                        entry.remove();
                    }
                },
        }
```

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2586)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 307 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2586#-ODg3SjMBl5riXZLE29D:-OE8zbttB2OI4ZAITEnF:b-kbs3bw) ([raw file](https://github.com/starkware-libs/sequencer/blob/9cfebe827e68bb56d6200f934321dca0b18806a3/crates/sequencing/papyrus_consensus/src/manager.rs#L307)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

I thought the "rust thing to do" was to put "match" everywhere. I agree let-else is much better in this case.
</blockquote></details>

What can I say, I'm just a renegade :sunglasses:

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2586)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Pull request merged**
