### PR TITLE
refactor: feature contracts to use native together with casm

### PR DESCRIPTION
**Pull request by varex83**

### CODE REVIEW

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1455)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 10 of 15 files at r9, 1 of 2 files at r10, 1 of 1 files at r11, 3 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1455)* status: 15 of 20 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @varex83)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 640 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OATSvnpCSZ3zLLbR4x-:-OATSvnq9WcH3QBbSicy:b-81g93p) ([raw file](https://github.com/starkware-libs/sequencer/blob/7166b97b6177805686cbe2aa3fbb358aae6cbce9/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L640)):*
> ```Cairo
>         assert(self.my_storage_var.read() == 0, 'values should not change.');
>     }
> }
> ```

Please revert

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 11 of 13 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1455)* status: 16 of 20 files reviewed, all discussions resolved (waiting on @noaov1)

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 15 files at r9, 2 of 6 files at r12, 8 of 13 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1455)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @varex83)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 202 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OAwhaaR0QUFNw0Kk3ro:-OAwhaaR0QUFNw0Kk3rp:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6147f6244b83fddb7c920a5207cc32d6ddc3b798/crates/blockifier/src/test_utils/cairo_compile.rs#L202)):*
> ```XML
> }
> 
> // Lock to prevent concurrent git operations that creat git index.lock file.
> ```





_Suggestion:_
```XML
// Lock to prevent concurrent git operations that create a git index.lock file.
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 450 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OAwrEZ25i8RAARfm9Gv:-OAwrEZ25i8RAARfm9Gw:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6147f6244b83fddb7c920a5207cc32d6ddc3b798/crates/blockifier/src/test_utils/contracts.rs#L450)):*
> ```XML
>                     .into_iter()
>             }
>         })
> ```





_Suggestion:_
```XML
            // If only one supported version exists, add the contract to the array as is.
            if contract.supported_versions().is_power_of_two() {
                vec![contract].into_iter()
            } else {
                let supported_versions = contract.supported_versions();

                #[cfg(feature = "cairo_native")]
                let range = 0..3isize;
                #[cfg(not(feature = "cairo_native"))]
                let range = 0..2isize;

                // If multiple supported versions exist, add each supported version of the
                // contract to the array.
                range
                    .filter(|i| supported_versions & (1u32 << i) != 0)
                    .map(move |i| {
                        let mut contract = contract;
                        contract.set_cairo_version(CairoVersion::from(i));

                        contract
                    })
                    .collect::<Vec<_>>()
                    .into_iter()
            }
        })
```
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 83 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OAwsNED4BEove2GR2LH:-OAwsNED4BEove2GR2LI:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6147f6244b83fddb7c920a5207cc32d6ddc3b798/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L83)):*
> ```XML
>     };
> 
>     // Collect base filenames from the FeatureContract enum for the given Cairo version
> ```





_Suggestion:_
```XML
    // Collect base filenames from the FeatureContract enum for the given Cairo version.
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1455)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1 and @varex83)

___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 12 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OAw2o4_68OQFHCxcyFO:-OAw2o4_68OQFHCxcyFP:b-4ajvqx) ([raw file](https://github.com/starkware-libs/sequencer/blob/6147f6244b83fddb7c920a5207cc32d6ddc3b798/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L12)):*
> ```XML
> const CAIRO1_FEATURE_CONTRACTS_DIR: &str = "feature_contracts/cairo1";
> #[cfg(feature = "cairo_native")]
> const CAIRO_NATIVE_FEATURE_CONTRACTS_DIR: &str = "feature_contracts/cairo1";
> ```

Why do we need this constant can't we just use CAIRO1_FEATURE_CONTRACTS_DIR?



_Code quote:_
```XML
const CAIRO_NATIVE_FEATURE_CONTRACTS_DIR: &str = "feature_contracts/cairo1";
```

**Review by varex83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1455)* status: 17 of 20 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 202 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OAwhaaR0QUFNw0Kk3ro:-OB-hn7W-7y_lXecd2kR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6147f6244b83fddb7c920a5207cc32d6ddc3b798/crates/blockifier/src/test_utils/cairo_compile.rs#L202)):*
> ```XML
> }
> 
> // Lock to prevent concurrent git operations that creat git index.lock file.
> ```

Done.
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 450 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OAwrEZ25i8RAARfm9Gv:-OB-hmdQ5Uf-8LfqcW3f:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6147f6244b83fddb7c920a5207cc32d6ddc3b798/crates/blockifier/src/test_utils/contracts.rs#L450)):*
> ```XML
>                     .into_iter()
>             }
>         })
> ```

Done.
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 12 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OAw2o4_68OQFHCxcyFO:-OB-ge6ZCUfA1vULUlhM:ba64eh9) ([raw file](https://github.com/starkware-libs/sequencer/blob/6147f6244b83fddb7c920a5207cc32d6ddc3b798/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L12)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why do we need this constant can't we just use CAIRO1_FEATURE_CONTRACTS_DIR?
</blockquote></details>

We can, but this approach seems to be cleaner, for example, if we change the directory for cairo native contract, we won't forget about this place. And since it's a const, the compiled binary will be the same in both scenarios 
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 83 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OAwsNED4BEove2GR2LH:-OB-hlsq8u1KnECcC125:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6147f6244b83fddb7c920a5207cc32d6ddc3b798/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L83)):*
> ```XML
>     };
> 
>     // Collect base filenames from the FeatureContract enum for the given Cairo version
> ```

Done.

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r14.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1455)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 13 files at r13, 1 of 3 files at r14.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1455)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1455)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1455)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @noaov1, and @varex83)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 213 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OBJmXNfBTqJYzmDfz2W:-OBJmXNfBTqJYzmDfz2X:b-gupu3) ([raw file](https://github.com/starkware-libs/sequencer/blob/9da70d6d342dbc6c7a0bc9b0ef8f97f8c564fb21/crates/blockifier/src/test_utils/cairo_compile.rs#L213)):*
> ```XML
> // remove the file manually to continue.
> // """
> static GIT_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
> ```

@dorimedini-starkware WDYT?



_Code quote:_
```XML
static GIT_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
```

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1455)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @varex83)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1455)* status: all files reviewed, 5 unresolved discussions (waiting on @meship-starkware, @noaov1, and @varex83)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 213 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OBJmXNfBTqJYzmDfz2W:-OBK7Zax02PsocdisqS7:b-k8sn6n) ([raw file](https://github.com/starkware-libs/sequencer/blob/9da70d6d342dbc6c7a0bc9b0ef8f97f8c564fb21/crates/blockifier/src/test_utils/cairo_compile.rs#L213)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

@dorimedini-starkware WDYT?
</blockquote></details>

can you explain why this is needed? not sure it's a good idea (let's chat)
___
*[`crates/blockifier/src/test_utils.rs` line 88 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OBK8ChV-dN6JnC6Jg7k:-OBK8ChV-dN6JnC6Jg7l:b-s6nyyr) ([raw file](https://github.com/starkware-libs/sequencer/blob/9da70d6d342dbc6c7a0bc9b0ef8f97f8c564fb21/crates/blockifier/src/test_utils.rs#L88)):*
> ```XML
>         }
>     }
> }
> ```

I don't think you really need this... and converting `2` to `Native` is non-intuitive



_Code quote:_
```XML
impl From<isize> for CairoVersion {
    fn from(value: isize) -> Self {
        match value {
            0 => Self::Cairo0,
            1 => Self::Cairo1,
            #[cfg(feature = "cairo_native")]
            2 => Self::Native,
            _ => panic!("Invalid value for CairoVersion: {}", value),
        }
    }
}
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 120 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OBK7eAI3aEQqteAFToJ:-OBK7eAI3aEQqteAFToK:bu9i0y4) ([raw file](https://github.com/starkware-libs/sequencer/blob/9da70d6d342dbc6c7a0bc9b0ef8f97f8c564fb21/crates/blockifier/src/test_utils/contracts.rs#L120)):*
> ```XML
>     ///
>     /// This order is defined in [CairoVersion] enum.
>     fn supported_versions(&self) -> u32 {
> ```

please use more explicit typing...



_Suggestion:_
```XML
HashSet<CairoVersion>
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 333 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OBK8W_ZBdi9BCT1JbYD:-OBK8W_ZBdi9BCT1JbYE:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/9da70d6d342dbc6c7a0bc9b0ef8f97f8c564fb21/crates/blockifier/src/test_utils/contracts.rs#L333)):*
> ```XML
>                     #[cfg(feature = "cairo_native")]
>                     CairoVersion::Native => "_sierra",
>                 },
> ```





_Suggestion:_
```XML
                "feature_contracts/cairo{}/{}{}.json",
                match cairo_version {
                    CairoVersion::Cairo0 => "0/compiled",
                    CairoVersion::Cairo1 => "1/compiled_casm",
                    #[cfg(feature = "cairo_native")]
                    CairoVersion::Native => "1/compiled_sierra",
                },
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 460 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OBK8qns9XIXvSR_l-06:-OBK8qntCg_CVaSzYJLC:b-hlaz0f) ([raw file](https://github.com/starkware-libs/sequencer/blob/9da70d6d342dbc6c7a0bc9b0ef8f97f8c564fb21/crates/blockifier/src/test_utils/contracts.rs#L460)):*
> ```XML
>                     .into_iter()
>             }
>         })
> ```

refactor: just iterate over supported versions and add the different variants (see above, supported_versions should return a set of versions, not a u32)



_Code quote:_
```XML
        Self::iter().flat_map(|contract| {
            // If only one supported version exists, add the contract to the array as is.
            if contract.supported_versions().is_power_of_two() {
                vec![contract].into_iter()
            } else {
                let supported_versions = contract.supported_versions();

                #[cfg(feature = "cairo_native")]
                let range = 0..3isize;
                #[cfg(not(feature = "cairo_native"))]
                let range = 0..2isize;

                // If multiple supported versions exist, add each supported version of the
                // contract to the array.
                range
                    .filter(|i| supported_versions & (1u32 << i) != 0)
                    .map(move |i| {
                        let mut contract = contract;
                        contract.set_cairo_version(CairoVersion::from(i));

                        contract
                    })
                    .collect::<Vec<_>>()
                    .into_iter()
            }
        })
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 5 of 8 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1455)* status: 17 of 20 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @noaov1, and @varex83)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 6 of 8 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1455)* status: 18 of 20 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @noaov1, and @varex83)

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 213 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OBJmXNfBTqJYzmDfz2W:-OBL4GgD0-JzmW8tqEHu:b5ghzwk) ([raw file](https://github.com/starkware-libs/sequencer/blob/9da70d6d342dbc6c7a0bc9b0ef8f97f8c564fb21/crates/blockifier/src/test_utils/cairo_compile.rs#L213)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you explain why this is needed? not sure it's a good idea (let's chat)
</blockquote></details>

As far as I understood, CI errors may appear when running git commands in the function `prepare_cairo1_compiler_deps` because it is run concurrently in tests, causing a race condition on the `index.lock` file.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1455)* status: 18 of 20 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @noaov1, and @varex83)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 213 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OBJmXNfBTqJYzmDfz2W:-OBL7MAjDlyG13xIJe1Y:b-cqxx00) ([raw file](https://github.com/starkware-libs/sequencer/blob/9da70d6d342dbc6c7a0bc9b0ef8f97f8c564fb21/crates/blockifier/src/test_utils/cairo_compile.rs#L213)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

As far as I understood, CI errors may appear when running git commands in the function `prepare_cairo1_compiler_deps` because it is run concurrently in tests, causing a race condition on the `index.lock` file.
</blockquote></details>

who runs it concurrently?
there is an open task to do this, it is not simple for this reason.
we do not want to parallelize blindly.
different cairo1 compiler versions used should be checked out sequentially, so we don't build the same tag multiple times.
when parallelizing, we should group compile jobs by compiler version, and execute groups sequentially,
or checkout different copies of the compiler repo (worktrees?) to be able to compile different versions in parallel

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 213 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OBJmXNfBTqJYzmDfz2W:-OBL7rAT169tKclqB_Wy:blk197r) ([raw file](https://github.com/starkware-libs/sequencer/blob/9da70d6d342dbc6c7a0bc9b0ef8f97f8c564fb21/crates/blockifier/src/test_utils/cairo_compile.rs#L213)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

who runs it concurrently?
there is an open task to do this, it is not simple for this reason.
we do not want to parallelize blindly.
different cairo1 compiler versions used should be checked out sequentially, so we don't build the same tag multiple times.
when parallelizing, we should group compile jobs by compiler version, and execute groups sequentially,
or checkout different copies of the compiler repo (worktrees?) to be able to compile different versions in parallel
</blockquote></details>

I think it is used in multiple tests and `cargo test` runs these tests concurrently in the CI

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1455)* status: 18 of 20 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @noaov1, and @varex83)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 213 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OBJmXNfBTqJYzmDfz2W:-OBL8j5m7kGQ1Je4Mxuk:b-15zil1) ([raw file](https://github.com/starkware-libs/sequencer/blob/9da70d6d342dbc6c7a0bc9b0ef8f97f8c564fb21/crates/blockifier/src/test_utils/cairo_compile.rs#L213)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I think it is used in multiple tests and `cargo test` runs these tests concurrently in the CI
</blockquote></details>

then this is new.
since when do multiple tests recompile?
this is not intended, and if it is done, the cairo repo should be explicitly checked out to a different directory

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1455)* status: 18 of 20 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @noaov1, and @varex83)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 213 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-OBJmXNfBTqJYzmDfz2W:-OBL8uUsB8sSCFBYBMBz:b-w3inxi) ([raw file](https://github.com/starkware-libs/sequencer/blob/9da70d6d342dbc6c7a0bc9b0ef8f97f8c564fb21/crates/blockifier/src/test_utils/cairo_compile.rs#L213)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

then this is new.
since when do multiple tests recompile?
this is not intended, and if it is done, the cairo repo should be explicitly checked out to a different directory
</blockquote></details>

or, implement "smart" parallelization...
waiting for a lock is not a good solution, we will end up recompiling the same compiler tag multiple times

**Review by Yoni-Starkware — COMMENTED** [review]
Can we avoid the extra casm compilation [here](https://github.com/starkware-libs/sequencer/blob/adbaf96134c839f9f9b0228cfa90f6e10b06a2b4/crates/blockifier/src/test_utils/struct_impls.rs#L263)?

> Reviewed 2 of 15 files at r9, 1 of 13 files at r13, 4 of 8 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1455#-:-OBdfLqF8EKZ36g2TLiw:b8syhqr)* status: 17 of 20 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @noaov1, and @varex83)

**Pull request closed without merging**
