### PR TITLE
fix: add missing config.toml

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/193)

### CODE REVIEW

**Comment by dan-starkware** [comment]
1. Why no just in native?
2. Shouldn't this replace existing code? (I would expect to see some deletions)

**Comment by dan-starkware** [comment]
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

1. Why no just in native?
2. Shouldn't this replace existing code? (I would expect to see some deletions)
</blockquote></details>

TAL https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/193)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @giladchase, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/193#-O32Qg5-7eU55ae3RcJH:-O333GJ86JPNiqmJqbTl:b-nhjw96) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

TAL https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure
</blockquote></details>

1. trying with native crate, will update
2. this file was missed in Lior's migration probably

___

**Review by giladchase — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/193)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @dorimedini-starkware, and @noaov1)

___
*[`.github/workflows/blockifier_ci.yml` line 12 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/193#-O336YgbDWsyj3YQOR6c:-O336Ygc2Zid4YJ223YC:b-cq4t3s) ([raw file](https://github.com/starkware-libs/sequencer/blob/f63d6c3aa836cf68c5ff1607dbd0eb485def14fb/.github/workflows/blockifier_ci.yml#L12)):*
> ```YAML
>     paths:
>       - 'crates/blockifier/**'
>       - 'crates/native_blockifier/.cargo/config.toml'
> ```

Can this be `native_blockifier/**`? or will that mess something up?



_Code quote:_
```YAML
      - 'crates/native_blockifier/.cargo/config.toml'
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/193)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @giladchase, and @noaov1)

___
*[`.github/workflows/blockifier_ci.yml` line 12 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/193#-O336YgbDWsyj3YQOR6c:-O338xOO6TxX4oCXeUoq:b61iqs4) ([raw file](https://github.com/starkware-libs/sequencer/blob/f63d6c3aa836cf68c5ff1607dbd0eb485def14fb/.github/workflows/blockifier_ci.yml#L12)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can this be `native_blockifier/**`? or will that mess something up?
</blockquote></details>

I have a [separate PR](https://reviewable.io/reviews/starkware-libs/sequencer/76) for enriching this trigger

**Pull request merged**
