### PR TITLE
chore(blockifier): refactor feature contract path getters for different paths

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/179)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
* **#182** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/182?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#181** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/181?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#180** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/180?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#179** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/179?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/test_utils/contracts.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/179#-O37caWZ6GKt5IfBMUfv:-O37caW_3JrKRB3qH8mV:bg1fmwx) ([raw file](https://github.com/starkware-libs/sequencer/blob/75b59bbeda972c08940b03933093f90dabed6029/crates/blockifier/src/test_utils/contracts.rs#L66)):*
> ```XML
> 
> // ERC20 contract is in a unique location.
> const ERC20_BASE_NAME: &str = "ERC20";
> ```

Why are you adding this, if it's never used?



_Code quote:_
```XML
const ERC20_BASE_NAME: &str = "ERC20";
```

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/test_utils/contracts.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/179#-O37csTN9XQuYiq0ERT0:-O37csTN9XQuYiq0ERT1:b-157slf) ([raw file](https://github.com/starkware-libs/sequencer/blob/75b59bbeda972c08940b03933093f90dabed6029/crates/blockifier/src/test_utils/contracts.rs#L202)):*
> ```XML
>             Self::SecurityTests => SECURITY_TEST_CONTRACT_NAME,
>             Self::TestContract(_) => TEST_CONTRACT_NAME,
>             Self::ERC20(_) => ERC20_BASE_NAME,
> ```

The above question



_Code quote:_
```XML
Self::ERC20(_) => ERC20_BASE_NAME,
```

**Review by aner-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/179)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/179#-O37eBlpE2pbgGgl2YrJ:-O37eBlpE2pbgGgl2YrK:bobpshn) ([raw file](https://github.com/starkware-libs/sequencer/blob/75b59bbeda972c08940b03933093f90dabed6029/crates/blockifier/src/test_utils/contracts.rs#L229)):*
> ```XML
>         let contract_name = match self {
>             // ERC20 is a special case - not in the feature_contracts directory.
>             Self::ERC20(cairo_version) => {
> ```

This is a bit confusing - you're over



_Code quote:_
```XML
        let cairo_version = self.cairo_version();
        let contract_name = match self {
            // ERC20 is a special case - not in the feature_contracts directory.
            Self::ERC20(cairo_version) => {
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/179)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @aner-starkware, @AvivYossef-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/179#-O37caWZ6GKt5IfBMUfv:-O38etTU0-_Qe309pKvT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/31a691f5319496f597aea53331db019e303348ca/crates/blockifier/src/test_utils/contracts.rs#L66)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Why are you adding this, if it's never used?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/179#-O37csTN9XQuYiq0ERT0:-O38eu3FAo2kv02Pv5h6:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/31a691f5319496f597aea53331db019e303348ca/crates/blockifier/src/test_utils/contracts.rs#L202)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

The above question
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/179#-O37eBlpE2pbgGgl2YrJ:-O38evwrAOX5uWD7VzdY:bq8mjyv) ([raw file](https://github.com/starkware-libs/sequencer/blob/31a691f5319496f597aea53331db019e303348ca/crates/blockifier/src/test_utils/contracts.rs#L229)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

This is a bit confusing - you're over
</blockquote></details>

what am I over?

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/test_utils/contracts.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/179#-O37eBlpE2pbgGgl2YrJ:-O39EetpDxCuckhuigNw:bvitd2v) ([raw file](https://github.com/starkware-libs/sequencer/blob/31a691f5319496f597aea53331db019e303348ca/crates/blockifier/src/test_utils/contracts.rs#L229)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what am I over?
</blockquote></details>

Sorry, I forgot to complete the  sentence :sweat_smile: 
You're overriding `cairo_version` before ever using it. Maybe consider postponing the first `let` statement, or using a different variable name (e.g.,  if you want to `assert_eq`)?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/179)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @aner-starkware, @AvivYossef-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/179#-O37eBlpE2pbgGgl2YrJ:-O3C7EpJ0RsHpqQh4brk:b-tuomwa) ([raw file](https://github.com/starkware-libs/sequencer/blob/31a691f5319496f597aea53331db019e303348ca/crates/blockifier/src/test_utils/contracts.rs#L229)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Sorry, I forgot to complete the  sentence :sweat_smile: 
You're overriding `cairo_version` before ever using it. Maybe consider postponing the first `let` statement, or using a different variable name (e.g.,  if you want to `assert_eq`)?
</blockquote></details>

Right! Done.

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/179)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @dorimedini-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 236 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/179#-O3D6wL36CcshbTthsL5:-O3D6wL36CcshbTthsL6:b-mcctmf) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca7a29b33f20e99cdfb16a4868ecb044de5b3ed/crates/blockifier/src/test_utils/contracts.rs#L236)):*
> ```XML
>             let base_name = Path::new(&source_path)
>                 .file_name()
>                 .unwrap()
> ```

Are we cool with all these `unwrap`s?



_Code quote:_
```XML
.unwrap()
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/179)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @AvivYossef-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 236 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/179#-O3D6wL36CcshbTthsL5:-O3RAnnG9OeSNIl4QRpE:bqag29h) ([raw file](https://github.com/starkware-libs/sequencer/blob/033708e1674e6b47d9ceef30be7e787b9efad9e0/crates/blockifier/src/test_utils/contracts.rs#L236)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

in a test util? I'd say yes, would you prefer some be `expect`s?
</blockquote></details>

OK, just checking.

**Review by aner-starkware — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/179#-:-O3X6qAK-uz2M1fj9eBT:bg7igkv)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @AvivYossef-starkware, @meship-starkware, and @noaov1)

**Review by TzahiTaub — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/179)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @dorimedini-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 240 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/179#-O3ydyfMAyn1oOCgm3N_:-O3ydyfMAyn1oOCgm3Na:bwkyb90) ([raw file](https://github.com/starkware-libs/sequencer/blob/3da45df0c77e6fbe4f529d4dd7deed79c2e14275/crates/blockifier/src/test_utils/contracts.rs#L240)):*
> ```XML
>                 .unwrap()
>                 .strip_suffix(".cairo")
>                 .unwrap();
> ```

Your choice, but it seems easier to define a private func for the match mapping and just call it here and in the above, than to do this processing.



_Code quote:_
```XML
            let base_name = Path::new(&source_path)
                .file_name()
                .unwrap()
                .to_str()
                .unwrap()
                .strip_suffix(".cairo")
                .unwrap();
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/179)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @meship-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 240 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/179#-O3ydyfMAyn1oOCgm3N_:-O4-MNOcBCo7Afg7aV34:b-ol6rq0) ([raw file](https://github.com/starkware-libs/sequencer/blob/3da45df0c77e6fbe4f529d4dd7deed79c2e14275/crates/blockifier/src/test_utils/contracts.rs#L240)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Your choice, but it seems easier to define a private func for the match mapping and just call it here and in the above, than to do this processing.
</blockquote></details>

wdym?
not that `ERC20_CAIRO0_CONTRACT_SOURCE_PATH` and `ERC20_CAIRO0_CONTRACT_PATH` are not the same

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/179)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @meship-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 240 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/179#-O3ydyfMAyn1oOCgm3N_:-O4-On-d96VVCNSxDrM9:bai88hc) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4fc3997f37e1a8c8ba647a94f67658e7d828352/crates/blockifier/src/test_utils/contracts.rs#L240)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

wdym?
not that `ERC20_CAIRO0_CONTRACT_SOURCE_PATH` and `ERC20_CAIRO0_CONTRACT_PATH` are not the same
</blockquote></details>

*note that

**Review by TzahiTaub — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/179)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @dorimedini-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 240 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/179#-O3ydyfMAyn1oOCgm3N_:-O4-b-vO2-kXzMcV6bp1:b-g3uvwj) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4fc3997f37e1a8c8ba647a94f67658e7d828352/crates/blockifier/src/test_utils/contracts.rs#L240)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

*note that
</blockquote></details>

In "in the above" I meant here (in the else clause) and in the else of `get_source_path`. I.e., something like
```
fn get_non_erc20_base_filename(&self)) -> String:
      match self {
                    Self::AccountWithLongValidate(_) => ACCOUNT_LONG_VALIDATE_NAME,
                    Self::AccountWithoutValidations(_) => ACCOUNT_WITHOUT_VALIDATIONS_NAME,
                    Self::Empty(_) => EMPTY_CONTRACT_NAME,
                    Self::FaultyAccount(_) => FAULTY_ACCOUNT_NAME,
                    Self::LegacyTestContract => LEGACY_CONTRACT_NAME,
                    Self::SecurityTests => SECURITY_TEST_CONTRACT_NAME,
                    Self::TestContract(_) => TEST_CONTRACT_NAME,
                    Self::ERC20(_) => unreachable!(),
                }
 pub fn get_source_path(&self) -> String {
...
    else {
        let base_name = self.get_non_erc20_base_filename()
...
 pub fn get_compiled_path(&self) -> String {
...
    else {
        let base_name = self.get_non_erc20_base_filename()



```

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/179#-:-O4-e9BV4lZ_mFG7CTn9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware, @meship-starkware, and @noaov1)

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Aug 11, 11:28 AM EDT**: @dorimedini-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/179).

**Pull request merged**
