### PR TITLE
build(fee): tx_context and create_tx_info cannot_fail

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/538)

### CODE REVIEW

**Comment by nimrod-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/538?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#538** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/538?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#537** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/537?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#508** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/508?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#509](https://github.com/starkware-libs/sequencer/pull/509) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/509?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#507** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/507?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#506** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/506?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#505** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/505?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#504** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/504?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#503** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/503?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nimrod-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/538#-:-O4k5ImM75yxkrBmD7gD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/538)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/538)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/538)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/538)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/538)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/538)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/538)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Comment by nimrod-starkware** [comment]
### Merge activity

* **Sep 4, 9:01 AM EDT**: @nimrod-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/538).

**Review by nimrod-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/538)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
