### PR TITLE
feat(starknet_batcher): validate height matches storage on add sync block

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2733?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2733** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2733?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2733?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2732** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2732?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2733)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2733#-OENv_Bm2LikMbgACGnw:-OENv_Bm2LikMbgACGnx:b-2qi25r) (no related file):*
Let's keep it simple, we only want to panic if the height it wrong.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2733)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2733#-OENv_Bm2LikMbgACGnw:-OEOYEmXCBAiKqGlTOfd:b-896fix) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Let's keep it simple, we only want to panic if the height it wrong.
</blockquote></details>

Done.

**Comment by ArniStarkware** [comment]
Replaced with the simpler: #2759

**Pull request closed without merging**
