### PR TITLE
refactor(consensus): pass block felt instead of hash to creating msg fn

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/550)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/550)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/550#-O4pDX9KDMlew-94VNBB:-O4pDX9KDMlew-94VNBC:b-4t5cz7) ([raw file](https://github.com/starkware-libs/sequencer/blob/7c611778f4e1ffbb8c493d4ca56d8ccdb2552fd8/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L27)):*
> ```XML
>     static ref BLOCK: TestBlock = TestBlock { content: vec![1, 2, 3], id: BlockHash(Felt::ONE) };
>     static ref BLOCK_HASH: BlockHash = BLOCK.id();
>     static ref BLOCK_FELT: Felt = BLOCK_HASH.0;
> ```

Let's remove both of these. Just use `BLOCK.id()` or `BLOCK.id().0`.



_Code quote:_
```XML
    static ref BLOCK_HASH: BlockHash = BLOCK.id();
    static ref BLOCK_FELT: Felt = BLOCK_HASH.0;
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/550)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/550#-O4ptlAx3gpCrMMcaWd6:-O4ptlAx3gpCrMMcaWd7:b-noxzs9) ([raw file](https://github.com/starkware-libs/sequencer/blob/de0ec6548c3986eab7ea09fc272351c884e31b78/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L25)):*
> ```XML
>     static ref VALIDATORS: Vec<ValidatorId> =
>         vec![*PROPOSER_ID, *VALIDATOR_ID_1, *VALIDATOR_ID_2, *VALIDATOR_ID_3];
>     static ref BLOCK: TestBlock = TestBlock { content: vec![1, 2, 3], id: BlockHash(Felt::ONE) };
> ```

Better idea.

BLOCK_HASH is a variable name, not a type. Then use BLOCK_HASH below in the tests. Seems nicer to me than my original suggestion. Feel free to disagree though.



_Suggestion:_
```XML
    static ref BLOCK_HASH: BlockHash = Felt::ONE;
    static ref BLOCK: TestBlock = TestBlock { content: vec![1, 2, 3], id: BlockHash(BlockHash)};
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/550)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/550#-O4ptlAx3gpCrMMcaWd6:-O571zPGBfBuLyYeKZqy:b1tml7l) ([raw file](https://github.com/starkware-libs/sequencer/blob/de0ec6548c3986eab7ea09fc272351c884e31b78/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L25)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Better idea.

BLOCK_HASH is a variable name, not a type. Then use BLOCK_HASH below in the tests. Seems nicer to me than my original suggestion. Feel free to disagree though.
</blockquote></details>

Both block hash and felt are needed; I think the current implementation suffices, and the code clearly shows that we're talking about the same block

**Review by matan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/550)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
