### PR TITLE
refactor(config): remove separation of required and non required config pointers

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Comment by yair-starkware** [comment]
* **#1954** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1954?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1953** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1953?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2111** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2111?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2111?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2111)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/starknet_sequencer_node/src/config/config_test.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2111#-OBvExTL2Ly4eCXSp3yz:-OBvExTL2Ly4eCXSp3z-:b-su55uh) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b8edd9c8ac2740b3c7d8003067b2622a8d57f35/crates/starknet_sequencer_node/src/config/config_test.rs#L122)):*
> ```XML
>     let expected_required_params = deserialized.as_object_mut().unwrap();
>     expected_required_params.retain(|_, value| {
>         let param = serde_json::from_value::<SerializedParam>(value.clone()).unwrap();
> ```

Is the clone needed?



_Code quote:_
```XML
.clone()
```
___
*[`crates/starknet_sequencer_node/src/config/config_test.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2111#-OBvGazJ9MkgTWZuxeht:-OBvGazJ9MkgTWZuxehu:b-zduab6) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b8edd9c8ac2740b3c7d8003067b2622a8d57f35/crates/starknet_sequencer_node/src/config/config_test.rs#L126)):*
> ```XML
>     });
>     let expected_required_keys =
>         expected_required_params.keys().cloned().collect::<HashSet<String>>();
> ```

IIUC this can be achieved more elegantly using https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.filter_map.
WDYT?



_Code quote:_
```XML
    expected_required_params.retain(|_, value| {
        let param = serde_json::from_value::<SerializedParam>(value.clone()).unwrap();
        param.is_required()
    });
    let expected_required_keys =
        expected_required_params.keys().cloned().collect::<HashSet<String>>();
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2111)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sequencer_node/src/config/config_test.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2111#-OBvExTL2Ly4eCXSp3yz:-OByOkqh4FiGZyzVOMaX:bi0mxeg) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b8edd9c8ac2740b3c7d8003067b2622a8d57f35/crates/starknet_sequencer_node/src/config/config_test.rs#L122)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Is the clone needed?
</blockquote></details>

Yes, value is borrowed and deserialization is consuming
___
*[`crates/starknet_sequencer_node/src/config/config_test.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2111#-OBvGazJ9MkgTWZuxeht:-OByP-anE0YLBKaZeMmz:bparr03) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b8edd9c8ac2740b3c7d8003067b2622a8d57f35/crates/starknet_sequencer_node/src/config/config_test.rs#L126)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

IIUC this can be achieved more elegantly using https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.filter_map.
WDYT?
</blockquote></details>

Tried, didn't go well.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2111#-:-OByXTI20RI0xzIatMhG:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2111)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Comment by yair-starkware** [comment]
### Merge activity

* **Nov 18, 4:13 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2111).

**Pull request merged**
