### PR TITLE
refactor(starknet_integration_tests): add sierra contract class to dummy state

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2467?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2467** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2467?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2467?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2466** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2466?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2467)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @Yoni-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2467#-ODLLlDP6jYwuT7hCcD6:-ODLLlDP6jYwuT7hCcD7:b-4ctrdh) (no related file):*
please add reviewer(s) from mempool team
___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2467#-ODLLJiL5x13BpXBBsrE:-ODLLJiL5x13BpXBBsrF:bt8ao43) ([raw file](https://github.com/starkware-libs/sequencer/blob/13e4acf14cba8035ec836a935b7e172a4ce4c436/crates/starknet_integration_tests/src/state_reader.rs#L171)):*
> ```XML
>         }
>     }
>     sierra_contract_classes
> ```

use filter_map



_Suggestion:_
```XML
    contract_classes_to_retrieve
        .iter()
        .filter_map(|contract| {
            if contract.cairo_version() == CairoVersion::Cairo1 {
                Some((contract.class_hash(), contract.sierra()))
            } else {
                None
            }
        })
        .collect()
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2467)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2467#-ODLLlDP6jYwuT7hCcD6:-ODLS9I_6Idsl51TqJ3-:b-cny5vo) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add reviewer(s) from mempool team
</blockquote></details>

I spoke with Dan before opening the PR, and he said it wasn’t necessary.
___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2467#-ODLLJiL5x13BpXBBsrE:-ODLUfOoE1F3xSJVHbJL:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/566536ca03f26a1e4229f9b477a2003d05a1b300/crates/starknet_integration_tests/src/state_reader.rs#L171)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use filter_map
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2467)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @Yoni-Starkware)

___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2467#-ODLqJXQDvyLEpJ8B5PP:-ODLqJXQDvyLEpJ8B5PQ:b-amr9pb) ([raw file](https://github.com/starkware-libs/sequencer/blob/110372ea52c71b1b28930fb0c1e2bc111d3501e6/crates/starknet_integration_tests/src/state_reader.rs#L171)):*
> ```XML
>             } else {
>                 None
>             }
> ```

sorry, missed this earlier.
please use `match`, we currently have another version variant



_Suggestion:_
```XML
            match contract.cairo_version() {
                CairoVersion::Cairo0 => None,
                CairoVersion::Cairo1 => Some((contract.class_hash(), contract.sierra())),
                #[cfg(feature = "cairo_native")]
                CairoVersion::Native => Some((contract.class_hash(), contract.sierra())),                
            }
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2467#-:-ODLvjvK3YEaAna5-0Xl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2467)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2467#-ODLqJXQDvyLEpJ8B5PP:-ODLtnDTBeNob8lOLUCL:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/110372ea52c71b1b28930fb0c1e2bc111d3501e6/crates/starknet_integration_tests/src/state_reader.rs#L171)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

sorry, missed this earlier.
please use `match`, we currently have another version variant
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2467)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 103 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2467#-ODMH7Zn8DTButbgtgD9:-ODMH7Zn8DTButbgtgDA:bjl282r) ([raw file](https://github.com/starkware-libs/sequencer/blob/f5062e4e7092a22d6a72fe10a90b87997fbeaf05/crates/blockifier/src/test_utils.rs#L103)):*
> ```XML
>     pub fn is_cairo0(&self) -> bool {
>         matches!(self, Self::Cairo0)
>     }
> ```

here, you *do* have the feature, so use full `match`



_Suggestion:_
```XML
    pub fn is_cairo0(&self) -> bool {
        match self {
            Self::Cairo0 => true,
            Self::Cairo1 => false,
            #[cfg(feature = "cairo_native")]
            Self::Native => false,
        }
    }
```
___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 169 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2467#-ODMHNHL5XLvNAjDJW84:-ODMHNHL5XLvNAjDJW85:b-pvkxpk) ([raw file](https://github.com/starkware-libs/sequencer/blob/f5062e4e7092a22d6a72fe10a90b87997fbeaf05/crates/starknet_integration_tests/src/state_reader.rs#L169)):*
> ```XML
>     contract_classes_to_retrieve
>         .filter(|contract| !contract.cairo_version().is_cairo0())
>         .map(|contract| (contract.class_hash(), contract.sierra()))
> ```

non-blocking, but filter+map should probably just be filter_map



_Suggestion:_
```XML
        .filter_map(|contract| if !contract.cairo_version().is_cairo0() {
            Some((contract.class_hash(), contract.sierra()))
        } else { None })
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2467)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 103 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2467#-ODMH7Zn8DTButbgtgD9:-OD_R3PR4JUd4kTp7F3A:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f5062e4e7092a22d6a72fe10a90b87997fbeaf05/crates/blockifier/src/test_utils.rs#L103)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

here, you *do* have the feature, so use full `match`
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/state_reader.rs` line 169 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2467#-ODMHNHL5XLvNAjDJW84:-OD_PKnc89FR_-l9dHYf:bhbm96j) ([raw file](https://github.com/starkware-libs/sequencer/blob/f5062e4e7092a22d6a72fe10a90b87997fbeaf05/crates/starknet_integration_tests/src/state_reader.rs#L169)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

non-blocking, but filter+map should probably just be filter_map
</blockquote></details>

Don’t you think this makes things clearer? I believe that using `filter_map` is a good option when the closure in the map returns an `Option`, as it clearly indicates what is being filtered. However, that isn’t the case for us. The logic behind the filter and the logic of the map are unrelated.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2467)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Comment by AvivYossef-starkware** [comment]
### Merge activity

* **Dec 8, 6:07 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2467).

**Pull request merged**
