### PR TITLE
feat(blockifier): pass alias contract address

### PR DESCRIPTION
**Pull request by yoavGrs**

### CODE REVIEW

**Comment by yoavGrs** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2674?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2674** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2674?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2674?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2535** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2535?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2534** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2534?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by nimrod-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2674#-:-OE9elov3hF_y3WMvQ1D:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2674)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2674#-OE9xcQv0He2BYUAyVKU:-OE9xcQv0He2BYUAyVKV:by8qmne) (no related file):*
why make the alias contract address a parameter? it is constant

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2674)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2674#-OE9xcQv0He2BYUAyVKU:-OEA7X1s1JJCIzTL1Lzc:b1missm) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why make the alias contract address a parameter? it is constant
</blockquote></details>

It's already in the versioned constants.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2674)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2674)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2674)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2674)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2674)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Comment by yoavGrs** [comment]
### Merge activity

* **Dec 23, 7:33 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2674).

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2674)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
