### PR TITLE
fix(mempool_p2p): avoid blocking the p2p runner while waiting for GW response

### PR DESCRIPTION
**Pull request by AlonLStarkWare**

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1977)* status: all files reviewed, 4 unresolved discussions (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`crates/mempool_p2p/src/runner/mod.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1977#-OBVJUhW5fPN-qj8qSsj:-OBVJUhW5fPN-qj8qSsk:bz0dtzc) ([raw file](https://github.com/starkware-libs/sequencer/blob/76f66bbcb16e0999a0c47c581c8397e4d0de172b/crates/mempool_p2p/src/runner/mod.rs#L49)):*
> ```XML
>             .map_err(|_| ComponentError::InternalComponentError);
>         pin_mut!(network_future);
>         let mut gateway_results = FuturesUnordered::new();
> ```

Keep this as a member of the struct
___
*[`crates/mempool_p2p/src/runner/mod.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1977#-OBVKzrH0-dJni4zBeSi:-OBVKzrH0-dJni4zBeSj:bkaw0mp) ([raw file](https://github.com/starkware-libs/sequencer/blob/76f66bbcb16e0999a0c47c581c8397e4d0de172b/crates/mempool_p2p/src/runner/mod.rs#L49)):*
> ```XML
>             .map_err(|_| ComponentError::InternalComponentError);
>         pin_mut!(network_future);
>         let mut gateway_results = FuturesUnordered::new();
> ```

Rename to gateway_requests or gateway_futures
___
*[`crates/mempool_p2p/src/runner/mod.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1977#-OBVLalV7pMk9yQODfzy:-OBVLalV7pMk9yQODfzz:b-dvoha1) ([raw file](https://github.com/starkware-libs/sequencer/blob/76f66bbcb16e0999a0c47c581c8397e4d0de172b/crates/mempool_p2p/src/runner/mod.rs#L72)):*
> ```XML
>                     match message_result {
>                         Ok(message) => {
>                             let gateway_result = self.gateway_client.add_tx(
> ```

rename to gateway_request or gateway_future
___
*[`crates/mempool_p2p/src/runner/mod.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1977#-OBVMLoG21whZZ13qBCy:-OBVLjzKDrFe8dZ9sgls:b-rfbhnd) ([raw file](https://github.com/starkware-libs/sequencer/blob/76f66bbcb16e0999a0c47c581c8397e4d0de172b/crates/mempool_p2p/src/runner/mod.rs#L74)):*
> ```XML
>                             let gateway_result = self.gateway_client.add_tx(
>                                 GatewayInput { rpc_tx: message.0, message_metadata: Some(broadcasted_message_metadata.clone()) });
>                             gateway_results.push(gateway_result.map( move |gateway_add_tx| (gateway_add_tx, broadcasted_message_metadata.clone()) ));
> ```

Remove this map. The error contains the metadata, Use that one instead https://github.com/starkware-libs/sequencer/blob/5e9d63a97d238c745b4ce752a3748ba369abc4d0/crates/gateway_types/src/errors.rs#L99

We don't want the node to store something in memory for each transaction being processed, as this might become a DDoS vector

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1977)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @eitanm-starkware and @ShahakShama)

___
*[`crates/mempool_p2p/src/runner/mod.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1977#-OBVKzrH0-dJni4zBeSi:-OBVPdatDB9aBArZRdsu:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/76f66bbcb16e0999a0c47c581c8397e4d0de172b/crates/mempool_p2p/src/runner/mod.rs#L49)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to gateway_requests or gateway_futures
</blockquote></details>

Done.
___
*[`crates/mempool_p2p/src/runner/mod.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1977#-OBVJUhW5fPN-qj8qSsj:-OBZu3stEg22h4jTErnV:b-rtyxar) ([raw file](https://github.com/starkware-libs/sequencer/blob/76f66bbcb16e0999a0c47c581c8397e4d0de172b/crates/mempool_p2p/src/runner/mod.rs#L49)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Keep this as a member of the struct
</blockquote></details>

I couldn't do this because FuturesUnordered requires inputs to be 'static
___
*[`crates/mempool_p2p/src/runner/mod.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1977#-OBVLalV7pMk9yQODfzy:-OBVPeqhA_xg_Vwb-qfM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/76f66bbcb16e0999a0c47c581c8397e4d0de172b/crates/mempool_p2p/src/runner/mod.rs#L72)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename to gateway_request or gateway_future
</blockquote></details>

Done.
___
*[`crates/mempool_p2p/src/runner/mod.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1977#-OBVMLoG21whZZ13qBCy:-OBVWkUS8eRAXxkOUojX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/76f66bbcb16e0999a0c47c581c8397e4d0de172b/crates/mempool_p2p/src/runner/mod.rs#L74)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this map. The error contains the metadata, Use that one instead https://github.com/starkware-libs/sequencer/blob/5e9d63a97d238c745b4ce752a3748ba369abc4d0/crates/gateway_types/src/errors.rs#L99

We don't want the node to store something in memory for each transaction being processed, as this might become a DDoS vector
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1977)* status: all files reviewed, 3 unresolved discussions (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`crates/starknet_mempool_p2p/src/runner/mod.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1977#-OB_NZCE-94LgEtq7pmM:-OB_NZCE-94LgEtq7pmN:bl2zrwq) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf96d170f3dca2f4718e6ac93d7f1b14963f28b0/crates/starknet_mempool_p2p/src/runner/mod.rs#L71)):*
> ```XML
>                                     match gateway_error {
>                                         GatewayError::GatewaySpecError {p2p_message_metadata, ..} => {
>                                             if let Some(p2p_message_metadata) = p2p_message_metadata {
> ```

Unite this with the previous 2 matches to a single `if let`
And change it to `let ... else { continue; }` so that you won't indent the entire code here
___
*[`crates/starknet_mempool_p2p/src/runner/mod.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1977#-OB_N91OAAkWVSFvQ4NE:-OB_N91PCZp6ENOR43ON:b-usu1cn) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf96d170f3dca2f4718e6ac93d7f1b14963f28b0/crates/starknet_mempool_p2p/src/runner/mod.rs#L72)):*
> ```XML
>                                         GatewayError::GatewaySpecError {p2p_message_metadata, ..} => {
>                                             if let Some(p2p_message_metadata) = p2p_message_metadata {
>                                                 if let Err(gateway_error) = self.broadcast_topic_client.report_peer(p2p_message_metadata.clone()).await {
> ```

This is not a gateway error, it's a network error
___
*[`crates/starknet_mempool_p2p/src/runner/mod.rs` line 86 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1977#-OB_Oqgy3wzvAq1L2075:-OB_Oqgy3wzvAq1L2076:b16skr) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf96d170f3dca2f4718e6ac93d7f1b14963f28b0/crates/starknet_mempool_p2p/src/runner/mod.rs#L86)):*
> ```XML
>                     match message_result {
>                         Ok(message) => {
>                             gateway_futures.push(self.gateway_client.add_tx(GatewayInput { rpc_tx: message.0, message_metadata: Some(broadcasted_message_metadata.clone()) }));
> ```

This is more than 100 chars. format doesn't work on macros so it's up to the developer to enforce formatting

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1977)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @eitanm-starkware and @ShahakShama)

___
*[`crates/starknet_mempool_p2p/src/runner/mod.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1977#-OB_NZCE-94LgEtq7pmM:-OB_esegEMPwFFg9PzuV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf96d170f3dca2f4718e6ac93d7f1b14963f28b0/crates/starknet_mempool_p2p/src/runner/mod.rs#L71)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Unite this with the previous 2 matches to a single `if let`
And change it to `let ... else { continue; }` so that you won't indent the entire code here
</blockquote></details>

Done.
___
*[`crates/starknet_mempool_p2p/src/runner/mod.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1977#-OB_N91OAAkWVSFvQ4NE:-OB_essYCI_9zt0cVXgN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf96d170f3dca2f4718e6ac93d7f1b14963f28b0/crates/starknet_mempool_p2p/src/runner/mod.rs#L72)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is not a gateway error, it's a network error
</blockquote></details>

Done.
___
*[`crates/starknet_mempool_p2p/src/runner/mod.rs` line 86 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1977#-OB_Oqgy3wzvAq1L2075:-OB_f9JMEMEiWIy3Yhsu:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf96d170f3dca2f4718e6ac93d7f1b14963f28b0/crates/starknet_mempool_p2p/src/runner/mod.rs#L86)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is more than 100 chars. format doesn't work on macros so it's up to the developer to enforce formatting
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1977#-:-OB_j17l-Fyc3T9_xnc2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Pull request merged**
