### PR TITLE
feat: get total l2 gas used in block

### PR DESCRIPTION
**Pull request by alonh5**

### CODE REVIEW

**Comment by alonh5** [comment]
* **#2764** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2764?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2764?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
1. Can you give some general context, for which feature is this required?
2. add a test.

> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2764#-:-OEiWi867JRoBCe2E7TL:bbie45v)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2764)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2764#-OEiVXby7pcaNC2FOXpU:-OEiVXby7pcaNC2FOXpV:undefined):*




_Suggestion:_
```
feat(starknet_batcher)
```
___
*[`crates/starknet_batcher/src/block_builder_test.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2764#-OEiXH5v4lbHfzDKbxJc:-OEiXH5v4lbHfzDKbxJd:bgx0wk2) ([raw file](https://github.com/starkware-libs/sequencer/blob/9bc4fc1e0f50f37616cf960dde3a99a4878b7455/crates/starknet_batcher/src/block_builder_test.rs#L47)):*
> ```XML
> }
> 
> fn block_execution_artifacts(
> ```

What's the purpose of this function?



_Code quote:_
```XML
block_execution_artifacts
```
___
*[`crates/starknet_batcher/src/block_builder_test.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2764#-OEiJtrIBH3bvto9giAM:-OEiJtrIBH3bvto9giAN:bjse8tb) ([raw file](https://github.com/starkware-libs/sequencer/blob/9bc4fc1e0f50f37616cf960dde3a99a4878b7455/crates/starknet_batcher/src/block_builder_test.rs#L55)):*
> ```XML
>         visited_segments_mapping: Default::default(),
>         bouncer_weights: BouncerWeights { l1_gas: 100, ..BouncerWeights::empty() },
>         l2_gas_used: Default::default(),
> ```

 I see that `Default::default` is used in the other fields here but I think that `GasAmount::Default` is clearer.



_Code quote:_
```XML
Default::default()
```
___
*[`crates/starknet_batcher/src/test_utils.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2764#-OEiW_aiB81h795qGcXn:-OEiW_aiB81h795qGcXo:bnj7hl0) ([raw file](https://github.com/starkware-libs/sequencer/blob/9bc4fc1e0f50f37616cf960dde3a99a4878b7455/crates/starknet_batcher/src/test_utils.rs#L40)):*
> ```XML
>             visited_segments_mapping: VisitedSegmentsMapping::default(),
>             bouncer_weights: BouncerWeights::empty(),
>             l2_gas_used: Default::default(),
> ```

same as above



_Code quote:_
```XML
Default
```

**Review by alonh5 — COMMENTED** [review]
Yes, we need the total l2 gas used to calculate the l2 gas price of the next block (EIP 1559). We'll need to pass it to the context that will use it to calculate and send the next blocks l2 gas prices, that's why I added it to the BlockExecutionArtifacts.

Added a test.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2764#-:-OEireEC9GUj9k0761aT:bcr09lb)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/starknet_batcher/src/block_builder_test.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2764#-OEiXH5v4lbHfzDKbxJc:-OEisrNQ6c_e8ZYc5kkZ:b1xmzpz) ([raw file](https://github.com/starkware-libs/sequencer/blob/9bc4fc1e0f50f37616cf960dde3a99a4878b7455/crates/starknet_batcher/src/block_builder_test.rs#L47)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

What's the purpose of this function?
</blockquote></details>

As you can see, it's in the test file. It's to save code duplication and share a non-trivial `BlockExecutionArtifacts` instance.

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2764)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/block_builder_test.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2764#-OEmfKVC4TTy2qbKxqQz:-OEmfKVC4TTy2qbKxqR-:bwovo3f) ([raw file](https://github.com/starkware-libs/sequencer/blob/d1fca1ca1f34428526c63ce562f08d69c409e99a/crates/starknet_batcher/src/block_builder_test.rs#L60)):*
> ```XML
>         l2_gas_used: GasAmount(execution_infos.len().try_into().unwrap()),
>     }
> }
> ```

try to remove the `execution_infos`'s clone



_Suggestion:_
```XML
    let l2_gas_used = GasAmount(execution_infos.len().try_into().unwrap());
    BlockExecutionArtifacts {
        execution_infos,
        commitment_state_diff: Default::default(),
        visited_segments_mapping: Default::default(),
        bouncer_weights: BouncerWeights { l1_gas: 100, ..BouncerWeights::empty() },
        // Each mock transaction uses 1 L2 gas so the total amount should be the number of txs.
        l2_gas_used,
    }
}
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2764)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/block_builder_test.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2764#-OEmfKVC4TTy2qbKxqQz:-OEmhTrB0N08WGPn6ged:blocm2a) ([raw file](https://github.com/starkware-libs/sequencer/blob/d1fca1ca1f34428526c63ce562f08d69c409e99a/crates/starknet_batcher/src/block_builder_test.rs#L60)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

try to remove the `execution_infos`'s clone
</blockquote></details>

Cloning is okay in tests normally, but this is okay too.

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2764#-:-OEmhwvZ3m_hgqTQTbfi:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2764)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
