### PR TITLE
feat(sequencing): cache proposals from bigger heights

### PR DESCRIPTION
**Pull request by guy-starkware**
If a proposal is received by Consensus that has height bigger than the current height, cache it into a hash map that saves it for later. 

When starting a new height, will first look to see if any cached proposals exist before listening to messages from the network.

### CODE REVIEW

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2325)* status: 2 of 19 files reviewed, 3 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 155 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2325#-OD1AfUCAai8JBAAxWV0:-OD1X7EZD4arfdZ-3Z2u:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/31603d7e19787ebf1ee95dc8b93ae0e0d263a44b/crates/sequencing/papyrus_consensus/src/manager.rs#L155)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

If you don't think a decision can happen let's explicitly panic or just log. I don't want to risk missing it.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 163 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2325#-OD1BGRKCNG2rLAWwy5s:-OD1YOi5BzkySj9Ugg6u:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/31603d7e19787ebf1ee95dc8b93ae0e0d263a44b/crates/sequencing/papyrus_consensus/src/manager.rs#L163)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Please add a TODO to remove the `continue_propagation/report_peer` from this. They make this function non cancel safe, since it's possible for `broadcasted_messages_receiver` to return a message, but when we call to one of those functions a different branch completes causing us to drop it without returning.

This is very important so please make sure I handle this as soon as your code is submitted
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2325#-OD1K-rm9m5jBY6XVMLD:-OD1YcL9DA31cq7KgxFD:b-7xt2v3) ([raw file](https://github.com/starkware-libs/sequencer/blob/31603d7e19787ebf1ee95dc8b93ae0e0d263a44b/crates/sequencing/papyrus_consensus/src/manager_test.rs#L84)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

remove? (and below)
</blockquote></details>

Yes!

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, 3 of 19 files at r7, 1 of 1 files at r8, all commit messages.
> Dismissed @guy-starkware from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2325)* status: 3 of 19 files reviewed, 2 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 47 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2325#-ODBajF-4RAPFpUhN-zz:-ODBajF08fuDQkHb5o3Q:bxs0e0m) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc1c85848ddbaa9bd7845e2194f0ca73778e5fb1/crates/sequencing/papyrus_consensus/src/manager_test.rs#L47)):*
> ```XML
> 
>     #[async_trait]
>     impl ConsensusContext for TestContext {
> ```

Now that we have removed ProposalWrapper I think we should be able to remove this whole mock scope and use the one from test_util. Can you please look into that in another PR?



_Code quote:_
```XML
    #[async_trait]
    impl ConsensusContext for TestContext {
```
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 151 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2325#-ODBZyFB2TM8P9FaQkwl:-ODBZyFB2TM8P9FaQkwm:bvrwqja) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc1c85848ddbaa9bd7845e2194f0ca73778e5fb1/crates/sequencing/papyrus_consensus/src/manager_test.rs#L151)):*
> ```XML
>                 .unwrap();
>             block_receiver
>         })
> ```

I feel like this pattern repeats a lot. WDYT of adding this helper fn?

This can be done in another PR, and also check other tests in this crate (if so put the fn def in test_util.rs)

I actually see that we don't have any examples here with us being the builder.



_Suggestion:_
```XML
fn validate_result(
    built_id: Felt,
    received_id: Felt,
) -> oneshot::Receiver<(ProposalContentId, ProposalFin)> {
    let (block_sender, block_receiver) = oneshot::channel();
    block_sender
        .send((
            ProposalContentId(built_id),
            ProposalFin { proposal_content_id: BlockHash(received_id) },
        ))
        .unwrap();
    block_receiver
}
       
        .return_once(move |_, _, _, _| {
            validate_result(Felt::TWO, Felt::TWO)
        })
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2325)* status: 2 of 19 files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 47 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2325#-ODBajF-4RAPFpUhN-zz:-ODGLUG53Gv5fktF3hNV:b-w94uxw) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc1c85848ddbaa9bd7845e2194f0ca73778e5fb1/crates/sequencing/papyrus_consensus/src/manager_test.rs#L47)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Now that we have removed ProposalWrapper I think we should be able to remove this whole mock scope and use the one from test_util. Can you please look into that in another PR?
</blockquote></details>

We can remove it because we can put the real SequencerConsensusContext instead? 
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 151 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2325#-ODBZyFB2TM8P9FaQkwl:-ODGdQx469b_mBDAyncI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc1c85848ddbaa9bd7845e2194f0ca73778e5fb1/crates/sequencing/papyrus_consensus/src/manager_test.rs#L151)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I feel like this pattern repeats a lot. WDYT of adding this helper fn?

This can be done in another PR, and also check other tests in this crate (if so put the fn def in test_util.rs)

I actually see that we don't have any examples here with us being the builder.
</blockquote></details>

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 14 of 19 files at r7, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2325)* status: all files reviewed, 2 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 47 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2325#-ODBajF-4RAPFpUhN-zz:-ODH8ZU07NJTvoKq5oDK:b-lg2f2k) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc1c85848ddbaa9bd7845e2194f0ca73778e5fb1/crates/sequencing/papyrus_consensus/src/manager_test.rs#L47)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

We can remove it because we can put the real SequencerConsensusContext instead?
</blockquote></details>

No, a given implementation of the Context trait cannot have any impact here since we are generic. I believe that we can redefine the test_util struct to have `ProposalPart = TestProposalPart` with:

enum TestProposalPart { ProposalInit, ProposalFin }.

This is another PR though so we can discuss when you get to it.
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 105 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2325#-ODH8VXb1hgY-wGXgNz3:-ODH8VXb1hgY-wGXgNz4:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/d53c1c5e0ef222780c586849ad7cd68ef79eaa55/crates/sequencing/papyrus_consensus/src/manager_test.rs#L105)):*
> ```XML
> }
> 
> fn context_validates_hashes(context: &mut MockTestContext, block_hash: Felt) {
> ```





_Suggestion:_
```XML
fn expect_validate_proposal(context: &mut MockTestContext, block_hash: Felt) {
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2325)* status: all files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 47 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2325#-ODBajF-4RAPFpUhN-zz:-ODIVwuy8Us4AqyR0ywj:byuqr5b) ([raw file](https://github.com/starkware-libs/sequencer/blob/bc1c85848ddbaa9bd7845e2194f0ca73778e5fb1/crates/sequencing/papyrus_consensus/src/manager_test.rs#L47)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

No, a given implementation of the Context trait cannot have any impact here since we are generic. I believe that we can redefine the test_util struct to have `ProposalPart = TestProposalPart` with:

enum TestProposalPart { ProposalInit, ProposalFin }.

This is another PR though so we can discuss when you get to it.
</blockquote></details>

Ok, I'm putting it on my list. 
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 105 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2325#-ODH8VXb1hgY-wGXgNz3:-ODIWLRF8cEB72kTsM6L:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d53c1c5e0ef222780c586849ad7cd68ef79eaa55/crates/sequencing/papyrus_consensus/src/manager_test.rs#L105)):*
> ```XML
> }
> 
> fn context_validates_hashes(context: &mut MockTestContext, block_hash: Felt) {
> ```

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2325)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Review by guy-starkware — COMMENTED** [review]
> Reviewed 14 of 19 files at r7, 12 of 13 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2325)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Pull request merged**
