### PR TITLE
chore(batcher): add use_kzg_da flag to propose block input

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#2219** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2219?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2219?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2219#-:-OCDkoeT-lvNERsmuDlC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2219)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @alonh5 and @dan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2219#-OCE3zbbBdytmRMKRUyg:-OCE3zbbBdytmRMKRUyh:b-buiikz) ([raw file](https://github.com/starkware-libs/sequencer/blob/6132fc9824502773c08555a67805a5bcd93a276e/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L118)):*
> ```XML
>                 hash: BlockHash::default(),
>             }),
>             use_kzg_da: false, // TODO: Pass non-default value.
> ```

Changed to `true` to match the [current](https://github.com/starkware-libs/sequencer/blob/2844be96648c3dd7e31769dd7494a0c9b1e09932/crates/starknet_batcher/src/block_builder.rs#L258C1-L258C30) `BlockBuilderConfig::default()`.



_Suggestion:_
```XML
use_kzg_da: true, // TODO: Pass non-default value.
```

**Review by alonh5 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2219)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2219#-OCE3zbbBdytmRMKRUyg:-OCEFVPdATt45rp-F4xh:bl9hxro) ([raw file](https://github.com/starkware-libs/sequencer/blob/6132fc9824502773c08555a67805a5bcd93a276e/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L118)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Changed to `true` to match the [current](https://github.com/starkware-libs/sequencer/blob/2844be96648c3dd7e31769dd7494a0c9b1e09932/crates/starknet_batcher/src/block_builder.rs#L258C1-L258C30) `BlockBuilderConfig::default()`.
</blockquote></details>

Oh good catch.

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2219)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_batcher_types/src/batcher_types.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2219#-OCS94eg8NL_qj3DduDV:-OCS94eh8Wn3DGQKs7Nk:b1vk44c) ([raw file](https://github.com/starkware-libs/sequencer/blob/155dcd20ef2bc24d417236c50360d866da54f43d/crates/starknet_batcher_types/src/batcher_types.rs#L38)):*
> ```XML
>     pub deadline: chrono::DateTime<Utc>,
>     pub retrospective_block_hash: Option<BlockHashAndNumber>,
>     pub use_kzg_da: bool,
> ```

Why don't we document these?



_Code quote:_
```XML
pub use_kzg_da: bool,
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 118 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2219#-OCS9xyg1kOGa9CftN1i:-OCS9xyg1kOGa9CftN1j:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/155dcd20ef2bc24d417236c50360d866da54f43d/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L118)):*
> ```XML
>                 hash: BlockHash::default(),
>             }),
>             use_kzg_da: true, // TODO: Pass non-default value.
> ```





_Suggestion:_
```XML
 // TODO (Dan, Matan): Pass non-default value.
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2219)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/starknet_batcher_types/src/batcher_types.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2219#-OCS94eg8NL_qj3DduDV:-OCSEDgQBMtdnOC-xBLu:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/155dcd20ef2bc24d417236c50360d866da54f43d/crates/starknet_batcher_types/src/batcher_types.rs#L38)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why don't we document these?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 118 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2219#-OCS9xyg1kOGa9CftN1i:-OCSEBOMCkZcBrh0vzCC:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/155dcd20ef2bc24d417236c50360d866da54f43d/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L118)):*
> ```XML
>                 hash: BlockHash::default(),
>             }),
>             use_kzg_da: true, // TODO: Pass non-default value.
> ```

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
Blocking - pass the whole block info, as we discussed.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2219#-:-OCDkZD84X6dj5oMNBGx:bu6u6hi)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
Closing this PR, as a more end-to-end approach was taken. See #2238

**Pull request closed without merging**
