### PR TITLE
chore: bug fix in tx macro in mempool test utils

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1349)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#1349** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1349?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1349#-:-O93v7Ob1iOovgre3epr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @Yael-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1349#-:-O93vs3e9BTaIHwege--:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Comment by ArniStarkware** [comment]
Fixes a logical conflict with #1317.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1349)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by elintul — APPROVED** [review]
What was the conflict? Only your PR touched this macro. I wonder how your CI passed.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1349#-:-O93wPQLAqwpvZrZ7FQQ:bl1js1y)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
the macro pasted the `use` in all usages of the macro; if another PR removed the usage of GasPrice in the macro usage this could happen

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1349#-:-O93wmHM-o9IbcOCDOtr:byu9oqr)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by elintul — APPROVED** [review]
No PR removed it, AFAIK...

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1349#-:-O93x1CX34n2JCymTVaF:b-9uj9nx)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1349)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1349)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1349)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Comment by ArniStarkware** [comment]
answered in slack.

**Review by elintul — APPROVED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1349#-:-O93xQTdENVBK0JEvenk:b-ucfknh)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1349)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
