### PR TITLE
chore(blockifier): move function definition out of macro

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1087)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1087)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 184 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1087#-O7y2lcM1S6kXWYeSgI2:-O7y2lcN1e0yAlRvxwRg:b-rv0xt8) ([raw file](https://github.com/starkware-libs/sequencer/blob/36eef87bd3f9c6d1f36d976208d0dd628f6692d0/crates/blockifier/src/versioned_constants.rs#L184)):*
> ```XML
> 
>     /// Get the constants that shipped with the current version of the Blockifier.
>     /// To use custom constants, initialize the struct from a file using `from_path`.
> ```

the `try_from` no longer exists, it was replaced with an explicit `from_path` associated method



_Code quote:_
```XML
`from_path`
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1087)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 184 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1087#-O7y2lcM1S6kXWYeSgI2:-O7y3IVfACyGi6F9PyjH:b-nu3ixp) ([raw file](https://github.com/starkware-libs/sequencer/blob/36eef87bd3f9c6d1f36d976208d0dd628f6692d0/crates/blockifier/src/versioned_constants.rs#L184)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the `try_from` no longer exists, it was replaced with an explicit `from_path` associated method
</blockquote></details>

Can you move this method to the top of the impl block?
___
*[`crates/blockifier/src/versioned_constants.rs` line 184 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1087#-O7y3O8w-1o4UE1Y3SoZ:-O7y3O8w-1o4UE1Y3So_:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/36eef87bd3f9c6d1f36d976208d0dd628f6692d0/crates/blockifier/src/versioned_constants.rs#L184)):*
> ```XML
> 
>     /// Get the constants that shipped with the current version of the Blockifier.
>     /// To use custom constants, initialize the struct from a file using `from_path`.
> ```





_Suggestion:_
```XML
    /// Gets the constants for the specified Starknet version.
    pub fn get(version: StarknetVersion) -> &'static Self {
        version.into()
    }

    /// Gets the constants that shipped with the current version of the Blockifier.
    /// To use custom constants, initialize the struct from a file using `from_path`.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1087)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 184 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1087#-O7y3O8w-1o4UE1Y3SoZ:-O7y3Xtu8Q-ycIXjRfo_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/36eef87bd3f9c6d1f36d976208d0dd628f6692d0/crates/blockifier/src/versioned_constants.rs#L184)):*
> ```XML
> 
>     /// Get the constants that shipped with the current version of the Blockifier.
>     /// To use custom constants, initialize the struct from a file using `from_path`.
> ```

Done.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1087)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 184 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1087#-O7y2lcM1S6kXWYeSgI2:-O7y3inCBehoXVuJn8X3:b-mrlh5m) ([raw file](https://github.com/starkware-libs/sequencer/blob/36eef87bd3f9c6d1f36d976208d0dd628f6692d0/crates/blockifier/src/versioned_constants.rs#L184)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you move this method to the top of the impl block?
</blockquote></details>

I meant the `from_path` method :)
It is hidden in the end right now

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1087#-:-O7y3r9t4CIx4HERKgUt:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1087)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
