### PR TITLE
test(mempool): test_add_tx_after_get_txs_fails_on_duplicate_nonce

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/216)

### CODE REVIEW

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/216)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/216)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/216)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 571 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/216#-O3WuVcX7lzAy3OodrRp:-O3WuVcX7lzAy3OodrRq:b-8e8e5t) ([raw file](https://github.com/starkware-libs/sequencer/blob/495fd6cfb3fee16f072b86276576e8d73218351d/crates/mempool/src/mempool_test.rs#L571)):*
> ```XML
>     mempool.get_txs(1).unwrap();
>     let res = mempool.add_tx(input_tx);
> ```

Add a TODO to use `add_tx`-and-expect-error util?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/216)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 571 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/216#-O3WuVcX7lzAy3OodrRp:-O3g5ILc7sc0Zb3imUDa:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/495fd6cfb3fee16f072b86276576e8d73218351d/crates/mempool/src/mempool_test.rs#L571)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a TODO to use `add_tx`-and-expect-error util?
</blockquote></details>

Done

**Review by giladchase — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/216)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 567 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/216#-O4JsC1B2pzzjQDR9Zyg:-O4JsC1C8_WTstJALZcB:bjcazyx) ([raw file](https://github.com/starkware-libs/sequencer/blob/b11f2ac45e44a855999f07dc28088acbacb8490b/crates/mempool/src/mempool_test.rs#L567)):*
> ```XML
>     // Setup.
>     let input_tx =
>         add_tx_input!(tx_hash: 1, sender_address: "0x0", tx_nonce: 0_u8, account_nonce: 0_u8);
> ```

The tx_hash: 1 wasn't used, effectively you just wanted something with nonce 0, which is already the default.



_Suggestion:_
```XML
let input_tx = MempoolInput::default();
```
___
*[`crates/mempool/src/mempool_test.rs` line 581 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/216#-O4JsX1D7mUJ4rYpjIrn:-O4JsX1D7mUJ4rYpjIro:b8yp3nf) ([raw file](https://github.com/starkware-libs/sequencer/blob/b11f2ac45e44a855999f07dc28088acbacb8490b/crates/mempool/src/mempool_test.rs#L581)):*
> ```XML
>             address: contract_address!("0x0"),
>             nonce: Nonce(felt!(0_u16)),
>         },
> ```

There is only one address playing here, no need to refer to it by name 



_Suggestion:_
```XML
        MempoolError::DuplicateNonce {
            nonce: Nonce(felt!(0_u16)),
            ..
        },
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/216)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 567 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/216#-O4JsC1B2pzzjQDR9Zyg:-O4KKsRbAlav9ToSGwwO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b11f2ac45e44a855999f07dc28088acbacb8490b/crates/mempool/src/mempool_test.rs#L567)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

The tx_hash: 1 wasn't used, effectively you just wanted something with nonce 0, which is already the default.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 581 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/216#-O4JsX1D7mUJ4rYpjIrn:-O4KNupP3qHKZTdiKDUp:b-ktkxke) ([raw file](https://github.com/starkware-libs/sequencer/blob/b11f2ac45e44a855999f07dc28088acbacb8490b/crates/mempool/src/mempool_test.rs#L581)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

There is only one address playing here, no need to refer to it by name
</blockquote></details>

I prefer the original code because it is easier to read.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/216)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 567 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/216#-O4JsC1B2pzzjQDR9Zyg:-O4Z4SpBExJhIPMZAo9T:b-36dsot) ([raw file](https://github.com/starkware-libs/sequencer/blob/b11f2ac45e44a855999f07dc28088acbacb8490b/crates/mempool/src/mempool_test.rs#L567)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you make sure that we use `default` c-tor in all tests we have a _single_ mempool input?
___
*[`crates/mempool/src/mempool_test.rs` line 581 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/216#-O4JsX1D7mUJ4rYpjIrn:-O4Z4dzHA7HMZ1VBQwhO:b-272jik) ([raw file](https://github.com/starkware-libs/sequencer/blob/b11f2ac45e44a855999f07dc28088acbacb8490b/crates/mempool/src/mempool_test.rs#L581)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I prefer the original code because it is easier to read.
</blockquote></details>

Now that you use `default`, I think it's more readable to only pass the nonce.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/216)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 567 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/216#-O4JsC1B2pzzjQDR9Zyg:-O4_s-DU3HX6lmBgJE8E:b-7bhps4) ([raw file](https://github.com/starkware-libs/sequencer/blob/b11f2ac45e44a855999f07dc28088acbacb8490b/crates/mempool/src/mempool_test.rs#L567)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you make sure that we use `default` c-tor in all tests we have a _single_ mempool input?
</blockquote></details>

Added to https://starkware.monday.com/boards/6678575467/pulses/7246965100
___
*[`crates/mempool/src/mempool_test.rs` line 581 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/216#-O4JsX1D7mUJ4rYpjIrn:-O4_qs0KEAMlyYgPgatZ:b-9wx6z4) ([raw file](https://github.com/starkware-libs/sequencer/blob/b11f2ac45e44a855999f07dc28088acbacb8490b/crates/mempool/src/mempool_test.rs#L581)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Now that you use `default`, I think it's more readable to only pass the nonce.
</blockquote></details>

It required default for MempoolError.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/216)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 567 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/216#-O4JsC1B2pzzjQDR9Zyg:-O4d4DsDEiOO2cPAKVYs:brvrt3k) ([raw file](https://github.com/starkware-libs/sequencer/blob/b11f2ac45e44a855999f07dc28088acbacb8490b/crates/mempool/src/mempool_test.rs#L567)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Added to https://starkware.monday.com/boards/6678575467/pulses/7246965100
</blockquote></details>

This is a small check that shouldn't take long, no need to add to future tasks.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/216)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 567 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/216#-O4JsC1B2pzzjQDR9Zyg:-O4d6pVUAytQDYkofxW7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b11f2ac45e44a855999f07dc28088acbacb8490b/crates/mempool/src/mempool_test.rs#L567)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This is a small check that shouldn't take long, no need to add to future tasks.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/216#-:-O4d778J3J3GM6yyEh_b:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 567 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/216#-O4JsC1B2pzzjQDR9Zyg:-O4d75Mc2WGSKknwOzVm:b-ucfknh) ([raw file](https://github.com/starkware-libs/sequencer/blob/b11f2ac45e44a855999f07dc28088acbacb8490b/crates/mempool/src/mempool_test.rs#L567)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/216)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 567 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/216#-O4JsC1B2pzzjQDR9Zyg:-O4d8Iio2aou2_2YF0gk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b11f2ac45e44a855999f07dc28088acbacb8490b/crates/mempool/src/mempool_test.rs#L567)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/216)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

**Review by OmriEshhar1 — COMMENTED** [review]
> Dismissed @giladchase from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/216)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by OmriEshhar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/216)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

**Review by OmriEshhar1 — APPROVED** [review]
> Dismissed @elintul from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/216)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

**Review by OmriEshhar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/216)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/216#-:-O4dX6PzE2bzjeY7vEHB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @OmriEshhar1)

**Review by elintul — APPROVED** [review]

**Review by elintul — APPROVED** [review]

**Review by elintul — APPROVED** [review]

**Pull request merged**
