### PR TITLE
fix(starknet_sierra_compile): resolve out_dir usage

### PR DESCRIPTION
**Pull request by avi-starkware**

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2616)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @avi-starkware)

___
*[`crates/starknet_sierra_compile/build.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2616#-ODjwhlt7kIbWV3Mw0kW:-ODjwhlt7kIbWV3Mw0kX:bqxe9vw) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d3144e110dde1d7140b123917773f49ee0cee10/crates/starknet_sierra_compile/build.rs#L51)):*
> ```XML
>     // Create a directory to store the compiled outputs.
>     let compiled_output_dir = compilation_output_dir(out_dir());
>     std::fs::create_dir_all(&compiled_output_dir).expect("Failed to create the output directory.");
> ```

Please see comment below :pray: 



_Code quote:_
```XML
std::fs::create_dir_all(&compiled_output_dir).expect("Failed to create the output directory.");
```
___
*[`crates/starknet_sierra_compile/src/paths.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2616#-ODjx6t73J6iq9n2Cwcf:-ODjx6t89gndHruFXPSC:b-uvi2fp) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d3144e110dde1d7140b123917773f49ee0cee10/crates/starknet_sierra_compile/src/paths.rs#L28)):*
> ```XML
> #[cfg(feature = "cairo_native")]
> pub fn compilation_output_file_path(out_dir: std::path::PathBuf) -> String {
>     compilation_output_dir(out_dir).join("output.so").to_str().unwrap().into()
> ```

I'm slightly confused: 

I thought that `out_dir()` points to the outputs of the build script, namely the native compiler executable. 
`out_dir()` example: `target/debug/build/starknet_sierra_compile-e679b05b01eef89a`

I also thought that during the build process, the binaries are moved from `out_dir()` to `target/debug/shared_executables`

Why does the code require `out_dir()` to invoke the executables and to access their results? I would have expected it to rely on `target/debug/shared_executables` for that.

Am I missing something?



_Code quote:_
```XML
compilation_output_dir(out_dir).join("output.so").to_str().unwrap().into()
```
___
*[`crates/starknet_sierra_compile/src/command_line_compiler.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2616#-ODjwLZm3vp91kzoD6ym:-ODjwLZm3vp91kzoD6yn:bha58ap) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d3144e110dde1d7140b123917773f49ee0cee10/crates/starknet_sierra_compile/src/command_line_compiler.rs#L71)):*
> ```XML
>         let output_directory = compilation_output_dir(out_dir());
>         std::fs::create_dir_all(&output_directory)
>             .expect("Failed to create native compilation output directory");
> ```

WDYT about moving this into `compilation_output_dir(...)`?



_Code quote:_
```XML
        std::fs::create_dir_all(&output_directory)
            .expect("Failed to create native compilation output directory");
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2616)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @avi-starkware)

___
*[`crates/starknet_sierra_compile/build.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2616#-ODjyrwVBFsrfx3Nmfwq:-ODjyrwVBFsrfx3Nmfwr:bmy416c) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d3144e110dde1d7140b123917773f49ee0cee10/crates/starknet_sierra_compile/build.rs#L109)):*
> ```XML
>         .args([post_install_file_path.as_os_str(), binary_path.as_os_str()])
>         .status()
>         .expect("Failed to perform mv command.");
> ```

Using this pr to point at another issue:
I think that this `mv` command is the culprit that re-triggers the build process -- the executable is removed from the `out_dir()`, triggering the `println!("cargo:rerun-if-changed={:?}", binary_path);` invocation condition.

Could we please change this to `cp` for the meanwhile, and add a todo to further investigate / design a more suited mechanim?

@noaov1 @giladchase @dan-starkware @dorimedini-starkware FYI



_Code quote:_
```XML
    let move_command_status = Command::new("mv")
        .args([post_install_file_path.as_os_str(), binary_path.as_os_str()])
        .status()
        .expect("Failed to perform mv command.");
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2616)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @dan-starkware, @dorimedini-starkware, @giladchase, @Itay-Tsabary-Starkware, and @noaov1)

___
*[`crates/starknet_sierra_compile/build.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2616#-ODjwhlt7kIbWV3Mw0kW:-ODk40IhA9EZC5LTpZMx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d3144e110dde1d7140b123917773f49ee0cee10/crates/starknet_sierra_compile/build.rs#L51)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please see comment below :pray:
</blockquote></details>

Done.
___
*[`crates/starknet_sierra_compile/build.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2616#-ODjyrwVBFsrfx3Nmfwq:-ODk0v7MAF0yWEZfz4Ci:bfz5xf5) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d3144e110dde1d7140b123917773f49ee0cee10/crates/starknet_sierra_compile/build.rs#L109)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Using this pr to point at another issue:
I think that this `mv` command is the culprit that re-triggers the build process -- the executable is removed from the `out_dir()`, triggering the `println!("cargo:rerun-if-changed={:?}", binary_path);` invocation condition.

Could we please change this to `cp` for the meanwhile, and add a todo to further investigate / design a more suited mechanim?

@noaov1 @giladchase @dan-starkware @dorimedini-starkware FYI
</blockquote></details>

I don't think that is the issue. I think I resolved the re-triggering of the build process. The culprit was `REQUIRED_CAIRO_NATIVE_VERSION`. It held the wrong version, so re-installation was always required. Now, rebuilding the crate after a successful build takes less than 1 second.
___
*[`crates/starknet_sierra_compile/src/command_line_compiler.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2616#-ODjwLZm3vp91kzoD6ym:-ODk3zzj9v1LU8j-AYyX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d3144e110dde1d7140b123917773f49ee0cee10/crates/starknet_sierra_compile/src/command_line_compiler.rs#L71)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

WDYT about moving this into `compilation_output_dir(...)`?
</blockquote></details>

Done.
___
*[`crates/starknet_sierra_compile/src/paths.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2616#-ODjx6t73J6iq9n2Cwcf:-ODk1wsj8PKJ82fTu6jQ:bix1dlr) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d3144e110dde1d7140b123917773f49ee0cee10/crates/starknet_sierra_compile/src/paths.rs#L28)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I'm slightly confused: 

I thought that `out_dir()` points to the outputs of the build script, namely the native compiler executable. 
`out_dir()` example: `target/debug/build/starknet_sierra_compile-e679b05b01eef89a`

I also thought that during the build process, the binaries are moved from `out_dir()` to `target/debug/shared_executables`

Why does the code require `out_dir()` to invoke the executables and to access their results? I would have expected it to rely on `target/debug/shared_executables` for that.

Am I missing something?
</blockquote></details>

This is just a path to put the output of sierra -> native compilation in. Not the path to the binary of the compiler itself.
Should I change this path to `/tmp`?

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2616)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @avi-starkware)

___
*[`crates/starknet_sierra_compile/build.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2616#-ODjyrwVBFsrfx3Nmfwq:-ODkC1kU-wuioEsRBjRk:bkcpsiw) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d3144e110dde1d7140b123917773f49ee0cee10/crates/starknet_sierra_compile/build.rs#L109)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I don't think that is the issue. I think I resolved the re-triggering of the build process. The culprit was `REQUIRED_CAIRO_NATIVE_VERSION`. It held the wrong version, so re-installation was always required. Now, rebuilding the crate after a successful build takes less than 1 second.
</blockquote></details>

:crown: 
___
*[`crates/starknet_sierra_compile/src/paths.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2616#-ODjx6t73J6iq9n2Cwcf:-ODkCMXd9R5ZJ4Fu_-_w:b5g1c2g) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d3144e110dde1d7140b123917773f49ee0cee10/crates/starknet_sierra_compile/src/paths.rs#L28)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

This is just a path to put the output of sierra -> native compilation in. Not the path to the binary of the compiler itself.
Should I change this path to `/tmp`?
</blockquote></details>

Yes, please do :saluting_face:

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2616)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sierra_compile/src/paths.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2616#-ODjx6t73J6iq9n2Cwcf:-ODkEAteEskS8DSK-ZB1:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d3144e110dde1d7140b123917773f49ee0cee10/crates/starknet_sierra_compile/src/paths.rs#L28)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Yes, please do :saluting_face:
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2616)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @avi-starkware)

___
*[`crates/starknet_sierra_compile/src/paths.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2616#-ODjx6t73J6iq9n2Cwcf:-ODkJNHi8KYXShFEq6XB:brmvc07) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d3144e110dde1d7140b123917773f49ee0cee10/crates/starknet_sierra_compile/src/paths.rs#L28)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please see the suggestion above. If you find it appealing, then you can delete both of these functions.
If not, regardless of other changes, I suggest unifying them into a single function, as `compilation_output_dir()` is used only once, by `compilation_output_file_path()`.
___
*[`crates/starknet_sierra_compile/src/command_line_compiler.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2616#-ODkI6FR1WiKuAPFzhYq:-ODkI6FR1WiKuAPFzhYr:bh8preq) ([raw file](https://github.com/starkware-libs/sequencer/blob/62961e68201c641bdcfb288b2898ea4d2a3c4029/crates/starknet_sierra_compile/src/command_line_compiler.rs#L69)):*
> ```XML
>     ) -> Result<AotContractExecutor, CompilationUtilError> {
>         let compiler_binary_path = &self.path_to_starknet_native_compile_binary;
>         let output_file_path = compilation_output_file_path();
> ```

Suggestion:
1. create a rust temp dir here (`tempdir()`)
2. create the output path with `.join("output.so")`

This has the added benefits of:
1. It maintains the temp dir handle exactly for as needed: the scope of this function.
2. Multiple / concurrent invocations should not interfere with each other
3. Resistent to the OS cleaning `/tmp` in the background
4. Removes the need for other functions.

WDYT? 



_Code quote:_
```XML
let output_file_path = compilation_output_file_path();
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2616)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sierra_compile/src/command_line_compiler.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2616#-ODkI6FR1WiKuAPFzhYq:-ODkNBo79gMHu9SdRJeB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/62961e68201c641bdcfb288b2898ea4d2a3c4029/crates/starknet_sierra_compile/src/command_line_compiler.rs#L69)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Suggestion:
1. create a rust temp dir here (`tempdir()`)
2. create the output path with `.join("output.so")`

This has the added benefits of:
1. It maintains the temp dir handle exactly for as needed: the scope of this function.
2. Multiple / concurrent invocations should not interfere with each other
3. Resistent to the OS cleaning `/tmp` in the background
4. Removes the need for other functions.

WDYT?
</blockquote></details>

Done.
___
*[`crates/starknet_sierra_compile/src/paths.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2616#-ODjx6t73J6iq9n2Cwcf:-ODkNEau2AVoLUdoB4pf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d3144e110dde1d7140b123917773f49ee0cee10/crates/starknet_sierra_compile/src/paths.rs#L28)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please see the suggestion above. If you find it appealing, then you can delete both of these functions.
If not, regardless of other changes, I suggest unifying them into a single function, as `compilation_output_dir()` is used only once, by `compilation_output_file_path()`.
</blockquote></details>

Done.

**Pull request merged**
