### PR TITLE
chore(execution): generalize contract class in executable txs

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1117)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
@avivg-starkware  FYI

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-:-O82j3XVBIrZEsgXr26l:b3mq8kj)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @ArniStarkware and @meship-starkware)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1117)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O85X_tSEvEV4Mvz5sJe:-O85X_tSEvEV4Mvz5sJf:b-6krz8n) ([raw file](https://github.com/starkware-libs/sequencer/blob/77316ce7c5d73d00be0ac681f3828e39f6f2a7eb/crates/blockifier/src/execution/contract_class.rs#L88)):*
> ```XML
>         Ok(contract_class)
>     }
> }
> ```

Why do we need one for & and one without here?

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/contract_class.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O85gFXv7S8oRlSjdhhO:-O85gFXv7S8oRlSjdhhP:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/77316ce7c5d73d00be0ac681f3828e39f6f2a7eb/crates/blockifier/src/execution/contract_class.rs#L88)):*
> ```XML
>         Ok(contract_class)
>     }
> }
> ```





_Suggestion:_
```XML
// TODO(Noa): Reconsider the code duplication.
impl TryFrom<&RawContractClass> for ContractClass {
    type Error = ProgramError;

    // Warning: This function is not supported for Cairo 0 contracts.
    fn try_from(raw_contract_class: &RawContractClass) -> Result<Self, Self::Error> {
        let contract_class: ContractClass = match raw_contract_class {
            RawContractClass::V0(_) => panic!("Cairo 0 does not support conversion by referance."),
            RawContractClass::V1(raw_contract_class) => {
                ContractClass::V1(raw_contract_class.try_into()?)
            }
        };

        Ok(contract_class)
    }
}
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/contract_class.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O85gFXv7S8oRlSjdhhO:-O85ghgO4s-pkfO1DxAQ:b-nsbike) ([raw file](https://github.com/starkware-libs/sequencer/blob/77316ce7c5d73d00be0ac681f3828e39f6f2a7eb/crates/blockifier/src/execution/contract_class.rs#L88)):*
> ```XML
>         Ok(contract_class)
>     }
> }
> ```

*reference.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1117)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O85X_tSEvEV4Mvz5sJe:-O85fzSxAXgwLwG5d7a8:bu4l71p) ([raw file](https://github.com/starkware-libs/sequencer/blob/77316ce7c5d73d00be0ac681f3828e39f6f2a7eb/crates/blockifier/src/execution/contract_class.rs#L88)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why do we need one for & and one without here?
</blockquote></details>

Even before the change, there was a by-ref version here, but you do have a point. See my other comment [here]( https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O85gFXv7S8oRlSjdhhO)
___
*[`crates/blockifier/src/execution/contract_class.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O85gv624ig4tH3LYc26:-O85gv624ig4tH3LYc27:b-qvhv7h) ([raw file](https://github.com/starkware-libs/sequencer/blob/77316ce7c5d73d00be0ac681f3828e39f6f2a7eb/crates/blockifier/src/execution/contract_class.rs#L88)):*
> ```XML
>         Ok(contract_class)
>     }
> }
> ```

If you decide not to take the panic route - you can remove `impl TryFrom<&DeprecatedContractClass> for ContractClassV0` with this change. (A clone is happening either way).



_Suggestion:_
```XML
// TODO(Noa): Reconsider the code duplication.
impl TryFrom<&RawContractClass> for ContractClass {
    type Error = ProgramError;

    fn try_from(raw_contract_class: &RawContractClass) -> Result<Self, Self::Error> {
        let contract_class: ContractClass = match raw_contract_class {
            RawContractClass::V0(raw_contract_class) => {
                ContractClass::V0(raw_contract_class.clone().try_into()?)
            }
            RawContractClass::V1(raw_contract_class) => {
                ContractClass::V1(raw_contract_class.try_into()?)
            }
        };

        Ok(contract_class)
    }
}
```
___
*[`crates/starknet_api/src/contract_class.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O85NqVWCO_N58jpheIt:-O85NqVWCO_N58jpheIu:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/77316ce7c5d73d00be0ac681f3828e39f6f2a7eb/crates/starknet_api/src/contract_class.rs#L17)):*
> ```XML
>     pub fn compiled_class_hash(&self) -> CompiledClassHash {
>         match self {
>             ContractClass::V0(_) => panic!("Cairo0 doesn't have compiled class hash."),
> ```





_Suggestion:_
```XML
"Cairo 0 doesn't have compiled class hash."
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1117)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @meship-starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O85X_tSEvEV4Mvz5sJe:-O8MQbEZAcXUo8G79tmK:bv4ln4u) ([raw file](https://github.com/starkware-libs/sequencer/blob/77316ce7c5d73d00be0ac681f3828e39f6f2a7eb/crates/blockifier/src/execution/contract_class.rs#L88)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Even before the change, there was a by-ref version here, but you do have a point. See my other comment [here]( https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O85gFXv7S8oRlSjdhhO)
</blockquote></details>

Both are used (the reference is used in the gateway and the non-reference in papyrus). We can (and should) consider removing one (in a separate PR).
___
*[`crates/blockifier/src/execution/contract_class.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O85gFXv7S8oRlSjdhhO:-O8MUA4mErTSQrm4meyi:bnnlcsl) ([raw file](https://github.com/starkware-libs/sequencer/blob/77316ce7c5d73d00be0ac681f3828e39f6f2a7eb/crates/blockifier/src/execution/contract_class.rs#L88)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

*reference.
</blockquote></details>

Implemented using `clone()` (as you also suggested).  Thanks!
___
*[`crates/blockifier/src/execution/contract_class.rs` line 228 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O85hS1l79DWMoFWckPB:-O8MU-m03cQUXpNsSS60:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/77316ce7c5d73d00be0ac681f3828e39f6f2a7eb/crates/blockifier/src/execution/contract_class.rs#L228)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

As I said - this can be removed.
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/contract_class.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O85NqVWCO_N58jpheIt:-O8MU8-X00HBuebY_47n:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/77316ce7c5d73d00be0ac681f3828e39f6f2a7eb/crates/starknet_api/src/contract_class.rs#L17)):*
> ```XML
>     pub fn compiled_class_hash(&self) -> CompiledClassHash {
>         match self {
>             ContractClass::V0(_) => panic!("Cairo0 doesn't have compiled class hash."),
> ```

Done.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1117)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 79 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O8_uxTL3GW4qOvaOZTz:-O8_uxTL3GW4qOvaOZU-:b38u4us) ([raw file](https://github.com/starkware-libs/sequencer/blob/63333e484c46135c1dd6d5215694662d985b137a/crates/blockifier/src/execution/contract_class.rs#L79)):*
> ```XML
>             RawContractClass::V0(raw_contract_class) => {
>                 ContractClass::V0(raw_contract_class.clone().try_into()?)
>             }
> ```

Suggesting this once more.
We do not want to use this conversion by ref - do we?



_Suggestion:_
```XML
            RawContractClass::V0(raw_contract_class) => {
                 panic!("Cairo 0 does not support conversion by referance.")
            }
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O8_ugkd46tJ_9QzPENX:-O8_ugkd46tJ_9QzPENY:b-t3lu3m) ([raw file](https://github.com/starkware-libs/sequencer/blob/63333e484c46135c1dd6d5215694662d985b137a/crates/blockifier/src/execution/contract_class.rs#L95)):*
> ```XML
>         Self::try_from(&raw_contract_class)
>     }
> }
> ```

This is using the wrong `try_from`. Befoe this PR the `try_from` was the version that took ownership.



_Code quote:_
```XML
impl TryFrom<RawContractClass> for ContractClass {
    type Error = ProgramError;

    fn try_from(raw_contract_class: RawContractClass) -> Result<Self, Self::Error> {
        Self::try_from(&raw_contract_class)
    }
}
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1117)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 436 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O8_x9pZ1x1mF1CXGnFt:-O8_x9pZ1x1mF1CXGnFu:b-p1uvy8) ([raw file](https://github.com/starkware-libs/sequencer/blob/63333e484c46135c1dd6d5215694662d985b137a/crates/blockifier/src/execution/contract_class.rs#L436)):*
> ```XML
> 
>     fn try_from(class: CasmContractClass) -> Result<Self, Self::Error> {
>         Self::try_from(&class)
> ```

Again - this is using the wrong try_from.

Let us split this into two PRs.
The first one is about adding `RawContractClass` (i.e., `starknet_api::contract_class::ContractClass`).



_Code quote:_
```XML
        Self::try_from(&class)
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1117)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @meship-starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 79 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O8_uxTL3GW4qOvaOZTz:-O8a0uRmDmoxlGqD-sGp:brvqxbt) ([raw file](https://github.com/starkware-libs/sequencer/blob/63333e484c46135c1dd6d5215694662d985b137a/crates/blockifier/src/execution/contract_class.rs#L79)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Suggesting this once more.
We do not want to use this conversion by ref - do we?
</blockquote></details>

It is currently only used in the gateway. I prefer to be consistent with cairo 1. Why are we so against cloning? 
Changed. 
___
*[`crates/blockifier/src/execution/contract_class.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O8_ugkd46tJ_9QzPENX:-O8a4aLJ28UHaJv0QxPz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/63333e484c46135c1dd6d5215694662d985b137a/crates/blockifier/src/execution/contract_class.rs#L95)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This is using the wrong `try_from`. Befoe this PR the `try_from` was the version that took ownership.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 436 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O8_x9pZ1x1mF1CXGnFt:-O8a4a546AnlB0X4L3I5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/63333e484c46135c1dd6d5215694662d985b137a/crates/blockifier/src/execution/contract_class.rs#L436)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Again - this is using the wrong try_from.

Let us split this into two PRs.
The first one is about adding `RawContractClass` (i.e., `starknet_api::contract_class::ContractClass`).
</blockquote></details>

Done.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1117)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 79 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O8_uxTL3GW4qOvaOZTz:-O8aCUTl-CLAZEWXiH0V:bsatr1b) ([raw file](https://github.com/starkware-libs/sequencer/blob/63333e484c46135c1dd6d5215694662d985b137a/crates/blockifier/src/execution/contract_class.rs#L79)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It is currently only used in the gateway. I prefer to be consistent with cairo 1. Why are we so against cloning? 
Changed.
</blockquote></details>

Oh, when the gateway is used in the centralized setting, it will indeed perform this conversion by ref on the stateful-validator stage.
So we *do* want to make this conversion by ref (and you want to delete it anyway in the next PR).

Clones are a bad habit, but in this case, they will not often happen (Cairo 0 not happens often). Let us clone.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1117)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @meship-starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 79 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-O8_uxTL3GW4qOvaOZTz:-O8aH3XYBt73VO_0Y643:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/63333e484c46135c1dd6d5215694662d985b137a/crates/blockifier/src/execution/contract_class.rs#L79)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Oh, when the gateway is used in the centralized setting, it will indeed perform this conversion by ref on the stateful-validator stage.
So we *do* want to make this conversion by ref (and you want to delete it anyway in the next PR).

Clones are a bad habit, but in this case, they will not often happen (Cairo 0 not happens often). Let us clone.
</blockquote></details>

Done.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1117#-:-O8aNzh-EvryrWA1K-oG:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @meship-starkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1117)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Pull request merged**
