### PR TITLE
test(starknet_integration_tests): test commit blocks by running multiple heights

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Comment by yair-starkware** [comment]
* **#2242** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2242?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2242?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2242)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @dan-starkware)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2242#-OCTCdZdEZBKytLoN8o5:-OCbnfg69081QNP3zcD0:b-kyd04) ([raw file](https://github.com/starkware-libs/sequencer/blob/37b311719118d37f6f526040b839438ac37f4853/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L37)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

`First` and `initial` mean the same, but they are different here, so it's a bit confusing. WDYT of this?
Also, the last height is only used for the iterator, so it is better to initialize it as it will be used.

Another option is `const END_HEIGHT: BlockNumber = BlockNumber(3);` Or you could implement for BlockNumber `fn iter_up(usize)`.

Any of these is fine IMO.
</blockquote></details>

Changed the variables, WDYT?
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2242#-OCTGY8c0WA0sfeP3NqH:-OCboCRlBNBdzLU4wdDE:b-z4vf1r) ([raw file](https://github.com/starkware-libs/sequencer/blob/37b311719118d37f6f526040b839438ac37f4853/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L43)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Did you make sure the txs are successful in the second block also? It must be checked manually once in order for us to "trust" this block hash.
</blockquote></details>

I didn't.
What do you regard as a sufficient check? I need to calc the `StateDiff` imposed by the test txs, and calculate its `StateDiffCommitment`.
I think it is not in the scope of the e2e test to validate these calculations.
Perhaps it doesn't need to check the `ContentId` at all, just the tx hashes.
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2242#-OCTGPVIAxvFVe3jmeD6:-OCbnuEk6P4Mlebtm16a:bzhix5d) ([raw file](https://github.com/starkware-libs/sequencer/blob/37b311719118d37f6f526040b839438ac37f4853/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L38)):*
> ```XML
>     let first_height = INITIAL_HEIGHT.unchecked_next();
>     let last_height = first_height.unchecked_next();
>     let expected_content_ids = [
> ```

I don't know why they convert to `BlockHash` in the consensus, that's a mistake IMO.
`ContentId` is the correct term.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2242)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2242#-OCTCdZdEZBKytLoN8o5:-OCclLCJBC89dAzJNkeI:b-vs1pr4) ([raw file](https://github.com/starkware-libs/sequencer/blob/37b311719118d37f6f526040b839438ac37f4853/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L37)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Changed the variables, WDYT?
</blockquote></details>

Looks good.
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2242#-OCTGY8c0WA0sfeP3NqH:-OCckqM3D-BJHz2npGG2:b-1jgw1s) ([raw file](https://github.com/starkware-libs/sequencer/blob/37b311719118d37f6f526040b839438ac37f4853/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L43)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I didn't.
What do you regard as a sufficient check? I need to calc the `StateDiff` imposed by the test txs, and calculate its `StateDiffCommitment`.
I think it is not in the scope of the e2e test to validate these calculations.
Perhaps it doesn't need to check the `ContentId` at all, just the tx hashes.
</blockquote></details>

I meant just to check in the logs that the 3 txs in the iteration go into that second block.
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2242#-OCcltUT6aqObNoruv9h:-OCcltUT6aqObNoruv9i:ba63q2x) ([raw file](https://github.com/starkware-libs/sequencer/blob/e72dca5a36ebbacf3e81744b9bc5c85244893374/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L50)):*
> ```XML
>     for (height, expected_content_id) in
>         next_height.iter_up_to(LAST_HEIGHT.unchecked_next()).zip(expected_content_ids.iter())
>     {
> ```

Check out `zip_eq` from iter_tools. I think you should use it here (and in general).



_Suggestion:_
```XML
    for (height, expected_content_id) in
        next_height.iter_up_to(LAST_HEIGHT).zip(expected_content_ids.iter())
    {
```

**Review by alonh5 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2242)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2242#-OCTGY8c0WA0sfeP3NqH:-OCh2Gqx2blT_qUZGoH-:b1v6ytq) ([raw file](https://github.com/starkware-libs/sequencer/blob/37b311719118d37f6f526040b839438ac37f4853/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L43)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I meant just to check in the logs that the 3 txs in the iteration go into that second block.
</blockquote></details>

in the second* iteration

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2242)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @dan-starkware)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2242#-OCTGY8c0WA0sfeP3NqH:-OCgSUfcCNEleix9YHVd:b-38lp1z) ([raw file](https://github.com/starkware-libs/sequencer/blob/37b311719118d37f6f526040b839438ac37f4853/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L43)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I meant just to check in the logs that the 3 txs in the iteration go into that second block.
</blockquote></details>

Oh yes I checked this
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2242#-OCcltUT6aqObNoruv9h:-OD0YqHpBBn6L_iEy3CY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e72dca5a36ebbacf3e81744b9bc5c85244893374/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L50)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Check out `zip_eq` from iter_tools. I think you should use it here (and in general).
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2242)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r4, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2242)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
