### PR TITLE
chore(ci): delete redundant CI job

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/553)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/553)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @elintul and @noaov1)

___
*[`.github/workflows/blockifier_post-merge.yml` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/553#-O4soubs7AfkPgOhC-Jr:-O4soubs7AfkPgOhC-Js:b-wfmero) ([raw file](https://github.com/starkware-libs/sequencer/blob/df672bc5a755e00cf30232464de6268082e78904/.github/workflows/blockifier_post-merge.yml#L1)):*
> ```YAML
> name: Blockifier-Post-Merge
> ```

If we remove post-merge we're gonna have to remove the post-merge badge [from the README](https://github.com/starkware-libs/sequencer/blob/cd3107459a81e77b5888718cc8d82ea9b1a068b7/docs/blockifier/README.md#L14), which typically describes the post-merge status.

This is another possible indicator not to remove a post-merge job completely, as this badge is quite common on GH repos

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/553)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @elintul and @noaov1)

___
*[`.github/workflows/blockifier_post-merge.yml` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/553#-O4soubs7AfkPgOhC-Jr:-O4t3s732JglBWj-O1ZD:b-xa5zbh) ([raw file](https://github.com/starkware-libs/sequencer/blob/df672bc5a755e00cf30232464de6268082e78904/.github/workflows/blockifier_post-merge.yml#L1)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

If we remove post-merge we're gonna have to remove the post-merge badge [from the README](https://github.com/starkware-libs/sequencer/blob/cd3107459a81e77b5888718cc8d82ea9b1a068b7/docs/blockifier/README.md#L14), which typically describes the post-merge status.

This is another possible indicator not to remove a post-merge job completely, as this badge is quite common on GH repos
</blockquote></details>

our main CI is also triggered on push to `main*`, so we have post-merge coverage... what needs to be done to get the badge?

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/553)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @noaov1)

___
*[`.github/workflows/blockifier_post-merge.yml` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/553#-O4soubs7AfkPgOhC-Jr:-O5NH_-xCJhw0vHi34ev:b-l4f8ls) ([raw file](https://github.com/starkware-libs/sequencer/blob/df672bc5a755e00cf30232464de6268082e78904/.github/workflows/blockifier_post-merge.yml#L1)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

our main CI is also triggered on push to `main*`, so we have post-merge coverage... what needs to be done to get the badge?
</blockquote></details>

Hmm we can change the url in the badge to point to the main-ci post-merge job you mentioned, but maybe the's more relevant as a badge in the whole monorepo README, rather than on a specific crate? not sure.
Either one is OK I think

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/553)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @noaov1)

___
*[`.github/workflows/blockifier_post-merge.yml` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/553#-O4soubs7AfkPgOhC-Jr:-O5N_7kODNuOyryau-TW:biaj0p2) ([raw file](https://github.com/starkware-libs/sequencer/blob/df672bc5a755e00cf30232464de6268082e78904/.github/workflows/blockifier_post-merge.yml#L1)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Hmm we can change the url in the badge to point to the main-ci post-merge job you mentioned, but maybe the's more relevant as a badge in the whole monorepo README, rather than on a specific crate? not sure.
Either one is OK I think
</blockquote></details>

putting a pin in this until next week's sync, we'll decide what "post merge" means in the sequencer era and go from there...
for now we can ignore post-merge failures IMO

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/553)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @noaov1)

___
*[`.github/workflows/blockifier_post-merge.yml` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/553#-O4soubs7AfkPgOhC-Jr:-O5RrpnSDbTb6wwDKL9t:b-krzsmn) ([raw file](https://github.com/starkware-libs/sequencer/blob/df672bc5a755e00cf30232464de6268082e78904/.github/workflows/blockifier_post-merge.yml#L1)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

putting a pin in this until next week's sync, we'll decide what "post merge" means in the sequencer era and go from there...
for now we can ignore post-merge failures IMO
</blockquote></details>

sababa

**Pull request closed without merging**
