### PR TITLE
chore(blockifier): check max gas amount covers minimal estimated gas amount

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/771)

### CODE REVIEW

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/771)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 243 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/771#-O7dYNGpAb5cK04rK_0G:-O7dYNGpAb5cK04rK_0H:b-mgz44f) ([raw file](https://github.com/starkware-libs/sequencer/blob/f05ccaa3101fe6c151d762140acd288e36a7086e/crates/blockifier/src/transaction/account_transaction.rs#L243)):*
> ```XML
>         )?;
>         let minimal_l1_gas_amount: u64 = match &tx_context.get_gas_vector_computation_mode() {
>             All => minimal_gas_amount_vector
> ```

The `All` and `NoL2Gas` branches needs to be swapped
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 244 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/771#-O7dY2egC3xhCgHV9VHc:-O7dY2egC3xhCgHV9VHd:bxe836i) ([raw file](https://github.com/starkware-libs/sequencer/blob/f05ccaa3101fe6c151d762140acd288e36a7086e/crates/blockifier/src/transaction/account_transaction.rs#L244)):*
> ```XML
>         let minimal_l1_gas_amount: u64 = match &tx_context.get_gas_vector_computation_mode() {
>             All => minimal_gas_amount_vector
>                 .to_discounted_l1_gas(tx_context)
> ```

Seems like this should be run only if use_kzg==True, and otherwise we should have the no discount computation of 
`l1_gas*l1_price + data_gas*16*l1_price`
Please add a todo to fix this (I think the `to_discounted_l1_gas` should have this if kzg logic in it)



_Code quote:_
```XML
              .to_discounted_l1_gas(tx_context)
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 246 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/771#-O7d_Xy16Oy_F8xwOPRk:-O7d_Xy16Oy_F8xwOPRl:b-bgsgxd) ([raw file](https://github.com/starkware-libs/sequencer/blob/f05ccaa3101fe6c151d762140acd288e36a7086e/crates/blockifier/src/transaction/account_transaction.rs#L246)):*
> ```XML
>                 .to_discounted_l1_gas(tx_context)
>                 .try_into()
>                 .expect("Failed to convert u128 to u64."),
> ```

Why do we expect this conversion to always succeed? You've removed the TODO Ori had on this message, but it's important to doc this and explain this in the error message.



_Suggestion:_
```XML
"Failed to convert u128 to u64."
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 331 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/771#-O7daxx_5P9t2R4su_gc:-O7daxx_5P9t2R4su_gd:b-ckk5k2) ([raw file](https://github.com/starkware-libs/sequencer/blob/f05ccaa3101fe6c151d762140acd288e36a7086e/crates/blockifier/src/transaction/account_transaction.rs#L331)):*
> ```XML
>                             })?;
>                         }
>                     }
> ```

I think it will be much more readable if the match won't check the actual conditions for the price and amounts (which are the same for both branches), but will only assign the prices and amounts to a list of tuples, the L1 branch will have a list of a single tuple, and the ALL branch will have 3 tuples.



_Suggestion:_
```XML
                    for (resource, max_gas_price, actual_gas_price) in resource_tuple
                     {
                        // TODO(Aner): refactor to return all prices that are too low.
                        if max_gas_price < actual_gas_price {
                            return Err(TransactionFeeError::MaxGasPriceTooLow {
                                resource,
                                max_gas_price,
                                actual_gas_price,
                            })?;
                        }
                    }
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/771)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 244 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/771#-O7dY2egC3xhCgHV9VHc:-O7df3QrBnDGBSk5MdN4:b4asdxq) ([raw file](https://github.com/starkware-libs/sequencer/blob/f05ccaa3101fe6c151d762140acd288e36a7086e/crates/blockifier/src/transaction/account_transaction.rs#L244)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Seems like this should be run only if use_kzg==True, and otherwise we should have the no discount computation of 
`l1_gas*l1_price + data_gas*16*l1_price`
Please add a todo to fix this (I think the `to_discounted_l1_gas` should have this if kzg logic in it)
</blockquote></details>

Updating after discussion: data_gas is 0 if kzg==False, so the "discount" function does nothing. Needs to doc this better here or there.

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/771)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 243 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/771#-O7dYNGpAb5cK04rK_0G:-O7de9vi58DDX3kuQz6l:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f05ccaa3101fe6c151d762140acd288e36a7086e/crates/blockifier/src/transaction/account_transaction.rs#L243)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

The `All` and `NoL2Gas` branches needs to be swapped
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 246 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/771#-O7d_Xy16Oy_F8xwOPRk:-O7dfnuQ7vX5MzyIr91j:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f05ccaa3101fe6c151d762140acd288e36a7086e/crates/blockifier/src/transaction/account_transaction.rs#L246)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Why do we expect this conversion to always succeed? You've removed the TODO Ori had on this message, but it's important to doc this and explain this in the error message.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 331 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/771#-O7daxx_5P9t2R4su_gc:-O7dmKl9E-JpC_wuRYF8:b6r53jj) ([raw file](https://github.com/starkware-libs/sequencer/blob/f05ccaa3101fe6c151d762140acd288e36a7086e/crates/blockifier/src/transaction/account_transaction.rs#L331)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I think it will be much more readable if the match won't check the actual conditions for the price and amounts (which are the same for both branches), but will only assign the prices and amounts to a list of tuples, the L1 branch will have a list of a single tuple, and the ALL branch will have 3 tuples.
</blockquote></details>

Done. Though I'm not a fan of this change.

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/771)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 331 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/771#-O7daxx_5P9t2R4su_gc:-O7hflyA7n-57dMsl-4C:b-kdebju) ([raw file](https://github.com/starkware-libs/sequencer/blob/f05ccaa3101fe6c151d762140acd288e36a7086e/crates/blockifier/src/transaction/account_transaction.rs#L331)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done. Though I'm not a fan of this change.
</blockquote></details>

Why? You can shorten the vec by adding the resource_bound instead of the amount and gas price.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 249 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/771#-O7hg6kx0q96asxafqZz:-O7hg6kx0q96asxafq_-:b4kbzlz) ([raw file](https://github.com/starkware-libs/sequencer/blob/bab4aae40b49e576ba46daf8f7c1d14f24640d93/crates/blockifier/src/transaction/account_transaction.rs#L249)):*
> ```XML
>             }
>             NoL2Gas => minimal_gas_amount_vector
>                 // When kzg_flag==false, then l1_data_gas==0, and this dicount function does nothing.
> ```

The comment in the function docstring is enough IMO
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 252 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/771#-O7hfxas4KmOHwdj6W3V:-O7hfxas4KmOHwdj6W3W:b-abthh3) ([raw file](https://github.com/starkware-libs/sequencer/blob/bab4aae40b49e576ba46daf8f7c1d14f24640d93/crates/blockifier/src/transaction/account_transaction.rs#L252)):*
> ```XML
>                 .to_discounted_l1_gas(tx_context)
>                 .try_into()
>                 // TODO(Ori, 1/2/2024): Write an indicative expect message explaining why the conversion works.
> ```

Add two of these todos below or remove this and add to the previous one "... here and below")
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 318 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/771#-O7hfgldDU5Cg9-o8UR3:-O7hfgle0hyPKft7IEWs:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/bab4aae40b49e576ba46daf8f7c1d14f24640d93/crates/blockifier/src/transaction/account_transaction.rs#L318)):*
> ```XML
>                 ) in resources_amount_tuple
>                 {
>                     // TODO(Aner): refactor to indicate both amount and price are to low.
> ```





_Suggestion:_
```XML
 refactor to indicate both amount and price are too low
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/771)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 252 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/771#-O7hfxas4KmOHwdj6W3V:-O7hiPZJ-YLzUzLrx9IP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bab4aae40b49e576ba46daf8f7c1d14f24640d93/crates/blockifier/src/transaction/account_transaction.rs#L252)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Add two of these todos below or remove this and add to the previous one "... here and below")
</blockquote></details>

Done.

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/771)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by TzahiTaub — APPROVED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/771)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
