### PR TITLE
fix(mempool): do not allow duplicate nonce if fee escalation if off

### PR DESCRIPTION
**Pull request by elintul**

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2064)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/starknet_mempool/src/mempool_test.rs` line 378 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2064#-OBe_lK5-oodThjbOLbB:-OBe_lK5-oodThjbOLbC:bwuz1f4) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd90460a7c1b8dbd7f9b2bd30c482a6a9f79346d/crates/starknet_mempool/src/mempool_test.rs#L378)):*
> ```XML
>         &mut mempool,
>         &invalid_input,
>         MempoolError::DuplicateNonce { address: contract_address!("0x0"), nonce: nonce!(0) },
> ```

This will become `NonceTooOld` in nonce abstraction PR, separated for minimal diff. in that PR.



_Code quote:_
```XML
DuplicateNonce
```

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2064#-:-OBtJWQv5cEZzXFYNDKI:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/starknet_mempool/src/mempool_test.rs` line 374 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2064#-OBtIki64Tm-nWmVpwkq:-OBtIki7E7Dqoiesmup9:b-d6153k) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd90460a7c1b8dbd7f9b2bd30c482a6a9f79346d/crates/starknet_mempool/src/mempool_test.rs#L374)):*
> ```XML
> 
>     // Test and assert: original transaction remains.
>     let invalid_input = add_tx_input!(tx_hash: 2, address: "0x0", tx_nonce: 0, account_nonce: 0);
> ```

It can be default values.



_Code quote:_
```XML
tx_hash: 2, address: "0x0", 
```
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 381 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2064#-OBtJ0K654bSNyaGILVo:-OBtJ0K70F8haKUZANW8:b7j83tk) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd90460a7c1b8dbd7f9b2bd30c482a6a9f79346d/crates/starknet_mempool/src/mempool_test.rs#L381)):*
> ```XML
>     );
> 
>     let invalid_input = add_tx_input!(tx_hash: 2, address: "0x0", tx_nonce: 1, account_nonce: 1);
> ```

Why it was changed to 1?



_Code quote:_
```XML
 account_nonce: 1
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2064)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/starknet_mempool/src/mempool_test.rs` line 374 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2064#-OBtIki64Tm-nWmVpwkq:-OBtWbZ99-SIYxh048_i:bp15ils) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd90460a7c1b8dbd7f9b2bd30c482a6a9f79346d/crates/starknet_mempool/src/mempool_test.rs#L374)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It can be default values.
</blockquote></details>

I don't think so, we use all values in the test.
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 381 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2064#-OBtJ0K654bSNyaGILVo:-OBtXEd-9qGxCDpX8jYH:brr30rn) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd90460a7c1b8dbd7f9b2bd30c482a6a9f79346d/crates/starknet_mempool/src/mempool_test.rs#L381)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why it was changed to 1?
</blockquote></details>

Right, no need. Done!

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2064#-:-OBtftcJ36TROrBnERqk:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2064)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/starknet_mempool/src/mempool.rs` line 266 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2064#-OBtwuCH8JS6UOszD_aH:-OBtwuCIDDNlC7BYVGaU:b-z6msf7) ([raw file](https://github.com/starkware-libs/sequencer/blob/768c3ec4bc86bde42fbd78d9f65def908d81b43b/crates/starknet_mempool/src/mempool.rs#L266)):*
> ```XML
>         if !self.config.enable_fee_escalation {
>             if self.tx_pool.get_by_address_and_nonce(address, nonce).is_some() {
>                 return Err(MempoolError::DuplicateNonce { address, nonce });
> ```

I think it's better to add this check-in `validate_incoming_tx_nonce.` I added it in #1999

**Pull request merged**
