### PR TITLE
refactor: refactor the stateful tx validator to get executable tx as input

### PR DESCRIPTION
**Pull request by ArniStarkware**
In this PR we change the inputs for the `run_validate` method of the stateful validator. This also streamlines `process+tx`.

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/519)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/519?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#520** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/520?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#519** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/519?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#518** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/518?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#517** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/517?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#516** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/516?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/519)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @MohammadNassar1, and @yair-starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/519#-O4o3ddT3-AWaKrX6ohG:-O4o3ddT3-AWaKrX6ohH:b7yx5ix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc0e749fd941b1a82cba11b4f6ed09f9e060a16a/crates/gateway/src/stateful_transaction_validator.rs#L77)):*
> ```XML
>         mut validator: V,
>     ) -> StatefulTransactionValidatorResult<ValidateInfo> {
>         let account_tx = AccountTransaction::try_from(executable_tx.clone()).map_err(|error| {
> ```

Why the clone here? Can't `AccountTransaction::try_from` get a reference?



_Code quote:_
```XML
executable_tx.clone()
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/519#-O4o3u1eDx9rTAJjqehk:-O4o3u1eDx9rTAJjqehl:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc0e749fd941b1a82cba11b4f6ed09f9e060a16a/crates/gateway/src/stateful_transaction_validator.rs#L78)):*
> ```XML
>     ) -> StatefulTransactionValidatorResult<ValidateInfo> {
>         let account_tx = AccountTransaction::try_from(executable_tx.clone()).map_err(|error| {
>             error!("Failed to executable transaction into account transaction: {}", error);
> ```





_Suggestion:_
```XML
Failed to convert executable transaction into account transaction: {}
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/519#-O4o4ZTk5oY1pD0h15YL:-O4o4ZTk5oY1pD0h15YM:bs5h48q) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc0e749fd941b1a82cba11b4f6ed09f9e060a16a/crates/gateway/src/stateful_transaction_validator_test.rs#L81)):*
> ```XML
> #[case::invalid_tx(invoke_tx(CairoVersion::Cairo1), Err(STATEFUL_VALIDATOR_FEE_ERROR))]
> fn test_stateful_tx_validator(
>     #[case] external_tx: RpcTransaction,
> ```

I think the test should start with an executable tx, and not do any conversion, and especially not compile anything.



_Code quote:_
```XML
#[case] external_tx: RpcTransaction,
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/stateful_transaction_validator.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/519#-O4o3u1eDx9rTAJjqehk:-O4oD6BU0PbQ97P71-zR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc0e749fd941b1a82cba11b4f6ed09f9e060a16a/crates/gateway/src/stateful_transaction_validator.rs#L78)):*
> ```XML
>     ) -> StatefulTransactionValidatorResult<ValidateInfo> {
>         let account_tx = AccountTransaction::try_from(executable_tx.clone()).map_err(|error| {
>             error!("Failed to executable transaction into account transaction: {}", error);
> ```

Done.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/519)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @MohammadNassar1, and @yair-starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/519#-O4o3ddT3-AWaKrX6ohG:-O5NwAzABIC4eCDf9A0_:bie9p1g) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc0e749fd941b1a82cba11b4f6ed09f9e060a16a/crates/gateway/src/stateful_transaction_validator.rs#L77)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why the clone here? Can't `AccountTransaction::try_from` get a reference?
</blockquote></details>

On one hand, it makes sense that the convertor function will take ownership of the struct. This is both the "morally correct behavior" and efficient (no need to clone the members again when creating the new struct).
On the other hand, here we want to pass the `ExecutableTransaction` by ref - as the validator should validate without affecting the original struct. We can write a converter into `AccountTransaction` that would be more efficient in that case (the compilation Sierra -> Casm can be optimized). It is addressed in #604.
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/519#-O4o4ZTk5oY1pD0h15YL:-O6Gn20g6z2qIbK--lIX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc0e749fd941b1a82cba11b4f6ed09f9e060a16a/crates/gateway/src/stateful_transaction_validator_test.rs#L81)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think the test should start with an executable tx, and not do any conversion, and especially not compile anything.
</blockquote></details>

Done.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3, 1 of 5 files at r4, 2 of 6 files at r7, 7 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/519)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @ayeletstarkware, @MohammadNassar1, and @yair-starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 161 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/519#-O6L3zO0AGOe3gjtL6Dg:-O6L3zO13SGYbm-BTYuQ:brelc3i) ([raw file](https://github.com/starkware-libs/sequencer/blob/f5567f79664b9995155865ca6a0411489e13c647/crates/gateway/src/gateway_test.rs#L161)):*
> ```XML
> }
> 
> // TODO(Arni): Remove this function. Replace with a function that take ownership of RpcTransaction.
> ```

Can you explain?



_Code quote:_
```XML
Replace with a function that take ownership of RpcTransaction.
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/519)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @dafnamatsry, @MohammadNassar1, and @yair-starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 161 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/519#-O6L3zO0AGOe3gjtL6Dg:-O6Lcu6Q6CSQdYVJ9KO0:b-i1e1u9) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ac6eb34cfa3f02e0ec4c91b68bcdc1e0ee4445c/crates/gateway/src/gateway_test.rs#L161)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can you explain?
</blockquote></details>

No. I would rather delete this function :)

This was a test util that should be deprecated.
Let us update the test.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway_test.rs` line 161 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/519#-O6L3zO0AGOe3gjtL6Dg:-O6MctBc0hqIdN3Sjr6k:bjnpaxq) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ac6eb34cfa3f02e0ec4c91b68bcdc1e0ee4445c/crates/gateway/src/gateway_test.rs#L161)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

No. I would rather delete this function :)

This was a test util that should be deprecated.
Let us update the test.
</blockquote></details>

The original thread was about a test util called `rpc_tx_to_account_tx` that first appeared in `r4` of this review session.
A new design of the code makes this code obsolete.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r7, 3 of 8 files at r8, 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/519#-:-O6ooAV_BamShQpOCAMS:bnfp4nl)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @dafnamatsry, and @MohammadNassar1)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/519)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/519#-O6ooAmq484dWCfXJL5t:-O6ooAmrAAvMO8n897Bp:b-zb5ish) (no related file):*
In this PR we change the 

___

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/519)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @dafnamatsry, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/519#-O6oo_KJAs33YbyFJ5z3:-O6oo_KJAs33YbyFJ5z4:bvooakq) (no related file):*
The original goal of this PR was to refactor the stateful tx validator so that it receives an executable transaction as input.
Another goal achieved is that the proper executable transaction is now used as the mempool input. This change occurred to address issues with the gateway_test: `test_add_tx`. In the meantime we also cleaned some test utils for this test and for the stateful validator test.

___

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r12, 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/519#-:-O72rJJh9rXAkGVckLae:bnfp4nl)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @ayeletstarkware and @MohammadNassar1)

**Review by dafnamatsry — COMMENTED** [review]
> Reviewed 1 of 7 files at r14, 1 of 6 files at r16, 5 of 5 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/519)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @ayeletstarkware and @MohammadNassar1)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/519#-:-O783R4G27vyB292B9C7:bnfp4nl)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @ayeletstarkware and @MohammadNassar1)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/519)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @MohammadNassar1)

**Pull request merged**
