### PR TITLE
chore: convert SequencerNodeClients members

### PR DESCRIPTION
**Pull request by nadin-Starkware**
commit-id:2ca0a7a3

---

**Stack**:
- #2047
- #2041
- #2040
- #2035
- #2034
- #2033
- #2032
- #2030 ⬅
- #2029
- #2028

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2030)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/starknet_sequencer_node/src/clients.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2030#-OBgQcBF1KXFfzAXWNl7:-OBgQcBF1KXFfzAXWNl8:b-ycsgpm) ([raw file](https://github.com/starkware-libs/sequencer/blob/a53a1187e86cc73ed6d2defe48fa55d9019ff3bb/crates/starknet_sequencer_node/src/clients.rs#L38)):*
> ```XML
> 
> pub struct SequencerNodeClients {
>     batcher_client: Option<Client<BatcherRequest, BatcherResponse>>,
> ```

Do we need the wrapping `Option` anymore?



_Code quote:_
```XML
Option<Client<BatcherRequest, BatcherResponse>>,
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2030)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sequencer_node/src/clients.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2030#-OBgQcBF1KXFfzAXWNl7:-OBtUoEOEZi9DPJCd8Ha:b-sonz7t) ([raw file](https://github.com/starkware-libs/sequencer/blob/a53a1187e86cc73ed6d2defe48fa55d9019ff3bb/crates/starknet_sequencer_node/src/clients.rs#L38)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Do we need the wrapping `Option` anymore?
</blockquote></details>

Yes, the create_client macro returns an Option<Client>

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2030#-:-OBu6mrE0ICHUHOVBxKK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Comment by nadin-Starkware** [comment]
✓ Commit merged in pull request [#2041](https://github.com/starkware-libs/sequencer/pull/2041)

**Pull request closed without merging**
