### PR TITLE
refactor(blockifier): remove execution_resources arg

### PR DESCRIPTION
**Pull request by Yoni-Starkware**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2189)* status: all files reviewed, 6 unresolved discussions (waiting on @TzahiTaub and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/call_info.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-OC51IbmEvihagi4ReOH:-OC51IbmEvihagi4ReOI:blef23y) ([raw file](https://github.com/starkware-libs/sequencer/blob/321d0edad70f3633c885f66e691ae1cc086ff1a1/crates/blockifier/src/execution/call_info.rs#L201)):*
> ```XML
> 
>         ExecutionSummary {
>             charged_resources: self.charged_resources.clone(),
> ```

why is this field precomputed, and not computed in `summarize` like everything else?



_Code quote:_
```XML
charged_resources: self.charged_resources.clone(),
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-OC50A4E4IydvjfC3m_V:-OC50A4E4IydvjfC3m_W:b-f1g55h) ([raw file](https://github.com/starkware-libs/sequencer/blob/321d0edad70f3633c885f66e691ae1cc086ff1a1/crates/blockifier/src/execution/native/entry_point_execution.rs#L94)):*
> ```XML
>         },
>         charged_resources: ChargedResources {
>             // TODO(Yoni): fix similarly to the VM - share that code.
> ```

can you be more specific? assume people read this without context



_Code quote:_
```XML
// TODO(Yoni): fix similarly to the VM - share that code.
```
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-OC50npe-9trTY7OIJv8:-OC50npe-9trTY7OIJv9:b-dfss5g) ([raw file](https://github.com/starkware-libs/sequencer/blob/321d0edad70f3633c885f66e691ae1cc086ff1a1/crates/blockifier/src/transaction/objects_test.rs#L195)):*
> ```XML
> 
>     let expected_summary = ExecutionSummary {
>         charged_resources: ChargedResources::default(),
> ```

why do we expect zero charged resources in this test...? seems like it should be positive



_Code quote:_
```XML
charged_resources: ChargedResources::default(),
```
___
*[`crates/blockifier/src/fee/receipt.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-OC50NRk4VbRczfUIqK1:-OC50NRk4VbRczfUIqK2:b-e6h9v5) ([raw file](https://github.com/starkware-libs/sequencer/blob/321d0edad70f3633c885f66e691ae1cc086ff1a1/crates/blockifier/src/fee/receipt.rs#L62)):*
> ```XML
>             reverted_steps,
>         } = tx_receipt_params;
>         let charged_resources = execution_summary_without_fee_transfer.charged_resources.clone();
> ```

don't we add fee transfer overhead when we charge a fee? isn't this a breaking change?



_Code quote:_
```XML
let charged_resources = execution_summary_without_fee_transfer.charged_resources.clone();
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 443 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-OC500bH-7-BjB7ZLA2z:-OC500bH-7-BjB7ZLA3-:brh4ihm) ([raw file](https://github.com/starkware-libs/sequencer/blob/321d0edad70f3633c885f66e691ae1cc086ff1a1/crates/blockifier/src/execution/entry_point_execution.rs#L443)):*
> ```XML
>             acc
>         },
>     );
> ```

same remark as above



_Code quote:_
```XML
    let charged_resources = syscall_handler.inner_calls.iter().fold(
        charged_resources_without_inner_calls,
        |mut acc, inner_call| {
            acc += &inner_call.charged_resources;
            acc
        },
    );
```
___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 261 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-OC5-P_A0xaZRN7UpDBd:-OC5-P_A0xaZRN7UpDBe:b-vdlf8n) ([raw file](https://github.com/starkware-libs/sequencer/blob/321d0edad70f3633c885f66e691ae1cc086ff1a1/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L261)):*
> ```XML
>             acc
>         },
>     );
> ```

isn't there a `derive_more::Sum` you can annotate resource with?
or, make this change?



_Suggestion:_
```XML
    let full_vm_resources = vm_resources_without_inner_calls + syscall_handler
        .inner_calls
        .iter()
        .map(|inner_call| inner_call.charged_resources.vm_resources)
        .sum();
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2189)* status: 13 of 21 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/execution/call_info.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-OC51IbmEvihagi4ReOH:-OC53Ue63AQMhG6Oy1oj:b-r5a2mj) ([raw file](https://github.com/starkware-libs/sequencer/blob/321d0edad70f3633c885f66e691ae1cc086ff1a1/crates/blockifier/src/execution/call_info.rs#L201)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this field precomputed, and not computed in `summarize` like everything else?
</blockquote></details>

The resources include inner calls. Events, message, etc - don't.
___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 261 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-OC5-P_A0xaZRN7UpDBd:-OC53oge8ITpJWwtcHQx:b-4yn66j) ([raw file](https://github.com/starkware-libs/sequencer/blob/321d0edad70f3633c885f66e691ae1cc086ff1a1/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L261)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

isn't there a `derive_more::Sum` you can annotate resource with?
or, make this change?
</blockquote></details>

ExecutionResources is not part of our repo, so I can't impl this trait.
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 443 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-OC500bH-7-BjB7ZLA2z:-OC54-v18O_lXFeSHQau:bb73xfv) ([raw file](https://github.com/starkware-libs/sequencer/blob/321d0edad70f3633c885f66e691ae1cc086ff1a1/crates/blockifier/src/execution/entry_point_execution.rs#L443)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

same remark as above
</blockquote></details>

Same
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-OC50A4E4IydvjfC3m_V:-OC54ad39Q6olvKCxEUv:b-30v8qi) ([raw file](https://github.com/starkware-libs/sequencer/blob/321d0edad70f3633c885f66e691ae1cc086ff1a1/crates/blockifier/src/execution/native/entry_point_execution.rs#L94)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you be more specific? assume people read this without context
</blockquote></details>

Easier to fix this. Done
___
*[`crates/blockifier/src/fee/receipt.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-OC50NRk4VbRczfUIqK1:-OC546aP2s3FixVO14Dz:bgn6by9) ([raw file](https://github.com/starkware-libs/sequencer/blob/321d0edad70f3633c885f66e691ae1cc086ff1a1/crates/blockifier/src/fee/receipt.rs#L62)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't we add fee transfer overhead when we charge a fee? isn't this a breaking change?
</blockquote></details>

Didn't change anything. 
The fee transfer overhead (and others) is part of the transaction overhead, which is added later in this func.
___
*[`crates/blockifier/src/transaction/objects_test.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-OC50npe-9trTY7OIJv8:-OC5A79o7_ddoaFShqkn:biosiz9) ([raw file](https://github.com/starkware-libs/sequencer/blob/321d0edad70f3633c885f66e691ae1cc086ff1a1/crates/blockifier/src/transaction/objects_test.rs#L195)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do we expect zero charged resources in this test...? seems like it should be positive
</blockquote></details>

No, need to add it to the test. Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2189)* status: all files reviewed, 4 unresolved discussions (waiting on @TzahiTaub and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-OC7UhfBETWGn8gLZUmC:-OC7UhfBETWGn8gLZUmD:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ea6d491eeae015768e07f0b485c321975b20d55/crates/blockifier/src/execution/native/entry_point_execution.rs#L90)):*
> ```XML
>     };
>     let mut charged_resources = charged_resources_without_inner_calls;
>     charged_resources += &CallInfo::summarize_charged_resources(syscall_handler.inner_calls.iter());
> ```





_Suggestion:_
```XML
    let charged_resources = charged_resources_without_inner_calls +
        &CallInfo::summarize_charged_resources(syscall_handler.inner_calls.iter());
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 438 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-OC7U_1Y49GsGsur5VM9:-OC7U_1Y49GsGsur5VMA:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ea6d491eeae015768e07f0b485c321975b20d55/crates/blockifier/src/execution/entry_point_execution.rs#L438)):*
> ```XML
>     };
>     let mut charged_resources = charged_resources_without_inner_calls;
>     charged_resources += &CallInfo::summarize_charged_resources(syscall_handler.inner_calls.iter());
> ```





_Suggestion:_
```XML
    let charged_resources = charged_resources_without_inner_calls +
        &CallInfo::summarize_charged_resources(syscall_handler.inner_calls.iter());
```
___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 262 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-OC7USUh8JMIatlYSCRl:-OC7USUh8JMIatlYSCRm:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ea6d491eeae015768e07f0b485c321975b20d55/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L262)):*
> ```XML
>     };
>     let mut charged_resources = charged_resources_without_inner_calls;
>     charged_resources += &CallInfo::summarize_charged_resources(syscall_handler.inner_calls.iter());
> ```





_Suggestion:_
```XML
    let charged_resources = charged_resources_without_inner_calls +
        &CallInfo::summarize_charged_resources(syscall_handler.inner_calls.iter());
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 222 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-OC7VuGACXxt4LFqT6vI:-OC7VuGB63Ub1X4LRwdu:b-xromlq) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ea6d491eeae015768e07f0b485c321975b20d55/crates/blockifier/src/execution/call_info.rs#L222)):*
> ```XML
>     ) -> ChargedResources {
>         // Note: the charged resourses of a call contains the inner call resources, unlike other
>         // fields such as events and messages,
> ```

is it possible to change this, so that charged resources behave like other fields?
it's still confusing - i.e. why would you need a summarize method like this, for a field that "already includes inner calls"?



_Code quote:_
```XML
        // Note: the charged resourses of a call contains the inner call resources, unlike other
        // fields such as events and messages,
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 0 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-OC7UqUy7O9WuYpuvw5i:-OC7UqUz43AuVEzkG-ab:b-mqv3pn) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ea6d491eeae015768e07f0b485c321975b20d55/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L0)):*
why are the native values now zero? this seems like an error

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-:-OC8gdes7j8RjCyV0Ttq:bnfp4nl)* status: 21 of 22 files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2189)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub and @Yoni-Starkware)

___
*[`crates/blockifier/cairo_native` line 1 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-OC8yITh8_eFPE2FNizp:-OC8yITh8_eFPE2FNizq:b-woiu20) ([raw file](https://github.com/starkware-libs/sequencer/blob/267026a0a6fd3a94104220ac71b9b7a845b0a2e3/crates/blockifier/cairo_native#L1)):*
> ```
> Subproject commit 0bc6f408884370e4fbbf421c4e8e109911c3d73e
> ```

this shouldn't be here



_Code quote:_
```
Subproject commit 0bc6f408884370e4fbbf421c4e8e109911c3d73e
```

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2189)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/cairo_native` line 1 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2189#-OC8yITh8_eFPE2FNizp:-OC8zP5u2nAGI5o-AFJX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/267026a0a6fd3a94104220ac71b9b7a845b0a2e3/crates/blockifier/cairo_native#L1)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this shouldn't be here
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2189)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
