### PR TITLE
refactor(mempool): remove redundant add-tx test

### PR DESCRIPTION
**Pull request by MohammadNassar1**
The test is already covered `test_add_tx_delete_tx_with_lower_nonce_than_account_nonce` test.

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1617)* status: 0 of 1 files reviewed, 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1617#-OAIXQLw9BFoN1C4MSJI:-OAIXQLw9BFoN1C4MSJJ:bl1qpwc) (no related file):*
The test is already covered in `test_add_tx_delete_tx_with_lower_nonce_than_account_nonce`.
The test name is informative

___
___
*[`crates/mempool/src/mempool_test.rs` line 447 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1617#-OAIX0DH7E4IAcURbnVN:-OAIX0DH7E4IAcURbnVO:br71s39) ([raw file](https://github.com/starkware-libs/sequencer/blob/a52ecf93747ae84bcda3e00490a7f902fbe4d5d0/crates/mempool/src/mempool_test.rs#L447)):*
> ```XML
>         .build();
>     expected_mempool_content.assert_eq(&mempool);
> }
> ```

The test is already covered here.
Both tests check the same scenario.
This test name is more informative.



_Code quote:_
```XML
fn test_add_tx_delete_tx_with_lower_nonce_than_account_nonce() {
    // Setup.
    let tx_nonce_0_account_nonce_0 =
        add_tx_input!(tx_hash: 1, address: "0x0", tx_nonce: 0, account_nonce: 0);
    let tx_nonce_1_account_nonce_1 =
        add_tx_input!(tx_hash: 2, address: "0x0", tx_nonce: 1, account_nonce: 1);

    let queue_txs = [TransactionReference::new(&tx_nonce_0_account_nonce_0.tx)];
    let pool_txs = [tx_nonce_0_account_nonce_0.tx];
    let mut mempool = MempoolContentBuilder::new()
        .with_pool(pool_txs)
        .with_priority_queue(queue_txs)
        .build_into_mempool();

    // Test.
    add_tx(&mut mempool, &tx_nonce_1_account_nonce_1);

    // Assert the transaction with the lower nonce is removed.
    let expected_queue_txs = [TransactionReference::new(&tx_nonce_1_account_nonce_1.tx)];
    let expected_pool_txs = [tx_nonce_1_account_nonce_1.tx];
    let expected_mempool_content = MempoolContentBuilder::new()
        .with_pool(expected_pool_txs)
        .with_priority_queue(expected_queue_txs)
        .build();
    expected_mempool_content.assert_eq(&mempool);
}
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1617)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 422 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1617#-OAIbl0n07wFTnzwaGTV:-OAIbl0n07wFTnzwaGTW:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/a52ecf93747ae84bcda3e00490a7f902fbe4d5d0/crates/mempool/src/mempool_test.rs#L422)):*
> ```XML
> 
> #[rstest]
> fn test_add_tx_delete_tx_with_lower_nonce_than_account_nonce() {
> ```





_Suggestion:_
```XML
deletes
```
___
*[`crates/mempool/src/mempool_test.rs` line 447 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1617#-OAIX0DH7E4IAcURbnVN:-OAIcCCT3huoHnZMwpIM:b-8ptauj) ([raw file](https://github.com/starkware-libs/sequencer/blob/a52ecf93747ae84bcda3e00490a7f902fbe4d5d0/crates/mempool/src/mempool_test.rs#L447)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

The test is already covered here.
Both tests check the same scenario.
This test name is more informative.
</blockquote></details>

i'm not sure it's a better name. how's `test_add_tx_replaces_lower_nonce_with_higher_nonce_in_queue_and_pool`?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1617)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 422 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1617#-OAIbl0n07wFTnzwaGTV:-OAN37bZ0sqgqQbIJQ7e:b-kfhk2n) ([raw file](https://github.com/starkware-libs/sequencer/blob/a52ecf93747ae84bcda3e00490a7f902fbe4d5d0/crates/mempool/src/mempool_test.rs#L422)):*
> ```XML
> 
> #[rstest]
> fn test_add_tx_delete_tx_with_lower_nonce_than_account_nonce() {
> ```

I have a [PR](https://reviewable.io/reviews/starkware-libs/sequencer/1590) that updates tests' names.

This PR simply deletes redundant test.
___
*[`crates/mempool/src/mempool_test.rs` line 447 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1617#-OAIX0DH7E4IAcURbnVN:-OAN0qVt5cjopaZfipHR:b-55ph6q) ([raw file](https://github.com/starkware-libs/sequencer/blob/a52ecf93747ae84bcda3e00490a7f902fbe4d5d0/crates/mempool/src/mempool_test.rs#L447)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

i'm not sure it's a better name. how's `test_add_tx_replaces_lower_nonce_with_higher_nonce_in_queue_and_pool`?
</blockquote></details>

Note that it does not replace the transaction (think about a case with several txs).
It deletes the txs with lower nonces.

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1617)* status: all files reviewed, 1 unresolved discussion

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1617#-:-OAN7CVQ9a7GSzEAgYcK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1617#-:-OAWXHqZ6JPZpVsI4fL8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

**Pull request merged**
