### PR TITLE
fix(mempool): move starknet-core-types to dev-dependencies

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1287)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1287)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1287#-O8pTXfU8WTG_GtidZLz:-O8pTXfV55GWQ5ukgLos:bs9juq9) (no related file):*
This crate is only used in tests, therefore should move to `dev-dependencies`.

___

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1287#-:-O8q1cbc4o2Ri3JyA4iD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1287#-O8pTXfU8WTG_GtidZLz:-O8q1dGs2O1jGhEQ8jCB:b-kl4gt0) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This crate is only used in tests, therefore should move to `dev-dependencies`.
</blockquote></details>

Noicee
BTW these kinds of things will also help with the linking issue, since they simplify the depdency graph (only test builds will require these dependencies, transitively)

___

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1287)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @MohammadNassar1)

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1287#-:-O8q4h6cCyrobR9gT6Rt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
