### PR TITLE
feat(cairo_native): add a binary crate for cairo_native compilation

### PR DESCRIPTION
**Pull request by avi-starkware**

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1945)* status: 4 of 9 files reviewed, 4 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/bin/starknet-native-compile/Cargo.toml` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OBQsaso20D4LmuRGgJi:-OBQsaso20D4LmuRGgJj:boolt4h) ([raw file](https://github.com/starkware-libs/sequencer/blob/32a4e79475bcaf9337cc37543d396d8331c1680a/crates/bin/starknet-native-compile/Cargo.toml#L13)):*
> ```TOML
> cairo-native = "0.2.0-alpha.4"
> clap = { version = "4.5.4", features = ["derive"] }
> serde_json = "1.0.68"
> ```

Update and add a todo to check consistency with the blockifier



_Code quote:_
```TOML
cairo-lang-sierra = "2.8.4"
cairo-lang-starknet-classes = "2.8.4"
cairo-native = "0.2.0-alpha.4"
clap = { version = "4.5.4", features = ["derive"] }
serde_json = "1.0.68"
```
___
*[`crates/bin/starknet-native-compile/src/test.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OBQvLap223Q5ZmnUkGT:-OBQvLap223Q5ZmnUkGU:b-42susd) ([raw file](https://github.com/starkware-libs/sequencer/blob/32a4e79475bcaf9337cc37543d396d8331c1680a/crates/bin/starknet-native-compile/src/test.rs#L13)):*
> ```XML
> 
> #[test]
> fn test_save_and_load_contract() {
> ```

Add a negative test: a class that cannot be compiled
___
*[`crates/bin/starknet-native-compile/src/main.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OBQvAzyANQr-1Qbt2Uv:-OBQvAzyANQr-1Qbt2Uw:b-1mq89t) ([raw file](https://github.com/starkware-libs/sequencer/blob/32a4e79475bcaf9337cc37543d396d8331c1680a/crates/bin/starknet-native-compile/src/main.rs#L24)):*
> ```XML
> const DEFAULT_OUTPUT_FILE: &str = "./output.so";
> 
> fn main() {
> ```

Add todos the restrict time and memory
___
*[`crates/bin/starknet-native-compile/src/main.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OBQv7ZZ9XfbC3jg-snk:-OBQv7ZZ9XfbC3jg-snl:b-s7oyj3) ([raw file](https://github.com/starkware-libs/sequencer/blob/32a4e79475bcaf9337cc37543d396d8331c1680a/crates/bin/starknet-native-compile/src/main.rs#L43)):*
> ```XML
>         process::exit(1);
>     });
>     println!("Compilation successful. Elapsed: {:?}", start.elapsed());
> ```

Move into a func and test the func



_Code quote:_
```XML
    let args = Args::parse();
    let path = args.path;
    let output = args.output.unwrap_or_else(|| DEFAULT_OUTPUT_FILE.to_string());

    println!("Loading Sierra program from file: {:?}", &path);
    let sierra_program = load_sierra_program_from_file(&path);

    println!("Compiling Sierra program into file {:?}", &output);
    let start = std::time::Instant::now();
    let mut contract_executor = AotContractExecutor::new(&sierra_program, OptLevel::default())
        .unwrap_or_else(|err| {
            eprintln!("Error compiling Sierra program: {}", err);
            process::exit(1);
        });
    contract_executor.save(output.clone()).unwrap_or_else(|err| {
        eprintln!("Error saving compiled program: {}", err);
        process::exit(1);
    });
    println!("Compilation successful. Elapsed: {:?}", start.elapsed());
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1945)* status: 4 of 9 files reviewed, 5 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/bin/starknet-native-compile/test_files/faulty_account.sierra.json` line 2 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OBQvSki6UjYHLrKQA9J:-OBQvSki6UjYHLrKQA9K:bgeh3wy) ([raw file](https://github.com/starkware-libs/sequencer/blob/32a4e79475bcaf9337cc37543d396d8331c1680a/crates/bin/starknet-native-compile/test_files/faulty_account.sierra.json#L2)):*
> ```JSON
> {
>   "sierra_program": [
> ```

Take erc20 or account instead

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1945)* status: 4 of 9 files reviewed, 6 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/bin/starknet-native-compile/src/test.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OBQvgxmA5GUWMAl1TEN:-OBQvgxmA5GUWMAl1TEO:b-pebrcw) ([raw file](https://github.com/starkware-libs/sequencer/blob/32a4e79475bcaf9337cc37543d396d8331c1680a/crates/bin/starknet-native-compile/src/test.rs#L10)):*
> ```XML
> 
> const TEST_FILE: &str = "./test_files/faulty_account.sierra.json";
> const TEST_OUTPUT: &str = "./target/test_output.so";
> ```

Better to remove this



_Code quote:_
```XML
const TEST_OUTPUT: &str = "./target/test_output.so";
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1945)* status: 4 of 9 files reviewed, 6 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/bin/starknet-native-compile/src/test.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OBQvgxmA5GUWMAl1TEN:-OBQvmfs3t6PI73njHfh:bj9w4rh) ([raw file](https://github.com/starkware-libs/sequencer/blob/32a4e79475bcaf9337cc37543d396d8331c1680a/crates/bin/starknet-native-compile/src/test.rs#L10)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Better to remove this
</blockquote></details>

Try to be consistent with sierra to casm

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1945)* status: 7 of 9 files reviewed, 6 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/bin/starknet-native-compile/src/test.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OBQvgxmA5GUWMAl1TEN:-OBW-IeU-Jy1_QccGadr:b32ey1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/32a4e79475bcaf9337cc37543d396d8331c1680a/crates/bin/starknet-native-compile/src/test.rs#L10)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Try to be consistent with sierra to casm
</blockquote></details>

I moved the testing to the crate that does the sierra to casm compilation in #1998
___
*[`crates/bin/starknet-native-compile/src/test.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OBQvLap223Q5ZmnUkGT:-OBW-YP34nvpLuf9F4S_:b-wxzaks) ([raw file](https://github.com/starkware-libs/sequencer/blob/32a4e79475bcaf9337cc37543d396d8331c1680a/crates/bin/starknet-native-compile/src/test.rs#L13)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Add a negative test: a class that cannot be compiled
</blockquote></details>

Added in #1998

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1945)* status: 4 of 9 files reviewed, 6 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/bin/starknet-native-compile/Cargo.toml` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OBQsaso20D4LmuRGgJi:-OBZqAj8C9to8iYuK4O-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/32a4e79475bcaf9337cc37543d396d8331c1680a/crates/bin/starknet-native-compile/Cargo.toml#L13)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Update and add a todo to check consistency with the blockifier
</blockquote></details>

Done.
___
*[`crates/bin/starknet-native-compile/src/main.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OBQvAzyANQr-1Qbt2Uv:-OBZrj19BkqtzaADgtbO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/32a4e79475bcaf9337cc37543d396d8331c1680a/crates/bin/starknet-native-compile/src/main.rs#L24)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Add todos the restrict time and memory
</blockquote></details>

Done.
___
*[`crates/bin/starknet-native-compile/src/main.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OBQv7ZZ9XfbC3jg-snk:-OBZrJ-00cm2IuukH5zc:b68o3y0) ([raw file](https://github.com/starkware-libs/sequencer/blob/32a4e79475bcaf9337cc37543d396d8331c1680a/crates/bin/starknet-native-compile/src/main.rs#L43)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Move into a func and test the func
</blockquote></details>

The testing will be done through `starknet_sierra_compile` in #1998.
___
*[`crates/bin/starknet-native-compile/test_files/faulty_account.sierra.json` line 2 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OBQvSki6UjYHLrKQA9J:-OBZqEvSEwK2AaJKGUDD:b-jjbjuy) ([raw file](https://github.com/starkware-libs/sequencer/blob/32a4e79475bcaf9337cc37543d396d8331c1680a/crates/bin/starknet-native-compile/test_files/faulty_account.sierra.json#L2)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Take erc20 or account instead
</blockquote></details>

I am using the test contract used in the crate `starknet_sierra_compile`.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1945)* status: 7 of 9 files reviewed, 7 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/bin/starknet-native-compile/src/main.rs` line 20 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OB_H_xp-JxEqlN3Bq_g:-OB_H_xp-JxEqlN3Bq_h:bdwx85) ([raw file](https://github.com/starkware-libs/sequencer/blob/580e598973588652903dc3b0e6f9cd9a8b9bb624/crates/bin/starknet-native-compile/src/main.rs#L20)):*
> ```XML
> }
> 
> const DEFAULT_OUTPUT_FILE: &str = "./output.so";
> ```

Remove the default value (no reason to do this so far)



_Code quote:_
```XML
    /// The output file name (default: output.so).
    output: Option<String>,
}

const DEFAULT_OUTPUT_FILE: &str = "./output.so";
```
___
*[`crates/bin/starknet-native-compile/build.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OB_H7Ra334Uz_b9BBHW:-OB_H7Ra334Uz_b9BBHX:b-ugi44f) ([raw file](https://github.com/starkware-libs/sequencer/blob/580e598973588652903dc3b0e6f9cd9a8b9bb624/crates/bin/starknet-native-compile/build.rs#L3)):*
> ```XML
> use std::path::Path;
> 
> // This build script sets the env var CAIRO_NATIVE_RUNTIME_LIBRARY to an absolute path to the runtime library.
> ```

Document why this is needed



_Code quote:_
```XML
// This build script sets the env var CAIRO_NATIVE_RUNTIME_LIBRARY to an absolute path to the runtime library.
```
___
*[`crates/bin/starknet-native-compile/build.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OB_HB9uB4taNDLK-e3H:-OB_HB9uB4taNDLK-e3I:b-wa9ath) ([raw file](https://github.com/starkware-libs/sequencer/blob/580e598973588652903dc3b0e6f9cd9a8b9bb624/crates/bin/starknet-native-compile/build.rs#L17)):*
> ```XML
>     let blockifier_path = out_dir
>         .ancestors()
>         .nth(3)
> ```

Document why 3



_Code quote:_
```XML
        .nth(3)
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1945)* status: 7 of 9 files reviewed, 6 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/bin/starknet-native-compile/src/utils.rs` line 11 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OB_KQ3l-OWfHlK5J8iV:-OB_KQ3l-OWfHlK5J8iW:b-u07gaw) ([raw file](https://github.com/starkware-libs/sequencer/blob/580e598973588652903dc3b0e6f9cd9a8b9bb624/crates/bin/starknet-native-compile/src/utils.rs#L11)):*
> ```XML
>     let raw_contract_class = std::fs::read_to_string(path).unwrap_or_else(|err| {
>         eprintln!("Error reading Sierra file: {}", err);
>         process::exit(1);
> ```

Is this the right way to go?
Why not returning Result throughout the code?
Can main return result?



_Code quote:_
```XML
  process::exit(1);
```
___
*[`crates/bin/starknet-native-compile/src/main.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OB_JhH2-z4RBGqUFA2z:-OB_JhH2-z4RBGqUFA3-:b-4kgpzz) ([raw file](https://github.com/starkware-libs/sequencer/blob/580e598973588652903dc3b0e6f9cd9a8b9bb624/crates/bin/starknet-native-compile/src/main.rs#L28)):*
> ```XML
>     let output = args.output.unwrap_or_else(|| DEFAULT_OUTPUT_FILE.to_string());
> 
>     println!("Loading Sierra program from file: {:?}", &path);
> ```

We are not going to see these prints in the blockifier run, right?



_Code quote:_
```XML
println!("Loading Sierra program from file: {:?}", &path);
```
___
*[`crates/bin/starknet-native-compile/src/main.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OB_KEDL99tVDSz8nOmW:-OB_KEDL99tVDSz8nOmX:b-3lcf73) ([raw file](https://github.com/starkware-libs/sequencer/blob/580e598973588652903dc3b0e6f9cd9a8b9bb624/crates/bin/starknet-native-compile/src/main.rs#L33)):*
> ```XML
>     println!("Compiling Sierra program into file {:?}", &output);
>     let start = std::time::Instant::now();
>     let mut contract_executor = AotContractExecutor::new(&sierra_program, OptLevel::default())
> ```

What is this? what are the options? do we want to pass argument for it?



_Code quote:_
```XML
OptLevel::default()
```

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1945)* status: 6 of 9 files reviewed, 6 unresolved discussions (waiting on @avi-starkware and @noaov1)

**Comment by avi-starkware** [comment]
*[`crates/bin/starknet-native-compile/src/main.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OB_KEDL99tVDSz8nOmW:-OBagvzA90lHIb7ddHBz:b-8vlvtt) ([raw file](https://github.com/starkware-libs/sequencer/blob/580e598973588652903dc3b0e6f9cd9a8b9bb624/crates/bin/starknet-native-compile/src/main.rs#L33)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

What is this? what are the options? do we want to pass argument for it?
</blockquote></details>

[These](https://github.com/lambdaclass/cairo_native/blob/564f7e2136e53a1e43033aefa3836b4dc591ffc1/src/ffi.rs#L55-L63) are the options.

It indicates the level of optimization the compiler should employ while compiling code. I am not sure what impact this config has, so I just put it on default. Nethermind did the same in their PRs.

The `OptLevel` is plugged into LLVM [here](https://github.com/lambdaclass/cairo_native/blob/564f7e2136e53a1e43033aefa3836b4dc591ffc1/src/ffi.rs#L142-L155).

According to ChatGPT, the higher the optimization the longer the compilation time, but the performance of the compiled code should improve, though it could increase the binary file size and its memory usage.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1945)* status: 6 of 9 files reviewed, 6 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/bin/starknet-native-compile/src/main.rs` line 20 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OB_H_xp-JxEqlN3Bq_g:-OBagGgv70nUE2wjt5Xx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/580e598973588652903dc3b0e6f9cd9a8b9bb624/crates/bin/starknet-native-compile/src/main.rs#L20)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Remove the default value (no reason to do this so far)
</blockquote></details>

Done.
___
*[`crates/bin/starknet-native-compile/src/main.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OB_JhH2-z4RBGqUFA2z:-OBagIjb2ctJK86D2A2u:b34vpl2) ([raw file](https://github.com/starkware-libs/sequencer/blob/580e598973588652903dc3b0e6f9cd9a8b9bb624/crates/bin/starknet-native-compile/src/main.rs#L28)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

We are not going to see these prints in the blockifier run, right?
</blockquote></details>

They will appear, unfortunately...
They were used for debugging. I removed all of them.
___
*[`crates/bin/starknet-native-compile/src/utils.rs` line 11 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OB_KQ3l-OWfHlK5J8iV:-OBajkI7CHjqs58RAy92:b9f4koy) ([raw file](https://github.com/starkware-libs/sequencer/blob/580e598973588652903dc3b0e6f9cd9a8b9bb624/crates/bin/starknet-native-compile/src/utils.rs#L11)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Is this the right way to go?
Why not returning Result throughout the code?
Can main return result?
</blockquote></details>

Because it is a binary running in another process. It can only output `stdout` and `stderr`.
___
*[`crates/bin/starknet-native-compile/build.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OB_H7Ra334Uz_b9BBHW:-OBak-Oj4A1g-XAuCGyM:b-s1msus) ([raw file](https://github.com/starkware-libs/sequencer/blob/580e598973588652903dc3b0e6f9cd9a8b9bb624/crates/bin/starknet-native-compile/build.rs#L3)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Document why this is needed
</blockquote></details>

I removed the file. The env var is needed to run the compiled binary, not to build it. It would make more sense to set it correctly in the crate that uses the compiled binary.
___
*[`crates/bin/starknet-native-compile/build.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OB_HB9uB4taNDLK-e3H:-OBakJCp1Mgu17P1qSP_:b-qt59j8) ([raw file](https://github.com/starkware-libs/sequencer/blob/580e598973588652903dc3b0e6f9cd9a8b9bb624/crates/bin/starknet-native-compile/build.rs#L17)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Document why 3
</blockquote></details>

I removed the `build.rs` file.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1945)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/bin/starknet-native-compile/src/main.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-OB_KEDL99tVDSz8nOmW:-OBayIyR879S6MRl7n-5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/580e598973588652903dc3b0e6f9cd9a8b9bb624/crates/bin/starknet-native-compile/src/main.rs#L33)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Add a todo to configure the opt level after testing it. It might speed things up
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1945#-:-OBdVP3q2bQR7YBvVssH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1945)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by avi-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1945)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
