### PR TITLE
refactor(mempool): change sender address to address in tx macro

### PR DESCRIPTION
**Pull request by MohammadNassar1**

### CODE REVIEW

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1484#-:-O9hx538Bd7oZNTSHEhQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1484)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/tests/flow_test.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1484#-O9hzNEK9by8BbMKqNiw:-O9hzNEK9by8BbMKqNix:b-dn7xy) ([raw file](https://github.com/starkware-libs/sequencer/blob/393f8021e418337001794cc33474a1fdb7851fd2/crates/mempool/tests/flow_test.rs#L24)):*
> ```XML
> 
> #[rstest]
> fn test_add_tx_fills_nonce_gap(mut mempool: Mempool) {
> ```

Can lines be squashed (in both test files)?
Note that it must fit into 100 chars.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1484)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 705 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1484#-O9iL6FK7jsVY-4ZmjEJ:-O9iKzajCn-KFIiG2Dgz:b-q1d5oq) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e28a837ada0af060e6a3e3638660dc76fa0806b/crates/mempool/src/mempool_test.rs#L705)):*
> ```XML
> 
> #[rstest]
> fn test_fee_escalation_invalid_replacement() {
> ```

Separate PR, please.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1484)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 705 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1484#-O9iL6FK7jsVY-4ZmjEJ:-O9iX1nj7ElvPpbYTrEV:bd10n9v) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e28a837ada0af060e6a3e3638660dc76fa0806b/crates/mempool/src/mempool_test.rs#L705)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Separate PR, please.
</blockquote></details>

There is no change here.
Maybe you mean the changes between r1 and r2? I rebased it over `origin/main`, which explains that.
___
*[`crates/mempool/tests/flow_test.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1484#-O9hzNEK9by8BbMKqNiw:-O9iYmws0LKzg6ydE54w:b8j17dp) ([raw file](https://github.com/starkware-libs/sequencer/blob/393f8021e418337001794cc33474a1fdb7851fd2/crates/mempool/tests/flow_test.rs#L24)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can lines be squashed (in both test files)?
Note that it must fit into 100 chars.
</blockquote></details>

Done.
I went over the updated lines.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1484)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/tests/flow_test.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1484#-O9hzNEK9by8BbMKqNiw:-O9iv0fSAJH3CNEQ22Mt:bwygxsx) ([raw file](https://github.com/starkware-libs/sequencer/blob/393f8021e418337001794cc33474a1fdb7851fd2/crates/mempool/tests/flow_test.rs#L24)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Okay, please note that `rustfmt` doesn't catch issues in macro calls.
</blockquote></details>

Noted.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1484#-:-O9jSpUc9MkuWL_0TDfQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
