### PR TITLE
chore(blockifier): combine tx_info.enforce_fee() with charge_fee flag

### PR DESCRIPTION
**Pull request by avivg-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/707)

### CODE REVIEW

**Review by avivg-starkware — COMMENTED** [review]
there are comments including "aviv" for my documentation, will remove before merge

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/707#-:-O5wu0Dk7oOOteSH8UFJ:b-plphe)* status: 0 of 17 files reviewed, all discussions resolved (waiting on @meship-starkware and @noaov1)

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/707)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/707#-O5x4wuc085m4ejl5Y7U:-O5x4wuc085m4ejl5Y7V:b5pzi10) ([raw file](https://github.com/starkware-libs/sequencer/blob/3857fad0f868f9d5dcb376fe4a768673cfe498b8/crates/blockifier/src/blockifier/transaction_executor.rs#L93)):*
> ```XML
>             self.block_state.as_mut().expect(BLOCK_STATE_ACCESS_ERR),
>         );
>         let tx_charge_fee = tx.create_tx_info().expect("Failed to create tx info.").enforce_fee(); //aviv: todo: msg -> CONST?
> ```

Remove all comments.

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/707)* status: 0 of 17 files reviewed, 3 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 287 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/707#-O5x5B_z23PSIXssa6VB:-O5x5B_z23PSIXssa6VC:b-amuv8r) ([raw file](https://github.com/starkware-libs/sequencer/blob/3857fad0f868f9d5dcb376fe4a768673cfe498b8/crates/blockifier/src/concurrency/versioned_state_test.rs#L287)):*
> ```XML
>         });
>     });
> }
> ```

I think it's better to declare a variable where you use it.  



_Suggestion:_
```XML


    // Execute transactions
    thread::scope(|s| {
        s.spawn(move || {
            let charge_fee_1 = account_tx_1.create_tx_info().unwrap().enforce_fee(); // aviv: todo better implementation?
            let result = account_tx_1.execute(&mut state_1, &block_context_1, charge_fee_1, true); // aviv: was true, true
            assert_eq!(result.is_err(), enforce_fee);
        });
        s.spawn(move || {
            let charge_fee_2 = account_tx_2.create_tx_info().unwrap().enforce_fee(); // aviv: todo better implementation?
            account_tx_2.execute(&mut state_2, &block_context_2, charge_fee_2, true).unwrap(); // aviv: was true, true
            // Check that the constructor wrote ctor_arg to the storage.
            let storage_key = get_storage_var_address("ctor_arg", &[]);
            let deployed_contract_address = calculate_contract_address(
                ContractAddressSalt::default(),
                class_hash,
                &constructor_calldata,
                ContractAddress::default(),
            )
            .unwrap();
            let read_storage_arg =
                state_2.get_storage_at(deployed_contract_address, storage_key).unwrap();
            assert_eq!(ctor_storage_arg, read_storage_arg);
        });
    });
}
```
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/707#-O5x6VgNDpWxwyQuYLOC:-O5x6VgNDpWxwyQuYLOD:b-xmepgq) ([raw file](https://github.com/starkware-libs/sequencer/blob/3857fad0f868f9d5dcb376fe4a768673cfe498b8/crates/blockifier/src/transaction/transaction_execution.rs#L119)):*
> ```XML
>     ) -> TransactionExecutionResult<TransactionExecutionInfo> {
>         let tx_context = Arc::new(block_context.to_tx_context(self)?);
>         let limit_steps_by_resources = _execution_flags.charge_fee; // aviv: new
> ```

The _ notion is for unused variables. 



_Suggestion:_
```XML
        execution_flags: ExecutionFlags,
    ) -> TransactionExecutionResult<TransactionExecutionInfo> {
        let tx_context = Arc::new(block_context.to_tx_context(self)?);
        let limit_steps_by_resources = execution_flags.charge_fee; // aviv: new
```

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/707)* status: 0 of 17 files reviewed, 5 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/test_utils/prices.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/707#-O6-bXwaC6OwmUFVlAdz:-O6-bXwaC6OwmUFVlAe-:bj4nr7h) ([raw file](https://github.com/starkware-libs/sequencer/blob/3857fad0f868f9d5dcb376fe4a768673cfe498b8/crates/blockifier/src/test_utils/prices.rs#L81)):*
> ```XML
>                 ),
>                 ExecutionMode::Execute,
>                 false, // aviv: limit_steps_by_resources: can be enforce_fee() instead of false.?
> ```

It is better here to have false because it is not dependent on enforce fee, here we just want to get the resources of fee_transfer without actually creating a transaction.  
___
*[`crates/papyrus_execution/src/lib.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/707#-O6-eGpqCEZT8nSZJuqY:-O6-eGpqCEZT8nSZJuqZ:bmik3h2) ([raw file](https://github.com/starkware-libs/sequencer/blob/3857fad0f868f9d5dcb376fe4a768673cfe498b8/crates/papyrus_execution/src/lib.rs#L256)):*
> ```XML
>         // TODO(yair): fix when supporting v3 transactions
>         Arc::new(TransactionContext { block_context, tx_info }),
>         limit_steps_by_resources,
> ```

I think the todo refers to the Deprecated tx_info. 



_Suggestion:_
```XML
    )?;
    // TODO(yair): fix when supporting v3 transactions
    let tx_info = TransactionInfo::Deprecated(DeprecatedTransactionInfo::default()); // aviv: new
    let limit_steps_by_resources = tx_info.enforce_fee(); // aviv: new

    let mut context = EntryPointExecutionContext::new_invoke(
        Arc::new(TransactionContext { block_context, tx_info }),
        limit_steps_by_resources,
```

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/707)* status: 0 of 18 files reviewed, 5 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 287 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/707#-O5x5B_z23PSIXssa6VB:-O61lGob61URlLRjWdaF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3857fad0f868f9d5dcb376fe4a768673cfe498b8/crates/blockifier/src/concurrency/versioned_state_test.rs#L287)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I think it's better to declare a variable where you use it.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/prices.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/707#-O6-bXwaC6OwmUFVlAdz:-O61kxNV2fTozxCyTTfW:b-lfw0a9) ([raw file](https://github.com/starkware-libs/sequencer/blob/3857fad0f868f9d5dcb376fe4a768673cfe498b8/crates/blockifier/src/test_utils/prices.rs#L81)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

It is better here to have false because it is not dependent on enforce fee, here we just want to get the resources of fee_transfer without actually creating a transaction.
</blockquote></details>

Thank you for explaining! I see what you're saying.  I'd love to ask about it in person as well
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/707#-O5x6VgNDpWxwyQuYLOC:-O61ks--BgVe-ZsLtvyh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3857fad0f868f9d5dcb376fe4a768673cfe498b8/crates/blockifier/src/transaction/transaction_execution.rs#L119)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

The _ notion is for unused variables.
</blockquote></details>

Done.
___
*[`crates/papyrus_execution/src/lib.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/707#-O6-eGpqCEZT8nSZJuqY:-O61kbhI2iosvSBj__wU:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/3857fad0f868f9d5dcb376fe4a768673cfe498b8/crates/papyrus_execution/src/lib.rs#L256)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I think the todo refers to the Deprecated tx_info.
</blockquote></details>

done

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 17 files at r1, 1 of 4 files at r2, 12 of 14 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/707)* status: 16 of 18 files reviewed, 2 unresolved discussions (waiting on @avivg-starkware and @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 17 files at r1, 1 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/707)* status: all files reviewed, 2 unresolved discussions (waiting on @avivg-starkware and @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/707)* status: all files reviewed, 4 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 171 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/707#-O6KJiiL0-kZt0-0toDB:-O6KJiiL0-kZt0-0toDC:b7m5pyj) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ecfacbc766670a60dea32e8b990affba565c089/crates/blockifier/src/transaction/account_transactions_test.rs#L171)):*
> ```XML
>             resource_bounds: l1_resource_bounds(u64::from(!zero_bounds), DEFAULT_STRK_L1_GAS_PRICE),
>             version,
>         },
> ```

We need to consider the relevance of these tests after our changes. I think they are still relevant, but maybe some changes are needed.  @noaov1 WDYT?
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 191 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/707#-O6KJvtT8gRRelNymeUp:-O6KJvtT8gRRelNymeUq:brhumzf) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ecfacbc766670a60dea32e8b990affba565c089/crates/blockifier/src/transaction/account_transactions_test.rs#L191)):*
> ```XML
>         &mut state,
>         &block_context,
>         invoke_tx_args! {
> ```

Same here

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/707)* status: all files reviewed, 5 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 805 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/707#-O6KKuA36lVBSeFPYIau:-O6KKuA36lVBSeFPYIav:b-83sjoh) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ecfacbc766670a60dea32e8b990affba565c089/crates/blockifier/src/transaction/transactions_test.rs#L805)):*
> ```XML
>     let charge_fee = tx_info.enforce_fee();
> 
>     match tx_info {
> ```

Nice!



_Code quote:_
```XML
    let tx_info = invalid_tx.create_tx_info();
    let charge_fee = tx_info.enforce_fee();

    match tx_info {
```

**Pull request closed without merging**
