### PR TITLE
chore(blockifier): add feild channel_size to contract_class_manager_config

### PR DESCRIPTION
**Pull request by avivg-starkware**

### CODE REVIEW

**Comment by avivg-starkware** [comment]
* **#2902** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2902?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2902?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/state/contract_class_manager.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2902#-OEsJSWL5Rxyw9Ps-LqL:-OEsJSWL5Rxyw9Ps-LqM:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7da892096f82a07b970a073c5f6cbf94e322c2d0/crates/blockifier/src/state/contract_class_manager.rs#L31)):*
> ```XML
> use crate::state::global_cache::{CachedCasm, ContractCaches};
> 
> pub const CHANNEL_SIZE: usize = 1000;
> ```





_Suggestion:_
```XML
pub const DEFAULT_COMPILATION_REQUEST_CHANNEL_SIZE: usize = 1000;
```

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2902)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware and @noaov1)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2902)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2902#-OEsJSWL5Rxyw9Ps-LqL:-OEsynwE6yAx-xJ8GMVX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7da892096f82a07b970a073c5f6cbf94e322c2d0/crates/blockifier/src/state/contract_class_manager.rs#L31)):*
> ```XML
> use crate::state::global_cache::{CachedCasm, ContractCaches};
> 
> pub const CHANNEL_SIZE: usize = 1000;
> ```

Done.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2902)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @avivg-starkware)

___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2902#-OEtKezT3erhX7lbz2u_:-OEtKezT3erhX7lbz2ua:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0adfb8cd902e769387d1670f2c078726dbb563db/crates/blockifier/src/state/contract_class_manager.rs#L96)):*
> ```XML
>             }
> 
>             let (sender, receiver) = sync_channel(DEFAULT_COMPILATION_REQUEST_CHANNEL_SIZE);
> ```





_Suggestion:_
```XML
            let (sender, receiver) = sync_channel(config.channel_size);
```

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2902)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on and @noaov1)

___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2902#-OEtKezT3erhX7lbz2u_:-OExuEa7ASoJkRxNTHfM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0adfb8cd902e769387d1670f2c078726dbb563db/crates/blockifier/src/state/contract_class_manager.rs#L96)):*
> ```XML
>             }
> 
>             let (sender, receiver) = sync_channel(DEFAULT_COMPILATION_REQUEST_CHANNEL_SIZE);
> ```

Done.

**Review by avi-starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2902)* status: all files reviewed, 2 unresolved discussions (waiting on @avivg-starkware and @noaov1)

___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 129 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2902#-OEy-jSXCKONMae985w9:-OEy-jSXCKONMae985wA:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e39a328ec3ddc458b90e0e78a87f3ed13d9c6720/crates/blockifier/src/state/contract_class_manager.rs#L129)):*
> ```XML
>                     "Compilation request channel is full (size: {}). Compilation request for \
>                      class hash {} was not sent.",
>                     DEFAULT_COMPILATION_REQUEST_CHANNEL_SIZE,
> ```





_Suggestion:_
```XML
self.config.channel_size
```

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2902)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

**Review by noaov1 — CHANGES_REQUESTED** [review]
Please rebase over `main-13.4`

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2902#-:-OEyORvX7H_o1NpXIy2i:bivdxdv)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

**Review by avivg-starkware — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2902#-:-OF1SbHhAl1p4CRclV-K:bb6un1j)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware)

___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 129 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2902#-OEy-jSXCKONMae985w9:-OF1SpVi0TgB05xwHhqr:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/19dab86c341ea58d021b561e9cbdb59c8e535e67/crates/blockifier/src/state/contract_class_manager.rs#L129)):*
> ```XML
>                     "Compilation request channel is full (size: {}). Compilation request for \
>                      class hash {} was not sent.",
>                     DEFAULT_COMPILATION_REQUEST_CHANNEL_SIZE,
> ```

Done.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2902#-:-OF31WB925zpaeiOM7iT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware)

**Review by avivg-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2902)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware)

**Review by avivg-starkware — COMMENTED** [review]
> Dismissed @avi-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2902)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Pull request merged**
