### PR TITLE
refactor(batcher): reduce the number of arguments to create_block_builder

### PR DESCRIPTION
**Pull request by dafnamatsry**

### CODE REVIEW

**Comment by dafnamatsry** [comment]
* **#1934** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1934?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2011** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2011?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dafnamatsry and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2011)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 336 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2011#-OB_SVLD2zhnpHwqvfpK:-OB_SVLD2zhnpHwqvfpL:b-mm9epj) ([raw file](https://github.com/starkware-libs/sequencer/blob/19bf13f7a93466bedbc01e2e6aa28796f88c526b/crates/starknet_batcher/src/block_builder.rs#L336)):*
> ```XML
>         let executor = self.preprocess_and_create_transaction_executor(
>             block_metadata.height,
>             block_metadata.retrospective_block_hash,
> ```

Make block metadata an arg instead?



_Code quote:_
```XML
            block_metadata.height,
            block_metadata.retrospective_block_hash,
```
___
*[`crates/starknet_batcher/src/block_builder.rs` line 344 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2011#-OB_SqKt0_7TBM6HkJMJ:-OB_SqKu1-MhQuQU93PT:b5v7f62) ([raw file](https://github.com/starkware-libs/sequencer/blob/19bf13f7a93466bedbc01e2e6aa28796f88c526b/crates/starknet_batcher/src/block_builder.rs#L344)):*
> ```XML
>             self.block_builder_config.tx_chunk_size,
>             execution_params.deadline,
>             execution_params.fail_on_err,
> ```

Also here.



_Code quote:_
```XML
            execution_params.deadline,
            execution_params.fail_on_err,
```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2011)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 336 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2011#-OB_SVLD2zhnpHwqvfpK:-OB_WVHgCJsirFu8zBc9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/19bf13f7a93466bedbc01e2e6aa28796f88c526b/crates/starknet_batcher/src/block_builder.rs#L336)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Make block metadata an arg instead?
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/block_builder.rs` line 344 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2011#-OB_SqKt0_7TBM6HkJMJ:-OB_WV_PA7oKsdObKnKB:b-htctya) ([raw file](https://github.com/starkware-libs/sequencer/blob/19bf13f7a93466bedbc01e2e6aa28796f88c526b/crates/starknet_batcher/src/block_builder.rs#L344)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Also here.
</blockquote></details>

Done.
Note that the chunk size is not part of the struct since it is defined in the BlockBuilderConfig.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2011#-:-OB_YSjO2BnjizXiNZf7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
