### PR TITLE
refactor(mempool): use TransactionQueueContent[Builder] in MempoolContent[Builder]

### PR DESCRIPTION
**Pull request by elintul**
…tent[Builder]

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/977)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/977)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YBfX2DAJrpfvHEkth:-O7YBfX36pJ-jxymE5h5:b-g583pp) ([raw file](https://github.com/starkware-libs/sequencer/blob/858741f52321936401d33d1f303ac655d17110d1/crates/mempool/src/mempool_test.rs#L47)):*
> ```XML
>     }
> 
>     fn assert_eq_tx_queue_content(&self, mempool: &Mempool) {
> ```

Will be renamed, next (only renames) PR.



_Suggestion:_
```XML
assert_eq_tx_priority_queue_content
```
___
*[`crates/mempool/src/mempool_test.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YBpbsAfsQksk0Qmg7:-O7YBpbsAfsQksk0Qmg8:b-g583pp) ([raw file](https://github.com/starkware-libs/sequencer/blob/858741f52321936401d33d1f303ac655d17110d1/crates/mempool/src/mempool_test.rs#L94)):*
> ```XML
>     }
> 
>     fn with_queue<Q>(mut self, queue_txs: Q) -> Self
> ```

Will be renamed, next (only renames) PR.



_Suggestion:_
```XML
with_priority_queue
```
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YBwCf5sACLPeBOK9V:-O7YBwCf5sACLPeBOK9W:b-cs8amz) ([raw file](https://github.com/starkware-libs/sequencer/blob/858741f52321936401d33d1f303ac655d17110d1/crates/mempool/src/transaction_queue_test_utils.rs#L9)):*
> ```XML
> 
> /// Represents the internal content of the transaction queue.
> /// Enables customized (and potentially inconsistent) creation for unit testing.
> ```

Comment from previous PR.
+ Renames only (no `_` in beginning of (now) used items).

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/977)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YBwCf5sACLPeBOK9V:-O7YCP3i1Ye5nXZyryMS:blwstov) ([raw file](https://github.com/starkware-libs/sequencer/blob/858741f52321936401d33d1f303ac655d17110d1/crates/mempool/src/transaction_queue_test_utils.rs#L9)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Comment from previous PR.
+ Renames only (no `_` in beginning of (now) used items).
</blockquote></details>

This bullet was supposed to be a "+".

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/977)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YaYgf3-ZbyBoxCkhg:-O7YaYgf3-ZbyBoxCkhh:bxe56p3) ([raw file](https://github.com/starkware-libs/sequencer/blob/252356546ef3686fff1c1393acf983f95e4ced44/crates/mempool/src/mempool_test.rs#L40)):*
> ```XML
>     fn assert_eq_pool_and_queue_content(&self, mempool: &Mempool) {
>         self.assert_eq_tx_pool_content(mempool);
>         self.assert_eq_tx_queue_content(mempool);
> ```

Why do we check only the priority queue here? if so, the function name should be updated



_Code quote:_
```XML
self.assert_eq_tx_queue_content(mempool);
```
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YcfOgAXUpzT_UqeSq:-O7YcfOgAXUpzT_UqeSr:blqqtzx) ([raw file](https://github.com/starkware-libs/sequencer/blob/252356546ef3686fff1c1393acf983f95e4ced44/crates/mempool/src/transaction_queue_test_utils.rs#L26)):*
> ```XML
>     }
> 
>     pub fn complete_to_tx_queue(self) -> TransactionQueue {
> ```

I suggest renaming it to `build_transaction_queue` as it clearly shows it's creating the queue. "Complete" doesn't clearly indicate this. 



_Suggestion:_
```XML
build_transaction_queue
```
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YayFZ1ym5KW5HJZo4:-O7YayFZ1ym5KW5HJZo5:ba58yyb) ([raw file](https://github.com/starkware-libs/sequencer/blob/252356546ef3686fff1c1393acf983f95e4ced44/crates/mempool/src/transaction_queue_test_utils.rs#L82)):*
> ```XML
>     }
> 
>     fn is_default(&self) -> bool {
> ```

I think it would be clearer



_Suggestion:_
```XML
is_empty
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/977)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YaYgf3-ZbyBoxCkhg:-O7Yga8qE0NiXJJGlbGb:bnkt1cl) ([raw file](https://github.com/starkware-libs/sequencer/blob/252356546ef3686fff1c1393acf983f95e4ced44/crates/mempool/src/mempool_test.rs#L40)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Why do we check only the priority queue here? if so, the function name should be updated
</blockquote></details>

Good point, I'll rename next PR; adding the check of pending Q will fail on `unwrap()` (it's `None` since existing tests don't care about it). 
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YcfOgAXUpzT_UqeSq:-O7Yg6XsDFbO3NsadsNc:bv1k5vt) ([raw file](https://github.com/starkware-libs/sequencer/blob/252356546ef3686fff1c1393acf983f95e4ced44/crates/mempool/src/transaction_queue_test_utils.rs#L26)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I suggest renaming it to `build_transaction_queue` as it clearly shows it's creating the queue. "Complete" doesn't clearly indicate this.
</blockquote></details>

Complete means, a complete (non-partial) queue object is created; for example, the address-to-transaction metadata is added.
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YayFZ1ym5KW5HJZo4:-O7YhCIRDl2KC2UR9J7V:bsuz9gg) ([raw file](https://github.com/starkware-libs/sequencer/blob/252356546ef3686fff1c1393acf983f95e4ced44/crates/mempool/src/transaction_queue_test_utils.rs#L82)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I think it would be clearer
</blockquote></details>

Note it's not the same; default means both queues are `None`, while empty means both queues are `Some([Pending/Priority]Queue::default())`

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/977)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YcfOgAXUpzT_UqeSq:-O7Yhbh60fw2xx11poJw:b-p4j02q) ([raw file](https://github.com/starkware-libs/sequencer/blob/252356546ef3686fff1c1393acf983f95e4ced44/crates/mempool/src/transaction_queue_test_utils.rs#L26)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Complete means, a complete (non-partial) queue object is created; for example, the address-to-transaction metadata is added.
</blockquote></details>

Planning to change `From<MempoolContent> for Mempool` to `MempoolContent::complete_to_mempool` as well; requires some more thinking (mainly due to account nonces).

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/977)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YiSQgCoG9QltF65X_:-O7YiSQh-ZJT7GDgpdbw:b1ejevt) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcb8a587c44ea709cf22354ffbbf28990bf3d0b6/crates/mempool/src/transaction_queue_test_utils.rs#L72)):*
> ```XML
> 
>     pub fn build(self) -> Option<TransactionQueueContent> {
>         if self == TransactionQueueContentBuilder::default() {
> ```

Not sure if it's better than the `is_default()` option; LMK what you think.



_Code quote:_
```XML
if self == TransactionQueueContentBuilder::default()
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/977)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YlJdFBljJcd15FG_i:-O7YlJdFBljJcd15FG_j:b16p76o) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcb8a587c44ea709cf22354ffbbf28990bf3d0b6/crates/mempool/src/transaction_queue_test_utils.rs#L47)):*
> ```XML
> }
> 
> #[derive(Debug, Default, PartialEq)]
> ```

why was it added?



_Code quote:_
```XML
PartialEq
```
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YiSQgCoG9QltF65X_:-O7YkkGT4p2YCHXO1ONs:b4na03h) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcb8a587c44ea709cf22354ffbbf28990bf3d0b6/crates/mempool/src/transaction_queue_test_utils.rs#L72)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure if it's better than the `is_default()` option; LMK what you think.
</blockquote></details>

I think it's better.
How's this:



_Code snippet:_
```XML
if self.priority_queue.is_none() && self.pending_queue.is_none(){
    return None;
}
```

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/977#-:-O7Ym_eTA-uQoklFVwrj:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YlGWUDH0yckvdDc7z:-O7YlGWUDH0yckvdDc8-:bdeavht) ([raw file](https://github.com/starkware-libs/sequencer/blob/252356546ef3686fff1c1393acf983f95e4ced44/crates/mempool/src/mempool_test.rs#L67)):*
> ```XML
>             tx_queue: tx_queue_content
>                 .map(|content| content.complete_to_tx_queue())
>                 .unwrap_or_default(),
> ```

:fire: 



_Code quote:_
```XML
            tx_queue: tx_queue_content
                .map(|content| content.complete_to_tx_queue())
                .unwrap_or_default(),
```
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YcfOgAXUpzT_UqeSq:-O7YkRGm2WGwr82o61pT:b-yb6iqh) ([raw file](https://github.com/starkware-libs/sequencer/blob/252356546ef3686fff1c1393acf983f95e4ced44/crates/mempool/src/transaction_queue_test_utils.rs#L26)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Planning to change `From<MempoolContent> for Mempool` to `MempoolContent::complete_to_mempool` as well; requires some more thinking (mainly due to account nonces).
</blockquote></details>

Also `build` is already used by the builder objects,  it is a canonical name for the consuming action of the builder pattern.

This is especially true here, to stay away from mirroring the builders too much, given how similar the Content object look like the builder objects (they both have options on all the fields mostly, which is a bit awk but justified in our case I guess)
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YayFZ1ym5KW5HJZo4:-O7YfrzYE8UzXtpRnom0:b95xf83) ([raw file](https://github.com/starkware-libs/sequencer/blob/252356546ef3686fff1c1393acf983f95e4ced44/crates/mempool/src/transaction_queue_test_utils.rs#L82)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Note it's not the same; default means both queues are `None`, while empty means both queues are `Some([Pending/Priority]Queue::default())`
</blockquote></details>

Another accepted word is `dirty`, for the negated condition, that is 
```rust
if !self.is_dirty() {
    return None;
}
```
not sure which is better
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YiSQgCoG9QltF65X_:-O7YkAZL02Habj4893Wp:b-qv8mxz) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcb8a587c44ea709cf22354ffbbf28990bf3d0b6/crates/mempool/src/transaction_queue_test_utils.rs#L72)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I think it's better.
How's this:
</blockquote></details>

I like the function better, less surprises in case we add more fields to the builder, but it's pedantic a bit.
On other other hand a whole function for a test that you can streamline with PartialEq :thinking: 

Yr call I think, either can work.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/977)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YlGWUDH0yckvdDc7z:-O7Yn9Bg3WGUd7Y5yCDS:b-jldur5) ([raw file](https://github.com/starkware-libs/sequencer/blob/252356546ef3686fff1c1393acf983f95e4ced44/crates/mempool/src/mempool_test.rs#L67)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

:fire:
</blockquote></details>

:woop woop:
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YcfOgAXUpzT_UqeSq:-O7YnGH65LWL3Nezgh61:b-s2rc75) ([raw file](https://github.com/starkware-libs/sequencer/blob/252356546ef3686fff1c1393acf983f95e4ced44/crates/mempool/src/transaction_queue_test_utils.rs#L26)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Also `build` is already used by the builder objects,  it is a canonical name for the consuming action of the builder pattern.

This is especially true here, to stay away from mirroring the builders too much, given how similar the Content object look like the builder objects (they both have options on all the fields mostly, which is a bit awk but justified in our case I guess)
</blockquote></details>

Good point, thanks.
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YayFZ1ym5KW5HJZo4:-O7Ymg5pBUmNJ-TeAKji:baykcip) ([raw file](https://github.com/starkware-libs/sequencer/blob/252356546ef3686fff1c1393acf983f95e4ced44/crates/mempool/src/transaction_queue_test_utils.rs#L82)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Another accepted word is `dirty`, for the negated condition, that is 
```rust
if !self.is_dirty() {
    return None;
}
```
not sure which is better
</blockquote></details>

I don't think it well-suited here, seems more confusing to me.
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YlJdFBljJcd15FG_i:-O7YmM0M6aqGS-2_CTjs:b-x95a5s) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcb8a587c44ea709cf22354ffbbf28990bf3d0b6/crates/mempool/src/transaction_queue_test_utils.rs#L47)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why was it added?
</blockquote></details>

Look at the changes between the penultimate to last revision; in order to be able to compare to the default value.
___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YiSQgCoG9QltF65X_:-O7YmmLg6d6B0NQagimM:b-e9haco) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcb8a587c44ea709cf22354ffbbf28990bf3d0b6/crates/mempool/src/transaction_queue_test_utils.rs#L72)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I like the function better, less surprises in case we add more fields to the builder, but it's pedantic a bit.
On other other hand a whole function for a test that you can streamline with PartialEq :thinking: 

Yr call I think, either can work.
</blockquote></details>

I think the first argument is stronger, restored.
Ayelet, what do you think is better? Didn't understand your opinion. Going forward without bundling the meaning of default seems riskier.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/977)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YiSQgCoG9QltF65X_:-O7YnSvi9Q0I1Vn9cYA_:b-yzxrha) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcb8a587c44ea709cf22354ffbbf28990bf3d0b6/crates/mempool/src/transaction_queue_test_utils.rs#L72)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think the first argument is stronger, restored.
Ayelet, what do you think is better? Didn't understand your opinion. Going forward without bundling the meaning of default seems riskier.
</blockquote></details>

_Although_... we might also forget to add new fields to `is_default`. IDK...

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/977#-:-O7YpWLXBiRTrD7IzbsU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/mempool/src/transaction_queue_test_utils.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/977#-O7YiSQgCoG9QltF65X_:-O7Yp3OgB1udBDtvfz6j:b-m58hye) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcb8a587c44ea709cf22354ffbbf28990bf3d0b6/crates/mempool/src/transaction_queue_test_utils.rs#L72)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

_Although_... we might also forget to add new fields to `is_default`. IDK...
</blockquote></details>

your call

**Pull request merged**
