### PR TITLE
chore(mempool_types): add testing feature, use automock only as test

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #2159
- #2158
- #2157 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2157)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_mempool_types/Cargo.toml` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2157#-OC2ETtJ5o01g9W1V_sS:-OC2ETtJ5o01g9W1V_sT:bghxr81) ([raw file](https://github.com/starkware-libs/sequencer/blob/412782354f6aae063da4fdaf4f57c0643114e947/crates/starknet_mempool_types/Cargo.toml#L26)):*
> ```TOML
> [dev-dependencies]
> # Enable self with "testing" feature in tests.
> starknet_mempool_types = { workspace = true, features = ["testing"] }
> ```

Why do we need this?



_Code quote:_
```TOML
# Enable self with "testing" feature in tests.
starknet_mempool_types = { workspace = true, features = ["testing"] }
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2157)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

___
*[`crates/starknet_mempool_types/Cargo.toml` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2157#-OC2ETtJ5o01g9W1V_sS:-OC2_skj8WVmkF_F6xz-:b-mwvb7s) ([raw file](https://github.com/starkware-libs/sequencer/blob/412782354f6aae063da4fdaf4f57c0643114e947/crates/starknet_mempool_types/Cargo.toml#L26)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why do we need this?
</blockquote></details>

This enables all the `testing` features when running in `test` mode. In this specific case, adds the `mockall`.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2157#-:-OC311Cn5WulYr4J6-Ip:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#2158](https://github.com/starkware-libs/sequencer/pull/2158)

**Pull request closed without merging**
