### PR TITLE
refactor(blockifier_reexecution): refactor https tests to get url and block number

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1900)* status: all files reviewed, 7 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-OBKaa66CELwYz6kCytl:-OBKaa66CELwYz6kCytm:b-ctrz4e) (no related file):*
IIUC, you have changed what we test in these tests.
Can you explain exactly what are we testing now?
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-OBKazce8AEoKMU2fO0G:-OBKazce8AEoKMU2fO0H:b-quypy0) ([raw file](https://github.com/starkware-libs/sequencer/blob/9c61e2fd11b0a82417f9d4e13ae1e378fcdeac11/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L117)):*
> ```XML
>     let block_number_int = test_block_number.0;
>     let expected_tx_hashes: Vec<String> = serde_json::from_value(read_json_file(
>         format!("block_{block_number_int}/tx_hashes_block_{block_number_int}.json").as_str(),
> ```

should this JSON be deleted? does it have any other use cases?



_Code quote:_
```XML
"block_{block_number_int}/tx_hashes_block_{block_number_int}.json"
```
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-OBKa6ziErFQeqy4j9Is:-OBKa6ziErFQeqy4j9It:b-rub4tk) ([raw file](https://github.com/starkware-libs/sequencer/blob/791912142d41de2d45032ef031db5ab803b0107b/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L11)):*
> ```XML
> /// - `TEST_URL`: URL of the RPC server. If not provided, a free public RPC URL is used, which
> ///   may cause sporadic errors due to request limits.
> /// - `BLOCK_NUMBER`: Block number for testing. If not provided, defaults to the latest block.
> ```

why latest block? why not EXAMPLE_BLOCK_NUMBER?



_Code quote:_
```XML
 `BLOCK_NUMBER`: Block number for testing. If not provided, defaults to the latest block.
```
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-OBKaiYCCmzAW-u5ieBg:-OBKaiYCCmzAW-u5ieBh:b-32p4fv) ([raw file](https://github.com/starkware-libs/sequencer/blob/791912142d41de2d45032ef031db5ab803b0107b/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L81)):*
> ```XML
>             raw_block_number.parse().expect("Failed to parse block number"),
>         )),
>         Err(_) => BlockId::Latest,
> ```

why not EXAMPLE_BLOCK_NUMBER?



_Code quote:_
```XML
Err(_) => BlockId::Latest,
```
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-OBKaqYJBOC6CM6RWhbW:-OBKaqYJBOC6CM6RWhbX:bp925vq) ([raw file](https://github.com/starkware-libs/sequencer/blob/791912142d41de2d45032ef031db5ab803b0107b/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L104)):*
> ```XML
> pub fn test_block_number(test_state_reader: TestStateReader) -> BlockNumber {
>     test_state_reader.get_block_info().unwrap().block_number
> }
> ```

why this change? why not assert the response number is equal to the expected number?



_Code quote:_
```XML
#[fixture]
pub fn test_block_number(test_state_reader: TestStateReader) -> BlockNumber {
    test_state_reader.get_block_info().unwrap().block_number
}
```
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 261 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-OBKb6c9BA0MhNP5WTjo:-OBKb6c9BA0MhNP5WTjp:b-45g1ym) ([raw file](https://github.com/starkware-libs/sequencer/blob/791912142d41de2d45032ef031db5ab803b0107b/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L261)):*
> ```XML
> ) {
>     test_state_reader.get_old_block_hash(last_constructed_block).unwrap();
> }
> ```

you can use the HTTP reader to also read the block hash 10 blocks back and compare the hashes



_Code quote:_
```XML
    test_state_reader.get_old_block_hash(last_constructed_block).unwrap();
}
```
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 277 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-OBKaXDi-sG0oIr62_fU:-OBKaXDi-sG0oIr62_fV:b-eq1qnx) ([raw file](https://github.com/starkware-libs/sequencer/blob/791912142d41de2d45032ef031db5ab803b0107b/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L277)):*
> ```XML
>         state_reader_after_replace_class.get_class_hash_at(stark_gate_address).unwrap()
>     );
> }
> ```

why is this special case interesting in HTTP tests?



_Code quote:_
```XML
/// Test that the contract class hash is different before and after the class is replaced
#[rstest]
pub fn test_contract_change_after_replace_class() {
    let state_reader_before_replace_class = TestStateReader::new_for_testing(BlockNumber(620978));
    let state_reader_after_replace_class = TestStateReader::new_for_testing(BlockNumber(630000));

    // The stark gate contract address. Replace class between the two blocks.
    let stark_gate_address =
        contract_address!("0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7");

    assert_ne!(
        state_reader_before_replace_class.get_class_hash_at(stark_gate_address).unwrap(),
        state_reader_after_replace_class.get_class_hash_at(stark_gate_address).unwrap()
    );
}
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1900)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-OBKaa66CELwYz6kCytl:-OBKu-8LCZk6uW1JY8_A:bgevm4n) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

IIUC, you have changed what we test in these tests.
Can you explain exactly what are we testing now?
</blockquote></details>

To set up a re-execution test with a specified block number and RPC URL, this test file includes a unit test to verify that your RPC URL is functioning correctly. The goal of setting the default `Block_Number` to "latest" is to allow this test to run periodically, confirming that the RPC reader is consistently able to fetch the required data for re-execution.
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-OBKa6ziErFQeqy4j9Is:-OBL8vDI4_bfIB9BM422:bl40ina) ([raw file](https://github.com/starkware-libs/sequencer/blob/791912142d41de2d45032ef031db5ab803b0107b/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L11)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why latest block? why not EXAMPLE_BLOCK_NUMBER?
</blockquote></details>

Discussed 
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-OBKaiYCCmzAW-u5ieBg:-OBL8teHD09Z0xqQN4zn:bgpxg56) ([raw file](https://github.com/starkware-libs/sequencer/blob/791912142d41de2d45032ef031db5ab803b0107b/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L81)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not EXAMPLE_BLOCK_NUMBER?
</blockquote></details>

Discussed
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-OBKaqYJBOC6CM6RWhbW:-OBLEeAB79WY_L9lK2u2:b-5luw55) ([raw file](https://github.com/starkware-libs/sequencer/blob/791912142d41de2d45032ef031db5ab803b0107b/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L104)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why this change? why not assert the response number is equal to the expected number?
</blockquote></details>

We don't know which number to expect if it is called on the latest block
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-OBKazce8AEoKMU2fO0G:-OBLFxT7-g4fbr1Y4Qxv:bkq0npy) ([raw file](https://github.com/starkware-libs/sequencer/blob/9c61e2fd11b0a82417f9d4e13ae1e378fcdeac11/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L117)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

should this JSON be deleted? does it have any other use cases?
</blockquote></details>

Yes it should 
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 261 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-OBKb6c9BA0MhNP5WTjo:-OBKw3MD7yVCqLEJPCts:bqtjo50) ([raw file](https://github.com/starkware-libs/sequencer/blob/791912142d41de2d45032ef031db5ab803b0107b/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L261)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you can use the HTTP reader to also read the block hash 10 blocks back and compare the hashes
</blockquote></details>

this is what how `get_old_block_hash` works
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 277 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-OBKaXDi-sG0oIr62_fU:-OBKvqv2DxpCxgapz7a-:b-8omoae) ([raw file](https://github.com/starkware-libs/sequencer/blob/791912142d41de2d45032ef031db5ab803b0107b/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L277)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this special case interesting in HTTP tests?
</blockquote></details>

its possible bug in the RPC server

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1900)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 277 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-OBKaXDi-sG0oIr62_fU:-OBLHdp39WMzeyyTWiPz:b-ddr3mp) ([raw file](https://github.com/starkware-libs/sequencer/blob/791912142d41de2d45032ef031db5ab803b0107b/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L277)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

its possible bug in the RPC server
</blockquote></details>

ok, why block 630000 and not 620979?

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1900)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 277 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-OBKaXDi-sG0oIr62_fU:-OBLRAJg4G8gkl76TJ3J:b9sfdmt) ([raw file](https://github.com/starkware-libs/sequencer/blob/791912142d41de2d45032ef031db5ab803b0107b/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L277)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ok, why block 630000 and not 620979?
</blockquote></details>

There were replace class syscall in block 629092
so I just chose 2 blocks between it

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1900)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 277 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-OBKaXDi-sG0oIr62_fU:-OBLYekc1uD_VMSABxhU:b-9zs3zm) ([raw file](https://github.com/starkware-libs/sequencer/blob/791912142d41de2d45032ef031db5ab803b0107b/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L277)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

There were replace class syscall in block 629092
so I just chose 2 blocks between it
</blockquote></details>

please choose the specific blocks, so it's easy to understand which block we are testing.
also, why make this an HTTP test, and not a regular reexecution test, on block 629092?
there was a specific deserialization bug?

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1900)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 277 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-OBKaXDi-sG0oIr62_fU:-OBLZpmMBELTvQ_tXsh_:bnd5zkk) ([raw file](https://github.com/starkware-libs/sequencer/blob/791912142d41de2d45032ef031db5ab803b0107b/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L277)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please choose the specific blocks, so it's easy to understand which block we are testing.
also, why make this an HTTP test, and not a regular reexecution test, on block 629092?
there was a specific deserialization bug?
</blockquote></details>

What do you mean by regular re-execution tests? This isn't about test deserialization. It simply verifies that the RPC URL returns a different class hash if the class hash changes.

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1900)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 277 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-OBKaXDi-sG0oIr62_fU:-OBLboKs38HNlaVaAM3L:b-ay99q) ([raw file](https://github.com/starkware-libs/sequencer/blob/791912142d41de2d45032ef031db5ab803b0107b/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L277)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this should be verified when reexecuting a block with a replace_class - it should appear in the state diff.
we shouldn't be testing the RPC server here - it's not our code. we only care about object deserialization here, not the values themselves
</blockquote></details>

ok, so I'll delete this test

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1900#-:-OBLekA46VxuW1l2NSrR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
