### PR TITLE
chore(consensus): add documentation to consensus crate

### PR DESCRIPTION
**Pull request by matan-starkware**

### CODE REVIEW

**Comment by matan-starkware** [comment]
* **#2626** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2626?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2626?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by asmaastarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2626)* status: all files reviewed, 9 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2626#-OEEbQdG5QPIMgNzT8kE:-OEEbQdG5QPIMgNzT8kF:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dd1c7bb4df2e14c3d53581df7f891b1b1a2eb77/crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs#L35)):*
> ```XML
> 
> impl NetworkReceiver {
>     /// Create a new NetworkReceiver.
> ```





_Suggestion:_
```XML
/// Creates a new NetworkReceiver.
```
___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2626#-OEEbojj7EehmB2ttQ1a:-OEEbojj7EehmB2ttQ1b:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dd1c7bb4df2e14c3d53581df7f891b1b1a2eb77/crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs#L39)):*
> ```XML
>     /// Inputs:
>     /// - `broadcasted_messages_receiver`: The receiver to listen to.
>     /// - `cache_size`: A small cache risks repeat messages all being handled the same way.
> ```





_Suggestion:_
```XML
 /// - `cache_size`: Determines the size of the cache. A smaller cache increases the risk of handling 
 ///   repeated messages in the same way.
```
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 5 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2626#-OEEXawO2wmlUNTfKdZA:-OEEXawO2wmlUNTfKdZB:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dd1c7bb4df2e14c3d53581df7f891b1b1a2eb77/crates/sequencing/papyrus_consensus/src/manager.rs#L5)):*
> ```XML
> //! [`run_consensus`] - This is the primary entrypoint for running the consensus component.
> //!
> //! [`MultiHeightManager`] - Run consensus repeatedly across different heights
> ```





_Suggestion:_
```XML
//! [`MultiHeightManager`] - Runs consensus repeatedly across different heights using
```
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2626#-OEEYL8t9KECK6YdHMB1:-OEEYL8t9KECK6YdHMB2:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dd1c7bb4df2e14c3d53581df7f891b1b1a2eb77/crates/sequencing/papyrus_consensus/src/manager.rs#L48)):*
> ```XML
> /// - `validator_id`: The ID of this node.
> /// - `consensus_delay`: The delay before starting consensus. There to allow the network to connect
> ///   to peers.
> ```





_Suggestion:_
```XML
/// - `consensus_delay`: The delay before starting consensus, allowing time the network to connect
///   to peers.
```
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2626#-OEEYcjRD8DAPOImCJ2E:-OEEYcjRD8DAPOImCJ2F:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dd1c7bb4df2e14c3d53581df7f891b1b1a2eb77/crates/sequencing/papyrus_consensus/src/manager.rs#L51)):*
> ```XML
> /// - `timeouts`: The timeouts for the consensus algorithm.
> /// - `inbound_vote_receiver`: The channels to receive votes from the network. These are self
> ///   contained messages.
> ```





_Suggestion:_
```XML
/// - `vote_receiver`: The channels to receive votes from the network. These are self
///   contained messages.
```
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2626#-OEEYwCW9jGUrRWZ6emp:-OEEYwCW9jGUrRWZ6emq:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dd1c7bb4df2e14c3d53581df7f891b1b1a2eb77/crates/sequencing/papyrus_consensus/src/manager.rs#L53)):*
> ```XML
> ///   contained messages.
> /// - `inbound_proposal_receiver`: The channel to receive proposals from the network. Proposals are
> ///   represented as streams (ProposalInit, Content.*, ProposalFin).
> ```





_Suggestion:_
```XML
/// - `proposal_receiver`: The channel to receive proposals from the network. Proposals are
///   represented as streams (ProposalInit, Content.*, ProposalFin).
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2626#-OEEd4Nb3WduaJshJvf0:-OEEd4Nb3WduaJshJvf1:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dd1c7bb4df2e14c3d53581df7f891b1b1a2eb77/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L154)):*
> ```XML
> /// - Timeouts: the SM returns an event timeout, but SHC then maps that to a task which can be run
> ///   by the Manager. The manager though unaware of the specific task as it has minimal consensus
> ///   logic.
> ```





_Suggestion:_
```XML
/// Represents a single height of consensus. It is responsible for mapping between the idealized
/// view of consensus represented in the StateMachine and the real world implementation.
///
/// Example:
/// - Timeouts: the SM returns an event timeout, but SHC then maps that to a task which can be run
///   by the Manager. The manager though unaware of the specific task as it has minimal consensus
///   logic.
```
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2626#-OEEWVvB8qpiGLS1fwV7:-OEEWVvC3L_--ly1niIy:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dd1c7bb4df2e14c3d53581df7f891b1b1a2eb77/crates/sequencing/papyrus_consensus/src/lib.rs#L18)):*
> ```XML
> //! Consensus can run in two modes:
> //! 1. Observer - receive consensus messages and update the node when a decision is reached.
> //! 2. Active - in addition to receiving messages the node can send messages to the network.
> ```





_Suggestion:_
```XML
//! Consensus operates in two modes:
//! 1. Observer - Receives consensus messages and updates the node when a decision is reached.
//! 2. Active - In addition to receiving messages, the node can also send messages to the network.
```
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2626#-OEEWyW8DvMols3sKp4G:-OEEWyW9ABh5859xRK4o:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dd1c7bb4df2e14c3d53581df7f891b1b1a2eb77/crates/sequencing/papyrus_consensus/src/lib.rs#L21)):*
> ```XML
> //!
> //! Observer mode is lower latency than sync, since we process Proposals and votes as they happen,
> //! not after the decision is made.
> ```





_Suggestion:_
```XML
//! Observer mode offers lower latency compared to sync, as Proposals and votes are processed in real-time
//! rather than after a decision has been made.
```

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2626)* status: 5 of 6 files reviewed, 9 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2626#-OEEbQdG5QPIMgNzT8kE:-OEEvIdHBNqfO_lWdoH8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dd1c7bb4df2e14c3d53581df7f891b1b1a2eb77/crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs#L35)):*
> ```XML
> 
> impl NetworkReceiver {
>     /// Create a new NetworkReceiver.
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2626#-OEEbojj7EehmB2ttQ1a:-OEEvIxJ09ruLu0AuAMc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dd1c7bb4df2e14c3d53581df7f891b1b1a2eb77/crates/sequencing/papyrus_consensus/src/simulation_network_receiver.rs#L39)):*
> ```XML
>     /// Inputs:
>     /// - `broadcasted_messages_receiver`: The receiver to listen to.
>     /// - `cache_size`: A small cache risks repeat messages all being handled the same way.
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2626#-OEEd4Nb3WduaJshJvf0:-OEEvOsk3-_MugOEeaOX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dd1c7bb4df2e14c3d53581df7f891b1b1a2eb77/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L154)):*
> ```XML
> /// - Timeouts: the SM returns an event timeout, but SHC then maps that to a task which can be run
> ///   by the Manager. The manager though unaware of the specific task as it has minimal consensus
> ///   logic.
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2626#-OEEYL8t9KECK6YdHMB1:-OEEtbLPCFQOg3lnOm9g:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dd1c7bb4df2e14c3d53581df7f891b1b1a2eb77/crates/sequencing/papyrus_consensus/src/manager.rs#L48)):*
> ```XML
> /// - `validator_id`: The ID of this node.
> /// - `consensus_delay`: The delay before starting consensus. There to allow the network to connect
> ///   to peers.
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2626#-OEEYcjRD8DAPOImCJ2E:-OEEthUb1V_xEAeeM1x7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dd1c7bb4df2e14c3d53581df7f891b1b1a2eb77/crates/sequencing/papyrus_consensus/src/manager.rs#L51)):*
> ```XML
> /// - `timeouts`: The timeouts for the consensus algorithm.
> /// - `inbound_vote_receiver`: The channels to receive votes from the network. These are self
> ///   contained messages.
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2626#-OEEYwCW9jGUrRWZ6emp:-OEEthnN5DmHZ8-IYRmU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dd1c7bb4df2e14c3d53581df7f891b1b1a2eb77/crates/sequencing/papyrus_consensus/src/manager.rs#L53)):*
> ```XML
> ///   contained messages.
> /// - `inbound_proposal_receiver`: The channel to receive proposals from the network. Proposals are
> ///   represented as streams (ProposalInit, Content.*, ProposalFin).
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2626#-OEEWVvB8qpiGLS1fwV7:-OEEtH7P3PjcBNvCNcZR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dd1c7bb4df2e14c3d53581df7f891b1b1a2eb77/crates/sequencing/papyrus_consensus/src/lib.rs#L18)):*
> ```XML
> //! Consensus can run in two modes:
> //! 1. Observer - receive consensus messages and update the node when a decision is reached.
> //! 2. Active - in addition to receiving messages the node can send messages to the network.
> ```

Done.
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2626#-OEEWyW8DvMols3sKp4G:-OEEtHip3DL9CTMVxwf8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dd1c7bb4df2e14c3d53581df7f891b1b1a2eb77/crates/sequencing/papyrus_consensus/src/lib.rs#L21)):*
> ```XML
> //!
> //! Observer mode is lower latency than sync, since we process Proposals and votes as they happen,
> //! not after the decision is made.
> ```

Done.

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2626#-:-OEEwPU725sOsnSteRMA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by asmaastarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2626)* status: 7 of 8 files reviewed, all discussions resolved

**Review by asmaastarkware — APPROVED** [review]
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2626)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Comment by matan-starkware** [comment]
### Merge activity

* **Dec 17, 8:14 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2626).

**Pull request merged**
