### PR TITLE
refactor(gateway): remove usage of AppState

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1978)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/gateway.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1978#-OBVKrGLEQArye6Gsjjl:-OBVKrGLEQArye6Gsjjm:b-z7kjhp) ([raw file](https://github.com/starkware-libs/sequencer/blob/39c089d3ea2ecb9eb0bf122f875f1a633236c447/crates/gateway/src/gateway.rs#L109)):*
> ```XML
>             state_reader_factory: gateway.state_reader_factory.clone(),
>             gateway_compiler: gateway.gateway_compiler.clone(),
>             chain_info: gateway.chain_info.clone(),
> ```

Must these be clones? Can we pass a reference to a singular instance of each and activate its methods?



_Code quote:_
```XML
            stateless_tx_validator: gateway.stateless_tx_validator.clone(),
            stateful_tx_validator: gateway.stateful_tx_validator.clone(),
            state_reader_factory: gateway.state_reader_factory.clone(),
            gateway_compiler: gateway.gateway_compiler.clone(),
            chain_info: gateway.chain_info.clone(),
```

**Comment by yair-starkware** [comment]
*[`crates/gateway/src/gateway.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1978#-OBVKrGLEQArye6Gsjjl:-OBVLaoy18vjo-O55wJO:b-87u65v) ([raw file](https://github.com/starkware-libs/sequencer/blob/39c089d3ea2ecb9eb0bf122f875f1a633236c447/crates/gateway/src/gateway.rs#L109)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Must these be clones? Can we pass a reference to a singular instance of each and activate its methods?
</blockquote></details>

No, because spawned tasks require ownership on the data they use

**Comment by yair-starkware** [comment]
*[`crates/gateway/src/gateway.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1978#-OBVKrGLEQArye6Gsjjl:-OBVLmUX7vjBEqO6nhVd:b-vswu0i) ([raw file](https://github.com/starkware-libs/sequencer/blob/39c089d3ea2ecb9eb0bf122f875f1a633236c447/crates/gateway/src/gateway.rs#L109)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

No, because spawned tasks require ownership on the data they use
</blockquote></details>

Note they are in `Arc`

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1978)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5, @dafnamatsry, and @Yael-Starkware)

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1978)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1978#-OBVMUaV2fAuFoF0ca87:-OBVMUaV2fAuFoF0ca88:b-r14q8d) ([raw file](https://github.com/starkware-libs/sequencer/blob/39c089d3ea2ecb9eb0bf122f875f1a633236c447/crates/gateway/src/gateway_test.rs#L62)):*
> ```XML
>     state_reader_factory: TestStateReaderFactory,
>     mock_mempool_client: MockMempoolClient,
> }
> ```

Why do we need this struct?
Just so there will be a thing holding all of the structs so that mock_mempool_client can use them?



_Code quote:_
```XML
struct MockDependencies {
    config: GatewayConfig,
    compiler: GatewayCompiler,
    state_reader_factory: TestStateReaderFactory,
    mock_mempool_client: MockMempoolClient,
}
```

**Comment by yair-starkware** [comment]
*[`crates/gateway/src/gateway_test.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1978#-OBVMUaV2fAuFoF0ca87:-OBVN1hl0_fBcLQeBvJh:bsc4v1c) ([raw file](https://github.com/starkware-libs/sequencer/blob/39c089d3ea2ecb9eb0bf122f875f1a633236c447/crates/gateway/src/gateway_test.rs#L62)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Why do we need this struct?
Just so there will be a thing holding all of the structs so that mock_mempool_client can use them?
</blockquote></details>

It extracts the code that handles creating the gateway outside of tests.
Without it, we would need to get all the components, mock, and assemble a gateway in each test.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1978#-:-OBVhl9_4Z_mrMbEYOzA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/gateway.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1978#-OBVhP1wEVfdTmBTXehq:-OBVhP1wEVfdTmBTXehr:b-bn7ke5) ([raw file](https://github.com/starkware-libs/sequencer/blob/39c089d3ea2ecb9eb0bf122f875f1a633236c447/crates/gateway/src/gateway.rs#L49)):*
> ```XML
>     ) -> Self {
>         Self {
>             config: config.clone(),
> ```

The struct `GatewayConfig` should implement `Copy`.  Non-blocking.



_Suggestion:_
```XML
config,
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1978)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1978#-OBVhP1wEVfdTmBTXehq:-OBVprfjDaats0HJOUsD:b-xo6ja8) ([raw file](https://github.com/starkware-libs/sequencer/blob/39c089d3ea2ecb9eb0bf122f875f1a633236c447/crates/gateway/src/gateway.rs#L49)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The struct `GatewayConfig` should implement `Copy`.  Non-blocking.
</blockquote></details>

out of scope of PR, need to change inner structs

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1978)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5, @dafnamatsry, and @Yael-Starkware)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1978)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @alonh5, @dafnamatsry, and @Yael-Starkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1978)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5, @dafnamatsry, and @Yael-Starkware)

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1978)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5, @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/starknet_gateway/src/gateway.rs` line 92 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1978#-OBZve_o-aQIRpfsVS-b:-OBdkKxd3C-vhiPXf2cZ:bl588bq) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7edd4cb58382a8572b759b3c4042bc3f5db9525/crates/starknet_gateway/src/gateway.rs#L92)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you explain here why it must be blocking?
</blockquote></details>

Do you mean why CPU-bounded operations need to be in `spawn_blocking` or what the function is doing that is CPU-bounded?

For both I don't think it is a good thing to doc here
___
*[`crates/starknet_gateway/src/gateway_test.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1978#-OBZu0Iq-XqNFChq95wu:-OBdku56EJt_v1naH3Rt:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7edd4cb58382a8572b759b3c4042bc3f5db9525/crates/starknet_gateway/src/gateway_test.rs#L65)):*
> ```XML
> 
> impl MockDependencies {
>     fn get_gateway(self) -> Gateway {
> ```

done

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1978)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/starknet_gateway/src/gateway.rs` line 92 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1978#-OBZve_o-aQIRpfsVS-b:-OBduzDu-b3w6kfs90IT:b-wn6rp1) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7edd4cb58382a8572b759b3c4042bc3f5db9525/crates/starknet_gateway/src/gateway.rs#L92)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Do you mean why CPU-bounded operations need to be in `spawn_blocking` or what the function is doing that is CPU-bounded?

For both I don't think it is a good thing to doc here
</blockquote></details>

The word blocking is used a lot here in names and comments, and (for me) it raises more questions than it gives answers. Blocking sounds like it logically has to be completed before continuing with other tasks, but if I understood you correctly, that's not exactly true.
Add a comment like: `/// CPU-intensive transaction processing, spawned in a blocking thread to run exclusively until completion.` (from chat gpt).

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1978#-:-OBemrSm4vtDeIvOUDNr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/starknet_gateway/src/gateway.rs` line 92 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1978#-OBZve_o-aQIRpfsVS-b:-OBejs6C7Q-br0iidQD0:bwv8g29) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7edd4cb58382a8572b759b3c4042bc3f5db9525/crates/starknet_gateway/src/gateway.rs#L92)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Done, wdyt?
</blockquote></details>

Ah okay, see only now I understand haha. I thought it was the opposite. Looks good, added a small suggestion.
___
*[`crates/starknet_gateway/src/gateway.rs` line 93 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1978#-OBem5VsBo1ZX6C6NMpc:-OBem5VtAwlGFtEkVbxs:b71v4ph) ([raw file](https://github.com/starkware-libs/sequencer/blob/f4f17c9f804650c4e1aa4f946f05348f5d717da6/crates/starknet_gateway/src/gateway.rs#L93)):*
> ```XML
> 
> /// CPU-intensive transaction processing, spawned in a blocking thread to avoid blocking the tokio
> /// runtime.
> ```

The less knowledge required to understand this comment, the better.



_Suggestion:_
```XML
/// CPU-intensive transaction processing, spawned in a blocking thread to avoid blocking other tasks
/// from running.
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1978)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @alonh5, @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/starknet_gateway/src/gateway.rs` line 93 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1978#-OBem5VsBo1ZX6C6NMpc:-OBeuzDQE35tEnVltTtc:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/f4f17c9f804650c4e1aa4f946f05348f5d717da6/crates/starknet_gateway/src/gateway.rs#L93)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

The less knowledge required to understand this comment, the better.
</blockquote></details>

done

**Pull request merged**
