### PR TITLE
refactor(starknet_mempool): share code of queues combination in tests

### PR DESCRIPTION
**Pull request by ayeletstarkware**

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2800)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2800#-OET0_MA7vrpD_9dONJy:-OET0_MBCAFdc4G1OdjZ:bjt8pm1) (no related file):*
See the comment in the previous PR. I think most of the function code can be shared. You can also reorder it to add the txs at the beginning or end for convenience.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2800)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2800#-OET0_MA7vrpD_9dONJy:-OETjm7S4ndBJibFCMy5:b-39g5g6) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

See the comment in the previous PR. I think most of the function code can be shared. You can also reorder it to add the txs at the beginning or end for convenience.
</blockquote></details>

Please review #2816 and let me know if anything else is needed beyond this and that PR.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2800)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2800#-OET0_MA7vrpD_9dONJy:-OETtNS45tYiTvKFK5zt:bcwjuhk) (no related file):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Please review #2816 and let me know if anything else is needed beyond this and that PR.
</blockquote></details>

See the comment in that PR. If it can be moved to the shared function, this PR can be closed.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2800)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2800#-OET0_MA7vrpD_9dONJy:-OEU7xPs7QkOzrkXl2E4:b-896fix) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

See the comment in that PR. If it can be moved to the shared function, this PR can be closed.
</blockquote></details>

Done.

**Pull request closed without merging**
