### PR TITLE
build: move local deps to root toml

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
commit-id:c7e2f0b9

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/362)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/blockifier/Cargo.toml` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/362#-O3lK8U21H-jEfL2r1PK:-O3lK8U21H-jEfL2r1PL:bc8v4eg) ([raw file](https://github.com/starkware-libs/sequencer/blob/9e7211c3cc5e0c4274018a1f719e58ac8380422c/crates/blockifier/Cargo.toml#L41)):*
> ```TOML
> num-traits.workspace = true
> once_cell.workspace = true
> papyrus_config = { workspace = true, version = "0.4.0-rc.0" }
> ```

version should be controlled by root cargo toml



_Suggestion:_
```TOML
papyrus_config.workspace = true
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/362)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/Cargo.toml` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/362#-O3lK8U21H-jEfL2r1PK:-O3lKqLW3seOoetVd1SH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9e7211c3cc5e0c4274018a1f719e58ac8380422c/crates/blockifier/Cargo.toml#L41)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

version should be controlled by root cargo toml
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/362#-:-O3lLSpbEG6B01-VIKce:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/362)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
