### PR TITLE
feat(papyrus_p2p_sync): handle internal block in datastreambuilder

### PR DESCRIPTION
**Pull request by eitanm-starkware**

### CODE REVIEW

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2589)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-ODfb6tj0SsvByvgZAoE:-ODfku2V86T_T37vjbsd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/68c29cf67e45bc8117a3646f2d3467a2a3f29a4d/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L107)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Do this before you send the query. not after
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-ODfbhPaDgpE828RmtHJ:-ODfmrc38yqgtChp1jE4:b6ptgcu) ([raw file](https://github.com/starkware-libs/sequencer/blob/68c29cf67e45bc8117a3646f2d3467a2a3f29a4d/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L107)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Try to extract all of this to a function. It can be named get_internal_block and the argument should be the hashmap and the block number
</blockquote></details>

Done.. look for load_internal_blocks
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-ODfb2Ws7B19NcTYHn7x:-ODfkuLC8CsLU8D0_tBH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/68c29cf67e45bc8117a3646f2d3467a2a3f29a4d/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L108)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You do not want to await here. You want to use now_or_never and if it returns None to go back to sending the query
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-ODfbT7u6lwIZnNPfoH5:-ODfkxz60D7BP4RR9mrt:b-bhkkw9) ([raw file](https://github.com/starkware-libs/sequencer/blob/68c29cf67e45bc8117a3646f2d3467a2a3f29a4d/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L117)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think that if you got an internal block you should yield it and continue the outer loop
</blockquote></details>

Done. we discussed the design in person

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2589)* status: all files reviewed, 4 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-ODfnTJH0a6Qua65Moj-:-ODfnTJH0a6Qua65Moj0:b-bsubxx) ([raw file](https://github.com/starkware-libs/sequencer/blob/3efac6b67a676f5e13bf081f4e47b7f9b2ab479c/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L60)):*
> ```XML
>         internal_blocks_received: &mut HashMap<BlockNumber, Self::Output>,
>         internal_block_receiver: &mut Option<Receiver<(BlockNumber, Self::Output)>>,
>         current_block_number: &BlockNumber,
> ```

Receive by value as BlockNumber derives Copy
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-ODfnHv9B0AA2IrgmWZi:-ODfnHv9B0AA2IrgmWZj:b-5xvh1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/3efac6b67a676f5e13bf081f4e47b7f9b2ab479c/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L64)):*
> ```XML
>         if let Some(internal_block_receiver) = internal_block_receiver {
>             while let Some((block_number, block_data)) =
>                 internal_block_receiver.next().now_or_never().flatten()
> ```

You should expect (unwrap) the inner option instead of flattening
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-ODfqVdXDdJ-PcvqQfqk:-ODfqVdXDdJ-PcvqQfql:b-1gv90n) ([raw file](https://github.com/starkware-libs/sequencer/blob/3efac6b67a676f5e13bf081f4e47b7f9b2ab479c/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L67)):*
> ```XML
>             {
>                 if &block_number >= current_block_number {
>                     internal_blocks_received.insert(block_number, block_data);
> ```

The reason I originally wrote get_internal_block and not load_internal_blocks is that I want to stop the function if block_number is equal to current_block_number

You can still do it here and not load everything, but that makes the function unclear
Plus, IMO it's best if all the hashmap logic sits here so that if we decide to use something else we only need to change this function and maybe the initialization of the map
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 133 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-ODfo3Zh-PyR3hHXeluo:-ODfo3Zh-PyR3hHXelup:be9801s) ([raw file](https://github.com/starkware-libs/sequencer/blob/3efac6b67a676f5e13bf081f4e47b7f9b2ab479c/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L133)):*
> ```XML
>                     if let Some(block_data) = internal_blocks_received.remove(&current_block_number) {
>                         yield Ok(Box::<dyn BlockData>::from(Box::new(block_data)));
>                         current_block_number = current_block_number.unchecked_next();
> ```

As discussed, let's keep this check just before each query and continue the outer loop

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2589)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 133 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-ODfo3Zh-PyR3hHXeluo:-ODjji1H83eNBJh5qyV-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3efac6b67a676f5e13bf081f4e47b7f9b2ab479c/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L133)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

As discussed, let's keep this check just before each query and continue the outer loop
</blockquote></details>

Done.

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2589)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-ODfnTJH0a6Qua65Moj-:-ODk6bZSCWpkcH5raK8K:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3efac6b67a676f5e13bf081f4e47b7f9b2ab479c/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L60)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Receive by value as BlockNumber derives Copy
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-ODfnHv9B0AA2IrgmWZi:-ODkc1PpCEW8liurQedI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3efac6b67a676f5e13bf081f4e47b7f9b2ab479c/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L64)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You should expect (unwrap) the inner option instead of flattening
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-ODfqVdXDdJ-PcvqQfqk:-ODkfHTYEaDPJGWHL6gQ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3efac6b67a676f5e13bf081f4e47b7f9b2ab479c/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L67)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

The reason I originally wrote get_internal_block and not load_internal_blocks is that I want to stop the function if block_number is equal to current_block_number

You can still do it here and not load everything, but that makes the function unclear
Plus, IMO it's best if all the hashmap logic sits here so that if we decide to use something else we only need to change this function and maybe the initialization of the map
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2589)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 57 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-OESmhyt7xBVrDeO7QGI:-OESmhyt7xBVrDeO7QGJ:be6zdxp) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb2947f182d487f2fa532fac08a99cbb8fc2e9bb/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L57)):*
> ```XML
>     fn get_start_block_number(storage_reader: &StorageReader) -> Result<BlockNumber, StorageError>;
> 
>     fn get_internal_blocks(
> ```

no need for plural
maybe get_current_internal_block or get_internal_block_by_number or get_internal_block_at
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 65 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-OESn1pC-VUN-eRdLng8:-OESn1pC-VUN-eRdLng9:b-mir4y5) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb2947f182d487f2fa532fac08a99cbb8fc2e9bb/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L65)):*
> ```XML
>             return Some(block);
>         }
>         if let Some(internal_block_receiver) = internal_block_receiver {
> ```

Consider using let else instead of if let to remove 1 indentation to all the code below
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 69 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-OESmdK34FS0OV9iOFLT:-OESmdK34FS0OV9iOFLU:b-6rup3z) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb2947f182d487f2fa532fac08a99cbb8fc2e9bb/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L69)):*
> ```XML
>                 .next()
>                 .now_or_never()
>                 .map(|now_or_never_res| now_or_never_res.expect("internal block receiver closed"))
> ```

Capitalization
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 133 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-OESo5O67cq69UQWGQED:-OESo5O67cq69UQWGQEE:b-a40rfw) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb2947f182d487f2fa532fac08a99cbb8fc2e9bb/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L133)):*
> ```XML
>                 }
>                 // TODO(shahak): Use the report callback.
>                 let mut client_response_manager = sqmr_sender
> ```

If current_block_number surpassed end_block_number you're sending an empty query here.
You can fix it by either adding a small if or continuing the outer loop after you yield an internal block

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2589)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 173 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-OESodg41zRulcTTxH5E:-OESodg41zRulcTTxH5F:bl22gvn) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb2947f182d487f2fa532fac08a99cbb8fc2e9bb/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L173)):*
> ```XML
>                     current_block_number = current_block_number.unchecked_next();
>                 }
>                 if stop_sync_at_block_number.is_some_and(|stop_sync_at_block_number| {
> ```

Why did you made this change (and the change above regarding stop_sync_at_block_number)

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2589)* status: all files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 57 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-OESmhyt7xBVrDeO7QGI:-OETEVRt0Qj6YY5tddKn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb2947f182d487f2fa532fac08a99cbb8fc2e9bb/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L57)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

no need for plural
maybe get_current_internal_block or get_internal_block_by_number or get_internal_block_at
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 133 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-OESo5O67cq69UQWGQED:-OETm_PaCcrEIcz-mpXG:b-6bw0sh) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb2947f182d487f2fa532fac08a99cbb8fc2e9bb/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L133)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

If current_block_number surpassed end_block_number you're sending an empty query here.
You can fix it by either adding a small if or continuing the outer loop after you yield an internal block
</blockquote></details>

small if makes it complicated because of scopes of response_manager. continuing wont solve it either because if we reached end_block_num due to stop_sync_at_block, we will still call the empty query. we would also need to change log messages as we wont always be downloading the blocks we claim to have.

i solved it by adding a loop instead of the while, using if clauses to differentiate between finishing due to current_block == end_block or due to  not having internal blocks. TAL
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 173 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-OESodg41zRulcTTxH5E:-OETJQVR8fb__P1hPfuW:b-z3jxy5) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb2947f182d487f2fa532fac08a99cbb8fc2e9bb/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L173)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why did you made this change (and the change above regarding stop_sync_at_block_number)
</blockquote></details>

because i defined end block to be the min(end_block, stop_sync_at_block) therefore there was no need to recheck this clause every iteration.

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2589)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Review by ShahakShama — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2589)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-:-OEUOzRO-YcWytewesUb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2589#-:-OEUXo-v1kGx9k0KBypF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Pull request merged**
