### PR TITLE
chore: align the scenario towards code share

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#1686** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1686?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1685** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1685?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ArniStarkware** [comment]
*[`crates/tests-integration/src/integration_test_utils.rs` line 186 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1685#-OASkgX37fzRuVfr9Ldw:-OASrily2RBGvzFJGtWL:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d658559e3dc8033970c7e91fcc98665b402ccfb3/crates/tests-integration/src/integration_test_utils.rs#L186)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The whole idea of the function is that the transactions are sent in one order - yet the mempool reorders them in some other way...
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1685)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 191 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1685#-OAWbATe6TZz3eVXG7yZ:-OAWbATe6TZz3eVXG7y_:brbo3e1) ([raw file](https://github.com/starkware-libs/sequencer/blob/02ece476a14b80d8c3dfc5191d3ff5a33609c678/crates/tests-integration/src/integration_test_utils.rs#L191)):*
> ```XML
>     // account0_invoke_nonce1, and account0_invoke_nonce2.
>     vec![tx_hashes[2], tx_hashes[0], tx_hashes[1]]
> }
> ```

Consider making this a bit shorter as suggested.
Ideally the priority explanation should be documented in the mempool files and referenced to here, but I couldn't find such docuentation.



_Suggestion:_
```XML
    // Return the transaction hashes by the order they should be given by the mempool:
    // Same account transactions must be ordered by nonce, otherwise a higher tip gets a higher priority.
    vec![account1_invoke_nonce1_tx_hash, account0_invoke_nonce1_tx_hash, account0_invoke_nonce2_tx_hash]
}
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1685)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 191 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1685#-OAWbATe6TZz3eVXG7yZ:-OAWk9Zr939smjde1H4b:blq89kf) ([raw file](https://github.com/starkware-libs/sequencer/blob/02ece476a14b80d8c3dfc5191d3ff5a33609c678/crates/tests-integration/src/integration_test_utils.rs#L191)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Consider making this a bit shorter as suggested.
Ideally the priority explanation should be documented in the mempool files and referenced to here, but I couldn't find such docuentation.
</blockquote></details>

Partially, Done.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1685)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 191 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1685#-OAWbATe6TZz3eVXG7yZ:-OAWr7bmB-8HyspTzaIF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/02ece476a14b80d8c3dfc5191d3ff5a33609c678/crates/tests-integration/src/integration_test_utils.rs#L191)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Partially, Done.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1685#-:-OAWseMx9lJyvonkMymj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 177 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1685#-OAWsMoJ0fr490X6yANM:-OAWsMoJ0fr490X6yANN:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/852beafad995617e76d709db40dc9e2316d60dff/crates/tests-integration/src/integration_test_utils.rs#L177)):*
> ```XML
>     let account1_invoke_nonce1_tx_hash = send_rpc_tx(account1_invoke_nonce1, send_rpc_tx_fn).await;
> 
>     // Send RPC transactions.
> ```





_Suggestion:_
```XML
// Ordered by sending order.
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1685)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 177 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1685#-OAWsMoJ0fr490X6yANM:-OAX2PF-3l7LGNCnkc-q:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/852beafad995617e76d709db40dc9e2316d60dff/crates/tests-integration/src/integration_test_utils.rs#L177)):*
> ```XML
>     let account1_invoke_nonce1_tx_hash = send_rpc_tx(account1_invoke_nonce1, send_rpc_tx_fn).await;
> 
>     // Send RPC transactions.
> ```

Done.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1685)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1685)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
