### PR TITLE
refactor: add casm contract class struct compatible for executable transaction

### PR DESCRIPTION
**Pull request by ArniStarkware**
This is a draft. A PR composed of multiple commits, which show the process handled one step at a time.

refactor: add casm contract class struct compatible for executable transaction

refactor: use casm contract class for executable transaction

refactor: add try from executable declare tx to account tx

chore: remove handle of impossible scenarios

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/357)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#357** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/357?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 2 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/357)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 177 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/357#-O3lo0_-72uGayIi5cOE:-O3lo0_-72uGayIi5cOF:b-ak1olb) ([raw file](https://github.com/starkware-libs/sequencer/blob/fc926d3e0c8e4063c428999f8f44966ae1c8aa1b/crates/blockifier/src/transaction/transactions.rs#L177)):*
> ```XML
>     }
> 
>     pub fn create_from_executable_tx(
> ```

Do we need both this and `TryFrom`?
You can either implement only `TryFrom` or make this method private.



_Code quote:_
```XML
pub fn create_from_executable_tx(
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 185 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/357#-O3lotGk-ufzF6o76osi:-O3lotGk-ufzF6o76osj:ba0fmh6) ([raw file](https://github.com/starkware-libs/sequencer/blob/fc926d3e0c8e4063c428999f8f44966ae1c8aa1b/crates/blockifier/src/transaction/transactions.rs#L185)):*
> ```XML
>         let class_info: ClassInfo = class_info.try_into()?;
> 
>         // Assert that the ContractClass matches the TransactionVersion, and return the result.
> ```

Do you mean the `ContractClassVersionMismatch` error?
`Self::create` can also return other errors.

Also, I'm not sure what do you mean by "In this flow"?
___
*[`crates/starknet_api/src/contract_class.rs` line 1 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/357#-O3ld0dhDUJ5VjVrBxQ5:-O3ld0dhDUJ5VjVrBxQ6:b-235m7z) ([raw file](https://github.com/starkware-libs/sequencer/blob/fc926d3e0c8e4063c428999f8f44966ae1c8aa1b/crates/starknet_api/src/contract_class.rs#L1)):*
> ```XML
> use cairo_lang_starknet_classes::casm_contract_class::CasmContractClass;
> ```

Please add documentation for all of the new types.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/357)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 177 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/357#-O3lo0_-72uGayIi5cOE:-O3lyyIWC-cPQf9voRsY:b-l3cfmq) ([raw file](https://github.com/starkware-libs/sequencer/blob/fc926d3e0c8e4063c428999f8f44966ae1c8aa1b/crates/blockifier/src/transaction/transactions.rs#L177)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Do we need both this and `TryFrom`?
You can either implement only `TryFrom` or make this method private.
</blockquote></details>

Done.

(This fix assumes we are never going to call `create_from_executable_tx` with `only_query = true.` The `only_query` flow is deprecated anyway IIUC).
___
*[`crates/blockifier/src/transaction/transactions.rs` line 185 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/357#-O3lotGk-ufzF6o76osi:-O3lzXuz9NlVqj9FB2qw:bjslrg0) ([raw file](https://github.com/starkware-libs/sequencer/blob/fc926d3e0c8e4063c428999f8f44966ae1c8aa1b/crates/blockifier/src/transaction/transactions.rs#L185)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Do you mean the `ContractClassVersionMismatch` error?
`Self::create` can also return other errors.

Also, I'm not sure what do you mean by "In this flow"?
</blockquote></details>

Removed. I was mistaken.
The PR is now comprised of 3 commits only.


(For the record: I do mean the `ContractClassVersionMismatch` error.
IIUC, `Self::create` can return only this error.  The only possible fail is on `verify_contract_class_version`, which can only fail on `ContractClassVersionMismatch` - or am I missing something?
The issue is - that this method can indeed fail in "In this flow". There are inputs for this function that may cause it to fail.)
___
*[`crates/starknet_api/src/contract_class.rs` line 1 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/357#-O3ld0dhDUJ5VjVrBxQ5:-O3lxUca38RobhgwHDj-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fc926d3e0c8e4063c428999f8f44966ae1c8aa1b/crates/starknet_api/src/contract_class.rs#L1)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please add documentation for all of the new types.
</blockquote></details>

Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/357#-:-O40HIe0CXDbCOqi2P2E:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/357)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 504 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/357#-O40fIyD1QbdKNoJ7Liv:-O40fIyD1QbdKNoJ7Liw:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/19f98a9b2bd51f6438d4d4cc1aa0c08ed30a1a99/crates/blockifier/src/execution/contract_class.rs#L504)):*
> ```XML
>     type Error = ProgramError;
> 
>     fn try_from(value: starknet_api::contract_class::ClassInfo) -> Result<Self, Self::Error> {
> ```





_Suggestion:_
```XML
class_info
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 142 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/357#-O40lK6A7Q7HgykO-fZg:-O40lK6A7Q7HgykO-fZh:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/19f98a9b2bd51f6438d4d4cc1aa0c08ed30a1a99/crates/blockifier/src/transaction/transactions.rs#L142)):*
> ```XML
> 
>     fn try_from(
>         value: starknet_api::executable_transaction::DeclareTransaction,
> ```





_Suggestion:_
```XML
declare_tx
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/357)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 504 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/357#-O40fIyD1QbdKNoJ7Liv:-O40sln85GUPX_hgNuHh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/19f98a9b2bd51f6438d4d4cc1aa0c08ed30a1a99/crates/blockifier/src/execution/contract_class.rs#L504)):*
> ```XML
>     type Error = ProgramError;
> 
>     fn try_from(value: starknet_api::contract_class::ClassInfo) -> Result<Self, Self::Error> {
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 142 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/357#-O40lK6A7Q7HgykO-fZg:-O40sn8I8KLy97T2e9dT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/19f98a9b2bd51f6438d4d4cc1aa0c08ed30a1a99/crates/blockifier/src/transaction/transactions.rs#L142)):*
> ```XML
> 
>     fn try_from(
>         value: starknet_api::executable_transaction::DeclareTransaction,
> ```

Done.

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/357)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
