### PR TITLE
refactor(blockifier): min compiler version for sierra gas type

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2421?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2421** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2421?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2421?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2420** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2420?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2313** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2313?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2383](https://github.com/starkware-libs/sequencer/pull/2383) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2383?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2421)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2421)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2421)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 266 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2421#-ODCAj3y19xGrk_gEnXQ:-ODCAj3y19xGrk_gEnXR:btqkvmc) ([raw file](https://github.com/starkware-libs/sequencer/blob/e5d5bcaa90d3d1e7e802713fd84ec4af84e1807a/crates/blockifier/src/execution/contract_class.rs#L266)):*
> ```XML
>     /// Returns whether this contract should run using Cairo steps or Sierra gas.
>     pub fn tracked_resource(&self, min_sierra_version: &SierraVersion) -> TrackedResource {
>         if *min_sierra_version <= self.sierra_version {
> ```

This field is irrelevant now. You need to move `fn tracked_resource` to your new object - VersionedRunnableContractClass - it is the only one holding the actual Sierra version



_Code quote:_
```XML
self.sierra_version
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2421)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2421)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2421#-OEsK9_r5yioMAR4vxCK:-OEsK9_r5yioMAR4vxCL:bpbja99) (no related file):*
rebase over `main-v0.13.4`

**Pull request closed without merging**
