### PR TITLE
refactor: streamline class info object to match contract class

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/427)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#427** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/427?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/427)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 49 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/427#-O4K0gkQ4UIAazuEsqnw:-O4K0gkQ4UIAazuEsqnx:b-srigi7) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f12b2ab9b61a4d84aeaaa1e21bd88ba2413bd53/crates/blockifier/src/execution/contract_class.rs#L49)):*
> ```XML
> /// We wrap the actual class in an Arc to avoid cloning the program when cloning the class.
> // Note: when deserializing from a SN API class JSON string, the ABI field is ignored
> // by serde, since it is not required for execution.
> ```

What is this referring to?



_Code quote:_
```XML
/// Represents a runnable Starknet contract class (meaning, the program is runnable by the VM).
/// We wrap the actual class in an Arc to avoid cloning the program when cloning the class.
// Note: when deserializing from a SN API class JSON string, the ABI field is ignored
// by serde, since it is not required for execution.
```
___
*[`crates/gateway/src/compilation.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/427#-O4K2pnY7v8qVsFF7NJH:-O4K2pnY7v8qVsFF7NJI:b-9up5se) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f12b2ab9b61a4d84aeaaa1e21bd88ba2413bd53/crates/gateway/src/compilation.rs#L3)):*
> ```XML
> use std::sync::Arc;
> 
> use blockifier::execution::contract_class::{ClassInfo, ContractClassV1};
> ```

Consider using `as BlockifierContractClass`



_Code quote:_
```XML
ContractClassV1
```
___
*[`crates/papyrus_execution/src/lib.rs` line 760 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/427#-O4K3Ulg58-P_xXGT7Ru:-O4K3UlhCEDar5vSLk8u:b3ksej6) ([raw file](https://github.com/starkware-libs/sequencer/blob/13ae0584764cfae0fde17671c9564823d1d7c51a/crates/papyrus_execution/src/lib.rs#L760)):*
> ```XML
>             )?);
>             let class_info = ClassInfo::new(&class_v0, DEPRECATED_CONTRACT_SIERRA_SIZE, abi_length)
>                 .map_err(|err| ExecutionError::BadDeclareTransaction {
> ```

Is this error still in use?



_Code quote:_
```XML
ExecutionError::BadDeclareTransaction
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/427)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 49 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/427#-O4K0gkQ4UIAazuEsqnw:-O4Kah3M4C0x7bfou78Y:b-7chg1y) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f12b2ab9b61a4d84aeaaa1e21bd88ba2413bd53/crates/blockifier/src/execution/contract_class.rs#L49)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

What is this referring to?
</blockquote></details>

The original intent was to document ContractClass:
https://reviewable.io/reviews/starkware-libs/blockifier/452

Done.
___
*[`crates/gateway/src/compilation.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/427#-O4K2pnY7v8qVsFF7NJH:-O4KbwtfCZ-fu0w98eNq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f12b2ab9b61a4d84aeaaa1e21bd88ba2413bd53/crates/gateway/src/compilation.rs#L3)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider using `as BlockifierContractClass`
</blockquote></details>

Done.
___
*[`crates/papyrus_execution/src/lib.rs` line 760 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/427#-O4K3Ulg58-P_xXGT7Ru:-O4Kc8cr83tdTeoD3oUo:b-dv5m55) ([raw file](https://github.com/starkware-libs/sequencer/blob/13ae0584764cfae0fde17671c9564823d1d7c51a/crates/papyrus_execution/src/lib.rs#L760)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Is this error still in use?
</blockquote></details>

No! :partying_face: 
Removed.

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/427)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 49 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/427#-O4K0gkQ4UIAazuEsqnw:-O4ZfZ9MBFQ7xtwIhzl_:b-7eib98) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f12b2ab9b61a4d84aeaaa1e21bd88ba2413bd53/crates/blockifier/src/execution/contract_class.rs#L49)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The original intent was to document ContractClass:
https://reviewable.io/reviews/starkware-libs/blockifier/452

Done.
</blockquote></details>

I don't understand how the comment matches the type (where is the Arc?)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/contract_class.rs` line 49 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/427#-O4K0gkQ4UIAazuEsqnw:-O4ZlS7Q6z3zUQEojrDS:bvbwmq1) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f12b2ab9b61a4d84aeaaa1e21bd88ba2413bd53/crates/blockifier/src/execution/contract_class.rs#L49)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I don't understand how the comment matches the type (where is the Arc?)
</blockquote></details>

You are correct.

This issue is now handled in #491. I think these are unrelated issues, and I hope the prep PR will be merged long before this one.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/427#-:-O4_4Quv0mMkV2G2cBtF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/contract_class.rs` line 502 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/427#-O4aGVUO5wbWCw9OoT3b:-O4aGVUO5wbWCw9OoT3c:b-34x388) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c8184d1772cf6a62c2a633c654eead22e5410d0/crates/blockifier/src/execution/contract_class.rs#L502)):*
> ```XML
>     V0 { contract_class: ContractClassV0, abi_length: usize },
>     V1 { contract_class: ContractClassV1, sierra_program_length: usize, abi_length: usize },
> }
> ```

Is this cleaner, in your opinion?



_Suggestion:_
```XML
pub enum ClassInfo {
    V0 (ClassInfoV0),
    V1 (ClassInfoV1),
}

pub struct ClassInfoV0 {contract_class: ContractClassV0, abi_length: usize};
pub struct ClassInfoV1 {contract_class: ContractClassV1, sierra_program_length: usize, abi_length: usize };
```

**Review by yair-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/427)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 502 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/427#-O4aGVUO5wbWCw9OoT3b:-O4srbY6ERbANnwzoccp:b32w12) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c8184d1772cf6a62c2a633c654eead22e5410d0/crates/blockifier/src/execution/contract_class.rs#L502)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Is this cleaner, in your opinion?
</blockquote></details>

No

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/427#-:-O5ID4trDD2ro8bqHAgs:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/427)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/427)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/contract_class.rs` line 565 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/427#-O80u7SfEvApKhiteaAw:-O80u7SfEvApKhiteaAx:b-hoapjl) ([raw file](https://github.com/starkware-libs/sequencer/blob/a013fb2378ca8c0bc73d3efe9896080ae84403b9/crates/blockifier/src/execution/contract_class.rs#L565)):*
> ```XML
>     V0 { contract_class: ContractClassV0, abi_length: usize },
>     V1 { contract_class: ContractClassV1, sierra_program_length: usize, abi_length: usize },
> }
> ```

This is the main innovation of this PR.
This, and deleting the combersom `new` class method.



_Code quote:_
```XML
pub enum ClassInfo {
    V0 { contract_class: ContractClassV0, abi_length: usize },
    V1 { contract_class: ContractClassV1, sierra_program_length: usize, abi_length: usize },
}
```

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/427)* status: 1 of 5 files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 565 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/427#-O80u7SfEvApKhiteaAw:-O8VWwwm6oF_xcKK0m4X:byjn6iz) ([raw file](https://github.com/starkware-libs/sequencer/blob/a013fb2378ca8c0bc73d3efe9896080ae84403b9/crates/blockifier/src/execution/contract_class.rs#L565)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This is the main innovation of this PR.
This, and deleting the combersom `new` class method.
</blockquote></details>

Using two separate enums (`ContractClass` and `ClassInfo`) that mirror each other's structure can be redundant and can make the code harder to maintain, as any changes to `ContractClass` would need to be reflected in `ClassInfo`

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/execution/contract_class.rs` line 565 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/427#-O80u7SfEvApKhiteaAw:-O8_sq2H5F5N_Ki_8gdM:bozxoso) ([raw file](https://github.com/starkware-libs/sequencer/blob/a013fb2378ca8c0bc73d3efe9896080ae84403b9/crates/blockifier/src/execution/contract_class.rs#L565)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Using two separate enums (`ContractClass` and `ClassInfo`) that mirror each other's structure can be redundant and can make the code harder to maintain, as any changes to `ContractClass` would need to be reflected in `ClassInfo`
</blockquote></details>

I split this PR into this one and #1215. PTAL.

**Comment by ArniStarkware** [comment]
No longer relevant. It becomes harder to streamline now that there are three variants of contract class.

**Pull request closed without merging**
