### PR TITLE
fix(native_blockifier): activate testing feature only in dev dependencies

### PR DESCRIPTION
**Pull request by dorimedini-starkware**

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
* **#2625** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2625?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2624** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2624?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2624?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by meship-starkware — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2624)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 152 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2624#-OEEf25wE1n61uDNiRSO:-OEEf25x-3Bb4sifMxju:b-p5q6ca) ([raw file](https://github.com/starkware-libs/sequencer/blob/96c2043eb1e12d6c2fe3fed35a5b2617becb6b17/crates/blockifier/src/test_utils.rs#L152)):*
> ```XML
>     NonzeroGasPrice::new_unchecked(GasPrice(100 * u128::pow(10, 9))); // Given in units of Wei.
> pub const DEFAULT_STRK_L1_GAS_PRICE: NonzeroGasPrice =
>     NonzeroGasPrice::new_unchecked(GasPrice(100 * u128::pow(10, 9))); // Given in units of Fri.
> ```

Is this related to this PR? 



_Code quote:_
```XML
    NonzeroGasPrice::new_unchecked(GasPrice(100 * u128::pow(10, 9))); // Given in units of Fri.
```
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2624#-OEEfqSsApDXxR0Hjs4H:-OEEfqSsApDXxR0Hjs4I:bucein2) ([raw file](https://github.com/starkware-libs/sequencer/blob/96c2043eb1e12d6c2fe3fed35a5b2617becb6b17/crates/native_blockifier/src/py_state_diff.rs#L25)):*
> ```XML
> const DEFAULT_STRK_L1_GAS_PRICE: GasPrice = GasPrice(100 * u128::pow(10, 9));
> const DEFAULT_ETH_L1_DATA_GAS_PRICE: GasPrice = GasPrice(u128::pow(10, 6));
> const DEFAULT_STRK_L1_DATA_GAS_PRICE: GasPrice = GasPrice(u128::pow(10, 9));
> ```

Also not part of this PR, right?



_Code quote:_
```XML
const DEFAULT_ETH_L1_GAS_PRICE: GasPrice = GasPrice(100 * u128::pow(10, 9));
const DEFAULT_STRK_L1_GAS_PRICE: GasPrice = GasPrice(100 * u128::pow(10, 9));
const DEFAULT_ETH_L1_DATA_GAS_PRICE: GasPrice = GasPrice(u128::pow(10, 6));
const DEFAULT_STRK_L1_DATA_GAS_PRICE: GasPrice = GasPrice(u128::pow(10, 9));
```
___
*[`crates/native_blockifier/Cargo.toml` line 47 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2624#-OEEfWvX9H9tk7TC5jDj:-OEEfWvYCmxud6wI7gcT:bvv7lxp) ([raw file](https://github.com/starkware-libs/sequencer/blob/96c2043eb1e12d6c2fe3fed35a5b2617becb6b17/crates/native_blockifier/Cargo.toml#L47)):*
> ```TOML
> 
> [dev-dependencies]
> blockifier = { workspace = true, features = ["cairo_native", "native_blockifier", "testing"] }
> ```

Why do we need the native blockifier config? 



_Code quote:_
```TOML
"native_blockifier
```

**Review by noaov1 — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2624)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/native_blockifier/Cargo.toml` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2624#-OEEe9X02hEbR3jlGHY8:-OEEe9X1-8rVoT7b-Fad:b-a316vr) ([raw file](https://github.com/starkware-libs/sequencer/blob/4acec9b0d42ce4b9e8ab39817003f6d3f6e7a711/crates/native_blockifier/Cargo.toml#L14)):*
> ```TOML
> # https://pyo3.rs/v0.19.1/faq#i-cant-run-cargo-test-or-i-cant-build-in-a-cargo-workspace-im-having-linker-issues-like-symbol-not-found-or-undefined-reference-to-_pyexc_systemerror
> extension-module = ["pyo3/extension-module"]
> testing = ["blockifier/testing", "papyrus_storage/testing", "starknet_api/testing"]
> ```

Why is this feature needed? 



_Code quote:_
```TOML
testing = ["blockifier/testing", "papyrus_storage/testing", "starknet_api/testing"]
```
___
*[`crates/native_blockifier/Cargo.toml` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2624#-OEEdrioDUFbKQoXytkd:-OEEdrioDUFbKQoXytke:b-s252vm) ([raw file](https://github.com/starkware-libs/sequencer/blob/4acec9b0d42ce4b9e8ab39817003f6d3f6e7a711/crates/native_blockifier/Cargo.toml#L47)):*
> ```TOML
> 
> [dev-dependencies]
> blockifier = { workspace = true, features = ["cairo_native", "native_blockifier", "testing"] }
> ```

Is the "cairo_native" feature needed? 



_Code quote:_
```TOML
blockifier = { workspace = true, features = ["cairo_native", "native_blockifier", "testing"] }
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2624)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 152 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2624#-OEEf25wE1n61uDNiRSO:-OEEgApw15QyaWhmLxL2:b-qzkxdy) ([raw file](https://github.com/starkware-libs/sequencer/blob/96c2043eb1e12d6c2fe3fed35a5b2617becb6b17/crates/blockifier/src/test_utils.rs#L152)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Is this related to this PR?
</blockquote></details>

not really, but removing the dependency on these constants *is* part of this PR, so I'm in favor of keeping it (it's just a doc change)
___
*[`crates/native_blockifier/Cargo.toml` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2624#-OEEe9X02hEbR3jlGHY8:-OEEhtjM5xhb3wwNCjEW:bf81cow) ([raw file](https://github.com/starkware-libs/sequencer/blob/4acec9b0d42ce4b9e8ab39817003f6d3f6e7a711/crates/native_blockifier/Cargo.toml#L14)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is this feature needed?
</blockquote></details>

note that this PR only fixes the `testing` feature:
previously the `testing` feature in these 3 crates was always activated, even in regular `cargo build`.
now, it's only activated in dev-dependencies (`cargo test`) and when the `testing` feature is activated
___
*[`crates/native_blockifier/Cargo.toml` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2624#-OEEdrioDUFbKQoXytkd:-OEEhpXL4M76qLbMTLT7:bmu4q0s) ([raw file](https://github.com/starkware-libs/sequencer/blob/4acec9b0d42ce4b9e8ab39817003f6d3f6e7a711/crates/native_blockifier/Cargo.toml#L47)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is the "cairo_native" feature needed?
</blockquote></details>

remove in the [next PR](https://reviewable.io/reviews/starkware-libs/sequencer/2625)
___
*[`crates/native_blockifier/Cargo.toml` line 47 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2624#-OEEfWvX9H9tk7TC5jDj:-OEEgg112SlVLXmZjzcT:b-4v8uaa) ([raw file](https://github.com/starkware-libs/sequencer/blob/96c2043eb1e12d6c2fe3fed35a5b2617becb6b17/crates/native_blockifier/Cargo.toml#L47)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why do we need the native blockifier config?
</blockquote></details>

you mean feature?
because `TransactionExecutorConfig::create_for_testing` is needed in python tests.
I don't think it's wise to expose all blockifier test utils to the native blockifier, but this specific test util is needed in python so I added another feature to turn it on specifically.
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2624#-OEEfqSsApDXxR0Hjs4H:-OEEgHU-BE43MOky2dMd:bth0m37) ([raw file](https://github.com/starkware-libs/sequencer/blob/96c2043eb1e12d6c2fe3fed35a5b2617becb6b17/crates/native_blockifier/src/py_state_diff.rs#L25)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Also not part of this PR, right?
</blockquote></details>

actually, this *is* part of this PR.
the constants were originally in the blockifier test utils,
but we want to be able to build the native_blockifier business logic without the `testing` feature of the blockifier,
so we redefine these constants for the native blockifier

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2624)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
