### PR TITLE
chore(consensus): add config pointer of sequencer address to validator id

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2494?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2494** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2494?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2494?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2409** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2409?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2425](https://github.com/starkware-libs/sequencer/pull/2425) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2425?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2486** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2486?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2494)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @matan-starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2494#-ODMHzJ-1nCbSUfIabao:-ODMHzJ06ta1x-JnTEF-:b-qvx7ed) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4c9f58fd5fe148c2922399c41419e110cfad7ad/crates/starknet_integration_tests/src/utils.rs#L66)):*
> ```XML
>             eth_fee_token_address: fee_token_addresses.eth_fee_token_address,
>             strk_fee_token_address: fee_token_addresses.strk_fee_token_address,
>             sequencer_address: ContractAddress::from(100_u128),
> ```

throughout the PR.



_Suggestion:_
```XML
validator_id
```

**Comment by ArniStarkware** [comment]
*[`crates/starknet_integration_tests/src/utils.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2494#-ODMHzJ-1nCbSUfIabao:-ODMKfN6B_V2sKz19g9Q:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4c9f58fd5fe148c2922399c41419e110cfad7ad/crates/starknet_integration_tests/src/utils.rs#L66)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

throughout the PR.
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2494)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @Itay-Tsabary-Starkware, and @matan-starkware)

___
*[`crates/starknet_sequencer_node/src/config/node_config.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2494#-ODMI0HN6BI__uQBCwVH:-ODMO8cwC-shMvf-7vFV:b39rob7) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4c9f58fd5fe148c2922399c41419e110cfad7ad/crates/starknet_sequencer_node/src/config/node_config.rs#L79)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I am confused. Let's talk in person.
</blockquote></details>

Is there a way to make a param required without making it a pointer? If so, let's do it in this PR; if not, leave it to TODO.
___
*[`crates/starknet_sequencer_node/src/config/node_config.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2494#-ODMOL79C58Gvc3iSXGO:-ODMOL79C58Gvc3iSXGP:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bef9606277a9a5feb8346269329f7c1e7a8dfeb/crates/starknet_sequencer_node/src/config/node_config.rs#L84)):*
> ```XML
>                 "validator_id",
>                 SerializationType::String,
>                 "The ID the validator. Also the address of this validator as a starknet contract.",
> ```





_Suggestion:_
```XML
The ID of the validator
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2494)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @alonh5, @Itay-Tsabary-Starkware, and @matan-starkware)

___
*[`crates/starknet_sequencer_node/src/config/node_config.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2494#-ODMOL79C58Gvc3iSXGO:-ODMWQxi8GJwk54r5sFi:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bef9606277a9a5feb8346269329f7c1e7a8dfeb/crates/starknet_sequencer_node/src/config/node_config.rs#L84)):*
> ```XML
>                 "validator_id",
>                 SerializationType::String,
>                 "The ID the validator. Also the address of this validator as a starknet contract.",
> ```

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2494#-:-OD_VViG6uJagkkQXdkr:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @Itay-Tsabary-Starkware, and @matan-starkware)

___
*[`crates/starknet_sequencer_node/src/config/node_config.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2494#-ODMI0HN6BI__uQBCwVH:-OD_VIpBEWAHpc2PLrG6:be0h9df) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4c9f58fd5fe148c2922399c41419e110cfad7ad/crates/starknet_sequencer_node/src/config/node_config.rs#L79)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Is there a way to make a param required without making it a pointer? If so, let's do it in this PR; if not, leave it to TODO.
</blockquote></details>

@ArniStarkware, please check with Itay about the above question before merging.
___
*[`crates/starknet_sequencer_node/src/config/node_config.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2494#-OD_VATh8N_YHB76zEsI:-OD_VATh8N_YHB76zEsJ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/06056a5c447100a9ef36641ea0975f71d0f0e004/crates/starknet_sequencer_node/src/config/node_config.rs#L84)):*
> ```XML
>                 "validator_id",
>                 SerializationType::String,
>                 "The ID of the validator.\
> ```





_Suggestion:_
```XML
"The ID of the validator. \
```

**Comment by ArniStarkware** [comment]
*[`crates/starknet_sequencer_node/src/config/node_config.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2494#-ODMI0HN6BI__uQBCwVH:-ODeVOyf97TEdLFNUAOJ:bzaaa4o) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4c9f58fd5fe148c2922399c41419e110cfad7ad/crates/starknet_sequencer_node/src/config/node_config.rs#L79)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

@ArniStarkware, please check with Itay about the above question before merging.
</blockquote></details>

Itay explained the subject of config pointers to me on huddle.
We can set required params without setting them as config pointers. There are two reasons to keep this as a pointer.
1. If we expect the value to be duplicated in one or more locations (we can consult Matan / Shachak). We suspect this is not the case, so this point might not matter.
2. If we want to keep the validator ID as a pointer for ease of use. Otherwise, when the system is set up - when the user needs to put in the config manually - he will have to provide the whole path: `consensus_manager_config.consensus_config.validator_id` instead of just the name of the pointer: `validator_id`.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2494)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @alonh5, @Itay-Tsabary-Starkware, and @matan-starkware)

___
*[`crates/starknet_sequencer_node/src/config/node_config.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2494#-ODMI0HN6BI__uQBCwVH:-ODeXmzm2HyMMa5grqfG:b-jnm1y9) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4c9f58fd5fe148c2922399c41419e110cfad7ad/crates/starknet_sequencer_node/src/config/node_config.rs#L79)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Itay explained the subject of config pointers to me on huddle.
We can set required params without setting them as config pointers. There are two reasons to keep this as a pointer.
1. If we expect the value to be duplicated in one or more locations (we can consult Matan / Shachak). We suspect this is not the case, so this point might not matter.
2. If we want to keep the validator ID as a pointer for ease of use. Otherwise, when the system is set up - when the user needs to put in the config manually - he will have to provide the whole path: `consensus_manager_config.consensus_config.validator_id` instead of just the name of the pointer: `validator_id`.
</blockquote></details>

Deleted the TODO.
IIUC, it will be easier to use this way.
___
*[`crates/starknet_sequencer_node/src/config/node_config.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2494#-OD_VATh8N_YHB76zEsI:-ODeVcIo0s8iWnVAAn4c:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/06056a5c447100a9ef36641ea0975f71d0f0e004/crates/starknet_sequencer_node/src/config/node_config.rs#L84)):*
> ```XML
>                 "validator_id",
>                 SerializationType::String,
>                 "The ID of the validator.\
> ```

Done.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2494)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @alonh5, @Itay-Tsabary-Starkware, and @matan-starkware)

___
*[`crates/starknet_sequencer_node/src/config/node_config.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2494#-OD_VATh8N_YHB76zEsI:-ODeflf43ongv6kCT9wp:b-bi6kpv) ([raw file](https://github.com/starkware-libs/sequencer/blob/06056a5c447100a9ef36641ea0975f71d0f0e004/crates/starknet_sequencer_node/src/config/node_config.rs#L84)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Don't see it.
</blockquote></details>

Now done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2494)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @Itay-Tsabary-Starkware, and @matan-starkware)

___
*[`config/sequencer/default_config.json` line 953 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2494#-ODehBG5ClSoReKCiF6C:-ODehBG62tWLvQdbMmi5:b-iwlz54) ([raw file](https://github.com/starkware-libs/sequencer/blob/934959133124b5be9dc403482be0d23145c69212/config/sequencer/default_config.json#L953)):*
> ```JSON
>   },
>   "validator_id": {
>     "description": "A required param! The ID of the validator.Also the address of this validator as a starknet contract.",
> ```

Here it should update also right? That's how I noticed the space was missing.



_Code quote:_
```JSON
validator.Also
```

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2494)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware and @matan-starkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2494)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware and @matan-starkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2494)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware and @matan-starkware)

**Pull request merged**
