### PR TITLE
chore(starknet_state_sync): remove StateSyncResult from starknet_state_sync_types

### PR DESCRIPTION
**Pull request by AlonLStarkWare**

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2595)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2595#-ODjb6Yj5Jon24fuV4mU:-ODjb6Yj5Jon24fuV4mV:biac8au) (no related file):*
Why do you want to remove it?

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2595)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @eitanm-starkware)

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2595)* status: all files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware and @ShahakShama)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2595#-ODjb6Yj5Jon24fuV4mU:-ODkseLM0oes6llM4YrM:b-n969eb) (no related file):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why do you want to remove it?
</blockquote></details>

It is duplicated (same definition appears in communications)

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2595)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2595#-ODjb6Yj5Jon24fuV4mU:-ODl1ghB8tvoc2ILVmXF:b1gwgb) (no related file):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

It is duplicated (same definition appears in communications)
</blockquote></details>

Erase the one in communications, and change all imports to import the one in state_sync_types

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2595#-:-OEEWDrB9Ne1DKC1UN-Y:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare)

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
ignore my :lgtm_cancel: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2595#-:-OEEWWXK0S4bqYWIjW1B:bvav2f0)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare)

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2595)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware and @ShahakShama)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2595#-ODjb6Yj5Jon24fuV4mU:-OEF0Wix1VTQiTNZEUA9:b-896fix) (no related file):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Erase the one in communications, and change all imports to import the one in state_sync_types
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2595#-:-OESy9sR5RUe3XxerSQe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Review by AlonLStarkWare — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2595)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2595#-:-OEU37wOEqNT0uLH0cpB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Pull request merged**
