### PR TITLE
refactor(starknet_batcher): rename GetProposalResultError and remove the ProposalNotFound variant

### PR DESCRIPTION
**Pull request by dafnamatsry**

### CODE REVIEW

**Comment by dafnamatsry** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2483?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2441** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2441?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2483** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2483?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2483?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2480** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2480?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2483)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @dafnamatsry)

___
*[`crates/starknet_batcher/src/batcher.rs` line 288 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2483#-OD_SQMD8A9q9clrnr_k:-OD_SQMD8A9q9clrnr_l:b-i61h4e) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4283c345999e05788183cfd1543d54fc454499c/crates/starknet_batcher/src/batcher.rs#L288)):*
> ```XML
>                 _ => return Err(BatcherError::InternalError),
>             },
>             Some(Err(ProposalError::Aborted)) => return Err(BatcherError::ProposalAborted),
> ```

I think that if the proposal was aborted, the function close_input_transaction_stream would return an error.
so this match arm would never be reached.



_Code quote:_
```XML
Some(Err(ProposalError::Aborted)) => return Err(BatcherError::ProposalAborted),
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 560 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2483#-OD_VJ2G72urlwT0tc9m:-OD_VJ2G72urlwT0tc9n:bdojcia) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4283c345999e05788183cfd1543d54fc454499c/crates/starknet_batcher/src/batcher_test.rs#L560)):*
> ```XML
>         .times(1)
>         .with(eq(PROPOSAL_ID))
>         .return_once(|_| async move { None }.boxed());
> ```

I think that move is not required here, 
probably in other places too. 
non blocking for this PR, but we should fix separately. 



_Code quote:_
```XML
move
```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2483)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 288 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2483#-OD_SQMD8A9q9clrnr_k:-OD__QMv1q3AanaXpiix:bvoycmf) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4283c345999e05788183cfd1543d54fc454499c/crates/starknet_batcher/src/batcher.rs#L288)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think that if the proposal was aborted, the function close_input_transaction_stream would return an error.
so this match arm would never be reached.
</blockquote></details>

We still need to cover it, and I think returning an error is better than panic in this case.
Also, in the following PR, I added a check at the beginning of `send_proposal_content`, so if the proposal does not exist/aborted/etc. it wouldn't reach this function at all.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 560 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2483#-OD_VJ2G72urlwT0tc9m:-OD_bPoq6LpTnAS43B1c:boz8mnh) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4283c345999e05788183cfd1543d54fc454499c/crates/starknet_batcher/src/batcher_test.rs#L560)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think that move is not required here, 
probably in other places too. 
non blocking for this PR, but we should fix separately.
</blockquote></details>

Right.
The tests are going to be changed a lot when the mock proposal manager will be deleted (and specifically this and almost all other expectations will be removed) . I'll keep this in mind.

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2483)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2483)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2483#-:-ODfAXE5E-VyWcV7WcFA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Comment by dafnamatsry** [comment]
### Merge activity

* **Dec 9, 6:47 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2483).

**Pull request merged**
