### PR TITLE
chore(blockifier): verify cairo compiler repo (with correct tag)

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/183)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/183?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#183** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/183?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#182** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/182?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#181** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/181?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#180** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/180?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#179** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/179?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by nimrod-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/183)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @dorimedini-starkware, @meship-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/183#-O36g7me5jfzyjzbxB1U:-O36g7mf9RYst-ur0pam:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7806fc5e28e7082314f917bf2ed77381bab33e3/crates/blockifier/src/test_utils/cairo_compile.rs#L68)):*
> ```XML
> }
> 
> /// Run a command, assert exit code is zero (otherwise panic with stderr output).
> ```





_Suggestion:_
```XML
/// Runs a command. If it has succeeded, it returns the command's output; otherwise, it panics with stderr output.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/183)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @meship-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/183#-O36g7me5jfzyjzbxB1U:-O38hd-_3-jpKVzQsns9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1927450f67f62f3a127af2bc6426441e3a0cb178/crates/blockifier/src/test_utils/cairo_compile.rs#L68)):*
> ```XML
> }
> 
> /// Run a command, assert exit code is zero (otherwise panic with stderr output).
> ```

Done.

**Review by nimrod-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/183#-:-O3BaMAr4Q7nwilkhfDy:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @AvivYossef-starkware, @meship-starkware, and @TzahiTaub)

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/183)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @dorimedini-starkware, @meship-starkware, and @nimrod-starkware)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/183#-O3DHXwwB64fBSEMfqPu:-O3DHXwwB64fBSEMfqPv:b-dwja2k) ([raw file](https://github.com/starkware-libs/sequencer/blob/e91ceccb5956c51760fa025a37b85f26f7c79dc2/crates/blockifier/src/test_utils/cairo_compile.rs#L9)):*
> ```XML
> 
> const CAIRO0_PIP_REQUIREMENTS_FILE: &str = "tests/requirements.txt";
> const LOCAL_CAIRO1_REPO_RELATIVE_PATH: &str = "../../../cairo";
> ```

This is too strict, please replace with env vars to allow a a hierarchy where the `sequencer` and `cairo` dirs aren't siblings, to work.



_Code quote:_
```XML
const LOCAL_CAIRO1_REPO_RELATIVE_PATH: &str = "../../../cairo";
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/183)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @meship-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/183#-O3DHXwwB64fBSEMfqPu:-O3DdtQm1Eg1tVFfmjaM:bk2mvbh) ([raw file](https://github.com/starkware-libs/sequencer/blob/e91ceccb5956c51760fa025a37b85f26f7c79dc2/crates/blockifier/src/test_utils/cairo_compile.rs#L9)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

This is too strict, please replace with env vars to allow a a hierarchy where the `sequencer` and `cairo` dirs aren't siblings, to work.
</blockquote></details>

Done. Now can be overridden by env var

**Review by TzahiTaub — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/183)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @dorimedini-starkware, and @meship-starkware)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 62 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/183#-O40A8RJD6AtYrillz4c:-O40A8RJD6AtYrillz4d:bvh84bf) ([raw file](https://github.com/starkware-libs/sequencer/blob/469c6a8e0ddf38c4b0e1fde0fef4da5989878a1a/crates/blockifier/src/test_utils/cairo_compile.rs#L62)):*
> ```XML
> 
> /// Returns the path to the local Cairo1 compiler repository.
> /// Returns <sequencer_crate_root>/<RELATIVE_PATH_TO_CAIRO_REPO>, where the relative path can be
> ```

The Sequencer is not a crate, right?



_Suggestion:_
```XML
<sequencer_repo_root>
```

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/183#-:-O40bzml70b2ZbqqReI-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware and @meship-starkware)

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Aug 11, 11:28 AM EDT**: @dorimedini-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/183).

**Pull request merged**
