### PR TITLE
chore(blockifier): add test declare v0 transaction has zero fee

### PR DESCRIPTION
**Pull request by avivg-starkware**

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1503)* status: all files reviewed, 6 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1510 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1503#-O9nBjYqDWOLd8_90lLh:-O9nBjYqDWOLd8_90lLi:bq0j276) ([raw file](https://github.com/starkware-libs/sequencer/blob/3647bd4924d7f6db615b4f4d331af1247809900f/crates/blockifier/src/transaction/transactions_test.rs#L1510)):*
> ```XML
> #[rstest]
> fn test_declare_tx_v0(default_l1_resource_bounds: ValidResourceBounds) {
>     let account_cairo_version = CairoVersion::Cairo0; //defoult
> ```

I think you can remove it.



_Suggestion:_
```XML
let account_cairo_version = CairoVersion::Cairo1;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1513 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1503#-O9nBwuz7lxGFoWWIi8c:-O9nBwuz7lxGFoWWIi8d:b-rlqovu) ([raw file](https://github.com/starkware-libs/sequencer/blob/3647bd4924d7f6db615b4f4d331af1247809900f/crates/blockifier/src/transaction/transactions_test.rs#L1513)):*
> ```XML
>     let use_kzg_da = true; //default
>     let tx_version = TransactionVersion::ZERO;
>     let block_context = &BlockContext::create_for_account_testing_with_kzg(use_kzg_da);
> ```

And than you can remove the variable ` use_kzg_da` :)



_Suggestion:_
```XML
    let block_context = &BlockContext::create_for_account_testing();
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1515 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1503#-O9nC9Y33m0CpgANms9T:-O9nC9Y33m0CpgANms9U:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/3647bd4924d7f6db615b4f4d331af1247809900f/crates/blockifier/src/transaction/transactions_test.rs#L1515)):*
> ```XML
>     let block_context = &BlockContext::create_for_account_testing_with_kzg(use_kzg_da);
>     let versioned_constants = &block_context.versioned_constants;
>     let empty_contract = FeatureContract::Empty(CairoVersion::Cairo0);
> ```





_Suggestion:_
```XML
let empty_contract = FeatureContract::Empty(CairoVersion::Cairo1);
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1516 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1503#-O9nCJh2EdmRgiBB1TIj:-O9nCJh2EdmRgiBB1TIk:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/3647bd4924d7f6db615b4f4d331af1247809900f/crates/blockifier/src/transaction/transactions_test.rs#L1516)):*
> ```XML
>     let versioned_constants = &block_context.versioned_constants;
>     let empty_contract = FeatureContract::Empty(CairoVersion::Cairo0);
>     let account = FeatureContract::AccountWithoutValidations(account_cairo_version);
> ```





_Suggestion:_
```XML
    let account = FeatureContract::AccountWithoutValidations(CairoVersion::Cairo1);
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1535 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1503#-O9nCW0NBdM5ys1zN50c:-O9nCW0NBdM5ys1zN50d:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/3647bd4924d7f6db615b4f4d331af1247809900f/crates/blockifier/src/transaction/transactions_test.rs#L1535)):*
> ```XML
>     let account_tx = declare_tx(
>         declare_tx_args! {
>             max_fee: MAX_FEE,
> ```





_Suggestion:_
```XML
max_fee:0,
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1599 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1503#-O9nCbQFDooo3r93p2ir:-O9nCbQFDooo3r93p2is:bt9sssb) ([raw file](https://github.com/starkware-libs/sequencer/blob/3647bd4924d7f6db615b4f4d331af1247809900f/crates/blockifier/src/transaction/transactions_test.rs#L1599)):*
> ```XML
>         },
>         revert_error: None,
>     };
> ```

Please remove. You can just compare the `actual_fee` and the `fee_transfer_call_info`.



_Code quote:_
```XML
    // Build expected validate call info.
    let expected_validate_call_info = declare_validate_callinfo(
        tx_version,
        account_cairo_version,
        class_hash,
        account.get_class_hash(),
        sender_address,
        account
            .get_class()
            .tracked_resource(&versioned_constants.min_compiler_version_for_sierra_gas),
    );

    let da_gas = starknet_resources.state.to_gas_vector(use_kzg_da);
    let expected_cairo_resources = get_expected_cairo_resources(
        versioned_constants,
        TransactionType::Declare,
        &starknet_resources,
        vec![&expected_validate_call_info],
    );
    let mut expected_actual_resources = TransactionResources {
        starknet_resources,
        computation: ComputationResources {
            vm_resources: expected_cairo_resources,
            ..Default::default()
        },
    };

    add_kzg_da_resources_to_resources_mapping(
        &mut expected_actual_resources.computation.vm_resources,
        &state_changes_for_fee,
        versioned_constants,
        use_kzg_da,
    );

    let expected_total_gas = expected_actual_resources.to_gas_vector(
        versioned_constants,
        use_kzg_da,
        &GasVectorComputationMode::NoL2Gas,
    );

    let expected_execution_info = TransactionExecutionInfo {
        validate_call_info: expected_validate_call_info,
        execute_call_info: None,
        fee_transfer_call_info: None,
        receipt: TransactionReceipt {
            fee: Fee(0),
            da_gas,
            resources: expected_actual_resources,
            gas: expected_total_gas,
        },
        revert_error: None,
    };
```

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1503)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1510 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1503#-O9nBjYqDWOLd8_90lLh:-O9nDuvk8qrv_t49LhW4:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3647bd4924d7f6db615b4f4d331af1247809900f/crates/blockifier/src/transaction/transactions_test.rs#L1510)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think you can remove it.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1513 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1503#-O9nBwuz7lxGFoWWIi8c:-O9nE01l4xBl0DuOP6YO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3647bd4924d7f6db615b4f4d331af1247809900f/crates/blockifier/src/transaction/transactions_test.rs#L1513)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

And than you can remove the variable ` use_kzg_da` :)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1515 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1503#-O9nC9Y33m0CpgANms9T:-O9nE4Rl2N2t2SPXQ5-D:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3647bd4924d7f6db615b4f4d331af1247809900f/crates/blockifier/src/transaction/transactions_test.rs#L1515)):*
> ```XML
>     let block_context = &BlockContext::create_for_account_testing_with_kzg(use_kzg_da);
>     let versioned_constants = &block_context.versioned_constants;
>     let empty_contract = FeatureContract::Empty(CairoVersion::Cairo0);
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1516 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1503#-O9nCJh2EdmRgiBB1TIj:-O9nECjl48TxFezTAzhS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3647bd4924d7f6db615b4f4d331af1247809900f/crates/blockifier/src/transaction/transactions_test.rs#L1516)):*
> ```XML
>     let versioned_constants = &block_context.versioned_constants;
>     let empty_contract = FeatureContract::Empty(CairoVersion::Cairo0);
>     let account = FeatureContract::AccountWithoutValidations(account_cairo_version);
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1535 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1503#-O9nCW0NBdM5ys1zN50c:-O9nEL-ABZF5ksn1JyWr:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3647bd4924d7f6db615b4f4d331af1247809900f/crates/blockifier/src/transaction/transactions_test.rs#L1535)):*
> ```XML
>     let account_tx = declare_tx(
>         declare_tx_args! {
>             max_fee: MAX_FEE,
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1599 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1503#-O9nCbQFDooo3r93p2ir:-O9nGXlU77Xr_gobPVqz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3647bd4924d7f6db615b4f4d331af1247809900f/crates/blockifier/src/transaction/transactions_test.rs#L1599)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please remove. You can just compare the `actual_fee` and the `fee_transfer_call_info`.
</blockquote></details>

Done.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1503)* status: all files reviewed, 3 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1512 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1503#-O9olOrVE2_ceHFzlcXK:-O9olOrVE2_ceHFzlcXL:be11mbz) ([raw file](https://github.com/starkware-libs/sequencer/blob/12e289458418d5d51baa93a5acde5d01e74642f9/crates/blockifier/src/transaction/transactions_test.rs#L1512)):*
> ```XML
>     let tx_version = TransactionVersion::ZERO;
>     let block_context = &BlockContext::create_for_account_testing();
>     let versioned_constants = &block_context.versioned_constants;
> ```

Can be removed, right?



_Code quote:_
```XML
    let versioned_constants = &block_context.versioned_constants;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1530 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1503#-O9olfA0DZsG4iC3zQwg:-O9olfA0DZsG4iC3zQwh:b-n6d6dn) ([raw file](https://github.com/starkware-libs/sequencer/blob/12e289458418d5d51baa93a5acde5d01e74642f9/crates/blockifier/src/transaction/transactions_test.rs#L1530)):*
> ```XML
>         None,
>         ExecutionSummary::default(),
>     );
> ```

Please remove



_Code quote:_
```XML
    let state_changes_for_fee = declare_expected_state_changes_count(tx_version);
    let starknet_resources = StarknetResources::new(
        0,
        0,
        class_info.code_size(),
        StateResources::new_for_testing(state_changes_for_fee),
        None,
        ExecutionSummary::default(),
    );
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1546 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1503#-O9olLOICat6YpMM_rGy:-O9olLOICat6YpMM_rGz:b-m37gwb) ([raw file](https://github.com/starkware-libs/sequencer/blob/12e289458418d5d51baa93a5acde5d01e74642f9/crates/blockifier/src/transaction/transactions_test.rs#L1546)):*
> ```XML
>     let actual_execution_info = account_tx.execute(state, block_context, true, true).unwrap();
> 
>     // Test execution info result.
> ```

Please remove (same below)



_Code quote:_
```XML
    // Test execution info result.
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1503)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1535 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1503#-O9nCW0NBdM5ys1zN50c:-OACkWYJ49InQbfFWbk4:b-i7ylua) ([raw file](https://github.com/starkware-libs/sequencer/blob/3647bd4924d7f6db615b4f4d331af1247809900f/crates/blockifier/src/transaction/transactions_test.rs#L1535)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

Also apologies, I reverted as well. when using Fee(0), it panicks with min higher than max. I will look into it,  I think this might point to something I should fix, WDYT?
</blockquote></details>

Try setting the `charge_fee` flag to false.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1503#-:-OACuA3z1JxOF_UfdGUT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Review by avivg-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1503)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Pull request merged**
