### PR TITLE
chore(batcher): rename transaction_provider

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
* **#1778** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1778?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Yael-Starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1778)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1778#-OAqzhmK9IbW0v3cwTDt:-OAqzhmK9IbW0v3cwTDu:b-rn6qwk) (no related file):*
Does Dispatcher give to the reader a better sense of what the trait does? I think I prefer Provider in this case.

___

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1778)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @alonh5)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1778#-OAqzhmK9IbW0v3cwTDt:-OArLqoA07NA_8KDq4Pt:bp0khrc) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Does Dispatcher give to the reader a better sense of what the trait does? I think I prefer Provider in this case.
</blockquote></details>

Lol, I actually tend to agree. TransactionProvider is a good name.

___

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1778)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1778#-OAqzhmK9IbW0v3cwTDt:-OB4equvBetFZ44U07NM:b-6g9yt4) (no related file):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Lol, I actually tend to agree. TransactionProvider is a good name.
</blockquote></details>

Close this PR?

___

**Pull request closed without merging**
