### PR TITLE
feat(committer): use FilledTree::create() in filled forest

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/495)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware 
second half of this PR:
https://reviewable.io/reviews/starkware-libs/sequencer/471

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/495#-:-O4_opSGD18BI3_oGSBu:b79598g)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/495)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/starknet_committer/src/block_committer/input.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/495#-O4dxoe3EYocH4Auwinc:-O4dxoe3EYocH4Auwind:b-xxt5jt) ([raw file](https://github.com/starkware-libs/sequencer/blob/dc3e396a599798c629b8803bc417c32da9ab9231/crates/starknet_committer/src/block_committer/input.rs#L19)):*
> ```XML
> impl From<&NodeIndex> for ContractAddress {
>     fn from(node_index: &NodeIndex) -> ContractAddress {
>         assert!(node_index.is_leaf(), "NodeIndex {:?} is not a leaf.", node_index);
> ```

if you need to `assert`, maybe you should consider implementing `TryFrom` instead of `From`...?



_Code quote:_
```XML
impl From<&NodeIndex> for ContractAddress {
    fn from(node_index: &NodeIndex) -> ContractAddress {
        assert!(node_index.is_leaf(), "NodeIndex {:?} is not a leaf.", node_index);
```
___
*[`crates/starknet_committer/src/block_committer/input.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/495#-O4dxxMW45_8IVe4Bjgu:-O4dxxMW45_8IVe4Bjgv:b8zbhlg) ([raw file](https://github.com/starkware-libs/sequencer/blob/dc3e396a599798c629b8803bc417c32da9ab9231/crates/starknet_committer/src/block_committer/input.rs#L23)):*
> ```XML
>             Felt::try_from(*node_index - NodeIndex::FIRST_LEAF)
>                 .expect("Unable to convert node index to felt."),
>         )
> ```

there is a computation here... please add a unit test for some valid values and edge cases.
if you convert this to a TryFrom implementation, also test some invalid cases please



_Code quote:_
```XML
        ContractAddress(
            Felt::try_from(*node_index - NodeIndex::FIRST_LEAF)
                .expect("Unable to convert node index to felt."),
        )
```
___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/495#-O4edF7CEQiS2YjKDNj0:-O4edF7CEQiS2YjKDNj1:b-91u1jc) ([raw file](https://github.com/starkware-libs/sequencer/blob/dc3e396a599798c629b8803bc417c32da9ab9231/crates/starknet_committer/src/forest/filled_forest.rs#L81)):*
> ```XML
>         let (contracts_trie, storage_tries) =
>             contracts_trie_task.await?.map_err(ForestError::ContractsTrie)?;
>         let classes_trie = classes_trie_task.await?.map_err(ForestError::ClassesTrie)?;
> ```

there are already running (in parallel) and it doesn't matter that you await each one separately, right?



_Code quote:_
```XML
        let (contracts_trie, storage_tries) =
            contracts_trie_task.await?.map_err(ForestError::ContractsTrie)?;
        let classes_trie = classes_trie_task.await?.map_err(ForestError::ClassesTrie)?;
```
___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/495#-O4edQmuAtnjnVLto6aZ:-O4edQmuAtnjnVLto6a_:b-33rtfr) ([raw file](https://github.com/starkware-libs/sequencer/blob/dc3e396a599798c629b8803bc417c32da9ab9231/crates/starknet_committer/src/forest/filled_forest.rs#L81)):*
> ```XML
>         let (contracts_trie, storage_tries) =
>             contracts_trie_task.await?.map_err(ForestError::ContractsTrie)?;
>         let classes_trie = classes_trie_task.await?.map_err(ForestError::ClassesTrie)?;
> ```

consider:
1. swapping the order of `await`s
2. adding logs

the classes trie will probably finish before the contracts trie (height 251 vs 502), so better to await it first



_Suggestion:_
```XML
        let classes_trie = classes_trie_task.await?.map_err(ForestError::ClassesTrie)?;
        log::???!("Classes trie update complete; {x} new facts computed.");
        let (contracts_trie, storage_tries) =
            contracts_trie_task.await?.map_err(ForestError::ContractsTrie)?;
        log::???!("Contracts trie update complete; {x} new facts computed.");
```
___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/495#-O4ebC801ZWYKqIE3IYb:-O4ebC801ZWYKqIE3IYc:b85d0fu) ([raw file](https://github.com/starkware-libs/sequencer/blob/dc3e396a599798c629b8803bc417c32da9ab9231/crates/starknet_committer/src/forest/filled_forest.rs#L109)):*
> ```XML
>             contract_address_to_storage_updates.len(),
>             contract_address_to_storage_skeleton.len()
>         );
> ```

please add an informative message if this assert fails



_Code quote:_
```XML
        assert_eq!(
            contract_address_to_storage_updates.len(),
            contract_address_to_storage_skeleton.len()
        );
```
___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/495#-O4ebpz-11uFATNo0lQY:-O4ebpz02rnA4izgN1cW:b-t147uv) ([raw file](https://github.com/starkware-libs/sequencer/blob/dc3e396a599798c629b8803bc417c32da9ab9231/crates/starknet_committer/src/forest/filled_forest.rs#L131)):*
> ```XML
>                         .ok_or(ForestError::MissingUpdatedSkeleton(contract_address))?,
>                     storage_updates,
>                 ),
> ```

this 4-tuple is IMO not a very nice way to describe a type...
can you open another PR on top of the current tip of your stack, to convert this 4-tuple to a struct with named fields?



_Code quote:_
```XML
                (
                    node_index,
                    *(address_to_nonce
                        .get(&contract_address)
                        .unwrap_or(&original_contract_state.nonce)),
                    *(address_to_class_hash
                        .get(&contract_address)
                        .unwrap_or(&original_contract_state.class_hash)),
                    contract_address_to_storage_skeleton
                        .remove(&contract_address)
                        .ok_or(ForestError::MissingUpdatedSkeleton(contract_address))?,
                    storage_updates,
                ),
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/495)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/starknet_committer/src/block_committer/input.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/495#-O4dxoe3EYocH4Auwinc:-O4evrLwExeY4L8bHMcV:b-orumjy) ([raw file](https://github.com/starkware-libs/sequencer/blob/dc3e396a599798c629b8803bc417c32da9ab9231/crates/starknet_committer/src/block_committer/input.rs#L19)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you need to `assert`, maybe you should consider implementing `TryFrom` instead of `From`...?
</blockquote></details>

Good point
___
*[`crates/starknet_committer/src/block_committer/input.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/495#-O4dxxMW45_8IVe4Bjgu:-O4j0gaT2QI5BPeuSEIG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dc3e396a599798c629b8803bc417c32da9ab9231/crates/starknet_committer/src/block_committer/input.rs#L23)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there is a computation here... please add a unit test for some valid values and edge cases.
if you convert this to a TryFrom implementation, also test some invalid cases please
</blockquote></details>

Done.
___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/495#-O4edF7CEQiS2YjKDNj0:-O4j6WKp2jPta_CSa6nG:b-7jzv7t) ([raw file](https://github.com/starkware-libs/sequencer/blob/dc3e396a599798c629b8803bc417c32da9ab9231/crates/starknet_committer/src/forest/filled_forest.rs#L81)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there are already running (in parallel) and it doesn't matter that you await each one separately, right?
</blockquote></details>

right
___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/495#-O4edQmuAtnjnVLto6aZ:-O4j8RWXDIlBh2rPuGjm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dc3e396a599798c629b8803bc417c32da9ab9231/crates/starknet_committer/src/forest/filled_forest.rs#L81)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

consider:
1. swapping the order of `await`s
2. adding logs

the classes trie will probably finish before the contracts trie (height 251 vs 502), so better to await it first
</blockquote></details>

Done.
___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/495#-O4ebC801ZWYKqIE3IYb:-O4j9ifo3_2rviiDwZZ9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dc3e396a599798c629b8803bc417c32da9ab9231/crates/starknet_committer/src/forest/filled_forest.rs#L109)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add an informative message if this assert fails
</blockquote></details>

Done.
___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/495#-O4ebpz-11uFATNo0lQY:-O4j9mQLEkrruEaXhNuf:b-5wkuq4) ([raw file](https://github.com/starkware-libs/sequencer/blob/dc3e396a599798c629b8803bc417c32da9ab9231/crates/starknet_committer/src/forest/filled_forest.rs#L131)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this 4-tuple is IMO not a very nice way to describe a type...
can you open another PR on top of the current tip of your stack, to convert this 4-tuple to a struct with named fields?
</blockquote></details>

Will do and paste link here

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/495)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/495#-O4ebpz-11uFATNo0lQY:-O4jI2_U8IlsxOyh-GpY:bv2fri5) ([raw file](https://github.com/starkware-libs/sequencer/blob/dc3e396a599798c629b8803bc417c32da9ab9231/crates/starknet_committer/src/forest/filled_forest.rs#L131)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Will do and paste link here
</blockquote></details>

Done.
https://reviewable.io/reviews/starkware-libs/sequencer/530

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/495)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 101 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/495#-O4jaJIV9uPNNyDcw9Jh:-O4jhdOo2FdC7w3Eya6C:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5335149d8e8497e8e3add2ab75c272a29b923267/crates/starknet_committer/src/forest/filled_forest.rs#L101)):*
> ```XML
>                                 "Got the following error when trying to convert node index {0:?} \
>                                  to a contract address: {1:?}",
>                                 node_index, error
> ```

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/495#-:-O4jlZIv0lk5aMBsezRB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
