### PR TITLE
feat(starknet_state_sync): pass new internal blocks from state sync to p2p sync client

### PR DESCRIPTION
**Pull request by AlonLStarkWare**

### CODE REVIEW

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2631#-:-ODkmp4RARhGIcmiQyeF:bnfp4nl)* status: 4 of 8 files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2631)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`crates/starknet_state_sync/src/runner/mod.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2631#-ODkolbO9aG4eD0xnm4X:-ODkolbP1M7ZRjoDIdrE:b-6ysdk3) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d8f02a07c1e312a5953ca460f96ad291ef5646a/crates/starknet_state_sync/src/runner/mod.rs#L74)):*
> ```XML
>             storage_writer,
>             p2p_sync_client_channels,
>             Box::pin(new_block_receiver),
> ```

use .boxed() instead
___
*[`crates/starknet_state_sync_types/src/errors.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2631#-ODl2Nzd71P7tWoLkbcs:-ODl2Nzd71P7tWoLkbct:b-pjbou7) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d8f02a07c1e312a5953ca460f96ad291ef5646a/crates/starknet_state_sync_types/src/errors.rs#L14)):*
> ```XML
>     StorageError(String),
>     #[error("Failed to send message to P2pSyncClient")]
>     P2PSyncClientError,
> ```

Read the comment above on the StorageError. The reason we did not use `#[error(transparent)]` and used the direct error in StorageError is because StorageError does not derive stuff


If your error type also doesn't derive these, copy the comment and change the type to string and implement the conversion manually
If it does, just contain the error and the `#[error(transparent)]` will implement the From by itself

Please note that in a different comment in the PR I wrote about changing the error here
___
*[`crates/starknet_state_sync/src/lib.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2631#-ODkou0HEfxIAmW8aH_Y:-ODkou0HEfxIAmW8aH_Z:b-dxhhhq) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d8f02a07c1e312a5953ca460f96ad291ef5646a/crates/starknet_state_sync/src/lib.rs#L50)):*
> ```XML
>                         .send((block_number, sync_block))
>                         .await
>                         .map_err(|_| StateSyncError::P2PSyncClientError),
> ```

This is a send error. not a sync client error
___
*[`crates/starknet_state_sync/src/lib.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2631#-ODl373lDEAmdTsnmQTb:-ODl373lDEAmdTsnmQTc:bqfe6xf) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d8f02a07c1e312a5953ca460f96ad291ef5646a/crates/starknet_state_sync/src/lib.rs#L50)):*
> ```XML
>                         .send((block_number, sync_block))
>                         .await
>                         .map_err(|_| StateSyncError::P2PSyncClientError),
> ```

If you implement error conversion like I said below, you can just use ? instead of map_err or use into()

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2631)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @eitanm-starkware and @ShahakShama)

___
*[`crates/starknet_state_sync/src/lib.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2631#-ODkou0HEfxIAmW8aH_Y:-ODlLPWe2cPWMAwUocIl:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d8f02a07c1e312a5953ca460f96ad291ef5646a/crates/starknet_state_sync/src/lib.rs#L50)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is a send error. not a sync client error
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync/src/lib.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2631#-ODl373lDEAmdTsnmQTb:-ODlLPtBB6diA3RZLv8t:b-3gdurj) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d8f02a07c1e312a5953ca460f96ad291ef5646a/crates/starknet_state_sync/src/lib.rs#L50)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

If you implement error conversion like I said below, you can just use ? instead of map_err or use into()
</blockquote></details>

SendError does not implement Deserialize so I changed to `from`
___
*[`crates/starknet_state_sync/src/runner/mod.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2631#-ODkolbO9aG4eD0xnm4X:-ODl9KnW0G766DsWZLEA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d8f02a07c1e312a5953ca460f96ad291ef5646a/crates/starknet_state_sync/src/runner/mod.rs#L74)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

use .boxed() instead
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync_types/src/errors.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2631#-ODl2Nzd71P7tWoLkbcs:-ODlLaQhCOKGhj0slU3f:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d8f02a07c1e312a5953ca460f96ad291ef5646a/crates/starknet_state_sync_types/src/errors.rs#L14)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Read the comment above on the StorageError. The reason we did not use `#[error(transparent)]` and used the direct error in StorageError is because StorageError does not derive stuff


If your error type also doesn't derive these, copy the comment and change the type to string and implement the conversion manually
If it does, just contain the error and the `#[error(transparent)]` will implement the From by itself

Please note that in a different comment in the PR I wrote about changing the error here
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2631)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare)

___
*[`crates/starknet_state_sync_types/src/errors.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2631#-ODl2Nzd71P7tWoLkbcs:-OE89H-uEKxOoLOF2VDw:bulfz56) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d8f02a07c1e312a5953ca460f96ad291ef5646a/crates/starknet_state_sync_types/src/errors.rs#L14)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Copy the comment

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2631)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/starknet_state_sync_types/src/errors.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2631#-ODl2Nzd71P7tWoLkbcs:-OE8Zu1Q-V-6ANuj4Ba6:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d8f02a07c1e312a5953ca460f96ad291ef5646a/crates/starknet_state_sync_types/src/errors.rs#L14)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Copy the comment
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
> Reviewed 4 of 5 files at r7, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2631)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2631#-:-OE8dOML8von1CftKrH-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2631)* status: 4 of 9 files reviewed, 3 unresolved discussions (waiting on @AlonLStarkWare and @ShahakShama)

___
*[`crates/starknet_state_sync/src/runner/mod.rs` line 46 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2631#-OEETmXL0joJg9uDWrqX:-OEETmXL0joJg9uDWrqY:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/92a266c344055ef77d25b07a27b9d1d6182900b6/crates/starknet_state_sync/src/runner/mod.rs#L46)):*
> ```XML
>     pub fn new(
>         config: StateSyncConfig,
>         new_block_receiver: Receiver<(BlockNumber, SyncBlock)>,
> ```





_Suggestion:_
```XML
internal
```
___
*[`crates/starknet_state_sync/src/runner/mod.rs` line 75 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2631#-OEETwEk64Ie-ZStBOsa:-OEETwEk64Ie-ZStBOsb:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/92a266c344055ef77d25b07a27b9d1d6182900b6/crates/starknet_state_sync/src/runner/mod.rs#L75)):*
> ```XML
>             storage_writer,
>             p2p_sync_client_channels,
>             new_block_receiver.boxed(),
> ```





_Suggestion:_
```XML
internal
```
___
*[`crates/starknet_state_sync/src/lib.rs` line 34 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2631#-OEEU4SB-PvALesRohoS:-OEEU4SB-PvALesRohoT:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/92a266c344055ef77d25b07a27b9d1d6182900b6/crates/starknet_state_sync/src/lib.rs#L34)):*
> ```XML
> pub struct StateSync {
>     storage_reader: StorageReader,
>     new_block_sender: Sender<(BlockNumber, SyncBlock)>,
> ```





_Suggestion:_
```XML
internal
```

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 9 files at r13, 9 of 9 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2631)* status: all files reviewed, 4 unresolved discussions (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`crates/starknet_state_sync/src/lib.rs` line 25 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/2631#-OEiFKhLDixhpawPXA2X:-OEiFKhLDixhpawPXA2Y:b7q0saz) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f03e118b3cddb477703d51626db6b5b6c1b86b5/crates/starknet_state_sync/src/lib.rs#L25)):*
> ```XML
>     let (new_block_sender, new_block_receiver) = channel(BUFFER_SIZE);
>     let (state_sync_runner, storage_reader) = StateSyncRunner::new(config, new_block_receiver);
>     (StateSync { storage_reader, new_block_sender }, state_sync_runner)
> ```

Consider defining StateSync at a separate line now that its definition becomes as long as the runner's definition
___
*[`crates/starknet_state_sync/src/runner/mod.rs` line 46 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2631#-OEETmXL0joJg9uDWrqX:-OEiF8116KRI1XaPwt-h:bmy0w61) ([raw file](https://github.com/starkware-libs/sequencer/blob/92a266c344055ef77d25b07a27b9d1d6182900b6/crates/starknet_state_sync/src/runner/mod.rs#L46)):*
> ```XML
>     pub fn new(
>         config: StateSyncConfig,
>         new_block_receiver: Receiver<(BlockNumber, SyncBlock)>,
> ```

Here it's better calling it new
___
*[`crates/starknet_state_sync/src/runner/mod.rs` line 75 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/2631#-OEETwEk64Ie-ZStBOsa:-OEiFA3V9tWtJB7-TOKy:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/92a266c344055ef77d25b07a27b9d1d6182900b6/crates/starknet_state_sync/src/runner/mod.rs#L75)):*
> ```XML
>             storage_writer,
>             p2p_sync_client_channels,
>             new_block_receiver.boxed(),
> ```

same

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2631#-:-OEiQWaK3lcgLLQUrGuN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Pull request merged**
