### PR TITLE
feat(starknet_gateway): implement sync state reader get block info

### PR DESCRIPTION
**Pull request by noamsp-starkware**

### CODE REVIEW

**Comment by noamsp-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2942?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2944** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2944?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2942** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2942?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2942?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2963** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2963?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2886](https://github.com/starkware-libs/sequencer/pull/2886) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2886?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2979** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2979?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2942)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware and @noamsp-starkware)

___
*[`crates/starknet_gateway/src/sync_state_reader.rs` line 53 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2942#-OFLm-vk6JjeSoA4ikZZ:-OFLm-vk6JjeSoA4ikZ_:b-1mru9a) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c370b3c921580a95269510f369592d23ff40e2e/crates/starknet_gateway/src/sync_state_reader.rs#L53)):*
> ```XML
>                 },
>             },
>             use_kzg_da: matches!(block_header.l1_da_mode, L1DataAvailabilityMode::Blob),
> ```

This will compile if someone adds a variant to L1DataAvailabilityMode, and I want it to not compile in that case so that the person who added a variant will TAL at this code and decide what's right

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2942)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware and @noamsp-starkware)

___
*[`crates/starknet_gateway/src/sync_state_reader.rs` line 53 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2942#-OFLm-vk6JjeSoA4ikZZ:-OFLm1_D2jekief5NS9-:b-fcqnmz) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c370b3c921580a95269510f369592d23ff40e2e/crates/starknet_gateway/src/sync_state_reader.rs#L53)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This will compile if someone adds a variant to L1DataAvailabilityMode, and I want it to not compile in that case so that the person who added a variant will TAL at this code and decide what's right
</blockquote></details>

Leaving unblocking so that if you fix it and Eitan approves you can merge

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2942)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware and @ShahakShama)

___
*[`crates/starknet_gateway/src/sync_state_reader.rs` line 53 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2942#-OFLm-vk6JjeSoA4ikZZ:-OFLsNP491YqbT0e0zuz:bt2vr0b) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c370b3c921580a95269510f369592d23ff40e2e/crates/starknet_gateway/src/sync_state_reader.rs#L53)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Leaving unblocking so that if you fix it and Eitan approves you can merge
</blockquote></details>

Fixed

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2942#-:-OFMH4V53H_iuTLtSRsg:bnfp4nl)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/starknet_gateway/src/sync_state_reader.rs` line 34 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2942#-OFMFrVb7zttVjyNR4yR:-OFMFrVb7zttVjyNR4yS:b-c512a4) ([raw file](https://github.com/starkware-libs/sequencer/blob/505f90da7a5bfa9960816efaa509c861f77eb792/crates/starknet_gateway/src/sync_state_reader.rs#L34)):*
> ```XML
>         let block = block_on(self.state_sync_client.get_block(self.block_number))
>             .map_err(|e| StateError::StateReadError(e.to_string()))?
>             .ok_or(StateError::StateReadError("Block not found".to_string()))?;
> ```

ok_or_else isnt eager  - better practice to use it when there is a fn calculated in the brackets. leaving unblocking



_Suggestion:_
```XML
ok_or_else(||
```

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2942)* status: 4 of 7 files reviewed, all discussions resolved (waiting on @eitanm-starkware and @ShahakShama)

___
*[`crates/starknet_gateway/src/sync_state_reader.rs` line 34 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2942#-OFMFrVb7zttVjyNR4yR:-OFMRcm8EeCsTKtikK75:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/505f90da7a5bfa9960816efaa509c861f77eb792/crates/starknet_gateway/src/sync_state_reader.rs#L34)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

ok_or_else isnt eager  - better practice to use it when there is a fn calculated in the brackets. leaving unblocking
</blockquote></details>

Done

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2942)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @eitanm-starkware)

___
*[`crates/starknet_gateway/src/sync_state_reader.rs` line 34 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2942#-OFMFrVb7zttVjyNR4yR:-OFMLc586rW9F_cLQ1Wg:b-s1e6wz) ([raw file](https://github.com/starkware-libs/sequencer/blob/505f90da7a5bfa9960816efaa509c861f77eb792/crates/starknet_gateway/src/sync_state_reader.rs#L34)):*
<details><summary><i>Previously, noamsp-starkware wrote…</i></summary><blockquote>

Done
</blockquote></details>

No. It's actually better to do ok_or in this case. ok_or_else should only be used if the calculation is either heavy or it produces panic

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2942)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @eitanm-starkware)

___
*[`crates/starknet_gateway/src/sync_state_reader.rs` line 34 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2942#-OFMFrVb7zttVjyNR4yR:-OFMVJna-t4brBJ9-7ik:b-n67mzv) ([raw file](https://github.com/starkware-libs/sequencer/blob/505f90da7a5bfa9960816efaa509c861f77eb792/crates/starknet_gateway/src/sync_state_reader.rs#L34)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No. It's actually better to do ok_or in this case. ok_or_else should only be used if the calculation is either heavy or it produces panic
</blockquote></details>

Please revert

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2942)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2942#-:-OFMlnnT8DATL9hFXkEz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)

**Pull request merged**
