### PR TITLE
fix(committer): deserialize contract state without nonce

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1003)

### CODE REVIEW

**Review by AvivYossef-starkware — COMMENTED** [review]
[python](https://github.com/starkware-industries/starkware/pull/35984)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1003#-:-O7cAD8n2qSIniaXfOrb:b-hgmwaw)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1003)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_serde.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1003#-O7cLzbVEFor9YTiHIjo:-O7cLzbW1W_1PDUNNGDi:b-y7d1z7) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c8600797e9224bbb09b4da80e008a017e92bdb2/crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_serde.rs#L93)):*
> ```XML
>         };
>         let class_hash_as_hex = get_leaf_key(&deserialized_map, "contract_hash")?;
>         let nonce_as_hex = get_leaf_key(&deserialized_map, "nonce").unwrap_or("0x0".to_string());
> ```

please add a comment stating that ancient leaves - before the starknet protocol supported nonces - may be missing the nonce



_Code quote:_
```XML
let nonce_as_hex = get_leaf_key(&deserialized_map, "nonce").unwrap_or("0x0".to_string());
```
___
*[`crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_serde_test.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1003#-O7cMEXV4F4pqgQKPNeB:-O7cMEXV4F4pqgQKPNeC:b-kpdpyt) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c8600797e9224bbb09b4da80e008a017e92bdb2/crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_serde_test.rs#L31)):*
> ```XML
>    })
> ]
> ```

no newline between test parametrization and the test itself
___
*[`crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_serde_test.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1003#-O7cMM2YEwvF6wk0WpKQ:-O7cMM2Z5XkFmyaTYpik:b5nt955) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c8600797e9224bbb09b4da80e008a017e92bdb2/crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_serde_test.rs#L48)):*
> ```XML
> #[rstest]
> fn test_deserialize_contract_state_without_nonce() {
>     // Simulate a serialized JSON without the "nonce" field
> ```

end in punctuation



_Suggestion:_
```XML
// Simulate a serialized JSON without the "nonce" field.
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1003)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_serde.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1003#-O7cLzbVEFor9YTiHIjo:-O7cPQw48EykpVCIF5bA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c8600797e9224bbb09b4da80e008a017e92bdb2/crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_serde.rs#L93)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a comment stating that ancient leaves - before the starknet protocol supported nonces - may be missing the nonce
</blockquote></details>

Done.
___
*[`crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_serde_test.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1003#-O7cMEXV4F4pqgQKPNeB:-O7cNUbQDzIt__KVDlXX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c8600797e9224bbb09b4da80e008a017e92bdb2/crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_serde_test.rs#L31)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no newline between test parametrization and the test itself
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1003#-:-O7cQWsH9--4nUi-ZfXQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
