### PR TITLE
feat(mempool): implement pool capacity in transaction pool

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/transaction_pool.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4eokVt6VmbQjZ7TRfS:-O4eokVu1Zqp3MRJzxoJ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/13b63a788a6962154fa82af752a33d7ed3f3e868/crates/mempool/src/transaction_pool.rs#L81)):*
> ```XML
>                 );
>             });
>             self.capacity.remove();
> ```





_Suggestion:_
```XML
            });
            
            self.capacity.remove();
```
___
*[`crates/mempool/src/transaction_pool.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4enXJtCgNzdJVqgE1I:-O4eopxK19mOLCFw489g:b-q2b45) ([raw file](https://github.com/starkware-libs/sequencer/blob/13b63a788a6962154fa82af752a33d7ed3f3e868/crates/mempool/src/transaction_pool.rs#L180)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Use `checked_sub`, if possible.
</blockquote></details>

Also, this shouldn't happen; it's a bug, so maybe we should `panic`.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: all files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 829 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4et9mb6HJj01JqQoBL:-O4et9mb6HJj01JqQoBM:bkb790x) ([raw file](https://github.com/starkware-libs/sequencer/blob/13b63a788a6962154fa82af752a33d7ed3f3e868/crates/mempool/src/mempool_test.rs#L829)):*
> ```XML
>     add_tx(&mut mempool, &tx_1);
>     add_tx(&mut mempool, &tx_2);
>     assert_eq!(mempool._tx_pool().txs_count(), 2);
> ```

Still not very elegant. What does the web suggest?



_Code quote:_
```XML
_tx_pool()
```
___
*[`crates/mempool/src/mempool_test.rs` line 836 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4etZieBwsxfsSED6aZ:-O4etZieBwsxfsSED6a_:b-knvnqx) ([raw file](https://github.com/starkware-libs/sequencer/blob/13b63a788a6962154fa82af752a33d7ed3f3e868/crates/mempool/src/mempool_test.rs#L836)):*
> ```XML
> 
>     // Test and assert: remove the transactions, counter does not go below 0.
>     let _txs = mempool.get_txs(3).unwrap();
> ```

Can be removed?



_Code quote:_
```XML
let _txs = 
```
___
*[`crates/mempool/src/transaction_pool.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4etJjAEZTZlrcHU87D:-O4etJjAEZTZlrcHU87E:bwhauqh) ([raw file](https://github.com/starkware-libs/sequencer/blob/13b63a788a6962154fa82af752a33d7ed3f3e868/crates/mempool/src/transaction_pool.rs#L110)):*
> ```XML
>     pub(crate) fn _tx_pool(&self) -> &HashToTransaction {
>         &self.tx_pool
>     }
> ```

Is this needed?



_Code quote:_
```XML
    #[cfg(test)]
    pub(crate) fn _tx_pool(&self) -> &HashToTransaction {
        &self.tx_pool
    }
```
___
*[`crates/mempool/src/transaction_pool.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4etGGR58jzgsAGBMg4:-O4etGGR58jzgsAGBMg5:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/13b63a788a6962154fa82af752a33d7ed3f3e868/crates/mempool/src/transaction_pool.rs#L113)):*
> ```XML
> 
>     #[cfg(test)]
>     pub fn txs_count(&self) -> usize {
> ```





_Suggestion:_
```XML
n_txs
```
___
*[`crates/mempool/src/transaction_pool.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4etRP06-T0GMe19wx0:-O4etRP06-T0GMe19wx1:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/13b63a788a6962154fa82af752a33d7ed3f3e868/crates/mempool/src/transaction_pool.rs#L168)):*
> ```XML
> #[derive(Debug, Default, Eq, PartialEq)]
> pub struct PoolCapacity {
>     txs_counter: usize,
> ```





_Suggestion:_
```XML
n_txs
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 829 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4et9mb6HJj01JqQoBL:-O4f5URQ2NNSN-94x7zg:b-6573dw) ([raw file](https://github.com/starkware-libs/sequencer/blob/13b63a788a6962154fa82af752a33d7ed3f3e868/crates/mempool/src/mempool_test.rs#L829)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Still not very elegant. What does the web suggest?
</blockquote></details>

to implement something like 'tx_count' func in the mempool iteself:
`impl Mempool { pub fn tx_count(&self) -> usize { self.tx_pool.n_txs() } }`
I'm not sure it's better. wdyt?
___
*[`crates/mempool/src/transaction_pool.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4etJjAEZTZlrcHU87D:-O4eumCQ9wRKoAuAIK2o:b-vlbw3e) ([raw file](https://github.com/starkware-libs/sequencer/blob/13b63a788a6962154fa82af752a33d7ed3f3e868/crates/mempool/src/transaction_pool.rs#L110)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this needed?
</blockquote></details>

it's not being used. removed it in a different PR #525
___
*[`crates/mempool/src/transaction_pool.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4etGGR58jzgsAGBMg4:-O4f2T8dE5vHIV96Voy-:b-3iartg) ([raw file](https://github.com/starkware-libs/sequencer/blob/13b63a788a6962154fa82af752a33d7ed3f3e868/crates/mempool/src/transaction_pool.rs#L113)):*
> ```XML
> 
>     #[cfg(test)]
>     pub fn txs_count(&self) -> usize {
> ```

done, but why? Seems less readable IMO
___
*[`crates/mempool/src/transaction_pool.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4enXJtCgNzdJVqgE1I:-O4euKOG-TUU-ayGdi4u:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/13b63a788a6962154fa82af752a33d7ed3f3e868/crates/mempool/src/transaction_pool.rs#L180)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Also, this shouldn't happen; it's a bug, so maybe we should `panic`.
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 829 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4et9mb6HJj01JqQoBL:-O4jCm76860yvWrCrPHY:b2fvn77) ([raw file](https://github.com/starkware-libs/sequencer/blob/13b63a788a6962154fa82af752a33d7ed3f3e868/crates/mempool/src/mempool_test.rs#L829)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

to implement something like 'tx_count' func in the mempool iteself:
`impl Mempool { pub fn tx_count(&self) -> usize { self.tx_pool.n_txs() } }`
I'm not sure it's better. wdyt?
</blockquote></details>

A test util?
___
*[`crates/mempool/src/transaction_pool.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4etGGR58jzgsAGBMg4:-O4f8XZcCUj1HDQ44jbJ:b-2qk4pf) ([raw file](https://github.com/starkware-libs/sequencer/blob/13b63a788a6962154fa82af752a33d7ed3f3e868/crates/mempool/src/transaction_pool.rs#L113)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

done, but why? Seems less readable IMO
</blockquote></details>

Which one, both locations?
Why? 
___
*[`crates/mempool/src/transaction_pool.rs` line 163 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4jCgaX-ptuwp6pSbc_:-O4jCgaY5NtTxHJi-iPS:b-vvkobc) ([raw file](https://github.com/starkware-libs/sequencer/blob/897b26bed1e81cf1ab59dc6b9d00d154f8bd0848/crates/mempool/src/transaction_pool.rs#L163)):*
> ```XML
> 
> #[derive(Debug, Default, Eq, PartialEq)]
> pub struct PoolCapacity {
> ```

Is there an ergonomic counter object in Rust?



_Code quote:_
```XML
PoolCapacity
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 829 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4et9mb6HJj01JqQoBL:-O4nj_ry6wytqv4cDNdk:blnr1bw) ([raw file](https://github.com/starkware-libs/sequencer/blob/13b63a788a6962154fa82af752a33d7ed3f3e868/crates/mempool/src/mempool_test.rs#L829)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

A test util?
</blockquote></details>

this function will have `#[cfg(test)]` annotation
___
*[`crates/mempool/src/transaction_pool.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4etGGR58jzgsAGBMg4:-O4jgiz38Eupo4JL_0RN:b-xb5ufc) ([raw file](https://github.com/starkware-libs/sequencer/blob/13b63a788a6962154fa82af752a33d7ed3f3e868/crates/mempool/src/transaction_pool.rs#L113)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Which one, both locations?
Why?
</blockquote></details>

i think txs_count is clearer, but no strong opinion.
___
*[`crates/mempool/src/transaction_pool.rs` line 163 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4jCgaX-ptuwp6pSbc_:-O4njPt00NNVetevK9CY:bnyej3y) ([raw file](https://github.com/starkware-libs/sequencer/blob/897b26bed1e81cf1ab59dc6b9d00d154f8bd0848/crates/mempool/src/transaction_pool.rs#L163)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is there an ergonomic counter object in Rust?
</blockquote></details>

didn't find one

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 832 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4nz-l04ZgxLohP7t9p:-O4nz-l04ZgxLohP7t9q:bk0wqyi) ([raw file](https://github.com/starkware-libs/sequencer/blob/897b26bed1e81cf1ab59dc6b9d00d154f8bd0848/crates/mempool/src/mempool_test.rs#L832)):*
> ```XML
>     // Test and assert: remove the transactions, counter does not go below 0.
>     mempool.get_txs(3).unwrap();
>     assert_eq!(mempool._tx_pool().n_txs(), 0);
> ```

What about `commit_block`?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 832 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4nz-l04ZgxLohP7t9p:-O4oT7R91urp6KY1N5Ve:bbextx0) ([raw file](https://github.com/starkware-libs/sequencer/blob/897b26bed1e81cf1ab59dc6b9d00d154f8bd0848/crates/mempool/src/mempool_test.rs#L832)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What about `commit_block`?
</blockquote></details>

`commit_block` removes transactions from the pool in the `align_to_account_state` function, which we already check in `add_tx`. Do we need an additional specific check for this

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 832 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4nz-l04ZgxLohP7t9p:-O4on0WzEkTVeCQv6pnd:b-dgvt52) ([raw file](https://github.com/starkware-libs/sequencer/blob/897b26bed1e81cf1ab59dc6b9d00d154f8bd0848/crates/mempool/src/mempool_test.rs#L832)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

`commit_block` removes transactions from the pool in the `align_to_account_state` function, which we already check in `add_tx`. Do we need an additional specific check for this
</blockquote></details>

Yes, the public API does not include it; you can't assume that's the case (and that it'll stay like that).

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 832 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O4nz-l04ZgxLohP7t9p:-O58GaP01-_T2JKeSXFt:b-wit3gi) ([raw file](https://github.com/starkware-libs/sequencer/blob/897b26bed1e81cf1ab59dc6b9d00d154f8bd0848/crates/mempool/src/mempool_test.rs#L832)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Yes, the public API does not include it; you can't assume that's the case (and that it'll stay like that).
</blockquote></details>

Done.
Separated into a different test case because we need a non-empty mempool. It felt odd to add a usage of `mempool_content` here.

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 857 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O58_JY27LC3P0nACYzf:-O58_JY27LC3P0nACYzg:bfv2ubb) ([raw file](https://github.com/starkware-libs/sequencer/blob/baf6414faea15b0f6247d717e2b4fdc58618800a/crates/mempool/src/mempool_test.rs#L857)):*
> ```XML
> 
>     // Test and assert: duplicate transaction doesn't affect capacity.
>     assert_matches!(mempool.add_tx(input_1), Err(MempoolError::DuplicateTransaction { .. }));
> ```

please use `add_tx_expet_err` instead



_Code quote:_
```XML
 assert_matches!(mempool.add_tx(input_1), Err(MempoolError::DuplicateTransaction { .. }));
```
___
*[`crates/mempool/src/mempool_test.rs` line 866 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O58_Z3y7YLWW-c2xbYf:-O58_Z3y7YLWW-c2xbYg:b-6811tt) ([raw file](https://github.com/starkware-libs/sequencer/blob/baf6414faea15b0f6247d717e2b4fdc58618800a/crates/mempool/src/mempool_test.rs#L866)):*
> ```XML
> 
> #[rstest]
> fn test_tx_pool_capacity_in_commit_block() {
> ```

I think it can be in the same test, no need for separate test for commit_blcok.



_Code quote:_
```XML
 test_tx_pool_capacity_in_commit_block(
```
___
*[`crates/mempool/src/transaction_pool.rs` line 182 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O58ZqSi-hTzgrKACdz1:-O58ZqSi-hTzgrKACdz2:b-rqpuho) ([raw file](https://github.com/starkware-libs/sequencer/blob/baf6414faea15b0f6247d717e2b4fdc58618800a/crates/mempool/src/transaction_pool.rs#L182)):*
> ```XML
>     }
> 
>     fn remove(&mut self) {
> ```

I think the interface should be `self,tx`.
Also for `add` method.



_Code quote:_
```XML
 fn remove(&mut self)
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 866 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O58_Z3y7YLWW-c2xbYf:-O58in33A2i794cAjNEd:bjo52xm) ([raw file](https://github.com/starkware-libs/sequencer/blob/baf6414faea15b0f6247d717e2b4fdc58618800a/crates/mempool/src/mempool_test.rs#L866)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I think it can be in the same test, no need for separate test for commit_blcok.
</blockquote></details>

I feel like this test is getting too long, and the commit part doesn't seem directly related to the add and get flow. don't you think?
___
*[`crates/mempool/src/transaction_pool.rs` line 182 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O58ZqSi-hTzgrKACdz1:-O58ijIODXHZEQ0vR0pd:bb7r2f0) ([raw file](https://github.com/starkware-libs/sequencer/blob/baf6414faea15b0f6247d717e2b4fdc58618800a/crates/mempool/src/transaction_pool.rs#L182)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I think the interface should be `self,tx`.
Also for `add` method.
</blockquote></details>

why?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 857 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O58_JY27LC3P0nACYzf:-O58l8DnCNZq4x8078UZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/baf6414faea15b0f6247d717e2b4fdc58618800a/crates/mempool/src/mempool_test.rs#L857)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

please use `add_tx_expet_err` instead
</blockquote></details>

Done.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 866 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O58_Z3y7YLWW-c2xbYf:-O59C2n7082dSffIDupG:b760okg) ([raw file](https://github.com/starkware-libs/sequencer/blob/baf6414faea15b0f6247d717e2b4fdc58618800a/crates/mempool/src/mempool_test.rs#L866)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I feel like this test is getting too long, and the commit part doesn't seem directly related to the add and get flow. don't you think?
</blockquote></details>

I think you only need to add 3 lines to the above test:

 let state_changes =
        HashMap::from([(contract_address!("0x0"), AccountState { nonce: Nonce(felt!(4_u8)) })]);
    assert!(mempool.commit_block(state_changes).is_ok());
    assert_eq!(mempool._tx_pool().n_txs(), 0);

I think it's better than two tests.
Non-blocking, it's up to you.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 874 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O59CMaD1La259uEuaIo:-O59CMaD1La259uEuaIp:bj6uftj) ([raw file](https://github.com/starkware-libs/sequencer/blob/a39013d4ae5d7b5a188ab66816cf83e0b8658131/crates/mempool/src/mempool_test.rs#L874)):*
> ```XML
>     let input =
>         add_tx_input!(tx_hash: 0, sender_address: 0_u8, tx_nonce: 0_u8, account_nonce: 0_u8);
>     let pool_txs = [input.tx];
> ```

no need for this variable.



_Code quote:_
```XML
let pool_txs = [input.tx];
```
___
*[`crates/mempool/src/transaction_pool.rs` line 182 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O58ZqSi-hTzgrKACdz1:-O59CZJV9ZQkcpxIC98Y:bb5slh8) ([raw file](https://github.com/starkware-libs/sequencer/blob/baf6414faea15b0f6247d717e2b4fdc58618800a/crates/mempool/src/transaction_pool.rs#L182)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why?
</blockquote></details>

Because, next you'll add the actual tx size, not only the number.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 866 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O58_Z3y7YLWW-c2xbYf:-O5D8YqV3HD8_LgUkp-B:bwzqmt) ([raw file](https://github.com/starkware-libs/sequencer/blob/baf6414faea15b0f6247d717e2b4fdc58618800a/crates/mempool/src/mempool_test.rs#L866)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I think you only need to add 3 lines to the above test:

 let state_changes =
        HashMap::from([(contract_address!("0x0"), AccountState { nonce: Nonce(felt!(4_u8)) })]);
    assert!(mempool.commit_block(state_changes).is_ok());
    assert_eq!(mempool._tx_pool().n_txs(), 0);

I think it's better than two tests.
Non-blocking, it's up to you.
</blockquote></details>

It's more than 3 lines because the mempool must have transactions from this account to update the count. This requires adding transactions to the mempool or creating a mempool with these transactions, which feels unrelated to the start of the test. It's a new setup.
___
*[`crates/mempool/src/transaction_pool.rs` line 182 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O58ZqSi-hTzgrKACdz1:-O5D8DigDLMqOUMnjgf6:b5u6ih4) ([raw file](https://github.com/starkware-libs/sequencer/blob/baf6414faea15b0f6247d717e2b4fdc58618800a/crates/mempool/src/transaction_pool.rs#L182)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Because, next you'll add the actual tx size, not only the number.
</blockquote></details>

Wouldn't it be better to add it when it's actually needed? I'm not a fan of premature optimizations.

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 866 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O58_Z3y7YLWW-c2xbYf:-O5I-mRs0tQfztk_aPG_:b-1e4ur1) ([raw file](https://github.com/starkware-libs/sequencer/blob/baf6414faea15b0f6247d717e2b4fdc58618800a/crates/mempool/src/mempool_test.rs#L866)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

It's more than 3 lines because the mempool must have transactions from this account to update the count. This requires adding transactions to the mempool or creating a mempool with these transactions, which feels unrelated to the start of the test. It's a new setup.
</blockquote></details>

Discussed F2F.
We decide to have a single test, the flow is as follow:
1. add tx_1, tx_2
2. check size
3. commit block that removes one tx from the queue
4. check size
5. get_txs(2)
6. check size

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 868 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/513#-O5I1j7G4pA9AqlkbV5w:-O5I2WiV7iQt38o_9Fix:bb68cpj) ([raw file](https://github.com/starkware-libs/sequencer/blob/edfd1a5ea1c76e0e466f0199aa98e3480739da53/crates/mempool/src/mempool_test.rs#L868)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

remove "_"
</blockquote></details>

#610

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/513)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
