### PR TITLE
chore(blockifier): move contract compilation logic to separate module + contracts.rs

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/180)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/180?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#182** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/182?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#181** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/181?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#180** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/180?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#179** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/179?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/180)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, @meship-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/180#-O32MLqV9hQBKlZA_NQu:-O32MLqV9hQBKlZA_NQv:b57gq02) ([raw file](https://github.com/starkware-libs/sequencer/blob/244da0c1cbec592424d188036e57c289ec190093/crates/blockifier/src/test_utils/cairo_compile.rs#L5)):*
> ```XML
> /// Compiles a Cairo0 program using the deprecated compiler.
> pub fn cairo0_compile(path: String, extra_arg: Option<String>, debug_info: bool) -> Vec<u8> {
>     let mut command = Command::new("starknet-compile-deprecated");
> ```

Consider defining it as a constant



_Code quote:_
```XML
"starknet-compile-deprecated"
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 273 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/180#-O32NoQ82GO0sjaVPK-p:-O32NoQ9A1iBiCnLrRVL:b-6dwr30) ([raw file](https://github.com/starkware-libs/sequencer/blob/244da0c1cbec592424d188036e57c289ec190093/crates/blockifier/src/test_utils/contracts.rs#L273)):*
> ```XML
>                     FeatureContract::ERC20(_) => unreachable!(),
>                 };
>                 cairo0_compile(self.get_source_path(), extra_arg, false)
> ```

Shouldn't that be configurable by whoever calls `compile`?



_Code quote:_
```XML
 false
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/180)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware, @meship-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/180#-O32MLqV9hQBKlZA_NQu:-O32mcaM4ZOhXqqIw1we:bvnu13q) ([raw file](https://github.com/starkware-libs/sequencer/blob/244da0c1cbec592424d188036e57c289ec190093/crates/blockifier/src/test_utils/cairo_compile.rs#L5)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Consider defining it as a constant
</blockquote></details>

why? this is the only usage of this string
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 273 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/180#-O32NoQ82GO0sjaVPK-p:-O32mh9q832GiISIIxsE:bqn1s0i) ([raw file](https://github.com/starkware-libs/sequencer/blob/244da0c1cbec592424d188036e57c289ec190093/crates/blockifier/src/test_utils/contracts.rs#L273)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Shouldn't that be configurable by whoever calls `compile`?
</blockquote></details>

yes, but this is only a preparation; we currently have no use case for the `true` case (this is not a callable script, it's just part of tests ATM)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/180)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, and @meship-starkware)

___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/180#-O4-g0fe8iEKDWTUJN5V:-O4-g0ff7YFmNOoTFLui:b-6jgubi) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4fc3997f37e1a8c8ba647a94f67658e7d828352/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L48)):*
> ```XML
>         let mut command = Command::new("starknet-compile-deprecated");
>         command.args([&path_str, "--no_debug_info"]);
>         if file_name.starts_with("account") {
> ```

FaultyAccount didn't fulfill this condition in the past, and now it does—is this the desired behavior? (I assume so; I'm just verifying.)



_Code quote:_
```XML
file_name.starts_with("account")
```
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/180#-O4-ggGm-ul05myXdh1v:-O4-ggGm-ul05myXdh1w:b3kre) ([raw file](https://github.com/starkware-libs/sequencer/blob/11f058a2f5ee8b80a17832f5849ecf7466d1bd78/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L59)):*
> ```XML
>             panic!(
>                 "{} does not compile to {existing_compiled_path}.\nRun `{FIX_COMMAND}` to fix the \
>                  expected test according to locally installed `starknet-compile-deprecated`.\n",
> ```

?



_Suggestion:_
```XML
               existing file according
```
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 116 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/180#-O4-gxCa9EVcg0G60nvF:-O4-gxCa9EVcg0G60nvG:bigivbq) ([raw file](https://github.com/starkware-libs/sequencer/blob/11f058a2f5ee8b80a17832f5849ecf7466d1bd78/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L116)):*
> ```XML
>         .map(|contract| contract.get_compiled_path())
>         .collect();
>     let mut compiled_paths_on_filesystem: Vec<String> = verify_and_get_files(CairoVersion::Cairo0)
> ```

Do we really need to enforce the dir hierarchy?
Can't we be satisfied with verifying the contracts we get by `all_feature_contracts` and the source/compiled_path functions exist in the dir, and that's it? (I think it'll be nice if we can remove that function).



_Code quote:_
```XML
verify_and_get_files
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/180)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @meship-starkware, and @TzahiTaub)

___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/180#-O4-g0fe8iEKDWTUJN5V:-O4-jN71CmLWo-8EwPHh:b-5i5shy) ([raw file](https://github.com/starkware-libs/sequencer/blob/e4fc3997f37e1a8c8ba647a94f67658e7d828352/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L48)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

FaultyAccount didn't fulfill this condition in the past, and now it does—is this the desired behavior? (I assume so; I'm just verifying.)
</blockquote></details>

it should be compiled as an account, yes
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 116 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/180#-O4-gxCa9EVcg0G60nvF:-O4-jX2S-eNVQvTbjjoy:bp14c4g) ([raw file](https://github.com/starkware-libs/sequencer/blob/11f058a2f5ee8b80a17832f5849ecf7466d1bd78/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L116)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Do we really need to enforce the dir hierarchy?
Can't we be satisfied with verifying the contracts we get by `all_feature_contracts` and the source/compiled_path functions exist in the dir, and that's it? (I think it'll be nice if we can remove that function).
</blockquote></details>

I want to prevent the case where an untracked contract is manually added. it's possible to miss adding it to the enum; why not enforce it?

**Review by TzahiTaub — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/180)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware and @meship-starkware)

___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 116 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/180#-O4-gxCa9EVcg0G60nvF:-O4074XC8HfpyJcQQ8S-:b-us1d25) ([raw file](https://github.com/starkware-libs/sequencer/blob/11f058a2f5ee8b80a17832f5849ecf7466d1bd78/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L116)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I want to prevent the case where an untracked contract is manually added. it's possible to miss adding it to the enum; why not enforce it?
</blockquote></details>

OK, :thumbsup:

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Aug 11, 11:28 AM EDT**: @dorimedini-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/180).

**Pull request merged**
