### PR TITLE
chore: split the inner tx creator in blockifier test utils

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/660)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#661** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/661?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#660** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/660?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/660)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/test_utils/declare.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/660#-O60_FDiAeXx_Z7KmuSV:-O60_FDj6I5yAMToeAYf:bqksqjv) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d55175b53f35732180e923055d358b690012dd8/crates/blockifier/src/test_utils/declare.rs#L78)):*
> ```XML
> }
> 
> fn inner_declare_tx(
> ```

Please change the order of the functions. 
First, public methods, then private functions.

Also relevant for the below files.



_Code quote:_
```XML
fn inner_declare_tx(
```

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/660#-:-O60jzBf5lSGrQzDQ9iL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/test_utils/declare.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/660#-O60_FDiAeXx_Z7KmuSV:-O60jduH2D0NKAw9BWz-:bs5ctxt) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d55175b53f35732180e923055d358b690012dd8/crates/blockifier/src/test_utils/declare.rs#L78)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please change the order of the functions. 
First, public methods, then private functions.

Also relevant for the below files.
</blockquote></details>

If you plan to move this function to the sn-api crate, there is no need to reorder them in this PR.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/660)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/test_utils/declare.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/660#-O60_FDiAeXx_Z7KmuSV:-O60kBMg6zljw2r7JdCX:bhfi87x) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d55175b53f35732180e923055d358b690012dd8/crates/blockifier/src/test_utils/declare.rs#L78)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

If you plan to move this function to the sn-api crate, there is no need to reorder them in this PR.
</blockquote></details>

already done :) but TY!

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/660)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/test_utils/invoke.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/660#-O61AYTMAU1FSqjyclM7:-O61AYTMAU1FSqjyclM8:bd6jxkw) ([raw file](https://github.com/starkware-libs/sequencer/blob/53ca21d2863d77826829689359bbb456d90fc66e/crates/blockifier/src/test_utils/invoke.rs#L83)):*
> ```XML
> 
>     let default_tx_hash = TransactionHash::default();
>     match only_query {
> ```

No need for additional variable.



_Suggestion:_
```XML
    let invoke_tx = inner_invoke_tx(invoke_args);

    let default_tx_hash = TransactionHash::default();
    match invoke_args.only_query {
```

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/660)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/660#-O61Ain75giC-hAJVdXU:-O61Ain89iDXqIdrxQfE:biklrwo) ([raw file](https://github.com/starkware-libs/sequencer/blob/53ca21d2863d77826829689359bbb456d90fc66e/crates/blockifier/src/test_utils/deploy_account.rs#L88)):*
> ```XML
>     let tx = inner_deploy_account_tx(deploy_tx_args, nonce_manager.next(contract_address));
> 
>     DeployAccountTransaction::new(tx, TransactionHash::default(), contract_address)
> ```

Do you know why the `invoke` and `deploy account` do not have a tx hash field, while `declare` does?



_Code quote:_
```XML
TransactionHash::default()
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/660)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/660#-O61Ain75giC-hAJVdXU:-O61F-_h3uJ3Ew6bJ41k:b-6wifw7) ([raw file](https://github.com/starkware-libs/sequencer/blob/53ca21d2863d77826829689359bbb456d90fc66e/crates/blockifier/src/test_utils/deploy_account.rs#L88)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Do you know why the `invoke` and `deploy account` do not have a tx hash field, while `declare` does?
</blockquote></details>

I don't know. Let us keep the option available and streamline the util across tx types.
I did not find why this util is used in declare - I see no instance of it's use (I deleted it and the blockifier's tests passed).
___
*[`crates/blockifier/src/test_utils/invoke.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/660#-O61AYTMAU1FSqjyclM7:-O61DcVN7Ca8WUi4hPXJ:b-a5jm36) ([raw file](https://github.com/starkware-libs/sequencer/blob/53ca21d2863d77826829689359bbb456d90fc66e/crates/blockifier/src/test_utils/invoke.rs#L83)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

No need for additional variable.
</blockquote></details>

Your suggestion yields this error.

```
error[E0382]: use of moved value: `invoke_args`
  --> crates/blockifier/src/test_utils/invoke.rs:82:5
   |
78 | pub fn invoke_tx(invoke_args: InvokeTxArgs) -> InvokeTransaction {
   |                  ----------- move occurs because `invoke_args` has type `test_utils::invoke::InvokeTxArgs`, which does not implement the `Copy` trait
79 |     let invoke_tx = inner_invoke_tx(invoke_args);
   |                                     ----------- value moved here
...
82 |     match invoke_args.only_query {
```

#rust_things #blessed.

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/660)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/test_utils/invoke.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/660#-O61AYTMAU1FSqjyclM7:-O61aZtg7_C8PB5lX_ic:b2nhkw4) ([raw file](https://github.com/starkware-libs/sequencer/blob/53ca21d2863d77826829689359bbb456d90fc66e/crates/blockifier/src/test_utils/invoke.rs#L83)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Your suggestion yields this error.

```
error[E0382]: use of moved value: `invoke_args`
  --> crates/blockifier/src/test_utils/invoke.rs:82:5
   |
78 | pub fn invoke_tx(invoke_args: InvokeTxArgs) -> InvokeTransaction {
   |                  ----------- move occurs because `invoke_args` has type `test_utils::invoke::InvokeTxArgs`, which does not implement the `Copy` trait
79 |     let invoke_tx = inner_invoke_tx(invoke_args);
   |                                     ----------- value moved here
...
82 |     match invoke_args.only_query {
```

#rust_things #blessed.
</blockquote></details>

OMG

**Comment by ArniStarkware** [comment]
### Merge activity

* **Sep 8, 3:01 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/660).

**Pull request merged**
