### PR TITLE
chore(sequencer_node): set chain_id as required pointer param

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
commit-id:cce1bea9

---

**Stack**:
- #1598
- #1553
- #1536 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1536)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`config/mempool/default_config.json` line 697 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1536#-O9oKAs_EwiU16bgOoFS:-OAE8RpR5tDlRlDLOvI7:bwppwt3) ([raw file](https://github.com/starkware-libs/sequencer/blob/65e4ab82b0931d73ecb971fd4047b9b6883d9cac/config/mempool/default_config.json#L697)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add blank line at EOF.
</blockquote></details>

1. This file is auto-generated (`cargo run --bin sequencer_dump_config`)
2. Please let's discuss this in another scope as this is unrelated to this pr :pray: 
___
*[`crates/mempool_node/src/config/node_config.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1536#-O9oOegcBL4acPcsESQ9:-OAE8omt3ZFQmfQ3lROb:b4tbrq0) ([raw file](https://github.com/starkware-libs/sequencer/blob/65e4ab82b0931d73ecb971fd4047b9b6883d9cac/crates/mempool_node/src/config/node_config.rs#L88)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What is this addition?
</blockquote></details>

You are correct, this is redundant, and removed.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1536)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`config/mempool/default_config.json` line 203 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1536#-O9oLE0rB3N0pVQNCUCt:-OAE9KeKDqJoKhvjcbuV:b-fnq4cy) ([raw file](https://github.com/starkware-libs/sequencer/blob/65e4ab82b0931d73ecb971fd4047b9b6883d9cac/config/mempool/default_config.json#L203)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Do you want to add `required` as a field for values in this json? Where are you enforcing they are given?
</blockquote></details>

This prefix is auto-generated when you set a parameter as `required`.
Check https://github.com/starkware-libs/sequencer/blob/8fb108bf6a74c31cb59007a6727b94a4bc429905/crates/papyrus_config/src/dumping.rs#L309-L311

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1536)* status: all files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`config/mempool/default_config.json` line 203 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1536#-O9oLE0rB3N0pVQNCUCt:-OAH6FEV0SwuAxDNvYE7:b-h34t97) ([raw file](https://github.com/starkware-libs/sequencer/blob/65e4ab82b0931d73ecb971fd4047b9b6883d9cac/config/mempool/default_config.json#L203)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

This prefix is auto-generated when you set a parameter as `required`.
Check https://github.com/starkware-libs/sequencer/blob/8fb108bf6a74c31cb59007a6727b94a4bc429905/crates/papyrus_config/src/dumping.rs#L309-L311
</blockquote></details>

Yeah I saw, I was asking where it's enforced that the chain ID is actually given. Or is this added string the only difference?
We should also probably add a test to check the required params (see that it fails if you don't pass them). It could save a lot of debugging in the future.
___
*[`config/mempool/default_config.json` line 697 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1536#-O9oKAs_EwiU16bgOoFS:-OAH786j7pPQt1FJZbBI:b-cdlmg1) ([raw file](https://github.com/starkware-libs/sequencer/blob/65e4ab82b0931d73ecb971fd4047b9b6883d9cac/config/mempool/default_config.json#L697)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

1. This file is auto-generated (`cargo run --bin sequencer_dump_config`)
2. Please let's discuss this in another scope as this is unrelated to this pr :pray:
</blockquote></details>

Notice the empty line was deleted in this PR. AFAIK our style guide requires it, and also the formatter adds it in vscode.
Maybe we can add it to the executable in a different PR, and only restore the change here for now.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1536)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`config/mempool/default_config.json` line 203 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1536#-O9oLE0rB3N0pVQNCUCt:-OAHLI6k-tFxX-j9c4mD:b-27gfm0) ([raw file](https://github.com/starkware-libs/sequencer/blob/65e4ab82b0931d73ecb971fd4047b9b6883d9cac/config/mempool/default_config.json#L203)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Yeah I saw, I was asking where it's enforced that the chain ID is actually given. Or is this added string the only difference?
We should also probably add a test to check the required params (see that it fails if you don't pass them). It could save a lot of debugging in the future.
</blockquote></details>

The `main` fn calls `config_validate`, which fails if the required parameter is not found, example:

```
itay @ ~/workspace/sequencer5 (tsabary/config) $ cargo run --bin starknet_sequencer_node
warning: /home/itay/workspace/sequencer5/crates/papyrus_base_layer/Cargo.toml: `default-features` is ignored for test-with, since `default-features` was not specified for `workspace.dependencies.test-with`, this could become a hard error in the future
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.44s
     Running `target/debug/starknet_sequencer_node`
2024-10-28T09:03:25.433406Z  INFO Finished loading configuration.
Error: chain_id is not found.
```


TAL at https://github.com/starkware-libs/sequencer/blob/652c7e92f4f504e8e9d08d807e143a631377c2c6/crates/mempool_node/src/main.rs#L16-L27

I expect this to be resolved when we'll (finally) have a working integration test in the CI. Do you think we need a dedicated test just for that?
___
*[`config/mempool/default_config.json` line 697 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1536#-O9oKAs_EwiU16bgOoFS:-OAHP-MN8qUIqBMt4tX7:bx4zwpy) ([raw file](https://github.com/starkware-libs/sequencer/blob/65e4ab82b0931d73ecb971fd4047b9b6883d9cac/config/mempool/default_config.json#L697)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Notice the empty line was deleted in this PR. AFAIK our style guide requires it, and also the formatter adds it in vscode.
Maybe we can add it to the executable in a different PR, and only restore the change here for now.
</blockquote></details>

Right. There's something flakey here, I'll try addressing that in a different pr.
Anyhow, fixed the newline issue.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1536)* status: all files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`config/mempool/default_config.json` line 203 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1536#-O9oLE0rB3N0pVQNCUCt:-OAI2soH8how1N2TGTWO:bd69kv4) ([raw file](https://github.com/starkware-libs/sequencer/blob/65e4ab82b0931d73ecb971fd4047b9b6883d9cac/config/mempool/default_config.json#L203)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

The `main` fn calls `config_validate`, which fails if the required parameter is not found, example:

```
itay @ ~/workspace/sequencer5 (tsabary/config) $ cargo run --bin starknet_sequencer_node
warning: /home/itay/workspace/sequencer5/crates/papyrus_base_layer/Cargo.toml: `default-features` is ignored for test-with, since `default-features` was not specified for `workspace.dependencies.test-with`, this could become a hard error in the future
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.44s
     Running `target/debug/starknet_sequencer_node`
2024-10-28T09:03:25.433406Z  INFO Finished loading configuration.
Error: chain_id is not found.
```


TAL at https://github.com/starkware-libs/sequencer/blob/652c7e92f4f504e8e9d08d807e143a631377c2c6/crates/mempool_node/src/main.rs#L16-L27

I expect this to be resolved when we'll (finally) have a working integration test in the CI. Do you think we need a dedicated test just for that?
</blockquote></details>

Yeah I would add a unit test for all required fields, (esspecially because) I still couldn't find where the required is enforced, let's talk about it offline.
___
*[`config/mempool/default_config.json` line 277 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1536#-OAI2j6u1AzOMBbKbNGr:-OAI2j6u1AzOMBbKbNGs:b-lfpk6t) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb1a70b82d4aac479122ecf4be24737c0fec9dd6/config/mempool/default_config.json#L277)):*
> ```JSON
>     "value": true
>   },
>   "components.consensus_manager.execution_mode": {
> ```

What are these changes below?

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1536)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`config/mempool/default_config.json` line 203 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1536#-O9oLE0rB3N0pVQNCUCt:-OAJMQGv9KiZLunHdL8t:b9bwpcl) ([raw file](https://github.com/starkware-libs/sequencer/blob/65e4ab82b0931d73ecb971fd4047b9b6883d9cac/config/mempool/default_config.json#L203)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Yeah I would add a unit test for all required fields, (esspecially because) I still couldn't find where the required is enforced, let's talk about it offline.
</blockquote></details>

I added a todo to discuss that with you. If that's ok by you, I'd prefer to proceed with merging this and then discussing whether the current enforcement suffices :pray: 
(i.e., we're not worse off by not enforcing anyhow)
___
*[`config/mempool/default_config.json` line 277 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1536#-OAI2j6u1AzOMBbKbNGr:-OAJBxBR1IVwzHZ-HCgE:b-ijs9rw) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb1a70b82d4aac479122ecf4be24737c0fec9dd6/config/mempool/default_config.json#L277)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What are these changes below?
</blockquote></details>

Changes in the config structure. Please review from base to latest revision, these do not apply there.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1536)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
