### PR TITLE
chore(blockifier): remove dupl tip() and resource_bounds() in AccountTx

### PR DESCRIPTION
**Pull request by avivg-starkware**

### CODE REVIEW

**Comment by avivg-starkware** [comment]
* **#2102** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2102?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2101** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2101?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2101?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2101)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`crates/starknet_api/src/executable_transaction.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2101#-OBuBIyx4S12UEJU4jrF:-OBuBIyx4S12UEJU4jrG:bhlnh3p) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb05e10dd8af1be71fbca951f2b158cd2e7506d1/crates/starknet_api/src/executable_transaction.rs#L113)):*
> ```XML
>                 _ => None,
>             },
>         }
> ```

looks like this is already being handled as part of the implementation of  tx.tx.resource_bounds() (same for tip)



_Code snippet (i):_
```XML
implement_v3_tx_getters!(
        (resource_bounds, ValidResourceBounds),
```



_Code snippet (ii):_
```XML
macro_rules! implement_v3_tx_getters {
    ($(($field:ident, $field_type:ty)),*) => {
        $(pub fn $field(&self) -> $field_type {
            match self {
                Self::V3(tx) => tx.$field.clone(),
                _ => panic!("{:?} do not support the field {}; they are only available for V3 transactions.", self.version(), stringify!($field)),
            }
        })*
    };
}
```

**Comment by avivg-starkware** [comment]
*[`crates/starknet_api/src/executable_transaction.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2101#-OBuBIyx4S12UEJU4jrF:-OBuH-v75-Nq15MFq-wh:b-vkyo7d) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb05e10dd8af1be71fbca951f2b158cd2e7506d1/crates/starknet_api/src/executable_transaction.rs#L113)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

What does it mean?
</blockquote></details>

in both funcs above we're making sure that the field 'tx' of the enum AccountTransaction is of version v3.
This 'tx' is either 
starknet_api::transaction::InvokeTransaction  or  
starknet_api::transaction::DeployAccountTransaction or  
starknet_api::transaction::DeclareTransaction

However, for each of those, there is a func resource_bounds() which implements the above macro, and thus panicking if version != v3

there was a duplication, as the blockifier's AccountTransaction implementation didn't actually use the api's AccountTransaction's implementation of those funcs, but rather accessed 'directly' the implementation of  the starknet_api::transaction.

With that said, the key difference between the 2 implementations I see are: the use of panic vs except (w Option) and clone() vs passing a ref.

Perhaps better to leave things as they were?

**Comment by avivg-starkware** [comment]
*[`crates/blockifier/src/transaction/account_transaction.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2101#-OBuFaWeCa03RRupvVVH:-OBuLMlZ0zmB9o-4Dxwk:b-n211h3) ([raw file](https://github.com/starkware-libs/sequencer/blob/b436fefecea5fa5797be152983472a7172d3c1a9/crates/blockifier/src/transaction/account_transaction.rs#L113)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Is this still needed?
</blockquote></details>

Yes as all the below funcs are not implemented by 'Transaction' (= starknet_api::executable_transaction::AccountTransaction)



_Code snippet:_
```XML
        (signature, TransactionSignature),
        (nonce, Nonce),
        (nonce_data_availability_mode, DataAvailabilityMode),
        (fee_data_availability_mode, DataAvailabilityMode),
        (paymaster_data, PaymasterData)
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2101)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2101#-OBuFaWeCa03RRupvVVH:-OBuygSSCbFE2lNiXcnQ:b9k6anl) ([raw file](https://github.com/starkware-libs/sequencer/blob/b436fefecea5fa5797be152983472a7172d3c1a9/crates/blockifier/src/transaction/account_transaction.rs#L113)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

Yes as all the below funcs are not implemented by 'Transaction' (= starknet_api::executable_transaction::AccountTransaction)
</blockquote></details>

Can you use `implement_tx_getter_calls!` instead of `implement_account_tx_inner_getters!` now?
___
*[`crates/starknet_api/src/executable_transaction.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2101#-OBuBIyx4S12UEJU4jrF:-OBuxLBV66ru1m2_NvRw:b-hay2ib) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb05e10dd8af1be71fbca951f2b158cd2e7506d1/crates/starknet_api/src/executable_transaction.rs#L113)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

in both funcs above we're making sure that the field 'tx' of the enum AccountTransaction is of version v3.
This 'tx' is either 
starknet_api::transaction::InvokeTransaction  or  
starknet_api::transaction::DeployAccountTransaction or  
starknet_api::transaction::DeclareTransaction

However, for each of those, there is a func resource_bounds() which implements the above macro, and thus panicking if version != v3

there was a duplication, as the blockifier's AccountTransaction implementation didn't actually use the api's AccountTransaction's implementation of those funcs, but rather accessed 'directly' the implementation of  the starknet_api::transaction.

With that said, the key difference between the 2 implementations I see are: the use of panic vs except (w Option) and clone() vs passing a ref.

Perhaps better to leave things as they were?
</blockquote></details>

Thanks!

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2101#-:-OBv0BQTCz17rC_WXr23:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2101#-OBuFaWeCa03RRupvVVH:-OBv04V_ATxT0wrtIqBT:bgngttk) ([raw file](https://github.com/starkware-libs/sequencer/blob/b436fefecea5fa5797be152983472a7172d3c1a9/crates/blockifier/src/transaction/account_transaction.rs#L113)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you use `implement_tx_getter_calls!` instead of `implement_account_tx_inner_getters!` now?
</blockquote></details>

Oh you are doing it in a later PR, so LGTM as long as that future PR gets in :)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2101)* status: 2 of 3 files reviewed, all discussions resolved

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2101#-OBuFaWeCa03RRupvVVH:-OBv0Erk6C4fs6ck_6jY:b-w369y1) ([raw file](https://github.com/starkware-libs/sequencer/blob/b436fefecea5fa5797be152983472a7172d3c1a9/crates/blockifier/src/transaction/account_transaction.rs#L113)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Oh you are doing it in a later PR, so LGTM as long as that future PR gets in :)
</blockquote></details>

(Should have been part of this PR)

**Comment by avivg-starkware** [comment]
*[`crates/blockifier/src/transaction/account_transaction.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2101#-OBuFaWeCa03RRupvVVH:-OBvPVcn6FGB9bYBPXTb:bqldabo) ([raw file](https://github.com/starkware-libs/sequencer/blob/b436fefecea5fa5797be152983472a7172d3c1a9/crates/blockifier/src/transaction/account_transaction.rs#L113)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

(Should have been part of this PR)
</blockquote></details>

I see, will know for the next :)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2101)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2101#-:-OChJpmMEzKIhuCOGDV2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Pull request merged**
