### PR TITLE
refactor(starknet_batcher): create method clear previous proposals for code dedup

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2670)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alonh5 and @dafnamatsry)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2670#-OE9NRFPCAfkH8v9wAh2:-OE9NRFPCAfkH8v9wAh3:bjpb0oi) (no related file):*
@dafnamatsry - You said we can expect conflicts with your stack on this PR.
This PR aims to extract the `abort active height` logic into a function and share code.

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2670)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2670)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 235 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2670#-OEELDeo6S-FH2KxjZ8F:-OEELDeo6S-FH2KxjZ8G:b-7hbpla) ([raw file](https://github.com/starkware-libs/sequencer/blob/d1790d9ae13fbf22e4254b6afd1d26fc9bf7e9ae/crates/starknet_batcher/src/batcher.rs#L235)):*
> ```XML
> 
>     /// Clear all the proposals from the previous height.
>     async fn clear_previous_proposals(&mut self) {
> ```

wdyt?



_Suggestion:_
```XML
abort_active_height
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2670)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/starknet_batcher/src/batcher.rs` line 235 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2670#-OEELDeo6S-FH2KxjZ8F:-OEEMM111i5_lJQuoemE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d1790d9ae13fbf22e4254b6afd1d26fc9bf7e9ae/crates/starknet_batcher/src/batcher.rs#L235)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

wdyt?
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2670#-:-OEEMwya-SDiuhoqnoLF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
