### PR TITLE
chore: add create local server macro

### PR DESCRIPTION
**Pull request by nadin-Starkware**
**Stack**:
- #1909
- #1878
- #1877 ⬅
- #1876
- #1874

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1877)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/sequencer_node/src/servers.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1877#-OBA-3T73pThHYrsp2vL:-OBA-3T73pThHYrsp2vM:by2pcnu) ([raw file](https://github.com/starkware-libs/sequencer/blob/e076abd58c41911205f8a81bc081590ccda19287/crates/sequencer_node/src/servers.rs#L76)):*
> ```XML
> ///     None => println!("Server not created because the execution mode is disabled."),
> /// }
> /// ```
> ```

Same comments as for the previous macro :pray: 



_Code quote:_
```XML
/// A macro to create a LocalComponentServer based on the component's execution mode.
///
/// This macro conditionally creates a LocalComponentServer instance for a given component
/// and channel receiver, based on whether the execution mode is enabled or disabled.
///
/// # Arguments
///
/// * $execution_mode - A reference to the execution mode to evaluate, expected to be of type
///   &ComponentExecutionMode.
/// * $component - The optional component that will be taken to initialize the server if the mode is
///   enabled.
/// * $receiver - An expression to retrieve the channel receiver required for the server.
///
/// # Returns
///
/// An Option<Box<LocalComponentServer<ComponentType, RequestType, ResponseType>>> containing the
/// server if the execution mode is enabled, or None if the execution mode is Disabled.
///
/// # Example
///
/// ```rust,ignore
/// let batcher_server = create_local_server!(
///     &config.components.batcher.execution_mode,
///     components.batcher,
///     communication.take_batcher_rx()
/// );
/// match batcher_server {
///     Some(server) => println!("Server created: {:?}", server),
///     None => println!("Server not created because the execution mode is disabled."),
/// }
/// ```
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1877)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/sequencer_node/src/servers.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1877#-OBA-3T73pThHYrsp2vL:-OBL-1Mc3eafRsyW_vKl:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/02091331c22f0cff6d1ecf823532aaeefb970442/crates/sequencer_node/src/servers.rs#L76)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Same comments as for the previous macro :pray:
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1877#-:-OBLN6M-6ZkspZhIaihm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1877)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Comment by nadin-Starkware** [comment]
✓ Commit merged in pull request [#1909](https://github.com/starkware-libs/sequencer/pull/1909)

**Pull request closed without merging**
