### PR TITLE
fix(consensus): papyrus context repropose using streamed proposal channel

### PR DESCRIPTION
**Pull request by asmaastarkware**

### CODE REVIEW

**Review by guy-starkware — APPROVED** [review]
LGTM

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2826#-:-OEUM5je3Ho3oSJmOPSx:bb6ywmx)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2826)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2826#-OEV5sSJ5gP6ywhmeuMP:-OEV5sSK03WwsmMDBHhL:bfmthr7) ([raw file](https://github.com/starkware-libs/sequencer/blob/f41524a7146bd6e6ea01da29f7d3a6f5562ca9a8/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs#L81)):*
> ```XML
>         let proposal_init = ProposalInit { height: block_number, ..Default::default() };
>         papyrus_context.repropose(block.header.block_hash, proposal_init).await;
>     }
> ```

Add a comment explaining this effectively just checks that we can retrieve the proposal from `self.valid` and that the user doesn't see what's done with this



_Code quote:_
```XML
    if repropose {
        let proposal_init = ProposalInit { height: block_number, ..Default::default() };
        papyrus_context.repropose(block.header.block_hash, proposal_init).await;
    }
```

**Review by matan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2826)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2826)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
