### PR TITLE
chore: add macro for communication request/response matching

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/206)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/206)* status: 0 of 5 files reviewed, all discussions resolved

___
*[`crates/papyrus_network/src/bin_utils/mod.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/206#-O32pbK40zwJMsZiechr:-O32pbK40zwJMsZiechs:bx81l7n) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa6a7124efdf4036d9f33be345ac6d1d174e153f/crates/papyrus_network/src/bin_utils/mod.rs#L5)):*
> ```XML
> 
> use libp2p::identity::Keypair;
> use libp2p::swarm::dial_opts::DialOpts;
> ```

Removing an unused import, flagged by this pr.

**Review by uriel-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/206)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by ItayTsabary — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/206)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/206)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
