### PR TITLE
chore(mempool_node): separate server struct

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
commit-id:e8a80c55

---

**Stack**:
- #1111
- #1110
- #1109
- #1103
- #1102
- #1101
- #1100
- #1099
- #1098
- #1097
- #1096
- #1090
- #1089
- #1088
- #1058
- #1057 ⬅
- #1056
- #1027

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by lev-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1057)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/servers.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1057#-O7xmpKt4fpZR5b7ASdx:-O7xmpKu0GK_FyRB-7wI:b3kre) ([raw file](https://github.com/starkware-libs/sequencer/blob/22749dd853f096cc66ee6d9b9cb0f20f4003eda1/crates/mempool_node/src/servers.rs#L41)):*
> ```XML
> }
> 
> impl Servers {
> ```

?

**Review by lev-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1057#-:-O81ZPte6LTphb38HrzY:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1057)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/servers.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1057#-O7xmpKt4fpZR5b7ASdx:-O81dDEjC1Y_lxKcWCDx:bvldis0) ([raw file](https://github.com/starkware-libs/sequencer/blob/22749dd853f096cc66ee6d9b9cb0f20f4003eda1/crates/mempool_node/src/servers.rs#L41)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

I removed the `taker` functions, and then it occured to me why I added them to begin with: the e2e does not use the infra wrapper functions and accesses the servers directly. I didn't want to add `pub` visibility to the inner members to facilitate that, so I added the `taker` functions.
I agree that these were bad, so I ended up enabling `pub` visibility and added a todo to address that, once the e2e is stabilized and we can insert the infra code.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1057)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
