### PR TITLE
refactor: add account nonce as input of run_validate and remove validation output

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/822)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/822?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#822** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/822?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#521** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/521?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#519** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/519?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#520](https://github.com/starkware-libs/sequencer/pull/520) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/520?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#604](https://github.com/starkware-libs/sequencer/pull/604) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/604?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#672** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/672?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#666** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/666?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#694](https://github.com/starkware-libs/sequencer/pull/694) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/694?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#701](https://github.com/starkware-libs/sequencer/pull/701) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/701?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#661** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/661?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#660** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/660?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/822)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/gateway/src/gateway.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/822#-O6zKFJQDLNouN68c-cQ:-O6zKFJQDLNouN68c-cR:b-pw0ymw) ([raw file](https://github.com/starkware-libs/sequencer/blob/46125e4e57eb43dc5a697a8a1ed5fada24acdcca/crates/gateway/src/gateway.rs#L169)):*
> ```XML
>     let account_nonce = validator.get_nonce(sender_address).map_err(|e| {
>         error!("Failed to get nonce for sender address {}: {}", sender_address, e);
>         GatewaySpecError::UnexpectedError { data: "Internal server error.".to_owned() }
> ```

I don't think this should be an internal error.
When does getting the nonce fail?



_Code quote:_
```XML
        error!("Failed to get nonce for sender address {}: {}", sender_address, e);
        GatewaySpecError::UnexpectedError { data: "Internal server error.".to_owned() }
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/822)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/gateway/src/gateway.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/822#-O6zKFJQDLNouN68c-cQ:-O73JB0J5hltPyXkUJ0K:b-ol50j1) ([raw file](https://github.com/starkware-libs/sequencer/blob/46125e4e57eb43dc5a697a8a1ed5fada24acdcca/crates/gateway/src/gateway.rs#L169)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I don't think this should be an internal error.
When does getting the nonce fail?
</blockquote></details>

Getting the nonce from the storage fails if the contract address doesn't exist, but in this case, the state reader will return the default value and not an error.
Other failures derive from communication, serde, internal papyrus error, etc, so I think it makes sense to classify it as an internal error.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/gateway.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/822#-O6zKFJQDLNouN68c-cQ:-O7857cX0gcs59s9zbW0:b3y82yj) ([raw file](https://github.com/starkware-libs/sequencer/blob/46125e4e57eb43dc5a697a8a1ed5fada24acdcca/crates/gateway/src/gateway.rs#L169)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Getting the nonce from the storage fails if the contract address doesn't exist, but in this case, the state reader will return the default value and not an error.
Other failures derive from communication, serde, internal papyrus error, etc, so I think it makes sense to classify it as an internal error.
</blockquote></details>

If I understand @Yael-Starkware correctly, this should indeed be an internal error. No error should be handled differently, and indeed, some internal errors may arise.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/822#-:-O7NVqQc5GWPDOolchy_:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/822)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Sep 22, 3:05 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/822).

**Pull request merged**
