### PR TITLE
chore(sequencer_node): load config using absolute path

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #1692
- #1691
- #1690
- #1689 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by nadin-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1689)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/utils.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1689#-OASdGDlA0PkyzMFaveD:-OASdGDlA0PkyzMFaveE:b-ktgxxr) ([raw file](https://github.com/starkware-libs/sequencer/blob/68a3fa8625ee7f48860c6bac39ffbeb5ef3fe862/crates/mempool_node/src/utils.rs#L21)):*
> ```XML
> 
> /// Returns the absolute path from the project root.
> pub fn get_absolute_path(relative_path: &str) -> PathBuf {
> ```

This function appears multiple times in the code, I think we should add a TODO to consolidate them into a single location. Maybe the rust_utils crate Alon H suggested. 
___
*[`crates/mempool_node/src/config/node_config.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1689#-OASdDkM09Ey7f1hqvv7:-OASdDkNBXdJITHcbF7m:brk2o17) ([raw file](https://github.com/starkware-libs/sequencer/blob/08d998bf8a019ddc6b7070a201f0f8580f29e5af/crates/mempool_node/src/config/node_config.rs#L73)):*
> ```XML
>     fn dump(&self) -> BTreeMap<ParamPath, SerializedParam> {
>         #[allow(unused_mut)]
>         let mut sub_configs = vec![
> ```

Why did we need this initially, and why are we removing it now?



_Code quote:_
```XML
        #[allow(unused_mut)]
        let mut sub_configs = vec![
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1689)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/mempool_node/src/utils.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1689#-OASdGDlA0PkyzMFaveD:-OASfV5M6PM5QZVQ6Ew0:b4c9lyr) ([raw file](https://github.com/starkware-libs/sequencer/blob/68a3fa8625ee7f48860c6bac39ffbeb5ef3fe862/crates/mempool_node/src/utils.rs#L21)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

This function appears multiple times in the code, I think we should add a TODO to consolidate them into a single location. Maybe the rust_utils crate Alon H suggested.
</blockquote></details>

:thumbsup: 
___
*[`crates/mempool_node/src/config/node_config.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1689#-OASdDkM09Ey7f1hqvv7:-OASf-F24ZZLQXAsr90O:b41kmlt) ([raw file](https://github.com/starkware-libs/sequencer/blob/08d998bf8a019ddc6b7070a201f0f8580f29e5af/crates/mempool_node/src/config/node_config.rs#L73)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Why did we need this initially, and why are we removing it now?
</blockquote></details>

Error, the `mut` is redundant as `sub_configs` does not get mutated. Note how it was masked with the  `#[allow(unused_mut)]` annotation.

There are other configs that are mutated throughout their creation (bad practice anyway), and someone probably copy-pasted this here, removed the mutating part, and got a clippy warning on the unused mutation var, which then he solved with the annotation.

here = this config, or the one that this was copy-pasted from.

**Review by nadin-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1689#-:-OASh6bS-ROzqZbo1jHu:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1689)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#1690](https://github.com/starkware-libs/sequencer/pull/1690)

**Pull request closed without merging**
