### PR TITLE
refactor: define sierra to casm compiler trait

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/319)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/319?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#319** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/319?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#318** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/318?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#283** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/283?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#284](https://github.com/starkware-libs/sequencer/pull/284) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/284?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#250** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/250?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/319)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/starknet_sierra_compile/src/compile.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/319#-O3biNyU8wbHir748hbb:-O3biNyU8wbHir748hbc:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6bc1920a0db34b2137b01e878646f6494754a47f/crates/starknet_sierra_compile/src/compile.rs#L18)):*
> ```XML
> /// `cairo_lang_starknet_classes` crate.
> #[derive(Clone)]
> pub struct CairoLangCompiler {
> ```





_Suggestion:_
```XML
CairoLangSierraToCasmCompiler
```
___
*[`crates/starknet_sierra_compile/src/lib.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/319#-O3bgDMaCrLOyz871ZEZ:-O3bgDMaCrLOyz871ZE_:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6bc1920a0db34b2137b01e878646f6494754a47f/crates/starknet_sierra_compile/src/lib.rs#L16)):*
> ```XML
> 
> pub trait SierraToCasmCompiler: Send + Sync {
>     fn compile_sierra_to_casm(
> ```





_Suggestion:_
```XML
compile
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/319)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/starknet_sierra_compile/src/compile.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/319#-O3biNyU8wbHir748hbb:-O3fcRp783_K2jrorNCi:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6bc1920a0db34b2137b01e878646f6494754a47f/crates/starknet_sierra_compile/src/compile.rs#L18)):*
> ```XML
> /// `cairo_lang_starknet_classes` crate.
> #[derive(Clone)]
> pub struct CairoLangCompiler {
> ```

Done.
___
*[`crates/starknet_sierra_compile/src/lib.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/319#-O3bgDMaCrLOyz871ZEZ:-O3f_pbvE8ipjg1ebaP1:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6bc1920a0db34b2137b01e878646f6494754a47f/crates/starknet_sierra_compile/src/lib.rs#L16)):*
> ```XML
> 
> pub trait SierraToCasmCompiler: Send + Sync {
>     fn compile_sierra_to_casm(
> ```

Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/319#-:-O3fjV8x1acE71P5cng5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware and @yair-starkware)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/319#-:-O3gJaQuBZL503wd1eVA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware and @yair-starkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Aug 8, 5:47 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/319).

**Pull request merged**
