### PR TITLE
Merge main-v0.13.2 into main

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/555)

### CODE REVIEW

**Comment by Yoni-Starkware** [comment]
[Src](https://github.com/starkware-libs/blockifier/compare/ce118c172792c33fd92a9260b60ca4b2b56a741e..main-v0.13.2#diff-e224e55165fc769a086e419c55b27304200ee360b8a3b09e9c05c43b5e3970a0) [Dst](https://github.com/starkware-libs/blockifier/compare/ce118c172792c33fd92a9260b60ca4b2b56a741e..main#diff-e224e55165fc769a086e419c55b27304200ee360b8a3b09e9c05c43b5e3970a0) .github/workflows/papyrus_ci.yml
[Src](https://github.com/starkware-libs/blockifier/compare/ce118c172792c33fd92a9260b60ca4b2b56a741e..main-v0.13.2#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542) [Dst](https://github.com/starkware-libs/blockifier/compare/ce118c172792c33fd92a9260b60ca4b2b56a741e..main#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542) Cargo.toml

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 3 files at r3, 4 of 8 files at r6, 1 of 2 files at r7, 2 of 5 files at r8, 3 of 5 files at r9, 1 of 6 files at r10, 7 of 7 files at r11, 4 of 5 files at r12, 2 of 2 files at r13, 7 of 7 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/555)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/555)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @yair-starkware)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 1 of 3 files at r3, 4 of 8 files at r6, 1 of 2 files at r7, 2 of 5 files at r8, 3 of 5 files at r9, 1 of 6 files at r10, 7 of 7 files at r11, 4 of 5 files at r12, 2 of 2 files at r13, 5 of 7 files at r14, 1 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/555#-:-O4sxIel9EZFjWHrEtw2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
