### PR TITLE
test(blockifier): function to build calldata for recursive call_contract calls

### PR DESCRIPTION
**Pull request by TzahiTaub**

### CODE REVIEW

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1449)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1449)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub and @yoavGrs)

___
*[`crates/blockifier/src/test_utils.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1449#-O9FjZPYEZ8Yxxa0NZZh:-O9FjZPYEZ8Yxxa0NZZi:b-3b0fd3) ([raw file](https://github.com/starkware-libs/sequencer/blob/7160c7ab237345acce046b8908cfa487c2f4b9b9/crates/blockifier/src/test_utils.rs#L103)):*
> ```XML
>         Self::CairoVersion(version)
>     }
> }
> ```

I would delete this - it is not intuitive. conversion from CairoVersion to the new enum should be explicit.

The other way around *can* be implemented if you want



_Code quote:_
```XML
impl From<CairoVersion> for CompilerBasedVersion {
    fn from(version: CairoVersion) -> Self {
        Self::CairoVersion(version)
    }
}
```
___
*[`crates/blockifier/src/test_utils.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1449#-O9FjhHy1OoIiqtU2ecQ:-O9FjhHy1OoIiqtU2ecR:b-4yr6dt) ([raw file](https://github.com/starkware-libs/sequencer/blob/7160c7ab237345acce046b8908cfa487c2f4b9b9/crates/blockifier/src/test_utils.rs#L112)):*
> ```XML
>     }
> }
> // Storage keys.
> ```

newline



_Suggestion:_
```XML
}

// Storage keys.
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1449#-O9FkOY00irnbIf_EYY1:-O9FkOY00irnbIf_EYY2:bdspdsx) ([raw file](https://github.com/starkware-libs/sequencer/blob/7160c7ab237345acce046b8908cfa487c2f4b9b9/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L113)):*
> ```XML
> ) {
>     let outer_contract = FeatureContract::TestContract(outer_version);
>     let inner_contract = FeatureContract::TestContract(inner_version);
> ```

consider making `[inner|outer]_version` params of type `CompilerBasedVersion`.
will be easy to parametrize a third variant later



_Suggestion:_
```XML
    #[values(
        CompilerBasedVersion::CairoVersion(CairoVersion::Cairo0),
        CompilerBasedVersion::CairoVersion(CairoVersion::Cairo1)
    ]
    outer_version: CairoVersion,
    #[values(
        CompilerBasedVersion::CairoVersion(CairoVersion::Cairo0),
        CompilerBasedVersion::CairoVersion(CairoVersion::Cairo1)
    ]
    inner_version: CairoVersion,
) {
    let outer_contract = outer_version.get_test_contract();
    let inner_contract = inner_version.get_test_contract();
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1449)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/test_utils.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1449#-O9FjZPYEZ8Yxxa0NZZh:-O9GEUNABnLaNO6u5dBe:b-nxgolj) ([raw file](https://github.com/starkware-libs/sequencer/blob/7160c7ab237345acce046b8908cfa487c2f4b9b9/crates/blockifier/src/test_utils.rs#L103)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I would delete this - it is not intuitive. conversion from CairoVersion to the new enum should be explicit.

The other way around *can* be implemented if you want
</blockquote></details>

It's sort of backward compatability + convinience thing. The OldCairo1 should be explicit in tests, and anything that was Ciaro1 until now should run as a new Cairo1 contract (i.e., sierra gas mode). The other way around is not the thing I'm interested in.
I just hate writing `CompilerBasedVersion::CairoVersion(CairoVersion::Cairo1)`
___
*[`crates/blockifier/src/test_utils.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1449#-O9FjhHy1OoIiqtU2ecQ:-O9GEU-I5eilkuvHqG1f:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7160c7ab237345acce046b8908cfa487c2f4b9b9/crates/blockifier/src/test_utils.rs#L112)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

newline
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1449#-O9GLFMpEske9Y5wYyvx:-O9GLFMpEske9Y5wYyvy:b-7gchic) ([raw file](https://github.com/starkware-libs/sequencer/blob/d903234dae7b318b4bbc5fb3337df2e79fcb6fa9/crates/blockifier/src/test_utils.rs#L110)):*
> ```XML
> 
>     /// Returns the tracked resource for a contract execution with the current version, assuming no
>     /// calls were made to other contracts prior to this execution.
> ```

Help with rewriting this will be appreciated.



_Code quote:_
```XML
    /// Returns the tracked resource for a contract execution with the current version, assuming no
    /// calls were made to other contracts prior to this execution.
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1449#-O9FkOY00irnbIf_EYY1:-O9GJkWI3NO6w2rGNDPs:b6fmnhu) ([raw file](https://github.com/starkware-libs/sequencer/blob/7160c7ab237345acce046b8908cfa487c2f4b9b9/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L113)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

consider making `[inner|outer]_version` params of type `CompilerBasedVersion`.
will be easy to parametrize a third variant later
</blockquote></details>

Changed the test a little and added the other cases. How does it look?

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1449)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub and @yoavGrs)

___
*[`crates/blockifier/src/test_utils.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1449#-O9GLFMpEske9Y5wYyvx:-O9OuC7lAPpGS5n7RIwZ:byaehvd) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4a60aca217481522be4975b4a5b7e8ff219d861/crates/blockifier/src/test_utils.rs#L110)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Help with rewriting this will be appreciated.
</blockquote></details>

hmmm... maybe
```
/// Returns the context-free tracked resource of this contract (does not take caller contract into account).
```
?

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1449)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/blockifier/src/test_utils.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1449#-O9GLFMpEske9Y5wYyvx:-OADAcZB6v8zAR3WHIrS:b-5oj3x8) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4a60aca217481522be4975b4a5b7e8ff219d861/crates/blockifier/src/test_utils.rs#L110)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

hmmm... maybe
```
/// Returns the context-free tracked resource of this contract (does not take caller contract into account).
```
?
</blockquote></details>

Bravo!

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1449#-:-OADGK3i8O4CtJq26Leq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
