### PR TITLE
feat(protobuf): create rpctransaction proto file and converters

### PR DESCRIPTION
**Pull request by eitanm-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/631)

### CODE REVIEW

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/631)* status: 1 of 14 files reviewed, 10 unresolved discussions (waiting on @MohammadNassar1 and @ShahakShama)

___
*[`crates/papyrus_protobuf/build.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/631#-O5g88EN8xxkj5oYYGFu:-O61AEma1n5lNnRz_CfA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f65a3b492f1f18319103f16d147a9a51021c3aad/crates/papyrus_protobuf/build.rs#L30)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Forgot to tell you that, but we decided to keep the name rpc because it's used only in the mempool. In consensus we'll use a different type that has a l1 handler variant

rename broadcasted to rpc throughout the PR
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/mempool.rs` line 2 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/631#-O5g83G0Eee3wcUEqgmy:-O61yViL3poE9HLd3qr5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f65a3b492f1f18319103f16d147a9a51021c3aad/crates/papyrus_protobuf/src/mempool.rs#L2)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This should be T and not Option<T>
Also, I see no reason this should be generic and not have the specific type you need
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/transaction_test.rs` line 203 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/631#-O5gFMT7Bun-RJJVcDaN:-O61yZ0ADvkHzgvvh1p6:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f65a3b492f1f18319103f16d147a9a51021c3aad/crates/papyrus_protobuf/src/converters/transaction_test.rs#L203)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/broadcasted_transaction.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/631#-O5gFVb682pcy6jqQDbI:-O61yaWiC72NEzgapW-M:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f65a3b492f1f18319103f16d147a9a51021c3aad/crates/papyrus_protobuf/src/converters/broadcasted_transaction.rs#L94)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Reduce code duplication (see my comment in proto)
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/broadcasted_transaction.proto` line 8 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/631#-O5gDIcz-224VAzzbV0f:-O61yfpQ1ayKSkD0RcLr:b-idlein) ([raw file](https://github.com/starkware-libs/sequencer/blob/f65a3b492f1f18319103f16d147a9a51021c3aad/crates/papyrus_protobuf/src/proto/p2p/proto/broadcasted_transaction.proto#L8)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Create a DeclareV3Common message in transaction.proto without contract_class and change DeclareV3 to contain common and class_hash and this to contain common and contract_class
@MohammadNassar1 DYT we should do this in starknet_api as well?
</blockquote></details>

we discussed a different solution. done
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/broadcasted_transaction.proto` line 22 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/631#-O5gCmU_EyKCHZKGe4sR:-O61yerl68Gy2I5bfljl:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f65a3b492f1f18319103f16d147a9a51021c3aad/crates/papyrus_protobuf/src/proto/p2p/proto/broadcasted_transaction.proto#L22)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Use the DeployAccountV3 and InvokeV3 from transaction.proto
@MohammadNassar1 Why in starknet_api don't you use the transactions from the regular transaction if possible?
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/broadcasted_transaction.proto` line 53 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/631#-O5gChpNEQTq4BcCQOr9:-O5gR5iu4SgZpKAPtrg9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f65a3b492f1f18319103f16d147a9a51021c3aad/crates/papyrus_protobuf/src/proto/p2p/proto/broadcasted_transaction.proto#L53)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

newline at end of file
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/transaction.proto` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/631#-O5gF5NC010k8e0qsUll:-O61ykDa4R0sP1t3dKc2:b-97e2w2) ([raw file](https://github.com/starkware-libs/sequencer/blob/f65a3b492f1f18319103f16d147a9a51021c3aad/crates/papyrus_protobuf/src/proto/p2p/proto/transaction.proto#L13)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I'm not sure what we should do here. Let's check together with Dori's team
</blockquote></details>

Done. Nimrod did it
___
*[`crates/papyrus_protobuf/src/converters/broadcasted_transaction_test.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/631#-O5gEdMS2WS6LYSQ9KmZ:-O618ikP9y2mLdRjpdMP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f65a3b492f1f18319103f16d147a9a51021c3aad/crates/papyrus_protobuf/src/converters/broadcasted_transaction_test.rs#L48)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is not a test, so the word validate/assert should appear as it is not implied (unlike tests where it is implied)
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/broadcasted_transaction_test.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/631#-O5gEm4w60s2BnrlZPxm:-O61yXiK3TOA8gDUT5wX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f65a3b492f1f18319103f16d147a9a51021c3aad/crates/papyrus_protobuf/src/converters/broadcasted_transaction_test.rs#L58)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Have a different value per type of resource
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 11 of 13 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/631)* status: all files reviewed, 2 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_protobuf/src/mempool.rs` line 2 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/631#-O5g83G0Eee3wcUEqgmy:-O6FNnF74e1ZXZQv23Xk:b-7ikwg0) ([raw file](https://github.com/starkware-libs/sequencer/blob/f65a3b492f1f18319103f16d147a9a51021c3aad/crates/papyrus_protobuf/src/mempool.rs#L2)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

As I said, remove the T and rename
```
pub struct RpcTransactionWrapper(pub RpcTransaction)
```
___
*[`crates/papyrus_protobuf/src/converters/rpc_transaction.rs` line 93 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/631#-O6FOn3n12XjA1fqSbz0:-O6FOn3n12XjA1fqSbz1:b-46ss4u) ([raw file](https://github.com/starkware-libs/sequencer/blob/613edce4dbc2c445d78141389062191add93ff67/crates/papyrus_protobuf/src/converters/rpc_transaction.rs#L93)):*
> ```XML
>         let declare_v3 = value.declare_v3.ok_or(ProtobufConversionError::MissingField {
>             field_description: "DeclareV3::declare_v3",
>         })?;
> ```

Convert this into Declare from SN_API's regular transaction and then get all the fields from that. Same for other txs and for other side of conversion

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/631)* status: 10 of 14 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_protobuf/src/mempool.rs` line 2 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/631#-O5g83G0Eee3wcUEqgmy:-O6FU1RUDy2spQGGagJV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f65a3b492f1f18319103f16d147a9a51021c3aad/crates/papyrus_protobuf/src/mempool.rs#L2)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

As I said, remove the T and rename
```
pub struct RpcTransactionWrapper(pub RpcTransaction)
```
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/rpc_transaction.rs` line 93 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/631#-O6FOn3n12XjA1fqSbz0:-O6Ffff46-CpCO6VDomw:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/613edce4dbc2c445d78141389062191add93ff67/crates/papyrus_protobuf/src/converters/rpc_transaction.rs#L93)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Convert this into Declare from SN_API's regular transaction and then get all the fields from that. Same for other txs and for other side of conversion
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/631)* status: all files reviewed, 2 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_protobuf/src/mempool.rs` line 2 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/631#-O5g83G0Eee3wcUEqgmy:-O6FkXCvDX2rlHh2GFWu:b-s1a1t6) ([raw file](https://github.com/starkware-libs/sequencer/blob/f65a3b492f1f18319103f16d147a9a51021c3aad/crates/papyrus_protobuf/src/mempool.rs#L2)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

import from sn_api instead of generic
___
*[`crates/papyrus_protobuf/src/converters/rpc_transaction.rs` line 158 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/631#-O6Fl53o3UJ88EtSypTR:-O6Fl53o3UJ88EtSypTS:b68dnlj) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba92f296c60f45a06bd2ced648a5bb5feaa58e52/crates/papyrus_protobuf/src/converters/rpc_transaction.rs#L158)):*
> ```XML
>             signature,
>             nonce,
>             class_hash: Default::default(),
> ```

Add TODO to refactor the protobuf to avoid this

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/631)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_protobuf/src/converters/rpc_transaction.rs` line 158 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/631#-O6Fl53o3UJ88EtSypTR:-O6L13EvCdbQRjGHCmQi:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba92f296c60f45a06bd2ced648a5bb5feaa58e52/crates/papyrus_protobuf/src/converters/rpc_transaction.rs#L158)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to refactor the protobuf to avoid this
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/631#-:-O6_8aNw6iuZvfpqMf0b:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Pull request merged**
