### PR TITLE
refactor(blockifier): make VersionedConstantsOverrides fields optional

### PR DESCRIPTION
**Pull request by ayeletstarkware**
I plan to make PyVersionedConstantsOverrides fields optional as well.

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1496)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 319 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1496#-O9nBpjXAKCxZzXJLNfX:-O9nBpjXAKCxZzXJLNfY:bb70w76) ([raw file](https://github.com/starkware-libs/sequencer/blob/81d574487a65061e86496326d595dd7f9f5d144f/crates/blockifier/src/versioned_constants.rs#L319)):*
> ```XML
> 
>         constants
>     }
> ```

Nice



_Code quote:_
```XML
    /// Returns the latest versioned constants after applying the given overrides.
    pub fn get_versioned_constants(
        versioned_constants_overrides: VersionedConstantsOverrides,
    ) -> Self {
        let mut constants = Self::latest_constants().clone();

        if let Some(validate_max_n_steps) = versioned_constants_overrides.validate_max_n_steps {
            constants.validate_max_n_steps = validate_max_n_steps;
        }
        if let Some(max_recursion_depth) = versioned_constants_overrides.max_recursion_depth {
            constants.max_recursion_depth = max_recursion_depth;
        }
        if let Some(invoke_tx_max_n_steps) = versioned_constants_overrides.invoke_tx_max_n_steps {
            constants.invoke_tx_max_n_steps = invoke_tx_max_n_steps;
        }

        constants
    }
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 838 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1496#-O9nAy9S5v0-h8ivg4Sx:-O9nAy9S5v0-h8ivg4Sy:bc8qxdi) ([raw file](https://github.com/starkware-libs/sequencer/blob/81d574487a65061e86496326d595dd7f9f5d144f/crates/blockifier/src/versioned_constants.rs#L838)):*
> ```XML
>         }
>     }
> }
> ```

This is the whole idea (or is it blocking this PR?)

We can simply derive it. "This is because the default value for `Option<T>` is `None`, regardless of the type `T`."



_Suggestion:_
```XML
impl Default for VersionedConstantsOverrides {
    // TODO: update the default values once the actual values are known.
    fn default() -> Self {
        Self {
            validate_max_n_steps: None,
            max_recursion_depth: None,
            invoke_tx_max_n_steps: None,
        }
    }
}
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/versioned_constants_test.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1496#-O9nD5XUA2l2gW2AicHR:-O9nD5XUA2l2gW2AicHS:b-7re0a6) ([raw file](https://github.com/starkware-libs/sequencer/blob/81d574487a65061e86496326d595dd7f9f5d144f/crates/blockifier/src/versioned_constants_test.rs#L58)):*
> ```XML
>     assert_eq!(result.validate_max_n_steps, updated_validate_max_n_steps);
>     assert_eq!(result.max_recursion_depth, updated_max_recursion_depth);
> }
> ```

Add one more test for the `None` case. i.e. test the scenario the removed `latest_constants_with_overrides` solved.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1496)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1496#-O9nCySH4NKSsqS7RvxB:-O9nCySH4NKSsqS7RvxC:bo5cpi2) ([raw file](https://github.com/starkware-libs/sequencer/blob/81d574487a65061e86496326d595dd7f9f5d144f/crates/gateway/src/stateful_transaction_validator.rs#L104)):*
> ```XML
>         };
>         let versioned_constants =
>             VersionedConstants::get_versioned_constants(versioned_constants_overrides);
> ```

Nice 2.



_Code quote:_
```XML
        let versioned_constants_overrides = VersionedConstantsOverrides {
            validate_max_n_steps: Some(self.config.validate_max_n_steps),
            max_recursion_depth: Some(self.config.max_recursion_depth),
            invoke_tx_max_n_steps: None,
        };
        let versioned_constants =
            VersionedConstants::get_versioned_constants(versioned_constants_overrides);
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1496)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 838 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1496#-O9nAy9S5v0-h8ivg4Sx:-O9xaNUXBcvDVA-IB61a:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/81d574487a65061e86496326d595dd7f9f5d144f/crates/blockifier/src/versioned_constants.rs#L838)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This is the whole idea (or is it blocking this PR?)

We can simply derive it. "This is because the default value for `Option<T>` is `None`, regardless of the type `T`."
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1496#-O9nD5XUA2l2gW2AicHR:-O9xdju74NjtFFKDtgBb:b-nb88fx) ([raw file](https://github.com/starkware-libs/sequencer/blob/81d574487a65061e86496326d595dd7f9f5d144f/crates/blockifier/src/versioned_constants_test.rs#L58)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Add one more test for the `None` case. i.e. test the scenario the removed `latest_constants_with_overrides` solved.
</blockquote></details>

How's this change? checks both overrides and not overrides in one test.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1496)* status: 3 of 4 files reviewed, all discussions resolved

___
*[`crates/blockifier/src/versioned_constants.rs` line 319 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1496#-O9nL6nSAF-VwoCncuKi:-O9nL6nSAF-VwoCncuKj:bj5x9yo) ([raw file](https://github.com/starkware-libs/sequencer/blob/81d574487a65061e86496326d595dd7f9f5d144f/crates/blockifier/src/versioned_constants.rs#L319)):*
> ```XML
> 
>         constants
>     }
> ```

Non-blocking. We can do the following. write a macro that gets the field name and does the override if need be.



_Code quote:_
```XML
    /// Returns the latest versioned constants after applying the given overrides.
    pub fn get_versioned_constants(
        versioned_constants_overrides: VersionedConstantsOverrides,
    ) -> Self {
        let mut constants = Self::latest_constants().clone();

        if let Some(validate_max_n_steps) = versioned_constants_overrides.validate_max_n_steps {
            constants.validate_max_n_steps = validate_max_n_steps;
        }
        if let Some(max_recursion_depth) = versioned_constants_overrides.max_recursion_depth {
            constants.max_recursion_depth = max_recursion_depth;
        }
        if let Some(invoke_tx_max_n_steps) = versioned_constants_overrides.invoke_tx_max_n_steps {
            constants.invoke_tx_max_n_steps = invoke_tx_max_n_steps;
        }

        constants
    }
```
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1496#-O9nD5XUA2l2gW2AicHR:-OA1gOGX4udQWlGLPvtV:b6oq40q) ([raw file](https://github.com/starkware-libs/sequencer/blob/81d574487a65061e86496326d595dd7f9f5d144f/crates/blockifier/src/versioned_constants_test.rs#L58)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

How's this change? checks both overrides and not overrides in one test.
</blockquote></details>

Love it.

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 319 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1496#-O9nL6nSAF-VwoCncuKi:-OAC-Ku11Sc1BojbgYi2:bxrdjml) ([raw file](https://github.com/starkware-libs/sequencer/blob/81d574487a65061e86496326d595dd7f9f5d144f/crates/blockifier/src/versioned_constants.rs#L319)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Non-blocking. We can do the following. write a macro that gets the field name and does the override if need be.
</blockquote></details>

But no need.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1496#-:-OAC0pir2lp3924GVxya:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 837 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1496#-OADNSDXE9TNtNxRePKk:-OADNSDXE9TNtNxRePKl:bp1k9w) ([raw file](https://github.com/starkware-libs/sequencer/blob/fac00094a4135fa9622df43b484f0478f4f102dd/crates/blockifier/src/versioned_constants.rs#L837)):*
> ```XML
>                 "Maximum number of steps the validation function is allowed to run.",
>                 ParamPrivacyInput::Public,
>             ),
> ```

I think this will solve *all* of our issues.

The corresponding `#is_none` flag will be turned on because of this is what the default of `VersionedConstantsOverrides` does!



_Suggestion:_
```XML
            ser_optional_param(
                "validate_max_n_steps",
                &self.validate_max_n_steps,
                "Maximum number of steps the validation function is allowed to run.",
                ParamPrivacyInput::Public,
            ),
```

**Pull request merged**
