### PR TITLE
refactor(starknet_batcher): move around some types and utils to a common utils file

### PR DESCRIPTION
**Pull request by dafnamatsry**

### CODE REVIEW

**Comment by dafnamatsry** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2622?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2618** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2618?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2622** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2622?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2622?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2441** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2441?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2483** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2483?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2480** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2480?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2622)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/utils.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2622#-ODkPG5CBHBz2oBELkAb:-ODkPG5CBHBz2oBELkAc:br94jzf) ([raw file](https://github.com/starkware-libs/sequencer/blob/3bc9a7f95ccd1f0692e15cb7b5d661cdd6139ab8/crates/starknet_batcher/src/utils.rs#L24)):*
> ```XML
> pub(crate) enum ProposalError {
>     #[error(transparent)]
>     BlockBuilderError(Arc<BlockBuilderError>),
> ```

BlockBuilderError has an Aborted variant. Can we use it and remove the ProposalError completely?

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2622)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/utils.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2622#-ODkPG5CBHBz2oBELkAb:-ODuCIbj7HalEKopf6hp:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3bc9a7f95ccd1f0692e15cb7b5d661cdd6139ab8/crates/starknet_batcher/src/utils.rs#L24)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

BlockBuilderError has an Aborted variant. Can we use it and remove the ProposalError completely?
</blockquote></details>

Done.

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2622)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 341 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2622#-OE97XhV-Qv2-GLegF96:-OE9D_5jAJiG3KMAMFJm:b-vbdy3o) ([raw file](https://github.com/starkware-libs/sequencer/blob/dfa16faea997e63de3b20b60a6e30b5d0c95f458/crates/starknet_batcher/src/batcher.rs#L341)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why is this an internal error? The proposal ID comes from the input 
Same below
</blockquote></details>

Note that we `expect` the proposal to exist. The `InternalError` is returned in case the proposal finished with an error.

By the way, I didn't change any logic here, the same thing happened before but was hidden behind the `?`, and the `From` implementation:

```
impl From<ProposalError> for BatcherError {
    fn from(err: ProposalError) -> Self {
        match err {
            ProposalError::BlockBuilderError(..) => BatcherError::InternalError,
            ProposalError::Aborted => BatcherError::ProposalAborted,
        }
    }
}
```
___
*[`crates/starknet_batcher/src/utils.rs` line 114 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2622#-OE98fPs1ILWzP_WgpZm:-OE9F-666cE_mbm_V53f:b-3vpca1) ([raw file](https://github.com/starkware-libs/sequencer/blob/dfa16faea997e63de3b20b60a6e30b5d0c95f458/crates/starknet_batcher/src/utils.rs#L114)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

When can this be returned? Does it make sense to return this error in all those cases?
</blockquote></details>

It can only happen if the consensus sends a `get_proposal_content` request about an aborted proposal (which shouldn't really happen).

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2622)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 341 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2622#-OE97XhV-Qv2-GLegF96:-OE9NHh1CyeXk0tWLERX:b-f01egr) ([raw file](https://github.com/starkware-libs/sequencer/blob/dfa16faea997e63de3b20b60a6e30b5d0c95f458/crates/starknet_batcher/src/batcher.rs#L341)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Note that we `expect` the proposal to exist. The `InternalError` is returned in case the proposal finished with an error.

By the way, I didn't change any logic here, the same thing happened before but was hidden behind the `?`, and the `From` implementation:

```
impl From<ProposalError> for BatcherError {
    fn from(err: ProposalError) -> Self {
        match err {
            ProposalError::BlockBuilderError(..) => BatcherError::InternalError,
            ProposalError::Aborted => BatcherError::ProposalAborted,
        }
    }
}
```
</blockquote></details>

Right. `expect`ing it is even worse, no? A wrong input can make the batcher panic. Do we want an error there?
___
*[`crates/starknet_batcher/src/utils.rs` line 114 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2622#-OE98fPs1ILWzP_WgpZm:-OE9NXCHAwl8Pzwn9RCC:b-6mhywn) ([raw file](https://github.com/starkware-libs/sequencer/blob/dfa16faea997e63de3b20b60a6e30b5d0c95f458/crates/starknet_batcher/src/utils.rs#L114)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

It can only happen if the consensus sends a `get_proposal_content` request about an aborted proposal (which shouldn't really happen).
</blockquote></details>

Great, thanks.

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2622)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 341 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2622#-OE97XhV-Qv2-GLegF96:-OE9OFFPCKZFLZJqMguc:b-oc71j2) ([raw file](https://github.com/starkware-libs/sequencer/blob/dfa16faea997e63de3b20b60a6e30b5d0c95f458/crates/starknet_batcher/src/batcher.rs#L341)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Right. `expect`ing it is even worse, no? A wrong input can make the batcher panic. Do we want an error there?
</blockquote></details>

I think the `expect` here assumes we already check the proposal exists above:
```
let tx_stream = &mut self
            .propose_tx_streams
            .get_mut(&proposal_id)
            .ok_or(BatcherError::ProposalNotFound { proposal_id })?;
```

I can change it to return an error instead, but it shouldn't happen.

**Pull request merged**
