### PR TITLE
Merge main-v0.13.2 into main

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/418)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
[Src](https://github.com/starkware-libs/blockifier/compare/8134c27b74e9e30e2a2236390405f68eb0ff4db3..main-v0.13.2#diff-ec529d83c32614a153f3c93db2985e08a4f736bd8261cf41bb521c9fdbf69dbd) [Dst](https://github.com/starkware-libs/blockifier/compare/8134c27b74e9e30e2a2236390405f68eb0ff4db3..main#diff-ec529d83c32614a153f3c93db2985e08a4f736bd8261cf41bb521c9fdbf69dbd) .github/workflows/blockifier_compiled_cairo.yml
[Src](https://github.com/starkware-libs/blockifier/compare/8134c27b74e9e30e2a2236390405f68eb0ff4db3..main-v0.13.2#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87e) [Dst](https://github.com/starkware-libs/blockifier/compare/8134c27b74e9e30e2a2236390405f68eb0ff4db3..main#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87e) Cargo.lock
[Src](https://github.com/starkware-libs/blockifier/compare/8134c27b74e9e30e2a2236390405f68eb0ff4db3..main-v0.13.2#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542) [Dst](https://github.com/starkware-libs/blockifier/compare/8134c27b74e9e30e2a2236390405f68eb0ff4db3..main#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542) Cargo.toml

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 11 files at r6, 2 of 4 files at r8, 71 of 74 files at r9, 7 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/418)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/418)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @TzahiTaub)

___
*[`Cargo.lock` line 6287 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/418#-O49rQV67wfH6GWc0SNr:-O4A8gFi7pGionxDhhRY:b-ko4ooh) ([raw file](https://github.com/starkware-libs/sequencer/blob/d28051ce93b5ffd4422c93d8e0cbe78f0005304d/Cargo.lock#L6287)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

You don't want to specifiy the version?
</blockquote></details>

this version was only specified because the committer used a *different* version; we aligned the `clap` version all across the workspace so no more explicit version required.
___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 19 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/418#-O4A-wKe12EvLwu5uIa1:-O4A8p3h-zHYUkU6UXtU:bg5jc9y) ([raw file](https://github.com/starkware-libs/sequencer/blob/d28051ce93b5ffd4422c93d8e0cbe78f0005304d/.github/workflows/blockifier_compiled_cairo.yml#L19)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Can you explain this? were your cairo1-compilation PRs over `main`?
</blockquote></details>

yes. they weren't needed on main-v0.13.2
___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 35 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/418#-O4A0RUA3_vz6tmYErpe:-O4A8sgi2uBBHPyJH285:b-7ropln) ([raw file](https://github.com/starkware-libs/sequencer/blob/d28051ce93b5ffd4422c93d8e0cbe78f0005304d/.github/workflows/blockifier_compiled_cairo.yml#L35)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 95 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/418#-O4A1XIh-nUOhvGppzAQ:-O4A8wXG7W-N_sP8HRtZ:b-wkox2f) ([raw file](https://github.com/starkware-libs/sequencer/blob/d28051ce93b5ffd4422c93d8e0cbe78f0005304d/.github/workflows/blockifier_compiled_cairo.yml#L95)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

the correct command is:
```
cargo test -p blockifier --test feature_contracts_compatibility_test --features testing -- --include-ignored
```
was fixed on both main and main-v0.13.2

**Review by amosStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/418#-:-O4AEGfr6yBffcuI_B5I:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

**Review by amosStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/418)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
