### PR TITLE
chore(blockifier_reexecution): upload and download reexecution files

### PR DESCRIPTION
**Pull request by aner-starkware**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2229)* status: all files reviewed, 9 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/Cargo.toml` line 18 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEUQiW0bVow10Pmyqb:-OCEUQiW0bVow10Pmyqc:b70g6nl) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/Cargo.toml#L18)):*
> ```TOML
> clap = { workspace = true, features = ["cargo", "derive"] }
> flate2.workspace = true
> google-cloud-storage = "0.22.1"
> ```

pending approval



_Code quote:_
```TOML
google-cloud-storage = "0.22.1"
```
___
*[`crates/blockifier_reexecution/src/main.rs` line 245 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEUcxd8ew28uvCCGTM:-OCEUcxd8ew28uvCCGTN:bhii64w) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L245)):*
> ```XML
>         Command::UploadFiles { block_numbers, directory_path } => {
>             let directory_path =
>                 directory_path.unwrap_or("./crates/blockifier_reexecution/resources".to_string());
> ```

this string appears several times in this module; please make a named constant



_Code quote:_
```XML
"./crates/blockifier_reexecution/resources"
```
___
*[`crates/blockifier_reexecution/src/main.rs` line 251 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEUkzjA__gnpFOBgkK:-OCEUkzjA__gnpFOBgkL:b-e11l1y) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L251)):*
> ```XML
> 
>             let files_prefix: String =
>                 fs::read_to_string(directory_path.clone() + "/offline_reexecution_files_prefix")
> ```

used twice; make it a constant?



_Code quote:_
```XML
 "/offline_reexecution_files_prefix"
```
___
*[`crates/blockifier_reexecution/src/main.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEUrf45imJdHApGpta:-OCEUrf45imJdHApGptb:b-8tc78g) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L258)):*
> ```XML
> 
>             // Get the client with authentication.
>             let config = ClientConfig::default().with_auth().await.unwrap();
> ```

this will fail if devs didn't log into google cloud?
when would this fail?
we may want a more informative error in an `expect()`



_Code quote:_
```XML
let config = ClientConfig::default().with_auth().await.unwrap();
```
___
*[`crates/blockifier_reexecution/src/main.rs` line 271 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEV8Ok18SPj5a_ToSZ:-OCEV8Ok18SPj5a_ToS_:bhmzqck) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L271)):*
> ```XML
>                 assert!(
>                     client
>                         .get_object(&GetObjectRequest {
> ```

is there a different request type that just queries if the file exists? shame to download the entire thing before returning an error.
or, is this what `get_object` (as opposed to `download_object`) does?



_Code quote:_
```XML
GetObjectRequest
```
___
*[`crates/blockifier_reexecution/src/main.rs` line 289 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEVbxf4ilGBXR44two:-OCEVbxf4ilGBXR44twp:bhte31r) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L289)):*
> ```XML
>                     .upload_object(
>                         &UploadObjectRequest {
>                             bucket: "reexecution_artifacts".to_string(),
> ```

this bucket name should be a constant



_Code quote:_
```XML
"reexecution_artifacts"
```
___
*[`crates/blockifier_reexecution/src/main.rs` line 305 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEW4DH3N_2la-cTBuU:-OCEW4DH3N_2la-cTBuV:b-m2xjt5) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L305)):*
> ```XML
>             }
> 
>             println!("All blocks uploaded successfully.");
> ```

can you add a link to the new directory / new objects on GCS here?



_Code quote:_
```XML
println!("All blocks uploaded successfully.");
```
___
*[`crates/blockifier_reexecution/src/main.rs` line 334 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEVRlj03qUwOQBD_sS:-OCEVRlj03qUwOQBD_sT:bx05qy1) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L334)):*
> ```XML
>                             bucket: "reexecution_artifacts".to_string(),
>                             object: files_prefix.clone()
>                                 + &format!("block_{block_number}/reexecution_data.json"),
> ```

this string is duplicated many times, sometimes with a different prefix, but still; please put it in a variable / lambda function for single point of truth



_Code quote:_
```XML
"block_{block_number}/reexecution_data.json"
```
___
*[`crates/blockifier_reexecution/src/main.rs` line 349 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEW0az8WuG0nbgreYY:-OCEW0az8WuG0nbgreYZ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L349)):*
> ```XML
>             }
> 
>             println!("All blocks downloaded successfully.");
> ```





_Suggestion:_
```XML
 println!("All blocks downloaded successfully to {directory_path}.");
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2229)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 245 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEUcxd8ew28uvCCGTM:-OCK0cZ_EI4Jm7B0VHf8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L245)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this string appears several times in this module; please make a named constant
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/main.rs` line 251 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEUkzjA__gnpFOBgkK:-OCK0_rt1G4SENYbWi6M:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L251)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

used twice; make it a constant?
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/main.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEUrf45imJdHApGpta:-OCK12QD6OLOczLeo0z7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L258)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this will fail if devs didn't log into google cloud?
when would this fail?
we may want a more informative error in an `expect()`
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/main.rs` line 271 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEV8Ok18SPj5a_ToSZ:-OCEXB0K3TZYru-l3Yty:b-7uv7bk) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L271)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is there a different request type that just queries if the file exists? shame to download the entire thing before returning an error.
or, is this what `get_object` (as opposed to `download_object`) does?
</blockquote></details>

I think `get_object` (as opposed to `download_object`) is that request.
___
*[`crates/blockifier_reexecution/src/main.rs` line 289 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEVbxf4ilGBXR44two:-OCK0Nv268WAvLLtrTV9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L289)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this bucket name should be a constant
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/main.rs` line 305 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEW4DH3N_2la-cTBuU:-OCEXSIA7K0iOTPR4nXi:b-7zi8tj) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L305)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you add a link to the new directory / new objects on GCS here?
</blockquote></details>

WDYM?
___
*[`crates/blockifier_reexecution/src/main.rs` line 334 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEVRlj03qUwOQBD_sS:-OCK0RZw89I_rtbqmqiN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L334)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this string is duplicated many times, sometimes with a different prefix, but still; please put it in a variable / lambda function for single point of truth
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/main.rs` line 349 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEW0az8WuG0nbgreYY:-OCK0WvTBkVLfoeMPMok:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L349)):*
> ```XML
>             }
> 
>             println!("All blocks downloaded successfully.");
> ```

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2229)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 305 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEW4DH3N_2la-cTBuU:-OCSs5KRE5vx5FZblZol:b-mxmx83) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L305)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

this command uploads artifacts to a remote bucket.
it will help if you output a URL linking to the new file(s), i.e. something that starts with `https://console.cloud.google.com/storage/browser/...`
___
*[`crates/blockifier_reexecution/src/main.rs` line 25 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCSqoP2Ej6BSU4KXxNp:-OCSqoP2Ej6BSU4KXxNq:bng4129) ([raw file](https://github.com/starkware-libs/sequencer/blob/0c600567f69f2c17dd03b9e50f5ff9422c31dbe3/crates/blockifier_reexecution/src/main.rs#L25)):*
> ```XML
> 
> const BUCKET: &str = "reexecution_artifacts";
> const RESOURCES_DIR: &str = "/resources";
> ```

this is only used in `prefix_dir`, you can inline it. non-blocking



_Code quote:_
```XML
const RESOURCES_DIR: &str = "/resources";
```
___
*[`crates/blockifier_reexecution/src/main.rs` line 170 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCSrJ5l8YkTcUuJvFCW:-OCSrJ5mAghBLAeIZM_B:bl77i3c) ([raw file](https://github.com/starkware-libs/sequencer/blob/0c600567f69f2c17dd03b9e50f5ff9422c31dbe3/crates/blockifier_reexecution/src/main.rs#L170)):*
> ```XML
>     let fn_block_full_file_path = |directory_path, block_number| {
>         fn_block_full_directory(directory_path, block_number) + FILE_NAME
>     };
> ```

please be consistent (`prefix_dir` doesn't start with `fn_`)
you can also rename to `fn_prefix_dir` if you prefer



_Suggestion:_
```XML
    let block_dir = |block_number| format!("/block_{block_number}");
    let block_data_file = |block_number| fn_block_dir(block_number) + FILE_NAME;
    let block_full_directory =
        |directory_path: String, block_number| directory_path + &fn_block_dir(block_number);
    let block_full_file_path = |directory_path, block_number| {
        fn_block_full_directory(directory_path, block_number) + FILE_NAME
    };
```
___
*[`crates/blockifier_reexecution/src/main.rs` line 280 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCSqJYI8k-rEUdzDqaZ:-OCSqJYI8k-rEUdzDqa_:b-gcuw1p) ([raw file](https://github.com/starkware-libs/sequencer/blob/0c600567f69f2c17dd03b9e50f5ff9422c31dbe3/crates/blockifier_reexecution/src/main.rs#L280)):*
> ```XML
>                     Path::exists(Path::new(&format!(
>                         "{directory_path}/block_{block_number}/reexecution_data.json"
>                     ))),
> ```

use your function please



_Code quote:_
```XML
                    Path::exists(Path::new(&format!(
                        "{directory_path}/block_{block_number}/reexecution_data.json"
                    ))),
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2229)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 305 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEW4DH3N_2la-cTBuU:-OCT6DmM33PAjaBOJCdo:bncrqr8) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L305)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this command uploads artifacts to a remote bucket.
it will help if you output a URL linking to the new file(s), i.e. something that starts with `https://console.cloud.google.com/storage/browser/...`
</blockquote></details>

There could be a lot of links, and each link is quite long... are you sure we want this?

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/main.rs` line 170 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCSrJ5l8YkTcUuJvFCW:-OCT7SrZ5le-hOe-sdfy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0c600567f69f2c17dd03b9e50f5ff9422c31dbe3/crates/blockifier_reexecution/src/main.rs#L170)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please be consistent (`prefix_dir` doesn't start with `fn_`)
you can also rename to `fn_prefix_dir` if you prefer
</blockquote></details>

Done.

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/main.rs` line 280 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCSqJYI8k-rEUdzDqaZ:-OCT7rSD6huX39SY16Iq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0c600567f69f2c17dd03b9e50f5ff9422c31dbe3/crates/blockifier_reexecution/src/main.rs#L280)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use your function please
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2229)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 305 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEW4DH3N_2la-cTBuU:-OCT9uVF67U8W2Sfi0zt:b-t1c9h1) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L305)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

There could be a lot of links, and each link is quite long... are you sure we want this?
</blockquote></details>

why a lot of links? if there are many artifacts, you can link to the directory...
IMO it's ok if the link is long, as long as there is only one link

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/main.rs` line 305 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCEW4DH3N_2la-cTBuU:-OCV5C7cANwks71zlHUT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d3fbd42e16eac2945391f395778a24ea5cdb17c/crates/blockifier_reexecution/src/main.rs#L305)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why a lot of links? if there are many artifacts, you can link to the directory...
IMO it's ok if the link is long, as long as there is only one link
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r7, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2229)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 180 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCXcAU8609nA7FQlsqn:-OCXcAU941bqaJqc1mgg:b2wpvgd) ([raw file](https://github.com/starkware-libs/sequencer/blob/2ccf816e4bf8b236dffb83f23a28032756abb261/crates/blockifier_reexecution/src/main.rs#L180)):*
> ```XML
> 
>     let upload_dir =
>         |prefix| format!("https://console.cloud.google.com/storage/browser/{BUCKET}/{prefix}");
> ```

it's used once; no need for the lambda



_Code quote:_
```XML
    let upload_dir =
        |prefix| format!("https://console.cloud.google.com/storage/browser/{BUCKET}/{prefix}");
```

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/main.rs` line 180 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-OCXcAU8609nA7FQlsqn:-OCYFXBN1IgjXmyZMlmd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2ccf816e4bf8b236dffb83f23a28032756abb261/crates/blockifier_reexecution/src/main.rs#L180)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

it's used once; no need for the lambda
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2229#-:-OCYdl5B8p3LiKQNiEtm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
