### PR TITLE
refactor(starknet_integration_tests): moving all end_to_end_integration test functions to  a module

### PR DESCRIPTION
**Pull request by lev-starkware**
**Stack**:
- #2642
- #2598
- #2597 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2597)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2597#-ODgMZHt1o52BwqPJG2P:-ODkfqd322G5frMDoj8g:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c6ead48eab8ce976f822cd0971eb7e1f7a89c13d/crates/starknet_integration_tests/src/end_to_end_integration.rs#L17)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Needed?
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2597#-ODgMb1VEk6B16JQKv3p:-ODkfr1WBUkaGQyCfn17:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c6ead48eab8ce976f822cd0971eb7e1f7a89c13d/crates/starknet_integration_tests/src/end_to_end_integration.rs#L26)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Needed?
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2597#-ODgMcK94v2GO6tlulgt:-ODkfr_24fE9JQIb5h2X:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c6ead48eab8ce976f822cd0971eb7e1f7a89c13d/crates/starknet_integration_tests/src/end_to_end_integration.rs#L40)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Needed?
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2597#-:-ODl5Ryb6h7EnCwEnO7n:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Review by lev-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2597)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Comment by lev-starkware** [comment]
✓ Commit merged in pull request [#2598](https://github.com/starkware-libs/sequencer/pull/2598)

**Pull request closed without merging**
