### PR TITLE
chore(starknet_integration_tests): remove const for json rpc version

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
commit-id:bfb3bef3

---

**Stack**:
- #2611 ⬅
- #2610
- #2609
- #2608

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2611)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2611#-ODkLkXgDjZiChjF3pMq:-ODkLkXgDjZiChjF3pMr:bu1nyra) ([raw file](https://github.com/starkware-libs/sequencer/blob/43ae61ab2521a6c75449e773c3cc986b8d6f97bb/crates/starknet_integration_tests/src/config_utils.rs#L52)):*
> ```XML
> /// Creates a config file for the sequencer node for the end to end integration test.
> pub(crate) fn dump_config_file_changes(
>     config: &SequencerNodeConfig,
> ```

Should the sub-member of this struct still have the field `json_rpc_version` as a member of this struct?



_Code quote:_
```XML
SequencerNodeConfig
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2611)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2611#-ODkLkXgDjZiChjF3pMq:-ODl2oV6E2a2yqY2gREt:bbey122) ([raw file](https://github.com/starkware-libs/sequencer/blob/43ae61ab2521a6c75449e773c3cc986b8d6f97bb/crates/starknet_integration_tests/src/config_utils.rs#L52)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Should the sub-member of this struct still have the field `json_rpc_version` as a member of this struct?
</blockquote></details>

Yes, it is used to generate the rpc messages, please see https://github.com/starkware-libs/sequencer/blob/main/crates/starknet_gateway/src/rpc_state_reader.rs#L49-L59

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2611)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2611)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2611)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
