### PR TITLE
fix(blockifier): update compiler version

### PR DESCRIPTION
**Pull request by meship-starkware**

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2709)* status: 1 of 4 files reviewed, all discussions resolved

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2709)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 667 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2709#-OEIfh2h1II9BvsBuOa0:-OEIfh2i0A9vUhGALJ9e:bccijvm) ([raw file](https://github.com/starkware-libs/sequencer/blob/b618cf826540954cc694ee5ee5edea8558ceac9d/crates/blockifier/src/execution/syscalls/hint_processor.rs#L667)):*
> ```XML
>             Hint::Core(hint) => execute_core_hint_base(vm, exec_scopes, hint, false),
>             Hint::Starknet(hint) => self.execute_next_syscall(vm, hint),
>             Hint::External(_) => todo!("Handle External Hints."),
> ```

This is not the right solution, but I am not sure what external hints represent and how I should handle them



_Code quote:_
```XML
            Hint::Core(hint) => execute_core_hint_base(vm, exec_scopes, hint, false),
            Hint::Starknet(hint) => self.execute_next_syscall(vm, hint),
            Hint::External(_) => todo!("Handle External Hints."),
```

**Review by noaov1 — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2709)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 665 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2709#-OEIl48F4_ddfhdn1BsR:-OEIl48F4_ddfhdn1BsS:b-z1lqq0) ([raw file](https://github.com/starkware-libs/sequencer/blob/b618cf826540954cc694ee5ee5edea8558ceac9d/crates/blockifier/src/execution/syscalls/hint_processor.rs#L665)):*
> ```XML
>         let hint = hint_data.downcast_ref::<Hint>().ok_or(HintError::WrongHintData)?;
>         match hint {
>             Hint::Core(hint) => execute_core_hint_base(vm, exec_scopes, hint, false),
> ```

What does the `false` mean?



_Code quote:_
```XML
            Hint::Core(hint) => execute_core_hint_base(vm, exec_scopes, hint, false),
```

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 12 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2709)* status: 15 of 19 files reviewed, 2 unresolved discussions (waiting on @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2709)* status: 15 of 19 files reviewed, 4 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 665 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2709#-OEIl48F4_ddfhdn1BsR:-OEIn_tuCkQPvNEoph5C:bumnumv) ([raw file](https://github.com/starkware-libs/sequencer/blob/b618cf826540954cc694ee5ee5edea8558ceac9d/crates/blockifier/src/execution/syscalls/hint_processor.rs#L665)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What does the `false` mean?
</blockquote></details>

I am not sure this is the comment in the Cairo compiler:
/// Avoid allocating memory segments so that the finalization of the segment arena may not occur.
So, to my understanding, false here means we do not avoid allocating memory segments, but I am not sure I will ask someone from the compiler team. 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2438 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2709#-OEIp8Kj1_pcP_M9PcpU:-OEIp8Kj1_pcP_M9PcpV:b56kpvv) ([raw file](https://github.com/starkware-libs/sequencer/blob/c5031270ee8b8bf317cd1aa043483be631155113/crates/blockifier/src/transaction/transactions_test.rs#L2438)):*
> ```XML
>         computation: ComputationResources {
>             vm_resources: expected_execution_resources,
>             sierra_gas: gas_consumed.into(),
> ```

The cosmetic change for Cllipy does not relate to the Cairo version update.  



_Code quote:_
```XML
sierra_gas: gas_consumed.into(),
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/keccak.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2709#-OEIopzO2KlynD3Qf_1F:-OEIopzO2KlynD3Qf_1G:bbftzpq) ([raw file](https://github.com/starkware-libs/sequencer/blob/001b236919ca369b9110698e11d9b3285a3655f6/crates/blockifier/src/execution/syscalls/syscall_tests/keccak.rs#L29)):*
> ```XML
>     pretty_assertions::assert_eq!(
>         entry_point_call.execute_directly(&mut state).unwrap().execution,
>         CallExecution { gas_consumed: 254240, ..CallExecution::from_retdata(retdata![]) }
> ```

@ilyalesokhin-starkware, Can you make sure this gas change looks logical after the compiler version update?  



_Code quote:_
```XML
CallExecution { gas_consumed: 254240, ..CallExecution::from_retdata(retdata![]) }
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2709)* status: 15 of 19 files reviewed, 4 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 665 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2709#-OEIl48F4_ddfhdn1BsR:-OEIuo7c1xisB2FZOHN9:b-kn8nqb) ([raw file](https://github.com/starkware-libs/sequencer/blob/b618cf826540954cc694ee5ee5edea8558ceac9d/crates/blockifier/src/execution/syscalls/hint_processor.rs#L665)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I am not sure this is the comment in the Cairo compiler:
/// Avoid allocating memory segments so that the finalization of the segment arena may not occur.
So, to my understanding, false here means we do not avoid allocating memory segments, but I am not sure I will ask someone from the compiler team.
</blockquote></details>

Talked with Ori Ziv, and I understood correctly but as the segment arena  finalization is  only relevant to the proofs, so we do want to avoid allocating temporary segments    
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 667 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2709#-OEIfh2h1II9BvsBuOa0:-OEIw-2LBmPWqzCRv7-o:b-xkmwg4) ([raw file](https://github.com/starkware-libs/sequencer/blob/b618cf826540954cc694ee5ee5edea8558ceac9d/crates/blockifier/src/execution/syscalls/hint_processor.rs#L667)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

This is not the right solution, but I am not sure what external hints represent and how I should handle them
</blockquote></details>

The sequencer shouldn't get external hints

**Review by noaov1 — APPROVED** [review]
> Reviewed 3 of 16 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2709)* status: all files reviewed, 3 unresolved discussions

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2709)* status: 16 of 19 files reviewed, 2 unresolved discussions (waiting on @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2709)* status: 17 of 19 files reviewed, 2 unresolved discussions (waiting on @noaov1)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2709)* status: 18 of 19 files reviewed, 2 unresolved discussions (waiting on @noaov1)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/syscall_tests/keccak.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2709#-OEIopzO2KlynD3Qf_1F:-OEJM9Tf2FHKA5s-EYxc:bsretfv) ([raw file](https://github.com/starkware-libs/sequencer/blob/001b236919ca369b9110698e11d9b3285a3655f6/crates/blockifier/src/execution/syscalls/syscall_tests/keccak.rs#L29)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

@ilyalesokhin-starkware, Can you make sure this gas change looks logical after the compiler version update?
</blockquote></details>

Looks fine

**Pull request merged**
