### PR TITLE
test(blockifier): test contract for validate and execute merging

### PR DESCRIPTION
**Pull request by yoavGrs**

### CODE REVIEW

**Comment by yoavGrs** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2456?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2456** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2456?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2456?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2310** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2310?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2407** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2407?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2301** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2301?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2300** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2300?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2293** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2293?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2150** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2150?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2175** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2175?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2149** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2149?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2200** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2200?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2456)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2456#-ODGyrPXBsTFIg_LICsC:-ODGyrPXBsTFIg_LICsD:b-vp5h1k) (no related file):*
There are too many tests for the same function. I suggest deleting `test_state_cache_merge` and `test_allocated_keys_two_transactions`. WDYT?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2456)* status: all files reviewed, 5 unresolved discussions (waiting on @yoavGrs)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2456#-ODGyrPXBsTFIg_LICsC:-ODH0n1DEN__CKIEv-FR:b-p92pwk) (no related file):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

There are too many tests for the same function. I suggest deleting `test_state_cache_merge` and `test_allocated_keys_two_transactions`. WDYT?
</blockquote></details>

as long as the union of scenarios and union of assertions exist - sgtm
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 490 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2456#-ODH0Q6H1IJ9_AZnO44w:-ODH0Q6I1BmxgIdhggV4:b-g5x389) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ef88f8803030853ceafc5424bb5cb708cb36ed4/crates/blockifier/src/state/cached_state_test.rs#L490)):*
> ```XML
> #[case(true, felt!("0x7"), felt!("0x7"), true)]
> #[case(false, felt!("0x0"), felt!("0x8"), false)]
> #[case(true, felt!("0x7"), felt!("0x0"), false)]
> ```

give names to cases like this



_Suggestion:_
```XML
#[case::real_diff_nonzero_base(false, felt!("0x7"), felt!("0x8"), false)]
#[case::execute_allocation(true, felt!("0x0"), felt!("0x8"), true)]
#[case::validate_allocation(true, felt!("0x7"), felt!("0x7"), true)]
#[case::nonzero_to_zero_to_nonzero(false, felt!("0x0"), felt!("0x8"), false)]
#[case::zero_to_nonzero_to_zero(true, felt!("0x7"), felt!("0x0"), false)]
```
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 516 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2456#-ODH-uTf9piFibzdzykz:-ODH-uTf9piFibzdzyl-:b-nesjhs) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ef88f8803030853ceafc5424bb5cb708cb36ed4/crates/blockifier/src/state/cached_state_test.rs#L516)):*
> ```XML
>     });
>     let tx_execution_info =
>         invoke_tx.execute(&mut transactional_state, &block_context, false, true).unwrap();
> ```

you shouldn't need to create a transactional state



_Suggestion:_
```XML
    let signature =
        TransactionSignature(vec![Felt::from(STORAGE_WRITE), validate_value, execute_value]);
    let invoke_tx = account_invoke_tx(invoke_tx_args! {
        signature,
        sender_address: contract_address,
        calldata: create_calldata(contract_address, "foo", &[]),
    });
    let tx_execution_info =
        invoke_tx.execute(&mut state, &block_context, false, true).unwrap();
```
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 516 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2456#-ODH0C-r5KXmJJU5SftO:-ODH0C-r5KXmJJU5SftP:b65ulqt) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ef88f8803030853ceafc5424bb5cb708cb36ed4/crates/blockifier/src/state/cached_state_test.rs#L516)):*
> ```XML
>     });
>     let tx_execution_info =
>         invoke_tx.execute(&mut transactional_state, &block_context, false, true).unwrap();
> ```

why did you set charge_fee to false here?



_Code quote:_
```XML
false
```
___
*[`crates/blockifier/feature_contracts/cairo1/account_faulty.cairo` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2456#-ODH-beqABoP2XAbcL3q:-ODH-beqABoP2XAbcL3r:bli86lk) ([raw file](https://github.com/starkware-libs/sequencer/blob/3ef88f8803030853ceafc5424bb5cb708cb36ed4/crates/blockifier/feature_contracts/cairo1/account_faulty.cairo#L0)):*
can you add the same functionality to the cairo0 contract?
that way we will be able to parametrize the test to both cairo versions

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2456)* status: all files reviewed, 5 unresolved discussions (waiting on @yoavGrs)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2456#-:-ODHUjc0-g-dsXu8mOnk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1159 of 1159 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2456)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2456#-ODLIWmLDx14z01eehtU:-ODLIWmLDx14z01eehtV:byzi23j) (no related file):*
remove the target_vscode from this PR...
where did it come from? did you set up your vscode in some non-standard way? or should this dir be added to everyone's gitignore?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2456)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2456)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2456#-ODLIWmLDx14z01eehtU:-ODMFIYF8M82VEf1dfXv:b-f1h235) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

remove the target_vscode from this PR...
where did it come from? did you set up your vscode in some non-standard way? or should this dir be added to everyone's gitignore?
</blockquote></details>

Done.
Maybe it should be added to '.gitignore'. Let's talk offline.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2456)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2456#-ODLIWmLDx14z01eehtU:-ODMLRKnEkAjpMQse4Jp:b-iopfcu) (no related file):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Done.
Maybe it should be added to '.gitignore'. Let's talk offline.
</blockquote></details>

I still see the files in this PR..

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1158 of 1158 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2456)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2456)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
