### PR TITLE
refactor(starknet_batcher): delete the proposal manager

### PR DESCRIPTION
**Pull request by dafnamatsry**

### CODE REVIEW

**Comment by dafnamatsry** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2618?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2618** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2618?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2618?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2441** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2441?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2483** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2483?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2480** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2480?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2, 1 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2618)* status: all files reviewed, 5 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/proposal_manager.rs` line 0 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2618#-OEECwjO7LdvGVK6M2ri:-OEECwjO7LdvGVK6M2rj:b-nc9gm1) ([raw file](https://github.com/starkware-libs/sequencer/blob/e1fdcc860ab02a14d91498a99cabb0bd285ef929/crates/starknet_batcher/src/proposal_manager.rs#L0)):*
Delete files.
___
*[`crates/starknet_batcher/src/batcher.rs` line 289 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2618#-OEECArfCAXpBgUK7iZJ:-OEECArfCAXpBgUK7iZK:bieco8t) ([raw file](https://github.com/starkware-libs/sequencer/blob/e1fdcc860ab02a14d91498a99cabb0bd285ef929/crates/starknet_batcher/src/batcher.rs#L289)):*
> ```XML
>             // TODO(dafna): at this point the proposal result must be an error, since it finsisehd
>             // earlier than expected. Consider panicking instead of returning an error.
>             Ok(_) => Err(BatcherError::ProposalAlreadyFinished { proposal_id }),
> ```

Okay, let's panic.



_Code quote:_
```XML
            // TODO(dafna): at this point the proposal result must be an error, since it finsisehd
            // earlier than expected. Consider panicking instead of returning an error.
            Ok(_) => Err(BatcherError::ProposalAlreadyFinished { proposal_id }),
```
___
*[`crates/starknet_batcher/src/batcher.rs` line 300 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2618#-OEECS8-4c-HvHmQW9S6:-OEECS8-4c-HvHmQW9S7:bdvs1n4) ([raw file](https://github.com/starkware-libs/sequencer/blob/e1fdcc860ab02a14d91498a99cabb0bd285ef929/crates/starknet_batcher/src/batcher.rs#L300)):*
> ```XML
>         debug!("Send proposal content done for {}", proposal_id);
> 
>         self.validate_tx_streams.remove(&proposal_id);
> ```

expect.



_Code quote:_
```XML
self.validate_tx_streams.remove(&proposal_id);
```
___
*[`crates/starknet_batcher/src/batcher.rs` line 304 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2618#-OEEE2qw-eYGOl3yNuI7:-OEEE2qw-eYGOl3yNuI8:bn460a7) ([raw file](https://github.com/starkware-libs/sequencer/blob/e1fdcc860ab02a14d91498a99cabb0bd285ef929/crates/starknet_batcher/src/batcher.rs#L304)):*
> ```XML
>             if let Some(proposal_task) = self.active_proposal_task.take() {
>                 proposal_task.join_handle.await.ok();
>             }
> ```

Use `await_active_proposal()`.



_Code quote:_
```XML
            if let Some(proposal_task) = self.active_proposal_task.take() {
                proposal_task.join_handle.await.ok();
            }
```
___
*[`crates/starknet_batcher/src/batcher.rs` line 422 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2618#-OEEGyUrDOh7jxGGdcXy:-OEEGyUs6wGp6bNyQw7Z:b-651a50) ([raw file](https://github.com/starkware-libs/sequencer/blob/e1fdcc860ab02a14d91498a99cabb0bd285ef929/crates/starknet_batcher/src/batcher.rs#L422)):*
> ```XML
>         let mut active_proposal = self.active_proposal.lock().await;
>         if let Some(active_proposal_id) = *active_proposal {
>             return Err(BatcherError::ServerBusy {
> ```

This error name isn't very informative, should we change it? (In a different PR)



_Code quote:_
```XML
ServerBusy
```

**Review by alonh5 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2618)* status: all files reviewed, 5 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2618)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 289 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2618#-OEECArfCAXpBgUK7iZJ:-OEEZ7gI0ztGRq4zUJzI:bmjvrze) ([raw file](https://github.com/starkware-libs/sequencer/blob/e1fdcc860ab02a14d91498a99cabb0bd285ef929/crates/starknet_batcher/src/batcher.rs#L289)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Okay, let's panic.
</blockquote></details>

Done.
Note that I deleted a test that simulated this scenario (something that cannot happen for real).
___
*[`crates/starknet_batcher/src/batcher.rs` line 300 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2618#-OEECS8-4c-HvHmQW9S6:-OEEZR1S1aCGZslSC4yC:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e1fdcc860ab02a14d91498a99cabb0bd285ef929/crates/starknet_batcher/src/batcher.rs#L300)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

expect.
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher.rs` line 304 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2618#-OEEE2qw-eYGOl3yNuI7:-OEEelHJDVkIpHOF_xsX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e1fdcc860ab02a14d91498a99cabb0bd285ef929/crates/starknet_batcher/src/batcher.rs#L304)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Use `await_active_proposal()`.
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher.rs` line 422 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2618#-OEEGyUrDOh7jxGGdcXy:-OEEetOVAn1pwjcAEjep:bk0k37e) ([raw file](https://github.com/starkware-libs/sequencer/blob/e1fdcc860ab02a14d91498a99cabb0bd285ef929/crates/starknet_batcher/src/batcher.rs#L422)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This error name isn't very informative, should we change it? (In a different PR)
</blockquote></details>

Yes, something like `ProposalInProgress` would be better. WDYT?
___
*[`crates/starknet_batcher/src/proposal_manager.rs` line  at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2618#-OEECwjO7LdvGVK6M2ri:-OEEfecZ9_b_O5cx26-v:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e1fdcc860ab02a14d91498a99cabb0bd285ef929/crates/starknet_batcher/src/proposal_manager.rs#L)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Delete files.
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2618)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 289 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2618#-OEECArfCAXpBgUK7iZJ:-OEJS7zE7v42Gx9C4vV-:b-2s21fw) ([raw file](https://github.com/starkware-libs/sequencer/blob/e1fdcc860ab02a14d91498a99cabb0bd285ef929/crates/starknet_batcher/src/batcher.rs#L289)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Done.
Note that I deleted a test that simulated this scenario (something that cannot happen for real).
</blockquote></details>

I'm confused, how could it be simulated if it cannot happen?
___
*[`crates/starknet_batcher/src/batcher.rs` line 422 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2618#-OEEGyUrDOh7jxGGdcXy:-OEJQyhkDGMAfV0Lhydk:bfi6jb) ([raw file](https://github.com/starkware-libs/sequencer/blob/e1fdcc860ab02a14d91498a99cabb0bd285ef929/crates/starknet_batcher/src/batcher.rs#L422)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Yes, something like `ProposalInProgress` would be better. WDYT?
</blockquote></details>

Sounds good. New PR?

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2618)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 289 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2618#-OEECArfCAXpBgUK7iZJ:-OENkL2n8poV68ctPyZQ:b-4hwn5z) ([raw file](https://github.com/starkware-libs/sequencer/blob/e1fdcc860ab02a14d91498a99cabb0bd285ef929/crates/starknet_batcher/src/batcher.rs#L289)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I'm confused, how could it be simulated if it cannot happen?
</blockquote></details>

With a mock block builder. The test mocks a block builder that finish successfully. I the validate flow it can't finish successfully unless we get an explicit Finish request from the consensus.
___
*[`crates/starknet_batcher/src/batcher.rs` line 422 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2618#-OEEGyUrDOh7jxGGdcXy:-OENkgC7B89in51Oem0Z:b-h1jywd) ([raw file](https://github.com/starkware-libs/sequencer/blob/e1fdcc860ab02a14d91498a99cabb0bd285ef929/crates/starknet_batcher/src/batcher.rs#L422)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Sounds good. New PR?
</blockquote></details>

Yap, I'll open one.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2618#-:-OENnCu30SzHgC8WjYNV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2618)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
