### PR TITLE
chore(blockifier): alternate use of casm and native depending on tracked_resource

### PR DESCRIPTION
**Pull request by avivg-starkware**

### CODE REVIEW

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1699)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1699#-OAX09N16C2zZZo02Y_a:-OAX09N16C2zZZo02Y_b:b-1ok0k5) ([raw file](https://github.com/starkware-libs/sequencer/blob/b421a99d7339b77ec4509e2fcd8402442c1aa4ae/crates/blockifier/src/execution/execution_utils.rs#L145)):*
> ```XML
>         #[cfg(feature = "cairo_native")]
>         ContractClass::V1Native(contract_class) => {
>             if context.tracked_resource_stack.last() == Some(&TrackedResource::CairoSteps) {
> ```

Please add a doc explaining this behaviour. 



_Code quote:_
```XML
if context.tracked_resource_stack.last() == Some(&TrackedResource::CairoSteps) {
```

**Comment by avivg-starkware** [comment]
*[`crates/blockifier/src/execution/execution_utils.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1699#-OAX09N16C2zZZo02Y_a:-OAXYcHd2LXHfyPG4ce5:b-zakow8) ([raw file](https://github.com/starkware-libs/sequencer/blob/b421a99d7339b77ec4509e2fcd8402442c1aa4ae/crates/blockifier/src/execution/execution_utils.rs#L145)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please add a doc explaining this behaviour.
</blockquote></details>

added, WDYT?

**Review by avivg-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1699)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1699)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1699#-OAY7zLJDVLTkgBLzDNd:-OAY7zLJDVLTkgBLzDNe:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ca58734ee5ebc865460037abdf45045e0046de8/crates/blockifier/src/execution/execution_utils.rs#L147)):*
> ```XML
>             if context.tracked_resource_stack.last() == Some(&TrackedResource::CairoSteps) {
>                 // if CairoSteps are tracked instead of SierraGas, use Casm for all following
>                 // calling txs.
> ```





_Suggestion:_
```XML
            // We cannot run native with cairo steps as the tracked resources (it's a vm resouorce).
            if context.tracked_resource_stack.last() == Some(&TrackedResource::CairoSteps) {
```

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1699)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1699#-OAY7zLJDVLTkgBLzDNd:-OAY9T0Y3jgzoV6HTW6X:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ca58734ee5ebc865460037abdf45045e0046de8/crates/blockifier/src/execution/execution_utils.rs#L147)):*
> ```XML
>             if context.tracked_resource_stack.last() == Some(&TrackedResource::CairoSteps) {
>                 // if CairoSteps are tracked instead of SierraGas, use Casm for all following
>                 // calling txs.
> ```

Done.

**Review by avivg-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1699)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1699#-:-OAYCfSf3sL5iUvw3Y_T:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Pull request merged**
