### PR TITLE
refactor(batcher): small refactor to build_block_proposal

### PR DESCRIPTION
**Pull request by dafnamatsry**

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1910)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1910#-OBLXFovEDDsLbJZR5z3:-OBLXFowCAypXuCVtV89:b3ayxv1) ([raw file](https://github.com/starkware-libs/sequencer/blob/4107ee38d19135ed43b2eeace66cb57a49f15398/crates/batcher/src/proposal_manager.rs#L190)):*
> ```XML
>                         active_proposal.take();
>                     }
>                 }
> ```

Isn't it a bug if there isn't an active proposal in this stage?



_Code quote:_
```XML
                // The proposal is done, clear the active proposal.
                let mut active_proposal = active_proposal.lock().await;
                if let Some(current_active_proposal_id) = *active_proposal {
                    if current_active_proposal_id == proposal_id {
                        active_proposal.take();
                    }
                }
```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1910)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1910#-OBLXFovEDDsLbJZR5z3:-OBOsASSBYbr3V3fnKwU:b-3697s4) ([raw file](https://github.com/starkware-libs/sequencer/blob/4107ee38d19135ed43b2eeace66cb57a49f15398/crates/batcher/src/proposal_manager.rs#L190)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Isn't it a bug if there isn't an active proposal in this stage?
</blockquote></details>

No, because a proposal can be aborted, and a new height can start.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1910)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1910#-OBLXFovEDDsLbJZR5z3:-OBPGltxB9_-U8YLN3n4:b39ax9g) ([raw file](https://github.com/starkware-libs/sequencer/blob/4107ee38d19135ed43b2eeace66cb57a49f15398/crates/batcher/src/proposal_manager.rs#L190)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

No, because a proposal can be aborted, and a new height can start.
</blockquote></details>

Wouldn't an aborted proposal exit and return from `build_block()` in the design you suggested?

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1910)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1910#-OBLXFovEDDsLbJZR5z3:-OBPI_aI1bmBiSU9tidr:b-rhehmn) ([raw file](https://github.com/starkware-libs/sequencer/blob/4107ee38d19135ed43b2eeace66cb57a49f15398/crates/batcher/src/proposal_manager.rs#L190)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Wouldn't an aborted proposal exit and return from `build_block()` in the design you suggested?
</blockquote></details>

Yes it would.
But it will also clear the `active_proposal` without waiting for the task to clear it.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1910#-:-OBPKxEX51Y6DNey1-l0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1910#-OBLXFovEDDsLbJZR5z3:-OBPJiPTE36xwq5m7RhO:bcr5s31) ([raw file](https://github.com/starkware-libs/sequencer/blob/4107ee38d19135ed43b2eeace66cb57a49f15398/crates/batcher/src/proposal_manager.rs#L190)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Yes it would.
But it will also clear the `active_proposal` without waiting for the task to clear it.
</blockquote></details>

Got it, thanks.

**Pull request merged**
