### PR TITLE
feat(starknet_api): chain version to the gas prices

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1077)

### CODE REVIEW

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1077#-:-O7xSfT9A5rVV4XZ9RP9:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1077#-O7xSOlW9cCXxYwjm2J1:-O7xSOlW9cCXxYwjm2J2:b-xb15hx) ([raw file](https://github.com/starkware-libs/sequencer/blob/487b9d019b97b68b347784e3c917c603a6f4e4ab/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L34)):*
> ```XML
>     ascii_as_felt("STARKNET_BLOCK_HASH0").expect("ascii_as_felt failed for 'STARKNET_BLOCK_HASH0'")
> });
> static STARKNET_GAS_PRICES0: LazyLock<Felt> = LazyLock::new(|| {
> ```

consider renaming the constant to STARKNET_GAS_PRICES and maybe even adding a word after it (MAGIC? CONSTANT? PREFIX?)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1077)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1077#-O7xSOlW9cCXxYwjm2J1:-O7xZa703Bv9S9_0wuoM:bq057dl) ([raw file](https://github.com/starkware-libs/sequencer/blob/487b9d019b97b68b347784e3c917c603a6f4e4ab/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L34)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

consider renaming the constant to STARKNET_GAS_PRICES and maybe even adding a word after it (MAGIC? CONSTANT? PREFIX?)
</blockquote></details>

I think we can leave it that way.
When there are several options (in the next PR, I bump the block hash constant), their wrapper will contain a word like this.
@dorimedini-starkware

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1077)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama and @yoavGrs)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1077#-O7xSOlW9cCXxYwjm2J1:-O7xoXM82Up2ELWXvPuN:b6swocq) ([raw file](https://github.com/starkware-libs/sequencer/blob/487b9d019b97b68b347784e3c917c603a6f4e4ab/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L34)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

I think we can leave it that way.
When there are several options (in the next PR, I bump the block hash constant), their wrapper will contain a word like this.
@dorimedini-starkware
</blockquote></details>

what is the advantage of adding a new constant that will be bumped per version? why not bump the entire block hash version?
we currently do not provide a "gas prices commitment" via RPC or anything like that, right? if you want to compute a new hash you will need to hash the gas prices...

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1077)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1077#-O7xSOlW9cCXxYwjm2J1:-O80iQVV90fTxnU3ecbE:b-87qmx7) ([raw file](https://github.com/starkware-libs/sequencer/blob/487b9d019b97b68b347784e3c917c603a6f4e4ab/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L34)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what is the advantage of adding a new constant that will be bumped per version? why not bump the entire block hash version?
we currently do not provide a "gas prices commitment" via RPC or anything like that, right? if you want to compute a new hash you will need to hash the gas prices...
</blockquote></details>

It allows us to update the gas prices without bumping the block hash version.
It's continuing the goal of separating the gas prices from the global block hash.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1077)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Comment by ShahakShama** [comment]
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1077#-O7xSOlW9cCXxYwjm2J1:-O861-rf5BkA33U6Jap2:b-hk4e7t) ([raw file](https://github.com/starkware-libs/sequencer/blob/487b9d019b97b68b347784e3c917c603a6f4e4ab/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L34)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

It allows us to update the gas prices without bumping the block hash version.
It's continuing the goal of separating the gas prices from the global block hash.
</blockquote></details>

What Yoav said

**Pull request merged**
