### PR TITLE
feat(blockifier): add n_allocated_aliases to tx receipt

### PR DESCRIPTION
**Pull request by yoavGrs**

### CODE REVIEW

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1926)* status: all files reviewed, 7 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/fee/resources.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQZAgn5S0B7LVzxDPC:-OBQZAgn5S0B7LVzxDPD:b-efv8me) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/fee/resources.rs#L145)):*
> ```XML
> #[derive(Clone, Debug, Default, PartialEq)]
> pub struct StateResources {
>     state_changes_for_fee: StateChangesCount,
> ```

The name can be misleading; ` n_allocated_aliases` is also part of the fee.
Maybe should be renamed to `state_changes`? @dorimedini-starkware ?



_Code quote:_
```XML
state_changes_for_fee: StateChangesCount,
```
___
*[`crates/blockifier/src/fee/resources.rs` line 172 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQWmJcBiW9fibgCOP0:-OBQWmJcBiW9fibgCOP1:bpm3wdz) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/fee/resources.rs#L172)):*
> ```XML
>         // TODO(Nimrod, 29/3/2024): delete `get_da_gas_cost` and move it's logic here.
>         get_da_gas_cost(&self.state_changes_for_fee, use_kzg_da)
>     }
> ```

The fee needs also to depend on `self.n_allocated_aliases`.



_Suggestion:_
```XML
    pub fn to_gas_vector(&self, use_kzg_da: bool) -> GasVector {
        // TODO(Nimrod, 29/3/2024): delete `get_da_gas_cost` and move it's logic here.
        // TODO(Yoav): Take into account `self.n_allocated_aliases`.
        get_da_gas_cost(&self.state_changes_for_fee, use_kzg_da)
    }
```
___
*[`crates/blockifier/src/fee/resources.rs` line 176 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQWag85drNsjpdDLpc:-OBQWag85drNsjpdDLpd:bw81iqy) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/fee/resources.rs#L176)):*
> ```XML
>     pub fn get_onchain_data_segment_length(&self) -> usize {
>         get_onchain_data_segment_length(&self.state_changes_for_fee)
>     }
> ```

Here also (I think...). Better to add TODO to be on the safe side



_Suggestion:_
```XML
    pub fn get_onchain_data_segment_length(&self) -> usize {
        // TODO(Yoav): Take into account `self.n_allocated_aliases`.
        get_onchain_data_segment_length(&self.state_changes_for_fee)
    }
```
___
*[`crates/blockifier/src/execution/alias_keys.rs` line 4 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQTpXA3wp6UQ6-Tldr:-OBQTpXA3wp6UQ6-Tlds:b4wf5tl) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/execution/alias_keys.rs#L4)):*
> ```XML
> use crate::state::state_api::{StateReader, StateResult};
> 
> /// Returns the number of charged new allocated aliases.
> ```

I think it's more precise. Sometimes we charge but don't really need to allocate...



_Suggestion:_
```XML
/// Returns the number of aliases we charge the transaction for.
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 617 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQY1uM3fFTtGemZfLe:-OBQY1uN2Q-_-iBhc1cp:b-1zqgmd) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/transaction/account_transaction.rs#L617)):*
> ```XML
>         let state_changes = state.get_actual_state_changes()?;
>         let n_allocated_aliases =
>             self.n_charged_aliases(tx_context.clone(), state, &state_changes)?;
> ```

Did you check if there is a way to avoid the clone?



_Code quote:_
```XML
tx_context.clone()
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 700 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQYPzy51htfpDX3MWk:-OBQYPzy51htfpDX3MWl:b-1zqgmd) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/transaction/account_transaction.rs#L700)):*
> ```XML
>                 let execution_state_changes = execution_state.get_actual_state_changes()?;
>                 let n_allocated_aliases = self.n_charged_aliases(
>                     tx_context.clone(),
> ```

Did you check if there is a way to avoid the clone?



_Code quote:_
```XML
tx_context.clone()
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 813 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQUTZHDMXG1VoxRma8:-OBQUTZI3pmPGmXuKhy_:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/transaction/account_transaction.rs#L813)):*
> ```XML
>                 Self::Declare(_) => 1,
>                 Self::DeployAccount(_) => 1,
>                 Self::Invoke(_) => n_charged_invoke_aliases(state, state_changes)?,
> ```





_Suggestion:_
```XML
                Self::Declare(_) => 1, // Charge for introducing new class hash.
                Self::DeployAccount(_) => 1, // Charge for introducing new contract address.
                Self::Invoke(_) => n_charged_invoke_aliases(state, state_changes)?,
```

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1926)* status: all files reviewed, 7 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 700 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQYPzy51htfpDX3MWk:-OBQZjmk3TF16QbD7gFh:b-l4fsn8) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/transaction/account_transaction.rs#L700)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Did you check if there is a way to avoid the clone?
</blockquote></details>

or maybe its `Arc<T>` so the clone is cheap?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1926)* status: all files reviewed, 7 unresolved discussions (waiting on @nimrod-starkware and @yoavGrs)

___
*[`crates/blockifier/src/fee/resources.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQZAgn5S0B7LVzxDPC:-OBQ_P342rR8acOOWx5N:bj505ht) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/fee/resources.rs#L145)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

The name can be misleading; ` n_allocated_aliases` is also part of the fee.
Maybe should be renamed to `state_changes`? @dorimedini-starkware ?
</blockquote></details>

I think that
1. state_changes_for_fee can stay as is
2. n_allocated_aliases is incorrect IMO: this number shouldn't represent the number of new aliases, it should represent the number of values changed from zero to nonzero. not sure what a good name would be, `n_values_from_zero_to_nonzero` is a bit long, but `aliases` shouldn't be part of the name

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1926)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/execution/alias_keys.rs` line 4 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQTpXA3wp6UQ6-Tldr:-OBQc_cg2r4BcwvkxY1a:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/execution/alias_keys.rs#L4)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I think it's more precise. Sometimes we charge but don't really need to allocate...
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/resources.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQZAgn5S0B7LVzxDPC:-OBQjONw2pXTsGaQDTyV:b2s3pht) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/fee/resources.rs#L145)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think that
1. state_changes_for_fee can stay as is
2. n_allocated_aliases is incorrect IMO: this number shouldn't represent the number of new aliases, it should represent the number of values changed from zero to nonzero. not sure what a good name would be, `n_values_from_zero_to_nonzero` is a bit long, but `aliases` shouldn't be part of the name
</blockquote></details>

`zero_to_nonzero` has too many details.
Maybe `n_aliases_for_fee`?
___
*[`crates/blockifier/src/fee/resources.rs` line 172 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQWmJcBiW9fibgCOP0:-OBQn4UrEr1HA0pwlOxY:b5l15pg) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/fee/resources.rs#L172)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

The fee needs also to depend on `self.n_allocated_aliases`.
</blockquote></details>

I'm adding the logic here.
___
*[`crates/blockifier/src/fee/resources.rs` line 176 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQWag85drNsjpdDLpc:-OBQn7FjASrC39uYlcMb:b5l15pg) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/fee/resources.rs#L176)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Here also (I think...). Better to add TODO to be on the safe side
</blockquote></details>

I'm adding the logic here.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 617 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQY1uM3fFTtGemZfLe:-OBQdIkN5T2wiZCrZDu-:bc6gm5x) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/transaction/account_transaction.rs#L617)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Did you check if there is a way to avoid the clone?
</blockquote></details>

Cloning `Arc` is like creating a new reference - a cheap operation.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 700 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQYPzy51htfpDX3MWk:-OBQe2uJ45NA35tVtvb0:bhzlujk) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/transaction/account_transaction.rs#L700)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

or maybe its `Arc<T>` so the clone is cheap?
</blockquote></details>

Right, the second.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 813 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQUTZHDMXG1VoxRma8:-OBQeQfC17x640-XSOqi:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/transaction/account_transaction.rs#L813)):*
> ```XML
>                 Self::Declare(_) => 1,
>                 Self::DeployAccount(_) => 1,
>                 Self::Invoke(_) => n_charged_invoke_aliases(state, state_changes)?,
> ```

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1926)* status: 2 of 7 files reviewed, 7 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQZAgn5S0B7LVzxDPC:-OBQxUYP2dnw779aSA0H:bt9vn8) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/fee/resources.rs#L145)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

`zero_to_nonzero` has too many details.
Maybe `n_aliases_for_fee`?
</blockquote></details>

but you're not counting aliases. even keys that already have an alias can be charged if they were nullified and then modified again. maybe `n_allocated_leaves`, referring to the state tree(s)?

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1926)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/fee/resources.rs` line 172 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQWmJcBiW9fibgCOP0:-OBUABW18LIFTwyu5iPQ:b-irwhab) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/fee/resources.rs#L172)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

I'm adding the logic here.
</blockquote></details>

where?

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1926)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQZAgn5S0B7LVzxDPC:-OBZUgFF8W-q74RrJfoH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/fee/resources.rs#L145)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

but you're not counting aliases. even keys that already have an alias can be charged if they were nullified and then modified again. maybe `n_allocated_leaves`, referring to the state tree(s)?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/resources.rs` line 172 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBQWmJcBiW9fibgCOP0:-OBZS-y14lPRb-qRqmTx:b53c1cw) ([raw file](https://github.com/starkware-libs/sequencer/blob/dca476b61080d2dfba2a9a828cd995db4a42b07d/crates/blockifier/src/fee/resources.rs#L172)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

where?
</blockquote></details>

In `fn new`.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1926)* status: all files reviewed, 5 unresolved discussions (waiting on @nimrod-starkware and @yoavGrs)

___
*[`crates/blockifier/src/fee/resources.rs` line 159 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBZ_cIa80fAS3qF80Cq:-OBZus5h-tDZ4Qp64Lk5:b-fus3v1) ([raw file](https://github.com/starkware-libs/sequencer/blob/395cf0d033e8a7d2f6dd6509895475868bfed87c/crates/blockifier/src/fee/resources.rs#L159)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

`n_allocated_leaves` might be priced differently from other storage updates since they can't be compressed...
IDK if this the right way... @dorimedini-starkware ?
</blockquote></details>

answered below
___
*[`crates/blockifier/src/fee/receipt.rs` line 37 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBZv_JK5HGEamXWs5mY:-OBZv_JK5HGEamXWs5mZ:b-ie6nbe) ([raw file](https://github.com/starkware-libs/sequencer/blob/395cf0d033e8a7d2f6dd6509895475868bfed87c/crates/blockifier/src/fee/receipt.rs#L37)):*
> ```XML
>     reverted_steps: usize,
>     n_allocated_leaves: usize,
> }
> ```

what is this object and how does it relate to `TransactionReceipt`?



_Code quote:_
```XML
struct TransactionReceiptParameters<'a> {
    tx_context: &'a TransactionContext,
    calldata_length: usize,
    signature_length: usize,
    code_size: usize,
    state_changes: &'a StateChanges,
    sender_address: Option<ContractAddress>,
    l1_handler_payload_size: Option<usize>,
    execution_summary_without_fee_transfer: ExecutionSummary,
    execution_resources: &'a ExecutionResources,
    tx_type: TransactionType,
    reverted_steps: usize,
    n_allocated_leaves: usize,
}
```
___
*[`crates/blockifier/src/fee/receipt.rs` line 138 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBZv-zA1ARgCdddCOTV:-OBZv-zA1ARgCdddCOTW:b-4lup6g) ([raw file](https://github.com/starkware-libs/sequencer/blob/395cf0d033e8a7d2f6dd6509895475868bfed87c/crates/blockifier/src/fee/receipt.rs#L138)):*
> ```XML
>             tx_type: TransactionType::L1Handler,
>             reverted_steps: 0,
>             n_allocated_leaves: 0,
> ```

L1 handlers can create new leaves, right?
a user depositing funds from L1 to an account that isn't deployed yet, will cause the account address to get a new alias.
1. if `n_allocated_leaves` is for fee computation only, this is fine - we can cover the alias costs of L1 handlers. however, need to rename the field to `n_allocated_leaves_for_fee` to be explicit that this value is not a guarantee on the number of leaf allocations in practice.
2. otherwise, need to compute the actual value here... i.e. the `from_l1_handler` should get the n_leaves as extra input

WDYT?



_Code quote:_
```XML
n_allocated_leaves: 0,
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1509 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBZwwM684VgCJ0mhOD4:-OBZwwM684VgCJ0mhOD5:bobrlnf) ([raw file](https://github.com/starkware-libs/sequencer/blob/395cf0d033e8a7d2f6dd6509895475868bfed87c/crates/blockifier/src/transaction/transactions_test.rs#L1509)):*
> ```XML
>         ExecutionSummary::default(),
>     );
>     starknet_resources.state.n_allocated_leaves = 1; // Declare tx.
> ```

this `= 1` should be handled in `StateResources::new_for_testing` no?



_Code quote:_
```XML
    let state_changes_for_fee = declare_expected_state_changes_count(tx_version);
    let mut starknet_resources = StarknetResources::new(
        0,
        0,
        class_info.code_size(),
        StateResources::new_for_testing(state_changes_for_fee),
        None,
        ExecutionSummary::default(),
    );
    starknet_resources.state.n_allocated_leaves = 1; // Declare tx.
```
___
*[`crates/blockifier/src/fee/resources.rs` line 160 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBZuhMsCosFHiIfvVOd:-OBZuhMsCosFHiIfvVOe:b5vhqa8) ([raw file](https://github.com/starkware-libs/sequencer/blob/395cf0d033e8a7d2f6dd6509895475868bfed87c/crates/blockifier/src/fee/resources.rs#L160)):*
> ```XML
>             state_changes.count_for_fee_charge(sender_address, fee_token_address);
>         state_changes_for_fee.n_storage_updates += n_allocated_leaves;
>         Self { state_changes_for_fee, n_allocated_leaves }
> ```

do not add the allocated leaves to storage changes: when computing gas vector from this object, take the new leaves into account, but not at this point



_Suggestion:_
```XML
        Self { state_changes_for_fee, n_allocated_leaves }
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1926)* status: 2 of 13 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/fee/receipt.rs` line 37 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBZv_JK5HGEamXWs5mY:-OBeILkA7B2y6YlqhYfw:b-ig3z9z) ([raw file](https://github.com/starkware-libs/sequencer/blob/395cf0d033e8a7d2f6dd6509895475868bfed87c/crates/blockifier/src/fee/receipt.rs#L37)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what is this object and how does it relate to `TransactionReceipt`?
</blockquote></details>

This is the input for the constructor of `TransactionReceipt`.
___
*[`crates/blockifier/src/fee/receipt.rs` line 138 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBZv-zA1ARgCdddCOTV:-OBeKuR10AEDDK2yb6fA:bcenaiq) ([raw file](https://github.com/starkware-libs/sequencer/blob/395cf0d033e8a7d2f6dd6509895475868bfed87c/crates/blockifier/src/fee/receipt.rs#L138)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

L1 handlers can create new leaves, right?
a user depositing funds from L1 to an account that isn't deployed yet, will cause the account address to get a new alias.
1. if `n_allocated_leaves` is for fee computation only, this is fine - we can cover the alias costs of L1 handlers. however, need to rename the field to `n_allocated_leaves_for_fee` to be explicit that this value is not a guarantee on the number of leaf allocations in practice.
2. otherwise, need to compute the actual value here... i.e. the `from_l1_handler` should get the n_leaves as extra input

WDYT?
</blockquote></details>

Yes, 1 is the case.
Nevertheless, we can charge fee for alias costs of L1 handlers, with the same logic that will be implemented in `n_charged_invoke_aliases`. WDYT?
___
*[`crates/blockifier/src/fee/resources.rs` line 159 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBZ_cIa80fAS3qF80Cq:-OBeJ1Ka3BDe-znlBDtm:b-40xz88) ([raw file](https://github.com/starkware-libs/sequencer/blob/395cf0d033e8a7d2f6dd6509895475868bfed87c/crates/blockifier/src/fee/resources.rs#L159)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

answered below
</blockquote></details>

Okay, I'm keeping them separate.
___
*[`crates/blockifier/src/fee/resources.rs` line 160 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBZuhMsCosFHiIfvVOd:-OBeIh60DRoTV7V6wC4d:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/395cf0d033e8a7d2f6dd6509895475868bfed87c/crates/blockifier/src/fee/resources.rs#L160)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do not add the allocated leaves to storage changes: when computing gas vector from this object, take the new leaves into account, but not at this point
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1509 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBZwwM684VgCJ0mhOD4:-OBeyjhW87Wyu03RYwx_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/395cf0d033e8a7d2f6dd6509895475868bfed87c/crates/blockifier/src/transaction/transactions_test.rs#L1509)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this `= 1` should be handled in `StateResources::new_for_testing` no?
</blockquote></details>

Done.

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1926)* status: all files reviewed, 11 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 190 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1926#-OBsou-M4FYhj1UNnvK1:-OBsou-N7KHSlS8LPFTP:b-w851j3) ([raw file](https://github.com/starkware-libs/sequencer/blob/57d134d32c24ba440576c5d61acc61be83a338d4/crates/blockifier/src/fee/gas_usage.rs#L190)):*
> ```XML
>             n_compiled_class_hash_updates: 0,
>             n_modified_contracts: 1,
>             n_allocated_leaves_for_fee: 0,
> ```

`DepoyAccount`, I think, always introduces a new contract address, right?



_Suggestion:_
```XML
n_allocated_leaves_for_fee: 1,
```

**Pull request closed without merging**
