### PR TITLE
chore: use starknet api test utils macros in tests

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#1631** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1631?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1630** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1630?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1629** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1629?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1629)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/transaction/objects_test.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1629#-OASN1Hi8y8AsxeZLsuC:-OASN1Hi8y8AsxeZLsuD:bkhya82) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba34b4443e128c18d92c3526b8284815100e662d/crates/blockifier/src/transaction/objects_test.rs#L42)):*
> ```XML
>             class_hash,
>             storage_address: contract_address!(storage_address),
>             storage_key: starknet_api::storage_key!(storage_key),
> ```

Please use full import.



_Code quote:_
```XML
starknet_api::storage_key
```
___
*[`crates/papyrus_rpc/src/v0_8/api/test.rs` line 1162 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1629#-OASNKbf3ADehg27sOrV:-OASNKbg0p7L64tidgwU:blfspul) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba34b4443e128c18d92c3526b8284815100e662d/crates/papyrus_rpc/src/v0_8/api/test.rs#L1162)):*
> ```XML
>                 header.block_header_without_hash.block_number,
>             ))),
>             Box::new(starknet_api::class_hash!("0x7")),
> ```

Here as well.



_Code quote:_
```XML
starknet_api::class_hash!
```
___
*[`crates/papyrus_rpc/src/v0_8/api/test.rs` line 1223 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1629#-OASNO1M08W2-Pp-HSd4:-OASNO1M08W2-Pp-HSd5:b-strkvw) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba34b4443e128c18d92c3526b8284815100e662d/crates/papyrus_rpc/src/v0_8/api/test.rs#L1223)):*
> ```XML
>                 "0x642b629ad8ce233b55798c83bb629a59bf0a0092f67da28d6d66776680d5484"
>             ))))),
>             Box::new(starknet_api::class_hash!("0x7")),
> ```

Here as well.
and others in this file.



_Code quote:_
```XML
starknet_api::class_hash!
```
___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1629#-OASNhZ2Ezf9D5-BzWb9:-OASNhZ2Ezf9D5-BzWbA:bt7x02f) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba34b4443e128c18d92c3526b8284815100e662d/crates/starknet_api/src/rpc_transaction_test.rs#L64)):*
> ```XML
>         class_hash: class_hash!("0x2"),
>         constructor_calldata: Calldata(Arc::new(vec![Felt::ZERO])),
>         nonce: nonce!(0x60_u64),
> ```

Do you mean this?



_Suggestion:_
```XML
(60_u64
```

**Comment by ArniStarkware** [comment]
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1629#-OASNhZ2Ezf9D5-BzWb9:-OASVv422Jvng3B9J804:b-6cmnf) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba34b4443e128c18d92c3526b8284815100e662d/crates/starknet_api/src/rpc_transaction_test.rs#L64)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Do you mean this?
</blockquote></details>

No - The original number was "0x60".

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1629)* status: 19 of 22 files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/objects_test.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1629#-OASN1Hi8y8AsxeZLsuC:-OASgpdU45ladSbAa-Dz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba34b4443e128c18d92c3526b8284815100e662d/crates/blockifier/src/transaction/objects_test.rs#L42)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please use full import.
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_8/api/test.rs` line 1162 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1629#-OASNKbf3ADehg27sOrV:-OASgqM9BlIHwnZpiso7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba34b4443e128c18d92c3526b8284815100e662d/crates/papyrus_rpc/src/v0_8/api/test.rs#L1162)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Here as well.
</blockquote></details>

Done.
___
*[`crates/papyrus_rpc/src/v0_8/api/test.rs` line 1223 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1629#-OASNO1M08W2-Pp-HSd4:-OASgqmTEyzdOMnyaO06:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba34b4443e128c18d92c3526b8284815100e662d/crates/papyrus_rpc/src/v0_8/api/test.rs#L1223)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Here as well.
and others in this file.
</blockquote></details>

Done.

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1629)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1629#-OASNhZ2Ezf9D5-BzWb9:-OAWxCe8DgcpROEPG8cz:betn4up) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba34b4443e128c18d92c3526b8284815100e662d/crates/starknet_api/src/rpc_transaction_test.rs#L64)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

No - The original number was "0x60".
</blockquote></details>

I think it's because felt receives hex, and nonce receive u64.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1629)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1629#-OASNhZ2Ezf9D5-BzWb9:-OAX01eO4gPgSvnybayT:bxxk5lc) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba34b4443e128c18d92c3526b8284815100e662d/crates/starknet_api/src/rpc_transaction_test.rs#L64)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I think it's because felt receives hex, and nonce receive u64.
</blockquote></details>

This is not correct, but this does not matter.
Simplified.

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1629)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 78 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1629#-OAXaGq14pYJKdAaZhLS:-OAXaGq14pYJKdAaZhLT:byba3mr) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef2cad294b9059002db4b8d909939c4a2c3b4a26/crates/starknet_api/src/rpc_transaction_test.rs#L78)):*
> ```XML
>         calldata: Calldata(Arc::new(vec![felt!("0x2000"), felt!("0x1000")])),
>         sender_address: contract_address!("0x53"),
>         nonce: nonce!(0x32_u64),
> ```

Can you please change here as well?



_Code quote:_
```XML
nonce: nonce!(0x32_u64),
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1629)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/starknet_api/src/rpc_transaction_test.rs` line 78 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1629#-OAXaGq14pYJKdAaZhLS:-OAXczyV9HwOq67ocuRY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ef2cad294b9059002db4b8d909939c4a2c3b4a26/crates/starknet_api/src/rpc_transaction_test.rs#L78)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can you please change here as well?
</blockquote></details>

Done.

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1629#-:-OAXkd9p7d6G3EzGSP5G:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Oct 31, 10:29 AM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1629).

**Pull request merged**
