### PR TITLE
chore(blockifier): check max price of l1_data_gas and l2_gas

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/710)

### CODE REVIEW

**Review by nimrod-starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/710)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O6uF7N6EhfcYINKLVCf:-O6uF7N6EhfcYINKLVCg:b-iabw75) ([raw file](https://github.com/starkware-libs/sequencer/blob/bab93ccb0f0f4210d86094112efa0d8c92c23106/crates/blockifier/src/transaction/account_transaction.rs#L234)):*
> ```XML
>         tx_context: &TransactionContext,
>     ) -> TransactionPreValidationResult<()> {
>         // TODO(Aner): seprate to cases based on context.resource_bounds type
> ```

Looks like you can remove the todo, right?



_Code quote:_
```XML
// TODO(Aner): seprate to cases based on context.resource_bounds type
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 260 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O6uEu7G5TkXmrxI9q1y:-O6uEu7G5TkXmrxI9q1z:b-39soph) ([raw file](https://github.com/starkware-libs/sequencer/blob/bab93ccb0f0f4210d86094112efa0d8c92c23106/crates/blockifier/src/transaction/account_transaction.rs#L260)):*
> ```XML
>                                 // TODO(Ori, 1/2/2024): Write an indicative expect message
>                                 // explaining why the convertion
>                                 // works.
> ```

why did this change?



_Code quote:_
```XML
                                // TODO(Ori, 1/2/2024): Write an indicative expect message
                                // explaining why the convertion
                                // works.
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 292 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O6uPblD7obM_CSozQpD:-O6uPblE0KWFyzrrMirI:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/bab93ccb0f0f4210d86094112efa0d8c92c23106/crates/blockifier/src/transaction/account_transaction.rs#L292)):*
> ```XML
>                             })?;
>                         }
>                         // TODO(Aner): add checks for minimal_l1_data_gas and minimal_l2_gas
> ```





_Suggestion:_
```XML
// TODO(Aner): Add checks for minimal l1_data_gas and minimal l2_gas.
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 296 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O6uPgETD0Crb-wRYZkh:-O6uPgETD0Crb-wRYZki:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/bab93ccb0f0f4210d86094112efa0d8c92c23106/crates/blockifier/src/transaction/account_transaction.rs#L296)):*
> ```XML
>                         let GasPricesForFeeType { l1_gas_price, l1_data_gas_price, l2_gas_price } =
>                             block_info.gas_prices.get_gas_prices_by_fee_type(fee_type);
>                         // TODO!(Aner): add tests for l1_data_gas_price and l2_gas_price
> ```





_Suggestion:_
```XML
// TODO(Aner): Add tests for l1_data_gas_price and l2_gas_price.
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 300 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O6uPlHJEyuBMLG3U5Z1:-O6uPlHJEyuBMLG3U5Z2:b-5fack2) ([raw file](https://github.com/starkware-libs/sequencer/blob/bab93ccb0f0f4210d86094112efa0d8c92c23106/crates/blockifier/src/transaction/account_transaction.rs#L300)):*
> ```XML
>                             (L1Gas, l1_gas.max_price_per_unit, l1_gas_price.into()),
>                             (L1DataGas, l1_data_gas.max_price_per_unit, l1_data_gas_price.into()),
>                             (L2Gas, l2_gas.max_price_per_unit, l2_gas_price.into()),
> ```

The order of the iteration matters if there is more than one resource that is too expensive, @dorimedini-starkware WDYT?



_Code quote:_
```XML
                        for (gas_type, max_gas_price, actual_gas_price) in [
                            (L1Gas, l1_gas.max_price_per_unit, l1_gas_price.into()),
                            (L1DataGas, l1_data_gas.max_price_per_unit, l1_data_gas_price.into()),
                            (L2Gas, l2_gas.max_price_per_unit, l2_gas_price.into()),
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 986 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O6uPSlj4ovtmsetIZHC:-O6uPSlj4ovtmsetIZHD:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/bab93ccb0f0f4210d86094112efa0d8c92c23106/crates/blockifier/src/transaction/transactions_test.rs#L986)):*
> ```XML
>     );
> 
>     // TODO(Aner): add test for low Max L1 data gas price and L2 gas price
> ```





_Suggestion:_
```XML
// TODO(Aner): Add test for low max L1 data gas price and L2 gas price.
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/710)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O6uF7N6EhfcYINKLVCf:-O7-DN940sDdqTgYgSPP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bab93ccb0f0f4210d86094112efa0d8c92c23106/crates/blockifier/src/transaction/account_transaction.rs#L234)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Looks like you can remove the todo, right?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 260 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O6uEu7G5TkXmrxI9q1y:-O7-6EjrEm_MKl55646u:b-wzyqcv) ([raw file](https://github.com/starkware-libs/sequencer/blob/bab93ccb0f0f4210d86094112efa0d8c92c23106/crates/blockifier/src/transaction/account_transaction.rs#L260)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

why did this change?
</blockquote></details>

The quoted comment didn't change (though it had a typo, so I fixed it now), but the error type changed to accommodate the different resources.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 292 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O6uPblD7obM_CSozQpD:-O7-Dt6n0Nlt1e5u2Unw:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bab93ccb0f0f4210d86094112efa0d8c92c23106/crates/blockifier/src/transaction/account_transaction.rs#L292)):*
> ```XML
>                             })?;
>                         }
>                         // TODO(Aner): add checks for minimal_l1_data_gas and minimal_l2_gas
> ```

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 296 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O6uPgETD0Crb-wRYZkh:-O7-Dw0B3bO-lPgzW7Dy:b-h44apy) ([raw file](https://github.com/starkware-libs/sequencer/blob/bab93ccb0f0f4210d86094112efa0d8c92c23106/crates/blockifier/src/transaction/account_transaction.rs#L296)):*
> ```XML
>                         let GasPricesForFeeType { l1_gas_price, l1_data_gas_price, l2_gas_price } =
>                             block_info.gas_prices.get_gas_prices_by_fee_type(fee_type);
>                         // TODO!(Aner): add tests for l1_data_gas_price and l2_gas_price
> ```

Done. The `!` symbolizes that it needs to be done in the following PR.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 986 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O6uPSlj4ovtmsetIZHC:-O7-ETbuA_dmB6uxxeZU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bab93ccb0f0f4210d86094112efa0d8c92c23106/crates/blockifier/src/transaction/transactions_test.rs#L986)):*
> ```XML
>     );
> 
>     // TODO(Aner): add test for low Max L1 data gas price and L2 gas price
> ```

Done.

**Review by nimrod-starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/710)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @dorimedini-starkware, and @TzahiTaub)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/710)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 300 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O6uPlHJEyuBMLG3U5Z1:-O73OAOc6OdINkZk0G5_:b-blh2oc) ([raw file](https://github.com/starkware-libs/sequencer/blob/bab93ccb0f0f4210d86094112efa0d8c92c23106/crates/blockifier/src/transaction/account_transaction.rs#L300)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

The order of the iteration matters if there is more than one resource that is too expensive, @dorimedini-starkware WDYT?
</blockquote></details>

I think we should do better: the error we return should indicate exactly which gas price(s) are too low.
You should be collecting all problematic (gas_type, max_price, actual_price) tuples and outputting all of them in the error.
The `MaxGasPriceTooLow` error should be updated to include a collection of such triples.
That way, the order won't matter, and the users will get the most information

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/transaction/account_transaction.rs` line 300 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O6uPlHJEyuBMLG3U5Z1:-O73gNPT3XGw0P0wI6kH:buqmdrk) ([raw file](https://github.com/starkware-libs/sequencer/blob/bab93ccb0f0f4210d86094112efa0d8c92c23106/crates/blockifier/src/transaction/account_transaction.rs#L300)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think we should do better: the error we return should indicate exactly which gas price(s) are too low.
You should be collecting all problematic (gas_type, max_price, actual_price) tuples and outputting all of them in the error.
The `MaxGasPriceTooLow` error should be updated to include a collection of such triples.
That way, the order won't matter, and the users will get the most information
</blockquote></details>

@AvivYossef-starkware I'm guessing this will affect your PRs as well.

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/710)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 300 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O6uPlHJEyuBMLG3U5Z1:-O73p3k753HFD3BRctVT:b-f0rs8e) ([raw file](https://github.com/starkware-libs/sequencer/blob/bab93ccb0f0f4210d86094112efa0d8c92c23106/crates/blockifier/src/transaction/account_transaction.rs#L300)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

@AvivYossef-starkware I'm guessing this will affect your PRs as well.
</blockquote></details>

I changed the error in my PR to include it

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/710)* status: 0 of 62 files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 300 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O6uPlHJEyuBMLG3U5Z1:-O7VCwBH--_G57v-RLHY:bkd5ega) ([raw file](https://github.com/starkware-libs/sequencer/blob/bab93ccb0f0f4210d86094112efa0d8c92c23106/crates/blockifier/src/transaction/account_transaction.rs#L300)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

I changed the error in my PR to include it
</blockquote></details>

Added a TODO

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/710)* status: 3 of 62 files reviewed, 5 unresolved discussions (waiting on @aner-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 239 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O7YYAUDBV0fn8sbi5IL:-O7YYAUE42ikUwsDT5fi:bu820sj) ([raw file](https://github.com/starkware-libs/sequencer/blob/928a8832607275f890b511a652642886cfd0e59c/crates/blockifier/src/transaction/account_transaction.rs#L239)):*
> ```XML
>             &tx_context.get_gas_vector_computation_mode(),
>         )?;
> ```

Remove the blank line IMO, as the first let just creates a temp var for the second let.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 247 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O7YqEqSBRlY0MG5nKTS:-O7YqEqSBRlY0MG5nKTT:b8fswvw) ([raw file](https://github.com/starkware-libs/sequencer/blob/928a8832607275f890b511a652642886cfd0e59c/crates/blockifier/src/transaction/account_transaction.rs#L247)):*
> ```XML
>         let fee_type = &tx_info.fee_type();
>         match tx_info {
>             TransactionInfo::Current(context) => {
> ```

Remove this and its counterpart and you'll earn one less indentation.



_Suggestion:_
```XML
TransactionInfo::Current(context) => 
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 249 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O7YZZA02JE88mC3YycZ:-O7YZZA02JE88mC3Yyc_:bbstuba) ([raw file](https://github.com/starkware-libs/sequencer/blob/928a8832607275f890b511a652642886cfd0e59c/crates/blockifier/src/transaction/account_transaction.rs#L249)):*
> ```XML
>             TransactionInfo::Current(context) => {
>                 match &context.resource_bounds {
>                     starknet_api::transaction::ValidResourceBounds::L1Gas(ResourceBounds {
> ```

Remove and add `ValidResourceBounds` to the imports.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 277 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O7YZeC9BnraRDWv5g7J:-O7YZeC9BnraRDWv5g7K:b-8a05gs) ([raw file](https://github.com/starkware-libs/sequencer/blob/928a8832607275f890b511a652642886cfd0e59c/crates/blockifier/src/transaction/account_transaction.rs#L277)):*
> ```XML
>                         }
>                     }
>                     starknet_api::transaction::ValidResourceBounds::AllResources(
> ```

As above

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/710)* status: 3 of 62 files reviewed, 5 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 239 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O7YYAUDBV0fn8sbi5IL:-O7YvTqx3D7d4IkFZ8vz:b49ttpp) ([raw file](https://github.com/starkware-libs/sequencer/blob/928a8832607275f890b511a652642886cfd0e59c/crates/blockifier/src/transaction/account_transaction.rs#L239)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Remove the blank line IMO, as the first let just creates a temp var for the second let.
</blockquote></details>

OK, but this part will change anyway in a future PR.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 247 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O7YqEqSBRlY0MG5nKTS:-O7YvGHK5FvqGxMJyDaT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/928a8832607275f890b511a652642886cfd0e59c/crates/blockifier/src/transaction/account_transaction.rs#L247)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Remove this and its counterpart and you'll earn one less indentation.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 249 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O7YZZA02JE88mC3YycZ:-O7Yvc9j7yyMMEzhrc6C:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/928a8832607275f890b511a652642886cfd0e59c/crates/blockifier/src/transaction/account_transaction.rs#L249)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Remove and add `ValidResourceBounds` to the imports.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 277 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O7YZeC9BnraRDWv5g7J:-O7Yvd-o5SM2DyADwiDa:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/928a8832607275f890b511a652642886cfd0e59c/crates/blockifier/src/transaction/account_transaction.rs#L277)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

As above
</blockquote></details>

Done.

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, 1 of 4 files at r3, 56 of 60 files at r16, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/710)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 293 at r18](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O7Z5R1_DY67GIdGkn3C:-O7Z5R1_DY67GIdGkn3D:b-fh49qp) ([raw file](https://github.com/starkware-libs/sequencer/blob/c833d067513fe09dfdd10f6cc0e5361b3a0dbfaa/crates/blockifier/src/transaction/account_transaction.rs#L293)):*
> ```XML
>                                 .expect("Failed to convert u128 to u64.")),
>                         })?;
>                     }
> ```

IMO - add some inner function (defined in this function) for this and call it here and above to avoid code duplication.



_Code quote:_
```XML
                    let max_l1_gas_amount_as_u128: u128 = l1_gas.max_amount.into();
                    if max_l1_gas_amount_as_u128 < minimal_l1_gas_amount {
                        return Err(TransactionFeeError::MaxGasAmountTooLow {
                            resource: L1Gas,
                            max_gas_amount: l1_gas.max_amount,
                            // TODO(Ori, 1/2/2024): Write an indicative expect message
                            // explaining why the conversion
                            // works.
                            minimal_gas_amount: (minimal_l1_gas_amount
                                .try_into()
                                .expect("Failed to convert u128 to u64.")),
                        })?;
                    }
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/710)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 293 at r18](https://reviewable.io/reviews/starkware-libs/sequencer/710#-O7Z5R1_DY67GIdGkn3C:-O7Z95JGD7TnclZL5-4p:bopq24r) ([raw file](https://github.com/starkware-libs/sequencer/blob/c833d067513fe09dfdd10f6cc0e5361b3a0dbfaa/crates/blockifier/src/transaction/account_transaction.rs#L293)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

IMO - add some inner function (defined in this function) for this and call it here and above to avoid code duplication.
</blockquote></details>

I think this part changes, and also this refactoring appears in several places. I'll add a TODO for refactoring in the following PR.

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/710#-:-O7ZGYcy98l-1o-Rb06s:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

**Review by aner-starkware — COMMENTED** [review]
> Dismissed @nimrod-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/710)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
