### PR TITLE
build(blockifier_reexecution): deserialize getstateupdate rpc request

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1266)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1266)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1266#-O953K4s9niAlhQ2U5o4:-O953K4s9niAlhQ2U5o5:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0272d7390f39eb237693ed1085c38e7f8037674/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L96)):*
> ```XML
> pub fn test_get_statediff_rpc(test_state_reader: TestStateReader) {
>     let _statediff_result: CommitmentStateDiff = test_state_reader.get_state_diff().unwrap();
> }
> ```





_Suggestion:_
```XML
#[rstest]
pub fn test_get_statediff_rpc(test_state_reader: TestStateReader) {
    test_state_reader.get_state_diff().unwrap();
}
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1266#-O953xxd0EARYOVZPIMT:-O953xxd0EARYOVZPIMU:b-f3x691) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0272d7390f39eb237693ed1085c38e7f8037674/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L225)):*
> ```XML
>         let _deprecated_declared_classes: Vec<Value> =
>             serde_json::from_value(raw_statediff["deprecated_declared_classes"].clone())
>                 .map_err(serde_err_to_state_err)?;
> ```

delete (unused)



_Code quote:_
```XML
        let _deprecated_declared_classes: Vec<Value> =
            serde_json::from_value(raw_statediff["deprecated_declared_classes"].clone())
                .map_err(serde_err_to_state_err)?;
```
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1266#-O95175Z35pVb9HNoc5z:-O95175Z35pVb9HNoc6-:b40s1r8) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0272d7390f39eb237693ed1085c38e7f8037674/crates/blockifier_reexecution/src/state_reader/utils.rs#L42)):*
> ```XML
> }
> 
> pub fn deserialize_transaction_json_to_starknet_api_tx(
> ```

this function - and the new functions below (except `disjoint_hashmap_union`) - should be in their own module, e.g. `serde_utils.rs` next to the `utils.rs` module



_Code quote:_
```XML
pub fn deserialize_transaction_json_to_starknet_api_tx(
```
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1266#-O953ALm283NaI79_uoA:-O953ALm283NaI79_uoB:bfz0ous) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0272d7390f39eb237693ed1085c38e7f8037674/crates/blockifier_reexecution/src/state_reader/utils.rs#L192)):*
> ```XML
>         })
>         .collect()
> }
> ```

can this logic imported from some external RPC client crate?
or at least copied from some external project, with a reference link?



_Code quote:_
```XML
pub(crate) fn disjoint_hashmap_union<K: std::hash::Hash + std::cmp::Eq, V>(
    map1: IndexMap<K, V>,
    map2: IndexMap<K, V>,
) -> IndexMap<K, V> {
    let expected_len = map1.len() + map2.len();
    let union_map: IndexMap<K, V> = map1.into_iter().chain(map2).collect();
    // verify union length is sum of lengths (disjoint union)
    assert_eq!(union_map.len(), expected_len, "Intersection of hashmaps is not empty.");
    union_map
}

pub(crate) fn hashmap_from_raw<
    K: for<'de> Deserialize<'de> + Eq + std::hash::Hash,
    V: for<'de> Deserialize<'de>,
>(
    raw_object: &Value,
    vec_str: &str,
    key_str: &str,
    value_str: &str,
) -> StateResult<IndexMap<K, V>> {
    Ok(vec_to_hashmap::<K, V>(
        serde_json::from_value(raw_object[vec_str].clone()).map_err(serde_err_to_state_err)?,
        key_str,
        value_str,
    ))
}

pub(crate) fn nested_hashmap_from_raw<
    K: for<'de> Deserialize<'de> + Eq + std::hash::Hash,
    VK: for<'de> Deserialize<'de> + Eq + std::hash::Hash,
    VV: for<'de> Deserialize<'de>,
>(
    raw_object: &Value,
    vec_str: &str,
    key_str: &str,
    value_str: &str,
    inner_key_str: &str,
    inner_value_str: &str,
) -> StateResult<IndexMap<K, IndexMap<VK, VV>>> {
    Ok(vec_to_nested_hashmap::<K, VK, VV>(
        serde_json::from_value(raw_object[vec_str].clone()).map_err(serde_err_to_state_err)?,
        key_str,
        value_str,
        inner_key_str,
        inner_value_str,
    ))
}

pub(crate) fn vec_to_hashmap<
    K: for<'de> Deserialize<'de> + Eq + std::hash::Hash,
    V: for<'de> Deserialize<'de>,
>(
    vec: Vec<Value>,
    key_str: &str,
    value_str: &str,
) -> IndexMap<K, V> {
    vec.iter()
        .map(|element| {
            (
                serde_json::from_value(element[key_str].clone())
                    .expect("Key string doesn't match expected."),
                serde_json::from_value(element[value_str].clone())
                    .expect("Value string doesn't match expected."),
            )
        })
        .collect()
}

pub(crate) fn vec_to_nested_hashmap<
    K: for<'de> Deserialize<'de> + Eq + std::hash::Hash,
    VK: for<'de> Deserialize<'de> + Eq + std::hash::Hash,
    VV: for<'de> Deserialize<'de>,
>(
    vec: Vec<Value>,
    key_str: &str,
    value_str: &str,
    inner_key_str: &str,
    inner_value_str: &str,
) -> IndexMap<K, IndexMap<VK, VV>> {
    vec.iter()
        .map(|element| {
            (
                serde_json::from_value(element[key_str].clone()).expect("Couldn't deserialize key"),
                vec_to_hashmap(
                    serde_json::from_value(element[value_str].clone())
                        .expect("Couldn't deserialize value"),
                    inner_key_str,
                    inner_value_str,
                ),
            )
        })
        .collect()
}
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1266)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1266)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1266#-O953K4s9niAlhQ2U5o4:-O99F04zBX0gHNwnUmsl:bv6ywgy) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0272d7390f39eb237693ed1085c38e7f8037674/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L96)):*
> ```XML
> pub fn test_get_statediff_rpc(test_state_reader: TestStateReader) {
>     let _statediff_result: CommitmentStateDiff = test_state_reader.get_state_diff().unwrap();
> }
> ```

This way, we don't force the return type, which is what I was trying to do.
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1266#-O953xxd0EARYOVZPIMT:-O99ELMz7EGpMsyecnTW:bghv932) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0272d7390f39eb237693ed1085c38e7f8037674/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L225)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete (unused)
</blockquote></details>

But we'll probably need it later on, right? This will make it easier to use it in any following PR.
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1266#-O95175Z35pVb9HNoc5z:-O99KZX_1L8WqukONrcr:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0272d7390f39eb237693ed1085c38e7f8037674/crates/blockifier_reexecution/src/state_reader/utils.rs#L42)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this function - and the new functions below (except `disjoint_hashmap_union`) - should be in their own module, e.g. `serde_utils.rs` next to the `utils.rs` module
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1266#-O953ALm283NaI79_uoA:-O99G6nT4C2q4a8JTAXF:b-rzh6ix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0272d7390f39eb237693ed1085c38e7f8037674/crates/blockifier_reexecution/src/state_reader/utils.rs#L192)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can this logic imported from some external RPC client crate?
or at least copied from some external project, with a reference link?
</blockquote></details>

I assume so, but it will require a bit of time and digging. I'll add a TODO.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1266)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1266#-O953K4s9niAlhQ2U5o4:-O99LGQX24vkXB5YtcvI:b9pajqu) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0272d7390f39eb237693ed1085c38e7f8037674/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L96)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

This way, we don't force the return type, which is what I was trying to do.
</blockquote></details>

the return type is enforced by the compiler; calling `unwrap()` makes sure you get the `Ok` variant (CommitmentStateDiff).
`assert!(...is_ok())` is also fine
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1266#-O953xxd0EARYOVZPIMT:-O99KuVeEt_9rEjRqhLj:bi7t3kx) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0272d7390f39eb237693ed1085c38e7f8037674/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L225)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

But we'll probably need it later on, right? This will make it easier to use it in any following PR.
</blockquote></details>

code should be added in the PR it is used. you don't support declares yet.
if you want you can add a check if `deprecated_declared_classes` is non-empty and if so call `unimplemented!()`, but don't create an unused variable "for later"

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1266#-O953K4s9niAlhQ2U5o4:-O99NwBM0kgNokOGCzfK:b6q1h7l) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0272d7390f39eb237693ed1085c38e7f8037674/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L96)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the return type is enforced by the compiler; calling `unwrap()` makes sure you get the `Ok` variant (CommitmentStateDiff).
`assert!(...is_ok())` is also fine
</blockquote></details>

I mean we don't enforce the return type to be `CommitmentStateDiff`

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1266)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1266#-O953xxd0EARYOVZPIMT:-O99Pp_I9_GwyBKvcQ8r:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0272d7390f39eb237693ed1085c38e7f8037674/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L225)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

code should be added in the PR it is used. you don't support declares yet.
if you want you can add a check if `deprecated_declared_classes` is non-empty and if so call `unimplemented!()`, but don't create an unused variable "for later"
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1266#-:-O99wvdi27N7_bd14Bp9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1266#-O953K4s9niAlhQ2U5o4:-O99we9r2qURUhEdAbgd:b-xt89h3) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0272d7390f39eb237693ed1085c38e7f8037674/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L96)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I mean we don't enforce the return type to be `CommitmentStateDiff`
</blockquote></details>

we shouldn't test for that... if you change the return type in `get_state_diff` tests shouldn't break for no reason

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 7 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1266)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
