### PR TITLE
feat(gateway): add non zero l1 data gas validation to gateway

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1993)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_gateway/src/config.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1993#-OBZsj191J6hgaH-ir8P:-OBZsj191J6hgaH-ir8Q:bmgroac) ([raw file](https://github.com/starkware-libs/sequencer/blob/a32f28e203916d65a35d063d0892b362e6e53674/crates/starknet_gateway/src/config.rs#L60)):*
> ```XML
>             validate_non_zero_l1_gas_fee: true,
>             validate_non_zero_l2_gas_fee: false,
>             validate_non_zero_l1_data_gas_fee: false,
> ```

In the pythonic gateway it isn't validated?



_Code quote:_
```XML
validate_non_zero_l1_data_gas_fee: false,
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1993)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/starknet_gateway/src/config.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1993#-OBZsj191J6hgaH-ir8P:-OB_1fiBBLICw_P36dcS:b-j4o01f) ([raw file](https://github.com/starkware-libs/sequencer/blob/a32f28e203916d65a35d063d0892b362e6e53674/crates/starknet_gateway/src/config.rs#L60)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

In the pythonic gateway it isn't validated?
</blockquote></details>

The original validation came from [here](https://github.com/starkware-industries/starkware/blob/e3a7d75bbdfe92750ef0ddf1ac53479bb372bada/src/starkware/starknet/services/api/gateway/account_transaction.py#L58-L65).
This code is 14 months old. This code is from before L1 data gas was in use.

Python has no corresponding validation for L2 gas and for L1_DATA gas.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1993)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_gateway/src/config.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1993#-OBZsj191J6hgaH-ir8P:-OB_6qCW-V6qBgYgABMX:b-biz39l) ([raw file](https://github.com/starkware-libs/sequencer/blob/a32f28e203916d65a35d063d0892b362e6e53674/crates/starknet_gateway/src/config.rs#L60)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The original validation came from [here](https://github.com/starkware-industries/starkware/blob/e3a7d75bbdfe92750ef0ddf1ac53479bb372bada/src/starkware/starknet/services/api/gateway/account_transaction.py#L58-L65).
This code is 14 months old. This code is from before L1 data gas was in use.

Python has no corresponding validation for L2 gas and for L1_DATA gas.
</blockquote></details>

Oh I see, so why do we need those validations?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1993)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/starknet_gateway/src/config.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1993#-OBZsj191J6hgaH-ir8P:-OB_AMNa2xkzwiWbWQ7L:b6j452f) ([raw file](https://github.com/starkware-libs/sequencer/blob/a32f28e203916d65a35d063d0892b362e6e53674/crates/starknet_gateway/src/config.rs#L60)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Oh I see, so why do we need those validations?
</blockquote></details>

For L1 - It happens in the Pythonic gateway, so I just went with it.
For L2 and L1-Data - For consistency. Future compatibility (When we would like to enable this validation - it will be just a click away).

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1993#-:-OB_JDlW738tZQYPQoez:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/starknet_gateway/src/config.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1993#-OBZsj191J6hgaH-ir8P:-OB_IiwH3jJvmJXYv2Ds:b-sb1jde) ([raw file](https://github.com/starkware-libs/sequencer/blob/a32f28e203916d65a35d063d0892b362e6e53674/crates/starknet_gateway/src/config.rs#L60)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

For L1 - It happens in the Pythonic gateway, so I just went with it.
For L2 and L1-Data - For consistency. Future compatibility (When we would like to enable this validation - it will be just a click away).
</blockquote></details>

Okay. I'm not sure we will want these validations at all in the future. But if it's already done let's merge it, worst case we can delete it.

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1993)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1993)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
