### PR TITLE
fix(sequencing): imporve e2e flow test assertion messages

### PR DESCRIPTION
**Pull request by guy-starkware**
This makes the errors on one of the e2e flow test more comprehensible.

### CODE REVIEW

**Comment by guy-starkware** [comment]
* **#2580** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2580?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2580?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2580)* status: all files reviewed, 1 unresolved discussion (waiting on @guy-starkware)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2580#-ODfCGUA7affHGvPqcPX:-ODfCGUA7affHGvPqcPY:b3cqjq8) ([raw file](https://github.com/starkware-libs/sequencer/blob/bbef9d130f18211963c2579f6bd77f9c730e0b16/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L102)):*
> ```XML
>     } = broadcasted_messages_receiver.next().await.unwrap().0.unwrap();
> 
>     assert_eq!(incoming_message_id, 0, "Expected message id to be 0");
> ```

Why is this expected? If someone's running the test and gets this panic, it should give him a clue on how to debug.
Same for the messages below.
For example (idk if this is true, it's an example):



_Suggestion:_
```XML
assert_eq!(incoming_message_id, 0, "First message id for each height should be 0");
```
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2580#-ODfDilq89o_liD9qVFy:-ODfDilq89o_liD9qVFz:b-5a8rfp) ([raw file](https://github.com/starkware-libs/sequencer/blob/bbef9d130f18211963c2579f6bd77f9c730e0b16/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L147)):*
> ```XML
>             assert!(
>                 received_tx_hashes.len() == expected_batched_tx_hashes.len(),
>                 "Expected {} transactions, got {}",
> ```

This is a good message because you can understand from this that not all txs went into the block.



_Code quote:_
```XML
"Expected {} transactions, got {}"
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2580)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2580#-ODfCGUA7affHGvPqcPX:-ODfGa6S0baxWP55cEQu:b-q1x8gw) ([raw file](https://github.com/starkware-libs/sequencer/blob/bbef9d130f18211963c2579f6bd77f9c730e0b16/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L102)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why is this expected? If someone's running the test and gets this panic, it should give him a clue on how to debug.
Same for the messages below.
For example (idk if this is true, it's an example):
</blockquote></details>

Yeah, good idea.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2580#-:-ODfNGfACWU8a8JayTSY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Pull request merged**
