### PR TITLE
refactor(mempool): move test utils to a separate file

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1182)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1182)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/test_utils.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1182#-O8Vp8o941X-8EaepFvL:-O8Vp8oA13MTqhtcO6yU:b-yd90oy) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcfdd03e35b3d8defc9dd8bbaf4653dd5ea79d3c/crates/mempool/src/test_utils.rs#L14)):*
> ```XML
> /// Creates an executable invoke transaction with the given field subset (the rest receive default
> /// values).
> #[macro_export]
> ```

This is only visible to crates that depend on mempool in the following way: 
```
starknet_mempool = { workspace = true, features = ["testing"] }
```
Since this file is only built under 



_Code quote:_
```XML
#[macro_export]
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1182)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/test_utils.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1182#-O8Vp8o941X-8EaepFvL:-O8VrasA-ktmnhCpynox:blqvs4p) ([raw file](https://github.com/starkware-libs/sequencer/blob/fcfdd03e35b3d8defc9dd8bbaf4653dd5ea79d3c/crates/mempool/src/test_utils.rs#L14)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This is only visible to crates that depend on mempool in the following way: 
```
starknet_mempool = { workspace = true, features = ["testing"] }
```
Since this file is only built under
</blockquote></details>

"testing" feature.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1182)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/test_utils.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1182#-O8VrgZNB8jIivskk4P-:-O8VrgZNB8jIivskk4P0:brhumzt) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7c2184cb7fa0efe79a0578bdc5403dc1263c1a6/crates/mempool/src/test_utils.rs#L105)):*
> ```XML
> 
> #[track_caller]
> pub fn get_txs_and_assert_expected(
> ```

Same here.



_Code quote:_
```XML
pub
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1182)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1182#-O8VrnMN3sMz066aIoj4:-O8VrnMN3sMz066aIoj5:b-4zzcu7) (no related file):*
Code move only.

___

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1182)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1182#-O8VrnMN3sMz066aIoj4:-O8VvxBt7m7pJ_eIDu_y:bg7igkv) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Code move only.
</blockquote></details>

:lgtm: 

___
___
*[`crates/mempool/src/lib.rs` line 4 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1182#-O8Vviey4gAXCMg8RlSy:-O8Vviey4gAXCMg8RlSz:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/48797e1fc16beae4634824d9b9fdacd6ddfd75ae/crates/mempool/src/lib.rs#L4)):*
> ```XML
> pub mod mempool;
> pub(crate) mod suspended_transaction_pool;
> #[cfg(feature = "testing")]
> ```





_Suggestion:_
```XML
#[cfg(any(feature = "testing", test))]
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1182)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/lib.rs` line 7 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1182#-O8VwZr-8gO0qZF1p-M5:-O8VwZr-8gO0qZF1p-M6:b79mctu) ([raw file](https://github.com/starkware-libs/sequencer/blob/48797e1fc16beae4634824d9b9fdacd6ddfd75ae/crates/mempool/src/lib.rs#L7)):*
> ```XML
> pub mod test_utils;
> pub(crate) mod transaction_pool;
> pub(crate) mod transaction_queue;
> ```

Maybe.
This is to separate between production and testing declerations



_Suggestion:_
```XML
pub mod communication;
pub mod mempool;
pub(crate) mod suspended_transaction_pool;
pub(crate) mod transaction_pool;
pub(crate) mod transaction_queue;

#[cfg(feature = "testing")]
pub mod test_utils;
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1182)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/lib.rs` line 4 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1182#-O8Vviey4gAXCMg8RlSy:-O8Vxwfb93FVg_-JAgPT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/48797e1fc16beae4634824d9b9fdacd6ddfd75ae/crates/mempool/src/lib.rs#L4)):*
> ```XML
> pub mod mempool;
> pub(crate) mod suspended_transaction_pool;
> #[cfg(feature = "testing")]
> ```

Done.
___
*[`crates/mempool/src/lib.rs` line 7 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1182#-O8VwZr-8gO0qZF1p-M5:-O8Vxw_wDzaK9h0fzxbP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/48797e1fc16beae4634824d9b9fdacd6ddfd75ae/crates/mempool/src/lib.rs#L7)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Maybe.
This is to separate between production and testing declerations
</blockquote></details>

Done.

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1182#-:-O8Vyyqz79MClgGRBAZY:bnfp4nl)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

**Review by giladchase — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1182)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1182)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
