### PR TITLE
chore: define creator for executable transaction

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/686)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/686?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#686** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/686?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#668** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/668?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#517](https://github.com/starkware-libs/sequencer/pull/517) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/517?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ArniStarkware** [comment]
*[`crates/starknet_api/src/executable_transaction.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/686#-O5rZreO4JyhKO-GPNQf:-O5rZreO4JyhKO-GPNQg:bq4294p) ([raw file](https://github.com/starkware-libs/sequencer/blob/9eacedef3949f8b2c8d31e1ac48a8cd3c63c8676/crates/starknet_api/src/executable_transaction.rs#L214)):*
> ```XML
>             deploy_account_tx.calculate_transaction_hash(chain_id, &deploy_account_tx.version())?;
>         Ok(Self { tx: deploy_account_tx, tx_hash, contract_address })
>     }
> ```

There are two calculations done by this method:
 - calculation of the contract address.
 - calculation of the transaction hash.


Do they belong inside of a `new` method?



_Code quote:_
```XML
    pub fn new(
        deploy_account_tx: crate::transaction::DeployAccountTransaction,
        chain_id: &ChainId,
    ) -> Result<Self, StarknetApiError> {
        let contract_address = calculate_contract_address(
            deploy_account_tx.contract_address_salt(),
            deploy_account_tx.class_hash(),
            &deploy_account_tx.constructor_calldata(),
            ContractAddress::default(),
        )?;
        let tx_hash =
            deploy_account_tx.calculate_transaction_hash(chain_id, &deploy_account_tx.version())?;
        Ok(Self { tx: deploy_account_tx, tx_hash, contract_address })
    }
```

**Comment by yair-starkware** [comment]
I think the validation code shouldn't be in the constructors:
1. It makes it hard to create testing instances and makes the tests unnecessary longer
2. It is CPU-bound and might cause the executor to get stuck in async code (not sure if this is a real issue)

Actually, I don't think it is correct to call the functions `new` as all the members are public so users don't need the functions to create instances.

A better approach IMO is to rename them to`validate` and change them to a method (work on `&self`).

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/686)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1 and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/686#-O5ray6G48aqo5xiE_mD:-O5rjGGfEPZhAI_aHKIh:b-896fix) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think the validation code shouldn't be in the constructors:
1. It makes it hard to create testing instances and makes the tests unnecessary longer
2. It is CPU-bound and might cause the executor to get stuck in async code (not sure if this is a real issue)

Actually, I don't think it is correct to call the functions `new` as all the members are public so users don't need the functions to create instances.

A better approach IMO is to rename them to`validate` and change them to a method (work on `&self`).
</blockquote></details>

Done.

___

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/686#-:-O5vhr1z7XMghxWBzhnK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/686#-O5vgyilCMMhoWyxGGxG:-O5vgyilCMMhoWyxGGxH:b-y6787y) ([raw file](https://github.com/starkware-libs/sequencer/blob/6530a9df04d6a7ab1f4c96f9e35cbfffe2615f65/crates/starknet_api/src/executable_transaction.rs#L161)):*
> ```XML
>     /// compiled class hash.
>     /// Relevant only for version 3 transactions.
>     pub fn validate_compiled_class_hash(&self) -> Result<(), StarknetApiError> {
> ```

Consider returning bool instead of result



_Code quote:_
```XML
Result<(), StarknetApiError>
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/686)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @yair-starkware)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/686#-O5vgyilCMMhoWyxGGxG:-O5wdcKaAmyDdDPqsFTw:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6530a9df04d6a7ab1f4c96f9e35cbfffe2615f65/crates/starknet_api/src/executable_transaction.rs#L161)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider returning bool instead of result
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/686)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/starknet_api/src/lib.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/686#-O5wtCBjArM3pTIGw1QI:-O5wtCBjArM3pTIGw1QJ:b-11cu7t) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a113d0643384f6e34aa704d6e3921830eaf782d/crates/starknet_api/src/lib.rs#L47)):*
> ```XML
>          {compiled_class_hash:?}"
>     )]
>     CompiledClassHashMismatch {
> ```

I think you can delete this?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/686)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @yair-starkware)

___
*[`crates/starknet_api/src/lib.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/686#-O5wtCBjArM3pTIGw1QI:-O5wu3Tz2VKijjZYqNFB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6a113d0643384f6e34aa704d6e3921830eaf782d/crates/starknet_api/src/lib.rs#L47)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think you can delete this?
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/686)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Sep 8, 4:31 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/686).

**Pull request merged**
