### PR TITLE
chore(tests-integration): dump additional data + use temp dirs

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #1826
- #1825
- #1824
- #1803 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by AlonLStarkWare — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1803)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/tests-integration/src/integration_test_config_utils.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1803#-OAvcX58BC-5YQGxd1yd:-OAvcX5993BjetIGWUtK:b-9d6hwe) ([raw file](https://github.com/starkware-libs/sequencer/blob/74ba4bc5a11c2d7a8898a0424f62511b475c8967/crates/tests-integration/src/integration_test_config_utils.rs#L74)):*
> ```XML
> /// Dumps the input JSON data to a file at the specified path.
> fn dump_json_data(json_data: Value, path: &str) -> Result<()> {
>     let dir = tempdir()?;
> ```

This generates a random path for the temp dir which is really inconvenient for using the configs. From what I can tell tempfile doesn't have a way of specifying the temp_dir name.

**Review by AlonLStarkWare — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1803)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

**Review by AlonLStarkWare — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1803)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by AlonLStarkWare — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1803#-:-OAwCLl24PLT-yxJiASr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#1824](https://github.com/starkware-libs/sequencer/pull/1824)

**Pull request closed without merging**
