### PR TITLE
refactor(papyrus_rpc): get compiled class

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2493?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2493** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2493?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2493?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2438** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2438?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2420** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2420?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2421](https://github.com/starkware-libs/sequencer/pull/2421) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2421?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2467** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2467?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2466** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2466?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2493)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/papyrus_rpc/src/v0_8/api/api_impl.rs` line 1478 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2493#-ODMHwh7CDQWP5OFSbBP:-OD_Hp81BfgiF2Tu53vZ:b-gnqnl0) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb75d10ac779a2db6b737f853dc3384afb48b8db/crates/papyrus_rpc/src/v0_8/api/api_impl.rs#L1478)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why panic here? shouldn't you return an RpcError if the sierra version is unavailable?
</blockquote></details>

Doesn't this error fails the declare transaction in the gateway?
___
*[`crates/papyrus_rpc/src/v0_8/api/api_impl.rs` line 1475 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2493#-OD_HPuIEDiY26T4dYUf:-OD_HPuJ3faprT02rk6k:b3onkf6) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb75d10ac779a2db6b737f853dc3384afb48b8db/crates/papyrus_rpc/src/v0_8/api/api_impl.rs#L1475)):*
> ```XML
>                     .get_class(&class_hash)
>                     .map_err(internal_server_error)?
>                     .ok_or_else(|| ErrorObjectOwned::from(CLASS_HASH_NOT_FOUND))?
> ```

does it make sense that the casm exists in storage and the sierra doesn't? 
I think this scenario indicates a bug.



_Code quote:_
```XML
ErrorObjectOwned::from(CLASS_HASH_NOT_FOUND)
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2493)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yael-Starkware)

___
*[`crates/papyrus_rpc/src/v0_8/api/api_impl.rs` line 1475 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2493#-OD_HPuIEDiY26T4dYUf:-OD_U_xI-ZpC2HvdnlL5:b-u2qx6u) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb75d10ac779a2db6b737f853dc3384afb48b8db/crates/papyrus_rpc/src/v0_8/api/api_impl.rs#L1475)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

does it make sense that the casm exists in storage and the sierra doesn't? 
I think this scenario indicates a bug.
</blockquote></details>

Right, Now the `get_sierra_and_casm` returns an error if  Sierra Xor Casm exist in the server`s storage
___
*[`crates/papyrus_rpc/src/v0_8/api/api_impl.rs` line 1478 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2493#-ODMHwh7CDQWP5OFSbBP:-OD_VmXA6b5R8WCIVw1S:b-a56m62) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb75d10ac779a2db6b737f853dc3384afb48b8db/crates/papyrus_rpc/src/v0_8/api/api_impl.rs#L1478)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Doesn't this error fails the declare transaction in the gateway?
</blockquote></details>

It should fail because it indicates that the Sierra program is invalid. I think that the internal server error is ok since it indicates we have saved an invalid Sierra program on our server.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2493)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2493)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2493)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/papyrus_rpc/src/v0_8/api/api_impl.rs` line 1473 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2493#-ODjd5c63ia3evlbfmBd:-ODjd5c63ia3evlbfmBe:b20u70w) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f6028a205f622eb105974062af238a947fce1ab/crates/papyrus_rpc/src/v0_8/api/api_impl.rs#L1473)):*
> ```XML
>             // Check if both options are `Some`.
>             let (casm, sierra) = option_casm
>                 .zip(option_sierra)
> ```

it's logic like this that makes me think returning `Option<(X, Y)>` is better than returning `(Option<X>, Option<Y>)`. this is not possible, since the storage layer can return one None and one Some?



_Code quote:_
```XML
            let (option_casm, option_sierra) = storage_txn
                .get_casm_and_sierra(&class_hash)
                .map_err(internal_server_error_with_msg)?;

            // Check if both options are `Some`.
            let (casm, sierra) = option_casm
                .zip(option_sierra)
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2493)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/papyrus_rpc/src/v0_8/api/api_impl.rs` line 1473 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2493#-ODjd5c63ia3evlbfmBd:-ODjgVKE3wTXb405ECmP:b9iruxz) ([raw file](https://github.com/starkware-libs/sequencer/blob/106d06c51afe45e1c955e944faee267be6b7285b/crates/papyrus_rpc/src/v0_8/api/api_impl.rs#L1473)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

it's logic like this that makes me think returning `Option<(X, Y)>` is better than returning `(Option<X>, Option<Y>)`. this is not possible, since the storage layer can return one None and one Some?
</blockquote></details>

Yes, the storage layer does not enforce that we have both.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2493)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Comment by AvivYossef-starkware** [comment]
### Merge activity

* **Dec 15, 3:06 PM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2493).

**Pull request merged**
