### PR TITLE
docs(network): add overview doc in lib.rs

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/54)

### CODE REVIEW

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/54)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @eitanm-starkware, and @ShahakShama)

___
*[`crates/papyrus_network/src/lib.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/54#-O2seL_E6CQ0-TpYWiDg:-O2seL_E6CQ0-TpYWiDh:b-3tnopu) ([raw file](https://github.com/starkware-libs/sequencer/blob/cfc0b73931bfcda3153f7fb7c884610782372390/crates/papyrus_network/src/lib.rs#L155)):*
> ```XML
> use validator::Validate;
> 
> pub use crate::network_manager::{NetworkManager, SqmrClientPayload, SqmrServerPayload};
> ```

Why is this part of a documentation commit?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/54)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare, @dan-starkware, and @eitanm-starkware)

___
*[`crates/papyrus_network/src/lib.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/54#-O2seL_E6CQ0-TpYWiDg:-O2ynPgp2sNJTaL_iV7O:bcadgp8) ([raw file](https://github.com/starkware-libs/sequencer/blob/cfc0b73931bfcda3153f7fb7c884610782372390/crates/papyrus_network/src/lib.rs#L155)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

Why is this part of a documentation commit?
</blockquote></details>

It's a pub use. It means that anyone can import these as if they're defined in this file. It's a change that's purely for UX which is what docs is

**Review by AlonLStarkWare — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/54#-:-O3RQjee-jaeF8jZ_OCD:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @eitanm-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/54)* status: all files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware)

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/54)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @dan-starkware and @eitanm-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/54#-O6_NNSX-DN8JvaVYqaB:-O6_NNSX-DN8JvaVYqaC:b-yymcw5) (no related file):*

Reviving this PR

___

**Pull request closed without merging**
