### PR TITLE
refactor(batcher): refactor proposal manager tests

### PR DESCRIPTION
**Pull request by dafnamatsry**

### CODE REVIEW

**Comment by dafnamatsry** [comment]
* **#1683** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1683?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dafnamatsry and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1683#-:-OAX78RX0V9n6YtYHgG3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1683#-:-OAXYOrH2T73W6qD8ezQ:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/batcher/src/proposal_manager_test.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1683#-OAXXDh31ZBBQmo8N06G:-OAXXDh31ZBBQmo8N06H:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e30a1f3d4d699d3258501620f1517fbbf9b1e77/crates/batcher/src/proposal_manager_test.rs#L107)):*
> ```XML
>     proposal_id: ProposalId,
> ) {
>     let (output_sender, _rec) = output_streaming();
> ```





_Suggestion:_
```XML
_receiver
```
___
*[`crates/batcher/src/proposal_manager_test.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1683#-OAXSedHEo9-a6qZBfeC:-OAXSedHEo9-a6qZBfeD:b-5snwk0) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e30a1f3d4d699d3258501620f1517fbbf9b1e77/crates/batcher/src/proposal_manager_test.rs#L225)):*
> ```XML
> #[rstest]
> #[tokio::test]
> async fn test_take_proposal_result_no_active_proposal(mut mock_dependencies: MockDependencies) {
> ```

I see this test did something different before, but now it suites it's name better. Was it a mistake before? Or am I missing something



_Code quote:_
```XML
 test_take_proposal_result_no_active_proposal
```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1683)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager_test.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1683#-OAXSedHEo9-a6qZBfeC:-OAXcS7E62JBHsObYyqc:b-l0z2um) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e30a1f3d4d699d3258501620f1517fbbf9b1e77/crates/batcher/src/proposal_manager_test.rs#L225)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I see this test did something different before, but now it suites it's name better. Was it a mistake before? Or am I missing something
</blockquote></details>

Right, it tested taking 2 different proposal results (not sure why 2), and now it tests only 1 proposal and verifies it is removed after the call to `take..`.
Don't know if it was a mistake before, I mainly wanted to add a test for the "take" aspect of the method.

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1683)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

___
*[`crates/batcher/src/proposal_manager_test.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1683#-OAXSedHEo9-a6qZBfeC:-OAXn8z65YnhT2-2_dp6:brxp9sq) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e30a1f3d4d699d3258501620f1517fbbf9b1e77/crates/batcher/src/proposal_manager_test.rs#L225)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Right, it tested taking 2 different proposal results (not sure why 2), and now it tests only 1 proposal and verifies it is removed after the call to `take..`.
Don't know if it was a mistake before, I mainly wanted to add a test for the "take" aspect of the method.
</blockquote></details>

Sounds good.

**Pull request merged**
