### PR TITLE
chore: rename events table to address_to_tx_index

### PR DESCRIPTION
**Pull request by AlonLStarkWare**

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2894)* status: all files reviewed, 3 unresolved discussions (waiting on @AlonLStarkWare and @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/body/events.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2894#-OEnMtiZ8JdPVmocSZ8t:-OEnMtiZ8JdPVmocSZ8u:bo0okr3) ([raw file](https://github.com/starkware-libs/sequencer/blob/757e449a93e4293a24ae3d4f2a581d5adbfe99e8/crates/papyrus_storage/src/body/events.rs#L145)):*
> ```XML
>     txn: &'txn DbTransaction<'env, RO>,
>     file_handles: &'txn FileHandlers<RO>,
>     // This value is the next entry in the events table to search for relevant events. If it is
> ```

Fix comment
___
*[`crates/papyrus_storage/src/body/events.rs` line 363 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2894#-OEnMjKm0A3FzSzdchB7:-OEnMjKm0A3FzSzdchB8:b-vdoviy) ([raw file](https://github.com/starkware-libs/sequencer/blob/757e449a93e4293a24ae3d4f2a581d5adbfe99e8/crates/papyrus_storage/src/body/events.rs#L363)):*
> ```XML
> 
> /// A cursor of the events table.
> type AddressToTxIndexTableCursor<'txn> =
> ```

Tx -> Transaction
___
*[`crates/papyrus_storage/src/lib.rs` line 531 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2894#-OEnMg_kBNntXjZoadkN:-OEnMg_kBNntXjZoadkO:bhyid9i) ([raw file](https://github.com/starkware-libs/sequencer/blob/757e449a93e4293a24ae3d4f2a581d5adbfe99e8/crates/papyrus_storage/src/lib.rs#L531)):*
> ```XML
>         // TODO(dvir): consider use here also the CommonPrefix table type.
>         deployed_contracts: TableIdentifier<(ContractAddress, BlockNumber), VersionZeroWrapper<ClassHash>, SimpleTable>,
>         address_to_tx_index: TableIdentifier<(ContractAddress, TransactionIndex), NoVersionValueWrapper<NoValue>, CommonPrefix>,
> ```

tx -> transaction

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2894)* status: all files reviewed, 4 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/body/mod.rs` line 483 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2894#-OErk7xw0pAnD6t1DB13:-OErk7xw0pAnD6t1DB14:b-q7vgy4) ([raw file](https://github.com/starkware-libs/sequencer/blob/757e449a93e4293a24ae3d4f2a581d5adbfe99e8/crates/papyrus_storage/src/body/mod.rs#L483)):*
> ```XML
>     tx_output: &TransactionOutput,
>     txn: &DbTransaction<'env, RW>,
>     events_table: &'env AddressToTxIndexTable<'env>,
> ```

events_table -> address_to_transaction_index

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2894#-:-OEwjMO8Dk2tKMNuMaDf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2894)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 531 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2894#-OEnMg_kBNntXjZoadkN:-OEtCTCQDC2gWqj_WpOx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/757e449a93e4293a24ae3d4f2a581d5adbfe99e8/crates/papyrus_storage/src/lib.rs#L531)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

tx -> transaction
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/body/events.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2894#-OEnMtiZ8JdPVmocSZ8t:-OEtCSrSE-SGEL77Yyme:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/757e449a93e4293a24ae3d4f2a581d5adbfe99e8/crates/papyrus_storage/src/body/events.rs#L145)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Fix comment
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/body/events.rs` line 363 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2894#-OEnMjKm0A3FzSzdchB7:-OEtCSTMEwDO3N2fHcdE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/757e449a93e4293a24ae3d4f2a581d5adbfe99e8/crates/papyrus_storage/src/body/events.rs#L363)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Tx -> Transaction
</blockquote></details>

Done.

**Pull request merged**
