### PR TITLE
refactor: merge multiple EntryPointType structs

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1318)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 32 of 34 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1318)* status: 32 of 34 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @noaov1, and @yair-starkware)

___
*[`crates/papyrus_test_utils/src/lib.rs` line 599 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1318#-O93bFO67WYd68x0KuMo:-O93bFO67WYd68x0KuMp:b-231taw) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce5629996f08692ef07b47f65ad8953d4a74058d/crates/papyrus_test_utils/src/lib.rs#L599)):*
> ```XML
>         External = 1,
>         L1Handler = 2,
>     }
> ```

Does this test enum and the real one have the same meaning?  



_Code quote:_
```XML
    pub enum DeprecatedEntryPointType {
        Constructor = 0,
        External = 1,
        L1Handler = 2,
    }
```

**Review by meship-starkware — APPROVED** [review]
> Reviewed 2 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1318)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @noaov1, and @yair-starkware)

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 34 of 34 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1318#-:-O93nd491784xkE41Gso:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1318#-:-O93njRXA4CltZjStkvm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1318)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/papyrus_test_utils/src/lib.rs` line 599 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1318#-O93bFO67WYd68x0KuMo:-O9498xi-AARg1YM0NPJ:b2nhswy) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce5629996f08692ef07b47f65ad8953d4a74058d/crates/papyrus_test_utils/src/lib.rs#L599)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Does this test enum and the real one have the same meaning?
</blockquote></details>

Yes

**Pull request merged**
