### PR TITLE
refactor(batcher): make versioned_constants_overrides field optional …

### PR DESCRIPTION
**Pull request by ayeletstarkware**
…in BlockBuilderConfig

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1414)

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1414)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9EHPMn2I4KqkfPAB-L:-O9EHPMo6slq4aFBv7JW:b8gczjv) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ffc6dc68471fb92b0a2d6e05db5e731fab50794/crates/batcher/src/block_builder.rs#L70)):*
> ```XML
> 
> #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
> pub struct BlockBuilderConfig {
> ```

This is not a papyrus configuration, is it? otherwise, changing the struct should affect the dump. 

It should be a papyrus config as it should be a part of node config. @Yael-Starkware 



_Code quote:_
```XML
pub struct BlockBuilderConfig {
```
___
*[`crates/batcher/src/block_builder.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9EH0uK8YpgAoN-FjNA:-O9EH0uK8YpgAoN-FjNB:b-biqgob) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ffc6dc68471fb92b0a2d6e05db5e731fab50794/crates/batcher/src/block_builder.rs#L234)):*
> ```XML
>                 VersionedConstants::get_versioned_constants(overrides)
>             } else {
>                 VersionedConstants::get_versioned_constants(VersionedConstantsOverrides::default())
> ```

Is this the simplest way to get_versioned_constants without overrides?
Are there other functions in that does this more simply?



_Code quote:_
```XML
VersionedConstants::get_versioned_constants(VersionedConstantsOverrides::default())
```
___
*[`crates/batcher/src/block_builder.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9EGhr1EgtsLPzdf1-o:-O9EGhr1EgtsLPzdf1-p:b-bgbaiy) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ffc6dc68471fb92b0a2d6e05db5e731fab50794/crates/batcher/src/block_builder.rs#L235)):*
> ```XML
>             } else {
>                 VersionedConstants::get_versioned_constants(VersionedConstantsOverrides::default())
>             };
> ```

Can this code be squashed into the function `VersionedConstants::get_versioned_constants`?
Is it complicated?



_Code quote:_
```XML
        let versioned_constants =
            if let Some(overrides) = execution_config.versioned_constants_overrides {
                VersionedConstants::get_versioned_constants(overrides)
            } else {
                VersionedConstants::get_versioned_constants(VersionedConstantsOverrides::default())
            };
```

**Comment by ArniStarkware** [comment]
*[`crates/batcher/src/block_builder.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9EH0uK8YpgAoN-FjNA:-O9EJflG9HPgyxjR2wdk:b-76qzv8) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ffc6dc68471fb92b0a2d6e05db5e731fab50794/crates/batcher/src/block_builder.rs#L234)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Is this the simplest way to get_versioned_constants without overrides?
Are there other functions in that does this more simply?
</blockquote></details>

Wait - is this the intended behavior?

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1414)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @ayeletstarkware)

___
*[`crates/batcher/src/block_builder.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9EHPMn2I4KqkfPAB-L:-O9EKYKV58pla-EH3Ww3:b-l4jprd) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ffc6dc68471fb92b0a2d6e05db5e731fab50794/crates/batcher/src/block_builder.rs#L70)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This is not a papyrus configuration, is it? otherwise, changing the struct should affect the dump. 

It should be a papyrus config as it should be a part of node config. @Yael-Starkware
</blockquote></details>

right.
___
*[`crates/batcher/src/block_builder.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9EKPvQAmlOYOQfBTQ2:-O9EKPvQAmlOYOQfBTQ3:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ffc6dc68471fb92b0a2d6e05db5e731fab50794/crates/batcher/src/block_builder.rs#L91)):*
> ```XML
>             use_kzg_da: true,
>             tx_chunk_size: 100,
>             versioned_constants_overrides: Some(VersionedConstantsOverrides::default()),
> ```





_Suggestion:_
```XML
None
```
___
*[`crates/batcher/src/block_builder.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9EH0uK8YpgAoN-FjNA:-O9EKjSR2-y-4-k1Xby4:bek857o) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ffc6dc68471fb92b0a2d6e05db5e731fab50794/crates/batcher/src/block_builder.rs#L234)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Wait - is this the intended behavior?
</blockquote></details>

Please change the signature of get_versioned_constants the get an Option, and then inside the function decide if needs an override or keep the constants as is.

**Comment by ArniStarkware** [comment]
*[`crates/batcher/src/block_builder.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9EGhr1EgtsLPzdf1-o:-O9EdrFZDbwBOu0EiEYQ:b-ug6auk) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ffc6dc68471fb92b0a2d6e05db5e731fab50794/crates/batcher/src/block_builder.rs#L235)):*
> Please change the signature of get\_versioned\_constants the get an Option, and then inside the function decide if needs an override or keep the constants as is.

This is what I meant.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1414)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @ayeletstarkware)

___
*[`crates/batcher/src/block_builder.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9EGhr1EgtsLPzdf1-o:-O9EqxA68iSCZX7sdi-Z:bgz2bxf) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ffc6dc68471fb92b0a2d6e05db5e731fab50794/crates/batcher/src/block_builder.rs#L235)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

> Please change the signature of get\_versioned\_constants the get an Option, and then inside the function decide if needs an override or keep the constants as is.

This is what I meant.
</blockquote></details>

right, sorry I repeated it :)

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1414)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9EKPvQAmlOYOQfBTQ2:-O9EoCoWAGZNj7XtJMR1:brjenlb) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ffc6dc68471fb92b0a2d6e05db5e731fab50794/crates/batcher/src/block_builder.rs#L91)):*
> ```XML
>             use_kzg_da: true,
>             tx_chunk_size: 100,
>             versioned_constants_overrides: Some(VersionedConstantsOverrides::default()),
> ```

Done. Replaced `VersionedConstantsOverrides`'s custom `Default` with `derive(Default)` as those values aren't used anymore. The derive is needed for `BlockBuilderConfig`'s `dump` function.
___
*[`crates/batcher/src/block_builder.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9EH0uK8YpgAoN-FjNA:-O9EqAzh7iJZVlsBRhw7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ffc6dc68471fb92b0a2d6e05db5e731fab50794/crates/batcher/src/block_builder.rs#L234)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Please change the signature of get_versioned_constants the get an Option, and then inside the function decide if needs an override or keep the constants as is.
</blockquote></details>

Done.
___
*[`crates/batcher/src/block_builder.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9EGhr1EgtsLPzdf1-o:-O9EqC0LDMZPhNKY1YJ-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ffc6dc68471fb92b0a2d6e05db5e731fab50794/crates/batcher/src/block_builder.rs#L235)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

> Please change the signature of get\_versioned\_constants the get an Option, and then inside the function decide if needs an override or keep the constants as is.

This is what I meant.
</blockquote></details>

Done.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1414)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9EGhr1EgtsLPzdf1-o:-O9EwCL230Tqf_tTnJUg:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ffc6dc68471fb92b0a2d6e05db5e731fab50794/crates/batcher/src/block_builder.rs#L235)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1414)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9EGhr1EgtsLPzdf1-o:-O9FjI2I7u7Ry2gkUY0P:b-h20vee) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ffc6dc68471fb92b0a2d6e05db5e731fab50794/crates/batcher/src/block_builder.rs#L235)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I am sorry I was not clearer.
___
*[`crates/blockifier/src/versioned_constants.rs` line 341 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9Fjkww8OjkJZIS_4GL:-O9Fjkww8OjkJZIS_4GM:b3kpx) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b1e72ba16ea2274c9f9ca960908a56aa05c354f/crates/blockifier/src/versioned_constants.rs#L341)):*
> ```XML
>     ) -> Self {
>         Self { validate_max_n_steps, max_recursion_depth, ..Self::latest_constants().clone() }
>     }
> ```





_Suggestion:_
```XML
    // TODO(Ayelet): Share code with get_versioned_constants.
    pub fn latest_constants_with_overrides(
        validate_max_n_steps: u32,
        max_recursion_depth: usize,
    ) -> Self {
        Self { validate_max_n_steps, max_recursion_depth, ..Self::latest_constants().clone() }
    }
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 865 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9FkE2uCFv65w_8-N0E:-O9FkE2v-Z67JB3WuGWi:b-dwx03m) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b1e72ba16ea2274c9f9ca960908a56aa05c354f/crates/blockifier/src/versioned_constants.rs#L865)):*
> ```XML
>     pub validate_max_n_steps: u32,
>     pub max_recursion_depth: usize,
>     pub invoke_tx_max_n_steps: u32,
> ```

Maybe this should be like this?
And should override only if not `None`.
(Connects to my comment on correctness). 
(Maybe my use-case does not exist - but It does connect to the other comment I had about sharing code).



_Suggestion:_
```XML
#[derive(Clone, Debug, Default, Deserialize, PartialEq, Serialize)]
pub struct VersionedConstantsOverrides {
    pub validate_max_n_steps: Option<u32>,
    pub max_recursion_depth: Option<usize>,
    pub invoke_tx_max_n_steps: Option<u32>,
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1414)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 865 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9FkE2uCFv65w_8-N0E:-O9dDVN03mmR-OSMFAnG:b-72r7wy) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b1e72ba16ea2274c9f9ca960908a56aa05c354f/crates/blockifier/src/versioned_constants.rs#L865)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Maybe this should be like this?
And should override only if not `None`.
(Connects to my comment on correctness). 
(Maybe my use-case does not exist - but It does connect to the other comment I had about sharing code).
</blockquote></details>

let's discuss this refactor offline and implement in a different PR. this PR is about making `versioned_constants_overrides` field optional in `BlockBuilderConfig`.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1414)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @Yael-Starkware)

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1414)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 341 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9Fjkww8OjkJZIS_4GL:-O9jMo8f4-wKcP1WynKu:b-mo0b3b) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b1e72ba16ea2274c9f9ca960908a56aa05c354f/crates/blockifier/src/versioned_constants.rs#L341)):*
> ```XML
>     ) -> Self {
>         Self { validate_max_n_steps, max_recursion_depth, ..Self::latest_constants().clone() }
>     }
> ```

will be done in a different PR
___
*[`crates/blockifier/src/versioned_constants.rs` line 865 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9FkE2uCFv65w_8-N0E:-O9jMrPX7hMWZqGof8Wb:b-7n7ote) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b1e72ba16ea2274c9f9ca960908a56aa05c354f/crates/blockifier/src/versioned_constants.rs#L865)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Well, my point is that maybe the original task was not set correctly.
My concern is with the intended behavior in each case - end in previous uses of `VersionedConstantsOverrides`.
</blockquote></details>

will be done in a different PR. added a TODO.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1414)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @Yael-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 832 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9jpA9d5sM3UIcyIIZI:-O9jpA9d5sM3UIcyIIZJ:bgqw3l8) ([raw file](https://github.com/starkware-libs/sequencer/blob/b50728a6bea08abf47d58a1b060de3cd35f9ce23/crates/blockifier/src/versioned_constants.rs#L832)):*
> ```XML
> 
> // TODO(Ayelet): Make fields optional.
> #[derive(Clone, Debug, Default, Deserialize, PartialEq, Serialize)]
> ```

Remove the derived impl of `Default`.
This is for sure affects the behavior. 



_Code quote:_
```XML
 Default,
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 843 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9jpWuB6KWOJAl_lOEX:-O9jpWuB6KWOJAl_lOEY:bzb6emu) ([raw file](https://github.com/starkware-libs/sequencer/blob/6b8ae3a517eb75d1d7f5383670c1ae2111df9560/crates/blockifier/src/versioned_constants.rs#L843)):*
> ```XML
>         }
>     }
> }
> ```

Bring this back for this PR.
Add a todo to delete it once the `Optional-overrides` feature is implemented.

This issue deserves it's owned PR.
Can we delete all calls to `VersionedConstantsOverrides::Default()` - and replace them with `None` - which stands for - do not override anything. Ask the original writer of the code what was the intention for each `Default`. 



_Code quote:_
```XML
impl Default for VersionedConstantsOverrides {
    // TODO: update the default values once the actual values are known.
    fn default() -> Self {
        Self {
            validate_max_n_steps: 1000000,
            max_recursion_depth: 50,
            invoke_tx_max_n_steps: 10000000,
        }
    }
}
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2, 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1414)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware and @ayeletstarkware)

___
*[`config/mempool/default_config.json` line 123 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9kBqAB-UgudJeIF2uK:-O9kBqAB-UgudJeIF2uL:bvd7blr) ([raw file](https://github.com/starkware-libs/sequencer/blob/b50728a6bea08abf47d58a1b060de3cd35f9ce23/config/mempool/default_config.json#L123)):*
> ```JSON
>   },
>   "batcher_config.block_builder_config.versioned_constants_overrides.#is_none": {
>     "description": "Flag for an optional field.",
> ```

Can you change this description?



_Suggestion:_
```JSON
Optional field for overriding some of the version constants values
```
___
*[`config/mempool/default_config.json` line 124 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9kCNFs65ovDTVVZ-PP:-O9kCNFs65ovDTVVZ-PQ:b-17bkjc) ([raw file](https://github.com/starkware-libs/sequencer/blob/b50728a6bea08abf47d58a1b060de3cd35f9ce23/config/mempool/default_config.json#L124)):*
> ```JSON
>   "batcher_config.block_builder_config.versioned_constants_overrides.#is_none": {
>     "description": "Flag for an optional field.",
>     "privacy": "TemporaryValue",
> ```

what does this mean?



_Code quote:_
```JSON
TemporaryValue
```
___
*[`crates/batcher/src/block_builder.rs` line 139 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9kBLcEEV7ZUQqTpzvk:-O9kBLcEEV7ZUQqTpzvl:b-75haxk) ([raw file](https://github.com/starkware-libs/sequencer/blob/b50728a6bea08abf47d58a1b060de3cd35f9ce23/crates/batcher/src/block_builder.rs#L139)):*
> ```XML
>             ParamPrivacyInput::Public,
>         )]));
>         dump.append(&mut ser_optional_sub_config(
> ```

I assume this is the way to handle optional fields dumping
just to know for the future, where did you find this information?



_Code quote:_
```XML
ser_optional_sub_config
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 843 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9jpWuB6KWOJAl_lOEX:-O9nmeHT1iB1xDZAA1-5:bpv1z3c) ([raw file](https://github.com/starkware-libs/sequencer/blob/6b8ae3a517eb75d1d7f5383670c1ae2111df9560/crates/blockifier/src/versioned_constants.rs#L843)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Bring this back for this PR.
Add a todo to delete it once the `Optional-overrides` feature is implemented.

This issue deserves it's owned PR.
Can we delete all calls to `VersionedConstantsOverrides::Default()` - and replace them with `None` - which stands for - do not override anything. Ask the original writer of the code what was the intention for each `Default`.
</blockquote></details>

It will be irrelevant after #1496 is merged.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1414)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @Yael-Starkware)

___
*[`config/mempool/default_config.json` line 125 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-OADLfMr4edvJac0bma-:-OADLfMr4edvJac0bma0:b-cy8na7) ([raw file](https://github.com/starkware-libs/sequencer/blob/b50728a6bea08abf47d58a1b060de3cd35f9ce23/config/mempool/default_config.json#L125)):*
> ```JSON
>     "description": "Flag for an optional field.",
>     "privacy": "TemporaryValue",
>     "value": true
> ```

@ayeletstarkware, and I had a long discussion about this little flag.
We like that it is here, and this value is set to `true`. This implies that the loaded default config will have *no overrides*

Can you test it manually? Can 



_Code quote:_
```JSON
    "value": true
```
___
*[`crates/batcher/src/block_builder.rs` line 139 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9kBLcEEV7ZUQqTpzvk:-OADMOP_EdgJRPKY6WlS:bkd8faw) ([raw file](https://github.com/starkware-libs/sequencer/blob/b50728a6bea08abf47d58a1b060de3cd35f9ce23/crates/batcher/src/block_builder.rs#L139)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I assume this is the way to handle optional fields dumping
just to know for the future, where did you find this information?
</blockquote></details>

All of these functions appear in `papyrus_config::dumping::{..}`.
Before future use - read the docstring of these functions. The docstring tells us about the `#is_none` flag we should read more about.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1414)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware)

___
*[`config/mempool/default_config.json` line 123 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9kBqAB-UgudJeIF2uK:-OAIDb__5-I5xYBgujk_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b50728a6bea08abf47d58a1b060de3cd35f9ce23/config/mempool/default_config.json#L123)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Can you change this description?
</blockquote></details>

Done.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1414)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware)

___
*[`config/mempool/default_config.json` line 123 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9kBqAB-UgudJeIF2uK:-OAILzDJBBPs_lI_yVTW:b61xjuw) ([raw file](https://github.com/starkware-libs/sequencer/blob/b50728a6bea08abf47d58a1b060de3cd35f9ce23/config/mempool/default_config.json#L123)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

fails tests. reverted.

**Comment by ArniStarkware** [comment]
*[`config/mempool/default_config.json` line 124 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-O9kCNFs65ovDTVVZ-PP:-OAIMpCE4geGbb-di_F7:bl4u2l2) ([raw file](https://github.com/starkware-libs/sequencer/blob/b50728a6bea08abf47d58a1b060de3cd35f9ce23/config/mempool/default_config.json#L124)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

what does this mean?
</blockquote></details>

This is the file structure generated by `SerializeConfig` of the sequencer node.

**Comment by ArniStarkware** [comment]
*[`crates/batcher/src/block_builder.rs` line 279 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-OAINKq93IiWP1FwnJct:-OAINKq93IiWP1FwnJcu:bvwt1q6) ([raw file](https://github.com/starkware-libs/sequencer/blob/55bde12c6d71ff679b7e2d2aaf9f45cb83d32934/crates/batcher/src/block_builder.rs#L279)):*
> ```XML
>             } else {
>                 VersionedConstants::latest_constants().clone()
>             };
> ```

Push this `if let` into a "class method" of `VersionedConstants`.



_Code quote:_
```XML
            if let Some(overrides) = block_builder_config.versioned_constants_overrides {
                VersionedConstants::get_versioned_constants(overrides)
            } else {
                VersionedConstants::latest_constants().clone()
            };
```

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1414)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 279 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-OAINKq93IiWP1FwnJct:-OAIOEVT0HFZMXf-LZhH:b-lno3le) ([raw file](https://github.com/starkware-libs/sequencer/blob/55bde12c6d71ff679b7e2d2aaf9f45cb83d32934/crates/batcher/src/block_builder.rs#L279)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Push this `if let` into a "class method" of `VersionedConstants`.
</blockquote></details>

not into `get_versioned_constants` but another function.

**Review by ArniStarkware — COMMENTED** [review]
This PR is replaced by: #1832.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1414#-:-OAwIOI54KDIjo8HQb2D:b2y79ct)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @Yael-Starkware)

**Pull request closed without merging**
