### PR TITLE
feat: post compilation size limit validation

### PR DESCRIPTION
**Pull request by ArniStarkware**
This PR is imported into this repo. The original PR: https://github.com/starkware-libs/mempool/pull/298.

Note the stack of PRs has a different order in this repo.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/284)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/284?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#284** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/284?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#283** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/283?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#250** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/250?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/284)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O3bBz3vAtU86prjCmM6:-O3bBz3vAtU86prjCmM7:b-2tewce) ([raw file](https://github.com/starkware-libs/sequencer/blob/78f25dbb25fb9cdff7d26ae6ca1ed61106202a5f/crates/gateway/src/compilation.rs#L32)):*
> ```XML
>             sierra_to_casm_compiler: SierraToCasmCompiler {
>                 config: config.sierra_to_casm_compiler_config,
>             },
> ```

why the duplication of sierra_to_casm_compiler_config?



_Code quote:_
```XML
            config,
            sierra_to_casm_compiler: SierraToCasmCompiler {
                config: config.sierra_to_casm_compiler_config,
            },
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/284)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/gateway/src/config.rs` line 242 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O3bGAxk4rQ_sKkEcXVz:-O3bGAxl-U8C35I-HhzF:b8f0j96) ([raw file](https://github.com/starkware-libs/sequencer/blob/78f25dbb25fb9cdff7d26ae6ca1ed61106202a5f/crates/gateway/src/config.rs#L242)):*
> ```XML
> pub struct GatewayCompilerConfig {
>     pub sierra_to_casm_compiler_config: SierraToCasmCompilationConfig,
>     pub max_raw_casm_class_size: usize,
> ```

the word raw confuses me, I am think about eating steak.



_Code quote:_
```XML
raw
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/284)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/gateway/src/config.rs` line 242 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O3bGAxk4rQ_sKkEcXVz:-O3bGKq1DqKsO3btcHVZ:bsu59bp) ([raw file](https://github.com/starkware-libs/sequencer/blob/78f25dbb25fb9cdff7d26ae6ca1ed61106202a5f/crates/gateway/src/config.rs#L242)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

the word raw confuses me, I am think about eating steak.
</blockquote></details>

*thinking

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/284)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O3bBz3vAtU86prjCmM6:-O3bkh_p-4dBxh50K_nB:b2ji5cw) ([raw file](https://github.com/starkware-libs/sequencer/blob/7da10618319a29406bd49f6026b7cd318ea49343/crates/gateway/src/compilation.rs#L32)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why the duplication of sierra_to_casm_compiler_config?
</blockquote></details>

Done.
Now there is no duplication. - The price is the multiplicity of objects.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/284)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O3bBz3vAtU86prjCmM6:-O3bkxPm8wbrGa396kBc:b-98qs5j) ([raw file](https://github.com/starkware-libs/sequencer/blob/7da10618319a29406bd49f6026b7cd318ea49343/crates/gateway/src/compilation.rs#L32)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
Now there is no duplication. - The price is the multiplicity of objects.
</blockquote></details>

The price is that there are more objects now.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/284)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/config.rs` line 242 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O3bGAxk4rQ_sKkEcXVz:-O3gjOO_ElGi-rB5cHDH:b-bxyzaa) ([raw file](https://github.com/starkware-libs/sequencer/blob/7da10618319a29406bd49f6026b7cd318ea49343/crates/gateway/src/config.rs#L242)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

*thinking
</blockquote></details>

Addressed in #354 (And #355).

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, 2 of 3 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/284)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 27 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O3lVYFtC2QYlW9ZwF0q:-O3lVYFtC2QYlW9ZwF0r:bw6n3ou) ([raw file](https://github.com/starkware-libs/sequencer/blob/367216ad4766202af98a9817c455ec16d9d54b9b/crates/gateway/src/compilation.rs#L27)):*
> ```XML
> 
> impl GatewayCompiler {
>     pub fn new(config: GatewayCompilerConfig) -> Self {
> ```

In the following PR: https://reviewable.io/reviews/starkware-libs/sequencer/319#- you define different initialisation methods. Are you planning to delete this `new` later?



_Code quote:_
```XML
pub fn new(config: GatewayCompilerConfig)
```
___
*[`crates/gateway/src/config.rs` line 230 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O3lUo8WAlFA5qf6tbDV:-O3lUo8WAlFA5qf6tbDW:b-t5nsxk) ([raw file](https://github.com/starkware-libs/sequencer/blob/367216ad4766202af98a9817c455ec16d9d54b9b/crates/gateway/src/config.rs#L230)):*
> ```XML
> #[derive(Clone, Copy, Debug, Default, Serialize, Deserialize, Validate, PartialEq)]
> pub struct GatewayCompilerConfig {
>     pub sierra_to_casm_compiler_config: SierraToCasmCompilationConfig,
> ```

Maybe better to put it outside of `GatewayCompilerConfig`?
The `SierraToCasmCompilation` is given to the  `GatewayCompiler` with a dependency injection (https://reviewable.io/reviews/starkware-libs/sequencer/319#-), so I think it makes sense that it would be outside.



_Code quote:_
```XML
pub sierra_to_casm_compiler_config: SierraToCasmCompilationConfig,
```
___
*[`crates/gateway/src/config.rs` line 251 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O3lDWHeEomU8FUPOhvH:-O3lDWHeEomU8FUPOhvI:b-ran97x) ([raw file](https://github.com/starkware-libs/sequencer/blob/367216ad4766202af98a9817c455ec16d9d54b9b/crates/gateway/src/config.rs#L251)):*
> ```XML
> /// The configuration for the post compilation process in the gateway compiler.
> #[derive(Clone, Copy, Debug, Serialize, Deserialize, Validate, PartialEq)]
> pub struct PostCompilationConfig {
> ```

Why do we need this extra level of config, and not just define `max_raw_casm_class_size` to the `GatewayCompilerConfig`?



_Code quote:_
```XML
PostCompilationConfig 
```

**Comment by ArniStarkware** [comment]
This PR will be restacked over #357.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/284)* status: 1 of 9 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 27 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O3lVYFtC2QYlW9ZwF0q:-O3lnk5J6lKK8RDsb7N0:b66eqru) ([raw file](https://github.com/starkware-libs/sequencer/blob/367216ad4766202af98a9817c455ec16d9d54b9b/crates/gateway/src/compilation.rs#L27)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

In the following PR: https://reviewable.io/reviews/starkware-libs/sequencer/319#- you define different initialisation methods. Are you planning to delete this `new` later?
</blockquote></details>

Deleted. Replaced with the existing `new_cario_lang_compiler` function.

Rebases made this comment had to follow.
___
*[`crates/gateway/src/config.rs` line 230 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O3lUo8WAlFA5qf6tbDV:-O3m9lDdC6vj8Cahrnd6:b-fxoelf) ([raw file](https://github.com/starkware-libs/sequencer/blob/367216ad4766202af98a9817c455ec16d9d54b9b/crates/gateway/src/config.rs#L230)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Maybe better to put it outside of `GatewayCompilerConfig`?
The `SierraToCasmCompilation` is given to the  `GatewayCompiler` with a dependency injection (https://reviewable.io/reviews/starkware-libs/sequencer/319#-), so I think it makes sense that it would be outside.
</blockquote></details>

Done. See previous PR in the stack. #374.

Now: `GatewayCompilerConfig` sits directly in the mempool node config.
___
*[`crates/gateway/src/config.rs` line 251 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O3lDWHeEomU8FUPOhvH:-O3mB1_540nh1F0kgAAI:b5cku4r) ([raw file](https://github.com/starkware-libs/sequencer/blob/367216ad4766202af98a9817c455ec16d9d54b9b/crates/gateway/src/config.rs#L251)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why do we need this extra level of config, and not just define `max_raw_casm_class_size` to the `GatewayCompilerConfig`?
</blockquote></details>

I think it's cleaner that there is a level with all sub-configs. But it is a taste thing.
I plan to also have other similar numbers in this `PostCompilerConfig` level - like the size of the casm-bytecode.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/284)* status: 6 of 11 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 22 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O44NV5R5AN7O1uqq9bT:-O44NV5R5AN7O1uqq9bU:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/eeb7ac1412e800d6bc8b39b19cb2162ec3214c7b/crates/gateway/src/compilation.rs#L22)):*
> ```XML
> #[derive(Clone)]
> pub struct GatewayCompiler {
>     config: PostCompilationConfig,
> ```





_Suggestion:_
```XML
config: GatewayCompilerConfig,
```
___
*[`crates/gateway/src/compilation.rs` line 27 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O44NhjJ5XldOdE40dJU:-O44NhjJ5XldOdE40dJV:brn4e1a) ([raw file](https://github.com/starkware-libs/sequencer/blob/eeb7ac1412e800d6bc8b39b19cb2162ec3214c7b/crates/gateway/src/compilation.rs#L27)):*
> ```XML
> 
> impl GatewayCompiler {
>     pub fn new_cairo_lang_compiler(config: GatewayCompilerConfig) -> Self {
> ```

Once you remove the `SierraToCasmCompilationConfig` from the `GatewayConfig` you can pass it here as an argument.
___
*[`crates/gateway/src/config.rs` line 242 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O3bGAxk4rQ_sKkEcXVz:-O44OPVX14uyZ_hzeqhY:b-iiiueu) ([raw file](https://github.com/starkware-libs/sequencer/blob/7da10618319a29406bd49f6026b7cd318ea49343/crates/gateway/src/config.rs#L242)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Addressed in #354 (And #355).
</blockquote></details>

Not critical but: for the future, I prefer you address this kind of comments in the same PR.
This field was introduced in this PR, so merging it and immediately renaming it in a following PR feels like extra work that could have been avoided.
___
*[`crates/gateway/src/config.rs` line 230 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O3lUo8WAlFA5qf6tbDV:-O44IJA19Nt9_TOaVMoM:b-4ur0p6) ([raw file](https://github.com/starkware-libs/sequencer/blob/367216ad4766202af98a9817c455ec16d9d54b9b/crates/gateway/src/config.rs#L230)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done. See previous PR in the stack. #374.

Now: `GatewayCompilerConfig` sits directly in the mempool node config.
</blockquote></details>

With the previous PR the `SierraToCasmCompilationConfig` sits directly in the mempool node config.  So you can remove it from here no?
___
*[`crates/gateway/src/config.rs` line 251 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O3lDWHeEomU8FUPOhvH:-O44O8eV5lLpJgiQHBbD:b2nhll9) ([raw file](https://github.com/starkware-libs/sequencer/blob/367216ad4766202af98a9817c455ec16d9d54b9b/crates/gateway/src/config.rs#L251)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I think it's cleaner that there is a level with all sub-configs. But it is a taste thing.
I plan to also have other similar numbers in this `PostCompilerConfig` level - like the size of the casm-bytecode.
</blockquote></details>

Ok.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/284)* status: 5 of 11 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 22 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O44NV5R5AN7O1uqq9bT:-O44WjlV4VqRfiRYOz8l:b-qr9q5g) ([raw file](https://github.com/starkware-libs/sequencer/blob/eeb7ac1412e800d6bc8b39b19cb2162ec3214c7b/crates/gateway/src/compilation.rs#L22)):*
> ```XML
> #[derive(Clone)]
> pub struct GatewayCompiler {
>     config: PostCompilationConfig,
> ```

The struct called `GatewayCompilerConfig` also holds the config of the `SierraToCasmCompiler.` There will be duplication - The `GatewayCompiler` will have access to unused info - which is used by the `SierraToCasmCompiler`.

Are you sure?
___
*[`crates/gateway/src/config.rs` line 230 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O3lUo8WAlFA5qf6tbDV:-O44WMkn7GH5rjchyoEc:b-h6rhgs) ([raw file](https://github.com/starkware-libs/sequencer/blob/367216ad4766202af98a9817c455ec16d9d54b9b/crates/gateway/src/config.rs#L230)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

With the previous PR the `SierraToCasmCompilationConfig` sits directly in the mempool node config.  So you can remove it from here no?
</blockquote></details>

Got it.
Do we want to do something similar with the `RpcStateReaderConfig`.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/284)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 22 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/284#-O44NV5R5AN7O1uqq9bT:-O4ASKbL9sao2928jNnt:bxzob3f) ([raw file](https://github.com/starkware-libs/sequencer/blob/eeb7ac1412e800d6bc8b39b19cb2162ec3214c7b/crates/gateway/src/compilation.rs#L22)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The struct called `GatewayCompilerConfig` also holds the config of the `SierraToCasmCompiler.` There will be duplication - The `GatewayCompiler` will have access to unused info - which is used by the `SierraToCasmCompiler`.

Are you sure?
</blockquote></details>

I think `GatewayCompilerConfig` shouldn't hold the `SierraToCasmCompilerConfig`.

**Comment by ArniStarkware** [comment]
A lot of requests regarding this PR. Please Do not review it until I re-publish it.

**Pull request closed without merging**
