### PR TITLE
chore: fix native blockifier build

### PR DESCRIPTION
**Pull request by alon-dotan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/215)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/215)* status: all files reviewed, 4 unresolved discussions (waiting on @alon-dotan-starkware)

___
*[`.github/workflows/blockifier_ci.yml` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/215#-O36voaWDrrIGXMTJrji:-O36voaWDrrIGXMTJrjj:b-8j23pg) ([raw file](https://github.com/starkware-libs/sequencer/blob/2c89c404c8ef7641f54ea0911cc7f87c18a0f579/.github/workflows/blockifier_ci.yml#L25)):*
> ```YAML
>     paths:
>       - 'crates/blockifier/**'
>       - 'crates/native_blockifier/**'
> ```

either revert this or also make this change above for consistency.
note that I have [this PR](https://reviewable.io/reviews/starkware-libs/sequencer/76) open to fix more triggering files



_Code quote:_
```YAML
- 'crates/native_blockifier/**'
```
___
*[`scripts/build_native_blockifier.sh` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/215#-O36wAatDmju1HzRtfCh:-O36wAatDmju1HzRtfCi:b-hmzsg1) ([raw file](https://github.com/starkware-libs/sequencer/blob/2c89c404c8ef7641f54ea0911cc7f87c18a0f579/scripts/build_native_blockifier.sh#L12)):*
> ```Shell
> pypy3.9 -m venv venv
> source venv/bin/activate
> cargo build --release -p native_blockifier --features "testing" || clean
> ```

does this command see the `config.toml`?
don't you need to invoke cargo in the crates/native_blockifier directory?



_Code quote:_
```Shell
cargo build --release -p native_blockifier --features "testing"
```
___
*[`scripts/build_native_blockifier.sh` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/215#-O36w07y7KSDF1wvR38U:-O36w07y7KSDF1wvR38V:bnt042l) ([raw file](https://github.com/starkware-libs/sequencer/blob/2c89c404c8ef7641f54ea0911cc7f87c18a0f579/scripts/build_native_blockifier.sh#L13)):*
> ```Shell
> source venv/bin/activate
> cargo build --release -p native_blockifier --features "testing" || clean
> clean
> ```

why is the `|| clean` needed if you clean after, regardless of return status?



_Suggestion:_
```Shell
cargo build --release -p native_blockifier --features "testing"
clean
```
___
*[`build_native_blockifier_in_docker.sh` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/215#-O36vi_S7apzk_j2_SZT:-O36vi_TCIqX_S0gHC7t:b-4jrng8) ([raw file](https://github.com/starkware-libs/sequencer/blob/2c89c404c8ef7641f54ea0911cc7f87c18a0f579/build_native_blockifier_in_docker.sh#L0)):*
how does this relate to [this move](https://reviewable.io/reviews/starkware-libs/sequencer/214)?
@liorgold2

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/215)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`.github/workflows/blockifier_ci.yml` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/215#-O36voaWDrrIGXMTJrji:-O36ygHR5RbBLLUxpCvE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2c89c404c8ef7641f54ea0911cc7f87c18a0f579/.github/workflows/blockifier_ci.yml#L25)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

either revert this or also make this change above for consistency.
note that I have [this PR](https://reviewable.io/reviews/starkware-libs/sequencer/76) open to fix more triggering files
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/215)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware)

___
*[`scripts/build_native_blockifier.sh` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/215#-O37XgmA3U4zJYS4dGBN:-O37XgmA3U4zJYS4dGBO:b-bfovam) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1ca7f9738113337a1faeddb2d6cbeb9cbdd095e/scripts/build_native_blockifier.sh#L16)):*
> ```Shell
>     pypy3.9 -m venv venv
>     source venv/bin/activate
>     cargo build --release -p native_blockifier --features "testing" | clean
> ```

need double pipe, no?



_Suggestion:_
```Shell
"testing" || clean
```

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/215)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`scripts/build_native_blockifier.sh` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/215#-O37XgmA3U4zJYS4dGBN:-O37gX402jV_CwI_NPEH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a1ca7f9738113337a1faeddb2d6cbeb9cbdd095e/scripts/build_native_blockifier.sh#L16)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

need double pipe, no?
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/215#-:-O38-1x4E0M60DkmSFpH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Pull request merged**
