### PR TITLE
build: add batcher_types crate

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #204
- #201
- #199 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/199)

### CODE REVIEW

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/199)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/batcher_types/Cargo.toml` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/199#-O3Bi8d18b8Yd2WhlaHO:-O3Bi8d2C_R0c6-G6eWE:by36l0i) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3a7d8f55029b2ba4b5dddb3fa57861a617e2d92/crates/batcher_types/Cargo.toml#L3)):*
> ```TOML
> [package]
> name = "starknet_batcher_types"
> version.workspace = true
> ```

Version should be in the crate level (since monorepo).



_Code quote:_
```TOML
version.workspace = true
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/199)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

___
*[`crates/batcher_types/Cargo.toml` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/199#-O3Bi8d18b8Yd2WhlaHO:-O3Bj0gH6y20shlleHOQ:b-5tgb6z) ([raw file](https://github.com/starkware-libs/sequencer/blob/f3a7d8f55029b2ba4b5dddb3fa57861a617e2d92/crates/batcher_types/Cargo.toml#L3)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Version should be in the crate level (since monorepo).
</blockquote></details>

Done: Changed to mimick `crates/batcher/Cargo.toml`.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/199)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`Cargo.toml` line 6 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/199#-O3Bm7DLDjisfsiMu7Go:-O3Bm7DM02CopqDROdUn:bqzm0l7) ([raw file](https://github.com/starkware-libs/sequencer/blob/84bf7325718990a7ce7486f343509d02eadddd5a/Cargo.toml#L6)):*
> ```TOML
> resolver = "2"
> 
> members = [
> ```

Something off happened here...

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/199)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

___
*[`Cargo.toml` line 6 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/199#-O3Bm7DLDjisfsiMu7Go:-O3Bw9OB1ibP0nGDtK6E:b-7jkgud) ([raw file](https://github.com/starkware-libs/sequencer/blob/84bf7325718990a7ce7486f343509d02eadddd5a/Cargo.toml#L6)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Something off happened here...
</blockquote></details>

Formatter issue :confused: Should be fixed now

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/199#-:-O3SDIoR8R09bjFZyNXO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/199)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
