### PR TITLE
chore(mempool): add create resource bounds for l2 gas price function

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1291)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1291)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1291#-O8q8aOo5KHDhhk2Q9Yo:-O8q8aOo5KHDhhk2Q9Yp:blmh85r) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb48bdbfbf745fe0257c3a41eeab548f2dba5958/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L138)):*
> ```XML
> }
> 
> pub fn create_resource_bounds_with_l2_max_price_per_unit(
> ```

Where will you use this function?



_Code quote:_
```XML
create_resource_bounds_with_l2_max_price_per_unit
```

**Review by MohammadNassar1 — COMMENTED** [review]
This method will be used in mempool tests. In tests involving two queues, transactions need to be created with different gas prices.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1291#-:-O8qBihcBV9Jnq4L4NG-:b-cxhzk6)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1291#-O8q8aOo5KHDhhk2Q9Yo:-O8qFYH4CSnEx7Nkamw7:b-cxhzk6) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb48bdbfbf745fe0257c3a41eeab548f2dba5958/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L138)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Where will you use this function?
</blockquote></details>

This method will be used in mempool tests. In tests involving two queues, transactions need to be created with different gas prices.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1291)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1291#-O8qI8ko40y3Q-VlK8Pu:-O8qI8ko40y3Q-VlK8Pv:b74ryhr) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb48bdbfbf745fe0257c3a41eeab548f2dba5958/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L146)):*
> ```XML
>         l2_gas: ResourceBounds {
>             max_price_per_unit: GasPrice(l2_max_price_per_unit),
>             ..Default::default()
> ```

The queues are not affected by the `max_amount` field, correct?



_Code quote:_
```XML
..Default::default()
```

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1291#-:-O8qMNa4Cg2xpxYyLZhC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1291)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1291#-O8qWFm36O88jCoZh07V:-O8qWFm36O88jCoZh07W:bwmzk8v) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae0c728134eb099ed42d768389933812d60d6615/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L136)):*
> ```XML
>         },
>     })
> }
> ```

I'm doing something similar. Are you sure the rest should be default and not valid?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1291)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1291#-O8qWFm36O88jCoZh07V:-O8qWoLY8ypfMBG9iQlf:bykqik1) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae0c728134eb099ed42d768389933812d60d6615/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L136)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'm doing something similar. Are you sure the rest should be default and not valid?
</blockquote></details>

Good question.

AFAIK, currently, only `l2_gas_price_per_unit` affects the mempool, so the rest of the parameters can be set to their defaults.

I’m planning to use this util in the two queue tests where the other parameters are not used.

See example of such usage: https://reviewable.io/reviews/starkware-libs/sequencer/1295 

Can you tell me why do you need similar util?

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1291)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1291#-O8qWFm36O88jCoZh07V:-O8qdGRC6S1GTpagdKXO:b-ce8dij) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae0c728134eb099ed42d768389933812d60d6615/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L136)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Good question.

AFAIK, currently, only `l2_gas_price_per_unit` affects the mempool, so the rest of the parameters can be set to their defaults.

I’m planning to use this util in the two queue tests where the other parameters are not used.

See example of such usage: https://reviewable.io/reviews/starkware-libs/sequencer/1295 

Can you tell me why do you need similar util?
</blockquote></details>

I'm changing the `[add_]tx[_input]` macros to accept `max_l2_gas_price` instead of `resource_bounds`; which as you said - only this field interests the mempool.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1291)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1291#-O8qWFm36O88jCoZh07V:-O8qeGBV9xyW8XNkycaC:b-km2jh9) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae0c728134eb099ed42d768389933812d60d6615/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L136)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'm changing the `[add_]tx[_input]` macros to accept `max_l2_gas_price` instead of `resource_bounds`; which as you said - only this field interests the mempool.
</blockquote></details>

I see.
So you will implement this function as part of the `add_tx_input`, right?

Then, shall I close this PR?

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1291)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 136 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1291#-O8qWFm36O88jCoZh07V:-O8qh3rxBUP2mtGF9y2f:b-yogedn) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae0c728134eb099ed42d768389933812d60d6615/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L136)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I see.
So you will implement this function as part of the `add_tx_input`, right?

Then, shall I close this PR?
</blockquote></details>

I'll ask for your review, and you'll decide.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1291)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1291#-O8qkZWW9ux7XqxumQHt:-O8qkZWW9ux7XqxumQHu:b5lex2m) (no related file):*
@ayeletstarkware, looking at the conversation in GH: I think the usage should have been explained better before approving. 

___

**Comment by MohammadNassar1** [comment]
Closing the PR as Elin implemented a similar function in a separate PR.

**Pull request closed without merging**
