### PR TITLE
chore(gateway,batcher): make gw and batcher use same values for execution

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1954)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @Itay-Tsabary-Starkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/sequencer_node/Cargo.toml` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1954#-OBV0vA6Ei6EdNxbpnfM:-OBV0vA6Ei6EdNxbpnfN:bh3nisz) ([raw file](https://github.com/starkware-libs/sequencer/blob/89d4169bcea17cee24161532e3d88668cc7ec67f/crates/sequencer_node/Cargo.toml#L16)):*
> ```TOML
> [dependencies]
> anyhow.workspace = true
> blockifier.workspace = true
> ```

Maybe it's better to move the versioned constants to a different crate that both the blockifier and the node depend on.

**Comment by yair-starkware** [comment]
*[`crates/sequencer_node/Cargo.toml` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1954#-OBV0vA6Ei6EdNxbpnfM:-OBV584pC4Y3J2MmPBxG:b-svcwoe) ([raw file](https://github.com/starkware-libs/sequencer/blob/89d4169bcea17cee24161532e3d88668cc7ec67f/crates/sequencer_node/Cargo.toml#L16)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Maybe it's better to move the versioned constants to a different crate that both the blockifier and the node depend on.
</blockquote></details>

I can't think of anything that makes sense.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1954)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @Itay-Tsabary-Starkware, and @Yael-Starkware)

___
*[`crates/sequencer_node/Cargo.toml` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1954#-OBV0vA6Ei6EdNxbpnfM:-OBVACZIDZh-X-_zu2Zo:b2x1v7g) ([raw file](https://github.com/starkware-libs/sequencer/blob/89d4169bcea17cee24161532e3d88668cc7ec67f/crates/sequencer_node/Cargo.toml#L16)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I can't think of anything that makes sense.
</blockquote></details>

We can also re-export from the batcher. @Itay-Tsabary-Starkware WDYT?

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1954)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5, @ArniStarkware, @dan-starkware, and @Yael-Starkware)

___
*[`crates/sequencer_node/Cargo.toml` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1954#-OBV0vA6Ei6EdNxbpnfM:-OBVsW70DTtjs33uQ9a9:bhcj59g) ([raw file](https://github.com/starkware-libs/sequencer/blob/89d4169bcea17cee24161532e3d88668cc7ec67f/crates/sequencer_node/Cargo.toml#L16)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

We can also re-export from the batcher. @Itay-Tsabary-Starkware WDYT?
</blockquote></details>

I'd rather avoid directly depending on the blockifier.
@dan-starkware iirc you had a similar issue, what did you end up doing?

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1954)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dan-starkware, and @Yael-Starkware)

___
*[`crates/sequencer_node/Cargo.toml` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1954#-OBV0vA6Ei6EdNxbpnfM:-OBZwdlu9cKyMwFmPvGr:bteb0ub) ([raw file](https://github.com/starkware-libs/sequencer/blob/89d4169bcea17cee24161532e3d88668cc7ec67f/crates/sequencer_node/Cargo.toml#L16)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I'd rather avoid directly depending on the blockifier.
@dan-starkware iirc you had a similar issue, what did you end up doing?
</blockquote></details>

Let's re-export from the batcher then.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1954)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/starknet_sequencer_node/src/config/node_config.rs` line 7 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1954#-OBduPoF9k-CvSBnkeox:-OBduPoG2FIPmL2Ky-y8:bv1rmo6) ([raw file](https://github.com/starkware-libs/sequencer/blob/34de2bdf088c511d12b4f5faea72954abd15a611/crates/starknet_sequencer_node/src/config/node_config.rs#L7)):*
> ```XML
> use std::vec::Vec;
> 
> use blockifier::versioned_constants::VersionedConstantsOverrides;
> ```

Re-export from batcher.



_Code quote:_
```XML
use blockifier::versioned_constants::VersionedConstantsOverrides;
```

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1954#-:-OBenEmY2Ndx5eubvkqW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware and @Yael-Starkware)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 7 files at r4, 2 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1954)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1954)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @yair-starkware)

___
*[`crates/starknet_sequencer_node/src/config/node_config.rs` line 79 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1954#-OBuL-AXCt4419VbBJOV:-OBuL-AXCt4419VbBJOW:b-r5s32m) ([raw file](https://github.com/starkware-libs/sequencer/blob/82b94e67de6143232e5ac4a088854c70abbcf90e/crates/starknet_sequencer_node/src/config/node_config.rs#L79)):*
> ```XML
>         ),
>     ];
>     let mut common_execution_config = generate_struct_pointer(
> ```

Why not just add to the vector like the other elements?

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1954)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @ArniStarkware)

___
*[`crates/starknet_sequencer_node/src/config/node_config.rs` line 79 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1954#-OBuL-AXCt4419VbBJOV:-OBuT3rnBsS6KRmBsz7L:b-6w9hs7) ([raw file](https://github.com/starkware-libs/sequencer/blob/2533717812915d4a676a4778a872e55a3f4aa268/crates/starknet_sequencer_node/src/config/node_config.rs#L79)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why not just add to the vector like the other elements?
</blockquote></details>

This is a struct that is a common config, not a single param.

**Review by alonh5 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1954)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by yair-starkware** [comment]
### Merge activity

* **Nov 18, 4:13 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1954).

**Pull request merged**
