### PR TITLE
chore(infra_utils): add spawn_monitored_task

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
commit-id:817cbd25

### CODE REVIEW

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2909)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/infra_utils/src/tasks.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2909#-OEsLpeUE4v5jTDxi9v6:-OEsLpeUE4v5jTDxi9v7:bidjzwp) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89a9bd4c6bfe1e625da9ced5c395f3d50f2dbf7/crates/infra_utils/src/tasks.rs#L17)):*
> ```XML
> ///    fails.
> ///    - If the first task succeeds then it returns its result.
> ///    - If the first task panics or returns an error, the process will terminate with exit code 1.
> ```

What errors can be returned? Do we want to exit on all of them?



_Code quote:_
```XML
returns an error
```
___
*[`crates/infra_utils/src/tasks.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2909#-OEsNiZcAOD02fwWLT2x:-OEsNiZcAOD02fwWLT2y:b3xmzjy) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89a9bd4c6bfe1e625da9ced5c395f3d50f2dbf7/crates/infra_utils/src/tasks.rs#L31)):*
> ```XML
> ///
> /// A `JoinHandle<T>` of the second monitoring task.
> pub fn spawn_monitored_task<F, T>(future: F) -> JoinHandle<T>
> ```

Not sure `monitored` reflects best what this function does.
Maybe `spawn_exit_on_panic`?



_Code quote:_
```XML
spawn_monitored_task
```
___
*[`crates/infra_utils/src/tasks.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2909#-OEsMOXkDhGx5J2rnzsP:-OEsMOXkDhGx5J2rnzsQ:bghxr81) ([raw file](https://github.com/starkware-libs/sequencer/blob/b89a9bd4c6bfe1e625da9ced5c395f3d50f2dbf7/crates/infra_utils/src/tasks.rs#L56)):*
> ```XML
>                 error!("Monitored task failed: {:?}", err);
>                 on_exit_f();
>                 unreachable!()
> ```

Why do we need this?



_Code quote:_
```XML
unreachable!()
```

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2909#-:-OEwRjIO-aDio5a6Ej2A:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2909)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 3 of 5 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2909)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
