### PR TITLE
refactor(blockifier): replace WORD_WIDTH w FELT_WIDTH in contract_class

### PR DESCRIPTION
**Pull request by avivg-starkware**

### CODE REVIEW

**Comment by avivg-starkware** [comment]
* **#1967** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1967?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @avivg-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1967)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1967#-OBUKbqzARidokOp6fjv:-OBUKbr-Czlh2EgeWf1e:b-nbdx8z) ([raw file](https://github.com/starkware-libs/sequencer/blob/170a607755c5d97024598d43e9eb9ba628963cbf/crates/blockifier/src/fee/eth_gas_constants.rs#L5)):*
> ```XML
> pub const GAS_PER_MEMORY_ZERO_BYTE: usize = 4;
> pub const GAS_PER_MEMORY_BYTE: usize = 16;
> pub const GAS_PER_MEMORY_WORD: usize = GAS_PER_MEMORY_BYTE * WORD_WIDTH;
> ```

1. Be consistent.
2. Imports come before everything.



_Suggestion:_
```XML
pub const GAS_PER_MEMORY_ZERO_BYTE: usize = 4;
pub const GAS_PER_MEMORY_BYTE: usize = 16;
pub const GAS_PER_MEMORY_WORD: usize = GAS_PER_MEMORY_BYTE * starknet_api::core::WORD_WIDTH;
```

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1967)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1967#-OBUKbqzARidokOp6fjv:-OBUNPeT6-N27rdGUpSX:bax9el1) ([raw file](https://github.com/starkware-libs/sequencer/blob/170a607755c5d97024598d43e9eb9ba628963cbf/crates/blockifier/src/fee/eth_gas_constants.rs#L5)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

1. Be consistent.
2. Imports come before everything.
</blockquote></details>

1- by consistent, you're referring to the use of "starknet_api::core::WORD_WIDTH" in the other files? 
(that is used without 'use' but rather explicitly? )

if so, I did so in this file as well. Otherwise, I'm sorry not sure i understand. 

2- I see, I thought comments are excluded.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1967)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @avivg-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1967#-OBUKbqzARidokOp6fjv:-OBUOsgxEfx2TK0s_Lzd:b-b4t7os) ([raw file](https://github.com/starkware-libs/sequencer/blob/170a607755c5d97024598d43e9eb9ba628963cbf/crates/blockifier/src/fee/eth_gas_constants.rs#L5)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

1- by consistent, you're referring to the use of "starknet_api::core::WORD_WIDTH" in the other files? 
(that is used without 'use' but rather explicitly? )

if so, I did so in this file as well. Otherwise, I'm sorry not sure i understand. 

2- I see, I thought comments are excluded.
</blockquote></details>

1. Yes - this is what I meant.
___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1967#-OBUPVU8CGYWYla809Wk:-OBUPVU8CGYWYla809Wl:b3cuqlp) (no related file):*
I apologize - because this is contradictory to my latest comment. Please import the const in each file using: `starknet_api::core::WORD_WIDTH`.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1967)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @avivg-starkware and @Yoni-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1967#-OBUPVU8CGYWYla809Wk:-OBUbara8RYSMN1xwjGN:b-hcbbau) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I apologize - because this is contradictory to my latest comment. Please import the const in each file using: `starknet_api::core::WORD_WIDTH`.
</blockquote></details>

`use `starknet_api::core::WORD_WIDTH`;`

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1967)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yoni-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1967#-OBUPVU8CGYWYla809Wk:-OBUbmr2ABROx4MrTEZc:bh69pyw) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

`use `starknet_api::core::WORD_WIDTH`;`
</blockquote></details>

all good, Done :)

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1967#-:-OBUmGMXAp3dxhOpM9FV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1967)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
Blocking

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1967#-:-OBZGl8nAgfPMyCWhxE4:bq9rql6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1967)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 1 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1967#-OBZHN0I8N0vq0fcd1P1:-OBZHN0I8N0vq0fcd1P2:b-p2fx6z) ([raw file](https://github.com/starkware-libs/sequencer/blob/e759d81548a2e122aec2cf5eb8b35e0aec5a6ae1/crates/blockifier/src/fee/eth_gas_constants.rs#L1)):*
> ```XML
> use starknet_api::core::WORD_WIDTH;
> ```

Remove this const, and instead define `FELT_WIDTH = 32` in `contract_class.rs`
`WORD_WIDTH` is the size of a word in ethereum.
In `code_size`, we approximate the code size by adding the max size of each element, which is felt, which is accidentally 32. Felt width could have been different.



_Code quote:_
```XML
use starknet_api::core::WORD_WIDTH;
```

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1967)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1967)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 1 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1967#-OBZHN0I8N0vq0fcd1P1:-OBZub9n4RB5MMlgxtv8:begpm7z) ([raw file](https://github.com/starkware-libs/sequencer/blob/30842e96c8d59f239568168562b96e6b294977db/crates/blockifier/src/fee/eth_gas_constants.rs#L1)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

Done  (please tell me if I missed something) .
are the comments clear enough?
</blockquote></details>

Move `starknet_api::core::WORD_WIDTH` back to this file.

Please rename the commit and PR message

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1967)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 1 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1967#-OBZHN0I8N0vq0fcd1P1:-OBZzRn3DA5u3nsKvcix:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/30842e96c8d59f239568168562b96e6b294977db/crates/blockifier/src/fee/eth_gas_constants.rs#L1)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Move `starknet_api::core::WORD_WIDTH` back to this file.

Please rename the commit and PR message
</blockquote></details>

Done.

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1967)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1967)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1967)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1967#-:-OB_EvVLAyYdIWdsNGFs:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1967)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Pull request merged**
