### PR TITLE
chore: add client object

### PR DESCRIPTION
**Pull request by nadin-Starkware**
**Stack**:
- #2047
- #2041
- #2040
- #2035
- #2034
- #2033
- #2032
- #2030
- #2029
- #2028 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2028)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/starknet_sequencer_infra/src/component_client/definitions.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2028#-OBdko1YAswiCO8uy5G_:-OBdko1YAswiCO8uy5Ga:bi6ofun) ([raw file](https://github.com/starkware-libs/sequencer/blob/58a7467ff4bf27dd8caf24a7f465ac5c74dd1057/crates/starknet_sequencer_infra/src/component_client/definitions.rs#L52)):*
> ```XML
> 
>     pub fn get_local_client(&self) -> Option<LocalComponentClient<Request, Response>> {
>         self.local_client.clone() //.expect("Error: local_client is missing.")
> ```

Please remove X 2



_Code quote:_
```XML
 //.expect("Error: local_client is missing.")
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2028)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sequencer_infra/src/component_client/definitions.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2028#-OBdko1YAswiCO8uy5G_:-OBdqX2PBeGjOGB7NEG9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/58a7467ff4bf27dd8caf24a7f465ac5c74dd1057/crates/starknet_sequencer_infra/src/component_client/definitions.rs#L52)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please remove X 2
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2028#-:-OBeMNSS6qtjMTfZ_egE:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2028)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Pull request closed without merging**
