### PR TITLE
chore(sequencer_node): add node compilation

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1700)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/compilation.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1700#-OASsOEQ50A9-VNA0sei:-OASsOEQ50A9-VNA0sej:b-qx0i8j) ([raw file](https://github.com/starkware-libs/sequencer/blob/569dbdbec938ead535e826609b91a15bbd0d5228/crates/mempool_node/src/compilation.rs#L11)):*
> ```XML
>     IO(#[from] io::Error),
>     #[error("Exit status: {0}.")]
>     STATUS(ExitStatus),
> ```

I love the enthusiasm though



_Suggestion:_
```XML
Status(ExitStatus),
```
___
*[`crates/mempool_node/src/compilation.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1700#-OASsrJCDzPlTPYWi8O3:-OASsrJD71wwdZ9HDLSB:boyaexz) ([raw file](https://github.com/starkware-libs/sequencer/blob/569dbdbec938ead535e826609b91a15bbd0d5228/crates/mempool_node/src/compilation.rs#L18)):*
> ```XML
> mod compilation_test;
> 
> fn compile_node() -> io::Result<ExitStatus> {
> ```

Document - when are we expected to call this function?

(I ask to document it - because I am not sure I myself understand when is this function useful - are we interested in the command to do something - or is it just for tests?)



_Code quote:_
```XML
fn compile_node() -> io::Result<ExitStatus> {
```
___
*[`crates/mempool_node/src/compilation.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1700#-OASsZa-1OQBqoVQusjr:-OASsZa-1OQBqoVQusjs:b-ddvctm) ([raw file](https://github.com/starkware-libs/sequencer/blob/569dbdbec938ead535e826609b91a15bbd0d5228/crates/mempool_node/src/compilation.rs#L41)):*
> ```XML
>         Err(e) => Err(NodeCompilationError::IO(e)),
>     }
> }
> ```

What is this function useful for? Is it just for testing?



_Code quote:_
```XML
pub fn compile_node_result() -> Result<(), NodeCompilationError> {
    match compile_node() {
        Ok(status) if status.success() => Ok(()),
        Ok(status) => Err(NodeCompilationError::STATUS(status)),
        Err(e) => Err(NodeCompilationError::IO(e)),
    }
}
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1700)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/mempool_node/src/compilation.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1700#-OASsrJCDzPlTPYWi8O3:-OAStJmm5sjBKRsbfgSz:b-cf2xms) ([raw file](https://github.com/starkware-libs/sequencer/blob/569dbdbec938ead535e826609b91a15bbd0d5228/crates/mempool_node/src/compilation.rs#L18)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Document - when are we expected to call this function?

(I ask to document it - because I am not sure I myself understand when is this function useful - are we interested in the command to do something - or is it just for tests?)
</blockquote></details>

Two purposes:
1. enable us to test in the ci that the node compilation does not break
2. will compile the node in an integration test (pr is wip :pray:)
___
*[`crates/mempool_node/src/compilation.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1700#-OASsZa-1OQBqoVQusjr:-OASu902DJVLuadEMfas:bn9gm41) ([raw file](https://github.com/starkware-libs/sequencer/blob/569dbdbec938ead535e826609b91a15bbd0d5228/crates/mempool_node/src/compilation.rs#L41)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

What is this function useful for? Is it just for testing?
</blockquote></details>

This is how I envision the api for compilation : nicely (imo) wraps the compilation as either success (no error from running the command + return status is success) or details the error (which of the aforementioned has failed).

In the integration test הבא עלינו לטובה the point is, similarly to the test, to compile and then run the node.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1700)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/mempool_node/src/compilation.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1700#-OASsOEQ50A9-VNA0sei:-OASujW6BqcNHHMb19mL:bwgkxy8) ([raw file](https://github.com/starkware-libs/sequencer/blob/569dbdbec938ead535e826609b91a15bbd0d5228/crates/mempool_node/src/compilation.rs#L11)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I love the enthusiasm though
</blockquote></details>

Yea I was over zealous with this!

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1700)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/compilation.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1700#-OASsrJCDzPlTPYWi8O3:-OAWJO5C69QyhBQF2kx4:bddyu90) ([raw file](https://github.com/starkware-libs/sequencer/blob/569dbdbec938ead535e826609b91a15bbd0d5228/crates/mempool_node/src/compilation.rs#L18)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Two purposes:
1. enable us to test in the ci that the node compilation does not break
2. will compile the node in an integration test (pr is wip :pray:)
</blockquote></details>

In both cases, it is a test util. Place the code in a proper file (i.e. in a folder indicated `test_utils` or something) and/or document the fact that it is a test util.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1700)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/mempool_node/src/compilation.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1700#-OASsrJCDzPlTPYWi8O3:-OAXcPZUA87NtlC0bg0N:ba0mjyb) ([raw file](https://github.com/starkware-libs/sequencer/blob/569dbdbec938ead535e826609b91a15bbd0d5228/crates/mempool_node/src/compilation.rs#L18)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

In both cases, it is a test util. Place the code in a proper file (i.e. in a folder indicated `test_utils` or something) and/or document the fact that it is a test util.
</blockquote></details>

Right, done :-)

**Comment by ArniStarkware** [comment]
*[`crates/mempool_node/src/test_utils/compilation.rs` line 7 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1700#-OAXgjXz20BMxEt3H2nC:-OAXgjXz20BMxEt3H2nD:bgrd33w) ([raw file](https://github.com/starkware-libs/sequencer/blob/1c70c090ad9aa2d6bf04686b5acbd5df96f61752/crates/mempool_node/src/test_utils/compilation.rs#L7)):*
> ```XML
> 
> #[cfg(test)]
> #[path = "compilation_test.rs"]
> ```

no longer needed.



_Code quote:_
```XML
#[cfg(test)]
#[path = "compilation_test.rs"]
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1700)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1700#-:-OAXi3aaEcizkVTkShmI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
