### PR TITLE
chore(network): create converters for stress test

### PR DESCRIPTION
**Pull request by eitanm-starkware**

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1869)* status: all files reviewed, 6 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/bin/network_stress_test/converters.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1869#-OB5RoUjEDlepdh7yZH0:-OB5RoUk5aMvg4C4nV6u:b-frtlrb) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb07a6873b2d14b6881b8cafb1d0496229f6a03/crates/papyrus_network/src/bin/network_stress_test/converters.rs#L3)):*
> ```XML
> use std::time::{Duration, SystemTime};
> 
> struct StressTestPayload(u32, Vec<u8>, SystemTime);
> ```

Rename to StressTestMessage
___
*[`crates/papyrus_network/src/bin/network_stress_test/converters.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1869#-OB5Rt_c7ubDH62CpAyA:-OB5Rt_c7ubDH62CpAyB:bx2fbjw) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb07a6873b2d14b6881b8cafb1d0496229f6a03/crates/papyrus_network/src/bin/network_stress_test/converters.rs#L3)):*
> ```XML
> use std::time::{Duration, SystemTime};
> 
> struct StressTestPayload(u32, Vec<u8>, SystemTime);
> ```

Make these fields named
___
*[`crates/papyrus_network/src/bin/network_stress_test/converters.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1869#-OB5Suwr4ruXPRFNTgrI:-OB5Suwr4ruXPRFNTgrJ:bl8qt9f) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb07a6873b2d14b6881b8cafb1d0496229f6a03/crates/papyrus_network/src/bin/network_stress_test/converters.rs#L12)):*
> ```XML
>         let seconds = time.as_secs().to_be_bytes().to_vec();
>         let nanos = time.subsec_nanos().to_be_bytes().to_vec();
>         [id, seconds, nanos, payload].concat()
> ```

Let's use the fact that payload is the bigger one to increase performance. If we serialize/deserialize it first instead of last then we can avoid copying it here. We'll just need to append to it a small amount of numbers
___
*[`crates/papyrus_network/src/bin/network_stress_test/converters.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1869#-OB5S76jDD76zIgFc7vW:-OB5S76jDD76zIgFc7vX:bfqdyah) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb07a6873b2d14b6881b8cafb1d0496229f6a03/crates/papyrus_network/src/bin/network_stress_test/converters.rs#L16)):*
> ```XML
> }
> 
> impl From<Vec<u8>> for StressTestPayload {
> ```

Add a comment that this automatically implements TryFrom<Vec<u8>> for StressTestPayload
___
*[`crates/papyrus_network/src/bin/network_stress_test/converters.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1869#-OB5SNnN2KYzt4cmNsSq:-OB5SNnN2KYzt4cmNsSr:b-lomcjv) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb07a6873b2d14b6881b8cafb1d0496229f6a03/crates/papyrus_network/src/bin/network_stress_test/converters.rs#L18)):*
> ```XML
> impl From<Vec<u8>> for StressTestPayload {
>     fn from(value: Vec<u8>) -> Self {
>         let id = u32::from_be_bytes([value[0], value[1], value[2], value[3]]);
> ```

write value[0..3] instead. Same below
___
*[`crates/papyrus_network/src/bin/network_stress_test/converters.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1869#-OB5SZHC-qcwfIypUgiI:-OB5SZHC-qcwfIypUgiJ:b-wrl9fp) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb07a6873b2d14b6881b8cafb1d0496229f6a03/crates/papyrus_network/src/bin/network_stress_test/converters.rs#L24)):*
> ```XML
>         let nanos = u32::from_be_bytes([value[12], value[13], value[14], value[15]]);
>         let time = SystemTime::UNIX_EPOCH + Duration::new(seconds, nanos);
>         let payload = value[16..].to_vec();
> ```

I think this copies the payload. Try to use Vec::split to extract the payload at the start from the rest of the fields and then parse the rest of the fields (see comment above. If we end up moving it then it's even simpler)

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1869)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/bin/network_stress_test/converters.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1869#-OB5RoUjEDlepdh7yZH0:-OB5Tu4sDl01T7UK-jXm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb07a6873b2d14b6881b8cafb1d0496229f6a03/crates/papyrus_network/src/bin/network_stress_test/converters.rs#L3)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to StressTestMessage
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/bin/network_stress_test/converters.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1869#-OB5Rt_c7ubDH62CpAyA:-OB5TuUMENJgpmvQQ1nE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb07a6873b2d14b6881b8cafb1d0496229f6a03/crates/papyrus_network/src/bin/network_stress_test/converters.rs#L3)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Make these fields named
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/bin/network_stress_test/converters.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1869#-OB5Suwr4ruXPRFNTgrI:-OB5UPBTASzNJzpGl9Wi:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb07a6873b2d14b6881b8cafb1d0496229f6a03/crates/papyrus_network/src/bin/network_stress_test/converters.rs#L12)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Let's use the fact that payload is the bigger one to increase performance. If we serialize/deserialize it first instead of last then we can avoid copying it here. We'll just need to append to it a small amount of numbers
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/bin/network_stress_test/converters.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1869#-OB5S76jDD76zIgFc7vW:-OB5U_NMC-jvHau-NF6Z:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb07a6873b2d14b6881b8cafb1d0496229f6a03/crates/papyrus_network/src/bin/network_stress_test/converters.rs#L16)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add a comment that this automatically implements TryFrom<Vec<u8>> for StressTestPayload
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/bin/network_stress_test/converters.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1869#-OB5SNnN2KYzt4cmNsSq:-OB67DHQ6o7BRPUsEYLE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb07a6873b2d14b6881b8cafb1d0496229f6a03/crates/papyrus_network/src/bin/network_stress_test/converters.rs#L18)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

write value[0..3] instead. Same below
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/bin/network_stress_test/converters.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1869#-OB5SZHC-qcwfIypUgiI:-OB66HSZEIYKQiZJoMFO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0bb07a6873b2d14b6881b8cafb1d0496229f6a03/crates/papyrus_network/src/bin/network_stress_test/converters.rs#L24)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think this copies the payload. Try to use Vec::split to extract the payload at the start from the rest of the fields and then parse the rest of the fields (see comment above. If we end up moving it then it's even simpler)
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1869)* status: all files reviewed, 3 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/bin/network_stress_test/converters.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1869#-OB67SRU-kX_DzvjCuhr:-OB67SRU-kX_DzvjCuhs:b-m92ksp) ([raw file](https://github.com/starkware-libs/sequencer/blob/abdc3293660939fb9df44f5a9913fdab6f3a58d2/crates/papyrus_network/src/bin/network_stress_test/converters.rs#L16)):*
> ```XML
>         let mut seconds = time.as_secs().to_be_bytes().to_vec();
>         let mut nanos = time.subsec_nanos().to_be_bytes().to_vec();
>         payload.append(&mut id);
> ```

use extend instead of append. should be cleaner
___
*[`crates/papyrus_network/src/bin/network_stress_test/converters.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1869#-OB67fD2EvM6wtcpLRY4:-OB67fD39XEnka3cKQoh:b2lyu41) ([raw file](https://github.com/starkware-libs/sequencer/blob/abdc3293660939fb9df44f5a9913fdab6f3a58d2/crates/papyrus_network/src/bin/network_stress_test/converters.rs#L28)):*
> ```XML
>         let vec_size = value.len();
>         let payload_size = vec_size - 12;
>         let id_time = value.split_off(payload_size);
> ```

rename to id_and_time

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1869)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/bin/network_stress_test/converters.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1869#-OB67SRU-kX_DzvjCuhr:-OB6AYRc8Cr0-LOv4jOy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/abdc3293660939fb9df44f5a9913fdab6f3a58d2/crates/papyrus_network/src/bin/network_stress_test/converters.rs#L16)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

use extend instead of append. should be cleaner
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/bin/network_stress_test/converters.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1869#-OB67fD2EvM6wtcpLRY4:-OB6AZQi7A-dN-bKl3eL:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/abdc3293660939fb9df44f5a9913fdab6f3a58d2/crates/papyrus_network/src/bin/network_stress_test/converters.rs#L28)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename to id_and_time
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1869#-:-OB6AjeJ3_8sNhdAz71R:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Pull request merged**
