### PR TITLE
chore(starknet_api): move gas price related test consts to starknet api

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#2446** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2446?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2445** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2445?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2444** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2444?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2443** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2443?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2443?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2443)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_api/src/test_utils.rs` line 119 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2443#-ODf2HSG3yZBkuVYfTQp:-ODf2HSG3yZBkuVYfTQq:bzgss6h) ([raw file](https://github.com/starkware-libs/sequencer/blob/4760d79bb2558beffaaaaeb210134beebf2dcd11/crates/starknet_api/src/test_utils.rs#L119)):*
> ```XML
> 
> // The max_fee / resource bounds used for txs in this test.
> // V3 transactions:
> ```

Is this comment still relevant?
Same below



_Code quote:_
```XML
// The max_fee / resource bounds used for txs in this test.
// V3 transactions:
```

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r1, 13 of 13 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2443)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_api/src/test_utils.rs` line 119 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2443#-ODf2HSG3yZBkuVYfTQp:-ODf2HSG3yZBkuVYfTQq:bo0okr3) ([raw file](https://github.com/starkware-libs/sequencer/blob/4760d79bb2558beffaaaaeb210134beebf2dcd11/crates/starknet_api/src/test_utils.rs#L119)):*
> ```XML
> 
> // The max_fee / resource bounds used for txs in this test.
> // V3 transactions:
> ```

Fix comment



_Code quote:_
```XML
// The max_fee / resource bounds used for txs in this test.
// V3 transactions:
```

**Review by alonh5 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2443#-:-OEOScPJ67NrAA_yncR8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2443)* status: 12 of 15 files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/starknet_api/src/test_utils.rs` line 119 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2443#-ODf2HSG3yZBkuVYfTQp:-OEOVrsX9PBiZ32T5PQF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4760d79bb2558beffaaaaeb210134beebf2dcd11/crates/starknet_api/src/test_utils.rs#L119)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Fix comment
</blockquote></details>

Done.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2443)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
