### PR TITLE
refactor(fee): rename ResourceBoundsMapping => DeprecatedResourceBoundsMapping

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/504)

### CODE REVIEW

**Comment by nimrod-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/504?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#506** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/506?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#505** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/505?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#504** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/504?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#503** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/503?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nimrod-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by nimrod-starkware — COMMENTED** [review]
All this PR is doing is renaming `ResourceBoundsMapping` => `DeprecatedResourceBoundsMapping`

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/504#-:-O4j-0851PJ5gvnfaAzv:b-z5smgu)* status: 0 of 33 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @TzahiTaub)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 33 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/504)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/papyrus_test_utils/src/lib.rs` line 725 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/504#-O4jAmBC4JJs5By39wcF:-O4jAmBEAbekCR6Xshpb:b57u0o7) ([raw file](https://github.com/starkware-libs/sequencer/blob/59b3b0b4cd759b51d8225809bb80b51c1638271e/crates/papyrus_test_utils/src/lib.rs#L725)):*
> ```XML
>         pub max_price_per_unit: u128,
>     }
>     pub struct DeprecatedResourceBoundsMapping(pub BTreeMap<Resource, ResourceBounds>);
> ```

this type is imported and defined in the same module; why?



_Code quote:_
```XML
pub struct DeprecatedResourceBoundsMapping(pub BTreeMap<Resource, ResourceBounds>);
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/504)* status: 32 of 35 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/papyrus_test_utils/src/lib.rs` line 725 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/504#-O4jAmBC4JJs5By39wcF:-O4jM5jz5JeT5MsvP7y1:bqb9o69) ([raw file](https://github.com/starkware-libs/sequencer/blob/f902df737277787ed24536bca9d8aa1b65fc06dd/crates/papyrus_test_utils/src/lib.rs#L725)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this type is imported and defined in the same module; why?
</blockquote></details>

It's under a weird macro that generates some trait implementations, all the types here were declared before

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/504#-:-O4jTjh4EOSmcCMwdakK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/504)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/504)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/504)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/504)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Comment by nimrod-starkware** [comment]
### Merge activity

* **Aug 25, 3:32 AM EDT**: @nimrod-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/504).

**Pull request merged**
