### PR TITLE
feat(consensus): use network channel instead of regular channel as input for StreamHandler

### PR DESCRIPTION
**Pull request by guy-starkware**
This PR replaces the regular `futures::channel::mpsc::Receiver` and `Sender` with `GenericReceiver` and `GenericSender` that integrate into our network (from `papyrus_network`). 

It also uses that crate's test utils to make a mock network to use in our tests. 

The new network channel provides a `PeerId` through the `BroadcastedMessageManager` struct, which is used to key all the incoming messages (i.e., instead of sorting and buffering on the `StreamId` alone, we now key them on `(PeerId, StreamId)`).
This re-keying of the dictionaries inside `StreamHandler` is deferred to another PR. 

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1084)

### CODE REVIEW

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
squash commits before merge

> Reviewed 2 of 3 files at r3, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1084#-:-O82JESm8ZRPvdgddEYb:b-an0snd)* status: all files reviewed, 1 unresolved discussion (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 27 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1084#-O82EUdM8zhJ6DAw_DPe:-O82EUdM8zhJ6DAw_DPf:b-m27nif) ([raw file](https://github.com/starkware-libs/sequencer/blob/786a0331fa498b4ab0922be18565e73518b06e4f/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L27)):*
> ```XML
>     // TODO(guyn): need to convert a Multiaddr to a PeerId (u64)
>     metadata.originator_id
>     // return 0; // placeholder
> ```

is this needed?



_Code quote:_
```XML
// return 0; // placeholder
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1084)* status: all files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 27 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1084#-O82EUdM8zhJ6DAw_DPe:-O85h6Pl97IqgO6jA6mH:b-fzasz9) ([raw file](https://github.com/starkware-libs/sequencer/blob/786a0331fa498b4ab0922be18565e73518b06e4f/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L27)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

is this needed?
</blockquote></details>

Sorry, forgot to delete those!

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1084#-:-O85v3LaDmnUPS9VXxkh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1084)* status: all files reviewed, 1 unresolved discussion (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 19 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1084#-O8WrfxD6wwF_IrRoKdN:-O8WrfxD6wwF_IrRoKdO:b957gef) ([raw file](https://github.com/starkware-libs/sequencer/blob/e96a5c75bdece74be7c1e2a466f3c84c2704b332/crates/sequencing/papyrus_consensus/src/lib.rs#L19)):*
> ```XML
> #[allow(missing_docs)]
> pub mod types;
> ```

Is this intentional? 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 63 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1084#-O8WsCSX2Fa15mVajJzi:-O8WsCSX2Fa15mVajJzj:b-n6d6dn) ([raw file](https://github.com/starkware-libs/sequencer/blob/025aa7dc3cf4ba39f7e4fcc7f364ee51616969b0/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L63)):*
> ```XML
>     sender: mpsc::Sender<mpsc::Receiver<T>>,
>     // An end of a channel used to receive messages.
>     // receiver: GenericReceiver<ReceivedBroadcastedMessage<StreamMessage<T>>>,
> ```

Please remove
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 100 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1084#-O8WuP3QCsN87UotTRgU:-O8WuP3R5mku_9nqttYX:b-l5z3i) ([raw file](https://github.com/starkware-libs/sequencer/blob/025aa7dc3cf4ba39f7e4fcc7f364ee51616969b0/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L100)):*
> ```XML
>     }
> 
>     // Handle the message, return true if the channel is still open.
> ```

Please delete.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 5 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1084#-O8WvANc0FZzNzdSRERZ:-O8WvANc0FZzNzdSRER_:b-n6d6dn) ([raw file](https://github.com/starkware-libs/sequencer/blob/025aa7dc3cf4ba39f7e4fcc7f364ee51616969b0/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L5)):*
> ```XML
> use futures::SinkExt;
> use papyrus_network::network_manager::test_utils::{
>     // create_test_broadcasted_message_manager,
> ```

Please remove

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1084)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 19 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1084#-O8WrfxD6wwF_IrRoKdN:-O8_i_K4EFi5hKsZLF7g:b-83og3x) ([raw file](https://github.com/starkware-libs/sequencer/blob/e96a5c75bdece74be7c1e2a466f3c84c2704b332/crates/sequencing/papyrus_consensus/src/lib.rs#L19)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Is this intentional?
</blockquote></details>

Nope.

**Pull request merged**
