### PR TITLE
refactor(ci): supporting git cliff for chosen projects

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/431)

### CODE REVIEW

**Comment by nimrod-starkware** [comment]
* **#431** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/431?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nimrod-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/431)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`scripts/generate_changelog.py` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4B02_O5ABQgwmbAovo:-O4B02_P0Av7_BQOcioe:b-z98gnx) ([raw file](https://github.com/starkware-libs/sequencer/blob/f93a92ab8558d6324c76279b92343b49c1f45fcb/scripts/generate_changelog.py#L40)):*
> ```Python
>     ],
>     "committer": ["committer", "committer_cli", "starknet_committer"],
>     "starknet_api": ["starknet_api"],
> ```

Is this mapping correct?
I don't know where to put `starknet_sierra_compile`, `task_executor`, `tests-integration`, `starknet_client`



_Code quote:_
```Python
    "blockifier": ["blockifier", "native_blockifier"],
    "mempool": [
        "gateway",
        "mempool",
        "mempool_infra",
        "mempool_node",
        "mempool_test_utils",
        "mempool_types",
    ],
    "papyrus": [
        "papyrus_base_layer",
        "papyrus_common",
        "papyrus_config",
        "papyrus_execution",
        "papyrus_load_test",
        "papyrus_monitoring_gateway",
        "papyrus_network",
        "papyrus_node",
        "papyrus_p2p_sync",
        "papyrus_proc_macros",
        "papyrus_protobuf",
        "papyrus_rpc",
        "papyrus_storage",
        "papyrus_sync",
        "papyrus_test_utils",
        "sequencing",
    ],
    "committer": ["committer", "committer_cli", "starknet_committer"],
    "starknet_api": ["starknet_api"],
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/431)* status: 1 of 2 files reviewed, 11 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, @dorimedini-starkware, @Itay-Tsabary-Starkware, and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4B2d053oWiSq6RzUCt:-O4B9G17DNlZ4Kpg2i_Z:bp6tfj9) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

did you manually test this?
</blockquote></details>

yes, it works.
I didn't test the installation of git-cliff (was already installed), will do it now

___
___
*[`scripts/generate_changelog.py` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4B1qBs55Yi9PTF-MnF:-O4BB8Rl91iLMAnuKX3i:b-1qlx90) ([raw file](https://github.com/starkware-libs/sequencer/blob/f93a92ab8558d6324c76279b92343b49c1f45fcb/scripts/generate_changelog.py#L3)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do these need to be listed in requirements.txt?
</blockquote></details>

I guess they do, no?
___
*[`scripts/generate_changelog.py` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4B1jlU86-JG4yvFUch:-O4B9TzU30TZp0QO4YQX:b-jlzes9) ([raw file](https://github.com/starkware-libs/sequencer/blob/f93a92ab8558d6324c76279b92343b49c1f45fcb/scripts/generate_changelog.py#L5)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`run_command` should probably be in it's own utils module
</blockquote></details>

Do you mean to create `utils.py` and move it there?
___
*[`scripts/generate_changelog.py` line 39 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4B1Ud-0ab1AKVUJeIg:-O4B9i_K-xAVFwvKhANX:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/f93a92ab8558d6324c76279b92343b49c1f45fcb/scripts/generate_changelog.py#L39)):*
> ```Python
>         "sequencing",
>     ],
>     "committer": ["committer", "committer_cli", "starknet_committer"],
> ```

Done
___
*[`scripts/generate_changelog.py` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4B02_O5ABQgwmbAovo:-O4BDHt_0RfZof25ts3l:b-q4ysxn) ([raw file](https://github.com/starkware-libs/sequencer/blob/f93a92ab8558d6324c76279b92343b49c1f45fcb/scripts/generate_changelog.py#L40)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

neither do I. ask Dafna/DanB/ItayT about these crates?
</blockquote></details>

@dafnamatsry @dan-starkware @Itay-Tsabary-Starkware ?
___
*[`scripts/generate_changelog.py` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4B2UiW7k3VCbYmuyLa:-O4BB-hS1WG3fqc4JYJG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f93a92ab8558d6324c76279b92343b49c1f45fcb/scripts/generate_changelog.py#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

calling this doesn't always install anything
</blockquote></details>

Done.
___
*[`scripts/generate_changelog.py` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4B1wbiEbz2kEEvZmmG:-O4BAfBEAnIwBYDp_iF4:bxcd8gf) ([raw file](https://github.com/starkware-libs/sequencer/blob/f93a92ab8558d6324c76279b92343b49c1f45fcb/scripts/generate_changelog.py#L60)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

assert. the raised exception gives a traceback, which is useful
</blockquote></details>

I removed this check because the usage of choices
___
*[`scripts/generate_changelog.py` line 62 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4B2752Drjm5pMS3TCY:-O4BAZ1E92YcyYBe2Cfw:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f93a92ab8558d6324c76279b92343b49c1f45fcb/scripts/generate_changelog.py#L62)):*
> ```Python
>         exit(1)
>     crates = PROJECT_TO_CRATES[project_name]
>     include_paths = "".join((f"--include-path crates/{crate}/ " for crate in crates))
> ```

Done.
___
*[`scripts/generate_changelog.py` line 66 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4B2ATC-U7d9fqqKv8_:-O4BAZQ6-c1zY7HJ8QRb:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f93a92ab8558d6324c76279b92343b49c1f45fcb/scripts/generate_changelog.py#L66)):*
> ```Python
>         f'git-cliff {start_tag}..{end_tag} -o changelog_{start_tag}_{end_tag}.md --ignore-tags ".*-dev.[0-9]+" '
>         + include_paths
>     )
> ```

Done.
___
*[`scripts/generate_changelog.py` line 74 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4B2It_0b7udDoY6XG2:-O4BAzkf-gNXykKjtkhJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f93a92ab8558d6324c76279b92343b49c1f45fcb/scripts/generate_changelog.py#L74)):*
> ```Python
>         "--start", type=str, help="The commit that changelog's history starts from."
>     )
>     parser.add_argument("--end", type=str, help="The commit that changelog's history ends at.")
> ```

Done.
___
*[`scripts/generate_changelog.py` line 76 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4B2ML905YB-B2uYkG4:-O4BAz31-cyrLk7dVuQS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f93a92ab8558d6324c76279b92343b49c1f45fcb/scripts/generate_changelog.py#L76)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use `choices` (I think this is the syntax)
</blockquote></details>

Done.

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/431)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @alon-dotan-starkware, @dafnamatsry, @dan-starkware, @dorimedini-starkware, @Itay-Tsabary-Starkware, and @TzahiTaub)

___
*[`scripts/generate_changelog.py` line 5 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4B1jlU86-JG4yvFUch:-O4EbRJo1FPXH-lXY6hb:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f93a92ab8558d6324c76279b92343b49c1f45fcb/scripts/generate_changelog.py#L5)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/431)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware, @dafnamatsry, @dan-starkware, @Itay-Tsabary-Starkware, and @TzahiTaub)

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/431)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware, @dan-starkware, @Itay-Tsabary-Starkware, and @TzahiTaub)

___
*[`scripts/generate_changelog.py` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4B02_O5ABQgwmbAovo:-O4EdIJgC9ANV0GQcPSn:b-fcgbrt) ([raw file](https://github.com/starkware-libs/sequencer/blob/f93a92ab8558d6324c76279b92343b49c1f45fcb/scripts/generate_changelog.py#L40)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

@dafnamatsry @dan-starkware @Itay-Tsabary-Starkware ?
</blockquote></details>

Not sure the division by the original repos make sense...
`starknet_sierra_compile`, `task_executor`, `tests-integration` originally came from the mempool repo.
But the first 2 are general utilities, not specific to the mempool.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/431)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @TzahiTaub)

___
*[`scripts/generate_changelog.py` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4B02_O5ABQgwmbAovo:-O4FHaMP-g7XiygQ-1oP:b-2q07qs) ([raw file](https://github.com/starkware-libs/sequencer/blob/f93a92ab8558d6324c76279b92343b49c1f45fcb/scripts/generate_changelog.py#L40)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Not sure the division by the original repos make sense...
`starknet_sierra_compile`, `task_executor`, `tests-integration` originally came from the mempool repo.
But the first 2 are general utilities, not specific to the mempool.
</blockquote></details>

OK, since only the blockifier really needs release notes ATM,
and in the future hopefully the entire sequencer will have release notes,
let's have two options: blockifier, or everything.

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/431)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`scripts/generate_changelog.py` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4B1qBs55Yi9PTF-MnF:-O4JmdGnDojnqJ_h_I-8:b-h6xwg4) ([raw file](https://github.com/starkware-libs/sequencer/blob/f93a92ab8558d6324c76279b92343b49c1f45fcb/scripts/generate_changelog.py#L3)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not sure.
merge_paths_test imports from merge_branches, which already imports argparse for example,
but the CI phase that runs merge_paths_test only installs scripts/requirements.txt, which only contains GitPython as a dependency.
@alon-dotan-starkware when should we and when should we not add things to scripts/requirements.txt?
</blockquote></details>

This script is not part of the CI flow. Maybe there's no need to add it to `requirements.txt` then? It can be generated locally
___
*[`scripts/generate_changelog.py` line 9 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4JmPCk9mMz6FqHXPnL:-O4JmPCk9mMz6FqHXPnM:b-oyqglq) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4e1a654b93c7ab50877a031b0f01feaecc4f66d/scripts/generate_changelog.py#L9)):*
> ```Python
> # scripts/generate_changelog.py --start <FROM_TAG> --end <TO_TAG> --project <PROJECT_NAME>
> GIT_CLIFF_VERSION = "2.4.0"
> PROJECT_TO_PATHS = {"blockifier": ["crates/blockifier/"], "all": []}
> ```

@dorimedini-starkware IIRC you said that `native_blockifier`should not be included, right?



_Code quote:_
```Python
["crates/blockifier/"]
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/431)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware, @dorimedini-starkware, and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4B2d053oWiSq6RzUCt:-O4Jnp8qAcz3eak1MG4t:baxtn4n) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this part was tested in the previous `.sh` version, it's ok
</blockquote></details>

@dorimedini-starkware Other than that, do you want to enforce that the scope in commitlint is not empty?

___

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/431#-:-O4K8k1U8NQxs2h3fYLd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4B2d053oWiSq6RzUCt:-O4K8i6MEPDmQxYgqswF:b-vkb3db) (no related file):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

@dorimedini-starkware Other than that, do you want to enforce that the scope in commitlint is not empty?
</blockquote></details>

no need now IMO

___
___
*[`scripts/generate_changelog.py` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4B1qBs55Yi9PTF-MnF:-O4K8NvODmcOL91MvjGK:b-jf6e3d) ([raw file](https://github.com/starkware-libs/sequencer/blob/f93a92ab8558d6324c76279b92343b49c1f45fcb/scripts/generate_changelog.py#L3)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

This script is not part of the CI flow. Maybe there's no need to add it to `requirements.txt` then? It can be generated locally
</blockquote></details>

ok, if there's nothing to test then no need to add anything to requirements
___
*[`scripts/generate_changelog.py` line 9 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/431#-O4JmPCk9mMz6FqHXPnL:-O4K8TSE7Of8QJow5Vnr:bsm1log) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4e1a654b93c7ab50877a031b0f01feaecc4f66d/scripts/generate_changelog.py#L9)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

@dorimedini-starkware IIRC you said that `native_blockifier`should not be included, right?
</blockquote></details>

right. native_blockifier depends on blockifier, but not the other way around; and the native blockifier crate is (and will remain) unpublished

**Pull request merged**
