### PR TITLE
chore(blockifier): move GasPrices to snapi

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2245)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware, @ArniStarkware, and @dorimedini-starkware)

___
*[`crates/blockifier/src/blockifier/block.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2245#-OCYUTtI8SRLB4_8ohv1:-OCYUTtJCy_HJQ6s5o4c:b-89znet) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0e9ff56648157f0312f7d9df63dd465d1c8e511/crates/blockifier/src/blockifier/block.rs#L41)):*
> ```XML
>     let expected_eth_l2_gas_price = VersionedConstants::latest_constants()
>         .convert_l1_to_l2_gas_price_round_up(
>             gas_prices.gas_price_vector(&FeeType::Eth).l1_gas_price.into(),
> ```

When the call is trivial, it's better to access the field directly instead of using this method. (copied comment from previous PR).



_Code quote:_
```XML
gas_price_vector(&FeeType::Eth)
```
___
*[`crates/blockifier/src/blockifier/block.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2245#-OCYUHZe46gySbDTPLZT:-OCYUHZe46gySbDTPLZU:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0e9ff56648157f0312f7d9df63dd465d1c8e511/crates/blockifier/src/blockifier/block.rs#L65)):*
> ```XML
> }
> 
> pub fn gas_prices(
> ```





_Suggestion:_
```XML
validated_gas_prices
```
___
*[`crates/starknet_api/src/transaction/fields.rs` line 469 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2245#-OCYWfrU28TYiwqmuB_R:-OCYWfrU28TYiwqmuB_S:b-mzsgri) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0e9ff56648157f0312f7d9df63dd465d1c8e511/crates/starknet_api/src/transaction/fields.rs#L469)):*
> ```XML
> 
> #[derive(Clone, Copy, Hash, EnumIter, Eq, PartialEq)]
> pub enum FeeType {
> ```

This isn't a tx field, it's only used in gas prices, right? Wouldn't it be better in the same file with gas prices?

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/blockifier/block.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2245#-OCYUHZe46gySbDTPLZT:-OCYfro82fX8w-HdS0xz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0e9ff56648157f0312f7d9df63dd465d1c8e511/crates/blockifier/src/blockifier/block.rs#L65)):*
> ```XML
> }
> 
> pub fn gas_prices(
> ```

Done.

**Comment by ArniStarkware** [comment]
*[`crates/starknet_api/src/transaction/fields.rs` line 469 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2245#-OCYWfrU28TYiwqmuB_R:-OCYh5Dj6yOR4Z1NQ07L:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0e9ff56648157f0312f7d9df63dd465d1c8e511/crates/starknet_api/src/transaction/fields.rs#L469)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This isn't a tx field, it's only used in gas prices, right? Wouldn't it be better in the same file with gas prices?
</blockquote></details>

Done.

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/blockifier/block.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2245#-OCYUTtI8SRLB4_8ohv1:-OCYfnRB3Ms5LFojTple:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0e9ff56648157f0312f7d9df63dd465d1c8e511/crates/blockifier/src/blockifier/block.rs#L41)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

When the call is trivial, it's better to access the field directly instead of using this method. (copied comment from previous PR).
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 24 of 24 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2245#-:-OCcD-hNAe7UtlG0A22b:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware and @dorimedini-starkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2245)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware and @dorimedini-starkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2245)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware and @dorimedini-starkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Nov 28, 5:18 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2245).

**Pull request merged**
