### PR TITLE
feat: add remote connection test

### PR DESCRIPTION
**Pull request by nadin-Starkware**
**Stack**:
- #2960
- #2959
- #2945 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2945)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2945#-OEyHkAPByv9jTH03crl:-OEyHkAQ3JknFWHLgBBP:b-u8ltgf) ([raw file](https://github.com/starkware-libs/sequencer/blob/bff6728ecd502697078102c9f6b24416203a9dd6/crates/starknet_integration_tests/src/end_to_end_integration.rs#L75)):*
> ```XML
> 
>     let mut available_ports =
>         AvailablePorts::new(TestIdentifier::EndToEndIntegrationTest.into(), 0);
> ```

Please change



_Code quote:_
```XML
0
```
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2945#-OEyFI343WTv1YcdEACH:-OEyFI343WTv1YcdEACI:b-2kzfos) ([raw file](https://github.com/starkware-libs/sequencer/blob/bff6728ecd502697078102c9f6b24416203a9dd6/crates/starknet_integration_tests/src/end_to_end_integration.rs#L79)):*
> ```XML
>     let component_configs: Vec<ComponentConfig> = vec![ComponentConfig::default(); N_SEQUENCERS]
>         .into_iter()
>         .chain(get_remote_test_config(&mut available_ports))
> ```

Please rename this function to reflect these are `component` configs.



_Code quote:_
```XML
get_remote_test_config
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2945)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2945#-OEyHkAPByv9jTH03crl:-OEyOLGf6OTZi2rzBg16:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bff6728ecd502697078102c9f6b24416203a9dd6/crates/starknet_integration_tests/src/end_to_end_integration.rs#L75)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2945#-OEyFI343WTv1YcdEACH:-OEyOMBp8gCmlMKGyL66:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bff6728ecd502697078102c9f6b24416203a9dd6/crates/starknet_integration_tests/src/end_to_end_integration.rs#L79)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please rename this function to reflect these are `component` configs.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2945)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Comment by nadin-Starkware** [comment]
✓ Commit merged in pull request [#2959](https://github.com/starkware-libs/sequencer/pull/2959)

**Pull request closed without merging**
