### PR TITLE
feat(batcher): add l1-provider client

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Comment by yair-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1870?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1870** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1870?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1791** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1791?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1788** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1788?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1787** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1787?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yair-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1870)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1870)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/batcher/src/transaction_provider.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1870#-OBKSa5A1bgVE_t77jjz:-OBKSa5A1bgVE_t77jk-:brs8ae6) ([raw file](https://github.com/starkware-libs/sequencer/blob/0464fa7fd8459680290b6d0e2526a95c2a38d960/crates/batcher/src/transaction_provider.rs#L69)):*
> ```XML
> }
> 
> // TODO: Remove L1Provider code when the communication module of l1-provider is added.
> ```

Why not put this in the communications module already, and have it changed/adujsted there later?
___
*[`crates/batcher/src/transaction_provider.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1870#-OBKSN3KCfmHM9tTap1i:-OBKSN3KCfmHM9tTap1j:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0464fa7fd8459680290b6d0e2526a95c2a38d960/crates/batcher/src/transaction_provider.rs#L72)):*
> ```XML
> #[cfg_attr(test, automock)]
> #[async_trait]
> pub trait L1ProviderClientTrait: Send + Sync {
> ```





_Suggestion:_
```XML
L1ProviderClient
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1870)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/batcher/src/transaction_provider.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1870#-OBKSa5A1bgVE_t77jjz:-OBKbtoA9Ek73ZYHnlrQ:b-o5y33w) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e506332b64e0836835e0b1588795213ad1760c5/crates/batcher/src/transaction_provider.rs#L69)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why not put this in the communications module already, and have it changed/adujsted there later?
</blockquote></details>

I am not sure what else needs to be done in communications modules.
I prefer to leave it for the infra team.
___
*[`crates/batcher/src/transaction_provider.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1870#-OBKSN3KCfmHM9tTap1i:-OBKf5H13dvrGkr2wX9K:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e506332b64e0836835e0b1588795213ad1760c5/crates/batcher/src/transaction_provider.rs#L72)):*
> ```XML
> #[cfg_attr(test, automock)]
> #[async_trait]
> pub trait L1ProviderClientTrait: Send + Sync {
> ```

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1870#-:-OBQQCgPDpe9ER3tp8FT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1870)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Comment by yair-starkware** [comment]
### Merge activity

* **Nov 12, 3:01 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1870).

**Pull request merged**
