### PR TITLE
feat(blockifier): versioned constants builtin names no longer strings

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/971)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/971)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/971#-O7UCyPW4CIbkPT8n52C:-O7UCyPW4CIbkPT8n52D:b-bpmez7) ([raw file](https://github.com/starkware-libs/sequencer/blob/a9beaf5018eda65920f2caf4e4e7485e3e314321/crates/blockifier/src/fee/fee_utils.rs#L48)):*
> ```XML
>         constants::N_STEPS_RESOURCE.to_string(),
>         vm_resource_usage.total_n_steps() + n_reverted_steps,
>     );
> ```

`n_steps` is not a builtin, so we shouldn't really combine the steps with the `fold` below; I used another `u128::max` explicitly, WDYT?



_Code quote:_
```XML
    vm_resource_usage_for_fee.insert(
        constants::N_STEPS_RESOURCE.to_string(),
        vm_resource_usage.total_n_steps() + n_reverted_steps,
    );
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 554 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/971#-O7UDD0d9AvXqTNVltI6:-O7UDD0d9AvXqTNVltI7:b-2rf6gt) ([raw file](https://github.com/starkware-libs/sequencer/blob/a9beaf5018eda65920f2caf4e4e7485e3e314321/crates/blockifier/src/transaction/objects.rs#L554)):*
> ```XML
>             .map(|(builtin, value)| (builtin.to_str_with_suffix().to_string(), *value))
>             .collect()
>     }
> ```

this is no only used in the below `to_resources_mapping` function, so I inlined it



_Code quote:_
```XML
    fn prover_builtins_by_name(&self) -> HashMap<String, usize> {
        self.prover_builtins()
            .iter()
            .map(|(builtin, value)| (builtin.to_str_with_suffix().to_string(), *value))
            .collect()
    }
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/971)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @amosStarkware and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/971#-O7UCyPW4CIbkPT8n52C:-O7UUl910ZQgXlENQW-_:b-vy99v2) ([raw file](https://github.com/starkware-libs/sequencer/blob/a9beaf5018eda65920f2caf4e4e7485e3e314321/crates/blockifier/src/fee/fee_utils.rs#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`n_steps` is not a builtin, so we shouldn't really combine the steps with the `fold` below; I used another `u128::max` explicitly, WDYT?
</blockquote></details>

nvm, used `chain` instead

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/971)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @amosStarkware and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/971#-O7UCyPW4CIbkPT8n52C:-O7UWCX2Dwq_zqSNU_XM:b-vwgwbe) ([raw file](https://github.com/starkware-libs/sequencer/blob/a9beaf5018eda65920f2caf4e4e7485e3e314321/crates/blockifier/src/fee/fee_utils.rs#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

nvm, used `chain` instead
</blockquote></details>

explanation: split iteration into parts:
1. collect (cost, usage) pairs for each builtin
2. add (step_cost, step_usage) (cairo steps aren't builtins)
3. map each pair to the product (total cost of usage), rounded up
4. take `max` of all values

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/971)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/971#-O7XmCkpDC8KhIHPBcFI:-O7XmCkpDC8KhIHPBcFJ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/fafc3e75bce16b7ef046bc491a5cc1fcdc9d6345/crates/blockifier/src/fee/fee_utils.rs#L44)):*
> ```XML
>     // TODO(Yoni, 1/7/2024): rename vm -> cairo.
>     let vm_resource_fee_costs = versioned_constants.vm_resource_fee_cost();
>     let vm_resource_usage_for_fee = vm_resource_usage.prover_builtins();
> ```





_Suggestion:_
```XML
    let builtin_usage_for_fee = vm_resource_usage.prover_builtins();
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 46 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/971#-O7XmeVz6kBWSlx6mHDZ:-O7XmeW-5vj-3BcfQRrw:b-ml86q0) ([raw file](https://github.com/starkware-libs/sequencer/blob/fafc3e75bce16b7ef046bc491a5cc1fcdc9d6345/crates/blockifier/src/fee/fee_utils.rs#L46)):*
> ```XML
>     let vm_resource_usage_for_fee = vm_resource_usage.prover_builtins();
> 
>     // Validate used Cairo resources.
> ```

I assume we don't need to validate the `n_steps` resource



_Suggestion:_
```XML
    // Validate used builtin resources.
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/971#-O7XjbR11u1EmmtCBwpz:-O7XjbR11u1EmmtCBwq-:bepr82w) ([raw file](https://github.com/starkware-libs/sequencer/blob/fafc3e75bce16b7ef046bc491a5cc1fcdc9d6345/crates/blockifier/src/fee/fee_utils.rs#L52)):*
> ```XML
>         "{:#?} should contain {:#?}",
>         vm_resource_fee_costs.builtins.keys(),
>         vm_resource_usage_for_fee.keys(),
> ```

Define variables?



_Code quote:_
```XML
        vm_resource_fee_costs.builtins.keys(),
        vm_resource_usage_for_fee.keys(),
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/971#-O7Xmu5Y0PkI055uWWhz:-O7Xmu5Y0PkI055uWWi-:b-j0evra) ([raw file](https://github.com/starkware-libs/sequencer/blob/fafc3e75bce16b7ef046bc491a5cc1fcdc9d6345/crates/blockifier/src/fee/fee_utils.rs#L55)):*
> ```XML
>     );
> 
>     // Convert Cairo builtin usage to L1 gas usage.
> ```

No? Because you consider the `n_steps` here



_Suggestion:_
```XML
    // Convert Cairo usage to L1 gas usage.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/971)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/971#-O7XmCkpDC8KhIHPBcFI:-O7Y-UNCAQFTEt8YKUtb:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fafc3e75bce16b7ef046bc491a5cc1fcdc9d6345/crates/blockifier/src/fee/fee_utils.rs#L44)):*
> ```XML
>     // TODO(Yoni, 1/7/2024): rename vm -> cairo.
>     let vm_resource_fee_costs = versioned_constants.vm_resource_fee_cost();
>     let vm_resource_usage_for_fee = vm_resource_usage.prover_builtins();
> ```

Done.
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/971#-O7XjbR11u1EmmtCBwpz:-O7Y-rdj8bUAUp_jNW4_:b-6orgk6) ([raw file](https://github.com/starkware-libs/sequencer/blob/fafc3e75bce16b7ef046bc491a5cc1fcdc9d6345/crates/blockifier/src/fee/fee_utils.rs#L52)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Define variables?
</blockquote></details>

I will need to clone them if I define them... WDYT?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/971)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/971#-O7XjbR11u1EmmtCBwpz:-O7YHBZg24anmO-GZJdn:b-ns7y9q) ([raw file](https://github.com/starkware-libs/sequencer/blob/fafc3e75bce16b7ef046bc491a5cc1fcdc9d6345/crates/blockifier/src/fee/fee_utils.rs#L52)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I will need to clone them if I define them... WDYT?
</blockquote></details>

nvm, did it without cloning

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/971)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/971#-O7YJK_R1mKIOChaAEJf:-O7YJK_R1mKIOChaAEJg:b-2ykbke) (no related file):*
[py side](https://reviewable.io/reviews/starkware-industries/starkware/35979)

___

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/971#-:-O7Yb_pM9vaLKUxIg04L:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

**Pull request merged**
