### PR TITLE
chore(cairo_native): allow disabling native compilation in the contract class manager

### PR DESCRIPTION
**Pull request by avi-starkware**

### CODE REVIEW

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2703)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2703#-OEFH_bK1zlfa_xZwEaG:-OEFH_bK1zlfa_xZwEaH:bt0qixo) ([raw file](https://github.com/starkware-libs/sequencer/blob/49520e251f9ea788bb2ba12d13bae2eac072a0ee/crates/blockifier/src/state/contract_class_manager.rs#L103)):*
> ```XML
>     pub fn set_casm(&self, class_hash: ClassHash, compiled_class: RunnableCompiledClass) {
>         self.contract_caches.set_casm(class_hash, compiled_class);
>     }
> ```

Why do we need the set casm function?



_Code quote:_
```XML
    /// Sets the casm compiled class for the given class hash in the cache.
    pub fn set_casm(&self, class_hash: ClassHash, compiled_class: RunnableCompiledClass) {
        self.contract_caches.set_casm(class_hash, compiled_class);
    }
```

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2703)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2703)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware)

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2703)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2703#-OEFH_bK1zlfa_xZwEaG:-OEItAZq1zloWiuoTWnR:bbpssso) ([raw file](https://github.com/starkware-libs/sequencer/blob/49520e251f9ea788bb2ba12d13bae2eac072a0ee/crates/blockifier/src/state/contract_class_manager.rs#L103)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why do we need the set casm function?
</blockquote></details>

When just getting the casm and not using sierra to native compilation (e.g., when using cairo 0, or when native compilation is disabled).

We need to be able to use the casm cache directly as a normal cache - setting the value obtained from the state when it couldn't be found in cache.

**Pull request merged**
