### PR TITLE
fix(infra): resolve build script issues in starknet_sierra_compile

### PR DESCRIPTION
**Pull request by avi-starkware**

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2207)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @avi-starkware)

___
*[`crates/starknet_sierra_compile/build.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCCvYrt4oIBfsrk_-iN:-OCCvYru3W_M9KqrOZqk:bfr8pez) ([raw file](https://github.com/starkware-libs/sequencer/blob/a2ce070f18b1b4e36457f3a6a82170fb9cf3f4bc/crates/starknet_sierra_compile/build.rs#L88)):*
> ```XML
>     let out_dir =
>         Path::new(&env::var("OUT_DIR").expect("Failed to get the OUT_DIR environment variable"))
>             .to_path_buf();
> ```

Please see comments in slack.



_Code quote:_
```XML
    let out_dir =
        Path::new(&env::var("OUT_DIR").expect("Failed to get the OUT_DIR environment variable"))
            .to_path_buf();
```

**Comment by avi-starkware** [comment]
*[`crates/starknet_sierra_compile/build.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCCvYrt4oIBfsrk_-iN:-OCDfqshCbDF1bYhC03_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a2ce070f18b1b4e36457f3a6a82170fb9cf3f4bc/crates/starknet_sierra_compile/build.rs#L88)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please see comments in slack.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2207)* status: 0 of 8 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware and @avi-starkware)

___
*[`crates/starknet_sierra_compile/build.rs` line 4 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDu-4v6wFzjjhjnka8:-OCDu-4v6wFzjjhjnka9:b-pc2u9w) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/starknet_sierra_compile/build.rs#L4)):*
> ```XML
> use std::process::Command;
> 
> use infra_utils::path::resolve_project_relative_path;
> ```

Is this supposed to be ` runtime_path_of_project_root` instead?



_Code quote:_
```XML
resolve_project_relative_path;
```
___
*[`crates/starknet_sierra_compile/build.rs` line 50 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDu818DoFBJN6MdwtF:-OCDu819CSX0abdLXlXh:bvbmc70) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/starknet_sierra_compile/build.rs#L50)):*
> ```XML
>     // Set the runtime library path. This is required for Cairo native compilation.
>     let runtime_library_path = resolve_project_relative_path(
>         "crates/blockifier/cairo_native/target/release/libcairo_native_runtime.a",
> ```

Can/should this be a constant as well?



_Code quote:_
```XML
"crates/blockifier/cairo_native/target/release/libcairo_native_runtime.a"
```
___
*[`crates/starknet_sierra_compile/build.rs` line 59 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDuFA6Ax0hpklWxC-4:-OCDuFA6Ax0hpklWxC-5:bvbmc70) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/starknet_sierra_compile/build.rs#L59)):*
> ```XML
> 
>     let starknet_native_compile_crate_path =
>         project_root_path().join("crates/bin").join(binary_name);
> ```

Can/should this be a constant as well?



_Code quote:_
```XML
"crates/bin"
```
___
*[`crates/starknet_sierra_compile/build.rs` line 94 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDv9RD2dgznNc5Gjkv:-OCDv9RD2dgznNc5Gjkw:bc4wkwa) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/starknet_sierra_compile/build.rs#L94)):*
> ```XML
>         Path::new(&env::var("OUT_DIR").expect("Failed to get the OUT_DIR environment variable"))
>             .to_path_buf();
>     let temp_cargo_path = out_dir.join("cargo");
> ```

Not for this pr, but you should use `TempDir`. Add a todo please.



_Code quote:_
```XML
 let temp_cargo_path = out_dir.join("cargo");
```
___
*[`crates/starknet_sierra_compile/build.rs` line 94 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDvTue4Ak0_2LJ_d7e:-OCDvTue4Ak0_2LJ_d7f:bcob4i0) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/starknet_sierra_compile/build.rs#L94)):*
> ```XML
>         Path::new(&env::var("OUT_DIR").expect("Failed to get the OUT_DIR environment variable"))
>             .to_path_buf();
>     let temp_cargo_path = out_dir.join("cargo");
> ```

Can this be simply `temp_dir`? Is this related to `cargo`? Or just used as the output dir of `cargo install`?



_Code quote:_
```XML
temp_cargo_path
```
___
*[`crates/starknet_sierra_compile/build.rs` line 95 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDu_0L7lvidbuBXj5m:-OCDu_0L7lvidbuBXj5n:bw97n84) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/starknet_sierra_compile/build.rs#L95)):*
> ```XML
>             .to_path_buf();
>     let temp_cargo_path = out_dir.join("cargo");
>     let post_install_file_path = temp_cargo_path.join("bin").join(binary_name);
> ```

This is the same `bin` as in the previous use of `crates/bin`, right? Could you please unify these, e.g., define two constants and concat when releant?



_Code quote:_
```XML
"bin"
```
___
*[`crates/starknet_sierra_compile/build.rs` line 113 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDvmo18ZblxQvBEkTv:-OCDvmo18ZblxQvBEkTw:b-sw8t4c) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/starknet_sierra_compile/build.rs#L113)):*
> ```XML
>     }
> 
>     // Move the 'starknet-sierra-compile' executable to a shared location
> ```

The comment sould be `'{binary_name}'`, no? As this can be the other exec?



_Code quote:_
```XML
'starknet-sierra-compile'
```
___
*[`crates/infra_utils/src/path.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDwhA07jrDHCli6-nE:-OCDwhA07jrDHCli6-nF:b-5v5efd) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/infra_utils/src/path.rs#L43)):*
> ```XML
>         .nth(4)
>         .expect("Failed to navigate up four levels from the executable")
>         .to_path_buf()
> ```

IIUC this is an equivalent of `path_of_project_root()`.
Could these be unified such that if one fails the other implementation is used?
E.g.,
1. check manifest dir env, if set, use it
2. if not, use env::current_dir()
3. if not, use env::current_exe()


Does this make sense?



_Code quote:_
```XML
    env::current_exe()
        .expect("Failed to get current executable path")
        .ancestors()
        .nth(4)
        .expect("Failed to navigate up four levels from the executable")
        .to_path_buf()
```
___
*[`crates/infra_utils/src/path.rs` line 44 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDtQeE3-TD856PPYeb:-OCDtQeE3-TD856PPYec:bdvwc7h) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/infra_utils/src/path.rs#L44)):*
> ```XML
>         .expect("Failed to navigate up four levels from the executable")
>         .to_path_buf()
> }
> ```

This assumes the executable is in `crates/<crate name>/src/bin/<exe name>`, right? Could you please mention this explicitly in the doc?



_Code quote:_
```XML
fn runtime_path_of_project_root() -> PathBuf {
    env::current_exe()
        .expect("Failed to get current executable path")
        .ancestors()
        .nth(4)
        .expect("Failed to navigate up four levels from the executable")
        .to_path_buf()
}
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2207)* status: 0 of 8 files reviewed, 10 unresolved discussions (waiting on @ArniStarkware and @avi-starkware)

___
*[`crates/starknet_sierra_compile/src/path_constants.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDy-MHC4UI86O-mcnx:-OCDy-MI3fRliklWOJZM:bsidjs0) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/starknet_sierra_compile/src/path_constants.rs#L9)):*
> ```XML
> pub fn project_root_path() -> PathBuf {
>     Path::new(env!("CARGO_MANIFEST_DIR")).join("../..").to_path_buf()
> }
> ```

Please move to `infra_utils` / unify with the other function there. Also please add documentation.



_Code quote:_
```XML
pub fn project_root_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..").to_path_buf()
}
```

**Comment by avi-starkware** [comment]
*[`crates/infra_utils/src/path.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDwhA07jrDHCli6-nE:-OCDz76D7XPrrtKksmXD:b-mzj9pd) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/infra_utils/src/path.rs#L43)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

IIUC this is an equivalent of `path_of_project_root()`.
Could these be unified such that if one fails the other implementation is used?
E.g.,
1. check manifest dir env, if set, use it
2. if not, use env::current_dir()
3. if not, use env::current_exe()


Does this make sense?
</blockquote></details>

`env::current_dir()` can yield unexpected results since using `env::set_current_dir()` changes the current dir to an arbitrary path (see [here](https://github.com/starkware-libs/sequencer/blob/0459bde67b5656b76a594152946c7c3b62ac3263/crates/starknet_sierra_compile/src/compile_test.rs#L29))

**Comment by avi-starkware** [comment]
*[`crates/infra_utils/src/path.rs` line 44 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDtQeE3-TD856PPYeb:-OCE-OgH1w8sL6OYpX95:b3hyqdb) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/infra_utils/src/path.rs#L44)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

This assumes the executable is in `crates/<crate name>/src/bin/<exe name>`, right? Could you please mention this explicitly in the doc?
</blockquote></details>

Actually it is something like this:
```
target/debug/build/starknet_sierra_compile-9e2f5d061515dbd0/
```
(I think this is the path in `OUT_DIR`)

The bin dir you mentioned just holds the rust files for the binaries. Not the binaries themselves.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2207)* status: 0 of 8 files reviewed, 10 unresolved discussions (waiting on @ArniStarkware and @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sierra_compile/build.rs` line 4 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDu-4v6wFzjjhjnka8:-OCoK0Xh8XxpKtNU0g3V:b-59olbc) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/starknet_sierra_compile/build.rs#L4)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Is this supposed to be ` runtime_path_of_project_root` instead?
</blockquote></details>

No. I made a runtime version for resolving relative paths to be used outside `build.rs`
___
*[`crates/starknet_sierra_compile/build.rs` line 50 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDu818DoFBJN6MdwtF:-OCoG-H5BoRKrMZ6ElOs:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/starknet_sierra_compile/build.rs#L50)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can/should this be a constant as well?
</blockquote></details>

Done.
___
*[`crates/starknet_sierra_compile/build.rs` line 59 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDuFA6Ax0hpklWxC-4:-OCoG-gZ17ImGLHlhWXN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/starknet_sierra_compile/build.rs#L59)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can/should this be a constant as well?
</blockquote></details>

Done.
___
*[`crates/starknet_sierra_compile/build.rs` line 94 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDv9RD2dgznNc5Gjkv:-OCoQRs_CKY28JntQxfB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/starknet_sierra_compile/build.rs#L94)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Not for this pr, but you should use `TempDir`. Add a todo please.
</blockquote></details>

Done.
___
*[`crates/starknet_sierra_compile/build.rs` line 94 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDvTue4Ak0_2LJ_d7e:-OCoQT2b2Qtyrdq9t91k:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/starknet_sierra_compile/build.rs#L94)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can this be simply `temp_dir`? Is this related to `cargo`? Or just used as the output dir of `cargo install`?
</blockquote></details>

Done.
___
*[`crates/starknet_sierra_compile/build.rs` line 95 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDu_0L7lvidbuBXj5m:-OCoQVG175d3W97Yx_Ic:b-si0dv2) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/starknet_sierra_compile/build.rs#L95)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

This is the same `bin` as in the previous use of `crates/bin`, right? Could you please unify these, e.g., define two constants and concat when releant?
</blockquote></details>

This is unrelated to the `crates/bin` path I put the `starknet-native-compile` crate in. This `bin` folder is just a default folder that gets created inside the folder in the `--root` argument of cargo install.
___
*[`crates/starknet_sierra_compile/build.rs` line 113 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDvmo18ZblxQvBEkTv:-OCoJeiE3ohdjNXEQ3rM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/starknet_sierra_compile/build.rs#L113)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

The comment sould be `'{binary_name}'`, no? As this can be the other exec?
</blockquote></details>

Done.
___
*[`crates/starknet_sierra_compile/src/path_constants.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2207#-OCDy-MHC4UI86O-mcnx:-OCoL98C5ZFrSWgTIQbA:b-mt071n) ([raw file](https://github.com/starkware-libs/sequencer/blob/41b1dbe54955d9cb370ccf1f0e4bbcfb484fca74/crates/starknet_sierra_compile/src/path_constants.rs#L9)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please move to `infra_utils` / unify with the other function there. Also please add documentation.
</blockquote></details>

Done.

Removed.

**Pull request closed without merging**
