### PR TITLE
feat(starknet_api): remove Ord and PartialOrd from TransactionVersion, implement explicit cmp

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
…, implement explicit cmp functions

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1638)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1638#-OAJpr3-7iBnnnAxNWjR:-OAJpr305fCoMFzN8Rg0:b-m15ern) (no related file):*
Also removed many `Ord, PartialOrd` derives; the objects they were derived on don't seem to have a natural order. Unclear why these derives were needed...

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1638)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/starknet_api/src/transaction.rs` line 862 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1638#-OAJqoYF2s7dClG-YAe3:-OAJqoYF2s7dClG-YAe4:b-gozilz) ([raw file](https://github.com/starkware-libs/sequencer/blob/33ecad360c75b90c04e62af1be39e053c0664a51/crates/starknet_api/src/transaction.rs#L862)):*
> ```XML
> 
>     pub fn base_lt(&self, other: &Self) -> bool {
>         self.without_query_bit().0 < other.without_query_bit().0
> ```

I can do `self.base_le(other) && self.without_query_bit() != other.without_query_bit()` but that would be 4 conversions instead of 2



_Code quote:_
```XML
self.without_query_bit().0 < other.without_query_bit().0
```

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1638#-:-OAM6TM_EHojehT55T-O:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by giladchase — CHANGES_REQUESTED** [review]
Note: this is a breaking change that might disrupt users who relied on the partialord behavior (like we did).
Can you involve product.

If this gets the OK, I still think it should be separated into two PRs, one removing unused derived and removing used derives with a replacement that explains why that order was chosen.

> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1638#-:-OAMAjYU3bZIDi23AFty:b6hjerx)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1638#-OAJpr3-7iBnnnAxNWjR:-OAMCONcEkR1DIa6SsmN:b-wvpagz) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Also removed many `Ord, PartialOrd` derives; the objects they were derived on don't seem to have a natural order. Unclear why these derives were needed...
</blockquote></details>

Orphan rule + legacy, if we don't implement PartialOrd/Ord then no-one can (except via newtypes), somebody probably added these all over SNAPI without thinking too much on whether or not it makes sense.
But you are right about the natural order.

___
___
*[`crates/starknet_api/src/transaction.rs` line 854 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1638#-OAMB_M528CwMcO6-Abz:-OAMB_M528CwMcO6-Ac-:b-4mgitw) ([raw file](https://github.com/starkware-libs/sequencer/blob/fdb006585765bcadea38748884e9b1d945d278d7/crates/starknet_api/src/transaction.rs#L854)):*
> ```XML
>         let mut self_biguint = self.0.to_biguint();
>         self_biguint.set_bit(QUERY_VERSION_BASE_BIT.into(), false);
>         Self(self_biguint.into())
> ```

Seems to expensive for `cmp`, biguint is a Vec, can this done on the stack?
Also can you explain what `base` here means and about the query_version_base_bit?



_Code quote:_
```XML
        let mut self_biguint = self.0.to_biguint();
        self_biguint.set_bit(QUERY_VERSION_BASE_BIT.into(), false);
        Self(self_biguint.into())
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1638)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/starknet_api/src/transaction.rs` line 862 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1638#-OAJqoYF2s7dClG-YAe3:-OAMCjod8W5nA3B3GY8I:bal7n9p) ([raw file](https://github.com/starkware-libs/sequencer/blob/33ecad360c75b90c04e62af1be39e053c0664a51/crates/starknet_api/src/transaction.rs#L862)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I can do `self.base_le(other) && self.without_query_bit() != other.without_query_bit()` but that would be 4 conversions instead of 2
</blockquote></details>

Conversions aren't the issue, this allocates two vectors on the heap just to compare two fels

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1638)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1638#-OAMdQNi-6pkVYY4tHRB:-OAMdQNi-6pkVYY4tHRC:b-rxqhbm) (no related file):*
Closing this, and will implement a "natural" order on TransactionVersion (ZERO < ZERO_QUERY < ONE < ONE_QUERY ...)

___

**Pull request closed without merging**
