### PR TITLE
refactor: make external tests generic

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/140)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/140?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#140** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/140?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#133** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/133?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main-v0.13.2`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/140)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/external_test_utils.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/140#-O2xxy3E28NpdiCJGMIE:-O2xxy3E28NpdiCJGMIF:b-d8etzg) ([raw file](https://github.com/starkware-libs/sequencer/blob/0dc9be4bd09d2950a0665155c30a970e0241a036/crates/committer/src/patricia_merkle_tree/external_test_utils.rs#L73)):*
> ```XML
> where
>     TH: TreeHashFunction<L> + 'static,
>     L: Leaf + Sized + 'static,
> ```

isn't `Leaf` already `Sized`?



_Code quote:_
```XML
Leaf + Sized
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/140#-O2xyj7j-Fo06X8f0xdl:-O2xyj7j-Fo06X8f0xdm:b9z4ixn) ([raw file](https://github.com/starkware-libs/sequencer/blob/0dc9be4bd09d2950a0665155c30a970e0241a036/crates/committer_cli/src/tests/python_tests.rs#L202)):*
> ```XML
>                 // 2. Run the test.
>                 let output = single_tree_flow_test::<StarknetStorageValue, TreeHashFunctionImpl>(
>                     leaf_modifications.clone(),
> ```

`leaf_modifications` is an `Arc`, right?
if not, please create the config before the call to `single_tree_flow_test` so you won't have to clone it



_Code quote:_
```XML
leaf_modifications.clone()
```
___
*[`crates/committer_cli/src/tests/regression_tests.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/140#-O2xysAQ6wkQDW9DOZMj:-O2xysAQ6wkQDW9DOZMk:b-ia41wb) ([raw file](https://github.com/starkware-libs/sequencer/blob/0dc9be4bd09d2950a0665155c30a970e0241a036/crates/committer_cli/src/tests/regression_tests.rs#L112)):*
> ```XML
>     // Benchmark the single tree flow test.
>     let output = single_tree_flow_test::<StarknetStorageValue, TreeHashFunctionImpl>(
>         leaf_modifications.clone(),
> ```

same comment as above



_Code quote:_
```XML
leaf_modifications.clone(),
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/140)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/external_test_utils.rs` line 113 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/140#-O37AcCMB2s8ClARdlrw:-O37AcCMB2s8ClARdlrx:b-8jccm8) ([raw file](https://github.com/starkware-libs/sequencer/blob/451e594ed31761976196cd4ea7661904c0b385d3/crates/committer/src/patricia_merkle_tree/external_test_utils.rs#L113)):*
> ```XML
>         .iter()
>         .map(|(k, v)| (NodeIndex::FIRST_LEAF + *k, v.clone()))
>         .collect::<LeafModifications<L>>();
> ```

please revert this... clone in the calling site, not here



_Code quote:_
```XML
    leaf_modifications: &LeafModifications<L>,
    storage: MapStorage,
    root_hash: HashOutput,
    config: &impl OriginalSkeletonTreeConfig<L>,
) -> String {
    // Move from leaf number to actual index.
    let leaf_modifications = leaf_modifications
        .iter()
        .map(|(k, v)| (NodeIndex::FIRST_LEAF + *k, v.clone()))
        .collect::<LeafModifications<L>>();
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/140#-O2xyj7j-Fo06X8f0xdl:-O379o-A9UXT07OeaHM6:beuac3m) ([raw file](https://github.com/starkware-libs/sequencer/blob/0dc9be4bd09d2950a0665155c30a970e0241a036/crates/committer_cli/src/tests/python_tests.rs#L202)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

> Leaf_modifications in a hash_map.

then we *really* don't want a `clone()`!

> The binding happens in TreeFlowInput here

I am looking at the diff, and previously there was no `clone`, but there was still the `serde_json` call.

We shouldn't add a clone here...
</blockquote></details>

ok this is a test function... please doc that this clone is unfortunate but it's ok for testing

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/140)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer_cli/src/tests/python_tests.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/140#-O2xyj7j-Fo06X8f0xdl:-O37PYoi3fTqbvlEcZjP:b-b1ipce) ([raw file](https://github.com/starkware-libs/sequencer/blob/0dc9be4bd09d2950a0665155c30a970e0241a036/crates/committer_cli/src/tests/python_tests.rs#L202)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

> Leaf_modifications in a hash_map.

then we *really* don't want a `clone()`!

> The binding happens in TreeFlowInput here

I am looking at the diff, and previously there was no `clone`, but there was still the `serde_json` call.

We shouldn't add a clone here...
</blockquote></details>

The change is reverted, 
we are clone also in tests ( not benchmark ) 
Monday ticket is opened https://starkware.monday.com/boards/6987445459/pulses/7130997008
 for refactoring OriginalSkeletonTreeConfig

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/140#-:-O38I_VV9VJjrU-VJlzf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Comment by AvivYossef-starkware** [comment]
### Merge activity

* **Aug 4, 4:08 AM EDT**: @AvivYossef-starkware merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/140).

**Pull request merged**
