### PR TITLE
test(starknet_batcher): setup gas prices for testing

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2445?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2446** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2446?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2445** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2445?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2445?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2444** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2444?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2443** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2443?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2445)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/starknet_api/src/block.rs` line 456 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2445#-ODG7DQ3DWHulJeZwIF-:-ODG7DQ3DWHulJeZwIF0:b-d3pwz7) ([raw file](https://github.com/starkware-libs/sequencer/blob/11f3e059eff77ed3b378b17bdae4f623182ad1b5/crates/starknet_api/src/block.rs#L456)):*
> ```XML
> 
> // TODO(Arni): Remove derive of Default. Gas prices should always be set.
> #[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
> ```

I used this to compare the results. There is no need for this struct to implement these properties.



_Suggestion:_
```XML
#[derive(Clone, Debug, Default, Deserialize, Serialize)]
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2445)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/starknet_api/src/block.rs` line 456 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2445#-ODG7DQ3DWHulJeZwIF-:-ODG8B-i8jIjhrYHS16V:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/11f3e059eff77ed3b378b17bdae4f623182ad1b5/crates/starknet_api/src/block.rs#L456)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I used this to compare the results. There is no need for this struct to implement these properties.
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2445)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_api/src/test_utils.rs` line 138 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2445#-ODf5PUh7ozi3K4UBudI:-ODf5PUh7ozi3K4UBudJ:b24kuga) ([raw file](https://github.com/starkware-libs/sequencer/blob/f32d0987938f08db9aa15c71f951ae0bd700c408/crates/starknet_api/src/test_utils.rs#L138)):*
> ```XML
>     NonzeroGasPrice::new_unchecked(GasPrice(25 * u128::pow(10, 5)));
> pub const DEFAULT_STRK_L2_GAS_PRICE: NonzeroGasPrice =
>     NonzeroGasPrice::new_unchecked(GasPrice(25 * u128::pow(10, 5)));
> ```

This is a good place to use static lazy if you want them to match the default l1 price. 



_Code quote:_
```XML
pub const DEFAULT_ETH_L2_GAS_PRICE: NonzeroGasPrice =
    NonzeroGasPrice::new_unchecked(GasPrice(25 * u128::pow(10, 5)));
pub const DEFAULT_STRK_L2_GAS_PRICE: NonzeroGasPrice =
    NonzeroGasPrice::new_unchecked(GasPrice(25 * u128::pow(10, 5)));
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2445)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/starknet_api/src/test_utils.rs` line 138 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2445#-ODf5PUh7ozi3K4UBudI:-OEIXXT_5Xuvr1SsQG0v:bw8h3xm) ([raw file](https://github.com/starkware-libs/sequencer/blob/f32d0987938f08db9aa15c71f951ae0bd700c408/crates/starknet_api/src/test_utils.rs#L138)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This is a good place to use static lazy if you want them to match the default l1 price.
</blockquote></details>

1. There is no need to match them to the l1 gas price.
2. The mechanism that does the conversion is dependent on versioned constants, which are in the blockifier repo.
3. If we put `DEFAULT_ETH_L2_GAS_PRICE` and `DEFAULT_STRK_L2_GAS_PRICE` inside a lazy evaluation block of any type, we would have to do the same for `DEFAULT_GAS_PRICES`. As I said in item 1 of this list - there is no benefit to that.

**Review by alonh5 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2445)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2445)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Dec 18, 7:09 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2445).

**Pull request merged**
