### PR TITLE
chore: make `write_to_output_map` generic

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/453)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/453)* status: 0 of 8 files reviewed, 2 unresolved discussions

___
*[`crates/committer_cli/src/filled_tree_output/errors.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/453#-O4FaBk7Cwu3xWXUX9Jz:-O4FaBk7Cwu3xWXUX9K-:b-q018k0) ([raw file](https://github.com/starkware-libs/sequencer/blob/3bbc87d42e4714161aad33e94f4cfe7a2ff8f4bc/crates/committer_cli/src/filled_tree_output/errors.rs#L0)):*
I deleted types from this file and notice it wasn't actually needed
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/errors.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/453#-O4FbWh161Jpir7Y-NpC:-O4FbWh161Jpir7Y-NpD:bhr0g50) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d3638afd7ea61298af99284b463dad3b65125b0/crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/errors.rs#L12)):*
> ```XML
>     DeletedLeafInSkeleton(NodeIndex),
>     #[error("Double update at node {index:?}. Existing value: {existing_value_as_string:?}.")]
>     DoubleUpdate { index: NodeIndex, existing_value_as_string: String },
> ```

The generic arg `L` was only used here -> removing the use of `L` here required deleting it from `FilledTreeError`'s signature.



_Code quote:_
```XML
    #[error("Double update at node {index:?}. Existing value: {existing_value_as_string:?}.")]
    DoubleUpdate { index: NodeIndex, existing_value_as_string: String },
```

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/453#-:-O4FkUEbDwAGluU9gjIV:b-hz3kb8)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/453)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/453#-O4Fyvc6BzIA5jDt1IcW:-O4Fyvc6BzIA5jDt1IcX:b-tzx8yb) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d3638afd7ea61298af99284b463dad3b65125b0/crates/starknet_committer/src/forest/filled_forest.rs#L110)):*
> ```XML
>             Ok(classes_trie) => classes_trie,
>             Err(error) => return Err(ForestError::ClassesTrie(error)),
>         };
> ```

isn't a double-question-mark good enough here?
this may be why we needed the error types we had defined before...



_Suggestion:_
```XML
        let contracts_trie = match contracts_trie_task.await??;
        let classes_trie = match classes_trie_task.await??;
```
___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/453#-O4Fz1wa9p7FAJ6PM3mT:-O4Fz1wb5-035UJWms-Z:b-lc1gz8) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d3638afd7ea61298af99284b463dad3b65125b0/crates/starknet_committer/src/forest/filled_forest.rs#L130)):*
> ```XML
>             Ok(filled_storage_trie) => filled_storage_trie,
>             Err(e) => return Err(ForestError::StorageTrie(e)),
>         };
> ```

ditto on the double-question-mark comment



_Code quote:_
```XML
        let filled_storage_trie = match StorageTrie::create::<TH>(
            Arc::new(updated_storage_trie),
            Arc::new(inner_updates),
        )
        .await
        {
            Ok(filled_storage_trie) => filled_storage_trie,
            Err(e) => return Err(ForestError::StorageTrie(e)),
        };
```
___
*[`crates/starknet_committer/src/forest/forest_errors.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/453#-O4Fz8TF9fF7UMD2-PU1:-O4Fz8TF9fF7UMD2-PU2:b-q56b01) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d3638afd7ea61298af99284b463dad3b65125b0/crates/starknet_committer/src/forest/forest_errors.rs#L20)):*
> ```XML
>     ClassesTrie(#[source] FilledTreeError),
>     #[error("Couldn't create Contracts Trie: {0}")]
>     ContractsTrie(#[source] FilledTreeError),
> ```

this doesn't work?
no need for the text; the error variant encodes the type of tree



_Suggestion:_
```XML
    #[error(transparent)]
    ClassesTrie(#[source] FilledTreeError),
    #[error(transparent)]
    ContractsTrie(#[source] FilledTreeError),
```
___
*[`crates/starknet_committer/src/forest/forest_errors.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/453#-O4FzFE_8_Q3XkEY4vI6:-O4FzFE_8_Q3XkEY4vI7:b-5qlfag) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d3638afd7ea61298af99284b463dad3b65125b0/crates/starknet_committer/src/forest/forest_errors.rs#L38)):*
> ```XML
>     JoinError(#[from] JoinError),
>     #[error("Couldn't create Storage Trie: {0}")]
>     StorageTrie(#[source] FilledTreeError),
> ```

ditto on the `transparent` comment



_Code quote:_
```XML
    #[error("Couldn't create Storage Trie: {0}")]
    StorageTrie(#[source] FilledTreeError),
```
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/errors.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/453#-O4FbWh161Jpir7Y-NpC:-O4FzhNB-Kfv-7hQvZXP:b-7m74ox) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d3638afd7ea61298af99284b463dad3b65125b0/crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/errors.rs#L12)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

The generic arg `L` was only used here -> removing the use of `L` here required deleting it from `FilledTreeError`'s signature.
</blockquote></details>

nice!

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/453)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/453#-O4Fyvc6BzIA5jDt1IcW:-O4JuMrF97oCbRx5IfsB:bj8fv3u) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d3638afd7ea61298af99284b463dad3b65125b0/crates/starknet_committer/src/forest/filled_forest.rs#L110)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

isn't a double-question-mark good enough here?
this may be why we needed the error types we had defined before...
</blockquote></details>

It's not good enough, because `FilledTreeError` doesn't have a generic argument anymore, and since we have three (in the next PRs we'll also delete `FilledTreeError::StorageTrie`)`FilledTreeError` variants, the compiler needs us to tell it which variant to use.
I'm not sure what you mean? 
___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/453#-O4Fz1wa9p7FAJ6PM3mT:-O4JvHbz3y_FQeIiqXKf:b-7ropln) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d3638afd7ea61298af99284b463dad3b65125b0/crates/starknet_committer/src/forest/filled_forest.rs#L130)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto on the double-question-mark comment
</blockquote></details>

ditto
___
*[`crates/starknet_committer/src/forest/forest_errors.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/453#-O4Fz8TF9fF7UMD2-PU1:-O4JvCv6Ar72KiJTTOuv:bcmodj3) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d3638afd7ea61298af99284b463dad3b65125b0/crates/starknet_committer/src/forest/forest_errors.rs#L20)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this doesn't work?
no need for the text; the error variant encodes the type of tree
</blockquote></details>

It doesn't work
___
*[`crates/starknet_committer/src/forest/forest_errors.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/453#-O4FzFE_8_Q3XkEY4vI6:-O4JvGJF568J-UpnBObK:b-7ropln) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d3638afd7ea61298af99284b463dad3b65125b0/crates/starknet_committer/src/forest/forest_errors.rs#L38)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto on the `transparent` comment
</blockquote></details>

ditto

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/453)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/453#-O4KAcljBtdeLHFFA30q:-O4KAcljBtdeLHFFA30r:b-j7iynv) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d3638afd7ea61298af99284b463dad3b65125b0/crates/starknet_committer/src/forest/filled_forest.rs#L110)):*
> ```XML
>             Ok(classes_trie) => classes_trie,
>             Err(error) => return Err(ForestError::ClassesTrie(error)),
>         };
> ```

ok, then does this (or some other usage of `map_err`) work?



_Suggestion:_
```XML
        let contracts_trie = match contracts_trie_task.await?.map_err(ForestError::ContractsTrie);
        let classes_trie = match classes_trie_task.await?.map_err(ForestError::ClassesTrie);
```
___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/453#-O4Fz1wa9p7FAJ6PM3mT:-O4KAsM153d5g-D98jSC:bexjw2w) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d3638afd7ea61298af99284b463dad3b65125b0/crates/starknet_committer/src/forest/filled_forest.rs#L130)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto on the `map_err` comment

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/453)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/453#-O4KAcljBtdeLHFFA30q:-O4KKNdEDLxbOcfNeXCS:b-iry7x8) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d3638afd7ea61298af99284b463dad3b65125b0/crates/starknet_committer/src/forest/filled_forest.rs#L110)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ok, then does this (or some other usage of `map_err`) work?
</blockquote></details>

Done, thanks
___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/453#-O4Fz1wa9p7FAJ6PM3mT:-O4KKRkj9_Pomc-5n-9r:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d3638afd7ea61298af99284b463dad3b65125b0/crates/starknet_committer/src/forest/filled_forest.rs#L130)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto on the `map_err` comment
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/453#-:-O4Kb_P073lqnB2A_2oU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
