### PR TITLE
feat(blockifier): add library_call cairo native syscall

### PR DESCRIPTION
**Pull request by PearsonWhite**
Implements `library_call` in the `NativeSyscallHandler`.

### CODE REVIEW

**Review by PearsonWhite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: 0 of 2 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OA4QoOv8VKQLrKREg3B:-OA4QoOv8VKQLrKREg3C:bv8kmlm) (no related file):*
`test_nested_library_call` fails due to a difference in `ExecutionResources` when comparing the CallInfo to the expected. The expected CallInfo is the same between the VM and Native. Eventually, these should be the same (right?), but for now it fails. How would you like me to address this? I could change the test to ignore `ExecutionResources` in the comparison for now, or mark the test as `#[ignored]`

___

**Review by varex83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @PearsonWhite)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OA4QoOv8VKQLrKREg3B:-OAHxR5iAGHk_U2Y-aw-:b-snycpa) (no related file):*
<details><summary><i>Previously, PearsonWhite wrote…</i></summary><blockquote>

`test_nested_library_call` fails due to a difference in `ExecutionResources` when comparing the CallInfo to the expected. The expected CallInfo is the same between the VM and Native. Eventually, these should be the same (right?), but for now it fails. How would you like me to address this? I could change the test to ignore `ExecutionResources` in the comparison for now, or mark the test as `#[ignored]`
</blockquote></details>

I think we can just ignore ExecutionResources check while running Native test

___

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1, @PearsonWhite, and @varex83)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OAULlLM4p8YKeb4JJ-P:-OAULlLM4p8YKeb4JJ-Q:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ec1f46a757bbd8284cd865880fa59a2982d06e3/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L115)):*
> ```XML
>     #[cfg_attr(not(feature = "cairo_native"), allow(unused_variables))]
>     fn if_native<T>(test_contract: &FeatureContract) -> impl Fn(T, T) -> T + '_ {
>         move |native: T, non_native: T| {
> ```





_Suggestion:_
```XML
move |native_value: T, non_native_value: T| {
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 217 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OAUNm11AGWmHM6E6eha:-OAUNm126lvojB-tp3dO:bv2e5fg) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ec1f46a757bbd8284cd865880fa59a2982d06e3/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L217)):*
> ```XML
>             ..CallExecution::default()
>         },
>         resources: first_storage_entry_point_resources,
> ```

What creates the difference here? Why does the native need the first storage entry point for the nested storage call info while the VM does not? 



_Code quote:_
```XML
resources: first_storage_entry_point_resources,
```

**Review by PearsonWhite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @meship-starkware, @noaov1, and @varex83)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 217 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OAUNm11AGWmHM6E6eha:-OAh5xy359gHNB5XAKKD:b-nr2n79) ([raw file](https://github.com/starkware-libs/sequencer/blob/0ec1f46a757bbd8284cd865880fa59a2982d06e3/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L217)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

What creates the difference here? Why does the native need the first storage entry point for the nested storage call info while the VM does not?
</blockquote></details>

n_steps appears to be cumulative.
The `n_steps` for the outer call `test_library_call` is `1022`
The `n_steps` for the inner call `test_storage_read_write` is `180`
The next `test_storage_read_write` is `1202` (1022+180).
And if we were to continue calling `test_storage_read_write`, in `crates/blockifier/feature_contracts/cairo_native/test_contract.cairo`, we would get
n_steps: 1382, 1562, 1742, 1922,... each value 180 greater than the last.

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @varex83)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1, @PearsonWhite, and @varex83)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OAvjZv8AbWDkSOeRYgD:-OAvjZv8AbWDkSOeRYgE:b-7zi8tj) ([raw file](https://github.com/starkware-libs/sequencer/blob/410a9dca7537bfb90d92c13f95f81c51464cacba/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L111)):*
> ```XML
>     // Todo(pwhite) 2024/10/28: Execution resources from the VM & Native are mesaured differently
>     // helper function to change the expected resource values from both of executions
>     // When gas is changed to be the same between VM and Native this should be removed.
> ```

WDYM?



_Code quote:_
```XML
    // Todo(pwhite) 2024/10/28: Execution resources from the VM & Native are mesaured differently
    // helper function to change the expected resource values from both of executions
    // When gas is changed to be the same between VM and Native this should be removed.
```

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware, @noaov1, @PearsonWhite, and @varex83)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 150 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OB1cVkS6t-83g2mEAf8:-OB1cVkS6t-83g2mEAf9:b-8aotxq) ([raw file](https://github.com/starkware-libs/sequencer/blob/410a9dca7537bfb90d92c13f95f81c51464cacba/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L150)):*
> ```XML
>         calldata: main_entry_point_calldata,
>         class_hash: Some(test_class_hash),
>         initial_gas: if_native(&test_contract)(9999584180, 9999292440),
> ```

Why do all the "non-native-value" numbers change as well? (In all calls to `if_native`)



_Code quote:_
```XML
        initial_gas: if_native(&test_contract)(9999584180, 9999292440),
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 186 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OB4iQRD4R2X8u8uxRnX:-OB4iQRD4R2X8u8uxRnY:b-iieoz1) ([raw file](https://github.com/starkware-libs/sequencer/blob/410a9dca7537bfb90d92c13f95f81c51464cacba/crates/blockifier/src/execution/native/syscall_handler.rs#L186)):*
> ```XML
>             class_hash: Some(class_hash),
>             code_address: None,
>             entry_point_type: EntryPointType::External,
> ```

In the [VM implementation](https://github.com/starkware-libs/sequencer/blob/e786639a78ea0db3aca1a0107080a26447793de4/crates/blockifier/src/execution/syscalls/hint_processor.rs#L850-L851) we support `EntryPointType::L1Handler` here as well. Is that planned to be added later?



_Code quote:_
```XML
            entry_point_type: EntryPointType::External,
```

**Review by PearsonWhite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @noaov1, and @varex83)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OAvjZv8AbWDkSOeRYgD:-OB8YOmo1G1Q7AP4uVX9:b-6pdcp1) ([raw file](https://github.com/starkware-libs/sequencer/blob/410a9dca7537bfb90d92c13f95f81c51464cacba/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L111)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

For now, we need different execution resources between VM and Native in our tests. Ideally, the resources would be the same between the two, and if that is the case in the future, the helper function will no longer be nessesary.
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 150 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OB1cVkS6t-83g2mEAf8:-OB8XrrZ9np4EoFeiHc-:bd0iwcb) ([raw file](https://github.com/starkware-libs/sequencer/blob/410a9dca7537bfb90d92c13f95f81c51464cacba/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L150)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Why do all the "non-native-value" numbers change as well? (In all calls to `if_native`)
</blockquote></details>

Fixed. Gas values for VM should now match what they were.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @PearsonWhite, and @varex83)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 186 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OB4iQRD4R2X8u8uxRnX:-OBA2M1KEL7cHibdHb8T:b-3z4qyd) ([raw file](https://github.com/starkware-libs/sequencer/blob/410a9dca7537bfb90d92c13f95f81c51464cacba/crates/blockifier/src/execution/native/syscall_handler.rs#L186)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

In the [VM implementation](https://github.com/starkware-libs/sequencer/blob/e786639a78ea0db3aca1a0107080a26447793de4/crates/blockifier/src/execution/syscalls/hint_processor.rs#L850-L851) we support `EntryPointType::L1Handler` here as well. Is that planned to be added later?
</blockquote></details>

In the library call syscall we always set it to `External`. In the deprecated syscall `library_call_l1_handler` we set it to `EntryPointType::L1Handler`. 
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OAvjZv8AbWDkSOeRYgD:-OBA60o0A9y9-y1EFZZ3:bqcwq8p) ([raw file](https://github.com/starkware-libs/sequencer/blob/410a9dca7537bfb90d92c13f95f81c51464cacba/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L111)):*
<details><summary><i>Previously, PearsonWhite wrote…</i></summary><blockquote>

For now, we need different execution resources between VM and Native in our tests. Ideally, the resources would be the same between the two, and if that is the case in the future, the helper function will no longer be nessesary.
</blockquote></details>

Why? Both should have the sierra gas, no?
The initial gas should be identical.
The vm resources should eventuallt also be identical (WIP)
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 197 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OBA3dk306Pe30wTXN1T:-OBA3dk306Pe30wTXN1U:b-ociw2s) ([raw file](https://github.com/starkware-libs/sequencer/blob/a852db05f1587df24025eef4f2ad8e0d9e70b6b9/crates/blockifier/src/execution/native/syscall_handler.rs#L197)):*
> ```XML
>         };
> 
>         Ok(self.execute_inner_call(entry_point, remaining_gas)?.0)
> ```

Consider changing the return type of `execute_inner_call` to `Vec<Felt>`. 



_Code quote:_
```XML
Ok(self.execute_inner_call(entry_point, remaining_gas)?.0)
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 188 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OBBFMLTCAfTJ8StNju6:-OBBFMLTCAfTJ8StNju7:byda5ec) ([raw file](https://github.com/starkware-libs/sequencer/blob/b22f19f4069f53bbfc409842a5b2b8f51cbc3fc4/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L188)):*
> ```XML
>             n_memory_holes: 0,
>             builtin_instance_counter: HashMap::from([(BuiltinName::range_check, 2)]),
>         },
> ```

How come the native execution has a non-default vm resources? :thinking: 



_Code quote:_
```XML
        ExecutionResources {
            n_steps: 180,
            n_memory_holes: 0,
            builtin_instance_counter: HashMap::from([(BuiltinName::range_check, 2)]),
        },
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 201 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OBBEQbn98UqMz7D6zCA:-OBBEQbo4439K93mb3YL:b-owtadl) ([raw file](https://github.com/starkware-libs/sequencer/blob/b22f19f4069f53bbfc409842a5b2b8f51cbc3fc4/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L201)):*
> ```XML
>             builtin_instance_counter: HashMap::from([(BuiltinName::range_check, 19)]),
>         },
>         first_storage_entry_point_resources.clone(),
> ```

Can you please explain?
Why is `the storage_entry_point_resources` non-native value depends on the native case?



_Code quote:_
```XML
        first_storage_entry_point_resources.clone(),
```

**Review by PearsonWhite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @noaov1, and @varex83)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 186 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OB4iQRD4R2X8u8uxRnX:-OBBSLEq4zVaRFQIY_jT:b3lq3sc) ([raw file](https://github.com/starkware-libs/sequencer/blob/410a9dca7537bfb90d92c13f95f81c51464cacba/crates/blockifier/src/execution/native/syscall_handler.rs#L186)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

In the library call syscall we always set it to `External`. In the deprecated syscall `library_call_l1_handler` we set it to `EntryPointType::L1Handler`.
</blockquote></details>

Do we need to support the deprecated calls? The logic for setting the entry point type comes from the caller (delegate_call or delegate_l1_handler which both set call_to_external to false), so I don't see how we could detect that from inside the library_call. If I'm understanding correctly, nothing needs to be changed here, correct?
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 197 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OBA3dk306Pe30wTXN1T:-OBBUFzL9P6vFxG5v20E:b-khiygo) ([raw file](https://github.com/starkware-libs/sequencer/blob/a852db05f1587df24025eef4f2ad8e0d9e70b6b9/crates/blockifier/src/execution/native/syscall_handler.rs#L197)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider changing the return type of `execute_inner_call` to `Vec<Felt>`.
</blockquote></details>

I think it's fine like this for now. I expect the error handling for StarknetSyscallHandler to change, and when that happens the return value for execute_inner_call will probably change as well.
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OAvjZv8AbWDkSOeRYgD:-OBBVCFVCYrVjaYkN43g:bh3yy32) ([raw file](https://github.com/starkware-libs/sequencer/blob/410a9dca7537bfb90d92c13f95f81c51464cacba/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L111)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why? Both should have the sierra gas, no?
The initial gas should be identical.
The vm resources should eventuallt also be identical (WIP)
</blockquote></details>

The initial gas should be identical now (main_entry_point's initial_gas on line 150). I adjusted the other 3 initial_gas values accordingly (nested_storage_entry_point, library_entry_point, and storage_entry_point).
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 188 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OBBFMLTCAfTJ8StNju6:-OBBevm7CRcZ_YPIhm5Z:bjn3o55) ([raw file](https://github.com/starkware-libs/sequencer/blob/b22f19f4069f53bbfc409842a5b2b8f51cbc3fc4/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L188)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

How come the native execution has a non-default vm resources? :thinking:
</blockquote></details>

It looks like we do account for VM resources in native execution. For example in `crates/blockifier/src/execution/entry_point_execution.rs`::`finalize_execution` which get called during the tests.
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 201 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OBBEQbn98UqMz7D6zCA:-OBBh6aW-lBAw-EI5GFr:b-k2rwtz) ([raw file](https://github.com/starkware-libs/sequencer/blob/b22f19f4069f53bbfc409842a5b2b8f51cbc3fc4/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L201)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain?
Why is `the storage_entry_point_resources` non-native value depends on the native case?
</blockquote></details>

Good catch. Fixed.

**Review by meship-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @avi-starkware, @noaov1, and @varex83)

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: all files reviewed, 5 unresolved discussions (waiting on @meship-starkware, @noaov1, and @varex83)

**Review by avi-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: all files reviewed, 5 unresolved discussions (waiting on @meship-starkware, @noaov1, and @varex83)

**Review by PearsonWhite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @noaov1, and @varex83)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 201 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OBBEQbn98UqMz7D6zCA:-OBRPJXfAnXNByN37Io1:b3a0zao) ([raw file](https://github.com/starkware-libs/sequencer/blob/b22f19f4069f53bbfc409842a5b2b8f51cbc3fc4/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L201)):*
<details><summary><i>Previously, PearsonWhite wrote…</i></summary><blockquote>

Good catch. Fixed.
</blockquote></details>

I forgot to `git add` this change on the previous update. It should be fixed now.

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1 and @varex83)

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1, @varex83, and @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-:-OBfrQVB0Csk8FNLGRcM:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1 and @varex83)

**Review by Yoni-Starkware — APPROVED** [review]
> Dismissed @noaov1 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1 and @varex83)

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @varex83)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 197 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OBA3dk306Pe30wTXN1T:-OBfrpcAB9j0mADa2QZ1:b3kqx) ([raw file](https://github.com/starkware-libs/sequencer/blob/a852db05f1587df24025eef4f2ad8e0d9e70b6b9/crates/blockifier/src/execution/native/syscall_handler.rs#L197)):*
<details><summary><i>Previously, PearsonWhite wrote…</i></summary><blockquote>

I think it's fine like this for now. I expect the error handling for StarknetSyscallHandler to change, and when that happens the return value for execute_inner_call will probably change as well.
</blockquote></details>

.

**Review by Yoni-Starkware — APPROVED** [review]
> Dismissed @noaov1 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @varex83)

**Review by Yoni-Starkware — APPROVED** [review]
> Dismissed @noaov1 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @varex83)

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @varex83)

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @varex83)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 201 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OBBEQbn98UqMz7D6zCA:-OBfs1rq9tVMltP6ERB5:b3kqx) ([raw file](https://github.com/starkware-libs/sequencer/blob/b22f19f4069f53bbfc409842a5b2b8f51cbc3fc4/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L201)):*
<details><summary><i>Previously, PearsonWhite wrote…</i></summary><blockquote>

I forgot to `git add` this change on the previous update. It should be fixed now.
</blockquote></details>

.

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @varex83)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs` line 188 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1547#-OBBFMLTCAfTJ8StNju6:-OBfsHun5TlmoKEzrt2P:b3kqx) ([raw file](https://github.com/starkware-libs/sequencer/blob/b22f19f4069f53bbfc409842a5b2b8f51cbc3fc4/crates/blockifier/src/execution/syscalls/syscall_tests/library_call.rs#L188)):*
<details><summary><i>Previously, PearsonWhite wrote…</i></summary><blockquote>

It looks like we do account for VM resources in native execution. For example in `crates/blockifier/src/execution/entry_point_execution.rs`::`finalize_execution` which get called during the tests.
</blockquote></details>

.

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1547)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @varex83)

**Pull request merged**
