### PR TITLE
refactor(mempool_test_utils): rename contract

### PR DESCRIPTION
**Pull request by giladchase**
** RENAME AND DOCS ONLY **

Rename:

- FeatureAccount -> Contract, this was an incorrect name, since we use this abstraction for both non-accounts and accounts. This is basically an enhancement of FeatureContract, allowing to construct it from a deploy account tx, as well as through the literal constructor.

- `account: Contract` -> `contract: Contract`.

Also added docs to clarify this issue.

Note: we still unfortunately expose `ThinStateDiffBuilder#fund()` for non-account contracts, which is only protected via an assert, but AFAICS mending this requires touchups inside FeatureContract itself, which is out of scope here.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1115)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1115)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 413 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1115#-O82WFS-5XgAkDRdi1_s:-O82WFS07nE39dyK_FEm:bk970qz) ([raw file](https://github.com/starkware-libs/sequencer/blob/52fe6854b9c056f6165da7a49490742613630d08/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L413)):*
> ```XML
>     }
> 
>     fn new(account: FeatureContract, deploy_account_tx: &RpcTransaction) -> Self {
> ```

Maybe rename "account" arg. here?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1115)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 413 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1115#-O82WFS-5XgAkDRdi1_s:-O82ZaviA3MKed-iuusW:b-fuf0ur) ([raw file](https://github.com/starkware-libs/sequencer/blob/52fe6854b9c056f6165da7a49490742613630d08/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L413)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Maybe rename "account" arg. here?
</blockquote></details>

Hmm, thing is, this is supposed to be used only by accounts.
How about I'll rename the method as `new_for_account` and leave it as `account` (separate PR cause this one's a rename)? WDYT?
___
*[`crates/tests-integration/src/state_reader.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1115#-O82X5Jv14_uhw_1S95f:-O82Zk340KCSQo8R8txP:b-uxgo4b) ([raw file](https://github.com/starkware-libs/sequencer/blob/6355144bec2ae35189adbbd86b4ef763c886ff32/crates/tests-integration/src/state_reader.rs#L68)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

These are only accounts, right? Maybe in such paragraphs "account" variable name should remain?
</blockquote></details>

Here actually they're all contracts :dizzy_face:  
Sorry, it's still confusing?

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1115)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 413 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1115#-O82WFS-5XgAkDRdi1_s:-O82r1M95qaCGxwyas0G:bym6nvu) ([raw file](https://github.com/starkware-libs/sequencer/blob/52fe6854b9c056f6165da7a49490742613630d08/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L413)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Hmm, thing is, this is supposed to be used only by accounts.
How about I'll rename the method as `new_for_account` and leave it as `account` (separate PR cause this one's a rename)? WDYT?
</blockquote></details>

Yeah, whatever seems more intuitive. :)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1115#-:-O82r8749ze4IoPQO-Yx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
