### PR TITLE
feat(ci): deny rust warnings in all workflows

### PR DESCRIPTION
**Pull request by dorimedini-starkware**

### CODE REVIEW

**Review by giladchase — APPROVED** [review]
Did you test? Yoni's example could work, that is, make a Pr on top of this branch with an unused import in whatever file Yoni said was only compiled when compiling with cairo-native, with the failure expected to be at blockifier_ci's job

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2388#-:-OD5a8f38BO5AezrHiDi:bfnf7gh)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
no need for a different PR, [this PR's CI fails](https://github.com/starkware-libs/sequencer/actions/runs/12115863736/job/33775081824) on an unused import :)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2388#-:-OD6G5sk9PBqWOFLxUZw:b17bgf2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2388)* status: 13 of 14 files reviewed, all discussions resolved

**Review by giladchase — COMMENTED** [review]
:woo:
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2388#-:-ODAq1_R7wLF62UuVojn:b5hkdya)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2388)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
