### PR TITLE
chore: move GatewaySpecError to gateway_types

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #806
- #804
- #810
- #799
- #798 ⬅
- #797
- #758

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/798)

### CODE REVIEW

**Review by yair-starkware — APPROVED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/798)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/gateway_types/Cargo.toml` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/798#-O6tpxMG22W7uz6V5Qb1:-O6tpxMG22W7uz6V5Qb2:b-okr1dx) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b7fc82757d5c85bf996e208d055e09ae5ea0f43/crates/gateway_types/Cargo.toml#L13)):*
> ```TOML
> [dependencies]
> async-trait.workspace = true
> axum.workspace = true
> ```

Why are there so many dependency additions?

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/798)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/gateway_types/Cargo.toml` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/798#-O6tpxMG22W7uz6V5Qb1:-O6tqWrWAhKOIGyAUidj:b8g7b7d) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b7fc82757d5c85bf996e208d055e09ae5ea0f43/crates/gateway_types/Cargo.toml#L13)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why are there so many dependency additions?
</blockquote></details>

Check the changes in: `crates/gateway_types/src/errors.rs`

Namely the addition of 
```
use std::fmt::Display;

use axum::http::StatusCode;
use axum::response::{IntoResponse, Response};
use enum_assoc::Assoc;
use papyrus_rpc::error::{
```
___
*[`crates/gateway_types/Cargo.toml` line 32 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/798#-O6tqotm3VtKouygh770:-O6tqotm3VtKouygh771:bscb0le) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b7fc82757d5c85bf996e208d055e09ae5ea0f43/crates/gateway_types/Cargo.toml#L32)):*
> ```TOML
> rstest.workspace = true
> starknet_mempool.workspace = true
> tracing-test.workspace = true
> ```

I'll see if these can be removed, and if so, will do.



_Code quote:_
```TOML
[dev-dependencies]
assert_matches.workspace = true
cairo-lang-sierra-to-casm.workspace = true
mockall.workspace = true
mockito.workspace = true
num-bigint.workspace = true
pretty_assertions.workspace = true
rstest.workspace = true
starknet_mempool.workspace = true
tracing-test.workspace = true
```

**Review by yair-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/798)* status: all files reviewed, 2 unresolved discussions

**Review by yair-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/798)* status: all files reviewed, 1 unresolved discussion

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 14 of 16 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/798)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#799](https://github.com/starkware-libs/sequencer/pull/799)

**Pull request closed without merging**
