### PR TITLE
feat(starknet_batcher): communication for sync block request

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#2604** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2604?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2603** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2603?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2603?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2603#-:-ODkR7hR9TF7Q5G5K7vD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_batcher_types/src/communication.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2603#-ODkQy0C3TwLMHVvQW8n:-ODkQy0D4-fkMIYCMvBi:b-ttm8u) ([raw file](https://github.com/starkware-libs/sequencer/blob/390db8042d38c8b670d00bb2fac5d0ffb54265ea/crates/starknet_batcher_types/src/communication.rs#L73)):*
> ```XML
>     async fn start_height(&self, input: StartHeightInput) -> BatcherClientResult<()>;
>     /// Add a block that came from the state sync. Update the batcher's state and commit the
>     /// transactions to the mempool.
> ```

Great documentation



_Suggestion:_
```XML
    /// Adds a block that came from the state sync. Updates the batcher's state and commit the
    /// transactions to the mempool.
```

**Comment by ArniStarkware** [comment]
*[`crates/starknet_batcher_types/src/communication.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2603#-ODkQy0C3TwLMHVvQW8n:-ODkcTGg3QygrhjZThm-:bmy30hh) ([raw file](https://github.com/starkware-libs/sequencer/blob/390db8042d38c8b670d00bb2fac5d0ffb54265ea/crates/starknet_batcher_types/src/communication.rs#L73)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Great documentation
</blockquote></details>

Added a few more fixes as suggested by ChatGPT.

**Review by alonh5 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2603)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2603)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2603)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Dec 16, 6:03 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2603).

**Pull request merged**
