### PR TITLE
chore: change checkout ref

### PR DESCRIPTION
**Pull request by nadin-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1213)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1213)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`.github/workflows/upload_artifacts_workflow.yml` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1213#-O8XVmgH2ED30ahZ9umi:-O8XVmgH2ED30ahZ9umj:b-zfagih) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7cb8306a7ce68adebdeba20e7c1b97decf19230/.github/workflows/upload_artifacts_workflow.yml#L28)):*
> ```YAML
>         env:
>           COMMIT_SHA: ${{ github.event.workflow_run.head_commit.id }}
>         run: echo "SHORT_HASH=${COMMIT_SHA:0:7}" >> $GITHUB_ENV
> ```

reuse the `github.event.workflow_run.head_commit.id` logic



_Suggestion:_
```YAML
      # Commit hash on pull request event would be the head commit of the branch.
      - name: Get commit hash prefix for PR update
        env:
          COMMIT_SHA: ${{ github.event.workflow_run.head_commit.id }}
        run: echo "SHORT_HASH=${COMMIT_SHA:0:7}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.SHORT_HASH }}
      - uses: ./.github/actions/bootstrap
      - name: Build native blockifier
        run: ./build_native_in_docker.sh scripts/build_native_blockifier.sh
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1213)* status: all files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1213)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`.github/workflows/upload_artifacts_workflow.yml` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1213#-O8XVmgH2ED30ahZ9umi:-O8XgW-G4OEuGIoWrAcX:brdfn7b) ([raw file](https://github.com/starkware-libs/sequencer/blob/e7cb8306a7ce68adebdeba20e7c1b97decf19230/.github/workflows/upload_artifacts_workflow.yml#L28)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

reuse the `github.event.workflow_run.head_commit.id` logic
</blockquote></details>

I need the full commit hash. Done

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1213#-:-O8XjMvuEmp79bljATVc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Pull request merged**
