### PR TITLE
refactor(network): flatten broadcast topic channels

### PR DESCRIPTION
**Pull request by eitanm-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/794)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/794)* status: all files reviewed, 2 unresolved discussions (waiting on @eitanm-starkware and @ShahakShama)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/794#-O6v5MfX-bDAdCbgD25G):*
I don't understand this. It looks to me like the point of this PR is to flatten BroadcastTopicChannels by deleting BroadcastClientChannels. What does this have to do with nested channels?



_Code quote:_
```
- c91fd99: refactor(network): have broadcast topic channels to hold nested channels
```
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 248 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/794#-O6tc26C6jplzAB455nc:-O6v2U-44RhDMsXQYEvp:b-20t51f) ([raw file](https://github.com/starkware-libs/sequencer/blob/c91fd99c6cec9aaa0ec9b01942a78460ed102f76/crates/sequencing/papyrus_consensus/src/manager.rs#L248)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

@matan-starkware up to you if you want to log send errors or not
</blockquote></details>

Let me check I understand. The point of this is for the end user of the network (consensus) to tell consensus that the message looks good and we should gossip. In the error case, consensus received the message without issue, but is unable to tell the network to propagate the message on?

Is there any reason that we should expect this (ie network drops the receiver)? My default is that this is unexpected, but doesn't actually break anything, so `warn!` log. Make sense? (and below for report)

BTW in the future we're going to need to propagate this handling further (aka to a place where we actually process the message). So I hope you've thought about the ergonomics of this :)

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/794)* status: all files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/794#-O6v5MfX-bDAdCbgD25G):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I don't understand this. It looks to me like the point of this PR is to flatten BroadcastTopicChannels by deleting BroadcastClientChannels. What does this have to do with nested channels?
</blockquote></details>

i meant nested within structs - but flatten is more correct - changing.
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 248 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/794#-O6tc26C6jplzAB455nc:-O6z1Ya53zIvYf9fqwDZ:b-ng4xb) ([raw file](https://github.com/starkware-libs/sequencer/blob/c91fd99c6cec9aaa0ec9b01942a78460ed102f76/crates/sequencing/papyrus_consensus/src/manager.rs#L248)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Let me check I understand. The point of this is for the end user of the network (consensus) to tell consensus that the message looks good and we should gossip. In the error case, consensus received the message without issue, but is unable to tell the network to propagate the message on?

Is there any reason that we should expect this (ie network drops the receiver)? My default is that this is unexpected, but doesn't actually break anything, so `warn!` log. Make sense? (and below for report)

BTW in the future we're going to need to propagate this handling further (aka to a place where we actually process the message). So I hope you've thought about the ergonomics of this :)
</blockquote></details>

im closing this and moving the discussion to the channel. we can address in future pr

**Review by matan-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/794)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/794#-:-O7-72iM9YWnH1_RnsGk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 852 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/794#-O6zwsixEJuArZIUi0oG:-O6zwsixEJuArZIUi0oH:b-iz5gy3) ([raw file](https://github.com/starkware-libs/sequencer/blob/77dde694464fa2f66843aee613bc6a2399f9c1cc/crates/papyrus_network/src/network_manager/mod.rs#L852)):*
> ```XML
>     (Result<Message, <Message as TryFrom<Bytes>>::Error>, BroadcastedMessageManager);
> 
> type BroadcastReceivedMessagesConverterFn<T> =
> ```

I think you can remove this type alias. you can do this in a later PR
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 248 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/794#-O6tc26C6jplzAB455nc:-O6zvntD7p5OexLNqRI_:b-9n7ola) ([raw file](https://github.com/starkware-libs/sequencer/blob/c91fd99c6cec9aaa0ec9b01942a78460ed102f76/crates/sequencing/papyrus_consensus/src/manager.rs#L248)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

im closing this and moving the discussion to the channel. we can address in future pr
</blockquote></details>

If there's an error it probably means that there are too many messages being sent to the network and the network has a big backlog. I don't think there's anything else you can do except of dropping this message
`warn!` sounds good.
@matan-starkware could you add it in a future PR once @eitanm-starkware merges? (I don't want to stall this PR)

**Review by eitanm-starkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/794#-:-O7-8L285iwjuKz-Ze21:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware)

**Pull request merged**
