### PR TITLE
chore(gateway): create a united test for invalid tx test scenario

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1987)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1987#-OBVYwAU7tCDvBeb6hD5:-OBVxi-g95jb4brj6UnD:blv8dk2) ([raw file](https://github.com/starkware-libs/sequencer/blob/36d897f20bf1ee42283eddadd1399967e060590a/crates/gateway/src/stateless_transaction_validator_test.rs#L221)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I will redefine this parameter so that it gets a vector of `TransactionType` and runs over each of the cases.
</blockquote></details>

Isn't that already what it's doing?
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1987#-OBVxSoH04EbwJGFSzh6:-OBVxSoH04EbwJGFSzh7:bw9vc8k) ([raw file](https://github.com/starkware-libs/sequencer/blob/36d897f20bf1ee42283eddadd1399967e060590a/crates/gateway/src/stateless_transaction_validator_test.rs#L169)):*
> ```XML
> 
> #[rstest]
> fn test_calldata_too_long(
> ```

Do you think this test also belongs as a test case?



_Code quote:_
```XML
test_calldata_too_long
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1987#-OBVYwAU7tCDvBeb6hD5:-OBW6N-N0Djj92-8aDkF:b-i8hp5x) ([raw file](https://github.com/starkware-libs/sequencer/blob/36d897f20bf1ee42283eddadd1399967e060590a/crates/gateway/src/stateless_transaction_validator_test.rs#L221)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Isn't that already what it's doing?
</blockquote></details>

Now each tx type corresponds to a test case. I.e. this test runs `For-each-case` times `For-each-tx-type`.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1987)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1987#-OBVYwAU7tCDvBeb6hD5:-OBZXocLAqFcRs7SA6LH:b-vkqb2d) ([raw file](https://github.com/starkware-libs/sequencer/blob/36d897f20bf1ee42283eddadd1399967e060590a/crates/gateway/src/stateless_transaction_validator_test.rs#L221)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Now each tx type corresponds to a test case. I.e. this test runs `For-each-case` times `For-each-tx-type`.
</blockquote></details>

So there must be the same number of test cases as tx types? In that case let's change it in this PR, and you can also add the test case above if that was the reason you left it out.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1987)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 169 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1987#-OBVxSoH04EbwJGFSzh6:-OBZaDRzDt9P0qG4iKDZ:bsndc7r) ([raw file](https://github.com/starkware-libs/sequencer/blob/36d897f20bf1ee42283eddadd1399967e060590a/crates/gateway/src/stateless_transaction_validator_test.rs#L169)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Do you think this test also belongs as a test case?
</blockquote></details>

Covered in #2002
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 221 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1987#-OBVYwAU7tCDvBeb6hD5:-OBZaA8N5WC4yER_Jr8h:b-z9z6zs) ([raw file](https://github.com/starkware-libs/sequencer/blob/36d897f20bf1ee42283eddadd1399967e060590a/crates/gateway/src/stateless_transaction_validator_test.rs#L221)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

So there must be the same number of test cases as tx types? In that case let's change it in this PR, and you can also add the test case above if that was the reason you left it out.
</blockquote></details>

Covered in #2001.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1987#-:-OBZqPsQDp0YxcGUaU7U:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1987)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Nov 13, 5:11 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1987).

**Pull request merged**
