### PR TITLE
fix(consensus): the state machine should retain messages in the queue if GetProposal is produced

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/687)

### CODE REVIEW

**Comment by matan-starkware** [comment]
* **#687** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/687?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by asmaastarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/687)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 317 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/687#-O5rcmGZ9z4bo6ZkwG8b:-O5rcmGZ9z4bo6ZkwG8c:bdi40hm) ([raw file](https://github.com/starkware-libs/sequencer/blob/909d6a107957a57429922c783895db2116dd795d/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L317)):*
> ```XML
>     // We simulate that this node is always the proposer, but it lagged, so the peers kept voting
>     // NIL and progressing rounds.
>     wrapper.send_prevote(None, 0);
> ```

let's use ROUND/ROUND+1/+2

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/687)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/state_machine_test.rs` line 317 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/687#-O5rcmGZ9z4bo6ZkwG8b:-O5rq7OF18FVclJL1DfY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/909d6a107957a57429922c783895db2116dd795d/crates/sequencing/papyrus_consensus/src/state_machine_test.rs#L317)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

let's use ROUND/ROUND+1/+2
</blockquote></details>

Done.

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/687#-:-O5rqqxp5V11pTv7mkM2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Comment by matan-starkware** [comment]
### Merge activity

* **Sep 3, 8:42 AM EDT**: @matan-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/687).

**Pull request merged**
