### PR TITLE
feat(blockifier): verify cairo-lang version before Cairo0 compilation

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/182)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/182?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#183** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/183?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#182** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/182?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#181** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/181?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#180** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/180?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#179** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/179?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by nimrod-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/182)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @dorimedini-starkware, @meship-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/182#-O32_hG_4yhr3w5E4Uxv:-O32_hGaBvDppI792Cm_:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/360c889e2c180b0f9a2df381fff0e3068ab3dec0/crates/blockifier/src/test_utils/cairo_compile.rs#L79)):*
> ```XML
> }
> 
> /// Verifies that the required dependencies are available before compiling.
> ```





_Suggestion:_
```XML
/// Verifies that the required dependencies are available before compiling; panics if unavailable.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/182)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @meship-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/182#-O32_hG_4yhr3w5E4Uxv:-O32n7tV6-tmDf_i0p-Y:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/360c889e2c180b0f9a2df381fff0e3068ab3dec0/crates/blockifier/src/test_utils/cairo_compile.rs#L79)):*
> ```XML
> }
> 
> /// Verifies that the required dependencies are available before compiling.
> ```

Done.

**Review by nimrod-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/182#-:-O36eSu5AvYhzI0l_u7U:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @AvivYossef-starkware, @meship-starkware, and @TzahiTaub)

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/182)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, and @meship-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/182#-O3yqvLv0WI1MNdd1nxO:-O3yqvLv0WI1MNdd1nxP:blefis6) (no related file):*
What happens ATM if we have the package in the wrong version? We fail the comparison, and if we fix we fix the wrong local version we use (and hopefully fails the CI)

___
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/182#-O3ymKoQ6EHSwYgMmNds:-O3ymKoQ6EHSwYgMmNdt:b-7wqzx6) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b47e7771ca5557c3a21fe77a55454a6820f023e/crates/blockifier/src/test_utils/cairo_compile.rs#L98)):*
> ```XML
>         cairo_lang_version.trim(),
>         expected_cairo_lang_version.trim(),
>         "cairo-lang not found. Please run:\npip3.9 install -r {}/{}\nthen rerun the test.",
> ```

We might have the package in the wrong version



_Suggestion:_
```XML
cairo-lang version {} not found...., expected_cairo_lang_version.trim().rsplit("=").next().unwrap()
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/182)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @meship-starkware, and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/182#-O3yqvLv0WI1MNdd1nxO:-O4-NUdH-S6bGhc_UYKH:berszto) (no related file):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

What happens ATM if we have the package in the wrong version? We fail the comparison, and if we fix we fix the wrong local version we use (and hopefully fails the CI)
</blockquote></details>

The CI installs whatever is in the requirements.txt file, if that version is "wrong" there's nothing we can check

___
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/182#-O3ymKoQ6EHSwYgMmNds:-O4-OFwfEQmrbkql0U-w:bvyb82y) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b47e7771ca5557c3a21fe77a55454a6820f023e/crates/blockifier/src/test_utils/cairo_compile.rs#L98)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

We might have the package in the wrong version
</blockquote></details>

better?

**Review by TzahiTaub — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/182)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @dorimedini-starkware, and @meship-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/182#-O3yqvLv0WI1MNdd1nxO:-O4-jm-r7u5ZTADOT-RI:byh6aa1) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

The CI installs whatever is in the requirements.txt file, if that version is "wrong" there's nothing we can check
</blockquote></details>

I meant if our installed local version doesn't match the requirements file. 

___
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/182#-O3ymKoQ6EHSwYgMmNds:-O4-ioV0CYto3tgmupK1:b-igji8k) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b47e7771ca5557c3a21fe77a55454a6820f023e/crates/blockifier/src/test_utils/cairo_compile.rs#L98)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

better?
</blockquote></details>

Yes, though when the package isn't installed, we'll get `(installed version: )` then maybe `if  cairo_lang_version.is_empty() {"not installed"} else { cairo_lang_version}, and raise the `trim()` above as you did for the expected one.

**Review by TzahiTaub — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/182)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @dorimedini-starkware, and @meship-starkware)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/182#-O3ymKoQ6EHSwYgMmNds:-O4-jzuwB8_YyC95gk_x:b-v1mgsq) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b47e7771ca5557c3a21fe77a55454a6820f023e/crates/blockifier/src/test_utils/cairo_compile.rs#L98)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Yes, though when the package isn't installed, we'll get `(installed version: )` then maybe `if  cairo_lang_version.is_empty() {"not installed"} else { cairo_lang_version}, and raise the `trim()` above as you did for the expected one.
</blockquote></details>

\* `and raise the` not a part of the code :)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/182)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware and @meship-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/182#-O3yqvLv0WI1MNdd1nxO:-O4-kDi2A0tD-OUFf3BD:b-ugpnky) (no related file):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I meant if our installed local version doesn't match the requirements file.
</blockquote></details>

the fix command also compares versions (same `cairo0_compile` is called), so you will also fail to fix

___
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/182#-O3ymKoQ6EHSwYgMmNds:-O4-kVB44qxqChmOsTe9:b-uwcsgv) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b47e7771ca5557c3a21fe77a55454a6820f023e/crates/blockifier/src/test_utils/cairo_compile.rs#L98)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

\* `and raise the` not a part of the code :)
</blockquote></details>

done. however, can't raise the `trim` ("value dropped"). defined an intermediate var to call trim once

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/182#-:-O408Ug9-Atm3LowEM40:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware and @meship-starkware)

**Review by TzahiTaub — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/182)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware and @meship-starkware)

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Aug 11, 11:28 AM EDT**: @dorimedini-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/182).

**Pull request merged**
