### PR TITLE
feat(mempool): add l2_gas_price support in BlockHeader

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/652)

### CODE REVIEW

**Comment by TzahiTaub** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/652?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#652** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/652?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#644** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/644?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#643** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/643?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#641** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/641?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @TzahiTaub and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/652)* status: all files reviewed, 3 unresolved discussions (waiting on @ShahakShama and @TzahiTaub)

___
*[`crates/papyrus_rpc/src/v0_8/api/test.rs` line 598 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/652#-O7SwPtQ1c9LwePK_Yt4:-O7SwPtQ1c9LwePK_Yt5:bl60bn5) ([raw file](https://github.com/starkware-libs/sequencer/blob/38d02d8ede65c225af2aed58aac46a03b83a0778/crates/papyrus_rpc/src/v0_8/api/test.rs#L598)):*
> ```XML
>     };
>     let pending_l2_gas_price =
>         GasPricePerToken { price_in_wei: GasPrice(0), price_in_fri: GasPrice(0) };
> ```

please refrain from using zero as a price... why not randomize, like with the `pending_l1_gas_price` above?



_Code quote:_
```XML
price_in_wei: GasPrice(0), price_in_fri: GasPrice(0)
```
___
*[`crates/papyrus_rpc/src/v0_8/api/test.rs` line 787 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/652#-O7SwZ2O9ShpwK7f-gDb:-O7SwZ2O9ShpwK7f-gDc:b-7ropln) ([raw file](https://github.com/starkware-libs/sequencer/blob/38d02d8ede65c225af2aed58aac46a03b83a0778/crates/papyrus_rpc/src/v0_8/api/test.rs#L787)):*
> ```XML
>     };
>     let pending_l2_gas_price =
>         GasPricePerToken { price_in_wei: GasPrice(0), price_in_fri: GasPrice(0) };
> ```

ditto



_Code quote:_
```XML
    let pending_l2_gas_price =
        GasPricePerToken { price_in_wei: GasPrice(0), price_in_fri: GasPrice(0) };
```
___
*[`crates/papyrus_rpc/src/v0_8/api/test.rs` line 976 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/652#-O7Sw_hM7g4hmCb4LGVs:-O7Sw_hM7g4hmCb4LGVt:b-7ropln) ([raw file](https://github.com/starkware-libs/sequencer/blob/38d02d8ede65c225af2aed58aac46a03b83a0778/crates/papyrus_rpc/src/v0_8/api/test.rs#L976)):*
> ```XML
>     };
>     let pending_l2_gas_price =
>         GasPricePerToken { price_in_wei: GasPrice(0), price_in_fri: GasPrice(0) };
> ```

ditto



_Code quote:_
```XML
    let pending_l2_gas_price =
        GasPricePerToken { price_in_wei: GasPrice(0), price_in_fri: GasPrice(0) };
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/652)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/papyrus_rpc/src/v0_8/api/test.rs` line 598 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/652#-O7SwPtQ1c9LwePK_Yt4:-O7TbyJo26bQjFkr5M_H:blenr7k) ([raw file](https://github.com/starkware-libs/sequencer/blob/38d02d8ede65c225af2aed58aac46a03b83a0778/crates/papyrus_rpc/src/v0_8/api/test.rs#L598)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please refrain from using zero as a price... why not randomize, like with the `pending_l1_gas_price` above?
</blockquote></details>

The `expected_pending_block` is compared against a `DeprecatedPendingBlock`, that doesn't have a `l2_gas_price` field.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/652)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama and @TzahiTaub)

___
*[`crates/papyrus_rpc/src/v0_8/api/test.rs` line 598 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/652#-O7SwPtQ1c9LwePK_Yt4:-O7U-mnU2vi06whyVKgc:bnwbvce) ([raw file](https://github.com/starkware-libs/sequencer/blob/38d02d8ede65c225af2aed58aac46a03b83a0778/crates/papyrus_rpc/src/v0_8/api/test.rs#L598)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

The `expected_pending_block` is compared against a `DeprecatedPendingBlock`, that doesn't have a `l2_gas_price` field.
</blockquote></details>

ah... gotcha

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/652#-:-O7U-tfT9qUQ8MCMSBXP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/652)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
