### PR TITLE
feat(starknet_state_sync): add_new_block on StateSyncClient

### PR DESCRIPTION
**Pull request by AlonLStarkWare**

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2590)* status: all files reviewed, 2 unresolved discussions (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`crates/starknet_state_sync_types/src/communication.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2590#-ODjeD1c2vcYAOyIAiWM:-ODjeD1c2vcYAOyIAiWN:bo880ve) ([raw file](https://github.com/starkware-libs/sequencer/blob/c6cb51a70691098d1c81f62ec9f4ca8c9f4238f0/crates/starknet_state_sync_types/src/communication.rs#L31)):*
> ```XML
> 
>     // Add a new block to the sync storage from another component within the same node.
>     async fn add_new_internal_block(&self, sync_block: SyncBlock) -> StateSyncClientResult<()>;
> ```

You should also receive block_number
___
*[`crates/starknet_state_sync_types/src/communication.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2590#-ODjfhoeEf8SygHL4Ymo:-ODjfhoeEf8SygHL4Ymp:blfkvcs) ([raw file](https://github.com/starkware-libs/sequencer/blob/c6cb51a70691098d1c81f62ec9f4ca8c9f4238f0/crates/starknet_state_sync_types/src/communication.rs#L31)):*
> ```XML
> 
>     // Add a new block to the sync storage from another component within the same node.
>     async fn add_new_internal_block(&self, sync_block: SyncBlock) -> StateSyncClientResult<()>;
> ```

I'm not sure this should be the name for the client. Asked in slack

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2590)* status: all files reviewed, 2 unresolved discussions (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`crates/starknet_state_sync_types/src/communication.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2590#-ODjfhoeEf8SygHL4Ymo:-ODjfrUeCGbrPRf4RhmS:b3prob5) ([raw file](https://github.com/starkware-libs/sequencer/blob/c6cb51a70691098d1c81f62ec9f4ca8c9f4238f0/crates/starknet_state_sync_types/src/communication.rs#L31)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I'm not sure this should be the name for the client. Asked in slack
</blockquote></details>

You can merge and worst case we'll rename it later on

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2590)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @eitanm-starkware and @ShahakShama)

___
*[`crates/starknet_state_sync_types/src/communication.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2590#-ODjeD1c2vcYAOyIAiWM:-ODjqEBdDZewufpPSaaM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3341112159299beaae951b4c63d5b0dddc31002c/crates/starknet_state_sync_types/src/communication.rs#L31)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You should also receive block_number
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2590)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`crates/starknet_state_sync_types/src/communication.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2590#-ODk-aw93lWFygBE_JjM:-ODk-aw93lWFygBE_JjN:bxlteks) ([raw file](https://github.com/starkware-libs/sequencer/blob/1ad66114c6587fccf813967a31c3a32c5f624360/crates/starknet_state_sync_types/src/communication.rs#L60)):*
> ```XML
> pub enum StateSyncRequest {
>     GetBlock(BlockNumber),
>     AddNewInternalBlock(SyncBlock, BlockNumber),
> ```

Swap the order (First block number)
That's the convention in the storage at least

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2590)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @eitanm-starkware and @ShahakShama)

___
*[`crates/starknet_state_sync_types/src/communication.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2590#-ODjfhoeEf8SygHL4Ymo:-ODkHSiH0qJtRmdeuEpe:boi613u) ([raw file](https://github.com/starkware-libs/sequencer/blob/3341112159299beaae951b4c63d5b0dddc31002c/crates/starknet_state_sync_types/src/communication.rs#L31)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You can merge and worst case we'll rename it later on
</blockquote></details>

Changed to add_new_block following the slack discussion
___
*[`crates/starknet_state_sync_types/src/communication.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2590#-ODk-aw93lWFygBE_JjM:-ODkHcgiDOsDpCWez5QV:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/1ad66114c6587fccf813967a31c3a32c5f624360/crates/starknet_state_sync_types/src/communication.rs#L60)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Swap the order (First block number)
That's the convention in the storage at least
</blockquote></details>

Done

**Pull request merged**
