### PR TITLE
feat(papyrus_base_layer): add events api

### PR DESCRIPTION
**Pull request by giladchase**

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2844)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @matan-starkware)

___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2844#-OEhZOUx7nP8rbQknlM9:-OEhZOUyAULd8hBo2JNh:bmrqek2) ([raw file](https://github.com/starkware-libs/sequencer/blob/9579f56179c345608cb5465d962db8327652eb1b/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L86)):*
> ```XML
>         _from_block: u64,
>         _until_block: u64,
>         _event_identifiers: &[&str],
> ```

What's an example for an event identifier?



_Code quote:_
```XML
_event_identifiers: &[&str]
```
___
*[`crates/papyrus_base_layer/src/lib.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2844#-OEhZY3y2l3FIfoEhOpc:-OEhZY3y2l3FIfoEhOpd:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/9579f56179c345608cb5465d962db8327652eb1b/crates/papyrus_base_layer/src/lib.rs#L28)):*
> ```XML
>     ) -> Result<Option<BlockHashAndNumber>, Self::Error>;
> 
>     /// Get specific events from the Starknet base contract between two l1 block numbers.
> ```





_Suggestion:_
```XML
L1
```
___
*[`crates/papyrus_base_layer/src/lib.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2844#-OEhZgK98-8Hg9rk-pGX:-OEhZgK98-8Hg9rk-pGY:b9o5xj5) ([raw file](https://github.com/starkware-libs/sequencer/blob/9579f56179c345608cb5465d962db8327652eb1b/crates/papyrus_base_layer/src/lib.rs#L45)):*
> ```XML
>     MessageToL2CancellationStarted(EventData),
>     MessageToL2Canceled(EventData),
>     ConsumedMessageToL1 { from_address: EthAddress, to_address: ContractAddress, payload: Calldata },
> ```

Note the "consumed" variant; should it be "to L2"?



_Suggestion:_
```XML
    
    ConsumedMessageToL2 { from_address: EthAddress, to_address: ContractAddress, payload: Calldata },
    LogMessageToL2 { tx: L1HandlerTransaction, fee: Fee },
    MessageToL2Canceled(EventData),
    MessageToL2CancellationStarted(EventData),
```
___
*[`crates/papyrus_base_layer/src/lib.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2844#-OEhZxWDCGFnJDgZrLRE:-OEhZxWDCGFnJDgZrLRF:b-grd0rt) ([raw file](https://github.com/starkware-libs/sequencer/blob/9579f56179c345608cb5465d962db8327652eb1b/crates/papyrus_base_layer/src/lib.rs#L50)):*
> ```XML
> /// Shared fields in Starknet messaging.
> #[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, Default)]
> pub struct EventData {
> ```

Why duplicate, for serde?



_Code quote:_
```XML
 EventData
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2844)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @matan-starkware)

___
*[`crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2844#-OEhZOUx7nP8rbQknlM9:-OEmGw-o8D-7xAYzdvbe:bw4n0vb) ([raw file](https://github.com/starkware-libs/sequencer/blob/9579f56179c345608cb5465d962db8327652eb1b/crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs#L86)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What's an example for an event identifier?
</blockquote></details>

For example,
`keccack("sendMessageToL2( uint256 toAddress, uint256 selector, uint256[] calldata payload)")`
which is the identifier that etherum uses to reference an event (it is placed in a fixed location in the event payload that is emitted).

However, l1 library were using `alloy` can also take the string without the keccak:`"sendMessageToL2( uint256 toAddress, uint256 selector, uint256[] calldata payload)"` and do the keccack by itself.

Regardless, I won't be using any handcrafted hardcoded strings anywhere,  `alloy` generates them as consts from the ABI and makes them accessible from  event struct it generates.
___
*[`crates/papyrus_base_layer/src/lib.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2844#-OEhZgK98-8Hg9rk-pGX:-OEmIqNz8dXWlT9qJ4db:b-2teolw) ([raw file](https://github.com/starkware-libs/sequencer/blob/9579f56179c345608cb5465d962db8327652eb1b/crates/papyrus_base_layer/src/lib.rs#L45)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Note the "consumed" variant; should it be "to L2"?
</blockquote></details>

Ohhh yr right, that explains why the args were different types :facepalm:  
Fixed.
___
*[`crates/papyrus_base_layer/src/lib.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2844#-OEhZxWDCGFnJDgZrLRE:-OEmJwtg1faOolXb_hSj:bckr0s1) ([raw file](https://github.com/starkware-libs/sequencer/blob/9579f56179c345608cb5465d962db8327652eb1b/crates/papyrus_base_layer/src/lib.rs#L50)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why duplicate, for serde?
</blockquote></details>

Duplicate what exactly? :thinking: 
The reason i have this struct is because I want the baselayer to pass on the most raw (deserialized) interpretation of what it read.
Ideally, I could have just passed the parsed type from alloy, which is rich and has everything I need, but Ethereum operates behind the trait BaseLayerContract, and in particular can't leak any eth-specific deps and their inner types like `alloy`.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2844)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @matan-starkware)

___
*[`crates/papyrus_base_layer/src/lib.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2844#-OEhZxWDCGFnJDgZrLRE:-OEmN7lw91TKO99Vj2oF:bbyiuzq) ([raw file](https://github.com/starkware-libs/sequencer/blob/9579f56179c345608cb5465d962db8327652eb1b/crates/papyrus_base_layer/src/lib.rs#L50)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Duplicate what exactly? :thinking: 
The reason i have this struct is because I want the baselayer to pass on the most raw (deserialized) interpretation of what it read.
Ideally, I could have just passed the parsed type from alloy, which is rich and has everything I need, but Ethereum operates behind the trait BaseLayerContract, and in particular can't leak any eth-specific deps and their inner types like `alloy`.
</blockquote></details>

I would have thought we'd already have a similar struct in SNAPI.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2844)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @matan-starkware)

___
*[`crates/papyrus_base_layer/src/lib.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2844#-OEhZgK98-8Hg9rk-pGX:-OEnKgBD2VGy2dr5Rptq:b-82gyow) ([raw file](https://github.com/starkware-libs/sequencer/blob/9579f56179c345608cb5465d962db8327652eb1b/crates/papyrus_base_layer/src/lib.rs#L45)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Ohhh yr right, that explains why the args were different types :facepalm:  
Fixed.
</blockquote></details>

Push?
___
*[`crates/papyrus_base_layer/src/lib.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2844#-OEhZxWDCGFnJDgZrLRE:-OEnKkWl-BEzSZjTssU4:b-80tlqk) ([raw file](https://github.com/starkware-libs/sequencer/blob/9579f56179c345608cb5465d962db8327652eb1b/crates/papyrus_base_layer/src/lib.rs#L50)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Not in snapi :pensive: 
There is some overlap with the startknet client [here](https://github.com/starkware-libs/sequencer/blob/c4b36db0a4043a88b90db2b4f27bfc91e86c4484/crates/starknet_client/src/reader/objects/transaction.rs#L842)  which I can then maybe extract usage from both to SNAPI.

However depending on starknet_client isn't right, because it is a crate for talking with the [feeder_]gateway.
I can however extract into SNAPI and have them both use that type, but I think it'd be best to do that after the design for l1provider settles.

WDYT?
</blockquote></details>

Sure.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2844)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @matan-starkware)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2844#-:-OEnM4z08zTrsAYoaFEK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by giladchase — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2844)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Pull request merged**
