### PR TITLE
fix(batcher): fix send_proposal_content return status and add the relevant tests

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2053?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2053** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2053?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2050** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2050?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2049** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2049?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2042** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2042?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2046** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2046?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1951** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1951?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1996** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1996?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1986** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1986?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1985** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1985?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Yael-Starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2053)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 207 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-OBtF14A-hdMiept1tGY:-OBtF14A-hdMiept1tGZ:b76q1b1) ([raw file](https://github.com/starkware-libs/sequencer/blob/8beaf77d44c7568f5b45bce0751f2c2577211871/crates/starknet_batcher/src/batcher.rs#L207)):*
> ```XML
>             .remove(&proposal_id)
>             .ok_or(BatcherError::ProposalNotFound { proposal_id })?;
>         drop(tx_provider_sender);
> ```

Why is the explicit drop necessary?



_Code quote:_
```XML
drop(tx_provider_sender);
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-OBtRT8mERkBX0esUsat:-OBtRT8mERkBX0esUsau:b4v6pdp) ([raw file](https://github.com/starkware-libs/sequencer/blob/8beaf77d44c7568f5b45bce0751f2c2577211871/crates/starknet_batcher/src/batcher_test.rs#L244)):*
> ```XML
>     };
>     let result = batcher.send_proposal_content(send_proposal_input_txs).await.unwrap();
>     assert_eq!(result, SendProposalContentResponse { response: ProposalStatus::InvalidProposal });
> ```

I think this should be an error
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 277 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-OBtRkXm6sKIIH-dBIGC:-OBtRkXm6sKIIH-dBIGD:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/8beaf77d44c7568f5b45bce0751f2c2577211871/crates/starknet_batcher/src/batcher_test.rs#L277)):*
> ```XML
>     let send_proposal_input_txs =
>         SendProposalContentInput { proposal_id: PROPOSAL_ID, content: SendProposalContent::Finish };
>     let result = batcher.send_proposal_content(send_proposal_input_txs).await.unwrap();
> ```

same

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2053)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 207 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-OBtF14A-hdMiept1tGY:-OBuVcyoAtT2oKkn7tlj:b40d4mo) ([raw file](https://github.com/starkware-libs/sequencer/blob/8beaf77d44c7568f5b45bce0751f2c2577211871/crates/starknet_batcher/src/batcher.rs#L207)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

that is the signal sent to tx_provider (and from the tx_provider to the block_builder) to finish the block.
</blockquote></details>

I think we should have something more explicit for this, probably a single-shot channel, WDYT?
I am fine with adding a comment here as to why this drop is necessary + a todo in the tx_provider and solving it in a separate PR.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-OBtRT8mERkBX0esUsat:-OBuWgNMChzsjM20p5Ps:bujc0xk) ([raw file](https://github.com/starkware-libs/sequencer/blob/8beaf77d44c7568f5b45bce0751f2c2577211871/crates/starknet_batcher/src/batcher_test.rs#L244)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

so what is the InvalidProposal for?
maybe InvalidProposal status should be removed from the API.
</blockquote></details>

Oh I thought this is when consensus sends more content after `finish`, my bad
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 277 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-OBtRkXm6sKIIH-dBIGC:-OBuXPrg6r-9p-1vwlNy:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/8beaf77d44c7568f5b45bce0751f2c2577211871/crates/starknet_batcher/src/batcher_test.rs#L277)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

same.

related to my comment as well. the return values are not well defined here. we need to decide when to return Invalid and when Error.
</blockquote></details>

same

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2053)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 207 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-OBtF14A-hdMiept1tGY:-OByS8rb5ehaRyie3sG2:biev0w8) ([raw file](https://github.com/starkware-libs/sequencer/blob/8beaf77d44c7568f5b45bce0751f2c2577211871/crates/starknet_batcher/src/batcher.rs#L207)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think we should have something more explicit for this, probably a single-shot channel, WDYT?
I am fine with adding a comment here as to why this drop is necessary + a todo in the tx_provider and solving it in a separate PR.
</blockquote></details>

I'm not sure we need to open another channel just for this when we can drop, but I think a comment here about the drop is a good idea, let's do that.
___
*[`crates/starknet_batcher/src/batcher.rs` line 213 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-OByShZV1LCikWEKsu2j:-OByShZV1LCikWEKsu2k:b-d0x5lq) ([raw file](https://github.com/starkware-libs/sequencer/blob/9526e01e4217622db200ff6a0c2d19a45e460317/crates/starknet_batcher/src/batcher.rs#L213)):*
> ```XML
>             Err(GetProposalResultError::BlockBuilderError(_)) => ProposalStatus::InvalidProposal,
>             Err(GetProposalResultError::ProposalDoesNotExist { proposal_id }) => {
>                 panic!("Proposal {} should exist in the proposal manager.", proposal_id)
> ```

I don't think we want to panic on a wrong call to our API. Can we return an error instead?



_Code quote:_
```XML
panic!("Proposal {} should exist in the proposal manager.", proposal_id)
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2053)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 207 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-OBtF14A-hdMiept1tGY:-OBzZZvN8pYZ78lIN6CH:b-7rl0jd) ([raw file](https://github.com/starkware-libs/sequencer/blob/8beaf77d44c7568f5b45bce0751f2c2577211871/crates/starknet_batcher/src/batcher.rs#L207)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I'm not sure we need to open another channel just for this when we can drop, but I think a comment here about the drop is a good idea, let's do that.
</blockquote></details>

done.
___
*[`crates/starknet_batcher/src/batcher.rs` line 213 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-OByShZV1LCikWEKsu2j:-OBzXuPm6V3k0yb6zCsZ:b-j1oemm) ([raw file](https://github.com/starkware-libs/sequencer/blob/9526e01e4217622db200ff6a0c2d19a45e460317/crates/starknet_batcher/src/batcher.rs#L213)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I don't think we want to panic on a wrong call to our API. Can we return an error instead?
</blockquote></details>

I agree, but there was already a check that this proposal exists in the batcher - at the beginning of the function:
        let tx_provider_sender = self
            .validate_proposals
            .remove(&proposal_id)
            .ok_or(BatcherError::ProposalNotFound { proposal_id })?;

so now I expect it to exist at the proposal manager.

This is one of the places that make it clear we should unite the batcher and the proposal_manager.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2053)* status: all files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 213 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-OByShZV1LCikWEKsu2j:-OBz_GV87-IUSteGGYKs:b-6mhywn) ([raw file](https://github.com/starkware-libs/sequencer/blob/9526e01e4217622db200ff6a0c2d19a45e460317/crates/starknet_batcher/src/batcher.rs#L213)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I agree, but there was already a check that this proposal exists in the batcher - at the beginning of the function:
        let tx_provider_sender = self
            .validate_proposals
            .remove(&proposal_id)
            .ok_or(BatcherError::ProposalNotFound { proposal_id })?;

so now I expect it to exist at the proposal manager.

This is one of the places that make it clear we should unite the batcher and the proposal_manager.
</blockquote></details>

Great, thanks.
___
*[`crates/starknet_batcher/src/batcher.rs` line 207 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-OBzZtcL5GyKix4ErD0s:-OBzZtcL5GyKix4ErD0t:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c0638ffbe15fdeef7019672a04dc122d9a251f62/crates/starknet_batcher/src/batcher.rs#L207)):*
> ```XML
>             .remove(&proposal_id)
>             .ok_or(BatcherError::ProposalNotFound { proposal_id })?;
>         // drop the channel to signal the tx provider that the transaction stream is done.
> ```





_Suggestion:_
```XML
Drop the channel to signal the tx provider that the transaction stream is done.
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 259 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-OBzZcVW0RG7LVyNtREQ:-OBzZcVX5dbVLJ4qTusP:b-jsd80i) ([raw file](https://github.com/starkware-libs/sequencer/blob/9526e01e4217622db200ff6a0c2d19a45e460317/crates/starknet_batcher/src/batcher_test.rs#L259)):*
> ```XML
>     let proposal_error = GetProposalResultError::BlockBuilderError(Arc::new(
>         BlockBuilderError::ExecutorError(TransactionExecutorError::BlockFull),
>     ));
> ```

Move above where it's used.



_Code quote:_
```XML
    let proposal_error = GetProposalResultError::BlockBuilderError(Arc::new(
        BlockBuilderError::ExecutorError(TransactionExecutorError::BlockFull),
    ));
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2053)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 259 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-OBzZcVW0RG7LVyNtREQ:-OBzgQvK9bX0iGuU3nhJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9526e01e4217622db200ff6a0c2d19a45e460317/crates/starknet_batcher/src/batcher_test.rs#L259)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Move above where it's used.
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher.rs` line 207 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-OBzZtcL5GyKix4ErD0s:-OBzgTRM0JHS3sf4RaU-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c0638ffbe15fdeef7019672a04dc122d9a251f62/crates/starknet_batcher/src/batcher.rs#L207)):*
> ```XML
>             .remove(&proposal_id)
>             .ok_or(BatcherError::ProposalNotFound { proposal_id })?;
>         // drop the channel to signal the tx provider that the transaction stream is done.
> ```

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-:-OBzh3H03yhgUAPIN1tn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2053)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 207 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-OBtF14A-hdMiept1tGY:-OBzk_3SCRTMlhLW0WdQ:bx0zv26) ([raw file](https://github.com/starkware-libs/sequencer/blob/8beaf77d44c7568f5b45bce0751f2c2577211871/crates/starknet_batcher/src/batcher.rs#L207)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

done.
</blockquote></details>

So a better way is to call a function that consumes the sender and is named properly
___
*[`crates/starknet_batcher/src/batcher.rs` line 215 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-OBzlbDz9_MabuPNAvwu:-OBzlbDz9_MabuPNAvwv:b-pybbv2) ([raw file](https://github.com/starkware-libs/sequencer/blob/bee69099787899046dbc804da9d915ba74b36e4e/crates/starknet_batcher/src/batcher.rs#L215)):*
> ```XML
>                 BlockBuilderError::FailOnError(_) => ProposalStatus::InvalidProposal,
>                 _ => return Err(BatcherError::InternalError),
>             },
> ```

Is the error logged somewhere?



_Code quote:_
```XML
            Err(GetProposalResultError::BlockBuilderError(err)) => match err.as_ref() {
                BlockBuilderError::FailOnError(_) => ProposalStatus::InvalidProposal,
                _ => return Err(BatcherError::InternalError),
            },
```

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2053)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Review by alonh5 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2053)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 207 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-OBtF14A-hdMiept1tGY:-OC2SSS6CZ_ARcpEC6Pp:bmi8ppe) ([raw file](https://github.com/starkware-libs/sequencer/blob/8beaf77d44c7568f5b45bce0751f2c2577211871/crates/starknet_batcher/src/batcher.rs#L207)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

done.
</blockquote></details>

:100:

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2053)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 207 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2053#-OBtF14A-hdMiept1tGY:-OC2TTbt8Bg1VdlFTcxp:b6zz3r2) ([raw file](https://github.com/starkware-libs/sequencer/blob/8beaf77d44c7568f5b45bce0751f2c2577211871/crates/starknet_batcher/src/batcher.rs#L207)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

:100:
</blockquote></details>

 reverting my ack here, so Yair will see this too.

**Comment by Yael-Starkware** [comment]
### Merge activity

* **Nov 19, 3:52 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2053).

**Pull request merged**
