### PR TITLE
chore(deployment): cdk8s refactor

### PR DESCRIPTION
**Pull request by idan-starkware**

### CODE REVIEW

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2468)* status: 1 of 17 files reviewed, 1 unresolved discussion (waiting on @idan-starkware)

___
*[`deployments/sequencer/.gitignore` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2468#-OF1cdur1isDttTNbix-:-OF1cdusDOaMZv2TIBtj:bb7r2f0) ([raw file](https://github.com/starkware-libs/sequencer/blob/ebbf98c8fb575996d1231196056f571c0013bf33/deployments/sequencer/.gitignore#L3)):*
> ```ignore
> __pycache__/
> .idea/
> services/test.py
> ```

why?



_Code quote:_
```ignore
services/test.py
```

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2468)* status: 1 of 17 files reviewed, 2 unresolved discussions (waiting on @idan-starkware)

___
*[`deployments/sequencer/app/service.py` line 99 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2468#-OF1coTk5ufyR7lXMdkI:-OF1coTk5ufyR7lXMdkJ:btqcjgm) ([raw file](https://github.com/starkware-libs/sequencer/blob/ebbf98c8fb575996d1231196056f571c0013bf33/deployments/sequencer/app/service.py#L99)):*
> ```Python
> 
>     def _get_ingress_tls(self):
>         pass
> ```

add return type



_Code quote:_
```Python
    def _get_config_attr(self, attribute):
        config_attr = self.node_config.get(attribute).get('value')
        if config_attr is not None:
            return config_attr
        else:
            assert f'Config attribute "{attribute}" is missing.'

    def _get_container_ports(self):
        return [
            k8s.ContainerPort(
                container_port=self._get_config_attr(port)
            ) for port in ["http_server_config.port", "monitoring_endpoint_config.port"]
        ]

    def _get_container_resources(self):
        pass

    def _get_service_ports(self):
        return [
            k8s.ServicePort(
                name=attr.split("_")[0],
                port=self._get_config_attr(attr),
                target_port=k8s.IntOrString.from_number(self._get_config_attr(attr))
            ) for attr in ["http_server_config.port", "monitoring_endpoint_config.port"]
        ]

    def _get_http_probe(
            self,
            period_seconds: int = const.PROBE_PERIOD_SECONDS,
            failure_threshold: int = const.PROBE_FAILURE_THRESHOLD,
            timeout_seconds: int = const.PROBE_TIMEOUT_SECONDS
    ):
        path = "/monitoring/alive"
        # path = self.node_config['monitoring_path'].get("value") # TODO add monitoring path in node_config
        port = self.node_config.get('monitoring_endpoint_config.port').get("value")

        return k8s.Probe(
            http_get=k8s.HttpGetAction(
                path=path,
                port=k8s.IntOrString.from_number(port),
            ),
            period_seconds=period_seconds,
            failure_threshold=failure_threshold,
            timeout_seconds=timeout_seconds,
        )

    def _get_ingress_rules(self):
        pass

    def _get_ingress_paths(self):
        pass

    def _get_ingress_tls(self):
        pass
```

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2468)* status: 1 of 17 files reviewed, 3 unresolved discussions (waiting on @idan-starkware)

___
*[`deployments/sequencer/services/topology_helpers.py` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2468#-OF1cuhYDttKJGnP7d4Z:-OF1cuhYDttKJGnP7d4_:b3kre) ([raw file](https://github.com/starkware-libs/sequencer/blob/ebbf98c8fb575996d1231196056f571c0013bf33/deployments/sequencer/services/topology_helpers.py#L8)):*
> ```Python
> # types
> # config
> # validators
> ```

?



_Code quote:_
```Python
# replicas
# types
# config
# validators
```

**Review by idan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2468)* status: 1 of 17 files reviewed, 3 unresolved discussions (waiting on @alon-dotan-starkware and @idan-starkware)

___
*[`deployments/sequencer/.gitignore` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2468#-OF1cdur1isDttTNbix-:-OF1eNKF8dmDx1HwfQOd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ebbf98c8fb575996d1231196056f571c0013bf33/deployments/sequencer/.gitignore#L3)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

why?
</blockquote></details>

Done.
___
*[`deployments/sequencer/app/service.py` line 99 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2468#-OF1coTk5ufyR7lXMdkI:-OF1gO1g9DAefXe8a4f1:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ebbf98c8fb575996d1231196056f571c0013bf33/deployments/sequencer/app/service.py#L99)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

add return type
</blockquote></details>

Done.
___
*[`deployments/sequencer/services/topology_helpers.py` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2468#-OF1cuhYDttKJGnP7d4Z:-OF1gMjm3z40JHx1rGH5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ebbf98c8fb575996d1231196056f571c0013bf33/deployments/sequencer/services/topology_helpers.py#L8)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by alon-dotan-starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2468)* status: 2 of 17 files reviewed, 1 unresolved discussion (waiting on @idan-starkware)

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2468#-:-OF1w0a917m3Y9Ui76Y7:bnfp4nl)* status: 2 of 17 files reviewed, 1 unresolved discussion (waiting on @idan-starkware)

**Review by idan-starkware — COMMENTED** [review]
> Reviewed 13 of 16 files at r3, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2468)* status: all files reviewed, 1 unresolved discussion (waiting on @idan-starkware)

**Pull request merged**
