### PR TITLE
refactor(network): blacklist duration depends on reputation modifier (malicious / unstable)

### PR DESCRIPTION
**Pull request by AlonLStarkWare**
…(malicious / unstable)

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/587)

### CODE REVIEW

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/587)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @ShahakShama)

___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/587#-O5Cvdfv4Naw9Gck0aKE:-O5Cvdfv4Naw9Gck0aKF:b-ijuwhk) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0545dde096684c78a53b019086a0e968966e949/crates/papyrus_network/src/peer_manager/peer.rs#L65)):*
> ```XML
>     fn blocked_until(&self) -> Instant {
>         if self.timed_out_until > Instant::now() { self.timed_out_until } else { Instant::now() }
>         // self.timed_out_until.unwrap_or_else(Instant::now)
> ```

why is this a comment?

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/587)* status: all files reviewed, 8 unresolved discussions (waiting on @AlonLStarkWare)

___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 5 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/587#-O5MOALJ36DVcCb1hkh4:-O5MNp5T4KVNGcD8nA_o:b-zcl2ts) ([raw file](https://github.com/starkware-libs/sequencer/blob/078f33565d30110085144436e151292e7d8b458e/crates/papyrus_network/src/peer_manager/peer.rs#L5)):*
> ```XML
> use libp2p::swarm::ConnectionId;
> use libp2p::{Multiaddr, PeerId};
> use tokio::time::Instant;
> ```

Use tokio::time::Instant only in the single place where you need it: When you call Instant::now(), call `tokio::time::Instant::now().into_std()` and change this use statement to std. Add a comment above the now() call that explains you're doing this for the test so that tokio::time::advance will change the value of Instant::now()
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/587#-O5MOom1EC4jXECnJBGQ:-O5MOom1EC4jXECnJBGR:b-32b45f) ([raw file](https://github.com/starkware-libs/sequencer/blob/078f33565d30110085144436e151292e7d8b458e/crates/papyrus_network/src/peer_manager/peer.rs#L64)):*
> ```XML
> 
>     fn blocked_until(&self) -> Instant {
>         if self.timed_out_until > Instant::now() { self.timed_out_until } else { Instant::now() }
> ```

Try to see if the autoformatter is ok with making this multiline (not vscode's autoformatter, but the one in ci)
```
if ... {
    ...
} else {
    ...
}
```
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 234 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/587#-O5MPRwRA6ydQ1Lnxff3:-O5MPRwRA6ydQ1Lnxff4:b-kg3r7d) ([raw file](https://github.com/starkware-libs/sequencer/blob/078f33565d30110085144436e151292e7d8b458e/crates/papyrus_network/src/peer_manager/test.rs#L234)):*
> ```XML
> 
> #[tokio::test]
> async fn peer_block_realeased_after_timeout() {
> ```

not related to your pr, but if we're here let's fix this: fix the typo realeased -> released
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/587#-O5MPjfJ03qiE7A52I6a:-O5MPjfJ03qiE7A52I6b:bjgy4yq) ([raw file](https://github.com/starkware-libs/sequencer/blob/078f33565d30110085144436e151292e7d8b458e/crates/papyrus_network/src/peer_manager/test.rs#L244)):*
> ```XML
> 
> #[tokio::test]
> async fn peer_unstable_block_released_after_timeout() {
> ```

What's the difference between the test above and the new one here? They look the same
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 256 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/587#-O5MPqRCD5CjX7LykXGS:-O5MPqRCD5CjX7LykXGT:bjhdpre) ([raw file](https://github.com/starkware-libs/sequencer/blob/078f33565d30110085144436e151292e7d8b458e/crates/papyrus_network/src/peer_manager/test.rs#L256)):*
> ```XML
> fn report_peer_on_unknown_peer_id() {
>     // Create a new peer manager
>     let mut peer_manager: PeerManager<Peer> = PeerManager::new(PeerManagerConfig::default());
> ```

Change PeerManager to not be generic and remove the trait defined for Peer. This can be done in a future PR if you prefer
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 371 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/587#-O5MQCak4wkj4sDH4Pug:-O5MQCak4wkj4sDH4Puh:b-967gs5) ([raw file](https://github.com/starkware-libs/sequencer/blob/078f33565d30110085144436e151292e7d8b458e/crates/papyrus_network/src/peer_manager/test.rs#L371)):*
> ```XML
>     let peer1 = Peer::new(peer_id1, Multiaddr::empty());
> 
>     // Create a mock peer - not blocked
> ```

This is not a mock as well
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 375 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/587#-O5MQF2S5rfnkA1e0lz6:-O5MQF2S5rfnkA1e0lz7:b168ien) ([raw file](https://github.com/starkware-libs/sequencer/blob/078f33565d30110085144436e151292e7d8b458e/crates/papyrus_network/src/peer_manager/test.rs#L375)):*
> ```XML
>     let peer2 = Peer::new(peer_id2, Multiaddr::empty());
> 
>     // Add the mock peers to the peer manager
> ```

These are not mocks.
In general I think this comment is unnecessary so you can erase it

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/587)* status: 5 of 7 files reviewed, 8 unresolved discussions (waiting on @eitanm-starkware and @ShahakShama)

___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/587#-O5Cvdfv4Naw9Gck0aKE:-O5rcd8i8UZcwYyRMVZ7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b0545dde096684c78a53b019086a0e968966e949/crates/papyrus_network/src/peer_manager/peer.rs#L65)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

why is this a comment?
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 5 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/587#-O5MOALJ36DVcCb1hkh4:-O5wBDJJ8ekk4XRJZmuL:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/078f33565d30110085144436e151292e7d8b458e/crates/papyrus_network/src/peer_manager/peer.rs#L5)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Use tokio::time::Instant only in the single place where you need it: When you call Instant::now(), call `tokio::time::Instant::now().into_std()` and change this use statement to std. Add a comment above the now() call that explains you're doing this for the test so that tokio::time::advance will change the value of Instant::now()
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/peer_manager/peer.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/587#-O5MOom1EC4jXECnJBGQ:-O5rcbx_AUCxQffVKbkx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/078f33565d30110085144436e151292e7d8b458e/crates/papyrus_network/src/peer_manager/peer.rs#L64)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Try to see if the autoformatter is ok with making this multiline (not vscode's autoformatter, but the one in ci)
```
if ... {
    ...
} else {
    ...
}
```
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 234 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/587#-O5MPRwRA6ydQ1Lnxff3:-O5rcMMlACjhJKebxv_o:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/078f33565d30110085144436e151292e7d8b458e/crates/papyrus_network/src/peer_manager/test.rs#L234)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

not related to your pr, but if we're here let's fix this: fix the typo realeased -> released
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/587#-O5MPjfJ03qiE7A52I6a:-O5rcVsj27vsK1Nx3uE-:btd4sy0) ([raw file](https://github.com/starkware-libs/sequencer/blob/078f33565d30110085144436e151292e7d8b458e/crates/papyrus_network/src/peer_manager/test.rs#L244)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What's the difference between the test above and the new one here? They look the same
</blockquote></details>

You're right. I don't see any difference, I deleted one of them.
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 256 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/587#-O5MPqRCD5CjX7LykXGS:-O5rboV72Z7PGa78oWC5:b-gg5l4o) ([raw file](https://github.com/starkware-libs/sequencer/blob/078f33565d30110085144436e151292e7d8b458e/crates/papyrus_network/src/peer_manager/test.rs#L256)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change PeerManager to not be generic and remove the trait defined for Peer. This can be done in a future PR if you prefer
</blockquote></details>

I think it's better to do this in a separate PR.
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 371 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/587#-O5MQCak4wkj4sDH4Pug:-O5rbnbiCShdDrmIEMe4:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/078f33565d30110085144436e151292e7d8b458e/crates/papyrus_network/src/peer_manager/test.rs#L371)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is not a mock as well
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/peer_manager/test.rs` line 375 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/587#-O5MQF2S5rfnkA1e0lz6:-O5rbnQF0Uc5zcuSYGPI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/078f33565d30110085144436e151292e7d8b458e/crates/papyrus_network/src/peer_manager/test.rs#L375)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

These are not mocks.
In general I think this comment is unnecessary so you can erase it
</blockquote></details>

Done.

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/587)* status: all files reviewed, 6 unresolved discussions (waiting on @eitanm-starkware)

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/587)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @eitanm-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/587#-:-O5wqFwE95axmhMOaMF_:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @eitanm-starkware)

**Review by ShahakShama — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/587)* status: all files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware)

**Review by AlonLStarkWare — COMMENTED** [review]
> Dismissed @eitanm-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/587)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/587#-:-O6FcoQTDFtUZIzrmZbL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
