### PR TITLE
chore(blockifier): added gas vector computation mode to calculate_l1_…

### PR DESCRIPTION
**Pull request by amosStarkware**
…gas_by_vm_usage

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/706)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/706)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 193 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/706#-O5wtS6Y66XYtwL2Cqqf:-O5wtS6Z9y9KWFXz7zuF:bv7ylo9) ([raw file](https://github.com/starkware-libs/sequencer/blob/8f2ab38447963b98c8071438588c5f2bf266a865/crates/blockifier/src/fee/gas_usage.rs#L193)):*
> ```XML
>             0,
>             &GasVectorComputationMode::NoL2Gas,
>         )?)
> ```

get gas vector computation mode from tx type / add TODO



_Code quote:_
```XML
        + calculate_l1_gas_by_vm_usage(
            versioned_constants,
            &resources,
            0,
            &GasVectorComputationMode::NoL2Gas,
        )?)
```

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@TzahiTaub +reviewer:@Yoni-Starkware +reviewer:@nimrod-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/706#-:-O60Tb1c7FSWBTfDkLbd:b-opgrxl)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @nimrod-starkware, @TzahiTaub, and @Yoni-Starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/706)* status: 4 of 9 files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/706#-O61MWg722lD7TNvvzz6:-O61MWg82Q-OgVqQdyW8:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/563b1bb85844e9537c86dbff48cc7e35e91bbeb9/crates/blockifier/src/fee/fee_utils.rs#L36)):*
> ```XML
> /// a proof is determined similarly - by the (normalized) largest segment.
> /// The result can be in either L1 or L2 gas, according to the gas vector computation mode.
> pub fn calculate_l1_gas_by_vm_usage(
> ```





_Suggestion:_
```XML
get_vm_resources_cost
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/706#-O61MM3iBg_9f1CW1i7x:-O61MM3jBI4sDBdW1HhK:b4mgfhe) ([raw file](https://github.com/starkware-libs/sequencer/blob/563b1bb85844e9537c86dbff48cc7e35e91bbeb9/crates/blockifier/src/fee/fee_utils.rs#L40)):*
> ```XML
>     vm_resource_usage: &ExecutionResources,
>     n_reverted_steps: usize,
>     gas_vector_computation_mode: &GasVectorComputationMode,
> ```

`computation_mode`/`mode`



_Code quote:_
```XML
 gas_vector_computation_mode
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 460 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/706#-O61POAy8Xcud-S7jHIP:-O61POAz7WXq3K5Zob0l:bs0p5z8) ([raw file](https://github.com/starkware-libs/sequencer/blob/563b1bb85844e9537c86dbff48cc7e35e91bbeb9/crates/blockifier/src/transaction/objects.rs#L460)):*
> ```XML
> 
> impl From<&TransactionContext> for GasVectorComputationMode {
>     fn from(context: &TransactionContext) -> Self {
> ```

I don't think it is good practice to implement `From` that is not consuming the input. 
`get_gas_vector_computation_mode()` is good enough IMO



_Code quote:_
```XML
impl From<&TransactionContext> for GasVectorComputationMode {
    fn from(context: &TransactionContext) -> Self {
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 464 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/706#-O61MyQy55-Mjgp8OQmI:-O61MyQy55-Mjgp8OQmJ:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/563b1bb85844e9537c86dbff48cc7e35e91bbeb9/crates/blockifier/src/transaction/objects.rs#L464)):*
> ```XML
>             TransactionInfo::Current(info) => match info.resource_bounds {
>                 ValidResourceBounds::L1Gas(_) => GasVectorComputationMode::NoL2Gas,
>                 ValidResourceBounds::AllResources(_) => GasVectorComputationMode::AllGasAmounts,
> ```





_Suggestion:_
```XML
                ValidResourceBounds::AllResources(_) => GasVectorComputationMode::AllGasAmounts,
                ValidResourceBounds::L1Gas(_) => GasVectorComputationMode::NoL2Gas,
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/706)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/706#-O61MWg722lD7TNvvzz6:-O6C4aqP3A-1dr_aXE0T:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/563b1bb85844e9537c86dbff48cc7e35e91bbeb9/crates/blockifier/src/fee/fee_utils.rs#L36)):*
> ```XML
> /// a proof is determined similarly - by the (normalized) largest segment.
> /// The result can be in either L1 or L2 gas, according to the gas vector computation mode.
> pub fn calculate_l1_gas_by_vm_usage(
> ```

Done.
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/706#-O61MM3iBg_9f1CW1i7x:-O6C0fblBKS5lRNOzfr1:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/563b1bb85844e9537c86dbff48cc7e35e91bbeb9/crates/blockifier/src/fee/fee_utils.rs#L40)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

`computation_mode`/`mode`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 460 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/706#-O61POAy8Xcud-S7jHIP:-O6C0sTR2NaWNZlc92-A:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/563b1bb85844e9537c86dbff48cc7e35e91bbeb9/crates/blockifier/src/transaction/objects.rs#L460)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I don't think it is good practice to implement `From` that is not consuming the input. 
`get_gas_vector_computation_mode()` is good enough IMO
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/objects.rs` line 464 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/706#-O61MyQy55-Mjgp8OQmI:-O6C2mMF6AMOj1SfTzZS:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/563b1bb85844e9537c86dbff48cc7e35e91bbeb9/crates/blockifier/src/transaction/objects.rs#L464)):*
> ```XML
>             TransactionInfo::Current(info) => match info.resource_bounds {
>                 ValidResourceBounds::L1Gas(_) => GasVectorComputationMode::NoL2Gas,
>                 ValidResourceBounds::AllResources(_) => GasVectorComputationMode::AllGasAmounts,
> ```

Done

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r3, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/706#-:-O6FD9BR5eKZvvTZGS4O:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware and @TzahiTaub)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/706)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware and @TzahiTaub)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/706#-:-O6G3VgfEspgZoK9voBG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware and @TzahiTaub)

**Pull request merged**
