### PR TITLE
refactor(consensus): consensus takes a generic network receiver

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/249)

### CODE REVIEW

**Comment by matan-starkware** [comment]
* **#208** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/208?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#200** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/200?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#249** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/249?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by matan-starkware — COMMENTED** [review]
Accidentally deleted https://reviewable.io/reviews/starkware-libs/sequencer/112, revived here.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/249#-:-O3CZh695JRW9BorAcZy:bulodyc)* status: 0 of 1 files reviewed, all discussions resolved

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/249#-:-O3D0gp48FN8jDqYX2px:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Comment by matan-starkware** [comment]
### Merge activity

* **Aug 4, 5:04 AM EDT**: @matan-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/249).

**Pull request merged**
