### PR TITLE
feat: adding new parameters to the component execution config

### PR DESCRIPTION
**Pull request by lev-starkware**
commit-id:54781e9e

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/306)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_infra/Cargo.toml` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3Wsk66COh9K6VpJUXJ:-O3Wsk67-oFftAQizh6v:b-dkpeo) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_infra/Cargo.toml#L18)):*
> ```TOML
> bincode.workspace = true
> hyper = { workspace = true, features = ["client", "http2", "server", "tcp"] }
> papyrus_config = { path = "../papyrus_config", version = "0.4.0-rc.0" }
> ```

Do we need a specific version here?



_Code quote:_
```TOML
version = "0.4.0-rc.0"
```
___
*[`crates/mempool_infra/src/component_server/local_component_server.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3WtOSU8B_2nJq8L46d:-O3WtOSU8B_2nJq8L46e:b-q6xvp3) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_infra/src/component_server/local_component_server.rs#L118)):*
> ```XML
> 
> #[derive(Clone, Debug, Serialize, Deserialize, Validate, PartialEq)]
> pub struct LocalComponentServerConfig {
> ```

For consistency with the comment below regarding the remote config, please remove `server` from this name.



_Code quote:_
```XML
LocalComponentServerConfig
```
___
*[`crates/mempool_infra/src/component_server/local_component_server.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3WszrMET5MUfolEIqS:-O3WszrMET5MUfolEIqT:b-qrx70j) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_infra/src/component_server/local_component_server.rs#L122)):*
> ```XML
> }
> 
> const DEFAULT_CHANNEL_BUFFER_SIZE: u32 = 32;
> ```

Please sort the file structs/consts/impl according to the convention.



_Code quote:_
```XML
const DEFAULT_CHANNEL_BUFFER_SIZE: u32 = 32;
```
___
*[`crates/mempool_infra/src/component_server/remote_component_server.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3WtFE3C3LGc4y6qXe-:-O3WtFE3C3LGc4y6qXe0:b2ckw4u) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_infra/src/component_server/remote_component_server.rs#L26)):*
> ```XML
> 
> #[derive(Clone, Debug, Serialize, Deserialize, Validate, PartialEq)]
> pub struct RemoteComponentServerConfig {
> ```

Is this a specific config for the server? It seems to apply to the client. Can we drop `Server` from its name?



_Code quote:_
```XML
RemoteComponentServerConfig
```
___
*[`crates/mempool_infra/src/component_server/remote_component_server.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3Wt76yDXsIPelQItGu:-O3Wt76z54GnSemWU0zI:b-qrx70j) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_infra/src/component_server/remote_component_server.rs#L32)):*
> ```XML
> }
> 
> const DEFAULT_RETRIES: u32 = 3;
> ```

Please sort the file structs/consts/impl according to the convention.



_Code quote:_
```XML
const DEFAULT_RETRIES: u32 = 3;
```
___
*[`crates/mempool_node/src/config/mod.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3Wtt_k5dmtsF-5jp1r:-O3Wtt_k5dmtsF-5jp1s:b-xx0w1o) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_node/src/config/mod.rs#L36)):*
> ```XML
>     Local,
>     Remote,
> }
> ```

Please add a todo to include the Local/Remote config types as part of the enum.



_Code quote:_
```XML
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub enum LocationType {
    Local,
    Remote,
}
```
___
*[`crates/mempool_node/src/config/mod.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3WteIU3BN6xpAnBd5q:-O3WteIU3BN6xpAnBd5r:bfpn5st) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_node/src/config/mod.rs#L42)):*
> ```XML
>     IndependentComponent,
>     SynchronousComponent,
>     AsynchronousComponent,
> ```

Let's sync on these names.



_Code quote:_
```XML
    IndependentComponent,
    SynchronousComponent,
    AsynchronousComponent,
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/306)* status: 0 of 7 files reviewed, 9 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/config/mod.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3WvH2z0Tn9FIKhVPS2:-O3WvH2z0Tn9FIKhVPS3:b-42lwn0) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_node/src/config/mod.rs#L104)):*
> ```XML
>     component: &ComponentExecutionConfig,
> ) -> Result<(), ValidationError> {
>     if component.location == LocationType::Local && component.local_config.is_none() {
> ```

I'd slightly change the structure of this function.
Using `match`, I'd check that if `LocationType::Local` then `component.local_config.is_some() and component.remote_config.is_none()`, and if not, error with the message: "Local component missing local config or has a remote config".

That is, make sure that for local config the local config exists and the remote one doesn't.

Ditto for the remote config, respectively.



_Code quote:_
```XML
if component.location == LocationType::Local && component.local_config.is_none() {
```
___
*[`crates/mempool_node/src/config/mod.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3Ww1b28K_qDzXIg2Ke:-O3Ww1b28K_qDzXIg2Kf:b-nhsd35) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_node/src/config/mod.rs#L136)):*
> ```XML
>         }
>     }
> }
> ```

Why does the original `Derive` is now inadequate?



_Code quote:_
```XML
impl Default for ComponentConfig {
    fn default() -> Self {
        Self {
            gateway: ComponentExecutionConfig {
                component_type: ComponentType::IndependentComponent,
                ..ComponentExecutionConfig::default()
            },
            mempool: ComponentExecutionConfig::default(),
        }
    }
}
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/306)* status: 0 of 7 files reviewed, 9 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/Cargo.toml` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3Wsk66COh9K6VpJUXJ:-O3b_aNCCAXSKuQ31hPK:b-6x0tzj) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_infra/Cargo.toml#L18)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Do we need a specific version here?
</blockquote></details>

After discussion leaving as is.
___
*[`crates/mempool_infra/src/component_server/local_component_server.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3WtOSU8B_2nJq8L46d:-O3Y--ho5Y0yoAJ2-Fc2:b-dg995u) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_infra/src/component_server/local_component_server.rs#L118)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

For consistency with the comment below regarding the remote config, please remove `server` from this name.
</blockquote></details>

Moved to the component_definitions.rs and renamed.
___
*[`crates/mempool_infra/src/component_server/local_component_server.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3WszrMET5MUfolEIqS:-O3Y-9xh8xIw8rSjH8hT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_infra/src/component_server/local_component_server.rs#L122)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please sort the file structs/consts/impl according to the convention.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_server/remote_component_server.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3WtFE3C3LGc4y6qXe-:-O3Y-JCT42u823c0q3_4:b-dg995u) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_infra/src/component_server/remote_component_server.rs#L26)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Is this a specific config for the server? It seems to apply to the client. Can we drop `Server` from its name?
</blockquote></details>

Moved to the component_definitions.rs and renamed.
___
*[`crates/mempool_infra/src/component_server/remote_component_server.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3Wt76yDXsIPelQItGu:-O3Y-RJADcd6ccK0_sh8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_infra/src/component_server/remote_component_server.rs#L32)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please sort the file structs/consts/impl according to the convention.
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/config/mod.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3Wtt_k5dmtsF-5jp1r:-O3XqCPT6eo9GYkg8sS5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_node/src/config/mod.rs#L36)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add a todo to include the Local/Remote config types as part of the enum.
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/config/mod.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3WteIU3BN6xpAnBd5q:-O3ba4UI5OS_1Kl0PfBv:b-cs3fee) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_node/src/config/mod.rs#L42)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Let's sync on these names.
</blockquote></details>

Currently in discussion.
___
*[`crates/mempool_node/src/config/mod.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3WvH2z0Tn9FIKhVPS2:-O3b_SkD4Nmji9A-t7Nj:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_node/src/config/mod.rs#L104)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I'd slightly change the structure of this function.
Using `match`, I'd check that if `LocationType::Local` then `component.local_config.is_some() and component.remote_config.is_none()`, and if not, error with the message: "Local component missing local config or has a remote config".

That is, make sure that for local config the local config exists and the remote one doesn't.

Ditto for the remote config, respectively.
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/config/mod.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3Ww1b28K_qDzXIg2Ke:-O3baI2UBG-6HgOUnALm:b-dkulfl) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_node/src/config/mod.rs#L136)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Why does the original `Derive` is now inadequate?
</blockquote></details>

After discussion added gateway_defaul_config and mempool_default config functions.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/306)* status: 0 of 8 files reviewed, 7 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_infra/src/component_definitions.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3ck-gh7cUma3Yy6mbU:-O3ck-gi3_marN2bR_Ie:bwa6lj2) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a15381837f3582cd6db62aa22160ffa1fbd9934/crates/mempool_infra/src/component_definitions.rs#L59)):*
> ```XML
> #[derive(Clone, Debug, Serialize, Deserialize, Validate, PartialEq)]
> pub struct LocalComponentCommunicationConfig {
>     pub channel_buffer_size: u32,
> ```

Please use `usize` for counters, lengths, etc.
(this is also the type tokio uses -- https://docs.rs/tokio/latest/tokio/sync/mpsc/fn.channel.html )



_Code quote:_
```XML
u32
```
___
*[`crates/mempool_infra/src/component_definitions.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3ckdFJEMvn2HaysM8Z:-O3ckdFJEMvn2HaysM8_:b-89a4l7) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a15381837f3582cd6db62aa22160ffa1fbd9934/crates/mempool_infra/src/component_definitions.rs#L84)):*
> ```XML
>     pub ip: IpAddr,
>     pub port: u16,
>     pub retries: u32,
> ```

Ditto



_Code quote:_
```XML
u32
```
___
*[`crates/mempool_infra/src/component_definitions.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3cknQc-wD6To6Q6ipo:-O3cknQc-wD6To6Q6ipp:b-y5yepl) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a15381837f3582cd6db62aa22160ffa1fbd9934/crates/mempool_infra/src/component_definitions.rs#L114)):*
> ```XML
> impl Default for RemoteComponentCommunicationConfig {
>     fn default() -> Self {
>         Self { ip: "0.0.0.0".parse().unwrap(), port: 8080, retries: DEFAULT_RETRIES }
> ```

Can these be defined as consts as well?



_Code quote:_
```XML
"0.0.0.0".parse().unwrap(), port: 8080
```
___
*[`crates/mempool_node/src/config/config_test.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3cn0_dCNke8Kq-880H:-O3cn0_dCNke8Kq-880I:b4663iq) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a15381837f3582cd6db62aa22160ffa1fbd9934/crates/mempool_node/src/config/config_test.rs#L91)):*
> ```XML
>     component_exe_config.local_config = None;
>     assert!(component_exe_config.validate().is_ok());
> }
> ```

Please split into two tests: one that checks valid configs and one that checks invalid ones. In both tests use the `case` option to parameterize the config (and potentially the error message if that's also needed).

There's a code example in `crates/mempool_infra/tests/component_server_client_http_test.rs`, note you'd need the `rstest` dependency as well.



_Code quote:_
```XML
fn test_component_execution_config_validation() {
    // Set both local and remote communication config active and check that the validator finds an
    // error.
    let mut component_exe_config = ComponentExecutionConfig {
        location: LocationType::Local,
        local_config: Some(LocalComponentCommunicationConfig::default()),
        remote_config: Some(RemoteComponentCommunicationConfig::default()),
        ..ComponentExecutionConfig::default()
    };
    check_validation_error(
        component_exe_config.validate(),
        "Invalid component configuration.",
        "Local config and Remote config are mutually exclusive, can't be both active.",
    );

    // Initialize an invalid config for a Local component and check that the validator finds an
    // error.
    component_exe_config.local_config = None;
    check_validation_error(
        component_exe_config.validate(),
        "Invalid component configuration.",
        "Local communication config is missing.",
    );

    // Initialize a valid config for a Local component and check that the validator returns Ok.
    component_exe_config.local_config = Some(LocalComponentCommunicationConfig::default());
    component_exe_config.remote_config = None;
    assert!(component_exe_config.validate().is_ok());

    // Initialize an invalid config for a Remote component and check that the validator finds an
    // error.
    component_exe_config.location = LocationType::Remote;
    check_validation_error(
        component_exe_config.validate(),
        "Invalid component configuration.",
        "Remote communication config is missing.",
    );

    // Initialize a valid config for a Remote component and check that the validator returns Ok.
    component_exe_config.remote_config = Some(RemoteComponentCommunicationConfig::default());
    component_exe_config.local_config = None;
    assert!(component_exe_config.validate().is_ok());
}
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/306)* status: 0 of 8 files reviewed, 9 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/config/config_test.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3cp8Bt9YTbAYoD-z3y:-O3cp8Bt9YTbAYoD-z3z:b-z5vj93) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a15381837f3582cd6db62aa22160ffa1fbd9934/crates/mempool_node/src/config/config_test.rs#L107)):*
> ```XML
>         "Invalid components configuration.",
>         "At least one component should be allowed to execute.",
>     );
> ```

Please split to "valid" and "invalid" config tests.



_Code quote:_
```XML
    let mut component_config = ComponentConfig {
        gateway: ComponentExecutionConfig { execute: false, ..ComponentExecutionConfig::default() },
        mempool: ComponentExecutionConfig { execute: false, ..ComponentExecutionConfig::default() },
    };

    check_validation_error(
        component_config.validate(),
        "Invalid components configuration.",
        "At least one component should be allowed to execute.",
    );
```
___
*[`crates/mempool_node/src/config/config_test.rs` line 117 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3cofhcA3ZdSQqjjous:-O3cofhcA3ZdSQqjjout:bghabxy) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a15381837f3582cd6db62aa22160ffa1fbd9934/crates/mempool_node/src/config/config_test.rs#L117)):*
> ```XML
> 
>         assert_matches!(component_config.validate(), Ok(()));
>     }
> ```

Not part of this pr, but can you please explain what's going on here? Why does it make sense to cover all `execute` combinations?



_Code quote:_
```XML
    // Update the config to be valid and check that the validator finds no errors.
    for (gateway_component_execute, mempool_component_execute) in
        [(true, false), (false, true), (true, true)]
    {
        component_config.gateway.execute = gateway_component_execute;
        component_config.mempool.execute = mempool_component_execute;

        assert_matches!(component_config.validate(), Ok(()));
    }
```
___
*[`crates/mempool_node/src/config/mod.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3Wtt_k5dmtsF-5jp1r:-O3co8dbEc6hBdflZxhc:b-l924uu) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_node/src/config/mod.rs#L36)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please attach a name / names to the enum (add yourself, you can also add me).

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/306)* status: 0 of 9 files reviewed, 9 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/config/config_test.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3cn0_dCNke8Kq-880H:-O3h0EAh6SpBisoMQxd3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a15381837f3582cd6db62aa22160ffa1fbd9934/crates/mempool_node/src/config/config_test.rs#L91)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please split into two tests: one that checks valid configs and one that checks invalid ones. In both tests use the `case` option to parameterize the config (and potentially the error message if that's also needed).

There's a code example in `crates/mempool_infra/tests/component_server_client_http_test.rs`, note you'd need the `rstest` dependency as well.
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/config/config_test.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3cp8Bt9YTbAYoD-z3y:-O3h0CkV1YNi5H3Guf5t:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a15381837f3582cd6db62aa22160ffa1fbd9934/crates/mempool_node/src/config/config_test.rs#L107)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please split to "valid" and "invalid" config tests.
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/config/config_test.rs` line 117 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3cofhcA3ZdSQqjjous:-O3h0C5j7w7-XLZnrvH5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a15381837f3582cd6db62aa22160ffa1fbd9934/crates/mempool_node/src/config/config_test.rs#L117)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Not part of this pr, but can you please explain what's going on here? Why does it make sense to cover all `execute` combinations?
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/config/mod.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3Wtt_k5dmtsF-5jp1r:-O3hCdSD4oF444I4bSTF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_node/src/config/mod.rs#L36)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please attach a name / names to the enum (add yourself, you can also add me).
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/306)* status: 3 of 9 files reviewed, 6 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_infra/src/component_definitions.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3cknQc-wD6To6Q6ipo:-O3hxPQeDR9WwWQGtL7F:bead97o) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a15381837f3582cd6db62aa22160ffa1fbd9934/crates/mempool_infra/src/component_definitions.rs#L114)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

"0.0.0.0", "127.0.0.1", 80, 8080, and 8081 all are well-known values and are already actual constants. They all are used in this form in other places throughout this project.
</blockquote></details>

I would prefer these to be defined as consts at the top of the module. Leaving as an unblocked comment, please change unless you have a strong objection, and if so, leave as is.
___
*[`crates/mempool_node/src/config/config_test.rs` line 69 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3hyI-i9RCf_oC4K4yT:-O3hyI-i9RCf_oC4K4yU:b-lf3vxp) ([raw file](https://github.com/starkware-libs/sequencer/blob/6487942b891daeaf3ef344959e8fe099fb47bd97/crates/mempool_node/src/config/config_test.rs#L69)):*
> ```XML
>     #[case] location: LocationType,
>     #[case] local_config_flag: bool,
>     #[case] remote_config_flag: bool,
> ```

Please parameterize using the actual value instead of the creation flag, i.e., use `Some(LocalComponentCommunicationConfig::default()) }` or `{ None }` instead of `true` and `false`, respecitvely.



_Code quote:_
```XML
    #[case] local_config_flag: bool,
    #[case] remote_config_flag: bool,
```
___
*[`crates/mempool_node/src/config/config_test.rs` line 107 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3hyt5jDq_7IvAyRXPq:-O3hyt5jDq_7IvAyRXPr:b-rw0005) ([raw file](https://github.com/starkware-libs/sequencer/blob/6487942b891daeaf3ef344959e8fe099fb47bd97/crates/mempool_node/src/config/config_test.rs#L107)):*
> ```XML
>     } else {
>         None
>     };
> ```

Apply the requested change detailed in the previous comment here as well: parameterize using the config (`Some(...)` or `None`) instead of the creation flags.



_Code quote:_
```XML
    let local_config = if location == LocationType::Local {
        Some(LocalComponentCommunicationConfig::default())
    } else {
        None
    };
    let remote_config = if location == LocationType::Remote {
        Some(RemoteComponentCommunicationConfig::default())
    } else {
        None
    };
```
___
*[`crates/mempool_node/src/config/config_test.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3hzGrG2CIaa5yJ-o4_:-O3hzGrG2CIaa5yJ-o4a:bg6d6ll) ([raw file](https://github.com/starkware-libs/sequencer/blob/6487942b891daeaf3ef344959e8fe099fb47bd97/crates/mempool_node/src/config/config_test.rs#L118)):*
> ```XML
> 
> /// Test the validation of the struct ComponentConfig.
> /// The validation validates at least one of the components is set with execute: true.
> ```

This docstring is now redundant, no?



_Code quote:_
```XML
/// Test the validation of the struct ComponentConfig.
/// The validation validates at least one of the components is set with execute: true.
```
___
*[`crates/mempool_node/src/config/mod.rs` line 141 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3i-R-80cXMpEjlnLBW:-O3i-R-9B6l6xLAIPQ6M:bwlxtjf) ([raw file](https://github.com/starkware-libs/sequencer/blob/6487942b891daeaf3ef344959e8fe099fb47bd97/crates/mempool_node/src/config/mod.rs#L141)):*
> ```XML
>             "Remote communication config is missing."
>         } else {
>             ""
> ```

You can return `Ok(())` here, and then avoid the additional `if !error_message.is_empty()` condition.
I prefer the above suggestion, but up to you (non-blocking comment).



_Code quote:_
```XML
""
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/306)* status: 3 of 9 files reviewed, 6 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/config/mod.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3WteIU3BN6xpAnBd5q:-O3i-w7GAk3eXcpyyF7D:buong20) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_node/src/config/mod.rs#L42)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

Currently in discussion.
</blockquote></details>

We forgot to discuss these.
To avoid further delays due to this, please add a doc string for each option that details its purpose / goal. 
We can always refactor these at a later point.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/306#-:-O3lBT1TCkLfPAj57tVy:bnfp4nl)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/config/config_test.rs` line 69 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3hyI-i9RCf_oC4K4yT:-O3lB7HO8ts4g6um-InQ:bwov7yt) ([raw file](https://github.com/starkware-libs/sequencer/blob/6487942b891daeaf3ef344959e8fe099fb47bd97/crates/mempool_node/src/config/config_test.rs#L69)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please parameterize using the actual value instead of the creation flag, i.e., use `Some(LocalComponentCommunicationConfig::default()) }` or `{ None }` instead of `true` and `false`, respecitvely.
</blockquote></details>

Changing to non-blocking, please change and merge
___
*[`crates/mempool_node/src/config/config_test.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3hzGrG2CIaa5yJ-o4_:-O3lBHf0AS6qws_Ar5vD:byi7hw3) ([raw file](https://github.com/starkware-libs/sequencer/blob/6487942b891daeaf3ef344959e8fe099fb47bd97/crates/mempool_node/src/config/config_test.rs#L118)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

This docstring is now redundant, no?
</blockquote></details>

Please remove (unblocked)
___
*[`crates/mempool_node/src/config/mod.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3WteIU3BN6xpAnBd5q:-O3lBLEWEXp6n6vYhTf5:b3r4hhm) ([raw file](https://github.com/starkware-libs/sequencer/blob/80abe40f83fd888d33194731528378ef1da956f8/crates/mempool_node/src/config/mod.rs#L42)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

We forgot to discuss these.
To avoid further delays due to this, please add a doc string for each option that details its purpose / goal. 
We can always refactor these at a later point.
</blockquote></details>

Add discussed docstring.
___
*[`crates/mempool_node/src/config/mod.rs` line 141 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/306#-O3i-R-80cXMpEjlnLBW:-O3lBPb17VPjkDxg1jhX:b-w1budb) ([raw file](https://github.com/starkware-libs/sequencer/blob/6487942b891daeaf3ef344959e8fe099fb47bd97/crates/mempool_node/src/config/mod.rs#L141)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

You can return `Ok(())` here, and then avoid the additional `if !error_message.is_empty()` condition.
I prefer the above suggestion, but up to you (non-blocking comment).
</blockquote></details>

Consider changing (unblocked).

**Review by lev-starkware — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 2 of 6 files at r2, 1 of 4 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/306)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Pull request merged**
