### PR TITLE
feat(consensus): add new context impl with just the build proposal flow

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1193)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1193?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1195** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1195?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1194** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1194?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1193** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1193?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1192** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1192?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dan-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1193)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware and @matan-starkware)

___
*[`Cargo.lock` line 7231 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1193#-O8euA_a2mKUyo-xqCfo:-O8euA_a2mKUyo-xqCfp:b-lcik44) ([raw file](https://github.com/starkware-libs/sequencer/blob/61c3774e38fbd6e804bace7751669d01d787993f/Cargo.lock#L7231)):*
> ```TOML
> dependencies = [
>  "async-trait",
>  "chrono",
> ```

Why do we need chrono?



_Code quote:_
```TOML
"chrono",
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1193#-O8ay-Er0EKIA0dU-WzW:-O8ay-Er0EKIA0dU-WzX:b-iihsta) ([raw file](https://github.com/starkware-libs/sequencer/blob/61c3774e38fbd6e804bace7751669d01d787993f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L37)):*
> ```XML
> type HeightToIdToContent = BTreeMap<BlockNumber, HashMap<ProposalContentId, Vec<Transaction>>>;
> 
> const CHANNEL_SIZE: usize = 5000;
> ```

Please document.
Should this be configurable? If so, please add TODO



_Code quote:_
```XML
const CHANNEL_SIZE: usize = 5000;
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1193#-O8az8FyESAHP74Gqvmt:-O8az8FyESAHP74Gqvmu:b-qak95g) ([raw file](https://github.com/starkware-libs/sequencer/blob/61c3774e38fbd6e804bace7751669d01d787993f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L45)):*
> ```XML
>     // valid_proposals map upon completion, ensuring consistency across tasks.
>     valid_proposals: Arc<Mutex<HeightToIdToContent>>,
>     proposal_id: u64,
> ```

This seems odd. Consider adding a comment explaining why this is part of the state. 



_Code quote:_
```XML
proposal_id: u64,
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1193#-O8euGgwB1bnzpvutmGw:-O8euGgx-_VgyV685kPf:b942fom) ([raw file](https://github.com/starkware-libs/sequencer/blob/61c3774e38fbd6e804bace7751669d01d787993f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L81)):*
> ```XML
>         let build_proposal_input = BuildProposalInput {
>             proposal_id,
>             deadline: chrono::Utc::now() + timeout,
> ```

IMO we should use duration. We can proceed with the current implementation, but please add a TODO to reconsider this.



_Code quote:_
```XML
        let timeout =
            chrono::Duration::from_std(timeout).expect("Can't convert timeout to chrono::Duration");
        let build_proposal_input = BuildProposalInput {
            proposal_id,
            deadline: chrono::Utc::now() + timeout,
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1193#-O8fY5QnBPIc9gEIk5IB:-O8fY5QnBPIc9gEIk5IC:b-30yjpf) ([raw file](https://github.com/starkware-libs/sequencer/blob/61c3774e38fbd6e804bace7751669d01d787993f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L179)):*
> ```XML
>                 // Can be caused by consensus exiting early (e.g. sync).
>                 warn!("Failed to get proposal content: {e:?}");
>                 return;
> ```

Shouldn't we notify the bathcer in that case?



_Code quote:_
```XML
                // Can be caused by consensus exiting early (e.g. sync).
                warn!("Failed to get proposal content: {e:?}");
                return;
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1193#-O8fYw010dzcVd9IbUA9:-O8fYw010dzcVd9IbUAA:bj61exk) ([raw file](https://github.com/starkware-libs/sequencer/blob/61c3774e38fbd6e804bace7751669d01d787993f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L63)):*
> ```XML
>     assert_eq!(content_receiver.next().await, Some(vec![generate_invoke_tx(Felt::THREE)]));
>     assert!(content_receiver.next().await.is_none());
>     assert_eq!(fin_receiver.await.unwrap().0, Felt::ZERO);
> ```

Consider defining variables and use the same ones in mock and expected (in other cases as well)



_Code quote:_
```XML
 Felt::ZERO
```

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1193)* status: all files reviewed, 2 unresolved discussions (waiting on @asmaastarkware and @dan-starkware)

___
*[`Cargo.lock` line 7231 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1193#-O8euA_a2mKUyo-xqCfo:-O8fflIkB-LzLUNOJR5N:b7sn03s) ([raw file](https://github.com/starkware-libs/sequencer/blob/61c3774e38fbd6e804bace7751669d01d787993f/Cargo.lock#L7231)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why do we need chrono?
</blockquote></details>

Discussed with Yair (Batcher wants this)
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1193#-O8euGgwB1bnzpvutmGw:-O8fgrhFAdKQ65J3NtRh:bnsc0hx) ([raw file](https://github.com/starkware-libs/sequencer/blob/61c3774e38fbd6e804bace7751669d01d787993f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L81)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

IMO we should use duration. We can proceed with the current implementation, but please add a TODO to reconsider this.
</blockquote></details>

After the conversation with Yair do you still want this?
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1193#-O8fY5QnBPIc9gEIk5IB:-O8fgxEH9S5ZmmgZSof4:b-orumjy) ([raw file](https://github.com/starkware-libs/sequencer/blob/61c3774e38fbd6e804bace7751669d01d787993f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L179)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Shouldn't we notify the bathcer in that case?
</blockquote></details>

Good point

**Comment by dan-starkware** [comment]
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1193#-O8ay-Er0EKIA0dU-WzW:-O8g0U-S1k4IC2s8gjAI:b-4l8z6l) ([raw file](https://github.com/starkware-libs/sequencer/blob/61c3774e38fbd6e804bace7751669d01d787993f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L37)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please document.
Should this be configurable? If so, please add TODO
</blockquote></details>

Please add a short documentation as well

**Comment by dan-starkware** [comment]
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1193#-O8euGgwB1bnzpvutmGw:-O8g0km-CU5ao6lh45AL:b-ujzkt0) ([raw file](https://github.com/starkware-libs/sequencer/blob/61c3774e38fbd6e804bace7751669d01d787993f/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L81)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

After the conversation with Yair do you still want this?
</blockquote></details>

The TODO? Yes

**Review by dan-starkware — APPROVED** [review]
> Reviewed 3 of 5 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1193)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1193)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Comment by matan-starkware** [comment]
### Merge activity

* **Oct 9, 3:33 AM EDT**: @matan-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1193).

**Pull request merged**
