### PR TITLE
chore(blockifier): add syscalls_gas_costs struct

### PR DESCRIPTION
**Pull request by Yonatan-Starkware**

### CODE REVIEW

**Comment by Yonatan-Starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2359?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2359** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2359?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2359?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2327** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2327?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2247** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2247?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2188** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2188?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2067** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2067?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 566 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD0JKxM0KbCJ3xVNTDD:-OD0JKxNDVNDAOSEb6kM:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ab50eb22ede373cc5d2006d04e565751a3463ac/crates/blockifier/src/versioned_constants.rs#L566)):*
> ```XML
> 
> #[derive(Debug, Default, Deserialize)]
> pub struct SyscallsGasCosts {
> ```





_Suggestion:_
```XML
SyscallGasCosts
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 662 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD0JSZ64Jy6_yiUu0nt:-OD0JSZ7-uAK7VviR2MO:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ab50eb22ede373cc5d2006d04e565751a3463ac/crates/blockifier/src/versioned_constants.rs#L662)):*
> ```XML
>     // OS gas costs.
>     pub transaction_gas_cost: u64,
>     pub syscalls_gas_costs: SyscallsGasCosts,
> ```





_Suggestion:_
```XML
syscall_gas_costs
```
___
*[`crates/blockifier/resources/versioned_constants_0_13_4.json` line 120 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD0JdQf2Zsc967n0lef:-OD0JdQg5_l0KTI9Vzcx:bkalse2) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ab50eb22ede373cc5d2006d04e565751a3463ac/crates/blockifier/resources/versioned_constants_0_13_4.json#L120)):*
> ```JSON
>         },
>         "validated": "VALID",
>         "syscalls_gas_costs": {
> ```

We are going to remove these fields from the VC eventually, right?
so better to wait with this PR



_Code quote:_
```JSON
        "syscalls_gas_costs": {
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_0_13_4.json` line 121 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD0rpESDamc1Wbc1Ou1:-OD0rpESDamc1Wbc1Ou2:b-exygi) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f6b4f13489cc671813c1acab2e9a5863dbbb959/crates/blockifier/resources/versioned_constants_0_13_4.json#L121)):*
> ```JSON
>         "validated": "VALID",
>         "syscalls_gas_costs": {
>             "call_contract_gas_cost": {
> ```

Now you can remove the `_gas_cost` suffix



_Suggestion:_
```JSON
"call_contract"
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 567 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD0rwD86PNNcs3zHhwr:-OD0rwD86PNNcs3zHhws:b-xhoend) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f6b4f13489cc671813c1acab2e9a5863dbbb959/crates/blockifier/src/versioned_constants.rs#L567)):*
> ```XML
> #[derive(Debug, Default, Deserialize)]
> pub struct SyscallsGasCosts {
>     pub call_contract_gas_cost: u64,
> ```

Now you can remove this suffix



_Suggestion:_
```XML
pub call_contract: u64,
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 705 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD0sCQM1ca3rxbQn-Ny:-OD0sCQM1ca3rxbQn-Nz:b-ah4e27) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f6b4f13489cc671813c1acab2e9a5863dbbb959/crates/blockifier/src/versioned_constants.rs#L705)):*
> ```XML
>             BuiltinName::mul_mod => self.base_gas_costs.mul_mod_gas_cost,
>             BuiltinName::segment_arena => return Err(GasCostsError::VirtualBuiltin),
>             BuiltinName::output | BuiltinName::ecdsa => {
> ```

You should have a price for this builtin as well now



_Code quote:_
```XML
 BuiltinName::ecdsa 
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 682 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD0sNayDM7pgeeRoOdy:-OD0sNayDM7pgeeRoOdz:bg3scxf) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f6b4f13489cc671813c1acab2e9a5863dbbb959/crates/blockifier/src/versioned_constants.rs#L682)):*
> ```XML
>         }        
>     }
> }
> ```

Please remove this impl. This is only used in the parsing phase, so just do it there



_Code quote:_
```XML
impl BaseGasCosts {
    fn get(&self, key: &str) -> u64 {
        match key {
            "step_gas_cost" => self.step_gas_cost,
            "memory_hole_gas_cost" => self.memory_hole_gas_cost,
            "range_check_gas_cost" => self.range_check_gas_cost,
            "keccak_builtin_gas_cost" => self.keccak_builtin_gas_cost,
            "pedersen_gas_cost" => self.pedersen_gas_cost,
            "bitwise_builtin_gas_cost" => self.bitwise_builtin_gas_cost,
            "ecop_gas_cost" => self.ecop_gas_cost,
            "poseidon_gas_cost" => self.poseidon_gas_cost,
            "add_mod_gas_cost" => self.add_mod_gas_cost,
            "mul_mod_gas_cost" => self.mul_mod_gas_cost,
            "default_initial_gas_cost" => self.default_initial_gas_cost,
            "entry_point_initial_budget" => self.entry_point_initial_budget,
            "syscall_base_gas_cost" => self.syscall_base_gas_cost,
            "transaction_gas_cost" => self.transaction_gas_cost,
            _ => panic! ("unvalid key"),
        }
    }
}
```

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/resources/versioned_constants_0_13_4.json` line 98 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD17rD85Hnv7gKxCP56:-OD1SeR73CnC7_fq0UeL:bsd47ao) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f6b4f13489cc671813c1acab2e9a5863dbbb959/crates/blockifier/resources/versioned_constants_0_13_4.json#L98)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

It does not have to be on this PR, but please extract the builtins to a sub-category as well
</blockquote></details>

next PR, this one is already big enough

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: 11 of 19 files reviewed, 10 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_0_13_1_1.json` line 651 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD1YxPoEh5x3EbYsTvv:-OD1YxPoEh5x3EbYsTvw:batjyoy) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb04196a6788174793b1d3a3009fe2573905ce9e/crates/blockifier/resources/versioned_constants_0_13_1_1.json#L651)):*
> ```JSON
>         ]
>     }
> }
> ```

Revert this on all files

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: 11 of 19 files reviewed, 9 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 705 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD0sCQM1ca3rxbQn-Ny:-OD1ZRls3gAqQ3t7_zYi:b2nhswy) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f6b4f13489cc671813c1acab2e9a5863dbbb959/crates/blockifier/src/versioned_constants.rs#L705)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

The price should be 10561; it is not part of the VC for now. Should we add a PR like the keccak one to it?
</blockquote></details>

Yes
___
*[`crates/blockifier/src/versioned_constants.rs` line 667 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD1ZMWhEfYrhCisyXA0:-OD1ZMWiDzaGA6Jhg96E:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb04196a6788174793b1d3a3009fe2573905ce9e/crates/blockifier/src/versioned_constants.rs#L667)):*
> ```XML
> pub struct GasCosts {
>     pub base_gas_costs: BaseGasCosts, 
>     pub syscall_gas_costs: SyscallGasCosts,
> ```





_Suggestion:_
```XML
    pub base: BaseGasCosts,
    pub syscalls: SyscallGasCosts,
```

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 13 files at r3, 7 of 11 files at r4, 6 of 7 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: all files reviewed (commit messages unreviewed), 9 unresolved discussions (waiting on @avi-starkware and @Yonatan-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: 8 of 19 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 667 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD1ZMWhEfYrhCisyXA0:-OD20c0xEsSD1-nSrJiE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb04196a6788174793b1d3a3009fe2573905ce9e/crates/blockifier/src/versioned_constants.rs#L667)):*
> ```XML
> pub struct GasCosts {
>     pub base_gas_costs: BaseGasCosts, 
>     pub syscall_gas_costs: SyscallGasCosts,
> ```

Done.

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants_test.rs` line 201 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD19X9FDtknFgk87n0F:-OD20nNt7G5IanPQmF2E:b-ve7g7l) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f6b4f13489cc671813c1acab2e9a5863dbbb959/crates/blockifier/src/versioned_constants_test.rs#L201)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Can you add one nestes syscall to this test?
</blockquote></details>

Yes sure. Which one of them is nested?

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/resources/versioned_constants_0_13_1_1.json` line 136 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD21J3lD_KCPL76Z_Ek:-OD21J3m11vkcm0CRlnw:b-eisnp7) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb04196a6788174793b1d3a3009fe2573905ce9e/crates/blockifier/resources/versioned_constants_0_13_1_1.json#L136)):*
> ```JSON
>                 "step_gas_cost": 10
>             },
>             "library_call": {
> ```

before, in all the old versioned it was:
"library_call": {
    "call_contract": 1
}
Instead I copied the contents of call_contract. The reason is that the way it was written before made it more complicated to parse.

**Review by Yonatan-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: 1 of 19 files reviewed, 6 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_0_13_1_1.json` line 651 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD1YxPoEh5x3EbYsTvv:-OD23NZa3gRlmMbWme6H:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb04196a6788174793b1d3a3009fe2573905ce9e/crates/blockifier/resources/versioned_constants_0_13_1_1.json#L651)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Revert this on all files
</blockquote></details>

Done.
___
*[`crates/blockifier/resources/versioned_constants_0_13_4.json` line 121 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD0rpESDamc1Wbc1Ou1:-OD1GhmcCdT4CjDh3tAt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f6b4f13489cc671813c1acab2e9a5863dbbb959/crates/blockifier/resources/versioned_constants_0_13_4.json#L121)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Now you can remove the `_gas_cost` suffix
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 567 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD0rwD86PNNcs3zHhwr:-OD1GrJ_B4uRH6lT8exf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f6b4f13489cc671813c1acab2e9a5863dbbb959/crates/blockifier/src/versioned_constants.rs#L567)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Now you can remove this suffix
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 682 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD0sNayDM7pgeeRoOdy:-OD1WIJn1SOvy4G_ITfs:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f6b4f13489cc671813c1acab2e9a5863dbbb959/crates/blockifier/src/versioned_constants.rs#L682)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Please remove this impl. This is only used in the parsing phase, so just do it there
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 566 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD0JKxM0KbCJ3xVNTDD:-OD1HNZr1H_AMd1TrHQG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ab50eb22ede373cc5d2006d04e565751a3463ac/crates/blockifier/src/versioned_constants.rs#L566)):*
> ```XML
> 
> #[derive(Debug, Default, Deserialize)]
> pub struct SyscallsGasCosts {
> ```

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 662 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD0JSZ64Jy6_yiUu0nt:-OD1HOyA-3wVIgd99K9u:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ab50eb22ede373cc5d2006d04e565751a3463ac/crates/blockifier/src/versioned_constants.rs#L662)):*
> ```XML
>     // OS gas costs.
>     pub transaction_gas_cost: u64,
>     pub syscalls_gas_costs: SyscallsGasCosts,
> ```

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 12 files at r7, 1 of 8 files at r8, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: 17 of 19 files reviewed, 8 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants_test.rs` line 141 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD5jrdW6Uoye4qnWA5i:-OD5jrdW6Uoye4qnWA5j:bad60e9) ([raw file](https://github.com/starkware-libs/sequencer/blob/99ee65584181104362017a1fccdb85aa4848e098/crates/blockifier/src/versioned_constants_test.rs#L141)):*
> ```XML
>     for file in all_jsons_in_dir().map(Result::unwrap) {
>         serde_json::from_reader::<_, VersionedConstants>(&std::fs::File::open(&file).unwrap())
>             .unwrap_or_else(|_| self::panic!("Versioned constants JSON file {file:#?} is malformed"));
> ```

Is this necessary?



_Code quote:_
```XML
self::panic!
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 755 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD5kNQg5N5R12dGUH-f:-OD5kNQg5N5R12dGUH-g:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/99ee65584181104362017a1fccdb85aa4848e098/crates/blockifier/src/versioned_constants.rs#L755)):*
> ```XML
>             syscalls : syscalls,
>         };
>         Ok(gas_costs)
> ```





_Suggestion:_
```XML
        Ok(GasCosts {base, syscalls})
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 808 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD5kwUr4iYiA4jFq715:-OD5kwUr4iYiA4jFq716:bfli5yp) ([raw file](https://github.com/starkware-libs/sequencer/blob/99ee65584181104362017a1fccdb85aa4848e098/crates/blockifier/src/versioned_constants.rs#L808)):*
> ```XML
>     /// Recursively adds a key to gas costs, calculating its value after processing any nested keys.
>     // Invariant: there is no circular dependency between key definitions.
>     fn recursive_add_to_base(
> ```

Let's get rid of these recursive functions. Please change old VC to support that

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 10 of 12 files at r7, 2 of 8 files at r8, 4 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: 18 of 19 files reviewed, 7 unresolved discussions (waiting on @avi-starkware and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants_test.rs` line 201 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD19X9FDtknFgk87n0F:-OD6K9dIEmvhVCiguWb3:b-r34nrz) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f6b4f13489cc671813c1acab2e9a5863dbbb959/crates/blockifier/src/versioned_constants_test.rs#L201)):*
<details><summary><i>Previously, Yonatan-Starkware wrote…</i></summary><blockquote>

Yes sure. Which one of them is nested?
</blockquote></details>

Just that there will be a 
syscall_gas_cost: {
    your favorite syscall here
}

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 12 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: all files reviewed, 7 unresolved discussions (waiting on @avi-starkware and @Yonatan-Starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 15 of 15 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: all files reviewed, 6 unresolved discussions (waiting on @avi-starkware and @Yonatan-Starkware)

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 808 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD5kwUr4iYiA4jFq715:-ODKm58PCa5fcnu4XJya:b-by0s6a) ([raw file](https://github.com/starkware-libs/sequencer/blob/99ee65584181104362017a1fccdb85aa4848e098/crates/blockifier/src/versioned_constants.rs#L808)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Let's get rid of these recursive functions. Please change old VC to support that
</blockquote></details>

The following fields are part of the base gas costs and are still nested:
entry_point_initial_budget
default_initial_gas_cost
os_contract_addresses
syscall_base_gas_cost
transaction_gas_cost
We still need the recursive to handle them. I can get rid of the recursive, but it will require handle those in a different way.

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: all files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @Yonatan-Starkware, and @Yoni-Starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: all files reviewed, 5 unresolved discussions (waiting on @avi-starkware and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 808 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD5kwUr4iYiA4jFq715:-ODKybJN3Dhei1dkm3Of:bp5zpjk) ([raw file](https://github.com/starkware-libs/sequencer/blob/99ee65584181104362017a1fccdb85aa4848e098/crates/blockifier/src/versioned_constants.rs#L808)):*
<details><summary><i>Previously, Yonatan-Starkware wrote…</i></summary><blockquote>

The following fields are part of the base gas costs and are still nested:
entry_point_initial_budget
default_initial_gas_cost
os_contract_addresses
syscall_base_gas_cost
transaction_gas_cost
We still need the recursive to handle them. I can get rid of the recursive, but it will require handle those in a different way.
</blockquote></details>

transaction_gas_cost - can be removed (it is not used, right?)
os_contract_addresses is not recursive
The rest need `step_gas_cost`

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 808 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD5kwUr4iYiA4jFq715:-ODKzZ8yE5ttNw4SoBfi:b-wpf4bn) ([raw file](https://github.com/starkware-libs/sequencer/blob/99ee65584181104362017a1fccdb85aa4848e098/crates/blockifier/src/versioned_constants.rs#L808)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

transaction_gas_cost - can be removed (it is not used, right?)
os_contract_addresses is not recursive
The rest need `step_gas_cost`
</blockquote></details>

Hmmm but okay, not in this PR. Resolved

**Review by meship-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware and @Yonatan-Starkware)

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 705 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD0sCQM1ca3rxbQn-Ny:-ODMOBC0-gwqXrL3cBwT:bw672iu) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f6b4f13489cc671813c1acab2e9a5863dbbb959/crates/blockifier/src/versioned_constants.rs#L705)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

should the price be 0 in the old jsons? or the above?

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @Yonatan-Starkware, and @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-:-OD_UWXgEH5gYRLREBXV:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @Yonatan-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware)

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/resources/versioned_constants_0_13_4.json` line 120 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD0JdQf2Zsc967n0lef:-ODa00IhAfH7Bexu3E9E:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ab50eb22ede373cc5d2006d04e565751a3463ac/crates/blockifier/resources/versioned_constants_0_13_4.json#L120)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

We are going to remove these fields from the VC eventually, right?
so better to wait with this PR
</blockquote></details>

Done.

**Review by Yonatan-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: 11 of 21 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants_test.rs` line 141 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD5jrdW6Uoye4qnWA5i:-ODL5OiT3ukAKefNZNFA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/99ee65584181104362017a1fccdb85aa4848e098/crates/blockifier/src/versioned_constants_test.rs#L141)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Is this necessary?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 755 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2359#-OD5kNQg5N5R12dGUH-f:-ODKoq2P0Tetf2mUqDVn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/99ee65584181104362017a1fccdb85aa4848e098/crates/blockifier/src/versioned_constants.rs#L755)):*
> ```XML
>             syscalls : syscalls,
>         };
>         Ok(gas_costs)
> ```

Done.

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 6 of 10 files at r15, 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 3 of 4 files at r14, 6 of 10 files at r15, 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2359)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Pull request merged**
