### PR TITLE
feat(starknet_api): bump block hash constant prefix

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1244)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1244)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama and @yoavGrs)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1244#-O8f6YKS90MvYRbNn2uU:-O8f6YKS90MvYRbNn2uV:b-aavjsf) ([raw file](https://github.com/starkware-libs/sequencer/blob/96be5db8c2c0f9b11f3a846567a21a7771ad5bcc/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L206)):*
> ```XML
>         &STARKNET_BLOCK_HASH1
>     }
> }
> ```

consider making this a method of starknet_api's StarknetVersion,
or, define a `BlockHashConstant(Felt)` type and add `impl From<StarknetVersion> for BlockHashConstant`.
(this function defines a relation between two objects, maybe better to make it a behavior of one of the objects)



_Code quote:_
```XML
// The prefix constant for the block hash calculation.
fn block_hash_constant(starknet_version: &StarknetVersion) -> &LazyLock<Felt> {
    if starknet_version < &BlockHashVersion::VO_13_3.into() {
        &STARKNET_BLOCK_HASH0
    } else {
        &STARKNET_BLOCK_HASH1
    }
}
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1244)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @ShahakShama)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1244#-O8f6YKS90MvYRbNn2uU:-O8fMkQs2GnGNGSnmsm-:b4mq74u) ([raw file](https://github.com/starkware-libs/sequencer/blob/96be5db8c2c0f9b11f3a846567a21a7771ad5bcc/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L206)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

consider making this a method of starknet_api's StarknetVersion,
or, define a `BlockHashConstant(Felt)` type and add `impl From<StarknetVersion> for BlockHashConstant`.
(this function defines a relation between two objects, maybe better to make it a behavior of one of the objects)
</blockquote></details>

So let's do all the logic here according to the `BlockHashVersion` instead of `StarknetVersion`.
(And panic where the version < 0.13.2)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1244)* status: all files reviewed, 4 unresolved discussions (waiting on @ShahakShama and @yoavGrs)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1244#-O8fSWdP8ejvv3barkyj:-O8fSWdP8ejvv3barkyk:b8p14rh) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b3ae06d42cab95290a4e09eb889a3dc595d3e44/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L57)):*
> ```XML
>         if value < StarknetVersion(vec![0, 13, 2]) {
>             panic!("Starknet version {} is too low for block hash calculation", value);
>         } else if value < StarknetVersion(vec![0, 13, 3]) {
> ```

these two starknet versions should either
1. be hard-coded somewhere
2. be converted *from* the block hash version for comparison

I prefer not to have magic numbers in business logic..



_Code quote:_
```XML
        if value < StarknetVersion(vec![0, 13, 2]) {
            panic!("Starknet version {} is too low for block hash calculation", value);
        } else if value < StarknetVersion(vec![0, 13, 3]) {
```
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1244#-O8fSSl4ADJEDqm5KFY_:-O8fSSl4ADJEDqm5KFYa:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b3ae06d42cab95290a4e09eb889a3dc595d3e44/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L60)):*
> ```XML
>             BlockHashVersion::VO_13_2
>         } else {
>             BlockHashVersion::VO_13_3
> ```





_Suggestion:_
```XML
            Self::VO_13_2
        } else {
            Self::VO_13_3
```
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1244#-O8fRsFu411x4Wi33nNu:-O8fRsFu411x4Wi33nNv:bifqi2g) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b3ae06d42cab95290a4e09eb889a3dc595d3e44/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L63)):*
> ```XML
>         }
>     }
> }
> ```

don't panic in `From<>`; the caller should choose to panic or not



_Suggestion:_
```XML
impl TryFrom<StarknetVersion> for BlockHashVersion {
    fn try_from(value: StarknetVersion) -> StarknetApiResult<Self> {
        if value < StarknetVersion(vec![0, 13, 2]) {
            Err(StarknetApiError::VersionForBlockHash(value))
        } else if value < StarknetVersion(vec![0, 13, 3]) {
            Ok(BlockHashVersion::VO_13_2)
        } else {
            Ok(BlockHashVersion::VO_13_3)
        }
    }
}
```
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1244#-O8fSsI3CgpR0xteYTx7:-O8fSsI44Zu2lsLKzp9B:bsm65lh) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b3ae06d42cab95290a4e09eb889a3dc595d3e44/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L41)):*
> ```XML
>         BlockHashVersion::VO_13_3 => StarknetVersion(vec![0, 13, 3]),
>     }
> }
> ```

why is this no longer an `impl From<BlockHashVersion> for StarknetVersion` block? seems more natural



_Code quote:_
```XML
fn convert_to_starknet_version(block_hash_version: &BlockHashVersion) -> StarknetVersion {
    match block_hash_version {
        BlockHashVersion::VO_13_2 => StarknetVersion(vec![0, 13, 2]),
        BlockHashVersion::VO_13_3 => StarknetVersion(vec![0, 13, 3]),
    }
}
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1244)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @ShahakShama)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1244#-O8fSWdP8ejvv3barkyj:-O8fUwqz76-T9WNSd184:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b3ae06d42cab95290a4e09eb889a3dc595d3e44/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L57)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

these two starknet versions should either
1. be hard-coded somewhere
2. be converted *from* the block hash version for comparison

I prefer not to have magic numbers in business logic..
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1244#-O8fSSl4ADJEDqm5KFY_:-O8fUhv_BXysJ_eYLwvX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b3ae06d42cab95290a4e09eb889a3dc595d3e44/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L60)):*
> ```XML
>             BlockHashVersion::VO_13_2
>         } else {
>             BlockHashVersion::VO_13_3
> ```

Done.
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1244#-O8fRsFu411x4Wi33nNu:-O8fYRrn-aPmCZ6lnMGx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b3ae06d42cab95290a4e09eb889a3dc595d3e44/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L63)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't panic in `From<>`; the caller should choose to panic or not
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1244#-O8fSsI3CgpR0xteYTx7:-O8fUlIN1jrBgf5EvrcR:b-l8hv1) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b3ae06d42cab95290a4e09eb889a3dc595d3e44/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L41)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this no longer an `impl From<BlockHashVersion> for StarknetVersion` block? seems more natural
</blockquote></details>

It was not used outside of tests.
Anyway, now it's back in use.

**Pull request merged**
