### PR TITLE
feat(blockifier): update cairo native to 0.2.0-alpha.2

### PR DESCRIPTION
**Pull request by rodrigo-pino**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1241)

### CODE REVIEW

**Review by noaov1 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1241)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Review by avi-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1241)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1241)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 3 files at r8, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1241)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 3 files at r11, 1 of 1 files at r13, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1241)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Pull request merged**
