### PR TITLE
feat: adding consensus manager to main node function

### PR DESCRIPTION
**Pull request by lev-starkware**
commit-id:c08d1931

### CODE REVIEW

**Review by uriel-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/496#-:-O4ig8rN8y1kTDfroGSw:bnfp4nl)* status: 0 of 8 files reviewed, all discussions resolved

**Review by uriel-starkware — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/496)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/496)* status: all files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/communication.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/496#-O4jQlPxEM3nJiOb37_B:-O4jQlPyAMCYh5dmOcJL:bntsk5a) ([raw file](https://github.com/starkware-libs/sequencer/blob/7aea502bfced4e8470e1a62d104c522ede96640f/crates/mempool_node/src/communication.rs#L82)):*
> ```XML
> pub struct MempoolNodeClients {
>     batcher_client: Option<SharedBatcherClient>,
>     consensus_manager_client: Option<SharedConsensusManagerClient>,
> ```

Why does the mempool hold a consensus client? If there is a consensus client I need to understand what we expect the server to supply.



_Code quote:_
```XML
    consensus_manager_client: Option<SharedConsensusManagerClient
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/496)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/mempool_node/src/communication.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/496#-O4jQlPxEM3nJiOb37_B:-O4jey7h508F9bq556hZ:b-8gcd40) ([raw file](https://github.com/starkware-libs/sequencer/blob/7aea502bfced4e8470e1a62d104c522ede96640f/crates/mempool_node/src/communication.rs#L82)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why does the mempool hold a consensus client? If there is a consensus client I need to understand what we expect the server to supply.
</blockquote></details>

It's not a mempool. This structure holds all clients for the mempool node to use in creating components in the latter stage.
In any case, when we talked, you said that Sync would need to communicate with the Consensus so it, probably, would receive this client (in the future). The client itself is already defined in consensus_manager_types/communication.rs. And currently, it's only some template.

**Review by matan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/496)* status: all files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/communication.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/496#-O4jQlPxEM3nJiOb37_B:-O4kF1zF5wPIOMEABGJQ:b-2r3pol) ([raw file](https://github.com/starkware-libs/sequencer/blob/7aea502bfced4e8470e1a62d104c522ede96640f/crates/mempool_node/src/communication.rs#L82)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

It's not a mempool. This structure holds all clients for the mempool node to use in creating components in the latter stage.
In any case, when we talked, you said that Sync would need to communicate with the Consensus so it, probably, would receive this client (in the future). The client itself is already defined in consensus_manager_types/communication.rs. And currently, it's only some template.
</blockquote></details>

Yes sync will be a client, I just didn't think of that as coming from the mempool component.

**Review by lev-starkware — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/496)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Review by lev-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/496)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Pull request merged**
