### PR TITLE
test(blockifier_reexecution): reexecution test on blocks

### PR DESCRIPTION
**Pull request by aner-starkware**

### CODE REVIEW

**Review by AvivYossef-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1820)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1820#-OB0sZsK6QLun996xJ8u:-OB0sZsK6QLun996xJ8v:b-sb09mc) ([raw file](https://github.com/starkware-libs/sequencer/blob/61ea9d22cdf06d06b94510cf0e713ba5ec6e6186/crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs#L20)):*
> ```XML
> use starknet_gateway::rpc_objects::BlockHeader;
> 
> use super::utils::reexecute_block_for_testing;
> ```

use::crate::state_reader::utils::reexecute_block_for_testing
___
*[`crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1820#-OB0tMG14rR0sS8ntuIO:-OB0tMG14rR0sS8ntuIP:bvs3l4j) ([raw file](https://github.com/starkware-libs/sequencer/blob/61ea9d22cdf06d06b94510cf0e713ba5ec6e6186/crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs#L168)):*
> ```XML
> #[case(780008)] // Contains invoke with replace class syscall.
> #[ignore = "Requires downloading JSON files prior to running; Long test, run with --release flag."]
> fn test_block_reexecution(#[case] block_number: u64) {
> ```

WTYT about using the function get_block_numbers_for_reexecution
here
https://reviewable.io/reviews/starkware-libs/sequencer/1796

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1820)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1820#-OB0xwgJ1qPESpIvgsYQ:-OB0xwgJ1qPESpIvgsYR:bld670d) ([raw file](https://github.com/starkware-libs/sequencer/blob/61ea9d22cdf06d06b94510cf0e713ba5ec6e6186/crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs#L166)):*
> ```XML
> #[case(750000)] // 0.13.2.1
> #[case(870136)] // Contains invoke with deploy syscall.
> #[case(780008)] // Contains invoke with replace class syscall.
> ```

give names to all test cases like this (will appear in console output, useful)



_Suggestion:_
```XML
#[case::0_13_0(600001)]
#[case(620978)] // 0.13.1
#[case(649367)] // 0.13.1.1
#[case(685878)] // 0.13.2
#[case(700000)] // 0.13.2.1
#[case(750000)] // 0.13.2.1
#[case::invoke_with_deploy_syscall(870136)]
#[case(780008)] // Contains invoke with replace class syscall.
```
___
*[`crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1820#-OB0tMG14rR0sS8ntuIO:-OB0xh5R9S-tFmlxWU55:b-atllbo) ([raw file](https://github.com/starkware-libs/sequencer/blob/61ea9d22cdf06d06b94510cf0e713ba5ec6e6186/crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs#L168)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

WTYT about using the function get_block_numbers_for_reexecution
here
https://reviewable.io/reviews/starkware-libs/sequencer/1796
</blockquote></details>

the problem is that this won't take advantage of cargo-test parallelization...

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1820)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1820#-OB0sZsK6QLun996xJ8u:-OB12Sn96owIqXnol0Y8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/61ea9d22cdf06d06b94510cf0e713ba5ec6e6186/crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs#L20)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

use::crate::state_reader::utils::reexecute_block_for_testing
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1820#-OB0tMG14rR0sS8ntuIO:-OB12TJ8DcyC9zxPMDIo:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/61ea9d22cdf06d06b94510cf0e713ba5ec6e6186/crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs#L168)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the problem is that this won't take advantage of cargo-test parallelization...
</blockquote></details>

Done.

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1820)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1820#-OB0xwgJ1qPESpIvgsYQ:-OB12e1PDM_jS5m-RCWV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/61ea9d22cdf06d06b94510cf0e713ba5ec6e6186/crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs#L166)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

give names to all test cases like this (will appear in console output, useful)
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1820#-OB0tMG14rR0sS8ntuIO:-OB12bNhDAqLukAb_D0l:buix1l3) ([raw file](https://github.com/starkware-libs/sequencer/blob/61ea9d22cdf06d06b94510cf0e713ba5ec6e6186/crates/blockifier_reexecution/src/state_reader/raw_rpc_json_test.rs#L168)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, wrong discussion

**Pull request closed without merging**
