### PR TITLE
feat(consensus): add remaining API implementations to sequencer context

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1196)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1196?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1196** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1196?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1195** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1195?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1194** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1194?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1193** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1193?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1192** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1192?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1196)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @asmaastarkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1196#-O8lAp_H936aNjHzcj7y:-O8lAp_N4x8ITeskYcz3:b-xx1c6u) ([raw file](https://github.com/starkware-libs/sequencer/blob/7ba795e3375e8a0fd79f81ff81c2ec31c7a850b6/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L141)):*
> ```XML
> 
>     fn proposer(&self, _height: BlockNumber, _round: Round) -> ValidatorId {
>         *self.validators.first().expect("validators should have at least 2 validators")
> ```

Why 2?



_Code quote:_
```XML
 *self.validators.first().expect("validators should have at least 2 validators"
```

**Review by dan-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1196)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @matan-starkware)

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1196#-:-O8qJMlV40lw5-IHZtpL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

**Comment by matan-starkware** [comment]
### Merge activity

* **Oct 10, 8:06 AM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1196).

**Pull request merged**
