### PR TITLE
feat(consensus): make the fields of BroadcastTopicClient public, used for test construction

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1198)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1198?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1198** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1198?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1197** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1197?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1196** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1196?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1195** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1195?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1194** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1194?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1193** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1193?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1192** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1192?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by dan-starkware** [comment]
If this is for testing only, maybe add conditionally compiled public getters instead (or another workaround)?

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1198)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @asmaastarkware, @dan-starkware, @eitanm-starkware, and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1198#-O8X72-yDHw3JngrtTdn:-O8a8wQs7x7MkaxYk1cn:b-ge6bgn) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

If this is for testing only, maybe add conditionally compiled public getters instead (or another workaround)?
</blockquote></details>

Discussed f2f, adding public new function which will be used everywhere.

___

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1198#-:-O8atgYDDNfiiUClaoFu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware, @eitanm-starkware, and @ShahakShama)

**Comment by matan-starkware** [comment]
### Merge activity

* **Oct 7, 8:15 AM EDT**: @matan-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1198).

**Pull request merged**
