### PR TITLE
chore(sequencer_node): remove chain_id from config

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #1725
- #1710 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by nadin-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1710)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/config/node_config.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1710#-OAgxtrrDilSjePnNC1O:-OAgxtrrDilSjePnNC1P:bbnor81) ([raw file](https://github.com/starkware-libs/sequencer/blob/e01b741cc961ce9cfe89b01b5ae27c0fbb250b3d/crates/mempool_node/src/config/node_config.rs#L64)):*
> ```XML
>     /// The [chain id](https://docs.rs/starknet_api/latest/starknet_api/core/struct.ChainId.html) of the Starknet network.
>     #[validate(custom = "validate_ascii")]
>     pub chain_id: ChainId,
> ```

Why not adding the required params as a field here?

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1710)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/mempool_node/src/config/node_config.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1710#-OAgxtrrDilSjePnNC1O:-OAktbvR-15ujvffGuN4:b-dwcosd) ([raw file](https://github.com/starkware-libs/sequencer/blob/e01b741cc961ce9cfe89b01b5ae27c0fbb250b3d/crates/mempool_node/src/config/node_config.rs#L64)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Why not adding the required params as a field here?
</blockquote></details>

They are implicitly added as pointer params. Let's further discuss f2f.

**Review by nadin-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1710#-:-OAlPJFb0g_oFky6DA8w:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#1725](https://github.com/starkware-libs/sequencer/pull/1725)

**Pull request closed without merging**
