### PR TITLE
chore(sequencer_infra): rename sequencer infra package

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
commit-id:afb5835e

---

**Stack**:
- #1516
- #1513
- #1512 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 50 of 50 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1512#-:-O9mz7Uc4rx4Vw9QPXhF:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`Cargo.toml` line 221 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1512#-O9myDBr0TyZTN_Styyd:-O9myDBr0TyZTN_Styye:bhrg42l) ([raw file](https://github.com/starkware-libs/sequencer/blob/b1f296a91427e791ac0a6749ebdd1d56e62b858f/Cargo.toml#L221)):*
> ```TOML
> starknet_monitoring_endpoint = { path = "crates/monitoring_endpoint", version = "0.0.0" }
> starknet_patricia = { path = "crates/starknet_patricia", version = "0.0.0" }
> starknet_sequencer_infra = { path = "crates/mempool_infra", version = "0.0.0" }
> ```

Are you also renaming the directory? I think that's what was more important 



_Code quote:_
```TOML
starknet_sequencer_infra = { path = "crates/mempool_infra", version = "0.0.0" }
```
___
*[`crates/task_executor/src/lib.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1512#-O9mym5F9vFWRK7JWR_1:-O9mym5F9vFWRK7JWR_2:b-qlzxg1) ([raw file](https://github.com/starkware-libs/sequencer/blob/b1f296a91427e791ac0a6749ebdd1d56e62b858f/crates/task_executor/src/lib.rs#L2)):*
> ```XML
> //! This crate contains the async and blocking tasks Executor, which is temporarily placed here.
> //! It will likely be moved to `starknet_sequencer_infra` or some other infra crate in the future.
> ```

I think this is refering to the crate (directory name) and not the package, which is unchanged here.



_Suggestion:_
```XML
mempool_infra
```

**Review by alonh5 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1512)* status: all files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/tests-integration/Cargo.toml` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1512#-O9mzh2uCD27rh-mrGxs:-O9mzh2uCD27rh-mrGxt:b-fo7juy) ([raw file](https://github.com/starkware-libs/sequencer/blob/b1f296a91427e791ac0a6749ebdd1d56e62b858f/crates/tests-integration/Cargo.toml#L48)):*
> ```TOML
> pretty_assertions.workspace = true
> rstest.workspace = true
> starknet_sequencer_infra.workspace = true
> ```

Unrelated to this PR, but I think this can be removed from dev-dependencies if it's already in dependencies.



_Code quote:_
```TOML
starknet_sequencer_infra.workspace = true
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1512)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`Cargo.toml` line 221 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1512#-O9myDBr0TyZTN_Styyd:-O9n6BbCBArgXoybGcWg:b-3w2am4) ([raw file](https://github.com/starkware-libs/sequencer/blob/b1f296a91427e791ac0a6749ebdd1d56e62b858f/Cargo.toml#L221)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Are you also renaming the directory? I think that's what was more important
</blockquote></details>

In a different pr, didn't want to mix שמחה ושמחה
___
*[`crates/tests-integration/Cargo.toml` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1512#-O9mzh2uCD27rh-mrGxs:-O9oDqx0EusBmLdL5Qbn:b-xgkuao) ([raw file](https://github.com/starkware-libs/sequencer/blob/b1f296a91427e791ac0a6749ebdd1d56e62b858f/crates/tests-integration/Cargo.toml#L48)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Unrelated to this PR, but I think this can be removed from dev-dependencies if it's already in dependencies.
</blockquote></details>

Noted, added a task on my monday for that

**Review by alonh5 — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1512)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/task_executor/src/lib.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1512#-O9mym5F9vFWRK7JWR_1:-O9oSEjiCiui6ahu1J71:b2nhkyh) ([raw file](https://github.com/starkware-libs/sequencer/blob/b1f296a91427e791ac0a6749ebdd1d56e62b858f/crates/task_executor/src/lib.rs#L2)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I think this is refering to the crate (directory name) and not the package, which is unchanged here.
</blockquote></details>

No?

**Pull request merged**
