### PR TITLE
feat(batcher): use the use_kzg_da flag in batcher block builder

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2226?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2226** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2226?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2226?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2219** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2219?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2226)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/proposal_manager.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2226#-OCEHGzv3P8I7obKuju2:-OCEHGzv3P8I7obKuju3:b-65jm3p) ([raw file](https://github.com/starkware-libs/sequencer/blob/17e423f560e12c7fa623f804d1d0b4a47be2ee76/crates/starknet_batcher/src/proposal_manager.rs#L68)):*
> ```XML
>         &mut self,
>         height: BlockNumber,
>         use_kzg_da: bool,
> ```

Consider bundling the fields into a struct, that way, you could also remove the clippy override. It will be even more important and convenient when adding the next fields.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2226)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/starknet_batcher/src/proposal_manager.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2226#-OCEHGzv3P8I7obKuju2:-OCEL70oCMVyUTgU0Bn0:b9bq9qg) ([raw file](https://github.com/starkware-libs/sequencer/blob/17e423f560e12c7fa623f804d1d0b4a47be2ee76/crates/starknet_batcher/src/proposal_manager.rs#L68)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Consider bundling the fields into a struct, that way, you could also remove the clippy override. It will be even more important and convenient when adding the next fields.
</blockquote></details>

maybe a BlockInfo struct should be passed here.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2226)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @dafnamatsry)

___
*[`crates/starknet_batcher/src/proposal_manager.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2226#-OCEHGzv3P8I7obKuju2:-OCE_AAw5iGWQK-MQT66:bntfvyv) ([raw file](https://github.com/starkware-libs/sequencer/blob/17e423f560e12c7fa623f804d1d0b4a47be2ee76/crates/starknet_batcher/src/proposal_manager.rs#L68)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

maybe a BlockInfo struct should be passed here.
</blockquote></details>

See #2231 towards that goal.

**Comment by ArniStarkware** [comment]
Closing this PR, as a more end-to-end approach was taken. See #2238

**Pull request closed without merging**
