### PR TITLE
chore(starknet_monitoring_endpoint): add metric test utils

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #2888
- #2885
- #2884 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by nadin-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2884)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_monitoring_endpoint/src/test_utils.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2884#-OEnOZNS50Z05SCfJlpE:-OEnOZNS50Z05SCfJlpF:b-sqtiht) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2cda4ad099004fbb6f5a99fafe7448c7c1afa77/crates/starknet_monitoring_endpoint/src/test_utils.rs#L87)):*
> ```XML
> 
>         // Parse the response body.
>         let body_bytes = hyper::body::to_bytes(response.into_body()).await.unwrap();
> ```

Import hyper::body::to_bytes



_Code quote:_
```XML
hyper::body::to_bytes
```
___
*[`crates/starknet_monitoring_endpoint/src/test_utils.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2884#-OEnPq5Y7crL5P2cdzc6:-OEnPq5Y7crL5P2cdzc7:bb73xfv) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2cda4ad099004fbb6f5a99fafe7448c7c1afa77/crates/starknet_monitoring_endpoint/src/test_utils.rs#L88)):*
> ```XML
>         // Parse the response body.
>         let body_bytes = hyper::body::to_bytes(response.into_body()).await.unwrap();
>         let body_string = String::from_utf8(body_bytes.to_vec()).unwrap();
> ```

Same



_Code quote:_
```XML
String::from_utf8
```
___
*[`crates/starknet_monitoring_endpoint/src/test_utils.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2884#-OEnODgg-crR9xiZ6KoK:-OEnODgg-crR9xiZ6KoL:bet4lk5) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2cda4ad099004fbb6f5a99fafe7448c7c1afa77/crates/starknet_monitoring_endpoint/src/test_utils.rs#L96)):*
> ```XML
> }
> 
> pub(crate) fn build_request(ip: &IpAddr, port: u16, method: &str) -> Request<Body> {
> ```

Please add TODO to pass the socket as an arg instead.



_Code quote:_
```XML
ip: &IpAddr, port: u16
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2884)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/starknet_monitoring_endpoint/src/test_utils.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2884#-OEnOZNS50Z05SCfJlpE:-OEnVMKc-LYMI4cXC2S2:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2cda4ad099004fbb6f5a99fafe7448c7c1afa77/crates/starknet_monitoring_endpoint/src/test_utils.rs#L87)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Import hyper::body::to_bytes
</blockquote></details>

Done.
___
*[`crates/starknet_monitoring_endpoint/src/test_utils.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2884#-OEnPq5Y7crL5P2cdzc6:-OEnVMZf5GtADbjq8cXG:b-h0f8sa) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2cda4ad099004fbb6f5a99fafe7448c7c1afa77/crates/starknet_monitoring_endpoint/src/test_utils.rs#L88)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Doesn't apply here, it's a class function of `A` (like calling `A::new()`), it's not a function from a module `String`.
___
*[`crates/starknet_monitoring_endpoint/src/test_utils.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2884#-OEnODgg-crR9xiZ6KoK:-OEnV7Eu16zkuJiFE1LL:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2cda4ad099004fbb6f5a99fafe7448c7c1afa77/crates/starknet_monitoring_endpoint/src/test_utils.rs#L96)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Please add TODO to pass the socket as an arg instead.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2884)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by nadin-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2884)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2884)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
