### PR TITLE
chore(blockifier): replace entry_point_gas_cost with initial_budget

### PR DESCRIPTION
**Pull request by Yonatan-Starkware**

### CODE REVIEW

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2247)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @Yonatan-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants_test.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2247#-OChdJCWB9YapG8Pc98J:-OChdJCX3JQ_MaZ17fRJ:b-l3skh6) ([raw file](https://github.com/starkware-libs/sequencer/blob/49bcd5767b971a00866f446eb13127d9ccc50b54/crates/blockifier/src/versioned_constants_test.rs#L25)):*
> ```XML
>             "entry_point_initial_budget": 4,
>             "step_gas_cost": 5
>         },
> ```

It bothers me a bit because this is not how transaction gas cost would look in 0.13.4 and further, but  AFAIK, this test will only apply to the older versions, so I think it is OK  



_Code quote:_
```XML
        },
        "transaction_gas_cost": {
            "entry_point_initial_budget": 4,
            "step_gas_cost": 5
        },
```
___
*[`crates/blockifier/resources/versioned_constants_0_13_2.json` line 640 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2247#-OChcQJc3drTVpW3XlSc:-OChcQJc3drTVpW3XlSd:b-kca28b) ([raw file](https://github.com/starkware-libs/sequencer/blob/49bcd5767b971a00866f446eb13127d9ccc50b54/crates/blockifier/resources/versioned_constants_0_13_2.json#L640)):*
> ```JSON
>         ]
>     }
> }
> ```

Add an empty line to this file. 



_Code quote:_
```JSON
  
```
___
*[`crates/blockifier/resources/versioned_constants_0_13_2_1.json` line 640 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2247#-OChcb8-5B58flgbOqdw:-OChcb8-5B58flgbOqdx:bb73xfv) ([raw file](https://github.com/starkware-libs/sequencer/blob/49bcd5767b971a00866f446eb13127d9ccc50b54/crates/blockifier/resources/versioned_constants_0_13_2_1.json#L640)):*
> ```JSON
>         ]
>     }
> }
> ```

Same
___
*[`crates/blockifier/resources/versioned_constants_0_13_3.json` line 640 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2247#-OChcfe70CGqiUDmv3QC:-OChcfe70CGqiUDmv3QD:bb73xfv) ([raw file](https://github.com/starkware-libs/sequencer/blob/49bcd5767b971a00866f446eb13127d9ccc50b54/crates/blockifier/resources/versioned_constants_0_13_3.json#L640)):*
> ```JSON
>         ]
>     }
> }
> ```

Same

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/cairo_native` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2247#-OCmEYxq2oQt27UTtfKz:-OCmEYxq2oQt27UTtfL-:b-at4ugi) ([raw file](https://github.com/starkware-libs/sequencer/blob/23231e473f6a0af25e233959360ab3f988b3ed15/crates/blockifier/cairo_native#L1)):*
> ```
> Subproject commit 76e83965d3bf1252eb6c68200a3accd5fd1ec004
> ```

reminder: solve this before merging

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2247#-:-OCmrZpm0lVs0jK_vKTQ:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @avi-starkware and @Yonatan-Starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 10 of 12 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2247)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2247)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 13 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2247#-:-OD1yI3D9336dm7lC7qI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2247)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Pull request merged**
