### PR TITLE
feat(blockifier): add `NativeSyscallHandler`

### PR DESCRIPTION
**Pull request by varex83**
This PR is follow-up after https://github.com/starkware-libs/sequencer/pull/429

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/549)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 18 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/549)* status: 18 of 22 files reviewed, all discussions resolved

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/549)* status: 19 of 22 files reviewed, all discussions resolved

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/549)* status: 20 of 22 files reviewed, 1 unresolved discussion (waiting on @varex83)

___
*[`crates/blockifier/src/execution/native/utils_test.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/549#-O5DQu-VBdb9Xeuz8W9z:-O5DQu-VBdb9Xeuz8WA-:bxn9163) ([raw file](https://github.com/starkware-libs/sequencer/blob/18ec25ea2d6a3881200039e04c89723027a4bb41/crates/blockifier/src/execution/native/utils_test.rs#L29)):*
> ```XML
> 
>     let res = decode_felts_as_str(&felts);
>     dbg!(res.as_bytes());
> ```

Is the print here intentional? If so, what is its purpose?



_Code quote:_
```XML
   dbg!(res.as_bytes());
```

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/549)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @varex83)

**Review by varex83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/549)* status: 16 of 22 files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

___
*[`crates/blockifier/src/execution/native/utils_test.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/549#-O5DQu-VBdb9Xeuz8W9z:-O5I99Fe-q6bfqkcejS4:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/18ec25ea2d6a3881200039e04c89723027a4bb41/crates/blockifier/src/execution/native/utils_test.rs#L29)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Is the print here intentional? If so, what is its purpose?
</blockquote></details>

Done.

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 2 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/549)* status: 20 of 22 files reviewed, all discussions resolved

**Comment by rodrigo-pino** [comment]
Solved in #1240

**Pull request closed without merging**
