### PR TITLE
test: use the executable_invoke_tx_creator in mempool test

### PR DESCRIPTION
**Pull request by ArniStarkware**
Replacing the PR: 789# because:
1. It diverged a bit after a merge conflict.
2. @MohammadNassar1 is going on vacation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/922)

### CODE REVIEW

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/922)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/922#-O7OQnVO0yJKtkpq-Ae4:-O7OQnVO0yJKtkpq-Ae5:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/a622d5b35c0108fe1ae53b1ccdbc599003df0080/crates/mempool/src/mempool_test.rs#L153)):*
> ```XML
> 
> /// Creates an executable transaction with the given field subset (the rest receive default values).
> macro_rules! tx {
> ```





_Suggestion:_
```XML
invoke_tx
```
___
*[`crates/starknet_api/src/test_utils/invoke.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/922#-O7OQuuV7koaavJVbRKE:-O7OQuuV7koaavJVbRKF:b8rtpv3) ([raw file](https://github.com/starkware-libs/sequencer/blob/a622d5b35c0108fe1ae53b1ccdbc599003df0080/crates/starknet_api/src/test_utils/invoke.rs#L112)):*
> ```XML
> 
> pub fn executable_invoke_tx(invoke_args: InvokeTxArgs) -> ExecutableInvokeTransaction {
>     let tx_hash = invoke_args.tx_hash;
> ```

I see you added tx hash to invoke and deploy_account, what about declare?



_Code quote:_
```XML
invoke_args.tx_hash
```

**Comment by ArniStarkware** [comment]
* **#922** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/922?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/922)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @Yael-Starkware)

___
*[`crates/mempool/src/mempool_test.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/922#-O7OQnVO0yJKtkpq-Ae4:-O7ORokw92UO8tQcl74C:b-al1513) ([raw file](https://github.com/starkware-libs/sequencer/blob/a622d5b35c0108fe1ae53b1ccdbc599003df0080/crates/mempool/src/mempool_test.rs#L153)):*
> ```XML
> 
> /// Creates an executable transaction with the given field subset (the rest receive default values).
> macro_rules! tx {
> ```

I do not want to interrupt the `mempool` tests too much. This macro is only used in this file, and if I understand correctly, the type of the transaction is irrelevant to the test's purpose. 
The word `invoke_` is just a boilerplate in this context. 
___
*[`crates/starknet_api/src/test_utils/invoke.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/922#-O7OQuuV7koaavJVbRKE:-O7ORZGiCANsU8UbjiUd:b-kuf73c) ([raw file](https://github.com/starkware-libs/sequencer/blob/a622d5b35c0108fe1ae53b1ccdbc599003df0080/crates/starknet_api/src/test_utils/invoke.rs#L112)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I see you added tx hash to invoke and deploy_account, what about declare?
</blockquote></details>

Already there :)

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/922)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @elintul and @MohammadNassar1)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/922)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @MohammadNassar1)

**Pull request merged**
