### PR TITLE
chore(blockifier): add keccak_builtin_gas_cost

### PR DESCRIPTION
**Pull request by Yonatan-Starkware**

### CODE REVIEW

**Comment by Yonatan-Starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2327?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2327** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2327?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2327?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2247** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2247?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2188** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2188?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2067** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2067?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2327)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @Yonatan-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_0_13_0.json` line 76 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2327#-OD-n8iA3ouaD2hzgkt9:-OD-n8iA3ouaD2hzgktA:bgxq81b) ([raw file](https://github.com/starkware-libs/sequencer/blob/8537aae9b4058acde20ab64176cd28993a7a2fd7/crates/blockifier/resources/versioned_constants_0_13_0.json#L76)):*
> ```JSON
>         "step_gas_cost": 100,
>         "range_check_gas_cost": 70,
>         "keccak_builtin_gas_cost": 136189,
> ```

It needs to be zero in all old files 



_Suggestion:_
```JSON
"keccak_builtin_gas_cost": 0,
```

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2327)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware and @Yoni-Starkware)

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/resources/versioned_constants_0_13_0.json` line 76 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2327#-OD-n8iA3ouaD2hzgkt9:-OD24fUG82ssRNHbEFPe:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/47f5e10254e7c18e868749ad0e88684ee79baecf/crates/blockifier/resources/versioned_constants_0_13_0.json#L76)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

It needs to be zero in all old files
</blockquote></details>

Done.

**Review by meship-starkware — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2327)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware and @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2327)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Pull request merged**
