### PR TITLE
fix(ci): adjust user UID in the sequencer ci dockerfile

### PR DESCRIPTION
**Pull request by adi-yakovian-starkware**

### CODE REVIEW

**Review by giladchase — APPROVED** [review]
I rebased a failing pr onto this branch and it passed the CI, seems to work then.
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2673#-:-OE9fig4DrG40TI_Q4WD:buwdejm)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @adi-yakovian-starkware)

**Review by giladchase — CHANGES_REQUESTED** [review]
Blocking i favor of https://github.com/starkware-libs/sequencer/pull/2676/files

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2673#-:-OE9khO6EJXXqnDAF8bo:b-adntlf)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @adi-yakovian-starkware)

**Review by giladchase — CHANGES_REQUESTED** [review]
*in favor

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2673#-:-OE9vwVr6TuFxcY1YvoO:b-lquyt4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @adi-yakovian-starkware)

**Comment by adi-yakovian-starkware** [comment]
There was a better solution: https://github.com/starkware-libs/sequencer/pull/2676/files.

**Pull request closed without merging**
