### PR TITLE
chore: make sure that the cairo_native flag works in python

### PR DESCRIPTION
**Pull request by meship-starkware**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2465)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @Yoni-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2465#-ODaHOxI40VlpuignSR2:-ODaHOxI40VlpuignSR3:bhnsx7b) (no related file):*
blocking (this is only a test PR and shouldn't be merged, right?)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2465)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2465#-ODaHOxI40VlpuignSR2:-ODapTp_8RxiWkeW3qOg:b-4na1cj) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

blocking (this is only a test PR and shouldn't be merged, right?)
</blockquote></details>

Yes, I don't know why You and Yoni are reviewers

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2465)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2465#-ODaHOxI40VlpuignSR2:-ODay1LF1OrCC9vSudtj:b-7l96f0) (no related file):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Yes, I don't know why You and Yoni are reviewers
</blockquote></details>

Does it work?
Let's merge it! to make sure native does not break

:lgtm:

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2465)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @Yoni-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2465#-ODaHOxI40VlpuignSR2:-ODb9tFa17bcfxf3qwfY:b-tvwxtb) (no related file):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Does it work?
Let's merge it! to make sure native does not break

:lgtm:
</blockquote></details>

what? why?
we don't (I think) want to add native to all CI, just the feature-combo build...
(change the blockifier ==> change the native blockifier ==> trigger tests with native active)

and if this is to be merged, I have an objection to initializing the submodule in different places (in the main CI);
can the checkout step be part of the bootstrapping action...?
if you are running the bootstrap action you are relying on scripts from the repo, so the checkout should probably coupled with the bootstrap anyway

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2465)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2465#-ODaHOxI40VlpuignSR2:-ODbGpTj7RDZaYxnX_KW:bvh9q3q) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what? why?
we don't (I think) want to add native to all CI, just the feature-combo build...
(change the blockifier ==> change the native blockifier ==> trigger tests with native active)

and if this is to be merged, I have an objection to initializing the submodule in different places (in the main CI);
can the checkout step be part of the bootstrapping action...?
if you are running the bootstrap action you are relying on scripts from the repo, so the checkout should probably coupled with the bootstrap anyway
</blockquote></details>

@meship-starkware worth checking (but keep it mind that we might be able to get rid of the submodule soon)

We will run native E2E very soon, so turning this feature on is a high priority.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2465)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2465#-ODaHOxI40VlpuignSR2:-ODeLt9X8b1CdZfmpYwt:brsg07j) (no related file):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@meship-starkware worth checking (but keep it mind that we might be able to get rid of the submodule soon)

We will run native E2E very soon, so turning this feature on is a high priority.
</blockquote></details>

It does not work. It does not build the artifact because we don't have the Cairo native submodules. I am working on a solution

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2465)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`.github/workflows/upload_artifacts_workflow.yml` line 74 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2465#-ODeN-Gn0bi6sxxepN2b:-ODeN-Go1NmKbacoPMQ7:b-vgulwt) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc300899344f168df94e4c048d4bda5fc433e429/.github/workflows/upload_artifacts_workflow.yml#L74)):*
> ```YAML
>       - uses: ./.github/actions/bootstrap
>       - name: Initialize and update submodules
>         run: git submodule update --init --recursive
> ```

I don't think this is a good solution; I just want to see if it can build the artifact with that. 



_Code quote:_
```YAML
      - name: Initialize and update submodules
        run: git submodule update --init --recursive
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2465)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware and @meship-starkware)

___
*[`scripts/build_native_blockifier.sh` line 23 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2465#-ODf51EYEPF0sDxlaid2:-ODf51EYEPF0sDxlaid3:b-d70w3) ([raw file](https://github.com/starkware-libs/sequencer/blob/f552c5e2b7d7d0d8c22240071cc73b456ac41aec/scripts/build_native_blockifier.sh#L23)):*
> ```Shell
> }
> 
> init_submodule &&
> ```

is this the correct syntax for "run and exit if failed"?



_Code quote:_
```Shell
init_submodule &&
```
___
*[`.github/workflows/main.yml` line 117 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2465#-ODf5Cjn47jdEaivQD31:-ODf5Cjn47jdEaivQD32:boobiip) ([raw file](https://github.com/starkware-libs/sequencer/blob/f552c5e2b7d7d0d8c22240071cc73b456ac41aec/.github/workflows/main.yml#L117)):*
> ```YAML
>           # Fetch the entire history.
>           fetch-depth: 0
>       - uses: ./.github/actions/bootstrap
> ```

should this be part of the bootstrap script? you can init submodules inside it, no?



_Code quote:_
```YAML
        with:
          # required to clone native as a gitsubmodule
          submodules: recursive
          # Fetch the entire history.
          fetch-depth: 0
      - uses: ./.github/actions/bootstrap
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2465)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware and @dorimedini-starkware)

___
*[`scripts/build_native_blockifier.sh` line 23 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2465#-ODf51EYEPF0sDxlaid2:-ODf7W4196P8h_tUxj5f:b-4lx7ao) ([raw file](https://github.com/starkware-libs/sequencer/blob/f552c5e2b7d7d0d8c22240071cc73b456ac41aec/scripts/build_native_blockifier.sh#L23)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this the correct syntax for "run and exit if failed"?
</blockquote></details>

According to Copilot this is the syntax or run and only run the next command upon success.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2465)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`.github/workflows/main.yml` line 117 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2465#-ODf5Cjn47jdEaivQD31:-ODfBR5q8sJmJgxeklAc:bei4324) ([raw file](https://github.com/starkware-libs/sequencer/blob/f552c5e2b7d7d0d8c22240071cc73b456ac41aec/.github/workflows/main.yml#L117)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

should this be part of the bootstrap script? you can init submodules inside it, no?
</blockquote></details>

It seems like the - uses: actions/checkout@v4 should happen before calling the bootstrap script because otherwise, it does not know the script.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2465)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @meship-starkware)

___
*[`.github/workflows/main.yml` line 117 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2465#-ODf5Cjn47jdEaivQD31:-ODfRgluD0nRS-zHVS-V:b-h9376s) ([raw file](https://github.com/starkware-libs/sequencer/blob/f552c5e2b7d7d0d8c22240071cc73b456ac41aec/.github/workflows/main.yml#L117)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

It seems like the - uses: actions/checkout@v4 should happen before calling the bootstrap script because otherwise, it does not know the script.
</blockquote></details>

yes but you can checkout without submodule init, and later explicitly init using a git command, during bootstrapping.
I prefer to share this code, rather than duplicate it

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2465)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @meship-starkware)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2465)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @dorimedini-starkware)

___
*[`.github/workflows/main.yml` line 108 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2465#-ODfUDCu4zowCB_BUZ7r:-ODfmc013fL0eHtFnGze:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/29ecc4c0c07e796aec4ed93737a9c5ef4cf82634/.github/workflows/main.yml#L108)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2465)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware)

**Pull request merged**
