### PR TITLE
feat(storage)!: bump storage version

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/669)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/669)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/669#-O5hHRKG4hqOH01xzWJ7:-O5hHRKG4hqOH01xzWJ8:blxne7m) (no related file):*
1. The state minor version was 1 for some reason, although all the wrappers have zero versions.
2. It looks like the major version was not bumped in 13.2 although we broke the storage
3. I match both the body and state versions to 3, although the body could stay without a change

___

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/669)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/669#-O5lntW611FQKchtdiom:-O5lntW611FQKchtdion:b8arz3j) ([raw file](https://github.com/starkware-libs/sequencer/blob/86b37a7bd6ffcb40d0195341a27e1c8c5575d1b7/crates/papyrus_storage/src/lib.rs#L158)):*
> ```XML
> // For more details on the storage version, see the module documentation.
> /// The current version of the storage state code.
> pub const STORAGE_VERSION_STATE: Version = Version { major: 3, minor: 0 };
> ```

Why `3`?



_Code quote:_
```XML
3
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/669)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/669#-O5lntW611FQKchtdiom:-O5luiWj6A_SfJNDBefE:b-ycfvhk) ([raw file](https://github.com/starkware-libs/sequencer/blob/86b37a7bd6ffcb40d0195341a27e1c8c5575d1b7/crates/papyrus_storage/src/lib.rs#L158)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why `3`?
</blockquote></details>

To have the same versions for both state and body and to have a "fresh start." I can make it 2, but there is no benefit to that.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/669)* status: all files reviewed, 2 unresolved discussions

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/669)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/669)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/669)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/669)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Pull request merged**
