### PR TITLE
feat(mempool): add contains func to suspended tx pool

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/663)

### CODE REVIEW

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/663)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/suspended_transaction_pool.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/663#-O5hVPHS9FLdCJSLysXO:-O5hVPHS9FLdCJSLysXP:b-66u1i3) ([raw file](https://github.com/starkware-libs/sequencer/blob/525a35cef8007aafd00675c56e41c39e04dadb93/crates/mempool/src/suspended_transaction_pool.rs#L19)):*
> ```XML
>             return true;
>         }
>         false
> ```

`contains_key` already returns bool.



_Suggestion:_
```XML
        self._suspended_tx_pool.contains_key(&(address, nonce))
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/663)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/suspended_transaction_pool.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/663#-O5hVYQ_DJIw0ZNjVooO:-O5hVYQ_DJIw0ZNjVooP:b-adyofs) ([raw file](https://github.com/starkware-libs/sequencer/blob/525a35cef8007aafd00675c56e41c39e04dadb93/crates/mempool/src/suspended_transaction_pool.rs#L15)):*
> ```XML
> 
> impl SuspendedTransactionPool {
>     pub fn _contains(&self, address: ContractAddress, nonce: Nonce) -> bool {
> ```

please pass by ref



_Code quote:_
```XML
 address: ContractAddress, nonce: Nonce)
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/663)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/suspended_transaction_pool.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/663#-O5hVYQ_DJIw0ZNjVooO:-O5hg0pEEB46fkKRjyM3:b-av6hh2) ([raw file](https://github.com/starkware-libs/sequencer/blob/525a35cef8007aafd00675c56e41c39e04dadb93/crates/mempool/src/suspended_transaction_pool.rs#L15)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

please pass by ref
</blockquote></details>

There are two options attached. I think the original one is the best because it’s simple, `felt` is okay to copy, and it avoids unnecessary references and dereferencing, making the code cleaner and more readable. don't you think?



_Code snippet (i):_
```XML
    pub fn _contains(&self, key: &(ContractAddress, Nonce)) -> bool {
        self._suspended_tx_pool.contains_key(key)
    }
```



_Code snippet (ii):_
```XML
    pub fn _contains(&self, address: &ContractAddress, nonce: &Nonce) -> bool {
        self._suspended_tx_pool.contains_key(&(*address, *nonce))
    }
```
___
*[`crates/mempool/src/suspended_transaction_pool.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/663#-O5hVPHS9FLdCJSLysXO:-O5hf1wg3Zrgby2-ZTQV:b7u03hh) ([raw file](https://github.com/starkware-libs/sequencer/blob/525a35cef8007aafd00675c56e41c39e04dadb93/crates/mempool/src/suspended_transaction_pool.rs#L19)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

`contains_key` already returns bool.
</blockquote></details>

Correct

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/663#-:-O5hzn2w7P6hLxs38aWY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/663)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/suspended_transaction_pool.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/663#-O6py8m1-9FvkB2DA6N6:-O6py8m1-9FvkB2DA6N7:b-l13dhj) ([raw file](https://github.com/starkware-libs/sequencer/blob/b3de04570b5e7e5add5dac2e4cfea3359f128d24/crates/mempool/src/suspended_transaction_pool.rs#L16)):*
> ```XML
> impl SuspendedTransactionPool {
>     pub fn _contains(&self, address: ContractAddress, nonce: Nonce) -> bool {
>         self._suspended_tx_pool.contains_key(&(address, nonce))
> ```

Why does _suspended_tx_pool have a `_` prefix?



_Code quote:_
```XML
        self._suspended_tx_pool.contains_key(&(address, nonce))
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/663)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/suspended_transaction_pool.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/663#-O6py8m1-9FvkB2DA6N6:-O6q2qiC-zPsmhisC8HF:bgv3u16) ([raw file](https://github.com/starkware-libs/sequencer/blob/b3de04570b5e7e5add5dac2e4cfea3359f128d24/crates/mempool/src/suspended_transaction_pool.rs#L16)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Why does _suspended_tx_pool have a `_` prefix?
</blockquote></details>

If I remove it, I get dead code error, because it's still not being used outside of this file. will be changed when used in PartitionManager.

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/663)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/suspended_transaction_pool.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/663#-O6py8m1-9FvkB2DA6N6:-O6q3hdr6T3R1LcmBDga:bohdfbq) ([raw file](https://github.com/starkware-libs/sequencer/blob/b3de04570b5e7e5add5dac2e4cfea3359f128d24/crates/mempool/src/suspended_transaction_pool.rs#L16)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

If I remove it, I get dead code error, because it's still not being used outside of this file. will be changed when used in PartitionManager.
</blockquote></details>

`contains` is a `pub` function though :thinking: 
Also what's the invariant on suspended_tx_pool that makes it private?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/663)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/suspended_transaction_pool.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/663#-O6py8m1-9FvkB2DA6N6:-O6uMqmV53go9iKjNxTz:by0stt9) ([raw file](https://github.com/starkware-libs/sequencer/blob/b3de04570b5e7e5add5dac2e4cfea3359f128d24/crates/mempool/src/suspended_transaction_pool.rs#L16)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

`contains` is a `pub` function though :thinking: 
Also what's the invariant on suspended_tx_pool that makes it private?
</blockquote></details>

I rebased this PR after removing `SuspendedTransactionPool` from Mempool (it will be moved to `PartitionManager`), so it's currently unused and triggers a dead code error. Since it's `pub(crate)` but not yet active, I temporarily added the `_` prefix to the struct name, type, and implemented function to avoid the error.

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/663)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/663#-:-O6ygsSq-X2qMfYFmjgu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
