### PR TITLE
test(batcher): block builder transaction failed test

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2171?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2171** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2171?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2171?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2148** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2148?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2053** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2053?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#2126](https://github.com/starkware-libs/sequencer/pull/2126) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2126?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#2162](https://github.com/starkware-libs/sequencer/pull/2162) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2162?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2050** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2050?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2049** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2049?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2042** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2042?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2046** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2046?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1951** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1951?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1996** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1996?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1986** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1986?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1985** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1985?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2171)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/starknet_batcher/src/block_builder_test.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2171#-OC33Gh0-MgpUxL2M5ZK:-OC33Gh0-MgpUxL2M5ZL:b-nrtr3t) ([raw file](https://github.com/starkware-libs/sequencer/blob/1374f3d984180a27ef0e93d50976a41dc787a3d7/crates/starknet_batcher/src/block_builder_test.rs#L207)):*
> ```XML
> }
> 
> fn transaction_failed_test_expectations(
> ```

I can add this test as a case to the previous test, with a bit of refactor.
wdyt?

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2171)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/starknet_batcher/src/block_builder_test.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2171#-OC33Gh0-MgpUxL2M5ZK:-OC33TSn8UQRaRcv4YBl:b-o2j26p) ([raw file](https://github.com/starkware-libs/sequencer/blob/1374f3d984180a27ef0e93d50976a41dc787a3d7/crates/starknet_batcher/src/block_builder_test.rs#L207)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I can add this test as a case to the previous test, with a bit of refactor.
wdyt?
</blockquote></details>

(this comment was supposed to be written over the test function and not here ).

**Review by alonh5 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2171)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/starknet_batcher/src/block_builder_test.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2171#-OC33Gh0-MgpUxL2M5ZK:-OC39jUgCTdA0ngNSUoi:b-zbhl0b) ([raw file](https://github.com/starkware-libs/sequencer/blob/1374f3d984180a27ef0e93d50976a41dc787a3d7/crates/starknet_batcher/src/block_builder_test.rs#L207)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

(this comment was supposed to be written over the test function and not here ).
</blockquote></details>

If it's not to big of a refactor and you think it makes sense, then yeah.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2171)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/starknet_batcher/src/block_builder_test.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2171#-OC33Gh0-MgpUxL2M5ZK:-OC7HvPg3UKjd-t95UkY:b2nhysk) ([raw file](https://github.com/starkware-libs/sequencer/blob/1374f3d984180a27ef0e93d50976a41dc787a3d7/crates/starknet_batcher/src/block_builder_test.rs#L207)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

If it's not to big of a refactor and you think it makes sense, then yeah.
</blockquote></details>

ack

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2171#-:-OC8sQAq4o5YFV7A3hnr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Comment by Yael-Starkware** [comment]
### Merge activity

* **Nov 20, 9:59 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2171).

**Pull request merged**
