### PR TITLE
chore: remove class_info referance from test_stateful_tx_validator

### PR DESCRIPTION
**Pull request by ArniStarkware**
Note - the class_info never plays a role. The only tested cases are invoke txs.

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/611)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#611** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/611?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/611)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/611#-O5SInY1B75x3fQE-NcF:-O5SInY24J5h_J3k4VRw:b-g6yk40) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae40fdc4fbd592b23f4456a12897ff5ff0d4cbc3/crates/gateway/src/stateful_transaction_validator_test.rs#L92)):*
> ```XML
>     mock_validator.expect_get_nonce().returning(|_| Ok(Nonce(Felt::ZERO)));
> 
>     let result = stateful_validator.run_validate(&rpc_tx, None, mock_validator);
> ```

consider adding a comment explaining why we pass `none` here
up to you

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/611#-:-O5SlI7dD7ui96IEwIjG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/611)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
