### PR TITLE
refactor(blockifier_reexecution): refactor retry config params

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1906?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1906** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1906?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1905** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1905?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1902** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1902?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1906)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1906#-OBKsJkq84-yVCFAQ6_f:-OBKsJkr-RMUVgUynBHF:bnzpmgg) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd34bafa38ee3885a267cafa5844d02501aaca9b/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L52)):*
> ```XML
> 
> pub const DEFAULT_RETRY_COUNT: usize = 3;
> pub const DEFAULT_RETRY_WAIT_TIME: u64 = 10000;
> ```

10 seconds per retry?
can you please log to the console between retries, and also output the retry length?



_Code quote:_
```XML
10000
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1906)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1906#-OBKsJkq84-yVCFAQ6_f:-OBLALS87Yap_7qC3mly:b9abnwu) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd34bafa38ee3885a267cafa5844d02501aaca9b/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L52)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

10 seconds per retry?
can you please log to the console between retries, and also output the retry length?
</blockquote></details>

There are occasional failures in the HTTPS test when the duration is less than 10 seconds.
Should I always print it or only in the https test?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1906)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1906#-OBKsJkq84-yVCFAQ6_f:-OBLBLbMDJSy7l7Bu5IE:bgki573) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd34bafa38ee3885a267cafa5844d02501aaca9b/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L52)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

There are occasional failures in the HTTPS test when the duration is less than 10 seconds.
Should I always print it or only in the https test?
</blockquote></details>

whenever the `retry` mechanism is used, log every retry attempt with the interval (if it's not HTTP, then no retries will happen anyway)
also, why would you use the retry mechanism *not* in an HTTP test?

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1906)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1906#-OBKsJkq84-yVCFAQ6_f:-OBLDJr5DoH8NLa_XWET:b-x52h9i) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd34bafa38ee3885a267cafa5844d02501aaca9b/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L52)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

whenever the `retry` mechanism is used, log every retry attempt with the interval (if it's not HTTP, then no retries will happen anyway)
also, why would you use the retry mechanism *not* in an HTTP test?
</blockquote></details>

We use it in the rexecution with the RPC-Mode
(HTTP test is the unitests file)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1906)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1906#-OBKsJkq84-yVCFAQ6_f:-OBLFg8Y7h3qnYgzb-vf:b-1tnqp4) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd34bafa38ee3885a267cafa5844d02501aaca9b/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L52)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

We use it in the rexecution with the RPC-Mode
(HTTP test is the unitests file)
</blockquote></details>

log whenever networking is involved

**Pull request closed without merging**
