### PR TITLE
feat(batcher): adding batcher configuration

### PR DESCRIPTION
**Pull request by lev-starkware**
**Stack**:
- #420
- #419
- #407 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/407)

### CODE REVIEW

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/407#-:-O49mQye47JQzrWEIAPB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Review by lev-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/407)* status: 3 of 8 files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by lev-starkware — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/407)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Comment by lev-starkware** [comment]
✓ Commit merged in pull request [#419](https://github.com/starkware-libs/sequencer/pull/419)

**Pull request closed without merging**
