### PR TITLE
chore: expose max bytecode size arg for the compile sierra to casm util

### PR DESCRIPTION
**Pull request by ArniStarkware**
This is an imported version of the PR: https://github.com/starkware-libs/mempool/pull/348.

Note the PRs are stacked in a different order in this REPO.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/283)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/283?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#284** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/284?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#283** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/283?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#250** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/250?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ArniStarkware** [comment]
This PR is very similar to: https://github.com/starkware-libs/mempool/pull/348

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 8 of 15 files at r1, 4 of 6 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/283)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/config.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/283#-O3bcLzw-Eo3pI9njw2b:-O3bcLzxBXPbvVLZriXO:biyzusq) ([raw file](https://github.com/starkware-libs/sequencer/blob/79ec16936f2a50cb7fc1501d049bcd44660a8df5/crates/gateway/src/config.rs#L95)):*
> ```XML
>             max_calldata_length: 4000,
>             max_signature_length: 4000,
>             max_bytecode_size: MAX_BYTECODE_SIZE,
> ```

Do we need to keep this validation in the stateless validator?



_Code quote:_
```XML
max_bytecode_size: MAX_BYTECODE_SIZE,
```
___
*[`crates/starknet_sierra_compile/Cargo.toml` line 15 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/283#-O3ba_bf0cMToHFyOARZ:-O3ba_bf0cMToHFyOAR_:bvbmd9e) ([raw file](https://github.com/starkware-libs/sequencer/blob/79ec16936f2a50cb7fc1501d049bcd44660a8df5/crates/starknet_sierra_compile/Cargo.toml#L15)):*
> ```TOML
> cairo-lang-starknet-classes.workspace = true
> cairo-lang-utils.workspace = true
> papyrus_config = { path = "../papyrus_config", version = "0.4.0-rc.0" }
> ```

Note that local crate deps have moved to the workspace.



_Code quote:_
```TOML
papyrus_config = { path = "../papyrus_config", version = "0.4.0-rc.0" }
```
___
*[`crates/starknet_sierra_compile/src/compile.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/283#-O3bZdFMA_0tG15K56cG:-O3bZdFMA_0tG15K56cH:b-b8qkh) ([raw file](https://github.com/starkware-libs/sequencer/blob/79ec16936f2a50cb7fc1501d049bcd44660a8df5/crates/starknet_sierra_compile/src/compile.rs#L18)):*
> ```XML
> 
> impl SierraToCasmCompiler {
>     pub fn compile_sierra_to_casm(
> ```

Now that the struct name is `SierraToCasmCompiler`...



_Suggestion:_
```XML
compile
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/283)* status: 11 of 16 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/config.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/283#-O3bcLzw-Eo3pI9njw2b:-O3bwBi40BtIEfmzKw6G:b3uk0mt) ([raw file](https://github.com/starkware-libs/sequencer/blob/79ec16936f2a50cb7fc1501d049bcd44660a8df5/crates/gateway/src/config.rs#L95)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Do we need to keep this validation in the stateless validator?
</blockquote></details>

Yes. The stateless validator validates the size of the Sierra program.

The compilation validates the size of the Casm program.
___
*[`crates/starknet_sierra_compile/Cargo.toml` line 15 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/283#-O3ba_bf0cMToHFyOARZ:-O3bwpge7aQUFTNMFHRk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/79ec16936f2a50cb7fc1501d049bcd44660a8df5/crates/starknet_sierra_compile/Cargo.toml#L15)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Note that local crate deps have moved to the workspace.
</blockquote></details>

Done.
___
*[`crates/starknet_sierra_compile/src/compile.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/283#-O3bZdFMA_0tG15K56cG:-O3bwrVp8PMjcOTeez2b:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/79ec16936f2a50cb7fc1501d049bcd44660a8df5/crates/starknet_sierra_compile/src/compile.rs#L18)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Now that the struct name is `SierraToCasmCompiler`...
</blockquote></details>

Done.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/config.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/283#-O3bcLzw-Eo3pI9njw2b:-O3c41Nv9LqK_nimlXTn:b-tnk4pu) ([raw file](https://github.com/starkware-libs/sequencer/blob/79ec16936f2a50cb7fc1501d049bcd44660a8df5/crates/gateway/src/config.rs#L95)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Yes. The stateless validator validates the size of the Sierra program.

The compilation validates the size of the Casm program.
</blockquote></details>

Sorry - I am mistaken. This PR indeed handles the `max_bytecode_size` flag for the compiler which is relevant for the size of the *Sierra*.

I still would like to have this validation in the lightweight - stateless validator, as early as possible.
I will add a comment documenting this.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/283)* status: 15 of 17 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/config.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/283#-O3bcLzw-Eo3pI9njw2b:-O3gIt-w0rbW9Y84yS94:b68nkq) ([raw file](https://github.com/starkware-libs/sequencer/blob/79ec16936f2a50cb7fc1501d049bcd44660a8df5/crates/gateway/src/config.rs#L95)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Sorry - I am mistaken. This PR indeed handles the `max_bytecode_size` flag for the compiler which is relevant for the size of the *Sierra*.

I still would like to have this validation in the lightweight - stateless validator, as early as possible.
I will add a comment documenting this.
</blockquote></details>

Discussed f2f. I think we can remove this from the stateless validator.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/283)* status: 13 of 19 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/config.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/283#-O3bcLzw-Eo3pI9njw2b:-O3gNnjs2xkcDGaf3MZ1:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/79ec16936f2a50cb7fc1501d049bcd44660a8df5/crates/gateway/src/config.rs#L95)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Discussed f2f. I think we can remove this from the stateless validator.
</blockquote></details>

Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/283#-:-O3lA1tiB7qjZAz5w3ZC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware and @yair-starkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Aug 8, 5:47 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/283).

**Pull request merged**
