### PR TITLE
feat(consensus): impl try_sync in sequencer context

### PR DESCRIPTION
**Pull request by asmaastarkware**

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2939)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 350 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2939#-OExZOyg0OTXPgfoKk9I:-OExZOyh5RgNKYnJfmW3:bbveyxw) ([raw file](https://github.com/starkware-libs/sequencer/blob/45515c5df64c9602b0cb1703efc7c7e9809d848b/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L350)):*
> ```XML
>         if let Ok(Some(sync_block)) = sync_block {
>             self.batcher.add_sync_block(sync_block).await.unwrap();
>             return true;
> ```

Ask Dvir if we should update the cende_ambassador



_Code quote:_
```XML
            return true;
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2939)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 350 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2939#-OExZOyg0OTXPgfoKk9I:-OEyiRQzC8HkrSxzrdzs:b-1k3v9s) ([raw file](https://github.com/starkware-libs/sequencer/blob/45515c5df64c9602b0cb1703efc7c7e9809d848b/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L350)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Ask Dvir if we should update the cende_ambassador
</blockquote></details>

no need

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2939)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Review by asmaastarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2939)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
