### PR TITLE
refactor(fee): transaction info creator may fail

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/506)

### CODE REVIEW

**Comment by nimrod-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/506?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#506** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/506?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#505** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/505?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#504** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/504?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#503** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/503?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nimrod-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/506)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/context.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/506#-O4eOcTt38B1gf-nQpV3:-O4eOcTt38B1gf-nQpV4:bal8dew) ([raw file](https://github.com/starkware-libs/sequencer/blob/4668bc1b48fd00165765311c3b70184bd4b3647c/crates/blockifier/src/context.rs#L71)):*
> ```XML
>         TransactionContext {
>             block_context: self.clone(),
>             tx_info: tx_info_creator.create_tx_info().expect("todo"),
> ```

will be handled in an upper branch on the stack



_Code quote:_
```XML
.expect("todo"),
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/506)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 722 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/506#-O4jUk2X-xWjn4JxKuPI:-O4jUk2X-xWjn4JxKuPJ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/57766e2e0f57f44eede64602347c0b4d7b8bb0fd/crates/blockifier/src/transaction/account_transaction.rs#L722)):*
> ```XML
> 
> impl TransactionInfoCreator for AccountTransaction {
>     fn create_tx_info(&self) -> Result<TransactionInfo, TransactionInfoCreationError> {
> ```





_Suggestion:_
```XML
impl TransactionInfoCreator for AccountTransaction {
    // TODO(Nimrod): This function should return `TransactionInfo` without a result.
    fn create_tx_info(&self) -> Result<TransactionInfo, TransactionInfoCreationError> {
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 143 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/506#-O4jUsbD3q2MtzwZpLa5:-O4jUsbD3q2MtzwZpLa6:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/57766e2e0f57f44eede64602347c0b4d7b8bb0fd/crates/blockifier/src/transaction/errors.rs#L143)):*
> ```XML
> 
> #[derive(Debug, Error)]
> pub enum TransactionInfoCreationError {
> ```





_Suggestion:_
```XML
// TODO(Nimrod): Delete this error once `create_tx_info` stops returning a `Result`.
#[derive(Debug, Error)]
pub enum TransactionInfoCreationError {
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/506)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 722 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/506#-O4jUk2X-xWjn4JxKuPI:-O4nefEA-rfvAubB8CIi:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/57766e2e0f57f44eede64602347c0b4d7b8bb0fd/crates/blockifier/src/transaction/account_transaction.rs#L722)):*
> ```XML
> 
> impl TransactionInfoCreator for AccountTransaction {
>     fn create_tx_info(&self) -> Result<TransactionInfo, TransactionInfoCreationError> {
> ```

Done.
___
*[`crates/blockifier/src/transaction/errors.rs` line 143 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/506#-O4jUsbD3q2MtzwZpLa5:-O4nexUQETddiPWFF9zV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/57766e2e0f57f44eede64602347c0b4d7b8bb0fd/crates/blockifier/src/transaction/errors.rs#L143)):*
> ```XML
> 
> #[derive(Debug, Error)]
> pub enum TransactionInfoCreationError {
> ```

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/506#-:-O4nsFt_1d2N9bQygapQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/506)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/506)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/506)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/506)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/506)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
