### PR TITLE
refactor(blockifier): small refactor in secp

### PR DESCRIPTION
**Pull request by Yoni-Starkware**

### CODE REVIEW

**Review by meship-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2129)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`Cargo.lock` line 10533 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2129#-OByW4HvDlK-i64oW6a2:-OByW4HvDlK-i64oW6a3:b-ehovxa) ([raw file](https://github.com/starkware-libs/sequencer/blob/595a55f62acdf0e4c8e47db2f3b08400bf78821c/Cargo.lock#L10533)):*
> ```TOML
>  "async-trait",
>  "futures",
>  "serde",
> ```

Why? It also changed my PR  



_Code quote:_
```TOML
 "serde",
```

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2129)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2129#-:-OByWoSB1lxIBYLXq8xb:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2129)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

___
*[`Cargo.lock` line 10533 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2129#-OByW4HvDlK-i64oW6a2:-OByiIwP8ZwmGR2jeVeP:bc96nki) ([raw file](https://github.com/starkware-libs/sequencer/blob/595a55f62acdf0e4c8e47db2f3b08400bf78821c/Cargo.lock#L10533)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Why? It also changed my PR
</blockquote></details>

IDK but let's נזרום with it

**Pull request merged**
