### PR TITLE
chore(mempool): implement mempool content builder

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/832)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/832)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/832#-O6zshPM3jc_kcPrzgC8:-O6zshPM3jc_kcPrzgC9:bpsoicg) ([raw file](https://github.com/starkware-libs/sequencer/blob/a754468b715bf7afb0090d77e103ba6c40dbcbf3/crates/mempool/src/mempool_test.rs#L76)):*
> ```XML
> impl MempoolContentBuilder {
>     pub fn new() -> Self {
>         Self::default()
> ```

What are the default values? I believe they should be `None`. Are they?



_Code quote:_
```XML
Self::default
```
___
*[`crates/mempool/src/mempool_test.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/832#-O6zsSuXAMXqHxB5CKoO:-O6zsSuXAMXqHxB5CKoP:b-cqapwn) ([raw file](https://github.com/starkware-libs/sequencer/blob/a754468b715bf7afb0090d77e103ba6c40dbcbf3/crates/mempool/src/mempool_test.rs#L79)):*
> ```XML
>     }
> 
>     pub fn with_pool<P>(mut self, pool_txs: P) -> Self
> ```

Why the functions are public?



_Code quote:_
```XML
pub
```
___
*[`crates/mempool/src/mempool_test.rs` line 89 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/832#-O6zszhA5Py29mBqa46h:-O6zszhA5Py29mBqa46i:bz8ntux) ([raw file](https://github.com/starkware-libs/sequencer/blob/a754468b715bf7afb0090d77e103ba6c40dbcbf3/crates/mempool/src/mempool_test.rs#L89)):*
> ```XML
>     pub fn with_queue<Q>(mut self, queue_txs: Q) -> Self
>     where
>         // TODO(Ayelet): Consider using `&Transaction` instead of `TransactionReference`.
> ```

I don't think it's relevant anymore. I think the purpose of this TODO was to send the same object to both the queue and the pool, which no longer applies.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/832)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/832#-O6zshPM3jc_kcPrzgC8:-O6zuZJTAqHAMI5VO_J9:b-o2y8jp) ([raw file](https://github.com/starkware-libs/sequencer/blob/a754468b715bf7afb0090d77e103ba6c40dbcbf3/crates/mempool/src/mempool_test.rs#L76)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

What are the default values? I believe they should be `None`. Are they?
</blockquote></details>

Correct, see [here](https://doc.rust-lang.org/1.81.0/src/core/option.rs.html#2070).
___
*[`crates/mempool/src/mempool_test.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/832#-O6zsSuXAMXqHxB5CKoO:-O6zuc433GUdm9LCsx05:b-19nlmw) ([raw file](https://github.com/starkware-libs/sequencer/blob/a754468b715bf7afb0090d77e103ba6c40dbcbf3/crates/mempool/src/mempool_test.rs#L79)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Why the functions are public?
</blockquote></details>

As they should be used in the `mempool_test` file.
___
*[`crates/mempool/src/mempool_test.rs` line 89 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/832#-O6zszhA5Py29mBqa46h:-O6zum5nDuI_hUoV5WTp:b-htgej3) ([raw file](https://github.com/starkware-libs/sequencer/blob/a754468b715bf7afb0090d77e103ba6c40dbcbf3/crates/mempool/src/mempool_test.rs#L89)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I don't think it's relevant anymore. I think the purpose of this TODO was to send the same object to both the queue and the pool, which no longer applies.
</blockquote></details>

Okay, removing it.

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/832)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/832#-O6zsSuXAMXqHxB5CKoO:-O7--CdIBeCpHmYT8eZZ:b-hhoth0) ([raw file](https://github.com/starkware-libs/sequencer/blob/a754468b715bf7afb0090d77e103ba6c40dbcbf3/crates/mempool/src/mempool_test.rs#L79)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

As they should be used in the `mempool_test` file.
</blockquote></details>

I think you can remove it

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/832)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/832#-O6zsSuXAMXqHxB5CKoO:-O7-1pf3DD3H_8-FpwZE:b-3k3xl6) ([raw file](https://github.com/starkware-libs/sequencer/blob/a754468b715bf7afb0090d77e103ba6c40dbcbf3/crates/mempool/src/mempool_test.rs#L79)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I think you can remove it
</blockquote></details>

Correct, it shouldn't be pub, as it's used in the same file.
Removed.

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/832)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/832#-:-O7-9kL00LZp0a3FBn1a:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/832#-:-O74bjKr9j10gVIAs9Am:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
