### PR TITLE
fix(network): kademlia removes blacklisted peers

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/57)

### CODE REVIEW

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/57)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @ShahakShama)

___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/57#-O2yEGqzDR9BmJwN2KwF:-O2yEGqzDR9BmJwN2KwG:bb3zyj4) ([raw file](https://github.com/starkware-libs/sequencer/blob/0fe0b5197d6babe4863f1042ee91f0d7dc803355/crates/papyrus_network/src/peer_manager/mod.rs#L190)):*
> ```XML
>             peer_id,
>             self.config.blacklist_timeout.as_secs_f64(),
>         );
> ```

this log should go in the blacklisted event

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/57)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/57#-O2yEGqzDR9BmJwN2KwF:-O2ynlcP8bIHLTerQHxJ:b-7zi8tj) ([raw file](https://github.com/starkware-libs/sequencer/blob/0fe0b5197d6babe4863f1042ee91f0d7dc803355/crates/papyrus_network/src/peer_manager/mod.rs#L190)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

this log should go in the blacklisted event
</blockquote></details>

WDYM?

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/57)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @ShahakShama)

___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/57#-O2yEGqzDR9BmJwN2KwF:-O32gy-u4ZT_bQ6z0YKA:bmqdh69) ([raw file](https://github.com/starkware-libs/sequencer/blob/0fe0b5197d6babe4863f1042ee91f0d7dc803355/crates/papyrus_network/src/peer_manager/mod.rs#L190)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

Here we create a backlist event but it should be logged inside the ToOtherBehviourEvent::PeerBlacklisted. This is so we can be sure we log all blacklist events and so we have a single point of reference if we ever want to change the log msg/level etc.

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/57)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`crates/papyrus_network/src/peer_manager/mod.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/57#-O2yEGqzDR9BmJwN2KwF:-O36dBv578v4eNjApQfQ:b-yk75gk) ([raw file](https://github.com/starkware-libs/sequencer/blob/0fe0b5197d6babe4863f1042ee91f0d7dc803355/crates/papyrus_network/src/peer_manager/mod.rs#L190)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Here we create a backlist event but it should be logged inside the ToOtherBehviourEvent::PeerBlacklisted. This is so we can be sure we log all blacklist events and so we have a single point of reference if we ever want to change the log msg/level etc.
</blockquote></details>

I moved it to update_reputation since in the future the timeout will change depending on the reason reported

**Review by AlonLStarkWare — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/57#-:-O36n9Ct7fOyGvBi32da:bnfp4nl)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware)

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/57#-:-O3Bsq_qAWwnwRNNc7Fm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
