### PR TITLE
feat(papyrus_storage): add sierra version to papyrus cache

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2438?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2438** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2438?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2438?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2420** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2420?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2421](https://github.com/starkware-libs/sequencer/pull/2421) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2421?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2313** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2313?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2383](https://github.com/starkware-libs/sequencer/pull/2383) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2383?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2438)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub and @Yoni-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2438#-ODFl99-BFiE5yQlu9IK:-ODFl99-BFiE5yQlu9IL:bb5xc99) (no related file):*
General remark: I have a feeling the size of the sierra version cache should be identical to the size of the sierra *contract* cache -when will you want a version with the class / a class without the version?

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2438)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @TzahiTaub)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2438#-ODFl99-BFiE5yQlu9IK:-ODFm7i21KENRoOfmVz3:b96h3b) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

General remark: I have a feeling the size of the sierra version cache should be identical to the size of the sierra *contract* cache -when will you want a version with the class / a class without the version?
</blockquote></details>

Blocking - this PR is not relevant, we're going to have a cache for the Sierra classes.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2438)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @TzahiTaub)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2438)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2438)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2438#-ODFl99-BFiE5yQlu9IK:-ODLJKk7CBmLi0oxQe1S:be2ihtx) (no related file):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Blocking - this PR is not relevant, we're going to have a cache for the Sierra classes.
</blockquote></details>

We decided to have a cache of VersionedRunnableCompiledClass = ( RunnableCompiledClass , SierraVersion )

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 8 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2438)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub and @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 8 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2438#-:-ODLax7y5fJvHvmKY1xk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2438)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2438)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2438)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2438)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2438)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2438)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Comment by AvivYossef-starkware** [comment]
### Merge activity

* **Dec 15, 2:33 PM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2438).

**Pull request merged**
