### PR TITLE
feat: adding sequencer monitoring to main

### PR DESCRIPTION
**Pull request by lev-starkware**
**Stack**:
- #1442
- #1315 ⬅
- #1298

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1315)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/mempool_node/src/components.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1315#-O95rU3kD-K2z0F113IQ:-O95rU3l8MvcmdkF65w4:b-mzcgrj) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2e123fa400efa5e7a01ae611e50097fd714ffc4/crates/mempool_node/src/components.rs#L21)):*
> ```XML
>     pub http_server: Option<HttpServer>,
>     pub mempool: Option<Mempool>,
>     pub sequencer_monitoring: Option<SequencerMonitoringEndpoint>,
> ```

Please rename the field `monitoring_endpoint` and the type `MonitoringEndpoint` for consistency with other fields/types.



_Code quote:_
```XML
 pub sequencer_monitoring: Option<SequencerMonitoringEndpoint>,
```
___
*[`crates/mempool_node/src/servers.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1315#-O95rjgEADToAOe-LuWY:-O95rjgEADToAOe-LuWZ:bs4q9op) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2e123fa400efa5e7a01ae611e50097fd714ffc4/crates/mempool_node/src/servers.rs#L36)):*
> ```XML
>     pub consensus_manager: Option<Box<ConsensusManagerServer>>,
>     pub http_server: Option<Box<HttpServer>>,
>     pub sequencer_monitoring: Option<Box<SequencerMonitoringServer>>,
> ```

Ditto.



_Code quote:_
```XML
pub sequencer_monitoring: Option<Box<SequencerMonitoringServer>>,
```
___
*[`crates/mempool_node/src/servers.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1315#-O95rse18rDwTp9xGUii:-O95rse18rDwTp9xGUij:b-867xyf) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2e123fa400efa5e7a01ae611e50097fd714ffc4/crates/mempool_node/src/servers.rs#L93)):*
> ```XML
>             components
>                 .sequencer_monitoring
>                 .expect("Sequencer Monitoring Endpoint is not initialized."),
> ```

Please remove.



_Code quote:_
```XML
Sequencer 
```
___
*[`crates/mempool_node/src/servers.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1315#-O95rqNa8QFhC2gAJxGy:-O95rqNa8QFhC2gAJxGz:bs4q9op) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2e123fa400efa5e7a01ae611e50097fd714ffc4/crates/mempool_node/src/servers.rs#L105)):*
> ```XML
>         consensus_manager: consensus_manager_server,
>         http_server,
>         sequencer_monitoring: sequencer_monitoring_server,
> ```

Ditto.



_Code quote:_
```XML
sequencer_monitoring: sequencer_monitoring_server,
```
___
*[`crates/mempool_node/src/servers.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1315#-O95s6-p7n_0iRKmGOPQ:-O95s6-p7n_0iRKmGOPR:b2qyvyj) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2e123fa400efa5e7a01ae611e50097fd714ffc4/crates/mempool_node/src/servers.rs#L163)):*
> ```XML
>     let http_server_handle = tokio::spawn(http_server_future);
>     let mempool_handle = tokio::spawn(mempool_future);
>     let sequencer_monitoring_handle = tokio::spawn(sequencer_monitoring_future);
> ```

Please change to `monitoring_endpoint_handle`



_Code quote:_
```XML
sequencer_monitoring_handle
```
___
*[`crates/mempool_node/src/servers.rs` line 187 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1315#-O95sFb09AnZqFn8GAeo:-O95sFb09AnZqFn8GAep:bs4q9op) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2e123fa400efa5e7a01ae611e50097fd714ffc4/crates/mempool_node/src/servers.rs#L187)):*
> ```XML
>         }
>         res = sequencer_monitoring_handle => {
>             error!("Sequencer Monitoring Server stopped.");
> ```

Ditto.



_Code quote:_
```XML
Sequencer Monitoring Server stopped.
```
___
*[`crates/mempool_node/src/config/config_test.rs` line 188 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1315#-O95sIAh1B69jeYqbh3r:-O95sIAh1B69jeYqbh3s:bs4q9op) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2e123fa400efa5e7a01ae611e50097fd714ffc4/crates/mempool_node/src/config/config_test.rs#L188)):*
> ```XML
>         },
>         mempool: ComponentExecutionConfig { execute: false, ..ComponentExecutionConfig::default() },
>         sequencer_monitoring: ComponentExecutionConfig {
> ```

Ditto.



_Code quote:_
```XML
sequencer_monitoring
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 3 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1315)* status: all files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1315#-:-O9EApiP4YzSE_sOTRpP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1315)

**Review by lev-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1315)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Review by lev-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1315)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Comment by lev-starkware** [comment]
✓ Commit merged in pull request [#1442](https://github.com/starkware-libs/sequencer/pull/1442)

**Pull request closed without merging**
