### PR TITLE
feat: add consensus_manager and com prep

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
commit-id:7de1f17f

---

**Stack**:
- #326 ⬅
- #325
- #324

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/326)* status: all files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/consensus_manager/src/communication.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/326#-O3clbhu3aTeycvFfjRs:-O3clbhvEJoFfpksbkw2:b-14uu0q) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcda206e10a84bc7a67f61c2d2411d2dbc09e03d/crates/consensus_manager/src/communication.rs#L8)):*
> ```XML
>     ConsensusManagerRequestAndResponseSender,
>     ConsensusManagerResponse,
> };
> ```

Remind me why we have 2 crates?
Why is the client defined in `types` and the Server here?



_Code quote:_
```XML
use starknet_consensus_manager_types::communication::{
    ConsensusManagerRequest,
    ConsensusManagerRequestAndResponseSender,
    ConsensusManagerResponse,
};
```
___
*[`crates/consensus_manager/src/communication.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/326#-O3clqJT2Hq9y6gVUC7C:-O3clqJT2Hq9y6gVUC7D:b4xhik8) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcda206e10a84bc7a67f61c2d2411d2dbc09e03d/crates/consensus_manager/src/communication.rs#L26)):*
> ```XML
> ) -> LocalConsensusManagerServer {
>     LocalComponentServer::new(consensus_manager, rx_consensus_manager)
> }
> ```

Are we planning to add more logic? If it's just a one liner why not just have users write the inner part? (same for remote)



_Code quote:_
```XML
pub fn create_local_consensus_manager_server(
    consensus_manager: ConsensusManager,
    rx_consensus_manager: Receiver<ConsensusManagerRequestAndResponseSender>,
) -> LocalConsensusManagerServer {
    LocalComponentServer::new(consensus_manager, rx_consensus_manager)
}
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/326)* status: all files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/consensus_manager/src/communication.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/326#-O3clbhu3aTeycvFfjRs:-O3figob3CIb84sqC5M2:b-kczp3e) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcda206e10a84bc7a67f61c2d2411d2dbc09e03d/crates/consensus_manager/src/communication.rs#L8)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Remind me why we have 2 crates?
Why is the client defined in `types` and the Server here?
</blockquote></details>

`X_types` is for whoever wants to communicate with `X`; it needs to know `X`'s "interface".

The server is specific for `X`, hence it is defined in that crate.
___
*[`crates/consensus_manager/src/communication.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/326#-O3clqJT2Hq9y6gVUC7C:-O3fiwiWBEmGdkCVti9T:b-w5fyoe) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcda206e10a84bc7a67f61c2d2411d2dbc09e03d/crates/consensus_manager/src/communication.rs#L26)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Are we planning to add more logic? If it's just a one liner why not just have users write the inner part? (same for remote)
</blockquote></details>

There's a longer explanation that I wouldn't mind discussing in person, but the TLDR is that indeed we plan on adding more logic, and that for consistency purposes with other components and their servers we prefer to wrap this invocation within a function.
Also please note that the user is the `main` function that creates the server according to the config.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/326)* status: all files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/consensus_manager/src/communication.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/326#-O3clbhu3aTeycvFfjRs:-O3g3X2m1oX0eeYqiUcy:bsob6z1) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcda206e10a84bc7a67f61c2d2411d2dbc09e03d/crates/consensus_manager/src/communication.rs#L8)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

`X_types` is for whoever wants to communicate with `X`; it needs to know `X`'s "interface".

The server is specific for `X`, hence it is defined in that crate.
</blockquote></details>

right, but why don't we just define those this crate. I guess my model is that we have a server as the "primary" piece. Then we expose to other types/clients to connect to it. I don't have such strong feelings but in my mind they are connected. On the other hand small crates I think are better for compiler performance.
___
*[`crates/consensus_manager/src/communication.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/326#-O3clqJT2Hq9y6gVUC7C:-O3g2ktt37H4yu_1DwgZ:b8mn2zg) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcda206e10a84bc7a67f61c2d2411d2dbc09e03d/crates/consensus_manager/src/communication.rs#L26)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

There's a longer explanation that I wouldn't mind discussing in person, but the TLDR is that indeed we plan on adding more logic, and that for consistency purposes with other components and their servers we prefer to wrap this invocation within a function.
Also please note that the user is the `main` function that creates the server according to the config.
</blockquote></details>

Cool. Happy to get the full story in person.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/326)* status: all files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/consensus_manager/src/communication.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/326#-O3clbhu3aTeycvFfjRs:-O3gW8cF3cszSDYEZhfU:b-k6vq7t) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcda206e10a84bc7a67f61c2d2411d2dbc09e03d/crates/consensus_manager/src/communication.rs#L8)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

right, but why don't we just define those this crate. I guess my model is that we have a server as the "primary" piece. Then we expose to other types/clients to connect to it. I don't have such strong feelings but in my mind they are connected. On the other hand small crates I think are better for compiler performance.
</blockquote></details>

Apologies, not following on the suggestion/concern.

**Review by matan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/326)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/consensus_manager/src/communication.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/326#-O3clbhu3aTeycvFfjRs:-O3gx1kC19wPW9_637N8:b8901fi) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcda206e10a84bc7a67f61c2d2411d2dbc09e03d/crates/consensus_manager/src/communication.rs#L8)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Apologies, not following on the suggestion/concern.
</blockquote></details>

I understand that there are different use cases:
1. Server
2. Client

These are tightly coupled things though, so why not just put them into a single crate? Reasons I see not to:
1. Smaller crates = faster (re)compile time
2. You think it just makes more sense to think of these as separate crates

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/326)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/consensus_manager/src/communication.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/326#-O3clbhu3aTeycvFfjRs:-O3h0Biq92P_fWSSuZMB:b-wj2jn9) ([raw file](https://github.com/starkware-libs/sequencer/blob/dcda206e10a84bc7a67f61c2d2411d2dbc09e03d/crates/consensus_manager/src/communication.rs#L8)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I understand that there are different use cases:
1. Server
2. Client

These are tightly coupled things though, so why not just put them into a single crate? Reasons I see not to:
1. Smaller crates = faster (re)compile time
2. You think it just makes more sense to think of these as separate crates
</blockquote></details>

The client needs to be in its own crate, to avoid circular build dependencies: both the component, and whoever tries accessing it, needs to know the client's types. Putting these in the component's crate will cause a circular dependency in case two components try accessing each other.

The server is relevant to any external components, just to the current one. Hence this is why it is in the component crate.

**Pull request merged**
