### PR TITLE
feat(starknet_state_sync): implement state sync get latest block number

### PR DESCRIPTION
**Pull request by noamsp-starkware**

### CODE REVIEW

**Comment by noamsp-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2944?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2944** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2944?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2944?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2942** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2942?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2963** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2963?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2886](https://github.com/starkware-libs/sequencer/pull/2886) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2886?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2979** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2979?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2944)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @noamsp-starkware)

___
*[`crates/starknet_gateway/src/stateful_transaction_validator.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2944#-OFLmPvD61aV8cLggRkb:-OFLmPvD61aV8cLggRkc:b6lym4e) ([raw file](https://github.com/starkware-libs/sequencer/blob/500067210be5ef1c342ef7d17377eb88a5033a98/crates/starknet_gateway/src/stateful_transaction_validator.rs#L138)):*
> ```XML
>     let state_reader = state_reader_factory.get_state_reader_from_latest_block().map_err(|e| {
>         error!("Failed to get state reader from latest block: {}", e);
>         GatewaySpecError::UnexpectedError { data: "Internal server error.".to_owned() }
> ```

Check this with @alonh5

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2944)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/starknet_gateway/src/stateful_transaction_validator.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2944#-OFLmPvD61aV8cLggRkb:-OFM8mKo9xY3XP1V2H_F:b-bjt3ge) ([raw file](https://github.com/starkware-libs/sequencer/blob/500067210be5ef1c342ef7d17377eb88a5033a98/crates/starknet_gateway/src/stateful_transaction_validator.rs#L138)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Check this with @alonh5
</blockquote></details>

This is fine. Didn't review the rest.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2944)* status: all files reviewed, 1 unresolved discussion (waiting on @noamsp-starkware)

___
*[`crates/starknet_gateway/src/sync_state_reader.rs` line 121 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2944#-OFMmMfG3YgdrX4X1P-E:-OFMmMfH0bJZRlyUoMRs:bd8gi4d) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8a8da244a1eaee666dc8bc289acb21b1382dc26/crates/starknet_gateway/src/sync_state_reader.rs#L121)):*
> ```XML
> 
> impl StateReaderFactory for SyncStateReaderFactory {
>     fn get_state_reader_from_latest_block(&self) -> StateResult<Box<dyn MempoolStateReader>> {
> ```

No reason to use StateResult. You can use StateSyncResult instead

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2944)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/starknet_gateway/src/sync_state_reader.rs` line 121 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2944#-OFMmMfG3YgdrX4X1P-E:-OFMrO_m87jn_qgKi5Sw:b-8y08lk) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8a8da244a1eaee666dc8bc289acb21b1382dc26/crates/starknet_gateway/src/sync_state_reader.rs#L121)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No reason to use StateResult. You can use StateSyncResult instead
</blockquote></details>

StateReaderFactory defines this return value.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2944)* status: all files reviewed, 1 unresolved discussion (waiting on @noamsp-starkware)

___
*[`crates/starknet_gateway/src/sync_state_reader.rs` line 121 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2944#-OFMmMfG3YgdrX4X1P-E:-OFMuQ6E7x1VGeqGLynq:b1uetfk) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8a8da244a1eaee666dc8bc289acb21b1382dc26/crates/starknet_gateway/src/sync_state_reader.rs#L121)):*
<details><summary><i>Previously, noamsp-starkware wrote…</i></summary><blockquote>

StateReaderFactory defines this return value.
</blockquote></details>

This just means that I put the comment on the wrong file. Fix it where you define StateReaderFactory

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2944)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @ShahakShama)

___
*[`crates/starknet_gateway/src/sync_state_reader.rs` line 121 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2944#-OFMmMfG3YgdrX4X1P-E:-OFQunm60PZPcEPJ-71d:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a8a8da244a1eaee666dc8bc289acb21b1382dc26/crates/starknet_gateway/src/sync_state_reader.rs#L121)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This just means that I put the comment on the wrong file. Fix it where you define StateReaderFactory
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2944#-:-OFQvfh0BLfuFfQHV_Fv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)

**Pull request merged**
