### PR TITLE
chore(blockifier): split builtin gas costs from base gas costs

### PR DESCRIPTION
**Pull request by Yonatan-Starkware**

### CODE REVIEW

**Comment by Yonatan-Starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2514?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2514** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2514?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2514?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2359** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2359?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2501](https://github.com/starkware-libs/sequencer/pull/2501) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2501?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2327** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2327?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2247** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2247?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2188** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2188?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2067** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2067?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 8 of 10 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2514)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @Yonatan-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 650 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2514#-ODaqJs752b1k_M00nUx:-ODaqJs87urHzkSZ9o5i:babn1xp) ([raw file](https://github.com/starkware-libs/sequencer/blob/a52c253b80042957b0a8f6155d0bca3b17d761c5/crates/blockifier/src/versioned_constants.rs#L650)):*
> ```XML
>     // An estimation of the initial gas for a transaction to run with. This solution is
>     // temporary and this value will be deduced from the transaction's fields.
>     pub default_initial_gas_cost: u64,
> ```

This is what the transaction costs were till now, right? 



_Code quote:_
```XML
 pub default_initial_gas_cost: u64,
```

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2514)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @Yonatan-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 662 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2514#-ODjpRjT9kJJx3OU8aVq:-ODjpRjT9kJJx3OU8aVr:bbrvwr3) ([raw file](https://github.com/starkware-libs/sequencer/blob/a52c253b80042957b0a8f6155d0bca3b17d761c5/crates/blockifier/src/versioned_constants.rs#L662)):*
> ```XML
>     pub range_check_gas_cost: u64,
>     // Priced builtins.
>     pub keccak_builtin_gas_cost: u64,
> ```

Let's remove the builtin from every builtin that has it because it is inconsistent and unnecessary now that they are under the builtin section.  



_Suggestion:_
```XML
pub keccak_gas_cost: u64,
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 753 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2514#-ODjqhNRBf0gSkkzLJ-h:-ODjqhNRBf0gSkkzLJ-i:by67ccq) ([raw file](https://github.com/starkware-libs/sequencer/blob/a52c253b80042957b0a8f6155d0bca3b17d761c5/crates/blockifier/src/versioned_constants.rs#L753)):*
> ```XML
>         "syscall_gas_costs",
>         "builtin_gas_costs",
>     ];
> ```

Are not all the keys in the base now? We should aim to remove this constant, but this is outside of this PR scope. 



_Code quote:_
```XML
    const ADDITIONAL_FIELDS: [&'static str; 31] = [
        "block_hash_contract_address",
        "constructor_entry_point_selector",
        "default_entry_point_selector",
        "entry_point_type_constructor",
        "entry_point_type_external",
        "entry_point_type_l1_handler",
        "error_block_number_out_of_range",
        "error_invalid_input_len",
        "error_invalid_argument",
        "error_entry_point_failed",
        "error_entry_point_not_found",
        "error_out_of_gas",
        "execute_entry_point_selector",
        "l1_gas",
        "l1_gas_index",
        "l1_handler_version",
        "l2_gas",
        "l2_gas_index",
        "l1_data_gas",
        "l1_data_gas_index",
        "nop_entry_point_offset",
        "sierra_array_len_bound",
        "stored_block_hash_buffer",
        "transfer_entry_point_selector",
        "validate_declare_entry_point_selector",
        "validate_deploy_entry_point_selector",
        "validate_entry_point_selector",
        "validate_rounding_consts",
        "validated",
        "syscall_gas_costs",
        "builtin_gas_costs",
    ];
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 765 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2514#-ODjnCq0E9Bs5s9qaGvq:-ODjnCq17ZsfrunAQkM_:b-aeog7q) ([raw file](https://github.com/starkware-libs/sequencer/blob/a52c253b80042957b0a8f6155d0bca3b17d761c5/crates/blockifier/src/versioned_constants.rs#L765)):*
> ```XML
>         let builtins: BuiltinGasCosts = serde_json::from_value(builtins_value)?;
>         let syscalls_value: Value =
>             serde_json::to_value(&raw_json_data.parse_syscalls(&base, &builtins)?)?;
> ```

Here, the way to make sure you have the builtins before you need to calculate the syscall is to call the builtin parse before you call the syscall parse, right? 



_Code quote:_
```XML
        let builtins_value: Value = serde_json::to_value(&raw_json_data.parse_builtin()?)?;
        let builtins: BuiltinGasCosts = serde_json::from_value(builtins_value)?;
        let syscalls_value: Value =
            serde_json::to_value(&raw_json_data.parse_syscalls(&base, &builtins)?)?;
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 961 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2514#-ODjokTg2NFqruJwzwEn:-ODjokTg2NFqruJwzwEo:b-jgu0ug) ([raw file](https://github.com/starkware-libs/sequencer/blob/a52c253b80042957b0a8f6155d0bca3b17d761c5/crates/blockifier/src/versioned_constants.rs#L961)):*
> ```XML
>                         "default_initial_gas_cost" => base.default_initial_gas_cost,
>                         "entry_point_initial_budget" => base.entry_point_initial_budget,
>                         "syscall_base_gas_cost" => base.syscall_base_gas_cost,
> ```

I think it is easier to read this way 



_Suggestion:_
```XML
                    let inner_value = match inner_key.as_str() {
                        "step_gas_cost" => base.step_gas_cost,
                        "memory_hole_gas_cost" => base.memory_hole_gas_cost,
                        "default_initial_gas_cost" => base.default_initial_gas_cost,
                        "entry_point_initial_budget" => base.entry_point_initial_budget,
                        "syscall_base_gas_cost" => base.syscall_base_gas_cost,
                        "range_check_gas_cost" => builtins.range_check_gas_cost,
                        "keccak_builtin_gas_cost" => builtins.keccak_builtin_gas_cost,
                        "pedersen_gas_cost" => builtins.pedersen_gas_cost,
                        "bitwise_builtin_gas_cost" => builtins.bitwise_builtin_gas_cost,
                        "ecop_gas_cost" => builtins.ecop_gas_cost,
                        "poseidon_gas_cost" => builtins.poseidon_gas_cost,
                        "add_mod_gas_cost" => builtins.add_mod_gas_cost,
                        "mul_mod_gas_cost" => builtins.mul_mod_gas_cost,
                        "ecdsa_gas_cost" => builtins.ecdsa_gas_cost,
```

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 662 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2514#-ODjpRjT9kJJx3OU8aVq:-OE8CzJk7I3FYjEx3SyB:byrx1pr) ([raw file](https://github.com/starkware-libs/sequencer/blob/a52c253b80042957b0a8f6155d0bca3b17d761c5/crates/blockifier/src/versioned_constants.rs#L662)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Let's remove the builtin from every builtin that has it because it is inconsistent and unnecessary now that they are under the builtin section.
</blockquote></details>

Agree. 
Specifically for keccak though, it might be confusing, because we also have the price of the syscall (it's name is just "keccak")

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 753 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2514#-ODjqhNRBf0gSkkzLJ-h:-OE8Dn0JB_DU6aVz0IBJ:b-4odq1r) ([raw file](https://github.com/starkware-libs/sequencer/blob/a52c253b80042957b0a8f6155d0bca3b17d761c5/crates/blockifier/src/versioned_constants.rs#L753)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Are not all the keys in the base now? We should aim to remove this constant, but this is outside of this PR scope.
</blockquote></details>

no, all the keys that are in BaseGasCosts are not here.
Actually the number of fields that are now in this list is much larger then the number of those that are not in the list. Might be cleaner to replace this list with a list of the ones that we don't want to skip

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 765 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2514#-ODjnCq0E9Bs5s9qaGvq:-OE8EcZy8ep8zDMxKTo1:b2nign6) ([raw file](https://github.com/starkware-libs/sequencer/blob/a52c253b80042957b0a8f6155d0bca3b17d761c5/crates/blockifier/src/versioned_constants.rs#L765)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Here, the way to make sure you have the builtins before you need to calculate the syscall is to call the builtin parse before you call the syscall parse, right?
</blockquote></details>

yes

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 961 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2514#-ODjokTg2NFqruJwzwEn:-OE8FTV-7teB3ivPvBQM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a52c253b80042957b0a8f6155d0bca3b17d761c5/crates/blockifier/src/versioned_constants.rs#L961)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I think it is easier to read this way
</blockquote></details>

Done.

**Review by meship-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2514)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @Yonatan-Starkware, and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2514)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @noaov1, @Yonatan-Starkware, and @Yoni-Starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2514)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @Yonatan-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_0_13_3.json` line 80 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2514#-OEShUUX0QInHWk0JmuM:-OEShUUX0QInHWk0JmuN:bij0w30) ([raw file](https://github.com/starkware-libs/sequencer/blob/70b0c13b93622ae395494d69a0f30c3d925dc17b/crates/blockifier/resources/versioned_constants_0_13_3.json#L80)):*
> ```JSON
>             "entry_point_initial_budget": 1,
>             "step_gas_cost": 600
>         },
> ```

Now that you removed `transaction_gas_cost`, this can be deleted as well (can be done in a separate PR)



_Code quote:_
```JSON
        "fee_transfer_gas_cost": {
            "entry_point_initial_budget": 1,
            "step_gas_cost": 600
        },
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 719 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2514#-OESgZmW4IMnwqNrwxtq:-OESgZmW4IMnwqNrwxtr:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/70b0c13b93622ae395494d69a0f30c3d925dc17b/crates/blockifier/src/versioned_constants.rs#L719)):*
> ```XML
>     // List of additinal os constants, beside the gas cost and validate rounding constants, that are
>     // not used by the blockifier but included for transparency. These constanst will be ignored
>     // during the creation of the struct containing the gas costs.
> ```





_Suggestion:_
```XML
    // List of os constants to be ignored
    // during the creation of the struct containing the base gas costs.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 752 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2514#-OESg7Za-WBDWY1d9OBq:-OESg7Za-WBDWY1d9OBr:b-fsij12) ([raw file](https://github.com/starkware-libs/sequencer/blob/70b0c13b93622ae395494d69a0f30c3d925dc17b/crates/blockifier/src/versioned_constants.rs#L752)):*
> ```XML
>         "validated",
>         "syscall_gas_costs",
>         "builtin_gas_costs",
> ```

Please keep the list alphabetize. 



_Code quote:_
```XML
        "builtin_gas_costs",
```

**Review by meship-starkware — APPROVED** [review]
> Reviewed 5 of 9 files at r5, 1 of 1 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2514)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @Yonatan-Starkware, and @Yoni-Starkware)

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 719 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2514#-OESgZmW4IMnwqNrwxtq:-OETu8Nj46bOC0a4OFfY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/70b0c13b93622ae395494d69a0f30c3d925dc17b/crates/blockifier/src/versioned_constants.rs#L719)):*
> ```XML
>     // List of additinal os constants, beside the gas cost and validate rounding constants, that are
>     // not used by the blockifier but included for transparency. These constanst will be ignored
>     // during the creation of the struct containing the gas costs.
> ```

Done.

**Review by meship-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2514)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2514)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> Dismissed @noaov1 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2514)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2514)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2514)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware and @Yoni-Starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2514)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware and @Yoni-Starkware)

**Pull request merged**
