### PR TITLE
feat: adding sequencer motoring endpoint

### PR DESCRIPTION
**Pull request by lev-starkware**
**Stack**:
- #1442
- #1315
- #1298 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1298)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/sequencer_monitoring_endpoint/src/communication.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O8qLH_HEP2NUIak648_:-O8qLH_HEP2NUIak648a:b7z04f9) ([raw file](https://github.com/starkware-libs/sequencer/blob/88b679617aa32ec570d14e04fae4d82168223f8b/crates/sequencer_monitoring_endpoint/src/communication.rs#L7)):*
> ```XML
> pub type SequencerMonitoringServer = WrapperServer<SequencerMonitoringEndpoint>;
> 
> pub fn create_http_server(
> ```

Please rename this function.



_Code quote:_
```XML
create_http_server
```
___
*[`crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O8qLRimBFdr74tx3LIx:-O8qLRimBFdr74tx3LIy:b-v3jkig) ([raw file](https://github.com/starkware-libs/sequencer/blob/88b679617aa32ec570d14e04fae4d82168223f8b/crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs#L22)):*
> ```XML
> #[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Validate)]
> pub struct SequencerMonitoringEndpointConfig {
>     pub endpoint_address: String,
> ```

Why not use `SocketAddr` directly?



_Code quote:_
```XML
String,
```
___
*[`crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O8qLZCgEk6fDUILbmw1:-O8qLZCgEk6fDUILbmw2:b-yu8jx7) ([raw file](https://github.com/starkware-libs/sequencer/blob/88b679617aa32ec570d14e04fae4d82168223f8b/crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs#L35)):*
> ```XML
>         BTreeMap::from_iter([ser_param(
>             "server_address",
>             &self.endpoint_address,
> ```

What's the difference between `endpoint_address` and `server_address`?



_Code quote:_
```XML
            "server_address",
            &self.endpoint_address,
```
___
*[`crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O8qL38m7CB33lw__uTq:-O8qL38nBbRu7LS6B4E7:b-wb7ht9) ([raw file](https://github.com/starkware-libs/sequencer/blob/88b679617aa32ec570d14e04fae4d82168223f8b/crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs#L47)):*
> ```XML
>         write!(f, "{self:?}")
>     }
> }
> ```

Can the Display implementation be derived?



_Code quote:_
```XML
impl Display for SequencerMonitoringEndpointConfig {
    #[cfg_attr(coverage_nightly, coverage_attribute)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{self:?}")
    }
}
```
___
*[`crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O8qNqwh3bM5PwFjPRlY:-O8qNqwh3bM5PwFjPRlZ:bdk7ku9) ([raw file](https://github.com/starkware-libs/sequencer/blob/88b679617aa32ec570d14e04fae4d82168223f8b/crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs#L76)):*
> ```XML
> }
> 
> #[allow(clippy::too_many_arguments)]
> ```

Why is this needed?



_Code quote:_
```XML
#[allow(clippy::too_many_arguments)]
```
___
*[`crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O8qNYU43TOpQdIgEiTN:-O8qNYU43TOpQdIgEiTO:b-dhvupk) ([raw file](https://github.com/starkware-libs/sequencer/blob/88b679617aa32ec570d14e04fae4d82168223f8b/crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs#L91)):*
> ```XML
>             get(move || async { version.to_string() }),
>         )
> }
> ```

Please make this code consistent with the format/layout of `crates/http_server/src/http_server.rs`, i.e., defintion of the `app` function, and the various `route` functions.



_Code quote:_
```XML
impl SequencerMonitoringEndpoint {
    pub fn new(config: SequencerMonitoringEndpointConfig, version: &'static str) -> Self {
        SequencerMonitoringEndpoint { config, version }
    }

    #[instrument(
        skip(self),
        fields(
            config = %self.config,
            version = %self.version,
        ),
        level = "debug")]
    pub async fn run(&self) -> std::result::Result<(), hyper::Error> {
        let server_address = SocketAddr::from_str(&self.config.endpoint_address).expect(
            "Configuration value for sequencer monitoring endpoint address should be valid",
        );
        let app = app(self.version);
        debug!("Starting sequencer monitoring endpoint.");
        axum::Server::bind(&server_address).serve(app.into_make_service()).await
    }
}

#[allow(clippy::too_many_arguments)]
fn app(version: &'static str) -> Router {
    Router::new()
        .route(
            format!("/{MONITORING_PREFIX}/alive").as_str(),
            get(move || async { StatusCode::OK.to_string() }),
        )
        .route(
            format!("/{MONITORING_PREFIX}/ready").as_str(),
            get(move || async { StatusCode::OK.to_string() }),
        )
        .route(
            format!("/{MONITORING_PREFIX}/nodeVersion").as_str(),
            get(move || async { version.to_string() }),
        )
}
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1298)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/sequencer_monitoring_endpoint/src/communication.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O8qLH_HEP2NUIak648_:-O8qV2hz0HZ772rKvX9Y:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/88b679617aa32ec570d14e04fae4d82168223f8b/crates/sequencer_monitoring_endpoint/src/communication.rs#L7)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please rename this function.
</blockquote></details>

Done.
___
*[`crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O8qLRimBFdr74tx3LIx:-O8qivkXCmFyXL6QLaTb:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/88b679617aa32ec570d14e04fae4d82168223f8b/crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs#L22)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Why not use `SocketAddr` directly?
</blockquote></details>

Done.
___
*[`crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O8qLZCgEk6fDUILbmw1:-O8qUEjk9v81JkTy8P4e:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/88b679617aa32ec570d14e04fae4d82168223f8b/crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs#L35)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

What's the difference between `endpoint_address` and `server_address`?
</blockquote></details>

Done.
___
*[`crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O8qL38m7CB33lw__uTq:-O8qUJ569JNW8oLTnIFn:b-4iohfg) ([raw file](https://github.com/starkware-libs/sequencer/blob/88b679617aa32ec570d14e04fae4d82168223f8b/crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs#L47)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can the Display implementation be derived?
</blockquote></details>

As I remember only Debug. 
___
*[`crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O8qNqwh3bM5PwFjPRlY:-O8qV09jB2sDb8Tr4rVA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/88b679617aa32ec570d14e04fae4d82168223f8b/crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs#L76)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

Done.
___
*[`crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O8qNYU43TOpQdIgEiTN:-O8qiNkrE6fiaQBX6jES:b-ippbf5) ([raw file](https://github.com/starkware-libs/sequencer/blob/88b679617aa32ec570d14e04fae4d82168223f8b/crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs#L91)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please make this code consistent with the format/layout of `crates/http_server/src/http_server.rs`, i.e., defintion of the `app` function, and the various `route` functions.
</blockquote></details>

Partially done.
Currently, in routes, we have only oneliners, so I prefer it that way. When we have more code we will add functions.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1298)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/sequencer_monitoring_endpoint/src/config.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O95pChP9An-7o_BvL9M:-O95pChP9An-7o_BvL9N:b-bpq0qe) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d7924bff9920db89f70512da541a8bd8ec48581/crates/sequencer_monitoring_endpoint/src/config.rs#L11)):*
> ```XML
> 
> #[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Validate)]
> pub struct SequencerMonitoringEndpointConfig {
> ```

Please drop the `Sequencer` prefix; all other component names do not include it.



_Code quote:_
```XML
Sequencer
```
___
*[`crates/sequencer_monitoring_endpoint/src/config.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O95poYDCPcCHA5AmaIt:-O95poYDCPcCHA5AmaIu:b-cvfqa1) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d7924bff9920db89f70512da541a8bd8ec48581/crates/sequencer_monitoring_endpoint/src/config.rs#L13)):*
> ```XML
> pub struct SequencerMonitoringEndpointConfig {
>     pub ip: IpAddr,
>     pub port: u16,
> ```

There is a `SocketAddr` object that holds ip and port. Do you have a preference to use separate ip and port fields over a single socket?



_Code quote:_
```XML
    pub ip: IpAddr,
    pub port: u16,
```
___
*[`crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O8qLRimBFdr74tx3LIx:-O95qOtPDa4ZIulTxjTJ:b-oa6iuv) ([raw file](https://github.com/starkware-libs/sequencer/blob/88b679617aa32ec570d14e04fae4d82168223f8b/crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs#L22)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Posted a comment at the new section.
___
*[`crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O8qNYU43TOpQdIgEiTN:-O95qgZn6WAaZxbSEHIa:ba5w5kw) ([raw file](https://github.com/starkware-libs/sequencer/blob/88b679617aa32ec570d14e04fae4d82168223f8b/crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs#L91)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

Partially done.
Currently, in routes, we have only oneliners, so I prefer it that way. When we have more code we will add functions.
</blockquote></details>

Could you please elaborate on why do you suggest these two modules should have inconsistent layouts? I don't understand the oneliner comment.

(I'm fine with reformatting the other file by the way).

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1298)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/sequencer_monitoring_endpoint/src/config.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O95pChP9An-7o_BvL9M:-O99GepC60GkD3CuBMXc:bkoyr5g) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d7924bff9920db89f70512da541a8bd8ec48581/crates/sequencer_monitoring_endpoint/src/config.rs#L11)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please drop the `Sequencer` prefix; all other component names do not include it.
</blockquote></details>

Why? You have HttpServerConfig, ConsensusManagerConfig, etc
___
*[`crates/sequencer_monitoring_endpoint/src/config.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O95poYDCPcCHA5AmaIt:-O99GQCtA5rELqKUJaCd:b-3dvw16) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d7924bff9920db89f70512da541a8bd8ec48581/crates/sequencer_monitoring_endpoint/src/config.rs#L13)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

There is a `SocketAddr` object that holds ip and port. Do you have a preference to use separate ip and port fields over a single socket?
</blockquote></details>

This is how it's done in config. Look at http_server or gateway config.
___
*[`crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O8qNYU43TOpQdIgEiTN:-O99INwGBW7RN26yCUJE:b-l3l01m) ([raw file](https://github.com/starkware-libs/sequencer/blob/88b679617aa32ec570d14e04fae4d82168223f8b/crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs#L91)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Could you please elaborate on why do you suggest these two modules should have inconsistent layouts? I don't understand the oneliner comment.

(I'm fine with reformatting the other file by the way).
</blockquote></details>

What is inconsistent?
I put the app function inside of "impl SequencerMonitoringEndpoint".

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1298)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/sequencer_monitoring_endpoint/src/config.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O95pChP9An-7o_BvL9M:-O99K31UBt7-XmB0DPZo:b-1mj6pe) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d7924bff9920db89f70512da541a8bd8ec48581/crates/sequencer_monitoring_endpoint/src/config.rs#L11)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

Why? You have HttpServerConfig, ConsensusManagerConfig, etc
</blockquote></details>

Yes, the component name is `MonitoringEndpoint`, not `SequencerMonitoringEndpoint`. Just like `ConsensusManager` is not `SequencerConsensusManager`.
___
*[`crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O8qNYU43TOpQdIgEiTN:-O99i7_m8kk6CdIFXG5E:b-2rss93) ([raw file](https://github.com/starkware-libs/sequencer/blob/88b679617aa32ec570d14e04fae4d82168223f8b/crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs#L91)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

What is inconsistent?
I put the app function inside of "impl SequencerMonitoringEndpoint".
</blockquote></details>

I prefer that the implementations of the functions would be as in the http server module, but I now understand what you meant by "one liners". Keep as is for now if you prefer, this will most likely change in the future, and I'd hope we remember to keep them consistent.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1298)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-O99isNM3lP38Wy7x0vt:-O99isNM3lP38Wy7x0vu:b-5zfuiz) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d7924bff9920db89f70512da541a8bd8ec48581/crates/sequencer_monitoring_endpoint/src/sequencer_monitoring_endpoint.rs#L47)):*
> ```XML
>         Router::new()
>             .route(
>                 format!("/{MONITORING_PREFIX}/alive").as_str(),
> ```

Please change to a const (that uses `MONITORING_PREFIX`). Apply for other functions as well.



_Code quote:_
```XML
format!("/{MONITORING_PREFIX}/alive").as_str()
```

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1298#-:-O9EAa_wCdoKqUCgVN55:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1298)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1298)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Comment by lev-starkware** [comment]
✓ Commit merged in pull request [#1442](https://github.com/starkware-libs/sequencer/pull/1442)

**Pull request closed without merging**
