### PR TITLE
build(blockifier_reexecution): convert declare starknet api to declare blockifier

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1658?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1658** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1658?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1604** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1604?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1658)* status: all files reviewed, 8 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OARlaf03wUPqf-tLUks:-OARlaf03wUPqf-tLUkt:b354p86) ([raw file](https://github.com/starkware-libs/sequencer/blob/56fff25663358a60d82b1815fddf3231c5f6c324/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L43)):*
> ```XML
> const EXAMPLE_DECLARE_V2_TX_HASH: &str =
>     "0x0409d159fbcab271ffc1693b08d9198f4bbff7e344e1624dadc2d9a67a960226";
> // class_hash = 0x3d311ba322e1f900d669586b191a2a82c50f6cb850563a8e1c01c7bac9be7b0
> ```

what's this?



_Code quote:_
```XML
// class_hash = 0x3d311ba322e1f900d669586b191a2a82c50f6cb850563a8e1c01c7bac9be7b0
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OARloiMDEIZAOGZw3iZ:-OARloiMDEIZAOGZw3i_:bubz0vp) ([raw file](https://github.com/starkware-libs/sequencer/blob/56fff25663358a60d82b1815fddf3231c5f6c324/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L19)):*
> ```XML
> use starknet_api::transaction::{Transaction, TransactionHash};
> use starknet_core::types::ContractClass as StarknetContractClass;
> use starknet_core::types::ContractClass::{Legacy, Sierra};
> ```

please don't import enum variants; use `ContractClass::Sierra` and `ContractClass::Legacy` explicitly (I know it's not from your PR but can you fix it?)



_Suggestion:_
```XML
use starknet_core::types::ContractClass;
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OARmKus2qPUlS54kLC8:-OARmKus2qPUlS54kLC9:b-o3wahj) ([raw file](https://github.com/starkware-libs/sequencer/blob/56fff25663358a60d82b1815fddf3231c5f6c324/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L238)):*
> ```XML
>                 let abi_length = sierra.abi.len();
>                 let sierra_length = sierra.sierra_program.len();
>                 Ok(ClassInfo::new(&sierra_to_contact_class_v1(sierra)?, sierra_length, abi_length)?)
> ```

this logic looks like a good candidate for an `impl From<?> for ClassInfo` block;
can you add it where relevant?
note that there are *multiple* `ClassInfo` and `ContractClass` definitions... make sure you're using the correct ones



_Code quote:_
```XML
                let abi_length = sierra.abi.len();
                let sierra_length = sierra.sierra_program.len();
                Ok(ClassInfo::new(&sierra_to_contact_class_v1(sierra)?, sierra_length, abi_length)?)
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 246 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OARmkSO7n2rS1wmoXBs:-OARmkSO7n2rS1wmoXBt:b-nvoid) ([raw file](https://github.com/starkware-libs/sequencer/blob/56fff25663358a60d82b1815fddf3231c5f6c324/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L246)):*
> ```XML
>                     &legacy_to_contract_class_v0(legacy)?,
>                     DEPRECATED_CONTRACT_SIERRA_SIZE,
>                     abi_length,
> ```

this also looks like a candidate for `From` (see above)



_Code quote:_
```XML
                let abi_length =
                    legacy.abi.clone().expect("legendary contract should have abi").len();
                Ok(ClassInfo::new(
                    &legacy_to_contract_class_v0(legacy)?,
                    DEPRECATED_CONTRACT_SIERRA_SIZE,
                    abi_length,
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OARn3UtAW2DR6X_dpMe:-OARn3UtAW2DR6X_dpMf:b-je2trp) ([raw file](https://github.com/starkware-libs/sequencer/blob/56fff25663358a60d82b1815fddf3231c5f6c324/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L262)):*
> ```XML
>             match tx {
>                 Transaction::Invoke(_) | Transaction::DeployAccount(_) => {
>                     Ok::<BlockifierTransaction, ReexecutionError>(BlockifierTransaction::from_api(tx, tx_hash, None, None, None, false)?)
> ```

does this work? should be a `Result<BlockifierTransaction, ReexecutionError>`



_Suggestion:_
```XML
BlockifierTransaction::from_api(tx, tx_hash, None, None, None, false).map_err(ReexecutionError::from)
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 269 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OARn9b52avRaIfnML42:-OARn9b52avRaIfnML43:b-ngv1l2) ([raw file](https://github.com/starkware-libs/sequencer/blob/56fff25663358a60d82b1815fddf3231c5f6c324/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L269)):*
> ```XML
>                         .map_err(ReexecutionError::from)?;
>                     Ok(BlockifierTransaction::from_api(tx, tx_hash, Some(class_info), None, None, false)?)
>                 }
> ```

why do you need the `::<BlockifierTransaction, ReexecutionError>` turbofish notation in the first match arm but not the second?



_Code quote:_
```XML
                Transaction::Invoke(_) | Transaction::DeployAccount(_) => {
                    Ok::<BlockifierTransaction, ReexecutionError>(BlockifierTransaction::from_api(tx, tx_hash, None, None, None, false)?)
                }
                Transaction::Declare(ref declare_tx) => {
                    let class_info = self
                        .get_class_info(declare_tx.class_hash())
                        .map_err(ReexecutionError::from)?;
                    Ok(BlockifierTransaction::from_api(tx, tx_hash, Some(class_info), None, None, false)?)
                }
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 274 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OARnTol-kSNCHNq9gXj:-OARnTol-kSNCHNq9gXk:b-jnas33) ([raw file](https://github.com/starkware-libs/sequencer/blob/56fff25663358a60d82b1815fddf3231c5f6c324/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L274)):*
> ```XML
>         })
>         // Collect the `Result<Vec<BlockifierTransaction>, ReexecutionError>` to handle the mapping and potential errors
>         .collect::<Result<Vec<_>, _>>() // No `?` needed here
> ```

I think the comments are unecessary here - the `Vec<Result<...>> -> Result<Vec<...>>` conversion is part of the language



_Code quote:_
```XML
        // Collect the `Result<Vec<BlockifierTransaction>, ReexecutionError>` to handle the mapping and potential errors
        .collect::<Result<Vec<_>, _>>() // No `?` needed here
```
___
*[`crates/papyrus_execution/src/lib.rs` line 404 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OARnijAEDSplV_-ddtI:-OARnijAEDSplV_-ddtJ:b-kmf6ap) ([raw file](https://github.com/starkware-libs/sequencer/blob/56fff25663358a60d82b1815fddf3231c5f6c324/crates/papyrus_execution/src/lib.rs#L404)):*
> ```XML
> 
> /// The size of the sierra program for deprecated contracts.
> pub const DEPRECATED_CONTRACT_SIERRA_SIZE: SierraSize = 0;
> ```

if you implement `From` for the legacy class info (see above), you can remove the `pub` (or at least convert to `pub(crate)`), right?



_Code quote:_
```XML
/// The size of the sierra program for deprecated contracts.
pub const DEPRECATED_CONTRACT_SIERRA_SIZE: SierraSize = 0;
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1658)* status: all files reviewed, 5 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1658)* status: all files reviewed, 5 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OARlaf03wUPqf-tLUks:-OASLtGE2Reo0nVGc7HM:b-p2g75e) ([raw file](https://github.com/starkware-libs/sequencer/blob/56fff25663358a60d82b1815fddf3231c5f6c324/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L43)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what's this?
</blockquote></details>

its the class hash of the contract declared. helped me for debuging
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OARloiMDEIZAOGZw3iZ:-OASEJqJ6To-tjnNGOfs:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/56fff25663358a60d82b1815fddf3231c5f6c324/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L19)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please don't import enum variants; use `ContractClass::Sierra` and `ContractClass::Legacy` explicitly (I know it's not from your PR but can you fix it?)
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OARmKus2qPUlS54kLC8:-OASH6Ys2lnT4_-5jJoi:b-ouydud) ([raw file](https://github.com/starkware-libs/sequencer/blob/56fff25663358a60d82b1815fddf3231c5f6c324/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L238)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this logic looks like a good candidate for an `impl From<?> for ClassInfo` block;
can you add it where relevant?
note that there are *multiple* `ClassInfo` and `ContractClass` definitions... make sure you're using the correct ones
</blockquote></details>

the problem is that we can impl the From trait for class info only in the blockifier ( the crate that class info defined ) .
But the code of the function including some code from the blockifier_reexecution crate ```sierra_to_contact_class_v1```
and we dont want that the blockifier will be depend on it
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 246 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OARmkSO7n2rS1wmoXBs:-OASIcMF1tYkkSoZDr0V:b-hbcosa) ([raw file](https://github.com/starkware-libs/sequencer/blob/56fff25663358a60d82b1815fddf3231c5f6c324/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L246)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this also looks like a candidate for `From` (see above)
</blockquote></details>

The same 
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OARn3UtAW2DR6X_dpMe:-OASK07r3dkjiH5KDLPb:b2nhswy) ([raw file](https://github.com/starkware-libs/sequencer/blob/56fff25663358a60d82b1815fddf3231c5f6c324/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L262)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does this work? should be a `Result<BlockifierTransaction, ReexecutionError>`
</blockquote></details>

Yes
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 269 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OARn9b52avRaIfnML42:-OASKFLe7rZ7BGQfmM3I:b-8bm3f5) ([raw file](https://github.com/starkware-libs/sequencer/blob/56fff25663358a60d82b1815fddf3231c5f6c324/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L269)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do you need the `::<BlockifierTransaction, ReexecutionError>` turbofish notation in the first match arm but not the second?
</blockquote></details>

doesnt needed 
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 274 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OARnTol-kSNCHNq9gXj:-OASKQtK5bW7EKzKq2Sz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/56fff25663358a60d82b1815fddf3231c5f6c324/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L274)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think the comments are unecessary here - the `Vec<Result<...>> -> Result<Vec<...>>` conversion is part of the language
</blockquote></details>

Done.
___
*[`crates/papyrus_execution/src/lib.rs` line 404 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OARnijAEDSplV_-ddtI:-OASKSSNDgdYpZcTXSAC:byr4ffv) ([raw file](https://github.com/starkware-libs/sequencer/blob/56fff25663358a60d82b1815fddf3231c5f6c324/crates/papyrus_execution/src/lib.rs#L404)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you implement `From` for the legacy class info (see above), you can remove the `pub` (or at least convert to `pub(crate)`), right?
</blockquote></details>

see above

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1658)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OARmKus2qPUlS54kLC8:-OASNb5B26HQt5BpMqx6:bafilut) ([raw file](https://github.com/starkware-libs/sequencer/blob/56fff25663358a60d82b1815fddf3231c5f6c324/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L238)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

the problem is that we can impl the From trait for class info only in the blockifier ( the crate that class info defined ) .
But the code of the function including some code from the blockifier_reexecution crate ```sierra_to_contact_class_v1```
and we dont want that the blockifier will be depend on it
</blockquote></details>

why is `sierra_to_contact_class_v1` even defined?
I think it's better to implement `TryFrom<FlattenedSierraClass> for ContractClass` (with `type Error = StateError`) in the blockifier

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1658)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OARmKus2qPUlS54kLC8:-OASsaKG3HOMBj4ydn0w:bclap38) ([raw file](https://github.com/starkware-libs/sequencer/blob/56fff25663358a60d82b1815fddf3231c5f6c324/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L238)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is `sierra_to_contact_class_v1` even defined?
I think it's better to implement `TryFrom<FlattenedSierraClass> for ContractClass` (with `type Error = StateError`) in the blockifier
</blockquote></details>

```FlattenedSierraClass``` is defined in starknet-core crate. How can I impl the ```TryFrom``` trait in different crate?
The  ````sierra_to_contact_class_v1``` is the function that compiles the sierra.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-:-OAT5h2IBV6FfJPKgnVD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OARmKus2qPUlS54kLC8:-OAT5N6TAnqHTAHX2TbQ:bfvcn93) ([raw file](https://github.com/starkware-libs/sequencer/blob/56fff25663358a60d82b1815fddf3231c5f6c324/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L238)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

```FlattenedSierraClass``` is defined in starknet-core crate. How can I impl the ```TryFrom``` trait in different crate?
The  ````sierra_to_contact_class_v1``` is the function that compiles the sierra.
</blockquote></details>

ah...
first, since `ContractClass` is defined in the blockifier, you can implement the TryFrom<T> trait even though <T> is defined externally.
however, the compilation is a good point... maybe we don't want to hide this in a TryFrom trait.
ok, unblocking

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 252 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OATGLDZ4O5GSDyfxUTE:-OATGLDZ4O5GSDyfxUTF:b-3tdvgj) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ccc5ba25946a3b616f8d9fe108f715214a713b1/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L252)):*
> ```XML
> 
>     // TODO(Aner): extend/refactor to accomodate all types of transactions.
>     pub(crate) fn from_api_txs_to_blockifier_txs(
> ```

@dorimedini-starkware Why move this function back here? I also need it in other contexts.



_Code quote:_
```XML
 pub(crate) fn from_api_txs_to_blockifier_txs(
```

**Review by aner-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1658)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 233 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OAW2W0xB4Pjrh9qxykm:-OAW2W0xB4Pjrh9qxykn:b73bzyu) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ccc5ba25946a3b616f8d9fe108f715214a713b1/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L233)):*
> ```XML
> 
>     pub fn get_class_info(&self, class_hash: ClassHash) -> ReexecutionResult<ClassInfo> {
>         match self.get_contract_class(&class_hash)? {
> ```

Is it possible to get the required information from the compiled contract class??



_Code quote:_
```XML
match self.get_contract_class(&class_hash)?
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1658)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 233 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OAW2W0xB4Pjrh9qxykm:-OAWUmJCARmjUhlMzpwQ:b-ytnl7t) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ccc5ba25946a3b616f8d9fe108f715214a713b1/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L233)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Is it possible to get the required information from the compiled contract class??
</blockquote></details>

I haven't found a way 
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 252 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OATGLDZ4O5GSDyfxUTE:-OAWV8cB7gI8ZLHG_zNi:bo00yoq) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ccc5ba25946a3b616f8d9fe108f715214a713b1/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L252)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

@dorimedini-starkware Why move this function back here? I also need it in other contexts.
</blockquote></details>

I moved it because the declare transaction requires more information, specifically the class info, which is provided by an RPC call. Another option is to change the function signature to include `option<ClassInfo>`. This way, the function won't need to make an RPC call and can return to utils.rs instead.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1658)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 252 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OATGLDZ4O5GSDyfxUTE:-OAWfA7k5uiS1hXZwqqI:bsgxp61) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ccc5ba25946a3b616f8d9fe108f715214a713b1/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L252)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

I moved it because the declare transaction requires more information, specifically the class info, which is provided by an RPC call. Another option is to change the function signature to include `option<ClassInfo>`. This way, the function won't need to make an RPC call and can return to utils.rs instead.
</blockquote></details>

@aner-starkware where else do you need it?
if you'll need to handle tx lists that possibly contain declares, the contract class needs to be fetched somehow anyway; you will require added context.
maybe useful to have a separate "contract-class-fetching" trait/type... not sure what is the good solution here

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1658)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 252 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OATGLDZ4O5GSDyfxUTE:-OAXRNu4BOvF7sOji2Fz:b-scvpvq) ([raw file](https://github.com/starkware-libs/sequencer/blob/50739a6433cc4af40c810e7f4c9ff2702d7ec728/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L252)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@aner-starkware where else do you need it?
if you'll need to handle tx lists that possibly contain declares, the contract class needs to be fetched somehow anyway; you will require added context.
maybe useful to have a separate "contract-class-fetching" trait/type... not sure what is the good solution here
</blockquote></details>

its now in the trait as discussed

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1658)* status: all files reviewed, 5 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`Cargo.lock` line 1496 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OAXUteuB25-C2nmNJhO:-OAXUteuB25-C2nmNJhP:b-rii7n2) ([raw file](https://github.com/starkware-libs/sequencer/blob/55b1ed1d6c832d03a9497ffdfe24ec623dbcf05d/Cargo.lock#L1496)):*
> ```TOML
>  "cairo-lang-sierra",
>  "cairo-lang-starknet-classes",
>  "cairo-lang-utils",
> ```

I merged this already, please fetch and restack



_Code quote:_
```TOML
 "cairo-lang-utils",
```
___
*[`crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs` line 38 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OAXV9538sV683t68OfM:-OAXV9538sV683t68OfN:b-iwibo3) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9b484eedfe2fa8e8af79a604cf744edd4825d7c/crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs#L38)):*
> ```XML
>                     .map_err(ReexecutionError::from)
>                 }
>                 _ => unimplemented!("unimplemented transaction type: {:?}", tx),
> ```

why is this needed? you are matching all three types
if there is also an L1 handler or something, please match it explicitly



_Code quote:_
```XML
_ => unimplemented!("unimplemented transaction type: {:?}", tx),
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 25 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OAXVNKP0IMV86_utTWg:-OAXVNKP0IMV86_utTWh:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9b484eedfe2fa8e8af79a604cf744edd4825d7c/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L25)):*
> ```XML
> use starknet_types_core::felt::Felt;
> 
> use super::reexecution_state_reader::ReexecutionStateReader;
> ```





_Suggestion:_
```XML
 crate::state_reader::reexecution_state_rea
```

**Review by aner-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1658)* status: all files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 236 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OAXbuytCBM8avDRN4Db:-OAXbuytCBM8avDRN4Dc:b-gocbed) ([raw file](https://github.com/starkware-libs/sequencer/blob/e9b484eedfe2fa8e8af79a604cf744edd4825d7c/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L236)):*
> ```XML
> impl ReexecutionStateReader for TestStateReader {
>     fn get_class_info(&self, class_hash: ClassHash) -> ReexecutionResult<ClassInfo> {
>         match self.get_contract_class(&class_hash)? {
> ```

Is this the only place you use an RPC call? If so, this function should be in the new trait, and the rest of `get_class_info` is common (i.e., should be implemented inside the trait).



_Code quote:_
```XML
self.get_contract_class(&class_hash)
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1658)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs` line 62 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OAXyXm54OiNnNEpu3LN:-OAXyXm54OiNnNEpu3LO:b-5m4po7) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b4dc892e0cee9c6c674d418725de67252f81779/crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs#L62)):*
> ```XML
>                 }
>                 Transaction::L1Handler(_) => todo!("Implement L1Handler transaction converter"),
>                 Transaction::Deploy(_) => todo!("Implement Deploy transaction converter"),
> ```

the `Deploy` transaction type is very old; we won't support reexecution for this



_Suggestion:_
```XML
panic!("Reexecution not supported for Deploy transactions."),
```
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 13 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OAXyNSE2uhspT5anhlL:-OAXyNSE2uhspT5anhlM:bok36zs) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b4dc892e0cee9c6c674d418725de67252f81779/crates/blockifier_reexecution/src/state_reader/utils.rs#L13)):*
> ```XML
> use starknet_types_core::felt::Felt;
> 
> use super::errors::ReexecutionError;
> ```

no `super` outside of tests



_Code quote:_
```XML
super
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1658)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs` line 62 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OAXyXm54OiNnNEpu3LN:-OAY8h83CJf8sm0RaZPW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/63e0d12f4440a5d03caf5f5b7dbb710a4f3fcba3/crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs#L62)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the `Deploy` transaction type is very old; we won't support reexecution for this
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 13 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-OAXyNSE2uhspT5anhlL:-OAXzftt9-hN3J45hsdN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/63e0d12f4440a5d03caf5f5b7dbb710a4f3fcba3/crates/blockifier_reexecution/src/state_reader/utils.rs#L13)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no `super` outside of tests
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1658#-:-OAYAMwy04H3WURHJ52f:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)

**Review by aner-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1658)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
