### PR TITLE
chore: add communication config struct

### PR DESCRIPTION
**Pull request by nadin-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1120)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1120)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1120#-O87FVT5AwQtNm67-Qsi:-O87FVT5AwQtNm67-Qsj:br2m7wr) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c74805d86836c7b040a145ff94c32ab8f845d8b/crates/mempool_infra/src/component_client/remote_component_client.rs#L79)):*
> ```XML
>     uri: Uri,
>     client: Client<hyper::client::HttpConnector>,
>     communication_config: RemoteComponentCommunicationConfig,
> ```

Please rename to `config`: We use this convention throughout the entire code base such that there are no other configs that need to be distinguished with. If a struct needs "multiple" configs then they are bundled together in as a single config struct.



_Code quote:_
```XML
communication_
```
___
*[`crates/mempool_infra/src/tests/remote_component_client_server_test.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1120#-O87Fwoc3dfbLljUfQzd:-O87Fwoc3dfbLljUfQze:b-at1t1o) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c74805d86836c7b040a145ff94c32ab8f845d8b/crates/mempool_infra/src/tests/remote_component_client_server_test.rs#L144)):*
> ```XML
> 
>     let communication_config = RemoteComponentCommunicationConfig::new(socket, MAX_RETRIES);
> ```

Please remove the newline.
___
*[`crates/mempool_infra/src/tests/remote_component_client_server_test.rs` line 200 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1120#-O87G-sWDIwjhfJrzln_:-O87G-sWDIwjhfJrzlna:b-at1t1o) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c74805d86836c7b040a145ff94c32ab8f845d8b/crates/mempool_infra/src/tests/remote_component_client_server_test.rs#L200)):*
> ```XML
> 
>     setup_for_tests(setup_value, a_socket, b_socket).await;
> ```

Please remove the newline.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1120)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/mempool_infra/src/component_definitions.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1120#-O87GOPq0uhzBYhXomZB:-O87GOPq0uhzBYhXomZC:b8dq6sy) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c74805d86836c7b040a145ff94c32ab8f845d8b/crates/mempool_infra/src/component_definitions.rs#L134)):*
> ```XML
>         Self { ip: socket.ip(), port: socket.port(), retries }
>     }
> }
> ```

The convention is to have all config fields as `pub` and not to define `fn new`. This enables changing a single field value compared to the default one.



_Code quote:_
```XML
impl RemoteComponentCommunicationConfig {
    pub fn new(socket: SocketAddr, retries: usize) -> Self {
        Self { ip: socket.ip(), port: socket.port(), retries }
    }
}
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1120)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/mempool_infra/src/component_definitions.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1120#-O87GrbB2qnoz-tKc_mN:-O87GrbC6Rruc2aA1dHa:bxuxylr) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c74805d86836c7b040a145ff94c32ab8f845d8b/crates/mempool_infra/src/component_definitions.rs#L95)):*
> ```XML
> pub struct RemoteComponentCommunicationConfig {
>     pub ip: IpAddr,
>     pub port: u16,
> ```

Non-blocking: Consider changing these to be a single `socket` field.



_Code quote:_
```XML
    pub ip: IpAddr,
    pub port: u16,
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1120)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_definitions.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1120#-O87GrbB2qnoz-tKc_mN:-O8QI2lLBjvHWG9H9cyH:bmfth72) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c74805d86836c7b040a145ff94c32ab8f845d8b/crates/mempool_infra/src/component_definitions.rs#L95)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Non-blocking: Consider changing these to be a single `socket` field.
</blockquote></details>

Thought you wouldn't like it in the same pr, Done :)
___
*[`crates/mempool_infra/src/component_definitions.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1120#-O87GOPq0uhzBYhXomZB:-O8QIvvu1dq0biT7xa-o:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c74805d86836c7b040a145ff94c32ab8f845d8b/crates/mempool_infra/src/component_definitions.rs#L134)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

The convention is to have all config fields as `pub` and not to define `fn new`. This enables changing a single field value compared to the default one.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1120#-O87FVT5AwQtNm67-Qsi:-O8QJT1UCJ8gGgsVmsNH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c74805d86836c7b040a145ff94c32ab8f845d8b/crates/mempool_infra/src/component_client/remote_component_client.rs#L79)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please rename to `config`: We use this convention throughout the entire code base such that there are no other configs that need to be distinguished with. If a struct needs "multiple" configs then they are bundled together in as a single config struct.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/tests/remote_component_client_server_test.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1120#-O87Fwoc3dfbLljUfQzd:-O8QJxRv0ffKvH9bddEn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c74805d86836c7b040a145ff94c32ab8f845d8b/crates/mempool_infra/src/tests/remote_component_client_server_test.rs#L144)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please remove the newline.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/tests/remote_component_client_server_test.rs` line 200 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1120#-O87G-sWDIwjhfJrzln_:-O8QKnq8CfmothUA9MYt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c74805d86836c7b040a145ff94c32ab8f845d8b/crates/mempool_infra/src/tests/remote_component_client_server_test.rs#L200)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please remove the newline.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1120)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/mempool_infra/src/component_definitions.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1120#-O87GrbB2qnoz-tKc_mN:-O8VVFgR9JweVaT0pTaS:b-sexynx) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c74805d86836c7b040a145ff94c32ab8f845d8b/crates/mempool_infra/src/component_definitions.rs#L95)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Thought you wouldn't like it in the same pr, Done :)
</blockquote></details>

Theoretically, yes, practically, this is fine :-)
___
*[`crates/mempool_infra/src/component_definitions.rs` line 112 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1120#-O8VV9TxBO7BOxC1juuZ:-O8VV9TxBO7BOxC1juu_:bo79p4w) ([raw file](https://github.com/starkware-libs/sequencer/blob/e64ee120e8b5643217bca0ea03f1ca0e3c415d53/crates/mempool_infra/src/component_definitions.rs#L112)):*
> ```XML
>                 "The remote component server port.",
>                 ParamPrivacyInput::Public,
>             ),
> ```

Please change to a single `socket` field (assuming it has a `to_string()` method, if not , leave as is).



_Code quote:_
```XML
            ser_param(
                "ip",
                &self.socket.ip().to_string(),
                "The remote component server ip.",
                ParamPrivacyInput::Public,
            ),
            ser_param(
                "port",
                &self.socket.port(),
                "The remote component server port.",
                ParamPrivacyInput::Public,
            ),
```
___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1120#-O8VV_iiBd0h83DDLOC9:-O8VV_iiBd0h83DDLOCA:b-cevxeb) ([raw file](https://github.com/starkware-libs/sequencer/blob/e64ee120e8b5643217bca0ea03f1ca0e3c415d53/crates/mempool_infra/src/component_client/remote_component_client.rs#L27)):*
> ```XML
> /// - `uri`: URI address of the server.
> /// - `client`: The inner HTTP client that initiates the connection to the server and manages it.
> /// - `config`: Configuration for IP, port, and retry attempts on failure.
> ```

Please change to `Client configuration`, i.e., better not list all the *current* config parameters, as these might change in the future, leading to a potential inaccurate doc.



_Code quote:_
```XML
Configuration for IP, port, and retry attempts on failure.
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1120)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_definitions.rs` line 112 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1120#-O8VV9TxBO7BOxC1juuZ:-O8VpgcJ3vefbn_Ua5px:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e64ee120e8b5643217bca0ea03f1ca0e3c415d53/crates/mempool_infra/src/component_definitions.rs#L112)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to a single `socket` field (assuming it has a `to_string()` method, if not , leave as is).
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client/remote_component_client.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1120#-O8VV_iiBd0h83DDLOC9:-O8Vpw360ynC0rD9V1R8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e64ee120e8b5643217bca0ea03f1ca0e3c415d53/crates/mempool_infra/src/component_client/remote_component_client.rs#L27)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to `Client configuration`, i.e., better not list all the *current* config parameters, as these might change in the future, leading to a potential inaccurate doc.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1120#-:-O8Vxy5SDvRs8SFa_6zm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Pull request merged**
