### PR TITLE
fix(consensus): initiate block building in spawned task

### PR DESCRIPTION
**Pull request by matan-starkware**
This results in less blocking code.
Also moved this code to another function since both large and complex.

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2891?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2891** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2891?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2891?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2876** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2876?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2873** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2873?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by asmaastarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2891)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 490 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2891#-OExZ2rb8eOLFMdaqljE:-OExZ2rb8eOLFMdaqljF:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd3da3e7152284d7279f0d3c876eda4140f49c14/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L490)):*
> ```XML
>     loop {
>         // We currently want one part of the node failing to cause all components to fail. If this
>         // changes, we can simply eeturn None and consider this as a failed proposal which consensus
> ```





_Suggestion:_
```XML
// changes, we can simply return None and consider this as a failed proposal which consensus
```

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2891)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 490 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2891#-OExZ2rb8eOLFMdaqljE:-OExZym19pENQwSnjrPb:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fd3da3e7152284d7279f0d3c876eda4140f49c14/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L490)):*
> ```XML
>     loop {
>         // We currently want one part of the node failing to cause all components to fail. If this
>         // changes, we can simply eeturn None and consider this as a failed proposal which consensus
> ```

Done.

**Review by asmaastarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2891)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Comment by matan-starkware** [comment]
### Merge activity

* **Dec 25, 6:50 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2891).

**Pull request merged**
