### PR TITLE
chore(blockifier): fetch compiler repo version

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/181)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/181?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#182** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/182?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#181** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/181?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#180** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/180?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#179** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/179?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/181)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @dorimedini-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/181#-O3DI6e5DHedwlaCNZP_:-O3DI6e5DHedwlaCNZPa:b84wjbd) ([raw file](https://github.com/starkware-libs/sequencer/blob/67192ddbde00d9c04d70a584b8c1f3d1102319b4/crates/blockifier/src/test_utils/cairo_compile.rs#L47)):*
> ```XML
> #[cached]
> /// Returns the version of the Cairo1 compiler* defined in the root Cargo.toml.
> pub fn cairo1_compiler_version() -> String {
> ```

Add a bash script to read the version from the toml for the CI, and add an assert that the bash output equals the value returned here.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/181)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @meship-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/181#-O3DI6e5DHedwlaCNZP_:-O3Daph_6UMnVqEB6tKl:b8i5z5i) ([raw file](https://github.com/starkware-libs/sequencer/blob/67192ddbde00d9c04d70a584b8c1f3d1102319b4/crates/blockifier/src/test_utils/cairo_compile.rs#L47)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Add a bash script to read the version from the toml for the CI, and add an assert that the bash output equals the value returned here.
</blockquote></details>

no need - can leave the version checkout phase part of the rust runtime, no need for CI to be aware of the tag. Updating upstream

**Review by aner-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/181)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @meship-starkware, @noaov1, and @TzahiTaub)

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/181)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 20 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/181#-O3ygIsD2i8jJzJtG-7e:-O3ygIsD2i8jJzJtG-7f:b-cid3re) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c186a0d318b5c09bf4d6611b2bf4ee1d37e99c2/crates/blockifier/src/test_utils/cairo_compile.rs#L20)):*
> ```XML
> /// """
> /// where `VERSION` can be a simple "x.y.z" version string or an object with a "version" field.
> #[derive(Debug, Serialize, Deserialize)]
> ```

I think



_Suggestion:_
```XML
/// where `VERSION` can be a simple "x.y.z" version string or an object with a "version" field.

#[derive(Debug, Serialize, Deserialize)]
```
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 46 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/181#-O3yfngx6H4GZyHS_Wxk:-O3yfngx6H4GZyHS_Wxl:b3971h3) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c186a0d318b5c09bf4d6611b2bf4ee1d37e99c2/crates/blockifier/src/test_utils/cairo_compile.rs#L46)):*
> ```XML
> 
> #[cached]
> /// Returns the version of the Cairo1 compiler* defined in the root Cargo.toml.
> ```

why the `*`? If it's a reference to the head of the file, it isn't clear (replace with `Cairo1 compiler "defined" (see doc at the head of the file) in the root...` or something).



_Code quote:_
```XML
compiler* defined 
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/181)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @meship-starkware, @noaov1, and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 20 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/181#-O3ygIsD2i8jJzJtG-7e:-O4-Mo0EAzWIhuTEIhOC:b-qtmwep) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c186a0d318b5c09bf4d6611b2bf4ee1d37e99c2/crates/blockifier/src/test_utils/cairo_compile.rs#L20)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I think
</blockquote></details>

this is not a docstring for the whole file, just for the struct(s) parsing the toml
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 46 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/181#-O3yfngx6H4GZyHS_Wxk:-O4-N8Q28ynYDGVE6oP_:bvyb82y) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c186a0d318b5c09bf4d6611b2bf4ee1d37e99c2/crates/blockifier/src/test_utils/cairo_compile.rs#L46)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

why the `*`? If it's a reference to the head of the file, it isn't clear (replace with `Cairo1 compiler "defined" (see doc at the head of the file) in the root...` or something).
</blockquote></details>

better?

**Review by TzahiTaub — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/181)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 20 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/181#-O3ygIsD2i8jJzJtG-7e:-O4-i-HN9gJ39rNV8Djr:b-4m83dv) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c186a0d318b5c09bf4d6611b2bf4ee1d37e99c2/crates/blockifier/src/test_utils/cairo_compile.rs#L20)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is not a docstring for the whole file, just for the struct(s) parsing the toml
</blockquote></details>

Just makes it look as docs for the first struct IMO ATM
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 46 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/181#-O3yfngx6H4GZyHS_Wxk:-O4-hxUzDJzr5ghT4xt2:bb77uch) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c186a0d318b5c09bf4d6611b2bf4ee1d37e99c2/crates/blockifier/src/test_utils/cairo_compile.rs#L46)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

better?
</blockquote></details>

Yep

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/181)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 20 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/181#-O3ygIsD2i8jJzJtG-7e:-O4-jxQi6ZDj29bCGYdI:b-c5etkt) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c186a0d318b5c09bf4d6611b2bf4ee1d37e99c2/crates/blockifier/src/test_utils/cairo_compile.rs#L20)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Just makes it look as docs for the first struct IMO ATM
</blockquote></details>

future PRs will add more to this module, this shouldn't be a module docstring.
want me to split the cairo-version-parsing stuff to a separate module and have this as a module-docstirng?

**Review by TzahiTaub — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/181)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 20 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/181#-O3ygIsD2i8jJzJtG-7e:-O4-kJ4J-Uykr2uAbAp_:bns9obi) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c186a0d318b5c09bf4d6611b2bf4ee1d37e99c2/crates/blockifier/src/test_utils/cairo_compile.rs#L20)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

future PRs will add more to this module, this shouldn't be a module docstring.
want me to split the cairo-version-parsing stuff to a separate module and have this as a module-docstirng?
</blockquote></details>

No need.

**Review by TzahiTaub — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/181)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware, @meship-starkware, and @noaov1)

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Aug 11, 11:28 AM EDT**: @dorimedini-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/181).

**Pull request merged**
