### PR TITLE
feat(blockifier): add get_class_hash_at test func

### PR DESCRIPTION
**Pull request by Yoni-Starkware**

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1899)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 132 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1899#-OBKGxTu5rSnKOVKo-tS:-OBKGxTu5rSnKOVKo-tT:b-eoccab) ([raw file](https://github.com/starkware-libs/sequencer/blob/fc8e7d7fe4fda6536126a6c9bc4dc09a59e25608/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L132)):*
> ```Cairo
>         let class_hash = syscalls::get_class_hash_at_syscall(address).unwrap_syscall();
>         assert(class_hash == expected_class_hash, 'WRONG_CLASS_HASH');
>     }
> ```

we will not implement this for cairo0, right?



_Code quote:_
```Cairo
    fn test_get_class_hash_at(
        self: @ContractState, address: ContractAddress, expected_class_hash: ClassHash
    ) {
        let class_hash = syscalls::get_class_hash_at_syscall(address).unwrap_syscall();
        assert(class_hash == expected_class_hash, 'WRONG_CLASS_HASH');
    }
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1899)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 132 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1899#-OBKGxTu5rSnKOVKo-tS:-OBKHX7i1eNRs53k1m_k:b-81la7d) ([raw file](https://github.com/starkware-libs/sequencer/blob/fc8e7d7fe4fda6536126a6c9bc4dc09a59e25608/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L132)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we will not implement this for cairo0, right?
</blockquote></details>

Right

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1899#-:-OBKQ1KWCECN2qlJUBBU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1899)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1899)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
