### PR TITLE
chore(blockifier_reexecution): replace rpc test with cli command

### PR DESCRIPTION
**Pull request by aner-starkware**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1575)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1575#-OADV4au3nSZDBY_lj9f:-OADV4av68qAIHt_SKMI:bn4nid2) ([raw file](https://github.com/starkware-libs/sequencer/blob/0064093359ad2673ac58dadc0a23e98682dae4d4/crates/blockifier_reexecution/src/main.rs#L1)):*
> ```XML
> use blockifier_reexecution::state_reader::test_state_reader::ConsecutiveTestStateReaders;
> ```

also add `use pretty_assertions::assert_eq;`
___
*[`crates/blockifier_reexecution/src/main.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1575#-OADUhIw-rgqzxpPzLYU:-OADUhIw-rgqzxpPzLYV:b-wc7rlw) ([raw file](https://github.com/starkware-libs/sequencer/blob/0064093359ad2673ac58dadc0a23e98682dae4d4/crates/blockifier_reexecution/src/main.rs#L46)):*
> ```XML
>                 "Running RPC test for block number {} using node url: {}",
>                 block_number, node_url
>             );
> ```

inline the printed fields + end with punctuation



_Suggestion:_
```XML
            println!(
                "Running RPC test for block number {block_number} using node url: {node_url}."
            );
```
___
*[`crates/blockifier_reexecution/src/main.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1575#-OADV6Pl2fepkUGoRXQY:-OADV6Pl2fepkUGoRXQZ:b8bnfuj) ([raw file](https://github.com/starkware-libs/sequencer/blob/0064093359ad2673ac58dadc0a23e98682dae4d4/crates/blockifier_reexecution/src/main.rs#L71)):*
> ```XML
>             // TODO(Aner): compute correct block hash at storage slot 0x1 instead of removing it.
>             expected_state_diff.storage_updates.shift_remove(&ContractAddress(1_u128.into()));
>             assert_eq!(expected_state_diff, actual_state_diff);
> ```

maybe add another print indicating success when the test is done?
___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1575#-OADUbrs3OzxnxOrHAPS:-OADUbrs3OzxnxOrHAPT:b-nty7rd) ([raw file](https://github.com/starkware-libs/sequencer/blob/0064093359ad2673ac58dadc0a23e98682dae4d4/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L109)):*
> ```XML
> 
> // TODO(Aner): remove test, already replaced by cli command.
> #[rstest]
> ```

what exactly remains to be done here?
if the answer is "nothing" please delete the test in this PR



_Code quote:_
```XML
// TODO(Aner): remove test, already replaced by cli command.
#[rstest]
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1575)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1575#-OADV4au3nSZDBY_lj9f:-OADufzl1F3cCBae8Nbp:bs7wumx) ([raw file](https://github.com/starkware-libs/sequencer/blob/0064093359ad2673ac58dadc0a23e98682dae4d4/crates/blockifier_reexecution/src/main.rs#L1)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

also add `use pretty_assertions::assert_eq;`
</blockquote></details>

Done. 
___
*[`crates/blockifier_reexecution/src/main.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1575#-OADUhIw-rgqzxpPzLYU:-OADuVoACPj8qxaBgn6c:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0064093359ad2673ac58dadc0a23e98682dae4d4/crates/blockifier_reexecution/src/main.rs#L46)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

inline the printed fields + end with punctuation
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/main.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1575#-OADV6Pl2fepkUGoRXQY:-OADuVaS0PbA2R8tXRS1:b-2q1eu9) ([raw file](https://github.com/starkware-libs/sequencer/blob/0064093359ad2673ac58dadc0a23e98682dae4d4/crates/blockifier_reexecution/src/main.rs#L71)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe add another print indicating success when the test is done?
</blockquote></details>

Done. Yeah, was kinda weird when I ran it and it just ended :laughing:

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1575)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1575#-OADUbrs3OzxnxOrHAPS:-OADvMWJ511OKdP2Xrwx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0064093359ad2673ac58dadc0a23e98682dae4d4/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L109)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what exactly remains to be done here?
if the answer is "nothing" please delete the test in this PR
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1575#-:-OAEbLHc2TneEer2mCWR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1575)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
