### PR TITLE
refactor(execution): delete starknet version string constants and usages

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1382)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1382?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1382** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1382?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1378** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1378?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1376** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1376?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1382)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 873 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1382#-O9GEsycDd1b8vGygpGe:-O9GEsycDd1b8vGygpGf:bkvd469) ([raw file](https://github.com/starkware-libs/sequencer/blob/cdb878e39b61425ed6489a4a802c2e7842210855/crates/papyrus_execution/src/lib.rs#L873)):*
> ```XML
>         })
>     } else {
>         Ok(VersionedConstants::latest_constants())
> ```

Is this still relevant? Why not try to get the exact constant and return the latest as a fallback?



_Code quote:_
```XML
    if let Some(starknet_version) = starknet_version {
        Ok(match starknet_version {
            StarknetVersion::V0_13_0 | StarknetVersion::V0_13_1 | StarknetVersion::V0_13_2 => {
                VersionedConstants::get(&starknet_version)?
            }
            _ => VersionedConstants::get(&StarknetVersion::V0_13_3)?,
        })
    } else {
        Ok(VersionedConstants::latest_constants())
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1382)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 873 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1382#-O9GEsycDd1b8vGygpGe:-O9VxAxE5KHBG6zlapDz:b5u8m37) ([raw file](https://github.com/starkware-libs/sequencer/blob/cdb878e39b61425ed6489a4a802c2e7842210855/crates/papyrus_execution/src/lib.rs#L873)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Yeah I think this function can be deleted, basically; but behavior isn't exactly identical to `VersionedConstants::get` so I'll leave it to someone from papyrus team.
Note that if you call this with `StarknetVersion::V0_9_1` you will get constants matching `V0_13_3`, and you will get `latest_constants` (not necessarily `V0_13_3`) if you send `None`
</blockquote></details>

deleted the function
___
*[`crates/papyrus_execution/src/lib.rs` line 372 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1382#-O9Vwd239f-88HkiDQyt:-O9Vwd239f-88HkiDQyu:bcq118j) ([raw file](https://github.com/starkware-libs/sequencer/blob/dfb9e29b1b3745a6370ef6c9fdcb1e41add05ebb/crates/papyrus_execution/src/lib.rs#L372)):*
> ```XML
>         .get_starknet_version(block_number)?
>         .unwrap_or(StarknetVersion::LATEST);
>     let versioned_constants = VersionedConstants::get(&starknet_version)?;
> ```

@ShahakShama this behavior has changed now:
previously if `starknet_version` was not one of 0.13.0, 0.13.1 or 0.13.2, you would get 0.13.3 constants; now, you get the constants specified by the version (e.g. 0.13.1.1) or an error (any version below 0.13.0, which is the minimal version for versioned constants).
is that ok?



_Code quote:_
```XML
let versioned_constants = VersionedConstants::get(&starknet_version)?;
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1382#-:-O9iq8ya16ZpTORqr33z:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1382#-:-OAkjY3V3I2Pnd7RrQYg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
