### PR TITLE
test: add threads to regression test

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/144)

### CODE REVIEW

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/144)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/committer_cli/src/tests/regression_tests.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/144#-O2tqg-9CYCvhNNLfjWz:-O2tqg-9CYCvhNNLfjX-:b-gexon7) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae291de4fe14ff2d86a1cf29183f99681fe92b07/crates/committer_cli/src/tests/regression_tests.rs#L165)):*
> ```XML
> #[ignore = "To avoid running the regression test in Coverage or without the --release flag."]
> #[tokio::test(flavor = "multi_thread")]
> pub async fn test_regression_committer_all_files() {
> ```

Please add a print of the input file that errored in case of a failure.



_Code quote:_
```XML
pub async fn test_regression_committer_all_files() {
```
___
*[`crates/committer_cli/src/tests/regression_tests.rs` line 176 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/144#-O2toyYd6LNhuKdv7TJO:-O2toyYd6LNhuKdv7TJP:b-ncvu74) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae291de4fe14ff2d86a1cf29183f99681fe92b07/crates/committer_cli/src/tests/regression_tests.rs#L176)):*
> ```XML
>             let file_str = fs::read_to_string(file_path.unwrap().path()).unwrap();
>             test_single_committer_flow(file_str, "/tmp/".to_owned() + &file_counter.to_string())
>                 .await
> ```

The current temp files are persisted after the run, please use a tempfile (no need for the enumeration)



_Suggestion:_
```XML
let mut file = NamedTempFile::new()?;

test_single_committer_flow(file, file.path.to_string())
                .await
```
___
*[`crates/committer_cli/src/tests/regression_tests.rs` line 181 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/144#-O2tjdZP75rdrx4sBKxr:-O2tjdZP75rdrx4sBKxs:b-21m61g) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae291de4fe14ff2d86a1cf29183f99681fe92b07/crates/committer_cli/src/tests/regression_tests.rs#L181)):*
> ```XML
>     for task in v {
>         task.await.unwrap();
>     }
> ```

Two options - the one below, or using a Joinset - I'm not sure if it's beneficial here so not writing it, but I'm not an expert on tokio.
Haven't checked may have inaccuracies. 



_Suggestion:_
```XML
    let mut tasks = Vec::with_capacity(EXPECTED_NUMBER_OF_FILES);
    for (file_counter, file_path) in dir_path.enumerate() {
        tasks.push(tokio::task::spawn(async move {
            let file_str = fs::read_to_string(file_path.unwrap().path()).unwrap();
            test_single_committer_flow(file_str, "/tmp/".to_owned() + &file_counter.to_string())
                .await
        }));
    }
    futures::future::try_join_all(tasks).await.unwrap();
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/144)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer_cli/src/tests/regression_tests.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/144#-O2tqg-9CYCvhNNLfjWz:-O2wqMP84eOhiF1ITHM5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae291de4fe14ff2d86a1cf29183f99681fe92b07/crates/committer_cli/src/tests/regression_tests.rs#L165)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Please add a print of the input file that errored in case of a failure.
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/regression_tests.rs` line 176 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/144#-O2toyYd6LNhuKdv7TJO:-O2wqNGnDb8fMspVI_o3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae291de4fe14ff2d86a1cf29183f99681fe92b07/crates/committer_cli/src/tests/regression_tests.rs#L176)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

The current temp files are persisted after the run, please use a tempfile (no need for the enumeration)
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/regression_tests.rs` line 181 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/144#-O2tjdZP75rdrx4sBKxr:-O2wqdtt2wWF10iZHwLT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae291de4fe14ff2d86a1cf29183f99681fe92b07/crates/committer_cli/src/tests/regression_tests.rs#L181)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Two options - the one below, or using a Joinset - I'm not sure if it's beneficial here so not writing it, but I'm not an expert on tokio.
Haven't checked may have inaccuracies.
</blockquote></details>

Done.

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/144)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/committer_cli/src/tests/regression_tests.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/144#-O2tqg-9CYCvhNNLfjWz:-O2yOOlV0fTKS59ECKNQ:b-8qjuag) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae291de4fe14ff2d86a1cf29183f99681fe92b07/crates/committer_cli/src/tests/regression_tests.rs#L165)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Meant input file name, sorry.
___
*[`crates/committer_cli/src/tests/regression_tests.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/144#-O2yOI9DBAqGTc3ka2Lm:-O2yOI9DBAqGTc3ka2Ln:b-gk4uob) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9843adf22d4dc82feb6cd03ba7e5d9a0ed6ebb4/crates/committer_cli/src/tests/regression_tests.rs#L164)):*
> ```XML
>         test_single_committer_flow(FLOW_TEST_INPUT.to_string(), OUTPUT_PATH.to_string()).await;
>     if result.is_err() {
>         panic!("Error in result for file: {}", FLOW_TEST_INPUT);
> ```

Print the actual error as well.



_Suggestion:_
```XML
 panic!("Error {} for file: {}", result, FLOW_TEST_INPUT);
```
___
*[`crates/committer_cli/src/tests/regression_tests.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/144#-O2yMDuA3cWHFr-prTQo:-O2yMDuA3cWHFr-prTQp:b-yulsin) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9843adf22d4dc82feb6cd03ba7e5d9a0ed6ebb4/crates/committer_cli/src/tests/regression_tests.rs#L190)):*
> ```XML
>             if result.is_err() {
>                 panic!("Error in result for file: {}", file_str);
>             }
> ```

I don't think printing the content will help debugging - these are very big files, and no we also lose time because we are cloning them. Printing the actual error and filename are helpful. Something like:



_Suggestion:_
```XML
            if result.is_err() {
                panic!("Error {} for file {}", result, file_path);
            }
```
___
*[`crates/committer_cli/src/tests/regression_tests.rs` line 193 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/144#-O2yNA0iALJe1TmswzE-:-O2yNA0j543q4YytQ-J9:blayeni) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9843adf22d4dc82feb6cd03ba7e5d9a0ed6ebb4/crates/committer_cli/src/tests/regression_tests.rs#L193)):*
> ```XML
>         }));
>     }
>     futures::future::join_all(tasks).await;
> ```

`join_all` suppresses errors and continues the run until all tasks are finished; `try_join_all` stops at the first error and raises it.



_Suggestion:_
```XML
 futures::future::try_join_all(tasks).await.unwrap();
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/144)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer_cli/src/tests/regression_tests.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/144#-O2yOI9DBAqGTc3ka2Lm:-O2yhnte7a7C3WqL4icz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9843adf22d4dc82feb6cd03ba7e5d9a0ed6ebb4/crates/committer_cli/src/tests/regression_tests.rs#L164)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Print the actual error as well.
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/regression_tests.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/144#-O2yMDuA3cWHFr-prTQo:-O2yhgx48RnxHzC-fCCQ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9843adf22d4dc82feb6cd03ba7e5d9a0ed6ebb4/crates/committer_cli/src/tests/regression_tests.rs#L190)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I don't think printing the content will help debugging - these are very big files, and no we also lose time because we are cloning them. Printing the actual error and filename are helpful. Something like:
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/regression_tests.rs` line 193 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/144#-O2yNA0iALJe1TmswzE-:-O2yhflH5YxXKkmcyDel:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9843adf22d4dc82feb6cd03ba7e5d9a0ed6ebb4/crates/committer_cli/src/tests/regression_tests.rs#L193)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

`join_all` suppresses errors and continues the run until all tasks are finished; `try_join_all` stops at the first error and raises it.
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/144)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

**Pull request merged**
