### PR TITLE
chore: rename getters for shared clients

### PR DESCRIPTION
**Pull request by nadin-Starkware**
**Stack**:
- #2047
- #2041
- #2040
- #2035
- #2034 ⬅
- #2033
- #2032
- #2030
- #2029
- #2028

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2034)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/starknet_sequencer_node/src/clients.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2034#-OBgRiRCEmV2JcWzf79U:-OBgRiRCEmV2JcWzf79V:b-voryzj) ([raw file](https://github.com/starkware-libs/sequencer/blob/227611b5304ad70f06061fd89ec073125604f661/crates/starknet_sequencer_node/src/clients.rs#L100)):*
> ```XML
> 
> impl SequencerNodeClients {
>     pub fn get_batcher_shared_client(&self) -> Option<SharedBatcherClient> {
> ```

Why do you prefer this over the last version?



_Code quote:_
```XML
er_shared_clie
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2034)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sequencer_node/src/clients.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2034#-OBgRiRCEmV2JcWzf79U:-OBtV4TB4nMunusQFdSS:b-y0ey3m) ([raw file](https://github.com/starkware-libs/sequencer/blob/227611b5304ad70f06061fd89ec073125604f661/crates/starknet_sequencer_node/src/clients.rs#L100)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Why do you prefer this over the last version?
</blockquote></details>

Because I need the ability to return both shared clients and the local client.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2034#-:-OBu74KbE5deHzWGdc4L:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved

**Review by nadin-Starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2034)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Comment by nadin-Starkware** [comment]
✓ Commit merged in pull request [#2041](https://github.com/starkware-libs/sequencer/pull/2041)

**Pull request closed without merging**
