### PR TITLE
chore(blockifier): impl deserialize for versioned_constants

### PR DESCRIPTION
**Pull request by Yonatan-Starkware**

### CODE REVIEW

**Comment by Yonatan-Starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2838?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2838** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2838?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2838?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2514** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2514?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2818](https://github.com/starkware-libs/sequencer/pull/2818) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2818?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2359** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2359?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2501](https://github.com/starkware-libs/sequencer/pull/2501) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2501?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2327** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2327?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2247** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2247?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2188** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2188?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2067** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2067?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2838)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 458 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2838#-OEyGSEBCcvKO684ZNEx:-OEyGSEBCcvKO684ZNEy:btbi2mm) ([raw file](https://github.com/starkware-libs/sequencer/blob/0c59b843e69740cab5ad8a0747141df61c6a180d/crates/blockifier/src/versioned_constants.rs#L458)):*
> ```XML
>                     .get_syscall_gas_cost(&SyscallSelector::Secp256r1New),
>                 keccak: versioned_constants.get_syscall_gas_cost(&SyscallSelector::Keccak),
>                 keccak_round_cost: 180000,
> ```

Is the keccak fix in the next PR? I think it should be before this PR or in this PR. 



_Code quote:_
```XML
                keccak: versioned_constants.get_syscall_gas_cost(&SyscallSelector::Keccak),
                keccak_round_cost: 180000,
```

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2838)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yonatan-Starkware)

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 458 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2838#-OEyGSEBCcvKO684ZNEx:-OF0nXxW5dLPxAwU9x0K:b-yy0321) ([raw file](https://github.com/starkware-libs/sequencer/blob/0c59b843e69740cab5ad8a0747141df61c6a180d/crates/blockifier/src/versioned_constants.rs#L458)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Is the keccak fix in the next PR? I think it should be before this PR or in this PR.
</blockquote></details>

In the next PR. It is not really matter as long as the os_constants are still in the json.

**Review by meship-starkware — APPROVED** [review]
> Reviewed 6 of 7 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2838)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, 1 of 7 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2838)* status: all files reviewed, 3 unresolved discussions (waiting on @Yonatan-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_0_13_0.json` line 106 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2838#-OF1Ij9y5CDDtGB32Q7u:-OF1Ij9y5CDDtGB32Q7v:b-nyu977) ([raw file](https://github.com/starkware-libs/sequencer/blob/93c3ef696614b0d5f58574c6b411c0a0881cec00/crates/blockifier/resources/versioned_constants_0_13_0.json#L106)):*
> ```JSON
>             "entry_point_initial_budget": 1,
>             "step_gas_cost": 600
>         },
> ```

Next time- better to do it in a separate PR :)



_Code quote:_
```JSON
        "fee_transfer_gas_cost": {
            "entry_point_initial_budget": 1,
            "step_gas_cost": 600
        },
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 416 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2838#-OF1Uihh9gme8sXPFTFo:-OF1Uihh9gme8sXPFTFp:bq3ouh1) ([raw file](https://github.com/starkware-libs/sequencer/blob/380967fc1cdcf966adceb119cf1235f72a28e261/crates/blockifier/src/versioned_constants.rs#L416)):*
> ```XML
> 
>         let syscall_gas_costs = &(versioned_constants.os_constants.gas_costs.syscalls);
>         if syscall_gas_costs == &SyscallGasCosts::default() {
> ```

What does ensure that we have a default value when the field is missing?
What will happen [here](https://github.com/starkware-libs/sequencer/blob/edafd7ed1475118df0ed77c634812073e9c75c56/crates/blockifier/src/versioned_constants.rs#L859-L861)?



_Code quote:_
```XML
        if syscall_gas_costs == &SyscallGasCosts::default() {
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 459 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2838#-OF1U32QCSUy4MZ0tTjO:-OF1U32QCSUy4MZ0tTjP:b-jduuqo) ([raw file](https://github.com/starkware-libs/sequencer/blob/380967fc1cdcf966adceb119cf1235f72a28e261/crates/blockifier/src/versioned_constants.rs#L459)):*
> ```XML
>                     .get_syscall_gas_cost(&SyscallSelector::Secp256r1New),
>                 keccak: versioned_constants.get_syscall_gas_cost(&SyscallSelector::Keccak),
>                 keccak_round_cost: 180000,
> ```

What does 180000 represent?



_Suggestion:_
```XML
                //TODO(Yonatan): Remove the default value.
                keccak_round_cost: 180000,
```

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/resources/versioned_constants_0_13_0.json` line 106 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2838#-OF1Ij9y5CDDtGB32Q7u:-OF1VFGpC7sQiCB530FM:b-30l2ue) ([raw file](https://github.com/starkware-libs/sequencer/blob/93c3ef696614b0d5f58574c6b411c0a0881cec00/crates/blockifier/resources/versioned_constants_0_13_0.json#L106)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Next time- better to do it in a separate PR :)
</blockquote></details>

It was. Meshi merged it into this one.

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2838)* status: all files reviewed, 3 unresolved discussions (waiting on @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 416 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2838#-OF1Uihh9gme8sXPFTFo:-OF1VKKmCRCLNR257oab:b-ana11r) ([raw file](https://github.com/starkware-libs/sequencer/blob/380967fc1cdcf966adceb119cf1235f72a28e261/crates/blockifier/src/versioned_constants.rs#L416)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What does ensure that we have a default value when the field is missing?
What will happen [here](https://github.com/starkware-libs/sequencer/blob/edafd7ed1475118df0ed77c634812073e9c75c56/crates/blockifier/src/versioned_constants.rs#L859-L861)?
</blockquote></details>

I just saw the added code. Great!

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 459 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2838#-OF1U32QCSUy4MZ0tTjO:-OF1VUY28ghjJV3AWCaq:b-piu0rf) ([raw file](https://github.com/starkware-libs/sequencer/blob/380967fc1cdcf966adceb119cf1235f72a28e261/crates/blockifier/src/versioned_constants.rs#L459)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What does 180000 represent?
</blockquote></details>

It is the only object in the syscall_gas_costs that does not have a parallel in the os_resources. So I just give it the appropriate value.
In the next PR we add KeccakRound in the OsResources, and then I change this line as well to be as the others.

**Pull request merged**
