### PR TITLE
build: add more utils to regression test

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/952)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/952?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#952** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/952?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#948** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/948?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#946** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/946?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#945** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/945?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by aner-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/952)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7U04bb4lCVRBDiEnnU:-O7U04bb4lCVRBDiEnnV:b-wc9una) ([raw file](https://github.com/starkware-libs/sequencer/blob/cffd45571a43821311deda050b1ccf0e1bc9d2ea/crates/blockifier_regression_test/src/test_state_reader.rs#L77)):*
> ```XML
>             [0, 13, 2, 1] => Ok(StarknetVersion::V0_13_2_1),
>             _ => Err(StateError::StateReadError("Failed to match starknet version".to_string())),
>         }
> ```

Isn't it possible to do this using some sort of macro? 



_Code quote:_
```XML
        match raw_version {
            [0, 13, 0] => Ok(StarknetVersion::V0_13_0),
            [0, 13, 1] => Ok(StarknetVersion::V0_13_1),
            [0, 13, 1, 1] => Ok(StarknetVersion::V0_13_1_1),
            [0, 13, 2] => Ok(StarknetVersion::V0_13_2),
            [0, 13, 2, 1] => Ok(StarknetVersion::V0_13_2_1),
            _ => Err(StateError::StateReadError("Failed to match starknet version".to_string())),
        }
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7U2VocBdRx_drjipW2:-O7U2VocBdRx_drjipW3:bc7jn9z) ([raw file](https://github.com/starkware-libs/sequencer/blob/cffd45571a43821311deda050b1ccf0e1bc9d2ea/crates/blockifier_regression_test/src/test_state_reader.rs#L77)):*
> ```XML
>             [0, 13, 2, 1] => Ok(StarknetVersion::V0_13_2_1),
>             _ => Err(StateError::StateReadError("Failed to match starknet version".to_string())),
>         }
> ```

You're changing this code in the following PR; why do you want me to review it here?



_Code quote:_
```XML
        let block_header: BlockHeader = serde_json::from_value(
            self.0.send_rpc_request("starknet_getBlockWithTxHashes", get_block_params)?,
        )
        .map_err(serde_err_to_state_err)?;
        let raw_version = block_header.starknet_version.0.as_slice();
        match raw_version {
            [0, 13, 0] => Ok(StarknetVersion::V0_13_0),
            [0, 13, 1] => Ok(StarknetVersion::V0_13_1),
            [0, 13, 1, 1] => Ok(StarknetVersion::V0_13_1_1),
            [0, 13, 2] => Ok(StarknetVersion::V0_13_2),
            [0, 13, 2, 1] => Ok(StarknetVersion::V0_13_2_1),
            _ => Err(StateError::StateReadError("Failed to match starknet version".to_string())),
        }
```
___
*[`crates/blockifier_regression_test/src/test_utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7XlE8ECYnylNPfQC3V:-O7XlE8ECYnylNPfQC3W:bqab8fk) ([raw file](https://github.com/starkware-libs/sequencer/blob/cffd45571a43821311deda050b1ccf0e1bc9d2ea/crates/blockifier_regression_test/src/test_utils.rs#L26)):*
> ```XML
> pub fn get_chain_info() -> ChainInfo {
>     ChainInfo { chain_id: ChainId::Mainnet, fee_token_addresses: get_fee_token_addresses() }
> }
> ```

Could you add some docstring here?



_Code quote:_
```XML
pub fn get_rpc_state_reader_config() -> RpcStateReaderConfig {
    RpcStateReaderConfig {
        url: RPC_NODE_URL.to_string(),
        json_rpc_version: JSON_RPC_VERSION.to_string(),
    }
}

pub fn get_chain_info() -> ChainInfo {
    ChainInfo { chain_id: ChainId::Mainnet, fee_token_addresses: get_fee_token_addresses() }
}
```
___
*[`crates/gateway/src/lib.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7TwXuA-Qo8mymAaIS_:-O7TwXuA-Qo8mymAaISa:b-c5zia2) ([raw file](https://github.com/starkware-libs/sequencer/blob/cffd45571a43821311deda050b1ccf0e1bc9d2ea/crates/gateway/src/lib.rs#L7)):*
> ```XML
> pub mod errors;
> pub mod gateway;
> pub mod rpc_objects;
> ```

Blocked until approved by @dorimedini-starkware .



_Code quote:_
```XML
pub 
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/952)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7U2VocBdRx_drjipW2:-O7Ye3frB17ZhwdpSI4b:b-m0982q) ([raw file](https://github.com/starkware-libs/sequencer/blob/cffd45571a43821311deda050b1ccf0e1bc9d2ea/crates/blockifier_regression_test/src/test_state_reader.rs#L77)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

You're changing this code in the following PR; why do you want me to review it here?
</blockquote></details>

I added a test in the following PR, and this function doesn't work as expected, I am moving the fix to this PR 
___
*[`crates/blockifier_regression_test/src/test_utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7XlE8ECYnylNPfQC3V:-O7Yeoe11CSgGrMrBl_B:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cffd45571a43821311deda050b1ccf0e1bc9d2ea/crates/blockifier_regression_test/src/test_utils.rs#L26)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Could you add some docstring here?
</blockquote></details>

Done.

**Comment by aner-starkware** [comment]
*[`crates/gateway/src/lib.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7TwXuA-Qo8mymAaIS_:-O7dbTPJ8QT1kmXuwTF8:bsuz8mk) ([raw file](https://github.com/starkware-libs/sequencer/blob/cffd45571a43821311deda050b1ccf0e1bc9d2ea/crates/gateway/src/lib.rs#L7)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Blocked until approved by @dorimedini-starkware .
</blockquote></details>

Please verify with GW team that this change is OK.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/952)* status: all files reviewed, 10 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7U04bb4lCVRBDiEnnU:-O7hrTGYBu5ViXUo1NVY:bw1immm) ([raw file](https://github.com/starkware-libs/sequencer/blob/cffd45571a43821311deda050b1ccf0e1bc9d2ea/crates/blockifier_regression_test/src/test_state_reader.rs#L77)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Isn't it possible to do this using some sort of macro?
</blockquote></details>

better yet: add an `impl TryFrom<Vec<u8>> for StarknetVersion` block in the `define_vesioned_constants` macro
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7hqWOd4CP5qb7DNRtQ:-O7hqWOd4CP5qb7DNRtR:begzn16) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd0d24509069245b71049dfa45107a58d4993447/crates/blockifier_regression_test/src/test_state_reader.rs#L57)):*
> ```XML
>             None => Self(RpcStateReader::from_number(&get_rpc_state_reader_config(), block_number)),
>         }
>     }
> ```

IMO it's less intuitive to change behavior like this based on `None` value.
consider reverting this change, and implementing a `for_testing` associated method on `RpcStateReaderConfig` that uses the constants you define in test_utils.
callers of `TestStateReader::new` should always pass explicit config...
or, you can also add a `new_for_testing` associated method on `TestStateReader` which calls `new` with this default config.



_Code quote:_
```XML
    pub fn new(config: Option<&RpcStateReaderConfig>, block_number: BlockNumber) -> Self {
        match config {
            Some(config) => Self(RpcStateReader::from_number(config, block_number)),
            None => Self(RpcStateReader::from_number(&get_rpc_state_reader_config(), block_number)),
        }
    }
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7hrmxuA2iOspNPL9Rv:-O7hrmxuA2iOspNPL9Rw:bbuk00x) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd0d24509069245b71049dfa45107a58d4993447/crates/blockifier_regression_test/src/test_state_reader.rs#L84)):*
> ```XML
>         let starknet_version = self.get_starknet_version()?;
>         let versioned_constants: &'static VersionedConstants = starknet_version.into();
>         Ok(versioned_constants)
> ```

does this work? more concise



_Suggestion:_
```XML
        Ok(self.get_starknet_version()?.into())
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 90 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7hry8l0FhFA8dkKdwp:-O7hry8l0FhFA8dkKdwq:b-qvyz1i) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd0d24509069245b71049dfa45107a58d4993447/crates/blockifier_regression_test/src/test_state_reader.rs#L90)):*
> ```XML
>         Ok(BlockContext::new(
>             self.get_block_info()?,
>             get_chain_info(),
> ```

this should be configurable; we may want to reexecute testnet blocks, no?



_Code quote:_
```XML
get_chain_info(),
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 91 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7hs24i8Y7fGWWUyLb0:-O7hs24i8Y7fGWWUyLb1:b-55qlh) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd0d24509069245b71049dfa45107a58d4993447/crates/blockifier_regression_test/src/test_state_reader.rs#L91)):*
> ```XML
>             self.get_block_info()?,
>             get_chain_info(),
>             self.get_versioned_constants()?.clone(),
> ```

why clone? it's static; do we always clone VC when creating block context?



_Code quote:_
```XML
self.get_versioned_constants()?.clone()
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 103 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7hsAio7GyAtmAc0uzu:-O7hsAio7GyAtmAc0uzv:b3bk3lu) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd0d24509069245b71049dfa45107a58d4993447/crates/blockifier_regression_test/src/test_state_reader.rs#L103)):*
> ```XML
>             CachedState::new(test_state_reader),
>             block_context,
>             TransactionExecutorConfig::default(),
> ```

don't we want to control this? is it in a later PR?



_Code quote:_
```XML
TransactionExecutorConfig::default()
```
___
*[`crates/blockifier_regression_test/src/test_utils.rs` line 0 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7hqj9pEr0fbvAANh5Y:-O7hqj9qEWn4DB2ulFz7:bif0lcn) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd0d24509069245b71049dfa45107a58d4993447/crates/blockifier_regression_test/src/test_utils.rs#L0)):*
consider renaming this module to `utils` - it's only "test utils" because of the crate it's in

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/952)* status: all files reviewed, 10 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

**Review by aner-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/952)* status: all files reviewed, 7 unresolved discussions (waiting on @AvivYossef-starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/952)* status: 3 of 7 files reviewed, 6 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7U04bb4lCVRBDiEnnU:-O7w_J-A6iW2KPE5OJNL:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/cffd45571a43821311deda050b1ccf0e1bc9d2ea/crates/blockifier_regression_test/src/test_state_reader.rs#L77)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

better yet: add an `impl TryFrom<Vec<u8>> for StarknetVersion` block in the `define_vesioned_constants` macro
</blockquote></details>

Done
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7hqWOd4CP5qb7DNRtQ:-O7wQADn-1XCnPIsgq14:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd0d24509069245b71049dfa45107a58d4993447/crates/blockifier_regression_test/src/test_state_reader.rs#L57)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

IMO it's less intuitive to change behavior like this based on `None` value.
consider reverting this change, and implementing a `for_testing` associated method on `RpcStateReaderConfig` that uses the constants you define in test_utils.
callers of `TestStateReader::new` should always pass explicit config...
or, you can also add a `new_for_testing` associated method on `TestStateReader` which calls `new` with this default config.
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7hrmxuA2iOspNPL9Rv:-O7w_TU8AnsY9Gq7oI0C:b-izbj8h) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd0d24509069245b71049dfa45107a58d4993447/crates/blockifier_regression_test/src/test_state_reader.rs#L84)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does this work? more concise
</blockquote></details>

Yes, thanks
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 90 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7hry8l0FhFA8dkKdwp:-O7waKE199PVv300EgvJ:b-gxkuw1) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd0d24509069245b71049dfa45107a58d4993447/crates/blockifier_regression_test/src/test_state_reader.rs#L90)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this should be configurable; we may want to reexecute testnet blocks, no?
</blockquote></details>

Yes, but I thought I would start with support for Mainnet only. I might need to make more changes to support Testnet.
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 91 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7hs24i8Y7fGWWUyLb0:-O7wb-62BXKj_ie_8pEA:bupxaut) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd0d24509069245b71049dfa45107a58d4993447/crates/blockifier_regression_test/src/test_state_reader.rs#L91)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why clone? it's static; do we always clone VC when creating block context?
</blockquote></details>

The block context needs to own the versioned constants, so it does not matter that it is static. We also clone it [here](https://github.com/starkware-libs/sequencer/blob/2fb9f3209de3e9b8952298b918e89ff0e5af7ec0/crates/blockifier/src/versioned_constants.rs#L278). and [here](https://github.com/starkware-libs/sequencer/blob/318ee7fdd236d3a39c2ead8d1402436328be2cd7/crates/native_blockifier/src/py_block_executor.rs#L174)
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 103 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7hsAio7GyAtmAc0uzu:-O7wd9AV4OOJADeuNr-b:bvxfhyl) ([raw file](https://github.com/starkware-libs/sequencer/blob/bd0d24509069245b71049dfa45107a58d4993447/crates/blockifier_regression_test/src/test_state_reader.rs#L103)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't we want to control this? is it in a later PR?
</blockquote></details>

Yes, I just try to start with the minimum that works
___
*[`crates/gateway/src/lib.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7TwXuA-Qo8mymAaIS_:-O7wxgCq9mWwfEELWS9x:bnt9p6o) ([raw file](https://github.com/starkware-libs/sequencer/blob/cffd45571a43821311deda050b1ccf0e1bc9d2ea/crates/gateway/src/lib.rs#L7)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Please verify with GW team that this change is OK.
</blockquote></details>

@dafnamatsry  can you plz approve?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/952)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 69 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7xJNw_AFd9YvGLUqFN:-O7xJNw_AFd9YvGLUqFO:b-a4u5oz) ([raw file](https://github.com/starkware-libs/sequencer/blob/4de802768247454971bab364d18c834eb98443ae/crates/blockifier/src/versioned_constants.rs#L69)):*
> ```XML
> 
> 
>         impl TryFrom<&str> for StarknetVersion {
> ```

fix whitespace



_Code quote:_
```XML
        }



        impl TryFrom<&str> for StarknetVersion {
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 79 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7xKH_yCw7M63RuF6xF:-O7xKH_yCw7M63RuF6xG:bj6dmli) ([raw file](https://github.com/starkware-libs/sequencer/blob/4de802768247454971bab364d18c834eb98443ae/crates/blockifier/src/versioned_constants.rs#L79)):*
> ```XML
>                 }
>             }
>         }
> ```

consider adding this to prevent human errors in macro construction



_Suggestion:_
```XML
}

#[cfg(test)]
#[test]
fn test_variant_name_string_consistency() {
    $(
        assert_eq!(
            "v".to_owned() + $version_str,
            String::from(stringify!($variant)).to_lowercase().replace("_",".")
        );
    )*
}
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/952)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 79 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7xKH_yCw7M63RuF6xF:-O7y-pGkBJySQC_dYUua:b-ym0t2v) ([raw file](https://github.com/starkware-libs/sequencer/blob/4de802768247454971bab364d18c834eb98443ae/crates/blockifier/src/versioned_constants.rs#L79)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

consider adding this to prevent human errors in macro construction
</blockquote></details>

ok now that you are rebased, you can compare the version string to the variant using `String::from(StarknetVersion::$variant)`

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/952)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 117 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7y09R4DuP7I_V2tt86:-O7y09R4DuP7I_V2tt87:bfvsr26) ([raw file](https://github.com/starkware-libs/sequencer/blob/c911fa741b4144e4d21dd9b09a5aaac0a5d3936a/crates/blockifier/src/versioned_constants.rs#L117)):*
> ```XML
> 
>         #[cfg(test)]
>         mod tests {
> ```

the `mod` is required? tests need a separate scope?



_Code quote:_
```XML
mod tests {
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 124 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/952#-O7y02A79XnFMFqjNwm-:-O7y02A79XnFMFqjNwm0:b-8e16op) ([raw file](https://github.com/starkware-libs/sequencer/blob/c911fa741b4144e4d21dd9b09a5aaac0a5d3936a/crates/blockifier/src/versioned_constants.rs#L124)):*
> ```XML
>                     assert_eq!(
>                         "v".to_owned() + $version_str,
>                         String::from(stringify!($variant)).to_lowercase().replace("_", ".")
> ```

now that you are rebased, you can do this instead



_Suggestion:_
```XML
String::from(StarknetVersion::$variant)
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/952#-:-O810WbOAbo9v8gUQ6vk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
