### PR TITLE
feat(blockifier): add allocation cost versioned constant

### PR DESCRIPTION
**Pull request by yoavGrs**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2200)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2200#-OC9JyM--7DnaZnUBTru:-OC9JyM--7DnaZnUBTrv:b4cohfd) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d8699bde7126af1a908744a510bbdd55c0a7716/crates/blockifier/src/versioned_constants.rs#L188)):*
> ```XML
>     // Fee related.
>     pub(crate) vm_resource_fee_cost: Arc<VmResourceCosts>,
>     // Cost in units of onchain data segment length
> ```

1. end in punctuation
2. @Yoni-Starkware should these be some other units...? e.g. sierra gas? allocations incur L2 costs, not L1



_Code quote:_
```XML
// Cost in units of onchain data segment length
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2200)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2200#-OCYjrbS9jD-6--blYnS:-OCYjrbS9jD-6--blYnT:b-w1vodz) (no related file):*
Python side:
https://reviewable.io/reviews/starkware-industries/starkware/36292
___
*[`crates/blockifier/src/versioned_constants.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2200#-OC9JyM--7DnaZnUBTru:-OCYjnoUEzcfXYiAJC90:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d8699bde7126af1a908744a510bbdd55c0a7716/crates/blockifier/src/versioned_constants.rs#L188)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. end in punctuation
2. @Yoni-Starkware should these be some other units...? e.g. sierra gas? allocations incur L2 costs, not L1
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2200#-:-OCYlzFC0Yeq3Tyk6EjT:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

**Comment by yoavGrs** [comment]
* **#2150** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2150?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2149** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2149?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2175** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2175?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2200** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2200?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2200?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2200#-:-OCbyfqGDOReT8e_ZAde:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

**Comment by yoavGrs** [comment]
### Merge activity

* **Nov 26, 5:53 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2200).

**Pull request merged**
