### PR TITLE
feat(starknet_integration_tests): pass test scenarios from the test body

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Comment by yair-starkware** [comment]
* **#2724** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2724?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2724?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2724)* status: all files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware and @yair-starkware)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2724#-OEP7asaAeKGyVtHfGXQ:-OEP7asb8RkcWiszjMwj:b-kd9mr7) ([raw file](https://github.com/starkware-libs/sequencer/blob/e02ed63f97db30e5edc57d274714502d4165a488/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L70)):*
> ```XML
> 
>     let test_tx_hashes_scenarios =
>         [test_tx_hashes_for_integration_test, test_tx_hashes_for_integration_test];
> ```

Why do you need these?



_Code quote:_
```XML
    let create_rpc_txs_scenarios =
        [create_txs_for_integration_test, create_txs_for_integration_test];

    let test_tx_hashes_scenarios =
        [test_tx_hashes_for_integration_test, test_tx_hashes_for_integration_test];
```
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2724#-OEP7r7a0QdthGRFGp6D:-OEP7r7a0QdthGRFGp6E:bnsnitk) ([raw file](https://github.com/starkware-libs/sequencer/blob/e02ed63f97db30e5edc57d274714502d4165a488/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L73)):*
> ```XML
> 
>     // Build multiple heights to ensure heights are committed.
>     for (height, expected_content_id, create_rpc_txs_fn, test_tx_hashes_fn) in itertools::izip!(
> ```

I think actually it is important to assert they are all the same length. Otherwise some of the test might be missing without us noticing 
___
*[`crates/starknet_integration_tests/src/utils.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2724#-OEP7QnEAeoQV0otuS31:-OEP7QnEAeoQV0otuS32:bgtx0bj) ([raw file](https://github.com/starkware-libs/sequencer/blob/e02ed63f97db30e5edc57d274714502d4165a488/crates/starknet_integration_tests/src/utils.rs#L207)):*
> ```XML
>     create_rpc_txs_fn: impl Fn(&mut MultiAccountTransactionGenerator) -> Vec<RpcTransaction>,
>     send_rpc_tx_fn: &'a mut dyn FnMut(RpcTransaction) -> Fut,
>     test_tx_hashes_fn: impl Fn(&[TransactionHash]) -> Vec<TransactionHash>,
> ```

Should these two be coupled?



_Code quote:_
```XML
    create_rpc_txs_fn: impl Fn(&mut MultiAccountTransactionGenerator) -> Vec<RpcTransaction>,
    send_rpc_tx_fn: &'a mut dyn FnMut(RpcTransaction) -> Fut,
    test_tx_hashes_fn: impl Fn(&[TransactionHash]) -> Vec<TransactionHash>,
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2724)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2724#-OEP7QnEAeoQV0otuS31:-OET22Pv0O5yMrUxjiOE:b-7zi8tj) ([raw file](https://github.com/starkware-libs/sequencer/blob/e02ed63f97db30e5edc57d274714502d4165a488/crates/starknet_integration_tests/src/utils.rs#L207)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Should these two be coupled?
</blockquote></details>

WDYM?
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2724#-OEP7asaAeKGyVtHfGXQ:-OET1rDc3oGbM3vqnV0s:b-n3z5g2) ([raw file](https://github.com/starkware-libs/sequencer/blob/e02ed63f97db30e5edc57d274714502d4165a488/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L70)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why do you need these?
</blockquote></details>

When adding deploy_account I need different test txs
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2724#-OEP7r7a0QdthGRFGp6D:-OETR_yP3wewUbdSg_3T:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e02ed63f97db30e5edc57d274714502d4165a488/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L73)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I think actually it is important to assert they are all the same length. Otherwise some of the test might be missing without us noticing
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2724)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware and @yair-starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2724#-OEP7QnEAeoQV0otuS31:-OETp1CR2laTuPpKFkpe:b-2sb7xu) ([raw file](https://github.com/starkware-libs/sequencer/blob/e02ed63f97db30e5edc57d274714502d4165a488/crates/starknet_integration_tests/src/utils.rs#L207)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

`create_rpc_txs_fn` and `test_tx_hashes_fn`.

**Comment by yair-starkware** [comment]
*[`crates/starknet_integration_tests/src/utils.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2724#-OEP7QnEAeoQV0otuS31:-OEiHNlL92zi2FTdIa0k:bd0ypek) ([raw file](https://github.com/starkware-libs/sequencer/blob/e02ed63f97db30e5edc57d274714502d4165a488/crates/starknet_integration_tests/src/utils.rs#L207)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

`create_rpc_txs_fn` and `test_tx_hashes_fn`.
</blockquote></details>

Added a TODO because it is a bit tricky task

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2724#-:-OExmKOR0FCpYKQYqvz6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
