### PR TITLE
test(starknet_integration_tests): test proposer-validator setup in flow test

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Comment by yair-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2348?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2348** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2348?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2348?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2299** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2299?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2242** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2242?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2253** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2253?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2348)* status: all files reviewed, 3 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2348#-ODfnpNm2q3rzWftptAG:-ODfnpNn9cUhdVqNeXRU:bskfwr5) ([raw file](https://github.com/starkware-libs/sequencer/blob/1ebaa4d02b7c0dfeaabe78fca6a10c65aad81d61/crates/sequencing/papyrus_consensus/src/lib.rs#L24)):*
> ```XML
> /// The offset of the validator ids used in the consensus.
> // TODO(Matan): Remove once PapyrusConsensusContext uses actual validator IDs.
> pub const VALIDATOR_OFFSET: u64 = 100;
> ```

Remove this and use `DEFAULT_VALIDATOR_ID` Arni added (need to rebase).



_Code quote:_
```XML
/// The offset of the validator ids used in the consensus.
// TODO(Matan): Remove once PapyrusConsensusContext uses actual validator IDs.
pub const VALIDATOR_OFFSET: u64 = 100;
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs` line 48 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2348#-ODfnwdZ0c-ofM2OVpBR:-ODfnwdZ0c-ofM2OVpBS:b-hsct7t) ([raw file](https://github.com/starkware-libs/sequencer/blob/1ebaa4d02b7c0dfeaabe78fca6a10c65aad81d61/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context.rs#L48)):*
> ```XML
> 
> const CHANNEL_SIZE: usize = 100;
> ```

remove blank line.
___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 29 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2348#-ODfmuSd1dNAFuTHlcgX:-ODfmuSd1dNAFuTHlcgY:b-9xw8zl) ([raw file](https://github.com/starkware-libs/sequencer/blob/1ebaa4d02b7c0dfeaabe78fca6a10c65aad81d61/crates/starknet_integration_tests/src/flow_test_setup.rs#L29)):*
> ```XML
> };
> 
> const PROPOSER_ID: usize = 0;
> ```

They are now interchanging, right? They both propose one block and validate the other



_Suggestion:_
```XML
const PROPOSER_INDEX: usize = 0;
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2348)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 29 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2348#-ODfmuSd1dNAFuTHlcgX:-ODja_O-Aua1oL4uMNa2:ba3o3s1) ([raw file](https://github.com/starkware-libs/sequencer/blob/1ebaa4d02b7c0dfeaabe78fca6a10c65aad81d61/crates/starknet_integration_tests/src/flow_test_setup.rs#L29)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

They are now interchanging, right? They both propose one block and validate the other
</blockquote></details>

Renamed
___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2348#-ODfnpNm2q3rzWftptAG:-ODjabbV7NyCFo-VLBCo:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1ebaa4d02b7c0dfeaabe78fca6a10c65aad81d61/crates/sequencing/papyrus_consensus/src/lib.rs#L24)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Remove this and use `DEFAULT_VALIDATOR_ID` Arni added (need to rebase).
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r6, 2 of 4 files at r7, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2348#-:-ODk8KIE2WGs21GCUcTR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Comment by yair-starkware** [comment]
### Merge activity

* **Dec 10, 7:43 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2348).

**Pull request merged**
