### PR TITLE
test(starknet_mempool): validate fee escalation attempt not replaced

### PR DESCRIPTION
**Pull request by ayeletstarkware**

### CODE REVIEW

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2165#-:-OC2scmFDyzn3jOs2U15:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2165)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2165)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/starknet_mempool/src/mempool_test.rs` line 153 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2165#-OCDG5Ld5y3IcOwd7YtO:-OCDG5LeBXTB37Lta8h5:b-p59dpq) ([raw file](https://github.com/starkware-libs/sequencer/blob/76dd5408b5dc96b44595cd0660814cff7eef1699/crates/starknet_mempool/src/mempool_test.rs#L153)):*
> ```XML
> ) {
>     // Ensure the transaction is not in both queues.
>     assert!(!(in_priority_queue && in_pending_queue));
> ```

Please try to find a more idiomatic way (similar to Pythonic `any/all`) + add an informative message (which will make the comment redundant; note that it should be slightly different than the comment and explain the behavioral assumptions of the Q).



_Code quote:_
```XML
assert!(!(in_priority_queue && in_pending_queue));
```
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2165#-OCDHS9H-wrhnFVIxGdI:-OCDHS9H-wrhnFVIxGdJ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/76dd5408b5dc96b44595cd0660814cff7eef1699/crates/starknet_mempool/src/mempool_test.rs#L175)):*
> ```XML
>     }
>     let expected_mempool_content = builder.with_pool([existing_tx]).build();
>     expected_mempool_content.assert_eq(&mempool);
> ```





_Suggestion:_
```XML
    let mut builder = MempoolContentBuilder::new();
    
    if in_priority_queue {
        builder = builder.with_priority_queue([TransactionReference::new(&existing_tx)]);
    }
    
    if in_pending_queue {
        builder = builder.with_pending_queue([TransactionReference::new(&existing_tx)]);
    }
    
    let expected_mempool_content = builder.with_pool([existing_tx]).build();
    expected_mempool_content.assert_eq(&mempool);
```
___
*[`crates/starknet_mempool/src/mempool_test.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2165#-OCDHDQe0nehBVMaoYii:-OCDHDQe0nehBVMaoYij:bwqncyk) ([raw file](https://github.com/starkware-libs/sequencer/blob/76dd5408b5dc96b44595cd0660814cff7eef1699/crates/starknet_mempool/src/mempool_test.rs#L189)):*
> ```XML
>         invalid_replacement_inputs,
>         false,
>         false,
> ```

Names?



_Code quote:_
```XML
        false,
        false,
```

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2165)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2165)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

**Pull request closed without merging**
