### PR TITLE
chore: streamline class info constructor

### PR DESCRIPTION
**Pull request by ArniStarkware**
It contains the lion's share of what was once #427.

It was split as parts of the original PR are controversial - so let us deal with one idea at a time.

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1215)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#427** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/427?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1215** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1215?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1215)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @yair-starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 632 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1215#-O8_zj7C-Xb2MaU-UEmK:-O8_zj7D5zxNHqvHjsuR:b4mn959) ([raw file](https://github.com/starkware-libs/sequencer/blob/85481c01646543541e40e0359e0c5270019b3ab7/crates/blockifier/src/execution/contract_class.rs#L632)):*
> ```XML
>     pub fn new_v1(
>         contract_class: ContractClassV1,
>         sierra_program_length: usize,
> ```

Or make sure it is has a positive value.



_Suggestion:_
```XML
sierra_program_length: NonZeroUsize,
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 170 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1215#-O8_yx_ZDJW83YGrCTUB:-O8_yx__0HPAxqk3Iyls:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/85481c01646543541e40e0359e0c5270019b3ab7/crates/native_blockifier/src/py_transaction.rs#L170)):*
> ```XML
>             | starknet_api::transaction::DeclareTransaction::V1(_) => {
>                 let contract_class =
>                     ContractClassV0::try_from_json_string(&py_class_info.raw_contract_class)?;
> ```





_Suggestion:_
```XML
                    ContractClassV0::try_from_json_string(&py_class_info.raw_contract_class)?;
                    assert_eq!(py_class_info.sierra_program_length, 0);
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1215)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @yair-starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 632 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1215#-O8_zj7C-Xb2MaU-UEmK:-O8a9Fgg1OSodIZajrtQ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/85481c01646543541e40e0359e0c5270019b3ab7/crates/blockifier/src/execution/contract_class.rs#L632)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Or make sure it is has a positive value.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 170 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1215#-O8_yx_ZDJW83YGrCTUB:-O8a1HFn87eTsa_-lSue:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/85481c01646543541e40e0359e0c5270019b3ab7/crates/native_blockifier/src/py_transaction.rs#L170)):*
> ```XML
>             | starknet_api::transaction::DeclareTransaction::V1(_) => {
>                 let contract_class =
>                     ContractClassV0::try_from_json_string(&py_class_info.raw_contract_class)?;
> ```

Done.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1215)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @yair-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 826 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1215#-O8aAaTu4QENMD1rPv90:-O8aAaTu4QENMD1rPv91:bgr7wco) ([raw file](https://github.com/starkware-libs/sequencer/blob/d4d1890f8844c1d533bae14693512f4458100b61/crates/papyrus_execution/src/lib.rs#L826)):*
> ```XML
>                         contract_class_version: 1,
>                         sierra_program_length: 0,
>                     },
> ```

This code is repeated throughout the repository.
Maybe it's better to have the method getting the sierra length as a `usize` and checking there that it's not zero.
WDYT?
(this will create inconsistency in the signature of the two `new` methods, which is not great).



_Code quote:_
```XML
                ExecutionError::BadDeclareTransaction {
                    tx: DeclareTransaction::V3(declare_tx.clone()),
                    err: ContractClassError::ContractClassVersionSierraProgramLengthMismatch {
                        contract_class_version: 1,
                        sierra_program_length: 0,
                    },
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1215)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @yair-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 826 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1215#-O8aAaTu4QENMD1rPv90:-O8b5Y7U0Yub-uMtnqc1:bhm1spx) ([raw file](https://github.com/starkware-libs/sequencer/blob/d4d1890f8844c1d533bae14693512f4458100b61/crates/papyrus_execution/src/lib.rs#L826)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

This code is repeated throughout the repository.
Maybe it's better to have the method getting the sierra length as a `usize` and checking there that it's not zero.
WDYT?
(this will create inconsistency in the signature of the two `new` methods, which is not great).
</blockquote></details>

No need to return an error, it's enough to add an assert, as it is an invariant of a cairo 1 contract.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1215)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @yair-starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 588 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1215#-O8qwMkeCUgiYIuGQlnD:-O8qwMkeCUgiYIuGQlnE:b-yudn2g) ([raw file](https://github.com/starkware-libs/sequencer/blob/625fcafaec4f551b7592cd54aded729ff842a234/crates/blockifier/src/execution/contract_class.rs#L588)):*
> ```XML
>             + self.abi_length()
>     }
> ```

A suggestion:
Leave the `new` method, replacing the error with panic.
I agree that it is a bit ugly to ask for a sierra length for a Cairo 0 contract *but*, Cairo 0 is not here to stay and having one new method allow to avoid matches on the contract class.

WDYT?
___
*[`crates/blockifier/src/execution/errors.rs` line 133 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1215#-O8qw9IH7yu2bLEAUH3e:-O8qw9IH7yu2bLEAUH3f:b5uk8lv) ([raw file](https://github.com/starkware-libs/sequencer/blob/625fcafaec4f551b7592cd54aded729ff842a234/crates/blockifier/src/execution/errors.rs#L133)):*
> ```XML
> 
> // TODO(Arni): remove this error variant. Squash this error into other error types. At least
> // simplify it.
> ```

Why is this error still needed after your changes?



_Code quote:_
```XML
// TODO(Arni): remove this error variant. Squash this error into other error types. At least
// simplify it.
```

**Comment by ArniStarkware** [comment]
This becomes harder now that there are three variants of contract class.

**Pull request closed without merging**
