### PR TITLE
refactor(blockifier): refactor to_discounted_l1_gas

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1178)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1178?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1179** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1179?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1178** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1178?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1177** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1177?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1176** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1176?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1175** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1175?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1174** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1174?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1173** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1173?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1172** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1172?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1178#-:-O8kcadI6Bwe1WFFzg0X:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 375 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1178#-O8kcWb-9QuN0DJQ6dWC:-O8kcWb-9QuN0DJQ6dWD:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ecff5850053d1b6fb54221dd57d5801d1ce4b62f/crates/blockifier/src/fee/resources.rs#L375)):*
> ```XML
>             l1_data_gas_fee.checked_div_ceil(gas_prices.l1_gas_price).unwrap_or_else(|| {
>                 log::warn!(
>                     "Discounted L1 gas cost overflowed: division of L1 data fee {} by regular L1 \
> ```





_Suggestion:_
```XML
ee ({}) by 
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1178)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1178#-:-O8kySFPAYoDOSuvJXaq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Oct 9, 7:30 AM EDT**: @dorimedini-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1178).

**Pull request merged**
