### PR TITLE
chore: extend remote communication config

### PR DESCRIPTION
**Pull request by nadin-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1207)

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1207)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/mempool_infra/src/component_definitions.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1207#-O8cGJ9j1-aEIpRAXEgF:-O8cGJ9j1-aEIpRAXEgG:b-ar1t08) ([raw file](https://github.com/starkware-libs/sequencer/blob/188d145ec77efe9928420c6b2d2b8a04aab6a721/crates/mempool_infra/src/component_definitions.rs#L117)):*
> ```XML
> pub struct RemoteComponentCommunicationConfig {
>     pub client_config: RemoteConnectionConfig,
>     pub server_config: RemoteConnectionConfig,
> ```

I suggest we go for separate `RemoteClientConfig` and `RemoteServerConfig`, as there are fields that are relevant for one but not the other (despite some common). 



_Code quote:_
```XML
    pub client_config: RemoteConnectionConfig,
    pub server_config: RemoteConnectionConfig,
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1207)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_definitions.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1207#-O8cGJ9j1-aEIpRAXEgF:-O8fcMay5dXzjdMx2C6V:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/188d145ec77efe9928420c6b2d2b8a04aab6a721/crates/mempool_infra/src/component_definitions.rs#L117)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I suggest we go for separate `RemoteClientConfig` and `RemoteServerConfig`, as there are fields that are relevant for one but not the other (despite some common).
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1207)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/mempool_infra/src/component_definitions.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1207#-O8hEye-7l3zOhJ5QyZZ:-O8hEye-7l3zOhJ5QyZ_:b12uxpc) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b005d921a86f53eccc6e2dba28433581cfcd5aa/crates/mempool_infra/src/component_definitions.rs#L74)):*
> ```XML
> pub struct LocalComponentCommunicationConfig {
>     pub channel_buffer_size: usize,
> }
> ```

Please add a TODO here (on both of our names) to refactor this into two different config structs, one for the client and one for the server; the server one should hold the current value, and the client one should be an empty struct.



_Code quote:_
```XML
// The communication configuration of the local component.
#[derive(Clone, Debug, Serialize, Deserialize, Validate, PartialEq)]
pub struct LocalComponentCommunicationConfig {
    pub channel_buffer_size: usize,
}
```
___
*[`crates/mempool_infra/src/component_definitions.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1207#-O8hEppJENg9QZavozab:-O8hEppJENg9QZavozac:b-bm6g2x) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b005d921a86f53eccc6e2dba28433581cfcd5aa/crates/mempool_infra/src/component_definitions.rs#L101)):*
> ```XML
> }
> 
> impl Default for RemoteClientConnectionConfig {
> ```

Please remove `Connection` from this name, IMO it's redundant.



_Code quote:_
```XML
RemoteClientConnectionConfig
```
___
*[`crates/mempool_infra/src/component_definitions.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1207#-O8hEOvT5BkepX9La_XE:-O8hEOvT5BkepX9La_XF:b-l3fz38) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b005d921a86f53eccc6e2dba28433581cfcd5aa/crates/mempool_infra/src/component_definitions.rs#L145)):*
> ```XML
> 
> #[derive(Clone, Debug, Serialize, Deserialize, Validate, PartialEq)]
> pub struct RemoteServerConnectionConfig {
> ```

Ditto regarding the name.



_Code quote:_
```XML
RemoteServerConnectionConfig
```
___
*[`crates/mempool_infra/src/component_definitions.rs` line 181 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1207#-O8hD8hz7hjBPLuZ-AJO:-O8hD8hz7hjBPLuZ-AJP:bbd79gx) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b005d921a86f53eccc6e2dba28433581cfcd5aa/crates/mempool_infra/src/component_definitions.rs#L181)):*
> ```XML
>         result
>     }
> }
> ```

 I expect that the node config will list for each component only one of the following:
1. `RemoteClientConnectionConfig` if this component is accessed through a remote connection
2. `RemoteServerConnectionConfig` if this component is run locally but needs to be accessed by other nodes through a remote connection
3. Neither if the component is disabled.

So, I don't see a scenario where this struct containing both `RemoteClientConnectionConfig` and `RemoteServerConnectionConfig` will be used.

Do you have anything else in mind? If not, please remove this struct, and use the appropriate config type in the relevant tests.



_Code quote:_
```XML
// The communication configuration of the remote component.
#[derive(Clone, Default, Debug, Serialize, Deserialize, Validate, PartialEq)]
pub struct RemoteComponentCommunicationConfig {
    pub client_config: RemoteClientConnectionConfig,
    pub server_config: RemoteServerConnectionConfig,
}

impl SerializeConfig for RemoteComponentCommunicationConfig {
    fn dump(&self) -> BTreeMap<ParamPath, SerializedParam> {
        let mut result = append_sub_config_name(self.client_config.dump(), "client_config");
        let server_config_dump = append_sub_config_name(self.server_config.dump(), "server_config");
        result.extend(server_config_dump);
        result
    }
}
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1207)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_definitions.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1207#-O8hEye-7l3zOhJ5QyZZ:-O8lssKX74gPPyCN-Vyo:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b005d921a86f53eccc6e2dba28433581cfcd5aa/crates/mempool_infra/src/component_definitions.rs#L74)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add a TODO here (on both of our names) to refactor this into two different config structs, one for the client and one for the server; the server one should hold the current value, and the client one should be an empty struct.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_definitions.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1207#-O8hEppJENg9QZavozab:-O8kAeuo-yWateJi0oRs:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b005d921a86f53eccc6e2dba28433581cfcd5aa/crates/mempool_infra/src/component_definitions.rs#L101)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please remove `Connection` from this name, IMO it's redundant.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_definitions.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1207#-O8hEOvT5BkepX9La_XE:-O8kApLg1_pj0C4nTi68:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b005d921a86f53eccc6e2dba28433581cfcd5aa/crates/mempool_infra/src/component_definitions.rs#L145)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Ditto regarding the name.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_definitions.rs` line 181 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1207#-O8hD8hz7hjBPLuZ-AJO:-O8lsveMAAoMr9Nn4zsO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b005d921a86f53eccc6e2dba28433581cfcd5aa/crates/mempool_infra/src/component_definitions.rs#L181)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I expect that the node config will list for each component only one of the following:
1. `RemoteClientConnectionConfig` if this component is accessed through a remote connection
2. `RemoteServerConnectionConfig` if this component is run locally but needs to be accessed by other nodes through a remote connection
3. Neither if the component is disabled.

So, I don't see a scenario where this struct containing both `RemoteClientConnectionConfig` and `RemoteServerConnectionConfig` will be used.

Do you have anything else in mind? If not, please remove this struct, and use the appropriate config type in the relevant tests.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1207#-:-O8psBXY3JCFlvCsVS1c:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Pull request merged**
