### PR TITLE
feat(blockifier): return compressed state diff at finalizing

### PR DESCRIPTION
**Pull request by yoavGrs**

### CODE REVIEW

**Comment by yoavGrs** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2767?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2767** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2767?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2767?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2766** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2766?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2765** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2765?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2674** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2674?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2675](https://github.com/starkware-libs/sequencer/pull/2675) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2675?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2535** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2535?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2534** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2534?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2767)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2767#-OExHqHv0zkEBiNK5NKA:-OExHqHv0zkEBiNK5NKB:b-5uq2lo) (no related file):*
The python side:
https://reviewable.io/reviews/starkware-industries/starkware/36522
https://reviewable.io/reviews/starkware-industries/starkware/36523

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2767#-:-OExjFIy7LD5CY9Qp97t:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2767)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2767)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2767)* status: all files reviewed, 2 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 260 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2767#-OFGbZD024MQ3aUh7fnG:-OFGbZD024MQ3aUh7fnH:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7c0998810a0b61d0a6b5f8c424fa3f39efc3490c/crates/native_blockifier/src/py_block_executor.rs#L260)):*
> ```XML
>     }
> 
>     /// Returns the state diff, a list of contract class hash and the block weights.
> ```





_Suggestion:_
```XML
ff, the stateful-compressed state diff and the block weights.
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2767)* status: all files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 260 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2767#-OFGbZD024MQ3aUh7fnG:-OFHREWq57WbEspfHUnr:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7c0998810a0b61d0a6b5f8c424fa3f39efc3490c/crates/native_blockifier/src/py_block_executor.rs#L260)):*
> ```XML
>     }
> 
>     /// Returns the state diff, a list of contract class hash and the block weights.
> ```

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2767#-:-OFHbuqL3XdrCWpjkyxz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2767)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2767)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
