### PR TITLE
refactor(mempool): add mempool p2p sender client to mempool communication wrapper

### PR DESCRIPTION
**Pull request by AlonLStarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1350)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1350)* status: all files reviewed, 2 unresolved discussions (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`crates/mempool/src/communication.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1350#-O94tGjv15GlsJJKH4f3:-O94tGjv15GlsJJKH4f4:b-vovad6) ([raw file](https://github.com/starkware-libs/sequencer/blob/54fc73eca3a07d4ebfee184a2084597bf4558fda/crates/mempool/src/communication.rs#L52)):*
> ```XML
>                     .continue_propagation(message_metadata)
>                     .await
>                     .unwrap();
> ```

Don't unwrap. Instead, return the relevant error and try to make MempoolError have a variant for this type of error
___
*[`crates/mempool_node/src/servers.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1350#-O94tW4r85DkaaXUJ7RT:-O94tW4r85DkaaXUJ7RU:b-3d7y4v) ([raw file](https://github.com/starkware-libs/sequencer/blob/54fc73eca3a07d4ebfee184a2084597bf4558fda/crates/mempool_node/src/servers.rs#L81)):*
> ```XML
>             components.mempool.expect("Mempool is not initialized."),
>             communication.take_mempool_rx(),
>             Arc::new(EmptyMempoolP2pSenderClient),
> ```

Add an argument to the function for mempool_p2p_sender_client and use it here. put this in the place that calls this function (should be the main). You can write all of this in a TODO instead

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1350)* status: all files reviewed, 3 unresolved discussions (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`crates/mempool/src/communication.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1350#-O94u1cfCMyIf74ZDizO:-O94u1cfCMyIf74ZDizP:b-b7hspf) ([raw file](https://github.com/starkware-libs/sequencer/blob/54fc73eca3a07d4ebfee184a2084597bf4558fda/crates/mempool/src/communication.rs#L62)):*
> ```XML
>     async fn add_tx(&mut self, args_wrapper: AddTransactionArgsWrapper) -> MempoolResult<()> {
>         self.mempool.add_tx(args_wrapper.args.clone())?;
>         self.send_tx_to_p2p(args_wrapper.p2p_message_metadata, args_wrapper.args.tx).await;
> ```

Add TODO to send tx to p2p only if mempool added it

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1350)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @eitanm-starkware and @ShahakShama)

___
*[`crates/mempool/src/communication.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1350#-O94tGjv15GlsJJKH4f3:-O9A5gfU9puvbIxULyfb:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/54fc73eca3a07d4ebfee184a2084597bf4558fda/crates/mempool/src/communication.rs#L52)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Don't unwrap. Instead, return the relevant error and try to make MempoolError have a variant for this type of error
</blockquote></details>

Done.
___
*[`crates/mempool/src/communication.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1350#-O94u1cfCMyIf74ZDizO:-O9A5JjsCedZWvCvkp5Q:b1odr0e) ([raw file](https://github.com/starkware-libs/sequencer/blob/54fc73eca3a07d4ebfee184a2084597bf4558fda/crates/mempool/src/communication.rs#L62)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to send tx to p2p only if mempool added it
</blockquote></details>

From what I understand, add_tx will only return Ok if the transaction is added to the mempool, so it will only be sent if it is added.
Either way, I added a comment.
___
*[`crates/mempool_node/src/servers.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1350#-O94tW4r85DkaaXUJ7RT:-O9A5jWb6JFOhsexqmkd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/54fc73eca3a07d4ebfee184a2084597bf4558fda/crates/mempool_node/src/servers.rs#L81)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add an argument to the function for mempool_p2p_sender_client and use it here. put this in the place that calls this function (should be the main). You can write all of this in a TODO instead
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, 2 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1350)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`crates/mempool/src/communication.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1350#-O94u1cfCMyIf74ZDizO:-O9EeFGW5GC0olkb6id4:bwych3u) ([raw file](https://github.com/starkware-libs/sequencer/blob/54fc73eca3a07d4ebfee184a2084597bf4558fda/crates/mempool/src/communication.rs#L62)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

From what I understand, add_tx will only return Ok if the transaction is added to the mempool, so it will only be sent if it is added.
Either way, I added a comment.
</blockquote></details>

That's not what I understand. From what I see in the code they didn't implement the option to not add a tx yet. If you want you can write a TODO that says you should verify that only txs that were added to the mempool are sent

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1350)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`crates/mempool_node/src/servers.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1350#-O94tW4r85DkaaXUJ7RT:-O9EfFXBB8MBdJ8Lha1T:bxegryg) ([raw file](https://github.com/starkware-libs/sequencer/blob/54fc73eca3a07d4ebfee184a2084597bf4558fda/crates/mempool_node/src/servers.rs#L81)):*
<details><summary><i>Previously, AlonLStarkWare (Alon-Lukatch-Starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is not done

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1350)* status: all files reviewed, 2 unresolved discussions (waiting on @AlonLStarkWare and @eitanm-starkware)

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1350)* status: 3 of 11 files reviewed, 2 unresolved discussions (waiting on @eitanm-starkware and @ShahakShama)

___
*[`crates/mempool/src/communication.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1350#-O94u1cfCMyIf74ZDizO:-O9Ep7dg7TYCPEuk8C8B:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/54fc73eca3a07d4ebfee184a2084597bf4558fda/crates/mempool/src/communication.rs#L62)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

That's not what I understand. From what I see in the code they didn't implement the option to not add a tx yet. If you want you can write a TODO that says you should verify that only txs that were added to the mempool are sent
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/servers.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1350#-O94tW4r85DkaaXUJ7RT:-O9Ep8Wz1E_vD-jItSqR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/54fc73eca3a07d4ebfee184a2084597bf4558fda/crates/mempool_node/src/servers.rs#L81)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is not done
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1350#-:-O9EpFslBcSycBUSJgvP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Pull request merged**
