### PR TITLE
test(starknet_gateway): add sync state reader unit tests

### PR DESCRIPTION
**Pull request by noamsp-starkware**

### CODE REVIEW

**Comment by noamsp-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2903?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2903** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2903?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2903?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2886** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2886?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2903)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @noamsp-starkware and @ShahakShama)

___
*[`crates/starknet_gateway/src/sync_state_reader_test.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2903#-OFMJM2D3jg009aJ6tg2:-OFMJM2D3jg009aJ6tg3:b-71zmch) ([raw file](https://github.com/starkware-libs/sequencer/blob/58b6eb9abb7803e19ceb300268065f185aec3c8f/crates/starknet_gateway/src/sync_state_reader_test.rs#L36)):*
> ```XML
>         GasPricePerToken { price_in_wei: 6_u8.into(), price_in_fri: 7_u8.into() };
>     let l2_gas_price = GasPricePerToken { price_in_wei: 8_u8.into(), price_in_fri: 9_u8.into() };
>     let l1_da_mode = L1DataAvailabilityMode::Blob;
> ```

use get test instance to randomize the enum
___
*[`crates/starknet_gateway/src/sync_state_reader_test.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2903#-OFMJTVh2CmAzkScb_TC:-OFMIb2Y4NHFt6rZ9Ry5:bspu8k3) ([raw file](https://github.com/starkware-libs/sequencer/blob/58b6eb9abb7803e19ceb300268065f185aec3c8f/crates/starknet_gateway/src/sync_state_reader_test.rs#L83)):*
> ```XML
>                 },
>             },
>             use_kzg_da: matches!(l1_da_mode, L1DataAvailabilityMode::Blob),
> ```

fix according to previous pr comment



_Code quote:_
```XML
matches!
```

**Review by noamsp-starkware — COMMENTED** [review]
> Dismissed @eitanm-starkware from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2903)* status: 3 of 7 files reviewed, all discussions resolved (waiting on @eitanm-starkware and @ShahakShama)

___
*[`crates/starknet_gateway/src/sync_state_reader_test.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2903#-OFMJM2D3jg009aJ6tg2:-OFMR9VT8U6xORVu3wBd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/58b6eb9abb7803e19ceb300268065f185aec3c8f/crates/starknet_gateway/src/sync_state_reader_test.rs#L36)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

use get test instance to randomize the enum
</blockquote></details>

Done.
___
*[`crates/starknet_gateway/src/sync_state_reader_test.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2903#-OFMJTVh2CmAzkScb_TC:-OFMRBne1krS4CYCOHpi:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/58b6eb9abb7803e19ceb300268065f185aec3c8f/crates/starknet_gateway/src/sync_state_reader_test.rs#L83)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

fix according to previous pr comment
</blockquote></details>

Done.

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2903#-:-OFMVtj3AXQ1xR14ef_d:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by ShahakShama — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2903)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)

**Pull request merged**
