### PR TITLE
feat: add cache size to batcher config

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#1493** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1493?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
+reviewer:@alonh5 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1493#-:-O9iYfeR0SjIQg6mILaz:b-wqqsco)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @alonh5 and @Yael-Starkware)

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1493)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @ArniStarkware)

___
*[`crates/batcher/src/config.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1493#-O9k9waD3cdA73Y5O8vq:-O9k9waEASMLr1KAo2oQ:bhi0be8) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ffc0fc6b386b6b8e788c8d936e845d83e1872bf/crates/batcher/src/config.rs#L65)):*
> ```XML
>             outstream_content_buffer_size: 100,
>             block_builder_config: BlockBuilderConfig::default(),
>             global_contract_cache_size: 100,
> ```

where is this number taken from



_Code quote:_
```XML
100
```

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1493)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
