### PR TITLE
test(mempool): enable l2 gas resource for mempool-test

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/544)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
This PR adds l2_gas_resource to `add_tx` macro.
It's essential to enable gap_price_threshold in mempool testing.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/544#-:-O4lAOTd3p34zPMsB-nR:bjmnj9o)* status: 0 of 4 files reviewed, all discussions resolved

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/544)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/544#-O4n0I-e7e4VFhAX-gYk:-O4n0I-e7e4VFhAX-gYl:bwgk7y8) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb9df81f43f08e80781b17200d23574d9dc2ad6e/crates/gateway/src/stateful_transaction_validator_test.rs#L71)):*
> ```XML
>     invoke_tx(CairoVersion::Cairo1),
>     Ok(ValidateInfo{
>         tx_hash: TransactionHash(felt!(
> ```

What happened here? Why is this test fragile?
___
*[`crates/mempool/src/mempool_test.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/544#-O4n0DT31nzLkBWldPlu:-O4n0DT31nzLkBWldPlv:b-btx01n) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb9df81f43f08e80781b17200d23574d9dc2ad6e/crates/mempool/src/mempool_test.rs#L173)):*
> ```XML
>     (tip: $tip:expr, tx_hash: $tx_hash:expr, sender_address: $sender_address:expr,
>         tx_nonce: $tx_nonce:expr, account_nonce: $account_nonce:expr) => {{
>             add_tx_input!(tip: $tip, tx_hash: $tx_hash, sender_address: $sender_address, tx_nonce: $tx_nonce, account_nonce: $account_nonce, resource_bounds: executable_resource_bounds_mapping().into())
> ```

Unclear from the name what it returns.



_Code quote:_
```XML
executable_resource_bounds_mapping
```
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/544#-O4n-zRq62yq5kUkRttz:-O4n-zRq62yq5kUkRtu-:b-bxq2jw) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb9df81f43f08e80781b17200d23574d9dc2ad6e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L28)):*
> ```XML
>     PaymasterData,
>     ResourceBounds,
>     ResourceBoundsMapping as ExecutableResourceBoundsMapping,
> ```

Why this alias?



_Code quote:_
```XML
ResourceBoundsMapping as ExecutableResourceBoundsMapping,
```
___
*[`crates/starknet_api/src/executable_transaction.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/544#-O4n02Iz7C6qzXsJSFH3:-O4n02Iz7C6qzXsJSFH4:b-a3mms7) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb9df81f43f08e80781b17200d23574d9dc2ad6e/crates/starknet_api/src/executable_transaction.rs#L117)):*
> ```XML
>                     tip: *rpc_tx.tip(),
>                     nonce: *rpc_tx.nonce(),
>                     resource_bounds: rpc_tx.resource_bounds().clone().into(),
> ```

Isn't it the same type?
Why `clone`ing and not `*` like for tip and nonce?
(Same Q for `gateway_test.rs`)



_Code quote:_
```XML
.into()
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/544)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/544#-O4n0I-e7e4VFhAX-gYk:-O4nLT4PAJOS8RyqbyGp:bfy7kbu) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb9df81f43f08e80781b17200d23574d9dc2ad6e/crates/gateway/src/stateful_transaction_validator_test.rs#L71)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What happened here? Why is this test fragile?
</blockquote></details>

resource bounds was changed -> expected tx hash changed.
___
*[`crates/mempool/src/mempool_test.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/544#-O4n0DT31nzLkBWldPlu:-O4nLzEJAKdRkXAbIGo0:b-mgs1xx) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb9df81f43f08e80781b17200d23574d9dc2ad6e/crates/mempool/src/mempool_test.rs#L173)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Unclear from the name what it returns.
</blockquote></details>

Changed to `test_resource_bounds_mapping`, as it's a resource mapping for testing.
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/544#-O4n-zRq62yq5kUkRttz:-O4nMVOi8KjfPrdRn4Av:b-91rgn9) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb9df81f43f08e80781b17200d23574d9dc2ad6e/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L28)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why this alias?
</blockquote></details>

Because there is another `ResourceBoundsMapping`, the rpc mapping.
___
*[`crates/starknet_api/src/executable_transaction.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/544#-O4n02Iz7C6qzXsJSFH3:-O4nMzX84bOlBh2z73sD:b-w99uan) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb9df81f43f08e80781b17200d23574d9dc2ad6e/crates/starknet_api/src/executable_transaction.rs#L117)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Isn't it the same type?
Why `clone`ing and not `*` like for tip and nonce?
(Same Q for `gateway_test.rs`)
</blockquote></details>

Resource bounds doesn't imply Copy, so it cannot deref.
The same answer for `gateway_test .rs`code.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/544)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/544#-O4n0I-e7e4VFhAX-gYk:-O4nzRImBNwTsxSkt5hy:bsuntwe) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb9df81f43f08e80781b17200d23574d9dc2ad6e/crates/gateway/src/stateful_transaction_validator_test.rs#L71)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

resource bounds was changed -> expected tx hash changed.
</blockquote></details>

This framework should be refactored.
___
*[`crates/mempool/src/mempool_test.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/544#-O4n0DT31nzLkBWldPlu:-O4nz7-N5p1G5vTFi5wS:bc91u5o) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb9df81f43f08e80781b17200d23574d9dc2ad6e/crates/mempool/src/mempool_test.rs#L173)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Changed to `test_resource_bounds_mapping`, as it's a resource mapping for testing.
</blockquote></details>

But what's its value? Default?

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/544#-:-O4o0QqP0HkUnmdF168U:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/544)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @giladchase)

**Pull request merged**
