### PR TITLE
feat(blockifier): add l2_gas to the receipt

### PR DESCRIPTION
**Pull request by TzahiTaub**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2031)* status: all files reviewed, 14 unresolved discussions (waiting on @TzahiTaub and @Yoni-Starkware)

___
*[`crates/starknet_api/src/execution_resources.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfQ2s42d-5dIXiW0NH:-OBfQ2s42d-5dIXiW0NI:bvn5whp) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/starknet_api/src/execution_resources.rs#L15)):*
> ```XML
> )]
> #[derive(
>     derive_more::Add,
> ```

no, be explicit: checked_add or saturating_add.
apparently when building with `--release` mode, integer overflows are silently wrapped by default - not what we want



_Code quote:_
```XML
derive_more::Add,
```
___
*[`crates/starknet_api/src/execution_resources.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfQ6XY5Ms902VpHr03:-OBfQ6XY5Ms902VpHr04:b-7ropln) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/starknet_api/src/execution_resources.rs#L73)):*
> ```XML
> 
> #[cfg_attr(any(test, feature = "testing"), derive(derive_more::Sum, derive_more::AddAssign))]
> #[derive(derive_more::Add, Clone, Copy, Debug, Default, Eq, PartialEq, Deserialize, Serialize)]
> ```

ditto



_Code quote:_
```XML
derive_more::Add,
```
___
*[`crates/blockifier/src/fee/resources.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfQVU54tePFdimA1BR:-OBfQVU54tePFdimA1BS:b5umgzc) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/fee/resources.rs#L75)):*
> ```XML
>             self.n_reverted_steps,
>             computation_mode,
>         ) + GasVector::from_l2_gas(self.l2_gas + self.reverted_l2_gas)
> ```

checked or saturating (see below)



_Code quote:_
```XML
 + GasVector
```
___
*[`crates/blockifier/src/fee/receipt.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfNOHD58IfnfjSO-s1:-OBfNOHD58IfnfjSO-s2:b9joihp) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/fee/receipt.rs#L34)):*
> ```XML
>     execution_summary_without_fee_transfer: ExecutionSummary,
>     execution_resources: &'a ExecutionResources,
>     l2_gas: GasAmount,
> ```

see above: these should be combined in a struct IMO



_Code quote:_
```XML
    execution_resources: &'a ExecutionResources,
    l2_gas: GasAmount,
```
___
*[`crates/blockifier/src/fee/receipt.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfNqmGC1IDS5Pd31yZ:-OBfNqmGC1IDS5Pd31y_:b-rxp4l7) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/fee/receipt.rs#L93)):*
> ```XML
>                 n_reverted_steps: reverted_steps,
>                 l2_gas,
>                 reverted_l2_gas: GasAmount(0), // TODO(tzahi): compute value.
> ```

from what? how?



_Code quote:_
```XML
/ TODO(tzahi): compute value.
```
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 160 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfQL9b3ESv89vbR16X:-OBfQL9b3ESv89vbR16Y:b-hid4em) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/transaction/transaction_execution.rs#L160)):*
> ```XML
>             Some(call_info) => call_info.charged_resources.gas_for_fee,
>             None => GasAmount(0),
>         };
> ```

code dup (see above)



_Code quote:_
```XML
        let l2_gas = match &execute_call_info {
            Some(call_info) => call_info.charged_resources.gas_for_fee,
            None => GasAmount(0),
        };
```
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 366 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfNGMPACWX9FbBLELd:-OBfNGMPACWX9FbBLELe:b2e5rz5) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/fee/gas_usage_test.rs#L366)):*
> ```XML
>     let n_reverted_steps = 15;
>     let l2_gas = GasAmount(0);
>     let reverted_l2_gas = GasAmount(0);
> ```

why zero values...? not supported yet? how will you remember to set these to nonzero values?



_Code quote:_
```XML
    let l2_gas = GasAmount(0);
    let reverted_l2_gas = GasAmount(0);
```
___
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfN26u3zbLrvrZJv9A:-OBfN26u3zbLrvrZJv9B:b-1aokm0) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/blockifier/stateful_validator.rs#L131)):*
> ```XML
>             Some(call_info) => call_info.charged_resources.gas_for_fee,
>             None => GasAmount(0),
>         };
> ```

should be equivalent, non-blocking



_Suggestion:_
```XML
        let gas_for_fee = validate_call_info
            .map(|call_info| call_info.charged_resources.gas_for_fee)
            .unwrap_or(GasAmount(0));
```
___
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfMuat6VPkmzgt5dts:-OBfMuat6VPkmzgt5dtt:b-u7sgz8) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/blockifier/stateful_validator.rs#L143)):*
> ```XML
>                 .get_actual_state_changes()?,
>             &execution_resources,
>             gas_for_fee,
> ```

didn't you combine these into a single "ChargedResources" struct?



_Code quote:_
```XML
            &execution_resources,
            gas_for_fee,
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 589 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfPN_78wQZP8G-DUGu:-OBfPN_78wQZP8G-DUGv:b-8aiiz8) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/transaction/account_transaction.rs#L589)):*
> ```XML
>             validate_call_info = self.handle_validate_tx(
>                 state,
>                 &mut resources,
> ```

why don't you mutate a gas amount, to align behavior to the `resources`?
strange, the different approaches to the same concept (non-blocking)



_Code quote:_
```XML
&mut resources,
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 605 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfOj1eCZjTxpMiXisG:-OBfOj1f9GPUV_y1cJ7_:bql1hk3) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/transaction/account_transaction.rs#L605)):*
> ```XML
>             Some(call_info) => call_info.charged_resources.gas_for_fee,
>             None => GasAmount(0),
>         };
> ```

1. see above for style (`.map(..).unwrap_or(..)`), non-blocking
2. checked or saturating `Add` (see below)



_Code quote:_
```XML
        let gas_for_fee = match &validate_call_info {
            Some(call_info) => call_info.charged_resources.gas_for_fee,
            None => GasAmount(0),
        } + match &execute_call_info {
            Some(call_info) => call_info.charged_resources.gas_for_fee,
            None => GasAmount(0),
        };
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 605 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfP0fz3ETdgK3VD4Ed:-OBfP0fz3ETdgK3VD4Ee:b-sj9tt5) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/transaction/account_transaction.rs#L605)):*
> ```XML
>             Some(call_info) => call_info.charged_resources.gas_for_fee,
>             None => GasAmount(0),
>         };
> ```

some logic is duplicated... I suggest you implement a `fn gas_for_fee_from_call_infos(validate: Option<&CallInfo>, execute: Option<&CallInfo>) -> GasAmount` which does this, + use it above in the stateful validator (with `None` as the execute callinfo)



_Code quote:_
```XML
        let gas_for_fee = match &validate_call_info {
            Some(call_info) => call_info.charged_resources.gas_for_fee,
            None => GasAmount(0),
        } + match &execute_call_info {
            Some(call_info) => call_info.charged_resources.gas_for_fee,
            None => GasAmount(0),
        };
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 674 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfPGkr6cDF8BNlzHpt:-OBfPGkr6cDF8BNlzHpu:b-jri67v) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/transaction/account_transaction.rs#L674)):*
> ```XML
>             Some(call_info) => call_info.charged_resources.gas_for_fee,
>             None => GasAmount(0),
>         };
> ```

duplicate logic (see above)



_Code quote:_
```XML
        let validate_gas_for_fee = match &validate_call_info {
            Some(call_info) => call_info.charged_resources.gas_for_fee,
            None => GasAmount(0),
        };
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 687 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfPeqS8bUDa8VqkqvY:-OBfPeqS8bUDa8VqkqvZ:b-6yl07u) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/transaction/account_transaction.rs#L687)):*
> ```XML
>             validate_gas_for_fee,
>             CallInfo::summarize_many(validate_call_info.iter()),
>             execution_steps_consumed,
> ```

3 of the 4 fields here - along with reverted L2 gas - already have their own struct, right? can you use it?



_Code quote:_
```XML
            &resources,
            validate_gas_for_fee,
            CallInfo::summarize_many(validate_call_info.iter()),
            execution_steps_consumed,
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 706 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfPpApDiuBrT2h1DjP:-OBfPpApDiuBrT2h1DjQ:b-lpw8gi) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/transaction/account_transaction.rs#L706)):*
> ```XML
>                             Some(call_info) => call_info.charged_resources.gas_for_fee,
>                             None => GasAmount(0),
>                         },
> ```

duplicate logic (see above) - although the first amount is already computed, the second amount computation is duped



_Code quote:_
```XML
                    validate_gas_for_fee
                        + match &execute_call_info {
                            Some(call_info) => call_info.charged_resources.gas_for_fee,
                            None => GasAmount(0),
                        },
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 718 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfQDu1BDCWFTddBSav:-OBfQDu1BDCWFTddBSaw:b-u2j5o0) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/transaction/account_transaction.rs#L718)):*
> ```XML
>                     &tx_receipt,
>                     charge_fee,
>                 )?;
> ```

what does the post-execution check do with the L2 gas for fee? I would expect a bounds check



_Code quote:_
```XML
                let post_execution_report = PostExecutionReport::new(
                    &mut execution_state,
                    &tx_context,
                    &tx_receipt,
                    charge_fee,
                )?;
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2031)* status: all files reviewed, 14 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/fee/receipt.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfNOHD58IfnfjSO-s1:-OBfswtS-xj9YPjFcj-5:bcinpll) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/fee/receipt.rs#L34)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above: these should be combined in a struct IMO
</blockquote></details>

Please rename (`sierra_gas` or something else).
L2 gas is too general (and part of the receipt anyway)

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2031)* status: 0 of 8 files reviewed, 14 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfMuat6VPkmzgt5dts:-OBh3Tv1Dj7yeYjznY4i:b-mbtjvk) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/blockifier/stateful_validator.rs#L143)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

didn't you combine these into a single "ChargedResources" struct?
</blockquote></details>

I have it for calls, not for a tx. Tried my best, the preparation of the input with all of the Optional structs is a bit annoying.
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 366 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfNGMPACWX9FbBLELd:-OBh9OvT3dG5a0BOo0nR:bj840m3) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/fee/gas_usage_test.rs#L366)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why zero values...? not supported yet? how will you remember to set these to nonzero values?
</blockquote></details>

Actually not, didn't see what this test is doing. Done.
___
*[`crates/blockifier/src/fee/receipt.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfNOHD58IfnfjSO-s1:-OBhA0qSBdWWWlybcG_B:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/fee/receipt.rs#L34)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Please rename (`sierra_gas` or something else).
L2 gas is too general (and part of the receipt anyway)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/receipt.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfNqmGC1IDS5Pd31yZ:-OBhA7zM9_3SN74YGq4h:b-4x6z6g) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/fee/receipt.rs#L93)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

from what? how?
</blockquote></details>

In a few PRs, the revert mechanism will send the reverted gas together with the error.
___
*[`crates/blockifier/src/fee/resources.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfQVU54tePFdimA1BR:-OBhBf9d1Xbmyay4vs0Z:bwmlszw) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/fee/resources.rs#L75)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

checked or saturating (see below)
</blockquote></details>

Done. I don't see we have a similar check in the get_vm_resources_cost computation.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 589 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfPN_78wQZP8G-DUGu:-OBhDyjHBC8vRSFYWesr:byp1ydb) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/transaction/account_transaction.rs#L589)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why don't you mutate a gas amount, to align behavior to the `resources`?
strange, the different approaches to the same concept (non-blocking)
</blockquote></details>

I agree this is weird, but it goes very deep into the current implementation, we can think of refactoring this. But I think the difference is due to the fact we ignore the `remaining_gas` for some of the calls. `resources` should be the sum of `execution_resources` in the calls "so far", but this is not the case for `remaining_gas` and `gas_for_fee` which is sort of the equivalent. 
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 605 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfOj1eCZjTxpMiXisG:-OBu2lHk7uQ7BU1UoxDz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/transaction/account_transaction.rs#L605)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. see above for style (`.map(..).unwrap_or(..)`), non-blocking
2. checked or saturating `Add` (see below)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 605 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfP0fz3ETdgK3VD4Ed:-OBu7rCm5EQasK80qMnC:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/transaction/account_transaction.rs#L605)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

some logic is duplicated... I suggest you implement a `fn gas_for_fee_from_call_infos(validate: Option<&CallInfo>, execute: Option<&CallInfo>) -> GasAmount` which does this, + use it above in the stateful validator (with `None` as the execute callinfo)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 674 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfPGkr6cDF8BNlzHpt:-OBu9EMd1QfCcgmI1jTI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/transaction/account_transaction.rs#L674)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

duplicate logic (see above)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 687 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfPeqS8bUDa8VqkqvY:-OBuBliH1FcJgo4wbJWZ:b-b4mmku) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/transaction/account_transaction.rs#L687)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

3 of the 4 fields here - along with reverted L2 gas - already have their own struct, right? can you use it?
</blockquote></details>

I can, but it will be a bit of misuse as `ChargedResources` is currently a field of `CallInfo` representing the resources of a call. The 
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 706 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfPpApDiuBrT2h1DjP:-OBugVLBAYq495Xc1HYW:b-dh6q2i) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/transaction/account_transaction.rs#L706)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

duplicate logic (see above) - although the first amount is already computed, the second amount computation is duped
</blockquote></details>

This OK?
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 718 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfQDu1BDCWFTddBSav:-OBuh0pu5V9yOpHKDste:bvrgjg4) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/transaction/account_transaction.rs#L718)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what does the post-execution check do with the L2 gas for fee? I would expect a bounds check
</blockquote></details>

It does check it.
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 160 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfQL9b3ESv89vbR16X:-OBuhKZm5VrcVPCLFCvR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/transaction/transaction_execution.rs#L160)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

code dup (see above)
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/execution_resources.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfQ2s42d-5dIXiW0NH:-OBw_dksE4c_mR7NpueN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/starknet_api/src/execution_resources.rs#L15)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no, be explicit: checked_add or saturating_add.
apparently when building with `--release` mode, integer overflows are silently wrapped by default - not what we want
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/execution_resources.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfQ6XY5Ms902VpHr03:-OBw_dRz9bdWoC-OR9bB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/starknet_api/src/execution_resources.rs#L73)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-:-OByYMwJ4aCaPWwHWy9K:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/fee/resources.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OBfQVU54tePFdimA1BR:-OByX_kZ1qi7xdw02Oi_:b7g44fe) ([raw file](https://github.com/starkware-libs/sequencer/blob/8c9cf2f8e42df2235877c82aca03f87bfd0e6d0e/crates/blockifier/src/fee/resources.rs#L75)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Done. I don't see we have a similar check in the get_vm_resources_cost computation.
</blockquote></details>

yes, step amount is still a `usize`... but gas counting will be with us forever so better do the right thing for gas at least
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 663 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OByXxFr6EgtDxgV49do:-OByXxFr6EgtDxgV49dp:bmuifb9) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4b37e0c357ef20cb689196a8ec9b587859123ff/crates/blockifier/src/transaction/account_transaction.rs#L663)):*
> ```XML
>             remaining_gas,
>         );
>         let gas_for_fee = gas_for_fee_from_call_infos(&validate_call_info, &None);
> ```

if you don't want to pass `None`s everywhere you can change the signature of this function to accept a `&[&Option<CallInfo>]`. non-blocking



_Code quote:_
```XML
gas_for_fee_from_call_infos(&validate_call_info, &None);
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 135 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OByWtrq4cTadKi7UFzx:-OByWtrq4cTadKi7UFzy:bxp78hp) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4b37e0c357ef20cb689196a8ec9b587859123ff/crates/blockifier/src/execution/call_info.rs#L135)):*
> ```XML
>     })
> }
> /// Represents the full effects of executing an entry point, including the inner calls it invoked.
> ```

newline (non-blocking)



_Suggestion:_
```XML
}

/// Represents the full effects of executing an entry point, including the inner calls it invoked.
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2031)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 663 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2031#-OByXxFr6EgtDxgV49do:-OByZs8u6tc2GuRrLV2y:b-65c8h2) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4b37e0c357ef20cb689196a8ec9b587859123ff/crates/blockifier/src/transaction/account_transaction.rs#L663)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you don't want to pass `None`s everywhere you can change the signature of this function to accept a `&[&Option<CallInfo>]`. non-blocking
</blockquote></details>

I think I prefer the explicit params.

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2031)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2031)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
