### PR TITLE
chore(cairo_native): add git submodule update to dependencies

### PR DESCRIPTION
**Pull request by avi-starkware**

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2012)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2012)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2012#-:-OBdrr4Z43JLsaRaF0eu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Comment by avi-starkware** [comment]
This change does not go through the CI, and does not solve the problem.
A different solution is found in #2166.

**Pull request closed without merging**
