### PR TITLE
refactor(blockifier_reexecution): add more expected string error

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
* **#1902** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1902?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1902)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1902#-OBKbK1_0Czf-KqzS7Su:-OBKbK1_0Czf-KqzS7Sv:b-uf2hg8) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3744ead64ba881e7f50a43f3f1c8515bd222d9c/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L53)):*
> ```XML
> pub const DEFAULT_RETRY_COUNT: usize = 3;
> pub const DEFAULT_RETRY_WAIT_TIME: u64 = 1000;
> pub const DEFAULT_EXPECTED_ERROR_STRINGS: [&str; 3] = ["Connection error", "RPCError", "429"];
> ```

this is too general - this could be a substring of some hash in a response.



_Code quote:_
```XML
"429"
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1902)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1902#-OBKbK1_0Czf-KqzS7Su:-OBL75fn8C4yfm9706vH:b-lquwd2) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3744ead64ba881e7f50a43f3f1c8515bd222d9c/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L53)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant: make it `ERROR 429` or whatever format you expect; just add more characters

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1902#-:-OBL9_DM4eeWVLfqcEle:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1902)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1902#-OBKbK1_0Czf-KqzS7Su:-OBLB2ZZ1Xja_JcsS5IW:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/d3744ead64ba881e7f50a43f3f1c8515bd222d9c/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L53)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I meant: make it `ERROR 429` or whatever format you expect; just add more characters
</blockquote></details>

Done

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1902)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
