### PR TITLE
chore(committer): change leaf to be created with associated types

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/469)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/469)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4K2jBi0slf4obAimYJ:-O4K2jBi0slf4obAimYK:b-9wqgql) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4a430d7af66114cb1d2678234c648cabf00132b/crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs#L1)):*
> ```XML
> use std::sync::Arc;
> ```

note that the new `Leaf::create()` isn't actually used yet - leaves are retrieved from leaf_modification dicts like they had before.



_Code quote:_
```XML
use std::sync::Arc;
```

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/469#-:-O4K4JP95RQU1Pu0F3Ll:b-hz3kb8)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/469)* status: all files reviewed, 7 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4K2jBi0slf4obAimYJ:-O4KCfFfA_6gYknH6GaA:b7qiz6i) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4a430d7af66114cb1d2678234c648cabf00132b/crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs#L1)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

note that the new `Leaf::create()` isn't actually used yet - leaves are retrieved from leaf_modification dicts like they had before.
</blockquote></details>

where will the "from leaf modifications" logic reside after you're done? I see it was removed from the trait and inlined when used ATM
___
*[`crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4KBZGp2BCKaCaTmsrG:-O4KBZGp2BCKaCaTmsrH:b-rqptci) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f3831f452e0082c2cdc64bebfbc615b38fc4074/crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs#L27)):*
> ```XML
>         self.0 == Felt::ZERO
>     }
>     async fn create(input: Self::I) -> LeafResult<(Self, Option<Self::O>)> {
> ```

restore the newline



_Suggestion:_
```XML
    }
    
    async fn create(input: Self::I) -> LeafResult<(Self, Option<Self::O>)> {
```
___
*[`crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4KBuZI6VY-32EPjvBx:-O4KBuZI6VY-32EPjvBy:b-flnxq3) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f3831f452e0082c2cdc64bebfbc615b38fc4074/crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs#L76)):*
> ```XML
>                 Err(LeafError::LeafComputationError(storage_error.to_string(), leaf_index))
>             }
>         }
> ```

use `map_err` instead of `match`ing the result?



_Code quote:_
```XML
        match FilledTreeImpl::<StarknetStorageValue>::create_with_existing_leaves::<
            TreeHashFunctionImpl,
        >(updated_skeleton, storage_modifications)
        .await
        {
            Ok(storage_trie) => Ok((
                Self { nonce, storage_root_hash: storage_trie.get_root_hash(), class_hash },
                Some(storage_trie),
            )),
            Err(storage_error) => {
                Err(LeafError::LeafComputationError(storage_error.to_string(), leaf_index))
            }
        }
```
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs` line 180 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4KC5m84v_bT0wv7wb_:-O4KC5m84v_bT0wv7wba:b-2weiq0) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f3831f452e0082c2cdc64bebfbc615b38fc4074/crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs#L180)):*
> ```XML
>                     .get(&index)
>                     .ok_or(LeafError::MissingLeafModificationData(index))
>                     .cloned()?;
> ```

temporary code, right?



_Suggestion:_
```XML
                // TODO(Amos): use `L::create`.
                let leaf_data = leaf_modifications
                    .get(&index)
                    .ok_or(LeafError::MissingLeafModificationData(index))
                    .cloned()?;
```
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/node_data/errors.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4KCJgAAoH7clyKMZRS:-O4KCJgAAoH7clyKMZRT:bxd5cyf) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f3831f452e0082c2cdc64bebfbc615b38fc4074/crates/starknet_patricia/src/patricia_merkle_tree/node_data/errors.rs#L25)):*
> ```XML
> pub enum LeafError {
>     #[error("While computing the leaf at index {0:?} got the following error: {1:?}")]
>     LeafComputationError(String, NodeIndex),
> ```

more structured data please



_Suggestion:_
```XML
{ error: String, index: NodeIndex }
```
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4KCQoV2QsWjyVxtEf-:-O4KCQoV2QsWjyVxtEf0:b-3dz3nl) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f3831f452e0082c2cdc64bebfbc615b38fc4074/crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs#L13)):*
> ```XML
>     // TODO(Amos, 1/1/2025): Add default values when it is stable.
>     type I: Send + Sync + 'static;
>     type O: Send + Debug + 'static;
> ```

informative names



_Suggestion:_
```XML
    type Input: Send + Sync + 'static;
    type Output: Send + Debug + 'static;
```
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4KCXRIDc0rBb-pPXmF:-O4KCXRIDc0rBb-pPXmG:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f3831f452e0082c2cdc64bebfbc615b38fc4074/crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs#L18)):*
> ```XML
>     fn is_empty(&self) -> bool;
> 
>     /// Creates a leaf and allows returning additional output.
> ```





_Suggestion:_
```XML
/// Creates a leaf (with some additional input) and allows returning additional output.
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/469)* status: all files reviewed, 8 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4KDKRQDOB9n4BO41k3:-O4KDKRQDOB9n4BO41k4:bktmtzn) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f3831f452e0082c2cdc64bebfbc615b38fc4074/crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs#L27)):*
> ```XML
>         self.0 == Felt::ZERO
>     }
>     async fn create(input: Self::I) -> LeafResult<(Self, Option<Self::O>)> {
> ```

I would drop the `Option<>` here.
Implementing leaves can decide they want to ignore the output `O = ()`), but leaves that do NOT want it ignored, should not have to `unwrap`



_Suggestion:_
```XML
LeafResult<(Self, Self::O)> {
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/469)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4K2jBi0slf4obAimYJ:-O4KbEum-e7z7Q_HfyEd:bvw5n14) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4a430d7af66114cb1d2678234c648cabf00132b/crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs#L1)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where will the "from leaf modifications" logic reside after you're done? I see it was removed from the trait and inlined when used ATM
</blockquote></details>

I now returned it to the leaf trait.
___
*[`crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4KBZGp2BCKaCaTmsrG:-O4Kbjpb0mQbRDzzaGDW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f3831f452e0082c2cdc64bebfbc615b38fc4074/crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs#L27)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

restore the newline
</blockquote></details>

Done.
___
*[`crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4KDKRQDOB9n4BO41k3:-O4Kbpie1GQsfjacYGI-:b-wvl5fl) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f3831f452e0082c2cdc64bebfbc615b38fc4074/crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs#L27)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I would drop the `Option<>` here.
Implementing leaves can decide they want to ignore the output `O = ()`), but leaves that do NOT want it ignored, should not have to `unwrap`
</blockquote></details>

IMO `Option` here makes sense - `None` lets leaves reflect they don't have any additional output. but I don't feel strongly about this
___
*[`crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4KBuZI6VY-32EPjvBx:-O4KehXf5CudJ_MIKhpm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f3831f452e0082c2cdc64bebfbc615b38fc4074/crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs#L76)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use `map_err` instead of `match`ing the result?
</blockquote></details>

Done.
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs` line 180 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4KC5m84v_bT0wv7wb_:-O4KexwE2TVokVuvhuSn:b-w3g9rb) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f3831f452e0082c2cdc64bebfbc615b38fc4074/crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs#L180)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

temporary code, right?
</blockquote></details>

how about this?
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/node_data/errors.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4KCJgAAoH7clyKMZRS:-O4L4-n44LMTEiV5NMC0:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f3831f452e0082c2cdc64bebfbc615b38fc4074/crates/starknet_patricia/src/patricia_merkle_tree/node_data/errors.rs#L25)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

more structured data please
</blockquote></details>

Done.
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4KCQoV2QsWjyVxtEf-:-O4L4ADj1YiR9fMXVOwp:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f3831f452e0082c2cdc64bebfbc615b38fc4074/crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs#L13)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

informative names
</blockquote></details>

Done.
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4KCXRIDc0rBb-pPXmF:-O4L4wnl3gHgAt6to9ZX:bufzjtv) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f3831f452e0082c2cdc64bebfbc615b38fc4074/crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs#L18)):*
> ```XML
>     fn is_empty(&self) -> bool;
> 
>     /// Creates a leaf and allows returning additional output.
> ```

It's not really additional output though - there is one parameter

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/469)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4KDKRQDOB9n4BO41k3:-O4L95H--XDTAnKhEhHO:b-t3hfsq) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f3831f452e0082c2cdc64bebfbc615b38fc4074/crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs#L27)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

IMO `Option` here makes sense - `None` lets leaves reflect they don't have any additional output. but I don't feel strongly about this
</blockquote></details>

I prefer they indicate it explicitly in the *definition* of `Output`. By defining `Output = ()` the leaf indicates it returns no output, and you can always return the defined output `()`.
What is the difference between `Some(())` and `None`?
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4L9XO5AByJiDzNIp0O:-O4L9XO5AByJiDzNIp0P:b-5gv6r2) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7027f3bf850541839255531e1067b47f4aaaf14/crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs#L13)):*
> ```XML
> pub trait Leaf: Clone + Sync + Send + DBObject + Deserializable + Default + Debug + Eq {
>     // TODO(Amos, 1/1/2025): When default values for associated types are stable - use them, and
>     // add a default implementation for `create`.
> ```

is there an issue you can link to here?



_Code quote:_
```XML
    // TODO(Amos, 1/1/2025): When default values for associated types are stable - use them, and
    // add a default implementation for `create`.
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/469)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4KDKRQDOB9n4BO41k3:-O4LBWI-4H9Q8N-mU3-X:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0f3831f452e0082c2cdc64bebfbc615b38fc4074/crates/starknet_committer/src/patricia_merkle_tree/leaf/leaf_impl.rs#L27)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I prefer they indicate it explicitly in the *definition* of `Output`. By defining `Output = ()` the leaf indicates it returns no output, and you can always return the defined output `()`.
What is the difference between `Some(())` and `None`?
</blockquote></details>

Done.
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4L9XO5AByJiDzNIp0O:-O4LC-402lmE1A8VZEA9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7027f3bf850541839255531e1067b47f4aaaf14/crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs#L13)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is there an issue you can link to here?
</blockquote></details>

Done.
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs` line 31 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4LCkawCjFgrS9C8ta2:-O4LCkawCjFgrS9C8ta3:b-8ziu6m) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d4094ce17288fe412746348a5a282420da91334/crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs#L31)):*
> ```XML
>         index: &NodeIndex,
>         leaf_modifications: Arc<LeafModifications<Self>>,
>     ) -> LeafResult<Self> {
> ```

Note that I'll remove the `Arc` in one of the next PRs



_Code quote:_
```XML
leaf_modifications: Arc<LeafModifications<Self>>,
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/469)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs` line 14 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4aP99iCTiCZEZQeYN4:-O4aP99iCTiCZEZQeYN5:b-cvz0nz) ([raw file](https://github.com/starkware-libs/sequencer/blob/06e6c008445185c03f1a4b93d4b943c5901cc650/crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs#L14)):*
> ```XML
>     // TODO(Amos, 1/1/2025): When default values for associated types are stable - use them, and
>     // add a default implementation for `create`.
>     // https://github.com/rust-lang/rust/issues/29661
> ```

strange... I think you should be failing the docs test
can you run it locally before and after this change?



_Suggestion:_
```XML
// [Issue](https://github.com/rust-lang/rust/issues/29661).
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/469)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs` line 14 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4aP99iCTiCZEZQeYN4:-O4dXpXK9IrhiXlLdPwQ:b-nb3y3p) ([raw file](https://github.com/starkware-libs/sequencer/blob/06e6c008445185c03f1a4b93d4b943c5901cc650/crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs#L14)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

strange... I think you should be failing the docs test
can you run it locally before and after this change?
</blockquote></details>

Done.
doc test passes with and without this

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/469)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs` line 178 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4eggOsE0wVW7YRYfBf:-O4eggOsE0wVW7YRYfBg:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/2ee2bc42ff6a615c02b4b5fab4c2939f60d95bb6/crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs#L178)):*
> ```XML
>                 // TODO(Amos): use `L::create` when no leaf modifications are provided.
>                 let leaf_data = L::from_modifications(&index, Arc::clone(&leaf_modifications))
>                     .map_err(|e| FilledTreeError::Leaf { leaf_error: e, leaf_index: index })?;
> ```





_Suggestion:_
```XML
error| FilledTreeError::Leaf { leaf_error: error
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/469)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs` line 178 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/469#-O4eggOsE0wVW7YRYfBf:-O4eii6x6GAjx5Kyid6K:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2ee2bc42ff6a615c02b4b5fab4c2939f60d95bb6/crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs#L178)):*
> ```XML
>                 // TODO(Amos): use `L::create` when no leaf modifications are provided.
>                 let leaf_data = L::from_modifications(&index, Arc::clone(&leaf_modifications))
>                     .map_err(|e| FilledTreeError::Leaf { leaf_error: e, leaf_index: index })?;
> ```

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/469#-:-O4ima95B-cMEkxI6lsz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
