### PR TITLE
chore(papyrus_execution):  get versioned contract class

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
Who should I add as a reviewer responsible for `papyrus_execution`?

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2680?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2680** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2680?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2680?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2679** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2679?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2678** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2678?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2668** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2668?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2641](https://github.com/starkware-libs/sequencer/pull/2641) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2641?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2614** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2614?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2493** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2493?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2438** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2438?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2420** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2420?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2421](https://github.com/starkware-libs/sequencer/pull/2421) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2421?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2467** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2467?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2466** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2466?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2680)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/papyrus_execution/src/execution_utils.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2680#-OE9yuQg1P107P7KGaMh:-OE9yuQh-BWxp4xVQvxJ:bnv5cwe) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a5ffcc74d34443e2f008f9d4ba2d170f39f708d/crates/papyrus_execution/src/execution_utils.rs#L75)):*
> ```XML
>             );
>             let sierra_version = SierraVersion::extract_from_program(&sierra.sierra_program)
>                 .map_err(|_| ExecutionUtilsError::CasmTableNotSynced)?;
> ```

what's this error?



_Code quote:_
```XML
ExecutionUtilsError::CasmTableNotSynced
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2680)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/papyrus_execution/src/execution_utils.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2680#-OE9yuQg1P107P7KGaMh:-OEJey81-bM5UN0W4hlv:b-fxe7ud) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a5ffcc74d34443e2f008f9d4ba2d170f39f708d/crates/papyrus_execution/src/execution_utils.rs#L75)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what's this error?
</blockquote></details>

I added a new one

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2680)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @AvivYossef-starkware, and @ShahakShama)

___
*[`crates/papyrus_execution/src/execution_utils.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2680#-OEPCkslBAVn4nuRsk9M:-OEPCkslBAVn4nuRsk9N:bdgm7t4) ([raw file](https://github.com/starkware-libs/sequencer/blob/26d288a2ef4c73a3d021c30b6709df7a517e8d32/crates/papyrus_execution/src/execution_utils.rs#L48)):*
> ```XML
>     CasmTableNotSynced,
>     #[error(transparent)]
>     SierraValidationError(#[from] starknet_api::StarknetApiError),
> ```

this should be explicit conversion IMO, not done implicitly via `?` operator. we don't know that all starknet-api errors are actually sierra validation errors, even if this is currently the case



_Suggestion:_
```XML
    #[error(transparent)]
    SierraValidationError(starknet_api::StarknetApiError),
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2680)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @dorimedini-starkware, and @ShahakShama)

___
*[`crates/papyrus_execution/src/execution_utils.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2680#-OEPCkslBAVn4nuRsk9M:-OEPDt1wEkTjBDpkpMZQ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/26d288a2ef4c73a3d021c30b6709df7a517e8d32/crates/papyrus_execution/src/execution_utils.rs#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this should be explicit conversion IMO, not done implicitly via `?` operator. we don't know that all starknet-api errors are actually sierra validation errors, even if this is currently the case
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2680)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @amosStarkware and @ShahakShama)

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2680)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/papyrus_execution/src/state_reader.rs` line 83 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2680#-OESlxRi37etrOmTGym2:-OESlxRj899LF0n7A2Ga:bdepunt) ([raw file](https://github.com/starkware-libs/sequencer/blob/dbcfb503725fbc46e5d3d0853fcd6f319095a425/crates/papyrus_execution/src/state_reader.rs#L83)):*
> ```XML
>             .maybe_pending_data
>             .as_ref()
>             .and_then(|pending_data| pending_data.classes.get_compiled_class(class_hash))
> ```

Remove the `get_compiled_class` section and then you'll have an object that contains both casm and class and you won't need to retreive the class again in the code below

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2680)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @ShahakShama)

___
*[`crates/papyrus_execution/src/state_reader.rs` line 83 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2680#-OESlxRi37etrOmTGym2:-OET643QCf9xpuFSjbnF:b-zcjvte) ([raw file](https://github.com/starkware-libs/sequencer/blob/dbcfb503725fbc46e5d3d0853fcd6f319095a425/crates/papyrus_execution/src/state_reader.rs#L83)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove the `get_compiled_class` section and then you'll have an object that contains both casm and class and you won't need to retreive the class again in the code below
</blockquote></details>

Thanks

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2680)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/papyrus_execution/src/state_reader.rs` line 83 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2680#-OESlxRi37etrOmTGym2:-OETGh8RAEmzmPVstU2C:bchx9zf) ([raw file](https://github.com/starkware-libs/sequencer/blob/dbcfb503725fbc46e5d3d0853fcd6f319095a425/crates/papyrus_execution/src/state_reader.rs#L83)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Thanks
</blockquote></details>

No, I meant
`.and_then(|pending_data| pending_data.classes)`
and call this variable pending_classes and inside the if body get the class and casm from it

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2680)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @AvivYossef-starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2680)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @dorimedini-starkware, and @ShahakShama)

___
*[`crates/papyrus_execution/src/state_reader.rs` line 83 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2680#-OESlxRi37etrOmTGym2:-OETLUlU3zbFCvxs_6il:b-xj4w9e) ([raw file](https://github.com/starkware-libs/sequencer/blob/dbcfb503725fbc46e5d3d0853fcd6f319095a425/crates/papyrus_execution/src/state_reader.rs#L83)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No, I meant
`.and_then(|pending_data| pending_data.classes)`
and call this variable pending_classes and inside the if body get the class and casm from it
</blockquote></details>

Is this what you mean?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2680)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @ShahakShama)

**Pull request merged**
