### PR TITLE
refactor(consensus): rename topic in config to network_topic

### PR DESCRIPTION
**Pull request by matan-starkware**
This is prep for adding sync_topic.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/406)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/406?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#406** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/406?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#404** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/404?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#389** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/389?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#403](https://github.com/starkware-libs/sequencer/pull/403) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/403?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#387** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/387?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#386** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/386?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by asmaastarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/406)* status: all files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/406#-O45PP3v1ftVZc9pVVxN):*
refactor is more appropriate
___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/406#-O45Or0s9xzE-GugYkid:-O45Or0s9xzE-GugYkie:bf3jbwq) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f5aa1891d480f4a913027e30a751434b9238d83/crates/sequencing/papyrus_consensus/src/config.rs#L52)):*
> ```XML
>                 "network_topic",
>                 &self.network_topic,
>                 "The network topic of the consensus",
> ```

"The network topic of the consensus.",



_Code quote:_
```XML
"The network topic of the consensus",
```

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/406)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/config.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/406#-O45Or0s9xzE-GugYkid:-O45ikuL4o8UX23ox30r:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9f5aa1891d480f4a913027e30a751434b9238d83/crates/sequencing/papyrus_consensus/src/config.rs#L52)):*
<details><summary><i>Previously, asmaastarkware (asmaa-starkware) wrote…</i></summary><blockquote>

"The network topic of the consensus.",
</blockquote></details>

Done.

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/406#-:-O4ABc9d2Hc3gH07Bw9w:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

**Review by asmaastarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/406)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by asmaastarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/406)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Comment by matan-starkware** [comment]
### Merge activity

* **Aug 15, 3:23 AM EDT**: @matan-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/406).

**Pull request merged**
