### PR TITLE
chore: share transaction option stracts

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1033)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1033)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_api/src/lib.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1033#-O7wSVJn4Vyo08LR4H2e:-O7wSVJoAUGuf64jDnC6:btb4e2k) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7e94d048111caebc9ff21663e92e17cea0d8f1e/crates/starknet_api/src/lib.rs#L46)):*
> ```XML
> }
> 
> #[derive(Copy, Clone, Debug, Eq, PartialEq, Default)]
> ```

put this in crates/starknet_api/src/transaction.rs

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1033)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_api/src/lib.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1033#-O7wSVJn4Vyo08LR4H2e:-O7wSkHlDEofRR2QRUCV:btlsz1x) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7e94d048111caebc9ff21663e92e17cea0d8f1e/crates/starknet_api/src/lib.rs#L46)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

put this in crates/starknet_api/src/transaction.rs
</blockquote></details>

or maybe in transaction_hash.rs

**Comment by ArniStarkware** [comment]
Already covered by #915.

**Comment by ArniStarkware** [comment]
*[`crates/starknet_api/src/lib.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1033#-O7wSVJn4Vyo08LR4H2e:-O7wojIp2JSZeJqQU4ZP:b54y26s) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7e94d048111caebc9ff21663e92e17cea0d8f1e/crates/starknet_api/src/lib.rs#L46)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

or maybe in transaction_hash.rs
</blockquote></details>

covered in #915. Done.

**Pull request closed without merging**
