### PR TITLE
test(starknet_integration_tests): test mempool syncing in e2e flow test

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Comment by yair-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2628?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2628** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2628?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2628?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2348** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2348?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2591** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2591?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2426** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2426?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2299** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2299?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2242** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2242?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2253** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2253?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2628)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2628#-ODkazus6JWnx6I5tLyx:-ODkazus6JWnx6I5tLyy:bkk5xpf) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb9df0a8ca58cb06185ca629bb07eebb13e2bf58/crates/starknet_integration_tests/src/flow_test_setup.rs#L61)):*
> ```XML
>         // order to make sure the ports are not overlapping.
>         let sequencer_0_consensus_manager_config = consensus_manager_configs.remove(0);
>         let sequencer_0_mempool_p2p_config = mempool_p2p_configs.remove(0);
> ```

Consider converting to array with try_into and use array unpacking
```
let [sequencer_0_mempool_p2p_config, sequencer_1_mempool_p2p_config]: [MempoolP2pConfig; 2] = mempool_p2p_configs.try_into().unwrap();
```
___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2628#-ODkbT1pCpi2z-f1k-Xv:-ODkbT1pCpi2z-f1k-Xw:bt9zqql) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb9df0a8ca58cb06185ca629bb07eebb13e2bf58/crates/starknet_integration_tests/src/integration_test_setup.rs#L59)):*
> ```XML
>         let (mut consensus_manager_configs, _consensus_proposals_channels) =
>             create_consensus_manager_configs_and_channels(SEQUENCER_INDICES.len());
>         let mut mempool_p2p_configs =
> ```

What's happening here? Are all the configs but one dropped?
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2628#-ODkbzol-Pa4jwMfUpR6:-ODkbzol-Pa4jwMfUpR7:bn4baus) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb9df0a8ca58cb06185ca629bb07eebb13e2bf58/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L58)):*
> ```XML
> 
>     let sequencers = [&mock_running_system.sequencer_0, &mock_running_system.sequencer_1];
>     // We use only the first sequencer's gateway to test that the mempools are syncing.
> ```

Make it clear, either by comments or (more preferrably) by code, that this is the validator

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2628)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @ShahakShama)

___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2628#-ODkazus6JWnx6I5tLyx:-ODkpzcW4vIsw51r7XwC:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb9df0a8ca58cb06185ca629bb07eebb13e2bf58/crates/starknet_integration_tests/src/flow_test_setup.rs#L61)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider converting to array with try_into and use array unpacking
```
let [sequencer_0_mempool_p2p_config, sequencer_1_mempool_p2p_config]: [MempoolP2pConfig; 2] = mempool_p2p_configs.try_into().unwrap();
```
</blockquote></details>

Done
___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2628#-ODkbT1pCpi2z-f1k-Xv:-ODkcNB_48cxz6lslUkk:b-uqb386) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb9df0a8ca58cb06185ca629bb07eebb13e2bf58/crates/starknet_integration_tests/src/integration_test_setup.rs#L59)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What's happening here? Are all the configs but one dropped?
</blockquote></details>

There's only 1 sequencer in the integration test for now
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2628#-ODkbzol-Pa4jwMfUpR6:-ODkcWkTAqZkTfT8ptfv:b7w30d0) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb9df0a8ca58cb06185ca629bb07eebb13e2bf58/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L58)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Make it clear, either by comments or (more preferrably) by code, that this is the validator
</blockquote></details>

The proposer/validator changes each height

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2628#-:-OEIdUgk0JoIuZUtcZTr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2628#-ODkbT1pCpi2z-f1k-Xv:-OEId4pM9AXv3dj62jQE:b-2ooyis) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb9df0a8ca58cb06185ca629bb07eebb13e2bf58/crates/starknet_integration_tests/src/integration_test_setup.rs#L59)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

There's only 1 sequencer in the integration test for now
</blockquote></details>

Do you want to add a TODO to add more?

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2628)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/src/integration_test_setup.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2628#-ODkbT1pCpi2z-f1k-Xv:-OEIdhJX2mKix6r8ynFC:bfu461q) ([raw file](https://github.com/starkware-libs/sequencer/blob/eb9df0a8ca58cb06185ca629bb07eebb13e2bf58/crates/starknet_integration_tests/src/integration_test_setup.rs#L59)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Do you want to add a TODO to add more?
</blockquote></details>

Itay's team is working on it

**Pull request merged**
