### PR TITLE
feat(config): struct pointers

### PR DESCRIPTION
**Pull request by yair-starkware**

### CODE REVIEW

**Comment by yair-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1953?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1954** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1954?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1953** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1953?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1946** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1946?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yair-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1953)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_config/src/lib.rs` line 153 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBVfNq_6CV3oQRkvFur:-OBVfNq_6CV3oQRkvFus:b-qdi1sv) ([raw file](https://github.com/starkware-libs/sequencer/blob/38815fb8818eda38dde2a35935d0969b1001fcf8/crates/papyrus_config/src/lib.rs#L153)):*
> ```XML
> /// A serialized type of a configuration parameter.
> #[derive(Clone, Copy, Serialize, Deserialize, Debug, PartialEq, strum_macros::Display)]
> #[allow(missing_docs)]
> ```

Is this still needed?



_Code quote:_
```XML
#[allow(missing_docs)]
```
___
*[`crates/papyrus_config/src/dumping.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBVuO_vD1165IdFQQMb:-OBVuO_vD1165IdFQQMc:b-3oz9eb) ([raw file](https://github.com/starkware-libs/sequencer/blob/38815fb8818eda38dde2a35935d0969b1001fcf8/crates/papyrus_config/src/dumping.rs#L66)):*
> ```XML
> pub type ConfigPointers = Vec<(PointerTarget, Pointers)>;
> 
> /// Given set of paths that are configuration of the same struct type, makes all the paths point to
> ```

Given *a* set



_Code quote:_
```XML
Given set 
```
___
*[`crates/papyrus_config/src/dumping.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBVwrR5CjD6jnTtJcdI:-OBVwrR5CjD6jnTtJcdJ:booy4lz) ([raw file](https://github.com/starkware-libs/sequencer/blob/38815fb8818eda38dde2a35935d0969b1001fcf8/crates/papyrus_config/src/dumping.rs#L75)):*
> ```XML
> ) {
>     let target_dump = default_instance.dump();
>     for (param_path, serialized_param) in target_dump {
> ```

Could this be ` default_instance.dump()`, and then you wouldn't have to define `target_dump`?



_Code quote:_
```XML
target_dump
```
___
*[`crates/papyrus_config/src/dumping.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBVuFvj67Rux5b_3dda:-OBVuFvj67Rux5b_3ddb:b-c9l0bk) ([raw file](https://github.com/starkware-libs/sequencer/blob/38815fb8818eda38dde2a35935d0969b1001fcf8/crates/papyrus_config/src/dumping.rs#L86)):*
> ```XML
>                     .strip_prefix(REQUIRED_PARAM_DESCRIPTION_PREFIX)
>                     .unwrap_or(&serialized_param.description);
>                 ser_pointer_target_required_param(
> ```

Note this sets the target as a required parameter. In https://reviewable.io/reviews/starkware-libs/sequencer/1954 however it is added as a non-required parameter.
I'd be more explicit here, and have two variants, one for required and one for non-required params. They can both call a common base function if that makes sense.



_Code quote:_
```XML
ser_pointer_target_required_param(
```
___
*[`crates/papyrus_config/src/dumping.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBVxh4k3Q-TpPInXolY:-OBVxh4k3Q-TpPInXolZ:b-37mgwf) ([raw file](https://github.com/starkware-libs/sequencer/blob/38815fb8818eda38dde2a35935d0969b1001fcf8/crates/papyrus_config/src/dumping.rs#L92)):*
> ```XML
>                 )
>             }
>             SerializedContent::PointerTarget(_) => panic!("Pointer target cannot be a pointer."),
> ```

Why not point it at the target as well?



_Code quote:_
```XML
SerializedContent::PointerTarget(_) => panic!("Pointer target cannot be a pointer."),
```
___
*[`crates/papyrus_config/src/dumping.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBVyKa_BW1KNE0iHo_7:-OBVyKa_BW1KNE0iHo_8:bmouzt7) ([raw file](https://github.com/starkware-libs/sequencer/blob/38815fb8818eda38dde2a35935d0969b1001fcf8/crates/papyrus_config/src/dumping.rs#L98)):*
> ```XML
>             pointer_prefixes
>                 .iter()
>                 .map(|pointer| format!("{}{}{}", pointer, FIELD_SEPARATOR, param_path))
> ```

Wrap as a function?



_Code quote:_
```XML
format!("{}{}{}", pointer, FIELD_SEPARATOR, param_path)
```
___
*[`crates/papyrus_config/src/dumping.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBVy5Ii-dZ-u1boXUq_:-OBVy5Ij6YGsz8BFBuyO:bjcvhf5) ([raw file](https://github.com/starkware-libs/sequencer/blob/38815fb8818eda38dde2a35935d0969b1001fcf8/crates/papyrus_config/src/dumping.rs#L100)):*
> ```XML
>                 .map(|pointer| format!("{}{}{}", pointer, FIELD_SEPARATOR, param_path))
>                 .collect(),
>         ));
> ```

Why not create a vector and return it?



_Code quote:_
```XML
        config_pointers.push((
            pointer_target,
            pointer_prefixes
                .iter()
                .map(|pointer| format!("{}{}{}", pointer, FIELD_SEPARATOR, param_path))
                .collect(),
        ));
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1953)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/papyrus_config/src/dumping.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBVuO_vD1165IdFQQMb:-OBZkJCn9KloRpzpOKt1:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/38815fb8818eda38dde2a35935d0969b1001fcf8/crates/papyrus_config/src/dumping.rs#L66)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Given *a* set
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/dumping.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBVwrR5CjD6jnTtJcdI:-OBZkTC5CKwrhUKcClkO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/38815fb8818eda38dde2a35935d0969b1001fcf8/crates/papyrus_config/src/dumping.rs#L75)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Could this be ` default_instance.dump()`, and then you wouldn't have to define `target_dump`?
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/dumping.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBVuFvj67Rux5b_3dda:-OBZndTX8ZvvDDyVL9QE:b-glqyhb) ([raw file](https://github.com/starkware-libs/sequencer/blob/38815fb8818eda38dde2a35935d0969b1001fcf8/crates/papyrus_config/src/dumping.rs#L86)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Note this sets the target as a required parameter. In https://reviewable.io/reviews/starkware-libs/sequencer/1954 however it is added as a non-required parameter.
I'd be more explicit here, and have two variants, one for required and one for non-required params. They can both call a common base function if that makes sense.
</blockquote></details>

Why do we have separation if they are combined later?
___
*[`crates/papyrus_config/src/dumping.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBVxh4k3Q-TpPInXolY:-OBZksfX74fu9U9klLGA:b-fvqjrf) ([raw file](https://github.com/starkware-libs/sequencer/blob/38815fb8818eda38dde2a35935d0969b1001fcf8/crates/papyrus_config/src/dumping.rs#L92)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Why not point it at the target as well?
</blockquote></details>

I don't think we support pointer to pointer, did you try it?
___
*[`crates/papyrus_config/src/dumping.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBVy5Ii-dZ-u1boXUq_:-OBZn1b46Ls703YgiW8V:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/38815fb8818eda38dde2a35935d0969b1001fcf8/crates/papyrus_config/src/dumping.rs#L100)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Why not create a vector and return it?
</blockquote></details>

Done.
___
*[`crates/papyrus_config/src/lib.rs` line 153 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBVfNq_6CV3oQRkvFur:-OBZnDDAA_jMO4WV1zEU:b-8fzolw) ([raw file](https://github.com/starkware-libs/sequencer/blob/38815fb8818eda38dde2a35935d0969b1001fcf8/crates/papyrus_config/src/lib.rs#L153)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Is this still needed?
</blockquote></details>

Yes, otherwise you need to doc each variant

**Comment by yair-starkware** [comment]
*[`crates/papyrus_config/src/dumping.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBVxh4k3Q-TpPInXolY:-OBdgv6d8fu0DeGrk-Hy:bnxo0j5) ([raw file](https://github.com/starkware-libs/sequencer/blob/38815fb8818eda38dde2a35935d0969b1001fcf8/crates/papyrus_config/src/dumping.rs#L92)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I don't think we support pointer to pointer, did you try it?
</blockquote></details>

Thinking about it, the dump of a struct shouldn't contain pointers at all I think, only in the `dump_to_file` it should get pointers

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1953)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_config/src/dumping.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBVuFvj67Rux5b_3dda:-OBgMod63fo_HtTutVtU:b-rtot4l) ([raw file](https://github.com/starkware-libs/sequencer/blob/38815fb8818eda38dde2a35935d0969b1001fcf8/crates/papyrus_config/src/dumping.rs#L86)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do we have separation if they are combined later?
</blockquote></details>

You could define a required parameter that no one points at. That's the current usage in papyrus.
However, we might as well just create required parameters as targets and have an empty set of pointers.
WDYT?
___
*[`crates/papyrus_config/src/dumping.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBVy5Ii-dZ-u1boXUq_:-OBgNZMZ5qbkCK9rihQa:b-kfll4h) ([raw file](https://github.com/starkware-libs/sequencer/blob/38815fb8818eda38dde2a35935d0969b1001fcf8/crates/papyrus_config/src/dumping.rs#L100)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I had something else in mind, wdyt?

The current code structure is:
```
let mut res;
loop over some list {
    ....
    calculations
    ....
   add a single result to res
}
res
```

I suggest to change it such it is more of a `map`-like syntax, i.e., map each element from `some list` to an element in `res`.

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1953)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/papyrus_config/src/dumping.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBVuFvj67Rux5b_3dda:-OBuScue4F_gOYQLMWEm:bskksqd) ([raw file](https://github.com/starkware-libs/sequencer/blob/38815fb8818eda38dde2a35935d0969b1001fcf8/crates/papyrus_config/src/dumping.rs#L86)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

You could define a required parameter that no one points at. That's the current usage in papyrus.
However, we might as well just create required parameters as targets and have an empty set of pointers.
WDYT?
</blockquote></details>

Consolidated pointers as discussed in https://github.com/starkware-libs/sequencer/pull/2111
___
*[`crates/papyrus_config/src/dumping.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBVy5Ii-dZ-u1boXUq_:-OBuSlOj48yEU7IkXKy5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/38815fb8818eda38dde2a35935d0969b1001fcf8/crates/papyrus_config/src/dumping.rs#L100)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I had something else in mind, wdyt?

The current code structure is:
```
let mut res;
loop over some list {
    ....
    calculations
    ....
   add a single result to res
}
res
```

I suggest to change it such it is more of a `map`-like syntax, i.e., map each element from `some list` to an element in `res`.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1953)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_config/src/dumping.rs` line 87 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBvDVPP1FfTz7cPvmCK:-OBvDVPQ31nYWtTN00Cw:b-5vd6b0) ([raw file](https://github.com/starkware-libs/sequencer/blob/b7afab75fd518232c72cd90c79f0517cd3dfcafd/crates/papyrus_config/src/dumping.rs#L87)):*
> ```XML
> 
> // Converts a serialized param to a pointer target.
> fn to_target(
> ```

Please change to a more descriptive name, e.g., `serialized_param_to_pointer_target` (leaving as non blocking).



_Code quote:_
```XML
to_target
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1953)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/papyrus_config/src/dumping.rs` line 87 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-OBvDVPP1FfTz7cPvmCK:-OByLbXR1p3Aty6rVfEd:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/b7afab75fd518232c72cd90c79f0517cd3dfcafd/crates/papyrus_config/src/dumping.rs#L87)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to a more descriptive name, e.g., `serialized_param_to_pointer_target` (leaving as non blocking).
</blockquote></details>

done

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1953#-:-OByUHnABkHh8ogYkjX5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Comment by yair-starkware** [comment]
### Merge activity

* **Nov 18, 4:13 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1953).

**Pull request merged**
