### PR TITLE
chore(batcher): rename block full boolean

### PR DESCRIPTION
**Pull request by alonh5**

### CODE REVIEW

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1748)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @dafnamatsry)

___
*[`crates/batcher/src/block_builder.rs` line 148 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1748#-OAlkG67CjPDdxJmOJaJ:-OAlkG68AtemJfxu_EMk:b-ghji6g) ([raw file](https://github.com/starkware-libs/sequencer/blob/dfb03a9c489c78aef4f6816cbed47375b2da5c10/crates/batcher/src/block_builder.rs#L148)):*
> ```XML
>         output_content_sender: tokio::sync::mpsc::UnboundedSender<Transaction>,
>     ) -> BlockBuilderResult<BlockExecutionArtifacts> {
>         let mut block_is_full = false;
> ```

not sure I understand why the renaming is required now?

Is this as preparation for the code I am writing, where there will be another reason to close a block?



_Code quote:_
```XML
block_is_full
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1748)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/block_builder.rs` line 148 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1748#-OAlkG67CjPDdxJmOJaJ:-OAllX0eEIdqP-9fkJZ8:b-srv22b) ([raw file](https://github.com/starkware-libs/sequencer/blob/dfb03a9c489c78aef4f6816cbed47375b2da5c10/crates/batcher/src/block_builder.rs#L148)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

not sure I understand why the renaming is required now?

Is this as preparation for the code I am writing, where there will be another reason to close a block?
</blockquote></details>

Becasue it doesn't refer to all the reasons a block should be closed, it only holds true if the block is full. I had to go inside the function each time to understand why a block should be close, so that indicates the naming could be better.
Just a small semantic issue that bothered me

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1748)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1748)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
