### PR TITLE
fix(blockifier_reexecution): fix declare bug in offline reexecution

### PR DESCRIPTION
**Pull request by aner-starkware**

### CODE REVIEW

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1935)* status: all files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1935#-OBPr0by6f3rnJtHrWCa:-OBPzTRg1e_pCzbzt3iO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/73ec0a4ea0d7563175c5c5d60a31b492aaeac4d8/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L134)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does this work?
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1935#-OBPqY1o1XfmFL9_BF67:-OBPzF74Aixsqi44jD63:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/73ec0a4ea0d7563175c5c5d60a31b492aaeac4d8/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L135)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a TODO to extract `api_txs_to_blockifier_txs_next_block` out of the state reader... after the code matured a bit, I think it's a better idea to inject a mapping from class hash to class info as a parameter, instead of reading it from `self`.
you really only need the contract class mapping to convert the txs
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 480 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1935#-OBPrBQjAaWGYEE0U0Ij:-OBPxZsID6sWSaee-ZE5:bip0mnc) ([raw file](https://github.com/starkware-libs/sequencer/blob/73ec0a4ea0d7563175c5c5d60a31b492aaeac4d8/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L480)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

I can change it to `expect` or remove it. The idea is to stop the reexecution from running if there's already an issue here.
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1935#-OBPrR5E6JmPbQlc14xc:-OBPxx6N4nWcFwoO75Lw:b-gpxsaw) ([raw file](https://github.com/starkware-libs/sequencer/blob/73ec0a4ea0d7563175c5c5d60a31b492aaeac4d8/crates/blockifier_reexecution/src/state_reader/utils.rs#L190)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you change it like this, you will get more informative failures in the console - if the assert fails you will get the specific error
</blockquote></details>

I'm not sure it's necessary to add debugging here, as it should pass. This is just to split any error into execution error and result error.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1935)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 477 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1935#-OBQBOe235xUK1qi1mzm:-OBQBOe235xUK1qi1mzn:b-4y8u1d) ([raw file](https://github.com/starkware-libs/sequencer/blob/5eb6198b1e70245d3f7dd8d31d218661cae63a03/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L477)):*
> ```XML
>         let (transactions_next_block, declared_classes) =
>             self.get_next_block_starknet_api_txs_and_declared_classes()?;
>         assert!(self.get_next_block_txs().is_ok());
> ```

or, just this:
```
self.get_next_block_txs().unwrap()
```
the point is seeing an informative error on failure



_Suggestion:_
```XML
assert_matches!(self.get_next_block_txs(), Ok(_));
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1935)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 477 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1935#-OBQBOe235xUK1qi1mzm:-OBQD7zM06UA4rb5JXgT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5eb6198b1e70245d3f7dd8d31d218661cae63a03/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L477)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

or, just this:
```
self.get_next_block_txs().unwrap()
```
the point is seeing an informative error on failure
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1935#-OBPrR5E6JmPbQlc14xc:-OBQD6YmC4vzf1yRHfNM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/73ec0a4ea0d7563175c5c5d60a31b492aaeac4d8/crates/blockifier_reexecution/src/state_reader/utils.rs#L190)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I'm not sure it's necessary to add debugging here, as it should pass. This is just to split any error into execution error and result error.
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1935#-:-OBQEwLi1VsTuWCM443p:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
