### PR TITLE
fix(blockifier,committer_cli,papyrus_network,papyrus_storage,starknet…

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
…_client): clippy

### CODE REVIEW

**Review by nimrod-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2355#-:-OCnR_X35tgLf2-zvZzo:bnfp4nl)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2355)* status: 9 of 29 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2355#-OCnSRw522ePs-7rkt0T:-OCnSRw522ePs-7rkt0U:b-8nn0c2) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c2bab501d2a4935c7d4c8a74eda142ac4f8f17c/crates/blockifier/src/execution/syscalls/hint_processor.rs#L190)):*
> ```XML
> 
> /// Error codes returned by Cairo 1.0 code.
> // "Out of gas";
> ```

Does this work?



_Suggestion:_
```XML
/// Error codes returned by Cairo 1.0 code.


// "Out of gas";
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 346 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2355#-OCnSAoV1qBCRI8JZeeg:-OCnSAoV1qBCRI8JZeeh:b-fmi334) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c2bab501d2a4935c7d4c8a74eda142ac4f8f17c/crates/blockifier/src/execution/entry_point.rs#L346)):*
> ```XML
>         // Logically, we update remaining steps to `max(0, remaining_steps - steps_to_subtract)`.
>         let remaining_steps = self.n_remaining_steps();
>         let new_remaining_steps = remaining_steps.saturating_sub(steps_to_subtract);
> ```

Uch... `saturating_sub` is indeed exactly that - but I would argue it is less readable.



_Code quote:_
```XML
let new_remaining_steps = remaining_steps.saturating_sub(steps_to_subtract);
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2355#-OCnScMmCVkdjywrOT4E:-OCnScMmCVkdjywrOT4F:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c2bab501d2a4935c7d4c8a74eda142ac4f8f17c/crates/blockifier/src/fee/gas_usage.rs#L68)):*
> ```XML
>         discount += eth_gas_constants::GAS_PER_MEMORY_WORD - fee_balance_value_cost;
> 
>         let gas = naive_cost.saturating_sub(discount);
> ```





_Suggestion:_
```XML
   // Cost must be non-negative after discount.
   let gas = naive_cost.saturating_sub(discount);
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 16 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2355)* status: 25 of 29 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/papyrus_test_utils/src/lib.rs` line 365 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2355#-OCnTJThEq9vzpR8hkJL:-OCnTJThEq9vzpR8hkJM:b2ni4dp) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c2bab501d2a4935c7d4c8a74eda142ac4f8f17c/crates/papyrus_test_utils/src/lib.rs#L365)):*
> ```XML
> //////////////////////////////////////////////////////////////////////////
> // /// EXTERNAL FUNCTIONS - REMOVE DUPLICATIONS
> //////////////////////////////////////////////////////////////////////////
> ```

hu?



_Code quote:_
```XML
//////////////////////////////////////////////////////////////////////////
// /// EXTERNAL FUNCTIONS - REMOVE DUPLICATIONS
//////////////////////////////////////////////////////////////////////////
```

**Comment by ArniStarkware** [comment]
*[`crates/starknet_api/src/core.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2355#-OCnUI4hB91h96ItSYsc:-OCnUI4hB91h96ItSYsd:bd6vu0t) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c2bab501d2a4935c7d4c8a74eda142ac4f8f17c/crates/starknet_api/src/core.rs#L90)):*
> ```XML
> /// [DeclareTransaction](`crate::transaction::DeclareTransaction`), and
> /// [BlockHeader](`crate::block::BlockHeader`).
> // The block hash table is stored in address 0x1,
> ```

Creating a discussion to get a link.



_Code quote:_
```XML
/// The address of a contract, used for example in [StateDiff](`crate::state::StateDiff`),
/// [DeclareTransaction](`crate::transaction::DeclareTransaction`), and
/// [BlockHeader](`crate::block::BlockHeader`).
// The block hash table is stored in address 0x1,
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2355)* status: 25 of 29 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2355#-OCnXE1SAfRtkEk04O7C:-OCnXE1SAfRtkEk04O7D:b-cflyt0) (no related file):*
There is one use in the repo of:
`is_none_or`

It can be replaced with:
```
match self.current_height {
            Some(h) => h < height,
            None => true,
        }
```

Use this to fix if it is blocking.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2355)* status: 27 of 29 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/papyrus_test_utils/src/lib.rs` line 365 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2355#-OD-tLVH8Ox4ljMogUlB:-OD-tLVH8Ox4ljMogUlC:b-1rrgjp) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c2bab501d2a4935c7d4c8a74eda142ac4f8f17c/crates/papyrus_test_utils/src/lib.rs#L365)):*
> ```XML
> //////////////////////////////////////////////////////////////////////////
> // /// EXTERNAL FUNCTIONS - REMOVE DUPLICATIONS
> //////////////////////////////////////////////////////////////////////////
> ```

This is how other headlines in this file are set.



_Suggestion:_
```XML
//////////////////////////////////////////////////////////////////////////
// EXTERNAL FUNCTIONS - REMOVE DUPLICATIONS
//////////////////////////////////////////////////////////////////////////
```

**Comment by ArniStarkware** [comment]
If we plan to revive this PR, it needs a restack.

**Comment by ArniStarkware** [comment]
Replaced with #2365

**Review by ArniStarkware — COMMENTED** [review]
Please delete this PR. #2371 was merged.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2355#-:-OD1FNMj3zZ0XZrby4_1:bxoe31z)* status: 27 of 29 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

**Pull request closed without merging**
