### PR TITLE
refactor(mempool): implement single [Mempool,TransactionQueue]Content::assert_eq

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1200)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1200)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1200#-O8WYNIJAXykuDbCVV8q:-O8WYNIJAXykuDbCVV8r:bghjmxr) ([raw file](https://github.com/starkware-libs/sequencer/blob/cd89f06ee5b0bb9f7b494a4bdd50fc5d00f65a9e/crates/mempool/src/mempool_test.rs#L38)):*
> ```XML
> 
> impl MempoolContent {
>     pub fn assert_eq(&self, mempool: &Mempool) {
> ```

is this necessary? 



_Code quote:_
```XML
pub 
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1200)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1200#-O8WYNIJAXykuDbCVV8q:-O8WZ1aV2LiSwsMsI0Cz:bddp37h) ([raw file](https://github.com/starkware-libs/sequencer/blob/cd89f06ee5b0bb9f7b494a4bdd50fc5d00f65a9e/crates/mempool/src/mempool_test.rs#L38)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

is this necessary?
</blockquote></details>

Nope, done.

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1200#-:-O8Wac5_EEexD6m4T8WK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1200#-:-O8WbBi21QjADy5fjwzY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
