### PR TITLE
feat(blockifier): initial_gas of call to empty ctor derived from tracked resource

### PR DESCRIPTION
**Pull request by TzahiTaub**

### CODE REVIEW

**Comment by TzahiTaub** [comment]
* **#3002** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3002?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/3002?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main-v0.13.4`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3002#-:-OFLRj7BDUxhuGNA8vI7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 459 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3002#-OFLRNyp4N0v5AwiOdY7:-OFLRNyp4N0v5AwiOdY8:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c34ca89b645b05674951409d37dff55c3af2d10e/crates/blockifier/src/execution/entry_point.rs#L459)):*
> ```XML
>     let current_tracked_resource = compiled_class.get_current_tracked_resource(context);
>     let initial_gas = if current_tracked_resource == TrackedResource::CairoSteps {
>         // Override the initial gas with a high value to ve consistent with the behavior for the
> ```





_Suggestion:_
```XML
value to be consis
```

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3002)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3002)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 464 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/3002#-OFMLyhl2aMxpBpJ60Ld:-OFMLyhl2aMxpBpJ60Le:beuq6nu) ([raw file](https://github.com/starkware-libs/sequencer/blob/38642a7ef56cbf44a61cfe00e020846e6cf624a8/crates/blockifier/src/execution/entry_point.rs#L464)):*
> ```XML
>     } else {
>         remaining_gas
>     };
> ```

y u no like `match`?
non-blocking



_Suggestion:_
```XML
    let initial_gas = match current_tracked_resource {
        TrackedResource::CairoSteps => {
        // Override the initial gas with a high value to be consistent with the behavior for the
        // rest of the CairoSteps mode calls.
        context.versioned_constants().infinite_gas_for_vm_mode()
        }
        TrackedResource::SierraGas => remaining_gas
    };
```

**Pull request merged**
