### PR TITLE
chore(mempool_infra): add documentation to remote component server

### PR DESCRIPTION
**Pull request by uriel-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/488)

### CODE REVIEW

**Review by lev-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/488)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_server/remote_component_server.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/488#-O4ZylfVDw6EnKh5D8tM:-O4ZylfVDw6EnKh5D8tN:b-os1dc0) ([raw file](https://github.com/starkware-libs/sequencer/blob/755f18a0ec803b850b277f0aa52e3ebad2d1c424/crates/mempool_infra/src/component_server/remote_component_server.rs#L33)):*
> ```XML
> ///   generates responses.
> /// - `Request`: The type of requests that the component will handle. This type must implement the
> ///   `serde::de::DeserializeOwned` trait.
> ```

I don't see the use of this trait in the example,



_Code quote:_
```XML
serde::de::DeserializeOwned
```

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/488)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/mempool_infra/src/component_server/remote_component_server.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/488#-O4ZylfVDw6EnKh5D8tM:-O4_574b3LUI0-I0smLd:b-s33l13) ([raw file](https://github.com/starkware-libs/sequencer/blob/755f18a0ec803b850b277f0aa52e3ebad2d1c424/crates/mempool_infra/src/component_server/remote_component_server.rs#L33)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

I don't see the use of this trait in the example,
</blockquote></details>

The derive macro with the Deserialize trait capture this trait
DeserializeOwned is an alias for `for<'a> Deserialize<'a>` so when you see the MyRequest has a derive with Deserialize it means it implement DeserializeOwned

**Review by lev-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/488)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_server/remote_component_server.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/488#-O4ZylfVDw6EnKh5D8tM:-O4_AKtvDvQ5sKRa9mv0:b-w894nk) ([raw file](https://github.com/starkware-libs/sequencer/blob/755f18a0ec803b850b277f0aa52e3ebad2d1c424/crates/mempool_infra/src/component_server/remote_component_server.rs#L33)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

The derive macro with the Deserialize trait capture this trait
DeserializeOwned is an alias for `for<'a> Deserialize<'a>` so when you see the MyRequest has a derive with Deserialize it means it implement DeserializeOwned
</blockquote></details>

No problem. Add something like 'this trait could be implemented by using #[derive(Deserialize)] on the structure' because you can't suppose that the user knows it.

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/488)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/mempool_infra/src/component_server/remote_component_server.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/488#-O4ZylfVDw6EnKh5D8tM:-O4_CHkXA_u9nefeF_5m:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/755f18a0ec803b850b277f0aa52e3ebad2d1c424/crates/mempool_infra/src/component_server/remote_component_server.rs#L33)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

No problem. Add something like 'this trait could be implemented by using #[derive(Deserialize)] on the structure' because you can't suppose that the user knows it.
</blockquote></details>

Done.

**Review by lev-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/488#-:-O4_CvoYBQMAEwtNwI-o:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)

**Pull request merged**
