### PR TITLE
feat: add trigger workflow to run upload artifacts on post merge

### PR DESCRIPTION
**Pull request by nadin-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1409)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1409)* status: all files reviewed, 5 unresolved discussions (waiting on @nadin-Starkware)

___
*[`.github/workflows/trigger _workflow.yml` line 6 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1409#-O9E5yFQ-K2qytsajcBi:-O9E5yFQ-K2qytsajcBj:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f6fd060f820edf6cdb5ff6e8385495f6de1b4e8/.github/workflows/trigger%20_workflow.yml#L6)):*
> ```YAML
> # events. It solves the issue of forked PRs not having access to secrets. Since external
> # contributors don’t have permission to access secrets, this dummy workflow runs with their
> #  privileges and triggers the upload_artifacts workflow via the workflow_run event.
> ```





_Suggestion:_
```YAML
# privi
```
___
*[`.github/workflows/trigger _workflow.yml` line 29 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1409#-O9E61BoEukYdHZZdnv-:-O9E61BoEukYdHZZdnv0:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f6fd060f820edf6cdb5ff6e8385495f6de1b4e8/.github/workflows/trigger%20_workflow.yml#L29)):*
> ```YAML
>       # Other than code-related changes, all changes related to the native-blockifier build-and-push
>       # process should trigger the build (e.g., changes to the Dockerfile, build scripts, etc.).
>       - '.github/workflows/blockifier_ci.yml'
> ```





_Suggestion:_
```YAML
- '.github/workflows/trigger_workflow.yml'
```
___
*[`.github/workflows/trigger _workflow.yml` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1409#-O9E692h4nFHlfE31ywu:-O9E692h4nFHlfE31ywv:b3lyp19) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f6fd060f820edf6cdb5ff6e8385495f6de1b4e8/.github/workflows/trigger%20_workflow.yml#L51)):*
> ```YAML
>     steps:
>       - name: Dummy step
>         run: echo "This is a dummy job to trigger the upload_artifacts workflow."
> ```

can this be completely empty? like `jobs: {}`?
will save the time it takes to set up a machine to run the dummy job on



_Code quote:_
```YAML
jobs:
  dummy_job:
    runs-on: starkware-ubuntu-latest-small
    steps:
      - name: Dummy step
        run: echo "This is a dummy job to trigger the upload_artifacts workflow."
```
___
*[`.github/workflows/upload_artifacts_workflow.yml` line 23 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1409#-O9E5h_U3aksK72Nw9gY:-O9E5h_U3aksK72Nw9gZ:b5skyt5) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f6fd060f820edf6cdb5ff6e8385495f6de1b4e8/.github/workflows/upload_artifacts_workflow.yml#L23)):*
> ```YAML
>         run: |
>           echo 'Trigger-Workflow failed'
>           exit 1
> ```

why is this necessary?



_Code quote:_
```YAML
      - name: Check tests status
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: |
          echo 'Trigger-Workflow failed'
          exit 1
```
___
*[`.github/workflows/upload_artifacts_workflow.yml` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1409#-O9E5rpn4bNBIUhNrLuY:-O9E5rpoCB8Vo4s3Qw5i:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f6fd060f820edf6cdb5ff6e8385495f6de1b4e8/.github/workflows/upload_artifacts_workflow.yml#L26)):*
> ```YAML
>       - uses: actions/checkout@v4
>         with:
>           ref: ${{ env.COMMIT_SHA }}
> ```





_Suggestion:_
```YAML
      # This workflow is always triggered in `main` branch context, so need to checkout the commit.
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMIT_SHA }}
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1409)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`.github/workflows/trigger _workflow.yml` line 6 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1409#-O9E5yFQ-K2qytsajcBi:-O9EB3qv2k8iazMzPpRM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f6fd060f820edf6cdb5ff6e8385495f6de1b4e8/.github/workflows/trigger%20_workflow.yml#L6)):*
> ```YAML
> # events. It solves the issue of forked PRs not having access to secrets. Since external
> # contributors don’t have permission to access secrets, this dummy workflow runs with their
> #  privileges and triggers the upload_artifacts workflow via the workflow_run event.
> ```

Done.
___
*[`.github/workflows/trigger _workflow.yml` line 29 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1409#-O9E61BoEukYdHZZdnv-:-O9EYLNW9pymV7Kg35mO:bin4ebc) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f6fd060f820edf6cdb5ff6e8385495f6de1b4e8/.github/workflows/trigger%20_workflow.yml#L29)):*
> ```YAML
>       # Other than code-related changes, all changes related to the native-blockifier build-and-push
>       # process should trigger the build (e.g., changes to the Dockerfile, build scripts, etc.).
>       - '.github/workflows/blockifier_ci.yml'
> ```

Need to add it, not replace it. Done.
___
*[`.github/workflows/trigger _workflow.yml` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1409#-O9E692h4nFHlfE31ywu:-O9EWJCLA0g6gc4jshcj:biemo3l) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f6fd060f820edf6cdb5ff6e8385495f6de1b4e8/.github/workflows/trigger%20_workflow.yml#L51)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can this be completely empty? like `jobs: {}`?
will save the time it takes to set up a machine to run the dummy job on
</blockquote></details>

A workflow run is made up of one or more jobs. (form GH)
But I added an if statement always to skip the steps (that should exist too).
___
*[`.github/workflows/upload_artifacts_workflow.yml` line 23 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1409#-O9E5h_U3aksK72Nw9gY:-O9EXdpW2V6bKt1EDPup:b-hxnghi) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f6fd060f820edf6cdb5ff6e8385495f6de1b4e8/.github/workflows/upload_artifacts_workflow.yml#L23)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this necessary?
</blockquote></details>

Indicates that the previous job succeeded, but not needed. deleting it
___
*[`.github/workflows/upload_artifacts_workflow.yml` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1409#-O9E5rpn4bNBIUhNrLuY:-O9EYF7m8u8lcv5IpbWp:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1f6fd060f820edf6cdb5ff6e8385495f6de1b4e8/.github/workflows/upload_artifacts_workflow.yml#L26)):*
> ```YAML
>       - uses: actions/checkout@v4
>         with:
>           ref: ${{ env.COMMIT_SHA }}
> ```

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1409)* status: all files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`.github/workflows/trigger _workflow.yml` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1409#-O9EspgP5RZLw_xrkXt8:-O9EspgP5RZLw_xrkXt9:b-p93uax) ([raw file](https://github.com/starkware-libs/sequencer/blob/29a19f7fb1d9b3776cd17e8af8170011c212b07b/.github/workflows/trigger%20_workflow.yml#L50)):*
> ```YAML
>   dummy_job:
>     runs-on: starkware-ubuntu-latest-small
>     if: false # This job should never run, as it only exists to trigger the upload_artifacts workflow.
> ```

this is marked as `skipped` now in the donut, and I don't see an upload-artifacts run, did it run?



_Code quote:_
```YAML
if: false # This job should never run, as it only exists to trigger the upload_artifacts workflow.
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1409)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`.github/workflows/trigger _workflow.yml` line 50 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1409#-O9EspgP5RZLw_xrkXt8:-O9cv8bK8-s9L7SBT8iO:b-8ll6bb) ([raw file](https://github.com/starkware-libs/sequencer/blob/29a19f7fb1d9b3776cd17e8af8170011c212b07b/.github/workflows/trigger%20_workflow.yml#L50)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is marked as `skipped` now in the donut, and I don't see an upload-artifacts run, did it run?
</blockquote></details>

I initially thought it would run, but after further research, I found that the job needs to be completed (and not skipped) for the upload_artifacts workflow to be triggered.

**Pull request merged**
