### PR TITLE
chore(ci, committer): stop running regression and bench on push

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/579)

### CODE REVIEW

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/579)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`.github/workflows/committer_ci.yml` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/579#-O57fWJSB61hW3PJSJKf:-O57fWJSB61hW3PJSJKg:b-nbj2du) ([raw file](https://github.com/starkware-libs/sequencer/blob/9aee7f48cbf1bd99b20ced4fed5a6e117fda5873/.github/workflows/committer_ci.yml#L113)):*
> ```YAML
>               repo: context.repo.repo,
>               body: fs.readFileSync('bench_new.txt', 'utf8'),
>               path: 'Commits'
> ```

Seems to be an ignored argument. See [here](https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#create-an-issue-comment--parameters).



_Code quote:_
```YAML
             path: 'Commits'
```

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/579)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/579#-:-O57hrpnCDJeLEesTOa6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/579)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/579)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
