### PR TITLE
chore(blockifier): add text file with current compiler version for CI use

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/195)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/195?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#197** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/197?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#196** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/196?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#195** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/195?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#194** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/194?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#184** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/184?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#183** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/183?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#182** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/182?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#181** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/181?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#180** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/180?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#179** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/179?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by aner-starkware** [comment]
*[`crates/blockifier/tests/cairo1_compiler_tag.txt` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/195#-O39R_snCv24DwqSzdWG:-O39R_snCv24DwqSzdWH:b-9h1u2b) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cc6a4f2a22c9ddebb3d177da49cdb44b5defd9d/crates/blockifier/tests/cairo1_compiler_tag.txt#L1)):*
> ```help
> v2.7.0-rc.3
> ```

imo, this is not a good idea. Apart from having to maintain 2 locations now instead of only the `.toml`, this also creates a "second point of truth", which is what you're trying to avoid.



_Code quote:_
```help
v2.7.0-rc.3
```

**Review by aner-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/195)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/tests/legacy_cairo1_compiler_tag.txt` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/195#-O39SFmh7mCSFxYysYux:-O39SFmh7mCSFxYysYuy:b6nmdr4) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cc6a4f2a22c9ddebb3d177da49cdb44b5defd9d/crates/blockifier/tests/legacy_cairo1_compiler_tag.txt#L1)):*
> ```help
> v2.1.0
> ```

What's the idea here?



_Code quote:_
```help
v2.1.0
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/195)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @AvivYossef-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/tests/cairo1_compiler_tag.txt` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/195#-O39R_snCv24DwqSzdWG:-O3CDRoZ294hq1ewGgap:b-dplefe) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cc6a4f2a22c9ddebb3d177da49cdb44b5defd9d/crates/blockifier/tests/cairo1_compiler_tag.txt#L1)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

imo, this is not a good idea. Apart from having to maintain 2 locations now instead of only the `.toml`, this also creates a "second point of truth", which is what you're trying to avoid.
</blockquote></details>

1. maintain: yes, you're right. need to update two places.
2. also correct but this is safe because it's tested for consistency
open to suggestions though
___
*[`crates/blockifier/tests/legacy_cairo1_compiler_tag.txt` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/195#-O39SFmh7mCSFxYysYux:-O3CDYzNAO8OZWV98cMH:b-lshlxw) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cc6a4f2a22c9ddebb3d177da49cdb44b5defd9d/crates/blockifier/tests/legacy_cairo1_compiler_tag.txt#L1)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

What's the idea here?
</blockquote></details>

legacy contract compiler tag. this version is unrelated to the version on the cargo toml and is constant.
now that I think of it, this text file can be the source of truth... just need to use `include_str!` to define the constant.
Done

**Comment by aner-starkware** [comment]
*[`crates/blockifier/tests/legacy_cairo1_compiler_tag.txt` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/195#-O39SFmh7mCSFxYysYux:-O3D21zh16c8dSG5BJDo:b-uw3ro2) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cc6a4f2a22c9ddebb3d177da49cdb44b5defd9d/crates/blockifier/tests/legacy_cairo1_compiler_tag.txt#L1)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

legacy contract compiler tag. this version is unrelated to the version on the cargo toml and is constant.
now that I think of it, this text file can be the source of truth... just need to use `include_str!` to define the constant.
Done
</blockquote></details>

If this is a constant that's not supposed to change, why not hardcode it?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/195)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @AvivYossef-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/tests/legacy_cairo1_compiler_tag.txt` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/195#-O39SFmh7mCSFxYysYux:-O3DbNs9DUdVbiJO7K3I:b-36u781) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cc6a4f2a22c9ddebb3d177da49cdb44b5defd9d/crates/blockifier/tests/legacy_cairo1_compiler_tag.txt#L1)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

If this is a constant that's not supposed to change, why not hardcode it?
</blockquote></details>

so it is also the point of truth in the CI.
if we know the tag in advance, the git-checkout phase in the CI is faster.
this is the *only* point of truth for this specific legacy version

**Comment by aner-starkware** [comment]
*[`crates/blockifier/tests/legacy_cairo1_compiler_tag.txt` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/195#-O39SFmh7mCSFxYysYux:-O3RCvyD8mmVLVQwVf8l:b-ugbyz6) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cc6a4f2a22c9ddebb3d177da49cdb44b5defd9d/crates/blockifier/tests/legacy_cairo1_compiler_tag.txt#L1)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

so it is also the point of truth in the CI.
if we know the tag in advance, the git-checkout phase in the CI is faster.
this is the *only* point of truth for this specific legacy version
</blockquote></details>

Why not hardcode in the CI instead of in a different file? The test can check that the hardcoded constant in the CI is equal to the expected.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/195)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @AvivYossef-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/tests/legacy_cairo1_compiler_tag.txt` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/195#-O39SFmh7mCSFxYysYux:-O3Xc0RXEfCj217FMVxO:blu1fwn) ([raw file](https://github.com/starkware-libs/sequencer/blob/0cc6a4f2a22c9ddebb3d177da49cdb44b5defd9d/crates/blockifier/tests/legacy_cairo1_compiler_tag.txt#L1)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Why not hardcode in the CI instead of in a different file? The test can check that the hardcoded constant in the CI is equal to the expected.
</blockquote></details>

actually I think it's not even needed anymore, see top of the stack

**Review by aner-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/195)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @AvivYossef-starkware, @meship-starkware, and @noaov1)

**Review by TzahiTaub — APPROVED** [review]
> Reviewed 1 of 4 files at r6, 2 of 4 files at r7, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/195)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware, @meship-starkware, and @noaov1)

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/195#-:-O40cVrxCZRkAgXb-OW9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware, @meship-starkware, and @noaov1)

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Aug 11, 11:28 AM EDT**: @dorimedini-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/195).

**Pull request merged**
