### PR TITLE
chore(ci): create sequencer integration test workflow

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
commit-id:55e84a9b

---

**Stack**:
- #2509
- #2508 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2508)* status: all files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/tests/end_to_end_integration_test.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-OD_O1Qv0VYBtTw9kXaX:-OD_O1Qv0VYBtTw9kXaY:bdmbzpt) ([raw file](https://github.com/starkware-libs/sequencer/blob/3113a2fa46aea19933f00249f8b2152c406a6aa5/crates/starknet_integration_tests/tests/end_to_end_integration_test.rs#L68)):*
> ```XML
>     if !run_integration_test() {
>         return;
>     }
> ```

general question:
why not use a feature? instead of an env var?
```
cargo test --test end_to_end_integration_test --feature run_integration_test
```
non-blocking



_Suggestion:_
```XML
#[cfg(feature = "run_integration_test")]
async fn test_end_to_end_integration(mut tx_generator: MultiAccountTransactionGenerator) {
```
___
*[`.github/workflows/sequencer_integration_tests.yml` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-OD_OE7hB9JArFyrV_Nc:-OD_OE7hB9JArFyrV_Nd:b-zf5hdm) ([raw file](https://github.com/starkware-libs/sequencer/blob/3113a2fa46aea19933f00249f8b2152c406a6aa5/.github/workflows/sequencer_integration_tests.yml#L9)):*
> ```YAML
>       - main-v[0-9].**
>     tags:
>       - v[0-9].**
> ```

this should also run on post-merge? why?



_Code quote:_
```YAML
  push:
    branches:
      - main
      - main-v[0-9].**
    tags:
      - v[0-9].**
```
___
*[`.github/workflows/sequencer_integration_tests.yml` line 33 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-OD_OLDDAKcVnb6qLiNP:-OD_OLDDAKcVnb6qLiNQ:b-il56az) ([raw file](https://github.com/starkware-libs/sequencer/blob/3113a2fa46aea19933f00249f8b2152c406a6aa5/.github/workflows/sequencer_integration_tests.yml#L33)):*
> ```YAML
>     steps:
>       - uses: actions/checkout@v4
>       - run: cargo build --bin starknet_sequencer_node
> ```

what about the bootstrapping? cargo and rust installation, etc?
what version of rust is used here?



_Code quote:_
```YAML
  build-sequencer-node:
    runs-on: starkware-ubuntu-latest-large
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --bin starknet_sequencer_node
```
___
*[`.github/workflows/sequencer_integration_tests.yml` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-OD_OWwGEkl2KqzA2vc7:-OD_OWwGEkl2KqzA2vc8:btlqbgg) ([raw file](https://github.com/starkware-libs/sequencer/blob/3113a2fa46aea19933f00249f8b2152c406a6aa5/.github/workflows/sequencer_integration_tests.yml#L36)):*
> ```YAML
> 
>   run-sequencer-integration-tests:
>     needs: build-sequencer-node
> ```

why not merge this job with the build-sequencer-node job, and run the test as just another step?
different jobs can (in theory) run concurrently, any other reason to split into two jobs?



_Code quote:_
```YAML
needs: build-sequencer-node
```
___
*[`.github/workflows/sequencer_integration_tests.yml` line 42 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-OD_Oe1b16uy91a7fcR2:-OD_Oe1b16uy91a7fcR3:bb7r2f0) ([raw file](https://github.com/starkware-libs/sequencer/blob/3113a2fa46aea19933f00249f8b2152c406a6aa5/.github/workflows/sequencer_integration_tests.yml#L42)):*
> ```YAML
>         with:
>           # Fetch the entire history.
>           fetch-depth: 0
> ```

why?



_Code quote:_
```YAML
        with:
          # Fetch the entire history.
          fetch-depth: 0
```
___
*[`crates/starknet_integration_tests/src/utils.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-OD_NqUeCyR8rxw1gdo_:-OD_NqUf8tzkcGJPodSt:b-d9sw8m) ([raw file](https://github.com/starkware-libs/sequencer/blob/3113a2fa46aea19933f00249f8b2152c406a6aa5/crates/starknet_integration_tests/src/utils.rs#L232)):*
> ```XML
> 
> pub fn run_integration_test() -> bool {
>     std::env::var("SEQUENCER_INTEGRATION_TESTS").is_ok()
> ```

use a util from infra utils please :)
all `std::env::var` calls should go through there, yes?



_Code quote:_
```XML
 std::env::var("SEQUENCER_INTEGRATION_TESTS").is_ok()
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2508)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`.github/workflows/sequencer_integration_tests.yml` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-OD_OE7hB9JArFyrV_Nc:-ODaJ6ZU8obEU1zq39_n:b-cktgov) ([raw file](https://github.com/starkware-libs/sequencer/blob/b905dddaa37a114d617250d87e110e6a81db1e74/.github/workflows/sequencer_integration_tests.yml#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this should also run on post-merge? why?
</blockquote></details>

I copied this part from `main.yml`. What should I change here?
___
*[`.github/workflows/sequencer_integration_tests.yml` line 33 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-OD_OLDDAKcVnb6qLiNP:-ODaXNWzCAG7aadQPhBw:bqciekj) ([raw file](https://github.com/starkware-libs/sequencer/blob/b905dddaa37a114d617250d87e110e6a81db1e74/.github/workflows/sequencer_integration_tests.yml#L33)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what about the bootstrapping? cargo and rust installation, etc?
what version of rust is used here?
</blockquote></details>

Added `- uses: ./.github/actions/bootstrap`, removed `actions/checkout@v4`
___
*[`.github/workflows/sequencer_integration_tests.yml` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-OD_OWwGEkl2KqzA2vc7:-ODaXaes1AVxVQD1hgLm:b-yoyjye) ([raw file](https://github.com/starkware-libs/sequencer/blob/b905dddaa37a114d617250d87e110e6a81db1e74/.github/workflows/sequencer_integration_tests.yml#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not merge this job with the build-sequencer-node job, and run the test as just another step?
different jobs can (in theory) run concurrently, any other reason to split into two jobs?
</blockquote></details>

Yes. We intend to have multiple integration tests, all relying on the build stage. I'd like these integration tests to run concurrently.
___
*[`.github/workflows/sequencer_integration_tests.yml` line 42 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-OD_Oe1b16uy91a7fcR2:-ODaXjZvD3n7pJt_5uP1:b-njzfze) ([raw file](https://github.com/starkware-libs/sequencer/blob/b905dddaa37a114d617250d87e110e6a81db1e74/.github/workflows/sequencer_integration_tests.yml#L42)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why?
</blockquote></details>

Removed, thanks.
___
*[`crates/starknet_integration_tests/src/utils.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-OD_NqUeCyR8rxw1gdo_:-ODaXwyaE-bV-r8lAj73:beop5iv) ([raw file](https://github.com/starkware-libs/sequencer/blob/b905dddaa37a114d617250d87e110e6a81db1e74/crates/starknet_integration_tests/src/utils.rs#L232)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use a util from infra utils please :)
all `std::env::var` calls should go through there, yes?
</blockquote></details>

:-)

This is intentional, `infra_utils` shouldn't care about `"SEQUENCER_INTEGRATION_TESTS"`. My point regarding consolidating env var usage was for envs that the producation code relies on. This is a mere test util that is solely relevant to this crate and its CI.

Should we further discuss the modus operandi in such tests at the weekly sync? There is another instance (which is where I got the inspiration from), please see https://github.com/starkware-libs/sequencer/blob/main/crates/papyrus_base_layer/src/base_layer_test.rs#L11-L13 
___
*[`crates/starknet_integration_tests/tests/end_to_end_integration_test.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-OD_O1Qv0VYBtTw9kXaX:-ODaYpfo9Df6C9_Bs5u-:bm1nwo8) ([raw file](https://github.com/starkware-libs/sequencer/blob/b905dddaa37a114d617250d87e110e6a81db1e74/crates/starknet_integration_tests/tests/end_to_end_integration_test.rs#L68)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

general question:
why not use a feature? instead of an env var?
```
cargo test --test end_to_end_integration_test --feature run_integration_test
```
non-blocking
</blockquote></details>

Will consider this offline, thanks for the suggestion :pray:

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2508)* status: all files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`.github/workflows/sequencer_integration_tests.yml` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-OD_OE7hB9JArFyrV_Nc:-ODaZaDa3i2hZZuaKdzX:b-t3yk6u) ([raw file](https://github.com/starkware-libs/sequencer/blob/b905dddaa37a114d617250d87e110e6a81db1e74/.github/workflows/sequencer_integration_tests.yml#L9)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I copied this part from `main.yml`. What should I change here?
</blockquote></details>

if you don't want this to run in post-merge, delete the entire `push:` entry.
search for `pull_request:` in our workflows, there should be at least one example for a workflow with *only* a `pull_request` event.
___
*[`.github/workflows/sequencer_integration_tests.yml` line 33 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-OD_OLDDAKcVnb6qLiNP:-ODa_Cec1ldREMfBrqxb:b-8owanv) ([raw file](https://github.com/starkware-libs/sequencer/blob/b905dddaa37a114d617250d87e110e6a81db1e74/.github/workflows/sequencer_integration_tests.yml#L33)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Added `- uses: ./.github/actions/bootstrap`, removed `actions/checkout@v4`
</blockquote></details>

why remove the checkout? isn't it required? [example](https://github.com/starkware-libs/sequencer/blob/main/.github/workflows/main.yml#L97-L102)
___
*[`crates/starknet_integration_tests/src/utils.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-OD_NqUeCyR8rxw1gdo_:-ODa_OYmBXWsgamljxCb:b1zsmgn) ([raw file](https://github.com/starkware-libs/sequencer/blob/b905dddaa37a114d617250d87e110e6a81db1e74/crates/starknet_integration_tests/src/utils.rs#L232)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

:-)

This is intentional, `infra_utils` shouldn't care about `"SEQUENCER_INTEGRATION_TESTS"`. My point regarding consolidating env var usage was for envs that the producation code relies on. This is a mere test util that is solely relevant to this crate and its CI.

Should we further discuss the modus operandi in such tests at the weekly sync? There is another instance (which is where I got the inspiration from), please see https://github.com/starkware-libs/sequencer/blob/main/crates/papyrus_base_layer/src/base_layer_test.rs#L11-L13
</blockquote></details>

ah, right... nvm
___
*[`.github/workflows/sequencer_integration_tests.yml` line 39 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-ODaZt273DO7I5sxNw0Y:-ODaZt273DO7I5sxNw0Z:b-wx44mn) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc069c3a59f4819f53f1873e59b34d441ee0aea9/.github/workflows/sequencer_integration_tests.yml#L39)):*
> ```YAML
>     runs-on: starkware-ubuntu-latest-large
>     steps:
>       - uses: ./.github/actions/bootstrap
> ```

if you already bootstrapped in the build-sequencer-node job, I don't think you need it again here



_Code quote:_
```YAML
- uses: ./.github/actions/bootstrap
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2508)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`.github/workflows/sequencer_integration_tests.yml` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-OD_OE7hB9JArFyrV_Nc:-ODadDsKBjz_wPX9UroM:b-fqxcy4) ([raw file](https://github.com/starkware-libs/sequencer/blob/b905dddaa37a114d617250d87e110e6a81db1e74/.github/workflows/sequencer_integration_tests.yml#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you don't want this to run in post-merge, delete the entire `push:` entry.
search for `pull_request:` in our workflows, there should be at least one example for a workflow with *only* a `pull_request` event.
</blockquote></details>

Ack, done.
___
*[`.github/workflows/sequencer_integration_tests.yml` line 33 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-OD_OLDDAKcVnb6qLiNP:-ODacddvAaVJVXreZcyF:bcvgupv) ([raw file](https://github.com/starkware-libs/sequencer/blob/b905dddaa37a114d617250d87e110e6a81db1e74/.github/workflows/sequencer_integration_tests.yml#L33)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why remove the checkout? isn't it required? [example](https://github.com/starkware-libs/sequencer/blob/main/.github/workflows/main.yml#L97-L102)
</blockquote></details>

Right, I thought it did something else. Got the following error without it, restoring.

```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/sequencer/sequencer/.github/actions/bootstrap'. Did you forget to run actions/checkout before running your local action?

Run cargo build --bin starknet\_sequencer\_node

0s

Complete job

0s
```
___
*[`.github/workflows/sequencer_integration_tests.yml` line 39 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-ODaZt273DO7I5sxNw0Y:-ODacwG92ri-preya0ME:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc069c3a59f4819f53f1873e59b34d441ee0aea9/.github/workflows/sequencer_integration_tests.yml#L39)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you already bootstrapped in the build-sequencer-node job, I don't think you need it again here
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-:-ODafZri5KCkIMOQdic1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2508)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`.github/workflows/sequencer_integration_tests.yml` line 33 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-ODagu4t7UphypUzpYxI:-ODagu4t7UphypUzpYxJ:bsvg8ch) ([raw file](https://github.com/starkware-libs/sequencer/blob/5e67c523465d2262a81ba957e70e20ec88f33c95/.github/workflows/sequencer_integration_tests.yml#L33)):*
> ```YAML
>     runs-on: starkware-ubuntu-latest-large
>     steps:
>       - uses: actions/checkout@v4
> ```

really? why?
I would expect the checkout in build-sequencer-node to be enough...
if not, isn't the bootstrap phase needed as well?



_Code quote:_
```YAML
- uses: actions/checkout@v4
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2508)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`.github/workflows/sequencer_integration_tests.yml` line 33 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-ODagu4t7UphypUzpYxI:-ODbhVUq0wjfvO0QcEE5:brm6j0i) ([raw file](https://github.com/starkware-libs/sequencer/blob/5e67c523465d2262a81ba957e70e20ec88f33c95/.github/workflows/sequencer_integration_tests.yml#L33)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

really? why?
I would expect the checkout in build-sequencer-node to be enough...
if not, isn't the bootstrap phase needed as well?
</blockquote></details>

Apparently jobs do not share state. Please see DM, and the new unified revision.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2508#-:-ODf6ocxCIMZZJJMRWzk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
