### PR TITLE
refactor(blockifier): move logic to function

### PR DESCRIPTION
**Pull request by dorimedini-starkware**

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
* **#2123** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2123?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2122** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2122?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2121** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2121?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2121?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2121#-:-OBzJolvAeBr65ul2m52:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2121)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Nov 19, 7:52 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2121).

**Pull request merged**
