### PR TITLE
fix(network): add chain id to Kademlia discovery protocol

### PR DESCRIPTION
**Pull request by AlonLStarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/171)

### CODE REVIEW

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/171)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @ShahakShama)

___
*[`crates/papyrus_network/src/lib.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/171#-O2yZbK_2G_Sc--TEhwY:-O2yZbK_2G_Sc--TEhwZ:b-yz7qps) ([raw file](https://github.com/starkware-libs/sequencer/blob/c0c83ada7c2af5d7fb2d0d52c2091b9dd0feb566/crates/papyrus_network/src/lib.rs#L92)):*
> ```XML
>              will be used.",
>             ParamPrivacyInput::Private,
>         )]);
> ```

need to include the new variable in the default config. to do so you'll need to run the dump config script that includes a call to dump which will use this func to dump your new variable into the config. additionally, this new default config should also be in this pr

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/171)* status: all files reviewed, 2 unresolved discussions (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`crates/papyrus_network/src/lib.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/171#-O2yZbK_2G_Sc--TEhwY:-O2yf8X6-BkjTqjzkraN:b-me2it0) ([raw file](https://github.com/starkware-libs/sequencer/blob/c0c83ada7c2af5d7fb2d0d52c2091b9dd0feb566/crates/papyrus_network/src/lib.rs#L92)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

need to include the new variable in the default config. to do so you'll need to run the dump config script that includes a call to dump which will use this func to dump your new variable into the config. additionally, this new default config should also be in this pr
</blockquote></details>

@eitanm-starkware I think it happens automatically because this config has a pointer. Otherwise the CI should've failed, right?
___
*[`crates/papyrus_network/src/mixed_behaviour.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/171#-O2yfVPr-SYQzGPelUnD:-O2yfVPr-SYQzGPelUnE:b-s3r2pt) ([raw file](https://github.com/starkware-libs/sequencer/blob/c0c83ada7c2af5d7fb2d0d52c2091b9dd0feb566/crates/papyrus_network/src/mixed_behaviour.rs#L71)):*
> ```XML
>         kademlia_config.set_protocol_names(vec![
>             StreamProtocol::try_from_owned(format!("/starknet/kad/{}/1.0.0", chain_id))
>                 .expect("Failed to create kademlia protocol"),
> ```

Change this error message. It should reflect your assumption that the code should never fail. Something like "Failed to create StreamProtocol from a string that starts with /"

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/171#-:-O32_WHMEyDDUzfXx2a4:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @AlonLStarkWare and @eitanm-starkware)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/171#-O32_Idf5NxZqQ5lHxo_):*
Make sure to merge with squash & merge and not rebase & merge if you have multiple commits

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/171#-:-O3D1mhQ52AvJwaE5d3L:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @AlonLStarkWare and @eitanm-starkware)

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/171)* status: all files reviewed, 2 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/mixed_behaviour.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/171#-O2yfVPr-SYQzGPelUnD:-O32huBA1nPQiXi3oS-f:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c0c83ada7c2af5d7fb2d0d52c2091b9dd0feb566/crates/papyrus_network/src/mixed_behaviour.rs#L71)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change this error message. It should reflect your assumption that the code should never fail. Something like "Failed to create StreamProtocol from a string that starts with /"
</blockquote></details>

Done.

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/171)* status: all files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/lib.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/171#-O2yZbK_2G_Sc--TEhwY:-O3DDiNYAho9V1KeKLN_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c0c83ada7c2af5d7fb2d0d52c2091b9dd0feb566/crates/papyrus_network/src/lib.rs#L92)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

@eitanm-starkware I think it happens automatically because this config has a pointer. Otherwise the CI should've failed, right?
</blockquote></details>

Done.

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/171#-:-O3RF9560JcWBV-WgN5v:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Review by AlonLStarkWare — COMMENTED** [review]
> Reviewed 6 of 8 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/171)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Review by ShahakShama — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/171)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r5, 4 of 4 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/171)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 565 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/171#-O3l-urt4QvBUjwzRo-6:-O3l-urt4QvBUjwzRo-7:b-4z9aoe) ([raw file](https://github.com/starkware-libs/sequencer/blob/df1289d4d0b0331dd37383636bc78f6dffaa72af/crates/papyrus_network/src/network_manager/mod.rs#L565)):*
> ```XML
>                 bootstrap_peer_multiaddr.clone(),
>                 sqmr::Config { session_timeout },
>                 chain_id.clone(),
> ```

Why clone? this is the only place you use this value

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/171#-:-O4-FC_X-MVAS8hhLSi7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Pull request merged**
