### PR TITLE
feat(sync): create transaction protocol

### PR DESCRIPTION
**Pull request by eitanm-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/298)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/298)* status: all files reviewed, 5 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_p2p_sync/src/client/mod.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/298#-O3S3JhF7d1SAUcBIFeZ:-O3S3JhG91D2TfLReczK:bf0e9z8) ([raw file](https://github.com/starkware-libs/sequencer/blob/9eb296bf8e8e29d8badd7e164acce1b8bfaae154/crates/papyrus_p2p_sync/src/client/mod.rs#L77)):*
> ```XML
>                 "num_transactions_per_query",
>                 &self.num_transactions_per_query,
>                 "The maximum amount of transactions to ask from peers in each iteration.",
> ```

"of transactions to ask from peers" -> "of blocks to ask their transactions from peers"
___
*[`crates/papyrus_p2p_sync/src/client/mod.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/298#-O3S49Th7x9J8veXmML3:-O3S49Th7x9J8veXmML4:b-pyhuka) ([raw file](https://github.com/starkware-libs/sequencer/blob/9eb296bf8e8e29d8badd7e164acce1b8bfaae154/crates/papyrus_p2p_sync/src/client/mod.rs#L133)):*
> ```XML
>     #[error("Expected to receive {expected} transactions from the network. got {actual} instead.")]
>     // TODO(eitan): Remove this and report to network on invalid data once that's possible.
>     WrongNumberOfTransactions { expected: usize, actual: usize },
> ```

Change this to NotEnoughTransactions and add a block_number field. Change the message to:
Expected to receive {expected} transactions for block {block_number} from the network. Got {actual} instead
___
*[`crates/papyrus_p2p_sync/src/client/mod.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/298#-O3S6YnfEfOMsvmjXtAE:-O3S6YnfEfOMsvmjXtAF:b-ixcm56) ([raw file](https://github.com/starkware-libs/sequencer/blob/9eb296bf8e8e29d8badd7e164acce1b8bfaae154/crates/papyrus_p2p_sync/src/client/mod.rs#L244)):*
> ```XML
>             config.stop_sync_at_block_number,
>         );
>         let transaction_stream = TransactionStreamFactory::create_stream(
> ```

newline before this line
___
*[`crates/papyrus_p2p_sync/src/client/transaction.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/298#-O3S8POBD9dMQ4qsuJpH:-O3S8POBD9dMQ4qsuJpI:b-w59vch) ([raw file](https://github.com/starkware-libs/sequencer/blob/9eb296bf8e8e29d8badd7e164acce1b8bfaae154/crates/papyrus_p2p_sync/src/client/transaction.rs#L25)):*
> ```XML
> 
> impl DataStreamBuilder<(Transaction, TransactionOutput)> for TransactionStreamFactory {
>     type Output = (BlockBody, BlockNumber);
> ```

Add TODO to either download the events or split their write in the storage
___
*[`crates/papyrus_p2p_sync/src/client/transaction.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/298#-O3SFPFR40Fad2WejgII:-O3SFPFSBPATuvhAxgui:bbmehj2) ([raw file](https://github.com/starkware-libs/sequencer/blob/9eb296bf8e8e29d8badd7e164acce1b8bfaae154/crates/papyrus_p2p_sync/src/client/transaction.rs#L62)):*
> ```XML
>                 // TODO(eitan): Add actual transaction hashes to the block body by reteiving chainid
>                 // from storage. Currently assuming mainnet.
>                 let random_transaction_hash = transaction
> ```

This is not a random hash. I prefer you put some truly random hash rather than calculating.
The TODO should be to add transaction hash to the protobuf

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/298)* status: all files reviewed, 5 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/client/mod.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/298#-O3S3JhF7d1SAUcBIFeZ:-O3SYxpf9GqPCu63udQq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9eb296bf8e8e29d8badd7e164acce1b8bfaae154/crates/papyrus_p2p_sync/src/client/mod.rs#L77)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

"of transactions to ask from peers" -> "of blocks to ask their transactions from peers"
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/mod.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/298#-O3S49Th7x9J8veXmML3:-O3SZRMU3jO-a-4Rl-Jd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9eb296bf8e8e29d8badd7e164acce1b8bfaae154/crates/papyrus_p2p_sync/src/client/mod.rs#L133)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change this to NotEnoughTransactions and add a block_number field. Change the message to:
Expected to receive {expected} transactions for block {block_number} from the network. Got {actual} instead
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/mod.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/298#-O3S6YnfEfOMsvmjXtAE:-O3SZWak-gpkvbE4rsdo:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9eb296bf8e8e29d8badd7e164acce1b8bfaae154/crates/papyrus_p2p_sync/src/client/mod.rs#L244)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

newline before this line
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/transaction.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/298#-O3S8POBD9dMQ4qsuJpH:-O3SbB_m3J6jogtHWWcC:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9eb296bf8e8e29d8badd7e164acce1b8bfaae154/crates/papyrus_p2p_sync/src/client/transaction.rs#L25)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to either download the events or split their write in the storage
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/transaction.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/298#-O3SFPFR40Fad2WejgII:-O3SbK7w3kmRQGwAuFe8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9eb296bf8e8e29d8badd7e164acce1b8bfaae154/crates/papyrus_p2p_sync/src/client/transaction.rs#L62)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is not a random hash. I prefer you put some truly random hash rather than calculating.
The TODO should be to add transaction hash to the protobuf
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/298#-:-O3Sgfya3sOq5dRqrmOA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/298#-:-O3W_vl8EWaO6Gesw0Pn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/298#-:-O3grjR90jsK3i_LH3TD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Pull request merged**
