### PR TITLE
feat(consensus): use an enum to make a StreamMessage flag as Fin

### PR DESCRIPTION
**Pull request by guy-starkware**
This PR removes the boolean "fin" on StreamMessage, and instead turns the "message" part to be an enum that can contain either `Content` variant (a generic `<T>`) or a `Fin` variant that contains nothing. 

This mean the last message to be sent doesn't have any content (e.g., no transactions) but will only contain the fin variant that flags the StreamHandler to close the channel and end the stream. 

In the case of the Consensus, the ProposalFin message will be followed by a separate message that only marks the end of the stream.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1048)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1048)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/papyrus_protobuf/src/consensus.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1048#-O7xd9g_5T2t5MY0akRl:-O7xd9g_5T2t5MY0akRm:bcy8j6) ([raw file](https://github.com/starkware-libs/sequencer/blob/fafcb6046d80d66dc8f7e427917b891c5b7f33b4/crates/papyrus_protobuf/src/consensus.rs#L50)):*
> ```XML
> 
> #[derive(Debug, Clone, Hash, Eq, PartialEq)]
> pub enum StreamMessageOption<T> {
> ```

Rename to StreamMessageContent or StreamMessageBody
___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1048#-O7xdWwt2zyp1pz3IMuo:-O7xdWwt2zyp1pz3IMup:b-ecr2fg) ([raw file](https://github.com/starkware-libs/sequencer/blob/fafcb6046d80d66dc8f7e427917b891c5b7f33b4/crates/papyrus_protobuf/src/converters/consensus_test.rs#L67)):*
> ```XML
> impl GetTestInstance for StreamMessage<ConsensusMessage> {
>     fn get_test_instance(rng: &mut rand_chacha::ChaCha8Rng) -> Self {
>         let message = if rng.gen_bool(0.5) {
> ```

Why not use the auto impl macro?
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1048#-O7xcrYu9x3LI2_dxDWQ:-O7xcrYv5MWQJcOZ9UQb:b-xi3z4k) ([raw file](https://github.com/starkware-libs/sequencer/blob/fafcb6046d80d66dc8f7e427917b891c5b7f33b4/crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto#L41)):*
> ```proto
>     oneof message {
>         bytes content = 1;
>         bool fin = 2;
> ```

bool -> Fin (Fin is defined in common.proto)

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1048)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_protobuf/src/consensus.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1048#-O7xd9g_5T2t5MY0akRl:-O7xe6os4Zq53FnzJO1m:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/fafcb6046d80d66dc8f7e427917b891c5b7f33b4/crates/papyrus_protobuf/src/consensus.rs#L50)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to StreamMessageContent or StreamMessageBody
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1048#-O7xdWwt2zyp1pz3IMuo:-O7xeLhG6p3-k8foCbsV:b-plv6uv) ([raw file](https://github.com/starkware-libs/sequencer/blob/fafcb6046d80d66dc8f7e427917b891c5b7f33b4/crates/papyrus_protobuf/src/converters/consensus_test.rs#L67)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why not use the auto impl macro?
</blockquote></details>

I was not able to make it work with a generic type. I'll add a comment in the code. 
___
*[`crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1048#-O7xcrYu9x3LI2_dxDWQ:-O7xejj0ArYr7LhqEe6C:b2o3l4z) ([raw file](https://github.com/starkware-libs/sequencer/blob/fafcb6046d80d66dc8f7e427917b891c5b7f33b4/crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto#L41)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

bool -> Fin (Fin is defined in common.proto)
</blockquote></details>

Got it!

**Review by ShahakShama — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1048#-:-O8620G355JeVOxGp9at:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus.rs` line 138 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1048#-O862Sl21vtWrOXnqzZZ:-O862Sl34uQ2A3R-EZ56:be9rtfd) ([raw file](https://github.com/starkware-libs/sequencer/blob/2c2b6465a5d7d03ddd0d0b5db4634fcd29586690/crates/papyrus_protobuf/src/converters/consensus.rs#L138)):*
> ```XML
>                 } => StreamMessageBody::Content(message.try_into()?),
>                 protobuf::StreamMessage {
>                     message: Some(protobuf::stream_message::Message::Fin(_)),
> ```

IMO it's clearer if you write the thing instead of _ (it only has one option after the type change in .proto
___
*[`crates/papyrus_protobuf/src/converters/consensus.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1048#-O862IxCBO7qhvAlww_m:-O862IxCBO7qhvAlww_n:bx53oja) ([raw file](https://github.com/starkware-libs/sequencer/blob/2c2b6465a5d7d03ddd0d0b5db4634fcd29586690/crates/papyrus_protobuf/src/converters/consensus.rs#L164)):*
> ```XML
>                 } => Some(protobuf::stream_message::Message::Content(message.into())),
>                 StreamMessage { message: StreamMessageBody::Fin, stream_id: _, message_id: _ } => {
>                     None
> ```

Shouldn't this be Some(protobuf::stream_message::Message::Fin)

**Review by guy-starkware — COMMENTED** [review]
I also removed the comments on this line in protobuf/common:
```
// mark the end of a stream of messages
// TBD: may not be required if we open a stream per request.
message Fin {}
```

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1048#-:-O86HTTu7XwUfnKvx-Ag:b-txwb6p)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_protobuf/src/converters/consensus.rs` line 138 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1048#-O862Sl21vtWrOXnqzZZ:-O86HRJMELr9pO34wtH7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2c2b6465a5d7d03ddd0d0b5db4634fcd29586690/crates/papyrus_protobuf/src/converters/consensus.rs#L138)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

IMO it's clearer if you write the thing instead of _ (it only has one option after the type change in .proto
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/converters/consensus.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1048#-O862IxCBO7qhvAlww_m:-O86HReW4JZ3ehchaNpC:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2c2b6465a5d7d03ddd0d0b5db4634fcd29586690/crates/papyrus_protobuf/src/converters/consensus.rs#L164)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Shouldn't this be Some(protobuf::stream_message::Message::Fin)
</blockquote></details>

Done.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 5 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1048)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Pull request merged**
