### PR TITLE
feat(committer): compute contracts trie and storage tries in parallel

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/471)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/471#-:-O4K8eK92VBBAg-ZatgK:b-hz3kb8)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/471)* status: all files reviewed, 8 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/471#-O4KDETU7rCOns0XdLHF:-O4KDETU7rCOns0XdLHG:bsrk9hi) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf73351bbac8d5f9cf57c488ef470c2d77875d69/crates/starknet_committer/src/forest/filled_forest.rs#L87)):*
> ```XML
>         Ok(Self {
>             storage_tries: storage_tries
>                 .expect("Missing storage tries.")
> ```

see prev PR: `storage_tries` should not be `Option`



_Code quote:_
```XML
            storage_tries: storage_tries
                .expect("Missing storage tries.")
```
___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/471#-O4KDyTbDozFG8QOAOi0:-O4KDyTbDozFG8QOAOi1:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf73351bbac8d5f9cf57c488ef470c2d77875d69/crates/starknet_committer/src/forest/filled_forest.rs#L104)):*
> ```XML
>             LeafModifications<StarknetStorageValue>,
>         >,
>         mut contract_address_to_storage_trie: HashMap<ContractAddress, UpdatedSkeletonTreeImpl>,
> ```





_Suggestion:_
```XML
contract_address_to_storage_skeleton
```
___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/471#-O4KE4mV4Rgl3YFgyWH0:-O4KE4mV4Rgl3YFgyWH1:bxy7da8) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf73351bbac8d5f9cf57c488ef470c2d77875d69/crates/starknet_committer/src/forest/filled_forest.rs#L115)):*
> ```XML
>         // `contract_address_to_storage_updates` includes all modified contracts, even those with
>         // unmodified storage, see StateDiff::actual_storage_updates().
>         for (contract_address, storage_updates) in contract_address_to_storage_updates {
> ```

using `iter().map().collect()` is more rusty than a for loop (non-blocking though)



_Code quote:_
```XML
for (contract_address, storage_updates) in contract_address_to_storage_updates {
```
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/471#-O4KEicW4yj-SIcTtKyV:-O4KEicW4yj-SIcTtKyW:b-vv0zrv) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf73351bbac8d5f9cf57c488ef470c2d77875d69/crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs#L108)):*
> ```XML
>     fn remove_arc_mutex_and_option<V>(
>         hash_map_in: Arc<HashMap<NodeIndex, Mutex<Option<V>>>>,
>         fail_on_none_value: bool,
> ```

why would this be false? why is this needed?



_Code quote:_
```XML
fail_on_none_value: bool,
```
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/471#-O4KEbBb7IGyumwoFgJ2:-O4KEbBb7IGyumwoFgJ3:bgrbas3) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf73351bbac8d5f9cf57c488ef470c2d77875d69/crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs#L113)):*
> ```XML
>         for (key, value) in Arc::into_inner(hash_map_in)
>             .unwrap_or_else(|| panic!("Cannot retrieve hashmap from Arc."))
>         {
> ```

why is this needed now? why not `hash_map_in.iter()`?



_Code quote:_
```XML
        for (key, value) in Arc::into_inner(hash_map_in)
            .unwrap_or_else(|| panic!("Cannot retrieve hashmap from Arc."))
        {
```
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/471#-O4KErb_ErY3tkIuUgQF:-O4KErb_ErY3tkIuUgQG:bylq1ct) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf73351bbac8d5f9cf57c488ef470c2d77875d69/crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs#L131)):*
> ```XML
>     }
> 
>     fn wrap_leaf_inputs(
> ```

... or something more informative



_Suggestion:_
```XML
wrap_leaf_inputs_for_internal_mutability
```
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/471#-O4KFFZRDc3L-PC0pk8f:-O4KFFZRDc3L-PC0pk8g:bwwt0hs) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf73351bbac8d5f9cf57c488ef470c2d77875d69/crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs#L143)):*
> ```XML
>         leaf_index_to_leaf_input: Arc<HashMap<NodeIndex, Mutex<Option<L::I>>>>,
>         index: NodeIndex,
>     ) -> FilledTreeResult<(L, Option<L::O>)> {
> ```

what if we decide that: leaves that are created directly from modifications, return the "default" instance of their output type?
that way you can remove the Option here



_Suggestion:_
```XML
FilledTreeResult<(L, L::O)
```
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/471#-O4KGKYz2npoE8ArCl46:-O4KGKYz2npoE8ArCl47:b-wflswe) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf73351bbac8d5f9cf57c488ef470c2d77875d69/crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs#L291)):*
> ```XML
>             Arc::new(updated_skeleton),
>             NodeIndex::ROOT,
>             Arc::new(None),
> ```

Should you use `Option<Arc<...>>` instead of `Arc<Option<...>>` in the signature? this looks kinda silly



_Code quote:_
```XML
Arc::new(None),
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/471)* status: all files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/471#-O4KDETU7rCOns0XdLHF:-O4Ze9ye7fIE_zqxOrW_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf73351bbac8d5f9cf57c488ef470c2d77875d69/crates/starknet_committer/src/forest/filled_forest.rs#L87)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see prev PR: `storage_tries` should not be `Option`
</blockquote></details>

Done.
___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/471#-O4KDyTbDozFG8QOAOi0:-O4Ze8yq26_glz1OxzBS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf73351bbac8d5f9cf57c488ef470c2d77875d69/crates/starknet_committer/src/forest/filled_forest.rs#L104)):*
> ```XML
>             LeafModifications<StarknetStorageValue>,
>         >,
>         mut contract_address_to_storage_trie: HashMap<ContractAddress, UpdatedSkeletonTreeImpl>,
> ```

Done.
___
*[`crates/starknet_committer/src/forest/filled_forest.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/471#-O4KE4mV4Rgl3YFgyWH0:-O4ZeK9D5j48je0adcAh:b-8hjjzw) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf73351bbac8d5f9cf57c488ef470c2d77875d69/crates/starknet_committer/src/forest/filled_forest.rs#L115)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

using `iter().map().collect()` is more rusty than a for loop (non-blocking though)
</blockquote></details>

there's a lot of logic, I think a loop is cleaner here
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/471#-O4KEicW4yj-SIcTtKyV:-O4ZmihiDgawBdtwQK2z:by76xzk) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf73351bbac8d5f9cf57c488ef470c2d77875d69/crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs#L108)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why would this be false? why is this needed?
</blockquote></details>

you're right, removed
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/471#-O4KEbBb7IGyumwoFgJ2:-O4Znoo2-MxLsleeBlKM:b-qlwq0q) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf73351bbac8d5f9cf57c488ef470c2d77875d69/crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs#L113)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this needed now? why not `hash_map_in.iter()`?
</blockquote></details>

because this function `consumes` the values in the hashmap, to avoid copying them.
`.iter()` returns (by convention) references, while `into_iter()` (which is used by the `for` loop) has a version which returns the objects themselves (there's should also be a version which returns references. the version used is context dependent)
https://stackoverflow.com/questions/34733811/what-is-the-difference-between-iter-and-into-iter#:~:text=The%20iterator%20returned%20by%20into_iter,mut%20T%2C%20by%20convention.
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/471#-O4KErb_ErY3tkIuUgQF:-O4Zpn0A0cN-MiRiLBuJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf73351bbac8d5f9cf57c488ef470c2d77875d69/crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs#L131)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

... or something more informative
</blockquote></details>

Done.
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/471#-O4KFFZRDc3L-PC0pk8f:-O4Zpuij4gapr0BCxwZi:b8aw285) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf73351bbac8d5f9cf57c488ef470c2d77875d69/crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs#L143)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what if we decide that: leaves that are created directly from modifications, return the "default" instance of their output type?
that way you can remove the Option here
</blockquote></details>

But then leaf output types will have to have a default value - why is an `Option` bad in this function?
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/471#-O4KGKYz2npoE8ArCl46:-O4_MLBX32jjxAbawfwz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf73351bbac8d5f9cf57c488ef470c2d77875d69/crates/starknet_patricia/src/patricia_merkle_tree/filled_tree/tree.rs#L291)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Should you use `Option<Arc<...>>` instead of `Arc<Option<...>>` in the signature? this looks kinda silly
</blockquote></details>

Done.

**Review by amosStarkware — COMMENTED** [review]
@dorimedini-starkware please review the following PRs instead of this one:
https://reviewable.io/reviews/starkware-libs/sequencer/494
https://reviewable.io/reviews/starkware-libs/sequencer/495

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/471#-:-O4_pbrzAPqbRvWaU_dm:bvge3pp)* status: 4 of 9 files reviewed, 8 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

**Pull request closed without merging**
