### PR TITLE
feat(ci): standalone tests (per-crate)

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/783)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
Does this have a performance impact?
I think I saw the compiler team do something similar but used parallelization, not that I'm saying that it's worth paralellizing from the start, I just want to know if this will slow things down

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/783#-:-O6q48j71UHxOVZI7ETd:b-ak4k4e)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
are you referring to 
1. running standalone tests in parallel?
2. CI performance?

for (1), I think each `cargo test` will wait for the build dir lock of some other process before compiling and running the specific crate's test, so how would you parallelize?
for (2), this is on post-merge, and we said we would start with this and check the impact on CI: if it's ok then cool, if not we will make this a scheduled cronjob (nightly)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/783#-:-O6q84Oz9XaR1K-cu6Gh:bsds1mb)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
1. in their case they write out the crates explicitly; using a python script we can catch new crates added to the workspace without (a) being aware or (b) extra work
2. caching won't work because different crates require different feature activation (that's the point)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/783#-:-O7decbK1wuZysPwP6gD:b-qm6pzk)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by giladchase — COMMENTED** [review]
1. That's two different things. (a) is a great thing to have, regardless of performance of the suite. But (b) needs benchmarking I think, that is, if cairo's way of "run everything in parallel" beats or is ~equiv to "run only what you must in separate processes, synchronously", then running everything is preferable probably. 

Srry I'm being a stickler here, it's just battle-scars from the pytest parallelism thing we both worked on in the past, where we ended up relying on pytest instead of trying to optimize it ourselves in a custom script (though in that case the custom script tried to parallelize, which isn't the case here, but the principle remains I think).

2. Considering how large .cargo cache gets, they might just be greedily caching everything, so for example, caching all versions of a file, if it is changed or not by toggling a feature. There is definitely some reuse, and most files are probably not cfg(feature) dependant, so can be cached.


Just to be clear, I'm not expecting anyone to actually check what cargo does under the hood, just a sanity check that what we're doing is actually improving the CI runtime (independently from point (a), which can be merged as is I think)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/783#-:-O7hYZraDDbwJ5NyVue_:b-zcs5o1)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
hmmm... should I just `asyncio.gather` the loop `for package in crates`?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/783#-:-O7hvh0G2RUqJm8WDLq7:b-3k5xrp)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request closed without merging**
