### PR TITLE
feat(consensus): proposer rotates across validators

### PR DESCRIPTION
**Pull request by matan-starkware**

### CODE REVIEW

**Comment by matan-starkware** [comment]
* **#2405** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2405?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2405?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by asmaastarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2405)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2405)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2405#-ODAelXj67LCH4jycZn4:-ODAelXj67LCH4jycZn5:bayxily) ([raw file](https://github.com/starkware-libs/sequencer/blob/195d20ec763d47997ea7a74bb142ef11f8a1b3cc/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L214)):*
> ```XML
> 
>     fn proposer(&self, height: BlockNumber, round: Round) -> ValidatorId {
>         let height: usize = height.0.try_into().expect("Cannot convert to usize");
> ```

Consider using [recommended message style](https://doc.rust-lang.org/std/option/enum.Option.html#recommended-message-style)



_Code quote:_
```XML
Cannot convert to usize
```

**Comment by matan-starkware** [comment]
### Merge activity

* **Dec 3, 4:31 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2405).

**Pull request merged**
