### PR TITLE
chore(starknet_integration_tests): use available ports for create config (unused)

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #2796
- #2795
- #2794
- #2789
- #2788
- #2787
- #2786 ⬅
- #2781
- #2780

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ShahakShama — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2786)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/flow_test_setup.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2786#-OETG2i6BfsP2Y3WkvYy:-OETG2i6BfsP2Y3WkvYz:b-949x18) ([raw file](https://github.com/starkware-libs/sequencer/blob/34b194ac6ab548ddbdd94dd6225f7ae4ef5670e7/crates/starknet_integration_tests/src/flow_test_setup.rs#L69)):*
> ```XML
>             sequencer_0_consensus_manager_config,
>             sequencer_0_mempool_p2p_config,
>             AvailablePorts::new(test_unique_index, 0),
> ```

You don't really need the instance index if this is where you use it, you can just pass a &mut to the same AvailablePorts instance and the second call will continue from where the first call left of

**Review by ShahakShama — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2786)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2786)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2786)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#2796](https://github.com/starkware-libs/sequencer/pull/2796)

**Pull request closed without merging**
