### PR TITLE
feat(consensus): rename proposal channels in preparation for adding voting

### PR DESCRIPTION
**Pull request by matan-starkware**

### CODE REVIEW

**Comment by matan-starkware** [comment]
* **#2393** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2393?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2392** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2392?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2392?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2392#-:-OD5gV3Y0ojUoIqpV1mN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by dan-starkware — COMMENTED** [review]
lgtm,
Just make sure this does not conflict with Guy's work

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2392#-:-OD6-L3PDoOG-izq5ia6:b5mchou)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Comment by matan-starkware** [comment]
### Merge activity

* **Dec 2, 7:02 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2392).

**Pull request merged**
