### PR TITLE
feat(blockifier): add `NativeSyscallHandler`

### PR DESCRIPTION
**Pull request by varex83**
This PR is a copy of https://github.com/starkware-libs/sequencer/pull/549 but with changed "from" branch

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/621)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/621)* status: 1 of 5 files reviewed, all discussions resolved

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/621)* status: 2 of 5 files reviewed, all discussions resolved

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/621)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @varex83)

___
*[`crates/blockifier/src/execution/native/utils.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/621#-O5wl5XLBruyQJwstLkp:-O5wl5XLBruyQJwstLkq:b-e14qn7) ([raw file](https://github.com/starkware-libs/sequencer/blob/15342e5d702f10880c596c42aaf6fd61541de445/crates/blockifier/src/execution/native/utils.rs#L17)):*
> ```XML
> 
> pub fn encode_str_as_felts(msg: &str) -> Vec<Felt> {
>     const CHUNK_SIZE: usize = 32;
> ```

Are these methods only for error handling, or will they have another usage in future prs?

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/621)* status: 2 of 5 files reviewed, all discussions resolved

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/621)* status: all files reviewed, 7 unresolved discussions (waiting on @varex83)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/621#-O7AQHui3zfAuCVpEsV3:-O7AQHui3zfAuCVpEsV4:btdaxks) ([raw file](https://github.com/starkware-libs/sequencer/blob/15342e5d702f10880c596c42aaf6fd61541de445/crates/blockifier/src/execution/native/syscall_handler.rs#L29)):*
> ```XML
>     pub state: &'state mut dyn State,
>     pub execution_resources: &'state mut ExecutionResources,
>     pub execution_context: &'state mut EntryPointExecutionContext,
> ```

For consistency



_Suggestion:_
```XML
    pub resources: &'state mut ExecutionResources,
    pub context: &'state mut EntryPointExecutionContext,
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/621#-O79o1sd4ssuzjMFac8Q:-O79o1sd4ssuzjMFac8R:b-7zi8ni) ([raw file](https://github.com/starkware-libs/sequencer/blob/15342e5d702f10880c596c42aaf6fd61541de445/crates/blockifier/src/execution/native/syscall_handler.rs#L34)):*
> ```XML
>     pub caller_address: ContractAddress,
>     pub contract_address: ContractAddress,
>     pub entry_point_selector: Felt,
> ```

WDYT?



_Suggestion:_
```XML
    pub call: CallEntryPoint,
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 35 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/621#-O7AP5DS3T9wzkChgvod:-O7AP5DS3T9wzkChgvoe:b-qnz7y8) ([raw file](https://github.com/starkware-libs/sequencer/blob/15342e5d702f10880c596c42aaf6fd61541de445/crates/blockifier/src/execution/native/syscall_handler.rs#L35)):*
> ```XML
>     pub contract_address: ContractAddress,
>     pub entry_point_selector: Felt,
> ```

Writing here for the record additional field of the cairo1 vm hint proccessor:
`read_only_segments`
`secp256k\r1_hint_processor`
`sha256_segment_end_ptr`
`hints`
`execution_info_ptr`
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/621#-O79ofnP-NLBR1Dp8Hl1:-O79ofnP-NLBR1Dp8Hl2:btdaxks) ([raw file](https://github.com/starkware-libs/sequencer/blob/15342e5d702f10880c596c42aaf6fd61541de445/crates/blockifier/src/execution/native/syscall_handler.rs#L43)):*
> ```XML
>     // Additional execution result info.
>     pub storage_read_values: Vec<Felt>,
>     pub accessed_storage_keys: HashSet<StorageKey, RandomState>,
> ```

For consistency



_Suggestion:_
```XML
    // Additional information gathered during execution.
    pub read_values: Vec<Felt>,
    pub accessed_keys: HashSet<StorageKey, RandomState>,
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/621#-O7AR9rr3iLF7ozeCslU:-O7AR9rs56sWaJreYMIi:b18sqws) ([raw file](https://github.com/starkware-libs/sequencer/blob/15342e5d702f10880c596c42aaf6fd61541de445/crates/blockifier/src/execution/native/syscall_handler.rs#L73)):*
> ```XML
>         &mut self,
>         entry_point: CallEntryPoint,
>         remaining_gas: &mut u128,
> ```

Possible? For consistency
Than you don't need the method `update_remaining_gas`



_Suggestion:_
```XML
        remaining_gas: &mut u64,
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/621#-O7AQncC1TquVC0M7lQn:-O7AQncC1TquVC0M7lQo:bntmziv) ([raw file](https://github.com/starkware-libs/sequencer/blob/15342e5d702f10880c596c42aaf6fd61541de445/crates/blockifier/src/execution/native/syscall_handler.rs#L89)):*
> ```XML
>         self.inner_calls.push(call_info.clone());
> 
>         Ok(call_info)
> ```

Can you please explain what is the call info used for?



_Code quote:_
```XML
        Ok(call_info)
```
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 117 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/621#-O7AS03U8JSL1oMF0Ry_:-O7AS03V6jqJ6IvekYkz:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/15342e5d702f10880c596c42aaf6fd61541de445/crates/blockifier/src/execution/native/syscall_handler.rs#L117)):*
> ```XML
>         if *remaining_gas < required_gas {
>             // Out of gas failure.
>             return Err(vec![Felt::from_hex(OUT_OF_GAS_ERROR).unwrap()]);
> ```





_Suggestion:_
```XML
return Err(vec![Felt::from_hex(OUT_OF_GAS_ERROR).expect("An informative error message")]
```

**Review by varex83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/621)* status: all files reviewed, 5 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/621#-O79o1sd4ssuzjMFac8Q:-O7EvKtIDRkFBfZFa2cZ:bp9sbg9) ([raw file](https://github.com/starkware-libs/sequencer/blob/15342e5d702f10880c596c42aaf6fd61541de445/crates/blockifier/src/execution/native/syscall_handler.rs#L34)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

I would like to keep things like they are because the current approach will cover all the needed fields, so we don't store extra unnecessary things, and also it will keep getting those fields much simpler (without `.call.<...>`)
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/621#-O79ofnP-NLBR1Dp8Hl1:-O7EvI2i4LQRnJwz39Sx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/15342e5d702f10880c596c42aaf6fd61541de445/crates/blockifier/src/execution/native/syscall_handler.rs#L43)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

For consistency
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/621#-O7AR9rr3iLF7ozeCslU:-O7Eu99f4rrCUdw9Z3El:brl1wtk) ([raw file](https://github.com/starkware-libs/sequencer/blob/15342e5d702f10880c596c42aaf6fd61541de445/crates/blockifier/src/execution/native/syscall_handler.rs#L73)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Possible? For consistency
Than you don't need the method `update_remaining_gas`
</blockquote></details>

We can't do it in that way because, in any case, we need to convert the u128 pointer and to make it work correctly we utilize the `update_remaining_gas` function, converting with the `u64::try_from(...)` will create a new integer losing the old pointer
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 117 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/621#-O7AS03U8JSL1oMF0Ry_:-O7EvD3L2OphKc4osA_K:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/15342e5d702f10880c596c42aaf6fd61541de445/crates/blockifier/src/execution/native/syscall_handler.rs#L117)):*
> ```XML
>         if *remaining_gas < required_gas {
>             // Out of gas failure.
>             return Err(vec![Felt::from_hex(OUT_OF_GAS_ERROR).unwrap()]);
> ```

Done.

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/621)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @noaov1 and @varex83)

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/621)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @varex83)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/621#-O7AR9rr3iLF7ozeCslU:-O7SLHOE-opnVONUvfHk:bzacsys) ([raw file](https://github.com/starkware-libs/sequencer/blob/dba8dd20ccc979d7f8562a8fd545e7687ae727af/crates/blockifier/src/execution/native/syscall_handler.rs#L73)):*
> we need to convert the u128 pointer

Where is it done?

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/621)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @varex83)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 121 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/621#-O7c3iCR5gjR4VECn8xb:-O7c3iCR5gjR4VECn8xc:b-nd7leo) ([raw file](https://github.com/starkware-libs/sequencer/blob/5102a32fd690aadd8d93bfa856b58399cef397a1/crates/blockifier/src/execution/native/syscall_handler.rs#L121)):*
> ```XML
>             return Err(vec![
>                 Felt::from_hex(OUT_OF_GAS_ERROR)
>                     .expect("Failed to parse OUT_OF_GAS_ERROR hex string"),
> ```

Note to self: in the vm syscall handler we return an error in case the conversion failed.



_Code quote:_
```XML
                Felt::from_hex(OUT_OF_GAS_ERROR)
                    .expect("Failed to parse OUT_OF_GAS_ERROR hex string"),
```
___
*[`crates/blockifier/src/execution/native/utils.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/621#-O5wl5XLBruyQJwstLkp:-O7cQ8TY4WckaNoWFYS8:b-y9a44u) ([raw file](https://github.com/starkware-libs/sequencer/blob/dba8dd20ccc979d7f8562a8fd545e7687ae727af/crates/blockifier/src/execution/native/utils.rs#L17)):*
<details><summary><i>Previously, varex83 (Bohdan Ohorodnii) wrote…</i></summary><blockquote>

Yes, it will be used in the future PRs for the error handling, since we can only return errors as vector of felt's due to `NativeSyscallHandler` trait bounds
</blockquote></details>

Why are those methods needed? We convert each specific error message separately, [e.g.](https://github.com/starkware-libs/sequencer/blob/d095a9d1392a7a3ad2bb9354fdc813d08edafb62/crates/blockifier/src/execution/syscalls/mod.rs#L417).
___
*[`crates/blockifier/src/execution/native/utils.rs` line 17 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/621#-O7cMpch73krfASPbB11:-O7cMpch73krfASPbB12:b-ohuij4) ([raw file](https://github.com/starkware-libs/sequencer/blob/5102a32fd690aadd8d93bfa856b58399cef397a1/crates/blockifier/src/execution/native/utils.rs#L17)):*
> ```XML
> 
> pub fn encode_str_as_felts(msg: &str) -> Vec<Felt> {
>     const CHUNK_SIZE: usize = 32;
> ```

Can you please explain? Why 32?



_Code quote:_
```XML
const CHUNK_SIZE: usize = 32;
```

**Pull request closed without merging**
