### PR TITLE
feat(sequencing): add cende module and main types

### PR DESCRIPTION
**Pull request by DvirYo-starkware**

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2714)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEJWy1h2rd2yCWMv0OK:-OEJrQjw7-1ndcrMljGf:b-s5gjqt) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d8e3d9a80b00852d4746175ec9a4a4c6b8b8053/crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs#L12)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

not sure I understand,
so you mean when transforming to fully decentralized?
</blockquote></details>

In the next PR I will use those types in consensus so will not get cllipy unused types warning
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEJXG_S4dSNUWAwCKQr:-OEJt1usAsDX6qKw950W:b-hfpv0l) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d8e3d9a80b00852d4746175ec9a4a4c6b8b8053/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L11)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why clone?
</blockquote></details>

removed
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEJcOEjAiWpvKjjnd-2:-OEJrhQ04Ywv_rAi5BVd:bhbct88) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d8e3d9a80b00852d4746175ec9a4a4c6b8b8053/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L20)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

is this variable intended to communicate when the writing to AS is done?
if so, consider using a oneshot channel
</blockquote></details>

This is a bit more complex without any advantages. If the task is done and the sender is dropped, when trying to read from the receiver, an error will be returned (at least, this is what I understand from the documentation).
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEJgRfA9CGdUNNjoE5E:-OEJsHnW16HanEUnnOAR:bphki9j) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d8e3d9a80b00852d4746175ec9a4a4c6b8b8053/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L53)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

doesn't this prevent from being a proposer?
doesn't this indicate an internal error that should cause panic? I assume the outer context takes care of it when receiving false?
</blockquote></details>

This prevents from being the proposer. The context will see the cell has a `false` value and will not send `ProposalFin`.
In case the node restarts, this value will be `None`, and only at the next height the node will have a valid value. It is fine.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEJh9hM6IK47QzqOqyM:-OEJsu2T3WFwK3-cJF9g:b-2zqpl5) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d8e3d9a80b00852d4746175ec9a4a4c6b8b8053/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L60)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

are these the BlockExecutionArtifacts?
</blockquote></details>

This and more structs. see line 69
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEJWrf50JaRJ2QGDB5z:-OEJt3R-B2oN3OFcAn9E:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d8e3d9a80b00852d4746175ec9a4a4c6b8b8053/crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs#L12)):*
> ```XML
> 
> /// Centralized and decentralized communication types and functionallity.
> // TODO(dvir): delte this when using the types in consensus.
> ```

done

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2714)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEOjPvaDdpkP-c60z22:-OEOjPvaDdpkP-c60z23:b-ma1jrx) ([raw file](https://github.com/starkware-libs/sequencer/blob/b38d4f983814e73f884e1638c3d9a4efa6732d17/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L23)):*
> ```XML
> 
>     // Prepares the previous height blob that will be written in the next height.
>     async fn prepare_prev_height_blob(&self, nfb: NeededForBlob);
> ```

If it is going to be written in the next height, maybe call it `prepare_blob_for_next_height`?



_Code quote:_
```XML
    // Prepares the previous height blob that will be written in the next height.
    async fn prepare_prev_height_blob(&self, nfb: NeededForBlob);
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEOialA93Yqi415QqGu:-OEOialA93Yqi415QqGv:b9edvfz) ([raw file](https://github.com/starkware-libs/sequencer/blob/b38d4f983814e73f884e1638c3d9a4efa6732d17/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L42)):*
> ```XML
> #[async_trait]
> impl CendeContext for CendeAmbassador {
>     fn write_prev_height_blob(&self) -> Arc<OnceLock<bool>> {
> ```

How is the caller is expected to use this API?
Why not make it a blocking function, and spawn it in the caller only if needed?



_Code quote:_
```XML
write_prev_height_blob(&self) -> Arc<OnceLock<bool>>
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEOkdaR77ZNCRtwcBkV:-OEOkdaR77ZNCRtwcBkW:b52iv6k) ([raw file](https://github.com/starkware-libs/sequencer/blob/b38d4f983814e73f884e1638c3d9a4efa6732d17/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L55)):*
> ```XML
>             debug!("Writing blob to Aerospike.");
>             cell.set(true).expect("Cell should be empty");
>             debug!("Blob writing to Aerospike completed.");
> ```

Set `self.prev_height_blob` to `None` if the write was successful?

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2714)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEOjPvaDdpkP-c60z22:-OEOm8Xk8rZcBNLI0YjU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b38d4f983814e73f884e1638c3d9a4efa6732d17/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L23)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

If it is going to be written in the next height, maybe call it `prepare_blob_for_next_height`?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEOialA93Yqi415QqGu:-OEOrM_Y8NuL0Nlzx85n:b-5nqn64) ([raw file](https://github.com/starkware-libs/sequencer/blob/b38d4f983814e73f884e1638c3d9a4efa6732d17/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L42)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

How is the caller is expected to use this API?
Why not make it a blocking function, and spawn it in the caller only if needed?
</blockquote></details>

The `next_height_blob` is in the `CendeAmbassador`, so there is a need to get a copy of this information from the `CendeAmbassador` before calling the inner task. In addition, there is some additional preparation that I think should be transparent for the caller   
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEOkdaR77ZNCRtwcBkV:-OEOsSB4ESFNyvo0ix4-:b-ye5lsn) ([raw file](https://github.com/starkware-libs/sequencer/blob/b38d4f983814e73f884e1638c3d9a4efa6732d17/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L55)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Set `self.prev_height_blob` to `None` if the write was successful?
</blockquote></details>

I added a to-do for that. It can be a problem if we should propose a block again at the same height for some reason (I am not sure this is possible consensus-wise). For now, I keep it like that.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2714)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEJcOEjAiWpvKjjnd-2:-OEOqkjj1HYZ2scL07kS:b-k56n1d) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d8e3d9a80b00852d4746175ec9a4a4c6b8b8053/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L20)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

This is a bit more complex without any advantages. If the task is done and the sender is dropped, when trying to read from the receiver, an error will be returned (at least, this is what I understand from the documentation).
</blockquote></details>

Afaiu. The receiver will first consume the message , and then get an error. 
see example in the docs: https://doc.servo.org/tokio/sync/oneshot/index.html

I think the code will be simpler and more self explanatory with a channel.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEOsEEZ9XPHhxTqMeU0:-OEOsEE_3g8NB4q2iSR8:b-9fbal1) ([raw file](https://github.com/starkware-libs/sequencer/blob/b38d4f983814e73f884e1638c3d9a4efa6732d17/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L52)):*
> ```XML
>                 return;
>             };
>             // TODO(dvir): write blob to AS.
> ```

this is a blocking operation, right?



_Code quote:_
```XML
// TODO(dvir): write blob to AS.
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEOsQH79yU3p8wvmB99:-OEOsQH79yU3p8wvmB9A:b-gl2na0) ([raw file](https://github.com/starkware-libs/sequencer/blob/b38d4f983814e73f884e1638c3d9a4efa6732d17/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L61)):*
> ```XML
>     }
> 
>     async fn prepare_prev_height_blob(&self, nfb: NeededForBlob) {
> ```

This is being called during the previous height, right? so during this time it is the current height



_Suggestion:_
```XML
prepare_blob_for_central_write
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2714)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEOsEEZ9XPHhxTqMeU0:-OEOtNr36wiOR4pmGN8r:bn3u2af) ([raw file](https://github.com/starkware-libs/sequencer/blob/b38d4f983814e73f884e1638c3d9a4efa6732d17/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L52)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

this is a blocking operation, right?
</blockquote></details>

maybe state it clearly in the TODO so we won't forget
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEOsQH79yU3p8wvmB99:-OEOtZAz8xtXVTQgcP1k:bbzs52s) ([raw file](https://github.com/starkware-libs/sequencer/blob/b38d4f983814e73f884e1638c3d9a4efa6732d17/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L61)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

This is being called during the previous height, right? so during this time it is the current height
</blockquote></details>

oh never mind, I see that Dafna already commented on this.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2714)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 70 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEOu7Vg1y5zmkc_UQe_:-OEOu7Vg1y5zmkc_UQea:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8468f09e17390b7b62eedb374520db1ebc3a2a92/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L70)):*
> ```XML
> 
> #[derive(Clone, Debug, Default)]
> pub(crate) struct NeededForBlob {
> ```





_Suggestion:_
```XML
BlobInput
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2714)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEJcOEjAiWpvKjjnd-2:-OEOzBe5BN8curCdxXBF:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d8e3d9a80b00852d4746175ec9a4a4c6b8b8053/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L20)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Afaiu. The receiver will first consume the message , and then get an error. 
see example in the docs: https://doc.servo.org/tokio/sync/oneshot/index.html

I think the code will be simpler and more self explanatory with a channel.
</blockquote></details>

Done
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEOialA93Yqi415QqGu:-OEOzDj59FPTugf7GOmM:b-z3wg5z) ([raw file](https://github.com/starkware-libs/sequencer/blob/b38d4f983814e73f884e1638c3d9a4efa6732d17/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L42)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

can we consume the CendeContext when calling this spawn, or should it be available for retries in case of failure?
</blockquote></details>

We can't consume. We should be able to retry.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEOsEEZ9XPHhxTqMeU0:-OEOtJ5w5WNXqtQcmMGc:b-nssgo9) ([raw file](https://github.com/starkware-libs/sequencer/blob/b38d4f983814e73f884e1638c3d9a4efa6732d17/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L52)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

maybe state it clearly in the TODO so we won't forget
</blockquote></details>

This fine.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEOsQH79yU3p8wvmB99:-OEOtRQ498X4c9tWxeof:b-yk5ekv) ([raw file](https://github.com/starkware-libs/sequencer/blob/b38d4f983814e73f884e1638c3d9a4efa6732d17/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L61)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

This is being called during the previous height, right? so during this time it is the current height
</blockquote></details>

changed to Dafna's suggestion `prepare\_blob\_for\_next\_height`

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2714)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, and @DvirYo-starkware)

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2714)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEP4DR77Cro-FWRAMxj:-OEP4DR8CIW4RQXnRB5k:b-mhb2xf) ([raw file](https://github.com/starkware-libs/sequencer/blob/679188d950c10651993d0a0dc75ab32e698f750e/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L76)):*
> ```XML
> 
> impl From<NeededForBlob> for AerospikeBlob {
>     fn from(_nfb: NeededForBlob) -> Self {
> ```

blob_input



_Code quote:_
```XML
nfb
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2714)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEP4DR77Cro-FWRAMxj:-OESWL8z01dl9pLKRA5J:b7ra53g) ([raw file](https://github.com/starkware-libs/sequencer/blob/679188d950c10651993d0a0dc75ab32e698f750e/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L76)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

blob_input
</blockquote></details>

blob_info/blob_data/needed_for_blob
anything that is not random three letters.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 70 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEOu7Vg1y5zmkc_UQe_:-OESWBQ19fhvTF_xYj7Y:byvwokl) ([raw file](https://github.com/starkware-libs/sequencer/blob/8468f09e17390b7b62eedb374520db1ebc3a2a92/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L70)):*
> ```XML
> 
> #[derive(Clone, Debug, Default)]
> pub(crate) struct NeededForBlob {
> ```

optional

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2714)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OEP4DR77Cro-FWRAMxj:-OESt-R-0Y9gjY9638ED:b-jvevw1) ([raw file](https://github.com/starkware-libs/sequencer/blob/679188d950c10651993d0a0dc75ab32e698f750e/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L76)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

blob_info/blob_data/needed_for_blob
anything that is not random three letters.
</blockquote></details>

`blob_parameters`

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2714)* status: all files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @dan-starkware)

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2714)* status: all files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @dan-starkware)

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2714)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 49 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OET70I_16Piwdlea4YW:-OET70I_16Piwdlea4YX:br1ulnt) ([raw file](https://github.com/starkware-libs/sequencer/blob/ad2309788ee3201dba3409fe0df708a7c6199184/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L49)):*
> ```XML
>             let Some(ref _blob) = *prev_height_blob.lock().await else {
>                 debug!("No blob to write to Aerospike.");
>                 sender.send(false).expect("Cell should be empty");
> ```

Please fix the expect error message here and below.



_Code quote:_
```XML
.expect("Cell should be empty");
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2714)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @dan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 49 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2714#-OET70I_16Piwdlea4YW:-OET9ui48IchKqdz-EV_:b-p4sddu) ([raw file](https://github.com/starkware-libs/sequencer/blob/ad2309788ee3201dba3409fe0df708a7c6199184/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L49)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please fix the expect error message here and below.
</blockquote></details>

I will fix this in a different PR

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2714)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
