### PR TITLE
build(blockifier): add l2_gas_price to blockinfo

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/463)

### CODE REVIEW

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/463)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @ShahakShama)

___
*[`crates/papyrus_execution/src/lib.rs` line 363 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4K00kq2Qx8dalRJaD9:-O4K00kq2Qx8dalRJaDA:bg02pt1) ([raw file](https://github.com/starkware-libs/sequencer/blob/1aa8dd37f8a3808a30e84d9eba941f8f22a2772e/crates/papyrus_execution/src/lib.rs#L363)):*
> ```XML
>             NonZeroU128::new(l1_data_gas_price.price_in_fri.0).unwrap_or(NonZeroU128::MIN),
>             NonZeroU128::MIN,
>             NonZeroU128::MIN,
> ```

I think these should come from the pending_data/block_header same way the l1 gas is



_Code quote:_
```XML
            NonZeroU128::MIN,
            NonZeroU128::MIN,
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/463)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/papyrus_execution/src/lib.rs` line 363 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4K00kq2Qx8dalRJaD9:-O4KV0GS0Xc8588KJX7B:b-pk3lz2) ([raw file](https://github.com/starkware-libs/sequencer/blob/1aa8dd37f8a3808a30e84d9eba941f8f22a2772e/crates/papyrus_execution/src/lib.rs#L363)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think these should come from the pending_data/block_header same way the l1 gas is
</blockquote></details>

@ShahakShama told me to leave a TODO for this for now (see the first revision - it doesn't compile)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 18 files at r1, 1 of 15 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/463)* status: 6 of 18 files reviewed, 5 unresolved discussions (waiting on @aner-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/blockifier/src/blockifier/block.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4Kh20o-bQ_3T4I-RZk:-O4Kh20o-bQ_3T4I-RZl:bu4w8zq) ([raw file](https://github.com/starkware-libs/sequencer/blob/88721563ffbf7657b1322c4ef1ada285f59598fb/crates/blockifier/src/blockifier/block.rs#L55)):*
> ```XML
>                 .expect("L1 to L2 price conversion error (Rust side).")
>         {
>             warn!("eth_l2_gas_price does not match expected!")
> ```

I suggest you output some numbers here: expected price, actual price, and the ratio
X2 (also below)



_Code quote:_
```XML
warn!("eth_l2_gas_price does not match expected!")
```
___
*[`crates/gateway/src/rpc_objects.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4KhKKR4z9grCVs_doq:-O4KhKKR4z9grCVs_dor:bdl8y6u) ([raw file](https://github.com/starkware-libs/sequencer/blob/88721563ffbf7657b1322c4ef1ada285f59598fb/crates/gateway/src/rpc_objects.rs#L94)):*
> ```XML
>                 parse_gas_price(self.l1_data_gas_price.price_in_fri)?,
>                 NonZeroU128::MIN,
>                 NonZeroU128::MIN,
> ```

shouldn't this be part of the block header @ShahakShama ?



_Code quote:_
```XML
                parse_gas_price(self.l1_data_gas_price.price_in_fri)?,
                NonZeroU128::MIN,
                NonZeroU128::MIN,
```
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 216 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4KhWwJCERs6YyDOK3j:-O4KhWwJCERs6YyDOK3k:b-ds5fzh) ([raw file](https://github.com/starkware-libs/sequencer/blob/88721563ffbf7657b1322c4ef1ada285f59598fb/crates/native_blockifier/src/py_state_diff.rs#L216)):*
> ```XML
>                 block_info.l2_gas_price.price_in_wei.try_into().map_err(|_| {
>                     NativeBlockifierInputError::InvalidNativeBlockifierInputError(
>                         InvalidNativeBlockifierInputError::InvalidGasPriceWei(
> ```

add a variant for this



_Suggestion:_
```XML
InvalidL2GasPriceWei
```
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 223 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4Kharh3WCtXNSqamGP:-O4Kharh3WCtXNSqamGQ:b-7ropln) ([raw file](https://github.com/starkware-libs/sequencer/blob/88721563ffbf7657b1322c4ef1ada285f59598fb/crates/native_blockifier/src/py_state_diff.rs#L223)):*
> ```XML
>                 block_info.l2_gas_price.price_in_fri.try_into().map_err(|_| {
>                     NativeBlockifierInputError::InvalidNativeBlockifierInputError(
>                         InvalidNativeBlockifierInputError::InvalidGasPriceFri(
> ```

ditto



_Suggestion:_
```XML
InvalidL2GasPriceFri
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 12 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/463)* status: all files reviewed, 5 unresolved discussions (waiting on @aner-starkware, @ShahakShama, and @TzahiTaub)

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/463)* status: 14 of 18 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware, @ShahakShama, and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4Kr4Hq3vvTLkvNZ8IO:-O4Kr4Hq3vvTLkvNZ8IP:b68ptva) (no related file):*
Python side: https://reviewable.io/reviews/starkware-industries/starkware/35733#-

___
___
*[`crates/blockifier/src/blockifier/block.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4Kh20o-bQ_3T4I-RZk:-O4Kqfr8-Tyn0MIVlO6E:bdd8oot) ([raw file](https://github.com/starkware-libs/sequencer/blob/88721563ffbf7657b1322c4ef1ada285f59598fb/crates/blockifier/src/blockifier/block.rs#L55)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I suggest you output some numbers here: expected price, actual price, and the ratio
X2 (also below)
</blockquote></details>

Why print the ratio? Did the rest.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/463)* status: all files reviewed, 11 unresolved discussions (waiting on @aner-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/blockifier/src/blockifier/block.rs` line 55 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4L7rNZ01vpLNL-hVRy:-O4L7rNZ01vpLNL-hVRz:b-e7vbht) ([raw file](https://github.com/starkware-libs/sequencer/blob/a31426c56321145af927e4416461ded3515d9310/crates/blockifier/src/blockifier/block.rs#L55)):*
> ```XML
>                 max_recursion_depth: 0,
>                 versioned_constants_base_overrides: None,
>             })
> ```

why this function...? you are not passing overrides from the caller, why call this overriding method?



_Code quote:_
```XML
            VersionedConstants::get_versioned_constants(VersionedConstantsOverrides {
                validate_max_n_steps: 0,
                max_recursion_depth: 0,
                versioned_constants_base_overrides: None,
            })
```
___
*[`crates/blockifier/src/blockifier/block.rs` line 60 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4L82jdAgU2IMoVmOsQ:-O4L82jdAgU2IMoVmOsR:b-vp3cbs) ([raw file](https://github.com/starkware-libs/sequencer/blob/a31426c56321145af927e4416461ded3515d9310/crates/blockifier/src/blockifier/block.rs#L60)):*
> ```XML
>             warn!(
>                 "eth_l2_gas_price does not match expected! eth_l2_gas_price:{}, expected:{}.",
>                 eth_l2_gas_price, expected_eth_l2_gas_price
> ```

can you inline the values? more readable



_Suggestion:_
```XML
                "eth_l2_gas_price does not match expected! eth_l2_gas_price: {eth_l2_gas_price}, expected: {expected}."
```
___
*[`crates/blockifier/src/blockifier/block.rs` line 68 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4L8CBzB0biFd8m3eGO:-O4L8CBzB0biFd8m3eGP:b-krsqec) ([raw file](https://github.com/starkware-libs/sequencer/blob/a31426c56321145af927e4416461ded3515d9310/crates/blockifier/src/blockifier/block.rs#L68)):*
> ```XML
>                 max_recursion_depth: 0,
>                 versioned_constants_base_overrides: None,
>             })
> ```

same Q



_Code quote:_
```XML
            VersionedConstants::get_versioned_constants(VersionedConstantsOverrides {
                validate_max_n_steps: 0,
                max_recursion_depth: 0,
                versioned_constants_base_overrides: None,
            })
```
___
*[`crates/blockifier/src/blockifier/block.rs` line 73 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4L8DzyAmq7jQN7_QXO:-O4L8DzyAmq7jQN7_QXP:bq6arbt) ([raw file](https://github.com/starkware-libs/sequencer/blob/a31426c56321145af927e4416461ded3515d9310/crates/blockifier/src/blockifier/block.rs#L73)):*
> ```XML
>             warn!(
>                 "strk_l2_gas_price does not match expected! strk_l2_gas_price:{}, expected:{}.",
>                 strk_l2_gas_price, expected_strk_l2_gas_price
> ```

inline printed values (see above)



_Code quote:_
```XML
                "strk_l2_gas_price does not match expected! strk_l2_gas_price:{}, expected:{}.",
                strk_l2_gas_price, expected_strk_l2_gas_price
```
___
*[`crates/blockifier/src/fee/fee_test.rs` line 152 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4L8HjJCUOFi9qq8oSx:-O4L8HjJCUOFi9qq8oSy:b-1dcx4w) ([raw file](https://github.com/starkware-libs/sequencer/blob/a31426c56321145af927e4416461ded3515d9310/crates/blockifier/src/fee/fee_test.rs#L152)):*
> ```XML
>         .try_into()
>         .unwrap(),
>     );
> ```

why use this getter with no overrides, instead of `latest_constants` or something without args?



_Code quote:_
```XML
        VersionedConstants::get_versioned_constants(VersionedConstantsOverrides {
            validate_max_n_steps: 0,
            max_recursion_depth: 0,
            versioned_constants_base_overrides: None,
        })
        .l1_to_l2_gas_price_conversion(DEFAULT_ETH_L1_GAS_PRICE)
        .try_into()
        .unwrap(),
        VersionedConstants::get_versioned_constants(VersionedConstantsOverrides {
            validate_max_n_steps: 0,
            max_recursion_depth: 0,
            versioned_constants_base_overrides: None,
        })
        .l1_to_l2_gas_price_conversion(gas_price)
        .try_into()
        .unwrap(),
    );
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 180 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4L8WB09oPckxJ--kzp:-O4L8WB09oPckxJ--kzq:b3ys4gt) ([raw file](https://github.com/starkware-libs/sequencer/blob/a31426c56321145af927e4416461ded3515d9310/crates/blockifier/src/test_utils/struct_impls.rs#L180)):*
> ```XML
>                     versioned_constants_base_overrides: None,
>                 })
>                 .l1_to_l2_gas_price_conversion(DEFAULT_STRK_L1_GAS_PRICE)
> ```

use `latest_constants` - it's equivalent, without the explicit overrides



_Code quote:_
```XML
                VersionedConstants::get_versioned_constants(VersionedConstantsOverrides {
                    validate_max_n_steps: 0,
                    max_recursion_depth: 0,
                    versioned_constants_base_overrides: None,
                })
                .l1_to_l2_gas_price_conversion(DEFAULT_ETH_L1_GAS_PRICE)
                .try_into()
                .unwrap(),
                VersionedConstants::get_versioned_constants(VersionedConstantsOverrides {
                    validate_max_n_steps: 0,
                    max_recursion_depth: 0,
                    versioned_constants_base_overrides: None,
                })
                .l1_to_l2_gas_price_conversion(DEFAULT_STRK_L1_GAS_PRICE)
```
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 179 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4L8bPz7nhycbnf4q6w:-O4L8bPz7nhycbnf4q6x:b-d3grqj) ([raw file](https://github.com/starkware-libs/sequencer/blob/a31426c56321145af927e4416461ded3515d9310/crates/native_blockifier/src/py_state_diff.rs#L179)):*
> ```XML
>                     },
>                 )
>                 .l1_to_l2_gas_price_conversion(DEFAULT_STRK_L1_GAS_PRICE),
> ```

use latest_constants



_Code quote:_
```XML
                price_in_wei: VersionedConstants::get_versioned_constants(
                    VersionedConstantsOverrides {
                        validate_max_n_steps: 0,
                        max_recursion_depth: 0,
                        versioned_constants_base_overrides: None,
                    },
                )
                .l1_to_l2_gas_price_conversion(DEFAULT_ETH_L1_GAS_PRICE),
                price_in_fri: VersionedConstants::get_versioned_constants(
                    VersionedConstantsOverrides {
                        validate_max_n_steps: 0,
                        max_recursion_depth: 0,
                        versioned_constants_base_overrides: None,
                    },
                )
                .l1_to_l2_gas_price_conversion(DEFAULT_STRK_L1_GAS_PRICE),
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/463)* status: 15 of 19 files reviewed, 11 unresolved discussions (waiting on @dorimedini-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/blockifier/src/blockifier/block.rs` line 55 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4L7rNZ01vpLNL-hVRy:-O4LUE8rBq2MAA-Sq7cd:b-nosj34) ([raw file](https://github.com/starkware-libs/sequencer/blob/a31426c56321145af927e4416461ded3515d9310/crates/blockifier/src/blockifier/block.rs#L55)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why this function...? you are not passing overrides from the caller, why call this overriding method?
</blockquote></details>

Sorry, misunderstanding on my part - I thought you asked for this change.
___
*[`crates/blockifier/src/blockifier/block.rs` line 60 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4L82jdAgU2IMoVmOsQ:-O4LVg0r-Wz8FZFYnglH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a31426c56321145af927e4416461ded3515d9310/crates/blockifier/src/blockifier/block.rs#L60)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you inline the values? more readable
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/block.rs` line 68 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4L8CBzB0biFd8m3eGO:-O4LVjAV84FK1d3K1U08:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a31426c56321145af927e4416461ded3515d9310/crates/blockifier/src/blockifier/block.rs#L68)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

same Q
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/block.rs` line 73 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4L8DzyAmq7jQN7_QXO:-O4LVkgK7IAorEI_HsTD:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a31426c56321145af927e4416461ded3515d9310/crates/blockifier/src/blockifier/block.rs#L73)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

inline printed values (see above)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/fee_test.rs` line 152 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4L8HjJCUOFi9qq8oSx:-O4LTJFh0Zgvm55_1uoG:b-nosj34) ([raw file](https://github.com/starkware-libs/sequencer/blob/a31426c56321145af927e4416461ded3515d9310/crates/blockifier/src/fee/fee_test.rs#L152)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why use this getter with no overrides, instead of `latest_constants` or something without args?
</blockquote></details>

Sorry, misunderstanding on my part - I thought you asked for this change.
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 180 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4L8WB09oPckxJ--kzp:-O4LVnKNEd1rNV4GkEE0:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a31426c56321145af927e4416461ded3515d9310/crates/blockifier/src/test_utils/struct_impls.rs#L180)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use `latest_constants` - it's equivalent, without the explicit overrides
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 216 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4KhWwJCERs6YyDOK3j:-O4LVyBKEBFmPbnWNbZm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/88721563ffbf7657b1322c4ef1ada285f59598fb/crates/native_blockifier/src/py_state_diff.rs#L216)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add a variant for this
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 223 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4Kharh3WCtXNSqamGP:-O4LVz1v8HFMBs38kpKD:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/88721563ffbf7657b1322c4ef1ada285f59598fb/crates/native_blockifier/src/py_state_diff.rs#L223)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 179 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4L8bPz7nhycbnf4q6w:-O4LVwu9EQNlt1aA4KSf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a31426c56321145af927e4416461ded3515d9310/crates/native_blockifier/src/py_state_diff.rs#L179)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use latest_constants
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/463)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @ShahakShama, and @TzahiTaub)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/463)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @ShahakShama, and @TzahiTaub)

___
*[`crates/gateway/src/rpc_objects.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4KhKKR4z9grCVs_doq:-O4dt0k19gkqcWfTvL5W:b-oltnj9) ([raw file](https://github.com/starkware-libs/sequencer/blob/88721563ffbf7657b1322c4ef1ada285f59598fb/crates/gateway/src/rpc_objects.rs#L94)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

shouldn't this be part of the block header @ShahakShama ?
</blockquote></details>

add the TODO here as well? (guessing it's related to the below discussion)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 15 files at r2, 1 of 1 files at r5, 3 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/463)* status: 15 of 19 files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @ShahakShama)

**Comment by TzahiTaub** [comment]
*[`crates/gateway/src/rpc_objects.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/463#-O4KhKKR4z9grCVs_doq:-O5910OkDHgzcsoZ6GUy:bupi4au) ([raw file](https://github.com/starkware-libs/sequencer/blob/88721563ffbf7657b1322c4ef1ada285f59598fb/crates/gateway/src/rpc_objects.rs#L94)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add the TODO here as well? (guessing it's related to the below discussion)
</blockquote></details>

Added. This is a part of the mempool project. @elintul FYI

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/463)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/463#-:-O5DhLVF-V-DIkEt4fVp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
