### PR TITLE
chore: split local config field

### PR DESCRIPTION
**Pull request by nadin-Starkware**

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1662)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/mempool_infra/src/component_definitions.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1662#-OARvan9-lpLSIiFPqz7:-OARvan9-lpLSIiFPqz8:bup5vlb) ([raw file](https://github.com/starkware-libs/sequencer/blob/169c16bbc7f894379740a6d4bd878c17ab353f7b/crates/mempool_infra/src/component_definitions.rs#L94)):*
> ```XML
>         Self { channel_buffer_size: DEFAULT_CHANNEL_BUFFER_SIZE }
>     }
> }
> ```

Do we need similar impls for `LocalClientConfig`?
If not, please add a comment in text stating why.



_Code quote:_
```XML
impl SerializeConfig for LocalServerConfig {
    fn dump(&self) -> BTreeMap<ParamPath, SerializedParam> {
        BTreeMap::from_iter([ser_param(
            "channel_buffer_size",
            &self.channel_buffer_size,
            "The communication channel buffer size.",
            ParamPrivacyInput::Public,
        )])
    }
}

impl Default for LocalServerConfig {
    fn default() -> Self {
        Self { channel_buffer_size: DEFAULT_CHANNEL_BUFFER_SIZE }
    }
}
```
___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1662#-OARw-Ia9L6oMIxgAapS:-OARw-IbER2_x6FCVgog:b5iko9t) ([raw file](https://github.com/starkware-libs/sequencer/blob/169c16bbc7f894379740a6d4bd878c17ab353f7b/crates/mempool_node/src/config/component_execution_config.rs#L64)):*
> ```XML
>         vec![
>             append_sub_config_name(self.execution_mode.dump(), "execution_mode"),
>             ser_optional_sub_config(&self.local_server_config, "local_server_config"),
> ```

Not dumping the client?



_Code quote:_
```XML
ser_optional_sub_config(&self.local_server_config, "local_server_config"),
```
___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1662#-OARwXWt3NcxrGaVROI0:-OARwXWt3NcxrGaVROI1:b6r02no) ([raw file](https://github.com/starkware-libs/sequencer/blob/169c16bbc7f894379740a6d4bd878c17ab353f7b/crates/mempool_node/src/config/component_execution_config.rs#L225)):*
> ```XML
>             "Configuration cannot be provided in disabled execution mode."
>         }
>         _ => return Ok(()),
> ```

Please change to match against `execution_mode`, and for each option to verify that the configs are as expected, returning `Ok` if so, and an error oherwise.



_Code quote:_
```XML
    let error_message = match (
        component_config.execution_mode.clone(),
        component_config.local_server_config.is_some(),
        component_config.remote_server_config.is_some(),
        component_config.remote_client_config.is_some(),
    ) {
        (mode, _, true, true) if mode == enable_remote_execution_mode => {
            "Remote server and remote client are mutually exclusive; both cannot be active \
             simultaneously."
        }
        (mode, true, _, true) if mode == enable_remote_execution_mode => {
            "Local server and remote client are mutually exclusive; both cannot be active \
             simultaneously."
        }
        (mode, _, false, false) if mode == enable_remote_execution_mode => {
            "Remote communication config is missing."
        }
        (mode, false, _, _) if mode == local_execution_mode => "Local server config is missing.",
        (mode, true, true, _) if mode == local_execution_mode => {
            "Cannot provide remote server configuration in local execution mode with remote \
             connection disabled."
        }
        (mode, true, _, true) if mode == local_execution_mode => {
            "Cannot provide remote client configuration in local execution mode with remote \
             connection disabled."
        }
        (mode, true, _, _) if mode == disabled => {
            "Configuration cannot be provided in disabled execution mode."
        }
        (mode, _, true, _) if mode == disabled => {
            "Configuration cannot be provided in disabled execution mode."
        }
        (mode, _, _, true) if mode == disabled => {
            "Configuration cannot be provided in disabled execution mode."
        }
        _ => return Ok(()),
```
___
*[`crates/mempool_node/src/config/config_test.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1662#-OARxvxjB_Z5eu8lb5T7:-OARxvxjB_Z5eu8lb5T8:b832ria) ([raw file](https://github.com/starkware-libs/sequencer/blob/169c16bbc7f894379740a6d4bd878c17ab353f7b/crates/mempool_node/src/config/config_test.rs#L45)):*
> ```XML
> fn test_valid_component_execution_config(
>     #[case] execution_mode: ComponentExecutionMode,
>     #[case] local_server_config: Option<LocalServerConfig>,
> ```

IMO add local config as well.



_Code quote:_
```XML
[case] local_server_config: Option<LocalServerConfig>,
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1662)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_definitions.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1662#-OARvan9-lpLSIiFPqz7:-OAWi8RT-qIvoHmqEcgB:bqj28ad) ([raw file](https://github.com/starkware-libs/sequencer/blob/169c16bbc7f894379740a6d4bd878c17ab353f7b/crates/mempool_infra/src/component_definitions.rs#L94)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Do we need similar impls for `LocalClientConfig`?
If not, please add a comment in text stating why.
</blockquote></details>

Deleted, as discussed.
___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1662#-OARw-Ia9L6oMIxgAapS:-OAWiDhC2bx0S_1E15d2:bb73xfv) ([raw file](https://github.com/starkware-libs/sequencer/blob/169c16bbc7f894379740a6d4bd878c17ab353f7b/crates/mempool_node/src/config/component_execution_config.rs#L64)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Not dumping the client?
</blockquote></details>

Same
___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1662#-OARwXWt3NcxrGaVROI0:-OAWhgGP6TCMbEsbGf-s:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/169c16bbc7f894379740a6d4bd878c17ab353f7b/crates/mempool_node/src/config/component_execution_config.rs#L225)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to match against `execution_mode`, and for each option to verify that the configs are as expected, returning `Ok` if so, and an error oherwise.
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/config/config_test.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1662#-OARxvxjB_Z5eu8lb5T7:-OAWmdco5UCouCk04ptZ:bb73xfv) ([raw file](https://github.com/starkware-libs/sequencer/blob/169c16bbc7f894379740a6d4bd878c17ab353f7b/crates/mempool_node/src/config/config_test.rs#L45)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

IMO add local config as well.
</blockquote></details>

Same

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1662)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1662#-OARwXWt3NcxrGaVROI0:-OAXsEoH0cKWIcxXvETc:b8j527b) ([raw file](https://github.com/starkware-libs/sequencer/blob/169c16bbc7f894379740a6d4bd878c17ab353f7b/crates/mempool_node/src/config/component_execution_config.rs#L225)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Much better, but here's a more concise suggestion, wdyt?

```
pub fn validate_single_component_config(
    component_config: &ComponentExecutionConfig,
) -> Result<(), ValidationError> {
    let execution_mode = &component_config.execution_mode;
    let local_server = &component_config.local_server_config.is_some();
    let remote_client = &component_config.remote_client_config.is_some();
    let remote_server = &component_config.remote_server_config.is_some();

    let mut error = ValidationError::new("Invalid component configuration.");

    match (execution_mode, local_server, remote_client, remote_server) {
        // Check that for a disabled component no configurations are provided.
        (ComponentExecutionMode::Disabled, false, false, false) => Ok(()),
        (ComponentExecutionMode::Disabled, _, _, _) => {
            error.message = Some(
                "Invalid configuration: The component is disabled, but local or remote \
                 configurations are provided."
                    .into(),
            );
            Err(error)
        },
        // Check that ....

```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1662)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 178 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1662#-OAXsaQ47dWUYDMdTTu3:-OAXsaQ47dWUYDMdTTu4:bgmx5dp) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c7235115c2fe34f916a587a53bc5fa72611410b/crates/mempool_node/src/config/component_execution_config.rs#L178)):*
> ```XML
>     let remote_server_config = &component_config.remote_server_config;
> 
>     let mut error = ValidationError::new("Invalid component configuration.");
> ```

Please add "execution" in between.



_Code quote:_
```XML
component configuration
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1662)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 202 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1662#-OAXsfQz51OfXFzBECtP:-OAXsfQz51OfXFzBECtQ:beurih9) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c7235115c2fe34f916a587a53bc5fa72611410b/crates/mempool_node/src/config/component_execution_config.rs#L202)):*
> ```XML
>                 print!("enable_remote_connection is true");
>                 error.message = Some(
>                     "Invalid configuration: Both local and remote server configurations must be \
> ```

Please be consistent with the error messages: either all with the `Invalid configuration: `, or none (I prefer the latter for conciseness).



_Code quote:_
```XML
Invalid configuration: 
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1662)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1662#-OARwXWt3NcxrGaVROI0:-OAXwsq_CXcDCqt1xQlf:bulgs2w) ([raw file](https://github.com/starkware-libs/sequencer/blob/169c16bbc7f894379740a6d4bd878c17ab353f7b/crates/mempool_node/src/config/component_execution_config.rs#L225)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Much better, but here's a more concise suggestion, wdyt?

```
pub fn validate_single_component_config(
    component_config: &ComponentExecutionConfig,
) -> Result<(), ValidationError> {
    let execution_mode = &component_config.execution_mode;
    let local_server = &component_config.local_server_config.is_some();
    let remote_client = &component_config.remote_client_config.is_some();
    let remote_server = &component_config.remote_server_config.is_some();

    let mut error = ValidationError::new("Invalid component configuration.");

    match (execution_mode, local_server, remote_client, remote_server) {
        // Check that for a disabled component no configurations are provided.
        (ComponentExecutionMode::Disabled, false, false, false) => Ok(()),
        (ComponentExecutionMode::Disabled, _, _, _) => {
            error.message = Some(
                "Invalid configuration: The component is disabled, but local or remote \
                 configurations are provided."
                    .into(),
            );
            Err(error)
        },
        // Check that ....

```
</blockquote></details>

This match could break if the order changes, as the first arm is contained within the second. It may be safer to use mutually exclusive conditions to avoid order dependency. wdyt?
___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 178 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1662#-OAXsaQ47dWUYDMdTTu3:-OAXvCFaDCP2wZ7dvakw:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c7235115c2fe34f916a587a53bc5fa72611410b/crates/mempool_node/src/config/component_execution_config.rs#L178)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add "execution" in between.
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 202 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1662#-OAXsfQz51OfXFzBECtP:-OAXvV-O7zoSqLkpUjJO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c7235115c2fe34f916a587a53bc5fa72611410b/crates/mempool_node/src/config/component_execution_config.rs#L202)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please be consistent with the error messages: either all with the `Invalid configuration: `, or none (I prefer the latter for conciseness).
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1662)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1662#-OARwXWt3NcxrGaVROI0:-OAYiDUwDdZDOWl4kvQ7:b-8q20in) ([raw file](https://github.com/starkware-libs/sequencer/blob/169c16bbc7f894379740a6d4bd878c17ab353f7b/crates/mempool_node/src/config/component_execution_config.rs#L225)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

This match could break if the order changes, as the first arm is contained within the second. It may be safer to use mutually exclusive conditions to avoid order dependency. wdyt?
</blockquote></details>

Yea, that makes sense. I think that for the sake of readable code it is preferred to opt out for avoiding specific errors in favor of bundling the code in concisely:

```
    match (execution_mode, local_server, remote_client, remote_server) {
        // Check that for a disabled component no configurations are provided.
        (ComponentExecutionMode::Disabled, false, false, false) => Ok(()),
        (ComponentExecutionMode::LocalExecution, x, y, z) => Ok(()),
        ...
        ...
        _ => {
            let error = ValidationError::new("Invalid component configuration.");
            Err(error)
        },
```
I'd explicilty mention the 4 `ok` coditions for readability, and avoid a specific error message in case of a failure. IMO the potential errors are simple enough that they do not require a specific description.

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1662)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/config/component_execution_config.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1662#-OARwXWt3NcxrGaVROI0:-OAftHiTEscRpEfep5eY:bbtnrv) ([raw file](https://github.com/starkware-libs/sequencer/blob/169c16bbc7f894379740a6d4bd878c17ab353f7b/crates/mempool_node/src/config/component_execution_config.rs#L225)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Yea, that makes sense. I think that for the sake of readable code it is preferred to opt out for avoiding specific errors in favor of bundling the code in concisely:

```
    match (execution_mode, local_server, remote_client, remote_server) {
        // Check that for a disabled component no configurations are provided.
        (ComponentExecutionMode::Disabled, false, false, false) => Ok(()),
        (ComponentExecutionMode::LocalExecution, x, y, z) => Ok(()),
        ...
        ...
        _ => {
            let error = ValidationError::new("Invalid component configuration.");
            Err(error)
        },
```
I'd explicilty mention the 4 `ok` coditions for readability, and avoid a specific error message in case of a failure. IMO the potential errors are simple enough that they do not require a specific description.
</blockquote></details>

Done, note: This approach uses a general error message without mode-specific details.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1662#-:-OAksvQq6XiE200Ltmv0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Pull request merged**
