### PR TITLE
feat(consensus): calculate base gas price

### PR DESCRIPTION
**Pull request by ayeletstarkware**
Calculate next base gas price and store it in the `SequencerConsensusContext` field for later use in `build_proposal`.

### CODE REVIEW

**Comment by ayeletstarkware** [comment]
* **#2999** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2999?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2999?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2999)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2999#-OFHysoF1HT6jiDL8P9O:-OFHysoF1HT6jiDL8P9P:b13hmha) ([raw file](https://github.com/starkware-libs/sequencer/blob/beef0a91c8fc89ff9112d7213d9e32679c34bd40/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L131)):*
> ```XML
>     chain_id: ChainId,
>     cende_ambassador: Arc<dyn CendeContext>,
>     l2_gas_price: u64,
> ```

document.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2999)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2999#-OFHysoF1HT6jiDL8P9O:-OFI25Cp1OqNTpSE9XBg:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/beef0a91c8fc89ff9112d7213d9e32679c34bd40/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L131)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

document.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2999#-:-OFI2yst-uyuVSJCuIm5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
