### PR TITLE
chore: add shell command builder

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
commit-id:96859c27

---

**Stack**:
- #2270
- #2266
- #2265
- #2264 ⬅
- #2255
- #2254

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2264)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2264#-OCYPOAyAcuZ7bZMNOgH:-OCYPOAz2_t9kqVUVo4z:b-v68e9n) (no related file):*
Is the end goal of the function `create_shell_command` to replace every other instance of `Command::new` in the repo?

Playing devil's advocate:
Isn't it an overkill?
Answer:
We just spent a couple of weeks fighting this kind of inconsistency. This assures the CI runs more similarly to an executable.
___
*[`crates/infra_utils/src/command.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2264#-OCYOe5n5MEVddADkLGb:-OCYOe5n5MEVddADkLGc:b-pcr5y3) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae3a0f8b7b8e476080ca3f87b982957c2575125c/crates/infra_utils/src/command.rs#L27)):*
> ```XML
>     env::vars().filter(|(key, _)| key.starts_with("CARGO_")).for_each(|(key, _)| {
>         command.env_remove(key);
>     });
> ```

This is just for safety, right? to ensure that every shell command is run consistently.



_Code quote:_
```XML
    // Filter out all CARGO_ environment variables.
    env::vars().filter(|(key, _)| key.starts_with("CARGO_")).for_each(|(key, _)| {
        command.env_remove(key);
    });
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2264)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/infra_utils/src/command.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2264#-OCYOe5n5MEVddADkLGb:-OCYQphm9Z7SqNdxDyyn:b-68r695) ([raw file](https://github.com/starkware-libs/sequencer/blob/ae3a0f8b7b8e476080ca3f87b982957c2575125c/crates/infra_utils/src/command.rs#L27)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This is just for safety, right? to ensure that every shell command is run consistently.
</blockquote></details>

This is to ensure (or, make an effort in the direction of ensuring) that we do not have side effects of running our executables due to using `cargo`. I.e., I'd like this to be a step in a direction of reducing the differences of `cargo run X` and `cargo build X; ./X` .

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2264)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2264#-OCYPOAyAcuZ7bZMNOgH:-OCYR9B69TP1-hZH97Cj:bt6x0gf) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Is the end goal of the function `create_shell_command` to replace every other instance of `Command::new` in the repo?

Playing devil's advocate:
Isn't it an overkill?
Answer:
We just spent a couple of weeks fighting this kind of inconsistency. This assures the CI runs more similarly to an executable.
</blockquote></details>

No, only those that we need to make sure we can run without `cargo`. Example, the sequencer node.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2264#-:-OCYRkew5jlS6mxivMtT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
