### PR TITLE
feat(mempool): implement fee escalation

### PR DESCRIPTION
**Pull request by elintul**
Tests will be added next.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 234 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O8qpsFc0C9yFPGiWlTT:-O8qpsFd2gO9WTHI5Av5:brrv6g5) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2d9865dc4c343463d3e79f2dd52beb33321ce87/crates/mempool/src/mempool.rs#L234)):*
> ```XML
>         self.tx_pool
>             .remove(existing_tx_ref.tx_hash)
>             .expect("Transaction hash from pool must exist.");
> ```

Still haven't figured out the `purge_tx` direction, not really straightforward.



_Code quote:_
```XML
        self.tx_queue.remove(sender_address);
        self.tx_pool
            .remove(existing_tx_ref.tx_hash)
            .expect("Transaction hash from pool must exist.");
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O9-RRaT2LlQlQksWG6G:-O9-RRaT2LlQlQksWG6H:b-xhroy) (no related file):*
Will pass CI once #1304 is merged.

___

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 89 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O90P7Pj7CoGJ53p9f2A:-O90P7Pj7CoGJ53p9f2B:b-yq6mqq) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e4488d0d41d52e9c002b4ebbec6b38a9c116e81/crates/mempool/src/mempool.rs#L89)):*
> ```XML
> 
>         let AddTransactionArgs { tx, account_state } = args;
>         self.handle_fee_escalation(&tx)?;
> ```

Why isn't it part of the transaction pool insertion?



_Code quote:_
```XML
self.handle_fee_escalation(&tx)?;
```
___
*[`crates/mempool/src/mempool.rs` line 228 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O90Nyxg6GtSdRwsGjJA:-O90Nyxg6GtSdRwsGjJB:b-w8c4dp) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e4488d0d41d52e9c002b4ebbec6b38a9c116e81/crates/mempool/src/mempool.rs#L228)):*
> ```XML
> 
>         if !self.should_replace_tx(existing_tx_ref, &incoming_tx_ref) {
>             return Err(MempoolError::DuplicateNonce { address: sender_address, nonce });
> ```

I believe it's better to return an error specifically for fee escalation if the new transaction's tip is lower than the specified percentage.



_Code quote:_
```XML
return Err(MempoolError::DuplicateNonce { address: sender_address, nonce });
```
___
*[`crates/mempool/src/mempool.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O90Ojd-8Y990oCpGyRy:-O90Ojd-8Y990oCpGyRz:bcfoy4q) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e4488d0d41d52e9c002b4ebbec6b38a9c116e81/crates/mempool/src/mempool.rs#L258)):*
> ```XML
> 
>         let Some(escalation_qualified_value) =
>             existing_value.checked_mul(escalation_factor).and_then(|v| v.checked_div(100))
> ```

How do you handle overflow during multiplication?

For example, if the factor is 110%:

-   When `new_tip * 1.1` is less than `2^128`, there’s no overflow.
-   However, if `tip * 110` exceeds `2^128`, overflow occurs.

In the current code, it panics, while it shouldn't panic, as the result is less than `2^128`.



_Code quote:_
```XML
        let Some(escalation_qualified_value) =
            existing_value.checked_mul(escalation_factor).and_then(|v| v.checked_div(100))
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 89 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O90P7Pj7CoGJ53p9f2A:-O93WTQ6AFYxhxUv0z_d:bb6ev2h) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e4488d0d41d52e9c002b4ebbec6b38a9c116e81/crates/mempool/src/mempool.rs#L89)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why isn't it part of the transaction pool insertion?
</blockquote></details>

It isn't its responsibility, it's the mempool's. The pool should remain a straightforward lean data structure. 
___
*[`crates/mempool/src/mempool.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O90Ojd-8Y990oCpGyRy:-O93WyT11Fy0oFW0Kepe:b-bex8m8) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e4488d0d41d52e9c002b4ebbec6b38a9c116e81/crates/mempool/src/mempool.rs#L258)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

How do you handle overflow during multiplication?

For example, if the factor is 110%:

-   When `new_tip * 1.1` is less than `2^128`, there’s no overflow.
-   However, if `tip * 110` exceeds `2^128`, overflow occurs.

In the current code, it panics, while it shouldn't panic, as the result is less than `2^128`.
</blockquote></details>

You can see, I use `checked_*` API.
I'll add a test to check different kinds of overflows; next PR.

**Review by giladchase — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O93RsGv87zMX5kFQ2Bk:-O93RsGv87zMX5kFQ2Bl:b-187b3q) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e4488d0d41d52e9c002b4ebbec6b38a9c116e81/crates/mempool/src/mempool.rs#L258)):*
> ```XML
> 
>         let Some(escalation_qualified_value) =
>             existing_value.checked_mul(escalation_factor).and_then(|v| v.checked_div(100))
> ```

According to [checked_div doc](https://doc.rust-lang.org/std/primitive.u128.html#method.checked_div), it can only fail if the RHS is 0, but since it is hard-coded as 100 I think we can use regular `/`, or maybe check_div(100).expect("dividing by nonzero is safe") to appease critical readers.



_Suggestion:_
```XML
            existing_value.checked_mul(escalation_factor).and_then(|v| v / 100)
```

**Review by giladchase — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O90Ojd-8Y990oCpGyRy:-O93ac7P1lD8-rw5l2MY:bp097p3) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e4488d0d41d52e9c002b4ebbec6b38a9c116e81/crates/mempool/src/mempool.rs#L258)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

You can see, I use `checked_*` API.
I'll add a test to check different kinds of overflows; next PR.
</blockquote></details>

So, in the given example, it would panic.
Is it the correct behavior in this case?

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O90Ojd-8Y990oCpGyRy:-O93bbTQ4n-FOdCW6i_c:b-b75vnu) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e4488d0d41d52e9c002b4ebbec6b38a9c116e81/crates/mempool/src/mempool.rs#L258)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

So, in the given example, it would panic.
Is it the correct behavior in this case?
</blockquote></details>

No, please see the aforementioned API's documentation.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 228 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O90Nyxg6GtSdRwsGjJA:-O93izcw0xfUrr2cbUtZ:b-9hctkg) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e4488d0d41d52e9c002b4ebbec6b38a9c116e81/crates/mempool/src/mempool.rs#L228)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I believe it's better to return an error specifically for fee escalation if the new transaction's tip is lower than the specified percentage.
</blockquote></details>

I'll consider it (also thought about it for other duplicate nonce flows, so I need to give it some broader thought).
___
*[`crates/mempool/src/mempool.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O93RsGv87zMX5kFQ2Bk:-O93jKk07OaL3wtcGHV0:bo3vl6y) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e4488d0d41d52e9c002b4ebbec6b38a9c116e81/crates/mempool/src/mempool.rs#L258)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

According to [checked_div doc](https://doc.rust-lang.org/std/primitive.u128.html#method.checked_div), it can only fail if the RHS is 0, but since it is hard-coded as 100 I think we can use regular `/`, or maybe check_div(100).expect("dividing by nonzero is safe") to appease critical readers.
</blockquote></details>

Thanks, done.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O90Ojd-8Y990oCpGyRy:-O93lPvdAtSaZGu7xfgo:bja2bem) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e4488d0d41d52e9c002b4ebbec6b38a9c116e81/crates/mempool/src/mempool.rs#L258)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No, please see the aforementioned API's documentation.
</blockquote></details>

Correction: the example you gave is good, I'll handle it separately.

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`-- commits` line 7 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O93mAIy7z_JHWMOHa2e):*
Is it by mistake?

I’d prefer to have a separate PR for the test since the original PR is quite long.



_Code quote:_
```
New commits in r4 on 13/10/2024 at 10:27:
- 3269214: test(mempool): add fee escalation test
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`-- commits` line 7 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O93mAIy7z_JHWMOHa2e):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Is it by mistake?

I’d prefer to have a separate PR for the test since the original PR is quite long.
</blockquote></details>

It's a mistake, the test appears in #1338.

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 228 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O90Nyxg6GtSdRwsGjJA:-O93uQEs3x7RNZg6cVS9:b98z23f) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e4488d0d41d52e9c002b4ebbec6b38a9c116e81/crates/mempool/src/mempool.rs#L228)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'll consider it (also thought about it for other duplicate nonce flows, so I need to give it some broader thought).
</blockquote></details>

Can you please add a TODO?
___
*[`crates/mempool/src/mempool_test.rs` line 376 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O93wl958spgibPwgFST:-O93wl967wKAFLO-Mtil:b-r4mw4i) ([raw file](https://github.com/starkware-libs/sequencer/blob/3f5a143820d139396da10232af5a144188bafc68/crates/mempool/src/mempool_test.rs#L376)):*
> ```XML
>     // This is an artificially crafted transaction with a different nonce in order to skip
>     // replacement logic.
>     let duplicate_input = add_tx_input!(tx_hash: 1, tx_nonce: 2, account_nonce: 0);
> ```

Is it a real scenario?
Is it possible to have different nonces with the same transaction hashes?

This test was aimed to check [this](https://github.com/starkware-libs/sequencer/blob/ff44c571b89b746fa00288a5d1e826dc81a217c7/crates/mempool/src/transaction_pool.rs#L33-L37) code. Now that fee escalation handling has been added, is this code still reachable? Perhaps it should be removed.

wdyt?



_Code quote:_
```XML
let duplicate_input = add_tx_input!(tx_hash: 1, tx_nonce: 2, account_nonce: 0);
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 228 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O90Nyxg6GtSdRwsGjJA:-O93xlgECcUq7RRYf4uz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e4488d0d41d52e9c002b4ebbec6b38a9c116e81/crates/mempool/src/mempool.rs#L228)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can you please add a TODO?
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 376 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O93wl958spgibPwgFST:-O93xmtv7QJW_Fn77jX3:b-oq6myu) ([raw file](https://github.com/starkware-libs/sequencer/blob/3f5a143820d139396da10232af5a144188bafc68/crates/mempool/src/mempool_test.rs#L376)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Is it a real scenario?
Is it possible to have different nonces with the same transaction hashes?

This test was aimed to check [this](https://github.com/starkware-libs/sequencer/blob/ff44c571b89b746fa00288a5d1e826dc81a217c7/crates/mempool/src/transaction_pool.rs#L33-L37) code. Now that fee escalation handling has been added, is this code still reachable? Perhaps it should be removed.

wdyt?
</blockquote></details>

I was wondering the same, but we must check duplicate hash, even artifitially.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 376 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O93wl958spgibPwgFST:-O93y1UY7JU-MncEbEaw:b5576ii) ([raw file](https://github.com/starkware-libs/sequencer/blob/3f5a143820d139396da10232af5a144188bafc68/crates/mempool/src/mempool_test.rs#L376)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I was wondering the same, but we must check duplicate hash, even artifitially.
</blockquote></details>

is this code still reachable? maybe it should be removed or paniced instead.

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 376 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O93wl958spgibPwgFST:-O93yFPm8_sMuK1DDxTq:b-o3mqyj) ([raw file](https://github.com/starkware-libs/sequencer/blob/3f5a143820d139396da10232af5a144188bafc68/crates/mempool/src/mempool_test.rs#L376)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

is this code still reachable? maybe it should be removed or paniced instead.
</blockquote></details>

I don't want to assume fee escalation check happens before, this might change and we'll forget to restore the test. Added a TODO.

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O93zM0V12JvqnnHuPBz:-O93zM0W2WQ1plpRdr7z:b-7ww4wc) (no related file):*
I want to emphasize that after this code change, duplicate hashes are checked only after calculating the new tip and gas price. This occurs because the fee escalation calculation happens outside (before) of the transaction pool.

As a result, a minor DoS vulnerability is possible, where someone could send many duplicate transactions and force the mempool to perform fee escalation calculations. We allow this because we assume that the fee escalation calculation is not resource-intensive.

Is it correct?

___

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-:-O94-yMn6hCth5uE0PIx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-O93zM0V12JvqnnHuPBz:-O94013nC-qix9kNddkh:booce30) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I want to emphasize that after this code change, duplicate hashes are checked only after calculating the new tip and gas price. This occurs because the fee escalation calculation happens outside (before) of the transaction pool.

As a result, a minor DoS vulnerability is possible, where someone could send many duplicate transactions and force the mempool to perform fee escalation calculations. We allow this because we assume that the fee escalation calculation is not resource-intensive.

Is it correct?
</blockquote></details>

Sounds right, part of the duplicate hash test task. Thanks!

___

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1304#-:-O940zA4CDyqw8lJPZUV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
