### PR TITLE
chore: add an additional node configured for remote connection mode

### PR DESCRIPTION
**Pull request by nadin-Starkware**
commit-id:acbc8c19

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3016)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3016#-OFR9boTAh_8uDiuWzWW:-OFR9boTAh_8uDiuWzWX:b-q87zf0) ([raw file](https://github.com/starkware-libs/sequencer/blob/a6de5c1e3fd400efb86ef40b884881675648e075/crates/starknet_integration_tests/src/end_to_end_integration.rs#L26)):*
> ```XML
> use crate::utils::send_account_txs;
> 
> const N_SEQUENCERS: usize = 3;
> ```

As this name is quite ambigious in its name please add a comment that explains what it means: the number of "full" sequencers that participate in the test.



_Code quote:_
```XML
const N_SEQUENCERS: usize = 3;
```
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3016#-OFR9pLW-ipCCvoas30D:-OFR9pLW-ipCCvoas30E:b-22638e) ([raw file](https://github.com/starkware-libs/sequencer/blob/a6de5c1e3fd400efb86ef40b884881675648e075/crates/starknet_integration_tests/src/end_to_end_integration.rs#L167)):*
> ```XML
>         get_non_http_container_config(gateway_socket_2, mempool_socket_2, mempool_p2p_socket_2),
>     ]
> }
> ```

Please:
1. receive a `usize` arg
2. using loop / iterator : apply in the inner functions and collect the inner results (`get_http_container_config` and `get_non_http_container_config`
3. Flatten the result and return it



_Code quote:_
```XML
fn get_remote_test_component_config(available_ports: &mut AvailablePorts) -> Vec<ComponentConfig> {
    let gateway_socket = available_ports.get_next_local_host_socket();
    let mempool_socket = available_ports.get_next_local_host_socket();
    let mempool_p2p_socket = available_ports.get_next_local_host_socket();

    let gateway_socket_2 = available_ports.get_next_local_host_socket();
    let mempool_socket_2 = available_ports.get_next_local_host_socket();
    let mempool_p2p_socket_2 = available_ports.get_next_local_host_socket();

    vec![
        get_http_container_config(gateway_socket, mempool_socket, mempool_p2p_socket),
        get_non_http_container_config(gateway_socket, mempool_socket, mempool_p2p_socket),
        get_http_container_config(gateway_socket_2, mempool_socket_2, mempool_p2p_socket_2),
        get_non_http_container_config(gateway_socket_2, mempool_socket_2, mempool_p2p_socket_2),
    ]
}
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3016)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3016#-OFR9boTAh_8uDiuWzWW:-OFRTx-e5doGQwp2VKna:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a6de5c1e3fd400efb86ef40b884881675648e075/crates/starknet_integration_tests/src/end_to_end_integration.rs#L26)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

As this name is quite ambigious in its name please add a comment that explains what it means: the number of "full" sequencers that participate in the test.
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3016#-OFR9pLW-ipCCvoas30D:-OFRU4gFCWMI5qSwc04L:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a6de5c1e3fd400efb86ef40b884881675648e075/crates/starknet_integration_tests/src/end_to_end_integration.rs#L167)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please:
1. receive a `usize` arg
2. using loop / iterator : apply in the inner functions and collect the inner results (`get_http_container_config` and `get_non_http_container_config`
3. Flatten the result and return it
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3016)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3016#-OFRduPg29TvfiU86i5r:-OFRduPg29TvfiU86i5s:b-5gmmwb) ([raw file](https://github.com/starkware-libs/sequencer/blob/e16e8e80192e3850d4a6b8ae50991160e160297b/crates/starknet_integration_tests/src/end_to_end_integration.rs#L164)):*
> ```XML
> ) -> Vec<ComponentConfig> {
>     (1..n)
>         .map(|_| {
> ```

Consider `repeat_with`:
https://doc.rust-lang.org/std/iter/fn.repeat_with.html



_Code quote:_
```XML
    (1..n)
        .map(|_| {
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3016)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3016#-OFRe2pE6HLNLgOQCXKf:-OFRe2pE6HLNLgOQCXKg:b-9vhieg) ([raw file](https://github.com/starkware-libs/sequencer/blob/e16e8e80192e3850d4a6b8ae50991160e160297b/crates/starknet_integration_tests/src/end_to_end_integration.rs#L174)):*
> ```XML
>             )
>         })
>         .flat_map(|(http_config, non_http_config)| vec![http_config, non_http_config])
> ```

IIUC: The current code creates a vector of 2-elements tuples, then transforms it to a vector of 2-elements vectors, and then flattens the vector to a vector of configs.
Can this process be shortened?
Can we go from vector of tuples to a flattened vector directly?
If not, can we create a 2-element vector instead of the 2-element tuple to begin with?



_Code quote:_
```XML
            (
                get_http_container_config(gateway_socket, mempool_socket, mempool_p2p_socket),
                get_non_http_container_config(gateway_socket, mempool_socket, mempool_p2p_socket),
            )
        })
        .flat_map(|(http_config, non_http_config)| vec![http_config, non_http_config])
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3016)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3016#-OFRefk5AowInU_dbcBy:-OFRefk60Qq1aSAJWn_0:b-8g2k0t) ([raw file](https://github.com/starkware-libs/sequencer/blob/e16e8e80192e3850d4a6b8ae50991160e160297b/crates/starknet_integration_tests/src/end_to_end_integration.rs#L161)):*
> ```XML
> fn create_remote_node_configs(
>     available_ports: &mut AvailablePorts,
>     n: usize,
> ```

A meaningful name please



_Code quote:_
```XML
n
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3016)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3016#-OFRefk5AowInU_dbcBy:-OFRgZWwCr8eqhgiBWbS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e16e8e80192e3850d4a6b8ae50991160e160297b/crates/starknet_integration_tests/src/end_to_end_integration.rs#L161)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

A meaningful name please
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3016#-OFRduPg29TvfiU86i5r:-OFRgZCi8QQ3WikvGE71:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e16e8e80192e3850d4a6b8ae50991160e160297b/crates/starknet_integration_tests/src/end_to_end_integration.rs#L164)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Consider `repeat_with`:
https://doc.rust-lang.org/std/iter/fn.repeat_with.html
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3016#-OFRe2pE6HLNLgOQCXKf:-OFRgYZl9-dEjKRDO4ir:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e16e8e80192e3850d4a6b8ae50991160e160297b/crates/starknet_integration_tests/src/end_to_end_integration.rs#L174)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

IIUC: The current code creates a vector of 2-elements tuples, then transforms it to a vector of 2-elements vectors, and then flattens the vector to a vector of configs.
Can this process be shortened?
Can we go from vector of tuples to a flattened vector directly?
If not, can we create a 2-element vector instead of the 2-element tuple to begin with?
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3016)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3016#-OFR9boTAh_8uDiuWzWW:-OFRkdXC1KJ4FKsx0_FW:b-3ntez8) ([raw file](https://github.com/starkware-libs/sequencer/blob/a6de5c1e3fd400efb86ef40b884881675648e075/crates/starknet_integration_tests/src/end_to_end_integration.rs#L26)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

As discussed :-)
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3016#-OFRefk5AowInU_dbcBy:-OFRjzx4Dmnzz9bZUrBP:b32z3hl) ([raw file](https://github.com/starkware-libs/sequencer/blob/e16e8e80192e3850d4a6b8ae50991160e160297b/crates/starknet_integration_tests/src/end_to_end_integration.rs#L161)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`full`?

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3016)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3016#-OFRefk5AowInU_dbcBy:-OFRku1t09MZ8umul_-8:b-yw0ocu) ([raw file](https://github.com/starkware-libs/sequencer/blob/e16e8e80192e3850d4a6b8ae50991160e160297b/crates/starknet_integration_tests/src/end_to_end_integration.rs#L161)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

`full`?
</blockquote></details>

Did you mean "distributed"?

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3016)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/3016#-OFR9boTAh_8uDiuWzWW:-OFRlSHW3EtEYLYmQWDz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a6de5c1e3fd400efb86ef40b884881675648e075/crates/starknet_integration_tests/src/end_to_end_integration.rs#L26)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

As discussed :-)
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/3016#-OFRefk5AowInU_dbcBy:-OFRlRRN3_6oMkXW5ZVX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e16e8e80192e3850d4a6b8ae50991160e160297b/crates/starknet_integration_tests/src/end_to_end_integration.rs#L161)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Did you mean "distributed"?
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3016#-:-OFRlt4oDOMO3jxjAOR6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Review by nadin-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3016)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @nadin-Starkware)

**Review by nadin-Starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/3016)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Pull request merged**
