### PR TITLE
test(mempool): get txs requested chunk in queue validate replenishing…

### PR DESCRIPTION
**Pull request by ayeletstarkware**
… queue

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/96)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/96)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/96#-O2d_XYB6hnAZddnaM-b:-O2d_XYB6hnAZddnaM-c:b5hpi3v) ([raw file](https://github.com/starkware-libs/sequencer/blob/40987c4690cc8aa19bae63f562a7b868886164f4/crates/mempool/src/mempool_test.rs#L201)):*
> ```XML
> 
> #[rstest]
> fn test_get_txs_requested_chuck_in_queue_validate_replenishing() {
> ```

This it not English... :(



_Code quote:_
```XML
 test_get_txs_requested_chuck_in_queue_validate_replenishing
```
___
*[`crates/mempool/src/mempool_test.rs` line 218 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/96#-O2d_O-h9M3X12wXTklt:-O2d_O-h9M3X12wXTklu:b-x1fmz3) ([raw file](https://github.com/starkware-libs/sequencer/blob/40987c4690cc8aa19bae63f562a7b868886164f4/crates/mempool/src/mempool_test.rs#L218)):*
> ```XML
>         tx_address_0_nonce_1.clone(),
>         tx_address_1_nonce_1.clone(),
>     ];
> ```

`map`, please...



_Code quote:_
```XML
    let pool_txs = [
        tx_address_0_nonce_0.clone(),
        tx_address_1_nonce_0.clone(),
        tx_address_0_nonce_1.clone(),
        tx_address_1_nonce_1.clone(),
    ];
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/96)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @dan-starkware)

___
*[`crates/mempool/src/mempool_test.rs` line 289 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/96#-O2s5Rlm9_xi2IxxTz3u:-O2s5Rlm9_xi2IxxTz3v:b-52dt2l) ([raw file](https://github.com/starkware-libs/sequencer/blob/8760cf035569afd56d1c5a8de91c60452e3e6d89/crates/mempool/src/mempool_test.rs#L289)):*
> ```XML
> 
> #[rstest]
> fn test_get_txs_replenishes_queue_with_next_transactions() {
> ```

The name you suggested is too generic, it can fit all replenishment tests.
How about:



_Suggestion:_
```XML
test_get_txs_replenishes_queue_multi_account
```
___
*[`crates/mempool/src/mempool_test.rs` line 315 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/96#-O2s5ILR9f0hOTHpAlTh:-O2s5ILR9f0hOTHpAlTi:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8760cf035569afd56d1c5a8de91c60452e3e6d89/crates/mempool/src/mempool_test.rs#L315)):*
> ```XML
>     // Assert: queue is replenished with the next transactions of each account.
>     assert_eq!(txs, [tx_address_0_nonce_0, tx_address_1_nonce_0]);
>     let expected_queue_txs =
> ```





_Suggestion:_
```XML
    assert_eq!(txs, [tx_address_0_nonce_0, tx_address_1_nonce_0]);
    
    let expected_queue_txs =
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/96)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @dan-starkware)

___
*[`crates/mempool/src/mempool_test.rs` line 289 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/96#-O2s5Rlm9_xi2IxxTz3u:-O2s5iUH-a2OuYQ62wBb:bgc8k1z) ([raw file](https://github.com/starkware-libs/sequencer/blob/8760cf035569afd56d1c5a8de91c60452e3e6d89/crates/mempool/src/mempool_test.rs#L289)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

The name you suggested is too generic, it can fit all replenishment tests.
How about:
</blockquote></details>

Maybe even: `test_get_txs_replenishes_queue_multi_account_between_chunks`.
Please also update commit message.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/96)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 289 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/96#-O2s5Rlm9_xi2IxxTz3u:-O2sp1Eo7V_2CrJTag2f:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8760cf035569afd56d1c5a8de91c60452e3e6d89/crates/mempool/src/mempool_test.rs#L289)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Maybe even: `test_get_txs_replenishes_queue_multi_account_between_chunks`.
Please also update commit message.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/96#-:-O2su1W1D_8HfpaeqHFc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
