### PR TITLE
chore(blockifier): renamed max_resource_bounds -> max_l1_resource_bounds

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/912)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/912#-:-O7OdoFb8y2tOIVjDcXr:bavka44)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/912)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/912#-O7P2sgoA1nRcn9cGbLP):*
should I add L2 gas test cases to any more tests?



_Code quote:_
```
New commits in r1 on 22/09/2024 at 15:08:
```

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@aner-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/912#-:-O7Z_Gy2BFb7YGgQSC9G:b7ntang)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @aner-starkware and @dorimedini-starkware)

**Review by aner-starkware — CHANGES_REQUESTED** [review]
Blocked until reviewed by @dorimedini-starkware 

> Reviewed 8 of 11 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/912#-:-O7czT4D6i-W9S-KID0J:b-v7j3uw)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/912#-:-O7hRlBr9Hsw5c9ca5zp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by aner-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/912#-:-O7czZSM2TKkC6sQNvZL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
