### PR TITLE
refactor(blockifier): update transaction cost in versioned constants

### PR DESCRIPTION
**Pull request by meship-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/944)

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/944)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/resources/versioned_constants.json` line 183 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/944#-O7Xo5yd0V7JyhZnHoEi:-O7Xo5ye-Xe12I_tPW7d:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d36445f586a7b100de984402331833df84eb2bd3/crates/blockifier/resources/versioned_constants.json#L183)):*
> ```JSON
>             "entry_point_gas_cost": 2,
>             "fee_transfer_gas_cost": 1,
>             "step_gas_cost": 4098,
> ```





_Suggestion:_
```JSON
        "transaction_gas_cost": {
            "step_gas_cost": 4098,
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/944#-:-O7YH-8gEvdVWkO5aeRY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/944)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 182 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/944#-O7YKi_WDT_vTK6hhnXg:-O7YKi_WDT_vTK6hhnXh:b-tvtjk3) ([raw file](https://github.com/starkware-libs/sequencer/blob/602ec6fec7c605b696780cff756e2653b0f4acd9/crates/blockifier/resources/versioned_constants.json#L182)):*
> ```JSON
>         "transaction_gas_cost": {
>             "entry_point_gas_cost": 2,
>             "fee_transfer_gas_cost": 1,
> ```

Is this field needed now?



_Code quote:_
```JSON
"fee_transfer_gas_cost": 1,
```

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/944#-:-O7h8krA1sk0sHYMTkqN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

**Pull request merged**
