### PR TITLE
feat(network): create broadcasted message manager

### PR DESCRIPTION
**Pull request by eitanm-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/564)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/564)* status: all files reviewed, 3 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 826 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/564#-O58Ko9E9uRZEHbQWUFs:-O58Ko9F9WsqCuXdkCDn:bn2s0wj) ([raw file](https://github.com/starkware-libs/sequencer/blob/5351092e4561de8369bf1883958d5dbb752e964a/crates/papyrus_network/src/network_manager/mod.rs#L826)):*
> ```XML
>     // TODO(eitan): implement
>     pub fn continue_propogation(&mut self) {
>         unimplemented!();
> ```

This will cause panic if it's called. remove the content of this function (keep the TODO so we'll know we need to implement it)
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/564#-O58NH6qET5zk9U2UkmH:-O58NH6qET5zk9U2UkmI:burxqlb) ([raw file](https://github.com/starkware-libs/sequencer/blob/5351092e4561de8369bf1883958d5dbb752e964a/crates/papyrus_network/src/network_manager/test_utils.rs#L76)):*
> ```XML
> }
> 
> pub fn create_test_broadcasted_message_manager() -> (BroadcastedMessageManager, ReportReceiver) {
> ```

After the serialization change, this won't be able to receive reports. Instead, we'll have a receiver channel for reported peers when we create the channels for broadcast

This means that there's no need to return the ReportReceiver here. I prefer we don't return it so that no one will accidentally use it and then we'll need to migrate their test code
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 258 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/564#-O58PYYt3Wfljyh6Sz_h:-O58PYYt3Wfljyh6Sz_i:bz9tdm2) ([raw file](https://github.com/starkware-libs/sequencer/blob/5351092e4561de8369bf1883958d5dbb752e964a/crates/sequencing/papyrus_consensus/src/manager.rs#L258)):*
> ```XML
>     match msg {
>         // TODO(matan): Return report_sender for use in later errors by SHC.
>         Ok(msg) => Ok(msg),
> ```

call broadcasted_message_manager.continue_propagation()

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/564)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 826 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/564#-O58Ko9E9uRZEHbQWUFs:-O58S7HpBeHoek3sFmPS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5351092e4561de8369bf1883958d5dbb752e964a/crates/papyrus_network/src/network_manager/mod.rs#L826)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This will cause panic if it's called. remove the content of this function (keep the TODO so we'll know we need to implement it)
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test_utils.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/564#-O58NH6qET5zk9U2UkmH:-O58Tez63G4kqbE2jOoU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5351092e4561de8369bf1883958d5dbb752e964a/crates/papyrus_network/src/network_manager/test_utils.rs#L76)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

After the serialization change, this won't be able to receive reports. Instead, we'll have a receiver channel for reported peers when we create the channels for broadcast

This means that there's no need to return the ReportReceiver here. I prefer we don't return it so that no one will accidentally use it and then we'll need to migrate their test code
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 258 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/564#-O58PYYt3Wfljyh6Sz_h:-O58Sd_yBDlQHCvUJgLv:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5351092e4561de8369bf1883958d5dbb752e964a/crates/sequencing/papyrus_consensus/src/manager.rs#L258)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

call broadcasted_message_manager.continue_propagation()
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/564#-:-O58Tveu03NNgywDkG6U:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Review by matan-starkware — DISMISSED** [review]
> Reviewed 3 of 8 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/564)* status: all files reviewed, 3 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 816 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/564#-O5CwmyL4XT6kKt4j6mS:-O5CwmyL4XT6kKt4j6mT:buxseon) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d7da96724b47e29bc129b271ef0778323966c77/crates/papyrus_network/src/network_manager/mod.rs#L816)):*
> ```XML
>     report_sender: ReportSender,
> }
> impl BroadcastedMessageManager {
> ```

IIUC the network wants this feedback as part of the gossip protocol:
- report_peer = this is a bad message, I don't want to forward it and I maybe want to "punish" the sender.
- continue_propogation = the message is fine to forward.

1. What is required of the user. Is there a potential future where the user must call to `continue_propogation`? What happens if this is dropped with no call being made (should we make this call part of the drop implementation?)

2. These functions are called by the end user. Are these names details that the caller shouldn't need to consider. As in we could put functions `err()` and `ok()` if we don't want the user to be aware of what these calls do. On the other hand, maybe it makes sense as the caller to understand that we are in a gossip network.



_Code quote:_
```XML
impl BroadcastedMessageManager {
```
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 127 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/564#-O5CzyXg9A-NG1cpvkve:-O5CzyXg9A-NG1cpvkvf:bmn2ud5) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d7da96724b47e29bc129b271ef0778323966c77/crates/sequencing/papyrus_consensus/src/manager.rs#L127)):*
> ```XML
>                     BroadcastedMessageManager,
>                 ),
>             > + Unpin,
> ```

This is getting unweildy. What about defining a type, either:
1. In consensus `type BroadcastItem = (Result<ConsensusMessage, ProtobufConversionError>, BroadcastedMessageManager)`
2. In network `type BroadcastItem<T> = (Result<T, ProtobufConversionError>, BroadcastedMessageManager)`



_Code quote:_
```XML
        NetworkReceiverT: Stream<
                Item = (
                    Result<ConsensusMessage, ProtobufConversionError>,
                    BroadcastedMessageManager,
                ),
            > + Unpin,
```
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 260 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/564#-O5D0cWs8Cnj4yThYnTx:-O5D0cWs8Cnj4yThYnTy:b-uyx3ip) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d7da96724b47e29bc129b271ef0778323966c77/crates/sequencing/papyrus_consensus/src/manager.rs#L260)):*
> ```XML
>         })?;
>     match msg {
>         // TODO(matan): Return report_sender for use in later errors by SHC.
> ```

OOS for you, but I want to bring up the future usage. Currently we make the report/continue decision purely based on receiving a message. It is possible that later the message will turn out to be invalid (invalid signature). I presume that in such a case we should also `report_sender`?



_Code quote:_
```XML
        // TODO(matan): Return report_sender for use in later errors by SHC.
```

**Review by ShahakShama — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/564)* status: all files reviewed, 3 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 816 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/564#-O5CwmyL4XT6kKt4j6mS:-O5HKDaf9_RCuXhYHSvw:b-cuv431) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d7da96724b47e29bc129b271ef0778323966c77/crates/papyrus_network/src/network_manager/mod.rs#L816)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

IIUC the network wants this feedback as part of the gossip protocol:
- report_peer = this is a bad message, I don't want to forward it and I maybe want to "punish" the sender.
- continue_propogation = the message is fine to forward.

1. What is required of the user. Is there a potential future where the user must call to `continue_propogation`? What happens if this is dropped with no call being made (should we make this call part of the drop implementation?)

2. These functions are called by the end user. Are these names details that the caller shouldn't need to consider. As in we could put functions `err()` and `ok()` if we don't want the user to be aware of what these calls do. On the other hand, maybe it makes sense as the caller to understand that we are in a gossip network.
</blockquote></details>

You're understanding is correct. report_peer punishes the sender
1. It's ok to drop it without calling any method. It means that you don't want to forward this message but you don't want to penalize the sender. We plan doing it in the mempool for unprioritized transactions
2. I didn't understand the question
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 127 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/564#-O5CzyXg9A-NG1cpvkve:-O5HJnQECKCd9iip7wgY:b-yz1y3p) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d7da96724b47e29bc129b271ef0778323966c77/crates/sequencing/papyrus_consensus/src/manager.rs#L127)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This is getting unweildy. What about defining a type, either:
1. In consensus `type BroadcastItem = (Result<ConsensusMessage, ProtobufConversionError>, BroadcastedMessageManager)`
2. In network `type BroadcastItem<T> = (Result<T, ProtobufConversionError>, BroadcastedMessageManager)`
</blockquote></details>

Eitan and I had a discussion whether to have the message inside BroadcastedMessageManager. Do you think I made the wrong call and we should insert Result<T, ...> into BroadcastedMessageManager?
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 260 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/564#-O5D0cWs8Cnj4yThYnTx:-O5HJawKDL5p0ytbQU8v:b3zj96t) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d7da96724b47e29bc129b271ef0778323966c77/crates/sequencing/papyrus_consensus/src/manager.rs#L260)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

OOS for you, but I want to bring up the future usage. Currently we make the report/continue decision purely based on receiving a message. It is possible that later the message will turn out to be invalid (invalid signature). I presume that in such a case we should also `report_sender`?
</blockquote></details>

Yes. It's ok to call continue_propagation and then call report_peer

**Review by ShahakShama — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/564)* status: all files reviewed, 3 unresolved discussions (waiting on @matan-starkware)

**Review by eitanm-starkware — COMMENTED** [review]
> Dismissed @matan-starkware from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/564)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 127 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/564#-O5CzyXg9A-NG1cpvkve:-O5D4dAe5JjUsmStDowQ:b-32p01z) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d7da96724b47e29bc129b271ef0778323966c77/crates/sequencing/papyrus_consensus/src/manager.rs#L127)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This is getting unweildy. What about defining a type, either:
1. In consensus `type BroadcastItem = (Result<ConsensusMessage, ProtobufConversionError>, BroadcastedMessageManager)`
2. In network `type BroadcastItem<T> = (Result<T, ProtobufConversionError>, BroadcastedMessageManager)`
</blockquote></details>

good call. ill introduce the type in the network.

**Comment by matan-starkware** [comment]
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 127 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/564#-O5CzyXg9A-NG1cpvkve:-O5S9sbl-kkNfqPMkdHY:b-m2kcfo) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d7da96724b47e29bc129b271ef0778323966c77/crates/sequencing/papyrus_consensus/src/manager.rs#L127)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

good call. ill introduce the type in the network.
</blockquote></details>

@ShahakShama, I wasn't thinking that radically. I think I prefer the option to handle the message as its own field (e.g., the decision you made). My comment was shallow, just about how long the type became.

**Comment by matan-starkware** [comment]
*[`crates/papyrus_network/src/network_manager/mod.rs` line 816 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/564#-O5CwmyL4XT6kKt4j6mS:-O5lGne74QDluJXBnBAA:b-flti9n) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d7da96724b47e29bc129b271ef0778323966c77/crates/papyrus_network/src/network_manager/mod.rs#L816)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You're understanding is correct. report_peer punishes the sender
1. It's ok to drop it without calling any method. It means that you don't want to forward this message but you don't want to penalize the sender. We plan doing it in the mempool for unprioritized transactions
2. I didn't understand the question
</blockquote></details>

It was an encapsulation question. The network receives a message and then wants to receive feedback about the quality of the message to decide:
1. Msg good - Propogate to peers
2. Msg good - Don't propagate to peers
3. Msg bad - don't propagate and stop listening to this peer

My thought had been that maybe we don't want the user to know that "msg good" maps to "continue propagating" and so we should instead name the function "ok/valid/msg_good". The fact that we need to differentiate between "good propagate" and "good don't propagate" though means we expect users to care about this detail. Therefore I accept your naming.

**Pull request merged**
