### PR TITLE
feat(consensus): implement ComponentStarter for the consensus manager component

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1199)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1199?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1199** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1199?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1198** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1198?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1197** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1197?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1196** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1196?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1195** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1195?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1194** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1194?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1193** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1193?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1192** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1192?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1199)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @matan-starkware)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1199#-O8WeHhKAceJZlT2Y9Dc):*
These might change in the future



_Code quote:_
```
  cargo run --package starknet_mempool_node --bin starknet_mempool_node -- \
    --consensus_manager_config.consensus_config.validator_id 0x0 \
    --batcher_config.storage.db_config.enforce_file_exists false
```
___
*[`crates/consensus_manager/src/consensus_manager.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1199#-O8WeZ152yDWrq9TU9ft:-O8WeZ164dsem8i2pRNy:bdzxo0j) ([raw file](https://github.com/starkware-libs/sequencer/blob/b79634891980fd2f8d6afead9283299679605738/crates/consensus_manager/src/consensus_manager.rs#L36)):*
> ```XML
>     pub async fn run(&self) -> Result<(), ConsensusError> {
>         let context = SequencerConsensusContext::new(
>             Arc::clone(&self.batcher_client),
> ```

Why not`&self.batcher_client.clone`?



_Code quote:_
```XML
Arc::clone(&self.batcher_client),
```
___
*[`crates/consensus_manager/src/consensus_manager.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1199#-O8Wepdt2FpBjYR24xYb:-O8Wepdt2FpBjYR24xYc:b-d2s6vn) ([raw file](https://github.com/starkware-libs/sequencer/blob/b79634891980fd2f8d6afead9283299679605738/crates/consensus_manager/src/consensus_manager.rs#L85)):*
> ```XML
> impl ComponentStarter for ConsensusManager {
>     async fn start(&mut self) -> Result<(), ComponentError> {
>         info!("Starting component {}.", type_name::<Self>());
> ```

You can be explicit with the name, i.e., `type_name::<Self>()` -> `ConsensusManager`



_Code quote:_
```XML
 info!("Starting component {}.", type_name::<Self>());
```

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1199)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @Itay-Tsabary-Starkware)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1199#-O8WeHhKAceJZlT2Y9Dc):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

These might change in the future
</blockquote></details>

Yes, that's why it is part of the commit message not codified in a README
___
*[`crates/consensus_manager/src/consensus_manager.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1199#-O8WeZ152yDWrq9TU9ft:-O8Wg-ofDYnmgeBo3pCT:b-ct43ih) ([raw file](https://github.com/starkware-libs/sequencer/blob/b79634891980fd2f8d6afead9283299679605738/crates/consensus_manager/src/consensus_manager.rs#L36)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Why not`&self.batcher_client.clone`?
</blockquote></details>

That's the style I remember learning (I generalized from Rc to Arc)

https://doc.rust-lang.org/book/ch15-04-rc.html#using-rct-to-share-data
```
We could have called a.clone() rather than Rc::clone(&a), but Rust’s convention is to use Rc::clone in this case. The implementation of Rc::clone doesn’t make a deep copy of all the data like most types’ implementations of clone do. The call to Rc::clone only increments the reference count, which doesn’t take much time. Deep copies of data can take a lot of time. By using Rc::clone for reference counting, we can visually distinguish between the deep-copy kinds of clones and the kinds of clones that increase the reference count. When looking for performance problems in the code, we only need to consider the deep-copy clones and can disregard calls to Rc::clone.
```

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1199#-:-O8Wi-vI4wIlREH2DPVS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r3, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1199)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by matan-starkware** [comment]
### Merge activity

* **Oct 13, 5:42 AM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1199).

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1199#-:-O94K0NcD-1JHHnk9cso:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
