### PR TITLE
fix(mempool): make `add_tx` look at correct mempool nonce

### PR DESCRIPTION
**Pull request by elintul**

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1657)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/tests/flow_test.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1657#-OANa-Hp8LX8lwbc_OY1:-OANa-Hp8LX8lwbc_OY2:b-ye1jhv) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba46ce4a016670a100c74a88ff974b3aa54fce33/crates/mempool/tests/flow_test.rs#L110)):*
> ```XML
> 
> #[rstest]
> fn test_add_tx_considers_already_given_nonce(mut mempool: Mempool) {
> ```

Not sure about this name.
In any case, should be consistent with [this](https://github.com/starkware-libs/sequencer/blob/dd4371c2f345dad70714621efabeef71f898566e/crates/mempool/tests/flow_test.rs#L51) test's name, since they test a similar scenario.



_Code quote:_
```XML
given_nonce
```

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1657)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/tests/flow_test.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1657#-OANa-Hp8LX8lwbc_OY1:-OAO7RFK6tZQ3fdIjWxD:buyixyq) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba46ce4a016670a100c74a88ff974b3aa54fce33/crates/mempool/tests/flow_test.rs#L110)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure about this name.
In any case, should be consistent with [this](https://github.com/starkware-libs/sequencer/blob/dd4371c2f345dad70714621efabeef71f898566e/crates/mempool/tests/flow_test.rs#L51) test's name, since they test a similar scenario.
</blockquote></details>

The link does not work for me.
___
*[`crates/mempool/tests/flow_test.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1657#-OAOBYaH6grWRqaLKinG:-OAOBYaI6PzxP_-UhKBs:bjqenyf) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba46ce4a016670a100c74a88ff974b3aa54fce33/crates/mempool/tests/flow_test.rs#L110)):*
> ```XML
> 
> #[rstest]
> fn test_add_tx_considers_already_given_nonce(mut mempool: Mempool) {
> ```

The test fails w/o the fix?



_Code quote:_
```XML
test_add_tx_considers_already_given_nonce
```
___
*[`crates/mempool/tests/flow_test.rs` line 112 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1657#-OAO8pTh7g7BWD8H4S8E:-OAO8pTi0R5-EPvZhaCf:bk38m7i) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba46ce4a016670a100c74a88ff974b3aa54fce33/crates/mempool/tests/flow_test.rs#L112)):*
> ```XML
> fn test_add_tx_considers_already_given_nonce(mut mempool: Mempool) {
>     // Setup.
>     let input_nonce_0 = add_tx_input!(tx_hash: 1, address: "0x0", tx_nonce: 0, account_nonce: 0);
> ```

Do we need to add the address arg here?



_Code quote:_
```XML
 address: "0x0",
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1657)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/tests/flow_test.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1657#-OAOBYaH6grWRqaLKinG:-OAOCWY79f40FTcgTCm_:b9c823) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba46ce4a016670a100c74a88ff974b3aa54fce33/crates/mempool/tests/flow_test.rs#L110)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

The test fails w/o the fix?
</blockquote></details>

I'm asking because I believe the account_nonce of the second tx should be 0, so in that case, the mempool state would be more updated than the account nonce.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1657)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/tests/flow_test.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1657#-OAOBYaH6grWRqaLKinG:-OAOQCBN9zLRPtrTghck:b-62h5db) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba46ce4a016670a100c74a88ff974b3aa54fce33/crates/mempool/tests/flow_test.rs#L110)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I'm asking because I believe the account_nonce of the second tx should be 0, so in that case, the mempool state would be more updated than the account nonce.
</blockquote></details>

Yeah, got a bit confused. Fixed the PR (logic and tests).
___
*[`crates/mempool/tests/flow_test.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1657#-OANa-Hp8LX8lwbc_OY1:-OAlRb1f3e1rN9xn0Btr:b-xt9nsf) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba46ce4a016670a100c74a88ff974b3aa54fce33/crates/mempool/tests/flow_test.rs#L110)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

The link does not work for me.
</blockquote></details>

Works.
___
*[`crates/mempool/tests/flow_test.rs` line 112 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1657#-OAO8pTh7g7BWD8H4S8E:-OAOQ1dVA6j5vViz2ZLq:bkut4lt) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba46ce4a016670a100c74a88ff974b3aa54fce33/crates/mempool/tests/flow_test.rs#L112)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Do we need to add the address arg here?
</blockquote></details>

I want it to be clear it's the same account.

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1657#-:-OAlVSfeAEKoFkQQNh9R:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1657)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/tests/flow_test.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1657#-OANa-Hp8LX8lwbc_OY1:-OAlarXA6ZQ_ZclJZ7jf:b-txg3gg) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba46ce4a016670a100c74a88ff974b3aa54fce33/crates/mempool/tests/flow_test.rs#L110)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Works.
</blockquote></details>

I see this test:
"test_add_tx_rejection_for_txs_passed_to_batcher"

And to be honest, I do not see consistency between the names.

I thought the link did not work because I saw this error:
"This commit does not belong to any branch on this repository,"
___
*[`crates/mempool/tests/flow_test.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1657#-OAlbENE9OM1OkjiLj4R:-OAlbENFCWEcVilz2LdI:b9vyhg8) ([raw file](https://github.com/starkware-libs/sequencer/blob/2151c534cecbacaf112dfed71543ca6827430426/crates/mempool/tests/flow_test.rs#L109)):*
> ```XML
> 
> #[rstest]
> fn test_add_tx_handles_nonces_correctly(mut mempool: Mempool) {
> ```

IIUC, this test verifies that adding a transaction with an 'old' account nonce updates the queue according to the `mempool_state`.

Could we make the test name more descriptive? The current name seems a bit generic.



_Code quote:_
```XML
test_add_tx_handles_nonces_correctly
```
___
*[`crates/mempool/tests/flow_test.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1657#-OAla02K6TjkOvzXmFtQ:-OAla02K6TjkOvzXmFtR:bmicjcj) ([raw file](https://github.com/starkware-libs/sequencer/blob/2151c534cecbacaf112dfed71543ca6827430426/crates/mempool/tests/flow_test.rs#L120)):*
> ```XML
>     // Although the input account nonce is higher, mempool looks at its internal registry.
>     add_tx(&mut mempool, &input_nonce_1);
>     get_txs_and_assert_expected(&mut mempool, 2, &[input_nonce_0.tx, input_nonce_1.tx]);
> ```

This code can be tested in a unit test, right?
Do we need to have it here?



_Code quote:_
```XML
    // Account is registered in mempool.
    add_tx(&mut mempool, &input_nonce_0);
    // Although the input account nonce is higher, mempool looks at its internal registry.
    add_tx(&mut mempool, &input_nonce_1);
    get_txs_and_assert_expected(&mut mempool, 2, &[input_nonce_0.tx, input_nonce_1.tx]);
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1657)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/tests/flow_test.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1657#-OANa-Hp8LX8lwbc_OY1:-OAlcYNbDvW0cBHtLHk6:bxj2l1e) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba46ce4a016670a100c74a88ff974b3aa54fce33/crates/mempool/tests/flow_test.rs#L110)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I see this test:
"test_add_tx_rejection_for_txs_passed_to_batcher"

And to be honest, I do not see consistency between the names.

I thought the link did not work because I saw this error:
"This commit does not belong to any branch on this repository,"
</blockquote></details>

Nevermind, this comment is stale. Retracting.
___
*[`crates/mempool/tests/flow_test.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1657#-OAlbENE9OM1OkjiLj4R:-OAlc0RL5z0Dt_oMqySj:bmcukuu) ([raw file](https://github.com/starkware-libs/sequencer/blob/2151c534cecbacaf112dfed71543ca6827430426/crates/mempool/tests/flow_test.rs#L109)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

IIUC, this test verifies that adding a transaction with an 'old' account nonce updates the queue according to the `mempool_state`.

Could we make the test name more descriptive? The current name seems a bit generic.
</blockquote></details>

Why? It's exactly what it does. Any more details will expose implementation.
___
*[`crates/mempool/tests/flow_test.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1657#-OAla02K6TjkOvzXmFtQ:-OAlcCfBEhpvrVKA-SBJ:b-2pkrw5) ([raw file](https://github.com/starkware-libs/sequencer/blob/2151c534cecbacaf112dfed71543ca6827430426/crates/mempool/tests/flow_test.rs#L120)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

This code can be tested in a unit test, right?
Do we need to have it here?
</blockquote></details>

No, more than one API is a flow. The two sequential `add_tx`s can become a unit, but unnecessary IMO. We should also be careful not to overtest (tests are code, which should be maintained).

**Pull request merged**
