### PR TITLE
refactor(mempool): make mempool content ctor receives transaction iter

### PR DESCRIPTION
**Pull request by MohammadNassar1**

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1751)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1751#-OAmkRaW5XgodzUtBP59:-OAmkRaW5XgodzUtBP5A:b-b2372u) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee4a5ad97767fd18a867d7dab336918dd8e683bf/crates/mempool/src/mempool_test.rs#L83)):*
> ```XML
>     fn with_priority_queue<'a, Q>(mut self, queue_txs: Q) -> Self
>     where
>         Q: IntoIterator<Item = &'a Transaction>,
> ```

why is that needed?



_Code quote:_
```XML
'a
```
___
*[`crates/mempool/src/mempool_test.rs` line 474 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1751#-OAmnIa7CW-yuHAhFlMk:-OAmnIa7CW-yuHAhFlMl:b3j2yow) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee4a5ad97767fd18a867d7dab336918dd8e683bf/crates/mempool/src/mempool_test.rs#L474)):*
> ```XML
>         tx_address_1_nonce_3.clone(),
>         tx_address_2_nonce_1.clone(),
>     ];
> ```

Consider moving inside `MempoolContentBuilder` for consistency.
Same for other locations if there are any.



_Code quote:_
```XML
    let queue_txs = [&tx_address_2_nonce_1, &tx_address_1_nonce_3, &tx_address_0_nonce_4];
    let pool_txs = [
        tx_address_0_nonce_3,
        tx_address_0_nonce_4.clone(),
        tx_address_0_nonce_5.clone(),
        tx_address_1_nonce_2,
        tx_address_1_nonce_3.clone(),
        tx_address_2_nonce_1.clone(),
    ];
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1751)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1751#-OAmkRaW5XgodzUtBP59:-OAmq4gxCvG7CuKj9nvv:bfdlafi) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee4a5ad97767fd18a867d7dab336918dd8e683bf/crates/mempool/src/mempool_test.rs#L83)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why is that needed?
</blockquote></details>

It's a lifetime parameter, as it gets a reference. It specifies that the lifetime of the reference to each `Transaction` in the iterator will match a single, consistent lifetime `'a` across all items.
___
*[`crates/mempool/src/mempool_test.rs` line 474 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1751#-OAmnIa7CW-yuHAhFlMk:-OAmsxk3AdIAoBeHGqYN:b7l93kj) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee4a5ad97767fd18a867d7dab336918dd8e683bf/crates/mempool/src/mempool_test.rs#L474)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Consider moving inside `MempoolContentBuilder` for consistency.
Same for other locations if there are any.
</blockquote></details>

I’d prefer to handle it in a separate PR to keep this one manageable and easy to review.

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1751)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1751#-OBQBaos-TPh1disa9Or:-OBQBaot4Temo0nHdOZr:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee4a5ad97767fd18a867d7dab336918dd8e683bf/crates/mempool/src/mempool_test.rs#L223)):*
> ```XML
>         .build_into_mempool();
> 
>     let expected_pool_txs = [tx.clone()];
> ```





_Suggestion:_
```XML
[tx]
```

**Comment by MohammadNassar1** [comment]
This task was given to NoamP.

**Pull request closed without merging**
