### PR TITLE
refactor(mempool): remove u8 from mempool tests

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1047)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1047)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1047#-O7iMOUD3Of5j4mhE8qK:-O7iMOUE91TSKeqjphI6:b-yhj86k) (no related file):*
Please make sure to mention the following to your reviewer in these kind of broad (unenforceable) changes: were all relevant locations changed?

+ what about other types, e.g. `u16`? 

___

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1047)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1047#-O7iMOUD3Of5j4mhE8qK:-O7iRX533ALmQSEnqfBn:b-8ebfjt) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please make sure to mention the following to your reviewer in these kind of broad (unenforceable) changes: were all relevant locations changed?

+ what about other types, e.g. `u16`?
</blockquote></details>

I've checked and found no remaining instances of `u_` or `i_` types (like `u16`, `i8`, etc.) in the file. 

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1047)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1047#-O7iMOUD3Of5j4mhE8qK:-O7iUgZz603YxwBK2zW5:b14r963) (no related file):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I've checked and found no remaining instances of `u_` or `i_` types (like `u16`, `i8`, etc.) in the file.
</blockquote></details>

Please check in all mempool crate.

___

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1047)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1047#-O7iMOUD3Of5j4mhE8qK:-O7ihW675z87P03nLL60:b-878ojr) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please check in all mempool crate.
</blockquote></details>

Done. Didn't find other locations to change. 

___

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1047#-:-O7jDXJX2SsfVXF0ovzU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
