### PR TITLE
feat(consensus): consensus default config enables single node execution

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1373)

### CODE REVIEW

**Comment by matan-starkware** [comment]
* **#1373** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1373?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1373#-:-O96Dvkq62uB-stocVJq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1373)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Comment by matan-starkware** [comment]
### Merge activity

* **Oct 15, 7:50 AM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1373).

**Pull request merged**
