### PR TITLE
chore(blockifier): add erc20 sierra contract

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2668?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2668** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2668?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2668?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2614** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2614?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2641](https://github.com/starkware-libs/sequencer/pull/2641) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2641?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2493** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2493?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2438** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2438?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2420** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2420?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2421](https://github.com/starkware-libs/sequencer/pull/2421) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2421?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2467** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2467?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2466** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2466?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by AvivYossef-starkware — COMMENTED** [review]
The contact is taken from [here](https://github.com/starkware-libs/cairo/blob/5ea64d69c8b98be77577c96200d6574722c07d1e/crates/cairo-lang-starknet/test_data/erc20__erc_20.contract_class.json)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2668#-:-OE9Ho_67945vhMge6AW:b-wdrwgh)* status: 0 of 2 files reviewed, all discussions resolved

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2668)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2668#-OE9RUV9E_zX1WMdUN7p:-OE9RUV9E_zX1WMdUN7q:b-7rfbep) ([raw file](https://github.com/starkware-libs/sequencer/blob/57b45d355a357c37db4d66602ad15cc6d726a1fc/crates/blockifier/src/test_utils/contracts.rs#L294)):*
> ```XML
>         assert_ne!(self.cairo_version(), CairoVersion::Cairo0);
>         // TODO (Meshi 01/01/2025): add a spacial case for ERC20 when ERC20 sierra is supported.
>         assert!(!matches!(self, &Self::ERC20(CairoVersion::Cairo1(_))));
> ```

I am not sure about the comment phrasing but, I would like to have the fact that this is not the ERC20 compiled Sierra documented.  



_Suggestion:_
```XML
 // This is not the compiled Sierra file of the existing ERC20 contract, 
 // but a file that was taken from the compiler repo of another ERC20 contract. 
 if matches!(self, &Self::ERC20(CairoVersion::Cairo1(_))) {
     return ERC20_SIERRA_CONTRACT_PATH;
}
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2668#-OE9R9MxDNt9x5lEjGk4:-OE9R9MxDNt9x5lEjGk5:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/a38fb1dff095fb092a7e3cfa540353a0ac5006ad/crates/blockifier/src/test_utils/contracts.rs#L83)):*
> ```XML
>                                           erc20_contract_without_some_syscalls_compiled.json";
> const ERC20_CAIRO1_CONTRACT_SOURCE_PATH: &str = "./ERC20/ERC20_Cairo1/ERC20.cairo";
> const ERC20_CONTRACT_NAME: &str = "erc20_contract";
> ```





_Suggestion:_
```XML
const ERC20_SIERRA_CONTRACT_PATH: &str = "./ERC20/ERC20_Cairo1/erc20.sierra.json";
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2668#-OE9QMO4C4MUQeOdp4pW:-OE9QMO4C4MUQeOdp4pX:b-utdn1y) ([raw file](https://github.com/starkware-libs/sequencer/blob/a38fb1dff095fb092a7e3cfa540353a0ac5006ad/crates/blockifier/src/test_utils/contracts.rs#L253)):*
> ```XML
>     }
> 
>     fn get_non_erc20_base_name(&self) -> &str {
> ```

Change the name if it also returns the ERC20 contract 



_Code quote:_
```XML
get_non_erc20_base_name
```
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 264 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2668#-OE9ROBf7zOfKdTC63eZ:-OE9ROBf7zOfKdTC63e_:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/a38fb1dff095fb092a7e3cfa540353a0ac5006ad/crates/blockifier/src/test_utils/contracts.rs#L264)):*
> ```XML
>             Self::CairoStepsTestContract => CAIRO_STEPS_TEST_CONTRACT_NAME,
>             Self::SierraExecutionInfoV1Contract(_) => EXECUTION_INFO_V1_CONTRACT_NAME,
>             Self::ERC20(_) => ERC20_CONTRACT_NAME,
> ```





_Suggestion:_
```XML
 Self::ERC20(_) => unreachable!(),
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2668)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @meship-starkware)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2668#-OE9QMO4C4MUQeOdp4pW:-OE9d64LBOxhRZrTyGoO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a38fb1dff095fb092a7e3cfa540353a0ac5006ad/crates/blockifier/src/test_utils/contracts.rs#L253)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Change the name if it also returns the ERC20 contract
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/contracts.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2668#-OE9RUV9E_zX1WMdUN7p:-OE9d76KBYqPwmhrQODq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/57b45d355a357c37db4d66602ad15cc6d726a1fc/crates/blockifier/src/test_utils/contracts.rs#L294)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I am not sure about the comment phrasing but, I would like to have the fact that this is not the ERC20 compiled Sierra documented.
</blockquote></details>

Done.

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2668)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/sierra/erc20_contract.sierra.json` line 49 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2668#-OE9eZRc8OIehIlcFrhf:-OE9eZRc8OIehIlcFrhg:b-y8ftg) ([raw file](https://github.com/starkware-libs/sequencer/blob/df0d54648724e73728f648b7db1867d7074c245c/crates/blockifier/feature_contracts/cairo1/sierra/erc20_contract.sierra.json#L49)):*
> ```JSON
>         "0x2ee1e2b1b89f8c495f200e4956278a4d47395fe262f27b52e5865c9524c08c3",
>         "0x3288d594b9a45d15bb2fcb7903f06cdb06b27f0ba88186ec4cfaa98307cb972",
>         "0x11",
> ```

Move this file to crates/blockifier/ERC20/ERC20_Cairo1

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2668)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2668)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2668)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/sierra/erc20_contract.sierra.json` line 49 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2668#-OE9eZRc8OIehIlcFrhf:-OE9lZVWAUWSzPbZcf6x:b2ni9hp) ([raw file](https://github.com/starkware-libs/sequencer/blob/e83ae75fe6408802274917bc6c3c30e88b2c5e8b/crates/blockifier/feature_contracts/cairo1/sierra/erc20_contract.sierra.json#L49)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Move this file to crates/blockifier/ERC20/ERC20_Cairo1
</blockquote></details>

ops

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2668)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2668#-:-OEDw5y60GUbpbz5kO6v:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Comment by AvivYossef-starkware** [comment]
### Merge activity

* **Dec 17, 3:08 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2668).

**Pull request merged**
