### PR TITLE
feat(batcher): add test for abort and restart height

### PR DESCRIPTION
**Pull request by dafnamatsry**

### CODE REVIEW

**Comment by dafnamatsry** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1687?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1687** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1687?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1683** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1683?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dafnamatsry and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1687#-:-OAX6NKn8DLCoDIPlg0a:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by alonh5 — APPROVED** [review]
Nice!
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1687#-:-OAXZmox5DQT95hj-Yq7:b-ojic6h)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

___
*[`crates/batcher/src/proposal_manager_test.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1687#-OAXZVC6C9FU8vNr1VFX:-OAXZVC6C9FU8vNr1VFY:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/19da89cf49fd3c95ee0739e4b9eb64c63784f09e/crates/batcher/src/proposal_manager_test.rs#L253)):*
> ```XML
> 
>     // Start a new height and create a proposal.
>     let (output_tx_sender, _rec) = output_streaming();
> ```





_Suggestion:_
```XML
_receiver
```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1687)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @alonh5 and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager_test.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1687#-OAXZVC6C9FU8vNr1VFX:-OAXenpmD5aUuJuqY7G2:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/19da89cf49fd3c95ee0739e4b9eb64c63784f09e/crates/batcher/src/proposal_manager_test.rs#L253)):*
> ```XML
> 
>     // Start a new height and create a proposal.
>     let (output_tx_sender, _rec) = output_streaming();
> ```

Done.

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1687)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1687)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Comment by dafnamatsry** [comment]
### Merge activity

* **Oct 31, 10:50 AM EDT**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1687).

**Pull request merged**
