### PR TITLE
feat(mempool): add basic p2p agent interface with unimplemented code

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
+reviewer:@ittaysw +reviewer:@giladchase 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479#-:-O4L49r07618qSrCiy6h:b-w4aouj)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @dan-starkware, @eitanm-starkware, @elintul, @giladchase, @ittaysw, and @liorgold2)

**Review by ShahakShama — COMMENTED** [review]
+reviewer:@lev-starkware +reviewer:@Itay-Tsabary-Starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479#-:-O4L4KNaAbNdcdvLlPmm:b-7oc242)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @dan-starkware, @eitanm-starkware, @elintul, @giladchase, @ittaysw, @lev-starkware, and @liorgold2)

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @eitanm-starkware, @giladchase, @Itay-Tsabary-Starkware, @ittaysw, @lev-starkware, @liorgold2, and @ShahakShama)

___
*[`crates/mempool_p2p_agent/src/lib.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O4Z0pzc1tUlLCORwTZS:-O4Z0pzc1tUlLCORwTZT:b-gk2pzv) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0de9edaf422459f4cd96e580e610f34d7c16d6d/crates/mempool_p2p_agent/src/lib.rs#L13)):*
> ```XML
> // TODO: In gateway, use this instead of MempoolClient.
> #[async_trait]
> pub trait MempoolP2PAgentClient: Send + Sync {
> ```

So that in snake case it would be `p2p` and not `p2_p` (although convention wins and I see many `P2P` throughout the code).



_Suggestion:_
```XML
P2p
```
___
*[`crates/mempool_p2p_agent/src/lib.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O4Z0nO_DuHyXuKy1Vqk:-O4Z0nO_DuHyXuKy1Vql:b-bx0mlk) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0de9edaf422459f4cd96e580e610f34d7c16d6d/crates/mempool_p2p_agent/src/lib.rs#L14)):*
> ```XML
> #[async_trait]
> pub trait MempoolP2PAgentClient: Send + Sync {
>     async fn add_transaction(&self, mempool_input: MempoolInput) -> ClientResult<()>;
> ```

Convention.



_Suggestion:_
```XML
add_tx
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @eitanm-starkware, @giladchase, @Itay-Tsabary-Starkware, @ittaysw, @lev-starkware, @liorgold2, and @ShahakShama)

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @eitanm-starkware, @giladchase, @Itay-Tsabary-Starkware, @ittaysw, @lev-starkware, @liorgold2, and @ShahakShama)

___
*[`crates/mempool_p2p_agent/src/lib.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O4erlo162JfO9MI6Hrr:-O4erlo29FvzpLiqQpOs:b2qpw51) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0de9edaf422459f4cd96e580e610f34d7c16d6d/crates/mempool_p2p_agent/src/lib.rs#L14)):*
> ```XML
> #[async_trait]
> pub trait MempoolP2PAgentClient: Send + Sync {
>     async fn add_transaction(&self, mempool_input: MempoolInput) -> ClientResult<()>;
> ```

Not sure about the transaction type here.



_Code quote:_
```XML
mempool_input: MempoolInput
```

**Review by giladchase — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @eitanm-starkware, @Itay-Tsabary-Starkware, @ittaysw, @lev-starkware, @liorgold2, and @ShahakShama)

___
*[`crates/mempool_p2p_agent/src/lib.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O5CGMyG3rGyU2DEO-Ta:-O5CGMyG3rGyU2DEO-Tb:bwq5vg3) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0de9edaf422459f4cd96e580e610f34d7c16d6d/crates/mempool_p2p_agent/src/lib.rs#L19)):*
> ```XML
> pub type SharedMempoolP2PAgentClient = Arc<dyn MempoolP2PAgentClient>;
> 
> #[allow(dead_code)]
> ```

Maybe instead we can rename `MempoolP2pAgent` -> `_MempoolP2PAgent`?

Will save us from remembering to delete the `allow(dead_code)` later.



_Code quote:_
```XML
#[allow(dead_code)]
```
___
*[`crates/mempool_p2p_agent/src/lib.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O5CHHB3AVAZHY7t8SoC:-O5CHHB3AVAZHY7t8SoD:b-x1fv62) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0de9edaf422459f4cd96e580e610f34d7c16d6d/crates/mempool_p2p_agent/src/lib.rs#L21)):*
> ```XML
> #[allow(dead_code)]
> pub struct MempoolP2PAgent {
>     mempool_client: SharedMempoolClient,
> ```

Can this be pub? is there some invariant on this that needs to be kept?



_Code quote:_
```XML
    mempool_client: SharedMempoolClient,
```
___
*[`crates/mempool_p2p_agent/src/lib.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O5CHVDs3IACrD8tEYIM:-O5CHVDtCoakFILo8w7S:bywwk9t) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0de9edaf422459f4cd96e580e610f34d7c16d6d/crates/mempool_p2p_agent/src/lib.rs#L27)):*
> ```XML
> #[async_trait]
> impl ComponentStarter for MempoolP2PAgent {
>     async fn start(&mut self) -> Result<(), ComponentStartError> {
> ```

I think the convention is run at other components? not sure



_Code quote:_
```XML
    async fn start(&mut self) -> Result<(), ComponentStartError> {
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @eitanm-starkware, @elintul, @giladchase, @Itay-Tsabary-Starkware, @ittaysw, @lev-starkware, and @liorgold2)

___
*[`crates/mempool_p2p_agent/src/lib.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O4Z0nO_DuHyXuKy1Vqk:-O5HbK1cAQ0tN6k95EuX:b-40jnv4) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0de9edaf422459f4cd96e580e610f34d7c16d6d/crates/mempool_p2p_agent/src/lib.rs#L14)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Convention.
</blockquote></details>

Added TODO in mempool to rename this
___
*[`crates/mempool_p2p_agent/src/lib.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O4erlo162JfO9MI6Hrr:-O5HbNJd7jmHwKUu8Ex5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0de9edaf422459f4cd96e580e610f34d7c16d6d/crates/mempool_p2p_agent/src/lib.rs#L14)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure about the transaction type here.
</blockquote></details>

Done.
___
*[`crates/mempool_p2p_agent/src/lib.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O5CHHB3AVAZHY7t8SoC:-O5HbPc7B1taNRvjGpxs:b8xges7) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0de9edaf422459f4cd96e580e610f34d7c16d6d/crates/mempool_p2p_agent/src/lib.rs#L21)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can this be pub? is there some invariant on this that needs to be kept?
</blockquote></details>

I'm against making this pub unless we need it to be pub, and I don't see a reason for pub
Anyway, this is deleted in the new design
___
*[`crates/mempool_p2p_agent/src/lib.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O5CHVDs3IACrD8tEYIM:-O5Has4KDOnyoTzjTaoI:bg7gsbv) ([raw file](https://github.com/starkware-libs/sequencer/blob/a0de9edaf422459f4cd96e580e610f34d7c16d6d/crates/mempool_p2p_agent/src/lib.rs#L27)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think the convention is run at other components? not sure
</blockquote></details>

I'm implementing a trait here, so I can't decide the name. I think that Tsabari's team is working on renaming it to run

**Review by giladchase — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @eitanm-starkware, @elintul, @Itay-Tsabary-Starkware, @ittaysw, @lev-starkware, and @liorgold2)

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @eitanm-starkware, @Itay-Tsabary-Starkware, @ittaysw, @lev-starkware, and @liorgold2)

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @eitanm-starkware, @giladchase, @Itay-Tsabary-Starkware, @ittaysw, @lev-starkware, and @liorgold2)

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479#-:-O5qHDvZDwXbDo93cBED:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @eitanm-starkware, @elintul, @Itay-Tsabary-Starkware, @ittaysw, @lev-starkware, and @liorgold2)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware, @eitanm-starkware, @Itay-Tsabary-Starkware, @ittaysw, @lev-starkware, and @liorgold2)

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @eitanm-starkware, @elintul, @giladchase, @ittaysw, @lev-starkware, @liorgold2, and @ShahakShama)

___
*[`crates/mempool_p2p/src/lib.rs` line 2 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O6GVFOS2082a7YTqSjy:-O6GVFOS2082a7YTqSjz:bc80fyj) ([raw file](https://github.com/starkware-libs/sequencer/blob/551b143c71f7785b6c4ebd833a2a4c0f8d8cf921/crates/mempool_p2p/src/lib.rs#L2)):*
> ```XML
> pub mod receiver;
> pub mod sender;
> ```

What do these modules represent?



_Code quote:_
```XML
pub mod receiver;
pub mod sender;
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @dan-starkware, @eitanm-starkware, @elintul, @giladchase, @ittaysw, @lev-starkware, @liorgold2, and @ShahakShama)

___
*[`crates/mempool_p2p/src/sender/mod.rs` line 30 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O6GVWhCA29J7O6EyI2_:-O6GVWhCA29J7O6EyI2a:b-ubit99) ([raw file](https://github.com/starkware-libs/sequencer/blob/551b143c71f7785b6c4ebd833a2a4c0f8d8cf921/crates/mempool_p2p/src/sender/mod.rs#L30)):*
> ```XML
>     AddTransaction(RpcTransaction),
>     ContinuePropagation(BroadcastedMessageManager),
> }
> ```

Please add `#[derive(Debug, Serialize, Deserialize)]` to this enum.



_Code quote:_
```XML
pub enum MempoolP2PSenderRequest {
    AddTransaction(RpcTransaction),
    ContinuePropagation(BroadcastedMessageManager),
}
```
___
*[`crates/mempool_p2p/src/sender/mod.rs` line 32 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O6GWJD41jGJx3Xdmjuq:-O6GWJD41jGJx3Xdmjur:b-czc2ji) ([raw file](https://github.com/starkware-libs/sequencer/blob/551b143c71f7785b6c4ebd833a2a4c0f8d8cf921/crates/mempool_p2p/src/sender/mod.rs#L32)):*
> ```XML
> }
> 
> pub struct MempoolP2PSenderResponse;
> ```

Please change to enum, populate it with the respective variants, and add `#[derive(Debug, Serialize, Deserialize)]`.



_Code quote:_
```XML
pub struct MempoolP2PSenderResponse;
```
___
*[`crates/mempool_p2p/src/sender/mod.rs` line 60 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O6GWgT1DBqRFEEI4tzH:-O6GWgT2AYmThclTTx_K:bdj30h3) ([raw file](https://github.com/starkware-libs/sequencer/blob/551b143c71f7785b6c4ebd833a2a4c0f8d8cf921/crates/mempool_p2p/src/sender/mod.rs#L60)):*
> ```XML
>     ) -> ClientResult<()> {
>         self.send(MempoolP2PSenderRequest::ContinuePropagation(propagation_manager)).await;
>         Ok(())
> ```

I'd suggest following the example in crates/mempool_types/src/communication.rs

Example:
```
    async fn get_txs(&self, n_txs: usize) -> MempoolClientResult<Vec<Transaction>> {
        let request = MempoolRequest::GetTransactions(n_txs);
        let response = self.send(request).await?;
        handle_response_variants!(
            MempoolResponse,
            GetTransactions,
            MempoolClientError,
            MempoolError
        )
    }
```

Don't forget
`use papyrus\_proc\_macros::handle\_response\_variants;`



_Code quote:_
```XML
        self.send(MempoolP2PSenderRequest::ContinuePropagation(propagation_manager)).await;
        Ok(())
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479)* status: 1 of 8 files reviewed, 4 unresolved discussions (waiting on @dan-starkware, @eitanm-starkware, @elintul, @giladchase, @Itay-Tsabary-Starkware, @ittaysw, @lev-starkware, and @liorgold2)

___
*[`crates/mempool_p2p/src/lib.rs` line 2 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O6GVFOS2082a7YTqSjy:-O6GX9xq-gcwB1uXvMkL:b-jqm3d) ([raw file](https://github.com/starkware-libs/sequencer/blob/551b143c71f7785b6c4ebd833a2a4c0f8d8cf921/crates/mempool_p2p/src/lib.rs#L2)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

What do these modules represent?
</blockquote></details>

The sender and receiver components
___
*[`crates/mempool_p2p/src/sender/mod.rs` line 30 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O6GVWhCA29J7O6EyI2_:-O6GgbYz2W8UrZFHYw3E:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/551b143c71f7785b6c4ebd833a2a4c0f8d8cf921/crates/mempool_p2p/src/sender/mod.rs#L30)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add `#[derive(Debug, Serialize, Deserialize)]` to this enum.
</blockquote></details>

Done.
___
*[`crates/mempool_p2p/src/sender/mod.rs` line 32 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O6GWJD41jGJx3Xdmjuq:-O6Ggbmj3uDR-245j-16:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/551b143c71f7785b6c4ebd833a2a4c0f8d8cf921/crates/mempool_p2p/src/sender/mod.rs#L32)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to enum, populate it with the respective variants, and add `#[derive(Debug, Serialize, Deserialize)]`.
</blockquote></details>

Done.
___
*[`crates/mempool_p2p/src/sender/mod.rs` line 60 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O6GWgT1DBqRFEEI4tzH:-O6Gm9Bk1iOcCvrRJzv5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/551b143c71f7785b6c4ebd833a2a4c0f8d8cf921/crates/mempool_p2p/src/sender/mod.rs#L60)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I'd suggest following the example in crates/mempool_types/src/communication.rs

Example:
```
    async fn get_txs(&self, n_txs: usize) -> MempoolClientResult<Vec<Transaction>> {
        let request = MempoolRequest::GetTransactions(n_txs);
        let response = self.send(request).await?;
        handle_response_variants!(
            MempoolResponse,
            GetTransactions,
            MempoolClientError,
            MempoolError
        )
    }
```

Don't forget
`use papyrus\_proc\_macros::handle\_response\_variants;`
</blockquote></details>

Done.

**Review by ittaysw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479)* status: 1 of 8 files reviewed, 5 unresolved discussions (waiting on @dan-starkware, @eitanm-starkware, @elintul, @giladchase, @Itay-Tsabary-Starkware, @lev-starkware, @liorgold2, and @ShahakShama)

___
*[`crates/mempool_p2p/src/sender/mod.rs` line 43 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O6Kd1ZjCmbpXLQvcqYL:-O6Kd1ZjCmbpXLQvcqYM:b-mlvo7i) ([raw file](https://github.com/starkware-libs/sequencer/blob/e72ea4e3da4a32d6943b937bd1bfa29478d17ea4/crates/mempool_p2p/src/sender/mod.rs#L43)):*
> ```XML
>     async fn continue_propagation(
>         &self,
>         propagation_manager: BroadcastedMessageManager,
> ```

How will this work in a non-local setting?

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 5 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @eitanm-starkware, @giladchase, @lev-starkware, @liorgold2, and @ShahakShama)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r3, 2 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479#-:-O6LMW2P7JGnpzoaD9gF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @eitanm-starkware, @lev-starkware, @liorgold2, and @ShahakShama)

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @eitanm-starkware, @ittaysw, @lev-starkware, and @liorgold2)

___
*[`crates/mempool_p2p/src/sender/mod.rs` line 43 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/479#-O6Kd1ZjCmbpXLQvcqYL:-O6L_2hnAXgbfkT1przO:bvyecpv) ([raw file](https://github.com/starkware-libs/sequencer/blob/e72ea4e3da4a32d6943b937bd1bfa29478d17ea4/crates/mempool_p2p/src/sender/mod.rs#L43)):*
<details><summary><i>Previously, ittaysw (Ittay Dror) wrote…</i></summary><blockquote>

How will this work in a non-local setting?
</blockquote></details>

BroadcastedMessageManager is serializable. There's a different PR to rename it to BroadcastedMessageMetadata

**Review by eitanm-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @ittaysw, @lev-starkware, and @liorgold2)

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479#-:-O6Lzew4EQZQNMCvRdBR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @ittaysw, @lev-starkware, and @liorgold2)

**Review by ittaysw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/479#-:-O6PDPlY1-ZgSBmoFn-_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware, @lev-starkware, and @liorgold2)

**Pull request merged**
