### PR TITLE
feat: add tx generator scenario for a lot of similar txs

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1626)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Itay-Tsabary-Starkware)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1626#-OAMoN-R98jkneQLJuYl:-OAMoN-S0rCF1sUIm8Z9:bhxab4l) ([raw file](https://github.com/starkware-libs/sequencer/blob/0df56cd070f7aa02b991a6d2079701588cf5f7c3/crates/tests-integration/src/integration_test_utils.rs#L181)):*
> ```XML
> }
> 
> pub async fn run_overflow_test_scenario<'a, Fut>(
> ```

The code of these two functions is quite similar, how about merging into one function that also gets n_txs as an argument?
It can be called here in the flowtest with 3 (or more) and in the integration with more. wdyt?
I'd also change the name to seomthing with sending txs and no runninga a test scenario
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1626#-OAMpfxQEAPUetWsTOOQ:-OAMpfxRCF3xUP1_R-qD:byj4kmd) ([raw file](https://github.com/starkware-libs/sequencer/blob/0df56cd070f7aa02b991a6d2079701588cf5f7c3/crates/tests-integration/tests/end_to_end_test.rs#L33)):*
> ```XML
> 
>     // Create and send transactions.
>     let expected_batched_tx_hashes = run_integration_test_scenario(&mut tx_generator, &|tx| {
> ```

What changed that requires this?



_Code quote:_
```XML
&mut
```

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1626)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @Itay-Tsabary-Starkware)

___
*[`crates/tests-integration/src/bin/run_test_tx_generator.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1626#-OARUfDCESPSdy96VNN-:-OARUStE8j0E8RwQlF7s:b-xhn7pq) ([raw file](https://github.com/starkware-libs/sequencer/blob/0df56cd070f7aa02b991a6d2079701588cf5f7c3/crates/tests-integration/src/bin/run_test_tx_generator.rs#L41)):*
> ```XML
>     let send_rpc_tx_fn = &|rpc_tx| http_test_client.assert_add_tx_success(rpc_tx);
> 
>     let tx_hashes = run_integration_test_scenario(&mut tx_generator, send_rpc_tx_fn).await;
> ```

Can we only call the second scenario here? We can add txs to it if we want

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1626?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1626** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1626?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1686** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1686?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1685** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1685?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1626)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @Itay-Tsabary-Starkware)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1626#-OAMoN-R98jkneQLJuYl:-OASck4S-Pr6cgRjFfef:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0df56cd070f7aa02b991a6d2079701588cf5f7c3/crates/tests-integration/src/integration_test_utils.rs#L181)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

The code of these two functions is quite similar, how about merging into one function that also gets n_txs as an argument?
It can be called here in the flowtest with 3 (or more) and in the integration with more. wdyt?
I'd also change the name to seomthing with sending txs and no runninga a test scenario
</blockquote></details>

Done.
___
*[`crates/tests-integration/src/bin/run_test_tx_generator.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1626#-OARUfDCESPSdy96VNN-:-OASeqvw6SjSzqopP9Dn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0df56cd070f7aa02b991a6d2079701588cf5f7c3/crates/tests-integration/src/bin/run_test_tx_generator.rs#L41)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can we only call the second scenario here? We can add txs to it if we want
</blockquote></details>

Done.
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1626#-OAMpfxQEAPUetWsTOOQ:-OASWgis8pT4iRxk4bGC:b-cxchxo) ([raw file](https://github.com/starkware-libs/sequencer/blob/0df56cd070f7aa02b991a6d2079701588cf5f7c3/crates/tests-integration/tests/end_to_end_test.rs#L33)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What changed that requires this?
</blockquote></details>

No longer relevant.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1626)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @Itay-Tsabary-Starkware)

___
*[`crates/tests-integration/src/bin/run_test_tx_generator.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1626#-OAWdVd8-N5poW4FoRmw:-OAWdVd8-N5poW4FoRmx:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/82f2bb5211d4450ccf3e3f247e55eda0b99524db/crates/tests-integration/src/bin/run_test_tx_generator.rs#L41)):*
> ```XML
> 
>     let n_txs = 50;
>     info!("Sending {n_txs} txs.");
> ```





_Suggestion:_
```XML
    info!("Adding {n_txs} txs.");
```

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1626)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware and @Itay-Tsabary-Starkware)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 152 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1626#-OAXFx0gEOwPkaYiJSsr:-OAXFx0gEOwPkaYiJSss:b-n9bu4t) ([raw file](https://github.com/starkware-libs/sequencer/blob/6e99ffb591c30600b13ae5dc6490e8ccc25c5e3d/crates/tests-integration/src/integration_test_utils.rs#L152)):*
> ```XML
> }
> 
> fn create_txs_for_integration_test_scenario(
> ```

Can we remove the `scenario` suffix from functions? It seems unnecessary 



_Suggestion:_
```XML
create_txs_for_integration_test
```
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 169 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1626#-OAXFuNdCkhPQhVjJCjb:-OAXFuNe0AHOUFsaeCVx:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6e99ffb591c30600b13ae5dc6490e8ccc25c5e3d/crates/tests-integration/src/integration_test_utils.rs#L169)):*
> ```XML
> }
> 
> fn create_tx_for_tx_generator_test_scenario(
> ```





_Suggestion:_
```XML
create_txs_for_tx_generator_test_scenario
```
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 182 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1626#-OAXHTsY6_9qRLSvOLRG:-OAXHTsY6_9qRLSvOLRH:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6e99ffb591c30600b13ae5dc6490e8ccc25c5e3d/crates/tests-integration/src/integration_test_utils.rs#L182)):*
> ```XML
> /// Runs a scenario for sequencer integration test. Returns a list of transaction hashes, in the
> /// order they are expected to be in the mempool.
> async fn send_rpc_txs_for_given_scenario<'a, Fut>(
> ```





_Suggestion:_
```XML
async fn send_rpc_txs<'a, Fut>(
```
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 189 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1626#-OAXKjBK1rXrWry2ffaP:-OAXKjBK1rXrWry2ffaQ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6e99ffb591c30600b13ae5dc6490e8ccc25c5e3d/crates/tests-integration/src/integration_test_utils.rs#L189)):*
> ```XML
>     Fut: Future<Output = TransactionHash> + 'a,
> {
>     // Send RPC transactions.
> ```


___
*[`crates/tests-integration/src/bin/run_test_tx_generator.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1626#-OAWdVd8-N5poW4FoRmw:-OAXCYPF-xm2usw5-UXn:b5ior39) ([raw file](https://github.com/starkware-libs/sequencer/blob/82f2bb5211d4450ccf3e3f247e55eda0b99524db/crates/tests-integration/src/bin/run_test_tx_generator.rs#L41)):*
> ```XML
> 
>     let n_txs = 50;
>     info!("Sending {n_txs} txs.");
> ```

Actually I think sending is more appropriate and explicit here.. Adding txs is a log that can be found in many places.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1626)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @Itay-Tsabary-Starkware)

___
*[`crates/tests-integration/src/integration_test_utils.rs` line 152 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1626#-OAXFx0gEOwPkaYiJSsr:-OAXPAB-0zJe7JRlc3b4:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6e99ffb591c30600b13ae5dc6490e8ccc25c5e3d/crates/tests-integration/src/integration_test_utils.rs#L152)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can we remove the `scenario` suffix from functions? It seems unnecessary
</blockquote></details>

Done.
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 169 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1626#-OAXFuNdCkhPQhVjJCjb:-OAXR-ETC8c7kfPvMxzO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6e99ffb591c30600b13ae5dc6490e8ccc25c5e3d/crates/tests-integration/src/integration_test_utils.rs#L169)):*
> ```XML
> }
> 
> fn create_tx_for_tx_generator_test_scenario(
> ```

Done.
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 182 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1626#-OAXHTsY6_9qRLSvOLRG:-OAXP4KH0d5vYLZCBT8F:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6e99ffb591c30600b13ae5dc6490e8ccc25c5e3d/crates/tests-integration/src/integration_test_utils.rs#L182)):*
> ```XML
> /// Runs a scenario for sequencer integration test. Returns a list of transaction hashes, in the
> /// order they are expected to be in the mempool.
> async fn send_rpc_txs_for_given_scenario<'a, Fut>(
> ```

Done.
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 189 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1626#-OAXKjBK1rXrWry2ffaP:-OAXP4elExMHtzC743VO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6e99ffb591c30600b13ae5dc6490e8ccc25c5e3d/crates/tests-integration/src/integration_test_utils.rs#L189)):*
> ```XML
>     Fut: Future<Output = TransactionHash> + 'a,
> {
>     // Send RPC transactions.
> ```

Done.
___
*[`crates/tests-integration/src/bin/run_test_tx_generator.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1626#-OAWdVd8-N5poW4FoRmw:-OAXP6U7-gNALwkBQmh2:bp3aow6) ([raw file](https://github.com/starkware-libs/sequencer/blob/82f2bb5211d4450ccf3e3f247e55eda0b99524db/crates/tests-integration/src/bin/run_test_tx_generator.rs#L41)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Actually I think sending is more appropriate and explicit here.. Adding txs is a log that can be found in many places.
</blockquote></details>

Reverted.

**Comment by ArniStarkware** [comment]
### Merge activity

* **Oct 31, 8:44 AM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1626).

**Pull request merged**
