### PR TITLE
chore: use direct imports for mempool test util macros

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
No need.

**Comment by ArniStarkware** [comment]
No, there isn't a practical issue with the imports being processed multiple times in macro expansions because:

Rust's module system is designed to handle this efficiently:

The actual symbol resolution is cached by the compiler
Duplicate imports in the same scope are effectively deduplicated
The compiler is smart enough to not do redundant work for the same imports


While theoretically it's less efficient than having a single import at the module level, the overhead is negligible in practice and will not meaningfully impact:

Compilation time
Runtime performance
Memory usage
Binary size



The current approach in your macro (having imports inside) might actually be preferable because:

It makes the macro more self-contained and explicit about its dependencies
It ensures all necessary types are available in the macro's scope, preventing subtle errors
It's more maintainable as all dependencies are clearly visible where they're used

Unless you're seeing specific performance issues that you've traced back to these macro imports, I would suggest keeping them as they are. The theoretical inefficiency isn't worth optimizing unless you have a concrete need to do so.

**Comment by ArniStarkware** [comment]
Reopened. Now used for just one small change.

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1631)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/mempool/src/test_utils.rs` line 24 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1631#-OAWyK3Z5zY_QoJKqfp_:-OAWyK3Z5zY_QoJKqfpa:b-8llbzs) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b8b56b11cdbeefc592d9f2078d9d82ad6121129/crates/mempool/src/test_utils.rs#L24)):*
> ```XML
>     ) => {{
>             use starknet_api::block::GasPrice;
>             use starknet_api::{contract_address, invoke_tx_args};
> ```

Could you please explain this change?
Why this import is needed?



_Code quote:_
```XML
use starknet_api::{contract_address, invoke_tx_args};
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1631)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/mempool/src/test_utils.rs` line 24 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1631#-OAWyK3Z5zY_QoJKqfp_:-OAX1-0jAiTmv5sI5XvB:b-by9q0f) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b8b56b11cdbeefc592d9f2078d9d82ad6121129/crates/mempool/src/test_utils.rs#L24)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Could you please explain this change?
Why this import is needed?
</blockquote></details>

See other comment.
___
*[`crates/mempool/src/test_utils.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1631#-OAX0lW44S91CACOCcvu:-OAX0lW52FoxKSuvBgTr:buxafqg) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b8b56b11cdbeefc592d9f2078d9d82ad6121129/crates/mempool/src/test_utils.rs#L44)):*
> ```XML
>             });
> 
>             Transaction::Invoke(executable_invoke_tx(invoke_tx_args!{
> ```

The macro `invoke_tx_args` is used here. Importing it with a `use` inside this macro saves the import from the other files (Where the macro is called).



_Code quote:_
```XML
            Transaction::Invoke(executable_invoke_tx(invoke_tx_args!{
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1631)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1631#-:-OAXZx9H9hpBf0_E8GTj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/mempool/src/test_utils.rs` line 24 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1631#-OAWyK3Z5zY_QoJKqfp_:-OAXZraR-It7kaTewckt:b-vo0hen) ([raw file](https://github.com/starkware-libs/sequencer/blob/9b8b56b11cdbeefc592d9f2078d9d82ad6121129/crates/mempool/src/test_utils.rs#L24)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

See other comment.
</blockquote></details>

Got it, thanks

**Pull request merged**
