### PR TITLE
feat(starknet_monitoring_endpoint): add config for collect metrics

### PR DESCRIPTION
**Pull request by dan-starkware**

### CODE REVIEW

**Comment by dan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2472?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2472** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2472?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2472?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2469** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2469?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2472)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/starknet_monitoring_endpoint/src/monitoring_endpoint.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2472#-ODQywPC0Ux4ZXIdI0gf:-ODQywPC0Ux4ZXIdI0gg:b-hn4bco) ([raw file](https://github.com/starkware-libs/sequencer/blob/1fe152d87ddff186cc9c9a7814f083599960dbd0/crates/starknet_monitoring_endpoint/src/monitoring_endpoint.rs#L34)):*
> ```XML
> impl MonitoringEndpoint {
>     pub fn new(config: MonitoringEndpointConfig, version: &'static str) -> Self {
>         // TODO(Ittay): consider error handling
> ```

Is this for me? If so, please `Ittay` -> `Tsabary` :pray: 



_Code quote:_
```XML
// TODO(Ittay): consider error handling
```

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2472)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_monitoring_endpoint/src/monitoring_endpoint.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2472#-ODQywPC0Ux4ZXIdI0gf:-ODa5AptAEc2n18O4Sys:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b36bbd8cb4659728763e5dc700a3086c9a4a5370/crates/starknet_monitoring_endpoint/src/monitoring_endpoint.rs#L34)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Is this for me? If so, please `Ittay` -> `Tsabary` :pray:
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2472#-:-ODblVjo7zfpSQdZDBgL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2472)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Comment by dan-starkware** [comment]
### Merge activity

* **Dec 9, 7:18 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2472).

**Pull request merged**
