### PR TITLE
chore(blockifier): verify local cairo repo state before compiling

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/194)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/194?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#197** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/197?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#196** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/196?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#195** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/195?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#194** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/194?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#184** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/184?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#183** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/183?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#182** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/182?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#181** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/181?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#180** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/180?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#179** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/179?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/194)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, @meship-starkware, and @nimrod-starkware)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 183 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/194#-O40LvJa571E7KaYOXCN:-O40LvJa571E7KaYOXCO:bcd46t6) ([raw file](https://github.com/starkware-libs/sequencer/blob/b29a56b1f8fa15e1fc9cf7853739e01d14fb33bd/crates/blockifier/src/test_utils/cairo_compile.rs#L183)):*
> ```XML
>         "Cannot verify Cairo1 contracts, Cairo repo not found at {0}.\n\
>         Please run:\n\
>         git clone https://github.com/starkware-libs/cairo {0} && git -C {0} checkout {1}\n\
> ```

The script checkout in the next stage, I think this can be removed
___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 205 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/194#-O40LOGO69_ALo1ruaqC:-O40LOGO69_ALo1ruaqD:bmsrbbb) ([raw file](https://github.com/starkware-libs/sequencer/blob/b29a56b1f8fa15e1fc9cf7853739e01d14fb33bd/crates/blockifier/src/test_utils/cairo_compile.rs#L205)):*
> ```XML
>         "--verify",
>         &tag,
>     ]));
> ```

What does this add to the previous action (I mean, if the tag doesn't exist, we will fail in the checkout stage)?



_Code quote:_
```XML
    // Verify that the checked out tag is as expected.
    run_and_verify_output(Command::new("git").args([
        "-C",
        cairo_repo_path.to_str().unwrap(),
        "rev-parse",
        "--verify",
        &tag,
    ]));
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/194)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @meship-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 205 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/194#-O40LOGO69_ALo1ruaqC:-O40VPz96qzxwCpCSogQ:bjmssgz) ([raw file](https://github.com/starkware-libs/sequencer/blob/b29a56b1f8fa15e1fc9cf7853739e01d14fb33bd/crates/blockifier/src/test_utils/cairo_compile.rs#L205)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

What does this add to the previous action (I mean, if the tag doesn't exist, we will fail in the checkout stage)?
</blockquote></details>

in case we somehow "silently" fail the checkout and not catch the error.
may be redundant, but when we parallelize this test (takes forever to sequencially compile all contracts...) it will be useful to split checkout / verify checkout phases anyway

**Review by TzahiTaub — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/194)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware, @meship-starkware, and @nimrod-starkware)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 205 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/194#-O40LOGO69_ALo1ruaqC:-O40cv5o3GYZOMcORUNq:by3o38n) ([raw file](https://github.com/starkware-libs/sequencer/blob/b29a56b1f8fa15e1fc9cf7853739e01d14fb33bd/crates/blockifier/src/test_utils/cairo_compile.rs#L205)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

in case we somehow "silently" fail the checkout and not catch the error.
may be redundant, but when we parallelize this test (takes forever to sequencially compile all contracts...) it will be useful to split checkout / verify checkout phases anyway
</blockquote></details>

Can't say I understand (to parallelize I assume you need to run different tag compilation sequentially and parallelize only contracts using the same tag. In this case you can make one checkout, parallel compilations, and when finished - new checkout, (parallel) compilation etc. Don't see where the verify helps here. But unblocking

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/194)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware, @meship-starkware, and @nimrod-starkware)

___
*[`crates/blockifier/src/test_utils/cairo_compile.rs` line 205 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/194#-O40LOGO69_ALo1ruaqC:-O40fqdZ9KhycZpTHQqj:bfz5t1t) ([raw file](https://github.com/starkware-libs/sequencer/blob/b29a56b1f8fa15e1fc9cf7853739e01d14fb33bd/crates/blockifier/src/test_utils/cairo_compile.rs#L205)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Can't say I understand (to parallelize I assume you need to run different tag compilation sequentially and parallelize only contracts using the same tag. In this case you can make one checkout, parallel compilations, and when finished - new checkout, (parallel) compilation etc. Don't see where the verify helps here. But unblocking
</blockquote></details>

exactly.
I can checkout once, and verify in every thread

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Aug 11, 11:28 AM EDT**: @dorimedini-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/194).

**Pull request merged**
