### PR TITLE
chore(mempool): derive copy for transaction reference struct

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/836)

### CODE REVIEW

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/836)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

**Review by ayeletstarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/836)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/836#-O6z7stK-mNNZNd7NpaF:-O6z7stK-mNNZNd7NpaG:btx67u9) ([raw file](https://github.com/starkware-libs/sequencer/blob/1db631a04fe5138652e7ae7697a19f2b685a3c59/crates/mempool/src/mempool.rs#L217)):*
> ```XML
> /// TODO(Mohammad): rename this struct to `ThinTransaction` once that name
> /// becomes available, to better reflect its purpose and usage.
> #[derive(Clone, Copy, Debug, Eq, PartialEq)]
> ```

Do we still need this?



_Code quote:_
```XML
Clone
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/836)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/836#-O6z8Kz9-oVbq6Kot20G:-O6z8Kz9-oVbq6Kot20H:b-q6hkpl) (no related file):*
Please preemtively add a comment to the reviewer: are all `clone()`s gone?

___
___
*[`crates/mempool/src/mempool.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/836#-O6z84S26prTlW-y2hPT:-O6z84S3E_FLuRoS1RRK:b-2ogpyp) ([raw file](https://github.com/starkware-libs/sequencer/blob/1db631a04fe5138652e7ae7697a19f2b685a3c59/crates/mempool/src/mempool.rs#L167)):*
> ```XML
>                 self.tx_pool.get_next_eligible_tx(current_account_state)?
>             {
>                 self.tx_queue.insert(*next_tx_reference);
> ```

What happens here? Is it the cheap `Copy`? Why is `*` needed when the object is `Copy`?



_Code quote:_
```XML
*next_tx_reference
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/836)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/836#-O6z8ascApz2NZJU2ed8:-O6z8ascApz2NZJU2ed9:b-ma1qk2) ([raw file](https://github.com/starkware-libs/sequencer/blob/1db631a04fe5138652e7ae7697a19f2b685a3c59/crates/mempool/src/mempool.rs#L223)):*
> ```XML
>     pub tx_hash: TransactionHash,
>     pub tip: Tip,
>     pub resource_bounds: ValidResourceBounds,
> ```

What is this struct? I don't understand its role from the name...



_Code quote:_
```XML
ValidResourceBounds
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/836)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/836#-O6z7stK-mNNZNd7NpaF:-O6z8aXy8RDOawEHwrB3:b-u3irvo) ([raw file](https://github.com/starkware-libs/sequencer/blob/1db631a04fe5138652e7ae7697a19f2b685a3c59/crates/mempool/src/mempool.rs#L217)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Do we still need this?
</blockquote></details>

`Clone` is used in `PriorityTransaction` and `PendingTransaction`.
I'm adding `Copy` for these struct in a separate PR, and only then I can delete this `Clone`.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/836)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/836#-O6z84S26prTlW-y2hPT:-O6z8slJD2CidXSfw9JT:b79x0oz) ([raw file](https://github.com/starkware-libs/sequencer/blob/1db631a04fe5138652e7ae7697a19f2b685a3c59/crates/mempool/src/mempool.rs#L167)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What happens here? Is it the cheap `Copy`? Why is `*` needed when the object is `Copy`?
</blockquote></details>

`next_tx_reference` is from `&TransactionReference` type.
So here I needed to deref, as `insert` expects `TransactionReference` type and not `&TransactionReference`.

The previous code has `clone` which returns `TransactionReference` type.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/836)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/836#-O6z8Kz9-oVbq6Kot20G:-O6z9ZjF6n0RKrLmeMe-:bqimt2z) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please preemtively add a comment to the reviewer: are all `clone()`s gone?
</blockquote></details>

Ofc, all the clones of `TransactionReference` were gone.
Otherwise, it would fail on `Clippy`.

___

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/836)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/836#-O6z8ascApz2NZJU2ed8:-O6zB--i8mUMYJYtEcpG:btivyb3) ([raw file](https://github.com/starkware-libs/sequencer/blob/1db631a04fe5138652e7ae7697a19f2b685a3c59/crates/mempool/src/mempool.rs#L223)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What is this struct? I don't understand its role from the name...
</blockquote></details>

I think it's the new name for the resource-bound structure.
Was added/changed by Dori's team.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/836)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/836#-O6z7stK-mNNZNd7NpaF:-O6zBOyE5s0uIiD5o1MQ:bhcjzvt) ([raw file](https://github.com/starkware-libs/sequencer/blob/1db631a04fe5138652e7ae7697a19f2b685a3c59/crates/mempool/src/mempool.rs#L217)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

`Clone` is used in `PriorityTransaction` and `PendingTransaction`.
I'm adding `Copy` for these struct in a separate PR, and only then I can delete this `Clone`.
</blockquote></details>

`PriorityTransaction` and `PendingTransaction` include`TransactionReference` struct. So, meanwhile they require `Clone` in `TransactionReference`.

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/836)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/836#-O6z7stK-mNNZNd7NpaF:-O6zH9GM89tLSNCp0H06:b-yhpvyd) ([raw file](https://github.com/starkware-libs/sequencer/blob/441a3a7f67c4f214c8c5bf5a23c81af28acdaec9/crates/mempool/src/mempool.rs#L217)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

`PriorityTransaction` and `PendingTransaction` include`TransactionReference` struct. So, meanwhile they require `Clone` in `TransactionReference`.
</blockquote></details>

Please do it in the PR right after.
___
*[`crates/mempool/src/mempool.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/836#-O6z8ascApz2NZJU2ed8:-O6zHDZG2nnj3yXwOeiZ:b5zjix3) ([raw file](https://github.com/starkware-libs/sequencer/blob/441a3a7f67c4f214c8c5bf5a23c81af28acdaec9/crates/mempool/src/mempool.rs#L223)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I think it's the new name for the resource-bound structure.
Was added/changed by Dori's team.
</blockquote></details>

Please understand the meaning of structs you're using.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/836)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/836#-O6z7stK-mNNZNd7NpaF:-O6zLygGB-5IZyg8mPUM:bx2tiek) ([raw file](https://github.com/starkware-libs/sequencer/blob/441a3a7f67c4f214c8c5bf5a23c81af28acdaec9/crates/mempool/src/mempool.rs#L217)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please do it in the PR right after.
</blockquote></details>

I've opened a [PR](https://reviewable.io/reviews/starkware-libs/sequencer/839) for that.
Will add you once it's ready.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/836)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/836#-O6z8ascApz2NZJU2ed8:-O6zP4e87O8T9iEGcMOV:b-mriowl) ([raw file](https://github.com/starkware-libs/sequencer/blob/441a3a7f67c4f214c8c5bf5a23c81af28acdaec9/crates/mempool/src/mempool.rs#L223)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please understand the meaning of structs you're using.
</blockquote></details>

'm clarifying with them..

**Review by ayeletstarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/836)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/836#-:-O6zRb9qAnJT8kRY2SEV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/836#-:-O6zSDAV5VTbrAcLEoKs:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
