### PR TITLE
fix(blockifier): remove the gas word following the resource name in errors

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/796)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/796)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/transaction/errors.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/796#-O6qPM5c5r5n9OpMo716:-O6qPM5c5r5n9OpMo717:bi9x9a) ([raw file](https://github.com/starkware-libs/sequencer/blob/647f0e6802aa7207d8d17b2a152f03a6c6f01189/crates/blockifier/src/transaction/errors.rs#L27)):*
> ```XML
>     InsufficientFee { paid_fee: Fee, actual_fee: Fee },
>     #[error(
>         "Resource {resource} bounds (max amount: {max_amount}, max price: {max_price}) exceed \
> ```

As the resource already contains a "gas" suffix. 
(same below)



_Code quote:_
```XML
        "Resource {resource} bounds (max amount: {max_amount}, max price: {max_price}) exceed \
```

**Review by AvivYossef-starkware — CHANGES_REQUESTED** [review]
You should open a Python pull request because it will break the gateway test.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/796#-:-O6tRJEb1eyJ8aMG_5AB:b-dbdvg9)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by noaov1 — COMMENTED** [review]
You are right. It's [here](https://reviewable.io/reviews/starkware-industries/starkware/35928)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/796#-:-O6tWgQ01U7CTlSHIcUv:bn228co)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by AvivYossef-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/796#-:-O6uW5YRASKLJQTqcr1S:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/796)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Pull request merged**
