### PR TITLE
build(blockifier_reexecution): convert starknet_api txs to blockifier txs

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1297)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1297)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1297#-O8qTQvC2lYbb_yKSLQp:-O8qTQvC2lYbb_yKSLQq:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fe3d2055aa38b659f7c408c366e6ac5628a2fb/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L194)):*
> ```XML
>             );
>         }
>         Ok(blockifier_txs)
> ```





_Suggestion:_
```XML
        txs_and_hashes.iter().map(|(tx, tx_hash)| {
            BlockifierTransaction::from_api(tx, tx_hash, None, None, None, false)
                .map_err(transaction_execution_err_to_state_err)
        })
        .collect()
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 186 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1297#-O8qW_9j0tIKL9cVx56X:-O8qW_9j0tIKL9cVx56Y:b-k6uftv) ([raw file](https://github.com/starkware-libs/sequencer/blob/319c87960299fda41a6a01f9422c1671deeaf7dc/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L186)):*
> ```XML
>     pub fn from_api_txs_to_blockifier_txs(
>         txs_and_hashes: Vec<(Transaction, TransactionHash)>,
>     ) -> StateResult<Vec<BlockifierTransaction>> {
> ```

change error type



_Code quote:_
```XML
StateResult
```
___
*[`crates/gateway/src/errors.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1297#-O8qTaeu2cZj0MiKxILB:-O8qTaeu2cZj0MiKxILC:b-4vxw1b) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fe3d2055aa38b659f7c408c366e6ac5628a2fb/crates/gateway/src/errors.rs#L121)):*
> ```XML
> pub fn transaction_execution_err_to_state_err(err: TransactionExecutionError) -> StateError {
>     StateError::StateReadError(format!("Failed to execute tx: {:?}", err.to_string()))
> }
> ```

not the way to use errors...
I see you are using `StateError` from the blockifier to describe errors from specific functions in the RPC state reader; why?
blockifier_reexecution crate should define it's own error enum and use it
(I see many return types are `StateResult`s... I think they should be `TestRpcStateError`s (new enum))



_Code quote:_
```XML
// Converts a transaction execution error to the error type of the state reader.
pub fn transaction_execution_err_to_state_err(err: TransactionExecutionError) -> StateError {
    StateError::StateReadError(format!("Failed to execute tx: {:?}", err.to_string()))
}
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1297)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 194 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1297#-O8qTQvC2lYbb_yKSLQp:-O8vcjXT0bComgcinax1:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fe3d2055aa38b659f7c408c366e6ac5628a2fb/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L194)):*
> ```XML
>             );
>         }
>         Ok(blockifier_txs)
> ```

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 186 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1297#-O8qW_9j0tIKL9cVx56X:-O8vcaeB-Mv6DwV1FCZ-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/319c87960299fda41a6a01f9422c1671deeaf7dc/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L186)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

change error type
</blockquote></details>

Done.
___
*[`crates/gateway/src/errors.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1297#-O8qTaeu2cZj0MiKxILB:-O8vcoAV3bW76XU6Lttg:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/93fe3d2055aa38b659f7c408c366e6ac5628a2fb/crates/gateway/src/errors.rs#L121)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not the way to use errors...
I see you are using `StateError` from the blockifier to describe errors from specific functions in the RPC state reader; why?
blockifier_reexecution crate should define it's own error enum and use it
(I see many return types are `StateResult`s... I think they should be `TestRpcStateError`s (new enum))
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1297)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 101 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1297#-O93okqW2bI3SUZj6_-g:-O93okqW2bI3SUZj6_-h:b9wse8z) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a6a80e0a30e12df897e611beea2b08b6db889b4/crates/blockifier_reexecution/src/state_reader/utils.rs#L101)):*
> ```XML
> 
> // TODO(Aner): extend/refactor to accomodate all types of transactions.
> #[allow(dead_code)]
> ```

will be removed in a later PR?



_Code quote:_
```XML
#[allow(dead_code)]
```
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 102 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1297#-O93ongZ629U8-rpXXkK:-O93ongZ629U8-rpXXkL:bft7q06) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a6a80e0a30e12df897e611beea2b08b6db889b4/crates/blockifier_reexecution/src/state_reader/utils.rs#L102)):*
> ```XML
> // TODO(Aner): extend/refactor to accomodate all types of transactions.
> #[allow(dead_code)]
> pub(crate) fn from_api_txs_to_blockifier_txs(
> ```

why is this now a standalone util and not an associated function of the test RPC?



_Code quote:_
```XML
pub(crate) fn from_api_txs_to_blockifier_txs(
```
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1297#-O93oQiU6iTmMoG8rohy:-O93oQiU6iTmMoG8rohz:b-gb2doj) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a6a80e0a30e12df897e611beea2b08b6db889b4/crates/blockifier_reexecution/src/state_reader/utils.rs#L107)):*
> ```XML
>     Ok(txs_and_hashes
>         .into_iter()
>         .map(|(tx, tx_hash)| BlockifierTransaction::from_api(tx, tx_hash, None, None, None, false))
> ```

please `match` on the tx and only call `from_api` on invoke txs (which is the only thing you support ATM, right?).
call `todo!()` on the other `match` arms, so we panic explicitly on unimplemented code



_Code quote:_
```XML
.map(|(tx, tx_hash)| BlockifierTransaction::from_api(tx, tx_hash, None, None, None, false))
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1297)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 101 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1297#-O93okqW2bI3SUZj6_-g:-O94S9Ki1vwlYdPFhOxl:b-7k5s6a) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a6a80e0a30e12df897e611beea2b08b6db889b4/crates/blockifier_reexecution/src/state_reader/utils.rs#L101)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

will be removed in a later PR?
</blockquote></details>

Most likely, unless it will be used only for tests (it doesn't seem probable at the moment).
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 102 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1297#-O93ongZ629U8-rpXXkK:-O94SMHN9MSt8Ek2Z8XF:bokmqwl) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a6a80e0a30e12df897e611beea2b08b6db889b4/crates/blockifier_reexecution/src/state_reader/utils.rs#L102)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this now a standalone util and not an associated function of the test RPC?
</blockquote></details>

I thought it made more sense for this function to be in `utils`. It doesn't make sense for it to be inside `StateReader` IMO.
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1297#-O93oQiU6iTmMoG8rohy:-O94UA-N4oO0JCc4ZYlo:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a6a80e0a30e12df897e611beea2b08b6db889b4/crates/blockifier_reexecution/src/state_reader/utils.rs#L107)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please `match` on the tx and only call `from_api` on invoke txs (which is the only thing you support ATM, right?).
call `todo!()` on the other `match` arms, so we panic explicitly on unimplemented code
</blockquote></details>

Done.

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1297)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1297#-O93oQiU6iTmMoG8rohy:-O94USVe0cCIcYu2-zV_:bpyms8h) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a6a80e0a30e12df897e611beea2b08b6db889b4/crates/blockifier_reexecution/src/state_reader/utils.rs#L107)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm guessing the function will be written quite differently once the other arms are implemented (e.g., the vars will be in the match, and the `from_api` will always be called).

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1297)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 102 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1297#-O93ongZ629U8-rpXXkK:-O94mQGc9vy5DXt2d_5N:bfi08s4) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a6a80e0a30e12df897e611beea2b08b6db889b4/crates/blockifier_reexecution/src/state_reader/utils.rs#L102)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I thought it made more sense for this function to be in `utils`. It doesn't make sense for it to be inside `StateReader` IMO.
</blockquote></details>

I think it makes sense: it is only used as part of the RPC client logic, converting RPC types into local (blockifier) types.
You can make this a private associated function.
Is this used outside of RPC context?
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1297#-O93oQiU6iTmMoG8rohy:-O94md-Q7FJY0M66AIO3:btxqo5r) ([raw file](https://github.com/starkware-libs/sequencer/blob/7a6a80e0a30e12df897e611beea2b08b6db889b4/crates/blockifier_reexecution/src/state_reader/utils.rs#L107)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I'm guessing the function will be written quite differently once the other arms are implemented (e.g., the vars will be in the match, and the `from_api` will always be called).
</blockquote></details>

yes, but for now we panic explicitly on unimplemented flows, the refactor won't be so painful

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1297)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1297)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

**Pull request merged**
