### PR TITLE
feat: use the installed starknet-sierra-compile crate to compile

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/331)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/331?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#331** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/331?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#330** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/330?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#319** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/319?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#318** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/318?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#283** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/283?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#284](https://github.com/starkware-libs/sequencer/pull/284) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/284?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#250** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/250?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/331)* status: 0 of 8 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/331#-O3ftNZV-u_vABzn8e-E:-O3ftNZWEqdy_3e1X8nD:b1tckxw) (no related file):*
To speed up development, we made a temporary hack.

The compiler is saved as an executable to `crates/starknet_sierra_compile/executable/starknet-sierra-compile`.
We run this executable to compile.

___

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 6 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/331)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/starknet_sierra_compile/src/command_line_compiler.rs` line 38 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/331#-O4EyazlBH5g6ZtrQr9c:-O4EyazlBH5g6ZtrQr9d:b-vm0rl3) ([raw file](https://github.com/starkware-libs/sequencer/blob/3202c03c74922e0b7b7457e7f8ba60f4fdc6b834/crates/starknet_sierra_compile/src/command_line_compiler.rs#L38)):*
> ```XML
>         command.args(["--max-bytecode-size", &self.config.max_bytecode_size.to_string()]);
> 
>         let compile_output = command.output()?;
> ```

Is this starting a new process and runs the command?
If so, please document.



_Code quote:_
```XML
command.output()
```
___
*[`crates/starknet_sierra_compile/src/command_line_compiler.rs` line 58 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/331#-O4Ey2xU1lXB8DuOCA8t:-O4Ey2xU1lXB8DuOCA8u:b-s3qbqp) ([raw file](https://github.com/starkware-libs/sequencer/blob/3202c03c74922e0b7b7457e7f8ba60f4fdc6b834/crates/starknet_sierra_compile/src/command_line_compiler.rs#L58)):*
> ```XML
> 
> // TODO(Arni): Get the binary in a cleaner way.
> fn excutable_file_location() -> String {
> ```

Can it be a static variable (using `OneLock`)?
___
*[`crates/starknet_sierra_compile/src/compile_test.rs` line 61 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/331#-O4F0G18D3mNK2_zQ2AJ:-O4F0G18D3mNK2_zQ2AK:bmqgq07) ([raw file](https://github.com/starkware-libs/sequencer/blob/3202c03c74922e0b7b7457e7f8ba60f4fdc6b834/crates/starknet_sierra_compile/src/compile_test.rs#L61)):*
> ```XML
> #[rstest]
> #[case::command_line_compiler(&COMMAND_LINE_COMPILER)]
> fn test_negative_flow_compile_sierra_to_casm_2(#[case] compiler: &impl SierraToCasmCompiler) {
> ```

Can't it be a case in the test above?



_Code quote:_
```XML
fn test_negative_flow_compile_sierra_to_casm_2(#[case] compiler: &impl SierraToCasmCompiler) {
```
___
*[`crates/starknet_sierra_compile/src/errors.rs` line 6 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/331#-O4F4Hgw8bJy4pkfPVQj:-O4F4Hgw8bJy4pkfPVQk:b-da4bbt) ([raw file](https://github.com/starkware-libs/sequencer/blob/3202c03c74922e0b7b7457e7f8ba60f4fdc6b834/crates/starknet_sierra_compile/src/errors.rs#L6)):*
> ```XML
> 
> #[derive(Debug, Error)]
> pub enum CompilationUtilError {
> ```

Each implementation returns slightly different errors, and this enum is used for the trait API. 
I would consider making it more general, something like:

```
#[derive(Debug, Error)]
pub enum CompilationUtilError {
    #[error("Starknet Sierra compilation error: {0}")]
    CompilationError(String),
    #[error("Compilation panicked")]
    UnexpectedError(String),
}
```

And leave the detailed error to be inside the error message.

Another alternative, if we don't wont to loose the specific error type is to define something like:

``` 
struct CompilationUtilError {
  kind: CompilationUtilErrorKind,
  source: Box<dyn std::error::Error>,
}
```

(but maybe that's an overkill)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/331)* status: 3 of 10 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/starknet_sierra_compile/src/command_line_compiler.rs` line 38 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/331#-O4EyazlBH5g6ZtrQr9c:-O4FfVdeCsvovcQx-8O-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3202c03c74922e0b7b7457e7f8ba60f4fdc6b834/crates/starknet_sierra_compile/src/command_line_compiler.rs#L38)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Is this starting a new process and runs the command?
If so, please document.
</blockquote></details>

Done.
___
*[`crates/starknet_sierra_compile/src/command_line_compiler.rs` line 58 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/331#-O4Ey2xU1lXB8DuOCA8t:-O4FcGRe8UCq71C3bWRB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3202c03c74922e0b7b7457e7f8ba60f4fdc6b834/crates/starknet_sierra_compile/src/command_line_compiler.rs#L58)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can it be a static variable (using `OneLock`)?
</blockquote></details>

Done.
___
*[`crates/starknet_sierra_compile/src/compile_test.rs` line 61 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/331#-O4F0G18D3mNK2_zQ2AJ:-O4FiTSj0eEgu-tkCNi6:brac0hz) ([raw file](https://github.com/starkware-libs/sequencer/blob/3202c03c74922e0b7b7457e7f8ba60f4fdc6b834/crates/starknet_sierra_compile/src/compile_test.rs#L61)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can't it be a case in the test above?
</blockquote></details>

Now it can :)
Done.
___
*[`crates/starknet_sierra_compile/src/errors.rs` line 6 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/331#-O4F4Hgw8bJy4pkfPVQj:-O4Fxqff29IlAKIlBR1s:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3202c03c74922e0b7b7457e7f8ba60f4fdc6b834/crates/starknet_sierra_compile/src/errors.rs#L6)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Each implementation returns slightly different errors, and this enum is used for the trait API. 
I would consider making it more general, something like:

```
#[derive(Debug, Error)]
pub enum CompilationUtilError {
    #[error("Starknet Sierra compilation error: {0}")]
    CompilationError(String),
    #[error("Compilation panicked")]
    UnexpectedError(String),
}
```

And leave the detailed error to be inside the error message.

Another alternative, if we don't wont to loose the specific error type is to define something like:

``` 
struct CompilationUtilError {
  kind: CompilationUtilErrorKind,
  source: Box<dyn std::error::Error>,
}
```

(but maybe that's an overkill)
</blockquote></details>

Done.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/331)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/starknet_sierra_compile/src/errors.rs` line 9 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/331#-O4Kf3cB0LntR9pWo627:-O4Kf3cB0LntR9pWo628:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/3085e45f7fbeae4e71de848992913af530d0e704/crates/starknet_sierra_compile/src/errors.rs#L9)):*
> ```XML
>     #[error("Starknet Sierra compilation error: {0}")]
>     CompilationError(String),
>     #[error("Compilation panicked")]
> ```





_Suggestion:_
```XML
#[error("Unexpected compilation error")]
```
___
*[`crates/starknet_sierra_compile/src/errors.rs` line 21 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/331#-O4KeaBw-ytxIWSgjWls:-O4KeaBx3SSSMpOBA2uP:bkwv74f) ([raw file](https://github.com/starkware-libs/sequencer/blob/3085e45f7fbeae4e71de848992913af530d0e704/crates/starknet_sierra_compile/src/errors.rs#L21)):*
> ```XML
> impl From<serde_json::Error> for CompilationUtilError {
>     fn from(_error: serde_json::Error) -> Self {
>         CompilationUtilError::UnexpectedError
> ```

Does `_error` have anymore detailed information about the error that can be passed as a string?



_Code quote:_
```XML
 CompilationUtilError::UnexpectedError
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/331)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/starknet_sierra_compile/src/errors.rs` line 9 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/331#-O4Kf3cB0LntR9pWo627:-O4KktMHAdMwwqmnSQwy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3085e45f7fbeae4e71de848992913af530d0e704/crates/starknet_sierra_compile/src/errors.rs#L9)):*
> ```XML
>     #[error("Starknet Sierra compilation error: {0}")]
>     CompilationError(String),
>     #[error("Compilation panicked")]
> ```

Done.
___
*[`crates/starknet_sierra_compile/src/errors.rs` line 21 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/331#-O4KeaBw-ytxIWSgjWls:-O4KktrO9wwxAxaG5bc3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3085e45f7fbeae4e71de848992913af530d0e704/crates/starknet_sierra_compile/src/errors.rs#L21)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Does `_error` have anymore detailed information about the error that can be passed as a string?
</blockquote></details>

Done.

**Comment by ArniStarkware** [comment]
We are waiting for infra-approval before we continue with this PR.
@dafnamatsry @liorgold2 .

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/331)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/gateway/src/compilation.rs` line 67 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/331#-O4eCOGXBDjAJkqb7TBV:-O4eCOGXBDjAJkqb7TBW:b-knvnqx) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3117736b59b4ca42e16ea68ac065736eb7a3ce3/crates/gateway/src/compilation.rs#L67)):*
> ```XML
>             Ok(casm_contract_class) => Ok(casm_contract_class),
>             Err(starknet_sierra_compile::errors::CompilationUtilError::UnexpectedError(error)) => {
>                 // TODO(Arni): Log the panic.UnexpectedPanic
> ```

Can be removed?



_Code quote:_
```XML
 // TODO(Arni): Log the panic.UnexpectedPanic
```

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/compilation.rs` line 67 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/331#-O4eCOGXBDjAJkqb7TBV:-O4eI64d6YhfiFjDgupS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e3117736b59b4ca42e16ea68ac065736eb7a3ce3/crates/gateway/src/compilation.rs#L67)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can be removed?
</blockquote></details>

Done.

**Comment by ArniStarkware** [comment]
This PR was replaced by other PRs: #597, #598.

**Pull request closed without merging**
