### PR TITLE
feat(starknet_state_sync): implement state sync get compiled class

### PR DESCRIPTION
**Pull request by noamsp-starkware**

### CODE REVIEW

**Comment by noamsp-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2817?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2817** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2817?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2817?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2757** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2757?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2755** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2755?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2754** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2754?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2662** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2662?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2537** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2537?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2538](https://github.com/starkware-libs/sequencer/pull/2538) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2538?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2531** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2531?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2515** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2515?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2817)* status: all files reviewed, 5 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/starknet_state_sync/src/lib.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2817#-OEU8O1v-AJR2dUEOFZP:-OEU8O1v-AJR2dUEOFZQ:bo1rr9q) ([raw file](https://github.com/starkware-libs/sequencer/blob/af6b19dac47710815c9e84890ed828dfdc434bbc/crates/starknet_state_sync/src/lib.rs#L155)):*
> ```XML
>     ) -> StateSyncResult<(ContractClass, SierraVersion)> {
>         let txn = self.storage_reader.begin_ro_txn()?;
>         verify_synced_up_to(&txn, block_number)?;
> ```

The check here should be against the casm marker and not the state marker
___
*[`crates/starknet_state_sync/src/lib.rs` line 170 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2817#-OEU8tMA49vgP184CSQn:-OEU8tMBAgqMYWWZhbJW:b-h93cnl) ([raw file](https://github.com/starkware-libs/sequencer/blob/af6b19dac47710815c9e84890ed828dfdc434bbc/crates/starknet_state_sync/src/lib.rs#L170)):*
> ```XML
>             let (casm, sierra) = option_casm
>                 .zip(option_sierra)
>                 .ok_or(StateSyncError::ClassHashNotFound(class_hash))?;
> ```

Add a comment that we've checked that block number is smaller than casm marker so if it's missing it's because it doesn't exist
___
*[`crates/starknet_state_sync_types/src/communication.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2817#-OEUNsLa5RzO4vMeMsPM:-OEUNsLbA1s6DJJVyIjL:bfa3z6s) ([raw file](https://github.com/starkware-libs/sequencer/blob/af6b19dac47710815c9e84890ed828dfdc434bbc/crates/starknet_state_sync_types/src/communication.rs#L60)):*
> ```XML
>     ) -> StateSyncClientResult<ClassHash>;
> 
>     async fn get_compiled_class(
> ```

Add TODO to remove this and use compiler component client instead in SyncStateReader
___
*[`crates/starknet_state_sync_types/src/communication.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2817#-OEUNuG25BHNzx-pQ0wz:-OEUNuG25BHNzx-pQ0x-:byo78yn) ([raw file](https://github.com/starkware-libs/sequencer/blob/af6b19dac47710815c9e84890ed828dfdc434bbc/crates/starknet_state_sync_types/src/communication.rs#L60)):*
> ```XML
>     ) -> StateSyncClientResult<ClassHash>;
> 
>     async fn get_compiled_class(
> ```

rename to get_compiled_class_deprecated so people will fear using it
___
*[`crates/starknet_state_sync_types/src/errors.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2817#-OEU8ebrAQWurYiVZ4v9:-OEU8ebrAQWurYiVZ4vA:byckk4f) ([raw file](https://github.com/starkware-libs/sequencer/blob/af6b19dac47710815c9e84890ed828dfdc434bbc/crates/starknet_state_sync_types/src/errors.rs#L17)):*
> ```XML
>     ContractNotFound(ContractAddress),
>     #[error("Class hash {0} was not found")]
>     ClassHashNotFound(ClassHash),
> ```

Rename to ClassNotFound

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2817)* status: all files reviewed, 5 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/starknet_state_sync/src/lib.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2817#-OEU8O1v-AJR2dUEOFZP:-OEUhWFF-OtKXhxsvo8N:bk8fmkh) ([raw file](https://github.com/starkware-libs/sequencer/blob/af6b19dac47710815c9e84890ed828dfdc434bbc/crates/starknet_state_sync/src/lib.rs#L155)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

The check here should be against the casm marker and not the state marker
</blockquote></details>

Ack.
The current rpc state reader checks the state marker and not the casm marker.
___
*[`crates/starknet_state_sync/src/lib.rs` line 170 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2817#-OEU8tMA49vgP184CSQn:-OEUyoDs8PQ0ZnQW4sCq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/af6b19dac47710815c9e84890ed828dfdc434bbc/crates/starknet_state_sync/src/lib.rs#L170)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add a comment that we've checked that block number is smaller than casm marker so if it's missing it's because it doesn't exist
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync_types/src/communication.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2817#-OEUNuG25BHNzx-pQ0wz:-OEUm5-TAgAJuFGkiODg:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/af6b19dac47710815c9e84890ed828dfdc434bbc/crates/starknet_state_sync_types/src/communication.rs#L60)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename to get_compiled_class_deprecated so people will fear using it
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync_types/src/communication.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2817#-OEUNsLa5RzO4vMeMsPM:-OEUzHRzANZTMSqlYuYn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/af6b19dac47710815c9e84890ed828dfdc434bbc/crates/starknet_state_sync_types/src/communication.rs#L60)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to remove this and use compiler component client instead in SyncStateReader
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync_types/src/errors.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2817#-OEU8ebrAQWurYiVZ4v9:-OEUlxYS3IthW_ml5Cij:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/af6b19dac47710815c9e84890ed828dfdc434bbc/crates/starknet_state_sync_types/src/errors.rs#L17)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to ClassNotFound
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2817#-:-OEhKnY9B5zkWl3BIoCp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)

___
*[`crates/starknet_state_sync/src/lib.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2817#-OEU8O1v-AJR2dUEOFZP:-OEhJcgZ7U_cAXhaNbDh:b-h9ptc0) ([raw file](https://github.com/starkware-libs/sequencer/blob/af6b19dac47710815c9e84890ed828dfdc434bbc/crates/starknet_state_sync/src/lib.rs#L155)):*
<details><summary><i>Previously, noamsp-starkware wrote…</i></summary><blockquote>

Ack.
The current rpc state reader checks the state marker and not the casm marker.
</blockquote></details>

Yes. They have a bit different case than our case

**Comment by noamsp-starkware** [comment]
### Merge activity

* **Dec 22, 3:18 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2817).

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2817#-:-OEilGsX8FfunrMe71KS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)

**Pull request merged**
