### PR TITLE
feat(l1_provider): implement `proposal_start`

### PR DESCRIPTION
**Pull request by giladchase**

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2058)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/starknet_l1_provider/src/errors.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2058#-OBePeDgDYYcmNDP0Bln:-OBePeDgDYYcmNDP0Blo:bl98qak) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c0a5050cf8d133004340561fb96f11f609db00b/crates/starknet_l1_provider/src/errors.rs#L17)):*
> ```XML
>     GetTransactionConsensusBug,
>     #[error("Cannot transition from {from} to {to}")]
>     UnexpectedProviderState { from: ProviderState, to: ProviderState },
> ```

If not too long IYO.



_Suggestion:_
```XML
UnexpectedProviderStateTransition
```
___
*[`crates/starknet_l1_provider/src/l1_provider_tests.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2058#-OBePkWbDzwn1gOhND74:-OBePkWbDzwn1gOhND75:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c0a5050cf8d133004340561fb96f11f609db00b/crates/starknet_l1_provider/src/l1_provider_tests.rs#L11)):*
> ```XML
>     let mut l1_provider = L1Provider::default();
> 
>     // Test
> ```





_Suggestion:_
```XML
// Test.
```
___
*[`crates/starknet_l1_provider/src/l1_provider_tests.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2058#-OBePw8ODk_-JaaJkGKI:-OBePw8ODk_-JaaJkGKJ:b-mjov44) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c0a5050cf8d133004340561fb96f11f609db00b/crates/starknet_l1_provider/src/l1_provider_tests.rs#L13)):*
> ```XML
>     // Test
>     l1_provider.proposal_start().unwrap();
>     assert_matches!(
> ```

Want to check all illegal transitions?
___
*[`crates/starknet_l1_provider/src/lib.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2058#-OBePNcY1uv0BNCebgNh:-OBePNcY1uv0BNCebgNi:bu12gl8) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c0a5050cf8d133004340561fb96f11f609db00b/crates/starknet_l1_provider/src/lib.rs#L3)):*
> ```XML
> pub mod errors;
> 
> use std::fmt;
> ```

Fully-qualified, please.



_Code quote:_
```XML
use std::fmt;
```
___
*[`crates/starknet_l1_provider/src/lib.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2058#-OBePRfh7cfK0vFVeVMO:-OBePRfiCLcYBLzUB1RZ:b-suv37y) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c0a5050cf8d133004340561fb96f11f609db00b/crates/starknet_l1_provider/src/lib.rs#L102)):*
> ```XML
> 
> /// Current state of the provider, where pending means: idle, between proposal/validation cycles.
> #[derive(Debug, Default, Clone, Copy)]
> ```

Alphabetize.



_Code quote:_
```XML
derive
```

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2058)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2058)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`crates/starknet_l1_provider/src/l1_provider_tests.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2058#-OBePw8ODk_-JaaJkGKI:-OBelvVVDDVT3jM-K5QG:bkqp47h) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c0a5050cf8d133004340561fb96f11f609db00b/crates/starknet_l1_provider/src/l1_provider_tests.rs#L13)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Want to check all illegal transitions?
</blockquote></details>

Thought about it, but i decided it might be easier to see what's being worked on by focusing on the get_txs flow, which I have cooking now. If I start implementing parts of other flows it might be hard to see what's implemented fully and what isn't.

WDYT?

**Review by elintul — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2058)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/starknet_l1_provider/src/l1_provider_tests.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2058#-OBePw8ODk_-JaaJkGKI:-OBeyDpS-lnpjTxLdCni:b-5h0us0) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c0a5050cf8d133004340561fb96f11f609db00b/crates/starknet_l1_provider/src/l1_provider_tests.rs#L13)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Thought about it, but i decided it might be easier to see what's being worked on by focusing on the get_txs flow, which I have cooking now. If I start implementing parts of other flows it might be hard to see what's implemented fully and what isn't.

WDYT?
</blockquote></details>

So when working on validate mode, you plan to add it? 
___
*[`crates/starknet_l1_provider/src/lib.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2058#-OBePNcY1uv0BNCebgNh:-OBeyIRyE5c1VvgZ82In:b950wc5) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c0a5050cf8d133004340561fb96f11f609db00b/crates/starknet_l1_provider/src/lib.rs#L3)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Fully-qualified, please.
</blockquote></details>

Other direction, I prefer `impl std::fmt::Display`.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2058)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`crates/starknet_l1_provider/src/l1_provider_tests.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2058#-OBePw8ODk_-JaaJkGKI:-OBtH3968R5DkBws2J3f:bb77uch) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c0a5050cf8d133004340561fb96f11f609db00b/crates/starknet_l1_provider/src/l1_provider_tests.rs#L13)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

So when working on validate mode, you plan to add it?
</blockquote></details>

Yep 
___
*[`crates/starknet_l1_provider/src/lib.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2058#-OBePNcY1uv0BNCebgNh:-OBtHPAl-MxM8ym0v0HO:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/6c0a5050cf8d133004340561fb96f11f609db00b/crates/starknet_l1_provider/src/lib.rs#L3)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Other direction, I prefer `impl std::fmt::Display`.
</blockquote></details>

Done

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2058#-:-OBtXQzHEdJWa7yf1AKx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/starknet_mempool/src/mempool.rs` line 358 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2058#-OBtXPoLEqJxwW2Qch0e:-OBtXPoLEqJxwW2Qch0f:bgc7vqv) ([raw file](https://github.com/starkware-libs/sequencer/blob/2bae6c226973bf7fea8bdf89ae54ad148691c5e8/crates/starknet_mempool/src/mempool.rs#L358)):*
> ```XML
> }
> 
> impl std::fmt::Display for TransactionReference {
> ```

:heart: 



_Code quote:_
```XML
impl std::fmt::Display for TransactionReference {
```

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2058)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2058)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
