### PR TITLE
refactor(mempool): add a commit_block test util

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/882)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
This is only extract to func? no logic changes?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/882#-:-O78V0Ni3rVD0Sblg55s:b-9ovjzn)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/882#-O78VKPn5BteMKw3yhJN:-O78VKPn5BteMKw3yhJO:bjtsvt9) ([raw file](https://github.com/starkware-libs/sequencer/blob/e981c978f5f2c0844e60b7ab4276722f6c0ba4d6/crates/mempool/src/mempool_test.rs#L148)):*
> ```XML
>     }));
> 
>     assert!(mempool.commit_block(state_changes).is_ok());
> ```

This has better error message on fail.
`unwrap` is also good.
Can be on a separate PR though plz, to keep commit free of logic changes (however maybe its ok here, since it is the only change)



_Suggestion:_
```XML
    assert_eq!(mempool.commit_block(state_changes), Ok());
```

**Review by elintul — COMMENTED** [review]
Yup, will make sure to write it down next time.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/882#-:-O78WXgw29ZC-MggnHUh:b-lbdrfl)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/882#-O78VKPn5BteMKw3yhJN:-O78Wgha9379S1x9e8oo:b-tpozkm) ([raw file](https://github.com/starkware-libs/sequencer/blob/e981c978f5f2c0844e60b7ab4276722f6c0ba4d6/crates/mempool/src/mempool_test.rs#L148)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This has better error message on fail.
`unwrap` is also good.
Can be on a separate PR though plz, to keep commit free of logic changes (however maybe its ok here, since it is the only change)
</blockquote></details>

NP, thanks.

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/882)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/882#-O78XL487SebZydziN43:-O78XL487SebZydziN44:b-75ywm7) ([raw file](https://github.com/starkware-libs/sequencer/blob/0d9cbd093268bb8480a0814b78be74e56c3e0b09/crates/mempool/src/mempool_test.rs#L145)):*
> ```XML
> fn commit_block(
>     mempool: &mut Mempool,
>     state_changes: impl IntoIterator<Item = (&'static str, u8)>,
> ```

why is this needed?



_Code quote:_
```XML
&'static
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/882)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 145 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/882#-O78XL487SebZydziN43:-O78YmXdC3e9vIdIJwSp:bkvx6uv) ([raw file](https://github.com/starkware-libs/sequencer/blob/0d9cbd093268bb8480a0814b78be74e56c3e0b09/crates/mempool/src/mempool_test.rs#L145)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

Since `&str` is a reference and require lifetime.

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/882)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 816 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/882#-O78Z1921kuYaWWbmVOt:-O78Z1921kuYaWWbmVOu:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/0d9cbd093268bb8480a0814b78be74e56c3e0b09/crates/mempool/src/mempool_test.rs#L816)):*
> ```XML
>     // Test.
>     let state_changes =
>         [("0x0", 5_u8), ("0x1", 0_u8), /* A hole, missing nonce 1. */ ("0x2", 1_u8)];
> ```





_Suggestion:_
```XML
[("0x0", 5_u8), /* A hole, missing nonce 1. */ ("0x1", 0_u8), ("0x2", 1_u8)];
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/882)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 816 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/882#-O78Z1921kuYaWWbmVOt:-O78_n-R0PqOgrKYQRnp:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0d9cbd093268bb8480a0814b78be74e56c3e0b09/crates/mempool/src/mempool_test.rs#L816)):*
> ```XML
>     // Test.
>     let state_changes =
>         [("0x0", 5_u8), ("0x1", 0_u8), /* A hole, missing nonce 1. */ ("0x2", 1_u8)];
> ```

Done.

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/882)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

**Review by ayeletstarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/882)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/882#-:-O78a8cp-Rutm1XDqVbj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/882#-:-O78adylDv3YJl4y6YhZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
