### PR TITLE
refactor: blockHeaderWithoutHash under BlockHeader

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/931)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/931)* status: all files reviewed, 2 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 519 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/931#-O7OygXC9HPdGEZ_m81F:-O7OygXC9HPdGEZ_m81G:bu5idst) ([raw file](https://github.com/starkware-libs/sequencer/blob/3677f1858105eaffac4d2e85d3014ef27ec527ff/crates/papyrus_sync/src/sources/central_sync_test.rs#L519)):*
> ```XML
>                                 block_number: i,
>                                 parent_hash: create_block_hash(i.prev().unwrap_or_default(), i.0 > CHAIN_FORK_BLOCK_NUMBER),
>                                 ..BlockHeaderWithoutHash::default()
> ```

I would also change the BlockHeader::default() too, no reason to write the type twice



_Suggestion:_
```XML
..Default::default()
```
___
*[`crates/papyrus_test_utils/src/lib.rs` line 453 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/931#-O7OyszN9xWdftS-uB0e:-O7OyszN9xWdftS-uB0f:bnxl8a0) ([raw file](https://github.com/starkware-libs/sequencer/blob/3677f1858105eaffac4d2e85d3014ef27ec527ff/crates/papyrus_test_utils/src/lib.rs#L453)):*
> ```XML
>         pub n_events: usize,
>     }
>     pub struct BlockHeaderWithoutHash {
> ```

ah... I thought this was an existing struct.
since it's new, maybe wise to think of a better name now rather than later...
how about `UncommittedBlockHeader`?
@Yoni-Starkware you have an opinion?



_Code quote:_
```XML
pub struct BlockHeaderWithoutHash
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/931)* status: all files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/papyrus_test_utils/src/lib.rs` line 453 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/931#-O7OyszN9xWdftS-uB0e:-O7ScSjlCdnYefTFw3jG:b-m5lxbp) ([raw file](https://github.com/starkware-libs/sequencer/blob/3677f1858105eaffac4d2e85d3014ef27ec527ff/crates/papyrus_test_utils/src/lib.rs#L453)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah... I thought this was an existing struct.
since it's new, maybe wise to think of a better name now rather than later...
how about `UncommittedBlockHeader`?
@Yoni-Starkware you have an opinion?
</blockquote></details>

It is an existing struct. Here it's just a test util.
Look at crates/starknet_api/src/block.rs

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/931)* status: 21 of 25 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/papyrus_sync/src/sources/central_sync_test.rs` line 519 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/931#-O7OygXC9HPdGEZ_m81F:-O7TNOOJ-lRVzqwf0VDu:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3677f1858105eaffac4d2e85d3014ef27ec527ff/crates/papyrus_sync/src/sources/central_sync_test.rs#L519)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I would also change the BlockHeader::default() too, no reason to write the type twice
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/931#-:-O7U1HnY34y4hNuwzoy6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/931)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
