### PR TITLE
chore: run codecov only on changed crates

### PR DESCRIPTION
**Pull request by nadin-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/633)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/633)* status: all files reviewed, 5 unresolved discussions (waiting on @nadin-Starkware)

___
*[`.github/workflows/main.yml` line 218 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/633#-O5NiA960Pr1scgmkLb7:-O5NiA960Pr1scgmkLb8:by1hw3n) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d47b4e47ae91b60e00ad5c88e17e7e045ef9bfe/.github/workflows/main.yml#L218)):*
> ```YAML
>       - uses: Swatinem/rust-cache@v2
>         with:
>           prefix-key: "v0-rust-ubuntu-20.04"
> ```

these lines are duplicated I think



_Code quote:_
```YAML
      - uses: ./.github/actions/install_rust
      - uses: Noelware/setup-protoc@1.1.0
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust-ubuntu-20.04"
```
___
*[`.github/workflows/main.yml` line 247 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/633#-O5NireqEW5v2ruZuD15:-O5NireqEW5v2ruZuD16:b-8m605z) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d47b4e47ae91b60e00ad5c88e17e7e045ef9bfe/.github/workflows/main.yml#L247)):*
> ```YAML
>           python3 -m venv ci
>           ci/bin/pip install -r scripts/requirements.txt
>           ci/bin/python scripts/run_codecov.py --commit_id ${{ github.event.pull_request.base.sha }}
> ```

`github.event.pull_request` is defined only if the event is a pull request (and not a merge, or `push` event, for example).
See how this is done for run_tests.py: there are two runs, one with `--commit_id` and one without, depending on the event type



_Code quote:_
```YAML
        run: |
          python3 -m venv ci
          ci/bin/pip install -r scripts/requirements.txt
          ci/bin/python scripts/run_codecov.py --commit_id ${{ github.event.pull_request.base.sha }}
```
___
*[`scripts/run_codecov.py` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/633#-O5NjiBD7mNTPwoT_cNw:-O5NjiBD7mNTPwoT_cNx:b4yvxrz) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d47b4e47ae91b60e00ad5c88e17e7e045ef9bfe/scripts/run_codecov.py#L25)):*
> ```Python
>         args.extend(["--package", package])
> 
>     cmd = ["cargo", "llvm-cov", "--codecov", "-r", "--output-path", "codecov.json"] + args
> ```

need to take `--changes_only` into account:
notice what happens if there are no modified packages.
you end up running `cargo llvm-cov` without any `--package` args,
which will run it on the entire workspace.
if `--changes_only` is set, you need to `return` without running anything if there are no modified packages



_Code quote:_
```Python
    args = []

    for package in modified_packages:
        args.extend(["--package", package])

    cmd = ["cargo", "llvm-cov", "--codecov", "-r", "--output-path", "codecov.json"] + args
```
___
*[`scripts/run_codecov.py` line 34 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/633#-O5NjY1a2BCBwZT7vvMt:-O5NjY1a2BCBwZT7vvMu:b-alw7rw) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d47b4e47ae91b60e00ad5c88e17e7e045ef9bfe/scripts/run_codecov.py#L34)):*
> ```Python
> 
> def parse_args() -> argparse.Namespace:
>     parser = argparse.ArgumentParser(description="Presubmit script.")
> ```

nope lol



_Code quote:_
```Python
"Presubmit script."
```
___
*[`scripts/run_codecov.py` line 35 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/633#-O5NjQZ728RMWDnnPs0O:-O5NjQZ728RMWDnnPs0P:b6bzudn) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d47b4e47ae91b60e00ad5c88e17e7e045ef9bfe/scripts/run_codecov.py#L35)):*
> ```Python
> def parse_args() -> argparse.Namespace:
>     parser = argparse.ArgumentParser(description="Presubmit script.")
>     parser.add_argument("--commit_id", type=str, help="GIT commit ID to compare against.")
> ```

you may need a `changes_only` flag as well, on `push` events (see above) you won't be using `git diff` to check for diffs IIUC



_Code quote:_
```Python
parser.add_argument("--commit_id", type=str, help="GIT commit ID to compare against.")
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/633)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`.github/workflows/main.yml` line 218 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/633#-O5NiA960Pr1scgmkLb7:-O5Np47sDyMcNh3OsRfx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d47b4e47ae91b60e00ad5c88e17e7e045ef9bfe/.github/workflows/main.yml#L218)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

these lines are duplicated I think
</blockquote></details>

Done.
___
*[`.github/workflows/main.yml` line 247 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/633#-O5NireqEW5v2ruZuD15:-O5NoY3z3WdMGGH3TmeY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d47b4e47ae91b60e00ad5c88e17e7e045ef9bfe/.github/workflows/main.yml#L247)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`github.event.pull_request` is defined only if the event is a pull request (and not a merge, or `push` event, for example).
See how this is done for run_tests.py: there are two runs, one with `--commit_id` and one without, depending on the event type
</blockquote></details>

Done.
___
*[`scripts/run_codecov.py` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/633#-O5NjiBD7mNTPwoT_cNw:-O5NnLTo4ey07JJnjmKB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d47b4e47ae91b60e00ad5c88e17e7e045ef9bfe/scripts/run_codecov.py#L25)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

need to take `--changes_only` into account:
notice what happens if there are no modified packages.
you end up running `cargo llvm-cov` without any `--package` args,
which will run it on the entire workspace.
if `--changes_only` is set, you need to `return` without running anything if there are no modified packages
</blockquote></details>

Done.
___
*[`scripts/run_codecov.py` line 34 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/633#-O5NjY1a2BCBwZT7vvMt:-O5NmPIx0hapafKpE7Mo:bb71nyg) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d47b4e47ae91b60e00ad5c88e17e7e045ef9bfe/scripts/run_codecov.py#L34)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

nope lol
</blockquote></details>

Oops
___
*[`scripts/run_codecov.py` line 35 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/633#-O5NjQZ728RMWDnnPs0O:-O5Np9L-BccY3rhPfcdm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9d47b4e47ae91b60e00ad5c88e17e7e045ef9bfe/scripts/run_codecov.py#L35)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you may need a `changes_only` flag as well, on `push` events (see above) you won't be using `git diff` to check for diffs IIUC
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/633)* status: all files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

___
*[`scripts/run_codecov.py` line 19 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/633#-O5Nq7C3CsBpwTWKQPUi:-O5Nq7C3CsBpwTWKQPUj:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d033053cfcffa973de4e9d25e365b3e229543fe2/scripts/run_codecov.py#L19)):*
> ```Python
> 
>     if changes_only:
>         if len(modified_packages) == 0:
> ```





_Suggestion:_
```Python
    if changes_only and len(modified_packages) == 0:
```
___
*[`scripts/run_codecov.py` line 39 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/633#-O5NqBi-23jcsAxAPFRt:-O5NqBi-23jcsAxAPFRu:bb7phvt) ([raw file](https://github.com/starkware-libs/sequencer/blob/d033053cfcffa973de4e9d25e365b3e229543fe2/scripts/run_codecov.py#L39)):*
> ```Python
> 
> def parse_args() -> argparse.Namespace:
>     parser = argparse.ArgumentParser(description="Code coverage csript.")
> ```

typo



_Code quote:_
```Python
csript
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/633)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`scripts/run_codecov.py` line 19 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/633#-O5Nq7C3CsBpwTWKQPUi:-O5Nzi1YCsuZHPDEY3yy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d033053cfcffa973de4e9d25e365b3e229543fe2/scripts/run_codecov.py#L19)):*
> ```Python
> 
>     if changes_only:
>         if len(modified_packages) == 0:
> ```

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/633)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

___
*[`.github/workflows/main.yml` line 251 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/633#-O5NzuUC2oHrMQ0vOsWQ:-O5NzuUC2oHrMQ0vOsWR:b-cbnzfn) ([raw file](https://github.com/starkware-libs/sequencer/blob/2059607ac4adef64ac43fe797bd92c42b394e1f0/.github/workflows/main.yml#L251)):*
> ```YAML
>           else
>             echo "codecov_output=false" >> $GITHUB_OUTPUT
>           fi
> ```

what's this...? why wouldn't the JSON appear?



_Code quote:_
```YAML
          if [ -f codecov.json ]; then
            echo "codecov_output=true" >> $GITHUB_OUTPUT
          else
            echo "codecov_output=false" >> $GITHUB_OUTPUT
          fi
```
___
*[`scripts/run_codecov.py` line 19 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/633#-O5Nq7C3CsBpwTWKQPUi:-O5NzyNV1UVV8yTAAsk0:b-irwhab) ([raw file](https://github.com/starkware-libs/sequencer/blob/d033053cfcffa973de4e9d25e365b3e229543fe2/scripts/run_codecov.py#L19)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

where?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/633)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/633)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`.github/workflows/main.yml` line 251 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/633#-O5NzuUC2oHrMQ0vOsWQ:-O5O-IbRC9yaLjZNG3cB:busgzsc) ([raw file](https://github.com/starkware-libs/sequencer/blob/2059607ac4adef64ac43fe797bd92c42b394e1f0/.github/workflows/main.yml#L251)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what's this...? why wouldn't the JSON appear?
</blockquote></details>

If there is no changes it wouldn't be there
___
*[`scripts/run_codecov.py` line 19 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/633#-O5Nq7C3CsBpwTWKQPUi:-O5O-VqK7NKiliNYQePd:by6g8oz) ([raw file](https://github.com/starkware-libs/sequencer/blob/d033053cfcffa973de4e9d25e365b3e229543fe2/scripts/run_codecov.py#L19)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where?
</blockquote></details>

sorry, I missed to push

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/633)* status: all files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`.github/workflows/main.yml` line 262 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/633#-O5O03m09IW4XGyuE-ck:-O5O03m09IW4XGyuE-cl:b18jepk) ([raw file](https://github.com/starkware-libs/sequencer/blob/2059607ac4adef64ac43fe797bd92c42b394e1f0/.github/workflows/main.yml#L262)):*
> ```YAML
>           ci/bin/pip install -r scripts/requirements.txt
>           ci/bin/python scripts/run_codecov.py
>           echo "codecov_output=false" >> $GITHUB_OUTPUT
> ```

why would this be false? here, you run codecov on the entire workspace



_Code quote:_
```YAML
echo "codecov_output=false" >> $GITHUB_OUTPUT
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/633#-:-O5O1Mvh3DKwfgh_yZde:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Pull request merged**
