### PR TITLE
build(blockifier_reexecution): add serialization for reexecution data

### PR DESCRIPTION
**Pull request by aner-starkware**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1744)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1744#-OAmjsj225NbEtAsqMrQ:-OAmjsj30j76MyySKHJk:bxkgd8v) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba49a4c09635670a6fe7d44d9a6b832aff29172b/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L69)):*
> ```XML
>         fs::create_dir_all(file_path).expect("Failed to create directory");
>         fs::write(file_path.to_owned() + "/" + file_name, serde_json::to_string_pretty(&self)?)
>             .expect("Failed to write reexecution data to file.");
> ```

print the problematic input



_Suggestion:_
```XML
        fs::create_dir_all(file_path).expect(format!("Failed to create directory '{file_path}'."));
        let full_file_path = file_path.to_owned() + "/" + file_name;
        fs::write(full_file_path, serde_json::to_string_pretty(&self)?)
            .expect(format!("Failed to write reexecution data to file '{full_file_path}'."));
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1744#-OAmu_Ia9Ufjaj5bRM6r:-OAmu_Ia9Ufjaj5bRM6s:bfs57mv) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba49a4c09635670a6fe7d44d9a6b832aff29172b/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L80)):*
> ```XML
>             contract_class_mapping: value.contract_class_mapping,
>         };
>         let transactions_next_block = offline_state_reader_prev_block
> ```

if the offline state reader is from the previous block, why are the "next" txs in it?
maybe rename the `offline_state_reader_prev_block` field, if it's fields are from different blocks;
the fields of `OfflineStateReader` should maybe be renamed to include `prev` or `next`...?
or am I misunderstanding the field semantics?



_Code quote:_
```XML
transactions_next_block = offline_state_reader_prev_block
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1744#-OAmusQk0FyD0Yx1xms1:-OAmusQk0FyD0Yx1xms2:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba49a4c09635670a6fe7d44d9a6b832aff29172b/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L83)):*
> ```XML
>             .api_txs_to_blockifier_txs(value.transactions_next_block)
>             .expect("Failed to convert starknet-api transactions to blockifier transactions.");
>         OfflineReexecutionData {
> ```





_Suggestion:_
```XML
 Self
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 473 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1744#-OAmv7jn7RhVO3e1xMId:-OAmv7jn7RhVO3e1xMIe:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba49a4c09635670a6fe7d44d9a6b832aff29172b/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L473)):*
> ```XML
>         }: OfflineReexecutionData,
>     ) -> Self {
>         OfflineConsecutiveStateReaders {
> ```





_Suggestion:_
```XML
Self
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1744)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1744#-OAmjsj225NbEtAsqMrQ:-OApjvbfC6AKn32AHRRq:bvbk9gf) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba49a4c09635670a6fe7d44d9a6b832aff29172b/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L69)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

print the problematic input
</blockquote></details>

Done. The compiler doesn't like `format!` inside `except`.
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1744#-OAmu_Ia9Ufjaj5bRM6r:-OApjwpcCPXDUjw3K1Zj:b-o86dth) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba49a4c09635670a6fe7d44d9a6b832aff29172b/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L80)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if the offline state reader is from the previous block, why are the "next" txs in it?
maybe rename the `offline_state_reader_prev_block` field, if it's fields are from different blocks;
the fields of `OfflineStateReader` should maybe be renamed to include `prev` or `next`...?
or am I misunderstanding the field semantics?
</blockquote></details>

I think this is correct - the TXs are not part of the previous block, but the conversion of the TXs for the next block uses info from the previous block, IIUC; let's talk about this with @AvivYossef-starkware and decide here.
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1744#-OAmusQk0FyD0Yx1xms1:-OApiGslDy1dM05jKix8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba49a4c09635670a6fe7d44d9a6b832aff29172b/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L83)):*
> ```XML
>             .api_txs_to_blockifier_txs(value.transactions_next_block)
>             .expect("Failed to convert starknet-api transactions to blockifier transactions.");
>         OfflineReexecutionData {
> ```

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 473 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1744#-OAmv7jn7RhVO3e1xMId:-OApizji7bHoZOKwyQUn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba49a4c09635670a6fe7d44d9a6b832aff29172b/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L473)):*
> ```XML
>         }: OfflineReexecutionData,
>     ) -> Self {
>         OfflineConsecutiveStateReaders {
> ```

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1744)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1744#-OAmu_Ia9Ufjaj5bRM6r:-OArEdU69uqZbQrgGRpH:b-opakd) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba49a4c09635670a6fe7d44d9a6b832aff29172b/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L80)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I think this is correct - the TXs are not part of the previous block, but the conversion of the TXs for the next block uses info from the previous block, IIUC; let's talk about this with @AvivYossef-starkware and decide here.
</blockquote></details>

nope (right?)

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1744#-OAmu_Ia9Ufjaj5bRM6r:-OArPKKC535p5NgXPIv0:b-itie6q) ([raw file](https://github.com/starkware-libs/sequencer/blob/ba49a4c09635670a6fe7d44d9a6b832aff29172b/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L80)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

nope (right?)
</blockquote></details>

I looked again - the other option (next), doesn't seem to make sense to me (maybe I'm missing something?)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1744#-:-OArY2RI84v1kaDQOqks:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
