### PR TITLE
feat(batcher): add abort to the proposal manager

### PR DESCRIPTION
**Pull request by dafnamatsry**

### CODE REVIEW

**Comment by dafnamatsry** [comment]
* **#2060** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2060?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dafnamatsry and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2060)* status: all files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 348 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2060#-OBtAY8V1y6CZhthIa2S:-OBtAY8V1y6CZhthIa2T:b-r4zfkl) ([raw file](https://github.com/starkware-libs/sequencer/blob/a998babbf4189fdcc1f99bccc0a5f6139e92ecf1/crates/starknet_batcher/src/batcher.rs#L348)):*
> ```XML
>                 BatcherError::ExecutedProposalNotFound { proposal_id }
>             }
>             GetProposalResultError::Aborted => BatcherError::ProposalAborted,
> ```

Do we want it as a batcher error? IIUC it's either there was an abort request from the consensus, or the abort was internal.



_Code quote:_
```XML
GetProposalResultError::Aborted => BatcherError::ProposalAborted,
```
___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 394 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2060#-OBtYkF252botVVpzH61:-OBtYkF252botVVpzH62:b-c13lqf) ([raw file](https://github.com/starkware-libs/sequencer/blob/a998babbf4189fdcc1f99bccc0a5f6139e92ecf1/crates/starknet_batcher/src/proposal_manager_test.rs#L394)):*
> ```XML
>     // Make sure there is no active proposal.
>     // TODO: uncommomment once the abort is implemented. This line will panic now.
>     // assert!(!proposal_manager.await_active_proposal().await);
> ```

Can you uncomment now?



_Code quote:_
```XML
    // TODO: uncommomment once the abort is implemented. This line will panic now.
    // assert!(!proposal_manager.await_active_proposal().await);
```
___
*[`crates/starknet_batcher/src/proposal_manager.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2060#-OBtUWE_D0j4ZSF0pfdo:-OBtUWE_D0j4ZSF0pfdp:bci4a6y) ([raw file](https://github.com/starkware-libs/sequencer/blob/a998babbf4189fdcc1f99bccc0a5f6139e92ecf1/crates/starknet_batcher/src/proposal_manager.rs#L294)):*
> ```XML
>     }
> 
>     async fn abort_proposal(&mut self, proposal_id: ProposalId) {
> ```

Document (this should only be called if an external abort signal was sent in the validate flow).



_Code quote:_
```XML
async fn abort_proposal(&mut self, proposal_id: ProposalId) {
```
___
*[`crates/starknet_batcher/src/proposal_manager.rs` line 339 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2060#-OBtU-eL0QR37xnuD2C5:-OBtU-eMAdL9ztezT3NG:b-lrvbc4) ([raw file](https://github.com/starkware-libs/sequencer/blob/a998babbf4189fdcc1f99bccc0a5f6139e92ecf1/crates/starknet_batcher/src/proposal_manager.rs#L339)):*
> ```XML
>                 // Keep the proposal result only if it is the same as the active proposal.
>                 let mut active_proposal = active_proposal.lock().await;
>                 if active_proposal.is_some_and(|id| id == proposal_id) {
> ```

If this is iff the task was aborted, can we make it more explicit?



_Code quote:_
```XML
if active_proposal.is_some_and(|id| id == proposal_id) {
```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2060)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 348 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2060#-OBtAY8V1y6CZhthIa2S:-OBtqazx39PlZmu3YJAl:b-c5yo8q) ([raw file](https://github.com/starkware-libs/sequencer/blob/a998babbf4189fdcc1f99bccc0a5f6139e92ecf1/crates/starknet_batcher/src/batcher.rs#L348)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Do we want it as a batcher error? IIUC it's either there was an abort request from the consensus, or the abort was internal.
</blockquote></details>

Good question, I guess that should never happen (the consensus shouldn't ask for a proposal content if it got aborted).
Not sure what to return though: `ProposalFailed`/`ProposalNotFound`?
___
*[`crates/starknet_batcher/src/proposal_manager.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2060#-OBtUWE_D0j4ZSF0pfdo:-OBtioXj8boeLDUuFmS5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a998babbf4189fdcc1f99bccc0a5f6139e92ecf1/crates/starknet_batcher/src/proposal_manager.rs#L294)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Document (this should only be called if an external abort signal was sent in the validate flow).
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/proposal_manager.rs` line 339 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2060#-OBtU-eL0QR37xnuD2C5:-OBtnAReB60UU1hR9ZSX:b-m2afhc) ([raw file](https://github.com/starkware-libs/sequencer/blob/a998babbf4189fdcc1f99bccc0a5f6139e92ecf1/crates/starknet_batcher/src/proposal_manager.rs#L339)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

If this is iff the task was aborted, can we make it more explicit?
</blockquote></details>

Talked f2f. Added a comment to clarify that.
___
*[`crates/starknet_batcher/src/proposal_manager_test.rs` line 394 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2060#-OBtYkF252botVVpzH61:-OBtlDDSAhZFNYNjE8eL:bpm9hl) ([raw file](https://github.com/starkware-libs/sequencer/blob/a998babbf4189fdcc1f99bccc0a5f6139e92ecf1/crates/starknet_batcher/src/proposal_manager_test.rs#L394)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you uncomment now?
</blockquote></details>

In this PR, no one calls to abort yet.
In the next PR it is uncommented (with additional small changes, since duplicate call to start_height with the same height should fail).

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2060#-:-OBu2YsD7Iyii4HosDHE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 348 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2060#-OBtAY8V1y6CZhthIa2S:-OBu15bL9rE36SUjoiG0:bmjjh8c) ([raw file](https://github.com/starkware-libs/sequencer/blob/a998babbf4189fdcc1f99bccc0a5f6139e92ecf1/crates/starknet_batcher/src/batcher.rs#L348)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Good question, I guess that should never happen (the consensus shouldn't ask for a proposal content if it got aborted).
Not sure what to return though: `ProposalFailed`/`ProposalNotFound`?
</blockquote></details>

Oh this is only returned when trying to get the proposal. That's fine then.

**Comment by dafnamatsry** [comment]
### Merge activity

* **Nov 17, 8:01 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2060).

**Pull request merged**
