### PR TITLE
refactor(blockifier): switch use of blockifier classinfo by starknet_api classinfo

### PR DESCRIPTION
**Pull request by avivg-starkware**
…api classinfo

### CODE REVIEW

**Review by meship-starkware — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware and @noaov1)

**Comment by ArniStarkware** [comment]
*[`crates/native_blockifier/src/py_transaction.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1858#-OB4t86V4x9lccmuO46_:-OB4t86V4x9lccmuO46a:b-r0rux7) ([raw file](https://github.com/starkware-libs/sequencer/blob/c755b6f17d5b8dfcf1dc042293169fa681b501e5/crates/native_blockifier/src/py_transaction.rs#L185)):*
> ```XML
>         Ok(class_info)
>     }
> }
> ```

Are we sure this works?
This is a cross repo function.
The issue is that `raw_contract_class` is formatted for the `cairo_vm` stuff (i.e. the Blockifier::ContractClass).


Where is this `try_from` used? I ask because I hope we can go around this issue.



_Code quote:_
```XML
impl PyClassInfo {
    pub fn try_from(
        py_class_info: PyClassInfo,
        tx: &starknet_api::transaction::DeclareTransaction,
    ) -> NativeBlockifierResult<ClassInfo> {
        let contract_class = match tx {
            starknet_api::transaction::DeclareTransaction::V0(_)
            | starknet_api::transaction::DeclareTransaction::V1(_) => {
                ContractClass::V0(serde_json::from_str(&py_class_info.raw_contract_class)?)
            }
            starknet_api::transaction::DeclareTransaction::V2(_)
            | starknet_api::transaction::DeclareTransaction::V3(_) => {
                ContractClass::V1(serde_json::from_str(&py_class_info.raw_contract_class)?)
            }
        };
        let class_info = ClassInfo::new(
            &contract_class,
            py_class_info.sierra_program_length,
            py_class_info.abi_length,
        )?;
        Ok(class_info)
    }
}
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 10 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware and @noaov1)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware and @noaov1)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1858#-OB4t86V4x9lccmuO46_:-OB5Yf45E_ErV0wYTYCe:bwj2utb) ([raw file](https://github.com/starkware-libs/sequencer/blob/c755b6f17d5b8dfcf1dc042293169fa681b501e5/crates/native_blockifier/src/py_transaction.rs#L185)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Are we sure this works?
This is a cross repo function.
The issue is that `raw_contract_class` is formatted for the `cairo_vm` stuff (i.e. the Blockifier::ContractClass).


Where is this `try_from` used? I ask because I hope we can go around this issue.
</blockquote></details>

As far as I understand this is used only once in the code, where according to the change, the expected struct is indeed the api_class_info. As the fields of blockifier_class_info and api_class_info are identical, i expect, that the conversion should stay the same. @noaov1 was the one to make this correlation, WDYT? Is there something I'm missing? 

Attaching the effected code where this is used, 1st snippet is of current impl and 2nd is after #1688 PR
(in native_blockifier::py_declare.rs)



_Code snippet (i):_
```XML
use blockifier::transaction::transactions::DeclareTransaction;

pub fn py_declare(
    py_tx: &PyAny,
    py_class_info: PyClassInfo,
) -> NativeBlockifierResult<DeclareTransaction> {
...
    let class_info = PyClassInfo::try_from(py_class_info, &tx)?;
    Ok(DeclareTransaction::new(tx, tx_hash, class_info)?)
}
```



_Code snippet (ii):_
```XML
use starknet_api::executable_transaction::DeclareTransaction;

pub fn py_declare(
    py_tx: &PyAny,
    py_class_info: PyClassInfo,
) -> NativeBlockifierResult<DeclareTransaction> {
...
    let class_info = PyClassInfo::try_from(py_class_info, &tx)?;
    Ok(DeclareTransaction { tx, tx_hash, class_info })
}
```

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Comment by ArniStarkware** [comment]
*[`crates/native_blockifier/src/py_transaction.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1858#-OB4t86V4x9lccmuO46_:-OB6gQVz4yCt4-lzm816:bq190be) ([raw file](https://github.com/starkware-libs/sequencer/blob/c755b6f17d5b8dfcf1dc042293169fa681b501e5/crates/native_blockifier/src/py_transaction.rs#L185)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

As far as I understand this is used only once in the code, where according to the change, the expected struct is indeed the api_class_info. As the fields of blockifier_class_info and api_class_info are identical, i expect, that the conversion should stay the same. @noaov1 was the one to make this correlation, WDYT? Is there something I'm missing? 

Attaching the effected code where this is used, 1st snippet is of current impl and 2nd is after #1688 PR
(in native_blockifier::py_declare.rs)
</blockquote></details>

[Python side](https://github.com/starkware-industries/starkware/blob/e5a2aadf70cc643fc55d23c5bc1174c9a1d7003c/src/starkware/starknet/business_logic/blockifier/blockifier.py#L189-L191) The corresponding `txs_with_class_infos` should have pre-processed `class_info` or, if this is too much work, we can save the old class info and have two types of `ClassInfo` :(

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @avivg-starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1858#-OB4t86V4x9lccmuO46_:-OBGk_Xq6RBFmeVBuCyC:b-l6hdk0) ([raw file](https://github.com/starkware-libs/sequencer/blob/c755b6f17d5b8dfcf1dc042293169fa681b501e5/crates/native_blockifier/src/py_transaction.rs#L185)):*
> The issue is that `raw_contract_class` is formatted for the `cairo_vm` stuff (i.e. the Blockifier::ContractClass).

Nope :)
The Python code passes a raw object, which is the output of the compilation. Note that the blockifier's class information already included the new contract class enum. I modified this in #1730. In this PR, you can see that before my change, we converted the string to the raw contract class (i.e., starkNet API contract class) and then converted it to the VM format  (look at the method `try_from_json_string`).
___
*[`crates/blockifier/src/transaction/transactions.rs` line 202 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1858#-OBGmS0M07C4vANvX6yA:-OBGmS0N6G2gb1MHmZDJ:b-yzis9j) ([raw file](https://github.com/starkware-libs/sequencer/blob/7f0312927d1ecc9fa3b64559a733f180a9f3a4f9/crates/blockifier/src/transaction/transactions.rs#L202)):*
> ```XML
>         let starknet_api::executable_transaction::DeclareTransaction { tx, tx_hash, class_info } =
>             declare_tx;
>         let class_info = class_info.try_into()?;
> ```

Note to self: This conversion had no effect.



_Code quote:_
```XML
let class_info = class_info.try_into()?;
```
___
*[`crates/native_blockifier/src/errors.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1858#-OBGmrW_-AUTvvGUPanC:-OBGmrWa3MCwtajHabzh:bti1onm) ([raw file](https://github.com/starkware-libs/sequencer/blob/7f0312927d1ecc9fa3b64559a733f180a9f3a4f9/crates/native_blockifier/src/errors.rs#L70)):*
> ```XML
> 
> native_blockifier_errors!(
>     (ContractClassError, ContractClassError, PyContractClassError),
> ```

This require a change in the python code. 



_Code quote:_
```XML
(ContractClassError, ContractClassError, PyContractClassError),
```

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @avivg-starkware)

**Comment by ArniStarkware** [comment]
*[`crates/native_blockifier/src/py_transaction.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1858#-OB4t86V4x9lccmuO46_:-OBK9hZ46mSv14O-wlB6:b-1fa6xd) ([raw file](https://github.com/starkware-libs/sequencer/blob/c755b6f17d5b8dfcf1dc042293169fa681b501e5/crates/native_blockifier/src/py_transaction.rs#L185)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

> The issue is that `raw_contract_class` is formatted for the `cairo_vm` stuff (i.e. the Blockifier::ContractClass).

Nope :)
The Python code passes a raw object, which is the output of the compilation. Note that the blockifier's class information already included the new contract class enum. I modified this in #1730. In this PR, you can see that before my change, we converted the string to the raw contract class (i.e., starkNet API contract class) and then converted it to the VM format  (look at the method `try_from_json_string`).
</blockquote></details>

Great!!
Unblocking.

Anyway, I think it will be a good idea to bump the blockifier version on the Python side for this change.

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1858#-OB4t86V4x9lccmuO46_:-OBKAQBy6gwaL455T1ge:bnypgs0) ([raw file](https://github.com/starkware-libs/sequencer/blob/c755b6f17d5b8dfcf1dc042293169fa681b501e5/crates/native_blockifier/src/py_transaction.rs#L185)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Great!!
Unblocking.

Anyway, I think it will be a good idea to bump the blockifier version on the Python side for this change.
</blockquote></details>

(My "anyway" was accounted for on another thread in this review).

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 11 files at r1, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @avivg-starkware, @meship-starkware, and @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware, @meship-starkware, and @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware and @noaov1)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @meship-starkware, and @noaov1)

___
*[`crates/native_blockifier/src/errors.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1858#-OBGmrW_-AUTvvGUPanC:-OBLn_Ep38FpScVp31XI:b3yaf3n) ([raw file](https://github.com/starkware-libs/sequencer/blob/7f0312927d1ecc9fa3b64559a733f180a9f3a4f9/crates/native_blockifier/src/errors.rs#L70)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

This require a change in the python code.
</blockquote></details>

Added a TODO, should do something else? rephrase?

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Comment by avivg-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1858?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1688** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1688?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1858** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1858?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1702** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1702?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @avivg-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by avivg-starkware — COMMENTED** [review]
> Reviewed 2 of 11 files at r1, 1 of 1 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Comment by ArniStarkware** [comment]
*[`crates/native_blockifier/src/errors.rs` line 70 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1858#-OBUFtE65GtFCc7m8r3R:-OBUFtE65GtFCc7m8r3S:b3bau33) ([raw file](https://github.com/starkware-libs/sequencer/blob/13baecd2db77ffdaeb1ddeea8f39bdb8edf42e70/crates/native_blockifier/src/errors.rs#L70)):*
> ```XML
> native_blockifier_errors!(
>     // TODO(AvivG): Have python compatible with removal of '(ContractClassError,
>     // ContractClassError, PyContractClassError)'
> ```

Remove this todo (if and when it was addressed)



_Code quote:_
```XML
    // TODO(AvivG): Have python compatible with removal of '(ContractClassError,
    // ContractClassError, PyContractClassError)'
```

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @meship-starkware, and @noaov1)

___
*[`crates/native_blockifier/src/errors.rs` line 70 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1858#-OBUFtE65GtFCc7m8r3R:-OBUHiCNC-oODQdnoznM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/13baecd2db77ffdaeb1ddeea8f39bdb8edf42e70/crates/native_blockifier/src/errors.rs#L70)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Remove this todo (if and when it was addressed)
</blockquote></details>

Done.

**Review by avivg-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @meship-starkware, and @noaov1)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @meship-starkware, and @noaov1)

___
*[`crates/native_blockifier/src/errors.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1858#-OBGmrW_-AUTvvGUPanC:-OBUKJy_5jCMUKr_jCC3:b1yqcsu) ([raw file](https://github.com/starkware-libs/sequencer/blob/7f0312927d1ecc9fa3b64559a733f180a9f3a4f9/crates/native_blockifier/src/errors.rs#L70)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

Added a TODO, should do something else? rephrase?
</blockquote></details>

Added a python PR addressing this

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: all files reviewed, 2 unresolved discussions (waiting on @avivg-starkware, @meship-starkware, and @noaov1)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1858#-OBUO2EEDglwvK6QfQ88:-OBUO2EEDglwvK6QfQ89:bu6uo33) (no related file):*
Blocking untill the Python side passes.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858#-:-OBUVyVeC_1zptcs1JhV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1858#-OBUO2EEDglwvK6QfQ88:-OBUW_Ro8xbYoCzKfanu:b303rdm) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Blocking untill the Python side passes.
</blockquote></details>

Passed :)

**Review by avivg-starkware — COMMENTED** [review]
> Dismissed @noaov1 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1858)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware and @noaov1)

**Pull request merged**
