### PR TITLE
refactor(blockifier,starknet_api): migrate GasVector from blockifier to starknet_api

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1179)

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1179?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1179** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1179?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1178** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1178?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1177** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1177?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1176** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1176?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1175** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1175?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1174** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1174?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1173** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1173?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1172** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1172?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 20 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1179#-:-O8kRvIu0r8x4---6h-z:bnfp4nl)* status: 20 of 21 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/resources.rs` line 296 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1179#-O8kRIxvETvM1DSZI1As:-O8kRIxvETvM1DSZI1At:b-mq30q0) ([raw file](https://github.com/starkware-libs/sequencer/blob/c9caed400f57387245d7f02e84d05dcc3c663017/crates/blockifier/src/fee/resources.rs#L296)):*
> ```XML
>     }
> }
> ```

Amazing
___
*[`crates/starknet_api/src/block.rs` line 348 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1179#-O8kRXGy8nTS2ksrDZux:-O8kRXGy8nTS2ksrDZuy:bt9cs3l) ([raw file](https://github.com/starkware-libs/sequencer/blob/d57918945deb6abd25bb2826229c2ac1841e449b/crates/starknet_api/src/block.rs#L348)):*
> ```XML
> 
> #[derive(Clone, Debug)]
> pub struct GasPricesForFeeType {
> ```

Not the best name. What about `GasPrices`, or `GasPriceVector`,
and the other struct should be `GasPricesByFeeType



_Code quote:_
```XML
pub struct GasPricesForFeeType {
```

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 21 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1179)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1179)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/starknet_api/src/block.rs` line 348 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1179#-O8kRXGy8nTS2ksrDZux:-O8kpYp1-qap4tSvDQ5z:b-tmt24s) ([raw file](https://github.com/starkware-libs/sequencer/blob/d57918945deb6abd25bb2826229c2ac1841e449b/crates/starknet_api/src/block.rs#L348)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Not the best name. What about `GasPrices`, or `GasPriceVector`,
and the other struct should be `GasPricesByFeeType
</blockquote></details>

what is "the other struct"?

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Oct 9, 7:30 AM EDT**: @dorimedini-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1179).

**Pull request merged**
