### PR TITLE
feat(starknet_api): derive serialize for executable transaction

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/426)

### CODE REVIEW

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/426#-:-O4Jq0a-5ps4TsGrNNIE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @elintul)

**Review by giladchase — APPROVED** [review]
BTW i think you can rebase this onto main and insert directly.
Yr Prs using it will temporarily fail CI, not too bad since this can be merged quickly

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/426#-:-O4Jq3wc1t9aMU-APZbm:b-b9etpf)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @elintul)

**Review by MohammadNassar1 — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/426#-:-O4K-nVsA41KoGfvHf6H:bb6un1j)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ayeletstarkware and @elintul)

**Review by giladchase — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/426)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @elintul)

**Comment by ArniStarkware** [comment]
*[`crates/starknet_api/src/executable_transaction.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/426#-O4Kx5Ag4Ou_AVsvj_L2:-O4Kx5Ag4Ou_AVsvj_L3:b-arm10t) ([raw file](https://github.com/starkware-libs/sequencer/blob/5769af02ffc74a2c5aa97bbedf00cef8270ee793/crates/starknet_api/src/executable_transaction.rs#L64)):*
> ```XML
>     pub tx_hash: TransactionHash,
>     pub class_info: ClassInfo,
> }
> ```

If we want to use Blockifier's ClassInfo, we have a problem: it cannot derive serialize.



_Code quote:_
```XML
// TODO(Mohammad): Add constructor for all the transaction's structs.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct DeclareTransaction {
    pub tx: crate::transaction::DeclareTransaction,
    pub tx_hash: TransactionHash,
    pub class_info: ClassInfo,
}
```

**Pull request merged**
