### PR TITLE
chore(starknet_batcher): set temp gas prices in propose block input

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2341#-:-OD0h2Yk3BIg1uKcwqwu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2341)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2341#-ODBOVZC8lzWQs8NQ_xa:-ODBOVZC8lzWQs8NQ_xb:bpt5l3c) ([raw file](https://github.com/starkware-libs/sequencer/blob/c2e4423fd9aa1cf981a5e90227c816507d186d5e/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L60)):*
> ```XML
> use tracing::{debug, debug_span, error, info, trace, warn, Instrument};
> 
> // TODO(Dan, Matan): Remove this once and replace with real gas prices.
> ```

Where will this info come from? When do we need to integrate this? Feel free to answer offline.

@dan-starkware @alonh5 



_Code quote:_
```XML
// TODO(Dan, Matan): Remove this once and replace with real gas prices.
```

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2341)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2341#-ODBOVZC8lzWQs8NQ_xa:-ODBR7r14GS-aN44NKAH:b-uzjq5g) ([raw file](https://github.com/starkware-libs/sequencer/blob/c2e4423fd9aa1cf981a5e90227c816507d186d5e/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L60)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Where will this info come from? When do we need to integrate this? Feel free to answer offline.

@dan-starkware @alonh5
</blockquote></details>

The L2 gas prices should be calculated according to 1559, which is in the next milestone at the end of the month.
Part of the calculation should already be implemented.
And the L1 gas prices should be retrieved from L1. Not for the next milestone AFAIK.

**Comment by ArniStarkware** [comment]
### Merge activity

* **Dec 3, 7:31 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2341).

**Pull request merged**
