### PR TITLE
feat(batcher): start height

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1041)

### CODE REVIEW

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1041)* status: all files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1041#-O81eKhs877ExV2mokDr:-O81eKhs877ExV2mokDs:bu71wfk) ([raw file](https://github.com/starkware-libs/sequencer/blob/acaad4556a912f590eb372660cbb588965149ba5/crates/batcher/src/proposal_manager.rs#L173)):*
> ```XML
>         if self.active_height.is_none() {
>             return Err(ProposalManagerError::NoActiveHeight);
>         }
> ```

I think the height of the proposal can be derived from the `ProposalID`.
Do we want to check that it matches the height we are working on? 
@matan-starkware 
___
*[`crates/batcher/src/proposal_manager_test.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1041#-O81gjarDZJgn4c__A-O:-O81gjarDZJgn4c__A-P:bk8pg8g) ([raw file](https://github.com/starkware-libs/sequencer/blob/acaad4556a912f590eb372660cbb588965149ba5/crates/batcher/src/proposal_manager_test.rs#L110)):*
> ```XML
>     let result = proposal_manager.start_height(height);
>     // Unfortunatelly ProposalManagerError doesn't implement PartialEq.
>     assert_eq!(format!("{:?}", result), format!("{:?}", expected_result));
> ```

Consider splitting to 2 tests: `start_height_success`, `start_height_failure`.
Then you could use `assert_matches!` to compare the errors.



_Code quote:_
```XML
    // Unfortunatelly ProposalManagerError doesn't implement PartialEq.
    assert_eq!(format!("{:?}", result), format!("{:?}", expected_result));
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1041)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/proposal_manager_test.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1041#-O81gjarDZJgn4c__A-O:-O85xnWn2XCa0hENd9g8:b1folf1) ([raw file](https://github.com/starkware-libs/sequencer/blob/acaad4556a912f590eb372660cbb588965149ba5/crates/batcher/src/proposal_manager_test.rs#L110)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Consider splitting to 2 tests: `start_height_success`, `start_height_failure`.
Then you could use `assert_matches!` to compare the errors.
</blockquote></details>

It will just check the variant of the error, not the content.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1041#-:-O8W2S4Y2aqcHblzZ-bD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1041)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 155 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1041#-O8alU443gV94V4JYpo1:-O8alU443gV94V4JYpo2:bufcztr) ([raw file](https://github.com/starkware-libs/sequencer/blob/317e6f63eeda3b049923ec503be242fe18af3622/crates/batcher/src/proposal_manager.rs#L155)):*
> ```XML
>             });
>         }
>         self.active_height = Some(height);
> ```

What are we doing if at this point there is an active proposal or non active proposals from previous height?

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1041)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 155 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1041#-O8alU443gV94V4JYpo1:-O8aocmG0V93tzOWAtPU:b-x40aln) ([raw file](https://github.com/starkware-libs/sequencer/blob/317e6f63eeda3b049923ec503be242fe18af3622/crates/batcher/src/proposal_manager.rs#L155)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What are we doing if at this point there is an active proposal or non active proposals from previous height?
</blockquote></details>

Shouldn't happen - active height will be `Some` and it is checked before reaching here

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1041)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware and @Yael-Starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 155 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1041#-O8alU443gV94V4JYpo1:-O8asLNxAd8Zr2EC_ZbJ:b3qxrbj) ([raw file](https://github.com/starkware-libs/sequencer/blob/317e6f63eeda3b049923ec503be242fe18af3622/crates/batcher/src/proposal_manager.rs#L155)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Shouldn't happen - active height will be `Some` and it is checked before reaching here
</blockquote></details>

Right. 
@matan-starkware pointed to me that there can be a scenario where the consensus get out of sync, then sync the state, and while we have an active proposal on an old height, we get a start_height with the new height. In that case we should first drop the active proposal.

Not critical for the upcoming milestone but we should keep this in mind (maybe add a todo)

**Review by Yael-Starkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1041)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @matan-starkware, and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1041#-O8bHth72ETQfq-RKYQN:-O8bHth72ETQfq-RKYQO:by3vsq3) ([raw file](https://github.com/starkware-libs/sequencer/blob/317e6f63eeda3b049923ec503be242fe18af3622/crates/batcher/src/batcher.rs#L64)):*
> ```XML
>                 unreachable!("Shouldn't happen here: {}", err)
>             }
>         })
> ```

This later moves into a function, right?
It is not so reader-friendly this way...



_Code quote:_
```XML
        self.proposal_manager.start_height(input.height).map_err(|err| match err {
            ProposalManagerError::AlreadyWorkingOnHeight { active_height, new_height } => {
                BatcherError::AlreadyWorkingOnHeight { active_height, new_height }
            }
            ProposalManagerError::HeightAlreadyPassed { storage_height, requested_height } => {
                BatcherError::HeightAlreadyPassed { storage_height, requested_height }
            }
            ProposalManagerError::StorageError(err) => {
                error!("{}", err);
                BatcherError::InternalError
            }
            ProposalManagerError::StorageNotSynced { storage_height, requested_height } => {
                error!("{}", err);
                BatcherError::StorageNotSynced { storage_height, requested_height }
            }
            ProposalManagerError::AlreadyGeneratingProposal { .. }
            | ProposalManagerError::MempoolError { .. }
            | ProposalManagerError::NoActiveHeight
            | ProposalManagerError::ProposalAlreadyExists { .. } => {
                unreachable!("Shouldn't happen here: {}", err)
            }
        })
```
___
*[`crates/batcher/src/proposal_manager.rs` line 155 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1041#-O8alU443gV94V4JYpo1:-O8amqQtCX6GPNq31v6U:b-rbqpxd) ([raw file](https://github.com/starkware-libs/sequencer/blob/317e6f63eeda3b049923ec503be242fe18af3622/crates/batcher/src/proposal_manager.rs#L155)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What are we doing if at this point there is an active proposal or non active proposals from previous height?
</blockquote></details>

I think we agreed in a meeting with @matan-starkware and @dan-starkware that this is the place to flush old heights' proposals.

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1041)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @matan-starkware, and @Yael-Starkware)

___
*[`crates/batcher/src/batcher.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1041#-O8bHth72ETQfq-RKYQN:-O8bTiuv7cKnZHZ5dyZX:b-khq8v4) ([raw file](https://github.com/starkware-libs/sequencer/blob/317e6f63eeda3b049923ec503be242fe18af3622/crates/batcher/src/batcher.rs#L64)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

This later moves into a function, right?
It is not so reader-friendly this way...
</blockquote></details>

Yes - https://github.com/starkware-libs/sequencer/pull/1105
___
*[`crates/batcher/src/proposal_manager.rs` line 155 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1041#-O8alU443gV94V4JYpo1:-O8bTsV6CSlraFbvJ6XE:bb85eig) ([raw file](https://github.com/starkware-libs/sequencer/blob/317e6f63eeda3b049923ec503be242fe18af3622/crates/batcher/src/proposal_manager.rs#L155)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think we agreed in a meeting with @matan-starkware and @dan-starkware that this is the place to flush old heights' proposals.
</blockquote></details>

Can it sync the state while the batcher is running?
Anyways, I don't mind clearing the proposals here

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1041)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @matan-starkware, and @Yael-Starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 155 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1041#-O8alU443gV94V4JYpo1:-O8k6oip9C24USKtXMRM:b-a8vm2p) ([raw file](https://github.com/starkware-libs/sequencer/blob/317e6f63eeda3b049923ec503be242fe18af3622/crates/batcher/src/proposal_manager.rs#L155)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can it sync the state while the batcher is running?
Anyways, I don't mind clearing the proposals here
</blockquote></details>

Yes, it can sync the state while the batcher is running. The batcher won't see the changes as long as it doesn't get a new state reader.
The scenario we should handle is when `next_height == height` and `active_height < next_height`. Can be done in another PR, just add a TODO now.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1041#-:-O8kBhSuB1qyTLIx2Sqs:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @matan-starkware, and @Yael-Starkware)

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1041)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @matan-starkware, and @Yael-Starkware)

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1041)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry, @dan-starkware, @matan-starkware, and @Yael-Starkware)

___
*[`crates/batcher/src/proposal_manager.rs` line 155 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1041#-O8alU443gV94V4JYpo1:-O8kA_ui5Gt-s-gV8IyZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/317e6f63eeda3b049923ec503be242fe18af3622/crates/batcher/src/proposal_manager.rs#L155)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Yes, it can sync the state while the batcher is running. The batcher won't see the changes as long as it doesn't get a new state reader.
The scenario we should handle is when `next_height == height` and `active_height < next_height`. Can be done in another PR, just add a TODO now.
</blockquote></details>

Done.

**Review by dafnamatsry — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1041)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @matan-starkware, and @Yael-Starkware)

**Pull request merged**
