### PR TITLE
chore: make the patricia_key and class_hash macros self contained

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1465?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1465** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1465?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1464** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1464?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1463** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1462** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1462?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1465)

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1465#-:-O9eLN7z8fOH_FOLEZKI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1465)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
