### PR TITLE
feat(batcher): stream tx outside on build_proposal

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1082)

### CODE REVIEW

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1082)* status: 1 of 8 files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O85zwuZ97FWwMVR-hEa:-O85zwuZ97FWwMVR-hEb:b-cuygg1) ([raw file](https://github.com/starkware-libs/sequencer/blob/a59aa3c81b595b53d9926ab15e2584a722e14d02/crates/batcher/src/batcher.rs#L119)):*
> ```XML
>         &mut self,
>         get_proposal_content_input: GetProposalContentInput,
>     ) -> BatcherResult<GetProposalContentResponse> {
> ```

The fact that we have the `get_ptoposal_content` endpoint is because of limitation of the component that don't support streams. I don't want this API to propagate down to the `ProposalManager`. 

If you keep the channel creation here in the `Batcher`, and you save the receiver, you could just directly read from it here, without adding extra logic to the `ProposalManger` (expect for maybe getters to get extra data about a proposal that is not streamed through the channel). 
___
*[`crates/batcher/src/proposal_manager.rs` line 276 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O85x6TY6ukuRCV4zenR:-O85x6TZAqoY9LgB69KP:bem7s43) ([raw file](https://github.com/starkware-libs/sequencer/blob/a59aa3c81b595b53d9926ab15e2584a722e14d02/crates/batcher/src/proposal_manager.rs#L276)):*
> ```XML
>     // TODO: Add stream.
>     #[allow(dead_code)]
>     ValidateProposal,
> ```

Why will they be different? the `BlockBuilder` has no distinction between validated and proposed blocks.



_Code quote:_
```XML
    BuildProposal(OutputStream),
    // TODO: Add stream.
    #[allow(dead_code)]
    ValidateProposal,
```
___
*[`crates/batcher_types/src/errors.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O861bIWExgT_8pPD8g0:-O861bIWExgT_8pPD8g1:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/a59aa3c81b595b53d9926ab15e2584a722e14d02/crates/batcher_types/src/errors.rs#L15)):*
> ```XML
>     AlreadyWorkingOnHeight { active_height: BlockNumber, new_height: BlockNumber },
>     #[error("Can't get content for proposal with ID {proposal_id} as it is not a build proposal.")]
>     GetContentOnNonBuildProposal { proposal_id: ProposalId },
> ```





_Suggestion:_
```XML
    #[error("Can't get content for proposal with ID {proposal_id}, as it is not proposed by this batcher.")]
    GetContentOnNonBuildProposal { proposal_id: ProposalId },
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1082)* status: 1 of 8 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/batcher.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O85zwuZ97FWwMVR-hEa:-O8WzxO23qOl9GWNakYM:b-f62uxj) ([raw file](https://github.com/starkware-libs/sequencer/blob/a59aa3c81b595b53d9926ab15e2584a722e14d02/crates/batcher/src/batcher.rs#L119)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

The fact that we have the `get_ptoposal_content` endpoint is because of limitation of the component that don't support streams. I don't want this API to propagate down to the `ProposalManager`. 

If you keep the channel creation here in the `Batcher`, and you save the receiver, you could just directly read from it here, without adding extra logic to the `ProposalManger` (expect for maybe getters to get extra data about a proposal that is not streamed through the channel).
</blockquote></details>

In `decision_reached` we need to drop the streams, it is logic that should be in the proposal manager IMO
___
*[`crates/batcher/src/proposal_manager.rs` line 276 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O85x6TY6ukuRCV4zenR:-O8WzTQ21xCA72Tq0y4c:bm06wuo) ([raw file](https://github.com/starkware-libs/sequencer/blob/a59aa3c81b595b53d9926ab15e2584a722e14d02/crates/batcher/src/proposal_manager.rs#L276)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why will they be different? the `BlockBuilder` has no distinction between validated and proposed blocks.
</blockquote></details>

It is to avoid situations where the consensus attempts to get the content of a validate_proposal 
___
*[`crates/batcher_types/src/errors.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O861bIWExgT_8pPD8g0:-O8WzCoM4GRom7AgkPrN:b-tabvu0) ([raw file](https://github.com/starkware-libs/sequencer/blob/a59aa3c81b595b53d9926ab15e2584a722e14d02/crates/batcher_types/src/errors.rs#L15)):*
> ```XML
>     AlreadyWorkingOnHeight { active_height: BlockNumber, new_height: BlockNumber },
>     #[error("Can't get content for proposal with ID {proposal_id} as it is not a build proposal.")]
>     GetContentOnNonBuildProposal { proposal_id: ProposalId },
> ```

See my previous comment

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1082)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O85zwuZ97FWwMVR-hEa:-O8_kmQhAKnJgDSw8C6m:bmk41q7) ([raw file](https://github.com/starkware-libs/sequencer/blob/a59aa3c81b595b53d9926ab15e2584a722e14d02/crates/batcher/src/batcher.rs#L119)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

In `decision_reached` we need to drop the streams, it is logic that should be in the proposal manager IMO
</blockquote></details>

We don't need to keep the streams of non active proposals.
The batcher can hold the stream of the active proposal being built, and drop it when it is done.
___
*[`crates/batcher/src/proposal_manager.rs` line 276 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O85x6TY6ukuRCV4zenR:-O8_miHy35vfX3stUzdF:bexdxn0) ([raw file](https://github.com/starkware-libs/sequencer/blob/a59aa3c81b595b53d9926ab15e2584a722e14d02/crates/batcher/src/proposal_manager.rs#L276)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

It is to avoid situations where the consensus attempts to get the content of a validate_proposal
</blockquote></details>

There should be no  streams in validate scenario, no?

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1082)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/batcher.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O85zwuZ97FWwMVR-hEa:-O8a2CfTBnXHkXJiEbYE:b-quxjwi) ([raw file](https://github.com/starkware-libs/sequencer/blob/a59aa3c81b595b53d9926ab15e2584a722e14d02/crates/batcher/src/batcher.rs#L119)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

We don't need to keep the streams of non active proposals.
The batcher can hold the stream of the active proposal being built, and drop it when it is done.
</blockquote></details>

We talked about making it possible to start a new proposal without consuming the active proposal
___
*[`crates/batcher/src/proposal_manager.rs` line 276 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O85x6TY6ukuRCV4zenR:-O8a2UCeCu1-IQwSt9Bf:bezjsv3) ([raw file](https://github.com/starkware-libs/sequencer/blob/a59aa3c81b595b53d9926ab15e2584a722e14d02/crates/batcher/src/proposal_manager.rs#L276)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

There should be no  streams in validate scenario, no?
</blockquote></details>

There is the stream of txs from consensus

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r4, 1 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1082)* status: 2 of 17 files reviewed, 6 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8kZz90EDEqxK902vfy:-O8kZz90EDEqxK902vfz:b-gtaqah) ([raw file](https://github.com/starkware-libs/sequencer/blob/757a45732a68cd6fe1fe9b5b1919d31bc69deeda/crates/batcher/src/batcher.rs#L39)):*
> ```XML
>     pub storage: Arc<dyn BatcherStorageReaderTrait>,
>     proposal_manager: Box<dyn ProposalManagerTrait>,
>     proposals: HashMap<ProposalId, Proposal>,
> ```

Should we keep all the proposals here?
I think we can get `GetProposalContent` requests only for the latest proposal that we proposed. So there should be only a single stream here at a time.

Worth checking it with Matan.



_Suggestion:_
```XML
proposed_block: (ProposalId, Proposal),
```
___
*[`crates/batcher/src/batcher.rs` line 178 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8kXqIZ3Bhk6p3S6xab:-O8kXqIZ3Bhk6p3S6xac:b-rb65g7) ([raw file](https://github.com/starkware-libs/sequencer/blob/757a45732a68cd6fe1fe9b5b1919d31bc69deeda/crates/batcher/src/batcher.rs#L178)):*
> ```XML
>     // TODO: Add stream.
>     #[allow(dead_code)]
>     ValidateProposal,
> ```

Still not sure, what will be the difference in the content of the stream between 
`BuildProposal` and `ValidateProposal`?
___
*[`crates/batcher/src/proposal_manager.rs` line 170 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8kVVnUDevv_kTr1-jm:-O8kVVnUDevv_kTr1-jn:b-u2715y) ([raw file](https://github.com/starkware-libs/sequencer/blob/9544273b57db3b2479be814b35e40839f73a2517/crates/batcher/src/proposal_manager.rs#L170)):*
> ```XML
>         if self.proposals.contains(&proposal_id) {
>             return Err(ProposalManagerError::ProposalAlreadyExists { proposal_id });
>         }
> ```

Why did you move this logic out to the batcher?
I only think the stream consuming logic should be in the batcher, but keep here the management of multiple proposals.



_Code quote:_
```XML
        if self.proposals.contains(&proposal_id) {
            return Err(ProposalManagerError::ProposalAlreadyExists { proposal_id });
        }
```
___
*[`crates/batcher/src/proposal_manager.rs` line 328 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8kWpU1ASO4u9nshf9N:-O8kWpU1ASO4u9nshf9O:btys7m6) ([raw file](https://github.com/starkware-libs/sequencer/blob/757a45732a68cd6fe1fe9b5b1919d31bc69deeda/crates/batcher/src/proposal_manager.rs#L328)):*
> ```XML
>         deadline: tokio::time::Instant,
>         tx_stream: InputTxStream,
>         output_content_sender: tokio::sync::mpsc::UnboundedSender<Transaction>,
> ```

Are we sure there can't be memory issues with this sender? From the documentation:
"Note that the amount of available system memory is an implicit bound to the channel. Using an `unbounded` channel has the ability of causing the process to run out of memory. In this case, the process will be aborted."



_Code quote:_
```XML
UnboundedSender
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1082)* status: 1 of 17 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/batcher.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8kZz90EDEqxK902vfy:-O8l10NB0_B57FyVUF74:buiyvp) ([raw file](https://github.com/starkware-libs/sequencer/blob/757a45732a68cd6fe1fe9b5b1919d31bc69deeda/crates/batcher/src/batcher.rs#L39)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Should we keep all the proposals here?
I think we can get `GetProposalContent` requests only for the latest proposal that we proposed. So there should be only a single stream here at a time.

Worth checking it with Matan.
</blockquote></details>

I will keep here also the state diff for the decision reached, so we still need all of them
___
*[`crates/batcher/src/batcher.rs` line 178 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8kXqIZ3Bhk6p3S6xab:-O8l1DPz84TxxMlzsiw7:b-q4vi6y) ([raw file](https://github.com/starkware-libs/sequencer/blob/757a45732a68cd6fe1fe9b5b1919d31bc69deeda/crates/batcher/src/batcher.rs#L178)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Still not sure, what will be the difference in the content of the stream between 
`BuildProposal` and `ValidateProposal`?
</blockquote></details>

They have different content types
___
*[`crates/batcher/src/proposal_manager.rs` line 328 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8kWpU1ASO4u9nshf9N:-O8l1XDv1UzMgzJHhu1n:bfez6h6) ([raw file](https://github.com/starkware-libs/sequencer/blob/757a45732a68cd6fe1fe9b5b1919d31bc69deeda/crates/batcher/src/proposal_manager.rs#L328)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Are we sure there can't be memory issues with this sender? From the documentation:
"Note that the amount of available system memory is an implicit bound to the channel. Using an `unbounded` channel has the ability of causing the process to run out of memory. In this case, the process will be aborted."
</blockquote></details>

Otherwise the block builder will be blocked and won't be able to execute more txs

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1082)* status: 2 of 17 files reviewed, 5 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8kZz90EDEqxK902vfy:-O8lpT4t76SMDy1PCPiQ:b6s62ml) ([raw file](https://github.com/starkware-libs/sequencer/blob/757a45732a68cd6fe1fe9b5b1919d31bc69deeda/crates/batcher/src/batcher.rs#L39)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I will keep here also the state diff for the decision reached, so we still need all of them
</blockquote></details>

Please keep the state diff (and other proposal related data) in the proposal manager (otherwise, what's the point of having it if not to manage the existing proposals?)

We need to keep only the steam here, and that's solely because we don't have stream support in the component abstraction.
___
*[`crates/batcher/src/batcher.rs` line 178 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8kXqIZ3Bhk6p3S6xab:-O8lqc98A6KjCKjkHSHO:b-ppaexg) ([raw file](https://github.com/starkware-libs/sequencer/blob/757a45732a68cd6fe1fe9b5b1919d31bc69deeda/crates/batcher/src/batcher.rs#L178)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

They have different content types
</blockquote></details>

It will be only transactions in both. What else is going to be in `ValidateProposal`?
Any initialisation data etc, can be passed to the proposal manager as function arguments.
___
*[`crates/batcher/src/proposal_manager.rs` line 328 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8kWpU1ASO4u9nshf9N:-O8lpH1f9F3e0h1Skr0f:bjre9wo) ([raw file](https://github.com/starkware-libs/sequencer/blob/757a45732a68cd6fe1fe9b5b1919d31bc69deeda/crates/batcher/src/proposal_manager.rs#L328)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Otherwise the block builder will be blocked and won't be able to execute more txs
</blockquote></details>

Why would it be blocked? The size of the stream can be large, but unbounded sounds risky.
___
*[`crates/batcher_types/src/errors.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O861bIWExgT_8pPD8g0:-O8lrPRZ9IQf9Fw0Yq1m:buem3u4) ([raw file](https://github.com/starkware-libs/sequencer/blob/a59aa3c81b595b53d9926ab15e2584a722e14d02/crates/batcher_types/src/errors.rs#L15)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

See my previous comment
</blockquote></details>

Just the term build proposal is not clear enough I think. Maybe "..., as it was not built by calling the BuildProposal API."

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1082)* status: 2 of 17 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/batcher.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8kZz90EDEqxK902vfy:-O8pGV2m9idYWDiUYYvv:bc2bdu2) ([raw file](https://github.com/starkware-libs/sequencer/blob/757a45732a68cd6fe1fe9b5b1919d31bc69deeda/crates/batcher/src/batcher.rs#L39)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please keep the state diff (and other proposal related data) in the proposal manager (otherwise, what's the point of having it if not to manage the existing proposals?)

We need to keep only the steam here, and that's solely because we don't have stream support in the component abstraction.
</blockquote></details>

talked f2f
___
*[`crates/batcher/src/batcher.rs` line 178 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8kXqIZ3Bhk6p3S6xab:-O8pH3hj7uONs-Zbl7hd:b-g94u6v) ([raw file](https://github.com/starkware-libs/sequencer/blob/757a45732a68cd6fe1fe9b5b1919d31bc69deeda/crates/batcher/src/batcher.rs#L178)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

It will be only transactions in both. What else is going to be in `ValidateProposal`?
Any initialisation data etc, can be passed to the proposal manager as function arguments.
</blockquote></details>

In validate there's also finish/abort
___
*[`crates/batcher/src/proposal_manager.rs` line 170 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8kVVnUDevv_kTr1-jm:-O8pKl3s1W3fUbqyko-G:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9544273b57db3b2479be814b35e40839f73a2517/crates/batcher/src/proposal_manager.rs#L170)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why did you move this logic out to the batcher?
I only think the stream consuming logic should be in the batcher, but keep here the management of multiple proposals.
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 328 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8kWpU1ASO4u9nshf9N:-O8pHI_a28OmILSG-XuL:b-w4zpz1) ([raw file](https://github.com/starkware-libs/sequencer/blob/757a45732a68cd6fe1fe9b5b1919d31bc69deeda/crates/batcher/src/proposal_manager.rs#L328)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why would it be blocked? The size of the stream can be large, but unbounded sounds risky.
</blockquote></details>

Will work on it in another PR - it makes the tests harder
___
*[`crates/batcher_types/src/errors.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O861bIWExgT_8pPD8g0:-O8pISSD763axGvtgM2x:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a59aa3c81b595b53d9926ab15e2584a722e14d02/crates/batcher_types/src/errors.rs#L15)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Just the term build proposal is not clear enough I think. Maybe "..., as it was not built by calling the BuildProposal API."
</blockquote></details>

Done.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 11 files at r4, 6 of 12 files at r5, 1 of 2 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1082)* status: 14 of 17 files reviewed, 8 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 178 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8kXqIZ3Bhk6p3S6xab:-O8ptCiZ92e7c1hQoEZy:bpr6jce) ([raw file](https://github.com/starkware-libs/sequencer/blob/757a45732a68cd6fe1fe9b5b1919d31bc69deeda/crates/batcher/src/batcher.rs#L178)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

In validate there's also finish/abort
</blockquote></details>

Not sure this is the right place to make the distinction. For example, we might want to do the separation by holding 2 different lists (`build_proposals` and `validate_proposals`).
Let's add it when we have validate proposals.
___
*[`crates/batcher/src/batcher.rs` line 156 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8puFL_ESNLNaiKAs5z:-O8puFL_ESNLNaiKAs6-:bu3nqvu) ([raw file](https://github.com/starkware-libs/sequencer/blob/536b35b6a94de4b7ffc426a820c03785f2232722/crates/batcher/src/batcher.rs#L156)):*
> ```XML
> 
>         let ProposalContentStream::BuildProposal(stream) = &mut proposal.content_stream else {
>             return Err(BatcherError::GetContentOnNonBuildProposal { proposal_id });
> ```

I assumed `proposals` only holds build proposals.
___
*[`crates/batcher/src/batcher_test.rs` line 55 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8pw_J3-9L4zp8jaB6b:-O8pw_J3-9L4zp8jaB6c:b-gup3im) ([raw file](https://github.com/starkware-libs/sequencer/blob/536b35b6a94de4b7ffc426a820c03785f2232722/crates/batcher/src/batcher_test.rs#L55)):*
> ```XML
> 
>     let mut proposal_manager = MockProposalManagerTraitWrapper::new();
>     proposal_manager.expect_wrap_start_height().with(eq(INITIAL_HEIGHT)).return_once(|_| Ok(()));
> ```

I don't think we should test `build_proposal` logic here.



_Suggestion:_
```XML
proposal_manager.expect_wrap_start_height().return_once(|_| Ok(()));
```
___
*[`crates/batcher/src/batcher_test.rs` line 62 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8pwhvR9ENgoUcNLqQC:-O8pwhvR9ENgoUcNLqQD:b-816h6l) ([raw file](https://github.com/starkware-libs/sequencer/blob/536b35b6a94de4b7ffc426a820c03785f2232722/crates/batcher/src/batcher_test.rs#L62)):*
> ```XML
>         .return_once(move |_proposal_id, _block_hash, _deadline, tx_sender| {
>             simulate_build_block_proposal(tx_sender, txs_to_stream).boxed()
>         });
> ```

Same.



_Suggestion:_
```XML
    proposal_manager
        .expect_wrap_build_block_proposal()
        .return_once(move |_proposal_id, _block_hash, _deadline, tx_sender| {
            simulate_build_block_proposal(tx_sender, txs_to_stream).boxed()
        });
```
___
*[`crates/batcher/src/batcher_test.rs` line 102 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8pyBei-aAbqD3M3dpL:-O8pyBei-aAbqD3M3dpM:b-mkoeqm) ([raw file](https://github.com/starkware-libs/sequencer/blob/536b35b6a94de4b7ffc426a820c03785f2232722/crates/batcher/src/batcher_test.rs#L102)):*
> ```XML
>     txs: Vec<Transaction>,
> ) -> ProposalManagerResult<()> {
>     for tx in txs {
> ```

Maybe we should put it inside `spawn` to simulate a more real scenario where we consume txs from this channel whole they are inserted.
___
*[`crates/batcher/src/batcher_test.rs` line 105 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8pxitP25q3-C6K3AVJ:-O8pxitP25q3-C6K3AVK:bf6vmec) ([raw file](https://github.com/starkware-libs/sequencer/blob/536b35b6a94de4b7ffc426a820c03785f2232722/crates/batcher/src/batcher_test.rs#L105)):*
> ```XML
>         tx_sender.send(tx).unwrap();
>     }
>     drop(tx_sender);
> ```

Are you sure it is needed? The `tx_sender` goes out of scope at the end of this function.



_Code quote:_
```XML
drop(tx_sender);
```
___
*[`crates/batcher/src/proposal_manager.rs` line 133 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8pyY_62rNZRa5kGEhe:-O8pyY_7DWElu-IzEQ88:bb7r2f0) ([raw file](https://github.com/starkware-libs/sequencer/blob/536b35b6a94de4b7ffc426a820c03785f2232722/crates/batcher/src/proposal_manager.rs#L133)):*
> ```XML
>     #[instrument(skip(self), err)]
>     fn start_height(&mut self, height: BlockNumber) -> ProposalManagerResult<()> {
>         // TODO: instead of returning an error, abort the current height.
> ```

why?



_Code quote:_
```XML
abort the current height.
```
___
*[`crates/batcher/src/proposal_manager_test.rs` line 172 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8q-4BS0j49i6myb5-V:-O8q-4BS0j49i6myb5-W:b1ojpco) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b5a1762b8ea74e142b9aa34b661485e767e92c5/crates/batcher/src/proposal_manager_test.rs#L172)):*
> ```XML
>     assert_matches!(proposal_manager.await_active_proposal().await, Some(Ok(())));
>     let proposal_content: Vec<_> = stream.collect().await;
>     assert_eq!(proposal_content, test_txs(0..n_txs));
> ```

Why did we remove this check? (here and below)



_Code quote:_
```XML
    let proposal_content: Vec<_> = stream.collect().await;
    assert_eq!(proposal_content, test_txs(0..n_txs));
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1082)* status: 8 of 17 files reviewed, 8 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/batcher.rs` line 178 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8kXqIZ3Bhk6p3S6xab:-O8qcBhXCuy3LJWL48uL:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/757a45732a68cd6fe1fe9b5b1919d31bc69deeda/crates/batcher/src/batcher.rs#L178)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Not sure this is the right place to make the distinction. For example, we might want to do the separation by holding 2 different lists (`build_proposals` and `validate_proposals`).
Let's add it when we have validate proposals.
</blockquote></details>

Done.
___
*[`crates/batcher/src/batcher.rs` line 156 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8puFL_ESNLNaiKAs5z:-O8qbbF0EYx2IGTvHVNA:b-ew33g) ([raw file](https://github.com/starkware-libs/sequencer/blob/536b35b6a94de4b7ffc426a820c03785f2232722/crates/batcher/src/batcher.rs#L156)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I assumed `proposals` only holds build proposals.
</blockquote></details>

Removed the check
___
*[`crates/batcher/src/batcher_test.rs` line 55 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8pw_J3-9L4zp8jaB6b:-O8qcSRU9C73-Z5lHozD:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/536b35b6a94de4b7ffc426a820c03785f2232722/crates/batcher/src/batcher_test.rs#L55)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I don't think we should test `build_proposal` logic here.
</blockquote></details>

Done.
___
*[`crates/batcher/src/batcher_test.rs` line 62 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8pwhvR9ENgoUcNLqQC:-O8qcYRz0zAaBrYveI5Q:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/536b35b6a94de4b7ffc426a820c03785f2232722/crates/batcher/src/batcher_test.rs#L62)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Same.
</blockquote></details>

Done.
___
*[`crates/batcher/src/batcher_test.rs` line 102 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8pyBei-aAbqD3M3dpL:-O8qeoYa59QCWYn0wlWF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/536b35b6a94de4b7ffc426a820c03785f2232722/crates/batcher/src/batcher_test.rs#L102)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Maybe we should put it inside `spawn` to simulate a more real scenario where we consume txs from this channel whole they are inserted.
</blockquote></details>

Done.
___
*[`crates/batcher/src/batcher_test.rs` line 105 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8pxitP25q3-C6K3AVJ:-O8qdUdC6ouVOYqvkZde:ba3dfob) ([raw file](https://github.com/starkware-libs/sequencer/blob/536b35b6a94de4b7ffc426a820c03785f2232722/crates/batcher/src/batcher_test.rs#L105)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Are you sure it is needed? The `tx_sender` goes out of scope at the end of this function.
</blockquote></details>

Removed
___
*[`crates/batcher/src/proposal_manager.rs` line 133 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8pyY_62rNZRa5kGEhe:-O8qeIo970p_409ytU-q:b5xyrd6) ([raw file](https://github.com/starkware-libs/sequencer/blob/536b35b6a94de4b7ffc426a820c03785f2232722/crates/batcher/src/proposal_manager.rs#L133)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

why?
</blockquote></details>

Talked about it with the consensus guys - it should be valid to call `start_height` multiple times for cases where the consensus restarts
___
*[`crates/batcher/src/proposal_manager_test.rs` line 172 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8q-4BS0j49i6myb5-V:-O8qecCl-s8O8eUaZ3WK:b-fclk69) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b5a1762b8ea74e142b9aa34b661485e767e92c5/crates/batcher/src/proposal_manager_test.rs#L172)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why did we remove this check? (here and below)
</blockquote></details>

It is being checked in the get_proposal_content

**Comment by yair-starkware** [comment]
*[`crates/batcher/src/proposal_manager_test.rs` line 172 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1082#-O8q-4BS0j49i6myb5-V:-O93xs2G09nuwutLMgkc:bc6i28w) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b5a1762b8ea74e142b9aa34b661485e767e92c5/crates/batcher/src/proposal_manager_test.rs#L172)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

In that case, is there a point in keeping the `simulate_build_block` above?
(Non blocking).
</blockquote></details>

I will clean the code in a separate PR

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 1 of 11 files at r4, 2 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1082)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
