### PR TITLE
feat(starknet_class_manager_types): add crate

### PR DESCRIPTION
**Pull request by elintul**

### CODE REVIEW

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2713#-:-OENuK749sZ1mtAn8Dm_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/starknet_class_manager_types/src/lib.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2713#-OENu54W07az08XdpeQo:-OENu54W07az08XdpeQp:br8z1qz) ([raw file](https://github.com/starkware-libs/sequencer/blob/7380df7f937c734ca94498af49ac4ebea0575e50/crates/starknet_class_manager_types/src/lib.rs#L11)):*
> ```XML
> use thiserror::Error;
> 
> pub type ClassManagerResult<T> = Result<T, ClassManagerError>;
> ```

:tophat: :tipping_hand_man: 



_Code quote:_
```XML
ClassManager
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2713)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/starknet_class_manager_types/src/lib.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2713#-OENu54W07az08XdpeQo:-OENwoKiEGmMvgw8uYyk:bgc7vqv) ([raw file](https://github.com/starkware-libs/sequencer/blob/7380df7f937c734ca94498af49ac4ebea0575e50/crates/starknet_class_manager_types/src/lib.rs#L11)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

:tophat: :tipping_hand_man:
</blockquote></details>

:heart:

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2713)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2713)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
