### PR TITLE
test(batcher): mock ProposalsManager to test the batcher

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/568)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
*[`crates/batcher/src/proposals_manager_test.rs` line 131 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/568#-O5N7pVD8CjuyObmJsWv:-O5N7pVD8CjuyObmJsWw:b5zcy86) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f66e6e0812bd85bc1ae7894aeb37a20dff19b7e/crates/batcher/src/proposals_manager_test.rs#L131)):*
> ```XML
>     let Err(err) = another_generate_request else {
>         panic!("Expected an error, got Ok");
>     };
> ```

Why not?
(It can even be squashed back into the assert matches.)

For me to learn - why was this unwrap needed?



_Suggestion:_
```XML
    let err = another_generate_request.unwrap_err();
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/568)* status: 1 of 14 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @yair-starkware)

**Comment by yair-starkware** [comment]
*[`crates/batcher/src/proposals_manager_test.rs` line 131 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/568#-O5N7pVD8CjuyObmJsWv:-O5hoyHG9NSG1W-WdRkX:bc3s4bp) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f66e6e0812bd85bc1ae7894aeb37a20dff19b7e/crates/batcher/src/proposals_manager_test.rs#L131)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Why not?
(It can even be squashed back into the assert matches.)

For me to learn - why was this unwrap needed?
</blockquote></details>

it will have the same effect - if that's not an error then the code will panic and the test will fail.

**Comment by ArniStarkware** [comment]
*[`crates/batcher/src/proposals_manager_test.rs` line 131 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/568#-O5N7pVD8CjuyObmJsWv:-O5mZhYP4ROW2UlXwu3U:b-2vpqn1) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f66e6e0812bd85bc1ae7894aeb37a20dff19b7e/crates/batcher/src/proposals_manager_test.rs#L131)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

it will have the same effect - if that's not an error then the code will panic and the test will fail.
</blockquote></details>

In that case - why should I treat this unexpected flow any differently than other unexpected flows?
What I am saying is that `panic` here is overkill.

**Review by Yael-Starkware — COMMENTED** [review]
I think that some of the code is duplicate with PR: https://reviewable.io/reviews/starkware-libs/sequencer/541

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/568#-:-O5rt2VfAj6x7INQ3QNY:b-myfalz)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/568)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/batcher/src/proposals_manager_test.rs` line 131 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/568#-O5N7pVD8CjuyObmJsWv:-O6GLA-FDQEdpLvzAPO5:bto1jkp) ([raw file](https://github.com/starkware-libs/sequencer/blob/6f66e6e0812bd85bc1ae7894aeb37a20dff19b7e/crates/batcher/src/proposals_manager_test.rs#L131)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

In that case - why should I treat this unexpected flow any differently than other unexpected flows?
What I am saying is that `panic` here is overkill.
</blockquote></details>

Oh the problem here is that the Ok return types don't implement Debug which is required for `unwrap_err`
___
*[`crates/batcher/src/proposals_manager_test.rs` line 159 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/568#-O5m_5nIAzDsCQUvesyM:-O6GLSTdEz1vnBVcKRoq:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/b5cd7f3f7661d00e81501233806c346b6ab89c0f/crates/batcher/src/proposals_manager_test.rs#L159)):*
> ```XML
>             new_proposal_id
>         } if current_generating_proposal_id == 0 && new_proposal_id == 1
>     );
> ```

same

**Comment by yair-starkware** [comment]
Closing because I think it's a mistake to mock the proposal manager in this context

**Pull request closed without merging**
