### PR TITLE
chore(cairo_native): add git submodule update as a post-checkout hook

### PR DESCRIPTION
**Pull request by avi-starkware**

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2166)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

___
*[`scripts/add_sumodule_hook.sh` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2166#-OC2saGkDDDjkSZ2zvkt:-OC2saGl7hz06NulO_DR:bna65er) ([raw file](https://github.com/starkware-libs/sequencer/blob/941b1c2b864e4329087f8b51afe7715e70db007b/scripts/add_sumodule_hook.sh#L9)):*
> ```Shell
>     HOOK_CONTENT="git submodule update --init --recursive"
> 
>     # Ensure the hooks directory exists
> ```

How does this script work? Do we have to run it, or is it part of the Build?

**Comment by avi-starkware** [comment]
*[`scripts/add_sumodule_hook.sh` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2166#-OC2saGkDDDjkSZ2zvkt:-OC2syf51oc8fmxbVM0P:bsheti) ([raw file](https://github.com/starkware-libs/sequencer/blob/941b1c2b864e4329087f8b51afe7715e70db007b/scripts/add_sumodule_hook.sh#L9)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

How does this script work? Do we have to run it, or is it part of the Build?
</blockquote></details>

You run it once, and it adds the hook to your local `.git` folder.
Then you don't need to update the git submodule every time you checkout a commit.
(It will update them automatically with the hook.)

**Comment by avi-starkware** [comment]
*[`scripts/add_sumodule_hook.sh` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2166#-OC2saGkDDDjkSZ2zvkt:-OC2uRX_-8XmCuiKyExe:b-97pzku) ([raw file](https://github.com/starkware-libs/sequencer/blob/941b1c2b864e4329087f8b51afe7715e70db007b/scripts/add_sumodule_hook.sh#L9)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

You run it once, and it adds the hook to your local `.git` folder.
Then you don't need to update the git submodule every time you checkout a commit.
(It will update them automatically with the hook.)
</blockquote></details>

I can add another script for safely removing the hook if you think that would be helpful

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2166)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @noaov1, and @Yoni-Starkware)

___
*[`scripts/add_sumodule_hook.sh` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2166#-OC2saGkDDDjkSZ2zvkt:-OC2v89M9glCCBidNsld:b1l0mpc) ([raw file](https://github.com/starkware-libs/sequencer/blob/941b1c2b864e4329087f8b51afe7715e70db007b/scripts/add_sumodule_hook.sh#L9)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I can add another script for safely removing the hook if you think that would be helpful
</blockquote></details>

I think that would be good. Running once is also great.

**Comment by avi-starkware** [comment]
*[`scripts/add_sumodule_hook.sh` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2166#-OC2saGkDDDjkSZ2zvkt:-OC2z5dzCZhqCg_1PB8H:b-w3meg0) ([raw file](https://github.com/starkware-libs/sequencer/blob/941b1c2b864e4329087f8b51afe7715e70db007b/scripts/add_sumodule_hook.sh#L9)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I think that would be good. Running once is also great.
</blockquote></details>

Added a removal function and a help message

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2166)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Comment by avi-starkware** [comment]
Actually, there might be a better solution:
```
git config --global submodule.recurse true
```
ensures that all submodules are automatically updated whenever you run commands like `git checkout` or `git pull`.

**Pull request closed without merging**
