### PR TITLE
refactor(mempool): call deploy_account_tx_args from StarknetAPI

### PR DESCRIPTION
**Pull request by noam-starkware**
Similar PR to [this one](https://github.com/starkware-libs/sequencer/pull/1371), dealing with the `deploy_account_tx_args` macro.

### CODE REVIEW

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1529)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @MohammadNassar1, and @noam-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1529#-O9pNXdi4e4QGjNBJt24:-O9pNXdj7X_Ublsp1vSv:bk37cq4) ([raw file](https://github.com/starkware-libs/sequencer/blob/d68510dcb344dc3ecaa674c9d3abd61251075a1d/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L195)):*
> ```XML
>     let deploy_account_args = deploy_account_tx_args!(
>         class_hash: account.get_class_hash(),
>         resource_bounds: ValidResourceBounds::AllResources(test_resource_bounds_mapping()),
> ```

You can call this instead



_Code snippet:_
```XML
pub fn test_valid_resource_bounds() -> ValidResourceBounds {
    ValidResourceBounds::AllResources(test_resource_bounds_mapping())
}
```

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1529#-:-O9sqBwkAo6eeNQfrGFq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @noam-starkware)

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1529)* status: all files reviewed, 2 unresolved discussions (waiting on @noam-starkware and @noamsp-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1529#-O9pNXdi4e4QGjNBJt24:-O9xSG3d5eH7CZH42ig0:b-2iddbu) ([raw file](https://github.com/starkware-libs/sequencer/blob/d68510dcb344dc3ecaa674c9d3abd61251075a1d/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L195)):*
<details><summary><i>Previously, noamsp-starkware wrote…</i></summary><blockquote>

You can call this instead
</blockquote></details>

Correct. replace in `invoke_tx_args!` as well. 
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 479 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1529#-O9xTT2Y2WvztZhznrM4:-O9xTT2Y2WvztZhznrM5:b94dnyg) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab16d8c4a0309f58e1f428efc2d4945d7a30d96a/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L479)):*
> ```XML
>             signature: TransactionSignature::default(),
>             version: TransactionVersion::THREE,
>             resource_bounds: zero_resource_bounds_mapping(),
> ```

I see that `StarknetAPI`'s resource bounds default uses create for testing func, which has different values than zeros. Should make sure it doesn't make a difference. 



_Code quote:_
```XML
zero_resource_bounds_mapping()
```

**Review by noam-starkware — COMMENTED** [review]
> Dismissed @ayeletstarkware and @noamsp-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1529)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1529#-O9pNXdi4e4QGjNBJt24:-OAMRdzi2k1OWEMiqBNK:bmfxpif) ([raw file](https://github.com/starkware-libs/sequencer/blob/d68510dcb344dc3ecaa674c9d3abd61251075a1d/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L195)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Correct. replace in `invoke_tx_args!` as well.
</blockquote></details>

Done.
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 479 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1529#-O9xTT2Y2WvztZhznrM4:-OAMRpFYDBm7M2hxELsw:b-bbny8n) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab16d8c4a0309f58e1f428efc2d4945d7a30d96a/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L479)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I see that `StarknetAPI`'s resource bounds default uses create for testing func, which has different values than zeros. Should make sure it doesn't make a difference.
</blockquote></details>

This will wait for a separate PR to figure out the differences between the two options and which one fits our usage.

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1529#-:-OAMiJe-4juRcixTSApH:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noam-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 479 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1529#-O9xTT2Y2WvztZhznrM4:-OAMhpoB-8qZ1S-ei_6K:bmjsk0w) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab16d8c4a0309f58e1f428efc2d4945d7a30d96a/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L479)):*
<details><summary><i>Previously, noam-starkware wrote…</i></summary><blockquote>

This will wait for a separate PR to figure out the differences between the two options and which one fits our usage.
</blockquote></details>

discussed offline: we don't use this`DeployAccountTxArgs`'s `resource_bounds` 's default. so it does not matter.

**Review by ayeletstarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1529)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noam-starkware)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1529)* status: all files reviewed, 1 unresolved discussion (waiting on @noam-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1529#-OAMqH4C8rOQG-_N2ylq:-OAMqH4C8rOQG-_N2ylr:besl9zp) ([raw file](https://github.com/starkware-libs/sequencer/blob/4acd57bb643327fcf21e32c45a5a6fb5f49dfda9/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L174)):*
> ```XML
> 
>     rpc_invoke_tx(invoke_tx_args!(
>         resource_bounds: test_valid_resource_bounds(),
> ```

Is this equivalent to the previous invocation?



_Code quote:_
```XML
test_valid_resource_bounds()
```

**Review by noam-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1529)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1529#-OAMqH4C8rOQG-_N2ylq:-OAMuH6E8CsN3BcS8UZS:bnztfmf) ([raw file](https://github.com/starkware-libs/sequencer/blob/4acd57bb643327fcf21e32c45a5a6fb5f49dfda9/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L174)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this equivalent to the previous invocation?
</blockquote></details>

Yes, it's simply a refactored call.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1529)* status: all files reviewed, 1 unresolved discussion (waiting on @noam-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1529#-OAMqH4C8rOQG-_N2ylq:-OAMweXn2v2jSMOhOC5U:b-bpn2i) ([raw file](https://github.com/starkware-libs/sequencer/blob/4acd57bb643327fcf21e32c45a5a6fb5f49dfda9/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L174)):*
<details><summary><i>Previously, noam-starkware wrote…</i></summary><blockquote>

Yes, it's simply a refactored call.
</blockquote></details>

Okay, note this is information that should be hinted to the reviewer of the PR, so they won't have to look for it in the code (if possible).
Please make sure all those invocations: `ValidResourceBounds::AllResources(test_resource_bounds_mapping())` are replaced with `test_valid_resource_bounds` (throughout the codebase).

**Review by noam-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1529)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1529#-OAMqH4C8rOQG-_N2ylq:-OAMyG-l5Mo_O6mNCG1m:bugc6o1) ([raw file](https://github.com/starkware-libs/sequencer/blob/4acd57bb643327fcf21e32c45a5a6fb5f49dfda9/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L174)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Okay, note this is information that should be hinted to the reviewer of the PR, so they won't have to look for it in the code (if possible).
Please make sure all those invocations: `ValidResourceBounds::AllResources(test_resource_bounds_mapping())` are replaced with `test_valid_resource_bounds` (throughout the codebase).
</blockquote></details>

1. Verified there are no other invocations in the codebase.
2. The change was due to Noam S's suggestion in the PR. What is the proper way to hint to it in such a case?

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1529#-:-OANGMGp-2WqN6yoNABh:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noam-starkware)

___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 174 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1529#-OAMqH4C8rOQG-_N2ylq:-OANGHry5KHqUm3jFwA7:bl3dx4o) ([raw file](https://github.com/starkware-libs/sequencer/blob/4acd57bb643327fcf21e32c45a5a6fb5f49dfda9/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L174)):*
<details><summary><i>Previously, noam-starkware wrote…</i></summary><blockquote>

1. Verified there are no other invocations in the codebase.
2. The change was due to Noam S's suggestion in the PR. What is the proper way to hint to it in such a case?
</blockquote></details>

Write a comment here to let the reviewer know. :)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1529)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noam-starkware)

**Pull request merged**
