### PR TITLE
refactor(blockifier): use sierra version in native blockifier

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2809?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2809** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2809?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2809?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2752** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2752?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2680** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2680?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2681](https://github.com/starkware-libs/sequencer/pull/2681) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2681?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2679** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2679?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2678** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2678?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2668** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2668?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2641](https://github.com/starkware-libs/sequencer/pull/2641) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2641?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2614** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2614?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2493** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2493?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2438** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2438?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2420** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2420?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2421](https://github.com/starkware-libs/sequencer/pull/2421) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2421?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2467** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2467?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2466** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2466?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by AvivYossef-starkware — COMMENTED** [review]
Need to add python PR

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2809#-:-OET8pJ7Am_NWtrX1uRG:b-29xyu1)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2809)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2809#-OETF7sp1GwXfmnIbpiL:-OETF7sp1GwXfmnIbpiM:bt8wd8v) (no related file):*
blocking, pending python PR
___
*[`crates/blockifier/src/execution/contract_class.rs` line 311 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2809#-OETEdWs9VokB5HbxHVA:-OETEdWs9VokB5HbxHVB:b67d0nv) ([raw file](https://github.com/starkware-libs/sequencer/blob/18c18b1b86bc9e48294a9565bc4a0ee48883a23b/crates/blockifier/src/execution/contract_class.rs#L311)):*
> ```XML
> 
>     pub fn try_from_json_string(
>         (raw_contract_class, sierra_version): (&str, SierraVersion),
> ```

why tuple and not two params? non-blocking



_Suggestion:_
```XML
 raw_contract_class: &str, sierra_version: SierraVersion
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2809)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2809#-OETF7sp1GwXfmnIbpiL:-OETFM3x7HNvPRDhis7p:b-d9iwu5) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

blocking, pending python PR
</blockquote></details>

[python pr](https://github.com/starkware-industries/starkware/pull/36481)
___
*[`crates/blockifier/src/execution/contract_class.rs` line 311 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2809#-OETEdWs9VokB5HbxHVA:-OETFTM7-Tkytokift1V:bruhcc4) ([raw file](https://github.com/starkware-libs/sequencer/blob/18c18b1b86bc9e48294a9565bc4a0ee48883a23b/crates/blockifier/src/execution/contract_class.rs#L311)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why tuple and not two params? non-blocking
</blockquote></details>

Its a good question  
lol

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2809)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2809)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
