### PR TITLE
build(blockifier_reexecution): add preprocess before execute txs

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1821?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1821** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1821?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1797** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1797?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1796** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1796?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1765** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1765?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1759** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1759?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1758** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1758?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1712** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1712?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1821)* status: all files reviewed, 5 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1821#-OAwWPNy-IQ5QB_fQECQ:-OAwhfi99itQIoczGyTi:b2nhswy) ([raw file](https://github.com/starkware-libs/sequencer/blob/0492ef5ee3abfc7f92ca0fa2f40c2e6cc838f2cf/crates/blockifier_reexecution/src/main.rs#L91)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this change was tested manually?
</blockquote></details>

Yes
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 398 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1821#-OAwWF8n0SQSwGOw-vHx:-OAwidVK0So1sKverZxv:b-6wdus0) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4fa9a8a5fbd8d378bd9021b646f7f565e988353/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L398)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is the smallest query that includes the block hash?
</blockquote></details>

There is a request called `starknet_blockHashAndNumber`, which returns the block hash and number associated with the current block number of the state reader. This means that if I want to use it, I need to create a new state reader with the current block number. Do you prefer this approach?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1821)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 398 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1821#-OAwWF8n0SQSwGOw-vHx:-OB-ro6d3K89kmthPOPX:b-c4cjlz) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4fa9a8a5fbd8d378bd9021b646f7f565e988353/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L398)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

There is a request called `starknet_blockHashAndNumber`, which returns the block hash and number associated with the current block number of the state reader. This means that if I want to use it, I need to create a new state reader with the current block number. Do you prefer this approach?
</blockquote></details>

since this query happens once per block - I would keep it as-is for simplicity

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1821)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1821)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1821#-OAwWYU3-Kz2HbhX7KI2:-OB0lcf09OGfC6MatpRc:b-2zf5jm) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4fa9a8a5fbd8d378bd9021b646f7f565e988353/crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs#L79)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this API is more generic: given a block number, you get it's data
</blockquote></details>

It's in the trait `ReexecutionStateReader,` and since you don't need to know the block hash of the current state to run the execution test, that makes more sense to me.
___
*[`crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1821#-OAwWf7YD4qc8Y5WUs2H:-OB0oIVy7nX1qTby-2ub:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4fa9a8a5fbd8d378bd9021b646f7f565e988353/crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs#L79)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why return the input parameter? you just need the block hash here; the caller should construct the object if it needs it
</blockquote></details>

Done
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 539 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1821#-OAwVN6W1dnXb9xD2bSy:-OB0oF2bB-5kiIKYh4g8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c4fa9a8a5fbd8d378bd9021b646f7f565e988353/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L539)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this implies it *should* be implemented :)
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1821#-:-OB0zd527JQaPRaYJYP9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Comment by AvivYossef-starkware** [comment]
### Merge activity

* **Nov 6, 10:34 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1821).

**Pull request merged**
