### PR TITLE
fix(blockifier_reexecution): bug in get storage at

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1698?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1698** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1698?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1658** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1658?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1604** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1604?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1698)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1698#-OAY-Fj16teZ-QV5VpUA:-OAY9WQGAN8QLbwgeTmL:b-otqfhy) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d20b7f0e639301ef1b1584ec25be48da077e4c4/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L59)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this isn't a bug in rpc state reader?
</blockquote></details>

 My guess is that the gateway group is using papyrus. So they just receive 0 instead of an error when doing this request

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1698)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1698#-OAY-Fj16teZ-QV5VpUA:-OAYADRpCw6kwI5wOEnw:b-xzyzbl) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d20b7f0e639301ef1b1584ec25be48da077e4c4/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L59)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

My guess is that the gateway group is using papyrus. So they just receive 0 instead of an error when doing this request
</blockquote></details>

who - other than us - is using the RPC reader, then?

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1698)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1698#-OAY-Fj16teZ-QV5VpUA:-OAYGkep0MAl74nYQIBH:b-b60si9) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d20b7f0e639301ef1b1584ec25be48da077e4c4/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L59)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

who - other than us - is using the RPC reader, then?
</blockquote></details>

The gateway group

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1698)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1698#-OAY-Fj16teZ-QV5VpUA:-OAl7mcQAkW0RlS6z_tT:b-zdtvvx) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d20b7f0e639301ef1b1584ec25be48da077e4c4/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L59)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

The gateway group
</blockquote></details>

no, you said the gateway group is using papyrus state reader. not the rpc reader...
1. if the GW group are using the rpc reader, why do they allow the error behavior instead of returning zero like papyrus?
2. if they are not using the rpc reader, who is?

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1698)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1698#-OAY-Fj16teZ-QV5VpUA:-OAlgfWd5Kc3x9Dc_l3E:b-yxlx8r) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d20b7f0e639301ef1b1584ec25be48da077e4c4/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L59)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no, you said the gateway group is using papyrus state reader. not the rpc reader...
1. if the GW group are using the rpc reader, why do they allow the error behavior instead of returning zero like papyrus?
2. if they are not using the rpc reader, who is?
</blockquote></details>

The gateway group uses the RPC reader. Papyrus is also an RPC server, so they tested their RPC reader with Papyrus while we use the link to other RPC server

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1698)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1698#-OAY-Fj16teZ-QV5VpUA:-OAlhW5a0k1G_PkqTesH:b320v4m) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d20b7f0e639301ef1b1584ec25be48da077e4c4/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L59)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

The gateway group uses the RPC reader. Papyrus is also an RPC server, so they tested their RPC reader with Papyrus while we use the link to other RPC server
</blockquote></details>

so the remote RPC returns an error where the papyrus reader returns zero?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1698)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1698#-OAY-Fj16teZ-QV5VpUA:-OAlhdQe-msw3dxOkb6s:b-7d4sxs) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d20b7f0e639301ef1b1584ec25be48da077e4c4/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L59)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

so the remote RPC returns an error where the papyrus reader returns zero?
</blockquote></details>

the papyrus server does not behave like the RPC server we use?

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1698)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1698#-OAY-Fj16teZ-QV5VpUA:-OAlmsIBDqZXHEhRSTQ9:b1nbsq8) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d20b7f0e639301ef1b1584ec25be48da077e4c4/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L59)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the papyrus server does not behave like the RPC server we use?
</blockquote></details>

That is what I thought at the beginning, but after first looking at the papyrus_rpc crate, I think that the papyrus RPC server returns an Error as well. I have a meeting with Yael tomorrow to understand it

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1698)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1698#-OAY-Fj16teZ-QV5VpUA:-OAmgRp-BShpSs-FPqe5:b-8upmvl) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d20b7f0e639301ef1b1584ec25be48da077e4c4/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L59)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

That is what I thought at the beginning, but after first looking at the papyrus_rpc crate, I think that the papyrus RPC server returns an Error as well. I have a meeting with Yael tomorrow to understand it
</blockquote></details>

OK, keeping this blocked for now, because it changes the behavior of the client - I would like to understand why (if) we need it

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1698)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1698#-OAY-Fj16teZ-QV5VpUA:-OAqF5emDpHxIeZvbvp8:b-65kj0m) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d20b7f0e639301ef1b1584ec25be48da077e4c4/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L59)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

OK, keeping this blocked for now, because it changes the behavior of the client - I would like to understand why (if) we need it
</blockquote></details>

It changes the behavior of our wrapper; I didn't touch the gateway`s code

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1698)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 75 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1698#-OArH-6r3EAGGiMRycWM:-OArH-6r3EAGGiMRycWN:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/25ae07d4abe1eb28fa064afc7a3f66775edb01a5/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L75)):*
> ```XML
>             Err(e) if e.to_string().contains("Contract address not found for request") => {
>                 Ok(Felt::default())
>             }
> ```





_Suggestion:_
```XML
            // TODO: Once the RPC state reader bug is fixed (CONTRACT_NOT_FOUND error should cause the
            //   reader to return the default felt), remove this `match` arm.
            Err(e) if e.to_string().contains("Contract address not found for request") => {
                Ok(Felt::default())
            }
```

**Pull request closed without merging**
