### PR TITLE
feat(starknet_monitoring_endpoint): add metrics endpoint

### PR DESCRIPTION
**Pull request by dan-starkware**

### CODE REVIEW

**Comment by dan-starkware** [comment]
* **#2469** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2469?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2469?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by dan-starkware** [comment]
*[`crates/starknet_monitoring_endpoint/src/monitoring_endpoint_test.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2469#-ODNGa4h7qEDIqf4sZFV:-ODa3Sm13Vb7_HIMZBcq:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4cb7c682acb73b4abf0cf78a182c679bb455aa36/crates/starknet_monitoring_endpoint/src/monitoring_endpoint_test.rs#L69)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please import at top, and use `METRICS` here.
</blockquote></details>

Done.

**Comment by dan-starkware** [comment]
*[`crates/starknet_monitoring_endpoint/src/monitoring_endpoint_test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2469#-ODNDZlD4KJrEoDQqjX8:-ODa4SeKC2fozt8D6Qc8:bmg60fd) ([raw file](https://github.com/starkware-libs/sequencer/blob/4cb7c682acb73b4abf0cf78a182c679bb455aa36/crates/starknet_monitoring_endpoint/src/monitoring_endpoint_test.rs#L51)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Could you please align the test names (with/without `test_` prefix) within this module? I don't mind to which, just aiming for consistency.
</blockquote></details>

Done further up the stack

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2469#-:-ODblLMm-Ry1iqcRq6OU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/starknet_monitoring_endpoint/src/monitoring_endpoint.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2469#-ODNGw502ZvcVurA5i6u:-ODbl9U10M4An14daN2S:b-hi7b91) ([raw file](https://github.com/starkware-libs/sequencer/blob/4cb7c682acb73b4abf0cf78a182c679bb455aa36/crates/starknet_monitoring_endpoint/src/monitoring_endpoint.rs#L101)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Are we expected not to collect metrics at some point? IIUC this is turned on once, and we'll keep adding new relevant metrics as we go.
Could we avoid using `Option` here, and simply return `handle.render().into_response()`?
</blockquote></details>

Could you please add a todo on my name (tsabary) to handle the `Option` setup?
Changed to non-blocking

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2469)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Comment by dan-starkware** [comment]
### Merge activity

* **Dec 9, 7:01 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2469).

**Pull request merged**
