### PR TITLE
chore(consensus): add sync_retry_interval to config

### PR DESCRIPTION
**Pull request by asmaastarkware**

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2923)* status: all files reviewed, 3 unresolved discussions (waiting on @asmaastarkware)

___
*[`config/papyrus/default_config.json` line 188 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2923#-OEtnNc14fmAAu3KpyMr:-OEtnNc14fmAAu3KpyMs:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/75097325fe99587473e9f5f6bee2ab1808d36c16/config/papyrus/default_config.json#L188)):*
> ```JSON
>   },
>   "consensus.sync_retry_interval": {
>     "description": "The duration (seconds) to wait before retrying a sync attempt.",
> ```





_Suggestion:_
```JSON
    "description": "The duration (seconds) between sync attempts.",
```
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2923#-OEto-A130kSIt54YE1m:-OEto-A130kSIt54YE1n:bkd6st1) ([raw file](https://github.com/starkware-libs/sequencer/blob/75097325fe99587473e9f5f6bee2ab1808d36c16/crates/sequencing/papyrus_consensus/src/manager_test.rs#L39)):*
> ```XML
> 
> const CHANNEL_SIZE: usize = 10;
> const SYNC_RETRY_INTERVAL: Duration = Duration::from_millis(100);
> ```

For this PR we can accept this, but I don't like having to actually use timing in tests. Please talk to Dan about if we have a clock abstraction that can be used.

It's much between when tests can be explicit about events happening (e.g. clock.next() when we want to retrigger sync)



_Code quote:_
```XML
const SYNC_RETRY_INTERVAL: Duration = Duration::from_millis(100);
```
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2923#-OEtoWp32VmEFi0Wxg8d:-OEtoWp32VmEFi0Wxg8e:b-nyrzac) ([raw file](https://github.com/starkware-libs/sequencer/blob/75097325fe99587473e9f5f6bee2ab1808d36c16/crates/sequencing/papyrus_consensus/src/manager.rs#L173)):*
> ```XML
>         height: BlockNumber,
>         must_observer: bool,
>         _sync_retry_interval: Duration,
> ```

I don't like unused params. I think this PR would be better if it was a pure config change.



_Code quote:_
```XML
        _sync_retry_interval: Duration,
```

**Review by matan-starkware — COMMENTED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2923)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2923)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2923#-OEtoWp32VmEFi0Wxg8d:-OExb_we3fp-Xhx69Fzk:blfmgq6) ([raw file](https://github.com/starkware-libs/sequencer/blob/75097325fe99587473e9f5f6bee2ab1808d36c16/crates/sequencing/papyrus_consensus/src/manager.rs#L173)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I don't like unused params. I think this PR would be better if it was a pure config change.
</blockquote></details>

deleted :white_check_mark: 
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2923#-OEto-A130kSIt54YE1m:-OExblkz4TrmaLRIcMsa:bfdsdwj) ([raw file](https://github.com/starkware-libs/sequencer/blob/75097325fe99587473e9f5f6bee2ab1808d36c16/crates/sequencing/papyrus_consensus/src/manager_test.rs#L39)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

For this PR we can accept this, but I don't like having to actually use timing in tests. Please talk to Dan about if we have a clock abstraction that can be used.

It's much between when tests can be explicit about events happening (e.g. clock.next() when we want to retrigger sync)
</blockquote></details>

irrelevant to this PR, will be discussed when needed

**Review by matan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2923)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
