### PR TITLE
feat(native_blockifier): support receiving L1 Data Gas

### PR DESCRIPTION
**Pull request by TzahiTaub**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2343)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @TzahiTaub)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2343#-OCn3vmqARnPywftXBM0:-OCn3vmqARnPywftXBM1:b-6bonui) (no related file):*
py side PR?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2343)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @TzahiTaub)

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2343)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2343#-ODfTLUB6qIYa3Eobeez:-ODfTLUB6qIYa3Eobef-:bnvko7u) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce7d6bcc909593102fdd63bddd50a5308f5c551b/crates/native_blockifier/src/py_transaction.rs#L42)):*
> ```XML
>             PyResource::L1Gas => Resource::L1Gas,
>             PyResource::L1DataGas => Resource::L1DataGas,
>             PyResource::L2Gas => Resource::L2Gas,
> ```

Moved to be consistent with the order in the enum.

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2343)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2343#-OCn3vmqARnPywftXBM0:-ODfdmss-cESjll3fuzJ:bjna1by) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

py side PR?
</blockquote></details>

https://reviewable.io/reviews/starkware-industries/starkware/36348#-

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2343)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
