### PR TITLE
feat(batcher): implement get_proposal_content as part of the validate_proposal flow

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
* **#1867** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1867?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Yael-Starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1867)* status: all files reviewed, 6 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1867)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OB51w-K2gimyoezU9O6:-OB5nAZ5-r2uHZZdB2g4:b-7evq2a) ([raw file](https://github.com/starkware-libs/sequencer/blob/d93b550ef9e9545ebb8982916d88458488a72ccf/crates/batcher/src/batcher.rs#L49)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider having an enum + 1 container instead of 2 stucts and 2 containers
</blockquote></details>

I thought about it , but didn't do it because of the following:
These contexts are used by different functions, there is no place where they are both needed.
If I'd use an enum then each time I'd read the proposalContext, I'll have to verify that it is of the correct type (validate/propose).
___
*[`crates/batcher/src/batcher.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OB53lCSDvosvukuB8z8:-OB5nOfY-77IbWcNiP4F:b-2gc1l4) ([raw file](https://github.com/starkware-libs/sequencer/blob/d93b550ef9e9545ebb8982916d88458488a72ccf/crates/batcher/src/batcher.rs#L122)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

That requests are received in order.

Perhaps we need to add an order identifier to the request
</blockquote></details>

if they are received in order, why do we need an identifier?
___
*[`crates/batcher/src/batcher.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OB53J-EEcaxXZwmCUbi:-OB676WEDz43-6X8wO76:b-7f3d79) ([raw file](https://github.com/starkware-libs/sequencer/blob/d93b550ef9e9545ebb8982916d88458488a72ccf/crates/batcher/src/batcher.rs#L148)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

There is also the possibility that the client sent a non-existing proposal id.
You should use a different function for checking the proposal status.
The `take` function is for `decision_reached` IIRC
</blockquote></details>


I changed it to get_proposal_status, now it is more explicit.
also it protects against a erroneous consensus server that calls send_proposal_content after the proposal was finished.
___
*[`crates/batcher/src/batcher.rs` line 287 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OB546ps15AKrKsL2M60:-OB5nlZBCikBf66vMOns:b-7rl0jd) ([raw file](https://github.com/starkware-libs/sequencer/blob/d93b550ef9e9545ebb8982916d88458488a72ccf/crates/batcher/src/batcher.rs#L287)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why not InputStream?
</blockquote></details>

done.
___
*[`crates/batcher/src/batcher.rs` line 287 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OB54WzB4Fp7EU6kLpGe:-OB5o-fm4jba35RovvkJ:b-fk2jy0) ([raw file](https://github.com/starkware-libs/sequencer/blob/d93b550ef9e9545ebb8982916d88458488a72ccf/crates/batcher/src/batcher.rs#L287)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Both streams should be bounded or unbounded - I think that unbounded is better in this case.
</blockquote></details>

I think that since the stream is coming from outside , we need to bound it to prevent a DoS attack.
___
*[`crates/batcher/src/proposal_manager.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OB54vdq12syHGi9dFLb:-OB6ZRBCENQzNKrykYsi:b-ta2mrl) ([raw file](https://github.com/starkware-libs/sequencer/blob/d93b550ef9e9545ebb8982916d88458488a72ccf/crates/batcher/src/proposal_manager.rs#L208)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

This function can be used to stream proposal content while a different proposal is being executed.
Shouldn't be waiting for the completion
</blockquote></details>

added a proposal_id param.
done.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1867)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OB51w-K2gimyoezU9O6:-OBJcw_8CkEDNk1bjyIJ:b32i49h) ([raw file](https://github.com/starkware-libs/sequencer/blob/d93b550ef9e9545ebb8982916d88458488a72ccf/crates/batcher/src/batcher.rs#L49)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I thought about it , but didn't do it because of the following:
These contexts are used by different functions, there is no place where they are both needed.
If I'd use an enum then each time I'd read the proposalContext, I'll have to verify that it is of the correct type (validate/propose).
</blockquote></details>

but I don't mind removing the structs and put the stream item directly.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1867)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/batcher/src/batcher.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OB51w-K2gimyoezU9O6:-OBKCimsBKBu-8-yjZ2i:b-du35yi) ([raw file](https://github.com/starkware-libs/sequencer/blob/d93b550ef9e9545ebb8982916d88458488a72ccf/crates/batcher/src/batcher.rs#L49)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

but I don't mind removing the structs and put the stream item directly.
</blockquote></details>

Legit.
I think that in abort proposal and clearing proposals we will have the same flow for both types.
___
*[`crates/batcher/src/batcher.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OB53lCSDvosvukuB8z8:-OBKCYoWELVxx4jRe3wt:by5kpx8) ([raw file](https://github.com/starkware-libs/sequencer/blob/d93b550ef9e9545ebb8982916d88458488a72ccf/crates/batcher/src/batcher.rs#L122)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

if they are received in order, why do we need an identifier?
</blockquote></details>

I meant `the function assumes that requests are received in order`
___
*[`crates/batcher/src/batcher.rs` line 287 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OB54WzB4Fp7EU6kLpGe:-OBKHlIY6-ENOizxBes6:bxg0kqh) ([raw file](https://github.com/starkware-libs/sequencer/blob/d93b550ef9e9545ebb8982916d88458488a72ccf/crates/batcher/src/batcher.rs#L287)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think that since the stream is coming from outside , we need to bound it to prevent a DoS attack.
</blockquote></details>

Oh you're right
___
*[`crates/batcher/src/batcher.rs` line 154 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKGnv1BQLQl3wOi2LI:-OBKGnv1BQLQl3wOi2LJ:b-amex16) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a2a8575fe4f457053e76413202d7dae799c5806/crates/batcher/src/batcher.rs#L154)):*
> ```XML
>                     .validate_proposals
>                     .get(&proposal_id)
>                     .expect("The tx input channel was dropped before the block was done.")
> ```

I think the message is not clear.
Consider something like "Expecting `tx_provider_sender` to exist during batching"



_Code quote:_
```XML
expect("The tx input channel was dropped before the block was done.")
```
___
*[`crates/batcher/src/batcher.rs` line 168 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKHSf3ApFieDh5ioYY:-OBKHSf44bztUVUJmjNM:bx801be) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a2a8575fe4f457053e76413202d7dae799c5806/crates/batcher/src/batcher.rs#L168)):*
> ```XML
>                 response: ResponseProposalStatus::InvalidProposal,
>             }),
>             ProposalStatus::Finished => Err(BatcherError::ProposalAlreadyFinished { proposal_id }),
> ```

I think this should also be `InvalidProposal`.  Worth checking with @matan-starkware / product



_Code quote:_
```XML
BatcherError::ProposalAlreadyFinished { proposal_id }
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1867)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OB53lCSDvosvukuB8z8:-OBKRIPP1KHhu0lxLPED:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d93b550ef9e9545ebb8982916d88458488a72ccf/crates/batcher/src/batcher.rs#L122)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I meant `the function assumes that requests are received in order`
</blockquote></details>

Done.
___
*[`crates/batcher/src/batcher.rs` line 154 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKGnv1BQLQl3wOi2LI:-OBKR_Ft7CsCvkfJA8li:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a2a8575fe4f457053e76413202d7dae799c5806/crates/batcher/src/batcher.rs#L154)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think the message is not clear.
Consider something like "Expecting `tx_provider_sender` to exist during batching"
</blockquote></details>

Done.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1867)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @alonh5, @matan-starkware, and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 168 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKHSf3ApFieDh5ioYY:-OBKXCnlDV8IJaR7newV:bmtrw4h) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a2a8575fe4f457053e76413202d7dae799c5806/crates/batcher/src/batcher.rs#L168)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think this should also be `InvalidProposal`.  Worth checking with @matan-starkware / product
</blockquote></details>

after discussing, we agreed on the error.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1867)* status: all files reviewed, 9 unresolved discussions (waiting on @matan-starkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OB51w-K2gimyoezU9O6:-OB5PaSy6ZLyxrGbfaBV:b-7d9r6y) ([raw file](https://github.com/starkware-libs/sequencer/blob/d93b550ef9e9545ebb8982916d88458488a72ccf/crates/batcher/src/batcher.rs#L49)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Legit.
I think that in abort proposal and clearing proposals we will have the same flow for both types.
</blockquote></details>

Also in decision reached right? It could either be our proposal or a different node's that we validated.
You also need to make sure they don't get the same ID. BTW are we checking that for propose atm?
___
*[`crates/batcher/src/batcher.rs` line 287 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OB54WzB4Fp7EU6kLpGe:-OBKYDxl7OPUIEmZO7n_:b-9zf5p0) ([raw file](https://github.com/starkware-libs/sequencer/blob/d93b550ef9e9545ebb8982916d88458488a72ccf/crates/batcher/src/batcher.rs#L287)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Oh you're right
</blockquote></details>

Reading the unbounded_channel docstring, it says: `/// If the receiver falls behind, messages will be arbitrarily buffered.`
Does that mean their order can change? Isn't that a problem?
___
*[`crates/batcher/src/batcher.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKX4-N5_Hi5Pm_RLAE:-OBKX4-N5_Hi5Pm_RLAF:bufcj4x) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a2a8575fe4f457053e76413202d7dae799c5806/crates/batcher/src/batcher.rs#L187)):*
> ```XML
> 
>         let proposal_commitment =
>             self.proposal_manager.get_executed_proposal_commitment(proposal_id).await?;
> ```

Where is the commitment being added to the `executed_proposals`?



_Code quote:_
```XML
        let proposal_commitment =
            self.proposal_manager.get_executed_proposal_commitment(proposal_id).await?;
```
___
*[`crates/batcher/src/proposal_manager.rs` line 290 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKeM2J78NlNcoFv82e:-OBKeM2J78NlNcoFv82f:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ae5a9af4b4bc551ba20228427324bc8663ce13c/crates/batcher/src/proposal_manager.rs#L290)):*
> ```XML
>     // This function assumes there are not requests processed in parallel by the batcher, otherwise
>     // there is a race conditon between creating the active_proposal_handle and awaiting on it.
>     pub async fn wait_for_proposal_completion(&mut self, proposal_id: ProposalId) {
> ```





_Suggestion:_
```XML
await_proposal_completion
```
___
*[`crates/batcher/src/batcher.rs` line 50 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKb4Yl2qbzUXzwEGGw:-OBKb4Yl2qbzUXzwEGGx:b-cfoop5) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ae5a9af4b4bc551ba20228427324bc8663ce13c/crates/batcher/src/batcher.rs#L50)):*
> ```XML
> struct ValidateProposalContext {
>     tx_provider_sender: InputStreamSender,
> }
> ```

Do we need these wrapper structs? They don't add information, they hide it.



_Code quote:_
```XML
struct BuildProposalContext {
    output_tx_stream: OutputStreamReceiver,
}

struct ValidateProposalContext {
    tx_provider_sender: InputStreamSender,
}
```
___
*[`crates/batcher/src/batcher.rs` line 288 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKasph19qkiPMVRvuG:-OBKasph19qkiPMVRvuH:ba6xw9b) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ae5a9af4b4bc551ba20228427324bc8663ce13c/crates/batcher/src/batcher.rs#L288)):*
> ```XML
> }
> 
> // TODO: Make this work with streams.
> ```

Can this be removed?



_Code quote:_
```XML
// TODO: Make this work with streams.
```
___
*[`crates/batcher/src/batcher.rs` line 290 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKbScw34LRDEimOeY4:-OBKbScw34LRDEimOeY5:bz3iqbz) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ae5a9af4b4bc551ba20228427324bc8663ce13c/crates/batcher/src/batcher.rs#L290)):*
> ```XML
> // TODO: Make this work with streams.
> type OutputStreamReceiver = tokio::sync::mpsc::UnboundedReceiver<Transaction>;
> type InputStreamSender = tokio::sync::mpsc::Sender<Transaction>;
> ```

move to top of file.



_Code quote:_
```XML
type OutputStreamReceiver = tokio::sync::mpsc::UnboundedReceiver<Transaction>;
type InputStreamSender = tokio::sync::mpsc::Sender<Transaction>;
```

**Comment by yair-starkware** [comment]
*[`crates/batcher/src/batcher.rs` line 287 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OB54WzB4Fp7EU6kLpGe:-OBKq4uR02hoDO6bMfvk:b-bgxsqj) ([raw file](https://github.com/starkware-libs/sequencer/blob/d93b550ef9e9545ebb8982916d88458488a72ccf/crates/batcher/src/batcher.rs#L287)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Reading the unbounded_channel docstring, it says: `/// If the receiver falls behind, messages will be arbitrarily buffered.`
Does that mean their order can change? Isn't that a problem?
</blockquote></details>

I don't think it means that. 
IIUC it means that they can stay on the sender side instead of moving to the receiver side until they are awaited.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1867)* status: all files reviewed, 9 unresolved discussions (waiting on @matan-starkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 287 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OB54WzB4Fp7EU6kLpGe:-OBKzY-z0Gj93FGob0sm:b-fy3wyi) ([raw file](https://github.com/starkware-libs/sequencer/blob/d93b550ef9e9545ebb8982916d88458488a72ccf/crates/batcher/src/batcher.rs#L287)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I don't think it means that. 
IIUC it means that they can stay on the sender side instead of moving to the receiver side until they are awaited.
</blockquote></details>

Okay. I also ran some tests locally and it seems fine, even with multiple senders.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1867)* status: all files reviewed, 8 unresolved discussions (waiting on @alonh5, @matan-starkware, and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OB51w-K2gimyoezU9O6:-OBL3XFb6ycCSb_uTRyM:bl5vsmc) ([raw file](https://github.com/starkware-libs/sequencer/blob/d93b550ef9e9545ebb8982916d88458488a72ccf/crates/batcher/src/batcher.rs#L49)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Also in decision reached right? It could either be our proposal or a different node's that we validated.
You also need to make sure they don't get the same ID. BTW are we checking that for propose atm?
</blockquote></details>

On decision reached, the stream is not used, it is consumed by get_proposal_content (which is only for propose) before decision is reached.

We do check that for propose,  and will do that same check for validate. It is the same vector if executed_proposals in the proposal_manager, so you can check for a proposal_id of either propose or validate at once.
https://github.com/starkware-libs/sequencer/blob/2cba2f365ebaf4391637bc3ea426ec095db4c8ce/crates/batcher/src/proposal_manager.rs#L162
___
*[`crates/batcher/src/batcher.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKX4-N5_Hi5Pm_RLAE:-OBL1sWH3zTduR-V8EEg:baybdsc) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a2a8575fe4f457053e76413202d7dae799c5806/crates/batcher/src/batcher.rs#L187)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Where is the commitment being added to the `executed_proposals`?
</blockquote></details>

at the end of the thread running build_block.
https://github.com/starkware-libs/sequencer/blob/2cba2f365ebaf4391637bc3ea426ec095db4c8ce/crates/batcher/src/proposal_manager.rs#L185
___
*[`crates/batcher/src/batcher.rs` line 50 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKb4Yl2qbzUXzwEGGw:-OBL4Q5ZAuRmjql3MLFm:b-bescrc) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ae5a9af4b4bc551ba20228427324bc8663ce13c/crates/batcher/src/batcher.rs#L50)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Do we need these wrapper structs? They don't add information, they hide it.
</blockquote></details>

I'm not sure which is better, anyway I deleted them.
Done.
___
*[`crates/batcher/src/batcher.rs` line 288 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKasph19qkiPMVRvuG:-OBL2Kb8AywKGegG9Kl2:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ae5a9af4b4bc551ba20228427324bc8663ce13c/crates/batcher/src/batcher.rs#L288)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can this be removed?
</blockquote></details>

Done.
___
*[`crates/batcher/src/batcher.rs` line 290 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKbScw34LRDEimOeY4:-OBL2dPp5DgoBB4UZoqf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ae5a9af4b4bc551ba20228427324bc8663ce13c/crates/batcher/src/batcher.rs#L290)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

move to top of file.
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 290 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKeM2J78NlNcoFv82e:-OBL2iM465Kyf1WcqyZF:b-7rl0jd) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ae5a9af4b4bc551ba20228427324bc8663ce13c/crates/batcher/src/proposal_manager.rs#L290)):*
> ```XML
>     // This function assumes there are not requests processed in parallel by the batcher, otherwise
>     // there is a race conditon between creating the active_proposal_handle and awaiting on it.
>     pub async fn wait_for_proposal_completion(&mut self, proposal_id: ProposalId) {
> ```

done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1867)* status: all files reviewed, 5 unresolved discussions (waiting on @matan-starkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OB51w-K2gimyoezU9O6:-OBLJUOZE2bunIxBJUsx:bpfugyi) ([raw file](https://github.com/starkware-libs/sequencer/blob/d93b550ef9e9545ebb8982916d88458488a72ccf/crates/batcher/src/batcher.rs#L49)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

On decision reached, the stream is not used, it is consumed by get_proposal_content (which is only for propose) before decision is reached.

We do check that for propose,  and will do that same check for validate. It is the same vector if executed_proposals in the proposal_manager, so you can check for a proposal_id of either propose or validate at once.
https://github.com/starkware-libs/sequencer/blob/2cba2f365ebaf4391637bc3ea426ec095db4c8ce/crates/batcher/src/proposal_manager.rs#L162
</blockquote></details>

Right, thanks.
___
*[`crates/batcher/src/batcher.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKX4-N5_Hi5Pm_RLAE:-OBLHrYWAeQ_C5VSHNf6:b-21r4vp) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a2a8575fe4f457053e76413202d7dae799c5806/crates/batcher/src/batcher.rs#L187)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

at the end of the thread running build_block.
https://github.com/starkware-libs/sequencer/blob/2cba2f365ebaf4391637bc3ea426ec095db4c8ce/crates/batcher/src/proposal_manager.rs#L185
</blockquote></details>

Got it, thanks.
Maybe we should name the function `await_proposal_commitment` so it's more clear?
___
*[`crates/batcher/src/batcher.rs` line 50 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKb4Yl2qbzUXzwEGGw:-OBLGmv8C5fkOvcjzN7j:b-r2tb5w) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ae5a9af4b4bc551ba20228427324bc8663ce13c/crates/batcher/src/batcher.rs#L50)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I'm not sure which is better, anyway I deleted them.
Done.
</blockquote></details>

Can you also delete the struct declarations?

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1867)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @alonh5, @matan-starkware, and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 50 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKb4Yl2qbzUXzwEGGw:-OBLiLXX5FXcZN9cmfBj:bsdxb2v) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ae5a9af4b4bc551ba20228427324bc8663ce13c/crates/batcher/src/batcher.rs#L50)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you also delete the struct declarations?
</blockquote></details>

yes oops, done.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1867)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @alonh5, @matan-starkware, and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKX4-N5_Hi5Pm_RLAE:-OBLixCdCIIwNnmG1CP1:b-n3ceap) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a2a8575fe4f457053e76413202d7dae799c5806/crates/batcher/src/batcher.rs#L187)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Got it, thanks.
Maybe we should name the function `await_proposal_commitment` so it's more clear?
</blockquote></details>

maybe await_proposal_result? 
because it produces more than the commitment.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1867)* status: all files reviewed, 4 unresolved discussions (waiting on @matan-starkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKX4-N5_Hi5Pm_RLAE:-OBPEqViChXaEjaq-urZ:b-npk1wn) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a2a8575fe4f457053e76413202d7dae799c5806/crates/batcher/src/batcher.rs#L187)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

maybe await_proposal_result? 
because it produces more than the commitment.
</blockquote></details>

What else does it produce? I'm talking about `get_executed_proposal_commitment()`.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1867)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @alonh5, @matan-starkware, and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-OBKX4-N5_Hi5Pm_RLAE:-OBPNDbm7a9u7WI27hlK:b-ezz225) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a2a8575fe4f457053e76413202d7dae799c5806/crates/batcher/src/batcher.rs#L187)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What else does it produce? I'm talking about `get_executed_proposal_commitment()`.
</blockquote></details>

oh ok, sure. Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-:-OBPcAim6F1_i73IFNxz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1867#-:-OBPcY-C0j06hVyusPEf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1867)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
