### PR TITLE
chore(starknet_integration_tests): check alive instead of timeout

### PR DESCRIPTION
**Pull request by lev-starkware**
**Stack**:
- #2723
- #2719 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2719#-:-OEJeuf4BaWJqpSOUheZ:bnfp4nl)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2719#-OEJg8qj7VSgyf0rAHVm:-OEJg8qj7VSgyf0rAHVn:b-oc42qg) ([raw file](https://github.com/starkware-libs/sequencer/blob/bebfd8b92e127b78cf90f21772df5bab110fe583/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L47)):*
> ```XML
> 
>     wait_for_sequencer_node(&mock_running_system.sequencer_0).await;
>     wait_for_sequencer_node(&mock_running_system.sequencer_1).await;
> ```

Can we use `join!` here? This implies in a clearer manner that the completion order of these does not matter, as long as they both successfully complete. 



_Code quote:_
```XML
    wait_for_sequencer_node(&mock_running_system.sequencer_0).await;
    wait_for_sequencer_node(&mock_running_system.sequencer_1).await;
```
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2719#-OEJfyQf3eQ0dppMSk5P:-OEJfyQgD15pxViU105c:b-hhkscf) ([raw file](https://github.com/starkware-libs/sequencer/blob/bebfd8b92e127b78cf90f21772df5bab110fe583/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L103)):*
> ```XML
>         Ok(_) => {}
>         Err(_) => panic!("Node is not alive."),
>     }
> ```

Please change to `expect("Node should be alive")`.



_Code quote:_
```XML
    match sequencer.is_alive_test_client.await_alive(5000, 50).await {
        Ok(_) => {}
        Err(_) => panic!("Node is not alive."),
    }
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2719)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2719#-OEJg8qj7VSgyf0rAHVm:-OEJpY8j52-Rqo5XFbdR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bebfd8b92e127b78cf90f21772df5bab110fe583/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L47)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can we use `join!` here? This implies in a clearer manner that the completion order of these does not matter, as long as they both successfully complete.
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2719#-OEJfyQf3eQ0dppMSk5P:-OEJnubXCreODjr5cAtG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/bebfd8b92e127b78cf90f21772df5bab110fe583/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L103)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change to `expect("Node should be alive")`.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2719#-:-OEJqdxo6E3U83NvGv41:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lev-starkware)

**Comment by lev-starkware** [comment]
✓ Commit merged in pull request [#2723](https://github.com/starkware-libs/sequencer/pull/2723)

**Pull request closed without merging**
