### PR TITLE
refactor(common,starknet_api): align tx hash logic to papyrus_common

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/915)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/915)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/915#-O7O4gqAAbHKhBzJ_v36:-O7O4gqAAbHKhBzJ_v37:b-6uoxlj) (no related file):*
[motivation](https://reviewable.io/reviews/starkware-libs/sequencer/919)

___

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/915)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/915#-O7Yetu75EmiyoQZIrHm:-O7Yetu80gTWtDmBC2vk:b-uejzir) ([raw file](https://github.com/starkware-libs/sequencer/blob/e779b435932a6483e60ffd7510b54a7cee6325a4/crates/papyrus_common/src/transaction_hash.rs#L151)):*
> ```XML
> /// transactions on mainnet, the hash is validated by calculating the precise hash
> /// based on the transaction version.
> pub fn validate_transaction_hash(
> ```

Is this needed? Why can't we use the one defined in SN API?
(applies to other methods in this file)



_Code quote:_
```XML
pub fn validate_transaction_hash(
```
___
*[`crates/starknet_api/src/transaction.rs` line 771 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/915#-O7Ye2n26DvDlb0DBwgA:-O7Ye2n3EEG3Tx4OSE9G:b-5hc7g1) ([raw file](https://github.com/starkware-libs/sequencer/blob/e779b435932a6483e60ffd7510b54a7cee6325a4/crates/starknet_api/src/transaction.rs#L771)):*
> ```XML
> 
> // Returns the transaction version taking into account the transaction options.
> pub fn get_tx_version(
> ```

Can you, in some way, use the method [signed_version](https://github.com/starkware-libs/sequencer/blob/2ab99183f6b2e96699e3e3506aaf9f424283ea48/crates/blockifier/src/transaction/objects.rs#L93)?



_Code quote:_
```XML
pub fn get_tx_version(
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/915)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/papyrus_common/src/transaction_hash.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/915#-O7Yetu75EmiyoQZIrHm:-O7Yj1Vp7SIacAn6Y297:bwyj0cm) ([raw file](https://github.com/starkware-libs/sequencer/blob/e779b435932a6483e60ffd7510b54a7cee6325a4/crates/papyrus_common/src/transaction_hash.rs#L151)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is this needed? Why can't we use the one defined in SN API?
(applies to other methods in this file)
</blockquote></details>

[I'll do you one better](https://reviewable.io/reviews/starkware-libs/sequencer/936)
___
*[`crates/starknet_api/src/transaction.rs` line 771 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/915#-O7Ye2n26DvDlb0DBwgA:-O7Yjeal8fUFvPCjJt18:bxa6eob) ([raw file](https://github.com/starkware-libs/sequencer/blob/e779b435932a6483e60ffd7510b54a7cee6325a4/crates/starknet_api/src/transaction.rs#L771)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you, in some way, use the method [signed_version](https://github.com/starkware-libs/sequencer/blob/2ab99183f6b2e96699e3e3506aaf9f424283ea48/crates/blockifier/src/transaction/objects.rs#L93)?
</blockquote></details>

1. How would I get a `TransactionInfo` object from a `Transaction` + `TransactionOptions`?
2. starknet_api can't use blockifier code, perhaps the signed_version should actually call `get_tx_version`?

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/915)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/starknet_api/src/transaction.rs` line 781 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/915#-O7YlXYa24XtXLsiPCc2:-O7YlXYa24XtXLsiPCc3:b9xfta5) ([raw file](https://github.com/starkware-libs/sequencer/blob/f375d3a567c7163cc1b5d541ae3f2af376b7a4f8/crates/starknet_api/src/transaction.rs#L781)):*
> ```XML
>         let query_only_bit: Felt = Felt::from_hex_unchecked("0x100000000000000000000000000000000");
>         let fe: Felt = version.0;
>         version = TransactionVersion(fe + query_only_bit);
> ```

Maybe better to have the constant here? (128)
And, as you suggested, call this method from the blockifier



_Suggestion:_
```XML
        let query_version_base = Felt::TWO.pow(constants::QUERY_VERSION_BASE_BIT);
        let query_version = query_version_base + version.0;
        TransactionVersion(query_version)
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/915)* status: 5 of 15 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/starknet_api/src/transaction.rs` line 781 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/915#-O7YlXYa24XtXLsiPCc2:-O7Yw14-4P-pboaTGNlX:b-q6n7v0) ([raw file](https://github.com/starkware-libs/sequencer/blob/f375d3a567c7163cc1b5d541ae3f2af376b7a4f8/crates/starknet_api/src/transaction.rs#L781)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Maybe better to have the constant here? (128)
And, as you suggested, call this method from the blockifier
</blockquote></details>

done, though now I added some sanity checks... we really should separate the types of versions... transaction obejcts have a `tx_version` method that doesn't take query bit into account, but this function here does

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/915)* status: 5 of 16 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 184 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/915#-O7ZD47uDnaFRLDEgK_v:-O7ZD47v-FOPsyoS1bbI:b-d17h62) ([raw file](https://github.com/starkware-libs/sequencer/blob/902c2b0bdb93a83a8b68291a07594a2b220ebbd7/crates/blockifier/src/versioned_constants.rs#L184)):*
> ```XML
>     pub fn get_l1_to_l2_gas_price_ratio(&self) -> ResourceCost {
>         self.l1_to_l2_gas_price_ratio()
>     }
> ```

merge conflict (duplicated definition)



_Code quote:_
```XML
    #[cfg(any(feature = "testing", test))]
    pub fn get_l1_to_l2_gas_price_ratio(&self) -> ResourceCost {
        self.l1_to_l2_gas_price_ratio()
    }
```

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 11 files at r4, 9 of 11 files at r5, 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/915)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/starknet_api/src/transaction.rs` line 781 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/915#-O7YlXYa24XtXLsiPCc2:-O7hBbT88Xs8-qkY3cpF:b6uo17c) ([raw file](https://github.com/starkware-libs/sequencer/blob/41dd6b7dd6c62224461719c27744cabe25a6fc72/crates/starknet_api/src/transaction.rs#L781)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

done, though now I added some sanity checks... we really should separate the types of versions... transaction obejcts have a `tx_version` method that doesn't take query bit into account, but this function here does
</blockquote></details>

I think it's safe to assume no query bit was set in the transaction version. Better to add an assert at the beginning of the function. 
___
*[`crates/starknet_api/src/transaction.rs` line 777 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/915#-O7hA4Yl2gIZqyg1nH8u:-O7hA4Yl2gIZqyg1nH8v:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1226a29df5be28ea83f2d9111d41a0da82c791a7/crates/starknet_api/src/transaction.rs#L777)):*
> ```XML
> // TODO: TransactionVersion and SignedTransactionVersion should probably be separate types.
> // Returns the transaction version taking into account the transaction options.
> pub fn get_signed_tx_version_from_tx(
> ```





_Suggestion:_
```XML
pub fn signed_tx_version_from_tx(
```
___
*[`crates/starknet_api/src/transaction.rs` line 784 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/915#-O7hAJvTEAtMKGBVCOax:-O7hAJvTEAtMKGBVCOay:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1226a29df5be28ea83f2d9111d41a0da82c791a7/crates/starknet_api/src/transaction.rs#L784)):*
> ```XML
> }
> 
> pub fn get_signed_tx_version(
> ```





_Suggestion:_
```XML
pub fn signed_tx_version(
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/915)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/starknet_api/src/transaction.rs` line 781 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/915#-O7YlXYa24XtXLsiPCc2:-O7hMw-h5os60fSyVcip:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/41dd6b7dd6c62224461719c27744cabe25a6fc72/crates/starknet_api/src/transaction.rs#L781)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think it's safe to assume no query bit was set in the transaction version. Better to add an assert at the beginning of the function.
</blockquote></details>

done

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 12 files at r7, 10 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/915#-:-O7htoCF7wUKcvs4G8ZL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
