### PR TITLE
Merge main-v0.13.2 into main

### PR DESCRIPTION
**Pull request by dan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/217)

### CODE REVIEW

**Comment by dan-starkware** [comment]
[Src](https://github.com/starkware-libs/blockifier/compare/7ee04dbc7e666cfa9e8b7c1a8769970fbea5b6fe..main-v0.13.2#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542) [Dst](https://github.com/starkware-libs/blockifier/compare/7ee04dbc7e666cfa9e8b7c1a8769970fbea5b6fe..main#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542) Cargo.toml
[Src](https://github.com/starkware-libs/blockifier/compare/7ee04dbc7e666cfa9e8b7c1a8769970fbea5b6fe..main-v0.13.2#diff-ac48598a1754d54f4157d0b6b0bbd3467dba93c72478a9beaffe15e4d8f58d03) [Dst](https://github.com/starkware-libs/blockifier/compare/7ee04dbc7e666cfa9e8b7c1a8769970fbea5b6fe..main#diff-ac48598a1754d54f4157d0b6b0bbd3467dba93c72478a9beaffe15e4d8f58d03) crates/mempool_types/Cargo.toml
[Src](https://github.com/starkware-libs/blockifier/compare/7ee04dbc7e666cfa9e8b7c1a8769970fbea5b6fe..main-v0.13.2#diff-b48a97cafbca500ce03511c076e7f97e3b8d8f17897d95848781b3843e52a3ee) [Dst](https://github.com/starkware-libs/blockifier/compare/7ee04dbc7e666cfa9e8b7c1a8769970fbea5b6fe..main#diff-b48a97cafbca500ce03511c076e7f97e3b8d8f17897d95848781b3843e52a3ee) crates/papyrus_network/Cargo.toml

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 22 of 30 files at r2, 2 of 2 files at r3, 1 of 1 files at r6, 1 of 1 files at r7, 2 of 3 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 3 of 3 files at r11, 8 of 8 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/217)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r15, 2 of 2 files at r16, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/217#-:-O37eOo42lB1Hck_EZD2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/217)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Pull request merged**
