### PR TITLE
refactor(mempool): provide optional broadcasted message metadata in mempool add_tx

### PR DESCRIPTION
**Pull request by AlonLStarkWare**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/746)

### CODE REVIEW

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/746)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 841 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/746#-O6M12Ym5avus5pmd9yj:-O6M12Ym5avus5pmd9yk:bp2h3xx) ([raw file](https://github.com/starkware-libs/sequencer/blob/7fad43aa662fd809c226c57a93c9fed61757e909/crates/papyrus_network/src/network_manager/mod.rs#L841)):*
> ```XML
> 
> // TODO(alonl): remove clone
> #[derive(Clone, Debug, PartialEq)]
> ```

where is this being used in the pr? 



_Code quote:_
```XML
, Debug, PartialEq
```

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/746)* status: all files reviewed, 5 unresolved discussions (waiting on @AlonLStarkWare)

___
*[`crates/gateway/src/gateway_test.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/746#-O6_NuAwAFqpB9z3aOih:-O6_NuAwAFqpB9z3aOii:bwhllhx) ([raw file](https://github.com/starkware-libs/sequencer/blob/7fad43aa662fd809c226c57a93c9fed61757e909/crates/gateway/src/gateway_test.rs#L72)):*
> ```XML
>             eq(MempoolInput {
>                 // TODO(Arni): Use external_to_executable_tx instead of `create_executable_tx`.
>                 // Consider creating a `convertor for testing` that does not do the
> ```

Revert this
___
*[`crates/gateway/src/gateway_test.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/746#-O6_O-6x5sEjpedNKVMk:-O6_O-6x5sEjpedNKVMl:b8iz8lp) ([raw file](https://github.com/starkware-libs/sequencer/blob/7fad43aa662fd809c226c57a93c9fed61757e909/crates/gateway/src/gateway_test.rs#L83)):*
> ```XML
>                 account: Account { sender_address, state: AccountState { nonce: *tx.nonce() } },
>             }),
>             eq(None),
> ```

Add TODO to add a test with Some
___
*[`crates/mempool_types/src/communication.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/746#-O6_OKLk58GXXh6_bYdW:-O6_OKLk58GXXh6_bYdX:b-kg4jh4) ([raw file](https://github.com/starkware-libs/sequencer/blob/7fad43aa662fd809c226c57a93c9fed61757e909/crates/mempool_types/src/communication.rs#L67)):*
> ```XML
>         &self,
>         mempool_input: MempoolInput,
>         _message_manager: Option<BroadcastedMessageManager>,
> ```

You should add Option<BroadcastedMessageManager> to MempoolRequest::AddTransaction and then use the variable when you define request
___
*[`crates/mempool_types/src/communication.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/746#-O6_OTfj9p4lQ05kTp46:-O6_OTfj9p4lQ05kTp47:b-ya81ng) ([raw file](https://github.com/starkware-libs/sequencer/blob/7fad43aa662fd809c226c57a93c9fed61757e909/crates/mempool_types/src/communication.rs#L91)):*
> ```XML
>         &self,
>         mempool_input: MempoolInput,
>         _message_manager: Option<BroadcastedMessageManager>,
> ```

Same as above

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/746)* status: 1 of 8 files reviewed, 4 unresolved discussions (waiting on @eitanm-starkware and @ShahakShama)

___
*[`crates/gateway/src/gateway_test.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/746#-O6_O-6x5sEjpedNKVMk:-O6pWklF8kUNKDabD1Kt:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7fad43aa662fd809c226c57a93c9fed61757e909/crates/gateway/src/gateway_test.rs#L83)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to add a test with Some
</blockquote></details>

Done.
___
*[`crates/mempool_types/src/communication.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/746#-O6_OKLk58GXXh6_bYdW:-O6pWja6EJ1ao9y-dpIH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7fad43aa662fd809c226c57a93c9fed61757e909/crates/mempool_types/src/communication.rs#L67)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You should add Option<BroadcastedMessageManager> to MempoolRequest::AddTransaction and then use the variable when you define request
</blockquote></details>

Done.
___
*[`crates/mempool_types/src/communication.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/746#-O6_OTfj9p4lQ05kTp46:-O6oh1Up36hjsO_QkQdC:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7fad43aa662fd809c226c57a93c9fed61757e909/crates/mempool_types/src/communication.rs#L91)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 841 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/746#-O6M12Ym5avus5pmd9yj:-O6ofwT50lPuwgjeMn4W:b2o8lx1) ([raw file](https://github.com/starkware-libs/sequencer/blob/7fad43aa662fd809c226c57a93c9fed61757e909/crates/papyrus_network/src/network_manager/mod.rs#L841)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

where is this being used in the pr?
</blockquote></details>

PartialEq is required for test_add_tx in gateway/src/gateway_test.rs
Debug, Serialize, and Deserialize are required to derive in MempoolRequest

**Review by ShahakShama — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/746)* status: all files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware)

**Review by AlonLStarkWare — COMMENTED** [review]
> Dismissed @eitanm-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/746)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Review by ShahakShama — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/746)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/746#-:-O6zU8uA62D9Vf0QIKQ4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Pull request merged**
