### PR TITLE
fix: add program to deprecated_contract_class to protobuf conversion

### PR DESCRIPTION
**Pull request by noamsp-starkware**

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1608)* status: all files reviewed, 2 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1608#-OAMTuDP6axu8FWJ_Ni1:-OAMTuDP6axu8FWJ_Ni2:bx6xmun) ([raw file](https://github.com/starkware-libs/sequencer/blob/313c385fb062d44b979eaa8539e03359cee42111/crates/papyrus_protobuf/src/converters/class.rs#L146)):*
> ```XML
>         // TODO: remove expects and handle results properly
>         let serialized_program = serde_json::to_value(&value.program)
>             .expect("Failed to serialize deprecated_contract_class::Program to JSON");
> ```

JSON -> serde_json::Value
___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1608#-OAMwKTY5LlBILiISuRD:-OAMwKTZ9bu648o9uRZF:b-w2hqlt) ([raw file](https://github.com/starkware-libs/sequencer/blob/313c385fb062d44b979eaa8539e03359cee42111/crates/papyrus_protobuf/src/converters/class.rs#L150)):*
> ```XML
>         // TODO: consider storing the encoded program
>         let encoded_program = compress_and_encode(serialized_program)
>             .expect("Failed to compress and encode serialized deprecated_contract_class::Program");
> ```

deprecated_contract_class::Program -> Cairo 0 program
A bit of explanation why here I said to not write the struct in "code form" and why above I said to write: Here, a cairo 0 class is something we use more throughout the node. and the word JSON can be interpreted in a lot of different ways. Also, because the serde_json crate is pretty popular it makes more sense to reference it

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1608)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1608#-OAMTuDP6axu8FWJ_Ni1:-OANGn-eCi8ouLPBj3p_:b-4ec1rn) ([raw file](https://github.com/starkware-libs/sequencer/blob/313c385fb062d44b979eaa8539e03359cee42111/crates/papyrus_protobuf/src/converters/class.rs#L146)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

JSON -> serde_json::Value
</blockquote></details>

Done.

Please note I applied the change suggested below to this line as well.
___
*[`crates/papyrus_protobuf/src/converters/class.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1608#-OAMwKTY5LlBILiISuRD:-OANGogA-KtywWnB2vmU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/313c385fb062d44b979eaa8539e03359cee42111/crates/papyrus_protobuf/src/converters/class.rs#L150)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

deprecated_contract_class::Program -> Cairo 0 program
A bit of explanation why here I said to not write the struct in "code form" and why above I said to write: Here, a cairo 0 class is something we use more throughout the node. and the word JSON can be interpreted in a lot of different ways. Also, because the serde_json crate is pretty popular it makes more sense to reference it
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1608#-:-OANVU2OClLkljypRnnJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r4, 3 of 3 files at r7, 2 of 3 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1608#-:-OAXV0igCKcvpopi3gx0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)

**Pull request merged**
