### PR TITLE
fix(mempool): fix nonce-rewind in `commit_block` for known non-included addresses

### PR DESCRIPTION
**Pull request by elintul**

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1837)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/tests/flow_test.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1837#-OAwaWt4AlMpRhasOI9D:-OAwaWt4AlMpRhasOI9E:b-zi1t1q) ([raw file](https://github.com/starkware-libs/sequencer/blob/c05a6eac5cb64b94e30f0ec0a7582fa2328fc79c/crates/mempool/tests/flow_test.rs#L226)):*
> ```XML
>     let tx_nonce_2 = add_tx_input!(tx_hash: 1, address: "0x0", tx_nonce: 2, account_nonce: 2);
>     let tx_nonce_3 = add_tx_input!(tx_hash: 2, address: "0x0", tx_nonce: 3, account_nonce: 2);
>     let tx_nonce_4 = add_tx_input!(tx_hash: 3, address: "0x0", tx_nonce: 4, account_nonce: 2);
> ```

No need for two nonces rewinded, it's the same case as one.
Also, I prefer the included and non-included cases to be symmetrical.



_Code quote:_
```XML
tx_nonce_4
```

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1837#-:-OAwjzegDhkemSEmBXf-:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/tests/flow_test.rs` line 246 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1837#-OAwjofREHnmAaeBwsg6:-OAwjofSEg3SSCS560s2:beccl49) ([raw file](https://github.com/starkware-libs/sequencer/blob/461201a826f551cb2a3a80704c887160e4586124/crates/mempool/tests/flow_test.rs#L246)):*
> ```XML
>             tx_address_0_nonce_2.tx,
>             tx_address_1_nonce_3.tx,
>             tx_address_0_nonce_3.tx.clone(),
> ```

Please re-order.



_Suggestion:_
```XML
            tx_address_0_nonce_2.tx,
            tx_address_0_nonce_3.tx.clone(),
            tx_address_1_nonce_2.tx.clone(),
            tx_address_1_nonce_3.tx,
```

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1837)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/tests/flow_test.rs` line 246 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1837#-OAwjofREHnmAaeBwsg6:-OAwkHHH5pGw_eD09iKz:b2r2kej) ([raw file](https://github.com/starkware-libs/sequencer/blob/461201a826f551cb2a3a80704c887160e4586124/crates/mempool/tests/flow_test.rs#L246)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please re-order.
</blockquote></details>

Please ignore.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1837)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/tests/flow_test.rs` line 246 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1837#-OAwjofREHnmAaeBwsg6:-OAwkv6i-gXb1FWNZlgm:b-gvddop) ([raw file](https://github.com/starkware-libs/sequencer/blob/461201a826f551cb2a3a80704c887160e4586124/crates/mempool/tests/flow_test.rs#L246)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please re-order.
</blockquote></details>

I can't, this is the order they're returned in (queue is only updated after all addresses are exhausted).

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1837)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/tests/flow_test.rs` line 246 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1837#-OAwjofREHnmAaeBwsg6:-OAwlIRM3S-B28DdQugM:bju85t9) ([raw file](https://github.com/starkware-libs/sequencer/blob/461201a826f551cb2a3a80704c887160e4586124/crates/mempool/tests/flow_test.rs#L246)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I can't, this is the order they're returned in (queue is only updated after all addresses are exhausted).
</blockquote></details>

You're correct,  got it.

**Pull request merged**
