### PR TITLE
test(mempool): fix `test_add_tx_lower_than_queued_nonce` setup

### PR DESCRIPTION
**Pull request by elintul**
- This is prep. for nonce abstraction feature; setup should be done in a complete manner, so all nonce layers will be updated properly.
- Removed the case of rejecting transactions with nonce that is queued; this is okay. Will be separately tested, both in nonce abstraction tests and in fee escalation tests.

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2023)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/starknet_mempool/src/mempool_test.rs` line 382 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2023#-OB_pUxtEwXNiCBjWwHs:-OB_pUxtEwXNiCBjWwHt:bnz1te0) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d7b287993065138a8880f0c4bb195d7121611e2/crates/starknet_mempool/src/mempool_test.rs#L382)):*
> ```XML
> 
>     // Test and assert: original transaction remains.
>     for tx_nonce in [0, 1] {
> ```

@ayeletstarkware, this case should fail fee escalation unit test (replacement of queued transaction).



_Code quote:_
```XML
1
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2023)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/starknet_mempool/src/mempool_test.rs` line 371 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2023#-OB_pfVI7wyjgWOpKr0k:-OB_pfVI7wyjgWOpKr0l:bu1j1vw) ([raw file](https://github.com/starkware-libs/sequencer/blob/81684fe8b89c2ff5231ff13f752f0c964e2e68d9/crates/starknet_mempool/src/mempool_test.rs#L371)):*
> ```XML
> 
> #[rstest]
> fn test_add_tx_lower_than_queued_nonce(mut mempool: Mempool) {
> ```

Will move to `flow_test.rs` next PR.



_Code quote:_
```XML
test_add_tx_lower_than_queued_nonce
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2023)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/starknet_mempool/src/mempool_test.rs` line 382 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2023#-OB_pUxtEwXNiCBjWwHs:-OBdbKOx8t92jL9gtO4z:bt07j8o) ([raw file](https://github.com/starkware-libs/sequencer/blob/7d7b287993065138a8880f0c4bb195d7121611e2/crates/starknet_mempool/src/mempool_test.rs#L382)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I think we should check the following scenario:
 The fee escalation flag is off, we receive a transaction with the queued nonce, and ensure it returns a DuplicateNonce error.
(made this change in both mempool and tests in a different PR, will attach it when ready)
WDYT?
</blockquote></details>

Restored this case; let's discuss the rest in your PR.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2023)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2023#-OBdrzTtCR851gSgKN9T:-OBdrzTtCR851gSgKN9U:b2ni2nk):*
fix

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:
update the reviewable's message as well

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2023#-:-OBe2EIOEte8-mqOgyGf:br3v6ni)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
