### PR TITLE
feat(blockifier): add get_syscall_gas_cost to versioned constants impl

### PR DESCRIPTION
**Pull request by Yonatan-Starkware**

### CODE REVIEW

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 347 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2188#-OC4KWFO9eH5317sz0VA:-OC4KWFO9eH5317sz0VB:bsu4nff) ([raw file](https://github.com/starkware-libs/sequencer/blob/86f183e91c91112e7d1b240d049a1f7a9e391577/crates/blockifier/src/versioned_constants.rs#L347)):*
> ```XML
>         let mut total_builtin_gas_cost: u64 = 0;
>         for (builtin, amount) in &execution_resources.builtin_instance_counter {
>             let builtin_cost = constant_gas_costs.get_builtin_gas_cost(builtin).unwrap_or(0);
> ```

for now, returning zero by default in the case of unsupported builtin. Would love to consider a better way to handle this error.

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants_test.rs` line 177 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2188#-OC4LEHM1JQSsAUGkL-d:-OC4LEHM1JQSsAUGkL-e:bgo8gwn) ([raw file](https://github.com/starkware-libs/sequencer/blob/86f183e91c91112e7d1b240d049a1f7a9e391577/crates/blockifier/src/versioned_constants_test.rs#L177)):*
> ```XML
>     assert_eq!(versioned_constants.get_syscall_gas_cost(&SyscallSelector::CallContract), 87650);
>     assert_eq!(versioned_constants.get_syscall_gas_cost(&SyscallSelector::Secp256k1Mul), 8143650);
>     assert_eq!(versioned_constants.get_syscall_gas_cost(&SyscallSelector::Sha256ProcessBlock), 841095);
> ```

will change the magic numbers to one of two options:
(1) named constants as in other tests
(2)the matching value in the GasCosts struct.

The problem with the first option is that it will require maintenance every time the values in the json will change.
The problem with the second option is that after we will delete the gas costs from the OsConstants as planned it will become a bug.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2188)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 347 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2188#-OC4KWFO9eH5317sz0VA:-OC7p7d-2E-7lW6bSuQv:by0igqn) ([raw file](https://github.com/starkware-libs/sequencer/blob/86f183e91c91112e7d1b240d049a1f7a9e391577/crates/blockifier/src/versioned_constants.rs#L347)):*
<details><summary><i>Previously, Yonatan-Starkware wrote…</i></summary><blockquote>

for now, returning zero by default in the case of unsupported builtin. Would love to consider a better way to handle this error.
</blockquote></details>

It's okay to panic. All builtins should be there.
___
*[`crates/blockifier/src/versioned_constants.rs` line 337 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2188#-OC7o729C0Q1HqIU3i4q:-OC7o72ABa-1aQTJuP9l:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/86f183e91c91112e7d1b240d049a1f7a9e391577/crates/blockifier/src/versioned_constants.rs#L337)):*
> ```XML
>     /// Calculates a syscall's gas costs from the os resources
>     pub fn get_syscall_gas_cost(&self, syscall_selector: &SyscallSelector) -> u64 {
>         let constant_gas_costs = &self.os_constants.gas_costs;
> ```





_Suggestion:_
```XML
 gas_costs 
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 343 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2188#-OC7oK1aCKvqtMTxYCs0:-OC7oK1bCvh5S_cm_Zr4:bwbxeqo) ([raw file](https://github.com/starkware-libs/sequencer/blob/86f183e91c91112e7d1b240d049a1f7a9e391577/crates/blockifier/src/versioned_constants.rs#L343)):*
> ```XML
>             .get(syscall_selector)
>             .expect("Fetching the execution resources of a syscall should not fail.");
>         let n_steps = std::cmp::max(u64_from_usize(execution_resources.n_steps), 100);
> ```

The max should be with `syscall_base_gas_cost`.
We should take the max at the end of the calculation. This will require further changes in python.
cc @meship-starkware 



_Suggestion:_
```XML
        // The minimum total cost is `syscall_base_gas_cost`, which is pre-charged by the compiler.
        let n_steps = std::cmp::max(u64_from_usize(execution_resources.n_steps), 100);
```

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 347 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2188#-OC4KWFO9eH5317sz0VA:-OCSRH5400T9wYu9ifgr:bs7wumb) ([raw file](https://github.com/starkware-libs/sequencer/blob/86f183e91c91112e7d1b240d049a1f7a9e391577/crates/blockifier/src/versioned_constants.rs#L347)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

It's okay to panic. All builtins should be there.
</blockquote></details>

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2188)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 343 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2188#-OC7oK1aCKvqtMTxYCs0:-OCTtZmD7AKH0mnguLR5:b-as3yau) ([raw file](https://github.com/starkware-libs/sequencer/blob/86f183e91c91112e7d1b240d049a1f7a9e391577/crates/blockifier/src/versioned_constants.rs#L343)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

this will break Python. Lets put in the Os_constants the number according to the calculation without the max and add the maximum where needed. @Yoni-Starkware WDYT?
</blockquote></details>

@meship-starkware why?  he is not using this func yet 
@Yonatan-Starkware please add my comment.
___
*[`crates/blockifier/src/versioned_constants.rs` line 335 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2188#-OCTsVgW8PXi4fVTRydn:-OCTsVgW8PXi4fVTRydo:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7b5bc8f23e173052bfb442dd17b5f5136f12697/crates/blockifier/src/versioned_constants.rs#L335)):*
> ```XML
>     }
> 
>     /// Calculates a syscall's gas costs from the os resources
> ```





_Suggestion:_
```XML
/// Calculates the syscall gas cost from the OS resources.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 346 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2188#-OCTtISf8apWaPj-hmWx:-OCTtISf8apWaPj-hmWy:b-vxa38p) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7b5bc8f23e173052bfb442dd17b5f5136f12697/crates/blockifier/src/versioned_constants.rs#L346)):*
> ```XML
>         let n_memory_holes = u64_from_usize(execution_resources.n_memory_holes);
>         let mut total_builtin_gas_cost: u64 = 0;
>         for (builtin, amount) in &execution_resources.builtin_instance_counter {
> ```

Use rust style instead (iter + map + sum)



_Code quote:_
```XML
        let mut total_builtin_gas_cost: u64 = 0;
        for (builtin, amount) in &execution_resources.builtin_instance_counter {
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 349 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2188#-OCTt42vBUBKBm_BkcJo:-OCTt42vBUBKBm_BkcJp:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7b5bc8f23e173052bfb442dd17b5f5136f12697/crates/blockifier/src/versioned_constants.rs#L349)):*
> ```XML
>             let builtin_cost = gas_costs
>                 .get_builtin_gas_cost(builtin)
>                 .unwrap_or_else(|err| panic!("Failed to get gas cost: {}", err));
> ```





_Suggestion:_
```XML
(|err| panic!("Failed to get gas cost: {}.",
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2188)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants_test.rs` line 177 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2188#-OC4LEHM1JQSsAUGkL-d:-OCTu3iK1WAW65FQ4yS5:b-hfghm4) ([raw file](https://github.com/starkware-libs/sequencer/blob/86f183e91c91112e7d1b240d049a1f7a9e391577/crates/blockifier/src/versioned_constants_test.rs#L177)):*
<details><summary><i>Previously, Yonatan-Starkware wrote…</i></summary><blockquote>

for now the function is just there, nothing call it. so by adding the test i verify that it works correctly, and prevent the error of it being unused
</blockquote></details>

Sounds good
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 172 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2188#-OCTtw2zDiiMTvQAtHwx:-OCTtw2zDiiMTvQAtHwy:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7b5bc8f23e173052bfb442dd17b5f5136f12697/crates/blockifier/src/versioned_constants_test.rs#L172)):*
> ```XML
> 
> #[test]
> fn test_correct_syscall_gas_cost_calculation() {
> ```





_Suggestion:_
```XML
fn test_syscall_gas_cost_calculation() {
```

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 349 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2188#-OCTt42vBUBKBm_BkcJo:-OCTvjwx03kWM8yWu6fN:b-it855g) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7b5bc8f23e173052bfb442dd17b5f5136f12697/crates/blockifier/src/versioned_constants.rs#L349)):*
> ```XML
>             let builtin_cost = gas_costs
>                 .get_builtin_gas_cost(builtin)
>                 .unwrap_or_else(|err| panic!("Failed to get gas cost: {}", err));
> ```

there is already a coma in the error mesegge itself.

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 349 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2188#-OCTt42vBUBKBm_BkcJo:-OCTvwF2AkhhSN9MPfAA:bgudzew) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7b5bc8f23e173052bfb442dd17b5f5136f12697/crates/blockifier/src/versioned_constants.rs#L349)):*
<details><summary><i>Previously, Yonatan-Starkware wrote…</i></summary><blockquote>

there is already a coma in the error mesegge itself.
</blockquote></details>

the messege that goes into the curly braces

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2188)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 343 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2188#-OCTy5Ix1YV2JnaiZC_v:-OCTy5Iy1ixyZPJDmFON:bb9jxvi) ([raw file](https://github.com/starkware-libs/sequencer/blob/7bf221e1832348313a93edcb73ef8fabca95384c/crates/blockifier/src/versioned_constants.rs#L343)):*
> ```XML
>             .get(syscall_selector)
>             .expect("Fetching the execution resources of a syscall should not fail.");
>         // The minimum total cost is `syscall_base_gas_cost`, which is pre-charged by the compiler.
> ```

Move the message down to the cmp



_Code quote:_
```XML
// The minimum total cost is `syscall_base_gas_cost`, which is pre-charged by the compiler.
```

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2188)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @avi-starkware and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 343 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2188#-OC7oK1aCKvqtMTxYCs0:-OCbHFhv9_XXZOR0N3G-:b-ane0nn) ([raw file](https://github.com/starkware-libs/sequencer/blob/86f183e91c91112e7d1b240d049a1f7a9e391577/crates/blockifier/src/versioned_constants.rs#L343)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@meship-starkware why?  he is not using this func yet 
@Yonatan-Starkware please add my comment.
</blockquote></details>

Oh, I see; I'll add a Monday task to change the Python accordingly.

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2188)* status: all files reviewed, 4 unresolved discussions (waiting on @avi-starkware and @Yonatan-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2188#-:-OClneaxBbf1WatgcVLd:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @Yonatan-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2188)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Pull request merged**
