### PR TITLE
test(native_blockifier): move alias constants to python

### PR DESCRIPTION
**Pull request by yoavGrs**

### CODE REVIEW

**Comment by yoavGrs** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2675?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2675** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2675?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2675?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2674** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2674?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2535** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2535?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2534** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2534?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2675)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/native_blockifier/src/lib.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2675#-OE9geIh1La0Gure08Kh:-OE9geIi11ynwIxyVxWf:b-usw7j2) ([raw file](https://github.com/starkware-libs/sequencer/blob/298fc708fc8790f6a4eb27d87eca2c4a2934c8cf/crates/native_blockifier/src/lib.rs#L77)):*
> ```XML
>         u16::from(*MAX_NON_COMPRESSED_CONTRACT_ADDRESS),
>     )?;
>     py_module.add("INITIAL_AVAILABLE_ALIAS", u16::from(*MIN_VALUE_FOR_ALIAS_ALLOC))?;
> ```

What is that doing?



_Code quote:_
```XML
    py_module.add("ALIAS_COUNTER_STORAGE_KEY", u16::from(*ALIAS_COUNTER_STORAGE_KEY))?;
    py_module.add(
        "MAX_NON_COMPRESSED_CONTRACT_ADDRESS",
        u16::from(*MAX_NON_COMPRESSED_CONTRACT_ADDRESS),
    )?;
    py_module.add("INITIAL_AVAILABLE_ALIAS", u16::from(*MIN_VALUE_FOR_ALIAS_ALLOC))?;
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2675)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2675#-OEIwV4e1hGzVpIe6BgF:-OEIwV4e1hGzVpIe6BgG:b-jd0mdb) (no related file):*
The python side:
https://reviewable.io/reviews/starkware-industries/starkware/36464
___
*[`crates/native_blockifier/src/lib.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2675#-OE9geIh1La0Gure08Kh:-OEIwXHq5Uwjo8jRpy81:b-s76cr4) ([raw file](https://github.com/starkware-libs/sequencer/blob/298fc708fc8790f6a4eb27d87eca2c4a2934c8cf/crates/native_blockifier/src/lib.rs#L77)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

What is that doing?
</blockquote></details>

Adds attributes to the `native_blockifier` object in python.

**Review by nimrod-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2675#-:-OEJ-kB2Bp60EqnxZU0Q:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2675#-:-OEnyUSH8U-_vpOEhDGT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
