### PR TITLE
feat(block_hash): add l2 gas to the block hash

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/683)

### CODE REVIEW

**Review by aner-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/683)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @TzahiTaub and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/683#-O6u0_Ra1Xq0q7uWYKPG:-O6u0_Ra1Xq0q7uWYKPH:b-5tug8g) (no related file):*
Please add a link to the python side.

___
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/683#-O6u14Ab9K7unDDjUZ6b:-O6u14Ab9K7unDDjUZ6c:b77hbet) ([raw file](https://github.com/starkware-libs/sequencer/blob/cccaddf63b0667a2f01c5feda4f64f5af92f2fd2/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L48)):*
> ```XML
>         }
>     }
> }
> ```

Was this how it was done previously? (E.g., when `l1_data_gas` was added)



_Code quote:_
```XML
#[allow(non_camel_case_types)]
pub enum BlockHashVersion {
    VO_13_2,
    VO_13_3,
}

impl BlockHashVersion {
    pub fn get_starknet_version(&self) -> StarknetVersion {
        match self {
            BlockHashVersion::VO_13_2 => StarknetVersion("0.13.2".to_owned()),
            BlockHashVersion::VO_13_3 => StarknetVersion("0.13.3".to_owned()),
        }
    }
}
```
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/683#-O6txyAd6OCn00Gt2KKO:-O6txyAd6OCn00Gt2KKP:bd9drlc) ([raw file](https://github.com/starkware-libs/sequencer/blob/e5d9324edbca7234bb3e8945c7079062fcf9d586/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L89)):*
> ```XML
>         calculate_block_commitments(&transactions_data, &state_diff, block_header.l1_da_mode);
> 
>     let expected_hash = felt!("0x061e4998d51a248f1d0288d7e17f6287757b0e5e6c5e1e58ddf740616e312134");
> ```

This is not a breaking change, right? So please don't make code changes and modify the regression test result in the same PR (either add a new test and delete the original test in the next PR, modify the test in a following PR, or write the changes so that they don't override the original test result).



_Code quote:_
```XML
  let expected_hash = felt!("0x061e4998d51a248f1d0288d7e17f6287757b0e5e6c5e1e58ddf740616e312134");
```

**Review by aner-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/683)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @TzahiTaub and @yoavGrs)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/683#-O6txyAd6OCn00Gt2KKO:-O6vax415-qi8KbFtvbX:b7t6qlk) ([raw file](https://github.com/starkware-libs/sequencer/blob/e5d9324edbca7234bb3e8945c7079062fcf9d586/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L89)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Done.
</blockquote></details>

So why did the hash change? It looks like it's already taking `l2_gas_price` into account. Maybe the ordering isn't as we expect?

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/683)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/683#-O6txyAd6OCn00Gt2KKO:-O6ypzOw4P6DQ7yV6Dia:b-6bjn72) ([raw file](https://github.com/starkware-libs/sequencer/blob/e5d9324edbca7234bb3e8945c7079062fcf9d586/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L89)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

So why did the hash change? It looks like it's already taking `l2_gas_price` into account. Maybe the ordering isn't as we expect?
</blockquote></details>

The starknet version in the test (10) is greater than 0.13.3

**Review by aner-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/683)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/683#-O6txyAd6OCn00Gt2KKO:-O6z4dUvA7z2pqJHi78S:bs3z0eg) ([raw file](https://github.com/starkware-libs/sequencer/blob/e5d9324edbca7234bb3e8945c7079062fcf9d586/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L89)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

The starknet version in the test (10) is greater than 0.13.3
</blockquote></details>

OK, then please verify locally that for version 0.13.2 the hash doesn't change for the changes in this PR.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/683)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub and @yoavGrs)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 101 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/683#-O6v0fjG3DFfQuEsLdNo:-O6v0fjH0h-FyW2_GiNQ:b-8zhaee) ([raw file](https://github.com/starkware-libs/sequencer/blob/06d0b415e8d73bc343305d3a55ee4fdc8ceea0d4/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L101)):*
> ```XML
>                     .ge(&STARKNET_VERSION_V0_13_3)
>                     .then_some(header.l2_gas_price.price_in_fri.0.into())
>             })
> ```

I don't like how the check is duplicated
1. Is there an option to pass an *iterator* to the `chain_if_fn` method? then you can check once and pass L2 price in wei and fri in one call
2. If not, please define a boolean `include_l2_gas_prices` above and use it twice



_Code quote:_
```XML
            .chain_if_fn(|| {
                header
                    .starknet_version
                    .ge(&STARKNET_VERSION_V0_13_3)
                    .then_some(header.l2_gas_price.price_in_wei.0.into())
            })
            .chain_if_fn(|| {
                header
                    .starknet_version
                    .ge(&STARKNET_VERSION_V0_13_3)
                    .then_some(header.l2_gas_price.price_in_fri.0.into())
            })
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/683)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 101 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/683#-O6v0fjG3DFfQuEsLdNo:-O6zTTIn7AYN5pDO_xSF:b-lpoh0b) ([raw file](https://github.com/starkware-libs/sequencer/blob/06d0b415e8d73bc343305d3a55ee4fdc8ceea0d4/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L101)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't like how the check is duplicated
1. Is there an option to pass an *iterator* to the `chain_if_fn` method? then you can check once and pass L2 price in wei and fri in one call
2. If not, please define a boolean `include_l2_gas_prices` above and use it twice
</blockquote></details>

1 - done.
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator_test.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/683#-O6txyAd6OCn00Gt2KKO:-O6zKnTq5NfZVJGcAlu2:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e5d9324edbca7234bb3e8945c7079062fcf9d586/crates/starknet_api/src/block_hash/block_hash_calculator_test.rs#L89)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

OK, then please verify locally that for version 0.13.2 the hash doesn't change for the changes in this PR.
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/683#-:-O6zjxhE8jOABUdJKa2M:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/683)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
