### PR TITLE
chore(starknet_batcher): set block timestamp in build block input

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2342)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @ArniStarkware)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2342#-OD0KPqO50Lv62-9bVrd:-OD0KPqO50Lv62-9bVre:b-75a3te) ([raw file](https://github.com/starkware-libs/sequencer/blob/3bb7ed9143aad42386c36ad09af6b9b8d4f5cf0c/crates/starknet_batcher/src/block_builder.rs#L321)):*
> ```XML
>                     .try_into()
>                     .map_err(BlockBuilderError::BadTimestamp)?,
>             ),
> ```

why did you change it? 
I think the previous version was easier to read.

This code will be deleted anyway, right?



_Code quote:_
```XML
            block_timestamp: BlockTimestamp(
                chrono::Utc::now()
                    .timestamp()
                    .try_into()
                    .map_err(BlockBuilderError::BadTimestamp)?,
            ),
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2342#-OD0KhfA31Ueb9h9EB6C:-OD0KhfA31Ueb9h9EB6D:b-ssrsno) ([raw file](https://github.com/starkware-libs/sequencer/blob/3bb7ed9143aad42386c36ad09af6b9b8d4f5cf0c/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L163)):*
> ```XML
>                 gas_prices: TEMPORARY_GAS_PRICES,
>                 block_timestamp: BlockTimestamp(
>                     now.timestamp().try_into().expect("Failed to convert timestamp"),
> ```

same for the next change.



_Suggestion:_
```XML
chrono::Utc::now().timestamp().try_into().expect("Failed to convert timestamp"),
```

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2342)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2342#-OD0l9jB-Q7g5t_GwUm8:-OD0l9jCDzRvuF4Zrpwp:bcgjvre) ([raw file](https://github.com/starkware-libs/sequencer/blob/6158a580ac460f98b1c3cdb928cc416ed6d63ab8/crates/starknet_batcher/src/block_builder.rs#L49)):*
> ```XML
> pub enum BlockBuilderError {
>     #[error(transparent)]
>     BadTimestamp(#[from] std::num::TryFromIntError),
> ```

Why this change?

**Comment by ArniStarkware** [comment]
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2342#-OD0KhfA31Ueb9h9EB6C:-OD0o6T63kOqYnDa7YBr:bvq6wtn) ([raw file](https://github.com/starkware-libs/sequencer/blob/3bb7ed9143aad42386c36ad09af6b9b8d4f5cf0c/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L163)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

same for the next change.
</blockquote></details>

So, Should I have two invocations of `chorono::Utc::now()` five lines apart? Once for `deadline` and once for `block_timestamp`.

In my opinion, it is bad - as these will be slightly different from each other - based on how long these lines take to execute.

**Review by ArniStarkware — COMMENTED** [review]
> Dismissed @alonh5 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2342)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/block_builder.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2342#-OD0l9jB-Q7g5t_GwUm8:-OD0pQP66u_K-IKbCT2o:b-jepbuy) ([raw file](https://github.com/starkware-libs/sequencer/blob/6158a580ac460f98b1c3cdb928cc416ed6d63ab8/crates/starknet_batcher/src/block_builder.rs#L49)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

As @Yael-Starkware  pointed out - this will be deleted by the next PR anyway.
Reverted.
___
*[`crates/starknet_batcher/src/block_builder.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2342#-OD0KPqO50Lv62-9bVrd:-OD0oq4Z1DK5cN5xIGjn:bg9o8wo) ([raw file](https://github.com/starkware-libs/sequencer/blob/3bb7ed9143aad42386c36ad09af6b9b8d4f5cf0c/crates/starknet_batcher/src/block_builder.rs#L321)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why did you change it? 
I think the previous version was easier to read.

This code will be deleted anyway, right?
</blockquote></details>

1. Yes - the code will be deleted anyway. Reverted.
2. I think it is bad that a generic `TryFromIntError` is always converted to a `BadTimestamp`. (Again - in theory), what happens if another conversion from integer happens in the scope of Block-build, but has nothing to do with timestamp?

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2342)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @alonh5)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2342)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
