### PR TITLE
chore: fix gas price warning in integration test state reader

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#1532** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1532?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
Thank you @Yael-Starkware .

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1532#-:-O9njahP00GCRJSGSZlc:b-rn9rxy)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alonh5 and @Itay-Tsabary-Starkware)

**Review by ArniStarkware — COMMENTED** [review]
These values were originaly added in #1067. 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1532#-:-O9o1Dgu9Vtu-ecO072n:buy613p)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alonh5 and @Itay-Tsabary-Starkware)

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1532#-:-O9o7uMKD2MSn5EUfbWp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
