### PR TITLE
refactor(consensus): merge propose into build_proposal and remove propose fn from context trait

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1431)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1431)* status: all files reviewed, 4 unresolved discussions (waiting on @asmaastarkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1431#-O9FWAcwAiiF3VZGFeBU):*
also mention the build_proposal change



_Code quote:_
```
New commits in r1 on 15/10/2024 at 14:18:
- 44f6081: refactor(consensus): remove propose from context trait
```
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1431#-O9FW7HF0WhKvFrUHIXD:-O9FW7HF0WhKvFrUHIXE:b-8zuwaf) ([raw file](https://github.com/starkware-libs/sequencer/blob/44f608136ce6e2ea46bb65b44bf61bccc660babd/crates/sequencing/papyrus_consensus/src/manager_test.rs#L51)):*
> ```XML
>         async fn build_proposal(
>             &mut self,
>             height: BlockNumber,
> ```

part of init, remove



_Code quote:_
```XML
            height: BlockNumber,
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1431#-O9FXTCbCMthSIrWPPj9:-O9FXTCbCMthSIrWPPjA:brwmv6g) ([raw file](https://github.com/starkware-libs/sequencer/blob/44f608136ce6e2ea46bb65b44bf61bccc660babd/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs#L39)):*
> ```XML
> 
>     let fin = fin_receiver.await.unwrap();
>     assert_eq!(fin, block.header.block_hash);
> ```

This test now seems to pay no attention to the content that the context broadcasts out to the network. I want that to also be tests. That we indeed broadcast the correct thing. Please find a way to check this (may need to talk to Shahak/Eitan)



_Code quote:_
```XML
#[tokio::test]
async fn build_proposal() {
    let (block, mut papyrus_context, _mock_network, _) = test_setup();
    let block_number = block.header.block_header_without_hash.block_number;
    let proposal_init = ProposalInit {
        height: block_number,
        round: 0,
        proposer: ContractAddress::default(),
        valid_round: None,
    };
    let fin_receiver =
        papyrus_context.build_proposal(block_number, proposal_init, Duration::MAX).await;

    let fin = fin_receiver.await.unwrap();
    assert_eq!(fin, block.header.block_hash);
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1431#-O9FXojW0_yLM5xE9z6O:-O9FXojW0_yLM5xE9z6P:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/44f608136ce6e2ea46bb65b44bf61bccc660babd/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L211)):*
> ```XML
>                 // TODO(matan): Convert to protobuf and make sure this isn't too large for a single
>                 // proto message (could this be a With adapter added to the channel in `new`?).
>                 // TODO: Broadcast the transactions to the network.
> ```





_Suggestion:_
```XML
                // TODO: Broadcast the transactions to the network.
                // TODO(matan): Convert to protobuf and make sure this isn't too large for a single
                // proto message (could this be a With adapter added to the channel in `new`?).
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1431)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1431#-O9FXTCbCMthSIrWPPj9:-O9e25pYDuBWxShzWD1z:b-2t1ow) ([raw file](https://github.com/starkware-libs/sequencer/blob/44f608136ce6e2ea46bb65b44bf61bccc660babd/crates/sequencing/papyrus_consensus_orchestrator/src/papyrus_consensus_context_test.rs#L39)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This test now seems to pay no attention to the content that the context broadcasts out to the network. I want that to also be tests. That we indeed broadcast the correct thing. Please find a way to check this (may need to talk to Shahak/Eitan)
</blockquote></details>

Shahak/Eitan unavailable - added TODO

**Review by matan-starkware — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1431)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Review by asmaastarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1431)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
