### PR TITLE
build(blockifier_reexecution): add dummy consecutive state readers

### PR DESCRIPTION
**Pull request by aner-starkware**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1703)* status: all files reviewed, 8 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXgVfI6lxiI-qwU3xc:-OAXgVfI6lxiI-qwU3xd:b45u6j2) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L289)):*
> ```XML
> }
> 
> pub type StarknetContractClassMapping = HashMap<ClassHash, StarknetContractClass>;
> ```

docstring with why this type is needed?



_Code quote:_
```XML
pub type StarknetContractClassMapping = HashMap<ClassHash, StarknetContractClass>;
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXgZVb1d8mWury439r:-OAXgZVb1d8mWury439s:b-ox9a22) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L291)):*
> ```XML
> pub type StarknetContractClassMapping = HashMap<ClassHash, StarknetContractClass>;
> 
> pub struct DummyStateReader(StateMaps, StarknetContractClassMapping);
> ```

1. named values, not a tuple struct
2. please rename, don't use the word "dummy" - it's not a mock object, it is a real object. maybe `Offline` or `Local` instead of `Dummy`?
3. why is `StarknetContractClassMapping` needed as an intermediate type? just for ease of use?



_Suggestion:_
```XML
pub struct DummyStateReader {
    contract_classes: HashMap<ClassHash, StarknetContractClass>,
    state_maps: StateMaps
}
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXhJYq-SRmZKXqjiAM:-OAXhJYq-SRmZKXqjiAN:b-g1jf0e) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L291)):*
> ```XML
> pub type StarknetContractClassMapping = HashMap<ClassHash, StarknetContractClass>;
> 
> pub struct DummyStateReader(StateMaps, StarknetContractClassMapping);
> ```

I prefer you separate between the struct containing all the data required,
and the state reader that uses the data, like we said.
that way you won't need a `new` function; later you can implement a `from_json` method when you want to read the data
```
// no "new" required, fields are public
pub struct ReexecutionData { pub s: StateMaps, pub c: StarknetContractClassMapping };
// no "new" required; "from_json" optional
pub struct OfflineStateReader(pub ReexecutionData);
```
WDYT?
non-blocking



_Code quote:_
```XML
pub struct DummyStateReader(StateMaps, StarknetContractClassMapping);
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 302 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXiQ9X-QYpq2xqBlgb:-OAXiQ9X-QYpq2xqBlgc:b-slavqy) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L302)):*
> ```XML
>             Some(val) => Ok(*val),
>             None => Err(StateError::StateReadError("Missing Value.".to_string())),
>         }
> ```

should be equivalent
if you need to return T and this returns &T, you can try like this:
```
        Ok(*self.0.storage.get(&(contract_address, key)).ok_or(
            StateError::StateReadError("Missing Value.".to_string())
        )?)
```

same comment for `get_nonce_at`, `get_class_hash_at` and `get_compiled_class_hash`



_Suggestion:_
```XML
        self.0.storage.get(&(contract_address, key)).ok_or(
            StateError::StateReadError("Missing Value.".to_string())
        )
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 334 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXitECD4q9VaVlNVKc:-OAXitECD4q9VaVlNVKd:bqy33e6) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L334)):*
> ```XML
>             None => Err(StateError::StateReadError("Missing Value.".to_string())),
>         }
>     }
> ```

each time you return `Missing value` please also stringify the key(s) that are missing



_Code quote:_
```XML
        match self.0.storage.get(&(contract_address, key)) {
            Some(val) => Ok(*val),
            None => Err(StateError::StateReadError("Missing Value.".to_string())),
        }
    }

    fn get_nonce_at(&self, contract_address: ContractAddress) -> StateResult<Nonce> {
        match self.0.nonces.get(&contract_address) {
            Some(val) => Ok(*val),
            None => Err(StateError::StateReadError("Missing Value.".to_string())),
        }
    }

    fn get_class_hash_at(&self, contract_address: ContractAddress) -> StateResult<ClassHash> {
        match self.0.class_hashes.get(&contract_address) {
            Some(val) => Ok(*val),
            None => Err(StateError::StateReadError("Missing Value.".to_string())),
        }
    }

    fn get_compiled_contract_class(
        &self,
        class_hash: ClassHash,
    ) -> StateResult<BlockifierContractClass> {
        match self.get_contract_class(&class_hash)? {
            Sierra(sierra) => sierra_to_contact_class_v1(sierra),
            Legacy(legacy) => legacy_to_contract_class_v0(legacy),
        }
    }

    fn get_compiled_class_hash(&self, class_hash: ClassHash) -> StateResult<CompiledClassHash> {
        match self.0.compiled_class_hashes.get(&class_hash) {
            Some(val) => Ok(*val),
            None => Err(StateError::StateReadError("Missing Value.".to_string())),
        }
    }
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 362 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXgyFD-SSbDbXGbrQB:-OAXgyFD-SSbDbXGbrQC:bhhc2rj) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L362)):*
> ```XML
>             None => Err(StateError::StateReadError("Missing Value.".to_string())),
>         }
>     }
> ```

aren't these methods required in the rpc state reader as well?
will they be in Aviv's trait?



_Code quote:_
```XML
    pub fn get_transaction_executor(
        self,
        block_context_next_block: BlockContext,
        transaction_executor_config: Option<TransactionExecutorConfig>,
    ) -> ReexecutionResult<TransactionExecutor<DummyStateReader>> {
        Ok(TransactionExecutor::<DummyStateReader>::new(
            CachedState::new(self),
            block_context_next_block,
            transaction_executor_config.unwrap_or_default(),
        ))
    }

    pub fn get_contract_class(&self, class_hash: &ClassHash) -> StateResult<StarknetContractClass> {
        match self.1.get(class_hash) {
            Some(contract_class) => Ok(contract_class.clone()),
            None => Err(StateError::StateReadError("Missing Value.".to_string())),
        }
    }
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 366 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXjZsR6-NnZnexhK4r:-OAXjZsR6-NnZnexhK4s:b97648d) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L366)):*
> ```XML
> 
> pub struct OfflineConsecutiveStateReaders {
>     pub dummy_state_reader: DummyStateReader,
> ```

state reader for which block?
I like how you have `next` in the other fields, add `next` or `prev` to this var name



_Code quote:_
```XML
dummy_state_reader: DummyStateReader,
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 377 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXjh2X0hxHmEDIDJCh:-OAXjh2X0hxHmEDIDJCi:bgbcrlw) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L377)):*
> ```XML
>         // TODO(Aner): Create a struct containing the following parameters.
>         state_maps: StateMaps,
>         contract_class_mapping: StarknetContractClassMapping,
> ```

see above... can be a single arg already in this PR



_Code quote:_
```XML
        // TODO(Aner): Create a struct containing the following parameters.
        state_maps: StateMaps,
        contract_class_mapping: StarknetContractClassMapping,
```

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXgZVb1d8mWury439r:-OAXrMFN8AXUiVQZWciu:bkblitb) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L291)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. named values, not a tuple struct
2. please rename, don't use the word "dummy" - it's not a mock object, it is a real object. maybe `Offline` or `Local` instead of `Dummy`?
3. why is `StarknetContractClassMapping` needed as an intermediate type? just for ease of use?
</blockquote></details>

Regarding 3, yes, for ease of use, it's used in several places, so it makes it more convenient.

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXhJYq-SRmZKXqjiAM:-OAXrnaGBe4OUQ8CcMi6:bbwkxc3) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L291)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I prefer you separate between the struct containing all the data required,
and the state reader that uses the data, like we said.
that way you won't need a `new` function; later you can implement a `from_json` method when you want to read the data
```
// no "new" required, fields are public
pub struct ReexecutionData { pub s: StateMaps, pub c: StarknetContractClassMapping };
// no "new" required; "from_json" optional
pub struct OfflineStateReader(pub ReexecutionData);
```
WDYT?
non-blocking
</blockquote></details>

This is an "inner" struct, the struct that should read from JSONs is the `OfflineConsecutiveStateReaders`

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1703)* status: all files reviewed, 8 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXhJYq-SRmZKXqjiAM:-OAXtbLa3Uju0T4y2zYM:blfdac6) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L291)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

This is an "inner" struct, the struct that should read from JSONs is the `OfflineConsecutiveStateReaders`
</blockquote></details>

ah... good point.
ok, just use named fields
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXgZVb1d8mWury439r:-OAXtyfEE6L7vCDaoNkr:b2zglgb) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L291)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Regarding 3, yes, for ease of use, it's used in several places, so it makes it more convenient.
</blockquote></details>

ok, sgtm.
1+2 still relevant

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1703)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXgVfI6lxiI-qwU3xc:-OAYE1bJ43D9HC8GVRwx:bfafji3) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L289)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

docstring with why this type is needed?
</blockquote></details>

It's just for convenience... Is a docstring really necessary?
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXgZVb1d8mWury439r:-OAYE85D5PDW9ubZP6R-:bryo501) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L291)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ok, sgtm.
1+2 still relevant
</blockquote></details>

1. Done.
2. It is a dummy, it mostly replies as in its storage... (except the functions that compile, but those are code duplications that should be moved into the trait IMO)
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 302 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXiQ9X-QYpq2xqBlgb:-OAYE_Qt3HR3KnXslnWH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L302)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

should be equivalent
if you need to return T and this returns &T, you can try like this:
```
        Ok(*self.0.storage.get(&(contract_address, key)).ok_or(
            StateError::StateReadError("Missing Value.".to_string())
        )?)
```

same comment for `get_nonce_at`, `get_class_hash_at` and `get_compiled_class_hash`
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 334 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXitECD4q9VaVlNVKc:-OAYEaW307RNFb5LnFKV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L334)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

each time you return `Missing value` please also stringify the key(s) that are missing
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 362 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXgyFD-SSbDbXGbrQB:-OAYAYBzCKtiTL-Zeqij:bjzt6kr) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L362)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

aren't these methods required in the rpc state reader as well?
will they be in Aviv's trait?
</blockquote></details>

Yes, they should be (or at least the second one).
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 366 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXjZsR6-NnZnexhK4r:-OAYDtM015ag94ZaSkbS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L366)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

state reader for which block?
I like how you have `next` in the other fields, add `next` or `prev` to this var name
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 377 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXjh2X0hxHmEDIDJCh:-OAYE-Ld9x8Ch8qku2lx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L377)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above... can be a single arg already in this PR
</blockquote></details>

Done.

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 362 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXgyFD-SSbDbXGbrQB:-OAj6OaY8OeW6KQaC5gZ:b30nfd8) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L362)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Yes, they should be (or at least the second one).
</blockquote></details>

The second one does exist in the trait, but it has the wrong signature. I guess that's why it's also not implemented in TestStateReader in the correct place.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1703)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 362 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXgyFD-SSbDbXGbrQB:-OAlL_gL7NozqxIDMPrs:ba3dkgu) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L362)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

It's in this PR: https://reviewable.io/reviews/starkware-libs/sequencer/1736
</blockquote></details>

rebase and implement the function as part of the trait implementation?

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1703)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 362 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXgyFD-SSbDbXGbrQB:-OAlMyUb1r1d_YUmrdvc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L362)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

rebase and implement the function as part of the trait implementation?
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1703)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXgZVb1d8mWury439r:-OAl9o099XsKpekZeqvl:bl9b2x1) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L291)):*
> It is a dummy

I don't think `dummy` is a well-defined term. If you mean it like "trivial", please rename to `Trivial`, but I think `Local` or `Offline` is much better because it indicates why this object is useful (in the context of reexecution, we have "RPC" and "X" - makes sense that "X" is "Offline").
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 362 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXgyFD-SSbDbXGbrQB:-OAlB6YQ558OcYqalhFs:b-4mn7z3) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L362)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

The second one does exist in the trait, but it has the wrong signature. I guess that's why it's also not implemented in TestStateReader in the correct place.
</blockquote></details>

is it already merged?
can you fix it in this PR? (fix the signature on the trait, and implement this method as part of the trait impl on the DummyStateReader)

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1703)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXgZVb1d8mWury439r:-OAlD7mt6VV4QyHmN-DA:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L291)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

> It is a dummy

I don't think `dummy` is a well-defined term. If you mean it like "trivial", please rename to `Trivial`, but I think `Local` or `Offline` is much better because it indicates why this object is useful (in the context of reexecution, we have "RPC" and "X" - makes sense that "X" is "Offline").
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 362 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-OAXgyFD-SSbDbXGbrQB:-OAlCaptCr7xacb_ce0F:bspi26) ([raw file](https://github.com/starkware-libs/sequencer/blob/1bec7fc20669edffc86fc81aaf1c7355851662ee/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L362)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is it already merged?
can you fix it in this PR? (fix the signature on the trait, and implement this method as part of the trait impl on the DummyStateReader)
</blockquote></details>

It's in this PR: https://reviewable.io/reviews/starkware-libs/sequencer/1736

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1703#-:-OAlR91t5VfGji1AhQdp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1703)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
