### PR TITLE
refactor(mempool): remove an add_tx redundant test

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This test is already covered in `test_add_tx`. See the second and the third txs.

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 296 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9jRtUC5zEn6SUNTcX_:-O9jRtUC5zEn6SUNTcXa:b-s14afm) ([raw file](https://github.com/starkware-libs/sequencer/blob/c242780b99e6e2674956c4cf6b3ad910b89591e9/crates/mempool/src/mempool_test.rs#L296)):*
> ```XML
>         add_tx_input!(tip: 50, tx_hash: 1, sender_address: "0x0", tx_nonce: 0, account_nonce: 0),
>         add_tx_input!(tip: 100, tx_hash: 2, sender_address: "0x1", tx_nonce: 1, account_nonce: 1),
>         add_tx_input!(tip: 80, tx_hash: 3, sender_address: "0x2", tx_nonce: 2, account_nonce: 2),
> ```

Covered by these two transactions.



_Code quote:_
```XML
        add_tx_input!(tip: 100, tx_hash: 2, sender_address: "0x1", tx_nonce: 1, account_nonce: 1),
        add_tx_input!(tip: 80, tx_hash: 3, sender_address: "0x2", tx_nonce: 2, account_nonce: 2),
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9jS0kqA1RIsIWlhOA9:-O9jS0kqA1RIsIWlhOAA:b-y0q7tp) (no related file):*
The deleted test is already covered in `test_add_tx`. See the second and the third txs.

___

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9mt_6tEPFrLrGaaOYS):*
fix



_Code quote:_
```
test_add_tx_account_state_fills_nonce_gap
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9mt_6tEPFrLrGaaOYS):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

fix
</blockquote></details>

Nice, updated.

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-:-O9n66dL9l9iDa1wvpRg:bnfp4nl)* status: all files reviewed, 2 unresolved discussions

**Review by elintul — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9jS0kqA1RIsIWlhOA9:-O9nHY9e0WRZoadEpSIX:by6hab2) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

The deleted test is already covered in `test_add_tx`. See the second and the third txs.
</blockquote></details>

Not sure it should be deleted: this is a dedicated test, while we can't be sure `test_add_tx` will continue checking this scenario without declaring itself as such.

___

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9jS0kqA1RIsIWlhOA9:-O9nQuH46mcW5tDJ8-Dw:b-fmgymi) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure it should be deleted: this is a dedicated test, while we can't be sure `test_add_tx` will continue checking this scenario without declaring itself as such.
</blockquote></details>

I changed the test's name to clearly describe what it checks.

___
___
*[`crates/mempool/src/mempool_test.rs` line 287 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9nRC_TB0BTGOiJ1gUp:-O9nRC_TB0BTGOiJ1gUq:b2ro36u) ([raw file](https://github.com/starkware-libs/sequencer/blob/5b043051f084ffe39a3e846b3f222fea61fad9f1/crates/mempool/src/mempool_test.rs#L287)):*
> ```XML
> 
> #[rstest]
> fn test_add_tx_insertion_sorted_by_priority(mut mempool: Mempool) {
> ```

I've added "insertion" as the `add_tx` itself doesn't sort according to priority - the queue sorts it.
wdyt?



_Code quote:_
```XML
test_add_tx_insertion_sorted_by_priority
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 300 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9nYR4r-LOhZv8rWC01:-O9nYR4r-LOhZv8rWC02:b4sz77h) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab16d8c4a0309f58e1f428efc2d4945d7a30d96a/crates/mempool/src/mempool_test.rs#L300)):*
> ```XML
>     }
> 
>     // TODO(Ayelet): Consider share this code.
> ```

I've consulted Ayelet. It seems that this function is not used in other places.



_Code quote:_
```XML
// TODO(Ayelet): Consider share this code.
```

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 309 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9xLcTEDMUkP9z9-wQN:-O9xLcTEDMUkP9z9-wQO:bpk3o5d) ([raw file](https://github.com/starkware-libs/sequencer/blob/989b5b9ced4f9f93797e1f2c42bb1a5fcb457d5a/crates/mempool/src/mempool_test.rs#L309)):*
> ```XML
>     let expected_pool_txs = add_tx_inputs.into_iter().map(|input| input.tx);
>     let expected_mempool_content = MempoolContentBuilder::new()
>         .with_pool(expected_pool_txs)
> ```

Why don't we want to verify the transactions are inserted into the pool?



_Code quote:_
```XML
.with_pool(expected_pool_txs)
```
___
*[`crates/mempool/src/mempool_test.rs` line 309 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9xMq3B74NvTC4mD3gU:-O9xMq3B74NvTC4mD3gV:bzd89ca) ([raw file](https://github.com/starkware-libs/sequencer/blob/5282d6891300d41c4e60ff7705ee66cd10748d46/crates/mempool/src/mempool_test.rs#L309)):*
> ```XML
>     let expected_queue_txs: Vec<TransactionReference> =
>         add_tx_inputs.iter().map(|input| TransactionReference::new(&input.tx)).collect();
>     // MempoolContent cannot be used here because the transaction order needs to be verified.
> ```

Why not? `MempoolContent`'s `assert_eq` uses the `assert_eq!` macro, which checks if two expressions are equal using `PartialEq`. I remember sorting `add_tx_inputs` to ensure the queue's content matched its expected order.



_Code quote:_
```XML
MempoolContent cannot be used here because the transaction order needs to be verified.
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 309 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9xLcTEDMUkP9z9-wQN:-OA9Jtuq6C77KQVyJlyH:b-8ynedt) ([raw file](https://github.com/starkware-libs/sequencer/blob/989b5b9ced4f9f93797e1f2c42bb1a5fcb457d5a/crates/mempool/src/mempool_test.rs#L309)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Why don't we want to verify the transactions are inserted into the pool?
</blockquote></details>

Insertion to pool was checked in another test (`test_add_tx_multi_nonce_success`).
In this test, we want to check the order, so we need to test the queue only.
___
*[`crates/mempool/src/mempool_test.rs` line 309 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9xMq3B74NvTC4mD3gU:-OA9K8SCCbZ-dBbvL45L:b-8poegb) ([raw file](https://github.com/starkware-libs/sequencer/blob/5282d6891300d41c4e60ff7705ee66cd10748d46/crates/mempool/src/mempool_test.rs#L309)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Why not? `MempoolContent`'s `assert_eq` uses the `assert_eq!` macro, which checks if two expressions are equal using `PartialEq`. I remember sorting `add_tx_inputs` to ensure the queue's content matched its expected order.
</blockquote></details>

Note that in the current implementation, the input order is ineffective - it's a bug.
It was solved [here](https://reviewable.io/reviews/starkware-libs/sequencer/1544).

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-:-OAIGo83-bUk8gOM7bkr:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9jS0kqA1RIsIWlhOA9:-OAWVlLI87lz-ItZ9R5k:bdxr7g6) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I changed the test's name to clearly describe what it checks.
</blockquote></details>

Not enough, see my comment below.
I think this PR should be closed.

___
___
*[`crates/mempool/src/mempool_test.rs` line 300 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9nYR4r-LOhZv8rWC01:-OAWVu2J4ihX85heOvaA:bhi6gpx) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab16d8c4a0309f58e1f428efc2d4945d7a30d96a/crates/mempool/src/mempool_test.rs#L300)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I've consulted Ayelet. It seems that this function is not used in other places.
</blockquote></details>

We should remove use of `sort_by_key` and pass the transactions in a sorted way explicitly. It's confusing, since it seems only in those test we pass the queue in a sorted way to the test util.
___
*[`crates/mempool/src/mempool_test.rs` line 471 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-OAWVZ8c--0s6WIrztjD:-OAWVZ8d595NxH5VLHLy:b4nrnbk) ([raw file](https://github.com/starkware-libs/sequencer/blob/0024cbeb4642e72cbae39ed8f2e66ee3628e2c56/crates/mempool/src/mempool_test.rs#L471)):*
> ```XML
> 
> #[rstest]
> fn test_add_tx_tip_priority_over_tx_hash(mut mempool: Mempool) {
> ```

This test shouldn't be deleted. We should have exactly one dedicated test that checks secondary (and so on) priority.



_Code quote:_
```XML
test_add_tx_tip_priority_over_tx_hash
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9jS0kqA1RIsIWlhOA9:-OAWarR5BorowmJc50WT:b-q69lih) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not enough, see my comment below.
I think this PR should be closed.
</blockquote></details>

I answered your comment below.
Please let me know what you think.

___
___
*[`crates/mempool/src/mempool_test.rs` line 471 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-OAWVZ8c--0s6WIrztjD:-OAWaSFp0QzgaME1HKRi:b971slc) ([raw file](https://github.com/starkware-libs/sequencer/blob/0024cbeb4642e72cbae39ed8f2e66ee3628e2c56/crates/mempool/src/mempool_test.rs#L471)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This test shouldn't be deleted. We should have exactly one dedicated test that checks secondary (and so on) priority.
</blockquote></details>

Note that the above test has tested exactly the same case.
See [here](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9jRtUC5zEn6SUNTcX_).

The above test checks the priority order; it also checks the secondary priority.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 300 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9nYR4r-LOhZv8rWC01:-OAWnjW-4yW10zNa9ni7:b-joh6de) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab16d8c4a0309f58e1f428efc2d4945d7a30d96a/crates/mempool/src/mempool_test.rs#L300)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

We should remove use of `sort_by_key` and pass the transactions in a sorted way explicitly. It's confusing, since it seems only in those test we pass the queue in a sorted way to the test util.
</blockquote></details>

Nice!
Updated.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 300 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9nYR4r-LOhZv8rWC01:-OAX7j9ZBqmgJxZjy0Jj:btieh16) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab16d8c4a0309f58e1f428efc2d4945d7a30d96a/crates/mempool/src/mempool_test.rs#L300)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Nice!
Updated.
</blockquote></details>

A separate PR, please; unrelated.
___
*[`crates/mempool/src/mempool_test.rs` line 471 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-OAWVZ8c--0s6WIrztjD:-OAX7phwAzJ166SpZYtm:b-teoip) ([raw file](https://github.com/starkware-libs/sequencer/blob/0024cbeb4642e72cbae39ed8f2e66ee3628e2c56/crates/mempool/src/mempool_test.rs#L471)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Note that the above test has tested exactly the same case.
See [here](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9jRtUC5zEn6SUNTcX_).

The above test checks the priority order; it also checks the secondary priority.
</blockquote></details>

I want _a dedicated_ test for secondary priority.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 471 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-OAWVZ8c--0s6WIrztjD:-OAX7vbRCuckwlcU57N0:b93s3u1) ([raw file](https://github.com/starkware-libs/sequencer/blob/0024cbeb4642e72cbae39ed8f2e66ee3628e2c56/crates/mempool/src/mempool_test.rs#L471)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I want _a dedicated_ test for secondary priority.
</blockquote></details>

Other tests, which aren't dedicated to this issue, will change in the future and we'll lose coverage.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 471 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-OAWVZ8c--0s6WIrztjD:-OAX8FeoATrQi0YmeyTT:b3nt9c1) ([raw file](https://github.com/starkware-libs/sequencer/blob/0024cbeb4642e72cbae39ed8f2e66ee3628e2c56/crates/mempool/src/mempool_test.rs#L471)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Other tests, which aren't dedicated to this issue, will change in the future and we'll lose coverage.
</blockquote></details>

Note both my comments below were discussed F2F and written multiple times; I'd like to converge with this subject.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 287 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9nRC_TB0BTGOiJ1gUp:-OAX6olzBfUUkdQ-WFYf:bwuv9uq) ([raw file](https://github.com/starkware-libs/sequencer/blob/5b043051f084ffe39a3e846b3f222fea61fad9f1/crates/mempool/src/mempool_test.rs#L287)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I've added "insertion" as the `add_tx` itself doesn't sort according to priority - the queue sorts it.
wdyt?
</blockquote></details>

Nice!!
___
*[`crates/mempool/src/mempool_test.rs` line 289 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-OAX6yku3AAak_bgStw7:-OAX6ykvE6PEEAKIAHH7:b-w9iaja) ([raw file](https://github.com/starkware-libs/sequencer/blob/c29b8c1da9bde2da9b10f24501e7772e3982b2fa/crates/mempool/src/mempool_test.rs#L289)):*
> ```XML
> fn test_add_tx_insertion_sorted_by_priority(mut mempool: Mempool) {
>     // Setup.
>     let input_smallest_tip_smallest_hash =
> ```

Maybe we don't need to specify the hash here since the tip is low.



_Suggestion:_
```XML
input_low_tip
```
___
*[`crates/mempool/src/mempool_test.rs` line 291 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-OAX71XCETOeQb79AjIh:-OAX71XCETOeQb79AjIi:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c29b8c1da9bde2da9b10f24501e7772e3982b2fa/crates/mempool/src/mempool_test.rs#L291)):*
> ```XML
>     let input_smallest_tip_smallest_hash =
>         add_tx_input!(tip: 50, tx_hash: 1, address: "0x0", tx_nonce: 0, account_nonce: 0);
>     let input_big_tip_small_hash =
> ```





_Suggestion:_
```XML
input_high_tip_mid_hash
```
___
*[`crates/mempool/src/mempool_test.rs` line 293 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-OAX75F0-wwJliqCZ4iD:-OAX75F15kmjx-fsa8Ww:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c29b8c1da9bde2da9b10f24501e7772e3982b2fa/crates/mempool/src/mempool_test.rs#L293)):*
> ```XML
>     let input_big_tip_small_hash =
>         add_tx_input!(tip: 100, tx_hash: 2, address: "0x1", tx_nonce: 1, account_nonce: 1);
>     let input_small_tip_big_hash =
> ```





_Suggestion:_
```XML
input_mid_tip_high_hash
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 471 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-OAWVZ8c--0s6WIrztjD:-OAX8jOU4l2nRKNDbRdp:b326on3) ([raw file](https://github.com/starkware-libs/sequencer/blob/0024cbeb4642e72cbae39ed8f2e66ee3628e2c56/crates/mempool/src/mempool_test.rs#L471)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Note both my comments below were discussed F2F and written multiple times; I'd like to converge with this subject.
</blockquote></details>

comment above *

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @MohammadNassar1)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: all files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9jS0kqA1RIsIWlhOA9:-OAX8spPEsIxbDeQxH7_:bexeuzv) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I answered your comment below.
Please let me know what you think.
</blockquote></details>

Still think this PR should be closed.

___

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9jS0kqA1RIsIWlhOA9:-OAXQoJXDDIh9HfnQoRL:b-fhz6ur) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Still think this PR should be closed.
</blockquote></details>

Answered below, let me know wdyt.

___
___
*[`crates/mempool/src/mempool_test.rs` line 300 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9nYR4r-LOhZv8rWC01:-OAXQ4nSEMAGKFS7naAX:bnhg85g) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab16d8c4a0309f58e1f428efc2d4945d7a30d96a/crates/mempool/src/mempool_test.rs#L300)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

A separate PR, please; unrelated.
</blockquote></details>

Reverted.
I would appreciate it if you could clearly mention in the comment that this should be addressed in the next PR :pray: 
___
*[`crates/mempool/src/mempool_test.rs` line 289 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-OAX6yku3AAak_bgStw7:-OAXXOSpBBvllNAt4hgg:bu4quob) ([raw file](https://github.com/starkware-libs/sequencer/blob/c29b8c1da9bde2da9b10f24501e7772e3982b2fa/crates/mempool/src/mempool_test.rs#L289)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Maybe we don't need to specify the hash here since the tip is low.
</blockquote></details>

Following Elin's request, the change was reverter, which will be done in a separate PR.
___
*[`crates/mempool/src/mempool_test.rs` line 291 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-OAX71XCETOeQb79AjIh:-OAXXYipEbVmYu9PwZX8:bu4quob) ([raw file](https://github.com/starkware-libs/sequencer/blob/c29b8c1da9bde2da9b10f24501e7772e3982b2fa/crates/mempool/src/mempool_test.rs#L291)):*
> ```XML
>     let input_smallest_tip_smallest_hash =
>         add_tx_input!(tip: 50, tx_hash: 1, address: "0x0", tx_nonce: 0, account_nonce: 0);
>     let input_big_tip_small_hash =
> ```

Following Elin's request, the change was reverter, which will be done in a separate PR.
___
*[`crates/mempool/src/mempool_test.rs` line 293 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-OAX75F0-wwJliqCZ4iD:-OAXXZDHETPLhQ1flpQg:bu4quob) ([raw file](https://github.com/starkware-libs/sequencer/blob/c29b8c1da9bde2da9b10f24501e7772e3982b2fa/crates/mempool/src/mempool_test.rs#L293)):*
> ```XML
>     let input_big_tip_small_hash =
>         add_tx_input!(tip: 100, tx_hash: 2, address: "0x1", tx_nonce: 1, account_nonce: 1);
>     let input_small_tip_big_hash =
> ```

Following Elin's request, the change was reverter, which will be done in a separate PR.

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul and @MohammadNassar1)

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 300 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9nYR4r-LOhZv8rWC01:-OAY0CrB45phJPytEUUx:bngan5k) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab16d8c4a0309f58e1f428efc2d4945d7a30d96a/crates/mempool/src/mempool_test.rs#L300)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Reverted.
I would appreciate it if you could clearly mention in the comment that this should be addressed in the next PR :pray:
</blockquote></details>

I don't think I should mention explicitly, it's part of separating to PRs; it's the writer's responsibility, and if the reviewer notes a mistaken unrelated code in the PR, they should mention it as escalation.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 300 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9nYR4r-LOhZv8rWC01:-OAY4_-p419zwUVzK2or:b-837i3v) ([raw file](https://github.com/starkware-libs/sequencer/blob/ab16d8c4a0309f58e1f428efc2d4945d7a30d96a/crates/mempool/src/mempool_test.rs#L300)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I don't think I should mention explicitly, it's part of separating to PRs; it's the writer's responsibility, and if the reviewer notes a mistaken unrelated code in the PR, they should mention it as escalation.
</blockquote></details>

Okay.

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 296 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-O9jRtUC5zEn6SUNTcX_:-OAm1Sho5iarpyLgpKOZ:b-fvgy27) ([raw file](https://github.com/starkware-libs/sequencer/blob/c242780b99e6e2674956c4cf6b3ad910b89591e9/crates/mempool/src/mempool_test.rs#L296)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Covered by these two transactions.
</blockquote></details>

I've added a comment to indicate that the test checks primary priority over secondary priority.
___
*[`crates/mempool/src/mempool_test.rs` line 471 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-OAWVZ8c--0s6WIrztjD:-OAm1FLM4ydER3BhOCLE:b-fvgy27) ([raw file](https://github.com/starkware-libs/sequencer/blob/0024cbeb4642e72cbae39ed8f2e66ee3628e2c56/crates/mempool/src/mempool_test.rs#L471)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can you please explain this:
"I want _a dedicated_ test for secondary priority."

Both the deleted test and this test `test_add_tx_insertion_sorted_by_priority` check both tip and tx_hash order.

And we have another test "test\_add\_tx\_with\_identical\_tip\_succeeds" that is dedicated for secondary priority, see [here](https://github.com/starkware-libs/sequencer/blob/221ae279b51f25ed36ccffe584201d392bd6a880/crates/mempool/src/mempool_test.rs#L400).
</blockquote></details>

I've added a comment to indicate that the test checks primary priority over secondary priority.

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509#-:-OArpcTo4QVVaW8mvvfy:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1509)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

**Pull request closed without merging**
