### PR TITLE
feat(blockifier): derive serialize for block info

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2244?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2246** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2246?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2245** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2245?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2244** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2244?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2244?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2243** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2243?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2244)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @ArniStarkware, and @dorimedini-starkware)

___
*[`crates/blockifier/src/blockifier/block.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2244#-OCTJDkC0OrckN3DX_pX:-OCTJDkC0OrckN3DX_pY:b-8ko8dm) ([raw file](https://github.com/starkware-libs/sequencer/blob/10c393b23fd524f971ae77d2e3d54340aa1d4df6/crates/blockifier/src/blockifier/block.rs#L24)):*
> ```XML
> pub mod block_test;
> 
> #[derive(Clone, Debug, Deserialize, Serialize)]
> ```

@aner-starkware @dorimedini-starkware is this okay? Why do we need this feature?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2244)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @ArniStarkware)

___
*[`crates/blockifier/src/blockifier/block.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2244#-OCTJDkC0OrckN3DX_pX:-OCTKWWP8LKVRKVgJWR0:b3fzasd) ([raw file](https://github.com/starkware-libs/sequencer/blob/10c393b23fd524f971ae77d2e3d54340aa1d4df6/crates/blockifier/src/blockifier/block.rs#L24)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

@aner-starkware @dorimedini-starkware is this okay? Why do we need this feature?
</blockquote></details>

already discussed with @ArniStarkware , any open question remain?

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/blockifier/block.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2244#-OCTJDkC0OrckN3DX_pX:-OCTKDBX-U_gSIEjV_S4:biq5gwg) ([raw file](https://github.com/starkware-libs/sequencer/blob/10c393b23fd524f971ae77d2e3d54340aa1d4df6/crates/blockifier/src/blockifier/block.rs#L24)):*
I DMed with both Dori and Anner.
From Dori:

>we were requested to add serialization by external parties, so we gated it behind a feature so it's clear it's not used in business logic.  
pretty sure you can remove the gate behind whatever object you need serialized, if it now needs serialization;  
only possible issue I can think of is if papyrus implement serde their own way for blockifier objects.  
ask shahak or dan if you want to derive serde on specific objects, if it's ok (if they don't implement their own serde).  
If they do, maybe add the feature to starknet api, and activate the feature in the crate you need?  
(if you depend on papyrus also, though, it may be an issue)

I will double check that this struct is not serialized any other way.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2244#-:-OCTOjmi3iWe_OK2NNTz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

___
*[`crates/blockifier/src/blockifier/block.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2244#-OCTJDkC0OrckN3DX_pX:-OCTOfc75-RcZTIUycFc:b-4so2ez) ([raw file](https://github.com/starkware-libs/sequencer/blob/10c393b23fd524f971ae77d2e3d54340aa1d4df6/crates/blockifier/src/blockifier/block.rs#L24)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I DMed with both Dori and Anner.
From Dori:

>we were requested to add serialization by external parties, so we gated it behind a feature so it's clear it's not used in business logic.  
pretty sure you can remove the gate behind whatever object you need serialized, if it now needs serialization;  
only possible issue I can think of is if papyrus implement serde their own way for blockifier objects.  
ask shahak or dan if you want to derive serde on specific objects, if it's ok (if they don't implement their own serde).  
If they do, maybe add the feature to starknet api, and activate the feature in the crate you need?  
(if you depend on papyrus also, though, it may be an issue)

I will double check that this struct is not serialized any other way.
</blockquote></details>

Great, thanks

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2244)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2244)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Nov 28, 4:56 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2244).

**Pull request merged**
