### PR TITLE
chore(mempool): move MempoolConfig struct before Mempool

### PR DESCRIPTION
**Pull request by ayeletstarkware**

### CODE REVIEW

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1659)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1659#-OANZhQm1WyE-VFHJFUG:-OANZhQn6H3Px4BeLMr6:be4vo4r) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa841f3a3b4dcf923d5aee9097b97c2a3cd3685c/crates/mempool/src/mempool.rs#L36)):*
> ```XML
> }
> 
> type AccountToNonce = HashMap<ContractAddress, Nonce>;
> ```

Please keep the alias above the structs.



_Code quote:_
```XML
type AccountToNonce = HashMap<ContractAddress, Nonce>;
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1659)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1659#-OANik6qC9ho72qlD0bn:-OANik6qC9ho72qlD0bo:b-u5z02f) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa841f3a3b4dcf923d5aee9097b97c2a3cd3685c/crates/mempool/src/mempool.rs#L36)):*
> ```XML
> }
> 
> type AccountToNonce = HashMap<ContractAddress, Nonce>;
> ```

Aliases always appear first.
Please also use for `mempool_state` annotation, while at it.



_Code quote:_
```XML
type AccountToNonce = HashMap<ContractAddress, Nonce>;
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1659)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1659#-OANik6qC9ho72qlD0bn:-OANkFG6AtDYDZuq0pC1:b-clclgn) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa841f3a3b4dcf923d5aee9097b97c2a3cd3685c/crates/mempool/src/mempool.rs#L36)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

@MohammadNassar1 suggested that as well. I think it's better to define the type directly above the struct if it’s specific to that struct, and at the top of the file when it’s used more broadly. don't you think?
</blockquote></details>

Okay, yeah. Note that `pub`iic ones _do_ go on top, since it's a more intuitive location for readers.
See second part of my comment.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1659)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1659#-OANik6qC9ho72qlD0bn:-OANriZaAGNB5s6DjnrY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d0b4fce1b0c36535a3ca98efabec58f0bdb1c03/crates/mempool/src/mempool.rs#L36)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Okay, yeah. Note that `pub`iic ones _do_ go on top, since it's a more intuitive location for readers.
See second part of my comment.
</blockquote></details>

Done.

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1659#-:-OANvk5lD7QNDkUjPY_5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1659#-:-OANyLTsC9N06p8Tp2Uh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1659#-:-OAO6rjDCijS06_X41FS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1659)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
