### PR TITLE
chore(deployment): cdk8s deployment tool refactor

### PR DESCRIPTION
**Pull request by idan-starkware**

### CODE REVIEW

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2257)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @idan-starkware)

___
*[`deployments/sequencer/services/topology_helpers.py` line 21 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2257#-OCXXDZBAkqDuES-Q61e:-OCXXDZBAkqDuES-Q61f:b-2f549g) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e865678e1cb443f755c600a25762ec9e3fe8918/deployments/sequencer/services/topology_helpers.py#L21)):*
> ```Python
> def get_port_mappings() -> typing.Sequence[objects.PortMapping]:
>   return [
>       objects.PortMapping(name="http", port=80, container_port=8080),
> ```

const all port numbers



_Code quote:_
```Python
80
```

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2257)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @idan-starkware)

___
*[`deployments/sequencer/services/objects.py` line 147 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2257#-OCXXaqr18z8kXloHBbN:-OCXXaqsATpPH7WecDsq:bqfm7qt) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e865678e1cb443f755c600a25762ec9e3fe8918/deployments/sequencer/services/objects.py#L147)):*
> ```Python
> @dataclasses.dataclass
> class Statefulset:
>     pass
> ```

why its needed?



_Code quote:_
```Python
@dataclasses.dataclass
class Container:
    name: str
    image: str
    args: List[str]
    ports: Sequence[ContainerPort]
    startup_probe: Optional[Probe]
    readiness_probe: Optional[Probe]
    liveness_probe: Optional[Probe]
    volume_mounts: Sequence[VolumeMount]


@dataclasses.dataclass
class Deployment:
    replicas: int
    annotations: Mapping[str, str] | None
    containers: Sequence[Container] | None
    configmap_volumes: Sequence[ConfigMapVolume] | None
    pvc_volumes: Sequence[PvcVolume] | None


@dataclasses.dataclass
class Statefulset:
    pass
```

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2257)* status: 0 of 13 files reviewed, 5 unresolved discussions (waiting on @idan-starkware)

___
*[`deployments/sequencer/services/helpers.py` line 8 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2257#-OCXXlSF5iEOzMFlmtVR:-OCXXlSG6cYOeYzv-wmF:b-p0ro99) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e865678e1cb443f755c600a25762ec9e3fe8918/deployments/sequencer/services/helpers.py#L8)):*
> ```Python
> 
>     parser.add_argument(
>         "--config",
> ```

---config-file-path



_Code quote:_
```Python
--config
```
___
*[`deployments/sequencer/services/helpers.py` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2257#-OCXXt7U9yp74Hto3DAu:-OCXXt7U9yp74Hto3DAv:bewd2fw) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e865678e1cb443f755c600a25762ec9e3fe8918/deployments/sequencer/services/helpers.py#L25)):*
> ```Python
>     parser.add_argument(
>         "--namespace",
>         required=False,
> ```

its required



_Code quote:_
```Python
False
```
___
*[`deployments/sequencer/services/helpers.py` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2257#-OCXXwrq1GrSj6jx584X:-OCXXwrr4ouZXqQAgkB8:b-l6mwxj) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e865678e1cb443f755c600a25762ec9e3fe8918/deployments/sequencer/services/helpers.py#L27)):*
> ```Python
>         required=False,
>         type=str,
>         default="default",
> ```

remove



_Code quote:_
```Python
default="default",
```

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2257)* status: 0 of 13 files reviewed, 6 unresolved discussions (waiting on @idan-starkware)

___
*[`deployments/sequencer/main.py` line 64 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2257#-OCXZPkICh5DcsEPz72b:-OCXZPkJ7IAcCBelW3oN:b-wem3tu) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e865678e1cb443f755c600a25762ec9e3fe8918/deployments/sequencer/main.py#L64)):*
> ```Python
>         scope=app,
>         name=system_preset.name,
>         namespace=system_preset.namespace,
> ```

why this namespace is needed?



_Code quote:_
```Python
namespace=system_preset.namespace,
```

**Review by idan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2257)* status: 0 of 18 files reviewed, 6 unresolved discussions (waiting on @alon-dotan-starkware)

___
*[`deployments/sequencer/services/helpers.py` line 27 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2257#-OCXXwrq1GrSj6jx584X:-OCYU2G8DxZPpMHF5I7x:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e865678e1cb443f755c600a25762ec9e3fe8918/deployments/sequencer/services/helpers.py#L27)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`deployments/sequencer/services/objects.py` line 147 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2257#-OCXXaqr18z8kXloHBbN:-OCYU3uu0MjQIcIYxLRG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e865678e1cb443f755c600a25762ec9e3fe8918/deployments/sequencer/services/objects.py#L147)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

why its needed?
</blockquote></details>

Done.
___
*[`deployments/sequencer/services/topology_helpers.py` line 21 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2257#-OCXXDZBAkqDuES-Q61e:-OCYU5YmAkJKc_5kbyGG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7e865678e1cb443f755c600a25762ec9e3fe8918/deployments/sequencer/services/topology_helpers.py#L21)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

const all port numbers
</blockquote></details>

Done.

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2257)* status: 7 of 20 files reviewed, 5 unresolved discussions (waiting on @idan-starkware)

___
*[`deployments/sequencer/services/objects.py` line 27 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2257#-OCcYJak-OOnnH_nGagX:-OCcYJak-OOnnH_nGagY:b-88n4iv) ([raw file](https://github.com/starkware-libs/sequencer/blob/0da4a2fb82aa9403e90e982c96a59d642cb54bfa/deployments/sequencer/services/objects.py#L27)):*
> ```Python
> @dataclasses.dataclass
> class Service:
>     type: Optional[str]
> ```

Enum?



_Code quote:_
```Python
Optional[str]
```

**Review by idan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2257)* status: 6 of 20 files reviewed, 3 unresolved discussions (waiting on @alon-dotan-starkware)

___
*[`deployments/sequencer/services/helpers.py` line 17 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2257#-OCcY2JO6xtsgT4PtacY:-OCd34aLCCTfE3afogaZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0da4a2fb82aa9403e90e982c96a59d642cb54bfa/deployments/sequencer/services/helpers.py#L17)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

reundent
</blockquote></details>

Done.
___
*[`deployments/sequencer/services/helpers.py` line 22 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2257#-OCcY5k_CAy_gzSqUw8j:-OCd34qh0AuNd9Kz9Wsk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0da4a2fb82aa9403e90e982c96a59d642cb54bfa/deployments/sequencer/services/helpers.py#L22)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

redundent
</blockquote></details>

Done.
___
*[`deployments/sequencer/services/objects.py` line 27 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2257#-OCcYJak-OOnnH_nGagX:-OCd35RDBa3RB0dcXGzf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/0da4a2fb82aa9403e90e982c96a59d642cb54bfa/deployments/sequencer/services/objects.py#L27)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

Enum?
</blockquote></details>

Done.

**Review by idan-starkware — COMMENTED** [review]
> Reviewed 4 of 11 files at r4, 2 of 5 files at r5, 14 of 14 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2257)* status: 18 of 20 files reviewed, 3 unresolved discussions (waiting on @alon-dotan-starkware)

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2257#-:-OCd9ls91kZn_1BPv8gj:bnfp4nl)* status: 18 of 20 files reviewed, all discussions resolved (waiting on @idan-starkware)

**Review by idan-starkware — COMMENTED** [review]
> Reviewed 20 of 20 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2257)* status: 0 of 20 files reviewed, all discussions resolved (waiting on @idan-starkware)

**Review by idan-starkware — COMMENTED** [review]
> Reviewed 11 of 11 files at r9, 5 of 5 files at r10, 14 of 14 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2257)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @idan-starkware)

**Pull request merged**
