### PR TITLE
build(blockifier_reexecution): add stability for rpc test

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1712?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1712** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1712?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1698** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1698?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1658** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1658?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1604** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1604?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1712)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-OAX8r_a5Jg33ELHkflZ:-OAX8r_a5Jg33ELHkfl_:bak5n1d) (no related file):*
general remarks:
1. add a config to the input of the rpc reader, with configurable number of retries and delay between retries
2. implement a `send_with_retries<T>(...) -> T` private method on the rpc reader, and use it in the StateReader implementation 
3. (2) may be hard (what is the input type to this function?), if so, let's talk on slack

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1712)* status: all files reviewed, 6 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-OAX8r_a5Jg33ELHkflZ:-OAXtEtf4_ydShBsZLkX:b-f5216h) (no related file):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

the best solution would probably be creating an attribute macro; but that's overkill for now...
gj

___
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-OAXrEuU6RS6Q2_cRmGg:-OAXrEuU6RS6Q2_cRmGh:b-b9gwe9) ([raw file](https://github.com/starkware-libs/sequencer/blob/89bb0585ed1dad6c53fdd8f03994726724f30abd/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L25)):*
> ```XML
> use starknet_types_core::felt::Felt;
> 
> use super::reexecution_state_reader::ReexecutionStateReader;
> ```

no `super` in non-test modules



_Code quote:_
```XML
super
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-OAXrJvD2OjOD_8QI4QH:-OAXrJvD2OjOD_8QI4QI:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/89bb0585ed1dad6c53fdd8f03994726724f30abd/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L49)):*
> ```XML
>     pub(crate) retry_count: usize,
>     pub(crate) retry_wait_time: u64,
> }
> ```





_Suggestion:_
```XML
pub struct RetryConfig {
    pub(crate) n_retries: usize,
    pub(crate) retry_interval_milliseconds: u64,
}

pub struct TestStateReader {
    pub(crate) rpc_reader: RpcStateReader,
    pub(crate) retry_config: RetryConfig,
}
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-OAXrbjOA-sfHsURqvtU:-OAXrbjOA-sfHsURqvtV:b2ix4ub) ([raw file](https://github.com/starkware-libs/sequencer/blob/89bb0585ed1dad6c53fdd8f03994726724f30abd/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L59)):*
> ```XML
>         }
>     }
> }
> ```

do you still need this if you split the retry config to a struct? you can implement default on the RetryConfig directly



_Code quote:_
```XML
impl Default for TestStateReader {
    fn default() -> Self {
        Self {
            rpc_reader: RpcStateReader::from_latest(&get_rpc_state_reader_config()),
            retry_count: DEFAULT_RETRY_COUNT,
            retry_wait_time: DEFAULT_RETRY_WAIT_TIME,
        }
    }
}
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 102 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-OAXt31u25pp6i_7SQ85:-OAXt31u25pp6i_7SQ86:b89qgx3) ([raw file](https://github.com/starkware-libs/sequencer/blob/89bb0585ed1dad6c53fdd8f03994726724f30abd/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L102)):*
> ```XML
>         let conract_class = retry_request!(self.retry_count, self.retry_wait_time, || self
>             .get_contract_class(&class_hash))
>         .unwrap();
> ```

why are you `unwrap`ing here now?
previously you could propagate the error; why did this change?



_Code quote:_
```XML
    fn get_storage_at(
        &self,
        contract_address: ContractAddress,
        key: StorageKey,
    ) -> StateResult<Felt> {
        Ok(retry_request!(self.retry_count, self.retry_wait_time, || self
            .rpc_reader
            .get_storage_at(contract_address, key))
        .or_else(|e| {
            if e.to_string().contains("Contract address not found for request") {
                Ok(Felt::default())
            } else {
                Err(e)
            }
        })
        .unwrap())
    }

    fn get_class_hash_at(&self, contract_address: ContractAddress) -> StateResult<ClassHash> {
        Ok(retry_request!(self.retry_count, self.retry_wait_time, || self
            .rpc_reader
            .get_class_hash_at(contract_address))
        .unwrap())
    }

    /// Returns the contract class of the given class hash.
    /// Compile the contract class if it is Sierra.
    fn get_compiled_contract_class(
        &self,
        class_hash: ClassHash,
    ) -> StateResult<BlockifierContractClass> {
        let conract_class = retry_request!(self.retry_count, self.retry_wait_time, || self
            .get_contract_class(&class_hash))
        .unwrap();
```
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-OAXsXpT6dL_GBTX4vV_:-OAXsXpT6dL_GBTX4vVa:byr4ffv) ([raw file](https://github.com/starkware-libs/sequencer/blob/89bb0585ed1dad6c53fdd8f03994726724f30abd/crates/blockifier_reexecution/src/state_reader/utils.rs#L45)):*
> ```XML
> #[macro_export]
> macro_rules! retry_request {
>     ($retry_count:expr, $delay:expr, $closure:expr) => {{
> ```

see above



_Suggestion:_
```XML
($retry_config:expr, $closure:expr)
```
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-OAXshGyDAeAza37Yivb:-OAXshGyDAeAza37Yivc:bcwxyim) ([raw file](https://github.com/starkware-libs/sequencer/blob/89bb0585ed1dad6c53fdd8f03994726724f30abd/crates/blockifier_reexecution/src/state_reader/utils.rs#L51)):*
> ```XML
>                 // If the error is a connection error, we want to retry.
>                 Err(e) if e.to_string().contains("connection error") => Err(e),
>                 Err(e) => return Err(e),
> ```

these two match arms return the same value from the closure, no...?



_Code quote:_
```XML
                Err(e) if e.to_string().contains("connection error") => Err(e),
                Err(e) => return Err(e),
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1712)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-OAXrEuU6RS6Q2_cRmGg:-OAXwwmjC92M0cDgMbFU:b-683ww7) ([raw file](https://github.com/starkware-libs/sequencer/blob/89bb0585ed1dad6c53fdd8f03994726724f30abd/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L25)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no `super` in non-test modules
</blockquote></details>

its the auto imports :|
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-OAXrJvD2OjOD_8QI4QH:-OAY-LcGEPDGE_SN_kJF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/89bb0585ed1dad6c53fdd8f03994726724f30abd/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L49)):*
> ```XML
>     pub(crate) retry_count: usize,
>     pub(crate) retry_wait_time: u64,
> }
> ```

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-OAXrbjOA-sfHsURqvtU:-OAY-S8R7wmxdx7LpDt_:b2s4b72) ([raw file](https://github.com/starkware-libs/sequencer/blob/89bb0585ed1dad6c53fdd8f03994726724f30abd/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L59)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do you still need this if you split the retry config to a struct? you can implement default on the RetryConfig directly
</blockquote></details>

just for the rpc_reader 
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 102 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-OAXt31u25pp6i_7SQ85:-OAY8VNG2K86MnGLT0jc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/89bb0585ed1dad6c53fdd8f03994726724f30abd/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L102)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why are you `unwrap`ing here now?
previously you could propagate the error; why did this change?
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-OAXsXpT6dL_GBTX4vV_:-OAY1Y-L4jenVflxHPI_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/89bb0585ed1dad6c53fdd8f03994726724f30abd/crates/blockifier_reexecution/src/state_reader/utils.rs#L45)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-OAXshGyDAeAza37Yivb:-OAY53aN4OByGSK0scX_:bc10hop) ([raw file](https://github.com/starkware-libs/sequencer/blob/89bb0585ed1dad6c53fdd8f03994726724f30abd/crates/blockifier_reexecution/src/state_reader/utils.rs#L51)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

these two match arms return the same value from the closure, no...?
</blockquote></details>

Ops, I mean to retry only for connection error

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1712)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 131 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-OAYAiUL-jwGWL4OX9gA:-OAYAiUL-jwGWL4OX9gB:briadr1) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ec774ffd77ad8d7acbab32147d5ec7b4f5ce641/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L131)):*
> ```XML
>                 e
>             }
>         })?;
> ```

code duplication.
add a private `fn panic_on_connection_error(error: StateError) -> StateError` and then just do `map_err(Self::panic_on_state_error)`, everywhere.
you can add a string error if you want to differentiate between sources of the error



_Code quote:_
```XML
    fn get_nonce_at(&self, contract_address: ContractAddress) -> StateResult<Nonce> {
        retry_request!(self.retry_config, || self.rpc_reader.get_nonce_at(contract_address))
            .map_err(|e| {
                if e.to_string().contains("Connection error") {
                    panic!("Connection error occurred while retrieving nonce {e}");
                } else {
                    e
                }
            })
    }

    fn get_storage_at(
        &self,
        contract_address: ContractAddress,
        key: StorageKey,
    ) -> StateResult<Felt> {
        retry_request!(self.retry_config, || self.rpc_reader.get_storage_at(contract_address, key))
            .or_else(|e| {
                if e.to_string().contains("Contract address not found for request") {
                    Ok(Felt::default())
                } else {
                    Err(e)
                }
            })
            .map_err(|e| {
                if e.to_string().contains("Connection error") {
                    panic!("Connection error occurred while retrieving storage {e}");
                } else {
                    e
                }
            })
    }

    fn get_class_hash_at(&self, contract_address: ContractAddress) -> StateResult<ClassHash> {
        retry_request!(self.retry_config, || self.rpc_reader.get_class_hash_at(contract_address))
            .map_err(|e| {
                if e.to_string().contains("Connection error") {
                    panic!("Connection error occurred while retrieving class hash {e}");
                } else {
                    e
                }
            })
    }

    /// Returns the contract class of the given class hash.
    /// Compile the contract class if it is Sierra.
    fn get_compiled_contract_class(
        &self,
        class_hash: ClassHash,
    ) -> StateResult<BlockifierContractClass> {
        let conract_class = retry_request!(self.retry_config, || self
            .get_contract_class(&class_hash))
        .map_err(|e| {
            if e.to_string().contains("Connection error") {
                panic!("Connection error occurred while retrieving contract class {e}");
            } else {
                e
            }
        })?;
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1712)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 131 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-OAYAiUL-jwGWL4OX9gA:-OAYG7J-3BIdqpX-juX-:b-86xs2e) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ec774ffd77ad8d7acbab32147d5ec7b4f5ce641/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L131)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

code duplication.
add a private `fn panic_on_connection_error(error: StateError) -> StateError` and then just do `map_err(Self::panic_on_state_error)`, everywhere.
you can add a string error if you want to differentiate between sources of the error
</blockquote></details>

I put it in the macro

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1712)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 126 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-OAl8lQa65p7bZFvR_yk:-OAl8lQb0HYrT46OOvHV:b-ctp7zn) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a746c3f8240766dfa2bdae531eef8264833389c/crates/blockifier_reexecution/src/state_reader/utils.rs#L126)):*
> ```XML
>             if e.error.to_string().contains("connection error") {
>                 panic!("Connection error: {:?}", e.error);
>             }
> ```

nice!
however, the retry macro is generic;
please add data to the RetryConfig to indicate which string should be searched for when checking for a connection error, and what error to panic with on "final failure"



_Suggestion:_
```XML
           if e.error.to_string().contains($retry_config.expected_error_string) {
                panic!("{}: {:?}", $retry_config.retry_failure_message, e.error);
            }
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1712)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/utils.rs` line 126 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-OAl8lQa65p7bZFvR_yk:-OAlpjQa4O85oNLx7HJ2:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a746c3f8240766dfa2bdae531eef8264833389c/crates/blockifier_reexecution/src/state_reader/utils.rs#L126)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

nice!
however, the retry macro is generic;
please add data to the RetryConfig to indicate which string should be searched for when checking for a connection error, and what error to panic with on "final failure"
</blockquote></details>

Done

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-:-OAmgmgYBfHu5UGxqiFA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1712)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1712)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1712#-:-OAveDoE7ZGXs4FqibW2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
