### PR TITLE
test(mempool): remove nop commit_block-s from two queues tests

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1068)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1068)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1068#-O7wswUu2KThR6K0wvXF):*
what does it mean? no operation?



_Code quote:_
```
nop
```
___
*[`crates/mempool/src/mempool_test.rs` line 430 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1068#-O7wtY812MFTUOcbYrNR:-O7wtY812MFTUOcbYrNS:b-5kyal4) ([raw file](https://github.com/starkware-libs/sequencer/blob/1128cce976548f1def82094c8c5164e4702543e9/crates/mempool/src/mempool_test.rs#L430)):*
> ```XML
>     // Updating the gas price threshold should happen in a new block creation.
>     let state_changes = [];
>     commit_block(&mut mempool, state_changes);
> ```

Can you explain what changed?

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1068)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1068#-O7wswUu2KThR6K0wvXF):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

what does it mean? no operation?
</blockquote></details>

Yes.
___
*[`crates/mempool/src/mempool_test.rs` line 430 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1068#-O7wtY812MFTUOcbYrNR:-O7wuoq7DPBtHTxe7Xau:b-cjd9bg) ([raw file](https://github.com/starkware-libs/sequencer/blob/1128cce976548f1def82094c8c5164e4702543e9/crates/mempool/src/mempool_test.rs#L430)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Can you explain what changed?
</blockquote></details>

It doesn't do anything, thus makes the test over-complicated and confusing.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1068)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 430 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1068#-O7wtY812MFTUOcbYrNR:-O7wvlaS34iR8SEByREf:b-mmuwpc) ([raw file](https://github.com/starkware-libs/sequencer/blob/1128cce976548f1def82094c8c5164e4702543e9/crates/mempool/src/mempool_test.rs#L430)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It doesn't do anything, thus makes the test over-complicated and confusing.
</blockquote></details>

Note it should have come up in the initial review.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1068)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 430 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1068#-O7wtY812MFTUOcbYrNR:-O7wxW6t1vu4iNst_WOJ:blqo41f) ([raw file](https://github.com/starkware-libs/sequencer/blob/1128cce976548f1def82094c8c5164e4702543e9/crates/mempool/src/mempool_test.rs#L430)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Note it should have come up in the initial review.
</blockquote></details>

Is the gas price threshold supposed to be updated during the block creation? Since it doesn't, we're using `mempool._update_gas_price_threshold`? Is this temporary, and will it be replaced with `commit_block`?

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1068)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 430 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1068#-O7wtY812MFTUOcbYrNR:-O7wzOzqEFfHV5hNh7Gp:b-qabhqg) ([raw file](https://github.com/starkware-libs/sequencer/blob/1128cce976548f1def82094c8c5164e4702543e9/crates/mempool/src/mempool_test.rs#L430)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Is the gas price threshold supposed to be updated during the block creation? Since it doesn't, we're using `mempool._update_gas_price_threshold`? Is this temporary, and will it be replaced with `commit_block`?
</blockquote></details>

From the fact `commit_block` does nothing here, you can conclude it's the latter. Note you reviewed this PR, was it asked and understood back then?

**Pull request merged**
