### PR TITLE
refactor(starknet_state_sync): refactor state sync to use p2p sync

### PR DESCRIPTION
**Pull request by noamsp-starkware**

### CODE REVIEW

**Comment by noamsp-starkware** [comment]
* **#2515** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2515?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2515?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2515)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/starknet_state_sync/src/runner/mod.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2515#-ODf7Uhz17fAdTtSCrOn:-ODf7Uhz17fAdTtSCrOo:bsol3vx) ([raw file](https://github.com/starkware-libs/sequencer/blob/f1589c9e740051533ce31f0c9f4a60da042c85bd/crates/starknet_state_sync/src/runner/mod.rs#L47)):*
> ```XML
>                 }
>                 result = &mut self.p2p_sync_client_future => return result.map_err(|_| ComponentError::InternalComponentError),
>                 _ = &mut self.p2p_sync_server_future => {
> ```

change _ to () so that if sync server changes the return type you'll get a compiler error and will change the code here to return result.map_err
___
*[`crates/starknet_state_sync/src/config.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2515#-ODf6wi86OlC_crLZ7ws:-ODf6wi86OlC_crLZ7wt:b-a82ldd) ([raw file](https://github.com/starkware-libs/sequencer/blob/f1589c9e740051533ce31f0c9f4a60da042c85bd/crates/starknet_state_sync/src/config.rs#L15)):*
> ```XML
>     #[validate]
>     pub storage_config: StorageConfig,
>     // TODO(shahak): add validate to P2PSyncClientConfig, NetworkConfig and use them here.
> ```

NetworkConfig already has validate. Use it

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2515)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/starknet_state_sync/src/runner/test.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2515#-ODf7xMkCGbUf7FfKhuv:-ODf7xMkCGbUf7FfKhuw:b1i2t3s) ([raw file](https://github.com/starkware-libs/sequencer/blob/f1589c9e740051533ce31f0c9f4a60da042c85bd/crates/starknet_state_sync/src/runner/test.rs#L1)):*
> ```XML
> // TODO: Refactor these to suit the change to state sync now using p2p sync.
> ```

Erase these instead of commenting them out

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2515)* status: all files reviewed, 3 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/starknet_state_sync/src/runner/test.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2515#-ODf7xMkCGbUf7FfKhuv:-ODf81YD3G7xyZ6gi0sJ:b2fbark) ([raw file](https://github.com/starkware-libs/sequencer/blob/f1589c9e740051533ce31f0c9f4a60da042c85bd/crates/starknet_state_sync/src/runner/test.rs#L1)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Erase these instead of commenting them out
</blockquote></details>

We have git to store the old code

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2515)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/starknet_state_sync/src/config.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2515#-ODf6wi86OlC_crLZ7ws:-ODf8vNF3o8UC-8pWWV9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f1589c9e740051533ce31f0c9f4a60da042c85bd/crates/starknet_state_sync/src/config.rs#L15)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

NetworkConfig already has validate. Use it
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync/src/runner/mod.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2515#-ODf7Uhz17fAdTtSCrOn:-ODf9DKJDO16RZVPyWnW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f1589c9e740051533ce31f0c9f4a60da042c85bd/crates/starknet_state_sync/src/runner/mod.rs#L47)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

change _ to () so that if sync server changes the return type you'll get a compiler error and will change the code here to return result.map_err
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync/src/runner/test.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2515#-ODf7xMkCGbUf7FfKhuv:-ODfSpjKDeiQJPDlNqo3:ba5269) ([raw file](https://github.com/starkware-libs/sequencer/blob/f1589c9e740051533ce31f0c9f4a60da042c85bd/crates/starknet_state_sync/src/runner/test.rs#L1)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

We have git to store the old code
</blockquote></details>

Alon's PR already took care of the file. I left this as so his PR doesn't have merge conflicts.

https://reviewable.io/reviews/starkware-libs/sequencer/2560

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2515#-:-ODfTV_tDNTkbCP1FN4t:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)

**Pull request merged**
