### PR TITLE
test: blockifier regression test test utils

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/956)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/956?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#956** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/956?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#952** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/952?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#948** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/948?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#946** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/946?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#945** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/945?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by aner-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/956)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7U1o603dWp3Cysp9jN:-O7U1o61Aw-riadnr5yH:bchgfxv) ([raw file](https://github.com/starkware-libs/sequencer/blob/f5fbf0a9c36804e1b5142a60a278fc0a985fb488/crates/blockifier/src/versioned_constants.rs#L47)):*
> ```XML
>                 pub(crate) const [<VERSIONED_CONSTANTS_ $variant:upper _JSON>]: &str =
>                     include_str!($path_to_json);
>                 pub static [<VERSIONED_CONSTANTS_ $variant:upper>]: LazyLock<VersionedConstants> = LazyLock::new(|| {
> ```

Blocking until approved by @dorimedini-starkware.



_Code quote:_
```XML
pub
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 129 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7dcn1zCl-dbCrwkOOZ:-O7dcn2-DdYxfwSeZtla:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/726943ebed83e0b3d0fa6653519409ee183167b6/crates/blockifier_regression_test/src/test_state_reader.rs#L129)):*
> ```XML
> 
>     #[rstest]
>     #[ignore = "This test using http request, so it should not be run in CI"]
> ```





_Suggestion:_
```XML
This test uses HTTP requests, so it should not be run in CI.
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 135 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7dcyTV9Z0XtqB9qmOG:-O7dcyTV9Z0XtqB9qmOH:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/726943ebed83e0b3d0fa6653519409ee183167b6/crates/blockifier_regression_test/src/test_state_reader.rs#L135)):*
> ```XML
> 
>     #[rstest]
>     #[ignore = "This test using http request, so it should not be run in CI"]
> ```





_Suggestion:_
```XML
This test uses HTTP requests, so it should not be run in CI.
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/956)* status: all files reviewed, 11 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7U1o603dWp3Cysp9jN:-O7hsQrTARfxR2iRXB8Z:b-f8humc) ([raw file](https://github.com/starkware-libs/sequencer/blob/f5fbf0a9c36804e1b5142a60a278fc0a985fb488/crates/blockifier/src/versioned_constants.rs#L47)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Blocking until approved by @dorimedini-starkware.
</blockquote></details>

approved
___
*[`crates/blockifier_regression_test/Cargo.toml` line 22 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7hsTc-CWKxYenN8g8-:-O7hsTc-CWKxYenN8g80:b-la2eu0) ([raw file](https://github.com/starkware-libs/sequencer/blob/726943ebed83e0b3d0fa6653519409ee183167b6/crates/blockifier_regression_test/Cargo.toml#L22)):*
> ```TOML
> [dev-dependencies]
> assert_matches.workspace = true
> rstest.workspace = true
> ```

move above `[lints]` section please (next to `[dependencies]`)



_Code quote:_
```TOML
[dev-dependencies]
assert_matches.workspace = true
rstest.workspace = true
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7hsa3w2rXPs_ujAbrG:-O7hsa3w2rXPs_ujAbrH:b-m2ktcx) ([raw file](https://github.com/starkware-libs/sequencer/blob/726943ebed83e0b3d0fa6653519409ee183167b6/crates/blockifier_regression_test/src/test_state_reader.rs#L109)):*
> ```XML
> 
> #[cfg(test)]
> pub mod test {
> ```

please put this test in a separate module next to this one



_Code quote:_
```XML
pub mod test {
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7hsfJy1AouFEHZ8XIE:-O7hsfJy1AouFEHZ8XIF:bp70cj6) ([raw file](https://github.com/starkware-libs/sequencer/blob/726943ebed83e0b3d0fa6653519409ee183167b6/crates/blockifier_regression_test/src/test_state_reader.rs#L113)):*
> ```XML
>     use blockifier::blockifier::block::BlockInfo;
>     use blockifier::versioned_constants::StarknetVersion;
>     use rstest::*;
> ```

why `*`? use only what you need



_Code quote:_
```XML
use rstest::*;
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7hskee9uDViGD-eu8J:-O7hskee9uDViGD-eu8K:bdw7auk) ([raw file](https://github.com/starkware-libs/sequencer/blob/726943ebed83e0b3d0fa6653519409ee183167b6/crates/blockifier_regression_test/src/test_state_reader.rs#L126)):*
> ```XML
>     pub fn test_block_number() -> BlockNumber {
>         BlockNumber(700000)
>     }
> ```

fixtures can use fixtures (IIRC)



_Suggestion:_
```XML
    #[fixture]
    pub fn test_state_reader(test_block_number: BlockNumber) -> TestStateReader {
        TestStateReader::new(None, test_block_number)
    }

    #[fixture]
    pub fn test_block_number() -> BlockNumber {
        BlockNumber(700000)
    }
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 129 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7hsrSV0mzO3WTiAVph:-O7hsrSWBPtLUdZMATa0:buatiqh) ([raw file](https://github.com/starkware-libs/sequencer/blob/726943ebed83e0b3d0fa6653519409ee183167b6/crates/blockifier_regression_test/src/test_state_reader.rs#L129)):*
> ```XML
> 
>     #[rstest]
>     #[ignore = "This test using http request, so it should not be run in CI"]
> ```

`ignore` may not be enough - you will have to check CI for anyone who may be running tests with `--include-ignored`.
I suggest you gate this test behind a `blockifier_regression_testing` feature or something, and then you'll need `cargo test --features blockifier_regression_testing` to reach this test



_Code quote:_
```XML
#[ignore = "This test using http request, so it should not be run in CI"]
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7ht8S6-rOLxGyDg_lr:-O7ht8S78nUahGGHx1X6:byopsqw) ([raw file](https://github.com/starkware-libs/sequencer/blob/726943ebed83e0b3d0fa6653519409ee183167b6/crates/blockifier_regression_test/src/test_state_reader.rs#L131)):*
> ```XML
>     #[ignore = "This test using http request, so it should not be run in CI"]
>     pub fn test_get_block_info(test_state_reader: TestStateReader, test_block_number: BlockNumber) {
>         assert_matches!(test_state_reader.get_block_info() ,  Ok(BlockInfo{block_number, .. }) if block_number==test_block_number);
> ```

fix whitespace (remove extra spaces, add spaces around `==`, break line if it's over 100 chars).
macro bodies aren't auto-formatted



_Code quote:_
```XML
assert_matches!(test_state_reader.get_block_info() ,  Ok(BlockInfo{block_number, .. }) if block_number==test_block_number);
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 135 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7htHEs1g5XkvDT8XLY:-O7htHEs1g5XkvDT8XLZ:byr4ffv) ([raw file](https://github.com/starkware-libs/sequencer/blob/726943ebed83e0b3d0fa6653519409ee183167b6/crates/blockifier_regression_test/src/test_state_reader.rs#L135)):*
> ```XML
> 
>     #[rstest]
>     #[ignore = "This test using http request, so it should not be run in CI"]
> ```

see above



_Code quote:_
```XML
ignore
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7htND70T_hju83mDOF:-O7htND70T_hju83mDOG:b-1u7que) ([raw file](https://github.com/starkware-libs/sequencer/blob/726943ebed83e0b3d0fa6653519409ee183167b6/crates/blockifier_regression_test/src/test_state_reader.rs#L137)):*
> ```XML
>     #[ignore = "This test using http request, so it should not be run in CI"]
>     pub fn test_get_starknet_version(test_state_reader: TestStateReader) {
>         assert!(test_state_reader.get_starknet_version().unwrap() == StarknetVersion::V0_13_2_1)
> ```

please add a TODO to use `StarknetVersion::latest()` [when it's merged](https://reviewable.io/reviews/starkware-libs/sequencer/1042)



_Code quote:_
```XML
StarknetVersion::V0_13_2_1
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/956)* status: all files reviewed, 11 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 8 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/956)* status: all files reviewed, 8 unresolved discussions (waiting on @AvivYossef-starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/956)* status: 6 of 8 files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier_regression_test/Cargo.toml` line 22 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7hsTc-CWKxYenN8g8-:-O7wnsKFDQT-kXAL5ASd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/726943ebed83e0b3d0fa6653519409ee183167b6/crates/blockifier_regression_test/Cargo.toml#L22)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move above `[lints]` section please (next to `[dependencies]`)
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7hsa3w2rXPs_ujAbrG:-O7wpqKB7aw3QxlAn9YB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/726943ebed83e0b3d0fa6653519409ee183167b6/crates/blockifier_regression_test/src/test_state_reader.rs#L109)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please put this test in a separate module next to this one
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7hsfJy1AouFEHZ8XIE:-O7wqo7h7KwJr5f2rTMI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/726943ebed83e0b3d0fa6653519409ee183167b6/crates/blockifier_regression_test/src/test_state_reader.rs#L113)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why `*`? use only what you need
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7hskee9uDViGD-eu8J:-O7wqvK6CBt_DPIZ5jJa:bb70w76) ([raw file](https://github.com/starkware-libs/sequencer/blob/726943ebed83e0b3d0fa6653519409ee183167b6/crates/blockifier_regression_test/src/test_state_reader.rs#L126)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

fixtures can use fixtures (IIRC)
</blockquote></details>

Nice
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 129 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7hsrSV0mzO3WTiAVph:-O7wrXMF0xhG-MhWDyzG:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/726943ebed83e0b3d0fa6653519409ee183167b6/crates/blockifier_regression_test/src/test_state_reader.rs#L129)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`ignore` may not be enough - you will have to check CI for anyone who may be running tests with `--include-ignored`.
I suggest you gate this test behind a `blockifier_regression_testing` feature or something, and then you'll need `cargo test --features blockifier_regression_testing` to reach this test
</blockquote></details>

Done
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7ht8S6-rOLxGyDg_lr:-O7wtWKZDQw86clAvV05:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/726943ebed83e0b3d0fa6653519409ee183167b6/crates/blockifier_regression_test/src/test_state_reader.rs#L131)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

fix whitespace (remove extra spaces, add spaces around `==`, break line if it's over 100 chars).
macro bodies aren't auto-formatted
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 135 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7htHEs1g5XkvDT8XLY:-O7wvwc68VnRD55y6Puw:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/726943ebed83e0b3d0fa6653519409ee183167b6/crates/blockifier_regression_test/src/test_state_reader.rs#L135)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7htND70T_hju83mDOF:-O7wrH6l71ycXSodfzjS:bvg0el3) ([raw file](https://github.com/starkware-libs/sequencer/blob/726943ebed83e0b3d0fa6653519409ee183167b6/crates/blockifier_regression_test/src/test_state_reader.rs#L137)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a TODO to use `StarknetVersion::latest()` [when it's merged](https://reviewable.io/reviews/starkware-libs/sequencer/1042)
</blockquote></details>

Why? block number 700,000 will always use this version

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/956)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier_regression_test/src/state_reader/test.rs` line 17 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O810qoW6_rDqNZNJOp8:-O810qoW6_rDqNZNJOp9:bc1srd3) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2152e7b0b2273ff8b14f814b2bc0977d36a54ac/crates/blockifier_regression_test/src/state_reader/test.rs#L17)):*
> ```XML
> pub fn test_block_number() -> BlockNumber {
>     BlockNumber(700000)
> }
> ```

move `test_block_number` above the `test_state_reader` fixture



_Code quote:_
```XML
#[fixture]
pub fn test_state_reader(test_block_number: BlockNumber) -> TestStateReader {
    TestStateReader::new_for_testing(test_block_number)
}

#[fixture]
pub fn test_block_number() -> BlockNumber {
    BlockNumber(700000)
}
```
___
*[`crates/blockifier_regression_test/src/state_reader/test.rs` line 29 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O811E7m9h4rpidMVNCJ:-O811E7nCSxMwYmbumM5:bpjqet5) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2152e7b0b2273ff8b14f814b2bc0977d36a54ac/crates/blockifier_regression_test/src/state_reader/test.rs#L29)):*
> ```XML
> #[rstest]
> pub fn test_get_starknet_version(test_state_reader: TestStateReader) {
>     assert!(test_state_reader.get_starknet_version().unwrap() == StarknetVersion::V0_13_2_1)
> ```

also, consider adding `use pretty_assertions::assert_eq;` at the top to get nice informative failures



_Suggestion:_
```XML
assert_eq!(test_state_reader.get_starknet_version().unwrap(), StarknetVersion::V0_13_2_1)
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O7htND70T_hju83mDOF:-O811XWi7vqRG2nS0dtk:b-z0x16s) ([raw file](https://github.com/starkware-libs/sequencer/blob/726943ebed83e0b3d0fa6653519409ee183167b6/crates/blockifier_regression_test/src/test_state_reader.rs#L137)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Why? block number 700,000 will always use this version
</blockquote></details>

ah, right

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/956)* status: 5 of 12 files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_regression_test/src/state_reader/test.rs` line 17 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O810qoW6_rDqNZNJOp8:-O81UqnfA_Xc6zH2CvqB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2152e7b0b2273ff8b14f814b2bc0977d36a54ac/crates/blockifier_regression_test/src/state_reader/test.rs#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move `test_block_number` above the `test_state_reader` fixture
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/state_reader/test.rs` line 29 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O811E7m9h4rpidMVNCJ:-O81V-gn50mPWGdlcecY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2152e7b0b2273ff8b14f814b2bc0977d36a54ac/crates/blockifier_regression_test/src/state_reader/test.rs#L29)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

also, consider adding `use pretty_assertions::assert_eq;` at the top to get nice informative failures
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/956)* status: all files reviewed, 6 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier_regression_test/src/json_test.rs` line 11 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O81Vav732qPcPCsU9-Y:-O81Vav732qPcPCsU9-Z:b-iolmmf) ([raw file](https://github.com/starkware-libs/sequencer/blob/c1ab32e917b28ab6305064e4494dd8a76e187e27/crates/blockifier_regression_test/src/json_test.rs#L11)):*
> ```XML
> #[fixture]
> fn block_header() -> BlockHeader {
>     let file_path = "src/json_objects/block_header.json";
> ```

the standard, I think, is to have a `resources` directory next to `src`.
see `fn read_json_file` and it's usages



_Code quote:_
```XML
"src/json_objects/block_header.json";
```
___
*[`crates/blockifier_regression_test/src/json_test.rs` line 16 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O81ZPRfCL56LfrkeeWZ:-O81ZPRfCL56LfrkeeW_:b-ihdnnk) ([raw file](https://github.com/starkware-libs/sequencer/blob/c1ab32e917b28ab6305064e4494dd8a76e187e27/crates/blockifier_regression_test/src/json_test.rs#L16)):*
> ```XML
> 
>     // Deserialize the JSON data into a BlockInfo struct
>     serde_json::from_reader(reader).expect("Failed to deserialize JSON")
> ```

please use `read_json_file`



_Code quote:_
```XML
    let file_path = "src/json_objects/block_header.json";
    let file = File::open(file_path).expect("Failed to open the file");
    let reader = BufReader::new(file);

    // Deserialize the JSON data into a BlockInfo struct
    serde_json::from_reader(reader).expect("Failed to deserialize JSON")
```
___
*[`crates/blockifier_regression_test/src/json_test.rs` line 22 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O81ZWD1DWfjQRVKAuPJ:-O81ZWD1DWfjQRVKAuPK:bgp8koh) ([raw file](https://github.com/starkware-libs/sequencer/blob/c1ab32e917b28ab6305064e4494dd8a76e187e27/crates/blockifier_regression_test/src/json_test.rs#L22)):*
> ```XML
> #[rstest]
> fn test_deserialize_block_header(block_header: BlockHeader) {
>     assert_eq!(block_header.block_number, BlockNumber(700000));
> ```

add `use pretty_assertions::assert_eq;` at the top of this module



_Code quote:_
```XML
assert_eq
```
___
*[`crates/blockifier_regression_test/src/state_reader/test.rs` line 29 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O811E7m9h4rpidMVNCJ:-O81ZjDk4cdQujJOBtCR:bcn64e8) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2152e7b0b2273ff8b14f814b2bc0977d36a54ac/crates/blockifier_regression_test/src/state_reader/test.rs#L29)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

what about `use pretty_assertions::assert_eq;`?
___
*[`crates/blockifier_regression_test/src/state_reader/test_state_reader.rs` line 82 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O81_Ya40EaB6MtWd9LA:-O81_Ya40EaB6MtWd9LB:bzh8fr9) ([raw file](https://github.com/starkware-libs/sequencer/blob/c1ab32e917b28ab6305064e4494dd8a76e187e27/crates/blockifier_regression_test/src/state_reader/test_state_reader.rs#L82)):*
> ```XML
>                 serde_json::from_value(json).map_err(serde_err_to_state_err)?;
>             let block_info: BlockInfo = block_header.try_into()?;
>             return Ok(block_info);
> ```

also works, right?



_Suggestion:_
```XML
            return Ok(serde_json::from_value(json).map_err(serde_err_to_state_err)?.try_into()?);
```
___
*[`crates/blockifier_regression_test/src/state_reader/test_state_reader.rs` line 88 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O81_4iJ5f8nzY1PW3no:-O81_4iJ5f8nzY1PW3np:bouckam) ([raw file](https://github.com/starkware-libs/sequencer/blob/c1ab32e917b28ab6305064e4494dd8a76e187e27/crates/blockifier_regression_test/src/state_reader/test_state_reader.rs#L88)):*
> ```XML
>         Err(StateError::StateReadError(
>             "starknet_getBlockWithTxHashes should return json value of type Object ".to_string(),
>         ))
> ```

I prefer you write the error next to where it originates - use `unwrap_or_else` to emulate that



_Suggestion:_
```XML
        let block_header_map = json.as_object_mut().unwrap_or_else(|| {
            Err(StateError::StateReadError(
                "starknet_getBlockWithTxHashes should return json value of type Object ".to_string(),
            )))?;
        
        if block_header_map.get("l2_gas_price").is_none() {
            // In old blocks, the l2_gas_price field is not present.
            block_header_map.insert(
                "l2_gas_price".to_string(),
                to_value(default_l2_price).map_err(serde_err_to_state_err)?,
            );
        }

        let block_header: BlockHeader =
            serde_json::from_value(json).map_err(serde_err_to_state_err)?;
        let block_info: BlockInfo = block_header.try_into()?;
        return Ok(block_info);
    }

        // The json value should be an object.
        
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/956)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/956)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier_regression_test/src/json_test.rs` line 11 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O81Vav732qPcPCsU9-Y:-O81bhNO216TaOAnxRoy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c1ab32e917b28ab6305064e4494dd8a76e187e27/crates/blockifier_regression_test/src/json_test.rs#L11)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the standard, I think, is to have a `resources` directory next to `src`.
see `fn read_json_file` and it's usages
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/json_test.rs` line 16 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O81ZPRfCL56LfrkeeWZ:-O81cK8Q73bJXnmcnLqc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c1ab32e917b28ab6305064e4494dd8a76e187e27/crates/blockifier_regression_test/src/json_test.rs#L16)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please use `read_json_file`
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/json_test.rs` line 22 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O81ZWD1DWfjQRVKAuPJ:-O81eIH-43SVFkncqdvs:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c1ab32e917b28ab6305064e4494dd8a76e187e27/crates/blockifier_regression_test/src/json_test.rs#L22)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add `use pretty_assertions::assert_eq;` at the top of this module
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/state_reader/test.rs` line 29 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O811E7m9h4rpidMVNCJ:-O81erZtAKXg2GqZMMCQ:b2nhkz1) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2152e7b0b2273ff8b14f814b2bc0977d36a54ac/crates/blockifier_regression_test/src/state_reader/test.rs#L29)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what about `use pretty_assertions::assert_eq;`?
</blockquote></details>

OPS
___
*[`crates/blockifier_regression_test/src/state_reader/test_state_reader.rs` line 82 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O81_Ya40EaB6MtWd9LA:-O81fWixEwuzvaBLYfoW:b-i8o359) ([raw file](https://github.com/starkware-libs/sequencer/blob/c1ab32e917b28ab6305064e4494dd8a76e187e27/crates/blockifier_regression_test/src/state_reader/test_state_reader.rs#L82)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

also works, right?
</blockquote></details>

Almost, need a type annotation
___
*[`crates/blockifier_regression_test/src/state_reader/test_state_reader.rs` line 88 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O81_4iJ5f8nzY1PW3no:-O81hp-zEDSfj4K1c5oI:b-uno9fs) ([raw file](https://github.com/starkware-libs/sequencer/blob/c1ab32e917b28ab6305064e4494dd8a76e187e27/crates/blockifier_regression_test/src/state_reader/test_state_reader.rs#L88)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I prefer you write the error next to where it originates - use `unwrap_or_else` to emulate that
</blockquote></details>

It does not work,  block_header_map has type issues, I did something else

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/956)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier_regression_test/src/state_reader/test_state_reader.rs` line 88 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O81_4iJ5f8nzY1PW3no:-O81ly8z26fTszHB9sGM:btv7vc5) ([raw file](https://github.com/starkware-libs/sequencer/blob/c1ab32e917b28ab6305064e4494dd8a76e187e27/crates/blockifier_regression_test/src/state_reader/test_state_reader.rs#L88)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

It does not work,  block_header_map has type issues, I did something else
</blockquote></details>

hmmm... how about [ok_or](https://doc.rust-lang.org/std/option/enum.Option.html#method.ok_or)?
```
        let block_header_map = json.as_object_mut().ok_or(StateError::StateReadError(
            "starknet_getBlockWithTxHashes should return JSON value of type Object".to_string(),
        ))?;
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/956)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier_regression_test/src/state_reader/test_state_reader.rs` line 88 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/956#-O81_4iJ5f8nzY1PW3no:-O81yCAL1v3hB_jACKaF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c1ab32e917b28ab6305064e4494dd8a76e187e27/crates/blockifier_regression_test/src/state_reader/test_state_reader.rs#L88)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

hmmm... how about [ok_or](https://doc.rust-lang.org/std/option/enum.Option.html#method.ok_or)?
```
        let block_header_map = json.as_object_mut().ok_or(StateError::StateReadError(
            "starknet_getBlockWithTxHashes should return JSON value of type Object".to_string(),
        ))?;
```
</blockquote></details>

Done.

**Pull request merged**
