### PR TITLE
chore(starknet_integration_tests): removing sequencer node compilation from the e2e integration test

### PR DESCRIPTION
**Pull request by lev-starkware**
**Stack**:
- #2683
- #2682 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2682)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/starknet_sequencer_node/src/test_utils/compilation.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2682#-OEAtDpNCx1bZvY0M32O:-OEAtDpNCx1bZvY0M32P:btwdu9w) ([raw file](https://github.com/starkware-libs/sequencer/blob/62c135706ca462f0d7daf88d0a433d96ff254abd/crates/starknet_sequencer_node/src/test_utils/compilation.rs#L79)):*
> ```XML
> }
> 
> pub fn get_node_executable_path() -> Result<String, io::Error> {
> ```

Do we need it as a pub function?



_Code quote:_
```XML
pub 
```
___
*[`crates/starknet_sequencer_node/src/test_utils/compilation.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2682#-OEAtHKd-x9eI3orT6ih:-OEAtHKd-x9eI3orT6ii:b8ndy1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/62c135706ca462f0d7daf88d0a433d96ff254abd/crates/starknet_sequencer_node/src/test_utils/compilation.rs#L83)):*
> ```XML
>         Ok(path) => Ok(path.to_string_lossy().to_string()),
>         Err(e) => Err(e),
>     }
> ```

This can be shortened by using the `map` function, please check it out
https://doc.rust-lang.org/std/result/enum.Result.html#method.map



_Code quote:_
```XML
    match resolve_project_relative_path(NODE_EXECUTABLE_PATH) {
        Ok(path) => Ok(path.to_string_lossy().to_string()),
        Err(e) => Err(e),
    }
```
___
*[`.github/workflows/sequencer_integration_tests.yml` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2682#-OEAsAORAY6uqsiLiUAI:-OEAsAOS6UQ77DfgATQE:b7ptpzt) ([raw file](https://github.com/starkware-libs/sequencer/blob/62c135706ca462f0d7daf88d0a433d96ff254abd/.github/workflows/sequencer_integration_tests.yml#L28)):*
> ```YAML
>       - run: |
>           cargo build --bin e2e_integration_test
>           cargo build --bin starknet_sequencer_node
> ```

Please first build the node, and then the test (this is not a functional difference, but this makes more sense to me in terms of order).



_Code quote:_
```YAML
cargo build --bin starknet_sequencer_node
```
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2682#-OEAsUPZ3lCRbIN6xHnN:-OEAsUPZ3lCRbIN6xHnO:br8kgjc) ([raw file](https://github.com/starkware-libs/sequencer/blob/62c135706ca462f0d7daf88d0a433d96ff254abd/crates/starknet_integration_tests/src/end_to_end_integration.rs#L64)):*
> ```XML
>             panic!("Node executable should be available: {}", e);
>         }
>     };
> ```

Please move this chunk to where the compilation code used to be. I.e., replace compilation with this.



_Code quote:_
```XML
    info!("Checking that sequencer node executable is present.");
    let node_executable: String = match get_node_executable_path() {
        Ok(path) => path,
        Err(e) => {
            error!(
                "Sequencer node binary is not present. Please compile it using 'cargo build --bin \
                 starknet_sequencer_node' command."
            );
            panic!("Node executable should be available: {}", e);
        }
    };
```
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2682#-OEAsior4mEJeA4f5uac:-OEAsios-ZTNWTbecIRR:b-gi2aw1) ([raw file](https://github.com/starkware-libs/sequencer/blob/62c135706ca462f0d7daf88d0a433d96ff254abd/crates/starknet_integration_tests/src/end_to_end_integration.rs#L72)):*
> ```XML
>     info!("Running sequencer node.");
>     let node_run_handle =
>         spawn_run_node(integration_test_setup.node_config_path, node_executable).await;
> ```

There's only a single exectuable, no need to pass it as an arg. Please revert this change.



_Code quote:_
```XML
, node_executable
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2682)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`.github/workflows/sequencer_integration_tests.yml` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2682#-OEAsAORAY6uqsiLiUAI:-OEDfNDp2Djvei0Zti_-:bzhekm6) ([raw file](https://github.com/starkware-libs/sequencer/blob/62c135706ca462f0d7daf88d0a433d96ff254abd/.github/workflows/sequencer_integration_tests.yml#L28)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please first build the node, and then the test (this is not a functional difference, but this makes more sense to me in terms of order).
</blockquote></details>

When I chose this order, I took two things into consideration:
1. `e2e_integration_test` spawns `starknet_sequencer_node`.
2. It is the right lexicographic order, even after renaming.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2682#-OEAsUPZ3lCRbIN6xHnN:-OEDqvi_6wnngrpfNYiu:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/62c135706ca462f0d7daf88d0a433d96ff254abd/crates/starknet_integration_tests/src/end_to_end_integration.rs#L64)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please move this chunk to where the compilation code used to be. I.e., replace compilation with this.
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2682#-OEAsior4mEJeA4f5uac:-OEDqhSqDFEnMunhTUb8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/62c135706ca462f0d7daf88d0a433d96ff254abd/crates/starknet_integration_tests/src/end_to_end_integration.rs#L72)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

There's only a single exectuable, no need to pass it as an arg. Please revert this change.
</blockquote></details>

Done.
___
*[`crates/starknet_sequencer_node/src/test_utils/compilation.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2682#-OEAtDpNCx1bZvY0M32O:-OEDqodh0tLcetP5a_2d:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/62c135706ca462f0d7daf88d0a433d96ff254abd/crates/starknet_sequencer_node/src/test_utils/compilation.rs#L79)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Do we need it as a pub function?
</blockquote></details>

Done.
___
*[`crates/starknet_sequencer_node/src/test_utils/compilation.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2682#-OEAtHKd-x9eI3orT6ih:-OEDqlmpDvropVHszpp0:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/62c135706ca462f0d7daf88d0a433d96ff254abd/crates/starknet_sequencer_node/src/test_utils/compilation.rs#L83)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

This can be shortened by using the `map` function, please check it out
https://doc.rust-lang.org/std/result/enum.Result.html#method.map
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2682)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @lev-starkware)

___
*[`.github/workflows/sequencer_integration_tests.yml` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2682#-OEAsAORAY6uqsiLiUAI:-OEDzKNa6Kya66AAIKE_:b-4syhxq) ([raw file](https://github.com/starkware-libs/sequencer/blob/62c135706ca462f0d7daf88d0a433d96ff254abd/.github/workflows/sequencer_integration_tests.yml#L28)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

When I chose this order, I took two things into consideration:
1. `e2e_integration_test` spawns `starknet_sequencer_node`.
2. It is the right lexicographic order, even after renaming.
</blockquote></details>

I see, let me explain the motivation though. 
The first and foremost issue here is the node itself, not the tester. As such, it should be built first -- there's no point in building the test if the node fails.
Moreover, we intend to have plenty of other integration tests such as this with differet names, some precede and some succeed the node name lexicographically. I'd like them all to be consistently formatted, regardless of that.
As such, please apply the requested change :pray: 
___
*[`crates/starknet_sequencer_node/src/test_utils/compilation.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2682#-OEEBeXS3vcTA7y_VNoU:-OEEBeXS3vcTA7y_VNoV:b-t03e6l) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4e3619c53b8371b11e0d1f0880bbce6b7c5ed7b/crates/starknet_sequencer_node/src/test_utils/compilation.rs#L96)):*
> ```XML
>     }
>     true
> }
> ```

Please change this to a function that returns the path, or panics with the current error message otherwise.
Then, tests won't have to include a pre-test verification of the node existence, but will simply fail when trying to run the non-existent node. 
It will also assure that the error message (i.e., 'run cargo build ...`) will always be presented in case the node is missing, even if a test forgot to check it explicitlity, or didn't turn on tracing.



_Code quote:_
```XML
pub fn check_node_executable_present() -> bool {
    if get_node_executable_path().is_err() {
        error!(
            "Sequencer node binary is not present. Please compile it using 'cargo build --bin \
             starknet_sequencer_node' command."
        );
        return false;
    }
    true
}
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2682)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @lev-starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2682#-OEECJO00qcYprGwidhi:-OEECJO00qcYprGwidhj:b5lfo65) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4e3619c53b8371b11e0d1f0880bbce6b7c5ed7b/crates/starknet_integration_tests/src/end_to_end_integration.rs#L60)):*
> ```XML
>     if !check_node_executable_present() {
>         panic!("Node executable is not present.");
>     }
> ```

This can be removed, please see comment below.



_Code quote:_
```XML
    info!("Checking that the sequencer node executable is present.");
    if !check_node_executable_present() {
        panic!("Node executable is not present.");
    }
```

**Review by lev-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2682)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`.github/workflows/sequencer_integration_tests.yml` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2682#-OEAsAORAY6uqsiLiUAI:-OEEcK_VE66bk9LfgZml:b-mwvkes) ([raw file](https://github.com/starkware-libs/sequencer/blob/62c135706ca462f0d7daf88d0a433d96ff254abd/.github/workflows/sequencer_integration_tests.yml#L28)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I see, let me explain the motivation though. 
The first and foremost issue here is the node itself, not the tester. As such, it should be built first -- there's no point in building the test if the node fails.
Moreover, we intend to have plenty of other integration tests such as this with differet names, some precede and some succeed the node name lexicographically. I'd like them all to be consistently formatted, regardless of that.
As such, please apply the requested change :pray:
</blockquote></details>

Done. In the PR 2683
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2682#-OEECJO00qcYprGwidhi:-OEEcfA6E3H836wEHGNb:b-a2ujfl) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4e3619c53b8371b11e0d1f0880bbce6b7c5ed7b/crates/starknet_integration_tests/src/end_to_end_integration.rs#L60)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

This can be removed, please see comment below.
</blockquote></details>

Changed.
___
*[`crates/starknet_sequencer_node/src/test_utils/compilation.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2682#-OEEBeXS3vcTA7y_VNoU:-OEEexse8supFVrSLzJB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4e3619c53b8371b11e0d1f0880bbce6b7c5ed7b/crates/starknet_sequencer_node/src/test_utils/compilation.rs#L96)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please change this to a function that returns the path, or panics with the current error message otherwise.
Then, tests won't have to include a pre-test verification of the node existence, but will simply fail when trying to run the non-existent node. 
It will also assure that the error message (i.e., 'run cargo build ...`) will always be presented in case the node is missing, even if a test forgot to check it explicitlity, or didn't turn on tracing.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2682)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @lev-starkware)

___
*[`crates/starknet_sequencer_node/src/test_utils/compilation.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2682#-OEFid-NEYzkcMp4rPz8:-OEFid-NEYzkcMp4rPz9:b-lkn7un) ([raw file](https://github.com/starkware-libs/sequencer/blob/01b308274fd5a729bc219cfe030a357c9a35281f/crates/starknet_sequencer_node/src/test_utils/compilation.rs#L94)):*
> ```XML
>             panic!("Node executable should be available");
>         }
>     }
> ```

Generally there's no need to use `match` for `Result`/`Option` types as there are already available functions that do just that. In this case, to apply a function on `Ok` values, and to apply another function on `Err` values, you can use `map_or_else`.

Link to docs: https://doc.rust-lang.org/std/result/enum.Result.html#method.map_or_else

Here's an example of how it might look like

```
    resolve_project_relative_path(NODE_EXECUTABLE_PATH).map_or_else(
        |_| {
            error!(
                "Sequencer node binary is not present. Please compile it using 'cargo build --bin \
                 starknet_sequencer_node' command."
            );
            panic!("Node executable should be available");
        },
        |path| path.to_string_lossy().to_string(),
    );
```



_Code quote:_
```XML
    match resolve_project_relative_path(NODE_EXECUTABLE_PATH)
        .map(|path| path.to_string_lossy().to_string())
    {
        Ok(path) => path,
        Err(_) => {
            error!(
                "Sequencer node binary is not present. Please compile it using 'cargo build --bin \
                 starknet_sequencer_node' command."
            );
            panic!("Node executable should be available");
        }
    }
```

**Comment by lev-starkware** [comment]
✓ Commit merged in pull request [#2683](https://github.com/starkware-libs/sequencer/pull/2683)

**Pull request closed without merging**
