### PR TITLE
test(mempool): remove full content from mempool content

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/591)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/591)* status: 0 of 1 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/591#-O5ChhgcA_KWq0EbBwA8:-O5ChhgcA_KWq0EbBwA9:b-roc0mh) (no related file):*
STACK OF PRS:
1. #590 
2. #560 
3. #591 (YOU'RE HERE)
4. #592 
5. #534

___

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/591)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/591#-O5DgK4LCUmCctkf-zdF:-O5DgK4M8MsFkWhOkG68:bflmg3h) (no related file):*
Why removing? We'll have a full one, right?

___

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/591)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/591#-O5DgK4LCUmCctkf-zdF:-O5HfRAr5gZ0uskGAEWX:b-3peig3) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why removing? We'll have a full one, right?
</blockquote></details>

Currently, we don't use it. If needed, it will be added later.

___

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/591)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/591#-O5DgK4LCUmCctkf-zdF:-O5Ht8dD9Hou8SBEq9Mw:b-1d49n4) (no related file):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Currently, we don't use it. If needed, it will be added later.
</blockquote></details>

Consult Gilad, please? :grimacing: 

___

**Pull request merged**
