### PR TITLE
refactor(batcher): remove the mempool stream

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
* **#1597** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1597?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1582** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1582?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Yael-Starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1582)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @alonh5)

___
*[`crates/batcher/src/block_builder.rs` line 77 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1582#-OAHI8xo2cugyPAPvRTo:-OAI1eo4EyfvXcpNCUwi:bogbnma) ([raw file](https://github.com/starkware-libs/sequencer/blob/35f5ff7f325195b0439f5794f340e7402b091d3d/crates/batcher/src/block_builder.rs#L77)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Just making sure this could have been removed regardless right? (It's okay you put it in this PR).
</blockquote></details>

you're right.
___
*[`crates/batcher/src/block_builder.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1582#-OAHJL_773kER9goL7L3:-OAI4VyoCohiQJC2aVy2:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e41941e963731293d2187072bc15ddf4d2d3a026/crates/batcher/src/block_builder.rs#L155)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Let's sleep here for 1 second and keep the TODO to consider, Right now it's spamming the mempool (and therefore the logs).
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1582#-OAHLDyI0BDSs86XA0Al:-OAHs33LD2u-810aYcjL:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e41941e963731293d2187072bc15ddf4d2d3a026/crates/batcher/src/proposal_manager.rs#L25)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You can remove in this PR :)
</blockquote></details>

Done.
___
*[`crates/batcher/src/proposal_manager.rs` line 210 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1582#-OAHVMi83pTMmyB4aPrK:-OAHs9CZDB7_DXsY3arG:b-cbou1r) ([raw file](https://github.com/starkware-libs/sequencer/blob/e41941e963731293d2187072bc15ddf4d2d3a026/crates/batcher/src/proposal_manager.rs#L210)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you check if we actually need to store this handle or maybe there's a cleaner way? (Not for this PR)
</blockquote></details>

Ack, will do
___
*[`crates/batcher/src/proposal_manager_test.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1582#-OAHSJFXB1pR2--jW4BV:-OAHsa3E-6-3u_TLys5f:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/e41941e963731293d2187072bc15ddf4d2d3a026/crates/batcher/src/proposal_manager_test.rs#L26)):*
> ```XML
> 
> const INITIAL_HEIGHT: BlockNumber = BlockNumber(3);
> const GENERATION_TIMEOUT: tokio::time::Duration = tokio::time::Duration::from_secs(1);
> ```

done
___
*[`crates/batcher/src/proposal_manager_test.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1582#-OAHTEWNAomUMDRxFjLH:-OAHscNk4dPC-28ym3Et:bdyjanr) ([raw file](https://github.com/starkware-libs/sequencer/blob/35f5ff7f325195b0439f5794f340e7402b091d3d/crates/batcher/src/proposal_manager_test.rs#L146)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

No need to mock get txs from mempool anymore?
</blockquote></details>

The block_builder is getting transactions from the mempool now, and here the block_builder is being mocked, so there is no need to  feed it with a mempool mock.
In the modified block_builder test, the mempool is mocked as an input to the block_builder.
___
*[`crates/batcher/src/proposal_manager_test.rs` line 287 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1582#-OAHXXCABb7JJduBAsY0:-OAI3t5dDWjWrhhla5ae:bw2p0kr) ([raw file](https://github.com/starkware-libs/sequencer/blob/e41941e963731293d2187072bc15ddf4d2d3a026/crates/batcher/src/proposal_manager_test.rs#L287)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why do you need these two separate functions? Is the sleep() the only difference?
</blockquote></details>

as we discussed, yes they are the same except for the sleep. added a comment to clarify.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1582)* status: all files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware)

___
*[`config/mempool/default_config.json` line 712 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1582#-OAIhybMCna8mJgkreKA:-OAIhybN4N7nC1cGG7U_:b18e0go) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb40cc3556e7391b342913e80000cbec3eb7332c/config/mempool/default_config.json#L712)):*
> ```JSON
>     "value": ""
>   }
> }
> ```

Restore blank line at eof
___
*[`crates/batcher/src/proposal_manager_test.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1582#-OAHTEWNAomUMDRxFjLH:-OAIiNnB6dMSX1qEEwhW:b-1k17ut) ([raw file](https://github.com/starkware-libs/sequencer/blob/35f5ff7f325195b0439f5794f340e7402b091d3d/crates/batcher/src/proposal_manager_test.rs#L146)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

The block_builder is getting transactions from the mempool now, and here the block_builder is being mocked, so there is no need to  feed it with a mempool mock.
In the modified block_builder test, the mempool is mocked as an input to the block_builder.
</blockquote></details>

Got it, thanks for the explanation :)
___
*[`crates/batcher/src/proposal_manager_test.rs` line 277 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1582#-OAIjLxZ6W2uqbaExgrv:-OAIjLx_8hYJ2aHP1IZZ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb40cc3556e7391b342913e80000cbec3eb7332c/crates/batcher/src/proposal_manager_test.rs#L277)):*
> ```XML
> }
> 
> fn arbitrary_deadline() -> tokio::time::Instant {
> ```





_Suggestion:_
```XML
proposal_deadline
```
___
*[`crates/batcher/src/proposal_manager_test.rs` line 286 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1582#-OAIkERF5wNyNcIzvv0L:-OAIkERF5wNyNcIzvv0M:b-mvw50a) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb40cc3556e7391b342913e80000cbec3eb7332c/crates/batcher/src/proposal_manager_test.rs#L286)):*
> ```XML
>     let mut mock_block_builder = MockBlockBuilderTrait::new();
>     mock_block_builder.expect_build_block().return_once(move |_, _, _| {
>         std::thread::sleep(BLOCK_GENERATION_TIMEOUT * 10);
> ```

Thinking about this again, wouldn't the build block operation terminate at the deadline inspite of this sleep? In that case multiplying by 10 doesn't fo anything and could be misleading.



_Code quote:_
```XML
std::thread::sleep(BLOCK_GENERATION_TIMEOUT * 10);
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1582)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`config/mempool/default_config.json` line 712 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1582#-OAIhybMCna8mJgkreKA:-OAIpzEVCiPQwljuRI4f:btenmf9) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb40cc3556e7391b342913e80000cbec3eb7332c/config/mempool/default_config.json#L712)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Restore blank line at eof
</blockquote></details>

it is auto generated, I can't change it.
___
*[`crates/batcher/src/proposal_manager_test.rs` line 277 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1582#-OAIjLxZ6W2uqbaExgrv:-OAIqEOR4Is-EdFv02kI:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb40cc3556e7391b342913e80000cbec3eb7332c/crates/batcher/src/proposal_manager_test.rs#L277)):*
> ```XML
> }
> 
> fn arbitrary_deadline() -> tokio::time::Instant {
> ```

done
___
*[`crates/batcher/src/proposal_manager_test.rs` line 286 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1582#-OAIkERF5wNyNcIzvv0L:-OAIpnSTAxqFVlhEfmeU:b-s2they) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb40cc3556e7391b342913e80000cbec3eb7332c/crates/batcher/src/proposal_manager_test.rs#L286)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Thinking about this again, wouldn't the build block operation terminate at the deadline inspite of this sleep? In that case multiplying by 10 doesn't fo anything and could be misleading.
</blockquote></details>

this is a mock block builder, it doesn't call the real block builder, so the timeout won't expire.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1582)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`config/mempool/default_config.json` line 712 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1582#-OAIhybMCna8mJgkreKA:-OALzzbH120dYg0IWGIF:b8090t) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb40cc3556e7391b342913e80000cbec3eb7332c/config/mempool/default_config.json#L712)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

it is auto generated, I can't change it.
</blockquote></details>

actually you're right, I have no idea how it was deleted. , now back!

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1582#-:-OAMMkCL2tzjaF9_B0aa:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)

___
*[`config/mempool/default_config.json` line 712 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1582#-OAIhybMCna8mJgkreKA:-OAMI5Fe3QhJAjxrPns_:b-iskap9) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb40cc3556e7391b342913e80000cbec3eb7332c/config/mempool/default_config.json#L712)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

actually you're right, I have no idea how it was deleted. , now back!
</blockquote></details>

It is auto generated that's why it was deleted but you can still edit it after. Itay is working on adding that extra line to the auto generation.
___
*[`crates/batcher/src/proposal_manager_test.rs` line 286 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1582#-OAIkERF5wNyNcIzvv0L:-OAMMebQDGMWymJZU0a4:bafhagk) ([raw file](https://github.com/starkware-libs/sequencer/blob/cb40cc3556e7391b342913e80000cbec3eb7332c/crates/batcher/src/proposal_manager_test.rs#L286)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

this is a mock block builder, it doesn't call the real block builder, so the timeout won't expire.
</blockquote></details>

Oh right.

**Pull request merged**
