### PR TITLE
chore: create try from referance of casm contract class method

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/910)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#910** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/910?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/910)* status: 0 of 4 files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/execution/contract_class.rs` line 447 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/910#-O7O-YgA9dqGmpMTj5Jm:-O7O-YgA9dqGmpMTj5Jn:b-41pcay) ([raw file](https://github.com/starkware-libs/sequencer/blob/604fedee4ec8498fb1c80deaa5742ddfee90d69e/crates/blockifier/src/execution/contract_class.rs#L447)):*
> ```XML
>         )
>     }
> }
> ```

This is a new code.
This is the goal of this PR. 



_Code quote:_
```XML
impl TryFrom<&CasmContractClass> for ContractClassV1 {
    type Error = ProgramError;

    fn try_from(class: &CasmContractClass) -> Result<Self, Self::Error> {
        try_from_casm_contrcat_class_internal(
            &class.bytecode,
            &class.hints,
            &class.entry_points_by_type,
            class.bytecode_segment_lengths.clone(),
            &class.compiler_version,
        )
    }
}
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 458 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/910#-O7O-hIX-0WTt7OjG9z3:-O7O-hIX-0WTt7OjG9z4:b-179nw7) ([raw file](https://github.com/starkware-libs/sequencer/blob/604fedee4ec8498fb1c80deaa5742ddfee90d69e/crates/blockifier/src/execution/contract_class.rs#L458)):*
> ```XML
>     sn_api_to_cairo_vm_program(deprecated_program)
>         .map_err(|err| DeserializationError::custom(err.to_string()))
> }
> ```

This is not a new code. This is only an artifact of the diff showing the body of the new function (`try_from_casm_contrcat_class_internal`) as the body of `impl TryFrom<CasmContractClass> for ContractClassV1`



_Code quote:_
```XML
// V0 utilities.

/// Converts the program type from SN API into a Cairo VM-compatible type.
pub fn deserialize_program<'de, D: Deserializer<'de>>(
    deserializer: D,
) -> Result<Program, D::Error> {
    let deprecated_program = DeprecatedProgram::deserialize(deserializer)?;
    sn_api_to_cairo_vm_program(deprecated_program)
        .map_err(|err| DeserializationError::custom(err.to_string()))
}
```

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/910#-:-O7c503G8xQskQzuh7fa:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Sep 25, 5:55 AM EDT**: @ArniStarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/910).

**Pull request merged**
