### PR TITLE
chore(blockifier): replace sierra_program with casm field for NativeContractClassV1

### PR DESCRIPTION
**Pull request by avivg-starkware**

### CODE REVIEW

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1540)* status: all files reviewed, 3 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1540#-OACyQ7N38GjGpd91K_9:-OACyQ7N38GjGpd91K_A:ba3dfna) ([raw file](https://github.com/starkware-libs/sequencer/blob/226114f7712a63b3e32a3bd7e4aab6d95607e9e2/crates/blockifier/src/execution/contract_class.rs#L14)):*
> ```XML
> };
> use cairo_lang_starknet_classes::NestedIntList;
> // use cairo_lang_utils::bigint::BigUintAsHex;
> ```

Remove?



_Code quote:_
```XML
// use cairo_lang_utils::bigint::BigUintAsHex;
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 634 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1540#-OACyVDHCR2_9S6-JETy:-OACyVDHCR2_9S6-JETz:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/226114f7712a63b3e32a3bd7e4aab6d95607e9e2/crates/blockifier/src/execution/contract_class.rs#L634)):*
> ```XML
>     pub executor: AotNativeExecutor,
>     entry_points_by_type: EntryPointsByType<NativeEntryPoint>,
>     casm: Option<starknet_api::contract_class::ContractClass>,
> ```





_Suggestion:_
```XML
   casm: ContractClassV1,
```
___
*[`crates/blockifier/src/execution/contract_class.rs` line 642 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1540#-OACzI1p86F5CH3ogp8X:-OACzI1p86F5CH3ogp8Y:b31bf4f) ([raw file](https://github.com/starkware-libs/sequencer/blob/226114f7712a63b3e32a3bd7e4aab6d95607e9e2/crates/blockifier/src/execution/contract_class.rs#L642)):*
> ```XML
>             executor,
>             entry_points_by_type: EntryPointsByType::from(&sierra_contract_class),
>             casm: None,
> ```

Please compile the sierra to casm. You can look [here](https://github.com/starkware-libs/sequencer/blob/2a0858286426055aca3c3cfeca15f0b599b2f4fd/crates/gateway/src/compilation.rs#L48).



_Code quote:_
```XML
            casm: None,
```

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1540)* status: all files reviewed, 3 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 642 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1540#-OACzI1p86F5CH3ogp8X:-OADlwg00OoRWfJCt07K:bb31bse) ([raw file](https://github.com/starkware-libs/sequencer/blob/226114f7712a63b3e32a3bd7e4aab6d95607e9e2/crates/blockifier/src/execution/contract_class.rs#L642)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please compile the sierra to casm. You can look [here](https://github.com/starkware-libs/sequencer/blob/2a0858286426055aca3c3cfeca15f0b599b2f4fd/crates/gateway/src/compilation.rs#L48).
</blockquote></details>

On a second thought: can you please get it as an input?

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1540)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1540#-OACyQ7N38GjGpd91K_9:-OADq5zL47FuGkMVlrRY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/226114f7712a63b3e32a3bd7e4aab6d95607e9e2/crates/blockifier/src/execution/contract_class.rs#L14)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 634 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1540#-OACyVDHCR2_9S6-JETy:-OADw78P7UbnAeqdlew-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/226114f7712a63b3e32a3bd7e4aab6d95607e9e2/crates/blockifier/src/execution/contract_class.rs#L634)):*
> ```XML
>     pub executor: AotNativeExecutor,
>     entry_points_by_type: EntryPointsByType<NativeEntryPoint>,
>     casm: Option<starknet_api::contract_class::ContractClass>,
> ```

Done.
___
*[`crates/blockifier/src/execution/contract_class.rs` line 642 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1540#-OACzI1p86F5CH3ogp8X:-OADw8Cy6nboClba_mYC:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/226114f7712a63b3e32a3bd7e4aab6d95607e9e2/crates/blockifier/src/execution/contract_class.rs#L642)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

On a second thought: can you please get it as an input?
</blockquote></details>

Done.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1540)* status: all files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 642 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1540#-OAEiI6ZAREL9SzRpb83:-OAEiI6ZAREL9SzRpb84:b2blo3q) ([raw file](https://github.com/starkware-libs/sequencer/blob/32d78fd1962dd3f114fa0fad4049bdf1ca7981cc/crates/blockifier/src/execution/contract_class.rs#L642)):*
> ```XML
>         sierra_contract_class: SierraContractClass,
>         casm: ContractClassV1,
>     ) -> ContractClassResult<Self> {
> ```

Is the result needed?
Same above



_Code quote:_
```XML
ContractClassResult<Self>
```

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1540)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 642 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1540#-OAEiI6ZAREL9SzRpb83:-OARqTzs4kN563wFRxUC:b-26snrm) ([raw file](https://github.com/starkware-libs/sequencer/blob/32d78fd1962dd3f114fa0fad4049bdf1ca7981cc/crates/blockifier/src/execution/contract_class.rs#L642)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is the result needed?
Same above
</blockquote></details>

Stayed from prev steps. not needed indeed, fixed.

**Pull request merged**
