### PR TITLE
fix(starknet_integration_tests): use AvailablePorts correctly in mempool p2p flow test

### PR DESCRIPTION
**Pull request by ShahakShama**

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
+reviewer:@lev-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2931#-:-OEtGL6SEKgOK8wzyMqW:bw1gi4r)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware and @lev-starkware)

**Review by lev-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2931#-:-OExfKbh5qrWfb9uhVOJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2931)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/starknet_integration_tests/tests/mempool_p2p_flow_test.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2931#-OExgzZG0JWLRURYQYXj:-OExgzZHCM8Qjt1cvxE_:b-kgx4lm) ([raw file](https://github.com/starkware-libs/sequencer/blob/34c98a06696a00fd766831e8089bdfd6b8e7d558/crates/starknet_integration_tests/tests/mempool_p2p_flow_test.rs#L88)):*
> ```XML
>         create_batcher_config(storage_for_test.batcher_storage_config, chain_info.clone());
>     let gateway_config = create_gateway_config(chain_info).await;
>     let http_server_config = create_http_server_config_to_be_deprecated().await;
> ```

Please deprecate :-)



_Code quote:_
```XML
create_http_server_config_to_be_deprecated
```

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2931)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/starknet_integration_tests/tests/mempool_p2p_flow_test.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2931#-OExgzZG0JWLRURYQYXj:-OExySCeA9Yud4IKRFn6:bk52cwn) ([raw file](https://github.com/starkware-libs/sequencer/blob/34c98a06696a00fd766831e8089bdfd6b8e7d558/crates/starknet_integration_tests/tests/mempool_p2p_flow_test.rs#L88)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please deprecate :-)
</blockquote></details>

Non-blocking, but please do it.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2931#-:-OEy74JW3w0p5ZpFjDJP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
