### PR TITLE
feat(blockifier): add call_contract cairo native syscall

### PR DESCRIPTION
**Pull request by PearsonWhite**
Implements `call_contract` in `NativeSyscallHandler`.

### CODE REVIEW

**Review by PearsonWhite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: 0 of 2 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1548#-OA4M7Tl5xJdAONqPO2n:-OA4M7Tl5xJdAONqPO2o:b-dw3y48) (no related file):*
In `test_track_resources`, the logic for what we expect has changed. Now, I'm not sure if the result is expected or not and I need clarification.

Previously, both the outer call and the inner call had to be (Cairo1 | Native) for the inner tracked_resource to be SierraGas.
Now, long as the inner is (Cairo1 | Native) I think SierraGas should be used.

Currently, one case fails: when outer is Cairo0 and inner is Cairo1, SierraGas is expected, but CairoSteps is used.
I've added a complete table of the results here in csv format:



_Code snippet:_
```
outer , inner , expected_outer , expected_inner , actual_outer , actual_expected , pass/fail
Cairo0 , Cairo0 , CairoSteps , CairoSteps , CairoSteps , CairoSteps , pass
Cairo0 , Cairo1 , CairoSteps , SierraGas , CairoSteps , CairoSteps , failed <--- Should this fail? Or is it expected?
Cairo1 , Cairo0 , SierraGas , CairoSteps , SierraGas , CairoSteps , pass
Cairo1 , Cairo1 , SierraGas , SierraGas , SierraGas , SierraGas , pass
Cairo0 , Native , CairoSteps , SierraGas , CairoSteps , SierraGas , pass
Native , Cairo1 , SierraGas , SierraGas , SierraGas , SierraGas , pass
Native , Cairo0 , SierraGas , CairoSteps , SierraGas , CairoSteps , pass
Cairo1 , Native , SierraGas , SierraGas , SierraGas , SierraGas , pass
Native , Native , SierraGas , SierraGas , SierraGas , SierraGas , pass
```

___

**Review by varex83 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @PearsonWhite)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1548#-OAHxdILBNPSAHkOKoPw:-OAHxdILBNPSAHkOKoPx:bolnvdv) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e422b72a501ab066ed8b126db2bf46f3c878338/crates/blockifier/src/execution/native/syscall_handler.rs#L225)):*
> ```XML
>             caller_address: self.contract_address,
>             call_type: CallType::Call,
>             initial_gas: u64::try_from(*remaining_gas).unwrap(),
> ```

Use `expect` instead of `unwrap` here

**Review by PearsonWhite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @varex83)

___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1548#-OAHwvw82Ak_Hb3V6RQH:-OAJr5ia-i_cCVES5HAZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e422b72a501ab066ed8b126db2bf46f3c878338/crates/blockifier/src/execution/native/syscall_handler.rs#L203)):*
<details><summary><i>Previously, varex83 (Bohdan Ohorodnii) wrote…</i></summary><blockquote>

Don't use expect, return runtime error instead
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/native/syscall_handler.rs` line 225 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1548#-OAHxdILBNPSAHkOKoPw:-OAJr61TE2JNFrRRkhqz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e422b72a501ab066ed8b126db2bf46f3c878338/crates/blockifier/src/execution/native/syscall_handler.rs#L225)):*
<details><summary><i>Previously, varex83 (Bohdan Ohorodnii) wrote…</i></summary><blockquote>

Use `expect` instead of `unwrap` here
</blockquote></details>

Done.

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @varex83)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1548#-OA4M7Tl5xJdAONqPO2n:-OAUS5nr8ECcmrnGOQLB:bpy7q9) (no related file):*
<details><summary><i>Previously, PearsonWhite wrote…</i></summary><blockquote>

In `test_track_resources`, the logic for what we expect has changed. Now, I'm not sure if the result is expected or not and I need clarification.

Previously, both the outer call and the inner call had to be (Cairo1 | Native) for the inner tracked_resource to be SierraGas.
Now, long as the inner is (Cairo1 | Native) I think SierraGas should be used.

Currently, one case fails: when outer is Cairo0 and inner is Cairo1, SierraGas is expected, but CairoSteps is used.
I've added a complete table of the results here in csv format:
</blockquote></details>

If I am not mistaken, if cairo0 contract calls cairo1 contract, we have decided to use the VM resources (meaning we do not use native in these cases), so both the outer and inner should be cairo steps in this case. @noaov1 could you please confirm 

___

**Review by PearsonWhite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @varex83)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1548#-OA4M7Tl5xJdAONqPO2n:-OATBlqi6PhBwvYyO10y:bjxr8wq) (no related file):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

If I am not mistaken, if cairo0 contract calls cairo1 contract, we have decided to use the VM resources (meaning we do not use native in these cases), so both the outer and inner should be cairo steps in this case. @noaov1 could you please confirm
</blockquote></details>

This has been changed in a recent rebase. Now I think it is working as expected. See updated logic/comments in `crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs`.

___

**Review by PearsonWhite — COMMENTED** [review]
> Dismissed @varex83 from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — DISMISSED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: all files reviewed, 1 unresolved discussion (waiting on @PearsonWhite)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1548#-OA4M7Tl5xJdAONqPO2n:-OB5fCwj2SU3C4y85t-f:be0mfv4) (no related file):*
<details><summary><i>Previously, PearsonWhite wrote…</i></summary><blockquote>

This has been changed in a recent rebase. Now I think it is working as expected. See updated logic/comments in `crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs`.
</blockquote></details>

@meship-starkware  you are right. Wrote some comment below. 

___
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 193 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1548#-OB4_sqGCr0iiyPngAi9:-OB4_sqGCr0iiyPngAiA:bx6wxc) ([raw file](https://github.com/starkware-libs/sequencer/blob/6b9e55501333324f5c4a6ca907d197b16e85baf9/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L193)):*
> ```XML
>     #[cfg(feature = "cairo_native")]
>     // If inner is Native, we expect inner to use SierraGas.
>     // This overrides previous logic.
> ```

If the outer call uses cairo steps, then we choose to run all the inner calls also with VM resources. 
This should not work, see [here](https://github.com/starkware-libs/sequencer/blob/03ef939f1959d29bf6a451c706c17f6db288871c/crates/blockifier/src/execution/execution_utils.rs#L73).



_Code quote:_
```XML
    // If inner is Native, we expect inner to use SierraGas.
    // This overrides previous logic.
```

**Review by PearsonWhite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 193 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1548#-OB4_sqGCr0iiyPngAi9:-OBBRA5R6pIbRcVQtyEx:b-l45m00) ([raw file](https://github.com/starkware-libs/sequencer/blob/6b9e55501333324f5c4a6ca907d197b16e85baf9/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L193)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

If the outer call uses cairo steps, then we choose to run all the inner calls also with VM resources. 
This should not work, see [here](https://github.com/starkware-libs/sequencer/blob/03ef939f1959d29bf6a451c706c17f6db288871c/crates/blockifier/src/execution/execution_utils.rs#L73).
</blockquote></details>

After rebasing, this no longer worked. Since this shouldn't have worked, that means the rebase fixed the execution logic, leaving only the test wrong. I've changed the logic for the test to match the VM. It should all be working as expected and passing now.

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by PearsonWhite — COMMENTED** [review]
Changed error mapping from `encode_str_as_felts` to `self.handle_error`.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548#-:-OBRBVSn54Qv78wLqvbT:b-czza7f)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware, @noaov1, and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by PearsonWhite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1548#-OB_ocRoD5yUabIQFI0J:-OBbtLPrAIa4boxUO_X_:bb7f2mf) (no related file):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Please rebase to resolve conflicts.
</blockquote></details>

done

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1 and @Yoni-Starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @PearsonWhite)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 205 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1548#-OBehqonDRGVDMjdE0uw:-OBehqonDRGVDMjdE0ux:b-r6lxtc) ([raw file](https://github.com/starkware-libs/sequencer/blob/4aab01ad47ca52b62511932da5e666efb9b6cfd5/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L205)):*
> ```XML
> ) {
>     let cairo_steps_contract = cairo_steps_contract_version.get_test_contract();
>     let sierra_gas_contract = FeatureContract::TestContract(CairoVersion::Cairo1);
> ```

Please fixturize this (add a case for native class)



_Code quote:_
```XML
sierra_gas_contract
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @PearsonWhite)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 32 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1548#-OBei8oPBrbP0WkhuahG:-OBei8oPBrbP0WkhuahH:b-2amhzg) ([raw file](https://github.com/starkware-libs/sequencer/blob/4aab01ad47ca52b62511932da5e666efb9b6cfd5/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L32)):*
> ```XML
> 
> #[test]
> fn test_call_contract_that_panics() {
> ```

Please add a TODO to support this test once we support reverts

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548#-:-OBfvhU99g7ts0bMmaMo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @PearsonWhite)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 202 at r12](https://reviewable.io/reviews/starkware-libs/sequencer/1548#-OBfukqq51eXqQCi6jC2:-OBfukqr-QKk6o2ZKVDi:b-dom1z2) ([raw file](https://github.com/starkware-libs/sequencer/blob/cdcb1105117e23288a5c30ed4cbfab1921b2ce4b/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L202)):*
> ```XML
> #[cfg_attr(
>   feature = "cairo_native",
>   test_case(CompilerBasedVersion::OldCairo1, CompilerBasedVersion::CairoVersion(CairoVersion::Native); "Cairo1_and_Native")
> ```

Thanks! non-blocking



_Suggestion:_
```XML
"OldCairo1_and_Native
```

**Review by PearsonWhite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 32 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1548#-OBei8oPBrbP0WkhuahG:-OBfybyI3IMN796x64uD:b-iwmm5x) ([raw file](https://github.com/starkware-libs/sequencer/blob/4aab01ad47ca52b62511932da5e666efb9b6cfd5/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L32)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Please add a TODO to support this test once we support reverts
</blockquote></details>

Added TODO
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 205 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1548#-OBehqonDRGVDMjdE0uw:-OBfyzVi8C3DqzNdbBNE:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/4aab01ad47ca52b62511932da5e666efb9b6cfd5/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L205)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Please fixturize this (add a case for native class)
</blockquote></details>

done

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1548#-:-OBg0z6l-rOQ7-rEiVdh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
