### PR TITLE
test(blockifier): insufficient amount new resource bounds

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/811)

### CODE REVIEW

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/811)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1026 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O7hjgQv22wf_BBJrAbe:-O7hjgQv22wf_BBJrAbf:bxeygim) ([raw file](https://github.com/starkware-libs/sequencer/blob/4f72f083e8447104aad3b8936263a52314124674/crates/blockifier/src/transaction/transactions_test.rs#L1026)):*
> ```XML
>             if resource == insufficient_resource
>         );
>     }
> ```

And the same for the gas_price below please (might be able to something better but this is sufficient for me).
And why no l1_data_gas in the amount?



_Suggestion:_
```XML
    for insufficient_resource in [L1Gas, L2Gas] {
        let mut invalid_resources = default_resource_bounds.clone();
        match insufficient_resource {
            L1Gas => invalid_resources.l1_gas.max_amount -= 1,
            L2Gas => invalid_resources.l2_gas.max_amount -= 1,
            _ => unreachable!(),
        }
        let invalid_v3_tx = account_invoke_tx(InvokeTxArgs {
            resource_bounds: ValidResourceBounds::AllResources(invalid_resources),
            nonce: nonce!(1),
            ..valid_invoke_tx_args.clone()
        });
        let execution_error = invalid_v3_tx.execute(state, block_context, true, true).unwrap_err();
        assert_matches!(
            execution_error,
            TransactionExecutionError::TransactionPreValidationError(
                TransactionPreValidationError::TransactionFeeError(
                    TransactionFeeError::MaxGasAmountTooLow{
                        resource,
                        ..}))
            if resource == insufficient_resource
        );
    }
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/811)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1026 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O7hjgQv22wf_BBJrAbe:-O7mJR6i9wPBRFBxyQKd:b-ziirc5) ([raw file](https://github.com/starkware-libs/sequencer/blob/4f72f083e8447104aad3b8936263a52314124674/crates/blockifier/src/transaction/transactions_test.rs#L1026)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

And the same for the gas_price below please (might be able to something better but this is sufficient for me).
And why no l1_data_gas in the amount?
</blockquote></details>

Done. The reason there's no test for the `l1_data_gas` is because the test didn't use the `use_kzg_da` flag. I added this, and then it failed the "successful execution", so I removed the successful execution (because, actually, there's no reason to assume `estimate_minimal_gas_vector` is sufficient to execute the tx, we just got lucky). If you want to reinsert this check, it needs to check either the tx is successful, or that the error is not any of the prevalidation errors we expect to pass.

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1026 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O7hjgQv22wf_BBJrAbe:-O7xuFvt8_YzzP0omZsQ:b-firsi2) ([raw file](https://github.com/starkware-libs/sequencer/blob/4f72f083e8447104aad3b8936263a52314124674/crates/blockifier/src/transaction/transactions_test.rs#L1026)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done. The reason there's no test for the `l1_data_gas` is because the test didn't use the `use_kzg_da` flag. I added this, and then it failed the "successful execution", so I removed the successful execution (because, actually, there's no reason to assume `estimate_minimal_gas_vector` is sufficient to execute the tx, we just got lucky). If you want to reinsert this check, it needs to check either the tx is successful, or that the error is not any of the prevalidation errors we expect to pass.
</blockquote></details>

Reinserted the "successful execution" check, as I explained in the above comment.

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/811)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1026 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O7hjgQv22wf_BBJrAbe:-O85wWyjA9LsGRoDRmpr:bkrbnap) ([raw file](https://github.com/starkware-libs/sequencer/blob/4f72f083e8447104aad3b8936263a52314124674/crates/blockifier/src/transaction/transactions_test.rs#L1026)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Reinserted the "successful execution" check, as I explained in the above comment.
</blockquote></details>

Great :+1: 
What made the valid_tx succeed in the end?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 945 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O85vJnuEhSHxuZAR8Lv:-O85vJnuEhSHxuZAR8Lw:bc6kiz0) ([raw file](https://github.com/starkware-libs/sequencer/blob/76547e3bc7eab4684bd1f90341d0833571f4cb36/crates/blockifier/src/transaction/transactions_test.rs#L945)):*
> ```XML
>     #[values(CairoVersion::Cairo0, CairoVersion::Cairo1)] account_cairo_version: CairoVersion,
> ) {
>     // TODO(Aner): test also with use_kzg_flag == true
> ```

remove the todo
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1015 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O85wL0u3Fmj0753AYW-:-O85wL0u3Fmj0753AYW0:b-x2pfnb) ([raw file](https://github.com/starkware-libs/sequencer/blob/76547e3bc7eab4684bd1f90341d0833571f4cb36/crates/blockifier/src/transaction/transactions_test.rs#L1015)):*
> ```XML
>     // contains all insufficient resources.
>     let resources_with_positive_amount = match use_kzg_da {
>         true => [L2Gas, L1DataGas],
> ```

Shouldn't the L1 resource also appear in here?



_Suggestion:_
```XML
> [L1Gas, L2Gas, L1DataGas],
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1047 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O85xMgi2peaOB9gI-SR:-O85xMgi2peaOB9gI-SS:b2kfe33) ([raw file](https://github.com/starkware-libs/sequencer/blob/76547e3bc7eab4684bd1f90341d0833571f4cb36/crates/blockifier/src/transaction/transactions_test.rs#L1047)):*
> ```XML
>             L1Gas => invalid_resources.l1_gas.max_price_per_unit -= 1,
>             L2Gas => invalid_resources.l2_gas.max_price_per_unit -= 1,
>             L1DataGas => invalid_resources.l1_data_gas.max_price_per_unit -= 1,
> ```

This fails a tx even if were use_kzg==False?



_Code quote:_
```XML
  L1DataGas => invalid_resources.l1_data_gas.max_price_per_unit -= 1,
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/811)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1026 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O7hjgQv22wf_BBJrAbe:-O86AH_aDL9j6aRq_AXe:bwa4nhn) ([raw file](https://github.com/starkware-libs/sequencer/blob/4f72f083e8447104aad3b8936263a52314124674/crates/blockifier/src/transaction/transactions_test.rs#L1026)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Great :+1: 
What made the valid_tx succeed in the end?
</blockquote></details>

What I wrote above - it can either succeed (in which case the nonce is increased), or fail, so long as the error is not one of the errors that we expect not to happen (in which case the nonce does not increase).
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 945 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O85vJnuEhSHxuZAR8Lv:-O86AFtS5myHgQ1s-y8e:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/76547e3bc7eab4684bd1f90341d0833571f4cb36/crates/blockifier/src/transaction/transactions_test.rs#L945)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

remove the todo
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1015 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O85wL0u3Fmj0753AYW-:-O86EYN1Bp4AjvgSfNVc:bckiiaw) ([raw file](https://github.com/starkware-libs/sequencer/blob/76547e3bc7eab4684bd1f90341d0833571f4cb36/crates/blockifier/src/transaction/transactions_test.rs#L1015)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Shouldn't the L1 resource also appear in here?
</blockquote></details>

Is it clearer this way? I can also put the bottom loop inside (shorter and less vars), though I think it's a bit less clear.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1047 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O85xMgi2peaOB9gI-SR:-O86AcGU-sFlCx0NIZcA:b-iec229) ([raw file](https://github.com/starkware-libs/sequencer/blob/76547e3bc7eab4684bd1f90341d0833571f4cb36/crates/blockifier/src/transaction/transactions_test.rs#L1047)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

This fails a tx even if were use_kzg==False?
</blockquote></details>

Yes, that's the spec I understood (though I guess it's better to double-check here). @Yoni-Starkware? There's also a question about whether `actual_gas_price` can be 0 for any resource, as this test assumes this scenario does not happen.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/811)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1047 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O85xMgi2peaOB9gI-SR:-O86_fk69w3_Qvd4pO2e:b8a6xwk) ([raw file](https://github.com/starkware-libs/sequencer/blob/76547e3bc7eab4684bd1f90341d0833571f4cb36/crates/blockifier/src/transaction/transactions_test.rs#L1047)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Yes, that's the spec I understood (though I guess it's better to double-check here). @Yoni-Starkware? There's also a question about whether `actual_gas_price` can be 0 for any resource, as this test assumes this scenario does not happen.
</blockquote></details>

Hmmm that's a good Q.
Since data gas amount might be 0, it's better to allow price 0 in this case.
I.e., skip the second check here: https://github.com/starkware-libs/sequencer/blob/faac38bf265d0a60f2948559f7f487992b585a25/crates/blockifier/src/transaction/account_transaction.rs#L405

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1047 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O85xMgi2peaOB9gI-SR:-O86iZO_5X9pMClLzSRs:btosez6) ([raw file](https://github.com/starkware-libs/sequencer/blob/76547e3bc7eab4684bd1f90341d0833571f4cb36/crates/blockifier/src/transaction/transactions_test.rs#L1047)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Hmmm that's a good Q.
Since data gas amount might be 0, it's better to allow price 0 in this case.
I.e., skip the second check here: https://github.com/starkware-libs/sequencer/blob/faac38bf265d0a60f2948559f7f487992b585a25/crates/blockifier/src/transaction/account_transaction.rs#L405
</blockquote></details>

I can do as in the previous check, and only check those that are not 0.

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1047 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O85xMgi2peaOB9gI-SR:-O86jZs_CIY638N22mD6:b1402sd) ([raw file](https://github.com/starkware-libs/sequencer/blob/76547e3bc7eab4684bd1f90341d0833571f4cb36/crates/blockifier/src/transaction/transactions_test.rs#L1047)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I can do as in the previous check, and only check those that are not 0.
</blockquote></details>

But the question still remains whether to always check the prices, or if it should depend on the flag\computation_mode

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/811)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1047 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O85xMgi2peaOB9gI-SR:-O86k194-i38FRBu_Bvf:b7tzbrf) ([raw file](https://github.com/starkware-libs/sequencer/blob/76547e3bc7eab4684bd1f90341d0833571f4cb36/crates/blockifier/src/transaction/transactions_test.rs#L1047)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

But the question still remains whether to always check the prices, or if it should depend on the flag\computation_mode
</blockquote></details>

It's enough to check against the min amount. If it's 0, you should not check the price, regardless of the reason (flag/lack of use)

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1047 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O85xMgi2peaOB9gI-SR:-O86kclH6yocJqbsfWY3:blj0a3c) ([raw file](https://github.com/starkware-libs/sequencer/blob/76547e3bc7eab4684bd1f90341d0833571f4cb36/crates/blockifier/src/transaction/transactions_test.rs#L1047)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

It's enough to check against the min amount. If it's 0, you should not check the price, regardless of the reason (flag/lack of use)
</blockquote></details>

That part is clear. But what if it's not 0, should I check the price regardless of the flags as well?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/811)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1047 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O85xMgi2peaOB9gI-SR:-O86lx7bCqaIuTFPQ8a_:b-9795p5) ([raw file](https://github.com/starkware-libs/sequencer/blob/76547e3bc7eab4684bd1f90341d0833571f4cb36/crates/blockifier/src/transaction/transactions_test.rs#L1047)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

That part is clear. But what if it's not 0, should I check the price regardless of the flags as well?
</blockquote></details>

Yes, you have a minimal_gas_vector calc - this logic should be (and is) encapsulated in it.
No reason to check the flag again

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/811)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, @nimrod-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1015 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O85wL0u3Fmj0753AYW-:-O86bnLCDS5hc1R-9wet:b-rfkog) ([raw file](https://github.com/starkware-libs/sequencer/blob/76547e3bc7eab4684bd1f90341d0833571f4cb36/crates/blockifier/src/transaction/transactions_test.rs#L1015)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Is it clearer this way? I can also put the bottom loop inside (shorter and less vars), though I think it's a bit less clear.
</blockquote></details>

It's clearer as in the previous the code assumes (what is correct but unknown to the reader and also very implicit) that L1Gas is 0 when kzg is True in the minimal_gas_vector. I think you should move the loop inside, but use a continue for `if max_amount == 0: continue` not avoid putting a lot of code under two indentations
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1047 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O85xMgi2peaOB9gI-SR:-O86dRjhDscAuj-EPeDT:bh4wd6a) ([raw file](https://github.com/starkware-libs/sequencer/blob/76547e3bc7eab4684bd1f90341d0833571f4cb36/crates/blockifier/src/transaction/transactions_test.rs#L1047)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Yes, you have a minimal_gas_vector calc - this logic should be (and is) encapsulated in it.
No reason to check the flag again
</blockquote></details>

About the previous question - "There's also a question about whether `actual_gas_price` can be 0 for any resource...", the type of gas_prices are NoneZero so no.

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/811)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, @nimrod-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1015 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O85wL0u3Fmj0753AYW-:-O86vik89RqTFGgbF51h:b-cv727w) ([raw file](https://github.com/starkware-libs/sequencer/blob/76547e3bc7eab4684bd1f90341d0833571f4cb36/crates/blockifier/src/transaction/transactions_test.rs#L1015)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

It's clearer as in the previous the code assumes (what is correct but unknown to the reader and also very implicit) that L1Gas is 0 when kzg is True in the minimal_gas_vector. I think you should move the loop inside, but use a continue for `if max_amount == 0: continue` not avoid putting a lot of code under two indentations
</blockquote></details>

\* to avoid putting a lot of code under two indentations

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/811)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, @nimrod-starkware, and @Yoni-Starkware)

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/811)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, @nimrod-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1026 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O7hjgQv22wf_BBJrAbe:-O87TIVeCDaV029t-5ND:bpo2zm4) ([raw file](https://github.com/starkware-libs/sequencer/blob/4f72f083e8447104aad3b8936263a52314124674/crates/blockifier/src/transaction/transactions_test.rs#L1026)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

What I wrote above - it can either succeed (in which case the nonce is increased), or fail, so long as the error is not one of the errors that we expect not to happen (in which case the nonce does not increase).
</blockquote></details>

But catching the errors above is strange. We have an amount that is too low in the first place so it throws an error we ignore, and later on we deduct 1 from that amount and assert we get that same error. I also don't understand how the estimate function can raise the exceptions were catching - the prevalidation checks uses the same estimate function before they throw these errors, it's not a post validation error.

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1026 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O7hjgQv22wf_BBJrAbe:-O87k5CqCBHFp3SfVhzW:bxw5dnt) ([raw file](https://github.com/starkware-libs/sequencer/blob/4f72f083e8447104aad3b8936263a52314124674/crates/blockifier/src/transaction/transactions_test.rs#L1026)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

But catching the errors above is strange. We have an amount that is too low in the first place so it throws an error we ignore, and later on we deduct 1 from that amount and assert we get that same error. I also don't understand how the estimate function can raise the exceptions were catching - the prevalidation checks uses the same estimate function before they throw these errors, it's not a post validation error.
</blockquote></details>

It's not the same error, that's the point! In the "successful" execution it passes the pre_validation checks here, but possibly fails later on (which we ignore). Later, when deducting 1, we verify it fails the expected pre_validation checks here, otherwise we panic.

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/811)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1015 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O85wL0u3Fmj0753AYW-:-O87oCRpC1iiDcN0E5Z_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/76547e3bc7eab4684bd1f90341d0833571f4cb36/crates/blockifier/src/transaction/transactions_test.rs#L1015)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

\* to avoid putting a lot of code under two indentations
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1047 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O85xMgi2peaOB9gI-SR:-O87krem38W9X1o-r9PS:bx0ukc3) ([raw file](https://github.com/starkware-libs/sequencer/blob/76547e3bc7eab4684bd1f90341d0833571f4cb36/crates/blockifier/src/transaction/transactions_test.rs#L1047)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

About the previous question - "There's also a question about whether `actual_gas_price` can be 0 for any resource...", the type of gas_prices are NoneZero so no.
</blockquote></details>

Ahh, right, that part is relevant only for the amount, thanks!

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/811)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1026 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O7hjgQv22wf_BBJrAbe:-O8VZnU65Ui4l9-2RFBA:bi42rkc) ([raw file](https://github.com/starkware-libs/sequencer/blob/4f72f083e8447104aad3b8936263a52314124674/crates/blockifier/src/transaction/transactions_test.rs#L1026)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

It's not the same error, that's the point! In the "successful" execution it passes the pre_validation checks here, but possibly fails later on (which we ignore). Later, when deducting 1, we verify it fails the expected pre_validation checks here, otherwise we panic.
</blockquote></details>

I might be totally missing something here, but the errors you catch below (i.e., errors that the "valid_tx" might raise due to a "mistake") are both prevalidation errors, thrown when the resources the user signed on are insufficient according to the estimate function (look for the single nontest code that throws MaxGasAmountTooLow). So the valid tx does fail in the prevalidation stage, and we shouldn't catch this as this doesn't make sense.

**Review by TzahiTaub — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/811)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1026 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O7hjgQv22wf_BBJrAbe:-O8WIdrFCILG5_7oWdeK:b-ddtvyn) ([raw file](https://github.com/starkware-libs/sequencer/blob/4f72f083e8447104aad3b8936263a52314124674/crates/blockifier/src/transaction/transactions_test.rs#L1026)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I might be totally missing something here, but the errors you catch below (i.e., errors that the "valid_tx" might raise due to a "mistake") are both prevalidation errors, thrown when the resources the user signed on are insufficient according to the estimate function (look for the single nontest code that throws MaxGasAmountTooLow). So the valid tx does fail in the prevalidation stage, and we shouldn't catch this as this doesn't make sense.
</blockquote></details>

OK, seems I got confused :) 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1016 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/811#-O8WJ0ao876dzi3vuyrh:-O8WJ0ao876dzi3vuyri:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1179903216fd765b18c862cafa1cc39a486c3aa0/crates/blockifier/src/transaction/transactions_test.rs#L1016)):*
> ```XML
>                 ),
>             ) => panic!("Transaction failed with expected minimal price."),
>             _ => 0,
> ```





_Suggestion:_
```XML
    _ => 0,  // Ignore failures other than those above (e.g., post-validation errors).
```

**Review by TzahiTaub — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/811#-:-O8WNU-e-W3qEZx7wdlV:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dorimedini-starkware and @nimrod-starkware)

**Review by TzahiTaub — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/811)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @nimrod-starkware)

**Pull request merged**
