### PR TITLE
chore: add client getters

### PR DESCRIPTION
**Pull request by nadin-Starkware**
**Stack**:
- #2047
- #2041
- #2040
- #2035 ⬅
- #2034
- #2033
- #2032
- #2030
- #2029
- #2028

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2035)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/starknet_sequencer_node/src/clients.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2035#-OBgS-7N1zej36OhB06n:-OBgS-7N1zej36OhB06o:b-sqynwb) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5bcac1a5590141cd3e9b405de36bc52653bc2fa/crates/starknet_sequencer_node/src/clients.rs#L122)):*
> ```XML
>     pub fn get_gateway_client(&self) -> Option<&Client<GatewayRequest, GatewayResponse>> {
>         self.gateway_client.as_ref()
>     }
> ```

These names are too similar, and can be confusing.



_Code quote:_
```XML
    pub fn get_gateway_shared_client(&self) -> Option<SharedGatewayClient> {
        get_shared_client!(self, gateway_client)
    }

    pub fn get_gateway_client(&self) -> Option<&Client<GatewayRequest, GatewayResponse>> {
        self.gateway_client.as_ref()
    }
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2035)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_sequencer_node/src/clients.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2035#-OBgS-7N1zej36OhB06n:-OBt_b102owxVaJj7Joa:bpwpe06) ([raw file](https://github.com/starkware-libs/sequencer/blob/a5bcac1a5590141cd3e9b405de36bc52653bc2fa/crates/starknet_sequencer_node/src/clients.rs#L122)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

These names are too similar, and can be confusing.
</blockquote></details>

Agree, I updated the name and function implementation to return the local client, as required for the server.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2035)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Comment by nadin-Starkware** [comment]
✓ Commit merged in pull request [#2041](https://github.com/starkware-libs/sequencer/pull/2041)

**Pull request closed without merging**
