### PR TITLE
refactor(mempool): move rpc_invoke_tx to StarknetAPI

### PR DESCRIPTION
**Pull request by noam-starkware**
Move the `rpc_invoke_tx` function from mempool_test_utils to starknet_api/test_utils.

### CODE REVIEW

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1740#-:-OAlhb5q05G2LPUe5FUV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1740#-:-OAlhzKk2zMfFwC0pwAe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noam-starkware)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1740)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @noam-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1740#-OAlq_G19yqz2NXlzPKc:-OAlq_G19yqz2NXlzPKd:bavmrsc) (no related file):*
Is this still in use? If so, where? Is there duplication like the `[invoke/deploy/declare]_args` macros?
Those are things that should be elaborated in the commit message.

___

**Review by noam-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1740)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1740#-OAlq_G19yqz2NXlzPKc:-OAlsRZ81AIyrIt05dX0:bul0ybh) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this still in use? If so, where? Is there duplication like the `[invoke/deploy/declare]_args` macros?
Those are things that should be elaborated in the commit message.
</blockquote></details>

The function is in use in the mempool_test_utils, it's not a duplicate but we think it makes sense to place it in the StarknetAPI test_utils folder since it is not specific to the mempool.

___

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1740)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @noam-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1740#-OAlq_G19yqz2NXlzPKc:-OAlu1TU8xkCFQ-7UOct:b844ojr) (no related file):*
<details><summary><i>Previously, noam-starkware wrote…</i></summary><blockquote>

The function is in use in the mempool_test_utils, it's not a duplicate but we think it makes sense to place it in the StarknetAPI test_utils folder since it is not specific to the mempool.
</blockquote></details>

How come Gateway doesn't use it?
This is becoming a design review which should not happen in a PR.
Please close this PR, consult with AlonH's team as to how these utils can be reused and reopen only if this change can be thoroughly yet succinctly explained.

___

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1740)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @noam-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1740#-OAluXGX1UJV-TD8kRv3:-OAluXGX1UJV-TD8kRv4:boq991) (no related file):*
Note the cleanup of the SN API test utils in `starknet_mempool` crate is a big non-trivial task, which should include consultations with other teams (such as, AlonH's and teams from Yoni's group) to best understand how this code can be correctly shared. Cleaning it up by moving code around according to _current use_ defeats the purpose: current use isn't good enough, it's leftovers from multirepo. 

___

**Pull request closed without merging**
