### PR TITLE
refactor(committer): refactor original skeleton tree config

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/754)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
* **#754** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/754?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/754)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/starknet_committer/src/forest/original_skeleton_forest.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/754#-O6LTaDV-w4u5SHgiB2h:-O6LTaDW2sDGlfJtxxO8:b-bh939r) ([raw file](https://github.com/starkware-libs/sequencer/blob/da9b945995c4a722f2d393f59c44395f2caafa20/crates/starknet_committer/src/forest/original_skeleton_forest.rs#L80)):*
> ```XML
>             contracts_trie_sorted_indices,
>             &OriginalSkeletonContractsTrieConfig::new(),
>             &HashMap::new(),
> ```

I created an empty HashMap because until now OriginalSkeletonContractsTrieConfig::new() puts an empty hash map inside the config.

**Review by AvivYossef-starkware — COMMENTED** [review]
https://github.com/starkware-industries/starkware/pull/35903
python side 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/754#-:-O6L_7q19Rs03P0auUPP:b-ojxzn5)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @dorimedini-starkware, and @Yoni-Starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/754)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @AvivYossef-starkware, and @Yoni-Starkware)

___
*[`crates/starknet_patricia/src/patricia_merkle_tree/original_skeleton_tree/config.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/754#-O6pFsKk1nSIAoQ9cKuv:-O6pFsKk1nSIAoQ9cKuw:b1vwikn) ([raw file](https://github.com/starkware-libs/sequencer/blob/da9b945995c4a722f2d393f59c44395f2caafa20/crates/starknet_patricia/src/patricia_merkle_tree/original_skeleton_tree/config.rs#L53)):*
> ```XML
>                     .ok_or(OriginalSkeletonTreeError::ReadModificationsError(*index))?;
>                 Ok(new_leaf == previous_leaf)
>             }
> ```

this function can be a standalone function; no need for macro, just `fn compare<L: Leaf>(...) -> Result<bool>`.
then you can remove the `leaf_type` param from the macro as well



_Code quote:_
```XML
            fn compare_leaf(
                &self,
                leaf_modifications: &$crate::patricia_merkle_tree::node_data::leaf::LeafModifications<$leaf_type>,
                index: &NodeIndex,
                previous_leaf: &$leaf_type,
            ) -> OriginalSkeletonTreeResult<bool> {
                let new_leaf =
                    leaf_modifications
                    .get(index)
                    .ok_or(OriginalSkeletonTreeError::ReadModificationsError(*index))?;
                Ok(new_leaf == previous_leaf)
            }
```
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/754#-O6pFAJzER1M2Cej1n4O:-O6pFAJzER1M2Cej1n4P:bdthu7p) ([raw file](https://github.com/starkware-libs/sequencer/blob/da9b945995c4a722f2d393f59c44395f2caafa20/crates/starknet_patricia/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L203)):*
> ```XML
>                                 &subtree.root_index,
>                                 &previous_leaf,
>                             )?
> ```

this no longer needs to be a method of the config, and this comparison function really shouldn't be a method of the config... please move the function, or, if it's only used once, just inline it here



_Code quote:_
```XML
                            && config.compare_leaf(
                                leaf_modifications,
                                &subtree.root_index,
                                &previous_leaf,
                            )?
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/754)* status: 10 of 15 files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/starknet_patricia/src/patricia_merkle_tree/original_skeleton_tree/config.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/754#-O6pFsKk1nSIAoQ9cKuv:-O6uLFCi9OOeqlCq1tz_:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/da9b945995c4a722f2d393f59c44395f2caafa20/crates/starknet_patricia/src/patricia_merkle_tree/original_skeleton_tree/config.rs#L53)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this function can be a standalone function; no need for macro, just `fn compare<L: Leaf>(...) -> Result<bool>`.
then you can remove the `leaf_type` param from the macro as well
</blockquote></details>

Done
___
*[`crates/starknet_patricia/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/754#-O6pFAJzER1M2Cej1n4O:-O6uP3KcCUMUVqoaQE5K:b-896fjb) ([raw file](https://github.com/starkware-libs/sequencer/blob/da9b945995c4a722f2d393f59c44395f2caafa20/crates/starknet_patricia/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L203)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this no longer needs to be a method of the config, and this comparison function really shouldn't be a method of the config... please move the function, or, if it's only used once, just inline it here
</blockquote></details>

Done

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/754)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @AvivYossef-starkware, and @Yoni-Starkware)

___
*[`crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/754#-O6uu1HQArFtWdO5luuq:-O6uu1HQArFtWdO5luur:bx9ufea) ([raw file](https://github.com/starkware-libs/sequencer/blob/f17bd3cc78e6f17db94f0e5957254fe5b0687eb5/crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs#L46)):*
> ```XML
>         index: &NodeIndex,
>         previous_leaf: &L,
>     ) -> OriginalSkeletonTreeResult<bool> {
> ```

you are already in the context of the trait; I don't think you need `L`.



_Suggestion:_
```XML
    fn compare(
        leaf_modifications: &LeafModifications<Self>,
        index: &NodeIndex,
        previous_leaf: &Self,
    ) -> OriginalSkeletonTreeResult<bool> {
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/754)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @dorimedini-starkware, and @Yoni-Starkware)

___
*[`crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/754#-O6uu1HQArFtWdO5luuq:-O6v3b5X1iK4KlSnHzAh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f17bd3cc78e6f17db94f0e5957254fe5b0687eb5/crates/starknet_patricia/src/patricia_merkle_tree/node_data/leaf.rs#L46)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you are already in the context of the trait; I don't think you need `L`.
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/754#-:-O6vJlLH8INcShUZbAoq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @Yoni-Starkware)

**Pull request merged**
