### PR TITLE
test(starknet_integration_tests): parameterize number of nodes

### PR DESCRIPTION
**Pull request by alonh5**

### CODE REVIEW

**Comment by alonh5** [comment]
* **#2870** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2870?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2870?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2870)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEidE_iE0jYwEuxyv9e:-OEidE_iE0jYwEuxyv9f:b8xmen6) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L85)):*
> ```XML
>     let mut join_set = JoinSet::new();
>     for handle in node_run_handles {
>         join_set.spawn(handle);
> ```

I think tokio's join_set spawns tasks as well. No need to spawn tasks twice. Use futures's join_all instead https://docs.rs/futures/latest/futures/future/fn.join_all.html

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
@nadin-Starkware fyi

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-:-OEift_HD9NAyEME43E_:b-4r51i)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2870)* status: all files reviewed, 6 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEigrsN01-y3MBKSkde:-OEigrsO-BP7YzwbFZ-S:b-rqqokn) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L90)):*
> ```XML
> 
>     // Wait for the nodes to start.
>     integration_test_setup.await_alive(5000, 50).await;
> ```

Does this wait until all nodes are alive?



_Code quote:_
```XML
    integration_test_setup.await_alive(5000, 50).await;
```
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEih7C76nt76LyG1HBG:-OEih7C76nt76LyG1HBH:bvypg2w) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L96)):*
> ```XML
>     let send_rpc_tx_fn = &mut |rpc_tx| {
>         integration_test_setup.sequencers[0].add_tx_http_client.assert_add_tx_success(rpc_tx)
>     };
> ```

Please add a function to `integration_test_setup` that returns the required `add_tx_http_client`.



_Code quote:_
```XML
    let send_rpc_tx_fn = &mut |rpc_tx| {
        integration_test_setup.sequencers[0].add_tx_http_client.assert_add_tx_success(rpc_tx)
    };
```
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEihGjm88QCX8UJL4cp:-OEihGjm88QCX8UJL4cq:bc6bnge) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L108)):*
> ```XML
> 
>     let (batcher_storage_reader, _) = papyrus_storage::open_storage(
>         integration_test_setup.sequencers[0].batcher_storage_config.clone(),
> ```

Similar comment to the above: Please add a comment that returns the required storage config for that.



_Code quote:_
```XML
integration_test_setup.sequencers[0].batcher_storage_config.clone(),
```
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEihTPpBFVL-DzDZ2Lq:-OEihTPpBFVL-DzDZ2Lr:bnyx8c2) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L114)):*
> ```XML
>     await_block(5000, EXPECTED_BLOCK_NUMBER, 30, &batcher_storage_reader)
>         .await
>         .expect("Block number should have been reached.");
> ```

Should we wait for something else to complete? E.g., the 2nd node gets synced (?)



_Code quote:_
```XML
    await_block(5000, EXPECTED_BLOCK_NUMBER, 30, &batcher_storage_reader)
        .await
        .expect("Block number should have been reached.");
```
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEigB4eA2P8cLAro2Me:-OEigB4eA2P8cLAro2Mf:bx632y1) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L117)):*
> ```XML
> 
>     info!("Shutting down nodes.");
>     node_run_tasks.iter().for_each(|task| task.abort());
> ```

Did you intentionally drop the 
```
        res_0.expect_err("Node 0 should have been stopped.").is_cancelled(),
        "Node 0 should have been stopped."

```
parts?
Good change imo, this doesn't do anything meaningful iiuc.

But I'd add a check that all node handles are non-errors before dropping them to ensure all nodes are still running correctly.



_Code quote:_
```XML
node_run_tasks.iter().for_each(|task| task.abort());
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2870)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware and @ShahakShama)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEidE_iE0jYwEuxyv9e:-OEijaAUCe9KiF3clAFj:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L85)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think tokio's join_set spawns tasks as well. No need to spawn tasks twice. Use futures's join_all instead https://docs.rs/futures/latest/futures/future/fn.join_all.html
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEigrsN01-y3MBKSkde:-OEijodS-7F6Sd5J-u0h:bgtu5iz) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L90)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Does this wait until all nodes are alive?
</blockquote></details>

Yes, I didn't change that part.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEih7C76nt76LyG1HBG:-OEik8qn1fA36KWDNskP:b-txi445) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L96)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add a function to `integration_test_setup` that returns the required `add_tx_http_client`.
</blockquote></details>

Why should this one line be a function?
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEihGjm88QCX8UJL4cp:-OEikFCo0fnZ95RoRi_K:bzcaofn) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L108)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Similar comment to the above: Please add a comment that returns the required storage config for that.
</blockquote></details>

Same question.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEihTPpBFVL-DzDZ2Lq:-OEik4E95bdva50o0q-R:bcpcbnn) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L114)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Should we wait for something else to complete? E.g., the 2nd node gets synced (?)
</blockquote></details>

We could open the storage of the second node also, I'm not sure it's needed. Also note I didn't change the test at all in those PR, only refactored it.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEigB4eA2P8cLAro2Me:-OEinjQp076CGU6r0O_o:b822gog) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L117)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Did you intentionally drop the 
```
        res_0.expect_err("Node 0 should have been stopped.").is_cancelled(),
        "Node 0 should have been stopped."

```
parts?
Good change imo, this doesn't do anything meaningful iiuc.

But I'd add a check that all node handles are non-errors before dropping them to ensure all nodes are still running correctly.
</blockquote></details>

I checked, and there isn't a simple way to check if a task didn't error, without awaiting it (and we can't await because it shouldn't end on it's own). I can maybe await it with a timeout and then if it times out I can consider it fine and if it returns an error not fine.
In any case t's very unlikely that we will reach the expected block and nonce and the after that a node will error.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-:-OEiqn4C1YiUOui7C_0t:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2870)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEigrsN01-y3MBKSkde:-OEmP1RRCc0Ai6pFGAd7:bnm3gjn) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L90)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Yes, I didn't change that part.
</blockquote></details>

Right.

Please note there's a confusing inconsistency here: the `IntegrationTestSetup` has functions that run on all of its nodes (e.g., `await_alive`), and functionality that requires invoking per node externally, e.g.,

```
    let node_run_tasks = integration_test_setup
        .sequencers
        .iter()
        .map(|sequencer| spawn_run_node(sequencer.node_config_path.clone()))
        .collect::<Vec<_>>();
```

I suggest to wrap the latter in designated functions as well, a la `async fn spawn_nodes() -> Vec<...>`
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEih7C76nt76LyG1HBG:-OEmQ-ruCdtzNj03Ahex:biuquml) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L96)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why should this one line be a function?
</blockquote></details>

Encapsulation: the test should not care about how the internals of `IntegrationTestSetup`, it just needs the endpoint.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEihGjm88QCX8UJL4cp:-OEmW2hZEVZ41XmbW-T6:b-yqsp1z) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L108)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Same question.
</blockquote></details>

Same answer :-)
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEihTPpBFVL-DzDZ2Lq:-OEmW6up6M5qMiBh8QCm:bc6trs5) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L114)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

We could open the storage of the second node also, I'm not sure it's needed. Also note I didn't change the test at all in those PR, only refactored it.
</blockquote></details>

Ack. Add a todo?
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEigB4eA2P8cLAro2Me:-OEmWNub0wesLnoBvygG:b-9it63j) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L117)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I checked, and there isn't a simple way to check if a task didn't error, without awaiting it (and we can't await because it shouldn't end on it's own). I can maybe await it with a timeout and then if it times out I can consider it fine and if it returns an error not fine.
In any case t's very unlikely that we will reach the expected block and nonce and the after that a node will error.
</blockquote></details>

I was aiming at checking the the node processes are still running, using something like
https://docs.rs/tokio/latest/tokio/task/struct.JoinHandle.html#method.is_finished (i.e., checking `!handle.is_finished()`)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2870)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware and @ShahakShama)

___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEigrsN01-y3MBKSkde:-OEmcihj3SU53VCKviNg:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L90)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Right.

Please note there's a confusing inconsistency here: the `IntegrationTestSetup` has functions that run on all of its nodes (e.g., `await_alive`), and functionality that requires invoking per node externally, e.g.,

```
    let node_run_tasks = integration_test_setup
        .sequencers
        .iter()
        .map(|sequencer| spawn_run_node(sequencer.node_config_path.clone()))
        .collect::<Vec<_>>();
```

I suggest to wrap the latter in designated functions as well, a la `async fn spawn_nodes() -> Vec<...>`
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEih7C76nt76LyG1HBG:-OEmfZOm3GixNgaU1TAM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L96)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Encapsulation: the test should not care about how the internals of `IntegrationTestSetup`, it just needs the endpoint.
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEihGjm88QCX8UJL4cp:-OEmf_Wv5T86-Q1m3eZK:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L108)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Same answer :-)
</blockquote></details>

Done.
___
*[`crates/starknet_integration_tests/src/end_to_end_integration.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-OEigB4eA2P8cLAro2Me:-OEmgGO028QS5qFGutSz:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/7b4a77906cb0f3b82ada06c7c523550386a1b53a/crates/starknet_integration_tests/src/end_to_end_integration.rs#L117)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I was aiming at checking the the node processes are still running, using something like
https://docs.rs/tokio/latest/tokio/task/struct.JoinHandle.html#method.is_finished (i.e., checking `!handle.is_finished()`)
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2870#-:-OEmnH940eW0wp9EjWyp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by alonh5** [comment]
### Merge activity

* **Dec 23, 4:20 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2870).

**Pull request merged**
