### PR TITLE
refactor(deployment): changed the way we pass configs to papyrus

### PR DESCRIPTION
**Pull request by idan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/673)

### CODE REVIEW

**Review by alon-dotan-starkware — COMMENTED** [review]
> Reviewed 3 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/673)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @idan-starkware)

___
*[`deployments/papyrus/helm/Chart.yaml` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/673#-O5lJMrU631kAvDQJLgf:-O5lJMrV9RzH2WMNOITW:b-kvy9j3) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa6ce5de66f4bc83a37f3071b226103f049450d9/deployments/papyrus/helm/Chart.yaml#L18)):*
> ```YAML
> # to the chart and its templates, including the app version.
> # Versions are expected to follow Semantic Versioning (https://semver.org/)
> version: 0.0.3
> ```

bump major, its a change in the API



_Code quote:_
```YAML
version: 0.0.3
```
___
*[`deployments/papyrus/helm/values.yaml` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/673#-O5lJXd1DRQi8g7betQo:-O5lJXd1DRQi8g7betQp:bb7kerq) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa6ce5de66f4bc83a37f3071b226103f049450d9/deployments/papyrus/helm/values.yaml#L26)):*
> ```YAML
>     tag: 0.4.0
> 
>   # Path to papyrus config file. The config file must be placed anywhere inside the chart directory.
> ```

add example



_Code quote:_
```YAML
# Path to papyrus config file. The config file must be placed anywhere inside the chart directory.
```
___
*[`deployments/papyrus/helm/values.yaml` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/673#-O5lJjGP06Cb2DEa0Q8f:-O5lJjGP06Cb2DEa0Q8g:bqfm7qt) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa6ce5de66f4bc83a37f3071b226103f049450d9/deployments/papyrus/helm/values.yaml#L113)):*
> ```YAML
>   # If service type is ClusterIP,
>   # Set static ip for the kubernetes service. Note that the ip address is not reserved and there might be a chance for ip collision.
>   # See https://kubernetes.io/docs/concepts/services-networking/cluster-ip-allocation/ to understand how to avoid such case.
> ```

why its needed?



_Code quote:_
```YAML
  # If service type is ClusterIP,
  # Set static ip for the kubernetes service. Note that the ip address is not reserved and there might be a chance for ip collision.
  # See https://kubernetes.io/docs/concepts/services-networking/cluster-ip-allocation/ to understand how to avoid such case.
```
___
*[`deployments/papyrus/helm/values.yaml` line 116 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/673#-O5lJoKv86J3BPs7z6ma:-O5lJoKv86J3BPs7z6mb:b-kuvco) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa6ce5de66f4bc83a37f3071b226103f049450d9/deployments/papyrus/helm/values.yaml#L116)):*
> ```YAML
>   clusterIP: 
>   # If service type is LoadBalancer,
>   # Set static ip for the loadbalancer. Note that a static IP needs to be reserved first in a cloud environment in order to use it.
> ```

add support to perform it with the configconnector



_Code quote:_
```YAML
  clusterIP:
  # If service type is LoadBalancer,
  # Set static ip for the loadbalancer. Note that a static IP needs to be reserved first in a cloud environment in order to use it.
```
___
*[`deployments/papyrus/helm/templates/configmap-env.yaml` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/673#-O5lK3Js12SthuI4Qw3t:-O5lK3Js12SthuI4Qw3u:b-srh1xb) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa6ce5de66f4bc83a37f3071b226103f049450d9/deployments/papyrus/helm/templates/configmap-env.yaml#L1)):*
> ```YAML
> apiVersion: v1
> ```

rename the file to env-cm.yaml?

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/673)* status: 2 of 10 files reviewed, 5 unresolved discussions (waiting on @idan-starkware)

___
*[`deployments/papyrus/helm/Chart.yaml` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/673#-O5lJMrU631kAvDQJLgf:-O5lp_Lg4wo0zTOmbg9W:b-8ld434) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa6ce5de66f4bc83a37f3071b226103f049450d9/deployments/papyrus/helm/Chart.yaml#L18)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

bump major, its a change in the API
</blockquote></details>

0.1.0

**Comment by idan-starkware** [comment]
*[`deployments/papyrus/helm/values.yaml` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/673#-O5lJjGP06Cb2DEa0Q8f:-O5lxAK09RpE6QyaegSF:b-fq8h7e) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa6ce5de66f4bc83a37f3071b226103f049450d9/deployments/papyrus/helm/values.yaml#L113)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

why its needed?
</blockquote></details>

If we want to have a papyrus cluster with internal communications only.

**Comment by idan-starkware** [comment]
*[`deployments/papyrus/helm/templates/configmap-env.yaml` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/673#-O5lK3Js12SthuI4Qw3t:-O5lyHtU7hccNmhDZZY2:b-19iway) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa6ce5de66f4bc83a37f3071b226103f049450d9/deployments/papyrus/helm/templates/configmap-env.yaml#L1)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

rename the file to env-cm.yaml?
</blockquote></details>

Lets keep it as is I like the fullname

**Comment by idan-starkware** [comment]
*[`deployments/papyrus/helm/values.yaml` line 116 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/673#-O5lJoKv86J3BPs7z6ma:-O5lyzMW4pmw4ru8ulPK:b-ygkaav) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa6ce5de66f4bc83a37f3071b226103f049450d9/deployments/papyrus/helm/values.yaml#L116)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

add support to perform it with the configconnector
</blockquote></details>

I'll do it in a different PR?

**Review by idan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/673)* status: 1 of 11 files reviewed, 5 unresolved discussions (waiting on @alon-dotan-starkware)

___
*[`deployments/papyrus/helm/Chart.yaml` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/673#-O5lJMrU631kAvDQJLgf:-O5lzSurB6rGZgX9O085:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa6ce5de66f4bc83a37f3071b226103f049450d9/deployments/papyrus/helm/Chart.yaml#L18)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

0.1.0
</blockquote></details>

Done.
___
*[`deployments/papyrus/helm/values.yaml` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/673#-O5lJXd1DRQi8g7betQo:-O5lzF8a5TuWbJaJ-f0b:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa6ce5de66f4bc83a37f3071b226103f049450d9/deployments/papyrus/helm/values.yaml#L26)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

add example
</blockquote></details>

Done.

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/673)* status: 1 of 11 files reviewed, 4 unresolved discussions (waiting on @idan-starkware)

___
*[`deployments/papyrus/helm/values.yaml` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/673#-O5lJXd1DRQi8g7betQo:-O5m-WKX0sWb3XwuHh7e:bvm1mdj) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa6ce5de66f4bc83a37f3071b226103f049450d9/deployments/papyrus/helm/values.yaml#L26)):*
<details><summary><i>Previously, idan-starkware (Idan Shamam) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

add example to the local path the file need to be
___
*[`deployments/papyrus/helm/values.yaml` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/673#-O5lJjGP06Cb2DEa0Q8f:-O5m-cFt2SyTQxeaEXoA:b-xal7bg) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa6ce5de66f4bc83a37f3071b226103f049450d9/deployments/papyrus/helm/values.yaml#L113)):*
<details><summary><i>Previously, idan-starkware (Idan Shamam) wrote…</i></summary><blockquote>

If we want to have a papyrus cluster with internal communications only.
</blockquote></details>

why you need to set the cluster IP ? you can use the service DNS name

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/673)* status: 1 of 11 files reviewed, 4 unresolved discussions (waiting on @idan-starkware)

___
*[`deployments/papyrus/helm/values.yaml` line 116 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/673#-O5lJoKv86J3BPs7z6ma:-O5m-hzYEKShbNwMxE5d:b32w0x) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa6ce5de66f4bc83a37f3071b226103f049450d9/deployments/papyrus/helm/values.yaml#L116)):*
<details><summary><i>Previously, idan-starkware (Idan Shamam) wrote…</i></summary><blockquote>

I'll do it in a different PR?
</blockquote></details>

OK

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/673)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @idan-starkware)

___
*[`deployments/papyrus/helm/templates/service-p2p.yaml` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/673#-O5m00W4CSWldvxhwfzz:-O5m00W53YA80xfbNW7V:b-hvbrl4) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa6ce5de66f4bc83a37f3071b226103f049450d9/deployments/papyrus/helm/templates/service-p2p.yaml#L18)):*
> ```YAML
>     protocol: {{ .Values.p2pService.protocol }}
>     targetPort: p2p
> {{- end }}
> ```

add new line

**Review by alon-dotan-starkware — COMMENTED** [review]
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/673)* status: 6 of 11 files reviewed, 3 unresolved discussions (waiting on @idan-starkware)

**Comment by idan-starkware** [comment]
*[`deployments/papyrus/helm/values.yaml` line 113 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/673#-O5lJjGP06Cb2DEa0Q8f:-O5m1-D77oXr12yyQzR0:bvdgb94) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa6ce5de66f4bc83a37f3071b226103f049450d9/deployments/papyrus/helm/values.yaml#L113)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

why you need to set the cluster IP ? you can use the service DNS name
</blockquote></details>

The dns name won't work for p2p. We need to have Papyrus support /dnsaddr protocol first.

**Comment by idan-starkware** [comment]
*[`deployments/papyrus/helm/values.yaml` line 26 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/673#-O5lJXd1DRQi8g7betQo:-O5m84-k3OW3VCcxmwln:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa6ce5de66f4bc83a37f3071b226103f049450d9/deployments/papyrus/helm/values.yaml#L26)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

add example to the local path the file need to be
</blockquote></details>

Done.

**Comment by idan-starkware** [comment]
*[`deployments/papyrus/helm/templates/service-p2p.yaml` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/673#-O5m00W4CSWldvxhwfzz:-O5m8-Q54QoPQuCTHJ6h:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/aa6ce5de66f4bc83a37f3071b226103f049450d9/deployments/papyrus/helm/templates/service-p2p.yaml#L18)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

add new line
</blockquote></details>

Done.

**Review by alon-dotan-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/673)* status: 5 of 12 files reviewed, 1 unresolved discussion (waiting on @idan-starkware)

**Comment by idan-starkware** [comment]
*[`deployments/papyrus/helm/config/example.json` line 8 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/673#-O5xe8uv7AMGik2s4PVo:-O5yMwkdD35BWmQVeNVe:b-mr78mb) ([raw file](https://github.com/starkware-libs/sequencer/blob/a2c3646a154812b462c2e6fcd9a366b99a93d7ac/deployments/papyrus/helm/config/example.json#L8)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

newline
</blockquote></details>

It already ends with a new line

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/673#-:-O5yOGh5B9KT5fCLBcT_:bnfp4nl)* status: 5 of 12 files reviewed, all discussions resolved (waiting on @idan-starkware)

**Review by RoeiE-starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/673#-:-O6FXC04Cp-sotpgS0DH:bnfp4nl)* status: 5 of 12 files reviewed, all discussions resolved (waiting on @alon-dotan-starkware and @idan-starkware)

**Review by RoeiE-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/673)* status: 5 of 12 files reviewed, all discussions resolved (waiting on @alon-dotan-starkware and @idan-starkware)

**Review by RoeiE-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/673)* status: 5 of 12 files reviewed, all discussions resolved (waiting on @alon-dotan-starkware and @idan-starkware)

**Review by RoeiE-starkware — COMMENTED** [review]
> Reviewed 3 of 5 files at r5, 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/673)* status: 9 of 12 files reviewed, all discussions resolved (waiting on @idan-starkware)

**Review by RoeiE-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/673)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @idan-starkware)

**Pull request merged**
