### PR TITLE
test(mempool): remove pool capacity test; tested indirectly

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1000)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
Just to be sure i understand, the first case in the removed test is covered by yr modification of the other test in this PR, and the two other cases in the removed tests are assumed to be covered by many other tests (which is a correct assumption)?

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1000#-:-O7cGkJd9Ubeh63JCeFq:b-q0ydfn)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by elintul — COMMENTED** [review]
Yup, we're comparing the pool (inc. its capacity in many tests). 
I also think this should be tested through eviction flow tests, not directly.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1000#-:-O7cHWKl9QQa36IV8BDI:b-arwgz9)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by elintul — COMMENTED** [review]
(inc. its capacity) in many tests. *
Parenthesis closed too late.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1000#-:-O7cHhl47OCHZ7dpYvnt:b-d9upx3)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1000#-:-O7cOGEC-2ul2YZyx_iJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
