### PR TITLE
feat(batcher): notify mempool on committed block

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1370)

### CODE REVIEW

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1370#-:-O9AZLaF7p5T13XMACMv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1370)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 158 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1370#-O9BaP0gELEkNsjPxs3w:-O9BaP0h-hPJQDArvC9Y:b-9ny9te) ([raw file](https://github.com/starkware-libs/sequencer/blob/d90d57c866d6a69f98bb4b544947858c4524492b/crates/batcher/src/batcher.rs#L158)):*
> ```XML
>         })?;
>         if let Err(mempool_err) =
>             self.mempool_client.commit_block(CommitBlockArgs { nonces, tx_hashes }).await
> ```

There is weird asymmetry here,  the proposal_manager is calling the mempool to get txs and then the batcher is calling it to commit them. 
I think it should be the same entity doing both calls, and only this entity should hold the mempool_client.



_Code quote:_
```XML
self.mempool_client.commit_block(CommitBlockArgs { nonces, tx_hashes }).await
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1370)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/batcher_test.rs` line 158 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1370#-O9Dn3bs8hGKvox0gTCK:-O9Dn3bs8hGKvox0gTCL:bru3zj) ([raw file](https://github.com/starkware-libs/sequencer/blob/d90d57c866d6a69f98bb4b544947858c4524492b/crates/batcher/src/batcher_test.rs#L158)):*
> ```XML
>     let expected_proposal_commitment = ProposalCommitment::default();
>     let tx_hashes: HashSet<_> =
>         (0..5).map(|i| TransactionHash(felt!(u128::try_from(i).unwrap()))).collect();
> ```

easier to read.



_Suggestion:_
```XML
    let tx_hashes =
        test_tx_hashes();
```
___
*[`crates/batcher/src/batcher_test.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1370#-O9DnDel0YnZmkztcycW:-O9DnDel0YnZmkztcycX:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/d90d57c866d6a69f98bb4b544947858c4524492b/crates/batcher/src/batcher_test.rs#L162)):*
> ```XML
>     let nonces: HashMap<_, _> = (0..3)
>         .map(|i| (ContractAddress(patricia_key!(u128::try_from(i).unwrap())), nonce!(i)))
>         .collect();
> ```

same



_Suggestion:_
```XML
    let nonces: test_nonces();
```

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1370)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 153 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1370#-O9E3FvE6UBrb3uq_ZrL:-O9E3FvE6UBrb3uq_ZrM:b-1bgle8) ([raw file](https://github.com/starkware-libs/sequencer/blob/d90d57c866d6a69f98bb4b544947858c4524492b/crates/batcher/src/batcher.rs#L153)):*
> ```XML
>             BatcherError::InternalError
>         })?;
>         self.storage_writer.commit_proposal(height, state_diff).map_err(|err| {
> ```

Is there info tracing of the created block anywhere? If not, please add it here

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1370)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @alonh5, @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/batcher.rs` line 158 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1370#-O9BaP0gELEkNsjPxs3w:-O9E0da4C-oVcSNQ7ol2:bmcpdob) ([raw file](https://github.com/starkware-libs/sequencer/blob/d90d57c866d6a69f98bb4b544947858c4524492b/crates/batcher/src/batcher.rs#L158)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

There is weird asymmetry here,  the proposal_manager is calling the mempool to get txs and then the batcher is calling it to commit them. 
I think it should be the same entity doing both calls, and only this entity should hold the mempool_client.
</blockquote></details>

You're right. Added a todo.
___
*[`crates/batcher/src/batcher_test.rs` line 158 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1370#-O9Dn3bs8hGKvox0gTCK:-O9E2GlRCop403SGVNpE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d90d57c866d6a69f98bb4b544947858c4524492b/crates/batcher/src/batcher_test.rs#L158)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

easier to read.
</blockquote></details>

Done.
___
*[`crates/batcher/src/batcher_test.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1370#-O9DnDel0YnZmkztcycW:-O9E2H6Y7Gl7UJ7PWgjS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d90d57c866d6a69f98bb4b544947858c4524492b/crates/batcher/src/batcher_test.rs#L162)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 4 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1370)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @alonh5, @ArniStarkware, and @dafnamatsry)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1370)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/batcher.rs` line 153 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1370#-O9E3FvE6UBrb3uq_ZrL:-O9Esop486y86o41ptb4:bli710w) ([raw file](https://github.com/starkware-libs/sequencer/blob/d90d57c866d6a69f98bb4b544947858c4524492b/crates/batcher/src/batcher.rs#L153)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Should be in the block builder
</blockquote></details>

I mean that a block was actually committed to the batcher's storage. Can You add it here after the write?

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1370)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1370)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @alonh5, @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/batcher.rs` line 153 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1370#-O9E3FvE6UBrb3uq_ZrL:-O9F3aZ23PdaOnknieiK:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d90d57c866d6a69f98bb4b544947858c4524492b/crates/batcher/src/batcher.rs#L153)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I mean that a block was actually committed to the batcher's storage. Can You add it here after the write?
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
> Reviewed 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1370)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/batcher/src/batcher.rs` line 153 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1370#-O9E3FvE6UBrb3uq_ZrL:-O9FDg8Y71y-JyP_lsRG:bo3nnq8) ([raw file](https://github.com/starkware-libs/sequencer/blob/d90d57c866d6a69f98bb4b544947858c4524492b/crates/batcher/src/batcher.rs#L153)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Great thanks!

**Pull request merged**
