### PR TITLE
refactor(mempool): transaction pool stores full transaction, API did not change

### PR DESCRIPTION
**Pull request by MohammadNassar1**
…did not change

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/341)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/341)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O3zyTM69Y8-Q3R-vOqR:-O3zyTM69Y8-Q3R-vOqS:bwcgx7d) (no related file):*
In this PR, the transaction pool stores `InternalTransaction` instead of `ThinTransaction`. 
The API did not change

Note that I have added a temporal functions.

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/341)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O40hIW006e3KOuBpegz:-O40hIW006e3KOuBpeh-:b-kpf8lx) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce7ec4c4e8f622ca9c5dbd4fc975c3b5711aa4d1/crates/mempool/src/mempool.rs#L233)):*
> ```XML
>         }
>     }
>     pub fn new_from_transaction(tx: &Transaction) -> Self {
> ```

Use `From`?



_Suggestion:_
```XML
    }
    
    pub fn new_from_transaction(tx: &Transaction) -> Self {
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O3fc6X05M5nJ56fnssT:-O3fc6X05M5nJ56fnssU:b-fypyyt) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce7ec4c4e8f622ca9c5dbd4fc975c3b5711aa4d1/crates/mempool_types/src/mempool_types.rs#L46)):*
> ```XML
> pub type MempoolResult<T> = Result<T, MempoolError>;
> 
> // TODO(Mohammad): Consider deleting these methods once `ThinTransaction` is deleted.
> ```

It will be obliged, no need to add a TODO.



_Code quote:_
```XML
// TODO(Mohammad): Consider deleting these methods once `ThinTransaction` is deleted.
```

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/341)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O3zyTM69Y8-Q3R-vOqR:-O40nKTY6rIRQ2XpXubQ:b52xce6) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

In this PR, the transaction pool stores `InternalTransaction` instead of `ThinTransaction`. 
The API did not change

Note that I have added a temporal functions.
</blockquote></details>

I find `InternalTransaction` potentially confusing, as the current struct is named `Transaction`. Consider noting in the commit message that `Transaction` was previously named `InternalTransaction,` perhaps like this: `Transaction (prev InternalTransaction).`

___

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/341)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O40p9sfD8gb4LlqEsfE:-O40p9sfD8gb4LlqEsfF:b-k2dg4x) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce7ec4c4e8f622ca9c5dbd4fc975c3b5711aa4d1/crates/mempool/src/mempool.rs#L238)):*
> ```XML
>             nonce: tx.nonce(),
>             tx_hash: tx.tx_hash(),
>             tip: tx.tip().unwrap(),
> ```

is it possible to avoid it?



_Code quote:_
```XML
.unwrap(),
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/341)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O40hIW006e3KOuBpegz:-O44NeAm36j6i_8nUF9m:b-pyl91a) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce7ec4c4e8f622ca9c5dbd4fc975c3b5711aa4d1/crates/mempool/src/mempool.rs#L233)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Use `From`?
</blockquote></details>

The code takes `&Transaction`, so to avoid writing ugly code, I do not prefer to use "from".



_Code snippet:_
```XML
(&tx).into()
```
___
*[`crates/mempool/src/mempool.rs` line 238 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O40p9sfD8gb4LlqEsfE:-O44OzuMEVJxZL-2GtYo:bux65yy) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce7ec4c4e8f622ca9c5dbd4fc975c3b5711aa4d1/crates/mempool/src/mempool.rs#L238)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

is it possible to avoid it?
</blockquote></details>

Updated to expect.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/341)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O3zyTM69Y8-Q3R-vOqR:-O4A43TxB-ZwfASp6wEU:b-bw8e14) (no related file):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I find `InternalTransaction` potentially confusing, as the current struct is named `Transaction`. Consider noting in the commit message that `Transaction` was previously named `InternalTransaction,` perhaps like this: `Transaction (prev InternalTransaction).`
</blockquote></details>

Updated.

___

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/341)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O40hIW006e3KOuBpegz:-O4KN1t88epGL8gO-bZh:b-3zbr45) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce7ec4c4e8f622ca9c5dbd4fc975c3b5711aa4d1/crates/mempool/src/mempool.rs#L233)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

The code takes `&Transaction`, so to avoid writing ugly code, I do not prefer to use "from".
</blockquote></details>

can you elaborate? what ugly code?
___
*[`crates/mempool_types/src/mempool_types.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O4KNTQDCa3lrpAjxH7U:-O4KNTQDCa3lrpAjxH7V:b-pp4uub) ([raw file](https://github.com/starkware-libs/sequencer/blob/5028b9dd82040b76c8f3bae841a0d7ec03070da5/crates/mempool_types/src/mempool_types.rs#L51)):*
> ```XML
>             sender_address: tx.contract_address(),
>             tx_hash: tx.tx_hash(),
>             tip: tx.tip().unwrap_or_default(),
> ```

can you avoid unrwrap?



_Code quote:_
```XML
unwrap_or_default()
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/341)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O40hIW006e3KOuBpegz:-O4KT8Vk4wOByIKZo7n0:b-g8h5ue) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce7ec4c4e8f622ca9c5dbd4fc975c3b5711aa4d1/crates/mempool/src/mempool.rs#L233)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

can you elaborate? what ugly code?
</blockquote></details>

To use from, I need to add parenthesis then reference `&`:
Like this:
`a_func_that_expects_tx_reference((&tx).into())`
___
*[`crates/mempool_types/src/mempool_types.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O4KNTQDCa3lrpAjxH7U:-O4KTRU08lFt4L6wzAt8:bnencc5) ([raw file](https://github.com/starkware-libs/sequencer/blob/5028b9dd82040b76c8f3bae841a0d7ec03070da5/crates/mempool_types/src/mempool_types.rs#L51)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

can you avoid unrwrap?
</blockquote></details>

What do you suggest? :)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/341)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O40hIW006e3KOuBpegz:-O4ZIXugAMHqVPUQjow4:b91o43s) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce7ec4c4e8f622ca9c5dbd4fc975c3b5711aa4d1/crates/mempool/src/mempool.rs#L233)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

To use from, I need to add parenthesis then reference `&`:
Like this:
`a_func_that_expects_tx_reference((&tx).into())`
</blockquote></details>

But here you can use the `From`. Also, please add a blank line between methods.
___
*[`crates/mempool/src/mempool.rs` line 236 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O4ZItBC1lLkmm5dUJo-:-O4ZItBC1lLkmm5dUJo0:b-s90bzo) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d2b4c77d6554dd6799a5a239f54ed74ff8b08b8/crates/mempool/src/mempool.rs#L236)):*
> ```XML
>         }
>     }
>     pub fn new_from_transaction(tx: &Transaction) -> Self {
> ```

In the end, this should be renamed to `new` (and the previous one deleted). 
Please start with a preliminary PR of rename the old `new -> new_from_thin_tx`, then add this `new` and use it, instead of `(&tx).into()`, which is what we wanted to avoid in the first place.



_Code quote:_
```XML
new_from_transaction
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O4KNTQDCa3lrpAjxH7U:-O4ZI93W4SGHA6MKnJGl:b-ky0syo) ([raw file](https://github.com/starkware-libs/sequencer/blob/5028b9dd82040b76c8f3bae841a0d7ec03070da5/crates/mempool_types/src/mempool_types.rs#L51)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

What do you suggest? :)
</blockquote></details>

It's `_or_default`, so it doesn't `panic`.
___
*[`crates/mempool_types/src/mempool_types.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O4ZIHsU7s4ue5kzFnTz:-O4ZIHsU7s4ue5kzFnU-:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/5028b9dd82040b76c8f3bae841a0d7ec03070da5/crates/mempool_types/src/mempool_types.rs#L69)):*
> ```XML
>                     calldata: Calldata::default(),
>                     nonce_data_availability_mode: DataAvailabilityMode::L1,
>                     fee_data_availability_mode: DataAvailabilityMode::L2,
> ```





_Suggestion:_
```XML
L1
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/341)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O4ZJsJc3WtHpysDq00I:-O4ZJsJc3WtHpysDq00J:bj6opre) (no related file):*
Please update commit message.

___

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/341)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 236 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O4ZItBC1lLkmm5dUJo-:-O4ZNLM82u_QDX05gsnJ:b-86o7if) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d2b4c77d6554dd6799a5a239f54ed74ff8b08b8/crates/mempool/src/mempool.rs#L236)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

In the end, this should be renamed to `new` (and the previous one deleted). 
Please start with a preliminary PR of rename the old `new -> new_from_thin_tx`, then add this `new` and use it, instead of `(&tx).into()`, which is what we wanted to avoid in the first place.
</blockquote></details>

Added a preliminary [PR](https://reviewable.io/reviews/starkware-libs/sequencer/486).

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/341)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, @giladchase, and @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/341)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O4ZJsJc3WtHpysDq00I:-O4ZRZXa055AywsTyY6T:b1jeyey) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please update commit message.
</blockquote></details>

what do you suggest?

___
___
*[`crates/mempool/src/mempool.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O40hIW006e3KOuBpegz:-O4ZSgzm8NjDfrpMaBtw:b-g58rsc) ([raw file](https://github.com/starkware-libs/sequencer/blob/ce7ec4c4e8f622ca9c5dbd4fc975c3b5711aa4d1/crates/mempool/src/mempool.rs#L233)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

But here you can use the `From`. Also, please add a blank line between methods.
</blockquote></details>

Not sure I get it; which `from` can be added? that replaces the new method?
___
*[`crates/mempool_types/src/mempool_types.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O4KNTQDCa3lrpAjxH7U:-O4ZRUYi5rGoulde-oFu:bx5ausi) ([raw file](https://github.com/starkware-libs/sequencer/blob/5028b9dd82040b76c8f3bae841a0d7ec03070da5/crates/mempool_types/src/mempool_types.rs#L51)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It's `_or_default`, so it doesn't `panic`.
</blockquote></details>

Added `expect`.
___
*[`crates/mempool_types/src/mempool_types.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O4ZIHsU7s4ue5kzFnTz:-O4ZR8rZ9YK236JgFomv:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5028b9dd82040b76c8f3bae841a0d7ec03070da5/crates/mempool_types/src/mempool_types.rs#L69)):*
> ```XML
>                     calldata: Calldata::default(),
>                     nonce_data_availability_mode: DataAvailabilityMode::L1,
>                     fee_data_availability_mode: DataAvailabilityMode::L2,
> ```

Done.

**Review by ayeletstarkware — COMMENTED** [review]
> Reviewed 3 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/341)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/341#-:-O4Zb0q-7WUk-3hZFkwu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/341)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/341#-O4ZJsJc3WtHpysDq00I:-O4Zb5mo5wM7IRBJklPk:b-kmdhuy) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

what do you suggest?
</blockquote></details>

"full transaction".

___

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/341)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
