### PR TITLE
test: move TransactionTestData to test_util

### PR DESCRIPTION
**Pull request by guy-starkware**
I need to use `TransactionTestData` in a new test I'm writing. I think that since `read_json_file` is made public in `test_util` then we may as well move the struct used to deserialize that JSON into the same file.

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2112)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @guy-starkware)

___
*[`crates/starknet_api/src/test_utils.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2112#-OBuJ3v042ORnqsKZcuq:-OBuJ3v042ORnqsKZcur:b73ctet) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d72ff832b1948d32d00627d52e715c1e83423e2/crates/starknet_api/src/test_utils.rs#L45)):*
> ```XML
>     /// The block number.
>     pub block_number: BlockNumber,
> }
> ```

There is no need to document self-explanatory fields. 



_Suggestion:_
```XML
pub struct TransactionTestData {
    /// The actual transaction.
    pub transaction: Transaction,
    /// The expected transaction hash.
    pub transaction_hash: TransactionHash,
    /// An optional transaction hash to query.
    pub only_query_transaction_hash: Option<TransactionHash>,
    pub chain_id: ChainId,
    pub block_number: BlockNumber,
}
```

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2112)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @guy-starkware)

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2112)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_api/src/test_utils.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2112#-OBuJ3v042ORnqsKZcuq:-OBuKeJ8-H742DuFd0Eo:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d72ff832b1948d32d00627d52e715c1e83423e2/crates/starknet_api/src/test_utils.rs#L45)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

There is no need to document self-explanatory fields.
</blockquote></details>

Done.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2112#-:-OBuL99U7EFNe4YoEPfH:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @guy-starkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2112)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2112)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
