### PR TITLE
feat(mempool): abstract mempool state

### PR DESCRIPTION
**Pull request by elintul**

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2027)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @giladchase)

___
*[`crates/starknet_mempool/src/mempool.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2027#-OBa22ZSCJgja42ZFcsk:-OBa22ZSCJgja42ZFcsl:b-vyu95f) ([raw file](https://github.com/starkware-libs/sequencer/blob/7da722f9dbe0af4bec0ee86b8fe991cd896fb372/crates/starknet_mempool/src/mempool.rs#L107)):*
> ```XML
>     }
> 
>     fn validate_commitment(&self, address: ContractAddress, next_nonce: Nonce) {
> ```

Copied as-is from `validate_committed_nonce`.



_Code quote:_
```XML
validate_commitment
```
___
*[`crates/starknet_mempool/src/mempool.rs` line 283 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2027#-OBa2BHK45wK7vmsaWn4:-OBa2BHK45wK7vmsaWn5:b7sygco) ([raw file](https://github.com/starkware-libs/sequencer/blob/7da722f9dbe0af4bec0ee86b8fe991cd896fb372/crates/starknet_mempool/src/mempool.rs#L283)):*
> ```XML
>     }
> 
>     fn _validate_incoming_tx_nonce(
> ```

Became unused, please ignore changes to it; I'll delete it next PR (wanted a minimal diff.).



_Code quote:_
```XML
_validate_incoming_tx_nonce
```
___
*[`crates/starknet_mempool/src/mempool.rs` line 303 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2027#-OBa2IuZ8__YjoIf_FHk:-OBa2IuZ8__YjoIf_FHl:b7sygco) ([raw file](https://github.com/starkware-libs/sequencer/blob/7da722f9dbe0af4bec0ee86b8fe991cd896fb372/crates/starknet_mempool/src/mempool.rs#L303)):*
> ```XML
>     }
> 
>     fn _validate_committed_nonce(&self, address: ContractAddress, next_nonce: Nonce) {
> ```

Became unused, please ignore changes to it; I'll delete it next PR (wanted a minimal diff.).



_Code quote:_
```XML
_validate_committed_nonce
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2027)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @giladchase)

___
*[`crates/starknet_mempool/src/mempool.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2027#-OBa3KW_4_dClzGAotpU:-OBa3KW_4_dClzGAotpV:bvqk6t3) ([raw file](https://github.com/starkware-libs/sequencer/blob/7da722f9dbe0af4bec0ee86b8fe991cd896fb372/crates/starknet_mempool/src/mempool.rs#L98)):*
> ```XML
>     }
> 
>     fn validate_incoming_tx(&self, tx_reference: TransactionReference) -> MempoolResult<()> {
> ```

Compare to `Mempool::validate_incoming_tx_nonce`.
Note that now `MempoolState::get` takes into account the given address in all layers known to mempool, so no need to check the queue separately. LMK if you think otherwise.



_Code quote:_
```XML
validate_incoming_tx
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2027)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @giladchase)

___
*[`crates/starknet_mempool/src/mempool_test.rs` line 169 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2027#-OBe7FA96ulqPs1_0AJk:-OBe7FAA9BarM8wz0lUP:ba4w9b0) ([raw file](https://github.com/starkware-libs/sequencer/blob/81003c0de45297eeb34b8ecc44583eae6ab35d36/crates/starknet_mempool/src/mempool_test.rs#L169)):*
> ```XML
> #[fixture]
> fn mempool() -> Mempool {
>     MempoolContentBuilder::new().build_into_mempool()
> ```

Empty mempool should be instantiated through builder, to match test behavior (e.g., by default no fee escalation).



_Code quote:_
```XML
MempoolContentBuilder::new().build_into_mempool()
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2027)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @giladchase)

___
*[`crates/starknet_mempool/src/mempool.rs` line 298 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2027#-OBeXYXn9umw59hyLqsl:-OBeXYXn9umw59hyLqsm:b-gyw42w) ([raw file](https://github.com/starkware-libs/sequencer/blob/53d218eca565d8626669d4cf4b094aa4615c73f6/crates/starknet_mempool/src/mempool.rs#L298)):*
> ```XML
>         if self.tx_queue.get_nonce(address).is_some_and(|queued_nonce| tx_nonce <= queued_nonce) {
>             return Err(MempoolError::DuplicateNonce { address, nonce: tx_nonce });
>         }
> ```

We previously checked against the Q, since in the beginning it contained exclusive nonce information we didn't have elsewhere. Now, `MempoolState` covers all known account nonces.



_Code quote:_
```XML
        // Check nonce against the queue.
        // TODO(Elin): change to < for fee escalation (and add test).
        if self.tx_queue.get_nonce(address).is_some_and(|queued_nonce| tx_nonce <= queued_nonce) {
            return Err(MempoolError::DuplicateNonce { address, nonce: tx_nonce });
        }
```

**Review by giladchase — APPROVED** [review]
:lgtm_strong: :fire:

> Reviewed 1 of 3 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2027#-:-OBekuSx4aG_w-qG1kF9:b-gf8scj)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/starknet_mempool/src/mempool.rs` line 298 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2027#-OBeXYXn9umw59hyLqsl:-OBekZCH-vDsStRRn2rH:bjl4rhu) ([raw file](https://github.com/starkware-libs/sequencer/blob/53d218eca565d8626669d4cf4b094aa4615c73f6/crates/starknet_mempool/src/mempool.rs#L298)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Repeats a comment from above, sorry; preferred explicitness.
</blockquote></details>

No need to be sorry, the part about the queue didn't really pass through when I read it the first time, so this reiteration was helpful.

**Review by giladchase — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2027)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by giladchase — APPROVED** [review]
> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2027)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
