### PR TITLE
chore(blockifier): add cairo-native feature

### PR DESCRIPTION
**Pull request by noaov1**

### CODE REVIEW

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1558)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1558#-OADYFOy8pV8pCAQO2xM):*
This is weird... Did you amend an existing commit instead of creating a new one?



_Code quote:_
```
7c9710f: feat(ci): small QoL improvements to publish_crates.py (#1542)
```

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 8 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1558)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 532 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1558#-OADYyRq5HRAPNYdR5aw:-OADYyRq5HRAPNYdR5ax:b-5by9em) ([raw file](https://github.com/starkware-libs/sequencer/blob/7c9710f0abc60c50d16b89352c3e315bef567881/crates/blockifier/src/execution/syscalls/mod.rs#L532)):*
> ```XML
>         }
>         #[cfg(feature = "cairo_native")]
>         ContractClass::V1Native(_) => {
> ```

This method introduces code duplication in many places.
Is there a way to avoid it?
Non-blocking



_Code quote:_
```XML
        #[cfg(feature = "cairo_native")]
        ContractClass::V1Native(_) => {
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1558)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @dorimedini-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1558#-OADYFOy8pV8pCAQO2xM):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

This is weird... Did you amend an existing commit instead of creating a new one?
</blockquote></details>

Indeed weird. Nice catch!

**Comment by avi-starkware** [comment]
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there are two options as I see it
1. what you did here
2. duplicate all code that has a variation into separate modules - one for native and one without. for example:

```
// Module gated behind #[cfg(feature = "cairo_native")]
pub enum ContractClass {
    V0(ContractClassV0),
    V1(ContractClassV1),
    V1Native(NativeContractClassV1),
}
...
// Module gated behind #[cfg(not(feature = "cairo_native"))]
pub enum ContractClass {
    V0(ContractClassV0),
    V1(ContractClassV1),
}
```

which one is better?
</blockquote></details>

Solution 2 adds much more code duplication. This means any change to this module will have to be made twice.

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1558)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 972 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1558#-OADay3C-9O8AoJX-p0z:-OAE3eLm1WfgOH_u8eS1:b-7gss6j) ([raw file](https://github.com/starkware-libs/sequencer/blob/85091d4fc69ba5365b518c24c75eb42291c3a1b8/crates/blockifier/src/transaction/account_transaction.rs#L972)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does this work?
</blockquote></details>

It should work. The same pattern is used in `test_utils.rs` in this PR (and in many other places...)

**Review by avi-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1558)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1558)* status: 12 of 15 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1558#-OADbNdp7BLYPHky6ioT:-OAEiTb47l0hPL7HWNJ1:b-u6i0em) (no related file):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Solution 2 adds much more code duplication. This means any change to this module will have to be made twice.
</blockquote></details>

I tend to agree with Avi.

___
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 532 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1558#-OADYyRq5HRAPNYdR5aw:-OAEidx83PARlWai0FCC:b-500k9) ([raw file](https://github.com/starkware-libs/sequencer/blob/7c9710f0abc60c50d16b89352c3e315bef567881/crates/blockifier/src/execution/syscalls/mod.rs#L532)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

This method introduces code duplication in many places.
Is there a way to avoid it?
Non-blocking
</blockquote></details>

Good question. Changed. WDYT?
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 972 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1558#-OADay3C-9O8AoJX-p0z:-OAEn-zO87algijEbfUw:b-dha9gi) ([raw file](https://github.com/starkware-libs/sequencer/blob/85091d4fc69ba5365b518c24c75eb42291c3a1b8/crates/blockifier/src/transaction/account_transaction.rs#L972)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

It should work. The same pattern is used in `test_utils.rs` in this PR (and in many other places...)
</blockquote></details>

Like. Done.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1558)* status: 12 of 15 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @dorimedini-starkware)

___
*[`.github/workflows/blockifier_ci.yml` line 54 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1558#-OADaUq97Mh_MXyTaVb7:-OAEua3k8FmT7G0M2YBg:bvna2u5) ([raw file](https://github.com/starkware-libs/sequencer/blob/85091d4fc69ba5365b518c24c75eb42291c3a1b8/.github/workflows/blockifier_ci.yml#L54)):*
> ```YAML
>       - run: cargo build -p blockifier --features transaction_serde
>       - run: cargo test -p blockifier --features transaction_serde
>         # native-blckifier is not activated by any workspace crate; test the build.
> ```

Opps. Done

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1558)* status: 11 of 15 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 532 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1558#-OADYyRq5HRAPNYdR5aw:-OAEvJg51FdQ-eU4CK4O:bh6c03b) ([raw file](https://github.com/starkware-libs/sequencer/blob/7c9710f0abc60c50d16b89352c3e315bef567881/crates/blockifier/src/execution/syscalls/mod.rs#L532)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Good question. Changed. WDYT?
</blockquote></details>

Why not just:
```
if !is_cairo1(&class) {
    return Err(....)
}
```
The function `is_cairo1` covers all the cases. If it is false, it has to be Cairo 0.

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1558)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 156 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1558#-OAExIOc9YcCmL2xiJKL:-OAExIOdCUI4JYmFhPvL:b-2irl1c) ([raw file](https://github.com/starkware-libs/sequencer/blob/113fd37f65d7228c2f9f5dfd92e1e2543e730153/crates/blockifier/src/transaction/transactions.rs#L156)):*
> ```XML
>         let declare_version = declare_tx.version();
>         // Verify contract class version.
>         if matches!(class_info.contract_class(), ContractClass::V0(_)) {
> ```

As I suggested above



_Suggestion:_
```XML
        if !is_cairo1(class_info.contract_class()) {
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1558#-:-OAHOMvZ9w9lQrTXWZfw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
