### PR TITLE
feat(batcher): add validate flow

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Comment by Yael-Starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2050?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2050** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2050?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2049** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2049?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2042** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2042?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2046** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2046?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1951** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1951?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1996** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1996?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1986** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1986?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1985** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1985?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Yael-Starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2050)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2050#-OBenP-L2DsXt_c7vKx5:-OBenP-MAGbOg7qbAXjY:bsce4yn) ([raw file](https://github.com/starkware-libs/sequencer/blob/82f4e3fdcdb73e0c4555cd435f07c6790f488eaf/crates/starknet_batcher/src/batcher_test.rs#L120)):*
> ```XML
>                         drop(tx_provider);
>                     });
>                     Ok(())
> ```

Can you implement it with a oneshot channel instead of sleep?



_Code quote:_
```XML
                    // Spawn a task to keep tx_provider alive until the deadline is reached.
                    // Without this, the provider would be dropped, causing the batcher to fail
                    // when sending transactions to it during the test.
                    tokio::spawn(async move {
                        tokio::time::sleep(BLOCK_GENERATION_TIMEOUT).await;
                        drop(tx_provider);
                    });
                    Ok(())
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2050)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2050#-OBenP-L2DsXt_c7vKx5:-OBt26jcBpdXPgv390sG:bon959z) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4900177eb7d4cee8fee3a779afa13108ebbe99e/crates/starknet_batcher/src/batcher_test.rs#L120)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can you implement it with a oneshot channel instead of sleep?
</blockquote></details>

it think it complicates the code , since I need to to used to pass to create the channel  and then use the receiver in one place and the send in another place, and it won't be easy to read and understand.

wdyt of this solution?
It is a busy-wait loop so not very elegant, but the condition makes sense when reading.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2050)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2050#-OBenP-L2DsXt_c7vKx5:-OBt3vW99eqwKPu-VXMH:b4gpjsl) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4900177eb7d4cee8fee3a779afa13108ebbe99e/crates/starknet_batcher/src/batcher_test.rs#L120)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

it think it complicates the code , since I need to to used to pass to create the channel  and then use the receiver in one place and the send in another place, and it won't be easy to read and understand.

wdyt of this solution?
It is a busy-wait loop so not very elegant, but the condition makes sense when reading.
</blockquote></details>

writing again the corrected first sentence (since I accidentally left some unrelated words there):
I think it complicates the code , since I need to create the channel at the beginning and then use the receiver in one place and the sender in another place, and it won't be easy to read and understand.

**Comment by yair-starkware** [comment]
*[`crates/starknet_batcher/src/batcher_test.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2050#-OBenP-L2DsXt_c7vKx5:-OBtDTrvC3MhgEPaxb3O:b-t52vbn) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4900177eb7d4cee8fee3a779afa13108ebbe99e/crates/starknet_batcher/src/batcher_test.rs#L120)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

writing again the corrected first sentence (since I accidentally left some unrelated words there):
I think it complicates the code , since I need to create the channel at the beginning and then use the receiver in one place and the sender in another place, and it won't be easy to read and understand.
</blockquote></details>

Isn't the new loop a blocking code? 
How is it not blocking the tokio executor?

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2050)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @alonh5 and @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2050)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2050#-OBenP-L2DsXt_c7vKx5:-OBtFUIR2Jeb_Nvr15Xm:b-blsv86) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4900177eb7d4cee8fee3a779afa13108ebbe99e/crates/starknet_batcher/src/batcher_test.rs#L120)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Isn't the new loop a blocking code? 
How is it not blocking the tokio executor?
</blockquote></details>

yes it is blocking on thread, added yield to prevent that.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2050)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 46 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2050#-OBtoPfH4YGfZQKlkGgL:-OBtoPfH4YGfZQKlkGgM:b-80bq0j) ([raw file](https://github.com/starkware-libs/sequencer/blob/abf28078e6cfcc53743b7548e583be9679f27b8e/crates/starknet_batcher/src/batcher_test.rs#L46)):*
> ```XML
>     ProposalOutput,
>     ProposalResult,
>     ProposalStatus as InternalProposalStatus,
> ```

How about renaming it `InternalProposalStatus` at the definition and making it `pub(crate)`?



_Code quote:_
```XML
ProposalStatus as InternalProposalStatus,
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2050#-OBtqeLt87KU6UNiJr9-:-OBtqeLt87KU6UNiJr90:bns7azq) ([raw file](https://github.com/starkware-libs/sequencer/blob/abf28078e6cfcc53743b7548e583be9679f27b8e/crates/starknet_batcher/src/batcher_test.rs#L99)):*
> ```XML
> }
> 
> fn mock_proposal_manager_validate_flow() -> MockProposalManagerTraitWrapper {
> ```

Can you share code with `build_proposal_full_flow`? Same for test
___
*[`crates/starknet_batcher/src/batcher.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2050#-OBeNund3e4jw-s1ZWkM:-OBeNund3e4jw-s1ZWkN:b-saa0) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4900177eb7d4cee8fee3a779afa13108ebbe99e/crates/starknet_batcher/src/batcher.rs#L143)):*
> ```XML
>             )
>             .await
>             .map_err(BatcherError::from)?;
> ```

The ? operand can convert error types



_Suggestion:_
```XML
            .await?;
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2050)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2050#-OBeNund3e4jw-s1ZWkM:-OBu3UFJDSYWLxdW7esX:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4900177eb7d4cee8fee3a779afa13108ebbe99e/crates/starknet_batcher/src/batcher.rs#L143)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

The ? operand can convert error types
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 46 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2050#-OBtoPfH4YGfZQKlkGgL:-OBu0IFYDY3_FaUwJ9VE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/abf28078e6cfcc53743b7548e583be9679f27b8e/crates/starknet_batcher/src/batcher_test.rs#L46)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

How about renaming it `InternalProposalStatus` at the definition and making it `pub(crate)`?
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2050#-OBtqeLt87KU6UNiJr9-:-OBu3N4eE2t6p_Kwj4dn:b7hxjsk) ([raw file](https://github.com/starkware-libs/sequencer/blob/abf28078e6cfcc53743b7548e583be9679f27b8e/crates/starknet_batcher/src/batcher_test.rs#L99)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you share code with `build_proposal_full_flow`? Same for test
</blockquote></details>

shared the mock properties,
not much to share in the test.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2050)* status: all files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2050#-OBuNaUr7f38SBna5jsP:-OBuNaUr7f38SBna5jsQ:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/561b8720f2b54c9309a484d71b7a478d70d1a649/crates/starknet_batcher/src/batcher_test.rs#L57)):*
> ```XML
> const PROPOSAL_ID: ProposalId = ProposalId(0);
> 
> fn non_default_proposal_commitment() -> ProposalCommitment {
> ```





_Suggestion:_
```XML
proposal_commitment
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 153 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2050#-OBuOcRs1l-88lM_nZa2:-OBuOcRs1l-88lM_nZa3:bthqlbn) ([raw file](https://github.com/starkware-libs/sequencer/blob/561b8720f2b54c9309a484d71b7a478d70d1a649/crates/starknet_batcher/src/batcher_test.rs#L153)):*
> ```XML
>     let mut batcher = batcher(proposal_manager);
> 
>     // TODO(Yael 14/11/2024): The test will pass without calling start height. Leaving this here
> ```

Why will it pass? Didn'y you say the `times(1)` makes calling it once mandatory?



_Code quote:_
```XML
 The test will pass without calling start height
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 166 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2050#-OBuP32jCKuQ38-iw-aO:-OBuP32kAranPOEqeAgV:bqgnxje) ([raw file](https://github.com/starkware-libs/sequencer/blob/561b8720f2b54c9309a484d71b7a478d70d1a649/crates/starknet_batcher/src/batcher_test.rs#L166)):*
> ```XML
>     let send_proposal_input_txs = SendProposalContentInput {
>         proposal_id: PROPOSAL_ID,
>         content: SendProposalContent::Txs(test_txs(0..1)),
> ```

Why only one tx?



_Code quote:_
```XML
test_txs(0..1)
```

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2050)* status: all files reviewed, 3 unresolved discussions (waiting on @Yael-Starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2050)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 153 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2050#-OBuOcRs1l-88lM_nZa2:-OBxq0Pb959x1XOHPnOU:bi3ln1z) ([raw file](https://github.com/starkware-libs/sequencer/blob/561b8720f2b54c9309a484d71b7a478d70d1a649/crates/starknet_batcher/src/batcher_test.rs#L153)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why will it pass? Didn'y you say the `times(1)` makes calling it once mandatory?
</blockquote></details>

I meant if we delete both the call and the expectation.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 166 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2050#-OBuP32jCKuQ38-iw-aO:-OBxqaTY555V5r-sbgbv:b9wyl48) ([raw file](https://github.com/starkware-libs/sequencer/blob/561b8720f2b54c9309a484d71b7a478d70d1a649/crates/starknet_batcher/src/batcher_test.rs#L166)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why only one tx?
</blockquote></details>

it doesn't really matter since the block_builder is mocked. I just wanted to send one SendProposalContentInput with Txs and one with Finish.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2050)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 153 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2050#-OBuOcRs1l-88lM_nZa2:-OBxruaJ1GEoRIu0ylUC:b5exstc) ([raw file](https://github.com/starkware-libs/sequencer/blob/561b8720f2b54c9309a484d71b7a478d70d1a649/crates/starknet_batcher/src/batcher_test.rs#L153)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I meant if we delete both the call and the expectation.
</blockquote></details>

added this info to the comment
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2050#-OBuNaUr7f38SBna5jsP:-OBxrxOm-BXDaipB_6aK:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/561b8720f2b54c9309a484d71b7a478d70d1a649/crates/starknet_batcher/src/batcher_test.rs#L57)):*
> ```XML
> const PROPOSAL_ID: ProposalId = ProposalId(0);
> 
> fn non_default_proposal_commitment() -> ProposalCommitment {
> ```

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2050#-:-OBzMOl28BZYPtbIMWnG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
