### PR TITLE
refactor(starknet_batcher): create a function to get_height from storage for code dedup

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2665?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2665** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2665?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2665?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2603** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2603?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2604](https://github.com/starkware-libs/sequencer/pull/2604) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2604?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2665#-:-OE9Mq_d3icWDlFPuntJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2665)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2665#-OE9ard1EgMlk6pfx0Pk:-OE9ard1EgMlk6pfx0Pl:b5otvfp) ([raw file](https://github.com/starkware-libs/sequencer/blob/272bbfb1813f7a1e2dbd3c879057b8ea26873353/crates/starknet_batcher/src/batcher.rs#L105)):*
> ```XML
> 
>         let storage_height =
>             self.get_height_from_storage().map_err(|_| BatcherError::InternalError)?;
> ```

This is already returning an internal error IIUC



_Code quote:_
```XML
.map_err(|_| BatcherError::InternalError)?;
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2665)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2665#-OE9ard1EgMlk6pfx0Pk:-OED_MIJBumF2sO-uK_V:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/272bbfb1813f7a1e2dbd3c879057b8ea26873353/crates/starknet_batcher/src/batcher.rs#L105)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

This is already returning an internal error IIUC
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2665#-:-OEDid3G24MzZeclX_Nc:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2665)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Dec 16, 6:03 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2665).

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2665)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
