### PR TITLE
chore: add impl from rpc tx to snapi tx

### PR DESCRIPTION
**Pull request by ArniStarkware**
chore: add impl from rpc tx to snapi tx

chore: do not use executable tx to calculate hash

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/636)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#636** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/636?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/636)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/636#-O5T6ZXq0imMbhmlvtbL:-O5T6ZXq0imMbhmlvtbM:b-gdhpt4) (no related file):*
Please also review #657. It uses this change to streamline a test util.

___

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/636)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @yair-starkware)

___
*[`crates/gateway/src/utils.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/636#-O5TiiE55XzXsk_HG0Y_:-O5TiiE67mCvyjzI22Kh:b2fccb8) ([raw file](https://github.com/starkware-libs/sequencer/blob/5ee840c36385117a1eda614b5859864b3cc7d666/crates/gateway/src/utils.rs#L29)):*
> ```XML
>     match rpc_tx {
>         RpcTransaction::Declare(tx) => {
>             let declare_tx: DeclareTransaction = tx.clone().into();
> ```

Please avoid using the word "clone". 
This clone is expensive.



_Code quote:_
```XML
.clone()
```
___
*[`crates/starknet_api/src/transaction.rs` line 111 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/636#-O5Tiwvi24FQw3JL5Du2:-O5Tiwvi24FQw3JL5Du3:b8rjku9) ([raw file](https://github.com/starkware-libs/sequencer/blob/5ee840c36385117a1eda614b5859864b3cc7d666/crates/starknet_api/src/transaction.rs#L111)):*
> ```XML
> }
> 
> impl From<RpcTransaction> for Transaction {
> ```

Does it work?
maybe it would solve the clone issue.



_Suggestion:_
```XML
From<&RpcTransaction>
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/636)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1 and @yair-starkware)

___
*[`crates/gateway/src/utils.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/636#-O5TiiE55XzXsk_HG0Y_:-O5TjByO2_VEwfRZpQe3:b-kx1xd5) ([raw file](https://github.com/starkware-libs/sequencer/blob/5ee840c36385117a1eda614b5859864b3cc7d666/crates/gateway/src/utils.rs#L29)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please avoid using the word "clone". 
This clone is expensive.
</blockquote></details>

There are also clones in the original code (deleted in this PR).
So the suggested code is not worse than the original code. 
___
*[`crates/starknet_api/src/transaction.rs` line 111 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/636#-O5Tiwvi24FQw3JL5Du2:-O5TjrEe43pGeVT0b76r:b-i0rgbq) ([raw file](https://github.com/starkware-libs/sequencer/blob/5ee840c36385117a1eda614b5859864b3cc7d666/crates/starknet_api/src/transaction.rs#L111)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Does it work?
maybe it would solve the clone issue.
</blockquote></details>

It will not solve the clone issue. The fields that don't implement copy will have to be cloned at some point.

See for example deploy_account:
```
               signature: tx.signature.clone(),
                constructor_calldata: tx.constructor_calldata.clone(),
                paymaster_data: tx.paymaster_data.clone(),
```

We need to be careful when using a `From` method that is by reference—and inside is doing clones. It is actually bad as it hides the fact we are cloning.

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/636)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @yair-starkware)

___
*[`crates/starknet_api/src/transaction.rs` line 111 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/636#-O5Tiwvi24FQw3JL5Du2:-O5TmgWpD6kFJ2wTogHO:bvz5be9) ([raw file](https://github.com/starkware-libs/sequencer/blob/5ee840c36385117a1eda614b5859864b3cc7d666/crates/starknet_api/src/transaction.rs#L111)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

It will not solve the clone issue. The fields that don't implement copy will have to be cloned at some point.

See for example deploy_account:
```
               signature: tx.signature.clone(),
                constructor_calldata: tx.constructor_calldata.clone(),
                paymaster_data: tx.paymaster_data.clone(),
```

We need to be careful when using a `From` method that is by reference—and inside is doing clones. It is actually bad as it hides the fact we are cloning.
</blockquote></details>

I think these fields are small, so you can clone.
But the rest, like class contract, we dont want to clone.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/utils.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/636#-O5TiiE55XzXsk_HG0Y_:-O5YlNszAnpUlCrtq7NW:b-c3974x) ([raw file](https://github.com/starkware-libs/sequencer/blob/5ee840c36385117a1eda614b5859864b3cc7d666/crates/gateway/src/utils.rs#L29)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

There are also clones in the original code (deleted in this PR).
So the suggested code is not worse than the original code.
</blockquote></details>

As you pointed out, the most meaningful clone is for class_info. This PR should be reconsidered.

**Comment by ArniStarkware** [comment]
Replaced with #668

**Pull request closed without merging**
