### PR TITLE
chore: convert uses of once lock with lazy lock

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#1557** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1557?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1557)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dorimedini-starkware, and @MohammadNassar1)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1557#-OAMYFeB04tUhgKI6Ts1:-OAMYFeC4Wtu1rYdmnTP:bgc6j8x) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf4aafa9297970d97461b95ca38eb4fafe2185bc/crates/gateway/src/stateless_transaction_validator_test.rs#L55)):*
> ```XML
>         validate_non_zero_l1_gas_fee: false,
>         validate_non_zero_l2_gas_fee: false,
>         ..DEFAULT_VALIDATOR_CONFIG_FOR_TESTING.clone()
> ```

just trying to understand something:
I tried to understand why some of the times you use *VAR and sometimes VAR.clone().
I think the reason for the different usage is the copy trait.
but here for example you could have used *DEFAULT_VALIDATOR_CONFIG_FOR_TESTING, I checked, and I'm not sure why.
can you explain the rational? 



_Code quote:_
```XML
DEFAULT_VALIDATOR_CONFIG_FOR_TESTING.clone()
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1557)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @dorimedini-starkware, @MohammadNassar1, and @Yael-Starkware)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1557#-OAMYFeB04tUhgKI6Ts1:-OAMaZAmBZzPHfwF_lVL:b5fmbe5) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf4aafa9297970d97461b95ca38eb4fafe2185bc/crates/gateway/src/stateless_transaction_validator_test.rs#L55)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

just trying to understand something:
I tried to understand why some of the times you use *VAR and sometimes VAR.clone().
I think the reason for the different usage is the copy trait.
but here for example you could have used *DEFAULT_VALIDATOR_CONFIG_FOR_TESTING, I checked, and I'm not sure why.
can you explain the rational?
</blockquote></details>

In this specific case - there was no rationale. Fixed.

I just wrote what I needed to write for the values to be accepted.
Thinking about it more - I understand this value should not have been hidden under LazyLock if it is always cloned. But since it is sometimes not cloned (Thanks to you) it is fine.

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1557#-OAMYFeB04tUhgKI6Ts1:-OAMfBg56tkMtgqg4r1r:b2r2t5x) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf4aafa9297970d97461b95ca38eb4fafe2185bc/crates/gateway/src/stateless_transaction_validator_test.rs#L55)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

In this specific case - there was no rationale. Fixed.

I just wrote what I needed to write for the values to be accepted.
Thinking about it more - I understand this value should not have been hidden under LazyLock if it is always cloned. But since it is sometimes not cloned (Thanks to you) it is fine.
</blockquote></details>

I think it is wrong to use a LazyLock - if the value is copied each time anyway...

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1557)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @MohammadNassar1)

___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1557#-OAMYFeB04tUhgKI6Ts1:-OAMfZBY0sXKfKF215d3:b-560u81) ([raw file](https://github.com/starkware-libs/sequencer/blob/bf4aafa9297970d97461b95ca38eb4fafe2185bc/crates/gateway/src/stateless_transaction_validator_test.rs#L55)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I think it is wrong to use a LazyLock - if the value is copied each time anyway...
</blockquote></details>

not sure, it still has an advantage that it is initialized only once

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1557)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dorimedini-starkware and @MohammadNassar1)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1557)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @MohammadNassar1)

**Pull request merged**
