### PR TITLE
chore: refactor deploy account as wrapper

### PR DESCRIPTION
**Pull request by ArniStarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

For internal deploy account transaction, the data is inseparable from the implementation.
The data of `IntrnalDeployAccountTransaction` and of `DeployAccountTransaction` (on the blockifier) is duplicated.

## What is the new behavior?

- Refactor `DeployAccountTransaction` as a wrapper of `IntrnalDeployAccountTransaction` while keeping the implementation.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/92)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#93** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/93?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#92** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/92?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/92)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @dafnamatsry and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/92#-O37AELv0D2mockCpp35:-O37AELv0D2mockCpp36:b-7xj55n) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4914741c7ab4d6ceea7877398e176f78347d783/crates/blockifier/src/transaction/account_transaction.rs#L77)):*
> ```XML
>         match self {
>             Self::Declare(tx) => tx.tx.version(),
>             Self::DeployAccount(tx) => tx.tx.tx.version(),
> ```

Yuck.



_Code quote:_
```XML
            Self::DeployAccount(tx) => tx.tx.tx.version(),
```

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/92)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/92#-O37AELv0D2mockCpp35:-O37G57Q-dy-Vb1Iab_V:bb70xp9) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4914741c7ab4d6ceea7877398e176f78347d783/crates/blockifier/src/transaction/account_transaction.rs#L77)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Yuck.
</blockquote></details>

OMG!
___
*[`crates/blockifier/src/transaction/transactions.rs` line 296 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/92#-O37SYPWE75KMDKB-xcK:-O37SYPWE75KMDKB-xcL:b-wvc2ii) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4914741c7ab4d6ceea7877398e176f78347d783/crates/blockifier/src/transaction/transactions.rs#L296)):*
> ```XML
>     // Indicates the presence of the only_query bit in the version.
>     pub only_query: bool,
> }
> ```

Can we use `Deref` here?
So, we don't need to add `tx` in all the place?



_Code quote:_
```XML
pub struct DeployAccountTransaction {
    pub tx: starknet_api::executable_transaction::DeployAccountTransaction,
    // Indicates the presence of the only_query bit in the version.
    pub only_query: bool,
}
```

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/transactions.rs` line 296 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/92#-O37SYPWE75KMDKB-xcK:-O37XWug74-6IDfJmPDV:b4w8o75) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4914741c7ab4d6ceea7877398e176f78347d783/crates/blockifier/src/transaction/transactions.rs#L296)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can we use `Deref` here?
So, we don't need to add `tx` in all the place?
</blockquote></details>

I am unfamiliar with this design pattern ( I assume this is what you mean).
Please elaborate.

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/transaction/transactions.rs` line 296 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/92#-O37SYPWE75KMDKB-xcK:-O37YFNbB4xFjGirmKEt:bg2aog) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4914741c7ab4d6ceea7877398e176f78347d783/crates/blockifier/src/transaction/transactions.rs#L296)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I am unfamiliar with this design pattern ( I assume this is what you mean).
Please elaborate.
</blockquote></details>

Upon further reading - I think I understand.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/92)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @dafnamatsry and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 296 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/92#-O37SYPWE75KMDKB-xcK:-O37lOj49pdJ5hEBqnXD:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4914741c7ab4d6ceea7877398e176f78347d783/crates/blockifier/src/transaction/transactions.rs#L296)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Upon further reading - I think I understand.
</blockquote></details>

Done.

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/92)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 296 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/92#-O37SYPWE75KMDKB-xcK:-O37oyWv1ohZ0UMWfXCa:b-83sjoh) ([raw file](https://github.com/starkware-libs/sequencer/blob/a4914741c7ab4d6ceea7877398e176f78347d783/crates/blockifier/src/transaction/transactions.rs#L296)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice!
___
*[`crates/blockifier/src/transaction/transactions.rs` line 383 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/92#-O37pEOTCLUXNm4dGRPE:-O37pEOTCLUXNm4dGRPF:b-q2ke9i) ([raw file](https://github.com/starkware-libs/sequencer/blob/e90a2752f2b6a11b41df4b6f0275008c82e2c088/crates/blockifier/src/transaction/transactions.rs#L383)):*
> ```XML
>         };
> 
>         match &self.tx.tx {
> ```

Deref cannot work here?



_Code quote:_
```XML
&self.tx.tx 
```
___
*[`crates/starknet_api/src/executable_transaction.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/92#-O37pQLX9Ls_fTXNlMFl:-O37pQLX9Ls_fTXNlMFm:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/e90a2752f2b6a11b41df4b6f0275008c82e2c088/crates/starknet_api/src/executable_transaction.rs#L71)):*
> ```XML
> }
> 
> impl std::ops::Deref for DeployAccountTransaction {
> ```





_Suggestion:_
```XML
Deref
```

**Comment by ArniStarkware** [comment]
*[`crates/starknet_api/src/executable_transaction.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/92#-O37pQLX9Ls_fTXNlMFl:-O3DHZqd3J_X-RqPXwFY:b-cxchxo) ([raw file](https://github.com/starkware-libs/sequencer/blob/e90a2752f2b6a11b41df4b6f0275008c82e2c088/crates/starknet_api/src/executable_transaction.rs#L71)):*
> ```XML
> }
> 
> impl std::ops::Deref for DeployAccountTransaction {
> ```

No longer relevant.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/92)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 383 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/92#-O37pEOTCLUXNm4dGRPE:-O3DHdvj0noCkNi3tnUk:b-m6iq3z) ([raw file](https://github.com/starkware-libs/sequencer/blob/e90a2752f2b6a11b41df4b6f0275008c82e2c088/crates/blockifier/src/transaction/transactions.rs#L383)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Deref cannot work here?
</blockquote></details>

Used a different approch.

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/92)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @MohammadNassar1)

___
*[`crates/starknet_api/src/executable_transaction.rs` line 106 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/92#-O3DZ-MQCDfwVsoC2qO2:-O3R78i10xJN5dJvuMnW:bltk29y) ([raw file](https://github.com/starkware-libs/sequencer/blob/100b093d9121fe03c25d846e36263b787938df3c/crates/starknet_api/src/executable_transaction.rs#L106)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

What do you think about using a macro instead?
</blockquote></details>

Done.
I did not create a macro just for the ref for `tx`, as this is just one line. (It will repeat 3 times eventually - we can add it then if we wish).

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/92#-:-O3WhSyy6QK8STgqx3pH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 4 of 10 files at r4, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/92#-:-O4iwWU0EkuLZFUZjgko:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/92)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
