### PR TITLE
chore: check the broken CI

### PR DESCRIPTION
**Pull request by meship-starkware**

### CODE REVIEW

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2414#-:-ODH0OCx8r2SjRFpDv_c:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2414)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware)

___
*[`.github/workflows/blockifier_ci.yml` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2414#-ODH1CHT4Nq1hdX4wMc8:-ODH1hzv-7CL1QsVK1yM:b-3cre0d) ([raw file](https://github.com/starkware-libs/sequencer/blob/d49f5d4e4da088d73ba1a8144ca24eb07fdace9f/.github/workflows/blockifier_ci.yml#L47)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why did this solve the issue?
I am afraid of a situation where we want to build the native blockifier with the cairo-native feature, and we are unable to, because this native blockifier build requires ubuntu 20.04
</blockquote></details>

This is a temporary solution. @alon-dotan-starkware  said we would tackle the problem later.
Should I add a todo?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2414)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware)

___
*[`.github/workflows/blockifier_ci.yml` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2414#-ODH1CHT4Nq1hdX4wMc8:-ODH2cXs8agAnqgqi7WS:bk3ytex) ([raw file](https://github.com/starkware-libs/sequencer/blob/d49f5d4e4da088d73ba1a8144ca24eb07fdace9f/.github/workflows/blockifier_ci.yml#L47)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

This is a temporary solution. @alon-dotan-starkware  said we would tackle the problem later.
Should I add a todo?
</blockquote></details>

I am against the "later" approach unless we know for certain that it *can* work with ubuntu 20.04,
or,
if you add a temporary commit that makes the native_blockifier crate depend on the cairo_native feature,
build the artifacts,
and open a py-side PR that uses the new artifacts.
I wouldn't expect tests to actually pass but if the `.so` file is properly loaded by the py side, I'm fine with this

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2414#-:-ODLF9Fv7FEcT_8Xo4YB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)

**Pull request merged**
