### PR TITLE
build(blockifier_reexecution): add reexecution errors

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1302)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1302)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/errors.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O8qrbMjE1HSAM32FaD4:-O8qrbMjE1HSAM32FaD5:b-4r92fr) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc8d385bbfeda8c75f725b86a7d400ae69a95932/crates/blockifier_reexecution/src/state_reader/errors.rs#L12)):*
> ```XML
>     FromStateError(#[from] StateError),
>     #[error(transparent)]
>     FromRPCError(#[from] RPCStateReaderError),
> ```

variant name and inner type name can (and should) be identical; no need for `From` prefix



_Suggestion:_
```XML
    #[error(transparent)]
    StateError(#[from] StateError),
    #[error(transparent)]
    RPCError(#[from] RPCStateReaderError),
```
___
*[`crates/blockifier_reexecution/src/state_reader/errors.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O8qrsqb5UKUkHBoQaUp:-O8qrsqb5UKUkHBoQaUq:bwmzyer) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc8d385bbfeda8c75f725b86a7d400ae69a95932/crates/blockifier_reexecution/src/state_reader/errors.rs#L20)):*
> ```XML
> pub fn serde_err_to_reexecution_err(err: SerdeError) -> ReexecutionError {
>     ReexecutionError::StateReadError(format!("Failed to parse rpc result {:?}", err.to_string()))
> }
> ```

make SerdeError part of the new enum, no explicit conversion functions.
you will not be able to take advantage of the `?` syntax as it is now



_Code quote:_
```XML
// Converts a serde error to the error type of the state reader.
pub fn serde_err_to_reexecution_err(err: SerdeError) -> ReexecutionError {
    ReexecutionError::StateReadError(format!("Failed to parse rpc result {:?}", err.to_string()))
}
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O8qs24y9Pa6C7l5aeFu:-O8qs24y9Pa6C7l5aeFv:b-h2mfm6) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc8d385bbfeda8c75f725b86a7d400ae69a95932/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L128)):*
> ```XML
>         )
>         .map_err(serde_err_to_state_err)?;
>         serde_json::from_value(raw_tx_hashes).map_err(serde_err_to_reexecution_err)
> ```

once you delete the mapping and make the serde error part of the enum, you will be able to do this. please apply everywhere



_Suggestion:_
```XML
Ok(serde_json::from_value(raw_tx_hashes)?)
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1302)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/errors.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O8qrbMjE1HSAM32FaD4:-O8r8UV37PFKZJLjRDmB:b-qw7xad) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc8d385bbfeda8c75f725b86a7d400ae69a95932/crates/blockifier_reexecution/src/state_reader/errors.rs#L12)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

variant name and inner type name can (and should) be identical; no need for `From` prefix
</blockquote></details>

Done. The compiler suggests removing the postfix `Error` as well.
___
*[`crates/blockifier_reexecution/src/state_reader/errors.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O8qrsqb5UKUkHBoQaUp:-O8r9-McCpiCG1BwTNPJ:b-94aia) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc8d385bbfeda8c75f725b86a7d400ae69a95932/crates/blockifier_reexecution/src/state_reader/errors.rs#L20)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

make SerdeError part of the new enum, no explicit conversion functions.
you will not be able to take advantage of the `?` syntax as it is now
</blockquote></details>

 Done. Interesting - so why didn't they do this for StateError? :thinking: 
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O8qs24y9Pa6C7l5aeFu:-O8r8wvvDRIkKCHE69c3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc8d385bbfeda8c75f725b86a7d400ae69a95932/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L128)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

once you delete the mapping and make the serde error part of the enum, you will be able to do this. please apply everywhere
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1302)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/errors.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O8qrbMjE1HSAM32FaD4:-O93p3Ns9gxsvSqF1kCU:b-8y4ya2) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc8d385bbfeda8c75f725b86a7d400ae69a95932/crates/blockifier_reexecution/src/state_reader/errors.rs#L12)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done. The compiler suggests removing the postfix `Error` as well.
</blockquote></details>

not a bad idea, `ReexecutionError::RPC` looks better than `ReexecutionError::RPCError`, but non-blocking
___
*[`crates/blockifier_reexecution/src/state_reader/errors.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O8qrsqb5UKUkHBoQaUp:-O93pG7E1VjxWbdIYj_c:b-xxsfd5) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc8d385bbfeda8c75f725b86a7d400ae69a95932/crates/blockifier_reexecution/src/state_reader/errors.rs#L20)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done. Interesting - so why didn't they do this for StateError? :thinking:
</blockquote></details>

can you point to a code location you're referring to? it may be a mistake
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O93pTdWDolHWLC3XJR-:-O93pTdWDolHWLC3XJR0:bkzmh80) ([raw file](https://github.com/starkware-libs/sequencer/blob/748e655adb25ea2edc456e19136bc65e0da1f7d5/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L106)):*
> ```XML
>     }
> 
>     pub fn get_starknet_version(&self) -> StateResult<StarknetVersion> {
> ```

this method is not part of the StateReader trait implementation, it should return the top level error type



_Suggestion:_
```XML
ReexecutionResult
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O93pbeG6F5po-LBpJyy:-O93pbeH4NLTEOhCwl0C:bb7od0r) ([raw file](https://github.com/starkware-libs/sequencer/blob/748e655adb25ea2edc456e19136bc65e0da1f7d5/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L140)):*
> ```XML
>     }
> 
>     pub fn get_contract_class(&self, class_hash: &ClassHash) -> StateResult<StarknetContractClass> {
> ```

same



_Suggestion:_
```XML
ReexecutionResult
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1302)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/errors.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O8qrbMjE1HSAM32FaD4:-O94OgWG2x5B8HBfp-yf:bw2h5iu) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc8d385bbfeda8c75f725b86a7d400ae69a95932/crates/blockifier_reexecution/src/state_reader/errors.rs#L12)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not a bad idea, `ReexecutionError::RPC` looks better than `ReexecutionError::RPCError`, but non-blocking
</blockquote></details>

There's a possible future issue here - someone could use just the `RPC`...
___
*[`crates/blockifier_reexecution/src/state_reader/errors.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O8qrsqb5UKUkHBoQaUp:-O94OaG47chqd9CpN6cZ:b-gopa37) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc8d385bbfeda8c75f725b86a7d400ae69a95932/crates/blockifier_reexecution/src/state_reader/errors.rs#L20)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you point to a code location you're referring to? it may be a mistake
</blockquote></details>

Here:
https://github.com/starkware-libs/sequencer/blob/c161ccaa31464e401f96e3101bdbf3354374ce21/crates/gateway/src/errors.rs#L112C1-L115C2
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O93pTdWDolHWLC3XJR-:-O94QozH6SzH_KWWtzNR:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/748e655adb25ea2edc456e19136bc65e0da1f7d5/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L106)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this method is not part of the StateReader trait implementation, it should return the top level error type
</blockquote></details>

Done.
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O93pbeG6F5po-LBpJyy:-O94Q6O47mCrtmLMrwGz:bfyfhsl) ([raw file](https://github.com/starkware-libs/sequencer/blob/748e655adb25ea2edc456e19136bc65e0da1f7d5/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L140)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

same
</blockquote></details>

This one is called from a function in the `StateReade`r trait implementation (`get_compiled_contract_class`), so I guess it needs to be `StateResult`?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1302)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/errors.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O8qrbMjE1HSAM32FaD4:-O94cjDK-Dadu4g7GfBy:bsnm3ni) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc8d385bbfeda8c75f725b86a7d400ae69a95932/crates/blockifier_reexecution/src/state_reader/errors.rs#L12)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

There's a possible future issue here - someone could use just the `RPC`...
</blockquote></details>

We usually don't `use` enum variants, we `use` the enum and qualify the variant.
(if you `use` variants please don't, variants are not types, we should `use` types)
___
*[`crates/blockifier_reexecution/src/state_reader/errors.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O8qrsqb5UKUkHBoQaUp:-O94dMdv7rR_4_XRx_RD:b401mr3) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc8d385bbfeda8c75f725b86a7d400ae69a95932/crates/blockifier_reexecution/src/state_reader/errors.rs#L20)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Here:
https://github.com/starkware-libs/sequencer/blob/c161ccaa31464e401f96e3101bdbf3354374ce21/crates/gateway/src/errors.rs#L112C1-L115C2
</blockquote></details>

maybe they had a good reason, but I would ask someone from the GW team internally on slack
___
*[`crates/blockifier_reexecution/src/state_reader/errors.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O94dnrU7C7jIeue1kOD:-O94dnrU7C7jIeue1kOE:b-pnzw9h) ([raw file](https://github.com/starkware-libs/sequencer/blob/69f644f3af89b615fec8baf3c13f583920c715fd/crates/blockifier_reexecution/src/state_reader/errors.rs#L17)):*
> ```XML
>     /// Represents all unexpected errors that may occur while reading from state.
>     #[error("Failed to read from state: {0}.")]
>     StateReadError(String),
> ```

the only usage you have of this is converting an existing error type to string.
please replace this with the respective `#[from]`, no need to stringify (right?)



_Code quote:_
```XML
    #[error("Failed to read from state: {0}.")]
    StateReadError(String),
```
___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O93pbeG6F5po-LBpJyy:-O94dhR8DVtQ501HbVGG:b-7tegs0) ([raw file](https://github.com/starkware-libs/sequencer/blob/748e655adb25ea2edc456e19136bc65e0da1f7d5/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L140)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

This one is called from a function in the `StateReade`r trait implementation (`get_compiled_contract_class`), so I guess it needs to be `StateResult`?
</blockquote></details>

ah ok

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1302)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/errors.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O8qrbMjE1HSAM32FaD4:-O94n4f593uzyk5y-PfU:b8j6g5y) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc8d385bbfeda8c75f725b86a7d400ae69a95932/crates/blockifier_reexecution/src/state_reader/errors.rs#L12)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

We usually don't `use` enum variants, we `use` the enum and qualify the variant.
(if you `use` variants please don't, variants are not types, we should `use` types)
</blockquote></details>

Done. OK, I didn't know that.
___
*[`crates/blockifier_reexecution/src/state_reader/errors.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O8qrsqb5UKUkHBoQaUp:-O94lbI93IGbQFt7G4Ci:bezd7eu) ([raw file](https://github.com/starkware-libs/sequencer/blob/cc8d385bbfeda8c75f725b86a7d400ae69a95932/crates/blockifier_reexecution/src/state_reader/errors.rs#L20)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe they had a good reason, but I would ask someone from the GW team internally on slack
</blockquote></details>

Sure, will check.
___
*[`crates/blockifier_reexecution/src/state_reader/errors.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O94dnrU7C7jIeue1kOD:-O94lTo72TXVoMiotOH4:b-qyvg2r) ([raw file](https://github.com/starkware-libs/sequencer/blob/69f644f3af89b615fec8baf3c13f583920c715fd/crates/blockifier_reexecution/src/state_reader/errors.rs#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the only usage you have of this is converting an existing error type to string.
please replace this with the respective `#[from]`, no need to stringify (right?)
</blockquote></details>

Done. I don't know whether it's needed, I just know that's what was done before this PR.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1302)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/errors.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O94dnrU7C7jIeue1kOD:-O94t3fyE7g4B1wifDHz:bnvowfh) ([raw file](https://github.com/starkware-libs/sequencer/blob/69f644f3af89b615fec8baf3c13f583920c715fd/crates/blockifier_reexecution/src/state_reader/errors.rs#L17)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done. I don't know whether it's needed, I just know that's what was done before this PR.
</blockquote></details>

before this PR, this crate didn't have it's own error enum :)
we no longer need to convert errors in any way, if you encounter new error types that can possibly arise, add the respective variant to the enum
___
*[`crates/blockifier_reexecution/src/state_reader/errors.rs` line 16 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O94t-gk2abrxYPSWZd5:-O94t-gk2abrxYPSWZd6:bvj2cob) ([raw file](https://github.com/starkware-libs/sequencer/blob/54bd7981e7012915e21a2a7b9639b12cfc270dbc/crates/blockifier_reexecution/src/state_reader/errors.rs#L16)):*
> ```XML
>     #[error(transparent)]
>     Serde(#[from] SerdeError),
>     /// Represents all unexpected errors that may occur while reading from state.
> ```

delete (no longer true)



_Code quote:_
```XML
/// Represents all unexpected errors that may occur while reading from state.
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1302)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/errors.rs` line 16 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-O94t-gk2abrxYPSWZd5:-O98wHIl9g8lOf_mjAw-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/54bd7981e7012915e21a2a7b9639b12cfc270dbc/crates/blockifier_reexecution/src/state_reader/errors.rs#L16)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete (no longer true)
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1302#-:-O99-RmNAJySbpeLcc9c:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
