### PR TITLE
feat(mempool_p2p): impl component starter for mempoolp2preceiver

### PR DESCRIPTION
**Pull request by eitanm-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1247)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1247)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/mempool_p2p/src/receiver/mod.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O94QlUt89niV8koMQWc:-O94QlUt89niV8koMQWd:bs01roz) ([raw file](https://github.com/starkware-libs/sequencer/blob/eaa70f9cf18a01593252034c99c49239a1d09e93/crates/mempool_p2p/src/receiver/mod.rs#L45)):*
> ```XML
> impl ComponentStarter for MempoolP2pReceiver {
>     async fn start(&mut self) -> Result<(), ComponentError> {
>         tokio::spawn(
> ```

Move this to the select. No need to spawn a different task for the network IMO
___
*[`crates/mempool_p2p/src/receiver/mod.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O94Qsqd2Rnw-BqpSZO3:-O94Qsqd2Rnw-BqpSZO4:b4ogfvf) ([raw file](https://github.com/starkware-libs/sequencer/blob/eaa70f9cf18a01593252034c99c49239a1d09e93/crates/mempool_p2p/src/receiver/mod.rs#L48)):*
> ```XML
>             self.network_manager
>                 .take()
>                 .expect("Network manager not configured")
> ```

Change the message into "Network manager is already taken. This probably happened because `start` was called twice"
___
*[`crates/mempool_p2p/src/receiver/mod.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O94SFme6OF0WclKb2lE:-O94SFme6OF0WclKb2lF:b-ieycxa) ([raw file](https://github.com/starkware-libs/sequencer/blob/eaa70f9cf18a01593252034c99c49239a1d09e93/crates/mempool_p2p/src/receiver/mod.rs#L50)):*
> ```XML
>                 .expect("Network manager not configured")
>                 .run()
>                 .map_err(|e| panic!("Network manager failed: {:?}", e)),
> ```

Map this into ComponentError::InternalComponentError and then use ?
___
*[`crates/mempool_p2p/src/receiver/mod.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O94TgLD-NmCAJ82m6ha:-O94TgLD-NmCAJ82m6hb:b7l1zn1) ([raw file](https://github.com/starkware-libs/sequencer/blob/eaa70f9cf18a01593252034c99c49239a1d09e93/crates/mempool_p2p/src/receiver/mod.rs#L54)):*
> ```XML
>         loop {
>             tokio::select! {
>                 Some((maybe_message, broadcasted_message_manager)) = self.broadcasted_messages_server.next() => {
> ```

the convention is maybe_x for option and x_result for result
___
*[`crates/mempool_p2p/src/receiver/mod.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O94UAAn68Vz-aAwNjeI:-O94UAAn68Vz-aAwNjeJ:bfhzlq) ([raw file](https://github.com/starkware-libs/sequencer/blob/eaa70f9cf18a01593252034c99c49239a1d09e93/crates/mempool_p2p/src/receiver/mod.rs#L55)):*
> ```XML
>             tokio::select! {
>                 Some((maybe_message, broadcasted_message_manager)) = self.broadcasted_messages_server.next() => {
>                     match maybe_message {
> ```

Extract this logic to an inner method called handle_broadcasted_message/handle_received_message
___
*[`crates/mempool_p2p/src/receiver/mod.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O94ToUr9kcWRBNpw4Na:-O94ToUr9kcWRBNpw4Nb:bzb6n3a) ([raw file](https://github.com/starkware-libs/sequencer/blob/eaa70f9cf18a01593252034c99c49239a1d09e93/crates/mempool_p2p/src/receiver/mod.rs#L69)):*
> ```XML
>                         }
>                         Err(e) => {
>                             warn!("Failed to receive transaction from network: {:?}", e);
> ```

We know that this is a conversion error, so you can type instead: "Received a faulty transaction from network: {:?}. Trying to report the sending peer"
___
*[`crates/mempool_p2p/src/receiver/test.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O94URXU2UJcPUgKkjct:-O94URXU2UJcPUgKkjcu:b-fw0htw) ([raw file](https://github.com/starkware-libs/sequencer/blob/eaa70f9cf18a01593252034c99c49239a1d09e93/crates/mempool_p2p/src/receiver/test.rs#L28)):*
> ```XML
> 
> #[derive(Clone)]
> struct MockGatewayClient {
> ```

Why not automock?

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1247)* status: 3 of 4 files reviewed, 9 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/mempool_p2p/src/receiver/mod.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O94lptDAP2pjUSQS906:-O94lptE4jESJu5M-SJU:b-w0z7bk) ([raw file](https://github.com/starkware-libs/sequencer/blob/eaa70f9cf18a01593252034c99c49239a1d09e93/crates/mempool_p2p/src/receiver/mod.rs#L48)):*
> ```XML
>             self.network_manager
>                 .take()
>                 .expect("Network manager not configured")
> ```

WDYT about allowing network_manager to be None, and if it's none to not run anything here? This will make your life easier at tests
___
*[`crates/mempool_p2p/src/receiver/test.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O94m-wC3GhJtm-RuEIX:-O94m-wC3GhJtm-RuEIY:bz4rfro) ([raw file](https://github.com/starkware-libs/sequencer/blob/eaa70f9cf18a01593252034c99c49239a1d09e93/crates/mempool_p2p/src/receiver/test.rs#L50)):*
> ```XML
>         ..
>     } = mock_network;
>     let mock_network_manager = NetworkManager::new(NetworkConfig::default(), None);
> ```

This isn't exactly mock. maybe other_network_manager? Also, please explain in comment what you're doing here

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1247)* status: 1 of 4 files reviewed, 9 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/mempool_p2p/src/receiver/mod.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O94QlUt89niV8koMQWc:-O955Dt9DCJt8UuGe_uH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/eaa70f9cf18a01593252034c99c49239a1d09e93/crates/mempool_p2p/src/receiver/mod.rs#L45)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move this to the select. No need to spawn a different task for the network IMO
</blockquote></details>

Done.
___
*[`crates/mempool_p2p/src/receiver/mod.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O94Qsqd2Rnw-BqpSZO3:-O955Jnd0hycG9pNyKD1:b44rs3i) ([raw file](https://github.com/starkware-libs/sequencer/blob/eaa70f9cf18a01593252034c99c49239a1d09e93/crates/mempool_p2p/src/receiver/mod.rs#L48)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change the message into "Network manager is already taken. This probably happened because `start` was called twice"
</blockquote></details>

It could also be because it wasn't provided upon init. I will write that it isn't found.
___
*[`crates/mempool_p2p/src/receiver/mod.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O94lptDAP2pjUSQS906:-O9569Dy-OHesuxfpknf:b-nwavcd) ([raw file](https://github.com/starkware-libs/sequencer/blob/eaa70f9cf18a01593252034c99c49239a1d09e93/crates/mempool_p2p/src/receiver/mod.rs#L48)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

WDYT about allowing network_manager to be None, and if it's none to not run anything here? This will make your life easier at tests
</blockquote></details>

We will return error if it is none and we can use that in tests the same way?
___
*[`crates/mempool_p2p/src/receiver/mod.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O94SFme6OF0WclKb2lE:-O95JfGM97BnjPY4viFo:bmjz1au) ([raw file](https://github.com/starkware-libs/sequencer/blob/eaa70f9cf18a01593252034c99c49239a1d09e93/crates/mempool_p2p/src/receiver/mod.rs#L50)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Map this into ComponentError::InternalComponentError and then use ?
</blockquote></details>

mapped but no need for ?
___
*[`crates/mempool_p2p/src/receiver/mod.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O94TgLD-NmCAJ82m6ha:-O956bR071dvbPFoh-mv:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/eaa70f9cf18a01593252034c99c49239a1d09e93/crates/mempool_p2p/src/receiver/mod.rs#L54)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

the convention is maybe_x for option and x_result for result
</blockquote></details>

Done.
___
*[`crates/mempool_p2p/src/receiver/mod.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O94UAAn68Vz-aAwNjeI:-O95Jctg1DvOUk_2DJe_:bb7462z) ([raw file](https://github.com/starkware-libs/sequencer/blob/eaa70f9cf18a01593252034c99c49239a1d09e93/crates/mempool_p2p/src/receiver/mod.rs#L55)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Extract this logic to an inner method called handle_broadcasted_message/handle_received_message
</blockquote></details>

TODO
___
*[`crates/mempool_p2p/src/receiver/mod.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O94ToUr9kcWRBNpw4Na:-O956mjn6QkvQlwMgRIE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/eaa70f9cf18a01593252034c99c49239a1d09e93/crates/mempool_p2p/src/receiver/mod.rs#L69)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

We know that this is a conversion error, so you can type instead: "Received a faulty transaction from network: {:?}. Trying to report the sending peer"
</blockquote></details>

Done.
___
*[`crates/mempool_p2p/src/receiver/test.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O94URXU2UJcPUgKkjct:-O95M6YCEFyWI7eNuSir:bb7462z) ([raw file](https://github.com/starkware-libs/sequencer/blob/eaa70f9cf18a01593252034c99c49239a1d09e93/crates/mempool_p2p/src/receiver/test.rs#L28)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why not automock?
</blockquote></details>

TODO
___
*[`crates/mempool_p2p/src/receiver/test.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O94m-wC3GhJtm-RuEIX:-O95KTTO-NCtjBoVN1mx:b3b4ejr) ([raw file](https://github.com/starkware-libs/sequencer/blob/eaa70f9cf18a01593252034c99c49239a1d09e93/crates/mempool_p2p/src/receiver/test.rs#L50)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This isn't exactly mock. maybe other_network_manager? Also, please explain in comment what you're doing here
</blockquote></details>

its a network_manager used as a placeholder for init. Calling it placeholder_network_manager

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1247)* status: all files reviewed, 5 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/mempool_p2p/src/receiver/mod.rs` line 57 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O99DaYd2LlEpPKwApZP:-O99DaYd2LlEpPKwApZQ:boa8i0a) ([raw file](https://github.com/starkware-libs/sequencer/blob/d902003dc8fff2489a44ec17a3ec54fcc09ff4d1/crates/mempool_p2p/src/receiver/mod.rs#L57)):*
> ```XML
>                         Ok(message) => {
>                             //TODO(eitan): Add message metadata.
>                             match self.gateway_client.add_tx(GatewayInput { rpc_tx: message.0, message_metadata: None }).await {
> ```

Make this non-blocking

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1247)* status: all files reviewed, 5 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/mempool_p2p/src/receiver/mod.rs` line 57 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-O99DaYd2LlEpPKwApZP:-O99DeVZ-auE9RxBn0Sm:bxr2mzo) ([raw file](https://github.com/starkware-libs/sequencer/blob/d902003dc8fff2489a44ec17a3ec54fcc09ff4d1/crates/mempool_p2p/src/receiver/mod.rs#L57)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Make this non-blocking
</blockquote></details>

by polling it in the select with some FuturesUnordered

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1247#-:-O99cZj_BIvvSMWm3Bmh:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @eitanm-starkware)

**Review by ShahakShama — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1247)* status: all files reviewed, 2 unresolved discussions (waiting on @eitanm-starkware)

**Review by ShahakShama — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1247)* status: all files reviewed, 2 unresolved discussions (waiting on @eitanm-starkware)

**Pull request closed without merging**
