### PR TITLE
test(blockifier): max fee exceeds balance errors on new resource bounds

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/764)

### CODE REVIEW

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/764)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 912 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O7i07gNEtjeNaDVd38j:-O7i07gNEtjeNaDVd38k:b-kp59g6) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dbaa4f9b7e11d2d2cbe6492e44916b0c8845de0/crates/blockifier/src/transaction/transactions_test.rs#L912)):*
> ```XML
>     let invalid_max_fee = Fee(BALANCE + 1);
>     // TODO(Ori, 1/2/2024): Write an indicative expect message explaining why the conversion works.
>     let balance_over_l1_gas_price: u64 =
> ```

Clearer?



_Suggestion:_
```XML
maximal_l1_amount
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 961 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O7i1ukQ59wIfy3y-lOn:-O7i1ukQ59wIfy3y-lOo:b-v2614o) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dbaa4f9b7e11d2d2cbe6492e44916b0c8845de0/crates/blockifier/src/transaction/transactions_test.rs#L961)):*
> ```XML
>     // TODO!(Aner): remove magic numbers, use function to calculate minimal amounts.
>     let min_l1_amount = 1652;
>     let min_l2_amount = 445500;
> ```

Do you know why these are needed here but weren't needed for the l1 cases above? 



_Code quote:_
```XML
    let min_l1_amount = 1652;
    let min_l2_amount = 445500;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 968 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O7i1Ut_99HT58bZX4_w:-O7i1Ut_99HT58bZX4_x:b-wlbemw) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dbaa4f9b7e11d2d2cbe6492e44916b0c8845de0/crates/blockifier/src/transaction/transactions_test.rs#L968)):*
> ```XML
>     // In the following cases, the balance is not enough to cover the gas price of the transaction.
>     // Minimal amounts are used to avoid failing the test due to min gas usage not covered.
>     for (l1_max_amount, l2_max_amount, l1_data_max_amount) in [
> ```

Why not modify the previous l1_gas txs tests for the all resources case as well? Loop between L1Resources once and AllResources and have less code (hopefully) and all scenarios for both types.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 969 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O7i0zlzCvq-MJWi6ZvS:-O7i0zlzCvq-MJWi6ZvT:bpj7wig) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dbaa4f9b7e11d2d2cbe6492e44916b0c8845de0/crates/blockifier/src/transaction/transactions_test.rs#L969)):*
> ```XML
>     // Minimal amounts are used to avoid failing the test due to min gas usage not covered.
>     for (l1_max_amount, l2_max_amount, l1_data_max_amount) in [
>         (min_l1_amount + balance_over_l1_gas_price + 1, min_l2_amount, 0),
> ```

Isn't this the tight bound we need?



_Suggestion:_
```XML
max(min_l1_amount, balance_over_l1_gas_price + 1)
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/764)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 912 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O7i07gNEtjeNaDVd38j:-O7mXKra2KqVFhvvUQ7s:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dbaa4f9b7e11d2d2cbe6492e44916b0c8845de0/crates/blockifier/src/transaction/transactions_test.rs#L912)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Clearer?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 961 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O7i1ukQ59wIfy3y-lOn:-O7mXUAs8lS1WLFitY1z:b-dy9b8i) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dbaa4f9b7e11d2d2cbe6492e44916b0c8845de0/crates/blockifier/src/transaction/transactions_test.rs#L961)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Do you know why these are needed here but weren't needed for the l1 cases above?
</blockquote></details>

Yes, because here I want to test each individual resource, so the other resources, if they are 0 for example, might fail a previous check and we won't get the correct error.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 968 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O7i1Ut_99HT58bZX4_w:-O7mXjIv1Gv3XphrhnzT:b-rd893d) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dbaa4f9b7e11d2d2cbe6492e44916b0c8845de0/crates/blockifier/src/transaction/transactions_test.rs#L968)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Why not modify the previous l1_gas txs tests for the all resources case as well? Loop between L1Resources once and AllResources and have less code (hopefully) and all scenarios for both types.
</blockquote></details>

I didn't understand your suggestion.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 969 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O7i0zlzCvq-MJWi6ZvS:-O7mWYduDeaJ2mFMp6Mp:bb117sq) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dbaa4f9b7e11d2d2cbe6492e44916b0c8845de0/crates/blockifier/src/transaction/transactions_test.rs#L969)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Isn't this the tight bound we need?
</blockquote></details>

Yes, but in any case, it was a temporary patch because of the bug. Now, it can be done without the `max` (though `max` is more correct, but is significantly longer and seems to not be needed).

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/764)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 912 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O7i07gNEtjeNaDVd38j:-O866whXCVpkyAUdpN79:b-mns953) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dbaa4f9b7e11d2d2cbe6492e44916b0c8845de0/crates/blockifier/src/transaction/transactions_test.rs#L912)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nope, it should be max **amount** (balance >= price * amount)
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 961 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O7i1ukQ59wIfy3y-lOn:-O86BRRK7A1crNIjYDrF:b-9v7sem) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dbaa4f9b7e11d2d2cbe6492e44916b0c8845de0/crates/blockifier/src/transaction/transactions_test.rs#L961)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Yes, because here I want to test each individual resource, so the other resources, if they are 0 for example, might fail a previous check and we won't get the correct error.
</blockquote></details>

Why can't we just use the maxes instead of the mins (and then avoid defining them)? I assume we fail on the per resource assertion before the total balance assertion.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 969 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O7i0zlzCvq-MJWi6ZvS:-O869qZW8rpum6KOF_39:b-vm5t2w) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dbaa4f9b7e11d2d2cbe6492e44916b0c8845de0/crates/blockifier/src/transaction/transactions_test.rs#L969)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Yes, but in any case, it was a temporary patch because of the bug. Now, it can be done without the `max` (though `max` is more correct, but is significantly longer and seems to not be needed).
</blockquote></details>

The bug? Do you mean that min_amount could have been larger than the max_amount and now it doesn't? I don't understand what happened
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 971 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O868QOF5oTVEpHXTunu:-O868QOF5oTVEpHXTunv:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/689ca5ef7c521ed889690a1779621753bb817c7e/crates/blockifier/src/transaction/transactions_test.rs#L971)):*
> ```XML
>     let min_l2_amount = 445500;
>     let min_l1_data_amount = 128;
>     let max_l2_gas_price: u64 =
> ```





_Suggestion:_
```XML
max_l2_gas_amount
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 973 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O868Tvd1E22fxTEqvTV:-O868Tvd1E22fxTEqvTW:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/689ca5ef7c521ed889690a1779621753bb817c7e/crates/blockifier/src/transaction/transactions_test.rs#L973)):*
> ```XML
>     let max_l2_gas_price: u64 =
>         (BALANCE / MAX_L2_GAS_PRICE).try_into().expect("Failed to convert u128 to u64.");
>     let max_l1_data_gas_price: u64 =
> ```





_Suggestion:_
```XML
max_l1_data_gas_amount
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/764)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 912 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O7i07gNEtjeNaDVd38j:-O87jEGB7wTjLnmdcLFj:b5pth8q) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dbaa4f9b7e11d2d2cbe6492e44916b0c8845de0/crates/blockifier/src/transaction/transactions_test.rs#L912)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Nope, it should be max **amount** (balance >= price * amount)
</blockquote></details>

Done. Sorry, I must have been super tired :grimacing: 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 961 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O7i1ukQ59wIfy3y-lOn:-O87hT7m2W1n7YCUAwaa:bpif9on) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dbaa4f9b7e11d2d2cbe6492e44916b0c8845de0/crates/blockifier/src/transaction/transactions_test.rs#L961)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Why can't we just use the maxes instead of the mins (and then avoid defining them)? I assume we fail on the per resource assertion before the total balance assertion.
</blockquote></details>

1. It wouldn't help if `min_amount`>`max_amount' (as was the case before the bug-fix)
2. It's better to make the test as tight as possible; I'm adding the `min_amount` only because it's necessary, putting `max_amount` slightly defeats the point of the test.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 969 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O7i0zlzCvq-MJWi6ZvS:-O87h-arBC7M_4_RlInL:b-j41jo5) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dbaa4f9b7e11d2d2cbe6492e44916b0c8845de0/crates/blockifier/src/transaction/transactions_test.rs#L969)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

The bug? Do you mean that min_amount could have been larger than the max_amount and now it doesn't? I don't understand what happened
</blockquote></details>

There was a bug that made the `l2_gas_price` super high, so the `max_amount` was very low (in particular, lower than `min_amount`); now that it's back to normal, there's no reason `min_amount` should be bigger than `max_amount` (though, technically, it can happen...). Your call if you want me to insert `max(...)`.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 971 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O868QOF5oTVEpHXTunu:-O87jD4V9_dzW828d8ws:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/689ca5ef7c521ed889690a1779621753bb817c7e/crates/blockifier/src/transaction/transactions_test.rs#L971)):*
> ```XML
>     let min_l2_amount = 445500;
>     let min_l1_data_amount = 128;
>     let max_l2_gas_price: u64 =
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 973 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O868Tvd1E22fxTEqvTV:-O87jKK3DU5_Rbambo9W:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/689ca5ef7c521ed889690a1779621753bb817c7e/crates/blockifier/src/transaction/transactions_test.rs#L973)):*
> ```XML
>     let max_l2_gas_price: u64 =
>         (BALANCE / MAX_L2_GAS_PRICE).try_into().expect("Failed to convert u128 to u64.");
>     let max_l1_data_gas_price: u64 =
> ```

Done.

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/764)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 968 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O7i1Ut_99HT58bZX4_w:-O8Wa9uU4qMhDVc_Nfp1:b-6v3p0w) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dbaa4f9b7e11d2d2cbe6492e44916b0c8845de0/crates/blockifier/src/transaction/transactions_test.rs#L968)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I didn't understand your suggestion.
</blockquote></details>

Never mind, too much of a change, I'll try to open a PR later on.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 969 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O7i0zlzCvq-MJWi6ZvS:-O8aTpHp2Y_qt2TNfvSG:bty3ioq) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dbaa4f9b7e11d2d2cbe6492e44916b0c8845de0/crates/blockifier/src/transaction/transactions_test.rs#L969)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

There was a bug that made the `l2_gas_price` super high, so the `max_amount` was very low (in particular, lower than `min_amount`); now that it's back to normal, there's no reason `min_amount` should be bigger than `max_amount` (though, technically, it can happen...). Your call if you want me to insert `max(...)`.
</blockquote></details>

Replace with asserts that max_amount/3 >= min_amount
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 964 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O86xBRe88zperlHxr51:-O86xBRe88zperlHxr52:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/689ca5ef7c521ed889690a1779621753bb817c7e/crates/blockifier/src/transaction/transactions_test.rs#L964)):*
> ```XML
>         class_info,
>     );
>     assert_failure_if_resource_bounds_exceed_balance(state, block_context, invalid_tx);
> ```





_Suggestion:_
```XML
    // V3 invoke.
    
    for (l1_max_amount, l2_max_amount, l1_data_max_amount) in [
        (max_l1_gas_price + 1, min_l2_amount, min_l1_data_amount),
        (min_l1_amount, max_l2_gas_price + 1, min_l1_data_amount),
        (min_l1_amount, min_l2_amount, max_l1_data_gas_price + 1),
        (max_l1_gas_price / 3 + 1, max_l2_gas_price / 3 + 1, max_l1_data_gas_price / 3 + 1),
    ] {
        let invalid_resource_bounds = ValidResourceBounds::AllResources(AllResourceBounds {
            l1_gas: ResourceBounds {
                max_amount: l1_max_amount,
                max_price_per_unit: MAX_L1_GAS_PRICE,
            },
            l2_gas: ResourceBounds {
                max_amount: l2_max_amount,
                max_price_per_unit: MAX_L2_GAS_PRICE,
            },
            l1_data_gas: ResourceBounds {
                max_amount: l1_data_max_amount,
                max_price_per_unit: MAX_L1_DATA_GAS_PRICE,
            },
        });

    let invalid_tx = account_invoke_tx(invoke_tx_args! {
        resource_bounds: invalid_l1_resource_bounds,
        ..default_args.clone()
    });
    assert_failure_if_resource_bounds_exceed_balance(state, block_context, invalid_tx);

    // Deploy.
    let invalid_tx = AccountTransaction::DeployAccount(deploy_account_tx(
        deploy_account_tx_args! {
            resource_bounds: max_l1_resource_bounds,
            class_hash: test_contract.get_class_hash()
        },
        &mut NonceManager::default(),
    ));
    assert_failure_if_resource_bounds_exceed_balance(state, block_context, invalid_tx);

    // Declare.
    let contract_to_declare = FeatureContract::Empty(CairoVersion::Cairo1);
    let class_info = calculate_class_info_for_testing(contract_to_declare.get_class());
    let invalid_tx = declare_tx(
        declare_tx_args! {
            class_hash: contract_to_declare.get_class_hash(),
            compiled_class_hash: contract_to_declare.get_compiled_class_hash(),
            sender_address: account_contract_address,
            resource_bounds: invalid_l1_resource_bounds,
        },
        class_info,
    );
    assert_failure_if_resource_bounds_exceed_balance(state, block_context, invalid_tx);
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/764)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 968 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O7i1Ut_99HT58bZX4_w:-O8alrnt5vbrfKIJc6tl:b-ieuofk) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dbaa4f9b7e11d2d2cbe6492e44916b0c8845de0/crates/blockifier/src/transaction/transactions_test.rs#L968)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Never mind, too much of a change, I'll try to open a PR later on.
</blockquote></details>

FYI https://reviewable.io/reviews/starkware-libs/sequencer/1228

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/764)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 969 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/764#-O7i0zlzCvq-MJWi6ZvS:-O8b05ja8itYvNVW5uTj:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8dbaa4f9b7e11d2d2cbe6492e44916b0c8845de0/crates/blockifier/src/transaction/transactions_test.rs#L969)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Replace with asserts that max_amount/3 >= min_amount
</blockquote></details>

Done.

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/764)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @nimrod-starkware)

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r13, 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/764)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 105 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/764#-OARo_n853bRQoEw9zSX:-OARo_n853bRQoEw9zSY:b-8nnkkx) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c6940fffcaf86eca488b09ab42d4cde4b4cf30a/crates/blockifier/src/test_utils.rs#L105)):*
> ```XML
> pub const MAX_L1_GAS_PRICE: NonzeroGasPrice = DEFAULT_STRK_L1_GAS_PRICE;
> pub const MAX_RESOURCE_COMMITMENT: Fee =
>     DEFAULT_L1_GAS_AMOUNT.nonzero_saturating_mul(MAX_L1_GAS_PRICE);
> ```

Not used



_Code quote:_
```XML
pub const MAX_RESOURCE_COMMITMENT: Fee =
    DEFAULT_L1_GAS_AMOUNT.nonzero_saturating_mul(MAX_L1_GAS_PRICE);
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 937 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/764#-OARpZ2oAlEmoijXwl-K:-OARpZ2oAlEmoijXwl-L:b-exf04b) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c6940fffcaf86eca488b09ab42d4cde4b4cf30a/crates/blockifier/src/transaction/transactions_test.rs#L937)):*
> ```XML
>     #[values(CairoVersion::Cairo0, CairoVersion::Cairo1)] account_cairo_version: CairoVersion,
> ) {
>     use starknet_api::execution_resources::GasAmount;
> ```

move up
___
*[`crates/starknet_api/src/execution_resources.rs` line 28 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/764#-OARqmXgDNB43_upQyMA:-OARqmXgDNB43_upQyMB:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c6940fffcaf86eca488b09ab42d4cde4b4cf30a/crates/starknet_api/src/execution_resources.rs#L28)):*
> ```XML
>     Hash,
> )]
> #[cfg_attr(any(test, feature = "testing"), derive(derive_more::Div))]
> ```





_Suggestion:_
```XML
#[cfg_attr(
    any(test, feature = "testing"),
    derive(derive_more::Add, derive_more::Div, derive_more::Sum, derive_more::AddAssign)
)]
#[derive(
    derive_more::Display,
    Clone,
    Copy,
    Debug,
    Default,
    Eq,
    PartialEq,
    PartialOrd,
    Ord,
    Serialize,
    Deserialize,
    Hash,
)]
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/764)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils.rs` line 105 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/764#-OARo_n853bRQoEw9zSX:-OARs5Co-2anxrKFUvGl:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c6940fffcaf86eca488b09ab42d4cde4b4cf30a/crates/blockifier/src/test_utils.rs#L105)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Not used
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 937 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/764#-OARpZ2oAlEmoijXwl-K:-OARsDAy6hIlwXCTTwJ1:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c6940fffcaf86eca488b09ab42d4cde4b4cf30a/crates/blockifier/src/transaction/transactions_test.rs#L937)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

move up
</blockquote></details>

Done.
___
*[`crates/starknet_api/src/execution_resources.rs` line 28 at r15](https://reviewable.io/reviews/starkware-libs/sequencer/764#-OARqmXgDNB43_upQyMA:-OARs1ZT1MfLmqWZYRWS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5c6940fffcaf86eca488b09ab42d4cde4b4cf30a/crates/starknet_api/src/execution_resources.rs#L28)):*
> ```XML
>     Hash,
> )]
> #[cfg_attr(any(test, feature = "testing"), derive(derive_more::Div))]
> ```

Done.

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/764#-:-OAT2SgG0rR6utJo1N65:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @nimrod-starkware)

**Review by TzahiTaub — APPROVED** [review]
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/764)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
