### PR TITLE
refactor(blockifier_reexecution): add chain ID to SerializableOfflineReexecutionData

### PR DESCRIPTION
**Pull request by dorimedini-starkware**

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1972?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1972** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1972?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1971** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1971?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1970** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1970?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by aner-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1972)* status: 0 of 221 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1972#-OB_GcjW2daMd_6kC-Iy:-OB_GcjW2daMd_6kC-Iz:b74uldf) ([raw file](https://github.com/starkware-libs/sequencer/blob/74cb4057f32687f2b8f558b1e3d7fb0fa1a0d5b8/crates/blockifier_reexecution/src/main.rs#L137)):*
> ```XML
>                 serializable_data_prev_block,
>                 serializable_data_next_block,
>                 chain_id: ChainId::Mainnet,
> ```

Is this really what we want? I mean, we probably want to save data for reexecution tests for Mainnet; do we also want to save and run tests for other networks; If not, then it should just be explicitly entered in the CLI, not saved in the file.



_Code quote:_
```XML
chain_id: ChainId::Mainnet,
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1972)* status: 0 of 221 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1972#-OB_GcjW2daMd_6kC-Iy:-OB_xOBy-XggrPz1qZij:b3uq6cw) ([raw file](https://github.com/starkware-libs/sequencer/blob/74cb4057f32687f2b8f558b1e3d7fb0fa1a0d5b8/crates/blockifier_reexecution/src/main.rs#L137)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Is this really what we want? I mean, we probably want to save data for reexecution tests for Mainnet; do we also want to save and run tests for other networks; If not, then it should just be explicitly entered in the CLI, not saved in the file.
</blockquote></details>

still relevant?
the idea is:
1. RPC tests guess the chain ID from the node URL; or, [get the chain ID explicitly if you want to override](https://reviewable.io/reviews/starkware-libs/sequencer/1974)
2. offline tests need to fetch the chain ID from the JSON (hence the addition of the chain ID to the JSON struct)

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/main.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1972#-OB_GcjW2daMd_6kC-Iy:-OBeMSjf5tzKHI7oOjcx:b-ro8scn) ([raw file](https://github.com/starkware-libs/sequencer/blob/74cb4057f32687f2b8f558b1e3d7fb0fa1a0d5b8/crates/blockifier_reexecution/src/main.rs#L137)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

still relevant?
the idea is:
1. RPC tests guess the chain ID from the node URL; or, [get the chain ID explicitly if you want to override](https://reviewable.io/reviews/starkware-libs/sequencer/1974)
2. offline tests need to fetch the chain ID from the JSON (hence the addition of the chain ID to the JSON struct)
</blockquote></details>

Are we planning to run reexecution in other networks often or in tests?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1972)* status: 0 of 221 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1972#-OB_GcjW2daMd_6kC-Iy:-OBe_B_SB2azPj8ybfPa:b-85dnha) ([raw file](https://github.com/starkware-libs/sequencer/blob/74cb4057f32687f2b8f558b1e3d7fb0fa1a0d5b8/crates/blockifier_reexecution/src/main.rs#L137)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Are we planning to run reexecution in other networks often or in tests?
</blockquote></details>

if we see interesting edge cases pop up in other networks, yes, I would like to be prepared.
maybe it will never but used in the CI but it was already useful for me, to manually test specific blocks from testnet

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/main.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1972#-OB_GcjW2daMd_6kC-Iy:-OBf1eTf8UmjL6_yTQZ7:b-7vhcp7) ([raw file](https://github.com/starkware-libs/sequencer/blob/74cb4057f32687f2b8f558b1e3d7fb0fa1a0d5b8/crates/blockifier_reexecution/src/main.rs#L137)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if we see interesting edge cases pop up in other networks, yes, I would like to be prepared.
maybe it will never but used in the CI but it was already useful for me, to manually test specific blocks from testnet
</blockquote></details>

I understand that testing in other networks is useful, but why do we need to store the network in the file?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1972)* status: 0 of 221 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1972#-OB_GcjW2daMd_6kC-Iy:-OBfR3LUAfhP7lycP-GB:byjlqrg) ([raw file](https://github.com/starkware-libs/sequencer/blob/74cb4057f32687f2b8f558b1e3d7fb0fa1a0d5b8/crates/blockifier_reexecution/src/main.rs#L137)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I understand that testing in other networks is useful, but why do we need to store the network in the file?
</blockquote></details>

because we need the block info for offline execution, right? the chain info requires knowledge of the network (in principle - in practice I think since the fee token addresses are the same it isn't really required, but good to have this for forward compatibility). no?

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/main.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1972#-OB_GcjW2daMd_6kC-Iy:-OByZ5gU-uihKtNllIG_:b8zslje) ([raw file](https://github.com/starkware-libs/sequencer/blob/74cb4057f32687f2b8f558b1e3d7fb0fa1a0d5b8/crates/blockifier_reexecution/src/main.rs#L137)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

because we need the block info for offline execution, right? the chain info requires knowledge of the network (in principle - in practice I think since the fee token addresses are the same it isn't really required, but good to have this for forward compatibility). no?
</blockquote></details>

I don't think it's necessary to add it right to the file—this seems like something we might never really use, and if we need it, the user can add the network via CLI. Adding the network to the file means we plan to make tests that rely on it, but at the moment, there's nothing to suggest such tests will ever be needed. For all the current networks, the behaviour is the same.

**Comment by aner-starkware** [comment]
*[`crates/blockifier_reexecution/src/main.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1972#-OB_GcjW2daMd_6kC-Iy:-OBy_CV16eODNFeYwtFY:br2i2st) ([raw file](https://github.com/starkware-libs/sequencer/blob/74cb4057f32687f2b8f558b1e3d7fb0fa1a0d5b8/crates/blockifier_reexecution/src/main.rs#L137)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I don't think it's necessary to add it right to the file—this seems like something we might never really use, and if we need it, the user can add the network via CLI. Adding the network to the file means we plan to make tests that rely on it, but at the moment, there's nothing to suggest such tests will ever be needed. For all the current networks, the behaviour is the same.
</blockquote></details>

*right now

**Review by aner-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1972)* status: 0 of 221 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @dorimedini-starkware)

**Review by aner-starkware — APPROVED** [review]
> Reviewed 2 of 221 files at r2, 219 of 219 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1972)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @dorimedini-starkware)

**Review by aner-starkware — APPROVED** [review]
> Reviewed 106 of 106 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1972)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Comment by dorimedini-starkware** [comment]
### Merge activity

* **Nov 19, 10:11 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1972).

**Pull request merged**
