### PR TITLE
test: use the exeutable tx creator test util for the account tx creator test util

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/749?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#749** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/749?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#748** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/748?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#747** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/747?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#672** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/672?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#519](https://github.com/starkware-libs/sequencer/pull/519) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/519?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#666** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/666?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#694](https://github.com/starkware-libs/sequencer/pull/694) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/694?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#701](https://github.com/starkware-libs/sequencer/pull/701) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/701?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#661** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/661?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#660** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/660?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/749)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/test_utils/invoke.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/749#-OB_R5376Os7275jp7uL:-OB_VJ3A3O3UId4oLWFk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f7d3cacbc86f194e08bc8f9f83690ff8f1714af/crates/blockifier/src/test_utils/invoke.rs#L9)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why not move to imports?
</blockquote></details>

Done.

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/749)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/749#-:-OBe7mXPCnuWGPxeTr6s:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/749)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @MohammadNassar1)

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/749)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @MohammadNassar1)

**Pull request merged**
