### PR TITLE
refactor(blockifier): move ugly code to native blockifier

### PR DESCRIPTION
**Pull request by Yoni-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1020)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1020)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1020#-O7hHWyL1_Sv9CnthJhs:-O7hHWyM7TDUziM4DM9V:bj39o2d) (no related file):*
please open a py side PR to make sure nothing was missed here

___
___
*[`crates/blockifier/src/transaction/objects.rs` line 288 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1020#-O7hHMOj4DjOShY861pY:-O7hHMOkDeFADLgKG7VL:b3bxptw) ([raw file](https://github.com/starkware-libs/sequencer/blob/6643538ef6c45c0e2a2e0079787aeffc984313e5/crates/blockifier/src/transaction/objects.rs#L288)):*
> ```XML
>     pub fn blob_gas_usage(&self) -> usize {
>         *self.0.get(abi_constants::BLOB_GAS_USAGE).unwrap()
>     }
> ```

these were unused...? if so why didn't clippy warn? if not, where is it now?



_Code quote:_
```XML
    #[cfg(test)]
    pub fn n_steps(&self) -> usize {
        *self.0.get(abi_constants::N_STEPS_RESOURCE).unwrap()
    }

    #[cfg(test)]
    pub fn gas_usage(&self) -> usize {
        *self.0.get(abi_constants::L1_GAS_USAGE).unwrap()
    }

    #[cfg(test)]
    pub fn blob_gas_usage(&self) -> usize {
        *self.0.get(abi_constants::BLOB_GAS_USAGE).unwrap()
    }
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1020)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1020#-O7hHWyL1_Sv9CnthJhs:-O7hMt-i1uLTrKsxbFGt:bm2nawh) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please open a py side PR to make sure nothing was missed here
</blockquote></details>

Done https://github.com/starkware-industries/starkware/pull/35988

___
___
*[`crates/blockifier/src/transaction/objects.rs` line 288 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1020#-O7hHMOj4DjOShY861pY:-O7hMulL1jv2iaed-LEx:bbz99n) ([raw file](https://github.com/starkware-libs/sequencer/blob/6643538ef6c45c0e2a2e0079787aeffc984313e5/crates/blockifier/src/transaction/objects.rs#L288)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

these were unused...? if so why didn't clippy warn? if not, where is it now?
</blockquote></details>

Unused, yes.
I'll google it. Maybe because they are public/with cfg?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1020)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/objects.rs` line 288 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1020#-O7hHMOj4DjOShY861pY:-O7hO_L-5KXW-nRjuUpR:b-7qpq7d) ([raw file](https://github.com/starkware-libs/sequencer/blob/6643538ef6c45c0e2a2e0079787aeffc984313e5/crates/blockifier/src/transaction/objects.rs#L288)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Unused, yes.
I'll google it. Maybe because they are public/with cfg?
</blockquote></details>

ah, `pub` is the issue, right

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1020#-:-O7hxajj8IaTJDQFp22A:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1020)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
