### PR TITLE
refactor: move node's main functionality into a public function

### PR DESCRIPTION
**Pull request by uriel-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/382)

### CODE REVIEW

**Review by lev-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/382)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @uriel-starkware)

___
*[`crates/mempool_node/src/communication.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/382#-O4-yNT36_8T1OfXwDC2:-O4-yNT36_8T1OfXwDC3:b-4prr8l) ([raw file](https://github.com/starkware-libs/sequencer/blob/d016d93cc5599ec1f4c305b12ce8a812060a4ffc/crates/mempool_node/src/communication.rs#L59)):*
> ```XML
> }
> 
> pub fn setup_from_config(config: &MempoolNodeConfig) -> (MempoolNodeClients, Servers) {
> ```

Not a meaningful name. Should be something like 'create_clients_servers_from_config'.
Also, the wrong module, in my opinion. It should be in 'servers.rs' or maybe in a separate module 'utils.rs' because it groups together communication (Clients) and Servers.

**Review by uriel-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/382)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @lev-starkware)

___
*[`crates/mempool_node/src/communication.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/382#-O4-yNT36_8T1OfXwDC2:-O40Aa7w4VR_UOgcDwHf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d016d93cc5599ec1f4c305b12ce8a812060a4ffc/crates/mempool_node/src/communication.rs#L59)):*
<details><summary><i>Previously, lev-starkware wrote…</i></summary><blockquote>

Not a meaningful name. Should be something like 'create_clients_servers_from_config'.
Also, the wrong module, in my opinion. It should be in 'servers.rs' or maybe in a separate module 'utils.rs' because it groups together communication (Clients) and Servers.
</blockquote></details>

Done.

**Review by lev-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/382#-:-O40NW3T-aFtCQYo-cID:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

**Review by uriel-starkware — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/382)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

**Review by uriel-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/382)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @lev-starkware)

**Review by lev-starkware — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/382#-:-O49akeOE0Vg4pLee-MD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @uriel-starkware)

**Review by lev-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/382)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)

**Pull request merged**
