### PR TITLE
feat(blockifier): tighter post-execution fee recommendation for new g…

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
…as bounds

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1331)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1331)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1331#-O8won570eLD2dTzdzHf:-O8won570eLD2dTzdzHg:b-u3xh5h) (no related file):*
tested [here](https://reviewable.io/reviews/starkware-libs/sequencer/1330) (manually ATM, by cherry-picking; will rebase test migration stack once this fix is merged)

___

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1331)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1331#-O93SpJXBIiwXnFq0cfR:-O93SpJXBIiwXnFq0cfS:bttq5d1) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2364d040ba0dc5f0b7813bddd765483b1488847/crates/blockifier/src/fee/fee_checks.rs#L73)):*
> ```XML
>             // the sender initially could cover the resource bounds), and (b) the actual resources
>             // are within the resource bounds set by the sender.
>             FeeCheckError::InsufficientFeeTokenBalance { .. } => actual_fee,
> ```

How can he pay this if he doesn't have enough balance?



_Code quote:_
```XML
=> actual_fee,
```
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1331#-O93TB390Esr_5hVOS4L:-O93TB390Esr_5hVOS4M:b-w6ghox) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2364d040ba0dc5f0b7813bddd765483b1488847/crates/blockifier/src/fee/fee_checks.rs#L75)):*
> ```XML
>             FeeCheckError::InsufficientFeeTokenBalance { .. } => actual_fee,
>             // If max fee exceeded (deprecated tx), the recommended fee is the max fee. The
>             // pre-validation phase ensures the account can cover the max fee.
> ```

It might changed during the execution



_Code quote:_
```XML
pre-validation phase ensures the account can cover the max fee.
```
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1331#-O93RXdE0pfAx0BeQbYQ:-O93RXdE0pfAx0BeQbYR:brivjzf) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2364d040ba0dc5f0b7813bddd765483b1488847/crates/blockifier/src/fee/fee_checks.rs#L94)):*
> ```XML
>                         l1_bounds.max_amount,
>                         actual_gas.to_discounted_l1_gas(gas_prices),
>                     )),
> ```

Is there a scenario where the gas here is not `l1_bounds.max_amount`?



_Code quote:_
```XML
                    ValidResourceBounds::L1Gas(l1_bounds) => GasVector::from_l1_gas(std::cmp::min(
                        l1_bounds.max_amount,
                        actual_gas.to_discounted_l1_gas(gas_prices),
                    )),
```
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 252 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1331#-O93Rnkz0yQSjaQ6ijlk:-O93Rnkz0yQSjaQ6ijll:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/881c4b0635550d091fcbfddc6aa48e2de71a56fc/crates/blockifier/src/fee/fee_checks.rs#L252)):*
> ```XML
>         let can_pay_fee_result = FeeCheckReport::check_can_pay_fee(state, tx_context, tx_receipt);
> 
>         for fee_check_result in [cost_with_bounds_result, can_pay_fee_result] {
> ```





_Suggestion:_
```XML
cost_within_bounds
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1331)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1331#-O93SpJXBIiwXnFq0cfR:-O93TTPj2lC7wItv5R2d:b6j0cuu) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2364d040ba0dc5f0b7813bddd765483b1488847/crates/blockifier/src/fee/fee_checks.rs#L73)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

How can he pay this if he doesn't have enough balance?
</blockquote></details>

Oh, because we are going to revert the tx. Please mention this
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1331#-O93TB390Esr_5hVOS4L:-O93Tg5g-qwVcFBiOhkU:b6j0cuu) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2364d040ba0dc5f0b7813bddd765483b1488847/crates/blockifier/src/fee/fee_checks.rs#L75)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

It might changed during the execution
</blockquote></details>

Oh, because we are going to revert the tx. Please mention this

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1331)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1331#-O93SpJXBIiwXnFq0cfR:-O93kUCA1taRbMsPGUyd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2364d040ba0dc5f0b7813bddd765483b1488847/crates/blockifier/src/fee/fee_checks.rs#L73)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Oh, because we are going to revert the tx. Please mention this
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1331#-O93TB390Esr_5hVOS4L:-O93kTStBx5Cmwhw0j8R:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2364d040ba0dc5f0b7813bddd765483b1488847/crates/blockifier/src/fee/fee_checks.rs#L75)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Oh, because we are going to revert the tx. Please mention this
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1331#-O93RXdE0pfAx0BeQbYQ:-O93jRss0vh3gpungkQb:byikj68) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2364d040ba0dc5f0b7813bddd765483b1488847/crates/blockifier/src/fee/fee_checks.rs#L94)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Is there a scenario where the gas here is not `l1_bounds.max_amount`?
</blockquote></details>

there shouldn't be, should I revert to just `l1_bounds.ax_amount` without the `min`?

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1331#-:-O93na_LBZYUcSa_XsLJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/fee_checks.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1331#-O93RXdE0pfAx0BeQbYQ:-O93nHyU9X1i5020-znJ:bgdtrok) ([raw file](https://github.com/starkware-libs/sequencer/blob/e2364d040ba0dc5f0b7813bddd765483b1488847/crates/blockifier/src/fee/fee_checks.rs#L94)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there shouldn't be, should I revert to just `l1_bounds.ax_amount` without the `min`?
</blockquote></details>

Yes, clearer

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1331)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1331)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
