### PR TITLE
test(mempool_p2p): test received rpc transactions are being broadcasted

### PR DESCRIPTION
**Pull request by AlonLStarkWare**
- chore: changing closure Fn requirements on integration test utils
- test(mempool_p2p): test received rpc transactions are being broadcasted

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1941)* status: all files reviewed, 10 unresolved discussions (waiting on @AlonLStarkWare)

___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVNfOW7IUqEGvgOGMf:-OBVNfOW7IUqEGvgOGMg:bf1flv5) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L63)):*
> ```XML
>     // Create and send transactions.
>     let expected_batched_tx_hashes =
>         run_integration_test_scenario(tx_generator, &mut |tx: RpcTransaction| {
> ```

Try to remove this change
___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 128 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVOL_uCBdjKfjPxZlB:-OBVOL_v7rATDclVyrwR:b-kbwko5) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L128)):*
> ```XML
> #[tokio::test]
> async fn test_mempool_sends_tx_to_other_peer(tx_generator: MultiAccountTransactionGenerator) {
>     let handle = Handle::current();
> ```

Add TODO to remove code duplication with FlowTestSetup
___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 155 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVOYH65IhUJNBASQDA:-OBVOYH65IhUJNBASQDB:by8vr4h) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L155)):*
> ```XML
> 
>     let chain_id = storage_for_test.batcher_storage_config.db_config.chain_id.clone();
>     // TODO(Tsabary): create chain_info in setup, and pass relevant values throughout.
> ```

Remove this TODO
___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 163 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVOfoa6ILetcnhqsP9:-OBVOfoa6ILetcnhqsPA:b-7ko81u) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L163)):*
> ```XML
>     let http_server_config = create_http_server_config().await;
>     let rpc_state_reader_config = test_rpc_state_reader_config(rpc_server_addr);
>     let consensus_manager_config = ConsensusManagerConfig {
> ```

Is this necessary? You're turning consensus off anyway
___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 196 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVPn0f2dD7raa0WXgi:-OBVPn0f2dD7raa0WXgj:bvf430v) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L196)):*
> ```XML
>     tokio::time::sleep(std::time::Duration::from_millis(1000)).await;
> 
>     // create a list of the sent transactions to compare against when listening to the broadcasted
> ```

to the broadcasted transaction
___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 196 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVPpOSDKHtw3Oc6c1R:-OBVPpOSDKHtw3Oc6c1S:b-4jtlxa) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L196)):*
> ```XML
>     tokio::time::sleep(std::time::Duration::from_millis(1000)).await;
> 
>     // create a list of the sent transactions to compare against when listening to the broadcasted
> ```

IMO this comment is redundant and can be erased
___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 197 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVPhZS4xj30uUSIqxb:-OBVPhZS4xj30uUSIqxc:bm7660t) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L197)):*
> ```XML
> 
>     // create a list of the sent transactions to compare against when listening to the broadcasted
>     let mut expected_txs = vec![];
> ```

This should be a set. Update the comment as well
___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 200 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVPN8m3e-fhcppHUOv:-OBVPN8m3e-fhcppHUOw:be0q2y5) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L200)):*
> ```XML
> 
>     // Create and send transactions.
>     let _expected_batched_tx_hashes =
> ```

No need to detail a variable name if you're not using it. Rename to _tx_hashes
___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 207 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVPal-0AZeuer8XEJm:-OBVPal-0AZeuer8XEJn:b2b775) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L207)):*
> ```XML
>         .await;
> 
>     assert!(!expected_txs.is_empty());
> ```

remove this assert
___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 214 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVQ-Kg6_b5YACgkk8u:-OBVQ-Kg6_b5YACgkk8v:b-mhe884) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L214)):*
> ```XML
>         let tx = broadcast_channels.broadcasted_messages_receiver.next().await.unwrap();
>         let rpc_transaction = tx.0.unwrap().0;
>         received_txs.push(rpc_transaction.clone());
> ```

You only use received_txs for its length. Change it to an integer

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1941)* status: all files reviewed, 11 unresolved discussions (waiting on @AlonLStarkWare)

___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVQKC3Cw665Im9VGn-:-OBVQKC3Cw665Im9VGn0:b-td3yg7) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L127)):*
> ```XML
> #[rstest]
> #[tokio::test]
> async fn test_mempool_sends_tx_to_other_peer(tx_generator: MultiAccountTransactionGenerator) {
> ```

Move this to a new file called mempool_p2p_flow_test

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1941)* status: all files reviewed, 9 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVQKC3Cw665Im9VGn-:-OBVhhTz5a3mtKjpK2ZO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L127)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move this to a new file called mempool_p2p_flow_test
</blockquote></details>

Done.
___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 128 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVOL_uCBdjKfjPxZlB:-OBVhi3X773VwHuf3Tow:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L128)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to remove code duplication with FlowTestSetup
</blockquote></details>

Done.
___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 155 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVOYH65IhUJNBASQDA:-OBVhmZmBUHhQyD15slZ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L155)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this TODO
</blockquote></details>

Done.
___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 163 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVOfoa6ILetcnhqsP9:-OBVhmy49HqsuEPvzdtY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L163)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Is this necessary? You're turning consensus off anyway
</blockquote></details>

Done.
___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 196 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVPn0f2dD7raa0WXgi:-OBVhoKQ5aYtaTlcdKv3:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L196)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

to the broadcasted transaction
</blockquote></details>

Done.
___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 197 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVPhZS4xj30uUSIqxb:-OBVhvcsE-K0UZgclDlj:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L197)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This should be a set. Update the comment as well
</blockquote></details>

Done.
___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 200 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVPN8m3e-fhcppHUOv:-OBVi4T1CS2Sem-wkN95:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L200)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

No need to detail a variable name if you're not using it. Rename to _tx_hashes
</blockquote></details>

Done.
___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 207 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVPal-0AZeuer8XEJm:-OBViaWi3eQZNrj9ppsI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L207)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

remove this assert
</blockquote></details>

Done.
___
*[`crates/tests_integration/tests/end_to_end_flow_test.rs` line 214 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OBVQ-Kg6_b5YACgkk8u:-OBVinPN7p17lCAhhUH1:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/142e6bb56ed79448c6356a897271d0fc70f84683/crates/tests_integration/tests/end_to_end_flow_test.rs#L214)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You only use received_txs for its length. Change it to an integer
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1941)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare)

___
*[`crates/starknet_integration_tests/tests/mempool_p2p_flow_test.rs` line 117 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OB_l45SC2lubFMja9lV:-OB_k_El54BR8DgSXbVQ:bjzao3g) ([raw file](https://github.com/starkware-libs/sequencer/blob/78c9861f652c380c8bc2f74bb2680c9416cb5c6a/crates/starknet_integration_tests/tests/mempool_p2p_flow_test.rs#L117)):*
> ```XML
>     .await;
> 
>     let mut received_txs_counter = 0;
> ```

This was a mistake because now the test doesn't check there are no duplicates
May I suggest instead to just erase tx from expected_txs after you check that it is contained inside it, and changing the for loop to a while loop while expected_txs is not empty?

**Review by AlonLStarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1941)* status: 6 of 13 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`crates/starknet_integration_tests/tests/mempool_p2p_flow_test.rs` line 117 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-OB_l45SC2lubFMja9lV:-OB_y1XT7d24gm6ZOt_g:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/78c9861f652c380c8bc2f74bb2680c9416cb5c6a/crates/starknet_integration_tests/tests/mempool_p2p_flow_test.rs#L117)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This was a mistake because now the test doesn't check there are no duplicates
May I suggest instead to just erase tx from expected_txs after you check that it is contained inside it, and changing the for loop to a while loop while expected_txs is not empty?
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1941#-:-OBdnzxxEj7JWDEOplEc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Pull request merged**
