### PR TITLE
refactor(consensus): add instrumentation when spawning tasks within consensus

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/221)

### CODE REVIEW

**Comment by matan-starkware** [comment]
* **#221** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/221?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/221#-:-O36wxEq6klkeSQz9gJf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/221#-O36we5I1YN5mihT9DLF:-O36we5I1YN5mihT9DLG:b5u8pf9) (no related file):*
Consider adding a consensus prefix. In addition, I advise you to run it and see if you get the span message where and when you want it.

___

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/221)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/221#-O36we5I1YN5mihT9DLF:-O37HWDK2-c1zJx4bMNv:b-etnk8j) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Consider adding a consensus prefix. In addition, I advise you to run it and see if you get the span message where and when you want it.
</blockquote></details>

good points.

___

**Comment by matan-starkware** [comment]
### Merge activity

* **Aug 1, 5:05 AM EDT**: @matan-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/221).

**Pull request merged**
