### PR TITLE
refactor(mempool): rearrange insert_tx before refactoring code

### PR DESCRIPTION
**Pull request by ayeletstarkware**
rearrange insert_tx func before refactoring code to share code functionality

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/470)

### CODE REVIEW

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/470)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/470#-O4LPdevD89BazYkIILR:-O4LPdevD89BazYkIILS:b-vir0ny) ([raw file](https://github.com/starkware-libs/sequencer/blob/724c44d0e15578221b7b0b75ee074ad1b2633d00/crates/mempool/src/mempool.rs#L136)):*
> ```XML
>         let MempoolInput { tx, account: Account { sender_address, state: AccountState { nonce } } } =
>             input;
> ```

Please add in the test a check on the queue.
___
*[`crates/mempool/src/mempool.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/470#-O4LQ1HW1EVO7MwFRvEt:-O4LQ1HW1EVO7MwFRvEu:bw3u8u5) ([raw file](https://github.com/starkware-libs/sequencer/blob/724c44d0e15578221b7b0b75ee074ad1b2633d00/crates/mempool/src/mempool.rs#L153)):*
> ```XML
>         }
> 
>         self.tx_pool.remove_up_to_nonce(sender_address, nonce);
> ```

why did you move it here? after updating the queue?



_Code quote:_
```XML
self.tx_pool.remove_up_to_nonce(sender_address, nonce);
```

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/470)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/470#-O4LQ1HW1EVO7MwFRvEt:-O4Z6o7F9i_ZFJI9MSQo:b-hft2pu) ([raw file](https://github.com/starkware-libs/sequencer/blob/724c44d0e15578221b7b0b75ee074ad1b2633d00/crates/mempool/src/mempool.rs#L153)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

why did you move it here? after updating the queue?
</blockquote></details>

Please explain why this is equivalent (the order doesn't matter); not sure I'm convinced.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/470)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/470#-O4LPdevD89BazYkIILR:-O4_EbyK1bELUEU5wH_3:b-9oymn0) ([raw file](https://github.com/starkware-libs/sequencer/blob/724c44d0e15578221b7b0b75ee074ad1b2633d00/crates/mempool/src/mempool.rs#L136)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please add in the test a check on the queue.
</blockquote></details>

added in #452
___
*[`crates/mempool/src/mempool.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/470#-O4LQ1HW1EVO7MwFRvEt:-O4_BFNp960VnoxVQZwW:b3lag7p) ([raw file](https://github.com/starkware-libs/sequencer/blob/724c44d0e15578221b7b0b75ee074ad1b2633d00/crates/mempool/src/mempool.rs#L153)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please explain why this is equivalent (the order doesn't matter); not sure I'm convinced.
</blockquote></details>

I moved it to align with the `commit_block` code. 
Why is this equivalent? Let’s break down the steps:
1.  We add the new transaction to the pool.
2.  We check if the new transaction has a higher account nonce than the one in the queue. If it does, we remove the queued transaction.
3.  We check if there’s a transaction in the pool with the current account nonce. If there is, we insert it into the queue.
4.  We remove transactions from the pool with lower nonces than the current account nonce.

In this PR, I made two changes by reordering the steps: 
* Previously, step 4 (removing older nonce transactions from the pool) was the first step. I believe the order doesn’t matter because none of the other steps will interact with pool transactions that have lower nonces than the current account nonce.
* The insertion of the pool transaction was originally between steps 2 and 3. I moved it to the first line. This change is safe because step 2 doesn’t modify the pool.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/470)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/470#-O4LQ1HW1EVO7MwFRvEt:-O4d3zIyAWpheJQDt5rp:b-2ih4vf) ([raw file](https://github.com/starkware-libs/sequencer/blob/724c44d0e15578221b7b0b75ee074ad1b2633d00/crates/mempool/src/mempool.rs#L153)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I moved it to align with the `commit_block` code. 
Why is this equivalent? Let’s break down the steps:
1.  We add the new transaction to the pool.
2.  We check if the new transaction has a higher account nonce than the one in the queue. If it does, we remove the queued transaction.
3.  We check if there’s a transaction in the pool with the current account nonce. If there is, we insert it into the queue.
4.  We remove transactions from the pool with lower nonces than the current account nonce.

In this PR, I made two changes by reordering the steps: 
* Previously, step 4 (removing older nonce transactions from the pool) was the first step. I believe the order doesn’t matter because none of the other steps will interact with pool transactions that have lower nonces than the current account nonce.
* The insertion of the pool transaction was originally between steps 2 and 3. I moved it to the first line. This change is safe because step 2 doesn’t modify the pool.
</blockquote></details>

Why not: maybe remove from queue, then from pool; then add to pool, maybe remove from queue.
This is a more logical story to tell.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/470)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/470#-O4LQ1HW1EVO7MwFRvEt:-O4dWhQ82iA9U3dZZhYZ:b-sebgg8) ([raw file](https://github.com/starkware-libs/sequencer/blob/724c44d0e15578221b7b0b75ee074ad1b2633d00/crates/mempool/src/mempool.rs#L153)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not: maybe remove from queue, then from pool; then add to pool, maybe remove from queue.
This is a more logical story to tell.
</blockquote></details>

I need the insertion to the pool to be the first or the last step since I'm extracting steps 2-4 to a function in #472. Anyway, can I change the order after extracting this logic to a function and use it in both `add_tx` and `commit_block`, so I won't have to change it in both?

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/470)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/470#-O4LQ1HW1EVO7MwFRvEt:-O4dZsbB-yYdDE6LstBz:b-25cd7z) ([raw file](https://github.com/starkware-libs/sequencer/blob/724c44d0e15578221b7b0b75ee074ad1b2633d00/crates/mempool/src/mempool.rs#L153)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I need the insertion to the pool to be the first or the last step since I'm extracting steps 2-4 to a function in #472. Anyway, can I change the order after extracting this logic to a function and use it in both `add_tx` and `commit_block`, so I won't have to change it in both?
</blockquote></details>

It can't be last, since it affects what you maybe insert to the queue. 
I'll reorder: maybe remove from queue, maybe remove from pool, add to pool, maybe add to queue.
When removing: you should first remove from the queue and then from pool; when inserting: you should first insert to pool, and then to queue. Perhaps we should separate removal and insertion.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/470#-:-O4emZhA2xyL6QJdD3nS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/470#-O4LQ1HW1EVO7MwFRvEt:-O4embMY-esZyWBouMv5:bxz8ao2) ([raw file](https://github.com/starkware-libs/sequencer/blob/724c44d0e15578221b7b0b75ee074ad1b2633d00/crates/mempool/src/mempool.rs#L153)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done. `commit_block` doesn’t insert into the pool, so this order doesn’t work if we want to share code. However, this is out of scope for this PR—let’s discuss it F2F.
</blockquote></details>

Note you haven't changed anything in the end.

**Review by MohammadNassar1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/470)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

**Review by MohammadNassar1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/470)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/470)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 91 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/470#-O4jq8ugA_mC0gXDllRi:-O4jq8ugA_mC0gXDllRj:bqf3xrr) ([raw file](https://github.com/starkware-libs/sequencer/blob/0a347a63ef232d995806b12877afe2236e4a0947/crates/mempool/src/mempool.rs#L91)):*
> ```XML
>             // Align the queue with the committed nonces.
> 
>             // Remove transactions with lower nonces from the queue and the pool.
> ```

Please update documentation of both segments of code with the one we agreed on in #472.



_Code quote:_
```XML
// Remove transactions with lower nonces from the queue and the pool.
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/470)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 128 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/470#-O4k-vUfCXczhTkUsCtU:-O4k-vUgCMIfOrnNjPom:b-bhwvq) ([raw file](https://github.com/starkware-libs/sequencer/blob/5e86960ccbe95e76d5abafa8178bdfe35c28fa98/crates/mempool/src/mempool.rs#L128)):*
> ```XML
> 
>         // Maybe remove out-of-date transactions.
>         // Note: != is actually equivalent to > here, as lower nonces are rejected in validation.
> ```

This should also appear in the new method; please be minded that you're not deleting documentation when moving code.



_Code quote:_
```XML
Note: != is actually equivalent to > here, as lower nonces are rejected in validation.
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/470)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 128 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/470#-O4k-vUfCXczhTkUsCtU:-O4k0fFt7jFEPixw18pS:bslbihl) ([raw file](https://github.com/starkware-libs/sequencer/blob/5e86960ccbe95e76d5abafa8178bdfe35c28fa98/crates/mempool/src/mempool.rs#L128)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This should also appear in the new method; please be minded that you're not deleting documentation when moving code.
</blockquote></details>

yes it's in the align function in #472

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/470)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 128 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/470#-O4k-vUfCXczhTkUsCtU:-O4k1G6Y9dYOQbNGzSR4:btojbfd) ([raw file](https://github.com/starkware-libs/sequencer/blob/5e86960ccbe95e76d5abafa8178bdfe35c28fa98/crates/mempool/src/mempool.rs#L128)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

yes it's in the align function in #472
</blockquote></details>

Great!

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/470)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
