### PR TITLE
chore(gateway): unify client implementations

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #2119
- #2115
- #2090
- #2089
- #2088 ⬅
- #2087
- #2086
- #2085

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by nadin-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2088)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_gateway_types/src/communication.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2088#-OBuHNQ8EnCQPXWBwMSf:-OBuHNQ9CbrIxe4JoeUo:b-wadyng) ([raw file](https://github.com/starkware-libs/sequencer/blob/259d98258b08db35d4f0ed05844538a043d77d86/crates/starknet_gateway_types/src/communication.rs#L58)):*
> ```XML
> 
> #[async_trait]
> impl<T> GatewayClient for T
> ```

Please replace T with a more descriptive name.



_Code quote:_
```XML
T
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2088)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/starknet_gateway_types/src/communication.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2088#-OBuHNQ8EnCQPXWBwMSf:-OBuSwIQ9eLE4D00tRHn:b-d3xf9y) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e26682d5c5c198d3ed2737b36950355e88c6d4f/crates/starknet_gateway_types/src/communication.rs#L58)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Please replace T with a more descriptive name.
</blockquote></details>

Single pr at the end

**Review by nadin-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2088)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#2119](https://github.com/starkware-libs/sequencer/pull/2119)

**Pull request closed without merging**
