### PR TITLE
feat(blockifier): get sierra contract class from feature contract

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
* **#2466** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2466?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2466?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2466)* status: all files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`crates/starknet_api/src/state.rs` line 250 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2466#-ODLKVMV7IyupR6v05u9:-ODLKVMV7IyupR6v05uA:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7045fbb2c682d60bfedcda2391616ff69973e5a2/crates/starknet_api/src/state.rs#L250)):*
> ```XML
>                     None => Default::default(),
>                 }
>             },
> ```





_Suggestion:_
```XML
            abi: cairo_lang_contract_class.abi.map(|abi| abi.json()).unwrap_or_default(),
```
___
*[`crates/starknet_api/src/state.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2466#-ODLKc5B9ybuMZdQ1XCp:-ODLKc5B9ybuMZdQ1XCq:b-46gcqi) ([raw file](https://github.com/starkware-libs/sequencer/blob/7045fbb2c682d60bfedcda2391616ff69973e5a2/crates/starknet_api/src/state.rs#L253)):*
> ```XML
>         }
>     }
> }
> ```

@Yoni-Starkware this conversion includes O(len(sierra_program)) Felt::from(biguint) operations...
how bad is it?
@AvivYossef-starkware how many times is this conversion invoked? is it cached?



_Code quote:_
```XML
impl From<CairoLangContractClass> for SierraContractClass {
    fn from(cairo_lang_contract_class: CairoLangContractClass) -> Self {
        Self {
            sierra_program: cairo_lang_contract_class
                .sierra_program
                .into_iter()
                .map(|big_uint_as_hex| Felt::from(big_uint_as_hex.value))
                .collect(),
            contract_class_version: cairo_lang_contract_class.contract_class_version,
            entry_points_by_type: cairo_lang_contract_class.entry_points_by_type.into(),
            abi: {
                match cairo_lang_contract_class.abi {
                    Some(abi) => abi.json(),
                    None => Default::default(),
                }
            },
        }
    }
}
```
___
*[`crates/starknet_api/src/rpc_transaction.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2466#-ODLJiaQDP0mEqB4LvLS:-ODLJiaQDP0mEqB4LvLT:bkwksdo) ([raw file](https://github.com/starkware-libs/sequencer/blob/7045fbb2c682d60bfedcda2391616ff69973e5a2/crates/starknet_api/src/rpc_transaction.rs#L7)):*
> ```XML
> use std::collections::HashMap;
> 
> use cairo_lang_starknet_classes::contract_class::ContractEntryPoints as CairoLangContractEntryPoints;
> ```

why rename? I don't see a name collision



_Suggestion:_
```XML
ContractEntryPoints;
```
___
*[`crates/starknet_api/src/rpc_transaction.rs` line 287 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2466#-ODLK0eX11ITq9ckVpX3:-ODLK0eX11ITq9ckVpX4:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/7045fbb2c682d60bfedcda2391616ff69973e5a2/crates/starknet_api/src/rpc_transaction.rs#L287)):*
> ```XML
> 
> // TODO(AVIV): Consider removing this conversion and using the one in the
> // CairoLangContractEntryPoints
> ```





_Suggestion:_
```XML
// TODO(AVIV): Consider removing this conversion and using ContractEntryPoints instead of
//   defining the EntryPointByType struct.
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2466)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/starknet_api/src/state.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2466#-ODLKc5B9ybuMZdQ1XCp:-ODLq1TS1Qdh4V-WysO5:b-9g18nq) ([raw file](https://github.com/starkware-libs/sequencer/blob/7045fbb2c682d60bfedcda2391616ff69973e5a2/crates/starknet_api/src/state.rs#L253)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Currently, I only use it once for each feature contract in the end-to-end test.
</blockquote></details>

this is not used in business logic? then please gate it behind #[cfg(any(test, feature = "testing"))]

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2466)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`crates/starknet_api/src/state.rs` line 253 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2466#-ODLKc5B9ybuMZdQ1XCp:-ODLsiIiC1uLoIvJsrHL:b32w12) ([raw file](https://github.com/starkware-libs/sequencer/blob/7045fbb2c682d60bfedcda2391616ff69973e5a2/crates/starknet_api/src/state.rs#L253)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is not used in business logic? then please gate it behind #[cfg(any(test, feature = "testing"))]
</blockquote></details>

No

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2466#-:-ODLvfYr9nSQvpttc7TN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2466)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2466)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Comment by AvivYossef-starkware** [comment]
### Merge activity

* **Dec 8, 4:35 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2466).

**Pull request merged**
