### PR TITLE
build: blockifier regression test compile class

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/980)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/980?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#980** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/980?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#956** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/956?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#943](https://github.com/starkware-libs/sequencer/pull/943) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/943?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#952** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/952?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#948** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/948?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#946** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/946?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#945** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/945?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by aner-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/980)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7cDyG_69nIMBDPksm8:-O7cDyG_69nIMBDPksm9:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/51209162597ca5a9738df0b093553d743c839ee6/crates/blockifier_regression_test/src/test_state_reader.rs#L48)):*
> ```XML
>     fn get_compiled_contract_class(
>         &self,
>         class_hash: starknet_api::core::ClassHash,
> ```





_Suggestion:_
```XML
class_hash: ClassHash
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7cEFSd0w725Ro0lM2q:-O7cEFSd0w725Ro0lM2r:b-uw6mq) ([raw file](https://github.com/starkware-libs/sequencer/blob/51209162597ca5a9738df0b093553d743c839ee6/crates/blockifier_regression_test/src/test_state_reader.rs#L56)):*
> ```XML
>             starknet_core::types::ContractClass::Legacy(legacy) => {
>                 legacy_to_contract_class_v0(legacy)
>             }
> ```

Add `use ...` in the beginning of the file.



_Suggestion:_
```XML
            Sierra(sierra) => sierra_to_contact_class_v1(sierra)
            Legacy(legacy) => legacy_to_contract_class_v0(legacy)
            
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7cHYCKEaUcZeIi8D_1:-O7cHYCKEaUcZeIi8D_2:b-r8lhcj) ([raw file](https://github.com/starkware-libs/sequencer/blob/51209162597ca5a9738df0b093553d743c839ee6/crates/blockifier_regression_test/src/test_state_reader.rs#L103)):*
> ```XML
>         "class_hash": class_hash.0.to_string(),
>         });
>         let contract_class: starknet_core::types::ContractClass =
> ```

I think it's not needed.
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7cDGs97rThtazgeNts:-O7cDGs97rThtazgeNtt:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/51209162597ca5a9738df0b093553d743c839ee6/crates/blockifier_regression_test/src/test_state_reader.rs#L166)):*
> ```XML
> 
>     #[rstest]
>     #[ignore = "This test using http request, so it should not be run in CI"]
> ```





_Suggestion:_
```XML
This test uses an HTTP request, so it should not be run in CI.
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7cD1deBSvYw7GE0kZa:-O7cD1deBSvYw7GE0kZb:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/51209162597ca5a9738df0b093553d743c839ee6/crates/blockifier_regression_test/src/test_state_reader.rs#L172)):*
> ```XML
> 
>     #[rstest]
>     #[ignore = "This test using http request, so it should not be run in CI"]
> ```





_Suggestion:_
```XML
This test uses an HTTP request, so it should not be run in CI.
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7cCWpy7RanmFpfKndz:-O7cCWpy7RanmFpfKne-:ba1owac) ([raw file](https://github.com/starkware-libs/sequencer/blob/51209162597ca5a9738df0b093553d743c839ee6/crates/blockifier_regression_test/src/test_state_reader.rs#L176)):*
> ```XML
>         let class_hash =
>             class_hash!("0x3131fa018d520a037686ce3efddeab8f28895662f019ca3ca18a626650f7d1e");
>         test_state_reader.get_contract_class(&class_hash).unwrap();
> ```

Is this asserting that the operation succeeded? Consider adding a message.



_Suggestion:_
```XML
.expect("...");
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7cHhIK0grarlq3si3c:-O7cHhIK0grarlq3si3d:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/51209162597ca5a9738df0b093553d743c839ee6/crates/blockifier_regression_test/src/test_state_reader.rs#L180)):*
> ```XML
> 
>     #[rstest]
>     #[ignore = "This test using http request, so it should not be run in CI"]
> ```





_Suggestion:_
```XML
This test uses an HTTP request, so it should not be run in CI.
```
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 184 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7cCnhr7TcvkhEGumb6:-O7cCnhr7TcvkhEGumb7:b-q64pkt) ([raw file](https://github.com/starkware-libs/sequencer/blob/51209162597ca5a9738df0b093553d743c839ee6/crates/blockifier_regression_test/src/test_state_reader.rs#L184)):*
> ```XML
>         let class_hash =
>             class_hash!("0x3131fa018d520a037686ce3efddeab8f28895662f019ca3ca18a626650f7d1e");
>         test_state_reader.get_compiled_contract_class(class_hash).unwrap();
> ```

See above.



_Suggestion:_
```XML
.expect("...")
```

**Review by aner-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/980)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7cDGs97rThtazgeNts:-O7macEv1X3gMpWPRkPU:b-rwvlnk) ([raw file](https://github.com/starkware-libs/sequencer/blob/51209162597ca5a9738df0b093553d743c839ee6/crates/blockifier_regression_test/src/test_state_reader.rs#L166)):*
> ```XML
> 
>     #[rstest]
>     #[ignore = "This test using http request, so it should not be run in CI"]
> ```

This one wasn't changed. I'm retracting to unblock.
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7cCWpy7RanmFpfKndz:-O7mao4o4sFJ4FFp4n1u:b-l8nh8r) ([raw file](https://github.com/starkware-libs/sequencer/blob/51209162597ca5a9738df0b093553d743c839ee6/crates/blockifier_regression_test/src/test_state_reader.rs#L176)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Is this asserting that the operation succeeded? Consider adding a message.
</blockquote></details>

Why not use use `expect`? It does the same thing.

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/980)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @aner-starkware)

___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7cDyG_69nIMBDPksm8:-O7cIW9MA2ci1YvnpQIC:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/51209162597ca5a9738df0b093553d743c839ee6/crates/blockifier_regression_test/src/test_state_reader.rs#L48)):*
> ```XML
>     fn get_compiled_contract_class(
>         &self,
>         class_hash: starknet_api::core::ClassHash,
> ```

Done.
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7cEFSd0w725Ro0lM2q:-O7cIpaX13LAKJWttOKH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/51209162597ca5a9738df0b093553d743c839ee6/crates/blockifier_regression_test/src/test_state_reader.rs#L56)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Add `use ...` in the beginning of the file.
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7cHYCKEaUcZeIi8D_1:-O7cJ9Ro9nPb4ZQS070j:b-f7z68q) ([raw file](https://github.com/starkware-libs/sequencer/blob/51209162597ca5a9738df0b093553d743c839ee6/crates/blockifier_regression_test/src/test_state_reader.rs#L103)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I think it's not needed.
</blockquote></details>

What not needed?
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7cDGs97rThtazgeNts:-O7cJRZF0jiM3JbT1wS-:b-pi0xrj) ([raw file](https://github.com/starkware-libs/sequencer/blob/51209162597ca5a9738df0b093553d743c839ee6/crates/blockifier_regression_test/src/test_state_reader.rs#L166)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

This one wasn't changed. I'm retracting to unblock.
</blockquote></details>

Not relevant 
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7cD1deBSvYw7GE0kZa:-O7cL8OUDFySw2X-1eZt:bwbelgx) ([raw file](https://github.com/starkware-libs/sequencer/blob/51209162597ca5a9738df0b093553d743c839ee6/crates/blockifier_regression_test/src/test_state_reader.rs#L172)):*
> ```XML
> 
>     #[rstest]
>     #[ignore = "This test using http request, so it should not be run in CI"]
> ```

not relevant 
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7cCWpy7RanmFpfKndz:-O7cL6fT84IGX49AVV1Y:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/51209162597ca5a9738df0b093553d743c839ee6/crates/blockifier_regression_test/src/test_state_reader.rs#L176)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Is this asserting that the operation succeeded? Consider adding a message.
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7cHhIK0grarlq3si3c:-O7wycBO7hHfDg5CM57q:b-pi0xrj) ([raw file](https://github.com/starkware-libs/sequencer/blob/51209162597ca5a9738df0b093553d743c839ee6/crates/blockifier_regression_test/src/test_state_reader.rs#L180)):*
> ```XML
> 
>     #[rstest]
>     #[ignore = "This test using http request, so it should not be run in CI"]
> ```

Not relevant 
___
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 184 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7cCnhr7TcvkhEGumb6:-O7cLGjJ26JS_LFjEpQo:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/51209162597ca5a9738df0b093553d743c839ee6/crates/blockifier_regression_test/src/test_state_reader.rs#L184)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.

**Comment by aner-starkware** [comment]
*[`crates/blockifier_regression_test/src/test_state_reader.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7cHYCKEaUcZeIi8D_1:-O7xx9Ln0cDEgvgfDDpp:bthoncr) ([raw file](https://github.com/starkware-libs/sequencer/blob/51209162597ca5a9738df0b093553d743c839ee6/crates/blockifier_regression_test/src/test_state_reader.rs#L103)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

What not needed?
</blockquote></details>

What you removed (you can look at the suggestion to understand what I was talking about).

**Review by aner-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/980)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier_regression_test/src/state_reader/compile.rs` line 68 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7y-S7887U8NgyIxkwV:-O7y-S7887U8NgyIxkwW:b-twhzpy) ([raw file](https://github.com/starkware-libs/sequencer/blob/8980aa64e173279621d8ec4cc8788c1fd87ca96e/crates/blockifier_regression_test/src/state_reader/compile.rs#L68)):*
> ```XML
> }
> 
> pub fn sierra_to_contact_class_v1(sierra: FlattenedSierraClass) -> StateResult<ContractClass> {
> ```

Docstring.



_Code quote:_
```XML
pub fn sierra_to_contact_class_v1(sierra: FlattenedSierraClass) -> StateResult<ContractClass>
```
___
*[`crates/blockifier_regression_test/src/state_reader/compile.rs` line 91 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7y-V4s3mysucjTzGgf:-O7y-V4s3mysucjTzGgg:b-twhzpy) ([raw file](https://github.com/starkware-libs/sequencer/blob/8980aa64e173279621d8ec4cc8788c1fd87ca96e/crates/blockifier_regression_test/src/state_reader/compile.rs#L91)):*
> ```XML
> }
> 
> pub fn legacy_to_contract_class_v0(
> ```

Docstring.



_Code quote:_
```XML
pub fn legacy_to_contract_class_v0
```
___
*[`crates/blockifier_regression_test/src/state_reader/test_state_reader.rs` line 93 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7xz_hN8lNaIUYiQH6X:-O7xz_hN8lNaIUYiQH6Y:b-hi2reg) ([raw file](https://github.com/starkware-libs/sequencer/blob/8980aa64e173279621d8ec4cc8788c1fd87ca96e/crates/blockifier_regression_test/src/state_reader/test_state_reader.rs#L93)):*
> ```XML
>         "class_hash": class_hash.0.to_string(),
>         });
>         let contract_class: starknet_core::types::ContractClass =
> ```

it's not needed.

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/980)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier_regression_test/src/state_reader/compile.rs` line 91 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7y-V4s3mysucjTzGgf:-O81m-GrAw_K21OwFAz2:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8980aa64e173279621d8ec4cc8788c1fd87ca96e/crates/blockifier_regression_test/src/state_reader/compile.rs#L91)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Docstring.
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/980)* status: 9 of 11 files reviewed, 8 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_regression_test/src/json_test.rs` line 42 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O82GAPYERufmH_J6EvR:-O82GAPYERufmH_J6EvS:bf7zsny) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e7fbf0b6912ea6ca60141315e3ba5ae551b1795/crates/blockifier_regression_test/src/json_test.rs#L42)):*
> ```XML
> pub fn deserialize_deprecated_contract_class(deprecated_contract_class: ContractClass) {
>     assert_matches!(deprecated_contract_class, ContractClass::Legacy(..));
> }
> ```

1. this test is redundant - `test_compile_deprecated_contract_class` already panics if this isn't a `Legacy` variant
2. no need for `pub` in a test function



_Code quote:_
```XML
pub fn deserialize_deprecated_contract_class(deprecated_contract_class: ContractClass) {
    assert_matches!(deprecated_contract_class, ContractClass::Legacy(..));
}
```
___
*[`crates/blockifier_regression_test/src/state_reader/rpc_test.rs` line 43 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O82GpoUAVo3eN8eOvc8:-O82GpoUAVo3eN8eOvc9:b-nuu6nj) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e7fbf0b6912ea6ca60141315e3ba5ae551b1795/crates/blockifier_regression_test/src/state_reader/rpc_test.rs#L43)):*
> ```XML
>         panic!("Error retrieving contract class for class hash {}: {}", class_hash, err);
>     });
> }
> ```

it is unclear from the body of this test why the class should exist - what is special about this class hash?
please add a message to the `expect` about it



_Code quote:_
```XML
#[rstest]
pub fn test_get_contract_class(test_state_reader: TestStateReader) {
    let class_hash =
        class_hash!("0x3131fa018d520a037686ce3efddeab8f28895662f019ca3ca18a626650f7d1e");
    test_state_reader.get_contract_class(&class_hash).unwrap_or_else(|err| {
        panic!("Error retrieving contract class for class hash {}: {}", class_hash, err);
    });
}
```
___
*[`crates/blockifier_regression_test/src/state_reader/rpc_test.rs` line 48 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O82H48C2hcRi2L78hkQ:-O82H48C2hcRi2L78hkR:b9trr) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e7fbf0b6912ea6ca60141315e3ba5ae551b1795/crates/blockifier_regression_test/src/state_reader/rpc_test.rs#L48)):*
> ```XML
> pub fn test_get_compiled_contract_class(test_state_reader: TestStateReader) {
>     let class_hash =
>         class_hash!("0x3131fa018d520a037686ce3efddeab8f28895662f019ca3ca18a626650f7d1e");
> ```

this is a special class hash...? or just the class hash of an example contract fetched via RPC?



_Code quote:_
```XML
"0x3131fa018d520a037686ce3efddeab8f28895662f019ca3ca18a626650f7d1e"
```
___
*[`crates/blockifier_regression_test/src/state_reader/rpc_test.rs` line 52 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O82GznCB_pcHmV_tjqj:-O82GznCB_pcHmV_tjqk:bcolc42) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e7fbf0b6912ea6ca60141315e3ba5ae551b1795/crates/blockifier_regression_test/src/state_reader/rpc_test.rs#L52)):*
> ```XML
>         panic!("Error retrieving compiled contract class for class hash {}: {}", class_hash, err);
>     });
> }
> ```

please combine this test with the above test - they test similar aspects of the state.



_Code quote:_
```XML
#[rstest]
pub fn test_get_compiled_contract_class(test_state_reader: TestStateReader) {
    let class_hash =
        class_hash!("0x3131fa018d520a037686ce3efddeab8f28895662f019ca3ca18a626650f7d1e");
    test_state_reader.get_compiled_contract_class(class_hash).unwrap_or_else(|err| {
        panic!("Error retrieving compiled contract class for class hash {}: {}", class_hash, err);
    });
}
```
___
*[`crates/blockifier_regression_test/src/state_reader/test_state_reader.rs` line 114 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O82HOgG-0n6clvyDMwR:-O82HOgG-0n6clvyDMwS:bv9xxix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e7fbf0b6912ea6ca60141315e3ba5ae551b1795/crates/blockifier_regression_test/src/state_reader/test_state_reader.rs#L114)):*
> ```XML
>         let params = json!({
>         "block_id": self.0.block_id,
>         "class_hash": class_hash.0.to_string(),
> ```

indent please



_Suggestion:_
```XML
            "block_id": self.0.block_id,
            "class_hash": class_hash.0.to_string(),
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/980)* status: 6 of 11 files reviewed, 8 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_regression_test/src/json_test.rs` line 42 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O82GAPYERufmH_J6EvR:-O85nPAt6TUn0c_0FcKT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e7fbf0b6912ea6ca60141315e3ba5ae551b1795/crates/blockifier_regression_test/src/json_test.rs#L42)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. this test is redundant - `test_compile_deprecated_contract_class` already panics if this isn't a `Legacy` variant
2. no need for `pub` in a test function
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/state_reader/rpc_test.rs` line 43 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O82GpoUAVo3eN8eOvc8:-O85psar01-Li4nL0Kr1:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e7fbf0b6912ea6ca60141315e3ba5ae551b1795/crates/blockifier_regression_test/src/state_reader/rpc_test.rs#L43)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

it is unclear from the body of this test why the class should exist - what is special about this class hash?
please add a message to the `expect` about it
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/state_reader/rpc_test.rs` line 48 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O82H48C2hcRi2L78hkQ:-O85pxYZ4Sq1GCwgZ334:b-oumnpi) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e7fbf0b6912ea6ca60141315e3ba5ae551b1795/crates/blockifier_regression_test/src/state_reader/rpc_test.rs#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is a special class hash...? or just the class hash of an example contract fetched via RPC?
</blockquote></details>

Just an example 
___
*[`crates/blockifier_regression_test/src/state_reader/rpc_test.rs` line 52 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O82GznCB_pcHmV_tjqj:-O85qDip3HAU9hGpo1Rd:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e7fbf0b6912ea6ca60141315e3ba5ae551b1795/crates/blockifier_regression_test/src/state_reader/rpc_test.rs#L52)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please combine this test with the above test - they test similar aspects of the state.
</blockquote></details>

Done
___
*[`crates/blockifier_regression_test/src/state_reader/compile.rs` line 68 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7y-S7887U8NgyIxkwV:-O85tmIED-zxWMAP3nyL:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8980aa64e173279621d8ec4cc8788c1fd87ca96e/crates/blockifier_regression_test/src/state_reader/compile.rs#L68)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Docstring.
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/state_reader/test_state_reader.rs` line 93 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O7xz_hN8lNaIUYiQH6X:-O85tVG31oSlcGxdHASj:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8980aa64e173279621d8ec4cc8788c1fd87ca96e/crates/blockifier_regression_test/src/state_reader/test_state_reader.rs#L93)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

it's not needed.
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/state_reader/test_state_reader.rs` line 114 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O82HOgG-0n6clvyDMwR:-O85t7sB3tRXeHC7W8gM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/3e7fbf0b6912ea6ca60141315e3ba5ae551b1795/crates/blockifier_regression_test/src/state_reader/test_state_reader.rs#L114)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

indent please
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/980)* status: all files reviewed, 5 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_regression_test/src/state_reader/compile.rs` line 0 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O85vPNZ3yCS86-kYIQN:-O85vPNZ3yCS86-kYIQO:b-1tzxsq) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3965e38746731fe306877dcaa1acac5323dcd7a/crates/blockifier_regression_test/src/state_reader/compile.rs#L0)):*
please add a comment at the top of this module, that it contains code taken from starknet-replay, and provide a link
___
*[`crates/blockifier_regression_test/src/state_reader/test_state_reader.rs` line 26 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O85vmPQ7VrckzHz42Pz:-O85vmPQ7VrckzHz42Q-:bhzmgk6) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3965e38746731fe306877dcaa1acac5323dcd7a/crates/blockifier_regression_test/src/state_reader/test_state_reader.rs#L26)):*
> ```XML
> use crate::state_reader::utils::{get_chain_info, get_rpc_state_reader_config};
> 
> pub struct TestStateReader(pub RpcStateReader);
> ```

why `pub`? is it necessary?



_Code quote:_
```XML
pub 
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/980)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_regression_test/src/state_reader/compile.rs` line  at r8](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O85vPNZ3yCS86-kYIQN:-O860vu9CsUcJq-CUeug:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3965e38746731fe306877dcaa1acac5323dcd7a/crates/blockifier_regression_test/src/state_reader/compile.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a comment at the top of this module, that it contains code taken from starknet-replay, and provide a link
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/state_reader/test_state_reader.rs` line 26 at r8](https://reviewable.io/reviews/starkware-libs/sequencer/980#-O85vmPQ7VrckzHz42Pz:-O86-g7e9-91XEiL33k1:b-pqnr24) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3965e38746731fe306877dcaa1acac5323dcd7a/crates/blockifier_regression_test/src/state_reader/test_state_reader.rs#L26)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why `pub`? is it necessary?
</blockquote></details>

I tried to access the block number  but it requires more changes in the gateway code, so I passed

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/980#-:-O861wfi4vAyWrJs5xXj:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware)

**Review by aner-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/980)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
