### PR TITLE
feat(consensus): handle proposals from different rounds by context

### PR DESCRIPTION
**Pull request by asmaastarkware**

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2178)* status: all files reviewed, 16 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 200 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC9kddU0Jx5tWHgk_eK:-OC9kddU0Jx5tWHgk_eL:b7ha1vg) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L200)):*
> ```XML
> 
> #[tokio::test]
> async fn proposals_from_different_rounds() {
> ```

This is a good test for what we do with receiving proposals. Let's add another one to show interrupts:

1. Validate(current round) - not completed
2. Validate(next round)
3. SetRound(next round) -> interrupt and handling the next proposal



_Code quote:_
```XML
#[tokio::test]
async fn proposals_from_different_rounds() {
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 219 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC9iDPR-yuwuKk5x1sq:-OC9iDPR-yuwuKk5x1sr:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L219)):*
> ```XML
>                 panic!("Expected SendProposalContent::Txs, got {:?}", input.content);
>             };
>             assert_eq!(txs, TX_BATCH.clone());
> ```





_Suggestion:_
```XML
            assert_eq!(txs, *TX_BATCH);
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 224 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC9jWb267gRIt2qWD8y:-OC9jWb267gRIt2qWD8z:bmw3w40) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L224)):*
> ```XML
>     );
>     let proposal_id_clone = Arc::clone(&proposal_id);
>     batcher.expect_send_proposal_content().times(1).returning(
> ```

Can you look into/ask around if anyone has figured out a way to set expectations during the test. This need to set expectations before you actually run things makes it much harder to understand what triggers lower down lead to which expectation here.



_Code quote:_
```XML
    batcher.expect_send_proposal_content().times(1).returning(
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 247 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC9k94yCpTCkkI2ohWA:-OC9k94yCpTCkkI2ohWB:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L247)):*
> ```XML
>     let fin_receiver_past_round =
>         context.validate_proposal(BlockNumber(0), 0, TIMEOUT, content_receiver_0).await;
>     content_sender.close_channel();
> ```





_Suggestion:_
```XML
    // The proposal from the past round is ignored.
    let (mut content_sender, content_receiver_0) = mpsc::channel(CHANNEL_SIZE);
    content_sender.send(TX_BATCH.clone()).await.unwrap();
    let fin_receiver_past_round =
        context.validate_proposal(BlockNumber(0), 0, TIMEOUT, content_receiver_0).await;
    content_sender.close_channel();
    assert!(fin_receiver_past_round.await.is_err());
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 253 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC9kSbG6GPrM2svX6aS:-OC9kSbG6GPrM2svX6aT:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L253)):*
> ```XML
>     let fin_receiver_curr_round =
>         context.validate_proposal(BlockNumber(0), 1, TIMEOUT, content_receiver_1).await;
>     content_sender.close_channel();
> ```





_Suggestion:_
```XML
    // The proposal from the current round should be validated.
    let (mut content_sender, content_receiver_1) = mpsc::channel(CHANNEL_SIZE);
    content_sender.send(TX_BATCH.clone()).await.unwrap();
    let fin_receiver_curr_round =
        context.validate_proposal(BlockNumber(0), 1, TIMEOUT, content_receiver_1).await;
    content_sender.close_channel();
    assert_eq!(fin_receiver_curr_round.await.unwrap().0, STATE_DIFF_COMMITMENT.0.0);
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 259 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC9kZRU3ROzRlHdBmZe:-OC9kZRU3ROzRlHdBmZf:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L259)):*
> ```XML
>     let fin_receiver_future_round =
>         context.validate_proposal(BlockNumber(0), 2, TIMEOUT, content_receiver).await;
>     content_sender.close_channel();
> ```





_Suggestion:_
```XML
    // The proposal from the future round should not be processed.
    let (mut content_sender, content_receiver) = mpsc::channel(CHANNEL_SIZE);
    content_sender.send(TX_BATCH.clone()).await.unwrap();
    let fin_receiver_future_round =
        context.validate_proposal(BlockNumber(0), 2, TIMEOUT, content_receiver).await;
    content_sender.close_channel();
    assert!(fin_receiver_future_round.now_or_never().is_none());
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 266 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC9kaSC5Y0Bq2ItZjmD:-OC9kaSC5Y0Bq2ItZjmE:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L266)):*
> ```XML
>     assert_eq!(fin_receiver_curr_round.await.unwrap().0, STATE_DIFF_COMMITMENT.0.0);
>     // The proposal from the future round should not be processed.
>     assert!(fin_receiver_future_round.now_or_never().is_none());
> ```


___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 127 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC91slz3_k_-92JzD-v:-OC91slz3_k_-92JzD-w:bvpokcc) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L127)):*
> ```XML
>                 let proposal_id = match id_built_from_content_receiver.await {
>                     Ok(proposal_id) => Some(proposal_id),
>                     // Proposal never received from peer, or proposal was interrupted.
> ```

An invalid proposal can cause this



_Code quote:_
```XML
                    // Proposal never received from peer, or proposal was interrupted.
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 139 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC91Hh1-SXqZR4jDue-:-OC91Hh1-SXqZR4jDue0:brxerid) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L139)):*
> ```XML
>                 // never interrupted. Allowing interruptions would require exposing interrupts
>                 // to consensus, enabling it to distinguish between an interrupt and an actual
>                 // failure.
> ```

I'm not sure what this means. If there is a cancellation, I expect both proposal_id to be None, just like if there was an invalid proposal that failed validations. Did you mean to add a TODO: Differentiate between invalid proposal and interrupt?



_Code quote:_
```XML
                // Avoid voting NIL due to an interrupt, as this does not indicate a failure of the
                // Proposal itself. To prevent this, we ensure the current round's proposal is
                // never interrupted. Allowing interruptions would require exposing interrupts
                // to consensus, enabling it to distinguish between an interrupt and an actual
                // failure.
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 200 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC98hSA7jyC0yQtKDWC:-OC98hSA7jyC0yQtKDWD:byh5qf8) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L200)):*
> ```XML
>         let events = self.state_machine.start(&leader_fn);
>         let ret = self.handle_state_machine_events(context, events).await;
>         context.set_height_and_round(self.height, self.state_machine.round()).await;
> ```

Given that we call this function upon `start`, Should we just move `maybe_start_height` to `set_height_and_round` and not call it from the proposal functions?



_Suggestion:_
```XML
        context.set_height_and_round(self.height, 0).await;
        let events = self.state_machine.start(&leader_fn);
        let ret = self.handle_state_machine_events(context, events).await;
        context.set_height_and_round(self.height, self.state_machine.round()).await;
```
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC9d1AdEVaiGJHZH9JX:-OC9d1AdEVaiGJHZH9JY:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus/src/types.rs#L108)):*
> ```XML
> 
>     /// Update the context with the current height and round.
>     async fn set_height_and_round(&mut self, height: BlockNumber, round: Round);
> ```





_Suggestion:_
```XML
    /// Update the context with the current height and round.
    /// Must be called at the beginning of each height.
    async fn set_height_and_round(&mut self, height: BlockNumber, round: Round);
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC9AhjMBCszZYkwybhJ:-OC9AhjMBCszZYkwybhK:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L69)):*
> ```XML
>     proposal_id: u64,
>     current_height: Option<BlockNumber>,
>     current_consensus_height: BlockNumber,
> ```





_Suggestion:_
```XML
    current_height: BlockNumber,
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC9BMMY5a4eMUF-5Yag:-OC9BMMY5a4eMUF-5Yah:bzi61rj) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L108)):*
> ```XML
>         timeout: Duration,
>     ) -> oneshot::Receiver<ProposalContentId> {
>         self.set_height_and_round(proposal_init.height, proposal_init.round).await;
> ```

I don't see where you set the build as the active proposal. On one hand a build shouldn't be interrupted. On the other hand it feels odd not to recognize it as the active proposal. There is no bug as things stand, but I want to mention potential changes that could create an issue:
1. Consensus doesn't wait for GetProposal - if we change this to allow consensus to stop waiting in the case that timeoutPropose passes, then it would be possible for the build task to still be running when we move into another round and then we would try to validate with the batcher in parallel to building.
2. Future validations - if we allow for validating proposals not just from the current round then we could end up in a similar situation.

These are changes that we don't expect to make anytime soon, but I think it's important at least to state clearly that we don't track the build as the active proposal because:
1. Consensus cannot progress rounds until this task completes
2. Context only works on proposals for the current round



_Suggestion:_
```XML
        // Handles interrupting an active proposal from a previous height/round
        self.set_height_and_round(proposal_init.height, proposal_init.round).await;
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 246 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC9dLUx1lZGXsGGJ7te:-OC9dLUx1lZGXsGGJ7tf:b2cstf4) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L246)):*
> ```XML
>             self.queued_proposals.clear();
>             self.active_proposal = None;
>             return;
> ```

This block assumes that this function is called before any proposal attempts. I believe the current implementation you have may call to `build_proposal` of a new height (shc.start) before calling to `set_height_and_round`. I think my suggestion there also happens to solve this issue.



_Code quote:_
```XML
            self.current_consensus_height = height;
            assert_eq!(round, 0);
            self.current_round = round;
            self.interrupt_active_proposal();
            self.queued_proposals.clear();
            self.active_proposal = None;
            return;
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 260 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC9e2qcCzqjIgHRikuC:-OC9e2qcCzqjIgHRikuD:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L260)):*
> ```XML
>                 std::cmp::Ordering::Less => {
>                     entry.remove();
>                 }
> ```





_Suggestion:_
```XML
                std::cmp::Ordering::Less => entry.remove(),
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 339 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC9fObn2bg7anFNVrK0:-OC9fObn2bg7anFNVrK1:bop7zdy) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L339)):*
> ```XML
>                         }
>                     }
>                 }
> ```

In another PR we should explicitly tell the batcher that we aborted. this should happen either due to interrupt or timeout.



_Code quote:_
```XML
                    _ = notify_clone.notified() => {}
                    result = tokio::time::timeout(timeout, validate_fut) =>{
                        if let Err(e) = result {
                            error!("Validation timed out. {e:?}");
                        }
                    }
                }
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2178)* status: all files reviewed, 10 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 139 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC91Hh1-SXqZR4jDue-:-OCbwiZl9xL2qbcakBsC:bnzhvaq) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L139)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I'm not sure what this means. If there is a cancellation, I expect both proposal_id to be None, just like if there was an invalid proposal that failed validations. Did you mean to add a TODO: Differentiate between invalid proposal and interrupt?
</blockquote></details>

I think we should remove this. If you want something then put it above `proposal_id` and something like "Consider if we want to differentiate between an interrupt and other failures."
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 339 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC9fObn2bg7anFNVrK0:-OCbxvTY6IRNP7Qm0fdm:bqlsnco) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L339)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

In another PR we should explicitly tell the batcher that we aborted. this should happen either due to interrupt or timeout.
</blockquote></details>

Please ack
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 281 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OCbySZO8Aa2byB3IP8G:-OCbySZO8Aa2byB3IP8H:bf1q52f) ([raw file](https://github.com/starkware-libs/sequencer/blob/6338aa88c2a6276fc1361005d83b98ef315cbdbc/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L281)):*
> ```XML
>         assert_eq!(input.height, BlockNumber(0));
>         Ok(())
>     });
> ```

let's use withf here



_Code quote:_
```XML
    batcher.expect_start_height().return_once(|input: StartHeightInput| {
        assert_eq!(input.height, BlockNumber(0));
        Ok(())
    });
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 285 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OCbyWE_9WLfCMCE3JTX:-OCbyWE_9WLfCMCE3JTY:be65cnh) ([raw file](https://github.com/starkware-libs/sequencer/blob/6338aa88c2a6276fc1361005d83b98ef315cbdbc/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L285)):*
> ```XML
>         .expect_send_proposal_content()
>         .withf(|input| input.proposal_id == ProposalId(0))
>         .times(0..=1)
> ```

Nice find!

I realize that another approach is to completely delete this expectation and below at line 326, we can just never send any content to the first proposal. Then this will never be called. We then can just rely on adding a `withf` to `expect_validate_block` which I think is good enough.



_Code quote:_
```XML
        .times(0..=1)
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 341 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OCc011-2Bp2ORwjuo28:-OCc011-2Bp2ORwjuo29:b-y31mon) ([raw file](https://github.com/starkware-libs/sequencer/blob/6338aa88c2a6276fc1361005d83b98ef315cbdbc/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L341)):*
> ```XML
>     // Interrupt active proposal.
>     assert!(fin_receiver_0.await.is_err());
>     assert_eq!(fin_receiver_1.await.unwrap().0, STATE_DIFF_COMMITMENT.0.0);
> ```

My suggested rewrite based on my comment above - proposal(0) never sends content and we rely on `withf` more.

Not blocking



_Suggestion:_
```XML
    let mut batcher = MockBatcherClient::new();
    batcher.expect_start_height().return_once(|input: StartHeightInput| {
        assert_eq!(input.height, BlockNumber(0));
        Ok(())
    });
    batcher
        .expect_validate_block()
        .times(1)
        .withf(|input| input.proposal_id == ProposalId(0))
        .returning(|_| Ok(()));
    batcher
        .expect_validate_block()
        .times(1)
        .withf(|input| input.proposal_id == ProposalId(1))
        .returning(|_| Ok(()));
    batcher
        .expect_send_proposal_content()
        .withf(|input| {
            input.proposal_id == ProposalId(1)
                && input.content == SendProposalContent::Txs(TX_BATCH.clone())
        })
        .times(1)
        .returning(move |_| {
            Ok(SendProposalContentResponse { response: ProposalStatus::Processing })
        });
    batcher
        .expect_send_proposal_content()
        .withf(|input| {
            input.proposal_id == ProposalId(1)
                && matches!(input.content, SendProposalContent::Finish)
        })
        .times(1)
        .returning(move |_| {
            Ok(SendProposalContentResponse {
                response: ProposalStatus::Finished(ProposalCommitment {
                    state_diff_commitment: STATE_DIFF_COMMITMENT,
                }),
            })
        });
    let TestSubscriberChannels { mock_network: _, subscriber_channels } =
        mock_register_broadcast_topic().expect("Failed to create mock network");
    let BroadcastTopicChannels { broadcasted_messages_receiver: _, broadcast_topic_client } =
        subscriber_channels;
    let mut context =
        SequencerConsensusContext::new(Arc::new(batcher), broadcast_topic_client, NUM_VALIDATORS);
    // Initialize the context for a specific height, starting with round 0.
    context.set_height_and_round(BlockNumber(0), 0).await;

    let (mut content_sender, content_receiver) = mpsc::channel(CHANNEL_SIZE);
    let fin_receiver_0 =
        context.validate_proposal(BlockNumber(0), 0, TIMEOUT, content_receiver).await;
    content_sender.close_channel();

    let (mut content_sender, content_receiver) = mpsc::channel(CHANNEL_SIZE);
    content_sender.send(TX_BATCH.clone()).await.unwrap();
    let fin_receiver_1 =
        context.validate_proposal(BlockNumber(0), 1, TIMEOUT, content_receiver).await;
    content_sender.close_channel();
    // Move the context to the next round.
    context.set_height_and_round(BlockNumber(0), 1).await;

    // Interrupt active proposal.
    assert!(fin_receiver_0.await.is_err());
    assert_eq!(fin_receiver_1.await.unwrap().0, STATE_DIFF_COMMITMENT.0.0);
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OCbxO8-11oGGF6sff0C:-OCbxO8-11oGGF6sff0D:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/6338aa88c2a6276fc1361005d83b98ef315cbdbc/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L74)):*
> ```XML
>     // Building proposals are not tracked as active, as consensus can't move on to the next
>     // height/round until building is done, also context only works on proposals for the
>     // current round.
> ```





_Suggestion:_
```XML
    // The active proposal refers to the proposal being validated at the current height/round.
    // Building proposals are not tracked as active, as consensus can't move on to the next
    // height/round until building is done. Context only works on proposals for the
    // current round.
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 251 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OCbxhRAAN6i0blKZ93c:-OCbxhRAAN6i0blKZ93d:bxhzj3l) ([raw file](https://github.com/starkware-libs/sequencer/blob/6338aa88c2a6276fc1361005d83b98ef315cbdbc/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L251)):*
> ```XML
>             // that consensus works on a given height until it is done (either a
>             // decision is reached or sync causes us to move on) and then moves on to a
>             // different height, never to return to the old height.
> ```

Fix line lengths



_Code quote:_
```XML
            // The Batcher must be told when we begin to work on a new height. The implicit model is
            // that consensus works on a given height until it is done (either a
            // decision is reached or sync causes us to move on) and then moves on to a
            // different height, never to return to the old height.
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2178)* status: all files reviewed, 10 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 139 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC91Hh1-SXqZR4jDue-:-OCc68m3DYPz27zDi3OW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L139)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I think we should remove this. If you want something then put it above `proposal_id` and something like "Consider if we want to differentiate between an interrupt and other failures."
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 339 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC9fObn2bg7anFNVrK0:-OCc6CF91Pn6ua0ZnonH:b-8fx2u7) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L339)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Please ack
</blockquote></details>

:+1: 
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 281 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OCbySZO8Aa2byB3IP8G:-OCc5Blu-JiX7g-fE88r:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6338aa88c2a6276fc1361005d83b98ef315cbdbc/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L281)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

let's use withf here
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 285 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OCbyWE_9WLfCMCE3JTX:-OCc4QqNA7gOvdur68-K:b-5n0a5v) ([raw file](https://github.com/starkware-libs/sequencer/blob/6338aa88c2a6276fc1361005d83b98ef315cbdbc/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L285)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Nice find!

I realize that another approach is to completely delete this expectation and below at line 326, we can just never send any content to the first proposal. Then this will never be called. We then can just rely on adding a `withf` to `expect_validate_block` which I think is good enough.
</blockquote></details>

Agree :+1: 
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 260 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC9e2qcCzqjIgHRikuC:-OCSpak482vZQdyxK6pg:bsyauld) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L260)):*
> ```XML
>                 std::cmp::Ordering::Less => {
>                     entry.remove();
>                 }
> ```

`match` arms must return the same type (this case () ).
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 219 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OC9iDPR-yuwuKk5x1sq:-OCc5zu3BpL80FWW2oCk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1818e795db752ecce8c893781cef86a7c9ad68be/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L219)):*
> ```XML
>                 panic!("Expected SendProposalContent::Txs, got {:?}", input.content);
>             };
>             assert_eq!(txs, TX_BATCH.clone());
> ```

Done.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2178)* status: all files reviewed, 3 unresolved discussions (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 251 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OCcRFOo8LID7QB574pA:-OCcRFOo8LID7QB574pB:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/f5304b7a26d9c3005948e642d39b29fc225631e9/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L251)):*
> ```XML
>             // The implicit model is that consensus works on a given height until
>             // it is done (either a decision is reached or sync causes us to move on)
>             // and then moves on to a different height, never to return to the old height.
> ```





_Suggestion:_
```XML
            // The Batcher must be told when we begin to work on a new height. The implicit model is
            // that consensus works on a given height until it is done (either a decision is reached
            // or sync causes us to move on) and then moves on to a different height, never to
            // return to the old height.
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 332 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OCcRwCy6BsPeZn5UWnO:-OCcRwCy6BsPeZn5UWnP:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/f5304b7a26d9c3005948e642d39b29fc225631e9/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L332)):*
> ```XML
>     let fin_receiver_1 =
>         context.validate_proposal(BlockNumber(0), 1, TIMEOUT, content_receiver).await;
>     content_sender.close_channel();
> ```





_Suggestion:_
```XML
    // Keep the sender open, as closing it or sending Fin would cause the validate to complete
    // without needing interrupt.
    let (mut content_sender0, content_receiver) = mpsc::channel(CHANNEL_SIZE);
    let fin_receiver_0 =
        context.validate_proposal(BlockNumber(0), 0, TIMEOUT, content_receiver).await;

    let (mut content_sender1, content_receiver) = mpsc::channel(CHANNEL_SIZE);
    content_sender.send(TX_BATCH.clone()).await.unwrap();
    let fin_receiver_1 =
        context.validate_proposal(BlockNumber(0), 1, TIMEOUT, content_receiver).await;
    content_sender.close_channel();
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2178)* status: all files reviewed, 3 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 332 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2178#-OCcRwCy6BsPeZn5UWnO:-OCcjKpXDVufsFw3R3QQ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f5304b7a26d9c3005948e642d39b29fc225631e9/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L332)):*
> ```XML
>     let fin_receiver_1 =
>         context.validate_proposal(BlockNumber(0), 1, TIMEOUT, content_receiver).await;
>     content_sender.close_channel();
> ```

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2178)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
