### PR TITLE
chore: refactor invoke as wrapper

### PR DESCRIPTION
**Pull request by ArniStarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

For internal deploy account transaction, the data is inseparable from the implementation.
The data of `IntrnalInvokeTransaction` and of `InvokeTransaction` (on the blockifier) is duplicated.

## What is the new behavior?

- Refactor `InvokeTransaction` as a wrapper of `IntrnalInvokeTransaction` while keeping the implementation.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/93)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/93?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#93** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/93?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#92** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/92?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/93)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 495 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/93#-O37w5RsB1fyn62Z06YF:-O37w5RsB1fyn62Z06YG:b-eivxfh) ([raw file](https://github.com/starkware-libs/sequencer/blob/91422c2acb28e3153e4298c2af0993fb2970a6e5/crates/blockifier/src/transaction/transactions.rs#L495)):*
> ```XML
>         let common_fields = CommonAccountFields {
>             transaction_hash: self.tx.tx_hash,
>             version: self.tx.tx.version(),
> ```

and the same for the other fields pls



_Suggestion:_
```XML
self.tx.version()
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/93)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 495 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/93#-O37w5RsB1fyn62Z06YF:-O3DHpQt6zmSCC4ZBVug:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/91422c2acb28e3153e4298c2af0993fb2970a6e5/crates/blockifier/src/transaction/transactions.rs#L495)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

and the same for the other fields pls
</blockquote></details>

Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/93#-:-O3XPGooEE6pVEvJ2MR7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
*[`crates/gateway/src/utils.rs` line 149 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/93#-O4EyFa28azLmqknjVnf:-O4EyFa28azLmqknjVng:b-j0qg8o) ([raw file](https://github.com/starkware-libs/sequencer/blob/747086ba463cfac90ab52658f800011e345ac55c/crates/gateway/src/utils.rs#L149)):*
> ```XML
>         },
>         AccountTransaction::DeployAccount(tx) => tx.contract_address(),
>         AccountTransaction::Invoke(tx) => match &tx.tx() {
> ```

Please review this change from the base commit.



_Code quote:_
```XML
 AccountTransaction::Invoke(tx) => match &tx.tx() {
```

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/93#-:-O4ix-L62e3U3thfNJ0W:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/93)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
