### PR TITLE
chore(starknet_sierra_compile): improve doc and tests for the param max_bytecode_size

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#2994** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2994?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2994?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2994#-:-OFGjcSR8GKrgjFhJeM-:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved

___
*[`config/sequencer/default_config.json` line 217 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2994#-OFGjFzRE5p43gtman9E:-OFGjFzRE5p43gtman9F:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/c9ba179bfba8c8102bce536f1592b88db144e575/config/sequencer/default_config.json#L217)):*
> ```JSON
>     "privacy": "TemporaryValue"
>   },
>   "compiler_config.max_bytecode_size": {
> ```





_Suggestion:_
```JSON
max_casm_bytecode_size
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2994)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @dafnamatsry)

___
*[`config/sequencer/default_config.json` line 217 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2994#-OFGjFzRE5p43gtman9E:-OFGmwLNCiEsrKHSs0qW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c9ba179bfba8c8102bce536f1592b88db144e575/config/sequencer/default_config.json#L217)):*
> ```JSON
>     "privacy": "TemporaryValue"
>   },
>   "compiler_config.max_bytecode_size": {
> ```

Done.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2994)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Pull request merged**
