### PR TITLE
fix: cosmetic changes in Docker and yaml files

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1171)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1171)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`Dockerfile` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1171#-O8Vke3w3IopnWWG12pA:-O8Vke3w3IopnWWG12pB:bkahmah) ([raw file](https://github.com/starkware-libs/sequencer/blob/612b2289021f83a9a8702c3ec2f95693a57daefb/Dockerfile#L34)):*
> ```Dockerfile
> # # This enables the creation of fully self-contained binaries that do not depend on the system's dynamic libraries,
> # # resulting in more portable executables that can run on any Linux distribution.
> # RUN rustup target add x86_64-unknown-linux-musl
> ```

why? the double-`#`s are here to differentiate between comments and commented-code



_Code quote:_
```Dockerfile
# # Reinstalling the stable Rust toolchain to ensure a clean environment
# RUN rustup toolchain uninstall stable-x86_64-unknown-linux-gnu && rustup toolchain install stable-x86_64-unknown-linux-gnu

# # Add the x86_64-unknown-linux-musl target to rustup for compiling statically linked binaries.
# # This enables the creation of fully self-contained binaries that do not depend on the system's dynamic libraries,
# # resulting in more portable executables that can run on any Linux distribution.
# RUN rustup target add x86_64-unknown-linux-musl
```
___
*[`.github/workflows/papyrus_benchmark.yaml` line 7 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1171#-O8VknFRCW29NqCB5Mrc:-O8VknFRCW29NqCB5Mrd:bd5l6mr) ([raw file](https://github.com/starkware-libs/sequencer/blob/dee92ff8c3a7264f97ef764fd6b2260990f36534/.github/workflows/papyrus_benchmark.yaml#L7)):*
> ```YAML
>   # TODO: Uncomment and run this automatically when the storage benchmark is fixed.
>   # push:
>     # branches: [main]
> ```

thanks!

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1171)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`Dockerfile` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1171#-O8Vke3w3IopnWWG12pA:-O8VnHsV0qGdBZIrR6HR:bhf5afi) ([raw file](https://github.com/starkware-libs/sequencer/blob/612b2289021f83a9a8702c3ec2f95693a57daefb/Dockerfile#L34)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why? the double-`#`s are here to differentiate between comments and commented-code
</blockquote></details>

Is it standard?
Comments usually have one `#`, no?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1171)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`Dockerfile` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1171#-O8Vke3w3IopnWWG12pA:-O8VnvT757GfOQ9GthcX:b-o5kgp1) ([raw file](https://github.com/starkware-libs/sequencer/blob/612b2289021f83a9a8702c3ec2f95693a57daefb/Dockerfile#L34)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it standard?
Comments usually have one `#`, no?
</blockquote></details>

yes but before your change, if you highlight all the lines here and `ctrl + /`, you will get the intended change: comments with single `#`s and lines starting with `RUN`.
not sure if "standard" but useful

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1171)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`Dockerfile` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1171#-O8Vke3w3IopnWWG12pA:-O8VtHSM99ZUj1r7NDPJ:b-fdy4b9) ([raw file](https://github.com/starkware-libs/sequencer/blob/612b2289021f83a9a8702c3ec2f95693a57daefb/Dockerfile#L34)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes but before your change, if you highlight all the lines here and `ctrl + /`, you will get the intended change: comments with single `#`s and lines starting with `RUN`.
not sure if "standard" but useful
</blockquote></details>

Why not highlight only the relevant line (`RUN ...`)?
I prefer one `#` but does not care that much

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1171#-:-O8VvP9b5jiK2W85g8zl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
