### PR TITLE
chore(blockifier_reexecution): compile sierra to versioned runnable class

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2679?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2679** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2679?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2679?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2678** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2678?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2668** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2668?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2641](https://github.com/starkware-libs/sequencer/pull/2641) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2641?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2614** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2614?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2493** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2493?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2438** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2438?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2420** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2420?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2421](https://github.com/starkware-libs/sequencer/pull/2421) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2421?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2467** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2467?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2466** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2466?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2679)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/test_state_reader.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2679#-OE9yUXl2isSAyale1ph:-OE9yUXm9zJogPVW03E2:b-yun83l) ([raw file](https://github.com/starkware-libs/sequencer/blob/484c4f688fcb190facac036a51ebd3be2fb56a8b/crates/blockifier_reexecution/src/state_reader/test_state_reader.rs#L138)):*
> ```XML
>             StarknetContractClass::Sierra(sierra) => {
>                 let (casm, _) = sierra_to_versioned_contract_class_v1(sierra).unwrap();
>                 let runnable_contract_class: RunnableCompiledClass = casm.try_into().unwrap();
> ```

personally prefer to avoid `let x: X = y.into()` when you can do `let x = X::from(y)`
non-blocking



_Suggestion:_
```XML
let runnable_contract_class = RunnableCompiledClass::try_from(casm).unwrap();
```
___
*[`crates/blockifier_reexecution/src/state_reader/compile.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2679#-OE9xskE5oFeawzeXAzj:-OE9xskE5oFeawzeXAzk:bj2zjg6) ([raw file](https://github.com/starkware-libs/sequencer/blob/484c4f688fcb190facac036a51ebd3be2fb56a8b/crates/blockifier_reexecution/src/state_reader/compile.rs#L79)):*
> ```XML
> pub fn sierra_to_versioned_contract_class_v1(
>     sierra: FlattenedSierraClass,
> ) -> StateResult<(ContractClass, SierraVersion)> {
> ```

doesn't this tuple type have a name you can use?



_Code quote:_
```XML
(ContractClass, SierraVersion)
```
___
*[`crates/blockifier_reexecution/src/state_reader/compile.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2679#-OE9xyhkBBiZR6-923ic:-OE9xyhkBBiZR6-923id:b67l2na) ([raw file](https://github.com/starkware-libs/sequencer/blob/484c4f688fcb190facac036a51ebd3be2fb56a8b/crates/blockifier_reexecution/src/state_reader/compile.rs#L100)):*
> ```XML
>         .collect::<Vec<u64>>()
>         .try_into()
>         .expect("Expected exactly 3 elements.");
> ```

this version-from-sierra logic is duplicated, no? is this avoidable? I realize the type of the sierra contract isn't the same but is there something you can reuse?
non-blocking



_Code quote:_
```XML
    let [major, minor, patch] = sierra
        .sierra_program
        .clone()
        .into_iter()
        .take(3)
        .map(|big_uint_as_hex| u64::try_from(big_uint_as_hex.value).unwrap())
        .collect::<Vec<u64>>()
        .try_into()
        .expect("Expected exactly 3 elements.");
```
___
*[`crates/blockifier_reexecution/src/state_reader/offline_state_reader.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2679#-OE9yEjH57m5iQgvmmMR:-OE9yEjH57m5iQgvmmMS:b-nlym40) ([raw file](https://github.com/starkware-libs/sequencer/blob/484c4f688fcb190facac036a51ebd3be2fb56a8b/crates/blockifier_reexecution/src/state_reader/offline_state_reader.rs#L163)):*
> ```XML
>         match self.get_contract_class(&class_hash)? {
>             StarknetContractClass::Sierra(sierra) => {
>                 let (casm, _) = sierra_to_versioned_contract_class_v1(sierra).unwrap();
> ```

why is this line needed...? where is `casm` used?



_Code quote:_
```XML
let (casm, _) = sierra_to_versioned_contract_class_v1(sierra).unwrap();
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2679)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @AvivYossef-starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2679)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/compile.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2679#-OE9xskE5oFeawzeXAzj:-OEAz4Vg43s6iovf4XB8:b-zge02k) ([raw file](https://github.com/starkware-libs/sequencer/blob/84d38fd05381a39116214dfbe1ddaef58d3a4f56/crates/blockifier_reexecution/src/state_reader/compile.rs#L79)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

doesn't this tuple type have a name you can use?
</blockquote></details>

No, I can define a new one but its in use only here

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2679#-:-OEJBzlIAqQTQ7X0jVtf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

___
*[`crates/blockifier_reexecution/src/state_reader/compile.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2679#-OE9xskE5oFeawzeXAzj:-OEJBmMNCe-6B1GArGcy:bio6ldp) ([raw file](https://github.com/starkware-libs/sequencer/blob/84d38fd05381a39116214dfbe1ddaef58d3a4f56/crates/blockifier_reexecution/src/state_reader/compile.rs#L79)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

No, I can define a new one but its in use only here
</blockquote></details>

nvm then

**Comment by AvivYossef-starkware** [comment]
### Merge activity

* **Dec 17, 3:08 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2679).

**Pull request merged**
