### PR TITLE
test(blockifier): global validate and execute sierra_gas

### PR DESCRIPTION
**Pull request by aner-starkware**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2596)* status: all files reviewed, 7 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODkYCE-EV8Y2DZ3AkCh:-ODkYCE-EV8Y2DZ3AkCi:b7jh03c) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/test_utils.rs#L98)):*
> ```XML
>     l2_gas_amount: GasAmount,
>     l1_data_gas_amount: GasAmount,
> ) -> ValidResourceBounds {
> ```

consider making this input a GasVector



_Suggestion:_
```XML
pub fn create_gas_amount_bounds_with_default_price(
    GasVector { l1_gas, l2_gas, l1_data_gas }
) -> ValidResourceBounds {
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODkXg_t9uR36V45DJ-L:-ODkXg_t9uR36V45DJ-M:bwj5798) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/test_utils.rs#L107)):*
> ```XML
>         DEFAULT_STRK_L1_DATA_GAS_PRICE.into(),
>     )
> }
> ```

cool!
I see three places where this function can be dropped in; can you search for usages of `create_all_resource_bounds` and use this util where applicable?



_Code quote:_
```XML
pub fn create_gas_amount_bounds_with_default_price(
    l1_gas_amount: GasAmount,
    l2_gas_amount: GasAmount,
    l1_data_gas_amount: GasAmount,
) -> ValidResourceBounds {
    create_all_resource_bounds(
        l1_gas_amount,
        DEFAULT_STRK_L1_GAS_PRICE.into(),
        l2_gas_amount,
        DEFAULT_STRK_L2_GAS_PRICE.into(),
        l1_data_gas_amount,
        DEFAULT_STRK_L1_DATA_GAS_PRICE.into(),
    )
}
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 117 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODkXs8SErMpgPykahsB:-ODkXs8SErMpgPykahsC:b-pe5z07) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/test_utils.rs#L117)):*
> ```XML
> pub fn versioned_constants(block_context: BlockContext) -> VersionedConstants {
>     block_context.versioned_constants().clone()
> }
> ```

can you use references...? cloning the VC can be slow if it really copies data,
VC instances should be `'static` refs so no cloning should be necessary unless the test edits the VC
non-blocking



_Code quote:_
```XML
pub fn versioned_constants(block_context: BlockContext) -> VersionedConstants {
    block_context.versioned_constants().clone()
}
```
___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 654 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODkXLH40Tqm8mMk79VG:-ODkXLH40Tqm8mMk79VH:bjtx5la) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L654)):*
> ```Cairo
>     fn return_result(ref self: ContractState, num: felt252) -> felt252 {
>         let result = num;
>         result
> ```

this doesn't compile? non-blocking



_Suggestion:_
```Cairo
        num
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2620 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODkZ_e08S-nHcO8T3Cy:-ODkZ_e08S-nHcO8T3Cz:bomfw5i) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/transactions_test.rs#L2620)):*
> ```XML
> #[test]
> fn test_balance_print() {
>     let int = balance_to_big_uint(&Felt::from(16_u64), &Felt::from(1_u64));
> ```

in both tests: deprecated tx testing is also required, not just different user bounds in V3 txs.
I suggest changing the type of `#[case]` param you have, from ResourceBounds to InvokeTxArgs / DeployAccountTxArgs. also pass a `version` field (v1 or v3) and a max_fee field if the version is v1. this will require very minimal changes to inputs, though you will need to update the checks as well. 
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2630 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODk_6QKEUsviFykP3pH:-ODk_6QKEUsviFykP3pI:b-knckg7) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/transactions_test.rs#L2630)):*
> ```XML
>     GasAmount(0)
> ))]
> #[case::user_bounds_between_validate_and_execute(create_gas_amount_bounds_with_default_price(GasAmount(1652), versioned_constants.validate_max_sierra_gas + GasAmount(1234567), GasAmount(0)))]
> ```

break lines



_Code quote:_
```XML
#[case::user_bounds_between_validate_and_execute(create_gas_amount_bounds_with_default_price(GasAmount(1652), versioned_constants.validate_max_sierra_gas + GasAmount(1234567), GasAmount(0)))]
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2707 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODkZDrU6gKO2hGRHnSe:-ODkZDrU6gKO2hGRHnSf:b-pxgc5g) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/transactions_test.rs#L2707)):*
> ```XML
>         // DOES THIS MAKE SENSE?!
>         actual_execute_initial_gas
>             - actual_execution_info.execute_call_info.as_ref().unwrap().execution.gas_consumed
> ```

hmmm... it looks like the initial gas of the inner call actually takes into account the gas consumption of the *entire tree*, right?
that doesn't sound right
@Yoni-Starkware ?



_Code quote:_
```XML
        // DOES THIS MAKE SENSE?!
        actual_execute_initial_gas
            - actual_execution_info.execute_call_info.as_ref().unwrap().execution.gas_consumed
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2720 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODk_8RTD7S450APGfep:-ODk_8RTD7S450APGfeq:b-knckg7) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/transactions_test.rs#L2720)):*
> ```XML
>     GasAmount(0)
> ))]
> #[case::user_bounds_between_validate_and_execute(create_gas_amount_bounds_with_default_price(GasAmount(2203), versioned_constants.validate_max_sierra_gas + GasAmount(1234567), GasAmount(0)))]
> ```

break lines



_Code quote:_
```XML
#[case::user_bounds_between_validate_and_execute(create_gas_amount_bounds_with_default_price(GasAmount(2203), versioned_constants.validate_max_sierra_gas + GasAmount(1234567), GasAmount(0)))]
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2759 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODk_JMNDqlHG6tYUbdJ:-ODk_JMNDqlHG6tYUbdK:b-rqhpjm) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/transactions_test.rs#L2759)):*
> ```XML
>             )
>             .unwrap();
>     }
> ```

we have a `fund_account` test util for this



_Code quote:_
```XML
    for fee_type in FeeType::iter() {
        state
            .set_storage_at(
                chain_info.fee_token_address(&fee_type),
                deployed_account_balance_key,
                felt!(BALANCE.0),
            )
            .unwrap();
    }
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2781 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODk_bIz2I4FzsA6Sl2r:-ODk_bIz2I4FzsA6Sl2s:b3ugem7) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/transactions_test.rs#L2781)):*
> ```XML
>                 .validate_max_sierra_gas
>                 .min(GasAmount(
>                     actual_execute_initial_gas
> ```

isn't this the expected amount to subtract from...?



_Suggestion:_
```XML
user_initial_gas
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2596)* status: 3 of 7 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 654 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODkXLH40Tqm8mMk79VG:-ODkfSTg85S9nDLxrnfd:bh731r1) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L654)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this doesn't compile? non-blocking
</blockquote></details>

Compiles.  I just tried to make it as similar to the Cairo0 function as possible (though it's subjective).
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODkYCE-EV8Y2DZ3AkCh:-ODklDnM-L9-N0ZaHrO0:b-ovwawk) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/test_utils.rs#L98)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

consider making this input a GasVector
</blockquote></details>

Good idea!
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODkXg_t9uR36V45DJ-L:-ODkoMT43rXDBM7gPWvM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/test_utils.rs#L107)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

cool!
I see three places where this function can be dropped in; can you search for usages of `create_all_resource_bounds` and use this util where applicable?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 117 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODkXs8SErMpgPykahsB:-ODkpODX-Ui38TnL16Uf:bv16unt) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/test_utils.rs#L117)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you use references...? cloning the VC can be slow if it really copies data,
VC instances should be `'static` refs so no cloning should be necessary unless the test edits the VC
non-blocking
</blockquote></details>

Not sure. I can try, but there seem to be issues with borrowing & lifetimes.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2630 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODk_6QKEUsviFykP3pH:-ODkrc4T90cNeUF04i4H:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/transactions_test.rs#L2630)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

break lines
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2720 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODk_8RTD7S450APGfep:-ODktIq_Dp2NFBCZPqYB:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/transactions_test.rs#L2720)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

break lines
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2781 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODk_bIz2I4FzsA6Sl2r:-ODkoNlVCo5ZhckdFhoY:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/transactions_test.rs#L2781)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

isn't this the expected amount to subtract from...?
</blockquote></details>

Done.

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2759 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODk_JMNDqlHG6tYUbdJ:-ODkv45S8YkwiP8Skod6:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/transactions_test.rs#L2759)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we have a `fund_account` test util for this
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2596)* status: all files reviewed, 6 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier/src/transaction/post_execution_test.rs` line 265 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODkxjF419T97pjf9B_H:-ODkxjF419T97pjf9B_I:b-fxzv0m) ([raw file](https://github.com/starkware-libs/sequencer/blob/8b3304c79c709b685c37fb6f66cb80f6918b59ac/crates/blockifier/src/transaction/post_execution_test.rs#L265)):*
> ```XML
>     use starknet_api::execution_resources::GasVector;
> 
>     use crate::transaction::test_utils::create_gas_amount_bounds_with_default_price;
> ```

move to top



_Code quote:_
```XML
    use starknet_api::execution_resources::GasVector;

    use crate::transaction::test_utils::create_gas_amount_bounds_with_default_price;
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 197 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODkxeH-6Ro3PcmeaGEC:-ODkxeH-6Ro3PcmeaGED:b-fxzv0m) ([raw file](https://github.com/starkware-libs/sequencer/blob/8b3304c79c709b685c37fb6f66cb80f6918b59ac/crates/blockifier/src/transaction/account_transactions_test.rs#L197)):*
> ```XML
>     #[values(true, false)] zero_bounds: bool,
> ) {
>     use crate::transaction::test_utils::create_gas_amount_bounds_with_default_price;
> ```

move to top



_Code quote:_
```XML
use crate::transaction::test_utils::create_gas_amount_bounds_with_default_price;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2614 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODky1ijDbF4Yd2pV3yr:-ODky1ijDbF4Yd2pV3ys:b70euap) ([raw file](https://github.com/starkware-libs/sequencer/blob/8b3304c79c709b685c37fb6f66cb80f6918b59ac/crates/blockifier/src/transaction/transactions_test.rs#L2614)):*
> ```XML
> #[rstest]
> #[case::small_user_bounds(create_gas_amount_bounds_with_default_price(
>     GasVector{ l1_gas: GasAmount(1652), l2_gas: GasAmount(654321), l1_data_gas: GasAmount(0) }
> ```

is this over 100 chars? need to line break if so



_Code quote:_
```XML
GasVector{ l1_gas: GasAmount(1652), l2_gas: GasAmount(654321), l1_data_gas: GasAmount(0) }
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2708 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODky7caDmVfH9h4dQNR:-ODky7caDmVfH9h4dQNS:b-k5ncrd) ([raw file](https://github.com/starkware-libs/sequencer/blob/8b3304c79c709b685c37fb6f66cb80f6918b59ac/crates/blockifier/src/transaction/transactions_test.rs#L2708)):*
> ```XML
> #[rstest]
> #[case::small_user_bounds(create_gas_amount_bounds_with_default_price(
>     GasVector{ l1_gas: GasAmount(2203), l1_data_gas: GasAmount(0), l2_gas: GasAmount(654321) }
> ```

line break?



_Code quote:_
```XML
GasVector{ l1_gas: GasAmount(2203), l1_data_gas: GasAmount(0), l2_gas: GasAmount(654321) }
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 7 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2596)* status: all files reviewed, 6 unresolved discussions (waiting on @aner-starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2596)* status: 3 of 7 files reviewed, 7 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2707 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODkZDrU6gKO2hGRHnSe:-ODlAA38EM6S2RKnjaQo:b-l6cbr3) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/transactions_test.rs#L2707)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

hmmm... it looks like the initial gas of the inner call actually takes into account the gas consumption of the *entire tree*, right?
that doesn't sound right
@Yoni-Starkware ?
</blockquote></details>

It is only possible if the inner call has gas_consumed 0 and the caller exists immediately after the call; please check that.
It can happen if the function is super cheap - below 10K gas (remember we put the initial 10K on the caller)

If it's indeed the case, please make the inner call more expensive.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2656 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODl9VpQ-mhhk60GrFVJ:-ODl9VpQ-mhhk60GrFVK:b-pvdpo7) ([raw file](https://github.com/starkware-libs/sequencer/blob/29742c25e1e550629a40099892ea17009680272d/crates/blockifier/src/transaction/transactions_test.rs#L2656)):*
> ```XML
>     let contract_tracked_resource = test_contract
>         .get_runnable_class()
>         .tracked_resource(&versioned_constants.min_compiler_version_for_sierra_gas, None);
> ```

Right?
If this account is the caller of the test contract.

I don't know what's the intention of this test though



_Suggestion:_
```XML
    let contract_tracked_resource = test_contract
        .get_runnable_class()
        .tracked_resource(&versioned_constants.min_compiler_version_for_sierra_gas, account_tracked_resource);
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2596)* status: 3 of 7 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 197 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODkxeH-6Ro3PcmeaGEC:-OE5gJj59fpVOwScONKF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8b3304c79c709b685c37fb6f66cb80f6918b59ac/crates/blockifier/src/transaction/account_transactions_test.rs#L197)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move to top
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/post_execution_test.rs` line 265 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODkxjF419T97pjf9B_H:-OE5gWgtBYvaWfsVRGD4:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8b3304c79c709b685c37fb6f66cb80f6918b59ac/crates/blockifier/src/transaction/post_execution_test.rs#L265)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move to top
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2620 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODkZ_e08S-nHcO8T3Cy:-OE5j5Dd45IaUvLzZY8T:b-p61ky9) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/transactions_test.rs#L2620)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

in both tests: deprecated tx testing is also required, not just different user bounds in V3 txs.
I suggest changing the type of `#[case]` param you have, from ResourceBounds to InvokeTxArgs / DeployAccountTxArgs. also pass a `version` field (v1 or v3) and a max_fee field if the version is v1. this will require very minimal changes to inputs, though you will need to update the checks as well.
</blockquote></details>

Sounds like it's not such a small change; added a TODO and will do it in the next PR. Though I'm not actually sure I understand what it is that I'm supposed to check and what is the expected result.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2707 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODkZDrU6gKO2hGRHnSe:-OE5ehHo49l5ZldtkMwD:b-btdayb) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/transactions_test.rs#L2707)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

It is only possible if the inner call has gas_consumed 0 and the caller exists immediately after the call; please check that.
It can happen if the function is super cheap - below 10K gas (remember we put the initial 10K on the caller)

If it's indeed the case, please make the inner call more expensive.
</blockquote></details>

Done. Though I'm not sure I completely understand the logic here.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2614 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODky1ijDbF4Yd2pV3yr:-OE5fJi44_KlQAcDivf4:b-hi6d57) ([raw file](https://github.com/starkware-libs/sequencer/blob/8b3304c79c709b685c37fb6f66cb80f6918b59ac/crates/blockifier/src/transaction/transactions_test.rs#L2614)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this over 100 chars? need to line break if so
</blockquote></details>

I don't think it is. There are longer lines above, for example in `test_balance_print`.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2708 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODky7caDmVfH9h4dQNR:-OE5fFsv03uBJci-wzWl:b-ybmmam) ([raw file](https://github.com/starkware-libs/sequencer/blob/8b3304c79c709b685c37fb6f66cb80f6918b59ac/crates/blockifier/src/transaction/transactions_test.rs#L2708)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

line break?
</blockquote></details>

I don't think it's needed here.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2656 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODl9VpQ-mhhk60GrFVJ:-OE5fsizB1Xp1FzfZzCD:b-k5g2m2) ([raw file](https://github.com/starkware-libs/sequencer/blob/29742c25e1e550629a40099892ea17009680272d/crates/blockifier/src/transaction/transactions_test.rs#L2656)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Right?
If this account is the caller of the test contract.

I don't know what's the intention of this test though
</blockquote></details>

Done. It's for the inner call `initial_gas` check.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2596)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2620 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODkZ_e08S-nHcO8T3Cy:-OE8POBR72kg62hAH5wq:b-sb6d1o) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/transactions_test.rs#L2620)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Sounds like it's not such a small change; added a TODO and will do it in the next PR. Though I'm not actually sure I understand what it is that I'm supposed to check and what is the expected result.
</blockquote></details>

we want to test that sierra gas tracking works, regardless of the tx version / resource bounds.
you are currently only testing v3.
unblocking; maybe it's not such a small change, although I think if you parametrize like this
```
#[case(InvokeTxArgs { resource_bounds: default_l1_bounds(), ..Default::default() })]
#[case(InvokeTxArgs { resource_bounds: default_all_bounds(), ..Default::default() })]
#[case(InvokeTxArgs { max_fee: MAX_FEE, ..Default::default() })]
fn test_...(tx_args: InvokeTxArgs, ...) {
...
    let invoke_tx = account_invoke_tx(InvokeTxArgs {
        <your params>,
        ...tx_args
    }
```
... it should work ok

**Comment by aner-starkware** [comment]
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2620 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-ODkZ_e08S-nHcO8T3Cy:-OEF82-S4Rc1aROCcbMM:byxdzbk) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004c1407db34abdca73a0d7eaf06258e84ddf55/crates/blockifier/src/transaction/transactions_test.rs#L2620)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we want to test that sierra gas tracking works, regardless of the tx version / resource bounds.
you are currently only testing v3.
unblocking; maybe it's not such a small change, although I think if you parametrize like this
```
#[case(InvokeTxArgs { resource_bounds: default_l1_bounds(), ..Default::default() })]
#[case(InvokeTxArgs { resource_bounds: default_all_bounds(), ..Default::default() })]
#[case(InvokeTxArgs { max_fee: MAX_FEE, ..Default::default() })]
fn test_...(tx_args: InvokeTxArgs, ...) {
...
    let invoke_tx = account_invoke_tx(InvokeTxArgs {
        <your params>,
        ...tx_args
    }
```
... it should work ok
</blockquote></details>

Done. (Merged commit above)

**Review by aner-starkware — COMMENTED** [review]
> Dismissed @Yoni-Starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2596)* status: 3 of 7 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 4 files at r16, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2596)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r19, 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2596#-:-OEJ3dcZ4iPUr2q4cv4W:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
