### PR TITLE
refactor(mempool): remove unnecessary txs from test_get_txs_does_not_…

### PR DESCRIPTION
**Pull request by MohammadNassar1**
…remove_returned_txs_from_pool

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1508)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 230 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1508#-O9jBUmYD8ETEqmkUk0o:-O9jBUmYD8ETEqmkUk0p:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/0215d0fa07f72113f8f534991f766490575b702d/crates/mempool/src/mempool_test.rs#L230)):*
> ```XML
>         .with_pool(pool_txs.clone())
>         .with_priority_queue(queue_txs)
>         .build_into_mempool();
> ```





_Suggestion:_
```XML
    let mut mempool = MempoolContentBuilder::new()
        .with_pool(tx.clone())
        .with_priority_queue(TransactionReference::new(&tx))
        .build_into_mempool();
```
___
*[`crates/mempool/src/mempool_test.rs` line 235 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1508#-O9jBhW85nQVOaOX0Szm:-O9jBhW85nQVOaOX0Szn:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/0215d0fa07f72113f8f534991f766490575b702d/crates/mempool/src/mempool_test.rs#L235)):*
> ```XML
>     get_txs_and_assert_expected(&mut mempool, 1, &pool_txs);
>     let expected_mempool_content =
>         MempoolContentBuilder::new().with_pool(pool_txs).with_priority_queue([]).build();
> ```





_Suggestion:_
```XML
    let expected_mempool_content =
        MempoolContentBuilder::new().with_pool(tx).with_priority_queue([]).build();
```

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1508#-:-O9jRw2ZC-6se6R1vZnq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/test_utils.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1508#-O9jRaI19UtxWfXJVuFt:-O9jRaI19UtxWfXJVuFu:b-y8wgbk) ([raw file](https://github.com/starkware-libs/sequencer/blob/f60b95234aa0dfd341ce62e3a74a277d5feb1f9b/crates/mempool/src/test_utils.rs#L83)):*
> ```XML
>     };
>     () => {
>         tx!(tx_nonce: 0)
> ```

please re-order this macro in a different PR (shortest input below, ..)



_Code quote:_
```XML
 tx!(tx_nonce: 0)
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1508)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/test_utils.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1508#-O9jRaI19UtxWfXJVuFt:-O9jSHbV34K2obCyxrVF:b-au08i4) ([raw file](https://github.com/starkware-libs/sequencer/blob/f60b95234aa0dfd341ce62e3a74a277d5feb1f9b/crates/mempool/src/test_utils.rs#L83)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

please re-order this macro in a different PR (shortest input below, ..)
</blockquote></details>

Sure, will do in a separate PR.

**Review by elintul — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1508#-:-O9jWpMB2ROQ_0UEpEXH:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 234 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1508#-O9jWqzI3iIzLbTHoJP6:-O9jWqzI3iIzLbTHoJP7:b-blh208) ([raw file](https://github.com/starkware-libs/sequencer/blob/f60b95234aa0dfd341ce62e3a74a277d5feb1f9b/crates/mempool/src/mempool_test.rs#L234)):*
> ```XML
> 
>     // Test and assert: all transactions are returned.
>     get_txs_and_assert_expected(&mut mempool, 1, &pool_txs);
> ```

Ask for `2`, just in case.



_Code quote:_
```XML
1
```
___
*[`crates/mempool/src/test_utils.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1508#-O9jRaI19UtxWfXJVuFt:-O9jWktm4tnHOSLqYyGp:b-ocoowt) ([raw file](https://github.com/starkware-libs/sequencer/blob/f60b95234aa0dfd341ce62e3a74a277d5feb1f9b/crates/mempool/src/test_utils.rs#L83)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Sure, will do in a separate PR.
</blockquote></details>

Break longer-than-100-chars lines, while at it

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1508)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1508)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 197 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1508#-O9jYooWAVSLU3EBnpDr:-O9jYooWAVSLU3EBnpDs:byr5o8) ([raw file](https://github.com/starkware-libs/sequencer/blob/6b8ae3a517eb75d1d7f5383670c1ae2111df9560/crates/mempool/src/mempool_test.rs#L197)):*
> ```XML
>     let mut txs = [
>         tx!(tip: 20, tx_hash: 1, sender_address: "0x0"),
>         tx!(tip: 30, tx_hash: 2, sender_address: "0x1"),
> ```

How come? Is master broken?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1508)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 234 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1508#-O9jWqzI3iIzLbTHoJP6:-O9jYTWL5aUdrq4Jk0Nw:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/f60b95234aa0dfd341ce62e3a74a277d5feb1f9b/crates/mempool/src/mempool_test.rs#L234)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Ask for `2`, just in case.
</blockquote></details>

Done

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1508)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 197 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1508#-O9jYooWAVSLU3EBnpDr:-O9jZeH17bTMjSCU4t4N:b-v7hx8o) ([raw file](https://github.com/starkware-libs/sequencer/blob/6b8ae3a517eb75d1d7f5383670c1ae2111df9560/crates/mempool/src/mempool_test.rs#L197)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How come? Is master broken?
</blockquote></details>

What was the issue here?
I've just rebased now, had a conflict with [this](https://github.com/starkware-libs/sequencer/pull/1484)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1508)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/test_utils.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1508#-O9jRaI19UtxWfXJVuFt:-O9j_1kR9keFhjmLi8FS:b-837i48) ([raw file](https://github.com/starkware-libs/sequencer/blob/f60b95234aa0dfd341ce62e3a74a277d5feb1f9b/crates/mempool/src/test_utils.rs#L83)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Break longer-than-100-chars lines, while at it
</blockquote></details>

Okay!

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1508#-:-O9jabLq5UY2T34QuWhn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
