### PR TITLE
chore: tirgger build on cario native binary

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2185)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Comment by avi-starkware** [comment]
*[`crates/starknet_sierra_compile/build.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2185#-OC7avFmDQD-PJpLvWKZ:-OC7avFn2Ln6ijrhSl4i:botapr) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd483945651aa4fbef34d5f2bcf9e9f4cd5b2823/crates/starknet_sierra_compile/build.rs#L15)):*
> ```XML
>         let cairo_native_binary_path = binary_path(CAIRO_NATIVE_BINARY_NAME);
>         println!("cargo:rerun-if-changed={:?}", cairo_native_binary_path);
>     }
> ```

You can put the `rerun-if-changed` inside `install_starknet_native_compile`.
Then you won't need to define the binary path nor add the `#[cfg(....`.


Non-blocking



_Code quote:_
```XML
    #[cfg(feature = "cairo_native")]
    {
        let cairo_native_binary_path = binary_path(CAIRO_NATIVE_BINARY_NAME);
        println!("cargo:rerun-if-changed={:?}", cairo_native_binary_path);
    }
```

**Review by avi-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2185#-:-OC7bXMX4E14gENmHP49:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

**Comment by ArniStarkware** [comment]
* **#2196** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2196?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2185** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2185?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2185?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2185)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/starknet_sierra_compile/build.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2185#-OC7avFmDQD-PJpLvWKZ:-OC93AfOEAJfY72coLbP:b-g5vrvn) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd483945651aa4fbef34d5f2bcf9e9f4cd5b2823/crates/starknet_sierra_compile/build.rs#L15)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

You can put the `rerun-if-changed` inside `install_starknet_native_compile`.
Then you won't need to define the binary path nor add the `#[cfg(....`.


Non-blocking
</blockquote></details>

Done in #2196

**Pull request merged**
