### PR TITLE
chore(batcher): impl SerializeConfig for BlockBuilderConfig and related …

### PR DESCRIPTION
**Pull request by ayeletstarkware**
…structs

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1369)

### CODE REVIEW

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1369)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @ayeletstarkware, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O99rLsFE-5kg7k1e4Bz:-O99rLsFE-5kg7k1e4C-:b1lh5p1) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/bouncer.rs#L46)):*
> ```XML
> pub struct BouncerConfig {
>     pub block_max_capacity: BouncerWeights,
> }
> ```

Why do we need both types?



_Code quote:_
```XML
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
pub struct BouncerConfig {
    pub block_max_capacity: BouncerWeights,
}
```
___
*[`crates/blockifier/src/blockifier/config.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O99sA6l8T89JbhgxkBO:-O99sA6l8T89JbhgxkBP:b1lh5p1) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/blockifier/config.rs#L10)):*
> ```XML
> pub struct TransactionExecutorConfig {
>     pub concurrency_config: ConcurrencyConfig,
> }
> ```

Why do we need both types?



_Code quote:_
```XML
#[derive(Clone, Debug, Default, Deserialize, PartialEq, Serialize)]
pub struct TransactionExecutorConfig {
    pub concurrency_config: ConcurrencyConfig,
}
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1369)* status: all files reviewed, 11 unresolved discussions (waiting on @avi-starkware and @ayeletstarkware)

___
*[`crates/blockifier/src/bouncer.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A5II31ho-WJeo5ql3:-O9A5II31ho-WJeo5ql4:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/bouncer.rs#L146)):*
> ```XML
>             "gas",
>             &self.gas,
>             "An upper bound on the total gas used by block transactions",
> ```





_Suggestion:_
```XML
in a block.
```
___
*[`crates/blockifier/src/bouncer.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A6B7D7-6IrHmGfW1H:-O9A6B7E7d-mWsRsqzj-:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/bouncer.rs#L152)):*
> ```XML
>             "n_steps",
>             &self.n_steps,
>             "An upper bound on the total number of steps used by block transactions",
> ```





_Suggestion:_
```XML
in a block.
```
___
*[`crates/blockifier/src/bouncer.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A5tud6LttPLZ5ZAQ6:-O9A5tud6LttPLZ5ZAQ7:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/bouncer.rs#L158)):*
> ```XML
>             "message_segment_length",
>             &self.message_segment_length,
>             "An upper bound on the message segment length used by block transactions",
> ```





_Suggestion:_
```XML
An upper bound on the message segment length in a block.
```
___
*[`crates/blockifier/src/bouncer.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A5eb67VGLco70k0-F:-O9A5eb67VGLco70k0-G:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/bouncer.rs#L164)):*
> ```XML
>             "n_events",
>             &self.n_events,
>             "An upper bound on the total number of events that occurred by the block transactions.",
> ```





_Suggestion:_
```XML
An upper bound on the total number of events generated in a block.
```
___
*[`crates/blockifier/src/bouncer.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A6J1hEpjcgkTyn-yA:-O9A6J1hEpjcgkTyn-yB:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/bouncer.rs#L170)):*
> ```XML
>             "state_diff_size",
>             &self.state_diff_size,
>             "An upper bound on the total state diff size used by block transactions",
> ```





_Suggestion:_
```XML
in a block.
```
___
*[`crates/blockifier/src/bouncer.rs` line 326 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A6TNf50koTlov7Fsg:-O9A6TNf50koTlov7Fsh:b-quncsj) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/bouncer.rs#L326)):*
> ```XML
>     fn dump(&self) -> BTreeMap<ParamPath, SerializedParam> {
>         BTreeMap::from_iter([
>             ser_param("add_mod", &self.add_mod, "Add mod builtin.", ParamPrivacyInput::Public),
> ```

same line for all builtins



_Suggestion:_
```XML
Max number of add mod builtin usage in a block. 
```
___
*[`crates/blockifier/src/blockifier/config.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A78FYA0bpFgM1peFM:-O9A78FYA0bpFgM1peFN:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/blockifier/config.rs#L46)):*
> ```XML
>                 "enabled",
>                 &self.enabled,
>                 "Whether to use concurrency.",
> ```





_Suggestion:_
```XML
Enables concurrency of transaction execution.
```
___
*[`crates/blockifier/src/blockifier/config.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A7FMEDrfg-AHHRI4y:-O9A7FMEDrfg-AHHRI4z:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/blockifier/config.rs#L52)):*
> ```XML
>                 "n_workers",
>                 &self.n_workers,
>                 "Number of workers.",
> ```





_Suggestion:_
```XML
Number of parallel transaction execution workers.
```
___
*[`crates/blockifier/src/blockifier/config.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A7aSoCGbIORo6KVgV:-O9A7aSoCGbIORo6KVgW:b-t35s9x) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/blockifier/config.rs#L55)):*
> ```XML
>                 ParamPrivacyInput::Public,
>             ),
>             ser_param("chunk_size", &self.chunk_size, "Chunk size.", ParamPrivacyInput::Public),
> ```

The size of the transaction chunk executed in parallel.



_Code quote:_
```XML
Chunk size
```

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1369)* status: all files reviewed, 12 unresolved discussions (waiting on @avi-starkware and @ayeletstarkware)

___
*[`crates/batcher/src/block_builder.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A8oeDCP89kT1raH7F:-O9A8oeDCP89kT1raH7G:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/batcher/src/block_builder.rs#L78)):*
> ```XML
>             "use_kzg_da",
>             &self.use_kzg_da,
>             "Defines which data availability mode to use.",
> ```





_Suggestion:_
```XML
Indicates whether the kzg mechanism is used for data availability.
```

**Comment by avi-starkware** [comment]
*[`crates/batcher/src/block_builder.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9AA9dyB15aILB8foHK:-O9AA9dyB15aILB8foHL:b-6235cn) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/batcher/src/block_builder.rs#L60)):*
> ```XML
>     pub sequencer_address: ContractAddress,
>     pub use_kzg_da: bool,
>     pub tx_chunk_size: usize,
> ```

Did you intentionally not append this config to the dump?



_Code quote:_
```XML
    pub tx_chunk_size: usize,
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1369)* status: all files reviewed, 13 unresolved discussions (waiting on @avi-starkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/batcher/src/block_builder.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9AA9dyB15aILB8foHK:-O9AD8tJD-1zM3rv_RFh:blmqmg7) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/batcher/src/block_builder.rs#L60)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Did you intentionally not append this config to the dump?
</blockquote></details>

nope, nice catch
___
*[`crates/batcher/src/block_builder.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A8oeDCP89kT1raH7F:-O9ADLkZ5a1IAMWhec1k:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/batcher/src/block_builder.rs#L78)):*
> ```XML
>             "use_kzg_da",
>             &self.use_kzg_da,
>             "Defines which data availability mode to use.",
> ```

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O99rLsFE-5kg7k1e4Bz:-O9AEsL4AYFgtOjgP_Ba:b-fgtyr1) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/bouncer.rs#L46)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do we need both types?
</blockquote></details>

Out of scope, can be refactored in a different PR.
___
*[`crates/blockifier/src/bouncer.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A5II31ho-WJeo5ql3:-O9ADf2j-1mc3cbxEAWc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/bouncer.rs#L146)):*
> ```XML
>             "gas",
>             &self.gas,
>             "An upper bound on the total gas used by block transactions",
> ```

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A6B7D7-6IrHmGfW1H:-O9ADnsu5A6UVb0osyqw:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/bouncer.rs#L152)):*
> ```XML
>             "n_steps",
>             &self.n_steps,
>             "An upper bound on the total number of steps used by block transactions",
> ```

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A5tud6LttPLZ5ZAQ6:-O9ADsBN-xEFARfriydy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/bouncer.rs#L158)):*
> ```XML
>             "message_segment_length",
>             &self.message_segment_length,
>             "An upper bound on the message segment length used by block transactions",
> ```

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A5eb67VGLco70k0-F:-O9ADvZ9BpOvsUWuKu-V:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/bouncer.rs#L164)):*
> ```XML
>             "n_events",
>             &self.n_events,
>             "An upper bound on the total number of events that occurred by the block transactions.",
> ```

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A6J1hEpjcgkTyn-yA:-O9ADy9n48FQHpXuDC0q:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/bouncer.rs#L170)):*
> ```XML
>             "state_diff_size",
>             &self.state_diff_size,
>             "An upper bound on the total state diff size used by block transactions",
> ```

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 326 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A6TNf50koTlov7Fsg:-O9AECcG5_5WecQIMcKb:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/bouncer.rs#L326)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

same line for all builtins
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/config.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O99sA6l8T89JbhgxkBO:-O9AEkOz779ORtY7-6eA:b-fgtyr1) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/blockifier/config.rs#L10)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do we need both types?
</blockquote></details>

Out of scope, can be refactored in a different PR.
___
*[`crates/blockifier/src/blockifier/config.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A78FYA0bpFgM1peFM:-O9AFAUa6AQ9BTUBgTRw:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/blockifier/config.rs#L46)):*
> ```XML
>                 "enabled",
>                 &self.enabled,
>                 "Whether to use concurrency.",
> ```

Done.
___
*[`crates/blockifier/src/blockifier/config.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A7FMEDrfg-AHHRI4y:-O9AF9BdCgy1VyR_mp9s:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/blockifier/config.rs#L52)):*
> ```XML
>                 "n_workers",
>                 &self.n_workers,
>                 "Number of workers.",
> ```

Done.
___
*[`crates/blockifier/src/blockifier/config.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9A7aSoCGbIORo6KVgV:-O9AF7bq9A3dyeT9Z-pT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b2926d6b2a53f61df2eedc32e65558350d0de362/crates/blockifier/src/blockifier/config.rs#L55)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

The size of the transaction chunk executed in parallel.
</blockquote></details>

Done.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1369)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 150 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1369#-O9DkaIe83gZfGrKN8aP:-O9E-vFF3TkXV3kC-v7v:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/69fc591e0a457a2d3a63b001aa9599b2d0d1367f/crates/blockifier/src/bouncer.rs#L150)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

lets keep this function ordered the same as the struct. (n_steps after n_events)
</blockquote></details>

Done.

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1369)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1369)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Pull request merged**
