### PR TITLE
refactor(starknet_batcher): refactor batcher test mock dependencies

### PR DESCRIPTION
**Pull request by dafnamatsry**

### CODE REVIEW

**Comment by dafnamatsry** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2307?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2307** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2307?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2307?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2297** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2297?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2279** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2279?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2307#-:-OD0GCUn5k2RMsjUFz9_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by alonh5 — APPROVED** [review]
:lgtm:

Great PR!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2307#-:-OD0aXFE0E8X3iDb48mu:bms0r5n)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 540 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2307#-OD0aLTt7r5sooCQ7rue:-OD0aLTt7r5sooCQ7ruf:bkn24wb) ([raw file](https://github.com/starkware-libs/sequencer/blob/57fb502ff7af87d34464b22366437b2f00cc6643/crates/starknet_batcher/src/batcher_test.rs#L540)):*
> ```XML
>         ..Default::default()
>     });
>     batcher.decision_reached(DecisionReachedInput { proposal_id: PROPOSAL_ID }).await.unwrap();
> ```

Also an option if you prefer it.



_Suggestion:_
```XML
    let mut mock_dependencies = MockDependencies { proposal_manager, ..Default::default() };
    mock_dependencies
        .mempool_client
        .expect_commit_block()
        .with(eq(CommitBlockArgs { address_to_nonce, tx_hashes }))
        .returning(|_| Ok(()));

    mock_dependencies
        .storage_writer
        .expect_commit_proposal()
        .with(eq(INITIAL_HEIGHT), eq(expected_state_diff))
        .returning(|_, _| Ok(()));

    let mut batcher = create_batcher(mock_dependencies);
    batcher.decision_reached(DecisionReachedInput { proposal_id: PROPOSAL_ID }).await.unwrap();
```

**Review by dafnamatsry — COMMENTED** [review]
Thanks :)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2307#-:-OD0h6hT0wG6_fw421uZ:bvtk9y9)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 540 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2307#-OD0aLTt7r5sooCQ7rue:-OD0cxpRDxOfpp10Bo0K:b-72020x) ([raw file](https://github.com/starkware-libs/sequencer/blob/57fb502ff7af87d34464b22366437b2f00cc6643/crates/starknet_batcher/src/batcher_test.rs#L540)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Also an option if you prefer it.
</blockquote></details>

Done.

Also deleted all the variables definitions in the beginning of the test, in which I think makes the test harder to read. Let me know if you prefer to revert back.

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2307)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 540 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2307#-OD0aLTt7r5sooCQ7rue:-OD0iXzy8pdUqNfPok_w:b-6akt58) ([raw file](https://github.com/starkware-libs/sequencer/blob/57fb502ff7af87d34464b22366437b2f00cc6643/crates/starknet_batcher/src/batcher_test.rs#L540)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Done.

Also deleted all the variables definitions in the beginning of the test, in which I think makes the test harder to read. Let me know if you prefer to revert back.
</blockquote></details>

Can you keep only the hashes and the nonces? Because they must be used with the same `range` values.
Another option is using a constant range inside the functions, I see they're only used in one test anyway, no need for that arg.

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2307)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 631 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2307#-OD147M-Alk8hjHDFxiu:-OD147M-Alk8hjHDFxiv:b-x04ili) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e18c09bb5139c14cb67d049d6edabfa2800b9ec/crates/starknet_batcher/src/batcher_test.rs#L631)):*
> ```XML
> fn test_contract_nonces() -> HashMap<ContractAddress, Nonce> {
>     HashMap::from_iter((0..3u8).map(|i| (contract_address!(i), nonce!(i))))
> }
> ```

It probably doesn't matter, but let's have different numbers. Sometimes when they are extremely trivial some bugs can be missed.



_Suggestion:_
```XML
fn test_tx_hashes() -> HashSet<TransactionHash> {
    (0..5u8).map(|i| tx_hash!(i+12)).collect()
}

fn test_contract_nonces() -> HashMap<ContractAddress, Nonce> {
    HashMap::from_iter((0..3u8).map(|i| (contract_address!(i+33), nonce!(i+9))))
}
```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2307)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 540 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2307#-OD0aLTt7r5sooCQ7rue:-OD0sI3tCDFHV7oRWxoF:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/57fb502ff7af87d34464b22366437b2f00cc6643/crates/starknet_batcher/src/batcher_test.rs#L540)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you keep only the hashes and the nonces? Because they must be used with the same `range` values.
Another option is using a constant range inside the functions, I see they're only used in one test anyway, no need for that arg.
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 631 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2307#-OD147M-Alk8hjHDFxiu:-OD1jELfCcqgj_RqphIV:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8e18c09bb5139c14cb67d049d6edabfa2800b9ec/crates/starknet_batcher/src/batcher_test.rs#L631)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

It probably doesn't matter, but let's have different numbers. Sometimes when they are extremely trivial some bugs can be missed.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2307)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Comment by dafnamatsry** [comment]
### Merge activity

* **Dec 2, 1:53 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2307).

**Pull request merged**
