### PR TITLE
feat(blockifier): update assert_actual_fee_in_bounds and add test

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1118)

### CODE REVIEW

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1118)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1118#-O86C8wu665X3JcPIMr_:-O86C8wu665X3JcPIMra:b5e8qfe) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4c059bba80bb0dd6478f97e8d30c473357f7381/crates/blockifier/src/transaction/account_transactions_test.rs#L190)):*
> ```XML
> #[case::positive_case_deprecated_tx(true, true)]
> #[case::positive_case_new_tx(true, false)]
> #[should_panic]
> ```

can you add the expected message?
https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html#:~:text=This%20attribute%20accepts%20optional%20parameter%20expected%20%3D%20with%20the%20text%20of%20the%20panic%20message.



_Code quote:_
```XML
#[should_panic]
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1118#-O86Dhi33C_B5IpH1NcI:-O86Dhi33C_B5IpH1NcJ:b-2rww2k) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4c059bba80bb0dd6478f97e8d30c473357f7381/crates/blockifier/src/transaction/account_transactions_test.rs#L202)):*
> ```XML
>     if deprecated_tx {
>         let tx = account_invoke_tx(invoke_tx_args! {
>             max_fee: Fee(100),
> ```

please store this in a variable



_Code quote:_
```XML
100
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 228 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1118#-O86J14U5SSkMGM0Dmk6:-O86J14U5SSkMGM0Dmk7:b-3oirye) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4c059bba80bb0dd6478f97e8d30c473357f7381/crates/blockifier/src/transaction/account_transactions_test.rs#L228)):*
> ```XML
>             let context = Arc::new(block_context.to_tx_context(&tx));
>             AccountTransaction::assert_actual_fee_in_bounds(&context, Fee(actual_fee));
>         }
> ```

IMO this is more readable - less magic numbers, more readable loop. non-blocking



_Suggestion:_
```XML
    // All resources.
        let l1_gas = ResourceBounds { max_amount: 2, max_price_per_unit: 3 };
        let l2_gas = ResourceBounds { max_amount: 4, max_price_per_unit: 5 };
        let l1_data_gas = ResourceBounds { max_amount: 6, max_price_per_unit: 7 };
        let all_resource_bounds =
            ValidResourceBounds::AllResources(AllResourceBounds { l1_gas, l2_gas, l1_data_gas });
        let all_resource_fee = l1_gas.max_amount * l1_gas.max_price_per_unit
            + l2_gas.max_amount * l2_gas.max_price_per_unit
            + l1_data_gas.max_amount * l1_data_gas.max_price_per_unit
            + actual_fee_offset;

        // L1 resources.
        let l1_resource_bounds = ValidResourceBounds::L1Gas(l1_gas);
        let l1_resource_fee = l1_gas.max_amount * l1_gas.max_price_per_unit + actual_fee_offset;

        for (bounds, actual_fee) in
            [(all_resource_bounds, all_resource_fee), (l1_resource_bounds, l1_resource_fee)]
        {
            let tx = account_invoke_tx(invoke_tx_args! {
                resource_bounds: bounds,
                version: TransactionVersion::THREE,
            });
            let context = Arc::new(block_context.to_tx_context(&tx));
            AccountTransaction::assert_actual_fee_in_bounds(&context, Fee(actual_fee));
        }
```

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1118)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 472 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1118#-O86MrrTE7IY8G4q2MKs:-O86MrrTE7IY8G4q2MKt:bcj63du) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4c059bba80bb0dd6478f97e8d30c473357f7381/crates/blockifier/src/transaction/account_transaction.rs#L472)):*
> ```XML
>         match &tx_context.tx_info {
>             TransactionInfo::Current(context) => {
>                 let max_fee = context.resource_bounds.max_possible_fee();
> ```

Talking via slack to make sure I understand



_Code quote:_
```XML
 let max_fee = context.resource_bounds.max_possible_fee();
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1118)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 472 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1118#-O86MrrTE7IY8G4q2MKs:-O86Nw0cEUg6DfIoG8Hb:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4c059bba80bb0dd6478f97e8d30c473357f7381/crates/blockifier/src/transaction/account_transaction.rs#L472)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Talking via slack to make sure I understand
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1118#-O86C8wu665X3JcPIMr_:-O86NT9T1j5Cp4h5rKHG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4c059bba80bb0dd6478f97e8d30c473357f7381/crates/blockifier/src/transaction/account_transactions_test.rs#L190)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

can you add the expected message?
https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html#:~:text=This%20attribute%20accepts%20optional%20parameter%20expected%20%3D%20with%20the%20text%20of%20the%20panic%20message.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1118#-O86Dhi33C_B5IpH1NcI:-O86Mrj1C3ctwQwAXKGd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b4c059bba80bb0dd6478f97e8d30c473357f7381/crates/blockifier/src/transaction/account_transactions_test.rs#L202)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

please store this in a variable
</blockquote></details>

Done.

**Review by amosStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1118#-:-O86_XDz6L_tu-S3MkeX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
