### PR TITLE
fix: remove &self arg from AccountTransaction::handle_fee

### PR DESCRIPTION
**Pull request by tdelabro**
fixes: https://github.com/starkware-libs/blockifier/issues/1770

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/218)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/218)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @tdelabro)

**Review by meship-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/218)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tdelabro)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/218)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tdelabro)

**Comment by tdelabro** [comment]
@meship-starkware the CI was failing, I rebased on main's latest commit. Let's see if it fixes it. Can you run the CI again please?

**Pull request closed without merging**
