### PR TITLE
feat(mempool): assert removal from the transaction queue in align to …

### PR DESCRIPTION
**Pull request by MohammadNassar1**
…state count

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/632)

### CODE REVIEW

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/632)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/632#-O5NN8xw-Si-x-K9ijGF):*
count?



_Code quote:_
```
count
```
___
*[`crates/mempool/src/mempool.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/632#-O5NNOap9569s9gNHZnK:-O5NNOap9569s9gNHZnL:b-lv9jw5) ([raw file](https://github.com/starkware-libs/sequencer/blob/8cca51d01adb7414ab57a08abf665b622788265e/crates/mempool/src/mempool.rs#L173)):*
> ```XML
>         // Note: != is equivalent to > in `add_tx`, as lower nonces are rejected in validation.
>         if self.tx_queue.get_nonce(address).is_some_and(|queued_nonce| queued_nonce != nonce) {
>             assert!(self.tx_queue.remove(address), "Expected to remove a transaction.");
> ```

Why was this assertion added?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/632)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/632#-O5NN8xw-Si-x-K9ijGF):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

count?
</blockquote></details>

typo, fixed.
___
*[`crates/mempool/src/mempool.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/632#-O5NNOap9569s9gNHZnK:-O5NRZW92ZPABnj_MGgn:bzejt4d) ([raw file](https://github.com/starkware-libs/sequencer/blob/8cca51d01adb7414ab57a08abf665b622788265e/crates/mempool/src/mempool.rs#L173)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Why was this assertion added?
</blockquote></details>

Please see the discussion [here](https://reviewable.io/reviews/starkware-libs/sequencer/482#-O57qVVY4lznL2y0WSmb).

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/632)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/632)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 173 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/632#-O5NVPDA8LEAp3ltg2Fm:-O5NVPDA8LEAp3ltg2Fn:b-t11aoz) ([raw file](https://github.com/starkware-libs/sequencer/blob/52304a3600703db365339a9ba57ed1bd3ce6cdbe/crates/mempool/src/mempool.rs#L173)):*
> ```XML
>         // Note: != is equivalent to > in `add_tx`, as lower nonces are rejected in validation.
>         if self.tx_queue.get_nonce(address).is_some_and(|queued_nonce| queued_nonce != nonce) {
>             assert!(self.tx_queue.remove(address), "Expected to remove a transaction.");
> ```

Code is clear enough here.
Whenever you're about to add any kind of non-code text you should think about whether it adds anything that can't be immediately understood from the code.



_Suggestion:_
```XML
           assert!(self.tx_queue.remove(address));
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/632)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 173 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/632#-O5NVPDA8LEAp3ltg2Fm:-O5NZswgDUnlbvlYQedW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/52304a3600703db365339a9ba57ed1bd3ce6cdbe/crates/mempool/src/mempool.rs#L173)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Code is clear enough here.
Whenever you're about to add any kind of non-code text you should think about whether it adds anything that can't be immediately understood from the code.
</blockquote></details>

Done.

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/632#-:-O5N_nsh3m02t7htMps_:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ayeletstarkware and @elintul)

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/632)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
