### PR TITLE
test(mempool): implement default for MempoolState FullState

### PR DESCRIPTION
**Pull request by ayeletstarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/102)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/102)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/102#-O2dgLRAD9eboMydNjo2:-O2dmk6d5XJVW58XJ9vo:bafnyk) ([raw file](https://github.com/starkware-libs/sequencer/blob/066d255b5651e681fb74d3a148535b9b4786ceb4/crates/mempool/src/mempool_test.rs#L106)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What happens here?
</blockquote></details>

redundant some. removed.
___
*[`crates/mempool/src/mempool_test.rs` line 257 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/102#-O2dgQQ6AAK0ohBUTiP8:-O2dmTJiBber7up6Ahlr:bcbnjlw) ([raw file](https://github.com/starkware-libs/sequencer/blob/066d255b5651e681fb74d3a148535b9b4786ceb4/crates/mempool/src/mempool_test.rs#L257)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Only location?
</blockquote></details>

For now, yes. There will be more after merging all the tests. I wrote to myself to go over and fix everything.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/102)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/102#-O2dgLRAD9eboMydNjo2:-O2dnO6TA_NsqzFyU50R:b25ut9n) ([raw file](https://github.com/starkware-libs/sequencer/blob/066d255b5651e681fb74d3a148535b9b4786ceb4/crates/mempool/src/mempool_test.rs#L106)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

redundant some. removed.
</blockquote></details>

So, what would be the default values? :)

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/102)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/102#-O2dgLRAD9eboMydNjo2:-O2doXWY7WaJP2ZkEWwI:b-j5q06w) ([raw file](https://github.com/starkware-libs/sequencer/blob/066d255b5651e681fb74d3a148535b9b4786ceb4/crates/mempool/src/mempool_test.rs#L106)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

So, what would be the default values? :)
</blockquote></details>

Sorry! hope now I got it right. 

In `tx_pool`, which is of type `TransactionPool`, both fields are hashmaps, so `tx_pool` is initialized with default hashmaps.
In `tx_queue`, which is of type `TransactionQueue`, one field is a hashmap and the other is a `BTreeSet`. Therefore, `tx_queue` is initialized with a default hashmap and a default `BTreeSet`.

We need to use `Some`, which wraps a value in an `Option`, indicating that the field has a value rather than being empty.

Here's an example of what a `MempoolState` instance look like when printed:
`MempoolState { tx_pool: Some(TransactionPool { tx_pool: {}, txs_by_account: AccountTransactionIndex({}) }), tx_queue: Some(TransactionQueue { queue: {}, address_to_tx: {} }), _phantom: PhantomData<starknet_mempool::mempool::mempool_test::FullState> }`

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/102)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/102#-O2dgLRAD9eboMydNjo2:-O2duuXs8QorIr3_G8Id:basl9sc) ([raw file](https://github.com/starkware-libs/sequencer/blob/066d255b5651e681fb74d3a148535b9b4786ceb4/crates/mempool/src/mempool_test.rs#L106)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Sorry! hope now I got it right. 

In `tx_pool`, which is of type `TransactionPool`, both fields are hashmaps, so `tx_pool` is initialized with default hashmaps.
In `tx_queue`, which is of type `TransactionQueue`, one field is a hashmap and the other is a `BTreeSet`. Therefore, `tx_queue` is initialized with a default hashmap and a default `BTreeSet`.

We need to use `Some`, which wraps a value in an `Option`, indicating that the field has a value rather than being empty.

Here's an example of what a `MempoolState` instance look like when printed:
`MempoolState { tx_pool: Some(TransactionPool { tx_pool: {}, txs_by_account: AccountTransactionIndex({}) }), tx_queue: Some(TransactionQueue { queue: {}, address_to_tx: {} }), _phantom: PhantomData<starknet_mempool::mempool::mempool_test::FullState> }`
</blockquote></details>

Thanks! 
Out of curiosity (I think this explicit version is better): what did `Some(Default::default())` previously returned?
Also, can the phantom data be removed from the struct's representation?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/102)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/102#-O2dgLRAD9eboMydNjo2:-O2e40Q1A0DddC9_cCdG:b5eroux) ([raw file](https://github.com/starkware-libs/sequencer/blob/066d255b5651e681fb74d3a148535b9b4786ceb4/crates/mempool/src/mempool_test.rs#L106)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Thanks! 
Out of curiosity (I think this explicit version is better): what did `Some(Default::default())` previously returned?
Also, can the phantom data be removed from the struct's representation?
</blockquote></details>

`Default::default` without `Some` returned None values. 
`Some(Default::defult)` returned the same example as I printed here.
I think `TransactionPool::default` is clearer than `Default::defult`.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/102#-:-O2eOTRj2lDayQDG-WP_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/102#-O2dgLRAD9eboMydNjo2:-O2eOLv7BWaPnkBMgdG2:bhfqam0) ([raw file](https://github.com/starkware-libs/sequencer/blob/066d255b5651e681fb74d3a148535b9b4786ceb4/crates/mempool/src/mempool_test.rs#L106)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

`Default::default` without `Some` returned None values. 
`Some(Default::defult)` returned the same example as I printed here.
I think `TransactionPool::default` is clearer than `Default::defult`.
</blockquote></details>

Agreed, and let's check my other Q separately from this PR.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/102)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/102#-O2dgLRAD9eboMydNjo2:-O2ePccE-hGk_xa-fFHL:b4nj5zm) ([raw file](https://github.com/starkware-libs/sequencer/blob/066d255b5651e681fb74d3a148535b9b4786ceb4/crates/mempool/src/mempool_test.rs#L106)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Agreed, and let's check my other Q separately from this PR.
</blockquote></details>

Nevermind, I think this can't be achieved without either: using an external dependency, or implmenting our customized `Debug`, which I don't want to ('cause it isn't future-proved).
Let's start using this new generic `MempoolState` while debugging, and see if and how much we'd suffer from this phantom appearing everywhere.

**Pull request merged**
