### PR TITLE
refactor(blockifier_reexecution): allow overriding chain ID explicitly

### PR DESCRIPTION
**Pull request by dorimedini-starkware**

### CODE REVIEW

**Comment by dorimedini-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1974?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1974** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1974?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1973** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1973?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1972** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1972?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1971** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1971?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1970** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1970?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dorimedini-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by AvivYossef-starkware — COMMENTED** [review]
I would also include it in the HTTP test.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1974#-:-OB_n3CqB7RlAvkBN6oN:b-lqvkpp)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
WDYM?
I added this in [the previous PR](https://reviewable.io/reviews/starkware-libs/sequencer/1973):
```
#[fixture]
pub fn test_url() -> String {
    get_test_url()
}

#[fixture]
pub fn test_chain_id(test_url: String) -> ChainId {
    guess_chain_id_from_node_url(test_url.as_str()).unwrap()
}
```

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1974#-:-OB_xxoO0UzJCkvcIYuk:b49d1dp)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
There are specific test cases from mainnet that would probably fail with another chain ID. 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1974#-:-OBts873COZm6v1xbC1x:b-9fkc66)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
which ones? I thought this was only for deserialization, deserialization should work on any chain, no?
or are you fetching specific tx hashes somewhere?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1974#-:-OBudoeo1HIl9efc7uYA:bmpjwpk)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
In the `test_get_invoke_tx_by_hash` and other tests that validate the deserialization of specific transactions.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1974#-:-OByGgWPDt9MWatrIzaR:b5l4td0)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1974#-:-OBz8aCY-2makS_bZTno:bb7f2mf)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by AvivYossef-starkware — CHANGES_REQUESTED** [review]
The ``test_get_invoke_tx_by_hash` is just an example. 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1974#-:-OBz_q9k--9iw84Q543s:b-6turtl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1974#-OBzb3Z_DDkHDgxdaUoC:-OBzb3Z_DDkHDgxdaUoD:b-vn2lew) ([raw file](https://github.com/starkware-libs/sequencer/blob/109d2538685f667fd9143a30415ffb523d6f77a5/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L51)):*
> ```XML
> const EXAMPLE_DEPLOY_ACCOUNT_V1_BLOCK_NUMBER: u64 = 837408;
> const EXAMPLE_DEPLOY_ACCOUNT_V1_TX_HASH: &str =
>     "0x02a2e13cd94f911ea18c20a81e853314e37de58d49d13aa3a92370accd4338e8";
> ```

All the transaction hashes listed here are from mainnet.

**Review by dorimedini-starkware — COMMENTED** [review]
ah, ok, then let's not support any network other than mainnet in HTTP tests - reverted the changes and added asserts

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1974#-:-OBzhCEt-DJEPLiiuOly:b-mybljv)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1974#-OBzb3Z_DDkHDgxdaUoC:-OBzhMkJ4Zpt9rTyoC9f:b-mu38mh) ([raw file](https://github.com/starkware-libs/sequencer/blob/109d2538685f667fd9143a30415ffb523d6f77a5/crates/blockifier_reexecution/src/state_reader/rpc_https_test.rs#L51)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

All the transaction hashes listed here are from mainnet.
</blockquote></details>

Done. see above

**Review by AvivYossef-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1974#-:-OC2Vr0H2BqJrdpoFBFO:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1974)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 57 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1974#-OC3tpCB746B1ElazUf4:-OC3vwB0-QiUUizOXYA6:b-gnrpcf) ([raw file](https://github.com/starkware-libs/sequencer/blob/585e7c0498374dbeff7592d585cf084cd9ebdd97/crates/blockifier_reexecution/src/main.rs#L57)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

What's the crate here? :thinking: Do you think we'll use this outside the main file?
</blockquote></details>

my mistake, fixed

**Review by aner-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1974)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
