### PR TITLE
feat(cairo_native): add synchronous sierra to native compilation flow

### PR DESCRIPTION
**Pull request by avi-starkware**

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2771)* status: all files reviewed, 6 unresolved discussions (waiting on @avi-starkware, @avivg-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2771#-OEi8ZaP6you6v8TrnlF:-OEi8ZaP6you6v8TrnlG:b-oc5dko) ([raw file](https://github.com/starkware-libs/sequencer/blob/64877193a7944c7f54c5931a86d87a4bb46abc3b/crates/blockifier/src/state/contract_class_manager.rs#L60)):*
> ```XML
>     /// The sierra-to-native compiler.
>     #[cfg(feature = "cairo_native")]
>     compiler: Option<Arc<dyn SierraToNativeCompiler>>,
> ```

Why is it an Arc? `process_compilation_request` can get a reference. 
Why do the `ContractClassManager` has to hold it in case of a compilation thread? 



_Code quote:_
```XML
    compiler: Option<Arc<dyn SierraToNativeCompiler>>,
```
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2771#-OEi5g1-EAvP13FM-6Eb:-OEi5g1-EAvP13FM-6Ec:bh1ovsv) ([raw file](https://github.com/starkware-libs/sequencer/blob/64877193a7944c7f54c5931a86d87a4bb46abc3b/crates/blockifier/src/state/contract_class_manager.rs#L104)):*
> ```XML
>             std::thread::spawn({
>                 let contract_caches = contract_caches.clone();
>                 let compiler = compiler.clone();
> ```

Why is the clone needed?



_Code quote:_
```XML
                let compiler = compiler.clone();
```
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2771#-OEi67Fh9dn0McuX2Z3M:-OEi67Fh9dn0McuX2Z3N:b2nhkyh) ([raw file](https://github.com/starkware-libs/sequencer/blob/64877193a7944c7f54c5931a86d87a4bb46abc3b/crates/blockifier/src/state/contract_class_manager.rs#L118)):*
> ```XML
> 
>     /// Sends a compilation request. Two cases:
>     /// 1. If `config.wait_on_native_compilation` is `true`, sends the request to the compilation
> ```

No?



_Suggestion:_
```XML
    /// 1. If `config.wait_on_native_compilation` is `false`, sends the request to the compilation
```
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2771#-OEi6-hM6suG3uXjikkw:-OEi6-hM6suG3uXjikkx:bdz1ko8) ([raw file](https://github.com/starkware-libs/sequencer/blob/64877193a7944c7f54c5931a86d87a4bb46abc3b/crates/blockifier/src/state/contract_class_manager.rs#L125)):*
> ```XML
>     pub fn send_compilation_request(&self, request: CompilationRequest) {
>         assert!(self.config.run_cairo_native, "Native compilation is disabled.");
>         self.cache_request_contracts(&request);
> ```

As discussed, can be deleted. 



_Code quote:_
```XML
        self.cache_request_contracts(&request);
```
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2771#-OEi70AP8frtAccA_FNw:-OEi70AP8frtAccA_FNx:brwpen1) ([raw file](https://github.com/starkware-libs/sequencer/blob/64877193a7944c7f54c5931a86d87a4bb46abc3b/crates/blockifier/src/state/contract_class_manager.rs#L137)):*
> ```XML
>         sender.try_send(request).unwrap_or_else(|err| match err {
>             TrySendError::Full((class_hash, _, _)) => {
>                 error!(
> ```

Can you please explain what this macro does? 



_Code quote:_
```XML
error!(
```
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 215 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2771#-OEi9Sog0V1nFwXdgJnE:-OEi9Sog0V1nFwXdgJnF:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/64877193a7944c7f54c5931a86d87a4bb46abc3b/crates/blockifier/src/state/contract_class_manager.rs#L215)):*
> ```XML
> fn process_compilation_request(
>     contract_caches: ContractCaches,
>     compiler: Arc<dyn SierraToNativeCompiler>,
> ```





_Suggestion:_
```XML
compiler: &impl SierraToNativeCompiler,
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2771)* status: all files reviewed, 5 unresolved discussions (waiting on @avivg-starkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2771#-OEi8ZaP6you6v8TrnlF:-OEiNJ9AAPOUR8uCvOaa:b2r029z) ([raw file](https://github.com/starkware-libs/sequencer/blob/64877193a7944c7f54c5931a86d87a4bb46abc3b/crates/blockifier/src/state/contract_class_manager.rs#L60)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it an Arc? `process_compilation_request` can get a reference. 
Why do the `ContractClassManager` has to hold it in case of a compilation thread?
</blockquote></details>

I can lose the `dyn` and give a concrete type here, or use a generic `T` implementing the trait, But if we don't want to do that, `Arc` is the only way. `Option<impl SierraToNativeCompiler>` does not work.

`Box` doesn't work since we want `ContractClassManager` to implement Clone.


Regarding the second question, the `ContractClassManager` does not need to hold the compiler in that case. I removed that.
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2771#-OEi5g1-EAvP13FM-6Eb:-OEiQNm43VT_S6eJRNVr:b-qpktu5) ([raw file](https://github.com/starkware-libs/sequencer/blob/64877193a7944c7f54c5931a86d87a4bb46abc3b/crates/blockifier/src/state/contract_class_manager.rs#L104)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is the clone needed?
</blockquote></details>

It isn't.

Removed
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2771#-OEi67Fh9dn0McuX2Z3M:-OEiQZ3hChTMbq0pZjoz:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/64877193a7944c7f54c5931a86d87a4bb46abc3b/crates/blockifier/src/state/contract_class_manager.rs#L118)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

No?
</blockquote></details>

Done
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2771#-OEi6-hM6suG3uXjikkw:-OEiQWJ72LjqqHyHA8eq:b-4znaav) ([raw file](https://github.com/starkware-libs/sequencer/blob/64877193a7944c7f54c5931a86d87a4bb46abc3b/crates/blockifier/src/state/contract_class_manager.rs#L125)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

As discussed, can be deleted.
</blockquote></details>

I am doing it in the PR unifying the caches
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2771#-OEi70AP8frtAccA_FNw:-OEiQdW5CLoK62-IczOk:bj0drih) ([raw file](https://github.com/starkware-libs/sequencer/blob/64877193a7944c7f54c5931a86d87a4bb46abc3b/crates/blockifier/src/state/contract_class_manager.rs#L137)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain what this macro does?
</blockquote></details>

It prints an error message to `stderr` using a configurable logger.
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 215 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2771#-OEi9Sog0V1nFwXdgJnE:-OEiQn2W1LkcZFb8u-vf:b-id369r) ([raw file](https://github.com/starkware-libs/sequencer/blob/64877193a7944c7f54c5931a86d87a4bb46abc3b/crates/blockifier/src/state/contract_class_manager.rs#L215)):*
> ```XML
> fn process_compilation_request(
>     contract_caches: ContractCaches,
>     compiler: Arc<dyn SierraToNativeCompiler>,
> ```

This doesn't work since we can't put the `impl SierraToNativeCompile` inside an `Option` (in the `ContractClassManager` struct)

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/state/contract_class_manager.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2771#-OEi70AP8frtAccA_FNw:-OEij9PICphwid_WRjni:b8j46xb) ([raw file](https://github.com/starkware-libs/sequencer/blob/64877193a7944c7f54c5931a86d87a4bb46abc3b/crates/blockifier/src/state/contract_class_manager.rs#L137)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

It prints an error message to `stderr` using a configurable logger.
</blockquote></details>

Should I write `log::error!()` to make it clearer?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2771)* status: all files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @avivg-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2771#-OEi8ZaP6you6v8TrnlF:-OEk2biP1mUokdHOcj6K:b-h7wu45) ([raw file](https://github.com/starkware-libs/sequencer/blob/64877193a7944c7f54c5931a86d87a4bb46abc3b/crates/blockifier/src/state/contract_class_manager.rs#L60)):*
> `Option<impl SierraToNativeCompiler>` does not work.

Can you please elaborate?
___
*[`crates/blockifier/src/state/contract_class_manager.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2771#-OEi70AP8frtAccA_FNw:-OEk2yoi6F6EjtdD2lKp:b-sv9ucz) ([raw file](https://github.com/starkware-libs/sequencer/blob/64877193a7944c7f54c5931a86d87a4bb46abc3b/crates/blockifier/src/state/contract_class_manager.rs#L137)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Should I write `log::error!()` to make it clearer?
</blockquote></details>

Oh, I see. I prefer that, but I leave it up to you.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/state/contract_class_manager.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2771#-OEi70AP8frtAccA_FNw:-OEn_6b8DiGg8i5PrfAf:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/64877193a7944c7f54c5931a86d87a4bb46abc3b/crates/blockifier/src/state/contract_class_manager.rs#L137)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Oh, I see. I prefer that, but I leave it up to you.
</blockquote></details>

Done.

**Review by meship-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2771)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @avivg-starkware, @noaov1, and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2771)* status: all files reviewed, 5 unresolved discussions (waiting on @avivg-starkware, @noaov1, and @Yoni-Starkware)

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2771)* status: all files reviewed, 2 unresolved discussions (waiting on @avivg-starkware and @Yoni-Starkware)

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2771)* status: all files reviewed, 2 unresolved discussions (waiting on @avivg-starkware and @Yoni-Starkware)

**Pull request merged**
