### PR TITLE
feat(l1_provider): implement get_txs

### PR DESCRIPTION
**Pull request by giladchase**

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2069)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/starknet_l1_provider/src/lib.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2069#-OBtAUFJ-H2MlYvfDcvw:-OBtAUFJ-H2MlYvfDcvx:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/79165cb5c5d8e4f34271f666114ebef1896ae14d/crates/starknet_l1_provider/src/lib.rs#L108)):*
> ```XML
>             .txs
>             .iter()
>             .skip(self.proposed_txs.len()) // txs are proposed FIFO.
> ```





_Suggestion:_
```XML
Transactions
```
___
*[`crates/starknet_l1_provider/src/l1_provider_tests.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2069#-OBt9dgQ53t1vT5bBFQi:-OBt9dgR6y1qbUa8N1dt:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/79165cb5c5d8e4f34271f666114ebef1896ae14d/crates/starknet_l1_provider/src/l1_provider_tests.rs#L33)):*
> ```XML
>         awaiting_l2_inclusion.len(),
>         n_txs,
>         "txs given to this constructor should have unique hashes."
> ```





_Suggestion:_
```XML
Transactions
```
___
*[`crates/starknet_l1_provider/src/l1_provider_tests.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2069#-OBtA1FG91GNja9hLlko:-OBtA1FG91GNja9hLlkp:b-mo7001) ([raw file](https://github.com/starkware-libs/sequencer/blob/79165cb5c5d8e4f34271f666114ebef1896ae14d/crates/starknet_l1_provider/src/l1_provider_tests.rs#L48)):*
> ```XML
>     let mut l1_provider = l1_provider(txs.clone());
>     l1_provider.proposal_start().unwrap();
> ```

Consider adding small util functions, as we have for mampool API, with next tests.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2069)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`crates/starknet_l1_provider/src/l1_provider_tests.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2069#-OBtA1FG91GNja9hLlko:-OBtYpaS3K5kQRPTY9zB:b-97ngsz) ([raw file](https://github.com/starkware-libs/sequencer/blob/79165cb5c5d8e4f34271f666114ebef1896ae14d/crates/starknet_l1_provider/src/l1_provider_tests.rs#L48)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider adding small util functions, as we have for mampool API, with next tests.
</blockquote></details>

For sure.
Wasn't sure yet what functionality they need, so was planning on creating them (and removing this boilerplate) once I also have validate and commit test up (which will be very soon hopefully)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2069)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/starknet_l1_provider/src/lib.rs` line 109 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2069#-OBtb_MICbo-DOrN7rb4:-OBtb_MICbo-DOrN7rb5:bxztp5h) ([raw file](https://github.com/starkware-libs/sequencer/blob/42d0ad9dec0670d2f4f88e89c6c0f6f68e09277c/crates/starknet_l1_provider/src/lib.rs#L109)):*
> ```XML
>             .take(n_txs)
>             .map(|(&hash, tx)| (hash, tx.clone()))
>             .unzip();
> ```

Beautiful!



_Code quote:_
```XML
        let (tx_hashes, txs): (Vec<_>, Vec<_>) = self
            .txs
            .iter()
            .skip(self.proposed_txs.len()) // Transactions are proposed FIFO.
            .take(n_txs)
            .map(|(&hash, tx)| (hash, tx.clone()))
            .unzip();
```
___
*[`crates/starknet_l1_provider/src/lib.rs` line 115 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2069#-OBtbzal23a3ZTflIWQf:-OBtbzam89falbWxukRn:b-4nnzrs) ([raw file](https://github.com/starkware-libs/sequencer/blob/42d0ad9dec0670d2f4f88e89c6c0f6f68e09277c/crates/starknet_l1_provider/src/lib.rs#L115)):*
> ```XML
>     }
> 
>     pub fn _add_unconsumed_l1_not_in_l2_block_tx(&mut self, _tx: L1HandlerTransaction) {
> ```

Can you explain at what part of the flow is this method called?



_Code quote:_
```XML
_add_unconsumed_l1_not_in_l2_block_tx
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2069)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/starknet_l1_provider/src/lib.rs` line 109 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2069#-OBtb_MICbo-DOrN7rb4:-OBtd2HaATF7DEIgx8Ig:b2x9v3l) ([raw file](https://github.com/starkware-libs/sequencer/blob/42d0ad9dec0670d2f4f88e89c6c0f6f68e09277c/crates/starknet_l1_provider/src/lib.rs#L109)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Beautiful!
</blockquote></details>

:blush: 
___
*[`crates/starknet_l1_provider/src/lib.rs` line 115 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2069#-OBtbzal23a3ZTflIWQf:-OBtd9FEAOxFKlGebpUv:bw12b47) ([raw file](https://github.com/starkware-libs/sequencer/blob/42d0ad9dec0670d2f4f88e89c6c0f6f68e09277c/crates/starknet_l1_provider/src/lib.rs#L115)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you explain at what part of the flow is this method called?
</blockquote></details>

Yep, it's part of the L1-scraping flow:
1) scraper parses a Tx from L1
2) scraper creaetes an L1HandlerTransaction from it (for example calculates a tx_hash in order to do so)
3) passes the Tx to the method you wrote, which (as of now) is intended to still do what's written in the `todo!`

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2069)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/starknet_l1_provider/src/lib.rs` line 115 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2069#-OBtbzal23a3ZTflIWQf:-OBtmh3qDDg1zZ8IP0kQ:bfjsvta) ([raw file](https://github.com/starkware-libs/sequencer/blob/42d0ad9dec0670d2f4f88e89c6c0f6f68e09277c/crates/starknet_l1_provider/src/lib.rs#L115)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Yep, it's part of the L1-scraping flow:
1) scraper parses a Tx from L1
2) scraper creaetes an L1HandlerTransaction from it (for example calculates a tx_hash in order to do so)
3) passes the Tx to the method you wrote, which (as of now) is intended to still do what's written in the `todo!`
</blockquote></details>

Okay, thanks. 
So the check whether the transaction was already seen, is for idempotency, right?

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2069#-:-OBtr6qHDRtmej3S9L_c:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2069)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

**Pull request merged**
