### PR TITLE
feat(sequencing): broadcast proposal in a stream

### PR DESCRIPTION
**Pull request by guy-starkware**
This PR adds the ability to broadcast a new proposal from Consensus, using the streamed channel.

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 17 files at r1, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2286)* status: 10 of 20 files reviewed, 3 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 84 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2286#-OD0BffnARoBGKx3C8hf:-OD0BffnARoBGKx3C8hg:b47z7p1) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a6c34c660e94002baf751e51d13c96468c424fd/crates/starknet_integration_tests/src/utils.rs#L84)):*
> ```XML
>         create_network_config_connected_to_broadcast_channels(
>             papyrus_network::gossipsub_impl::Topic::new(
>                 // TODO(guyn): return this to NETWORK_TOPIC once we have integrated streaming.
> ```

Are you sure? I think what we want is to add the Vote channel in addition to this streaming one.



_Code quote:_
```XML
                // TODO(guyn): return this to NETWORK_TOPIC once we have integrated streaming.
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 335 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2286#-OD09g2v7pSddY2zW3TE:-OD09g2v7pSddY2zW3TF:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a6c34c660e94002baf751e51d13c96468c424fd/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L335)):*
> ```XML
>                 );
>                 debug!("Broadcasting proposal fin: {proposal_content_id:?}");
>                 println!("Broadcasting proposal fin: {proposal_content_id:?}");
> ```





_Suggestion:_
```XML
                debug!("Broadcasting proposal fin: {proposal_content_id:?}");
```
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 98 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2286#-OD0Bv9d9Gx2URgHU57v:-OD0Bv9d9Gx2URgHU57w:b-rcyknj) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a6c34c660e94002baf751e51d13c96468c424fd/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L98)):*
> ```XML
>             }
>             // Ignore this, in case it comes out of the network before some of the other messages.
>             StreamMessageBody::Fin => (),
> ```

Why is this OK? don't we want to check that after Content(Fin) is sent that Stream::Fin is sent? So here this is unexpected, and then after the loop we want to assert this is received?



_Code quote:_
```XML
            // Ignore this, in case it comes out of the network before some of the other messages.
            StreamMessageBody::Fin => (),
```

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2286)* status: 10 of 20 files reviewed, 4 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 79 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2286#-OD0CjBy-GPs3-moOgnt:-OD0CjBy-GPs3-moOgnu:b-au5a78) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a6c34c660e94002baf751e51d13c96468c424fd/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L79)):*
> ```XML
>         broadcasted_messages_receiver.next().await.unwrap().0.unwrap().message,
>         StreamMessageBody::Content(ProposalPart::Init(expected_proposal_init))
>     );
> ```

I think we should get the stream_id from this and assert all messages have this stream_id



_Code quote:_
```XML
    assert_eq!(
        broadcasted_messages_receiver.next().await.unwrap().0.unwrap().message,
        StreamMessageBody::Content(ProposalPart::Init(expected_proposal_init))
    );
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2286)* status: 3 of 20 files reviewed, 4 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 84 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2286#-OD0BffnARoBGKx3C8hf:-OD0GkAJDlxj5ApO3Y8J:b-5iqi6o) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a6c34c660e94002baf751e51d13c96468c424fd/crates/starknet_integration_tests/src/utils.rs#L84)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Are you sure? I think what we want is to add the Vote channel in addition to this streaming one.
</blockquote></details>

Yes, this is not related to the voting channel. This is only for the channels that go into Context. 
Since I've left the "old plumbing" for passing proposals, there are two NETWORK_TOPICs right now, but we will get rid of the old one soon. 
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 79 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2286#-OD0CjBy-GPs3-moOgnt:-OD0IIW9-JEZqJiywzn8:b-xmam17) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a6c34c660e94002baf751e51d13c96468c424fd/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L79)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I think we should get the stream_id from this and assert all messages have this stream_id
</blockquote></details>

Good idea. I'm also checking that the first message has message_id zero. 
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 98 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2286#-OD0Bv9d9Gx2URgHU57v:-OD0IobU8ZNBg2AHvKtl:b4zotq8) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a6c34c660e94002baf751e51d13c96468c424fd/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L98)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why is this OK? don't we want to check that after Content(Fin) is sent that Stream::Fin is sent? So here this is unexpected, and then after the loop we want to assert this is received?
</blockquote></details>

Yeah, this is a little confusing. 
I can reorganize this to make sure we get both different fins. 
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 335 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2286#-OD09g2v7pSddY2zW3TE:-OD0GCjW045VwijDlqh1:b-ople7v) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a6c34c660e94002baf751e51d13c96468c424fd/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L335)):*
> ```XML
>                 );
>                 debug!("Broadcasting proposal fin: {proposal_content_id:?}");
>                 println!("Broadcasting proposal fin: {proposal_content_id:?}");
> ```

Thanks! Removed.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 17 files at r1, 1 of 7 files at r8, 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2286)* status: all files reviewed, 2 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 84 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2286#-OD0BffnARoBGKx3C8hf:-OD0UOy89SdAo4H2MJk1:b-apd91i) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a6c34c660e94002baf751e51d13c96468c424fd/crates/starknet_integration_tests/src/utils.rs#L84)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

Yes, this is not related to the voting channel. This is only for the channels that go into Context. 
Since I've left the "old plumbing" for passing proposals, there are two NETWORK_TOPICs right now, but we will get rid of the old one soon.
</blockquote></details>

Add a TODO that we need to add the vote channels also
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 116 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2286#-OD0XqdK1piC800pY6Fs:-OD0XqdL1SnHqmBMgsNA:bi5p6g2) ([raw file](https://github.com/starkware-libs/sequencer/blob/0271cd9ab236fe6963511c1e237fa5d6a10c93e0/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L116)):*
> ```XML
>             break;
>         }
>     }
> ```

My biggest issue is that I don't like the variables in the loop. I think that they order expected can just be represented in the tests structure. 
- Init
- Loop
- Fin



_Suggestion:_
```XML
    // Must be const since `assert_matches` ignores variables.
    const INCOMING_STREAM_ID: u64 = 0;
    assert_eq!(
        broadcasted_messages_receiver.next().await.unwrap().0.unwrap(),
        StreamMessage {
            stream_id: INCOMING_STREAM_ID,
            message_id: 0, // Init must be the first message.
            message: StreamMessageBody::Content(ProposalPart::Init(expected_proposal_init))
        }
    );

    loop {
        let message = broadcasted_messages_receiver.next().await.unwrap().0.unwrap();
        assert_eq!(message.stream_id, INCOMING_STREAM_ID);
        match message.message {
            StreamMessageBody::Content(ProposalPart::Fin(proposal_fin)) => {
                assert_eq!(proposal_fin, expected_proposal_fin);
                break;
            }
            StreamMessageBody::Content(ProposalPart::Transactions(transactions)) => {
                received_tx_hashes.extend(
                    transactions
                        .transactions
                        .iter()
                        .map(|tx| tx.calculate_transaction_hash(&chain_id).unwrap()),
                );
            }
            _ => panic!("Unexpected message: {:?}", message),
        }
    }
    assert_matches!(
        broadcasted_messages_receiver.next().await.unwrap().0.unwrap(),
        StreamMessage {
            stream_id: INCOMING_STREAM_ID,
            message_id: _,
            message: StreamMessageBody::Fin,
        }
    );
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2286)* status: all files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 84 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2286#-OD0BffnARoBGKx3C8hf:-OD0hXCG4zHbIzmk9JHm:b-tgt3wb) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a6c34c660e94002baf751e51d13c96468c424fd/crates/starknet_integration_tests/src/utils.rs#L84)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Add a TODO that we need to add the vote channels also
</blockquote></details>

If I understand this test correctly, it isn't supposed to include the votes. Those go into Consensus. These channels go straight into the Context. I'm not sure where the votes go into the Consensus but it wasn't through this part. 
___
*[`crates/starknet_integration_tests/tests/end_to_end_flow_test.rs` line 116 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/2286#-OD0XqdK1piC800pY6Fs:-OD0jBPSBaV-CmriQKd4:b-1gnbl3) ([raw file](https://github.com/starkware-libs/sequencer/blob/0271cd9ab236fe6963511c1e237fa5d6a10c93e0/crates/starknet_integration_tests/tests/end_to_end_flow_test.rs#L116)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

My biggest issue is that I don't like the variables in the loop. I think that they order expected can just be represented in the tests structure. 
- Init
- Loop
- Fin
</blockquote></details>

This is much nicer, but... I'm not sure the stream ID would be 0 (it can be a lot of things, in general, and it wouldn't even remain a single number for much longer). 
Also, I've confirmed that the `StreamMessage::Fin` comes before the `ProposalPart::Fin` (I'm not sure if this is random order or just the way it comes from the test all the time). So this is a weird test that waits for things to arrive in a weird order. 

Let me try to do something more clear.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 16 files at r13, 5 of 7 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2286)* status: 8 of 20 files reviewed, 1 unresolved discussion (waiting on @guy-starkware)

___
*[`crates/starknet_integration_tests/src/utils.rs` line 84 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2286#-OD0BffnARoBGKx3C8hf:-OD1qMZa1hK5O71bm-iJ:bow9jtd) ([raw file](https://github.com/starkware-libs/sequencer/blob/1a6c34c660e94002baf751e51d13c96468c424fd/crates/starknet_integration_tests/src/utils.rs#L84)):*
<details><summary><i>Previously, guy-starkware wrote…</i></summary><blockquote>

If I understand this test correctly, it isn't supposed to include the votes. Those go into Consensus. These channels go straight into the Context. I'm not sure where the votes go into the Consensus but it wasn't through this part.
</blockquote></details>

Yes, the test doesn't yet have votes because we don't yet support them... Consensus will need a receiver to receive votes, and the context will need a sender to broadcast votes when we want to support this.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 10 of 16 files at r13, 7 of 7 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2286)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Pull request merged**
