### PR TITLE
chore(cairo_native): grow the stack to handle overflows

### PR DESCRIPTION
**Pull request by Yoni-Starkware**

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODezeNvD64OfEMTiEe0:-ODezeNvD64OfEMTiEe1:bp036fp) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/native/entry_point_execution.rs#L59)):*
> ```XML
>     let stack_size_red_zone = 160 * 1024 * 1024;
>     let target_stack_size = stack_size_red_zone + 10 * 1024 * 1024;
>     let execution_result = stacker::maybe_grow(stack_size_red_zone, target_stack_size, || {
> ```

maybe_grow because of nested calls?



_Code quote:_
```XML
 stacker::maybe_grow(
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2563)* status: all files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODf1jAN2Lt_1bXb8icL:-ODf1jAO60oZe1BIf5VS:b-y2eueb) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L55)):*
> ```XML
> 
>     let depth = felt!(1000000_u128);
>     // TODO(Aner): assert that the total tx limits are <= 3500M gas.
> ```

WDYM? V+E? or the "infinite" gas limit?



_Code quote:_
```XML
// TODO(Aner): assert that the total tx limits are <= 3500M gas.
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODf224u4kDl3cGr0_o0:-ODf224vEshwrOU_Bjnu:biq5ul8) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L56)):*
> ```XML
>     let depth = felt!(1000000_u128);
>     // TODO(Aner): assert that the total tx limits are <= 3500M gas.
>     let max_initial_gas_for_sierra_mode = 3_500_000_000; // Equivalent to 35M steps.
> ```

I prefer you set `max_steps = 35_000_000` and multiply by the gas-per-step field of the VC



_Code quote:_
```XML
let max_initial_gas_for_sierra_mode = 3_500_000_000; // Equivalent to 35M steps.
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODf1CM38HIYrDc6EBhm:-ODf1CM38HIYrDc6EBhn:b-1uxexv) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/native/entry_point_execution.rs#L47)):*
> ```XML
>     // (unlike the VM where the stack is simulated in the heap as a memory segment).
>     //
>     // We pre-allocate the stack here, and not during Native execution (technichal issue), so it
> ```

elaborate?



_Code quote:_
```XML
(technichal issue)
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODf1Hui6a5Ns9uZzxfc:-ODf1Hui6a5Ns9uZzxfd:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/native/entry_point_execution.rs#L50)):*
> ```XML
>     // needs to be big enough ahead.
>     // However, making it very big is wasteful (especially with multi-threading).
>     // So, the stack size should support calls with a reasonable gas limit, for extreamly deep
> ```





_Suggestion:_
```XML
extremely
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODf1NhIB4yOTqg2M1fJ:-ODf1NhIB4yOTqg2M1fK:b3l1ql4) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/native/entry_point_execution.rs#L58)):*
> ```XML
>     // TODO(Aviv/Yonatan): add these numbers to overridable VC.
>     let stack_size_red_zone = 160 * 1024 * 1024;
>     let target_stack_size = stack_size_red_zone + 10 * 1024 * 1024;
> ```

1. name these constants, make them public
2. add a test that enforces some sanity between the versioned constants max gas limits and the stack size constants - to prevent mistakes in the future



_Code quote:_
```XML
    let stack_size_red_zone = 160 * 1024 * 1024;
    let target_stack_size = stack_size_red_zone + 10 * 1024 * 1024;
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2563)* status: all files reviewed, 6 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, @ilyalesokhin-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODf1CM38HIYrDc6EBhm:-ODf3-qGEKZR_-KpRepm:btfnr7r) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/native/entry_point_execution.rs#L47)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

elaborate?
</blockquote></details>

It's not trivial, IDK if possible. Need to wrap every function call (not contract call).
Out of our scope
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODf1NhIB4yOTqg2M1fJ:-ODf3P6WDLzgxHrZMHI6:byituq5) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/native/entry_point_execution.rs#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. name these constants, make them public
2. add a test that enforces some sanity between the versioned constants max gas limits and the stack size constants - to prevent mistakes in the future
</blockquote></details>

These numbers should come from the VC - see the TODO.
@aner-starkware should restrict the max gas configs, and use it in my test. This would do.
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODezeNvD64OfEMTiEe0:-ODf3dUN0uFx52HKRG2p:b-ssx88a) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/native/entry_point_execution.rs#L59)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

maybe_grow because of nested calls?
</blockquote></details>

Right, in happy flows only the main call should trigger the growth.
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODf1jAN2Lt_1bXb8icL:-ODf42qI3qaajBTzC5P3:b-a0jylw) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L55)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYM? V+E? or the "infinite" gas limit?
</blockquote></details>

V+E, note the `sierra_mod`.
The infinite runs only in CS mode
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODf224u4kDl3cGr0_o0:-ODf4owaEVQTdjZ5GH9r:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L56)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I prefer you set `max_steps = 35_000_000` and multiply by the gas-per-step field of the VC
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODf1Hui6a5Ns9uZzxfc:-ODf3-FqAgOfCkHPl6K9:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/native/entry_point_execution.rs#L50)):*
> ```XML
>     // needs to be big enough ahead.
>     // However, making it very big is wasteful (especially with multi-threading).
>     // So, the stack size should support calls with a reasonable gas limit, for extreamly deep
> ```

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2563)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware, @ilyalesokhin-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODf1NhIB4yOTqg2M1fJ:-ODf9xA74Byx5flMkrOf:b-l1jsq4) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/native/entry_point_execution.rs#L58)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

These numbers should come from the VC - see the TODO.
@aner-starkware should restrict the max gas configs, and use it in my test. This would do.
</blockquote></details>

you are saying the stack sizes here depend on the max gas bounds?
in what way?
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODfACMW9tR-BjtJ6mTl:-ODfACMW9tR-BjtJ6mTm:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f8e30dbceb6c59e615a90e13ae5b911e3c15334/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L57)):*
> ```XML
>     // TODO(Aner): assert that the total tx limits are <= 3500M gas.
>     let max_n_steps_for_sierra_mode = 35_000_000;
>     let max_initial_gas_for_sierra_mode = max_n_steps_for_sierra_mode * 100;
> ```





_Suggestion:_
```XML
VersionedConstants::latest().gas_per_step
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2563)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, @ilyalesokhin-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODf1NhIB4yOTqg2M1fJ:-ODfKup99HWSbQ4iyp-h:b-yigs3t) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/native/entry_point_execution.rs#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you are saying the stack sizes here depend on the max gas bounds?
in what way?
</blockquote></details>

Empirically. I set a limit of 35M steps, and tested the required stack size to support recursions that need more than 35M steps to reach the bottom.
```
    // So, the stack size should support calls with a reasonable gas limit, for extremely deep
    // recursions to reach out-of-gas before hitting the bottom of the recursion.
```

After @aner-starkware will add the gas limit to VC and use it in my test, the test should fail when increasing the limit (should reach overflow)
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODfACMW9tR-BjtJ6mTl:-ODfKmAR0LCqBZUtCmCM:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2f8e30dbceb6c59e615a90e13ae5b911e3c15334/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L57)):*
> ```XML
>     // TODO(Aner): assert that the total tx limits are <= 3500M gas.
>     let max_n_steps_for_sierra_mode = 35_000_000;
>     let max_initial_gas_for_sierra_mode = max_n_steps_for_sierra_mode * 100;
> ```

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2563)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODf1NhIB4yOTqg2M1fJ:-ODfS-nuC8K5htS6HSa4:b3896yn) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/native/entry_point_execution.rs#L58)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Empirically. I set a limit of 35M steps, and tested the required stack size to support recursions that need more than 35M steps to reach the bottom.
```
    // So, the stack size should support calls with a reasonable gas limit, for extremely deep
    // recursions to reach out-of-gas before hitting the bottom of the recursion.
```

After @aner-starkware will add the gas limit to VC and use it in my test, the test should fail when increasing the limit (should reach overflow)
</blockquote></details>

what I'm asking for is a definition of `f(max_validate, max_execute)`, the function that should return the target stack size.
even after aner adds the bounds I don't understand the exact relation between these bounds (100M, 1000M) and your "gas" limit (3500M)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2563)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, @ilyalesokhin-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODf1NhIB4yOTqg2M1fJ:-ODfSzdED7NTs6PqYAtd:bvf0ezd) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/native/entry_point_execution.rs#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what I'm asking for is a definition of `f(max_validate, max_execute)`, the function that should return the target stack size.
even after aner adds the bounds I don't understand the exact relation between these bounds (100M, 1000M) and your "gas" limit (3500M)
</blockquote></details>

Add an assertion in my test: `assert V+E <= max_initial_gas_for_sierra_mode`

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2563)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, @ilyalesokhin-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODf1NhIB4yOTqg2M1fJ:-ODfVnS7C1kX3eOACEav:buhr8od) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/native/entry_point_execution.rs#L58)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Add an assertion in my test: `assert V+E <= max_initial_gas_for_sierra_mode`
</blockquote></details>

I don't want to commit to a function `f(max_validate, max_execute)`; 
my claim is that my test passes with gas limit M; make sure you don't allow higher limits.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2563)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @ilyalesokhin-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODf1NhIB4yOTqg2M1fJ:-ODftLxJ9kJMCJDFmza9:bj5py3j) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/native/entry_point_execution.rs#L58)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I don't want to commit to a function `f(max_validate, max_execute)`; 
my claim is that my test passes with gas limit M; make sure you don't allow higher limits.
</blockquote></details>

ok, so if M is defined without context, please make a named constant of M so it's clear.
if it depends on VC (i.e. gas per step) please make it a function of the VC.
I'll make sure it's tested
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODf1jAN2Lt_1bXb8icL:-ODftb4w9uAZuD-9-3Id:b-11ns24) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/syscalls/syscall_tests/out_of_gas.rs#L55)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

V+E, note the `sierra_mod`.
The infinite runs only in CS mode
</blockquote></details>

@aner-starkware FYI

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2563)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @dorimedini-starkware, @ilyalesokhin-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODf1NhIB4yOTqg2M1fJ:-ODg8exH8FtUabgB3Phs:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7eb25e66a364e869074b6904dff2f14d8dca917/crates/blockifier/src/execution/native/entry_point_execution.rs#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ok, so if M is defined without context, please make a named constant of M so it's clear.
if it depends on VC (i.e. gas per step) please make it a function of the VC.
I'll make sure it's tested
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2563)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 58 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODjbmoA5tvd2lIGvi7n:-ODjbmoA5tvd2lIGvi7o:bfqqulr) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7454d6cc133c6c727bbe98dd9678ead9e31f29f/crates/blockifier/src/execution/native/entry_point_execution.rs#L58)):*
> ```XML
>     // TODO(Aviv/Yonatan): add these numbers to overridable VC.
>     let stack_size_red_zone = 160 * 1024 * 1024;
>     let target_stack_size = stack_size_red_zone + 10 * 1024 * 1024;
> ```

these numbers have no relation to the MAX_POSSIBLE_SIERRA_GAS?



_Code quote:_
```XML
    // TODO(Aviv/Yonatan): add these numbers to overridable VC.
    let stack_size_red_zone = 160 * 1024 * 1024;
    let target_stack_size = stack_size_red_zone + 10 * 1024 * 1024;
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-:-ODjc2Ed6-4JJQ9UMNLZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware and @noaov1)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2563)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 58 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2563#-ODjbmoA5tvd2lIGvi7n:-ODjeDFy8idzrtjRBFIl:b-qi3mt8) ([raw file](https://github.com/starkware-libs/sequencer/blob/d7454d6cc133c6c727bbe98dd9678ead9e31f29f/crates/blockifier/src/execution/native/entry_point_execution.rs#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

these numbers have no relation to the MAX_POSSIBLE_SIERRA_GAS?
</blockquote></details>

They have, but I am afraid of playing with them. 
The relation might change with new Sierra/native compiler versions. I'll add to Monday to consider it

**Pull request merged**
