### PR TITLE
chore(blockifier): remove entry point gas cost from versioned constan…

### PR DESCRIPTION
**Pull request by Yonatan-Starkware**
…ts jsons

### CODE REVIEW

**Comment by avi-starkware** [comment]
Why is this needed?

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2132#-:-OBzClq1BObfMgGrRc5f:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware and @meship-starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2132)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yonatan-Starkware)

**Comment by Yonatan-Starkware** [comment]
* **#2132** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2132?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2132?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2132)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @Yonatan-Starkware and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_0_13_4.json` line 641 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2132#-OC2OMfsAhpN6haBDhUc:-OC2OMft24bme_UbxDHA:b-uzhriq) ([raw file](https://github.com/starkware-libs/sequencer/blob/7459837fbf1396d93a87520c13313aaf3b4dcf99/crates/blockifier/resources/versioned_constants_0_13_4.json#L641)):*
> ```JSON
>         ]
>     }
> }
> ```

Add a new line at the end of the file. 



_Code quote:_
```JSON
}
```
___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/deploy.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2132#-OC2O_Ql6PeRREOhV-vX:-OC2O_Ql6PeRREOhV-vY:b2vfbl7) ([raw file](https://github.com/starkware-libs/sequencer/blob/7459837fbf1396d93a87520c13313aaf3b4dcf99/crates/blockifier/src/execution/syscalls/syscall_tests/deploy.rs#L20)):*
> ```XML
> #[cfg_attr(
>     feature = "cairo_native",
>     test_case(FeatureContract::TestContract(CairoVersion::Native), 215310;"Native")
> ```

Note to self: After fixing the native gas cost, see if they are the same (except the 10k known issue)



_Code quote:_
```XML
ve), 215310;"Native")
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/cairo_native` line 1 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2132#-OC2VngU4xKTT9hy1wUh:-OC2VngU4xKTT9hy1wUi:b-cd79pv) ([raw file](https://github.com/starkware-libs/sequencer/blob/822aed034d7ad0fceb1bc5bd186815a10dbe2554/crates/blockifier/cairo_native#L1)):*
> ```
> Subproject commit 564f7e2136e53a1e43033aefa3836b4dc591ffc1
> ```

This shouldn't change.

To fix, run
```git submodule update --init --recursive```



_Code quote:_
```
Subproject commit 564f7e2136e53a1e43033aefa3836b4dc591ffc1
```

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 1 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2132)* status: 10 of 15 files reviewed, 3 unresolved discussions (waiting on @meship-starkware, @Yonatan-Starkware, and @Yoni-Starkware)

**Review by avi-starkware — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 3 of 7 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2132)* status: all files reviewed, 3 unresolved discussions (waiting on @Yonatan-Starkware)

**Comment by Yonatan-Starkware** [comment]
### Merge activity

* **Nov 28, 3:52 AM EST**: [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2132) disabled "merge when ready" on this PR due to: a merge conflict with the target branch; resolve the conflict and try again..

**Review by meship-starkware — APPROVED** [review]
Please fetch and rebase this PR. It has conflicts  

> Reviewed 1 of 7 files at r2, 5 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2132#-:-OCmO3JHA0Kdr33YXxLF:b-i2a0ww)* status: all files reviewed, 1 unresolved discussion (waiting on @Yonatan-Starkware)

**Pull request closed without merging**
