### PR TITLE
chore(consensus): use non zero validator id in consensus config

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#2550** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2550?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2549** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2549?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2549?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2549)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2549#-ODefvfZ-AXJfZCGwASz:-ODefvfZ-AXJfZCGwAT-:b-pgctve) ([raw file](https://github.com/starkware-libs/sequencer/blob/5f9e909e699d7bb60bbbf2d8e4575cf544de496f/crates/sequencing/papyrus_consensus/src/manager_test.rs#L44)):*
> ```XML
>     static ref VALIDATOR_ID: ValidatorId = 101_u32.into();
>     static ref VALIDATOR_ID_2: ValidatorId = 102_u32.into();
>     static ref VALIDATOR_ID_3: ValidatorId = 103_u32.into();
> ```

Use here also?



_Code quote:_
```XML
    static ref VALIDATOR_ID: ValidatorId = 101_u32.into();
    static ref VALIDATOR_ID_2: ValidatorId = 102_u32.into();
    static ref VALIDATOR_ID_3: ValidatorId = 103_u32.into();
```

**Comment by ArniStarkware** [comment]
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2549#-ODefvfZ-AXJfZCGwASz:-ODelD12AtHAsANg-jeI:b-enkprl) ([raw file](https://github.com/starkware-libs/sequencer/blob/5f9e909e699d7bb60bbbf2d8e4575cf544de496f/crates/sequencing/papyrus_consensus/src/manager_test.rs#L44)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Use here also?
</blockquote></details>

as in `DEFAULT_VALIDATOR_ID + 1`?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2549)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2549#-ODefvfZ-AXJfZCGwASz:-ODf6-hQDus__V28mmys:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/5f9e909e699d7bb60bbbf2d8e4575cf544de496f/crates/sequencing/papyrus_consensus/src/manager_test.rs#L44)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

as in `DEFAULT_VALIDATOR_ID + 1`?
</blockquote></details>

Done.

**Comment by ArniStarkware** [comment]
### Merge activity

* **Dec 9, 9:55 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2549).

**Pull request merged**
