### PR TITLE
feat(mempool): get txs return requested txs after replenishing queue

### PR DESCRIPTION
**Pull request by ayeletstarkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/91)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/91)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/91#-O2dRoYQ7rePO_tOkvp5:-O2dRoYQ7rePO_tOkvp6:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/56dcbfea6df1943da0456721b06d44895d12140f/crates/mempool/src/mempool.rs#L174)):*
> ```XML
>     }
> 
>     fn enqueue_next_eligible_txs(&mut self, txs: &Vec<TransactionReference>) -> MempoolResult<()> {
> ```





_Suggestion:_
```XML
&[TransactionReference]
```
___
*[`crates/mempool/src/mempool_test.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/91#-O2dRrwb2qPnOgv-AVgY:-O2dRrwb2qPnOgv-AVgZ:b-yngdz9) ([raw file](https://github.com/starkware-libs/sequencer/blob/56dcbfea6df1943da0456721b06d44895d12140f/crates/mempool/src/mempool_test.rs#L188)):*
> ```XML
> 
>     let queue_txs = [TransactionReference::new(&tx_nonce_0)];
>     let pool_txs = [tx_nonce_0.clone(), tx_nonce_1.clone(), tx_nonce_2.clone()];
> ```

`map`, please. Throughout the file.



_Code quote:_
```XML
[tx_nonce_0.clone(), tx_nonce_1.clone(), tx_nonce_2.clone()];
```

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/91)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 246 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/91#-O2dkW1q3nIObByFzuqH:-O2dkW1q3nIObByFzuqI:bhev15q) ([raw file](https://github.com/starkware-libs/sequencer/blob/069a5ca6b1bdfbd853e699d5d3c17f003009865e/crates/mempool/src/mempool_test.rs#L246)):*
> ```XML
> 
>     // Assert: all transactions are returned.
>     assert_eq!(fetched_txs, &pool_txs);
> ```

Use `with_pool` and the corresponding comparison?



_Code quote:_
```XML
assert_eq!(fetched_txs, &pool_txs);
```
___
*[`crates/mempool/src/mempool_test.rs` line 247 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/91#-O2dkReAEv-LTGjYDiIj:-O2dkReAEv-LTGjYDiIk:b1k8ds5) ([raw file](https://github.com/starkware-libs/sequencer/blob/069a5ca6b1bdfbd853e699d5d3c17f003009865e/crates/mempool/src/mempool_test.rs#L247)):*
> ```XML
>     // Assert: all transactions are returned.
>     assert_eq!(fetched_txs, &pool_txs);
>     let expected_mempool_state = MempoolState::new([], []);
> ```

`::default`?



_Code quote:_
```XML
MempoolState::new([], []);
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/91)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 246 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/91#-O2dkW1q3nIObByFzuqH:-O2dnLjv72No9_ejpD-R:b-yjrpdk) ([raw file](https://github.com/starkware-libs/sequencer/blob/069a5ca6b1bdfbd853e699d5d3c17f003009865e/crates/mempool/src/mempool_test.rs#L246)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Use `with_pool` and the corresponding comparison?
</blockquote></details>

we check the total state. I think it's better to change the variable name. 
___
*[`crates/mempool/src/mempool_test.rs` line 247 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/91#-O2dkReAEv-LTGjYDiIj:-O2dnE_j0ROS6p--os3-:bc4iu9b) ([raw file](https://github.com/starkware-libs/sequencer/blob/069a5ca6b1bdfbd853e699d5d3c17f003009865e/crates/mempool/src/mempool_test.rs#L247)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`::default`?
</blockquote></details>

was not merged yet.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/91)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 246 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/91#-O2dkW1q3nIObByFzuqH:-O2duai8EsC9EamI99RK:b-yhdfh5) ([raw file](https://github.com/starkware-libs/sequencer/blob/069a5ca6b1bdfbd853e699d5d3c17f003009865e/crates/mempool/src/mempool_test.rs#L246)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

we check the total state. I think it's better to change the variable name.
</blockquote></details>

WDYM? 
___
*[`crates/mempool/src/mempool_test.rs` line 247 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/91#-O2dkReAEv-LTGjYDiIj:-O2duUc4CYpFqQ-k5yGS:b-lhqk4a) ([raw file](https://github.com/starkware-libs/sequencer/blob/069a5ca6b1bdfbd853e699d5d3c17f003009865e/crates/mempool/src/mempool_test.rs#L247)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

was not merged yet.
</blockquote></details>

It can be, right?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/91)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 246 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/91#-O2dkW1q3nIObByFzuqH:-O2e5o2XBup3tMm9NE56:b-la9m53) ([raw file](https://github.com/starkware-libs/sequencer/blob/069a5ca6b1bdfbd853e699d5d3c17f003009865e/crates/mempool/src/mempool_test.rs#L246)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

We check the entire state here, both pool and queue, so using `with_pool` may be misleading.
___
*[`crates/mempool/src/mempool_test.rs` line 247 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/91#-O2dkReAEv-LTGjYDiIj:-O2e5d0gDY_w8B0UEdYj:bq0ufin) ([raw file](https://github.com/starkware-libs/sequencer/blob/069a5ca6b1bdfbd853e699d5d3c17f003009865e/crates/mempool/src/mempool_test.rs#L247)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It can be, right?
</blockquote></details>

not yet. I have a task to go over all tests and replace them when the default PR is merged.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/91)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool_test.rs` line 246 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/91#-O2dkW1q3nIObByFzuqH:-O2eOi34Eq1LCYw1OEqP:bvj02p4) ([raw file](https://github.com/starkware-libs/sequencer/blob/069a5ca6b1bdfbd853e699d5d3c17f003009865e/crates/mempool/src/mempool_test.rs#L246)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

We check the entire state here, both pool and queue, so using `with_pool` may be misleading.
</blockquote></details>

Sorry, my bad. You're right.
___
*[`crates/mempool/src/mempool_test.rs` line 247 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/91#-O2dkReAEv-LTGjYDiIj:-O2eOU3K60xBrm-8qT8y:btb1rw2) ([raw file](https://github.com/starkware-libs/sequencer/blob/069a5ca6b1bdfbd853e699d5d3c17f003009865e/crates/mempool/src/mempool_test.rs#L247)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

not yet. I have a task to go over all tests and replace them when the default PR is merged.
</blockquote></details>

I LGTM-ed, it can be merged and used here; you call on the order.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/91#-:-O2eOlyv9j064mFx87IR:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

**Pull request merged**
