### PR TITLE
chore(blockifier): use test_utils::invoke_tx() instead of trans::test_utils::account_invoke_tx()

### PR DESCRIPTION
**Pull request by avivg-starkware**

### CODE REVIEW

**Comment by avivg-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2428?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2413** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2413?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2354** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2354?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2428** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2428?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2428?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2412** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2412?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2377** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2377?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2331** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2331?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2428)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 593 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2428#-ODC0ALL10wNyl5Y7DOr:-ODC0ALM0XdHIxCASZIS:b39j5pz) ([raw file](https://github.com/starkware-libs/sequencer/blob/bac51a07f79e5f51dbe7a6db79e9ccc60c86f875/crates/blockifier/src/transaction/execution_flavors_test.rs#L593)):*
> ```XML
>         calldata: recurse_calldata(test_contract_address, true, 3),
>         nonce: nonce_manager.next(account_address),
>         only_query,
> ```

Do we still need this on InvokeTxArgs?



_Code quote:_
```XML
        only_query,
```

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2428)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2428)* status: 3 of 5 files reviewed, all discussions resolved

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 593 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2428#-ODC0ALL10wNyl5Y7DOr:-ODC0vlR9TT5YbfmRVdf:blyvobo) ([raw file](https://github.com/starkware-libs/sequencer/blob/bac51a07f79e5f51dbe7a6db79e9ccc60c86f875/crates/blockifier/src/transaction/execution_flavors_test.rs#L593)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Do we still need this on InvokeTxArgs?
</blockquote></details>

Non-blocking, let it be for now

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2428)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2428#-ODC174gAV5c-nUIimQW:-ODC174gAV5c-nUIimQX:b7oocry) ([raw file](https://github.com/starkware-libs/sequencer/blob/bac51a07f79e5f51dbe7a6db79e9ccc60c86f875/crates/blockifier/src/transaction/test_utils.rs#L297)):*
> ```XML
>     let only_query = invoke_args.only_query;
>     AccountTransaction { tx: invoke_tx(invoke_args), only_query }
> }
> ```

So, can you delete this now?



_Code quote:_
```XML
pub fn account_invoke_tx(invoke_args: InvokeTxArgs) -> AccountTransaction {
    let only_query = invoke_args.only_query;
    AccountTransaction { tx: invoke_tx(invoke_args), only_query }
}
```

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2428)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 593 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2428#-ODC0ALL10wNyl5Y7DOr:-ODC8-0f0_B_fygOdTbY:b-8oifqx) ([raw file](https://github.com/starkware-libs/sequencer/blob/bac51a07f79e5f51dbe7a6db79e9ccc60c86f875/crates/blockifier/src/transaction/execution_flavors_test.rs#L593)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Non-blocking, let it be for now
</blockquote></details>

It seems like it is still used. 
though strangely,  I created a PR removing it and it works. 
I need to look into this. 
my source of confusion is that test_account_flow_test doesn't fail although info is lost after the removal of only_query from invoke_tx_args

link to code: 
https://github.com/starkware-libs/sequencer/blob/ccb5c8dabc54c5c99dca78d6cad455fda2588808/crates/blockifier/src/transaction/account_transactions_test.rs#L314

PR:
#2437 
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 297 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2428#-ODC174gAV5c-nUIimQW:-ODC1hOgBvAOqUxlCYZC:bcmdj6p) ([raw file](https://github.com/starkware-libs/sequencer/blob/bac51a07f79e5f51dbe7a6db79e9ccc60c86f875/crates/blockifier/src/transaction/test_utils.rs#L297)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

So, can you delete this now?
</blockquote></details>

this is my intention. It is still used quite a lot in the code. added a TODO.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2428#-:-ODCPGEdB9_Sv4EuMixA:bnfp4nl)* status: 3 of 5 files reviewed, all discussions resolved

**Review by avivg-starkware — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2428)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Pull request merged**
