### PR TITLE
feat: add display impl for StreamMessage

### PR DESCRIPTION
**Pull request by guy-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1071)

### CODE REVIEW

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1071)* status: all files reviewed, 2 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/papyrus_protobuf/src/consensus.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1071#-O7wsq9R66Dp-3_op0wq:-O7wsq9S2ZTOgIaUw5bP:b-vnu7az) ([raw file](https://github.com/starkware-libs/sequencer/blob/cdde30ccd1cc0d3030869bb0cb8cf98ceb2b976a/crates/papyrus_protobuf/src/consensus.rs#L58)):*
> ```XML
> impl<T: Clone + Into<Vec<u8>> + TryFrom<Vec<u8>, Error = ProtobufConversionError>> std::fmt::Display
>     for StreamMessage<T>
> {
> ```

switch to a where clause



_Code quote:_
```XML
impl<T: Clone + Into<Vec<u8>> + TryFrom<Vec<u8>, Error = ProtobufConversionError>> std::fmt::Display
    for StreamMessage<T>
{
```
___
*[`crates/papyrus_protobuf/src/consensus.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1071#-O7wszpB8lCkm_I4S4_p:-O7wszpB8lCkm_I4S4_q:b709kvo) ([raw file](https://github.com/starkware-libs/sequencer/blob/cdde30ccd1cc0d3030869bb0cb8cf98ceb2b976a/crates/papyrus_protobuf/src/consensus.rs#L65)):*
> ```XML
>             "StreamMessage {{ message: {:?}, stream_id: {}, message_id: {}, fin: {} }}",
>             message, self.stream_id, self.message_id, self.fin
>         )
> ```

This looks like the exact same as Debug, why add this?

If you want something different I'd recommend switching from dumping message in Display to putting it's length. The dump is more appropriate for Debug



_Code quote:_
```XML
        write!(
            f,
            "StreamMessage {{ message: {:?}, stream_id: {}, message_id: {}, fin: {} }}",
            message, self.stream_id, self.message_id, self.fin
        )
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1071)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/papyrus_protobuf/src/consensus.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1071#-O7wsq9R66Dp-3_op0wq:-O7wxHBq5Pvsy4WXrLAk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cdde30ccd1cc0d3030869bb0cb8cf98ceb2b976a/crates/papyrus_protobuf/src/consensus.rs#L58)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

switch to a where clause
</blockquote></details>

Done.
___
*[`crates/papyrus_protobuf/src/consensus.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1071#-O7wszpB8lCkm_I4S4_p:-O7wxI9X2AB1kQv-KhOY:b-rxp0ue) ([raw file](https://github.com/starkware-libs/sequencer/blob/cdde30ccd1cc0d3030869bb0cb8cf98ceb2b976a/crates/papyrus_protobuf/src/consensus.rs#L65)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

This looks like the exact same as Debug, why add this?

If you want something different I'd recommend switching from dumping message in Display to putting it's length. The dump is more appropriate for Debug
</blockquote></details>

Good point. I will do the length instead of the contents. 
Also, this will be nice to have two display options when the messages have an enum that is either Fin or Content. I'll add a todo to fix that once that is merged.

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1071)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/papyrus_protobuf/src/consensus.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1071#-O7xYJS7CRic7CX8pAiU:-O7xYJS7CRic7CX8pAiV:b-hmaf4u) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d8212251281556db01d0e0f1dba3f166faa607d/crates/papyrus_protobuf/src/consensus.rs#L64)):*
> ```XML
>         // TODO(guyn): add option to display when message is Fin and doesn't have content (PR #1048)
>         write!(
>             f,
> ```

Why this instead of write_fmt + format_args? (IDK display that well so not recommend, just asking)



_Code quote:_
```XML
        write!(
            f,
```
___
*[`crates/papyrus_protobuf/src/consensus.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1071#-O7xXXMN7JgR8HV0xVZt:-O7xXXMN7JgR8HV0xVZu:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d8212251281556db01d0e0f1dba3f166faa607d/crates/papyrus_protobuf/src/consensus.rs#L70)):*
> ```XML
>             message.len(),
>             self.fin
>         )
> ```





_Suggestion:_
```XML
        write!(
            f,
            "StreamMessage {{ stream_id: {}, message_id: {}, message_length: {}, fin: {} }}",
            self.stream_id,
            self.message_id,
            message.len(),
            self.fin
        )
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1071)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/papyrus_protobuf/src/consensus.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1071#-O7xYJS7CRic7CX8pAiU:-O7xc-nL8ygtvPe3w05M:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8d8212251281556db01d0e0f1dba3f166faa607d/crates/papyrus_protobuf/src/consensus.rs#L64)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Why this instead of write_fmt + format_args? (IDK display that well so not recommend, just asking)
</blockquote></details>

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1071)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1071#-:-O8ag3Z3Bj-l0FbnHUe0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1071)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @guy-starkware and @matan-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 154 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1071#-O8jzisj3ASACjFBXIdx:-O8jzisj3ASACjFBXIdy:b3gzirk) ([raw file](https://github.com/starkware-libs/sequencer/blob/8faddca54ac13c3b2efe0d706f69074b0efe9353/crates/papyrus_protobuf/src/converters/consensus_test.rs#L154)):*
> ```XML
>     let mut rng = get_rng();
>     let stream_id = rng.gen_range(0..100);
>     let message_id = rng.gen_range(0..1000);
> ```

Why is it random?



_Code quote:_
```XML
    let mut rng = get_rng();
    let stream_id = rng.gen_range(0..100);
    let message_id = rng.gen_range(0..1000);
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1071)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/papyrus_protobuf/src/converters/consensus_test.rs` line 154 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1071#-O8jzisj3ASACjFBXIdx:-O8kI0lI8EPhN4nNCV-1:bj74wlt) ([raw file](https://github.com/starkware-libs/sequencer/blob/8faddca54ac13c3b2efe0d706f69074b0efe9353/crates/papyrus_protobuf/src/converters/consensus_test.rs#L154)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why is it random?
</blockquote></details>

removed randomness.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1071)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

**Review by guy-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1071)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

**Pull request merged**
