### PR TITLE
chore(deployment): ensure python3.10 installation

### PR DESCRIPTION
**Pull request by idan-starkware**

### CODE REVIEW

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2769)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @idan-starkware)

___
*[`.github/workflows/deployment.yml` line 30 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2769#-OETBe2r97aq8DJlXq8k:-OETBe2r97aq8DJlXq8l:b-7ze2so) ([raw file](https://github.com/starkware-libs/sequencer/blob/4083b004892be57c2b26acb278576caef2b6fe3c/.github/workflows/deployment.yml#L30)):*
> ```YAML
>       - uses: actions/setup-python@v5
>         with:
>           python-version: 'pypy3.10'
> ```

why?
we using pypy only in very special places 



_Code quote:_
```YAML
      - uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.10'
```

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2769)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @idan-starkware)

___
*[`.github/workflows/deployment.yml` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2769#-OETBrdlAZfgPp382JKY:-OETBrdlAZfgPp382JKZ:b-gvj4b3) ([raw file](https://github.com/starkware-libs/sequencer/blob/4083b004892be57c2b26acb278576caef2b6fe3c/.github/workflows/deployment.yml#L47)):*
> ```YAML
>           cd deployments/sequencer
>           pipenv install
>           cdk8s synth --app "pipenv run python main.py --namespace sequencer-node"
> ```

why mixing this in this PR?



_Code quote:_
```YAML
 cdk8s synth --app "pipenv run python main.py --namespace sequencer-node"
```

**Comment by idan-starkware** [comment]
*[`.github/workflows/deployment.yml` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2769#-OETBrdlAZfgPp382JKY:-OETD5Xd3Zmf7N-FLZ98:bxw3rxq) ([raw file](https://github.com/starkware-libs/sequencer/blob/4083b004892be57c2b26acb278576caef2b6fe3c/.github/workflows/deployment.yml#L47)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

why mixing this in this PR?
</blockquote></details>

Its important for the fix to align with references

**Review by idan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2769)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware and @idan-starkware)

___
*[`.github/workflows/deployment.yml` line 30 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2769#-OETBe2r97aq8DJlXq8k:-OETDIiEDSWv0zPcVIqH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4083b004892be57c2b26acb278576caef2b6fe3c/.github/workflows/deployment.yml#L30)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

why?
we using pypy only in very special places
</blockquote></details>

Done.

**Review by alon-dotan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2769)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @idan-starkware)

___
*[`.github/workflows/deployment.yml` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2769#-OETBrdlAZfgPp382JKY:-OETDdOU20aUnxAGrtJW:b5kt6o4) ([raw file](https://github.com/starkware-libs/sequencer/blob/4083b004892be57c2b26acb278576caef2b6fe3c/.github/workflows/deployment.yml#L47)):*
<details><summary><i>Previously, idan-starkware (Idan Shamam) wrote…</i></summary><blockquote>

Its important for the fix to align with references
</blockquote></details>

it failes the CI?

**Comment by idan-starkware** [comment]
*[`.github/workflows/deployment.yml` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2769#-OETBrdlAZfgPp382JKY:-OEhUKik8e-9zOWrtpxv:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4083b004892be57c2b26acb278576caef2b6fe3c/.github/workflows/deployment.yml#L47)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

it failes the CI?
</blockquote></details>

Done.

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2769#-:-OEhVE448kWtYDGs6PC0:bnfp4nl)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @idan-starkware)

**Review by idan-starkware — COMMENTED** [review]
> Reviewed 1 of 8 files at r4, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2769)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @idan-starkware)

**Pull request merged**
