### PR TITLE
chore(starknet_integration_tests): use available ports for state sync

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #2796
- #2795
- #2794
- #2789 ⬅
- #2788
- #2787
- #2786
- #2781
- #2780

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2789#-:-OETaaMhBXCZQbtITFlI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2789)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2789)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#2796](https://github.com/starkware-libs/sequencer/pull/2796)

**Pull request closed without merging**
