### PR TITLE
chore(infra): canonicalize path resolution

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #2270
- #2266
- #2265
- #2264
- #2255
- #2254 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2254)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/infra_utils/src/path.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2254#-OCYEy9b28AqDLP4E9hA:-OCYEy9b28AqDLP4E9hB:b8nxy1h) ([raw file](https://github.com/starkware-libs/sequencer/blob/7dd34cec791e6fdf540ec37bc314fa0856efd8d4/crates/infra_utils/src/path.rs#L17)):*
> ```XML
>     #[error(transparent)]
>     IoError(#[from] std::io::Error),
> }
> ```

Should we delete this error variant and use `std::io::Error as IOError` throughout?



_Code quote:_
```XML
#[derive(Debug, Error)]
pub enum PathResolutionError {
    /// This error is raised when the file path does not exist, or when a non-final component in a
    /// path is not a directory. See [`std::fs::canonicalize`] for more information.
    #[error(transparent)]
    IoError(#[from] std::io::Error),
}
```
___
*[`crates/infra_utils/src/path_test.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2254#-OCYFFmB6tgwNimMZPUZ:-OCYFFmB6tgwNimMZPU_:bzcq08m) ([raw file](https://github.com/starkware-libs/sequencer/blob/7dd34cec791e6fdf540ec37bc314fa0856efd8d4/crates/infra_utils/src/path_test.rs#L3)):*
> ```XML
> use crate::path::{path_of_project_root, resolve_project_relative_path};
> 
> // TODO: Add a test for PathResolutionError::IoError.
> ```

Delete this TODO.

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2254)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/infra_utils/src/path_test.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2254#-OCYKWYEEFZ7aWPb7JKR:-OCYKWYF0f4phv4CoPfN:b-2k10aq) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d734ebd8988fe6f8d60f5d15b3523d8f394cd90/crates/infra_utils/src/path_test.rs#L10)):*
> ```XML
>     let result = resolve_project_relative_path(relative_path);
> 
>     assert!(result.is_err(), "Expected an non-existent path error, got {:?}", result);
> ```

Or is this an overkill?



_Suggestion:_
```XML
assert_eq!(result.unwrap_err().display(), "File not fount", "Expected an non-existent path error, got {:?}", result);
```

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2254#-:-OCYLAg8EOIz4qPnWCU8:bnfp4nl)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#2264](https://github.com/starkware-libs/sequencer/pull/2264)

**Pull request closed without merging**
