### PR TITLE
feat(starknet_state_sync): implement sync state reader get storage at

### PR DESCRIPTION
**Pull request by noamsp-starkware**

### CODE REVIEW

**Comment by noamsp-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2755?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2755** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2755?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2755?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2754** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2754?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2662** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2662?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2537** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2537?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2538](https://github.com/starkware-libs/sequencer/pull/2538) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2538?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2531** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2531?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2515** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2515?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2755)* status: 8 of 10 files reviewed, 5 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/starknet_state_sync/src/lib.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2755#-OETSHJ43H1L9iY_Xphx:-OETSHJ43H1L9iY_Xphy:b-gm36si) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbd9226abe127404e6f140a941cd77a1c48b9bb2/crates/starknet_state_sync/src/lib.rs#L95)):*
> ```XML
>             state_reader
>                 .get_class_hash_at(state_number, &contract_address)?
>                 .ok_or(StateSyncError::ContractAddressNotFoundError(contract_address))?;
> ```

This should return Ok(None) instead, right?
___
*[`crates/starknet_state_sync/src/lib.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2755#-OETRF6A0JKsuLWRPJDk:-OETRF6A0JKsuLWRPJDl:bsvuhlk) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbd9226abe127404e6f140a941cd77a1c48b9bb2/crates/starknet_state_sync/src/lib.rs#L102)):*
> ```XML
> }
> 
> fn verify_block_number<Mode: TransactionKind>(
> ```

Rename to verify_synced_up_to
___
*[`crates/starknet_state_sync/src/lib.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2755#-OETSDJI1fExBXNTLos0:-OETS3t02OfVtQNkpjVV:bde9a9y) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbd9226abe127404e6f140a941cd77a1c48b9bb2/crates/starknet_state_sync/src/lib.rs#L112)):*
> ```XML
>     }
> 
>     Err(StateSyncError::StorageError(format!("Block number {} not found", block_number)))
> ```

This should return an option, not result
___
*[`crates/blockifier/src/state/errors.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2755#-OETPD1W5Mo0Jtp3WjK6:-OETPD1W5Mo0Jtp3WjK7:b-sqapbl) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbd9226abe127404e6f140a941cd77a1c48b9bb2/crates/blockifier/src/state/errors.rs#L34)):*
> ```XML
>     StarknetApiError(#[from] StarknetApiError),
>     #[error(transparent)]
>     StateSyncClientError(#[from] StateSyncClientError),
> ```

You shouldn't change blockifier in your work. You should use the StateReadError below
___
*[`crates/starknet_state_sync_types/src/errors.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2755#-OETSNRQ4e5iXPoOB2Y0:-OETSNRQ4e5iXPoOB2Y1:b4qb19a) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbd9226abe127404e6f140a941cd77a1c48b9bb2/crates/starknet_state_sync_types/src/errors.rs#L11)):*
> ```XML
>     RunnerCommunicationError,
>     #[error("Contract address {0} was not found")]
>     ContractAddressNotFoundError(ContractAddress),
> ```

Remove this error and return None instead

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2755)* status: all files reviewed, 5 unresolved discussions (waiting on @noamsp-starkware)

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2755)* status: 5 of 10 files reviewed, 5 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/starknet_state_sync/src/lib.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2755#-OETSHJ43H1L9iY_Xphx:-OETcvYX8Og_iXMOMFuY:bg7xmjf) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbd9226abe127404e6f140a941cd77a1c48b9bb2/crates/starknet_state_sync/src/lib.rs#L95)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This should return Ok(None) instead, right?
</blockquote></details>

Spoke offline. Decided it's better to keep contract address and block number not found errors to differentiate between both scenarios.
___
*[`crates/starknet_state_sync/src/lib.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2755#-OETRF6A0JKsuLWRPJDk:-OETcv6H7IjO702qT0ft:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbd9226abe127404e6f140a941cd77a1c48b9bb2/crates/starknet_state_sync/src/lib.rs#L102)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename to verify_synced_up_to
</blockquote></details>

Done.
___
*[`crates/starknet_state_sync/src/lib.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2755#-OETSDJI1fExBXNTLos0:-OETdVXt506DymEguiwe:bnj7hl0) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbd9226abe127404e6f140a941cd77a1c48b9bb2/crates/starknet_state_sync/src/lib.rs#L112)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This should return an option, not result
</blockquote></details>

same as above
___
*[`crates/starknet_state_sync_types/src/errors.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2755#-OETSNRQ4e5iXPoOB2Y0:-OETdeSNAoFQ9qu-D44w:bnj7hl0) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbd9226abe127404e6f140a941cd77a1c48b9bb2/crates/starknet_state_sync_types/src/errors.rs#L11)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this error and return None instead
</blockquote></details>

same as above
___
*[`crates/blockifier/src/state/errors.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2755#-OETPD1W5Mo0Jtp3WjK6:-OETdgys7sLGYkkt2WiE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/cbd9226abe127404e6f140a941cd77a1c48b9bb2/crates/blockifier/src/state/errors.rs#L34)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You shouldn't change blockifier in your work. You should use the StateReadError below
</blockquote></details>

Done.

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 4 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2755)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @noamsp-starkware)

**Comment by noamsp-starkware** [comment]
### Merge activity

* **Dec 22, 3:18 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2755).

**Review by noamsp-starkware — COMMENTED** [review]
> Dismissed @graphite-app[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2755)* status: 6 of 10 files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by ShahakShama — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2755#-:-OEirUSe-Y7aFr43nTLb:bnfp4nl)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @noamsp-starkware)

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2755)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noamsp-starkware)

**Pull request merged**
