### PR TITLE
chore(native_blockifier): convert general config to os config

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/561)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/561)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 407 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/561#-O57rakt1PPQ_CP6tPAw:-O57rakuCpYuPJu_rq3d:b49q6m6) ([raw file](https://github.com/starkware-libs/sequencer/blob/df672bc5a755e00cf30232464de6268082e78904/crates/native_blockifier/src/py_block_executor.rs#L407)):*
> ```XML
>         path: std::path::PathBuf,
>         max_state_diff_size: usize,
>     ) -> Self {
> ```

Turns out this was passed to `PyValidator` & `PyBlockExecutor`, just never used.
`validate_max_n_steps` was also passed `PyGeneralConfig` and not used (but it was also passed by 'PyVersionedConstantsOverrides' and used. this duplication was not added by me, BTW)



_Suggestion:_
```XML
    pub invoke_tx_max_n_steps: u32
```

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware +reviewer:@Yonatan-Starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/561#-:-O58VdFa3Erc9NYQHNOV:b8blj49)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yonatan-Starkware)

**Review by amosStarkware — COMMENTED** [review]
-reviewer:@Yonatan-Starkware +reviewer:@Yoni-Starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/561#-:-O58Vs837Tx2NyXxXlVo:bo31y3m)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/561#-:-O5909E44RxMkynEy3Ez:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 407 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/561#-O57rakt1PPQ_CP6tPAw:-O5909h95phWCeBvPuiM:b-wgiaj1) ([raw file](https://github.com/starkware-libs/sequencer/blob/df672bc5a755e00cf30232464de6268082e78904/crates/native_blockifier/src/py_block_executor.rs#L407)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Turns out this was passed to `PyValidator` & `PyBlockExecutor`, just never used.
`validate_max_n_steps` was also passed `PyGeneralConfig` and not used (but it was also passed by 'PyVersionedConstantsOverrides' and used. this duplication was not added by me, BTW)
</blockquote></details>

I don't see these highlighted lines here, what are you referring to?

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/561)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 407 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/561#-O57rakt1PPQ_CP6tPAw:-O5C_NDq8-DdbnyjtdoF:b36knax) ([raw file](https://github.com/starkware-libs/sequencer/blob/df672bc5a755e00cf30232464de6268082e78904/crates/native_blockifier/src/py_block_executor.rs#L407)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't see these highlighted lines here, what are you referring to?
</blockquote></details>

to the fields `PyGeneralConfig::invoke_tx_max_n_steps`, `PyGeneralConfig::validate_max_n_steps` (which I deleted)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/561)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Pull request merged**
