### PR TITLE
refactor(mempool): call rpc_deploy_account_tx from StarknetAPI

### PR DESCRIPTION
**Pull request by noam-starkware**

### CODE REVIEW

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2136#-:-OC2WeQL6kAjwJGh6s4f:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noam-starkware)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2136)* status: all files reviewed, 1 unresolved discussion (waiting on @noam-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2136#-OC33_Yi0wRppG1ZoVXj:-OC33_Yi0wRppG1ZoVXk:b-rcbpu6) (no related file):*
No logic changes here too, right? Only code move.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2136)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noam-starkware)

**Review by noam-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2136)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2136#-OC33_Yi0wRppG1ZoVXj:-OC8tAhL3HbtmOL7EX3-:baypkx4) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No logic changes here too, right? Only code move.
</blockquote></details>

Yes, only code move.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2136)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noam-starkware)

**Pull request merged**
