### PR TITLE
chore(blockifier): update cairo submodule to tagged commit

### PR DESCRIPTION
**Pull request by PearsonWhite**
#1854 updated cairo native submodule to 26e1c67966b93acd8b183823aae6f3e4fdc5c78c instead of 564f7e2136e53a1e43033aefa3836b4dc591ffc1 (v0.2.1-alpha.0). This change points the native submodule to the tagged commit in main.

### CODE REVIEW

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1947)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PearsonWhite)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1947)* status: all files reviewed, 1 unresolved discussion (waiting on @PearsonWhite)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1947#-OBZ_LRt8nMryFQbBPZA:-OBZ_LRt8nMryFQbBPZB:b-fr3ooa) (no related file):*
Please resolve conflicts so we can merge

**Review by meship-starkware — COMMENTED** [review]
> Dismissed @graphite-app[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1947)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @PearsonWhite and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1947)* status: all files reviewed, 1 unresolved discussion (waiting on @PearsonWhite and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1947)* status: all files reviewed, 1 unresolved discussion (waiting on @PearsonWhite and @Yoni-Starkware)

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1947)* status: all files reviewed, 1 unresolved discussion (waiting on @PearsonWhite and @Yoni-Starkware)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1947)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1947#-:-OBfDEj30oJ_ca_iXXA7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PearsonWhite)

**Pull request merged**
