### PR TITLE
feat(gateway): add validation for empty account_deployment_data and paymaster_data

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
* **#1938** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1938?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1938)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @alonh5 and @noaov1)

___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1938#-OBQBZw_CZx3khuKy4JX:-OBQBZw_CZx3khuKy4JY:biy1hoa) ([raw file](https://github.com/starkware-libs/sequencer/blob/936e71da9ee485e645cd8e4f022e59390b7a7e01/crates/gateway/src/stateless_transaction_validator.rs#L72)):*
> ```XML
> 
>     /// The Starknet OS enforces that the deployer data is empty. We add this validation here at the
>     /// gateway to prevent transaction revert.
> ```

Grammarly suggests:



_Suggestion:_
```XML
    /// The Starknet OS enforces that the deployer data is empty. We added this validation here
    /// at the gateway to prevent a transaction from reverting.
```

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1938#-:-OBQOMLRAYbKGGzhd1by:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @noaov1)

___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1938#-OBQNxeH0z76q8SB66bO:-OBQNxeH0z76q8SB66bP:b32wzj) ([raw file](https://github.com/starkware-libs/sequencer/blob/936e71da9ee485e645cd8e4f022e59390b7a7e01/crates/gateway/src/stateless_transaction_validator.rs#L72)):*
> ```XML
> 
>     /// The Starknet OS enforces that the deployer data is empty. We add this validation here at the
>     /// gateway to prevent transaction revert.
> ```

x2



_Suggestion:_
```XML
transactions from reverting
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1938)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @alonh5 and @noaov1)

___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1938#-OBQNxeH0z76q8SB66bO:-OBQPD8_85E-dsJLASxG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/936e71da9ee485e645cd8e4f022e59390b7a7e01/crates/gateway/src/stateless_transaction_validator.rs#L72)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

x2
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1938)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
