### PR TITLE
feat(blockifier): add entry point execution logic for native

### PR DESCRIPTION
**Pull request by rodrigo-pino**
This is a newer version of #622 (which was a copy of #551) with addressed comments and updated git history.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1158)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 7 files at r3, 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1158)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 104 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8_eK9hCgzPPoO7X_vm:-O8_eK9hCgzPPoO7X_vn:bizmps1) ([raw file](https://github.com/starkware-libs/sequencer/blob/beab11aed32f216bfe81f776344a05872b58ec02/crates/blockifier/src/execution/native/entry_point_execution.rs#L104)):*
> ```XML
>             n_memory_holes: 0,
>             builtin_instance_counter: HashMap::default(),
>         },
> ```

I am not sure all zero is what we want here @noaov1 WDYT? Maybe the estimated value of the versioned constants will be a better 
solution. Anyway, I think this is outside of PR's scope.    



_Code quote:_
```XML
        // todo(rodrigo): execution resources rely heavily on how the VM work, therefore
        // the dummy values
        resources: ExecutionResources {
            n_steps: 0,
            n_memory_holes: 0,
            builtin_instance_counter: HashMap::default(),
        },
```

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1158)* status: all files reviewed, 1 unresolved discussion (waiting on @rodrigo-pino)

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 4 of 5 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1158)* status: all files reviewed, 1 unresolved discussion (waiting on @rodrigo-pino)

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1158)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 104 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8_eK9hCgzPPoO7X_vm:-O8iGk4nB4Hr9GGmP9E-:b-bzp505) ([raw file](https://github.com/starkware-libs/sequencer/blob/beab11aed32f216bfe81f776344a05872b58ec02/crates/blockifier/src/execution/native/entry_point_execution.rs#L104)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I am not sure all zero is what we want here @noaov1 WDYT? Maybe the estimated value of the versioned constants will be a better 
solution. Anyway, I think this is outside of PR's scope.
</blockquote></details>

If this is non-blocking maybe we can open an issue and continue with the mergin' of this PR?

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r4, 1 of 5 files at r8, 1 of 1 files at r10, 1 of 2 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1158)* status: all files reviewed, 6 unresolved discussions (waiting on @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 36 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8uGYDy6LKSxSwnS0R_:-O8uGYDz8WLeeYJgqmAb:bve1f2o) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L36)):*
> ```XML
>         resources,
>         context,
>     );
> ```

I suggest having the `call` as a field of the syscall handler (non-blocking and should be done in a separate PR).



_Code quote:_
```XML
    let syscall_handler: NativeSyscallHandler<'_> = NativeSyscallHandler::new(
        state,
        call.caller_address,
        call.storage_address,
        call.entry_point_selector,
        resources,
        context,
    );
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 58 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8uD-MO1-mmONc4FiIj:-O8uD-MO1-mmONc4FiIk:b-4kqevk) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L58)):*
> ```XML
>             Err(EntryPointExecutionError::NativeUnexpectedError { source: runner_err })
>         }
>         Ok(res) if res.failure_flag => Err(EntryPointExecutionError::NativeExecutionError {
> ```

And then you don't need to dcode. We currently return `Vec<Felt>`.
See [here](https://github.com/starkware-libs/sequencer/blob/876810d9da9902dffd187f0cf5ba02b10bad6dc4/crates/blockifier/src/execution/entry_point_execution.rs#L109).



_Suggestion:_
```XML
Err(EntryPointExecutionError::ExecutionFailed {
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 68 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8uFeOVDyHJmhm_XNT0:-O8uFeOVDyHJmhm_XNT1:b-su55uh) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L68)):*
> ```XML
>     }?;
> 
>     create_callinfo(call.clone(), run_result, syscall_handler)
> ```

Is the clone needed?



_Suggestion:_
```XML
    create_callinfo(call, run_result, syscall_handler)
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 85 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8uFlWd-lH89SYgheME:-O8uFlWd-lH89SYgheMF:b-7zi8ni) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L85)):*
> ```XML
>                 info: "Overflow: gas consumed bigger than 64 bit".into(),
>             });
>         }
> ```

WDYT?



_Suggestion:_
```XML
    let gas_consumed = gas.to_u64().ok_or(PostExecutionError::MalformedReturnData {
        error_message: format!("Unexpected remaining gas: {gas}."),
    })?;
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 86 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8uFuhO3GfsAaH2OVdJ:-O8uFuhO3GfsAaH2OVdK:bxf30ow) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L86)):*
> ```XML
>             });
>         }
>         call.initial_gas - low
> ```

What will happen in case `low > call.initial_gas`



_Code quote:_
```XML
call.initial_gas - low
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 104 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8uGOZq27-PjK0IM19N:-O8uGOZr1BZzBlQtwUya:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L104)):*
> ```XML
>             n_memory_holes: 0,
>             builtin_instance_counter: HashMap::default(),
>         },
> ```





_Suggestion:_
```XML
        resources: ExecutionResources::default(),
```

**Review by avi-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1158)* status: all files reviewed, 9 unresolved discussions (waiting on @rodrigo-pino)

___
*[`crates/blockifier/src/execution/errors.rs` line 96 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O95u0yO8JwoeKUjSDXV:-O95u0yQ8leIGc9Hc66T:biz7e44) ([raw file](https://github.com/starkware-libs/sequencer/blob/7cc9660c2acbc38f7a890f0daf87bb3855ac8ee0/crates/blockifier/src/execution/errors.rs#L96)):*
> ```XML
>         #[source]
>         source: NativeRunnerError,
>     },
> ```

Why not use `from` instead of `source`? (As in the other examples in this enum)



_Suggestion:_
```XML
    NativeUnexpectedError(#[from] NativeRunnerError),
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 54 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O9623gX95KnqhM1lxc-:-O9623gX95KnqhM1lxc0:b-rixy70) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L54)):*
> ```XML
>     );
> 
>     let run_result = match execution_result {
> ```

I think this name makes more sense. `run_result` sounds the same as `execution_result`, so it was slightly confusing to me. `call_result` implies that this result is related to the `call_info`, which is the output of the current function.

Non-blocking



_Suggestion:_
```XML
    let call_result = match execution_result 
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 78 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O964a4Q2Ew1je1TM9Uy:-O964a4Q2Ew1je1TM9Uz:bd50xy2) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L78)):*
> ```XML
>     let gas_consumed = {
>         // We can use `.unwrap()` directly in both cases because the most significant bit is could
>         // be only 63 here (128 = 64 + 64).
> ```

Non-blocking



_Suggestion:_
```XML
        // We can use `.unwrap()` directly in both cases because the most significant bit can
        // be at most 63 here (128 = 64 + 64).
```

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r11, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1158)* status: all files reviewed, 9 unresolved discussions (waiting on @rodrigo-pino)

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1158)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/errors.rs` line 96 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O95u0yO8JwoeKUjSDXV:-O97k2RPDbk_iLnIPc5T:b-896fja) ([raw file](https://github.com/starkware-libs/sequencer/blob/7cc9660c2acbc38f7a890f0daf87bb3855ac8ee0/crates/blockifier/src/execution/errors.rs#L96)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Why not use `from` instead of `source`? (As in the other examples in this enum)
</blockquote></details>

Done!
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 36 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8uGYDy6LKSxSwnS0R_:-O97k7sA6Vy5Xw8HaQqm:b1ubcge) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L36)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I suggest having the `call` as a field of the syscall handler (non-blocking and should be done in a separate PR).
</blockquote></details>

Makes sense
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 54 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O9623gX95KnqhM1lxc-:-O97lDvw9ZY0g3T5TLCW:b-896fja) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L54)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I think this name makes more sense. `run_result` sounds the same as `execution_result`, so it was slightly confusing to me. `call_result` implies that this result is related to the `call_info`, which is the output of the current function.

Non-blocking
</blockquote></details>

Done!
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 58 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8uD-MO1-mmONc4FiIj:-O97qRdXAwCR_E9TLcuw:bqp30y1) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L58)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

And then you don't need to dcode. We currently return `Vec<Felt>`.
See [here](https://github.com/starkware-libs/sequencer/blob/876810d9da9902dffd187f0cf5ba02b10bad6dc4/crates/blockifier/src/execution/entry_point_execution.rs#L109).
</blockquote></details>

I don't fully understand this one. Assuming the way it starts there was a first part somewhere else?
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 68 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8uFeOVDyHJmhm_XNT0:-O97ljAL0upkQTTz04UR:baesz6z) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L68)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is the clone needed?
</blockquote></details>

Not at all!!! I think it might have been a refactor left-over
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 85 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8uFlWd-lH89SYgheME:-O97pf8o1K8bFdpU09ew:b-uc9zve) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L85)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

Yes! A lot shorter, thank you!
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 86 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8uFuhO3GfsAaH2OVdJ:-O97mCpb0MNk_pkhFnmJ:b2e63fs) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L86)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What will happen in case `low > call.initial_gas`
</blockquote></details>

In this case `low` is the gas used by the execution. At this point in the code is not possible (assuming the correctness of Native & Syscalls) for `low` to be greater than `call.initial_gas`

If there had been an `out_of_gas` exception this method wouldn't execute. The code would take the "report error route" and not the "create call info" one.  You can see in the function above (`run_native_executor`) where property `failure_flag` is used to determine the correct execution flow.
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 104 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8uGOZq27-PjK0IM19N:-O97nd554wI3XB-uke5J:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L104)):*
> ```XML
>             n_memory_holes: 0,
>             builtin_instance_counter: HashMap::default(),
>         },
> ```

Done

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1158)* status: 4 of 7 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 36 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8uGYDy6LKSxSwnS0R_:-O983tma7eht57n2OzKk:b5jxlk1) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L36)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

Makes sense
</blockquote></details>

https://github.com/starkware-libs/sequencer/pull/1380

**Review by noaov1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r19, 1 of 2 files at r20, 1 of 2 files at r23, 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1158)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @rodrigo-pino)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 58 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8uD-MO1-mmONc4FiIj:-O9E0knT9OHsTnb75ybM:buxxdck) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L58)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

I don't fully understand this one. Assuming the way it starts there was a first part somewhere else?
</blockquote></details>

When executing a casm, if the failure flag is on, we return an `ExecutionFailed` error, containing the vector of felts (without decoding the error). We can keep this behaviour for consistency (see [here](https://github.com/starkware-libs/sequencer/blob/876810d9da9902dffd187f0cf5ba02b10bad6dc4/crates/blockifier/src/execution/entry_point_execution.rs#L110)).
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 86 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8uFuhO3GfsAaH2OVdJ:-O9E6P547IX4xmlP0JdI:b-z9xd4a) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L86)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

In this case `low` is the gas used by the execution. At this point in the code is not possible (assuming the correctness of Native & Syscalls) for `low` to be greater than `call.initial_gas`

If there had been an `out_of_gas` exception this method wouldn't execute. The code would take the "report error route" and not the "create call info" one.  You can see in the function above (`run_native_executor`) where property `failure_flag` is used to determine the correct execution flow.
</blockquote></details>

Is `low` the gas used by the execution or the gas remained after the execution?
Anyway, I think that we can consume a negative amount of gas.
Currently, in the casm execution, we return an error in this case (see [here](https://github.com/starkware-libs/sequencer/blob/876810d9da9902dffd187f0cf5ba02b10bad6dc4/crates/blockifier/src/execution/entry_point_execution.rs#L468).
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 59 at r25](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O9E1XjEAgDx4FCs6Q65:-O9E1XjEAgDx4FCs6Q66:bvau0wd) ([raw file](https://github.com/starkware-libs/sequencer/blob/edde72bdc903efd9d53ea024629f9866694e5126/crates/blockifier/src/execution/native/entry_point_execution.rs#L59)):*
> ```XML
>                 decode_felts_as_str(&res.return_values)
>             } else {
>                 String::from("Unknown error")
> ```

Why is it considered an unknown error in this case? 



_Code quote:_
```XML
                String::from("Unknown error")
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 75 at r25](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O9E1xxK2-tjdNPEtLkc:-O9E1xxK2-tjdNPEtLkd:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/edde72bdc903efd9d53ea024629f9866694e5126/crates/blockifier/src/execution/native/entry_point_execution.rs#L75)):*
> ```XML
>     // todo(rodro): Even if the property is called `remaining_gas` it behaves like gas used.
>     // Update once gas works on Native side has been completed (or at least this part)
>     let gas_used =
> ```





_Suggestion:_
```XML
let remaining_gas =
```

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1158)* status: 5 of 9 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 58 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8uD-MO1-mmONc4FiIj:-O9HRRe8CErxG5k5wva1:bkh3bzd) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L58)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

When executing a casm, if the failure flag is on, we return an `ExecutionFailed` error, containing the vector of felts (without decoding the error). We can keep this behaviour for consistency (see [here](https://github.com/starkware-libs/sequencer/blob/876810d9da9902dffd187f0cf5ba02b10bad6dc4/crates/blockifier/src/execution/entry_point_execution.rs#L110)).
</blockquote></details>

Right, I've added the `enable_revert` flag as a condition for the error as well
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 86 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8uFuhO3GfsAaH2OVdJ:-O9HXQWI7FSgMuoyiq7b:b-u7mduy) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L86)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is `low` the gas used by the execution or the gas remained after the execution?
Anyway, I think that we can consume a negative amount of gas.
Currently, in the casm execution, we return an error in this case (see [here](https://github.com/starkware-libs/sequencer/blob/876810d9da9902dffd187f0cf5ba02b10bad6dc4/crates/blockifier/src/execution/entry_point_execution.rs#L468).
</blockquote></details>

Sorry, `low` is remaining gas.

Regarding the other stuff, makes sense!

With the removal of `NativeExecutionError` there is also no reason to decode felts the way we did since you have a similar function.(`format_panic_data`). Therefore I am removing `decode_felts_as_str` function.

By chance do you guys have a method for encoding string as felts :)?
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 59 at r25](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O9E1XjEAgDx4FCs6Q65:-O9HWulK-6_blQk6P2-f:bvbss71) ([raw file](https://github.com/starkware-libs/sequencer/blob/edde72bdc903efd9d53ea024629f9866694e5126/crates/blockifier/src/execution/native/entry_point_execution.rs#L59)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it considered an unknown error in this case?
</blockquote></details>

Good question, luckily is no longer relevant since we are using `ExecutionFailed` error now
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 75 at r25](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O9E1xxK2-tjdNPEtLkc:-O9HgIrN6PBTWR6atCpB:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/edde72bdc903efd9d53ea024629f9866694e5126/crates/blockifier/src/execution/native/entry_point_execution.rs#L75)):*
> ```XML
>     // todo(rodro): Even if the property is called `remaining_gas` it behaves like gas used.
>     // Update once gas works on Native side has been completed (or at least this part)
>     let gas_used =
> ```

Done

**Review by noaov1 — APPROVED** [review]
> Reviewed 2 of 5 files at r8, 1 of 7 files at r27, 1 of 2 files at r28, 1 of 1 files at r32, 4 of 4 files at r34, 1 of 1 files at r35, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1158)* status: all files reviewed, 1 unresolved discussion (waiting on @rodrigo-pino)

___
*[`.github/workflows/main.yml` line 110 at r35](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O9eED469-pvyM5-7N7J:-O9eED469-pvyM5-7N7K:bb76mu4) ([raw file](https://github.com/starkware-libs/sequencer/blob/c773bf12a81637637c18b64ec106e0170cb04586/.github/workflows/main.yml#L110)):*
> ```YAML
> 
>   codecov:
>     runs-on: starkware-ubuntu-latest-large
> ```

Why?



_Code quote:_
```YAML
runs-on: starkware-ubuntu-latest-large
```
___
*[`crates/blockifier/src/execution/native/entry_point_execution.rs` line 86 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/1158#-O8uFuhO3GfsAaH2OVdJ:-O9eDXOZ4YPQqNHauO7G:bqdzhj4) ([raw file](https://github.com/starkware-libs/sequencer/blob/075b8350fde6bd35964547c4b8256da79240fa3f/crates/blockifier/src/execution/native/entry_point_execution.rs#L86)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

Sorry, `low` is remaining gas.

Regarding the other stuff, makes sense!

With the removal of `NativeExecutionError` there is also no reason to decode felts the way we did since you have a similar function.(`format_panic_data`). Therefore I am removing `decode_felts_as_str` function.

By chance do you guys have a method for encoding string as felts :)?
</blockquote></details>

Not that I know of.

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1158)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rodrigo-pino)

**Pull request merged**
