### PR TITLE
build: blockifier regression test serde rpc tx to starknet api tx

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1021)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1021?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1021** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1021?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1016** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1016?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#980** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/980?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#956** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/956?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#943](https://github.com/starkware-libs/sequencer/pull/943) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/943?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#952** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/952?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#948** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/948?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#946** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/946?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#945** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/945?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2, 2 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1021)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_regression_test/resources/json_objects/invoke_v1.json` line 0 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O8601vn9Egs0q_EAESw:-O8601vn9Egs0q_EAESx:b-fstc5c) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ef0e01a02014a16df11eb3035be8de2a363cdba/crates/blockifier_regression_test/resources/json_objects/invoke_v1.json#L0)):*
I wouldn't create a JSON per tx... consider creating a `tx_hash_to_tx.json` file with a dict mapping tx hash to this object

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1021)* status: 8 of 9 files reviewed, 8 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_regression_test/resources/json_objects/transactions.json` line 0 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O86dyfj8sDfCAMSS-er:-O86dyfk2rVXYQd3s-C6:bnkqtr1) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed51c6e7be4a804d9743cf01c375d8e9e7770721/crates/blockifier_regression_test/resources/json_objects/transactions.json#L0)):*
this is data for testing internal utils, correct?
I prefer the tests you run for internal utils will be on "real" reexecution data - the same JSONs that will be used in reexecution tests.
otherwise, the RPC-data-fetching process can break, and your tests won't catch it because this JSON won't be updated, right?
___
*[`crates/blockifier_regression_test/src/json_test.rs` line 40 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O86fxCq3cqNdJ6Mrqjt:-O86fxCq3cqNdJ6Mrqju:b8l4m33) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed51c6e7be4a804d9743cf01c375d8e9e7770721/crates/blockifier_regression_test/src/json_test.rs#L40)):*
> ```XML
>     )
>     .expect("Failed to deserialize invoke v3 tx")
> }
> ```

will these be useful fixtures? or are they only needed for a single test?



_Code quote:_
```XML
#[fixture]
fn invoke_tx_v1() -> Transaction {
    deserialize_transaction_json_to_starknet_api_tx(
        read_json_file("json_objects/transactions.json")["invoke_v1"].clone(),
    )
    .expect("Failed to deserialize invoke v1 tx")
}

#[fixture]
fn invoke_tx_v3() -> Transaction {
    deserialize_transaction_json_to_starknet_api_tx(
        read_json_file("json_objects/transactions.json")["invoke_v3"].clone(),
    )
    .expect("Failed to deserialize invoke v3 tx")
}
```
___
*[`crates/blockifier_regression_test/src/json_test.rs` line 76 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O86g0lHCdbhhluD0FxC:-O86g0lHCdbhhluD0FxD:b-p2y83y) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed51c6e7be4a804d9743cf01c375d8e9e7770721/crates/blockifier_regression_test/src/json_test.rs#L76)):*
> ```XML
> fn deserialize_invoke_tx_v3(invoke_tx_v3: Transaction) {
>     assert_matches!(invoke_tx_v3, Transaction::Invoke(InvokeTransaction::V3(..)));
> }
> ```

please combine these tests



_Suggestion:_
```XML
#[rstest]
fn deserialize_invoke_txs(invoke_tx_v1: Transaction, invoke_tx_v3: Transaction) {
    assert_matches!(invoke_tx_v1, Transaction::Invoke(InvokeTransaction::V1(..)));
    assert_matches!(invoke_tx_v3, Transaction::Invoke(InvokeTransaction::V3(..)));
}
```
___
*[`crates/blockifier_regression_test/src/state_reader/rpc_test.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O86gCtl2f2S5v4uop5y:-O86gCtl2f2S5v4uop5z:bljtoyx) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed51c6e7be4a804d9743cf01c375d8e9e7770721/crates/blockifier_regression_test/src/state_reader/rpc_test.rs#L81)):*
> ```XML
> #[rstest]
> pub fn test_get_tx_by_hash(test_state_reader: TestStateReader) {
>     let tx_hash = "0xa7c7db686c7f756ceb7ca85a759caef879d425d156da83d6a836f86851983";
> ```

you now have two constants defined in this test... please create named constants for them at the top of this module, e.g.
```
const EXAMPLE_INVOKE_TX_HASH: &str = "0xa7c7db686c7f756ceb7ca85a759caef879d425d156da83d6a836f86851983";
```



_Code quote:_
```XML
"0xa7c7db686c7f756ceb7ca85a759caef879d425d156da83d6a836f86851983";
```
___
*[`crates/blockifier_regression_test/src/state_reader/test_state_reader.rs` line 153 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O86fJgT6RCkT5PxnQ0X:-O86fJgT6RCkT5PxnQ0Y:b-i64gsx) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed51c6e7be4a804d9743cf01c375d8e9e7770721/crates/blockifier_regression_test/src/state_reader/test_state_reader.rs#L153)):*
> ```XML
>         for tx_hash in txs_hash {
>             txs.push(self.get_tx_by_hash(&tx_hash)?);
>         }
> ```

when using an RPC reader, this will use network to fetch data?
if so, please make this code async (fetch txs in parallel),
or - is there a "multi-get" RPC endpoint?



_Code quote:_
```XML
        for tx_hash in txs_hash {
            txs.push(self.get_tx_by_hash(&tx_hash)?);
        }
```
___
*[`crates/blockifier_regression_test/src/state_reader/test_state_reader.rs` line 154 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O86egtk74XC-gq0u8Lg:-O86egtk74XC-gq0u8Lh:b-cjmtyn) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed51c6e7be4a804d9743cf01c375d8e9e7770721/crates/blockifier_regression_test/src/state_reader/test_state_reader.rs#L154)):*
> ```XML
>             txs.push(self.get_tx_by_hash(&tx_hash)?);
>         }
>         Ok(txs)
> ```

[seems rustier](https://stackoverflow.com/questions/26368288/how-do-i-stop-iteration-and-return-an-error-when-iteratormap-returns-a-result), WDYT? non-blocking



_Suggestion:_
```XML
        let tx_results: Result<Vec<_>, _> = self
            .get_tx_hashes()?
            .iter()
            .map(|tx_hash| self.get_tx_by_hash(&tx_hash))
            .collect();
        Ok(tx_results?)
```
___
*[`crates/blockifier_regression_test/src/state_reader/utils.rs` line 38 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O86e_cjDMKUCaF4Y9xj:-O86e_cjDMKUCaF4Y9xk:b-e70r7d) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed51c6e7be4a804d9743cf01c375d8e9e7770721/crates/blockifier_regression_test/src/state_reader/utils.rs#L38)):*
> ```XML
> }
> 
> pub fn deserialize_transaction_json_to_starknet_api_tx(
> ```

this is also from starknet-replay repo?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1021)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_regression_test/src/state_reader/rpc_https_test.rs` line 21 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O878UFhCbB6T_NjFPs7:-O878UFhCbB6T_NjFPs8:b-qjdqc6) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee1b1fff884b11525be4789d1e2378c66e8a325a/crates/blockifier_regression_test/src/state_reader/rpc_https_test.rs#L21)):*
> ```XML
> #[fixture]
> pub fn test_block_number() -> BlockNumber {
>     BlockNumber(700000)
> ```

const EXAMPLE_BLOCK_NUMBER = 700000



_Code quote:_
```XML
700000
```
___
*[`crates/blockifier_regression_test/src/state_reader/rpc_https_test.rs` line 46 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O878QumBuA68Yx2ixd_:-O878QumBuA68Yx2ixda:b-uz443i) ([raw file](https://github.com/starkware-libs/sequencer/blob/ee1b1fff884b11525be4789d1e2378c66e8a325a/crates/blockifier_regression_test/src/state_reader/rpc_https_test.rs#L46)):*
> ```XML
>     // An example of existing class hash in Mainnet.
>     let class_hash =
>         class_hash!("0x3131fa018d520a037686ce3efddeab8f28895662f019ca3ca18a626650f7d1e");
> ```

this should also be a constant at the top



_Code quote:_
```XML
"0x3131fa018d520a037686ce3efddeab8f28895662f019ca3ca18a626650f7d1e"
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1021)* status: 8 of 11 files reviewed, 5 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_regression_test/src/state_reader/rpc_https_test.rs` line 21 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O878UFhCbB6T_NjFPs7:-O87AJdr5Kx-idRAf0Dh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/961a6fe7ac4360c220fd78f453b8233bb93a78c1/crates/blockifier_regression_test/src/state_reader/rpc_https_test.rs#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

const EXAMPLE_BLOCK_NUMBER = 700000
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/state_reader/rpc_https_test.rs` line 46 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O878QumBuA68Yx2ixd_:-O87AqAl5pmQujew1CAD:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/961a6fe7ac4360c220fd78f453b8233bb93a78c1/crates/blockifier_regression_test/src/state_reader/rpc_https_test.rs#L46)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this should also be a constant at the top
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/state_reader/test_state_reader.rs` line 153 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O86fJgT6RCkT5PxnQ0X:-O86ojTu6kalbUt2XlBS:b-aqkjui) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed51c6e7be4a804d9743cf01c375d8e9e7770721/crates/blockifier_regression_test/src/state_reader/test_state_reader.rs#L153)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

when using an RPC reader, this will use network to fetch data?
if so, please make this code async (fetch txs in parallel),
or - is there a "multi-get" RPC endpoint?
</blockquote></details>

There is a multi-get function, but it hasn't been implemented in our code yet (at least, I haven't found it). I'm adding a todo for using it.
___
*[`crates/blockifier_regression_test/src/state_reader/test_state_reader.rs` line 154 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O86egtk74XC-gq0u8Lg:-O8765Iw4nQpWCEZXFAv:b2nhswy) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed51c6e7be4a804d9743cf01c375d8e9e7770721/crates/blockifier_regression_test/src/state_reader/test_state_reader.rs#L154)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[seems rustier](https://stackoverflow.com/questions/26368288/how-do-i-stop-iteration-and-return-an-error-when-iteratormap-returns-a-result), WDYT? non-blocking
</blockquote></details>

Yes
___
*[`crates/blockifier_regression_test/src/state_reader/utils.rs` line 38 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O86e_cjDMKUCaF4Y9xj:-O86o9Sx417gxsKaQO_B:bjbaq7s) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed51c6e7be4a804d9743cf01c375d8e9e7770721/crates/blockifier_regression_test/src/state_reader/utils.rs#L38)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is also from starknet-replay repo?
</blockquote></details>

Yes, but with changes since we change the txs structs
___
*[`crates/blockifier_regression_test/resources/json_objects/invoke_v1.json` line  at r4](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O8601vn9Egs0q_EAESw:-O8763gYBcS9DTjTWCdO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8ef0e01a02014a16df11eb3035be8de2a363cdba/crates/blockifier_regression_test/resources/json_objects/invoke_v1.json#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I wouldn't create a JSON per tx... consider creating a `tx_hash_to_tx.json` file with a dict mapping tx hash to this object
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/json_test.rs` line 40 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O86fxCq3cqNdJ6Mrqjt:-O874VEt-MOep6jEQiW-:b5pikqh) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed51c6e7be4a804d9743cf01c375d8e9e7770721/crates/blockifier_regression_test/src/json_test.rs#L40)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

will these be useful fixtures? or are they only needed for a single test?
</blockquote></details>

Im not sure
___
*[`crates/blockifier_regression_test/src/json_test.rs` line 76 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O86g0lHCdbhhluD0FxC:-O874X1N5F575oPBX_Xr:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed51c6e7be4a804d9743cf01c375d8e9e7770721/crates/blockifier_regression_test/src/json_test.rs#L76)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please combine these tests
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/state_reader/rpc_test.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O86gCtl2f2S5v4uop5y:-O8756Db7BgqBncDcpzW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed51c6e7be4a804d9743cf01c375d8e9e7770721/crates/blockifier_regression_test/src/state_reader/rpc_test.rs#L81)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you now have two constants defined in this test... please create named constants for them at the top of this module, e.g.
```
const EXAMPLE_INVOKE_TX_HASH: &str = "0xa7c7db686c7f756ceb7ca85a759caef879d425d156da83d6a836f86851983";
```
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/resources/json_objects/transactions.json` line  at r5](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O86dyfj8sDfCAMSS-er:-O86nccX3ekhClYcz2ho:b-rnhsn5) ([raw file](https://github.com/starkware-libs/sequencer/blob/ed51c6e7be4a804d9743cf01c375d8e9e7770721/crates/blockifier_regression_test/resources/json_objects/transactions.json#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is data for testing internal utils, correct?
I prefer the tests you run for internal utils will be on "real" reexecution data - the same JSONs that will be used in reexecution tests.
otherwise, the RPC-data-fetching process can break, and your tests won't catch it because this JSON won't be updated, right?
</blockquote></details>

is it ok?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1021)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_regression_test/src/state_reader/utils.rs` line 44 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O87DQAi8ibBOxiKtdHm:-O87DQAi8ibBOxiKtdHn:bb682eb) ([raw file](https://github.com/starkware-libs/sequencer/blob/b656fb798b852cbf912c9f76aa0ece1ddde80b10/crates/blockifier_regression_test/src/state_reader/utils.rs#L44)):*
> ```XML
>     let tx_version: String = serde_json::from_value(raw_transaction["version"].clone())?;
> 
>     match tx_type.as_str() {
> ```

I think this `match` will be nicer (and flatter) if you match tuples of (type, version);
you can have a single wildcard at the end with an Err for an unknown pair



_Suggestion:_
```XML
match (tx_type.as_str(), tx_version.as_str())
```
___
*[`crates/blockifier_regression_test/src/state_reader/utils.rs` line 58 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O87DgIg9ppS7DoGGdiK:-O87DgIg9ppS7DoGGdiL:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/b656fb798b852cbf912c9f76aa0ece1ddde80b10/crates/blockifier_regression_test/src/state_reader/utils.rs#L58)):*
> ```XML
>                     resource_bounds.insert("L1_GAS".to_string(), l1_gas_value);
>                 }
>                 if let Some(l1_gas_value) = resource_bounds.remove("l2_gas") {
> ```





_Suggestion:_
```XML
l2
```
___
*[`crates/blockifier_regression_test/src/state_reader/utils.rs` line 60 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O87DjXcBEg3j15NUR8s:-O87DjXcBEg3j15NUR8t:b-snab8u) ([raw file](https://github.com/starkware-libs/sequencer/blob/b656fb798b852cbf912c9f76aa0ece1ddde80b10/crates/blockifier_regression_test/src/state_reader/utils.rs#L60)):*
> ```XML
>                 if let Some(l1_gas_value) = resource_bounds.remove("l2_gas") {
>                     resource_bounds.insert("L2_GAS".to_string(), l1_gas_value);
>                 }
> ```

what about data gas?



_Code quote:_
```XML
                if let Some(l1_gas_value) = resource_bounds.remove("l1_gas") {
                    resource_bounds.insert("L1_GAS".to_string(), l1_gas_value);
                }
                if let Some(l1_gas_value) = resource_bounds.remove("l2_gas") {
                    resource_bounds.insert("L2_GAS".to_string(), l1_gas_value);
                }
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1021)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_regression_test/src/state_reader/utils.rs` line 44 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O87DQAi8ibBOxiKtdHm:-O87HLQqCnntS1OqHHdW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b656fb798b852cbf912c9f76aa0ece1ddde80b10/crates/blockifier_regression_test/src/state_reader/utils.rs#L44)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think this `match` will be nicer (and flatter) if you match tuples of (type, version);
you can have a single wildcard at the end with an Err for an unknown pair
</blockquote></details>

Done.
___
*[`crates/blockifier_regression_test/src/state_reader/utils.rs` line 58 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O87DgIg9ppS7DoGGdiK:-O87HR7U4vot6kl6WkK-:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b656fb798b852cbf912c9f76aa0ece1ddde80b10/crates/blockifier_regression_test/src/state_reader/utils.rs#L58)):*
> ```XML
>                     resource_bounds.insert("L1_GAS".to_string(), l1_gas_value);
>                 }
>                 if let Some(l1_gas_value) = resource_bounds.remove("l2_gas") {
> ```

Done.
___
*[`crates/blockifier_regression_test/src/state_reader/utils.rs` line 60 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O87DjXcBEg3j15NUR8s:-O87FNPvCuqw6MVsgZ-o:b-cj6m7r) ([raw file](https://github.com/starkware-libs/sequencer/blob/b656fb798b852cbf912c9f76aa0ece1ddde80b10/crates/blockifier_regression_test/src/state_reader/utils.rs#L60)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what about data gas?
</blockquote></details>

It's for deserializing old TXs, if the TXs contain l1_data_gas the json should not need any change

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1021)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_regression_test/src/state_reader/utils.rs` line 60 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O87DjXcBEg3j15NUR8s:-O87SigdEjCMlxJkPV_4:b5zajg1) ([raw file](https://github.com/starkware-libs/sequencer/blob/b656fb798b852cbf912c9f76aa0ece1ddde80b10/crates/blockifier_regression_test/src/state_reader/utils.rs#L60)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

so, old txs have lowercase gas names, and new txs have uppercase?
</blockquote></details>

Nimrod changed the Resource bounds serialization. The tx has Resource bound field..

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1021)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_regression_test/src/state_reader/utils.rs` line 54 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O87U-wI9g-mVf6ZG5ne:-O87U-wI9g-mVf6ZG5nf:bif1my) ([raw file](https://github.com/starkware-libs/sequencer/blob/8deb32692605cac6d39dbef9e7119e17f6b4152a/crates/blockifier_regression_test/src/state_reader/utils.rs#L54)):*
> ```XML
>             if let Some(resource_bounds) =
>                 raw_transaction.get_mut("resource_bounds").and_then(Value::as_object_mut)
>             {
> ```

what will happen if the v3 tx *doesn't* contains this field?
shouldn't it always contain it? v3 txs always have resource bounds



_Code quote:_
```XML
            if let Some(resource_bounds) =
                raw_transaction.get_mut("resource_bounds").and_then(Value::as_object_mut)
            {
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1021)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_regression_test/src/state_reader/utils.rs` line 51 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O87XC930Vg5GkB4hAna:-O87XC930Vg5GkB4hAnb:b-tqm7x) ([raw file](https://github.com/starkware-libs/sequencer/blob/8deb32692605cac6d39dbef9e7119e17f6b4152a/crates/blockifier_regression_test/src/state_reader/utils.rs#L51)):*
> ```XML
>             Ok(Transaction::Invoke(InvokeTransaction::V1(serde_json::from_value(raw_transaction)?)))
>         }
>         ("INVOKE", "0x3") => {
> ```

please document in comments what is going on here; this (invoke, v3) case is confusing



_Code quote:_
```XML
 ("INVOKE", "0x3") => {
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1021)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_regression_test/src/state_reader/utils.rs` line 61 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-O87_gs90Mu2lOHEP29U:-O87btFN7sSShQS6MPy8:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8deb32692605cac6d39dbef9e7119e17f6b4152a/crates/blockifier_regression_test/src/state_reader/utils.rs#L61)):*
> ```XML
>                     resource_bounds.insert("L2_GAS".to_string(), l2_gas_value);
>                 }
>             }
> ```

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1021#-:-O87hzupCi3u9pxssHov:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
