### PR TITLE
refactor(blockifier): versioned constant

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/642)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
* **#642** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/642?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 41 of 41 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/642)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/642)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/642)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/642#-O5OK0Rk-mIsvkalF5DD:-O5h_U2O-nM7r26ikZLi:bb7mg7q) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

pending python checks
</blockquote></details>

pass

___

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/642)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 89 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/642#-O5hfjVP9Zi-4Yj8mda3:-O5hicK--2fVdErCeP14:b89bmtr) ([raw file](https://github.com/starkware-libs/sequencer/blob/a08d1cdffc6c3e642fc2df13ef675febb8708ff1/crates/blockifier/resources/versioned_constants.json#L89)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

wait, why don't you need these fields in the other JSONs as well?
on `main`, all JSONs from all versions need to be deserializable into the *current* VersionedConstants struct; can these OS fields simply be ignored in deserialization?
</blockquote></details>

It seems that serde success.
There is a macro here that loads the other JSONs
 https://github.com/starkware-libs/sequencer/blob/d846784519cedc91d90796c16b8831d71da1052e/crates/blockifier/src/versioned_constants.rs#L115

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/642)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 89 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/642#-O5hfjVP9Zi-4Yj8mda3:-O5hlaE11EstrhVlfNzG:baqwbl9) ([raw file](https://github.com/starkware-libs/sequencer/blob/a08d1cdffc6c3e642fc2df13ef675febb8708ff1/crates/blockifier/resources/versioned_constants.json#L89)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

It seems that serde success.
There is a macro here that loads the other JSONs
 https://github.com/starkware-libs/sequencer/blob/d846784519cedc91d90796c16b8831d71da1052e/crates/blockifier/src/versioned_constants.rs#L115
</blockquote></details>

I am wondering why [this test](https://github.com/starkware-libs/sequencer/blob/6b7dcbb199401a4db92f9743277d1afc8b0cf783/crates/blockifier/src/versioned_constants_test.rs#L226-L227) passes; please check how these fields are loaded. it's probably fine, I just want to make sure

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/642)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 89 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/642#-O5hfjVP9Zi-4Yj8mda3:-O5hnC80EHjdCweWAcm0:b-kvda1b) ([raw file](https://github.com/starkware-libs/sequencer/blob/a08d1cdffc6c3e642fc2df13ef675febb8708ff1/crates/blockifier/resources/versioned_constants.json#L89)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I am wondering why [this test](https://github.com/starkware-libs/sequencer/blob/6b7dcbb199401a4db92f9743277d1afc8b0cf783/crates/blockifier/src/versioned_constants_test.rs#L226-L227) passes; please check how these fields are loaded. it's probably fine, I just want to make sure
</blockquote></details>

this is how it loads 0.13.2


VersionedConstants {
    tx_event_limits: EventLimits {
        max_data_length: 300,
        max_keys_length: 50,
        max_n_emitted_events: 1000,
    },
    invoke_tx_max_n_steps: 10000000,
    l2_resource_gas_costs: L2ResourceGasCosts {
        gas_per_data_felt: Ratio {
            numer: 128,
            denom: 1000,
        },
        event_key_factor: Ratio {
            numer: 2,
            denom: 1,
        },
        gas_per_code_byte: Ratio {
            numer: 875,
            denom: 1000,
        },
    },
    max_recursion_depth: 50,
    validate_max_n_steps: 1000000,
    segment_arena_cells: false,
    disable_cairo0_redeclaration: true,
    os_constants: OsConstants {
        gas_costs: GasCosts {
            step_gas_cost: 100,
            memory_hole_gas_cost: 10,
            range_check_gas_cost: 70,
            pedersen_gas_cost: 0,
            bitwise_builtin_gas_cost: 594,
            ecop_gas_cost: 0,
            poseidon_gas_cost: 0,
            add_mod_gas_cost: 0,
            mul_mod_gas_cost: 0,
            initial_gas_cost: 10000000000,
            entry_point_initial_budget: 10000,
            syscall_base_gas_cost: 10000,
            entry_point_gas_cost: 60000,
            fee_transfer_gas_cost: 70000,
            transaction_gas_cost: 200000,
            call_contract_gas_cost: 71000,
            deploy_gas_cost: 90000,
            get_block_hash_gas_cost: 15000,
            get_execution_info_gas_cost: 11000,
            library_call_gas_cost: 71000,
            replace_class_gas_cost: 15000,
            storage_read_gas_cost: 15000,
            storage_write_gas_cost: 15000,
            emit_event_gas_cost: 11000,
            send_message_to_l1_gas_cost: 15000,
            secp256k1_add_gas_cost: 42630,
            secp256k1_get_point_from_x_gas_cost: 41400,
            secp256k1_get_xy_gas_cost: 25070,
            secp256k1_mul_gas_cost: 8143270,
            secp256k1_new_gas_cost: 50350,
            secp256r1_add_gas_cost: 62890,
            secp256r1_get_point_from_x_gas_cost: 54280,
            secp256r1_get_xy_gas_cost: 25270,
            secp256r1_mul_gas_cost: 13511290,
            secp256r1_new_gas_cost: 63230,
            keccak_gas_cost: 10000,
            keccak_round_cost_gas_cost: 180000,
            sha256_process_block_gas_cost: 862060,
        },
        validate_rounding_consts: ValidateRoundingConsts {
            validate_block_number_rounding: 100,
            validate_timestamp_rounding: 3600,
        },
    },
    os_resources: OsResources {
        execute_syscalls: {
            GetContractAddress: ExecutionResources {
                n_steps: 64,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 1,
                },
            },
            Keccak: ExecutionResources {
                n_steps: 381,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    bitwise: 6,
                    keccak: 1,
                    range_check: 56,
                },
            },
            DelegateCall: ExecutionResources {
                n_steps: 713,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 19,
                },
            },
            Secp256r1New: ExecutionResources {
                n_steps: 580,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 49,
                },
            },
            DelegateL1Handler: ExecutionResources {
                n_steps: 692,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 15,
                },
            },
            LibraryCallL1Handler: ExecutionResources {
                n_steps: 659,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 15,
                },
            },
            GetCallerAddress: ExecutionResources {
                n_steps: 64,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 1,
                },
            },
            ReplaceClass: ExecutionResources {
                n_steps: 98,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 1,
                },
            },
            Secp256k1GetXy: ExecutionResources {
                n_steps: 207,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 11,
                },
            },
            GetBlockTimestamp: ExecutionResources {
                n_steps: 38,
                n_memory_holes: 0,
                builtin_instance_counter: {},
            },
            Secp256r1Mul: ExecutionResources {
                n_steps: 125344,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 13961,
                },
            },
            SendMessageToL1: ExecutionResources {
                n_steps: 141,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 1,
                },
            },
            StorageWrite: ExecutionResources {
                n_steps: 89,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 1,
                },
            },
            Deploy: ExecutionResources {
                n_steps: 1097,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 18,
                    pedersen: 7,
                },
            },
            CallContract: ExecutionResources {
                n_steps: 827,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 15,
                },
            },
            Sha256ProcessBlock: ExecutionResources {
                n_steps: 1855,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    bitwise: 1115,
                    range_check: 65,
                },
            },
            EmitEvent: ExecutionResources {
                n_steps: 61,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 1,
                },
            },
            Secp256k1Mul: ExecutionResources {
                n_steps: 76505,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 7045,
                },
            },
            LibraryCall: ExecutionResources {
                n_steps: 818,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 15,
                },
            },
            Secp256k1New: ExecutionResources {
                n_steps: 461,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 35,
                },
            },
            GetExecutionInfo: ExecutionResources {
                n_steps: 64,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 1,
                },
            },
            Secp256k1GetPointFromX: ExecutionResources {
                n_steps: 395,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 30,
                },
            },
            Secp256r1GetXy: ExecutionResources {
                n_steps: 209,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 11,
                },
            },
            StorageRead: ExecutionResources {
                n_steps: 87,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 1,
                },
            },
            GetBlockHash: ExecutionResources {
                n_steps: 104,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 2,
                },
            },
            Secp256r1GetPointFromX: ExecutionResources {
                n_steps: 514,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 44,
                },
            },
            GetTxInfo: ExecutionResources {
                n_steps: 64,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 1,
                },
            },
            GetBlockNumber: ExecutionResources {
                n_steps: 40,
                n_memory_holes: 0,
                builtin_instance_counter: {},
            },
            GetTxSignature: ExecutionResources {
                n_steps: 44,
                n_memory_holes: 0,
                builtin_instance_counter: {},
            },
            Secp256k1Add: ExecutionResources {
                n_steps: 410,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 29,
                },
            },
            GetSequencerAddress: ExecutionResources {
                n_steps: 34,
                n_memory_holes: 0,
                builtin_instance_counter: {},
            },
            Secp256r1Add: ExecutionResources {
                n_steps: 593,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 57,
                },
            },
        },
        execute_txs_inner: {
            DeployAccount: ResourcesByVersion {
                resources: ResourcesParams {
                    constant: ExecutionResources {
                        n_steps: 4137,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 11,
                            range_check: 77,
                            poseidon: 10,
                        },
                    },
                    calldata_factor: ExecutionResources {
                        n_steps: 21,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 2,
                        },
                    },
                },
                deprecated_resources: ResourcesParams {
                    constant: ExecutionResources {
                        n_steps: 4015,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            range_check: 72,
                            pedersen: 23,
                        },
                    },
                    calldata_factor: ExecutionResources {
                        n_steps: 21,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 2,
                        },
                    },
                },
            },
            InvokeFunction: ResourcesByVersion {
                resources: ResourcesParams {
                    constant: ExecutionResources {
                        n_steps: 3904,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 4,
                            range_check: 74,
                            poseidon: 11,
                        },
                    },
                    calldata_factor: ExecutionResources {
                        n_steps: 8,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 1,
                        },
                    },
                },
                deprecated_resources: ResourcesParams {
                    constant: ExecutionResources {
                        n_steps: 3763,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 14,
                            range_check: 69,
                        },
                    },
                    calldata_factor: ExecutionResources {
                        n_steps: 8,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 1,
                        },
                    },
                },
            },
            L1Handler: ResourcesByVersion {
                resources: ResourcesParams {
                    constant: ExecutionResources {
                        n_steps: 0,
                        n_memory_holes: 0,
                        builtin_instance_counter: {},
                    },
                    calldata_factor: ExecutionResources {
                        n_steps: 13,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 1,
                        },
                    },
                },
                deprecated_resources: ResourcesParams {
                    constant: ExecutionResources {
                        n_steps: 1233,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            range_check: 16,
                            pedersen: 11,
                        },
                    },
                    calldata_factor: ExecutionResources {
                        n_steps: 13,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 1,
                        },
                    },
                },
            },
            Declare: ResourcesByVersion {
                resources: ResourcesParams {
                    constant: ExecutionResources {
                        n_steps: 3079,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 4,
                            range_check: 58,
                            poseidon: 10,
                        },
                    },
                    calldata_factor: ExecutionResources {
                        n_steps: 0,
                        n_memory_holes: 0,
                        builtin_instance_counter: {},
                    },
                },
                deprecated_resources: ResourcesParams {
                    constant: ExecutionResources {
                        n_steps: 2973,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 16,
                            range_check: 53,
                        },
                    },
                    calldata_factor: ExecutionResources {
                        n_steps: 0,
                        n_memory_holes: 0,
                        builtin_instance_counter: {},
                    },
                },
            },
        },
        compute_os_kzg_commitment_info: ExecutionResources {
            n_steps: 113,
            n_memory_holes: 0,
            builtin_instance_counter: {
                range_check: 17,
            },
        },
    },
    vm_resource_fee_cost: {
        "ecdsa_builtin": Ratio {
            numer: 512,
            denom: 100,
        },
        "range_check_builtin": Ratio {
            numer: 4,
            denom: 100,
        },
        "keccak_builtin": Ratio {
            numer: 512,
            denom: 100,
        },
        "bitwise_builtin": Ratio {
            numer: 16,
            denom: 100,
        },
        "ec_op_builtin": Ratio {
            numer: 256,
            denom: 100,
        },
        "mul_mod_builtin": Ratio {
            numer: 4,
            denom: 100,
        },
        "output_builtin": Ratio {
            numer: 0,
            denom: 1,
        },
        "add_mod_builtin": Ratio {
            numer: 4,
            denom: 100,
        },
        "pedersen_builtin": Ratio {
            numer: 8,
            denom: 100,
        },
        "range_check96_builtin": Ratio {
            numer: 4,
            denom: 100,
        },
        "n_steps": Ratio {
            numer: 25,
            denom: 10000,
        },
        "poseidon_builtin": Ratio {
            numer: 8,
            denom: 100,
        },
    },
}

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/642)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 89 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/642#-O5hfjVP9Zi-4Yj8mda3:-O5ho9Ne29DyzH4F7AUr:b-jjkql7) ([raw file](https://github.com/starkware-libs/sequencer/blob/a08d1cdffc6c3e642fc2df13ef675febb8708ff1/crates/blockifier/resources/versioned_constants.json#L89)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

this is how it loads 0.13.2


VersionedConstants {
    tx_event_limits: EventLimits {
        max_data_length: 300,
        max_keys_length: 50,
        max_n_emitted_events: 1000,
    },
    invoke_tx_max_n_steps: 10000000,
    l2_resource_gas_costs: L2ResourceGasCosts {
        gas_per_data_felt: Ratio {
            numer: 128,
            denom: 1000,
        },
        event_key_factor: Ratio {
            numer: 2,
            denom: 1,
        },
        gas_per_code_byte: Ratio {
            numer: 875,
            denom: 1000,
        },
    },
    max_recursion_depth: 50,
    validate_max_n_steps: 1000000,
    segment_arena_cells: false,
    disable_cairo0_redeclaration: true,
    os_constants: OsConstants {
        gas_costs: GasCosts {
            step_gas_cost: 100,
            memory_hole_gas_cost: 10,
            range_check_gas_cost: 70,
            pedersen_gas_cost: 0,
            bitwise_builtin_gas_cost: 594,
            ecop_gas_cost: 0,
            poseidon_gas_cost: 0,
            add_mod_gas_cost: 0,
            mul_mod_gas_cost: 0,
            initial_gas_cost: 10000000000,
            entry_point_initial_budget: 10000,
            syscall_base_gas_cost: 10000,
            entry_point_gas_cost: 60000,
            fee_transfer_gas_cost: 70000,
            transaction_gas_cost: 200000,
            call_contract_gas_cost: 71000,
            deploy_gas_cost: 90000,
            get_block_hash_gas_cost: 15000,
            get_execution_info_gas_cost: 11000,
            library_call_gas_cost: 71000,
            replace_class_gas_cost: 15000,
            storage_read_gas_cost: 15000,
            storage_write_gas_cost: 15000,
            emit_event_gas_cost: 11000,
            send_message_to_l1_gas_cost: 15000,
            secp256k1_add_gas_cost: 42630,
            secp256k1_get_point_from_x_gas_cost: 41400,
            secp256k1_get_xy_gas_cost: 25070,
            secp256k1_mul_gas_cost: 8143270,
            secp256k1_new_gas_cost: 50350,
            secp256r1_add_gas_cost: 62890,
            secp256r1_get_point_from_x_gas_cost: 54280,
            secp256r1_get_xy_gas_cost: 25270,
            secp256r1_mul_gas_cost: 13511290,
            secp256r1_new_gas_cost: 63230,
            keccak_gas_cost: 10000,
            keccak_round_cost_gas_cost: 180000,
            sha256_process_block_gas_cost: 862060,
        },
        validate_rounding_consts: ValidateRoundingConsts {
            validate_block_number_rounding: 100,
            validate_timestamp_rounding: 3600,
        },
    },
    os_resources: OsResources {
        execute_syscalls: {
            GetContractAddress: ExecutionResources {
                n_steps: 64,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 1,
                },
            },
            Keccak: ExecutionResources {
                n_steps: 381,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    bitwise: 6,
                    keccak: 1,
                    range_check: 56,
                },
            },
            DelegateCall: ExecutionResources {
                n_steps: 713,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 19,
                },
            },
            Secp256r1New: ExecutionResources {
                n_steps: 580,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 49,
                },
            },
            DelegateL1Handler: ExecutionResources {
                n_steps: 692,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 15,
                },
            },
            LibraryCallL1Handler: ExecutionResources {
                n_steps: 659,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 15,
                },
            },
            GetCallerAddress: ExecutionResources {
                n_steps: 64,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 1,
                },
            },
            ReplaceClass: ExecutionResources {
                n_steps: 98,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 1,
                },
            },
            Secp256k1GetXy: ExecutionResources {
                n_steps: 207,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 11,
                },
            },
            GetBlockTimestamp: ExecutionResources {
                n_steps: 38,
                n_memory_holes: 0,
                builtin_instance_counter: {},
            },
            Secp256r1Mul: ExecutionResources {
                n_steps: 125344,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 13961,
                },
            },
            SendMessageToL1: ExecutionResources {
                n_steps: 141,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 1,
                },
            },
            StorageWrite: ExecutionResources {
                n_steps: 89,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 1,
                },
            },
            Deploy: ExecutionResources {
                n_steps: 1097,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 18,
                    pedersen: 7,
                },
            },
            CallContract: ExecutionResources {
                n_steps: 827,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 15,
                },
            },
            Sha256ProcessBlock: ExecutionResources {
                n_steps: 1855,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    bitwise: 1115,
                    range_check: 65,
                },
            },
            EmitEvent: ExecutionResources {
                n_steps: 61,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 1,
                },
            },
            Secp256k1Mul: ExecutionResources {
                n_steps: 76505,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 7045,
                },
            },
            LibraryCall: ExecutionResources {
                n_steps: 818,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 15,
                },
            },
            Secp256k1New: ExecutionResources {
                n_steps: 461,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 35,
                },
            },
            GetExecutionInfo: ExecutionResources {
                n_steps: 64,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 1,
                },
            },
            Secp256k1GetPointFromX: ExecutionResources {
                n_steps: 395,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 30,
                },
            },
            Secp256r1GetXy: ExecutionResources {
                n_steps: 209,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 11,
                },
            },
            StorageRead: ExecutionResources {
                n_steps: 87,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 1,
                },
            },
            GetBlockHash: ExecutionResources {
                n_steps: 104,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 2,
                },
            },
            Secp256r1GetPointFromX: ExecutionResources {
                n_steps: 514,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 44,
                },
            },
            GetTxInfo: ExecutionResources {
                n_steps: 64,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 1,
                },
            },
            GetBlockNumber: ExecutionResources {
                n_steps: 40,
                n_memory_holes: 0,
                builtin_instance_counter: {},
            },
            GetTxSignature: ExecutionResources {
                n_steps: 44,
                n_memory_holes: 0,
                builtin_instance_counter: {},
            },
            Secp256k1Add: ExecutionResources {
                n_steps: 410,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 29,
                },
            },
            GetSequencerAddress: ExecutionResources {
                n_steps: 34,
                n_memory_holes: 0,
                builtin_instance_counter: {},
            },
            Secp256r1Add: ExecutionResources {
                n_steps: 593,
                n_memory_holes: 0,
                builtin_instance_counter: {
                    range_check: 57,
                },
            },
        },
        execute_txs_inner: {
            DeployAccount: ResourcesByVersion {
                resources: ResourcesParams {
                    constant: ExecutionResources {
                        n_steps: 4137,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 11,
                            range_check: 77,
                            poseidon: 10,
                        },
                    },
                    calldata_factor: ExecutionResources {
                        n_steps: 21,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 2,
                        },
                    },
                },
                deprecated_resources: ResourcesParams {
                    constant: ExecutionResources {
                        n_steps: 4015,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            range_check: 72,
                            pedersen: 23,
                        },
                    },
                    calldata_factor: ExecutionResources {
                        n_steps: 21,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 2,
                        },
                    },
                },
            },
            InvokeFunction: ResourcesByVersion {
                resources: ResourcesParams {
                    constant: ExecutionResources {
                        n_steps: 3904,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 4,
                            range_check: 74,
                            poseidon: 11,
                        },
                    },
                    calldata_factor: ExecutionResources {
                        n_steps: 8,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 1,
                        },
                    },
                },
                deprecated_resources: ResourcesParams {
                    constant: ExecutionResources {
                        n_steps: 3763,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 14,
                            range_check: 69,
                        },
                    },
                    calldata_factor: ExecutionResources {
                        n_steps: 8,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 1,
                        },
                    },
                },
            },
            L1Handler: ResourcesByVersion {
                resources: ResourcesParams {
                    constant: ExecutionResources {
                        n_steps: 0,
                        n_memory_holes: 0,
                        builtin_instance_counter: {},
                    },
                    calldata_factor: ExecutionResources {
                        n_steps: 13,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 1,
                        },
                    },
                },
                deprecated_resources: ResourcesParams {
                    constant: ExecutionResources {
                        n_steps: 1233,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            range_check: 16,
                            pedersen: 11,
                        },
                    },
                    calldata_factor: ExecutionResources {
                        n_steps: 13,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 1,
                        },
                    },
                },
            },
            Declare: ResourcesByVersion {
                resources: ResourcesParams {
                    constant: ExecutionResources {
                        n_steps: 3079,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 4,
                            range_check: 58,
                            poseidon: 10,
                        },
                    },
                    calldata_factor: ExecutionResources {
                        n_steps: 0,
                        n_memory_holes: 0,
                        builtin_instance_counter: {},
                    },
                },
                deprecated_resources: ResourcesParams {
                    constant: ExecutionResources {
                        n_steps: 2973,
                        n_memory_holes: 0,
                        builtin_instance_counter: {
                            pedersen: 16,
                            range_check: 53,
                        },
                    },
                    calldata_factor: ExecutionResources {
                        n_steps: 0,
                        n_memory_holes: 0,
                        builtin_instance_counter: {},
                    },
                },
            },
        },
        compute_os_kzg_commitment_info: ExecutionResources {
            n_steps: 113,
            n_memory_holes: 0,
            builtin_instance_counter: {
                range_check: 17,
            },
        },
    },
    vm_resource_fee_cost: {
        "ecdsa_builtin": Ratio {
            numer: 512,
            denom: 100,
        },
        "range_check_builtin": Ratio {
            numer: 4,
            denom: 100,
        },
        "keccak_builtin": Ratio {
            numer: 512,
            denom: 100,
        },
        "bitwise_builtin": Ratio {
            numer: 16,
            denom: 100,
        },
        "ec_op_builtin": Ratio {
            numer: 256,
            denom: 100,
        },
        "mul_mod_builtin": Ratio {
            numer: 4,
            denom: 100,
        },
        "output_builtin": Ratio {
            numer: 0,
            denom: 1,
        },
        "add_mod_builtin": Ratio {
            numer: 4,
            denom: 100,
        },
        "pedersen_builtin": Ratio {
            numer: 8,
            denom: 100,
        },
        "range_check96_builtin": Ratio {
            numer: 4,
            denom: 100,
        },
        "n_steps": Ratio {
            numer: 25,
            denom: 10000,
        },
        "poseidon_builtin": Ratio {
            numer: 8,
            denom: 100,
        },
    },
}
</blockquote></details>

where, for example, is the `l1_handler_version` field?
I'm only interested in where the new fields you added, are loaded; no need for the entire JSON

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/642)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 89 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/642#-O5hfjVP9Zi-4Yj8mda3:-O5hrgBe1b6XrVGuDHLu:bjfwqm4) ([raw file](https://github.com/starkware-libs/sequencer/blob/a08d1cdffc6c3e642fc2df13ef675febb8708ff1/crates/blockifier/resources/versioned_constants.json#L89)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where, for example, is the `l1_handler_version` field?
I'm only interested in where the new fields you added, are loaded; no need for the entire JSON
</blockquote></details>

the new fields that I added are not loaded,
they are un the additional fields of
```
OsConstants
```
and it's not used by the blockifier at all, as mentioned here
https://github.com/starkware-libs/sequencer/blob/d846784519cedc91d90796c16b8831d71da1052e/crates/blockifier/src/versioned_constants.rs#L517

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/642#-:-O5huHUo7JmPyySDifb_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
