### PR TITLE
feat(consensus): send proposal content

### PR DESCRIPTION
**Pull request by dan-starkware**

### CODE REVIEW

**Comment by dan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1810?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1810** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1810?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1809** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1809?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1808** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1808?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1807** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1807?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1806** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1806?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1774** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1774?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1810)* status: all files reviewed, 4 unresolved discussions (waiting on @asmaastarkware, @dan-starkware, and @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1810#-OAwMf2h8nnQmarzz3mf:-OAwMf2h8nnQmarzz3mg:b-hqknaf) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b85d335e2fdd0553f6c72e9dd56260f83571140/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context.rs#L308)):*
> ```XML
>                     transaction_hashes.push(tx.tx_hash());
>                     transactions.push(tx.tx());
>                 });
> ```

I prefer just using a for loop here. This is because iterators are usually lazy/don't have side effects, not doing anything unless there is a return value. This causes me to feel that `for_each` is surprising.

Documentation seems to agree "...It’s generally more idiomatic to use a `for` loop..."
https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.for_each



_Code quote:_
```XML
                txs.into_iter().for_each(|tx| {
                    transaction_hashes.push(tx.tx_hash());
                    transactions.push(tx.tx());
                });
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1810#-OAwNvOk8UeCW9PoYaO6:-OAwNvOk8UeCW9PoYaO7:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b85d335e2fdd0553f6c72e9dd56260f83571140/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L85)):*
> ```XML
>         mock_register_broadcast_topic().expect("Failed to create mock network");
>     let BroadcastTopicChannels { broadcasted_messages_receiver: _, broadcast_topic_client } =
>         subscriber_channels;
> ```





_Suggestion:_
```XML
    let BroadcastTopicChannels { broadcast_topic_client, .. } = subscriber_channels;
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1810#-OAwPGDKC-NT4lvyBdBi:-OAwPGDKC-NT4lvyBdBj:bpldi67) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b85d335e2fdd0553f6c72e9dd56260f83571140/crates/sequencing/papyrus_consensus_orchestrator/src/sequencer_consensus_context_test.rs#L88)):*
> ```XML
>     let BroadcastNetworkMock {
>         broadcasted_messages_sender: _mock_broadcasted_messages_sender, ..
>     } = mock_network;
> ```

Why destructure if we never use this?

I would have thought you'd do this to get the receiver out so that we can inspect the actual proposal content send out by the context.



_Code quote:_
```XML
    let BroadcastNetworkMock {
        broadcasted_messages_sender: _mock_broadcasted_messages_sender, ..
    } = mock_network;
```
___
*[`crates/starknet_api/src/executable_transaction.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1810#-OAwPp6A-rvYG1Kvcd2p:-OAwPp6A-rvYG1Kvcd2q:bd1zkj6) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b85d335e2fdd0553f6c72e9dd56260f83571140/crates/starknet_api/src/executable_transaction.rs#L62)):*
> ```XML
>             Transaction::Invoke(tx_data) => crate::transaction::Transaction::Invoke(tx_data.tx),
>         }
>     }
> ```

Should this be the `Into` trait? Or better yet "implement [`From`](https://doc.rust-lang.org/std/convert/trait.From.html "trait std::convert::From") instead" in the non-executable TX's location?



_Code quote:_
```XML
    pub fn tx(self) -> crate::transaction::Transaction {
        match self {
            Transaction::Declare(tx_data) => crate::transaction::Transaction::Declare(tx_data.tx),
            Transaction::DeployAccount(tx_data) => {
                crate::transaction::Transaction::DeployAccount(tx_data.tx)
            }
            Transaction::Invoke(tx_data) => crate::transaction::Transaction::Invoke(tx_data.tx),
        }
    }
```

**Review by matan-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1810)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Review by matan-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1810)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
