### PR TITLE
refactor(consensus): move fee_market to concensus

### PR DESCRIPTION
**Pull request by ayeletstarkware**

### CODE REVIEW

**Comment by ayeletstarkware** [comment]
* **#2977** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2977?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2977?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2977)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2977#-OF1sLxz4zIbvzWXrX-5:-OF1sLxz4zIbvzWXrX-6:b-67s0br) ([raw file](https://github.com/starkware-libs/sequencer/blob/eedeb1376cfb358a2f7b9b632540e6bce03b3a2f/crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs#L15)):*
> ```XML
> pub mod cende;
> 
> /// Fee market logic.
> ```

No need if it's just repeating the name of the module.



_Code quote:_
```XML
/// Fee market logic.
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2977#-OF1sJuyB6nxVgist3jF:-OF1sJuz0PmCcM8wO82J:b2s2ria) ([raw file](https://github.com/starkware-libs/sequencer/blob/eedeb1376cfb358a2f7b9b632540e6bce03b3a2f/crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs#L16)):*
> ```XML
> 
> /// Fee market logic.
> #[allow(missing_docs)]
> ```

What is this?



_Code quote:_
```XML
#[allow(missing_docs)]
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/fee_market_logic/mod.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2977#-OF1tkut-3ojtBPUCVeu:-OF1tkut-3ojtBPUCVev:b7axeh0) ([raw file](https://github.com/starkware-libs/sequencer/blob/eedeb1376cfb358a2f7b9b632540e6bce03b3a2f/crates/sequencing/papyrus_consensus_orchestrator/src/fee_market_logic/mod.rs#L1)):*
> ```XML
> pub mod fee_market;
> ```

The module is fee_market_logic, no need to declare another module here.
Also, move all the content of `fee_market.rs` here. You can rename `fee_market_logic` -> `fee_market`.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2977)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2977#-OF1sLxz4zIbvzWXrX-5:-OFGfmOM9FtwDEFWIj5W:b-yesy1g) ([raw file](https://github.com/starkware-libs/sequencer/blob/eedeb1376cfb358a2f7b9b632540e6bce03b3a2f/crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs#L15)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

No need if it's just repeating the name of the module.
</blockquote></details>

if we leave this documention we can remove the `#[allow(missing_docs)]`, so I left it. do you prefer I add more info about this module?
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2977#-OF1sJuyB6nxVgist3jF:-OFGhtJ41zFYfV5dxVof:b-fvdr1d) ([raw file](https://github.com/starkware-libs/sequencer/blob/eedeb1376cfb358a2f7b9b632540e6bce03b3a2f/crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs#L16)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What is this?
</blockquote></details>

answered above
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/fee_market_logic/mod.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2977#-OF1tkut-3ojtBPUCVeu:-OFGfl3r4qjCQWTzKbDa:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/eedeb1376cfb358a2f7b9b632540e6bce03b3a2f/crates/sequencing/papyrus_consensus_orchestrator/src/fee_market_logic/mod.rs#L1)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

The module is fee_market_logic, no need to declare another module here.
Also, move all the content of `fee_market.rs` here. You can rename `fee_market_logic` -> `fee_market`.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2977#-:-OFGmrZi05VOZA7SZH-1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2977#-OF1sLxz4zIbvzWXrX-5:-OFGmNVN2EhUlMDivz2-:bde3v7l) ([raw file](https://github.com/starkware-libs/sequencer/blob/eedeb1376cfb358a2f7b9b632540e6bce03b3a2f/crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs#L15)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

if we leave this documention we can remove the `#[allow(missing_docs)]`, so I left it. do you prefer I add more info about this module?
</blockquote></details>

This is fine in that case. Can you remove the `#[allow(missing_docs)]` from cende also?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2977)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2977#-OF1sLxz4zIbvzWXrX-5:-OFGnD99-Yy9BPfh247H:b-8qr3it) ([raw file](https://github.com/starkware-libs/sequencer/blob/eedeb1376cfb358a2f7b9b632540e6bce03b3a2f/crates/sequencing/papyrus_consensus_orchestrator/src/lib.rs#L15)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This is fine in that case. Can you remove the `#[allow(missing_docs)]` from cende also?
</blockquote></details>

I tried to, but more documentation is needed there (in `cende/mod.rs`).

**Pull request merged**
