### PR TITLE
feat(consensus): handle invalid vote

### PR DESCRIPTION
**Pull request by asmaastarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/228)

### CODE REVIEW

**Review by matan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/228)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Review by matan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/228)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware)

___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/228#-O3DELWx1TdTgGu-6UjJ:-O3DELWx1TdTgGu-6UjK:b-gpkkaz) ([raw file](https://github.com/starkware-libs/sequencer/blob/8df2f92b047e57902fb73ee41cfbc7bce5e63ab7/crates/sequencing/papyrus_consensus/src/types.rs#L168)):*
> ```XML
>     InvalidProposal(ValidatorId, BlockNumber, String),
>     #[error("Invalid vote sent by peer {0:?} at height {1}: {2}")]
>     InvalidVote(ValidatorId, BlockNumber, String),
> ```

Votes are of constant size so let's just print the whole thing along with the message.



_Suggestion:_
```XML
    #[error("Invalid vote {0:?}. {1}")]
    InvalidVote(ConsensusMessage, String),
```

**Review by asmaastarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/228)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/228#-O3DELWx1TdTgGu-6UjJ:-O3DpOO_9fazNzvxRYDm:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8df2f92b047e57902fb73ee41cfbc7bce5e63ab7/crates/sequencing/papyrus_consensus/src/types.rs#L168)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Votes are of constant size so let's just print the whole thing along with the message.
</blockquote></details>

Done.

**Review by matan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/228)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @asmaastarkware)

**Pull request merged**
