### PR TITLE
feat(blockifier): add caching for hot compilation of native contracts

### PR DESCRIPTION
**Pull request by rodrigo-pino**

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2080)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @rodrigo-pino and @varex83)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 293 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2080#-OBsori68BbSFm2_bINE:-OBsori68BbSFm2_bINF:bok2321) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0afc5a609077a0555d0a50df631f8c5db1d0652/crates/blockifier/src/test_utils/struct_impls.rs#L293)):*
> ```XML
>                 return cached_class.clone();
>             }
>         }
> ```

Is the outer scope to drop the lock of the cache? If so, I think this would be more readable 



_Suggestion:_
```XML
        
        let cache = CACHED.read().unwrap();
        if let Some(cached_class) = cache.get(path) {
            return cached_class.clone();
        }
        std::mem::drop(cache);
        
        
```
___
*[`crates/blockifier/src/execution/native/contract_class.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2080#-OBsnxguBa8_n93Uthya:-OBsnxguBa8_n93Uthyb:byvgdqt) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0afc5a609077a0555d0a50df631f8c5db1d0652/crates/blockifier/src/execution/native/contract_class.rs#L16)):*
> ```XML
> use crate::execution::errors::PreExecutionError;
> use crate::execution::native::utils::contract_entrypoint_to_entrypoint_selector;
> ```

Please revert

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2080)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @rodrigo-pino and @varex83)

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2080)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @rodrigo-pino, @varex83, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 250 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2080#-OBtrLV6CHxeiUw8dqlU:-OBtrLV73bKOjRp-CvnV:b4t7tsj) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0afc5a609077a0555d0a50df631f8c5db1d0652/crates/blockifier/src/test_utils/struct_impls.rs#L250)):*
> ```XML
> lazy_static! {
>     /// A cache for compiled native contract classes.
>     static ref CACHED: RwLock<HashMap<String, NativeContractClassV1>> = RwLock::new(HashMap::new());
> ```

Is this Cache shared between all of the tests?



_Code quote:_
```XML
 static ref CACHED: RwLock<HashMap<String, NativeContractClassV1>> = RwLock::new(HashMap::new());
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 250 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2080#-OBtrstw7HZoDkUGA4AR:-OBtrstw7HZoDkUGA4AS:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0afc5a609077a0555d0a50df631f8c5db1d0652/crates/blockifier/src/test_utils/struct_impls.rs#L250)):*
> ```XML
> lazy_static! {
>     /// A cache for compiled native contract classes.
>     static ref CACHED: RwLock<HashMap<String, NativeContractClassV1>> = RwLock::new(HashMap::new());
> ```





_Suggestion:_
```XML
COMPILED_NATIVE_CONTRACT_CACHED
```

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2080)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @rodrigo-pino, @varex83, and @Yoni-Starkware)

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2080)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @meship-starkware, @varex83, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/native/contract_class.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2080#-OBsnxguBa8_n93Uthya:-OBziPQP6Q9jv8yW9mWc:b9ui6zr) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0afc5a609077a0555d0a50df631f8c5db1d0652/crates/blockifier/src/execution/native/contract_class.rs#L16)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Please revert
</blockquote></details>

Not sure what do you mean?
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 250 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2080#-OBtrLV6CHxeiUw8dqlU:-OBziXFK9tqdd8IRwQ3P:b2nhswy) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0afc5a609077a0555d0a50df631f8c5db1d0652/crates/blockifier/src/test_utils/struct_impls.rs#L250)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Is this Cache shared between all of the tests?
</blockquote></details>

Yes
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 293 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2080#-OBsori68BbSFm2_bINE:-OBzjbpT06zbAXEIFm8d:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0afc5a609077a0555d0a50df631f8c5db1d0652/crates/blockifier/src/test_utils/struct_impls.rs#L293)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Is the outer scope to drop the lock of the cache? If so, I think this would be more readable
</blockquote></details>

Done
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 250 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2080#-OBtrstw7HZoDkUGA4AR:-OBzi_8wAIIL_flBaGVT:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/f0afc5a609077a0555d0a50df631f8c5db1d0652/crates/blockifier/src/test_utils/struct_impls.rs#L250)):*
> ```XML
> lazy_static! {
>     /// A cache for compiled native contract classes.
>     static ref CACHED: RwLock<HashMap<String, NativeContractClassV1>> = RwLock::new(HashMap::new());
> ```

Done

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2080)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware, @varex83, and @Yoni-Starkware)

**Review by avi-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2080)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @varex83 and @Yoni-Starkware)

**Review by avi-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2080)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @varex83 and @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2080)* status: all files reviewed, 1 unresolved discussion (waiting on @rodrigo-pino and @varex83)

___
*[`crates/blockifier/src/test_utils/contracts.rs` line 195 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2080#-OC3zC4a7d9uEmOrEBRn:-OC3zC4a7d9uEmOrEBRo:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/8fb02f11a12a187d8d81b920d0f167237f6e4487/crates/blockifier/src/test_utils/contracts.rs#L195)):*
> ```XML
>             // let native_contract_class =
>             // NativeContractClassV1::from_file(&self.get_compiled_path());
>             return RunnableContractClass::V1Native(native_contract_class);
> ```





_Suggestion:_
```XML
            return RunnableContractClass::V1Native(native_contract_class);
```

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2080)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @dorimedini-starkware, @meship-starkware, @varex83, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 251 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2080#-OC7l9v2DPKmGDcUA2KK:-OC8Gao800yPLcv1RNEG:bhlpdn4) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb8db36c4c846a3f664f6ee99dc1653e4be8de18/crates/blockifier/src/test_utils/struct_impls.rs#L251)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@dorimedini-starkware mentioned that we don't use this macro.
Please use `LazyLock` instead - it is part of the standard library
</blockquote></details>

Done, didn't know about this. I like it a lot more with `LazyLock`

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2080#-:-OC8Iidu1Bbjla9TUQLB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @varex83)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 251 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2080#-OC7l9v2DPKmGDcUA2KK:-OC8Iegm8qXJRpcR6LAk:b-ucfknh) ([raw file](https://github.com/starkware-libs/sequencer/blob/fb8db36c4c846a3f664f6ee99dc1653e4be8de18/crates/blockifier/src/test_utils/struct_impls.rs#L251)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

Done, didn't know about this. I like it a lot more with `LazyLock`
</blockquote></details>

Thanks!

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2080)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @varex83)

**Pull request merged**
