### PR TITLE
chore: add disabled function to ComponentConfig

### PR DESCRIPTION
**Pull request by nadin-Starkware**
commit-id:9673c1ca

---

**Stack**:
- #2867 ⬅
- #2866

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2867)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2867#-OEijlTV-spQS7Zqpq98:-OEijlTV-spQS7Zqpq99:bwotban) ([raw file](https://github.com/starkware-libs/sequencer/blob/f1fa7c4df87d90c1d7dcf0c48c6ed3f8a877385c/crates/starknet_integration_tests/src/config_utils.rs#L122)):*
> ```XML
>         ..ComponentConfig::default()
>     }
> }
> ```

Please format this function to be as `get_http_only_component_config`



_Code quote:_
```XML
pub async fn get_non_http_component_config(gateway_socket: SocketAddr) -> ComponentConfig {
    ComponentConfig {
        http_server: ActiveComponentExecutionConfig::disabled(),
        monitoring_endpoint: Default::default(),
        gateway: ReactiveComponentExecutionConfig::local_with_remote_enabled(gateway_socket),
        ..ComponentConfig::default()
    }
}
```
___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2867#-OEijvxT4Ke7X_WfcPdw:-OEijvxU-dRCIH04t31p:b-2ocweo) ([raw file](https://github.com/starkware-libs/sequencer/blob/f1fa7c4df87d90c1d7dcf0c48c6ed3f8a877385c/crates/starknet_integration_tests/src/config_utils.rs#L124)):*
> ```XML
> }
> 
> pub async fn get_remote_flow_test_config() -> Vec<ComponentConfig> {
> ```

Is this still for the `flow` test? If not, please rename.



_Code quote:_
```XML
get_remote_flow_test_config()
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2867)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2867#-OEijlTV-spQS7Zqpq98:-OEinHNrCHx_b_zFuNqv:b98buux) ([raw file](https://github.com/starkware-libs/sequencer/blob/f1fa7c4df87d90c1d7dcf0c48c6ed3f8a877385c/crates/starknet_integration_tests/src/config_utils.rs#L122)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please format this function to be as `get_http_only_component_config`
</blockquote></details>

`Default` doesn't provide mutable fields for assignment after creation.
___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2867#-OEijvxT4Ke7X_WfcPdw:-OEinHjUC-5rvqdpUUYI:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f1fa7c4df87d90c1d7dcf0c48c6ed3f8a877385c/crates/starknet_integration_tests/src/config_utils.rs#L124)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Is this still for the `flow` test? If not, please rename.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2867)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2867#-OEijlTV-spQS7Zqpq98:-OEmyziv5H40uS_6cfBJ:b-uog8fv) ([raw file](https://github.com/starkware-libs/sequencer/blob/f1fa7c4df87d90c1d7dcf0c48c6ed3f8a877385c/crates/starknet_integration_tests/src/config_utils.rs#L122)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

`Default` doesn't provide mutable fields for assignment after creation.
</blockquote></details>

```
let mut config = ComponentConfig::Default()
config.X = Y
```
That doesn't work?

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2867)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/starknet_integration_tests/src/config_utils.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2867#-OEijlTV-spQS7Zqpq98:-OEnGHlhAYyYj75CtwNE:bb710yj) ([raw file](https://github.com/starkware-libs/sequencer/blob/f1fa7c4df87d90c1d7dcf0c48c6ed3f8a877385c/crates/starknet_integration_tests/src/config_utils.rs#L122)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

```
let mut config = ComponentConfig::Default()
config.X = Y
```
That doesn't work?
</blockquote></details>

Nope

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2867#-:-OEnRRrB3ckKOeaLWEhU:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved

**Review by nadin-Starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2867)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Pull request merged**
