### PR TITLE
refactor(consensus): create manager which encapsulates messages cached between heights

### PR DESCRIPTION
**Pull request by matan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/200)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/200?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#200** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/200?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#112** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/112?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#166** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/166?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/200#-:-O32KJDlDICWu3QkfUGa:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/200)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @asmaastarkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 57 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/200#-O3Qx9a4CgWg5dnX5yVH:-O3Qx9a4CgWg5dnX5yVI:b-jhft14) ([raw file](https://github.com/starkware-libs/sequencer/blob/b143026b16b40d1604330672281eb7b8e223ad8b/crates/sequencing/papyrus_consensus/src/lib.rs#L57)):*
> ```XML
>     loop {
>         let decision = manager
>             .run_height(&mut context, current_height, validator_id, &mut network_receiver)
> ```

Add TODO to support failed rounds (unless the plan is that run_height will run several rounds until it reaches a decision)
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/200#-O3Qwfp37qnsSNZXwi9A:-O3Qwfp37qnsSNZXwi9B:b-9g43c6) ([raw file](https://github.com/starkware-libs/sequencer/blob/b143026b16b40d1604330672281eb7b8e223ad8b/crates/sequencing/papyrus_consensus/src/manager.rs#L26)):*
> ```XML
> use crate::ProposalWrapper;
> 
> /// Used run Tendermint. Handles issues which are not explicitly part of the single height consensus
> ```

WDYM "Used run Tendermint"? Try to improve this sentence
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/200#-O3QxSnQCAGQ8_GvOAt3:-O3QxSnQCAGQ8_GvOAt4:b-fz2tqf) ([raw file](https://github.com/starkware-libs/sequencer/blob/b143026b16b40d1604330672281eb7b8e223ad8b/crates/sequencing/papyrus_consensus/src/manager_test.rs#L27)):*
> ```XML
> #[derive(Debug, PartialEq, Clone)]
> pub struct TestBlock {
>     pub content: Vec<Transaction>,
> ```

Why not use something simpler than Transaction, like u64?
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 117 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/200#-O3QxllT8PsVYTCKdgAw:-O3QxllT8PsVYTCKdgAx:b-iolotu) ([raw file](https://github.com/starkware-libs/sequencer/blob/b143026b16b40d1604330672281eb7b8e223ad8b/crates/sequencing/papyrus_consensus/src/manager_test.rs#L117)):*
> ```XML
> 
> #[tokio::test]
> async fn run_multiple_heights() {
> ```

rename to run_multiple_heights_unordered

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/200)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @asmaastarkware and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 57 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/200#-O3Qx9a4CgWg5dnX5yVH:-O3RUGESCri6PQ5R1lcg:bepxa5h) ([raw file](https://github.com/starkware-libs/sequencer/blob/b143026b16b40d1604330672281eb7b8e223ad8b/crates/sequencing/papyrus_consensus/src/lib.rs#L57)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to support failed rounds (unless the plan is that run_height will run several rounds until it reaches a decision)
</blockquote></details>

A height contains multiple rounds. This is something the manager doesn't need to consider.
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/200#-O3Qwfp37qnsSNZXwi9A:-O3RUaidAKYyKIYJgqRg:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b143026b16b40d1604330672281eb7b8e223ad8b/crates/sequencing/papyrus_consensus/src/manager.rs#L26)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

WDYM "Used run Tendermint"? Try to improve this sentence
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/200#-O3QxSnQCAGQ8_GvOAt3:-O3RTPFlDCiFMmk2XSDE:b-e0hkv5) ([raw file](https://github.com/starkware-libs/sequencer/blob/b143026b16b40d1604330672281eb7b8e223ad8b/crates/sequencing/papyrus_consensus/src/manager_test.rs#L27)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why not use something simpler than Transaction, like u64?
</blockquote></details>

Because we don't support streaming yet. We have the `Proposal` ConsensusMessage which includes the field for `Transaction`. When we support streaming I will instead make us generic on:
```
ConsensusStreamMessage: From<ProposalInit> + From<ProposalFin>
```

I tried faking this genericness now and it lead to a lot of ugly code, so I'd prefer to have the complexity in my test until we have streaming.
___
*[`crates/sequencing/papyrus_consensus/src/manager_test.rs` line 117 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/200#-O3QxllT8PsVYTCKdgAw:-O3RU6xO9YN7j1weM4pb:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/b143026b16b40d1604330672281eb7b8e223ad8b/crates/sequencing/papyrus_consensus/src/manager_test.rs#L117)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

rename to run_multiple_heights_unordered
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/200)* status: all files reviewed, 3 unresolved discussions (waiting on @asmaastarkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 28 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/200#-O3Rn7o1BibJdagwxnoE:-O3Rn7o1BibJdagwxnoF:btly7e6) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd1cdfae3f1b33a5bdd788f99ceb711e92b16c45/crates/sequencing/papyrus_consensus/src/manager.rs#L28)):*
> ```XML
> /// Runs Tendermint repeatedly across different heights. Handles issues which are not explicitly
> /// part of the single height consensus algorithm (e.g. messages from future heights).
> pub struct Manager {
> ```

Consider renaming to HeightManager or MultiHeightManager
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 29 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/200#-O3Rnsgc0Q0JNJA_Sfyx:-O3Rnsgc0Q0JNJA_Sfyy:b-lxys6z) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd1cdfae3f1b33a5bdd788f99ceb711e92b16c45/crates/sequencing/papyrus_consensus/src/manager.rs#L29)):*
> ```XML
> /// part of the single height consensus algorithm (e.g. messages from future heights).
> pub struct Manager {
>     cached_messages: Vec<ConsensusMessage>,
> ```

Change this to HashMap<Height, Vec<ConsensusMessage>>. Then cleaning it up will be much more efficient
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 70 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/200#-O3Ro-i65QxLvFRy9SQp:-O3Ro-i65QxLvFRy9SQq:b-1tth34) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd1cdfae3f1b33a5bdd788f99ceb711e92b16c45/crates/sequencing/papyrus_consensus/src/manager.rs#L70)):*
> ```XML
>         let mut current_height_messages = Vec::new();
>         for msg in std::mem::take(&mut self.cached_messages) {
>             match height.0.cmp(&msg.height()) {
> ```

Change the ordering of cmp here so that it will be clearer what's going on in the match arms. You should have in the left the thing that's always changing and in the right the constant thing

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/200#-:-O3RoSj96eXr5DKWTkCo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @asmaastarkware and @matan-starkware)

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/200)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @asmaastarkware and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 29 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/200#-O3Rnsgc0Q0JNJA_Sfyx:-O3RqM_cBSn1etyPs7MJ:b-jgclnc) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd1cdfae3f1b33a5bdd788f99ceb711e92b16c45/crates/sequencing/papyrus_consensus/src/manager.rs#L29)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change this to HashMap<Height, Vec<ConsensusMessage>>. Then cleaning it up will be much more efficient
</blockquote></details>

Sure, but I consider this to be part of the refactor (next PR). I'd like to keep this one just moving the existing code.
___
*[`crates/sequencing/papyrus_consensus/src/manager.rs` line 70 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/200#-O3Ro-i65QxLvFRy9SQp:-O3Rph3_1bre43niUi7G:b-rqqyp0) ([raw file](https://github.com/starkware-libs/sequencer/blob/dd1cdfae3f1b33a5bdd788f99ceb711e92b16c45/crates/sequencing/papyrus_consensus/src/manager.rs#L70)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change the ordering of cmp here so that it will be clearer what's going on in the match arms. You should have in the left the thing that's always changing and in the right the constant thing
</blockquote></details>

You put this comment in 208 earlier and I already did it, so to avoid conflicts I'll just leave it there.

**Review by asmaastarkware — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/200)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Comment by matan-starkware** [comment]
### Merge activity

* **Aug 4, 7:35 AM EDT**: @matan-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/200).

**Pull request merged**
