### PR TITLE
feat(gateway): return GatewaySpecErrr to match the SN spec

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/202)

### CODE REVIEW

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 12 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/202)* status: 12 of 13 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/202#-O370KVL07y15rqFBuk0:-O370KVL07y15rqFBuk1:b-knvnqx) ([raw file](https://github.com/starkware-libs/sequencer/blob/79dd9c950dae617c45513f26a65ef69030100705/crates/gateway/src/compilation.rs#L69)):*
> ```XML
>             })?,
>             Err(_panicked_compilation) => {
>                 // TODO(Arni): Log the panic.
> ```

Can be removed?



_Code quote:_
```XML
// TODO(Arni): Log the panic.
```
___
*[`crates/gateway/src/errors.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/202#-O36X9hM8-rBwJmF-02I:-O36X9hM8-rBwJmF-02J:baoij1y) ([raw file](https://github.com/starkware-libs/sequencer/blob/79dd9c950dae617c45513f26a65ef69030100705/crates/gateway/src/errors.rs#L46)):*
> ```XML
>         let status = resp.status();
>         let body = serde_json::to_string(resp.body()).expect("Expecting valid body");
>         (status, body).into_response()
> ```

Isn't `resp` already the `Response` we want to return?



_Code quote:_
```XML
        let status = resp.status();
        let body = serde_json::to_string(resp.body()).expect("Expecting valid body");
        (status, body).into_response()
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/202#-O36_xNIDMSqUdgM0y_R:-O36_xNIDMSqUdgM0y_S:bnwzxte) ([raw file](https://github.com/starkware-libs/sequencer/blob/79dd9c950dae617c45513f26a65ef69030100705/crates/gateway/src/stateful_transaction_validator.rs#L88)):*
> ```XML
>         validator
>             .validate(account_tx, skip_validate)
>             .map_err(|err| GatewaySpecError::ValidationFailure { data: err.to_string() })?;
> ```

Not sure all the errors should be mapped to `GatewaySpecError::ValidationError`.
For example, `StateError::UndeclaredClassHash` can be mapped to `GatewaySpecError::ClassHashNotFound`



_Code quote:_
```XML
.map_err(|err| GatewaySpecError::ValidationFailure { data: err.to_string() })?;
```
___
*[`crates/gateway/src/utils.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/202#-O36zFq61eLArYH2A4-X:-O36zFq61eLArYH2A4-Y:b-amezvs) ([raw file](https://github.com/starkware-libs/sequencer/blob/79dd9c950dae617c45513f26a65ef69030100705/crates/gateway/src/utils.rs#L111)):*
> ```XML
>                 .calculate_transaction_hash(chain_id, &declare_tx.version())
>                 .map_err(|e| {
>                     debug!("Failed to calculate tx hash: {}", e);
> ```

How did you decide the tracing level of each error (`error` vs `debug`)?



_Code quote:_
```XML
debug!
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/202)* status: 12 of 13 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/gateway/src/compilation.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/202#-O370KVL07y15rqFBuk0:-O37ATl89ooXwq-EZik8:bfqk2tg) ([raw file](https://github.com/starkware-libs/sequencer/blob/79dd9c950dae617c45513f26a65ef69030100705/crates/gateway/src/compilation.rs#L69)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can be removed?
</blockquote></details>

I meant the panic message - it's a weird type that doesn't implement ToString
___
*[`crates/gateway/src/errors.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/202#-O36X9hM8-rBwJmF-02I:-O37Agg31mnl4ql-LIm1:b-ib4drf) ([raw file](https://github.com/starkware-libs/sequencer/blob/79dd9c950dae617c45513f26a65ef69030100705/crates/gateway/src/errors.rs#L46)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Isn't `resp` already the `Response` we want to return?
</blockquote></details>

Unfortunately no, the generic type is different.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/202#-O36_xNIDMSqUdgM0y_R:-O37CghFCMz7D3I1AT7I:b-hrhpvu) ([raw file](https://github.com/starkware-libs/sequencer/blob/79dd9c950dae617c45513f26a65ef69030100705/crates/gateway/src/stateful_transaction_validator.rs#L88)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Not sure all the errors should be mapped to `GatewaySpecError::ValidationError`.
For example, `StateError::UndeclaredClassHash` can be mapped to `GatewaySpecError::ClassHashNotFound`
</blockquote></details>

I will ask product
___
*[`crates/gateway/src/utils.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/202#-O36zFq61eLArYH2A4-X:-O37C7XvADu6Tby2EZRb:b-d7lpwu) ([raw file](https://github.com/starkware-libs/sequencer/blob/79dd9c950dae617c45513f26a65ef69030100705/crates/gateway/src/utils.rs#L111)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

How did you decide the tracing level of each error (`error` vs `debug`)?
</blockquote></details>

I think here it should be `error` actually.

In general, `error` when it's a bug/internal error and `debug` when it's the user's fault (bad input)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/202)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/202#-O3XHWWo4PDF7d0J_YiU:-O3XHWWo4PDF7d0J_YiV:b-eurkta) ([raw file](https://github.com/starkware-libs/sequencer/blob/79dd9c950dae617c45513f26a65ef69030100705/crates/gateway/src/stateful_transaction_validator_test.rs#L94)):*
> ```XML
> 
>     let mut mock_validator = MockStatefulTransactionValidatorTrait::new();
>     mock_validator.expect_validate().return_once(|_, _| expected_result.map(|_| ()));
> ```

What does this do?



_Code quote:_
```XML
.map(|_| ()))
```
___
*[`crates/gateway/src/utils.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/202#-O36zFq61eLArYH2A4-X:-O3XIC8QEqnxzmL3GFFH:b5sbri5) ([raw file](https://github.com/starkware-libs/sequencer/blob/79dd9c950dae617c45513f26a65ef69030100705/crates/gateway/src/utils.rs#L111)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think here it should be `error` actually.

In general, `error` when it's a bug/internal error and `debug` when it's the user's fault (bad input)
</blockquote></details>

I also think it should be an error. And also the other `debug!` below.

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/202)* status: 2 of 13 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/202#-O3XHWWo4PDF7d0J_YiU:-O44cl0dBMNwURTmSrEZ:b-ls64ti) ([raw file](https://github.com/starkware-libs/sequencer/blob/79dd9c950dae617c45513f26a65ef69030100705/crates/gateway/src/stateful_transaction_validator_test.rs#L94)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What does this do?
</blockquote></details>

The expected result argument is `Result<TransactionHash, BlockifierError`, but the blockifier shouldn't return the tx hash, just an error if it occurred.
___
*[`crates/gateway/src/utils.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/202#-O36zFq61eLArYH2A4-X:-O4554IPBsZZ-ih2owMb:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/79dd9c950dae617c45513f26a65ef69030100705/crates/gateway/src/utils.rs#L111)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I also think it should be an error. And also the other `debug!` below.
</blockquote></details>

Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 9 of 11 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/202#-:-O45O1ra77w9vKhczsY6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yael-Starkware)

**Review by dafnamatsry — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/202)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
