### PR TITLE
test: add p2p transaction sync happy flow test

### PR DESCRIPTION
**Pull request by noamsp-starkware**

### CODE REVIEW

**Comment by noamsp-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2154?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2154** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2154?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2154?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2147** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2147?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#1942](https://github.com/starkware-libs/sequencer/pull/1942) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1942?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2154)* status: all files reviewed, 4 unresolved discussions (waiting on @noamsp-starkware)

___
*[`crates/papyrus_test_utils/src/lib.rs` line 1130 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2154#-OCXFsMk9qYQD3bRaW12:-OCXFsMk9qYQD3bRaW13:b-mp619h) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7ca8381ce9edfa681e28a239597c4f77ed066b2/crates/papyrus_test_utils/src/lib.rs#L1130)):*
> ```XML
> }
> 
> // TODO: Match memeber types for ExecutionResources and protobuf::receipt::ExecutionResources.
> ```

Match makes people think of rust's match. Rephrase to "fix mismatch of ..."
___
*[`crates/papyrus_test_utils/src/lib.rs` line 1130 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2154#-OCXFzHO7R19eOO3GxZC:-OCXFzHP4jfFFlIhSudf:b-y0dpn) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7ca8381ce9edfa681e28a239597c4f77ed066b2/crates/papyrus_test_utils/src/lib.rs#L1130)):*
> ```XML
> }
> 
> // TODO: Match memeber types for ExecutionResources and protobuf::receipt::ExecutionResources.
> ```

for -> between
___
*[`crates/papyrus_p2p_sync/src/client/transaction_test.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2154#-OCXF50x5AoMj6TEf49R:-OCXF50x5AoMj6TEf49S:b-7v52xy) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7ca8381ce9edfa681e28a239597c4f77ed066b2/crates/papyrus_p2p_sync/src/client/transaction_test.rs#L90)):*
> ```XML
>         .await;
> 
>         // Simulate time has passed so that state diff sync will resend query after it waited for
> ```

Change the comment to match transactions
___
*[`crates/papyrus_p2p_sync/src/client/transaction_test.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2154#-OCXFcgC0GJO_O3TJ0QW:-OCXFCQ07IrEBqRNL6B0:bswj90e) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7ca8381ce9edfa681e28a239597c4f77ed066b2/crates/papyrus_p2p_sync/src/client/transaction_test.rs#L97)):*
> ```XML
> 
>         let num_transaction_queries = HEADER_QUERY_LENGTH.div_ceil(TRANSACTION_QUERY_LENGTH);
>         for transaction_querie in 0..num_transaction_queries {
> ```

Change this index name into start_block_number and add a step to the iteration

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2154)* status: all files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/client/transaction_test.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2154#-OCXF50x5AoMj6TEf49R:-OCYqRyF3bAmVlLufpdC:b2nhb2c) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7ca8381ce9edfa681e28a239597c4f77ed066b2/crates/papyrus_p2p_sync/src/client/transaction_test.rs#L90)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change the comment to match transactions
</blockquote></details>

Ack
___
*[`crates/papyrus_p2p_sync/src/client/transaction_test.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2154#-OCXFcgC0GJO_O3TJ0QW:-OCYsfpb6LK5wg7Dnwec:b7lkeur) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7ca8381ce9edfa681e28a239597c4f77ed066b2/crates/papyrus_p2p_sync/src/client/transaction_test.rs#L97)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change this index name into start_block_number and add a step to the iteration
</blockquote></details>

What do you mean by adding a step to the iteration?
___
*[`crates/papyrus_test_utils/src/lib.rs` line 1130 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2154#-OCXFsMk9qYQD3bRaW12:-OCYtCZZ4y89LBwAGaNJ:b2nhb2c) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7ca8381ce9edfa681e28a239597c4f77ed066b2/crates/papyrus_test_utils/src/lib.rs#L1130)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Match makes people think of rust's match. Rephrase to "fix mismatch of ..."
</blockquote></details>

Ack
___
*[`crates/papyrus_test_utils/src/lib.rs` line 1130 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2154#-OCXFzHO7R19eOO3GxZC:-OCYtE4-Erf6SDE8QYsR:b2nhb2c) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7ca8381ce9edfa681e28a239597c4f77ed066b2/crates/papyrus_test_utils/src/lib.rs#L1130)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

for -> between
</blockquote></details>

Ack

**Review by noamsp-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2154)* status: all files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_p2p_sync/src/client/transaction_test.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2154#-OCXFcgC0GJO_O3TJ0QW:-OCcJQF29YcPv3RcW75D:b2nhb2c) ([raw file](https://github.com/starkware-libs/sequencer/blob/c7ca8381ce9edfa681e28a239597c4f77ed066b2/crates/papyrus_p2p_sync/src/client/transaction_test.rs#L97)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

https://stackoverflow.com/questions/27893223/how-do-i-iterate-over-a-range-with-a-custom-step
</blockquote></details>

Ack

**Pull request merged**
