### PR TITLE
feat(batcher, mempool_node): add local storage to the batcher

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/982)

### CODE REVIEW

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/982)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry, @dan-starkware, @lev-starkware, and @yair-starkware)

___
*[`config/mempool/default_config.json` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/982#-O7Z6jWoCLVurkaUdNsx:-O7Z6jWp3-gEDwMY5dWD:b-64bnxt) ([raw file](https://github.com/starkware-libs/sequencer/blob/639ef1f26fe2db5e5aa22848272eae34f96e3bc5/config/mempool/default_config.json#L1)):*
> ```JSON
> {
> ```

why is this file called mempool/default_config? 
should it be sequencer/default_config?

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/982)* status: 8 of 9 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry, @dan-starkware, @lev-starkware, and @Yael-Starkware)

___
*[`config/mempool/default_config.json` line 1 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/982#-O7Z6jWoCLVurkaUdNsx:-O7cLxSXEa5SM6OIxcbd:briac1g) ([raw file](https://github.com/starkware-libs/sequencer/blob/639ef1f26fe2db5e5aa22848272eae34f96e3bc5/config/mempool/default_config.json#L1)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why is this file called mempool/default_config? 
should it be sequencer/default_config?
</blockquote></details>

This is not related to this PR...
___
*[`config/mempool/default_config.json` line 52 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/982#-O7bx9tc16kQiXb9WP_M:-O7cMB6a9jVDtWEO46XR:bbvnobv) ([raw file](https://github.com/starkware-libs/sequencer/blob/639ef1f26fe2db5e5aa22848272eae34f96e3bc5/config/mempool/default_config.json#L52)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Shouldn't we use the same chain ID already configured in the `storage.db_config`?
</blockquote></details>

It does - I made the `storage.db_config.chain_id` point to this param so other components that need the chain ID will share the same value.
___
*[`crates/batcher/src/batcher.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/982#-O7brMta7gfNAVVIfzwQ:-O7cOfCCCmau7g4H82ob:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/639ef1f26fe2db5e5aa22848272eae34f96e3bc5/crates/batcher/src/batcher.rs#L22)):*
> ```XML
>         config: BatcherConfig,
>         mempool_client: SharedMempoolClient,
>         local_storage: Arc<dyn BatcherStorageTrait>,
> ```

Done.
___
*[`crates/batcher/src/batcher.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/982#-O7bn7dY3OS3mROadLtb:-O7cOr2qDhLTPsOvEWvS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/639ef1f26fe2db5e5aa22848272eae34f96e3bc5/crates/batcher/src/batcher.rs#L38)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Is it intended to be only a reader? If so, please rename to `StorageReaderTrait`
</blockquote></details>

Done.
___
*[`crates/mempool_node/src/config/mod.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/982#-O7bvkGv7oHh4QbEABOa:-O7cNSUeEcHunY7ghMSn:bz29ihq) ([raw file](https://github.com/starkware-libs/sequencer/blob/639ef1f26fe2db5e5aa22848272eae34f96e3bc5/crates/mempool_node/src/config/mod.rs#L41)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Is it possible to somehow put pointer value (`ChainId::Mainnet`) in the config json file?
It is a little confusing that some values are defined there and some here...
</blockquote></details>

The json file is generated automatically from the `ComponentConfig` struct and this pointer mapping.
You can see in the json that there is already a `chain_id` param with the default value and that the `storage.db_config.chain_id` points to that value.

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/982)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @lev-starkware, and @Yael-Starkware)

___
*[`crates/mempool_node/src/config/mod.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/982#-O7bvkGv7oHh4QbEABOa:-O7cRL6J9CrmHzZhHdlP:bhrhnqk) ([raw file](https://github.com/starkware-libs/sequencer/blob/639ef1f26fe2db5e5aa22848272eae34f96e3bc5/crates/mempool_node/src/config/mod.rs#L41)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The json file is generated automatically from the `ComponentConfig` struct and this pointer mapping.
You can see in the json that there is already a `chain_id` param with the default value and that the `storage.db_config.chain_id` points to that value.
</blockquote></details>

Ok, I misunderstood how it works. Thanks.

**Review by lev-starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/982#-:-O7cjCAeEzY2AXX94JjY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @Yael-Starkware)

**Pull request merged**
