### PR TITLE
refactor(starknet_batcher): add getters to the proposal manger

### PR DESCRIPTION
**Pull request by dafnamatsry**

### CODE REVIEW

**Comment by dafnamatsry** [comment]
* **#2441** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2441?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2480** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2480?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2480?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2480)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @dafnamatsry)

___
*[`crates/starknet_batcher/src/proposal_manager.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2480#-OD_Nv_l571SMlnKhgVf:-OD_Nv_l571SMlnKhgVg:brgfhqt) ([raw file](https://github.com/starkware-libs/sequencer/blob/f37c9423885ca1f81ffa8db7d756c81d08a07471/crates/starknet_batcher/src/proposal_manager.rs#L93)):*
> ```XML
>     pub abort_signal_sender: tokio::sync::oneshot::Sender<()>,
>     pub join_handle: tokio::task::JoinHandle<()>,
> }
> ```

why is the pub required?



_Code quote:_
```XML
pub struct ProposalTask {
    pub abort_signal_sender: tokio::sync::oneshot::Sender<()>,
    pub join_handle: tokio::task::JoinHandle<()>,
}
```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2480)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @Yael-Starkware)

___
*[`crates/starknet_batcher/src/proposal_manager.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2480#-OD_Nv_l571SMlnKhgVf:-OD_YnfO15V7dZORP6Ga:b-4w4s2y) ([raw file](https://github.com/starkware-libs/sequencer/blob/f37c9423885ca1f81ffa8db7d756c81d08a07471/crates/starknet_batcher/src/proposal_manager.rs#L93)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why is the pub required?
</blockquote></details>

Removed. (left by mistake)

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2480)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2480#-:-ODaZXge9yACD5FjFdc1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Comment by dafnamatsry** [comment]
### Merge activity

* **Dec 9, 6:47 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2480).

**Pull request merged**
