### PR TITLE
chore(blockifier): remove only_qury from IvokeTxArgs

### PR DESCRIPTION
**Pull request by avivg-starkware**

### CODE REVIEW

**Comment by avivg-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2437?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2437** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2437?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2437?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2431** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2431?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2429** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2429?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2428** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2428?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2354](https://github.com/starkware-libs/sequencer/pull/2354) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2354?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2412** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2412?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2377** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2377?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2331** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2331?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2437#-:-ODCAQHI7se7TUvu6UQr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avivg-starkware)

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2437)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 310 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2437#-ODL8GTY4OWqOUVgM2Dr:-ODL8GTZ2-bVHix55Lz7:b-s0qbiq) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3d0730c5e69c2416a054f828667b4f8ac62fe6f/crates/blockifier/src/transaction/account_transactions_test.rs#L310)):*
> ```XML
>     #[case] tx_version: TransactionVersion,
>     #[case] resource_bounds: ValidResourceBounds,
>     #[values(true, false)] only_query: bool,
> ```

when removing 'only_query' from InvokeTxArgs this bool is no longer used. the test anyway pass, it doesn't seem like 'only_query' is used to effect the run. @Yoni-Starkware  Do you think removing it is wanted?  
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 188 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2437#-ODL99st0hPk3-_hNcD1:-ODL99st0hPk3-_hNcD2:b-x4w4tc) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3d0730c5e69c2416a054f828667b4f8ac62fe6f/crates/blockifier/src/transaction/execution_flavors_test.rs#L188)):*
> ```XML
>     cairo_version: CairoVersion,
>     version: TransactionVersion,
>     only_query: bool,
> ```

same as above. 
it doesn't seem like 'only_query' is used to effect the run. 
@Yoni-Starkware  Do you think removing it is wanted?

**Review by Yoni-Starkware — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2437#-:-ODLSJm697FN_shqBHUx:bnfp4nl)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @avivg-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 310 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2437#-ODL8GTY4OWqOUVgM2Dr:-ODLRfPm1tyBZZlcIr3S:b-so3fo0) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3d0730c5e69c2416a054f828667b4f8ac62fe6f/crates/blockifier/src/transaction/account_transactions_test.rs#L310)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

when removing 'only_query' from InvokeTxArgs this bool is no longer used. the test anyway pass, it doesn't seem like 'only_query' is used to effect the run. @Yoni-Starkware  Do you think removing it is wanted?
</blockquote></details>

It's okay to remove it from this one. 
`execution_falvors_test` tests this bool extensively
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 188 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2437#-ODL99st0hPk3-_hNcD1:-ODLRX0O8-fxNL_00bIF:b89lmsg) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3d0730c5e69c2416a054f828667b4f8ac62fe6f/crates/blockifier/src/transaction/execution_flavors_test.rs#L188)):*
<details><summary><i>Previously, avivg-starkware wrote…</i></summary><blockquote>

same as above. 
it doesn't seem like 'only_query' is used to effect the run. 
@Yoni-Starkware  Do you think removing it is wanted?
</blockquote></details>

Yes - if the tests pass this bool directly to the AccountTransaction now, you can remove it.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 307 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2437#-ODLSEhO9sS6-TIHgTPU:-ODLSEhO9sS6-TIHgTPV:b-xo3k0j) ([raw file](https://github.com/starkware-libs/sequencer/blob/e76d5a444edc4ff1a56fe4d442db0e1871a796e0/crates/blockifier/src/transaction/test_utils.rs#L307)):*
> ```XML
> pub fn account_invoke_tx(invoke_args: InvokeTxArgs) -> AccountTransaction {
>     let only_query = invoke_args.only_query;
>     let execution_flags = ExecutionFlags { only_query, ..ExecutionFlags::default() };
> ```

Use new_with_default_flags



_Code quote:_
```XML
    let execution_flags = ExecutionFlags::default();
    AccountTransaction { tx: invoke_tx(invoke_args), execution_flags }
```

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2437)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 310 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2437#-ODL8GTY4OWqOUVgM2Dr:-ODLbvlz7RVD3CzEwQeq:bh0u7y3) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3d0730c5e69c2416a054f828667b4f8ac62fe6f/crates/blockifier/src/transaction/account_transactions_test.rs#L310)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

It's okay to remove it from this one. 
`execution_falvors_test` tests this bool extensively
</blockquote></details>

cool perfect
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 188 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2437#-ODL99st0hPk3-_hNcD1:-ODLc4bP4J0TUEDbydaF:bd5l6mr) ([raw file](https://github.com/starkware-libs/sequencer/blob/a3d0730c5e69c2416a054f828667b4f8ac62fe6f/crates/blockifier/src/transaction/execution_flavors_test.rs#L188)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Yes - if the tests pass this bool directly to the AccountTransaction now, you can remove it.
</blockquote></details>

thanks!

**Review by avivg-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2437)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 307 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2437#-ODLSEhO9sS6-TIHgTPU:-ODMWHCoAP1jHdvWOnr6:bjuhzs6) ([raw file](https://github.com/starkware-libs/sequencer/blob/e76d5a444edc4ff1a56fe4d442db0e1871a796e0/crates/blockifier/src/transaction/test_utils.rs#L307)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Use new_with_default_flags
</blockquote></details>

Done in following PR #2479

**Review by avivg-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2437)* status: all files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)

**Pull request merged**
