### PR TITLE
chore(infra_utils): add short_module_name util

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #2656
- #2655 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2655)* status: all files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/infra_utils/src/type_name.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2655#-OE8szUnBtNv44xfz9bV:-OE8szUnBtNv44xfz9bW:b-cj1wq) ([raw file](https://github.com/starkware-libs/sequencer/blob/2279521e561915d4cfb9126284c0725748b59749/crates/infra_utils/src/type_name.rs#L17)):*
> ```XML
> /// # Algorithm
> /// The function maintains two indices, `back` and `ahead`, where:
> /// - `back` tracks the start of the current segment.
> ```

Rename them to reflect this
back -> curr_segment_start
ahead -> string_iter
___
*[`crates/infra_utils/src/type_name.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2655#-OE8tSJsB_F-wcsgzAjj:-OE8tSJsB_F-wcsgzAjk:byjnpfj) ([raw file](https://github.com/starkware-libs/sequencer/blob/2279521e561915d4cfb9126284c0725748b59749/crates/infra_utils/src/type_name.rs#L37)):*
> ```XML
> /// - It processes the string in a single pass, ensuring linear time complexity.
> fn truncate_type(input: &str) -> String {
>     let mut buffer = String::new();
> ```

rename buffer to result
___
*[`crates/infra_utils/src/type_name.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2655#-OE8qCkB6fNpy-t67ar5:-OE8qCkB6fNpy-t67ar6:b-xj6aoa) ([raw file](https://github.com/starkware-libs/sequencer/blob/2279521e561915d4cfb9126284c0725748b59749/crates/infra_utils/src/type_name.rs#L38)):*
> ```XML
> fn truncate_type(input: &str) -> String {
>     let mut buffer = String::new();
>     let mut back = 0;
> ```

use iterators instead of indices

The code will look like this
```
while let Some(ahead_char) = ahead.next() {
    if ahead_char == '<' || ... {
        ...
        back = ahead.clone();
        back.next();
    }
    if ahead_char == ':' && ahead.peek() == Some(':') {
        ahead = ahead.next();
        back = ahead.clone();
        back.next();
    }
}
```

___
*[`crates/infra_utils/src/type_name.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2655#-OE8sDQe0CRd7r_kVani:-OE8sDQe0CRd7r_kVanj:byb5ut4) ([raw file](https://github.com/starkware-libs/sequencer/blob/2279521e561915d4cfb9126284c0725748b59749/crates/infra_utils/src/type_name.rs#L40)):*
> ```XML
>     let mut back = 0;
> 
>     let chars: Vec<char> = input.chars().collect();
> ```

Why do you need it as a vector? String is also iterable and has [] AFAIK
___
*[`crates/infra_utils/src/type_name_test.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2655#-OE8t9uJEcy82zyaGvm9:-OE8t9uJEcy82zyaGvmA:b-68ldqy) ([raw file](https://github.com/starkware-libs/sequencer/blob/2279521e561915d4cfb9126284c0725748b59749/crates/infra_utils/src/type_name_test.rs#L17)):*
> ```XML
> #[test]
> fn resolve_project_relative_path_success() {
>     assert_matches!(short_type_name::<TestStruct>().as_str(), "TestStruct");
> ```

why assert_matches and not assert_eq

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2655)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/infra_utils/src/type_name.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2655#-OE8sDQe0CRd7r_kVani:-OEJkero95IewTKUK1_F:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/2279521e561915d4cfb9126284c0725748b59749/crates/infra_utils/src/type_name.rs#L40)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why do you need it as a vector? String is also iterable and has [] AFAIK
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2655#-:-OEJyn_F738uVmpzYjyp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2655)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request merged**
