### PR TITLE
feat(ci): add no path dependencies test

### PR DESCRIPTION
**Pull request by nadin-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/577)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/577)* status: 0 of 2 files reviewed, all discussions resolved

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/577)* status: all files reviewed, 8 unresolved discussions (waiting on @nadin-Starkware)

___
*[`workspace_tests/toml_utils.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5HlPB0DpyXhLij53UO:-O5HlPB0DpyXhLij53UP:b-p1r1zc) ([raw file](https://github.com/starkware-libs/sequencer/blob/f57228946825a8878665f54eaf68efcc53a20cb0/workspace_tests/toml_utils.rs#L13)):*
> ```XML
>     String(String),
>     Object { version: String, path: Option<String> },
>     CrateObject { workspace: Option<bool>, features: Option<Vec<String>>, path: Option<String> },
> ```

where is this used?



_Code quote:_
```XML
CrateObject { workspace: Option<bool>, features: Option<Vec<String>>, path: Option<String> },
```
___
*[`workspace_tests/toml_utils.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5HjcJs9KmWsBfF6AOT:-O5HjcJs9KmWsBfF6AOU:b-umpbzh) ([raw file](https://github.com/starkware-libs/sequencer/blob/f57228946825a8878665f54eaf68efcc53a20cb0/workspace_tests/toml_utils.rs#L36)):*
> ```XML
> pub(crate) struct CrateCargoToml {
>     dependencies: Option<HashMap<String, DependencyValue>>,
> }
> ```

what if a crate only has `dev-dependencies`?
will these show up? they also need checking



_Code quote:_
```XML
#[derive(Clone, Debug, Serialize, Deserialize)]
pub(crate) struct CrateCargoToml {
    dependencies: Option<HashMap<String, DependencyValue>>,
}
```
___
*[`workspace_tests/toml_utils.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5Hk2QXBis6AGCRts40:-O5Hk2QXBis6AGCRts41:b-8fkowa) ([raw file](https://github.com/starkware-libs/sequencer/blob/f57228946825a8878665f54eaf68efcc53a20cb0/workspace_tests/toml_utils.rs#L85)):*
> ```XML
>             cargo_tomls.push(cargo_toml);
>         }
>         cargo_tomls
> ```

more rusty like this



_Suggestion:_
```XML
        self.members().iter().map(|member| {
            let cargo_toml_path = Path::new(&crates_dir).join(member).join("Cargo.toml");

            let cargo_toml_content = fs::read_to_string(&cargo_toml_path)
                .expect(&format!("Failed to read {:?}", cargo_toml_path));

            let cargo_toml: CrateCargoToml = toml::from_str(&cargo_toml_content).unwrap();
            cargo_toml
        })
        .collect()
```
___
*[`workspace_tests/toml_utils.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5Hkm4QBieng1kJCqVZ:-O5Hkm4QBieng1kJCqV_:b21fz7s) ([raw file](https://github.com/starkware-libs/sequencer/blob/f57228946825a8878665f54eaf68efcc53a20cb0/workspace_tests/toml_utils.rs#L94)):*
> ```XML
>     }
> 
>     pub(crate) fn crate_path_dependencies(&self) -> impl Iterator<Item = LocalCrate> + '_ {
> ```

like this?
it's already part of a *crate* cargo toml so the `crate_` prefix is redundant



_Suggestion:_
```XML
path_dependencies
```
___
*[`workspace_tests/toml_utils.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5Hl1M60QIeJaatCUXX:-O5Hl1M60QIeJaatCUXY:bpafor7) ([raw file](https://github.com/starkware-libs/sequencer/blob/f57228946825a8878665f54eaf68efcc53a20cb0/workspace_tests/toml_utils.rs#L99)):*
> ```XML
>                 if let DependencyValue::Object { path: Some(path), version } = value {
>                     Some(LocalCrate { path: path.to_string(), version: version.to_string() })
>                 } else {
> ```

if a crate Cargo.toml contains a `path` dependency, even *without* a `version` field, we want to check it.
(you can have a path without version)
did you mean to use the `DependencyValue::CrateObject` variant?



_Code quote:_
```XML
                if let DependencyValue::Object { path: Some(path), version } = value {
                    Some(LocalCrate { path: path.to_string(), version: version.to_string() })
                } else {
```
___
*[`workspace_tests/toml_utils.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5HktLb56eBOZrLUVMb:-O5HktLb56eBOZrLUVMc:b-wppwts) ([raw file](https://github.com/starkware-libs/sequencer/blob/f57228946825a8878665f54eaf68efcc53a20cb0/workspace_tests/toml_utils.rs#L105)):*
> ```XML
>         } else {
>             panic!("No dependencies exist");
>         }
> ```

why panic? if there are no dependencies, return an empty iterator



_Code quote:_
```XML
        } else {
            panic!("No dependencies exist");
        }
```
___
*[`workspace_tests/version_integrity_test.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5HkYNr370PVcuj2Chs:-O5HkYNr370PVcuj2Cht:b-4591fh) ([raw file](https://github.com/starkware-libs/sequencer/blob/f57228946825a8878665f54eaf68efcc53a20cb0/workspace_tests/version_integrity_test.rs#L32)):*
> ```XML
> #[test]
> fn validate_no_path_dependencies() {
>     let mut all_crate_paths: Vec<LocalCrate> = Vec::new();
> ```

"all_crate_paths" is confusing, this is more informative IMO



_Suggestion:_
```XML
all_path_deps_in_crate_tomls
```
___
*[`workspace_tests/version_integrity_test.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5HkRva2F1VINwjYDlN:-O5HkRva2F1VINwjYDlO:b-g66eyn) ([raw file](https://github.com/starkware-libs/sequencer/blob/f57228946825a8878665f54eaf68efcc53a20cb0/workspace_tests/version_integrity_test.rs#L39)):*
> ```XML
>         } else {
>             println!("No dependencies exist");
>         }
> ```

I don't think this is necessary



_Code quote:_
```XML
        } else {
            println!("No dependencies exist");
        }
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/577)* status: all files reviewed, 8 unresolved discussions (waiting on @nadin-Starkware)

___
*[`workspace_tests/toml_utils.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5HjcJs9KmWsBfF6AOT:-O5IhhmBAn53Ug1IbRij:b-lgkh97) ([raw file](https://github.com/starkware-libs/sequencer/blob/f57228946825a8878665f54eaf68efcc53a20cb0/workspace_tests/toml_utils.rs#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

actually this Q is also relevant for the workspace toml
</blockquote></details>

nvm, just for crate tomls

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/577)* status: all files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`workspace_tests/toml_utils.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5HlPB0DpyXhLij53UO:-O5IQxt237CyXuBUfc-L:b53gmyi) ([raw file](https://github.com/starkware-libs/sequencer/blob/f57228946825a8878665f54eaf68efcc53a20cb0/workspace_tests/toml_utils.rs#L13)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where is this used?
</blockquote></details>

In the path_dependencies function
___
*[`workspace_tests/toml_utils.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5HjcJs9KmWsBfF6AOT:-O5Ihi4tEMnSnK3rEC6h:b-lo2ed3) ([raw file](https://github.com/starkware-libs/sequencer/blob/f57228946825a8878665f54eaf68efcc53a20cb0/workspace_tests/toml_utils.rs#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

nvm, just for crate tomls
</blockquote></details>

Done. As discussed, the main toml doesn't contain dev-dependencies 
___
*[`workspace_tests/toml_utils.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5Hk2QXBis6AGCRts40:-O5I01SaBZATZtTceY6h:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f57228946825a8878665f54eaf68efcc53a20cb0/workspace_tests/toml_utils.rs#L85)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

more rusty like this
</blockquote></details>

Done.
___
*[`workspace_tests/toml_utils.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5Hkm4QBieng1kJCqVZ:-O5IKgS6Dq4GcF2ff8a5:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f57228946825a8878665f54eaf68efcc53a20cb0/workspace_tests/toml_utils.rs#L94)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

like this?
it's already part of a *crate* cargo toml so the `crate_` prefix is redundant
</blockquote></details>

Done.
___
*[`workspace_tests/toml_utils.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5Hl1M60QIeJaatCUXX:-O5IL8BF6FR_y3ADMefH:b4fh118) ([raw file](https://github.com/starkware-libs/sequencer/blob/f57228946825a8878665f54eaf68efcc53a20cb0/workspace_tests/toml_utils.rs#L99)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if a crate Cargo.toml contains a `path` dependency, even *without* a `version` field, we want to check it.
(you can have a path without version)
did you mean to use the `DependencyValue::CrateObject` variant?
</blockquote></details>

Yep, thanks, Done.
___
*[`workspace_tests/toml_utils.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5HktLb56eBOZrLUVMb:-O5IY_ijEFf9zZMvoX5t:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f57228946825a8878665f54eaf68efcc53a20cb0/workspace_tests/toml_utils.rs#L105)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why panic? if there are no dependencies, return an empty iterator
</blockquote></details>

Done.
___
*[`workspace_tests/version_integrity_test.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5HkYNr370PVcuj2Chs:-O5Hnr6vAY5Zv-7qsloH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f57228946825a8878665f54eaf68efcc53a20cb0/workspace_tests/version_integrity_test.rs#L32)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

"all_crate_paths" is confusing, this is more informative IMO
</blockquote></details>

Done.
___
*[`workspace_tests/version_integrity_test.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5HkRva2F1VINwjYDlN:-O5Hnk5MBo_Azez9k53_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f57228946825a8878665f54eaf68efcc53a20cb0/workspace_tests/version_integrity_test.rs#L39)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't think this is necessary
</blockquote></details>

Done.

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/577)* status: all files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`workspace_tests/toml_utils.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5IlOnNDauGU99M2LUA:-O5MEt7d8lRbNknZfUu0:b-ag5oz3) ([raw file](https://github.com/starkware-libs/sequencer/blob/641975026a3402acb1df5820007d82e89fea5e2b/workspace_tests/toml_utils.rs#L94)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see below (reuse `all_dependencies`)
</blockquote></details>

There is no need for the all_dependencies function, so I've left it unchanged
___
*[`workspace_tests/toml_utils.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5IkgDg6poz7BYnYxOX:-O5MFLuN4TJWZzM1J6Ro:b1gfxwu) ([raw file](https://github.com/starkware-libs/sequencer/blob/641975026a3402acb1df5820007d82e89fea5e2b/workspace_tests/toml_utils.rs#L95)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the iteration over all dependencies can be improved, I think... maybe define an `all_dependencies` method like this?
```
match (self.dependencies, self.dev_dependencies) {
    (None, None) => vec![].iter(),
    (Some(deps), None) | (None, Some(deps)) => deps.iter(),
    (Some(deps), Some(dev_deps)) => deps.iter().chain(dev_deps.iter())
}
```
</blockquote></details>

Is it still needed?
___
*[`workspace_tests/toml_utils.rs` line 96 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5IjyCf1ZFT5PblSF-e:-O5MEjKyCULbZMqogouE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/641975026a3402acb1df5820007d82e89fea5e2b/workspace_tests/toml_utils.rs#L96)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no `Box` please, see below for problem and possible solution
</blockquote></details>

Done.
___
*[`workspace_tests/toml_utils.rs` line 106 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5Ijhe97kn5CF5hipwT:-O5MEfKH4v1VE18Npgji:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/641975026a3402acb1df5820007d82e89fea5e2b/workspace_tests/toml_utils.rs#L106)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

If you do this, can you drop the `Box` type?
Rust complains because it needs a concrete return type, the return type in the function signature is `impl T` for some trait `T` (`Iterator` in this case).
if the compiler still complains, maybe you need something like
```
let empty_vec: Vec<String> = vec![];
empty_vec.iter()
```
if the compiler still complains about the value being dropped (returning a reference to a local variable), maybe you can define this const near the top of the module:
```
const EMPTY_STRING_SLICE: [String; 0] = [];
```
and return `EMPTY_STRING_SLICE.iter()`
</blockquote></details>

Done.
___
*[`workspace_tests/toml_utils.rs` line 122 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5Il8SKAVydTAF4i6GW:-O5MEmZO30OIjXFgiiCh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/641975026a3402acb1df5820007d82e89fea5e2b/workspace_tests/toml_utils.rs#L122)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

instead of iterating separately, use `all_dependencies` (see above)
</blockquote></details>

Done.
___
*[`workspace_tests/version_integrity_test.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5Ilbg-0JCjRdLMPUpR:-O5IpfIWER4mSKKUx5b7:b-4qh3w7) ([raw file](https://github.com/starkware-libs/sequencer/blob/641975026a3402acb1df5820007d82e89fea5e2b/workspace_tests/version_integrity_test.rs#L42)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you have two crates, both with path dependencies, you will only fail and print details about one of the crates.
can you collect all problematic crate tomls and print them all at the end?
</blockquote></details>

Absolutely, this was the point.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/577)* status: all files reviewed, 2 unresolved discussions (waiting on @nadin-Starkware)

___
*[`workspace_tests/toml_utils.rs` line 97 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5MjSjQ3UTgrKrYNC1A:-O5MjSjQ3UTgrKrYNC1B:b-c5fkuk) ([raw file](https://github.com/starkware-libs/sequencer/blob/8eebc0f2692d17cf6a5ad4b356e550dcee1648cc/workspace_tests/toml_utils.rs#L97)):*
> ```XML
>         self.dependencies.iter().chain(self.dev_dependencies.iter()).flatten().filter_map(
>             |(_name, value)| {
>                 if let DependencyValue::Object { path: Some(path), version: Some(_version) } = value
> ```

ignore unused fields with `..`



_Suggestion:_
```XML
if let DependencyValue::Object { path: Some(path), .. } = value
```
___
*[`workspace_tests/version_integrity_test.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5MjtdN0D9k1Jz1QB19:-O5MjtdN0D9k1Jz1QB1A:b-1ovjbo) ([raw file](https://github.com/starkware-libs/sequencer/blob/8eebc0f2692d17cf6a5ad4b356e550dcee1648cc/workspace_tests/version_integrity_test.rs#L34)):*
> ```XML
>     let mut all_path_deps_in_crate_tomls: Vec<String> = Vec::new();
>     for crate_cargo_toml in ROOT_TOML.member_cargo_tomls().iter() {
>         if crate_cargo_toml.has_dependencies() {
> ```

is this `if` needed?
`path_dependencies` will just return an empty iterator if there are no dependencies, which is fine, right?



_Code quote:_
```XML
if crate_cargo_toml.has_dependencies() {
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/577)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`workspace_tests/toml_utils.rs` line 97 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5MjSjQ3UTgrKrYNC1A:-O5MkS7w6eN9kY101L1G:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8eebc0f2692d17cf6a5ad4b356e550dcee1648cc/workspace_tests/toml_utils.rs#L97)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ignore unused fields with `..`
</blockquote></details>

Done.
___
*[`workspace_tests/version_integrity_test.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/577#-O5MjtdN0D9k1Jz1QB19:-O5Mks-s6tF5d0oweeUv:b-ofpkmv) ([raw file](https://github.com/starkware-libs/sequencer/blob/8eebc0f2692d17cf6a5ad4b356e550dcee1648cc/workspace_tests/version_integrity_test.rs#L34)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this `if` needed?
`path_dependencies` will just return an empty iterator if there are no dependencies, which is fine, right?
</blockquote></details>

Not anymore, Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/577#-:-O5MmI9l1LIOeDKUVx3k:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Pull request merged**
