### PR TITLE
refactor(consensus): consensus takes a generic network receiver

### PR DESCRIPTION
**Pull request by matan-starkware**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [x] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/112)

### CODE REVIEW

**Comment by matan-starkware** [comment]
* **#112** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/112?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/112)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @asmaastarkware, @eitanm-starkware, and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/112#-O2eHf6Q02k48o3ma_K6:-O32vSxD5c7qfQb1Zyhj:b-84jve4) (no related file):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

We plan to change those channels to Box<dyn Sink/Stream>, and then this PR will be unnecessary
@eitanm-starkware could you do that on Sunday?
</blockquote></details>

As discussed your change is nothappening. Reviving.

___

**Review by asmaastarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/112#-:-O371Cbq5qvGDM0M4K1v:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @eitanm-starkware and @ShahakShama)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/112#-:-O382ar0BS7B3dEmcm56:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Pull request closed without merging**
