### PR TITLE
feat(mempool): add insert func to suspended tx pool

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/662)

### CODE REVIEW

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/662)* status: 0 of 1 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/662#-O5Tc5osEhY1BJjCzqxL:-O5Tc5ot-F8KjgQBNaYR:b-ug9r7x) (no related file):*
STACK OF PRS:
1. #634
2. #662 (YOU'RE HERE)
3. #664

___

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/662)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/suspended_transaction_pool.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/662#-O5hVp4bE6QPaXkyOBqS:-O5hVp4bE6QPaXkyOBqT:bgjrjxg) ([raw file](https://github.com/starkware-libs/sequencer/blob/47dbaa4ce0acdec6d349ca84f62cf66ff97a17e5/crates/mempool/src/suspended_transaction_pool.rs#L17)):*
> ```XML
>     pub fn _insert(&mut self, tx: TransactionReference) {
>         self._suspended_tx_pool.insert((tx.sender_address, tx.nonce), tx);
>     }
> ```

maybe add assert that we so not have the tx, or a return value for such case.



_Code quote:_
```XML
    pub fn _insert(&mut self, tx: TransactionReference) {
        self._suspended_tx_pool.insert((tx.sender_address, tx.nonce), tx);
    }
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/662)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/suspended_transaction_pool.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/662#-O5hVp4bE6QPaXkyOBqS:-O5hVzOt-pH7bkB7Cx7Z:b-1xxng7) ([raw file](https://github.com/starkware-libs/sequencer/blob/47dbaa4ce0acdec6d349ca84f62cf66ff97a17e5/crates/mempool/src/suspended_transaction_pool.rs#L17)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

maybe add assert that we so not have the tx, or a return value for such case.
</blockquote></details>

What the expected behavior if a new tx (with the same nonce, and address) where added? (like in fee escalation)?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/662)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/suspended_transaction_pool.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/662#-O5hVp4bE6QPaXkyOBqS:-O5i-03O-uKYpvOMglDN:by37y68) ([raw file](https://github.com/starkware-libs/sequencer/blob/47dbaa4ce0acdec6d349ca84f62cf66ff97a17e5/crates/mempool/src/suspended_transaction_pool.rs#L17)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

What the expected behavior if a new tx (with the same nonce, and address) where added? (like in fee escalation)?
</blockquote></details>

added an assertion as discussed offline

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/662#-:-O5i0jze4gWkVk1Ju347:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/suspended_transaction_pool.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/662#-O5i0XdS0QR0YkAKeRwL:-O5i0XdS0QR0YkAKeRwM:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/55c7b90c2951018ab2a58786c20093519d4e5b31/crates/mempool/src/suspended_transaction_pool.rs#L19)):*
> ```XML
>             self._suspended_tx_pool.insert((tx.sender_address, tx.nonce), tx),
>             None,
>             "Keys should be unique; duplicates are checked prior."
> ```





_Suggestion:_
```XML
Only a single transaction from the same contract class can be in the suspended pool at a time
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/662)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/suspended_transaction_pool.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/662#-O5i0XdS0QR0YkAKeRwL:-O5i4mGo9OmLmvukh_QF:b-k1xe10) ([raw file](https://github.com/starkware-libs/sequencer/blob/55c7b90c2951018ab2a58786c20093519d4e5b31/crates/mempool/src/suspended_transaction_pool.rs#L19)):*
> ```XML
>             self._suspended_tx_pool.insert((tx.sender_address, tx.nonce), tx),
>             None,
>             "Keys should be unique; duplicates are checked prior."
> ```

i like `Keys should be unique; duplicates are checked prior` better

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/662)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/suspended_transaction_pool.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/662#-O5i0XdS0QR0YkAKeRwL:-O6px_Gn36Sj-9AETZcm:b-3i0tcj) ([raw file](https://github.com/starkware-libs/sequencer/blob/55c7b90c2951018ab2a58786c20093519d4e5b31/crates/mempool/src/suspended_transaction_pool.rs#L19)):*
> i like `Keys should be unique; duplicates are checked prior` better

Why? Saying that you like something better is not a sufficient response to a reviewer.

Also, where are dups checked here?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/662)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/suspended_transaction_pool.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/662#-O5i0XdS0QR0YkAKeRwL:-O6q7lQaEra_XQ6Rf0hS:br1s9i) ([raw file](https://github.com/starkware-libs/sequencer/blob/55c7b90c2951018ab2a58786c20093519d4e5b31/crates/mempool/src/suspended_transaction_pool.rs#L19)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

> i like `Keys should be unique; duplicates are checked prior` better

Why? Saying that you like something better is not a sufficient response to a reviewer.

Also, where are dups checked here?
</blockquote></details>

The assertion checks that inserting `(tx.sender_address, tx.nonce)` into `suspended_tx_pool` returns `None`, confirming no duplicates; if not `None`, it means the key already exists.

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/662)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/suspended_transaction_pool.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/662#-O5i0XdS0QR0YkAKeRwL:-O6uWbc39f238KFU0Bq0:b78eh42) ([raw file](https://github.com/starkware-libs/sequencer/blob/55c7b90c2951018ab2a58786c20093519d4e5b31/crates/mempool/src/suspended_transaction_pool.rs#L19)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

The assertion checks that inserting `(tx.sender_address, tx.nonce)` into `suspended_tx_pool` returns `None`, confirming no duplicates; if not `None`, it means the key already exists.
</blockquote></details>

This function will be used during transaction insertion in `add_tx` (and, where the transaction duplication is already validated). Therefore, we don't expect this error to occur here.

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/662#-:-O6yfM9e9fJsKnaEv4j0:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @elintul and @MohammadNassar1)

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/662)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
