### PR TITLE
chore(starknet_api): move test utils constants to starknet api

### PR DESCRIPTION
**Pull request by ArniStarkware**

### CODE REVIEW

**Comment by ArniStarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2446?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2446** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2446?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2446?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2445** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2445?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2444** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2444?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2443** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2443?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2446#-ODMgkxU7WikROXxJaeb:-ODMgkxU7WikROXxJaec:b-54egn4) ([raw file](https://github.com/starkware-libs/sequencer/blob/f37d328eccf14d42682e098ad6f7a922b2063fad/crates/blockifier/src/test_utils/struct_impls.rs#L137)):*
> ```XML
> pub trait BlockInfoExt {
>     fn create_for_testing() -> Self;
>     fn create_for_testing_with_kzg(use_kzg_da: bool) -> Self;
> ```

Delete this.



_Code quote:_
```XML
pub trait BlockInfoExt {
    fn create_for_testing() -> Self;
    fn create_for_testing_with_kzg(use_kzg_da: bool) -> Self;
```

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2446)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @yair-starkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2446#-ODMgkxU7WikROXxJaeb:-ODf5vUVDGpKG1CyUl8k:b-875k1i) ([raw file](https://github.com/starkware-libs/sequencer/blob/f37d328eccf14d42682e098ad6f7a922b2063fad/crates/blockifier/src/test_utils/struct_impls.rs#L137)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Delete this.
</blockquote></details>

Here?

**Comment by ArniStarkware** [comment]
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2446#-ODMgkxU7WikROXxJaeb:-OEIbM7p4yqxEQIoiBbN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f37d328eccf14d42682e098ad6f7a922b2063fad/crates/blockifier/src/test_utils/struct_impls.rs#L137)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Here?
</blockquote></details>

Done.

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2446)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5 and @yair-starkware)

**Comment by ArniStarkware** [comment]
### Merge activity

* **Dec 18, 7:09 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2446).

**Review by ArniStarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2446)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5 and @yair-starkware)

**Pull request merged**
