### PR TITLE
refactor(mempool): align mempool with account nonce

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/472)

### CODE REVIEW

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/472#-:-O4LVIdd7mD3Smidxwnj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul and @giladchase)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/472)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/472#-O4Z2QbTBhlZaM-t9ukX:-O4Z2QbTBhlZaM-t9ukY:b-zfvjeg) ([raw file](https://github.com/starkware-libs/sequencer/blob/c164c2ab9466903f3551345fee96b7b6128c10a7/crates/mempool/src/mempool.rs#L183)):*
> ```XML
>     }
> 
>     fn align_pool_and_queue_with_account_nonce(&mut self, address: ContractAddress, nonce: Nonce) {
> ```

Nonblocking: we pass this tuple which represents an account state too many times. We should think of a better abstraction, maybe `AccountState`? I believe Mohammad previously gave it some thought.



_Code quote:_
```XML
address: ContractAddress, nonce: Nonce
```
___
*[`crates/mempool/src/mempool.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/472#-O4Z3NHtAyCmCznOBmMe:-O4Z3NHtAyCmCznOBmMf:bfpcbfr) ([raw file](https://github.com/starkware-libs/sequencer/blob/c164c2ab9466903f3551345fee96b7b6128c10a7/crates/mempool/src/mempool.rs#L183)):*
> ```XML
>     }
> 
>     fn align_pool_and_queue_with_account_nonce(&mut self, address: ContractAddress, nonce: Nonce) {
> ```

Both pool and queue, and what's the account state, are implementation details that should not appear in the interface.



_Suggestion:_
```XML
align_with_account_state
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/472)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/472#-O4Z6J3z-T4b9wbT_zAF:-O4Z6J3z-T4b9wbT_zAG:b4liti5) ([raw file](https://github.com/starkware-libs/sequencer/blob/724c44d0e15578221b7b0b75ee074ad1b2633d00/crates/mempool/src/mempool.rs#L145)):*
> ```XML
>         }
> 
>         // Maybe close nonce gap.
> ```

Please notice comments; they should remain.



_Code quote:_
```XML
// Maybe close nonce gap.
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/472)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/472#-O4Z8qQoBj2leFnNCLSJ:-O4Z8qQp6O8A43YsZd-d:b-8amjtw) (no related file):*
Let the reviewer know the context of the PR, especially if it's part of a stack (either by using some visual tool like Graphite, or writing a comment referencing the rest of the PRs in the stack).

___

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/472)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/472#-O4Z6J3z-T4b9wbT_zAF:-O4_HJrE6qUdJTYGWgDK:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/724c44d0e15578221b7b0b75ee074ad1b2633d00/crates/mempool/src/mempool.rs#L145)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please notice comments; they should remain.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/472#-O4Z3NHtAyCmCznOBmMe:-O4_HOU36zgSJqB6n67v:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c164c2ab9466903f3551345fee96b7b6128c10a7/crates/mempool/src/mempool.rs#L183)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Both pool and queue, and what's the account state, are implementation details that should not appear in the interface.
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/472)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/472#-O4d3O6zBAWMec3TQZjc:-O4d3O6zBAWMec3TQZjd:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec82fa7fadcb98723a238c144245294a6fb927d0/crates/mempool/src/mempool.rs#L185)):*
> ```XML
> 
>     fn align_with_account_state(&mut self, address: ContractAddress, nonce: Nonce) {
>         // Remove the queued transaction if its nonce doesn't match the given nonce.
> ```





_Suggestion:_
```XML
// Maybe remove out-of-data queued transaction.
```
___
*[`crates/mempool/src/mempool.rs` line 192 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/472#-O4d3KAVANKXn3VZqc8U:-O4d3KAVANKXn3VZqc8V:b-78m0gw) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec82fa7fadcb98723a238c144245294a6fb927d0/crates/mempool/src/mempool.rs#L192)):*
> ```XML
> 
>         // If there's a transaction with the current account nonce, close the gap and insert it into
>         // the queue.
> ```

Keep comments succinct.



_Suggestion:_
```XML
// Maybe close nonce gap.
```
___
*[`crates/mempool/src/mempool.rs` line 200 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/472#-O4d3TlSBzwXhq2cAb8e:-O4d3TlSBzwXhq2cAb8f:b3cmktf) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec82fa7fadcb98723a238c144245294a6fb927d0/crates/mempool/src/mempool.rs#L200)):*
> ```XML
> 
>         // Remove all transactions from the pool with a nonce lower than the given nonce.
>         self.tx_pool.remove_up_to_nonce(address, nonce);
> ```

No need, function name is self-explanatory.



_Suggestion:_
```XML
        self.tx_pool.remove_up_to_nonce(address, nonce);
```

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/472)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 200 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/472#-O4d3TlSBzwXhq2cAb8e:-O4fCOR03nnzMouXUF1a:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec82fa7fadcb98723a238c144245294a6fb927d0/crates/mempool/src/mempool.rs#L200)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No need, function name is self-explanatory.
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/472)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/472#-O4d3O6zBAWMec3TQZjc:-O4iAnCE6dSf15K8bh05:b-r0l0pz) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec82fa7fadcb98723a238c144245294a6fb927d0/crates/mempool/src/mempool.rs#L185)):*
> ```XML
> 
>     fn align_with_account_state(&mut self, address: ContractAddress, nonce: Nonce) {
>         // Remove the queued transaction if its nonce doesn't match the given nonce.
> ```

"Maybe remove out-of-date transactions."
Had a typo there + it now explains both removals. 
___
*[`crates/mempool/src/mempool.rs` line 92 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/472#-O4iBH3fB8Xp7x6QkCBO:-O4iBH3fB8Xp7x6QkCBP:bw6c101) ([raw file](https://github.com/starkware-libs/sequencer/blob/762d712ffa040b03d761c8ff8072acafbcbd6cc5/crates/mempool/src/mempool.rs#L92)):*
> ```XML
>         state_changes: HashMap<ContractAddress, AccountState>,
>     ) -> MempoolResult<()> {
>         for (&address, AccountState { nonce }) in &state_changes {
> ```

Delete blank line?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/472)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/472#-O4d3O6zBAWMec3TQZjc:-O4iLDda09AqaVxxgNdc:b-2r01dl) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec82fa7fadcb98723a238c144245294a6fb927d0/crates/mempool/src/mempool.rs#L185)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

"Maybe remove out-of-date transactions."
Had a typo there + it now explains both removals.
</blockquote></details>

oops. added a line gap so it will be clear its for both removals

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/472)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/472#-O4d3O6zBAWMec3TQZjc:-O4iuxIG1jl8OSd_gA2d:b8u0l0j) ([raw file](https://github.com/starkware-libs/sequencer/blob/ec82fa7fadcb98723a238c144245294a6fb927d0/crates/mempool/src/mempool.rs#L185)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

oops. added a line gap so it will be clear its for both removals
</blockquote></details>

format disapprove

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/472)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 88 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/472#-O4jC5Yn6YDVHC40UHXa:-O4jC5Yn6YDVHC40UHXb:b-xw64s4) ([raw file](https://github.com/starkware-libs/sequencer/blob/170b8cf0bc621321d3975bbe3579cb0be1001f7e/crates/mempool/src/mempool.rs#L88)):*
> ```XML
>         for (&address, AccountState { nonce }) in &state_changes {
>             let next_nonce = nonce.try_increment().map_err(|_| MempoolError::FeltOutOfRange)?;
> ```

Code should be deleted here, right?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/472)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 88 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/472#-O4jC5Yn6YDVHC40UHXa:-O4jelhcE-VhKxYoapA7:bk5h4qe) ([raw file](https://github.com/starkware-libs/sequencer/blob/170b8cf0bc621321d3975bbe3579cb0be1001f7e/crates/mempool/src/mempool.rs#L88)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Code should be deleted here, right?
</blockquote></details>

Oops. Missed it when rebased. Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/472)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 109 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/472#-O4jkzPK64eWjWF8BJtO:-O4jkzPL3x2F0DDgww4Q:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/a7dacabed82a22f2d0defa31641bee967698ede4/crates/mempool/src/mempool.rs#L109)):*
> ```XML
>         self.tx_pool.insert(tx)?;
> 
>         self.align_with_account_state(sender_address, nonce);
> ```





_Suggestion:_
```XML
        self.tx_pool.insert(tx)?;
        self.align_with_account_state(sender_address, nonce);
```
___
*[`crates/mempool/src/mempool.rs` line 168 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/472#-O4jqUIRE2352fz3oHNX:-O4jqUIRE2352fz3oHNY:b-fs937p) ([raw file](https://github.com/starkware-libs/sequencer/blob/a7dacabed82a22f2d0defa31641bee967698ede4/crates/mempool/src/mempool.rs#L168)):*
> ```XML
>     }
> 
>     fn align_with_account_state(&mut self, address: ContractAddress, nonce: Nonce) {
> ```

Please add a TODO to think of a good abstraction for the `(address, nonce)` tuple we keep passing everywhere.



_Suggestion:_
```XML
align_to_account_state
```

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/472#-:-O4k7PSyA6CECuDpiLJ1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Pull request merged**
