### PR TITLE
build(blockifier_reexecution): add support for l1 handler tx

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1765?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1765** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1765?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1759** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1759?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1758** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1758?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1712** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1712?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1698** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1698?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1658** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1658?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1604** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1604?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1765)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1765#-OAmj2H57HQcVb8K8yz0:-OAmj2H57HQcVb8K8yz1:b-u5kjxi) ([raw file](https://github.com/starkware-libs/sequencer/blob/c85ea0efb98b2ac1b5baba3027de71011e597bdf/crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs#L45)):*
> ```XML
>                 Transaction::Invoke(_) | Transaction::DeployAccount(_) => {
>                     BlockifierTransaction::from_api(tx, tx_hash, None, None, None, false)
>                         .map_err(ReexecutionError::from)
> ```

do you really need these?
why not replace with `?`?

times 3



_Code quote:_
```XML
.map_err(ReexecutionError::from)
```
___
*[`crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1765#-OAmhtWR7DM6gIDWt-CV:-OAmhtWR7DM6gIDWt-CW:bggajon) ([raw file](https://github.com/starkware-libs/sequencer/blob/c85ea0efb98b2ac1b5baba3027de71011e597bdf/crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs#L68)):*
> ```XML
>                         tx_hash,
>                         None,
>                         Some(Fee(u128::MAX)),
> ```

there is a constant `MAX_FEE` in the blockifier, isn't it public?



_Suggestion:_
```XML
Some(Fee(MAX_FEE))
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1765)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1765#-OAmj2H57HQcVb8K8yz0:-OAqo3a28H18orImZo3S:bn5w1g2) ([raw file](https://github.com/starkware-libs/sequencer/blob/c85ea0efb98b2ac1b5baba3027de71011e597bdf/crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs#L45)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do you really need these?
why not replace with `?`?

times 3
</blockquote></details>

it works
___
*[`crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1765#-OAmhtWR7DM6gIDWt-CV:-OAqlCUu7mVQBsJJsFkS:bw987sz) ([raw file](https://github.com/starkware-libs/sequencer/blob/c85ea0efb98b2ac1b5baba3027de71011e597bdf/crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs#L68)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there is a constant `MAX_FEE` in the blockifier, isn't it public?
</blockquote></details>

Are you sure? I don't find it

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1765)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1765#-OAmhtWR7DM6gIDWt-CV:-OAwURdkDH7ugeV8MIkz:bszdrsf) ([raw file](https://github.com/starkware-libs/sequencer/blob/c85ea0efb98b2ac1b5baba3027de71011e597bdf/crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs#L68)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Are you sure? I don't find it
</blockquote></details>

[here](https://github.com/starkware-libs/sequencer/blob/main/crates/blockifier/src/test_utils.rs#L150)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1765)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1765#-OAmhtWR7DM6gIDWt-CV:-OAwg7rdCvsd8t_DQvPq:b-zcjvte) ([raw file](https://github.com/starkware-libs/sequencer/blob/c85ea0efb98b2ac1b5baba3027de71011e597bdf/crates/blockifier_reexecution/src/state_reader/reexecution_state_reader.rs#L68)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[here](https://github.com/starkware-libs/sequencer/blob/main/crates/blockifier/src/test_utils.rs#L150)
</blockquote></details>

Thanks

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1765#-:-OAwqJqfCv4nCJCCd1Ne:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1765)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1765)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Comment by AvivYossef-starkware** [comment]
### Merge activity

* **Nov 6, 7:31 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/1765).

**Pull request merged**
