### PR TITLE
chore: cherry-pick add native dependencies to the CI (#726)

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/875)

### CODE REVIEW

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/875)* status: 11 of 28 files reviewed, 25 unresolved discussions (waiting on @dorimedini-starkware, @noaov1, and @varex83)

___
*[`Cargo.toml` line 97 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/875#-O78geqU3U1oGeC6EQDA:-O7TVI3fDyiXes-U1tDa:b213zob) ([raw file](https://github.com/starkware-libs/sequencer/blob/94800c2ff08f370761b882f6a1459cbd35ed375d/Cargo.toml#L97)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

as long as this exists we cannot publish the blockifier; this is ok?
</blockquote></details>

If this is important, we can make a follow up PR addressing this
___
*[`Dockerfile` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/875#-O78rS_dAgHwI_sKXRsf:-O7TVdE81iYKZZQ7Fq6S:bd12pig) ([raw file](https://github.com/starkware-libs/sequencer/blob/94800c2ff08f370761b882f6a1459cbd35ed375d/Dockerfile#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

IIRC this dockerfile is used by papyrus team; need their eyes here
</blockquote></details>

Could you tag them?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/875)* status: 10 of 28 files reviewed, 24 unresolved discussions (waiting on @alon-dotan-starkware, @dan-starkware, @noaov1, and @varex83)

___
*[`Cargo.toml` line 97 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/875#-O78geqU3U1oGeC6EQDA:-O7U2ep0-oN5p8WcBnwT:b-p4dic3) ([raw file](https://github.com/starkware-libs/sequencer/blob/94800c2ff08f370761b882f6a1459cbd35ed375d/Cargo.toml#L97)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

If this is important, we can make a follow up PR addressing this
</blockquote></details>

we prefer to be able to publish crates quickly if the need arises; follow-up PR would be a good idea
___
*[`Dockerfile` line 49 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/875#-O78rHzz5gWgw1mbIM5t:-O7U2ucl7LqyooEOT4ox:b-qtutma) ([raw file](https://github.com/starkware-libs/sequencer/blob/94800c2ff08f370761b882f6a1459cbd35ed375d/Dockerfile#L49)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

Because the config file is not part of the repo (it is autogenerated). I think is better to leave this exports here
</blockquote></details>

@alon-dotan-starkware WDYT?
___
*[`Dockerfile` line  at r1](https://reviewable.io/reviews/starkware-libs/sequencer/875#-O78rS_dAgHwI_sKXRsf:-O7U2q_c3Y86uTAj6vlP:bz7du5d) ([raw file](https://github.com/starkware-libs/sequencer/blob/94800c2ff08f370761b882f6a1459cbd35ed375d/Dockerfile#L)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

Could you tag them?
</blockquote></details>

@dan-starkware

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/875)* status: 10 of 28 files reviewed, 25 unresolved discussions (waiting on @alon-dotan-starkware, @dan-starkware, @dorimedini-starkware, and @varex83)

___
*[`.github/workflows/papyrus_nightly-tests-call.yml` line 31 at r16](https://reviewable.io/reviews/starkware-libs/sequencer/875#-O7U8Q2K3GpTGmNU-A_7:-O7U8Q2K3GpTGmNU-A_8:b-82z83j) ([raw file](https://github.com/starkware-libs/sequencer/blob/2964a37710b94ba6c0df9b1b19f46b9875c681e4/.github/workflows/papyrus_nightly-tests-call.yml#L31)):*
> ```YAML
>       - uses: Swatinem/rust-cache@v2
> =======
> >>>>>>> main
> ```

Please reslove



_Code quote:_
```YAML
<<<<<<< HEAD
      - name: Set up Native Dependencies
        uses: ./.github/actions/setup-native-deps
        id: native-deps
      - uses: Swatinem/rust-cache@v2
=======
>>>>>>> main
```

**Review by rodrigo-pino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/875)* status: 10 of 28 files reviewed, 25 unresolved discussions (waiting on @alon-dotan-starkware, @dan-starkware, @dorimedini-starkware, @noaov1, and @varex83)

___
*[`Dockerfile` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/875#-O78rZcg0ib2ynczqhXP:-O7YVHTxAZcoTxo5o03W:b-gj7asa) ([raw file](https://github.com/starkware-libs/sequencer/blob/ac56adaef0e5fc9aea35fec00184558b7ccd1955/Dockerfile#L20)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why was this removed?
</blockquote></details>

Adding this specific target makes it near impossible to compile LLVM dependencies with Cairo Native. LLVM requires dynamic linking and the clib provided by musl does not allow it.
___
*[`.github/actions/setup-native-deps/action.yml` line 28 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/875#-O78rtmCDEju5Kdjbcbp:-O7YVuaN1xjllxtxn2L9:b-nzmmz0) ([raw file](https://github.com/starkware-libs/sequencer/blob/94800c2ff08f370761b882f6a1459cbd35ed375d/.github/actions/setup-native-deps/action.yml#L28)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can this be in a config.toml? see above
</blockquote></details>

I am not familiar with reviewable, but in this location there should be a command to run the script that autogenerates the config.toml
___
*[`scripts/sequencer-ci.Dockerfile` line 21 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/875#-O78tRpfBbrbgKJjJZMQ:-O7YX9i_AMtdOJkX-Kqt:ba3dfob) ([raw file](https://github.com/starkware-libs/sequencer/blob/94800c2ff08f370761b882f6a1459cbd35ed375d/scripts/sequencer-ci.Dockerfile#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

config.toml? (see above)
</blockquote></details>

Removed
___
*[`scripts/build_native_blockifier.sh` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/875#-O78tGVy70b-43x73iqA:-O7YXBcl-Z20EUpsevt4:ba3dfob) ([raw file](https://github.com/starkware-libs/sequencer/blob/94800c2ff08f370761b882f6a1459cbd35ed375d/scripts/build_native_blockifier.sh#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can this be in config.toml? see above
</blockquote></details>

Removed
___
*[`scripts/setup_native_deps.sh` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/875#-O78tW-v7GhDn0pRSjp4:-O7YX50q1wbhqh5ta-gT:b1spwrj) ([raw file](https://github.com/starkware-libs/sequencer/blob/94800c2ff08f370761b882f6a1459cbd35ed375d/scripts/setup_native_deps.sh#L15)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I see tabs instead of 4 whitespaces; we don't use tabs
</blockquote></details>

There should be whitespaces here now

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/875)* status: 10 of 28 files reviewed, 21 unresolved discussions (waiting on @alon-dotan-starkware, @dan-starkware, @noaov1, and @varex83)

___
*[`Dockerfile` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/875#-O78rZcg0ib2ynczqhXP:-O7YZOvaEyranXus3CDG:bhly2qv) ([raw file](https://github.com/starkware-libs/sequencer/blob/ac56adaef0e5fc9aea35fec00184558b7ccd1955/Dockerfile#L20)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

Adding this specific target makes it near impossible to compile LLVM dependencies with Cairo Native. LLVM requires dynamic linking and the clib provided by musl does not allow it.
</blockquote></details>

@alon-dotan-starkware @noaov1 how is it possible that the native blockifier SO runs successfully without this target architecture?
@noaov1 please update both committer and blockifier commits on the py side and make sure tests pass before merging
___
*[`scripts/setup_native_deps.sh` line 15 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/875#-O78tW-v7GhDn0pRSjp4:-O7YZ2X4399AQYTIk_KX:b-x0ctng) ([raw file](https://github.com/starkware-libs/sequencer/blob/94800c2ff08f370761b882f6a1459cbd35ed375d/scripts/setup_native_deps.sh#L15)):*
<details><summary><i>Previously, rodrigo-pino (Rodrigo) wrote…</i></summary><blockquote>

There should be whitespaces here now
</blockquote></details>

I see more tabs now, but I'll unblock, you don't have our dev setup.
@noaov1 maybe be worth going over all files here and `ctrl+s`ing everything to get whitespace corrections, after this is merged. WDYT?

**Comment by aner-starkware** [comment]
*[`.github/workflows/committer_ci.yml` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/875#-O78s_yz1uxO8yA7ZRcV:-O7Z62AVCh_YqBzzyUXd:b4bilww) ([raw file](https://github.com/starkware-libs/sequencer/blob/94800c2ff08f370761b882f6a1459cbd35ed375d/.github/workflows/committer_ci.yml#L122)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

requires review from @aner-starkware and / or @TzahiTaub
</blockquote></details>

This is just where the comment is posted, IIUC. I actually tried putting the comment in the Commits previously, but for some reason didn't manage to make it work (so if this works, hurray!)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/875)* status: 9 of 28 files reviewed, 21 unresolved discussions (waiting on @alon-dotan-starkware, @dan-starkware, @noaov1, @TzahiTaub, and @varex83)

___
*[`.github/workflows/committer_ci.yml` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/875#-O78s_yz1uxO8yA7ZRcV:-O7Z8ABx-uwWx5Jkoj74:b-vxk2ty) ([raw file](https://github.com/starkware-libs/sequencer/blob/94800c2ff08f370761b882f6a1459cbd35ed375d/.github/workflows/committer_ci.yml#L122)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

This is just where the comment is posted, IIUC. I actually tried putting the comment in the Commits previously, but for some reason didn't manage to make it work (so if this works, hurray!)
</blockquote></details>

@aner-starkware what do we need to check to "make sure it works"?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/875)* status: 9 of 28 files reviewed, 21 unresolved discussions (waiting on @alon-dotan-starkware, @dan-starkware, @nadin-Starkware, @noaov1, @TzahiTaub, and @varex83)

___
*[`Dockerfile` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/875#-O78rZcg0ib2ynczqhXP:-O7Zh_HdDGcFUUfqX7Io:b-xyw4lg) ([raw file](https://github.com/starkware-libs/sequencer/blob/ac56adaef0e5fc9aea35fec00184558b7ccd1955/Dockerfile#L20)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@alon-dotan-starkware @noaov1 how is it possible that the native blockifier SO runs successfully without this target architecture?
@noaov1 please update both committer and blockifier commits on the py side and make sure tests pass before merging
</blockquote></details>

@nadin-Starkware

**Comment by aner-starkware** [comment]
*[`.github/workflows/committer_ci.yml` line 122 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/875#-O78s_yz1uxO8yA7ZRcV:-O7xt7BJ7Ezj5kCcvFV9:b-fv4t8o) ([raw file](https://github.com/starkware-libs/sequencer/blob/94800c2ff08f370761b882f6a1459cbd35ed375d/.github/workflows/committer_ci.yml#L122)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@aner-starkware what do we need to check to "make sure it works"?
</blockquote></details>

Apparently, it isn't working, as the comment is still posted in the main discussion.

**Pull request closed without merging**
