### PR TITLE
chore(batcher): reorder block builder file

### PR DESCRIPTION
**Pull request by Yael-Starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1410)

### CODE REVIEW

**Review by Yael-Starkware — COMMENTED** [review]
this PR re-arranges the block builder file according to Dafna's request ina previous PR:
https://reviewable.io/reviews/starkware-libs/sequencer/745#-O8VsrToBZDuYffNj_vB

also she asked to open a new file for the executor trait.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1410#-:-O9DxpFWDgFJJGneSSUO:b-1y7wc4)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alonh5 and @ArniStarkware)

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1410#-:-O9dPrdT8itb7iCvAzZG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5 and @ArniStarkware)

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1410)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1410#-:-O9dlV9qCnM_01IhtUEd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1410)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
