### PR TITLE
feat(blockifier): add impl for GasCosts in versioned_constants

### PR DESCRIPTION
**Pull request by Yonatan-Starkware**

### CODE REVIEW

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 592 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OBf98J46o5dyPby9dj7:-OBf98J59FxA6jUaAFRN:bw5y0ac) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d93eab7dd5765456ae14bf37ee6a66d3becb79b/crates/blockifier/src/versioned_constants.rs#L592)):*
> ```XML
>     pub fn get_builtin_gas_cost(&self, builtin: &BuiltinName) -> u64 {
>         match *builtin {
>             BuiltinName::output => 0,
> ```

Please locate all zeros at the end and document them
segment_arena - it's a virtual builtin.
output - not relevant for smart contract.
The rest are not supported for cairo 1
___
*[`crates/blockifier/src/versioned_constants.rs` line 631 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OBf8oWA3SeZ8V2HCF31:-OBf8oWA3SeZ8V2HCF32:bybeb54) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d93eab7dd5765456ae14bf37ee6a66d3becb79b/crates/blockifier/src/versioned_constants.rs#L631)):*
> ```XML
>             SyscallSelector::StorageRead => self.storage_read_gas_cost,
>             SyscallSelector::StorageWrite => self.storage_write_gas_cost,
>             _ => 0,
> ```

Please list all cases explicitly (we don't like default, it could hide bugs)

**Review by avi-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: all files reviewed, 2 unresolved discussions (waiting on @Yonatan-Starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: all files reviewed, 3 unresolved discussions (waiting on @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 607 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OBspVb0DZp048wVibl_:-OBspVb0DZp048wVibla:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d93eab7dd5765456ae14bf37ee6a66d3becb79b/crates/blockifier/src/versioned_constants.rs#L607)):*
> ```XML
>     }
> 
>     pub fn get_syscall_gas_cost_in_os_constants(&self, selector: &SyscallSelector) -> u64 {
> ```





_Suggestion:_
```XML
get_syscall_gas_cost
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: all files reviewed, 3 unresolved discussions (waiting on @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 631 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OBf8oWA3SeZ8V2HCF31:-OBt0Qb307Yo9n-8AqUZ:b-ucgium) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d93eab7dd5765456ae14bf37ee6a66d3becb79b/crates/blockifier/src/versioned_constants.rs#L631)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Please list all cases explicitly (we don't like default, it could hide bugs)
</blockquote></details>

Actually, better to return an error.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: all files reviewed, 4 unresolved discussions (waiting on @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 596 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OBtUCxICqq_kAUjkyoD:-OBtUCxICqq_kAUjkyoE:b-xkzegd) ([raw file](https://github.com/starkware-libs/sequencer/blob/1d93eab7dd5765456ae14bf37ee6a66d3becb79b/crates/blockifier/src/versioned_constants.rs#L596)):*
> ```XML
>             BuiltinName::pedersen => self.pedersen_gas_cost,
>             BuiltinName::ecdsa => 0,
>             BuiltinName::keccak => 0,
> ```

Hmmm, might be a problem since we need a price for all builtins for the bouncer.
cc @meship-starkware 



_Code quote:_
```XML
       BuiltinName::keccak => 0,
```

**Review by avi-starkware — DISMISSED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 582 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OBz0Kb33S8P68t80yIk:-OBz0Kb33S8P68t80yIl:b-5sbm9n) ([raw file](https://github.com/starkware-libs/sequencer/blob/fca9332edcc672d9cb31284bacc6951dd7ca48c2/crates/blockifier/src/versioned_constants.rs#L582)):*
> ```XML
>             BuiltinName::segment_arena => Err(GasCostsError::VirtualBuiltin),
>             // The unsupported builtins in Cairo 1: output, ecdsa
>             _ => Err(GasCostsError::UnsupportedBuiltin),
> ```

The comment would inevitably become stale. If there are only two cases, better to list them explicitly than mention them in a comment



_Suggestion:_
```XML
            BuiltinName::output => Err(GasCostsError::UnsupportedBuiltin),
            BuiltinName::ecdsa => Err(GasCostsError::UnsupportedBuiltin),
            _ => Err(GasCostsError::UnsupportedBuiltin),
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 817 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OByz3GK3T0Cy47yOA9V:-OByz3GK3T0Cy47yOA9W:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/fca9332edcc672d9cb31284bacc6951dd7ca48c2/crates/blockifier/src/versioned_constants.rs#L817)):*
> ```XML
>     UnsupportedBuiltin,
>     #[error("A virtual builin- not relevant for smart contracts")]
>     VirtualBuiltin,
> ```





_Suggestion:_
```XML
    #[error("used syscall: {0} is not supported in a Cairo 0 contract")]
    UnsupportedCairo0Syscall,
    #[error("used builtin: {0} is not supported in a Cairo 1 contract")]
    UnsupportedCairo1Builtin,
    #[error("a virtual builtin cannot be used in a smart contract")]
    VirtualBuiltin,
```

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @avi-starkware and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 571 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OC2d8FtAtXdIeoj-Pq9:-OC2d8FtAtXdIeoj-PqA:b3kqx) ([raw file](https://github.com/starkware-libs/sequencer/blob/fca9332edcc672d9cb31284bacc6951dd7ca48c2/crates/blockifier/src/versioned_constants.rs#L571)):*
> ```XML
>     pub fn get_builtin_gas_cost(&self, builtin: &BuiltinName) -> Result<u64, GasCostsError> {
>         match *builtin {
>             BuiltinName::range_check => Ok(self.range_check_gas_cost),
> ```

.



_Suggestion:_
```XML
 self.range_check_gas_cost,
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 573 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OC2dXByCg8Vh0fJpZwn:-OC2dXByCg8Vh0fJpZwo:banvj9h) ([raw file](https://github.com/starkware-libs/sequencer/blob/fca9332edcc672d9cb31284bacc6951dd7ca48c2/crates/blockifier/src/versioned_constants.rs#L573)):*
> ```XML
>             BuiltinName::range_check => Ok(self.range_check_gas_cost),
>             BuiltinName::pedersen => Ok(self.pedersen_gas_cost),
>             BuiltinName::keccak => Ok(self.keccak_gas_cost),
> ```

This is not the right price. This price is for the keccak syscall, which contains the builtin price and other resources. 



_Code quote:_
```XML
self.keccak_gas_cost
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 582 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OC2dwTjA5qF56BlFNjG:-OC2dwTjA5qF56BlFNjH:b-fxtn28) ([raw file](https://github.com/starkware-libs/sequencer/blob/fca9332edcc672d9cb31284bacc6951dd7ca48c2/crates/blockifier/src/versioned_constants.rs#L582)):*
> ```XML
>             BuiltinName::segment_arena => Err(GasCostsError::VirtualBuiltin),
>             // The unsupported builtins in Cairo 1: output, ecdsa
>             _ => Err(GasCostsError::UnsupportedBuiltin),
> ```

Please do this explicitly (return error for all not supported builtins explicitly). 



_Code quote:_
```XML
            // The unsupported builtins in Cairo 1: output, ecdsa
            _ => Err(GasCostsError::UnsupportedBuiltin),
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 610 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OC2eYRO77xZamAHClsd:-OC2eYRO77xZamAHClse:b-n82b4v) ([raw file](https://github.com/starkware-libs/sequencer/blob/fca9332edcc672d9cb31284bacc6951dd7ca48c2/crates/blockifier/src/versioned_constants.rs#L610)):*
> ```XML
>             SyscallSelector::StorageRead => Ok(self.storage_read_gas_cost),
>             SyscallSelector::StorageWrite => Ok(self.storage_write_gas_cost),
>             _ => Err(GasCostsError::UnvalidSyscall),
> ```

Please do this explicitly (return error for all cairo 0 syscalls explicitly). 



_Code quote:_
```XML
 _ => Err(GasCostsError::UnvalidSyscall),
```

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @avi-starkware and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 817 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OByz3GK3T0Cy47yOA9V:-OC2fq7j6SY34YmLpVtp:b-k0pszc) ([raw file](https://github.com/starkware-libs/sequencer/blob/fca9332edcc672d9cb31284bacc6951dd7ca48c2/crates/blockifier/src/versioned_constants.rs#L817)):*
> ```XML
>     UnsupportedBuiltin,
>     #[error("A virtual builin- not relevant for smart contracts")]
>     VirtualBuiltin,
> ```

  #[error("used syscall: {0} is not supported in a Cairo 1 contract")]
    UnsupportedCairo1Syscall,

**Review by meship-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @avi-starkware and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 573 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OC2dXByCg8Vh0fJpZwn:-OC2vPjw9zaAhKlKUYh5:b-yni4l3) ([raw file](https://github.com/starkware-libs/sequencer/blob/fca9332edcc672d9cb31284bacc6951dd7ca48c2/crates/blockifier/src/versioned_constants.rs#L573)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

This is not the right price. This price is for the keccak syscall, which contains the builtin price and other resources.
</blockquote></details>

The right price is 136189. Lets talk about it f2f as well.

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: all files reviewed, 10 unresolved discussions (waiting on @avi-starkware and @Yonatan-Starkware)

**Comment by Yonatan-Starkware** [comment]
* **#2067** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2067?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2067?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: 0 of 3 files reviewed, 10 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 583 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OC3wkvvE1HgF-ZkRXGA:-OC3wkvw9HeUlpBT9AQ5:b-nnp64p) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004e1b8790b36a1aa5f218133d5edeb8a9e2f12/crates/blockifier/src/versioned_constants.rs#L583)):*
> ```XML
>             // The following are unsupported builtins in Cairo 1
>             BuiltinName::output => Err(GasCostsError::UnsupportedCairo1Builtin {builtin: *builtin,}),
>             BuiltinName::ecdsa => Err(GasCostsError::UnsupportedCairo1Builtin {builtin: *builtin,}),
> ```

Gather these variants in the same arm



_Code quote:_
```XML
            // The following are unsupported builtins in Cairo 1
            BuiltinName::output => Err(GasCostsError::UnsupportedCairo1Builtin {builtin: *builtin,}),
            BuiltinName::ecdsa => Err(GasCostsError::UnsupportedCairo1Builtin {builtin: *builtin,}),
```

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 577 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OC42mCf28PjL3JsWzHu:-OC42mCf28PjL3JsWzHv:b-jgsjjz) ([raw file](https://github.com/starkware-libs/sequencer/blob/b5ced97b0ffad1d9b8c2d15e380a68c49f023414/crates/blockifier/src/versioned_constants.rs#L577)):*
> ```XML
>             BuiltinName::ec_op => Ok(self.ecop_gas_cost),
>             //TODO (Yonatan): once keccak_builtin_gas_cost is being inserted to the versioned constants, replace the constant with field's value 
>             BuiltinName::keccak => Ok(KECCAK_BUILTIN_GAS_COST), 
> ```

For now I put the correct price manually. I suggest that for now we will merge it like this. This will help us achieve a separation between this task and the task of inserting keccak_builtin_gas_cost to the versioned constants. I think this is important because the latter will involve changes in the python repo as well, and thus take a little longer.

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: 0 of 3 files reviewed, 14 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 577 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OC42mCf28PjL3JsWzHu:-OC7nkDXEmXE0j6wwmfb:b-8ayu6x) ([raw file](https://github.com/starkware-libs/sequencer/blob/b5ced97b0ffad1d9b8c2d15e380a68c49f023414/crates/blockifier/src/versioned_constants.rs#L577)):*
<details><summary><i>Previously, Yonatan-Starkware wrote…</i></summary><blockquote>

For now I put the correct price manually. I suggest that for now we will merge it like this. This will help us achieve a separation between this task and the task of inserting keccak_builtin_gas_cost to the versioned constants. I think this is important because the latter will involve changes in the python repo as well, and thus take a little longer.
</blockquote></details>

Agree

**Review by avi-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: 2 of 3 files reviewed, 13 unresolved discussions (waiting on @meship-starkware and @Yonatan-Starkware)

___
*[`crates/blockifier/cairo_native` line 1 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OCDmhzm94APsvkdHrWf:-OCDmhzm94APsvkdHrWg:bmxz2o2) ([raw file](https://github.com/starkware-libs/sequencer/blob/16242539ca0d73d134cebf48e481710634ef7d12/crates/blockifier/cairo_native#L1)):*
> ```
> Subproject commit 564f7e2136e53a1e43033aefa3836b4dc591ffc1
> ```

Please fix the commit:
run `git submodule update --init --recursive`



_Code quote:_
```
Subproject commit 564f7e2136e53a1e43033aefa3836b4dc591ffc1
```

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 583 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OC3wkvvE1HgF-ZkRXGA:-OCSH1A52RY8uik0zB-Q:bs7wumb) ([raw file](https://github.com/starkware-libs/sequencer/blob/2004e1b8790b36a1aa5f218133d5edeb8a9e2f12/crates/blockifier/src/versioned_constants.rs#L583)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Gather these variants in the same arm
</blockquote></details>

Done.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: 1 of 3 files reviewed, 8 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

___
*[`crates/blockifier/cairo_native` line 1 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OCDmhzm94APsvkdHrWf:-OCSP8b_6_DaH6oGMsFr:b7hsaz) ([raw file](https://github.com/starkware-libs/sequencer/blob/16242539ca0d73d134cebf48e481710634ef7d12/crates/blockifier/cairo_native#L1)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Please fix the commit:
run `git submodule update --init --recursive`
</blockquote></details>

Blocking until reverted
___
*[`crates/blockifier/src/versioned_constants.rs` line 584 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OCSPVFXB4DlGXiNbHN3:-OCSPVFXB4DlGXiNbHN4:bxxtxro) ([raw file](https://github.com/starkware-libs/sequencer/blob/4bae353a27b804c6ca62061e60622e29694a067a/crates/blockifier/src/versioned_constants.rs#L584)):*
> ```XML
>             BuiltinName::mul_mod => Ok(self.mul_mod_gas_cost),
>             BuiltinName::segment_arena => Err(GasCostsError::VirtualBuiltin),
>             // The following are unsupported builtins in Cairo 1
> ```

The error is self-explenatory
___
*[`crates/blockifier/src/versioned_constants.rs` line 614 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OCSPlbK62HFHFldtIz4:-OCSPlbK62HFHFldtIz5:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4bae353a27b804c6ca62061e60622e29694a067a/crates/blockifier/src/versioned_constants.rs#L614)):*
> ```XML
>             SyscallSelector::StorageRead => Ok(self.storage_read_gas_cost),
>             SyscallSelector::StorageWrite => Ok(self.storage_write_gas_cost),
>             // The following are unsupported syscalls in Cairo 1
> ```


___
*[`crates/blockifier/src/versioned_constants.rs` line 822 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OCSQ1nL8GyeZED1LSGo:-OCSQ1nL8GyeZED1LSGp:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4bae353a27b804c6ca62061e60622e29694a067a/crates/blockifier/src/versioned_constants.rs#L822)):*
> ```XML
>     UnsupportedBuiltinInCairo1 {builtin: BuiltinName},
>     #[error("a virtual builtin cannot be used in a smart contract")]
>     VirtualBuiltin,
> ```





_Suggestion:_
```XML
pub enum GasCostsError {
    #[error("used syscall: {:?} is not supported in a Cairo 0 contract.", selector)]
    DeprecatedSyscall {selector: SyscallSelector},
    #[error("used builtin: {:?} is not supported in a Cairo 1 contract.", builtin)]
    UnsupportedBuiltinInCairo1 {builtin: BuiltinName},
    #[error("a virtual builtin does not have a gas cost.")]
    VirtualBuiltin,
```

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: 1 of 3 files reviewed, 7 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 584 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OCSPVFXB4DlGXiNbHN3:-OCSxIPx1tUoAObC23nY:b-ode52m) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b21fc4d5d562ca28e90dc1707115ba78f18f502/crates/blockifier/src/versioned_constants.rs#L584)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

The error is self-explenatory
</blockquote></details>

(Remove the comment)
___
*[`crates/blockifier/src/versioned_constants.rs` line 614 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OCSPlbK62HFHFldtIz4:-OCSxL6J54WpbaOIbE2M:b-ode52m) ([raw file](https://github.com/starkware-libs/sequencer/blob/2b21fc4d5d562ca28e90dc1707115ba78f18f502/crates/blockifier/src/versioned_constants.rs#L614)):*
> ```XML
>             SyscallSelector::StorageRead => Ok(self.storage_read_gas_cost),
>             SyscallSelector::StorageWrite => Ok(self.storage_write_gas_cost),
>             // The following are unsupported syscalls in Cairo 1
> ```

(Remove the comment)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 597 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OCSxvkdABKvlYCE3q5c:-OCSxvkdABKvlYCE3q5d:b-89fcom) ([raw file](https://github.com/starkware-libs/sequencer/blob/7f1ff03e850b14ef4da3feb0f410b0910251c637/crates/blockifier/src/versioned_constants.rs#L597)):*
> ```XML
>     pub fn get_syscall_gas_cost(&self, selector: &SyscallSelector) -> Result<u64, GasCostsError> {
>         match selector {
>             SyscallSelector::CallContract => Ok(self.call_contract_gas_cost),
> ```

Remove the Ok here as well



_Code quote:_
```XML
Ok(
```

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 597 at r10](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-OCSxvkdABKvlYCE3q5c:-OCT-Kc3DJedoKiUMMGe:b-7rl0kd) ([raw file](https://github.com/starkware-libs/sequencer/blob/7f1ff03e850b14ef4da3feb0f410b0910251c637/crates/blockifier/src/versioned_constants.rs#L597)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Remove the Ok here as well
</blockquote></details>

done

**Review by Yoni-Starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @Yonatan-Starkware)

**Review by meship-starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 1 of 2 files at r10, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Review by meship-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2067#-:-OCTdBj4Bh6eperdB9Y2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @avi-starkware)

**Pull request merged**
