### PR TITLE
feat(sequencer_node): add required params test util

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #1725
- #1710
- #1709
- #1708
- #1707 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by nadin-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1707)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/Cargo.toml` line 41 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1707#-OAY0HJ_2g-j9-BWq4GZ:-OAY0HJ_2g-j9-BWq4G_:b-n6d6dn) ([raw file](https://github.com/starkware-libs/sequencer/blob/93ecb9d098eb1da8af5ce4d7c68c06b6a00c6c60/crates/mempool_node/Cargo.toml#L41)):*
> ```TOML
> tracing.workspace = true
> validator.workspace = true
> ```

Please remove

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1707)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/mempool_node/Cargo.toml` line 41 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1707#-OAY0HJ_2g-j9-BWq4GZ:-OAYkxl07qNj-WLZpjxx:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/93ecb9d098eb1da8af5ce4d7c68c06b6a00c6c60/crates/mempool_node/Cargo.toml#L41)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

Please remove
</blockquote></details>

Done.

**Review by nadin-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1707)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_node/src/config/test_utils.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1707#-OAgyQod9yparAiUWKav:-OAgyQoe-30_8MTYz9U9:b-ndadqh) ([raw file](https://github.com/starkware-libs/sequencer/blob/f8fd51cc7e42ac51e2ec349e93452bc49f0671cf/crates/mempool_node/src/config/test_utils.rs#L8)):*
> ```XML
> /// Required parameters utility struct.
> #[gen_field_names_fn]
> pub struct RequiredParams {
> ```

why is this located in test_utils?



_Code quote:_
```XML
pub struct RequiredParams
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1707)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/mempool_node/src/config/test_utils.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1707#-OAgyQod9yparAiUWKav:-OAkt12W40KGLcc2pOsw:b-4vgzmc) ([raw file](https://github.com/starkware-libs/sequencer/blob/f8fd51cc7e42ac51e2ec349e93452bc49f0671cf/crates/mempool_node/src/config/test_utils.rs#L8)):*
<details><summary><i>Previously, nadin-Starkware (Nadin Jbara) wrote…</i></summary><blockquote>

why is this located in test_utils?
</blockquote></details>

This is used only for testing: this is a more genric way of supplying required parameters for tests. In production we'd have presets.

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#1709](https://github.com/starkware-libs/sequencer/pull/1709)

**Review by nadin-Starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1707)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

**Pull request closed without merging**
