### PR TITLE
refactor(blockifier): remove gas cost duplication in versioned constants

### PR DESCRIPTION
**Pull request by Yonatan-Starkware**

### CODE REVIEW

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 353 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9jE3IU-kqcVvDCMYGX:-O9jE3IU-kqcVvDCMYGY:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0557883907e84df45dc1f24f82a999c8b0ac60f/crates/blockifier/src/versioned_constants.rs#L353)):*
> ```XML
>     // calculating syscalls gas costs using os resources
>     pub fn calc_syscall_gas_cost(&self, syscall_selector: &SyscallSelector) -> u64 {
>         let constants = &self.os_constants.gas_costs;
> ```





_Suggestion:_
```XML
        let constant_gas_costs = &self.os_constants.gas_costs;
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 351 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9jN1NH5giRGLG_5ox0:-O9jN1NH5giRGLG_5ox1:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0557883907e84df45dc1f24f82a999c8b0ac60f/crates/blockifier/src/versioned_constants.rs#L351)):*
> ```XML
>     // }
> 
>     // calculating syscalls gas costs using os resources
> ```





_Suggestion:_
```XML
/// Calculates a syscall's gas costs from the os resources.
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 353 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9jOkoK1dXBcbaTyiLO:-O9jOkoK1dXBcbaTyiLP:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0557883907e84df45dc1f24f82a999c8b0ac60f/crates/blockifier/src/versioned_constants.rs#L353)):*
> ```XML
>     // calculating syscalls gas costs using os resources
>     pub fn calc_syscall_gas_cost(&self, syscall_selector: &SyscallSelector) -> u64 {
>         let constants = &self.os_constants.gas_costs;
> ```





_Suggestion:_
```XML
 let gas_costs = &self.os_constants.gas_costs;
```

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 329 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9odBP801Snp-h65Te-:-O9odBP801Snp-h65Te0:b-t8clgb) ([raw file](https://github.com/starkware-libs/sequencer/blob/929012ea0a6513d201196cf1f93671c9f3f1be0b/crates/blockifier/src/execution/syscalls/hint_processor.rs#L329)):*
> ```XML
>         if selector == SyscallSelector::Keccak {
>             assert_ne!(syscall_gas_cost_in_os_constants, 0);
>         }
> ```

I don't understand.
You sometimes want to calculate using the formula and sometimes take the fixed cost?
Or do you always just take the non-zero gas costs from the constants if their constant cost is 0?
If you only calculate the gas cost if the fixed cost is 0, then I think you should put all this logic inside `calc_syscall_gas_cost` and have just one function to call here to get the cost you need.



_Code quote:_
```XML
        let syscall_gas_cost_in_os_constants =
            self.context.gas_costs().get_syscall_gas_cost_in_os_constants(&selector);
        let syscall_gas_cost = match syscall_gas_cost_in_os_constants {
            0 => self.context.versioned_constants().calc_syscall_gas_cost(&selector),
            _ => syscall_gas_cost_in_os_constants,
        };

        if selector == SyscallSelector::Keccak {
            assert_ne!(syscall_gas_cost_in_os_constants, 0);
        }
```

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1480)* status: 6 of 14 files reviewed, 8 unresolved discussions (waiting on @avi-starkware, @noaov1, and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 341 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9o_35VA81iLBHKQX6H:-O9o_35VA81iLBHKQX6I:b-3mwmmz) ([raw file](https://github.com/starkware-libs/sequencer/blob/929012ea0a6513d201196cf1f93671c9f3f1be0b/crates/blockifier/src/versioned_constants.rs#L341)):*
> ```XML
>         let constant_gas_costs = &self.os_constants.gas_costs;
>         let execution_resources =
>             &self.os_resources.execute_syscalls.get(syscall_selector).expect("unvalid syscall");
> ```

The variable syscall_selector is of type `SyscallSelector`. All variables of this type should point to a valid syscall. If this `get` fails, then there is a bug.



_Suggestion:_
```XML
Fetching the execution resources of a syscall should not fail.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 346 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9o_kmf3IRkXhjdcjDP:-O9o_kmf3IRkXhjdcjDQ:bn2v9bs) ([raw file](https://github.com/starkware-libs/sequencer/blob/929012ea0a6513d201196cf1f93671c9f3f1be0b/crates/blockifier/src/versioned_constants.rs#L346)):*
> ```XML
>         let mut total_builtin_gas_cost: u64 = 0;
> 
>         for (builtin, amount) in &execution_resources.builtin_instance_counter {
> ```

Makes it clearer that the `for` and the `let` are related.



_Suggestion:_
```XML

        let mut total_builtin_gas_cost: u64 = 0;
        for (builtin, amount) in &execution_resources.builtin_instance_counter {
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 573 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9o_xzODQBT1DFWjmwh:-O9o_xzODQBT1DFWjmwi:b-wmbjvq) ([raw file](https://github.com/starkware-libs/sequencer/blob/929012ea0a6513d201196cf1f93671c9f3f1be0b/crates/blockifier/src/versioned_constants.rs#L573)):*
> ```XML
>     pub transaction_gas_cost: u64,
>     // Syscall gas costs.
>     #[serde(default)]
> ```

Isn't the default of `u64` just `0`? Why are we adding all these costs back?



_Code quote:_
```XML
    #[serde(default)]
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 628 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9oaAQl6tqtXlG5mLah:-O9oaAQl6tqtXlG5mLai:b-960830) ([raw file](https://github.com/starkware-libs/sequencer/blob/929012ea0a6513d201196cf1f93671c9f3f1be0b/crates/blockifier/src/versioned_constants.rs#L628)):*
> ```XML
>             BuiltinName::pedersen => self.pedersen_gas_cost,
>             BuiltinName::ecdsa => 0,
>             BuiltinName::keccak => 0, // TODO: need to understand how to approach this one
> ```

If this is a comment for yourself, just delete it.
If you want to keep this todo here, then please write it clearly so that other people can understand what you mean here, and please use our standard TODO format (look for TODO examples in repo and you will get what the format is ).



_Suggestion:_
```XML
            BuiltinName::keccak => 0,
```

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 573 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9o_xzODQBT1DFWjmwh:-O9oh-2F1w0YihUZoVnl:b-y6m70l) ([raw file](https://github.com/starkware-libs/sequencer/blob/929012ea0a6513d201196cf1f93671c9f3f1be0b/crates/blockifier/src/versioned_constants.rs#L573)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Isn't the default of `u64` just `0`? Why are we adding all these costs back?
</blockquote></details>

this is there to let the serde know that this field might not be in the json. Without it the deseriliazation process gives errors.

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 329 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9odBP801Snp-h65Te-:-O9oiKGM6iKhmhsGjphw:b-uc9iu8) ([raw file](https://github.com/starkware-libs/sequencer/blob/929012ea0a6513d201196cf1f93671c9f3f1be0b/crates/blockifier/src/execution/syscalls/hint_processor.rs#L329)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I don't understand.
You sometimes want to calculate using the formula and sometimes take the fixed cost?
Or do you always just take the non-zero gas costs from the constants if their constant cost is 0?
If you only calculate the gas cost if the fixed cost is 0, then I think you should put all this logic inside `calc_syscall_gas_cost` and have just one function to call here to get the cost you need.
</blockquote></details>

for now the the gas costs in the os resources and in the os constants are identical, so we can erase them from the os constants. 
The match here, together with the decision to leave the syscall_gas_cost fields in the GasCosts struct, is for future compatibility- we want to allow an option for the gas costs values to be different, even just for some specific syscalls. 
Either way, putting this match inside calc_syscall_gas_cost is a good sugesstion, and I will try to do it in this way.

**Review by Yonatan-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1480)* status: all files reviewed, 8 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 341 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9o_35VA81iLBHKQX6H:-O9og8auBhmLhJFL1Ide:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/929012ea0a6513d201196cf1f93671c9f3f1be0b/crates/blockifier/src/versioned_constants.rs#L341)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

The variable syscall_selector is of type `SyscallSelector`. All variables of this type should point to a valid syscall. If this `get` fails, then there is a bug.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 346 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9o_kmf3IRkXhjdcjDP:-O9ogTQI8vngtYRtMLPP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/929012ea0a6513d201196cf1f93671c9f3f1be0b/crates/blockifier/src/versioned_constants.rs#L346)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Makes it clearer that the `for` and the `let` are related.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 628 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9oaAQl6tqtXlG5mLah:-O9oi2A27Fbf9koQuxtO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/929012ea0a6513d201196cf1f93671c9f3f1be0b/crates/blockifier/src/versioned_constants.rs#L628)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

If this is a comment for yourself, just delete it.
If you want to keep this todo here, then please write it clearly so that other people can understand what you mean here, and please use our standard TODO format (look for TODO examples in repo and you will get what the format is ).
</blockquote></details>

Done.

**Review by avi-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1480)* status: all files reviewed, 7 unresolved discussions (waiting on @noaov1 and @Yonatan-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 352 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9jMltQ2ERs7r8lWNv8:-O9p23kb7-kHJ8ovVupY:b4cqnso) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0557883907e84df45dc1f24f82a999c8b0ac60f/crates/blockifier/src/versioned_constants.rs#L352)):*
> ```XML
> 
>     // calculating syscalls gas costs using os resources
>     pub fn calc_syscall_gas_cost(&self, syscall_selector: &SyscallSelector) -> u64 {
> ```

Please rename the prefix of this function to either `get_` as I suggested or to `calculate_`.
We generally avoid using partial words in function and variable names, as this can make the code harder to read.
___
*[`crates/blockifier/src/versioned_constants.rs` line 337 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9p0tBrAc48IkgWCoku:-O9p0tBrAc48IkgWCokv:bkt4b4u) ([raw file](https://github.com/starkware-libs/sequencer/blob/929012ea0a6513d201196cf1f93671c9f3f1be0b/crates/blockifier/src/versioned_constants.rs#L337)):*
> ```XML
>     }
> 
>     // Calculates syscalls gas costs using the information in os resources
> ```

Note your docstring still has grammar mistakes. Also, a docstring should start with `///` instead of `//` of a regular comment.



_Suggestion:_
```XML
/// Calculates a syscall's gas costs from the execution resources and os constants.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 341 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9o_35VA81iLBHKQX6H:-O9p0fMa0lm5saEJ8PNQ:b-njq066) ([raw file](https://github.com/starkware-libs/sequencer/blob/929012ea0a6513d201196cf1f93671c9f3f1be0b/crates/blockifier/src/versioned_constants.rs#L341)):*
<details><summary><i>Previously, Yonatan-Starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did you not push it?
___
*[`crates/blockifier/src/versioned_constants.rs` line 346 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9o_kmf3IRkXhjdcjDP:-O9p0mLI3ipbI5PSyYHW:b-uli6j8) ([raw file](https://github.com/starkware-libs/sequencer/blob/929012ea0a6513d201196cf1f93671c9f3f1be0b/crates/blockifier/src/versioned_constants.rs#L346)):*
<details><summary><i>Previously, Yonatan-Starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did you forget to push?
___
*[`crates/blockifier/src/versioned_constants.rs` line 351 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9p2iYh-3Ahm6sN-sjj:-O9p2iYh-3Ahm6sN-sjk:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/929012ea0a6513d201196cf1f93671c9f3f1be0b/crates/blockifier/src/versioned_constants.rs#L351)):*
> ```XML
>         }
> 
>         let n_entry_point = match syscall_selector {
> ```





_Suggestion:_
```XML
        let n_entry_points = match syscall_selector {
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 329 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9odBP801Snp-h65Te-:-O9p3KoVEUceVLfiJ5bZ:bb71kmx) ([raw file](https://github.com/starkware-libs/sequencer/blob/929012ea0a6513d201196cf1f93671c9f3f1be0b/crates/blockifier/src/execution/syscalls/hint_processor.rs#L329)):*
<details><summary><i>Previously, Yonatan-Starkware wrote…</i></summary><blockquote>

for now the the gas costs in the os resources and in the os constants are identical, so we can erase them from the os constants. 
The match here, together with the decision to leave the syscall_gas_cost fields in the GasCosts struct, is for future compatibility- we want to allow an option for the gas costs values to be different, even just for some specific syscalls. 
Either way, putting this match inside calc_syscall_gas_cost is a good sugesstion, and I will try to do it in this way.
</blockquote></details>

Okay

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 4 of 8 files at r1, 2 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1480)* status: all files reviewed, 7 unresolved discussions (waiting on @avi-starkware, @noaov1, @Yonatan-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 329 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9odBP801Snp-h65Te-:-OBelnn_7vG52SKG7RhB:b5n71yy) ([raw file](https://github.com/starkware-libs/sequencer/blob/929012ea0a6513d201196cf1f93671c9f3f1be0b/crates/blockifier/src/execution/syscalls/hint_processor.rs#L329)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Okay
</blockquote></details>

We talked with Yoni, and the solution is to change the VC structure. We will add a "syscall_gas_cost" level in os_constants so that all the syscall gas costs will be under so we either have all of the syscall gas costs or none. We will only put a default value on the syscall_gas_cost level.

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 351 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9p2iYh-3Ahm6sN-sjj:-OBiybmu8god42ypLn1n:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/929012ea0a6513d201196cf1f93671c9f3f1be0b/crates/blockifier/src/versioned_constants.rs#L351)):*
> ```XML
>         }
> 
>         let n_entry_point = match syscall_selector {
> ```

done

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 353 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9jE3IU-kqcVvDCMYGX:-OBiygZBCzzRhWJZyBnu:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0557883907e84df45dc1f24f82a999c8b0ac60f/crates/blockifier/src/versioned_constants.rs#L353)):*
> ```XML
>     // calculating syscalls gas costs using os resources
>     pub fn calc_syscall_gas_cost(&self, syscall_selector: &SyscallSelector) -> u64 {
>         let constants = &self.os_constants.gas_costs;
> ```

done

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 352 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9jMltQ2ERs7r8lWNv8:-OBixma22QopBgjTV-of:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0557883907e84df45dc1f24f82a999c8b0ac60f/crates/blockifier/src/versioned_constants.rs#L352)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Please rename the prefix of this function to either `get_` as I suggested or to `calculate_`.
We generally avoid using partial words in function and variable names, as this can make the code harder to read.
</blockquote></details>

done

**Comment by Yonatan-Starkware** [comment]
*[`crates/blockifier/src/versioned_constants.rs` line 351 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1480#-O9jN1NH5giRGLG_5ox0:-OBixRXc1R_X-R2F5WF6:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/d0557883907e84df45dc1f24f82a999c8b0ac60f/crates/blockifier/src/versioned_constants.rs#L351)):*
> ```XML
>     // }
> 
>     // calculating syscalls gas costs using os resources
> ```

done

**Pull request closed without merging**
