### PR TITLE
chore(blockifier_reexecution): offline reexecution from file

### PR DESCRIPTION
**Pull request by aner-starkware**

### CODE REVIEW

**Comment by aner-starkware** [comment]
Refactoring to reduce code duplication in following PR: https://reviewable.io/reviews/starkware-libs/sequencer/1814

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1764)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/blockifier_reexecution/src/main.rs` line 199 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1764#-OAwQCyC8ExcJP0vC9la:-OAwQCyC8ExcJP0vC9lb:b-so3mo8) ([raw file](https://github.com/starkware-libs/sequencer/blob/b7b358781c3d187ebb0c70f22d2ec1a857ad97ec/crates/blockifier_reexecution/src/main.rs#L199)):*
> ```XML
> 
>             // TODO(Aner): compute correct block hash at storage slot 0x1 instead of removing it.
>             expected_state_diff.storage_updates.shift_remove(&ContractAddress(1_u128.into()));
> ```

call `pre_process_block` first, and then you can delete these lines, no?



_Suggestion:_
```XML
            transaction_executor.execute_txs(&all_txs_in_next_block);
            // Finalize block and read actual statediff.
            let (actual_state_diff, _, _) =
                transaction_executor.finalize().expect("Couldn't finalize block");
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1764)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

**Review by AvivYossef-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1764#-:-OB4zjjeAnCNNrzg-aGO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1764)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)

**Pull request merged**
