### PR TITLE
feat(blockifier): add n_allocated_keys

### PR DESCRIPTION
**Pull request by yoavGrs**

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2149)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware and @yoavGrs)

___
*[`crates/blockifier/src/state/cached_state.rs` line 687 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2149#-OC3VfFw0EYbo9B6_UaV:-OC3VfFw0EYbo9B6_UaW:bh5nenb) ([raw file](https://github.com/starkware-libs/sequencer/blob/63e320159e0c006a9975a4499f69f040c6a03740/crates/blockifier/src/state/cached_state.rs#L687)):*
> ```XML
> 
> impl AllocatedKeys {
>     pub fn extend(&mut self, state_change: &StateChanges) {
> ```

you are not going to implement this with `extend` later



_Suggestion:_
```XML
update
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 692 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2149#-OC3Vpm-498xldSvOFm_:-OC3Vpm-498xldSvOFma:b-dm4xiy) ([raw file](https://github.com/starkware-libs/sequencer/blob/63e320159e0c006a9975a4499f69f040c6a03740/crates/blockifier/src/state/cached_state.rs#L692)):*
> ```XML
>     }
> 
>     pub fn count(&self) -> usize {
> ```

seems natural, non-blocking



_Suggestion:_
```XML
len
```

**Comment by yoavGrs** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2149?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2149** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2149?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2149?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2175** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2175?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2174** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2174?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2173** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2173?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2172** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2172?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2149)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/2149#-OC-iaNsEXx2kvASx197:-OC3nnTyB5dOD8mIaeY5:b-896fix) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please split this PR
there are functions being moved to different types here, they can be separated (if you can think of other things that can be split away please do)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 687 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2149#-OC3VfFw0EYbo9B6_UaV:-OC3oKDF7XH0rINqxKMS:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/63e320159e0c006a9975a4499f69f040c6a03740/crates/blockifier/src/state/cached_state.rs#L687)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you are not going to implement this with `extend` later
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 692 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2149#-OC3Vpm-498xldSvOFm_:-OC3pBmZ4sYouK9l71oj:boz157l) ([raw file](https://github.com/starkware-libs/sequencer/blob/63e320159e0c006a9975a4499f69f040c6a03740/crates/blockifier/src/state/cached_state.rs#L692)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

seems natural, non-blocking
</blockquote></details>

Rust asks me to implement `is_empty` as well.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2149)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2149)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Comment by yoavGrs** [comment]
### Merge activity

* **Nov 26, 5:53 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2149).

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2149)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
