### PR TITLE
test(sync): add e2e test for p2p sync

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/423)

### CODE REVIEW

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/423#-:-O4AQAHIAgbN1TndTiFq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @ShahakShama)

___
*[`scripts/papyrus/p2p_sync_e2e_test/client_node_config.json` line 8 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/423#-O4AQ2-z1IwiDV5st0Y0:-O4AQ2-z1IwiDV5st0Y1:bg9k6vl) ([raw file](https://github.com/starkware-libs/sequencer/blob/47964370187f65157d9cb859d2c28190c5fe80bc/scripts/papyrus/p2p_sync_e2e_test/client_node_config.json#L8)):*
> ```JSON
>     "storage.db_config.path_prefix": "./scripts/papyrus/p2p_sync_e2e_test/data_client",
>     "monitoring_gateway.server_address": "127.0.0.1:8082",
>     "collect_metrics": true,
> ```

is this the minimal amount of args for this test to work?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/423)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

___
*[`scripts/papyrus/p2p_sync_e2e_test/client_node_config.json` line 8 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/423#-O4AQ2-z1IwiDV5st0Y0:-O4AQnGkBzfeiU4wsqGq:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/47964370187f65157d9cb859d2c28190c5fe80bc/scripts/papyrus/p2p_sync_e2e_test/client_node_config.json#L8)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

is this the minimal amount of args for this test to work?
</blockquote></details>

Done

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/423#-:-O4ARK9WEmWbgGmjCKPc:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @ShahakShama)

___
*[`scripts/papyrus/p2p_sync_e2e_test/p2p_sync_client.json` line 2 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/423#-O4AR9NMBDf0_h41J8Mg:-O4AR9NMBDf0_h41J8Mh:bhtapfa) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e09b84046b7687e3490d7cd30144c0f909c4a82/scripts/papyrus/p2p_sync_e2e_test/p2p_sync_client.json#L2)):*
> ```JSON
> {
>     "central.http_headers": "X-Throttling-Bypass:dlaxszinf1zggax2xfbqeujanj603hhry8vli3vma34j",
> ```

here too?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/423)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

___
*[`scripts/papyrus/p2p_sync_e2e_test/p2p_sync_client.json` line 2 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/423#-O4AR9NMBDf0_h41J8Mg:-O4ARdDD-lnqC4tDDXPB:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e09b84046b7687e3490d7cd30144c0f909c4a82/scripts/papyrus/p2p_sync_e2e_test/p2p_sync_client.json#L2)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

here too?
</blockquote></details>

Done

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/423#-:-O4ARoU4D4Hy4KRqflrZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AlonLStarkWare)

**Pull request merged**
