### PR TITLE
feat(sequencer_node): add NetworkConfig to SequencerNodeConfig

### PR DESCRIPTION
**Pull request by ShahakShama**

### CODE REVIEW

**Comment by lotem-starkware** [comment]
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1446)

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1446)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @AlonLStarkWare and @ShahakShama)

___
*[`crates/mempool_p2p/src/lib.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1446#-O9G87cZ8ss50nABopEG:-O9G87c_0A-14OqjxoMK:bmo4pv) ([raw file](https://github.com/starkware-libs/sequencer/blob/e06a7a47476afdd87f1c865e8b2d482fde693ac4/crates/mempool_p2p/src/lib.rs#L28)):*
> ```XML
>         append_sub_config_name(self.network_config.dump(), "network_config")
>     }
> }
> ```

Consider moving this to a `config.rs` module.



_Code quote:_
```XML
#[derive(Debug, Default, Deserialize, Serialize, Clone, PartialEq, Validate)]
pub struct MempoolP2pConfig {
    #[validate]
    pub network_config: NetworkConfig,
}

impl SerializeConfig for MempoolP2pConfig {
    fn dump(&self) -> BTreeMap<ParamPath, SerializedParam> {
        append_sub_config_name(self.network_config.dump(), "network_config")
    }
}
```
___
*[`crates/mempool_p2p/src/lib.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1446#-O9G8F0e4QvY-otnQMzZ:-O9G8F0e4QvY-otnQMz_:b-guj8mg) ([raw file](https://github.com/starkware-libs/sequencer/blob/e06a7a47476afdd87f1c865e8b2d482fde693ac4/crates/mempool_p2p/src/lib.rs#L35)):*
> ```XML
>     version: Option<String>,
>     buffer_size: usize,
>     topic: Topic,
> ```

Recall this function should be invoked by `main.rs`, which only has `MempoolP2pConfig` with relevant data towards this module.

I assume you can derive the required `version`, `buffer_size`, and `topic` from the `MempoolP2pConfig` config.
If so, please do, within this implementation (i.e., I would like the fn args to include only the config and the client).
If not, please let's discuss in person.



_Code quote:_
```XML
    version: Option<String>,
    buffer_size: usize,
    topic: Topic,
```

**Review by AlonLStarkWare — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1446#-:-OAHBtHYD7qR6KGb8_2Y:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

**Review by AlonLStarkWare — CHANGES_REQUESTED** [review]
Retracted...
Notice the failed tests

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1446#-:-OAHDQ3m8xt8VmJyZRus:b-9qr82q)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1446)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @AlonLStarkWare and @Itay-Tsabary-Starkware)

___
*[`crates/mempool_p2p/src/lib.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1446#-O9G8F0e4QvY-otnQMzZ:-OAHLDe4E6hbEhtzebmv:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/e06a7a47476afdd87f1c865e8b2d482fde693ac4/crates/mempool_p2p/src/lib.rs#L35)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Recall this function should be invoked by `main.rs`, which only has `MempoolP2pConfig` with relevant data towards this module.

I assume you can derive the required `version`, `buffer_size`, and `topic` from the `MempoolP2pConfig` config.
If so, please do, within this implementation (i.e., I would like the fn args to include only the config and the client).
If not, please let's discuss in person.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> Reviewed 4 of 7 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1446)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by AlonLStarkWare — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1446#-:-OAHMVuT8lRfLtd5PdJd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by AlonLStarkWare — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1446)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
