### PR TITLE
refactor(batcher): move height mgmt out to the batcher

### PR DESCRIPTION
**Pull request by dafnamatsry**

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2192)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-OC8zBL6Dj9AOr3Ow8x6:-OC8zBL6Dj9AOr3Ow8x7:bbwhcm7) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e7676241f723df1e9cc1634d1e99b71c97dd558/crates/starknet_batcher/src/batcher.rs#L84)):*
> ```XML
>     pub async fn start_height(&mut self, input: StartHeightInput) -> BatcherResult<()> {
>         self.propose_tx_streams.clear();
>         self.validate_tx_streams.clear();
> ```

It was bad that it was cleared before, right?



_Code quote:_
```XML
        self.propose_tx_streams.clear();
        self.validate_tx_streams.clear();
```
___
*[`crates/starknet_batcher/src/batcher.rs` line 339 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-OC8szItEY3ah9Y_VJ27:-OC8szItEY3ah9Y_VJ28:b6oq40q) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e7676241f723df1e9cc1634d1e99b71c97dd558/crates/starknet_batcher/src/batcher.rs#L339)):*
> ```XML
> }
> 
> impl From<StartHeightError> for BatcherError {
> ```

Love it.
___
*[`crates/starknet_batcher/src/batcher.rs` line 124 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-OC8slptC2XWaJvIa0Vc:-OC8slptC2XWaJvIa0Vd:b-l45qpk) ([raw file](https://github.com/starkware-libs/sequencer/blob/adda41faace720b29af20c08b049ae3d19ce9037/crates/starknet_batcher/src/batcher.rs#L124)):*
> ```XML
>         propose_block_input: ProposeBlockInput,
>     ) -> BatcherResult<()> {
>         self.active_height.ok_or(BatcherError::NoActiveHeight)?;
> ```

Would this work? Instead of needing to `expect` it later.



_Suggestion:_
```XML
let active_height = self.active_height.ok_or(BatcherError::NoActiveHeight)?;
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 144 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-OC96WBjEDQ9dDFV7LoL:-OC96WBjEDQ9dDFV7LoM:b-o8fsr3) ([raw file](https://github.com/starkware-libs/sequencer/blob/adda41faace720b29af20c08b049ae3d19ce9037/crates/starknet_batcher/src/batcher_test.rs#L144)):*
> ```XML
> #[rstest]
> #[tokio::test]
> async fn start_height_success() {
> ```

Are these the exact tests that were in the proposal manager (with only the necessary semantic changes)?
If not can you first copy them and then refactor/changes in a new PR? It will be much easier to review

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2192)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-OC8zBL6Dj9AOr3Ow8x6:-OCCYrQtBUGPORW2KbqX:b-najv6g) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e7676241f723df1e9cc1634d1e99b71c97dd558/crates/starknet_batcher/src/batcher.rs#L84)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

It was bad that it was cleared before, right?
</blockquote></details>

Yes, I think so. I wouldn't expect any side effects to happen if the call fails.
___
*[`crates/starknet_batcher/src/batcher.rs` line 124 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-OC8slptC2XWaJvIa0Vc:-OCC_LcN0iCpLZkXGfoP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/adda41faace720b29af20c08b049ae3d19ce9037/crates/starknet_batcher/src/batcher.rs#L124)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Would this work? Instead of needing to `expect` it later.
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher.rs` line 339 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-OC8szItEY3ah9Y_VJ27:-OCC_MpA1p5dYawUM7Zg:b32vhw) ([raw file](https://github.com/starkware-libs/sequencer/blob/4e7676241f723df1e9cc1634d1e99b71c97dd558/crates/starknet_batcher/src/batcher.rs#L339)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Love it.
</blockquote></details>

:)
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 144 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-OC96WBjEDQ9dDFV7LoL:-OCCe-Oo3i-4ERBIY3_0:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/adda41faace720b29af20c08b049ae3d19ce9037/crates/starknet_batcher/src/batcher_test.rs#L144)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Are these the exact tests that were in the proposal manager (with only the necessary semantic changes)?
If not can you first copy them and then refactor/changes in a new PR? It will be much easier to review
</blockquote></details>

Done.

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2192)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 144 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-OC96WBjEDQ9dDFV7LoL:-OCCg2i_ET-BsdTk0Y4i:bnnzatx) ([raw file](https://github.com/starkware-libs/sequencer/blob/adda41faace720b29af20c08b049ae3d19ce9037/crates/starknet_batcher/src/batcher_test.rs#L144)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The followup PR: https://reviewable.io/reviews/starkware-libs/sequencer/2205

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2192)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 172 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-OCCm79Z6qO1M6wxyA4g:-OCCm79Z6qO1M6wxyA4h:b-vb3s6d) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eb0a08459ed0559f38e44e4c0135208a86599c5/crates/starknet_batcher/src/batcher_test.rs#L172)):*
> ```XML
>     let mut batcher = batcher(proposal_manager);
>     let result = batcher.start_height(StartHeightInput { height }).await;
>     assert_eq!(format!("{:?}", result), format!("{:?}", expected_result));
> ```

BatcherError does implement PartialEq. Can you compare the actual values?



_Code quote:_
```XML
assert_eq!(format!("{:?}", result), format!("{:?}", expected_result));
```
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 183 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-OCCpGKh3ShdLme5EZS8:-OCCpGKh3ShdLme5EZS9:bsbn0e6) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eb0a08459ed0559f38e44e4c0135208a86599c5/crates/starknet_batcher/src/batcher_test.rs#L183)):*
> ```XML
>     let mut batcher = batcher(proposal_manager);
> 
>     assert_matches!(
> ```

You can also change most of these in the file.



_Suggestion:_
```XML
assert_eq!
```

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2192)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher_test.rs` line 172 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-OCCm79Z6qO1M6wxyA4g:-OCD02w159WP6NruTt6t:bm3vnxk) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eb0a08459ed0559f38e44e4c0135208a86599c5/crates/starknet_batcher/src/batcher_test.rs#L172)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

BatcherError does implement PartialEq. Can you compare the actual values?
</blockquote></details>

I change it in the next PR.
___
*[`crates/starknet_batcher/src/batcher_test.rs` line 183 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-OCCpGKh3ShdLme5EZS8:-OCD0Fqw5bNij2OjNVhP:bmvd1lw) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eb0a08459ed0559f38e44e4c0135208a86599c5/crates/starknet_batcher/src/batcher_test.rs#L183)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You can also change most of these in the file.
</blockquote></details>

Same :)

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2192)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5 and @dafnamatsry)

___
*[`crates/starknet_batcher/src/batcher.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-OCD-Yxe7e-zWiPR3bPS:-OCD-Yxe7e-zWiPR3bPT:bv981fs) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eb0a08459ed0559f38e44e4c0135208a86599c5/crates/starknet_batcher/src/batcher.rs#L84)):*
> ```XML
>     }
> 
>     pub async fn start_height(&mut self, input: StartHeightInput) -> BatcherResult<()> {
> ```

Can you please add `#[instrument(skip(self), err)]`?
___
*[`crates/starknet_batcher/src/batcher.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-OCD-non67oejP82REW8:-OCD-non67oejP82REW9:bwhjcod) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eb0a08459ed0559f38e44e4c0135208a86599c5/crates/starknet_batcher/src/batcher.rs#L95)):*
> ```XML
>                 "Storage is not synced. Storage height: {}, requested height: {}.",
>                 storage_height, input.height
>             );
> ```

And then this is unnecessary



_Code quote:_
```XML
            error!(
                "Storage is not synced. Storage height: {}, requested height: {}.",
                storage_height, input.height
            );
```

**Review by alonh5 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-:-OCD2RJ--sZRWYfKVvNA:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-OCD-Yxe7e-zWiPR3bPS:-OCD2I3j3x-xv79O_Z1p:bpfugyi) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eb0a08459ed0559f38e44e4c0135208a86599c5/crates/starknet_batcher/src/batcher.rs#L84)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can you please add `#[instrument(skip(self), err)]`?
</blockquote></details>

Right, thanks.

**Review by dafnamatsry — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2192)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/starknet_batcher/src/batcher.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-OCD-Yxe7e-zWiPR3bPS:-OCD2c381Nv4zUCaUN8B:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eb0a08459ed0559f38e44e4c0135208a86599c5/crates/starknet_batcher/src/batcher.rs#L84)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Right, thanks.
</blockquote></details>

Done.
___
*[`crates/starknet_batcher/src/batcher.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-OCD-non67oejP82REW8:-OCD2hAABTunMjU0nrvD:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6eb0a08459ed0559f38e44e4c0135208a86599c5/crates/starknet_batcher/src/batcher.rs#L95)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

And then this is unnecessary
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2192#-:-OCDRjCt4sg3aH9m-2fd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Comment by dafnamatsry** [comment]
### Merge activity

* **Nov 21, 6:20 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2192).

**Pull request merged**
