### PR TITLE
feat: use the peer_id to key the hash maps in StreamHandler

### PR DESCRIPTION
**Pull request by guy-starkware**
This uses the now public interface for getting the `OpaquePeerId` as the message metadata (currently stored in `BroadcastedMessageManager`) and using that (and the `stream_id` of the message) to keep separate the different streams. 

The idea is that each peer can choose whatever number they like for the `stream_id`, and by making the internal key (inside the `StreamHandler`) be a tuple of `(peer_id, stream_id)` we can make sure the stream keys are unique and don't collide.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1095)

### CODE REVIEW

**Review by eitanm-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 2 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1095)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 193 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1095#-O8VrfZF9Imd1gsuN3iV:-O8VrfZF9Imd1gsuN3iW:b902tu4) ([raw file](https://github.com/starkware-libs/sequencer/blob/65cf65d8b3e023eb450348b2e09afc4a2a4277d2/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L193)):*
> ```XML
>                 "Received message with id that is smaller than the next message expected! \
>                  peer_id: {:?}, stream_id: {}, message_id: {}, next_message_id: {}",
>                 peer_id.clone(),
> ```

no need to clone here, it is the last usage of peer_id



_Code quote:_
```XML
clone()
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 80 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1095#-O8VsFI29TuvNP1uNkRI:-O8VsFI29TuvNP1uNkRJ:b-pc7kko) ([raw file](https://github.com/starkware-libs/sequencer/blob/65cf65d8b3e023eb450348b2e09afc4a2a4277d2/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L80)):*
> ```XML
>         for i in 0..10 {
>             let message = make_test_message(stream_id, i, i == 9);
>             // tx_input.try_send(message).expect("Send should succeed");
> ```

can be removed



_Code quote:_
```XML
    // tx_input.try_send(message).expect("Send should succeed");
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 125 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1095#-O8VsTq55_IgHys-V62g:-O8VsTq55_IgHys-V62h:b6o3rmw) ([raw file](https://github.com/starkware-libs/sequencer/blob/65cf65d8b3e023eb450348b2e09afc4a2a4277d2/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L125)):*
> ```XML
>         );
>         let range: Vec<u64> = (1..6).collect();
>         let keys: Vec<u64> = stream_handler.stream_data[&(peer_id.clone(), stream_id)]
> ```

no need to clone



_Code quote:_
```XML
.clone()
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 298 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1095#-O8Vsmcy1v4mgI6wJRGZ:-O8Vsmcy1v4mgI6wJRG_:b-2guby3) ([raw file](https://github.com/starkware-libs/sequencer/blob/65cf65d8b3e023eb450348b2e09afc4a2a4277d2/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L298)):*
> ```XML
>         // But the buffer should be empty, as we've successfully drained it all.
>         assert!(
>             stream_handler.stream_data[&(peer_id.clone(), stream_id3)].message_buffer.is_empty()
> ```

same here



_Code quote:_
```XML
.clone()
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1095)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 193 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1095#-O8VrfZF9Imd1gsuN3iV:-O8W4VlL6RlneNVQRcWd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/65cf65d8b3e023eb450348b2e09afc4a2a4277d2/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L193)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

no need to clone here, it is the last usage of peer_id
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 80 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1095#-O8VsFI29TuvNP1uNkRI:-O8W4bsjBJ8x8Rh95iEJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/65cf65d8b3e023eb450348b2e09afc4a2a4277d2/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L80)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

can be removed
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 125 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1095#-O8VsTq55_IgHys-V62g:-O8W4gIwAM3Jgsavr5rh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/65cf65d8b3e023eb450348b2e09afc4a2a4277d2/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L125)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

no need to clone
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler_test.rs` line 298 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/1095#-O8Vsmcy1v4mgI6wJRGZ:-O8W4mY09JjXt_FcMhDw:bs7wumx) ([raw file](https://github.com/starkware-libs/sequencer/blob/65cf65d8b3e023eb450348b2e09afc4a2a4277d2/crates/sequencing/papyrus_consensus/src/stream_handler_test.rs#L298)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

**Review by eitanm-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1095#-:-O8W6Ssj3_7e-V4oFMGI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guy-starkware)

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 2 of 4 files at r15.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1095)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @eitanm-starkware and @guy-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 19 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/1095#-O8lfuiG95uQD1qrQDvp:-O8lfuiG95uQD1qrQDvq:b6hsf4w) ([raw file](https://github.com/starkware-libs/sequencer/blob/057656b21267c6115a64698805883fd5b7326cde/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L19)):*
> ```XML
> type PeerId = OpaquePeerId;
> type StreamId = u64;
> type MessageId = u64;
> ```

Is it used by itself, or always by streamkey?



_Code quote:_
```XML
type MessageId = u64;
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 21 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/1095#-O8lfm8_4_9Aengxr6n3:-O8lfm8_4_9Aengxr6n4:b-pjkis1) ([raw file](https://github.com/starkware-libs/sequencer/blob/057656b21267c6115a64698805883fd5b7326cde/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L21)):*
> ```XML
> type MessageId = u64;
> 
> type StreamKey = (PeerId, StreamId);
> ```

Is there a reason for the extra newline? 



_Suggestion:_
```XML
type MessageId = u64;
type StreamKey = (PeerId, StreamId);
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 27 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/1095#-O8lhCQv4UFEBSxcNIEd:-O8lhCQv4UFEBSxcNIEe:b-60e19u) ([raw file](https://github.com/starkware-libs/sequencer/blob/057656b21267c6115a64698805883fd5b7326cde/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L27)):*
> ```XML
> fn get_metadata_peer_id(metadata: &BroadcastedMessageManager) -> PeerId {
>     metadata.originator_id.clone()
> }
> ```

What is the reason for this change? 



_Code quote:_
```XML
fn get_metadata_peer_id(metadata: &BroadcastedMessageManager) -> PeerId {
    metadata.originator_id.clone()
}
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 31 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/1095#-O8ljmbo5ntJM2B91qb8:-O8ljmbo5ntJM2B91qb9:bqmajbk) ([raw file](https://github.com/starkware-libs/sequencer/blob/057656b21267c6115a64698805883fd5b7326cde/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L31)):*
> ```XML
> #[derive(Debug, Clone)]
> struct StreamData<T: Clone + Into<Vec<u8>> + TryFrom<Vec<u8>, Error = ProtobufConversionError>> {
>     peer_id: PeerId,
> ```

Why do we need 



_Code quote:_
```XML
 peer_id: PeerId,
```
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 37 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/1095#-O8lgaZa-TLOWUcnpQsp:-O8lgaZb5mLMdVvrrsFX:brv6pjy) ([raw file](https://github.com/starkware-libs/sequencer/blob/057656b21267c6115a64698805883fd5b7326cde/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L37)):*
> ```XML
>     // if None, it means we have not yet gotten to it.
>     fin_message_id: Option<MessageId>,
>     max_message_id: MessageId,
> ```

Consider



_Suggestion:_
```XML
 max_message_id_received
```

**Review by guy-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1095)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @dan-starkware and @eitanm-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 19 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/1095#-O8lfuiG95uQD1qrQDvp:-O94ioBUDNGZxSTl7yDj:b-a06fq1) ([raw file](https://github.com/starkware-libs/sequencer/blob/057656b21267c6115a64698805883fd5b7326cde/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L19)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Is it used by itself, or always by streamkey?
</blockquote></details>

StreamId is only used along with PeerId so I removed it. 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 21 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/1095#-O8lfm8_4_9Aengxr6n3:-O94ikws-00BhAkv5Dcs:b-bc5wtt) ([raw file](https://github.com/starkware-libs/sequencer/blob/057656b21267c6115a64698805883fd5b7326cde/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L21)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Is there a reason for the extra newline?
</blockquote></details>

Removed spaces from struct definitions. 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 27 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/1095#-O8lhCQv4UFEBSxcNIEd:-O94iIdtBMreCoQh0RmS:b-mrhh35) ([raw file](https://github.com/starkware-libs/sequencer/blob/057656b21267c6115a64698805883fd5b7326cde/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L27)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

What is the reason for this change?
</blockquote></details>

It used to be a u64, but it is now (after some update from Shahak's team) a struct (something like `OpaquePeerId`. 
___
*[`crates/sequencing/papyrus_consensus/src/stream_handler.rs` line 31 at r17](https://reviewable.io/reviews/starkware-libs/sequencer/1095#-O8ljmbo5ntJM2B91qb8:-O94hqD3AXR-CfzhEj8p:b-v6s1o3) ([raw file](https://github.com/starkware-libs/sequencer/blob/057656b21267c6115a64698805883fd5b7326cde/crates/sequencing/papyrus_consensus/src/stream_handler.rs#L31)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why do we need
</blockquote></details>

Removed.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r17, 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1095)* status: all files reviewed, 3 unresolved discussions (waiting on @guy-starkware)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1095)* status: all files reviewed, 1 unresolved discussion (waiting on @guy-starkware)

**Pull request merged**
