### PR TITLE
refactor(gateway): delete `CairoLangSierraToCasmCompiler`

### PR DESCRIPTION
**Pull request by elintul**
No longer in use, we compile using CLI.
This is a leftover of an earlier design (depending on the compiler in `Cargo.toml`, which ended up being less favorable.

### CODE REVIEW

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2228)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/starknet_sierra_compile/src/compile_test.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2228#-OCERd0Y17jRPpVnvs_b:-OCERd0Y17jRPpVnvs_c:bam5ei6) ([raw file](https://github.com/starkware-libs/sequencer/blob/2ee1d497f3349605409d53dbbbfc5125d61fbfa2/crates/starknet_sierra_compile/src/compile_test.rs#L37)):*
> ```XML
> }
> 
> // TODO: use the other compiler as well.
> ```

Who added this todo? 
Should it be removed? (non-blocking).



_Code quote:_
```XML
// TODO: use the other compiler as well.
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2228)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/starknet_sierra_compile/src/compile_test.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2228#-OCERV7V49J6xZAOaulD:-OCESGij7O_lS9bffgSL:b-k4tq5e) ([raw file](https://github.com/starkware-libs/sequencer/blob/2ee1d497f3349605409d53dbbbfc5125d61fbfa2/crates/starknet_sierra_compile/src/compile_test.rs#L39)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This will fail.
</blockquote></details>

Thanks, done (ran only GW tests locally :smiling_face_with_tear:).

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2228#-:-OCSEKvc-37VvyNlvXHq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by ArniStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2228)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
