### PR TITLE
chore(network): implement logic for network channels

### PR DESCRIPTION
**Pull request by eitanm-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/244)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/244)* status: all files reviewed, 15 unresolved discussions (waiting on @eitanm-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3ByuY29hueqMhizKRe):*
I don't think you should fix this, but this is the classic example of feat
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 639 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3Bz4DS3wKy1efWXOAy:-O3Bz4DS3wKy1efWXOAz:b-iwcscc) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L639)):*
> ```XML
> type ReportReceiver = oneshot::Receiver<()>;
> 
> // TODO: make fields private
> ```

The struct itself can be private as well
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 640 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3Bzf_qBoogbDE-ohwJ:-O3Bzf_qBoogbDE-ohwK:b-304g62) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L640)):*
> ```XML
> 
> // TODO: make fields private
> pub struct SqmrClientPayload<Query, Response: TryFrom<Bytes>> {
> ```

Put this below ClientResponseManager
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 641 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C-uxY8pSgHJsdTsZY:-O3C-uxY8pSgHJsdTsZZ:beka5p0) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L641)):*
> ```XML
> // TODO: make fields private
> pub struct SqmrClientPayload<Query, Response: TryFrom<Bytes>> {
>     pub query: Query,
> ```

If we already make this struct private, let's erase it and use SqmrClientPayloadForNetwork instead
Then the channel conversion will move to the functions of the structs you defined here
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 645 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3BzBcu-sh6ipn4LZzi:-O3BzBcu-sh6ipn4LZzj:b-miaotn) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L645)):*
> ```XML
>     pub responses_sender: ResponsesSender<Response>,
> }
> pub struct ClientResponseManager<Response: TryFrom<Bytes>> {
> ```

Newline between structs
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 645 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C1ds6DBrcbRlMeZTX:-O3C1ds6DBrcbRlMeZTY:b8ewhqg) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L645)):*
> ```XML
>     pub responses_sender: ResponsesSender<Response>,
> }
> pub struct ClientResponseManager<Response: TryFrom<Bytes>> {
> ```

I tend to think ClientQueryManager is better, since it manages a single query (its responses), but I'm ok with either
Anyway, if you stick with Response, change it to Responses
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 655 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3BzGzp18vAijIxF2cz:-O3BzGzp18vAijIxF2d-:b-i0rua5) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L655)):*
> ```XML
>     }
> 
>     pub async fn next_response(
> ```

Now that I think of this more, I think you should impl Stream on ClientResponseManager so that we can use all kind of StreamExt functionality on this
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 662 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3BzUw07ZReqTnLGt7n:-O3BzUw07ZReqTnLGt7o:b-4lhbam) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L662)):*
> ```XML
> }
> 
> pub struct SqmrClientSender<Query, Response: TryFrom<Bytes>> {
> ```

Put this above ClientResponseManager
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 670 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C33XsAKJuEHfzeYPF:-O3C-7pi8Q3F7xk2OcHf:b-sfn4e8) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L670)):*
> ```XML
>     <Response as TryFrom<Bytes>>::Error: Send + 'static,
> {
>     pub fn new(channel: GenericSender<SqmrClientPayload<Query, Response>>) -> Self {
> ```

I think we should distinguish this function between the feature testing and not. Under the testing feature it should be public and not under it it should be pub(crate). There are two ways to do this:
1. add `#[cfg(feature = "testing")]` above this and copy this function with `#[cfg(not(feature = "testing"))]` and there define it as pub crate
2. Create a new_for_test function that calls this one and is enabled only under the testing feature
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 673 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C-G3R5abVXSaM64UW:-O3C-G3R5abVXSaM64UX:b-17desu) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L673)):*
> ```XML
>         Self { channel }
>     }
>     pub async fn send(
> ```

Rename this to send_new_query
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 676 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C-LYO3lWmewueJkF7:-O3C-LYP15nCjgR6OBkF:bvxrdl7) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L676)):*
> ```XML
>         &mut self,
>         query: Query,
>         response_buffer_size: usize,
> ```

IMO this should be a field of this struct
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C0wqJAtAObJ7hYyKQ:-O3C0dPl8iip3KNKVpAD:b-gr7fml) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/test.rs#L233)):*
> ```XML
>     tokio::select! {
>         _ = network_manager.run() => panic!("network manager ended"),
>         _ = poll_fn(|cx| event_listner.poll_unpin(cx)).then(|_| async move {
> ```

Let's use this opportunity to clean the code here:
1. rename event_listner to first_event_listener
2. don't use poll_fn. Just put `first_event_listener.then(...`
___
*[`crates/papyrus_p2p_sync/src/client/mod.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C2GdY-kblpt54pRVz:-O3C2GdY-kblpt54pRW-:bhaa3xb) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_p2p_sync/src/client/mod.rs#L12)):*
> ```XML
> 
> use std::collections::BTreeMap;
> use std::time::Duration;
> ```

Remove the use of the word payload/Payload across the entire p2p sync crate
___
*[`crates/papyrus_p2p_sync/src/client/mod.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C2BUkC3sruuqbrUxW:-O3C2BUkC3sruuqbrUxX:b-3st4qh) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_p2p_sync/src/client/mod.rs#L159)):*
> ```XML
> }
> 
> // TODO(Eitan): Use SqmrSubscriberChannels once there is a utility function for testing
> ```

I think you can remove this TODO
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C2miH7n6MAQikcyQ0:-O3C2miH7n6MAQikcyQ1:bb2dp3m) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L88)):*
> ```XML
>                 );
>                 // TODO(shahak): Use the report callback.
>                 //TODO(Eitan): abstract report functionality to the channel struct
> ```

I think you can remove your TODO

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/244)* status: all files reviewed, 14 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 639 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3Bz4DS3wKy1efWXOAy:-O3C6jkmB7iBApTnalHO:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L639)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

The struct itself can be private as well
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 640 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3Bzf_qBoogbDE-ohwJ:-O3C6rG00FRu8Vti1v9n:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L640)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Put this below ClientResponseManager
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 641 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C-uxY8pSgHJsdTsZY:-O3C8XUl4iA8tjEax266:bmkzhxm) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L641)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

If we already make this struct private, let's erase it and use SqmrClientPayloadForNetwork instead
Then the channel conversion will move to the functions of the structs you defined here
</blockquote></details>

Next PR
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 645 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3BzBcu-sh6ipn4LZzi:-O3C712a9ulSs-_qYmUe:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L645)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Newline between structs
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 645 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C1ds6DBrcbRlMeZTX:-O3C7757Ap1_2X5eYg1l:budaw47) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L645)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I tend to think ClientQueryManager is better, since it manages a single query (its responses), but I'm ok with either
Anyway, if you stick with Response, change it to Responses
</blockquote></details>

I see what you're saying but I think I'll keep it as Responses. 
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 655 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3BzGzp18vAijIxF2cz:-O3CbRqG-2Ui4Xw4EAly:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L655)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Now that I think of this more, I think you should impl Stream on ClientResponseManager so that we can use all kind of StreamExt functionality on this
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 662 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3BzUw07ZReqTnLGt7n:-O3C7Rj8Er37JgquMtfn:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L662)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Put this above ClientResponseManager
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 670 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C33XsAKJuEHfzeYPF:-O3DWAyh827Qm01nuvWO:b7fgmhw) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L670)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think we should distinguish this function between the feature testing and not. Under the testing feature it should be public and not under it it should be pub(crate). There are two ways to do this:
1. add `#[cfg(feature = "testing")]` above this and copy this function with `#[cfg(not(feature = "testing"))]` and there define it as pub crate
2. Create a new_for_test function that calls this one and is enabled only under the testing feature
</blockquote></details>

its only needed in tests and in the same module so I moved it to testing and changed the module usage
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 673 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C-G3R5abVXSaM64UW:-O3C7VclEG5qpEGXFIXi:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L673)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename this to send_new_query
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 676 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C-LYO3lWmewueJkF7:-O3C5_hw99tKtXdcuTBj:bwvgzc1) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L676)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

IMO this should be a field of this struct
</blockquote></details>

thought of it too, but wasn't sure if it would be consistent for each query. if it is, then we could supply it in `register_sqmr_protocol_client`
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C0wqJAtAObJ7hYyKQ:-O3CcP0D70dYn_6WAFUP:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/test.rs#L233)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Let's use this opportunity to clean the code here:
1. rename event_listner to first_event_listener
2. don't use poll_fn. Just put `first_event_listener.then(...`
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/mod.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C2GdY-kblpt54pRVz:-O3DTjiI7mYgQDLa4ZGH:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_p2p_sync/src/client/mod.rs#L12)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove the use of the word payload/Payload across the entire p2p sync crate
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/mod.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C2BUkC3sruuqbrUxW:-O3CedrFDchoVSNIQGsW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_p2p_sync/src/client/mod.rs#L159)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think you can remove this TODO
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/stream_builder.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C2miH7n6MAQikcyQ0:-O3CeShxD8xNvDn3Y-zL:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_p2p_sync/src/client/stream_builder.rs#L88)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think you can remove your TODO
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/244)* status: all files reviewed, 7 unresolved discussions (waiting on @eitanm-starkware)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 641 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C-uxY8pSgHJsdTsZY:-O3DzUMq1ePuai-IXkKJ:bapp488) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L641)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Next PR
</blockquote></details>

Added to Monday https://starkware.monday.com/boards/7076051078/pulses/7144047463
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 676 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C-LYO3lWmewueJkF7:-O3Dysxv45CZuKcharTW:b-m5q1tk) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L676)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

thought of it too, but wasn't sure if it would be consistent for each query. if it is, then we could supply it in `register_sqmr_protocol_client`
</blockquote></details>

In general yes. I think for now it can be the same buffer size we already have there. You can add a TODO to separate the buffer size to query_buffer_size and responses_buffer_size
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 676 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3DzxH773w71Kk2lNSQ:-O3DzxH773w71Kk2lNSR:b-9c24uo) ([raw file](https://github.com/starkware-libs/sequencer/blob/c6e485a6ee26a96d4ff8eddf77d5bd19c2d4649c/crates/papyrus_network/src/network_manager/mod.rs#L676)):*
> ```XML
> impl<Response: TryFrom<Bytes>> ClientResponsesManager<Response> {
>     pub async fn report_peer(self) {
>         let _ = self.report_sender.send(());
> ```

Add a log if report_sender failed in error level
___
*[`crates/papyrus_p2p_sync/src/client/mod.rs` line 159 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3E-UZ63saj02Ng7qOg:-O3E-UZ63saj02Ng7qOh:b-29m9sg) ([raw file](https://github.com/starkware-libs/sequencer/blob/c6e485a6ee26a96d4ff8eddf77d5bd19c2d4649c/crates/papyrus_p2p_sync/src/client/mod.rs#L159)):*
> ```XML
> }
> 
> type HeaderSender = SqmrClientSender<HeaderQuery, DataOrFin<SignedBlockHeader>>;
> ```

These should be *SqmrSender
___
*[`crates/papyrus_p2p_sync/src/client/mod.rs` line 178 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3E-ZTm4DyWwNSeQAHz:-O3E-ZTm4DyWwNSeQAI-:biftf6v) ([raw file](https://github.com/starkware-libs/sequencer/blob/c6e485a6ee26a96d4ff8eddf77d5bd19c2d4649c/crates/papyrus_p2p_sync/src/client/mod.rs#L178)):*
> ```XML
>     ) -> Self {
>         Self {
>             header_sender: header_payload_sender,
> ```

payload is still here
___
*[`crates/papyrus_p2p_sync/src/client/test_utils.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3E0VG58KLLseHH_52u:-O3E0VG58KLLseHH_52v:bgl6tyi) ([raw file](https://github.com/starkware-libs/sequencer/blob/c6e485a6ee26a96d4ff8eddf77d5bd19c2d4649c/crates/papyrus_p2p_sync/src/client/test_utils.rs#L47)):*
> ```XML
>     pub p2p_sync: P2PSyncClient,
>     pub storage_reader: StorageReader,
>     pub header_payload_receiver:
> ```

payload is still here. and in state_diff_test.rs
___
*[`crates/papyrus_p2p_sync/src/client/test_utils.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3E0__uBl6SjdRGLpO1:-O3E0__uBl6SjdRGLpO2:biftf6v) ([raw file](https://github.com/starkware-libs/sequencer/blob/c6e485a6ee26a96d4ff8eddf77d5bd19c2d4649c/crates/papyrus_p2p_sync/src/client/test_utils.rs#L60)):*
> ```XML
>     let buffer_size = p2p_sync_config.buffer_size;
>     let ((storage_reader, storage_writer), _temp_dir) = get_test_storage();
>     let (header_payload_sender, header_payload_receiver) =
> ```

payload is still here

**Review by eitanm-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/244)* status: all files reviewed, 7 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 676 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3C-LYO3lWmewueJkF7:-O3RZPVI6CTa_uzKGPQ7:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/44a179c40a4747f2767ddd200bfd783af70e8c56/crates/papyrus_network/src/network_manager/mod.rs#L676)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

In general yes. I think for now it can be the same buffer size we already have there. You can add a TODO to separate the buffer size to query_buffer_size and responses_buffer_size
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 676 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3DzxH773w71Kk2lNSQ:-O3RYrPH0V0APPuJrArG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c6e485a6ee26a96d4ff8eddf77d5bd19c2d4649c/crates/papyrus_network/src/network_manager/mod.rs#L676)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add a log if report_sender failed in error level
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/mod.rs` line 159 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3E-UZ63saj02Ng7qOg:-O3RWfhkCcDFWPDf8vL6:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c6e485a6ee26a96d4ff8eddf77d5bd19c2d4649c/crates/papyrus_p2p_sync/src/client/mod.rs#L159)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

These should be *SqmrSender
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/mod.rs` line 178 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3E-ZTm4DyWwNSeQAHz:-O3RVNbQ-YE516pGiHJh:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c6e485a6ee26a96d4ff8eddf77d5bd19c2d4649c/crates/papyrus_p2p_sync/src/client/mod.rs#L178)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

payload is still here
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/test_utils.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3E0VG58KLLseHH_52u:-O3RVaKU3OYaa3kXucIk:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c6e485a6ee26a96d4ff8eddf77d5bd19c2d4649c/crates/papyrus_p2p_sync/src/client/test_utils.rs#L47)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

payload is still here. and in state_diff_test.rs
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/client/test_utils.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/244#-O3E0__uBl6SjdRGLpO1:-O3RVb7p9t3zQySe4eZU:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/c6e485a6ee26a96d4ff8eddf77d5bd19c2d4649c/crates/papyrus_p2p_sync/src/client/test_utils.rs#L60)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

payload is still here
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/244#-:-O3RuCoC372cjYh0jyb8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Review by ShahakShama — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/244)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/244#-:-O3aSh5c90b4t532XXxn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @eitanm-starkware)

**Pull request merged**
