### PR TITLE
feat: add support for remote client

### PR DESCRIPTION
**Pull request by nadin-Starkware**
commit-id:5e8aae1c

---

**Stack**:
- #1961 ⬅
- #1960
- #1959
- #1958
- #1957

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by Itay-Tsabary-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1961)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

___
*[`crates/sequencer_node/src/clients.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1961#-OBV7DiY3Pwfy-oWWA0Z:-OBV7DiY3Pwfy-oWWA0_:b6wh3or) ([raw file](https://github.com/starkware-libs/sequencer/blob/6d214da9e180547bf10c4689324944145c3d60ba/crates/sequencer_node/src/clients.rs#L62)):*
> ```XML
> /// * $channel_expr - Sender side for the client.
> /// * $client_type - The client type to create, e.g., LocalBatcherClient. The client type should
> ///   have a function $client_type::new(tx : $channel_expr).
> ```

Please update the doc.



_Code quote:_
```XML
/// A macro for creating a component client, determined by the component's execution mode. Returns a
/// local client if the component is run locally, otherwise None.
///
/// # Arguments
///
/// * $execution_mode - A reference to the component's execution mode, i.e., type
///   &ComponentExecutionMode.
/// * $channel_expr - Sender side for the client.
/// * $client_type - The client type to create, e.g., LocalBatcherClient. The client type should
///   have a function $client_type::new(tx : $channel_expr).
```

**Review by nadin-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1961)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/sequencer_node/src/clients.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1961#-OBV7DiY3Pwfy-oWWA0Z:-OBVGTAo9_eQVHR8e4mG:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/da16c06c09fbe8e6757e8abae7a76ac1de8ee6ba/crates/sequencer_node/src/clients.rs#L62)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please update the doc.
</blockquote></details>

Done.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1961#-:-OBW4Ohu1p2OzgQC4j9Z:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nadin-Starkware)

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1961)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadin-Starkware)

**Pull request merged**
