### PR TITLE
feat(blockifier): add native entry point execution

### PR DESCRIPTION
**Pull request by varex83**
This PR is follow-up after https://github.com/starkware-libs/sequencer/pull/549

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/551)

### CODE REVIEW

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 4 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/551)* status: 4 of 23 files reviewed, all discussions resolved

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 16 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/551)* status: 20 of 23 files reviewed, all discussions resolved

**Review by meship-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/551)* status: 20 of 23 files reviewed, 1 unresolved discussion (waiting on @varex83)

___
*[`crates/blockifier/src/execution/native/utils.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/551#-O5HvHgF9ef4_sc5aZh6:-O5HvHgF9ef4_sc5aZh7:bnt2wr) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa1af67543538d1b6d705f8bf5eadd59218687e6/crates/blockifier/src/execution/native/utils.rs#L87)):*
> ```XML
>     storage_read_values: Vec<Felt>,
>     accessed_storage_keys: HashSet<StorageKey, RandomState>,
> ) -> Result<CallInfo, EntryPointExecutionError> {
> ```

Is there a reason for this function to return a Result? It looks like it will always return call info, wouldn't it be better if this function will return CallInfo and the function that calls it will wrap it with Ok?

**Review by varex83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/551)* status: 20 of 23 files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

___
*[`crates/blockifier/src/execution/native/utils.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/551#-O5HvHgF9ef4_sc5aZh6:-O5IF3x92ANV_fS5Lj2v:b-vkhl5k) ([raw file](https://github.com/starkware-libs/sequencer/blob/fa1af67543538d1b6d705f8bf5eadd59218687e6/crates/blockifier/src/execution/native/utils.rs#L87)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Is there a reason for this function to return a Result? It looks like it will always return call info, wouldn't it be better if this function will return CallInfo and the function that calls it will wrap it with Ok?
</blockquote></details>

Yeah, that sounds reasonable, it should be done.

**Review by meship-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r3, 1 of 7 files at r5, 1 of 4 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/551)* status: 21 of 23 files reviewed, all discussions resolved (waiting on @varex83)

**Comment by rodrigo-pino** [comment]
Solved in #1158

**Pull request closed without merging**
