### PR TITLE
chore(starknet_api, blockifier): make 0.13.3 an intermediate version equivalent to 0.13.2.1

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
…equivalent to 0.13.2.1

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1802)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @yoavGrs and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1802#-OArx0bd9MdbcJuYW16H:-OArx0bd9MdbcJuYW16I:b-2y5of8) (no related file):*
[py side](https://reviewable.io/reviews/starkware-industries/starkware/36156)

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1802)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @yoavGrs and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_0_13_3.json` line 0 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1802#-OArx8dGEHMlYaJO_tV7:-OArx8dGEHMlYaJO_tV8:blhbpeo) ([raw file](https://github.com/starkware-libs/sequencer/blob/d9a1a52d9e6351e5983eb87bdebc0bf1d8b3d01a/crates/blockifier/resources/versioned_constants_0_13_3.json#L0)):*
no changes here: just pasted the contents of VC 0.13.2.1 in this file.
the old 0.13.3 VC file is now called `versioned_constants_0_13_4.json`

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1802#-:-OAs8bf--YoqRgmW9jqS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1802)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1802#-OArx0bd9MdbcJuYW16H:-OAv5WnS8tDujwgbx2gv:b-kxrypq) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[py side](https://reviewable.io/reviews/starkware-industries/starkware/36156)
</blockquote></details>

Can you bump dev as well?

___

**Review by yoavGrs — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1802)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1802#-OAvNEWD6ddSy9uiWvnF:-OAvNEWD6ddSy9uiWvnG:b-8k0rka) ([raw file](https://github.com/starkware-libs/sequencer/blob/558299724189428103e0ed0fe69c7d53389dab9a/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L50)):*
> ```XML
> #[derive(Clone, Debug, PartialEq, Eq, PartialOrd)]
> pub enum BlockHashVersion {
>     VO_13_2,
> ```

This version remains, no?
I think that you should change only 0.13.3 -> 0.13.4.



_Code quote:_
```XML
VO_13_2
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1802)* status: all files reviewed, 2 unresolved discussions (waiting on @yoavGrs and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1802#-OArx0bd9MdbcJuYW16H:-OAvUU9I4DCZlyoVOZd5:bgdj5qa) (no related file):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you bump dev as well?
</blockquote></details>

WDYM...? the link *is* for dev

___
___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1802#-OAvNEWD6ddSy9uiWvnF:-OAvVTof29TCz9QgotDg:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/558299724189428103e0ed0fe69c7d53389dab9a/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L50)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

This version remains, no?
I think that you should change only 0.13.3 -> 0.13.4.
</blockquote></details>

Done.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1802)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1802#-OArx0bd9MdbcJuYW16H:-OAvVj5G66IIDmJnye8Y:berv0pf) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYM...? the link *is* for dev
</blockquote></details>

I.e., bump SN version to 0.13.4 on dev

___

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1802)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1802#-OAvNEWD6ddSy9uiWvnF:-OAvVo6d1KZYIslqW-vT:bdutc06) ([raw file](https://github.com/starkware-libs/sequencer/blob/558299724189428103e0ed0fe69c7d53389dab9a/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L50)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No implications on py side at all?

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1802)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

**Review by yoavGrs — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1802)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/starknet_api/src/block_hash/block_hash_calculator.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1802#-OAvNEWD6ddSy9uiWvnF:-OAvX9QhBB4pYX1gCYsh:bz7ygm8) ([raw file](https://github.com/starkware-libs/sequencer/blob/558299724189428103e0ed0fe69c7d53389dab9a/crates/starknet_api/src/block_hash/block_hash_calculator.rs#L50)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

No implications on py side at all?
</blockquote></details>

Not that I know of.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1802)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1802#-OArx0bd9MdbcJuYW16H:-OAvuOG04yQGQtoLHjNn:b-cenv5t) (no related file):*
yes, I was waiting to test my test:
```
def test_starknet_version_for_vc():
        """
        Tests that the Starknet version for versioned constants matches the currently set starknet
        version.
        """
        blockifier_starknet_version = native_blockifier.starknet_version()
        assert isinstance(blockifier_starknet_version, str)
>       assert blockifier_starknet_version == STARKNET_VERSION
E       AssertionError: assert '0.13.4' == '0.13.3'
E         - 0.13.3
E         ?      ^
E         + 0.13.4
E         ?      ^
```
py side will not pass until the version is bumped :)

___

**Pull request merged**
