### PR TITLE
feat(cairo_native): add a struct containing all global contract caches

### PR DESCRIPTION
**Pull request by avi-starkware**

### CODE REVIEW

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2186)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/state/global_cache.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2186#-OC7KN_r3lR9Db6iH4us:-OC7KN_r3lR9Db6iH4ut:b6gb9bp) ([raw file](https://github.com/starkware-libs/sequencer/blob/fc634d80b380ed284ec03c076861e24281ff6ca8/crates/blockifier/src/state/global_cache.rs#L50)):*
> ```XML
> pub struct GlobalContractCacheManager {
>     pub casm_contract_class_cache: GlobalContractCache<RunnableContractClass>,
>     pub native_contract_executor_cache: GlobalContractCache<Option<AotContractExecutor>>,
> ```

Non blocking for this PR: I think a specific enum would be more readable for this case (that's what you said in one of my concurrency PRs, remember?)



_Code quote:_
```XML
Option<AotContractExecutor>
```
___
*[`crates/blockifier/src/state/global_cache.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2186#-OC7K1OR9q3bskY2Dyz_:-OC7K1OSArgZvUgHgjEh:b-woeehj) ([raw file](https://github.com/starkware-libs/sequencer/blob/fc634d80b380ed284ec03c076861e24281ff6ca8/crates/blockifier/src/state/global_cache.rs#L51)):*
> ```XML
>     pub casm_contract_class_cache: GlobalContractCache<RunnableContractClass>,
>     pub native_contract_executor_cache: GlobalContractCache<Option<AotContractExecutor>>,
>     pub sierra_contract_class_cache: GlobalContractCache<Arc<SierraContractClass>>,
> ```

Clear from the struct name



_Suggestion:_
```XML
pub struct GlobalContractCacheManager {
    pub casm_cache: GlobalContractCache<RunnableContractClass>,
    pub native_cache: GlobalContractCache<Option<AotContractExecutor>>,
    pub sierra_cache: GlobalContractCache<Arc<SierraContractClass>>,
```
___
*[`crates/blockifier/src/state/global_cache.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2186#-OC7KBd0-ga4vqZ1aVWn:-OC7KBd0-ga4vqZ1aVWo:blj2h7o) ([raw file](https://github.com/starkware-libs/sequencer/blob/fc634d80b380ed284ec03c076861e24281ff6ca8/crates/blockifier/src/state/global_cache.rs#L56)):*
> ```XML
> #[cfg(feature = "cairo_native")]
> impl GlobalContractCacheManager {
>     pub fn get_casm_contract_class(&self, class_hash: &ClassHash) -> Option<RunnableContractClass> {
> ```

Same re func names



_Suggestion:_
```XML
get_casm
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2186)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/state/global_cache.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2186#-OC7jb4554p7rUFiboQR:-OC7jb4554p7rUFiboQS:b-7zi8ni) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a057393d4723fe4c40d449a28fd408f18efd81a/crates/blockifier/src/state/global_cache.rs#L25)):*
> ```XML
> pub enum CachedCairoNative {
>     Compiled(AotContractExecutor),
>     NoCompilation,
> ```

WDYT?



_Suggestion:_
```XML
    CompilationError
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2186#-:-OC7rSyPBv1QQGgpS9xx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/state/global_cache.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2186#-OC7jb4554p7rUFiboQR:-OC7rzZKCCNNjGbR1E7P:b-iaaav8) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a057393d4723fe4c40d449a28fd408f18efd81a/crates/blockifier/src/state/global_cache.rs#L25)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

I made it compilation failed because it doesn't have to be an error that failed it. WDYT?

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2186)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/state/global_cache.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2186#-OC7jb4554p7rUFiboQR:-OC7u5M03GaQpeixgSqg:bb6ywmx) ([raw file](https://github.com/starkware-libs/sequencer/blob/8a057393d4723fe4c40d449a28fd408f18efd81a/crates/blockifier/src/state/global_cache.rs#L25)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I made it compilation failed because it doesn't have to be an error that failed it. WDYT?
</blockquote></details>

LGTM

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/state/global_cache.rs` line 13 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2186#-OC80wlP4ecR0b9AYnn-:-OC80wlP4ecR0b9AYnn0:btstxap) ([raw file](https://github.com/starkware-libs/sequencer/blob/867ef753556fe42de9ac5e6c8743f943dc6f5635/crates/blockifier/src/state/global_cache.rs#L13)):*
> ```XML
> use crate::execution::contract_class::RunnableContractClass;
> 
> // Note: `ContractClassLRUCache` key-value types must align with `ContractClassMapping`.
> ```

@Yoni-Starkware 
Why must it align?
What should we change it to?



_Code quote:_
```XML
// Note: `ContractClassLRUCache` key-value types must align with `ContractClassMapping`.
```

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2186)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/state/global_cache.rs` line 13 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2186#-OC80wlP4ecR0b9AYnn-:-OC8DdfkAXjbJoNdK-Qw:b4i64je) ([raw file](https://github.com/starkware-libs/sequencer/blob/867ef753556fe42de9ac5e6c8743f943dc6f5635/crates/blockifier/src/state/global_cache.rs#L13)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

@Yoni-Starkware 
Why must it align?
What should we change it to?
</blockquote></details>

I don't know what this comment is. It's not true, delete it.

**Comment by avi-starkware** [comment]
*[`crates/blockifier/src/state/global_cache.rs` line 13 at r5](https://reviewable.io/reviews/starkware-libs/sequencer/2186#-OC80wlP4ecR0b9AYnn-:-OC8O7uD5KbIAYZ6RgZe:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/867ef753556fe42de9ac5e6c8743f943dc6f5635/crates/blockifier/src/state/global_cache.rs#L13)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I don't know what this comment is. It's not true, delete it.
</blockquote></details>

Done.

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2186#-:-OC8W_oM2Upgy08upn2D:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Pull request merged**
