### PR TITLE
test(tests-integration): add setup and state reader spawn to e2e integration test

### PR DESCRIPTION
**Pull request by Itay-Tsabary-Starkware**
**Stack**:
- #1895
- #1894
- #1893
- #1892 ⬅
- #1891

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by ArniStarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1892)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/tests-integration/tests/end_to_end_integration_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1892#-OBKF2os4MEIx76P__RG:-OBKF2os4MEIx76P__RH:booins4) ([raw file](https://github.com/starkware-libs/sequencer/blob/a696cf1821c38b5b33d413ca6a88a8ed93295431/crates/tests-integration/tests/end_to_end_integration_test.rs#L41)):*
> ```XML
>     // TODO(Tsabary): pass path instead of temp dir.
> 
>     let (_node_config_path, _) = dump_config_file_changes(&config, required_params, &temp_dir);
> ```

Can this be more similar to how we do it in the [end_to_end_flow_test](https://github.com/starkware-libs/sequencer/blob/b7f8ed7bfd7f7c3ce3919bc64eba686e9388fa1e/crates/tests-integration/tests/end_to_end_test.rs#L28) where there is a [IntegrationTestSetup](https://github.com/starkware-libs/sequencer/blob/01567c30db5ffd4acdf21de7eed235ab9ace3376/crates/tests-integration/src/integration_test_setup.rs#L20).

Can we use the same object?



_Suggestion:_
```XML
    running_system = MyIntegrationTestSetup::new();
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1892)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/tests-integration/tests/end_to_end_integration_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1892#-OBKF2os4MEIx76P__RG:-OBKMKHm8Z2PoJg1VsOJ:bh4bgfj) ([raw file](https://github.com/starkware-libs/sequencer/blob/a696cf1821c38b5b33d413ca6a88a8ed93295431/crates/tests-integration/tests/end_to_end_integration_test.rs#L41)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Can this be more similar to how we do it in the [end_to_end_flow_test](https://github.com/starkware-libs/sequencer/blob/b7f8ed7bfd7f7c3ce3919bc64eba686e9388fa1e/crates/tests-integration/tests/end_to_end_test.rs#L28) where there is a [IntegrationTestSetup](https://github.com/starkware-libs/sequencer/blob/01567c30db5ffd4acdf21de7eed235ab9ace3376/crates/tests-integration/src/integration_test_setup.rs#L20).

Can we use the same object?
</blockquote></details>

Not really; I'll write here succinctly and otherwise we can discuss.

This is the struc:

```
pub struct IntegrationTestSetup {
    pub task_executor: TokioExecutor,

    // Client for adding transactions to the sequencer node.
    pub add_tx_http_client: HttpTestClient,

    // Handlers for the storage files, maintained so the files are not deleted.
    pub batcher_storage_file_handle: TempDir,
    pub rpc_storage_file_handle: TempDir,

    // TODO(Arni): Remove batcher client once the consensus manager is integrated into the test.
    pub batcher_client: SharedBatcherClient,

    // Handle of the sequencer node.
    pub sequencer_node_handle: JoinHandle<Result<(), anyhow::Error>>,
}
```

`task_executor` is a (redundant) indirection for spawning the node from the current tokio runtime.
`add_tx_http_client` is reproduced 
`?_storage_file_handle` are reproduced
`batcher_client` should not be available, you are not supposed to have access to internal node channels in integration test
`sequencer_node_handle` is only later created, after the node is spawned, i.e., after the storage handlers and the config are created

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1892#-:-OBKWujQ85TLUofVuLWs:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/tests-integration/tests/end_to_end_integration_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1892#-OBKF2os4MEIx76P__RG:-OBKWpe61bu0SVNu9gGv:b570za2) ([raw file](https://github.com/starkware-libs/sequencer/blob/a696cf1821c38b5b33d413ca6a88a8ed93295431/crates/tests-integration/tests/end_to_end_integration_test.rs#L41)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Not really; I'll write here succinctly and otherwise we can discuss.

This is the struc:

```
pub struct IntegrationTestSetup {
    pub task_executor: TokioExecutor,

    // Client for adding transactions to the sequencer node.
    pub add_tx_http_client: HttpTestClient,

    // Handlers for the storage files, maintained so the files are not deleted.
    pub batcher_storage_file_handle: TempDir,
    pub rpc_storage_file_handle: TempDir,

    // TODO(Arni): Remove batcher client once the consensus manager is integrated into the test.
    pub batcher_client: SharedBatcherClient,

    // Handle of the sequencer node.
    pub sequencer_node_handle: JoinHandle<Result<(), anyhow::Error>>,
}
```

`task_executor` is a (redundant) indirection for spawning the node from the current tokio runtime.
`add_tx_http_client` is reproduced 
`?_storage_file_handle` are reproduced
`batcher_client` should not be available, you are not supposed to have access to internal node channels in integration test
`sequencer_node_handle` is only later created, after the node is spawned, i.e., after the storage handlers and the config are created
</blockquote></details>

Discussed F2f.

**Comment by Itay-Tsabary-Starkware** [comment]
✓ Commit merged in pull request [#1895](https://github.com/starkware-libs/sequencer/pull/1895)

**Pull request closed without merging**
