### PR TITLE
feat(ci): make rust version in ci configurable

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)

### CODE REVIEW

**Review by nimrod-starkware — COMMENTED** [review]
I couldn't find an easy way to set this variable per CI run (i.e for all workflows)..
If this is the right way to do that, we can add it to the other workflows (committer ci for example)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294#-:-O3R_VwH9und2EIlJ_Ji:b-jkqold)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`.github/workflows/main.yml` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3R_HLp4Wf-BqHDJkeB:-O3R_HLqEI-1jYS2PT2u:bns1asw) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ba8c0805ace546cd0833bb80f0f15b8f0969b21/.github/workflows/main.yml#L58)):*
> ```YAML
>         with:
>           components: rustfmt
>           toolchain: nightly-2024-04-29
> ```

@dorimedini-starkware, do you know why it is fixed to that version? Is that on purpose?



_Code quote:_
```YAML
nightly-2024-04-29
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @dan-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`.github/workflows/main.yml` line 18 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3Wfi41BKdoekXzOhud:-O3X-jiw1zwtEdFSlmXj:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ba8c0805ace546cd0833bb80f0f15b8f0969b21/.github/workflows/main.yml#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

newline
</blockquote></details>

Done.
___
*[`.github/workflows/main.yml` line 24 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3WfkNQAHfJ0pLXDUXi:-O3X-k7O9rY8oCjnet8K:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ba8c0805ace546cd0833bb80f0f15b8f0969b21/.github/workflows/main.yml#L24)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

env vars in all caps by convension
</blockquote></details>

Done.

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @dan-starkware, @dorimedini-starkware, and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3WiHNl7pCm4GloPnCK:-O3X9IsH5JdoUfz4jdi7:b-896fix) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please rebase over main-v0.13.2 (this is a CI fix)
</blockquote></details>

Done.

___

**Comment by dan-starkware** [comment]
*[`.github/workflows/main.yml` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3R_HLp4Wf-BqHDJkeB:-O3ae6RW5x5JAAXd3Y6R:b18davt) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ba8c0805ace546cd0833bb80f0f15b8f0969b21/.github/workflows/main.yml#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no. @dan-starkware any idea? not sure this is from papyrus CI, just from your experience maybe you know
</blockquote></details>

We didn't want it to break between changes. AFAIR we agreed on default to latest with an easy way to change globally if needed

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`.github/workflows/main.yml` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3R_HLp4Wf-BqHDJkeB:-O3asZ0AAjrCQ7N0G1IJ:b-njbptr) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ba8c0805ace546cd0833bb80f0f15b8f0969b21/.github/workflows/main.yml#L58)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

We didn't want it to break between changes. AFAIR we agreed on default to latest with an easy way to change globally if needed
</blockquote></details>

@nimrod-starkware try changing this to stable and see if CIs pass? this may cause many format issues; but if it works then I think you can and should replace the toolchain here to the one in your `rust_version.txt`

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: all files reviewed, 4 unresolved discussions (waiting on @dan-starkware, @dorimedini-starkware, and @nimrod-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3b8ExxBI_m9FPG5mQ3:-O3b8ExxBI_m9FPG5mQ4:b-h2ct53) (no related file):*
What exactly is the desired behavior? Do we want the rust version to be determined per commit across all of the CI? Or do we just want the ability to change it globally (i.e., not 

___
___
*[`.github/workflows/papyrus_nightly-tests-call.yml` line 36 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3aVUDB6KplLyC0U2ND:-O3bDiwE1UdFhKxtpg2X:brb21mw) ([raw file](https://github.com/starkware-libs/sequencer/blob/8044734ddd40af1d2b456e29a3bd505edd22a984/.github/workflows/papyrus_nightly-tests-call.yml#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

non-blocking, but if this works - consider it... you have code duplication anyway, maybe `cat`ing each time isn't so bad
</blockquote></details>

AFAIU this is not possible - you can't run a bash command out of a `run` step

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @dorimedini-starkware, and @nimrod-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3Wi-F20gTb3CYoBLsx:-O3bE10H1UJ2S_GF3fQD:b-brzhxv) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. share the env-variable logic between CI jobs
2. this env var should select the rust version in all CIs, not just main
</blockquote></details>

I'm not sure I understand 2. What exactly do we want? If we want the ability to change the version globally for all branches - we can set an env var via the repo settings and read it in all workflows - this is the better option if we don't want the version to be per commit (the limitation is that only the repo owners can set the version). Can this work?

___

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3Wi-F20gTb3CYoBLsx:-O3bGgit6dGGTu0u0Rly:b9vfgvh) (no related file):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I'm not sure I understand 2. What exactly do we want? If we want the ability to change the version globally for all branches - we can set an env var via the repo settings and read it in all workflows - this is the better option if we don't want the version to be per commit (the limitation is that only the repo owners can set the version). Can this work?
</blockquote></details>

We do want a version per commit. For example, we would like to fix a rust version for release branches

___

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: 13 of 15 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @dorimedini-starkware)

___
*[`.github/workflows/main.yml` line 58 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3R_HLp4Wf-BqHDJkeB:-O3b_eRR8KBfjvZrMyBV:b-3teuai) ([raw file](https://github.com/starkware-libs/sequencer/blob/9ba8c0805ace546cd0833bb80f0f15b8f0969b21/.github/workflows/main.yml#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if format fails - (a) bummer, (b) add a TODO here to fix formatting issues (if this is feasible) and keep the nightly for now
</blockquote></details>

it fails due to some format errors.
I'll bump the toolchain used here in a future PR and will fix the format errors. (wrote a TODO)
___
*[`.github/workflows/papyrus_nightly-tests-call.yml` line 36 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3aVUDB6KplLyC0U2ND:-O3bSplO-MgfuajhFnCs:b-81kw54) ([raw file](https://github.com/starkware-libs/sequencer/blob/8044734ddd40af1d2b456e29a3bd505edd22a984/.github/workflows/papyrus_nightly-tests-call.yml#L36)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

AFAIU this is not possible - you can't run a bash command out of a `run` step
</blockquote></details>

yes, it's impossible
___
*[`.github/workflows/verify-deps.yml` line 32 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3aVAT796aNLenG5A-n:-O3bTDXJ21BU0wXlVBlW:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/8044734ddd40af1d2b456e29a3bd505edd22a984/.github/workflows/verify-deps.yml#L32)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

looking at this particular job, I believe this one should actually stay `stable`.
not sure who wrote it and what the intention was, but it looks like it tests that our code works with latest packages - so makes sense to also test if our code works with latest release of rust, even if the rest of the jobs have fixed rust versions
</blockquote></details>

Done

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: 13 of 15 files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @dorimedini-starkware)

___
*[`scripts/rust_fmt.sh` line 4 at r9](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3b_ope4sQ2ZEn_AsBZ:-O3bb2iS0eTOlvkDsMU9:b-9pqkp0) ([raw file](https://github.com/starkware-libs/sequencer/blob/353e911f73f7cc4b1a4a47605e207df89bdc148d/scripts/rust_fmt.sh#L4)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

read the contents of `rust_version.txt` here (otherwise you have a double point of truth)
</blockquote></details>

Will do when I'll fix the format errors.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nimrod-starkware)

___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 56 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3btC9w9tngXxXvIxwC:-O3btC9w9tngXxXvIxwD:bgo87uh) ([raw file](https://github.com/starkware-libs/sequencer/blob/9194f75047c452668baf62546162b970b4fdd7f2/.github/workflows/blockifier_compiled_cairo.yml#L56)):*
> ```YAML
>       - run:
>           pip install -r crates/blockifier/tests/requirements.txt;
>           cargo test verify_feature_contracts -- --include-ignored
> ```

no need for protoc in a blockifier-only test - please edit the command to the one below



_Suggestion:_
```YAML
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust-ubuntu-20.04"

      # Setup pypy and link to the location expected by .cargo/config.toml.
      - uses: actions/setup-python@v5
        id: setup-pypy
        with:
          python-version: 'pypy3.9'
      - run: ln -s '${{ steps.setup-pypy.outputs.python-path }}' /usr/local/bin/pypy3.9
      - env:
          LD_LIBRARY_PATH: ${{ env.Python3_ROOT_DIR }}/bin
        run: echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}" >> $GITHUB_ENV

      - run:
          pip install -r crates/blockifier/tests/requirements.txt;
          cargo test -p blockifier --test feature_contracts_compatibility_test --features testing -- --include-ignored
```

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 3 of 9 files at r4, 1 of 2 files at r5, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @nimrod-starkware)

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 56 at r11](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3btC9w9tngXxXvIxwC:-O3fPTRQ8elo3l2mRzR_:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9194f75047c452668baf62546162b970b4fdd7f2/.github/workflows/blockifier_compiled_cairo.yml#L56)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no need for protoc in a blockifier-only test - please edit the command to the one below
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nimrod-starkware)

___
*[`.github/workflows/papyrus_nightly-tests-call.yml` line 36 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3aVUDB6KplLyC0U2ND:-O3fY_fi4f9tQNPgNvDU:by5n2v0) ([raw file](https://github.com/starkware-libs/sequencer/blob/8044734ddd40af1d2b456e29a3bd505edd22a984/.github/workflows/papyrus_nightly-tests-call.yml#L36)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

yes, it's impossible
</blockquote></details>

do we want to use `cat` everywhere, or use @TzahiTaub 's suggestion?
whichever involves less boilerplate code gets my vote

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @nimrod-starkware)

___
*[`.github/actions/install_rust/action.yml` line 22 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3gbVmV4gefB7Sa3US6:-O3gbVmV4gefB7Sa3US7:b-kbdlaw) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d24530d1dd6f088e448a195574fd354d18e4473/.github/actions/install_rust/action.yml#L22)):*
> ```YAML
>       uses: dtolnay/rust-toolchain@master
>       with:
>         toolchain: stable
> ```

so this will be our point of truth for the rust version? nice



_Code quote:_
```YAML
  using: "composite"
  steps:
    - name: install rust toolchain with given components
      if: "${{ inputs.components != '' }}"
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: ${{ inputs.components }}

    - name: install rust toolchain without given components
      if: "${{ inputs.components == '' }}"
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
```
___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 44 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3gbpnd6DwQeB4bWl0R:-O3gbpnd6DwQeB4bWl0S:bdmac95) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d24530d1dd6f088e448a195574fd354d18e4473/.github/workflows/blockifier_compiled_cairo.yml#L44)):*
> ```YAML
>       - run:
>           pip install -r crates/blockifier/tests/requirements.txt;
>           cargo test verify_feature_contracts -- --include-ignored
> ```

regression :)



_Suggestion:_
```YAML
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust-ubuntu-20.04"

      # Setup pypy and link to the location expected by .cargo/config.toml.
      - uses: actions/setup-python@v5
        id: setup-pypy
        with:
          python-version: 'pypy3.9'
      - run: ln -s '${{ steps.setup-pypy.outputs.python-path }}' /usr/local/bin/pypy3.9
      - env:
          LD_LIBRARY_PATH: ${{ env.Python3_ROOT_DIR }}/bin
        run: echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}" >> $GITHUB_ENV

      - run:
          pip install -r crates/blockifier/tests/requirements.txt;
          cargo test -p blockifier --test feature_contracts_compatibility_test --features testing -- --include-ignored
```
___
*[`.github/workflows/main.yml` line 47 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3gc-_fDgzvEvWnNwOw:-O3gc-_fDgzvEvWnNwOx:bdmac95) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d24530d1dd6f088e448a195574fd354d18e4473/.github/workflows/main.yml#L47)):*
> ```YAML
>     steps:
>       - uses: actions/checkout@v4
>       - uses: dtolnay/rust-toolchain@master
> ```

regression :)



_Suggestion:_
```YAML
uses: dtolnay/rust-toolchain@master # TODO(Nimrod, 15/8/2024): Use stable toolchain.
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: all files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @dorimedini-starkware)

___
*[`.github/workflows/blockifier_compiled_cairo.yml` line 44 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3gbpnd6DwQeB4bWl0R:-O3gdBPn2yCwk8pQMqAd:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d24530d1dd6f088e448a195574fd354d18e4473/.github/workflows/blockifier_compiled_cairo.yml#L44)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

regression :)
</blockquote></details>

Done.
___
*[`.github/workflows/main.yml` line 47 at r13](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3gc-_fDgzvEvWnNwOw:-O3gd-YG-sPm90G439yv:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/4d24530d1dd6f088e448a195574fd354d18e4473/.github/workflows/main.yml#L47)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

regression :)
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294#-:-O3gdxUJBBwN_rPyr3v3:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nimrod-starkware)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 9 of 12 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nimrod-starkware)

___
*[`.github/actions/install_rust/action.yml` line 15 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3gugxe6sR9LuYVSQry:-O3gugxe6sR9LuYVSQrz:b-26wxtm) ([raw file](https://github.com/starkware-libs/sequencer/blob/e6045c15091ad4f7fd03f86b64ed50df4f9810fc/.github/actions/install_rust/action.yml#L15)):*
> ```YAML
>       uses: dtolnay/rust-toolchain@master
>       with:
>         toolchain: stable
> ```

A suggestion - define an env var here with the toolchain version - to have a single location to change and to avoid the `edit lines 15 & 22` guidelines - as changing this file can change the line numbers but it's easy to miss updating the comment.



_Code quote:_
```YAML
toolchain: stable
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @dan-starkware and @TzahiTaub)

___
*[`.github/actions/install_rust/action.yml` line 15 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3gugxe6sR9LuYVSQry:-O3khhKB24xTe_indg1E:b4ucvgi) ([raw file](https://github.com/starkware-libs/sequencer/blob/e6045c15091ad4f7fd03f86b64ed50df4f9810fc/.github/actions/install_rust/action.yml#L15)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

A suggestion - define an env var here with the toolchain version - to have a single location to change and to avoid the `edit lines 15 & 22` guidelines - as changing this file can change the line numbers but it's easy to miss updating the comment.
</blockquote></details>

I tried to do that, but I couldn't find an easy way.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @TzahiTaub)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nimrod-starkware)

___
*[`.github/actions/install_rust/action.yml` line 15 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3gugxe6sR9LuYVSQry:-O3yWXc72ErIfunzFTRn:byr5drl) ([raw file](https://github.com/starkware-libs/sequencer/blob/e6045c15091ad4f7fd03f86b64ed50df4f9810fc/.github/actions/install_rust/action.yml#L15)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I tried to do that, but I couldn't find an easy way.
</blockquote></details>

I see, I thought it would be possible to define an `env` scope but I see it's [not possible for composite actions.](https://github.com/orgs/community/discussions/51280) You can try to define the toolchain in a step above the current two:

```
steps:
  - name: Define toolchain
    run: echo "DEFAULT_TOOLCHAIN=stable"  >> $GITHUB_ENV  # Will change the env of a caller workflow (overriding this var if it exists)
 - name: install ...
   ...
   with:
     toolchain: ${{ env.DEFAULT_TOOLCHAIN}}
```

**Review by TzahiTaub — APPROVED** [review]

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294)* status: 15 of 16 files reviewed, all discussions resolved (waiting on @dan-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`.github/actions/install_rust/action.yml` line 15 at r14](https://reviewable.io/reviews/starkware-libs/sequencer/294#-O3gugxe6sR9LuYVSQry:-O4-2WVN3HAjlhQS_MX9:bb6un1j) ([raw file](https://github.com/starkware-libs/sequencer/blob/e6045c15091ad4f7fd03f86b64ed50df4f9810fc/.github/actions/install_rust/action.yml#L15)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I see, I thought it would be possible to define an `env` scope but I see it's [not possible for composite actions.](https://github.com/orgs/community/discussions/51280) You can try to define the toolchain in a step above the current two:

```
steps:
  - name: Define toolchain
    run: echo "DEFAULT_TOOLCHAIN=stable"  >> $GITHUB_ENV  # Will change the env of a caller workflow (overriding this var if it exists)
 - name: install ...
   ...
   with:
     toolchain: ${{ env.DEFAULT_TOOLCHAIN}}
```
</blockquote></details>

Done

**Review by TzahiTaub — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/294#-:-O4-2dssCv7ZSY-tvwML:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
