### PR TITLE
feat(batcher): proposer module

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/188)

### CODE REVIEW

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/188)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/batcher/src/proposer.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/188#-O32rhH1BzE2fsML822P:-O32rhH23QaCs7LzXERp:byathsx) ([raw file](https://github.com/starkware-libs/sequencer/blob/af28262b06936881a944fb41ff2c191f068e497b/crates/batcher/src/proposer.rs#L47)):*
> ```XML
> impl Proposer {
>     #[instrument(skip(self), err)]
>     pub async fn take_more_transactions(&self) -> Result<Vec<ThinTransaction>, ProposerError> {
> ```

get_txs



_Code quote:_
```XML
take_more_transactions
```
___
*[`crates/batcher/src/proposer_test.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/188#-O36lcln1fPlA9mDUBn7:-O36lcln1fPlA9mDUBn8:btqan0d) ([raw file](https://github.com/starkware-libs/sequencer/blob/282ed616b7ac998f24ca4d9a7e934ef541e27946/crates/batcher/src/proposer_test.rs#L20)):*
> ```XML
> #[case::mempool_empty(Ok(vec![]))]
> #[case::mempool_few_txs(Ok(vec![ThinTransaction::default()]))]
> #[case::mempool_full(Ok(vec![ThinTransaction::default(); MAX_N_TXS_TO_FETCH]))]
> ```

add a case that the client returns error.

**Review by Yael-Starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/188)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/batcher/src/proposer.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/188#-O32rhH1BzE2fsML822P:-O36xqkT-eY1UmnMlpRX:bjfwo9c) ([raw file](https://github.com/starkware-libs/sequencer/blob/af28262b06936881a944fb41ff2c191f068e497b/crates/batcher/src/proposer.rs#L47)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think take is a better name because it removes transactions from the mempool.
Also, IIUC this function will be called multiple times per block until it is full, hence the `more`.
</blockquote></details>

I think it is good to align the names throughout the different components.

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/188)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/proposer.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/188#-O32rhH1BzE2fsML822P:-O371IM66sM6WQIDEPEq:bujvxwf) ([raw file](https://github.com/starkware-libs/sequencer/blob/af28262b06936881a944fb41ff2c191f068e497b/crates/batcher/src/proposer.rs#L47)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think it is good to align the names throughout the different components.
</blockquote></details>

Changed to pop because of this TODO: https://github.com/starkware-libs/sequencer/blob/41906a6ad3a7266e5aa1981c1d7fdbe66432ec3e/crates/mempool/src/mempool.rs#L55-L56

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/188)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dafnamatsry)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/188)* status: all files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/batcher/src/proposer_test.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/188#-O3Boe9MDjBjjXF5TR4m:-O3Boe9MDjBjjXF5TR4n:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c9ab6aeedd46f388a4530e959caad97fd8cb1d3/crates/batcher/src/proposer_test.rs#L28)):*
> ```XML
> #[case::mempool_client_error(Err(MempoolClientError::ClientError(ClientError::UnexpectedResponse("TEST".to_owned()))))]
> #[tokio::test]
> async fn test_take_more_transactions(
> ```





_Suggestion:_
```XML
test_pop_more_transactions
```
___
*[`crates/batcher/src/proposer_test.rs` line 46 at r4](https://reviewable.io/reviews/starkware-libs/sequencer/188#-O3WQbO2EPj47XMeWPFW:-O3WQbO2EPj47XMeWPFX:bues60k) ([raw file](https://github.com/starkware-libs/sequencer/blob/4c9ab6aeedd46f388a4530e959caad97fd8cb1d3/crates/batcher/src/proposer_test.rs#L46)):*
> ```XML
>     let expected_result = mempool_response.map_err(ProposerError::MempoolClientError);
> 
>     // The error type is not comparable, so we compare the debug representation instead.
> ```

Most of the expected results are comparable (`vec`). Maybe split to 2 test case, one for success scenarios and one for failures.



_Code quote:_
```XML
// The error type is not comparable
```

**Pull request closed without merging**
