### PR TITLE
chore: change bench to allow consuming leaf modifications

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/456)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/456)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/committer_cli/benches/committer_bench.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/456#-O4FgSusD6_ZKYDdKtYW:-O4FgSut75xSKh_mWmH-:b-yriya4) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b717a912151651e1fadd0c076a0c9cc25f35ddb/crates/committer_cli/benches/committer_bench.rs#L45)):*
> ```XML
>         b.iter_batched(
>             || leaf_modifications.clone(),
>             |leaf_modifications_input| {
> ```

To allow consuming the leaf modifications, it has to be cloned on every benchmark iteration.
`iter_batched` allows preparation before each iteration:
https://docs.rs/criterion/latest/criterion/struct.Bencher.html#:~:text=(I)%20%2D%3E%20O%2C-,Times%20a%20routine%20that%20requires%20some%20input%20by%20generating%20a%20batch%20of%20input%2C%20then%20timing%20the%20iteration%20of%20the%20benchmark%20over%20the%20input.,-See%20BatchSize%20for



_Code quote:_
```XML
        b.iter_batched(
            || leaf_modifications.clone(),
            |leaf_modifications_input| {
```

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/456#-:-O4FkRE08DqwgESOY2EP:b-hz3kb8)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/456)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer_cli/benches/committer_bench.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/456#-O4G-HT3AchMh7NYxyOw:-O4JwgutEKt84MQqKrhN:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b717a912151651e1fadd0c076a0c9cc25f35ddb/crates/committer_cli/benches/committer_bench.rs#L42)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

informative variable names pls
</blockquote></details>

Done.
___
*[`crates/committer_cli/benches/committer_bench.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/456#-O4G-dPy4yXfjxVTDaRh:-O4Jx8IdAs_5HsIhd-3G:b3pxzxm) ([raw file](https://github.com/starkware-libs/sequencer/blob/1b717a912151651e1fadd0c076a0c9cc25f35ddb/crates/committer_cli/benches/committer_bench.rs#L55)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why?
</blockquote></details>

the smaller variant:
'`SmallInput` indicates that the input to the benchmark routine (the value returned from the setup routine) is small enough that millions of values can be safely held in memory'.
the input size is a few megabytes, I think

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/456#-:-O4KBLQMALgHU66IcOzX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request closed without merging**
