### PR TITLE
refactor(blockifier): use get versioned contract class in py state reader

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2614?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2614** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2614?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2614?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2420** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2420?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#2421](https://github.com/starkware-libs/sequencer/pull/2421) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2421?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#2438](https://github.com/starkware-libs/sequencer/pull/2438) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2438?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2467** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2467?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2466** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2466?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by AvivYossef-starkware — COMMENTED** [review]
[Python ](https://reviewable.io/reviews/starkware-industries/starkware/36423)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2614#-:-ODl7oAA-00Rcu-yQyzc:btozikj)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @Yoni-Starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2614)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/state_readers/py_state_reader.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2614#-OE8LbxTDktvsxj1xiwS:-OE8LbxTDktvsxj1xiwT:b-rlrib3) ([raw file](https://github.com/starkware-libs/sequencer/blob/715c82462a3416dea49ba91c24244aed53ce5868/crates/native_blockifier/src/state_readers/py_state_reader.rs#L96)):*
> ```XML
>         .map_err(|err| {
>             Python::with_gil(|py| {
>                 if err.is_instance_of::<UndeclaredClassHashError>(py) {
> ```

why did you move the `if` here?



_Code quote:_
```XML
            Python::with_gil(|py| {
                if err.is_instance_of::<UndeclaredClassHashError>(py) {
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2614)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/state_readers/py_state_reader.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2614#-OE8LbxTDktvsxj1xiwS:-OE8wyVtAbUF9NRvXbKy:b-j1lbxr) ([raw file](https://github.com/starkware-libs/sequencer/blob/c9addafdeb5bd43673d1964ee6cfe9915742404e/crates/native_blockifier/src/state_readers/py_state_reader.rs#L96)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why did you move the `if` here?
</blockquote></details>

Not intended.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2614)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
Block until python passes Hodor

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2614#-:-OEAwCxo9xsOFzvlanvL:bkjxb2h)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2614)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Comment by AvivYossef-starkware** [comment]
### Merge activity

* **Dec 17, 3:08 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2614).

**Pull request merged**
