### PR TITLE
refactor(blockifier): remove constant from mid execution test

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1070)

### CODE REVIEW

**Review by aner-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1070)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1070#-O7wnZ509fuFgk8GOKMx:-O7wnZ51-IZTq4nhKHII:b4dh5jj) ([raw file](https://github.com/starkware-libs/sequencer/blob/8cde0b6b8ce19d3dc72a0cf77797b7209478b967/crates/blockifier/src/transaction/execution_flavors_test.rs#L107)):*
> ```XML
> /// Returns the amount of L1 gas and derived fee, given base gas amount and a boolean indicating
> /// if validation is to be done.
> fn gas_and_fee(base_gas: u64, validation_overhead: bool, fee_type: &FeeType) -> (u64, Fee) {
> ```

This name makes more sense for a numeric value. Maybe `include_` or `add_`?



_Suggestion:_
```XML
add_validation_overhead: bool
```
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1070#-O7wo-h_7IP93fE5zhrY:-O7wo-h_7IP93fE5zhrZ:b-q64pkt) ([raw file](https://github.com/starkware-libs/sequencer/blob/8cde0b6b8ce19d3dc72a0cf77797b7209478b967/crates/blockifier/src/transaction/execution_flavors_test.rs#L123)):*
> ```XML
>     tx_execution_info: &TransactionExecutionInfo,
>     block_context: &BlockContext,
>     validation_overhead: bool,
> ```

See above.



_Suggestion:_
```XML
remove_validation_overhead: bool
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1070)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1070#-O7wnZ509fuFgk8GOKMx:-O7ws9xx7cW3gbuWH1kr:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8cde0b6b8ce19d3dc72a0cf77797b7209478b967/crates/blockifier/src/transaction/execution_flavors_test.rs#L107)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

This name makes more sense for a numeric value. Maybe `include_` or `add_`?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1070#-O7wo-h_7IP93fE5zhrY:-O7wsFLk9dGk0FLUWAPE:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/8cde0b6b8ce19d3dc72a0cf77797b7209478b967/crates/blockifier/src/transaction/execution_flavors_test.rs#L123)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.

**Review by aner-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1070)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @yoavGrs)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 574 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1070#-O7y0h2W4HINv0kHg8o0:-O7y0h2W4HINv0kHg8o1:bfcs99w) ([raw file](https://github.com/starkware-libs/sequencer/blob/da7e99233d5d222bb88ffaf01b8f0fab9fbae558/crates/blockifier/src/transaction/execution_flavors_test.rs#L574)):*
> ```XML
>     .unwrap();
>     let base_gas: u64 =
>         calculate_actual_gas(&tx_execution_info, &block_context, validate).try_into().unwrap();
> ```

Maybe consider adding a comment about the offset of the validation overhead between the `execute` and `calculate_actual_gas`?



_Code quote:_
```XML
    .execute(&mut state, &block_context, charge_fee, validate)
    .unwrap();
    let base_gas: u64 =
        calculate_actual_gas(&tx_execution_info, &block_context, validate).try_into().unwrap();
```

**Review by aner-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1070)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1070#-O7y1dek47RNmAhVTgve:-O7y1dek47RNmAhVTgvf:b-v7j3ui) (no related file):*
Blocked until reviewed by @dorimedini-starkware.

___

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1070)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 574 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1070#-O7y0h2W4HINv0kHg8o0:-O7yDclJ1U99zs5Tc1zc:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/da7e99233d5d222bb88ffaf01b8f0fab9fbae558/crates/blockifier/src/transaction/execution_flavors_test.rs#L574)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Maybe consider adding a comment about the offset of the validation overhead between the `execute` and `calculate_actual_gas`?
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1070)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1070#-O7y1dek47RNmAhVTgve:-O7yFQt5EF4p99BtWzFX:bb7f2mf) (no related file):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Blocked until reviewed by @dorimedini-starkware.
</blockquote></details>

done

___
___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 137 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1070#-O7yFEEPDO8hqxE-LCKX:-O7yFEEPDO8hqxE-LCKY:b7kv01y) ([raw file](https://github.com/starkware-libs/sequencer/blob/2bf465c5b414b195c3f0c1ae7d161a8a2fe3056c/crates/blockifier/src/transaction/execution_flavors_test.rs#L137)):*
> ```XML
>         .l1_gas
>         - if remove_validation_overhead { VALIDATE_GAS_OVERHEAD.into() } else { 0 }
> }
> ```

why does one function add validation overhead while the other removes?



_Code quote:_
```XML
fn gas_and_fee(base_gas: u64, add_validation_overhead: bool, fee_type: &FeeType) -> (u64, Fee) {
    // Validation incurs a constant gas overhead.
    let gas = base_gas + if add_validation_overhead { VALIDATE_GAS_OVERHEAD } else { 0 };
    (
        gas,
        get_fee_by_gas_vector(
            &BlockContext::create_for_account_testing().block_info,
            GasVector::from_l1_gas(gas.into()),
            fee_type,
        ),
    )
}

// Calculates the actual gas used by a transaction. Removing the validation overhead if requested,
// as it's already considered in the tx_execution_info.
fn calculate_actual_gas(
    tx_execution_info: &TransactionExecutionInfo,
    block_context: &BlockContext,
    remove_validation_overhead: bool,
) -> u128 {
    tx_execution_info
        .receipt
        .resources
        .to_gas_vector(
            &block_context.versioned_constants,
            block_context.block_info.use_kzg_da,
            &GasVectorComputationMode::NoL2Gas,
        )
        .l1_gas
        - if remove_validation_overhead { VALIDATE_GAS_OVERHEAD.into() } else { 0 }
}
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1070)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/execution_flavors_test.rs` line 137 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/1070#-O7yFEEPDO8hqxE-LCKX:-O80f6oN-H8qxS8G-5mm:butflq7) ([raw file](https://github.com/starkware-libs/sequencer/blob/2bf465c5b414b195c3f0c1ae7d161a8a2fe3056c/crates/blockifier/src/transaction/execution_flavors_test.rs#L137)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why does one function add validation overhead while the other removes?
</blockquote></details>

It comes from the stage of the failure. There is validation overhead in `mid_execution` , while it isn't in `pre_validate`.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1070)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)

**Review by aner-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1070)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
