### PR TITLE
refactor(batcher): test block builder with two chunks

### PR DESCRIPTION
**Pull request by Yael-Starkware**

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
The PRs are split nicely, very convinient for reviewing :)

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1562#-:-OACrlOs3PKAaDTYdlS3:bkmpmfe)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/batcher/src/block_builder_test.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1562#-OAClPi508HVz27yZNEL:-OAClPi508HVz27yZNEM:byybls0) ([raw file](https://github.com/starkware-libs/sequencer/blob/830c941d8e4916be121e36a524c6e1a8a2775f11/crates/batcher/src/block_builder_test.rs#L46)):*
> ```XML
> }
> 
> // TODO: Add test cases for multiple chunks, block full, empty block, failed transaction,
> ```

Can remove now :)
___
*[`crates/batcher/src/block_builder_test.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1562#-OACoVNn6OEexhZjplJY:-OACoVNn6OEexhZjplJZ:bfavcot) ([raw file](https://github.com/starkware-libs/sequencer/blob/830c941d8e4916be121e36a524c6e1a8a2775f11/crates/batcher/src/block_builder_test.rs#L120)):*
> ```XML
>         .in_sequence(&mut seq)
>         .withf(move |blockifier_input| compare_tx_hashes(second_chunk.clone(), blockifier_input))
>         .returning(move |_| vec![execution_info(); block_size].into_iter().map(Ok).collect());
> ```

Suggestion:
Extract the common code into a closure. Also notice it shouldn't be block_size but TEST_CHUNK_SIZE, right?



_Suggestion:_
```XML
let mut set_expectation = |tx_chunk: Vec<Transaction>, seq: &mut Sequence| {
        mock_transaction_executor
            .expect_add_txs_to_block()
            .times(1)
            .in_sequence(seq)
            .withf(move |blockifier_input| compare_tx_hashes(tx_chunk.clone(), blockifier_input))
            .returning(move |_| {
                vec![execution_info(); TEST_CHUNK_SIZE].into_iter().map(Ok).collect()
            });
    };
    set_expectation(first_chunk, &mut seq);
    set_expectation(second_chunk, &mut seq);
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1562)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @dafnamatsry)

___
*[`crates/batcher/src/block_builder_test.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1562#-OAClPi508HVz27yZNEL:-OAH4Rwe416biel5ER65:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/830c941d8e4916be121e36a524c6e1a8a2775f11/crates/batcher/src/block_builder_test.rs#L46)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can remove now :)
</blockquote></details>

done
___
*[`crates/batcher/src/block_builder_test.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1562#-OACoVNn6OEexhZjplJY:-OAH7toqDfXyW6ZwTsGq:b-dnjbch) ([raw file](https://github.com/starkware-libs/sequencer/blob/830c941d8e4916be121e36a524c6e1a8a2775f11/crates/batcher/src/block_builder_test.rs#L120)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Suggestion:
Extract the common code into a closure. Also notice it shouldn't be block_size but TEST_CHUNK_SIZE, right?
</blockquote></details>

very nice :)
done.

**Comment by Yael-Starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1562?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1562** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1562?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1561** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1561?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1539** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/1539?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Yael-Starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1562)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @dafnamatsry)

___
*[`crates/batcher/src/block_builder_test.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1562#-OACoVNn6OEexhZjplJY:-OAH818X7QbEy7sQbMhi:b-4fahzq) ([raw file](https://github.com/starkware-libs/sequencer/blob/830c941d8e4916be121e36a524c6e1a8a2775f11/crates/batcher/src/block_builder_test.rs#L120)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

very nice :)
done.
</blockquote></details>

by the way, I checked how the test passed with "block_size"  instead of "TX_CHUNK_SIZE", and that's because the build_block function iterates the execution_info vector only until it reaches the len of the input_txs.  I think maybe we should add an assert there is the output vec is longer than the input vec, wdyt?

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1562)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @dafnamatsry)

___
*[`crates/batcher/src/block_builder_test.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1562#-OACoVNn6OEexhZjplJY:-OAIAsex3MkHDD5UWSQb:bhz4mmg) ([raw file](https://github.com/starkware-libs/sequencer/blob/830c941d8e4916be121e36a524c6e1a8a2775f11/crates/batcher/src/block_builder_test.rs#L120)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I think it should be an invariant of the tx executor, I'm not sure we want to panic in the block builder in that case. wdyt?
</blockquote></details>

I agree, makes more sense that the executor will enforce this, since this implies and executor bug .
___
*[`crates/batcher/src/block_builder_test.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1562#-OAHlIOkDjmT9R1UqWlt:-OAIANKXBYUi4RSH5U8q:bh4tsvw) ([raw file](https://github.com/starkware-libs/sequencer/blob/aeed9e4006fffcca02299498d66d8fb46e91a3f4/crates/batcher/src/block_builder_test.rs#L114)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Does this also work here?
</blockquote></details>

no, already tried :) 
sequence needs exact times() to work properly.

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1562)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1562)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1562)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1562)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/batcher/src/block_builder_test.rs` line 70 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1562#-OAXaCZa7ynmOgA2Vttt:-OAXaCZa7ynmOgA2Vttu:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/496dad71792dbeb107f684437534d7141db06151/crates/batcher/src/block_builder_test.rs#L70)):*
> ```XML
> 
>     let mut mock_transaction_executor = MockTransactionExecutorTrait::new();
>     let mut set_expectation = |tx_chunk: Vec<Transaction>, seq: &mut Sequence| {
> ```





_Suggestion:_
```XML
mock_add_txs_to_block
```
___
*[`crates/batcher/src/block_builder_test.rs` line 77 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1562#-OAXaqSE8mpF7WZOd3g1:-OAXaqSE8mpF7WZOd3g2:biw9du3) ([raw file](https://github.com/starkware-libs/sequencer/blob/496dad71792dbeb107f684437534d7141db06151/crates/batcher/src/block_builder_test.rs#L77)):*
> ```XML
>             .withf(move |blockifier_input| compare_tx_hashes(&tx_chunk, blockifier_input))
>             .returning(move |_| {
>                 vec![execution_info(); TX_CHUNK_SIZE].into_iter().map(Ok).collect()
> ```

Same as in the other PR.



_Suggestion:_
```XML
(0..TX_CHUNK_SIZE).map(Ok(execution_info()).collect()
```

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1562)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @dafnamatsry)

___
*[`crates/batcher/src/block_builder_test.rs` line 70 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1562#-OAXaCZa7ynmOgA2Vttt:-OAXkQF5EPuZ5gPA_Vbl:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/496dad71792dbeb107f684437534d7141db06151/crates/batcher/src/block_builder_test.rs#L70)):*
> ```XML
> 
>     let mut mock_transaction_executor = MockTransactionExecutorTrait::new();
>     let mut set_expectation = |tx_chunk: Vec<Transaction>, seq: &mut Sequence| {
> ```

Done.
___
*[`crates/batcher/src/block_builder_test.rs` line 77 at r6](https://reviewable.io/reviews/starkware-libs/sequencer/1562#-OAXaqSE8mpF7WZOd3g1:-OAXnCzOBJRcN5NNboex:bb7f2mf) ([raw file](https://github.com/starkware-libs/sequencer/blob/496dad71792dbeb107f684437534d7141db06151/crates/batcher/src/block_builder_test.rs#L77)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Same as in the other PR.
</blockquote></details>

done

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1562)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

**Pull request merged**
