### PR TITLE
chore(deployment): support statefulset in papyrus helm chart

### PR DESCRIPTION
**Pull request by alon-dotan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/484)

### CODE REVIEW

**Comment by idan-starkware** [comment]
*[`deployments/papyrus/helm/values.yaml` line 48 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/484#-O4_S6svCzGalwn7kkM4:-O4_S6svCzGalwn7kkM5:bmhh13q) ([raw file](https://github.com/starkware-libs/sequencer/blob/6877375cecd976971a50304737abeb865fe24df2/deployments/papyrus/helm/values.yaml#L48)):*
> ```YAML
> 
> deployment:
>   type: deployment
> ```

Add a comment that tells what are the options for deployment type.

**Review by idan-starkware — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/484)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @OriStarkware)

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/484)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @idan-starkware and @OriStarkware)

___
*[`deployments/papyrus/helm/values.yaml` line 48 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/484#-O4_S6svCzGalwn7kkM4:-O4d_RhG2qFZmMvHX3Oy:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/6877375cecd976971a50304737abeb865fe24df2/deployments/papyrus/helm/values.yaml#L48)):*
<details><summary><i>Previously, idan-starkware (Idan Shamam) wrote…</i></summary><blockquote>

Add a comment that tells what are the options for deployment type.
</blockquote></details>

Done.

**Comment by idan-starkware** [comment]
:lgtm:

**Review by idan-starkware — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/484)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Review by alon-dotan-starkware — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/484)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)

**Pull request merged**
