### PR TITLE
refactor(starknet_api): remove duplicate definition of contract class

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2298?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2298** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2298?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2298?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2294** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2294?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2277** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2277?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2276** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/2276?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2298)* status: 8 of 12 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/starknet_sierra_compile/src/utils.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2298#-OChuZlm69DpltsGafWn:-OChuZlm69DpltsGafWo:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/1da9eaebc4f3dfb33eb28cde8984d9919aa3b047/crates/starknet_sierra_compile/src/utils.rs#L12)):*
> ```XML
> use starknet_api::state::{
>     EntryPoint as StarknetApiEntryPoint,
>     SierraContractClass as RpcContractClass,
> ```





_Suggestion:_
```XML
SierraContractClass as StarknetApiContractClass,
```
___
*[`crates/papyrus_protobuf/src/converters/rpc_transaction.rs` line 334 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2298#-OChtjNI7rKY5PJxIUSK:-OChtjNI7rKY5PJxIUSL:b6qwdyj) ([raw file](https://github.com/starkware-libs/sequencer/blob/3da1a47260834d8b474637ade72426f0e6155897/crates/papyrus_protobuf/src/converters/rpc_transaction.rs#L334)):*
> ```XML
> }
> 
> impl TryFrom<protobuf::Cairo1Class> for ContractClass {
> ```

@DvirYo-starkware are we okay with removing this?



_Code quote:_
```XML
impl TryFrom<protobuf::Cairo1Class> for ContractClass {
```
___
*[`crates/starknet_gateway/src/stateless_transaction_validator_test.rs` line 359 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/2298#-OChuDY42ytvnlEgzB9G:-OChuDY42ytvnlEgzB9H:bad60e9) ([raw file](https://github.com/starkware-libs/sequencer/blob/1da9eaebc4f3dfb33eb28cde8984d9919aa3b047/crates/starknet_gateway/src/stateless_transaction_validator_test.rs#L359)):*
> ```XML
>     #[case] expected_error: StatelessTransactionValidatorError,
> ) {
>     use starknet_api::state::SierraContractClass;
> ```

Is this necessary?



_Code quote:_
```XML
use starknet_api::state::SierraContractClass;
```

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 12 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2298#-:-OCiMSUU0wkHAtJV5wsc:bnfp4nl)* status: 11 of 12 files reviewed, all discussions resolved

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2298)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Comment by AvivYossef-starkware** [comment]
### Merge activity

* **Nov 28, 2:53 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/2298).

**Pull request merged**
