### PR TITLE
feat(blockifier): support reverts in native

### PR DESCRIPTION
**Pull request by Yoni-Starkware**

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2271#-OCYW790BOTjlM3Z1_eV:-OCYW790BOTjlM3Z1_eW:bxbr8le) ([raw file](https://github.com/starkware-libs/sequencer/blob/fc8224aaa0385e8d4b2607f1edaa9f090bfe7ef8/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L68)):*
> ```XML
>     for call in res.iter() {
>         assert_eq!(call.tracked_resource, TrackedResource::SierraGas);
>     }
> ```

Using SierraGas without cairo-native is not supported?



_Code quote:_
```XML
    // Check that the tracked resource is SierraGas to make sure that Native is running.
    for call in res.iter() {
        assert_eq!(call.tracked_resource, TrackedResource::SierraGas);
    }
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2271)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @dorimedini-starkware, and @Yoni-Starkware)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2271)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @dorimedini-starkware, and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2271#-OCYW790BOTjlM3Z1_eV:-OCYWLoW1AWfBH0G8Q_n:b-vtd6ox) ([raw file](https://github.com/starkware-libs/sequencer/blob/fc8224aaa0385e8d4b2607f1edaa9f090bfe7ef8/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L68)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Using SierraGas without cairo-native is not supported?
</blockquote></details>

It is supported. But is the resource was CairoSteps, the Native class would be replace with casm.
This check is to verify that the native case is not replaced under the hood.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2271)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @dorimedini-starkware, and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2271#-OCYW790BOTjlM3Z1_eV:-OCYkTgg6Kbd93WCaT5F:b4tobit) ([raw file](https://github.com/starkware-libs/sequencer/blob/9692b16cbc73c75e159dd0439841820cab0b6666/crates/blockifier/src/execution/syscalls/syscall_tests/call_contract.rs#L68)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it feels like a bad check for usage of native.
</blockquote></details>

Native yes/no should be transparent :(
I'll think about a better indication

**Pull request merged**
