### PR TITLE
feat(consensus): add sync sender to context to broadcast on decision

### PR DESCRIPTION
**Pull request by matan-starkware**
This is optional since outside of testing mode sync should be its own component of the node.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/413)

### CODE REVIEW

**Comment by matan-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/413?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#414** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/414?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#413** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/413?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#412** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/412?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#409** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/409?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#406** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/406?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#404** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/404?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#389** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/389?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#403](https://github.com/starkware-libs/sequencer/pull/403) <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/403?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#387** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/387?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#386** <a href="https://app.graphite.dev/github/pr/starkware-libs/sequencer/386?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by DvirYo-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/413)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @matan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/413#-O4AkZZM4dNi47K4Rtz_:-O4AkZZN82tmNV2V-Qgk:bu79i8n) (no related file):*
I am not sure I understand this PR.
1. I don't understand why the sync component should broadcast new blocks. Why not the consensus?
2. Is the new `sync_broadcast_sender` used only for tests (and also to be used in the future only for this purpose)? If it does I don't think it should be part of a "real" code

___

**Review by matan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/413)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/413#-O4AkZZM4dNi47K4Rtz_:-O4Ktrp_9eRKFGpMYg1m:b-uictf7) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I am not sure I understand this PR.
1. I don't understand why the sync component should broadcast new blocks. Why not the consensus?
2. Is the new `sync_broadcast_sender` used only for tests (and also to be used in the future only for this purpose)? If it does I don't think it should be part of a "real" code
</blockquote></details>

Spoke f2f.

___

**Review by DvirYo-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/413#-:-O4L9JWQ5YlbM3PTljaY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)

**Comment by matan-starkware** [comment]
### Merge activity

* **Aug 15, 9:56 AM EDT**: @matan-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/sequencer/413).

**Pull request merged**
