### PR TITLE
feat(ci): codestyle phases now run through py script on changes only

### PR DESCRIPTION
**Pull request by dorimedini-starkware**

### CODE REVIEW

**Review by adi-yakovian-starkware — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1549)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @giladchase, @Itay-Tsabary-Starkware, and @nadin-Starkware)

___
*[`.github/workflows/main.yml` line 32 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/1549#-O9yebRq6VFzRrr025b_:-OADtF021rObT-s8STzW:b-w49lbd) ([raw file](https://github.com/starkware-libs/sequencer/blob/ad4961eac5421e0390682463abec4ea79a73ce23/.github/workflows/main.yml#L32)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

required to checkout the merge target commit
</blockquote></details>

Consider adding this explanation to the comment.
___
*[`scripts/run_tests.py` line 125 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1549#-OAD0sQxA5pDv_TwS46w:-OAD0sQy0qpszIrbAhH4:b-pw2sb2) ([raw file](https://github.com/starkware-libs/sequencer/blob/7f072d70baa5f1324e77e96ae1d419c57df54f5e/scripts/run_tests.py#L125)):*
> ```Python
>         "--command",
>         required=True,
>         choices=[cmd.name for cmd in BaseCommand],
> ```

Just wondering: why `cmd.name` and not `cmd.value`? Is it common to use capital letters for flag values?



_Code quote:_
```Python
cmd.name
```

**Review by Itay-Tsabary-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1549)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, and @nadin-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1549#-O9yeqmw8_FTg6aVSrdj:-OAEaJ7ZBe_BJLXoDBB5:b-kncozk) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

change to how we run clippy, doc and rustfmt:
1. clippy and rustfmt bash scripts no longer use `--workspace` or `--all`, now get `-p X` list as input
2. rustfmt hard-codes `--check` (reasonable? @giladchase @Itay-Tsabary-Starkware does anyone use the bash script for it's fix option?)
3. these phases now run (through `run_test.py`) with `--changes_only`
</blockquote></details>

RE 2

IMO makes sense to change the invocation of `rustfmt.sh` through `run_tests.py` to use the `--check` flag.
It also makes sense to keep the default option of a direct invocation of `rustfmt.sh` to be `--fix`.

___
___
*[`scripts/run_tests.py` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1549#-OAEapX229vsxE4kx00V:-OAEapX229vsxE4kx00W:b-uhyr31) ([raw file](https://github.com/starkware-libs/sequencer/blob/7f072d70baa5f1324e77e96ae1d419c57df54f5e/scripts/run_tests.py#L1)):*
> ```Python
> #!/bin/env python3
> ```

What python is this? There's match case starting 3.10
https://docs.python.org/3/whatsnew/3.10.html



_Code quote:_
```Python
#!/bin/env python3
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1549)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase and @nadin-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1549#-O9yeqmw8_FTg6aVSrdj:-OAHD94P4IPQzw_JyMXe:b-o44tbz) (no related file):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

RE 2

IMO makes sense to change the invocation of `rustfmt.sh` through `run_tests.py` to use the `--check` flag.
It also makes sense to keep the default option of a direct invocation of `rustfmt.sh` to be `--fix`.
</blockquote></details>

you can now run `rust_fmt.sh --all -- --check` or `rust_fmt.sh --all -- --fix` (not sure if `fix` is even a flag, or just the default). SG?

___
___
*[`scripts/run_tests.py` line 1 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/1549#-OAEapX229vsxE4kx00V:-OAHDbzG7Il0_nJWFMul:blbg9rf) ([raw file](https://github.com/starkware-libs/sequencer/blob/7f072d70baa5f1324e77e96ae1d419c57df54f5e/scripts/run_tests.py#L1)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

What python is this? There's match case starting 3.10
https://docs.python.org/3/whatsnew/3.10.html
</blockquote></details>

let's upgrade our python side repo to 3.10 before we start using it here...
otherwise devs will need multiple local python versions and it will be a headache.

**Review by Itay-Tsabary-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1549#-:-OAHUuqp8r-hMQI-aMDc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase and @nadin-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/1549#-O9yeqmw8_FTg6aVSrdj:-OAHUnYz6MUvTIFrnhU9:b4c9lyr) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you can now run `rust_fmt.sh --all -- --check` or `rust_fmt.sh --all -- --fix` (not sure if `fix` is even a flag, or just the default). SG?
</blockquote></details>

:thumbsup: 

___

**Review by adi-yakovian-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/1549#-:-OAHXHpD-W5zeDJ1kQYJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase and @nadin-Starkware)

**Pull request merged**
