### PR TITLE
test(mempool): flow test send tx twice

### PR DESCRIPTION
**Pull request by MohammadNassar1**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/90)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/90)* status: all files reviewed, 7 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 516 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/90#-O2dS9YlBlPY55qrGMY_:-O2dS9YlBlPY55qrGMYa:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/2502bfac0877076a11b40054010ac706173d132d/crates/mempool/src/mempool_test.rs#L516)):*
> ```XML
> 
> #[rstest]
> #[ignore]
> ```





_Suggestion:_
```XML
#[rstest]
```
___
*[`crates/mempool/src/mempool_test.rs` line 517 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/90#-O2dSrhLAbYXQiY6wnYq:-O2dSrhM-_QGfQBqmpTd:b-ylftcu) ([raw file](https://github.com/starkware-libs/sequencer/blob/2502bfac0877076a11b40054010ac706173d132d/crates/mempool/src/mempool_test.rs#L517)):*
> ```XML
> #[rstest]
> #[ignore]
> fn test_flow_send_tx_twice() {
> ```

Not a good name, maybe `send_same_nonce_tx_after_previous_not_included`.
Does it have to be a flow test though? Let's think what is the logic that's checked here.



_Code quote:_
```XML
test_flow_send_tx_twice
```
___
*[`crates/mempool/src/mempool_test.rs` line 526 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/90#-O2dSB_G-dZ-q_4zTD8M:-O2dSB_G-dZ-q_4zTD8N:b1ta8oh) ([raw file](https://github.com/starkware-libs/sequencer/blob/2502bfac0877076a11b40054010ac706173d132d/crates/mempool/src/mempool_test.rs#L526)):*
> ```XML
> 
>     let queue_txs = [TransactionReference::new(&tx_nonce3)];
>     let pool_txs = vec![tx_nonce3.clone(), tx_input_nonce4.tx.clone(), tx_nonce5.clone()];
> ```

`map`, please.



_Code quote:_
```XML
vec![tx_nonce3.clone(), tx_input_nonce4.tx.clone(), tx_nonce5.clone()];
```
___
*[`crates/mempool/src/mempool_test.rs` line 531 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/90#-O2dSW_H3WNaJM_-e7ga:-O2dSW_H3WNaJM_-e7gb:bmjaac0) ([raw file](https://github.com/starkware-libs/sequencer/blob/2502bfac0877076a11b40054010ac706173d132d/crates/mempool/src/mempool_test.rs#L531)):*
> ```XML
>     // Test.
>     let txs = mempool.get_txs(2).unwrap();
>     assert_eq!(txs, &[tx_nonce3, tx_input_nonce4.tx.clone()]);
> ```

Can we substitute with artificially creating the `mempoo_state` you need (using `MempoolState`)?



_Code quote:_
```XML
    // Test.
    let txs = mempool.get_txs(2).unwrap();
    assert_eq!(txs, &[tx_nonce3, tx_input_nonce4.tx.clone()]);
```
___
*[`crates/mempool/src/mempool_test.rs` line 533 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/90#-O2dSP2b1tOkOkqD6kvW:-O2dSP2cCN_XXHcV3bpl:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/2502bfac0877076a11b40054010ac706173d132d/crates/mempool/src/mempool_test.rs#L533)):*
> ```XML
>     assert_eq!(txs, &[tx_nonce3, tx_input_nonce4.tx.clone()]);
> 
>     // Transaction 4 is reverted.
> ```





_Suggestion:_
```XML
// Transaction with nonce 4 is not included in the block.
```
___
*[`crates/mempool/src/mempool_test.rs` line 534 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/90#-O2dSdmS-RE2QwFOlpp0:-O2dSdmS-RE2QwFOlpp1:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/2502bfac0877076a11b40054010ac706173d132d/crates/mempool/src/mempool_test.rs#L534)):*
> ```XML
> 
>     // Transaction 4 is reverted.
>     let commit_state =
> ```





_Suggestion:_
```XML
state_changes
```

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/90)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 526 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/90#-O2dSB_G-dZ-q_4zTD8M:-O2eU-LtEHn3QhvveGiM:b75z8qz) ([raw file](https://github.com/starkware-libs/sequencer/blob/2502bfac0877076a11b40054010ac706173d132d/crates/mempool/src/mempool_test.rs#L526)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`map`, please.
</blockquote></details>

Took me a while to get to this solution! Do you think it hurts readability (might someone think that we're "cloning references"? Whatever that means)?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/90)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 517 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/90#-O2dSrhLAbYXQiY6wnYq:-O2y-CpaEHYidsmMOGob:b-muix3u) ([raw file](https://github.com/starkware-libs/sequencer/blob/2502bfac0877076a11b40054010ac706173d132d/crates/mempool/src/mempool_test.rs#L517)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not a good name, maybe `send_same_nonce_tx_after_previous_not_included`.
Does it have to be a flow test though? Let's think what is the logic that's checked here.
</blockquote></details>

I think it has to be a flow test. To have such a scenario, we need to delete a tx using `commit_block`, and to insure that it can be send again, we need ``add_tx`.
___
*[`crates/mempool/src/mempool_test.rs` line 526 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/90#-O2dSB_G-dZ-q_4zTD8M:-O2y0LUT8FvcMLBJ14Fu:b-hw7cqp) ([raw file](https://github.com/starkware-libs/sequencer/blob/2502bfac0877076a11b40054010ac706173d132d/crates/mempool/src/mempool_test.rs#L526)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Took me a while to get to this solution! Do you think it hurts readability (might someone think that we're "cloning references"? Whatever that means)?
</blockquote></details>

The process of cloning a reference is the same as creating a normal clone.
___
*[`crates/mempool/src/mempool_test.rs` line 531 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/90#-O2dSW_H3WNaJM_-e7ga:-O2y1SxlCxVEJrTSwJpy:b-atmd7l) ([raw file](https://github.com/starkware-libs/sequencer/blob/2502bfac0877076a11b40054010ac706173d132d/crates/mempool/src/mempool_test.rs#L531)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we substitute with artificially creating the `mempoo_state` you need (using `MempoolState`)?
</blockquote></details>

Changed to mempool_state.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/90)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/sequencer/90#-O31lEBhBKOpQCUu0P5S:-O32t4XvEST4SOsCgbeI:b-2crodr) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think the two flow tests of `commit_block` closing a hole can be merged. WDYT?
</blockquote></details>

This one doesn't close hole, a `commit_block` reverts a tx, which enables us to resend the same tx.

___
___
*[`crates/mempool/src/mempool_test.rs` line 526 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/90#-O2dSB_G-dZ-q_4zTD8M:-O32yqwU92QSYt6hKS_m:b-7r1jvw) ([raw file](https://github.com/starkware-libs/sequencer/blob/2502bfac0877076a11b40054010ac706173d132d/crates/mempool/src/mempool_test.rs#L526)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYM? Can you point me to a doc. reference?
</blockquote></details>

Can you pls explain again your point?
___
*[`crates/mempool/src/mempool_test.rs` line 531 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/90#-O2dSW_H3WNaJM_-e7ga:-O32vvLI27Ux8D7mY7e2:b4rjvyg) ([raw file](https://github.com/starkware-libs/sequencer/blob/2502bfac0877076a11b40054010ac706173d132d/crates/mempool/src/mempool_test.rs#L531)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I meant creating the staging area without calling `get_txs` (a possible impl. of a `commit_block` _unit test_ of this scenario).
</blockquote></details>

I believe we have a task where MempoolState/MempoolContent should support initializing the staging area.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/90)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 700 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/90#-O3WvVGl430SU96O2ihv:-O3WvVGl430SU96O2ihw:b7txtav) ([raw file](https://github.com/starkware-libs/sequencer/blob/33bd07d6f3add08f1a01496fe58dde26ae515da1/crates/mempool/src/mempool_test.rs#L700)):*
> ```XML
>         HashMap::from([(contract_address!("0x0"), AccountState { nonce: Nonce(felt!(3_u16)) })]);
>     assert!(mempool.commit_block(state_changes).is_ok());
> ```

Do we want to assert on the state of the mempool after block is committed?
___
*[`crates/mempool/src/mempool_test.rs` line 706 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/90#-O3WvMLM5CXHW6k8AT3-:-O3WvMLM5CXHW6k8AT30:b-ij2o5c) ([raw file](https://github.com/starkware-libs/sequencer/blob/33bd07d6f3add08f1a01496fe58dde26ae515da1/crates/mempool/src/mempool_test.rs#L706)):*
> ```XML
>     // Assert.
>     assert_eq!(txs, &[tx_input_nonce4.tx]);
>     let expected_queue_txs = [&tx_nonce5].map(TransactionReference::new);
> ```

No `map` on a single element.



_Code quote:_
```XML
[&tx_nonce5].map(TransactionReference::new);
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/90)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 700 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/90#-O3WvVGl430SU96O2ihv:-O3Xx9t78HJdgqDdQy7k:bs6g0) ([raw file](https://github.com/starkware-libs/sequencer/blob/33bd07d6f3add08f1a01496fe58dde26ae515da1/crates/mempool/src/mempool_test.rs#L700)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we want to assert on the state of the mempool after block is committed?
</blockquote></details>

No need, I think the assert on the state after the add would cover it.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/90#-:-O3b0Qpz35w9iZKVR3x6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Pull request merged**
