### PR TITLE
test(mempool): flow test with a happy flow scenario

### PR DESCRIPTION
**Pull request by MohammadNassar1**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/94)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/94)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 552 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/94#-O2dUXtF72BWFF78Xm_Y:-O2dUXtF72BWFF78Xm_Z:ba70pg7) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb43561daa7cd25452be09e6122c766faafaed22/crates/mempool/src/mempool_test.rs#L552)):*
> ```XML
>     mempool.get_txs(2).unwrap();
>     // It gets: tx_address1_nonce1, and tx_address2_nonce2.
>     mempool.get_txs(3).unwrap();
> ```

Maybe build the `mempool_state`? Should this really be a flow test?



_Code quote:_
```XML
    // It gets: tx_address0_nonce3, and tx_address1_nonce0.
    mempool.get_txs(2).unwrap();
    // It gets: tx_address1_nonce1, and tx_address2_nonce2.
    mempool.get_txs(3).unwrap();
```
___
*[`crates/mempool/src/mempool_test.rs` line 555 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/94#-O2dUVV4AgDzioaUNPi0:-O2dUVV4AgDzioaUNPi1:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb43561daa7cd25452be09e6122c766faafaed22/crates/mempool/src/mempool_test.rs#L555)):*
> ```XML
> 
>     // Reverted txs: tx_address2_nonce2, and tx_address1_nonce1.
>     let commit_state = HashMap::from([
> ```





_Suggestion:_
```XML
state_changes
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/94)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/94)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 552 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/94#-O2dUXtF72BWFF78Xm_Y:-O2dk7T-27EaD_PRS6DP:blun9du) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb43561daa7cd25452be09e6122c766faafaed22/crates/mempool/src/mempool_test.rs#L552)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Maybe build the `mempool_state`? Should this really be a flow test?
</blockquote></details>

It's a happy flow. I wanted to run a test that has several get_txs and then a commit_block/

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/94)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 552 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/94#-O2dUXtF72BWFF78Xm_Y:-O2dlPzIBcq2oNZA_CXi:b3we7tl) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb43561daa7cd25452be09e6122c766faafaed22/crates/mempool/src/mempool_test.rs#L552)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It's a happy flow. I wanted to run a test that has several get_txs and then a commit_block/
</blockquote></details>

Is there extra coverage (more isolated) we'll gain if we also add this as a unit test?

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/94)* status: all files reviewed, 5 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 552 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/94#-O2dUXtF72BWFF78Xm_Y:-O2s3g9KDdoYnGOpCSC_:b90icuu) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb43561daa7cd25452be09e6122c766faafaed22/crates/mempool/src/mempool_test.rs#L552)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

This is the only test that checks mempool_state, as the get_txs, updates it, and commit_block uses it.
wdyt?
</blockquote></details>

Do we check these scenarios separately in unit tests? Can you please point me to them?
___
*[`crates/mempool/src/mempool_test.rs` line 581 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/94#-O2s3mbe0RkEzZD8_WzB:-O2s3mbe0RkEzZD8_WzC:bgmiqvb) ([raw file](https://github.com/starkware-libs/sequencer/blob/63b4edd99f7a2cb106da22076af55f73d7fc2ec9/crates/mempool/src/mempool_test.rs#L581)):*
> ```XML
> #[rstest]
> #[ignore]
> fn test_happy_flow_get_txs_commit_block() {
> ```

Maybe add a short docstring explaining that in this flow not all transactions given to the sequencer were eventually included in the block.



_Suggestion:_
```XML
test_flow_partial_commit_block
```
___
*[`crates/mempool/src/mempool_test.rs` line 616 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/94#-O2s4-7v-tyVFaAxl6AG:-O2s4-7w4LyW05GPicHZ:bnlhbhy) ([raw file](https://github.com/starkware-libs/sequencer/blob/63b4edd99f7a2cb106da22076af55f73d7fc2ec9/crates/mempool/src/mempool_test.rs#L616)):*
> ```XML
>     mempool.get_txs(2).unwrap();
>     // It gets: tx_address1_nonce1, and tx_address2_nonce2.
>     mempool.get_txs(3).unwrap();
> ```

Let's assert instead of documenting.



_Code quote:_
```XML
    // It gets: tx_address0_nonce3, and tx_address1_nonce0.
    mempool.get_txs(2).unwrap();
    // It gets: tx_address1_nonce1, and tx_address2_nonce2.
    mempool.get_txs(3).unwrap();
```
___
*[`crates/mempool/src/mempool_test.rs` line 618 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/94#-O2s4ifdE7eP1Q-eCLgU:-O2s4ife7WQcW-I8XUrd:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/63b4edd99f7a2cb106da22076af55f73d7fc2ec9/crates/mempool/src/mempool_test.rs#L618)):*
> ```XML
>     mempool.get_txs(3).unwrap();
> 
>     // Reverted txs: tx_address2_nonce2, and tx_address1_nonce1.
> ```





_Suggestion:_
```XML
    // Not included in block: `tx_address2_nonce2`, `tx_address1_nonce1`.
```
___
*[`crates/mempool/src/mempool_test.rs` line 628 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/94#-O2s4prJ-pSqH358DEud:-O2s4prJ-pSqH358DEue:bq5iuaa) ([raw file](https://github.com/starkware-libs/sequencer/blob/63b4edd99f7a2cb106da22076af55f73d7fc2ec9/crates/mempool/src/mempool_test.rs#L628)):*
> ```XML
>     let expected_pool_txs = [tx_address0_nonce5, tx_address0_nonce6, tx_address1_nonce2];
>     let expected_mempool_state = MempoolState::new(expected_pool_txs, []);
>     expected_mempool_state.assert_eq_mempool_state(&mempool);
> ```

Why not queue as well? I think it's appropriate to do a full state check in a flow test.



_Code quote:_
```XML
assert_eq_mempool_state
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/94)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 552 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/94#-O2dUXtF72BWFF78Xm_Y:-O2xH4wq0TcYZf6UrlOY:b-vcjr3d) ([raw file](https://github.com/starkware-libs/sequencer/blob/bb43561daa7cd25452be09e6122c766faafaed22/crates/mempool/src/mempool_test.rs#L552)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we check these scenarios separately in unit tests? Can you please point me to them?
</blockquote></details>

Currently, we don't check mempool state in a unit test.
___
*[`crates/mempool/src/mempool_test.rs` line 581 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/94#-O2s3mbe0RkEzZD8_WzB:-O2xGcnP9CX7ktBqvTXJ:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/63b4edd99f7a2cb106da22076af55f73d7fc2ec9/crates/mempool/src/mempool_test.rs#L581)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Maybe add a short docstring explaining that in this flow not all transactions given to the sequencer were eventually included in the block.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 616 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/94#-O2s4-7v-tyVFaAxl6AG:-O2xz--D8o1AJotdi2ba:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/63b4edd99f7a2cb106da22076af55f73d7fc2ec9/crates/mempool/src/mempool_test.rs#L616)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's assert instead of documenting.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 618 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/94#-O2s4ifdE7eP1Q-eCLgU:-O2xz2itEoqNORB4jL-m:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/63b4edd99f7a2cb106da22076af55f73d7fc2ec9/crates/mempool/src/mempool_test.rs#L618)):*
> ```XML
>     mempool.get_txs(3).unwrap();
> 
>     // Reverted txs: tx_address2_nonce2, and tx_address1_nonce1.
> ```

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 628 at r2](https://reviewable.io/reviews/starkware-libs/sequencer/94#-O2s4prJ-pSqH358DEud:-O2xz8fXB8fD8ip0nvCs:b-3v92mt) ([raw file](https://github.com/starkware-libs/sequencer/blob/63b4edd99f7a2cb106da22076af55f73d7fc2ec9/crates/mempool/src/mempool_test.rs#L628)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not queue as well? I think it's appropriate to do a full state check in a flow test.
</blockquote></details>

As the mempool queue is empty.
Not sure I got your point.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/94#-:-O31PNbf2IaBFCIt4AzF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
