### PR TITLE
feat(sequencing): add client to cende

### PR DESCRIPTION
**Pull request by DvirYo-starkware**

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2906)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/starknet_sequencer_node/src/config/node_config.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OEpK-G---U-5FrUZhve:-OEpK-G---U-5FrUZhvf:b-rlgpmi) ([raw file](https://github.com/starkware-libs/sequencer/blob/99092e8d600f51fe02b65da13d72dec7ee003e01/crates/starknet_sequencer_node/src/config/node_config.rs#L92)):*
> ```XML
>             set_pointing_param_paths(&["consensus_manager_config.consensus_config.validator_id"]),
>         ),
>         (
> ```

Mandatory config params are at the top level with pointers to the "real" value.

**Review by Yael-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2906)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[`crates/starknet_sequencer_node/src/config/node_config.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OEpK-G---U-5FrUZhve:-OEstAq_A6Hv2_zTVPBl:b-s4eovm) ([raw file](https://github.com/starkware-libs/sequencer/blob/99092e8d600f51fe02b65da13d72dec7ee003e01/crates/starknet_sequencer_node/src/config/node_config.rs#L92)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Mandatory config params are at the top level with pointers to the "real" value.
</blockquote></details>

I thought that config pointers are used to share configs between different services. 
why does this need to be here?
There are many mandatory config (most are mandatory), that do not appear here.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2906)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OEt588h6mtc7LfrnFSJ:-OEt588h6mtc7LfrnFSK:b45h) ([raw file](https://github.com/starkware-libs/sequencer/blob/99092e8d600f51fe02b65da13d72dec7ee003e01/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L103)):*
> ```XML
>             // Heights that are permitted to be built without writing to Aerospike.
>             // Height 1 to make  `end_to_end_flow` test pass.
>             const PERMITTED_HEIGHTS: [BlockNumber; 1] = [BlockNumber(1)];
> ```





_Suggestion:_
```XML
NO_WRITE_REQUIRED_HEIGHTS
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OEt4b-d-IDiPIcYypjr:-OEt4b-d-IDiPIcYypjs:b-cp1rlb) ([raw file](https://github.com/starkware-libs/sequencer/blob/99092e8d600f51fe02b65da13d72dec7ee003e01/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L115)):*
> ```XML
>             }
>             let Some(ref blob) = *prev_height_blob.lock().await else {
>                 debug!("No blob to write to Aerospike.");
> ```

when does it happen that there is no blob to write?



_Code quote:_
```XML
debug!("No blob to write to Aerospike.");
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OEt5LXDCfnWbmBF9wrk:-OEt5LXDCfnWbmBF9wrl:b-5qo25z) ([raw file](https://github.com/starkware-libs/sequencer/blob/99092e8d600f51fe02b65da13d72dec7ee003e01/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L131)):*
> ```XML
>                     }
>                 }
>                 Err(err) => {
> ```

what is the difference between the 2 errors? one is a communication error and one is an error in the recorder service?
lets write a more specific log message



_Code quote:_
```XML
Err(err) => {
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OEt688ZBLbJurNvUUF2:-OEt688ZBLbJurNvUUF3:bv2w29c) ([raw file](https://github.com/starkware-libs/sequencer/blob/99092e8d600f51fe02b65da13d72dec7ee003e01/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L134)):*
> ```XML
>                     debug!("Failed to write blob to Aerospike. Error: {}", err);
>                     // TODO(dvir): change this to `false`. The reason for the current value is to
>                     // make the `end_to_end_flow_test` to pass.
> ```

lets use mock for tests



_Code quote:_
```XML
                    // TODO(dvir): change this to `false`. The reason for the current value is to
                    // make the `end_to_end_flow_test` to pass.
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2906)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry, @Itay-Tsabary-Starkware, and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OEt4b-d-IDiPIcYypjr:-OEwv21h2NTCYp5YrtJZ:bfxlpne) ([raw file](https://github.com/starkware-libs/sequencer/blob/99092e8d600f51fe02b65da13d72dec7ee003e01/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L115)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

when does it happen that there is no blob to write?
</blockquote></details>

When starting. You don't have the info from the previous height
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OEt5LXDCfnWbmBF9wrk:-OEwvTnSEu3ryvHQpXzQ:b-kpz4m8) ([raw file](https://github.com/starkware-libs/sequencer/blob/99092e8d600f51fe02b65da13d72dec7ee003e01/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L131)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

what is the difference between the 2 errors? one is a communication error and one is an error in the recorder service?
lets write a more specific log message
</blockquote></details>

Please suggest different messages
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OEt688ZBLbJurNvUUF2:-OEwvXMn4wodgzQr-n3m:bvos9ae) ([raw file](https://github.com/starkware-libs/sequencer/blob/99092e8d600f51fe02b65da13d72dec7ee003e01/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L134)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

lets use mock for tests
</blockquote></details>

In unitests, we use mocks; in flow tests, we should not use mocks.
___
*[`crates/starknet_sequencer_node/src/config/node_config.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OEpK-G---U-5FrUZhve:-OEx61wUBZ8E-FPgCusA:b-u9vvfi) ([raw file](https://github.com/starkware-libs/sequencer/blob/99092e8d600f51fe02b65da13d72dec7ee003e01/crates/starknet_sequencer_node/src/config/node_config.rs#L92)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I thought that config pointers are used to share configs between different services. 
why does this need to be here?
There are many mandatory config (most are mandatory), that do not appear here.
</blockquote></details>

I also talked with @Itay-Tsabary-Starkware; at least for now, this is how we treat required parameters.
all the mandatory configs are here.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OEt588h6mtc7LfrnFSJ:-OEx6NQnAi_HHonw6nxb:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/99092e8d600f51fe02b65da13d72dec7ee003e01/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L103)):*
> ```XML
>             // Heights that are permitted to be built without writing to Aerospike.
>             // Height 1 to make  `end_to_end_flow` test pass.
>             const PERMITTED_HEIGHTS: [BlockNumber; 1] = [BlockNumber(1)];
> ```

Done.

**Review by dafnamatsry — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2906)* status: 0 of 12 files reviewed, 8 unresolved discussions (waiting on @DvirYo-starkware, @Itay-Tsabary-Starkware, and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 105 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OExP8Te2NIoeE08mk59:-OExP8Tf5jlBfB86EOWX:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/9681cf11e907ccc26c209d1a604a0793add8a117/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L105)):*
> ```XML
>             // Heights that are permitted to be built without writing to Aerospike.
>             // Height 1 to make  `end_to_end_flow` test pass.
>             const NO_WRITE_REQUIRED_HEIGHTS: [BlockNumber; 1] = [BlockNumber(1)];
> ```





_Suggestion:_
```XML
SKIP_WRITE_HEIGHTS
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OExPCSm5mfkOfD8EuZZ:-OExPCSm5mfkOfD8EuZ_:b4d045z) ([raw file](https://github.com/starkware-libs/sequencer/blob/9681cf11e907ccc26c209d1a604a0793add8a117/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L109)):*
> ```XML
>             if NO_WRITE_REQUIRED_HEIGHTS.contains(&height) {
>                 debug!(
>                     "height {} is in `PERMITTED_HEIGHTS`, consensus can send proposal without \
> ```

Change here as well.



_Code quote:_
```XML
PERMITTED_HEIGHTS
```
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OExQey_1StcV1ptP_mw:-OExQeya4xx3qfnk6qwo:bwkcak2) ([raw file](https://github.com/starkware-libs/sequencer/blob/9681cf11e907ccc26c209d1a604a0793add8a117/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L127)):*
> ```XML
>                     if response.status().is_success() {
>                         debug!("Blob written to Aerospike successfully.");
>                         sender.send(true).expect("Writing to a one-shot sender should succeed.");
> ```

This line repeats itself many times (sometimes with expect, sometimes with unwrap). Please move it to a helper function.



_Code quote:_
```XML
sender.send(true).expect("Writing to a one-shot sender should succeed.");
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2906)* status: 0 of 12 files reviewed, 8 unresolved discussions (waiting on @dafnamatsry, @Itay-Tsabary-Starkware, and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OExPCSm5mfkOfD8EuZZ:-OExSw2LCXgEhsSztjub:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9681cf11e907ccc26c209d1a604a0793add8a117/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L109)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Change here as well.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OExQey_1StcV1ptP_mw:-OExT_QiBasnUN3FG605:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9681cf11e907ccc26c209d1a604a0793add8a117/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L127)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

This line repeats itself many times (sometimes with expect, sometimes with unwrap). Please move it to a helper function.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 105 at r3](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OExP8Te2NIoeE08mk59:-OExSvGW9BcfKAY2DiOp:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/9681cf11e907ccc26c209d1a604a0793add8a117/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L105)):*
> ```XML
>             // Heights that are permitted to be built without writing to Aerospike.
>             // Height 1 to make  `end_to_end_flow` test pass.
>             const NO_WRITE_REQUIRED_HEIGHTS: [BlockNumber; 1] = [BlockNumber(1)];
> ```

Done.

**Review by Yael-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2906)* status: 0 of 12 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry, @DvirYo-starkware, and @Itay-Tsabary-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OEt5LXDCfnWbmBF9wrk:-OExxk-aAYe7tpQak1tS:b5joiow) ([raw file](https://github.com/starkware-libs/sequencer/blob/99092e8d600f51fe02b65da13d72dec7ee003e01/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L131)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Please suggest different messages
</blockquote></details>

if the reasons for failure are the ones I wrote above:
1. "The recorder failed to write blob. Error: {}",...
2. "Failed to send a request to the recorder. Error: {}",....

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2906)* status: 0 of 12 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry, @Itay-Tsabary-Starkware, and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OEt5LXDCfnWbmBF9wrk:-OEy4NLNAKpg0KQWCOTT:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/99092e8d600f51fe02b65da13d72dec7ee003e01/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L131)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

if the reasons for failure are the ones I wrote above:
1. "The recorder failed to write blob. Error: {}",...
2. "Failed to send a request to the recorder. Error: {}",....
</blockquote></details>

Done.

**Review by Yael-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2906)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @DvirYo-starkware)

**Review by Yael-Starkware — COMMENTED** [review]
> Reviewed 7 of 11 files at r1, 3 of 5 files at r2, 1 of 1 files at r3, 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2906)* status: 10 of 12 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry)

**Review by Yael-Starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-:-OEy85T3ED5n0spKtmjR:bnfp4nl)* status: 10 of 12 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OEt4b-d-IDiPIcYypjr:-OEy8CCw8eiL1WOTiYMg:b-kh8ll4) ([raw file](https://github.com/starkware-libs/sequencer/blob/99092e8d600f51fe02b65da13d72dec7ee003e01/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L115)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

When starting. You don't have the info from the previous height
</blockquote></details>

can you add a comment explaining that?

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2906)* status: 9 of 12 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OEt4b-d-IDiPIcYypjr:-OEyWg_e-5KVzyM7rcNv:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/99092e8d600f51fe02b65da13d72dec7ee003e01/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L115)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

can you add a comment explaining that?
</blockquote></details>

Done.

**Review by dafnamatsry — APPROVED** [review]
> Reviewed 4 of 11 files at r1, 2 of 5 files at r2, 1 of 1 files at r4, 1 of 1 files at r6, 4 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2906)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 118 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OFH5Oj793xaDKZV3MKi:-OFH5Oj793xaDKZV3MKj:undefined) ([raw file](https://github.com/starkware-libs/sequencer/blob/f1a1e3c5ca165eb17dca91be05200b53264a65b2/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L118)):*
> ```XML
>             let Some(ref blob) = *prev_height_blob.lock().await else {
>                 // This case nappen when restarting the node, `prev_height_blob` intial value in
>                 // `None`.
> ```





_Suggestion:_
```XML
                // This case happens when restarting the node, `prev_height_blob` intial value is
                // `None`.
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2906)* status: 8 of 12 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs` line 118 at r7](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-OFH5Oj793xaDKZV3MKi:-OFH6b_88ksN5Rk4FYrW:b-896fix) ([raw file](https://github.com/starkware-libs/sequencer/blob/f1a1e3c5ca165eb17dca91be05200b53264a65b2/crates/sequencing/papyrus_consensus_orchestrator/src/cende/mod.rs#L118)):*
> ```XML
>             let Some(ref blob) = *prev_height_blob.lock().await else {
>                 // This case nappen when restarting the node, `prev_height_blob` intial value in
>                 // `None`.
> ```

Done.

**Review by dafnamatsry — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/sequencer/2906#-:-OFH7Dg35hoJDr7nsJ5e:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DvirYo-starkware)

**Pull request merged**
